In [1]:
import os 
import pandas as pd
import numpy as np

os.chdir("/homes/t326h379/deepubi/download_12038_proteins/")

df_positive = pd.read_csv('Second_Final_DeepUbi_Positive_xtrimopglm_features.txt', header=None)

df_negative = pd.read_csv('Second_Final_DeepUbi_Negative_xtrimopglm_features.txt', header=None)

In [2]:
Header_name = ["PID","Position","K"] + [i for i in range(1,4353)]+["Label"]

df_positive.columns = Header_name
df_negative.columns = Header_name

In [3]:
df_positive

,PID,Position,K,1,2,3,4,5,6,7,...,4344,4345,4346,4347,4348,4349,4350,4351,4352,Label
0,P16144,1020,K,0.045898,-0.013123,0.398438,-0.416016,-0.519531,-0.035156,0.058838,...,-0.003174,-0.224609,-2.281250,-0.008545,0.435547,0.000916,-0.000492,0.010193,-0.000984,1
1,P16144,1054,K,-0.017456,-0.002792,-0.812500,-0.363281,0.628906,0.024414,0.007996,...,0.001854,0.503906,-0.500000,0.006897,0.188477,-0.004486,-0.058594,-0.017822,0.005707,1
2,P16144,1059,K,-0.018677,0.008728,0.613281,-0.435547,-0.464844,-0.060303,0.089355,...,0.001953,0.147461,-0.135742,-0.003693,-0.200195,0.024170,-0.020142,0.010010,-0.022705,1
3,P16144,1159,K,0.070312,-0.008057,1.085938,-0.122559,0.253906,-0.054199,0.094238,...,0.014771,1.703125,-1.929688,-0.007935,0.186523,-0.017212,-0.061523,0.019165,0.017090,1
4,P16144,1712,K,-0.020508,0.003937,-0.419922,-0.589844,-0.412109,-0.072754,0.035400,...,0.012207,-0.051514,0.777344,-0.001480,-0.894531,-0.005859,-0.031982,0.002731,0.004761,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44891,V5BD48,984,K,0.013123,0.003845,-0.279297,-0.314453,0.269531,-0.006134,-0.001190,...,0.000085,0.135742,-0.098633,-0.002075,0.090820,-0.005066,0.007141,-0.000288,0.011169,1
44892,V5BD66,451,K,-0.014038,0.002151,0.457031,0.082520,0.210938,-0.015869,-0.008179,...,-0.002563,0.048584,-0.652344,0.003738,-0.021851,0.002945,0.015869,0.000614,0.005554,1
44893,V5BD66,506,K,0.008850,-0.002335,-0.083496,0.259766,-0.209961,-0.016479,0.011169,...,-0.000030,0.023804,-0.570312,0.002167,-0.531250,-0.000591,-0.004761,-0.003754,-0.004730,1
44894,V5BMW2,637,K,0.008789,-0.003464,-0.275391,0.273438,0.139648,-0.003799,0.016846,...,-0.003235,0.067871,-0.417969,-0.000992,-0.108398,-0.003616,0.019287,-0.005676,-0.002701,1
44895,X6RE90,119,K,-0.009644,-0.004517,-0.375000,0.151367,0.492188,-0.005096,-0.004425,...,-0.000553,0.660156,-0.964844,0.001907,0.125977,0.009216,0.002701,-0.003403,-0.003708,1

In [4]:
df_negative

,PID,Position,K,1,2,3,4,5,6,7,...,4344,4345,4346,4347,4348,4349,4350,4351,4352,Label
0,Q5AYD5,591,K,0.141602,0.004181,0.730469,-0.429688,0.382812,0.002121,0.029907,...,0.002792,0.511719,-0.392578,-0.006531,-0.566406,-0.008057,-0.014954,0.014832,0.009277,0
1,P53336,90,K,0.060303,0.001869,0.316406,0.033936,-0.070801,-0.012573,0.007782,...,-0.000992,0.140625,-0.154297,0.002335,-0.101562,-0.005829,0.001198,-0.003052,0.003540,0
2,Q5BEV5,938,K,0.039307,-0.003296,0.519531,0.242188,-0.058838,-0.042236,0.030396,...,0.002151,0.170898,-0.433594,0.005096,0.069336,0.000097,0.006805,0.006561,-0.006073,0
3,F4JGB7,12,K,-0.000732,-0.002029,0.171875,0.157227,0.074219,0.012451,0.011841,...,0.001030,0.075684,0.033691,0.005798,-0.097168,-0.000443,0.007507,0.004883,0.007446,0
4,Q96IG2,25,K,-0.005005,-0.014709,1.468750,-0.174805,-0.115234,-0.060791,-0.009277,...,0.005707,1.101562,-1.296875,-0.009460,-0.074707,0.025757,-0.046387,0.018311,0.027954,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43225,Q5B9P3,183,K,0.009277,0.000117,0.451172,-0.073242,0.005798,-0.005676,0.002258,...,0.004059,0.392578,0.318359,0.004944,-0.404297,-0.012207,0.001236,0.011658,-0.011841,0
43226,Q5B0N6,229,K,0.019287,-0.000622,-0.024780,-0.122559,0.174805,0.006744,0.005951,...,0.004089,0.040527,-0.453125,0.000893,-0.316406,0.007996,-0.008240,-0.001671,-0.006470,0
43227,Q5T6F2,167,K,0.010010,-0.001007,-0.261719,-0.020142,0.060303,-0.017944,0.003784,...,0.010254,-0.175781,-0.574219,-0.003769,-0.180664,-0.003708,-0.047119,0.009583,0.019531,0
43228,C8VRT7,467,K,-0.002686,0.001984,0.233398,0.074707,-0.212891,-0.007324,0.004089,...,0.001472,-0.453125,0.294922,0.000021,-0.106445,0.009705,0.014709,0.002533,-0.006104,0
43229,A0A0G2JV04,110,K,-0.031006,-0.008850,0.875000,-0.333984,0.308594,-0.001465,-0.030029,...,0.011353,0.925781,-1.359375,0.005951,1.093750,0.003708,-0.025269,0.009033,0.009827,0

In [5]:
frames = [df_positive, df_negative]

Ubiquitination_training = pd.concat(frames,ignore_index = True)

df_Train_array = Ubiquitination_training.drop(["Label","PID","Position","K"],axis=1)

df_Train_array = np.array(df_Train_array)

In [6]:
X_train_full = df_Train_array

y_train_full = np.array(list(df_positive["Label"]) + list(df_negative["Label"]))

In [7]:
X_train_full.shape

(88126, 4352)

In [8]:
y_train_full.shape

(88126,)

In [9]:
import os 
import pandas as pd
import numpy as np
from tensorflow.keras.layers import Dense, MaxPooling2D, Conv2D, Flatten, \
    BatchNormalization, Activation, GlobalAveragePooling2D, DepthwiseConv2D, \
    Dropout, ReLU, Concatenate, Input, add, Conv1D, MaxPooling1D
import pandas as pd
from Bio import SeqIO
import os
import random
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv1D, Dense, MaxPooling1D, Input, Flatten, LSTM, Dropout, Bidirectional, LeakyReLU, Reshape, Lambda
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import plot_model
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.callbacks import EarlyStopping

# performance matrices
from sklearn.metrics import confusion_matrix, matthews_corrcoef, accuracy_score

# plots
import matplotlib.pyplot as plt
import numpy as np

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.callbacks import ModelCheckpoint
from numpy import array
from numpy import argmax

from tensorflow.keras.regularizers import l1, l2


from tensorflow.keras.models import Model
from tensorflow.keras.layers import Concatenate

from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_curve, roc_auc_score, classification_report, auc
from imblearn.under_sampling import RandomUnderSampler
import imblearn
a = random.sample(range(1, 1000000), 200)

2025-05-31 19:44:37.793478: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [ ]:
from imblearn.under_sampling import RandomUnderSampler

for i in range(len(a)):
    print("Seed   :", a[i])
    seed = a[i]

    rus = RandomUnderSampler(random_state = seed)
    X_train, y_train = rus.fit_resample(X_train_full,y_train_full)
    
    kfold = StratifiedKFold(n_splits=10)
    cvscores, auc_scores, sn, sp, acc, precision_Charles = list(), list(), list(), list(), list(), list()

    for train_index, test_index in kfold.split(X_train,y_train):
        xtrain, xval = X_train[train_index], X_train[test_index]

        ytrain, yval = y_train[train_index], y_train[test_index]  

        X_train_train, X_test_test, Y_train_train, Y_test_test = train_test_split(xtrain, ytrain, test_size = 0.1, random_state = 321)

        model = Sequential()

        model.add(Input(shape=(4352,)))

    #     model.add(Dense(2560, activation='relu'))
    #     model.add(Dropout(0.3))

    #     model.add(Dense(1024, activation='relu'))
    #     model.add(Dropout(0.3))

    #     model.add(Dense(256, activation='relu'))
    #     model.add(Dropout(0.3))

        model.add(Dense(32,activation='relu',name="Dense_1"))
        model.add(Dropout(0.3))

        model.add(Dense(1,activation='sigmoid',name="Dense_2"))


        model.compile(optimizer=tf.keras.optimizers.Adam(),loss="binary_crossentropy",metrics=["accuracy"])

        reduce_lr_acc = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_accuracy', factor=0.001, patience=5, verbose=1, min_delta=1e-4, mode='max')

        early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_accuracy',patience=5,mode='max')

        history = model.fit(X_train_train, Y_train_train,epochs=400,verbose=1,batch_size=256,
                                callbacks=[reduce_lr_acc, early_stopping],validation_data=(X_test_test, Y_test_test))

        Y_pred = model.predict(xval)
        y_pred = np.array([1 if x > 0.5 else 0 for x in Y_pred])

        Accurayc_laurie = accuracy_score(yval, y_pred)

        print("Independent Testing Matthews Correlation: ",matthews_corrcoef(yval, y_pred))
        print("Confusion Matrix : \n",confusion_matrix(yval, y_pred))
        print("Accuracy on test set:   ",Accurayc_laurie)

        cm = confusion_matrix(yval, y_pred)

        TP = cm[1][1]
        TN = cm[0][0]
        FP = cm[0][1]
        FN = cm[1][0]

        mcc = matthews_corrcoef(yval, y_pred)

        cvscores.append(mcc)


        Sensitivity = TP/(TP+FN)

        Specificity = TN/(TN+FP)

        sn.append(Sensitivity)
        sp.append(Specificity)

        acc.append(Accurayc_laurie)

        print("Sensitivity:   ",Sensitivity,"\t","Specificity:   ",Specificity)


        fpr, tpr, _ = roc_curve(yval, y_pred)

        roc_auc_test = auc(fpr,tpr)

        pre = TP / (TP + FP)

        print("Precision  :",pre)

        precision_Charles.append(pre)

        print("Area Under Curve:   ",roc_auc_test)

        auc_scores.append(roc_auc_test)

        print(xval.shape, yval.shape)


    print("Mean MCC = %.4f + %.4f and Mean AUC = %.4f + %.4f" % (np.mean(cvscores),np.std(cvscores),np.mean(auc_scores),np.std(auc_scores)))

    print("Mean Sensitivity = %.4f + %.4f and Mean Specificity = %.4f + %.4f and Mean Accuracy = %.4f + %.4f" % (np.mean(sn),np.std(sn),np.mean(sp),np.std(sp),np.mean(acc),np.std(acc)))

    print("Mean Precision = %.4f + %.4f" % (np.mean(precision_Charles),np.std(precision_Charles)))

    print("\n\n\n\n")

Seed   : 314901

2025-05-31 19:45:08.024965: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2027] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 8.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
2025-05-31 19:45:08.041881: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2027] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 8.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
2025-05-31 19:45:29.023174: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 22278 MB memory:  -> device: 0, name: NVIDIA A30, pci bus id: 0000:17:00.0, compute capability: 8.0

Epoch 1/400

2025-05-31 19:45:32.327016: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:630] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.

274/274 [==============================] - 10s 3ms/step - loss: 0.6075 - accuracy: 0.6660 - val_loss: 0.5691 - val_accuracy: 0.7010 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7120 - val_loss: 0.5539 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7249 - val_loss: 0.5456 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7314 - val_loss: 0.5454 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7364 - val_loss: 0.5421 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7406 - val_loss: 0.5425 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7446 - val_loss: 0.5407 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7500 - val_loss: 0.5421 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4974 - accuracy: 0.7518 - val_loss: 0.5446 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7566 - val_loss: 0.5406 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7620 - val_loss: 0.5444 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4769 - accuracy: 0.7647 - val_loss: 0.5506 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7675 - val_loss: 0.5456 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4669 - accuracy: 0.7703 - val_loss: 0.5474 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4563 - accuracy: 0.7747 - val_loss: 0.5573 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4515 - accuracy: 0.7782 - val_loss: 0.5542 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4458 - accuracy: 0.7803 - val_loss: 0.5669 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4391 - accuracy: 0.7844 - val_loss: 0.5682 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 19/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4337 - accuracy: 0.7870
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4344 - accuracy: 0.7861 - val_loss: 0.5743 - val_accuracy: 0.7141 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4136056603124987
Confusion Matrix :
 [[3065 1258]
 [1277 3046]]
Accuracy on test set:    0.7068008327550312
Sensitivity:    0.7046032847559565 	 Specificity:    0.7089983807541059
Precision  : 0.7077137546468402
Area Under Curve:    0.7068008327550312
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6152 - accuracy: 0.6589 - val_loss: 0.5683 - val_accuracy: 0.7014 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5632 - accuracy: 0.7085 - val_loss: 0.5502 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7193 - val_loss: 0.5478 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7270 - val_loss: 0.5436 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5295 - accuracy: 0.7316 - val_loss: 0.5418 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5210 - accuracy: 0.7375 - val_loss: 0.5398 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7394 - val_loss: 0.5400 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7430 - val_loss: 0.5379 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7488 - val_loss: 0.5379 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4961 - accuracy: 0.7515 - val_loss: 0.5414 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7560 - val_loss: 0.5363 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7585 - val_loss: 0.5400 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4793 - accuracy: 0.7631 - val_loss: 0.5417 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4743 - accuracy: 0.7659 - val_loss: 0.5491 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4706 - accuracy: 0.7686 - val_loss: 0.5446 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4605 - accuracy: 0.7743
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4608 - accuracy: 0.7740 - val_loss: 0.5523 - val_accuracy: 0.7197 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4214788544540079
Confusion Matrix :
 [[3089 1234]
 [1267 3056]]
Accuracy on test set:    0.7107332870691649
Sensitivity:    0.7069164931760351 	 Specificity:    0.7145500809622947
Precision  : 0.7123543123543123
Area Under Curve:    0.7107332870691648
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6036 - accuracy: 0.6685 - val_loss: 0.5629 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5549 - accuracy: 0.7149 - val_loss: 0.5530 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7233 - val_loss: 0.5588 - val_accuracy: 0.6971 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7290 - val_loss: 0.5455 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7345 - val_loss: 0.5493 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7402 - val_loss: 0.5534 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7441 - val_loss: 0.5397 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7470 - val_loss: 0.5459 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7502 - val_loss: 0.5393 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4932 - accuracy: 0.7547 - val_loss: 0.5424 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4859 - accuracy: 0.7601 - val_loss: 0.5464 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7622 - val_loss: 0.5433 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4740 - accuracy: 0.7652 - val_loss: 0.5609 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4687 - accuracy: 0.7690
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4684 - accuracy: 0.7694 - val_loss: 0.5623 - val_accuracy: 0.7195 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.4545493948293144
Confusion Matrix :
 [[3153 1170]
 [1188 3135]]
Accuracy on test set:    0.7272727272727273
Sensitivity:    0.7251908396946565 	 Specificity:    0.7293546148507981
Precision  : 0.7282229965156795
Area Under Curve:    0.7272727272727273
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6028 - accuracy: 0.6709 - val_loss: 0.5605 - val_accuracy: 0.7052 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5558 - accuracy: 0.7150 - val_loss: 0.5494 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7255 - val_loss: 0.5408 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7300 - val_loss: 0.5386 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5223 - accuracy: 0.7371 - val_loss: 0.5359 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7416 - val_loss: 0.5451 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7469 - val_loss: 0.5354 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5006 - accuracy: 0.7502 - val_loss: 0.5369 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7565 - val_loss: 0.5410 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7604 - val_loss: 0.5404 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4830 - accuracy: 0.7608 - val_loss: 0.5416 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4766 - accuracy: 0.7636 - val_loss: 0.5431 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4680 - accuracy: 0.7715 - val_loss: 0.5461 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4636 - accuracy: 0.7719
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4633 - accuracy: 0.7718 - val_loss: 0.5534 - val_accuracy: 0.7223 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.43546761794122296
Confusion Matrix :
 [[2791 1532]
 [ 927 3396]]
Accuracy on test set:    0.7155910247513301
Sensitivity:    0.7855655794587092 	 Specificity:    0.645616470043951
Precision  : 0.6891233766233766
Area Under Curve:    0.71559102475133
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5988 - accuracy: 0.6727 - val_loss: 0.5610 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5554 - accuracy: 0.7140 - val_loss: 0.5484 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7224 - val_loss: 0.5402 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7320 - val_loss: 0.5369 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5204 - accuracy: 0.7382 - val_loss: 0.5382 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7419 - val_loss: 0.5360 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7473 - val_loss: 0.5385 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7518 - val_loss: 0.5468 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7552 - val_loss: 0.5393 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7582 - val_loss: 0.5377 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 11/400
256/274 [===========================>..] - ETA: 0s - loss: 0.4790 - accuracy: 0.7647
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4799 - accuracy: 0.7640 - val_loss: 0.5374 - val_accuracy: 0.7249 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.4398938999670973
Confusion Matrix :
 [[3169 1154]
 [1268 3055]]
Accuracy on test set:    0.7198704603284756
Sensitivity:    0.7066851723340273 	 Specificity:    0.7330557483229239
Precision  : 0.7258256117842719
Area Under Curve:    0.7198704603284755
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6108 - accuracy: 0.6611 - val_loss: 0.5629 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5617 - accuracy: 0.7092 - val_loss: 0.5460 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7227 - val_loss: 0.5395 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7283 - val_loss: 0.5365 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5263 - accuracy: 0.7360 - val_loss: 0.5349 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5195 - accuracy: 0.7377 - val_loss: 0.5344 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7406 - val_loss: 0.5374 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5065 - accuracy: 0.7456 - val_loss: 0.5332 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7503 - val_loss: 0.5309 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4960 - accuracy: 0.7528 - val_loss: 0.5320 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7544 - val_loss: 0.5365 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4868 - accuracy: 0.7581 - val_loss: 0.5345 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4805 - accuracy: 0.7612 - val_loss: 0.5422 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 14/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4746 - accuracy: 0.7658 - val_loss: 0.5527 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4706 - accuracy: 0.7682
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4714 - accuracy: 0.7675 - val_loss: 0.5432 - val_accuracy: 0.7217 - lr: 0.0010
271/271 [==============================] - 0s 668us/step
Independent Testing Matthews Correlation:  0.4408026073485785
Confusion Matrix :
 [[2905 1418]
 [1008 3315]]
Accuracy on test set:    0.7194078186444599
Sensitivity:    0.7668285912560722 	 Specificity:    0.6719870460328475
Precision  : 0.7004014367208958
Area Under Curve:    0.7194078186444599
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5982 - accuracy: 0.6740 - val_loss: 0.5574 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5542 - accuracy: 0.7156 - val_loss: 0.5467 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7243 - val_loss: 0.5439 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7312 - val_loss: 0.5437 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5234 - accuracy: 0.7366 - val_loss: 0.5410 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7399 - val_loss: 0.5348 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7454 - val_loss: 0.5408 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7504 - val_loss: 0.5355 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7545 - val_loss: 0.5378 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7574 - val_loss: 0.5354 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4841 - accuracy: 0.7594
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4850 - accuracy: 0.7588 - val_loss: 0.5455 - val_accuracy: 0.7258 - lr: 0.0010
271/271 [==============================] - 0s 708us/step
Independent Testing Matthews Correlation:  0.46403707300918406
Confusion Matrix :
 [[2994 1329]
 [ 994 3329]]
Accuracy on test set:    0.731320842007865
Sensitivity:    0.7700670830441823 	 Specificity:    0.6925746009715475
Precision  : 0.71468441391155
Area Under Curve:    0.731320842007865
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6078 - accuracy: 0.6671 - val_loss: 0.5671 - val_accuracy: 0.7023 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5625 - accuracy: 0.7087 - val_loss: 0.5523 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7218 - val_loss: 0.5483 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7275 - val_loss: 0.5427 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5276 - accuracy: 0.7334 - val_loss: 0.5390 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5220 - accuracy: 0.7380 - val_loss: 0.5392 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7422 - val_loss: 0.5368 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7459 - val_loss: 0.5370 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5056 - accuracy: 0.7467 - val_loss: 0.5373 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7505 - val_loss: 0.5445 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7560 - val_loss: 0.5397 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4880 - accuracy: 0.7601 - val_loss: 0.5428 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4841 - accuracy: 0.7612
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7613 - val_loss: 0.5510 - val_accuracy: 0.7227 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.4758794510906924
Confusion Matrix :
 [[2920 1403]
 [ 878 3445]]
Accuracy on test set:    0.7361785796900301
Sensitivity:    0.7969003007170946 	 Specificity:    0.6754568586629656
Precision  : 0.710602310231023
Area Under Curve:    0.7361785796900301
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6084 - accuracy: 0.6653 - val_loss: 0.5612 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5615 - accuracy: 0.7097 - val_loss: 0.5530 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7207 - val_loss: 0.5447 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7293 - val_loss: 0.5449 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7320 - val_loss: 0.5414 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7355 - val_loss: 0.5410 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7401 - val_loss: 0.5391 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7460 - val_loss: 0.5604 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5050 - accuracy: 0.7471 - val_loss: 0.5491 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7534 - val_loss: 0.5417 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4929 - accuracy: 0.7545 - val_loss: 0.5474 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7601 - val_loss: 0.5459 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4821 - accuracy: 0.7626 - val_loss: 0.5416 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7656 - val_loss: 0.5453 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4718 - accuracy: 0.7685 - val_loss: 0.5489 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7718 - val_loss: 0.5500 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 17/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4642 - accuracy: 0.7728
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4634 - accuracy: 0.7734 - val_loss: 0.5539 - val_accuracy: 0.7240 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4571399825131445
Confusion Matrix :
 [[3364  959]
 [1398 2925]]
Accuracy on test set:    0.7273883876937312
Sensitivity:    0.6766134628730048 	 Specificity:    0.7781633125144576
Precision  : 0.7530895983522142
Area Under Curve:    0.7273883876937313
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6129 - accuracy: 0.6605 - val_loss: 0.5664 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5657 - accuracy: 0.7071 - val_loss: 0.5542 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5497 - accuracy: 0.7196 - val_loss: 0.5481 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7241 - val_loss: 0.5487 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5300 - accuracy: 0.7317 - val_loss: 0.5478 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7346 - val_loss: 0.5630 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7404 - val_loss: 0.5462 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7452 - val_loss: 0.5505 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7501 - val_loss: 0.5503 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4961 - accuracy: 0.7539 - val_loss: 0.5542 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7586 - val_loss: 0.5507 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7589 - val_loss: 0.5515 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7643 - val_loss: 0.5575 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4712 - accuracy: 0.7675 - val_loss: 0.5614 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4652 - accuracy: 0.7689 - val_loss: 0.5677 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4604 - accuracy: 0.7724 - val_loss: 0.5614 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4530 - accuracy: 0.7765 - val_loss: 0.5683 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4485 - accuracy: 0.7790 - val_loss: 0.5694 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4451 - accuracy: 0.7785 - val_loss: 0.5795 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4375 - accuracy: 0.7844 - val_loss: 0.5859 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4317 - accuracy: 0.7867 - val_loss: 0.5941 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 22/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4268 - accuracy: 0.7901
Epoch 22: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4268 - accuracy: 0.7899 - val_loss: 0.5839 - val_accuracy: 0.7120 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4737153308420967
Confusion Matrix :
 [[3332  991]
 [1289 3034]]
Accuracy on test set:    0.7362942401110341
Sensitivity:    0.7018274346518621 	 Specificity:    0.7707610455702059
Precision  : 0.7537888198757764
Area Under Curve:    0.7362942401110341
(8646, 4352) (8646,)
Mean MCC = 0.4477 + 0.0200 and Mean AUC = 0.7231 + 0.0097
Mean Sensitivity = 0.7341 + 0.0397 and Mean Specificity = 0.7121 + 0.0404 and Mean Accuracy = 0.7231 + 0.0097
Mean Precision = 0.7196 + 0.0200





Seed   : 581893
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6153 - accuracy: 0.6599 - val_loss: 0.5680 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7106 - val_loss: 0.5589 - val_accuracy: 0.7077 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7241 - val_loss: 0.5500 - val_accuracy: 0.7107 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7316 - val_loss: 0.5449 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5261 - accuracy: 0.7336 - val_loss: 0.5461 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5194 - accuracy: 0.7373 - val_loss: 0.5428 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5125 - accuracy: 0.7428 - val_loss: 0.5486 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7493 - val_loss: 0.5428 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7496 - val_loss: 0.5607 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7558 - val_loss: 0.5429 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4889 - accuracy: 0.7585
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7588 - val_loss: 0.5456 - val_accuracy: 0.7177 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.41851066546160454
Confusion Matrix :
 [[2751 1572]
 [ 960 3363]]
Accuracy on test set:    0.707147814018043
Sensitivity:    0.7779319916724496 	 Specificity:    0.6363636363636364
Precision  : 0.6814589665653495
Area Under Curve:    0.7071478140180429
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6062 - accuracy: 0.6675 - val_loss: 0.5681 - val_accuracy: 0.7048 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5562 - accuracy: 0.7126 - val_loss: 0.5606 - val_accuracy: 0.7039 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7236 - val_loss: 0.5422 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7307 - val_loss: 0.5433 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7362 - val_loss: 0.5466 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7402 - val_loss: 0.5410 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7459 - val_loss: 0.5397 - val_accuracy: 0.7182 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7521 - val_loss: 0.5403 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7518 - val_loss: 0.5427 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7587 - val_loss: 0.5398 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4795 - accuracy: 0.7624 - val_loss: 0.5456 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4728 - accuracy: 0.7660 - val_loss: 0.5505 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4677 - accuracy: 0.7714 - val_loss: 0.5479 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4637 - accuracy: 0.7703 - val_loss: 0.5581 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4551 - accuracy: 0.7775 - val_loss: 0.5593 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4524 - accuracy: 0.7774 - val_loss: 0.5553 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4455 - accuracy: 0.7805 - val_loss: 0.5598 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 18/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4384 - accuracy: 0.7843
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4387 - accuracy: 0.7842 - val_loss: 0.5704 - val_accuracy: 0.7209 - lr: 0.0010
271/271 [==============================] - 0s 671us/step
Independent Testing Matthews Correlation:  0.4369988623122015
Confusion Matrix :
 [[3002 1321]
 [1115 3208]]
Accuracy on test set:    0.7182512144344205
Sensitivity:    0.7420772611612306 	 Specificity:    0.6944251677076104
Precision  : 0.7083241333627732
Area Under Curve:    0.7182512144344206
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6030 - accuracy: 0.6690 - val_loss: 0.5639 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5568 - accuracy: 0.7138 - val_loss: 0.5531 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7234 - val_loss: 0.5516 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7290 - val_loss: 0.5451 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7334 - val_loss: 0.5419 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5211 - accuracy: 0.7363 - val_loss: 0.5358 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7418 - val_loss: 0.5388 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5062 - accuracy: 0.7458 - val_loss: 0.5339 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5025 - accuracy: 0.7462 - val_loss: 0.5356 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4954 - accuracy: 0.7524 - val_loss: 0.5358 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7554 - val_loss: 0.5375 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7601 - val_loss: 0.5430 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4770 - accuracy: 0.7633 - val_loss: 0.5421 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4732 - accuracy: 0.7663
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4736 - accuracy: 0.7658 - val_loss: 0.5439 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4400296866177742
Confusion Matrix :
 [[2749 1574]
 [ 872 3451]]
Accuracy on test set:    0.7170946102243813
Sensitivity:    0.7982882257691418 	 Specificity:    0.6359009946796206
Precision  : 0.6867661691542288
Area Under Curve:    0.7170946102243813
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6160 - accuracy: 0.6605 - val_loss: 0.5662 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7104 - val_loss: 0.5464 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7220 - val_loss: 0.5410 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7302 - val_loss: 0.5394 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5269 - accuracy: 0.7341 - val_loss: 0.5378 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5187 - accuracy: 0.7400 - val_loss: 0.5330 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7432 - val_loss: 0.5359 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7486 - val_loss: 0.5337 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4990 - accuracy: 0.7526 - val_loss: 0.5351 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7550 - val_loss: 0.5399 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7583 - val_loss: 0.5452 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7615 - val_loss: 0.5427 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4757 - accuracy: 0.7668 - val_loss: 0.5450 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4707 - accuracy: 0.7709 - val_loss: 0.5444 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4651 - accuracy: 0.7724 - val_loss: 0.5517 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4592 - accuracy: 0.7762
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4594 - accuracy: 0.7758 - val_loss: 0.5455 - val_accuracy: 0.7196 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4212851784876584
Confusion Matrix :
 [[2767 1556]
 [ 963 3360]]
Accuracy on test set:    0.7086513994910941
Sensitivity:    0.7772380291464261 	 Specificity:    0.6400647698357622
Precision  : 0.6834825061025224
Area Under Curve:    0.7086513994910942
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6001 - accuracy: 0.6732 - val_loss: 0.5579 - val_accuracy: 0.7107 - lr: 0.0010
Epoch 2/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5572 - accuracy: 0.7127 - val_loss: 0.5474 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7217 - val_loss: 0.5440 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7294 - val_loss: 0.5387 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5272 - accuracy: 0.7323 - val_loss: 0.5345 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5200 - accuracy: 0.7380 - val_loss: 0.5384 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5149 - accuracy: 0.7415 - val_loss: 0.5345 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7444 - val_loss: 0.5373 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7448 - val_loss: 0.5353 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7500 - val_loss: 0.5441 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4942 - accuracy: 0.7551 - val_loss: 0.5383 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4923 - accuracy: 0.7542
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4932 - accuracy: 0.7538 - val_loss: 0.5351 - val_accuracy: 0.7282 - lr: 0.0010
271/271 [==============================] - 0s 668us/step
Independent Testing Matthews Correlation:  0.4428191417988126
Confusion Matrix :
 [[3244 1079]
 [1333 2990]]
Accuracy on test set:    0.721027064538515
Sensitivity:    0.6916493176035161 	 Specificity:    0.7504048114735138
Precision  : 0.7348242811501597
Area Under Curve:    0.721027064538515
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6015 - accuracy: 0.6710 - val_loss: 0.5573 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5580 - accuracy: 0.7121 - val_loss: 0.5436 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7237 - val_loss: 0.5428 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7288 - val_loss: 0.5357 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7362 - val_loss: 0.5331 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7412 - val_loss: 0.5319 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7460 - val_loss: 0.5309 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7474 - val_loss: 0.5358 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7512 - val_loss: 0.5360 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4918 - accuracy: 0.7577 - val_loss: 0.5356 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4870 - accuracy: 0.7591
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7591 - val_loss: 0.5330 - val_accuracy: 0.7299 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.43725873827326567
Confusion Matrix :
 [[3143 1180]
 [1253 3070]]
Accuracy on test set:    0.7185981956974323
Sensitivity:    0.7101549849641453 	 Specificity:    0.7270414064307195
Precision  : 0.7223529411764706
Area Under Curve:    0.7185981956974323
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6081 - accuracy: 0.6667 - val_loss: 0.5635 - val_accuracy: 0.7041 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5598 - accuracy: 0.7123 - val_loss: 0.5487 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7226 - val_loss: 0.5507 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7300 - val_loss: 0.5431 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7355 - val_loss: 0.5376 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5168 - accuracy: 0.7409 - val_loss: 0.5417 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7467 - val_loss: 0.5373 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7486 - val_loss: 0.5342 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7523 - val_loss: 0.5407 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4899 - accuracy: 0.7598 - val_loss: 0.5401 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7617 - val_loss: 0.5436 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4774 - accuracy: 0.7673
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4774 - accuracy: 0.7674 - val_loss: 0.5431 - val_accuracy: 0.7282 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.44668018578982127
Confusion Matrix :
 [[3196 1127]
 [1266 3057]]
Accuracy on test set:    0.7232246125375896
Sensitivity:    0.707147814018043 	 Specificity:    0.7393014110571362
Precision  : 0.7306405353728489
Area Under Curve:    0.7232246125375899
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6081 - accuracy: 0.6672 - val_loss: 0.5614 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5619 - accuracy: 0.7093 - val_loss: 0.5504 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7198 - val_loss: 0.5465 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7275 - val_loss: 0.5379 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5272 - accuracy: 0.7341 - val_loss: 0.5490 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5220 - accuracy: 0.7377 - val_loss: 0.5324 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7398 - val_loss: 0.5335 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7452 - val_loss: 0.5362 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7478 - val_loss: 0.5308 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7506 - val_loss: 0.5309 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7556 - val_loss: 0.5338 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4865 - accuracy: 0.7574
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4865 - accuracy: 0.7571 - val_loss: 0.5357 - val_accuracy: 0.7242 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4595050093189859
Confusion Matrix :
 [[3200 1123]
 [1214 3109]]
Accuracy on test set:    0.7297015961138098
Sensitivity:    0.719176497802452 	 Specificity:    0.7402266944251678
Precision  : 0.7346408317580341
Area Under Curve:    0.7297015961138098
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6130 - accuracy: 0.6612 - val_loss: 0.5637 - val_accuracy: 0.7023 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5620 - accuracy: 0.7092 - val_loss: 0.5532 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7209 - val_loss: 0.5537 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7246 - val_loss: 0.5459 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5295 - accuracy: 0.7318 - val_loss: 0.5363 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5210 - accuracy: 0.7372 - val_loss: 0.5347 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7440 - val_loss: 0.5409 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5116 - accuracy: 0.7443 - val_loss: 0.5409 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7519 - val_loss: 0.5413 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4949 - accuracy: 0.7528 - val_loss: 0.5444 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4895 - accuracy: 0.7563
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7561 - val_loss: 0.5432 - val_accuracy: 0.7273 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.47082262133011515
Confusion Matrix :
 [[3138 1185]
 [1103 3220]]
Accuracy on test set:    0.7353689567430025
Sensitivity:    0.744853111265325 	 Specificity:    0.7258848022206801
Precision  : 0.7309875141884222
Area Under Curve:    0.7353689567430026
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6102 - accuracy: 0.6632 - val_loss: 0.5652 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5636 - accuracy: 0.7083 - val_loss: 0.5486 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5508 - accuracy: 0.7183 - val_loss: 0.5435 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7221 - val_loss: 0.5418 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7306 - val_loss: 0.5359 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5260 - accuracy: 0.7334 - val_loss: 0.5369 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7371 - val_loss: 0.5369 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5167 - accuracy: 0.7398 - val_loss: 0.5350 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7448 - val_loss: 0.5336 - val_accuracy: 0.7345 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7451 - val_loss: 0.5364 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7503 - val_loss: 0.5379 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7538 - val_loss: 0.5390 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7550 - val_loss: 0.5418 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4853 - accuracy: 0.7590
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4858 - accuracy: 0.7590 - val_loss: 0.5449 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.47066560641729593
Confusion Matrix :
 [[3579  744]
 [1583 2740]]
Accuracy on test set:    0.7308582003238492
Sensitivity:    0.6338191071015499 	 Specificity:    0.8278972935461485
Precision  : 0.7864523536165328
Area Under Curve:    0.7308582003238491
(8646, 4352) (8646,)
Mean MCC = 0.4445 + 0.0172 and Mean AUC = 0.7210 + 0.0087
Mean Sensitivity = 0.7302 + 0.0462 and Mean Specificity = 0.7118 + 0.0582 and Mean Accuracy = 0.7210 + 0.0087
Mean Precision = 0.7200 + 0.0302





Seed   : 352988
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6150 - accuracy: 0.6595 - val_loss: 0.5639 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7145 - val_loss: 0.5543 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7237 - val_loss: 0.5479 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5300 - accuracy: 0.7310 - val_loss: 0.5426 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5206 - accuracy: 0.7372 - val_loss: 0.5433 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7437 - val_loss: 0.5357 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5063 - accuracy: 0.7466 - val_loss: 0.5392 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7510 - val_loss: 0.5405 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7550 - val_loss: 0.5447 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7624 - val_loss: 0.5437 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7663 - val_loss: 0.5446 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7712 - val_loss: 0.5458 - val_accuracy: 0.7250 - lr: 0.0010

Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4651 - accuracy: 0.7723 - val_loss: 0.5432 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4602 - accuracy: 0.7768 - val_loss: 0.5501 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4529 - accuracy: 0.7794 - val_loss: 0.5434 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4445 - accuracy: 0.7851 - val_loss: 0.5534 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4394 - accuracy: 0.7881 - val_loss: 0.5483 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4342 - accuracy: 0.7907 - val_loss: 0.5676 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4281 - accuracy: 0.7954 - val_loss: 0.5545 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4213 - accuracy: 0.7972 - val_loss: 0.5633 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 21/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4191 - accuracy: 0.7979
Epoch 21: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4200 - accuracy: 0.7978 - val_loss: 0.5645 - val_accuracy: 0.7169 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.40616635518028227
Confusion Matrix :
 [[2794 1529]
 [1049 3274]]
Accuracy on test set:    0.7018274346518621
Sensitivity:    0.7573444367337497 	 Specificity:    0.6463104325699746
Precision  : 0.6816572975223818
Area Under Curve:    0.7018274346518623
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6003 - accuracy: 0.6735 - val_loss: 0.5775 - val_accuracy: 0.6955 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5571 - accuracy: 0.7120 - val_loss: 0.5566 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7220 - val_loss: 0.5515 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7299 - val_loss: 0.5438 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5277 - accuracy: 0.7342 - val_loss: 0.5449 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5223 - accuracy: 0.7374 - val_loss: 0.5412 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5125 - accuracy: 0.7430 - val_loss: 0.5502 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7448 - val_loss: 0.5393 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7492 - val_loss: 0.5401 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7510 - val_loss: 0.5428 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4947 - accuracy: 0.7531 - val_loss: 0.5420 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4890 - accuracy: 0.7577 - val_loss: 0.5385 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7602 - val_loss: 0.5465 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7642 - val_loss: 0.5488 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4713 - accuracy: 0.7682 - val_loss: 0.5439 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4641 - accuracy: 0.7720 - val_loss: 0.5596 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4597 - accuracy: 0.7739
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4601 - accuracy: 0.7740 - val_loss: 0.5607 - val_accuracy: 0.7151 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4158833943054452
Confusion Matrix :
 [[3127 1196]
 [1330 2993]]
Accuracy on test set:    0.7078417765440667
Sensitivity:    0.6923432801295397 	 Specificity:    0.7233402729585936
Precision  : 0.7144903318214371
Area Under Curve:    0.7078417765440667
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6122 - accuracy: 0.6649 - val_loss: 0.5698 - val_accuracy: 0.7055 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5605 - accuracy: 0.7096 - val_loss: 0.5599 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7216 - val_loss: 0.5466 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7281 - val_loss: 0.5473 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7351 - val_loss: 0.5437 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7402 - val_loss: 0.5449 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7445 - val_loss: 0.5437 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5008 - accuracy: 0.7490 - val_loss: 0.5436 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7523 - val_loss: 0.5579 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7549 - val_loss: 0.5438 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4809 - accuracy: 0.7620 - val_loss: 0.5428 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4745 - accuracy: 0.7654
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4743 - accuracy: 0.7650 - val_loss: 0.5516 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.44592544648608473
Confusion Matrix :
 [[2989 1334]
 [1065 3258]]
Accuracy on test set:    0.722530650011566
Sensitivity:    0.7536433032616239 	 Specificity:    0.6914179967615082
Precision  : 0.7094947735191638
Area Under Curve:    0.7225306500115659
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6081 - accuracy: 0.6628 - val_loss: 0.5698 - val_accuracy: 0.7059 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5588 - accuracy: 0.7120 - val_loss: 0.5517 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7253 - val_loss: 0.5449 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7297 - val_loss: 0.5462 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7362 - val_loss: 0.5503 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7407 - val_loss: 0.5453 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5110 - accuracy: 0.7442 - val_loss: 0.5384 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5017 - accuracy: 0.7520 - val_loss: 0.5384 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7532 - val_loss: 0.5544 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7556 - val_loss: 0.5424 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7597 - val_loss: 0.5445 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7635 - val_loss: 0.5442 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4753 - accuracy: 0.7671 - val_loss: 0.5494 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4677 - accuracy: 0.7704 - val_loss: 0.5564 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4617 - accuracy: 0.7748 - val_loss: 0.5514 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4559 - accuracy: 0.7779
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4561 - accuracy: 0.7774 - val_loss: 0.5554 - val_accuracy: 0.7217 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.44577479121207114
Confusion Matrix :
 [[2888 1435]
 [ 972 3351]]
Accuracy on test set:    0.7216053666435346
Sensitivity:    0.7751561415683553 	 Specificity:    0.6680545917187138
Precision  : 0.7001671541997493
Area Under Curve:    0.7216053666435346
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6053 - accuracy: 0.6665 - val_loss: 0.5612 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7116 - val_loss: 0.5483 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7237 - val_loss: 0.5477 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7337 - val_loss: 0.5437 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5264 - accuracy: 0.7354 - val_loss: 0.5430 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7402 - val_loss: 0.5392 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5127 - accuracy: 0.7419 - val_loss: 0.5441 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7435 - val_loss: 0.5414 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7510 - val_loss: 0.5533 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4963 - accuracy: 0.7528 - val_loss: 0.5500 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4906 - accuracy: 0.7553
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7547 - val_loss: 0.5424 - val_accuracy: 0.7235 - lr: 0.0010
271/271 [==============================] - 0s 678us/step
Independent Testing Matthews Correlation:  0.44547194055311595
Confusion Matrix :
 [[3239 1084]
 [1316 3007]]
Accuracy on test set:    0.7224149895905622
Sensitivity:    0.6955817719176498 	 Specificity:    0.7492482072634744
Precision  : 0.7350281104864337
Area Under Curve:    0.7224149895905622
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6116 - accuracy: 0.6612 - val_loss: 0.5706 - val_accuracy: 0.7029 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7108 - val_loss: 0.5484 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7194 - val_loss: 0.5455 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7288 - val_loss: 0.5461 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5274 - accuracy: 0.7344 - val_loss: 0.5430 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5197 - accuracy: 0.7384 - val_loss: 0.5327 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7430 - val_loss: 0.5398 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7448 - val_loss: 0.5380 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7518 - val_loss: 0.5362 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7506 - val_loss: 0.5443 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 11/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4915 - accuracy: 0.7541
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7540 - val_loss: 0.5397 - val_accuracy: 0.7273 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4443710368150817
Confusion Matrix :
 [[3022 1301]
 [1103 3220]]
Accuracy on test set:    0.7219523479065464
Sensitivity:    0.744853111265325 	 Specificity:    0.6990515845477677
Precision  : 0.712231807122318
Area Under Curve:    0.7219523479065464
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6075 - accuracy: 0.6683 - val_loss: 0.5623 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5580 - accuracy: 0.7118 - val_loss: 0.5486 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7228 - val_loss: 0.5428 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7307 - val_loss: 0.5387 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7352 - val_loss: 0.5389 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5191 - accuracy: 0.7402 - val_loss: 0.5377 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7437 - val_loss: 0.5480 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5056 - accuracy: 0.7471 - val_loss: 0.5371 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7521 - val_loss: 0.5355 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7551 - val_loss: 0.5352 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4859 - accuracy: 0.7593 - val_loss: 0.5366 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7620 - val_loss: 0.5447 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4762 - accuracy: 0.7661
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4762 - accuracy: 0.7659 - val_loss: 0.5409 - val_accuracy: 0.7258 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.45256096954560066
Confusion Matrix :
 [[3031 1292]
 [1077 3246]]
Accuracy on test set:    0.726000462641684
Sensitivity:    0.7508674531575295 	 Specificity:    0.7011334721258385
Precision  : 0.7152930806522697
Area Under Curve:    0.726000462641684
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6121 - accuracy: 0.6637 - val_loss: 0.5678 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7111 - val_loss: 0.5524 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7216 - val_loss: 0.5458 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7261 - val_loss: 0.5481 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7316 - val_loss: 0.5385 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5208 - accuracy: 0.7388 - val_loss: 0.5396 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7434 - val_loss: 0.5358 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7465 - val_loss: 0.5385 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7503 - val_loss: 0.5459 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4950 - accuracy: 0.7536 - val_loss: 0.5432 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4879 - accuracy: 0.7601 - val_loss: 0.5365 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7604 - val_loss: 0.5417 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4785 - accuracy: 0.7642
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4789 - accuracy: 0.7642 - val_loss: 0.5434 - val_accuracy: 0.7262 - lr: 0.0010
271/271 [==============================] - 0s 665us/step
Independent Testing Matthews Correlation:  0.4511548433990759
Confusion Matrix :
 [[3177 1146]
 [1227 3096]]
Accuracy on test set:    0.7255378209576683
Sensitivity:    0.7161693268563497 	 Specificity:    0.7349063150589868
Precision  : 0.7298444130127298
Area Under Curve:    0.7255378209576682
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6077 - accuracy: 0.6651 - val_loss: 0.5813 - val_accuracy: 0.6912 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5616 - accuracy: 0.7117 - val_loss: 0.5553 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7222 - val_loss: 0.5493 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7285 - val_loss: 0.5443 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7327 - val_loss: 0.5444 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5223 - accuracy: 0.7372 - val_loss: 0.5472 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5172 - accuracy: 0.7400 - val_loss: 0.5478 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5096 - accuracy: 0.7431 - val_loss: 0.5456 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7490 - val_loss: 0.5509 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7506 - val_loss: 0.5406 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7547 - val_loss: 0.5417 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7563 - val_loss: 0.5483 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4822 - accuracy: 0.7621 - val_loss: 0.5480 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4762 - accuracy: 0.7661 - val_loss: 0.5612 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4704 - accuracy: 0.7683 - val_loss: 0.5481 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4630 - accuracy: 0.7719 - val_loss: 0.5615 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 17/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4609 - accuracy: 0.7735
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4609 - accuracy: 0.7735 - val_loss: 0.5531 - val_accuracy: 0.7213 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4594675913745129
Confusion Matrix :
 [[3050 1273]
 [1066 3257]]
Accuracy on test set:    0.729470275271802
Sensitivity:    0.753411982419616 	 Specificity:    0.705528568123988
Precision  : 0.7189845474613686
Area Under Curve:    0.7294702752718021
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6218 - accuracy: 0.6532 - val_loss: 0.5701 - val_accuracy: 0.7026 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5668 - accuracy: 0.7047 - val_loss: 0.5546 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5533 - accuracy: 0.7163 - val_loss: 0.5601 - val_accuracy: 0.7041 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7261 - val_loss: 0.5460 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7299 - val_loss: 0.5490 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5263 - accuracy: 0.7341 - val_loss: 0.5442 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5190 - accuracy: 0.7401 - val_loss: 0.5441 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7434 - val_loss: 0.5506 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5054 - accuracy: 0.7493 - val_loss: 0.5451 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7511 - val_loss: 0.5469 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7517 - val_loss: 0.5499 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 12/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4922 - accuracy: 0.7581
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4932 - accuracy: 0.7572 - val_loss: 0.5497 - val_accuracy: 0.7137 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.5106425497606806
Confusion Matrix :
 [[3161 1162]
 [ 956 3367]]
Accuracy on test set:    0.7550312283136711
Sensitivity:    0.7788572750404812 	 Specificity:    0.731205181586861
Precision  : 0.7434312210200927
Area Under Curve:    0.7550312283136711
(8646, 4352) (8646,)
Mean MCC = 0.4477 + 0.0263 and Mean AUC = 0.7234 + 0.0133
Mean Sensitivity = 0.7418 + 0.0289 and Mean Specificity = 0.7050 + 0.0299 and Mean Accuracy = 0.7234 + 0.0133
Mean Precision = 0.7161 + 0.0167





Seed   : 547781
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6052 - accuracy: 0.6679 - val_loss: 0.5677 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7121 - val_loss: 0.5449 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7242 - val_loss: 0.5376 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5314 - accuracy: 0.7291 - val_loss: 0.5341 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7346 - val_loss: 0.5307 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7393 - val_loss: 0.5360 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7442 - val_loss: 0.5302 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7490 - val_loss: 0.5355 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7528 - val_loss: 0.5363 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7567 - val_loss: 0.5386 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4841 - accuracy: 0.7599 - val_loss: 0.5414 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4738 - accuracy: 0.7672
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4756 - accuracy: 0.7656 - val_loss: 0.5338 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4195762707313678
Confusion Matrix :
 [[2851 1472]
 [1046 3277]]
Accuracy on test set:    0.7087670599120981
Sensitivity:    0.7580383992597733 	 Specificity:    0.6594957205644228
Precision  : 0.6900400084228259
Area Under Curve:    0.708767059912098
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6086 - accuracy: 0.6652 - val_loss: 0.5643 - val_accuracy: 0.7010 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7108 - val_loss: 0.5446 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7205 - val_loss: 0.5442 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7285 - val_loss: 0.5391 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7304 - val_loss: 0.5348 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7350 - val_loss: 0.5368 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7397 - val_loss: 0.5295 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7452 - val_loss: 0.5317 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7492 - val_loss: 0.5336 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7515 - val_loss: 0.5328 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7558 - val_loss: 0.5332 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4842 - accuracy: 0.7594 - val_loss: 0.5420 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4795 - accuracy: 0.7635 - val_loss: 0.5459 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4755 - accuracy: 0.7655
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4754 - accuracy: 0.7657 - val_loss: 0.5364 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4292244659353162
Confusion Matrix :
 [[2975 1348]
 [1122 3201]]
Accuracy on test set:    0.7143187601202868
Sensitivity:    0.7404580152671756 	 Specificity:    0.6881795049733981
Precision  : 0.7036711365135194
Area Under Curve:    0.7143187601202868
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6061 - accuracy: 0.6670 - val_loss: 0.5627 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5572 - accuracy: 0.7120 - val_loss: 0.5461 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7223 - val_loss: 0.5415 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7297 - val_loss: 0.5359 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7341 - val_loss: 0.5342 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7381 - val_loss: 0.5357 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5125 - accuracy: 0.7432 - val_loss: 0.5383 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5078 - accuracy: 0.7456 - val_loss: 0.5343 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7478 - val_loss: 0.5430 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4960 - accuracy: 0.7524 - val_loss: 0.5352 - val_accuracy: 0.7223 - lr: 0.0010

Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7562 - val_loss: 0.5425 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7589 - val_loss: 0.5439 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4795 - accuracy: 0.7643 - val_loss: 0.5466 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4727 - accuracy: 0.7652 - val_loss: 0.5510 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4675 - accuracy: 0.7685 - val_loss: 0.5568 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4626 - accuracy: 0.7734 - val_loss: 0.5551 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4590 - accuracy: 0.7736
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4597 - accuracy: 0.7732 - val_loss: 0.5542 - val_accuracy: 0.7210 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4436238777461884
Confusion Matrix :
 [[2747 1576]
 [ 856 3467]]
Accuracy on test set:    0.7187138561184363
Sensitivity:    0.8019893592412677 	 Specificity:    0.6354383529956049
Precision  : 0.6874876065833829
Area Under Curve:    0.7187138561184363
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6064 - accuracy: 0.6658 - val_loss: 0.5586 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7109 - val_loss: 0.5460 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7230 - val_loss: 0.5408 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7296 - val_loss: 0.5382 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5280 - accuracy: 0.7343 - val_loss: 0.5354 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5214 - accuracy: 0.7393 - val_loss: 0.5437 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5165 - accuracy: 0.7404 - val_loss: 0.5344 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7450 - val_loss: 0.5375 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7495 - val_loss: 0.5397 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7518 - val_loss: 0.5369 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7528 - val_loss: 0.5395 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 12/400
252/274 [==========================>...] - ETA: 0s - loss: 0.4897 - accuracy: 0.7568
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4891 - accuracy: 0.7565 - val_loss: 0.5431 - val_accuracy: 0.7233 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4467609247117702
Confusion Matrix :
 [[3086 1237]
 [1155 3168]]
Accuracy on test set:    0.7233402729585936
Sensitivity:    0.732824427480916 	 Specificity:    0.7138561184362711
Precision  : 0.7191827468785471
Area Under Curve:    0.7233402729585935
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5989 - accuracy: 0.6750 - val_loss: 0.5548 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5554 - accuracy: 0.7153 - val_loss: 0.5514 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7255 - val_loss: 0.5357 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7297 - val_loss: 0.5390 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7350 - val_loss: 0.5332 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7416 - val_loss: 0.5290 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7442 - val_loss: 0.5297 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5056 - accuracy: 0.7471 - val_loss: 0.5325 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7523 - val_loss: 0.5316 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4910 - accuracy: 0.7562 - val_loss: 0.5319 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7596 - val_loss: 0.5324 - val_accuracy: 0.7346 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4778 - accuracy: 0.7632 - val_loss: 0.5342 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4712 - accuracy: 0.7687 - val_loss: 0.5431 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4666 - accuracy: 0.7726 - val_loss: 0.5473 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4611 - accuracy: 0.7742 - val_loss: 0.5406 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4519 - accuracy: 0.7777
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4519 - accuracy: 0.7776 - val_loss: 0.5531 - val_accuracy: 0.7292 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.43750263216711816
Confusion Matrix :
 [[3147 1176]
 [1256 3067]]
Accuracy on test set:    0.7187138561184363
Sensitivity:    0.7094610224381217 	 Specificity:    0.7279666897987509
Precision  : 0.7228376148951213
Area Under Curve:    0.7187138561184363
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5978 - accuracy: 0.6760 - val_loss: 0.5735 - val_accuracy: 0.7039 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7122 - val_loss: 0.5456 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7225 - val_loss: 0.5385 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7297 - val_loss: 0.5382 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5262 - accuracy: 0.7353 - val_loss: 0.5418 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5205 - accuracy: 0.7383 - val_loss: 0.5332 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7437 - val_loss: 0.5310 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5083 - accuracy: 0.7455 - val_loss: 0.5325 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7502 - val_loss: 0.5290 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4966 - accuracy: 0.7522 - val_loss: 0.5338 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7560 - val_loss: 0.5319 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4854 - accuracy: 0.7594 - val_loss: 0.5364 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4804 - accuracy: 0.7621 - val_loss: 0.5443 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4749 - accuracy: 0.7656 - val_loss: 0.5386 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7675 - val_loss: 0.5508 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4637 - accuracy: 0.7721
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4640 - accuracy: 0.7721 - val_loss: 0.5480 - val_accuracy: 0.7246 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.44481655464543457
Confusion Matrix :
 [[2936 1387]
 [1020 3303]]
Accuracy on test set:    0.7216053666435346
Sensitivity:    0.7640527411519777 	 Specificity:    0.6791579921350914
Precision  : 0.7042643923240938
Area Under Curve:    0.7216053666435347
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6017 - accuracy: 0.6713 - val_loss: 0.5709 - val_accuracy: 0.7020 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5562 - accuracy: 0.7128 - val_loss: 0.5526 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7238 - val_loss: 0.5464 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7315 - val_loss: 0.5452 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7338 - val_loss: 0.5436 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7405 - val_loss: 0.5382 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7461 - val_loss: 0.5442 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7508 - val_loss: 0.5486 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7530 - val_loss: 0.5401 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7588 - val_loss: 0.5510 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7625 - val_loss: 0.5461 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4758 - accuracy: 0.7659 - val_loss: 0.5485 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4697 - accuracy: 0.7710 - val_loss: 0.5572 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4612 - accuracy: 0.7734 - val_loss: 0.5541 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4567 - accuracy: 0.7770 - val_loss: 0.5590 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4514 - accuracy: 0.7797
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4525 - accuracy: 0.7794 - val_loss: 0.5582 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4481426286401941
Confusion Matrix :
 [[3002 1321]
 [1068 3255]]
Accuracy on test set:    0.7236872542216054
Sensitivity:    0.7529493407356003 	 Specificity:    0.6944251677076104
Precision  : 0.7113199300699301
Area Under Curve:    0.7236872542216054
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5996 - accuracy: 0.6742 - val_loss: 0.5612 - val_accuracy: 0.7077 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5563 - accuracy: 0.7117 - val_loss: 0.5540 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7233 - val_loss: 0.5441 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7303 - val_loss: 0.5426 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7351 - val_loss: 0.5426 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7402 - val_loss: 0.5381 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7478 - val_loss: 0.5400 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7515 - val_loss: 0.5371 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7542 - val_loss: 0.5421 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7596 - val_loss: 0.5445 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4811 - accuracy: 0.7627 - val_loss: 0.5471 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4725 - accuracy: 0.7681 - val_loss: 0.5459 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7691 - val_loss: 0.5459 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4605 - accuracy: 0.7744 - val_loss: 0.5628 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4569 - accuracy: 0.7762 - val_loss: 0.5524 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4517 - accuracy: 0.7788 - val_loss: 0.5633 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4445 - accuracy: 0.7839 - val_loss: 0.5700 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 18/400
252/274 [==========================>...] - ETA: 0s - loss: 0.4372 - accuracy: 0.7846
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4384 - accuracy: 0.7839 - val_loss: 0.5621 - val_accuracy: 0.7200 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.43545545768792127
Confusion Matrix :
 [[3151 1172]
 [1269 3054]]
Accuracy on test set:    0.7176729123294009
Sensitivity:    0.7064538514920194 	 Specificity:    0.7288919731667823
Precision  : 0.722669190724089
Area Under Curve:    0.7176729123294009
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6151 - accuracy: 0.6592 - val_loss: 0.5673 - val_accuracy: 0.7059 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7104 - val_loss: 0.5535 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7228 - val_loss: 0.5502 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7292 - val_loss: 0.5448 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5294 - accuracy: 0.7327 - val_loss: 0.5553 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7378 - val_loss: 0.5456 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7421 - val_loss: 0.5406 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7464 - val_loss: 0.5414 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5012 - accuracy: 0.7490 - val_loss: 0.5427 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7530 - val_loss: 0.5498 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7573 - val_loss: 0.5506 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4832 - accuracy: 0.7613 - val_loss: 0.5539 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4790 - accuracy: 0.7635 - val_loss: 0.5471 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 14/400
257/274 [===========================>..] - ETA: 0s - loss: 0.4722 - accuracy: 0.7690
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4721 - accuracy: 0.7689 - val_loss: 0.5561 - val_accuracy: 0.7255 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.46844129537546925
Confusion Matrix :
 [[3035 1288]
 [1014 3309]]
Accuracy on test set:    0.7337497108489475
Sensitivity:    0.765440666204025 	 Specificity:    0.70205875549387
Precision  : 0.7198172721340005
Area Under Curve:    0.7337497108489475
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6169 - accuracy: 0.6583 - val_loss: 0.5768 - val_accuracy: 0.6957 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5689 - accuracy: 0.7042 - val_loss: 0.5613 - val_accuracy: 0.7034 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5542 - accuracy: 0.7170 - val_loss: 0.5558 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7234 - val_loss: 0.5507 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7289 - val_loss: 0.5507 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7341 - val_loss: 0.5552 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7378 - val_loss: 0.5478 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7421 - val_loss: 0.5568 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7464 - val_loss: 0.5554 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7495 - val_loss: 0.5531 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7488 - val_loss: 0.5520 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7545 - val_loss: 0.5552 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7583 - val_loss: 0.5616 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4805 - accuracy: 0.7617
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7616 - val_loss: 0.5595 - val_accuracy: 0.7219 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.506959618340989
Confusion Matrix :
 [[3207 1116]
 [1016 3307]]
Accuracy on test set:    0.753411982419616
Sensitivity:    0.7649780245200093 	 Specificity:    0.7418459403192228
Precision  : 0.7476825683924938
Area Under Curve:    0.753411982419616
(8646, 4352) (8646,)
Mean MCC = 0.4481 + 0.0231 and Mean AUC = 0.7234 + 0.0118
Mean Sensitivity = 0.7497 + 0.0271 and Mean Specificity = 0.6971 + 0.0315 and Mean Accuracy = 0.7234 + 0.0118
Mean Precision = 0.7129 + 0.0168





Seed   : 602043
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6049 - accuracy: 0.6673 - val_loss: 0.5592 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5589 - accuracy: 0.7123 - val_loss: 0.5598 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7215 - val_loss: 0.5512 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7289 - val_loss: 0.5401 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7332 - val_loss: 0.5413 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5208 - accuracy: 0.7385 - val_loss: 0.5345 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7402 - val_loss: 0.5372 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7435 - val_loss: 0.5338 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7464 - val_loss: 0.5409 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7512 - val_loss: 0.5389 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7542 - val_loss: 0.5351 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7567 - val_loss: 0.5301 - val_accuracy: 0.7327 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4810 - accuracy: 0.7610 - val_loss: 0.5373 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4758 - accuracy: 0.7622 - val_loss: 0.5344 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4716 - accuracy: 0.7644 - val_loss: 0.5425 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4665 - accuracy: 0.7696 - val_loss: 0.5405 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 17/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4604 - accuracy: 0.7724
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4606 - accuracy: 0.7717 - val_loss: 0.5459 - val_accuracy: 0.7283 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4131972772562765
Confusion Matrix :
 [[2945 1378]
 [1161 3162]]
Accuracy on test set:    0.7063381910710155
Sensitivity:    0.7314365024288688 	 Specificity:    0.6812398797131621
Precision  : 0.6964757709251101
Area Under Curve:    0.7063381910710154
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6069 - accuracy: 0.6624 - val_loss: 0.5624 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5567 - accuracy: 0.7150 - val_loss: 0.5521 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7232 - val_loss: 0.5376 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7291 - val_loss: 0.5356 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5231 - accuracy: 0.7352 - val_loss: 0.5362 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7429 - val_loss: 0.5305 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7459 - val_loss: 0.5295 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5006 - accuracy: 0.7500 - val_loss: 0.5313 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7546 - val_loss: 0.5331 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4906 - accuracy: 0.7557 - val_loss: 0.5373 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4833 - accuracy: 0.7615
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7611 - val_loss: 0.5338 - val_accuracy: 0.7289 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4404031418923602
Confusion Matrix :
 [[2941 1382]
 [1043 3280]]
Accuracy on test set:    0.7195234790654638
Sensitivity:    0.758732361785797 	 Specificity:    0.6803145963451307
Precision  : 0.7035607035607035
Area Under Curve:    0.7195234790654639
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6032 - accuracy: 0.6695 - val_loss: 0.5591 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5557 - accuracy: 0.7138 - val_loss: 0.5452 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7253 - val_loss: 0.5398 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7316 - val_loss: 0.5449 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5256 - accuracy: 0.7348 - val_loss: 0.5366 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7421 - val_loss: 0.5399 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7436 - val_loss: 0.5314 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7491 - val_loss: 0.5372 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7527 - val_loss: 0.5371 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7551 - val_loss: 0.5354 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4852 - accuracy: 0.7589 - val_loss: 0.5319 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4805 - accuracy: 0.7633
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7625 - val_loss: 0.5373 - val_accuracy: 0.7232 - lr: 0.0010
271/271 [==============================] - 0s 667us/step
Independent Testing Matthews Correlation:  0.41963166400021157
Confusion Matrix :
 [[2683 1640]
 [ 896 3427]]
Accuracy on test set:    0.7066851723340273
Sensitivity:    0.7927365255609531 	 Specificity:    0.6206338191071016
Precision  : 0.6763370830866391
Area Under Curve:    0.7066851723340273
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6026 - accuracy: 0.6716 - val_loss: 0.5588 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7121 - val_loss: 0.5452 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7248 - val_loss: 0.5378 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7298 - val_loss: 0.5346 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7357 - val_loss: 0.5335 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7395 - val_loss: 0.5343 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7448 - val_loss: 0.5322 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7476 - val_loss: 0.5361 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7519 - val_loss: 0.5326 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7547 - val_loss: 0.5373 - val_accuracy: 0.7335 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4868 - accuracy: 0.7583 - val_loss: 0.5336 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4802 - accuracy: 0.7634 - val_loss: 0.5384 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4722 - accuracy: 0.7666 - val_loss: 0.5371 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4690 - accuracy: 0.7683 - val_loss: 0.5489 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4614 - accuracy: 0.7732
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4620 - accuracy: 0.7727 - val_loss: 0.5573 - val_accuracy: 0.7227 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4195955987440608
Confusion Matrix :
 [[2699 1624]
 [ 910 3413]]
Accuracy on test set:    0.7069164931760351
Sensitivity:    0.7894980337728429 	 Specificity:    0.6243349525792274
Precision  : 0.6775858646019456
Area Under Curve:    0.7069164931760352
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6081 - accuracy: 0.6637 - val_loss: 0.5549 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5595 - accuracy: 0.7124 - val_loss: 0.5449 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7218 - val_loss: 0.5406 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7272 - val_loss: 0.5388 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7339 - val_loss: 0.5371 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5223 - accuracy: 0.7352 - val_loss: 0.5379 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5137 - accuracy: 0.7398 - val_loss: 0.5343 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7456 - val_loss: 0.5357 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 9/400
258/274 [===========================>..] - ETA: 0s - loss: 0.5021 - accuracy: 0.7483
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7485 - val_loss: 0.5342 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.43358786973750785
Confusion Matrix :
 [[2834 1489]
 [ 973 3350]]
Accuracy on test set:    0.7152440434883183
Sensitivity:    0.7749248207263475 	 Specificity:    0.6555632662502892
Precision  : 0.6922917958255838
Area Under Curve:    0.7152440434883183
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6171 - accuracy: 0.6590 - val_loss: 0.5675 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5631 - accuracy: 0.7096 - val_loss: 0.5433 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7185 - val_loss: 0.5413 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7277 - val_loss: 0.5328 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5281 - accuracy: 0.7315 - val_loss: 0.5326 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5206 - accuracy: 0.7355 - val_loss: 0.5332 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7414 - val_loss: 0.5320 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5065 - accuracy: 0.7464 - val_loss: 0.5377 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7473 - val_loss: 0.5338 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7505 - val_loss: 0.5319 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 3ms/step - loss: 0.4917 - accuracy: 0.7541 - val_loss: 0.5322 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7576 - val_loss: 0.5298 - val_accuracy: 0.7330 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4802 - accuracy: 0.7600 - val_loss: 0.5403 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4727 - accuracy: 0.7663 - val_loss: 0.5419 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4651 - accuracy: 0.7701 - val_loss: 0.5412 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4594 - accuracy: 0.7724 - val_loss: 0.5437 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4525 - accuracy: 0.7760
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4527 - accuracy: 0.7762 - val_loss: 0.5490 - val_accuracy: 0.7223 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.44021589758979657
Confusion Matrix :
 [[2970 1353]
 [1071 3252]]
Accuracy on test set:    0.7196391394864677
Sensitivity:    0.7522553782095767 	 Specificity:    0.6870229007633588
Precision  : 0.7061889250814333
Area Under Curve:    0.7196391394864678
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6026 - accuracy: 0.6682 - val_loss: 0.5601 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5569 - accuracy: 0.7131 - val_loss: 0.5466 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7243 - val_loss: 0.5408 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7299 - val_loss: 0.5380 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5267 - accuracy: 0.7351 - val_loss: 0.5372 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7409 - val_loss: 0.5376 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7437 - val_loss: 0.5330 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7483 - val_loss: 0.5349 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7535 - val_loss: 0.5350 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4918 - accuracy: 0.7571 - val_loss: 0.5314 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7631 - val_loss: 0.5335 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4750 - accuracy: 0.7693
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4755 - accuracy: 0.7689 - val_loss: 0.5325 - val_accuracy: 0.7258 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.4501829376544583
Confusion Matrix :
 [[3060 1263]
 [1115 3208]]
Accuracy on test set:    0.7249595188526486
Sensitivity:    0.7420772611612306 	 Specificity:    0.7078417765440667
Precision  : 0.717512860657571
Area Under Curve:    0.7249595188526485
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6127 - accuracy: 0.6628 - val_loss: 0.5577 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7097 - val_loss: 0.5444 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7227 - val_loss: 0.5428 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7291 - val_loss: 0.5333 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5249 - accuracy: 0.7349 - val_loss: 0.5350 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5165 - accuracy: 0.7417 - val_loss: 0.5413 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7467 - val_loss: 0.5362 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5055 - accuracy: 0.7475 - val_loss: 0.5301 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4974 - accuracy: 0.7528 - val_loss: 0.5356 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4893 - accuracy: 0.7581 - val_loss: 0.5370 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4817 - accuracy: 0.7635 - val_loss: 0.5363 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4744 - accuracy: 0.7655 - val_loss: 0.5340 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4673 - accuracy: 0.7730 - val_loss: 0.5352 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4620 - accuracy: 0.7732 - val_loss: 0.5364 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 15/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4571 - accuracy: 0.7768
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4571 - accuracy: 0.7771 - val_loss: 0.5406 - val_accuracy: 0.7294 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.471488505981914
Confusion Matrix :
 [[3214 1109]
 [1176 3147]]
Accuracy on test set:    0.7357159380060143
Sensitivity:    0.7279666897987509 	 Specificity:    0.7434651862132778
Precision  : 0.7394266917293233
Area Under Curve:    0.7357159380060143
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6042 - accuracy: 0.6702 - val_loss: 0.5768 - val_accuracy: 0.6953 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7090 - val_loss: 0.5452 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7218 - val_loss: 0.5409 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7304 - val_loss: 0.5371 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7325 - val_loss: 0.5360 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7366 - val_loss: 0.5345 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7408 - val_loss: 0.5327 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7458 - val_loss: 0.5376 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7525 - val_loss: 0.5317 - val_accuracy: 0.7336 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4963 - accuracy: 0.7532 - val_loss: 0.5323 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7588 - val_loss: 0.5369 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7616 - val_loss: 0.5368 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4792 - accuracy: 0.7631 - val_loss: 0.5308 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 14/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4731 - accuracy: 0.7676
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4736 - accuracy: 0.7669 - val_loss: 0.5351 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4690621199454439
Confusion Matrix :
 [[3234 1089]
 [1207 3116]]
Accuracy on test set:    0.7344436733749711
Sensitivity:    0.720795743696507 	 Specificity:    0.7480916030534351
Precision  : 0.7410225921521998
Area Under Curve:    0.734443673374971
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6061 - accuracy: 0.6676 - val_loss: 0.5667 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5621 - accuracy: 0.7103 - val_loss: 0.5515 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7203 - val_loss: 0.5453 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7282 - val_loss: 0.5433 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7325 - val_loss: 0.5393 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7381 - val_loss: 0.5490 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7429 - val_loss: 0.5377 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7456 - val_loss: 0.5394 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7500 - val_loss: 0.5431 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4990 - accuracy: 0.7516 - val_loss: 0.5399 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7570 - val_loss: 0.5389 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 12/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4826 - accuracy: 0.7625
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7623 - val_loss: 0.5430 - val_accuracy: 0.7287 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4852325181761076
Confusion Matrix :
 [[3352  971]
 [1259 3064]]
Accuracy on test set:    0.7420772611612306
Sensitivity:    0.7087670599120981 	 Specificity:    0.7753874624103632
Precision  : 0.7593556381660471
Area Under Curve:    0.7420772611612306
(8646, 4352) (8646,)
Mean MCC = 0.4443 + 0.0232 and Mean AUC = 0.7212 + 0.0123
Mean Sensitivity = 0.7499 + 0.0274 and Mean Specificity = 0.6924 + 0.0493 and Mean Accuracy = 0.7212 + 0.0123
Mean Precision = 0.7110 + 0.0265





Seed   : 896851
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6085 - accuracy: 0.6658 - val_loss: 0.5683 - val_accuracy: 0.7014 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5577 - accuracy: 0.7115 - val_loss: 0.5506 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7221 - val_loss: 0.5431 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5303 - accuracy: 0.7310 - val_loss: 0.5389 - val_accuracy: 0.7230 - lr: 0.0010

Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7349 - val_loss: 0.5340 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5168 - accuracy: 0.7396 - val_loss: 0.5367 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7471 - val_loss: 0.5374 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7483 - val_loss: 0.5338 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7522 - val_loss: 0.5293 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7572 - val_loss: 0.5313 - val_accuracy: 0.7341 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7602 - val_loss: 0.5322 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7656 - val_loss: 0.5457 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4725 - accuracy: 0.7679 - val_loss: 0.5371 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4668 - accuracy: 0.7683 - val_loss: 0.5442 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 15/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4597 - accuracy: 0.7733
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4592 - accuracy: 0.7736 - val_loss: 0.5461 - val_accuracy: 0.7247 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.45280155591865967
Confusion Matrix :
 [[3056 1267]
 [1100 3223]]
Accuracy on test set:    0.7262317834836919
Sensitivity:    0.7455470737913485 	 Specificity:    0.7069164931760351
Precision  : 0.7178173719376392
Area Under Curve:    0.7262317834836919
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6119 - accuracy: 0.6597 - val_loss: 0.5679 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7078 - val_loss: 0.5564 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7214 - val_loss: 0.5442 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7285 - val_loss: 0.5444 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7337 - val_loss: 0.5409 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7399 - val_loss: 0.5419 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7446 - val_loss: 0.5389 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5008 - accuracy: 0.7486 - val_loss: 0.5433 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7511 - val_loss: 0.5382 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7556 - val_loss: 0.5354 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7612 - val_loss: 0.5445 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7636 - val_loss: 0.5410 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4712 - accuracy: 0.7651 - val_loss: 0.5655 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4614 - accuracy: 0.7722 - val_loss: 0.5522 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4552 - accuracy: 0.7746
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4553 - accuracy: 0.7745 - val_loss: 0.5585 - val_accuracy: 0.7204 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.4446272211990947
Confusion Matrix :
 [[3098 1225]
 [1176 3147]]
Accuracy on test set:    0.7222993291695582
Sensitivity:    0.7279666897987509 	 Specificity:    0.7166319685403655
Precision  : 0.719807868252516
Area Under Curve:    0.7222993291695582
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6069 - accuracy: 0.6680 - val_loss: 0.5583 - val_accuracy: 0.7070 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5568 - accuracy: 0.7129 - val_loss: 0.5553 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7249 - val_loss: 0.5395 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7278 - val_loss: 0.5414 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7339 - val_loss: 0.5446 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7392 - val_loss: 0.5464 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7434 - val_loss: 0.5352 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7504 - val_loss: 0.5413 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4949 - accuracy: 0.7534 - val_loss: 0.5353 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4880 - accuracy: 0.7598 - val_loss: 0.5340 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7596 - val_loss: 0.5372 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4754 - accuracy: 0.7666 - val_loss: 0.5426 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4725 - accuracy: 0.7678 - val_loss: 0.5374 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4648 - accuracy: 0.7708 - val_loss: 0.5425 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4579 - accuracy: 0.7753
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4584 - accuracy: 0.7750 - val_loss: 0.5462 - val_accuracy: 0.7263 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4371436425799088
Confusion Matrix :
 [[2968 1355]
 [1082 3241]]
Accuracy on test set:    0.7181355540134166
Sensitivity:    0.7497108489474902 	 Specificity:    0.686560259079343
Precision  : 0.7051784160139252
Area Under Curve:    0.7181355540134167
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6045 - accuracy: 0.6686 - val_loss: 0.5582 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 2/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7129 - val_loss: 0.5445 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7231 - val_loss: 0.5383 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7297 - val_loss: 0.5393 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5251 - accuracy: 0.7359 - val_loss: 0.5390 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5187 - accuracy: 0.7400 - val_loss: 0.5309 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7421 - val_loss: 0.5381 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7469 - val_loss: 0.5345 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7496 - val_loss: 0.5334 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4963 - accuracy: 0.7533 - val_loss: 0.5384 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4889 - accuracy: 0.7581 - val_loss: 0.5365 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7599 - val_loss: 0.5414 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4776 - accuracy: 0.7631 - val_loss: 0.5481 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4732 - accuracy: 0.7657 - val_loss: 0.5425 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7702 - val_loss: 0.5498 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4607 - accuracy: 0.7745 - val_loss: 0.5460 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4528 - accuracy: 0.7795 - val_loss: 0.5459 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 18/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4508 - accuracy: 0.7795
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4510 - accuracy: 0.7795 - val_loss: 0.5586 - val_accuracy: 0.7203 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.44010350433108225
Confusion Matrix :
 [[2880 1443]
 [ 988 3335]]
Accuracy on test set:    0.7188295165394402
Sensitivity:    0.7714550080962295 	 Specificity:    0.666204024982651
Precision  : 0.6979907911259942
Area Under Curve:    0.71882951653944
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6094 - accuracy: 0.6642 - val_loss: 0.5590 - val_accuracy: 0.7107 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5623 - accuracy: 0.7089 - val_loss: 0.5461 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7204 - val_loss: 0.5400 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7272 - val_loss: 0.5399 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5267 - accuracy: 0.7333 - val_loss: 0.5464 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5220 - accuracy: 0.7366 - val_loss: 0.5326 - val_accuracy: 0.7335 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7415 - val_loss: 0.5330 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7453 - val_loss: 0.5420 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7489 - val_loss: 0.5317 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7515 - val_loss: 0.5337 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4910 - accuracy: 0.7551
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7551 - val_loss: 0.5283 - val_accuracy: 0.7295 - lr: 0.0010
271/271 [==============================] - 0s 673us/step
Independent Testing Matthews Correlation:  0.43011456916097096
Confusion Matrix :
 [[3135 1188]
 [1276 3047]]
Accuracy on test set:    0.7150127226463104
Sensitivity:    0.7048346055979644 	 Specificity:    0.7251908396946565
Precision  : 0.7194805194805195
Area Under Curve:    0.7150127226463104
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6144 - accuracy: 0.6605 - val_loss: 0.5594 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5632 - accuracy: 0.7097 - val_loss: 0.5461 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7210 - val_loss: 0.5412 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7300 - val_loss: 0.5348 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7323 - val_loss: 0.5318 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5199 - accuracy: 0.7367 - val_loss: 0.5328 - val_accuracy: 0.7339 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7425 - val_loss: 0.5305 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7470 - val_loss: 0.5399 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5009 - accuracy: 0.7505 - val_loss: 0.5277 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7550 - val_loss: 0.5326 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 11/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4887 - accuracy: 0.7570
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7562 - val_loss: 0.5351 - val_accuracy: 0.7295 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.43897722168014114
Confusion Matrix :
 [[2912 1411]
 [1022 3301]]
Accuracy on test set:    0.7185981956974323
Sensitivity:    0.7635900994679621 	 Specificity:    0.6736062919269026
Precision  : 0.7005517826825127
Area Under Curve:    0.7185981956974323
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6084 - accuracy: 0.6646 - val_loss: 0.5613 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7105 - val_loss: 0.5470 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7204 - val_loss: 0.5415 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7284 - val_loss: 0.5392 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7329 - val_loss: 0.5381 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5172 - accuracy: 0.7407 - val_loss: 0.5352 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7444 - val_loss: 0.5397 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7474 - val_loss: 0.5328 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5002 - accuracy: 0.7516 - val_loss: 0.5340 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7564 - val_loss: 0.5411 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4860 - accuracy: 0.7581 - val_loss: 0.5532 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7635 - val_loss: 0.5442 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4718 - accuracy: 0.7685
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4725 - accuracy: 0.7682 - val_loss: 0.5412 - val_accuracy: 0.7255 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.4544639698335252
Confusion Matrix :
 [[3199 1124]
 [1235 3088]]
Accuracy on test set:    0.7271570668517233
Sensitivity:    0.7143187601202868 	 Specificity:    0.7399953735831598
Precision  : 0.7331433998100665
Area Under Curve:    0.7271570668517233
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6130 - accuracy: 0.6608 - val_loss: 0.5652 - val_accuracy: 0.7029 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5640 - accuracy: 0.7077 - val_loss: 0.5476 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5502 - accuracy: 0.7198 - val_loss: 0.5443 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7246 - val_loss: 0.5430 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7290 - val_loss: 0.5372 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7333 - val_loss: 0.5363 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7398 - val_loss: 0.5350 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7426 - val_loss: 0.5394 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7436 - val_loss: 0.5358 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7478 - val_loss: 0.5377 - val_accuracy: 0.7348 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7548 - val_loss: 0.5396 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4902 - accuracy: 0.7560 - val_loss: 0.5410 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7581 - val_loss: 0.5480 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4815 - accuracy: 0.7595 - val_loss: 0.5506 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4750 - accuracy: 0.7638
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4750 - accuracy: 0.7641 - val_loss: 0.5479 - val_accuracy: 0.7253 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.45780015058812534
Confusion Matrix :
 [[2952 1371]
 [ 981 3342]]
Accuracy on test set:    0.7279666897987509
Sensitivity:    0.7730742539902845 	 Specificity:    0.6828591256072172
Precision  : 0.709102482495226
Area Under Curve:    0.7279666897987508
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6141 - accuracy: 0.6589 - val_loss: 0.5674 - val_accuracy: 0.7038 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5654 - accuracy: 0.7080 - val_loss: 0.5542 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5508 - accuracy: 0.7199 - val_loss: 0.5478 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7262 - val_loss: 0.5406 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7304 - val_loss: 0.5414 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5234 - accuracy: 0.7362 - val_loss: 0.5347 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7393 - val_loss: 0.5360 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7458 - val_loss: 0.5321 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7484 - val_loss: 0.5325 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7526 - val_loss: 0.5366 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7544 - val_loss: 0.5346 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4868 - accuracy: 0.7591 - val_loss: 0.5408 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4801 - accuracy: 0.7631
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4802 - accuracy: 0.7628 - val_loss: 0.5443 - val_accuracy: 0.7282 - lr: 0.0010
271/271 [==============================] - 0s 671us/step
Independent Testing Matthews Correlation:  0.48194962120248763
Confusion Matrix :
 [[3044 1279]
 [ 966 3357]]
Accuracy on test set:    0.7403423548461716
Sensitivity:    0.7765440666204025 	 Specificity:    0.7041406430719408
Precision  : 0.7241156169111302
Area Under Curve:    0.7403423548461716
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6070 - accuracy: 0.6664 - val_loss: 0.5649 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5629 - accuracy: 0.7092 - val_loss: 0.5458 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7192 - val_loss: 0.5459 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7255 - val_loss: 0.5396 - val_accuracy: 0.7340 - lr: 0.0010
Epoch 5/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7330 - val_loss: 0.5371 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7351 - val_loss: 0.5336 - val_accuracy: 0.7350 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7405 - val_loss: 0.5346 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5110 - accuracy: 0.7446 - val_loss: 0.5364 - val_accuracy: 0.7348 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7482 - val_loss: 0.5395 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7515 - val_loss: 0.5338 - val_accuracy: 0.7353 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7556 - val_loss: 0.5381 - val_accuracy: 0.7336 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4864 - accuracy: 0.7587 - val_loss: 0.5443 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4810 - accuracy: 0.7628 - val_loss: 0.5377 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4726 - accuracy: 0.7694 - val_loss: 0.5456 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 15/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4682 - accuracy: 0.7708
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4692 - accuracy: 0.7705 - val_loss: 0.5636 - val_accuracy: 0.7179 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4908441631870525
Confusion Matrix :
 [[2998 1325]
 [ 887 3436]]
Accuracy on test set:    0.7441591487393014
Sensitivity:    0.7948184131390238 	 Specificity:    0.693499884339579
Precision  : 0.7216971224532661
Area Under Curve:    0.7441591487393013
(8646, 4352) (8646,)
Mean MCC = 0.4529 + 0.0187 and Mean AUC = 0.7259 + 0.0092
Mean Sensitivity = 0.7522 + 0.0277 and Mean Specificity = 0.6996 + 0.0222 and Mean Accuracy = 0.7259 + 0.0092
Mean Precision = 0.7149 + 0.0107





Seed   : 440836
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6038 - accuracy: 0.6676 - val_loss: 0.5646 - val_accuracy: 0.7014 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5558 - accuracy: 0.7135 - val_loss: 0.5492 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7257 - val_loss: 0.5372 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5301 - accuracy: 0.7292 - val_loss: 0.5398 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5206 - accuracy: 0.7378 - val_loss: 0.5421 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5146 - accuracy: 0.7406 - val_loss: 0.5323 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7468 - val_loss: 0.5289 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7473 - val_loss: 0.5296 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7554 - val_loss: 0.5305 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7567 - val_loss: 0.5344 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4823 - accuracy: 0.7629
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7628 - val_loss: 0.5329 - val_accuracy: 0.7286 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4210023232917358
Confusion Matrix :
 [[2909 1414]
 [1094 3229]]
Accuracy on test set:    0.7099236641221374
Sensitivity:    0.7469349988433958 	 Specificity:    0.672912329400879
Precision  : 0.6954555244454017
Area Under Curve:    0.7099236641221374
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6008 - accuracy: 0.6701 - val_loss: 0.5630 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5546 - accuracy: 0.7126 - val_loss: 0.5544 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7226 - val_loss: 0.5422 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5317 - accuracy: 0.7292 - val_loss: 0.5402 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7351 - val_loss: 0.5361 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7393 - val_loss: 0.5318 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7437 - val_loss: 0.5343 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7483 - val_loss: 0.5437 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7521 - val_loss: 0.5355 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7550 - val_loss: 0.5343 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4875 - accuracy: 0.7587
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4868 - accuracy: 0.7587 - val_loss: 0.5348 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.44221644469215704
Confusion Matrix :
 [[2907 1416]
 [1004 3319]]
Accuracy on test set:    0.7201017811704835
Sensitivity:    0.7677538746241036 	 Specificity:    0.6724496877168633
Precision  : 0.7009503695881731
Area Under Curve:    0.7201017811704835
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6135 - accuracy: 0.6584 - val_loss: 0.5645 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5630 - accuracy: 0.7069 - val_loss: 0.5529 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7223 - val_loss: 0.5457 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5369 - accuracy: 0.7273 - val_loss: 0.5425 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7336 - val_loss: 0.5405 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7375 - val_loss: 0.5381 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7418 - val_loss: 0.5354 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7462 - val_loss: 0.5359 - val_accuracy: 0.7215 - lr: 0.0010

Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7491 - val_loss: 0.5335 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4932 - accuracy: 0.7538 - val_loss: 0.5379 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4852 - accuracy: 0.7597 - val_loss: 0.5345 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4818 - accuracy: 0.7608 - val_loss: 0.5392 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4722 - accuracy: 0.7665 - val_loss: 0.5422 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4676 - accuracy: 0.7705
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7698 - val_loss: 0.5384 - val_accuracy: 0.7223 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.44055665870249716
Confusion Matrix :
 [[2860 1463]
 [ 968 3355]]
Accuracy on test set:    0.7188295165394402
Sensitivity:    0.7760814249363868 	 Specificity:    0.6615776081424937
Precision  : 0.6963470319634704
Area Under Curve:    0.7188295165394402
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6110 - accuracy: 0.6595 - val_loss: 0.5617 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7097 - val_loss: 0.5480 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7228 - val_loss: 0.5422 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7280 - val_loss: 0.5402 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5274 - accuracy: 0.7323 - val_loss: 0.5387 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7397 - val_loss: 0.5413 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7431 - val_loss: 0.5426 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5062 - accuracy: 0.7475 - val_loss: 0.5363 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7521 - val_loss: 0.5384 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7556 - val_loss: 0.5418 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4861 - accuracy: 0.7580 - val_loss: 0.5424 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4793 - accuracy: 0.7626 - val_loss: 0.5391 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7641 - val_loss: 0.5440 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4677 - accuracy: 0.7699 - val_loss: 0.5437 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4624 - accuracy: 0.7726 - val_loss: 0.5432 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4559 - accuracy: 0.7772 - val_loss: 0.5529 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4528 - accuracy: 0.7773 - val_loss: 0.5499 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4444 - accuracy: 0.7814 - val_loss: 0.5579 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 19/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4385 - accuracy: 0.7860
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4387 - accuracy: 0.7860 - val_loss: 0.5616 - val_accuracy: 0.7219 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.43152673882998
Confusion Matrix :
 [[2897 1426]
 [1039 3284]]
Accuracy on test set:    0.7148970622253065
Sensitivity:    0.7596576451538284 	 Specificity:    0.6701364792967847
Precision  : 0.6972399150743099
Area Under Curve:    0.7148970622253065
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6086 - accuracy: 0.6671 - val_loss: 0.5563 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5590 - accuracy: 0.7130 - val_loss: 0.5406 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7227 - val_loss: 0.5409 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7322 - val_loss: 0.5342 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5256 - accuracy: 0.7340 - val_loss: 0.5307 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5189 - accuracy: 0.7391 - val_loss: 0.5284 - val_accuracy: 0.7328 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7450 - val_loss: 0.5303 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5054 - accuracy: 0.7467 - val_loss: 0.5298 - val_accuracy: 0.7363 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7488 - val_loss: 0.5303 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7571 - val_loss: 0.5364 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7591 - val_loss: 0.5354 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4811 - accuracy: 0.7599 - val_loss: 0.5493 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 13/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4734 - accuracy: 0.7656
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4744 - accuracy: 0.7650 - val_loss: 0.5393 - val_accuracy: 0.7236 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.42764376425809786
Confusion Matrix :
 [[2872 1451]
 [1032 3291]]
Accuracy on test set:    0.7128151746472358
Sensitivity:    0.7612768910478834 	 Specificity:    0.664353458246588
Precision  : 0.6940109658371995
Area Under Curve:    0.7128151746472358
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6139 - accuracy: 0.6585 - val_loss: 0.5557 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7090 - val_loss: 0.5466 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7219 - val_loss: 0.5404 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7281 - val_loss: 0.5308 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 5/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7375 - val_loss: 0.5314 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7403 - val_loss: 0.5299 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5110 - accuracy: 0.7446 - val_loss: 0.5340 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7477 - val_loss: 0.5310 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7524 - val_loss: 0.5368 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7562 - val_loss: 0.5327 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4827 - accuracy: 0.7617
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7617 - val_loss: 0.5449 - val_accuracy: 0.7178 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4290110270088181
Confusion Matrix :
 [[3434  889]
 [1605 2718]]
Accuracy on test set:    0.7115429100161924
Sensitivity:    0.6287300485773768 	 Specificity:    0.7943557714550081
Precision  : 0.7535347934571667
Area Under Curve:    0.7115429100161925
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6044 - accuracy: 0.6680 - val_loss: 0.5591 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5598 - accuracy: 0.7115 - val_loss: 0.5458 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7218 - val_loss: 0.5397 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7272 - val_loss: 0.5356 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7338 - val_loss: 0.5379 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7401 - val_loss: 0.5327 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7405 - val_loss: 0.5345 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7445 - val_loss: 0.5343 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5056 - accuracy: 0.7483 - val_loss: 0.5353 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7512 - val_loss: 0.5307 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4938 - accuracy: 0.7556 - val_loss: 0.5366 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4875 - accuracy: 0.7572 - val_loss: 0.5406 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4854 - accuracy: 0.7605
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7607 - val_loss: 0.5361 - val_accuracy: 0.7241 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.4536640823223136
Confusion Matrix :
 [[2866 1457]
 [ 920 3403]]
Accuracy on test set:    0.7250751792736525
Sensitivity:    0.7871848253527642 	 Specificity:    0.6629655331945409
Precision  : 0.7002057613168724
Area Under Curve:    0.7250751792736525
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6068 - accuracy: 0.6647 - val_loss: 0.5622 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5598 - accuracy: 0.7139 - val_loss: 0.5467 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7220 - val_loss: 0.5462 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7287 - val_loss: 0.5394 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7345 - val_loss: 0.5364 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5196 - accuracy: 0.7405 - val_loss: 0.5372 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7422 - val_loss: 0.5349 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7466 - val_loss: 0.5337 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7512 - val_loss: 0.5332 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4960 - accuracy: 0.7545 - val_loss: 0.5442 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
256/274 [===========================>..] - ETA: 0s - loss: 0.4868 - accuracy: 0.7596
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7591 - val_loss: 0.5346 - val_accuracy: 0.7271 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.46126061794835116
Confusion Matrix :
 [[3060 1263]
 [1068 3255]]
Accuracy on test set:    0.7303955586398334
Sensitivity:    0.7529493407356003 	 Specificity:    0.7078417765440667
Precision  : 0.7204515272244356
Area Under Curve:    0.7303955586398334
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6093 - accuracy: 0.6667 - val_loss: 0.5653 - val_accuracy: 0.7038 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5616 - accuracy: 0.7085 - val_loss: 0.5555 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7250 - val_loss: 0.5499 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7305 - val_loss: 0.5446 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5260 - accuracy: 0.7352 - val_loss: 0.5407 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7368 - val_loss: 0.5435 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5141 - accuracy: 0.7421 - val_loss: 0.5546 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7450 - val_loss: 0.5528 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7517 - val_loss: 0.5501 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7557 - val_loss: 0.5433 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4851 - accuracy: 0.7599 - val_loss: 0.5445 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4786 - accuracy: 0.7642 - val_loss: 0.5437 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4699 - accuracy: 0.7698 - val_loss: 0.5498 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4662 - accuracy: 0.7704 - val_loss: 0.5501 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4597 - accuracy: 0.7734 - val_loss: 0.5604 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4523 - accuracy: 0.7778
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4534 - accuracy: 0.7773 - val_loss: 0.5620 - val_accuracy: 0.7114 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4593726099379412
Confusion Matrix :
 [[2883 1440]
 [ 912 3411]]
Accuracy on test set:    0.7279666897987509
Sensitivity:    0.7890353920888272 	 Specificity:    0.6668979875086746
Precision  : 0.7031539888682746
Area Under Curve:    0.7279666897987509
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6114 - accuracy: 0.6637 - val_loss: 0.5713 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5649 - accuracy: 0.7074 - val_loss: 0.5556 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5503 - accuracy: 0.7203 - val_loss: 0.5578 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7242 - val_loss: 0.5478 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7322 - val_loss: 0.5454 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5269 - accuracy: 0.7342 - val_loss: 0.5430 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5197 - accuracy: 0.7381 - val_loss: 0.5464 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7414 - val_loss: 0.5443 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7452 - val_loss: 0.5487 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7498 - val_loss: 0.5428 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7504 - val_loss: 0.5468 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7542 - val_loss: 0.5459 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4862 - accuracy: 0.7574
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4855 - accuracy: 0.7580 - val_loss: 0.5543 - val_accuracy: 0.7195 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.5145839070514151
Confusion Matrix :
 [[3150 1173]
 [ 929 3394]]
Accuracy on test set:    0.756881795049734
Sensitivity:    0.7851029377746935 	 Specificity:    0.7286606523247745
Precision  : 0.7431574337639588
Area Under Curve:    0.7568817950497341
(8646, 4352) (8646,)
Mean MCC = 0.4481 + 0.0258 and Mean AUC = 0.7228 + 0.0131
Mean Sensitivity = 0.7555 + 0.0445 and Mean Specificity = 0.6902 + 0.0405 and Mean Accuracy = 0.7228 + 0.0131
Mean Precision = 0.7105 + 0.0204





Seed   : 845585
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6055 - accuracy: 0.6672 - val_loss: 0.5689 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5619 - accuracy: 0.7075 - val_loss: 0.5572 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7186 - val_loss: 0.5462 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7258 - val_loss: 0.5470 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5278 - accuracy: 0.7324 - val_loss: 0.5426 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5218 - accuracy: 0.7381 - val_loss: 0.5430 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5157 - accuracy: 0.7415 - val_loss: 0.5382 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7437 - val_loss: 0.5374 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5052 - accuracy: 0.7456 - val_loss: 0.5365 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7500 - val_loss: 0.5483 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7515 - val_loss: 0.5401 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7556 - val_loss: 0.5410 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4839 - accuracy: 0.7585 - val_loss: 0.5436 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4770 - accuracy: 0.7609 - val_loss: 0.5500 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4735 - accuracy: 0.7662 - val_loss: 0.5529 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4720 - accuracy: 0.7654 - val_loss: 0.5551 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4656 - accuracy: 0.7698 - val_loss: 0.5566 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4596 - accuracy: 0.7735
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4599 - accuracy: 0.7732 - val_loss: 0.5553 - val_accuracy: 0.7200 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4216426909797424
Confusion Matrix :
 [[2977 1346]
 [1156 3167]]
Accuracy on test set:    0.710617626648161
Sensitivity:    0.7325931066389082 	 Specificity:    0.6886421466574139
Precision  : 0.7017504985597164
Area Under Curve:    0.7106176266481611
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6239 - accuracy: 0.6507 - val_loss: 0.5725 - val_accuracy: 0.7016 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5669 - accuracy: 0.7053 - val_loss: 0.5559 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5507 - accuracy: 0.7187 - val_loss: 0.5581 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7264 - val_loss: 0.5446 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7315 - val_loss: 0.5444 - val_accuracy: 0.7274 - lr: 0.0010

Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7355 - val_loss: 0.5482 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7385 - val_loss: 0.5524 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7428 - val_loss: 0.5456 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7459 - val_loss: 0.5412 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5015 - accuracy: 0.7484 - val_loss: 0.5440 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7519 - val_loss: 0.5480 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7536 - val_loss: 0.5473 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4851 - accuracy: 0.7595 - val_loss: 0.5476 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4793 - accuracy: 0.7623
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4791 - accuracy: 0.7628 - val_loss: 0.5543 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.43576433292218086
Confusion Matrix :
 [[3220 1103]
 [1339 2984]]
Accuracy on test set:    0.7175572519083969
Sensitivity:    0.6902613925514689 	 Specificity:    0.744853111265325
Precision  : 0.7301198923415708
Area Under Curve:    0.7175572519083969
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6020 - accuracy: 0.6712 - val_loss: 0.5638 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5563 - accuracy: 0.7121 - val_loss: 0.5510 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7238 - val_loss: 0.5443 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7299 - val_loss: 0.5440 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7366 - val_loss: 0.5438 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5195 - accuracy: 0.7385 - val_loss: 0.5405 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7436 - val_loss: 0.5351 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7478 - val_loss: 0.5376 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7494 - val_loss: 0.5391 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7546 - val_loss: 0.5420 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4851 - accuracy: 0.7580 - val_loss: 0.5392 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 12/400
252/274 [==========================>...] - ETA: 0s - loss: 0.4794 - accuracy: 0.7627
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 3ms/step - loss: 0.4795 - accuracy: 0.7627 - val_loss: 0.5524 - val_accuracy: 0.7265 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.45551300536831735
Confusion Matrix :
 [[2933 1390]
 [ 973 3350]]
Accuracy on test set:    0.7266944251677077
Sensitivity:    0.7749248207263475 	 Specificity:    0.6784640296090678
Precision  : 0.7067510548523207
Area Under Curve:    0.7266944251677077
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6077 - accuracy: 0.6663 - val_loss: 0.5660 - val_accuracy: 0.7002 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5572 - accuracy: 0.7128 - val_loss: 0.5528 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7248 - val_loss: 0.5616 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7327 - val_loss: 0.5377 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7366 - val_loss: 0.5362 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7412 - val_loss: 0.5380 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7464 - val_loss: 0.5406 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7492 - val_loss: 0.5407 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7544 - val_loss: 0.5454 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7569 - val_loss: 0.5355 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7601 - val_loss: 0.5438 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4791 - accuracy: 0.7629 - val_loss: 0.5471 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4716 - accuracy: 0.7691 - val_loss: 0.5429 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4676 - accuracy: 0.7706 - val_loss: 0.5474 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 15/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4603 - accuracy: 0.7747
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4607 - accuracy: 0.7739 - val_loss: 0.5456 - val_accuracy: 0.7241 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4353635416366243
Confusion Matrix :
 [[3122 1201]
 [1240 3083]]
Accuracy on test set:    0.7176729123294009
Sensitivity:    0.7131621559102476 	 Specificity:    0.7221836687485542
Precision  : 0.7196545284780579
Area Under Curve:    0.7176729123294009
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6062 - accuracy: 0.6695 - val_loss: 0.5658 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7112 - val_loss: 0.5763 - val_accuracy: 0.6940 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7218 - val_loss: 0.5507 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5319 - accuracy: 0.7293 - val_loss: 0.5428 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7357 - val_loss: 0.5406 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7412 - val_loss: 0.5433 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7458 - val_loss: 0.5427 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7493 - val_loss: 0.5391 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7538 - val_loss: 0.5422 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7576 - val_loss: 0.5547 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7601 - val_loss: 0.5437 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4778 - accuracy: 0.7626 - val_loss: 0.5533 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4702 - accuracy: 0.7690 - val_loss: 0.5524 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4624 - accuracy: 0.7731 - val_loss: 0.5545 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4566 - accuracy: 0.7763 - val_loss: 0.5491 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4508 - accuracy: 0.7804 - val_loss: 0.5544 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4445 - accuracy: 0.7836 - val_loss: 0.5575 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 18/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4370 - accuracy: 0.7890
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4373 - accuracy: 0.7884 - val_loss: 0.5715 - val_accuracy: 0.7165 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.426366999190706
Confusion Matrix :
 [[2722 1601]
 [ 903 3420]]
Accuracy on test set:    0.7103863058061531
Sensitivity:    0.7911172796668979 	 Specificity:    0.6296553319454082
Precision  : 0.6811392152957578
Area Under Curve:    0.7103863058061531
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6036 - accuracy: 0.6685 - val_loss: 0.5609 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5584 - accuracy: 0.7113 - val_loss: 0.5586 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7235 - val_loss: 0.5452 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7318 - val_loss: 0.5378 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7342 - val_loss: 0.5347 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7388 - val_loss: 0.5393 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5137 - accuracy: 0.7440 - val_loss: 0.5318 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7473 - val_loss: 0.5453 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7508 - val_loss: 0.5369 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7513 - val_loss: 0.5442 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7545 - val_loss: 0.5336 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4878 - accuracy: 0.7592 - val_loss: 0.5389 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4837 - accuracy: 0.7594 - val_loss: 0.5515 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4770 - accuracy: 0.7630 - val_loss: 0.5415 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4719 - accuracy: 0.7669 - val_loss: 0.5412 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4658 - accuracy: 0.7717
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4666 - accuracy: 0.7712 - val_loss: 0.5476 - val_accuracy: 0.7282 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4321758936857951
Confusion Matrix :
 [[3134 1189]
 [1266 3057]]
Accuracy on test set:    0.7160536664353458
Sensitivity:    0.707147814018043 	 Specificity:    0.7249595188526486
Precision  : 0.7199717381064531
Area Under Curve:    0.7160536664353458
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6186 - accuracy: 0.6522 - val_loss: 0.5796 - val_accuracy: 0.7001 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5659 - accuracy: 0.7079 - val_loss: 0.5566 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7209 - val_loss: 0.5487 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7260 - val_loss: 0.5551 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7344 - val_loss: 0.5416 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5197 - accuracy: 0.7366 - val_loss: 0.5423 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7406 - val_loss: 0.5422 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7468 - val_loss: 0.5436 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7498 - val_loss: 0.5421 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7559 - val_loss: 0.5483 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7563 - val_loss: 0.5512 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7597 - val_loss: 0.5501 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 13/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4768 - accuracy: 0.7645
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7647 - val_loss: 0.5633 - val_accuracy: 0.7143 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4490177712364257
Confusion Matrix :
 [[2788 1535]
 [ 870 3453]]
Accuracy on test set:    0.7218366874855424
Sensitivity:    0.7987508674531575 	 Specificity:    0.6449225075179273
Precision  : 0.692261427425822
Area Under Curve:    0.7218366874855424
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6000 - accuracy: 0.6728 - val_loss: 0.5612 - val_accuracy: 0.7038 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7146 - val_loss: 0.5528 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7237 - val_loss: 0.5455 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7285 - val_loss: 0.5418 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7369 - val_loss: 0.5420 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7408 - val_loss: 0.5380 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5096 - accuracy: 0.7454 - val_loss: 0.5390 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7487 - val_loss: 0.5409 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7524 - val_loss: 0.5455 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7564 - val_loss: 0.5428 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 11/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4850 - accuracy: 0.7599
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7599 - val_loss: 0.5414 - val_accuracy: 0.7186 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.45256384603622174
Confusion Matrix :
 [[3185 1138]
 [1229 3094]]
Accuracy on test set:    0.7262317834836919
Sensitivity:    0.715706685172334 	 Specificity:    0.7367568817950497
Precision  : 0.7310964083175804
Area Under Curve:    0.7262317834836919
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6062 - accuracy: 0.6671 - val_loss: 0.5672 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5619 - accuracy: 0.7085 - val_loss: 0.5590 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7225 - val_loss: 0.5490 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7259 - val_loss: 0.5449 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7333 - val_loss: 0.5403 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7359 - val_loss: 0.5410 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5165 - accuracy: 0.7406 - val_loss: 0.5449 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7445 - val_loss: 0.5417 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7492 - val_loss: 0.5425 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4970 - accuracy: 0.7530 - val_loss: 0.5386 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4933 - accuracy: 0.7552 - val_loss: 0.5397 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4878 - accuracy: 0.7582 - val_loss: 0.5465 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7587 - val_loss: 0.5454 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4756 - accuracy: 0.7657 - val_loss: 0.5459 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7675 - val_loss: 0.5490 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4656 - accuracy: 0.7695 - val_loss: 0.5564 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4610 - accuracy: 0.7732 - val_loss: 0.5576 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4545 - accuracy: 0.7758 - val_loss: 0.5658 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4511 - accuracy: 0.7761 - val_loss: 0.5657 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4476 - accuracy: 0.7794 - val_loss: 0.5714 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4402 - accuracy: 0.7829 - val_loss: 0.5708 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 22/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4388 - accuracy: 0.7838 - val_loss: 0.5715 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 23/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4304 - accuracy: 0.7892 - val_loss: 0.5836 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 24/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4252 - accuracy: 0.7909 - val_loss: 0.5929 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 25/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4240 - accuracy: 0.7920
Epoch 25: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4244 - accuracy: 0.7918 - val_loss: 0.5764 - val_accuracy: 0.7253 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4678524408882512
Confusion Matrix :
 [[3343  980]
 [1327 2996]]
Accuracy on test set:    0.7331714087439278
Sensitivity:    0.6930372426555632 	 Specificity:    0.7733055748322923
Precision  : 0.7535211267605634
Area Under Curve:    0.7331714087439277
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6155 - accuracy: 0.6576 - val_loss: 0.5673 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5646 - accuracy: 0.7074 - val_loss: 0.5548 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5491 - accuracy: 0.7188 - val_loss: 0.5507 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7264 - val_loss: 0.5500 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7318 - val_loss: 0.5429 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7347 - val_loss: 0.5411 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7410 - val_loss: 0.5429 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7416 - val_loss: 0.5487 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7480 - val_loss: 0.5426 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4966 - accuracy: 0.7534
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7530 - val_loss: 0.5465 - val_accuracy: 0.7263 - lr: 0.0010

271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.5125054219592269
Confusion Matrix :
 [[3145 1178]
 [ 933 3390]]
Accuracy on test set:    0.7558408512606986
Sensitivity:    0.7841776544066621 	 Specificity:    0.7275040481147351
Precision  : 0.7421190893169878
Area Under Curve:    0.7558408512606987
(8646, 4352) (8646,)
Mean MCC = 0.4489 + 0.0252 and Mean AUC = 0.7236 + 0.0127
Mean Sensitivity = 0.7401 + 0.0404 and Mean Specificity = 0.7071 + 0.0432 and Mean Accuracy = 0.7236 + 0.0127
Mean Precision = 0.7178 + 0.0214





Seed   : 758631
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6129 - accuracy: 0.6586 - val_loss: 0.5644 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5626 - accuracy: 0.7093 - val_loss: 0.5467 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7198 - val_loss: 0.5484 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7274 - val_loss: 0.5372 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7352 - val_loss: 0.5371 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5172 - accuracy: 0.7382 - val_loss: 0.5369 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5119 - accuracy: 0.7428 - val_loss: 0.5465 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5042 - accuracy: 0.7482 - val_loss: 0.5285 - val_accuracy: 0.7343 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7514 - val_loss: 0.5316 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7573 - val_loss: 0.5403 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7614 - val_loss: 0.5383 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4794 - accuracy: 0.7621 - val_loss: 0.5555 - val_accuracy: 0.7345 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7679 - val_loss: 0.5387 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4652 - accuracy: 0.7699 - val_loss: 0.5424 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4592 - accuracy: 0.7756 - val_loss: 0.5479 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4539 - accuracy: 0.7775 - val_loss: 0.5481 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 17/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4489 - accuracy: 0.7815
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4487 - accuracy: 0.7815 - val_loss: 0.5683 - val_accuracy: 0.7262 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4330370997741617
Confusion Matrix :
 [[2764 1559]
 [ 913 3410]]
Accuracy on test set:    0.714087439278279
Sensitivity:    0.7888040712468194 	 Specificity:    0.6393708073097386
Precision  : 0.6862547796337292
Area Under Curve:    0.714087439278279
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6207 - accuracy: 0.6542 - val_loss: 0.5672 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5658 - accuracy: 0.7048 - val_loss: 0.5541 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7212 - val_loss: 0.5378 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7279 - val_loss: 0.5383 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7312 - val_loss: 0.5392 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5227 - accuracy: 0.7363 - val_loss: 0.5340 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7408 - val_loss: 0.5367 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7457 - val_loss: 0.5364 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7505 - val_loss: 0.5363 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4960 - accuracy: 0.7539 - val_loss: 0.5372 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4911 - accuracy: 0.7561
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7562 - val_loss: 0.5383 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.44055994958174177
Confusion Matrix :
 [[3165 1158]
 [1261 3062]]
Accuracy on test set:    0.7202174415914874
Sensitivity:    0.7083044182280823 	 Specificity:    0.7321304649548924
Precision  : 0.7255924170616114
Area Under Curve:    0.7202174415914874
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6052 - accuracy: 0.6660 - val_loss: 0.5631 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7099 - val_loss: 0.5575 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7212 - val_loss: 0.5485 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7268 - val_loss: 0.5444 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5300 - accuracy: 0.7329 - val_loss: 0.5462 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7364 - val_loss: 0.5411 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7396 - val_loss: 0.5378 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5112 - accuracy: 0.7436 - val_loss: 0.5448 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7468 - val_loss: 0.5364 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4987 - accuracy: 0.7501 - val_loss: 0.5445 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4961 - accuracy: 0.7522 - val_loss: 0.5384 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7544 - val_loss: 0.5498 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4854 - accuracy: 0.7615 - val_loss: 0.5483 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4802 - accuracy: 0.7628
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

274/274 [==============================] - 1s 2ms/step - loss: 0.4806 - accuracy: 0.7625 - val_loss: 0.5459 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.43494864549575596
Confusion Matrix :
 [[3139 1184]
 [1259 3064]]
Accuracy on test set:    0.7174415914873931
Sensitivity:    0.7087670599120981 	 Specificity:    0.7261161230626879
Precision  : 0.7212806026365348
Area Under Curve:    0.7174415914873931
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6236 - accuracy: 0.6428 - val_loss: 0.5721 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5708 - accuracy: 0.7035 - val_loss: 0.5535 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5526 - accuracy: 0.7165 - val_loss: 0.5426 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7232 - val_loss: 0.5398 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7275 - val_loss: 0.5388 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7323 - val_loss: 0.5373 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5222 - accuracy: 0.7369 - val_loss: 0.5435 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7390 - val_loss: 0.5352 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5110 - accuracy: 0.7425 - val_loss: 0.5374 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5054 - accuracy: 0.7453 - val_loss: 0.5384 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7486 - val_loss: 0.5439 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7519 - val_loss: 0.5392 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7550 - val_loss: 0.5461 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4850 - accuracy: 0.7591 - val_loss: 0.5372 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7605 - val_loss: 0.5424 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4749 - accuracy: 0.7631 - val_loss: 0.5500 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4695 - accuracy: 0.7670 - val_loss: 0.5498 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4667 - accuracy: 0.7675 - val_loss: 0.5557 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4597 - accuracy: 0.7723 - val_loss: 0.5584 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4575 - accuracy: 0.7730 - val_loss: 0.5626 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4521 - accuracy: 0.7755 - val_loss: 0.5672 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 22/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4489 - accuracy: 0.7765 - val_loss: 0.5649 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 23/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4415 - accuracy: 0.7788
Epoch 23: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4425 - accuracy: 0.7782 - val_loss: 0.5733 - val_accuracy: 0.7199 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4255859948489641
Confusion Matrix :
 [[2831 1492]
 [1003 3320]]
Accuracy on test set:    0.7114272495951885
Sensitivity:    0.7679851954661115 	 Specificity:    0.6548693037242656
Precision  : 0.6899418121363259
Area Under Curve:    0.7114272495951885
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6101 - accuracy: 0.6622 - val_loss: 0.5613 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7107 - val_loss: 0.5485 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7212 - val_loss: 0.5446 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7307 - val_loss: 0.5381 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7339 - val_loss: 0.5417 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5195 - accuracy: 0.7387 - val_loss: 0.5345 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5150 - accuracy: 0.7421 - val_loss: 0.5371 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7468 - val_loss: 0.5400 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7482 - val_loss: 0.5450 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4964 - accuracy: 0.7536 - val_loss: 0.5418 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4923 - accuracy: 0.7551
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4924 - accuracy: 0.7552 - val_loss: 0.5425 - val_accuracy: 0.7267 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4416357157245831
Confusion Matrix :
 [[2761 1562]
 [ 876 3447]]
Accuracy on test set:    0.7180198935924127
Sensitivity:    0.7973629424011104 	 Specificity:    0.638676844783715
Precision  : 0.6881613096426432
Area Under Curve:    0.7180198935924127
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6028 - accuracy: 0.6676 - val_loss: 0.5606 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5553 - accuracy: 0.7129 - val_loss: 0.5449 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7235 - val_loss: 0.5504 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7298 - val_loss: 0.5386 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5223 - accuracy: 0.7350 - val_loss: 0.5345 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7400 - val_loss: 0.5337 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7429 - val_loss: 0.5360 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5047 - accuracy: 0.7489 - val_loss: 0.5390 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7511 - val_loss: 0.5342 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7570 - val_loss: 0.5362 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7615 - val_loss: 0.5360 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4782 - accuracy: 0.7650 - val_loss: 0.5430 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4752 - accuracy: 0.7650 - val_loss: 0.5422 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4679 - accuracy: 0.7709 - val_loss: 0.5443 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4625 - accuracy: 0.7745
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4626 - accuracy: 0.7742 - val_loss: 0.5501 - val_accuracy: 0.7283 - lr: 0.0010
271/271 [==============================] - 0s 667us/step
Independent Testing Matthews Correlation:  0.45108444002039233
Confusion Matrix :
 [[3123 1200]
 [1173 3150]]
Accuracy on test set:    0.7255378209576683
Sensitivity:    0.7286606523247745 	 Specificity:    0.7224149895905622
Precision  : 0.7241379310344828
Area Under Curve:    0.7255378209576682
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6159 - accuracy: 0.6606 - val_loss: 0.5663 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5624 - accuracy: 0.7087 - val_loss: 0.5505 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7225 - val_loss: 0.5459 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7297 - val_loss: 0.5431 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7352 - val_loss: 0.5466 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7411 - val_loss: 0.5418 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7462 - val_loss: 0.5420 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5047 - accuracy: 0.7511 - val_loss: 0.5457 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7526 - val_loss: 0.5441 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7592 - val_loss: 0.5513 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4810 - accuracy: 0.7627 - val_loss: 0.5465 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7654 - val_loss: 0.5552 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7703 - val_loss: 0.5542 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4629 - accuracy: 0.7725 - val_loss: 0.5539 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 15/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4573 - accuracy: 0.7749
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4578 - accuracy: 0.7746 - val_loss: 0.5600 - val_accuracy: 0.7191 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.44707693319817726
Confusion Matrix :
 [[3012 1311]
 [1082 3241]]
Accuracy on test set:    0.7232246125375896
Sensitivity:    0.7497108489474902 	 Specificity:    0.6967383761276891
Precision  : 0.7119947275922671
Area Under Curve:    0.7232246125375896
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6080 - accuracy: 0.6671 - val_loss: 0.5617 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5586 - accuracy: 0.7116 - val_loss: 0.5462 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7227 - val_loss: 0.5421 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7304 - val_loss: 0.5421 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7351 - val_loss: 0.5422 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7405 - val_loss: 0.5435 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7438 - val_loss: 0.5416 - val_accuracy: 0.7346 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7513 - val_loss: 0.5463 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7514 - val_loss: 0.5449 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7554 - val_loss: 0.5449 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4861 - accuracy: 0.7607 - val_loss: 0.5517 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4801 - accuracy: 0.7647
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4797 - accuracy: 0.7647 - val_loss: 0.5460 - val_accuracy: 0.7210 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4624629249467116
Confusion Matrix :
 [[3262 1061]
 [1265 3058]]
Accuracy on test set:    0.7309738607448532
Sensitivity:    0.7073791348600509 	 Specificity:    0.7545685866296553
Precision  : 0.7424132070890993
Area Under Curve:    0.730973860744853
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6069 - accuracy: 0.6662 - val_loss: 0.5701 - val_accuracy: 0.7039 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7108 - val_loss: 0.5601 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7206 - val_loss: 0.5515 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7273 - val_loss: 0.5530 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7340 - val_loss: 0.5468 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7401 - val_loss: 0.5437 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7413 - val_loss: 0.5447 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7463 - val_loss: 0.5442 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 9/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5012 - accuracy: 0.7503 - val_loss: 0.5448 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7536 - val_loss: 0.5512 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7555 - val_loss: 0.5483 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4839 - accuracy: 0.7595 - val_loss: 0.5512 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4789 - accuracy: 0.7637 - val_loss: 0.5499 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7627 - val_loss: 0.5667 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7685 - val_loss: 0.5611 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4629 - accuracy: 0.7699 - val_loss: 0.5566 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4589 - accuracy: 0.7729 - val_loss: 0.5700 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4533 - accuracy: 0.7768 - val_loss: 0.5734 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4476 - accuracy: 0.7784 - val_loss: 0.5758 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 20/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4427 - accuracy: 0.7825
Epoch 20: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4439 - accuracy: 0.7814 - val_loss: 0.5776 - val_accuracy: 0.7186 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4626473510368476
Confusion Matrix :
 [[3339  984]
 [1346 2977]]
Accuracy on test set:    0.7305112190608374
Sensitivity:    0.6886421466574139 	 Specificity:    0.7723802914642609
Precision  : 0.7515778843726332
Area Under Curve:    0.7305112190608374
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6066 - accuracy: 0.6665 - val_loss: 0.5638 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7141 - val_loss: 0.5585 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7220 - val_loss: 0.5531 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7286 - val_loss: 0.5478 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7354 - val_loss: 0.5661 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7376 - val_loss: 0.5479 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5130 - accuracy: 0.7431 - val_loss: 0.5483 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7464 - val_loss: 0.5484 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5009 - accuracy: 0.7521 - val_loss: 0.5554 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7552 - val_loss: 0.5549 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 11/400
263/274 [===========================>..] - ETA: 0s - loss: 0.4850 - accuracy: 0.7595
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4857 - accuracy: 0.7592 - val_loss: 0.5577 - val_accuracy: 0.7192 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.48537400834697525
Confusion Matrix :
 [[3507  816]
 [1430 2893]]
Accuracy on test set:    0.7402266944251678
Sensitivity:    0.6692111959287532 	 Specificity:    0.8112421929215823
Precision  : 0.7799946077109733
Area Under Curve:    0.7402266944251678
(8646, 4352) (8646,)
Mean MCC = 0.4484 + 0.0168 and Mean AUC = 0.7232 + 0.0084
Mean Sensitivity = 0.7315 + 0.0408 and Mean Specificity = 0.7149 + 0.0549 and Mean Accuracy = 0.7232 + 0.0084
Mean Precision = 0.7221 + 0.0287





Seed   : 155267
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6086 - accuracy: 0.6652 - val_loss: 0.5641 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5562 - accuracy: 0.7133 - val_loss: 0.5499 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7251 - val_loss: 0.5436 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7319 - val_loss: 0.5409 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5227 - accuracy: 0.7356 - val_loss: 0.5405 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7434 - val_loss: 0.5402 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5054 - accuracy: 0.7465 - val_loss: 0.5355 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5032 - accuracy: 0.7471 - val_loss: 0.5397 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4951 - accuracy: 0.7547 - val_loss: 0.5404 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7591 - val_loss: 0.5344 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4806 - accuracy: 0.7633 - val_loss: 0.5388 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4744 - accuracy: 0.7660 - val_loss: 0.5387 - val_accuracy: 0.7335 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7704 - val_loss: 0.5401 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4638 - accuracy: 0.7745 - val_loss: 0.5494 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4564 - accuracy: 0.7759 - val_loss: 0.5489 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4498 - accuracy: 0.7800 - val_loss: 0.5455 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4442 - accuracy: 0.7824
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4441 - accuracy: 0.7826 - val_loss: 0.5539 - val_accuracy: 0.7201 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.40768167252526266
Confusion Matrix :
 [[2996 1327]
 [1234 3089]]
Accuracy on test set:    0.703793661808929
Sensitivity:    0.7145500809622947 	 Specificity:    0.6930372426555632
Precision  : 0.6995018115942029
Area Under Curve:    0.703793661808929
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6213 - accuracy: 0.6472 - val_loss: 0.5668 - val_accuracy: 0.7091 - lr: 0.0010

Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5639 - accuracy: 0.7090 - val_loss: 0.5544 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7206 - val_loss: 0.5463 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7274 - val_loss: 0.5441 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7322 - val_loss: 0.5407 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7370 - val_loss: 0.5440 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5165 - accuracy: 0.7398 - val_loss: 0.5398 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7445 - val_loss: 0.5467 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7462 - val_loss: 0.5382 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7496 - val_loss: 0.5512 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4951 - accuracy: 0.7544 - val_loss: 0.5432 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7578 - val_loss: 0.5467 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4822 - accuracy: 0.7637 - val_loss: 0.5497 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 14/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4755 - accuracy: 0.7646
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4761 - accuracy: 0.7639 - val_loss: 0.5502 - val_accuracy: 0.7245 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4411180089030265
Confusion Matrix :
 [[2847 1476]
 [ 954 3369]]
Accuracy on test set:    0.7189451769604441
Sensitivity:    0.7793199167244969 	 Specificity:    0.6585704371963914
Precision  : 0.6953560371517028
Area Under Curve:    0.7189451769604441
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6197 - accuracy: 0.6611 - val_loss: 0.5681 - val_accuracy: 0.7070 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5569 - accuracy: 0.7135 - val_loss: 0.5568 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7216 - val_loss: 0.5520 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7300 - val_loss: 0.5459 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7369 - val_loss: 0.5420 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7409 - val_loss: 0.5421 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7456 - val_loss: 0.5436 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7515 - val_loss: 0.5458 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4924 - accuracy: 0.7562 - val_loss: 0.5422 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4873 - accuracy: 0.7596 - val_loss: 0.5580 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 11/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4816 - accuracy: 0.7605
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7613 - val_loss: 0.5458 - val_accuracy: 0.7240 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4531301063540747
Confusion Matrix :
 [[2986 1337]
 [1032 3291]]
Accuracy on test set:    0.726000462641684
Sensitivity:    0.7612768910478834 	 Specificity:    0.6907240342354846
Precision  : 0.7111063094209161
Area Under Curve:    0.726000462641684
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6146 - accuracy: 0.6622 - val_loss: 0.5645 - val_accuracy: 0.7012 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7113 - val_loss: 0.5501 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7209 - val_loss: 0.5538 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7298 - val_loss: 0.5676 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7362 - val_loss: 0.5428 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5167 - accuracy: 0.7405 - val_loss: 0.5421 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7439 - val_loss: 0.5416 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7470 - val_loss: 0.5402 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7521 - val_loss: 0.5479 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7566 - val_loss: 0.5463 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7614 - val_loss: 0.5534 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4796 - accuracy: 0.7613 - val_loss: 0.5577 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4727 - accuracy: 0.7686 - val_loss: 0.5537 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4650 - accuracy: 0.7724 - val_loss: 0.5653 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4613 - accuracy: 0.7717 - val_loss: 0.5678 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4538 - accuracy: 0.7779 - val_loss: 0.5575 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4499 - accuracy: 0.7773 - val_loss: 0.5709 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4432 - accuracy: 0.7829 - val_loss: 0.5733 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 19/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4351 - accuracy: 0.7884
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4351 - accuracy: 0.7886 - val_loss: 0.5724 - val_accuracy: 0.7204 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.43821877525184255
Confusion Matrix :
 [[3154 1169]
 [1260 3063]]
Accuracy on test set:    0.7190608373814481
Sensitivity:    0.7085357390700903 	 Specificity:    0.7295859356928059
Precision  : 0.7237712665406427
Area Under Curve:    0.7190608373814481
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6203 - accuracy: 0.6526 - val_loss: 0.5692 - val_accuracy: 0.7048 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5627 - accuracy: 0.7082 - val_loss: 0.5529 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7203 - val_loss: 0.5438 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7272 - val_loss: 0.5480 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7328 - val_loss: 0.5368 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5202 - accuracy: 0.7374 - val_loss: 0.5405 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7432 - val_loss: 0.5413 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7465 - val_loss: 0.5365 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7505 - val_loss: 0.5434 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7542 - val_loss: 0.5514 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7543 - val_loss: 0.5388 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7602 - val_loss: 0.5408 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4753 - accuracy: 0.7653
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4753 - accuracy: 0.7652 - val_loss: 0.5446 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4374323936049531
Confusion Matrix :
 [[3097 1226]
 [1206 3117]]
Accuracy on test set:    0.7187138561184363
Sensitivity:    0.721027064538515 	 Specificity:    0.7164006476983577
Precision  : 0.7177066543863688
Area Under Curve:    0.7187138561184362
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6037 - accuracy: 0.6682 - val_loss: 0.5678 - val_accuracy: 0.7030 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5587 - accuracy: 0.7126 - val_loss: 0.5482 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7244 - val_loss: 0.5425 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7305 - val_loss: 0.5410 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7364 - val_loss: 0.5453 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7415 - val_loss: 0.5397 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7446 - val_loss: 0.5398 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5057 - accuracy: 0.7473 - val_loss: 0.5427 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7483 - val_loss: 0.5445 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4956 - accuracy: 0.7520 - val_loss: 0.5424 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7566 - val_loss: 0.5486 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4858 - accuracy: 0.7588 - val_loss: 0.5480 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7623 - val_loss: 0.5484 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4744 - accuracy: 0.7659 - val_loss: 0.5630 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4682 - accuracy: 0.7700
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4682 - accuracy: 0.7701 - val_loss: 0.5521 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.43131739599268715
Confusion Matrix :
 [[2909 1414]
 [1051 3272]]
Accuracy on test set:    0.7148970622253065
Sensitivity:    0.756881795049734 	 Specificity:    0.672912329400879
Precision  : 0.6982501067008109
Area Under Curve:    0.7148970622253065
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6066 - accuracy: 0.6673 - val_loss: 0.5653 - val_accuracy: 0.7052 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7117 - val_loss: 0.5537 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7229 - val_loss: 0.5435 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7306 - val_loss: 0.5409 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7353 - val_loss: 0.5416 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7404 - val_loss: 0.5418 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7435 - val_loss: 0.5399 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7470 - val_loss: 0.5387 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4970 - accuracy: 0.7514 - val_loss: 0.5381 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7556 - val_loss: 0.5376 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4869 - accuracy: 0.7588 - val_loss: 0.5417 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4795 - accuracy: 0.7653 - val_loss: 0.5404 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4717 - accuracy: 0.7690 - val_loss: 0.5372 - val_accuracy: 0.7330 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7697 - val_loss: 0.5460 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4581 - accuracy: 0.7770 - val_loss: 0.5528 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4514 - accuracy: 0.7811 - val_loss: 0.5573 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4449 - accuracy: 0.7832 - val_loss: 0.5480 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4428 - accuracy: 0.7842
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4433 - accuracy: 0.7840 - val_loss: 0.5586 - val_accuracy: 0.7210 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.45889072911694595
Confusion Matrix :
 [[2902 1421]
 [ 931 3392]]
Accuracy on test set:    0.7279666897987509
Sensitivity:    0.7846402960906778 	 Specificity:    0.6712930835068239
Precision  : 0.7047579472262622
Area Under Curve:    0.7279666897987509
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6084 - accuracy: 0.6665 - val_loss: 0.5691 - val_accuracy: 0.7029 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7106 - val_loss: 0.5581 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7209 - val_loss: 0.5583 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7279 - val_loss: 0.5470 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7344 - val_loss: 0.5420 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5190 - accuracy: 0.7386 - val_loss: 0.5452 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7397 - val_loss: 0.5393 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5106 - accuracy: 0.7428 - val_loss: 0.5421 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7501 - val_loss: 0.5436 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7536 - val_loss: 0.5444 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4884 - accuracy: 0.7577 - val_loss: 0.5428 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4859 - accuracy: 0.7579 - val_loss: 0.5492 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4763 - accuracy: 0.7633
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4764 - accuracy: 0.7635 - val_loss: 0.5488 - val_accuracy: 0.7228 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.46426601119993816
Confusion Matrix :
 [[3261 1062]
 [1256 3067]]
Accuracy on test set:    0.7318991441128846
Sensitivity:    0.7094610224381217 	 Specificity:    0.7543372657876475
Precision  : 0.7427948655848874
Area Under Curve:    0.7318991441128846
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6098 - accuracy: 0.6631 - val_loss: 0.5706 - val_accuracy: 0.7028 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5627 - accuracy: 0.7088 - val_loss: 0.5551 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7199 - val_loss: 0.5539 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7269 - val_loss: 0.5551 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5285 - accuracy: 0.7313 - val_loss: 0.5482 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5210 - accuracy: 0.7373 - val_loss: 0.5460 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7391 - val_loss: 0.5491 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7458 - val_loss: 0.5527 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7522 - val_loss: 0.5467 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7550 - val_loss: 0.5523 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4881 - accuracy: 0.7581 - val_loss: 0.5478 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4809 - accuracy: 0.7603 - val_loss: 0.5551 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7645 - val_loss: 0.5587 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4675 - accuracy: 0.7702 - val_loss: 0.5588 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4649 - accuracy: 0.7702 - val_loss: 0.5646 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4587 - accuracy: 0.7762
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4585 - accuracy: 0.7763 - val_loss: 0.5693 - val_accuracy: 0.7142 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.47932596032553665
Confusion Matrix :
 [[2958 1365]
 [ 898 3425]]
Accuracy on test set:    0.7382604672681009
Sensitivity:    0.7922738838769373 	 Specificity:    0.6842470506592644
Precision  : 0.7150313152400835
Area Under Curve:    0.7382604672681008
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6169 - accuracy: 0.6582 - val_loss: 0.5748 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5679 - accuracy: 0.7038 - val_loss: 0.5601 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5517 - accuracy: 0.7184 - val_loss: 0.5547 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7251 - val_loss: 0.5464 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7313 - val_loss: 0.5464 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7343 - val_loss: 0.5468 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7386 - val_loss: 0.5487 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5144 - accuracy: 0.7424 - val_loss: 0.5464 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7449 - val_loss: 0.5434 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7476 - val_loss: 0.5534 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7510 - val_loss: 0.5481 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4929 - accuracy: 0.7549
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7544 - val_loss: 0.5473 - val_accuracy: 0.7199 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.48677338982340557
Confusion Matrix :
 [[3314 1009]
 [1212 3111]]
Accuracy on test set:    0.743118204950266
Sensitivity:    0.7196391394864677 	 Specificity:    0.7665972704140643
Precision  : 0.7550970873786408
Area Under Curve:    0.7431182049502659
(8646, 4352) (8646,)
Mean MCC = 0.4498 + 0.0224 and Mean AUC = 0.7243 + 0.0110
Mean Sensitivity = 0.7448 + 0.0318 and Mean Specificity = 0.7038 + 0.0347 and Mean Accuracy = 0.7243 + 0.0110
Mean Precision = 0.7163 + 0.0186





Seed   : 995890
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6165 - accuracy: 0.6574 - val_loss: 0.5755 - val_accuracy: 0.7012 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5652 - accuracy: 0.7070 - val_loss: 0.5548 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5489 - accuracy: 0.7203 - val_loss: 0.5495 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7259 - val_loss: 0.5413 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7351 - val_loss: 0.5388 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.7365 - val_loss: 0.5414 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5167 - accuracy: 0.7388 - val_loss: 0.5416 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7474 - val_loss: 0.5432 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7490 - val_loss: 0.5401 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4965 - accuracy: 0.7541
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4974 - accuracy: 0.7530 - val_loss: 0.5429 - val_accuracy: 0.7187 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.39744074869824825
Confusion Matrix :
 [[2672 1651]
 [ 975 3348]]
Accuracy on test set:    0.6962757344436734
Sensitivity:    0.7744621790423317 	 Specificity:    0.618089289845015
Precision  : 0.6697339467893578
Area Under Curve:    0.6962757344436734
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6037 - accuracy: 0.6702 - val_loss: 0.5659 - val_accuracy: 0.7034 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5567 - accuracy: 0.7130 - val_loss: 0.5510 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7235 - val_loss: 0.5442 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5290 - accuracy: 0.7331 - val_loss: 0.5439 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7348 - val_loss: 0.5403 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7396 - val_loss: 0.5396 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7460 - val_loss: 0.5390 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5008 - accuracy: 0.7515 - val_loss: 0.5435 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7534 - val_loss: 0.5394 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7596 - val_loss: 0.5445 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4809 - accuracy: 0.7638
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4811 - accuracy: 0.7634 - val_loss: 0.5459 - val_accuracy: 0.7159 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.4378110947885152
Confusion Matrix :
 [[3272 1051]
 [1385 2938]]
Accuracy on test set:    0.7182512144344205
Sensitivity:    0.6796206338191071 	 Specificity:    0.756881795049734
Precision  : 0.7365254449736777
Area Under Curve:    0.7182512144344205
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5934 - accuracy: 0.6797 - val_loss: 0.5672 - val_accuracy: 0.6979 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5525 - accuracy: 0.7150 - val_loss: 0.5527 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7263 - val_loss: 0.5535 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7335 - val_loss: 0.5472 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5194 - accuracy: 0.7383 - val_loss: 0.5429 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7441 - val_loss: 0.5369 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5073 - accuracy: 0.7475 - val_loss: 0.5382 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4988 - accuracy: 0.7511 - val_loss: 0.5401 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4924 - accuracy: 0.7573 - val_loss: 0.5402 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7587 - val_loss: 0.5507 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4778 - accuracy: 0.7650
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4791 - accuracy: 0.7636 - val_loss: 0.5430 - val_accuracy: 0.7187 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.44660869082539795
Confusion Matrix :
 [[2844 1479]
 [ 929 3394]]
Accuracy on test set:    0.7214897062225306
Sensitivity:    0.7851029377746935 	 Specificity:    0.6578764746703678
Precision  : 0.6964908680484301
Area Under Curve:    0.7214897062225307
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6105 - accuracy: 0.6613 - val_loss: 0.5603 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5629 - accuracy: 0.7076 - val_loss: 0.5587 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7209 - val_loss: 0.5388 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7262 - val_loss: 0.5399 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5272 - accuracy: 0.7327 - val_loss: 0.5356 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5212 - accuracy: 0.7369 - val_loss: 0.5429 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7427 - val_loss: 0.5364 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7457 - val_loss: 0.5357 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7478 - val_loss: 0.5458 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7508 - val_loss: 0.5427 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7546 - val_loss: 0.5380 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7544 - val_loss: 0.5439 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7604 - val_loss: 0.5434 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4775 - accuracy: 0.7608 - val_loss: 0.5458 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7663 - val_loss: 0.5471 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7659 - val_loss: 0.5534 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4607 - accuracy: 0.7723 - val_loss: 0.5452 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4594 - accuracy: 0.7715 - val_loss: 0.5578 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4531 - accuracy: 0.7763 - val_loss: 0.5592 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 20/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4475 - accuracy: 0.7787
Epoch 20: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4483 - accuracy: 0.7776 - val_loss: 0.5608 - val_accuracy: 0.7176 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4148293069675531
Confusion Matrix :
 [[3018 1305]
 [1225 3098]]
Accuracy on test set:    0.7073791348600509
Sensitivity:    0.7166319685403655 	 Specificity:    0.6981263011797363
Precision  : 0.7036111741994094
Area Under Curve:    0.7073791348600509
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6010 - accuracy: 0.6713 - val_loss: 0.5546 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7139 - val_loss: 0.5508 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7229 - val_loss: 0.5395 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7331 - val_loss: 0.5447 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7345 - val_loss: 0.5374 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7383 - val_loss: 0.5379 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5105 - accuracy: 0.7451 - val_loss: 0.5336 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7481 - val_loss: 0.5355 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4963 - accuracy: 0.7520 - val_loss: 0.5340 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4922 - accuracy: 0.7566 - val_loss: 0.5377 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4868 - accuracy: 0.7602 - val_loss: 0.5422 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4815 - accuracy: 0.7614 - val_loss: 0.5399 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4766 - accuracy: 0.7652 - val_loss: 0.5395 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4705 - accuracy: 0.7680 - val_loss: 0.5471 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4638 - accuracy: 0.7714 - val_loss: 0.5474 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4606 - accuracy: 0.7746 - val_loss: 0.5516 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4556 - accuracy: 0.7759 - val_loss: 0.5659 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 18/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4503 - accuracy: 0.7795
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4505 - accuracy: 0.7793 - val_loss: 0.5486 - val_accuracy: 0.7218 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.419511288292561
Confusion Matrix :
 [[2842 1481]
 [1038 3285]]
Accuracy on test set:    0.7086513994910941
Sensitivity:    0.7598889659958362 	 Specificity:    0.657413832986352
Precision  : 0.6892572387746538
Area Under Curve:    0.7086513994910942
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6287 - accuracy: 0.6472 - val_loss: 0.5696 - val_accuracy: 0.7034 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5727 - accuracy: 0.7015 - val_loss: 0.5512 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5554 - accuracy: 0.7155 - val_loss: 0.5540 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7238 - val_loss: 0.5402 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7272 - val_loss: 0.5383 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5285 - accuracy: 0.7344 - val_loss: 0.5357 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5213 - accuracy: 0.7353 - val_loss: 0.5366 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7397 - val_loss: 0.5369 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7444 - val_loss: 0.5358 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
261/274 [===========================>..] - ETA: 0s - loss: 0.5066 - accuracy: 0.7453
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7458 - val_loss: 0.5362 - val_accuracy: 0.7240 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.42938939853703806
Confusion Matrix :
 [[3054 1269]
 [1198 3125]]
Accuracy on test set:    0.7146657413832986
Sensitivity:    0.7228776312745778 	 Specificity:    0.7064538514920194
Precision  : 0.7111970869367319
Area Under Curve:    0.7146657413832987
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6022 - accuracy: 0.6725 - val_loss: 0.5607 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5587 - accuracy: 0.7105 - val_loss: 0.5490 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7239 - val_loss: 0.5467 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7303 - val_loss: 0.5401 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5247 - accuracy: 0.7354 - val_loss: 0.5394 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7410 - val_loss: 0.5379 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7446 - val_loss: 0.5414 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5056 - accuracy: 0.7481 - val_loss: 0.5451 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7504 - val_loss: 0.5369 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7550 - val_loss: 0.5342 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4884 - accuracy: 0.7592 - val_loss: 0.5347 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7610 - val_loss: 0.5397 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7612 - val_loss: 0.5470 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4685 - accuracy: 0.7696 - val_loss: 0.5429 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 15/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4620 - accuracy: 0.7742
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4627 - accuracy: 0.7732 - val_loss: 0.5405 - val_accuracy: 0.7200 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4349040395093279
Confusion Matrix :
 [[3242 1081]
 [1366 2957]]
Accuracy on test set:    0.7169789498033773
Sensitivity:    0.6840157298172566 	 Specificity:    0.749942169789498
Precision  : 0.7322932144626052
Area Under Curve:    0.7169789498033773
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6150 - accuracy: 0.6592 - val_loss: 0.5620 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5654 - accuracy: 0.7059 - val_loss: 0.5492 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5497 - accuracy: 0.7167 - val_loss: 0.5485 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7230 - val_loss: 0.5410 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7293 - val_loss: 0.5393 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7330 - val_loss: 0.5346 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7358 - val_loss: 0.5338 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7434 - val_loss: 0.5328 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7454 - val_loss: 0.5346 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7494 - val_loss: 0.5339 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4956 - accuracy: 0.7521 - val_loss: 0.5354 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7564 - val_loss: 0.5434 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7589 - val_loss: 0.5449 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4788 - accuracy: 0.7614 - val_loss: 0.5443 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4734 - accuracy: 0.7637
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4742 - accuracy: 0.7631 - val_loss: 0.5394 - val_accuracy: 0.7235 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4418475869567354
Confusion Matrix :
 [[3217 1106]
 [1309 3014]]
Accuracy on test set:    0.7206800832755031
Sensitivity:    0.6972010178117048 	 Specificity:    0.7441591487393014
Precision  : 0.7315533980582525
Area Under Curve:    0.720680083275503
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 5s 3ms/step - loss: 0.6152 - accuracy: 0.6632 - val_loss: 0.5728 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5626 - accuracy: 0.7078 - val_loss: 0.5550 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7209 - val_loss: 0.5478 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5369 - accuracy: 0.7276 - val_loss: 0.5416 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5280 - accuracy: 0.7327 - val_loss: 0.5462 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7363 - val_loss: 0.5472 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5141 - accuracy: 0.7418 - val_loss: 0.5377 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5065 - accuracy: 0.7476 - val_loss: 0.5397 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7491 - val_loss: 0.5418 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7528 - val_loss: 0.5451 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7590 - val_loss: 0.5477 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4805 - accuracy: 0.7637 - val_loss: 0.5421 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4738 - accuracy: 0.7649 - val_loss: 0.5488 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4716 - accuracy: 0.7671 - val_loss: 0.5466 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4624 - accuracy: 0.7732 - val_loss: 0.5464 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4586 - accuracy: 0.7748 - val_loss: 0.5487 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 17/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4504 - accuracy: 0.7802
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4507 - accuracy: 0.7799 - val_loss: 0.5637 - val_accuracy: 0.7268 - lr: 0.0010
271/271 [==============================] - 0s 667us/step
Independent Testing Matthews Correlation:  0.48128831137707145
Confusion Matrix :
 [[3286 1037]
 [1207 3116]]
Accuracy on test set:    0.7404580152671756
Sensitivity:    0.720795743696507 	 Specificity:    0.760120286837844
Precision  : 0.7503009872381411
Area Under Curve:    0.7404580152671755
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6164 - accuracy: 0.6577 - val_loss: 0.5687 - val_accuracy: 0.7017 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5659 - accuracy: 0.7085 - val_loss: 0.5621 - val_accuracy: 0.7092 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5500 - accuracy: 0.7193 - val_loss: 0.5434 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7248 - val_loss: 0.5447 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7304 - val_loss: 0.5418 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5240 - accuracy: 0.7352 - val_loss: 0.5357 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7409 - val_loss: 0.5387 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7463 - val_loss: 0.5478 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7492 - val_loss: 0.5408 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4974 - accuracy: 0.7514
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4970 - accuracy: 0.7517 - val_loss: 0.5396 - val_accuracy: 0.7278 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.5084820122278156
Confusion Matrix :
 [[3375  948]
 [1180 3143]]
Accuracy on test set:    0.7538746241036317
Sensitivity:    0.7270414064307195 	 Specificity:    0.7807078417765441
Precision  : 0.7682718161818626
Area Under Curve:    0.7538746241036318
(8646, 4352) (8646,)
Mean MCC = 0.4412 + 0.0307 and Mean AUC = 0.7199 + 0.0157
Mean Sensitivity = 0.7268 + 0.0344 and Mean Specificity = 0.7130 + 0.0514 and Mean Accuracy = 0.7199 + 0.0157
Mean Precision = 0.7189 + 0.0286





Seed   : 216717
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6086 - accuracy: 0.6634 - val_loss: 0.5669 - val_accuracy: 0.7048 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5588 - accuracy: 0.7115 - val_loss: 0.5466 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7226 - val_loss: 0.5407 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7288 - val_loss: 0.5410 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7344 - val_loss: 0.5365 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7412 - val_loss: 0.5408 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5116 - accuracy: 0.7434 - val_loss: 0.5327 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7484 - val_loss: 0.5324 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7542 - val_loss: 0.5384 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7561 - val_loss: 0.5342 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7592 - val_loss: 0.5361 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4801 - accuracy: 0.7641 - val_loss: 0.5392 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4761 - accuracy: 0.7654 - val_loss: 0.5418 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4699 - accuracy: 0.7690
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4699 - accuracy: 0.7689 - val_loss: 0.5418 - val_accuracy: 0.7240 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4314313616303073
Confusion Matrix :
 [[2991 1332]
 [1128 3195]]
Accuracy on test set:    0.7154753643303262
Sensitivity:    0.7390700902151284 	 Specificity:    0.6918806384455239
Precision  : 0.705765407554672
Area Under Curve:    0.7154753643303262
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6006 - accuracy: 0.6722 - val_loss: 0.5723 - val_accuracy: 0.6922 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5545 - accuracy: 0.7157 - val_loss: 0.5602 - val_accuracy: 0.7032 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7259 - val_loss: 0.5396 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5297 - accuracy: 0.7331 - val_loss: 0.5445 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5213 - accuracy: 0.7367 - val_loss: 0.5409 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7424 - val_loss: 0.5357 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7490 - val_loss: 0.5308 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7505 - val_loss: 0.5355 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7551 - val_loss: 0.5345 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7595 - val_loss: 0.5345 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4809 - accuracy: 0.7634 - val_loss: 0.5503 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 12/400
263/274 [===========================>..] - ETA: 0s - loss: 0.4735 - accuracy: 0.7657
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4737 - accuracy: 0.7658 - val_loss: 0.5401 - val_accuracy: 0.7258 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.43017431069047746
Confusion Matrix :
 [[2844 1479]
 [ 996 3327]]
Accuracy on test set:    0.7137404580152672
Sensitivity:    0.7696044413601666 	 Specificity:    0.6578764746703678
Precision  : 0.6922596754057428
Area Under Curve:    0.7137404580152671
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6083 - accuracy: 0.6665 - val_loss: 0.5622 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5578 - accuracy: 0.7126 - val_loss: 0.5463 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7232 - val_loss: 0.5381 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7320 - val_loss: 0.5377 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7358 - val_loss: 0.5377 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7408 - val_loss: 0.5400 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5102 - accuracy: 0.7435 - val_loss: 0.5363 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7472 - val_loss: 0.5368 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7513 - val_loss: 0.5466 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7546 - val_loss: 0.5464 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7594 - val_loss: 0.5461 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7633 - val_loss: 0.5383 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4739 - accuracy: 0.7655 - val_loss: 0.5497 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4676 - accuracy: 0.7701 - val_loss: 0.5481 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4653 - accuracy: 0.7723 - val_loss: 0.5445 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4560 - accuracy: 0.7758 - val_loss: 0.5532 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4508 - accuracy: 0.7799 - val_loss: 0.5570 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4465 - accuracy: 0.7800 - val_loss: 0.5529 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4429 - accuracy: 0.7814 - val_loss: 0.5648 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4334 - accuracy: 0.7860 - val_loss: 0.5688 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 21/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4286 - accuracy: 0.7911
Epoch 21: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4290 - accuracy: 0.7905 - val_loss: 0.5714 - val_accuracy: 0.7223 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4311641449106105
Confusion Matrix :
 [[3025 1298]
 [1162 3161]]
Accuracy on test set:    0.7154753643303262
Sensitivity:    0.731205181586861 	 Specificity:    0.6997455470737913
Precision  : 0.7089033415564028
Area Under Curve:    0.7154753643303261
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6049 - accuracy: 0.6671 - val_loss: 0.5574 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5558 - accuracy: 0.7143 - val_loss: 0.5427 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7240 - val_loss: 0.5385 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5317 - accuracy: 0.7307 - val_loss: 0.5359 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7368 - val_loss: 0.5387 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7405 - val_loss: 0.5327 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7482 - val_loss: 0.5354 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7487 - val_loss: 0.5344 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7542 - val_loss: 0.5349 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4906 - accuracy: 0.7565 - val_loss: 0.5441 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7605 - val_loss: 0.5408 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4790 - accuracy: 0.7640 - val_loss: 0.5459 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4706 - accuracy: 0.7685 - val_loss: 0.5414 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4647 - accuracy: 0.7715
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4645 - accuracy: 0.7716 - val_loss: 0.5410 - val_accuracy: 0.7203 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.436418260979646
Confusion Matrix :
 [[3194 1129]
 [1309 3014]]
Accuracy on test set:    0.7180198935924127
Sensitivity:    0.6972010178117048 	 Specificity:    0.7388387693731205
Precision  : 0.7274921554429158
Area Under Curve:    0.7180198935924127
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6029 - accuracy: 0.6714 - val_loss: 0.5609 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5584 - accuracy: 0.7113 - val_loss: 0.5509 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7244 - val_loss: 0.5400 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7317 - val_loss: 0.5401 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5268 - accuracy: 0.7344 - val_loss: 0.5425 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7399 - val_loss: 0.5365 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5105 - accuracy: 0.7439 - val_loss: 0.5367 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7481 - val_loss: 0.5365 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7507 - val_loss: 0.5446 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7555 - val_loss: 0.5387 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4857 - accuracy: 0.7594 - val_loss: 0.5529 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4797 - accuracy: 0.7628 - val_loss: 0.5423 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4755 - accuracy: 0.7643 - val_loss: 0.5553 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4706 - accuracy: 0.7674 - val_loss: 0.5580 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4614 - accuracy: 0.7718 - val_loss: 0.5534 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4582 - accuracy: 0.7757 - val_loss: 0.5625 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4533 - accuracy: 0.7771
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4529 - accuracy: 0.7771 - val_loss: 0.5489 - val_accuracy: 0.7218 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.43474055407267176
Confusion Matrix :
 [[2920 1403]
 [1047 3276]]
Accuracy on test set:    0.7166319685403655
Sensitivity:    0.7578070784177654 	 Specificity:    0.6754568586629656
Precision  : 0.700149604616371
Area Under Curve:    0.7166319685403653
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5995 - accuracy: 0.6704 - val_loss: 0.5589 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5567 - accuracy: 0.7120 - val_loss: 0.5456 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7248 - val_loss: 0.5410 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5285 - accuracy: 0.7329 - val_loss: 0.5370 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5221 - accuracy: 0.7385 - val_loss: 0.5346 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7426 - val_loss: 0.5327 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7470 - val_loss: 0.5351 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5002 - accuracy: 0.7519 - val_loss: 0.5318 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7553 - val_loss: 0.5365 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7596 - val_loss: 0.5352 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7628 - val_loss: 0.5370 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4761 - accuracy: 0.7659 - val_loss: 0.5424 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4677 - accuracy: 0.7715 - val_loss: 0.5412 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4608 - accuracy: 0.7753 - val_loss: 0.5514 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4560 - accuracy: 0.7790
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4554 - accuracy: 0.7793 - val_loss: 0.5498 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4217644740699706
Confusion Matrix :
 [[2906 1417]
 [1088 3235]]
Accuracy on test set:    0.7102706453851492
Sensitivity:    0.748322923895443 	 Specificity:    0.6722183668748555
Precision  : 0.6953998280309545
Area Under Curve:    0.7102706453851491
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6079 - accuracy: 0.6657 - val_loss: 0.5608 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5574 - accuracy: 0.7121 - val_loss: 0.5538 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7213 - val_loss: 0.5504 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7300 - val_loss: 0.5397 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7334 - val_loss: 0.5396 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5210 - accuracy: 0.7389 - val_loss: 0.5429 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5150 - accuracy: 0.7412 - val_loss: 0.5409 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7452 - val_loss: 0.5395 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7514 - val_loss: 0.5381 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4990 - accuracy: 0.7512 - val_loss: 0.5358 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7556 - val_loss: 0.5456 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7615 - val_loss: 0.5427 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4785 - accuracy: 0.7660 - val_loss: 0.5471 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4752 - accuracy: 0.7665
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4754 - accuracy: 0.7660 - val_loss: 0.5442 - val_accuracy: 0.7224 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4496127552004577
Confusion Matrix :
 [[3076 1247]
 [1133 3190]]
Accuracy on test set:    0.7247281980106408
Sensitivity:    0.7379134860050891 	 Specificity:    0.7115429100161924
Precision  : 0.7189542483660131
Area Under Curve:    0.7247281980106408
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6054 - accuracy: 0.6673 - val_loss: 0.5605 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5572 - accuracy: 0.7126 - val_loss: 0.5450 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7236 - val_loss: 0.5406 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7300 - val_loss: 0.5440 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5264 - accuracy: 0.7348 - val_loss: 0.5382 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7383 - val_loss: 0.5358 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7447 - val_loss: 0.5341 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7481 - val_loss: 0.5353 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4985 - accuracy: 0.7530 - val_loss: 0.5392 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4901 - accuracy: 0.7567 - val_loss: 0.5367 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4844 - accuracy: 0.7601 - val_loss: 0.5368 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4772 - accuracy: 0.7631
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4771 - accuracy: 0.7628 - val_loss: 0.5432 - val_accuracy: 0.7253 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4660247391355772
Confusion Matrix :
 [[2850 1473]
 [ 856 3467]]
Accuracy on test set:    0.7306268794818414
Sensitivity:    0.8019893592412677 	 Specificity:    0.659264399722415
Precision  : 0.7018218623481781
Area Under Curve:    0.7306268794818414
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6119 - accuracy: 0.6639 - val_loss: 0.5638 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7120 - val_loss: 0.5490 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7222 - val_loss: 0.5444 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7298 - val_loss: 0.5399 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7350 - val_loss: 0.5387 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7389 - val_loss: 0.5380 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7446 - val_loss: 0.5430 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7453 - val_loss: 0.5466 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7517 - val_loss: 0.5442 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4927 - accuracy: 0.7536
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7536 - val_loss: 0.5386 - val_accuracy: 0.7237 - lr: 0.0010
271/271 [==============================] - 0s 670us/step
Independent Testing Matthews Correlation:  0.47081542285670186
Confusion Matrix :
 [[3318 1005]
 [1287 3036]]
Accuracy on test set:    0.7349063150589868
Sensitivity:    0.7022900763358778 	 Specificity:    0.7675225537820958
Precision  : 0.7512991833704529
Area Under Curve:    0.7349063150589867
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6084 - accuracy: 0.6653 - val_loss: 0.5700 - val_accuracy: 0.7028 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5649 - accuracy: 0.7077 - val_loss: 0.5587 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5512 - accuracy: 0.7169 - val_loss: 0.5529 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7252 - val_loss: 0.5486 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7304 - val_loss: 0.5499 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7350 - val_loss: 0.5433 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7385 - val_loss: 0.5474 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7438 - val_loss: 0.5421 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5062 - accuracy: 0.7472 - val_loss: 0.5395 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7522 - val_loss: 0.5454 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7553 - val_loss: 0.5437 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4837 - accuracy: 0.7598 - val_loss: 0.5447 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7640 - val_loss: 0.5476 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4699 - accuracy: 0.7719 - val_loss: 0.5534 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4647 - accuracy: 0.7723 - val_loss: 0.5626 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4604 - accuracy: 0.7742 - val_loss: 0.5618 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4526 - accuracy: 0.7798 - val_loss: 0.5586 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 18/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4429 - accuracy: 0.7833
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4439 - accuracy: 0.7828 - val_loss: 0.5632 - val_accuracy: 0.7158 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.5028009744021156
Confusion Matrix :
 [[3122 1201]
 [ 952 3371]]
Accuracy on test set:    0.7509831135785334
Sensitivity:    0.7797825584085126 	 Specificity:    0.7221836687485542
Precision  : 0.7373140857392826
Area Under Curve:    0.7509831135785335
(8646, 4352) (8646,)
Mean MCC = 0.4475 + 0.0239 and Mean AUC = 0.7231 + 0.0119
Mean Sensitivity = 0.7465 + 0.0310 and Mean Specificity = 0.6997 + 0.0340 and Mean Accuracy = 0.7231 + 0.0119
Mean Precision = 0.7139 + 0.0184





Seed   : 160750
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6098 - accuracy: 0.6626 - val_loss: 0.5666 - val_accuracy: 0.6998 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7098 - val_loss: 0.5540 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7229 - val_loss: 0.5508 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7269 - val_loss: 0.5420 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7345 - val_loss: 0.5435 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5149 - accuracy: 0.7408 - val_loss: 0.5375 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7463 - val_loss: 0.5385 - val_accuracy: 0.7217 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7480 - val_loss: 0.5467 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7517 - val_loss: 0.5377 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4889 - accuracy: 0.7559 - val_loss: 0.5393 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4844 - accuracy: 0.7570 - val_loss: 0.5433 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4792 - accuracy: 0.7619 - val_loss: 0.5435 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4735 - accuracy: 0.7656 - val_loss: 0.5418 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7681 - val_loss: 0.5432 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4638 - accuracy: 0.7689
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4628 - accuracy: 0.7695 - val_loss: 0.5562 - val_accuracy: 0.7169 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.41650740132752423
Confusion Matrix :
 [[2971 1352]
 [1172 3151]]
Accuracy on test set:    0.7080730973860745
Sensitivity:    0.7288919731667823 	 Specificity:    0.6872542216053666
Precision  : 0.6997557184099489
Area Under Curve:    0.7080730973860745
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6079 - accuracy: 0.6678 - val_loss: 0.5670 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7130 - val_loss: 0.5597 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7235 - val_loss: 0.5548 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7303 - val_loss: 0.5544 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7345 - val_loss: 0.5441 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7402 - val_loss: 0.5564 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7436 - val_loss: 0.5438 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7479 - val_loss: 0.5411 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5008 - accuracy: 0.7511 - val_loss: 0.5483 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4924 - accuracy: 0.7558 - val_loss: 0.5421 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4881 - accuracy: 0.7599 - val_loss: 0.5477 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7636 - val_loss: 0.5474 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4771 - accuracy: 0.7642 - val_loss: 0.5486 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4690 - accuracy: 0.7701 - val_loss: 0.5645 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4604 - accuracy: 0.7753
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4610 - accuracy: 0.7750 - val_loss: 0.5466 - val_accuracy: 0.7247 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4395931261990873
Confusion Matrix :
 [[2870 1453]
 [ 981 3342]]
Accuracy on test set:    0.7184825352764284
Sensitivity:    0.7730742539902845 	 Specificity:    0.6638908165625723
Precision  : 0.6969760166840459
Area Under Curve:    0.7184825352764284
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6137 - accuracy: 0.6632 - val_loss: 0.5734 - val_accuracy: 0.7011 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7114 - val_loss: 0.5579 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7252 - val_loss: 0.5484 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5280 - accuracy: 0.7340 - val_loss: 0.5489 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5199 - accuracy: 0.7373 - val_loss: 0.5460 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7425 - val_loss: 0.5393 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7488 - val_loss: 0.5450 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7514 - val_loss: 0.5389 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7581 - val_loss: 0.5455 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4865 - accuracy: 0.7583 - val_loss: 0.5508 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4782 - accuracy: 0.7648 - val_loss: 0.5480 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7651 - val_loss: 0.5496 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4673 - accuracy: 0.7714 - val_loss: 0.5782 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4631 - accuracy: 0.7708 - val_loss: 0.5512 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4539 - accuracy: 0.7784 - val_loss: 0.5532 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 16/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4498 - accuracy: 0.7825
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4493 - accuracy: 0.7822 - val_loss: 0.5580 - val_accuracy: 0.7203 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4288697704992525
Confusion Matrix :
 [[3093 1230]
 [1239 3084]]
Accuracy on test set:    0.7144344205412908
Sensitivity:    0.7133934767522554 	 Specificity:    0.7154753643303262
Precision  : 0.7148817802503477
Area Under Curve:    0.7144344205412908
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6040 - accuracy: 0.6699 - val_loss: 0.5668 - val_accuracy: 0.7016 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5586 - accuracy: 0.7141 - val_loss: 0.5541 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7237 - val_loss: 0.5456 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 4/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7305 - val_loss: 0.5427 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7364 - val_loss: 0.5405 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7424 - val_loss: 0.5421 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5122 - accuracy: 0.7437 - val_loss: 0.5389 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7489 - val_loss: 0.5494 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7516 - val_loss: 0.5404 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7533 - val_loss: 0.5395 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4922 - accuracy: 0.7562 - val_loss: 0.5430 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 12/400
257/274 [===========================>..] - ETA: 0s - loss: 0.4828 - accuracy: 0.7626
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7620 - val_loss: 0.5410 - val_accuracy: 0.7197 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.43979217848678576
Confusion Matrix :
 [[3145 1178]
 [1244 3079]]
Accuracy on test set:    0.7198704603284756
Sensitivity:    0.712236872542216 	 Specificity:    0.7275040481147351
Precision  : 0.7232793046746535
Area Under Curve:    0.7198704603284756
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6171 - accuracy: 0.6544 - val_loss: 0.5669 - val_accuracy: 0.7052 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5640 - accuracy: 0.7080 - val_loss: 0.5534 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7216 - val_loss: 0.5494 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7287 - val_loss: 0.5422 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5267 - accuracy: 0.7331 - val_loss: 0.5428 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5195 - accuracy: 0.7385 - val_loss: 0.5423 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5127 - accuracy: 0.7434 - val_loss: 0.5408 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7473 - val_loss: 0.5439 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7503 - val_loss: 0.5432 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
257/274 [===========================>..] - ETA: 0s - loss: 0.4944 - accuracy: 0.7548
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7551 - val_loss: 0.5442 - val_accuracy: 0.7206 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4409868364207061
Confusion Matrix :
 [[3158 1165]
 [1252 3071]]
Accuracy on test set:    0.7204487624334952
Sensitivity:    0.7103863058061531 	 Specificity:    0.7305112190608374
Precision  : 0.7249763928234183
Area Under Curve:    0.7204487624334952
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6077 - accuracy: 0.6657 - val_loss: 0.5650 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5597 - accuracy: 0.7115 - val_loss: 0.5549 - val_accuracy: 0.7059 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7222 - val_loss: 0.5495 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7299 - val_loss: 0.5439 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5274 - accuracy: 0.7338 - val_loss: 0.5406 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5191 - accuracy: 0.7383 - val_loss: 0.5489 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7443 - val_loss: 0.5376 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7490 - val_loss: 0.5390 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7510 - val_loss: 0.5387 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4961 - accuracy: 0.7537 - val_loss: 0.5428 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7566 - val_loss: 0.5488 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7601 - val_loss: 0.5457 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7612 - val_loss: 0.5428 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4764 - accuracy: 0.7637 - val_loss: 0.5463 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4701 - accuracy: 0.7689 - val_loss: 0.5512 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4637 - accuracy: 0.7741 - val_loss: 0.5421 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4603 - accuracy: 0.7750 - val_loss: 0.5492 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4552 - accuracy: 0.7776 - val_loss: 0.5607 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 19/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4514 - accuracy: 0.7799
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4516 - accuracy: 0.7794 - val_loss: 0.5525 - val_accuracy: 0.7212 - lr: 0.0010
271/271 [==============================] - 0s 675us/step
Independent Testing Matthews Correlation:  0.44142968873825694
Confusion Matrix :
 [[2937 1386]
 [1035 3288]]
Accuracy on test set:    0.7199861207494795
Sensitivity:    0.7605829285218598 	 Specificity:    0.6793893129770993
Precision  : 0.7034659820282413
Area Under Curve:    0.7199861207494795
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5988 - accuracy: 0.6752 - val_loss: 0.5652 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5554 - accuracy: 0.7136 - val_loss: 0.5537 - val_accuracy: 0.7077 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7238 - val_loss: 0.5522 - val_accuracy: 0.7092 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7316 - val_loss: 0.5461 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7364 - val_loss: 0.5491 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5159 - accuracy: 0.7398 - val_loss: 0.5533 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7460 - val_loss: 0.5436 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7490 - val_loss: 0.5671 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4972 - accuracy: 0.7533
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7533 - val_loss: 0.5483 - val_accuracy: 0.7154 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4412271531848817
Confusion Matrix :
 [[3398  925]
 [1508 2815]]
Accuracy on test set:    0.7185981956974323
Sensitivity:    0.6511681702521397 	 Specificity:    0.786028221142725
Precision  : 0.7526737967914439
Area Under Curve:    0.7185981956974323
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6016 - accuracy: 0.6721 - val_loss: 0.5651 - val_accuracy: 0.7012 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5595 - accuracy: 0.7110 - val_loss: 0.5548 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7228 - val_loss: 0.5484 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7327 - val_loss: 0.5562 - val_accuracy: 0.7003 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7363 - val_loss: 0.5431 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7414 - val_loss: 0.5441 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7428 - val_loss: 0.5455 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7468 - val_loss: 0.5451 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7507 - val_loss: 0.5468 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4936 - accuracy: 0.7558 - val_loss: 0.5485 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7590 - val_loss: 0.5409 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7643 - val_loss: 0.5486 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4781 - accuracy: 0.7634
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4787 - accuracy: 0.7629 - val_loss: 0.5418 - val_accuracy: 0.7164 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4534907339744451
Confusion Matrix :
 [[3268 1055]
 [1311 3012]]
Accuracy on test set:    0.7263474439046959
Sensitivity:    0.6967383761276891 	 Specificity:    0.7559565116817025
Precision  : 0.7405950331940004
Area Under Curve:    0.7263474439046957
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6088 - accuracy: 0.6630 - val_loss: 0.5757 - val_accuracy: 0.6943 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5620 - accuracy: 0.7090 - val_loss: 0.5598 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7210 - val_loss: 0.5526 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7267 - val_loss: 0.5465 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5304 - accuracy: 0.7324 - val_loss: 0.5422 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7386 - val_loss: 0.5494 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7411 - val_loss: 0.5405 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5105 - accuracy: 0.7438 - val_loss: 0.5415 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5009 - accuracy: 0.7511 - val_loss: 0.5407 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7523 - val_loss: 0.5400 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7560 - val_loss: 0.5408 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7612 - val_loss: 0.5455 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4785 - accuracy: 0.7633 - val_loss: 0.5479 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4725 - accuracy: 0.7665 - val_loss: 0.5508 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4665 - accuracy: 0.7702 - val_loss: 0.5534 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4607 - accuracy: 0.7741
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4617 - accuracy: 0.7736 - val_loss: 0.5529 - val_accuracy: 0.7194 - lr: 0.0010
271/271 [==============================] - 0s 672us/step
Independent Testing Matthews Correlation:  0.46180995719612583
Confusion Matrix :
 [[3301 1022]
 [1309 3014]]
Accuracy on test set:    0.7303955586398334
Sensitivity:    0.6972010178117048 	 Specificity:    0.7635900994679621
Precision  : 0.7467789890981169
Area Under Curve:    0.7303955586398334
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6165 - accuracy: 0.6614 - val_loss: 0.5713 - val_accuracy: 0.7014 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5625 - accuracy: 0.7113 - val_loss: 0.5594 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5499 - accuracy: 0.7187 - val_loss: 0.5572 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7292 - val_loss: 0.5543 - val_accuracy: 0.7070 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7336 - val_loss: 0.5517 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5212 - accuracy: 0.7395 - val_loss: 0.5536 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7432 - val_loss: 0.5484 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7458 - val_loss: 0.5482 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 9/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7500 - val_loss: 0.5492 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7531 - val_loss: 0.5611 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7600 - val_loss: 0.5597 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 12/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4810 - accuracy: 0.7633
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7631 - val_loss: 0.5550 - val_accuracy: 0.7182 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.491066462770197
Confusion Matrix :
 [[3416  907]
 [1302 3021]]
Accuracy on test set:    0.7445061300023132
Sensitivity:    0.6988202637057599 	 Specificity:    0.7901919962988665
Precision  : 0.7690936863543788
Area Under Curve:    0.7445061300023132
(8646, 4352) (8646,)
Mean MCC = 0.4455 + 0.0191 and Mean AUC = 0.7221 + 0.0094
Mean Sensitivity = 0.7142 + 0.0326 and Mean Specificity = 0.7300 + 0.0419 and Mean Accuracy = 0.7221 + 0.0094
Mean Precision = 0.7272 + 0.0232





Seed   : 851631
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6027 - accuracy: 0.6708 - val_loss: 0.5616 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5565 - accuracy: 0.7143 - val_loss: 0.5457 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7260 - val_loss: 0.5412 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5310 - accuracy: 0.7296 - val_loss: 0.5363 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7341 - val_loss: 0.5433 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5157 - accuracy: 0.7394 - val_loss: 0.5355 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5106 - accuracy: 0.7445 - val_loss: 0.5344 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7497 - val_loss: 0.5384 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7534 - val_loss: 0.5340 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7551 - val_loss: 0.5356 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4836 - accuracy: 0.7600
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4847 - accuracy: 0.7595 - val_loss: 0.5343 - val_accuracy: 0.7258 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.42524354388072005
Confusion Matrix :
 [[2949 1374]
 [1114 3209]]
Accuracy on test set:    0.712236872542216
Sensitivity:    0.7423085820032385 	 Specificity:    0.6821651630811936
Precision  : 0.7001963779183941
Area Under Curve:    0.712236872542216
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6036 - accuracy: 0.6669 - val_loss: 0.5549 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7145 - val_loss: 0.5456 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7244 - val_loss: 0.5585 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7311 - val_loss: 0.5357 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7388 - val_loss: 0.5339 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7422 - val_loss: 0.5343 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7462 - val_loss: 0.5407 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7516 - val_loss: 0.5351 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4929 - accuracy: 0.7565 - val_loss: 0.5389 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4873 - accuracy: 0.7592 - val_loss: 0.5390 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4816 - accuracy: 0.7629 - val_loss: 0.5420 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4750 - accuracy: 0.7682 - val_loss: 0.5472 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4690 - accuracy: 0.7703
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4694 - accuracy: 0.7700 - val_loss: 0.5494 - val_accuracy: 0.7206 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.41893027886544765
Confusion Matrix :
 [[2667 1656]
 [ 885 3438]]
Accuracy on test set:    0.7061068702290076
Sensitivity:    0.7952810548230396 	 Specificity:    0.6169326856349757
Precision  : 0.6749116607773852
Area Under Curve:    0.7061068702290076
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6124 - accuracy: 0.6590 - val_loss: 0.5662 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7110 - val_loss: 0.5488 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7208 - val_loss: 0.5443 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7292 - val_loss: 0.5389 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5279 - accuracy: 0.7336 - val_loss: 0.5359 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7385 - val_loss: 0.5351 - val_accuracy: 0.7335 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7434 - val_loss: 0.5337 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5102 - accuracy: 0.7443 - val_loss: 0.5352 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7507 - val_loss: 0.5382 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7548 - val_loss: 0.5347 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4891 - accuracy: 0.7597
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7584 - val_loss: 0.5351 - val_accuracy: 0.7292 - lr: 0.0010
271/271 [==============================] - 0s 669us/step
Independent Testing Matthews Correlation:  0.43234772258583265
Confusion Matrix :
 [[3082 1241]
 [1213 3110]]
Accuracy on test set:    0.7161693268563497
Sensitivity:    0.7194078186444599 	 Specificity:    0.7129308350682396
Precision  : 0.7147782119053091
Area Under Curve:    0.7161693268563498
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6028 - accuracy: 0.6676 - val_loss: 0.5652 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5583 - accuracy: 0.7114 - val_loss: 0.5456 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7234 - val_loss: 0.5498 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7280 - val_loss: 0.5353 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5262 - accuracy: 0.7343 - val_loss: 0.5356 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5200 - accuracy: 0.7379 - val_loss: 0.5336 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7415 - val_loss: 0.5355 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7453 - val_loss: 0.5337 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7493 - val_loss: 0.5400 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7543 - val_loss: 0.5380 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7553 - val_loss: 0.5375 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7607 - val_loss: 0.5417 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4821 - accuracy: 0.7594
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4821 - accuracy: 0.7592 - val_loss: 0.5403 - val_accuracy: 0.7291 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.4393849771118718
Confusion Matrix :
 [[3000 1323]
 [1103 3220]]
Accuracy on test set:    0.7194078186444599
Sensitivity:    0.744853111265325 	 Specificity:    0.6939625260235948
Precision  : 0.7087827426810478
Area Under Curve:    0.7194078186444598
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6141 - accuracy: 0.6597 - val_loss: 0.5624 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5628 - accuracy: 0.7095 - val_loss: 0.5474 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7201 - val_loss: 0.5411 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7280 - val_loss: 0.5353 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5286 - accuracy: 0.7304 - val_loss: 0.5440 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7336 - val_loss: 0.5297 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7413 - val_loss: 0.5300 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7452 - val_loss: 0.5321 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7465 - val_loss: 0.5296 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7487 - val_loss: 0.5349 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7539 - val_loss: 0.5319 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7574 - val_loss: 0.5426 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4804 - accuracy: 0.7593
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7596 - val_loss: 0.5432 - val_accuracy: 0.7227 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4447374368193649
Confusion Matrix :
 [[2927 1396]
 [1012 3311]]
Accuracy on test set:    0.7214897062225306
Sensitivity:    0.7659033078880407 	 Specificity:    0.6770761045570206
Precision  : 0.7034204376460591
Area Under Curve:    0.7214897062225306
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6034 - accuracy: 0.6699 - val_loss: 0.5564 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7117 - val_loss: 0.5441 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7219 - val_loss: 0.5441 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7288 - val_loss: 0.5325 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7329 - val_loss: 0.5298 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5222 - accuracy: 0.7362 - val_loss: 0.5297 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5172 - accuracy: 0.7404 - val_loss: 0.5369 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7460 - val_loss: 0.5446 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7483 - val_loss: 0.5336 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7504 - val_loss: 0.5368 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7558 - val_loss: 0.5392 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7567 - val_loss: 0.5439 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4844 - accuracy: 0.7595 - val_loss: 0.5612 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4747 - accuracy: 0.7644 - val_loss: 0.5374 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4692 - accuracy: 0.7698 - val_loss: 0.5401 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4657 - accuracy: 0.7689 - val_loss: 0.5495 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4601 - accuracy: 0.7753 - val_loss: 0.5536 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4546 - accuracy: 0.7759 - val_loss: 0.5611 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4484 - accuracy: 0.7797 - val_loss: 0.5564 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 20/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4443 - accuracy: 0.7811
Epoch 20: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4442 - accuracy: 0.7811 - val_loss: 0.5575 - val_accuracy: 0.7253 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4468555959632855
Confusion Matrix :
 [[2863 1460]
 [ 945 3378]]
Accuracy on test set:    0.7218366874855424
Sensitivity:    0.7814018043025677 	 Specificity:    0.6622715706685173
Precision  : 0.6982224059528731
Area Under Curve:    0.7218366874855424
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6095 - accuracy: 0.6643 - val_loss: 0.5693 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5589 - accuracy: 0.7121 - val_loss: 0.5436 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7227 - val_loss: 0.5429 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7309 - val_loss: 0.5411 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5214 - accuracy: 0.7376 - val_loss: 0.5362 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7425 - val_loss: 0.5455 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7452 - val_loss: 0.5344 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7493 - val_loss: 0.5436 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4954 - accuracy: 0.7548 - val_loss: 0.5339 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4868 - accuracy: 0.7589 - val_loss: 0.5375 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4791 - accuracy: 0.7644 - val_loss: 0.5433 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4723 - accuracy: 0.7683 - val_loss: 0.5409 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7685 - val_loss: 0.5517 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4600 - accuracy: 0.7744 - val_loss: 0.5487 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4527 - accuracy: 0.7782 - val_loss: 0.5489 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4489 - accuracy: 0.7793 - val_loss: 0.5522 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 17/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4436 - accuracy: 0.7859
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4438 - accuracy: 0.7855 - val_loss: 0.5481 - val_accuracy: 0.7253 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4584446023684953
Confusion Matrix :
 [[3035 1288]
 [1056 3267]]
Accuracy on test set:    0.7288919731667823
Sensitivity:    0.7557251908396947 	 Specificity:    0.70205875549387
Precision  : 0.7172338090010977
Area Under Curve:    0.7288919731667823
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6148 - accuracy: 0.6643 - val_loss: 0.5584 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5597 - accuracy: 0.7108 - val_loss: 0.5560 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7228 - val_loss: 0.5381 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7286 - val_loss: 0.5362 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5256 - accuracy: 0.7350 - val_loss: 0.5341 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7400 - val_loss: 0.5330 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7431 - val_loss: 0.5358 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5050 - accuracy: 0.7463 - val_loss: 0.5361 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4985 - accuracy: 0.7529 - val_loss: 0.5311 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7536 - val_loss: 0.5363 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4891 - accuracy: 0.7560
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7564 - val_loss: 0.5405 - val_accuracy: 0.7282 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4573543929747715
Confusion Matrix :
 [[3176 1147]
 [1199 3124]]
Accuracy on test set:    0.7286606523247745
Sensitivity:    0.72264631043257 	 Specificity:    0.7346749942169789
Precision  : 0.7314446265511589
Area Under Curve:    0.7286606523247745
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6215 - accuracy: 0.6504 - val_loss: 0.5659 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5709 - accuracy: 0.7013 - val_loss: 0.5468 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7129 - val_loss: 0.5494 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7184 - val_loss: 0.5489 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7231 - val_loss: 0.5385 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7281 - val_loss: 0.5373 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5276 - accuracy: 0.7306 - val_loss: 0.5322 - val_accuracy: 0.7334 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7320 - val_loss: 0.5333 - val_accuracy: 0.7335 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5187 - accuracy: 0.7338 - val_loss: 0.5326 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5116 - accuracy: 0.7405 - val_loss: 0.5371 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7418 - val_loss: 0.5341 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7435 - val_loss: 0.5352 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.5000 - accuracy: 0.7463
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5006 - accuracy: 0.7461 - val_loss: 0.5358 - val_accuracy: 0.7253 - lr: 0.0010

271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.48459254142731023
Confusion Matrix :
 [[2973 1350]
 [ 890 3433]]
Accuracy on test set:    0.7409206569511912
Sensitivity:    0.7941244506130002 	 Specificity:    0.6877168632893824
Precision  : 0.7177503658791553
Area Under Curve:    0.7409206569511912
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6134 - accuracy: 0.6600 - val_loss: 0.5642 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5660 - accuracy: 0.7074 - val_loss: 0.5519 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5500 - accuracy: 0.7194 - val_loss: 0.5429 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7267 - val_loss: 0.5418 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7311 - val_loss: 0.5362 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5231 - accuracy: 0.7367 - val_loss: 0.5391 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7391 - val_loss: 0.5381 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7453 - val_loss: 0.5338 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7468 - val_loss: 0.5384 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7501 - val_loss: 0.5328 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7550 - val_loss: 0.5366 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4855 - accuracy: 0.7595 - val_loss: 0.5401 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4793 - accuracy: 0.7612 - val_loss: 0.5473 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4734 - accuracy: 0.7654 - val_loss: 0.5476 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4673 - accuracy: 0.7715 - val_loss: 0.5626 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4588 - accuracy: 0.7738
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4590 - accuracy: 0.7736 - val_loss: 0.5528 - val_accuracy: 0.7196 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.5033103655063347
Confusion Matrix :
 [[3190 1133]
 [1015 3308]]
Accuracy on test set:    0.7515614156835531
Sensitivity:    0.7652093453620171 	 Specificity:    0.7379134860050891
Precision  : 0.7448772798919162
Area Under Curve:    0.7515614156835532
(8646, 4352) (8646,)
Mean MCC = 0.4511 + 0.0249 and Mean AUC = 0.7247 + 0.0128
Mean Sensitivity = 0.7587 + 0.0255 and Mean Specificity = 0.6908 + 0.0336 and Mean Accuracy = 0.7247 + 0.0128
Mean Precision = 0.7112 + 0.0182





Seed   : 726560
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6019 - accuracy: 0.6701 - val_loss: 0.5638 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5537 - accuracy: 0.7160 - val_loss: 0.5485 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7235 - val_loss: 0.5455 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5300 - accuracy: 0.7312 - val_loss: 0.5375 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5210 - accuracy: 0.7377 - val_loss: 0.5420 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5144 - accuracy: 0.7434 - val_loss: 0.5376 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7440 - val_loss: 0.5380 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7477 - val_loss: 0.5468 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7539 - val_loss: 0.5397 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4878 - accuracy: 0.7582 - val_loss: 0.5368 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7627 - val_loss: 0.5429 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4758 - accuracy: 0.7658
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4766 - accuracy: 0.7652 - val_loss: 0.5436 - val_accuracy: 0.7210 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.42745724481188546
Confusion Matrix :
 [[3205 1118]
 [1360 2963]]
Accuracy on test set:    0.7133934767522554
Sensitivity:    0.6854036548693038 	 Specificity:    0.741383298635207
Precision  : 0.7260475373682921
Area Under Curve:    0.7133934767522554
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6189 - accuracy: 0.6541 - val_loss: 0.5742 - val_accuracy: 0.7001 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5659 - accuracy: 0.7060 - val_loss: 0.5637 - val_accuracy: 0.7026 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7204 - val_loss: 0.5524 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7278 - val_loss: 0.5446 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5287 - accuracy: 0.7315 - val_loss: 0.5433 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5225 - accuracy: 0.7363 - val_loss: 0.5476 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7417 - val_loss: 0.5398 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7438 - val_loss: 0.5420 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7475 - val_loss: 0.5444 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7516 - val_loss: 0.5562 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7557 - val_loss: 0.5473 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4834 - accuracy: 0.7593
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4844 - accuracy: 0.7593 - val_loss: 0.5472 - val_accuracy: 0.7208 - lr: 0.0010
271/271 [==============================] - 0s 668us/step
Independent Testing Matthews Correlation:  0.43809462956506057
Confusion Matrix :
 [[3042 1281]
 [1149 3174]]
Accuracy on test set:    0.7189451769604441
Sensitivity:    0.7342123525329632 	 Specificity:    0.703678001387925
Precision  : 0.7124579124579125
Area Under Curve:    0.7189451769604441
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6021 - accuracy: 0.6696 - val_loss: 0.5566 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5568 - accuracy: 0.7123 - val_loss: 0.5567 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7258 - val_loss: 0.5531 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5317 - accuracy: 0.7301 - val_loss: 0.5364 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7381 - val_loss: 0.5381 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7433 - val_loss: 0.5375 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7449 - val_loss: 0.5415 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5025 - accuracy: 0.7488 - val_loss: 0.5369 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7532 - val_loss: 0.5399 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7584 - val_loss: 0.5428 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7619 - val_loss: 0.5406 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4763 - accuracy: 0.7660 - val_loss: 0.5423 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 13/400
256/274 [===========================>..] - ETA: 0s - loss: 0.4731 - accuracy: 0.7684
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4731 - accuracy: 0.7682 - val_loss: 0.5440 - val_accuracy: 0.7230 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.43461325261475936
Confusion Matrix :
 [[2961 1362]
 [1086 3237]]
Accuracy on test set:    0.7168632893823733
Sensitivity:    0.7487855655794587 	 Specificity:    0.684941013185288
Precision  : 0.7038486627527724
Area Under Curve:    0.7168632893823733
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6016 - accuracy: 0.6689 - val_loss: 0.5599 - val_accuracy: 0.7107 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5549 - accuracy: 0.7152 - val_loss: 0.5518 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7254 - val_loss: 0.5402 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7313 - val_loss: 0.5414 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5234 - accuracy: 0.7363 - val_loss: 0.5382 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7437 - val_loss: 0.5349 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7461 - val_loss: 0.5361 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7489 - val_loss: 0.5362 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7518 - val_loss: 0.5417 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7581 - val_loss: 0.5416 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7598 - val_loss: 0.5397 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4777 - accuracy: 0.7626 - val_loss: 0.5486 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 13/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4731 - accuracy: 0.7688
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4732 - accuracy: 0.7685 - val_loss: 0.5476 - val_accuracy: 0.7251 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4370599885349844
Confusion Matrix :
 [[3022 1301]
 [1134 3189]]
Accuracy on test set:    0.7183668748554245
Sensitivity:    0.7376821651630812 	 Specificity:    0.6990515845477677
Precision  : 0.7102449888641426
Area Under Curve:    0.7183668748554245
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6061 - accuracy: 0.6677 - val_loss: 0.5582 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5554 - accuracy: 0.7145 - val_loss: 0.5450 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7247 - val_loss: 0.5443 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5294 - accuracy: 0.7324 - val_loss: 0.5379 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5240 - accuracy: 0.7366 - val_loss: 0.5379 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5141 - accuracy: 0.7432 - val_loss: 0.5453 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7473 - val_loss: 0.5442 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7520 - val_loss: 0.5428 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7559 - val_loss: 0.5374 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7603 - val_loss: 0.5424 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4796 - accuracy: 0.7657 - val_loss: 0.5554 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4771 - accuracy: 0.7656 - val_loss: 0.5435 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4668 - accuracy: 0.7714 - val_loss: 0.5471 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4620 - accuracy: 0.7742 - val_loss: 0.5520 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4563 - accuracy: 0.7773 - val_loss: 0.5601 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 16/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4467 - accuracy: 0.7825
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4469 - accuracy: 0.7822 - val_loss: 0.5628 - val_accuracy: 0.7196 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.44430733448864457
Confusion Matrix :
 [[3213 1110]
 [1294 3029]]
Accuracy on test set:    0.7219523479065464
Sensitivity:    0.7006708304418228 	 Specificity:    0.7432338653712699
Precision  : 0.7318192800193284
Area Under Curve:    0.7219523479065465
(8646, 4352) (8646,)
Epoch 1/400

274/274 [==============================] - 2s 4ms/step - loss: 0.6012 - accuracy: 0.6713 - val_loss: 0.5603 - val_accuracy: 0.7092 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5565 - accuracy: 0.7126 - val_loss: 0.5445 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7230 - val_loss: 0.5420 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7299 - val_loss: 0.5585 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7338 - val_loss: 0.5408 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7412 - val_loss: 0.5387 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7439 - val_loss: 0.5377 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7495 - val_loss: 0.5384 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7506 - val_loss: 0.5362 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7544 - val_loss: 0.5405 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4902 - accuracy: 0.7561 - val_loss: 0.5433 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7603 - val_loss: 0.5434 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4776 - accuracy: 0.7648 - val_loss: 0.5439 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4729 - accuracy: 0.7670
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4729 - accuracy: 0.7668 - val_loss: 0.5486 - val_accuracy: 0.7190 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.43841723218421724
Confusion Matrix :
 [[3072 1251]
 [1177 3146]]
Accuracy on test set:    0.719176497802452
Sensitivity:    0.727735368956743 	 Specificity:    0.710617626648161
Precision  : 0.7154878326131453
Area Under Curve:    0.719176497802452
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6094 - accuracy: 0.6644 - val_loss: 0.5640 - val_accuracy: 0.6985 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5620 - accuracy: 0.7098 - val_loss: 0.5617 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7216 - val_loss: 0.5454 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7282 - val_loss: 0.5467 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7320 - val_loss: 0.5416 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5212 - accuracy: 0.7391 - val_loss: 0.5432 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7448 - val_loss: 0.5440 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5054 - accuracy: 0.7487 - val_loss: 0.5482 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7542 - val_loss: 0.5439 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7567 - val_loss: 0.5480 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4856 - accuracy: 0.7621 - val_loss: 0.5490 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4774 - accuracy: 0.7675
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4776 - accuracy: 0.7670 - val_loss: 0.5498 - val_accuracy: 0.7125 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4376871501085781
Confusion Matrix :
 [[3132 1191]
 [1240 3083]]
Accuracy on test set:    0.7188295165394402
Sensitivity:    0.7131621559102476 	 Specificity:    0.7244968771686329
Precision  : 0.7213383247543285
Area Under Curve:    0.7188295165394402
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6044 - accuracy: 0.6667 - val_loss: 0.5652 - val_accuracy: 0.6998 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5600 - accuracy: 0.7105 - val_loss: 0.5532 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7231 - val_loss: 0.5592 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7282 - val_loss: 0.5420 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5306 - accuracy: 0.7300 - val_loss: 0.5430 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7363 - val_loss: 0.5437 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7404 - val_loss: 0.5439 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7426 - val_loss: 0.5413 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7449 - val_loss: 0.5443 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7486 - val_loss: 0.5447 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4951 - accuracy: 0.7524 - val_loss: 0.5450 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4894 - accuracy: 0.7573
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4901 - accuracy: 0.7569 - val_loss: 0.5450 - val_accuracy: 0.7169 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4531670350699017
Confusion Matrix :
 [[3127 1196]
 [1168 3155]]
Accuracy on test set:    0.7265787647467037
Sensitivity:    0.7298172565348138 	 Specificity:    0.7233402729585936
Precision  : 0.7251206619168007
Area Under Curve:    0.7265787647467037
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6224 - accuracy: 0.6552 - val_loss: 0.5730 - val_accuracy: 0.6960 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5676 - accuracy: 0.7070 - val_loss: 0.5583 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5506 - accuracy: 0.7183 - val_loss: 0.5577 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7284 - val_loss: 0.5547 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7298 - val_loss: 0.5495 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7368 - val_loss: 0.5461 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5165 - accuracy: 0.7414 - val_loss: 0.5481 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5111 - accuracy: 0.7446 - val_loss: 0.5510 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5054 - accuracy: 0.7478 - val_loss: 0.5487 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7480 - val_loss: 0.5569 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7540 - val_loss: 0.5489 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7592 - val_loss: 0.5517 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7600 - val_loss: 0.5606 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7620 - val_loss: 0.5514 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4722 - accuracy: 0.7656 - val_loss: 0.5567 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4655 - accuracy: 0.7710 - val_loss: 0.5572 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4590 - accuracy: 0.7740 - val_loss: 0.5622 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4554 - accuracy: 0.7759 - val_loss: 0.5658 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4526 - accuracy: 0.7780 - val_loss: 0.5680 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4453 - accuracy: 0.7823 - val_loss: 0.5662 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4383 - accuracy: 0.7867 - val_loss: 0.5739 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 22/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4353 - accuracy: 0.7863
Epoch 22: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4361 - accuracy: 0.7856 - val_loss: 0.5735 - val_accuracy: 0.7154 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4426650856953241
Confusion Matrix :
 [[3207 1116]
 [1295 3028]]
Accuracy on test set:    0.7211427249595188
Sensitivity:    0.7004395095998149 	 Specificity:    0.7418459403192228
Precision  : 0.7306949806949807
Area Under Curve:    0.7211427249595189
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6041 - accuracy: 0.6682 - val_loss: 0.5657 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7099 - val_loss: 0.5532 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7197 - val_loss: 0.5525 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7290 - val_loss: 0.5605 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5268 - accuracy: 0.7361 - val_loss: 0.5451 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5192 - accuracy: 0.7406 - val_loss: 0.5481 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7441 - val_loss: 0.5527 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7493 - val_loss: 0.5468 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7525 - val_loss: 0.5437 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7564 - val_loss: 0.5560 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7626 - val_loss: 0.5507 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4793 - accuracy: 0.7641 - val_loss: 0.5738 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4726 - accuracy: 0.7659 - val_loss: 0.5522 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4658 - accuracy: 0.7714
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4659 - accuracy: 0.7712 - val_loss: 0.5570 - val_accuracy: 0.7154 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.5001561411284139
Confusion Matrix :
 [[3215 1108]
 [1053 3270]]
Accuracy on test set:    0.750057830210502
Sensitivity:    0.7564191533657183 	 Specificity:    0.7436965070552857
Precision  : 0.7469164001827319
Area Under Curve:    0.750057830210502
(8646, 4352) (8646,)
Mean MCC = 0.4454 + 0.0193 and Mean AUC = 0.7225 + 0.0097
Mean Sensitivity = 0.7234 + 0.0217 and Mean Specificity = 0.7216 + 0.0202 and Mean Accuracy = 0.7225 + 0.0097
Mean Precision = 0.7224 + 0.0119





Seed   : 645882
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6057 - accuracy: 0.6693 - val_loss: 0.5672 - val_accuracy: 0.7002 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5555 - accuracy: 0.7147 - val_loss: 0.5571 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7260 - val_loss: 0.5572 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7326 - val_loss: 0.5449 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5223 - accuracy: 0.7358 - val_loss: 0.5400 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7443 - val_loss: 0.5373 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7471 - val_loss: 0.5407 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7512 - val_loss: 0.5378 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7557 - val_loss: 0.5383 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7594 - val_loss: 0.5410 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7656 - val_loss: 0.5412 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4739 - accuracy: 0.7660
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4747 - accuracy: 0.7656 - val_loss: 0.5611 - val_accuracy: 0.7114 - lr: 0.0010

271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4126077738490493
Confusion Matrix :
 [[2287 2036]
 [ 604 3719]]
Accuracy on test set:    0.6946564885496184
Sensitivity:    0.8602822114272496 	 Specificity:    0.529030765671987
Precision  : 0.64622067767159
Area Under Curve:    0.6946564885496184
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6039 - accuracy: 0.6670 - val_loss: 0.5658 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7137 - val_loss: 0.5591 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7240 - val_loss: 0.5464 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7302 - val_loss: 0.5423 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.7368 - val_loss: 0.5439 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7427 - val_loss: 0.5506 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7472 - val_loss: 0.5411 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7521 - val_loss: 0.5470 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7535 - val_loss: 0.5414 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7585 - val_loss: 0.5484 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4806 - accuracy: 0.7642 - val_loss: 0.5427 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4752 - accuracy: 0.7663 - val_loss: 0.5431 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7689 - val_loss: 0.5505 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4652 - accuracy: 0.7706 - val_loss: 0.5506 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4560 - accuracy: 0.7752 - val_loss: 0.5523 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4510 - accuracy: 0.7768 - val_loss: 0.5557 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4459 - accuracy: 0.7799
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4463 - accuracy: 0.7796 - val_loss: 0.5630 - val_accuracy: 0.7222 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.43141711010517625
Confusion Matrix :
 [[3103 1220]
 [1238 3085]]
Accuracy on test set:    0.715706685172334
Sensitivity:    0.7136247975942632 	 Specificity:    0.7177885727504049
Precision  : 0.7166085946573751
Area Under Curve:    0.715706685172334
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5989 - accuracy: 0.6710 - val_loss: 0.5656 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5587 - accuracy: 0.7119 - val_loss: 0.5685 - val_accuracy: 0.6978 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7247 - val_loss: 0.5640 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7306 - val_loss: 0.5660 - val_accuracy: 0.6973 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5227 - accuracy: 0.7344 - val_loss: 0.5458 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7401 - val_loss: 0.5459 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7441 - val_loss: 0.5428 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7485 - val_loss: 0.5420 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7517 - val_loss: 0.5461 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4947 - accuracy: 0.7553 - val_loss: 0.5447 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7581 - val_loss: 0.5483 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7598 - val_loss: 0.5448 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4784 - accuracy: 0.7624
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4786 - accuracy: 0.7623 - val_loss: 0.5477 - val_accuracy: 0.7206 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4509491831497044
Confusion Matrix :
 [[2876 1447]
 [ 940 3383]]
Accuracy on test set:    0.7239185750636132
Sensitivity:    0.7825584085126069 	 Specificity:    0.6652787416146195
Precision  : 0.7004140786749482
Area Under Curve:    0.7239185750636132
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6017 - accuracy: 0.6732 - val_loss: 0.5646 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5570 - accuracy: 0.7128 - val_loss: 0.5643 - val_accuracy: 0.7030 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7247 - val_loss: 0.5497 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7303 - val_loss: 0.5471 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5221 - accuracy: 0.7386 - val_loss: 0.5458 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5150 - accuracy: 0.7417 - val_loss: 0.5462 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7447 - val_loss: 0.5461 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7491 - val_loss: 0.5449 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7535 - val_loss: 0.5510 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4910 - accuracy: 0.7558 - val_loss: 0.5466 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4850 - accuracy: 0.7614
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7619 - val_loss: 0.5597 - val_accuracy: 0.7146 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4277372174079878
Confusion Matrix :
 [[3228 1095]
 [1383 2940]]
Accuracy on test set:    0.7133934767522554
Sensitivity:    0.6800832755031229 	 Specificity:    0.7467036780013879
Precision  : 0.7286245353159851
Area Under Curve:    0.7133934767522554
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6126 - accuracy: 0.6610 - val_loss: 0.5650 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7104 - val_loss: 0.5506 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7232 - val_loss: 0.5515 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7283 - val_loss: 0.5447 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5251 - accuracy: 0.7343 - val_loss: 0.5455 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7406 - val_loss: 0.5407 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7448 - val_loss: 0.5395 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7467 - val_loss: 0.5411 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7541 - val_loss: 0.5424 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7563 - val_loss: 0.5479 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7620 - val_loss: 0.5396 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4779 - accuracy: 0.7630 - val_loss: 0.5470 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4716 - accuracy: 0.7670 - val_loss: 0.5490 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4683 - accuracy: 0.7700 - val_loss: 0.5511 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4598 - accuracy: 0.7745 - val_loss: 0.5526 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4543 - accuracy: 0.7789
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4554 - accuracy: 0.7779 - val_loss: 0.5619 - val_accuracy: 0.7191 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.43076592152934523
Confusion Matrix :
 [[2800 1523]
 [ 954 3369]]
Accuracy on test set:    0.7135091371732593
Sensitivity:    0.7793199167244969 	 Specificity:    0.6476983576220218
Precision  : 0.6886753883892068
Area Under Curve:    0.7135091371732594
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6031 - accuracy: 0.6698 - val_loss: 0.5625 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5580 - accuracy: 0.7128 - val_loss: 0.5596 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7242 - val_loss: 0.5449 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7294 - val_loss: 0.5457 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5274 - accuracy: 0.7348 - val_loss: 0.5421 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5196 - accuracy: 0.7387 - val_loss: 0.5387 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7421 - val_loss: 0.5390 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7465 - val_loss: 0.5402 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7492 - val_loss: 0.5373 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7537 - val_loss: 0.5418 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7563 - val_loss: 0.5420 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4859 - accuracy: 0.7602 - val_loss: 0.5408 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4793 - accuracy: 0.7649 - val_loss: 0.5430 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4734 - accuracy: 0.7696 - val_loss: 0.5456 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4679 - accuracy: 0.7711 - val_loss: 0.5446 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4628 - accuracy: 0.7745 - val_loss: 0.5527 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4577 - accuracy: 0.7789 - val_loss: 0.5553 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4519 - accuracy: 0.7810 - val_loss: 0.5544 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4471 - accuracy: 0.7819 - val_loss: 0.5711 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 20/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4408 - accuracy: 0.7864
Epoch 20: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4425 - accuracy: 0.7850 - val_loss: 0.5688 - val_accuracy: 0.7217 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.4489177364865965
Confusion Matrix :
 [[2936 1387]
 [1003 3320]]
Accuracy on test set:    0.7235715938006014
Sensitivity:    0.7679851954661115 	 Specificity:    0.6791579921350914
Precision  : 0.7053324835351604
Area Under Curve:    0.7235715938006015
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6101 - accuracy: 0.6622 - val_loss: 0.5749 - val_accuracy: 0.6978 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5598 - accuracy: 0.7097 - val_loss: 0.5566 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7216 - val_loss: 0.5618 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7287 - val_loss: 0.5481 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7340 - val_loss: 0.5490 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5206 - accuracy: 0.7387 - val_loss: 0.5401 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7429 - val_loss: 0.5423 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7460 - val_loss: 0.5451 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7473 - val_loss: 0.5454 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4956 - accuracy: 0.7529 - val_loss: 0.5452 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
272/274 [============================>.] - ETA: 0s - loss: 0.4907 - accuracy: 0.7567
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7569 - val_loss: 0.5463 - val_accuracy: 0.7208 - lr: 0.0010
271/271 [==============================] - 0s 665us/step
Independent Testing Matthews Correlation:  0.4596039674342165
Confusion Matrix :
 [[2986 1337]
 [1005 3318]]
Accuracy on test set:    0.7291232940087902
Sensitivity:    0.7675225537820958 	 Specificity:    0.6907240342354846
Precision  : 0.7127819548872181
Area Under Curve:    0.7291232940087902
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6130 - accuracy: 0.6614 - val_loss: 0.5709 - val_accuracy: 0.6993 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5642 - accuracy: 0.7089 - val_loss: 0.5571 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7198 - val_loss: 0.5507 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7270 - val_loss: 0.5487 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7305 - val_loss: 0.5433 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7363 - val_loss: 0.5433 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7413 - val_loss: 0.5390 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7448 - val_loss: 0.5365 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5047 - accuracy: 0.7475 - val_loss: 0.5428 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7530 - val_loss: 0.5534 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7541 - val_loss: 0.5440 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4875 - accuracy: 0.7577 - val_loss: 0.5419 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 13/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4823 - accuracy: 0.7605
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4827 - accuracy: 0.7604 - val_loss: 0.5608 - val_accuracy: 0.7124 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4320210156365429
Confusion Matrix :
 [[3458  865]
 [1619 2704]]
Accuracy on test set:    0.7126995142262318
Sensitivity:    0.6254915567892667 	 Specificity:    0.7999074716631969
Precision  : 0.7576351919305128
Area Under Curve:    0.7126995142262318
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6055 - accuracy: 0.6675 - val_loss: 0.5692 - val_accuracy: 0.6993 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7119 - val_loss: 0.5524 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7213 - val_loss: 0.5540 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7319 - val_loss: 0.5438 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7367 - val_loss: 0.5416 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7394 - val_loss: 0.5395 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7424 - val_loss: 0.5431 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5057 - accuracy: 0.7472 - val_loss: 0.5362 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7531 - val_loss: 0.5476 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4901 - accuracy: 0.7585 - val_loss: 0.5434 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4838 - accuracy: 0.7622
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4854 - accuracy: 0.7614 - val_loss: 0.5439 - val_accuracy: 0.7208 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.45509201883086015
Confusion Matrix :
 [[3390  933]
 [1436 2887]]
Accuracy on test set:    0.726000462641684
Sensitivity:    0.667823270876706 	 Specificity:    0.7841776544066621
Precision  : 0.7557591623036649
Area Under Curve:    0.726000462641684
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6092 - accuracy: 0.6650 - val_loss: 0.5737 - val_accuracy: 0.6992 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5638 - accuracy: 0.7096 - val_loss: 0.5577 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5519 - accuracy: 0.7172 - val_loss: 0.5759 - val_accuracy: 0.6957 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7270 - val_loss: 0.5488 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7301 - val_loss: 0.5467 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7342 - val_loss: 0.5471 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7395 - val_loss: 0.5500 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7418 - val_loss: 0.5543 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7477 - val_loss: 0.5467 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7476 - val_loss: 0.5462 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7531 - val_loss: 0.5460 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7539 - val_loss: 0.5625 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4851 - accuracy: 0.7611 - val_loss: 0.5557 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4802 - accuracy: 0.7618
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7614 - val_loss: 0.5556 - val_accuracy: 0.7181 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.48210070610866823
Confusion Matrix :
 [[3300 1023]
 [1218 3105]]
Accuracy on test set:    0.7408049965301874
Sensitivity:    0.7182512144344205 	 Specificity:    0.7633587786259542
Precision  : 0.7521802325581395
Area Under Curve:    0.7408049965301873
(8646, 4352) (8646,)
Mean MCC = 0.4431 + 0.0190 and Mean AUC = 0.7193 + 0.0117
Mean Sensitivity = 0.7363 + 0.0650 and Mean Specificity = 0.7024 + 0.0756 and Mean Accuracy = 0.7193 + 0.0117
Mean Precision = 0.7164 + 0.0328





Seed   : 731811

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5989 - accuracy: 0.6731 - val_loss: 0.5556 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5548 - accuracy: 0.7140 - val_loss: 0.5409 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7264 - val_loss: 0.5350 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5301 - accuracy: 0.7303 - val_loss: 0.5380 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5199 - accuracy: 0.7381 - val_loss: 0.5328 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7427 - val_loss: 0.5303 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5057 - accuracy: 0.7478 - val_loss: 0.5281 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7519 - val_loss: 0.5266 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7558 - val_loss: 0.5379 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7577 - val_loss: 0.5300 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4805 - accuracy: 0.7632 - val_loss: 0.5369 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4742 - accuracy: 0.7670 - val_loss: 0.5407 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4682 - accuracy: 0.7715 - val_loss: 0.5417 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4601 - accuracy: 0.7740
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4610 - accuracy: 0.7733 - val_loss: 0.5379 - val_accuracy: 0.7226 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.41210345027620093
Confusion Matrix :
 [[2936 1387]
 [1157 3166]]
Accuracy on test set:    0.7057598889659958
Sensitivity:    0.7323617857969003 	 Specificity:    0.6791579921350914
Precision  : 0.6953656929497035
Area Under Curve:    0.7057598889659958
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6016 - accuracy: 0.6709 - val_loss: 0.5583 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5570 - accuracy: 0.7130 - val_loss: 0.5463 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7219 - val_loss: 0.5440 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7303 - val_loss: 0.5470 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7363 - val_loss: 0.5330 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7392 - val_loss: 0.5332 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7434 - val_loss: 0.5352 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7474 - val_loss: 0.5367 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5002 - accuracy: 0.7519 - val_loss: 0.5327 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7546 - val_loss: 0.5305 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7590 - val_loss: 0.5361 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7627 - val_loss: 0.5376 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4779 - accuracy: 0.7643 - val_loss: 0.5434 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4717 - accuracy: 0.7668 - val_loss: 0.5463 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4659 - accuracy: 0.7723
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4659 - accuracy: 0.7723 - val_loss: 0.5702 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.44499689968032113
Confusion Matrix :
 [[2649 1674]
 [ 768 3555]]
Accuracy on test set:    0.7175572519083969
Sensitivity:    0.8223455933379598 	 Specificity:    0.6127689104788342
Precision  : 0.6798623063683304
Area Under Curve:    0.7175572519083969
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6061 - accuracy: 0.6680 - val_loss: 0.5640 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5558 - accuracy: 0.7131 - val_loss: 0.5433 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7235 - val_loss: 0.5404 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5297 - accuracy: 0.7323 - val_loss: 0.5393 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7365 - val_loss: 0.5346 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5150 - accuracy: 0.7404 - val_loss: 0.5363 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7460 - val_loss: 0.5357 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7489 - val_loss: 0.5318 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7533 - val_loss: 0.5340 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7564 - val_loss: 0.5378 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7607 - val_loss: 0.5414 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4740 - accuracy: 0.7656 - val_loss: 0.5369 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4682 - accuracy: 0.7707
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7703 - val_loss: 0.5540 - val_accuracy: 0.7283 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4435137363541355
Confusion Matrix :
 [[2729 1594]
 [ 841 3482]]
Accuracy on test set:    0.7183668748554245
Sensitivity:    0.8054591718713856 	 Specificity:    0.6312745778394634
Precision  : 0.685973207249803
Area Under Curve:    0.7183668748554244
(8646, 4352) (8646,)
Epoch 1/400

274/274 [==============================] - 2s 3ms/step - loss: 0.6135 - accuracy: 0.6609 - val_loss: 0.5684 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7121 - val_loss: 0.5484 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7213 - val_loss: 0.5463 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7280 - val_loss: 0.5389 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7348 - val_loss: 0.5359 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7374 - val_loss: 0.5365 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7405 - val_loss: 0.5368 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7447 - val_loss: 0.5362 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7495 - val_loss: 0.5387 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7529 - val_loss: 0.5467 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7559 - val_loss: 0.5471 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4869 - accuracy: 0.7590 - val_loss: 0.5389 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4807 - accuracy: 0.7635
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4812 - accuracy: 0.7632 - val_loss: 0.5394 - val_accuracy: 0.7227 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4364144780820632
Confusion Matrix :
 [[2882 1441]
 [1005 3318]]
Accuracy on test set:    0.7170946102243813
Sensitivity:    0.7675225537820958 	 Specificity:    0.6666666666666666
Precision  : 0.6972052952300903
Area Under Curve:    0.7170946102243814
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6070 - accuracy: 0.6648 - val_loss: 0.5610 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5633 - accuracy: 0.7079 - val_loss: 0.5509 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7206 - val_loss: 0.5446 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7274 - val_loss: 0.5384 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7338 - val_loss: 0.5374 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5206 - accuracy: 0.7378 - val_loss: 0.5370 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7406 - val_loss: 0.5375 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7470 - val_loss: 0.5368 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5005 - accuracy: 0.7493 - val_loss: 0.5373 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7519 - val_loss: 0.5433 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7545 - val_loss: 0.5352 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7565 - val_loss: 0.5395 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4806 - accuracy: 0.7607 - val_loss: 0.5435 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4741 - accuracy: 0.7656 - val_loss: 0.5422 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4663 - accuracy: 0.7704 - val_loss: 0.5444 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 16/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4624 - accuracy: 0.7711
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4633 - accuracy: 0.7709 - val_loss: 0.5554 - val_accuracy: 0.7224 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.43861875262174227
Confusion Matrix :
 [[2820 1503]
 [ 940 3383]]
Accuracy on test set:    0.7174415914873931
Sensitivity:    0.7825584085126069 	 Specificity:    0.6523247744621791
Precision  : 0.6923864101514531
Area Under Curve:    0.717441591487393
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6027 - accuracy: 0.6699 - val_loss: 0.5623 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5557 - accuracy: 0.7131 - val_loss: 0.5449 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7222 - val_loss: 0.5447 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7288 - val_loss: 0.5389 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5247 - accuracy: 0.7353 - val_loss: 0.5340 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5195 - accuracy: 0.7396 - val_loss: 0.5359 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5122 - accuracy: 0.7444 - val_loss: 0.5352 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5052 - accuracy: 0.7483 - val_loss: 0.5323 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5006 - accuracy: 0.7505 - val_loss: 0.5354 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7553 - val_loss: 0.5376 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7592 - val_loss: 0.5420 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4818 - accuracy: 0.7622 - val_loss: 0.5387 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4770 - accuracy: 0.7639 - val_loss: 0.5428 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7691 - val_loss: 0.5424 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4630 - accuracy: 0.7743
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4637 - accuracy: 0.7738 - val_loss: 0.5540 - val_accuracy: 0.7086 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.42019114985281975
Confusion Matrix :
 [[3537  786]
 [1768 2555]]
Accuracy on test set:    0.7046032847559565
Sensitivity:    0.5910247513300948 	 Specificity:    0.8181818181818182
Precision  : 0.764741095480395
Area Under Curve:    0.7046032847559565
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6016 - accuracy: 0.6725 - val_loss: 0.5687 - val_accuracy: 0.6974 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7138 - val_loss: 0.5567 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7228 - val_loss: 0.5487 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7297 - val_loss: 0.5432 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7352 - val_loss: 0.5487 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5177 - accuracy: 0.7394 - val_loss: 0.5431 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7435 - val_loss: 0.5450 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7497 - val_loss: 0.5422 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4990 - accuracy: 0.7526 - val_loss: 0.5465 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4932 - accuracy: 0.7543 - val_loss: 0.5482 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4868 - accuracy: 0.7580 - val_loss: 0.5433 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4805 - accuracy: 0.7628 - val_loss: 0.5464 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4735 - accuracy: 0.7674 - val_loss: 0.5475 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4682 - accuracy: 0.7697 - val_loss: 0.5533 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4626 - accuracy: 0.7726 - val_loss: 0.5604 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4575 - accuracy: 0.7761
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4570 - accuracy: 0.7766 - val_loss: 0.5595 - val_accuracy: 0.7244 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.45900599827204186
Confusion Matrix :
 [[3117 1206]
 [1133 3190]]
Accuracy on test set:    0.729470275271802
Sensitivity:    0.7379134860050891 	 Specificity:    0.721027064538515
Precision  : 0.7256596906278435
Area Under Curve:    0.7294702752718019
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6032 - accuracy: 0.6699 - val_loss: 0.5697 - val_accuracy: 0.7006 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7114 - val_loss: 0.5544 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7209 - val_loss: 0.5497 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7299 - val_loss: 0.5463 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5262 - accuracy: 0.7351 - val_loss: 0.5419 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7381 - val_loss: 0.5458 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7439 - val_loss: 0.5392 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7456 - val_loss: 0.5391 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7498 - val_loss: 0.5473 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4949 - accuracy: 0.7536 - val_loss: 0.5402 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4889 - accuracy: 0.7577 - val_loss: 0.5444 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4841 - accuracy: 0.7603 - val_loss: 0.5473 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7634 - val_loss: 0.5467 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4701 - accuracy: 0.7692
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4704 - accuracy: 0.7687 - val_loss: 0.5470 - val_accuracy: 0.7212 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.47175655610423006
Confusion Matrix :
 [[3138 1185]
 [1099 3224]]
Accuracy on test set:    0.7358315984270183
Sensitivity:    0.7457783946333565 	 Specificity:    0.7258848022206801
Precision  : 0.7312315717849852
Area Under Curve:    0.7358315984270183
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6173 - accuracy: 0.6557 - val_loss: 0.5698 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5661 - accuracy: 0.7052 - val_loss: 0.5585 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5500 - accuracy: 0.7172 - val_loss: 0.5482 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7250 - val_loss: 0.5515 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7306 - val_loss: 0.5426 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7329 - val_loss: 0.5430 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5219 - accuracy: 0.7374 - val_loss: 0.5402 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7403 - val_loss: 0.5397 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5111 - accuracy: 0.7435 - val_loss: 0.5431 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5055 - accuracy: 0.7445 - val_loss: 0.5418 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7494 - val_loss: 0.5446 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4952 - accuracy: 0.7492
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4963 - accuracy: 0.7487 - val_loss: 0.5488 - val_accuracy: 0.7200 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4757644498009007
Confusion Matrix :
 [[2964 1359]
 [ 918 3405]]
Accuracy on test set:    0.7366412213740458
Sensitivity:    0.78764746703678 	 Specificity:    0.6856349757113116
Precision  : 0.714735516372796
Area Under Curve:    0.7366412213740459
(8646, 4352) (8646,)
Epoch 1/400

274/274 [==============================] - 1s 3ms/step - loss: 0.6256 - accuracy: 0.6533 - val_loss: 0.5824 - val_accuracy: 0.6974 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5692 - accuracy: 0.7054 - val_loss: 0.5643 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5530 - accuracy: 0.7177 - val_loss: 0.5558 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7249 - val_loss: 0.5511 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7297 - val_loss: 0.5484 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5295 - accuracy: 0.7322 - val_loss: 0.5464 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5231 - accuracy: 0.7351 - val_loss: 0.5422 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7422 - val_loss: 0.5460 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7443 - val_loss: 0.5465 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7484 - val_loss: 0.5452 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7509 - val_loss: 0.5550 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4919 - accuracy: 0.7560
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7562 - val_loss: 0.5475 - val_accuracy: 0.7221 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.49583779643331255
Confusion Matrix :
 [[3186 1137]
 [1043 3280]]
Accuracy on test set:    0.7478602822114272
Sensitivity:    0.758732361785797 	 Specificity:    0.7369882026370576
Precision  : 0.7425854652479058
Area Under Curve:    0.7478602822114273
(8646, 4352) (8646,)
Mean MCC = 0.4498 + 0.0245 and Mean AUC = 0.7231 + 0.0133
Mean Sensitivity = 0.7531 + 0.0607 and Mean Specificity = 0.6930 + 0.0568 and Mean Accuracy = 0.7231 + 0.0133
Mean Precision = 0.7130 + 0.0262





Seed   : 472416
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6005 - accuracy: 0.6707 - val_loss: 0.5655 - val_accuracy: 0.7010 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5546 - accuracy: 0.7152 - val_loss: 0.5524 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7262 - val_loss: 0.5490 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7336 - val_loss: 0.5449 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5223 - accuracy: 0.7361 - val_loss: 0.5419 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7411 - val_loss: 0.5417 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7441 - val_loss: 0.5459 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7483 - val_loss: 0.5394 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7511 - val_loss: 0.5384 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7560 - val_loss: 0.5396 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4879 - accuracy: 0.7602 - val_loss: 0.5431 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7603 - val_loss: 0.5411 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4753 - accuracy: 0.7663
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4760 - accuracy: 0.7659 - val_loss: 0.5392 - val_accuracy: 0.7217 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4179515643418188
Confusion Matrix :
 [[3000 1323]
 [1194 3129]]
Accuracy on test set:    0.7088827203331021
Sensitivity:    0.7238029146426093 	 Specificity:    0.6939625260235948
Precision  : 0.7028301886792453
Area Under Curve:    0.708882720333102
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6052 - accuracy: 0.6683 - val_loss: 0.5707 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5572 - accuracy: 0.7133 - val_loss: 0.5529 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7225 - val_loss: 0.5484 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7293 - val_loss: 0.5483 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5249 - accuracy: 0.7363 - val_loss: 0.5453 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7393 - val_loss: 0.5466 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7435 - val_loss: 0.5407 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5078 - accuracy: 0.7475 - val_loss: 0.5430 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7489 - val_loss: 0.5447 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7509 - val_loss: 0.5407 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4910 - accuracy: 0.7555 - val_loss: 0.5487 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4866 - accuracy: 0.7567 - val_loss: 0.5469 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4768 - accuracy: 0.7641 - val_loss: 0.5447 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4741 - accuracy: 0.7642 - val_loss: 0.5502 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 15/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4686 - accuracy: 0.7701
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4696 - accuracy: 0.7688 - val_loss: 0.5529 - val_accuracy: 0.7176 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.43744835820029804
Confusion Matrix :
 [[3128 1195]
 [1237 3086]]
Accuracy on test set:    0.7187138561184363
Sensitivity:    0.7138561184362711 	 Specificity:    0.7235715938006014
Precision  : 0.7208596122401308
Area Under Curve:    0.7187138561184362
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6032 - accuracy: 0.6690 - val_loss: 0.5645 - val_accuracy: 0.7014 - lr: 0.0010

Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5599 - accuracy: 0.7114 - val_loss: 0.5632 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7215 - val_loss: 0.5484 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7304 - val_loss: 0.5487 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5268 - accuracy: 0.7342 - val_loss: 0.5439 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7382 - val_loss: 0.5485 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7426 - val_loss: 0.5455 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7456 - val_loss: 0.5452 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7505 - val_loss: 0.5410 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7535 - val_loss: 0.5448 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4889 - accuracy: 0.7566 - val_loss: 0.5494 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4827 - accuracy: 0.7603 - val_loss: 0.5386 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7624 - val_loss: 0.5498 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4738 - accuracy: 0.7646 - val_loss: 0.5454 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7699 - val_loss: 0.5602 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4614 - accuracy: 0.7718 - val_loss: 0.5577 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4568 - accuracy: 0.7727
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4571 - accuracy: 0.7729 - val_loss: 0.5602 - val_accuracy: 0.7206 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4433293277057764
Confusion Matrix :
 [[2847 1476]
 [ 945 3378]]
Accuracy on test set:    0.7199861207494795
Sensitivity:    0.7814018043025677 	 Specificity:    0.6585704371963914
Precision  : 0.695920889987639
Area Under Curve:    0.7199861207494795
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6017 - accuracy: 0.6732 - val_loss: 0.5740 - val_accuracy: 0.6913 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5569 - accuracy: 0.7147 - val_loss: 0.5610 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7256 - val_loss: 0.5508 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7342 - val_loss: 0.5438 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7355 - val_loss: 0.5407 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7431 - val_loss: 0.5387 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7460 - val_loss: 0.5389 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7514 - val_loss: 0.5372 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4933 - accuracy: 0.7560 - val_loss: 0.5442 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7597 - val_loss: 0.5374 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4800 - accuracy: 0.7637
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4797 - accuracy: 0.7638 - val_loss: 0.5553 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.44008137568304057
Confusion Matrix :
 [[2733 1590]
 [ 858 3465]]
Accuracy on test set:    0.7168632893823733
Sensitivity:    0.8015267175572519 	 Specificity:    0.6321998612074948
Precision  : 0.685459940652819
Area Under Curve:    0.7168632893823733
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6228 - accuracy: 0.6510 - val_loss: 0.5651 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7118 - val_loss: 0.5476 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7227 - val_loss: 0.5424 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7293 - val_loss: 0.5413 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7353 - val_loss: 0.5387 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7420 - val_loss: 0.5454 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5119 - accuracy: 0.7435 - val_loss: 0.5349 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7468 - val_loss: 0.5346 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7510 - val_loss: 0.5352 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7529 - val_loss: 0.5419 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7550 - val_loss: 0.5370 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7589 - val_loss: 0.5461 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4795 - accuracy: 0.7633 - val_loss: 0.5404 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4752 - accuracy: 0.7655 - val_loss: 0.5453 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7698 - val_loss: 0.5405 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4641 - accuracy: 0.7706 - val_loss: 0.5512 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 17/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4591 - accuracy: 0.7760
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4591 - accuracy: 0.7761 - val_loss: 0.5525 - val_accuracy: 0.7174 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.4398019237381686
Confusion Matrix :
 [[3148 1175]
 [1247 3076]]
Accuracy on test set:    0.7198704603284756
Sensitivity:    0.7115429100161924 	 Specificity:    0.7281980106407587
Precision  : 0.7235944483650906
Area Under Curve:    0.7198704603284756
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6102 - accuracy: 0.6641 - val_loss: 0.5605 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5604 - accuracy: 0.7098 - val_loss: 0.5510 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7235 - val_loss: 0.5442 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5301 - accuracy: 0.7321 - val_loss: 0.5465 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7375 - val_loss: 0.5397 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7409 - val_loss: 0.5396 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7474 - val_loss: 0.5461 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5025 - accuracy: 0.7513 - val_loss: 0.5447 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4933 - accuracy: 0.7572 - val_loss: 0.5415 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4883 - accuracy: 0.7597 - val_loss: 0.5441 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4804 - accuracy: 0.7619
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7616 - val_loss: 0.5505 - val_accuracy: 0.7178 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4235805197281669
Confusion Matrix :
 [[3202 1121]
 [1374 2949]]
Accuracy on test set:    0.7114272495951885
Sensitivity:    0.6821651630811936 	 Specificity:    0.7406893361091834
Precision  : 0.7245700245700246
Area Under Curve:    0.7114272495951884
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6088 - accuracy: 0.6649 - val_loss: 0.5624 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5598 - accuracy: 0.7105 - val_loss: 0.5580 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7206 - val_loss: 0.5478 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7289 - val_loss: 0.5451 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7333 - val_loss: 0.5463 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7362 - val_loss: 0.5429 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7409 - val_loss: 0.5415 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7452 - val_loss: 0.5456 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7474 - val_loss: 0.5480 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7516 - val_loss: 0.5421 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7554 - val_loss: 0.5514 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7604 - val_loss: 0.5511 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4786 - accuracy: 0.7629 - val_loss: 0.5470 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4746 - accuracy: 0.7635 - val_loss: 0.5541 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4676 - accuracy: 0.7689 - val_loss: 0.5518 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4620 - accuracy: 0.7718
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4628 - accuracy: 0.7713 - val_loss: 0.5582 - val_accuracy: 0.7127 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4549921574494637
Confusion Matrix :
 [[3211 1112]
 [1245 3078]]
Accuracy on test set:    0.7273883876937312
Sensitivity:    0.7120055517002082 	 Specificity:    0.7427712236872542
Precision  : 0.7346062052505966
Area Under Curve:    0.7273883876937313
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6092 - accuracy: 0.6644 - val_loss: 0.5670 - val_accuracy: 0.7029 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7141 - val_loss: 0.5503 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7228 - val_loss: 0.5515 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7273 - val_loss: 0.5423 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7348 - val_loss: 0.5368 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5219 - accuracy: 0.7360 - val_loss: 0.5391 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5165 - accuracy: 0.7397 - val_loss: 0.5358 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7450 - val_loss: 0.5419 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7475 - val_loss: 0.5406 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7530 - val_loss: 0.5400 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7521 - val_loss: 0.5421 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 12/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4877 - accuracy: 0.7562
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7560 - val_loss: 0.5489 - val_accuracy: 0.7226 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.44675423100498834
Confusion Matrix :
 [[2821 1502]
 [ 908 3415]]
Accuracy on test set:    0.7212583853805228
Sensitivity:    0.7899606754568587 	 Specificity:    0.6525560953041869
Precision  : 0.6945291844620703
Area Under Curve:    0.7212583853805228
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6071 - accuracy: 0.6657 - val_loss: 0.5644 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7102 - val_loss: 0.5523 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7230 - val_loss: 0.5530 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 4/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7283 - val_loss: 0.5504 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7345 - val_loss: 0.5586 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5192 - accuracy: 0.7394 - val_loss: 0.5419 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5120 - accuracy: 0.7433 - val_loss: 0.5483 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7472 - val_loss: 0.5490 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4973 - accuracy: 0.7531 - val_loss: 0.5394 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7574 - val_loss: 0.5393 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7596 - val_loss: 0.5449 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7653 - val_loss: 0.5438 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4721 - accuracy: 0.7692 - val_loss: 0.5449 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4658 - accuracy: 0.7730 - val_loss: 0.5552 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 15/400
252/274 [==========================>...] - ETA: 0s - loss: 0.4583 - accuracy: 0.7762
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4578 - accuracy: 0.7763 - val_loss: 0.5630 - val_accuracy: 0.7159 - lr: 0.0010
271/271 [==============================] - 0s 665us/step
Independent Testing Matthews Correlation:  0.48275699181485143
Confusion Matrix :
 [[2958 1365]
 [ 884 3439]]
Accuracy on test set:    0.739879713162156
Sensitivity:    0.7955123756650474 	 Specificity:    0.6842470506592644
Precision  : 0.7158617818484596
Area Under Curve:    0.739879713162156
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6107 - accuracy: 0.6630 - val_loss: 0.5717 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5639 - accuracy: 0.7102 - val_loss: 0.5554 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5498 - accuracy: 0.7191 - val_loss: 0.5516 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7252 - val_loss: 0.5522 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7299 - val_loss: 0.5485 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7365 - val_loss: 0.5492 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7400 - val_loss: 0.5486 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7414 - val_loss: 0.5571 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7456 - val_loss: 0.5500 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7490 - val_loss: 0.5472 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4990 - accuracy: 0.7522 - val_loss: 0.5477 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7537 - val_loss: 0.5523 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4898 - accuracy: 0.7556 - val_loss: 0.5570 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7594 - val_loss: 0.5527 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4794 - accuracy: 0.7633 - val_loss: 0.5547 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4736 - accuracy: 0.7653 - val_loss: 0.5574 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4725 - accuracy: 0.7669 - val_loss: 0.5617 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4664 - accuracy: 0.7689 - val_loss: 0.5749 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4625 - accuracy: 0.7731 - val_loss: 0.5646 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4592 - accuracy: 0.7755 - val_loss: 0.5651 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 21/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4523 - accuracy: 0.7769
Epoch 21: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4528 - accuracy: 0.7763 - val_loss: 0.5845 - val_accuracy: 0.7196 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.5073062060367366
Confusion Matrix :
 [[3277 1046]
 [1084 3239]]
Accuracy on test set:    0.7536433032616239
Sensitivity:    0.7492482072634744 	 Specificity:    0.7580383992597733
Precision  : 0.7558926487747958
Area Under Curve:    0.7536433032616239
(8646, 4352) (8646,)
Mean MCC = 0.4494 + 0.0255 and Mean AUC = 0.7238 + 0.0128
Mean Sensitivity = 0.7461 + 0.0408 and Mean Specificity = 0.7015 + 0.0413 and Mean Accuracy = 0.7238 + 0.0128
Mean Precision = 0.7154 + 0.0201





Seed   : 609503
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6088 - accuracy: 0.6646 - val_loss: 0.5706 - val_accuracy: 0.6979 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5571 - accuracy: 0.7131 - val_loss: 0.5528 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7262 - val_loss: 0.5496 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5314 - accuracy: 0.7307 - val_loss: 0.5500 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5222 - accuracy: 0.7370 - val_loss: 0.5502 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7398 - val_loss: 0.5421 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5083 - accuracy: 0.7454 - val_loss: 0.5443 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7490 - val_loss: 0.5408 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7546 - val_loss: 0.5428 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7561 - val_loss: 0.5409 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7607 - val_loss: 0.5441 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4806 - accuracy: 0.7639 - val_loss: 0.5410 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4755 - accuracy: 0.7669 - val_loss: 0.5512 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4673 - accuracy: 0.7702 - val_loss: 0.5383 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4614 - accuracy: 0.7726 - val_loss: 0.5673 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4570 - accuracy: 0.7745 - val_loss: 0.5525 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4499 - accuracy: 0.7778
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4501 - accuracy: 0.7778 - val_loss: 0.5567 - val_accuracy: 0.7188 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4164569052119513
Confusion Matrix :
 [[2736 1587]
 [ 955 3368]]
Accuracy on test set:    0.7059912098080037
Sensitivity:    0.779088595882489 	 Specificity:    0.6328938237335184
Precision  : 0.6797174571140262
Area Under Curve:    0.7059912098080037
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6112 - accuracy: 0.6659 - val_loss: 0.5665 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5570 - accuracy: 0.7140 - val_loss: 0.5576 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7283 - val_loss: 0.5461 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5278 - accuracy: 0.7347 - val_loss: 0.5471 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5178 - accuracy: 0.7376 - val_loss: 0.5390 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7441 - val_loss: 0.5385 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7508 - val_loss: 0.5408 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7542 - val_loss: 0.5409 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7597 - val_loss: 0.5419 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4828 - accuracy: 0.7641
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7642 - val_loss: 0.5447 - val_accuracy: 0.7169 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4359422040912358
Confusion Matrix :
 [[2838 1485]
 [ 967 3356]]
Accuracy on test set:    0.7164006476983577
Sensitivity:    0.7763127457783946 	 Specificity:    0.6564885496183206
Precision  : 0.6932451972732906
Area Under Curve:    0.7164006476983577
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5984 - accuracy: 0.6728 - val_loss: 0.5644 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5584 - accuracy: 0.7099 - val_loss: 0.5546 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7218 - val_loss: 0.5452 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7281 - val_loss: 0.5440 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7344 - val_loss: 0.5396 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5202 - accuracy: 0.7384 - val_loss: 0.5392 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5159 - accuracy: 0.7422 - val_loss: 0.5436 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7446 - val_loss: 0.5384 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7468 - val_loss: 0.5509 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7516 - val_loss: 0.5408 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7559 - val_loss: 0.5415 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7571 - val_loss: 0.5467 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7589 - val_loss: 0.5454 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4749 - accuracy: 0.7639 - val_loss: 0.5474 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4692 - accuracy: 0.7677 - val_loss: 0.5566 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 16/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4653 - accuracy: 0.7720
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4650 - accuracy: 0.7724 - val_loss: 0.5531 - val_accuracy: 0.7208 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.44258517092411515
Confusion Matrix :
 [[3080 1243]
 [1167 3156]]
Accuracy on test set:    0.7212583853805228
Sensitivity:    0.7300485773768216 	 Specificity:    0.712468193384224
Precision  : 0.7174357808592862
Area Under Curve:    0.7212583853805227
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6080 - accuracy: 0.6666 - val_loss: 0.5643 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7136 - val_loss: 0.5536 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7245 - val_loss: 0.5518 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7310 - val_loss: 0.5434 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7365 - val_loss: 0.5464 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7423 - val_loss: 0.5416 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5078 - accuracy: 0.7455 - val_loss: 0.5390 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7496 - val_loss: 0.5407 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7543 - val_loss: 0.5442 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7589 - val_loss: 0.5462 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4810 - accuracy: 0.7628 - val_loss: 0.5424 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4762 - accuracy: 0.7655 - val_loss: 0.5531 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4680 - accuracy: 0.7711 - val_loss: 0.5486 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4605 - accuracy: 0.7756 - val_loss: 0.5638 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4564 - accuracy: 0.7773 - val_loss: 0.5605 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4492 - accuracy: 0.7809 - val_loss: 0.5546 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4452 - accuracy: 0.7850 - val_loss: 0.5592 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 18/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4375 - accuracy: 0.7881
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4381 - accuracy: 0.7879 - val_loss: 0.5631 - val_accuracy: 0.7230 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.44306601109818905
Confusion Matrix :
 [[2971 1352]
 [1060 3263]]
Accuracy on test set:    0.721027064538515
Sensitivity:    0.7547999074716631 	 Specificity:    0.6872542216053666
Precision  : 0.7070422535211267
Area Under Curve:    0.721027064538515
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6059 - accuracy: 0.6689 - val_loss: 0.5629 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5559 - accuracy: 0.7120 - val_loss: 0.5445 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7244 - val_loss: 0.5475 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7319 - val_loss: 0.5422 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5178 - accuracy: 0.7397 - val_loss: 0.5412 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5106 - accuracy: 0.7457 - val_loss: 0.5412 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5050 - accuracy: 0.7490 - val_loss: 0.5412 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4964 - accuracy: 0.7529 - val_loss: 0.5353 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7559 - val_loss: 0.5388 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7606 - val_loss: 0.5418 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7650 - val_loss: 0.5416 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7718 - val_loss: 0.5387 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4618 - accuracy: 0.7768 - val_loss: 0.5461 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4538 - accuracy: 0.7801 - val_loss: 0.5457 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4462 - accuracy: 0.7838 - val_loss: 0.5542 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4426 - accuracy: 0.7866 - val_loss: 0.5583 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4357 - accuracy: 0.7885 - val_loss: 0.5627 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 18/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4287 - accuracy: 0.7924
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4292 - accuracy: 0.7922 - val_loss: 0.5530 - val_accuracy: 0.7188 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.416142610432691
Confusion Matrix :
 [[2989 1334]
 [1191 3132]]
Accuracy on test set:    0.7079574369650705
Sensitivity:    0.7244968771686329 	 Specificity:    0.6914179967615082
Precision  : 0.7012987012987013
Area Under Curve:    0.7079574369650705
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6031 - accuracy: 0.6675 - val_loss: 0.5621 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5570 - accuracy: 0.7127 - val_loss: 0.5612 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7246 - val_loss: 0.5445 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7295 - val_loss: 0.5429 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7358 - val_loss: 0.5352 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7393 - val_loss: 0.5377 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7449 - val_loss: 0.5453 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7505 - val_loss: 0.5419 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7530 - val_loss: 0.5363 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4878 - accuracy: 0.7585 - val_loss: 0.5431 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4821 - accuracy: 0.7618 - val_loss: 0.5427 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4755 - accuracy: 0.7664 - val_loss: 0.5553 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 13/400
146/274 [==============>...............] - ETA: 0s - loss: 0.4650 - accuracy: 0.7694

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

274/274 [==============================] - 1s 2ms/step - loss: 0.5012 - accuracy: 0.7504 - val_loss: 0.5426 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7536 - val_loss: 0.5528 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4881 - accuracy: 0.7585 - val_loss: 0.5427 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7624 - val_loss: 0.5451 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4776 - accuracy: 0.7638 - val_loss: 0.5552 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4692 - accuracy: 0.7687 - val_loss: 0.5581 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4643 - accuracy: 0.7712 - val_loss: 0.5495 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4554 - accuracy: 0.7765 - val_loss: 0.5608 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4505 - accuracy: 0.7783 - val_loss: 0.5602 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4427 - accuracy: 0.7859 - val_loss: 0.5605 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4408 - accuracy: 0.7847
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4408 - accuracy: 0.7845 - val_loss: 0.5737 - val_accuracy: 0.7232 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.43427679914284806
Confusion Matrix :
 [[2934 1389]
 [1062 3261]]
Accuracy on test set:    0.7165163081193615
Sensitivity:    0.7543372657876475 	 Specificity:    0.6786953504510757
Precision  : 0.7012903225806452
Area Under Curve:    0.7165163081193615
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5979 - accuracy: 0.6736 - val_loss: 0.5637 - val_accuracy: 0.6983 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5564 - accuracy: 0.7138 - val_loss: 0.5531 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7259 - val_loss: 0.5381 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7309 - val_loss: 0.5361 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5223 - accuracy: 0.7365 - val_loss: 0.5413 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7400 - val_loss: 0.5391 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7446 - val_loss: 0.5447 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5047 - accuracy: 0.7480 - val_loss: 0.5405 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7531 - val_loss: 0.5445 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7579 - val_loss: 0.5425 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7627 - val_loss: 0.5371 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4789 - accuracy: 0.7657 - val_loss: 0.5437 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4729 - accuracy: 0.7688 - val_loss: 0.5476 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 14/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4658 - accuracy: 0.7723
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4666 - accuracy: 0.7718 - val_loss: 0.5459 - val_accuracy: 0.7146 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.42187277418850366
Confusion Matrix :
 [[2915 1408]
 [1096 3227]]
Accuracy on test set:    0.7103863058061531
Sensitivity:    0.7464723571593801 	 Specificity:    0.6743002544529262
Precision  : 0.6962243797195253
Area Under Curve:    0.7103863058061531
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6049 - accuracy: 0.6662 - val_loss: 0.5559 - val_accuracy: 0.7107 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5555 - accuracy: 0.7142 - val_loss: 0.5426 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7265 - val_loss: 0.5431 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5292 - accuracy: 0.7323 - val_loss: 0.5389 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5219 - accuracy: 0.7379 - val_loss: 0.5371 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5144 - accuracy: 0.7425 - val_loss: 0.5395 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7463 - val_loss: 0.5397 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7480 - val_loss: 0.5455 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4966 - accuracy: 0.7530 - val_loss: 0.5362 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4877 - accuracy: 0.7602 - val_loss: 0.5384 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4839 - accuracy: 0.7591 - val_loss: 0.5564 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4755 - accuracy: 0.7650 - val_loss: 0.5442 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7712 - val_loss: 0.5475 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 14/400
252/274 [==========================>...] - ETA: 0s - loss: 0.4626 - accuracy: 0.7749
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4627 - accuracy: 0.7747 - val_loss: 0.5539 - val_accuracy: 0.7212 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.44862834669297486
Confusion Matrix :
 [[3086 1237]
 [1147 3176]]
Accuracy on test set:    0.724265556326625
Sensitivity:    0.7346749942169789 	 Specificity:    0.7138561184362711
Precision  : 0.7196918196238387
Area Under Curve:    0.724265556326625
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6139 - accuracy: 0.6606 - val_loss: 0.5557 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5631 - accuracy: 0.7098 - val_loss: 0.5486 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7202 - val_loss: 0.5396 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7268 - val_loss: 0.5373 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7325 - val_loss: 0.5398 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5214 - accuracy: 0.7383 - val_loss: 0.5324 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7382 - val_loss: 0.5337 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5091 - accuracy: 0.7445 - val_loss: 0.5335 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7493 - val_loss: 0.5339 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7520 - val_loss: 0.5316 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4936 - accuracy: 0.7538 - val_loss: 0.5377 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7574 - val_loss: 0.5376 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7598 - val_loss: 0.5317 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4744 - accuracy: 0.7657 - val_loss: 0.5319 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4695 - accuracy: 0.7696 - val_loss: 0.5365 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4638 - accuracy: 0.7721 - val_loss: 0.5437 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4598 - accuracy: 0.7735 - val_loss: 0.5503 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4513 - accuracy: 0.7790
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4514 - accuracy: 0.7789 - val_loss: 0.5483 - val_accuracy: 0.7250 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4274549968181176
Confusion Matrix :
 [[3152 1171]
 [1305 3018]]
Accuracy on test set:    0.7136247975942632
Sensitivity:    0.6981263011797363 	 Specificity:    0.7291232940087902
Precision  : 0.7204583432800191
Area Under Curve:    0.7136247975942632
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6070 - accuracy: 0.6638 - val_loss: 0.5769 - val_accuracy: 0.6931 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5612 - accuracy: 0.7120 - val_loss: 0.5457 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7226 - val_loss: 0.5462 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7277 - val_loss: 0.5437 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7361 - val_loss: 0.5429 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5208 - accuracy: 0.7386 - val_loss: 0.5371 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7447 - val_loss: 0.5411 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7473 - val_loss: 0.5355 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7523 - val_loss: 0.5363 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7547 - val_loss: 0.5369 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4864 - accuracy: 0.7589 - val_loss: 0.5379 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7638 - val_loss: 0.5488 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4738 - accuracy: 0.7670 - val_loss: 0.5422 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4689 - accuracy: 0.7702
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4695 - accuracy: 0.7695 - val_loss: 0.5518 - val_accuracy: 0.7154 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4449348296161979
Confusion Matrix :
 [[2974 1349]
 [1055 3268]]
Accuracy on test set:    0.7219523479065464
Sensitivity:    0.7559565116817025 	 Specificity:    0.6879481841313903
Precision  : 0.7078189300411523
Area Under Curve:    0.7219523479065464
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6082 - accuracy: 0.6657 - val_loss: 0.5655 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5605 - accuracy: 0.7120 - val_loss: 0.5443 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7226 - val_loss: 0.5420 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7284 - val_loss: 0.5359 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5262 - accuracy: 0.7355 - val_loss: 0.5405 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7416 - val_loss: 0.5318 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7449 - val_loss: 0.5347 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7471 - val_loss: 0.5343 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7512 - val_loss: 0.5363 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4938 - accuracy: 0.7573 - val_loss: 0.5371 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7592 - val_loss: 0.5336 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7619 - val_loss: 0.5353 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4747 - accuracy: 0.7671 - val_loss: 0.5408 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4707 - accuracy: 0.7688 - val_loss: 0.5390 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4632 - accuracy: 0.7741 - val_loss: 0.5412 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4604 - accuracy: 0.7744 - val_loss: 0.5563 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 17/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4531 - accuracy: 0.7785 - val_loss: 0.5566 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4453 - accuracy: 0.7824
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4452 - accuracy: 0.7823 - val_loss: 0.5568 - val_accuracy: 0.7228 - lr: 0.0010
271/271 [==============================] - 0s 634us/step
Independent Testing Matthews Correlation:  0.43913589481977966
Confusion Matrix :
 [[3154 1169]
 [1256 3067]]
Accuracy on test set:    0.7195234790654638
Sensitivity:    0.7094610224381217 	 Specificity:    0.7295859356928059
Precision  : 0.7240321057601511
Area Under Curve:    0.7195234790654639
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6176 - accuracy: 0.6608 - val_loss: 0.5703 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5647 - accuracy: 0.7088 - val_loss: 0.5501 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5486 - accuracy: 0.7197 - val_loss: 0.5552 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7276 - val_loss: 0.5415 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7289 - val_loss: 0.5373 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7363 - val_loss: 0.5492 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7385 - val_loss: 0.5359 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7438 - val_loss: 0.5417 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7487 - val_loss: 0.5372 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5009 - accuracy: 0.7498 - val_loss: 0.5331 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7540 - val_loss: 0.5391 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7562 - val_loss: 0.5383 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7608 - val_loss: 0.5456 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4792 - accuracy: 0.7648 - val_loss: 0.5510 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4746 - accuracy: 0.7669
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4738 - accuracy: 0.7672 - val_loss: 0.5493 - val_accuracy: 0.7249 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.4681503930348474
Confusion Matrix :
 [[3320 1003]
 [1301 3022]]
Accuracy on test set:    0.7335183900069396
Sensitivity:    0.6990515845477677 	 Specificity:    0.7679851954661115
Precision  : 0.7508074534161491
Area Under Curve:    0.7335183900069395
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6105 - accuracy: 0.6651 - val_loss: 0.5610 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5636 - accuracy: 0.7100 - val_loss: 0.5507 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7223 - val_loss: 0.5462 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7280 - val_loss: 0.5456 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5268 - accuracy: 0.7350 - val_loss: 0.5505 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5212 - accuracy: 0.7368 - val_loss: 0.5440 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 7/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5148 - accuracy: 0.7423
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5150 - accuracy: 0.7423 - val_loss: 0.5470 - val_accuracy: 0.7168 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4898526682775296
Confusion Matrix :
 [[3511  812]
 [1414 2909]]
Accuracy on test set:    0.7425399028452464
Sensitivity:    0.672912329400879 	 Specificity:    0.8121674762896137
Precision  : 0.7817790916420317
Area Under Curve:    0.7425399028452464
(8646, 4352) (8646,)
Mean MCC = 0.4436 + 0.0199 and Mean AUC = 0.7207 + 0.0098
Mean Sensitivity = 0.7356 + 0.0384 and Mean Specificity = 0.7059 + 0.0540 and Mean Accuracy = 0.7207 + 0.0098
Mean Precision = 0.7169 + 0.0291





Seed   : 619742
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6125 - accuracy: 0.6636 - val_loss: 0.5577 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5588 - accuracy: 0.7114 - val_loss: 0.5573 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7242 - val_loss: 0.5398 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5310 - accuracy: 0.7317 - val_loss: 0.5470 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7381 - val_loss: 0.5431 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7418 - val_loss: 0.5348 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7455 - val_loss: 0.5359 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5008 - accuracy: 0.7497 - val_loss: 0.5339 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7552 - val_loss: 0.5342 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7589 - val_loss: 0.5338 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4799 - accuracy: 0.7640
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7635 - val_loss: 0.5345 - val_accuracy: 0.7258 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4186862855159876
Confusion Matrix :
 [[2941 1382]
 [1134 3189]]
Accuracy on test set:    0.7089983807541059
Sensitivity:    0.7376821651630812 	 Specificity:    0.6803145963451307
Precision  : 0.6976591555458325
Area Under Curve:    0.7089983807541059
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6110 - accuracy: 0.6609 - val_loss: 0.5652 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5627 - accuracy: 0.7081 - val_loss: 0.5517 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7208 - val_loss: 0.5436 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7288 - val_loss: 0.5473 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5256 - accuracy: 0.7337 - val_loss: 0.5407 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7374 - val_loss: 0.5394 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7428 - val_loss: 0.5380 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7470 - val_loss: 0.5448 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7521 - val_loss: 0.5380 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7538 - val_loss: 0.5407 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4864 - accuracy: 0.7577 - val_loss: 0.5438 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 12/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4823 - accuracy: 0.7600
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7598 - val_loss: 0.5411 - val_accuracy: 0.7251 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.42536517556328024
Confusion Matrix :
 [[2841 1482]
 [1013 3310]]
Accuracy on test set:    0.7114272495951885
Sensitivity:    0.7656719870460329 	 Specificity:    0.6571825121443442
Precision  : 0.6907345575959933
Area Under Curve:    0.7114272495951885
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6100 - accuracy: 0.6623 - val_loss: 0.5591 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7109 - val_loss: 0.5548 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7227 - val_loss: 0.5481 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7304 - val_loss: 0.5439 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5247 - accuracy: 0.7360 - val_loss: 0.5432 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7383 - val_loss: 0.5378 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7431 - val_loss: 0.5387 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5032 - accuracy: 0.7497 - val_loss: 0.5442 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7529 - val_loss: 0.5402 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7562 - val_loss: 0.5383 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4821 - accuracy: 0.7622
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7622 - val_loss: 0.5435 - val_accuracy: 0.7312 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4464553445813026
Confusion Matrix :
 [[3004 1319]
 [1077 3246]]
Accuracy on test set:    0.7228776312745778
Sensitivity:    0.7508674531575295 	 Specificity:    0.6948878093916262
Precision  : 0.7110624315443592
Area Under Curve:    0.7228776312745778
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6055 - accuracy: 0.6647 - val_loss: 0.5637 - val_accuracy: 0.7092 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7092 - val_loss: 0.5606 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7246 - val_loss: 0.5499 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7307 - val_loss: 0.5423 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7349 - val_loss: 0.5389 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7411 - val_loss: 0.5359 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7482 - val_loss: 0.5428 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7504 - val_loss: 0.5380 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4956 - accuracy: 0.7548 - val_loss: 0.5438 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7569 - val_loss: 0.5516 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4841 - accuracy: 0.7611 - val_loss: 0.5397 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4794 - accuracy: 0.7630 - val_loss: 0.5520 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4716 - accuracy: 0.7668 - val_loss: 0.5451 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4650 - accuracy: 0.7716 - val_loss: 0.5503 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4600 - accuracy: 0.7745 - val_loss: 0.5629 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4565 - accuracy: 0.7757
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4571 - accuracy: 0.7753 - val_loss: 0.5614 - val_accuracy: 0.7203 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.42797582288687014
Confusion Matrix :
 [[2923 1400]
 [1078 3245]]
Accuracy on test set:    0.7133934767522554
Sensitivity:    0.7506361323155216 	 Specificity:    0.6761508211889892
Precision  : 0.6986006458557589
Area Under Curve:    0.7133934767522554
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6045 - accuracy: 0.6685 - val_loss: 0.5563 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5573 - accuracy: 0.7136 - val_loss: 0.5439 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7245 - val_loss: 0.5410 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5317 - accuracy: 0.7300 - val_loss: 0.5368 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7357 - val_loss: 0.5380 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 6/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7423 - val_loss: 0.5356 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7459 - val_loss: 0.5299 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5012 - accuracy: 0.7507 - val_loss: 0.5337 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7524 - val_loss: 0.5337 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4899 - accuracy: 0.7582 - val_loss: 0.5321 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7641 - val_loss: 0.5395 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7673 - val_loss: 0.5442 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4693 - accuracy: 0.7707 - val_loss: 0.5418 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4609 - accuracy: 0.7735 - val_loss: 0.5522 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4597 - accuracy: 0.7748 - val_loss: 0.5507 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4529 - accuracy: 0.7797 - val_loss: 0.5453 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4479 - accuracy: 0.7793 - val_loss: 0.5586 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 18/400
256/274 [===========================>..] - ETA: 0s - loss: 0.4420 - accuracy: 0.7863
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4429 - accuracy: 0.7857 - val_loss: 0.5622 - val_accuracy: 0.7271 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4300990974080765
Confusion Matrix :
 [[3051 1272]
 [1192 3131]]
Accuracy on test set:    0.7150127226463104
Sensitivity:    0.724265556326625 	 Specificity:    0.7057598889659958
Precision  : 0.7111060640472405
Area Under Curve:    0.7150127226463104
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6107 - accuracy: 0.6630 - val_loss: 0.5676 - val_accuracy: 0.7038 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7093 - val_loss: 0.5530 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7204 - val_loss: 0.5469 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7285 - val_loss: 0.5414 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5274 - accuracy: 0.7333 - val_loss: 0.5378 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7403 - val_loss: 0.5365 - val_accuracy: 0.7330 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7423 - val_loss: 0.5424 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5055 - accuracy: 0.7473 - val_loss: 0.5393 - val_accuracy: 0.7331 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7548 - val_loss: 0.5365 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4932 - accuracy: 0.7554 - val_loss: 0.5397 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4842 - accuracy: 0.7610 - val_loss: 0.5406 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7630 - val_loss: 0.5421 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 13/400
268/274 [============================>.] - ETA: 0s - loss: 0.4754 - accuracy: 0.7660
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4756 - accuracy: 0.7659 - val_loss: 0.5512 - val_accuracy: 0.7240 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.4390329484140784
Confusion Matrix :
 [[3042 1281]
 [1145 3178]]
Accuracy on test set:    0.7194078186444599
Sensitivity:    0.7351376359009947 	 Specificity:    0.703678001387925
Precision  : 0.7127158555729984
Area Under Curve:    0.7194078186444599
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6083 - accuracy: 0.6640 - val_loss: 0.5681 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7112 - val_loss: 0.5494 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7214 - val_loss: 0.5465 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7279 - val_loss: 0.5398 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7303 - val_loss: 0.5463 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5212 - accuracy: 0.7369 - val_loss: 0.5382 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7400 - val_loss: 0.5405 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7453 - val_loss: 0.5463 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7515 - val_loss: 0.5378 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7532 - val_loss: 0.5377 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4891 - accuracy: 0.7567 - val_loss: 0.5469 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4855 - accuracy: 0.7586 - val_loss: 0.5428 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4788 - accuracy: 0.7639 - val_loss: 0.5536 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4725 - accuracy: 0.7657 - val_loss: 0.5505 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4655 - accuracy: 0.7729
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4653 - accuracy: 0.7730 - val_loss: 0.5530 - val_accuracy: 0.7227 - lr: 0.0010
271/271 [==============================] - 0s 637us/step
Independent Testing Matthews Correlation:  0.4499445110779309
Confusion Matrix :
 [[3111 1212]
 [1166 3157]]
Accuracy on test set:    0.7249595188526486
Sensitivity:    0.7302798982188295 	 Specificity:    0.7196391394864677
Precision  : 0.722590981918059
Area Under Curve:    0.7249595188526485
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6074 - accuracy: 0.6646 - val_loss: 0.5660 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5615 - accuracy: 0.7092 - val_loss: 0.5527 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7192 - val_loss: 0.5416 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7269 - val_loss: 0.5432 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5307 - accuracy: 0.7300 - val_loss: 0.5484 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7357 - val_loss: 0.5415 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7395 - val_loss: 0.5358 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7443 - val_loss: 0.5368 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5022 - accuracy: 0.7498 - val_loss: 0.5340 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7521 - val_loss: 0.5427 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4922 - accuracy: 0.7558 - val_loss: 0.5403 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4845 - accuracy: 0.7599 - val_loss: 0.5392 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4786 - accuracy: 0.7618 - val_loss: 0.5517 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4740 - accuracy: 0.7629 - val_loss: 0.5458 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4668 - accuracy: 0.7687 - val_loss: 0.5440 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4584 - accuracy: 0.7737 - val_loss: 0.5473 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4548 - accuracy: 0.7752 - val_loss: 0.5532 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4477 - accuracy: 0.7788 - val_loss: 0.5593 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 19/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4425 - accuracy: 0.7813
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4441 - accuracy: 0.7804 - val_loss: 0.5659 - val_accuracy: 0.7300 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.4694412835186837
Confusion Matrix :
 [[3016 1307]
 [ 992 3331]]
Accuracy on test set:    0.7340966921119593
Sensitivity:    0.770529724728198 	 Specificity:    0.6976636594957205
Precision  : 0.7181974989219491
Area Under Curve:    0.7340966921119594
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6042 - accuracy: 0.6717 - val_loss: 0.5675 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7121 - val_loss: 0.5521 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7218 - val_loss: 0.5483 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7273 - val_loss: 0.5399 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7323 - val_loss: 0.5385 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5207 - accuracy: 0.7385 - val_loss: 0.5368 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7420 - val_loss: 0.5379 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7448 - val_loss: 0.5400 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5037 - accuracy: 0.7477 - val_loss: 0.5355 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7514 - val_loss: 0.5369 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7575 - val_loss: 0.5419 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4880 - accuracy: 0.7580
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4880 - accuracy: 0.7583 - val_loss: 0.5403 - val_accuracy: 0.7283 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.47934250478250784
Confusion Matrix :
 [[3374  949]
 [1309 3014]]
Accuracy on test set:    0.7388387693731205
Sensitivity:    0.6972010178117048 	 Specificity:    0.7804765209345362
Precision  : 0.7605349482715115
Area Under Curve:    0.7388387693731205
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6128 - accuracy: 0.6621 - val_loss: 0.5730 - val_accuracy: 0.7021 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5639 - accuracy: 0.7089 - val_loss: 0.5529 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
 29/274 [==>...........................] - ETA: 0s - loss: 0.5517 - accuracy: 0.7188

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

274/274 [==============================] - 1s 3ms/step - loss: 0.6134 - accuracy: 0.6627 - val_loss: 0.5623 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5582 - accuracy: 0.7113 - val_loss: 0.5531 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7220 - val_loss: 0.5482 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7288 - val_loss: 0.5479 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7343 - val_loss: 0.5423 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7401 - val_loss: 0.5419 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7437 - val_loss: 0.5392 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7492 - val_loss: 0.5454 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7525 - val_loss: 0.5450 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4898 - accuracy: 0.7579 - val_loss: 0.5420 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4850 - accuracy: 0.7598 - val_loss: 0.5479 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4770 - accuracy: 0.7649
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4774 - accuracy: 0.7646 - val_loss: 0.5444 - val_accuracy: 0.7244 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.44405918239657993
Confusion Matrix :
 [[2938 1385]
 [1025 3298]]
Accuracy on test set:    0.7212583853805228
Sensitivity:    0.7628961369419385 	 Specificity:    0.6796206338191071
Precision  : 0.7042494127695922
Area Under Curve:    0.7212583853805228
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6009 - accuracy: 0.6714 - val_loss: 0.5603 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5574 - accuracy: 0.7126 - val_loss: 0.5541 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7227 - val_loss: 0.5478 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7302 - val_loss: 0.5451 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7357 - val_loss: 0.5380 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7399 - val_loss: 0.5384 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7412 - val_loss: 0.5414 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7466 - val_loss: 0.5400 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7490 - val_loss: 0.5412 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 10/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4965 - accuracy: 0.7514
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7515 - val_loss: 0.5464 - val_accuracy: 0.7197 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.43442430581420827
Confusion Matrix :
 [[3296 1027]
 [1426 2897]]
Accuracy on test set:    0.7162849872773537
Sensitivity:    0.6701364792967847 	 Specificity:    0.7624334952579227
Precision  : 0.7382772680937818
Area Under Curve:    0.7162849872773537
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6091 - accuracy: 0.6670 - val_loss: 0.5618 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7110 - val_loss: 0.5500 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7226 - val_loss: 0.5461 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7297 - val_loss: 0.5401 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5234 - accuracy: 0.7354 - val_loss: 0.5383 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7393 - val_loss: 0.5379 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7434 - val_loss: 0.5378 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7471 - val_loss: 0.5325 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4970 - accuracy: 0.7525 - val_loss: 0.5373 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7545 - val_loss: 0.5384 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4845 - accuracy: 0.7586 - val_loss: 0.5410 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7622 - val_loss: 0.5448 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4742 - accuracy: 0.7670 - val_loss: 0.5467 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4649 - accuracy: 0.7731 - val_loss: 0.5471 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4632 - accuracy: 0.7734
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4634 - accuracy: 0.7731 - val_loss: 0.5547 - val_accuracy: 0.7170 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.43465179823787764
Confusion Matrix :
 [[3030 1293]
 [1152 3171]]
Accuracy on test set:    0.7172102706453851
Sensitivity:    0.7335183900069396 	 Specificity:    0.7009021512838307
Precision  : 0.7103494623655914
Area Under Curve:    0.7172102706453852
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6035 - accuracy: 0.6698 - val_loss: 0.5708 - val_accuracy: 0.7008 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5588 - accuracy: 0.7116 - val_loss: 0.5499 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7210 - val_loss: 0.5457 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7279 - val_loss: 0.5433 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5270 - accuracy: 0.7341 - val_loss: 0.5404 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7354 - val_loss: 0.5386 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7415 - val_loss: 0.5360 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7453 - val_loss: 0.5435 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7470 - val_loss: 0.5473 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4974 - accuracy: 0.7529 - val_loss: 0.5479 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4899 - accuracy: 0.7565 - val_loss: 0.5466 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7596 - val_loss: 0.5443 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7627 - val_loss: 0.5425 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 14/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4746 - accuracy: 0.7654
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4748 - accuracy: 0.7652 - val_loss: 0.5462 - val_accuracy: 0.7191 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.4425788658314265
Confusion Matrix :
 [[2901 1422]
 [ 997 3326]]
Accuracy on test set:    0.7202174415914874
Sensitivity:    0.7693731205181586 	 Specificity:    0.6710617626648161
Precision  : 0.7005054759898904
Area Under Curve:    0.7202174415914874
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6019 - accuracy: 0.6721 - val_loss: 0.5656 - val_accuracy: 0.7016 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7124 - val_loss: 0.5481 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7234 - val_loss: 0.5446 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7291 - val_loss: 0.5394 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5251 - accuracy: 0.7336 - val_loss: 0.5422 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7401 - val_loss: 0.5462 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5111 - accuracy: 0.7420 - val_loss: 0.5419 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7484 - val_loss: 0.5426 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4973 - accuracy: 0.7531 - val_loss: 0.5420 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4901 - accuracy: 0.7568
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7564 - val_loss: 0.5586 - val_accuracy: 0.7206 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4524730850209688
Confusion Matrix :
 [[2721 1602]
 [ 799 3524]]
Accuracy on test set:    0.7222993291695582
Sensitivity:    0.815174647235716 	 Specificity:    0.6294240111034004
Precision  : 0.6874756145142411
Area Under Curve:    0.7222993291695581
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6086 - accuracy: 0.6655 - val_loss: 0.5630 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7129 - val_loss: 0.5530 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7219 - val_loss: 0.5454 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7279 - val_loss: 0.5446 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5263 - accuracy: 0.7343 - val_loss: 0.5458 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7401 - val_loss: 0.5393 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7453 - val_loss: 0.5397 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7463 - val_loss: 0.5426 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7513 - val_loss: 0.5378 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7561 - val_loss: 0.5428 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4879 - accuracy: 0.7585 - val_loss: 0.5404 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4813 - accuracy: 0.7617
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4815 - accuracy: 0.7616 - val_loss: 0.5483 - val_accuracy: 0.7215 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.46724752530682623
Confusion Matrix :
 [[2921 1402]
 [ 914 3409]]
Accuracy on test set:    0.7321304649548924
Sensitivity:    0.7885727504048115 	 Specificity:    0.6756881795049734
Precision  : 0.7085844938682186
Area Under Curve:    0.7321304649548924
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6070 - accuracy: 0.6666 - val_loss: 0.5649 - val_accuracy: 0.7016 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7087 - val_loss: 0.5499 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5486 - accuracy: 0.7199 - val_loss: 0.5440 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7268 - val_loss: 0.5424 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7320 - val_loss: 0.5422 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5231 - accuracy: 0.7359 - val_loss: 0.5350 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5187 - accuracy: 0.7391 - val_loss: 0.5444 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7428 - val_loss: 0.5356 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7475 - val_loss: 0.5383 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7517 - val_loss: 0.5382 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4938 - accuracy: 0.7535
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7538 - val_loss: 0.5385 - val_accuracy: 0.7290 - lr: 0.0010

271/271 [==============================] - 0s 637us/step
Independent Testing Matthews Correlation:  0.47287659775614926
Confusion Matrix :
 [[3150 1173]
 [1106 3217]]
Accuracy on test set:    0.7364099005320379
Sensitivity:    0.7441591487393014 	 Specificity:    0.7286606523247745
Precision  : 0.7328018223234624
Area Under Curve:    0.736409900532038
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6128 - accuracy: 0.6596 - val_loss: 0.5648 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5659 - accuracy: 0.7070 - val_loss: 0.5565 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5514 - accuracy: 0.7165 - val_loss: 0.5466 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7263 - val_loss: 0.5450 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7312 - val_loss: 0.5491 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5260 - accuracy: 0.7341 - val_loss: 0.5427 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7387 - val_loss: 0.5402 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5122 - accuracy: 0.7424 - val_loss: 0.5402 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7481 - val_loss: 0.5402 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7523 - val_loss: 0.5415 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7572 - val_loss: 0.5434 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4880 - accuracy: 0.7589 - val_loss: 0.5463 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4795 - accuracy: 0.7633
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4805 - accuracy: 0.7628 - val_loss: 0.5520 - val_accuracy: 0.7169 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4987371108233031
Confusion Matrix :
 [[3049 1274]
 [ 901 3422]]
Accuracy on test set:    0.7484385843164469
Sensitivity:    0.7915799213509137 	 Specificity:    0.7052972472819801
Precision  : 0.7287052810902896
Area Under Curve:    0.7484385843164469
(8646, 4352) (8646,)
Mean MCC = 0.4493 + 0.0234 and Mean AUC = 0.7236 + 0.0118
Mean Sensitivity = 0.7549 + 0.0403 and Mean Specificity = 0.6923 + 0.0382 and Mean Accuracy = 0.7236 + 0.0118
Mean Precision = 0.7114 + 0.0177





Seed   : 855692
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6206 - accuracy: 0.6556 - val_loss: 0.5675 - val_accuracy: 0.7028 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7113 - val_loss: 0.5563 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7248 - val_loss: 0.5442 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7318 - val_loss: 0.5485 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.7379 - val_loss: 0.5427 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7430 - val_loss: 0.5362 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7464 - val_loss: 0.5396 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7512 - val_loss: 0.5411 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4954 - accuracy: 0.7541 - val_loss: 0.5361 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7567 - val_loss: 0.5343 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4818 - accuracy: 0.7621 - val_loss: 0.5325 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4761 - accuracy: 0.7636 - val_loss: 0.5396 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4704 - accuracy: 0.7679 - val_loss: 0.5442 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4616 - accuracy: 0.7733 - val_loss: 0.5419 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4567 - accuracy: 0.7754 - val_loss: 0.5425 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4506 - accuracy: 0.7802
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4508 - accuracy: 0.7799 - val_loss: 0.5443 - val_accuracy: 0.7173 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.41205081663555354
Confusion Matrix :
 [[2734 1589]
 [ 971 3352]]
Accuracy on test set:    0.703909322229933
Sensitivity:    0.7753874624103632 	 Specificity:    0.6324311820495027
Precision  : 0.6784051811374215
Area Under Curve:    0.7039093222299329
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6053 - accuracy: 0.6671 - val_loss: 0.5650 - val_accuracy: 0.7014 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5572 - accuracy: 0.7129 - val_loss: 0.5523 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7249 - val_loss: 0.5501 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5314 - accuracy: 0.7317 - val_loss: 0.5462 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5204 - accuracy: 0.7372 - val_loss: 0.5410 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5165 - accuracy: 0.7408 - val_loss: 0.5479 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7461 - val_loss: 0.5578 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7505 - val_loss: 0.5427 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4956 - accuracy: 0.7550 - val_loss: 0.5426 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4929 - accuracy: 0.7541 - val_loss: 0.5501 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4844 - accuracy: 0.7612 - val_loss: 0.5466 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7637 - val_loss: 0.5464 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4716 - accuracy: 0.7699 - val_loss: 0.5571 - val_accuracy: 0.7187 - lr: 0.0010

Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4689 - accuracy: 0.7700 - val_loss: 0.5567 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4629 - accuracy: 0.7731 - val_loss: 0.5558 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4582 - accuracy: 0.7762 - val_loss: 0.5583 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4526 - accuracy: 0.7789 - val_loss: 0.5765 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4473 - accuracy: 0.7823 - val_loss: 0.5692 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 19/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4421 - accuracy: 0.7844
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4432 - accuracy: 0.7836 - val_loss: 0.5638 - val_accuracy: 0.7137 - lr: 0.0010
271/271 [==============================] - 0s 638us/step
Independent Testing Matthews Correlation:  0.4070849451054898
Confusion Matrix :
 [[2942 1381]
 [1184 3139]]
Accuracy on test set:    0.7033310201249132
Sensitivity:    0.7261161230626879 	 Specificity:    0.6805459171871385
Precision  : 0.6944690265486726
Area Under Curve:    0.7033310201249132
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6142 - accuracy: 0.6604 - val_loss: 0.5716 - val_accuracy: 0.7041 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7093 - val_loss: 0.5554 - val_accuracy: 0.7092 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7222 - val_loss: 0.5458 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7281 - val_loss: 0.5443 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7351 - val_loss: 0.5523 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7391 - val_loss: 0.5435 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7430 - val_loss: 0.5418 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7489 - val_loss: 0.5460 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7515 - val_loss: 0.5435 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7561 - val_loss: 0.5455 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4880 - accuracy: 0.7599 - val_loss: 0.5568 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 12/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4805 - accuracy: 0.7625
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7620 - val_loss: 0.5487 - val_accuracy: 0.7177 - lr: 0.0010
271/271 [==============================] - 0s 637us/step
Independent Testing Matthews Correlation:  0.45147267310356876
Confusion Matrix :
 [[3022 1301]
 [1073 3250]]
Accuracy on test set:    0.7254221605366643
Sensitivity:    0.751792736525561 	 Specificity:    0.6990515845477677
Precision  : 0.7141287629092508
Area Under Curve:    0.7254221605366644
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6086 - accuracy: 0.6670 - val_loss: 0.5645 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5631 - accuracy: 0.7079 - val_loss: 0.5516 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7221 - val_loss: 0.5494 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7259 - val_loss: 0.5462 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5310 - accuracy: 0.7333 - val_loss: 0.5424 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5247 - accuracy: 0.7353 - val_loss: 0.5394 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7391 - val_loss: 0.5412 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7417 - val_loss: 0.5386 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7438 - val_loss: 0.5387 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7471 - val_loss: 0.5373 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7503 - val_loss: 0.5414 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4950 - accuracy: 0.7538 - val_loss: 0.5422 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7537 - val_loss: 0.5538 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4845 - accuracy: 0.7583 - val_loss: 0.5461 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4807 - accuracy: 0.7596
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7591 - val_loss: 0.5486 - val_accuracy: 0.7161 - lr: 0.0010
271/271 [==============================] - 0s 638us/step
Independent Testing Matthews Correlation:  0.4210044843825592
Confusion Matrix :
 [[3068 1255]
 [1248 3075]]
Accuracy on test set:    0.7105019662271571
Sensitivity:    0.7113115891741846 	 Specificity:    0.7096923432801295
Precision  : 0.710161662817552
Area Under Curve:    0.710501966227157
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6064 - accuracy: 0.6674 - val_loss: 0.5643 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5595 - accuracy: 0.7120 - val_loss: 0.5500 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7217 - val_loss: 0.5486 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7285 - val_loss: 0.5456 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5276 - accuracy: 0.7327 - val_loss: 0.5428 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5190 - accuracy: 0.7393 - val_loss: 0.5398 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5125 - accuracy: 0.7435 - val_loss: 0.5380 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7465 - val_loss: 0.5376 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7521 - val_loss: 0.5416 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 10/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7550 - val_loss: 0.5414 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4858 - accuracy: 0.7587 - val_loss: 0.5452 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7615 - val_loss: 0.5465 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4763 - accuracy: 0.7651 - val_loss: 0.5469 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4703 - accuracy: 0.7681
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7680 - val_loss: 0.5595 - val_accuracy: 0.7204 - lr: 0.0010
271/271 [==============================] - 0s 666us/step
Independent Testing Matthews Correlation:  0.4289518259010333
Confusion Matrix :
 [[2735 1588]
 [ 904 3419]]
Accuracy on test set:    0.7117742308582004
Sensitivity:    0.7908859588248901 	 Specificity:    0.6326625028915105
Precision  : 0.682844018374276
Area Under Curve:    0.7117742308582002
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6100 - accuracy: 0.6664 - val_loss: 0.5591 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5563 - accuracy: 0.7146 - val_loss: 0.5447 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7256 - val_loss: 0.5464 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7327 - val_loss: 0.5412 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5218 - accuracy: 0.7358 - val_loss: 0.5366 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7431 - val_loss: 0.5363 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7465 - val_loss: 0.5384 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7513 - val_loss: 0.5352 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4929 - accuracy: 0.7564 - val_loss: 0.5493 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7594 - val_loss: 0.5379 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4821 - accuracy: 0.7640 - val_loss: 0.5378 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4759 - accuracy: 0.7661 - val_loss: 0.5459 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4694 - accuracy: 0.7698 - val_loss: 0.5458 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4634 - accuracy: 0.7730 - val_loss: 0.5402 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4573 - accuracy: 0.7762 - val_loss: 0.5446 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4523 - accuracy: 0.7810 - val_loss: 0.5561 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4461 - accuracy: 0.7823 - val_loss: 0.5551 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4384 - accuracy: 0.7854 - val_loss: 0.5728 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 19/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4328 - accuracy: 0.7889
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4334 - accuracy: 0.7886 - val_loss: 0.5738 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.42623179915584325
Confusion Matrix :
 [[2734 1589]
 [ 914 3409]]
Accuracy on test set:    0.7105019662271571
Sensitivity:    0.7885727504048115 	 Specificity:    0.6324311820495027
Precision  : 0.6820728291316527
Area Under Curve:    0.710501966227157
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6186 - accuracy: 0.6578 - val_loss: 0.5656 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.7093 - val_loss: 0.5498 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7200 - val_loss: 0.5523 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7279 - val_loss: 0.5381 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5286 - accuracy: 0.7339 - val_loss: 0.5421 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5211 - accuracy: 0.7377 - val_loss: 0.5376 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7427 - val_loss: 0.5365 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7440 - val_loss: 0.5397 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7494 - val_loss: 0.5390 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7512 - val_loss: 0.5373 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7561 - val_loss: 0.5372 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7620 - val_loss: 0.5438 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7650 - val_loss: 0.5400 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4734 - accuracy: 0.7676 - val_loss: 0.5398 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4682 - accuracy: 0.7701 - val_loss: 0.5436 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4636 - accuracy: 0.7721 - val_loss: 0.5528 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4582 - accuracy: 0.7748 - val_loss: 0.5639 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 18/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4515 - accuracy: 0.7775
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4525 - accuracy: 0.7772 - val_loss: 0.5647 - val_accuracy: 0.7200 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4395572726067135
Confusion Matrix :
 [[3188 1135]
 [1289 3034]]
Accuracy on test set:    0.7196391394864677
Sensitivity:    0.7018274346518621 	 Specificity:    0.7374508443210733
Precision  : 0.7277524586231711
Area Under Curve:    0.7196391394864678
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6096 - accuracy: 0.6662 - val_loss: 0.5648 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5616 - accuracy: 0.7095 - val_loss: 0.5506 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7210 - val_loss: 0.5475 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7287 - val_loss: 0.5427 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7299 - val_loss: 0.5375 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5269 - accuracy: 0.7355 - val_loss: 0.5408 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5211 - accuracy: 0.7364 - val_loss: 0.5368 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7413 - val_loss: 0.5378 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7458 - val_loss: 0.5369 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7472 - val_loss: 0.5370 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7512 - val_loss: 0.5444 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7534 - val_loss: 0.5455 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7600 - val_loss: 0.5489 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7606 - val_loss: 0.5434 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7643 - val_loss: 0.5496 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4729 - accuracy: 0.7670 - val_loss: 0.5569 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 17/400
263/274 [===========================>..] - ETA: 0s - loss: 0.4670 - accuracy: 0.7711
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7710 - val_loss: 0.5482 - val_accuracy: 0.7238 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4520010341216113
Confusion Matrix :
 [[3137 1186]
 [1183 3140]]
Accuracy on test set:    0.726000462641684
Sensitivity:    0.7263474439046959 	 Specificity:    0.7256534813786722
Precision  : 0.7258437355524734
Area Under Curve:    0.7260004626416839
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6132 - accuracy: 0.6632 - val_loss: 0.5678 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5633 - accuracy: 0.7088 - val_loss: 0.5517 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7194 - val_loss: 0.5472 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7274 - val_loss: 0.5423 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5307 - accuracy: 0.7308 - val_loss: 0.5396 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7384 - val_loss: 0.5376 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7397 - val_loss: 0.5371 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7442 - val_loss: 0.5423 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7487 - val_loss: 0.5370 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4988 - accuracy: 0.7523 - val_loss: 0.5449 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4945 - accuracy: 0.7543
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7545 - val_loss: 0.5403 - val_accuracy: 0.7224 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.47935836602958765
Confusion Matrix :
 [[3349  974]
 [1282 3041]]
Accuracy on test set:    0.7390700902151284
Sensitivity:    0.7034466805459172 	 Specificity:    0.7746934998843396
Precision  : 0.7574097135740971
Area Under Curve:    0.7390700902151284
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6180 - accuracy: 0.6560 - val_loss: 0.5699 - val_accuracy: 0.7052 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5679 - accuracy: 0.7067 - val_loss: 0.5544 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5505 - accuracy: 0.7183 - val_loss: 0.5503 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7247 - val_loss: 0.5457 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7301 - val_loss: 0.5391 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7352 - val_loss: 0.5413 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7393 - val_loss: 0.5429 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7426 - val_loss: 0.5402 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7494 - val_loss: 0.5403 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7512 - val_loss: 0.5383 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7534 - val_loss: 0.5451 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4890 - accuracy: 0.7563 - val_loss: 0.5409 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4820 - accuracy: 0.7602 - val_loss: 0.5422 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4759 - accuracy: 0.7647 - val_loss: 0.5498 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7679 - val_loss: 0.5446 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4642 - accuracy: 0.7694 - val_loss: 0.5572 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4587 - accuracy: 0.7727 - val_loss: 0.5576 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 18/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4545 - accuracy: 0.7761 - val_loss: 0.5692 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 19/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4485 - accuracy: 0.7789
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4487 - accuracy: 0.7790 - val_loss: 0.5629 - val_accuracy: 0.7191 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.46370206577891643
Confusion Matrix :
 [[3425  898]
 [1436 2887]]
Accuracy on test set:    0.7300485773768216
Sensitivity:    0.667823270876706 	 Specificity:    0.7922738838769373
Precision  : 0.7627476882430647
Area Under Curve:    0.7300485773768217
(8646, 4352) (8646,)
Mean MCC = 0.4381 + 0.0221 and Mean AUC = 0.7180 + 0.0113
Mean Sensitivity = 0.7344 + 0.0390 and Mean Specificity = 0.7017 + 0.0550 and Mean Accuracy = 0.7180 + 0.0113
Mean Precision = 0.7136 + 0.0287





Seed   : 140328
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6066 - accuracy: 0.6678 - val_loss: 0.5720 - val_accuracy: 0.6985 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5574 - accuracy: 0.7106 - val_loss: 0.5516 - val_accuracy: 0.7107 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7240 - val_loss: 0.5473 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5294 - accuracy: 0.7324 - val_loss: 0.5399 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7368 - val_loss: 0.5453 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7425 - val_loss: 0.5381 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7479 - val_loss: 0.5437 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7528 - val_loss: 0.5378 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7575 - val_loss: 0.5440 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4845 - accuracy: 0.7604 - val_loss: 0.5430 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7631 - val_loss: 0.5363 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4712 - accuracy: 0.7668 - val_loss: 0.5501 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4644 - accuracy: 0.7729 - val_loss: 0.5484 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4610 - accuracy: 0.7739 - val_loss: 0.5486 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4522 - accuracy: 0.7785 - val_loss: 0.5540 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 16/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4471 - accuracy: 0.7823
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4473 - accuracy: 0.7824 - val_loss: 0.5556 - val_accuracy: 0.7213 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4348651805213258
Confusion Matrix :
 [[2842 1481]
 [ 975 3348]]
Accuracy on test set:    0.7159380060143419
Sensitivity:    0.7744621790423317 	 Specificity:    0.657413832986352
Precision  : 0.693311244564092
Area Under Curve:    0.715938006014342
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6087 - accuracy: 0.6681 - val_loss: 0.5655 - val_accuracy: 0.7030 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5588 - accuracy: 0.7101 - val_loss: 0.5532 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7217 - val_loss: 0.5450 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7310 - val_loss: 0.5566 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5240 - accuracy: 0.7359 - val_loss: 0.5490 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7391 - val_loss: 0.5418 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7469 - val_loss: 0.5458 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7492 - val_loss: 0.5399 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7521 - val_loss: 0.5445 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4893 - accuracy: 0.7575 - val_loss: 0.5463 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7624 - val_loss: 0.5438 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4738 - accuracy: 0.7661 - val_loss: 0.5478 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4717 - accuracy: 0.7666 - val_loss: 0.5428 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4633 - accuracy: 0.7739 - val_loss: 0.5511 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4558 - accuracy: 0.7779 - val_loss: 0.5478 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4483 - accuracy: 0.7822
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4488 - accuracy: 0.7816 - val_loss: 0.5592 - val_accuracy: 0.7213 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4188238776622401
Confusion Matrix :
 [[3012 1311]
 [1202 3121]]
Accuracy on test set:    0.7093453620171177
Sensitivity:    0.7219523479065464 	 Specificity:    0.6967383761276891
Precision  : 0.7041967509025271
Area Under Curve:    0.7093453620171177
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6061 - accuracy: 0.6681 - val_loss: 0.5648 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7134 - val_loss: 0.5511 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7230 - val_loss: 0.5521 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7288 - val_loss: 0.5566 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7358 - val_loss: 0.5437 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7365 - val_loss: 0.5479 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5119 - accuracy: 0.7414 - val_loss: 0.5493 - val_accuracy: 0.7227 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7458 - val_loss: 0.5425 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7482 - val_loss: 0.5446 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7534 - val_loss: 0.5399 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4890 - accuracy: 0.7551 - val_loss: 0.5451 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4845 - accuracy: 0.7601 - val_loss: 0.5401 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7609 - val_loss: 0.5470 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4716 - accuracy: 0.7642 - val_loss: 0.5501 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4672 - accuracy: 0.7669 - val_loss: 0.5479 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4650 - accuracy: 0.7703 - val_loss: 0.5661 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4577 - accuracy: 0.7746
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4573 - accuracy: 0.7742 - val_loss: 0.5627 - val_accuracy: 0.7226 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.4256004817208485
Confusion Matrix :
 [[2865 1458]
 [1034 3289]]
Accuracy on test set:    0.7117742308582004
Sensitivity:    0.7608142493638677 	 Specificity:    0.6627342123525329
Precision  : 0.6928586475668843
Area Under Curve:    0.7117742308582004
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6023 - accuracy: 0.6708 - val_loss: 0.5661 - val_accuracy: 0.7038 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5553 - accuracy: 0.7133 - val_loss: 0.5511 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7262 - val_loss: 0.5513 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5286 - accuracy: 0.7344 - val_loss: 0.5491 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5208 - accuracy: 0.7383 - val_loss: 0.5446 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7420 - val_loss: 0.5438 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7460 - val_loss: 0.5436 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5009 - accuracy: 0.7517 - val_loss: 0.5613 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4936 - accuracy: 0.7554 - val_loss: 0.5431 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4880 - accuracy: 0.7596 - val_loss: 0.5456 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7609 - val_loss: 0.5634 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4769 - accuracy: 0.7648
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7644 - val_loss: 0.5478 - val_accuracy: 0.7265 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4328610470221063
Confusion Matrix :
 [[2968 1355]
 [1100 3223]]
Accuracy on test set:    0.7160536664353458
Sensitivity:    0.7455470737913485 	 Specificity:    0.686560259079343
Precision  : 0.7040192223678462
Area Under Curve:    0.7160536664353457
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6106 - accuracy: 0.6611 - val_loss: 0.5661 - val_accuracy: 0.7015 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7113 - val_loss: 0.5540 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7220 - val_loss: 0.5441 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7304 - val_loss: 0.5461 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7355 - val_loss: 0.5428 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7410 - val_loss: 0.5467 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5102 - accuracy: 0.7448 - val_loss: 0.5417 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7498 - val_loss: 0.5522 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7527 - val_loss: 0.5436 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7559 - val_loss: 0.5469 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7591 - val_loss: 0.5470 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4806 - accuracy: 0.7630
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7628 - val_loss: 0.5453 - val_accuracy: 0.7226 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.44304375959805614
Confusion Matrix :
 [[2902 1421]
 [ 996 3327]]
Accuracy on test set:    0.7204487624334952
Sensitivity:    0.7696044413601666 	 Specificity:    0.6712930835068239
Precision  : 0.7007160909856782
Area Under Curve:    0.7204487624334953
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6009 - accuracy: 0.6698 - val_loss: 0.5577 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5568 - accuracy: 0.7121 - val_loss: 0.5495 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7224 - val_loss: 0.5498 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7274 - val_loss: 0.5495 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7355 - val_loss: 0.5508 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5168 - accuracy: 0.7403 - val_loss: 0.5407 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7456 - val_loss: 0.5445 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7462 - val_loss: 0.5424 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7510 - val_loss: 0.5437 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7535 - val_loss: 0.5493 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4864 - accuracy: 0.7588 - val_loss: 0.5486 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4805 - accuracy: 0.7638
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4806 - accuracy: 0.7634 - val_loss: 0.5511 - val_accuracy: 0.7210 - lr: 0.0010
271/271 [==============================] - 0s 637us/step
Independent Testing Matthews Correlation:  0.4406666284611713
Confusion Matrix :
 [[3117 1206]
 [1212 3111]]
Accuracy on test set:    0.7203331020124913
Sensitivity:    0.7196391394864677 	 Specificity:    0.721027064538515
Precision  : 0.7206393328700487
Area Under Curve:    0.7203331020124912
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6066 - accuracy: 0.6690 - val_loss: 0.5664 - val_accuracy: 0.7055 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5587 - accuracy: 0.7145 - val_loss: 0.5539 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7224 - val_loss: 0.5470 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7308 - val_loss: 0.5489 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5268 - accuracy: 0.7347 - val_loss: 0.5463 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7398 - val_loss: 0.5479 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7429 - val_loss: 0.5564 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5050 - accuracy: 0.7481 - val_loss: 0.5478 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7508 - val_loss: 0.5459 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4936 - accuracy: 0.7547 - val_loss: 0.5494 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7585 - val_loss: 0.5538 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4820 - accuracy: 0.7622 - val_loss: 0.5499 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4728 - accuracy: 0.7663 - val_loss: 0.5581 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4679 - accuracy: 0.7701 - val_loss: 0.5673 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4630 - accuracy: 0.7724
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4632 - accuracy: 0.7724 - val_loss: 0.5572 - val_accuracy: 0.7159 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4519616360528491
Confusion Matrix :
 [[2895 1428]
 [ 953 3370]]
Accuracy on test set:    0.7246125375896368
Sensitivity:    0.7795512375665048 	 Specificity:    0.6696738376127689
Precision  : 0.7023759899958316
Area Under Curve:    0.7246125375896368
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6128 - accuracy: 0.6654 - val_loss: 0.5672 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7110 - val_loss: 0.5540 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7219 - val_loss: 0.5577 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7259 - val_loss: 0.5521 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5261 - accuracy: 0.7341 - val_loss: 0.5451 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7395 - val_loss: 0.5459 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7430 - val_loss: 0.5475 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7491 - val_loss: 0.5493 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7510 - val_loss: 0.5462 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7562 - val_loss: 0.5473 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4855 - accuracy: 0.7596 - val_loss: 0.5502 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7584 - val_loss: 0.5507 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4731 - accuracy: 0.7675 - val_loss: 0.5545 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4691 - accuracy: 0.7696 - val_loss: 0.5602 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4616 - accuracy: 0.7728 - val_loss: 0.5606 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4546 - accuracy: 0.7766
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4547 - accuracy: 0.7767 - val_loss: 0.5610 - val_accuracy: 0.7191 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.45449438067017744
Confusion Matrix :
 [[3008 1315]
 [1047 3276]]
Accuracy on test set:    0.7268100855887115
Sensitivity:    0.7578070784177654 	 Specificity:    0.6958130927596576
Precision  : 0.7135700283162709
Area Under Curve:    0.7268100855887115
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6072 - accuracy: 0.6667 - val_loss: 0.5681 - val_accuracy: 0.7048 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7109 - val_loss: 0.5540 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7229 - val_loss: 0.5466 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7283 - val_loss: 0.5461 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5270 - accuracy: 0.7340 - val_loss: 0.5453 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5196 - accuracy: 0.7392 - val_loss: 0.5447 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7432 - val_loss: 0.5463 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5083 - accuracy: 0.7463 - val_loss: 0.5438 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7503 - val_loss: 0.5722 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7535 - val_loss: 0.5474 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7560 - val_loss: 0.5518 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7621 - val_loss: 0.5570 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4761 - accuracy: 0.7645
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7639 - val_loss: 0.5521 - val_accuracy: 0.7182 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.46640461616758444
Confusion Matrix :
 [[3045 1278]
 [1032 3291]]
Accuracy on test set:    0.732824427480916
Sensitivity:    0.7612768910478834 	 Specificity:    0.7043719639139486
Precision  : 0.7202889034799738
Area Under Curve:    0.732824427480916
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6143 - accuracy: 0.6599 - val_loss: 0.5756 - val_accuracy: 0.6987 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5639 - accuracy: 0.7086 - val_loss: 0.5628 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7202 - val_loss: 0.5540 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7268 - val_loss: 0.5484 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7327 - val_loss: 0.5482 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7369 - val_loss: 0.5514 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7377 - val_loss: 0.5487 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 8/400
263/274 [===========================>..] - ETA: 0s - loss: 0.5092 - accuracy: 0.7452
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7447 - val_loss: 0.5511 - val_accuracy: 0.7182 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.5083878188296294
Confusion Matrix :
 [[3173 1150]
 [ 977 3346]]
Accuracy on test set:    0.7539902845246357
Sensitivity:    0.773999537358316 	 Specificity:    0.7339810316909554
Precision  : 0.7442170818505338
Area Under Curve:    0.7539902845246357
(8646, 4352) (8646,)
Mean MCC = 0.4477 + 0.0242 and Mean AUC = 0.7232 + 0.0122
Mean Sensitivity = 0.7565 + 0.0201 and Mean Specificity = 0.6900 + 0.0240 and Mean Accuracy = 0.7232 + 0.0122
Mean Precision = 0.7096 + 0.0148





Seed   : 994306
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6068 - accuracy: 0.6665 - val_loss: 0.5628 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7108 - val_loss: 0.5440 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7228 - val_loss: 0.5377 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7292 - val_loss: 0.5394 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5256 - accuracy: 0.7342 - val_loss: 0.5364 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7395 - val_loss: 0.5335 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7410 - val_loss: 0.5358 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7471 - val_loss: 0.5323 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7503 - val_loss: 0.5322 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7513 - val_loss: 0.5313 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4883 - accuracy: 0.7565 - val_loss: 0.5403 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7608 - val_loss: 0.5373 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4793 - accuracy: 0.7652 - val_loss: 0.5391 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4735 - accuracy: 0.7642 - val_loss: 0.5485 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4689 - accuracy: 0.7683 - val_loss: 0.5431 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4634 - accuracy: 0.7693 - val_loss: 0.5427 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4575 - accuracy: 0.7743 - val_loss: 0.5469 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4520 - accuracy: 0.7771
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4515 - accuracy: 0.7770 - val_loss: 0.5581 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.4334739154080064
Confusion Matrix :
 [[2924 1399]
 [1056 3267]]
Accuracy on test set:    0.7160536664353458
Sensitivity:    0.7557251908396947 	 Specificity:    0.676382142030997
Precision  : 0.7001714530647235
Area Under Curve:    0.7160536664353458
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6109 - accuracy: 0.6636 - val_loss: 0.5549 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5565 - accuracy: 0.7136 - val_loss: 0.5426 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7234 - val_loss: 0.5377 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7312 - val_loss: 0.5444 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7366 - val_loss: 0.5392 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7429 - val_loss: 0.5332 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7449 - val_loss: 0.5356 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7496 - val_loss: 0.5344 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7525 - val_loss: 0.5366 - val_accuracy: 0.7292 - lr: 0.0010

Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4902 - accuracy: 0.7585 - val_loss: 0.5352 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4852 - accuracy: 0.7600 - val_loss: 0.5390 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4791 - accuracy: 0.7636 - val_loss: 0.5439 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4709 - accuracy: 0.7702 - val_loss: 0.5424 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 14/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4664 - accuracy: 0.7717
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4670 - accuracy: 0.7710 - val_loss: 0.5430 - val_accuracy: 0.7231 - lr: 0.0010
271/271 [==============================] - 0s 637us/step
Independent Testing Matthews Correlation:  0.428824779865393
Confusion Matrix :
 [[2948 1375]
 [1098 3225]]
Accuracy on test set:    0.713971778857275
Sensitivity:    0.7460097154753643 	 Specificity:    0.6819338422391857
Precision  : 0.7010869565217391
Area Under Curve:    0.713971778857275
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6060 - accuracy: 0.6681 - val_loss: 0.5600 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7097 - val_loss: 0.5477 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7231 - val_loss: 0.5440 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7288 - val_loss: 0.5401 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7360 - val_loss: 0.5394 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7402 - val_loss: 0.5356 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7440 - val_loss: 0.5375 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7466 - val_loss: 0.5359 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4964 - accuracy: 0.7528 - val_loss: 0.5357 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7571 - val_loss: 0.5446 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7619 - val_loss: 0.5418 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4756 - accuracy: 0.7642 - val_loss: 0.5403 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7686 - val_loss: 0.5465 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4636 - accuracy: 0.7735 - val_loss: 0.5476 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4588 - accuracy: 0.7742 - val_loss: 0.5462 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4556 - accuracy: 0.7758 - val_loss: 0.5530 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4477 - accuracy: 0.7811 - val_loss: 0.5588 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4413 - accuracy: 0.7837 - val_loss: 0.5697 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4339 - accuracy: 0.7871 - val_loss: 0.5617 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 20/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4315 - accuracy: 0.7892
Epoch 20: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4312 - accuracy: 0.7890 - val_loss: 0.5741 - val_accuracy: 0.7226 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.43615187160054236
Confusion Matrix :
 [[3153 1170]
 [1268 3055]]
Accuracy on test set:    0.7180198935924127
Sensitivity:    0.7066851723340273 	 Specificity:    0.7293546148507981
Precision  : 0.7230769230769231
Area Under Curve:    0.7180198935924127
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6018 - accuracy: 0.6709 - val_loss: 0.5564 - val_accuracy: 0.7092 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5551 - accuracy: 0.7149 - val_loss: 0.5453 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7250 - val_loss: 0.5400 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7313 - val_loss: 0.5361 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7363 - val_loss: 0.5322 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7411 - val_loss: 0.5319 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7474 - val_loss: 0.5362 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7510 - val_loss: 0.5353 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7545 - val_loss: 0.5302 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4891 - accuracy: 0.7582 - val_loss: 0.5364 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4851 - accuracy: 0.7618 - val_loss: 0.5335 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4789 - accuracy: 0.7669 - val_loss: 0.5382 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4715 - accuracy: 0.7679 - val_loss: 0.5375 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4676 - accuracy: 0.7709 - val_loss: 0.5361 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4596 - accuracy: 0.7759 - val_loss: 0.5418 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4527 - accuracy: 0.7802
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4529 - accuracy: 0.7797 - val_loss: 0.5565 - val_accuracy: 0.7199 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.43070396024633034
Confusion Matrix :
 [[2720 1603]
 [ 884 3439]]
Accuracy on test set:    0.71235253296322
Sensitivity:    0.7955123756650474 	 Specificity:    0.6291926902613926
Precision  : 0.682070606902023
Area Under Curve:    0.7123525329632201
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6100 - accuracy: 0.6631 - val_loss: 0.5710 - val_accuracy: 0.6983 - lr: 0.0010
Epoch 2/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5600 - accuracy: 0.7118 - val_loss: 0.5468 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7226 - val_loss: 0.5379 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7295 - val_loss: 0.5350 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7353 - val_loss: 0.5334 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7392 - val_loss: 0.5332 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5110 - accuracy: 0.7445 - val_loss: 0.5320 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7467 - val_loss: 0.5314 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5017 - accuracy: 0.7501 - val_loss: 0.5354 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7533 - val_loss: 0.5386 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7588 - val_loss: 0.5325 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4785 - accuracy: 0.7622
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4789 - accuracy: 0.7618 - val_loss: 0.5363 - val_accuracy: 0.7245 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4421792191048318
Confusion Matrix :
 [[3247 1076]
 [1339 2984]]
Accuracy on test set:    0.7206800832755031
Sensitivity:    0.6902613925514689 	 Specificity:    0.7510987739995374
Precision  : 0.734975369458128
Area Under Curve:    0.7206800832755031
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6051 - accuracy: 0.6674 - val_loss: 0.5574 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7121 - val_loss: 0.5449 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7223 - val_loss: 0.5375 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7302 - val_loss: 0.5405 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7346 - val_loss: 0.5468 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7375 - val_loss: 0.5325 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5144 - accuracy: 0.7430 - val_loss: 0.5427 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7467 - val_loss: 0.5293 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7515 - val_loss: 0.5436 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7558 - val_loss: 0.5304 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7594 - val_loss: 0.5338 - val_accuracy: 0.7334 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7619 - val_loss: 0.5333 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4781 - accuracy: 0.7658 - val_loss: 0.5363 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4740 - accuracy: 0.7660 - val_loss: 0.5392 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4656 - accuracy: 0.7726 - val_loss: 0.5382 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 16/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4610 - accuracy: 0.7774
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4619 - accuracy: 0.7763 - val_loss: 0.5434 - val_accuracy: 0.7237 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.42958817678279476
Confusion Matrix :
 [[2986 1337]
 [1131 3192]]
Accuracy on test set:    0.7145500809622947
Sensitivity:    0.7383761276891048 	 Specificity:    0.6907240342354846
Precision  : 0.7047913446676971
Area Under Curve:    0.7145500809622947
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6132 - accuracy: 0.6608 - val_loss: 0.5625 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5615 - accuracy: 0.7123 - val_loss: 0.5463 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7230 - val_loss: 0.5464 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7287 - val_loss: 0.5366 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5278 - accuracy: 0.7339 - val_loss: 0.5365 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5197 - accuracy: 0.7400 - val_loss: 0.5349 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7415 - val_loss: 0.5340 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7450 - val_loss: 0.5337 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
261/274 [===========================>..] - ETA: 0s - loss: 0.5004 - accuracy: 0.7523
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7517 - val_loss: 0.5394 - val_accuracy: 0.7247 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.44652390095093036
Confusion Matrix :
 [[2838 1485]
 [ 924 3399]]
Accuracy on test set:    0.7213740458015268
Sensitivity:    0.7862595419847328 	 Specificity:    0.6564885496183206
Precision  : 0.6959459459459459
Area Under Curve:    0.7213740458015268
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6090 - accuracy: 0.6665 - val_loss: 0.5597 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5577 - accuracy: 0.7121 - val_loss: 0.5465 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7222 - val_loss: 0.5420 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7289 - val_loss: 0.5420 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5260 - accuracy: 0.7336 - val_loss: 0.5350 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7426 - val_loss: 0.5350 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7453 - val_loss: 0.5333 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7501 - val_loss: 0.5388 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7558 - val_loss: 0.5372 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4875 - accuracy: 0.7598 - val_loss: 0.5390 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4817 - accuracy: 0.7642
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4811 - accuracy: 0.7642 - val_loss: 0.5394 - val_accuracy: 0.7268 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4510809641642856
Confusion Matrix :
 [[3147 1176]
 [1197 3126]]
Accuracy on test set:    0.7255378209576683
Sensitivity:    0.7231089521165857 	 Specificity:    0.7279666897987509
Precision  : 0.7266387726638772
Area Under Curve:    0.7255378209576684
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6092 - accuracy: 0.6668 - val_loss: 0.5660 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7104 - val_loss: 0.5498 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7231 - val_loss: 0.5439 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7296 - val_loss: 0.5432 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5268 - accuracy: 0.7349 - val_loss: 0.5364 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7391 - val_loss: 0.5406 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7435 - val_loss: 0.5426 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7473 - val_loss: 0.5341 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7513 - val_loss: 0.5366 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4893 - accuracy: 0.7555
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7557 - val_loss: 0.5382 - val_accuracy: 0.7291 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.47324584572190936
Confusion Matrix :
 [[3246 1077]
 [1201 3122]]
Accuracy on test set:    0.7365255609530419
Sensitivity:    0.7221836687485542 	 Specificity:    0.7508674531575295
Precision  : 0.7435103596094308
Area Under Curve:    0.7365255609530418
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6259 - accuracy: 0.6521 - val_loss: 0.5724 - val_accuracy: 0.7001 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5715 - accuracy: 0.7030 - val_loss: 0.5562 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5569 - accuracy: 0.7139 - val_loss: 0.5548 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7213 - val_loss: 0.5490 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7268 - val_loss: 0.5450 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7316 - val_loss: 0.5432 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5264 - accuracy: 0.7352 - val_loss: 0.5423 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5200 - accuracy: 0.7387 - val_loss: 0.5395 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7421 - val_loss: 0.5451 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5102 - accuracy: 0.7426 - val_loss: 0.5412 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7482 - val_loss: 0.5459 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7495 - val_loss: 0.5483 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4925 - accuracy: 0.7527
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7527 - val_loss: 0.5566 - val_accuracy: 0.7160 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4889031477192736
Confusion Matrix :
 [[3447  876]
 [1346 2977]]
Accuracy on test set:    0.7430025445292621
Sensitivity:    0.6886421466574139 	 Specificity:    0.7973629424011104
Precision  : 0.7726446924474436
Area Under Curve:    0.7430025445292622
(8646, 4352) (8646,)
Mean MCC = 0.4461 + 0.0192 and Mean AUC = 0.7222 + 0.0096
Mean Sensitivity = 0.7353 + 0.0348 and Mean Specificity = 0.7091 + 0.0483 and Mean Accuracy = 0.7222 + 0.0096
Mean Precision = 0.7185 + 0.0256





Seed   : 879715
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6149 - accuracy: 0.6623 - val_loss: 0.5659 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7115 - val_loss: 0.5510 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7246 - val_loss: 0.5424 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5310 - accuracy: 0.7311 - val_loss: 0.5428 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7358 - val_loss: 0.5385 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5157 - accuracy: 0.7407 - val_loss: 0.5351 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7425 - val_loss: 0.5386 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7483 - val_loss: 0.5445 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7501 - val_loss: 0.5339 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7568 - val_loss: 0.5465 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 11/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4846 - accuracy: 0.7586
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4847 - accuracy: 0.7588 - val_loss: 0.5358 - val_accuracy: 0.7223 - lr: 0.0010
271/271 [==============================] - 0s 638us/step
Independent Testing Matthews Correlation:  0.4384489503629558
Confusion Matrix :
 [[3025 1298]
 [1131 3192]]
Accuracy on test set:    0.7190608373814481

Sensitivity:    0.7383761276891048 	 Specificity:    0.6997455470737913
Precision  : 0.710913140311804
Area Under Curve:    0.719060837381448
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6084 - accuracy: 0.6642 - val_loss: 0.5811 - val_accuracy: 0.6870 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5595 - accuracy: 0.7110 - val_loss: 0.5532 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7227 - val_loss: 0.5468 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7283 - val_loss: 0.5441 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7357 - val_loss: 0.5461 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7401 - val_loss: 0.5430 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5116 - accuracy: 0.7442 - val_loss: 0.5472 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5073 - accuracy: 0.7469 - val_loss: 0.5382 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5002 - accuracy: 0.7530 - val_loss: 0.5436 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7569 - val_loss: 0.5425 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7597 - val_loss: 0.5439 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4809 - accuracy: 0.7628 - val_loss: 0.5396 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7650 - val_loss: 0.5506 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4704 - accuracy: 0.7684
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4712 - accuracy: 0.7678 - val_loss: 0.5490 - val_accuracy: 0.7185 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.42545804195396747
Confusion Matrix :
 [[3045 1278]
 [1206 3117]]
Accuracy on test set:    0.7126995142262318
Sensitivity:    0.721027064538515 	 Specificity:    0.7043719639139486
Precision  : 0.7092150170648465
Area Under Curve:    0.7126995142262317
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6134 - accuracy: 0.6611 - val_loss: 0.5681 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5613 - accuracy: 0.7103 - val_loss: 0.5543 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7214 - val_loss: 0.5425 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7271 - val_loss: 0.5406 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5263 - accuracy: 0.7329 - val_loss: 0.5427 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7361 - val_loss: 0.5409 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7377 - val_loss: 0.5379 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7440 - val_loss: 0.5380 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7470 - val_loss: 0.5375 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4988 - accuracy: 0.7506 - val_loss: 0.5364 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7546 - val_loss: 0.5465 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4864 - accuracy: 0.7583 - val_loss: 0.5415 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 13/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4809 - accuracy: 0.7619
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4805 - accuracy: 0.7617 - val_loss: 0.5407 - val_accuracy: 0.7235 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4456928346109423
Confusion Matrix :
 [[3065 1258]
 [1139 3184]]
Accuracy on test set:    0.7227619708535739
Sensitivity:    0.7365255609530419 	 Specificity:    0.7089983807541059
Precision  : 0.7167942368302567
Area Under Curve:    0.7227619708535739
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6119 - accuracy: 0.6590 - val_loss: 0.5627 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7096 - val_loss: 0.5522 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7220 - val_loss: 0.5424 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7301 - val_loss: 0.5382 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7373 - val_loss: 0.5359 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7420 - val_loss: 0.5374 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5096 - accuracy: 0.7443 - val_loss: 0.5343 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7480 - val_loss: 0.5350 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4966 - accuracy: 0.7520 - val_loss: 0.5349 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7546 - val_loss: 0.5412 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4869 - accuracy: 0.7599 - val_loss: 0.5375 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4819 - accuracy: 0.7612
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4809 - accuracy: 0.7619 - val_loss: 0.5416 - val_accuracy: 0.7321 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.425102971652949
Confusion Matrix :
 [[2986 1337]
 [1150 3173]]
Accuracy on test set:    0.71235253296322
Sensitivity:    0.7339810316909554 	 Specificity:    0.6907240342354846
Precision  : 0.7035476718403547
Area Under Curve:    0.71235253296322
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6124 - accuracy: 0.6616 - val_loss: 0.5672 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5623 - accuracy: 0.7096 - val_loss: 0.5481 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7204 - val_loss: 0.5436 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7296 - val_loss: 0.5376 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7313 - val_loss: 0.5412 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7380 - val_loss: 0.5376 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7432 - val_loss: 0.5401 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7456 - val_loss: 0.5356 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5005 - accuracy: 0.7505 - val_loss: 0.5295 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4932 - accuracy: 0.7557 - val_loss: 0.5335 - val_accuracy: 0.7350 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4898 - accuracy: 0.7572 - val_loss: 0.5340 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7594 - val_loss: 0.5315 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4757 - accuracy: 0.7632 - val_loss: 0.5400 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4693 - accuracy: 0.7685 - val_loss: 0.5428 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4637 - accuracy: 0.7723
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4643 - accuracy: 0.7715 - val_loss: 0.5426 - val_accuracy: 0.7228 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4296369965823061
Confusion Matrix :
 [[3171 1152]
 [1315 3008]]
Accuracy on test set:    0.7146657413832986
Sensitivity:    0.6958130927596576 	 Specificity:    0.7335183900069396
Precision  : 0.7230769230769231
Area Under Curve:    0.7146657413832986
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6099 - accuracy: 0.6643 - val_loss: 0.5580 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7105 - val_loss: 0.5514 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7223 - val_loss: 0.5459 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7305 - val_loss: 0.5353 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5270 - accuracy: 0.7346 - val_loss: 0.5344 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5190 - accuracy: 0.7412 - val_loss: 0.5424 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5137 - accuracy: 0.7434 - val_loss: 0.5330 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7451 - val_loss: 0.5360 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7500 - val_loss: 0.5385 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4974 - accuracy: 0.7538 - val_loss: 0.5431 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7602 - val_loss: 0.5405 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4875 - accuracy: 0.7598 - val_loss: 0.5460 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4775 - accuracy: 0.7650 - val_loss: 0.5433 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4729 - accuracy: 0.7675
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4727 - accuracy: 0.7678 - val_loss: 0.5511 - val_accuracy: 0.7236 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4427295121348451
Confusion Matrix :
 [[3051 1272]
 [1138 3185]]
Accuracy on test set:    0.7212583853805228
Sensitivity:    0.7367568817950497 	 Specificity:    0.7057598889659958
Precision  : 0.7146062373794032
Area Under Curve:    0.7212583853805228
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6027 - accuracy: 0.6710 - val_loss: 0.5573 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5560 - accuracy: 0.7144 - val_loss: 0.5500 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7228 - val_loss: 0.5440 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7294 - val_loss: 0.5390 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.7360 - val_loss: 0.5506 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5159 - accuracy: 0.7415 - val_loss: 0.5344 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5083 - accuracy: 0.7457 - val_loss: 0.5372 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5017 - accuracy: 0.7495 - val_loss: 0.5341 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4963 - accuracy: 0.7534 - val_loss: 0.5358 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7589 - val_loss: 0.5441 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4844 - accuracy: 0.7590 - val_loss: 0.5490 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4754 - accuracy: 0.7670
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4762 - accuracy: 0.7660 - val_loss: 0.5413 - val_accuracy: 0.7253 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.44809629211391994
Confusion Matrix :
 [[2916 1407]
 [ 988 3335]]
Accuracy on test set:    0.7229932916955818
Sensitivity:    0.7714550080962295 	 Specificity:    0.6745315752949341
Precision  : 0.7032897511598482
Area Under Curve:    0.7229932916955818
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6017 - accuracy: 0.6724 - val_loss: 0.5567 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7127 - val_loss: 0.5554 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7223 - val_loss: 0.5385 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7300 - val_loss: 0.5351 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7333 - val_loss: 0.5367 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7402 - val_loss: 0.5356 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7453 - val_loss: 0.5315 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7490 - val_loss: 0.5328 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7525 - val_loss: 0.5309 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7552 - val_loss: 0.5334 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4852 - accuracy: 0.7605 - val_loss: 0.5353 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7624 - val_loss: 0.5338 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4743 - accuracy: 0.7676
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4745 - accuracy: 0.7678 - val_loss: 0.5374 - val_accuracy: 0.7272 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4583258182525526
Confusion Matrix :
 [[3025 1298]
 [1047 3276]]
Accuracy on test set:    0.7287763127457784
Sensitivity:    0.7578070784177654 	 Specificity:    0.6997455470737913
Precision  : 0.7162221250546568
Area Under Curve:    0.7287763127457784
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6048 - accuracy: 0.6695 - val_loss: 0.5657 - val_accuracy: 0.7070 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7122 - val_loss: 0.5455 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7224 - val_loss: 0.5406 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7297 - val_loss: 0.5396 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5263 - accuracy: 0.7372 - val_loss: 0.5410 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7391 - val_loss: 0.5438 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7430 - val_loss: 0.5384 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7465 - val_loss: 0.5524 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5014 - accuracy: 0.7499 - val_loss: 0.5375 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7537 - val_loss: 0.5434 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4877 - accuracy: 0.7571 - val_loss: 0.5499 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7621 - val_loss: 0.5418 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4762 - accuracy: 0.7645 - val_loss: 0.5505 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4702 - accuracy: 0.7683 - val_loss: 0.5463 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4654 - accuracy: 0.7708
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4650 - accuracy: 0.7714 - val_loss: 0.5564 - val_accuracy: 0.7188 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4688777865095982
Confusion Matrix :
 [[3079 1244]
 [1054 3269]]
Accuracy on test set:    0.7342123525329632
Sensitivity:    0.7561878325237104 	 Specificity:    0.712236872542216
Precision  : 0.7243518723687126
Area Under Curve:    0.7342123525329634
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6209 - accuracy: 0.6567 - val_loss: 0.5669 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5673 - accuracy: 0.7060 - val_loss: 0.5502 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5500 - accuracy: 0.7188 - val_loss: 0.5480 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7259 - val_loss: 0.5461 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7295 - val_loss: 0.5463 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5251 - accuracy: 0.7361 - val_loss: 0.5437 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7435 - val_loss: 0.5432 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5096 - accuracy: 0.7450 - val_loss: 0.5426 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7489 - val_loss: 0.5419 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7515 - val_loss: 0.5407 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7555 - val_loss: 0.5448 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7579 - val_loss: 0.5439 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4762 - accuracy: 0.7637 - val_loss: 0.5559 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4717 - accuracy: 0.7676
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4721 - accuracy: 0.7671 - val_loss: 0.5558 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.503532348821738
Confusion Matrix :
 [[3192 1131]
 [1016 3307]]
Accuracy on test set:    0.751677076104557
Sensitivity:    0.7649780245200093 	 Specificity:    0.7383761276891048
Precision  : 0.7451554754393871
Area Under Curve:    0.751677076104557
(8646, 4352) (8646,)
Mean MCC = 0.4486 + 0.0226 and Mean AUC = 0.7240 + 0.0113
Mean Sensitivity = 0.7413 + 0.0213 and Mean Specificity = 0.7068 + 0.0178 and Mean Accuracy = 0.7240 + 0.0113
Mean Precision = 0.7167 + 0.0116





Seed   : 743527
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6025 - accuracy: 0.6710 - val_loss: 0.5657 - val_accuracy: 0.6996 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5565 - accuracy: 0.7141 - val_loss: 0.5538 - val_accuracy: 0.7070 - lr: 0.0010

Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7252 - val_loss: 0.5418 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7311 - val_loss: 0.5390 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.7369 - val_loss: 0.5367 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7417 - val_loss: 0.5417 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7437 - val_loss: 0.5363 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7480 - val_loss: 0.5333 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4954 - accuracy: 0.7527 - val_loss: 0.5384 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4918 - accuracy: 0.7575 - val_loss: 0.5350 - val_accuracy: 0.7330 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4844 - accuracy: 0.7596 - val_loss: 0.5380 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4775 - accuracy: 0.7645 - val_loss: 0.5386 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4723 - accuracy: 0.7671 - val_loss: 0.5461 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4655 - accuracy: 0.7718 - val_loss: 0.5520 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4621 - accuracy: 0.7720
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4623 - accuracy: 0.7722 - val_loss: 0.5526 - val_accuracy: 0.7250 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.4275267534918019
Confusion Matrix :
 [[2921 1402]
 [1078 3245]]
Accuracy on test set:    0.7131621559102476
Sensitivity:    0.7506361323155216 	 Specificity:    0.6756881795049734
Precision  : 0.6982999784807402
Area Under Curve:    0.7131621559102476
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6096 - accuracy: 0.6662 - val_loss: 0.5687 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5582 - accuracy: 0.7102 - val_loss: 0.5547 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7237 - val_loss: 0.5421 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7305 - val_loss: 0.5405 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7370 - val_loss: 0.5441 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7406 - val_loss: 0.5388 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7439 - val_loss: 0.5433 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7491 - val_loss: 0.5403 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4974 - accuracy: 0.7530
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7521 - val_loss: 0.5390 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.44979633818960185
Confusion Matrix :
 [[3086 1237]
 [1142 3181]]
Accuracy on test set:    0.7248438584316447
Sensitivity:    0.7358315984270183 	 Specificity:    0.7138561184362711
Precision  : 0.7200090538705296
Area Under Curve:    0.7248438584316447
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5987 - accuracy: 0.6747 - val_loss: 0.5614 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7140 - val_loss: 0.5491 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7243 - val_loss: 0.5411 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5307 - accuracy: 0.7322 - val_loss: 0.5423 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7355 - val_loss: 0.5384 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7412 - val_loss: 0.5412 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7452 - val_loss: 0.5370 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7493 - val_loss: 0.5437 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7520 - val_loss: 0.5418 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7565 - val_loss: 0.5417 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4847 - accuracy: 0.7585 - val_loss: 0.5408 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4769 - accuracy: 0.7638 - val_loss: 0.5437 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7676 - val_loss: 0.5487 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 14/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4652 - accuracy: 0.7714
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4662 - accuracy: 0.7706 - val_loss: 0.5493 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4483144853198067
Confusion Matrix :
 [[3113 1210]
 [1175 3148]]
Accuracy on test set:    0.7241498959056211
Sensitivity:    0.7281980106407587 	 Specificity:    0.7201017811704835
Precision  : 0.7223497016980266
Area Under Curve:    0.7241498959056212
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6072 - accuracy: 0.6684 - val_loss: 0.5764 - val_accuracy: 0.6975 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7130 - val_loss: 0.5473 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7242 - val_loss: 0.5435 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7323 - val_loss: 0.5401 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7370 - val_loss: 0.5381 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5150 - accuracy: 0.7414 - val_loss: 0.5368 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7438 - val_loss: 0.5369 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7518 - val_loss: 0.5365 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7575 - val_loss: 0.5368 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4881 - accuracy: 0.7596 - val_loss: 0.5364 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4807 - accuracy: 0.7641
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7639 - val_loss: 0.5368 - val_accuracy: 0.7280 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4439446538272062
Confusion Matrix :
 [[3092 1231]
 [1173 3150]]
Accuracy on test set:    0.7219523479065464
Sensitivity:    0.7286606523247745 	 Specificity:    0.7152440434883183
Precision  : 0.7190139237616983
Area Under Curve:    0.7219523479065464
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6045 - accuracy: 0.6678 - val_loss: 0.5603 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5600 - accuracy: 0.7090 - val_loss: 0.5469 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7238 - val_loss: 0.5415 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7278 - val_loss: 0.5396 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5274 - accuracy: 0.7322 - val_loss: 0.5368 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5199 - accuracy: 0.7375 - val_loss: 0.5382 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7409 - val_loss: 0.5375 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5065 - accuracy: 0.7460 - val_loss: 0.5346 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7496 - val_loss: 0.5365 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4960 - accuracy: 0.7533 - val_loss: 0.5404 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4912 - accuracy: 0.7553
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7558 - val_loss: 0.5404 - val_accuracy: 0.7235 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.42758501313400216
Confusion Matrix :
 [[3216 1107]
 [1371 2952]]
Accuracy on test set:    0.7133934767522554
Sensitivity:    0.6828591256072172 	 Specificity:    0.7439278278972935
Precision  : 0.7272727272727273
Area Under Curve:    0.7133934767522555
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6116 - accuracy: 0.6634 - val_loss: 0.5601 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5589 - accuracy: 0.7135 - val_loss: 0.5443 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7238 - val_loss: 0.5408 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7297 - val_loss: 0.5448 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7344 - val_loss: 0.5491 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7412 - val_loss: 0.5355 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5120 - accuracy: 0.7446 - val_loss: 0.5359 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7503 - val_loss: 0.5341 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4951 - accuracy: 0.7525 - val_loss: 0.5315 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7562 - val_loss: 0.5337 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4841 - accuracy: 0.7617 - val_loss: 0.5439 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7645 - val_loss: 0.5381 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4697 - accuracy: 0.7679 - val_loss: 0.5472 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4641 - accuracy: 0.7722 - val_loss: 0.5421 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 15/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4576 - accuracy: 0.7755
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4577 - accuracy: 0.7755 - val_loss: 0.5477 - val_accuracy: 0.7181 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4447397335219055
Confusion Matrix :
 [[2955 1368]
 [1038 3285]]
Accuracy on test set:    0.7217210270645386
Sensitivity:    0.7598889659958362 	 Specificity:    0.6835530881332408
Precision  : 0.7059961315280464
Area Under Curve:    0.7217210270645384
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6299 - accuracy: 0.6479 - val_loss: 0.5716 - val_accuracy: 0.7007 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5682 - accuracy: 0.7057 - val_loss: 0.5563 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5509 - accuracy: 0.7178 - val_loss: 0.5482 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7246 - val_loss: 0.5439 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7287 - val_loss: 0.5491 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5292 - accuracy: 0.7310 - val_loss: 0.5376 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5234 - accuracy: 0.7324 - val_loss: 0.5386 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5168 - accuracy: 0.7393 - val_loss: 0.5385 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7396 - val_loss: 0.5397 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7422 - val_loss: 0.5368 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7441 - val_loss: 0.5384 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4985 - accuracy: 0.7486 - val_loss: 0.5386 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7537 - val_loss: 0.5496 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4891 - accuracy: 0.7550 - val_loss: 0.5440 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4820 - accuracy: 0.7558
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4821 - accuracy: 0.7557 - val_loss: 0.5492 - val_accuracy: 0.7215 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.44636087864180424
Confusion Matrix :
 [[3214 1109]
 [1286 3037]]
Accuracy on test set:    0.7229932916955818
Sensitivity:    0.7025213971778858 	 Specificity:    0.7434651862132778
Precision  : 0.7325132657983598
Area Under Curve:    0.7229932916955817
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6118 - accuracy: 0.6603 - val_loss: 0.5657 - val_accuracy: 0.7007 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.7091 - val_loss: 0.5496 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7210 - val_loss: 0.5451 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7235 - val_loss: 0.5497 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7319 - val_loss: 0.5405 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7360 - val_loss: 0.5388 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7400 - val_loss: 0.5396 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7426 - val_loss: 0.5415 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5054 - accuracy: 0.7463 - val_loss: 0.5407 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7497 - val_loss: 0.5384 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7518 - val_loss: 0.5417 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7542 - val_loss: 0.5504 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7579 - val_loss: 0.5448 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4804 - accuracy: 0.7612 - val_loss: 0.5480 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4753 - accuracy: 0.7633 - val_loss: 0.5457 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4701 - accuracy: 0.7663 - val_loss: 0.5501 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4637 - accuracy: 0.7705 - val_loss: 0.5546 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 18/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4576 - accuracy: 0.7747
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4581 - accuracy: 0.7747 - val_loss: 0.5495 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4459885999503699
Confusion Matrix :
 [[3119 1204]
 [1191 3132]]
Accuracy on test set:    0.7229932916955818
Sensitivity:    0.7244968771686329 	 Specificity:    0.7214897062225306
Precision  : 0.7223247232472325
Area Under Curve:    0.7229932916955818
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6142 - accuracy: 0.6602 - val_loss: 0.5662 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.7083 - val_loss: 0.5557 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7218 - val_loss: 0.5474 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7270 - val_loss: 0.5425 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7332 - val_loss: 0.5496 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7386 - val_loss: 0.5383 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5141 - accuracy: 0.7417 - val_loss: 0.5375 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7445 - val_loss: 0.5444 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5003 - accuracy: 0.7496 - val_loss: 0.5359 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7523 - val_loss: 0.5427 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7581 - val_loss: 0.5415 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4818 - accuracy: 0.7633
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4821 - accuracy: 0.7632 - val_loss: 0.5430 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4739849779170372
Confusion Matrix :
 [[3199 1124]
 [1150 3173]]
Accuracy on test set:    0.7369882026370576
Sensitivity:    0.7339810316909554 	 Specificity:    0.7399953735831598
Precision  : 0.7384221549918548
Area Under Curve:    0.7369882026370577
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6275 - accuracy: 0.6457 - val_loss: 0.5795 - val_accuracy: 0.6928 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5715 - accuracy: 0.7035 - val_loss: 0.5581 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5543 - accuracy: 0.7176 - val_loss: 0.5596 - val_accuracy: 0.7077 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7235 - val_loss: 0.5519 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7274 - val_loss: 0.5524 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5317 - accuracy: 0.7318 - val_loss: 0.5482 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7354 - val_loss: 0.5467 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5190 - accuracy: 0.7403 - val_loss: 0.5476 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7399 - val_loss: 0.5480 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5105 - accuracy: 0.7445 - val_loss: 0.5565 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5031 - accuracy: 0.7489
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7487 - val_loss: 0.5473 - val_accuracy: 0.7195 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.5007162713029928
Confusion Matrix :
 [[3326  997]
 [1163 3160]]
Accuracy on test set:    0.7501734906315058
Sensitivity:    0.7309738607448532 	 Specificity:    0.7693731205181586
Precision  : 0.7601635795044503
Area Under Curve:    0.750173490631506
(8646, 4352) (8646,)
Mean MCC = 0.4509 + 0.0206 and Mean AUC = 0.7252 + 0.0104
Mean Sensitivity = 0.7278 + 0.0208 and Mean Specificity = 0.7227 + 0.0269 and Mean Accuracy = 0.7252 + 0.0104
Mean Precision = 0.7246 + 0.0162





Seed   : 769557
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6106 - accuracy: 0.6642 - val_loss: 0.5594 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7129 - val_loss: 0.5514 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7252 - val_loss: 0.5395 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7312 - val_loss: 0.5372 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7360 - val_loss: 0.5349 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7411 - val_loss: 0.5351 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7443 - val_loss: 0.5338 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7516 - val_loss: 0.5299 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7529 - val_loss: 0.5358 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7565 - val_loss: 0.5307 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7605 - val_loss: 0.5338 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4794 - accuracy: 0.7629 - val_loss: 0.5383 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4726 - accuracy: 0.7668 - val_loss: 0.5429 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4684 - accuracy: 0.7690 - val_loss: 0.5421 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 15/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4601 - accuracy: 0.7744
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4617 - accuracy: 0.7738 - val_loss: 0.5417 - val_accuracy: 0.7240 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.40263980207312317
Confusion Matrix :
 [[2938 1385]
 [1199 3124]]
Accuracy on test set:    0.7011334721258385
Sensitivity:    0.72264631043257 	 Specificity:    0.6796206338191071
Precision  : 0.6928365491239743
Area Under Curve:    0.7011334721258385
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6106 - accuracy: 0.6644 - val_loss: 0.5694 - val_accuracy: 0.6975 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7104 - val_loss: 0.5472 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7216 - val_loss: 0.5387 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7298 - val_loss: 0.5331 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7341 - val_loss: 0.5310 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7365 - val_loss: 0.5293 - val_accuracy: 0.7361 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7390 - val_loss: 0.5316 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7459 - val_loss: 0.5294 - val_accuracy: 0.7343 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7472 - val_loss: 0.5312 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4988 - accuracy: 0.7528 - val_loss: 0.5302 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4938 - accuracy: 0.7550
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7547 - val_loss: 0.5295 - val_accuracy: 0.7343 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4393154586811633
Confusion Matrix :
 [[2966 1357]
 [1071 3252]]
Accuracy on test set:    0.719176497802452
Sensitivity:    0.7522553782095767 	 Specificity:    0.6860976173953273
Precision  : 0.7055760468648297
Area Under Curve:    0.719176497802452
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6156 - accuracy: 0.6591 - val_loss: 0.5609 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5613 - accuracy: 0.7100 - val_loss: 0.5570 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7196 - val_loss: 0.5352 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7269 - val_loss: 0.5355 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7334 - val_loss: 0.5555 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5207 - accuracy: 0.7369 - val_loss: 0.5325 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7414 - val_loss: 0.5309 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7463 - val_loss: 0.5292 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7504 - val_loss: 0.5297 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7553 - val_loss: 0.5344 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4883 - accuracy: 0.7567 - val_loss: 0.5346 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4817 - accuracy: 0.7604 - val_loss: 0.5340 - val_accuracy: 0.7286 - lr: 0.0010

Epoch 13/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4737 - accuracy: 0.7658
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4749 - accuracy: 0.7654 - val_loss: 0.5525 - val_accuracy: 0.7182 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4410998715292834
Confusion Matrix :
 [[2686 1637]
 [ 814 3509]]
Accuracy on test set:    0.7165163081193615
Sensitivity:    0.811704834605598 	 Specificity:    0.6213277816331252
Precision  : 0.6818888457054022
Area Under Curve:    0.7165163081193615
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6122 - accuracy: 0.6646 - val_loss: 0.5539 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5612 - accuracy: 0.7128 - val_loss: 0.5438 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7216 - val_loss: 0.5412 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7296 - val_loss: 0.5330 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5285 - accuracy: 0.7359 - val_loss: 0.5302 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5221 - accuracy: 0.7370 - val_loss: 0.5271 - val_accuracy: 0.7327 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7397 - val_loss: 0.5275 - val_accuracy: 0.7334 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5102 - accuracy: 0.7457 - val_loss: 0.5261 - val_accuracy: 0.7357 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7481 - val_loss: 0.5305 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4966 - accuracy: 0.7526 - val_loss: 0.5290 - val_accuracy: 0.7330 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4933 - accuracy: 0.7546 - val_loss: 0.5292 - val_accuracy: 0.7331 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7553 - val_loss: 0.5366 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4828 - accuracy: 0.7618
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7612 - val_loss: 0.5342 - val_accuracy: 0.7269 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.41590585639247246
Confusion Matrix :
 [[3183 1140]
 [1388 2935]]
Accuracy on test set:    0.7076104557020587
Sensitivity:    0.6789266712930835 	 Specificity:    0.7362942401110341
Precision  : 0.7202453987730061
Area Under Curve:    0.7076104557020587
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6184 - accuracy: 0.6573 - val_loss: 0.5621 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7087 - val_loss: 0.5396 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7199 - val_loss: 0.5413 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7275 - val_loss: 0.5305 - val_accuracy: 0.7337 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5287 - accuracy: 0.7308 - val_loss: 0.5462 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5202 - accuracy: 0.7376 - val_loss: 0.5295 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7406 - val_loss: 0.5268 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7435 - val_loss: 0.5269 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5012 - accuracy: 0.7480 - val_loss: 0.5295 - val_accuracy: 0.7361 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7538 - val_loss: 0.5332 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4899 - accuracy: 0.7561 - val_loss: 0.5361 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7609 - val_loss: 0.5291 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7628 - val_loss: 0.5387 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4699 - accuracy: 0.7667
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4692 - accuracy: 0.7674 - val_loss: 0.5428 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.43731134396512583
Confusion Matrix :
 [[3020 1303]
 [1131 3192]]
Accuracy on test set:    0.7184825352764284
Sensitivity:    0.7383761276891048 	 Specificity:    0.6985889428637521
Precision  : 0.7101223581757509
Area Under Curve:    0.7184825352764282
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6050 - accuracy: 0.6675 - val_loss: 0.5606 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5582 - accuracy: 0.7114 - val_loss: 0.5388 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7230 - val_loss: 0.5312 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7311 - val_loss: 0.5322 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7381 - val_loss: 0.5293 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5150 - accuracy: 0.7411 - val_loss: 0.5287 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7459 - val_loss: 0.5252 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7503 - val_loss: 0.5427 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7547 - val_loss: 0.5288 - val_accuracy: 0.7355 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4883 - accuracy: 0.7595 - val_loss: 0.5331 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7625 - val_loss: 0.5288 - val_accuracy: 0.7335 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7650 - val_loss: 0.5283 - val_accuracy: 0.7345 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4693 - accuracy: 0.7700 - val_loss: 0.5307 - val_accuracy: 0.7377 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4637 - accuracy: 0.7753 - val_loss: 0.5314 - val_accuracy: 0.7357 - lr: 0.0010
Epoch 15/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4596 - accuracy: 0.7756 - val_loss: 0.5413 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4515 - accuracy: 0.7821 - val_loss: 0.5387 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4440 - accuracy: 0.7843 - val_loss: 0.5427 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4381 - accuracy: 0.7872
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4380 - accuracy: 0.7869 - val_loss: 0.5483 - val_accuracy: 0.7326 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.434762035357001
Confusion Matrix :
 [[2857 1466]
 [ 989 3334]]
Accuracy on test set:    0.7160536664353458
Sensitivity:    0.7712236872542216 	 Specificity:    0.6608836456164701
Precision  : 0.6945833333333333
Area Under Curve:    0.7160536664353458
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6132 - accuracy: 0.6600 - val_loss: 0.5687 - val_accuracy: 0.7023 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7102 - val_loss: 0.5566 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7213 - val_loss: 0.5457 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7285 - val_loss: 0.5403 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7323 - val_loss: 0.5351 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7362 - val_loss: 0.5343 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7420 - val_loss: 0.5367 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7465 - val_loss: 0.5360 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7485 - val_loss: 0.5418 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7513 - val_loss: 0.5386 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7564 - val_loss: 0.5397 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7578 - val_loss: 0.5345 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4832 - accuracy: 0.7583 - val_loss: 0.5408 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4745 - accuracy: 0.7656
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4753 - accuracy: 0.7648 - val_loss: 0.5389 - val_accuracy: 0.7312 - lr: 0.0010
271/271 [==============================] - 0s 668us/step
Independent Testing Matthews Correlation:  0.45404746760374426
Confusion Matrix :
 [[3079 1244]
 [1117 3206]]
Accuracy on test set:    0.7269257460097155
Sensitivity:    0.7416146194772149 	 Specificity:    0.712236872542216
Precision  : 0.7204494382022472
Area Under Curve:    0.7269257460097155
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6024 - accuracy: 0.6694 - val_loss: 0.5612 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7107 - val_loss: 0.5486 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7230 - val_loss: 0.5478 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7292 - val_loss: 0.5445 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5269 - accuracy: 0.7327 - val_loss: 0.5397 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5192 - accuracy: 0.7383 - val_loss: 0.5363 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7450 - val_loss: 0.5352 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5057 - accuracy: 0.7460 - val_loss: 0.5396 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4985 - accuracy: 0.7524 - val_loss: 0.5340 - val_accuracy: 0.7345 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7568 - val_loss: 0.5371 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4868 - accuracy: 0.7591 - val_loss: 0.5396 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7619 - val_loss: 0.5449 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4758 - accuracy: 0.7659 - val_loss: 0.5355 - val_accuracy: 0.7350 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4701 - accuracy: 0.7680 - val_loss: 0.5438 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4609 - accuracy: 0.7720 - val_loss: 0.5481 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4557 - accuracy: 0.7774 - val_loss: 0.5480 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4535 - accuracy: 0.7778 - val_loss: 0.5570 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 18/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4448 - accuracy: 0.7819
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4450 - accuracy: 0.7817 - val_loss: 0.5609 - val_accuracy: 0.7335 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.46314746201753887
Confusion Matrix :
 [[3133 1190]
 [1131 3192]]
Accuracy on test set:    0.7315521628498728
Sensitivity:    0.7383761276891048 	 Specificity:    0.7247281980106408
Precision  : 0.7284345047923323
Area Under Curve:    0.7315521628498728
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6124 - accuracy: 0.6634 - val_loss: 0.5668 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5633 - accuracy: 0.7074 - val_loss: 0.5493 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5490 - accuracy: 0.7200 - val_loss: 0.5505 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7275 - val_loss: 0.5413 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7296 - val_loss: 0.5433 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5231 - accuracy: 0.7359 - val_loss: 0.5432 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5159 - accuracy: 0.7407 - val_loss: 0.5376 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5078 - accuracy: 0.7464 - val_loss: 0.5446 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7492 - val_loss: 0.5397 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7511 - val_loss: 0.5455 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7569 - val_loss: 0.5502 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4810 - accuracy: 0.7618
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4820 - accuracy: 0.7615 - val_loss: 0.5479 - val_accuracy: 0.7265 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4562447954784501
Confusion Matrix :
 [[3107 1216]
 [1135 3188]]
Accuracy on test set:    0.7280823502197548
Sensitivity:    0.7374508443210733 	 Specificity:    0.7187138561184363
Precision  : 0.7238873751135332
Area Under Curve:    0.7280823502197549
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6159 - accuracy: 0.6580 - val_loss: 0.5673 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5665 - accuracy: 0.7085 - val_loss: 0.5529 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5508 - accuracy: 0.7211 - val_loss: 0.5434 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7252 - val_loss: 0.5427 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7295 - val_loss: 0.5403 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5268 - accuracy: 0.7335 - val_loss: 0.5402 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7380 - val_loss: 0.5409 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7423 - val_loss: 0.5392 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7464 - val_loss: 0.5385 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7488 - val_loss: 0.5415 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7525 - val_loss: 0.5379 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7551 - val_loss: 0.5427 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4857 - accuracy: 0.7593 - val_loss: 0.5416 - val_accuracy: 0.7350 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4802 - accuracy: 0.7643 - val_loss: 0.5512 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4733 - accuracy: 0.7666 - val_loss: 0.5532 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4689 - accuracy: 0.7682 - val_loss: 0.5558 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4643 - accuracy: 0.7726 - val_loss: 0.5495 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4562 - accuracy: 0.7778
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4568 - accuracy: 0.7776 - val_loss: 0.5542 - val_accuracy: 0.7262 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4734153133458791
Confusion Matrix :
 [[3435  888]
 [1403 2920]]
Accuracy on test set:    0.7350219754799907
Sensitivity:    0.6754568586629656 	 Specificity:    0.794587092297016
Precision  : 0.7668067226890757
Area Under Curve:    0.7350219754799907
(8646, 4352) (8646,)
Mean MCC = 0.4418 + 0.0202 and Mean AUC = 0.7201 + 0.0101
Mean Sensitivity = 0.7368 + 0.0379 and Mean Specificity = 0.7033 + 0.0443 and Mean Accuracy = 0.7201 + 0.0101
Mean Precision = 0.7145 + 0.0226





Seed   : 663181
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6076 - accuracy: 0.6671 - val_loss: 0.5624 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7126 - val_loss: 0.5480 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7245 - val_loss: 0.5517 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7297 - val_loss: 0.5402 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7365 - val_loss: 0.5387 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5178 - accuracy: 0.7389 - val_loss: 0.5409 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7439 - val_loss: 0.5359 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7477 - val_loss: 0.5357 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7533 - val_loss: 0.5368 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7578 - val_loss: 0.5458 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7604 - val_loss: 0.5346 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4771 - accuracy: 0.7645 - val_loss: 0.5380 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4721 - accuracy: 0.7679 - val_loss: 0.5430 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4631 - accuracy: 0.7720 - val_loss: 0.5444 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4561 - accuracy: 0.7749 - val_loss: 0.5551 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4532 - accuracy: 0.7783 - val_loss: 0.5562 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4492 - accuracy: 0.7782 - val_loss: 0.5581 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4419 - accuracy: 0.7835
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4420 - accuracy: 0.7833 - val_loss: 0.5632 - val_accuracy: 0.7154 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.41780703714546447
Confusion Matrix :
 [[3034 1289]
 [1228 3095]]
Accuracy on test set:    0.7088827203331021
Sensitivity:    0.7159380060143419 	 Specificity:    0.7018274346518621
Precision  : 0.7059762773722628
Area Under Curve:    0.7088827203331021
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6158 - accuracy: 0.6567 - val_loss: 0.5675 - val_accuracy: 0.7005 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5630 - accuracy: 0.7105 - val_loss: 0.5537 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7217 - val_loss: 0.5509 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7279 - val_loss: 0.5477 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5281 - accuracy: 0.7341 - val_loss: 0.5480 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7365 - val_loss: 0.5405 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7436 - val_loss: 0.5415 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7465 - val_loss: 0.5397 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5003 - accuracy: 0.7509 - val_loss: 0.5385 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4961 - accuracy: 0.7540 - val_loss: 0.5396 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7563 - val_loss: 0.5441 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7592 - val_loss: 0.5472 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4756 - accuracy: 0.7661 - val_loss: 0.5475 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4724 - accuracy: 0.7661 - val_loss: 0.5565 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4687 - accuracy: 0.7658 - val_loss: 0.5512 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4649 - accuracy: 0.7687 - val_loss: 0.5508 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4564 - accuracy: 0.7746
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4565 - accuracy: 0.7744 - val_loss: 0.5573 - val_accuracy: 0.7204 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.42224439570329003
Confusion Matrix :
 [[2990 1333]
 [1166 3157]]
Accuracy on test set:    0.7109646079111728
Sensitivity:    0.7302798982188295 	 Specificity:    0.6916493176035161
Precision  : 0.7031180400890868
Area Under Curve:    0.7109646079111728
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6018 - accuracy: 0.6713 - val_loss: 0.5663 - val_accuracy: 0.7034 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5537 - accuracy: 0.7155 - val_loss: 0.5542 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7271 - val_loss: 0.5447 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7306 - val_loss: 0.5417 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7357 - val_loss: 0.5418 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7423 - val_loss: 0.5437 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7478 - val_loss: 0.5464 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5037 - accuracy: 0.7494 - val_loss: 0.5401 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7541 - val_loss: 0.5490 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7585 - val_loss: 0.5484 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7630 - val_loss: 0.5421 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4786 - accuracy: 0.7650 - val_loss: 0.5481 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4695 - accuracy: 0.7706 - val_loss: 0.5559 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4640 - accuracy: 0.7735 - val_loss: 0.5609 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4570 - accuracy: 0.7779 - val_loss: 0.5605 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4498 - accuracy: 0.7818 - val_loss: 0.5644 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4482 - accuracy: 0.7809 - val_loss: 0.5759 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4376 - accuracy: 0.7872 - val_loss: 0.5702 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4353 - accuracy: 0.7886 - val_loss: 0.5778 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4267 - accuracy: 0.7937 - val_loss: 0.5822 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4244 - accuracy: 0.7945 - val_loss: 0.5773 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 22/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4177 - accuracy: 0.7978
Epoch 22: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4184 - accuracy: 0.7974 - val_loss: 0.5904 - val_accuracy: 0.7142 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4280007529181615
Confusion Matrix :
 [[3192 1131]
 [1344 2979]]
Accuracy on test set:    0.7137404580152672
Sensitivity:    0.6891047883414295 	 Specificity:    0.7383761276891048
Precision  : 0.7248175182481752
Area Under Curve:    0.7137404580152671
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5993 - accuracy: 0.6729 - val_loss: 0.5598 - val_accuracy: 0.7015 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5549 - accuracy: 0.7156 - val_loss: 0.5510 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7263 - val_loss: 0.5470 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7297 - val_loss: 0.5408 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5227 - accuracy: 0.7382 - val_loss: 0.5442 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7408 - val_loss: 0.5378 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5096 - accuracy: 0.7456 - val_loss: 0.5351 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7512 - val_loss: 0.5405 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7546 - val_loss: 0.5384 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7577 - val_loss: 0.5385 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7621 - val_loss: 0.5417 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4764 - accuracy: 0.7668 - val_loss: 0.5459 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4720 - accuracy: 0.7684 - val_loss: 0.5509 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4646 - accuracy: 0.7721
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4655 - accuracy: 0.7716 - val_loss: 0.5529 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.43197829728772696
Confusion Matrix :
 [[3242 1081]
 [1379 2944]]
Accuracy on test set:    0.7154753643303262
Sensitivity:    0.6810085588711543 	 Specificity:    0.749942169789498
Precision  : 0.7314285714285714
Area Under Curve:    0.7154753643303261
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6048 - accuracy: 0.6686 - val_loss: 0.5556 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5613 - accuracy: 0.7090 - val_loss: 0.5472 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7238 - val_loss: 0.5508 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7306 - val_loss: 0.5409 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7358 - val_loss: 0.5380 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7408 - val_loss: 0.5371 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5102 - accuracy: 0.7445 - val_loss: 0.5356 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5052 - accuracy: 0.7467 - val_loss: 0.5378 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7507 - val_loss: 0.5362 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7570 - val_loss: 0.5337 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4821 - accuracy: 0.7607 - val_loss: 0.5351 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7634 - val_loss: 0.5457 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4699 - accuracy: 0.7690 - val_loss: 0.5423 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4673 - accuracy: 0.7699 - val_loss: 0.5401 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4623 - accuracy: 0.7730 - val_loss: 0.5462 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4544 - accuracy: 0.7788
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4548 - accuracy: 0.7784 - val_loss: 0.5494 - val_accuracy: 0.7230 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.42846729274184553
Confusion Matrix :
 [[3124 1199]
 [1272 3051]]
Accuracy on test set:    0.7142030996992829
Sensitivity:    0.7057598889659958 	 Specificity:    0.72264631043257
Precision  : 0.7178823529411764
Area Under Curve:    0.7142030996992829
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6045 - accuracy: 0.6655 - val_loss: 0.5625 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5562 - accuracy: 0.7135 - val_loss: 0.5487 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7226 - val_loss: 0.5637 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7298 - val_loss: 0.5451 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5256 - accuracy: 0.7347 - val_loss: 0.5368 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7394 - val_loss: 0.5409 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7428 - val_loss: 0.5390 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7483 - val_loss: 0.5335 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7508 - val_loss: 0.5350 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7542 - val_loss: 0.5486 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4878 - accuracy: 0.7595 - val_loss: 0.5343 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7641 - val_loss: 0.5386 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4748 - accuracy: 0.7659 - val_loss: 0.5436 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4680 - accuracy: 0.7703 - val_loss: 0.5431 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4619 - accuracy: 0.7751 - val_loss: 0.5395 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4593 - accuracy: 0.7770 - val_loss: 0.5450 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4529 - accuracy: 0.7790 - val_loss: 0.5534 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4467 - accuracy: 0.7834
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4464 - accuracy: 0.7836 - val_loss: 0.5567 - val_accuracy: 0.7227 - lr: 0.0010
271/271 [==============================] - 0s 665us/step
Independent Testing Matthews Correlation:  0.4261007631786946
Confusion Matrix :
 [[3205 1118]
 [1366 2957]]
Accuracy on test set:    0.7126995142262318
Sensitivity:    0.6840157298172566 	 Specificity:    0.741383298635207
Precision  : 0.7256441717791411
Area Under Curve:    0.7126995142262318
(8646, 4352) (8646,)
Epoch 1/400

274/274 [==============================] - 1s 3ms/step - loss: 0.5986 - accuracy: 0.6731 - val_loss: 0.5632 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5562 - accuracy: 0.7150 - val_loss: 0.5557 - val_accuracy: 0.7077 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7229 - val_loss: 0.5457 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7311 - val_loss: 0.5460 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7380 - val_loss: 0.5399 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7392 - val_loss: 0.5411 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5105 - accuracy: 0.7464 - val_loss: 0.5388 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7515 - val_loss: 0.5374 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4973 - accuracy: 0.7517 - val_loss: 0.5401 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7566 - val_loss: 0.5455 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4869 - accuracy: 0.7598 - val_loss: 0.5502 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4796 - accuracy: 0.7643 - val_loss: 0.5404 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4724 - accuracy: 0.7666
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4726 - accuracy: 0.7663 - val_loss: 0.5432 - val_accuracy: 0.7230 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4386345939935646
Confusion Matrix :
 [[3004 1319]
 [1110 3213]]
Accuracy on test set:    0.7190608373814481
Sensitivity:    0.7432338653712699 	 Specificity:    0.6948878093916262
Precision  : 0.7089585172109444
Area Under Curve:    0.719060837381448
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6055 - accuracy: 0.6682 - val_loss: 0.5641 - val_accuracy: 0.7028 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5597 - accuracy: 0.7118 - val_loss: 0.5519 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7201 - val_loss: 0.5472 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7317 - val_loss: 0.5447 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5252 - accuracy: 0.7362 - val_loss: 0.5450 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5192 - accuracy: 0.7383 - val_loss: 0.5411 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7417 - val_loss: 0.5382 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7452 - val_loss: 0.5468 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5017 - accuracy: 0.7497 - val_loss: 0.5408 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4987 - accuracy: 0.7532 - val_loss: 0.5470 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4893 - accuracy: 0.7574 - val_loss: 0.5477 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4855 - accuracy: 0.7585
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7578 - val_loss: 0.5437 - val_accuracy: 0.7238 - lr: 0.0010
271/271 [==============================] - 0s 638us/step
Independent Testing Matthews Correlation:  0.45925128621586114
Confusion Matrix :
 [[3233 1090]
 [1249 3074]]
Accuracy on test set:    0.729470275271802
Sensitivity:    0.7110802683321767 	 Specificity:    0.7478602822114272
Precision  : 0.7382324687800192
Area Under Curve:    0.7294702752718021
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6128 - accuracy: 0.6606 - val_loss: 0.5691 - val_accuracy: 0.7059 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5664 - accuracy: 0.7071 - val_loss: 0.5563 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5516 - accuracy: 0.7177 - val_loss: 0.5542 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7251 - val_loss: 0.5468 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7306 - val_loss: 0.5486 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5297 - accuracy: 0.7345 - val_loss: 0.5437 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5220 - accuracy: 0.7352 - val_loss: 0.5379 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7426 - val_loss: 0.5432 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5096 - accuracy: 0.7459 - val_loss: 0.5410 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7465 - val_loss: 0.5441 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7530 - val_loss: 0.5448 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4898 - accuracy: 0.7566
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4901 - accuracy: 0.7564 - val_loss: 0.5471 - val_accuracy: 0.7113 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.4733573444987887
Confusion Matrix :
 [[2833 1490]
 [ 812 3511]]
Accuracy on test set:    0.7337497108489475
Sensitivity:    0.8121674762896137 	 Specificity:    0.6553319454082813
Precision  : 0.7020595880823836
Area Under Curve:    0.7337497108489476
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6163 - accuracy: 0.6590 - val_loss: 0.5689 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5655 - accuracy: 0.7067 - val_loss: 0.5550 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5505 - accuracy: 0.7194 - val_loss: 0.5520 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7279 - val_loss: 0.5518 - val_accuracy: 0.7107 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7323 - val_loss: 0.5501 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7383 - val_loss: 0.5440 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7410 - val_loss: 0.5452 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5106 - accuracy: 0.7455 - val_loss: 0.5443 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5047 - accuracy: 0.7463 - val_loss: 0.5561 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7514 - val_loss: 0.5421 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4926 - accuracy: 0.7572
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4924 - accuracy: 0.7570 - val_loss: 0.5507 - val_accuracy: 0.7232 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.5122173791201112
Confusion Matrix :
 [[3305 1018]
 [1091 3232]]
Accuracy on test set:    0.7560721721027065
Sensitivity:    0.7476289613694194 	 Specificity:    0.7645153828359935
Precision  : 0.7604705882352941
Area Under Curve:    0.7560721721027064
(8646, 4352) (8646,)
Mean MCC = 0.4438 + 0.0281 and Mean AUC = 0.7214 + 0.0138
Mean Sensitivity = 0.7220 + 0.0373 and Mean Specificity = 0.7208 + 0.0322 and Mean Accuracy = 0.7214 + 0.0138
Mean Precision = 0.7219 + 0.0175





Seed   : 648497
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6220 - accuracy: 0.6560 - val_loss: 0.5671 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5628 - accuracy: 0.7112 - val_loss: 0.5515 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7219 - val_loss: 0.5454 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7288 - val_loss: 0.5450 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7338 - val_loss: 0.5388 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7377 - val_loss: 0.5387 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7427 - val_loss: 0.5341 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7415 - val_loss: 0.5351 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7486 - val_loss: 0.5356 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4974 - accuracy: 0.7537 - val_loss: 0.5333 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7547 - val_loss: 0.5372 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4856 - accuracy: 0.7598 - val_loss: 0.5373 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7618 - val_loss: 0.5353 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4725 - accuracy: 0.7668 - val_loss: 0.5388 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4680 - accuracy: 0.7681 - val_loss: 0.5403 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4664 - accuracy: 0.7698 - val_loss: 0.5546 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4561 - accuracy: 0.7755 - val_loss: 0.5474 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4515 - accuracy: 0.7777 - val_loss: 0.5515 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4459 - accuracy: 0.7805 - val_loss: 0.5700 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4439 - accuracy: 0.7824 - val_loss: 0.5557 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4378 - accuracy: 0.7839 - val_loss: 0.5725 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 22/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4316 - accuracy: 0.7881 - val_loss: 0.5706 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 23/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4255 - accuracy: 0.7904 - val_loss: 0.5753 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 24/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4213 - accuracy: 0.7930
Epoch 24: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4218 - accuracy: 0.7927 - val_loss: 0.5756 - val_accuracy: 0.7147 - lr: 0.0010
271/271 [==============================] - 0s 638us/step
Independent Testing Matthews Correlation:  0.4188238776622401
Confusion Matrix :
 [[3121 1202]
 [1311 3012]]
Accuracy on test set:    0.7093453620171177
Sensitivity:    0.6967383761276891 	 Specificity:    0.7219523479065464
Precision  : 0.7147603227337447
Area Under Curve:    0.7093453620171177
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6298 - accuracy: 0.6465 - val_loss: 0.5679 - val_accuracy: 0.6996 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5658 - accuracy: 0.7076 - val_loss: 0.5529 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5484 - accuracy: 0.7213 - val_loss: 0.5444 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7276 - val_loss: 0.5444 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7336 - val_loss: 0.5422 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5234 - accuracy: 0.7367 - val_loss: 0.5352 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7412 - val_loss: 0.5398 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5110 - accuracy: 0.7443 - val_loss: 0.5345 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7469 - val_loss: 0.5381 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7505 - val_loss: 0.5430 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4960 - accuracy: 0.7537 - val_loss: 0.5378 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7592 - val_loss: 0.5398 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7606 - val_loss: 0.5422 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4756 - accuracy: 0.7682 - val_loss: 0.5417 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 15/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4706 - accuracy: 0.7681 - val_loss: 0.5444 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4674 - accuracy: 0.7708 - val_loss: 0.5504 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4625 - accuracy: 0.7750 - val_loss: 0.5479 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4556 - accuracy: 0.7763 - val_loss: 0.5550 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 19/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4530 - accuracy: 0.7796
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4527 - accuracy: 0.7800 - val_loss: 0.5695 - val_accuracy: 0.7150 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.40791757373379967
Confusion Matrix :
 [[2437 1886]
 [ 737 3586]]
Accuracy on test set:    0.6966227157066852
Sensitivity:    0.8295165394402035 	 Specificity:    0.5637288919731668
Precision  : 0.6553362573099415
Area Under Curve:    0.6966227157066851
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6030 - accuracy: 0.6693 - val_loss: 0.5617 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5574 - accuracy: 0.7134 - val_loss: 0.5498 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7235 - val_loss: 0.5435 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7296 - val_loss: 0.5535 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7317 - val_loss: 0.5425 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5190 - accuracy: 0.7377 - val_loss: 0.5409 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5111 - accuracy: 0.7424 - val_loss: 0.5418 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5078 - accuracy: 0.7451 - val_loss: 0.5475 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7488 - val_loss: 0.5416 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7514 - val_loss: 0.5418 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7549 - val_loss: 0.5489 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4859 - accuracy: 0.7575 - val_loss: 0.5449 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4781 - accuracy: 0.7617 - val_loss: 0.5494 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 14/400
263/274 [===========================>..] - ETA: 0s - loss: 0.4733 - accuracy: 0.7646
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4738 - accuracy: 0.7640 - val_loss: 0.5446 - val_accuracy: 0.7213 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.4519632118518431
Confusion Matrix :
 [[2984 1339]
 [1035 3288]]
Accuracy on test set:    0.7254221605366643
Sensitivity:    0.7605829285218598 	 Specificity:    0.6902613925514689
Precision  : 0.7106116274043657
Area Under Curve:    0.7254221605366643
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6053 - accuracy: 0.6668 - val_loss: 0.5607 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5573 - accuracy: 0.7124 - val_loss: 0.5554 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7240 - val_loss: 0.5405 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7320 - val_loss: 0.5372 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7386 - val_loss: 0.5408 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7409 - val_loss: 0.5381 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7446 - val_loss: 0.5486 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7496 - val_loss: 0.5372 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7521 - val_loss: 0.5455 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7567 - val_loss: 0.5403 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4867 - accuracy: 0.7589
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4866 - accuracy: 0.7591 - val_loss: 0.5354 - val_accuracy: 0.7269 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.444105696913085
Confusion Matrix :
 [[2922 1401]
 [1010 3313]]
Accuracy on test set:    0.7211427249595188
Sensitivity:    0.7663659495720564 	 Specificity:    0.6759195003469812
Precision  : 0.702800169707255
Area Under Curve:    0.7211427249595189
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6043 - accuracy: 0.6681 - val_loss: 0.5619 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5600 - accuracy: 0.7098 - val_loss: 0.5572 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7192 - val_loss: 0.5525 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5368 - accuracy: 0.7263 - val_loss: 0.5404 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5278 - accuracy: 0.7319 - val_loss: 0.5445 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5208 - accuracy: 0.7358 - val_loss: 0.5479 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7383 - val_loss: 0.5378 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7433 - val_loss: 0.5359 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5062 - accuracy: 0.7448 - val_loss: 0.5412 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4990 - accuracy: 0.7471 - val_loss: 0.5403 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7485 - val_loss: 0.5347 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7523 - val_loss: 0.5421 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4873 - accuracy: 0.7575 - val_loss: 0.5445 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4806 - accuracy: 0.7609 - val_loss: 0.5442 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4789 - accuracy: 0.7604 - val_loss: 0.5541 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4696 - accuracy: 0.7652 - val_loss: 0.5458 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7658 - val_loss: 0.5518 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4637 - accuracy: 0.7690
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4635 - accuracy: 0.7692 - val_loss: 0.5570 - val_accuracy: 0.7174 - lr: 0.0010
271/271 [==============================] - 0s 637us/step
Independent Testing Matthews Correlation:  0.45040717895564597
Confusion Matrix :
 [[3112 1211]
 [1165 3158]]
Accuracy on test set:    0.7251908396946565
Sensitivity:    0.7305112190608374 	 Specificity:    0.7198704603284756
Precision  : 0.7228198672465095
Area Under Curve:    0.7251908396946565
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6201 - accuracy: 0.6553 - val_loss: 0.5682 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5630 - accuracy: 0.7066 - val_loss: 0.5486 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7184 - val_loss: 0.5455 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7291 - val_loss: 0.5459 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5276 - accuracy: 0.7336 - val_loss: 0.5389 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7388 - val_loss: 0.5387 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7430 - val_loss: 0.5401 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7466 - val_loss: 0.5373 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7545 - val_loss: 0.5376 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7572 - val_loss: 0.5432 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4858 - accuracy: 0.7613 - val_loss: 0.5413 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7661 - val_loss: 0.5457 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 13/400
263/274 [===========================>..] - ETA: 0s - loss: 0.4687 - accuracy: 0.7697
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4698 - accuracy: 0.7691 - val_loss: 0.5439 - val_accuracy: 0.7228 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.44120312287478075
Confusion Matrix :
 [[2986 1337]
 [1082 3241]]
Accuracy on test set:    0.7202174415914874
Sensitivity:    0.7497108489474902 	 Specificity:    0.6907240342354846
Precision  : 0.7079510703363915
Area Under Curve:    0.7202174415914873
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6106 - accuracy: 0.6651 - val_loss: 0.5648 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7102 - val_loss: 0.5494 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7217 - val_loss: 0.5464 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7297 - val_loss: 0.5366 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5247 - accuracy: 0.7353 - val_loss: 0.5357 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7412 - val_loss: 0.5399 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5122 - accuracy: 0.7443 - val_loss: 0.5379 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5050 - accuracy: 0.7478 - val_loss: 0.5393 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4940 - accuracy: 0.7553
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7551 - val_loss: 0.5464 - val_accuracy: 0.7190 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.4415576311638451
Confusion Matrix :
 [[3386  937]
 [1493 2830]]
Accuracy on test set:    0.7189451769604441
Sensitivity:    0.6546379828822577 	 Specificity:    0.7832523710386305
Precision  : 0.7512609503583754
Area Under Curve:    0.7189451769604441
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6093 - accuracy: 0.6649 - val_loss: 0.5659 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5600 - accuracy: 0.7102 - val_loss: 0.5501 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7197 - val_loss: 0.5420 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7298 - val_loss: 0.5442 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5272 - accuracy: 0.7334 - val_loss: 0.5369 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5172 - accuracy: 0.7402 - val_loss: 0.5385 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7429 - val_loss: 0.5427 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7453 - val_loss: 0.5359 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7503 - val_loss: 0.5369 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4934 - accuracy: 0.7557
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4938 - accuracy: 0.7554 - val_loss: 0.5364 - val_accuracy: 0.7267 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.4570437457557594
Confusion Matrix :
 [[2981 1342]
 [1011 3312]]
Accuracy on test set:    0.7278510293777469
Sensitivity:    0.7661346287300486 	 Specificity:    0.6895674300254453
Precision  : 0.7116458960034379
Area Under Curve:    0.7278510293777469
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6063 - accuracy: 0.6674 - val_loss: 0.5615 - val_accuracy: 0.7143 - lr: 0.0010

Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7123 - val_loss: 0.5488 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7230 - val_loss: 0.5427 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7303 - val_loss: 0.5394 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7324 - val_loss: 0.5464 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7411 - val_loss: 0.5400 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5106 - accuracy: 0.7446 - val_loss: 0.5374 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7480 - val_loss: 0.5368 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7532 - val_loss: 0.5459 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7564 - val_loss: 0.5373 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7623 - val_loss: 0.5350 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7639 - val_loss: 0.5379 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 13/400
272/274 [============================>.] - ETA: 0s - loss: 0.4703 - accuracy: 0.7702
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7701 - val_loss: 0.5462 - val_accuracy: 0.7236 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.45856180623914833
Confusion Matrix :
 [[3046 1277]
 [1066 3257]]
Accuracy on test set:    0.7290076335877863
Sensitivity:    0.753411982419616 	 Specificity:    0.7046032847559565
Precision  : 0.7183502426113807
Area Under Curve:    0.7290076335877863
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6101 - accuracy: 0.6639 - val_loss: 0.5724 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5636 - accuracy: 0.7094 - val_loss: 0.5505 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5507 - accuracy: 0.7196 - val_loss: 0.5529 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7265 - val_loss: 0.5432 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7309 - val_loss: 0.5464 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7355 - val_loss: 0.5399 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7421 - val_loss: 0.5385 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5111 - accuracy: 0.7451 - val_loss: 0.5409 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7474 - val_loss: 0.5456 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7522 - val_loss: 0.5440 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7565 - val_loss: 0.5518 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 12/400
263/274 [===========================>..] - ETA: 0s - loss: 0.4853 - accuracy: 0.7596
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4851 - accuracy: 0.7594 - val_loss: 0.5516 - val_accuracy: 0.7241 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4845471763879722
Confusion Matrix :
 [[3121 1202]
 [1028 3295]]
Accuracy on test set:    0.7420772611612306
Sensitivity:    0.7622021744159149 	 Specificity:    0.7219523479065464
Precision  : 0.7327106960195686
Area Under Curve:    0.7420772611612306
(8646, 4352) (8646,)
Mean MCC = 0.4456 + 0.0201 and Mean AUC = 0.7216 + 0.0115
Mean Sensitivity = 0.7470 + 0.0440 and Mean Specificity = 0.6962 + 0.0525 and Mean Accuracy = 0.7216 + 0.0115
Mean Precision = 0.7128 + 0.0233





Seed   : 750990
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6013 - accuracy: 0.6726 - val_loss: 0.5583 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5558 - accuracy: 0.7118 - val_loss: 0.5401 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7247 - val_loss: 0.5414 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7324 - val_loss: 0.5394 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7389 - val_loss: 0.5493 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5137 - accuracy: 0.7419 - val_loss: 0.5303 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7473 - val_loss: 0.5281 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7510 - val_loss: 0.5272 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7563 - val_loss: 0.5355 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4842 - accuracy: 0.7598 - val_loss: 0.5301 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4797 - accuracy: 0.7617 - val_loss: 0.5316 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4719 - accuracy: 0.7674 - val_loss: 0.5329 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4627 - accuracy: 0.7725 - val_loss: 0.5388 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4592 - accuracy: 0.7752 - val_loss: 0.5362 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4515 - accuracy: 0.7787 - val_loss: 0.5488 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4454 - accuracy: 0.7824
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4457 - accuracy: 0.7824 - val_loss: 0.5413 - val_accuracy: 0.7265 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4071585490149132
Confusion Matrix :
 [[2963 1360]
 [1204 3119]]
Accuracy on test set:    0.7034466805459172
Sensitivity:    0.7214897062225306 	 Specificity:    0.6854036548693038
Precision  : 0.6963607948202724
Area Under Curve:    0.7034466805459171
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6014 - accuracy: 0.6735 - val_loss: 0.5645 - val_accuracy: 0.7077 - lr: 0.0010

Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5569 - accuracy: 0.7122 - val_loss: 0.5441 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7234 - val_loss: 0.5423 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7292 - val_loss: 0.5457 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7343 - val_loss: 0.5332 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7397 - val_loss: 0.5325 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7420 - val_loss: 0.5311 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5057 - accuracy: 0.7467 - val_loss: 0.5313 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7514 - val_loss: 0.5333 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7550 - val_loss: 0.5345 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7567 - val_loss: 0.5359 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7605 - val_loss: 0.5309 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4771 - accuracy: 0.7639 - val_loss: 0.5342 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 14/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4698 - accuracy: 0.7677
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4709 - accuracy: 0.7667 - val_loss: 0.5433 - val_accuracy: 0.7194 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.42193771096422256
Confusion Matrix :
 [[2744 1579]
 [ 940 3383]]
Accuracy on test set:    0.7086513994910941
Sensitivity:    0.7825584085126069 	 Specificity:    0.6347443904695813
Precision  : 0.6817815397017332
Area Under Curve:    0.7086513994910941
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6032 - accuracy: 0.6690 - val_loss: 0.5606 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5580 - accuracy: 0.7131 - val_loss: 0.5445 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7219 - val_loss: 0.5444 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7293 - val_loss: 0.5416 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7327 - val_loss: 0.5328 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5204 - accuracy: 0.7397 - val_loss: 0.5477 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5141 - accuracy: 0.7408 - val_loss: 0.5354 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7461 - val_loss: 0.5330 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7515 - val_loss: 0.5313 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7539 - val_loss: 0.5318 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7579 - val_loss: 0.5362 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4827 - accuracy: 0.7609 - val_loss: 0.5310 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7626 - val_loss: 0.5347 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4730 - accuracy: 0.7671 - val_loss: 0.5339 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4650 - accuracy: 0.7724 - val_loss: 0.5466 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4613 - accuracy: 0.7746 - val_loss: 0.5375 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 17/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4548 - accuracy: 0.7794
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4551 - accuracy: 0.7789 - val_loss: 0.5466 - val_accuracy: 0.7221 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4194638808147784
Confusion Matrix :
 [[3110 1213]
 [1297 3026]]
Accuracy on test set:    0.7096923432801295
Sensitivity:    0.6999768679157992 	 Specificity:    0.7194078186444599
Precision  : 0.7138476055673508
Area Under Curve:    0.7096923432801295
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6102 - accuracy: 0.6612 - val_loss: 0.5608 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5629 - accuracy: 0.7079 - val_loss: 0.5587 - val_accuracy: 0.7070 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5484 - accuracy: 0.7193 - val_loss: 0.5375 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7246 - val_loss: 0.5375 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5301 - accuracy: 0.7326 - val_loss: 0.5333 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5261 - accuracy: 0.7347 - val_loss: 0.5474 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7375 - val_loss: 0.5349 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5122 - accuracy: 0.7429 - val_loss: 0.5461 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7444 - val_loss: 0.5482 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7496 - val_loss: 0.5361 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7491 - val_loss: 0.5391 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4910 - accuracy: 0.7551 - val_loss: 0.5426 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4850 - accuracy: 0.7575
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7577 - val_loss: 0.5503 - val_accuracy: 0.7105 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.43445388907948684
Confusion Matrix :
 [[3520  803]
 [1681 2642]]
Accuracy on test set:    0.7126995142262318
Sensitivity:    0.611149664584779 	 Specificity:    0.8142493638676844
Precision  : 0.7669085631349782
Area Under Curve:    0.7126995142262317
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6079 - accuracy: 0.6657 - val_loss: 0.5579 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7113 - val_loss: 0.5411 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7223 - val_loss: 0.5437 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7285 - val_loss: 0.5423 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7354 - val_loss: 0.5388 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7391 - val_loss: 0.5336 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7436 - val_loss: 0.5305 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7485 - val_loss: 0.5288 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7533 - val_loss: 0.5343 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7572 - val_loss: 0.5325 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7579 - val_loss: 0.5291 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4776 - accuracy: 0.7649 - val_loss: 0.5328 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4737 - accuracy: 0.7695 - val_loss: 0.5340 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4685 - accuracy: 0.7708 - val_loss: 0.5409 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4607 - accuracy: 0.7747
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4610 - accuracy: 0.7741 - val_loss: 0.5423 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.42343322517726123
Confusion Matrix :
 [[2923 1400]
 [1097 3226]]
Accuracy on test set:    0.7111959287531806
Sensitivity:    0.7462410363173722 	 Specificity:    0.6761508211889892
Precision  : 0.6973627323821876
Area Under Curve:    0.7111959287531806
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6137 - accuracy: 0.6604 - val_loss: 0.5548 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5616 - accuracy: 0.7100 - val_loss: 0.5449 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7229 - val_loss: 0.5418 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7304 - val_loss: 0.5352 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5279 - accuracy: 0.7321 - val_loss: 0.5324 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5211 - accuracy: 0.7365 - val_loss: 0.5361 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7423 - val_loss: 0.5327 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7447 - val_loss: 0.5315 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5037 - accuracy: 0.7488 - val_loss: 0.5285 - val_accuracy: 0.7328 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4964 - accuracy: 0.7515 - val_loss: 0.5326 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4922 - accuracy: 0.7541 - val_loss: 0.5294 - val_accuracy: 0.7335 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4830 - accuracy: 0.7606 - val_loss: 0.5348 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4787 - accuracy: 0.7629 - val_loss: 0.5360 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4704 - accuracy: 0.7696 - val_loss: 0.5478 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4665 - accuracy: 0.7695 - val_loss: 0.5450 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4584 - accuracy: 0.7755
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4590 - accuracy: 0.7756 - val_loss: 0.5400 - val_accuracy: 0.7256 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.44017284699266995
Confusion Matrix :
 [[2956 1367]
 [1058 3265]]
Accuracy on test set:    0.7195234790654638
Sensitivity:    0.7552625491556789 	 Specificity:    0.6837844089752487
Precision  : 0.7048791018998273
Area Under Curve:    0.7195234790654638
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6056 - accuracy: 0.6662 - val_loss: 0.5644 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5624 - accuracy: 0.7097 - val_loss: 0.5497 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7207 - val_loss: 0.5530 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7281 - val_loss: 0.5383 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7324 - val_loss: 0.5417 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7362 - val_loss: 0.5392 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7425 - val_loss: 0.5368 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7470 - val_loss: 0.5407 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7501 - val_loss: 0.5363 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4990 - accuracy: 0.7499 - val_loss: 0.5394 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4956 - accuracy: 0.7530 - val_loss: 0.5400 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4910 - accuracy: 0.7557 - val_loss: 0.5372 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4826 - accuracy: 0.7626
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7620 - val_loss: 0.5445 - val_accuracy: 0.7240 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4687378813494425
Confusion Matrix :
 [[3253 1070]
 [1228 3095]]
Accuracy on test set:    0.7342123525329632
Sensitivity:    0.7159380060143419 	 Specificity:    0.7524866990515845
Precision  : 0.7430972388955582
Area Under Curve:    0.7342123525329632
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6176 - accuracy: 0.6559 - val_loss: 0.5725 - val_accuracy: 0.7005 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5651 - accuracy: 0.7074 - val_loss: 0.5450 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5482 - accuracy: 0.7213 - val_loss: 0.5437 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7283 - val_loss: 0.5395 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5272 - accuracy: 0.7326 - val_loss: 0.5379 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7386 - val_loss: 0.5345 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7422 - val_loss: 0.5322 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7447 - val_loss: 0.5331 - val_accuracy: 0.7327 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7503 - val_loss: 0.5346 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7540 - val_loss: 0.5390 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7581 - val_loss: 0.5361 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.7611 - val_loss: 0.5366 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4774 - accuracy: 0.7644
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7636 - val_loss: 0.5345 - val_accuracy: 0.7245 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.451689862847897
Confusion Matrix :
 [[2907 1416]
 [ 965 3358]]
Accuracy on test set:    0.7246125375896368
Sensitivity:    0.7767753874624104 	 Specificity:    0.6724496877168633
Precision  : 0.7033933808127356
Area Under Curve:    0.7246125375896368
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6080 - accuracy: 0.6647 - val_loss: 0.5648 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5629 - accuracy: 0.7106 - val_loss: 0.5519 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5491 - accuracy: 0.7183 - val_loss: 0.5424 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7241 - val_loss: 0.5393 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7306 - val_loss: 0.5374 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5252 - accuracy: 0.7349 - val_loss: 0.5403 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7402 - val_loss: 0.5419 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7424 - val_loss: 0.5380 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7472 - val_loss: 0.5374 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7502 - val_loss: 0.5383 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4966 - accuracy: 0.7520
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7524 - val_loss: 0.5387 - val_accuracy: 0.7273 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.47424782193553605
Confusion Matrix :
 [[3086 1237]
 [1038 3285]]
Accuracy on test set:    0.7368725422160537
Sensitivity:    0.7598889659958362 	 Specificity:    0.7138561184362711
Precision  : 0.7264484741264927
Area Under Curve:    0.7368725422160536
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6183 - accuracy: 0.6532 - val_loss: 0.5804 - val_accuracy: 0.6948 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5681 - accuracy: 0.7055 - val_loss: 0.5537 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5533 - accuracy: 0.7168 - val_loss: 0.5422 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7247 - val_loss: 0.5519 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7297 - val_loss: 0.5378 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5274 - accuracy: 0.7345 - val_loss: 0.5397 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5191 - accuracy: 0.7397 - val_loss: 0.5391 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7398 - val_loss: 0.5403 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7443 - val_loss: 0.5391 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7480 - val_loss: 0.5420 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7521 - val_loss: 0.5448 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7537 - val_loss: 0.5430 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7588 - val_loss: 0.5434 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4777 - accuracy: 0.7605
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4780 - accuracy: 0.7602 - val_loss: 0.5442 - val_accuracy: 0.7292 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4988196827425377
Confusion Matrix :
 [[3281 1042]
 [1125 3198]]
Accuracy on test set:    0.7493638676844784
Sensitivity:    0.739764052741152 	 Specificity:    0.7589636826278048
Precision  : 0.754245283018868
Area Under Curve:    0.7493638676844784
(8646, 4352) (8646,)
Mean MCC = 0.4440 + 0.0275 and Mean AUC = 0.7210 + 0.0141
Mean Sensitivity = 0.7309 + 0.0470 and Mean Specificity = 0.7111 + 0.0497 and Mean Accuracy = 0.7210 + 0.0141
Mean Precision = 0.7188 + 0.0265





Seed   : 325160
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5994 - accuracy: 0.6721 - val_loss: 0.5673 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5545 - accuracy: 0.7154 - val_loss: 0.5595 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7243 - val_loss: 0.5520 - val_accuracy: 0.7187 - lr: 0.0010

Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5297 - accuracy: 0.7333 - val_loss: 0.5449 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7344 - val_loss: 0.5411 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7410 - val_loss: 0.5457 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7473 - val_loss: 0.5511 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7501 - val_loss: 0.5427 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4950 - accuracy: 0.7561 - val_loss: 0.5473 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4902 - accuracy: 0.7580 - val_loss: 0.5420 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4836 - accuracy: 0.7621 - val_loss: 0.5464 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7646 - val_loss: 0.5494 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4709 - accuracy: 0.7690 - val_loss: 0.5631 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7696 - val_loss: 0.5471 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4612 - accuracy: 0.7737 - val_loss: 0.5556 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4552 - accuracy: 0.7796
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4549 - accuracy: 0.7801 - val_loss: 0.5634 - val_accuracy: 0.7195 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4231141216714028
Confusion Matrix :
 [[3051 1272]
 [1222 3101]]
Accuracy on test set:    0.7115429100161924
Sensitivity:    0.7173259310663891 	 Specificity:    0.7057598889659958
Precision  : 0.7091241710496227
Area Under Curve:    0.7115429100161925
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6096 - accuracy: 0.6653 - val_loss: 0.5716 - val_accuracy: 0.6984 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5558 - accuracy: 0.7132 - val_loss: 0.5620 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7253 - val_loss: 0.5600 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7336 - val_loss: 0.5469 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5218 - accuracy: 0.7375 - val_loss: 0.5459 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7411 - val_loss: 0.5498 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7443 - val_loss: 0.5420 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5006 - accuracy: 0.7507 - val_loss: 0.5448 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4960 - accuracy: 0.7553 - val_loss: 0.5503 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4893 - accuracy: 0.7578 - val_loss: 0.5508 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4810 - accuracy: 0.7631 - val_loss: 0.5507 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4766 - accuracy: 0.7657 - val_loss: 0.5506 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4689 - accuracy: 0.7686
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4695 - accuracy: 0.7680 - val_loss: 0.5537 - val_accuracy: 0.7147 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.42563219982097816
Confusion Matrix :
 [[2789 1534]
 [ 965 3358]]
Accuracy on test set:    0.7109646079111728
Sensitivity:    0.7767753874624104 	 Specificity:    0.6451538283599352
Precision  : 0.6864268192968112
Area Under Curve:    0.7109646079111728
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6042 - accuracy: 0.6658 - val_loss: 0.5684 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7137 - val_loss: 0.5528 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7243 - val_loss: 0.5495 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7302 - val_loss: 0.5446 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.7348 - val_loss: 0.5476 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7386 - val_loss: 0.5474 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7442 - val_loss: 0.5506 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7480 - val_loss: 0.5449 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7528 - val_loss: 0.5421 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4899 - accuracy: 0.7558 - val_loss: 0.5467 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4830 - accuracy: 0.7611 - val_loss: 0.5484 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4746 - accuracy: 0.7672 - val_loss: 0.5536 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4700 - accuracy: 0.7698 - val_loss: 0.5546 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 14/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4630 - accuracy: 0.7728
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4630 - accuracy: 0.7725 - val_loss: 0.5529 - val_accuracy: 0.7188 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4246717618868918
Confusion Matrix :
 [[3013 1310]
 [1178 3145]]
Accuracy on test set:    0.712236872542216
Sensitivity:    0.7275040481147351 	 Specificity:    0.696969696969697
Precision  : 0.7059483726150393
Area Under Curve:    0.712236872542216
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6095 - accuracy: 0.6636 - val_loss: 0.5686 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7119 - val_loss: 0.5526 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7215 - val_loss: 0.5525 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7291 - val_loss: 0.5469 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7351 - val_loss: 0.5439 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5187 - accuracy: 0.7372 - val_loss: 0.5431 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7431 - val_loss: 0.5470 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7460 - val_loss: 0.5413 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7488 - val_loss: 0.5449 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 10/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4957 - accuracy: 0.7511
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4961 - accuracy: 0.7511 - val_loss: 0.5510 - val_accuracy: 0.7254 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.4312850678158421
Confusion Matrix :
 [[2884 1439]
 [1028 3295]]
Accuracy on test set:    0.7146657413832986
Sensitivity:    0.7622021744159149 	 Specificity:    0.6671293083506824
Precision  : 0.69602872834812
Area Under Curve:    0.7146657413832986
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6154 - accuracy: 0.6610 - val_loss: 0.5640 - val_accuracy: 0.7015 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5636 - accuracy: 0.7070 - val_loss: 0.5534 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7193 - val_loss: 0.5537 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7258 - val_loss: 0.5452 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7309 - val_loss: 0.5430 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5249 - accuracy: 0.7359 - val_loss: 0.5517 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7388 - val_loss: 0.5560 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5136 - accuracy: 0.7428 - val_loss: 0.5420 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7420 - val_loss: 0.5400 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7480 - val_loss: 0.5445 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7517 - val_loss: 0.5403 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7556 - val_loss: 0.5471 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4873 - accuracy: 0.7591
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7597 - val_loss: 0.5520 - val_accuracy: 0.7096 - lr: 0.0010
271/271 [==============================] - 0s 637us/step
Independent Testing Matthews Correlation:  0.4352606063804724
Confusion Matrix :
 [[3046 1277]
 [1165 3158]]
Accuracy on test set:    0.7175572519083969
Sensitivity:    0.7305112190608374 	 Specificity:    0.7046032847559565
Precision  : 0.7120631341600901
Area Under Curve:    0.7175572519083969
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6058 - accuracy: 0.6635 - val_loss: 0.5657 - val_accuracy: 0.7028 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7115 - val_loss: 0.5518 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7230 - val_loss: 0.5558 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7289 - val_loss: 0.5420 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5268 - accuracy: 0.7349 - val_loss: 0.5470 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7393 - val_loss: 0.5421 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7420 - val_loss: 0.5410 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7469 - val_loss: 0.5413 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5006 - accuracy: 0.7508 - val_loss: 0.5425 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7529 - val_loss: 0.5424 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7555 - val_loss: 0.5514 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7594 - val_loss: 0.5470 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4777 - accuracy: 0.7643 - val_loss: 0.5601 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7655 - val_loss: 0.5517 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4669 - accuracy: 0.7707 - val_loss: 0.5644 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4592 - accuracy: 0.7751 - val_loss: 0.5647 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4585 - accuracy: 0.7750 - val_loss: 0.5643 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4502 - accuracy: 0.7778 - val_loss: 0.5707 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 19/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4467 - accuracy: 0.7832
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4474 - accuracy: 0.7828 - val_loss: 0.5747 - val_accuracy: 0.7115 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4277575260620486
Confusion Matrix :
 [[3273 1050]
 [1431 2892]]
Accuracy on test set:    0.7130464954892436
Sensitivity:    0.6689798750867453 	 Specificity:    0.7571131158917418
Precision  : 0.7336377473363774
Area Under Curve:    0.7130464954892436
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6094 - accuracy: 0.6654 - val_loss: 0.5645 - val_accuracy: 0.7021 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7117 - val_loss: 0.5505 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7240 - val_loss: 0.5508 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7309 - val_loss: 0.5504 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7360 - val_loss: 0.5488 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7423 - val_loss: 0.5434 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5127 - accuracy: 0.7439 - val_loss: 0.5438 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7477 - val_loss: 0.5434 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4983 - accuracy: 0.7537 - val_loss: 0.5452 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7538 - val_loss: 0.5478 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7586 - val_loss: 0.5444 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4810 - accuracy: 0.7622 - val_loss: 0.5514 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 13/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4741 - accuracy: 0.7662
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4744 - accuracy: 0.7662 - val_loss: 0.5494 - val_accuracy: 0.7170 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4550860042894199
Confusion Matrix :
 [[3328  995]
 [1368 2955]]
Accuracy on test set:    0.7266944251677077
Sensitivity:    0.6835530881332408 	 Specificity:    0.7698357622021744
Precision  : 0.7481012658227848
Area Under Curve:    0.7266944251677077
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6077 - accuracy: 0.6661 - val_loss: 0.5665 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5586 - accuracy: 0.7118 - val_loss: 0.5507 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7226 - val_loss: 0.5458 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7318 - val_loss: 0.5518 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7362 - val_loss: 0.5476 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7435 - val_loss: 0.5445 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7462 - val_loss: 0.5428 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7534 - val_loss: 0.5442 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7525 - val_loss: 0.5377 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7585 - val_loss: 0.5440 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7638 - val_loss: 0.5483 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7649 - val_loss: 0.5453 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4728 - accuracy: 0.7706 - val_loss: 0.5472 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4641 - accuracy: 0.7750
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4646 - accuracy: 0.7747 - val_loss: 0.5443 - val_accuracy: 0.7186 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.44217366340557657
Confusion Matrix :
 [[2922 1401]
 [1018 3305]]
Accuracy on test set:    0.7202174415914874
Sensitivity:    0.7645153828359935 	 Specificity:    0.6759195003469812
Precision  : 0.7022949426264343
Area Under Curve:    0.7202174415914875
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6041 - accuracy: 0.6704 - val_loss: 0.5643 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5590 - accuracy: 0.7117 - val_loss: 0.5505 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7241 - val_loss: 0.5521 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7292 - val_loss: 0.5411 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5261 - accuracy: 0.7348 - val_loss: 0.5496 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7395 - val_loss: 0.5450 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7440 - val_loss: 0.5377 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5057 - accuracy: 0.7475 - val_loss: 0.5423 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7526 - val_loss: 0.5509 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7550 - val_loss: 0.5564 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4875 - accuracy: 0.7585 - val_loss: 0.5457 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4799 - accuracy: 0.7631 - val_loss: 0.5505 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4745 - accuracy: 0.7644 - val_loss: 0.5434 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4655 - accuracy: 0.7720 - val_loss: 0.5535 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4608 - accuracy: 0.7728 - val_loss: 0.5524 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4534 - accuracy: 0.7790
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4543 - accuracy: 0.7783 - val_loss: 0.5514 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.47085891708599664
Confusion Matrix :
 [[3228 1095]
 [1193 3130]]
Accuracy on test set:    0.7353689567430025
Sensitivity:    0.7240342354846172 	 Specificity:    0.7467036780013879
Precision  : 0.7408284023668639
Area Under Curve:    0.7353689567430025
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6032 - accuracy: 0.6713 - val_loss: 0.5729 - val_accuracy: 0.6978 - lr: 0.0010
Epoch 2/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7108 - val_loss: 0.5586 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5480 - accuracy: 0.7192 - val_loss: 0.5566 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7269 - val_loss: 0.5487 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7312 - val_loss: 0.5484 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7349 - val_loss: 0.5446 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5177 - accuracy: 0.7397 - val_loss: 0.5461 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7457 - val_loss: 0.5474 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5057 - accuracy: 0.7482 - val_loss: 0.5478 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4990 - accuracy: 0.7511 - val_loss: 0.5509 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4936 - accuracy: 0.7555 - val_loss: 0.5558 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4918 - accuracy: 0.7545 - val_loss: 0.5480 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4848 - accuracy: 0.7596
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4851 - accuracy: 0.7596 - val_loss: 0.5569 - val_accuracy: 0.7237 - lr: 0.0010
271/271 [==============================] - 1s 670us/step
Independent Testing Matthews Correlation:  0.4956192231272837
Confusion Matrix :
 [[3183 1140]
 [1041 3282]]
Accuracy on test set:    0.7477446217904233
Sensitivity:    0.7591950034698126 	 Specificity:    0.7362942401110341
Precision  : 0.7421981004070556
Area Under Curve:    0.7477446217904232
(8646, 4352) (8646,)
Mean MCC = 0.4431 + 0.0227 and Mean AUC = 0.7210 + 0.0116
Mean Sensitivity = 0.7315 + 0.0337 and Mean Specificity = 0.7105 + 0.0391 and Mean Accuracy = 0.7210 + 0.0116
Mean Precision = 0.7177 + 0.0206





Seed   : 664734
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6162 - accuracy: 0.6580 - val_loss: 0.5718 - val_accuracy: 0.7011 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5627 - accuracy: 0.7096 - val_loss: 0.5689 - val_accuracy: 0.6976 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7200 - val_loss: 0.5513 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7293 - val_loss: 0.5481 - val_accuracy: 0.7107 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7340 - val_loss: 0.5433 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5211 - accuracy: 0.7362 - val_loss: 0.5453 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5136 - accuracy: 0.7437 - val_loss: 0.5442 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7442 - val_loss: 0.5396 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7486 - val_loss: 0.5419 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7514 - val_loss: 0.5439 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7561 - val_loss: 0.5459 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4857 - accuracy: 0.7600 - val_loss: 0.5436 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4796 - accuracy: 0.7626 - val_loss: 0.5473 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4797 - accuracy: 0.7618 - val_loss: 0.5507 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4724 - accuracy: 0.7684 - val_loss: 0.5527 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4682 - accuracy: 0.7687 - val_loss: 0.5543 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4612 - accuracy: 0.7744 - val_loss: 0.5647 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4578 - accuracy: 0.7756 - val_loss: 0.5607 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4540 - accuracy: 0.7757 - val_loss: 0.5557 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4486 - accuracy: 0.7806 - val_loss: 0.5629 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4440 - accuracy: 0.7836 - val_loss: 0.5632 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 22/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4359 - accuracy: 0.7868
Epoch 22: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4366 - accuracy: 0.7866 - val_loss: 0.5721 - val_accuracy: 0.7098 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.3956260208005513
Confusion Matrix :
 [[2787 1536]
 [1086 3237]]
Accuracy on test set:    0.6967383761276891
Sensitivity:    0.7487855655794587 	 Specificity:    0.6446911866759195
Precision  : 0.6781898177247014
Area Under Curve:    0.6967383761276891
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6120 - accuracy: 0.6613 - val_loss: 0.5744 - val_accuracy: 0.7019 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7087 - val_loss: 0.5666 - val_accuracy: 0.7016 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7210 - val_loss: 0.5532 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7292 - val_loss: 0.5518 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7368 - val_loss: 0.5501 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7406 - val_loss: 0.5518 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7439 - val_loss: 0.5487 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7478 - val_loss: 0.5479 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7559 - val_loss: 0.5483 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4890 - accuracy: 0.7575 - val_loss: 0.5493 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7629 - val_loss: 0.5478 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4752 - accuracy: 0.7651 - val_loss: 0.5567 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 13/400
256/274 [===========================>..] - ETA: 0s - loss: 0.4688 - accuracy: 0.7713
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4695 - accuracy: 0.7702 - val_loss: 0.5599 - val_accuracy: 0.7170 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4323453165026473
Confusion Matrix :
 [[3108 1215]
 [1239 3084]]
Accuracy on test set:    0.7161693268563497
Sensitivity:    0.7133934767522554 	 Specificity:    0.7189451769604441
Precision  : 0.7173761339846476
Area Under Curve:    0.7161693268563498
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6089 - accuracy: 0.6655 - val_loss: 0.5704 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7136 - val_loss: 0.5585 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7212 - val_loss: 0.5502 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7310 - val_loss: 0.5450 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7376 - val_loss: 0.5429 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7416 - val_loss: 0.5483 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7447 - val_loss: 0.5411 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7484 - val_loss: 0.5436 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7533 - val_loss: 0.5492 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7562 - val_loss: 0.5506 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7578 - val_loss: 0.5445 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7632 - val_loss: 0.5468 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4713 - accuracy: 0.7683 - val_loss: 0.5532 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4654 - accuracy: 0.7727
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4661 - accuracy: 0.7717 - val_loss: 0.5566 - val_accuracy: 0.7167 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.43345589188104033
Confusion Matrix :
 [[3002 1321]
 [1130 3193]]
Accuracy on test set:    0.7165163081193615
Sensitivity:    0.7386074485311126 	 Specificity:    0.6944251677076104
Precision  : 0.7073548958794861
Area Under Curve:    0.7165163081193616
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5982 - accuracy: 0.6728 - val_loss: 0.5727 - val_accuracy: 0.6969 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5563 - accuracy: 0.7135 - val_loss: 0.5545 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7265 - val_loss: 0.5470 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7334 - val_loss: 0.5486 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5196 - accuracy: 0.7404 - val_loss: 0.5439 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5116 - accuracy: 0.7448 - val_loss: 0.5408 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7471 - val_loss: 0.5504 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7527 - val_loss: 0.5418 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7577 - val_loss: 0.5449 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7619 - val_loss: 0.5503 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4766 - accuracy: 0.7653 - val_loss: 0.5501 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4680 - accuracy: 0.7705 - val_loss: 0.5550 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4640 - accuracy: 0.7735 - val_loss: 0.5678 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4555 - accuracy: 0.7780 - val_loss: 0.5627 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4504 - accuracy: 0.7801 - val_loss: 0.5656 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4415 - accuracy: 0.7844 - val_loss: 0.5757 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4331 - accuracy: 0.7901 - val_loss: 0.5675 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4287 - accuracy: 0.7927 - val_loss: 0.5760 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 19/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4222 - accuracy: 0.7957
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4227 - accuracy: 0.7951 - val_loss: 0.5872 - val_accuracy: 0.7138 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.42239493997680105
Confusion Matrix :
 [[3146 1177]
 [1321 3002]]
Accuracy on test set:    0.7110802683321767
Sensitivity:    0.6944251677076104 	 Specificity:    0.727735368956743
Precision  : 0.7183536731275425
Area Under Curve:    0.7110802683321766
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6043 - accuracy: 0.6697 - val_loss: 0.5573 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5568 - accuracy: 0.7128 - val_loss: 0.5496 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7231 - val_loss: 0.5475 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7301 - val_loss: 0.5433 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7371 - val_loss: 0.5440 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7414 - val_loss: 0.5422 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7469 - val_loss: 0.5498 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7489 - val_loss: 0.5421 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4983 - accuracy: 0.7523 - val_loss: 0.5420 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7575 - val_loss: 0.5402 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7576 - val_loss: 0.5491 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4812 - accuracy: 0.7615 - val_loss: 0.5434 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4760 - accuracy: 0.7671 - val_loss: 0.5436 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4683 - accuracy: 0.7695 - val_loss: 0.5499 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4622 - accuracy: 0.7729 - val_loss: 0.5535 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4569 - accuracy: 0.7757 - val_loss: 0.5666 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4534 - accuracy: 0.7760
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4539 - accuracy: 0.7754 - val_loss: 0.5547 - val_accuracy: 0.7235 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.4346102017501694
Confusion Matrix :
 [[2928 1395]
 [1055 3268]]
Accuracy on test set:    0.7166319685403655
Sensitivity:    0.7559565116817025 	 Specificity:    0.6773074253990284
Precision  : 0.7008363714346987
Area Under Curve:    0.7166319685403655
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6073 - accuracy: 0.6678 - val_loss: 0.5677 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7096 - val_loss: 0.5570 - val_accuracy: 0.7077 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7250 - val_loss: 0.5443 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7306 - val_loss: 0.5428 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7374 - val_loss: 0.5413 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7434 - val_loss: 0.5487 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7454 - val_loss: 0.5382 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5022 - accuracy: 0.7512 - val_loss: 0.5418 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7548 - val_loss: 0.5454 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4885 - accuracy: 0.7605
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7603 - val_loss: 0.5437 - val_accuracy: 0.7194 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.43730556150833705
Confusion Matrix :
 [[2995 1328]
 [1107 3216]]
Accuracy on test set:    0.7183668748554245
Sensitivity:    0.7439278278972935 	 Specificity:    0.6928059218135554
Precision  : 0.7077464788732394
Area Under Curve:    0.7183668748554244
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6108 - accuracy: 0.6637 - val_loss: 0.5711 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5605 - accuracy: 0.7097 - val_loss: 0.5585 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7221 - val_loss: 0.5476 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7288 - val_loss: 0.5539 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5281 - accuracy: 0.7337 - val_loss: 0.5532 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7373 - val_loss: 0.5442 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5141 - accuracy: 0.7407 - val_loss: 0.5431 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5063 - accuracy: 0.7472 - val_loss: 0.5476 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7480 - val_loss: 0.5406 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7529 - val_loss: 0.5507 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7566 - val_loss: 0.5439 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4841 - accuracy: 0.7618 - val_loss: 0.5506 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4794 - accuracy: 0.7637 - val_loss: 0.5498 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4730 - accuracy: 0.7671 - val_loss: 0.5475 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4667 - accuracy: 0.7701 - val_loss: 0.5546 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4619 - accuracy: 0.7726 - val_loss: 0.5563 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4551 - accuracy: 0.7768 - val_loss: 0.5566 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4501 - accuracy: 0.7794 - val_loss: 0.5657 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 19/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4427 - accuracy: 0.7836
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4428 - accuracy: 0.7835 - val_loss: 0.5662 - val_accuracy: 0.7194 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.4580700740340258
Confusion Matrix :
 [[2927 1396]
 [ 957 3366]]
Accuracy on test set:    0.7278510293777469
Sensitivity:    0.7786259541984732 	 Specificity:    0.6770761045570206
Precision  : 0.7068458630827383
Area Under Curve:    0.7278510293777469
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6045 - accuracy: 0.6687 - val_loss: 0.5639 - val_accuracy: 0.7033 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7123 - val_loss: 0.5598 - val_accuracy: 0.7003 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7209 - val_loss: 0.5480 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7320 - val_loss: 0.5476 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7361 - val_loss: 0.5410 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5195 - accuracy: 0.7374 - val_loss: 0.5392 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5106 - accuracy: 0.7448 - val_loss: 0.5396 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7489 - val_loss: 0.5410 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4959 - accuracy: 0.7546 - val_loss: 0.5444 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4932 - accuracy: 0.7550 - val_loss: 0.5516 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7580 - val_loss: 0.5409 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4787 - accuracy: 0.7654 - val_loss: 0.5438 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4730 - accuracy: 0.7670 - val_loss: 0.5466 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4675 - accuracy: 0.7700 - val_loss: 0.5460 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4589 - accuracy: 0.7755 - val_loss: 0.5558 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4530 - accuracy: 0.7772 - val_loss: 0.5589 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4515 - accuracy: 0.7781 - val_loss: 0.5573 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4398 - accuracy: 0.7862 - val_loss: 0.5597 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 19/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4393 - accuracy: 0.7836
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4395 - accuracy: 0.7836 - val_loss: 0.5660 - val_accuracy: 0.7208 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.446536769351705
Confusion Matrix :
 [[2979 1344]
 [1053 3270]]
Accuracy on test set:    0.7227619708535739
Sensitivity:    0.7564191533657183 	 Specificity:    0.6891047883414295
Precision  : 0.7087126137841352
Area Under Curve:    0.722761970853574
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6072 - accuracy: 0.6665 - val_loss: 0.5629 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5589 - accuracy: 0.7105 - val_loss: 0.5526 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7207 - val_loss: 0.5476 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7309 - val_loss: 0.5504 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7340 - val_loss: 0.5491 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7399 - val_loss: 0.5397 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5141 - accuracy: 0.7409 - val_loss: 0.5404 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7479 - val_loss: 0.5419 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7519 - val_loss: 0.5515 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7542 - val_loss: 0.5412 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7610 - val_loss: 0.5475 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4816 - accuracy: 0.7627 - val_loss: 0.5483 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4744 - accuracy: 0.7661 - val_loss: 0.5494 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4683 - accuracy: 0.7689 - val_loss: 0.5556 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4620 - accuracy: 0.7731 - val_loss: 0.5512 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4569 - accuracy: 0.7754 - val_loss: 0.5589 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4533 - accuracy: 0.7784 - val_loss: 0.5661 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4455 - accuracy: 0.7807
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4449 - accuracy: 0.7813 - val_loss: 0.5848 - val_accuracy: 0.7212 - lr: 0.0010
271/271 [==============================] - 0s 637us/step
Independent Testing Matthews Correlation:  0.46305143776279506
Confusion Matrix :
 [[3222 1101]
 [1221 3102]]
Accuracy on test set:    0.7314365024288688
Sensitivity:    0.7175572519083969 	 Specificity:    0.7453157529493407
Precision  : 0.7380442541042113
Area Under Curve:    0.7314365024288689
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6263 - accuracy: 0.6485 - val_loss: 0.5765 - val_accuracy: 0.6980 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5687 - accuracy: 0.7067 - val_loss: 0.5683 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5524 - accuracy: 0.7179 - val_loss: 0.5482 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7239 - val_loss: 0.5503 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7302 - val_loss: 0.5481 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5276 - accuracy: 0.7350 - val_loss: 0.5448 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5219 - accuracy: 0.7397 - val_loss: 0.5442 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7441 - val_loss: 0.5434 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7492 - val_loss: 0.5428 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7498 - val_loss: 0.5501 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 11/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7530 - val_loss: 0.5474 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7552 - val_loss: 0.5433 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4847 - accuracy: 0.7615 - val_loss: 0.5485 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4787 - accuracy: 0.7646 - val_loss: 0.5512 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7689 - val_loss: 0.5568 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7724 - val_loss: 0.5575 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4619 - accuracy: 0.7729
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4619 - accuracy: 0.7734 - val_loss: 0.5644 - val_accuracy: 0.7186 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.5047831508765813
Confusion Matrix :
 [[3181 1142]
 [1000 3323]]
Accuracy on test set:    0.7522553782095767
Sensitivity:    0.768679157992135 	 Specificity:    0.7358315984270183
Precision  : 0.7442329227323629
Area Under Curve:    0.7522553782095767
(8646, 4352) (8646,)
Mean MCC = 0.4428 + 0.0273 and Mean AUC = 0.7210 + 0.0138
Mean Sensitivity = 0.7416 + 0.0249 and Mean Specificity = 0.7003 + 0.0296 and Mean Accuracy = 0.7210 + 0.0138
Mean Precision = 0.7128 + 0.0177





Seed   : 335132
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6156 - accuracy: 0.6611 - val_loss: 0.5618 - val_accuracy: 0.7052 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5624 - accuracy: 0.7077 - val_loss: 0.5605 - val_accuracy: 0.7008 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7232 - val_loss: 0.5431 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7281 - val_loss: 0.5401 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7360 - val_loss: 0.5361 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7417 - val_loss: 0.5401 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7457 - val_loss: 0.5352 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7503 - val_loss: 0.5367 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7556 - val_loss: 0.5356 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4865 - accuracy: 0.7568 - val_loss: 0.5373 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4821 - accuracy: 0.7614 - val_loss: 0.5448 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4728 - accuracy: 0.7668 - val_loss: 0.5491 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4664 - accuracy: 0.7704
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4668 - accuracy: 0.7704 - val_loss: 0.5491 - val_accuracy: 0.7206 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4146980642496794
Confusion Matrix :
 [[2490 1833]
 [ 754 3569]]
Accuracy on test set:    0.7007864908628267
Sensitivity:    0.8255840851260698 	 Specificity:    0.5759888965995836
Precision  : 0.6606812291743799
Area Under Curve:    0.7007864908628267
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6045 - accuracy: 0.6679 - val_loss: 0.5685 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7125 - val_loss: 0.5445 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7240 - val_loss: 0.5413 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7319 - val_loss: 0.5366 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5218 - accuracy: 0.7369 - val_loss: 0.5361 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5146 - accuracy: 0.7424 - val_loss: 0.5316 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7487 - val_loss: 0.5416 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7510 - val_loss: 0.5401 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7563 - val_loss: 0.5345 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4860 - accuracy: 0.7601 - val_loss: 0.5336 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4790 - accuracy: 0.7627
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7633 - val_loss: 0.5417 - val_accuracy: 0.7237 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.43711079227626176
Confusion Matrix :
 [[3219 1104]
 [1332 2991]]
Accuracy on test set:    0.7182512144344205
Sensitivity:    0.6918806384455239 	 Specificity:    0.7446217904233171
Precision  : 0.7304029304029304
Area Under Curve:    0.7182512144344205
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6093 - accuracy: 0.6637 - val_loss: 0.5604 - val_accuracy: 0.7092 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7127 - val_loss: 0.5533 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7206 - val_loss: 0.5380 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7314 - val_loss: 0.5361 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5274 - accuracy: 0.7322 - val_loss: 0.5400 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5205 - accuracy: 0.7373 - val_loss: 0.5336 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5120 - accuracy: 0.7429 - val_loss: 0.5343 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7450 - val_loss: 0.5365 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5009 - accuracy: 0.7493
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7492 - val_loss: 0.5360 - val_accuracy: 0.7265 - lr: 0.0010

271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.44038166389632066
Confusion Matrix :
 [[2761 1562]
 [ 881 3442]]
Accuracy on test set:    0.7174415914873931
Sensitivity:    0.796206338191071 	 Specificity:    0.638676844783715
Precision  : 0.687849720223821
Area Under Curve:    0.717441591487393
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.5979 - accuracy: 0.6750 - val_loss: 0.5622 - val_accuracy: 0.7107 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5537 - accuracy: 0.7171 - val_loss: 0.5480 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7262 - val_loss: 0.5412 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5290 - accuracy: 0.7335 - val_loss: 0.5436 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5223 - accuracy: 0.7364 - val_loss: 0.5369 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7424 - val_loss: 0.5357 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7464 - val_loss: 0.5387 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5032 - accuracy: 0.7483 - val_loss: 0.5451 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7541 - val_loss: 0.5557 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4904 - accuracy: 0.7576
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7577 - val_loss: 0.5386 - val_accuracy: 0.7247 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4413814176846738
Confusion Matrix :
 [[3237 1086]
 [1332 2991]]
Accuracy on test set:    0.7203331020124913
Sensitivity:    0.6918806384455239 	 Specificity:    0.7487855655794587
Precision  : 0.7336276674025018
Area Under Curve:    0.7203331020124912
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6105 - accuracy: 0.6666 - val_loss: 0.5686 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5599 - accuracy: 0.7113 - val_loss: 0.5446 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7217 - val_loss: 0.5489 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7298 - val_loss: 0.5366 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7338 - val_loss: 0.5345 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5172 - accuracy: 0.7406 - val_loss: 0.5364 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7435 - val_loss: 0.5339 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5009 - accuracy: 0.7505 - val_loss: 0.5332 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7522 - val_loss: 0.5374 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7572 - val_loss: 0.5331 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4822 - accuracy: 0.7606 - val_loss: 0.5385 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4774 - accuracy: 0.7636
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4780 - accuracy: 0.7634 - val_loss: 0.5404 - val_accuracy: 0.7236 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.44205796107827977
Confusion Matrix :
 [[3108 1215]
 [1197 3126]]
Accuracy on test set:    0.721027064538515
Sensitivity:    0.7231089521165857 	 Specificity:    0.7189451769604441
Precision  : 0.7201105736005529
Area Under Curve:    0.721027064538515
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6043 - accuracy: 0.6715 - val_loss: 0.5578 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7127 - val_loss: 0.5498 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7235 - val_loss: 0.5355 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7304 - val_loss: 0.5408 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5262 - accuracy: 0.7357 - val_loss: 0.5382 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7399 - val_loss: 0.5311 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7467 - val_loss: 0.5327 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7503 - val_loss: 0.5342 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4942 - accuracy: 0.7558 - val_loss: 0.5323 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7593 - val_loss: 0.5372 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4809 - accuracy: 0.7639 - val_loss: 0.5322 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4776 - accuracy: 0.7644 - val_loss: 0.5354 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4730 - accuracy: 0.7690 - val_loss: 0.5423 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4648 - accuracy: 0.7728 - val_loss: 0.5469 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4586 - accuracy: 0.7751 - val_loss: 0.5533 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4500 - accuracy: 0.7818
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4499 - accuracy: 0.7820 - val_loss: 0.5491 - val_accuracy: 0.7233 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.445484767343324
Confusion Matrix :
 [[2969 1354]
 [1048 3275]]
Accuracy on test set:    0.7221836687485542
Sensitivity:    0.7575757575757576 	 Specificity:    0.6867915799213509
Precision  : 0.7074962194858501
Area Under Curve:    0.7221836687485542
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6101 - accuracy: 0.6633 - val_loss: 0.5603 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5612 - accuracy: 0.7108 - val_loss: 0.5468 - val_accuracy: 0.7168 - lr: 0.0010

Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7213 - val_loss: 0.5383 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7294 - val_loss: 0.5431 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5294 - accuracy: 0.7321 - val_loss: 0.5325 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5211 - accuracy: 0.7390 - val_loss: 0.5378 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5157 - accuracy: 0.7394 - val_loss: 0.5361 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7451 - val_loss: 0.5302 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5062 - accuracy: 0.7460 - val_loss: 0.5362 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7517 - val_loss: 0.5309 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4951 - accuracy: 0.7537 - val_loss: 0.5313 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7557 - val_loss: 0.5308 - val_accuracy: 0.7341 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7592 - val_loss: 0.5351 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4810 - accuracy: 0.7607 - val_loss: 0.5420 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4725 - accuracy: 0.7653 - val_loss: 0.5402 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4702 - accuracy: 0.7686 - val_loss: 0.5460 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4625 - accuracy: 0.7708
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4628 - accuracy: 0.7705 - val_loss: 0.5459 - val_accuracy: 0.7233 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4300925004088532
Confusion Matrix :
 [[3010 1313]
 [1152 3171]]
Accuracy on test set:    0.7148970622253065
Sensitivity:    0.7335183900069396 	 Specificity:    0.6962757344436734
Precision  : 0.7071810883140054
Area Under Curve:    0.7148970622253066
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6014 - accuracy: 0.6725 - val_loss: 0.5623 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5590 - accuracy: 0.7108 - val_loss: 0.5470 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7229 - val_loss: 0.5409 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7270 - val_loss: 0.5384 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5281 - accuracy: 0.7341 - val_loss: 0.5400 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5205 - accuracy: 0.7387 - val_loss: 0.5434 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7408 - val_loss: 0.5318 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7457 - val_loss: 0.5362 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7487 - val_loss: 0.5385 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7508 - val_loss: 0.5335 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7549 - val_loss: 0.5400 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7584 - val_loss: 0.5432 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7624 - val_loss: 0.5412 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4755 - accuracy: 0.7654 - val_loss: 0.5432 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4674 - accuracy: 0.7709 - val_loss: 0.5442 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4640 - accuracy: 0.7726 - val_loss: 0.5558 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4582 - accuracy: 0.7739 - val_loss: 0.5505 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4516 - accuracy: 0.7792 - val_loss: 0.5555 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4473 - accuracy: 0.7788 - val_loss: 0.5507 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 20/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4420 - accuracy: 0.7819
Epoch 20: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4428 - accuracy: 0.7817 - val_loss: 0.5626 - val_accuracy: 0.7217 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.44263813153940595
Confusion Matrix :
 [[2923 1400]
 [1017 3306]]
Accuracy on test set:    0.7204487624334952
Sensitivity:    0.7647467036780013 	 Specificity:    0.6761508211889892
Precision  : 0.7025074373140672
Area Under Curve:    0.7204487624334952
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6170 - accuracy: 0.6612 - val_loss: 0.5611 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5625 - accuracy: 0.7086 - val_loss: 0.5504 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7225 - val_loss: 0.5398 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7297 - val_loss: 0.5403 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5267 - accuracy: 0.7339 - val_loss: 0.5384 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7381 - val_loss: 0.5371 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7404 - val_loss: 0.5438 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7463 - val_loss: 0.5391 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7517 - val_loss: 0.5363 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4960 - accuracy: 0.7531 - val_loss: 0.5357 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7569 - val_loss: 0.5501 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4797 - accuracy: 0.7624 - val_loss: 0.5436 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7644 - val_loss: 0.5383 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4707 - accuracy: 0.7690 - val_loss: 0.5505 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4638 - accuracy: 0.7746
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4642 - accuracy: 0.7739 - val_loss: 0.5412 - val_accuracy: 0.7219 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.48585906212208174
Confusion Matrix :
 [[3171 1152]
 [1071 3252]]
Accuracy on test set:    0.7428868841082582
Sensitivity:    0.7522553782095767 	 Specificity:    0.7335183900069396
Precision  : 0.7384196185286104
Area Under Curve:    0.7428868841082582
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6294 - accuracy: 0.6465 - val_loss: 0.5750 - val_accuracy: 0.6994 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5697 - accuracy: 0.7012 - val_loss: 0.5598 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5534 - accuracy: 0.7148 - val_loss: 0.5449 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7234 - val_loss: 0.5402 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7311 - val_loss: 0.5390 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5249 - accuracy: 0.7355 - val_loss: 0.5421 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7410 - val_loss: 0.5382 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7464 - val_loss: 0.5396 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7500 - val_loss: 0.5432 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4974 - accuracy: 0.7531 - val_loss: 0.5347 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7603 - val_loss: 0.5386 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4812 - accuracy: 0.7633 - val_loss: 0.5371 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4754 - accuracy: 0.7671
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4754 - accuracy: 0.7670 - val_loss: 0.5401 - val_accuracy: 0.7277 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4969658345344474
Confusion Matrix :
 [[3399  924]
 [1257 3066]]
Accuracy on test set:    0.7477446217904233
Sensitivity:    0.7092297015961138 	 Specificity:    0.7862595419847328
Precision  : 0.7684210526315789
Area Under Curve:    0.7477446217904232
(8646, 4352) (8646,)
Mean MCC = 0.4477 + 0.0236 and Mean AUC = 0.7226 + 0.0128
Mean Sensitivity = 0.7446 + 0.0415 and Mean Specificity = 0.7006 + 0.0576 and Mean Accuracy = 0.7226 + 0.0128
Mean Precision = 0.7157 + 0.0282





Seed   : 198363
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6041 - accuracy: 0.6692 - val_loss: 0.5586 - val_accuracy: 0.7077 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5549 - accuracy: 0.7125 - val_loss: 0.5454 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7259 - val_loss: 0.5374 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7306 - val_loss: 0.5386 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7371 - val_loss: 0.5359 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7416 - val_loss: 0.5441 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7455 - val_loss: 0.5325 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5015 - accuracy: 0.7492 - val_loss: 0.5365 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4959 - accuracy: 0.7525 - val_loss: 0.5332 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4879 - accuracy: 0.7587 - val_loss: 0.5404 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4815 - accuracy: 0.7610 - val_loss: 0.5380 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4747 - accuracy: 0.7662 - val_loss: 0.5413 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7687 - val_loss: 0.5382 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4610 - accuracy: 0.7745 - val_loss: 0.5472 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4590 - accuracy: 0.7750
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4594 - accuracy: 0.7749 - val_loss: 0.5496 - val_accuracy: 0.7219 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.40643014280955475
Confusion Matrix :
 [[2830 1493]
 [1081 3242]]
Accuracy on test set:    0.7022900763358778
Sensitivity:    0.749942169789498 	 Specificity:    0.6546379828822577
Precision  : 0.684688489968321
Area Under Curve:    0.7022900763358778
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6128 - accuracy: 0.6621 - val_loss: 0.5686 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5587 - accuracy: 0.7124 - val_loss: 0.5491 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7229 - val_loss: 0.5421 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7328 - val_loss: 0.5431 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7347 - val_loss: 0.5415 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7404 - val_loss: 0.5398 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7474 - val_loss: 0.5378 - val_accuracy: 0.7327 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5014 - accuracy: 0.7512 - val_loss: 0.5372 - val_accuracy: 0.7309 - lr: 0.0010

Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4949 - accuracy: 0.7538 - val_loss: 0.5560 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7602 - val_loss: 0.5414 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4811 - accuracy: 0.7611 - val_loss: 0.5413 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4755 - accuracy: 0.7654
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4758 - accuracy: 0.7653 - val_loss: 0.5428 - val_accuracy: 0.7273 - lr: 0.0010
271/271 [==============================] - 0s 638us/step
Independent Testing Matthews Correlation:  0.44368106778734717
Confusion Matrix :
 [[3020 1303]
 [1104 3219]]
Accuracy on test set:    0.7216053666435346
Sensitivity:    0.7446217904233171 	 Specificity:    0.6985889428637521
Precision  : 0.7118531623175586
Area Under Curve:    0.7216053666435345
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6057 - accuracy: 0.6666 - val_loss: 0.5694 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7109 - val_loss: 0.5486 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7224 - val_loss: 0.5448 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7282 - val_loss: 0.5410 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7327 - val_loss: 0.5416 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7381 - val_loss: 0.5389 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7442 - val_loss: 0.5467 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7463 - val_loss: 0.5373 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5002 - accuracy: 0.7517 - val_loss: 0.5407 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7528 - val_loss: 0.5429 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 11/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4883 - accuracy: 0.7593
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4875 - accuracy: 0.7594 - val_loss: 0.5429 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.43116211199696175
Confusion Matrix :
 [[2904 1419]
 [1047 3276]]
Accuracy on test set:    0.7147814018043026
Sensitivity:    0.7578070784177654 	 Specificity:    0.6717557251908397
Precision  : 0.6977635782747604
Area Under Curve:    0.7147814018043025
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6038 - accuracy: 0.6691 - val_loss: 0.5793 - val_accuracy: 0.6933 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5565 - accuracy: 0.7127 - val_loss: 0.5474 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7242 - val_loss: 0.5460 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5306 - accuracy: 0.7311 - val_loss: 0.5420 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5223 - accuracy: 0.7378 - val_loss: 0.5370 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7429 - val_loss: 0.5383 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7476 - val_loss: 0.5346 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5006 - accuracy: 0.7510 - val_loss: 0.5371 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7558 - val_loss: 0.5365 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7574 - val_loss: 0.5408 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7623 - val_loss: 0.5442 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4725 - accuracy: 0.7689
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4727 - accuracy: 0.7689 - val_loss: 0.5453 - val_accuracy: 0.7277 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.42294821602976146
Confusion Matrix :
 [[3121 1202]
 [1293 3030]]
Accuracy on test set:    0.7114272495951885
Sensitivity:    0.7009021512838307 	 Specificity:    0.7219523479065464
Precision  : 0.7159735349716446
Area Under Curve:    0.7114272495951885
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6101 - accuracy: 0.6645 - val_loss: 0.5603 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5612 - accuracy: 0.7101 - val_loss: 0.5463 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7205 - val_loss: 0.5417 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7259 - val_loss: 0.5389 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7333 - val_loss: 0.5438 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5204 - accuracy: 0.7383 - val_loss: 0.5436 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7405 - val_loss: 0.5351 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7457 - val_loss: 0.5367 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7502 - val_loss: 0.5421 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7532 - val_loss: 0.5352 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7567 - val_loss: 0.5397 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 12/400
257/274 [===========================>..] - ETA: 0s - loss: 0.4864 - accuracy: 0.7583
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4865 - accuracy: 0.7587 - val_loss: 0.5394 - val_accuracy: 0.7219 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.4341896386465189
Confusion Matrix :
 [[3103 1220]
 [1226 3097]]
Accuracy on test set:    0.7170946102243813
Sensitivity:    0.7164006476983577 	 Specificity:    0.7177885727504049
Precision  : 0.7173963400509613
Area Under Curve:    0.7170946102243813
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6034 - accuracy: 0.6694 - val_loss: 0.5573 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7136 - val_loss: 0.5465 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7259 - val_loss: 0.5455 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7301 - val_loss: 0.5361 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7362 - val_loss: 0.5405 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7404 - val_loss: 0.5391 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7455 - val_loss: 0.5399 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7488 - val_loss: 0.5406 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4992 - accuracy: 0.7533
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4990 - accuracy: 0.7533 - val_loss: 0.5382 - val_accuracy: 0.7254 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.4513000619490127
Confusion Matrix :
 [[2853 1470]
 [ 918 3405]]
Accuracy on test set:    0.7238029146426093
Sensitivity:    0.78764746703678 	 Specificity:    0.6599583622484386
Precision  : 0.6984615384615385
Area Under Curve:    0.7238029146426094
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6020 - accuracy: 0.6675 - val_loss: 0.5696 - val_accuracy: 0.6985 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5616 - accuracy: 0.7084 - val_loss: 0.5559 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7237 - val_loss: 0.5431 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7291 - val_loss: 0.5433 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5264 - accuracy: 0.7337 - val_loss: 0.5532 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7368 - val_loss: 0.5368 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5127 - accuracy: 0.7415 - val_loss: 0.5366 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7450 - val_loss: 0.5342 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7497 - val_loss: 0.5385 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7544 - val_loss: 0.5346 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4861 - accuracy: 0.7593 - val_loss: 0.5425 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4802 - accuracy: 0.7613 - val_loss: 0.5408 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7640 - val_loss: 0.5434 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7697 - val_loss: 0.5566 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4606 - accuracy: 0.7745
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4605 - accuracy: 0.7747 - val_loss: 0.5566 - val_accuracy: 0.7224 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.44910811078731827
Confusion Matrix :
 [[3292 1031]
 [1356 2967]]
Accuracy on test set:    0.7239185750636132
Sensitivity:    0.6863289382373352 	 Specificity:    0.7615082118898913
Precision  : 0.7421210605302652
Area Under Curve:    0.7239185750636132
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6082 - accuracy: 0.6650 - val_loss: 0.5595 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5582 - accuracy: 0.7128 - val_loss: 0.5439 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7230 - val_loss: 0.5409 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7285 - val_loss: 0.5400 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7348 - val_loss: 0.5343 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7404 - val_loss: 0.5362 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5111 - accuracy: 0.7436 - val_loss: 0.5359 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7493 - val_loss: 0.5368 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7529 - val_loss: 0.5425 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7569 - val_loss: 0.5369 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 11/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4863 - accuracy: 0.7592
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4864 - accuracy: 0.7590 - val_loss: 0.5399 - val_accuracy: 0.7276 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.46105327746916663
Confusion Matrix :
 [[3183 1140]
 [1190 3133]]
Accuracy on test set:    0.7305112190608374
Sensitivity:    0.7247281980106408 	 Specificity:    0.7362942401110341
Precision  : 0.7332085186051954
Area Under Curve:    0.7305112190608374
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6116 - accuracy: 0.6618 - val_loss: 0.5668 - val_accuracy: 0.7059 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5645 - accuracy: 0.7078 - val_loss: 0.5503 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5506 - accuracy: 0.7188 - val_loss: 0.5471 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7254 - val_loss: 0.5448 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7288 - val_loss: 0.5419 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7324 - val_loss: 0.5461 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5219 - accuracy: 0.7361 - val_loss: 0.5388 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7418 - val_loss: 0.5452 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7440 - val_loss: 0.5420 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7499 - val_loss: 0.5429 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7500 - val_loss: 0.5457 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7519 - val_loss: 0.5512 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 13/400
257/274 [===========================>..] - ETA: 0s - loss: 0.4925 - accuracy: 0.7539
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4924 - accuracy: 0.7541 - val_loss: 0.5444 - val_accuracy: 0.7263 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.4735869549825738
Confusion Matrix :
 [[3223 1100]
 [1176 3147]]
Accuracy on test set:    0.7367568817950497
Sensitivity:    0.7279666897987509 	 Specificity:    0.7455470737913485
Precision  : 0.7409936425712268
Area Under Curve:    0.7367568817950496
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6061 - accuracy: 0.6657 - val_loss: 0.5675 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5627 - accuracy: 0.7100 - val_loss: 0.5635 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5494 - accuracy: 0.7198 - val_loss: 0.5492 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7262 - val_loss: 0.5482 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7299 - val_loss: 0.5436 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7354 - val_loss: 0.5451 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7396 - val_loss: 0.5435 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7447 - val_loss: 0.5431 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7481 - val_loss: 0.5447 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 10/400
261/274 [===========================>..] - ETA: 0s - loss: 0.5004 - accuracy: 0.7525
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7521 - val_loss: 0.5565 - val_accuracy: 0.7149 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.5176580988323451
Confusion Matrix :
 [[2940 1383]
 [ 728 3595]]
Accuracy on test set:    0.7558408512606986
Sensitivity:    0.8315984270182744 	 Specificity:    0.6800832755031229
Precision  : 0.722177581357975
Area Under Curve:    0.7558408512606984
(8646, 4352) (8646,)
Mean MCC = 0.4491 + 0.0292 and Mean AUC = 0.7238 + 0.0141
Mean Sensitivity = 0.7428 + 0.0405 and Mean Specificity = 0.7048 + 0.0355 and Mean Accuracy = 0.7238 + 0.0141
Mean Precision = 0.7165 + 0.0181





Seed   : 366076
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6037 - accuracy: 0.6691 - val_loss: 0.5632 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5577 - accuracy: 0.7129 - val_loss: 0.5507 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7236 - val_loss: 0.5421 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7309 - val_loss: 0.5432 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7360 - val_loss: 0.5446 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7418 - val_loss: 0.5396 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7461 - val_loss: 0.5447 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7494 - val_loss: 0.5377 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7533 - val_loss: 0.5385 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7573 - val_loss: 0.5354 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7562 - val_loss: 0.5403 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7637 - val_loss: 0.5414 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7657 - val_loss: 0.5412 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4691 - accuracy: 0.7704 - val_loss: 0.5454 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4634 - accuracy: 0.7728 - val_loss: 0.5471 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4573 - accuracy: 0.7767 - val_loss: 0.5557 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 17/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4534 - accuracy: 0.7763
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4539 - accuracy: 0.7761 - val_loss: 0.5562 - val_accuracy: 0.7172 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4163976259150295
Confusion Matrix :
 [[2660 1663]
 [ 889 3434]]
Accuracy on test set:    0.7048346055979644
Sensitivity:    0.7943557714550081 	 Specificity:    0.6153134397409207
Precision  : 0.6737296448891504
Area Under Curve:    0.7048346055979644
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6073 - accuracy: 0.6647 - val_loss: 0.5756 - val_accuracy: 0.6951 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5574 - accuracy: 0.7124 - val_loss: 0.5514 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7230 - val_loss: 0.5455 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5304 - accuracy: 0.7306 - val_loss: 0.5474 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7361 - val_loss: 0.5452 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5178 - accuracy: 0.7398 - val_loss: 0.5427 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5091 - accuracy: 0.7453 - val_loss: 0.5418 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7479 - val_loss: 0.5434 - val_accuracy: 0.7218 - lr: 0.0010

Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4987 - accuracy: 0.7520 - val_loss: 0.5456 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7599 - val_loss: 0.5449 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7624 - val_loss: 0.5435 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4780 - accuracy: 0.7645 - val_loss: 0.5440 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4714 - accuracy: 0.7688 - val_loss: 0.5634 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4673 - accuracy: 0.7714 - val_loss: 0.5508 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4596 - accuracy: 0.7754 - val_loss: 0.5501 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4563 - accuracy: 0.7755 - val_loss: 0.5535 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4513 - accuracy: 0.7810 - val_loss: 0.5618 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4433 - accuracy: 0.7846 - val_loss: 0.5616 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4390 - accuracy: 0.7864 - val_loss: 0.5621 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 20/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4307 - accuracy: 0.7898
Epoch 20: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4312 - accuracy: 0.7894 - val_loss: 0.5845 - val_accuracy: 0.7167 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4341938671583802
Confusion Matrix :
 [[3090 1233]
 [1213 3110]]
Accuracy on test set:    0.7170946102243813
Sensitivity:    0.7194078186444599 	 Specificity:    0.7147814018043026
Precision  : 0.7160948653004835
Area Under Curve:    0.7170946102243813
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6156 - accuracy: 0.6576 - val_loss: 0.5647 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5627 - accuracy: 0.7095 - val_loss: 0.5534 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7201 - val_loss: 0.5492 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7275 - val_loss: 0.5476 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5290 - accuracy: 0.7308 - val_loss: 0.5456 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5211 - accuracy: 0.7360 - val_loss: 0.5423 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7374 - val_loss: 0.5407 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7421 - val_loss: 0.5468 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7467 - val_loss: 0.5402 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7491 - val_loss: 0.5463 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7543 - val_loss: 0.5457 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 12/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4875 - accuracy: 0.7556
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4877 - accuracy: 0.7556 - val_loss: 0.5446 - val_accuracy: 0.7183 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.44539792726744126
Confusion Matrix :
 [[3077 1246]
 [1152 3171]]
Accuracy on test set:    0.72264631043257
Sensitivity:    0.7335183900069396 	 Specificity:    0.7117742308582004
Precision  : 0.7179080824088748
Area Under Curve:    0.72264631043257
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6075 - accuracy: 0.6657 - val_loss: 0.5629 - val_accuracy: 0.7059 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5572 - accuracy: 0.7124 - val_loss: 0.5475 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7239 - val_loss: 0.5445 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7303 - val_loss: 0.5411 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7360 - val_loss: 0.5415 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7409 - val_loss: 0.5403 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7441 - val_loss: 0.5400 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7474 - val_loss: 0.5412 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5005 - accuracy: 0.7512 - val_loss: 0.5422 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7549 - val_loss: 0.5433 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7577 - val_loss: 0.5398 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7616 - val_loss: 0.5443 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4792 - accuracy: 0.7633 - val_loss: 0.5458 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4724 - accuracy: 0.7689 - val_loss: 0.5624 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4685 - accuracy: 0.7684 - val_loss: 0.5425 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4631 - accuracy: 0.7723 - val_loss: 0.5447 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4553 - accuracy: 0.7779 - val_loss: 0.5570 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4527 - accuracy: 0.7795 - val_loss: 0.5582 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4458 - accuracy: 0.7814 - val_loss: 0.5715 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4429 - accuracy: 0.7831 - val_loss: 0.5592 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 21/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4364 - accuracy: 0.7861
Epoch 21: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4359 - accuracy: 0.7861 - val_loss: 0.5591 - val_accuracy: 0.7246 - lr: 0.0010

271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.43539124755281206
Confusion Matrix :
 [[2897 1426]
 [1023 3300]]
Accuracy on test set:    0.7167476289613695
Sensitivity:    0.7633587786259542 	 Specificity:    0.6701364792967847
Precision  : 0.6982649174777825
Area Under Curve:    0.7167476289613695
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6021 - accuracy: 0.6730 - val_loss: 0.5601 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5578 - accuracy: 0.7102 - val_loss: 0.5494 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7230 - val_loss: 0.5393 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7290 - val_loss: 0.5436 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5261 - accuracy: 0.7347 - val_loss: 0.5401 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7391 - val_loss: 0.5388 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5146 - accuracy: 0.7400 - val_loss: 0.5501 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7488 - val_loss: 0.5328 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7508 - val_loss: 0.5370 - val_accuracy: 0.7371 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7566 - val_loss: 0.5355 - val_accuracy: 0.7349 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4880 - accuracy: 0.7581 - val_loss: 0.5429 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7633 - val_loss: 0.5366 - val_accuracy: 0.7337 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4758 - accuracy: 0.7650 - val_loss: 0.5411 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4675 - accuracy: 0.7697
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4679 - accuracy: 0.7694 - val_loss: 0.5452 - val_accuracy: 0.7260 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.43993024375645984
Confusion Matrix :
 [[3017 1306]
 [1117 3206]]
Accuracy on test set:    0.7197547999074717
Sensitivity:    0.7416146194772149 	 Specificity:    0.6978949803377285
Precision  : 0.7105496453900709
Area Under Curve:    0.7197547999074716
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6131 - accuracy: 0.6614 - val_loss: 0.5703 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7089 - val_loss: 0.5471 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7228 - val_loss: 0.5401 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7284 - val_loss: 0.5369 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7345 - val_loss: 0.5367 - val_accuracy: 0.7339 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7391 - val_loss: 0.5392 - val_accuracy: 0.7335 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7452 - val_loss: 0.5355 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7492 - val_loss: 0.5352 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7517 - val_loss: 0.5334 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4904 - accuracy: 0.7562
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7562 - val_loss: 0.5436 - val_accuracy: 0.7269 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.43554428622878383
Confusion Matrix :
 [[3006 1317]
 [1125 3198]]
Accuracy on test set:    0.7175572519083969
Sensitivity:    0.739764052741152 	 Specificity:    0.6953504510756419
Precision  : 0.7083056478405315
Area Under Curve:    0.7175572519083969
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6111 - accuracy: 0.6607 - val_loss: 0.5638 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5583 - accuracy: 0.7129 - val_loss: 0.5463 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7220 - val_loss: 0.5441 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7290 - val_loss: 0.5407 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7344 - val_loss: 0.5571 - val_accuracy: 0.7032 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7372 - val_loss: 0.5376 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7421 - val_loss: 0.5363 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
253/274 [==========================>...] - ETA: 0s - loss: 0.5061 - accuracy: 0.7481
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7465 - val_loss: 0.5391 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4525889052855838
Confusion Matrix :
 [[3268 1055]
 [1315 3008]]
Accuracy on test set:    0.7258848022206801
Sensitivity:    0.6958130927596576 	 Specificity:    0.7559565116817025
Precision  : 0.7403396505045533
Area Under Curve:    0.7258848022206801
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6021 - accuracy: 0.6707 - val_loss: 0.5558 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5590 - accuracy: 0.7113 - val_loss: 0.5507 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7225 - val_loss: 0.5454 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7299 - val_loss: 0.5419 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5285 - accuracy: 0.7345 - val_loss: 0.5358 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5200 - accuracy: 0.7385 - val_loss: 0.5334 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7415 - val_loss: 0.5338 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7466 - val_loss: 0.5344 - val_accuracy: 0.7296 - lr: 0.0010

Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7497 - val_loss: 0.5357 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7532 - val_loss: 0.5355 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7534 - val_loss: 0.5360 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4858 - accuracy: 0.7592 - val_loss: 0.5389 - val_accuracy: 0.7345 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4790 - accuracy: 0.7642 - val_loss: 0.5382 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4757 - accuracy: 0.7635 - val_loss: 0.5493 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4691 - accuracy: 0.7698 - val_loss: 0.5389 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4654 - accuracy: 0.7699 - val_loss: 0.5426 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4600 - accuracy: 0.7725
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4613 - accuracy: 0.7717 - val_loss: 0.5437 - val_accuracy: 0.7242 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4399722532702699
Confusion Matrix :
 [[3112 1211]
 [1210 3113]]
Accuracy on test set:    0.7199861207494795
Sensitivity:    0.7201017811704835 	 Specificity:    0.7198704603284756
Precision  : 0.7199352451433858
Area Under Curve:    0.7199861207494795
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6141 - accuracy: 0.6642 - val_loss: 0.5675 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5622 - accuracy: 0.7097 - val_loss: 0.5525 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7216 - val_loss: 0.5443 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7271 - val_loss: 0.5417 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5280 - accuracy: 0.7327 - val_loss: 0.5411 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5202 - accuracy: 0.7403 - val_loss: 0.5392 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5168 - accuracy: 0.7403 - val_loss: 0.5376 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7478 - val_loss: 0.5433 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7521 - val_loss: 0.5376 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7531 - val_loss: 0.5401 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7582 - val_loss: 0.5422 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7617 - val_loss: 0.5408 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4768 - accuracy: 0.7649 - val_loss: 0.5503 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4728 - accuracy: 0.7657 - val_loss: 0.5516 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4635 - accuracy: 0.7727 - val_loss: 0.5508 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4583 - accuracy: 0.7774
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4588 - accuracy: 0.7770 - val_loss: 0.5512 - val_accuracy: 0.7276 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4585707816295065
Confusion Matrix :
 [[3196 1127]
 [1214 3109]]
Accuracy on test set:    0.7292389544297941
Sensitivity:    0.719176497802452 	 Specificity:    0.7393014110571362
Precision  : 0.733947119924457
Area Under Curve:    0.7292389544297941
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6096 - accuracy: 0.6646 - val_loss: 0.5693 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5638 - accuracy: 0.7100 - val_loss: 0.5512 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7221 - val_loss: 0.5434 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7282 - val_loss: 0.5454 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5290 - accuracy: 0.7331 - val_loss: 0.5416 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7382 - val_loss: 0.5443 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7426 - val_loss: 0.5425 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7461 - val_loss: 0.5422 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4989 - accuracy: 0.7528
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4988 - accuracy: 0.7530 - val_loss: 0.5454 - val_accuracy: 0.7233 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.5088879420115467
Confusion Matrix :
 [[3100 1223]
 [ 906 3417]]
Accuracy on test set:    0.7537589636826278
Sensitivity:    0.7904233171408744 	 Specificity:    0.7170946102243813
Precision  : 0.7364224137931035
Area Under Curve:    0.7537589636826278
(8646, 4352) (8646,)
Mean MCC = 0.4467 + 0.0234 and Mean AUC = 0.7228 + 0.0120
Mean Sensitivity = 0.7418 + 0.0304 and Mean Specificity = 0.7037 + 0.0370 and Mean Accuracy = 0.7228 + 0.0120
Mean Precision = 0.7155 + 0.0188





Seed   : 264505
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6064 - accuracy: 0.6672 - val_loss: 0.5636 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5588 - accuracy: 0.7118 - val_loss: 0.5522 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7216 - val_loss: 0.5505 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7288 - val_loss: 0.5474 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7349 - val_loss: 0.5439 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5187 - accuracy: 0.7387 - val_loss: 0.5434 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7447 - val_loss: 0.5393 - val_accuracy: 0.7212 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7474 - val_loss: 0.5412 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7531 - val_loss: 0.5349 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4884 - accuracy: 0.7584 - val_loss: 0.5402 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7603 - val_loss: 0.5368 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4768 - accuracy: 0.7644 - val_loss: 0.5421 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4706 - accuracy: 0.7677 - val_loss: 0.5487 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4625 - accuracy: 0.7731
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4627 - accuracy: 0.7731 - val_loss: 0.5543 - val_accuracy: 0.7173 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.43514056556535213
Confusion Matrix :
 [[2885 1438]
 [1013 3310]]
Accuracy on test set:    0.7165163081193615
Sensitivity:    0.7656719870460329 	 Specificity:    0.6673606291926902
Precision  : 0.6971356360572872
Area Under Curve:    0.7165163081193615
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6034 - accuracy: 0.6681 - val_loss: 0.5596 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5541 - accuracy: 0.7126 - val_loss: 0.5485 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7244 - val_loss: 0.5448 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7325 - val_loss: 0.5407 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7389 - val_loss: 0.5400 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5137 - accuracy: 0.7422 - val_loss: 0.5401 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5052 - accuracy: 0.7477 - val_loss: 0.5467 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7506 - val_loss: 0.5394 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4933 - accuracy: 0.7555 - val_loss: 0.5377 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4893 - accuracy: 0.7584 - val_loss: 0.5417 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4820 - accuracy: 0.7622 - val_loss: 0.5405 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4745 - accuracy: 0.7665 - val_loss: 0.5495 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 13/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4676 - accuracy: 0.7701
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7698 - val_loss: 0.5481 - val_accuracy: 0.7192 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.44379936097572514
Confusion Matrix :
 [[3069 1254]
 [1151 3172]]
Accuracy on test set:    0.7218366874855424
Sensitivity:    0.7337497108489475 	 Specificity:    0.7099236641221374
Precision  : 0.7166741979213737
Area Under Curve:    0.7218366874855424
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6113 - accuracy: 0.6610 - val_loss: 0.5668 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7126 - val_loss: 0.5498 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7256 - val_loss: 0.5443 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7296 - val_loss: 0.5419 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5221 - accuracy: 0.7351 - val_loss: 0.5413 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5168 - accuracy: 0.7413 - val_loss: 0.5576 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7466 - val_loss: 0.5448 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5050 - accuracy: 0.7477 - val_loss: 0.5494 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4985 - accuracy: 0.7512
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4985 - accuracy: 0.7514 - val_loss: 0.5457 - val_accuracy: 0.7120 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.44056889835539725
Confusion Matrix :
 [[3398  925]
 [1511 2812]]
Accuracy on test set:    0.7182512144344205
Sensitivity:    0.6504742077261161 	 Specificity:    0.786028221142725
Precision  : 0.7524752475247525
Area Under Curve:    0.7182512144344205
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5980 - accuracy: 0.6760 - val_loss: 0.5606 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7151 - val_loss: 0.5548 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7244 - val_loss: 0.5483 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7304 - val_loss: 0.5402 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7372 - val_loss: 0.5413 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7404 - val_loss: 0.5375 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7429 - val_loss: 0.5358 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7465 - val_loss: 0.5376 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7513 - val_loss: 0.5540 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7533 - val_loss: 0.5353 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7556 - val_loss: 0.5429 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7620 - val_loss: 0.5414 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7613 - val_loss: 0.5491 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 14/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4743 - accuracy: 0.7660 - val_loss: 0.5444 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4680 - accuracy: 0.7705 - val_loss: 0.5468 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4593 - accuracy: 0.7756 - val_loss: 0.5484 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4535 - accuracy: 0.7776
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4539 - accuracy: 0.7772 - val_loss: 0.5563 - val_accuracy: 0.7246 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4404297870253934
Confusion Matrix :
 [[3211 1112]
 [1309 3014]]
Accuracy on test set:    0.7199861207494795
Sensitivity:    0.6972010178117048 	 Specificity:    0.7427712236872542
Precision  : 0.7304895782840524
Area Under Curve:    0.7199861207494795
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6119 - accuracy: 0.6622 - val_loss: 0.5600 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7111 - val_loss: 0.5466 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7227 - val_loss: 0.5450 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7295 - val_loss: 0.5420 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7330 - val_loss: 0.5454 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7399 - val_loss: 0.5405 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5149 - accuracy: 0.7434 - val_loss: 0.5558 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7459 - val_loss: 0.5341 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7520 - val_loss: 0.5338 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4951 - accuracy: 0.7544 - val_loss: 0.5435 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7558 - val_loss: 0.5406 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4844 - accuracy: 0.7592 - val_loss: 0.5408 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7616 - val_loss: 0.5459 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4724 - accuracy: 0.7662 - val_loss: 0.5438 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7695 - val_loss: 0.5453 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4638 - accuracy: 0.7715
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4636 - accuracy: 0.7720 - val_loss: 0.5516 - val_accuracy: 0.7164 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4269718750428109
Confusion Matrix :
 [[3202 1121]
 [1359 2964]]
Accuracy on test set:    0.7131621559102476
Sensitivity:    0.6856349757113116 	 Specificity:    0.7406893361091834
Precision  : 0.7255813953488373
Area Under Curve:    0.7131621559102475
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6052 - accuracy: 0.6703 - val_loss: 0.5592 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7093 - val_loss: 0.5548 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7223 - val_loss: 0.5394 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7286 - val_loss: 0.5350 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7348 - val_loss: 0.5371 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7405 - val_loss: 0.5362 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7418 - val_loss: 0.5330 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7488 - val_loss: 0.5331 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7510 - val_loss: 0.5353 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4950 - accuracy: 0.7550 - val_loss: 0.5384 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7569 - val_loss: 0.5374 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.7604 - val_loss: 0.5389 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4750 - accuracy: 0.7641
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4750 - accuracy: 0.7642 - val_loss: 0.5407 - val_accuracy: 0.7237 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.43123308366697555
Confusion Matrix :
 [[2965 1358]
 [1104 3219]]
Accuracy on test set:    0.7152440434883183
Sensitivity:    0.7446217904233171 	 Specificity:    0.6858662965533194
Precision  : 0.7032991042167358
Area Under Curve:    0.7152440434883182
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6039 - accuracy: 0.6695 - val_loss: 0.5645 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7125 - val_loss: 0.5488 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7238 - val_loss: 0.5453 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7279 - val_loss: 0.5423 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5270 - accuracy: 0.7339 - val_loss: 0.5462 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7387 - val_loss: 0.5392 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7439 - val_loss: 0.5420 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7469 - val_loss: 0.5467 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7508 - val_loss: 0.5397 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4922 - accuracy: 0.7562 - val_loss: 0.5410 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7590 - val_loss: 0.5461 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4816 - accuracy: 0.7631 - val_loss: 0.5538 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4734 - accuracy: 0.7676 - val_loss: 0.5466 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4667 - accuracy: 0.7711
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4674 - accuracy: 0.7706 - val_loss: 0.5514 - val_accuracy: 0.7188 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.46829098916227413
Confusion Matrix :
 [[3092 1231]
 [1069 3254]]
Accuracy on test set:    0.7339810316909554
Sensitivity:    0.7527180198935924 	 Specificity:    0.7152440434883183
Precision  : 0.7255295429208473
Area Under Curve:    0.7339810316909554
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6112 - accuracy: 0.6626 - val_loss: 0.5677 - val_accuracy: 0.6999 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5618 - accuracy: 0.7078 - val_loss: 0.5543 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7220 - val_loss: 0.5458 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7266 - val_loss: 0.5377 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7339 - val_loss: 0.5377 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7380 - val_loss: 0.5366 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7419 - val_loss: 0.5400 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7466 - val_loss: 0.5319 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7509 - val_loss: 0.5409 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7556 - val_loss: 0.5339 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4857 - accuracy: 0.7598 - val_loss: 0.5384 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4793 - accuracy: 0.7644 - val_loss: 0.5373 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4734 - accuracy: 0.7676 - val_loss: 0.5423 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4687 - accuracy: 0.7706 - val_loss: 0.5406 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4603 - accuracy: 0.7759 - val_loss: 0.5459 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4551 - accuracy: 0.7784 - val_loss: 0.5486 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4507 - accuracy: 0.7812 - val_loss: 0.5446 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 18/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4480 - accuracy: 0.7805
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4479 - accuracy: 0.7813 - val_loss: 0.5487 - val_accuracy: 0.7186 - lr: 0.0010
271/271 [==============================] - 0s 665us/step
Independent Testing Matthews Correlation:  0.4626768066176539
Confusion Matrix :
 [[2939 1384]
 [ 949 3374]]
Accuracy on test set:    0.7301642377978256
Sensitivity:    0.7804765209345362 	 Specificity:    0.6798519546611149
Precision  : 0.7091214796132829
Area Under Curve:    0.7301642377978256
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6039 - accuracy: 0.6691 - val_loss: 0.5647 - val_accuracy: 0.7029 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5605 - accuracy: 0.7090 - val_loss: 0.5560 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7223 - val_loss: 0.5463 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7309 - val_loss: 0.5419 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5260 - accuracy: 0.7356 - val_loss: 0.5497 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5207 - accuracy: 0.7388 - val_loss: 0.5408 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7422 - val_loss: 0.5376 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7473 - val_loss: 0.5426 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7527 - val_loss: 0.5405 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7551 - val_loss: 0.5377 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4857 - accuracy: 0.7602 - val_loss: 0.5459 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7622 - val_loss: 0.5455 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4762 - accuracy: 0.7663 - val_loss: 0.5454 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4680 - accuracy: 0.7700
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4683 - accuracy: 0.7700 - val_loss: 0.5420 - val_accuracy: 0.7227 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4608604796955031
Confusion Matrix :
 [[3120 1203]
 [1128 3195]]
Accuracy on test set:    0.7303955586398334
Sensitivity:    0.7390700902151284 	 Specificity:    0.7217210270645386
Precision  : 0.7264665757162346
Area Under Curve:    0.7303955586398334
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6067 - accuracy: 0.6673 - val_loss: 0.5698 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5627 - accuracy: 0.7085 - val_loss: 0.5592 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7194 - val_loss: 0.5538 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7296 - val_loss: 0.5593 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5268 - accuracy: 0.7352 - val_loss: 0.5495 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 6/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5205 - accuracy: 0.7392 - val_loss: 0.5446 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7416 - val_loss: 0.5445 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7465 - val_loss: 0.5467 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5008 - accuracy: 0.7517 - val_loss: 0.5504 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7576 - val_loss: 0.5497 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7611 - val_loss: 0.5470 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4766 - accuracy: 0.7653
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7659 - val_loss: 0.5561 - val_accuracy: 0.7168 - lr: 0.0010
271/271 [==============================] - 0s 668us/step
Independent Testing Matthews Correlation:  0.5077933839054778
Confusion Matrix :
 [[3141 1182]
 [ 949 3374]]
Accuracy on test set:    0.7535276428406199
Sensitivity:    0.7804765209345362 	 Specificity:    0.7265787647467037
Precision  : 0.7405618964003512
Area Under Curve:    0.7535276428406199
(8646, 4352) (8646,)
Mean MCC = 0.4518 + 0.0229 and Mean AUC = 0.7253 + 0.0116
Mean Sensitivity = 0.7330 + 0.0406 and Mean Specificity = 0.7176 + 0.0331 and Mean Accuracy = 0.7253 + 0.0116
Mean Precision = 0.7227 + 0.0160





Seed   : 9640
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6040 - accuracy: 0.6686 - val_loss: 0.5654 - val_accuracy: 0.7029 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7135 - val_loss: 0.5550 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7249 - val_loss: 0.5476 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7311 - val_loss: 0.5493 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5207 - accuracy: 0.7385 - val_loss: 0.5431 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7427 - val_loss: 0.5403 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7481 - val_loss: 0.5468 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5012 - accuracy: 0.7492 - val_loss: 0.5466 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7537 - val_loss: 0.5442 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7566 - val_loss: 0.5461 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4834 - accuracy: 0.7609
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7606 - val_loss: 0.5421 - val_accuracy: 0.7240 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.43028950731899496
Confusion Matrix :
 [[2913 1410]
 [1059 3264]]
Accuracy on test set:    0.7144344205412908
Sensitivity:    0.7550312283136711 	 Specificity:    0.6738376127689105
Precision  : 0.6983311938382541
Area Under Curve:    0.7144344205412908
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6131 - accuracy: 0.6614 - val_loss: 0.5757 - val_accuracy: 0.6979 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5628 - accuracy: 0.7108 - val_loss: 0.5611 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7220 - val_loss: 0.5545 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7296 - val_loss: 0.5502 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5285 - accuracy: 0.7336 - val_loss: 0.5491 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7364 - val_loss: 0.5520 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7399 - val_loss: 0.5488 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7442 - val_loss: 0.5506 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7463 - val_loss: 0.5496 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7493 - val_loss: 0.5456 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7540 - val_loss: 0.5495 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7557 - val_loss: 0.5536 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4830 - accuracy: 0.7595 - val_loss: 0.5511 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4776 - accuracy: 0.7641 - val_loss: 0.5572 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4702 - accuracy: 0.7677 - val_loss: 0.5551 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4668 - accuracy: 0.7700
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7690 - val_loss: 0.5658 - val_accuracy: 0.7204 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.44091367456863473
Confusion Matrix :
 [[3133 1190]
 [1227 3096]]
Accuracy on test set:    0.7204487624334952
Sensitivity:    0.7161693268563497 	 Specificity:    0.7247281980106408
Precision  : 0.7223518432104526
Area Under Curve:    0.7204487624334953
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6062 - accuracy: 0.6676 - val_loss: 0.5691 - val_accuracy: 0.7032 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5563 - accuracy: 0.7150 - val_loss: 0.5628 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7281 - val_loss: 0.5630 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7298 - val_loss: 0.5498 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5202 - accuracy: 0.7386 - val_loss: 0.5476 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5157 - accuracy: 0.7406 - val_loss: 0.5535 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5078 - accuracy: 0.7472 - val_loss: 0.5520 - val_accuracy: 0.7205 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5017 - accuracy: 0.7507 - val_loss: 0.5473 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4949 - accuracy: 0.7549 - val_loss: 0.5482 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7585 - val_loss: 0.5502 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4834 - accuracy: 0.7628 - val_loss: 0.5539 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7656 - val_loss: 0.5504 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 13/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4691 - accuracy: 0.7700
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4698 - accuracy: 0.7700 - val_loss: 0.5486 - val_accuracy: 0.7208 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.42958672466192255
Confusion Matrix :
 [[3015 1308]
 [1159 3164]]
Accuracy on test set:    0.7146657413832986
Sensitivity:    0.7318991441128846 	 Specificity:    0.6974323386537127
Precision  : 0.7075134168157424
Area Under Curve:    0.7146657413832986
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6026 - accuracy: 0.6719 - val_loss: 0.5664 - val_accuracy: 0.7070 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5583 - accuracy: 0.7128 - val_loss: 0.5587 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7233 - val_loss: 0.5548 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7312 - val_loss: 0.5469 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7353 - val_loss: 0.5467 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5190 - accuracy: 0.7402 - val_loss: 0.5510 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7439 - val_loss: 0.5468 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5063 - accuracy: 0.7492 - val_loss: 0.5490 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4983 - accuracy: 0.7518 - val_loss: 0.5532 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7559 - val_loss: 0.5463 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7565 - val_loss: 0.5512 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7600 - val_loss: 0.5570 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4773 - accuracy: 0.7654
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7655 - val_loss: 0.5555 - val_accuracy: 0.7188 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.43710769240398056
Confusion Matrix :
 [[2953 1370]
 [1068 3255]]
Accuracy on test set:    0.7180198935924127
Sensitivity:    0.7529493407356003 	 Specificity:    0.6830904464492251
Precision  : 0.7037837837837838
Area Under Curve:    0.7180198935924127
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6075 - accuracy: 0.6663 - val_loss: 0.5657 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7125 - val_loss: 0.5583 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7230 - val_loss: 0.5521 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7284 - val_loss: 0.5461 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5256 - accuracy: 0.7344 - val_loss: 0.5495 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5192 - accuracy: 0.7394 - val_loss: 0.5502 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7414 - val_loss: 0.5553 - val_accuracy: 0.7026 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7458 - val_loss: 0.5427 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4985 - accuracy: 0.7522 - val_loss: 0.5478 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7543 - val_loss: 0.5472 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7577 - val_loss: 0.5510 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4821 - accuracy: 0.7615 - val_loss: 0.5579 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4770 - accuracy: 0.7627
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4769 - accuracy: 0.7624 - val_loss: 0.5526 - val_accuracy: 0.7230 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.44699977944788793
Confusion Matrix :
 [[2949 1374]
 [1023 3300]]
Accuracy on test set:    0.7227619708535739
Sensitivity:    0.7633587786259542 	 Specificity:    0.6821651630811936
Precision  : 0.7060333761232349
Area Under Curve:    0.7227619708535739
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6309 - accuracy: 0.6484 - val_loss: 0.5724 - val_accuracy: 0.7028 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5667 - accuracy: 0.7062 - val_loss: 0.5555 - val_accuracy: 0.7092 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5504 - accuracy: 0.7179 - val_loss: 0.5531 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7266 - val_loss: 0.5538 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5292 - accuracy: 0.7317 - val_loss: 0.5417 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7375 - val_loss: 0.5453 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7405 - val_loss: 0.5409 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7455 - val_loss: 0.5450 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7486 - val_loss: 0.5441 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7520 - val_loss: 0.5415 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 11/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7578 - val_loss: 0.5437 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4836 - accuracy: 0.7621 - val_loss: 0.5440 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4788 - accuracy: 0.7630 - val_loss: 0.5543 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4741 - accuracy: 0.7670 - val_loss: 0.5456 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4676 - accuracy: 0.7712 - val_loss: 0.5505 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4615 - accuracy: 0.7753 - val_loss: 0.5606 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4551 - accuracy: 0.7780
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4554 - accuracy: 0.7776 - val_loss: 0.5602 - val_accuracy: 0.7218 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.44250548915580856
Confusion Matrix :
 [[2805 1518]
 [ 911 3412]]
Accuracy on test set:    0.7190608373814481
Sensitivity:    0.7892667129308351 	 Specificity:    0.648854961832061
Precision  : 0.6920892494929006
Area Under Curve:    0.7190608373814482
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6076 - accuracy: 0.6685 - val_loss: 0.5686 - val_accuracy: 0.6992 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7105 - val_loss: 0.5561 - val_accuracy: 0.7048 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7230 - val_loss: 0.5515 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7279 - val_loss: 0.5462 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7332 - val_loss: 0.5464 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5227 - accuracy: 0.7376 - val_loss: 0.5410 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7406 - val_loss: 0.5412 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7451 - val_loss: 0.5456 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7510 - val_loss: 0.5413 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7511 - val_loss: 0.5527 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7552 - val_loss: 0.5505 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7573 - val_loss: 0.5429 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4812 - accuracy: 0.7625 - val_loss: 0.5466 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4769 - accuracy: 0.7646 - val_loss: 0.5487 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4704 - accuracy: 0.7668 - val_loss: 0.5484 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 16/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4636 - accuracy: 0.7718
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4645 - accuracy: 0.7710 - val_loss: 0.5546 - val_accuracy: 0.7145 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4432094454871181
Confusion Matrix :
 [[2978 1345]
 [1066 3257]]
Accuracy on test set:    0.7211427249595188
Sensitivity:    0.753411982419616 	 Specificity:    0.6888734674994217
Precision  : 0.707735767057801
Area Under Curve:    0.7211427249595189
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6051 - accuracy: 0.6692 - val_loss: 0.5689 - val_accuracy: 0.7017 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5588 - accuracy: 0.7116 - val_loss: 0.5525 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7252 - val_loss: 0.5469 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7290 - val_loss: 0.5419 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7358 - val_loss: 0.5418 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5190 - accuracy: 0.7387 - val_loss: 0.5421 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7435 - val_loss: 0.5411 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7461 - val_loss: 0.5403 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4990 - accuracy: 0.7532 - val_loss: 0.5465 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7556 - val_loss: 0.5400 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4898 - accuracy: 0.7580 - val_loss: 0.5398 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7615 - val_loss: 0.5508 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4749 - accuracy: 0.7676 - val_loss: 0.5432 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4683 - accuracy: 0.7712
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4690 - accuracy: 0.7708 - val_loss: 0.5498 - val_accuracy: 0.7150 - lr: 0.0010
271/271 [==============================] - 0s 668us/step
Independent Testing Matthews Correlation:  0.4534054575836957
Confusion Matrix :
 [[3123 1200]
 [1163 3160]]
Accuracy on test set:    0.7266944251677077
Sensitivity:    0.7309738607448532 	 Specificity:    0.7224149895905622
Precision  : 0.7247706422018348
Area Under Curve:    0.7266944251677077
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6109 - accuracy: 0.6634 - val_loss: 0.5754 - val_accuracy: 0.6953 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5627 - accuracy: 0.7093 - val_loss: 0.5559 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7205 - val_loss: 0.5520 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7262 - val_loss: 0.5469 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7323 - val_loss: 0.5450 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5221 - accuracy: 0.7377 - val_loss: 0.5430 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7396 - val_loss: 0.5396 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7433 - val_loss: 0.5387 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7462 - val_loss: 0.5402 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5009 - accuracy: 0.7513 - val_loss: 0.5519 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7531 - val_loss: 0.5534 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7560 - val_loss: 0.5510 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4847 - accuracy: 0.7587 - val_loss: 0.5459 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4799 - accuracy: 0.7617 - val_loss: 0.5393 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4735 - accuracy: 0.7657 - val_loss: 0.5421 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4675 - accuracy: 0.7695 - val_loss: 0.5519 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 17/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4644 - accuracy: 0.7715
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4644 - accuracy: 0.7716 - val_loss: 0.5533 - val_accuracy: 0.7224 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.47066360266890894
Confusion Matrix :
 [[3030 1293]
 [1000 3323]]
Accuracy on test set:    0.7347906546379829
Sensitivity:    0.768679157992135 	 Specificity:    0.7009021512838307
Precision  : 0.7198873483535528
Area Under Curve:    0.7347906546379829
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6181 - accuracy: 0.6560 - val_loss: 0.5761 - val_accuracy: 0.6998 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5694 - accuracy: 0.7035 - val_loss: 0.5613 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7155 - val_loss: 0.5508 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7239 - val_loss: 0.5551 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7279 - val_loss: 0.5445 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7336 - val_loss: 0.5497 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7377 - val_loss: 0.5414 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5199 - accuracy: 0.7397 - val_loss: 0.5464 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7420 - val_loss: 0.5451 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7475 - val_loss: 0.5433 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7508 - val_loss: 0.5443 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4980 - accuracy: 0.7531
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7534 - val_loss: 0.5499 - val_accuracy: 0.7168 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.5121508533976744
Confusion Matrix :
 [[3069 1254]
 [ 864 3459]]
Accuracy on test set:    0.7550312283136711
Sensitivity:    0.8001387925052047 	 Specificity:    0.7099236641221374
Precision  : 0.7339274347549332
Area Under Curve:    0.755031228313671
(8646, 4352) (8646,)
Mean MCC = 0.4507 + 0.0234 and Mean AUC = 0.7247 + 0.0116
Mean Sensitivity = 0.7562 + 0.0247 and Mean Specificity = 0.6932 + 0.0219 and Mean Accuracy = 0.7247 + 0.0116
Mean Precision = 0.7116 + 0.0124





Seed   : 372370
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6099 - accuracy: 0.6652 - val_loss: 0.5651 - val_accuracy: 0.7028 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7122 - val_loss: 0.5523 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7219 - val_loss: 0.5465 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7286 - val_loss: 0.5402 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5297 - accuracy: 0.7324 - val_loss: 0.5382 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7379 - val_loss: 0.5411 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7428 - val_loss: 0.5421 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7441 - val_loss: 0.5433 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7486 - val_loss: 0.5380 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7494 - val_loss: 0.5420 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7533 - val_loss: 0.5406 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4884 - accuracy: 0.7576 - val_loss: 0.5384 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7611 - val_loss: 0.5447 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4833 - accuracy: 0.7616
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7617 - val_loss: 0.5486 - val_accuracy: 0.7280 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4370223670073406
Confusion Matrix :
 [[3071 1252]
 [1182 3141]]
Accuracy on test set:    0.7184825352764284
Sensitivity:    0.7265787647467037 	 Specificity:    0.7103863058061531
Precision  : 0.7150011381743683
Area Under Curve:    0.7184825352764284
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6019 - accuracy: 0.6687 - val_loss: 0.5611 - val_accuracy: 0.7041 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5573 - accuracy: 0.7133 - val_loss: 0.5509 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7236 - val_loss: 0.5461 - val_accuracy: 0.7174 - lr: 0.0010

Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7300 - val_loss: 0.5489 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5225 - accuracy: 0.7376 - val_loss: 0.5407 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7396 - val_loss: 0.5420 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7468 - val_loss: 0.5433 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7477 - val_loss: 0.5391 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7531 - val_loss: 0.5455 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4910 - accuracy: 0.7568 - val_loss: 0.5391 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4854 - accuracy: 0.7609 - val_loss: 0.5481 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7643 - val_loss: 0.5463 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4719 - accuracy: 0.7695 - val_loss: 0.5437 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4673 - accuracy: 0.7695 - val_loss: 0.5487 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4587 - accuracy: 0.7750 - val_loss: 0.5545 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4516 - accuracy: 0.7802
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4521 - accuracy: 0.7799 - val_loss: 0.5530 - val_accuracy: 0.7228 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.42831355958114237
Confusion Matrix :
 [[3032 1291]
 [1181 3142]]
Accuracy on test set:    0.714087439278279
Sensitivity:    0.7268100855887115 	 Specificity:    0.7013647929678464
Precision  : 0.70877509587187
Area Under Curve:    0.7140874392782789
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6223 - accuracy: 0.6456 - val_loss: 0.5726 - val_accuracy: 0.6979 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5686 - accuracy: 0.7059 - val_loss: 0.5596 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5527 - accuracy: 0.7185 - val_loss: 0.5500 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7250 - val_loss: 0.5453 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7321 - val_loss: 0.5465 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7340 - val_loss: 0.5425 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7405 - val_loss: 0.5438 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7407 - val_loss: 0.5428 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7442 - val_loss: 0.5427 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7476 - val_loss: 0.5468 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7498 - val_loss: 0.5481 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4966 - accuracy: 0.7550 - val_loss: 0.5580 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4947 - accuracy: 0.7542 - val_loss: 0.5456 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4881 - accuracy: 0.7590
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7587 - val_loss: 0.5542 - val_accuracy: 0.7128 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4244041156986974
Confusion Matrix :
 [[2985 1338]
 [1152 3171]]
Accuracy on test set:    0.7120055517002082
Sensitivity:    0.7335183900069396 	 Specificity:    0.6904927133934767
Precision  : 0.7032601463739189
Area Under Curve:    0.7120055517002082
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6185 - accuracy: 0.6591 - val_loss: 0.5710 - val_accuracy: 0.7033 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7100 - val_loss: 0.5534 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7221 - val_loss: 0.5423 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7303 - val_loss: 0.5409 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7378 - val_loss: 0.5400 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7418 - val_loss: 0.5375 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7464 - val_loss: 0.5389 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7500 - val_loss: 0.5409 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7537 - val_loss: 0.5394 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7574 - val_loss: 0.5365 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 11/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4833 - accuracy: 0.7624
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4837 - accuracy: 0.7623 - val_loss: 0.5445 - val_accuracy: 0.7235 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.437287727178562
Confusion Matrix :
 [[2912 1411]
 [1029 3294]]
Accuracy on test set:    0.7177885727504049
Sensitivity:    0.761970853573907 	 Specificity:    0.6736062919269026
Precision  : 0.7001062699256111
Area Under Curve:    0.7177885727504048
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5999 - accuracy: 0.6734 - val_loss: 0.5562 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7135 - val_loss: 0.5470 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7251 - val_loss: 0.5435 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5297 - accuracy: 0.7332 - val_loss: 0.5423 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5208 - accuracy: 0.7388 - val_loss: 0.5413 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7420 - val_loss: 0.5386 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7443 - val_loss: 0.5407 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7508 - val_loss: 0.5361 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7537 - val_loss: 0.5462 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7572 - val_loss: 0.5392 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7617 - val_loss: 0.5569 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4775 - accuracy: 0.7642 - val_loss: 0.5458 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4721 - accuracy: 0.7659 - val_loss: 0.5524 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4662 - accuracy: 0.7700 - val_loss: 0.5412 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 15/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4611 - accuracy: 0.7735
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4613 - accuracy: 0.7734 - val_loss: 0.5524 - val_accuracy: 0.7246 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.43831507378644763
Confusion Matrix :
 [[2813 1510]
 [ 935 3388]]
Accuracy on test set:    0.7172102706453851
Sensitivity:    0.7837150127226463 	 Specificity:    0.650705528568124
Precision  : 0.6917109024091466
Area Under Curve:    0.7172102706453852
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6103 - accuracy: 0.6632 - val_loss: 0.5613 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7126 - val_loss: 0.5480 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7212 - val_loss: 0.5459 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7279 - val_loss: 0.5428 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5262 - accuracy: 0.7334 - val_loss: 0.5408 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5204 - accuracy: 0.7377 - val_loss: 0.5384 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7419 - val_loss: 0.5421 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7471 - val_loss: 0.5372 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7502 - val_loss: 0.5388 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7534 - val_loss: 0.5481 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7547 - val_loss: 0.5382 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7606 - val_loss: 0.5384 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7611 - val_loss: 0.5435 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4734 - accuracy: 0.7661 - val_loss: 0.5527 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4690 - accuracy: 0.7681 - val_loss: 0.5481 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4625 - accuracy: 0.7722 - val_loss: 0.5512 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 17/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4557 - accuracy: 0.7754
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4560 - accuracy: 0.7752 - val_loss: 0.5615 - val_accuracy: 0.7197 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4276664017089227
Confusion Matrix :
 [[2796 1527]
 [ 963 3360]]
Accuracy on test set:    0.7120055517002082
Sensitivity:    0.7772380291464261 	 Specificity:    0.6467730742539903
Precision  : 0.6875383670963782
Area Under Curve:    0.7120055517002084
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6086 - accuracy: 0.6665 - val_loss: 0.5659 - val_accuracy: 0.7029 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7113 - val_loss: 0.5517 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7216 - val_loss: 0.5453 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7271 - val_loss: 0.5411 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5256 - accuracy: 0.7346 - val_loss: 0.5432 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7388 - val_loss: 0.5412 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5106 - accuracy: 0.7439 - val_loss: 0.5417 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7476 - val_loss: 0.5412 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7526 - val_loss: 0.5427 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7573 - val_loss: 0.5390 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7591 - val_loss: 0.5425 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4810 - accuracy: 0.7629 - val_loss: 0.5453 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4738 - accuracy: 0.7670 - val_loss: 0.5460 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4676 - accuracy: 0.7708 - val_loss: 0.5542 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4613 - accuracy: 0.7755
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4618 - accuracy: 0.7754 - val_loss: 0.5516 - val_accuracy: 0.7187 - lr: 0.0010
271/271 [==============================] - 0s 637us/step
Independent Testing Matthews Correlation:  0.45185361142284935
Confusion Matrix :
 [[2947 1376]
 [1001 3322]]
Accuracy on test set:    0.7250751792736525
Sensitivity:    0.7684478371501272 	 Specificity:    0.6817025213971779
Precision  : 0.7071094082588335
Area Under Curve:    0.7250751792736526
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6148 - accuracy: 0.6570 - val_loss: 0.5748 - val_accuracy: 0.6934 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5622 - accuracy: 0.7078 - val_loss: 0.5543 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7222 - val_loss: 0.5442 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7272 - val_loss: 0.5452 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7348 - val_loss: 0.5422 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5199 - accuracy: 0.7399 - val_loss: 0.5401 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5150 - accuracy: 0.7415 - val_loss: 0.5404 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7471 - val_loss: 0.5510 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7515 - val_loss: 0.5439 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7533 - val_loss: 0.5408 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7580 - val_loss: 0.5459 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4851 - accuracy: 0.7609 - val_loss: 0.5465 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4804 - accuracy: 0.7639 - val_loss: 0.5484 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4723 - accuracy: 0.7682 - val_loss: 0.5455 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4668 - accuracy: 0.7726
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7720 - val_loss: 0.5569 - val_accuracy: 0.7136 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4445789626734423
Confusion Matrix :
 [[3240 1083]
 [1321 3002]]
Accuracy on test set:    0.7219523479065464
Sensitivity:    0.6944251677076104 	 Specificity:    0.7494795281054824
Precision  : 0.7348837209302326
Area Under Curve:    0.7219523479065463
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6017 - accuracy: 0.6720 - val_loss: 0.5597 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5570 - accuracy: 0.7131 - val_loss: 0.5483 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7215 - val_loss: 0.5455 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7297 - val_loss: 0.5425 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5221 - accuracy: 0.7364 - val_loss: 0.5376 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7419 - val_loss: 0.5369 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7442 - val_loss: 0.5385 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7495 - val_loss: 0.5364 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4964 - accuracy: 0.7533 - val_loss: 0.5382 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7568 - val_loss: 0.5358 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4816 - accuracy: 0.7623 - val_loss: 0.5451 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4780 - accuracy: 0.7641 - val_loss: 0.5573 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4700 - accuracy: 0.7673 - val_loss: 0.5519 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 14/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4642 - accuracy: 0.7732
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4642 - accuracy: 0.7734 - val_loss: 0.5401 - val_accuracy: 0.7272 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4647396862789583
Confusion Matrix :
 [[3184 1139]
 [1175 3148]]
Accuracy on test set:    0.7323617857969003
Sensitivity:    0.7281980106407587 	 Specificity:    0.7365255609530419
Precision  : 0.7343130394215068
Area Under Curve:    0.7323617857969004
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6078 - accuracy: 0.6687 - val_loss: 0.5716 - val_accuracy: 0.7005 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5615 - accuracy: 0.7091 - val_loss: 0.5568 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5486 - accuracy: 0.7199 - val_loss: 0.5488 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7286 - val_loss: 0.5408 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7330 - val_loss: 0.5401 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7380 - val_loss: 0.5424 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5146 - accuracy: 0.7418 - val_loss: 0.5375 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7468 - val_loss: 0.5395 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4999 - accuracy: 0.7533 - val_loss: 0.5383 - val_accuracy: 0.7330 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7565 - val_loss: 0.5449 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7604 - val_loss: 0.5553 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4790 - accuracy: 0.7645 - val_loss: 0.5410 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4713 - accuracy: 0.7703 - val_loss: 0.5451 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4672 - accuracy: 0.7718
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4670 - accuracy: 0.7720 - val_loss: 0.5568 - val_accuracy: 0.7316 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.49974074961128406
Confusion Matrix :
 [[3282 1041]
 [1122 3201]]
Accuracy on test set:    0.7498265093684942
Sensitivity:    0.7404580152671756 	 Specificity:    0.7591950034698126
Precision  : 0.7545968882602546
Area Under Curve:    0.7498265093684942
(8646, 4352) (8646,)
Mean MCC = 0.4454 + 0.0215 and Mean AUC = 0.7221 + 0.0110
Mean Sensitivity = 0.7441 + 0.0265 and Mean Specificity = 0.7000 + 0.0371 and Mean Accuracy = 0.7221 + 0.0110
Mean Precision = 0.7137 + 0.0202





Seed   : 315510

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6016 - accuracy: 0.6695 - val_loss: 0.5653 - val_accuracy: 0.6981 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5563 - accuracy: 0.7150 - val_loss: 0.5607 - val_accuracy: 0.7015 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7250 - val_loss: 0.5410 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7300 - val_loss: 0.5416 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7375 - val_loss: 0.5380 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7400 - val_loss: 0.5338 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7456 - val_loss: 0.5328 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5050 - accuracy: 0.7477 - val_loss: 0.5346 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7505 - val_loss: 0.5358 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7531 - val_loss: 0.5344 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4845 - accuracy: 0.7592
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7588 - val_loss: 0.5351 - val_accuracy: 0.7271 - lr: 0.0010
271/271 [==============================] - 0s 638us/step
Independent Testing Matthews Correlation:  0.4329763277103242
Confusion Matrix :
 [[2941 1382]
 [1074 3249]]
Accuracy on test set:    0.7159380060143419
Sensitivity:    0.7515614156835531 	 Specificity:    0.6803145963451307
Precision  : 0.701576333405312
Area Under Curve:    0.7159380060143419
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6080 - accuracy: 0.6667 - val_loss: 0.5619 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5599 - accuracy: 0.7124 - val_loss: 0.5518 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7230 - val_loss: 0.5385 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7299 - val_loss: 0.5347 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7384 - val_loss: 0.5486 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7393 - val_loss: 0.5330 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7445 - val_loss: 0.5348 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7489 - val_loss: 0.5383 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7501 - val_loss: 0.5344 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4898 - accuracy: 0.7570 - val_loss: 0.5401 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4851 - accuracy: 0.7596 - val_loss: 0.5384 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7624 - val_loss: 0.5405 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4726 - accuracy: 0.7653 - val_loss: 0.5388 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4670 - accuracy: 0.7696 - val_loss: 0.5392 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4596 - accuracy: 0.7741 - val_loss: 0.5432 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 16/400
256/274 [===========================>..] - ETA: 0s - loss: 0.4583 - accuracy: 0.7731
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4582 - accuracy: 0.7732 - val_loss: 0.5469 - val_accuracy: 0.7241 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.43739668085389294
Confusion Matrix :
 [[3010 1313]
 [1121 3202]]
Accuracy on test set:    0.7184825352764284
Sensitivity:    0.7406893361091834 	 Specificity:    0.6962757344436734
Precision  : 0.7091915836101883
Area Under Curve:    0.7184825352764284
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6049 - accuracy: 0.6672 - val_loss: 0.5656 - val_accuracy: 0.7041 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5580 - accuracy: 0.7114 - val_loss: 0.5436 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7237 - val_loss: 0.5422 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7295 - val_loss: 0.5364 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7341 - val_loss: 0.5328 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7402 - val_loss: 0.5323 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7430 - val_loss: 0.5417 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7464 - val_loss: 0.5311 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 9/400
261/274 [===========================>..] - ETA: 0s - loss: 0.5000 - accuracy: 0.7501
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7499 - val_loss: 0.5307 - val_accuracy: 0.7298 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.43583613929015264
Confusion Matrix :
 [[3000 1323]
 [1118 3205]]
Accuracy on test set:    0.7176729123294009
Sensitivity:    0.741383298635207 	 Specificity:    0.6939625260235948
Precision  : 0.7078180212014135
Area Under Curve:    0.7176729123294008
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6208 - accuracy: 0.6514 - val_loss: 0.5647 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5641 - accuracy: 0.7092 - val_loss: 0.5484 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5494 - accuracy: 0.7185 - val_loss: 0.5393 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7269 - val_loss: 0.5356 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7312 - val_loss: 0.5353 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7358 - val_loss: 0.5340 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7387 - val_loss: 0.5307 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7438 - val_loss: 0.5347 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7437 - val_loss: 0.5354 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5032 - accuracy: 0.7496 - val_loss: 0.5335 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4974 - accuracy: 0.7520 - val_loss: 0.5354 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4919 - accuracy: 0.7571
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7565 - val_loss: 0.5353 - val_accuracy: 0.7289 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.424401787151155
Confusion Matrix :
 [[2940 1383]
 [1109 3214]]
Accuracy on test set:    0.7117742308582004
Sensitivity:    0.7434651862132778 	 Specificity:    0.6800832755031229
Precision  : 0.6991516206221449
Area Under Curve:    0.7117742308582002
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6084 - accuracy: 0.6639 - val_loss: 0.5596 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5598 - accuracy: 0.7113 - val_loss: 0.5513 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7227 - val_loss: 0.5395 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7304 - val_loss: 0.5332 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7353 - val_loss: 0.5279 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7401 - val_loss: 0.5319 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7462 - val_loss: 0.5259 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7475 - val_loss: 0.5292 - val_accuracy: 0.7352 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4964 - accuracy: 0.7524 - val_loss: 0.5304 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7566 - val_loss: 0.5310 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7606 - val_loss: 0.5345 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4771 - accuracy: 0.7653 - val_loss: 0.5351 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4691 - accuracy: 0.7691
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4696 - accuracy: 0.7688 - val_loss: 0.5396 - val_accuracy: 0.7313 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4421004330001921
Confusion Matrix :
 [[2847 1476]
 [ 950 3373]]
Accuracy on test set:    0.7194078186444599
Sensitivity:    0.7802452000925283 	 Specificity:    0.6585704371963914
Precision  : 0.6956073417199422
Area Under Curve:    0.7194078186444598
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6004 - accuracy: 0.6736 - val_loss: 0.5562 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5572 - accuracy: 0.7138 - val_loss: 0.5425 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7254 - val_loss: 0.5376 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7305 - val_loss: 0.5348 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5256 - accuracy: 0.7347 - val_loss: 0.5345 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5189 - accuracy: 0.7390 - val_loss: 0.5309 - val_accuracy: 0.7331 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7433 - val_loss: 0.5280 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7484 - val_loss: 0.5287 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7507 - val_loss: 0.5299 - val_accuracy: 0.7359 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7540 - val_loss: 0.5341 - val_accuracy: 0.7335 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7584 - val_loss: 0.5388 - val_accuracy: 0.7348 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4812 - accuracy: 0.7615 - val_loss: 0.5374 - val_accuracy: 0.7331 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4763 - accuracy: 0.7654 - val_loss: 0.5352 - val_accuracy: 0.7348 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4693 - accuracy: 0.7683
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4699 - accuracy: 0.7682 - val_loss: 0.5390 - val_accuracy: 0.7336 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.4439126857173078
Confusion Matrix :
 [[2863 1460]
 [ 957 3366]]
Accuracy on test set:    0.7204487624334952
Sensitivity:    0.7786259541984732 	 Specificity:    0.6622715706685173
Precision  : 0.6974720265230004
Area Under Curve:    0.7204487624334952
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6047 - accuracy: 0.6676 - val_loss: 0.5580 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5570 - accuracy: 0.7118 - val_loss: 0.5438 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7219 - val_loss: 0.5385 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7294 - val_loss: 0.5353 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7346 - val_loss: 0.5311 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7405 - val_loss: 0.5398 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5127 - accuracy: 0.7444 - val_loss: 0.5361 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7463 - val_loss: 0.5313 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7511 - val_loss: 0.5358 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 10/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7560 - val_loss: 0.5329 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4859 - accuracy: 0.7606 - val_loss: 0.5514 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4834 - accuracy: 0.7627 - val_loss: 0.5366 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4769 - accuracy: 0.7649 - val_loss: 0.5414 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7680 - val_loss: 0.5455 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4656 - accuracy: 0.7743 - val_loss: 0.5479 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4593 - accuracy: 0.7761 - val_loss: 0.5527 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4550 - accuracy: 0.7781 - val_loss: 0.5491 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 18/400
256/274 [===========================>..] - ETA: 0s - loss: 0.4501 - accuracy: 0.7809
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4505 - accuracy: 0.7808 - val_loss: 0.5468 - val_accuracy: 0.7289 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4503436811228485
Confusion Matrix :
 [[2913 1410]
 [ 976 3347]]
Accuracy on test set:    0.7240342354846172
Sensitivity:    0.7742308582003239 	 Specificity:    0.6738376127689105
Precision  : 0.7035947025436199
Area Under Curve:    0.7240342354846173
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6111 - accuracy: 0.6632 - val_loss: 0.5638 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7110 - val_loss: 0.5513 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7218 - val_loss: 0.5392 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7276 - val_loss: 0.5365 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5260 - accuracy: 0.7367 - val_loss: 0.5332 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5195 - accuracy: 0.7392 - val_loss: 0.5336 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7436 - val_loss: 0.5317 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7505 - val_loss: 0.5370 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7527 - val_loss: 0.5310 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7567 - val_loss: 0.5304 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7618 - val_loss: 0.5322 - val_accuracy: 0.7335 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4804 - accuracy: 0.7617 - val_loss: 0.5355 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4750 - accuracy: 0.7665 - val_loss: 0.5428 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4673 - accuracy: 0.7718 - val_loss: 0.5365 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4612 - accuracy: 0.7748 - val_loss: 0.5406 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4564 - accuracy: 0.7773
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4562 - accuracy: 0.7776 - val_loss: 0.5436 - val_accuracy: 0.7277 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.45547492519915456
Confusion Matrix :
 [[3076 1247]
 [1108 3215]]
Accuracy on test set:    0.7276197085357391
Sensitivity:    0.7436965070552857 	 Specificity:    0.7115429100161924
Precision  : 0.7205289108023308
Area Under Curve:    0.7276197085357391
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6110 - accuracy: 0.6653 - val_loss: 0.5681 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5612 - accuracy: 0.7117 - val_loss: 0.5474 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7227 - val_loss: 0.5451 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7291 - val_loss: 0.5372 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7333 - val_loss: 0.5387 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5214 - accuracy: 0.7382 - val_loss: 0.5374 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7420 - val_loss: 0.5341 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7482 - val_loss: 0.5353 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5008 - accuracy: 0.7519 - val_loss: 0.5326 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7524 - val_loss: 0.5383 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7578 - val_loss: 0.5358 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4854 - accuracy: 0.7610 - val_loss: 0.5545 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7615 - val_loss: 0.5412 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4736 - accuracy: 0.7671 - val_loss: 0.5493 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4685 - accuracy: 0.7711 - val_loss: 0.5422 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4649 - accuracy: 0.7715 - val_loss: 0.5554 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4604 - accuracy: 0.7735 - val_loss: 0.5525 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 18/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4526 - accuracy: 0.7792
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4524 - accuracy: 0.7792 - val_loss: 0.5579 - val_accuracy: 0.7278 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4657099125387912
Confusion Matrix :
 [[3203 1120]
 [1190 3133]]
Accuracy on test set:    0.732824427480916
Sensitivity:    0.7247281980106408 	 Specificity:    0.7409206569511912
Precision  : 0.7366564777803903
Area Under Curve:    0.732824427480916
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6146 - accuracy: 0.6637 - val_loss: 0.5627 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5627 - accuracy: 0.7100 - val_loss: 0.5583 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7227 - val_loss: 0.5410 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5369 - accuracy: 0.7275 - val_loss: 0.5390 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5287 - accuracy: 0.7332 - val_loss: 0.5376 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5208 - accuracy: 0.7381 - val_loss: 0.5423 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5146 - accuracy: 0.7436 - val_loss: 0.5411 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7454 - val_loss: 0.5367 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
253/274 [==========================>...] - ETA: 0s - loss: 0.5035 - accuracy: 0.7487
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7486 - val_loss: 0.5385 - val_accuracy: 0.7242 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.49720517158277056
Confusion Matrix :
 [[3314 1009]
 [1166 3157]]
Accuracy on test set:    0.7484385843164469
Sensitivity:    0.7302798982188295 	 Specificity:    0.7665972704140643
Precision  : 0.757801248199712
Area Under Curve:    0.7484385843164469
(8646, 4352) (8646,)
Mean MCC = 0.4485 + 0.0197 and Mean AUC = 0.7237 + 0.0100
Mean Sensitivity = 0.7509 + 0.0189 and Mean Specificity = 0.6964 + 0.0328 and Mean Accuracy = 0.7237 + 0.0100
Mean Precision = 0.7129 + 0.0190





Seed   : 460014
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5997 - accuracy: 0.6723 - val_loss: 0.5609 - val_accuracy: 0.7030 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5557 - accuracy: 0.7144 - val_loss: 0.5495 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7243 - val_loss: 0.5449 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7317 - val_loss: 0.5390 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7363 - val_loss: 0.5376 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7412 - val_loss: 0.5410 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7448 - val_loss: 0.5308 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5047 - accuracy: 0.7498 - val_loss: 0.5423 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7513 - val_loss: 0.5326 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7551 - val_loss: 0.5312 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7613 - val_loss: 0.5318 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7621 - val_loss: 0.5365 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4760 - accuracy: 0.7656 - val_loss: 0.5344 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4731 - accuracy: 0.7676 - val_loss: 0.5387 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4651 - accuracy: 0.7733 - val_loss: 0.5390 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4609 - accuracy: 0.7744 - val_loss: 0.5436 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4556 - accuracy: 0.7750 - val_loss: 0.5430 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4498 - accuracy: 0.7799 - val_loss: 0.5488 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4437 - accuracy: 0.7837 - val_loss: 0.5449 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 20/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4387 - accuracy: 0.7848
Epoch 20: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4385 - accuracy: 0.7849 - val_loss: 0.5585 - val_accuracy: 0.7209 - lr: 0.0010
271/271 [==============================] - 0s 636us/step
Independent Testing Matthews Correlation:  0.41777475230521166
Confusion Matrix :
 [[2918 1405]
 [1116 3207]]
Accuracy on test set:    0.7084200786490863
Sensitivity:    0.7418459403192228 	 Specificity:    0.6749942169789498
Precision  : 0.6953599306157849
Area Under Curve:    0.7084200786490863
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6064 - accuracy: 0.6661 - val_loss: 0.5670 - val_accuracy: 0.7032 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7146 - val_loss: 0.5476 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7227 - val_loss: 0.5432 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7286 - val_loss: 0.5412 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7349 - val_loss: 0.5419 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7396 - val_loss: 0.5354 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7423 - val_loss: 0.5361 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7477 - val_loss: 0.5357 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7489 - val_loss: 0.5406 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7544 - val_loss: 0.5416 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4891 - accuracy: 0.7569 - val_loss: 0.5392 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7617 - val_loss: 0.5383 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4764 - accuracy: 0.7654 - val_loss: 0.5411 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4744 - accuracy: 0.7684 - val_loss: 0.5471 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4665 - accuracy: 0.7720 - val_loss: 0.5429 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 16/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4622 - accuracy: 0.7725 - val_loss: 0.5538 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4569 - accuracy: 0.7761 - val_loss: 0.5612 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4514 - accuracy: 0.7801 - val_loss: 0.5552 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4452 - accuracy: 0.7814 - val_loss: 0.5571 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4388 - accuracy: 0.7852 - val_loss: 0.5764 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4348 - accuracy: 0.7885 - val_loss: 0.5624 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 22/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4296 - accuracy: 0.7911
Epoch 22: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4305 - accuracy: 0.7906 - val_loss: 0.5612 - val_accuracy: 0.7123 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4228309262392826
Confusion Matrix :
 [[2899 1424]
 [1077 3246]]
Accuracy on test set:    0.7107332870691649
Sensitivity:    0.7508674531575295 	 Specificity:    0.6705991209808003
Precision  : 0.6950749464668095
Area Under Curve:    0.7107332870691649
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6088 - accuracy: 0.6637 - val_loss: 0.5585 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7100 - val_loss: 0.5693 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7200 - val_loss: 0.5453 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7289 - val_loss: 0.5358 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7330 - val_loss: 0.5336 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5189 - accuracy: 0.7380 - val_loss: 0.5354 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7422 - val_loss: 0.5395 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7436 - val_loss: 0.5340 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5032 - accuracy: 0.7473 - val_loss: 0.5453 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5001 - accuracy: 0.7488
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7490 - val_loss: 0.5361 - val_accuracy: 0.7236 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4423565890314642
Confusion Matrix :
 [[2900 1423]
 [ 997 3326]]
Accuracy on test set:    0.7201017811704835
Sensitivity:    0.7693731205181586 	 Specificity:    0.6708304418228083
Precision  : 0.7003579700989682
Area Under Curve:    0.7201017811704834
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6063 - accuracy: 0.6662 - val_loss: 0.5700 - val_accuracy: 0.6974 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5646 - accuracy: 0.7106 - val_loss: 0.5471 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5482 - accuracy: 0.7206 - val_loss: 0.5396 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5368 - accuracy: 0.7287 - val_loss: 0.5357 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7319 - val_loss: 0.5387 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7357 - val_loss: 0.5329 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7407 - val_loss: 0.5303 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5110 - accuracy: 0.7428 - val_loss: 0.5339 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5054 - accuracy: 0.7482 - val_loss: 0.5334 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7506 - val_loss: 0.5418 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4931 - accuracy: 0.7530
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7535 - val_loss: 0.5474 - val_accuracy: 0.7182 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.42910561292141136
Confusion Matrix :
 [[3403  920]
 [1569 2754]]
Accuracy on test set:    0.7121212121212122
Sensitivity:    0.63705759888966 	 Specificity:    0.7871848253527642
Precision  : 0.7495917256396298
Area Under Curve:    0.7121212121212122
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6013 - accuracy: 0.6720 - val_loss: 0.5638 - val_accuracy: 0.7070 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5595 - accuracy: 0.7105 - val_loss: 0.5448 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7237 - val_loss: 0.5525 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7290 - val_loss: 0.5362 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5240 - accuracy: 0.7363 - val_loss: 0.5332 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7400 - val_loss: 0.5349 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7439 - val_loss: 0.5339 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7472 - val_loss: 0.5331 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7522 - val_loss: 0.5340 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7555 - val_loss: 0.5330 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4850 - accuracy: 0.7607 - val_loss: 0.5375 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7638 - val_loss: 0.5439 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4741 - accuracy: 0.7660
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4746 - accuracy: 0.7660 - val_loss: 0.5387 - val_accuracy: 0.7192 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.4478613185707607
Confusion Matrix :
 [[3202 1121]
 [1267 3056]]
Accuracy on test set:    0.7238029146426093
Sensitivity:    0.7069164931760351 	 Specificity:    0.7406893361091834
Precision  : 0.731625568589897
Area Under Curve:    0.7238029146426094
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6101 - accuracy: 0.6619 - val_loss: 0.5550 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7078 - val_loss: 0.5456 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7202 - val_loss: 0.5420 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7286 - val_loss: 0.5362 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7339 - val_loss: 0.5366 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7378 - val_loss: 0.5320 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7438 - val_loss: 0.5311 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7467 - val_loss: 0.5294 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5022 - accuracy: 0.7498 - val_loss: 0.5294 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7526 - val_loss: 0.5332 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4899 - accuracy: 0.7578 - val_loss: 0.5360 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7599 - val_loss: 0.5369 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7626 - val_loss: 0.5383 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4721 - accuracy: 0.7682 - val_loss: 0.5450 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4692 - accuracy: 0.7697 - val_loss: 0.5433 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 16/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4629 - accuracy: 0.7731
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4629 - accuracy: 0.7729 - val_loss: 0.5421 - val_accuracy: 0.7313 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.44024379839629646
Confusion Matrix :
 [[2806 1517]
 [ 921 3402]]
Accuracy on test set:    0.7180198935924127
Sensitivity:    0.7869535045107564 	 Specificity:    0.649086282674069
Precision  : 0.6916039845497052
Area Under Curve:    0.7180198935924127
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6192 - accuracy: 0.6581 - val_loss: 0.5713 - val_accuracy: 0.6957 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5640 - accuracy: 0.7084 - val_loss: 0.5504 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7208 - val_loss: 0.5456 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7266 - val_loss: 0.5389 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7312 - val_loss: 0.5354 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7367 - val_loss: 0.5363 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7416 - val_loss: 0.5354 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7470 - val_loss: 0.5321 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5002 - accuracy: 0.7512 - val_loss: 0.5341 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7550 - val_loss: 0.5478 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4918 - accuracy: 0.7560 - val_loss: 0.5375 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4812 - accuracy: 0.7632 - val_loss: 0.5388 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4729 - accuracy: 0.7673 - val_loss: 0.5386 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7700 - val_loss: 0.5425 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4624 - accuracy: 0.7739 - val_loss: 0.5431 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4558 - accuracy: 0.7779 - val_loss: 0.5507 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4526 - accuracy: 0.7797 - val_loss: 0.5506 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 18/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4430 - accuracy: 0.7843
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4438 - accuracy: 0.7841 - val_loss: 0.5633 - val_accuracy: 0.7167 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4475821665578944
Confusion Matrix :
 [[2638 1685]
 [ 749 3574]]
Accuracy on test set:    0.7184825352764284
Sensitivity:    0.8267406893361092 	 Specificity:    0.6102243812167476
Precision  : 0.6795968815364137
Area Under Curve:    0.7184825352764284
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6072 - accuracy: 0.6675 - val_loss: 0.5573 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5577 - accuracy: 0.7124 - val_loss: 0.5525 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7223 - val_loss: 0.5403 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7309 - val_loss: 0.5383 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7340 - val_loss: 0.5407 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7411 - val_loss: 0.5457 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7451 - val_loss: 0.5311 - val_accuracy: 0.7328 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5014 - accuracy: 0.7495 - val_loss: 0.5322 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4960 - accuracy: 0.7535 - val_loss: 0.5309 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 10/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7574 - val_loss: 0.5298 - val_accuracy: 0.7345 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4811 - accuracy: 0.7620 - val_loss: 0.5348 - val_accuracy: 0.7345 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7643 - val_loss: 0.5344 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4670 - accuracy: 0.7699 - val_loss: 0.5428 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4602 - accuracy: 0.7744 - val_loss: 0.5380 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 15/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4514 - accuracy: 0.7795
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4527 - accuracy: 0.7785 - val_loss: 0.5490 - val_accuracy: 0.7190 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.43893527627837103
Confusion Matrix :
 [[2783 1540]
 [ 906 3417]]
Accuracy on test set:    0.7170946102243813
Sensitivity:    0.7904233171408744 	 Specificity:    0.6437659033078881
Precision  : 0.689328222715352
Area Under Curve:    0.7170946102243811
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6151 - accuracy: 0.6583 - val_loss: 0.5630 - val_accuracy: 0.7030 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.7084 - val_loss: 0.5498 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7203 - val_loss: 0.5422 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7253 - val_loss: 0.5385 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7311 - val_loss: 0.5351 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5247 - accuracy: 0.7348 - val_loss: 0.5384 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7412 - val_loss: 0.5318 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7446 - val_loss: 0.5279 - val_accuracy: 0.7335 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7497 - val_loss: 0.5318 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7533 - val_loss: 0.5430 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7567 - val_loss: 0.5378 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4855 - accuracy: 0.7593 - val_loss: 0.5386 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4748 - accuracy: 0.7652
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4764 - accuracy: 0.7645 - val_loss: 0.5402 - val_accuracy: 0.7253 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4661424541568823
Confusion Matrix :
 [[3047 1276]
 [1035 3288]]
Accuracy on test set:    0.7327087670599121
Sensitivity:    0.7605829285218598 	 Specificity:    0.7048346055979644
Precision  : 0.7204206836108676
Area Under Curve:    0.7327087670599121
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6144 - accuracy: 0.6609 - val_loss: 0.5670 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5650 - accuracy: 0.7071 - val_loss: 0.5529 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5508 - accuracy: 0.7176 - val_loss: 0.5475 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7244 - val_loss: 0.5428 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7280 - val_loss: 0.5386 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7352 - val_loss: 0.5406 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7369 - val_loss: 0.5399 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7429 - val_loss: 0.5391 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7461 - val_loss: 0.5418 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 10/400
260/274 [===========================>..] - ETA: 0s - loss: 0.5020 - accuracy: 0.7487
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5022 - accuracy: 0.7487 - val_loss: 0.5401 - val_accuracy: 0.7244 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.5132071068055645
Confusion Matrix :
 [[3165 1158]
 [ 949 3374]]
Accuracy on test set:    0.7563034929447143
Sensitivity:    0.7804765209345362 	 Specificity:    0.7321304649548924
Precision  : 0.7444836716681377
Area Under Curve:    0.7563034929447143
(8646, 4352) (8646,)
Mean MCC = 0.4466 + 0.0258 and Mean AUC = 0.7218 + 0.0133
Mean Sensitivity = 0.7551 + 0.0497 and Mean Specificity = 0.6884 + 0.0501 and Mean Accuracy = 0.7218 + 0.0133
Mean Precision = 0.7097 + 0.0236





Seed   : 628972
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6034 - accuracy: 0.6682 - val_loss: 0.5553 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7149 - val_loss: 0.5455 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7240 - val_loss: 0.5469 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5290 - accuracy: 0.7333 - val_loss: 0.5362 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7380 - val_loss: 0.5381 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7440 - val_loss: 0.5350 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7480 - val_loss: 0.5344 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7530 - val_loss: 0.5428 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4936 - accuracy: 0.7556 - val_loss: 0.5336 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4845 - accuracy: 0.7596 - val_loss: 0.5352 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4793 - accuracy: 0.7620 - val_loss: 0.5420 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4758 - accuracy: 0.7658 - val_loss: 0.5441 - val_accuracy: 0.7194 - lr: 0.0010

Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4696 - accuracy: 0.7675 - val_loss: 0.5456 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 14/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4623 - accuracy: 0.7732
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4636 - accuracy: 0.7724 - val_loss: 0.5492 - val_accuracy: 0.7163 - lr: 0.0010
271/271 [==============================] - 0s 638us/step
Independent Testing Matthews Correlation:  0.4399904033590731
Confusion Matrix :
 [[2843 1480]
 [ 955 3368]]
Accuracy on test set:    0.7183668748554245
Sensitivity:    0.779088595882489 	 Specificity:    0.65764515382836
Precision  : 0.6947194719471947
Area Under Curve:    0.7183668748554244
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6102 - accuracy: 0.6633 - val_loss: 0.5621 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7094 - val_loss: 0.5612 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7214 - val_loss: 0.5420 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7286 - val_loss: 0.5410 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5251 - accuracy: 0.7350 - val_loss: 0.5392 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7393 - val_loss: 0.5427 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7441 - val_loss: 0.5359 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5065 - accuracy: 0.7478 - val_loss: 0.5353 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5012 - accuracy: 0.7495 - val_loss: 0.5409 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7532 - val_loss: 0.5427 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4884 - accuracy: 0.7569 - val_loss: 0.5363 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4832 - accuracy: 0.7604
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4839 - accuracy: 0.7599 - val_loss: 0.5356 - val_accuracy: 0.7237 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.45093452883331325
Confusion Matrix :
 [[3028 1295]
 [1081 3242]]
Accuracy on test set:    0.7251908396946565
Sensitivity:    0.749942169789498 	 Specificity:    0.7004395095998149
Precision  : 0.7145690985232532
Area Under Curve:    0.7251908396946565
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6149 - accuracy: 0.6601 - val_loss: 0.5691 - val_accuracy: 0.6976 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7097 - val_loss: 0.5518 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7207 - val_loss: 0.5408 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7297 - val_loss: 0.5437 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5268 - accuracy: 0.7326 - val_loss: 0.5393 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7384 - val_loss: 0.5425 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5116 - accuracy: 0.7429 - val_loss: 0.5406 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7464 - val_loss: 0.5367 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7503 - val_loss: 0.5407 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7537 - val_loss: 0.5427 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7553 - val_loss: 0.5464 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7576 - val_loss: 0.5428 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4761 - accuracy: 0.7637 - val_loss: 0.5455 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4705 - accuracy: 0.7665
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4705 - accuracy: 0.7663 - val_loss: 0.5548 - val_accuracy: 0.7200 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4397603430469538
Confusion Matrix :
 [[2797 1526]
 [ 915 3408]]
Accuracy on test set:    0.7176729123294009
Sensitivity:    0.7883414295628036 	 Specificity:    0.6470043950959982
Precision  : 0.6907174706120794
Area Under Curve:    0.7176729123294009
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6266 - accuracy: 0.6466 - val_loss: 0.5734 - val_accuracy: 0.6930 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5662 - accuracy: 0.7066 - val_loss: 0.5475 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5497 - accuracy: 0.7174 - val_loss: 0.5506 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7233 - val_loss: 0.5377 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7309 - val_loss: 0.5362 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7354 - val_loss: 0.5373 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5205 - accuracy: 0.7382 - val_loss: 0.5340 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7421 - val_loss: 0.5354 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7424 - val_loss: 0.5346 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5056 - accuracy: 0.7464 - val_loss: 0.5349 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7502 - val_loss: 0.5367 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4963 - accuracy: 0.7518 - val_loss: 0.5402 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7546 - val_loss: 0.5400 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7597 - val_loss: 0.5414 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 15/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4804 - accuracy: 0.7609 - val_loss: 0.5442 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4750 - accuracy: 0.7638 - val_loss: 0.5423 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4704 - accuracy: 0.7648 - val_loss: 0.5428 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4693 - accuracy: 0.7648 - val_loss: 0.5493 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 19/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4622 - accuracy: 0.7714
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4622 - accuracy: 0.7707 - val_loss: 0.5640 - val_accuracy: 0.7236 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4489118618936771
Confusion Matrix :
 [[2841 1482]
 [ 917 3406]]
Accuracy on test set:    0.722530650011566
Sensitivity:    0.7878787878787878 	 Specificity:    0.6571825121443442
Precision  : 0.6968085106382979
Area Under Curve:    0.722530650011566
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6129 - accuracy: 0.6605 - val_loss: 0.5563 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7111 - val_loss: 0.5432 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5491 - accuracy: 0.7192 - val_loss: 0.5391 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7271 - val_loss: 0.5337 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7335 - val_loss: 0.5383 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7363 - val_loss: 0.5318 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7414 - val_loss: 0.5365 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7452 - val_loss: 0.5309 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5055 - accuracy: 0.7476 - val_loss: 0.5321 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7504 - val_loss: 0.5340 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7576 - val_loss: 0.5372 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4880 - accuracy: 0.7587 - val_loss: 0.5356 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7623 - val_loss: 0.5348 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4763 - accuracy: 0.7660 - val_loss: 0.5427 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4686 - accuracy: 0.7694
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4690 - accuracy: 0.7690 - val_loss: 0.5396 - val_accuracy: 0.7163 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.42164763978984177
Confusion Matrix :
 [[2754 1569]
 [ 950 3373]]
Accuracy on test set:    0.7086513994910941
Sensitivity:    0.7802452000925283 	 Specificity:    0.63705759888966
Precision  : 0.6825171995143666
Area Under Curve:    0.7086513994910941
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6052 - accuracy: 0.6664 - val_loss: 0.5556 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7098 - val_loss: 0.5413 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7227 - val_loss: 0.5356 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7304 - val_loss: 0.5323 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7370 - val_loss: 0.5302 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7399 - val_loss: 0.5282 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7456 - val_loss: 0.5371 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5056 - accuracy: 0.7488 - val_loss: 0.5342 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4983 - accuracy: 0.7493 - val_loss: 0.5328 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7567 - val_loss: 0.5334 - val_accuracy: 0.7334 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4852 - accuracy: 0.7583 - val_loss: 0.5342 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4802 - accuracy: 0.7624 - val_loss: 0.5380 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4700 - accuracy: 0.7693 - val_loss: 0.5447 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7707 - val_loss: 0.5423 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 15/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4619 - accuracy: 0.7721
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4621 - accuracy: 0.7718 - val_loss: 0.5489 - val_accuracy: 0.7245 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.43580680461583976
Confusion Matrix :
 [[2854 1469]
 [ 982 3341]]
Accuracy on test set:    0.7165163081193615
Sensitivity:    0.7728429331482767 	 Specificity:    0.6601896830904465
Precision  : 0.6945945945945946
Area Under Curve:    0.7165163081193615
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6054 - accuracy: 0.6681 - val_loss: 0.5647 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5587 - accuracy: 0.7106 - val_loss: 0.5454 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7243 - val_loss: 0.5365 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7327 - val_loss: 0.5389 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7356 - val_loss: 0.5352 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7402 - val_loss: 0.5327 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7464 - val_loss: 0.5353 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5032 - accuracy: 0.7507 - val_loss: 0.5387 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7532 - val_loss: 0.5328 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4904 - accuracy: 0.7581
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4902 - accuracy: 0.7580 - val_loss: 0.5333 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.45874057556339876
Confusion Matrix :
 [[3030 1293]
 [1050 3273]]
Accuracy on test set:    0.7290076335877863
Sensitivity:    0.7571131158917418 	 Specificity:    0.7009021512838307
Precision  : 0.716819973718791
Area Under Curve:    0.7290076335877863
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6002 - accuracy: 0.6745 - val_loss: 0.5581 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7141 - val_loss: 0.5444 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7238 - val_loss: 0.5390 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7325 - val_loss: 0.5318 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7380 - val_loss: 0.5398 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7415 - val_loss: 0.5394 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5083 - accuracy: 0.7478 - val_loss: 0.5277 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7495 - val_loss: 0.5289 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7550 - val_loss: 0.5277 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7594 - val_loss: 0.5305 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7622 - val_loss: 0.5391 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4745 - accuracy: 0.7664 - val_loss: 0.5335 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4696 - accuracy: 0.7710 - val_loss: 0.5387 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4626 - accuracy: 0.7733
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4628 - accuracy: 0.7734 - val_loss: 0.5549 - val_accuracy: 0.7263 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4610519020382693
Confusion Matrix :
 [[2959 1364]
 [ 974 3349]]
Accuracy on test set:    0.7295859356928059
Sensitivity:    0.7746934998843396 	 Specificity:    0.6844783715012722
Precision  : 0.7105877360492255
Area Under Curve:    0.729585935692806
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6166 - accuracy: 0.6575 - val_loss: 0.5796 - val_accuracy: 0.6843 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5658 - accuracy: 0.7066 - val_loss: 0.5520 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5505 - accuracy: 0.7183 - val_loss: 0.5382 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7255 - val_loss: 0.5399 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7299 - val_loss: 0.5369 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7337 - val_loss: 0.5355 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5178 - accuracy: 0.7380 - val_loss: 0.5363 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7418 - val_loss: 0.5440 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5055 - accuracy: 0.7470 - val_loss: 0.5377 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4993 - accuracy: 0.7507
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7503 - val_loss: 0.5442 - val_accuracy: 0.7263 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.46279519553966547
Confusion Matrix :
 [[3012 1311]
 [1016 3307]]
Accuracy on test set:    0.7308582003238492
Sensitivity:    0.7649780245200093 	 Specificity:    0.6967383761276891
Precision  : 0.7161108705067128
Area Under Curve:    0.7308582003238492
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6147 - accuracy: 0.6598 - val_loss: 0.5635 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5665 - accuracy: 0.7062 - val_loss: 0.5518 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5505 - accuracy: 0.7183 - val_loss: 0.5432 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7258 - val_loss: 0.5453 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7311 - val_loss: 0.5413 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7351 - val_loss: 0.5390 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7394 - val_loss: 0.5359 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7441 - val_loss: 0.5405 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7464 - val_loss: 0.5369 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7514 - val_loss: 0.5388 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4942 - accuracy: 0.7523 - val_loss: 0.5417 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4854 - accuracy: 0.7594
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7586 - val_loss: 0.5466 - val_accuracy: 0.7269 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4833933978879158
Confusion Matrix :
 [[3388  935]
 [1306 3017]]
Accuracy on test set:    0.7408049965301874
Sensitivity:    0.6978949803377285 	 Specificity:    0.7837150127226463
Precision  : 0.7634109311740891
Area Under Curve:    0.7408049965301875
(8646, 4352) (8646,)
Mean MCC = 0.4503 + 0.0164 and Mean AUC = 0.7239 + 0.0087
Mean Sensitivity = 0.7653 + 0.0254 and Mean Specificity = 0.6825 + 0.0402 and Mean Accuracy = 0.7239 + 0.0087
Mean Precision = 0.7081 + 0.0217





Seed   : 34548

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6201 - accuracy: 0.6558 - val_loss: 0.5755 - val_accuracy: 0.6990 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5630 - accuracy: 0.7078 - val_loss: 0.5507 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7197 - val_loss: 0.5438 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7265 - val_loss: 0.5430 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5278 - accuracy: 0.7338 - val_loss: 0.5346 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5206 - accuracy: 0.7392 - val_loss: 0.5346 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5136 - accuracy: 0.7416 - val_loss: 0.5330 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7451 - val_loss: 0.5339 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7481 - val_loss: 0.5370 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4974 - accuracy: 0.7532 - val_loss: 0.5367 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4936 - accuracy: 0.7555 - val_loss: 0.5327 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4874 - accuracy: 0.7576
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7573 - val_loss: 0.5401 - val_accuracy: 0.7179 - lr: 0.0010
271/271 [==============================] - 1s 653us/step
Independent Testing Matthews Correlation:  0.4252724886260944
Confusion Matrix :
 [[2803 1520]
 [ 979 3344]]
Accuracy on test set:    0.7109646079111728
Sensitivity:    0.7735368956743003 	 Specificity:    0.6483923201480454
Precision  : 0.6875
Area Under Curve:    0.7109646079111728
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6172 - accuracy: 0.6578 - val_loss: 0.5677 - val_accuracy: 0.7026 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5632 - accuracy: 0.7094 - val_loss: 0.5506 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7201 - val_loss: 0.5490 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7249 - val_loss: 0.5409 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7317 - val_loss: 0.5398 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7336 - val_loss: 0.5393 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5210 - accuracy: 0.7350 - val_loss: 0.5364 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7410 - val_loss: 0.5370 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7466 - val_loss: 0.5387 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5042 - accuracy: 0.7487 - val_loss: 0.5376 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7494 - val_loss: 0.5394 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7490 - val_loss: 0.5401 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7529 - val_loss: 0.5398 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7596 - val_loss: 0.5517 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4818 - accuracy: 0.7630 - val_loss: 0.5461 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7628 - val_loss: 0.5479 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4705 - accuracy: 0.7673 - val_loss: 0.5489 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 18/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4658 - accuracy: 0.7693
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4661 - accuracy: 0.7692 - val_loss: 0.5540 - val_accuracy: 0.7172 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4250863291289484
Confusion Matrix :
 [[3195 1128]
 [1360 2963]]
Accuracy on test set:    0.712236872542216
Sensitivity:    0.6854036548693038 	 Specificity:    0.7390700902151284
Precision  : 0.7242727939379124
Area Under Curve:    0.712236872542216
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6226 - accuracy: 0.6525 - val_loss: 0.5731 - val_accuracy: 0.6962 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5684 - accuracy: 0.7049 - val_loss: 0.5583 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5508 - accuracy: 0.7173 - val_loss: 0.5490 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7233 - val_loss: 0.5421 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7289 - val_loss: 0.5602 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7335 - val_loss: 0.5427 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5189 - accuracy: 0.7379 - val_loss: 0.5406 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7395 - val_loss: 0.5493 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7432 - val_loss: 0.5439 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7469 - val_loss: 0.5411 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7526 - val_loss: 0.5450 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4936 - accuracy: 0.7551 - val_loss: 0.5454 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7602 - val_loss: 0.5546 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4799 - accuracy: 0.7624 - val_loss: 0.5580 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4771 - accuracy: 0.7631 - val_loss: 0.5567 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4744 - accuracy: 0.7666 - val_loss: 0.5544 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 17/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4662 - accuracy: 0.7709
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4654 - accuracy: 0.7711 - val_loss: 0.5699 - val_accuracy: 0.7134 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4206801145889547
Confusion Matrix :
 [[2567 1756]
 [ 794 3529]]
Accuracy on test set:    0.7050659264399722
Sensitivity:    0.8163312514457552 	 Specificity:    0.5938006014341892
Precision  : 0.6677388836329233
Area Under Curve:    0.7050659264399722
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5990 - accuracy: 0.6723 - val_loss: 0.5621 - val_accuracy: 0.7020 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5546 - accuracy: 0.7151 - val_loss: 0.5517 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7255 - val_loss: 0.5426 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7334 - val_loss: 0.5444 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7391 - val_loss: 0.5527 - val_accuracy: 0.7035 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7424 - val_loss: 0.5403 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7464 - val_loss: 0.5427 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7503 - val_loss: 0.5439 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7563 - val_loss: 0.5440 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4859 - accuracy: 0.7597 - val_loss: 0.5391 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4810 - accuracy: 0.7624 - val_loss: 0.5510 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4750 - accuracy: 0.7667 - val_loss: 0.5465 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4697 - accuracy: 0.7675 - val_loss: 0.5482 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4625 - accuracy: 0.7731 - val_loss: 0.5512 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 15/400
256/274 [===========================>..] - ETA: 0s - loss: 0.4575 - accuracy: 0.7757
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4578 - accuracy: 0.7760 - val_loss: 0.5512 - val_accuracy: 0.7137 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.419712157497163
Confusion Matrix :
 [[3179 1144]
 [1367 2956]]
Accuracy on test set:    0.7095766828591256
Sensitivity:    0.6837844089752487 	 Specificity:    0.7353689567430025
Precision  : 0.7209756097560975
Area Under Curve:    0.7095766828591257
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6044 - accuracy: 0.6683 - val_loss: 0.5676 - val_accuracy: 0.7017 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5584 - accuracy: 0.7129 - val_loss: 0.5517 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7250 - val_loss: 0.5450 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5317 - accuracy: 0.7309 - val_loss: 0.5417 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5220 - accuracy: 0.7364 - val_loss: 0.5446 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7417 - val_loss: 0.5447 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7448 - val_loss: 0.5444 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5017 - accuracy: 0.7516 - val_loss: 0.5429 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7552 - val_loss: 0.5449 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7575 - val_loss: 0.5411 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7626 - val_loss: 0.5478 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4776 - accuracy: 0.7657 - val_loss: 0.5478 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4728 - accuracy: 0.7696
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4731 - accuracy: 0.7693 - val_loss: 0.5530 - val_accuracy: 0.7168 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4430184300093464
Confusion Matrix :
 [[3194 1129]
 [1280 3043]]
Accuracy on test set:    0.7213740458015268
Sensitivity:    0.703909322229933 	 Specificity:    0.7388387693731205
Precision  : 0.7293863854266539
Area Under Curve:    0.7213740458015268
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6151 - accuracy: 0.6602 - val_loss: 0.5646 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7121 - val_loss: 0.5497 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7221 - val_loss: 0.5520 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7271 - val_loss: 0.5506 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5300 - accuracy: 0.7328 - val_loss: 0.5462 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5214 - accuracy: 0.7379 - val_loss: 0.5457 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5136 - accuracy: 0.7420 - val_loss: 0.5501 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7459 - val_loss: 0.5452 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7481 - val_loss: 0.5607 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7514 - val_loss: 0.5441 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7569 - val_loss: 0.5478 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7606 - val_loss: 0.5477 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 13/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4781 - accuracy: 0.7653 - val_loss: 0.5551 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4720 - accuracy: 0.7667 - val_loss: 0.5582 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7699 - val_loss: 0.5580 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4621 - accuracy: 0.7743 - val_loss: 0.5571 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4566 - accuracy: 0.7756 - val_loss: 0.5591 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4502 - accuracy: 0.7786 - val_loss: 0.5591 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 19/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4437 - accuracy: 0.7834
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4442 - accuracy: 0.7831 - val_loss: 0.5653 - val_accuracy: 0.7136 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.43637732897824905
Confusion Matrix :
 [[3019 1304]
 [1134 3189]]
Accuracy on test set:    0.7180198935924127
Sensitivity:    0.7376821651630812 	 Specificity:    0.6983576220217441
Precision  : 0.7097707545070109
Area Under Curve:    0.7180198935924127
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6006 - accuracy: 0.6726 - val_loss: 0.5662 - val_accuracy: 0.7005 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7109 - val_loss: 0.5522 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7230 - val_loss: 0.5467 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7340 - val_loss: 0.5430 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5264 - accuracy: 0.7338 - val_loss: 0.5398 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5159 - accuracy: 0.7417 - val_loss: 0.5394 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7438 - val_loss: 0.5373 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7498 - val_loss: 0.5432 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7533 - val_loss: 0.5424 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4938 - accuracy: 0.7554 - val_loss: 0.5394 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4852 - accuracy: 0.7621 - val_loss: 0.5441 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7632 - val_loss: 0.5536 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4737 - accuracy: 0.7668 - val_loss: 0.5441 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4682 - accuracy: 0.7724 - val_loss: 0.5535 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4652 - accuracy: 0.7715 - val_loss: 0.5516 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4598 - accuracy: 0.7759 - val_loss: 0.5563 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4532 - accuracy: 0.7791 - val_loss: 0.5564 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4473 - accuracy: 0.7831
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4474 - accuracy: 0.7831 - val_loss: 0.5669 - val_accuracy: 0.7111 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.4478474207477673
Confusion Matrix :
 [[2742 1581]
 [ 835 3488]]
Accuracy on test set:    0.7205644228544992
Sensitivity:    0.8068470969234328 	 Specificity:    0.6342817487855655
Precision  : 0.6881041625567172
Area Under Curve:    0.7205644228544992
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6013 - accuracy: 0.6723 - val_loss: 0.5652 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7102 - val_loss: 0.5520 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7224 - val_loss: 0.5512 - val_accuracy: 0.7092 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7285 - val_loss: 0.5397 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5280 - accuracy: 0.7338 - val_loss: 0.5398 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7372 - val_loss: 0.5376 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7396 - val_loss: 0.5497 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7425 - val_loss: 0.5391 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7473 - val_loss: 0.5399 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7529 - val_loss: 0.5409 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4964 - accuracy: 0.7536 - val_loss: 0.5408 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7569 - val_loss: 0.5384 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7581 - val_loss: 0.5398 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7632 - val_loss: 0.5426 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4740 - accuracy: 0.7682 - val_loss: 0.5449 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4727 - accuracy: 0.7667 - val_loss: 0.5462 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4655 - accuracy: 0.7723 - val_loss: 0.5479 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4606 - accuracy: 0.7739
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4612 - accuracy: 0.7736 - val_loss: 0.5623 - val_accuracy: 0.7174 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.4452633058476996
Confusion Matrix :
 [[2938 1385]
 [1020 3303]]
Accuracy on test set:    0.7218366874855424
Sensitivity:    0.7640527411519777 	 Specificity:    0.6796206338191071
Precision  : 0.7045648464163823
Area Under Curve:    0.7218366874855424
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6163 - accuracy: 0.6631 - val_loss: 0.5667 - val_accuracy: 0.7055 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5635 - accuracy: 0.7077 - val_loss: 0.5502 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7212 - val_loss: 0.5499 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7275 - val_loss: 0.5451 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7349 - val_loss: 0.5396 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7382 - val_loss: 0.5434 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7420 - val_loss: 0.5409 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5047 - accuracy: 0.7478 - val_loss: 0.5414 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4985 - accuracy: 0.7518 - val_loss: 0.5435 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4947 - accuracy: 0.7539 - val_loss: 0.5405 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4865 - accuracy: 0.7572 - val_loss: 0.5523 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4777 - accuracy: 0.7640 - val_loss: 0.5449 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4745 - accuracy: 0.7649 - val_loss: 0.5533 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4664 - accuracy: 0.7696
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4670 - accuracy: 0.7692 - val_loss: 0.5511 - val_accuracy: 0.7192 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4791471362607021
Confusion Matrix :
 [[3093 1230]
 [1024 3299]]
Accuracy on test set:    0.7393014110571362
Sensitivity:    0.7631274577839463 	 Specificity:    0.7154753643303262
Precision  : 0.728416869066019
Area Under Curve:    0.7393014110571362
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6085 - accuracy: 0.6670 - val_loss: 0.5605 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5633 - accuracy: 0.7084 - val_loss: 0.5564 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7200 - val_loss: 0.5483 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7277 - val_loss: 0.5453 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7337 - val_loss: 0.5450 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7352 - val_loss: 0.5412 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7407 - val_loss: 0.5499 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5106 - accuracy: 0.7463 - val_loss: 0.5440 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7498 - val_loss: 0.5437 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7528 - val_loss: 0.5424 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7541 - val_loss: 0.5476 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4854 - accuracy: 0.7616 - val_loss: 0.5619 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7629 - val_loss: 0.5597 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4735 - accuracy: 0.7678
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4734 - accuracy: 0.7679 - val_loss: 0.5554 - val_accuracy: 0.7238 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.48878726863621036
Confusion Matrix :
 [[3229 1094]
 [1116 3207]]
Accuracy on test set:    0.7443904695813093
Sensitivity:    0.7418459403192228 	 Specificity:    0.7469349988433958
Precision  : 0.7456405487096024
Area Under Curve:    0.7443904695813093
(8646, 4352) (8646,)
Mean MCC = 0.4431 + 0.0227 and Mean AUC = 0.7203 + 0.0120
Mean Sensitivity = 0.7477 + 0.0440 and Mean Specificity = 0.6930 + 0.0499 and Mean Accuracy = 0.7203 + 0.0120
Mean Precision = 0.7106 + 0.0226





Seed   : 994430
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6112 - accuracy: 0.6638 - val_loss: 0.5704 - val_accuracy: 0.6944 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5584 - accuracy: 0.7133 - val_loss: 0.5515 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7245 - val_loss: 0.5472 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5319 - accuracy: 0.7320 - val_loss: 0.5428 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5225 - accuracy: 0.7366 - val_loss: 0.5451 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7415 - val_loss: 0.5456 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7458 - val_loss: 0.5414 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7506 - val_loss: 0.5347 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7517 - val_loss: 0.5410 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7548 - val_loss: 0.5426 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.7599 - val_loss: 0.5474 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7665 - val_loss: 0.5385 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4707 - accuracy: 0.7678 - val_loss: 0.5389 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4650 - accuracy: 0.7709
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4658 - accuracy: 0.7705 - val_loss: 0.5490 - val_accuracy: 0.7183 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.4320992473931484
Confusion Matrix :
 [[2754 1569]
 [ 908 3415]]
Accuracy on test set:    0.7135091371732593

Sensitivity:    0.7899606754568587 	 Specificity:    0.63705759888966
Precision  : 0.6851926163723917
Area Under Curve:    0.7135091371732594
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6132 - accuracy: 0.6609 - val_loss: 0.5657 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7107 - val_loss: 0.5501 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7269 - val_loss: 0.5444 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7297 - val_loss: 0.5397 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.7355 - val_loss: 0.5408 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7428 - val_loss: 0.5388 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5091 - accuracy: 0.7452 - val_loss: 0.5471 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7499 - val_loss: 0.5507 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4949 - accuracy: 0.7554 - val_loss: 0.5442 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4888 - accuracy: 0.7593
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4893 - accuracy: 0.7589 - val_loss: 0.5419 - val_accuracy: 0.7215 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4228699879913244
Confusion Matrix :
 [[3094 1229]
 [1266 3057]]
Accuracy on test set:    0.7114272495951885
Sensitivity:    0.707147814018043 	 Specificity:    0.715706685172334
Precision  : 0.7132524498366776
Area Under Curve:    0.7114272495951887
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6105 - accuracy: 0.6611 - val_loss: 0.5683 - val_accuracy: 0.7021 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7099 - val_loss: 0.5501 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7222 - val_loss: 0.5479 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7299 - val_loss: 0.5444 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5264 - accuracy: 0.7318 - val_loss: 0.5437 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7374 - val_loss: 0.5389 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7437 - val_loss: 0.5533 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7464 - val_loss: 0.5441 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5003 - accuracy: 0.7509
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7515 - val_loss: 0.5463 - val_accuracy: 0.7182 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.4326219363033264
Confusion Matrix :
 [[3063 1260]
 [1193 3130]]
Accuracy on test set:    0.7162849872773537
Sensitivity:    0.7240342354846172 	 Specificity:    0.7085357390700903
Precision  : 0.7129840546697038
Area Under Curve:    0.7162849872773537
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6170 - accuracy: 0.6577 - val_loss: 0.5665 - val_accuracy: 0.7015 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5643 - accuracy: 0.7063 - val_loss: 0.5534 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5480 - accuracy: 0.7211 - val_loss: 0.5508 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7254 - val_loss: 0.5483 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7322 - val_loss: 0.5410 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7336 - val_loss: 0.5407 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5202 - accuracy: 0.7386 - val_loss: 0.5417 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7405 - val_loss: 0.5411 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7448 - val_loss: 0.5416 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7463 - val_loss: 0.5415 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7487 - val_loss: 0.5538 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7521 - val_loss: 0.5423 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7542 - val_loss: 0.5451 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7553 - val_loss: 0.5443 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4837 - accuracy: 0.7608 - val_loss: 0.5471 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4786 - accuracy: 0.7610
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4794 - accuracy: 0.7601 - val_loss: 0.5466 - val_accuracy: 0.7155 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.42794549269096693
Confusion Matrix :
 [[3093 1230]
 [1243 3080]]
Accuracy on test set:    0.713971778857275
Sensitivity:    0.712468193384224 	 Specificity:    0.7154753643303262
Precision  : 0.7146171693735499
Area Under Curve:    0.7139717788572751
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6047 - accuracy: 0.6662 - val_loss: 0.5626 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7123 - val_loss: 0.5453 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7218 - val_loss: 0.5457 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7307 - val_loss: 0.5413 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7348 - val_loss: 0.5368 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7414 - val_loss: 0.5328 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7437 - val_loss: 0.5310 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5054 - accuracy: 0.7472 - val_loss: 0.5339 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7532 - val_loss: 0.5314 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7550 - val_loss: 0.5322 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4856 - accuracy: 0.7591 - val_loss: 0.5335 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7646 - val_loss: 0.5302 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4723 - accuracy: 0.7675 - val_loss: 0.5316 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4690 - accuracy: 0.7691 - val_loss: 0.5373 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4632 - accuracy: 0.7733
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4630 - accuracy: 0.7735 - val_loss: 0.5440 - val_accuracy: 0.7238 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4397832812143089
Confusion Matrix :
 [[3142 1181]
 [1241 3082]]
Accuracy on test set:    0.7198704603284756
Sensitivity:    0.7129308350682396 	 Specificity:    0.7268100855887115
Precision  : 0.7229650480882008
Area Under Curve:    0.7198704603284755
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6027 - accuracy: 0.6699 - val_loss: 0.5590 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7122 - val_loss: 0.5458 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7243 - val_loss: 0.5427 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7307 - val_loss: 0.5377 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7362 - val_loss: 0.5431 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5168 - accuracy: 0.7419 - val_loss: 0.5324 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7472 - val_loss: 0.5401 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7519 - val_loss: 0.5358 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7535 - val_loss: 0.5351 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7576 - val_loss: 0.5353 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7588 - val_loss: 0.5454 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4779 - accuracy: 0.7671 - val_loss: 0.5391 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4741 - accuracy: 0.7679 - val_loss: 0.5432 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4660 - accuracy: 0.7732
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4663 - accuracy: 0.7730 - val_loss: 0.5465 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.44159344884681606
Confusion Matrix :
 [[2974 1349]
 [1069 3254]]
Accuracy on test set:    0.7203331020124913
Sensitivity:    0.7527180198935924 	 Specificity:    0.6879481841313903
Precision  : 0.70693026287204
Area Under Curve:    0.7203331020124913
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6080 - accuracy: 0.6631 - val_loss: 0.5633 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5619 - accuracy: 0.7083 - val_loss: 0.5492 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7212 - val_loss: 0.5465 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7286 - val_loss: 0.5444 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5263 - accuracy: 0.7348 - val_loss: 0.5381 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5195 - accuracy: 0.7384 - val_loss: 0.5385 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5130 - accuracy: 0.7423 - val_loss: 0.5345 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7459 - val_loss: 0.5395 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7499 - val_loss: 0.5385 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7548 - val_loss: 0.5360 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4898 - accuracy: 0.7554 - val_loss: 0.5369 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4856 - accuracy: 0.7600
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4854 - accuracy: 0.7603 - val_loss: 0.5427 - val_accuracy: 0.7203 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.45205682377169815
Confusion Matrix :
 [[3034 1289]
 [1082 3241]]
Accuracy on test set:    0.7257691417996761
Sensitivity:    0.7497108489474902 	 Specificity:    0.7018274346518621
Precision  : 0.7154525386313466
Area Under Curve:    0.7257691417996761
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6148 - accuracy: 0.6620 - val_loss: 0.5616 - val_accuracy: 0.7077 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5595 - accuracy: 0.7104 - val_loss: 0.5467 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7224 - val_loss: 0.5464 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5314 - accuracy: 0.7306 - val_loss: 0.5406 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7355 - val_loss: 0.5382 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7372 - val_loss: 0.5386 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7443 - val_loss: 0.5379 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 8/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7514 - val_loss: 0.5402 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7528 - val_loss: 0.5357 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7566 - val_loss: 0.5408 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4839 - accuracy: 0.7627 - val_loss: 0.5494 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
256/274 [===========================>..] - ETA: 0s - loss: 0.4780 - accuracy: 0.7634
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4794 - accuracy: 0.7625 - val_loss: 0.5493 - val_accuracy: 0.7197 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.464162575265154
Confusion Matrix :
 [[2907 1416]
 [ 914 3409]]
Accuracy on test set:    0.7305112190608374
Sensitivity:    0.7885727504048115 	 Specificity:    0.6724496877168633
Precision  : 0.7065284974093264
Area Under Curve:    0.7305112190608374
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6018 - accuracy: 0.6721 - val_loss: 0.5703 - val_accuracy: 0.7023 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5582 - accuracy: 0.7126 - val_loss: 0.5517 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7220 - val_loss: 0.5467 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7312 - val_loss: 0.5445 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.7363 - val_loss: 0.5419 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5157 - accuracy: 0.7408 - val_loss: 0.5433 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7465 - val_loss: 0.5363 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7492 - val_loss: 0.5532 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4941 - accuracy: 0.7551
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7548 - val_loss: 0.5404 - val_accuracy: 0.7230 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.47495052230667745
Confusion Matrix :
 [[3017 1306]
 [ 970 3353]]
Accuracy on test set:    0.7367568817950497
Sensitivity:    0.775618783252371 	 Specificity:    0.6978949803377285
Precision  : 0.7196823352650783
Area Under Curve:    0.7367568817950497
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6175 - accuracy: 0.6610 - val_loss: 0.5759 - val_accuracy: 0.7008 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5683 - accuracy: 0.7046 - val_loss: 0.5547 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5507 - accuracy: 0.7172 - val_loss: 0.5538 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7240 - val_loss: 0.5518 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7313 - val_loss: 0.5480 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5274 - accuracy: 0.7322 - val_loss: 0.5474 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7404 - val_loss: 0.5445 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7432 - val_loss: 0.5442 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7473 - val_loss: 0.5501 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7520 - val_loss: 0.5430 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7555 - val_loss: 0.5490 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 12/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4828 - accuracy: 0.7598
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4834 - accuracy: 0.7589 - val_loss: 0.5533 - val_accuracy: 0.7238 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.5025771359859799
Confusion Matrix :
 [[3195 1128]
 [1023 3300]]
Accuracy on test set:    0.7512144344205413
Sensitivity:    0.7633587786259542 	 Specificity:    0.7390700902151284
Precision  : 0.7452574525745257
Area Under Curve:    0.7512144344205413
(8646, 4352) (8646,)
Mean MCC = 0.4491 + 0.0237 and Mean AUC = 0.7240 + 0.0119
Mean Sensitivity = 0.7477 + 0.0303 and Mean Specificity = 0.7003 + 0.0277 and Mean Accuracy = 0.7240 + 0.0119
Mean Precision = 0.7143 + 0.0142





Seed   : 800219
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6075 - accuracy: 0.6684 - val_loss: 0.5699 - val_accuracy: 0.7012 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5574 - accuracy: 0.7136 - val_loss: 0.5541 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7247 - val_loss: 0.5505 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7293 - val_loss: 0.5405 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7370 - val_loss: 0.5422 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5150 - accuracy: 0.7435 - val_loss: 0.5386 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7470 - val_loss: 0.5478 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7504 - val_loss: 0.5385 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 9/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4952 - accuracy: 0.7557
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7555 - val_loss: 0.5382 - val_accuracy: 0.7199 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.41902991861082606
Confusion Matrix :
 [[2733 1590]
 [ 942 3381]]
Accuracy on test set:    0.707147814018043
Sensitivity:    0.7820957668285913 	 Specificity:    0.6321998612074948
Precision  : 0.68014484007242
Area Under Curve:    0.7071478140180432
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6094 - accuracy: 0.6643 - val_loss: 0.5667 - val_accuracy: 0.6981 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5584 - accuracy: 0.7110 - val_loss: 0.5523 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7225 - val_loss: 0.5517 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7298 - val_loss: 0.5447 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7359 - val_loss: 0.5508 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7384 - val_loss: 0.5447 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7434 - val_loss: 0.5388 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7501 - val_loss: 0.5464 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7532 - val_loss: 0.5441 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7565 - val_loss: 0.5424 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7587 - val_loss: 0.5439 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4779 - accuracy: 0.7631 - val_loss: 0.5501 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4732 - accuracy: 0.7663 - val_loss: 0.5472 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4657 - accuracy: 0.7702 - val_loss: 0.5574 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4599 - accuracy: 0.7738 - val_loss: 0.5508 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4535 - accuracy: 0.7767 - val_loss: 0.5584 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4506 - accuracy: 0.7781
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4513 - accuracy: 0.7778 - val_loss: 0.5549 - val_accuracy: 0.7195 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.43334275729494837
Confusion Matrix :
 [[2834 1489]
 [ 974 3349]]
Accuracy on test set:    0.7151283830673144
Sensitivity:    0.7746934998843396 	 Specificity:    0.6555632662502892
Precision  : 0.6922281934683754
Area Under Curve:    0.7151283830673143
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6085 - accuracy: 0.6674 - val_loss: 0.5620 - val_accuracy: 0.7023 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7120 - val_loss: 0.5545 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7222 - val_loss: 0.5454 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7287 - val_loss: 0.5372 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7335 - val_loss: 0.5363 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7394 - val_loss: 0.5367 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7453 - val_loss: 0.5380 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5047 - accuracy: 0.7475 - val_loss: 0.5346 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7513 - val_loss: 0.5382 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7565 - val_loss: 0.5413 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4880 - accuracy: 0.7559 - val_loss: 0.5388 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4796 - accuracy: 0.7633 - val_loss: 0.5424 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7701 - val_loss: 0.5455 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4706 - accuracy: 0.7682 - val_loss: 0.5544 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4603 - accuracy: 0.7749
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4612 - accuracy: 0.7747 - val_loss: 0.5491 - val_accuracy: 0.7152 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4261657878429642
Confusion Matrix :
 [[2677 1646]
 [ 865 3458]]
Accuracy on test set:    0.7095766828591256
Sensitivity:    0.7999074716631969 	 Specificity:    0.6192458940550544
Precision  : 0.6775078369905956
Area Under Curve:    0.7095766828591257
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6094 - accuracy: 0.6658 - val_loss: 0.5602 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5582 - accuracy: 0.7130 - val_loss: 0.5436 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7240 - val_loss: 0.5480 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7310 - val_loss: 0.5370 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7369 - val_loss: 0.5324 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5159 - accuracy: 0.7396 - val_loss: 0.5371 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7445 - val_loss: 0.5366 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7510 - val_loss: 0.5348 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7536 - val_loss: 0.5335 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7590 - val_loss: 0.5343 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4859 - accuracy: 0.7609 - val_loss: 0.5352 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7639 - val_loss: 0.5393 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4721 - accuracy: 0.7697 - val_loss: 0.5412 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4649 - accuracy: 0.7725 - val_loss: 0.5395 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4587 - accuracy: 0.7755 - val_loss: 0.5480 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 16/400

262/274 [===========================>..] - ETA: 0s - loss: 0.4541 - accuracy: 0.7774
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4546 - accuracy: 0.7775 - val_loss: 0.5488 - val_accuracy: 0.7204 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.43857808370130036
Confusion Matrix :
 [[2987 1336]
 [1094 3229]]
Accuracy on test set:    0.7189451769604441
Sensitivity:    0.7469349988433958 	 Specificity:    0.6909553550774925
Precision  : 0.7073384446878422
Area Under Curve:    0.7189451769604441
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6111 - accuracy: 0.6650 - val_loss: 0.5578 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5605 - accuracy: 0.7105 - val_loss: 0.5438 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7240 - val_loss: 0.5446 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7316 - val_loss: 0.5341 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7354 - val_loss: 0.5322 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7418 - val_loss: 0.5301 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7446 - val_loss: 0.5298 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5037 - accuracy: 0.7489 - val_loss: 0.5306 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7521 - val_loss: 0.5282 - val_accuracy: 0.7334 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7543 - val_loss: 0.5329 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7583 - val_loss: 0.5342 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4790 - accuracy: 0.7619 - val_loss: 0.5384 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4733 - accuracy: 0.7649 - val_loss: 0.5441 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 14/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4668 - accuracy: 0.7696
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4672 - accuracy: 0.7695 - val_loss: 0.5653 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4465623668027509
Confusion Matrix :
 [[2632 1691]
 [ 748 3575]]
Accuracy on test set:    0.7179042331714087
Sensitivity:    0.8269720101781171 	 Specificity:    0.6088364561647004
Precision  : 0.6788834029624004
Area Under Curve:    0.7179042331714086
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6116 - accuracy: 0.6619 - val_loss: 0.5653 - val_accuracy: 0.6973 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5637 - accuracy: 0.7087 - val_loss: 0.5450 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7210 - val_loss: 0.5351 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7279 - val_loss: 0.5317 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5288 - accuracy: 0.7338 - val_loss: 0.5314 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7361 - val_loss: 0.5392 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5157 - accuracy: 0.7413 - val_loss: 0.5319 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7462 - val_loss: 0.5285 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5028 - accuracy: 0.7481
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7484 - val_loss: 0.5296 - val_accuracy: 0.7300 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4337527299911338
Confusion Matrix :
 [[2973 1350]
 [1101 3222]]
Accuracy on test set:    0.7165163081193615
Sensitivity:    0.7453157529493407 	 Specificity:    0.6877168632893824
Precision  : 0.7047244094488189
Area Under Curve:    0.7165163081193617
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6055 - accuracy: 0.6673 - val_loss: 0.5572 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5599 - accuracy: 0.7114 - val_loss: 0.5521 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7203 - val_loss: 0.5381 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7273 - val_loss: 0.5357 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5269 - accuracy: 0.7320 - val_loss: 0.5322 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7383 - val_loss: 0.5428 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7405 - val_loss: 0.5334 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7449 - val_loss: 0.5334 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5022 - accuracy: 0.7467 - val_loss: 0.5397 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5003 - accuracy: 0.7497 - val_loss: 0.5363 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4935 - accuracy: 0.7547
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7545 - val_loss: 0.5366 - val_accuracy: 0.7240 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.44878999835051625
Confusion Matrix :
 [[3313 1010]
 [1380 2943]]
Accuracy on test set:    0.7235715938006014
Sensitivity:    0.6807772380291465 	 Specificity:    0.7663659495720564
Precision  : 0.7444978497343789
Area Under Curve:    0.7235715938006015
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6073 - accuracy: 0.6674 - val_loss: 0.5626 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7120 - val_loss: 0.5505 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7231 - val_loss: 0.5431 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7292 - val_loss: 0.5435 - val_accuracy: 0.7140 - lr: 0.0010

Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5249 - accuracy: 0.7362 - val_loss: 0.5367 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7425 - val_loss: 0.5322 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7452 - val_loss: 0.5343 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7508 - val_loss: 0.5353 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7526 - val_loss: 0.5406 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7571 - val_loss: 0.5359 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4827 - accuracy: 0.7627 - val_loss: 0.5372 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4766 - accuracy: 0.7651 - val_loss: 0.5395 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7675 - val_loss: 0.5387 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4632 - accuracy: 0.7729 - val_loss: 0.5445 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4579 - accuracy: 0.7752 - val_loss: 0.5425 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4516 - accuracy: 0.7796
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4519 - accuracy: 0.7793 - val_loss: 0.5534 - val_accuracy: 0.7199 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.43492369060588065
Confusion Matrix :
 [[3131 1192]
 [1251 3072]]
Accuracy on test set:    0.7174415914873931
Sensitivity:    0.710617626648161 	 Specificity:    0.724265556326625
Precision  : 0.7204502814258912
Area Under Curve:    0.7174415914873931
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6037 - accuracy: 0.6696 - val_loss: 0.5595 - val_accuracy: 0.7107 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5598 - accuracy: 0.7115 - val_loss: 0.5498 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7215 - val_loss: 0.5414 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7281 - val_loss: 0.5413 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7344 - val_loss: 0.5322 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5200 - accuracy: 0.7385 - val_loss: 0.5372 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5127 - accuracy: 0.7442 - val_loss: 0.5366 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7453 - val_loss: 0.5316 - val_accuracy: 0.7327 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5037 - accuracy: 0.7501 - val_loss: 0.5397 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7537 - val_loss: 0.5411 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4902 - accuracy: 0.7571 - val_loss: 0.5396 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7606 - val_loss: 0.5337 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4795 - accuracy: 0.7658
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4795 - accuracy: 0.7657 - val_loss: 0.5415 - val_accuracy: 0.7256 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4835873839103748
Confusion Matrix :
 [[3256 1067]
 [1166 3157]]
Accuracy on test set:    0.7417302798982188
Sensitivity:    0.7302798982188295 	 Specificity:    0.7531806615776081
Precision  : 0.7473958333333334
Area Under Curve:    0.7417302798982188
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6102 - accuracy: 0.6656 - val_loss: 0.5700 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5665 - accuracy: 0.7074 - val_loss: 0.5538 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5527 - accuracy: 0.7179 - val_loss: 0.5487 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7229 - val_loss: 0.5436 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7285 - val_loss: 0.5408 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7310 - val_loss: 0.5403 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7337 - val_loss: 0.5385 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5192 - accuracy: 0.7382 - val_loss: 0.5409 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7418 - val_loss: 0.5386 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7446 - val_loss: 0.5400 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7473 - val_loss: 0.5426 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7503 - val_loss: 0.5435 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7538 - val_loss: 0.5464 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7542 - val_loss: 0.5429 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4834 - accuracy: 0.7596 - val_loss: 0.5482 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4792 - accuracy: 0.7619
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4795 - accuracy: 0.7616 - val_loss: 0.5527 - val_accuracy: 0.7260 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4867437736612432
Confusion Matrix :
 [[3421  902]
 [1327 2996]]
Accuracy on test set:    0.7421929215822346
Sensitivity:    0.6930372426555632 	 Specificity:    0.7913486005089059
Precision  : 0.7685992816829144
Area Under Curve:    0.7421929215822345
(8646, 4352) (8646,)
Mean MCC = 0.4451 + 0.0216 and Mean AUC = 0.7210 + 0.0114
Mean Sensitivity = 0.7491 + 0.0448 and Mean Specificity = 0.6930 + 0.0611 and Mean Accuracy = 0.7210 + 0.0114
Mean Precision = 0.7122 + 0.0306





Seed   : 818964

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6110 - accuracy: 0.6677 - val_loss: 0.5645 - val_accuracy: 0.7032 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5559 - accuracy: 0.7130 - val_loss: 0.5464 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7246 - val_loss: 0.5403 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5294 - accuracy: 0.7315 - val_loss: 0.5425 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7342 - val_loss: 0.5348 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5130 - accuracy: 0.7434 - val_loss: 0.5530 - val_accuracy: 0.7041 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7471 - val_loss: 0.5328 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7521 - val_loss: 0.5340 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4947 - accuracy: 0.7558 - val_loss: 0.5385 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4855 - accuracy: 0.7617 - val_loss: 0.5369 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7655 - val_loss: 0.5441 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 12/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4702 - accuracy: 0.7701
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4707 - accuracy: 0.7696 - val_loss: 0.5368 - val_accuracy: 0.7221 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4167390212142482
Confusion Matrix :
 [[2812 1511]
 [1022 3301]]
Accuracy on test set:    0.7070321535970391
Sensitivity:    0.7635900994679621 	 Specificity:    0.6504742077261161
Precision  : 0.6859933499584372
Area Under Curve:    0.707032153597039
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6162 - accuracy: 0.6564 - val_loss: 0.5648 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5651 - accuracy: 0.7081 - val_loss: 0.5502 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5500 - accuracy: 0.7191 - val_loss: 0.5445 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7244 - val_loss: 0.5496 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5310 - accuracy: 0.7318 - val_loss: 0.5368 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5227 - accuracy: 0.7365 - val_loss: 0.5365 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7408 - val_loss: 0.5349 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7425 - val_loss: 0.5367 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7478 - val_loss: 0.5365 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7516 - val_loss: 0.5369 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7515 - val_loss: 0.5415 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4896 - accuracy: 0.7561
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4899 - accuracy: 0.7558 - val_loss: 0.5435 - val_accuracy: 0.7223 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4375447915485214
Confusion Matrix :
 [[3157 1166]
 [1266 3057]]
Accuracy on test set:    0.7187138561184363
Sensitivity:    0.707147814018043 	 Specificity:    0.7302798982188295
Precision  : 0.7238929670850106
Area Under Curve:    0.7187138561184363
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6114 - accuracy: 0.6613 - val_loss: 0.5663 - val_accuracy: 0.7010 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7114 - val_loss: 0.5507 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7234 - val_loss: 0.5487 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7279 - val_loss: 0.5458 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7334 - val_loss: 0.5468 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7390 - val_loss: 0.5379 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7432 - val_loss: 0.5404 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7474 - val_loss: 0.5381 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4960 - accuracy: 0.7522 - val_loss: 0.5430 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4900 - accuracy: 0.7543
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7537 - val_loss: 0.5461 - val_accuracy: 0.7199 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4418916845763602
Confusion Matrix :
 [[3325  998]
 [1424 2899]]
Accuracy on test set:    0.7198704603284756
Sensitivity:    0.6705991209808003 	 Specificity:    0.7691417996761508
Precision  : 0.7439055683859379
Area Under Curve:    0.7198704603284755
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6058 - accuracy: 0.6677 - val_loss: 0.5767 - val_accuracy: 0.6866 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5572 - accuracy: 0.7143 - val_loss: 0.5522 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7237 - val_loss: 0.5477 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7332 - val_loss: 0.5529 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5221 - accuracy: 0.7383 - val_loss: 0.5393 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7411 - val_loss: 0.5402 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5073 - accuracy: 0.7469 - val_loss: 0.5399 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5015 - accuracy: 0.7493 - val_loss: 0.5413 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7536 - val_loss: 0.5416 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7566 - val_loss: 0.5413 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4816 - accuracy: 0.7618 - val_loss: 0.5414 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4739 - accuracy: 0.7686 - val_loss: 0.5520 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7703 - val_loss: 0.5485 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4611 - accuracy: 0.7748
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4623 - accuracy: 0.7740 - val_loss: 0.5506 - val_accuracy: 0.7190 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4255238685903618
Confusion Matrix :
 [[2882 1441]
 [1050 3273]]
Accuracy on test set:    0.7118898912792042
Sensitivity:    0.7571131158917418 	 Specificity:    0.6666666666666666
Precision  : 0.6943148069579974
Area Under Curve:    0.7118898912792043
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6068 - accuracy: 0.6679 - val_loss: 0.5542 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7124 - val_loss: 0.5429 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7233 - val_loss: 0.5361 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7291 - val_loss: 0.5362 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5260 - accuracy: 0.7348 - val_loss: 0.5350 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5191 - accuracy: 0.7396 - val_loss: 0.5410 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5125 - accuracy: 0.7433 - val_loss: 0.5329 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7467 - val_loss: 0.5343 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4987 - accuracy: 0.7522 - val_loss: 0.5341 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7581 - val_loss: 0.5354 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7621 - val_loss: 0.5447 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4776 - accuracy: 0.7626 - val_loss: 0.5434 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7680 - val_loss: 0.5458 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4634 - accuracy: 0.7720 - val_loss: 0.5480 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4572 - accuracy: 0.7755 - val_loss: 0.5503 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4509 - accuracy: 0.7806 - val_loss: 0.5518 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 17/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4433 - accuracy: 0.7845
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4440 - accuracy: 0.7843 - val_loss: 0.5574 - val_accuracy: 0.7250 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.43359147599001296
Confusion Matrix :
 [[3014 1309]
 [1141 3182]]
Accuracy on test set:    0.7166319685403655
Sensitivity:    0.7360629192690261 	 Specificity:    0.6972010178117048
Precision  : 0.7085281674460031
Area Under Curve:    0.7166319685403655
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6312 - accuracy: 0.6466 - val_loss: 0.5677 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5675 - accuracy: 0.7054 - val_loss: 0.5520 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5515 - accuracy: 0.7191 - val_loss: 0.5357 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7260 - val_loss: 0.5411 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7322 - val_loss: 0.5431 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5251 - accuracy: 0.7361 - val_loss: 0.5440 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7393 - val_loss: 0.5385 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5127 - accuracy: 0.7424 - val_loss: 0.5339 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7488 - val_loss: 0.5352 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7506 - val_loss: 0.5335 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7531 - val_loss: 0.5342 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7569 - val_loss: 0.5374 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4851 - accuracy: 0.7594
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4855 - accuracy: 0.7591 - val_loss: 0.5434 - val_accuracy: 0.7244 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4485487589946051
Confusion Matrix :
 [[3230 1093]
 [1293 3030]]
Accuracy on test set:    0.7240342354846172
Sensitivity:    0.7009021512838307 	 Specificity:    0.7471663196854037
Precision  : 0.7349017705554208
Area Under Curve:    0.7240342354846172
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6038 - accuracy: 0.6682 - val_loss: 0.5607 - val_accuracy: 0.7077 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5573 - accuracy: 0.7134 - val_loss: 0.5484 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7234 - val_loss: 0.5479 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7322 - val_loss: 0.5404 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7336 - val_loss: 0.5423 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7406 - val_loss: 0.5405 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 7/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7452 - val_loss: 0.5374 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7489 - val_loss: 0.5414 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4954 - accuracy: 0.7538 - val_loss: 0.5410 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7580 - val_loss: 0.5459 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4834 - accuracy: 0.7615 - val_loss: 0.5463 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4770 - accuracy: 0.7657 - val_loss: 0.5447 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7690 - val_loss: 0.5537 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4621 - accuracy: 0.7728 - val_loss: 0.5510 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 15/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4582 - accuracy: 0.7742
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4580 - accuracy: 0.7744 - val_loss: 0.5571 - val_accuracy: 0.7265 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4380077170378051
Confusion Matrix :
 [[3238 1085]
 [1348 2975]]
Accuracy on test set:    0.7185981956974323
Sensitivity:    0.6881795049733981 	 Specificity:    0.7490168864214666
Precision  : 0.7327586206896551
Area Under Curve:    0.7185981956974323
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6116 - accuracy: 0.6619 - val_loss: 0.5630 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7117 - val_loss: 0.5474 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7227 - val_loss: 0.5420 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7273 - val_loss: 0.5446 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5262 - accuracy: 0.7327 - val_loss: 0.5354 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5192 - accuracy: 0.7386 - val_loss: 0.5395 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7420 - val_loss: 0.5361 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7474 - val_loss: 0.5361 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7511 - val_loss: 0.5336 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7539 - val_loss: 0.5332 - val_accuracy: 0.7328 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7564 - val_loss: 0.5407 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.7582 - val_loss: 0.5407 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4746 - accuracy: 0.7658 - val_loss: 0.5428 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4721 - accuracy: 0.7673 - val_loss: 0.5434 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4636 - accuracy: 0.7727
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4641 - accuracy: 0.7724 - val_loss: 0.5410 - val_accuracy: 0.7273 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.45551173704313136
Confusion Matrix :
 [[3117 1206]
 [1148 3175]]
Accuracy on test set:    0.727735368956743
Sensitivity:    0.7344436733749711 	 Specificity:    0.721027064538515
Precision  : 0.7247203834740926
Area Under Curve:    0.727735368956743
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6096 - accuracy: 0.6616 - val_loss: 0.5831 - val_accuracy: 0.6844 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5620 - accuracy: 0.7107 - val_loss: 0.5527 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7222 - val_loss: 0.5457 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7284 - val_loss: 0.5437 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5287 - accuracy: 0.7324 - val_loss: 0.5356 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5197 - accuracy: 0.7396 - val_loss: 0.5379 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7429 - val_loss: 0.5366 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5083 - accuracy: 0.7454 - val_loss: 0.5335 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5032 - accuracy: 0.7485 - val_loss: 0.5354 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7517 - val_loss: 0.5360 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4918 - accuracy: 0.7551 - val_loss: 0.5404 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7595 - val_loss: 0.5370 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4810 - accuracy: 0.7611 - val_loss: 0.5466 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4782 - accuracy: 0.7641 - val_loss: 0.5397 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4704 - accuracy: 0.7699 - val_loss: 0.5501 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4655 - accuracy: 0.7704 - val_loss: 0.5442 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 17/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4594 - accuracy: 0.7730
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4600 - accuracy: 0.7730 - val_loss: 0.5487 - val_accuracy: 0.7217 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.4643054462526063
Confusion Matrix :
 [[3063 1260]
 [1058 3265]]
Accuracy on test set:    0.7318991441128846
Sensitivity:    0.7552625491556789 	 Specificity:    0.7085357390700903
Precision  : 0.7215469613259669
Area Under Curve:    0.7318991441128845
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6081 - accuracy: 0.6690 - val_loss: 0.5665 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5640 - accuracy: 0.7083 - val_loss: 0.5507 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7220 - val_loss: 0.5453 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7268 - val_loss: 0.5513 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7327 - val_loss: 0.5486 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7377 - val_loss: 0.5444 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7414 - val_loss: 0.5427 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7493 - val_loss: 0.5430 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7498 - val_loss: 0.5411 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7529 - val_loss: 0.5498 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7576 - val_loss: 0.5469 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4845 - accuracy: 0.7613 - val_loss: 0.5440 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 13/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4761 - accuracy: 0.7650
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7644 - val_loss: 0.5465 - val_accuracy: 0.7244 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.5056733270067325
Confusion Matrix :
 [[3265 1058]
 [1079 3244]]
Accuracy on test set:    0.7528336803145963
Sensitivity:    0.7504048114735138 	 Specificity:    0.7552625491556789
Precision  : 0.7540678754067875
Area Under Curve:    0.7528336803145963
(8646, 4352) (8646,)
Mean MCC = 0.4467 + 0.0236 and Mean AUC = 0.7229 + 0.0121
Mean Sensitivity = 0.7264 + 0.0308 and Mean Specificity = 0.7195 + 0.0370 and Mean Accuracy = 0.7229 + 0.0121
Mean Precision = 0.7225 + 0.0201





Seed   : 813246
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6075 - accuracy: 0.6660 - val_loss: 0.5620 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5552 - accuracy: 0.7131 - val_loss: 0.5499 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7233 - val_loss: 0.5514 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7321 - val_loss: 0.5435 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7361 - val_loss: 0.5391 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5146 - accuracy: 0.7415 - val_loss: 0.5373 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7462 - val_loss: 0.5385 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7506 - val_loss: 0.5418 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4949 - accuracy: 0.7538
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4950 - accuracy: 0.7537 - val_loss: 0.5354 - val_accuracy: 0.7174 - lr: 0.0010
271/271 [==============================] - 0s 637us/step
Independent Testing Matthews Correlation:  0.420807919985862
Confusion Matrix :
 [[3043 1280]
 [1224 3099]]
Accuracy on test set:    0.7103863058061531
Sensitivity:    0.7168632893823733 	 Specificity:    0.703909322229933
Precision  : 0.7076958209636903
Area Under Curve:    0.710386305806153
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6090 - accuracy: 0.6639 - val_loss: 0.5669 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7102 - val_loss: 0.5555 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7216 - val_loss: 0.5491 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7276 - val_loss: 0.5435 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5287 - accuracy: 0.7324 - val_loss: 0.5416 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5207 - accuracy: 0.7378 - val_loss: 0.5404 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7434 - val_loss: 0.5357 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7458 - val_loss: 0.5408 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5032 - accuracy: 0.7493 - val_loss: 0.5423 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7497 - val_loss: 0.5405 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4922 - accuracy: 0.7557
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7559 - val_loss: 0.5426 - val_accuracy: 0.7192 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.4304868964038194
Confusion Matrix :
 [[2766 1557]
 [ 925 3398]]
Accuracy on test set:    0.7129308350682396
Sensitivity:    0.786028221142725 	 Specificity:    0.6398334489937544
Precision  : 0.6857719475277497
Area Under Curve:    0.7129308350682396
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6028 - accuracy: 0.6703 - val_loss: 0.5640 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5583 - accuracy: 0.7131 - val_loss: 0.5524 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7246 - val_loss: 0.5447 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7301 - val_loss: 0.5455 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7349 - val_loss: 0.5514 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7412 - val_loss: 0.5453 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7426 - val_loss: 0.5417 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7490 - val_loss: 0.5460 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4999 - accuracy: 0.7526 - val_loss: 0.5410 - val_accuracy: 0.7277 - lr: 0.0010

Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4938 - accuracy: 0.7539 - val_loss: 0.5412 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4869 - accuracy: 0.7599 - val_loss: 0.5519 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7615 - val_loss: 0.5469 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4755 - accuracy: 0.7652 - val_loss: 0.5474 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4698 - accuracy: 0.7695
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4698 - accuracy: 0.7694 - val_loss: 0.5526 - val_accuracy: 0.7230 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.45595699742897494
Confusion Matrix :
 [[3169 1154]
 [1198 3125]]
Accuracy on test set:    0.7279666897987509
Sensitivity:    0.7228776312745778 	 Specificity:    0.7330557483229239
Precision  : 0.7303108202851133
Area Under Curve:    0.7279666897987509
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6059 - accuracy: 0.6674 - val_loss: 0.5628 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5565 - accuracy: 0.7149 - val_loss: 0.5488 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7240 - val_loss: 0.5419 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7319 - val_loss: 0.5421 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5252 - accuracy: 0.7365 - val_loss: 0.5457 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7402 - val_loss: 0.5458 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7463 - val_loss: 0.5407 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5062 - accuracy: 0.7486 - val_loss: 0.5452 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5003 - accuracy: 0.7517 - val_loss: 0.5455 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7549 - val_loss: 0.5435 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7582 - val_loss: 0.5392 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 12/400
252/274 [==========================>...] - ETA: 0s - loss: 0.4835 - accuracy: 0.7630
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7623 - val_loss: 0.5380 - val_accuracy: 0.7240 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4370191390978133
Confusion Matrix :
 [[3140 1183]
 [1251 3072]]
Accuracy on test set:    0.7184825352764284
Sensitivity:    0.710617626648161 	 Specificity:    0.7263474439046959
Precision  : 0.7219741480611046
Area Under Curve:    0.7184825352764284
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6121 - accuracy: 0.6685 - val_loss: 0.5613 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5586 - accuracy: 0.7108 - val_loss: 0.5503 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7251 - val_loss: 0.5378 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5304 - accuracy: 0.7319 - val_loss: 0.5385 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5220 - accuracy: 0.7373 - val_loss: 0.5459 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7413 - val_loss: 0.5340 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7467 - val_loss: 0.5331 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7500 - val_loss: 0.5349 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7543 - val_loss: 0.5357 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7575 - val_loss: 0.5339 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7619 - val_loss: 0.5380 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4726 - accuracy: 0.7674 - val_loss: 0.5423 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 13/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4688 - accuracy: 0.7723
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4694 - accuracy: 0.7723 - val_loss: 0.5405 - val_accuracy: 0.7316 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4402183566244352
Confusion Matrix :
 [[2886 1437]
 [ 993 3330]]
Accuracy on test set:    0.7189451769604441
Sensitivity:    0.7702984038861902 	 Specificity:    0.6675919500346982
Precision  : 0.6985525487728131
Area Under Curve:    0.718945176960444
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6050 - accuracy: 0.6670 - val_loss: 0.5658 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5573 - accuracy: 0.7105 - val_loss: 0.5431 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7238 - val_loss: 0.5384 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7319 - val_loss: 0.5371 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7370 - val_loss: 0.5328 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7420 - val_loss: 0.5324 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7449 - val_loss: 0.5316 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5022 - accuracy: 0.7500 - val_loss: 0.5356 - val_accuracy: 0.7328 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4936 - accuracy: 0.7560 - val_loss: 0.5360 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7570 - val_loss: 0.5330 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7612 - val_loss: 0.5413 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4774 - accuracy: 0.7648 - val_loss: 0.5378 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 13/400

262/274 [===========================>..] - ETA: 0s - loss: 0.4677 - accuracy: 0.7709
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4679 - accuracy: 0.7706 - val_loss: 0.5417 - val_accuracy: 0.7249 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.4345495038056287
Confusion Matrix :
 [[3188 1135]
 [1311 3012]]
Accuracy on test set:    0.7170946102243813
Sensitivity:    0.6967383761276891 	 Specificity:    0.7374508443210733
Precision  : 0.7263081745840366
Area Under Curve:    0.7170946102243813
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6030 - accuracy: 0.6705 - val_loss: 0.5615 - val_accuracy: 0.7070 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7133 - val_loss: 0.5470 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7242 - val_loss: 0.5462 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7295 - val_loss: 0.5391 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7357 - val_loss: 0.5401 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7415 - val_loss: 0.5421 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5102 - accuracy: 0.7439 - val_loss: 0.5413 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7511 - val_loss: 0.5364 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7531 - val_loss: 0.5388 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7553 - val_loss: 0.5464 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4865 - accuracy: 0.7593 - val_loss: 0.5396 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4818 - accuracy: 0.7627 - val_loss: 0.5396 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7656 - val_loss: 0.5423 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4699 - accuracy: 0.7697 - val_loss: 0.5456 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4629 - accuracy: 0.7734 - val_loss: 0.5479 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4583 - accuracy: 0.7751
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4584 - accuracy: 0.7746 - val_loss: 0.5547 - val_accuracy: 0.7226 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.4393841822833038
Confusion Matrix :
 [[3257 1066]
 [1362 2961]]
Accuracy on test set:    0.719176497802452
Sensitivity:    0.684941013185288 	 Specificity:    0.753411982419616
Precision  : 0.7352868140054631
Area Under Curve:    0.719176497802452
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6146 - accuracy: 0.6578 - val_loss: 0.5706 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5643 - accuracy: 0.7066 - val_loss: 0.5505 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5487 - accuracy: 0.7201 - val_loss: 0.5473 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7282 - val_loss: 0.5401 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5301 - accuracy: 0.7311 - val_loss: 0.5453 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7364 - val_loss: 0.5354 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7389 - val_loss: 0.5370 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7433 - val_loss: 0.5320 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5063 - accuracy: 0.7477 - val_loss: 0.5423 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7499 - val_loss: 0.5319 - val_accuracy: 0.7345 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4954 - accuracy: 0.7537 - val_loss: 0.5331 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4898 - accuracy: 0.7556 - val_loss: 0.5382 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4845 - accuracy: 0.7589 - val_loss: 0.5356 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7619 - val_loss: 0.5409 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 15/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4712 - accuracy: 0.7681
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4706 - accuracy: 0.7681 - val_loss: 0.5410 - val_accuracy: 0.7345 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.47981786124954734
Confusion Matrix :
 [[3076 1247]
 [1005 3318]]
Accuracy on test set:    0.7395327318991441
Sensitivity:    0.7675225537820958 	 Specificity:    0.7115429100161924
Precision  : 0.7268346111719606
Area Under Curve:    0.7395327318991441
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6019 - accuracy: 0.6688 - val_loss: 0.5609 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5593 - accuracy: 0.7111 - val_loss: 0.5467 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7216 - val_loss: 0.5422 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7287 - val_loss: 0.5393 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7348 - val_loss: 0.5385 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7378 - val_loss: 0.5341 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7411 - val_loss: 0.5374 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7442 - val_loss: 0.5361 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7516 - val_loss: 0.5389 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7536 - val_loss: 0.5366 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4875 - accuracy: 0.7606
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7603 - val_loss: 0.5362 - val_accuracy: 0.7267 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4707111659658766
Confusion Matrix :
 [[3085 1238]
 [1052 3271]]
Accuracy on test set:    0.7351376359009947
Sensitivity:    0.7566504742077261 	 Specificity:    0.7136247975942632
Precision  : 0.7254380128631626
Area Under Curve:    0.7351376359009947
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6141 - accuracy: 0.6572 - val_loss: 0.5740 - val_accuracy: 0.7059 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5688 - accuracy: 0.7058 - val_loss: 0.5536 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5522 - accuracy: 0.7176 - val_loss: 0.5480 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7250 - val_loss: 0.5485 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7297 - val_loss: 0.5440 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5263 - accuracy: 0.7355 - val_loss: 0.5410 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7385 - val_loss: 0.5455 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7414 - val_loss: 0.5415 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7466 - val_loss: 0.5432 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7512 - val_loss: 0.5401 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4966 - accuracy: 0.7541 - val_loss: 0.5404 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7567 - val_loss: 0.5466 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7574 - val_loss: 0.5480 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4812 - accuracy: 0.7647
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4820 - accuracy: 0.7642 - val_loss: 0.5470 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4890436761784007
Confusion Matrix :
 [[3243 1080]
 [1129 3194]]
Accuracy on test set:    0.7445061300023132
Sensitivity:    0.7388387693731205 	 Specificity:    0.7501734906315058
Precision  : 0.7473093121197941
Area Under Curve:    0.7445061300023132
(8646, 4352) (8646,)
Mean MCC = 0.4498 + 0.0217 and Mean AUC = 0.7244 + 0.0111
Mean Sensitivity = 0.7351 + 0.0323 and Mean Specificity = 0.7137 + 0.0342 and Mean Accuracy = 0.7244 + 0.0111
Mean Precision = 0.7205 + 0.0173





Seed   : 763927
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6010 - accuracy: 0.6733 - val_loss: 0.5642 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5537 - accuracy: 0.7161 - val_loss: 0.5560 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7266 - val_loss: 0.5514 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7342 - val_loss: 0.5512 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7392 - val_loss: 0.5417 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7435 - val_loss: 0.5424 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7464 - val_loss: 0.5433 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7505 - val_loss: 0.5416 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7551 - val_loss: 0.5413 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4877 - accuracy: 0.7584 - val_loss: 0.5450 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7618 - val_loss: 0.5415 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4755 - accuracy: 0.7655 - val_loss: 0.5497 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4697 - accuracy: 0.7683 - val_loss: 0.5479 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4650 - accuracy: 0.7711 - val_loss: 0.5492 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4575 - accuracy: 0.7766 - val_loss: 0.5499 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 16/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4518 - accuracy: 0.7800
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4528 - accuracy: 0.7795 - val_loss: 0.5711 - val_accuracy: 0.7104 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4021115771525596
Confusion Matrix :
 [[2436 1887]
 [ 758 3565]]
Accuracy on test set:    0.6940781864445986
Sensitivity:    0.8246588017580384 	 Specificity:    0.563497571131159
Precision  : 0.6538884812912693
Area Under Curve:    0.6940781864445988
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6257 - accuracy: 0.6490 - val_loss: 0.5751 - val_accuracy: 0.6952 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5656 - accuracy: 0.7071 - val_loss: 0.5631 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5507 - accuracy: 0.7183 - val_loss: 0.5556 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7265 - val_loss: 0.5503 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7286 - val_loss: 0.5515 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5263 - accuracy: 0.7354 - val_loss: 0.5615 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5213 - accuracy: 0.7372 - val_loss: 0.5461 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7398 - val_loss: 0.5510 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7431 - val_loss: 0.5458 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5037 - accuracy: 0.7494 - val_loss: 0.5531 - val_accuracy: 0.7092 - lr: 0.0010

Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7526 - val_loss: 0.5475 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7560 - val_loss: 0.5596 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4852 - accuracy: 0.7604 - val_loss: 0.5507 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4838 - accuracy: 0.7601
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4837 - accuracy: 0.7600 - val_loss: 0.5549 - val_accuracy: 0.7170 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.43002913567418577
Confusion Matrix :
 [[2947 1376]
 [1092 3231]]
Accuracy on test set:    0.7145500809622947
Sensitivity:    0.7473976405274115 	 Specificity:    0.6817025213971779
Precision  : 0.7013240720642501
Area Under Curve:    0.7145500809622947
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6074 - accuracy: 0.6664 - val_loss: 0.5746 - val_accuracy: 0.6961 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5605 - accuracy: 0.7102 - val_loss: 0.5555 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7219 - val_loss: 0.5580 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7267 - val_loss: 0.5501 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7326 - val_loss: 0.5485 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7323 - val_loss: 0.5486 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5200 - accuracy: 0.7377 - val_loss: 0.5462 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5136 - accuracy: 0.7402 - val_loss: 0.5462 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5073 - accuracy: 0.7455
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7448 - val_loss: 0.5487 - val_accuracy: 0.7200 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.441521855691372
Confusion Matrix :
 [[2780 1543]
 [ 893 3430]]
Accuracy on test set:    0.7182512144344205
Sensitivity:    0.7934304880869766 	 Specificity:    0.6430719407818645
Precision  : 0.6897245123667806
Area Under Curve:    0.7182512144344204
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5982 - accuracy: 0.6749 - val_loss: 0.5636 - val_accuracy: 0.7055 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5533 - accuracy: 0.7161 - val_loss: 0.5518 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7259 - val_loss: 0.5443 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5276 - accuracy: 0.7333 - val_loss: 0.5429 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5212 - accuracy: 0.7375 - val_loss: 0.5412 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5120 - accuracy: 0.7445 - val_loss: 0.5446 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7472 - val_loss: 0.5395 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7531 - val_loss: 0.5422 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4924 - accuracy: 0.7570 - val_loss: 0.5433 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4865 - accuracy: 0.7606 - val_loss: 0.5444 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4788 - accuracy: 0.7663 - val_loss: 0.5417 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4728 - accuracy: 0.7679 - val_loss: 0.5479 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 13/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4673 - accuracy: 0.7723
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4669 - accuracy: 0.7723 - val_loss: 0.5547 - val_accuracy: 0.7226 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.4209322295862915
Confusion Matrix :
 [[2753 1570]
 [ 952 3371]]
Accuracy on test set:    0.7083044182280823
Sensitivity:    0.7797825584085126 	 Specificity:    0.6368262780476521
Precision  : 0.6822505565674964
Area Under Curve:    0.7083044182280824
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6057 - accuracy: 0.6661 - val_loss: 0.5602 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5572 - accuracy: 0.7141 - val_loss: 0.5520 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7255 - val_loss: 0.5543 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7332 - val_loss: 0.5416 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7384 - val_loss: 0.5363 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7400 - val_loss: 0.5365 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7455 - val_loss: 0.5353 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7483 - val_loss: 0.5404 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7537 - val_loss: 0.5470 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7564 - val_loss: 0.5412 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4834 - accuracy: 0.7596 - val_loss: 0.5438 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4783 - accuracy: 0.7650
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4789 - accuracy: 0.7646 - val_loss: 0.5436 - val_accuracy: 0.7194 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4300457418796161
Confusion Matrix :
 [[3070 1253]
 [1211 3112]]
Accuracy on test set:    0.7150127226463104
Sensitivity:    0.7198704603284756 	 Specificity:    0.7101549849641453
Precision  : 0.7129438717067583
Area Under Curve:    0.7150127226463104
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6079 - accuracy: 0.6673 - val_loss: 0.5607 - val_accuracy: 0.7101 - lr: 0.0010

Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7119 - val_loss: 0.5457 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7234 - val_loss: 0.5451 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7293 - val_loss: 0.5389 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7329 - val_loss: 0.5376 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7379 - val_loss: 0.5388 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5105 - accuracy: 0.7435 - val_loss: 0.5401 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7465 - val_loss: 0.5386 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7506 - val_loss: 0.5389 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4942 - accuracy: 0.7549 - val_loss: 0.5399 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4877 - accuracy: 0.7588 - val_loss: 0.5426 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7611 - val_loss: 0.5409 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7638 - val_loss: 0.5474 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4702 - accuracy: 0.7666
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4704 - accuracy: 0.7662 - val_loss: 0.5495 - val_accuracy: 0.7221 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4310364588805802
Confusion Matrix :
 [[2872 1451]
 [1018 3305]]
Accuracy on test set:    0.7144344205412908
Sensitivity:    0.7645153828359935 	 Specificity:    0.664353458246588
Precision  : 0.6949116904962153
Area Under Curve:    0.7144344205412907
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6004 - accuracy: 0.6745 - val_loss: 0.5690 - val_accuracy: 0.7032 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5598 - accuracy: 0.7107 - val_loss: 0.5540 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7213 - val_loss: 0.5516 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7288 - val_loss: 0.5419 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7336 - val_loss: 0.5409 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5211 - accuracy: 0.7385 - val_loss: 0.5449 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5146 - accuracy: 0.7424 - val_loss: 0.5424 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5073 - accuracy: 0.7462 - val_loss: 0.5399 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5017 - accuracy: 0.7512 - val_loss: 0.5397 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4959 - accuracy: 0.7529 - val_loss: 0.5485 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7551 - val_loss: 0.5393 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4855 - accuracy: 0.7589 - val_loss: 0.5403 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4796 - accuracy: 0.7625
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7624 - val_loss: 0.5487 - val_accuracy: 0.7188 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4574378101535329
Confusion Matrix :
 [[2846 1477]
 [ 887 3436]]
Accuracy on test set:    0.7265787647467037
Sensitivity:    0.7948184131390238 	 Specificity:    0.6583391163543836
Precision  : 0.6993690209647873
Area Under Curve:    0.7265787647467035
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6051 - accuracy: 0.6712 - val_loss: 0.5696 - val_accuracy: 0.7029 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7110 - val_loss: 0.5414 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7225 - val_loss: 0.5472 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5317 - accuracy: 0.7309 - val_loss: 0.5357 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7358 - val_loss: 0.5411 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7387 - val_loss: 0.5347 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7467 - val_loss: 0.5316 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7471 - val_loss: 0.5295 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7549 - val_loss: 0.5360 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7582 - val_loss: 0.5357 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4885 - accuracy: 0.7595
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7592 - val_loss: 0.5354 - val_accuracy: 0.7289 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.4502098523898224
Confusion Matrix :
 [[3008 1315]
 [1065 3258]]
Accuracy on test set:    0.7247281980106408
Sensitivity:    0.7536433032616239 	 Specificity:    0.6958130927596576
Precision  : 0.7124425978569867
Area Under Curve:    0.7247281980106407
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6100 - accuracy: 0.6622 - val_loss: 0.5682 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5647 - accuracy: 0.7073 - val_loss: 0.5488 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7184 - val_loss: 0.5409 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7280 - val_loss: 0.5403 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5288 - accuracy: 0.7336 - val_loss: 0.5415 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7372 - val_loss: 0.5455 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7395 - val_loss: 0.5379 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7459 - val_loss: 0.5349 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7483 - val_loss: 0.5435 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7533 - val_loss: 0.5430 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4891 - accuracy: 0.7568 - val_loss: 0.5416 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4818 - accuracy: 0.7610
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4830 - accuracy: 0.7604 - val_loss: 0.5504 - val_accuracy: 0.7187 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4820662155154953
Confusion Matrix :
 [[2903 1420]
 [ 838 3485]]
Accuracy on test set:    0.7388387693731205
Sensitivity:    0.8061531343974092 	 Specificity:    0.6715244043488319
Precision  : 0.7104994903160041
Area Under Curve:    0.7388387693731204
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6137 - accuracy: 0.6624 - val_loss: 0.5653 - val_accuracy: 0.7021 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5674 - accuracy: 0.7046 - val_loss: 0.5558 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5518 - accuracy: 0.7178 - val_loss: 0.5481 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7237 - val_loss: 0.5426 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7284 - val_loss: 0.5411 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5267 - accuracy: 0.7337 - val_loss: 0.5393 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5206 - accuracy: 0.7380 - val_loss: 0.5381 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5127 - accuracy: 0.7430 - val_loss: 0.5444 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7467 - val_loss: 0.5375 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7471 - val_loss: 0.5393 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7505 - val_loss: 0.5405 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7555 - val_loss: 0.5458 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7569 - val_loss: 0.5485 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 14/400
257/274 [===========================>..] - ETA: 0s - loss: 0.4816 - accuracy: 0.7590
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4819 - accuracy: 0.7587 - val_loss: 0.5472 - val_accuracy: 0.7210 - lr: 0.0010
271/271 [==============================] - 0s 667us/step
Independent Testing Matthews Correlation:  0.5174714244861347
Confusion Matrix :
 [[3269 1054]
 [1032 3291]]
Accuracy on test set:    0.758732361785797
Sensitivity:    0.7612768910478834 	 Specificity:    0.7561878325237104
Precision  : 0.757422324510932
Area Under Curve:    0.758732361785797
(8646, 4352) (8646,)
Mean MCC = 0.4463 + 0.0314 and Mean AUC = 0.7214 + 0.0167
Mean Sensitivity = 0.7746 + 0.0296 and Mean Specificity = 0.6681 + 0.0481 and Mean Accuracy = 0.7214 + 0.0167
Mean Precision = 0.7015 + 0.0251





Seed   : 523732
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6097 - accuracy: 0.6662 - val_loss: 0.5675 - val_accuracy: 0.7003 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7126 - val_loss: 0.5546 - val_accuracy: 0.7059 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7259 - val_loss: 0.5479 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7308 - val_loss: 0.5423 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7350 - val_loss: 0.5460 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7392 - val_loss: 0.5400 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7452 - val_loss: 0.5399 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7481 - val_loss: 0.5385 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7544 - val_loss: 0.5443 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7559 - val_loss: 0.5421 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4868 - accuracy: 0.7575 - val_loss: 0.5479 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7631 - val_loss: 0.5515 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 13/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4732 - accuracy: 0.7657
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4729 - accuracy: 0.7662 - val_loss: 0.5665 - val_accuracy: 0.7192 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4110460206932481
Confusion Matrix :
 [[2717 1606]
 [ 960 3363]]
Accuracy on test set:    0.7032153597039094
Sensitivity:    0.7779319916724496 	 Specificity:    0.628498727735369
Precision  : 0.6767961360434696
Area Under Curve:    0.7032153597039092
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.5988 - accuracy: 0.6734 - val_loss: 0.5653 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5535 - accuracy: 0.7143 - val_loss: 0.5530 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7266 - val_loss: 0.5482 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5287 - accuracy: 0.7333 - val_loss: 0.5452 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5210 - accuracy: 0.7392 - val_loss: 0.5442 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7423 - val_loss: 0.5442 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7482 - val_loss: 0.5523 - val_accuracy: 0.7177 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7508 - val_loss: 0.5422 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7563 - val_loss: 0.5438 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7579 - val_loss: 0.5474 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7638 - val_loss: 0.5457 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4753 - accuracy: 0.7666 - val_loss: 0.5476 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4684 - accuracy: 0.7730 - val_loss: 0.5544 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4612 - accuracy: 0.7743 - val_loss: 0.5493 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4562 - accuracy: 0.7763 - val_loss: 0.5594 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 3ms/step - loss: 0.4498 - accuracy: 0.7794 - val_loss: 0.5542 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4420 - accuracy: 0.7847 - val_loss: 0.5569 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4357 - accuracy: 0.7892 - val_loss: 0.5629 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4305 - accuracy: 0.7911 - val_loss: 0.5668 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4256 - accuracy: 0.7931 - val_loss: 0.5670 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4182 - accuracy: 0.7968 - val_loss: 0.5897 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 22/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4144 - accuracy: 0.7994
Epoch 22: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4146 - accuracy: 0.7994 - val_loss: 0.5898 - val_accuracy: 0.7140 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.41373807436982846
Confusion Matrix :
 [[3111 1212]
 [1323 3000]]
Accuracy on test set:    0.7068008327550312
Sensitivity:    0.6939625260235948 	 Specificity:    0.7196391394864677
Precision  : 0.7122507122507122
Area Under Curve:    0.7068008327550314
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6021 - accuracy: 0.6717 - val_loss: 0.5694 - val_accuracy: 0.6969 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7109 - val_loss: 0.5565 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7223 - val_loss: 0.5589 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7298 - val_loss: 0.5475 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5251 - accuracy: 0.7357 - val_loss: 0.5468 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7398 - val_loss: 0.5488 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7435 - val_loss: 0.5474 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7484 - val_loss: 0.5494 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5025 - accuracy: 0.7508 - val_loss: 0.5508 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7523 - val_loss: 0.5514 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7552 - val_loss: 0.5444 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4827 - accuracy: 0.7610 - val_loss: 0.5462 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4753 - accuracy: 0.7636 - val_loss: 0.5551 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4735 - accuracy: 0.7650 - val_loss: 0.5556 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4679 - accuracy: 0.7693 - val_loss: 0.5516 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4617 - accuracy: 0.7718
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4621 - accuracy: 0.7717 - val_loss: 0.5556 - val_accuracy: 0.7182 - lr: 0.0010
271/271 [==============================] - 0s 668us/step
Independent Testing Matthews Correlation:  0.4455923814162229
Confusion Matrix :
 [[3018 1305]
 [1094 3229]]
Accuracy on test set:    0.722530650011566
Sensitivity:    0.7469349988433958 	 Specificity:    0.6981263011797363
Precision  : 0.7121746801940891
Area Under Curve:    0.722530650011566
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6010 - accuracy: 0.6699 - val_loss: 0.5753 - val_accuracy: 0.6956 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5558 - accuracy: 0.7146 - val_loss: 0.5532 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7259 - val_loss: 0.5449 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7286 - val_loss: 0.5449 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5225 - accuracy: 0.7388 - val_loss: 0.5430 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7390 - val_loss: 0.5448 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5083 - accuracy: 0.7469 - val_loss: 0.5422 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7473 - val_loss: 0.5452 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7528 - val_loss: 0.5538 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4933 - accuracy: 0.7550 - val_loss: 0.5460 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4884 - accuracy: 0.7562 - val_loss: 0.5476 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7614 - val_loss: 0.5568 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7643 - val_loss: 0.5512 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4673 - accuracy: 0.7693 - val_loss: 0.5511 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4635 - accuracy: 0.7712
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4639 - accuracy: 0.7708 - val_loss: 0.5599 - val_accuracy: 0.7221 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.45050916328832596
Confusion Matrix :
 [[2884 1439]
 [ 949 3374]]
Accuracy on test set:    0.7238029146426093
Sensitivity:    0.7804765209345362 	 Specificity:    0.6671293083506824
Precision  : 0.7010180760440474
Area Under Curve:    0.7238029146426093
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6055 - accuracy: 0.6685 - val_loss: 0.5645 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5620 - accuracy: 0.7107 - val_loss: 0.5586 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7223 - val_loss: 0.5513 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7257 - val_loss: 0.5570 - val_accuracy: 0.7092 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5300 - accuracy: 0.7318 - val_loss: 0.5496 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7362 - val_loss: 0.5455 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7408 - val_loss: 0.5454 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7446 - val_loss: 0.5475 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7467 - val_loss: 0.5485 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7475 - val_loss: 0.5500 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4954 - accuracy: 0.7531
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4959 - accuracy: 0.7529 - val_loss: 0.5465 - val_accuracy: 0.7167 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.44929393960457675
Confusion Matrix :
 [[3053 1270]
 [1112 3211]]
Accuracy on test set:    0.7244968771686329
Sensitivity:    0.7427712236872542 	 Specificity:    0.7062225306500116
Precision  : 0.7165811202856506
Area Under Curve:    0.7244968771686329
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5997 - accuracy: 0.6746 - val_loss: 0.5648 - val_accuracy: 0.7033 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7146 - val_loss: 0.5511 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7240 - val_loss: 0.5437 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5297 - accuracy: 0.7329 - val_loss: 0.5455 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5218 - accuracy: 0.7359 - val_loss: 0.5440 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7425 - val_loss: 0.5437 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7459 - val_loss: 0.5434 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7512 - val_loss: 0.5459 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7538 - val_loss: 0.5482 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4890 - accuracy: 0.7573 - val_loss: 0.5484 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7613 - val_loss: 0.5488 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7664 - val_loss: 0.5540 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4700 - accuracy: 0.7686 - val_loss: 0.5555 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4626 - accuracy: 0.7729
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4640 - accuracy: 0.7722 - val_loss: 0.5524 - val_accuracy: 0.7149 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.45342292809777274
Confusion Matrix :
 [[3115 1208]
 [1155 3168]]
Accuracy on test set:    0.7266944251677077
Sensitivity:    0.732824427480916 	 Specificity:    0.7205644228544992
Precision  : 0.7239488117001828
Area Under Curve:    0.7266944251677075
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6040 - accuracy: 0.6706 - val_loss: 0.5636 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7134 - val_loss: 0.5521 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7238 - val_loss: 0.5489 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7290 - val_loss: 0.5504 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7364 - val_loss: 0.5436 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7394 - val_loss: 0.5675 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5120 - accuracy: 0.7438 - val_loss: 0.5457 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7465 - val_loss: 0.5440 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7516 - val_loss: 0.5421 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4933 - accuracy: 0.7534 - val_loss: 0.5467 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4875 - accuracy: 0.7580 - val_loss: 0.5498 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4811 - accuracy: 0.7619 - val_loss: 0.5495 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4778 - accuracy: 0.7626 - val_loss: 0.5666 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4691 - accuracy: 0.7695 - val_loss: 0.5518 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4625 - accuracy: 0.7718 - val_loss: 0.5541 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4588 - accuracy: 0.7748 - val_loss: 0.5672 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 17/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4525 - accuracy: 0.7767 - val_loss: 0.5615 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4453 - accuracy: 0.7807 - val_loss: 0.5725 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4428 - accuracy: 0.7835 - val_loss: 0.5816 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 20/400
257/274 [===========================>..] - ETA: 0s - loss: 0.4379 - accuracy: 0.7843
Epoch 20: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4382 - accuracy: 0.7838 - val_loss: 0.5765 - val_accuracy: 0.7115 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4404354879252656
Confusion Matrix :
 [[2939 1384]
 [1041 3282]]
Accuracy on test set:    0.7195234790654638
Sensitivity:    0.7591950034698126 	 Specificity:    0.6798519546611149
Precision  : 0.7033861980282897
Area Under Curve:    0.7195234790654638
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6056 - accuracy: 0.6684 - val_loss: 0.5658 - val_accuracy: 0.7016 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5577 - accuracy: 0.7119 - val_loss: 0.5500 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7254 - val_loss: 0.5456 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7284 - val_loss: 0.5521 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7343 - val_loss: 0.5491 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7407 - val_loss: 0.5410 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7451 - val_loss: 0.5446 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7511 - val_loss: 0.5467 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7531 - val_loss: 0.5485 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7544 - val_loss: 0.5565 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7601 - val_loss: 0.5544 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4810 - accuracy: 0.7627
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7625 - val_loss: 0.5550 - val_accuracy: 0.7177 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.45445401822017195
Confusion Matrix :
 [[2950 1373]
 [ 993 3330]]
Accuracy on test set:    0.7263474439046959
Sensitivity:    0.7702984038861902 	 Specificity:    0.6823964839232015
Precision  : 0.7080586859451414
Area Under Curve:    0.7263474439046959
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6242 - accuracy: 0.6543 - val_loss: 0.5779 - val_accuracy: 0.6929 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5649 - accuracy: 0.7054 - val_loss: 0.5618 - val_accuracy: 0.7059 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5487 - accuracy: 0.7187 - val_loss: 0.5502 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7274 - val_loss: 0.5503 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7315 - val_loss: 0.5477 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7378 - val_loss: 0.5467 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5149 - accuracy: 0.7416 - val_loss: 0.5439 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7490 - val_loss: 0.5484 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7500 - val_loss: 0.5459 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7521 - val_loss: 0.5535 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7538 - val_loss: 0.5550 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4840 - accuracy: 0.7612
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4844 - accuracy: 0.7609 - val_loss: 0.5530 - val_accuracy: 0.7210 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.46873754106439836
Confusion Matrix :
 [[3329  994]
 [1308 3015]]
Accuracy on test set:    0.7337497108489475
Sensitivity:    0.6974323386537127 	 Specificity:    0.7700670830441823
Precision  : 0.7520578697929658
Area Under Curve:    0.7337497108489475
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6101 - accuracy: 0.6621 - val_loss: 0.5720 - val_accuracy: 0.7008 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5638 - accuracy: 0.7076 - val_loss: 0.5589 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7214 - val_loss: 0.5530 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7277 - val_loss: 0.5547 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5281 - accuracy: 0.7344 - val_loss: 0.5536 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7359 - val_loss: 0.5508 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7410 - val_loss: 0.5504 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7446 - val_loss: 0.5511 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7457 - val_loss: 0.5517 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7520 - val_loss: 0.5537 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7563 - val_loss: 0.5507 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4889 - accuracy: 0.7593 - val_loss: 0.5555 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4839 - accuracy: 0.7611 - val_loss: 0.5551 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4755 - accuracy: 0.7652 - val_loss: 0.5590 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7685 - val_loss: 0.5639 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 16/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4662 - accuracy: 0.7722
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4650 - accuracy: 0.7728 - val_loss: 0.5648 - val_accuracy: 0.7178 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4936587661278194
Confusion Matrix :
 [[3209 1114]
 [1075 3248]]
Accuracy on test set:    0.7468193384223919
Sensitivity:    0.7513300948415452 	 Specificity:    0.7423085820032385
Precision  : 0.744612563044475
Area Under Curve:    0.7468193384223918
(8646, 4352) (8646,)
Mean MCC = 0.4481 + 0.0228 and Mean AUC = 0.7234 + 0.0117
Mean Sensitivity = 0.7453 + 0.0287 and Mean Specificity = 0.7015 + 0.0380 and Mean Accuracy = 0.7234 + 0.0117
Mean Precision = 0.7151 + 0.0205





Seed   : 19415
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6104 - accuracy: 0.6634 - val_loss: 0.5591 - val_accuracy: 0.7055 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7122 - val_loss: 0.5498 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7228 - val_loss: 0.5458 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7314 - val_loss: 0.5448 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.7354 - val_loss: 0.5389 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7429 - val_loss: 0.5391 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5063 - accuracy: 0.7450 - val_loss: 0.5484 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7507 - val_loss: 0.5389 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7543 - val_loss: 0.5434 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7569 - val_loss: 0.5372 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7624 - val_loss: 0.5438 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4749 - accuracy: 0.7649 - val_loss: 0.5440 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4646 - accuracy: 0.7720 - val_loss: 0.5428 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4591 - accuracy: 0.7740 - val_loss: 0.5459 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4554 - accuracy: 0.7755 - val_loss: 0.5625 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4477 - accuracy: 0.7810
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4472 - accuracy: 0.7813 - val_loss: 0.5550 - val_accuracy: 0.7233 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.43707582249216764
Confusion Matrix :
 [[3020 1303]
 [1132 3191]]
Accuracy on test set:    0.7183668748554245
Sensitivity:    0.7381448068470969 	 Specificity:    0.6985889428637521
Precision  : 0.710057854917668
Area Under Curve:    0.7183668748554244
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6043 - accuracy: 0.6713 - val_loss: 0.5650 - val_accuracy: 0.7052 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5562 - accuracy: 0.7122 - val_loss: 0.5549 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7244 - val_loss: 0.5434 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5307 - accuracy: 0.7314 - val_loss: 0.5467 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5240 - accuracy: 0.7343 - val_loss: 0.5439 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7418 - val_loss: 0.5391 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7434 - val_loss: 0.5404 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7505 - val_loss: 0.5387 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4950 - accuracy: 0.7545 - val_loss: 0.5375 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4889 - accuracy: 0.7578 - val_loss: 0.5498 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4827 - accuracy: 0.7643
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.7640 - val_loss: 0.5455 - val_accuracy: 0.7226 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.43862516882380304
Confusion Matrix :
 [[3139 1184]
 [1243 3080]]
Accuracy on test set:    0.7192921582234559
Sensitivity:    0.712468193384224 	 Specificity:    0.7261161230626879
Precision  : 0.7223264540337712
Area Under Curve:    0.719292158223456
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6062 - accuracy: 0.6667 - val_loss: 0.5601 - val_accuracy: 0.7055 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5582 - accuracy: 0.7114 - val_loss: 0.5533 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7232 - val_loss: 0.5476 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7310 - val_loss: 0.5453 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7346 - val_loss: 0.5401 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7386 - val_loss: 0.5380 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7425 - val_loss: 0.5377 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7454 - val_loss: 0.5453 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7501 - val_loss: 0.5466 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4965 - accuracy: 0.7532
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7534 - val_loss: 0.5377 - val_accuracy: 0.7222 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.4499598487544576
Confusion Matrix :
 [[2945 1378]
 [1007 3316]]
Accuracy on test set:    0.7241498959056211
Sensitivity:    0.76705991209808 	 Specificity:    0.6812398797131621
Precision  : 0.7064337452066468
Area Under Curve:    0.724149895905621
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6304 - accuracy: 0.6520 - val_loss: 0.5896 - val_accuracy: 0.6727 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5680 - accuracy: 0.7039 - val_loss: 0.5520 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5523 - accuracy: 0.7162 - val_loss: 0.5437 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7238 - val_loss: 0.5398 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7271 - val_loss: 0.5382 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5240 - accuracy: 0.7347 - val_loss: 0.5458 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5199 - accuracy: 0.7354 - val_loss: 0.5375 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7417 - val_loss: 0.5428 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
265/274 [============================>.] - ETA: 0s - loss: 0.5063 - accuracy: 0.7443
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7439 - val_loss: 0.5404 - val_accuracy: 0.7200 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.42446435223510626
Confusion Matrix :
 [[2682 1641]
 [ 876 3447]]
Accuracy on test set:    0.7088827203331021
Sensitivity:    0.7973629424011104 	 Specificity:    0.6204024982650936
Precision  : 0.6774764150943396
Area Under Curve:    0.7088827203331021
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6026 - accuracy: 0.6683 - val_loss: 0.5645 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7116 - val_loss: 0.5468 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7230 - val_loss: 0.5455 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7274 - val_loss: 0.5477 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7330 - val_loss: 0.5405 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7370 - val_loss: 0.5381 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5149 - accuracy: 0.7401 - val_loss: 0.5381 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7472 - val_loss: 0.5402 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7479 - val_loss: 0.5400 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7517 - val_loss: 0.5399 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7542 - val_loss: 0.5404 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4883 - accuracy: 0.7562 - val_loss: 0.5446 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4832 - accuracy: 0.7596 - val_loss: 0.5423 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4778 - accuracy: 0.7636 - val_loss: 0.5463 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4738 - accuracy: 0.7643 - val_loss: 0.5484 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4715 - accuracy: 0.7630 - val_loss: 0.5524 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4657 - accuracy: 0.7651 - val_loss: 0.5532 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4610 - accuracy: 0.7698 - val_loss: 0.5543 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4570 - accuracy: 0.7721 - val_loss: 0.5563 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 20/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4486 - accuracy: 0.7775
Epoch 20: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4500 - accuracy: 0.7767 - val_loss: 0.5561 - val_accuracy: 0.7194 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4259586193097271
Confusion Matrix :
 [[2751 1572]
 [ 930 3393]]
Accuracy on test set:    0.710617626648161
Sensitivity:    0.7848716169326856 	 Specificity:    0.6363636363636364
Precision  : 0.6833836858006043
Area Under Curve:    0.710617626648161
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6010 - accuracy: 0.6705 - val_loss: 0.5680 - val_accuracy: 0.7017 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7138 - val_loss: 0.5475 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7256 - val_loss: 0.5426 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5304 - accuracy: 0.7321 - val_loss: 0.5382 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5264 - accuracy: 0.7341 - val_loss: 0.5407 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7388 - val_loss: 0.5390 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7440 - val_loss: 0.5322 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7471 - val_loss: 0.5335 - val_accuracy: 0.7327 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7535 - val_loss: 0.5369 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7557 - val_loss: 0.5371 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7596 - val_loss: 0.5510 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7602 - val_loss: 0.5447 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 13/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4743 - accuracy: 0.7665
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4749 - accuracy: 0.7661 - val_loss: 0.5413 - val_accuracy: 0.7251 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.44008669844051584
Confusion Matrix :
 [[2778 1545]
 [ 897 3426]]
Accuracy on test set:    0.7175572519083969
Sensitivity:    0.7925052047189451 	 Specificity:    0.6426092990978487
Precision  : 0.6891973445986723
Area Under Curve:    0.7175572519083969
(8646, 4352) (8646,)
Epoch 1/400

274/274 [==============================] - 1s 3ms/step - loss: 0.6114 - accuracy: 0.6652 - val_loss: 0.5650 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7079 - val_loss: 0.5505 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7192 - val_loss: 0.5508 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7284 - val_loss: 0.5422 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7337 - val_loss: 0.5447 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7393 - val_loss: 0.5424 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5137 - accuracy: 0.7411 - val_loss: 0.5419 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7487 - val_loss: 0.5553 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7514 - val_loss: 0.5394 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7561 - val_loss: 0.5416 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4881 - accuracy: 0.7584 - val_loss: 0.5462 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7639 - val_loss: 0.5538 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4719 - accuracy: 0.7655 - val_loss: 0.5569 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4656 - accuracy: 0.7705 - val_loss: 0.5556 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4589 - accuracy: 0.7737
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4594 - accuracy: 0.7737 - val_loss: 0.5593 - val_accuracy: 0.7201 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4480807471061352
Confusion Matrix :
 [[3146 1177]
 [1209 3114]]
Accuracy on test set:    0.7240342354846172
Sensitivity:    0.7203331020124913 	 Specificity:    0.727735368956743
Precision  : 0.725704963877884
Area Under Curve:    0.7240342354846171
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6062 - accuracy: 0.6677 - val_loss: 0.5709 - val_accuracy: 0.7002 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5604 - accuracy: 0.7128 - val_loss: 0.5498 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7225 - val_loss: 0.5461 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7315 - val_loss: 0.5373 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5252 - accuracy: 0.7372 - val_loss: 0.5473 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7400 - val_loss: 0.5387 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7444 - val_loss: 0.5523 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5062 - accuracy: 0.7478 - val_loss: 0.5383 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7527 - val_loss: 0.5385 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4932 - accuracy: 0.7554 - val_loss: 0.5439 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4879 - accuracy: 0.7594 - val_loss: 0.5431 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4811 - accuracy: 0.7630 - val_loss: 0.5399 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4762 - accuracy: 0.7672 - val_loss: 0.5459 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7711 - val_loss: 0.5442 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4630 - accuracy: 0.7728
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4627 - accuracy: 0.7732 - val_loss: 0.5532 - val_accuracy: 0.7241 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4634266673377713
Confusion Matrix :
 [[3319 1004]
 [1321 3002]]
Accuracy on test set:    0.731089521165857
Sensitivity:    0.6944251677076104 	 Specificity:    0.7677538746241036
Precision  : 0.7493759360958562
Area Under Curve:    0.731089521165857
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6052 - accuracy: 0.6677 - val_loss: 0.5951 - val_accuracy: 0.6803 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7102 - val_loss: 0.5530 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7201 - val_loss: 0.5517 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7252 - val_loss: 0.5426 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5292 - accuracy: 0.7322 - val_loss: 0.5407 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5213 - accuracy: 0.7376 - val_loss: 0.5523 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5168 - accuracy: 0.7401 - val_loss: 0.5367 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7448 - val_loss: 0.5511 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7484 - val_loss: 0.5443 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5003 - accuracy: 0.7504 - val_loss: 0.5423 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7522 - val_loss: 0.5399 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7558 - val_loss: 0.5464 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4842 - accuracy: 0.7607 - val_loss: 0.5440 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7630 - val_loss: 0.5392 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4736 - accuracy: 0.7651 - val_loss: 0.5394 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4683 - accuracy: 0.7691 - val_loss: 0.5477 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4640 - accuracy: 0.7715 - val_loss: 0.5491 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4596 - accuracy: 0.7723 - val_loss: 0.5520 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4533 - accuracy: 0.7767 - val_loss: 0.5497 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4493 - accuracy: 0.7773 - val_loss: 0.5624 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4459 - accuracy: 0.7798 - val_loss: 0.5639 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 22/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4405 - accuracy: 0.7814
Epoch 22: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4413 - accuracy: 0.7812 - val_loss: 0.5690 - val_accuracy: 0.7179 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.44542945893340985
Confusion Matrix :
 [[3504  819]
 [1611 2712]]
Accuracy on test set:    0.7189451769604441
Sensitivity:    0.6273421235253296 	 Specificity:    0.8105482303955587
Precision  : 0.7680543755310111
Area Under Curve:    0.7189451769604441
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6076 - accuracy: 0.6670 - val_loss: 0.5688 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5642 - accuracy: 0.7068 - val_loss: 0.5588 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5492 - accuracy: 0.7185 - val_loss: 0.5590 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7235 - val_loss: 0.5461 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5300 - accuracy: 0.7318 - val_loss: 0.5450 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7357 - val_loss: 0.5441 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7400 - val_loss: 0.5455 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7440 - val_loss: 0.5454 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7471 - val_loss: 0.5456 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7512 - val_loss: 0.5529 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7549 - val_loss: 0.5467 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4884 - accuracy: 0.7592
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7588 - val_loss: 0.5536 - val_accuracy: 0.7205 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.47135895704047404
Confusion Matrix :
 [[3484  839]
 [1468 2855]]
Accuracy on test set:    0.7331714087439278
Sensitivity:    0.6604210039324543 	 Specificity:    0.8059218135554014
Precision  : 0.7728749323226854
Area Under Curve:    0.7331714087439278
(8646, 4352) (8646,)
Mean MCC = 0.4444 + 0.0141 and Mean AUC = 0.7206 + 0.0074
Mean Sensitivity = 0.7295 + 0.0547 and Mean Specificity = 0.7117 + 0.0649 and Mean Accuracy = 0.7206 + 0.0074
Mean Precision = 0.7205 + 0.0322





Seed   : 109453
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5984 - accuracy: 0.6745 - val_loss: 0.5594 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5546 - accuracy: 0.7144 - val_loss: 0.5607 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7268 - val_loss: 0.5445 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7322 - val_loss: 0.5443 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5204 - accuracy: 0.7374 - val_loss: 0.5389 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7435 - val_loss: 0.5415 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7471 - val_loss: 0.5387 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7535 - val_loss: 0.5395 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7585 - val_loss: 0.5434 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4873 - accuracy: 0.7596 - val_loss: 0.5428 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4787 - accuracy: 0.7636 - val_loss: 0.5461 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4732 - accuracy: 0.7679 - val_loss: 0.5464 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4643 - accuracy: 0.7728 - val_loss: 0.5515 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4605 - accuracy: 0.7726 - val_loss: 0.5491 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4533 - accuracy: 0.7809
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4536 - accuracy: 0.7807 - val_loss: 0.5535 - val_accuracy: 0.7160 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.43019687588121625
Confusion Matrix :
 [[2843 1480]
 [ 995 3328]]
Accuracy on test set:    0.7137404580152672
Sensitivity:    0.7698357622021744 	 Specificity:    0.65764515382836
Precision  : 0.6921797004991681
Area Under Curve:    0.7137404580152671
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6029 - accuracy: 0.6686 - val_loss: 0.5597 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5580 - accuracy: 0.7101 - val_loss: 0.5520 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7242 - val_loss: 0.5497 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7298 - val_loss: 0.5500 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5240 - accuracy: 0.7369 - val_loss: 0.5501 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5172 - accuracy: 0.7403 - val_loss: 0.5422 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5116 - accuracy: 0.7463 - val_loss: 0.5530 - val_accuracy: 0.7141 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7483 - val_loss: 0.5404 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5012 - accuracy: 0.7512 - val_loss: 0.5395 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7544 - val_loss: 0.5367 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4879 - accuracy: 0.7584 - val_loss: 0.5409 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7612 - val_loss: 0.5449 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4778 - accuracy: 0.7641 - val_loss: 0.5410 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4713 - accuracy: 0.7670 - val_loss: 0.5431 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4646 - accuracy: 0.7707 - val_loss: 0.5488 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4602 - accuracy: 0.7731 - val_loss: 0.5448 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4563 - accuracy: 0.7745 - val_loss: 0.5608 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 18/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4496 - accuracy: 0.7792
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4509 - accuracy: 0.7784 - val_loss: 0.5496 - val_accuracy: 0.7192 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.4358547518980655
Confusion Matrix :
 [[3072 1251]
 [1188 3135]]
Accuracy on test set:    0.7179042331714087
Sensitivity:    0.7251908396946565 	 Specificity:    0.710617626648161
Precision  : 0.7147742818057455
Area Under Curve:    0.7179042331714087
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6149 - accuracy: 0.6562 - val_loss: 0.5661 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5640 - accuracy: 0.7080 - val_loss: 0.5554 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7224 - val_loss: 0.5523 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7282 - val_loss: 0.5478 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5280 - accuracy: 0.7324 - val_loss: 0.5436 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7360 - val_loss: 0.5409 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7424 - val_loss: 0.5442 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7433 - val_loss: 0.5464 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7497 - val_loss: 0.5479 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7509 - val_loss: 0.5485 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4946 - accuracy: 0.7531
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4951 - accuracy: 0.7529 - val_loss: 0.5477 - val_accuracy: 0.7205 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.44113054524352824
Confusion Matrix :
 [[3109 1214]
 [1202 3121]]
Accuracy on test set:    0.7205644228544992
Sensitivity:    0.7219523479065464 	 Specificity:    0.719176497802452
Precision  : 0.7199538638985006
Area Under Curve:    0.7205644228544991
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6073 - accuracy: 0.6656 - val_loss: 0.5686 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5589 - accuracy: 0.7113 - val_loss: 0.5592 - val_accuracy: 0.7070 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7238 - val_loss: 0.5535 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7287 - val_loss: 0.5450 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5260 - accuracy: 0.7337 - val_loss: 0.5447 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7384 - val_loss: 0.5454 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7453 - val_loss: 0.5389 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7464 - val_loss: 0.5412 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7509 - val_loss: 0.5474 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7517 - val_loss: 0.5406 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4850 - accuracy: 0.7596 - val_loss: 0.5422 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4821 - accuracy: 0.7614 - val_loss: 0.5409 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4730 - accuracy: 0.7674
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4725 - accuracy: 0.7676 - val_loss: 0.5468 - val_accuracy: 0.7244 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.43972650142502284
Confusion Matrix :
 [[2924 1399]
 [1030 3293]]
Accuracy on test set:    0.7190608373814481
Sensitivity:    0.7617395327318991 	 Specificity:    0.676382142030997
Precision  : 0.7018329070758739
Area Under Curve:    0.719060837381448
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6061 - accuracy: 0.6680 - val_loss: 0.5691 - val_accuracy: 0.6976 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7136 - val_loss: 0.5531 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7241 - val_loss: 0.5629 - val_accuracy: 0.6987 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7307 - val_loss: 0.5457 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5234 - accuracy: 0.7365 - val_loss: 0.5427 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7399 - val_loss: 0.5543 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5102 - accuracy: 0.7444 - val_loss: 0.5445 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7494 - val_loss: 0.5450 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4963 - accuracy: 0.7527 - val_loss: 0.5454 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4909 - accuracy: 0.7577
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7583 - val_loss: 0.5487 - val_accuracy: 0.7172 - lr: 0.0010
271/271 [==============================] - 0s 669us/step
Independent Testing Matthews Correlation:  0.4368646864461609
Confusion Matrix :
 [[2746 1577]
 [ 882 3441]]
Accuracy on test set:    0.7155910247513301
Sensitivity:    0.7959750173490632 	 Specificity:    0.6352070321535971
Precision  : 0.6857313670785173
Area Under Curve:    0.71559102475133
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6034 - accuracy: 0.6684 - val_loss: 0.5643 - val_accuracy: 0.7019 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7115 - val_loss: 0.5489 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7253 - val_loss: 0.5450 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7295 - val_loss: 0.5478 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5240 - accuracy: 0.7364 - val_loss: 0.5412 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7405 - val_loss: 0.5418 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7444 - val_loss: 0.5389 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5025 - accuracy: 0.7477 - val_loss: 0.5355 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7502 - val_loss: 0.5423 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7560 - val_loss: 0.5424 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7577 - val_loss: 0.5446 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4801 - accuracy: 0.7617 - val_loss: 0.5454 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 13/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4739 - accuracy: 0.7652
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4737 - accuracy: 0.7655 - val_loss: 0.5504 - val_accuracy: 0.7182 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.4329752489057814
Confusion Matrix :
 [[3190 1133]
 [1320 3003]]
Accuracy on test set:    0.7162849872773537
Sensitivity:    0.6946564885496184 	 Specificity:    0.7379134860050891
Precision  : 0.726063829787234
Area Under Curve:    0.7162849872773537
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6018 - accuracy: 0.6717 - val_loss: 0.5639 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5582 - accuracy: 0.7126 - val_loss: 0.5563 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7239 - val_loss: 0.5551 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7280 - val_loss: 0.5457 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7356 - val_loss: 0.5454 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5172 - accuracy: 0.7404 - val_loss: 0.5555 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7461 - val_loss: 0.5454 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5022 - accuracy: 0.7517 - val_loss: 0.5479 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7519 - val_loss: 0.5474 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4889 - accuracy: 0.7586 - val_loss: 0.5448 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7615 - val_loss: 0.5499 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 12/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4778 - accuracy: 0.7662
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7659 - val_loss: 0.5523 - val_accuracy: 0.7222 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4430690987251553
Confusion Matrix :
 [[2989 1334]
 [1077 3246]]
Accuracy on test set:    0.7211427249595188
Sensitivity:    0.7508674531575295 	 Specificity:    0.6914179967615082
Precision  : 0.7087336244541484
Area Under Curve:    0.7211427249595188
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6331 - accuracy: 0.6401 - val_loss: 0.5765 - val_accuracy: 0.6976 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5714 - accuracy: 0.7022 - val_loss: 0.5611 - val_accuracy: 0.7016 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5550 - accuracy: 0.7162 - val_loss: 0.5568 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7197 - val_loss: 0.5536 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7260 - val_loss: 0.5493 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7296 - val_loss: 0.5490 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7325 - val_loss: 0.5471 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7336 - val_loss: 0.5475 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7381 - val_loss: 0.5455 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7399 - val_loss: 0.5441 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5073 - accuracy: 0.7435 - val_loss: 0.5485 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5014 - accuracy: 0.7488 - val_loss: 0.5531 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7507 - val_loss: 0.5597 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7534 - val_loss: 0.5541 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 15/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4854 - accuracy: 0.7589
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4858 - accuracy: 0.7582 - val_loss: 0.5521 - val_accuracy: 0.7208 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4645627386204799
Confusion Matrix :
 [[3320 1003]
 [1317 3006]]
Accuracy on test set:    0.7316678232708768
Sensitivity:    0.6953504510756419 	 Specificity:    0.7679851954661115
Precision  : 0.7498129209279122
Area Under Curve:    0.7316678232708765
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6073 - accuracy: 0.6685 - val_loss: 0.5659 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7108 - val_loss: 0.5546 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7225 - val_loss: 0.5517 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7281 - val_loss: 0.5452 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5262 - accuracy: 0.7342 - val_loss: 0.5487 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5187 - accuracy: 0.7378 - val_loss: 0.5422 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7439 - val_loss: 0.5433 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7490 - val_loss: 0.5486 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4985 - accuracy: 0.7505 - val_loss: 0.5384 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4918 - accuracy: 0.7557 - val_loss: 0.5404 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4861 - accuracy: 0.7591 - val_loss: 0.5425 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4796 - accuracy: 0.7630 - val_loss: 0.5453 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4732 - accuracy: 0.7667 - val_loss: 0.5495 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 14/400
251/274 [==========================>...] - ETA: 0s - loss: 0.4668 - accuracy: 0.7690
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4673 - accuracy: 0.7687 - val_loss: 0.5510 - val_accuracy: 0.7201 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4468728778822798
Confusion Matrix :
 [[3473  850]
 [1568 2755]]
Accuracy on test set:    0.7203331020124913
Sensitivity:    0.6372889197316678 	 Specificity:    0.8033772842933148
Precision  : 0.7642163661581137
Area Under Curve:    0.7203331020124913
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6282 - accuracy: 0.6433 - val_loss: 0.5751 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5722 - accuracy: 0.7023 - val_loss: 0.5611 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5554 - accuracy: 0.7136 - val_loss: 0.5544 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7238 - val_loss: 0.5502 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7289 - val_loss: 0.5494 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5290 - accuracy: 0.7326 - val_loss: 0.5495 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7381 - val_loss: 0.5508 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7413 - val_loss: 0.5485 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7441 - val_loss: 0.5491 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5037 - accuracy: 0.7480
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7481 - val_loss: 0.5462 - val_accuracy: 0.7209 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.48682672523800413
Confusion Matrix :
 [[3263 1060]
 [1159 3164]]
Accuracy on test set:    0.7433495257922739
Sensitivity:    0.7318991441128846 	 Specificity:    0.7547999074716631
Precision  : 0.7490530303030303
Area Under Curve:    0.7433495257922739
(8646, 4352) (8646,)
Mean MCC = 0.4458 + 0.0164 and Mean AUC = 0.7220 + 0.0085
Mean Sensitivity = 0.7285 + 0.0430 and Mean Specificity = 0.7155 + 0.0495 and Mean Accuracy = 0.7220 + 0.0085
Mean Precision = 0.7212 + 0.0248





Seed   : 99078
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6199 - accuracy: 0.6528 - val_loss: 0.5668 - val_accuracy: 0.7048 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5612 - accuracy: 0.7090 - val_loss: 0.5518 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7196 - val_loss: 0.5484 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7274 - val_loss: 0.5440 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7328 - val_loss: 0.5442 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7377 - val_loss: 0.5379 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7405 - val_loss: 0.5438 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7441 - val_loss: 0.5364 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7489 - val_loss: 0.5333 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7542 - val_loss: 0.5344 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7588 - val_loss: 0.5328 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4869 - accuracy: 0.7607
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4868 - accuracy: 0.7609 - val_loss: 0.5354 - val_accuracy: 0.7274 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4284516987872703
Confusion Matrix :
 [[3056 1267]
 [1204 3119]]
Accuracy on test set:    0.7142030996992829
Sensitivity:    0.7214897062225306 	 Specificity:    0.7069164931760351
Precision  : 0.7111263109895121
Area Under Curve:    0.714203099699283
(8646, 4352) (8646,)
Epoch 1/400

274/274 [==============================] - 1s 3ms/step - loss: 0.6096 - accuracy: 0.6637 - val_loss: 0.5653 - val_accuracy: 0.7005 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5587 - accuracy: 0.7123 - val_loss: 0.5513 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7247 - val_loss: 0.5611 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7289 - val_loss: 0.5422 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7344 - val_loss: 0.5369 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5187 - accuracy: 0.7400 - val_loss: 0.5431 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5119 - accuracy: 0.7451 - val_loss: 0.5403 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7481 - val_loss: 0.5376 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7509 - val_loss: 0.5382 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4929 - accuracy: 0.7563 - val_loss: 0.5362 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7576 - val_loss: 0.5401 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7605 - val_loss: 0.5435 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4731 - accuracy: 0.7675
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4729 - accuracy: 0.7675 - val_loss: 0.5500 - val_accuracy: 0.7199 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4256148086487193
Confusion Matrix :
 [[2877 1446]
 [1045 3278]]
Accuracy on test set:    0.7118898912792042
Sensitivity:    0.7582697201017812 	 Specificity:    0.6655100624566274
Precision  : 0.6939034716342083
Area Under Curve:    0.7118898912792042
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6018 - accuracy: 0.6726 - val_loss: 0.5629 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5559 - accuracy: 0.7126 - val_loss: 0.5573 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7265 - val_loss: 0.5470 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7314 - val_loss: 0.5415 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7375 - val_loss: 0.5380 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7403 - val_loss: 0.5382 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7451 - val_loss: 0.5361 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7498 - val_loss: 0.5412 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7537 - val_loss: 0.5387 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7576 - val_loss: 0.5394 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4809 - accuracy: 0.7626 - val_loss: 0.5436 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4754 - accuracy: 0.7661 - val_loss: 0.5455 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7703 - val_loss: 0.5558 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4613 - accuracy: 0.7732 - val_loss: 0.5546 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4548 - accuracy: 0.7755
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4553 - accuracy: 0.7750 - val_loss: 0.5484 - val_accuracy: 0.7230 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4402284856459139
Confusion Matrix :
 [[3090 1233]
 [1187 3136]]
Accuracy on test set:    0.7201017811704835
Sensitivity:    0.7254221605366643 	 Specificity:    0.7147814018043026
Precision  : 0.7177843900205997
Area Under Curve:    0.7201017811704835
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6104 - accuracy: 0.6634 - val_loss: 0.5643 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7137 - val_loss: 0.5500 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7248 - val_loss: 0.5428 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7305 - val_loss: 0.5388 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7373 - val_loss: 0.5391 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7408 - val_loss: 0.5417 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7445 - val_loss: 0.5364 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7504 - val_loss: 0.5409 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7533 - val_loss: 0.5365 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4906 - accuracy: 0.7586 - val_loss: 0.5477 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7618 - val_loss: 0.5481 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4777 - accuracy: 0.7640
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4782 - accuracy: 0.7639 - val_loss: 0.5430 - val_accuracy: 0.7213 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.4305295562019089
Confusion Matrix :
 [[3062 1261]
 [1201 3122]]
Accuracy on test set:    0.7152440434883183
Sensitivity:    0.7221836687485542 	 Specificity:    0.7083044182280823
Precision  : 0.7122975131188684
Area Under Curve:    0.7152440434883183
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6157 - accuracy: 0.6586 - val_loss: 0.5653 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5620 - accuracy: 0.7087 - val_loss: 0.5525 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7201 - val_loss: 0.5429 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7281 - val_loss: 0.5428 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5279 - accuracy: 0.7314 - val_loss: 0.5389 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7374 - val_loss: 0.5383 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7419 - val_loss: 0.5392 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7443 - val_loss: 0.5399 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7492 - val_loss: 0.5358 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4951 - accuracy: 0.7521 - val_loss: 0.5411 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7561 - val_loss: 0.5411 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.7592 - val_loss: 0.5425 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7608 - val_loss: 0.5410 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7672 - val_loss: 0.5534 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4653 - accuracy: 0.7694 - val_loss: 0.5487 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4602 - accuracy: 0.7729 - val_loss: 0.5533 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4527 - accuracy: 0.7768 - val_loss: 0.5551 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4464 - accuracy: 0.7800
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4473 - accuracy: 0.7799 - val_loss: 0.5576 - val_accuracy: 0.7152 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4332935195474981
Confusion Matrix :
 [[2994 1329]
 [1123 3200]]
Accuracy on test set:    0.7164006476983577
Sensitivity:    0.7402266944251678 	 Specificity:    0.6925746009715475
Precision  : 0.7065577390152351
Area Under Curve:    0.7164006476983578
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6119 - accuracy: 0.6565 - val_loss: 0.5663 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5635 - accuracy: 0.7079 - val_loss: 0.5506 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7212 - val_loss: 0.5454 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7286 - val_loss: 0.5414 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5270 - accuracy: 0.7336 - val_loss: 0.5400 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7348 - val_loss: 0.5381 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7404 - val_loss: 0.5361 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7454 - val_loss: 0.5372 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7485 - val_loss: 0.5427 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7535 - val_loss: 0.5360 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7532 - val_loss: 0.5378 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4879 - accuracy: 0.7562 - val_loss: 0.5386 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7601 - val_loss: 0.5642 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4797 - accuracy: 0.7625 - val_loss: 0.5512 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4718 - accuracy: 0.7671 - val_loss: 0.5560 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4663 - accuracy: 0.7686 - val_loss: 0.5568 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4582 - accuracy: 0.7727
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4586 - accuracy: 0.7727 - val_loss: 0.5596 - val_accuracy: 0.7282 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4301519451985851
Confusion Matrix :
 [[2880 1443]
 [1029 3294]]
Accuracy on test set:    0.714087439278279
Sensitivity:    0.761970853573907 	 Specificity:    0.666204024982651
Precision  : 0.695376820772641
Area Under Curve:    0.7140874392782789
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6030 - accuracy: 0.6680 - val_loss: 0.5681 - val_accuracy: 0.7034 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5541 - accuracy: 0.7144 - val_loss: 0.5480 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7260 - val_loss: 0.5401 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7314 - val_loss: 0.5441 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5207 - accuracy: 0.7382 - val_loss: 0.5388 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7420 - val_loss: 0.5388 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5065 - accuracy: 0.7472 - val_loss: 0.5384 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4992 - accuracy: 0.7515
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4999 - accuracy: 0.7511 - val_loss: 0.5409 - val_accuracy: 0.7235 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4483435854960329
Confusion Matrix :
 [[3313 1010]
 [1382 2941]]
Accuracy on test set:    0.7233402729585936
Sensitivity:    0.6803145963451307 	 Specificity:    0.7663659495720564
Precision  : 0.7443685143001771
Area Under Curve:    0.7233402729585936
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6016 - accuracy: 0.6701 - val_loss: 0.5624 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7111 - val_loss: 0.5462 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7229 - val_loss: 0.5446 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7290 - val_loss: 0.5410 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7339 - val_loss: 0.5412 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5196 - accuracy: 0.7395 - val_loss: 0.5388 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7411 - val_loss: 0.5401 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7479 - val_loss: 0.5431 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7493 - val_loss: 0.5350 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7522 - val_loss: 0.5367 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7560 - val_loss: 0.5386 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4859 - accuracy: 0.7591 - val_loss: 0.5392 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7623 - val_loss: 0.5468 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4793 - accuracy: 0.7643 - val_loss: 0.5455 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4705 - accuracy: 0.7688 - val_loss: 0.5428 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4655 - accuracy: 0.7702
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4670 - accuracy: 0.7695 - val_loss: 0.5506 - val_accuracy: 0.7174 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.42255401246145485
Confusion Matrix :
 [[3191 1132]
 [1367 2956]]
Accuracy on test set:    0.7109646079111728
Sensitivity:    0.6837844089752487 	 Specificity:    0.7381448068470969
Precision  : 0.723091976516634
Area Under Curve:    0.7109646079111729
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6089 - accuracy: 0.6618 - val_loss: 0.5654 - val_accuracy: 0.7048 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5640 - accuracy: 0.7090 - val_loss: 0.5558 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7200 - val_loss: 0.5500 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7248 - val_loss: 0.5592 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7324 - val_loss: 0.5468 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5261 - accuracy: 0.7353 - val_loss: 0.5394 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5206 - accuracy: 0.7388 - val_loss: 0.5437 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5130 - accuracy: 0.7434 - val_loss: 0.5377 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7468 - val_loss: 0.5431 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7491 - val_loss: 0.5397 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7545 - val_loss: 0.5394 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7535 - val_loss: 0.5428 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4889 - accuracy: 0.7596 - val_loss: 0.5461 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7596 - val_loss: 0.5497 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4763 - accuracy: 0.7659 - val_loss: 0.5450 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4704 - accuracy: 0.7702
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4712 - accuracy: 0.7695 - val_loss: 0.5485 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4747208100918988
Confusion Matrix :
 [[3065 1258]
 [1016 3307]]
Accuracy on test set:    0.7369882026370576
Sensitivity:    0.7649780245200093 	 Specificity:    0.7089983807541059
Precision  : 0.7244249726177437
Area Under Curve:    0.7369882026370576
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6141 - accuracy: 0.6627 - val_loss: 0.5699 - val_accuracy: 0.7010 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5643 - accuracy: 0.7086 - val_loss: 0.5556 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7184 - val_loss: 0.5481 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7260 - val_loss: 0.5478 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7309 - val_loss: 0.5456 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5234 - accuracy: 0.7352 - val_loss: 0.5414 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7410 - val_loss: 0.5397 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7451 - val_loss: 0.5451 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7493 - val_loss: 0.5439 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7522 - val_loss: 0.5480 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4879 - accuracy: 0.7580 - val_loss: 0.5447 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4816 - accuracy: 0.7620
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4819 - accuracy: 0.7622 - val_loss: 0.5479 - val_accuracy: 0.7285 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.4971496221174792
Confusion Matrix :
 [[3352  971]
 [1206 3117]]
Accuracy on test set:    0.748207263474439
Sensitivity:    0.721027064538515 	 Specificity:    0.7753874624103632
Precision  : 0.7624755381604696
Area Under Curve:    0.748207263474439
(8646, 4352) (8646,)
Mean MCC = 0.4431 + 0.0231 and Mean AUC = 0.7211 + 0.0115
Mean Sensitivity = 0.7280 + 0.0282 and Mean Specificity = 0.7143 + 0.0351 and Mean Accuracy = 0.7211 + 0.0115
Mean Precision = 0.7191 + 0.0201





Seed   : 684111

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6022 - accuracy: 0.6716 - val_loss: 0.5633 - val_accuracy: 0.7038 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5545 - accuracy: 0.7146 - val_loss: 0.5479 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7256 - val_loss: 0.5405 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7332 - val_loss: 0.5374 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5192 - accuracy: 0.7393 - val_loss: 0.5400 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7448 - val_loss: 0.5390 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7474 - val_loss: 0.5382 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7525 - val_loss: 0.5333 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7560 - val_loss: 0.5374 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7586 - val_loss: 0.5378 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4817 - accuracy: 0.7618 - val_loss: 0.5410 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4755 - accuracy: 0.7682 - val_loss: 0.5392 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7691 - val_loss: 0.5426 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4649 - accuracy: 0.7717 - val_loss: 0.5454 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4555 - accuracy: 0.7787 - val_loss: 0.5488 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4523 - accuracy: 0.7775 - val_loss: 0.5540 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4458 - accuracy: 0.7842 - val_loss: 0.5647 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 18/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4396 - accuracy: 0.7874
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4402 - accuracy: 0.7865 - val_loss: 0.5588 - val_accuracy: 0.7178 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.40933419140055066
Confusion Matrix :
 [[3136 1187]
 [1368 2955]]
Accuracy on test set:    0.7044876243349526
Sensitivity:    0.6835530881332408 	 Specificity:    0.7254221605366643
Precision  : 0.7134234669241912
Area Under Curve:    0.7044876243349526
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6059 - accuracy: 0.6661 - val_loss: 0.5652 - val_accuracy: 0.7077 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5577 - accuracy: 0.7122 - val_loss: 0.5582 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7246 - val_loss: 0.5499 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7316 - val_loss: 0.5524 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7358 - val_loss: 0.5454 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7399 - val_loss: 0.5453 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7465 - val_loss: 0.5412 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5057 - accuracy: 0.7487 - val_loss: 0.5429 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4954 - accuracy: 0.7521 - val_loss: 0.5481 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4901 - accuracy: 0.7579 - val_loss: 0.5468 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7625 - val_loss: 0.5546 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7639 - val_loss: 0.5500 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4726 - accuracy: 0.7678 - val_loss: 0.5593 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4731 - accuracy: 0.7670
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4724 - accuracy: 0.7671 - val_loss: 0.5581 - val_accuracy: 0.7188 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4372188351632576
Confusion Matrix :
 [[2836 1487]
 [ 960 3363]]
Accuracy on test set:    0.7169789498033773
Sensitivity:    0.7779319916724496 	 Specificity:    0.6560259079343049
Precision  : 0.6934020618556701
Area Under Curve:    0.7169789498033774
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6093 - accuracy: 0.6646 - val_loss: 0.5714 - val_accuracy: 0.6967 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5565 - accuracy: 0.7111 - val_loss: 0.5507 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7221 - val_loss: 0.5470 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7320 - val_loss: 0.5473 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7342 - val_loss: 0.5534 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7416 - val_loss: 0.5410 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7453 - val_loss: 0.5387 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7487 - val_loss: 0.5451 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7526 - val_loss: 0.5458 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7568 - val_loss: 0.5518 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7610 - val_loss: 0.5525 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4772 - accuracy: 0.7634
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4776 - accuracy: 0.7633 - val_loss: 0.5523 - val_accuracy: 0.7201 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.4253777964661295
Confusion Matrix :
 [[3289 1034]
 [1459 2864]]
Accuracy on test set:    0.7116585704371964
Sensitivity:    0.6625028915105251 	 Specificity:    0.7608142493638677
Precision  : 0.7347357619291944
Area Under Curve:    0.7116585704371964
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6016 - accuracy: 0.6696 - val_loss: 0.5644 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7142 - val_loss: 0.5519 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7236 - val_loss: 0.5446 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7301 - val_loss: 0.5462 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7351 - val_loss: 0.5462 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7397 - val_loss: 0.5447 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7437 - val_loss: 0.5459 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7460 - val_loss: 0.5451 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5006 - accuracy: 0.7508 - val_loss: 0.5402 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4956 - accuracy: 0.7532 - val_loss: 0.5428 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4901 - accuracy: 0.7576 - val_loss: 0.5467 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4857 - accuracy: 0.7592 - val_loss: 0.5479 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4799 - accuracy: 0.7625 - val_loss: 0.5397 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4733 - accuracy: 0.7679 - val_loss: 0.5472 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4701 - accuracy: 0.7674 - val_loss: 0.5546 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4648 - accuracy: 0.7706 - val_loss: 0.5605 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4584 - accuracy: 0.7742 - val_loss: 0.5532 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 18/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4513 - accuracy: 0.7784
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4507 - accuracy: 0.7781 - val_loss: 0.5606 - val_accuracy: 0.7263 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4378540197866673
Confusion Matrix :
 [[3172 1151]
 [1280 3043]]
Accuracy on test set:    0.7188295165394402
Sensitivity:    0.703909322229933 	 Specificity:    0.7337497108489475
Precision  : 0.7255603242727706
Area Under Curve:    0.7188295165394403
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6035 - accuracy: 0.6689 - val_loss: 0.5692 - val_accuracy: 0.7026 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5590 - accuracy: 0.7109 - val_loss: 0.5489 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7232 - val_loss: 0.5430 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7284 - val_loss: 0.5421 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7350 - val_loss: 0.5385 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7379 - val_loss: 0.5473 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7436 - val_loss: 0.5367 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7456 - val_loss: 0.5464 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7505 - val_loss: 0.5368 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7534 - val_loss: 0.5414 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7593 - val_loss: 0.5437 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7620 - val_loss: 0.5393 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4760 - accuracy: 0.7673 - val_loss: 0.5448 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4718 - accuracy: 0.7673 - val_loss: 0.5477 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4630 - accuracy: 0.7733 - val_loss: 0.5444 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4594 - accuracy: 0.7743 - val_loss: 0.5487 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4543 - accuracy: 0.7803 - val_loss: 0.5515 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4508 - accuracy: 0.7798 - val_loss: 0.5595 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 19/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4425 - accuracy: 0.7833
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4432 - accuracy: 0.7830 - val_loss: 0.5551 - val_accuracy: 0.7283 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4250757904760139
Confusion Matrix :
 [[2964 1359]
 [1129 3194]]
Accuracy on test set:    0.712236872542216
Sensitivity:    0.7388387693731205 	 Specificity:    0.6856349757113116
Precision  : 0.7015154842960686
Area Under Curve:    0.7122368725422161
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6063 - accuracy: 0.6655 - val_loss: 0.5601 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5599 - accuracy: 0.7113 - val_loss: 0.5497 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7194 - val_loss: 0.5429 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7285 - val_loss: 0.5589 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7311 - val_loss: 0.5407 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7366 - val_loss: 0.5382 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7409 - val_loss: 0.5395 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7422 - val_loss: 0.5402 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7439 - val_loss: 0.5436 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7489 - val_loss: 0.5455 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7509 - val_loss: 0.5437 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4929 - accuracy: 0.7548 - val_loss: 0.5439 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4878 - accuracy: 0.7584 - val_loss: 0.5477 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4812 - accuracy: 0.7617 - val_loss: 0.5460 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7639 - val_loss: 0.5514 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4744 - accuracy: 0.7651
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4744 - accuracy: 0.7651 - val_loss: 0.5566 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.4498378830329603
Confusion Matrix :
 [[3044 1279]
 [1101 3222]]
Accuracy on test set:    0.7247281980106408
Sensitivity:    0.7453157529493407 	 Specificity:    0.7041406430719408
Precision  : 0.715840924239058
Area Under Curve:    0.7247281980106408
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6109 - accuracy: 0.6613 - val_loss: 0.5717 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5627 - accuracy: 0.7087 - val_loss: 0.5595 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7194 - val_loss: 0.5502 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7261 - val_loss: 0.5474 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5285 - accuracy: 0.7323 - val_loss: 0.5470 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7362 - val_loss: 0.5426 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7400 - val_loss: 0.5444 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5119 - accuracy: 0.7439 - val_loss: 0.5403 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5042 - accuracy: 0.7476 - val_loss: 0.5467 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4982 - accuracy: 0.7523
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7525 - val_loss: 0.5428 - val_accuracy: 0.7235 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.44234368137272173
Confusion Matrix :
 [[2990 1333]
 [1081 3242]]
Accuracy on test set:    0.720795743696507
Sensitivity:    0.749942169789498 	 Specificity:    0.6916493176035161
Precision  : 0.7086338797814208
Area Under Curve:    0.720795743696507
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6040 - accuracy: 0.6687 - val_loss: 0.5626 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7136 - val_loss: 0.5555 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7214 - val_loss: 0.5452 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7310 - val_loss: 0.5405 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7347 - val_loss: 0.5381 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5149 - accuracy: 0.7427 - val_loss: 0.5353 - val_accuracy: 0.7345 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7444 - val_loss: 0.5460 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7493 - val_loss: 0.5370 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7543 - val_loss: 0.5436 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7579 - val_loss: 0.5394 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4836 - accuracy: 0.7629
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7625 - val_loss: 0.5428 - val_accuracy: 0.7282 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.46912891146026553
Confusion Matrix :
 [[2992 1331]
 [ 971 3352]]
Accuracy on test set:    0.7337497108489475
Sensitivity:    0.7753874624103632 	 Specificity:    0.6921119592875318
Precision  : 0.7157804825966261
Area Under Curve:    0.7337497108489475
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6147 - accuracy: 0.6584 - val_loss: 0.5639 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5643 - accuracy: 0.7069 - val_loss: 0.5506 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5480 - accuracy: 0.7209 - val_loss: 0.5499 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7262 - val_loss: 0.5419 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7338 - val_loss: 0.5428 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5205 - accuracy: 0.7387 - val_loss: 0.5395 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7428 - val_loss: 0.5446 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7455 - val_loss: 0.5373 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5014 - accuracy: 0.7519 - val_loss: 0.5372 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7529 - val_loss: 0.5429 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7583 - val_loss: 0.5422 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4809 - accuracy: 0.7619 - val_loss: 0.5464 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 13/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4772 - accuracy: 0.7637
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4779 - accuracy: 0.7635 - val_loss: 0.5477 - val_accuracy: 0.7287 - lr: 0.0010

271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.4825576169191955
Confusion Matrix :
 [[3051 1272]
 [ 970 3353]]
Accuracy on test set:    0.7406893361091834
Sensitivity:    0.775618783252371 	 Specificity:    0.7057598889659958
Precision  : 0.7249729729729729
Area Under Curve:    0.7406893361091835
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6139 - accuracy: 0.6617 - val_loss: 0.5652 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5671 - accuracy: 0.7063 - val_loss: 0.5540 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5524 - accuracy: 0.7169 - val_loss: 0.5553 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7252 - val_loss: 0.5473 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7306 - val_loss: 0.5415 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7346 - val_loss: 0.5435 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7390 - val_loss: 0.5465 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7422 - val_loss: 0.5418 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7480 - val_loss: 0.5446 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5009 - accuracy: 0.7524 - val_loss: 0.5478 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7518 - val_loss: 0.5454 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4902 - accuracy: 0.7578 - val_loss: 0.5418 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7608 - val_loss: 0.5551 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4775 - accuracy: 0.7645
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4779 - accuracy: 0.7643 - val_loss: 0.5476 - val_accuracy: 0.7285 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.5023030294606081
Confusion Matrix :
 [[3444  879]
 [1282 3041]]
Accuracy on test set:    0.750057830210502
Sensitivity:    0.7034466805459172 	 Specificity:    0.7966689798750868
Precision  : 0.775765306122449
Area Under Curve:    0.750057830210502
(8646, 4352) (8646,)
Mean MCC = 0.4481 + 0.0272 and Mean AUC = 0.7234 + 0.0134
Mean Sensitivity = 0.7316 + 0.0390 and Mean Specificity = 0.7152 + 0.0385 and Mean Accuracy = 0.7234 + 0.0134
Mean Precision = 0.7210 + 0.0215





Seed   : 76472
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6167 - accuracy: 0.6526 - val_loss: 0.5625 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5638 - accuracy: 0.7104 - val_loss: 0.5509 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7192 - val_loss: 0.5471 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7272 - val_loss: 0.5391 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7336 - val_loss: 0.5326 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7354 - val_loss: 0.5317 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5177 - accuracy: 0.7399 - val_loss: 0.5321 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7442 - val_loss: 0.5351 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7473 - val_loss: 0.5298 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.5021 - accuracy: 0.7505
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7496 - val_loss: 0.5319 - val_accuracy: 0.7246 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4220107574831157
Confusion Matrix :
 [[2750 1573]
 [ 945 3378]]
Accuracy on test set:    0.7087670599120981
Sensitivity:    0.7814018043025677 	 Specificity:    0.6361323155216285
Precision  : 0.6822864067865078
Area Under Curve:    0.7087670599120981
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6174 - accuracy: 0.6542 - val_loss: 0.6066 - val_accuracy: 0.6671 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5649 - accuracy: 0.7068 - val_loss: 0.5533 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5503 - accuracy: 0.7174 - val_loss: 0.5455 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7237 - val_loss: 0.5456 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5304 - accuracy: 0.7313 - val_loss: 0.5422 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7346 - val_loss: 0.5422 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7395 - val_loss: 0.5426 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5102 - accuracy: 0.7437 - val_loss: 0.5412 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7468 - val_loss: 0.5389 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7480 - val_loss: 0.5436 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7519 - val_loss: 0.5450 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4877 - accuracy: 0.7567 - val_loss: 0.5447 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4812 - accuracy: 0.7599 - val_loss: 0.5577 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4757 - accuracy: 0.7627 - val_loss: 0.5488 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4701 - accuracy: 0.7655 - val_loss: 0.5462 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4647 - accuracy: 0.7678
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4656 - accuracy: 0.7673 - val_loss: 0.5520 - val_accuracy: 0.7179 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4264726236924568
Confusion Matrix :
 [[3026 1297]
 [1183 3140]]
Accuracy on test set:    0.7131621559102476
Sensitivity:    0.7263474439046959 	 Specificity:    0.6999768679157992
Precision  : 0.7076853729997746
Area Under Curve:    0.7131621559102475
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6041 - accuracy: 0.6682 - val_loss: 0.5614 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7108 - val_loss: 0.5581 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7237 - val_loss: 0.5529 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5287 - accuracy: 0.7329 - val_loss: 0.5379 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5218 - accuracy: 0.7387 - val_loss: 0.5374 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7434 - val_loss: 0.5380 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5078 - accuracy: 0.7478 - val_loss: 0.5387 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7493 - val_loss: 0.5365 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7551 - val_loss: 0.5374 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4884 - accuracy: 0.7584 - val_loss: 0.5500 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4794 - accuracy: 0.7636 - val_loss: 0.5407 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4750 - accuracy: 0.7668 - val_loss: 0.5409 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7710 - val_loss: 0.5423 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4612 - accuracy: 0.7737
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4616 - accuracy: 0.7732 - val_loss: 0.5457 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 638us/step
Independent Testing Matthews Correlation:  0.4441055452650881
Confusion Matrix :
 [[3186 1137]
 [1267 3056]]
Accuracy on test set:    0.7219523479065464
Sensitivity:    0.7069164931760351 	 Specificity:    0.7369882026370576
Precision  : 0.7288337705699977
Area Under Curve:    0.7219523479065464
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6256 - accuracy: 0.6487 - val_loss: 0.5702 - val_accuracy: 0.7011 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5656 - accuracy: 0.7064 - val_loss: 0.5539 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7208 - val_loss: 0.5510 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7261 - val_loss: 0.5433 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7308 - val_loss: 0.5396 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7344 - val_loss: 0.5407 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7409 - val_loss: 0.5464 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7417 - val_loss: 0.5417 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5054 - accuracy: 0.7458 - val_loss: 0.5399 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4966 - accuracy: 0.7521
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7522 - val_loss: 0.5455 - val_accuracy: 0.7176 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4253582067024332
Confusion Matrix :
 [[2730 1593]
 [ 914 3409]]
Accuracy on test set:    0.7100393245431413
Sensitivity:    0.7885727504048115 	 Specificity:    0.6315058986814712
Precision  : 0.6815273890443823
Area Under Curve:    0.7100393245431413
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6066 - accuracy: 0.6643 - val_loss: 0.5632 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5583 - accuracy: 0.7130 - val_loss: 0.5513 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7238 - val_loss: 0.5410 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7306 - val_loss: 0.5412 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5287 - accuracy: 0.7335 - val_loss: 0.5370 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5200 - accuracy: 0.7389 - val_loss: 0.5380 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7419 - val_loss: 0.5374 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7478 - val_loss: 0.5351 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7504 - val_loss: 0.5351 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7529 - val_loss: 0.5355 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4933 - accuracy: 0.7548 - val_loss: 0.5398 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7583 - val_loss: 0.5451 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4822 - accuracy: 0.7612 - val_loss: 0.5425 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7642 - val_loss: 0.5451 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 15/400
263/274 [===========================>..] - ETA: 0s - loss: 0.4731 - accuracy: 0.7677
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4731 - accuracy: 0.7679 - val_loss: 0.5500 - val_accuracy: 0.7208 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.43597933851039256
Confusion Matrix :
 [[2735 1588]
 [ 876 3447]]
Accuracy on test set:    0.7150127226463104
Sensitivity:    0.7973629424011104 	 Specificity:    0.6326625028915105
Precision  : 0.6846077457795432
Area Under Curve:    0.7150127226463104
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6035 - accuracy: 0.6698 - val_loss: 0.5605 - val_accuracy: 0.7030 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5559 - accuracy: 0.7136 - val_loss: 0.5518 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7246 - val_loss: 0.5388 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5310 - accuracy: 0.7303 - val_loss: 0.5360 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7369 - val_loss: 0.5328 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7421 - val_loss: 0.5312 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7441 - val_loss: 0.5315 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7509 - val_loss: 0.5351 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7549 - val_loss: 0.5401 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7573 - val_loss: 0.5386 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4834 - accuracy: 0.7608 - val_loss: 0.5351 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4747 - accuracy: 0.7663 - val_loss: 0.5469 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4711 - accuracy: 0.7694
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4709 - accuracy: 0.7696 - val_loss: 0.5543 - val_accuracy: 0.7271 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4340812333078237
Confusion Matrix :
 [[2710 1613]
 [ 862 3461]]
Accuracy on test set:    0.7137404580152672
Sensitivity:    0.8006014341892205 	 Specificity:    0.6268794818413139
Precision  : 0.6821048482459598
Area Under Curve:    0.7137404580152672
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6094 - accuracy: 0.6627 - val_loss: 0.5737 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5615 - accuracy: 0.7084 - val_loss: 0.5543 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7202 - val_loss: 0.5477 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7271 - val_loss: 0.5444 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5294 - accuracy: 0.7314 - val_loss: 0.5423 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5214 - accuracy: 0.7370 - val_loss: 0.5407 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7427 - val_loss: 0.5412 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7457 - val_loss: 0.5451 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7484 - val_loss: 0.5417 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7512 - val_loss: 0.5382 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7555 - val_loss: 0.5469 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4851 - accuracy: 0.7591
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4859 - accuracy: 0.7583 - val_loss: 0.5524 - val_accuracy: 0.7147 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.453047834316721
Confusion Matrix :
 [[2707 1616]
 [ 785 3538]]
Accuracy on test set:    0.7222993291695582
Sensitivity:    0.8184131390238261 	 Specificity:    0.6261855193152903
Precision  : 0.6864571206829647
Area Under Curve:    0.7222993291695582
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6056 - accuracy: 0.6670 - val_loss: 0.5766 - val_accuracy: 0.6980 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5639 - accuracy: 0.7089 - val_loss: 0.5537 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7211 - val_loss: 0.5539 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5368 - accuracy: 0.7277 - val_loss: 0.5469 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5290 - accuracy: 0.7325 - val_loss: 0.5411 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7366 - val_loss: 0.5395 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7394 - val_loss: 0.5414 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7406 - val_loss: 0.5374 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7481 - val_loss: 0.5396 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7494 - val_loss: 0.5430 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7502 - val_loss: 0.5408 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4925 - accuracy: 0.7554
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7555 - val_loss: 0.5440 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.45399328294395114
Confusion Matrix :
 [[3253 1070]
 [1293 3030]]
Accuracy on test set:    0.7266944251677077
Sensitivity:    0.7009021512838307 	 Specificity:    0.7524866990515845
Precision  : 0.7390243902439024
Area Under Curve:    0.7266944251677078
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6071 - accuracy: 0.6694 - val_loss: 0.5621 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5598 - accuracy: 0.7119 - val_loss: 0.5506 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7209 - val_loss: 0.5446 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7291 - val_loss: 0.5437 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5301 - accuracy: 0.7317 - val_loss: 0.5410 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5191 - accuracy: 0.7388 - val_loss: 0.5384 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7436 - val_loss: 0.5411 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7451 - val_loss: 0.5376 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7504 - val_loss: 0.5475 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7533 - val_loss: 0.5451 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7581 - val_loss: 0.5396 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4827 - accuracy: 0.7630 - val_loss: 0.5423 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4741 - accuracy: 0.7653
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4748 - accuracy: 0.7651 - val_loss: 0.5479 - val_accuracy: 0.7186 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.4585887391596458
Confusion Matrix :
 [[3279 1044]
 [1300 3023]]
Accuracy on test set:    0.7288919731667823
Sensitivity:    0.6992829053897757 	 Specificity:    0.758501040943789
Precision  : 0.7432997295303664
Area Under Curve:    0.7288919731667823
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6134 - accuracy: 0.6596 - val_loss: 0.5693 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5656 - accuracy: 0.7075 - val_loss: 0.5675 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5510 - accuracy: 0.7197 - val_loss: 0.5562 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7258 - val_loss: 0.5529 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7322 - val_loss: 0.5527 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7338 - val_loss: 0.5484 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5172 - accuracy: 0.7409 - val_loss: 0.5463 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7432 - val_loss: 0.5487 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5062 - accuracy: 0.7465 - val_loss: 0.5463 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7504 - val_loss: 0.5546 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7568 - val_loss: 0.5517 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4859 - accuracy: 0.7610 - val_loss: 0.5508 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4822 - accuracy: 0.7617 - val_loss: 0.5561 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4760 - accuracy: 0.7661 - val_loss: 0.5658 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4701 - accuracy: 0.7676 - val_loss: 0.5645 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4641 - accuracy: 0.7733
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4632 - accuracy: 0.7740 - val_loss: 0.5760 - val_accuracy: 0.7170 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.5048542543496357
Confusion Matrix :
 [[3389  934]
 [1211 3112]]
Accuracy on test set:    0.7519083969465649
Sensitivity:    0.7198704603284756 	 Specificity:    0.7839463335646542
Precision  : 0.7691547207118141
Area Under Curve:    0.7519083969465649
(8646, 4352) (8646,)
Mean MCC = 0.4458 + 0.0232 and Mean AUC = 0.7212 + 0.0121
Mean Sensitivity = 0.7540 + 0.0448 and Mean Specificity = 0.6885 + 0.0611 and Mean Accuracy = 0.7212 + 0.0121
Mean Precision = 0.7105 + 0.0306





Seed   : 704563
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6008 - accuracy: 0.6741 - val_loss: 0.5710 - val_accuracy: 0.7023 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5605 - accuracy: 0.7089 - val_loss: 0.5591 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7232 - val_loss: 0.5418 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7292 - val_loss: 0.5442 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7350 - val_loss: 0.5373 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7389 - val_loss: 0.5337 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7421 - val_loss: 0.5375 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7490 - val_loss: 0.5419 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7490 - val_loss: 0.5354 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7556 - val_loss: 0.5385 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7533 - val_loss: 0.5414 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4821 - accuracy: 0.7591 - val_loss: 0.5364 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4756 - accuracy: 0.7653 - val_loss: 0.5457 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4696 - accuracy: 0.7671 - val_loss: 0.5426 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4652 - accuracy: 0.7699 - val_loss: 0.5411 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4572 - accuracy: 0.7727 - val_loss: 0.5437 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4562 - accuracy: 0.7740 - val_loss: 0.5581 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4498 - accuracy: 0.7791 - val_loss: 0.5523 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 19/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4430 - accuracy: 0.7833
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4435 - accuracy: 0.7830 - val_loss: 0.5512 - val_accuracy: 0.7245 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.41767837789611334
Confusion Matrix :
 [[2849 1474]
 [1052 3271]]
Accuracy on test set:    0.7078417765440667
Sensitivity:    0.7566504742077261 	 Specificity:    0.6590330788804071
Precision  : 0.6893572181243414
Area Under Curve:    0.7078417765440665
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5986 - accuracy: 0.6742 - val_loss: 0.5643 - val_accuracy: 0.7052 - lr: 0.0010

Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5569 - accuracy: 0.7140 - val_loss: 0.5525 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7242 - val_loss: 0.5462 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5304 - accuracy: 0.7315 - val_loss: 0.5500 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7365 - val_loss: 0.5404 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7396 - val_loss: 0.5450 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7444 - val_loss: 0.5358 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5042 - accuracy: 0.7490 - val_loss: 0.5398 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7507 - val_loss: 0.5370 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4911 - accuracy: 0.7563
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7560 - val_loss: 0.5389 - val_accuracy: 0.7183 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.41888309285855213
Confusion Matrix :
 [[3001 1322]
 [1191 3132]]
Accuracy on test set:    0.7093453620171177
Sensitivity:    0.7244968771686329 	 Specificity:    0.6941938468656026
Precision  : 0.7031881454872025
Area Under Curve:    0.7093453620171177
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6006 - accuracy: 0.6728 - val_loss: 0.5663 - val_accuracy: 0.7052 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7122 - val_loss: 0.5516 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7243 - val_loss: 0.5471 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7298 - val_loss: 0.5402 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7361 - val_loss: 0.5400 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7391 - val_loss: 0.5405 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5102 - accuracy: 0.7436 - val_loss: 0.5395 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7486 - val_loss: 0.5527 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4970 - accuracy: 0.7543 - val_loss: 0.5534 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4933 - accuracy: 0.7533 - val_loss: 0.5410 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7602 - val_loss: 0.5457 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4763 - accuracy: 0.7649 - val_loss: 0.5475 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4715 - accuracy: 0.7677 - val_loss: 0.5569 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4664 - accuracy: 0.7725 - val_loss: 0.5615 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4584 - accuracy: 0.7753
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4591 - accuracy: 0.7749 - val_loss: 0.5593 - val_accuracy: 0.7170 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4407753723063644
Confusion Matrix :
 [[2964 1359]
 [1063 3260]]
Accuracy on test set:    0.7198704603284756
Sensitivity:    0.7541059449456397 	 Specificity:    0.6856349757113116
Precision  : 0.7057804719636285
Area Under Curve:    0.7198704603284756
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6073 - accuracy: 0.6651 - val_loss: 0.5641 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5593 - accuracy: 0.7107 - val_loss: 0.5641 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7196 - val_loss: 0.5633 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7284 - val_loss: 0.5429 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5269 - accuracy: 0.7338 - val_loss: 0.5435 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5207 - accuracy: 0.7387 - val_loss: 0.5451 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7417 - val_loss: 0.5410 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5062 - accuracy: 0.7474 - val_loss: 0.5409 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7497 - val_loss: 0.5435 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4954 - accuracy: 0.7538 - val_loss: 0.5487 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7569 - val_loss: 0.5376 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7574 - val_loss: 0.5408 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7631 - val_loss: 0.5467 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4745 - accuracy: 0.7672 - val_loss: 0.5508 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7705 - val_loss: 0.5524 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4628 - accuracy: 0.7708 - val_loss: 0.5529 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4530 - accuracy: 0.7769 - val_loss: 0.5528 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4505 - accuracy: 0.7772 - val_loss: 0.5592 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 19/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4455 - accuracy: 0.7807
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4456 - accuracy: 0.7810 - val_loss: 0.5528 - val_accuracy: 0.7267 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4379055381413977
Confusion Matrix :
 [[3126 1197]
 [1233 3090]]
Accuracy on test set:    0.7189451769604441
Sensitivity:    0.7147814018043026 	 Specificity:    0.7231089521165857
Precision  : 0.7207837648705389
Area Under Curve:    0.7189451769604441
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6088 - accuracy: 0.6684 - val_loss: 0.5616 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5589 - accuracy: 0.7115 - val_loss: 0.5468 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7242 - val_loss: 0.5400 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7296 - val_loss: 0.5368 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5231 - accuracy: 0.7360 - val_loss: 0.5396 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7390 - val_loss: 0.5341 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7432 - val_loss: 0.5380 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7468 - val_loss: 0.5362 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7506 - val_loss: 0.5310 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7566 - val_loss: 0.5391 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4860 - accuracy: 0.7586 - val_loss: 0.5395 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7629 - val_loss: 0.5457 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7676 - val_loss: 0.5418 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 14/400
264/274 [===========================>..] - ETA: 0s - loss: 0.4665 - accuracy: 0.7688
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4661 - accuracy: 0.7694 - val_loss: 0.5474 - val_accuracy: 0.7278 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4416610917975339
Confusion Matrix :
 [[2969 1354]
 [1064 3259]]
Accuracy on test set:    0.7203331020124913
Sensitivity:    0.7538746241036317 	 Specificity:    0.6867915799213509
Precision  : 0.7064816822024713
Area Under Curve:    0.7203331020124912
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6180 - accuracy: 0.6558 - val_loss: 0.5635 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7103 - val_loss: 0.5508 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7234 - val_loss: 0.5408 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7289 - val_loss: 0.5358 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5262 - accuracy: 0.7348 - val_loss: 0.5315 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7383 - val_loss: 0.5289 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7444 - val_loss: 0.5340 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7488 - val_loss: 0.5277 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5008 - accuracy: 0.7491 - val_loss: 0.5326 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7562 - val_loss: 0.5327 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7592 - val_loss: 0.5315 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4809 - accuracy: 0.7613 - val_loss: 0.5434 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4754 - accuracy: 0.7660 - val_loss: 0.5389 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4660 - accuracy: 0.7700 - val_loss: 0.5439 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4644 - accuracy: 0.7705 - val_loss: 0.5385 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 16/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4549 - accuracy: 0.7752
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4554 - accuracy: 0.7745 - val_loss: 0.5584 - val_accuracy: 0.7300 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.43920028006453427
Confusion Matrix :
 [[2913 1410]
 [1022 3301]]
Accuracy on test set:    0.7187138561184363
Sensitivity:    0.7635900994679621 	 Specificity:    0.6738376127689105
Precision  : 0.7007004882190617
Area Under Curve:    0.7187138561184364
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6117 - accuracy: 0.6651 - val_loss: 0.5661 - val_accuracy: 0.7020 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7100 - val_loss: 0.5532 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7214 - val_loss: 0.5461 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7302 - val_loss: 0.5345 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7362 - val_loss: 0.5337 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7386 - val_loss: 0.5311 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5106 - accuracy: 0.7436 - val_loss: 0.5317 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7477 - val_loss: 0.5337 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7529 - val_loss: 0.5425 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4918 - accuracy: 0.7562 - val_loss: 0.5332 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4852 - accuracy: 0.7588 - val_loss: 0.5373 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4801 - accuracy: 0.7628 - val_loss: 0.5459 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4714 - accuracy: 0.7681 - val_loss: 0.5419 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4674 - accuracy: 0.7687 - val_loss: 0.5439 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 15/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4608 - accuracy: 0.7738
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4616 - accuracy: 0.7734 - val_loss: 0.5457 - val_accuracy: 0.7274 - lr: 0.0010

271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4518458884951282
Confusion Matrix :
 [[2911 1412]
 [ 968 3355]]
Accuracy on test set:    0.7247281980106408
Sensitivity:    0.7760814249363868 	 Specificity:    0.6733749710848947
Precision  : 0.7037969372771135
Area Under Curve:    0.7247281980106407
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6128 - accuracy: 0.6626 - val_loss: 0.5695 - val_accuracy: 0.6999 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7096 - val_loss: 0.5547 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7213 - val_loss: 0.5458 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7281 - val_loss: 0.5474 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7338 - val_loss: 0.5551 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5199 - accuracy: 0.7379 - val_loss: 0.5422 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7440 - val_loss: 0.5331 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7469 - val_loss: 0.5343 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4963 - accuracy: 0.7527 - val_loss: 0.5360 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7557 - val_loss: 0.5331 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4845 - accuracy: 0.7605 - val_loss: 0.5386 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4762 - accuracy: 0.7651 - val_loss: 0.5397 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4705 - accuracy: 0.7691 - val_loss: 0.5489 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4656 - accuracy: 0.7722 - val_loss: 0.5404 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 15/400
249/274 [==========================>...] - ETA: 0s - loss: 0.4594 - accuracy: 0.7744
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4588 - accuracy: 0.7748 - val_loss: 0.5445 - val_accuracy: 0.7290 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.45558781707239676
Confusion Matrix :
 [[3097 1226]
 [1128 3195]]
Accuracy on test set:    0.727735368956743
Sensitivity:    0.7390700902151284 	 Specificity:    0.7164006476983577
Precision  : 0.7226871748473196
Area Under Curve:    0.727735368956743
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6084 - accuracy: 0.6644 - val_loss: 0.5731 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5630 - accuracy: 0.7085 - val_loss: 0.5529 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5492 - accuracy: 0.7189 - val_loss: 0.5454 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7247 - val_loss: 0.5462 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7310 - val_loss: 0.5403 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5227 - accuracy: 0.7364 - val_loss: 0.5406 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5157 - accuracy: 0.7402 - val_loss: 0.5417 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7449 - val_loss: 0.5394 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7473 - val_loss: 0.5414 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7527 - val_loss: 0.5444 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7550 - val_loss: 0.5403 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4881 - accuracy: 0.7575 - val_loss: 0.5375 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4795 - accuracy: 0.7635 - val_loss: 0.5430 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4742 - accuracy: 0.7652
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4747 - accuracy: 0.7650 - val_loss: 0.5449 - val_accuracy: 0.7217 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.45599534687689897
Confusion Matrix :
 [[3408  915]
 [1452 2871]]
Accuracy on test set:    0.7262317834836919
Sensitivity:    0.6641221374045801 	 Specificity:    0.7883414295628036
Precision  : 0.7583201267828843
Area Under Curve:    0.7262317834836918
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6109 - accuracy: 0.6636 - val_loss: 0.5659 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5636 - accuracy: 0.7071 - val_loss: 0.5528 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5492 - accuracy: 0.7191 - val_loss: 0.5485 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7250 - val_loss: 0.5441 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7310 - val_loss: 0.5426 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7347 - val_loss: 0.5389 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7405 - val_loss: 0.5407 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7453 - val_loss: 0.5341 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5042 - accuracy: 0.7476 - val_loss: 0.5414 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7531 - val_loss: 0.5383 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7552 - val_loss: 0.5388 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4855 - accuracy: 0.7604 - val_loss: 0.5393 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4768 - accuracy: 0.7640
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4777 - accuracy: 0.7633 - val_loss: 0.5449 - val_accuracy: 0.7316 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.5029239879088123
Confusion Matrix :
 [[3178 1145]
 [1005 3318]]
Accuracy on test set:    0.7513300948415452
Sensitivity:    0.7675225537820958 	 Specificity:    0.7351376359009947
Precision  : 0.7434461124803944
Area Under Curve:    0.7513300948415451
(8646, 4352) (8646,)
Mean MCC = 0.4462 + 0.0227 and Mean AUC = 0.7225 + 0.0114
Mean Sensitivity = 0.7414 + 0.0315 and Mean Specificity = 0.7036 + 0.0363 and Mean Accuracy = 0.7225 + 0.0114
Mean Precision = 0.7155 + 0.0202





Seed   : 941984
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6018 - accuracy: 0.6731 - val_loss: 0.5623 - val_accuracy: 0.7077 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5551 - accuracy: 0.7139 - val_loss: 0.5476 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7263 - val_loss: 0.5391 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7313 - val_loss: 0.5352 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7382 - val_loss: 0.5431 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7422 - val_loss: 0.5315 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7469 - val_loss: 0.5331 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7491 - val_loss: 0.5350 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7528 - val_loss: 0.5275 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4878 - accuracy: 0.7579 - val_loss: 0.5331 - val_accuracy: 0.7331 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4839 - accuracy: 0.7617 - val_loss: 0.5338 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4760 - accuracy: 0.7655 - val_loss: 0.5321 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4706 - accuracy: 0.7679 - val_loss: 0.5374 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4631 - accuracy: 0.7740 - val_loss: 0.5423 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 15/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4582 - accuracy: 0.7777
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4583 - accuracy: 0.7773 - val_loss: 0.5429 - val_accuracy: 0.7312 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4171969128248575
Confusion Matrix :
 [[3116 1207]
 [1313 3010]]
Accuracy on test set:    0.7085357390700903
Sensitivity:    0.6962757344436734 	 Specificity:    0.720795743696507
Precision  : 0.7137775669907517
Area Under Curve:    0.7085357390700903
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6034 - accuracy: 0.6674 - val_loss: 0.5620 - val_accuracy: 0.7020 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5565 - accuracy: 0.7114 - val_loss: 0.5563 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7222 - val_loss: 0.5519 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7290 - val_loss: 0.5397 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7350 - val_loss: 0.5349 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7397 - val_loss: 0.5337 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7441 - val_loss: 0.5302 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5037 - accuracy: 0.7474 - val_loss: 0.5372 - val_accuracy: 0.7331 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7507 - val_loss: 0.5464 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7541 - val_loss: 0.5405 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4866 - accuracy: 0.7585 - val_loss: 0.5361 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7579 - val_loss: 0.5321 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4781 - accuracy: 0.7634 - val_loss: 0.5365 - val_accuracy: 0.7379 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4707 - accuracy: 0.7664 - val_loss: 0.5364 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4646 - accuracy: 0.7703 - val_loss: 0.5367 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4570 - accuracy: 0.7751 - val_loss: 0.5481 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4514 - accuracy: 0.7777 - val_loss: 0.5531 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4454 - accuracy: 0.7792
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4455 - accuracy: 0.7790 - val_loss: 0.5523 - val_accuracy: 0.7291 - lr: 0.0010
271/271 [==============================] - 0s 638us/step
Independent Testing Matthews Correlation:  0.42631815452197624
Confusion Matrix :
 [[3182 1141]
 [1341 2982]]
Accuracy on test set:    0.7129308350682396
Sensitivity:    0.6897987508674531 	 Specificity:    0.7360629192690261
Precision  : 0.7232597623089984
Area Under Curve:    0.7129308350682397
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6176 - accuracy: 0.6564 - val_loss: 0.5660 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5613 - accuracy: 0.7087 - val_loss: 0.5468 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7186 - val_loss: 0.5445 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7242 - val_loss: 0.5486 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7306 - val_loss: 0.5419 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7344 - val_loss: 0.5353 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7384 - val_loss: 0.5386 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5130 - accuracy: 0.7406 - val_loss: 0.5404 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5073 - accuracy: 0.7453 - val_loss: 0.5358 - val_accuracy: 0.7292 - lr: 0.0010

Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5006 - accuracy: 0.7486 - val_loss: 0.5355 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7518 - val_loss: 0.5336 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7563 - val_loss: 0.5367 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7600 - val_loss: 0.5398 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7590 - val_loss: 0.5392 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4699 - accuracy: 0.7664 - val_loss: 0.5539 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4703 - accuracy: 0.7647
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4705 - accuracy: 0.7644 - val_loss: 0.5457 - val_accuracy: 0.7271 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.4413800178843032
Confusion Matrix :
 [[3136 1187]
 [1228 3095]]
Accuracy on test set:    0.7206800832755031
Sensitivity:    0.7159380060143419 	 Specificity:    0.7254221605366643
Precision  : 0.7227930873423634
Area Under Curve:    0.7206800832755031
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6045 - accuracy: 0.6666 - val_loss: 0.5634 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5595 - accuracy: 0.7122 - val_loss: 0.5534 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7263 - val_loss: 0.5384 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7313 - val_loss: 0.5364 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7356 - val_loss: 0.5341 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7398 - val_loss: 0.5350 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5125 - accuracy: 0.7442 - val_loss: 0.5313 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7507 - val_loss: 0.5418 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7534 - val_loss: 0.5319 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4949 - accuracy: 0.7552 - val_loss: 0.5365 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7612 - val_loss: 0.5357 - val_accuracy: 0.7340 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4801 - accuracy: 0.7639 - val_loss: 0.5512 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4723 - accuracy: 0.7688 - val_loss: 0.5399 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4682 - accuracy: 0.7705 - val_loss: 0.5459 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4607 - accuracy: 0.7770 - val_loss: 0.5453 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 16/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4547 - accuracy: 0.7791
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4558 - accuracy: 0.7783 - val_loss: 0.5463 - val_accuracy: 0.7280 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.420564076791643
Confusion Matrix :
 [[3048 1275]
 [1230 3093]]
Accuracy on test set:    0.7102706453851492
Sensitivity:    0.7154753643303262 	 Specificity:    0.7050659264399722
Precision  : 0.7081043956043956
Area Under Curve:    0.7102706453851493
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6148 - accuracy: 0.6582 - val_loss: 0.5606 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7095 - val_loss: 0.5479 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7193 - val_loss: 0.5404 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7282 - val_loss: 0.5330 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5277 - accuracy: 0.7323 - val_loss: 0.5374 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7372 - val_loss: 0.5382 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7421 - val_loss: 0.5366 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5096 - accuracy: 0.7448 - val_loss: 0.5314 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7498 - val_loss: 0.5347 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7547 - val_loss: 0.5313 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7565 - val_loss: 0.5305 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7623 - val_loss: 0.5440 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4778 - accuracy: 0.7649
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7650 - val_loss: 0.5371 - val_accuracy: 0.7269 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.43381135945223936
Confusion Matrix :
 [[3016 1307]
 [1142 3181]]
Accuracy on test set:    0.7167476289613695
Sensitivity:    0.7358315984270183 	 Specificity:    0.6976636594957205
Precision  : 0.7087789661319073
Area Under Curve:    0.7167476289613695
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6120 - accuracy: 0.6601 - val_loss: 0.5666 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5627 - accuracy: 0.7092 - val_loss: 0.5509 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5492 - accuracy: 0.7188 - val_loss: 0.5447 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7265 - val_loss: 0.5380 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5290 - accuracy: 0.7344 - val_loss: 0.5318 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5223 - accuracy: 0.7355 - val_loss: 0.5353 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 7/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7409 - val_loss: 0.5390 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7442 - val_loss: 0.5353 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7492 - val_loss: 0.5334 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7512 - val_loss: 0.5379 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7563 - val_loss: 0.5508 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4858 - accuracy: 0.7590 - val_loss: 0.5397 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4801 - accuracy: 0.7651 - val_loss: 0.5380 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4731 - accuracy: 0.7682
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4735 - accuracy: 0.7680 - val_loss: 0.5447 - val_accuracy: 0.7309 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.45250019058611357
Confusion Matrix :
 [[3167 1156]
 [1211 3112]]
Accuracy on test set:    0.7262317834836919
Sensitivity:    0.7198704603284756 	 Specificity:    0.7325931066389082
Precision  : 0.7291471415182755
Area Under Curve:    0.726231783483692
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6094 - accuracy: 0.6643 - val_loss: 0.5623 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7090 - val_loss: 0.5536 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7225 - val_loss: 0.5425 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7277 - val_loss: 0.5390 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7363 - val_loss: 0.5384 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7395 - val_loss: 0.5348 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5105 - accuracy: 0.7449 - val_loss: 0.5361 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7469 - val_loss: 0.5371 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7512 - val_loss: 0.5369 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4901 - accuracy: 0.7589 - val_loss: 0.5416 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4852 - accuracy: 0.7588 - val_loss: 0.5482 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4808 - accuracy: 0.7623
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7622 - val_loss: 0.5421 - val_accuracy: 0.7241 - lr: 0.0010
271/271 [==============================] - 0s 676us/step
Independent Testing Matthews Correlation:  0.4587591680466288
Confusion Matrix :
 [[2979 1344]
 [1002 3321]]
Accuracy on test set:    0.7286606523247745
Sensitivity:    0.7682165163081194 	 Specificity:    0.6891047883414295
Precision  : 0.7118971061093248
Area Under Curve:    0.7286606523247745
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6337 - accuracy: 0.6444 - val_loss: 0.5687 - val_accuracy: 0.7026 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5695 - accuracy: 0.7033 - val_loss: 0.5519 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5525 - accuracy: 0.7164 - val_loss: 0.5485 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7240 - val_loss: 0.5395 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7285 - val_loss: 0.5405 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5274 - accuracy: 0.7327 - val_loss: 0.5368 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5220 - accuracy: 0.7376 - val_loss: 0.5342 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7399 - val_loss: 0.5353 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5122 - accuracy: 0.7428 - val_loss: 0.5349 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7441 - val_loss: 0.5298 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5002 - accuracy: 0.7502 - val_loss: 0.5323 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7544 - val_loss: 0.5342 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4898 - accuracy: 0.7580 - val_loss: 0.5377 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4818 - accuracy: 0.7613 - val_loss: 0.5382 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7641 - val_loss: 0.5371 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4714 - accuracy: 0.7680
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4715 - accuracy: 0.7680 - val_loss: 0.5481 - val_accuracy: 0.7241 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.45233856864266925
Confusion Matrix :
 [[3055 1268]
 [1101 3222]]
Accuracy on test set:    0.726000462641684
Sensitivity:    0.7453157529493407 	 Specificity:    0.7066851723340273
Precision  : 0.7175946547884187
Area Under Curve:    0.726000462641684
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6089 - accuracy: 0.6659 - val_loss: 0.5624 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5617 - accuracy: 0.7072 - val_loss: 0.5577 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7201 - val_loss: 0.5431 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7277 - val_loss: 0.5401 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5264 - accuracy: 0.7353 - val_loss: 0.5355 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5213 - accuracy: 0.7380 - val_loss: 0.5461 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7408 - val_loss: 0.5370 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7457 - val_loss: 0.5560 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7488 - val_loss: 0.5429 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4942 - accuracy: 0.7541 - val_loss: 0.5428 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7562 - val_loss: 0.5393 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.7601 - val_loss: 0.5399 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4781 - accuracy: 0.7646 - val_loss: 0.5474 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 14/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4706 - accuracy: 0.7677
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4711 - accuracy: 0.7675 - val_loss: 0.5441 - val_accuracy: 0.7267 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4761056934913432
Confusion Matrix :
 [[3160 1163]
 [1102 3221]]
Accuracy on test set:    0.738029146426093
Sensitivity:    0.7450844321073329 	 Specificity:    0.7309738607448532
Precision  : 0.7347171532846716
Area Under Curve:    0.738029146426093
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6114 - accuracy: 0.6656 - val_loss: 0.5698 - val_accuracy: 0.6973 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5617 - accuracy: 0.7088 - val_loss: 0.5457 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5484 - accuracy: 0.7180 - val_loss: 0.5573 - val_accuracy: 0.7070 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7258 - val_loss: 0.5440 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7325 - val_loss: 0.5397 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7350 - val_loss: 0.5580 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7437 - val_loss: 0.5378 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7461 - val_loss: 0.5356 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7505 - val_loss: 0.5360 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4964 - accuracy: 0.7527 - val_loss: 0.5370 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7569 - val_loss: 0.5441 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4810 - accuracy: 0.7616
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7615 - val_loss: 0.5377 - val_accuracy: 0.7272 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.49914318696683385
Confusion Matrix :
 [[3349  974]
 [1194 3129]]
Accuracy on test set:    0.7492482072634744
Sensitivity:    0.7238029146426093 	 Specificity:    0.7746934998843396
Precision  : 0.7626127223982452
Area Under Curve:    0.7492482072634744
(8646, 4352) (8646,)
Mean MCC = 0.4478 + 0.0244 and Mean AUC = 0.7237 + 0.0122
Mean Sensitivity = 0.7256 + 0.0225 and Mean Specificity = 0.7219 + 0.0232 and Mean Accuracy = 0.7237 + 0.0122
Mean Precision = 0.7233 + 0.0155





Seed   : 118337
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6122 - accuracy: 0.6607 - val_loss: 0.5737 - val_accuracy: 0.6874 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5605 - accuracy: 0.7103 - val_loss: 0.5481 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7225 - val_loss: 0.5399 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7275 - val_loss: 0.5391 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5297 - accuracy: 0.7300 - val_loss: 0.5337 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7361 - val_loss: 0.5299 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7407 - val_loss: 0.5339 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7407 - val_loss: 0.5314 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7454 - val_loss: 0.5285 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7507 - val_loss: 0.5340 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4966 - accuracy: 0.7513 - val_loss: 0.5330 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7554 - val_loss: 0.5318 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4816 - accuracy: 0.7607 - val_loss: 0.5314 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4768 - accuracy: 0.7645 - val_loss: 0.5385 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4718 - accuracy: 0.7668 - val_loss: 0.5356 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7682 - val_loss: 0.5427 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4594 - accuracy: 0.7731 - val_loss: 0.5456 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4534 - accuracy: 0.7756 - val_loss: 0.5431 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 19/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4477 - accuracy: 0.7791
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4477 - accuracy: 0.7792 - val_loss: 0.5565 - val_accuracy: 0.7267 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4361635746298617
Confusion Matrix :
 [[2936 1387]
 [1056 3267]]
Accuracy on test set:    0.7174415914873931
Sensitivity:    0.7557251908396947 	 Specificity:    0.6791579921350914
Precision  : 0.7019767941555651
Area Under Curve:    0.7174415914873931
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6043 - accuracy: 0.6698 - val_loss: 0.5614 - val_accuracy: 0.7077 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5577 - accuracy: 0.7148 - val_loss: 0.5461 - val_accuracy: 0.7174 - lr: 0.0010

Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7260 - val_loss: 0.5435 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7326 - val_loss: 0.5367 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7371 - val_loss: 0.5360 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7405 - val_loss: 0.5384 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7432 - val_loss: 0.5376 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5037 - accuracy: 0.7487 - val_loss: 0.5368 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7513 - val_loss: 0.5357 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7548 - val_loss: 0.5436 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4859 - accuracy: 0.7582 - val_loss: 0.5383 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7624 - val_loss: 0.5424 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4735 - accuracy: 0.7645 - val_loss: 0.5421 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4685 - accuracy: 0.7689 - val_loss: 0.5547 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4648 - accuracy: 0.7699 - val_loss: 0.5475 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4568 - accuracy: 0.7755 - val_loss: 0.5527 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4499 - accuracy: 0.7779 - val_loss: 0.5544 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4429 - accuracy: 0.7827
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4436 - accuracy: 0.7823 - val_loss: 0.5566 - val_accuracy: 0.7218 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.42984271595738394
Confusion Matrix :
 [[3123 1200]
 [1265 3058]]
Accuracy on test set:    0.7148970622253065
Sensitivity:    0.7073791348600509 	 Specificity:    0.7224149895905622
Precision  : 0.7181775481446688
Area Under Curve:    0.7148970622253064
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6107 - accuracy: 0.6631 - val_loss: 0.5670 - val_accuracy: 0.7033 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7101 - val_loss: 0.5537 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7232 - val_loss: 0.5417 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7285 - val_loss: 0.5451 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7338 - val_loss: 0.5381 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7383 - val_loss: 0.5388 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5112 - accuracy: 0.7426 - val_loss: 0.5412 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7466 - val_loss: 0.5408 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7496 - val_loss: 0.5370 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7534 - val_loss: 0.5452 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4842 - accuracy: 0.7581 - val_loss: 0.5458 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4782 - accuracy: 0.7626
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4782 - accuracy: 0.7629 - val_loss: 0.5440 - val_accuracy: 0.7190 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.4571009889568332
Confusion Matrix :
 [[3028 1295]
 [1055 3268]]
Accuracy on test set:    0.7281980106407587
Sensitivity:    0.7559565116817025 	 Specificity:    0.7004395095998149
Precision  : 0.7161954854262547
Area Under Curve:    0.7281980106407588
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6274 - accuracy: 0.6491 - val_loss: 0.5704 - val_accuracy: 0.6987 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5667 - accuracy: 0.7054 - val_loss: 0.5526 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7189 - val_loss: 0.5475 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7262 - val_loss: 0.5423 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5292 - accuracy: 0.7335 - val_loss: 0.5421 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7386 - val_loss: 0.5389 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7427 - val_loss: 0.5411 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7463 - val_loss: 0.5421 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7493 - val_loss: 0.5419 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7519 - val_loss: 0.5445 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7563 - val_loss: 0.5434 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7606 - val_loss: 0.5440 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4797 - accuracy: 0.7630
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4796 - accuracy: 0.7629 - val_loss: 0.5488 - val_accuracy: 0.7226 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.44139649929040364
Confusion Matrix :
 [[2939 1384]
 [1037 3286]]
Accuracy on test set:    0.7199861207494795
Sensitivity:    0.760120286837844 	 Specificity:    0.6798519546611149
Precision  : 0.7036402569593148
Area Under Curve:    0.7199861207494795
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6002 - accuracy: 0.6717 - val_loss: 0.5699 - val_accuracy: 0.6994 - lr: 0.0010
Epoch 2/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5560 - accuracy: 0.7124 - val_loss: 0.5478 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7257 - val_loss: 0.5496 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7315 - val_loss: 0.5397 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7353 - val_loss: 0.5392 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7403 - val_loss: 0.5622 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7418 - val_loss: 0.5383 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7474 - val_loss: 0.5404 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 9/400
259/274 [===========================>..] - ETA: 0s - loss: 0.5022 - accuracy: 0.7485
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7486 - val_loss: 0.5405 - val_accuracy: 0.7185 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4431889294394451
Confusion Matrix :
 [[2999 1324]
 [1086 3237]]
Accuracy on test set:    0.7212583853805228
Sensitivity:    0.7487855655794587 	 Specificity:    0.6937312051815868
Precision  : 0.7097127822845867
Area Under Curve:    0.7212583853805228
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6164 - accuracy: 0.6593 - val_loss: 0.5669 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5598 - accuracy: 0.7112 - val_loss: 0.5478 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7235 - val_loss: 0.5445 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7304 - val_loss: 0.5399 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7362 - val_loss: 0.5374 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7393 - val_loss: 0.5353 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7435 - val_loss: 0.5356 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5065 - accuracy: 0.7468 - val_loss: 0.5441 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7528 - val_loss: 0.5403 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7567 - val_loss: 0.5380 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4837 - accuracy: 0.7617 - val_loss: 0.5459 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4788 - accuracy: 0.7636 - val_loss: 0.5410 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4721 - accuracy: 0.7670 - val_loss: 0.5486 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4672 - accuracy: 0.7699 - val_loss: 0.5442 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4612 - accuracy: 0.7743 - val_loss: 0.5453 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4556 - accuracy: 0.7761 - val_loss: 0.5525 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4500 - accuracy: 0.7810 - val_loss: 0.5631 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4428 - accuracy: 0.7826 - val_loss: 0.5536 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4351 - accuracy: 0.7883 - val_loss: 0.5657 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 20/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4321 - accuracy: 0.7873
Epoch 20: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4321 - accuracy: 0.7875 - val_loss: 0.5749 - val_accuracy: 0.7192 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.4333425600811138
Confusion Matrix :
 [[2989 1334]
 [1118 3205]]
Accuracy on test set:    0.7164006476983577
Sensitivity:    0.741383298635207 	 Specificity:    0.6914179967615082
Precision  : 0.7061026657854153
Area Under Curve:    0.7164006476983575
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6004 - accuracy: 0.6706 - val_loss: 0.5632 - val_accuracy: 0.7023 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5549 - accuracy: 0.7149 - val_loss: 0.5492 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7237 - val_loss: 0.5507 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5319 - accuracy: 0.7311 - val_loss: 0.5487 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5247 - accuracy: 0.7345 - val_loss: 0.5598 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5199 - accuracy: 0.7388 - val_loss: 0.5389 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5083 - accuracy: 0.7444 - val_loss: 0.5406 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7478 - val_loss: 0.5426 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4974 - accuracy: 0.7526 - val_loss: 0.5399 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7564 - val_loss: 0.5445 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4876 - accuracy: 0.7581
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7577 - val_loss: 0.5420 - val_accuracy: 0.7181 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.451035632145631
Confusion Matrix :
 [[2982 1341]
 [1037 3286]]
Accuracy on test set:    0.7249595188526486
Sensitivity:    0.760120286837844 	 Specificity:    0.6897987508674531
Precision  : 0.7101793818889129
Area Under Curve:    0.7249595188526486
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6028 - accuracy: 0.6711 - val_loss: 0.5638 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7147 - val_loss: 0.5534 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7247 - val_loss: 0.5557 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7306 - val_loss: 0.5517 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7361 - val_loss: 0.5435 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5149 - accuracy: 0.7429 - val_loss: 0.5383 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7470 - val_loss: 0.5434 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7507 - val_loss: 0.5404 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7562 - val_loss: 0.5467 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7611 - val_loss: 0.5553 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4828 - accuracy: 0.7627
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7628 - val_loss: 0.5455 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.46427652540228326
Confusion Matrix :
 [[3009 1314]
 [1007 3316]]
Accuracy on test set:    0.7315521628498728
Sensitivity:    0.76705991209808 	 Specificity:    0.6960444136016655
Precision  : 0.7161987041036717
Area Under Curve:    0.7315521628498727
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6047 - accuracy: 0.6675 - val_loss: 0.5649 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7131 - val_loss: 0.5510 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7245 - val_loss: 0.5575 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7324 - val_loss: 0.5427 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7359 - val_loss: 0.5425 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7407 - val_loss: 0.5449 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7493 - val_loss: 0.5476 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7488 - val_loss: 0.5519 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4954 - accuracy: 0.7562 - val_loss: 0.5511 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7570 - val_loss: 0.5440 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4837 - accuracy: 0.7612
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4834 - accuracy: 0.7611 - val_loss: 0.5575 - val_accuracy: 0.7197 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.462053938941884
Confusion Matrix :
 [[2903 1420]
 [ 919 3404]]
Accuracy on test set:    0.729470275271802
Sensitivity:    0.7874161461947722 	 Specificity:    0.6715244043488319
Precision  : 0.7056384742951907
Area Under Curve:    0.7294702752718019
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6133 - accuracy: 0.6593 - val_loss: 0.5757 - val_accuracy: 0.6996 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5647 - accuracy: 0.7073 - val_loss: 0.5582 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5503 - accuracy: 0.7191 - val_loss: 0.5490 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7265 - val_loss: 0.5483 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7280 - val_loss: 0.5519 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7343 - val_loss: 0.5436 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5202 - accuracy: 0.7400 - val_loss: 0.5468 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5150 - accuracy: 0.7410 - val_loss: 0.5457 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7462 - val_loss: 0.5494 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7508 - val_loss: 0.5498 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7516 - val_loss: 0.5458 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 12/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4908 - accuracy: 0.7581
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7576 - val_loss: 0.5584 - val_accuracy: 0.7172 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4854295629216047
Confusion Matrix :
 [[3084 1239]
 [ 989 3334]]
Accuracy on test set:    0.7423085820032385
Sensitivity:    0.7712236872542216 	 Specificity:    0.7133934767522554
Precision  : 0.7290618849770392
Area Under Curve:    0.7423085820032385
(8646, 4352) (8646,)
Mean MCC = 0.4504 + 0.0163 and Mean AUC = 0.7246 + 0.0080
Mean Sensitivity = 0.7555 + 0.0200 and Mean Specificity = 0.6938 + 0.0148 and Mean Accuracy = 0.7246 + 0.0080
Mean Precision = 0.7117 + 0.0079





Seed   : 775260
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6052 - accuracy: 0.6690 - val_loss: 0.5643 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5595 - accuracy: 0.7127 - val_loss: 0.5459 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7206 - val_loss: 0.5394 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7296 - val_loss: 0.5374 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7332 - val_loss: 0.5367 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5199 - accuracy: 0.7391 - val_loss: 0.5339 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7428 - val_loss: 0.5320 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7459 - val_loss: 0.5314 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7493 - val_loss: 0.5325 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4966 - accuracy: 0.7544 - val_loss: 0.5388 - val_accuracy: 0.7168 - lr: 0.0010

Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7566 - val_loss: 0.5366 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7597 - val_loss: 0.5359 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4802 - accuracy: 0.7626
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7618 - val_loss: 0.5477 - val_accuracy: 0.7160 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.40242388062439377
Confusion Matrix :
 [[3203 1120]
 [1469 2854]]
Accuracy on test set:    0.7005551700208189
Sensitivity:    0.6601896830904465 	 Specificity:    0.7409206569511912
Precision  : 0.7181680926019124
Area Under Curve:    0.7005551700208188
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6141 - accuracy: 0.6599 - val_loss: 0.5673 - val_accuracy: 0.7021 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5621 - accuracy: 0.7107 - val_loss: 0.5517 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7238 - val_loss: 0.5466 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7296 - val_loss: 0.5397 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5272 - accuracy: 0.7330 - val_loss: 0.5438 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7399 - val_loss: 0.5431 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7406 - val_loss: 0.5400 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7473 - val_loss: 0.5393 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5022 - accuracy: 0.7499
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5025 - accuracy: 0.7494 - val_loss: 0.5375 - val_accuracy: 0.7219 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4325857876995767
Confusion Matrix :
 [[3237 1086]
 [1371 2952]]
Accuracy on test set:    0.7158223455933379
Sensitivity:    0.6828591256072172 	 Specificity:    0.7487855655794587
Precision  : 0.7310549777117384
Area Under Curve:    0.7158223455933379
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6185 - accuracy: 0.6540 - val_loss: 0.5672 - val_accuracy: 0.7016 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5645 - accuracy: 0.7085 - val_loss: 0.5493 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7211 - val_loss: 0.5406 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7260 - val_loss: 0.5403 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5307 - accuracy: 0.7310 - val_loss: 0.5378 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5247 - accuracy: 0.7350 - val_loss: 0.5370 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5177 - accuracy: 0.7396 - val_loss: 0.5335 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7440 - val_loss: 0.5356 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7460 - val_loss: 0.5402 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5003 - accuracy: 0.7499 - val_loss: 0.5374 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7534 - val_loss: 0.5430 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7543 - val_loss: 0.5398 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4830 - accuracy: 0.7601 - val_loss: 0.5390 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4810 - accuracy: 0.7621
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4812 - accuracy: 0.7619 - val_loss: 0.5487 - val_accuracy: 0.7254 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4372437004114779
Confusion Matrix :
 [[2866 1457]
 [ 987 3336]]
Accuracy on test set:    0.7173259310663891
Sensitivity:    0.7716863289382373 	 Specificity:    0.6629655331945409
Precision  : 0.6960150219069476
Area Under Curve:    0.7173259310663891
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6093 - accuracy: 0.6652 - val_loss: 0.5600 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5590 - accuracy: 0.7109 - val_loss: 0.5446 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7233 - val_loss: 0.5396 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5297 - accuracy: 0.7325 - val_loss: 0.5388 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7357 - val_loss: 0.5361 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7411 - val_loss: 0.5317 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7481 - val_loss: 0.5315 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7488 - val_loss: 0.5378 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4956 - accuracy: 0.7541 - val_loss: 0.5360 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7563 - val_loss: 0.5427 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 11/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4826 - accuracy: 0.7626
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7626 - val_loss: 0.5399 - val_accuracy: 0.7244 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.42843152090264736
Confusion Matrix :
 [[3064 1259]
 [1212 3111]]
Accuracy on test set:    0.7142030996992829
Sensitivity:    0.7196391394864677 	 Specificity:    0.7087670599120981
Precision  : 0.7118993135011442
Area Under Curve:    0.7142030996992829
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6042 - accuracy: 0.6708 - val_loss: 0.5593 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5562 - accuracy: 0.7146 - val_loss: 0.5463 - val_accuracy: 0.7161 - lr: 0.0010

Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7240 - val_loss: 0.5484 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7310 - val_loss: 0.5348 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5212 - accuracy: 0.7394 - val_loss: 0.5306 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5165 - accuracy: 0.7405 - val_loss: 0.5311 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7465 - val_loss: 0.5286 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7512 - val_loss: 0.5304 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4956 - accuracy: 0.7540 - val_loss: 0.5352 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4889 - accuracy: 0.7569 - val_loss: 0.5304 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4818 - accuracy: 0.7622 - val_loss: 0.5452 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4756 - accuracy: 0.7655 - val_loss: 0.5380 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7684 - val_loss: 0.5502 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4635 - accuracy: 0.7725
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4632 - accuracy: 0.7730 - val_loss: 0.5493 - val_accuracy: 0.7194 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.45203160350066796
Confusion Matrix :
 [[2996 1327]
 [1046 3277]]
Accuracy on test set:    0.7255378209576683
Sensitivity:    0.7580383992597733 	 Specificity:    0.6930372426555632
Precision  : 0.7117723718505647
Area Under Curve:    0.7255378209576684
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6101 - accuracy: 0.6680 - val_loss: 0.5604 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7102 - val_loss: 0.5528 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7215 - val_loss: 0.5408 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7285 - val_loss: 0.5382 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5252 - accuracy: 0.7350 - val_loss: 0.5363 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7389 - val_loss: 0.5325 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7434 - val_loss: 0.5269 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7472 - val_loss: 0.5321 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4951 - accuracy: 0.7532 - val_loss: 0.5269 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4899 - accuracy: 0.7549 - val_loss: 0.5318 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7623 - val_loss: 0.5354 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4760 - accuracy: 0.7651 - val_loss: 0.5360 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4700 - accuracy: 0.7674 - val_loss: 0.5352 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4624 - accuracy: 0.7711 - val_loss: 0.5445 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4558 - accuracy: 0.7766
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4558 - accuracy: 0.7767 - val_loss: 0.5446 - val_accuracy: 0.7195 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4334848607882648
Confusion Matrix :
 [[3029 1294]
 [1156 3167]]
Accuracy on test set:    0.7166319685403655
Sensitivity:    0.7325931066389082 	 Specificity:    0.7006708304418228
Precision  : 0.7099305088545169
Area Under Curve:    0.7166319685403655
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6137 - accuracy: 0.6598 - val_loss: 0.5708 - val_accuracy: 0.6994 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5648 - accuracy: 0.7070 - val_loss: 0.5490 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7199 - val_loss: 0.5395 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7281 - val_loss: 0.5354 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7320 - val_loss: 0.5382 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7361 - val_loss: 0.5342 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7394 - val_loss: 0.5366 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5091 - accuracy: 0.7453 - val_loss: 0.5398 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7475 - val_loss: 0.5383 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7482 - val_loss: 0.5368 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4949 - accuracy: 0.7534
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4947 - accuracy: 0.7536 - val_loss: 0.5444 - val_accuracy: 0.7262 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.4727971516560455
Confusion Matrix :
 [[3048 1275]
 [1008 3315]]
Accuracy on test set:    0.7359472588480223
Sensitivity:    0.7668285912560722 	 Specificity:    0.7050659264399722
Precision  : 0.7222222222222222
Area Under Curve:    0.7359472588480223
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6000 - accuracy: 0.6726 - val_loss: 0.5560 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7131 - val_loss: 0.5486 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7228 - val_loss: 0.5414 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7272 - val_loss: 0.5356 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5276 - accuracy: 0.7347 - val_loss: 0.5330 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5200 - accuracy: 0.7385 - val_loss: 0.5350 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7440 - val_loss: 0.5342 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7469 - val_loss: 0.5375 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7494 - val_loss: 0.5343 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7546 - val_loss: 0.5349 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7566 - val_loss: 0.5350 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7597 - val_loss: 0.5393 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4768 - accuracy: 0.7655 - val_loss: 0.5444 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7688 - val_loss: 0.5529 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4660 - accuracy: 0.7692
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4658 - accuracy: 0.7692 - val_loss: 0.5528 - val_accuracy: 0.7262 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.47026229560593424
Confusion Matrix :
 [[2996 1327]
 [ 970 3353]]
Accuracy on test set:    0.7343280129539671
Sensitivity:    0.775618783252371 	 Specificity:    0.6930372426555632
Precision  : 0.7164529914529915
Area Under Curve:    0.7343280129539672
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6126 - accuracy: 0.6637 - val_loss: 0.5613 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5644 - accuracy: 0.7079 - val_loss: 0.5464 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7206 - val_loss: 0.5376 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7270 - val_loss: 0.5353 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5295 - accuracy: 0.7329 - val_loss: 0.5353 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7344 - val_loss: 0.5344 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5157 - accuracy: 0.7414 - val_loss: 0.5327 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7431 - val_loss: 0.5339 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5057 - accuracy: 0.7475 - val_loss: 0.5299 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7514 - val_loss: 0.5312 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4949 - accuracy: 0.7549 - val_loss: 0.5304 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4901 - accuracy: 0.7554 - val_loss: 0.5348 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4822 - accuracy: 0.7612 - val_loss: 0.5342 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4765 - accuracy: 0.7644
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4764 - accuracy: 0.7648 - val_loss: 0.5398 - val_accuracy: 0.7237 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.4659912580624867
Confusion Matrix :
 [[3294 1029]
 [1283 3040]]
Accuracy on test set:    0.7325931066389082
Sensitivity:    0.7032153597039094 	 Specificity:    0.761970853573907
Precision  : 0.7471123126075203
Area Under Curve:    0.7325931066389083
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6109 - accuracy: 0.6661 - val_loss: 0.5612 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5649 - accuracy: 0.7073 - val_loss: 0.5508 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5493 - accuracy: 0.7193 - val_loss: 0.5437 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7261 - val_loss: 0.5437 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5304 - accuracy: 0.7319 - val_loss: 0.5364 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7346 - val_loss: 0.5359 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7409 - val_loss: 0.5352 - val_accuracy: 0.7343 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7435 - val_loss: 0.5327 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7464 - val_loss: 0.5330 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7475 - val_loss: 0.5379 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7511 - val_loss: 0.5334 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4909 - accuracy: 0.7567
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7566 - val_loss: 0.5401 - val_accuracy: 0.7221 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.48957424439250175
Confusion Matrix :
 [[3095 1228]
 [ 982 3341]]
Accuracy on test set:    0.7443904695813093
Sensitivity:    0.7728429331482767 	 Specificity:    0.7159380060143419
Precision  : 0.7312322171153425
Area Under Curve:    0.7443904695813093
(8646, 4352) (8646,)
Mean MCC = 0.4485 + 0.0249 and Mean AUC = 0.7237 + 0.0125
Mean Sensitivity = 0.7344 + 0.0394 and Mean Specificity = 0.7131 + 0.0283 and Mean Accuracy = 0.7237 + 0.0125
Mean Precision = 0.7196 + 0.0135





Seed   : 364684
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5987 - accuracy: 0.6746 - val_loss: 0.5666 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5557 - accuracy: 0.7120 - val_loss: 0.5520 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7251 - val_loss: 0.5427 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7296 - val_loss: 0.5427 - val_accuracy: 0.7242 - lr: 0.0010

Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5251 - accuracy: 0.7358 - val_loss: 0.5388 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7423 - val_loss: 0.5381 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7453 - val_loss: 0.5378 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5017 - accuracy: 0.7476 - val_loss: 0.5407 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7518 - val_loss: 0.5368 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7564 - val_loss: 0.5413 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4846 - accuracy: 0.7606
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4852 - accuracy: 0.7601 - val_loss: 0.5387 - val_accuracy: 0.7230 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4375413332620289
Confusion Matrix :
 [[2853 1470]
 [ 974 3349]]
Accuracy on test set:    0.7173259310663891
Sensitivity:    0.7746934998843396 	 Specificity:    0.6599583622484386
Precision  : 0.6949574600539531
Area Under Curve:    0.7173259310663891
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6111 - accuracy: 0.6605 - val_loss: 0.5735 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5622 - accuracy: 0.7084 - val_loss: 0.5617 - val_accuracy: 0.7028 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7224 - val_loss: 0.5476 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7288 - val_loss: 0.5422 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5264 - accuracy: 0.7322 - val_loss: 0.5416 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5190 - accuracy: 0.7375 - val_loss: 0.5373 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7410 - val_loss: 0.5454 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7440 - val_loss: 0.5414 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5022 - accuracy: 0.7485 - val_loss: 0.5363 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7518 - val_loss: 0.5384 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7548 - val_loss: 0.5385 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4841 - accuracy: 0.7593 - val_loss: 0.5414 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4788 - accuracy: 0.7609 - val_loss: 0.5448 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4733 - accuracy: 0.7656 - val_loss: 0.5456 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4683 - accuracy: 0.7671
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4685 - accuracy: 0.7672 - val_loss: 0.5494 - val_accuracy: 0.7263 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4320595713816625
Confusion Matrix :
 [[3158 1165]
 [1291 3032]]
Accuracy on test set:    0.7159380060143419
Sensitivity:    0.7013647929678464 	 Specificity:    0.7305112190608374
Precision  : 0.7224207767452943
Area Under Curve:    0.7159380060143419
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6086 - accuracy: 0.6632 - val_loss: 0.5695 - val_accuracy: 0.7012 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5578 - accuracy: 0.7122 - val_loss: 0.5544 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7234 - val_loss: 0.5528 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5294 - accuracy: 0.7322 - val_loss: 0.5453 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5199 - accuracy: 0.7372 - val_loss: 0.5482 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7426 - val_loss: 0.5466 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5065 - accuracy: 0.7484 - val_loss: 0.5422 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7509 - val_loss: 0.5506 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7537 - val_loss: 0.5474 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7591 - val_loss: 0.5463 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4780 - accuracy: 0.7656 - val_loss: 0.5485 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4706 - accuracy: 0.7681 - val_loss: 0.5551 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4645 - accuracy: 0.7721 - val_loss: 0.5553 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4577 - accuracy: 0.7767 - val_loss: 0.5569 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4523 - accuracy: 0.7791 - val_loss: 0.5708 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4447 - accuracy: 0.7815 - val_loss: 0.5566 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4421 - accuracy: 0.7837 - val_loss: 0.5717 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4307 - accuracy: 0.7905 - val_loss: 0.5950 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4237 - accuracy: 0.7948 - val_loss: 0.5780 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4209 - accuracy: 0.7935 - val_loss: 0.5834 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4134 - accuracy: 0.8008 - val_loss: 0.5856 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 22/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4083 - accuracy: 0.8010 - val_loss: 0.5837 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 23/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4004 - accuracy: 0.8068
Epoch 23: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4027 - accuracy: 0.8051 - val_loss: 0.5919 - val_accuracy: 0.7221 - lr: 0.0010

271/271 [==============================] - 0s 638us/step
Independent Testing Matthews Correlation:  0.41781508001801976
Confusion Matrix :
 [[2868 1455]
 [1069 3254]]
Accuracy on test set:    0.7080730973860745
Sensitivity:    0.7527180198935924 	 Specificity:    0.6634281748785565
Precision  : 0.6910172011042685
Area Under Curve:    0.7080730973860745
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6058 - accuracy: 0.6664 - val_loss: 0.5690 - val_accuracy: 0.7023 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5536 - accuracy: 0.7153 - val_loss: 0.5531 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7267 - val_loss: 0.5433 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5285 - accuracy: 0.7339 - val_loss: 0.5395 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7414 - val_loss: 0.5444 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5105 - accuracy: 0.7440 - val_loss: 0.5399 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7471 - val_loss: 0.5414 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4970 - accuracy: 0.7533 - val_loss: 0.5407 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4893 - accuracy: 0.7578 - val_loss: 0.5428 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4818 - accuracy: 0.7631 - val_loss: 0.5420 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4743 - accuracy: 0.7672 - val_loss: 0.5406 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4677 - accuracy: 0.7723 - val_loss: 0.5441 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4628 - accuracy: 0.7738 - val_loss: 0.5495 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4551 - accuracy: 0.7771 - val_loss: 0.5471 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4506 - accuracy: 0.7799 - val_loss: 0.5516 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4426 - accuracy: 0.7835
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4429 - accuracy: 0.7832 - val_loss: 0.5566 - val_accuracy: 0.7235 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4201126513826085
Confusion Matrix :
 [[3042 1281]
 [1226 3097]]
Accuracy on test set:    0.7100393245431413
Sensitivity:    0.7164006476983577 	 Specificity:    0.703678001387925
Precision  : 0.7074006395614436
Area Under Curve:    0.7100393245431413
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6136 - accuracy: 0.6615 - val_loss: 0.5638 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5618 - accuracy: 0.7106 - val_loss: 0.5550 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7219 - val_loss: 0.5444 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7286 - val_loss: 0.5399 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5294 - accuracy: 0.7325 - val_loss: 0.5430 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5247 - accuracy: 0.7355 - val_loss: 0.5429 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5194 - accuracy: 0.7386 - val_loss: 0.5400 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7439 - val_loss: 0.5406 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 9/400
260/274 [===========================>..] - ETA: 0s - loss: 0.5068 - accuracy: 0.7472
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7474 - val_loss: 0.5404 - val_accuracy: 0.7223 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.43869297012896535
Confusion Matrix :
 [[2836 1487]
 [ 954 3369]]
Accuracy on test set:    0.7176729123294009
Sensitivity:    0.7793199167244969 	 Specificity:    0.6560259079343049
Precision  : 0.6937808896210873
Area Under Curve:    0.717672912329401
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6009 - accuracy: 0.6700 - val_loss: 0.5705 - val_accuracy: 0.6985 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5560 - accuracy: 0.7131 - val_loss: 0.5487 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7247 - val_loss: 0.5410 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7326 - val_loss: 0.5431 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7369 - val_loss: 0.5371 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5197 - accuracy: 0.7398 - val_loss: 0.5360 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7450 - val_loss: 0.5418 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7473 - val_loss: 0.5383 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7512 - val_loss: 0.5482 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7519 - val_loss: 0.5453 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4883 - accuracy: 0.7593
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4890 - accuracy: 0.7587 - val_loss: 0.5385 - val_accuracy: 0.7221 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.44640158259049545
Confusion Matrix :
 [[3064 1259]
 [1135 3188]]
Accuracy on test set:    0.7231089521165857
Sensitivity:    0.7374508443210733 	 Specificity:    0.7087670599120981
Precision  : 0.7168877895210254
Area Under Curve:    0.7231089521165858
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6009 - accuracy: 0.6707 - val_loss: 0.5694 - val_accuracy: 0.7003 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5573 - accuracy: 0.7135 - val_loss: 0.5510 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7240 - val_loss: 0.5455 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7297 - val_loss: 0.5458 - val_accuracy: 0.7188 - lr: 0.0010

Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7333 - val_loss: 0.5431 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5206 - accuracy: 0.7387 - val_loss: 0.5448 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7426 - val_loss: 0.5401 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7472 - val_loss: 0.5385 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7504 - val_loss: 0.5374 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7551 - val_loss: 0.5562 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7537 - val_loss: 0.5413 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4891 - accuracy: 0.7586 - val_loss: 0.5471 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4837 - accuracy: 0.7624 - val_loss: 0.5565 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 14/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4790 - accuracy: 0.7656
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4790 - accuracy: 0.7654 - val_loss: 0.5489 - val_accuracy: 0.7226 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.45990858230665355
Confusion Matrix :
 [[2997 1326]
 [1014 3309]]
Accuracy on test set:    0.7293546148507981
Sensitivity:    0.765440666204025 	 Specificity:    0.6932685634975712
Precision  : 0.713915857605178
Area Under Curve:    0.7293546148507981
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5999 - accuracy: 0.6714 - val_loss: 0.5655 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5571 - accuracy: 0.7121 - val_loss: 0.5583 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7236 - val_loss: 0.5495 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7288 - val_loss: 0.5447 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5247 - accuracy: 0.7351 - val_loss: 0.5421 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7425 - val_loss: 0.5461 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7459 - val_loss: 0.5438 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7484 - val_loss: 0.5518 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7531 - val_loss: 0.5468 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7576 - val_loss: 0.5407 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4832 - accuracy: 0.7623 - val_loss: 0.5459 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4771 - accuracy: 0.7636 - val_loss: 0.5476 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4691 - accuracy: 0.7699 - val_loss: 0.5524 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4661 - accuracy: 0.7714 - val_loss: 0.5571 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4582 - accuracy: 0.7766
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4581 - accuracy: 0.7769 - val_loss: 0.5581 - val_accuracy: 0.7233 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4624856505828073
Confusion Matrix :
 [[3200 1123]
 [1201 3122]]
Accuracy on test set:    0.731205181586861
Sensitivity:    0.7221836687485542 	 Specificity:    0.7402266944251678
Precision  : 0.7354534746760896
Area Under Curve:    0.7312051815868609
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6108 - accuracy: 0.6619 - val_loss: 0.5733 - val_accuracy: 0.7003 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5628 - accuracy: 0.7091 - val_loss: 0.5675 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5495 - accuracy: 0.7176 - val_loss: 0.5565 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7290 - val_loss: 0.5521 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7319 - val_loss: 0.5506 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7350 - val_loss: 0.5471 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7414 - val_loss: 0.5497 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5119 - accuracy: 0.7433 - val_loss: 0.5488 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7499 - val_loss: 0.5490 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4990 - accuracy: 0.7524 - val_loss: 0.5453 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4924 - accuracy: 0.7574 - val_loss: 0.5557 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7589 - val_loss: 0.5585 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7614 - val_loss: 0.5469 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4780 - accuracy: 0.7653 - val_loss: 0.5485 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4741 - accuracy: 0.7676
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4748 - accuracy: 0.7672 - val_loss: 0.5552 - val_accuracy: 0.7125 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.481618023803578
Confusion Matrix :
 [[3066 1257]
 [ 988 3335]]
Accuracy on test set:    0.7403423548461716
Sensitivity:    0.7714550080962295 	 Specificity:    0.7092297015961138
Precision  : 0.7262630662020906
Area Under Curve:    0.7403423548461716
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6102 - accuracy: 0.6643 - val_loss: 0.5760 - val_accuracy: 0.6967 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5651 - accuracy: 0.7077 - val_loss: 0.5605 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7216 - val_loss: 0.5515 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7258 - val_loss: 0.5557 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7307 - val_loss: 0.5607 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5234 - accuracy: 0.7362 - val_loss: 0.5551 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7396 - val_loss: 0.5516 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7438 - val_loss: 0.5515 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7462 - val_loss: 0.5532 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7489 - val_loss: 0.5490 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7519 - val_loss: 0.5537 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7555 - val_loss: 0.5567 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7593 - val_loss: 0.5632 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4836 - accuracy: 0.7599 - val_loss: 0.5586 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4752 - accuracy: 0.7670 - val_loss: 0.5718 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4716 - accuracy: 0.7661
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4723 - accuracy: 0.7659 - val_loss: 0.5731 - val_accuracy: 0.7154 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.4923064044980156
Confusion Matrix :
 [[3193 1130]
 [1065 3258]]
Accuracy on test set:    0.7461253758963683
Sensitivity:    0.7536433032616239 	 Specificity:    0.7386074485311126
Precision  : 0.7424794895168642
Area Under Curve:    0.7461253758963683
(8646, 4352) (8646,)
Mean MCC = 0.4489 + 0.0236 and Mean AUC = 0.7239 + 0.0120
Mean Sensitivity = 0.7475 + 0.0256 and Mean Specificity = 0.7004 + 0.0302 and Mean Accuracy = 0.7239 + 0.0120
Mean Precision = 0.7145 + 0.0169





Seed   : 828140
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6068 - accuracy: 0.6657 - val_loss: 0.5571 - val_accuracy: 0.7070 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7116 - val_loss: 0.5452 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7262 - val_loss: 0.5359 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5300 - accuracy: 0.7339 - val_loss: 0.5382 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5240 - accuracy: 0.7366 - val_loss: 0.5285 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7406 - val_loss: 0.5318 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7471 - val_loss: 0.5328 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7491 - val_loss: 0.5413 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4964 - accuracy: 0.7536 - val_loss: 0.5332 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7575 - val_loss: 0.5293 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4822 - accuracy: 0.7611 - val_loss: 0.5300 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4761 - accuracy: 0.7651 - val_loss: 0.5371 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4723 - accuracy: 0.7683 - val_loss: 0.5343 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4641 - accuracy: 0.7735 - val_loss: 0.5365 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4592 - accuracy: 0.7736 - val_loss: 0.5373 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4512 - accuracy: 0.7791
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4507 - accuracy: 0.7796 - val_loss: 0.5556 - val_accuracy: 0.7277 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4178140993799986
Confusion Matrix :
 [[2915 1408]
 [1113 3210]]
Accuracy on test set:    0.7084200786490863
Sensitivity:    0.7425399028452464 	 Specificity:    0.6743002544529262
Precision  : 0.6951061065396276
Area Under Curve:    0.7084200786490863
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6073 - accuracy: 0.6670 - val_loss: 0.5571 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5604 - accuracy: 0.7119 - val_loss: 0.5515 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7209 - val_loss: 0.5435 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7254 - val_loss: 0.5362 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7318 - val_loss: 0.5365 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7355 - val_loss: 0.5342 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5178 - accuracy: 0.7404 - val_loss: 0.5325 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7430 - val_loss: 0.5407 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7454 - val_loss: 0.5355 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.5056 - accuracy: 0.7461
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7463 - val_loss: 0.5379 - val_accuracy: 0.7173 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4210889528809816
Confusion Matrix :
 [[2848 1475]
 [1037 3286]]
Accuracy on test set:    0.7094610224381217
Sensitivity:    0.760120286837844 	 Specificity:    0.6588017580383992
Precision  : 0.6901911363159
Area Under Curve:    0.7094610224381216
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6138 - accuracy: 0.6577 - val_loss: 0.5657 - val_accuracy: 0.7070 - lr: 0.0010

Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5613 - accuracy: 0.7096 - val_loss: 0.5439 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7219 - val_loss: 0.5370 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7281 - val_loss: 0.5384 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7322 - val_loss: 0.5329 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7365 - val_loss: 0.5335 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7408 - val_loss: 0.5316 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7433 - val_loss: 0.5339 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7495 - val_loss: 0.5324 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7516 - val_loss: 0.5355 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7560 - val_loss: 0.5326 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7592 - val_loss: 0.5375 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4836 - accuracy: 0.7589 - val_loss: 0.5423 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4779 - accuracy: 0.7634 - val_loss: 0.5414 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4702 - accuracy: 0.7681 - val_loss: 0.5467 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4625 - accuracy: 0.7721
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4632 - accuracy: 0.7715 - val_loss: 0.5443 - val_accuracy: 0.7241 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4343917695159106
Confusion Matrix :
 [[3034 1289]
 [1157 3166]]
Accuracy on test set:    0.7170946102243813
Sensitivity:    0.7323617857969003 	 Specificity:    0.7018274346518621
Precision  : 0.710662177328844
Area Under Curve:    0.7170946102243811
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6079 - accuracy: 0.6646 - val_loss: 0.5692 - val_accuracy: 0.6958 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7116 - val_loss: 0.5513 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7220 - val_loss: 0.5380 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7274 - val_loss: 0.5331 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5270 - accuracy: 0.7348 - val_loss: 0.5295 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5207 - accuracy: 0.7382 - val_loss: 0.5507 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5136 - accuracy: 0.7418 - val_loss: 0.5353 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7485 - val_loss: 0.5402 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5032 - accuracy: 0.7491 - val_loss: 0.5320 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4959 - accuracy: 0.7530
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7525 - val_loss: 0.5299 - val_accuracy: 0.7308 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.445788810182577
Confusion Matrix :
 [[3050 1273]
 [1124 3199]]
Accuracy on test set:    0.7227619708535739
Sensitivity:    0.7399953735831598 	 Specificity:    0.705528568123988
Precision  : 0.715339892665474
Area Under Curve:    0.722761970853574
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6094 - accuracy: 0.6629 - val_loss: 0.5564 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5586 - accuracy: 0.7119 - val_loss: 0.5433 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7226 - val_loss: 0.5384 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7280 - val_loss: 0.5360 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7350 - val_loss: 0.5334 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5196 - accuracy: 0.7391 - val_loss: 0.5300 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7424 - val_loss: 0.5377 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5054 - accuracy: 0.7478 - val_loss: 0.5300 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7504 - val_loss: 0.5319 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7543 - val_loss: 0.5359 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7581 - val_loss: 0.5355 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7626 - val_loss: 0.5357 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4760 - accuracy: 0.7657
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7654 - val_loss: 0.5327 - val_accuracy: 0.7286 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.43517026190670793
Confusion Matrix :
 [[3023 1300]
 [1143 3180]]
Accuracy on test set:    0.7174415914873931
Sensitivity:    0.7356002775850105 	 Specificity:    0.6992829053897757
Precision  : 0.7098214285714286
Area Under Curve:    0.717441591487393
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6040 - accuracy: 0.6692 - val_loss: 0.5590 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5605 - accuracy: 0.7107 - val_loss: 0.5530 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7227 - val_loss: 0.5386 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7294 - val_loss: 0.5401 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5272 - accuracy: 0.7347 - val_loss: 0.5382 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7405 - val_loss: 0.5356 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7429 - val_loss: 0.5396 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5065 - accuracy: 0.7461 - val_loss: 0.5406 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7484 - val_loss: 0.5386 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7526 - val_loss: 0.5435 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4877 - accuracy: 0.7603
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4881 - accuracy: 0.7596 - val_loss: 0.5377 - val_accuracy: 0.7254 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4372722088618565
Confusion Matrix :
 [[3025 1298]
 [1136 3187]]
Accuracy on test set:    0.7184825352764284
Sensitivity:    0.7372195234790655 	 Specificity:    0.6997455470737913
Precision  : 0.7105908584169454
Area Under Curve:    0.7184825352764285
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6044 - accuracy: 0.6678 - val_loss: 0.5678 - val_accuracy: 0.6987 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5615 - accuracy: 0.7111 - val_loss: 0.5498 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7213 - val_loss: 0.5427 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7279 - val_loss: 0.5400 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5281 - accuracy: 0.7350 - val_loss: 0.5388 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5214 - accuracy: 0.7391 - val_loss: 0.5400 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7421 - val_loss: 0.5456 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7449 - val_loss: 0.5345 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7487 - val_loss: 0.5366 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4986 - accuracy: 0.7531
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4987 - accuracy: 0.7530 - val_loss: 0.5378 - val_accuracy: 0.7215 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.46222192461394557
Confusion Matrix :
 [[3037 1286]
 [1042 3281]]
Accuracy on test set:    0.7307425399028452
Sensitivity:    0.7589636826278048 	 Specificity:    0.7025213971778858
Precision  : 0.7184147142544339
Area Under Curve:    0.7307425399028453
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6149 - accuracy: 0.6583 - val_loss: 0.5689 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.7081 - val_loss: 0.5527 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7221 - val_loss: 0.5475 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7260 - val_loss: 0.5453 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5306 - accuracy: 0.7323 - val_loss: 0.5416 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5218 - accuracy: 0.7372 - val_loss: 0.5427 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7416 - val_loss: 0.5542 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7439 - val_loss: 0.5364 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7483 - val_loss: 0.5459 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7514 - val_loss: 0.5446 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7568 - val_loss: 0.5407 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7578 - val_loss: 0.5450 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4802 - accuracy: 0.7600 - val_loss: 0.5430 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4729 - accuracy: 0.7651 - val_loss: 0.5486 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4675 - accuracy: 0.7671 - val_loss: 0.5504 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 16/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4647 - accuracy: 0.7690
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4646 - accuracy: 0.7690 - val_loss: 0.5530 - val_accuracy: 0.7265 - lr: 0.0010
271/271 [==============================] - 0s 666us/step
Independent Testing Matthews Correlation:  0.4612246595665042
Confusion Matrix :
 [[3222 1101]
 [1229 3094]]
Accuracy on test set:    0.7305112190608374
Sensitivity:    0.715706685172334 	 Specificity:    0.7453157529493407
Precision  : 0.7375446960667461
Area Under Curve:    0.7305112190608374
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6064 - accuracy: 0.6668 - val_loss: 0.5665 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7103 - val_loss: 0.5503 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7232 - val_loss: 0.5441 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7283 - val_loss: 0.5401 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5272 - accuracy: 0.7331 - val_loss: 0.5440 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5202 - accuracy: 0.7381 - val_loss: 0.5412 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7447 - val_loss: 0.5454 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7460 - val_loss: 0.5458 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7507 - val_loss: 0.5414 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 10/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4954 - accuracy: 0.7542 - val_loss: 0.5394 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7594 - val_loss: 0.5438 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7602 - val_loss: 0.5421 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4768 - accuracy: 0.7640 - val_loss: 0.5412 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4721 - accuracy: 0.7672 - val_loss: 0.5507 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4648 - accuracy: 0.7715
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4644 - accuracy: 0.7721 - val_loss: 0.5487 - val_accuracy: 0.7213 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.47560672125994885
Confusion Matrix :
 [[3120 1203]
 [1065 3258]]
Accuracy on test set:    0.7376821651630812
Sensitivity:    0.7536433032616239 	 Specificity:    0.7217210270645386
Precision  : 0.7303295225285811
Area Under Curve:    0.737682165163081
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6199 - accuracy: 0.6544 - val_loss: 0.5728 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5666 - accuracy: 0.7056 - val_loss: 0.5571 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5522 - accuracy: 0.7158 - val_loss: 0.5523 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7253 - val_loss: 0.5518 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7278 - val_loss: 0.5491 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5267 - accuracy: 0.7354 - val_loss: 0.5508 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5207 - accuracy: 0.7372 - val_loss: 0.5442 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7427 - val_loss: 0.5461 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7440 - val_loss: 0.5437 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5002 - accuracy: 0.7527 - val_loss: 0.5483 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7518 - val_loss: 0.5460 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7556 - val_loss: 0.5499 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7555 - val_loss: 0.5521 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4821 - accuracy: 0.7607 - val_loss: 0.5521 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4764 - accuracy: 0.7657
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4771 - accuracy: 0.7653 - val_loss: 0.5546 - val_accuracy: 0.7187 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.4914148882737737
Confusion Matrix :
 [[3344  979]
 [1223 3100]]
Accuracy on test set:    0.7453157529493407
Sensitivity:    0.7170946102243813 	 Specificity:    0.7735368956743003
Precision  : 0.7599901936749204
Area Under Curve:    0.7453157529493408
(8646, 4352) (8646,)
Mean MCC = 0.4482 + 0.0226 and Mean AUC = 0.7238 + 0.0114
Mean Sensitivity = 0.7393 + 0.0147 and Mean Specificity = 0.7083 + 0.0311 and Mean Accuracy = 0.7238 + 0.0114
Mean Precision = 0.7178 + 0.0194





Seed   : 138028
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6069 - accuracy: 0.6677 - val_loss: 0.5677 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5552 - accuracy: 0.7144 - val_loss: 0.5490 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7270 - val_loss: 0.5427 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5279 - accuracy: 0.7331 - val_loss: 0.5469 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7377 - val_loss: 0.5372 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7404 - val_loss: 0.5389 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7471 - val_loss: 0.5357 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7521 - val_loss: 0.5441 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7536 - val_loss: 0.5429 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7574 - val_loss: 0.5352 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7609 - val_loss: 0.5439 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7657 - val_loss: 0.5416 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4702 - accuracy: 0.7692 - val_loss: 0.5500 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4628 - accuracy: 0.7745 - val_loss: 0.5413 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4596 - accuracy: 0.7744 - val_loss: 0.5478 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4514 - accuracy: 0.7780 - val_loss: 0.5502 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 17/400
264/274 [===========================>..] - ETA: 0s - loss: 0.4467 - accuracy: 0.7822
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4472 - accuracy: 0.7819 - val_loss: 0.5478 - val_accuracy: 0.7232 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.4238193612555776
Confusion Matrix :
 [[2857 1466]
 [1034 3289]]
Accuracy on test set:    0.7108489474901689
Sensitivity:    0.7608142493638677 	 Specificity:    0.6608836456164701
Precision  : 0.6916929547844375
Area Under Curve:    0.7108489474901688
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6009 - accuracy: 0.6704 - val_loss: 0.5614 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7131 - val_loss: 0.5489 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7232 - val_loss: 0.5470 - val_accuracy: 0.7191 - lr: 0.0010

Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7272 - val_loss: 0.5460 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5261 - accuracy: 0.7337 - val_loss: 0.5418 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5192 - accuracy: 0.7383 - val_loss: 0.5415 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7419 - val_loss: 0.5417 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7460 - val_loss: 0.5407 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7498 - val_loss: 0.5396 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7528 - val_loss: 0.5404 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4899 - accuracy: 0.7573 - val_loss: 0.5433 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4852 - accuracy: 0.7586 - val_loss: 0.5427 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4785 - accuracy: 0.7636 - val_loss: 0.5426 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4711 - accuracy: 0.7685 - val_loss: 0.5508 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 15/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4656 - accuracy: 0.7703
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4668 - accuracy: 0.7698 - val_loss: 0.5499 - val_accuracy: 0.7186 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.416632423882444
Confusion Matrix :
 [[3085 1238]
 [1284 3039]]
Accuracy on test set:    0.7083044182280823
Sensitivity:    0.7029840388619014 	 Specificity:    0.7136247975942632
Precision  : 0.7105447743745616
Area Under Curve:    0.7083044182280824
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6036 - accuracy: 0.6700 - val_loss: 0.5644 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5574 - accuracy: 0.7118 - val_loss: 0.5559 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7242 - val_loss: 0.5452 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7287 - val_loss: 0.5475 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5225 - accuracy: 0.7376 - val_loss: 0.5406 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7404 - val_loss: 0.5372 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7441 - val_loss: 0.5397 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5022 - accuracy: 0.7488 - val_loss: 0.5346 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7546 - val_loss: 0.5386 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4877 - accuracy: 0.7594 - val_loss: 0.5419 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4837 - accuracy: 0.7609 - val_loss: 0.5416 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4761 - accuracy: 0.7655 - val_loss: 0.5455 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4715 - accuracy: 0.7685 - val_loss: 0.5538 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4639 - accuracy: 0.7735 - val_loss: 0.5514 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4614 - accuracy: 0.7739 - val_loss: 0.5530 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4544 - accuracy: 0.7776 - val_loss: 0.5504 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4466 - accuracy: 0.7823 - val_loss: 0.5581 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 18/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4425 - accuracy: 0.7851
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4423 - accuracy: 0.7852 - val_loss: 0.5655 - val_accuracy: 0.7204 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4368897817272267
Confusion Matrix :
 [[3196 1127]
 [1309 3014]]
Accuracy on test set:    0.7182512144344205
Sensitivity:    0.6972010178117048 	 Specificity:    0.7393014110571362
Precision  : 0.727843516058923
Area Under Curve:    0.7182512144344206
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6091 - accuracy: 0.6654 - val_loss: 0.5639 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5569 - accuracy: 0.7156 - val_loss: 0.5490 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7230 - val_loss: 0.5383 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7317 - val_loss: 0.5402 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7383 - val_loss: 0.5375 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5159 - accuracy: 0.7417 - val_loss: 0.5330 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7484 - val_loss: 0.5349 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7510 - val_loss: 0.5438 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7561 - val_loss: 0.5372 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4879 - accuracy: 0.7599 - val_loss: 0.5369 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4790 - accuracy: 0.7662
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4809 - accuracy: 0.7653 - val_loss: 0.5412 - val_accuracy: 0.7244 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4171395623358421
Confusion Matrix :
 [[3171 1152]
 [1370 2953]]
Accuracy on test set:    0.7083044182280823
Sensitivity:    0.6830904464492251 	 Specificity:    0.7335183900069396
Precision  : 0.7193666260657734
Area Under Curve:    0.7083044182280823
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6179 - accuracy: 0.6545 - val_loss: 0.5679 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5623 - accuracy: 0.7091 - val_loss: 0.5489 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7209 - val_loss: 0.5551 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7285 - val_loss: 0.5396 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7332 - val_loss: 0.5363 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7364 - val_loss: 0.5368 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7407 - val_loss: 0.5381 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7454 - val_loss: 0.5424 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7461 - val_loss: 0.5354 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4966 - accuracy: 0.7518 - val_loss: 0.5407 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4920 - accuracy: 0.7579
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7571 - val_loss: 0.5401 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 665us/step
Independent Testing Matthews Correlation:  0.43814334997776794
Confusion Matrix :
 [[3087 1236]
 [1193 3130]]
Accuracy on test set:    0.7190608373814481
Sensitivity:    0.7240342354846172 	 Specificity:    0.714087439278279
Precision  : 0.7169033440219881
Area Under Curve:    0.7190608373814481
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6105 - accuracy: 0.6606 - val_loss: 0.5610 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5619 - accuracy: 0.7080 - val_loss: 0.5504 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7225 - val_loss: 0.5408 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7290 - val_loss: 0.5399 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7331 - val_loss: 0.5405 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7351 - val_loss: 0.5410 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7398 - val_loss: 0.5368 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7447 - val_loss: 0.5388 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7467 - val_loss: 0.5374 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7514 - val_loss: 0.5395 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7550 - val_loss: 0.5402 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4866 - accuracy: 0.7580 - val_loss: 0.5417 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7597 - val_loss: 0.5440 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4757 - accuracy: 0.7637
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4757 - accuracy: 0.7640 - val_loss: 0.5488 - val_accuracy: 0.7267 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4390729085708556
Confusion Matrix :
 [[3134 1189]
 [1236 3087]]
Accuracy on test set:    0.7195234790654638
Sensitivity:    0.714087439278279 	 Specificity:    0.7249595188526486
Precision  : 0.7219363891487371
Area Under Curve:    0.7195234790654638
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6024 - accuracy: 0.6710 - val_loss: 0.5647 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5583 - accuracy: 0.7118 - val_loss: 0.5528 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7244 - val_loss: 0.5466 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7299 - val_loss: 0.5396 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7364 - val_loss: 0.5450 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5189 - accuracy: 0.7393 - val_loss: 0.5384 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7413 - val_loss: 0.5384 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5062 - accuracy: 0.7481 - val_loss: 0.5351 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7506 - val_loss: 0.5365 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4924 - accuracy: 0.7547 - val_loss: 0.5499 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4890 - accuracy: 0.7580 - val_loss: 0.5379 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4844 - accuracy: 0.7590 - val_loss: 0.5485 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4776 - accuracy: 0.7629 - val_loss: 0.5497 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 14/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4726 - accuracy: 0.7671
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4729 - accuracy: 0.7668 - val_loss: 0.5418 - val_accuracy: 0.7260 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.455329805323109
Confusion Matrix :
 [[3251 1072]
 [1285 3038]]
Accuracy on test set:    0.7273883876937312
Sensitivity:    0.7027527180198936 	 Specificity:    0.7520240573675688
Precision  : 0.7391727493917275
Area Under Curve:    0.7273883876937313
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6008 - accuracy: 0.6723 - val_loss: 0.5661 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5567 - accuracy: 0.7121 - val_loss: 0.5483 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7245 - val_loss: 0.5429 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7294 - val_loss: 0.5466 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7360 - val_loss: 0.5394 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7422 - val_loss: 0.5376 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5091 - accuracy: 0.7457 - val_loss: 0.5428 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7504 - val_loss: 0.5386 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7524 - val_loss: 0.5348 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7569 - val_loss: 0.5487 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7600 - val_loss: 0.5432 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4789 - accuracy: 0.7644 - val_loss: 0.5451 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4737 - accuracy: 0.7669 - val_loss: 0.5459 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4650 - accuracy: 0.7727
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4663 - accuracy: 0.7719 - val_loss: 0.5552 - val_accuracy: 0.7236 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.45836438071123314
Confusion Matrix :
 [[3201 1122]
 [1220 3103]]
Accuracy on test set:    0.7291232940087902
Sensitivity:    0.7177885727504049 	 Specificity:    0.7404580152671756
Precision  : 0.7344378698224852
Area Under Curve:    0.7291232940087903
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6146 - accuracy: 0.6615 - val_loss: 0.5732 - val_accuracy: 0.7011 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5635 - accuracy: 0.7096 - val_loss: 0.5526 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5488 - accuracy: 0.7185 - val_loss: 0.5468 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7278 - val_loss: 0.5445 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7315 - val_loss: 0.5414 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7366 - val_loss: 0.5384 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5159 - accuracy: 0.7410 - val_loss: 0.5377 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7453 - val_loss: 0.5401 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7497 - val_loss: 0.5395 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 10/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4996 - accuracy: 0.7511
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7510 - val_loss: 0.5415 - val_accuracy: 0.7217 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.47961422726686415
Confusion Matrix :
 [[3040 1283]
 [ 972 3351]]
Accuracy on test set:    0.7391857506361323
Sensitivity:    0.7751561415683553 	 Specificity:    0.7032153597039094
Precision  : 0.7231333621061717
Area Under Curve:    0.7391857506361322
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6082 - accuracy: 0.6628 - val_loss: 0.5658 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5625 - accuracy: 0.7088 - val_loss: 0.5540 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7190 - val_loss: 0.5492 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7242 - val_loss: 0.5486 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5301 - accuracy: 0.7324 - val_loss: 0.5447 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5221 - accuracy: 0.7380 - val_loss: 0.5586 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5165 - accuracy: 0.7393 - val_loss: 0.5386 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5122 - accuracy: 0.7430 - val_loss: 0.5439 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7474 - val_loss: 0.5404 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7513 - val_loss: 0.5417 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4899 - accuracy: 0.7579 - val_loss: 0.5495 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4861 - accuracy: 0.7591
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7583 - val_loss: 0.5492 - val_accuracy: 0.7199 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.5071882992973883
Confusion Matrix :
 [[3307 1016]
 [1115 3208]]
Accuracy on test set:    0.7535276428406199
Sensitivity:    0.7420772611612306 	 Specificity:    0.7649780245200093
Precision  : 0.759469696969697
Area Under Curve:    0.7535276428406199
(8646, 4352) (8646,)
Mean MCC = 0.4472 + 0.0273 and Mean AUC = 0.7234 + 0.0137
Mean Sensitivity = 0.7220 + 0.0277 and Mean Specificity = 0.7247 + 0.0277 and Mean Accuracy = 0.7234 + 0.0137
Mean Precision = 0.7245 + 0.0171





Seed   : 938118
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6075 - accuracy: 0.6644 - val_loss: 0.5691 - val_accuracy: 0.6997 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7118 - val_loss: 0.5471 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7219 - val_loss: 0.5458 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7283 - val_loss: 0.5362 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5252 - accuracy: 0.7358 - val_loss: 0.5358 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5205 - accuracy: 0.7375 - val_loss: 0.5331 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7430 - val_loss: 0.5333 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7479 - val_loss: 0.5349 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7503 - val_loss: 0.5313 - val_accuracy: 0.7283 - lr: 0.0010

Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7532 - val_loss: 0.5338 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 11/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4889 - accuracy: 0.7557
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7560 - val_loss: 0.5349 - val_accuracy: 0.7273 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4196650245017689
Confusion Matrix :
 [[2754 1569]
 [ 958 3365]]
Accuracy on test set:    0.7077261161230627
Sensitivity:    0.7783946333564654 	 Specificity:    0.63705759888966
Precision  : 0.6820024321037698
Area Under Curve:    0.7077261161230627
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6149 - accuracy: 0.6616 - val_loss: 0.5715 - val_accuracy: 0.7019 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5597 - accuracy: 0.7108 - val_loss: 0.5497 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7224 - val_loss: 0.5410 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7282 - val_loss: 0.5444 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7349 - val_loss: 0.5437 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5189 - accuracy: 0.7391 - val_loss: 0.5356 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7428 - val_loss: 0.5375 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7474 - val_loss: 0.5335 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7482 - val_loss: 0.5343 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7540 - val_loss: 0.5319 - val_accuracy: 0.7346 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4910 - accuracy: 0.7579 - val_loss: 0.5342 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7607 - val_loss: 0.5388 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7649 - val_loss: 0.5429 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4711 - accuracy: 0.7680 - val_loss: 0.5436 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4663 - accuracy: 0.7695
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4667 - accuracy: 0.7691 - val_loss: 0.5462 - val_accuracy: 0.7265 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.44134766940971065
Confusion Matrix :
 [[2868 1455]
 [ 972 3351]]
Accuracy on test set:    0.7192921582234559
Sensitivity:    0.7751561415683553 	 Specificity:    0.6634281748785565
Precision  : 0.6972534332084894
Area Under Curve:    0.7192921582234559
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6093 - accuracy: 0.6649 - val_loss: 0.5604 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5583 - accuracy: 0.7131 - val_loss: 0.5477 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7223 - val_loss: 0.5445 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7295 - val_loss: 0.5393 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5267 - accuracy: 0.7321 - val_loss: 0.5387 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5189 - accuracy: 0.7367 - val_loss: 0.5385 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7424 - val_loss: 0.5369 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7464 - val_loss: 0.5418 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4983 - accuracy: 0.7512 - val_loss: 0.5388 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4932 - accuracy: 0.7545
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7549 - val_loss: 0.5487 - val_accuracy: 0.7219 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.43330969208382836
Confusion Matrix :
 [[2892 1431]
 [1027 3296]]
Accuracy on test set:    0.715706685172334
Sensitivity:    0.7624334952579227 	 Specificity:    0.6689798750867453
Precision  : 0.6972709964036387
Area Under Curve:    0.7157066851723339
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5981 - accuracy: 0.6728 - val_loss: 0.5584 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5549 - accuracy: 0.7137 - val_loss: 0.5531 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7243 - val_loss: 0.5444 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5319 - accuracy: 0.7316 - val_loss: 0.5454 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7380 - val_loss: 0.5483 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5167 - accuracy: 0.7403 - val_loss: 0.5453 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7467 - val_loss: 0.5353 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7504 - val_loss: 0.5381 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4954 - accuracy: 0.7541 - val_loss: 0.5388 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4878 - accuracy: 0.7577 - val_loss: 0.5402 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7617 - val_loss: 0.5408 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7647 - val_loss: 0.5480 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4718 - accuracy: 0.7680 - val_loss: 0.5511 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4643 - accuracy: 0.7709 - val_loss: 0.5457 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4576 - accuracy: 0.7783 - val_loss: 0.5551 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 16/400

261/274 [===========================>..] - ETA: 0s - loss: 0.4522 - accuracy: 0.7814
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4525 - accuracy: 0.7812 - val_loss: 0.5674 - val_accuracy: 0.7190 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.4127716965508536
Confusion Matrix :
 [[3302 1021]
 [1530 2793]]
Accuracy on test set:    0.7049502660189683
Sensitivity:    0.6460791117279667 	 Specificity:    0.7638214203099699
Precision  : 0.732302045097011
Area Under Curve:    0.7049502660189683
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6007 - accuracy: 0.6719 - val_loss: 0.5587 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5552 - accuracy: 0.7135 - val_loss: 0.5475 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7243 - val_loss: 0.5406 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7313 - val_loss: 0.5415 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5211 - accuracy: 0.7366 - val_loss: 0.5387 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7427 - val_loss: 0.5377 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5062 - accuracy: 0.7462 - val_loss: 0.5307 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7526 - val_loss: 0.5399 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7535 - val_loss: 0.5379 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4883 - accuracy: 0.7594 - val_loss: 0.5354 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7601 - val_loss: 0.5473 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4734 - accuracy: 0.7674
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4738 - accuracy: 0.7672 - val_loss: 0.5405 - val_accuracy: 0.7292 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.43790389779456285
Confusion Matrix :
 [[3091 1232]
 [1198 3125]]
Accuracy on test set:    0.7189451769604441
Sensitivity:    0.7228776312745778 	 Specificity:    0.7150127226463104
Precision  : 0.7172366307092036
Area Under Curve:    0.7189451769604442
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6163 - accuracy: 0.6577 - val_loss: 0.5631 - val_accuracy: 0.7077 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5624 - accuracy: 0.7085 - val_loss: 0.5491 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7183 - val_loss: 0.5450 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7265 - val_loss: 0.5386 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5307 - accuracy: 0.7338 - val_loss: 0.5373 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5240 - accuracy: 0.7369 - val_loss: 0.5361 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7396 - val_loss: 0.5378 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5106 - accuracy: 0.7438 - val_loss: 0.5367 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7463 - val_loss: 0.5492 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7495 - val_loss: 0.5380 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4959 - accuracy: 0.7524
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4959 - accuracy: 0.7523 - val_loss: 0.5510 - val_accuracy: 0.7203 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4552432834191843
Confusion Matrix :
 [[2828 1495]
 [ 880 3443]]
Accuracy on test set:    0.7253065001156604
Sensitivity:    0.7964376590330788 	 Specificity:    0.6541753411982419
Precision  : 0.6972458485216687
Area Under Curve:    0.7253065001156604
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6034 - accuracy: 0.6696 - val_loss: 0.5564 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5589 - accuracy: 0.7101 - val_loss: 0.5616 - val_accuracy: 0.7041 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7227 - val_loss: 0.5433 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7281 - val_loss: 0.5408 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7342 - val_loss: 0.5379 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7389 - val_loss: 0.5416 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7440 - val_loss: 0.5419 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7442 - val_loss: 0.5368 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7498 - val_loss: 0.5381 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4934 - accuracy: 0.7551
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7552 - val_loss: 0.5376 - val_accuracy: 0.7282 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.4628542462525438
Confusion Matrix :
 [[3227 1096]
 [1227 3096]]
Accuracy on test set:    0.731320842007865
Sensitivity:    0.7161693268563497 	 Specificity:    0.7464723571593801
Precision  : 0.7385496183206107
Area Under Curve:    0.731320842007865
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6079 - accuracy: 0.6656 - val_loss: 0.5592 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5608 - accuracy: 0.7098 - val_loss: 0.5481 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7217 - val_loss: 0.5411 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7297 - val_loss: 0.5424 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5251 - accuracy: 0.7337 - val_loss: 0.5381 - val_accuracy: 0.7206 - lr: 0.0010

Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5196 - accuracy: 0.7372 - val_loss: 0.5386 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7420 - val_loss: 0.5348 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7465 - val_loss: 0.5408 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7523 - val_loss: 0.5365 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7546 - val_loss: 0.5393 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7597 - val_loss: 0.5397 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4785 - accuracy: 0.7641 - val_loss: 0.5441 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4768 - accuracy: 0.7652 - val_loss: 0.5417 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4673 - accuracy: 0.7678 - val_loss: 0.5457 - val_accuracy: 0.7331 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4633 - accuracy: 0.7718 - val_loss: 0.5441 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4563 - accuracy: 0.7758 - val_loss: 0.5670 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4487 - accuracy: 0.7810 - val_loss: 0.5556 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4435 - accuracy: 0.7818 - val_loss: 0.5618 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 19/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4387 - accuracy: 0.7853
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4392 - accuracy: 0.7847 - val_loss: 0.5574 - val_accuracy: 0.7246 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4533322171800678
Confusion Matrix :
 [[3201 1122]
 [1242 3081]]
Accuracy on test set:    0.7265787647467037
Sensitivity:    0.7126995142262318 	 Specificity:    0.7404580152671756
Precision  : 0.7330478229835832
Area Under Curve:    0.7265787647467037
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6079 - accuracy: 0.6681 - val_loss: 0.5677 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5615 - accuracy: 0.7110 - val_loss: 0.5525 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7226 - val_loss: 0.5440 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7279 - val_loss: 0.5414 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5274 - accuracy: 0.7342 - val_loss: 0.5446 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5192 - accuracy: 0.7396 - val_loss: 0.5454 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5141 - accuracy: 0.7401 - val_loss: 0.5377 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
253/274 [==========================>...] - ETA: 0s - loss: 0.5078 - accuracy: 0.7458
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7457 - val_loss: 0.5408 - val_accuracy: 0.7145 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.45727202387176386
Confusion Matrix :
 [[3370  953]
 [1404 2919]]
Accuracy on test set:    0.7273883876937312
Sensitivity:    0.6752255378209576 	 Specificity:    0.7795512375665048
Precision  : 0.7538739669421488
Area Under Curve:    0.7273883876937313
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6097 - accuracy: 0.6644 - val_loss: 0.5704 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5628 - accuracy: 0.7080 - val_loss: 0.5539 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7216 - val_loss: 0.5492 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7278 - val_loss: 0.5528 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5286 - accuracy: 0.7352 - val_loss: 0.5477 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5219 - accuracy: 0.7370 - val_loss: 0.5485 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7418 - val_loss: 0.5459 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7467 - val_loss: 0.5433 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7500 - val_loss: 0.5453 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4964 - accuracy: 0.7527 - val_loss: 0.5496 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7577 - val_loss: 0.5468 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4860 - accuracy: 0.7596
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7594 - val_loss: 0.5512 - val_accuracy: 0.7143 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.5020726395299597
Confusion Matrix :
 [[3291 1032]
 [1121 3202]]
Accuracy on test set:    0.7509831135785334
Sensitivity:    0.7406893361091834 	 Specificity:    0.7612768910478834
Precision  : 0.7562588568729334
Area Under Curve:    0.7509831135785333
(8646, 4352) (8646,)
Mean MCC = 0.4476 + 0.0239 and Mean AUC = 0.7228 + 0.0124
Mean Sensitivity = 0.7326 + 0.0453 and Mean Specificity = 0.7130 + 0.0498 and Mean Accuracy = 0.7228 + 0.0124
Mean Precision = 0.7205 + 0.0248





Seed   : 965584
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6034 - accuracy: 0.6697 - val_loss: 0.5562 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5552 - accuracy: 0.7120 - val_loss: 0.5403 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7226 - val_loss: 0.5459 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5300 - accuracy: 0.7320 - val_loss: 0.5320 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5208 - accuracy: 0.7365 - val_loss: 0.5330 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7455 - val_loss: 0.5313 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5056 - accuracy: 0.7471 - val_loss: 0.5365 - val_accuracy: 0.7227 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7516 - val_loss: 0.5361 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7564 - val_loss: 0.5308 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4856 - accuracy: 0.7618 - val_loss: 0.5322 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4796 - accuracy: 0.7654 - val_loss: 0.5305 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4719 - accuracy: 0.7689 - val_loss: 0.5331 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4642 - accuracy: 0.7722 - val_loss: 0.5331 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4591 - accuracy: 0.7766
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4599 - accuracy: 0.7760 - val_loss: 0.5375 - val_accuracy: 0.7215 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4095526436373706
Confusion Matrix :
 [[2831 1492]
 [1069 3254]]
Accuracy on test set:    0.703793661808929
Sensitivity:    0.7527180198935924 	 Specificity:    0.6548693037242656
Precision  : 0.685630004214075
Area Under Curve:    0.703793661808929
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6133 - accuracy: 0.6616 - val_loss: 0.5569 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5627 - accuracy: 0.7069 - val_loss: 0.5479 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7216 - val_loss: 0.5412 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7276 - val_loss: 0.5347 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7325 - val_loss: 0.5350 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5210 - accuracy: 0.7375 - val_loss: 0.5338 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5146 - accuracy: 0.7419 - val_loss: 0.5290 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7456 - val_loss: 0.5275 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7493 - val_loss: 0.5317 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4964 - accuracy: 0.7546 - val_loss: 0.5273 - val_accuracy: 0.7339 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7562 - val_loss: 0.5285 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7600 - val_loss: 0.5412 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4786 - accuracy: 0.7633 - val_loss: 0.5389 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4738 - accuracy: 0.7659 - val_loss: 0.5302 - val_accuracy: 0.7339 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4676 - accuracy: 0.7675
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7672 - val_loss: 0.5349 - val_accuracy: 0.7221 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.41414616051526326
Confusion Matrix :
 [[2705 1618]
 [ 937 3386]]
Accuracy on test set:    0.7044876243349526
Sensitivity:    0.7832523710386305 	 Specificity:    0.6257228776312745
Precision  : 0.6766586730615508
Area Under Curve:    0.7044876243349526
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6054 - accuracy: 0.6665 - val_loss: 0.5572 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5597 - accuracy: 0.7099 - val_loss: 0.5464 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7225 - val_loss: 0.5418 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7271 - val_loss: 0.5420 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7327 - val_loss: 0.5311 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5219 - accuracy: 0.7368 - val_loss: 0.5400 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5110 - accuracy: 0.7446 - val_loss: 0.5301 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7453 - val_loss: 0.5325 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7511 - val_loss: 0.5280 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4943 - accuracy: 0.7538
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7540 - val_loss: 0.5376 - val_accuracy: 0.7223 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4333668227227722
Confusion Matrix :
 [[3299 1024]
 [1434 2889]]
Accuracy on test set:    0.715706685172334
Sensitivity:    0.6682859125607217 	 Specificity:    0.7631274577839463
Precision  : 0.7383082034244824
Area Under Curve:    0.715706685172334
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6074 - accuracy: 0.6658 - val_loss: 0.5642 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5578 - accuracy: 0.7120 - val_loss: 0.5459 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7233 - val_loss: 0.5395 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7312 - val_loss: 0.5350 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7362 - val_loss: 0.5330 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7416 - val_loss: 0.5315 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7452 - val_loss: 0.5305 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7468 - val_loss: 0.5291 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4973 - accuracy: 0.7514 - val_loss: 0.5293 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7576 - val_loss: 0.5305 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7607 - val_loss: 0.5311 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4797 - accuracy: 0.7635 - val_loss: 0.5342 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4718 - accuracy: 0.7664 - val_loss: 0.5369 - val_accuracy: 0.7340 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4662 - accuracy: 0.7721 - val_loss: 0.5410 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4575 - accuracy: 0.7758 - val_loss: 0.5461 - val_accuracy: 0.7336 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4531 - accuracy: 0.7789 - val_loss: 0.5466 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4485 - accuracy: 0.7803 - val_loss: 0.5477 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4402 - accuracy: 0.7845 - val_loss: 0.5486 - val_accuracy: 0.7364 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4347 - accuracy: 0.7881 - val_loss: 0.5707 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4310 - accuracy: 0.7883 - val_loss: 0.5628 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4261 - accuracy: 0.7921 - val_loss: 0.5722 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 22/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4196 - accuracy: 0.7947 - val_loss: 0.5768 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 23/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4150 - accuracy: 0.7982
Epoch 23: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4153 - accuracy: 0.7980 - val_loss: 0.5835 - val_accuracy: 0.7249 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.4240227204158729
Confusion Matrix :
 [[3094 1229]
 [1261 3062]]
Accuracy on test set:    0.7120055517002082
Sensitivity:    0.7083044182280823 	 Specificity:    0.715706685172334
Precision  : 0.7135865765555814
Area Under Curve:    0.7120055517002083
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6025 - accuracy: 0.6678 - val_loss: 0.5632 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5583 - accuracy: 0.7129 - val_loss: 0.5512 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7216 - val_loss: 0.5363 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7276 - val_loss: 0.5368 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5249 - accuracy: 0.7343 - val_loss: 0.5328 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7378 - val_loss: 0.5314 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5144 - accuracy: 0.7395 - val_loss: 0.5298 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7459 - val_loss: 0.5293 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7509 - val_loss: 0.5348 - val_accuracy: 0.7348 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4949 - accuracy: 0.7533 - val_loss: 0.5361 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7558 - val_loss: 0.5357 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4842 - accuracy: 0.7599 - val_loss: 0.5318 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7618 - val_loss: 0.5503 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4723 - accuracy: 0.7657 - val_loss: 0.5398 - val_accuracy: 0.7381 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4661 - accuracy: 0.7708 - val_loss: 0.5403 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4590 - accuracy: 0.7734 - val_loss: 0.5407 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4536 - accuracy: 0.7752 - val_loss: 0.5521 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4498 - accuracy: 0.7788 - val_loss: 0.5560 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 19/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4448 - accuracy: 0.7823
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4451 - accuracy: 0.7822 - val_loss: 0.5478 - val_accuracy: 0.7241 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.42956298749367244
Confusion Matrix :
 [[3092 1231]
 [1235 3088]]
Accuracy on test set:    0.7147814018043026
Sensitivity:    0.7143187601202868 	 Specificity:    0.7152440434883183
Precision  : 0.714980319518407
Area Under Curve:    0.7147814018043026
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6115 - accuracy: 0.6619 - val_loss: 0.5608 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5645 - accuracy: 0.7066 - val_loss: 0.5473 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5501 - accuracy: 0.7190 - val_loss: 0.5390 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7264 - val_loss: 0.5368 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7292 - val_loss: 0.5363 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7353 - val_loss: 0.5346 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7394 - val_loss: 0.5344 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7427 - val_loss: 0.5336 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7474 - val_loss: 0.5333 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5012 - accuracy: 0.7502 - val_loss: 0.5431 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7519 - val_loss: 0.5364 - val_accuracy: 0.7335 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7572 - val_loss: 0.5373 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4855 - accuracy: 0.7599 - val_loss: 0.5416 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 14/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.7618 - val_loss: 0.5370 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4733 - accuracy: 0.7677 - val_loss: 0.5367 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4688 - accuracy: 0.7683
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4690 - accuracy: 0.7682 - val_loss: 0.5366 - val_accuracy: 0.7295 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4315386673602659
Confusion Matrix :
 [[2748 1575]
 [ 905 3418]]
Accuracy on test set:    0.7131621559102476
Sensitivity:    0.7906546379828823 	 Specificity:    0.6356696738376127
Precision  : 0.6845583817344282
Area Under Curve:    0.7131621559102475
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6043 - accuracy: 0.6690 - val_loss: 0.5605 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7093 - val_loss: 0.5506 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7255 - val_loss: 0.5391 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7279 - val_loss: 0.5360 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7360 - val_loss: 0.5359 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5190 - accuracy: 0.7407 - val_loss: 0.5320 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7418 - val_loss: 0.5333 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7465 - val_loss: 0.5328 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5009 - accuracy: 0.7497 - val_loss: 0.5340 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4922 - accuracy: 0.7555 - val_loss: 0.5322 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4866 - accuracy: 0.7584 - val_loss: 0.5367 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4812 - accuracy: 0.7631 - val_loss: 0.5404 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4747 - accuracy: 0.7651 - val_loss: 0.5442 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4704 - accuracy: 0.7688
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7689 - val_loss: 0.5514 - val_accuracy: 0.7250 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4516094234581064
Confusion Matrix :
 [[2793 1530]
 [ 864 3459]]
Accuracy on test set:    0.7231089521165857
Sensitivity:    0.8001387925052047 	 Specificity:    0.6460791117279667
Precision  : 0.6933253156945279
Area Under Curve:    0.7231089521165857
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6096 - accuracy: 0.6642 - val_loss: 0.5571 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5616 - accuracy: 0.7092 - val_loss: 0.5555 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7234 - val_loss: 0.5445 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7277 - val_loss: 0.5390 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5303 - accuracy: 0.7313 - val_loss: 0.5372 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7362 - val_loss: 0.5395 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7399 - val_loss: 0.5356 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7426 - val_loss: 0.5390 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5055 - accuracy: 0.7481 - val_loss: 0.5343 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7501 - val_loss: 0.5346 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4960 - accuracy: 0.7552 - val_loss: 0.5327 - val_accuracy: 0.7362 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7575 - val_loss: 0.5326 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7603 - val_loss: 0.5382 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4788 - accuracy: 0.7633 - val_loss: 0.5403 - val_accuracy: 0.7335 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4738 - accuracy: 0.7665 - val_loss: 0.5360 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4688 - accuracy: 0.7692
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4693 - accuracy: 0.7689 - val_loss: 0.5423 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4554585809600724
Confusion Matrix :
 [[2924 1399]
 [ 965 3358]]
Accuracy on test set:    0.7265787647467037
Sensitivity:    0.7767753874624104 	 Specificity:    0.676382142030997
Precision  : 0.7059070842968257
Area Under Curve:    0.7265787647467037
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6044 - accuracy: 0.6677 - val_loss: 0.5592 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7103 - val_loss: 0.5455 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7207 - val_loss: 0.5479 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5368 - accuracy: 0.7280 - val_loss: 0.5362 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7321 - val_loss: 0.5362 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7373 - val_loss: 0.5366 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5136 - accuracy: 0.7431 - val_loss: 0.5383 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7465 - val_loss: 0.5298 - val_accuracy: 0.7344 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7493 - val_loss: 0.5326 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4959 - accuracy: 0.7531 - val_loss: 0.5349 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7555 - val_loss: 0.5349 - val_accuracy: 0.7336 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4854 - accuracy: 0.7601 - val_loss: 0.5362 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4799 - accuracy: 0.7607
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4801 - accuracy: 0.7607 - val_loss: 0.5383 - val_accuracy: 0.7282 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4737517895920556
Confusion Matrix :
 [[3174 1149]
 [1126 3197]]
Accuracy on test set:    0.7368725422160537
Sensitivity:    0.7395327318991441 	 Specificity:    0.7342123525329632
Precision  : 0.7356189599631845
Area Under Curve:    0.7368725422160536
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6122 - accuracy: 0.6621 - val_loss: 0.5653 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5659 - accuracy: 0.7065 - val_loss: 0.5464 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5491 - accuracy: 0.7191 - val_loss: 0.5450 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7261 - val_loss: 0.5386 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5297 - accuracy: 0.7323 - val_loss: 0.5387 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5211 - accuracy: 0.7370 - val_loss: 0.5372 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7390 - val_loss: 0.5367 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7432 - val_loss: 0.5365 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7501 - val_loss: 0.5362 - val_accuracy: 0.7341 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7515 - val_loss: 0.5438 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7574 - val_loss: 0.5388 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4832 - accuracy: 0.7600 - val_loss: 0.5601 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4789 - accuracy: 0.7632 - val_loss: 0.5490 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4748 - accuracy: 0.7667
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4747 - accuracy: 0.7667 - val_loss: 0.5477 - val_accuracy: 0.7197 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.5066905980054088
Confusion Matrix :
 [[3214 1109]
 [1024 3299]]
Accuracy on test set:    0.7532963219986121
Sensitivity:    0.7631274577839463 	 Specificity:    0.7434651862132778
Precision  : 0.7484119782214156
Area Under Curve:    0.753296321998612
(8646, 4352) (8646,)
Mean MCC = 0.4430 + 0.0282 and Mean AUC = 0.7204 + 0.0145
Mean Sensitivity = 0.7497 + 0.0400 and Mean Specificity = 0.6910 + 0.0468 and Mean Accuracy = 0.7204 + 0.0145
Mean Precision = 0.7097 + 0.0237





Seed   : 939291
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6015 - accuracy: 0.6723 - val_loss: 0.5634 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5558 - accuracy: 0.7141 - val_loss: 0.5476 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7249 - val_loss: 0.5437 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5303 - accuracy: 0.7313 - val_loss: 0.5401 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5220 - accuracy: 0.7361 - val_loss: 0.5362 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7416 - val_loss: 0.5401 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7461 - val_loss: 0.5488 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7479 - val_loss: 0.5377 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7529 - val_loss: 0.5355 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4884 - accuracy: 0.7576
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7574 - val_loss: 0.5344 - val_accuracy: 0.7258 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.4329571927230992
Confusion Matrix :
 [[3155 1168]
 [1284 3039]]
Accuracy on test set:    0.7164006476983577
Sensitivity:    0.7029840388619014 	 Specificity:    0.7298172565348138
Precision  : 0.7223674827668172
Area Under Curve:    0.7164006476983577
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6085 - accuracy: 0.6639 - val_loss: 0.5730 - val_accuracy: 0.6951 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7072 - val_loss: 0.5519 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7208 - val_loss: 0.5554 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7272 - val_loss: 0.5451 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7321 - val_loss: 0.5403 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5197 - accuracy: 0.7370 - val_loss: 0.5354 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7419 - val_loss: 0.5363 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7458 - val_loss: 0.5564 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7477 - val_loss: 0.5393 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7523 - val_loss: 0.5408 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4883 - accuracy: 0.7552
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4878 - accuracy: 0.7555 - val_loss: 0.5399 - val_accuracy: 0.7219 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4366729655839957
Confusion Matrix :
 [[2906 1417]
 [1026 3297]]
Accuracy on test set:    0.7174415914873931
Sensitivity:    0.7626648160999306 	 Specificity:    0.6722183668748555
Precision  : 0.699406024607552
Area Under Curve:    0.7174415914873931
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6022 - accuracy: 0.6686 - val_loss: 0.5612 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5573 - accuracy: 0.7127 - val_loss: 0.5482 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7224 - val_loss: 0.5461 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5319 - accuracy: 0.7296 - val_loss: 0.5418 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7335 - val_loss: 0.5454 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5199 - accuracy: 0.7366 - val_loss: 0.5375 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7416 - val_loss: 0.5358 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7454 - val_loss: 0.5386 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7478 - val_loss: 0.5368 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7493 - val_loss: 0.5358 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7546 - val_loss: 0.5372 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4857 - accuracy: 0.7577 - val_loss: 0.5393 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4812 - accuracy: 0.7599 - val_loss: 0.5423 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 14/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4758 - accuracy: 0.7658
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4766 - accuracy: 0.7654 - val_loss: 0.5405 - val_accuracy: 0.7271 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.44952225970128445
Confusion Matrix :
 [[3170 1153]
 [1227 3096]]
Accuracy on test set:    0.7247281980106408
Sensitivity:    0.7161693268563497 	 Specificity:    0.7332870691649318
Precision  : 0.7286420334196282
Area Under Curve:    0.7247281980106408
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5998 - accuracy: 0.6730 - val_loss: 0.5608 - val_accuracy: 0.7077 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5565 - accuracy: 0.7146 - val_loss: 0.5602 - val_accuracy: 0.7016 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7246 - val_loss: 0.5436 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7298 - val_loss: 0.5377 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5267 - accuracy: 0.7342 - val_loss: 0.5376 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5200 - accuracy: 0.7383 - val_loss: 0.5370 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5125 - accuracy: 0.7423 - val_loss: 0.5413 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7457 - val_loss: 0.5362 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7493 - val_loss: 0.5332 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4983 - accuracy: 0.7534 - val_loss: 0.5372 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4902 - accuracy: 0.7570 - val_loss: 0.5376 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4856 - accuracy: 0.7616 - val_loss: 0.5398 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7634 - val_loss: 0.5473 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4725 - accuracy: 0.7683 - val_loss: 0.5446 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4706 - accuracy: 0.7680 - val_loss: 0.5457 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4628 - accuracy: 0.7721 - val_loss: 0.5462 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4585 - accuracy: 0.7766 - val_loss: 0.5499 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4549 - accuracy: 0.7746 - val_loss: 0.5528 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 19/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4487 - accuracy: 0.7812
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4496 - accuracy: 0.7805 - val_loss: 0.5524 - val_accuracy: 0.7204 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.42290573295083034
Confusion Matrix :
 [[2996 1327]
 [1169 3154]]
Accuracy on test set:    0.7113115891741846
Sensitivity:    0.7295859356928059 	 Specificity:    0.6930372426555632
Precision  : 0.7038607453693372
Area Under Curve:    0.7113115891741847
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6123 - accuracy: 0.6640 - val_loss: 0.5652 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5589 - accuracy: 0.7127 - val_loss: 0.5466 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7240 - val_loss: 0.5399 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7278 - val_loss: 0.5363 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5261 - accuracy: 0.7348 - val_loss: 0.5436 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5190 - accuracy: 0.7399 - val_loss: 0.5329 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7417 - val_loss: 0.5329 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7470 - val_loss: 0.5305 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7505 - val_loss: 0.5335 - val_accuracy: 0.7336 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4942 - accuracy: 0.7529 - val_loss: 0.5337 - val_accuracy: 0.7349 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4891 - accuracy: 0.7567 - val_loss: 0.5339 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4847 - accuracy: 0.7618 - val_loss: 0.5366 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4781 - accuracy: 0.7645 - val_loss: 0.5361 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4704 - accuracy: 0.7668 - val_loss: 0.5360 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4686 - accuracy: 0.7678
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4682 - accuracy: 0.7681 - val_loss: 0.5418 - val_accuracy: 0.7272 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4372200798328961
Confusion Matrix :
 [[3084 1239]
 [1194 3129]]
Accuracy on test set:    0.7185981956974323
Sensitivity:    0.7238029146426093 	 Specificity:    0.7133934767522554
Precision  : 0.7163461538461539
Area Under Curve:    0.7185981956974323
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6032 - accuracy: 0.6672 - val_loss: 0.5663 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5587 - accuracy: 0.7107 - val_loss: 0.5443 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7206 - val_loss: 0.5557 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7270 - val_loss: 0.5382 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5260 - accuracy: 0.7338 - val_loss: 0.5419 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5196 - accuracy: 0.7393 - val_loss: 0.5380 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7447 - val_loss: 0.5413 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7468 - val_loss: 0.5331 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5003 - accuracy: 0.7522 - val_loss: 0.5329 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7565 - val_loss: 0.5359 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7612 - val_loss: 0.5348 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4839 - accuracy: 0.7614 - val_loss: 0.5425 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4793 - accuracy: 0.7630 - val_loss: 0.5350 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4709 - accuracy: 0.7689
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7688 - val_loss: 0.5469 - val_accuracy: 0.7273 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.44345848320549974
Confusion Matrix :
 [[2842 1481]
 [ 940 3383]]
Accuracy on test set:    0.7199861207494795
Sensitivity:    0.7825584085126069 	 Specificity:    0.657413832986352
Precision  : 0.6955180921052632
Area Under Curve:    0.7199861207494795
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.5998 - accuracy: 0.6712 - val_loss: 0.5648 - val_accuracy: 0.6980 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5583 - accuracy: 0.7111 - val_loss: 0.5499 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7227 - val_loss: 0.5428 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7293 - val_loss: 0.5424 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7358 - val_loss: 0.5502 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5172 - accuracy: 0.7397 - val_loss: 0.5408 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7410 - val_loss: 0.5382 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7461 - val_loss: 0.5393 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7498 - val_loss: 0.5398 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4924 - accuracy: 0.7560 - val_loss: 0.5423 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4880 - accuracy: 0.7575 - val_loss: 0.5437 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4786 - accuracy: 0.7627 - val_loss: 0.5451 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4768 - accuracy: 0.7652
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4768 - accuracy: 0.7655 - val_loss: 0.5436 - val_accuracy: 0.7307 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.4437805435430331
Confusion Matrix :
 [[3073 1250]
 [1155 3168]]
Accuracy on test set:    0.7218366874855424
Sensitivity:    0.732824427480916 	 Specificity:    0.7108489474901689
Precision  : 0.7170665459483929
Area Under Curve:    0.7218366874855424
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6131 - accuracy: 0.6610 - val_loss: 0.5677 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5653 - accuracy: 0.7066 - val_loss: 0.5481 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5488 - accuracy: 0.7180 - val_loss: 0.5438 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7255 - val_loss: 0.5452 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7303 - val_loss: 0.5385 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5261 - accuracy: 0.7340 - val_loss: 0.5374 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5204 - accuracy: 0.7370 - val_loss: 0.5388 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7420 - val_loss: 0.5372 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7427 - val_loss: 0.5336 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7441 - val_loss: 0.5392 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7492 - val_loss: 0.5443 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7519 - val_loss: 0.5332 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 13/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7572 - val_loss: 0.5402 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7580 - val_loss: 0.5392 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 15/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4774 - accuracy: 0.7610
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7604 - val_loss: 0.5419 - val_accuracy: 0.7212 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4644937544666317
Confusion Matrix :
 [[3160 1163]
 [1152 3171]]
Accuracy on test set:    0.7322461253758964
Sensitivity:    0.7335183900069396 	 Specificity:    0.7309738607448532
Precision  : 0.7316566682048915
Area Under Curve:    0.7322461253758963
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6128 - accuracy: 0.6582 - val_loss: 0.5662 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5616 - accuracy: 0.7096 - val_loss: 0.5504 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5500 - accuracy: 0.7189 - val_loss: 0.5482 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7277 - val_loss: 0.5411 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7314 - val_loss: 0.5406 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7366 - val_loss: 0.5449 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7376 - val_loss: 0.5343 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7420 - val_loss: 0.5431 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7467 - val_loss: 0.5340 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7498 - val_loss: 0.5340 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7553 - val_loss: 0.5351 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4906 - accuracy: 0.7570 - val_loss: 0.5364 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4830 - accuracy: 0.7616 - val_loss: 0.5411 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4765 - accuracy: 0.7645
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7644 - val_loss: 0.5401 - val_accuracy: 0.7290 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4867230310962873
Confusion Matrix :
 [[3143 1180]
 [1040 3283]]
Accuracy on test set:    0.7432338653712699
Sensitivity:    0.7594263243118204 	 Specificity:    0.7270414064307195
Precision  : 0.7356038539099261
Area Under Curve:    0.7432338653712699
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6207 - accuracy: 0.6557 - val_loss: 0.5656 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5666 - accuracy: 0.7052 - val_loss: 0.5567 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5522 - accuracy: 0.7177 - val_loss: 0.5438 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7260 - val_loss: 0.5430 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7285 - val_loss: 0.5395 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5272 - accuracy: 0.7345 - val_loss: 0.5396 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5202 - accuracy: 0.7389 - val_loss: 0.5360 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7419 - val_loss: 0.5408 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7439 - val_loss: 0.5367 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7463 - val_loss: 0.5417 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4983 - accuracy: 0.7530 - val_loss: 0.5478 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7569 - val_loss: 0.5405 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4893 - accuracy: 0.7564 - val_loss: 0.5418 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4806 - accuracy: 0.7620
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4818 - accuracy: 0.7612 - val_loss: 0.5420 - val_accuracy: 0.7277 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.48318722691300653
Confusion Matrix :
 [[3266 1057]
 [1178 3145]]
Accuracy on test set:    0.741498959056211
Sensitivity:    0.7275040481147351 	 Specificity:    0.7554938699976868
Precision  : 0.7484531175630652
Area Under Curve:    0.7414989590562109
(8646, 4352) (8646,)
Mean MCC = 0.4501 + 0.0203 and Mean AUC = 0.7247 + 0.0103
Mean Sensitivity = 0.7371 + 0.0228 and Mean Specificity = 0.7124 + 0.0286 and Mean Accuracy = 0.7247 + 0.0103
Mean Precision = 0.7199 + 0.0160





Seed   : 707266
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6077 - accuracy: 0.6667 - val_loss: 0.5782 - val_accuracy: 0.6888 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5563 - accuracy: 0.7135 - val_loss: 0.5500 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7248 - val_loss: 0.5448 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7323 - val_loss: 0.5380 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5219 - accuracy: 0.7361 - val_loss: 0.5394 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7408 - val_loss: 0.5340 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7482 - val_loss: 0.5395 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7504 - val_loss: 0.5450 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7544 - val_loss: 0.5388 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4873 - accuracy: 0.7597 - val_loss: 0.5381 - val_accuracy: 0.7250 - lr: 0.0010

Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4797 - accuracy: 0.7631
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7629 - val_loss: 0.5434 - val_accuracy: 0.7231 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.43007586183237717
Confusion Matrix :
 [[2709 1614]
 [ 877 3446]]
Accuracy on test set:    0.7118898912792042
Sensitivity:    0.7971316215591024 	 Specificity:    0.6266481609993061
Precision  : 0.6810276679841897
Area Under Curve:    0.7118898912792042
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6122 - accuracy: 0.6639 - val_loss: 0.5622 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7130 - val_loss: 0.5594 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7239 - val_loss: 0.5436 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7307 - val_loss: 0.5404 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5218 - accuracy: 0.7383 - val_loss: 0.5406 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7427 - val_loss: 0.5359 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7459 - val_loss: 0.5624 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7508 - val_loss: 0.5407 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7538 - val_loss: 0.5357 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4890 - accuracy: 0.7585 - val_loss: 0.5484 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4833 - accuracy: 0.7604
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.7604 - val_loss: 0.5441 - val_accuracy: 0.7255 - lr: 0.0010
271/271 [==============================] - 0s 638us/step
Independent Testing Matthews Correlation:  0.42314149660072375
Confusion Matrix :
 [[3237 1086]
 [1413 2910]]
Accuracy on test set:    0.7109646079111728
Sensitivity:    0.6731436502428869 	 Specificity:    0.7487855655794587
Precision  : 0.7282282282282282
Area Under Curve:    0.7109646079111728
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6037 - accuracy: 0.6679 - val_loss: 0.5629 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5582 - accuracy: 0.7110 - val_loss: 0.5524 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7241 - val_loss: 0.5431 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7281 - val_loss: 0.5496 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7352 - val_loss: 0.5391 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7409 - val_loss: 0.5388 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5119 - accuracy: 0.7417 - val_loss: 0.5355 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7498 - val_loss: 0.5370 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7495 - val_loss: 0.5402 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7565 - val_loss: 0.5406 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7592 - val_loss: 0.5524 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4811 - accuracy: 0.7612 - val_loss: 0.5485 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 13/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4727 - accuracy: 0.7692
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4730 - accuracy: 0.7690 - val_loss: 0.5423 - val_accuracy: 0.7262 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4410433434133552
Confusion Matrix :
 [[3000 1323]
 [1096 3227]]
Accuracy on test set:    0.7202174415914874
Sensitivity:    0.7464723571593801 	 Specificity:    0.6939625260235948
Precision  : 0.7092307692307692
Area Under Curve:    0.7202174415914874
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5975 - accuracy: 0.6745 - val_loss: 0.5565 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5537 - accuracy: 0.7146 - val_loss: 0.5496 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7254 - val_loss: 0.5416 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5294 - accuracy: 0.7332 - val_loss: 0.5377 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5205 - accuracy: 0.7364 - val_loss: 0.5381 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7439 - val_loss: 0.5385 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7479 - val_loss: 0.5380 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4973 - accuracy: 0.7518 - val_loss: 0.5378 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4927 - accuracy: 0.7562
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7570 - val_loss: 0.5483 - val_accuracy: 0.7237 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.4379628690923306
Confusion Matrix :
 [[3188 1135]
 [1296 3027]]
Accuracy on test set:    0.7188295165394402
Sensitivity:    0.7002081887578071 	 Specificity:    0.7374508443210733
Precision  : 0.7272945699183085
Area Under Curve:    0.7188295165394403
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6088 - accuracy: 0.6644 - val_loss: 0.5614 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5593 - accuracy: 0.7121 - val_loss: 0.5473 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7224 - val_loss: 0.5465 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7291 - val_loss: 0.5404 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5260 - accuracy: 0.7330 - val_loss: 0.5471 - val_accuracy: 0.7168 - lr: 0.0010

Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7380 - val_loss: 0.5373 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5136 - accuracy: 0.7428 - val_loss: 0.5390 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7470 - val_loss: 0.5390 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5008 - accuracy: 0.7499 - val_loss: 0.5380 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7540 - val_loss: 0.5374 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7570 - val_loss: 0.5392 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7613 - val_loss: 0.5458 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4776 - accuracy: 0.7631 - val_loss: 0.5446 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7678 - val_loss: 0.5502 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4643 - accuracy: 0.7694
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4642 - accuracy: 0.7697 - val_loss: 0.5488 - val_accuracy: 0.7218 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.4442181924991392
Confusion Matrix :
 [[2929 1394]
 [1016 3307]]
Accuracy on test set:    0.7212583853805228
Sensitivity:    0.7649780245200093 	 Specificity:    0.6775387462410363
Precision  : 0.7034673473728994
Area Under Curve:    0.7212583853805228
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6111 - accuracy: 0.6632 - val_loss: 0.5668 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7108 - val_loss: 0.5467 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7217 - val_loss: 0.5435 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7274 - val_loss: 0.5443 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7368 - val_loss: 0.5402 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7407 - val_loss: 0.5419 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7447 - val_loss: 0.5394 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7465 - val_loss: 0.5388 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7526 - val_loss: 0.5390 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 10/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4913 - accuracy: 0.7559
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7553 - val_loss: 0.5373 - val_accuracy: 0.7164 - lr: 0.0010
271/271 [==============================] - 0s 665us/step
Independent Testing Matthews Correlation:  0.428830543966214
Confusion Matrix :
 [[2930 1393]
 [1081 3242]]
Accuracy on test set:    0.7138561184362711
Sensitivity:    0.749942169789498 	 Specificity:    0.6777700670830442
Precision  : 0.699460625674218
Area Under Curve:    0.7138561184362711
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6008 - accuracy: 0.6703 - val_loss: 0.5707 - val_accuracy: 0.6990 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7107 - val_loss: 0.5630 - val_accuracy: 0.7048 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7211 - val_loss: 0.5533 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7275 - val_loss: 0.5537 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7314 - val_loss: 0.5522 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7371 - val_loss: 0.5509 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7413 - val_loss: 0.5513 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7455 - val_loss: 0.5508 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7500 - val_loss: 0.5512 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7541 - val_loss: 0.5507 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7580 - val_loss: 0.5506 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4868 - accuracy: 0.7602 - val_loss: 0.5510 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7624 - val_loss: 0.5518 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4762 - accuracy: 0.7668 - val_loss: 0.5580 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4715 - accuracy: 0.7710 - val_loss: 0.5608 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4695 - accuracy: 0.7692 - val_loss: 0.5587 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 17/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4646 - accuracy: 0.7738
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4641 - accuracy: 0.7742 - val_loss: 0.5797 - val_accuracy: 0.7143 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.44893638114220796
Confusion Matrix :
 [[3321 1002]
 [1388 2935]]
Accuracy on test set:    0.7235715938006014
Sensitivity:    0.6789266712930835 	 Specificity:    0.7682165163081194
Precision  : 0.745491490982982
Area Under Curve:    0.7235715938006015
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6072 - accuracy: 0.6621 - val_loss: 0.5670 - val_accuracy: 0.7028 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5587 - accuracy: 0.7117 - val_loss: 0.5538 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7246 - val_loss: 0.5528 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7315 - val_loss: 0.5482 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5249 - accuracy: 0.7349 - val_loss: 0.5485 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 6/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7385 - val_loss: 0.5413 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7462 - val_loss: 0.5423 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7453 - val_loss: 0.5465 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5006 - accuracy: 0.7510 - val_loss: 0.5457 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7541 - val_loss: 0.5508 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4873 - accuracy: 0.7576 - val_loss: 0.5467 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4822 - accuracy: 0.7618 - val_loss: 0.5499 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4764 - accuracy: 0.7645 - val_loss: 0.5473 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7698 - val_loss: 0.5645 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4618 - accuracy: 0.7725
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4623 - accuracy: 0.7724 - val_loss: 0.5633 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 638us/step
Independent Testing Matthews Correlation:  0.4599206018226584
Confusion Matrix :
 [[3052 1271]
 [1066 3257]]
Accuracy on test set:    0.7297015961138098
Sensitivity:    0.753411982419616 	 Specificity:    0.7059912098080037
Precision  : 0.7193021201413428
Area Under Curve:    0.7297015961138099
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6068 - accuracy: 0.6659 - val_loss: 0.5758 - val_accuracy: 0.7003 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7104 - val_loss: 0.5597 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7206 - val_loss: 0.5507 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7269 - val_loss: 0.5512 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7352 - val_loss: 0.5624 - val_accuracy: 0.7070 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5205 - accuracy: 0.7370 - val_loss: 0.5488 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7427 - val_loss: 0.5455 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7478 - val_loss: 0.5412 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7502 - val_loss: 0.5499 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7545 - val_loss: 0.5505 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4877 - accuracy: 0.7585 - val_loss: 0.5493 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7627 - val_loss: 0.5500 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 13/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4759 - accuracy: 0.7667
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4758 - accuracy: 0.7669 - val_loss: 0.5594 - val_accuracy: 0.7160 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4707381149971047
Confusion Matrix :
 [[3181 1142]
 [1146 3177]]
Accuracy on test set:    0.7353689567430025
Sensitivity:    0.7349063150589868 	 Specificity:    0.7358315984270183
Precision  : 0.7355869414216254
Area Under Curve:    0.7353689567430026
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6053 - accuracy: 0.6683 - val_loss: 0.5731 - val_accuracy: 0.7029 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5621 - accuracy: 0.7094 - val_loss: 0.5686 - val_accuracy: 0.7023 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7208 - val_loss: 0.5616 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7268 - val_loss: 0.5540 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7329 - val_loss: 0.5528 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.7362 - val_loss: 0.5546 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7420 - val_loss: 0.5489 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7460 - val_loss: 0.5509 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7499 - val_loss: 0.5516 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7515 - val_loss: 0.5525 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7585 - val_loss: 0.5511 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4855 - accuracy: 0.7608
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7611 - val_loss: 0.5563 - val_accuracy: 0.7199 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4856572723814853
Confusion Matrix :
 [[3258 1065]
 [1159 3164]]
Accuracy on test set:    0.7427712236872542
Sensitivity:    0.7318991441128846 	 Specificity:    0.7536433032616239
Precision  : 0.7481674154646488
Area Under Curve:    0.7427712236872542
(8646, 4352) (8646,)
Mean MCC = 0.4471 + 0.0188 and Mean AUC = 0.7228 + 0.0098
Mean Sensitivity = 0.7331 + 0.0369 and Mean Specificity = 0.7126 + 0.0418 and Mean Accuracy = 0.7228 + 0.0098
Mean Precision = 0.7197 + 0.0203





Seed   : 833164
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6035 - accuracy: 0.6697 - val_loss: 0.5635 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5541 - accuracy: 0.7151 - val_loss: 0.5468 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7242 - val_loss: 0.5424 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5303 - accuracy: 0.7331 - val_loss: 0.5337 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5208 - accuracy: 0.7374 - val_loss: 0.5380 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7428 - val_loss: 0.5315 - val_accuracy: 0.7298 - lr: 0.0010

Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7465 - val_loss: 0.5289 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7507 - val_loss: 0.5324 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7530 - val_loss: 0.5292 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7561 - val_loss: 0.5402 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4832 - accuracy: 0.7604 - val_loss: 0.5323 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4742 - accuracy: 0.7662 - val_loss: 0.5319 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4680 - accuracy: 0.7700 - val_loss: 0.5345 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4619 - accuracy: 0.7730
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4617 - accuracy: 0.7731 - val_loss: 0.5358 - val_accuracy: 0.7291 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.4292096282786666
Confusion Matrix :
 [[2937 1386]
 [1086 3237]]
Accuracy on test set:    0.714087439278279
Sensitivity:    0.7487855655794587 	 Specificity:    0.6793893129770993
Precision  : 0.700194678780013
Area Under Curve:    0.714087439278279
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6046 - accuracy: 0.6663 - val_loss: 0.5663 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5580 - accuracy: 0.7116 - val_loss: 0.5520 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7205 - val_loss: 0.5515 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7286 - val_loss: 0.5399 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5269 - accuracy: 0.7356 - val_loss: 0.5366 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5212 - accuracy: 0.7391 - val_loss: 0.5348 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5157 - accuracy: 0.7411 - val_loss: 0.5334 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7478 - val_loss: 0.5331 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5032 - accuracy: 0.7502 - val_loss: 0.5336 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7528 - val_loss: 0.5301 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4932 - accuracy: 0.7537 - val_loss: 0.5304 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4906 - accuracy: 0.7564 - val_loss: 0.5345 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4839 - accuracy: 0.7604 - val_loss: 0.5362 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4789 - accuracy: 0.7636 - val_loss: 0.5425 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 15/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4710 - accuracy: 0.7671
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4721 - accuracy: 0.7663 - val_loss: 0.5402 - val_accuracy: 0.7244 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.44348321215043235
Confusion Matrix :
 [[3222 1101]
 [1307 3016]]
Accuracy on test set:    0.7214897062225306
Sensitivity:    0.6976636594957205 	 Specificity:    0.7453157529493407
Precision  : 0.7325722613553558
Area Under Curve:    0.7214897062225306
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6080 - accuracy: 0.6640 - val_loss: 0.5646 - val_accuracy: 0.7016 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5622 - accuracy: 0.7105 - val_loss: 0.5542 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7219 - val_loss: 0.5448 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7274 - val_loss: 0.5506 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7321 - val_loss: 0.5409 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7347 - val_loss: 0.5389 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5189 - accuracy: 0.7394 - val_loss: 0.5378 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7440 - val_loss: 0.5406 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7467 - val_loss: 0.5416 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5008 - accuracy: 0.7494 - val_loss: 0.5424 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7512 - val_loss: 0.5400 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4942 - accuracy: 0.7548 - val_loss: 0.5445 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7588 - val_loss: 0.5495 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4806 - accuracy: 0.7629 - val_loss: 0.5441 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4758 - accuracy: 0.7661 - val_loss: 0.5564 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4694 - accuracy: 0.7691
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4697 - accuracy: 0.7686 - val_loss: 0.5507 - val_accuracy: 0.7191 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.44624770515927514
Confusion Matrix :
 [[2878 1445]
 [ 961 3362]]
Accuracy on test set:    0.7217210270645386
Sensitivity:    0.7777006708304418 	 Specificity:    0.6657413832986352
Precision  : 0.6993967131266903
Area Under Curve:    0.7217210270645384
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6123 - accuracy: 0.6636 - val_loss: 0.5676 - val_accuracy: 0.6956 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7119 - val_loss: 0.5505 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7226 - val_loss: 0.5545 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 4/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7295 - val_loss: 0.5417 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7361 - val_loss: 0.5384 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7405 - val_loss: 0.5466 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7425 - val_loss: 0.5386 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7508 - val_loss: 0.5406 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7504 - val_loss: 0.5402 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7557 - val_loss: 0.5407 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4866 - accuracy: 0.7563 - val_loss: 0.5420 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4818 - accuracy: 0.7619
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4822 - accuracy: 0.7616 - val_loss: 0.5381 - val_accuracy: 0.7237 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.4398493881352589
Confusion Matrix :
 [[3160 1163]
 [1259 3064]]
Accuracy on test set:    0.7198704603284756
Sensitivity:    0.7087670599120981 	 Specificity:    0.7309738607448532
Precision  : 0.7248639697184764
Area Under Curve:    0.7198704603284756
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6069 - accuracy: 0.6669 - val_loss: 0.5876 - val_accuracy: 0.6852 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5564 - accuracy: 0.7128 - val_loss: 0.5517 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7241 - val_loss: 0.5441 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7313 - val_loss: 0.5404 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5227 - accuracy: 0.7376 - val_loss: 0.5398 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7420 - val_loss: 0.5413 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7470 - val_loss: 0.5380 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7491 - val_loss: 0.5340 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7547 - val_loss: 0.5396 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7570 - val_loss: 0.5450 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4856 - accuracy: 0.7605 - val_loss: 0.5339 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4771 - accuracy: 0.7652 - val_loss: 0.5421 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4717 - accuracy: 0.7671 - val_loss: 0.5431 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4656 - accuracy: 0.7727 - val_loss: 0.5453 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4590 - accuracy: 0.7758 - val_loss: 0.5469 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4524 - accuracy: 0.7784
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4532 - accuracy: 0.7776 - val_loss: 0.5513 - val_accuracy: 0.7253 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.439659674757639
Confusion Matrix :
 [[2792 1531]
 [ 911 3412]]
Accuracy on test set:    0.7175572519083969
Sensitivity:    0.7892667129308351 	 Specificity:    0.6458477908859588
Precision  : 0.6902690673679951
Area Under Curve:    0.7175572519083969
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6031 - accuracy: 0.6711 - val_loss: 0.5592 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5562 - accuracy: 0.7145 - val_loss: 0.5527 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7236 - val_loss: 0.5463 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7298 - val_loss: 0.5375 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7377 - val_loss: 0.5336 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5177 - accuracy: 0.7412 - val_loss: 0.5502 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7454 - val_loss: 0.5396 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7478 - val_loss: 0.5390 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7533 - val_loss: 0.5367 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7583 - val_loss: 0.5378 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7606 - val_loss: 0.5427 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4804 - accuracy: 0.7632 - val_loss: 0.5407 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4716 - accuracy: 0.7689 - val_loss: 0.5445 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4668 - accuracy: 0.7713 - val_loss: 0.5503 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4605 - accuracy: 0.7737 - val_loss: 0.5478 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4557 - accuracy: 0.7790 - val_loss: 0.5490 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4489 - accuracy: 0.7821 - val_loss: 0.5553 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 18/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4444 - accuracy: 0.7840
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4442 - accuracy: 0.7840 - val_loss: 0.5606 - val_accuracy: 0.7222 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.44394098118287156
Confusion Matrix :
 [[2945 1378]
 [1032 3291]]
Accuracy on test set:    0.7212583853805228
Sensitivity:    0.7612768910478834 	 Specificity:    0.6812398797131621
Precision  : 0.7048618547868922
Area Under Curve:    0.7212583853805228
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6048 - accuracy: 0.6719 - val_loss: 0.5698 - val_accuracy: 0.6937 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7116 - val_loss: 0.5521 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7237 - val_loss: 0.5453 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7312 - val_loss: 0.5449 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7353 - val_loss: 0.5413 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5177 - accuracy: 0.7417 - val_loss: 0.5418 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5096 - accuracy: 0.7457 - val_loss: 0.5408 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7499 - val_loss: 0.5505 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4966 - accuracy: 0.7539 - val_loss: 0.5439 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4910 - accuracy: 0.7606
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7601 - val_loss: 0.5461 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.444185200526349
Confusion Matrix :
 [[2807 1516]
 [ 906 3417]]
Accuracy on test set:    0.7198704603284756
Sensitivity:    0.7904233171408744 	 Specificity:    0.6493176035160768
Precision  : 0.6926819379687816
Area Under Curve:    0.7198704603284757
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6056 - accuracy: 0.6678 - val_loss: 0.5757 - val_accuracy: 0.6934 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5574 - accuracy: 0.7134 - val_loss: 0.5522 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7244 - val_loss: 0.5528 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7284 - val_loss: 0.5450 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5269 - accuracy: 0.7341 - val_loss: 0.5408 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5196 - accuracy: 0.7380 - val_loss: 0.5465 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7400 - val_loss: 0.5449 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5062 - accuracy: 0.7476 - val_loss: 0.5396 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7518 - val_loss: 0.5416 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7527 - val_loss: 0.5443 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7567 - val_loss: 0.5500 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4865 - accuracy: 0.7599 - val_loss: 0.5503 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4792 - accuracy: 0.7636 - val_loss: 0.5505 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7648 - val_loss: 0.5507 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4689 - accuracy: 0.7694
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7696 - val_loss: 0.5535 - val_accuracy: 0.7179 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4544428280926932
Confusion Matrix :
 [[3272 1051]
 [1311 3012]]
Accuracy on test set:    0.7268100855887115
Sensitivity:    0.6967383761276891 	 Specificity:    0.756881795049734
Precision  : 0.7413241447206498
Area Under Curve:    0.7268100855887115
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6121 - accuracy: 0.6635 - val_loss: 0.5743 - val_accuracy: 0.7005 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5628 - accuracy: 0.7080 - val_loss: 0.5608 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7226 - val_loss: 0.5533 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7267 - val_loss: 0.5492 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7332 - val_loss: 0.5450 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7363 - val_loss: 0.5473 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7407 - val_loss: 0.5449 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7451 - val_loss: 0.5444 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5022 - accuracy: 0.7501 - val_loss: 0.5461 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4933 - accuracy: 0.7541 - val_loss: 0.5420 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7574 - val_loss: 0.5473 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4809 - accuracy: 0.7632
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7632 - val_loss: 0.5477 - val_accuracy: 0.7212 - lr: 0.0010
271/271 [==============================] - 0s 638us/step
Independent Testing Matthews Correlation:  0.4849378733897769
Confusion Matrix :
 [[3168 1155]
 [1072 3251]]
Accuracy on test set:    0.7424242424242424
Sensitivity:    0.7520240573675688 	 Specificity:    0.732824427480916
Precision  : 0.7378574670903314
Area Under Curve:    0.7424242424242424
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6167 - accuracy: 0.6589 - val_loss: 0.5802 - val_accuracy: 0.6897 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5652 - accuracy: 0.7070 - val_loss: 0.5674 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7199 - val_loss: 0.5579 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7290 - val_loss: 0.5541 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5278 - accuracy: 0.7340 - val_loss: 0.5549 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5218 - accuracy: 0.7373 - val_loss: 0.5548 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5141 - accuracy: 0.7429 - val_loss: 0.5525 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5106 - accuracy: 0.7456 - val_loss: 0.5487 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7503 - val_loss: 0.5484 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7510 - val_loss: 0.5514 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4881 - accuracy: 0.7582 - val_loss: 0.5607 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4827 - accuracy: 0.7616 - val_loss: 0.5550 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4761 - accuracy: 0.7654 - val_loss: 0.5737 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4687 - accuracy: 0.7679 - val_loss: 0.5668 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4644 - accuracy: 0.7726
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4644 - accuracy: 0.7731 - val_loss: 0.5786 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.5004973546135053
Confusion Matrix :
 [[3116 1207]
 [ 956 3367]]
Accuracy on test set:    0.7498265093684942
Sensitivity:    0.7788572750404812 	 Specificity:    0.720795743696507
Precision  : 0.7361171840839528
Area Under Curve:    0.7498265093684942
(8646, 4352) (8646,)
Mean MCC = 0.4526 + 0.0212 and Mean AUC = 0.7255 + 0.0109
Mean Sensitivity = 0.7502 + 0.0349 and Mean Specificity = 0.7008 + 0.0390 and Mean Accuracy = 0.7255 + 0.0109
Mean Precision = 0.7160 + 0.0193





Seed   : 899105
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6082 - accuracy: 0.6639 - val_loss: 0.5695 - val_accuracy: 0.7019 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7104 - val_loss: 0.5494 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7252 - val_loss: 0.5580 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7303 - val_loss: 0.5391 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5256 - accuracy: 0.7348 - val_loss: 0.5369 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5191 - accuracy: 0.7399 - val_loss: 0.5374 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7462 - val_loss: 0.5346 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7503 - val_loss: 0.5333 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7528 - val_loss: 0.5388 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7556 - val_loss: 0.5324 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7626 - val_loss: 0.5338 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4792 - accuracy: 0.7659 - val_loss: 0.5440 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4756 - accuracy: 0.7679 - val_loss: 0.5476 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4686 - accuracy: 0.7702
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4688 - accuracy: 0.7704 - val_loss: 0.5385 - val_accuracy: 0.7245 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.41521170640191357
Confusion Matrix :
 [[2880 1443]
 [1091 3232]]
Accuracy on test set:    0.7069164931760351
Sensitivity:    0.7476289613694194 	 Specificity:    0.666204024982651
Precision  : 0.6913368983957219
Area Under Curve:    0.7069164931760351
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6004 - accuracy: 0.6734 - val_loss: 0.5745 - val_accuracy: 0.6916 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7132 - val_loss: 0.5563 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7242 - val_loss: 0.5403 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5310 - accuracy: 0.7324 - val_loss: 0.5448 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7371 - val_loss: 0.5390 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5167 - accuracy: 0.7410 - val_loss: 0.5368 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7451 - val_loss: 0.5350 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7501 - val_loss: 0.5452 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7526 - val_loss: 0.5363 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7569 - val_loss: 0.5344 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4859 - accuracy: 0.7613 - val_loss: 0.5383 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4792 - accuracy: 0.7656 - val_loss: 0.5425 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4755 - accuracy: 0.7667 - val_loss: 0.5416 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4695 - accuracy: 0.7708
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4691 - accuracy: 0.7709 - val_loss: 0.5476 - val_accuracy: 0.7242 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.44922652946922254
Confusion Matrix :
 [[3138 1185]
 [1196 3127]]
Accuracy on test set:    0.7246125375896368
Sensitivity:    0.7233402729585936 	 Specificity:    0.7258848022206801
Precision  : 0.7251855287569573
Area Under Curve:    0.7246125375896368
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6063 - accuracy: 0.6662 - val_loss: 0.5613 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7112 - val_loss: 0.5577 - val_accuracy: 0.7011 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7219 - val_loss: 0.5448 - val_accuracy: 0.7212 - lr: 0.0010

Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7311 - val_loss: 0.5389 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7361 - val_loss: 0.5427 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7380 - val_loss: 0.5372 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7393 - val_loss: 0.5348 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7474 - val_loss: 0.5359 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4988 - accuracy: 0.7514 - val_loss: 0.5354 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7547 - val_loss: 0.5403 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7586 - val_loss: 0.5391 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4825 - accuracy: 0.7609
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7612 - val_loss: 0.5416 - val_accuracy: 0.7251 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4422367515561724
Confusion Matrix :
 [[3210 1113]
 [1300 3023]]
Accuracy on test set:    0.720911404117511
Sensitivity:    0.6992829053897757 	 Specificity:    0.7425399028452464
Precision  : 0.7308994197292069
Area Under Curve:    0.7209114041175111
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6089 - accuracy: 0.6660 - val_loss: 0.5685 - val_accuracy: 0.6989 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7100 - val_loss: 0.5464 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7215 - val_loss: 0.5526 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7327 - val_loss: 0.5378 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5247 - accuracy: 0.7348 - val_loss: 0.5373 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7422 - val_loss: 0.5396 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7434 - val_loss: 0.5361 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7483 - val_loss: 0.5467 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7526 - val_loss: 0.5398 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4901 - accuracy: 0.7573 - val_loss: 0.5388 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7616 - val_loss: 0.5483 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7634 - val_loss: 0.5442 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4707 - accuracy: 0.7673 - val_loss: 0.5419 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4636 - accuracy: 0.7721 - val_loss: 0.5419 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4568 - accuracy: 0.7773 - val_loss: 0.5471 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4515 - accuracy: 0.7790 - val_loss: 0.5601 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4445 - accuracy: 0.7822 - val_loss: 0.5554 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4429 - accuracy: 0.7817 - val_loss: 0.5591 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4327 - accuracy: 0.7885 - val_loss: 0.5687 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4296 - accuracy: 0.7893 - val_loss: 0.5746 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 21/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4214 - accuracy: 0.7948
Epoch 21: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4210 - accuracy: 0.7954 - val_loss: 0.5756 - val_accuracy: 0.7186 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.42552221435795445
Confusion Matrix :
 [[2896 1427]
 [1063 3260]]
Accuracy on test set:    0.7120055517002082
Sensitivity:    0.7541059449456397 	 Specificity:    0.6699051584547768
Precision  : 0.6955408576914871
Area Under Curve:    0.7120055517002083
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6185 - accuracy: 0.6565 - val_loss: 0.5584 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5631 - accuracy: 0.7090 - val_loss: 0.5504 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7200 - val_loss: 0.5451 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7294 - val_loss: 0.5502 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7326 - val_loss: 0.5409 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5206 - accuracy: 0.7384 - val_loss: 0.5388 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7420 - val_loss: 0.5459 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7463 - val_loss: 0.5381 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7483 - val_loss: 0.5385 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4960 - accuracy: 0.7514 - val_loss: 0.5427 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4901 - accuracy: 0.7562 - val_loss: 0.5438 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4850 - accuracy: 0.7580 - val_loss: 0.5499 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4785 - accuracy: 0.7650 - val_loss: 0.5485 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4719 - accuracy: 0.7663 - val_loss: 0.5529 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 15/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4678 - accuracy: 0.7705
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4676 - accuracy: 0.7700 - val_loss: 0.5527 - val_accuracy: 0.7197 - lr: 0.0010

271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4492239318739481
Confusion Matrix :
 [[3011 1312]
 [1072 3251]]
Accuracy on test set:    0.724265556326625
Sensitivity:    0.7520240573675688 	 Specificity:    0.6965070552856812
Precision  : 0.7124698663160202
Area Under Curve:    0.724265556326625
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6147 - accuracy: 0.6615 - val_loss: 0.5628 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7113 - val_loss: 0.5503 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7236 - val_loss: 0.5485 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7293 - val_loss: 0.5377 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7366 - val_loss: 0.5369 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7412 - val_loss: 0.5443 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7465 - val_loss: 0.5368 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5050 - accuracy: 0.7493 - val_loss: 0.5437 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4985 - accuracy: 0.7528 - val_loss: 0.5428 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7564 - val_loss: 0.5484 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7615 - val_loss: 0.5410 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4802 - accuracy: 0.7636 - val_loss: 0.5435 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4752 - accuracy: 0.7670 - val_loss: 0.5497 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4682 - accuracy: 0.7724 - val_loss: 0.5547 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4640 - accuracy: 0.7750 - val_loss: 0.5488 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 16/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4572 - accuracy: 0.7775
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4566 - accuracy: 0.7777 - val_loss: 0.5620 - val_accuracy: 0.7233 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.43235591941714335
Confusion Matrix :
 [[2796 1527]
 [ 944 3379]]
Accuracy on test set:    0.7142030996992829
Sensitivity:    0.7816331251445755 	 Specificity:    0.6467730742539903
Precision  : 0.688748471259682
Area Under Curve:    0.714203099699283
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6102 - accuracy: 0.6636 - val_loss: 0.5715 - val_accuracy: 0.7059 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5597 - accuracy: 0.7123 - val_loss: 0.5524 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7228 - val_loss: 0.5496 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7268 - val_loss: 0.5597 - val_accuracy: 0.7005 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7326 - val_loss: 0.5399 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7369 - val_loss: 0.5400 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7420 - val_loss: 0.5401 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7449 - val_loss: 0.5399 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7501 - val_loss: 0.5426 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7502 - val_loss: 0.5428 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7532 - val_loss: 0.5468 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4839 - accuracy: 0.7597 - val_loss: 0.5448 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7639 - val_loss: 0.5443 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4737 - accuracy: 0.7650 - val_loss: 0.5487 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7677 - val_loss: 0.5641 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4617 - accuracy: 0.7706 - val_loss: 0.5666 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4562 - accuracy: 0.7738 - val_loss: 0.5584 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4517 - accuracy: 0.7772 - val_loss: 0.5589 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4484 - accuracy: 0.7787 - val_loss: 0.5633 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 20/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4414 - accuracy: 0.7840
Epoch 20: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4418 - accuracy: 0.7836 - val_loss: 0.5771 - val_accuracy: 0.7181 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.45367425425641683
Confusion Matrix :
 [[2928 1395]
 [ 976 3347]]
Accuracy on test set:    0.7257691417996761
Sensitivity:    0.7742308582003239 	 Specificity:    0.6773074253990284
Precision  : 0.705820328975116
Area Under Curve:    0.7257691417996761
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6064 - accuracy: 0.6650 - val_loss: 0.5623 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5605 - accuracy: 0.7130 - val_loss: 0.5586 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7210 - val_loss: 0.5427 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5369 - accuracy: 0.7282 - val_loss: 0.5412 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7292 - val_loss: 0.5394 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7345 - val_loss: 0.5382 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5177 - accuracy: 0.7395 - val_loss: 0.5366 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7438 - val_loss: 0.5372 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7464 - val_loss: 0.5399 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7500 - val_loss: 0.5414 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7510 - val_loss: 0.5428 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4916 - accuracy: 0.7554
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7553 - val_loss: 0.5395 - val_accuracy: 0.7245 - lr: 0.0010
271/271 [==============================] - 0s 637us/step
Independent Testing Matthews Correlation:  0.4529873072928451
Confusion Matrix :
 [[3176 1147]
 [1218 3105]]
Accuracy on test set:    0.7264631043256997
Sensitivity:    0.7182512144344205 	 Specificity:    0.7346749942169789
Precision  : 0.730244590780809
Area Under Curve:    0.7264631043256997
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6330 - accuracy: 0.6465 - val_loss: 0.5751 - val_accuracy: 0.6966 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5698 - accuracy: 0.7028 - val_loss: 0.5618 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5504 - accuracy: 0.7177 - val_loss: 0.5482 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7249 - val_loss: 0.5573 - val_accuracy: 0.7033 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7300 - val_loss: 0.5465 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5231 - accuracy: 0.7361 - val_loss: 0.5403 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7376 - val_loss: 0.5405 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5110 - accuracy: 0.7422 - val_loss: 0.5413 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7462 - val_loss: 0.5404 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7511 - val_loss: 0.5358 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4910 - accuracy: 0.7559
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7563 - val_loss: 0.5426 - val_accuracy: 0.7253 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4856025267158868
Confusion Matrix :
 [[3177 1146]
 [1078 3245]]
Accuracy on test set:    0.7427712236872542
Sensitivity:    0.7506361323155216 	 Specificity:    0.7349063150589868
Precision  : 0.739011614666363
Area Under Curve:    0.7427712236872542
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6079 - accuracy: 0.6656 - val_loss: 0.5695 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5631 - accuracy: 0.7097 - val_loss: 0.5590 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7205 - val_loss: 0.5536 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7276 - val_loss: 0.5502 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7327 - val_loss: 0.5473 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5212 - accuracy: 0.7391 - val_loss: 0.5483 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7432 - val_loss: 0.5474 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7463 - val_loss: 0.5548 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7502 - val_loss: 0.5525 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4964 - accuracy: 0.7532 - val_loss: 0.5516 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7560 - val_loss: 0.5507 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7619 - val_loss: 0.5558 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7656 - val_loss: 0.5579 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7679 - val_loss: 0.5579 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4627 - accuracy: 0.7714 - val_loss: 0.5574 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4558 - accuracy: 0.7784 - val_loss: 0.5651 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4490 - accuracy: 0.7814 - val_loss: 0.5606 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4445 - accuracy: 0.7826 - val_loss: 0.5659 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4369 - accuracy: 0.7881 - val_loss: 0.5804 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 20/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4318 - accuracy: 0.7907
Epoch 20: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4320 - accuracy: 0.7905 - val_loss: 0.5771 - val_accuracy: 0.7182 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4902523846330438
Confusion Matrix :
 [[3118 1205]
 [1001 3322]]
Accuracy on test set:    0.744853111265325
Sensitivity:    0.7684478371501272 	 Specificity:    0.7212583853805228
Precision  : 0.7338193063839187
Area Under Curve:    0.7448531112653249
(8646, 4352) (8646,)
Mean MCC = 0.4496 + 0.0226 and Mean AUC = 0.7243 + 0.0116
Mean Sensitivity = 0.7470 + 0.0248 and Mean Specificity = 0.7016 + 0.0328 and Mean Accuracy = 0.7243 + 0.0116
Mean Precision = 0.7153 + 0.0180





Seed   : 235337
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6153 - accuracy: 0.6610 - val_loss: 0.5630 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5636 - accuracy: 0.7079 - val_loss: 0.5469 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7219 - val_loss: 0.5365 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7274 - val_loss: 0.5353 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7348 - val_loss: 0.5318 - val_accuracy: 0.7215 - lr: 0.0010

Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7357 - val_loss: 0.5370 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7428 - val_loss: 0.5291 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7455 - val_loss: 0.5298 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7515 - val_loss: 0.5310 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4942 - accuracy: 0.7554 - val_loss: 0.5259 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4866 - accuracy: 0.7610 - val_loss: 0.5282 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7618 - val_loss: 0.5324 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7688 - val_loss: 0.5344 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4717 - accuracy: 0.7706 - val_loss: 0.5329 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4663 - accuracy: 0.7720 - val_loss: 0.5388 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4615 - accuracy: 0.7757 - val_loss: 0.5450 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4533 - accuracy: 0.7782 - val_loss: 0.5398 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4478 - accuracy: 0.7847 - val_loss: 0.5509 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4426 - accuracy: 0.7861 - val_loss: 0.5530 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 20/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4365 - accuracy: 0.7901
Epoch 20: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4364 - accuracy: 0.7901 - val_loss: 0.5545 - val_accuracy: 0.7200 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4114238365949492
Confusion Matrix :
 [[2933 1390]
 [1157 3166]]
Accuracy on test set:    0.705412907702984
Sensitivity:    0.7323617857969003 	 Specificity:    0.6784640296090678
Precision  : 0.6949078138718174
Area Under Curve:    0.705412907702984
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6099 - accuracy: 0.6636 - val_loss: 0.5677 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7087 - val_loss: 0.5464 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7208 - val_loss: 0.5448 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7301 - val_loss: 0.5380 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5260 - accuracy: 0.7330 - val_loss: 0.5337 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5191 - accuracy: 0.7390 - val_loss: 0.5351 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7428 - val_loss: 0.5350 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7486 - val_loss: 0.5325 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7512 - val_loss: 0.5442 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4912 - accuracy: 0.7545
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7539 - val_loss: 0.5395 - val_accuracy: 0.7196 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4513000619490127
Confusion Matrix :
 [[2853 1470]
 [ 918 3405]]
Accuracy on test set:    0.7238029146426093
Sensitivity:    0.78764746703678 	 Specificity:    0.6599583622484386
Precision  : 0.6984615384615385
Area Under Curve:    0.7238029146426094
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6033 - accuracy: 0.6690 - val_loss: 0.5708 - val_accuracy: 0.6996 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5578 - accuracy: 0.7134 - val_loss: 0.5461 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7236 - val_loss: 0.5429 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7307 - val_loss: 0.5372 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5261 - accuracy: 0.7334 - val_loss: 0.5376 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5178 - accuracy: 0.7387 - val_loss: 0.5389 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5096 - accuracy: 0.7449 - val_loss: 0.5360 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7477 - val_loss: 0.5411 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7508 - val_loss: 0.5390 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7560 - val_loss: 0.5427 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4847 - accuracy: 0.7588 - val_loss: 0.5419 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4802 - accuracy: 0.7622 - val_loss: 0.5374 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4748 - accuracy: 0.7641 - val_loss: 0.5429 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4687 - accuracy: 0.7692 - val_loss: 0.5522 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4616 - accuracy: 0.7728 - val_loss: 0.5476 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4570 - accuracy: 0.7732 - val_loss: 0.5595 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 17/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4495 - accuracy: 0.7772
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4497 - accuracy: 0.7772 - val_loss: 0.5577 - val_accuracy: 0.7215 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.42828494129050604
Confusion Matrix :
 [[3038 1285]
 [1187 3136]]
Accuracy on test set:    0.714087439278279
Sensitivity:    0.7254221605366643 	 Specificity:    0.7027527180198936
Precision  : 0.7093417778783081
Area Under Curve:    0.714087439278279
(8646, 4352) (8646,)
Epoch 1/400

274/274 [==============================] - 1s 3ms/step - loss: 0.6034 - accuracy: 0.6686 - val_loss: 0.5541 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7120 - val_loss: 0.5432 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7238 - val_loss: 0.5444 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7313 - val_loss: 0.5343 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5234 - accuracy: 0.7358 - val_loss: 0.5331 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7406 - val_loss: 0.5317 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7467 - val_loss: 0.5303 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7474 - val_loss: 0.5325 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7521 - val_loss: 0.5362 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7555 - val_loss: 0.5351 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4858 - accuracy: 0.7575 - val_loss: 0.5366 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4811 - accuracy: 0.7606 - val_loss: 0.5416 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4764 - accuracy: 0.7645 - val_loss: 0.5400 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4699 - accuracy: 0.7697 - val_loss: 0.5422 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4611 - accuracy: 0.7729 - val_loss: 0.5483 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4543 - accuracy: 0.7769
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4551 - accuracy: 0.7766 - val_loss: 0.5575 - val_accuracy: 0.7028 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.42112219271204676
Confusion Matrix :
 [[3413  910]
 [1617 2706]]
Accuracy on test set:    0.7077261161230627
Sensitivity:    0.6259541984732825 	 Specificity:    0.7894980337728429
Precision  : 0.7483407079646017
Area Under Curve:    0.7077261161230627
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6063 - accuracy: 0.6682 - val_loss: 0.5531 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5558 - accuracy: 0.7153 - val_loss: 0.5426 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7231 - val_loss: 0.5383 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7298 - val_loss: 0.5302 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7363 - val_loss: 0.5304 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5159 - accuracy: 0.7412 - val_loss: 0.5378 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7467 - val_loss: 0.5317 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7484 - val_loss: 0.5277 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7565 - val_loss: 0.5289 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4856 - accuracy: 0.7588 - val_loss: 0.5310 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4809 - accuracy: 0.7624 - val_loss: 0.5314 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7679 - val_loss: 0.5294 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7708 - val_loss: 0.5455 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4595 - accuracy: 0.7753 - val_loss: 0.5413 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4524 - accuracy: 0.7792
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4528 - accuracy: 0.7790 - val_loss: 0.5427 - val_accuracy: 0.7265 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.44553854423423517
Confusion Matrix :
 [[3142 1181]
 [1216 3107]]
Accuracy on test set:    0.7227619708535739
Sensitivity:    0.7187138561184363 	 Specificity:    0.7268100855887115
Precision  : 0.7245802238805971
Area Under Curve:    0.722761970853574
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6115 - accuracy: 0.6596 - val_loss: 0.5635 - val_accuracy: 0.7048 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5637 - accuracy: 0.7088 - val_loss: 0.5434 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5490 - accuracy: 0.7182 - val_loss: 0.5364 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7256 - val_loss: 0.5474 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7313 - val_loss: 0.5347 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7355 - val_loss: 0.5354 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5190 - accuracy: 0.7385 - val_loss: 0.5324 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7430 - val_loss: 0.5370 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7449 - val_loss: 0.5328 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7480 - val_loss: 0.5328 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7513 - val_loss: 0.5312 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4929 - accuracy: 0.7564
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7564 - val_loss: 0.5336 - val_accuracy: 0.7227 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.43670588392778403
Confusion Matrix :
 [[2965 1358]
 [1081 3242]]
Accuracy on test set:    0.7179042331714087
Sensitivity:    0.749942169789498 	 Specificity:    0.6858662965533194
Precision  : 0.7047826086956521
Area Under Curve:    0.7179042331714087
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6144 - accuracy: 0.6603 - val_loss: 0.5660 - val_accuracy: 0.7028 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5632 - accuracy: 0.7080 - val_loss: 0.5462 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7208 - val_loss: 0.5416 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7273 - val_loss: 0.5362 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5279 - accuracy: 0.7336 - val_loss: 0.5361 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7389 - val_loss: 0.5362 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7420 - val_loss: 0.5342 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7468 - val_loss: 0.5351 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7498 - val_loss: 0.5452 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7537 - val_loss: 0.5380 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4898 - accuracy: 0.7552 - val_loss: 0.5360 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7607 - val_loss: 0.5469 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4765 - accuracy: 0.7649
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4769 - accuracy: 0.7647 - val_loss: 0.5490 - val_accuracy: 0.7199 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4551377877571931
Confusion Matrix :
 [[2800 1523]
 [ 856 3467]]
Accuracy on test set:    0.7248438584316447
Sensitivity:    0.8019893592412677 	 Specificity:    0.6476983576220218
Precision  : 0.6947895791583166
Area Under Curve:    0.7248438584316448
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6133 - accuracy: 0.6615 - val_loss: 0.5659 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5631 - accuracy: 0.7089 - val_loss: 0.5492 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7205 - val_loss: 0.5464 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7267 - val_loss: 0.5367 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5288 - accuracy: 0.7335 - val_loss: 0.5399 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5234 - accuracy: 0.7350 - val_loss: 0.5335 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5178 - accuracy: 0.7395 - val_loss: 0.5359 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7435 - val_loss: 0.5325 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 9/400
264/274 [===========================>..] - ETA: 0s - loss: 0.5053 - accuracy: 0.7481
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7475 - val_loss: 0.5376 - val_accuracy: 0.7233 - lr: 0.0010
271/271 [==============================] - 0s 637us/step
Independent Testing Matthews Correlation:  0.46270062609667795
Confusion Matrix :
 [[3196 1127]
 [1196 3127]]
Accuracy on test set:    0.731320842007865
Sensitivity:    0.7233402729585936 	 Specificity:    0.7393014110571362
Precision  : 0.735072872590503
Area Under Curve:    0.731320842007865
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6052 - accuracy: 0.6711 - val_loss: 0.5636 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7127 - val_loss: 0.5462 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7220 - val_loss: 0.5466 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7265 - val_loss: 0.5436 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5264 - accuracy: 0.7351 - val_loss: 0.5371 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5194 - accuracy: 0.7389 - val_loss: 0.5343 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5127 - accuracy: 0.7428 - val_loss: 0.5325 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7486 - val_loss: 0.5332 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7513 - val_loss: 0.5361 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7549 - val_loss: 0.5344 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7579 - val_loss: 0.5374 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4800 - accuracy: 0.7634
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7635 - val_loss: 0.5427 - val_accuracy: 0.7283 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.47562089672998004
Confusion Matrix :
 [[3020 1303]
 [ 970 3353]]
Accuracy on test set:    0.7371038630580615
Sensitivity:    0.775618783252371 	 Specificity:    0.6985889428637521
Precision  : 0.7201460481099656
Area Under Curve:    0.7371038630580615
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6206 - accuracy: 0.6570 - val_loss: 0.5773 - val_accuracy: 0.6919 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5668 - accuracy: 0.7055 - val_loss: 0.5513 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5502 - accuracy: 0.7182 - val_loss: 0.5454 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7286 - val_loss: 0.5490 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5295 - accuracy: 0.7328 - val_loss: 0.5505 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5208 - accuracy: 0.7375 - val_loss: 0.5408 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7440 - val_loss: 0.5396 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7494 - val_loss: 0.5412 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7525 - val_loss: 0.5385 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7572 - val_loss: 0.5463 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7611 - val_loss: 0.5462 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4771 - accuracy: 0.7653 - val_loss: 0.5497 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4697 - accuracy: 0.7684 - val_loss: 0.5499 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4624 - accuracy: 0.7731
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4631 - accuracy: 0.7727 - val_loss: 0.5521 - val_accuracy: 0.7232 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.49882897428261896
Confusion Matrix :
 [[3360  963]
 [1207 3116]]
Accuracy on test set:    0.7490168864214666
Sensitivity:    0.720795743696507 	 Specificity:    0.7772380291464261
Precision  : 0.7639127237067909
Area Under Curve:    0.7490168864214665
(8646, 4352) (8646,)
Mean MCC = 0.4487 + 0.0249 and Mean AUC = 0.7234 + 0.0126
Mean Sensitivity = 0.7362 + 0.0466 and Mean Specificity = 0.7106 + 0.0449 and Mean Accuracy = 0.7234 + 0.0126
Mean Precision = 0.7194 + 0.0225





Seed   : 300944
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6097 - accuracy: 0.6637 - val_loss: 0.5656 - val_accuracy: 0.7012 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7102 - val_loss: 0.5441 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7221 - val_loss: 0.5556 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7315 - val_loss: 0.5366 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7355 - val_loss: 0.5424 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7393 - val_loss: 0.5340 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7415 - val_loss: 0.5350 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7481 - val_loss: 0.5384 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5014 - accuracy: 0.7498 - val_loss: 0.5316 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4922 - accuracy: 0.7549 - val_loss: 0.5394 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4868 - accuracy: 0.7571
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7566 - val_loss: 0.5353 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.41538635803265284
Confusion Matrix :
 [[2998 1325]
 [1203 3120]]
Accuracy on test set:    0.7076104557020587
Sensitivity:    0.7217210270645386 	 Specificity:    0.693499884339579
Precision  : 0.7019122609673791
Area Under Curve:    0.7076104557020587
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6020 - accuracy: 0.6724 - val_loss: 0.5601 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7143 - val_loss: 0.5536 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7231 - val_loss: 0.5479 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7306 - val_loss: 0.5430 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7369 - val_loss: 0.5438 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5157 - accuracy: 0.7405 - val_loss: 0.5390 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7456 - val_loss: 0.5366 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7494 - val_loss: 0.5380 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7555 - val_loss: 0.5411 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4883 - accuracy: 0.7588 - val_loss: 0.5394 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4806 - accuracy: 0.7628 - val_loss: 0.5447 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4759 - accuracy: 0.7668 - val_loss: 0.5460 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4695 - accuracy: 0.7707
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4690 - accuracy: 0.7712 - val_loss: 0.5575 - val_accuracy: 0.7192 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4281597832946968
Confusion Matrix :
 [[2658 1665]
 [ 841 3482]]
Accuracy on test set:    0.7101549849641453
Sensitivity:    0.8054591718713856 	 Specificity:    0.6148507980569049
Precision  : 0.6765105886924422
Area Under Curve:    0.7101549849641452
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6040 - accuracy: 0.6681 - val_loss: 0.5712 - val_accuracy: 0.6921 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7125 - val_loss: 0.5569 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7229 - val_loss: 0.5492 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7317 - val_loss: 0.5470 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7344 - val_loss: 0.5418 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7392 - val_loss: 0.5417 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7413 - val_loss: 0.5418 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5055 - accuracy: 0.7485 - val_loss: 0.5415 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7507 - val_loss: 0.5403 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4950 - accuracy: 0.7537 - val_loss: 0.5435 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4884 - accuracy: 0.7575 - val_loss: 0.5458 - val_accuracy: 0.7265 - lr: 0.0010

Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4827 - accuracy: 0.7594 - val_loss: 0.5489 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4764 - accuracy: 0.7629 - val_loss: 0.5437 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4766 - accuracy: 0.7643 - val_loss: 0.5477 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7687 - val_loss: 0.5546 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4623 - accuracy: 0.7715
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4619 - accuracy: 0.7715 - val_loss: 0.5628 - val_accuracy: 0.7222 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.44699451313512173
Confusion Matrix :
 [[3208 1115]
 [1277 3046]]
Accuracy on test set:    0.7233402729585936
Sensitivity:    0.7046032847559565 	 Specificity:    0.7420772611612306
Precision  : 0.7320355683729872
Area Under Curve:    0.7233402729585935
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6140 - accuracy: 0.6597 - val_loss: 0.5640 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7105 - val_loss: 0.5522 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7214 - val_loss: 0.5504 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7294 - val_loss: 0.5442 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7349 - val_loss: 0.5416 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5168 - accuracy: 0.7405 - val_loss: 0.5416 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7431 - val_loss: 0.5429 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5047 - accuracy: 0.7492 - val_loss: 0.5420 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7514 - val_loss: 0.5419 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7555 - val_loss: 0.5459 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7581 - val_loss: 0.5510 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4805 - accuracy: 0.7611 - val_loss: 0.5521 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4752 - accuracy: 0.7646 - val_loss: 0.5590 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4692 - accuracy: 0.7688
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7690 - val_loss: 0.5548 - val_accuracy: 0.7231 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.42623351956891725
Confusion Matrix :
 [[3138 1185]
 [1296 3027]]
Accuracy on test set:    0.7130464954892436
Sensitivity:    0.7002081887578071 	 Specificity:    0.7258848022206801
Precision  : 0.7186609686609686
Area Under Curve:    0.7130464954892436
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6103 - accuracy: 0.6604 - val_loss: 0.5626 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5624 - accuracy: 0.7073 - val_loss: 0.5477 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7213 - val_loss: 0.5444 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7280 - val_loss: 0.5403 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7300 - val_loss: 0.5449 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5222 - accuracy: 0.7354 - val_loss: 0.5387 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5168 - accuracy: 0.7373 - val_loss: 0.5391 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5111 - accuracy: 0.7440 - val_loss: 0.5369 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7481 - val_loss: 0.5357 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4983 - accuracy: 0.7506 - val_loss: 0.5393 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4922 - accuracy: 0.7524 - val_loss: 0.5530 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7571 - val_loss: 0.5460 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7609 - val_loss: 0.5525 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4750 - accuracy: 0.7638 - val_loss: 0.5468 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4687 - accuracy: 0.7655 - val_loss: 0.5507 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4649 - accuracy: 0.7664 - val_loss: 0.5481 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4572 - accuracy: 0.7719 - val_loss: 0.5571 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 18/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4504 - accuracy: 0.7757
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4512 - accuracy: 0.7757 - val_loss: 0.5591 - val_accuracy: 0.7163 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4288350624475955
Confusion Matrix :
 [[2873 1450]
 [1028 3295]]
Accuracy on test set:    0.7133934767522554
Sensitivity:    0.7622021744159149 	 Specificity:    0.6645847790885959
Precision  : 0.6944151738672286
Area Under Curve:    0.7133934767522554
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6109 - accuracy: 0.6618 - val_loss: 0.5601 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7101 - val_loss: 0.5569 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7226 - val_loss: 0.5416 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7287 - val_loss: 0.5357 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7345 - val_loss: 0.5450 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7392 - val_loss: 0.5375 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7436 - val_loss: 0.5413 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7479 - val_loss: 0.5337 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7551 - val_loss: 0.5398 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7564 - val_loss: 0.5449 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4854 - accuracy: 0.7586 - val_loss: 0.5374 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4780 - accuracy: 0.7621 - val_loss: 0.5428 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4748 - accuracy: 0.7667 - val_loss: 0.5424 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4675 - accuracy: 0.7686 - val_loss: 0.5627 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4612 - accuracy: 0.7741 - val_loss: 0.5528 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4546 - accuracy: 0.7765 - val_loss: 0.5496 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4487 - accuracy: 0.7808
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4499 - accuracy: 0.7799 - val_loss: 0.5545 - val_accuracy: 0.7268 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.4361900647170926
Confusion Matrix :
 [[2906 1417]
 [1028 3295]]
Accuracy on test set:    0.7172102706453851
Sensitivity:    0.7622021744159149 	 Specificity:    0.6722183668748555
Precision  : 0.6992784380305602
Area Under Curve:    0.7172102706453851
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6113 - accuracy: 0.6641 - val_loss: 0.5671 - val_accuracy: 0.6988 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5622 - accuracy: 0.7085 - val_loss: 0.5519 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7197 - val_loss: 0.5441 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7308 - val_loss: 0.5470 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7346 - val_loss: 0.5395 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7407 - val_loss: 0.5412 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7429 - val_loss: 0.5385 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7493 - val_loss: 0.5466 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4990 - accuracy: 0.7525 - val_loss: 0.5423 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7563 - val_loss: 0.5439 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4859 - accuracy: 0.7617 - val_loss: 0.5474 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4792 - accuracy: 0.7644 - val_loss: 0.5459 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4723 - accuracy: 0.7668 - val_loss: 0.5608 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4697 - accuracy: 0.7700 - val_loss: 0.5566 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4595 - accuracy: 0.7741 - val_loss: 0.5606 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4555 - accuracy: 0.7783
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4558 - accuracy: 0.7779 - val_loss: 0.5596 - val_accuracy: 0.7143 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4461319207125331
Confusion Matrix :
 [[2883 1440]
 [ 966 3357]]
Accuracy on test set:    0.7217210270645386
Sensitivity:    0.7765440666204025 	 Specificity:    0.6668979875086746
Precision  : 0.699812382739212
Area Under Curve:    0.7217210270645384
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6140 - accuracy: 0.6601 - val_loss: 0.5676 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5648 - accuracy: 0.7075 - val_loss: 0.5544 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5507 - accuracy: 0.7179 - val_loss: 0.5532 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7259 - val_loss: 0.5426 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7313 - val_loss: 0.5391 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7331 - val_loss: 0.5422 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5192 - accuracy: 0.7394 - val_loss: 0.5425 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7422 - val_loss: 0.5397 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5065 - accuracy: 0.7474 - val_loss: 0.5427 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4999 - accuracy: 0.7513
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5008 - accuracy: 0.7506 - val_loss: 0.5451 - val_accuracy: 0.7179 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.47086315758562847
Confusion Matrix :
 [[2896 1427]
 [ 877 3446]]
Accuracy on test set:    0.7335183900069396
Sensitivity:    0.7971316215591024 	 Specificity:    0.6699051584547768
Precision  : 0.7071619125795198
Area Under Curve:    0.7335183900069397
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6043 - accuracy: 0.6701 - val_loss: 0.5600 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5604 - accuracy: 0.7108 - val_loss: 0.5484 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7220 - val_loss: 0.5451 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7275 - val_loss: 0.5413 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7331 - val_loss: 0.5458 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5218 - accuracy: 0.7362 - val_loss: 0.5366 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7406 - val_loss: 0.5376 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7472 - val_loss: 0.5376 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7513 - val_loss: 0.5462 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7534 - val_loss: 0.5392 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7563 - val_loss: 0.5388 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4844 - accuracy: 0.7611 - val_loss: 0.5399 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7643 - val_loss: 0.5504 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4706 - accuracy: 0.7677 - val_loss: 0.5478 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4669 - accuracy: 0.7688 - val_loss: 0.5527 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4573 - accuracy: 0.7746 - val_loss: 0.5499 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 17/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4505 - accuracy: 0.7804
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4508 - accuracy: 0.7802 - val_loss: 0.5584 - val_accuracy: 0.7249 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.47711380996993935
Confusion Matrix :
 [[3243 1080]
 [1181 3142]]
Accuracy on test set:    0.7384917881101087
Sensitivity:    0.7268100855887115 	 Specificity:    0.7501734906315058
Precision  : 0.744197063003316
Area Under Curve:    0.7384917881101087
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6286 - accuracy: 0.6472 - val_loss: 0.5833 - val_accuracy: 0.6857 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5699 - accuracy: 0.7067 - val_loss: 0.5641 - val_accuracy: 0.7019 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5522 - accuracy: 0.7162 - val_loss: 0.5554 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7230 - val_loss: 0.5571 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7294 - val_loss: 0.5458 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5295 - accuracy: 0.7327 - val_loss: 0.5459 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5213 - accuracy: 0.7378 - val_loss: 0.5487 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7435 - val_loss: 0.5442 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5073 - accuracy: 0.7472 - val_loss: 0.5486 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7499 - val_loss: 0.5489 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7522 - val_loss: 0.5414 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7535 - val_loss: 0.5474 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7583 - val_loss: 0.5544 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7590 - val_loss: 0.5643 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7629 - val_loss: 0.5574 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4698 - accuracy: 0.7655
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4700 - accuracy: 0.7655 - val_loss: 0.5586 - val_accuracy: 0.7164 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4740011960771919
Confusion Matrix :
 [[3283 1040]
 [1236 3087]]
Accuracy on test set:    0.7367568817950497
Sensitivity:    0.714087439278279 	 Specificity:    0.7594263243118204
Precision  : 0.7480009692270414
Area Under Curve:    0.7367568817950496
(8646, 4352) (8646,)
Mean MCC = 0.4450 + 0.0210 and Mean AUC = 0.7215 + 0.0107
Mean Sensitivity = 0.7471 + 0.0366 and Mean Specificity = 0.6960 + 0.0443 and Mean Accuracy = 0.7215 + 0.0107
Mean Precision = 0.7122 + 0.0219





Seed   : 213679
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6041 - accuracy: 0.6688 - val_loss: 0.5629 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7140 - val_loss: 0.5433 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7292 - val_loss: 0.5398 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7338 - val_loss: 0.5432 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7379 - val_loss: 0.5452 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5137 - accuracy: 0.7429 - val_loss: 0.5404 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7461 - val_loss: 0.5350 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7512 - val_loss: 0.5326 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7550 - val_loss: 0.5377 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7582 - val_loss: 0.5375 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7607 - val_loss: 0.5409 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4737 - accuracy: 0.7664 - val_loss: 0.5397 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4663 - accuracy: 0.7712 - val_loss: 0.5448 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4619 - accuracy: 0.7747 - val_loss: 0.5430 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4555 - accuracy: 0.7767 - val_loss: 0.5426 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 16/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4489 - accuracy: 0.7813 - val_loss: 0.5500 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4449 - accuracy: 0.7834 - val_loss: 0.5630 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4338 - accuracy: 0.7898 - val_loss: 0.5566 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4322 - accuracy: 0.7896 - val_loss: 0.5596 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4225 - accuracy: 0.7954 - val_loss: 0.5673 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4192 - accuracy: 0.7953 - val_loss: 0.5667 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 22/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4135 - accuracy: 0.7987 - val_loss: 0.6026 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 23/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4059 - accuracy: 0.8019
Epoch 23: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4063 - accuracy: 0.8013 - val_loss: 0.5815 - val_accuracy: 0.7201 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4173719244009128
Confusion Matrix :
 [[2981 1342]
 [1178 3145]]
Accuracy on test set:    0.7085357390700903
Sensitivity:    0.7275040481147351 	 Specificity:    0.6895674300254453
Precision  : 0.7009137508357477
Area Under Curve:    0.7085357390700903
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6114 - accuracy: 0.6650 - val_loss: 0.5676 - val_accuracy: 0.7039 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5620 - accuracy: 0.7085 - val_loss: 0.5496 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7191 - val_loss: 0.5432 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7277 - val_loss: 0.5409 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7316 - val_loss: 0.5393 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7341 - val_loss: 0.5381 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7404 - val_loss: 0.5383 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7426 - val_loss: 0.5381 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7473 - val_loss: 0.5365 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4985 - accuracy: 0.7506
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4987 - accuracy: 0.7504 - val_loss: 0.5352 - val_accuracy: 0.7251 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4463765218422663
Confusion Matrix :
 [[3011 1312]
 [1084 3239]]
Accuracy on test set:    0.7228776312745778
Sensitivity:    0.7492482072634744 	 Specificity:    0.6965070552856812
Precision  : 0.7117117117117117
Area Under Curve:    0.7228776312745778
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6093 - accuracy: 0.6624 - val_loss: 0.5636 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7105 - val_loss: 0.5548 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7222 - val_loss: 0.5464 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7290 - val_loss: 0.5451 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5274 - accuracy: 0.7322 - val_loss: 0.5406 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7387 - val_loss: 0.5383 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5125 - accuracy: 0.7429 - val_loss: 0.5352 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7433 - val_loss: 0.5367 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7493 - val_loss: 0.5364 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4961 - accuracy: 0.7530 - val_loss: 0.5391 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7582 - val_loss: 0.5411 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4827 - accuracy: 0.7616 - val_loss: 0.5396 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7653 - val_loss: 0.5432 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4716 - accuracy: 0.7673 - val_loss: 0.5485 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4662 - accuracy: 0.7699 - val_loss: 0.5486 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4624 - accuracy: 0.7712
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4615 - accuracy: 0.7718 - val_loss: 0.5608 - val_accuracy: 0.7204 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.45130696275734444
Confusion Matrix :
 [[3137 1186]
 [1186 3137]]
Accuracy on test set:    0.7256534813786722
Sensitivity:    0.7256534813786722 	 Specificity:    0.7256534813786722
Precision  : 0.7256534813786722
Area Under Curve:    0.7256534813786721
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6001 - accuracy: 0.6703 - val_loss: 0.5627 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5578 - accuracy: 0.7126 - val_loss: 0.5491 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7257 - val_loss: 0.5422 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7314 - val_loss: 0.5373 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7368 - val_loss: 0.5460 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5146 - accuracy: 0.7416 - val_loss: 0.5376 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5078 - accuracy: 0.7471 - val_loss: 0.5383 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7524 - val_loss: 0.5412 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4954 - accuracy: 0.7547 - val_loss: 0.5371 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4902 - accuracy: 0.7584 - val_loss: 0.5409 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4810 - accuracy: 0.7633 - val_loss: 0.5448 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4756 - accuracy: 0.7663
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4750 - accuracy: 0.7668 - val_loss: 0.5455 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4395088140997858
Confusion Matrix :
 [[3041 1282]
 [1142 3181]]
Accuracy on test set:    0.7196391394864677
Sensitivity:    0.7358315984270183 	 Specificity:    0.7034466805459172
Precision  : 0.7127492717902756
Area Under Curve:    0.7196391394864677
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6153 - accuracy: 0.6587 - val_loss: 0.5644 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5621 - accuracy: 0.7100 - val_loss: 0.5495 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7199 - val_loss: 0.5445 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7285 - val_loss: 0.5447 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7320 - val_loss: 0.5399 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5206 - accuracy: 0.7371 - val_loss: 0.5373 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7421 - val_loss: 0.5344 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7449 - val_loss: 0.5445 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7471 - val_loss: 0.5396 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7523 - val_loss: 0.5501 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4890 - accuracy: 0.7569 - val_loss: 0.5400 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4847 - accuracy: 0.7572 - val_loss: 0.5397 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7643 - val_loss: 0.5488 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4711 - accuracy: 0.7677 - val_loss: 0.5502 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4660 - accuracy: 0.7697 - val_loss: 0.5498 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4598 - accuracy: 0.7725 - val_loss: 0.5508 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4543 - accuracy: 0.7758 - val_loss: 0.5506 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4498 - accuracy: 0.7809
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4506 - accuracy: 0.7802 - val_loss: 0.5553 - val_accuracy: 0.7208 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.4291371968346217
Confusion Matrix :
 [[2910 1413]
 [1061 3262]]
Accuracy on test set:    0.7138561184362711
Sensitivity:    0.7545685866296553 	 Specificity:    0.6731436502428869
Precision  : 0.6977540106951872
Area Under Curve:    0.7138561184362712
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6127 - accuracy: 0.6619 - val_loss: 0.5599 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5597 - accuracy: 0.7138 - val_loss: 0.5479 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7233 - val_loss: 0.5464 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7294 - val_loss: 0.5441 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7344 - val_loss: 0.5433 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7405 - val_loss: 0.5415 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7420 - val_loss: 0.5353 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7458 - val_loss: 0.5394 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7498 - val_loss: 0.5364 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7525 - val_loss: 0.5460 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7556 - val_loss: 0.5367 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4837 - accuracy: 0.7606 - val_loss: 0.5395 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4802 - accuracy: 0.7640 - val_loss: 0.5499 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4765 - accuracy: 0.7656
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4762 - accuracy: 0.7654 - val_loss: 0.5429 - val_accuracy: 0.7244 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4284292257304891
Confusion Matrix :
 [[2869 1454]
 [1026 3297]]
Accuracy on test set:    0.7131621559102476
Sensitivity:    0.7626648160999306 	 Specificity:    0.6636594957205644
Precision  : 0.693959166491265
Area Under Curve:    0.7131621559102475
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6253 - accuracy: 0.6462 - val_loss: 0.5720 - val_accuracy: 0.7010 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5676 - accuracy: 0.7081 - val_loss: 0.5578 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7213 - val_loss: 0.5489 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7286 - val_loss: 0.5457 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7300 - val_loss: 0.5426 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7359 - val_loss: 0.5445 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 7/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5197 - accuracy: 0.7383 - val_loss: 0.5429 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5137 - accuracy: 0.7412 - val_loss: 0.5420 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7484 - val_loss: 0.5402 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5017 - accuracy: 0.7495 - val_loss: 0.5419 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7518 - val_loss: 0.5468 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7572 - val_loss: 0.5433 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7567 - val_loss: 0.5463 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4849 - accuracy: 0.7601
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4850 - accuracy: 0.7602 - val_loss: 0.5471 - val_accuracy: 0.7208 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.4632209491451745
Confusion Matrix :
 [[3114 1209]
 [1112 3211]]
Accuracy on test set:    0.7315521628498728
Sensitivity:    0.7427712236872542 	 Specificity:    0.7203331020124913
Precision  : 0.7264705882352941
Area Under Curve:    0.7315521628498728
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6157 - accuracy: 0.6613 - val_loss: 0.5643 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7100 - val_loss: 0.5535 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7220 - val_loss: 0.5465 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7297 - val_loss: 0.5467 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5280 - accuracy: 0.7339 - val_loss: 0.5374 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5213 - accuracy: 0.7376 - val_loss: 0.5395 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5112 - accuracy: 0.7455 - val_loss: 0.5390 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7459 - val_loss: 0.5404 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7490 - val_loss: 0.5455 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4929 - accuracy: 0.7563 - val_loss: 0.5372 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4884 - accuracy: 0.7583 - val_loss: 0.5411 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 12/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4771 - accuracy: 0.7652
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7644 - val_loss: 0.5394 - val_accuracy: 0.7212 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4475736579361463
Confusion Matrix :
 [[3010 1313]
 [1078 3245]]
Accuracy on test set:    0.7234559333795975
Sensitivity:    0.7506361323155216 	 Specificity:    0.6962757344436734
Precision  : 0.7119350592365072
Area Under Curve:    0.7234559333795976
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6092 - accuracy: 0.6651 - val_loss: 0.5643 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7108 - val_loss: 0.5505 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7219 - val_loss: 0.5538 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7318 - val_loss: 0.5440 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5263 - accuracy: 0.7351 - val_loss: 0.5369 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7392 - val_loss: 0.5487 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5125 - accuracy: 0.7434 - val_loss: 0.5390 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5055 - accuracy: 0.7477 - val_loss: 0.5361 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7530 - val_loss: 0.5434 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7571 - val_loss: 0.5430 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4873 - accuracy: 0.7592 - val_loss: 0.5360 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7637 - val_loss: 0.5452 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4723 - accuracy: 0.7684 - val_loss: 0.5386 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4651 - accuracy: 0.7728 - val_loss: 0.5469 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4624 - accuracy: 0.7730 - val_loss: 0.5541 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4518 - accuracy: 0.7803
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4525 - accuracy: 0.7801 - val_loss: 0.5484 - val_accuracy: 0.7262 - lr: 0.0010
271/271 [==============================] - 0s 670us/step
Independent Testing Matthews Correlation:  0.4705132519678912
Confusion Matrix :
 [[3190 1133]
 [1156 3167]]
Accuracy on test set:    0.7352532963219987
Sensitivity:    0.7325931066389082 	 Specificity:    0.7379134860050891
Precision  : 0.7365116279069768
Area Under Curve:    0.7352532963219987
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6133 - accuracy: 0.6575 - val_loss: 0.5726 - val_accuracy: 0.7034 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5622 - accuracy: 0.7109 - val_loss: 0.5583 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7230 - val_loss: 0.5503 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7276 - val_loss: 0.5483 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5287 - accuracy: 0.7315 - val_loss: 0.5448 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7372 - val_loss: 0.5479 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7421 - val_loss: 0.5554 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5110 - accuracy: 0.7442 - val_loss: 0.5381 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7479 - val_loss: 0.5474 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4999 - accuracy: 0.7530 - val_loss: 0.5397 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7560 - val_loss: 0.5423 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7610 - val_loss: 0.5558 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7635 - val_loss: 0.5466 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4758 - accuracy: 0.7667 - val_loss: 0.5553 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4704 - accuracy: 0.7716 - val_loss: 0.5486 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4641 - accuracy: 0.7726 - val_loss: 0.5539 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4598 - accuracy: 0.7763 - val_loss: 0.5564 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4536 - accuracy: 0.7801
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4538 - accuracy: 0.7796 - val_loss: 0.5571 - val_accuracy: 0.7242 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.4938512720611403
Confusion Matrix :
 [[3411  912]
 [1284 3039]]
Accuracy on test set:    0.7460097154753643
Sensitivity:    0.7029840388619014 	 Specificity:    0.7890353920888272
Precision  : 0.7691723614274867
Area Under Curve:    0.7460097154753643
(8646, 4352) (8646,)
Mean MCC = 0.4487 + 0.0214 and Mean AUC = 0.7240 + 0.0107
Mean Sensitivity = 0.7384 + 0.0165 and Mean Specificity = 0.7096 + 0.0342 and Mean Accuracy = 0.7240 + 0.0107
Mean Precision = 0.7187 + 0.0211





Seed   : 602106
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6153 - accuracy: 0.6570 - val_loss: 0.5651 - val_accuracy: 0.6993 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5616 - accuracy: 0.7094 - val_loss: 0.5620 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7220 - val_loss: 0.5475 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7292 - val_loss: 0.5489 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5290 - accuracy: 0.7333 - val_loss: 0.5447 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7376 - val_loss: 0.5446 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7416 - val_loss: 0.5441 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7456 - val_loss: 0.5444 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7506 - val_loss: 0.5485 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7540 - val_loss: 0.5446 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7569 - val_loss: 0.5458 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4881 - accuracy: 0.7586 - val_loss: 0.5511 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4796 - accuracy: 0.7636 - val_loss: 0.5490 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4775 - accuracy: 0.7643 - val_loss: 0.5608 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4689 - accuracy: 0.7703 - val_loss: 0.5439 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4660 - accuracy: 0.7737 - val_loss: 0.5532 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4600 - accuracy: 0.7776 - val_loss: 0.5548 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 18/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4535 - accuracy: 0.7798
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4539 - accuracy: 0.7794 - val_loss: 0.5625 - val_accuracy: 0.7194 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.40383875429099697
Confusion Matrix :
 [[2789 1534]
 [1054 3269]]
Accuracy on test set:    0.7006708304418228
Sensitivity:    0.7561878325237104 	 Specificity:    0.6451538283599352
Precision  : 0.6806162814907349
Area Under Curve:    0.7006708304418228
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6046 - accuracy: 0.6681 - val_loss: 0.5668 - val_accuracy: 0.7003 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5582 - accuracy: 0.7108 - val_loss: 0.5582 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7250 - val_loss: 0.5574 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7295 - val_loss: 0.5504 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5227 - accuracy: 0.7381 - val_loss: 0.5417 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7406 - val_loss: 0.5412 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7440 - val_loss: 0.5466 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7483 - val_loss: 0.5448 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4956 - accuracy: 0.7533 - val_loss: 0.5400 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7554 - val_loss: 0.5427 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4865 - accuracy: 0.7572 - val_loss: 0.5433 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4796 - accuracy: 0.7602 - val_loss: 0.5461 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4749 - accuracy: 0.7660 - val_loss: 0.5480 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4677 - accuracy: 0.7708 - val_loss: 0.5505 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 15/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4617 - accuracy: 0.7712 - val_loss: 0.5565 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4557 - accuracy: 0.7757 - val_loss: 0.5640 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 17/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4479 - accuracy: 0.7814
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4489 - accuracy: 0.7804 - val_loss: 0.5597 - val_accuracy: 0.7173 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4362106290551985
Confusion Matrix :
 [[2933 1390]
 [1053 3270]]
Accuracy on test set:    0.7174415914873931
Sensitivity:    0.7564191533657183 	 Specificity:    0.6784640296090678
Precision  : 0.7017167381974249
Area Under Curve:    0.7174415914873931
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6051 - accuracy: 0.6698 - val_loss: 0.5642 - val_accuracy: 0.7005 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5559 - accuracy: 0.7121 - val_loss: 0.5553 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7230 - val_loss: 0.5527 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7314 - val_loss: 0.5448 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5210 - accuracy: 0.7382 - val_loss: 0.5454 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5165 - accuracy: 0.7409 - val_loss: 0.5420 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7473 - val_loss: 0.5408 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7503 - val_loss: 0.5387 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7538 - val_loss: 0.5441 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7587 - val_loss: 0.5395 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4815 - accuracy: 0.7632 - val_loss: 0.5466 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4782 - accuracy: 0.7641 - val_loss: 0.5460 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 13/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4686 - accuracy: 0.7679
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4680 - accuracy: 0.7681 - val_loss: 0.5505 - val_accuracy: 0.7161 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.43216259237927995
Confusion Matrix :
 [[2916 1407]
 [1054 3269]]
Accuracy on test set:    0.7153597039093222
Sensitivity:    0.7561878325237104 	 Specificity:    0.6745315752949341
Precision  : 0.6991017964071856
Area Under Curve:    0.7153597039093222
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6072 - accuracy: 0.6649 - val_loss: 0.5687 - val_accuracy: 0.6980 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5578 - accuracy: 0.7126 - val_loss: 0.5510 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7245 - val_loss: 0.5435 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7284 - val_loss: 0.5471 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7356 - val_loss: 0.5433 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7410 - val_loss: 0.5426 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7455 - val_loss: 0.5384 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7497 - val_loss: 0.5456 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7527 - val_loss: 0.5516 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7584 - val_loss: 0.5478 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4856 - accuracy: 0.7600 - val_loss: 0.5546 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4788 - accuracy: 0.7637
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4790 - accuracy: 0.7634 - val_loss: 0.5478 - val_accuracy: 0.7201 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.42697313532610925
Confusion Matrix :
 [[2776 1547]
 [ 948 3375]]
Accuracy on test set:    0.7114272495951885
Sensitivity:    0.7807078417765441 	 Specificity:    0.642146657413833
Precision  : 0.685696871190573
Area Under Curve:    0.7114272495951885
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6121 - accuracy: 0.6611 - val_loss: 0.5636 - val_accuracy: 0.7026 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5622 - accuracy: 0.7090 - val_loss: 0.5509 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7222 - val_loss: 0.5502 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7303 - val_loss: 0.5445 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7343 - val_loss: 0.5412 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5190 - accuracy: 0.7384 - val_loss: 0.5419 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5130 - accuracy: 0.7425 - val_loss: 0.5426 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7450 - val_loss: 0.5448 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5032 - accuracy: 0.7479 - val_loss: 0.5444 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4942 - accuracy: 0.7554 - val_loss: 0.5412 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7575 - val_loss: 0.5442 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4837 - accuracy: 0.7607 - val_loss: 0.5458 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4768 - accuracy: 0.7641 - val_loss: 0.5562 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4744 - accuracy: 0.7657 - val_loss: 0.5610 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7694 - val_loss: 0.5586 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4608 - accuracy: 0.7750 - val_loss: 0.5651 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4560 - accuracy: 0.7753 - val_loss: 0.5667 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4509 - accuracy: 0.7780 - val_loss: 0.5729 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4487 - accuracy: 0.7789 - val_loss: 0.5664 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4411 - accuracy: 0.7832 - val_loss: 0.5665 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 21/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4347 - accuracy: 0.7878
Epoch 21: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4349 - accuracy: 0.7874 - val_loss: 0.5792 - val_accuracy: 0.7164 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4284253862067099
Confusion Matrix :
 [[2835 1488]
 [ 995 3328]]
Accuracy on test set:    0.7128151746472358
Sensitivity:    0.7698357622021744 	 Specificity:    0.655794587092297
Precision  : 0.6910299003322259
Area Under Curve:    0.7128151746472355
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6118 - accuracy: 0.6626 - val_loss: 0.5627 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5587 - accuracy: 0.7144 - val_loss: 0.5486 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7225 - val_loss: 0.5495 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7303 - val_loss: 0.5435 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7379 - val_loss: 0.5468 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5192 - accuracy: 0.7387 - val_loss: 0.5446 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5105 - accuracy: 0.7448 - val_loss: 0.5402 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7476 - val_loss: 0.5461 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5014 - accuracy: 0.7496 - val_loss: 0.5390 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4932 - accuracy: 0.7567 - val_loss: 0.5436 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4850 - accuracy: 0.7612 - val_loss: 0.5437 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4804 - accuracy: 0.7630 - val_loss: 0.5469 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4729 - accuracy: 0.7683 - val_loss: 0.5549 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7689 - val_loss: 0.5567 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4623 - accuracy: 0.7728 - val_loss: 0.5589 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4575 - accuracy: 0.7759
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4579 - accuracy: 0.7756 - val_loss: 0.5574 - val_accuracy: 0.7156 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.4347029841411603
Confusion Matrix :
 [[3226 1097]
 [1350 2973]]
Accuracy on test set:    0.7169789498033773
Sensitivity:    0.6877168632893824 	 Specificity:    0.7462410363173722
Precision  : 0.7304668304668305
Area Under Curve:    0.7169789498033772
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6158 - accuracy: 0.6538 - val_loss: 0.5624 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5642 - accuracy: 0.7075 - val_loss: 0.5577 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7198 - val_loss: 0.5542 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7266 - val_loss: 0.5492 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5307 - accuracy: 0.7324 - val_loss: 0.5433 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7337 - val_loss: 0.5478 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7409 - val_loss: 0.5435 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7442 - val_loss: 0.5464 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7463 - val_loss: 0.5526 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7499 - val_loss: 0.5469 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7549 - val_loss: 0.5490 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7586 - val_loss: 0.5497 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4841 - accuracy: 0.7619 - val_loss: 0.5538 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4780 - accuracy: 0.7660 - val_loss: 0.5509 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4757 - accuracy: 0.7662 - val_loss: 0.5531 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4681 - accuracy: 0.7705
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4679 - accuracy: 0.7703 - val_loss: 0.5616 - val_accuracy: 0.7188 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4522462335913208
Confusion Matrix :
 [[3122 1201]
 [1167 3156]]
Accuracy on test set:    0.7261161230626879
Sensitivity:    0.7300485773768216 	 Specificity:    0.7221836687485542
Precision  : 0.7243516180858389
Area Under Curve:    0.7261161230626879
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6010 - accuracy: 0.6725 - val_loss: 0.5635 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7128 - val_loss: 0.5567 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7238 - val_loss: 0.5507 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7288 - val_loss: 0.5511 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5285 - accuracy: 0.7342 - val_loss: 0.5428 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5208 - accuracy: 0.7371 - val_loss: 0.5413 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7405 - val_loss: 0.5455 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7450 - val_loss: 0.5485 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7465 - val_loss: 0.5462 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7513 - val_loss: 0.5463 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7551 - val_loss: 0.5446 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7586 - val_loss: 0.5463 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4834 - accuracy: 0.7606 - val_loss: 0.5476 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4758 - accuracy: 0.7654 - val_loss: 0.5515 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4734 - accuracy: 0.7668
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4731 - accuracy: 0.7672 - val_loss: 0.5506 - val_accuracy: 0.7232 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.4588420279215631
Confusion Matrix :
 [[3205 1118]
 [1222 3101]]
Accuracy on test set:    0.7293546148507981
Sensitivity:    0.7173259310663891 	 Specificity:    0.741383298635207
Precision  : 0.7350082958046931
Area Under Curve:    0.7293546148507981
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6017 - accuracy: 0.6702 - val_loss: 0.5645 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7103 - val_loss: 0.5552 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7219 - val_loss: 0.5476 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7280 - val_loss: 0.5500 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7317 - val_loss: 0.5459 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7366 - val_loss: 0.5460 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7402 - val_loss: 0.5450 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7435 - val_loss: 0.5453 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7464 - val_loss: 0.5548 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4999 - accuracy: 0.7511
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5005 - accuracy: 0.7510 - val_loss: 0.5445 - val_accuracy: 0.7212 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4840523574581539
Confusion Matrix :
 [[3080 1243]
 [ 991 3332]]
Accuracy on test set:    0.7416146194772149
Sensitivity:    0.7707610455702059 	 Specificity:    0.712468193384224
Precision  : 0.7283060109289617
Area Under Curve:    0.7416146194772149
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6184 - accuracy: 0.6579 - val_loss: 0.5815 - val_accuracy: 0.6904 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5652 - accuracy: 0.7078 - val_loss: 0.5595 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5493 - accuracy: 0.7209 - val_loss: 0.5581 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7255 - val_loss: 0.5540 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7313 - val_loss: 0.5527 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7371 - val_loss: 0.5601 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7403 - val_loss: 0.5497 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5112 - accuracy: 0.7450 - val_loss: 0.5527 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7476 - val_loss: 0.5537 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7526 - val_loss: 0.5556 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7546 - val_loss: 0.5565 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4834 - accuracy: 0.7608
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4841 - accuracy: 0.7607 - val_loss: 0.5551 - val_accuracy: 0.7160 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.4920499057794078
Confusion Matrix :
 [[3295 1028]
 [1169 3154]]
Accuracy on test set:    0.7458940550543603
Sensitivity:    0.7295859356928059 	 Specificity:    0.7622021744159149
Precision  : 0.7541846006695361
Area Under Curve:    0.7458940550543605
(8646, 4352) (8646,)
Mean MCC = 0.4450 + 0.0257 and Mean AUC = 0.7218 + 0.0133
Mean Sensitivity = 0.7455 + 0.0273 and Mean Specificity = 0.6981 + 0.0421 and Mean Accuracy = 0.7218 + 0.0133
Mean Precision = 0.7130 + 0.0233





Seed   : 946675
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6079 - accuracy: 0.6656 - val_loss: 0.5692 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5573 - accuracy: 0.7145 - val_loss: 0.5595 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7237 - val_loss: 0.5558 - val_accuracy: 0.7059 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7311 - val_loss: 0.5396 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7368 - val_loss: 0.5399 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5177 - accuracy: 0.7402 - val_loss: 0.5394 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7442 - val_loss: 0.5353 - val_accuracy: 0.7249 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7499 - val_loss: 0.5375 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7525 - val_loss: 0.5381 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4922 - accuracy: 0.7566 - val_loss: 0.5434 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7628 - val_loss: 0.5444 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4793 - accuracy: 0.7633 - val_loss: 0.5414 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4742 - accuracy: 0.7672 - val_loss: 0.5490 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4685 - accuracy: 0.7704 - val_loss: 0.5477 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4599 - accuracy: 0.7761 - val_loss: 0.5470 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4562 - accuracy: 0.7745
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4563 - accuracy: 0.7750 - val_loss: 0.5444 - val_accuracy: 0.7263 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.4104339908796184
Confusion Matrix :
 [[2896 1427]
 [1126 3197]]
Accuracy on test set:    0.7047189451769604
Sensitivity:    0.7395327318991441 	 Specificity:    0.6699051584547768
Precision  : 0.6913927335640139
Area Under Curve:    0.7047189451769604
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6015 - accuracy: 0.6722 - val_loss: 0.5731 - val_accuracy: 0.6974 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5586 - accuracy: 0.7122 - val_loss: 0.5546 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7244 - val_loss: 0.5456 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5314 - accuracy: 0.7318 - val_loss: 0.5441 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7355 - val_loss: 0.5413 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5165 - accuracy: 0.7402 - val_loss: 0.5425 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7444 - val_loss: 0.5416 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5062 - accuracy: 0.7465 - val_loss: 0.5413 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7533 - val_loss: 0.5467 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 10/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4898 - accuracy: 0.7581
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7574 - val_loss: 0.5417 - val_accuracy: 0.7182 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.44661387861781676
Confusion Matrix :
 [[3217 1106]
 [1288 3035]]
Accuracy on test set:    0.7231089521165857
Sensitivity:    0.70205875549387 	 Specificity:    0.7441591487393014
Precision  : 0.7329147548901231
Area Under Curve:    0.7231089521165857
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6109 - accuracy: 0.6612 - val_loss: 0.5715 - val_accuracy: 0.6946 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5619 - accuracy: 0.7057 - val_loss: 0.5605 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7210 - val_loss: 0.5478 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7270 - val_loss: 0.5478 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5270 - accuracy: 0.7336 - val_loss: 0.5391 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5202 - accuracy: 0.7373 - val_loss: 0.5415 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7425 - val_loss: 0.5375 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5062 - accuracy: 0.7459 - val_loss: 0.5367 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4985 - accuracy: 0.7529 - val_loss: 0.5411 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7533 - val_loss: 0.5409 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7539 - val_loss: 0.5441 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7609 - val_loss: 0.5466 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 13/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4746 - accuracy: 0.7625
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4749 - accuracy: 0.7625 - val_loss: 0.5519 - val_accuracy: 0.7164 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4437772874921809
Confusion Matrix :
 [[3204 1119]
 [1287 3036]]
Accuracy on test set:    0.7217210270645386
Sensitivity:    0.7022900763358778 	 Specificity:    0.7411519777931992
Precision  : 0.7306859205776173
Area Under Curve:    0.7217210270645384
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6110 - accuracy: 0.6620 - val_loss: 0.5724 - val_accuracy: 0.6953 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5620 - accuracy: 0.7096 - val_loss: 0.5583 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7215 - val_loss: 0.5456 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7285 - val_loss: 0.5551 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5285 - accuracy: 0.7334 - val_loss: 0.5381 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7398 - val_loss: 0.5398 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7442 - val_loss: 0.5422 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7468 - val_loss: 0.5395 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7510 - val_loss: 0.5399 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7565 - val_loss: 0.5425 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 11/400

262/274 [===========================>..] - ETA: 0s - loss: 0.4858 - accuracy: 0.7601
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7598 - val_loss: 0.5395 - val_accuracy: 0.7206 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.43349149709676993
Confusion Matrix :
 [[2838 1485]
 [ 977 3346]]
Accuracy on test set:    0.7152440434883183
Sensitivity:    0.773999537358316 	 Specificity:    0.6564885496183206
Precision  : 0.6926102256261644
Area Under Curve:    0.7152440434883183
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6029 - accuracy: 0.6697 - val_loss: 0.5664 - val_accuracy: 0.7014 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5577 - accuracy: 0.7149 - val_loss: 0.5502 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7231 - val_loss: 0.5488 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7300 - val_loss: 0.5509 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5247 - accuracy: 0.7339 - val_loss: 0.5385 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7396 - val_loss: 0.5392 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7427 - val_loss: 0.5357 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7492 - val_loss: 0.5422 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7534 - val_loss: 0.5415 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4932 - accuracy: 0.7556 - val_loss: 0.5445 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7577 - val_loss: 0.5376 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4792 - accuracy: 0.7654 - val_loss: 0.5373 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4717 - accuracy: 0.7693 - val_loss: 0.5418 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4658 - accuracy: 0.7716 - val_loss: 0.5458 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4582 - accuracy: 0.7754 - val_loss: 0.5489 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 16/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4568 - accuracy: 0.7776
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4568 - accuracy: 0.7775 - val_loss: 0.5496 - val_accuracy: 0.7238 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.441085335966262
Confusion Matrix :
 [[2778 1545]
 [ 893 3430]]
Accuracy on test set:    0.7180198935924127
Sensitivity:    0.7934304880869766 	 Specificity:    0.6426092990978487
Precision  : 0.6894472361809045
Area Under Curve:    0.7180198935924127
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6122 - accuracy: 0.6634 - val_loss: 0.5661 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5597 - accuracy: 0.7114 - val_loss: 0.5462 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7219 - val_loss: 0.5419 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7297 - val_loss: 0.5388 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7345 - val_loss: 0.5352 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7383 - val_loss: 0.5373 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5141 - accuracy: 0.7418 - val_loss: 0.5371 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7470 - val_loss: 0.5441 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7508 - val_loss: 0.5337 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7545 - val_loss: 0.5390 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7576 - val_loss: 0.5357 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7610 - val_loss: 0.5360 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4730 - accuracy: 0.7666 - val_loss: 0.5424 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7694 - val_loss: 0.5440 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4615 - accuracy: 0.7726 - val_loss: 0.5515 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4606 - accuracy: 0.7726 - val_loss: 0.5490 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4544 - accuracy: 0.7771 - val_loss: 0.5578 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4457 - accuracy: 0.7800 - val_loss: 0.5481 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 19/400
264/274 [===========================>..] - ETA: 0s - loss: 0.4407 - accuracy: 0.7829
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4414 - accuracy: 0.7826 - val_loss: 0.5658 - val_accuracy: 0.7187 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.4424296327894918
Confusion Matrix :
 [[2885 1438]
 [ 983 3340]]
Accuracy on test set:    0.7199861207494795
Sensitivity:    0.7726116123062688 	 Specificity:    0.6673606291926902
Precision  : 0.6990372540812055
Area Under Curve:    0.7199861207494795
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6121 - accuracy: 0.6616 - val_loss: 0.5640 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5612 - accuracy: 0.7109 - val_loss: 0.5569 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7193 - val_loss: 0.5436 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7275 - val_loss: 0.5397 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7321 - val_loss: 0.5425 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5211 - accuracy: 0.7388 - val_loss: 0.5453 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7398 - val_loss: 0.5374 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5078 - accuracy: 0.7447 - val_loss: 0.5490 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7494 - val_loss: 0.5371 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7508 - val_loss: 0.5423 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7538 - val_loss: 0.5415 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7583 - val_loss: 0.5369 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4811 - accuracy: 0.7610 - val_loss: 0.5451 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4762 - accuracy: 0.7642 - val_loss: 0.5539 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4719 - accuracy: 0.7667 - val_loss: 0.5538 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4662 - accuracy: 0.7700 - val_loss: 0.5541 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4584 - accuracy: 0.7736
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4588 - accuracy: 0.7736 - val_loss: 0.5544 - val_accuracy: 0.7215 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.4514269368669385
Confusion Matrix :
 [[2897 1426]
 [ 957 3366]]
Accuracy on test set:    0.724381216747629
Sensitivity:    0.7786259541984732 	 Specificity:    0.6701364792967847
Precision  : 0.7024207011686143
Area Under Curve:    0.7243812167476289
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6064 - accuracy: 0.6652 - val_loss: 0.5646 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7102 - val_loss: 0.5579 - val_accuracy: 0.7107 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7188 - val_loss: 0.5474 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7252 - val_loss: 0.5434 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7335 - val_loss: 0.5442 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7365 - val_loss: 0.5424 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7437 - val_loss: 0.5403 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7442 - val_loss: 0.5433 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7491 - val_loss: 0.5462 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4956 - accuracy: 0.7546 - val_loss: 0.5411 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7562 - val_loss: 0.5370 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7605 - val_loss: 0.5435 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7649 - val_loss: 0.5472 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4737 - accuracy: 0.7681 - val_loss: 0.5446 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4694 - accuracy: 0.7680 - val_loss: 0.5535 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4619 - accuracy: 0.7741 - val_loss: 0.5521 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4573 - accuracy: 0.7783 - val_loss: 0.5504 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 18/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4505 - accuracy: 0.7811
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4509 - accuracy: 0.7809 - val_loss: 0.5566 - val_accuracy: 0.7183 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4487677284506226
Confusion Matrix :
 [[3121 1202]
 [1181 3142]]
Accuracy on test set:    0.724381216747629
Sensitivity:    0.7268100855887115 	 Specificity:    0.7219523479065464
Precision  : 0.7232965009208103
Area Under Curve:    0.724381216747629
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6078 - accuracy: 0.6645 - val_loss: 0.5780 - val_accuracy: 0.6917 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5612 - accuracy: 0.7098 - val_loss: 0.5503 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7193 - val_loss: 0.5473 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7277 - val_loss: 0.5395 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7322 - val_loss: 0.5450 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7372 - val_loss: 0.5406 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7403 - val_loss: 0.5374 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7451 - val_loss: 0.5366 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7451 - val_loss: 0.5409 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7491 - val_loss: 0.5384 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4954 - accuracy: 0.7531 - val_loss: 0.5441 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7562 - val_loss: 0.5381 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4822 - accuracy: 0.7616 - val_loss: 0.5485 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4768 - accuracy: 0.7647 - val_loss: 0.5535 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4711 - accuracy: 0.7667 - val_loss: 0.5511 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4661 - accuracy: 0.7695 - val_loss: 0.5541 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 17/400

258/274 [===========================>..] - ETA: 0s - loss: 0.4603 - accuracy: 0.7738
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4613 - accuracy: 0.7728 - val_loss: 0.5502 - val_accuracy: 0.7238 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.46975932204580106
Confusion Matrix :
 [[3236 1087]
 [1206 3117]]
Accuracy on test set:    0.7347906546379829
Sensitivity:    0.721027064538515 	 Specificity:    0.7485542447374508
Precision  : 0.7414367269267365
Area Under Curve:    0.7347906546379829
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6151 - accuracy: 0.6579 - val_loss: 0.5684 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5661 - accuracy: 0.7067 - val_loss: 0.5515 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5499 - accuracy: 0.7192 - val_loss: 0.5458 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7263 - val_loss: 0.5432 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5301 - accuracy: 0.7318 - val_loss: 0.5415 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7357 - val_loss: 0.5423 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7408 - val_loss: 0.5404 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7432 - val_loss: 0.5429 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7493 - val_loss: 0.5454 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4981 - accuracy: 0.7522
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7521 - val_loss: 0.5451 - val_accuracy: 0.7244 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.5048140565673364
Confusion Matrix :
 [[3216 1107]
 [1034 3289]]
Accuracy on test set:    0.7523710386305806
Sensitivity:    0.7608142493638677 	 Specificity:    0.7439278278972935
Precision  : 0.7481801637852593
Area Under Curve:    0.7523710386305806
(8646, 4352) (8646,)
Mean MCC = 0.4493 + 0.0233 and Mean AUC = 0.7239 + 0.0119
Mean Sensitivity = 0.7471 + 0.0314 and Mean Specificity = 0.7006 + 0.0406 and Mean Accuracy = 0.7239 + 0.0119
Mean Precision = 0.7151 + 0.0214





Seed   : 617107
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6088 - accuracy: 0.6662 - val_loss: 0.5632 - val_accuracy: 0.7016 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5555 - accuracy: 0.7143 - val_loss: 0.5480 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7246 - val_loss: 0.5447 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7305 - val_loss: 0.5404 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5206 - accuracy: 0.7380 - val_loss: 0.5378 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7426 - val_loss: 0.5333 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7466 - val_loss: 0.5367 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7514 - val_loss: 0.5298 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7545 - val_loss: 0.5320 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7590 - val_loss: 0.5344 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4821 - accuracy: 0.7634 - val_loss: 0.5324 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4741 - accuracy: 0.7671 - val_loss: 0.5325 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7712 - val_loss: 0.5391 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 14/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4597 - accuracy: 0.7761
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4613 - accuracy: 0.7750 - val_loss: 0.5394 - val_accuracy: 0.7274 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.39925510460164326
Confusion Matrix :
 [[2920 1403]
 [1196 3127]]
Accuracy on test set:    0.6993985658107795
Sensitivity:    0.7233402729585936 	 Specificity:    0.6754568586629656
Precision  : 0.6902869757174392
Area Under Curve:    0.6993985658107795
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6092 - accuracy: 0.6665 - val_loss: 0.5736 - val_accuracy: 0.6940 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5597 - accuracy: 0.7117 - val_loss: 0.5534 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7209 - val_loss: 0.5563 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7291 - val_loss: 0.5393 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7345 - val_loss: 0.5431 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7381 - val_loss: 0.5399 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7431 - val_loss: 0.5410 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7481 - val_loss: 0.5402 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7518 - val_loss: 0.5490 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7571 - val_loss: 0.5462 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4832 - accuracy: 0.7605 - val_loss: 0.5469 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4759 - accuracy: 0.7647 - val_loss: 0.5420 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4709 - accuracy: 0.7674 - val_loss: 0.5399 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4660 - accuracy: 0.7703 - val_loss: 0.5498 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 15/400
256/274 [===========================>..] - ETA: 0s - loss: 0.4559 - accuracy: 0.7767
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4574 - accuracy: 0.7755 - val_loss: 0.5498 - val_accuracy: 0.7200 - lr: 0.0010

271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.43480631114539925
Confusion Matrix :
 [[2815 1508]
 [ 951 3372]]
Accuracy on test set:    0.7155910247513301
Sensitivity:    0.7800138792505205 	 Specificity:    0.6511681702521397
Precision  : 0.690983606557377
Area Under Curve:    0.7155910247513301
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6084 - accuracy: 0.6664 - val_loss: 0.5687 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5563 - accuracy: 0.7134 - val_loss: 0.5502 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7255 - val_loss: 0.5492 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7318 - val_loss: 0.5449 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7356 - val_loss: 0.5503 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7397 - val_loss: 0.5440 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7454 - val_loss: 0.5356 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7489 - val_loss: 0.5405 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4973 - accuracy: 0.7525 - val_loss: 0.5415 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7545 - val_loss: 0.5401 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4868 - accuracy: 0.7593 - val_loss: 0.5525 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4785 - accuracy: 0.7643
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4786 - accuracy: 0.7641 - val_loss: 0.5487 - val_accuracy: 0.7245 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.44081332706967874
Confusion Matrix :
 [[3347  976]
 [1453 2870]]
Accuracy on test set:    0.7190608373814481
Sensitivity:    0.6638908165625723 	 Specificity:    0.7742308582003239
Precision  : 0.7462298491939677
Area Under Curve:    0.7190608373814481
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6095 - accuracy: 0.6616 - val_loss: 0.5718 - val_accuracy: 0.6976 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7101 - val_loss: 0.5494 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7233 - val_loss: 0.5465 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7302 - val_loss: 0.5440 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7344 - val_loss: 0.5618 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7402 - val_loss: 0.5386 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7461 - val_loss: 0.5371 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7449 - val_loss: 0.5367 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4973 - accuracy: 0.7533 - val_loss: 0.5489 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7580 - val_loss: 0.5421 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7602 - val_loss: 0.5506 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4780 - accuracy: 0.7650
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4786 - accuracy: 0.7649 - val_loss: 0.5476 - val_accuracy: 0.7226 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4320457832737951
Confusion Matrix :
 [[2895 1428]
 [1035 3288]]
Accuracy on test set:    0.7151283830673144
Sensitivity:    0.7605829285218598 	 Specificity:    0.6696738376127689
Precision  : 0.6972010178117048
Area Under Curve:    0.7151283830673143
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6020 - accuracy: 0.6706 - val_loss: 0.5636 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7119 - val_loss: 0.5486 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7258 - val_loss: 0.5482 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7284 - val_loss: 0.5381 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7347 - val_loss: 0.5393 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7399 - val_loss: 0.5399 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7441 - val_loss: 0.5394 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5047 - accuracy: 0.7477 - val_loss: 0.5374 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7511 - val_loss: 0.5386 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7557 - val_loss: 0.5353 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4854 - accuracy: 0.7581 - val_loss: 0.5423 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7626 - val_loss: 0.5463 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4726 - accuracy: 0.7662 - val_loss: 0.5570 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4631 - accuracy: 0.7735
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4637 - accuracy: 0.7729 - val_loss: 0.5479 - val_accuracy: 0.7218 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4606272872183517
Confusion Matrix :
 [[3194 1129]
 [1203 3120]]
Accuracy on test set:    0.7302798982188295
Sensitivity:    0.7217210270645386 	 Specificity:    0.7388387693731205
Precision  : 0.7342904212755943
Area Under Curve:    0.7302798982188297
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6145 - accuracy: 0.6631 - val_loss: 0.5691 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5600 - accuracy: 0.7110 - val_loss: 0.5532 - val_accuracy: 0.7123 - lr: 0.0010

Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7217 - val_loss: 0.5433 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7284 - val_loss: 0.5418 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5263 - accuracy: 0.7347 - val_loss: 0.5403 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7387 - val_loss: 0.5420 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7419 - val_loss: 0.5419 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7469 - val_loss: 0.5397 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5006 - accuracy: 0.7498 - val_loss: 0.5336 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7547 - val_loss: 0.5396 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7550 - val_loss: 0.5373 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7587 - val_loss: 0.5425 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7642 - val_loss: 0.5435 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4706 - accuracy: 0.7688 - val_loss: 0.5422 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4644 - accuracy: 0.7698
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4656 - accuracy: 0.7689 - val_loss: 0.5426 - val_accuracy: 0.7223 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.43306275364205327
Confusion Matrix :
 [[3123 1200]
 [1251 3072]]
Accuracy on test set:    0.7165163081193615
Sensitivity:    0.710617626648161 	 Specificity:    0.7224149895905622
Precision  : 0.7191011235955056
Area Under Curve:    0.7165163081193615
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6130 - accuracy: 0.6645 - val_loss: 0.5730 - val_accuracy: 0.6958 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5586 - accuracy: 0.7112 - val_loss: 0.5660 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7213 - val_loss: 0.5491 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7292 - val_loss: 0.5453 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5272 - accuracy: 0.7343 - val_loss: 0.5484 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7397 - val_loss: 0.5459 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7440 - val_loss: 0.5408 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7457 - val_loss: 0.5408 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7504 - val_loss: 0.5481 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7540 - val_loss: 0.5438 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4873 - accuracy: 0.7582 - val_loss: 0.5465 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4842 - accuracy: 0.7592 - val_loss: 0.5459 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4801 - accuracy: 0.7633 - val_loss: 0.5424 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4719 - accuracy: 0.7679 - val_loss: 0.5524 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4630 - accuracy: 0.7724
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4632 - accuracy: 0.7724 - val_loss: 0.5502 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.45063133852717535
Confusion Matrix :
 [[3116 1207]
 [1168 3155]]
Accuracy on test set:    0.7253065001156604
Sensitivity:    0.7298172565348138 	 Specificity:    0.720795743696507
Precision  : 0.7232920678587804
Area Under Curve:    0.7253065001156604
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6001 - accuracy: 0.6734 - val_loss: 0.5699 - val_accuracy: 0.6996 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5588 - accuracy: 0.7117 - val_loss: 0.5556 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7219 - val_loss: 0.5493 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7292 - val_loss: 0.5472 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7359 - val_loss: 0.5490 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7386 - val_loss: 0.5453 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5111 - accuracy: 0.7431 - val_loss: 0.5389 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5042 - accuracy: 0.7496 - val_loss: 0.5412 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7514 - val_loss: 0.5400 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7573 - val_loss: 0.5427 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4851 - accuracy: 0.7612 - val_loss: 0.5414 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7641 - val_loss: 0.5436 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7694 - val_loss: 0.5515 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4632 - accuracy: 0.7741 - val_loss: 0.5460 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4576 - accuracy: 0.7770 - val_loss: 0.5526 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 16/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4515 - accuracy: 0.7811
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4526 - accuracy: 0.7803 - val_loss: 0.5488 - val_accuracy: 0.7215 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.45582749354931673
Confusion Matrix :
 [[2982 1341]
 [1017 3306]]
Accuracy on test set:    0.7272727272727273
Sensitivity:    0.7647467036780013 	 Specificity:    0.6897987508674531
Precision  : 0.7114267269205939
Area Under Curve:    0.7272727272727273
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6141 - accuracy: 0.6583 - val_loss: 0.5777 - val_accuracy: 0.6979 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5631 - accuracy: 0.7090 - val_loss: 0.5542 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7214 - val_loss: 0.5497 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7272 - val_loss: 0.5456 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5277 - accuracy: 0.7328 - val_loss: 0.5498 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7351 - val_loss: 0.5457 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7430 - val_loss: 0.5409 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7443 - val_loss: 0.5491 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7463 - val_loss: 0.5477 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7537 - val_loss: 0.5494 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7567 - val_loss: 0.5475 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7592 - val_loss: 0.5564 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4768 - accuracy: 0.7633 - val_loss: 0.5546 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4722 - accuracy: 0.7669
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4723 - accuracy: 0.7668 - val_loss: 0.5589 - val_accuracy: 0.7201 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.48976131214264024
Confusion Matrix :
 [[3099 1224]
 [ 985 3338]]
Accuracy on test set:    0.7445061300023132
Sensitivity:    0.7721489706222531 	 Specificity:    0.7168632893823733
Precision  : 0.7316966242875932
Area Under Curve:    0.7445061300023132
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6104 - accuracy: 0.6646 - val_loss: 0.5736 - val_accuracy: 0.7038 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5625 - accuracy: 0.7092 - val_loss: 0.5624 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7189 - val_loss: 0.5602 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7273 - val_loss: 0.5504 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7321 - val_loss: 0.5476 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7377 - val_loss: 0.5525 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7415 - val_loss: 0.5504 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7458 - val_loss: 0.5545 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7498 - val_loss: 0.5514 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7554 - val_loss: 0.5567 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7580 - val_loss: 0.5617 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4832 - accuracy: 0.7617 - val_loss: 0.5618 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4756 - accuracy: 0.7665 - val_loss: 0.5678 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4685 - accuracy: 0.7694
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7696 - val_loss: 0.5668 - val_accuracy: 0.7149 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4877601807716556
Confusion Matrix :
 [[3356  967]
 [1252 3071]]
Accuracy on test set:    0.7433495257922739
Sensitivity:    0.7103863058061531 	 Specificity:    0.7763127457783946
Precision  : 0.7605250123823675
Area Under Curve:    0.7433495257922738
(8646, 4352) (8646,)
Mean MCC = 0.4485 + 0.0257 and Mean AUC = 0.7236 + 0.0130
Mean Sensitivity = 0.7337 + 0.0339 and Mean Specificity = 0.7136 + 0.0403 and Mean Accuracy = 0.7236 + 0.0130
Mean Precision = 0.7205 + 0.0224





Seed   : 545965
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6070 - accuracy: 0.6670 - val_loss: 0.5717 - val_accuracy: 0.6988 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5621 - accuracy: 0.7112 - val_loss: 0.5500 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7220 - val_loss: 0.5432 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7291 - val_loss: 0.5403 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5276 - accuracy: 0.7329 - val_loss: 0.5398 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5213 - accuracy: 0.7371 - val_loss: 0.5358 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5144 - accuracy: 0.7440 - val_loss: 0.5355 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7450 - val_loss: 0.5331 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7483 - val_loss: 0.5350 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7526 - val_loss: 0.5340 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7576 - val_loss: 0.5407 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7583 - val_loss: 0.5402 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4817 - accuracy: 0.7621 - val_loss: 0.5380 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4768 - accuracy: 0.7645 - val_loss: 0.5414 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 15/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4742 - accuracy: 0.7661
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4737 - accuracy: 0.7668 - val_loss: 0.5486 - val_accuracy: 0.7165 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4304772001602519
Confusion Matrix :
 [[2603 1720]
 [ 786 3537]]
Accuracy on test set:    0.7101549849641453
Sensitivity:    0.8181818181818182 	 Specificity:    0.6021281517464724
Precision  : 0.6728171961194598
Area Under Curve:    0.7101549849641453
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6086 - accuracy: 0.6660 - val_loss: 0.5692 - val_accuracy: 0.6944 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5578 - accuracy: 0.7125 - val_loss: 0.5567 - val_accuracy: 0.7059 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7245 - val_loss: 0.5448 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5288 - accuracy: 0.7327 - val_loss: 0.5400 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5210 - accuracy: 0.7386 - val_loss: 0.5422 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7447 - val_loss: 0.5386 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7476 - val_loss: 0.5367 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5005 - accuracy: 0.7510 - val_loss: 0.5359 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4910 - accuracy: 0.7559
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7558 - val_loss: 0.5414 - val_accuracy: 0.7208 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4377055305420196
Confusion Matrix :
 [[3184 1139]
 [1293 3030]]
Accuracy on test set:    0.7187138561184363
Sensitivity:    0.7009021512838307 	 Specificity:    0.7365255609530419
Precision  : 0.7267929959222835
Area Under Curve:    0.7187138561184363
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6124 - accuracy: 0.6654 - val_loss: 0.5649 - val_accuracy: 0.7048 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5584 - accuracy: 0.7120 - val_loss: 0.5534 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7235 - val_loss: 0.5493 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5314 - accuracy: 0.7313 - val_loss: 0.5449 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5247 - accuracy: 0.7345 - val_loss: 0.5438 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5157 - accuracy: 0.7427 - val_loss: 0.5399 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7482 - val_loss: 0.5396 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7511 - val_loss: 0.5481 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4951 - accuracy: 0.7556 - val_loss: 0.5437 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4864 - accuracy: 0.7624 - val_loss: 0.5419 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4790 - accuracy: 0.7652 - val_loss: 0.5516 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4791 - accuracy: 0.7641 - val_loss: 0.5456 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4665 - accuracy: 0.7715 - val_loss: 0.5456 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4577 - accuracy: 0.7783
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4585 - accuracy: 0.7776 - val_loss: 0.5545 - val_accuracy: 0.7169 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4316439620729742
Confusion Matrix :
 [[2878 1445]
 [1021 3302]]
Accuracy on test set:    0.7147814018043026
Sensitivity:    0.7638214203099699 	 Specificity:    0.6657413832986352
Precision  : 0.6955972192963977
Area Under Curve:    0.7147814018043026
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6068 - accuracy: 0.6637 - val_loss: 0.5645 - val_accuracy: 0.7033 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7135 - val_loss: 0.5501 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7247 - val_loss: 0.5444 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7303 - val_loss: 0.5400 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7359 - val_loss: 0.5416 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5165 - accuracy: 0.7412 - val_loss: 0.5549 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7413 - val_loss: 0.5400 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7475 - val_loss: 0.5370 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7517 - val_loss: 0.5371 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7554 - val_loss: 0.5417 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4855 - accuracy: 0.7606 - val_loss: 0.5428 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4805 - accuracy: 0.7626 - val_loss: 0.5496 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4729 - accuracy: 0.7667 - val_loss: 0.5532 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4681 - accuracy: 0.7698
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7696 - val_loss: 0.5498 - val_accuracy: 0.7208 - lr: 0.0010
271/271 [==============================] - 0s 665us/step
Independent Testing Matthews Correlation:  0.4206192697749223
Confusion Matrix :
 [[2642 1681]
 [ 857 3466]]
Accuracy on test set:    0.7064538514920194
Sensitivity:    0.8017580383992597 	 Specificity:    0.611149664584779
Precision  : 0.6734019817369341
Area Under Curve:    0.7064538514920194
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6052 - accuracy: 0.6691 - val_loss: 0.5606 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7126 - val_loss: 0.5483 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7261 - val_loss: 0.5403 - val_accuracy: 0.7227 - lr: 0.0010

Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7294 - val_loss: 0.5402 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7365 - val_loss: 0.5365 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7423 - val_loss: 0.5355 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7466 - val_loss: 0.5369 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5022 - accuracy: 0.7485 - val_loss: 0.5442 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7522 - val_loss: 0.5363 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4884 - accuracy: 0.7594 - val_loss: 0.5383 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4827 - accuracy: 0.7632 - val_loss: 0.5464 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7635 - val_loss: 0.5472 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4699 - accuracy: 0.7705 - val_loss: 0.5459 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4640 - accuracy: 0.7739
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4643 - accuracy: 0.7736 - val_loss: 0.5471 - val_accuracy: 0.7253 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.43278786235195527
Confusion Matrix :
 [[2764 1559]
 [ 914 3409]]
Accuracy on test set:    0.713971778857275
Sensitivity:    0.7885727504048115 	 Specificity:    0.6393708073097386
Precision  : 0.6861916264090178
Area Under Curve:    0.713971778857275
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6079 - accuracy: 0.6652 - val_loss: 0.5607 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5571 - accuracy: 0.7119 - val_loss: 0.5563 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7241 - val_loss: 0.5415 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7332 - val_loss: 0.5358 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7364 - val_loss: 0.5352 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7408 - val_loss: 0.5337 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7462 - val_loss: 0.5376 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5003 - accuracy: 0.7510 - val_loss: 0.5358 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7559 - val_loss: 0.5410 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7595 - val_loss: 0.5414 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4802 - accuracy: 0.7637 - val_loss: 0.5389 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7671 - val_loss: 0.5433 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 13/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4691 - accuracy: 0.7699
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4697 - accuracy: 0.7694 - val_loss: 0.5493 - val_accuracy: 0.7209 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.4476481812264899
Confusion Matrix :
 [[2589 1734]
 [ 709 3614]]
Accuracy on test set:    0.7174415914873931
Sensitivity:    0.8359935230164238 	 Specificity:    0.5988896599583623
Precision  : 0.6757666417352282
Area Under Curve:    0.717441591487393
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6014 - accuracy: 0.6732 - val_loss: 0.5633 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7124 - val_loss: 0.5656 - val_accuracy: 0.7052 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7217 - val_loss: 0.5462 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7284 - val_loss: 0.5433 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7363 - val_loss: 0.5406 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7398 - val_loss: 0.5465 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7443 - val_loss: 0.5394 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7474 - val_loss: 0.5418 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7524 - val_loss: 0.5405 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7551 - val_loss: 0.5463 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4865 - accuracy: 0.7603 - val_loss: 0.5492 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7626 - val_loss: 0.5398 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4707 - accuracy: 0.7676 - val_loss: 0.5420 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4675 - accuracy: 0.7697 - val_loss: 0.5469 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4612 - accuracy: 0.7746 - val_loss: 0.5552 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4533 - accuracy: 0.7774 - val_loss: 0.5591 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4471 - accuracy: 0.7809 - val_loss: 0.5616 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 18/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4430 - accuracy: 0.7823
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4437 - accuracy: 0.7816 - val_loss: 0.5598 - val_accuracy: 0.7196 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.44742509401993896
Confusion Matrix :
 [[3024 1299]
 [1092 3231]]
Accuracy on test set:    0.7234559333795975
Sensitivity:    0.7473976405274115 	 Specificity:    0.6995142262317835
Precision  : 0.7132450331125828
Area Under Curve:    0.7234559333795975
(8646, 4352) (8646,)
Epoch 1/400

274/274 [==============================] - 1s 3ms/step - loss: 0.6024 - accuracy: 0.6705 - val_loss: 0.5685 - val_accuracy: 0.7030 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7131 - val_loss: 0.5554 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7226 - val_loss: 0.5417 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7287 - val_loss: 0.5432 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5247 - accuracy: 0.7360 - val_loss: 0.5380 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7411 - val_loss: 0.5343 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7428 - val_loss: 0.5332 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7498 - val_loss: 0.5497 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7516 - val_loss: 0.5379 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4936 - accuracy: 0.7559 - val_loss: 0.5353 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7571 - val_loss: 0.5359 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4788 - accuracy: 0.7635 - val_loss: 0.5445 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4744 - accuracy: 0.7650 - val_loss: 0.5412 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 14/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4668 - accuracy: 0.7697
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4672 - accuracy: 0.7695 - val_loss: 0.5435 - val_accuracy: 0.7238 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4704815518809348
Confusion Matrix :
 [[3114 1209]
 [1081 3242]]
Accuracy on test set:    0.7351376359009947
Sensitivity:    0.749942169789498 	 Specificity:    0.7203331020124913
Precision  : 0.7283756459222647
Area Under Curve:    0.7351376359009947
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6111 - accuracy: 0.6625 - val_loss: 0.5761 - val_accuracy: 0.7059 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5645 - accuracy: 0.7072 - val_loss: 0.5570 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7202 - val_loss: 0.5471 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7269 - val_loss: 0.5423 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7322 - val_loss: 0.5438 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7342 - val_loss: 0.5404 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7402 - val_loss: 0.5392 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7450 - val_loss: 0.5403 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7478 - val_loss: 0.5447 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4983 - accuracy: 0.7520 - val_loss: 0.5387 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7562 - val_loss: 0.5398 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4850 - accuracy: 0.7593 - val_loss: 0.5470 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7622 - val_loss: 0.5479 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7636 - val_loss: 0.5479 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4672 - accuracy: 0.7697 - val_loss: 0.5597 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4641 - accuracy: 0.7698
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4639 - accuracy: 0.7700 - val_loss: 0.5690 - val_accuracy: 0.7209 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4509811019002169
Confusion Matrix :
 [[3356  967]
 [1417 2906]]
Accuracy on test set:    0.724265556326625
Sensitivity:    0.6722183668748555 	 Specificity:    0.7763127457783946
Precision  : 0.7503227472243739
Area Under Curve:    0.7242655563266249
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6075 - accuracy: 0.6656 - val_loss: 0.5755 - val_accuracy: 0.6952 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5653 - accuracy: 0.7073 - val_loss: 0.5598 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5514 - accuracy: 0.7178 - val_loss: 0.5516 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7253 - val_loss: 0.5461 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7302 - val_loss: 0.5488 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7329 - val_loss: 0.5432 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5195 - accuracy: 0.7363 - val_loss: 0.5436 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5136 - accuracy: 0.7407 - val_loss: 0.5416 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5120 - accuracy: 0.7425
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7426 - val_loss: 0.5507 - val_accuracy: 0.7246 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.5091913076656704
Confusion Matrix :
 [[3126 1197]
 [ 929 3394]]
Accuracy on test set:    0.7541059449456397
Sensitivity:    0.7851029377746935 	 Specificity:    0.7231089521165857
Precision  : 0.7392724896536702
Area Under Curve:    0.7541059449456397
(8646, 4352) (8646,)
Mean MCC = 0.4479 + 0.0243 and Mean AUC = 0.7218 + 0.0132
Mean Sensitivity = 0.7664 + 0.0484 and Mean Specificity = 0.6773 + 0.0596 and Mean Accuracy = 0.7218 + 0.0132
Mean Precision = 0.7062 + 0.0276





Seed   : 642632
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6024 - accuracy: 0.6685 - val_loss: 0.5590 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5549 - accuracy: 0.7122 - val_loss: 0.5511 - val_accuracy: 0.7119 - lr: 0.0010

Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7271 - val_loss: 0.5407 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7317 - val_loss: 0.5413 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5213 - accuracy: 0.7370 - val_loss: 0.5370 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7404 - val_loss: 0.5317 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7437 - val_loss: 0.5332 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7513 - val_loss: 0.5337 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7564 - val_loss: 0.5374 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7576 - val_loss: 0.5320 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4836 - accuracy: 0.7597 - val_loss: 0.5356 - val_accuracy: 0.7341 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7653 - val_loss: 0.5404 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7686 - val_loss: 0.5420 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4653 - accuracy: 0.7716 - val_loss: 0.5362 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4592 - accuracy: 0.7751 - val_loss: 0.5411 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4551 - accuracy: 0.7766
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4557 - accuracy: 0.7761 - val_loss: 0.5376 - val_accuracy: 0.7294 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.408123940968311
Confusion Matrix :
 [[2715 1608]
 [ 970 3353]]
Accuracy on test set:    0.7018274346518621
Sensitivity:    0.775618783252371 	 Specificity:    0.6280360860513532
Precision  : 0.6758718000403144
Area Under Curve:    0.7018274346518621
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6009 - accuracy: 0.6702 - val_loss: 0.5615 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5590 - accuracy: 0.7113 - val_loss: 0.5550 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7255 - val_loss: 0.5445 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7291 - val_loss: 0.5427 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7333 - val_loss: 0.5462 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5187 - accuracy: 0.7375 - val_loss: 0.5380 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7420 - val_loss: 0.5407 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7477 - val_loss: 0.5342 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7506 - val_loss: 0.5352 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7538 - val_loss: 0.5334 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7570 - val_loss: 0.5370 - val_accuracy: 0.7337 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7596 - val_loss: 0.5373 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7646 - val_loss: 0.5389 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4693 - accuracy: 0.7673 - val_loss: 0.5356 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4657 - accuracy: 0.7691 - val_loss: 0.5456 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4587 - accuracy: 0.7736
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4581 - accuracy: 0.7741 - val_loss: 0.5497 - val_accuracy: 0.7312 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.44113002593922673
Confusion Matrix :
 [[3120 1203]
 [1213 3110]]
Accuracy on test set:    0.7205644228544992
Sensitivity:    0.7194078186444599 	 Specificity:    0.7217210270645386
Precision  : 0.7210758172965454
Area Under Curve:    0.7205644228544992
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6170 - accuracy: 0.6549 - val_loss: 0.5744 - val_accuracy: 0.6949 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5676 - accuracy: 0.7053 - val_loss: 0.5515 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5506 - accuracy: 0.7187 - val_loss: 0.5450 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7261 - val_loss: 0.5440 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7326 - val_loss: 0.5496 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7377 - val_loss: 0.5404 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7401 - val_loss: 0.5415 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7447 - val_loss: 0.5363 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7489 - val_loss: 0.5387 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7525 - val_loss: 0.5412 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7548 - val_loss: 0.5433 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7615 - val_loss: 0.5472 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7611 - val_loss: 0.5508 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4743 - accuracy: 0.7690
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4742 - accuracy: 0.7684 - val_loss: 0.5595 - val_accuracy: 0.7164 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.44240620982663625

Confusion Matrix :
 [[3168 1155]
 [1256 3067]]
Accuracy on test set:    0.7211427249595188
Sensitivity:    0.7094610224381217 	 Specificity:    0.732824427480916
Precision  : 0.726432970156324
Area Under Curve:    0.7211427249595188
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6103 - accuracy: 0.6621 - val_loss: 0.5564 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5565 - accuracy: 0.7138 - val_loss: 0.5493 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7237 - val_loss: 0.5390 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7308 - val_loss: 0.5384 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5214 - accuracy: 0.7373 - val_loss: 0.5374 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7418 - val_loss: 0.5392 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7460 - val_loss: 0.5424 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7499 - val_loss: 0.5370 - val_accuracy: 0.7328 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4947 - accuracy: 0.7551 - val_loss: 0.5395 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4884 - accuracy: 0.7587 - val_loss: 0.5356 - val_accuracy: 0.7334 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7595 - val_loss: 0.5406 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4760 - accuracy: 0.7672 - val_loss: 0.5665 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7692 - val_loss: 0.5443 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4607 - accuracy: 0.7744 - val_loss: 0.5536 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4552 - accuracy: 0.7793
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4556 - accuracy: 0.7792 - val_loss: 0.5420 - val_accuracy: 0.7283 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4348080237274679
Confusion Matrix :
 [[2916 1407]
 [1043 3280]]
Accuracy on test set:    0.7166319685403655
Sensitivity:    0.758732361785797 	 Specificity:    0.6745315752949341
Precision  : 0.6998079795178153
Area Under Curve:    0.7166319685403656
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6059 - accuracy: 0.6677 - val_loss: 0.5547 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7144 - val_loss: 0.5409 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7238 - val_loss: 0.5383 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7290 - val_loss: 0.5345 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7353 - val_loss: 0.5314 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7405 - val_loss: 0.5317 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5120 - accuracy: 0.7433 - val_loss: 0.5288 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7486 - val_loss: 0.5341 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7508 - val_loss: 0.5309 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4925 - accuracy: 0.7537
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7534 - val_loss: 0.5338 - val_accuracy: 0.7286 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.44705515177357946
Confusion Matrix :
 [[3014 1309]
 [1084 3239]]
Accuracy on test set:    0.7232246125375896
Sensitivity:    0.7492482072634744 	 Specificity:    0.6972010178117048
Precision  : 0.7121811785400176
Area Under Curve:    0.7232246125375896
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6021 - accuracy: 0.6714 - val_loss: 0.5570 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5558 - accuracy: 0.7148 - val_loss: 0.5425 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7237 - val_loss: 0.5382 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5301 - accuracy: 0.7314 - val_loss: 0.5369 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5234 - accuracy: 0.7346 - val_loss: 0.5329 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7415 - val_loss: 0.5296 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7432 - val_loss: 0.5298 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7491 - val_loss: 0.5309 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4970 - accuracy: 0.7531 - val_loss: 0.5309 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4902 - accuracy: 0.7566 - val_loss: 0.5302 - val_accuracy: 0.7327 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4837 - accuracy: 0.7612 - val_loss: 0.5342 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4757 - accuracy: 0.7648 - val_loss: 0.5348 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4713 - accuracy: 0.7685 - val_loss: 0.5324 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4659 - accuracy: 0.7707 - val_loss: 0.5369 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4589 - accuracy: 0.7751
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4583 - accuracy: 0.7759 - val_loss: 0.5509 - val_accuracy: 0.7312 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4369559267113187
Confusion Matrix :
 [[2827 1496]
 [ 953 3370]]
Accuracy on test set:    0.7167476289613695
Sensitivity:    0.7795512375665048 	 Specificity:    0.6539440203562341
Precision  : 0.6925606247431155
Area Under Curve:    0.7167476289613695
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6140 - accuracy: 0.6598 - val_loss: 0.5773 - val_accuracy: 0.6892 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5627 - accuracy: 0.7099 - val_loss: 0.5473 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7223 - val_loss: 0.5416 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7267 - val_loss: 0.5374 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5286 - accuracy: 0.7315 - val_loss: 0.5344 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7393 - val_loss: 0.5318 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7423 - val_loss: 0.5350 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7480 - val_loss: 0.5381 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7519 - val_loss: 0.5361 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7580 - val_loss: 0.5354 - val_accuracy: 0.7355 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4850 - accuracy: 0.7588 - val_loss: 0.5362 - val_accuracy: 0.7334 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4777 - accuracy: 0.7660 - val_loss: 0.5403 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4720 - accuracy: 0.7676 - val_loss: 0.5398 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4653 - accuracy: 0.7722 - val_loss: 0.5382 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4615 - accuracy: 0.7740
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4620 - accuracy: 0.7738 - val_loss: 0.5458 - val_accuracy: 0.7242 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4507059155577516
Confusion Matrix :
 [[2790 1533]
 [ 865 3458]]
Accuracy on test set:    0.72264631043257
Sensitivity:    0.7999074716631969 	 Specificity:    0.6453851492019431
Precision  : 0.6928471248246845
Area Under Curve:    0.72264631043257
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6007 - accuracy: 0.6749 - val_loss: 0.5630 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5583 - accuracy: 0.7110 - val_loss: 0.5444 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7231 - val_loss: 0.5379 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7274 - val_loss: 0.5383 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5268 - accuracy: 0.7348 - val_loss: 0.5342 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5187 - accuracy: 0.7403 - val_loss: 0.5410 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7414 - val_loss: 0.5352 - val_accuracy: 0.7344 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7468 - val_loss: 0.5330 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7491 - val_loss: 0.5332 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4959 - accuracy: 0.7537 - val_loss: 0.5380 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7556 - val_loss: 0.5317 - val_accuracy: 0.7339 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4849 - accuracy: 0.7585
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7592 - val_loss: 0.5351 - val_accuracy: 0.7313 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.46443687101216324
Confusion Matrix :
 [[3255 1068]
 [1249 3074]]
Accuracy on test set:    0.7320148045338885
Sensitivity:    0.7110802683321767 	 Specificity:    0.7529493407356003
Precision  : 0.7421535490101401
Area Under Curve:    0.7320148045338886
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6081 - accuracy: 0.6670 - val_loss: 0.5598 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5633 - accuracy: 0.7084 - val_loss: 0.5446 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5498 - accuracy: 0.7182 - val_loss: 0.5467 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7240 - val_loss: 0.5383 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5300 - accuracy: 0.7323 - val_loss: 0.5440 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5225 - accuracy: 0.7377 - val_loss: 0.5355 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5159 - accuracy: 0.7409 - val_loss: 0.5299 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7449 - val_loss: 0.5321 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7477 - val_loss: 0.5295 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7511 - val_loss: 0.5300 - val_accuracy: 0.7359 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7556 - val_loss: 0.5314 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7612 - val_loss: 0.5392 - val_accuracy: 0.7328 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4745 - accuracy: 0.7661 - val_loss: 0.5428 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7668 - val_loss: 0.5357 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4618 - accuracy: 0.7722
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4620 - accuracy: 0.7722 - val_loss: 0.5482 - val_accuracy: 0.7290 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.475072750753887
Confusion Matrix :
 [[3130 1193]
 [1077 3246]]
Accuracy on test set:    0.7374508443210733
Sensitivity:    0.7508674531575295 	 Specificity:    0.7240342354846172
Precision  : 0.7312457760756927
Area Under Curve:    0.7374508443210733
(8646, 4352) (8646,)
Epoch 1/400

274/274 [==============================] - 1s 3ms/step - loss: 0.6227 - accuracy: 0.6506 - val_loss: 0.5653 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5673 - accuracy: 0.7055 - val_loss: 0.5539 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5507 - accuracy: 0.7187 - val_loss: 0.5459 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7253 - val_loss: 0.5410 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7307 - val_loss: 0.5357 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7376 - val_loss: 0.5380 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7397 - val_loss: 0.5379 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5149 - accuracy: 0.7434 - val_loss: 0.5350 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7452 - val_loss: 0.5350 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7500 - val_loss: 0.5396 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7553 - val_loss: 0.5398 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7581 - val_loss: 0.5412 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7613 - val_loss: 0.5434 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4796 - accuracy: 0.7624
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4812 - accuracy: 0.7615 - val_loss: 0.5454 - val_accuracy: 0.7281 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.5045116202944453
Confusion Matrix :
 [[3248 1075]
 [1067 3256]]
Accuracy on test set:    0.7522553782095767
Sensitivity:    0.7531806615776081 	 Specificity:    0.7513300948415452
Precision  : 0.7517894250750404
Area Under Curve:    0.7522553782095767
(8646, 4352) (8646,)
Mean MCC = 0.4505 + 0.0247 and Mean AUC = 0.7245 + 0.0129
Mean Sensitivity = 0.7507 + 0.0286 and Mean Specificity = 0.6982 + 0.0430 and Mean Accuracy = 0.7245 + 0.0129
Mean Precision = 0.7146 + 0.0230





Seed   : 988435
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.5998 - accuracy: 0.6769 - val_loss: 0.5656 - val_accuracy: 0.7005 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5558 - accuracy: 0.7146 - val_loss: 0.5515 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7251 - val_loss: 0.5469 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5294 - accuracy: 0.7322 - val_loss: 0.5476 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5213 - accuracy: 0.7389 - val_loss: 0.5411 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7432 - val_loss: 0.5397 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5065 - accuracy: 0.7457 - val_loss: 0.5387 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7508 - val_loss: 0.5370 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7549 - val_loss: 0.5363 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4877 - accuracy: 0.7578 - val_loss: 0.5415 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4794 - accuracy: 0.7623 - val_loss: 0.5485 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7652 - val_loss: 0.5542 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4692 - accuracy: 0.7683
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4693 - accuracy: 0.7684 - val_loss: 0.5485 - val_accuracy: 0.7158 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4326937945663453
Confusion Matrix :
 [[2983 1340]
 [1115 3208]]
Accuracy on test set:    0.7160536664353458
Sensitivity:    0.7420772611612306 	 Specificity:    0.6900300717094611
Precision  : 0.7053649956024626
Area Under Curve:    0.7160536664353457
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5984 - accuracy: 0.6762 - val_loss: 0.5590 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5529 - accuracy: 0.7153 - val_loss: 0.5561 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7265 - val_loss: 0.5455 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5277 - accuracy: 0.7341 - val_loss: 0.5455 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7399 - val_loss: 0.5408 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7429 - val_loss: 0.5386 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5056 - accuracy: 0.7475 - val_loss: 0.5546 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7525 - val_loss: 0.5412 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7576 - val_loss: 0.5423 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4834 - accuracy: 0.7610 - val_loss: 0.5453 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4774 - accuracy: 0.7648 - val_loss: 0.5462 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4704 - accuracy: 0.7695 - val_loss: 0.5398 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4655 - accuracy: 0.7709 - val_loss: 0.5561 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4585 - accuracy: 0.7760 - val_loss: 0.5502 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4503 - accuracy: 0.7824
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4511 - accuracy: 0.7818 - val_loss: 0.5533 - val_accuracy: 0.7165 - lr: 0.0010
271/271 [==============================] - 0s 636us/step
Independent Testing Matthews Correlation:  0.42030047318117464
Confusion Matrix :
 [[3291 1032]
 [1484 2839]]
Accuracy on test set:    0.7089983807541059

Sensitivity:    0.6567198704603284 	 Specificity:    0.7612768910478834
Precision  : 0.7334022216481529
Area Under Curve:    0.7089983807541059
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6050 - accuracy: 0.6679 - val_loss: 0.5648 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7117 - val_loss: 0.5527 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7228 - val_loss: 0.5495 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7282 - val_loss: 0.5477 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5264 - accuracy: 0.7327 - val_loss: 0.5433 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5196 - accuracy: 0.7385 - val_loss: 0.5451 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5149 - accuracy: 0.7412 - val_loss: 0.5496 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7444 - val_loss: 0.5387 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7475 - val_loss: 0.5407 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4973 - accuracy: 0.7500 - val_loss: 0.5461 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7549 - val_loss: 0.5469 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4860 - accuracy: 0.7578 - val_loss: 0.5468 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7588 - val_loss: 0.5516 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4782 - accuracy: 0.7618 - val_loss: 0.5480 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7660 - val_loss: 0.5555 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4641 - accuracy: 0.7688 - val_loss: 0.5696 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4595 - accuracy: 0.7728 - val_loss: 0.5652 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 18/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4536 - accuracy: 0.7740
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4538 - accuracy: 0.7736 - val_loss: 0.5666 - val_accuracy: 0.7181 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4422046519782666
Confusion Matrix :
 [[2759 1564]
 [ 872 3451]]
Accuracy on test set:    0.7182512144344205
Sensitivity:    0.7982882257691418 	 Specificity:    0.6382142030996992
Precision  : 0.688135593220339
Area Under Curve:    0.7182512144344206
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6047 - accuracy: 0.6653 - val_loss: 0.5642 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5598 - accuracy: 0.7105 - val_loss: 0.5563 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7210 - val_loss: 0.5465 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7280 - val_loss: 0.5440 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7342 - val_loss: 0.5389 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7386 - val_loss: 0.5376 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7425 - val_loss: 0.5420 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7460 - val_loss: 0.5398 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7500 - val_loss: 0.5430 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7512 - val_loss: 0.5448 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7553 - val_loss: 0.5465 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4834 - accuracy: 0.7605 - val_loss: 0.5541 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4789 - accuracy: 0.7641 - val_loss: 0.5463 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 14/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4735 - accuracy: 0.7666
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4732 - accuracy: 0.7671 - val_loss: 0.5610 - val_accuracy: 0.7192 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.43022309199620795
Confusion Matrix :
 [[2994 1329]
 [1136 3187]]
Accuracy on test set:    0.7148970622253065
Sensitivity:    0.7372195234790655 	 Specificity:    0.6925746009715475
Precision  : 0.7057130203720107
Area Under Curve:    0.7148970622253065
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5991 - accuracy: 0.6730 - val_loss: 0.5646 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7134 - val_loss: 0.5543 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7244 - val_loss: 0.5497 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5314 - accuracy: 0.7312 - val_loss: 0.5466 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7349 - val_loss: 0.5437 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7414 - val_loss: 0.5469 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7444 - val_loss: 0.5410 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5017 - accuracy: 0.7485 - val_loss: 0.5439 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4959 - accuracy: 0.7541 - val_loss: 0.5461 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7564 - val_loss: 0.5449 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4836 - accuracy: 0.7614 - val_loss: 0.5464 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7654 - val_loss: 0.5451 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4732 - accuracy: 0.7663 - val_loss: 0.5528 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4638 - accuracy: 0.7726 - val_loss: 0.5520 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4591 - accuracy: 0.7738 - val_loss: 0.5519 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4539 - accuracy: 0.7776 - val_loss: 0.5600 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4484 - accuracy: 0.7794
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4488 - accuracy: 0.7788 - val_loss: 0.5594 - val_accuracy: 0.7173 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4381570709962698
Confusion Matrix :
 [[2880 1443]
 [ 996 3327]]
Accuracy on test set:    0.7179042331714087
Sensitivity:    0.7696044413601666 	 Specificity:    0.666204024982651
Precision  : 0.6974842767295597
Area Under Curve:    0.7179042331714087
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6138 - accuracy: 0.6645 - val_loss: 0.5653 - val_accuracy: 0.7092 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7104 - val_loss: 0.5598 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7234 - val_loss: 0.5468 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7295 - val_loss: 0.5451 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7353 - val_loss: 0.5420 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5187 - accuracy: 0.7390 - val_loss: 0.5411 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7415 - val_loss: 0.5417 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7474 - val_loss: 0.5418 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5003 - accuracy: 0.7515 - val_loss: 0.5395 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7540 - val_loss: 0.5478 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7585 - val_loss: 0.5443 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7607 - val_loss: 0.5490 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4747 - accuracy: 0.7657 - val_loss: 0.5461 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4718 - accuracy: 0.7672 - val_loss: 0.5504 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4685 - accuracy: 0.7668 - val_loss: 0.5619 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 16/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4565 - accuracy: 0.7758
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4578 - accuracy: 0.7751 - val_loss: 0.5577 - val_accuracy: 0.7176 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4323216500058286
Confusion Matrix :
 [[2921 1402]
 [1058 3265]]
Accuracy on test set:    0.7154753643303262
Sensitivity:    0.7552625491556789 	 Specificity:    0.6756881795049734
Precision  : 0.6995928862224127
Area Under Curve:    0.7154753643303262
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6025 - accuracy: 0.6687 - val_loss: 0.5678 - val_accuracy: 0.7001 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7117 - val_loss: 0.5563 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7215 - val_loss: 0.5540 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7283 - val_loss: 0.5485 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5280 - accuracy: 0.7347 - val_loss: 0.5496 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5207 - accuracy: 0.7382 - val_loss: 0.5515 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7428 - val_loss: 0.5454 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7465 - val_loss: 0.5454 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7487 - val_loss: 0.5443 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7520 - val_loss: 0.5432 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 11/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4937 - accuracy: 0.7542
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7543 - val_loss: 0.5555 - val_accuracy: 0.7118 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.46000301257419596
Confusion Matrix :
 [[3315 1008]
 [1332 2991]]
Accuracy on test set:    0.7293546148507981
Sensitivity:    0.6918806384455239 	 Specificity:    0.7668285912560722
Precision  : 0.7479369842460615
Area Under Curve:    0.729354614850798
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6064 - accuracy: 0.6660 - val_loss: 0.5713 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7115 - val_loss: 0.5558 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7206 - val_loss: 0.5469 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7274 - val_loss: 0.5454 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5281 - accuracy: 0.7334 - val_loss: 0.5447 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5211 - accuracy: 0.7373 - val_loss: 0.5406 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7408 - val_loss: 0.5428 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7442 - val_loss: 0.5407 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7474 - val_loss: 0.5472 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7505 - val_loss: 0.5423 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7547 - val_loss: 0.5457 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7591 - val_loss: 0.5488 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4799 - accuracy: 0.7606
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4796 - accuracy: 0.7610 - val_loss: 0.5530 - val_accuracy: 0.7132 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.44929393960457675
Confusion Matrix :
 [[3211 1112]
 [1270 3053]]
Accuracy on test set:    0.7244968771686329
Sensitivity:    0.7062225306500116 	 Specificity:    0.7427712236872542
Precision  : 0.7330132052821129
Area Under Curve:    0.724496877168633
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6159 - accuracy: 0.6571 - val_loss: 0.5749 - val_accuracy: 0.6960 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5649 - accuracy: 0.7072 - val_loss: 0.5639 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7197 - val_loss: 0.5631 - val_accuracy: 0.7038 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7247 - val_loss: 0.5476 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7307 - val_loss: 0.5457 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5220 - accuracy: 0.7355 - val_loss: 0.5478 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7390 - val_loss: 0.5536 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7431 - val_loss: 0.5406 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7460 - val_loss: 0.5466 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7518 - val_loss: 0.5491 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7518 - val_loss: 0.5560 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4869 - accuracy: 0.7587 - val_loss: 0.5448 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4798 - accuracy: 0.7608
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7605 - val_loss: 0.5482 - val_accuracy: 0.7209 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.47069331607979925
Confusion Matrix :
 [[3064 1259]
 [1032 3291]]
Accuracy on test set:    0.7350219754799907
Sensitivity:    0.7612768910478834 	 Specificity:    0.7087670599120981
Precision  : 0.7232967032967033
Area Under Curve:    0.7350219754799908
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6156 - accuracy: 0.6612 - val_loss: 0.5721 - val_accuracy: 0.7014 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5649 - accuracy: 0.7079 - val_loss: 0.5604 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5493 - accuracy: 0.7176 - val_loss: 0.5555 - val_accuracy: 0.7107 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7267 - val_loss: 0.5471 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5301 - accuracy: 0.7318 - val_loss: 0.5530 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7361 - val_loss: 0.5449 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7405 - val_loss: 0.5532 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7433 - val_loss: 0.5510 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5057 - accuracy: 0.7467
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5056 - accuracy: 0.7468 - val_loss: 0.5484 - val_accuracy: 0.7172 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.4929922000356088
Confusion Matrix :
 [[3197 1126]
 [1066 3257]]
Accuracy on test set:    0.7464723571593801
Sensitivity:    0.753411982419616 	 Specificity:    0.7395327318991441
Precision  : 0.7430983344741044
Area Under Curve:    0.7464723571593801
(8646, 4352) (8646,)
Mean MCC = 0.4469 + 0.0209 and Mean AUC = 0.7227 + 0.0107
Mean Sensitivity = 0.7372 + 0.0393 and Mean Specificity = 0.7082 + 0.0409 and Mean Accuracy = 0.7227 + 0.0107
Mean Precision = 0.7177 + 0.0199





Seed   : 122577
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6210 - accuracy: 0.6584 - val_loss: 0.5681 - val_accuracy: 0.6978 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7120 - val_loss: 0.5544 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7230 - val_loss: 0.5486 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7287 - val_loss: 0.5415 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7361 - val_loss: 0.5382 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7422 - val_loss: 0.5366 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7457 - val_loss: 0.5335 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7500 - val_loss: 0.5379 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7552 - val_loss: 0.5359 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4866 - accuracy: 0.7586 - val_loss: 0.5335 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4791 - accuracy: 0.7631 - val_loss: 0.5384 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4721 - accuracy: 0.7674 - val_loss: 0.5390 - val_accuracy: 0.7327 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4661 - accuracy: 0.7728 - val_loss: 0.5465 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4617 - accuracy: 0.7734 - val_loss: 0.5408 - val_accuracy: 0.7327 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4541 - accuracy: 0.7758 - val_loss: 0.5495 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4473 - accuracy: 0.7811 - val_loss: 0.5524 - val_accuracy: 0.7269 - lr: 0.0010

Epoch 17/400
252/274 [==========================>...] - ETA: 0s - loss: 0.4403 - accuracy: 0.7846
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4407 - accuracy: 0.7840 - val_loss: 0.5507 - val_accuracy: 0.7262 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4074443107407575
Confusion Matrix :
 [[2997 1326]
 [1236 3087]]
Accuracy on test set:    0.703678001387925
Sensitivity:    0.714087439278279 	 Specificity:    0.6932685634975712
Precision  : 0.699524133242692
Area Under Curve:    0.703678001387925
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6066 - accuracy: 0.6652 - val_loss: 0.5632 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5574 - accuracy: 0.7108 - val_loss: 0.5545 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7232 - val_loss: 0.5462 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7299 - val_loss: 0.5450 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7357 - val_loss: 0.5479 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5177 - accuracy: 0.7391 - val_loss: 0.5457 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7427 - val_loss: 0.5392 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7485 - val_loss: 0.5393 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7504 - val_loss: 0.5417 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7565 - val_loss: 0.5529 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7607 - val_loss: 0.5441 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7627 - val_loss: 0.5441 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4755 - accuracy: 0.7661 - val_loss: 0.5477 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 14/400
256/274 [===========================>..] - ETA: 0s - loss: 0.4673 - accuracy: 0.7704
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7702 - val_loss: 0.5475 - val_accuracy: 0.7194 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.4379601278017858
Confusion Matrix :
 [[2856 1467]
 [ 975 3348]]
Accuracy on test set:    0.7175572519083969
Sensitivity:    0.7744621790423317 	 Specificity:    0.6606523247744622
Precision  : 0.6953271028037383
Area Under Curve:    0.717557251908397
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6054 - accuracy: 0.6665 - val_loss: 0.5557 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5578 - accuracy: 0.7105 - val_loss: 0.5452 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7239 - val_loss: 0.5455 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7291 - val_loss: 0.5393 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7334 - val_loss: 0.5395 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5189 - accuracy: 0.7378 - val_loss: 0.5380 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5116 - accuracy: 0.7435 - val_loss: 0.5394 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7468 - val_loss: 0.5354 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7509 - val_loss: 0.5378 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7549 - val_loss: 0.5411 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4873 - accuracy: 0.7588 - val_loss: 0.5514 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7617 - val_loss: 0.5492 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4771 - accuracy: 0.7644
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4769 - accuracy: 0.7646 - val_loss: 0.5511 - val_accuracy: 0.7185 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.43222056534291864
Confusion Matrix :
 [[3339  984]
 [1483 2840]]
Accuracy on test set:    0.7146657413832986
Sensitivity:    0.6569511913023364 	 Specificity:    0.7723802914642609
Precision  : 0.7426778242677824
Area Under Curve:    0.7146657413832986
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6047 - accuracy: 0.6668 - val_loss: 0.5667 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7137 - val_loss: 0.5579 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7241 - val_loss: 0.5478 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7296 - val_loss: 0.5443 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7358 - val_loss: 0.5407 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5150 - accuracy: 0.7409 - val_loss: 0.5429 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7463 - val_loss: 0.5384 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7478 - val_loss: 0.5381 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7532 - val_loss: 0.5396 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7561 - val_loss: 0.5367 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4869 - accuracy: 0.7579 - val_loss: 0.5461 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7602 - val_loss: 0.5454 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4726 - accuracy: 0.7662
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4729 - accuracy: 0.7662 - val_loss: 0.5414 - val_accuracy: 0.7326 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4359983942814644
Confusion Matrix :
 [[2947 1376]
 [1067 3256]]
Accuracy on test set:    0.7174415914873931
Sensitivity:    0.7531806615776081 	 Specificity:    0.6817025213971779
Precision  : 0.7029360967184801
Area Under Curve:    0.7174415914873931
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6094 - accuracy: 0.6659 - val_loss: 0.5636 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5578 - accuracy: 0.7115 - val_loss: 0.5440 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7236 - val_loss: 0.5416 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5288 - accuracy: 0.7307 - val_loss: 0.5369 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5204 - accuracy: 0.7376 - val_loss: 0.5349 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5141 - accuracy: 0.7405 - val_loss: 0.5357 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5054 - accuracy: 0.7478 - val_loss: 0.5337 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4983 - accuracy: 0.7533 - val_loss: 0.5495 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7556 - val_loss: 0.5349 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4839 - accuracy: 0.7602 - val_loss: 0.5421 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4781 - accuracy: 0.7639 - val_loss: 0.5447 - val_accuracy: 0.7339 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4725 - accuracy: 0.7680 - val_loss: 0.5435 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4665 - accuracy: 0.7717 - val_loss: 0.5446 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4566 - accuracy: 0.7768 - val_loss: 0.5506 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4502 - accuracy: 0.7783 - val_loss: 0.5550 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4423 - accuracy: 0.7859
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4431 - accuracy: 0.7850 - val_loss: 0.5544 - val_accuracy: 0.7258 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.434825051110504
Confusion Matrix :
 [[3162 1161]
 [1283 3040]]
Accuracy on test set:    0.7173259310663891
Sensitivity:    0.7032153597039094 	 Specificity:    0.7314365024288688
Precision  : 0.7236372292311355
Area Under Curve:    0.7173259310663891
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6168 - accuracy: 0.6541 - val_loss: 0.5664 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5635 - accuracy: 0.7062 - val_loss: 0.5480 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5489 - accuracy: 0.7202 - val_loss: 0.5425 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7255 - val_loss: 0.5394 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7342 - val_loss: 0.5380 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7377 - val_loss: 0.5371 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7388 - val_loss: 0.5378 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7421 - val_loss: 0.5390 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5032 - accuracy: 0.7497 - val_loss: 0.5399 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7544 - val_loss: 0.5353 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7586 - val_loss: 0.5426 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4847 - accuracy: 0.7625 - val_loss: 0.5380 - val_accuracy: 0.7340 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4789 - accuracy: 0.7657 - val_loss: 0.5457 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4709 - accuracy: 0.7702 - val_loss: 0.5446 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7707 - val_loss: 0.5495 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4595 - accuracy: 0.7755 - val_loss: 0.5564 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4513 - accuracy: 0.7827
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4518 - accuracy: 0.7823 - val_loss: 0.5522 - val_accuracy: 0.7226 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.43660565649540867
Confusion Matrix :
 [[3058 1265]
 [1171 3152]]
Accuracy on test set:    0.7182512144344205
Sensitivity:    0.7291232940087902 	 Specificity:    0.7073791348600509
Precision  : 0.7136065202626217
Area Under Curve:    0.7182512144344205
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6101 - accuracy: 0.6661 - val_loss: 0.5631 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5588 - accuracy: 0.7129 - val_loss: 0.5617 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7257 - val_loss: 0.5462 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7294 - val_loss: 0.5440 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7359 - val_loss: 0.5443 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7386 - val_loss: 0.5394 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7435 - val_loss: 0.5411 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7488 - val_loss: 0.5395 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7515 - val_loss: 0.5460 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7575 - val_loss: 0.5422 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 11/400

253/274 [==========================>...] - ETA: 0s - loss: 0.4863 - accuracy: 0.7598
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7597 - val_loss: 0.5450 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.45525938375257025
Confusion Matrix :
 [[3045 1278]
 [1079 3244]]
Accuracy on test set:    0.7273883876937312
Sensitivity:    0.7504048114735138 	 Specificity:    0.7043719639139486
Precision  : 0.7173816895179125
Area Under Curve:    0.7273883876937313
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6015 - accuracy: 0.6701 - val_loss: 0.5633 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5572 - accuracy: 0.7130 - val_loss: 0.5508 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7236 - val_loss: 0.5425 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7279 - val_loss: 0.5409 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7356 - val_loss: 0.5452 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7403 - val_loss: 0.5386 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5119 - accuracy: 0.7441 - val_loss: 0.5448 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5042 - accuracy: 0.7495 - val_loss: 0.5400 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4984 - accuracy: 0.7525
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4987 - accuracy: 0.7521 - val_loss: 0.5395 - val_accuracy: 0.7289 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.4673242306592082
Confusion Matrix :
 [[3205 1118]
 [1185 3138]]
Accuracy on test set:    0.7336340504279436
Sensitivity:    0.7258848022206801 	 Specificity:    0.741383298635207
Precision  : 0.737312030075188
Area Under Curve:    0.7336340504279435
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6199 - accuracy: 0.6603 - val_loss: 0.5665 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5617 - accuracy: 0.7091 - val_loss: 0.5526 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7190 - val_loss: 0.5483 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7282 - val_loss: 0.5498 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5278 - accuracy: 0.7331 - val_loss: 0.5455 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5197 - accuracy: 0.7373 - val_loss: 0.5542 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5112 - accuracy: 0.7440 - val_loss: 0.5458 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5056 - accuracy: 0.7458 - val_loss: 0.5414 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7504 - val_loss: 0.5444 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7545 - val_loss: 0.5400 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7574 - val_loss: 0.5524 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4769 - accuracy: 0.7645
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4778 - accuracy: 0.7637 - val_loss: 0.5506 - val_accuracy: 0.7272 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.46592656301825325
Confusion Matrix :
 [[3138 1185]
 [1124 3199]]
Accuracy on test set:    0.73294008790192
Sensitivity:    0.7399953735831598 	 Specificity:    0.7258848022206801
Precision  : 0.7296989051094891
Area Under Curve:    0.73294008790192
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6148 - accuracy: 0.6580 - val_loss: 0.5797 - val_accuracy: 0.6981 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5659 - accuracy: 0.7064 - val_loss: 0.5566 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5510 - accuracy: 0.7161 - val_loss: 0.5537 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7245 - val_loss: 0.5568 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7271 - val_loss: 0.5459 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7312 - val_loss: 0.5481 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5207 - accuracy: 0.7363 - val_loss: 0.5483 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7399 - val_loss: 0.5449 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7442 - val_loss: 0.5450 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5056 - accuracy: 0.7486 - val_loss: 0.5480 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7514 - val_loss: 0.5589 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4933 - accuracy: 0.7530 - val_loss: 0.5513 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4889 - accuracy: 0.7589
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4890 - accuracy: 0.7584 - val_loss: 0.5541 - val_accuracy: 0.7209 - lr: 0.0010
271/271 [==============================] - 1s 643us/step
Independent Testing Matthews Correlation:  0.49476171019284004
Confusion Matrix :
 [[3320 1003]
 [1183 3140]]
Accuracy on test set:    0.7471663196854037
Sensitivity:    0.7263474439046959 	 Specificity:    0.7679851954661115
Precision  : 0.7579048998310403
Area Under Curve:    0.7471663196854036
(8646, 4352) (8646,)
Mean MCC = 0.4468 + 0.0232 and Mean AUC = 0.7230 + 0.0117
Mean Sensitivity = 0.7274 + 0.0305 and Mean Specificity = 0.7186 + 0.0343 and Mean Accuracy = 0.7230 + 0.0117
Mean Precision = 0.7220 + 0.0192





Seed   : 689115
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6095 - accuracy: 0.6636 - val_loss: 0.5610 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5590 - accuracy: 0.7124 - val_loss: 0.5516 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7246 - val_loss: 0.5429 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7301 - val_loss: 0.5457 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7370 - val_loss: 0.5363 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7418 - val_loss: 0.5338 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7448 - val_loss: 0.5317 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7478 - val_loss: 0.5335 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7501 - val_loss: 0.5322 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4918 - accuracy: 0.7556
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4918 - accuracy: 0.7560 - val_loss: 0.5397 - val_accuracy: 0.7219 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.40973545522067656
Confusion Matrix :
 [[2663 1660]
 [ 918 3405]]
Accuracy on test set:    0.7018274346518621
Sensitivity:    0.78764746703678 	 Specificity:    0.6160074022669443
Precision  : 0.6722606120434353
Area Under Curve:    0.701827434651862
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6074 - accuracy: 0.6677 - val_loss: 0.5618 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5595 - accuracy: 0.7119 - val_loss: 0.5450 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7227 - val_loss: 0.5542 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7311 - val_loss: 0.5388 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7367 - val_loss: 0.5376 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5189 - accuracy: 0.7386 - val_loss: 0.5369 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7448 - val_loss: 0.5373 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7473 - val_loss: 0.5388 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7537 - val_loss: 0.5349 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7564 - val_loss: 0.5392 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4854 - accuracy: 0.7608 - val_loss: 0.5407 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4792 - accuracy: 0.7637 - val_loss: 0.5354 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4723 - accuracy: 0.7675 - val_loss: 0.5407 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4687 - accuracy: 0.7694
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7694 - val_loss: 0.5440 - val_accuracy: 0.7217 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4342110138114125
Confusion Matrix :
 [[2618 1705]
 [ 784 3539]]
Accuracy on test set:    0.7121212121212122
Sensitivity:    0.8186444598658339 	 Specificity:    0.6055979643765903
Precision  : 0.6748665141113653
Area Under Curve:    0.712121212121212
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6119 - accuracy: 0.6604 - val_loss: 0.5615 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7076 - val_loss: 0.5514 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7217 - val_loss: 0.5429 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7274 - val_loss: 0.5393 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5267 - accuracy: 0.7321 - val_loss: 0.5396 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5213 - accuracy: 0.7359 - val_loss: 0.5314 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7418 - val_loss: 0.5380 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5083 - accuracy: 0.7437 - val_loss: 0.5344 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7481 - val_loss: 0.5295 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4956 - accuracy: 0.7536 - val_loss: 0.5385 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7580 - val_loss: 0.5351 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4822 - accuracy: 0.7600 - val_loss: 0.5377 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4779 - accuracy: 0.7641 - val_loss: 0.5393 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4716 - accuracy: 0.7681
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4722 - accuracy: 0.7678 - val_loss: 0.5360 - val_accuracy: 0.7303 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.43824759966483195
Confusion Matrix :
 [[2844 1479]
 [ 963 3360]]
Accuracy on test set:    0.7175572519083969
Sensitivity:    0.7772380291464261 	 Specificity:    0.6578764746703678
Precision  : 0.69435833849969
Area Under Curve:    0.7175572519083969
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6064 - accuracy: 0.6658 - val_loss: 0.5622 - val_accuracy: 0.7052 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5619 - accuracy: 0.7100 - val_loss: 0.5471 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7226 - val_loss: 0.5353 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7299 - val_loss: 0.5344 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7358 - val_loss: 0.5323 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5168 - accuracy: 0.7413 - val_loss: 0.5301 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 7/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7438 - val_loss: 0.5389 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5057 - accuracy: 0.7464 - val_loss: 0.5400 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7504 - val_loss: 0.5361 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4945 - accuracy: 0.7563
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4951 - accuracy: 0.7558 - val_loss: 0.5331 - val_accuracy: 0.7292 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4275802833617069
Confusion Matrix :
 [[2840 1483]
 [1003 3320]]
Accuracy on test set:    0.712468193384224
Sensitivity:    0.7679851954661115 	 Specificity:    0.6569511913023364
Precision  : 0.6912346450135332
Area Under Curve:    0.712468193384224
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6081 - accuracy: 0.6669 - val_loss: 0.5572 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5563 - accuracy: 0.7129 - val_loss: 0.5407 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7231 - val_loss: 0.5369 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7291 - val_loss: 0.5386 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7365 - val_loss: 0.5316 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7391 - val_loss: 0.5303 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5116 - accuracy: 0.7444 - val_loss: 0.5376 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7475 - val_loss: 0.5302 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4974 - accuracy: 0.7523 - val_loss: 0.5350 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7561 - val_loss: 0.5338 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7595 - val_loss: 0.5339 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7625 - val_loss: 0.5360 - val_accuracy: 0.7343 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4763 - accuracy: 0.7642 - val_loss: 0.5365 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4680 - accuracy: 0.7676 - val_loss: 0.5353 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4639 - accuracy: 0.7719 - val_loss: 0.5435 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4546 - accuracy: 0.7764 - val_loss: 0.5455 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 17/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4496 - accuracy: 0.7805
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4493 - accuracy: 0.7806 - val_loss: 0.5398 - val_accuracy: 0.7299 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4336883895772804
Confusion Matrix :
 [[3034 1289]
 [1160 3163]]
Accuracy on test set:    0.7167476289613695
Sensitivity:    0.7316678232708768 	 Specificity:    0.7018274346518621
Precision  : 0.7104672057502246
Area Under Curve:    0.7167476289613695
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6091 - accuracy: 0.6629 - val_loss: 0.5707 - val_accuracy: 0.7029 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5612 - accuracy: 0.7103 - val_loss: 0.5408 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7202 - val_loss: 0.5408 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7269 - val_loss: 0.5348 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5276 - accuracy: 0.7320 - val_loss: 0.5325 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5207 - accuracy: 0.7375 - val_loss: 0.5338 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7431 - val_loss: 0.5310 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7473 - val_loss: 0.5324 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5015 - accuracy: 0.7507 - val_loss: 0.5304 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7533 - val_loss: 0.5366 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7579 - val_loss: 0.5329 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4836 - accuracy: 0.7606 - val_loss: 0.5351 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7649 - val_loss: 0.5369 - val_accuracy: 0.7336 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4697 - accuracy: 0.7689 - val_loss: 0.5367 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4641 - accuracy: 0.7723 - val_loss: 0.5487 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4576 - accuracy: 0.7736 - val_loss: 0.5445 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4515 - accuracy: 0.7782 - val_loss: 0.5451 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4466 - accuracy: 0.7801
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4466 - accuracy: 0.7801 - val_loss: 0.5499 - val_accuracy: 0.7213 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4298037954345371
Confusion Matrix :
 [[3076 1247]
 [1218 3105]]
Accuracy on test set:    0.7148970622253065
Sensitivity:    0.7182512144344205 	 Specificity:    0.7115429100161924
Precision  : 0.7134650735294118
Area Under Curve:    0.7148970622253065
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6069 - accuracy: 0.6639 - val_loss: 0.5630 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5599 - accuracy: 0.7098 - val_loss: 0.5498 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7234 - val_loss: 0.5462 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7277 - val_loss: 0.5414 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5281 - accuracy: 0.7336 - val_loss: 0.5511 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5200 - accuracy: 0.7393 - val_loss: 0.5368 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5146 - accuracy: 0.7424 - val_loss: 0.5335 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5047 - accuracy: 0.7471 - val_loss: 0.5331 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7522 - val_loss: 0.5379 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7542 - val_loss: 0.5393 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4877 - accuracy: 0.7577 - val_loss: 0.5391 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4820 - accuracy: 0.7615 - val_loss: 0.5444 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4781 - accuracy: 0.7630
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4778 - accuracy: 0.7632 - val_loss: 0.5559 - val_accuracy: 0.7201 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4288197031441996
Confusion Matrix :
 [[3151 1172]
 [1298 3025]]
Accuracy on test set:    0.7143187601202868
Sensitivity:    0.6997455470737913 	 Specificity:    0.7288919731667823
Precision  : 0.7207529187514892
Area Under Curve:    0.7143187601202868
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6121 - accuracy: 0.6620 - val_loss: 0.5636 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5626 - accuracy: 0.7074 - val_loss: 0.5545 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7181 - val_loss: 0.5448 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7258 - val_loss: 0.5417 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7313 - val_loss: 0.5357 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7341 - val_loss: 0.5385 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7374 - val_loss: 0.5471 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7421 - val_loss: 0.5393 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7480 - val_loss: 0.5379 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4990 - accuracy: 0.7523 - val_loss: 0.5411 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4933 - accuracy: 0.7546
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7545 - val_loss: 0.5457 - val_accuracy: 0.7179 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.449196797211319
Confusion Matrix :
 [[3323 1000]
 [1389 2934]]
Accuracy on test set:    0.7236872542216054
Sensitivity:    0.6786953504510757 	 Specificity:    0.768679157992135
Precision  : 0.7458057956278596
Area Under Curve:    0.7236872542216053
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6154 - accuracy: 0.6573 - val_loss: 0.5698 - val_accuracy: 0.6985 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5630 - accuracy: 0.7087 - val_loss: 0.5551 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7197 - val_loss: 0.5521 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7265 - val_loss: 0.5457 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7327 - val_loss: 0.5448 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7361 - val_loss: 0.5403 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5157 - accuracy: 0.7405 - val_loss: 0.5385 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5096 - accuracy: 0.7454 - val_loss: 0.5412 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7493 - val_loss: 0.5437 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4966 - accuracy: 0.7533 - val_loss: 0.5399 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4922 - accuracy: 0.7533 - val_loss: 0.5455 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4860 - accuracy: 0.7584
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7573 - val_loss: 0.5469 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4830226551121107
Confusion Matrix :
 [[3068 1255]
 [ 984 3339]]
Accuracy on test set:    0.7410363173721952
Sensitivity:    0.7723802914642609 	 Specificity:    0.7096923432801295
Precision  : 0.7268175881584675
Area Under Curve:    0.7410363173721952
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6098 - accuracy: 0.6642 - val_loss: 0.5705 - val_accuracy: 0.6965 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5632 - accuracy: 0.7103 - val_loss: 0.5543 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5495 - accuracy: 0.7200 - val_loss: 0.5491 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7281 - val_loss: 0.5459 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5307 - accuracy: 0.7316 - val_loss: 0.5414 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7348 - val_loss: 0.5452 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7396 - val_loss: 0.5424 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7428 - val_loss: 0.5397 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7463 - val_loss: 0.5386 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 10/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7480 - val_loss: 0.5450 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7520 - val_loss: 0.5386 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7575 - val_loss: 0.5456 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7585 - val_loss: 0.5450 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4795 - accuracy: 0.7631 - val_loss: 0.5401 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7637 - val_loss: 0.5488 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4700 - accuracy: 0.7666 - val_loss: 0.5505 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4646 - accuracy: 0.7691 - val_loss: 0.5588 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4591 - accuracy: 0.7743 - val_loss: 0.5535 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 19/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4529 - accuracy: 0.7754
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4536 - accuracy: 0.7748 - val_loss: 0.5548 - val_accuracy: 0.7241 - lr: 0.0010
271/271 [==============================] - 0s 665us/step
Independent Testing Matthews Correlation:  0.5005210445180597
Confusion Matrix :
 [[3186 1137]
 [1023 3300]]
Accuracy on test set:    0.7501734906315058
Sensitivity:    0.7633587786259542 	 Specificity:    0.7369882026370576
Precision  : 0.7437457741717377
Area Under Curve:    0.7501734906315058
(8646, 4352) (8646,)
Mean MCC = 0.4435 + 0.0262 and Mean AUC = 0.7205 + 0.0137
Mean Sensitivity = 0.7516 + 0.0410 and Mean Specificity = 0.6894 + 0.0506 and Mean Accuracy = 0.7205 + 0.0137
Mean Precision = 0.7094 + 0.0247





Seed   : 133289
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6084 - accuracy: 0.6671 - val_loss: 0.5675 - val_accuracy: 0.7023 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7140 - val_loss: 0.5485 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7236 - val_loss: 0.5439 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5319 - accuracy: 0.7304 - val_loss: 0.5439 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5252 - accuracy: 0.7359 - val_loss: 0.5356 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7399 - val_loss: 0.5386 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7425 - val_loss: 0.5389 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7518 - val_loss: 0.5419 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4970 - accuracy: 0.7538 - val_loss: 0.5354 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4911 - accuracy: 0.7571
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7564 - val_loss: 0.5378 - val_accuracy: 0.7219 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.41392813290624497
Confusion Matrix :
 [[2673 1650]
 [ 910 3413]]
Accuracy on test set:    0.703909322229933
Sensitivity:    0.7894980337728429 	 Specificity:    0.6183206106870229
Precision  : 0.6741062611100138
Area Under Curve:    0.7039093222299329
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5991 - accuracy: 0.6747 - val_loss: 0.5694 - val_accuracy: 0.7020 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5568 - accuracy: 0.7127 - val_loss: 0.5488 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7267 - val_loss: 0.5447 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7324 - val_loss: 0.5424 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7358 - val_loss: 0.5399 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5167 - accuracy: 0.7435 - val_loss: 0.5378 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5105 - accuracy: 0.7445 - val_loss: 0.5344 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7489 - val_loss: 0.5346 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4983 - accuracy: 0.7524 - val_loss: 0.5391 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7550 - val_loss: 0.5370 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4860 - accuracy: 0.7584 - val_loss: 0.5420 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4818 - accuracy: 0.7608 - val_loss: 0.5399 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4748 - accuracy: 0.7675 - val_loss: 0.5411 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4704 - accuracy: 0.7685 - val_loss: 0.5430 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 15/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4647 - accuracy: 0.7733
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4641 - accuracy: 0.7737 - val_loss: 0.5492 - val_accuracy: 0.7251 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.42332802530023816
Confusion Matrix :
 [[3092 1231]
 [1262 3061]]
Accuracy on test set:    0.7116585704371964
Sensitivity:    0.7080730973860745 	 Specificity:    0.7152440434883183
Precision  : 0.7131873252562908
Area Under Curve:    0.7116585704371964
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6014 - accuracy: 0.6701 - val_loss: 0.5688 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5547 - accuracy: 0.7153 - val_loss: 0.5575 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7246 - val_loss: 0.5557 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5303 - accuracy: 0.7321 - val_loss: 0.5423 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7376 - val_loss: 0.5431 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7374 - val_loss: 0.5534 - val_accuracy: 0.7210 - lr: 0.0010

Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7447 - val_loss: 0.5487 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7495 - val_loss: 0.5391 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7512 - val_loss: 0.5498 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4932 - accuracy: 0.7548 - val_loss: 0.5418 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4861 - accuracy: 0.7594 - val_loss: 0.5473 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4770 - accuracy: 0.7645
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4782 - accuracy: 0.7638 - val_loss: 0.5468 - val_accuracy: 0.7161 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.435362863168786
Confusion Matrix :
 [[3175 1148]
 [1294 3029]]
Accuracy on test set:    0.7175572519083969
Sensitivity:    0.7006708304418228 	 Specificity:    0.7344436733749711
Precision  : 0.7251615992338999
Area Under Curve:    0.7175572519083969
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5995 - accuracy: 0.6738 - val_loss: 0.5635 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5546 - accuracy: 0.7142 - val_loss: 0.5503 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7259 - val_loss: 0.5464 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7329 - val_loss: 0.5450 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5212 - accuracy: 0.7366 - val_loss: 0.5411 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7423 - val_loss: 0.5390 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7445 - val_loss: 0.5456 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7494 - val_loss: 0.5428 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7537 - val_loss: 0.5427 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4884 - accuracy: 0.7578 - val_loss: 0.5490 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4818 - accuracy: 0.7620
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7612 - val_loss: 0.5440 - val_accuracy: 0.7255 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4261085984026365
Confusion Matrix :
 [[3101 1222]
 [1259 3064]]
Accuracy on test set:    0.7130464954892436
Sensitivity:    0.7087670599120981 	 Specificity:    0.7173259310663891
Precision  : 0.7148856742883808
Area Under Curve:    0.7130464954892436
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6210 - accuracy: 0.6561 - val_loss: 0.5751 - val_accuracy: 0.6975 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5628 - accuracy: 0.7094 - val_loss: 0.5547 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7217 - val_loss: 0.5476 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7292 - val_loss: 0.5637 - val_accuracy: 0.6942 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7341 - val_loss: 0.5534 - val_accuracy: 0.7055 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5202 - accuracy: 0.7384 - val_loss: 0.5396 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7422 - val_loss: 0.5410 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7485 - val_loss: 0.5499 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7507 - val_loss: 0.5408 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4918 - accuracy: 0.7555 - val_loss: 0.5405 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7562 - val_loss: 0.5513 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4796 - accuracy: 0.7624 - val_loss: 0.5449 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4755 - accuracy: 0.7641 - val_loss: 0.5499 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4684 - accuracy: 0.7688
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4682 - accuracy: 0.7691 - val_loss: 0.5556 - val_accuracy: 0.7221 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.441864706024967
Confusion Matrix :
 [[3040 1283]
 [1131 3192]]
Accuracy on test set:    0.720795743696507
Sensitivity:    0.7383761276891048 	 Specificity:    0.7032153597039094
Precision  : 0.7132960893854748
Area Under Curve:    0.720795743696507
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6095 - accuracy: 0.6633 - val_loss: 0.5663 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5580 - accuracy: 0.7130 - val_loss: 0.5497 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7242 - val_loss: 0.5460 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7320 - val_loss: 0.5490 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7374 - val_loss: 0.5446 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7406 - val_loss: 0.5450 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7447 - val_loss: 0.5454 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7498 - val_loss: 0.5461 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4970 - accuracy: 0.7548 - val_loss: 0.5419 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7566 - val_loss: 0.5471 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7613 - val_loss: 0.5441 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4788 - accuracy: 0.7636 - val_loss: 0.5444 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4719 - accuracy: 0.7684 - val_loss: 0.5502 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4669 - accuracy: 0.7685 - val_loss: 0.5502 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4620 - accuracy: 0.7723 - val_loss: 0.5523 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 16/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4541 - accuracy: 0.7775
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4550 - accuracy: 0.7773 - val_loss: 0.5557 - val_accuracy: 0.7208 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.42733666862474773
Confusion Matrix :
 [[2863 1460]
 [1025 3298]]
Accuracy on test set:    0.7125838538052278
Sensitivity:    0.7628961369419385 	 Specificity:    0.6622715706685173
Precision  : 0.6931483816729719
Area Under Curve:    0.7125838538052278
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6068 - accuracy: 0.6648 - val_loss: 0.5709 - val_accuracy: 0.7012 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7103 - val_loss: 0.5558 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7174 - val_loss: 0.5556 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7262 - val_loss: 0.5525 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7312 - val_loss: 0.5525 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7364 - val_loss: 0.5466 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5191 - accuracy: 0.7372 - val_loss: 0.5480 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5111 - accuracy: 0.7431 - val_loss: 0.5527 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7450 - val_loss: 0.5463 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7490 - val_loss: 0.5502 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7529 - val_loss: 0.5530 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7539 - val_loss: 0.5529 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4862 - accuracy: 0.7574
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4860 - accuracy: 0.7574 - val_loss: 0.5650 - val_accuracy: 0.7110 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4595898003003091
Confusion Matrix :
 [[2802 1521]
 [ 840 3483]]
Accuracy on test set:    0.7269257460097155
Sensitivity:    0.8056904927133934 	 Specificity:    0.6481609993060374
Precision  : 0.6960431654676259
Area Under Curve:    0.7269257460097155
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6056 - accuracy: 0.6673 - val_loss: 0.5704 - val_accuracy: 0.7021 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7115 - val_loss: 0.5550 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7215 - val_loss: 0.5462 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7287 - val_loss: 0.5527 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7352 - val_loss: 0.5456 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7403 - val_loss: 0.5415 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7457 - val_loss: 0.5416 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7474 - val_loss: 0.5416 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7527 - val_loss: 0.5420 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7581 - val_loss: 0.5418 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7595 - val_loss: 0.5455 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7665 - val_loss: 0.5489 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4727 - accuracy: 0.7692 - val_loss: 0.5479 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 14/400
264/274 [===========================>..] - ETA: 0s - loss: 0.4659 - accuracy: 0.7726
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4662 - accuracy: 0.7727 - val_loss: 0.5527 - val_accuracy: 0.7203 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4338128282035929
Confusion Matrix :
 [[3260 1063]
 [1390 2933]]
Accuracy on test set:    0.7162849872773537
Sensitivity:    0.6784640296090678 	 Specificity:    0.7541059449456397
Precision  : 0.733983983983984
Area Under Curve:    0.7162849872773536
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6138 - accuracy: 0.6563 - val_loss: 0.5756 - val_accuracy: 0.6992 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5624 - accuracy: 0.7099 - val_loss: 0.5556 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7223 - val_loss: 0.5513 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7264 - val_loss: 0.5486 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7314 - val_loss: 0.5456 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7351 - val_loss: 0.5522 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7407 - val_loss: 0.5451 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7449 - val_loss: 0.5473 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7486 - val_loss: 0.5443 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7533 - val_loss: 0.5473 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 11/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7560 - val_loss: 0.5509 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 12/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4831 - accuracy: 0.7602
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4839 - accuracy: 0.7588 - val_loss: 0.5597 - val_accuracy: 0.7154 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.4853568125495619
Confusion Matrix :
 [[2857 1466]
 [ 785 3538]]
Accuracy on test set:    0.739648392320148
Sensitivity:    0.8184131390238261 	 Specificity:    0.6608836456164701
Precision  : 0.7070343725019984
Area Under Curve:    0.739648392320148
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6117 - accuracy: 0.6625 - val_loss: 0.5694 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.7077 - val_loss: 0.5588 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5491 - accuracy: 0.7190 - val_loss: 0.5510 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7222 - val_loss: 0.5513 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7306 - val_loss: 0.5531 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7319 - val_loss: 0.5442 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5207 - accuracy: 0.7376 - val_loss: 0.5499 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7424 - val_loss: 0.5453 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5095 - accuracy: 0.7447
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7444 - val_loss: 0.5463 - val_accuracy: 0.7223 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.5102239023671101
Confusion Matrix :
 [[3121 1202]
 [ 920 3403]]
Accuracy on test set:    0.7545685866296553
Sensitivity:    0.7871848253527642 	 Specificity:    0.7219523479065464
Precision  : 0.7389793702497286
Area Under Curve:    0.7545685866296553
(8646, 4352) (8646,)
Mean MCC = 0.4457 + 0.0290 and Mean AUC = 0.7217 + 0.0143
Mean Sensitivity = 0.7498 + 0.0469 and Mean Specificity = 0.6936 + 0.0413 and Mean Accuracy = 0.7217 + 0.0143
Mean Precision = 0.7110 + 0.0186





Seed   : 169621
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5993 - accuracy: 0.6740 - val_loss: 0.5548 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5559 - accuracy: 0.7152 - val_loss: 0.5420 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7261 - val_loss: 0.5386 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7287 - val_loss: 0.5359 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5262 - accuracy: 0.7348 - val_loss: 0.5337 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5205 - accuracy: 0.7389 - val_loss: 0.5274 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7424 - val_loss: 0.5261 - val_accuracy: 0.7331 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7446 - val_loss: 0.5262 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7487 - val_loss: 0.5261 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4966 - accuracy: 0.7517 - val_loss: 0.5272 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7562 - val_loss: 0.5279 - val_accuracy: 0.7358 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4880 - accuracy: 0.7597 - val_loss: 0.5286 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4819 - accuracy: 0.7611 - val_loss: 0.5286 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4741 - accuracy: 0.7678 - val_loss: 0.5280 - val_accuracy: 0.7327 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4705 - accuracy: 0.7666 - val_loss: 0.5306 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 16/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4667 - accuracy: 0.7706
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4673 - accuracy: 0.7704 - val_loss: 0.5315 - val_accuracy: 0.7282 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.41779848958665683
Confusion Matrix :
 [[2899 1424]
 [1098 3225]]
Accuracy on test set:    0.7083044182280823
Sensitivity:    0.7460097154753643 	 Specificity:    0.6705991209808003
Precision  : 0.6936975693697569
Area Under Curve:    0.7083044182280823
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6147 - accuracy: 0.6610 - val_loss: 0.5639 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5599 - accuracy: 0.7107 - val_loss: 0.5438 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7223 - val_loss: 0.5439 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7316 - val_loss: 0.5367 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7345 - val_loss: 0.5412 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7397 - val_loss: 0.5276 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7441 - val_loss: 0.5379 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7486 - val_loss: 0.5291 - val_accuracy: 0.7361 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7532 - val_loss: 0.5339 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4901 - accuracy: 0.7573 - val_loss: 0.5259 - val_accuracy: 0.7350 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4844 - accuracy: 0.7594 - val_loss: 0.5273 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4781 - accuracy: 0.7657 - val_loss: 0.5333 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 13/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4693 - accuracy: 0.7693
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4699 - accuracy: 0.7690 - val_loss: 0.5363 - val_accuracy: 0.7278 - lr: 0.0010

271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4237787435791642
Confusion Matrix :
 [[2814 1509]
 [ 995 3328]]
Accuracy on test set:    0.7103863058061531
Sensitivity:    0.7698357622021744 	 Specificity:    0.6509368494101319
Precision  : 0.6880297705189167
Area Under Curve:    0.710386305806153
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6090 - accuracy: 0.6656 - val_loss: 0.5583 - val_accuracy: 0.7107 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7117 - val_loss: 0.5481 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7230 - val_loss: 0.5432 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7305 - val_loss: 0.5381 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7364 - val_loss: 0.5325 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7416 - val_loss: 0.5416 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7458 - val_loss: 0.5378 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7504 - val_loss: 0.5293 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4959 - accuracy: 0.7552 - val_loss: 0.5312 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4901 - accuracy: 0.7580 - val_loss: 0.5387 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4819 - accuracy: 0.7615 - val_loss: 0.5336 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4779 - accuracy: 0.7643 - val_loss: 0.5369 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7708 - val_loss: 0.5412 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4624 - accuracy: 0.7724
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4628 - accuracy: 0.7726 - val_loss: 0.5397 - val_accuracy: 0.7258 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4459760103289031
Confusion Matrix :
 [[3057 1266]
 [1130 3193]]
Accuracy on test set:    0.7228776312745778
Sensitivity:    0.7386074485311126 	 Specificity:    0.707147814018043
Precision  : 0.7160798385288181
Area Under Curve:    0.7228776312745779
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5981 - accuracy: 0.6734 - val_loss: 0.5553 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5558 - accuracy: 0.7123 - val_loss: 0.5445 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7220 - val_loss: 0.5412 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7298 - val_loss: 0.5326 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7345 - val_loss: 0.5448 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7398 - val_loss: 0.5256 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7443 - val_loss: 0.5252 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5057 - accuracy: 0.7461 - val_loss: 0.5287 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7521 - val_loss: 0.5267 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7555 - val_loss: 0.5302 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7591 - val_loss: 0.5248 - val_accuracy: 0.7331 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.7630 - val_loss: 0.5303 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4752 - accuracy: 0.7655 - val_loss: 0.5309 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4707 - accuracy: 0.7678 - val_loss: 0.5411 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4648 - accuracy: 0.7711 - val_loss: 0.5345 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 16/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4585 - accuracy: 0.7750
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4594 - accuracy: 0.7745 - val_loss: 0.5333 - val_accuracy: 0.7295 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4306715404707982
Confusion Matrix :
 [[2935 1388]
 [1078 3245]]
Accuracy on test set:    0.7147814018043026
Sensitivity:    0.7506361323155216 	 Specificity:    0.6789266712930835
Precision  : 0.7004101014461472
Area Under Curve:    0.7147814018043026
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6041 - accuracy: 0.6677 - val_loss: 0.5629 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5578 - accuracy: 0.7120 - val_loss: 0.5448 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7210 - val_loss: 0.5472 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7294 - val_loss: 0.5374 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7364 - val_loss: 0.5324 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7386 - val_loss: 0.5293 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5111 - accuracy: 0.7442 - val_loss: 0.5296 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7476 - val_loss: 0.5283 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7556 - val_loss: 0.5367 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7562 - val_loss: 0.5349 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4812 - accuracy: 0.7620
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4816 - accuracy: 0.7615 - val_loss: 0.5354 - val_accuracy: 0.7307 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4284407893442444
Confusion Matrix :
 [[2960 1363]
 [1111 3212]]
Accuracy on test set:    0.7138561184362711
Sensitivity:    0.7430025445292621 	 Specificity:    0.6847096923432802
Precision  : 0.7020765027322404
Area Under Curve:    0.7138561184362711
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6131 - accuracy: 0.6619 - val_loss: 0.5606 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7112 - val_loss: 0.5404 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7205 - val_loss: 0.5333 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7283 - val_loss: 0.5308 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7332 - val_loss: 0.5299 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7374 - val_loss: 0.5273 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7423 - val_loss: 0.5298 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5078 - accuracy: 0.7470 - val_loss: 0.5312 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7507 - val_loss: 0.5313 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7522 - val_loss: 0.5278 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7562 - val_loss: 0.5294 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4857 - accuracy: 0.7583 - val_loss: 0.5326 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4804 - accuracy: 0.7625
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7626 - val_loss: 0.5414 - val_accuracy: 0.7258 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.433820849699028
Confusion Matrix :
 [[3368  955]
 [1508 2815]]
Accuracy on test set:    0.7151283830673144
Sensitivity:    0.6511681702521397 	 Specificity:    0.779088595882489
Precision  : 0.746684350132626
Area Under Curve:    0.7151283830673143
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6235 - accuracy: 0.6454 - val_loss: 0.5705 - val_accuracy: 0.7019 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5719 - accuracy: 0.7015 - val_loss: 0.5550 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5553 - accuracy: 0.7153 - val_loss: 0.5504 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7242 - val_loss: 0.5478 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7258 - val_loss: 0.5405 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7313 - val_loss: 0.5378 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5270 - accuracy: 0.7348 - val_loss: 0.5371 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7370 - val_loss: 0.5353 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7394 - val_loss: 0.5408 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5116 - accuracy: 0.7433 - val_loss: 0.5451 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7465 - val_loss: 0.5401 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7471 - val_loss: 0.5375 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7500 - val_loss: 0.5424 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7546 - val_loss: 0.5430 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4860 - accuracy: 0.7590 - val_loss: 0.5437 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4830 - accuracy: 0.7602 - val_loss: 0.5406 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4782 - accuracy: 0.7618 - val_loss: 0.5526 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4732 - accuracy: 0.7648 - val_loss: 0.5517 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 19/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4667 - accuracy: 0.7699
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4669 - accuracy: 0.7695 - val_loss: 0.5559 - val_accuracy: 0.7223 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.4448259612658827
Confusion Matrix :
 [[2965 1358]
 [1047 3276]]
Accuracy on test set:    0.7218366874855424
Sensitivity:    0.7578070784177654 	 Specificity:    0.6858662965533194
Precision  : 0.7069486404833837
Area Under Curve:    0.7218366874855424
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6090 - accuracy: 0.6619 - val_loss: 0.5652 - val_accuracy: 0.7070 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5587 - accuracy: 0.7136 - val_loss: 0.5454 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7224 - val_loss: 0.5439 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7276 - val_loss: 0.5375 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7324 - val_loss: 0.5402 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7393 - val_loss: 0.5333 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5167 - accuracy: 0.7419 - val_loss: 0.5364 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7458 - val_loss: 0.5321 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7498 - val_loss: 0.5361 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7557 - val_loss: 0.5344 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7569 - val_loss: 0.5394 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7629 - val_loss: 0.5395 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4793 - accuracy: 0.7648 - val_loss: 0.5385 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4712 - accuracy: 0.7687 - val_loss: 0.5441 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4662 - accuracy: 0.7724
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4665 - accuracy: 0.7720 - val_loss: 0.5415 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4446465544624799
Confusion Matrix :
 [[2932 1391]
 [1017 3306]]
Accuracy on test set:    0.7214897062225306
Sensitivity:    0.7647467036780013 	 Specificity:    0.6782327087670599
Precision  : 0.7038535235256547
Area Under Curve:    0.7214897062225306
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6065 - accuracy: 0.6676 - val_loss: 0.5740 - val_accuracy: 0.6924 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7100 - val_loss: 0.5524 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7201 - val_loss: 0.5511 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7268 - val_loss: 0.5516 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7308 - val_loss: 0.5404 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7361 - val_loss: 0.5410 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7411 - val_loss: 0.5405 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7461 - val_loss: 0.5404 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5032 - accuracy: 0.7485 - val_loss: 0.5394 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7520 - val_loss: 0.5394 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7547 - val_loss: 0.5446 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4856 - accuracy: 0.7597 - val_loss: 0.5406 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4805 - accuracy: 0.7625
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7626 - val_loss: 0.5510 - val_accuracy: 0.7190 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.47899530917997013
Confusion Matrix :
 [[3049 1274]
 [ 983 3340]]
Accuracy on test set:    0.7389544297941244
Sensitivity:    0.7726116123062688 	 Specificity:    0.7052972472819801
Precision  : 0.7238838318162115
Area Under Curve:    0.7389544297941244
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6103 - accuracy: 0.6641 - val_loss: 0.5645 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5649 - accuracy: 0.7076 - val_loss: 0.5550 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5505 - accuracy: 0.7182 - val_loss: 0.5496 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7252 - val_loss: 0.5467 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7283 - val_loss: 0.5419 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7355 - val_loss: 0.5419 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7368 - val_loss: 0.5443 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5116 - accuracy: 0.7443 - val_loss: 0.5438 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7426 - val_loss: 0.5454 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7502 - val_loss: 0.5497 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4932 - accuracy: 0.7539 - val_loss: 0.5424 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4890 - accuracy: 0.7586 - val_loss: 0.5578 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4827 - accuracy: 0.7603
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.7598 - val_loss: 0.5486 - val_accuracy: 0.7188 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4982661734926591
Confusion Matrix :
 [[3234 1089]
 [1080 3243]]
Accuracy on test set:    0.7491325468424705
Sensitivity:    0.7501734906315058 	 Specificity:    0.7480916030534351
Precision  : 0.7486149584487535
Area Under Curve:    0.7491325468424704
(8646, 4352) (8646,)
Mean MCC = 0.4447 + 0.0241 and Mean AUC = 0.7217 + 0.0123
Mean Sensitivity = 0.7445 + 0.0329 and Mean Specificity = 0.6989 + 0.0364 and Mean Accuracy = 0.7217 + 0.0123
Mean Precision = 0.7130 + 0.0198





Seed   : 562472
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6054 - accuracy: 0.6687 - val_loss: 0.5645 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7109 - val_loss: 0.5515 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7266 - val_loss: 0.5450 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7310 - val_loss: 0.5460 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5231 - accuracy: 0.7381 - val_loss: 0.5403 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7413 - val_loss: 0.5361 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7452 - val_loss: 0.5360 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7494 - val_loss: 0.5374 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7527 - val_loss: 0.5415 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7566 - val_loss: 0.5364 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4852 - accuracy: 0.7620 - val_loss: 0.5371 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4756 - accuracy: 0.7672 - val_loss: 0.5471 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4725 - accuracy: 0.7693 - val_loss: 0.5449 - val_accuracy: 0.7242 - lr: 0.0010

Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4652 - accuracy: 0.7730 - val_loss: 0.5475 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4608 - accuracy: 0.7765 - val_loss: 0.5497 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4544 - accuracy: 0.7789
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4542 - accuracy: 0.7793 - val_loss: 0.5584 - val_accuracy: 0.7192 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4237613534430609
Confusion Matrix :
 [[2954 1369]
 [1125 3198]]
Accuracy on test set:    0.7115429100161924
Sensitivity:    0.739764052741152 	 Specificity:    0.683321767291233
Precision  : 0.7002408583315086
Area Under Curve:    0.7115429100161925
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6141 - accuracy: 0.6567 - val_loss: 0.5688 - val_accuracy: 0.6974 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5590 - accuracy: 0.7113 - val_loss: 0.5541 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7228 - val_loss: 0.5492 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7295 - val_loss: 0.5468 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7361 - val_loss: 0.5415 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7396 - val_loss: 0.5406 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5105 - accuracy: 0.7419 - val_loss: 0.5450 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7463 - val_loss: 0.5442 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7508 - val_loss: 0.5415 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4924 - accuracy: 0.7552 - val_loss: 0.5400 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4855 - accuracy: 0.7586 - val_loss: 0.5435 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7604 - val_loss: 0.5489 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4758 - accuracy: 0.7635 - val_loss: 0.5476 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4665 - accuracy: 0.7684 - val_loss: 0.5493 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 15/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4623 - accuracy: 0.7724
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4640 - accuracy: 0.7712 - val_loss: 0.5518 - val_accuracy: 0.7170 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4234498884274967
Confusion Matrix :
 [[2940 1383]
 [1113 3210]]
Accuracy on test set:    0.7113115891741846
Sensitivity:    0.7425399028452464 	 Specificity:    0.6800832755031229
Precision  : 0.6988896146309601
Area Under Curve:    0.7113115891741846
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5999 - accuracy: 0.6696 - val_loss: 0.5666 - val_accuracy: 0.7003 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5557 - accuracy: 0.7141 - val_loss: 0.5503 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7229 - val_loss: 0.5416 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7306 - val_loss: 0.5463 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.7361 - val_loss: 0.5410 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7412 - val_loss: 0.5348 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7453 - val_loss: 0.5377 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7496 - val_loss: 0.5396 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7503 - val_loss: 0.5375 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7551 - val_loss: 0.5397 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7599 - val_loss: 0.5377 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4775 - accuracy: 0.7647 - val_loss: 0.5447 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4722 - accuracy: 0.7668 - val_loss: 0.5477 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4669 - accuracy: 0.7695 - val_loss: 0.5479 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4592 - accuracy: 0.7742
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4593 - accuracy: 0.7738 - val_loss: 0.5601 - val_accuracy: 0.7209 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.438252949413009
Confusion Matrix :
 [[2912 1411]
 [1025 3298]]
Accuracy on test set:    0.7182512144344205
Sensitivity:    0.7628961369419385 	 Specificity:    0.6736062919269026
Precision  : 0.7003610108303249
Area Under Curve:    0.7182512144344205
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6031 - accuracy: 0.6711 - val_loss: 0.5609 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5574 - accuracy: 0.7124 - val_loss: 0.5497 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7232 - val_loss: 0.5406 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7290 - val_loss: 0.5378 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7362 - val_loss: 0.5416 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5167 - accuracy: 0.7405 - val_loss: 0.5384 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7448 - val_loss: 0.5372 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7507 - val_loss: 0.5395 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4983 - accuracy: 0.7522 - val_loss: 0.5411 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 10/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7539 - val_loss: 0.5398 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4850 - accuracy: 0.7601 - val_loss: 0.5442 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4791 - accuracy: 0.7652
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4794 - accuracy: 0.7650 - val_loss: 0.5418 - val_accuracy: 0.7289 - lr: 0.0010
271/271 [==============================] - 1s 649us/step
Independent Testing Matthews Correlation:  0.4407735223040347
Confusion Matrix :
 [[2851 1472]
 [ 959 3364]]
Accuracy on test set:    0.7188295165394402
Sensitivity:    0.7781633125144576 	 Specificity:    0.6594957205644228
Precision  : 0.695616211745244
Area Under Curve:    0.7188295165394403
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6167 - accuracy: 0.6566 - val_loss: 0.5687 - val_accuracy: 0.7052 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5615 - accuracy: 0.7106 - val_loss: 0.5451 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7212 - val_loss: 0.5438 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7269 - val_loss: 0.5333 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7324 - val_loss: 0.5349 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7388 - val_loss: 0.5358 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7410 - val_loss: 0.5296 - val_accuracy: 0.7341 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7440 - val_loss: 0.5293 - val_accuracy: 0.7344 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7482 - val_loss: 0.5277 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7532 - val_loss: 0.5418 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7537 - val_loss: 0.5308 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4864 - accuracy: 0.7600 - val_loss: 0.5358 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4843 - accuracy: 0.7592
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7589 - val_loss: 0.5329 - val_accuracy: 0.7343 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4447846357260025
Confusion Matrix :
 [[3060 1263]
 [1138 3185]]
Accuracy on test set:    0.7222993291695582
Sensitivity:    0.7367568817950497 	 Specificity:    0.7078417765440667
Precision  : 0.7160521582733813
Area Under Curve:    0.7222993291695581
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6061 - accuracy: 0.6668 - val_loss: 0.5578 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5586 - accuracy: 0.7099 - val_loss: 0.5441 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7218 - val_loss: 0.5422 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7279 - val_loss: 0.5372 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7333 - val_loss: 0.5338 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5167 - accuracy: 0.7391 - val_loss: 0.5390 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7429 - val_loss: 0.5360 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7484 - val_loss: 0.5344 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7520 - val_loss: 0.5366 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7568 - val_loss: 0.5335 - val_accuracy: 0.7349 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7612 - val_loss: 0.5329 - val_accuracy: 0.7350 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7648 - val_loss: 0.5371 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4721 - accuracy: 0.7679 - val_loss: 0.5419 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4653 - accuracy: 0.7717 - val_loss: 0.5441 - val_accuracy: 0.7327 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4596 - accuracy: 0.7729 - val_loss: 0.5533 - val_accuracy: 0.7335 - lr: 0.0010
Epoch 16/400
263/274 [===========================>..] - ETA: 0s - loss: 0.4538 - accuracy: 0.7764
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4537 - accuracy: 0.7764 - val_loss: 0.5443 - val_accuracy: 0.7294 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4444594337591314
Confusion Matrix :
 [[3166 1157]
 [1245 3078]]
Accuracy on test set:    0.7221836687485542
Sensitivity:    0.7120055517002082 	 Specificity:    0.7323617857969003
Precision  : 0.7268004722550178
Area Under Curve:    0.7221836687485541
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6050 - accuracy: 0.6681 - val_loss: 0.5607 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5639 - accuracy: 0.7087 - val_loss: 0.5496 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7199 - val_loss: 0.5438 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7271 - val_loss: 0.5421 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5303 - accuracy: 0.7325 - val_loss: 0.5389 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5260 - accuracy: 0.7327 - val_loss: 0.5443 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5208 - accuracy: 0.7362 - val_loss: 0.5385 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7408 - val_loss: 0.5387 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7450 - val_loss: 0.5382 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7482 - val_loss: 0.5426 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5009 - accuracy: 0.7472 - val_loss: 0.5419 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7520 - val_loss: 0.5402 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7580 - val_loss: 0.5462 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7593 - val_loss: 0.5456 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7597 - val_loss: 0.5587 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4749 - accuracy: 0.7630 - val_loss: 0.5496 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7661 - val_loss: 0.5639 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4656 - accuracy: 0.7681 - val_loss: 0.5569 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 19/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4630 - accuracy: 0.7684
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4636 - accuracy: 0.7682 - val_loss: 0.5624 - val_accuracy: 0.7178 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.45547596053522044
Confusion Matrix :
 [[2790 1533]
 [ 846 3477]]
Accuracy on test set:    0.7248438584316447
Sensitivity:    0.8043025676613463 	 Specificity:    0.6453851492019431
Precision  : 0.6940119760479042
Area Under Curve:    0.7248438584316448
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6109 - accuracy: 0.6613 - val_loss: 0.5622 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5631 - accuracy: 0.7099 - val_loss: 0.5537 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5484 - accuracy: 0.7207 - val_loss: 0.5505 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7282 - val_loss: 0.5411 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7321 - val_loss: 0.5369 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.7387 - val_loss: 0.5382 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7392 - val_loss: 0.5391 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7446 - val_loss: 0.5390 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7485 - val_loss: 0.5396 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7527 - val_loss: 0.5373 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7558 - val_loss: 0.5365 - val_accuracy: 0.7336 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4854 - accuracy: 0.7578 - val_loss: 0.5439 - val_accuracy: 0.7331 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7610 - val_loss: 0.5375 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4730 - accuracy: 0.7667 - val_loss: 0.5382 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4672 - accuracy: 0.7700 - val_loss: 0.5553 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4650 - accuracy: 0.7701
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4651 - accuracy: 0.7705 - val_loss: 0.5570 - val_accuracy: 0.7296 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4532243340148464
Confusion Matrix :
 [[2864 1459]
 [ 920 3403]]
Accuracy on test set:    0.7248438584316447
Sensitivity:    0.7871848253527642 	 Specificity:    0.6625028915105251
Precision  : 0.699917729329494
Area Under Curve:    0.7248438584316447
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6060 - accuracy: 0.6646 - val_loss: 0.5597 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7119 - val_loss: 0.5459 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7210 - val_loss: 0.5382 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7273 - val_loss: 0.5350 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5286 - accuracy: 0.7315 - val_loss: 0.5369 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7359 - val_loss: 0.5346 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7424 - val_loss: 0.5320 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7455 - val_loss: 0.5335 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7479 - val_loss: 0.5325 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7542 - val_loss: 0.5343 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7586 - val_loss: 0.5437 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7598 - val_loss: 0.5350 - val_accuracy: 0.7336 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4778 - accuracy: 0.7630 - val_loss: 0.5411 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4718 - accuracy: 0.7678 - val_loss: 0.5431 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4655 - accuracy: 0.7732 - val_loss: 0.5440 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4581 - accuracy: 0.7765 - val_loss: 0.5465 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 17/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4519 - accuracy: 0.7808
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4529 - accuracy: 0.7799 - val_loss: 0.5519 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.4741075074738398
Confusion Matrix :
 [[3101 1222]
 [1053 3270]]
Accuracy on test set:    0.7368725422160537
Sensitivity:    0.7564191533657183 	 Specificity:    0.7173259310663891
Precision  : 0.7279608192341941
Area Under Curve:    0.7368725422160537
(8646, 4352) (8646,)
Epoch 1/400

274/274 [==============================] - 1s 3ms/step - loss: 0.6140 - accuracy: 0.6591 - val_loss: 0.5643 - val_accuracy: 0.7077 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5682 - accuracy: 0.7049 - val_loss: 0.5514 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5524 - accuracy: 0.7174 - val_loss: 0.5444 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7247 - val_loss: 0.5385 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7308 - val_loss: 0.5421 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7365 - val_loss: 0.5402 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7388 - val_loss: 0.5419 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5120 - accuracy: 0.7427 - val_loss: 0.5364 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5054 - accuracy: 0.7479 - val_loss: 0.5381 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4963 - accuracy: 0.7535
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4973 - accuracy: 0.7530 - val_loss: 0.5392 - val_accuracy: 0.7276 - lr: 0.0010
271/271 [==============================] - 0s 669us/step
Independent Testing Matthews Correlation:  0.5172350771849544
Confusion Matrix :
 [[3274 1049]
 [1038 3285]]
Accuracy on test set:    0.758616701364793
Sensitivity:    0.7598889659958362 	 Specificity:    0.7573444367337497
Precision  : 0.7579603137978772
Area Under Curve:    0.758616701364793
(8646, 4352) (8646,)
Mean MCC = 0.4516 + 0.0261 and Mean AUC = 0.7250 + 0.0132
Mean Sensitivity = 0.7580 + 0.0256 and Mean Specificity = 0.6919 + 0.0338 and Mean Accuracy = 0.7250 + 0.0132
Mean Precision = 0.7118 + 0.0195





Seed   : 498880
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6118 - accuracy: 0.6652 - val_loss: 0.5593 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5589 - accuracy: 0.7107 - val_loss: 0.5474 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7219 - val_loss: 0.5409 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7312 - val_loss: 0.5400 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5225 - accuracy: 0.7358 - val_loss: 0.5387 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7411 - val_loss: 0.5413 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7437 - val_loss: 0.5337 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7496 - val_loss: 0.5357 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4956 - accuracy: 0.7542 - val_loss: 0.5408 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7573 - val_loss: 0.5321 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7603 - val_loss: 0.5376 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4756 - accuracy: 0.7665 - val_loss: 0.5388 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 13/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4698 - accuracy: 0.7681
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4711 - accuracy: 0.7675 - val_loss: 0.5538 - val_accuracy: 0.7221 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4201209587618348
Confusion Matrix :
 [[3147 1176]
 [1332 2991]]
Accuracy on test set:    0.7099236641221374
Sensitivity:    0.6918806384455239 	 Specificity:    0.7279666897987509
Precision  : 0.7177825773938085
Area Under Curve:    0.7099236641221374
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6134 - accuracy: 0.6626 - val_loss: 0.5739 - val_accuracy: 0.6951 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7112 - val_loss: 0.5609 - val_accuracy: 0.7020 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7223 - val_loss: 0.5537 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7286 - val_loss: 0.5459 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7361 - val_loss: 0.5370 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7405 - val_loss: 0.5409 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7459 - val_loss: 0.5359 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5003 - accuracy: 0.7489 - val_loss: 0.5359 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7560 - val_loss: 0.5405 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 10/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4879 - accuracy: 0.7586
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4880 - accuracy: 0.7583 - val_loss: 0.5403 - val_accuracy: 0.7241 - lr: 0.0010
271/271 [==============================] - 0s 665us/step
Independent Testing Matthews Correlation:  0.4453476530268078
Confusion Matrix :
 [[3046 1277]
 [1122 3201]]
Accuracy on test set:    0.722530650011566
Sensitivity:    0.7404580152671756 	 Specificity:    0.7046032847559565
Precision  : 0.7148280482358196
Area Under Curve:    0.722530650011566
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6049 - accuracy: 0.6673 - val_loss: 0.5657 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5580 - accuracy: 0.7119 - val_loss: 0.5495 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7241 - val_loss: 0.5438 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7308 - val_loss: 0.5413 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5251 - accuracy: 0.7345 - val_loss: 0.5384 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7389 - val_loss: 0.5388 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7426 - val_loss: 0.5415 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7470 - val_loss: 0.5393 - val_accuracy: 0.7319 - lr: 0.0010

Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5002 - accuracy: 0.7493 - val_loss: 0.5391 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7537 - val_loss: 0.5430 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7569 - val_loss: 0.5423 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7606 - val_loss: 0.5433 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 13/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4763 - accuracy: 0.7620
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4766 - accuracy: 0.7618 - val_loss: 0.5422 - val_accuracy: 0.7298 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.440144686584549
Confusion Matrix :
 [[3052 1271]
 [1150 3173]]
Accuracy on test set:    0.7199861207494795
Sensitivity:    0.7339810316909554 	 Specificity:    0.7059912098080037
Precision  : 0.713996399639964
Area Under Curve:    0.7199861207494795
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6075 - accuracy: 0.6663 - val_loss: 0.5690 - val_accuracy: 0.7052 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5570 - accuracy: 0.7138 - val_loss: 0.5663 - val_accuracy: 0.7035 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7254 - val_loss: 0.5436 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7308 - val_loss: 0.5395 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5247 - accuracy: 0.7360 - val_loss: 0.5376 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7390 - val_loss: 0.5406 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7428 - val_loss: 0.5413 - val_accuracy: 0.7350 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7485 - val_loss: 0.5400 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7521 - val_loss: 0.5385 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7544 - val_loss: 0.5463 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4881 - accuracy: 0.7589 - val_loss: 0.5485 - val_accuracy: 0.7343 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4781 - accuracy: 0.7626
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4787 - accuracy: 0.7620 - val_loss: 0.5412 - val_accuracy: 0.7290 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.43534138933457367
Confusion Matrix :
 [[2913 1410]
 [1038 3285]]
Accuracy on test set:    0.7168632893823733
Sensitivity:    0.7598889659958362 	 Specificity:    0.6738376127689105
Precision  : 0.6996805111821086
Area Under Curve:    0.7168632893823734
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6139 - accuracy: 0.6627 - val_loss: 0.5634 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5605 - accuracy: 0.7120 - val_loss: 0.5501 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7201 - val_loss: 0.5446 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7292 - val_loss: 0.5498 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7329 - val_loss: 0.5431 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5172 - accuracy: 0.7398 - val_loss: 0.5402 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7439 - val_loss: 0.5459 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7445 - val_loss: 0.5376 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7493 - val_loss: 0.5413 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7561 - val_loss: 0.5381 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7582 - val_loss: 0.5451 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4842 - accuracy: 0.7596 - val_loss: 0.5473 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4782 - accuracy: 0.7637 - val_loss: 0.5466 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4716 - accuracy: 0.7672 - val_loss: 0.5458 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4656 - accuracy: 0.7701 - val_loss: 0.5500 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4608 - accuracy: 0.7723 - val_loss: 0.5522 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4588 - accuracy: 0.7743 - val_loss: 0.5489 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4528 - accuracy: 0.7780 - val_loss: 0.5591 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 19/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4461 - accuracy: 0.7806
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4467 - accuracy: 0.7804 - val_loss: 0.5605 - val_accuracy: 0.7245 - lr: 0.0010
271/271 [==============================] - 0s 667us/step
Independent Testing Matthews Correlation:  0.4430478638191322
Confusion Matrix :
 [[3039 1284]
 [1125 3198]]
Accuracy on test set:    0.7213740458015268
Sensitivity:    0.739764052741152 	 Specificity:    0.7029840388619014
Precision  : 0.713520749665328
Area Under Curve:    0.7213740458015269
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6193 - accuracy: 0.6589 - val_loss: 0.5657 - val_accuracy: 0.7030 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7091 - val_loss: 0.5485 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7220 - val_loss: 0.5408 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5306 - accuracy: 0.7323 - val_loss: 0.5399 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7336 - val_loss: 0.5540 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7383 - val_loss: 0.5352 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 7/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7434 - val_loss: 0.5378 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7490 - val_loss: 0.5365 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4963 - accuracy: 0.7523 - val_loss: 0.5398 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7573 - val_loss: 0.5387 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4818 - accuracy: 0.7623 - val_loss: 0.5393 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4782 - accuracy: 0.7618 - val_loss: 0.5513 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 13/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4699 - accuracy: 0.7671
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7669 - val_loss: 0.5444 - val_accuracy: 0.7273 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.44721113354495373
Confusion Matrix :
 [[2924 1399]
 [ 999 3324]]
Accuracy on test set:    0.72264631043257
Sensitivity:    0.768910478834143 	 Specificity:    0.676382142030997
Precision  : 0.7037899640059284
Area Under Curve:    0.72264631043257
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6103 - accuracy: 0.6643 - val_loss: 0.5651 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5571 - accuracy: 0.7142 - val_loss: 0.5544 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7234 - val_loss: 0.5577 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7318 - val_loss: 0.5449 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7366 - val_loss: 0.5442 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7412 - val_loss: 0.5592 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5110 - accuracy: 0.7443 - val_loss: 0.5420 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7508 - val_loss: 0.5463 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7542 - val_loss: 0.5489 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4893 - accuracy: 0.7598 - val_loss: 0.5469 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4845 - accuracy: 0.7592 - val_loss: 0.5465 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4748 - accuracy: 0.7673
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4752 - accuracy: 0.7669 - val_loss: 0.5497 - val_accuracy: 0.7160 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.4414267801212562
Confusion Matrix :
 [[2898 1425]
 [ 999 3324]]
Accuracy on test set:    0.7196391394864677
Sensitivity:    0.768910478834143 	 Specificity:    0.6703678001387925
Precision  : 0.6999368288060644
Area Under Curve:    0.7196391394864677
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6085 - accuracy: 0.6637 - val_loss: 0.5702 - val_accuracy: 0.7005 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5600 - accuracy: 0.7112 - val_loss: 0.5513 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7210 - val_loss: 0.5476 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7300 - val_loss: 0.5458 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5256 - accuracy: 0.7358 - val_loss: 0.5434 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5210 - accuracy: 0.7380 - val_loss: 0.5475 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7435 - val_loss: 0.5376 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7448 - val_loss: 0.5386 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5022 - accuracy: 0.7504 - val_loss: 0.5415 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4950 - accuracy: 0.7550 - val_loss: 0.5492 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4898 - accuracy: 0.7569 - val_loss: 0.5462 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4840 - accuracy: 0.7599
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7602 - val_loss: 0.5391 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4563261911197001
Confusion Matrix :
 [[3205 1118]
 [1233 3090]]
Accuracy on test set:    0.7280823502197548
Sensitivity:    0.7147814018043026 	 Specificity:    0.741383298635207
Precision  : 0.7343155893536122
Area Under Curve:    0.7280823502197548
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6190 - accuracy: 0.6546 - val_loss: 0.5719 - val_accuracy: 0.6996 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5661 - accuracy: 0.7047 - val_loss: 0.5567 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5492 - accuracy: 0.7185 - val_loss: 0.5494 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7250 - val_loss: 0.5529 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5286 - accuracy: 0.7323 - val_loss: 0.5434 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7355 - val_loss: 0.5472 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7402 - val_loss: 0.5516 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7434 - val_loss: 0.5448 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7473 - val_loss: 0.5412 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7521 - val_loss: 0.5484 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7555 - val_loss: 0.5451 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4866 - accuracy: 0.7572 - val_loss: 0.5470 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 13/400
257/274 [===========================>..] - ETA: 0s - loss: 0.4775 - accuracy: 0.7632
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4778 - accuracy: 0.7631 - val_loss: 0.5500 - val_accuracy: 0.7219 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.47327854276830017
Confusion Matrix :
 [[3117 1206]
 [1072 3251]]
Accuracy on test set:    0.7365255609530419
Sensitivity:    0.7520240573675688 	 Specificity:    0.721027064538515
Precision  : 0.7294144043078303
Area Under Curve:    0.7365255609530419
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6142 - accuracy: 0.6605 - val_loss: 0.5734 - val_accuracy: 0.7005 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5669 - accuracy: 0.7062 - val_loss: 0.5589 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5484 - accuracy: 0.7212 - val_loss: 0.5615 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7270 - val_loss: 0.5524 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7309 - val_loss: 0.5483 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7372 - val_loss: 0.5498 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5187 - accuracy: 0.7392 - val_loss: 0.5491 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5144 - accuracy: 0.7411 - val_loss: 0.5477 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7473 - val_loss: 0.5540 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7496 - val_loss: 0.5496 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7516 - val_loss: 0.5479 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7560 - val_loss: 0.5542 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7610 - val_loss: 0.5630 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7654 - val_loss: 0.5589 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4719 - accuracy: 0.7671 - val_loss: 0.5592 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4663 - accuracy: 0.7715 - val_loss: 0.5625 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4629 - accuracy: 0.7726 - val_loss: 0.5690 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4554 - accuracy: 0.7772 - val_loss: 0.5650 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 19/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4479 - accuracy: 0.7808
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4483 - accuracy: 0.7807 - val_loss: 0.5743 - val_accuracy: 0.7203 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.48968734363912625
Confusion Matrix :
 [[3127 1196]
 [1012 3311]]
Accuracy on test set:    0.7446217904233171
Sensitivity:    0.7659033078880407 	 Specificity:    0.7233402729585936
Precision  : 0.7346350122032395
Area Under Curve:    0.7446217904233171
(8646, 4352) (8646,)
Mean MCC = 0.4492 + 0.0187 and Mean AUC = 0.7242 + 0.0095
Mean Sensitivity = 0.7437 + 0.0240 and Mean Specificity = 0.7048 + 0.0233 and Mean Accuracy = 0.7242 + 0.0095
Mean Precision = 0.7162 + 0.0125





Seed   : 871476
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6155 - accuracy: 0.6573 - val_loss: 0.5584 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5654 - accuracy: 0.7058 - val_loss: 0.5408 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7211 - val_loss: 0.5447 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7271 - val_loss: 0.5330 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5292 - accuracy: 0.7331 - val_loss: 0.5438 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7377 - val_loss: 0.5326 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7409 - val_loss: 0.5348 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7449 - val_loss: 0.5311 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7519 - val_loss: 0.5299 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7546 - val_loss: 0.5300 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7573 - val_loss: 0.5277 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7591 - val_loss: 0.5329 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4785 - accuracy: 0.7643
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4787 - accuracy: 0.7641 - val_loss: 0.5295 - val_accuracy: 0.7273 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4271094401316652
Confusion Matrix :
 [[2952 1371]
 [1109 3214]]
Accuracy on test set:    0.7131621559102476
Sensitivity:    0.7434651862132778 	 Specificity:    0.6828591256072172
Precision  : 0.7009814612868048
Area Under Curve:    0.7131621559102475
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5987 - accuracy: 0.6750 - val_loss: 0.5577 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5533 - accuracy: 0.7155 - val_loss: 0.5448 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7239 - val_loss: 0.5334 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7310 - val_loss: 0.5379 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7358 - val_loss: 0.5337 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5146 - accuracy: 0.7404 - val_loss: 0.5319 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7469 - val_loss: 0.5287 - val_accuracy: 0.7335 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5014 - accuracy: 0.7495 - val_loss: 0.5327 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7529 - val_loss: 0.5263 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7571 - val_loss: 0.5327 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7613 - val_loss: 0.5309 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4754 - accuracy: 0.7642
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4754 - accuracy: 0.7645 - val_loss: 0.5303 - val_accuracy: 0.7291 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4352453649603754
Confusion Matrix :
 [[3155 1168]
 [1274 3049]]
Accuracy on test set:    0.7175572519083969
Sensitivity:    0.7052972472819801 	 Specificity:    0.7298172565348138
Precision  : 0.7230258477590704
Area Under Curve:    0.7175572519083968
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5995 - accuracy: 0.6722 - val_loss: 0.5570 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5550 - accuracy: 0.7128 - val_loss: 0.5493 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7242 - val_loss: 0.5393 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5294 - accuracy: 0.7331 - val_loss: 0.5366 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5212 - accuracy: 0.7381 - val_loss: 0.5308 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7417 - val_loss: 0.5334 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7460 - val_loss: 0.5315 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7509 - val_loss: 0.5460 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7554 - val_loss: 0.5365 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4878 - accuracy: 0.7583 - val_loss: 0.5319 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4796 - accuracy: 0.7629 - val_loss: 0.5362 - val_accuracy: 0.7331 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7651 - val_loss: 0.5434 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4702 - accuracy: 0.7670 - val_loss: 0.5412 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4627 - accuracy: 0.7730 - val_loss: 0.5409 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4583 - accuracy: 0.7761 - val_loss: 0.5458 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 16/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4471 - accuracy: 0.7829
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4472 - accuracy: 0.7829 - val_loss: 0.5453 - val_accuracy: 0.7241 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4400384700707063
Confusion Matrix :
 [[3075 1248]
 [1173 3150]]
Accuracy on test set:    0.7199861207494795
Sensitivity:    0.7286606523247745 	 Specificity:    0.7113115891741846
Precision  : 0.7162346521145976
Area Under Curve:    0.7199861207494795
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.5971 - accuracy: 0.6756 - val_loss: 0.5575 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5546 - accuracy: 0.7127 - val_loss: 0.5409 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7247 - val_loss: 0.5429 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5317 - accuracy: 0.7317 - val_loss: 0.5368 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5222 - accuracy: 0.7354 - val_loss: 0.5310 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7403 - val_loss: 0.5300 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7458 - val_loss: 0.5287 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5055 - accuracy: 0.7483 - val_loss: 0.5311 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7520 - val_loss: 0.5320 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7569 - val_loss: 0.5352 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4875 - accuracy: 0.7569 - val_loss: 0.5335 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 12/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4803 - accuracy: 0.7636
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4809 - accuracy: 0.7635 - val_loss: 0.5319 - val_accuracy: 0.7296 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.4477499685130962
Confusion Matrix :
 [[3040 1283]
 [1106 3217]]
Accuracy on test set:    0.7236872542216054
Sensitivity:    0.7441591487393014 	 Specificity:    0.7032153597039094
Precision  : 0.7148888888888889
Area Under Curve:    0.7236872542216054
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6009 - accuracy: 0.6718 - val_loss: 0.5593 - val_accuracy: 0.7092 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5563 - accuracy: 0.7148 - val_loss: 0.5445 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7247 - val_loss: 0.5373 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7330 - val_loss: 0.5371 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7366 - val_loss: 0.5332 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7398 - val_loss: 0.5317 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7463 - val_loss: 0.5296 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7498 - val_loss: 0.5324 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4938 - accuracy: 0.7534 - val_loss: 0.5314 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 10/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4869 - accuracy: 0.7585 - val_loss: 0.5355 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4797 - accuracy: 0.7627 - val_loss: 0.5312 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4737 - accuracy: 0.7670 - val_loss: 0.5423 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4689 - accuracy: 0.7702 - val_loss: 0.5389 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4598 - accuracy: 0.7746
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4609 - accuracy: 0.7742 - val_loss: 0.5437 - val_accuracy: 0.7210 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.44144515024139935
Confusion Matrix :
 [[3275 1048]
 [1372 2951]]
Accuracy on test set:    0.7201017811704835
Sensitivity:    0.6826278047652093 	 Specificity:    0.7575757575757576
Precision  : 0.7379344836209052
Area Under Curve:    0.7201017811704834
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6087 - accuracy: 0.6650 - val_loss: 0.5564 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7089 - val_loss: 0.5434 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7228 - val_loss: 0.5330 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7296 - val_loss: 0.5384 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7348 - val_loss: 0.5308 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7413 - val_loss: 0.5309 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7445 - val_loss: 0.5275 - val_accuracy: 0.7334 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7478 - val_loss: 0.5310 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7522 - val_loss: 0.5327 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7564 - val_loss: 0.5353 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4850 - accuracy: 0.7584 - val_loss: 0.5357 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4766 - accuracy: 0.7656
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4764 - accuracy: 0.7657 - val_loss: 0.5373 - val_accuracy: 0.7290 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.447834701200166
Confusion Matrix :
 [[2818 1505]
 [ 901 3422]]
Accuracy on test set:    0.7217210270645386
Sensitivity:    0.7915799213509137 	 Specificity:    0.6518621327781633
Precision  : 0.6945402882078344
Area Under Curve:    0.7217210270645386
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6042 - accuracy: 0.6703 - val_loss: 0.5566 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5578 - accuracy: 0.7114 - val_loss: 0.5533 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7232 - val_loss: 0.5454 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7282 - val_loss: 0.5446 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7339 - val_loss: 0.5394 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5177 - accuracy: 0.7400 - val_loss: 0.5345 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7423 - val_loss: 0.5333 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7488 - val_loss: 0.5314 - val_accuracy: 0.7336 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5005 - accuracy: 0.7497 - val_loss: 0.5393 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4938 - accuracy: 0.7539 - val_loss: 0.5361 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7590 - val_loss: 0.5347 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4806 - accuracy: 0.7633 - val_loss: 0.5359 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4754 - accuracy: 0.7637
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7628 - val_loss: 0.5350 - val_accuracy: 0.7296 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.44361299659734044
Confusion Matrix :
 [[3060 1263]
 [1143 3180]]
Accuracy on test set:    0.7217210270645386
Sensitivity:    0.7356002775850105 	 Specificity:    0.7078417765440667
Precision  : 0.7157326130992573
Area Under Curve:    0.7217210270645384
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6097 - accuracy: 0.6598 - val_loss: 0.5619 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5595 - accuracy: 0.7116 - val_loss: 0.5528 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7211 - val_loss: 0.5420 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7283 - val_loss: 0.5383 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7350 - val_loss: 0.5377 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5207 - accuracy: 0.7388 - val_loss: 0.5447 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7425 - val_loss: 0.5366 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7455 - val_loss: 0.5389 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7516 - val_loss: 0.5407 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7559 - val_loss: 0.5457 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4855 - accuracy: 0.7609 - val_loss: 0.5415 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4795 - accuracy: 0.7644 - val_loss: 0.5478 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4754 - accuracy: 0.7689
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4754 - accuracy: 0.7688 - val_loss: 0.5525 - val_accuracy: 0.7251 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.46270409325111855
Confusion Matrix :
 [[3197 1126]
 [1197 3126]]
Accuracy on test set:    0.731320842007865
Sensitivity:    0.7231089521165857 	 Specificity:    0.7395327318991441
Precision  : 0.7351834430856068
Area Under Curve:    0.7313208420078648
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6117 - accuracy: 0.6614 - val_loss: 0.5682 - val_accuracy: 0.7026 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5635 - accuracy: 0.7091 - val_loss: 0.5573 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7213 - val_loss: 0.5581 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7273 - val_loss: 0.5410 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7305 - val_loss: 0.5422 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7367 - val_loss: 0.5453 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7393 - val_loss: 0.5350 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7431 - val_loss: 0.5405 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5065 - accuracy: 0.7473
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7467 - val_loss: 0.5400 - val_accuracy: 0.7219 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4821871633158756
Confusion Matrix :
 [[3371  952]
 [1293 3030]]
Accuracy on test set:    0.7403423548461716
Sensitivity:    0.7009021512838307 	 Specificity:    0.7797825584085126
Precision  : 0.7609241587142139
Area Under Curve:    0.7403423548461717
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6315 - accuracy: 0.6480 - val_loss: 0.5762 - val_accuracy: 0.6993 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5729 - accuracy: 0.7042 - val_loss: 0.5564 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5553 - accuracy: 0.7165 - val_loss: 0.5521 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7219 - val_loss: 0.5501 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7277 - val_loss: 0.5445 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7323 - val_loss: 0.5478 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5251 - accuracy: 0.7368 - val_loss: 0.5499 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7397 - val_loss: 0.5517 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7443 - val_loss: 0.5469 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 10/400
261/274 [===========================>..] - ETA: 0s - loss: 0.5043 - accuracy: 0.7486
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5042 - accuracy: 0.7485 - val_loss: 0.5480 - val_accuracy: 0.7182 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.5059337218478676
Confusion Matrix :
 [[3414  909]
 [1233 3090]]
Accuracy on test set:    0.7522553782095767
Sensitivity:    0.7147814018043026 	 Specificity:    0.7897293546148508
Precision  : 0.7726931732933233
Area Under Curve:    0.7522553782095767
(8646, 4352) (8646,)
Mean MCC = 0.4534 + 0.0228 and Mean AUC = 0.7262 + 0.0113
Mean Sensitivity = 0.7270 + 0.0285 and Mean Specificity = 0.7254 + 0.0407 and Mean Accuracy = 0.7262 + 0.0113
Mean Precision = 0.7272 + 0.0236





Seed   : 282431
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5982 - accuracy: 0.6735 - val_loss: 0.5575 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5533 - accuracy: 0.7138 - val_loss: 0.5462 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7270 - val_loss: 0.5422 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5295 - accuracy: 0.7333 - val_loss: 0.5406 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5204 - accuracy: 0.7397 - val_loss: 0.5360 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7410 - val_loss: 0.5460 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7459 - val_loss: 0.5419 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5006 - accuracy: 0.7498 - val_loss: 0.5386 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4942 - accuracy: 0.7549 - val_loss: 0.5343 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4875 - accuracy: 0.7601 - val_loss: 0.5370 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4820 - accuracy: 0.7607 - val_loss: 0.5396 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4726 - accuracy: 0.7682 - val_loss: 0.5439 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4689 - accuracy: 0.7716 - val_loss: 0.5459 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4637 - accuracy: 0.7729 - val_loss: 0.5454 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4571 - accuracy: 0.7764
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4582 - accuracy: 0.7758 - val_loss: 0.5456 - val_accuracy: 0.7273 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4298134555707732
Confusion Matrix :
 [[3111 1212]
 [1253 3070]]
Accuracy on test set:    0.7148970622253065
Sensitivity:    0.7101549849641453 	 Specificity:    0.7196391394864677
Precision  : 0.7169546940681925
Area Under Curve:    0.7148970622253065
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6010 - accuracy: 0.6723 - val_loss: 0.5627 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5564 - accuracy: 0.7114 - val_loss: 0.5487 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7234 - val_loss: 0.5460 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5290 - accuracy: 0.7327 - val_loss: 0.5472 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5208 - accuracy: 0.7377 - val_loss: 0.5409 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7409 - val_loss: 0.5399 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7465 - val_loss: 0.5412 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7497 - val_loss: 0.5385 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7545 - val_loss: 0.5406 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7586 - val_loss: 0.5396 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7608 - val_loss: 0.5408 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4752 - accuracy: 0.7680
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4757 - accuracy: 0.7675 - val_loss: 0.5436 - val_accuracy: 0.7199 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.438465674632906
Confusion Matrix :
 [[3060 1263]
 [1165 3158]]
Accuracy on test set:    0.719176497802452
Sensitivity:    0.7305112190608374 	 Specificity:    0.7078417765440667
Precision  : 0.7143180275955666
Area Under Curve:    0.719176497802452
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6136 - accuracy: 0.6610 - val_loss: 0.5673 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5613 - accuracy: 0.7108 - val_loss: 0.5476 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7220 - val_loss: 0.5404 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7298 - val_loss: 0.5418 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5279 - accuracy: 0.7347 - val_loss: 0.5338 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5204 - accuracy: 0.7385 - val_loss: 0.5323 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7427 - val_loss: 0.5346 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7446 - val_loss: 0.5342 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7482 - val_loss: 0.5366 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7519 - val_loss: 0.5473 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 11/400
263/274 [===========================>..] - ETA: 0s - loss: 0.4922 - accuracy: 0.7540
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7538 - val_loss: 0.5412 - val_accuracy: 0.7256 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.45026013484947774
Confusion Matrix :
 [[2970 1353]
 [1029 3294]]
Accuracy on test set:    0.7244968771686329
Sensitivity:    0.761970853573907 	 Specificity:    0.6870229007633588
Precision  : 0.7088444157520981
Area Under Curve:    0.7244968771686329
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6041 - accuracy: 0.6687 - val_loss: 0.5647 - val_accuracy: 0.7029 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7115 - val_loss: 0.5479 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7238 - val_loss: 0.5372 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7310 - val_loss: 0.5396 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7352 - val_loss: 0.5328 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7397 - val_loss: 0.5325 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5130 - accuracy: 0.7432 - val_loss: 0.5324 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5052 - accuracy: 0.7490 - val_loss: 0.5393 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7512 - val_loss: 0.5368 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4963 - accuracy: 0.7533
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4964 - accuracy: 0.7531 - val_loss: 0.5325 - val_accuracy: 0.7305 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.4514616751796715
Confusion Matrix :
 [[3249 1074]
 [1300 3023]]
Accuracy on test set:    0.7254221605366643
Sensitivity:    0.6992829053897757 	 Specificity:    0.7515614156835531
Precision  : 0.7378569685135465
Area Under Curve:    0.7254221605366644
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6090 - accuracy: 0.6643 - val_loss: 0.5646 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5589 - accuracy: 0.7124 - val_loss: 0.5479 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7226 - val_loss: 0.5401 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7306 - val_loss: 0.5314 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7373 - val_loss: 0.5337 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7418 - val_loss: 0.5435 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7466 - val_loss: 0.5296 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5012 - accuracy: 0.7509 - val_loss: 0.5260 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7547 - val_loss: 0.5282 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7572 - val_loss: 0.5293 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4827 - accuracy: 0.7625 - val_loss: 0.5499 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4768 - accuracy: 0.7649 - val_loss: 0.5326 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4719 - accuracy: 0.7664
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4723 - accuracy: 0.7663 - val_loss: 0.5336 - val_accuracy: 0.7195 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.4339419119826502
Confusion Matrix :
 [[3327  996]
 [1462 2861]]
Accuracy on test set:    0.715706685172334
Sensitivity:    0.6618089289845015 	 Specificity:    0.7696044413601666
Precision  : 0.7417682136375421
Area Under Curve:    0.715706685172334
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6030 - accuracy: 0.6688 - val_loss: 0.5614 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5568 - accuracy: 0.7131 - val_loss: 0.5437 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7218 - val_loss: 0.5358 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7287 - val_loss: 0.5351 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7345 - val_loss: 0.5335 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7420 - val_loss: 0.5368 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7424 - val_loss: 0.5318 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7476 - val_loss: 0.5290 - val_accuracy: 0.7349 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5003 - accuracy: 0.7508 - val_loss: 0.5294 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7554 - val_loss: 0.5342 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4869 - accuracy: 0.7611 - val_loss: 0.5400 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4797 - accuracy: 0.7644 - val_loss: 0.5341 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4727 - accuracy: 0.7701
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4730 - accuracy: 0.7698 - val_loss: 0.5362 - val_accuracy: 0.7286 - lr: 0.0010
271/271 [==============================] - 0s 636us/step
Independent Testing Matthews Correlation:  0.4303352232175801
Confusion Matrix :
 [[3009 1314]
 [1150 3173]]
Accuracy on test set:    0.7150127226463104
Sensitivity:    0.7339810316909554 	 Specificity:    0.6960444136016655
Precision  : 0.7071540004457321
Area Under Curve:    0.7150127226463104
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6051 - accuracy: 0.6703 - val_loss: 0.5684 - val_accuracy: 0.7041 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7135 - val_loss: 0.5474 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7228 - val_loss: 0.5472 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7280 - val_loss: 0.5429 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7362 - val_loss: 0.5392 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5168 - accuracy: 0.7416 - val_loss: 0.5403 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7452 - val_loss: 0.5498 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7495 - val_loss: 0.5368 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7534 - val_loss: 0.5411 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7564 - val_loss: 0.5337 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4858 - accuracy: 0.7590 - val_loss: 0.5376 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4810 - accuracy: 0.7627 - val_loss: 0.5390 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4744 - accuracy: 0.7658 - val_loss: 0.5504 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4685 - accuracy: 0.7690
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4687 - accuracy: 0.7687 - val_loss: 0.5440 - val_accuracy: 0.7197 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.4666422703846993
Confusion Matrix :
 [[3011 1312]
 [ 999 3324]]
Accuracy on test set:    0.7327087670599121
Sensitivity:    0.768910478834143 	 Specificity:    0.6965070552856812
Precision  : 0.7169974115616912
Area Under Curve:    0.7327087670599121
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6015 - accuracy: 0.6708 - val_loss: 0.5613 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7130 - val_loss: 0.5539 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7215 - val_loss: 0.5446 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7298 - val_loss: 0.5460 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7357 - val_loss: 0.5373 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7389 - val_loss: 0.5402 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7443 - val_loss: 0.5346 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7476 - val_loss: 0.5401 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7539 - val_loss: 0.5346 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7544 - val_loss: 0.5376 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7584 - val_loss: 0.5381 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4816 - accuracy: 0.7632 - val_loss: 0.5365 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4795 - accuracy: 0.7652 - val_loss: 0.5364 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 14/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4709 - accuracy: 0.7687 - val_loss: 0.5383 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4652 - accuracy: 0.7722 - val_loss: 0.5416 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4593 - accuracy: 0.7772 - val_loss: 0.5424 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4556 - accuracy: 0.7767 - val_loss: 0.5485 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4478 - accuracy: 0.7820 - val_loss: 0.5530 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 19/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4409 - accuracy: 0.7847
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4410 - accuracy: 0.7843 - val_loss: 0.5561 - val_accuracy: 0.7290 - lr: 0.0010
271/271 [==============================] - 1s 662us/step
Independent Testing Matthews Correlation:  0.4648893327060813
Confusion Matrix :
 [[3016 1307]
 [1011 3312]]
Accuracy on test set:    0.7318991441128846
Sensitivity:    0.7661346287300486 	 Specificity:    0.6976636594957205
Precision  : 0.7170383199826802
Area Under Curve:    0.7318991441128847
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6187 - accuracy: 0.6568 - val_loss: 0.5676 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5647 - accuracy: 0.7073 - val_loss: 0.5544 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7216 - val_loss: 0.5473 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7286 - val_loss: 0.5463 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5268 - accuracy: 0.7331 - val_loss: 0.5387 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7390 - val_loss: 0.5381 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7439 - val_loss: 0.5384 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7471 - val_loss: 0.5379 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7487 - val_loss: 0.5403 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7533 - val_loss: 0.5411 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4861 - accuracy: 0.7586 - val_loss: 0.5508 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4802 - accuracy: 0.7620 - val_loss: 0.5447 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 13/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4726 - accuracy: 0.7677
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4731 - accuracy: 0.7668 - val_loss: 0.5412 - val_accuracy: 0.7233 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.48715752521629824
Confusion Matrix :
 [[3148 1175]
 [1043 3280]]
Accuracy on test set:    0.7434651862132778
Sensitivity:    0.758732361785797 	 Specificity:    0.7281980106407587
Precision  : 0.7362514029180696
Area Under Curve:    0.7434651862132778
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6151 - accuracy: 0.6586 - val_loss: 0.5839 - val_accuracy: 0.6925 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5670 - accuracy: 0.7049 - val_loss: 0.5600 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5506 - accuracy: 0.7175 - val_loss: 0.5498 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7242 - val_loss: 0.5460 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7311 - val_loss: 0.5460 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5262 - accuracy: 0.7334 - val_loss: 0.5416 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5190 - accuracy: 0.7394 - val_loss: 0.5443 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7429 - val_loss: 0.5467 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5044 - accuracy: 0.7484
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7482 - val_loss: 0.5494 - val_accuracy: 0.7134 - lr: 0.0010
271/271 [==============================] - 0s 637us/step
Independent Testing Matthews Correlation:  0.4704388735576585
Confusion Matrix :
 [[3235 1088]
 [1202 3121]]
Accuracy on test set:    0.7351376359009947
Sensitivity:    0.7219523479065464 	 Specificity:    0.748322923895443
Precision  : 0.7415062960323117
Area Under Curve:    0.7351376359009947
(8646, 4352) (8646,)
Mean MCC = 0.4523 + 0.0185 and Mean AUC = 0.7258 + 0.0093
Mean Sensitivity = 0.7313 + 0.0327 and Mean Specificity = 0.7202 + 0.0268 and Mean Accuracy = 0.7258 + 0.0093
Mean Precision = 0.7239 + 0.0131





Seed   : 778614
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6101 - accuracy: 0.6639 - val_loss: 0.5633 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5593 - accuracy: 0.7119 - val_loss: 0.5415 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7222 - val_loss: 0.5366 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7278 - val_loss: 0.5372 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7337 - val_loss: 0.5313 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7389 - val_loss: 0.5334 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7412 - val_loss: 0.5316 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7466 - val_loss: 0.5281 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7497 - val_loss: 0.5324 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4954 - accuracy: 0.7530 - val_loss: 0.5294 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7584 - val_loss: 0.5318 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7618 - val_loss: 0.5290 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4780 - accuracy: 0.7641 - val_loss: 0.5302 - val_accuracy: 0.7232 - lr: 0.0010

Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4713 - accuracy: 0.7682 - val_loss: 0.5407 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7679 - val_loss: 0.5405 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 16/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4618 - accuracy: 0.7723
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4622 - accuracy: 0.7723 - val_loss: 0.5425 - val_accuracy: 0.7159 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.415456244922398
Confusion Matrix :
 [[3069 1254]
 [1273 3050]]
Accuracy on test set:    0.7077261161230627
Sensitivity:    0.705528568123988 	 Specificity:    0.7099236641221374
Precision  : 0.7086431226765799
Area Under Curve:    0.7077261161230627
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6103 - accuracy: 0.6604 - val_loss: 0.5624 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5598 - accuracy: 0.7115 - val_loss: 0.5550 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7237 - val_loss: 0.5386 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7310 - val_loss: 0.5495 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7337 - val_loss: 0.5367 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5190 - accuracy: 0.7382 - val_loss: 0.5360 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5106 - accuracy: 0.7448 - val_loss: 0.5338 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7474 - val_loss: 0.5342 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4973 - accuracy: 0.7533 - val_loss: 0.5381 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7563 - val_loss: 0.5457 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7592 - val_loss: 0.5441 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4781 - accuracy: 0.7636
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4787 - accuracy: 0.7635 - val_loss: 0.5373 - val_accuracy: 0.7256 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4406933704137507
Confusion Matrix :
 [[3090 1233]
 [1185 3138]]
Accuracy on test set:    0.7203331020124913
Sensitivity:    0.7258848022206801 	 Specificity:    0.7147814018043026
Precision  : 0.7179135209334249
Area Under Curve:    0.7203331020124915
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6121 - accuracy: 0.6620 - val_loss: 0.5662 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5633 - accuracy: 0.7088 - val_loss: 0.5467 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7196 - val_loss: 0.5423 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7270 - val_loss: 0.5363 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5303 - accuracy: 0.7313 - val_loss: 0.5326 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7364 - val_loss: 0.5330 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7392 - val_loss: 0.5354 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7433 - val_loss: 0.5359 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7447 - val_loss: 0.5368 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5037 - accuracy: 0.7492 - val_loss: 0.5367 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7520 - val_loss: 0.5413 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7551 - val_loss: 0.5354 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4873 - accuracy: 0.7574 - val_loss: 0.5396 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4803 - accuracy: 0.7615
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7619 - val_loss: 0.5409 - val_accuracy: 0.7249 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.4546161553951246
Confusion Matrix :
 [[2999 1324]
 [1038 3285]]
Accuracy on test set:    0.7268100855887115
Sensitivity:    0.7598889659958362 	 Specificity:    0.6937312051815868
Precision  : 0.7127359513994359
Area Under Curve:    0.7268100855887116
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6058 - accuracy: 0.6688 - val_loss: 0.5531 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5593 - accuracy: 0.7102 - val_loss: 0.5460 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7266 - val_loss: 0.5394 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7300 - val_loss: 0.5349 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7374 - val_loss: 0.5385 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7412 - val_loss: 0.5336 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7442 - val_loss: 0.5308 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7501 - val_loss: 0.5318 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7512 - val_loss: 0.5375 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7586 - val_loss: 0.5386 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4834 - accuracy: 0.7597 - val_loss: 0.5429 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4797 - accuracy: 0.7631 - val_loss: 0.5392 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4705 - accuracy: 0.7700
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

274/274 [==============================] - 1s 2ms/step - loss: 0.4715 - accuracy: 0.7691 - val_loss: 0.5373 - val_accuracy: 0.7199 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.422597378700828
Confusion Matrix :
 [[3195 1128]
 [1371 2952]]
Accuracy on test set:    0.7109646079111728
Sensitivity:    0.6828591256072172 	 Specificity:    0.7390700902151284
Precision  : 0.7235294117647059
Area Under Curve:    0.7109646079111728
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6073 - accuracy: 0.6637 - val_loss: 0.5646 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5595 - accuracy: 0.7117 - val_loss: 0.5441 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7218 - val_loss: 0.5454 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7297 - val_loss: 0.5384 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5261 - accuracy: 0.7355 - val_loss: 0.5423 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5214 - accuracy: 0.7375 - val_loss: 0.5375 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7409 - val_loss: 0.5348 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7471 - val_loss: 0.5403 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7514 - val_loss: 0.5377 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7515 - val_loss: 0.5390 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7532 - val_loss: 0.5429 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 12/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4840 - accuracy: 0.7603
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4842 - accuracy: 0.7601 - val_loss: 0.5419 - val_accuracy: 0.7170 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4370645139334533
Confusion Matrix :
 [[2911 1412]
 [1029 3294]]
Accuracy on test set:    0.7176729123294009
Sensitivity:    0.761970853573907 	 Specificity:    0.6733749710848947
Precision  : 0.6999575010624735
Area Under Curve:    0.7176729123294008
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6032 - accuracy: 0.6696 - val_loss: 0.5633 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5582 - accuracy: 0.7121 - val_loss: 0.5422 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7219 - val_loss: 0.5426 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7304 - val_loss: 0.5419 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7358 - val_loss: 0.5348 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7394 - val_loss: 0.5384 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5110 - accuracy: 0.7458 - val_loss: 0.5352 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5055 - accuracy: 0.7486 - val_loss: 0.5375 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7515 - val_loss: 0.5394 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4938 - accuracy: 0.7552 - val_loss: 0.5426 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7577 - val_loss: 0.5373 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4822 - accuracy: 0.7622
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4822 - accuracy: 0.7623 - val_loss: 0.5412 - val_accuracy: 0.7289 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.44373852767747224
Confusion Matrix :
 [[3041 1282]
 [1124 3199]]
Accuracy on test set:    0.7217210270645386
Sensitivity:    0.7399953735831598 	 Specificity:    0.7034466805459172
Precision  : 0.7139031466190583
Area Under Curve:    0.7217210270645386
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6032 - accuracy: 0.6706 - val_loss: 0.5648 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5563 - accuracy: 0.7143 - val_loss: 0.5571 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7226 - val_loss: 0.5499 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5307 - accuracy: 0.7314 - val_loss: 0.5523 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7376 - val_loss: 0.5575 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5167 - accuracy: 0.7423 - val_loss: 0.5460 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7458 - val_loss: 0.5428 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7492 - val_loss: 0.5449 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7542 - val_loss: 0.5446 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4910 - accuracy: 0.7579 - val_loss: 0.5485 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7611 - val_loss: 0.5494 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4781 - accuracy: 0.7648 - val_loss: 0.5508 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4705 - accuracy: 0.7698 - val_loss: 0.5489 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4644 - accuracy: 0.7735 - val_loss: 0.5532 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 15/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4588 - accuracy: 0.7772
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4594 - accuracy: 0.7766 - val_loss: 0.5542 - val_accuracy: 0.7210 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4490191753225007
Confusion Matrix :
 [[3155 1168]
 [1214 3109]]
Accuracy on test set:    0.7244968771686329
Sensitivity:    0.719176497802452 	 Specificity:    0.7298172565348138
Precision  : 0.7269113864858545
Area Under Curve:    0.7244968771686329
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6043 - accuracy: 0.6696 - val_loss: 0.5641 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5586 - accuracy: 0.7132 - val_loss: 0.5590 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7239 - val_loss: 0.5578 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7287 - val_loss: 0.5489 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5251 - accuracy: 0.7346 - val_loss: 0.5518 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5208 - accuracy: 0.7375 - val_loss: 0.5418 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5137 - accuracy: 0.7419 - val_loss: 0.5385 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7464 - val_loss: 0.5405 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5003 - accuracy: 0.7503 - val_loss: 0.5467 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7544 - val_loss: 0.5443 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7554 - val_loss: 0.5419 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7615 - val_loss: 0.5470 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4782 - accuracy: 0.7620 - val_loss: 0.5502 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4756 - accuracy: 0.7660 - val_loss: 0.5484 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4696 - accuracy: 0.7676 - val_loss: 0.5512 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4645 - accuracy: 0.7716
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4647 - accuracy: 0.7713 - val_loss: 0.5575 - val_accuracy: 0.7178 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.46137274455969884
Confusion Matrix :
 [[3049 1274]
 [1057 3266]]
Accuracy on test set:    0.7303955586398334
Sensitivity:    0.7554938699976868 	 Specificity:    0.7052972472819801
Precision  : 0.7193832599118942
Area Under Curve:    0.7303955586398334
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6117 - accuracy: 0.6626 - val_loss: 0.5719 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5655 - accuracy: 0.7074 - val_loss: 0.5564 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5488 - accuracy: 0.7181 - val_loss: 0.5526 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7263 - val_loss: 0.5501 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7318 - val_loss: 0.5458 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7359 - val_loss: 0.5442 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7401 - val_loss: 0.5459 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7430 - val_loss: 0.5418 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5056 - accuracy: 0.7472 - val_loss: 0.5450 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7534 - val_loss: 0.5474 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7550 - val_loss: 0.5463 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4894 - accuracy: 0.7552
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7555 - val_loss: 0.5486 - val_accuracy: 0.7213 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4696265687642082
Confusion Matrix :
 [[3276 1047]
 [1248 3075]]
Accuracy on test set:    0.734559333795975
Sensitivity:    0.7113115891741846 	 Specificity:    0.7578070784177654
Precision  : 0.7459970887918487
Area Under Curve:    0.734559333795975
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6067 - accuracy: 0.6673 - val_loss: 0.5714 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5644 - accuracy: 0.7086 - val_loss: 0.5716 - val_accuracy: 0.7017 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5505 - accuracy: 0.7177 - val_loss: 0.5523 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7247 - val_loss: 0.5475 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7313 - val_loss: 0.5457 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7356 - val_loss: 0.5430 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7396 - val_loss: 0.5435 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7446 - val_loss: 0.5424 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7470 - val_loss: 0.5434 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5003 - accuracy: 0.7501 - val_loss: 0.5433 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4950 - accuracy: 0.7538 - val_loss: 0.5505 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7584 - val_loss: 0.5445 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4834 - accuracy: 0.7612 - val_loss: 0.5540 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4761 - accuracy: 0.7656 - val_loss: 0.5534 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4682 - accuracy: 0.7693
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4685 - accuracy: 0.7689 - val_loss: 0.5520 - val_accuracy: 0.7200 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.5095681387272224
Confusion Matrix :
 [[3323 1000]
 [1121 3202]]
Accuracy on test set:    0.7546842470506593
Sensitivity:    0.7406893361091834 	 Specificity:    0.768679157992135
Precision  : 0.7620180866254165
Area Under Curve:    0.7546842470506592
(8646, 4352) (8646,)
Mean MCC = 0.4504 + 0.0251 and Mean AUC = 0.7249 + 0.0126
Mean Sensitivity = 0.7303 + 0.0247 and Mean Specificity = 0.7196 + 0.0278 and Mean Accuracy = 0.7249 + 0.0126
Mean Precision = 0.7231 + 0.0174





Seed   : 328920

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6074 - accuracy: 0.6683 - val_loss: 0.5637 - val_accuracy: 0.6998 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5564 - accuracy: 0.7138 - val_loss: 0.5454 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7216 - val_loss: 0.5426 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7315 - val_loss: 0.5368 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7350 - val_loss: 0.5354 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7397 - val_loss: 0.5354 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7422 - val_loss: 0.5431 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7468 - val_loss: 0.5325 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7522 - val_loss: 0.5365 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4926 - accuracy: 0.7563
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7557 - val_loss: 0.5378 - val_accuracy: 0.7197 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4103079219468853
Confusion Matrix :
 [[2794 1529]
 [1032 3291]]
Accuracy on test set:    0.703793661808929
Sensitivity:    0.7612768910478834 	 Specificity:    0.6463104325699746
Precision  : 0.6827800829875519
Area Under Curve:    0.7037936618089291
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6149 - accuracy: 0.6624 - val_loss: 0.5660 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7101 - val_loss: 0.5652 - val_accuracy: 0.6964 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7209 - val_loss: 0.5467 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7290 - val_loss: 0.5408 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7344 - val_loss: 0.5543 - val_accuracy: 0.7048 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7392 - val_loss: 0.5373 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5141 - accuracy: 0.7426 - val_loss: 0.5450 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7465 - val_loss: 0.5374 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7520 - val_loss: 0.5352 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4929 - accuracy: 0.7575 - val_loss: 0.5374 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4876 - accuracy: 0.7584
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4878 - accuracy: 0.7587 - val_loss: 0.5393 - val_accuracy: 0.7204 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4381222491321798
Confusion Matrix :
 [[3105 1218]
 [1211 3112]]
Accuracy on test set:    0.7190608373814481
Sensitivity:    0.7198704603284756 	 Specificity:    0.7182512144344205
Precision  : 0.7187066974595843
Area Under Curve:    0.719060837381448
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6027 - accuracy: 0.6710 - val_loss: 0.5640 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5557 - accuracy: 0.7141 - val_loss: 0.5468 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7260 - val_loss: 0.5532 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5310 - accuracy: 0.7298 - val_loss: 0.5391 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7368 - val_loss: 0.5381 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7431 - val_loss: 0.5373 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7451 - val_loss: 0.5340 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7507 - val_loss: 0.5420 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4962 - accuracy: 0.7516
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4961 - accuracy: 0.7516 - val_loss: 0.5368 - val_accuracy: 0.7256 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.45944853350425446
Confusion Matrix :
 [[3229 1094]
 [1244 3079]]
Accuracy on test set:    0.7295859356928059
Sensitivity:    0.712236872542216 	 Specificity:    0.7469349988433958
Precision  : 0.7378384855020369
Area Under Curve:    0.7295859356928058
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6212 - accuracy: 0.6555 - val_loss: 0.5696 - val_accuracy: 0.7021 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5625 - accuracy: 0.7106 - val_loss: 0.5519 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5480 - accuracy: 0.7217 - val_loss: 0.5445 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7283 - val_loss: 0.5421 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7335 - val_loss: 0.5396 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7388 - val_loss: 0.5371 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7429 - val_loss: 0.5367 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7467 - val_loss: 0.5360 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7486 - val_loss: 0.5375 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7548 - val_loss: 0.5378 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4890 - accuracy: 0.7605 - val_loss: 0.5388 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4852 - accuracy: 0.7595
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7597 - val_loss: 0.5354 - val_accuracy: 0.7265 - lr: 0.0010

271/271 [==============================] - 0s 669us/step
Independent Testing Matthews Correlation:  0.4286788111994289
Confusion Matrix :
 [[3118 1205]
 [1265 3058]]
Accuracy on test set:    0.7143187601202868
Sensitivity:    0.7073791348600509 	 Specificity:    0.7212583853805228
Precision  : 0.7173352099460474
Area Under Curve:    0.7143187601202868
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6039 - accuracy: 0.6704 - val_loss: 0.5682 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5589 - accuracy: 0.7110 - val_loss: 0.5508 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7220 - val_loss: 0.5446 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7251 - val_loss: 0.5428 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5295 - accuracy: 0.7327 - val_loss: 0.5362 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.7367 - val_loss: 0.5393 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7398 - val_loss: 0.5409 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5122 - accuracy: 0.7423 - val_loss: 0.5432 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5073 - accuracy: 0.7457 - val_loss: 0.5351 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7491 - val_loss: 0.5346 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4961 - accuracy: 0.7508 - val_loss: 0.5393 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7578 - val_loss: 0.5471 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7576 - val_loss: 0.5489 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4805 - accuracy: 0.7602
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7601 - val_loss: 0.5397 - val_accuracy: 0.7250 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4383228781664475
Confusion Matrix :
 [[3204 1119]
 [1311 3012]]
Accuracy on test set:    0.7189451769604441
Sensitivity:    0.6967383761276891 	 Specificity:    0.7411519777931992
Precision  : 0.729121278140886
Area Under Curve:    0.7189451769604441
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6067 - accuracy: 0.6640 - val_loss: 0.5876 - val_accuracy: 0.6803 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7135 - val_loss: 0.5477 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7249 - val_loss: 0.5431 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7310 - val_loss: 0.5399 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5225 - accuracy: 0.7376 - val_loss: 0.5400 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5149 - accuracy: 0.7401 - val_loss: 0.5404 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7476 - val_loss: 0.5372 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7503 - val_loss: 0.5372 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7557 - val_loss: 0.5418 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4860 - accuracy: 0.7594 - val_loss: 0.5466 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4788 - accuracy: 0.7627 - val_loss: 0.5410 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4739 - accuracy: 0.7665 - val_loss: 0.5422 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4658 - accuracy: 0.7713 - val_loss: 0.5531 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4592 - accuracy: 0.7749 - val_loss: 0.5550 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4531 - accuracy: 0.7789 - val_loss: 0.5556 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4459 - accuracy: 0.7830
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4467 - accuracy: 0.7823 - val_loss: 0.5554 - val_accuracy: 0.7206 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4291882711933144
Confusion Matrix :
 [[2922 1401]
 [1072 3251]]
Accuracy on test set:    0.713971778857275
Sensitivity:    0.7520240573675688 	 Specificity:    0.6759195003469812
Precision  : 0.6988392089423904
Area Under Curve:    0.7139717788572753
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6028 - accuracy: 0.6681 - val_loss: 0.5637 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5558 - accuracy: 0.7144 - val_loss: 0.5511 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7222 - val_loss: 0.5482 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7293 - val_loss: 0.5423 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5249 - accuracy: 0.7348 - val_loss: 0.5411 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7386 - val_loss: 0.5402 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5112 - accuracy: 0.7434 - val_loss: 0.5416 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7472 - val_loss: 0.5373 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4987 - accuracy: 0.7522 - val_loss: 0.5433 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7542 - val_loss: 0.5442 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4869 - accuracy: 0.7581 - val_loss: 0.5439 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4799 - accuracy: 0.7633 - val_loss: 0.5546 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4754 - accuracy: 0.7670 - val_loss: 0.5473 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4661 - accuracy: 0.7714 - val_loss: 0.5566 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4622 - accuracy: 0.7727 - val_loss: 0.5615 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4535 - accuracy: 0.7783
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4542 - accuracy: 0.7780 - val_loss: 0.5550 - val_accuracy: 0.7194 - lr: 0.0010
271/271 [==============================] - 0s 665us/step
Independent Testing Matthews Correlation:  0.44205796107827977
Confusion Matrix :
 [[3126 1197]
 [1215 3108]]
Accuracy on test set:    0.721027064538515
Sensitivity:    0.7189451769604441 	 Specificity:    0.7231089521165857
Precision  : 0.7219512195121951
Area Under Curve:    0.721027064538515
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6075 - accuracy: 0.6657 - val_loss: 0.5634 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5577 - accuracy: 0.7135 - val_loss: 0.5632 - val_accuracy: 0.6998 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7223 - val_loss: 0.5474 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7297 - val_loss: 0.5541 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5264 - accuracy: 0.7334 - val_loss: 0.5441 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5192 - accuracy: 0.7402 - val_loss: 0.5408 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7416 - val_loss: 0.5475 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7451 - val_loss: 0.5378 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7499 - val_loss: 0.5429 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7558 - val_loss: 0.5412 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7582 - val_loss: 0.5430 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7633 - val_loss: 0.5455 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4771 - accuracy: 0.7646
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4774 - accuracy: 0.7645 - val_loss: 0.5468 - val_accuracy: 0.7263 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4599791042101551
Confusion Matrix :
 [[3026 1297]
 [1041 3282]]
Accuracy on test set:    0.7295859356928059
Sensitivity:    0.7591950034698126 	 Specificity:    0.6999768679157992
Precision  : 0.7167503821795151
Area Under Curve:    0.7295859356928058
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6023 - accuracy: 0.6724 - val_loss: 0.5611 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7100 - val_loss: 0.5631 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7197 - val_loss: 0.5557 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7277 - val_loss: 0.5448 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7348 - val_loss: 0.5468 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5202 - accuracy: 0.7384 - val_loss: 0.5454 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7412 - val_loss: 0.5406 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7449 - val_loss: 0.5497 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7514 - val_loss: 0.5394 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7543 - val_loss: 0.5437 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4883 - accuracy: 0.7580 - val_loss: 0.5463 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4852 - accuracy: 0.7604 - val_loss: 0.5451 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4763 - accuracy: 0.7645 - val_loss: 0.5522 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4740 - accuracy: 0.7675 - val_loss: 0.5515 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4648 - accuracy: 0.7731
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4653 - accuracy: 0.7732 - val_loss: 0.5527 - val_accuracy: 0.7222 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.47403165371879225
Confusion Matrix :
 [[3153 1170]
 [1104 3219]]
Accuracy on test set:    0.7369882026370576
Sensitivity:    0.7446217904233171 	 Specificity:    0.7293546148507981
Precision  : 0.7334244702665755
Area Under Curve:    0.7369882026370576
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6138 - accuracy: 0.6597 - val_loss: 0.5700 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5671 - accuracy: 0.7077 - val_loss: 0.5556 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5513 - accuracy: 0.7183 - val_loss: 0.5476 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7239 - val_loss: 0.5457 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7296 - val_loss: 0.5488 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5249 - accuracy: 0.7343 - val_loss: 0.5402 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7400 - val_loss: 0.5472 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7421 - val_loss: 0.5448 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7455 - val_loss: 0.5470 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5014 - accuracy: 0.7497 - val_loss: 0.5502 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 11/400
264/274 [===========================>..] - ETA: 0s - loss: 0.4961 - accuracy: 0.7521
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7521 - val_loss: 0.5476 - val_accuracy: 0.7227 - lr: 0.0010

271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.4986583824952697
Confusion Matrix :
 [[3429  894]
 [1282 3041]]
Accuracy on test set:    0.748322923895443
Sensitivity:    0.7034466805459172 	 Specificity:    0.7931991672449688
Precision  : 0.7728081321473952
Area Under Curve:    0.748322923895443
(8646, 4352) (8646,)
Mean MCC = 0.4479 + 0.0243 and Mean AUC = 0.7236 + 0.0122
Mean Sensitivity = 0.7276 + 0.0231 and Mean Specificity = 0.7195 + 0.0380 and Mean Accuracy = 0.7236 + 0.0122
Mean Precision = 0.7230 + 0.0227





Seed   : 892793
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6074 - accuracy: 0.6649 - val_loss: 0.5626 - val_accuracy: 0.7048 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7097 - val_loss: 0.5489 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7232 - val_loss: 0.5452 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7285 - val_loss: 0.5404 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7362 - val_loss: 0.5387 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7400 - val_loss: 0.5373 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7442 - val_loss: 0.5385 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7463 - val_loss: 0.5483 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7499 - val_loss: 0.5369 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7557 - val_loss: 0.5394 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7568 - val_loss: 0.5399 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4821 - accuracy: 0.7607 - val_loss: 0.5442 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4760 - accuracy: 0.7633 - val_loss: 0.5431 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4717 - accuracy: 0.7647
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4717 - accuracy: 0.7651 - val_loss: 0.5432 - val_accuracy: 0.7265 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.42948347399501186
Confusion Matrix :
 [[3032 1291]
 [1176 3147]]
Accuracy on test set:    0.7146657413832986
Sensitivity:    0.7279666897987509 	 Specificity:    0.7013647929678464
Precision  : 0.7091031996394772
Area Under Curve:    0.7146657413832986
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6121 - accuracy: 0.6644 - val_loss: 0.5715 - val_accuracy: 0.6992 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5582 - accuracy: 0.7111 - val_loss: 0.5563 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7254 - val_loss: 0.5439 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7294 - val_loss: 0.5470 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7363 - val_loss: 0.5436 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5168 - accuracy: 0.7388 - val_loss: 0.5424 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7440 - val_loss: 0.5458 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7479 - val_loss: 0.5456 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7526 - val_loss: 0.5511 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7581 - val_loss: 0.5402 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4844 - accuracy: 0.7601 - val_loss: 0.5468 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7632 - val_loss: 0.5459 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4738 - accuracy: 0.7671 - val_loss: 0.5526 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4652 - accuracy: 0.7706 - val_loss: 0.5591 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4602 - accuracy: 0.7733 - val_loss: 0.5583 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4514 - accuracy: 0.7782
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4517 - accuracy: 0.7781 - val_loss: 0.5570 - val_accuracy: 0.7215 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4326959051596287
Confusion Matrix :
 [[2962 1361]
 [1095 3228]]
Accuracy on test set:    0.7159380060143419
Sensitivity:    0.7467036780013879 	 Specificity:    0.6851723340272958
Precision  : 0.7034212246676836
Area Under Curve:    0.715938006014342
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6134 - accuracy: 0.6591 - val_loss: 0.5662 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7126 - val_loss: 0.5542 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7225 - val_loss: 0.5546 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7315 - val_loss: 0.5440 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7365 - val_loss: 0.5501 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7415 - val_loss: 0.5399 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7454 - val_loss: 0.5375 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7489 - val_loss: 0.5605 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7512 - val_loss: 0.5390 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4910 - accuracy: 0.7559 - val_loss: 0.5388 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.7594 - val_loss: 0.5435 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4776 - accuracy: 0.7635
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

274/274 [==============================] - 1s 2ms/step - loss: 0.4775 - accuracy: 0.7635 - val_loss: 0.5437 - val_accuracy: 0.7178 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.42842127027075
Confusion Matrix :
 [[2882 1441]
 [1038 3285]]
Accuracy on test set:    0.7132778163312514
Sensitivity:    0.7598889659958362 	 Specificity:    0.6666666666666666
Precision  : 0.6950909860347017
Area Under Curve:    0.7132778163312516
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6010 - accuracy: 0.6734 - val_loss: 0.5593 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5517 - accuracy: 0.7171 - val_loss: 0.5507 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7265 - val_loss: 0.5444 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7342 - val_loss: 0.5459 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5212 - accuracy: 0.7379 - val_loss: 0.5450 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7409 - val_loss: 0.5463 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7470 - val_loss: 0.5433 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5014 - accuracy: 0.7503 - val_loss: 0.5491 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7534 - val_loss: 0.5415 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4922 - accuracy: 0.7553 - val_loss: 0.5447 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4836 - accuracy: 0.7610 - val_loss: 0.5469 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4764 - accuracy: 0.7670
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4766 - accuracy: 0.7670 - val_loss: 0.5571 - val_accuracy: 0.7173 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.4451898578408855
Confusion Matrix :
 [[2871 1452]
 [ 959 3364]]
Accuracy on test set:    0.7211427249595188
Sensitivity:    0.7781633125144576 	 Specificity:    0.6641221374045801
Precision  : 0.6985049833887044
Area Under Curve:    0.7211427249595188
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6127 - accuracy: 0.6626 - val_loss: 0.5638 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7106 - val_loss: 0.5557 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7233 - val_loss: 0.5470 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7281 - val_loss: 0.5430 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7344 - val_loss: 0.5404 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7393 - val_loss: 0.5380 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7403 - val_loss: 0.5427 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7472 - val_loss: 0.5419 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5008 - accuracy: 0.7497 - val_loss: 0.5430 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7545 - val_loss: 0.5389 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7590 - val_loss: 0.5403 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4841 - accuracy: 0.7608 - val_loss: 0.5402 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7613 - val_loss: 0.5486 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4735 - accuracy: 0.7658 - val_loss: 0.5476 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4669 - accuracy: 0.7701 - val_loss: 0.5511 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4607 - accuracy: 0.7724 - val_loss: 0.5512 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 17/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4585 - accuracy: 0.7714
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4575 - accuracy: 0.7723 - val_loss: 0.5567 - val_accuracy: 0.7179 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.44327641269784335
Confusion Matrix :
 [[3224 1099]
 [1310 3013]]
Accuracy on test set:    0.7213740458015268
Sensitivity:    0.696969696969697 	 Specificity:    0.7457783946333565
Precision  : 0.7327334630350194
Area Under Curve:    0.7213740458015268
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6110 - accuracy: 0.6626 - val_loss: 0.5636 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7118 - val_loss: 0.5483 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7227 - val_loss: 0.5434 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7281 - val_loss: 0.5419 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5280 - accuracy: 0.7331 - val_loss: 0.5431 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5220 - accuracy: 0.7379 - val_loss: 0.5424 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7406 - val_loss: 0.5388 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7451 - val_loss: 0.5512 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7493 - val_loss: 0.5372 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4985 - accuracy: 0.7520 - val_loss: 0.5379 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4910 - accuracy: 0.7565 - val_loss: 0.5415 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4866 - accuracy: 0.7606 - val_loss: 0.5431 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4805 - accuracy: 0.7642 - val_loss: 0.5417 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4748 - accuracy: 0.7649
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4750 - accuracy: 0.7649 - val_loss: 0.5443 - val_accuracy: 0.7232 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.45590508402734387
Confusion Matrix :
 [[3211 1112]
 [1241 3082]]
Accuracy on test set:    0.7278510293777469
Sensitivity:    0.7129308350682396 	 Specificity:    0.7427712236872542
Precision  : 0.7348593228421555
Area Under Curve:    0.7278510293777469
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6034 - accuracy: 0.6706 - val_loss: 0.5596 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7114 - val_loss: 0.5537 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7224 - val_loss: 0.5533 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7263 - val_loss: 0.5437 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7319 - val_loss: 0.5419 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7380 - val_loss: 0.5410 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7414 - val_loss: 0.5467 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7430 - val_loss: 0.5412 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7456 - val_loss: 0.5401 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7496 - val_loss: 0.5508 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7547 - val_loss: 0.5553 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4875 - accuracy: 0.7588 - val_loss: 0.5492 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7607 - val_loss: 0.5495 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4770 - accuracy: 0.7642
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7644 - val_loss: 0.5529 - val_accuracy: 0.7210 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.4621632198845356
Confusion Matrix :
 [[3094 1229]
 [1097 3226]]
Accuracy on test set:    0.7309738607448532
Sensitivity:    0.7462410363173722 	 Specificity:    0.715706685172334
Precision  : 0.7241301907968575
Area Under Curve:    0.730973860744853
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6278 - accuracy: 0.6459 - val_loss: 0.5697 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5668 - accuracy: 0.7082 - val_loss: 0.5546 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5501 - accuracy: 0.7194 - val_loss: 0.5490 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7259 - val_loss: 0.5471 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7292 - val_loss: 0.5423 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7354 - val_loss: 0.5418 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5205 - accuracy: 0.7371 - val_loss: 0.5415 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7404 - val_loss: 0.5444 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7438 - val_loss: 0.5482 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7472 - val_loss: 0.5417 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7520 - val_loss: 0.5503 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7542 - val_loss: 0.5556 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4873 - accuracy: 0.7565
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4873 - accuracy: 0.7565 - val_loss: 0.5503 - val_accuracy: 0.7228 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4588471869837451
Confusion Matrix :
 [[3100 1223]
 [1117 3206]]
Accuracy on test set:    0.7293546148507981
Sensitivity:    0.7416146194772149 	 Specificity:    0.7170946102243813
Precision  : 0.7238654323775119
Area Under Curve:    0.729354614850798
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6054 - accuracy: 0.6687 - val_loss: 0.5686 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7118 - val_loss: 0.5556 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7200 - val_loss: 0.5461 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7276 - val_loss: 0.5409 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7374 - val_loss: 0.5405 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7395 - val_loss: 0.5414 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5120 - accuracy: 0.7424 - val_loss: 0.5391 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5075 - accuracy: 0.7452 - val_loss: 0.5382 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7500 - val_loss: 0.5447 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4936 - accuracy: 0.7550 - val_loss: 0.5382 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7568 - val_loss: 0.5395 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7620 - val_loss: 0.5478 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4773 - accuracy: 0.7640
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7641 - val_loss: 0.5400 - val_accuracy: 0.7253 - lr: 0.0010

271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4510261844442492
Confusion Matrix :
 [[3228 1095]
 [1280 3043]]
Accuracy on test set:    0.7253065001156604
Sensitivity:    0.703909322229933 	 Specificity:    0.7467036780013879
Precision  : 0.7353794103431609
Area Under Curve:    0.7253065001156603
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6131 - accuracy: 0.6603 - val_loss: 0.5650 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5645 - accuracy: 0.7080 - val_loss: 0.5579 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5512 - accuracy: 0.7183 - val_loss: 0.5512 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7256 - val_loss: 0.5499 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7304 - val_loss: 0.5478 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.7359 - val_loss: 0.5484 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7390 - val_loss: 0.5464 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5111 - accuracy: 0.7449 - val_loss: 0.5476 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7495 - val_loss: 0.5510 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4964 - accuracy: 0.7537 - val_loss: 0.5444 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7578 - val_loss: 0.5574 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7612 - val_loss: 0.5505 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4762 - accuracy: 0.7616 - val_loss: 0.5523 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4729 - accuracy: 0.7659 - val_loss: 0.5472 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4624 - accuracy: 0.7723
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4633 - accuracy: 0.7713 - val_loss: 0.5547 - val_accuracy: 0.7218 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.47369876621928764
Confusion Matrix :
 [[3358  965]
 [1317 3006]]
Accuracy on test set:    0.7360629192690261
Sensitivity:    0.6953504510756419 	 Specificity:    0.7767753874624104
Precision  : 0.7569881641903803
Area Under Curve:    0.7360629192690261
(8646, 4352) (8646,)
Mean MCC = 0.4481 + 0.0143 and Mean AUC = 0.7236 + 0.0072
Mean Sensitivity = 0.7310 + 0.0267 and Mean Specificity = 0.7162 + 0.0354 and Mean Accuracy = 0.7236 + 0.0072
Mean Precision = 0.7214 + 0.0186





Seed   : 654198
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6059 - accuracy: 0.6662 - val_loss: 0.5741 - val_accuracy: 0.6913 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7102 - val_loss: 0.5551 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7237 - val_loss: 0.5472 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7279 - val_loss: 0.5416 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5281 - accuracy: 0.7345 - val_loss: 0.5396 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5200 - accuracy: 0.7383 - val_loss: 0.5364 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7405 - val_loss: 0.5352 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7439 - val_loss: 0.5343 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7499 - val_loss: 0.5343 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7534 - val_loss: 0.5412 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4932 - accuracy: 0.7557 - val_loss: 0.5363 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4852 - accuracy: 0.7606 - val_loss: 0.5417 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7619 - val_loss: 0.5376 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4742 - accuracy: 0.7678 - val_loss: 0.5482 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4706 - accuracy: 0.7699 - val_loss: 0.5395 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4645 - accuracy: 0.7737 - val_loss: 0.5504 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4569 - accuracy: 0.7781 - val_loss: 0.5484 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4504 - accuracy: 0.7828 - val_loss: 0.5531 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4455 - accuracy: 0.7847 - val_loss: 0.5682 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 20/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4391 - accuracy: 0.7871
Epoch 20: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4399 - accuracy: 0.7868 - val_loss: 0.5579 - val_accuracy: 0.7205 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.42154615351028657
Confusion Matrix :
 [[3155 1168]
 [1334 2989]]
Accuracy on test set:    0.710617626648161
Sensitivity:    0.6914179967615082 	 Specificity:    0.7298172565348138
Precision  : 0.7190281452970892
Area Under Curve:    0.710617626648161
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5982 - accuracy: 0.6746 - val_loss: 0.5582 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5559 - accuracy: 0.7142 - val_loss: 0.5510 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7216 - val_loss: 0.5527 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7304 - val_loss: 0.5392 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7354 - val_loss: 0.5494 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7388 - val_loss: 0.5602 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5122 - accuracy: 0.7432 - val_loss: 0.5387 - val_accuracy: 0.7206 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7473 - val_loss: 0.5470 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7492 - val_loss: 0.5404 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4964 - accuracy: 0.7515 - val_loss: 0.5378 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7558 - val_loss: 0.5406 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4825 - accuracy: 0.7596
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7599 - val_loss: 0.5433 - val_accuracy: 0.7201 - lr: 0.0010
271/271 [==============================] - 1s 651us/step
Independent Testing Matthews Correlation:  0.43004461410920863
Confusion Matrix :
 [[2899 1424]
 [1047 3276]]
Accuracy on test set:    0.7142030996992829
Sensitivity:    0.7578070784177654 	 Specificity:    0.6705991209808003
Precision  : 0.6970212765957446
Area Under Curve:    0.7142030996992829
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6082 - accuracy: 0.6665 - val_loss: 0.5621 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7085 - val_loss: 0.5461 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7211 - val_loss: 0.5460 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7252 - val_loss: 0.5395 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7325 - val_loss: 0.5427 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5200 - accuracy: 0.7378 - val_loss: 0.5356 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7417 - val_loss: 0.5370 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7460 - val_loss: 0.5453 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5006 - accuracy: 0.7487 - val_loss: 0.5548 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7544 - val_loss: 0.5337 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7571 - val_loss: 0.5383 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4847 - accuracy: 0.7604 - val_loss: 0.5398 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7625 - val_loss: 0.5461 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4731 - accuracy: 0.7664 - val_loss: 0.5419 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4642 - accuracy: 0.7719 - val_loss: 0.5479 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4592 - accuracy: 0.7739
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4592 - accuracy: 0.7740 - val_loss: 0.5724 - val_accuracy: 0.7160 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4261097805732777
Confusion Matrix :
 [[2510 1813]
 [ 727 3596]]
Accuracy on test set:    0.7062225306500116
Sensitivity:    0.8318297478602822 	 Specificity:    0.5806153134397409
Precision  : 0.6648178960990941
Area Under Curve:    0.7062225306500115
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6116 - accuracy: 0.6616 - val_loss: 0.5587 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7086 - val_loss: 0.5448 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7226 - val_loss: 0.5447 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7288 - val_loss: 0.5410 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5252 - accuracy: 0.7349 - val_loss: 0.5400 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7378 - val_loss: 0.5387 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5120 - accuracy: 0.7438 - val_loss: 0.5352 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5073 - accuracy: 0.7458 - val_loss: 0.5422 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7485 - val_loss: 0.5383 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7543 - val_loss: 0.5392 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7595 - val_loss: 0.5357 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4842 - accuracy: 0.7588 - val_loss: 0.5403 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4775 - accuracy: 0.7628 - val_loss: 0.5434 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4722 - accuracy: 0.7663 - val_loss: 0.5585 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4633 - accuracy: 0.7716 - val_loss: 0.5512 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4622 - accuracy: 0.7729
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4625 - accuracy: 0.7732 - val_loss: 0.5537 - val_accuracy: 0.7236 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4265876935777005
Confusion Matrix :
 [[3110 1213]
 [1266 3057]]
Accuracy on test set:    0.7132778163312514
Sensitivity:    0.707147814018043 	 Specificity:    0.7194078186444599
Precision  : 0.7159250585480094
Area Under Curve:    0.7132778163312515
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6161 - accuracy: 0.6612 - val_loss: 0.5674 - val_accuracy: 0.7003 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5644 - accuracy: 0.7080 - val_loss: 0.5570 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7215 - val_loss: 0.5441 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7287 - val_loss: 0.5419 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7345 - val_loss: 0.5384 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7367 - val_loss: 0.5462 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7427 - val_loss: 0.5356 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5058 - accuracy: 0.7466 - val_loss: 0.5355 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5002 - accuracy: 0.7500 - val_loss: 0.5410 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7549 - val_loss: 0.5348 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7562 - val_loss: 0.5455 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4835 - accuracy: 0.7599
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7594 - val_loss: 0.5379 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4451027557051672
Confusion Matrix :
 [[3094 1229]
 [1170 3153]]
Accuracy on test set:    0.722530650011566
Sensitivity:    0.7293546148507981 	 Specificity:    0.715706685172334
Precision  : 0.7195344591510726
Area Under Curve:    0.7225306500115661
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6041 - accuracy: 0.6691 - val_loss: 0.5576 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5613 - accuracy: 0.7117 - val_loss: 0.5454 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7212 - val_loss: 0.5403 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7278 - val_loss: 0.5437 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5278 - accuracy: 0.7337 - val_loss: 0.5341 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7397 - val_loss: 0.5342 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5146 - accuracy: 0.7437 - val_loss: 0.5354 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7453 - val_loss: 0.5316 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7489 - val_loss: 0.5341 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4964 - accuracy: 0.7529 - val_loss: 0.5373 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7563 - val_loss: 0.5348 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7594 - val_loss: 0.5359 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4806 - accuracy: 0.7623 - val_loss: 0.5439 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4746 - accuracy: 0.7648
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4749 - accuracy: 0.7642 - val_loss: 0.5442 - val_accuracy: 0.7258 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4390529058363042
Confusion Matrix :
 [[2987 1336]
 [1092 3231]]
Accuracy on test set:    0.719176497802452
Sensitivity:    0.7473976405274115 	 Specificity:    0.6909553550774925
Precision  : 0.7074666082767681
Area Under Curve:    0.719176497802452
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6190 - accuracy: 0.6562 - val_loss: 0.5709 - val_accuracy: 0.7026 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5640 - accuracy: 0.7067 - val_loss: 0.5491 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7184 - val_loss: 0.5477 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7297 - val_loss: 0.5438 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5290 - accuracy: 0.7317 - val_loss: 0.5348 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5194 - accuracy: 0.7382 - val_loss: 0.5415 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7417 - val_loss: 0.5342 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7444 - val_loss: 0.5385 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5009 - accuracy: 0.7500 - val_loss: 0.5386 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7518 - val_loss: 0.5375 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7566 - val_loss: 0.5420 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4834 - accuracy: 0.7608 - val_loss: 0.5404 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4771 - accuracy: 0.7630 - val_loss: 0.5416 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4695 - accuracy: 0.7664 - val_loss: 0.5539 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4687 - accuracy: 0.7678 - val_loss: 0.5630 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4594 - accuracy: 0.7739
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4598 - accuracy: 0.7737 - val_loss: 0.5516 - val_accuracy: 0.7174 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.46040353936703704
Confusion Matrix :
 [[2996 1327]
 [1011 3312]]
Accuracy on test set:    0.7295859356928059
Sensitivity:    0.7661346287300486 	 Specificity:    0.6930372426555632
Precision  : 0.713946971330028
Area Under Curve:    0.7295859356928059
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6108 - accuracy: 0.6652 - val_loss: 0.5645 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7106 - val_loss: 0.5499 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7211 - val_loss: 0.5427 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7273 - val_loss: 0.5412 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7330 - val_loss: 0.5399 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7386 - val_loss: 0.5478 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7420 - val_loss: 0.5413 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7454 - val_loss: 0.5436 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5055 - accuracy: 0.7468 - val_loss: 0.5371 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7518 - val_loss: 0.5420 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7565 - val_loss: 0.5347 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7566 - val_loss: 0.5561 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4779 - accuracy: 0.7638 - val_loss: 0.5454 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4757 - accuracy: 0.7635 - val_loss: 0.5441 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7669 - val_loss: 0.5532 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4616 - accuracy: 0.7730
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4622 - accuracy: 0.7726 - val_loss: 0.5462 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4548728959777003
Confusion Matrix :
 [[3226 1097]
 [1261 3062]]
Accuracy on test set:    0.7272727272727273
Sensitivity:    0.7083044182280823 	 Specificity:    0.7462410363173722
Precision  : 0.7362346717961048
Area Under Curve:    0.7272727272727273
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6027 - accuracy: 0.6703 - val_loss: 0.5643 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7104 - val_loss: 0.5569 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7197 - val_loss: 0.5466 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7282 - val_loss: 0.5388 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5268 - accuracy: 0.7338 - val_loss: 0.5431 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7385 - val_loss: 0.5423 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7432 - val_loss: 0.5368 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7456 - val_loss: 0.5410 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4983 - accuracy: 0.7525 - val_loss: 0.5377 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4924 - accuracy: 0.7564
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7559 - val_loss: 0.5469 - val_accuracy: 0.7158 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.45073452768458744
Confusion Matrix :
 [[3490  833]
 [1570 2753]]
Accuracy on test set:    0.7220680083275504
Sensitivity:    0.6368262780476521 	 Specificity:    0.8073097386074485
Precision  : 0.7677077523703291
Area Under Curve:    0.7220680083275504
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6042 - accuracy: 0.6697 - val_loss: 0.5614 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7104 - val_loss: 0.5512 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7186 - val_loss: 0.5428 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7276 - val_loss: 0.5475 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5287 - accuracy: 0.7315 - val_loss: 0.5431 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5205 - accuracy: 0.7383 - val_loss: 0.5412 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5159 - accuracy: 0.7420 - val_loss: 0.5421 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5096 - accuracy: 0.7458 - val_loss: 0.5367 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7502 - val_loss: 0.5423 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7526 - val_loss: 0.5376 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4902 - accuracy: 0.7564 - val_loss: 0.5385 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4845 - accuracy: 0.7613 - val_loss: 0.5483 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4816 - accuracy: 0.7606
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4815 - accuracy: 0.7607 - val_loss: 0.5424 - val_accuracy: 0.7273 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.49154599927058656
Confusion Matrix :
 [[3369  954]
 [1249 3074]]
Accuracy on test set:    0.7452000925283369
Sensitivity:    0.7110802683321767 	 Specificity:    0.7793199167244969
Precision  : 0.7631578947368421
Area Under Curve:    0.7452000925283369
(8646, 4352) (8646,)
Mean MCC = 0.4446 + 0.0201 and Mean AUC = 0.7210 + 0.0107
Mean Sensitivity = 0.7287 + 0.0493 and Mean Specificity = 0.7133 + 0.0591 and Mean Accuracy = 0.7210 + 0.0107
Mean Precision = 0.7205 + 0.0286





Seed   : 765208
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6073 - accuracy: 0.6675 - val_loss: 0.5622 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5544 - accuracy: 0.7147 - val_loss: 0.5511 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7250 - val_loss: 0.5460 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5295 - accuracy: 0.7325 - val_loss: 0.5437 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7394 - val_loss: 0.5417 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5141 - accuracy: 0.7426 - val_loss: 0.5493 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5063 - accuracy: 0.7460 - val_loss: 0.5411 - val_accuracy: 0.7222 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7515 - val_loss: 0.5384 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7553 - val_loss: 0.5413 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4857 - accuracy: 0.7598 - val_loss: 0.5441 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4781 - accuracy: 0.7653 - val_loss: 0.5468 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4730 - accuracy: 0.7674 - val_loss: 0.5602 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4662 - accuracy: 0.7710 - val_loss: 0.5485 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4569 - accuracy: 0.7777 - val_loss: 0.5467 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4530 - accuracy: 0.7800 - val_loss: 0.5646 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4503 - accuracy: 0.7799 - val_loss: 0.5513 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4411 - accuracy: 0.7861
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4417 - accuracy: 0.7859 - val_loss: 0.5629 - val_accuracy: 0.7145 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.41768975160410765
Confusion Matrix :
 [[3005 1318]
 [1200 3123]]
Accuracy on test set:    0.7087670599120981
Sensitivity:    0.7224149895905622 	 Specificity:    0.695119130233634
Precision  : 0.7032199954965098
Area Under Curve:    0.708767059912098
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6064 - accuracy: 0.6661 - val_loss: 0.5654 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5590 - accuracy: 0.7116 - val_loss: 0.5547 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7249 - val_loss: 0.5491 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7275 - val_loss: 0.5419 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5264 - accuracy: 0.7338 - val_loss: 0.5453 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7381 - val_loss: 0.5406 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5119 - accuracy: 0.7413 - val_loss: 0.5424 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7469 - val_loss: 0.5527 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7521 - val_loss: 0.5500 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7548 - val_loss: 0.5410 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7578 - val_loss: 0.5485 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4816 - accuracy: 0.7617 - val_loss: 0.5491 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4762 - accuracy: 0.7655 - val_loss: 0.5512 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4704 - accuracy: 0.7698 - val_loss: 0.5580 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4632 - accuracy: 0.7716
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4638 - accuracy: 0.7711 - val_loss: 0.5594 - val_accuracy: 0.7150 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4294184514149163
Confusion Matrix :
 [[3133 1190]
 [1277 3046]]
Accuracy on test set:    0.7146657413832986
Sensitivity:    0.7046032847559565 	 Specificity:    0.7247281980106408
Precision  : 0.7190745986779982
Area Under Curve:    0.7146657413832986
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6084 - accuracy: 0.6655 - val_loss: 0.5696 - val_accuracy: 0.6983 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7122 - val_loss: 0.5564 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7247 - val_loss: 0.5463 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7316 - val_loss: 0.5461 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7356 - val_loss: 0.5434 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7397 - val_loss: 0.5470 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7470 - val_loss: 0.5411 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7492 - val_loss: 0.5431 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7555 - val_loss: 0.5522 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7562 - val_loss: 0.5493 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7610 - val_loss: 0.5464 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4777 - accuracy: 0.7649
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4779 - accuracy: 0.7649 - val_loss: 0.5476 - val_accuracy: 0.7240 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4340220053082807
Confusion Matrix :
 [[2935 1388]
 [1064 3259]]
Accuracy on test set:    0.7164006476983577
Sensitivity:    0.7538746241036317 	 Specificity:    0.6789266712930835
Precision  : 0.7013126748439854
Area Under Curve:    0.7164006476983575
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6017 - accuracy: 0.6714 - val_loss: 0.5696 - val_accuracy: 0.7015 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5566 - accuracy: 0.7110 - val_loss: 0.5732 - val_accuracy: 0.6997 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7250 - val_loss: 0.5503 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7313 - val_loss: 0.5511 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5223 - accuracy: 0.7379 - val_loss: 0.5533 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 6/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7408 - val_loss: 0.5436 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7462 - val_loss: 0.5475 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5042 - accuracy: 0.7480 - val_loss: 0.5481 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7514 - val_loss: 0.5448 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7578 - val_loss: 0.5463 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4859 - accuracy: 0.7613 - val_loss: 0.5737 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4793 - accuracy: 0.7642 - val_loss: 0.5516 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4738 - accuracy: 0.7677 - val_loss: 0.5532 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4679 - accuracy: 0.7691 - val_loss: 0.5599 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4628 - accuracy: 0.7733 - val_loss: 0.5599 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4579 - accuracy: 0.7762 - val_loss: 0.5636 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4518 - accuracy: 0.7790 - val_loss: 0.5641 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4449 - accuracy: 0.7827
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4458 - accuracy: 0.7825 - val_loss: 0.5643 - val_accuracy: 0.7142 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4224783088566771
Confusion Matrix :
 [[3222 1101]
 [1400 2923]]
Accuracy on test set:    0.7107332870691649
Sensitivity:    0.6761508211889892 	 Specificity:    0.7453157529493407
Precision  : 0.7263916500994035
Area Under Curve:    0.7107332870691649
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6125 - accuracy: 0.6631 - val_loss: 0.5684 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7100 - val_loss: 0.5561 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7221 - val_loss: 0.5475 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5369 - accuracy: 0.7260 - val_loss: 0.5502 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5274 - accuracy: 0.7337 - val_loss: 0.5435 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5211 - accuracy: 0.7378 - val_loss: 0.5400 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5136 - accuracy: 0.7420 - val_loss: 0.5443 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7471 - val_loss: 0.5385 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5017 - accuracy: 0.7497 - val_loss: 0.5434 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4960 - accuracy: 0.7527 - val_loss: 0.5445 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7568 - val_loss: 0.5405 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4841 - accuracy: 0.7599 - val_loss: 0.5470 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4785 - accuracy: 0.7649
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4782 - accuracy: 0.7649 - val_loss: 0.5471 - val_accuracy: 0.7217 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.44124691564411966
Confusion Matrix :
 [[3065 1258]
 [1158 3165]]
Accuracy on test set:    0.7205644228544992
Sensitivity:    0.7321304649548924 	 Specificity:    0.7089983807541059
Precision  : 0.7155776622202126
Area Under Curve:    0.7205644228544992
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6018 - accuracy: 0.6691 - val_loss: 0.5618 - val_accuracy: 0.7007 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5570 - accuracy: 0.7121 - val_loss: 0.5492 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7211 - val_loss: 0.5478 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5317 - accuracy: 0.7315 - val_loss: 0.5405 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5222 - accuracy: 0.7376 - val_loss: 0.5464 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5144 - accuracy: 0.7415 - val_loss: 0.5422 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7470 - val_loss: 0.5397 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5056 - accuracy: 0.7486 - val_loss: 0.5541 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7506 - val_loss: 0.5423 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7570 - val_loss: 0.5369 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7600 - val_loss: 0.5427 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7614 - val_loss: 0.5470 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4741 - accuracy: 0.7664 - val_loss: 0.5426 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4706 - accuracy: 0.7692 - val_loss: 0.5477 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4630 - accuracy: 0.7717 - val_loss: 0.5541 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4580 - accuracy: 0.7768 - val_loss: 0.5491 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4499 - accuracy: 0.7802
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4495 - accuracy: 0.7804 - val_loss: 0.5594 - val_accuracy: 0.7236 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.44215113644489007
Confusion Matrix :
 [[2937 1386]
 [1032 3291]]
Accuracy on test set:    0.7203331020124913
Sensitivity:    0.7612768910478834 	 Specificity:    0.6793893129770993
Precision  : 0.7036561898652983
Area Under Curve:    0.7203331020124913
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6066 - accuracy: 0.6661 - val_loss: 0.5674 - val_accuracy: 0.6997 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5593 - accuracy: 0.7115 - val_loss: 0.5549 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7223 - val_loss: 0.5470 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7293 - val_loss: 0.5490 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5264 - accuracy: 0.7350 - val_loss: 0.5458 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5191 - accuracy: 0.7402 - val_loss: 0.5500 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7437 - val_loss: 0.5416 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7463 - val_loss: 0.5433 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4987 - accuracy: 0.7498 - val_loss: 0.5426 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7565 - val_loss: 0.5446 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7577 - val_loss: 0.5453 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7619 - val_loss: 0.5525 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4749 - accuracy: 0.7664 - val_loss: 0.5489 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4686 - accuracy: 0.7702
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4691 - accuracy: 0.7698 - val_loss: 0.5489 - val_accuracy: 0.7195 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.44164257309876903
Confusion Matrix :
 [[3240 1083]
 [1334 2989]]
Accuracy on test set:    0.7204487624334952
Sensitivity:    0.6914179967615082 	 Specificity:    0.7494795281054824
Precision  : 0.7340373280943026
Area Under Curve:    0.7204487624334952
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6250 - accuracy: 0.6526 - val_loss: 0.5735 - val_accuracy: 0.6964 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5654 - accuracy: 0.7067 - val_loss: 0.5612 - val_accuracy: 0.7052 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5497 - accuracy: 0.7188 - val_loss: 0.5493 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7235 - val_loss: 0.5488 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5307 - accuracy: 0.7310 - val_loss: 0.5467 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7362 - val_loss: 0.5448 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7371 - val_loss: 0.5477 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7455 - val_loss: 0.5485 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7470 - val_loss: 0.5546 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7507 - val_loss: 0.5552 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7569 - val_loss: 0.5460 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4875 - accuracy: 0.7574
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4879 - accuracy: 0.7573 - val_loss: 0.5500 - val_accuracy: 0.7124 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.45657638324563327
Confusion Matrix :
 [[2966 1357]
 [ 999 3324]]
Accuracy on test set:    0.7275040481147351
Sensitivity:    0.768910478834143 	 Specificity:    0.6860976173953273
Precision  : 0.7101046784875027
Area Under Curve:    0.7275040481147351
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6107 - accuracy: 0.6655 - val_loss: 0.5708 - val_accuracy: 0.6989 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7110 - val_loss: 0.5552 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7233 - val_loss: 0.5546 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7283 - val_loss: 0.5502 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5294 - accuracy: 0.7321 - val_loss: 0.5432 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5202 - accuracy: 0.7369 - val_loss: 0.5424 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7419 - val_loss: 0.5443 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7461 - val_loss: 0.5565 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7512 - val_loss: 0.5446 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4947 - accuracy: 0.7556 - val_loss: 0.5450 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7587 - val_loss: 0.5448 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4780 - accuracy: 0.7625 - val_loss: 0.5454 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4749 - accuracy: 0.7655 - val_loss: 0.5573 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4711 - accuracy: 0.7683 - val_loss: 0.5616 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4623 - accuracy: 0.7725 - val_loss: 0.5654 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4586 - accuracy: 0.7751
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4589 - accuracy: 0.7751 - val_loss: 0.5588 - val_accuracy: 0.7158 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.47459161229078034
Confusion Matrix :
 [[2973 1350]
 [ 931 3392]]
Accuracy on test set:    0.7361785796900301
Sensitivity:    0.7846402960906778 	 Specificity:    0.6877168632893824
Precision  : 0.7153099957823703
Area Under Curve:    0.7361785796900301
(8646, 4352) (8646,)
Epoch 1/400

274/274 [==============================] - 1s 3ms/step - loss: 0.6096 - accuracy: 0.6645 - val_loss: 0.5709 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5626 - accuracy: 0.7088 - val_loss: 0.5615 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7194 - val_loss: 0.5527 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7274 - val_loss: 0.5533 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5295 - accuracy: 0.7325 - val_loss: 0.5522 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7377 - val_loss: 0.5481 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5149 - accuracy: 0.7407 - val_loss: 0.5516 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7454 - val_loss: 0.5629 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7500 - val_loss: 0.5499 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7550 - val_loss: 0.5513 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7565 - val_loss: 0.5516 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7608 - val_loss: 0.5584 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4754 - accuracy: 0.7652 - val_loss: 0.5527 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4704 - accuracy: 0.7689
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7686 - val_loss: 0.5565 - val_accuracy: 0.7208 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4941218247639858
Confusion Matrix :
 [[3298 1025]
 [1163 3160]]
Accuracy on test set:    0.7469349988433958
Sensitivity:    0.7309738607448532 	 Specificity:    0.7628961369419385
Precision  : 0.7550776583034647
Area Under Curve:    0.7469349988433959
(8646, 4352) (8646,)
Mean MCC = 0.4454 + 0.0225 and Mean AUC = 0.7223 + 0.0112
Mean Sensitivity = 0.7326 + 0.0333 and Mean Specificity = 0.7119 + 0.0300 and Mean Accuracy = 0.7223 + 0.0112
Mean Precision = 0.7184 + 0.0157





Seed   : 279560
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6008 - accuracy: 0.6708 - val_loss: 0.5627 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5548 - accuracy: 0.7154 - val_loss: 0.5452 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7258 - val_loss: 0.5403 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5303 - accuracy: 0.7324 - val_loss: 0.5406 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7361 - val_loss: 0.5358 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5166 - accuracy: 0.7398 - val_loss: 0.5400 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7455 - val_loss: 0.5339 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7518 - val_loss: 0.5401 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7560 - val_loss: 0.5326 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7571 - val_loss: 0.5367 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7622 - val_loss: 0.5404 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4722 - accuracy: 0.7684 - val_loss: 0.5398 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4661 - accuracy: 0.7716 - val_loss: 0.5388 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4596 - accuracy: 0.7755
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4609 - accuracy: 0.7740 - val_loss: 0.5403 - val_accuracy: 0.7204 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4199524150077175
Confusion Matrix :
 [[2982 1341]
 [1168 3155]]
Accuracy on test set:    0.7098080037011335
Sensitivity:    0.7298172565348138 	 Specificity:    0.6897987508674531
Precision  : 0.7017348754448398
Area Under Curve:    0.7098080037011335
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6178 - accuracy: 0.6591 - val_loss: 0.5709 - val_accuracy: 0.7041 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5635 - accuracy: 0.7102 - val_loss: 0.5529 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5486 - accuracy: 0.7195 - val_loss: 0.5439 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7258 - val_loss: 0.5456 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7315 - val_loss: 0.5369 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7343 - val_loss: 0.5333 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7386 - val_loss: 0.5358 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7417 - val_loss: 0.5386 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7441 - val_loss: 0.5386 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7500 - val_loss: 0.5344 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4951 - accuracy: 0.7516 - val_loss: 0.5347 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4910 - accuracy: 0.7545 - val_loss: 0.5348 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4839 - accuracy: 0.7585 - val_loss: 0.5326 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4811 - accuracy: 0.7619 - val_loss: 0.5392 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4741 - accuracy: 0.7646
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4742 - accuracy: 0.7643 - val_loss: 0.5479 - val_accuracy: 0.7222 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.4451782162090281
Confusion Matrix :
 [[2882 1441]
 [ 969 3354]]
Accuracy on test set:    0.7212583853805228
Sensitivity:    0.7758501040943789 	 Specificity:    0.6666666666666666
Precision  : 0.6994786235662148
Area Under Curve:    0.721258385380523
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6083 - accuracy: 0.6664 - val_loss: 0.5642 - val_accuracy: 0.7019 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5595 - accuracy: 0.7116 - val_loss: 0.5504 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7203 - val_loss: 0.5460 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7287 - val_loss: 0.5386 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5269 - accuracy: 0.7330 - val_loss: 0.5383 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7384 - val_loss: 0.5355 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5136 - accuracy: 0.7426 - val_loss: 0.5396 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5065 - accuracy: 0.7470 - val_loss: 0.5339 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7495 - val_loss: 0.5356 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7545 - val_loss: 0.5386 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4904 - accuracy: 0.7565
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7562 - val_loss: 0.5367 - val_accuracy: 0.7208 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4469360816069605
Confusion Matrix :
 [[3105 1218]
 [1173 3150]]
Accuracy on test set:    0.7234559333795975
Sensitivity:    0.7286606523247745 	 Specificity:    0.7182512144344205
Precision  : 0.7211538461538461
Area Under Curve:    0.7234559333795976
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6121 - accuracy: 0.6618 - val_loss: 0.5587 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5587 - accuracy: 0.7124 - val_loss: 0.5435 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7231 - val_loss: 0.5422 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7305 - val_loss: 0.5347 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5263 - accuracy: 0.7358 - val_loss: 0.5367 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5172 - accuracy: 0.7418 - val_loss: 0.5318 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7470 - val_loss: 0.5320 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5056 - accuracy: 0.7478 - val_loss: 0.5334 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4978 - accuracy: 0.7555
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7551 - val_loss: 0.5327 - val_accuracy: 0.7258 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.42794549269096693
Confusion Matrix :
 [[3093 1230]
 [1243 3080]]
Accuracy on test set:    0.713971778857275
Sensitivity:    0.712468193384224 	 Specificity:    0.7154753643303262
Precision  : 0.7146171693735499
Area Under Curve:    0.7139717788572751
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6082 - accuracy: 0.6646 - val_loss: 0.5528 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5598 - accuracy: 0.7118 - val_loss: 0.5415 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7232 - val_loss: 0.5369 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7291 - val_loss: 0.5313 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7347 - val_loss: 0.5307 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7399 - val_loss: 0.5308 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7440 - val_loss: 0.5276 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5042 - accuracy: 0.7473 - val_loss: 0.5303 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7515 - val_loss: 0.5305 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7538 - val_loss: 0.5289 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4877 - accuracy: 0.7567 - val_loss: 0.5377 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4841 - accuracy: 0.7572 - val_loss: 0.5355 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4758 - accuracy: 0.7631
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4756 - accuracy: 0.7633 - val_loss: 0.5332 - val_accuracy: 0.7250 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.432814746539017
Confusion Matrix :
 [[2846 1477]
 [ 987 3336]]
Accuracy on test set:    0.7150127226463104
Sensitivity:    0.7716863289382373 	 Specificity:    0.6583391163543836
Precision  : 0.6931227924371494
Area Under Curve:    0.7150127226463104
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6117 - accuracy: 0.6621 - val_loss: 0.5609 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5678 - accuracy: 0.7067 - val_loss: 0.5435 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5520 - accuracy: 0.7176 - val_loss: 0.5388 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7260 - val_loss: 0.5362 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7288 - val_loss: 0.5386 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7305 - val_loss: 0.5319 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7350 - val_loss: 0.5328 - val_accuracy: 0.7227 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5177 - accuracy: 0.7387 - val_loss: 0.5298 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7411 - val_loss: 0.5332 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7445 - val_loss: 0.5282 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5065 - accuracy: 0.7440 - val_loss: 0.5299 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7500 - val_loss: 0.5327 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7513 - val_loss: 0.5329 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7555 - val_loss: 0.5373 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4836 - accuracy: 0.7578 - val_loss: 0.5380 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4785 - accuracy: 0.7605 - val_loss: 0.5406 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4743 - accuracy: 0.7629 - val_loss: 0.5370 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4712 - accuracy: 0.7643 - val_loss: 0.5467 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4664 - accuracy: 0.7659 - val_loss: 0.5478 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4607 - accuracy: 0.7694 - val_loss: 0.5477 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4574 - accuracy: 0.7698 - val_loss: 0.5602 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 22/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4537 - accuracy: 0.7730
Epoch 22: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4532 - accuracy: 0.7734 - val_loss: 0.5603 - val_accuracy: 0.7218 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.42942021873428865
Confusion Matrix :
 [[3198 1125]
 [1344 2979]]
Accuracy on test set:    0.7144344205412908
Sensitivity:    0.6891047883414295 	 Specificity:    0.739764052741152
Precision  : 0.7258771929824561
Area Under Curve:    0.7144344205412907
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6065 - accuracy: 0.6650 - val_loss: 0.5572 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7108 - val_loss: 0.5477 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7200 - val_loss: 0.5435 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7294 - val_loss: 0.5385 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7329 - val_loss: 0.5353 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5210 - accuracy: 0.7379 - val_loss: 0.5328 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7420 - val_loss: 0.5333 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7469 - val_loss: 0.5435 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5022 - accuracy: 0.7492 - val_loss: 0.5351 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4956 - accuracy: 0.7541 - val_loss: 0.5355 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7552 - val_loss: 0.5392 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7602 - val_loss: 0.5339 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7617 - val_loss: 0.5406 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4732 - accuracy: 0.7659 - val_loss: 0.5491 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7691 - val_loss: 0.5437 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4611 - accuracy: 0.7728 - val_loss: 0.5482 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4547 - accuracy: 0.7762 - val_loss: 0.5483 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4537 - accuracy: 0.7753 - val_loss: 0.5533 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 19/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4448 - accuracy: 0.7815
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4452 - accuracy: 0.7809 - val_loss: 0.5506 - val_accuracy: 0.7221 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.45729203459371043
Confusion Matrix :
 [[3032 1291]
 [1058 3265]]
Accuracy on test set:    0.7283136710617627
Sensitivity:    0.7552625491556789 	 Specificity:    0.7013647929678464
Precision  : 0.7166374012291484
Area Under Curve:    0.7283136710617626
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6060 - accuracy: 0.6683 - val_loss: 0.5613 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7110 - val_loss: 0.5461 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7223 - val_loss: 0.5399 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7300 - val_loss: 0.5392 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5278 - accuracy: 0.7305 - val_loss: 0.5400 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5191 - accuracy: 0.7385 - val_loss: 0.5369 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7396 - val_loss: 0.5332 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7448 - val_loss: 0.5337 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7500 - val_loss: 0.5342 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4950 - accuracy: 0.7535 - val_loss: 0.5348 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4901 - accuracy: 0.7568 - val_loss: 0.5358 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 12/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4857 - accuracy: 0.7605
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4850 - accuracy: 0.7605 - val_loss: 0.5380 - val_accuracy: 0.7282 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.45373570051207324
Confusion Matrix :
 [[3057 1266]
 [1097 3226]]
Accuracy on test set:    0.7266944251677077
Sensitivity:    0.7462410363173722 	 Specificity:    0.707147814018043
Precision  : 0.7181656277827249
Area Under Curve:    0.7266944251677077
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6155 - accuracy: 0.6625 - val_loss: 0.5710 - val_accuracy: 0.6994 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5654 - accuracy: 0.7074 - val_loss: 0.5546 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5506 - accuracy: 0.7174 - val_loss: 0.5465 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7243 - val_loss: 0.5490 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5306 - accuracy: 0.7313 - val_loss: 0.5394 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7372 - val_loss: 0.5399 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5159 - accuracy: 0.7401 - val_loss: 0.5431 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7453 - val_loss: 0.5411 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7481 - val_loss: 0.5431 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 10/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4967 - accuracy: 0.7501
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7499 - val_loss: 0.5460 - val_accuracy: 0.7254 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.46796211346259353
Confusion Matrix :
 [[3174 1149]
 [1151 3172]]
Accuracy on test set:    0.7339810316909554
Sensitivity:    0.7337497108489475 	 Specificity:    0.7342123525329632
Precision  : 0.7340893311733395
Area Under Curve:    0.7339810316909554
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6084 - accuracy: 0.6656 - val_loss: 0.5699 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5662 - accuracy: 0.7075 - val_loss: 0.5557 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5482 - accuracy: 0.7212 - val_loss: 0.5495 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7271 - val_loss: 0.5456 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7311 - val_loss: 0.5479 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7358 - val_loss: 0.5440 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5194 - accuracy: 0.7386 - val_loss: 0.5405 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7438 - val_loss: 0.5409 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7454 - val_loss: 0.5465 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5015 - accuracy: 0.7504 - val_loss: 0.5404 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7543 - val_loss: 0.5502 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4869 - accuracy: 0.7570 - val_loss: 0.5481 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.7599 - val_loss: 0.5468 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7620 - val_loss: 0.5492 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4724 - accuracy: 0.7662 - val_loss: 0.5485 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4684 - accuracy: 0.7692 - val_loss: 0.5552 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4608 - accuracy: 0.7726
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4617 - accuracy: 0.7721 - val_loss: 0.5585 - val_accuracy: 0.7235 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.49591454684068215
Confusion Matrix :
 [[3322 1001]
 [1180 3143]]
Accuracy on test set:    0.7477446217904233
Sensitivity:    0.7270414064307195 	 Specificity:    0.7684478371501272
Precision  : 0.7584459459459459
Area Under Curve:    0.7477446217904233
(8646, 4352) (8646,)
Mean MCC = 0.4477 + 0.0214 and Mean AUC = 0.7235 + 0.0108
Mean Sensitivity = 0.7370 + 0.0250 and Mean Specificity = 0.7099 + 0.0317 and Mean Accuracy = 0.7235 + 0.0108
Mean Precision = 0.7183 + 0.0179





Seed   : 798312
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6058 - accuracy: 0.6676 - val_loss: 0.5580 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5547 - accuracy: 0.7148 - val_loss: 0.5403 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7256 - val_loss: 0.5418 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7315 - val_loss: 0.5327 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5214 - accuracy: 0.7383 - val_loss: 0.5320 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7433 - val_loss: 0.5310 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7471 - val_loss: 0.5360 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7501 - val_loss: 0.5293 - val_accuracy: 0.7345 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7578 - val_loss: 0.5302 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4860 - accuracy: 0.7582 - val_loss: 0.5305 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4782 - accuracy: 0.7658 - val_loss: 0.5249 - val_accuracy: 0.7343 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4719 - accuracy: 0.7674 - val_loss: 0.5382 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 13/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4656 - accuracy: 0.7709
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

274/274 [==============================] - 1s 2ms/step - loss: 0.4663 - accuracy: 0.7706 - val_loss: 0.5351 - val_accuracy: 0.7323 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.41143406075599737
Confusion Matrix :
 [[2993 1330]
 [1215 3108]]
Accuracy on test set:    0.7056442285449919
Sensitivity:    0.7189451769604441 	 Specificity:    0.6923432801295397
Precision  : 0.7003154574132492
Area Under Curve:    0.705644228544992
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6122 - accuracy: 0.6638 - val_loss: 0.5569 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5570 - accuracy: 0.7153 - val_loss: 0.5475 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7237 - val_loss: 0.5460 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7310 - val_loss: 0.5364 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7357 - val_loss: 0.5429 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7397 - val_loss: 0.5338 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5091 - accuracy: 0.7456 - val_loss: 0.5494 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7503 - val_loss: 0.5303 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4963 - accuracy: 0.7532 - val_loss: 0.5343 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4902 - accuracy: 0.7556 - val_loss: 0.5355 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4815 - accuracy: 0.7622 - val_loss: 0.5399 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4746 - accuracy: 0.7671 - val_loss: 0.5410 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4688 - accuracy: 0.7708
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4694 - accuracy: 0.7698 - val_loss: 0.5493 - val_accuracy: 0.7165 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4263138955526225
Confusion Matrix :
 [[3425  898]
 [1607 2716]]
Accuracy on test set:    0.7102706453851492
Sensitivity:    0.6282674068933611 	 Specificity:    0.7922738838769373
Precision  : 0.7515218594355285
Area Under Curve:    0.7102706453851493
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6058 - accuracy: 0.6657 - val_loss: 0.5608 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7127 - val_loss: 0.5461 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7219 - val_loss: 0.5430 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7302 - val_loss: 0.5369 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7352 - val_loss: 0.5341 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7394 - val_loss: 0.5302 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7429 - val_loss: 0.5338 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5057 - accuracy: 0.7473 - val_loss: 0.5287 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7533 - val_loss: 0.5381 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4924 - accuracy: 0.7531 - val_loss: 0.5308 - val_accuracy: 0.7339 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7556 - val_loss: 0.5353 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4805 - accuracy: 0.7611 - val_loss: 0.5361 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4755 - accuracy: 0.7659 - val_loss: 0.5384 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4715 - accuracy: 0.7677 - val_loss: 0.5423 - val_accuracy: 0.7334 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4654 - accuracy: 0.7691
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4657 - accuracy: 0.7690 - val_loss: 0.5490 - val_accuracy: 0.7289 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.43913000054419643
Confusion Matrix :
 [[2880 1443]
 [ 992 3331]]
Accuracy on test set:    0.7183668748554245
Sensitivity:    0.770529724728198 	 Specificity:    0.666204024982651
Precision  : 0.6977377461248429
Area Under Curve:    0.7183668748554244
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6059 - accuracy: 0.6645 - val_loss: 0.5584 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7108 - val_loss: 0.5563 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7222 - val_loss: 0.5384 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7280 - val_loss: 0.5409 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7347 - val_loss: 0.5377 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7385 - val_loss: 0.5364 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5141 - accuracy: 0.7431 - val_loss: 0.5365 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7453 - val_loss: 0.5375 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5012 - accuracy: 0.7492 - val_loss: 0.5406 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4938 - accuracy: 0.7539 - val_loss: 0.5415 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7578 - val_loss: 0.5364 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4847 - accuracy: 0.7589 - val_loss: 0.5418 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4795 - accuracy: 0.7624 - val_loss: 0.5431 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4711 - accuracy: 0.7670 - val_loss: 0.5481 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4674 - accuracy: 0.7692 - val_loss: 0.5526 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4646 - accuracy: 0.7706 - val_loss: 0.5489 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4580 - accuracy: 0.7750 - val_loss: 0.5515 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4522 - accuracy: 0.7779 - val_loss: 0.5583 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 19/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4466 - accuracy: 0.7787
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4468 - accuracy: 0.7790 - val_loss: 0.5600 - val_accuracy: 0.7262 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.43048850160957464
Confusion Matrix :
 [[3095 1228]
 [1234 3089]]
Accuracy on test set:    0.7152440434883183
Sensitivity:    0.7145500809622947 	 Specificity:    0.7159380060143419
Precision  : 0.7155432012971972
Area Under Curve:    0.7152440434883183
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6066 - accuracy: 0.6658 - val_loss: 0.5629 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7130 - val_loss: 0.5610 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7225 - val_loss: 0.5533 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7294 - val_loss: 0.5416 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5267 - accuracy: 0.7336 - val_loss: 0.5387 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5208 - accuracy: 0.7384 - val_loss: 0.5388 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7423 - val_loss: 0.5380 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7468 - val_loss: 0.5326 - val_accuracy: 0.7364 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7489 - val_loss: 0.5323 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4963 - accuracy: 0.7554 - val_loss: 0.5483 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7572 - val_loss: 0.5374 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4868 - accuracy: 0.7595 - val_loss: 0.5367 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 13/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4790 - accuracy: 0.7661
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7665 - val_loss: 0.5394 - val_accuracy: 0.7308 - lr: 0.0010
271/271 [==============================] - 0s 637us/step
Independent Testing Matthews Correlation:  0.4478809445823217
Confusion Matrix :
 [[2721 1602]
 [ 817 3506]]
Accuracy on test set:    0.7202174415914874
Sensitivity:    0.8110108720795743 	 Specificity:    0.6294240111034004
Precision  : 0.6863743148003132
Area Under Curve:    0.7202174415914874
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6086 - accuracy: 0.6660 - val_loss: 0.5615 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7131 - val_loss: 0.5451 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7229 - val_loss: 0.5390 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7313 - val_loss: 0.5405 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7345 - val_loss: 0.5373 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5199 - accuracy: 0.7392 - val_loss: 0.5334 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7424 - val_loss: 0.5445 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7470 - val_loss: 0.5318 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7522 - val_loss: 0.5364 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4959 - accuracy: 0.7533 - val_loss: 0.5359 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7590 - val_loss: 0.5373 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7594 - val_loss: 0.5386 - val_accuracy: 0.7340 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4819 - accuracy: 0.7611 - val_loss: 0.5401 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4737 - accuracy: 0.7672 - val_loss: 0.5466 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7703 - val_loss: 0.5376 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4612 - accuracy: 0.7736 - val_loss: 0.5449 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4562 - accuracy: 0.7760
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4565 - accuracy: 0.7757 - val_loss: 0.5465 - val_accuracy: 0.7295 - lr: 0.0010
271/271 [==============================] - 1s 657us/step
Independent Testing Matthews Correlation:  0.4357865506272417
Confusion Matrix :
 [[3036 1287]
 [1153 3170]]
Accuracy on test set:    0.7177885727504049
Sensitivity:    0.7332870691649318 	 Specificity:    0.7022900763358778
Precision  : 0.7112407448956697
Area Under Curve:    0.7177885727504049
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6021 - accuracy: 0.6719 - val_loss: 0.5571 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5577 - accuracy: 0.7109 - val_loss: 0.5569 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7230 - val_loss: 0.5466 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7322 - val_loss: 0.5441 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7365 - val_loss: 0.5372 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7410 - val_loss: 0.5386 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5102 - accuracy: 0.7449 - val_loss: 0.5368 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5042 - accuracy: 0.7495 - val_loss: 0.5364 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7531 - val_loss: 0.5409 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7585 - val_loss: 0.5474 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7612 - val_loss: 0.5453 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4781 - accuracy: 0.7657 - val_loss: 0.5451 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 13/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4691 - accuracy: 0.7711
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4697 - accuracy: 0.7708 - val_loss: 0.5444 - val_accuracy: 0.7253 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4594096943993274
Confusion Matrix :
 [[3166 1157]
 [1180 3143]]
Accuracy on test set:    0.7297015961138098
Sensitivity:    0.7270414064307195 	 Specificity:    0.7323617857969003
Precision  : 0.7309302325581395
Area Under Curve:    0.7297015961138098
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6013 - accuracy: 0.6712 - val_loss: 0.5727 - val_accuracy: 0.7003 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7137 - val_loss: 0.5501 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7228 - val_loss: 0.5448 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7291 - val_loss: 0.5415 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7337 - val_loss: 0.5409 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5197 - accuracy: 0.7393 - val_loss: 0.5409 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7453 - val_loss: 0.5359 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7478 - val_loss: 0.5396 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7511 - val_loss: 0.5382 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4939 - accuracy: 0.7544
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7537 - val_loss: 0.5413 - val_accuracy: 0.7268 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.45902486693824535
Confusion Matrix :
 [[3379  944]
 [1406 2917]]
Accuracy on test set:    0.7281980106407587
Sensitivity:    0.674762896136942 	 Specificity:    0.7816331251445755
Precision  : 0.7555037555037555
Area Under Curve:    0.7281980106407587
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6148 - accuracy: 0.6604 - val_loss: 0.5697 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5629 - accuracy: 0.7099 - val_loss: 0.5514 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7224 - val_loss: 0.5655 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7303 - val_loss: 0.5383 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5267 - accuracy: 0.7342 - val_loss: 0.5417 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5208 - accuracy: 0.7380 - val_loss: 0.5478 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7426 - val_loss: 0.5410 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7453 - val_loss: 0.5418 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7500 - val_loss: 0.5391 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7552 - val_loss: 0.5411 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7587 - val_loss: 0.5432 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4822 - accuracy: 0.7619
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4830 - accuracy: 0.7610 - val_loss: 0.5402 - val_accuracy: 0.7223 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.47419432189620375
Confusion Matrix :
 [[3034 1289]
 [ 989 3334]]
Accuracy on test set:    0.7365255609530419
Sensitivity:    0.7712236872542216 	 Specificity:    0.7018274346518621
Precision  : 0.7211767250703006
Area Under Curve:    0.7365255609530419
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6190 - accuracy: 0.6522 - val_loss: 0.5677 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5721 - accuracy: 0.7015 - val_loss: 0.5571 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7130 - val_loss: 0.5504 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5486 - accuracy: 0.7199 - val_loss: 0.5477 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7260 - val_loss: 0.5443 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7296 - val_loss: 0.5412 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5300 - accuracy: 0.7320 - val_loss: 0.5438 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5220 - accuracy: 0.7374 - val_loss: 0.5437 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7407 - val_loss: 0.5429 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7453 - val_loss: 0.5441 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7470 - val_loss: 0.5414 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4996 - accuracy: 0.7515 - val_loss: 0.5480 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7549 - val_loss: 0.5478 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4881 - accuracy: 0.7593
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7583 - val_loss: 0.5516 - val_accuracy: 0.7146 - lr: 0.0010

271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.5147133758981383
Confusion Matrix :
 [[3024 1299]
 [ 813 3510]]
Accuracy on test set:    0.7557251908396947
Sensitivity:    0.8119361554476058 	 Specificity:    0.6995142262317835
Precision  : 0.7298814722395508
Area Under Curve:    0.7557251908396946
(8646, 4352) (8646,)
Mean MCC = 0.4498 + 0.0277 and Mean AUC = 0.7238 + 0.0138
Mean Sensitivity = 0.7362 + 0.0548 and Mean Specificity = 0.7114 + 0.0462 and Mean Accuracy = 0.7238 + 0.0138
Mean Precision = 0.7200 + 0.0214





Seed   : 333559
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6095 - accuracy: 0.6635 - val_loss: 0.5656 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5583 - accuracy: 0.7113 - val_loss: 0.5612 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7214 - val_loss: 0.5541 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7285 - val_loss: 0.5455 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5249 - accuracy: 0.7348 - val_loss: 0.5432 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7379 - val_loss: 0.5438 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7422 - val_loss: 0.5370 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7484 - val_loss: 0.5357 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7524 - val_loss: 0.5412 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7537 - val_loss: 0.5455 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7567 - val_loss: 0.5346 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4809 - accuracy: 0.7613 - val_loss: 0.5419 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4753 - accuracy: 0.7637 - val_loss: 0.5405 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7705 - val_loss: 0.5409 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4611 - accuracy: 0.7735 - val_loss: 0.5515 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4550 - accuracy: 0.7762 - val_loss: 0.5663 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4495 - accuracy: 0.7785 - val_loss: 0.5561 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 18/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4438 - accuracy: 0.7817
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4445 - accuracy: 0.7812 - val_loss: 0.5469 - val_accuracy: 0.7251 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.42124655415352463
Confusion Matrix :
 [[2865 1458]
 [1052 3271]]
Accuracy on test set:    0.7096923432801295
Sensitivity:    0.7566504742077261 	 Specificity:    0.6627342123525329
Precision  : 0.6916895749629943
Area Under Curve:    0.7096923432801295
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6029 - accuracy: 0.6707 - val_loss: 0.5722 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5578 - accuracy: 0.7118 - val_loss: 0.5610 - val_accuracy: 0.7026 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7234 - val_loss: 0.5506 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7303 - val_loss: 0.5445 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5225 - accuracy: 0.7378 - val_loss: 0.5464 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7416 - val_loss: 0.5513 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7442 - val_loss: 0.5509 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4999 - accuracy: 0.7498 - val_loss: 0.5440 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4940 - accuracy: 0.7552
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7549 - val_loss: 0.5473 - val_accuracy: 0.7205 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.43578033322759063
Confusion Matrix :
 [[3006 1317]
 [1124 3199]]
Accuracy on test set:    0.7176729123294009
Sensitivity:    0.7399953735831598 	 Specificity:    0.6953504510756419
Precision  : 0.70837023914969
Area Under Curve:    0.7176729123294009
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6050 - accuracy: 0.6680 - val_loss: 0.5705 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5572 - accuracy: 0.7104 - val_loss: 0.5612 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7245 - val_loss: 0.5513 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5287 - accuracy: 0.7320 - val_loss: 0.5502 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5218 - accuracy: 0.7364 - val_loss: 0.5444 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7426 - val_loss: 0.5471 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7484 - val_loss: 0.5456 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7496 - val_loss: 0.5492 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7546 - val_loss: 0.5476 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7590 - val_loss: 0.5479 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7643 - val_loss: 0.5568 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4724 - accuracy: 0.7680 - val_loss: 0.5488 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4670 - accuracy: 0.7705 - val_loss: 0.5483 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4601 - accuracy: 0.7742
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4604 - accuracy: 0.7741 - val_loss: 0.5534 - val_accuracy: 0.7172 - lr: 0.0010

271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.45341372334899943
Confusion Matrix :
 [[2968 1355]
 [1014 3309]]
Accuracy on test set:    0.726000462641684
Sensitivity:    0.765440666204025 	 Specificity:    0.686560259079343
Precision  : 0.7094768439108061
Area Under Curve:    0.7260004626416839
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6084 - accuracy: 0.6629 - val_loss: 0.5675 - val_accuracy: 0.7006 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5580 - accuracy: 0.7129 - val_loss: 0.5533 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7233 - val_loss: 0.5471 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7293 - val_loss: 0.5392 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5270 - accuracy: 0.7331 - val_loss: 0.5380 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5178 - accuracy: 0.7395 - val_loss: 0.5399 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7423 - val_loss: 0.5369 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5052 - accuracy: 0.7481 - val_loss: 0.5361 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4985 - accuracy: 0.7521 - val_loss: 0.5359 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7550 - val_loss: 0.5375 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4855 - accuracy: 0.7593 - val_loss: 0.5376 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4778 - accuracy: 0.7650 - val_loss: 0.5421 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4724 - accuracy: 0.7678
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4732 - accuracy: 0.7672 - val_loss: 0.5388 - val_accuracy: 0.7244 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.4271228530082911
Confusion Matrix :
 [[2887 1436]
 [1048 3275]]
Accuracy on test set:    0.7126995142262318
Sensitivity:    0.7575757575757576 	 Specificity:    0.667823270876706
Precision  : 0.6951814901294842
Area Under Curve:    0.7126995142262318
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6077 - accuracy: 0.6655 - val_loss: 0.5662 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5590 - accuracy: 0.7122 - val_loss: 0.5575 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7224 - val_loss: 0.5481 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7283 - val_loss: 0.5435 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7335 - val_loss: 0.5421 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7403 - val_loss: 0.5403 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.7419 - val_loss: 0.5380 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7484 - val_loss: 0.5384 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7501 - val_loss: 0.5377 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4950 - accuracy: 0.7552 - val_loss: 0.5414 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7575 - val_loss: 0.5376 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4827 - accuracy: 0.7607 - val_loss: 0.5413 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7619 - val_loss: 0.5410 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4718 - accuracy: 0.7677 - val_loss: 0.5515 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4654 - accuracy: 0.7706
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4659 - accuracy: 0.7706 - val_loss: 0.5528 - val_accuracy: 0.7176 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.4125573646749561
Confusion Matrix :
 [[2708 1615]
 [ 946 3377]]
Accuracy on test set:    0.703793661808929
Sensitivity:    0.7811704834605598 	 Specificity:    0.6264168401572981
Precision  : 0.6764823717948718
Area Under Curve:    0.703793661808929
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6104 - accuracy: 0.6628 - val_loss: 0.5753 - val_accuracy: 0.7011 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5618 - accuracy: 0.7105 - val_loss: 0.5527 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7227 - val_loss: 0.5495 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7286 - val_loss: 0.5438 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7349 - val_loss: 0.5404 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7375 - val_loss: 0.5430 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7423 - val_loss: 0.5419 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7485 - val_loss: 0.5395 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7502 - val_loss: 0.5451 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4963 - accuracy: 0.7546
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4966 - accuracy: 0.7547 - val_loss: 0.5475 - val_accuracy: 0.7233 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.43743345675829065
Confusion Matrix :
 [[3206 1117]
 [1317 3006]]
Accuracy on test set:    0.7184825352764284
Sensitivity:    0.6953504510756419 	 Specificity:    0.7416146194772149
Precision  : 0.7290807664322095
Area Under Curve:    0.7184825352764284
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6252 - accuracy: 0.6542 - val_loss: 0.5706 - val_accuracy: 0.6942 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5641 - accuracy: 0.7068 - val_loss: 0.5588 - val_accuracy: 0.7089 - lr: 0.0010

Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7213 - val_loss: 0.5495 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7279 - val_loss: 0.5518 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5278 - accuracy: 0.7338 - val_loss: 0.5440 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5189 - accuracy: 0.7402 - val_loss: 0.5457 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7413 - val_loss: 0.5419 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7475 - val_loss: 0.5414 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4988 - accuracy: 0.7525 - val_loss: 0.5528 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4947 - accuracy: 0.7527 - val_loss: 0.5451 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4861 - accuracy: 0.7603 - val_loss: 0.5469 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7626 - val_loss: 0.5490 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 13/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4731 - accuracy: 0.7671
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4739 - accuracy: 0.7666 - val_loss: 0.5547 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 665us/step
Independent Testing Matthews Correlation:  0.4570281073669044
Confusion Matrix :
 [[3058 1265]
 [1084 3239]]
Accuracy on test set:    0.7283136710617627
Sensitivity:    0.7492482072634744 	 Specificity:    0.7073791348600509
Precision  : 0.7191385435168739
Area Under Curve:    0.7283136710617626
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6126 - accuracy: 0.6635 - val_loss: 0.5688 - val_accuracy: 0.7038 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7098 - val_loss: 0.5550 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7230 - val_loss: 0.5494 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7291 - val_loss: 0.5472 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5285 - accuracy: 0.7341 - val_loss: 0.5529 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5222 - accuracy: 0.7378 - val_loss: 0.5439 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5149 - accuracy: 0.7431 - val_loss: 0.5463 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7454 - val_loss: 0.5454 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7501 - val_loss: 0.5494 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7535 - val_loss: 0.5445 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4899 - accuracy: 0.7574 - val_loss: 0.5488 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4865 - accuracy: 0.7592 - val_loss: 0.5502 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7620 - val_loss: 0.5482 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4741 - accuracy: 0.7661 - val_loss: 0.5465 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4669 - accuracy: 0.7710 - val_loss: 0.5544 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4641 - accuracy: 0.7717 - val_loss: 0.5569 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4568 - accuracy: 0.7776
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4569 - accuracy: 0.7772 - val_loss: 0.5561 - val_accuracy: 0.7217 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.45667896733039604
Confusion Matrix :
 [[3116 1207]
 [1142 3181]]
Accuracy on test set:    0.7283136710617627
Sensitivity:    0.7358315984270183 	 Specificity:    0.720795743696507
Precision  : 0.7249316317228806
Area Under Curve:    0.7283136710617627
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6093 - accuracy: 0.6640 - val_loss: 0.5702 - val_accuracy: 0.7033 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5638 - accuracy: 0.7094 - val_loss: 0.5530 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7207 - val_loss: 0.5522 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7272 - val_loss: 0.5465 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5263 - accuracy: 0.7353 - val_loss: 0.5459 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7379 - val_loss: 0.5473 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7422 - val_loss: 0.5448 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7462 - val_loss: 0.5446 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5022 - accuracy: 0.7506 - val_loss: 0.5429 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7528 - val_loss: 0.5532 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7575 - val_loss: 0.5469 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 12/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4847 - accuracy: 0.7603
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7605 - val_loss: 0.5503 - val_accuracy: 0.7194 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4762411357753779
Confusion Matrix :
 [[3077 1246]
 [1021 3302]]
Accuracy on test set:    0.7377978255840851
Sensitivity:    0.7638214203099699 	 Specificity:    0.7117742308582004
Precision  : 0.7260334212840809
Area Under Curve:    0.7377978255840851
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6079 - accuracy: 0.6655 - val_loss: 0.5669 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5641 - accuracy: 0.7070 - val_loss: 0.5578 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 3/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7193 - val_loss: 0.5457 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7243 - val_loss: 0.5541 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7314 - val_loss: 0.5453 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7342 - val_loss: 0.5512 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7416 - val_loss: 0.5428 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5092 - accuracy: 0.7465
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7457 - val_loss: 0.5473 - val_accuracy: 0.7170 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.505631881595765
Confusion Matrix :
 [[3014 1309]
 [ 841 3482]]
Accuracy on test set:    0.7513300948415452
Sensitivity:    0.8054591718713856 	 Specificity:    0.6972010178117048
Precision  : 0.7267793780004175
Area Under Curve:    0.7513300948415452
(8646, 4352) (8646,)
Mean MCC = 0.4483 + 0.0264 and Mean AUC = 0.7234 + 0.0134
Mean Sensitivity = 0.7551 + 0.0276 and Mean Specificity = 0.6918 + 0.0312 and Mean Accuracy = 0.7234 + 0.0134
Mean Precision = 0.7107 + 0.0170





Seed   : 470796
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6030 - accuracy: 0.6711 - val_loss: 0.5670 - val_accuracy: 0.7038 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5574 - accuracy: 0.7126 - val_loss: 0.5525 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7241 - val_loss: 0.5462 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5319 - accuracy: 0.7322 - val_loss: 0.5505 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5252 - accuracy: 0.7322 - val_loss: 0.5453 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5178 - accuracy: 0.7405 - val_loss: 0.5397 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7439 - val_loss: 0.5429 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7497 - val_loss: 0.5472 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7508 - val_loss: 0.5414 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7553 - val_loss: 0.5418 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4884 - accuracy: 0.7586 - val_loss: 0.5417 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7633 - val_loss: 0.5571 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4753 - accuracy: 0.7651 - val_loss: 0.5501 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4689 - accuracy: 0.7690 - val_loss: 0.5479 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4636 - accuracy: 0.7730 - val_loss: 0.5616 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4549 - accuracy: 0.7800 - val_loss: 0.5593 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4511 - accuracy: 0.7796 - val_loss: 0.5617 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4460 - accuracy: 0.7826
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4461 - accuracy: 0.7824 - val_loss: 0.5661 - val_accuracy: 0.7231 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.42805712951157965
Confusion Matrix :
 [[2724 1599]
 [ 898 3425]]
Accuracy on test set:    0.7111959287531806
Sensitivity:    0.7922738838769373 	 Specificity:    0.630117973629424
Precision  : 0.6817277070063694
Area Under Curve:    0.7111959287531807
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6092 - accuracy: 0.6644 - val_loss: 0.5702 - val_accuracy: 0.7001 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5577 - accuracy: 0.7121 - val_loss: 0.5586 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7234 - val_loss: 0.5545 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7319 - val_loss: 0.5466 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5227 - accuracy: 0.7363 - val_loss: 0.5448 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7411 - val_loss: 0.5451 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7462 - val_loss: 0.5421 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5022 - accuracy: 0.7488 - val_loss: 0.5457 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4947 - accuracy: 0.7525 - val_loss: 0.5416 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7555 - val_loss: 0.5389 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7575 - val_loss: 0.5498 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4788 - accuracy: 0.7637 - val_loss: 0.5427 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4725 - accuracy: 0.7679 - val_loss: 0.5498 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4690 - accuracy: 0.7674 - val_loss: 0.5457 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4610 - accuracy: 0.7727
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4611 - accuracy: 0.7727 - val_loss: 0.5485 - val_accuracy: 0.7249 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4417305790708312
Confusion Matrix :
 [[3027 1296]
 [1119 3204]]
Accuracy on test set:    0.7206800832755031
Sensitivity:    0.7411519777931992 	 Specificity:    0.7002081887578071
Precision  : 0.712
Area Under Curve:    0.7206800832755031
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6042 - accuracy: 0.6689 - val_loss: 0.5611 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5567 - accuracy: 0.7134 - val_loss: 0.5614 - val_accuracy: 0.7128 - lr: 0.0010

Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7223 - val_loss: 0.5441 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7284 - val_loss: 0.5444 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7356 - val_loss: 0.5420 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5205 - accuracy: 0.7356 - val_loss: 0.5479 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7432 - val_loss: 0.5414 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7443 - val_loss: 0.5420 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5012 - accuracy: 0.7481 - val_loss: 0.5419 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7522 - val_loss: 0.5373 - val_accuracy: 0.7330 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4890 - accuracy: 0.7546 - val_loss: 0.5448 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7563 - val_loss: 0.5485 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4775 - accuracy: 0.7619 - val_loss: 0.5475 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4731 - accuracy: 0.7637 - val_loss: 0.5501 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4676 - accuracy: 0.7666
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4682 - accuracy: 0.7665 - val_loss: 0.5471 - val_accuracy: 0.7263 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.43954697484113847
Confusion Matrix :
 [[2895 1428]
 [1004 3319]]
Accuracy on test set:    0.7187138561184363
Sensitivity:    0.7677538746241036 	 Specificity:    0.6696738376127689
Precision  : 0.699178428481146
Area Under Curve:    0.7187138561184363
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6058 - accuracy: 0.6673 - val_loss: 0.5714 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7120 - val_loss: 0.5564 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7228 - val_loss: 0.5517 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7305 - val_loss: 0.5420 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7340 - val_loss: 0.5466 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7393 - val_loss: 0.5453 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7457 - val_loss: 0.5439 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5037 - accuracy: 0.7488 - val_loss: 0.5391 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4985 - accuracy: 0.7525 - val_loss: 0.5407 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7561 - val_loss: 0.5400 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4883 - accuracy: 0.7600 - val_loss: 0.5445 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7607 - val_loss: 0.5432 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4747 - accuracy: 0.7663 - val_loss: 0.5488 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4700 - accuracy: 0.7687 - val_loss: 0.5466 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4652 - accuracy: 0.7697 - val_loss: 0.5519 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 16/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4595 - accuracy: 0.7755
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4594 - accuracy: 0.7752 - val_loss: 0.5549 - val_accuracy: 0.7250 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.4292657646447831
Confusion Matrix :
 [[2933 1390]
 [1082 3241]]
Accuracy on test set:    0.714087439278279
Sensitivity:    0.7497108489474902 	 Specificity:    0.6784640296090678
Precision  : 0.6998488447419564
Area Under Curve:    0.714087439278279
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6048 - accuracy: 0.6686 - val_loss: 0.5604 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7108 - val_loss: 0.5520 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7223 - val_loss: 0.5442 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7303 - val_loss: 0.5376 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5270 - accuracy: 0.7347 - val_loss: 0.5399 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5199 - accuracy: 0.7379 - val_loss: 0.5461 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7417 - val_loss: 0.5387 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5083 - accuracy: 0.7445 - val_loss: 0.5378 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5037 - accuracy: 0.7491 - val_loss: 0.5368 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4970 - accuracy: 0.7520 - val_loss: 0.5360 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7572 - val_loss: 0.5439 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4844 - accuracy: 0.7608 - val_loss: 0.5436 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4804 - accuracy: 0.7623 - val_loss: 0.5458 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4773 - accuracy: 0.7637
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4766 - accuracy: 0.7645 - val_loss: 0.5528 - val_accuracy: 0.7272 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.44258816221592656
Confusion Matrix :
 [[2857 1466]
 [ 957 3366]]
Accuracy on test set:    0.7197547999074717
Sensitivity:    0.7786259541984732 	 Specificity:    0.6608836456164701
Precision  : 0.6966059602649006
Area Under Curve:    0.7197547999074716
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6067 - accuracy: 0.6669 - val_loss: 0.5623 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7100 - val_loss: 0.5443 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7244 - val_loss: 0.5417 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7311 - val_loss: 0.5365 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7356 - val_loss: 0.5478 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5194 - accuracy: 0.7392 - val_loss: 0.5428 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7426 - val_loss: 0.5345 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7479 - val_loss: 0.5330 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5002 - accuracy: 0.7518 - val_loss: 0.5357 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7570 - val_loss: 0.5355 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4861 - accuracy: 0.7590 - val_loss: 0.5318 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7628 - val_loss: 0.5428 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4746 - accuracy: 0.7666 - val_loss: 0.5360 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4676 - accuracy: 0.7712 - val_loss: 0.5397 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4627 - accuracy: 0.7733 - val_loss: 0.5388 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4579 - accuracy: 0.7761 - val_loss: 0.5394 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4513 - accuracy: 0.7793 - val_loss: 0.5507 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 18/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4453 - accuracy: 0.7816
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4454 - accuracy: 0.7816 - val_loss: 0.5535 - val_accuracy: 0.7263 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4191399272030196
Confusion Matrix :
 [[2923 1400]
 [1115 3208]]
Accuracy on test set:    0.7091140411751099
Sensitivity:    0.7420772611612306 	 Specificity:    0.6761508211889892
Precision  : 0.6961805555555556
Area Under Curve:    0.7091140411751098
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6058 - accuracy: 0.6701 - val_loss: 0.5635 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5573 - accuracy: 0.7133 - val_loss: 0.5492 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7235 - val_loss: 0.5422 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7302 - val_loss: 0.5479 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7377 - val_loss: 0.5378 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7416 - val_loss: 0.5355 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5112 - accuracy: 0.7430 - val_loss: 0.5425 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7484 - val_loss: 0.5403 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5002 - accuracy: 0.7514 - val_loss: 0.5337 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4933 - accuracy: 0.7552 - val_loss: 0.5391 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7629 - val_loss: 0.5463 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4804 - accuracy: 0.7617 - val_loss: 0.5477 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4708 - accuracy: 0.7683
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4716 - accuracy: 0.7678 - val_loss: 0.5500 - val_accuracy: 0.7231 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.444365780682102
Confusion Matrix :
 [[3191 1132]
 [1271 3052]]
Accuracy on test set:    0.7220680083275504
Sensitivity:    0.7059912098080037 	 Specificity:    0.7381448068470969
Precision  : 0.7294455066921606
Area Under Curve:    0.7220680083275502
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6067 - accuracy: 0.6648 - val_loss: 0.5616 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5578 - accuracy: 0.7128 - val_loss: 0.5532 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7230 - val_loss: 0.5426 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7305 - val_loss: 0.5462 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7341 - val_loss: 0.5389 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5200 - accuracy: 0.7377 - val_loss: 0.5382 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7424 - val_loss: 0.5347 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5063 - accuracy: 0.7480 - val_loss: 0.5346 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5009 - accuracy: 0.7509 - val_loss: 0.5343 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7557 - val_loss: 0.5359 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4883 - accuracy: 0.7592 - val_loss: 0.5379 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7611 - val_loss: 0.5410 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4775 - accuracy: 0.7644 - val_loss: 0.5414 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4726 - accuracy: 0.7687
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4726 - accuracy: 0.7687 - val_loss: 0.5446 - val_accuracy: 0.7228 - lr: 0.0010

271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4530606998199057
Confusion Matrix :
 [[2947 1376]
 [ 996 3327]]
Accuracy on test set:    0.7256534813786722
Sensitivity:    0.7696044413601666 	 Specificity:    0.6817025213971779
Precision  : 0.7074207952370827
Area Under Curve:    0.7256534813786722
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6058 - accuracy: 0.6662 - val_loss: 0.5648 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5631 - accuracy: 0.7097 - val_loss: 0.5484 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7211 - val_loss: 0.5450 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7271 - val_loss: 0.5400 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5294 - accuracy: 0.7334 - val_loss: 0.5394 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5256 - accuracy: 0.7334 - val_loss: 0.5361 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7386 - val_loss: 0.5410 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7440 - val_loss: 0.5337 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7470 - val_loss: 0.5366 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5014 - accuracy: 0.7507 - val_loss: 0.5372 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7539 - val_loss: 0.5461 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7572 - val_loss: 0.5445 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4844 - accuracy: 0.7608 - val_loss: 0.5346 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4808 - accuracy: 0.7612
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7613 - val_loss: 0.5388 - val_accuracy: 0.7278 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.4681503872874912
Confusion Matrix :
 [[3081 1242]
 [1059 3264]]
Accuracy on test set:    0.7338653712699514
Sensitivity:    0.7550312283136711 	 Specificity:    0.7126995142262318
Precision  : 0.7243675099866844
Area Under Curve:    0.7338653712699514
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6060 - accuracy: 0.6679 - val_loss: 0.5626 - val_accuracy: 0.7092 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5624 - accuracy: 0.7115 - val_loss: 0.5504 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7196 - val_loss: 0.5487 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7281 - val_loss: 0.5427 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7312 - val_loss: 0.5417 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5261 - accuracy: 0.7368 - val_loss: 0.5378 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7400 - val_loss: 0.5462 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5130 - accuracy: 0.7440 - val_loss: 0.5387 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7461 - val_loss: 0.5368 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7515 - val_loss: 0.5393 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7527 - val_loss: 0.5400 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7600 - val_loss: 0.5423 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7622 - val_loss: 0.5461 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4785 - accuracy: 0.7657 - val_loss: 0.5437 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4727 - accuracy: 0.7706
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4738 - accuracy: 0.7700 - val_loss: 0.5487 - val_accuracy: 0.7192 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.48437374506026787
Confusion Matrix :
 [[3442  881]
 [1361 2962]]
Accuracy on test set:    0.7406893361091834
Sensitivity:    0.6851723340272958 	 Specificity:    0.796206338191071
Precision  : 0.770752016653656
Area Under Curve:    0.7406893361091834
(8646, 4352) (8646,)
Mean MCC = 0.4450 + 0.0184 and Mean AUC = 0.7216 + 0.0093
Mean Sensitivity = 0.7487 + 0.0310 and Mean Specificity = 0.6944 + 0.0439 and Mean Accuracy = 0.7216 + 0.0093
Mean Precision = 0.7118 + 0.0238





Seed   : 455564
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6043 - accuracy: 0.6687 - val_loss: 0.5841 - val_accuracy: 0.6862 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7125 - val_loss: 0.5564 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7251 - val_loss: 0.5417 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7302 - val_loss: 0.5504 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5222 - accuracy: 0.7368 - val_loss: 0.5384 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7417 - val_loss: 0.5434 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7463 - val_loss: 0.5363 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7488 - val_loss: 0.5326 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7514 - val_loss: 0.5323 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7571 - val_loss: 0.5344 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7604 - val_loss: 0.5342 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4796 - accuracy: 0.7614 - val_loss: 0.5370 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4741 - accuracy: 0.7650 - val_loss: 0.5432 - val_accuracy: 0.7250 - lr: 0.0010

Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4655 - accuracy: 0.7708 - val_loss: 0.5468 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4629 - accuracy: 0.7714 - val_loss: 0.5424 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4540 - accuracy: 0.7771
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4552 - accuracy: 0.7763 - val_loss: 0.5447 - val_accuracy: 0.7186 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.4252162821972613
Confusion Matrix :
 [[2848 1475]
 [1020 3303]]
Accuracy on test set:    0.7114272495951885
Sensitivity:    0.7640527411519777 	 Specificity:    0.6588017580383992
Precision  : 0.6912934282126413
Area Under Curve:    0.7114272495951884
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6090 - accuracy: 0.6668 - val_loss: 0.5659 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5583 - accuracy: 0.7112 - val_loss: 0.5528 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7243 - val_loss: 0.5503 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5307 - accuracy: 0.7320 - val_loss: 0.5409 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5231 - accuracy: 0.7349 - val_loss: 0.5393 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7403 - val_loss: 0.5404 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5078 - accuracy: 0.7459 - val_loss: 0.5424 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7494 - val_loss: 0.5407 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7531 - val_loss: 0.5346 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4878 - accuracy: 0.7567 - val_loss: 0.5364 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7600 - val_loss: 0.5409 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4776 - accuracy: 0.7642 - val_loss: 0.5403 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4718 - accuracy: 0.7671 - val_loss: 0.5479 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4643 - accuracy: 0.7733
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4641 - accuracy: 0.7735 - val_loss: 0.5506 - val_accuracy: 0.7169 - lr: 0.0010
271/271 [==============================] - 1s 655us/step
Independent Testing Matthews Correlation:  0.422055677361523
Confusion Matrix :
 [[3224 1099]
 [1404 2919]]
Accuracy on test set:    0.7105019662271571
Sensitivity:    0.6752255378209576 	 Specificity:    0.7457783946333565
Precision  : 0.7264808362369338
Area Under Curve:    0.7105019662271571
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6097 - accuracy: 0.6653 - val_loss: 0.5663 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7110 - val_loss: 0.5581 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7215 - val_loss: 0.5468 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7274 - val_loss: 0.5429 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7328 - val_loss: 0.5390 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5202 - accuracy: 0.7389 - val_loss: 0.5371 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7419 - val_loss: 0.5426 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7457 - val_loss: 0.5354 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7490 - val_loss: 0.5365 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7543 - val_loss: 0.5463 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4875 - accuracy: 0.7573
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7574 - val_loss: 0.5449 - val_accuracy: 0.7296 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4435082684681135
Confusion Matrix :
 [[2992 1331]
 [1078 3245]]
Accuracy on test set:    0.7213740458015268
Sensitivity:    0.7506361323155216 	 Specificity:    0.6921119592875318
Precision  : 0.7091346153846154
Area Under Curve:    0.7213740458015268
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6128 - accuracy: 0.6622 - val_loss: 0.5636 - val_accuracy: 0.7041 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7121 - val_loss: 0.5526 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7221 - val_loss: 0.5500 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7302 - val_loss: 0.5405 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7367 - val_loss: 0.5454 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5200 - accuracy: 0.7394 - val_loss: 0.5361 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7442 - val_loss: 0.5332 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7495 - val_loss: 0.5346 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7530 - val_loss: 0.5357 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4922 - accuracy: 0.7571 - val_loss: 0.5540 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7582 - val_loss: 0.5363 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 12/400
257/274 [===========================>..] - ETA: 0s - loss: 0.4780 - accuracy: 0.7659
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4790 - accuracy: 0.7650 - val_loss: 0.5434 - val_accuracy: 0.7262 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4314771356760789
Confusion Matrix :
 [[2792 1531]
 [ 944 3379]]
Accuracy on test set:    0.7137404580152672
Sensitivity:    0.7816331251445755 	 Specificity:    0.6458477908859588
Precision  : 0.6881873727087576
Area Under Curve:    0.7137404580152671
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 7s 3ms/step - loss: 0.6110 - accuracy: 0.6624 - val_loss: 0.5691 - val_accuracy: 0.6980 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7099 - val_loss: 0.5554 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7229 - val_loss: 0.5410 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7279 - val_loss: 0.5381 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7367 - val_loss: 0.5372 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7385 - val_loss: 0.5366 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7454 - val_loss: 0.5335 - val_accuracy: 0.7336 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7465 - val_loss: 0.5336 - val_accuracy: 0.7335 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7528 - val_loss: 0.5363 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7546 - val_loss: 0.5368 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4837 - accuracy: 0.7614 - val_loss: 0.5357 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4775 - accuracy: 0.7652
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4791 - accuracy: 0.7644 - val_loss: 0.5368 - val_accuracy: 0.7285 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.4433937995284793
Confusion Matrix :
 [[2792 1531]
 [ 896 3427]]
Accuracy on test set:    0.7192921582234559
Sensitivity:    0.7927365255609531 	 Specificity:    0.6458477908859588
Precision  : 0.6912061315046389
Area Under Curve:    0.7192921582234559
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6122 - accuracy: 0.6653 - val_loss: 0.5599 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7089 - val_loss: 0.5522 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7218 - val_loss: 0.5422 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7295 - val_loss: 0.5385 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7355 - val_loss: 0.5314 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5195 - accuracy: 0.7396 - val_loss: 0.5343 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7451 - val_loss: 0.5336 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7464 - val_loss: 0.5337 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7523 - val_loss: 0.5375 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4951 - accuracy: 0.7529 - val_loss: 0.5394 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4902 - accuracy: 0.7570 - val_loss: 0.5354 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4826 - accuracy: 0.7606
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7604 - val_loss: 0.5367 - val_accuracy: 0.7280 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4248401322584933
Confusion Matrix :
 [[3025 1298]
 [1189 3134]]
Accuracy on test set:    0.71235253296322
Sensitivity:    0.7249595188526486 	 Specificity:    0.6997455470737913
Precision  : 0.7071299638989169
Area Under Curve:    0.71235253296322
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6025 - accuracy: 0.6686 - val_loss: 0.5551 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5573 - accuracy: 0.7112 - val_loss: 0.5532 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7232 - val_loss: 0.5434 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7306 - val_loss: 0.5448 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7348 - val_loss: 0.5376 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7413 - val_loss: 0.5408 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7438 - val_loss: 0.5465 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7482 - val_loss: 0.5406 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7516 - val_loss: 0.5362 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7558 - val_loss: 0.5432 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7597 - val_loss: 0.5435 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4788 - accuracy: 0.7652 - val_loss: 0.5417 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4717 - accuracy: 0.7672 - val_loss: 0.5434 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4646 - accuracy: 0.7722 - val_loss: 0.5554 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4599 - accuracy: 0.7737 - val_loss: 0.5484 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4556 - accuracy: 0.7756
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4557 - accuracy: 0.7756 - val_loss: 0.5518 - val_accuracy: 0.7274 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.45102093460251574
Confusion Matrix :
 [[2983 1340]
 [1038 3285]]
Accuracy on test set:    0.7249595188526486
Sensitivity:    0.7598889659958362 	 Specificity:    0.6900300717094611
Precision  : 0.7102702702702702
Area Under Curve:    0.7249595188526486
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6077 - accuracy: 0.6670 - val_loss: 0.5605 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7132 - val_loss: 0.5460 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7254 - val_loss: 0.5435 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7311 - val_loss: 0.5414 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7361 - val_loss: 0.5496 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7411 - val_loss: 0.5403 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7451 - val_loss: 0.5371 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7505 - val_loss: 0.5389 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4966 - accuracy: 0.7532 - val_loss: 0.5441 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7586 - val_loss: 0.5454 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4842 - accuracy: 0.7604 - val_loss: 0.5434 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4748 - accuracy: 0.7673 - val_loss: 0.5503 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4675 - accuracy: 0.7715
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7712 - val_loss: 0.5523 - val_accuracy: 0.7246 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4627230612263425
Confusion Matrix :
 [[3017 1306]
 [1021 3302]]
Accuracy on test set:    0.7308582003238492
Sensitivity:    0.7638214203099699 	 Specificity:    0.6978949803377285
Precision  : 0.7165798611111112
Area Under Curve:    0.7308582003238492
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6153 - accuracy: 0.6598 - val_loss: 0.5710 - val_accuracy: 0.6984 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5641 - accuracy: 0.7099 - val_loss: 0.5503 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7205 - val_loss: 0.5444 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7273 - val_loss: 0.5428 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5285 - accuracy: 0.7333 - val_loss: 0.5397 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7375 - val_loss: 0.5390 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7448 - val_loss: 0.5369 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7469 - val_loss: 0.5411 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7489 - val_loss: 0.5378 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4978 - accuracy: 0.7521
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7525 - val_loss: 0.5458 - val_accuracy: 0.7282 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.47089072531714044
Confusion Matrix :
 [[2878 1445]
 [ 861 3462]]
Accuracy on test set:    0.7332870691649318
Sensitivity:    0.8008327550312283 	 Specificity:    0.6657413832986352
Precision  : 0.7055227226411249
Area Under Curve:    0.7332870691649318
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6142 - accuracy: 0.6599 - val_loss: 0.5614 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5656 - accuracy: 0.7064 - val_loss: 0.5753 - val_accuracy: 0.6868 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5522 - accuracy: 0.7173 - val_loss: 0.5449 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7256 - val_loss: 0.5481 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7315 - val_loss: 0.5388 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7377 - val_loss: 0.5374 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7400 - val_loss: 0.5416 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5111 - accuracy: 0.7462 - val_loss: 0.5461 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7512 - val_loss: 0.5415 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7542 - val_loss: 0.5444 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4898 - accuracy: 0.7595
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4899 - accuracy: 0.7593 - val_loss: 0.5455 - val_accuracy: 0.7292 - lr: 0.0010
271/271 [==============================] - 1s 653us/step
Independent Testing Matthews Correlation:  0.4823415877080164
Confusion Matrix :
 [[3231 1092]
 [1146 3177]]
Accuracy on test set:    0.7411519777931992
Sensitivity:    0.7349063150589868 	 Specificity:    0.7473976405274115
Precision  : 0.7442023893183415
Area Under Curve:    0.7411519777931992
(8646, 4352) (8646,)
Mean MCC = 0.4457 + 0.0198 and Mean AUC = 0.7219 + 0.0100
Mean Sensitivity = 0.7549 + 0.0348 and Mean Specificity = 0.6889 + 0.0347 and Mean Accuracy = 0.7219 + 0.0100
Mean Precision = 0.7090 + 0.0164





Seed   : 586464
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6190 - accuracy: 0.6540 - val_loss: 0.5718 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5628 - accuracy: 0.7100 - val_loss: 0.5545 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7218 - val_loss: 0.5477 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7283 - val_loss: 0.5430 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5294 - accuracy: 0.7337 - val_loss: 0.5362 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5214 - accuracy: 0.7380 - val_loss: 0.5367 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5144 - accuracy: 0.7409 - val_loss: 0.5411 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7436 - val_loss: 0.5387 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7475 - val_loss: 0.5390 - val_accuracy: 0.7231 - lr: 0.0010

Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7516 - val_loss: 0.5384 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7542 - val_loss: 0.5418 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4866 - accuracy: 0.7567 - val_loss: 0.5408 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 13/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4798 - accuracy: 0.7624
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4809 - accuracy: 0.7620 - val_loss: 0.5417 - val_accuracy: 0.7238 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.41263362362854833
Confusion Matrix :
 [[2768 1555]
 [ 999 3324]]
Accuracy on test set:    0.7046032847559565
Sensitivity:    0.768910478834143 	 Specificity:    0.64029609067777
Precision  : 0.6812871490059439
Area Under Curve:    0.7046032847559566
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6215 - accuracy: 0.6506 - val_loss: 0.5727 - val_accuracy: 0.7032 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5647 - accuracy: 0.7066 - val_loss: 0.5642 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7201 - val_loss: 0.5476 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7251 - val_loss: 0.5420 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7310 - val_loss: 0.5401 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5211 - accuracy: 0.7379 - val_loss: 0.5416 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5150 - accuracy: 0.7405 - val_loss: 0.5423 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5112 - accuracy: 0.7402 - val_loss: 0.5391 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5056 - accuracy: 0.7475 - val_loss: 0.5421 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5003 - accuracy: 0.7506
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5005 - accuracy: 0.7508 - val_loss: 0.5377 - val_accuracy: 0.7246 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.43542608669826344
Confusion Matrix :
 [[3061 1262]
 [1179 3144]]
Accuracy on test set:    0.7176729123294009
Sensitivity:    0.7272727272727273 	 Specificity:    0.7080730973860745
Precision  : 0.7135724012709941
Area Under Curve:    0.7176729123294009
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6013 - accuracy: 0.6713 - val_loss: 0.5554 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5558 - accuracy: 0.7132 - val_loss: 0.5418 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7216 - val_loss: 0.5376 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7306 - val_loss: 0.5400 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5219 - accuracy: 0.7373 - val_loss: 0.5333 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5167 - accuracy: 0.7415 - val_loss: 0.5348 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5091 - accuracy: 0.7463 - val_loss: 0.5440 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7468 - val_loss: 0.5316 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7533 - val_loss: 0.5344 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7550 - val_loss: 0.5346 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7629 - val_loss: 0.5448 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7661 - val_loss: 0.5371 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4709 - accuracy: 0.7693 - val_loss: 0.5399 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4672 - accuracy: 0.7711 - val_loss: 0.5403 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4608 - accuracy: 0.7755 - val_loss: 0.5406 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4528 - accuracy: 0.7812 - val_loss: 0.5422 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4474 - accuracy: 0.7819 - val_loss: 0.5409 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4411 - accuracy: 0.7843
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4412 - accuracy: 0.7844 - val_loss: 0.5486 - val_accuracy: 0.7287 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4271436860469793
Confusion Matrix :
 [[2827 1496]
 [ 993 3330]]
Accuracy on test set:    0.7121212121212122
Sensitivity:    0.7702984038861902 	 Specificity:    0.6539440203562341
Precision  : 0.6900124326564443
Area Under Curve:    0.7121212121212122
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6042 - accuracy: 0.6711 - val_loss: 0.5589 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5605 - accuracy: 0.7104 - val_loss: 0.5432 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7242 - val_loss: 0.5408 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7309 - val_loss: 0.5379 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5274 - accuracy: 0.7335 - val_loss: 0.5370 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7382 - val_loss: 0.5280 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7422 - val_loss: 0.5334 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5073 - accuracy: 0.7469 - val_loss: 0.5292 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7477 - val_loss: 0.5274 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7543 - val_loss: 0.5328 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 11/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7549 - val_loss: 0.5481 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7608 - val_loss: 0.5309 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7616 - val_loss: 0.5356 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 14/400
256/274 [===========================>..] - ETA: 0s - loss: 0.4746 - accuracy: 0.7645
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4753 - accuracy: 0.7638 - val_loss: 0.5403 - val_accuracy: 0.7287 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.44439035619536316
Confusion Matrix :
 [[3100 1223]
 [1179 3144]]
Accuracy on test set:    0.7221836687485542
Sensitivity:    0.7272727272727273 	 Specificity:    0.7170946102243813
Precision  : 0.7199450423631784
Area Under Curve:    0.7221836687485542
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6051 - accuracy: 0.6678 - val_loss: 0.5540 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5593 - accuracy: 0.7102 - val_loss: 0.5390 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7232 - val_loss: 0.5311 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7298 - val_loss: 0.5303 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5269 - accuracy: 0.7350 - val_loss: 0.5264 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5203 - accuracy: 0.7383 - val_loss: 0.5275 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7394 - val_loss: 0.5264 - val_accuracy: 0.7334 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7458 - val_loss: 0.5225 - val_accuracy: 0.7370 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7489 - val_loss: 0.5264 - val_accuracy: 0.7367 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7521 - val_loss: 0.5285 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7552 - val_loss: 0.5268 - val_accuracy: 0.7340 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7585 - val_loss: 0.5269 - val_accuracy: 0.7368 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4795 - accuracy: 0.7623
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4797 - accuracy: 0.7618 - val_loss: 0.5287 - val_accuracy: 0.7336 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.4408653943063573
Confusion Matrix :
 [[3018 1305]
 [1114 3209]]
Accuracy on test set:    0.7202174415914874
Sensitivity:    0.7423085820032385 	 Specificity:    0.6981263011797363
Precision  : 0.7108994240141782
Area Under Curve:    0.7202174415914874
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6077 - accuracy: 0.6645 - val_loss: 0.5462 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7106 - val_loss: 0.5402 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7222 - val_loss: 0.5310 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7280 - val_loss: 0.5295 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7326 - val_loss: 0.5255 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7377 - val_loss: 0.5355 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7427 - val_loss: 0.5244 - val_accuracy: 0.7370 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7462 - val_loss: 0.5347 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7503 - val_loss: 0.5276 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7550 - val_loss: 0.5324 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4860 - accuracy: 0.7590 - val_loss: 0.5293 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4805 - accuracy: 0.7624
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4809 - accuracy: 0.7625 - val_loss: 0.5262 - val_accuracy: 0.7296 - lr: 0.0010
271/271 [==============================] - 0s 665us/step
Independent Testing Matthews Correlation:  0.44681488556006643
Confusion Matrix :
 [[3180 1143]
 [1249 3074]]
Accuracy on test set:    0.7233402729585936
Sensitivity:    0.7110802683321767 	 Specificity:    0.7356002775850105
Precision  : 0.728954232866967
Area Under Curve:    0.7233402729585936
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6076 - accuracy: 0.6650 - val_loss: 0.5588 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7106 - val_loss: 0.5404 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7220 - val_loss: 0.5337 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7271 - val_loss: 0.5286 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5268 - accuracy: 0.7333 - val_loss: 0.5370 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5205 - accuracy: 0.7374 - val_loss: 0.5263 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5165 - accuracy: 0.7406 - val_loss: 0.5256 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7464 - val_loss: 0.5254 - val_accuracy: 0.7339 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7498 - val_loss: 0.5267 - val_accuracy: 0.7355 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7531 - val_loss: 0.5293 - val_accuracy: 0.7339 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4901 - accuracy: 0.7558 - val_loss: 0.5256 - val_accuracy: 0.7327 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7586 - val_loss: 0.5308 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4791 - accuracy: 0.7631 - val_loss: 0.5306 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 14/400
263/274 [===========================>..] - ETA: 0s - loss: 0.4736 - accuracy: 0.7660
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4739 - accuracy: 0.7661 - val_loss: 0.5298 - val_accuracy: 0.7305 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.45605541202651273
Confusion Matrix :
 [[3097 1226]
 [1126 3197]]
Accuracy on test set:    0.7279666897987509
Sensitivity:    0.7395327318991441 	 Specificity:    0.7164006476983577
Precision  : 0.7228125706534027
Area Under Curve:    0.7279666897987508
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6191 - accuracy: 0.6569 - val_loss: 0.5556 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5661 - accuracy: 0.7073 - val_loss: 0.5396 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7193 - val_loss: 0.5369 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7241 - val_loss: 0.5321 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7311 - val_loss: 0.5338 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5262 - accuracy: 0.7345 - val_loss: 0.5305 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5199 - accuracy: 0.7379 - val_loss: 0.5253 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7418 - val_loss: 0.5285 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5078 - accuracy: 0.7452 - val_loss: 0.5335 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5037 - accuracy: 0.7479 - val_loss: 0.5339 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7521 - val_loss: 0.5277 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7539 - val_loss: 0.5271 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4885 - accuracy: 0.7588
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7586 - val_loss: 0.5342 - val_accuracy: 0.7199 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.44063476918110067
Confusion Matrix :
 [[3376  947]
 [1486 2837]]
Accuracy on test set:    0.7185981956974323
Sensitivity:    0.6562572287763128 	 Specificity:    0.7809391626185519
Precision  : 0.7497357293868921
Area Under Curve:    0.7185981956974323
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6132 - accuracy: 0.6609 - val_loss: 0.5641 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5628 - accuracy: 0.7081 - val_loss: 0.5443 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7195 - val_loss: 0.5353 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7265 - val_loss: 0.5316 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5286 - accuracy: 0.7325 - val_loss: 0.5303 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5221 - accuracy: 0.7366 - val_loss: 0.5311 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7420 - val_loss: 0.5291 - val_accuracy: 0.7362 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7447 - val_loss: 0.5340 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7475 - val_loss: 0.5330 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4974 - accuracy: 0.7514 - val_loss: 0.5535 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4922 - accuracy: 0.7561 - val_loss: 0.5404 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4832 - accuracy: 0.7619
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7620 - val_loss: 0.5330 - val_accuracy: 0.7283 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4713043777163659
Confusion Matrix :
 [[3098 1225]
 [1062 3261]]
Accuracy on test set:    0.7354846171640065
Sensitivity:    0.7543372657876475 	 Specificity:    0.7166319685403655
Precision  : 0.726928221132412
Area Under Curve:    0.7354846171640065
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6126 - accuracy: 0.6626 - val_loss: 0.5600 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5648 - accuracy: 0.7085 - val_loss: 0.5587 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5494 - accuracy: 0.7190 - val_loss: 0.5429 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7271 - val_loss: 0.5423 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5297 - accuracy: 0.7319 - val_loss: 0.5396 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7378 - val_loss: 0.5332 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5164 - accuracy: 0.7418 - val_loss: 0.5366 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7422 - val_loss: 0.5355 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5078 - accuracy: 0.7463 - val_loss: 0.5345 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7522 - val_loss: 0.5360 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7550 - val_loss: 0.5341 - val_accuracy: 0.7331 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4858 - accuracy: 0.7588 - val_loss: 0.5372 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7635 - val_loss: 0.5451 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4726 - accuracy: 0.7681 - val_loss: 0.5478 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4687 - accuracy: 0.7692 - val_loss: 0.5482 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4625 - accuracy: 0.7728 - val_loss: 0.5458 - val_accuracy: 0.7348 - lr: 0.0010
Epoch 17/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4547 - accuracy: 0.7776 - val_loss: 0.5491 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4497 - accuracy: 0.7785 - val_loss: 0.5536 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4437 - accuracy: 0.7832 - val_loss: 0.5571 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4379 - accuracy: 0.7856 - val_loss: 0.5772 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 21/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4306 - accuracy: 0.7902
Epoch 21: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4313 - accuracy: 0.7896 - val_loss: 0.5860 - val_accuracy: 0.7269 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.5025886531946882
Confusion Matrix :
 [[3193 1130]
 [1021 3302]]
Accuracy on test set:    0.7512144344205413
Sensitivity:    0.7638214203099699 	 Specificity:    0.7386074485311126
Precision  : 0.7450361010830325
Area Under Curve:    0.7512144344205414
(8646, 4352) (8646,)
Mean MCC = 0.4478 + 0.0236 and Mean AUC = 0.7233 + 0.0122
Mean Sensitivity = 0.7361 + 0.0325 and Mean Specificity = 0.7106 + 0.0384 and Mean Accuracy = 0.7233 + 0.0122
Mean Precision = 0.7189 + 0.0204





Seed   : 991499
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5972 - accuracy: 0.6732 - val_loss: 0.5715 - val_accuracy: 0.6985 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5531 - accuracy: 0.7141 - val_loss: 0.5447 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7281 - val_loss: 0.5494 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5280 - accuracy: 0.7345 - val_loss: 0.5403 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7407 - val_loss: 0.5382 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7450 - val_loss: 0.5380 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7490 - val_loss: 0.5379 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7512 - val_loss: 0.5390 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7545 - val_loss: 0.5357 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7592 - val_loss: 0.5335 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7645 - val_loss: 0.5411 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4712 - accuracy: 0.7706
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4714 - accuracy: 0.7701 - val_loss: 0.5466 - val_accuracy: 0.7241 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4196850706332984
Confusion Matrix :
 [[2858 1465]
 [1052 3271]]
Accuracy on test set:    0.7088827203331021
Sensitivity:    0.7566504742077261 	 Specificity:    0.6611149664584779
Precision  : 0.6906672297297297
Area Under Curve:    0.7088827203331021
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6086 - accuracy: 0.6625 - val_loss: 0.5691 - val_accuracy: 0.6965 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5570 - accuracy: 0.7127 - val_loss: 0.5581 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7238 - val_loss: 0.5474 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7306 - val_loss: 0.5426 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5231 - accuracy: 0.7356 - val_loss: 0.5422 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7406 - val_loss: 0.5400 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7450 - val_loss: 0.5434 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7482 - val_loss: 0.5399 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4973 - accuracy: 0.7511 - val_loss: 0.5378 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7584 - val_loss: 0.5389 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7607 - val_loss: 0.5400 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7640 - val_loss: 0.5410 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4733 - accuracy: 0.7671 - val_loss: 0.5495 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4718 - accuracy: 0.7679
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4717 - accuracy: 0.7683 - val_loss: 0.5537 - val_accuracy: 0.7200 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.4294351870781384
Confusion Matrix :
 [[3042 1281]
 [1186 3137]]
Accuracy on test set:    0.7146657413832986
Sensitivity:    0.7256534813786722 	 Specificity:    0.703678001387925
Precision  : 0.7100497962879131
Area Under Curve:    0.7146657413832987
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6048 - accuracy: 0.6672 - val_loss: 0.5678 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5584 - accuracy: 0.7110 - val_loss: 0.5536 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7243 - val_loss: 0.5450 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7308 - val_loss: 0.5481 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7335 - val_loss: 0.5429 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7379 - val_loss: 0.5392 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7436 - val_loss: 0.5375 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7465 - val_loss: 0.5410 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7492 - val_loss: 0.5424 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7539 - val_loss: 0.5457 - val_accuracy: 0.7228 - lr: 0.0010

Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7591 - val_loss: 0.5436 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4839 - accuracy: 0.7609
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7608 - val_loss: 0.5425 - val_accuracy: 0.7210 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4512196242572416
Confusion Matrix :
 [[2885 1438]
 [ 947 3376]]
Accuracy on test set:    0.7241498959056211
Sensitivity:    0.7809391626185519 	 Specificity:    0.6673606291926902
Precision  : 0.7012879102617366
Area Under Curve:    0.7241498959056212
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6026 - accuracy: 0.6710 - val_loss: 0.5697 - val_accuracy: 0.6965 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5547 - accuracy: 0.7173 - val_loss: 0.5485 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7254 - val_loss: 0.5410 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5281 - accuracy: 0.7326 - val_loss: 0.5416 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7398 - val_loss: 0.5358 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7422 - val_loss: 0.5385 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7474 - val_loss: 0.5351 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5025 - accuracy: 0.7507 - val_loss: 0.5407 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4960 - accuracy: 0.7550 - val_loss: 0.5360 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7594 - val_loss: 0.5436 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4820 - accuracy: 0.7631 - val_loss: 0.5389 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4781 - accuracy: 0.7663 - val_loss: 0.5471 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4712 - accuracy: 0.7683 - val_loss: 0.5541 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4650 - accuracy: 0.7715 - val_loss: 0.5472 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4587 - accuracy: 0.7777
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4588 - accuracy: 0.7773 - val_loss: 0.5512 - val_accuracy: 0.7240 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.43035212353137653
Confusion Matrix :
 [[3137 1186]
 [1277 3046]]
Accuracy on test set:    0.7151283830673144
Sensitivity:    0.7046032847559565 	 Specificity:    0.7256534813786722
Precision  : 0.7197542533081286
Area Under Curve:    0.7151283830673142
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.5987 - accuracy: 0.6754 - val_loss: 0.5566 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7161 - val_loss: 0.5519 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7241 - val_loss: 0.5399 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7293 - val_loss: 0.5394 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7371 - val_loss: 0.5351 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7404 - val_loss: 0.5369 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7432 - val_loss: 0.5445 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7470 - val_loss: 0.5365 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7514 - val_loss: 0.5413 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4981 - accuracy: 0.7537 - val_loss: 0.5442 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4918 - accuracy: 0.7563 - val_loss: 0.5384 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4875 - accuracy: 0.7593 - val_loss: 0.5427 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4816 - accuracy: 0.7625
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4822 - accuracy: 0.7623 - val_loss: 0.5391 - val_accuracy: 0.7228 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4423605105650079
Confusion Matrix :
 [[2925 1398]
 [1020 3303]]
Accuracy on test set:    0.7203331020124913
Sensitivity:    0.7640527411519777 	 Specificity:    0.6766134628730048
Precision  : 0.7026164645820038
Area Under Curve:    0.7203331020124912
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6070 - accuracy: 0.6677 - val_loss: 0.5638 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5584 - accuracy: 0.7120 - val_loss: 0.5420 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7261 - val_loss: 0.5412 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7295 - val_loss: 0.5389 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7382 - val_loss: 0.5423 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5187 - accuracy: 0.7414 - val_loss: 0.5361 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5106 - accuracy: 0.7443 - val_loss: 0.5379 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7491 - val_loss: 0.5362 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7528 - val_loss: 0.5369 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4924 - accuracy: 0.7570 - val_loss: 0.5331 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7623 - val_loss: 0.5343 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4774 - accuracy: 0.7653 - val_loss: 0.5363 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 13/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4733 - accuracy: 0.7667 - val_loss: 0.5492 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4681 - accuracy: 0.7709
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4685 - accuracy: 0.7709 - val_loss: 0.5417 - val_accuracy: 0.7262 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4437401606706701
Confusion Matrix :
 [[3158 1165]
 [1240 3083]]
Accuracy on test set:    0.7218366874855424
Sensitivity:    0.7131621559102476 	 Specificity:    0.7305112190608374
Precision  : 0.72575329566855
Area Under Curve:    0.7218366874855424
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6115 - accuracy: 0.6585 - val_loss: 0.5646 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5650 - accuracy: 0.7103 - val_loss: 0.5536 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5495 - accuracy: 0.7197 - val_loss: 0.5468 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7265 - val_loss: 0.5434 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7295 - val_loss: 0.5407 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5249 - accuracy: 0.7347 - val_loss: 0.5412 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5213 - accuracy: 0.7376 - val_loss: 0.5447 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 8/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5139 - accuracy: 0.7436
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7428 - val_loss: 0.5410 - val_accuracy: 0.7181 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4607062627934535
Confusion Matrix :
 [[3025 1298]
 [1037 3286]]
Accuracy on test set:    0.7299329169558177
Sensitivity:    0.760120286837844 	 Specificity:    0.6997455470737913
Precision  : 0.7168411867364747
Area Under Curve:    0.7299329169558176
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6108 - accuracy: 0.6624 - val_loss: 0.5628 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5619 - accuracy: 0.7085 - val_loss: 0.5484 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7188 - val_loss: 0.5521 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7282 - val_loss: 0.5406 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7324 - val_loss: 0.5389 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7357 - val_loss: 0.5414 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7405 - val_loss: 0.5384 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7448 - val_loss: 0.5388 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7496 - val_loss: 0.5398 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7542 - val_loss: 0.5402 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7571 - val_loss: 0.5394 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7602 - val_loss: 0.5514 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7610 - val_loss: 0.5496 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4718 - accuracy: 0.7685 - val_loss: 0.5493 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4660 - accuracy: 0.7717
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4665 - accuracy: 0.7712 - val_loss: 0.5499 - val_accuracy: 0.7224 - lr: 0.0010
271/271 [==============================] - 0s 665us/step
Independent Testing Matthews Correlation:  0.4545793471291103
Confusion Matrix :
 [[3042 1281]
 [1079 3244]]
Accuracy on test set:    0.7270414064307195
Sensitivity:    0.7504048114735138 	 Specificity:    0.703678001387925
Precision  : 0.7169060773480663
Area Under Curve:    0.7270414064307195
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6153 - accuracy: 0.6619 - val_loss: 0.5751 - val_accuracy: 0.6933 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5647 - accuracy: 0.7082 - val_loss: 0.5558 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7212 - val_loss: 0.5456 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7266 - val_loss: 0.5475 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5280 - accuracy: 0.7329 - val_loss: 0.5440 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5223 - accuracy: 0.7366 - val_loss: 0.5411 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7430 - val_loss: 0.5360 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7482 - val_loss: 0.5408 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7548 - val_loss: 0.5434 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7561 - val_loss: 0.5439 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4856 - accuracy: 0.7602 - val_loss: 0.5464 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7642 - val_loss: 0.5488 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4733 - accuracy: 0.7661 - val_loss: 0.5574 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4661 - accuracy: 0.7699 - val_loss: 0.5485 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4595 - accuracy: 0.7757 - val_loss: 0.5582 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 16/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4520 - accuracy: 0.7794
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4517 - accuracy: 0.7798 - val_loss: 0.5737 - val_accuracy: 0.7176 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.47541496774845876
Confusion Matrix :
 [[2980 1343]
 [ 934 3389]]
Accuracy on test set:    0.7366412213740458
Sensitivity:    0.7839463335646542 	 Specificity:    0.6893361091834375
Precision  : 0.7161876584953508
Area Under Curve:    0.7366412213740458
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6138 - accuracy: 0.6624 - val_loss: 0.5629 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5647 - accuracy: 0.7076 - val_loss: 0.5534 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5490 - accuracy: 0.7200 - val_loss: 0.5455 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7272 - val_loss: 0.5414 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7307 - val_loss: 0.5386 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5220 - accuracy: 0.7374 - val_loss: 0.5432 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5167 - accuracy: 0.7402 - val_loss: 0.5415 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7472 - val_loss: 0.5384 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7494 - val_loss: 0.5372 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4954 - accuracy: 0.7533 - val_loss: 0.5448 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4879 - accuracy: 0.7584 - val_loss: 0.5445 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4799 - accuracy: 0.7638 - val_loss: 0.5457 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 13/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4737 - accuracy: 0.7685
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4741 - accuracy: 0.7682 - val_loss: 0.5500 - val_accuracy: 0.7263 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4974052499075325
Confusion Matrix :
 [[3494  829]
 [1360 2963]]
Accuracy on test set:    0.7468193384223919
Sensitivity:    0.6854036548693038 	 Specificity:    0.80823502197548
Precision  : 0.7813818565400844
Area Under Curve:    0.7468193384223919
(8646, 4352) (8646,)
Mean MCC = 0.4505 + 0.0220 and Mean AUC = 0.7245 + 0.0107
Mean Sensitivity = 0.7425 + 0.0317 and Mean Specificity = 0.7066 + 0.0402 and Mean Accuracy = 0.7245 + 0.0107
Mean Precision = 0.7181 + 0.0233





Seed   : 275993
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6067 - accuracy: 0.6645 - val_loss: 0.5557 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7115 - val_loss: 0.5446 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7237 - val_loss: 0.5332 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7274 - val_loss: 0.5307 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7353 - val_loss: 0.5303 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5165 - accuracy: 0.7398 - val_loss: 0.5265 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7445 - val_loss: 0.5553 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5037 - accuracy: 0.7481 - val_loss: 0.5385 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4961 - accuracy: 0.7529 - val_loss: 0.5280 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4911 - accuracy: 0.7568 - val_loss: 0.5293 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4838 - accuracy: 0.7582
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7587 - val_loss: 0.5326 - val_accuracy: 0.7316 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.42503771721166306
Confusion Matrix :
 [[2994 1329]
 [1158 3165]]
Accuracy on test set:    0.71235253296322
Sensitivity:    0.7321304649548924 	 Specificity:    0.6925746009715475
Precision  : 0.7042723631508678
Area Under Curve:    0.7123525329632201
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6081 - accuracy: 0.6670 - val_loss: 0.5580 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7112 - val_loss: 0.5467 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7208 - val_loss: 0.5422 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7294 - val_loss: 0.5381 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7341 - val_loss: 0.5436 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7404 - val_loss: 0.5356 - val_accuracy: 0.7331 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7444 - val_loss: 0.5295 - val_accuracy: 0.7328 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7469 - val_loss: 0.5312 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7525 - val_loss: 0.5352 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7539 - val_loss: 0.5350 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4879 - accuracy: 0.7575
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4880 - accuracy: 0.7573 - val_loss: 0.5315 - val_accuracy: 0.7271 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4298121191846098
Confusion Matrix :
 [[2828 1495]
 [ 983 3340]]
Accuracy on test set:    0.7133934767522554
Sensitivity:    0.7726116123062688 	 Specificity:    0.6541753411982419
Precision  : 0.6907962771458118
Area Under Curve:    0.7133934767522554
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6101 - accuracy: 0.6634 - val_loss: 0.5611 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5587 - accuracy: 0.7105 - val_loss: 0.5483 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7213 - val_loss: 0.5400 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7293 - val_loss: 0.5425 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5274 - accuracy: 0.7339 - val_loss: 0.5373 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5213 - accuracy: 0.7375 - val_loss: 0.5358 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7391 - val_loss: 0.5385 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7443 - val_loss: 0.5391 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7484 - val_loss: 0.5374 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7523 - val_loss: 0.5382 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7575 - val_loss: 0.5415 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7577 - val_loss: 0.5396 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4788 - accuracy: 0.7615
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4788 - accuracy: 0.7615 - val_loss: 0.5461 - val_accuracy: 0.7262 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.43390005762524664
Confusion Matrix :
 [[3215 1108]
 [1342 2981]]
Accuracy on test set:    0.7166319685403655
Sensitivity:    0.6895674300254453 	 Specificity:    0.7436965070552857
Precision  : 0.7290291024700416
Area Under Curve:    0.7166319685403655
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6000 - accuracy: 0.6728 - val_loss: 0.5766 - val_accuracy: 0.6943 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5550 - accuracy: 0.7156 - val_loss: 0.5504 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7252 - val_loss: 0.5420 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7311 - val_loss: 0.5399 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.7370 - val_loss: 0.5341 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7422 - val_loss: 0.5358 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7439 - val_loss: 0.5339 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5054 - accuracy: 0.7465 - val_loss: 0.5361 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7549 - val_loss: 0.5352 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4914 - accuracy: 0.7552
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4924 - accuracy: 0.7549 - val_loss: 0.5382 - val_accuracy: 0.7224 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.43479399562481946
Confusion Matrix :
 [[2845 1478]
 [ 978 3345]]
Accuracy on test set:    0.7159380060143419
Sensitivity:    0.7737682165163081 	 Specificity:    0.6581077955123756
Precision  : 0.6935517312875803
Area Under Curve:    0.7159380060143418
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6061 - accuracy: 0.6646 - val_loss: 0.5547 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7109 - val_loss: 0.5466 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7226 - val_loss: 0.5416 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7278 - val_loss: 0.5368 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7348 - val_loss: 0.5438 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5172 - accuracy: 0.7410 - val_loss: 0.5365 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7422 - val_loss: 0.5370 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7471 - val_loss: 0.5458 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5014 - accuracy: 0.7489 - val_loss: 0.5388 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7531 - val_loss: 0.5392 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7582 - val_loss: 0.5413 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7603 - val_loss: 0.5403 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4761 - accuracy: 0.7661 - val_loss: 0.5481 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7667 - val_loss: 0.5581 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4623 - accuracy: 0.7732 - val_loss: 0.5594 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4603 - accuracy: 0.7737 - val_loss: 0.5453 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4540 - accuracy: 0.7771 - val_loss: 0.5515 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4492 - accuracy: 0.7795 - val_loss: 0.5579 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 19/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4458 - accuracy: 0.7817
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4463 - accuracy: 0.7814 - val_loss: 0.5567 - val_accuracy: 0.7308 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4344791435628003
Confusion Matrix :
 [[3065 1258]
 [1187 3136]]
Accuracy on test set:    0.7172102706453851
Sensitivity:    0.7254221605366643 	 Specificity:    0.7089983807541059
Precision  : 0.7137005006827492
Area Under Curve:    0.7172102706453851
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6065 - accuracy: 0.6656 - val_loss: 0.5648 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7115 - val_loss: 0.5480 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7232 - val_loss: 0.5379 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7304 - val_loss: 0.5363 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5276 - accuracy: 0.7339 - val_loss: 0.5359 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7404 - val_loss: 0.5339 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7430 - val_loss: 0.5351 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7477 - val_loss: 0.5363 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5008 - accuracy: 0.7500 - val_loss: 0.5342 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7518 - val_loss: 0.5362 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4880 - accuracy: 0.7573 - val_loss: 0.5309 - val_accuracy: 0.7337 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4822 - accuracy: 0.7620 - val_loss: 0.5345 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4760 - accuracy: 0.7639 - val_loss: 0.5374 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4716 - accuracy: 0.7671 - val_loss: 0.5410 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4650 - accuracy: 0.7708 - val_loss: 0.5492 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4587 - accuracy: 0.7737
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4586 - accuracy: 0.7738 - val_loss: 0.5646 - val_accuracy: 0.7305 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.44928781010956453
Confusion Matrix :
 [[3027 1296]
 [1087 3236]]
Accuracy on test set:    0.724381216747629
Sensitivity:    0.7485542447374508 	 Specificity:    0.7002081887578071
Precision  : 0.7140335392762577
Area Under Curve:    0.724381216747629
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6062 - accuracy: 0.6661 - val_loss: 0.5609 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5572 - accuracy: 0.7112 - val_loss: 0.5511 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7222 - val_loss: 0.5531 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7301 - val_loss: 0.5489 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7356 - val_loss: 0.5445 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5194 - accuracy: 0.7403 - val_loss: 0.5443 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5122 - accuracy: 0.7433 - val_loss: 0.5437 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5061 - accuracy: 0.7488
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7486 - val_loss: 0.5418 - val_accuracy: 0.7188 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.46434379039769025
Confusion Matrix :
 [[3085 1238]
 [1079 3244]]
Accuracy on test set:    0.7320148045338885
Sensitivity:    0.7504048114735138 	 Specificity:    0.7136247975942632
Precision  : 0.7237840249888443
Area Under Curve:    0.7320148045338886
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6124 - accuracy: 0.6629 - val_loss: 0.5616 - val_accuracy: 0.7033 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5630 - accuracy: 0.7070 - val_loss: 0.5521 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7195 - val_loss: 0.5459 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7252 - val_loss: 0.5451 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7333 - val_loss: 0.5425 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7379 - val_loss: 0.5380 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5120 - accuracy: 0.7431 - val_loss: 0.5367 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7470 - val_loss: 0.5396 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7506 - val_loss: 0.5411 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7523 - val_loss: 0.5448 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4888 - accuracy: 0.7577 - val_loss: 0.5410 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 12/400
257/274 [===========================>..] - ETA: 0s - loss: 0.4826 - accuracy: 0.7613
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7614 - val_loss: 0.5455 - val_accuracy: 0.7176 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.4701601327563286
Confusion Matrix :
 [[2976 1347]
 [ 952 3371]]
Accuracy on test set:    0.7340966921119593
Sensitivity:    0.7797825584085126 	 Specificity:    0.6884108258154059
Precision  : 0.7144976685036032
Area Under Curve:    0.7340966921119594
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6099 - accuracy: 0.6676 - val_loss: 0.5655 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7109 - val_loss: 0.5503 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7229 - val_loss: 0.5482 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7277 - val_loss: 0.5478 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7351 - val_loss: 0.5413 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5191 - accuracy: 0.7400 - val_loss: 0.5526 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5144 - accuracy: 0.7427 - val_loss: 0.5519 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7458 - val_loss: 0.5448 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7500 - val_loss: 0.5419 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400

261/274 [===========================>..] - ETA: 0s - loss: 0.4913 - accuracy: 0.7569
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7563 - val_loss: 0.5447 - val_accuracy: 0.7191 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4590302030686875
Confusion Matrix :
 [[3359  964]
 [1384 2939]]
Accuracy on test set:    0.7284293314827666
Sensitivity:    0.6798519546611149 	 Specificity:    0.7770067083044182
Precision  : 0.7530105047399437
Area Under Curve:    0.7284293314827666
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6125 - accuracy: 0.6608 - val_loss: 0.5720 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5628 - accuracy: 0.7081 - val_loss: 0.5560 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7192 - val_loss: 0.5536 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7248 - val_loss: 0.5502 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7305 - val_loss: 0.5472 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7348 - val_loss: 0.5461 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7421 - val_loss: 0.5506 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7428 - val_loss: 0.5500 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7475 - val_loss: 0.5548 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4988 - accuracy: 0.7529 - val_loss: 0.5496 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4947 - accuracy: 0.7537
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7541 - val_loss: 0.5599 - val_accuracy: 0.7188 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.5052821917075885
Confusion Matrix :
 [[3086 1237]
 [ 908 3415]]
Accuracy on test set:    0.7519083969465649
Sensitivity:    0.7899606754568587 	 Specificity:    0.7138561184362711
Precision  : 0.7340928632846088
Area Under Curve:    0.7519083969465649
(8646, 4352) (8646,)
Mean MCC = 0.4506 + 0.0235 and Mean AUC = 0.7246 + 0.0117
Mean Sensitivity = 0.7442 + 0.0357 and Mean Specificity = 0.7051 + 0.0348 and Mean Accuracy = 0.7246 + 0.0117
Mean Precision = 0.7171 + 0.0179





Seed   : 597981
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6042 - accuracy: 0.6674 - val_loss: 0.5621 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5584 - accuracy: 0.7111 - val_loss: 0.5507 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7231 - val_loss: 0.5388 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5303 - accuracy: 0.7320 - val_loss: 0.5433 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7372 - val_loss: 0.5402 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7418 - val_loss: 0.5381 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7459 - val_loss: 0.5520 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7457 - val_loss: 0.5376 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7536 - val_loss: 0.5377 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7573 - val_loss: 0.5391 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7589 - val_loss: 0.5449 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4781 - accuracy: 0.7625 - val_loss: 0.5416 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4717 - accuracy: 0.7654 - val_loss: 0.5385 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4628 - accuracy: 0.7705 - val_loss: 0.5443 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4591 - accuracy: 0.7744 - val_loss: 0.5471 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4540 - accuracy: 0.7750 - val_loss: 0.5533 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4475 - accuracy: 0.7780 - val_loss: 0.5549 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 18/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4422 - accuracy: 0.7821
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4427 - accuracy: 0.7817 - val_loss: 0.5589 - val_accuracy: 0.7255 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4139057050949841
Confusion Matrix :
 [[2923 1400]
 [1137 3186]]
Accuracy on test set:    0.7065695119130234
Sensitivity:    0.7369882026370576 	 Specificity:    0.6761508211889892
Precision  : 0.6947230702136938
Area Under Curve:    0.7065695119130233
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6014 - accuracy: 0.6705 - val_loss: 0.5643 - val_accuracy: 0.7055 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5557 - accuracy: 0.7131 - val_loss: 0.5534 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7247 - val_loss: 0.5519 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7297 - val_loss: 0.5471 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7364 - val_loss: 0.5415 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7408 - val_loss: 0.5470 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5120 - accuracy: 0.7451 - val_loss: 0.5418 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7499 - val_loss: 0.5408 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7524 - val_loss: 0.5439 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7537 - val_loss: 0.5373 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7590 - val_loss: 0.5422 - val_accuracy: 0.7245 - lr: 0.0010

Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7618 - val_loss: 0.5480 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4746 - accuracy: 0.7654 - val_loss: 0.5451 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4726 - accuracy: 0.7660 - val_loss: 0.5626 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4633 - accuracy: 0.7724
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4639 - accuracy: 0.7719 - val_loss: 0.5452 - val_accuracy: 0.7206 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.42872184567303473
Confusion Matrix :
 [[2892 1431]
 [1046 3277]]
Accuracy on test set:    0.7135091371732593
Sensitivity:    0.7580383992597733 	 Specificity:    0.6689798750867453
Precision  : 0.6960492778249787
Area Under Curve:    0.7135091371732593
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6026 - accuracy: 0.6708 - val_loss: 0.5715 - val_accuracy: 0.7020 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5544 - accuracy: 0.7141 - val_loss: 0.5553 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7238 - val_loss: 0.5625 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5303 - accuracy: 0.7305 - val_loss: 0.5524 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5220 - accuracy: 0.7364 - val_loss: 0.5512 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7402 - val_loss: 0.5486 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7467 - val_loss: 0.5473 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7495 - val_loss: 0.5520 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7548 - val_loss: 0.5399 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7571 - val_loss: 0.5535 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4840 - accuracy: 0.7595 - val_loss: 0.5428 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4771 - accuracy: 0.7629 - val_loss: 0.5571 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4752 - accuracy: 0.7648 - val_loss: 0.5590 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4649 - accuracy: 0.7693
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4653 - accuracy: 0.7690 - val_loss: 0.5579 - val_accuracy: 0.7186 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.44256673531844337
Confusion Matrix :
 [[3275 1048]
 [1367 2956]]
Accuracy on test set:    0.7206800832755031
Sensitivity:    0.6837844089752487 	 Specificity:    0.7575757575757576
Precision  : 0.7382617382617382
Area Under Curve:    0.7206800832755031
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5992 - accuracy: 0.6713 - val_loss: 0.5677 - val_accuracy: 0.7008 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5533 - accuracy: 0.7165 - val_loss: 0.5608 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7251 - val_loss: 0.5492 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7326 - val_loss: 0.5571 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5220 - accuracy: 0.7387 - val_loss: 0.5451 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7421 - val_loss: 0.5440 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7480 - val_loss: 0.5419 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5017 - accuracy: 0.7520 - val_loss: 0.5474 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7546 - val_loss: 0.5547 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4906 - accuracy: 0.7592 - val_loss: 0.5549 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4842 - accuracy: 0.7625 - val_loss: 0.5515 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4780 - accuracy: 0.7669 - val_loss: 0.5546 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7709 - val_loss: 0.5515 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4630 - accuracy: 0.7734 - val_loss: 0.5694 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4611 - accuracy: 0.7757 - val_loss: 0.5600 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4552 - accuracy: 0.7798 - val_loss: 0.5644 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4495 - accuracy: 0.7812 - val_loss: 0.5593 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 18/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4439 - accuracy: 0.7840
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4444 - accuracy: 0.7837 - val_loss: 0.5720 - val_accuracy: 0.7169 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.42463148172979204
Confusion Matrix :
 [[2583 1740]
 [ 792 3531]]
Accuracy on test set:    0.707147814018043
Sensitivity:    0.816793893129771 	 Specificity:    0.5975017349063151
Precision  : 0.6698918611269209
Area Under Curve:    0.7071478140180432
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6017 - accuracy: 0.6690 - val_loss: 0.5640 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5559 - accuracy: 0.7134 - val_loss: 0.5518 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7259 - val_loss: 0.5509 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7315 - val_loss: 0.5454 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5212 - accuracy: 0.7377 - val_loss: 0.5460 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5128 - accuracy: 0.7415 - val_loss: 0.5436 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7447 - val_loss: 0.5401 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7495 - val_loss: 0.5477 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7534 - val_loss: 0.5449 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4879 - accuracy: 0.7586 - val_loss: 0.5503 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7614 - val_loss: 0.5543 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4759 - accuracy: 0.7653 - val_loss: 0.5612 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7703 - val_loss: 0.5602 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4605 - accuracy: 0.7757 - val_loss: 0.5577 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4597 - accuracy: 0.7757
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4592 - accuracy: 0.7758 - val_loss: 0.5716 - val_accuracy: 0.7210 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.44814687627007144
Confusion Matrix :
 [[2784 1539]
 [ 870 3453]]
Accuracy on test set:    0.7213740458015268
Sensitivity:    0.7987508674531575 	 Specificity:    0.6439972241498959
Precision  : 0.6917067307692307
Area Under Curve:    0.7213740458015268
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6103 - accuracy: 0.6664 - val_loss: 0.5677 - val_accuracy: 0.6989 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7133 - val_loss: 0.5554 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7208 - val_loss: 0.5492 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7293 - val_loss: 0.5485 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5223 - accuracy: 0.7377 - val_loss: 0.5440 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7417 - val_loss: 0.5472 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7420 - val_loss: 0.5404 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7499 - val_loss: 0.5441 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7528 - val_loss: 0.5407 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7567 - val_loss: 0.5456 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7587 - val_loss: 0.5466 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4793 - accuracy: 0.7641 - val_loss: 0.5441 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4744 - accuracy: 0.7670 - val_loss: 0.5485 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4696 - accuracy: 0.7689
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4701 - accuracy: 0.7685 - val_loss: 0.5536 - val_accuracy: 0.7137 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4392561247977511
Confusion Matrix :
 [[3229 1094]
 [1333 2990]]
Accuracy on test set:    0.7192921582234559
Sensitivity:    0.6916493176035161 	 Specificity:    0.7469349988433958
Precision  : 0.7321253672869735
Area Under Curve:    0.7192921582234559
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6050 - accuracy: 0.6649 - val_loss: 0.5748 - val_accuracy: 0.6990 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7108 - val_loss: 0.5616 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7204 - val_loss: 0.5600 - val_accuracy: 0.7041 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7286 - val_loss: 0.5539 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7324 - val_loss: 0.5561 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5220 - accuracy: 0.7358 - val_loss: 0.5517 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7416 - val_loss: 0.5484 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7446 - val_loss: 0.5538 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5050 - accuracy: 0.7481 - val_loss: 0.5564 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4987 - accuracy: 0.7536 - val_loss: 0.5540 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7569 - val_loss: 0.5521 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4880 - accuracy: 0.7593 - val_loss: 0.5506 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7632 - val_loss: 0.5547 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 14/400
256/274 [===========================>..] - ETA: 0s - loss: 0.4779 - accuracy: 0.7651
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7647 - val_loss: 0.5617 - val_accuracy: 0.7190 - lr: 0.0010
271/271 [==============================] - 0s 668us/step
Independent Testing Matthews Correlation:  0.4384194875213059
Confusion Matrix :
 [[2847 1476]
 [ 965 3358]]
Accuracy on test set:    0.7176729123294009
Sensitivity:    0.7767753874624104 	 Specificity:    0.6585704371963914
Precision  : 0.6946628051303269
Area Under Curve:    0.7176729123294009
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6197 - accuracy: 0.6518 - val_loss: 0.5893 - val_accuracy: 0.6829 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5655 - accuracy: 0.7084 - val_loss: 0.5625 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7204 - val_loss: 0.5564 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7281 - val_loss: 0.5547 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5301 - accuracy: 0.7321 - val_loss: 0.5558 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7358 - val_loss: 0.5501 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7402 - val_loss: 0.5573 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5091 - accuracy: 0.7433 - val_loss: 0.5547 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5047 - accuracy: 0.7480 - val_loss: 0.5527 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 10/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4987 - accuracy: 0.7533
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4983 - accuracy: 0.7530 - val_loss: 0.5538 - val_accuracy: 0.7131 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4660453560061786
Confusion Matrix :
 [[2874 1449]
 [ 877 3446]]
Accuracy on test set:    0.7309738607448532
Sensitivity:    0.7971316215591024 	 Specificity:    0.6648160999306038
Precision  : 0.7039836567926455
Area Under Curve:    0.730973860744853
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6082 - accuracy: 0.6664 - val_loss: 0.5719 - val_accuracy: 0.7003 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5622 - accuracy: 0.7076 - val_loss: 0.5586 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7215 - val_loss: 0.5625 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7298 - val_loss: 0.5503 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5279 - accuracy: 0.7337 - val_loss: 0.5602 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5197 - accuracy: 0.7386 - val_loss: 0.5491 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5122 - accuracy: 0.7429 - val_loss: 0.5580 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5062 - accuracy: 0.7468 - val_loss: 0.5485 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7506 - val_loss: 0.5511 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7534 - val_loss: 0.5513 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7579 - val_loss: 0.5533 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4832 - accuracy: 0.7620 - val_loss: 0.5537 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4762 - accuracy: 0.7646 - val_loss: 0.5524 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7686 - val_loss: 0.5596 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4651 - accuracy: 0.7714
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4644 - accuracy: 0.7719 - val_loss: 0.5599 - val_accuracy: 0.7186 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.47730501164968997
Confusion Matrix :
 [[3235 1088]
 [1172 3151]]
Accuracy on test set:    0.7386074485311126
Sensitivity:    0.7288919731667823 	 Specificity:    0.748322923895443
Precision  : 0.7433356923802784
Area Under Curve:    0.7386074485311126
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6110 - accuracy: 0.6639 - val_loss: 0.5750 - val_accuracy: 0.7005 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5642 - accuracy: 0.7087 - val_loss: 0.5608 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7203 - val_loss: 0.5572 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7275 - val_loss: 0.5521 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5297 - accuracy: 0.7322 - val_loss: 0.5535 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7369 - val_loss: 0.5549 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7429 - val_loss: 0.5492 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5102 - accuracy: 0.7438 - val_loss: 0.5509 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7503 - val_loss: 0.5525 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7528 - val_loss: 0.5622 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4881 - accuracy: 0.7581
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4889 - accuracy: 0.7572 - val_loss: 0.5573 - val_accuracy: 0.7158 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.4859362270608474
Confusion Matrix :
 [[3298 1025]
 [1199 3124]]
Accuracy on test set:    0.7427712236872542
Sensitivity:    0.72264631043257 	 Specificity:    0.7628961369419385
Precision  : 0.7529525186791998
Area Under Curve:    0.7427712236872543
(8646, 4352) (8646,)
Mean MCC = 0.4465 + 0.0221 and Mean AUC = 0.7219 + 0.0116
Mean Sensitivity = 0.7511 + 0.0436 and Mean Specificity = 0.6926 + 0.0542 and Mean Accuracy = 0.7219 + 0.0116
Mean Precision = 0.7118 + 0.0262





Seed   : 352509
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6025 - accuracy: 0.6700 - val_loss: 0.5667 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5568 - accuracy: 0.7128 - val_loss: 0.5507 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7217 - val_loss: 0.5436 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7286 - val_loss: 0.5411 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7343 - val_loss: 0.5388 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7397 - val_loss: 0.5376 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5136 - accuracy: 0.7408 - val_loss: 0.5363 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7450 - val_loss: 0.5390 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7492 - val_loss: 0.5372 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4963 - accuracy: 0.7520 - val_loss: 0.5416 - val_accuracy: 0.7232 - lr: 0.0010

Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4889 - accuracy: 0.7570 - val_loss: 0.5377 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7585 - val_loss: 0.5400 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7608 - val_loss: 0.5373 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4769 - accuracy: 0.7645 - val_loss: 0.5414 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7688 - val_loss: 0.5495 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4666 - accuracy: 0.7701 - val_loss: 0.5426 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4616 - accuracy: 0.7731 - val_loss: 0.5437 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4572 - accuracy: 0.7745 - val_loss: 0.5483 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4517 - accuracy: 0.7779 - val_loss: 0.5592 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4476 - accuracy: 0.7800 - val_loss: 0.5572 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 21/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4434 - accuracy: 0.7815
Epoch 21: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4439 - accuracy: 0.7811 - val_loss: 0.5577 - val_accuracy: 0.7256 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.4208278234289605
Confusion Matrix :
 [[2837 1486]
 [1028 3295]]
Accuracy on test set:    0.7092297015961138
Sensitivity:    0.7622021744159149 	 Specificity:    0.6562572287763128
Precision  : 0.6891863626856306
Area Under Curve:    0.7092297015961138
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6105 - accuracy: 0.6631 - val_loss: 0.5658 - val_accuracy: 0.7041 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5618 - accuracy: 0.7082 - val_loss: 0.5539 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7198 - val_loss: 0.5481 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5369 - accuracy: 0.7267 - val_loss: 0.5436 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5295 - accuracy: 0.7338 - val_loss: 0.5440 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5215 - accuracy: 0.7374 - val_loss: 0.5428 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5172 - accuracy: 0.7381 - val_loss: 0.5426 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5096 - accuracy: 0.7441 - val_loss: 0.5399 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7484 - val_loss: 0.5507 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7519 - val_loss: 0.5435 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7566 - val_loss: 0.5497 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4858 - accuracy: 0.7592 - val_loss: 0.5472 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4802 - accuracy: 0.7625 - val_loss: 0.5504 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4755 - accuracy: 0.7664 - val_loss: 0.5681 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7672 - val_loss: 0.5505 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4613 - accuracy: 0.7711 - val_loss: 0.5582 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 17/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4560 - accuracy: 0.7739
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4559 - accuracy: 0.7742 - val_loss: 0.5802 - val_accuracy: 0.7181 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4359188515579839
Confusion Matrix :
 [[2632 1691]
 [ 789 3534]]
Accuracy on test set:    0.7131621559102476
Sensitivity:    0.8174878556557946 	 Specificity:    0.6088364561647004
Precision  : 0.6763636363636364
Area Under Curve:    0.7131621559102475
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6041 - accuracy: 0.6684 - val_loss: 0.5607 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5545 - accuracy: 0.7136 - val_loss: 0.5532 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7241 - val_loss: 0.5418 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5303 - accuracy: 0.7311 - val_loss: 0.5418 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5205 - accuracy: 0.7370 - val_loss: 0.5369 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5141 - accuracy: 0.7430 - val_loss: 0.5418 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7449 - val_loss: 0.5403 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7512 - val_loss: 0.5505 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7547 - val_loss: 0.5441 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7576 - val_loss: 0.5405 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7614 - val_loss: 0.5451 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4739 - accuracy: 0.7666 - val_loss: 0.5460 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4662 - accuracy: 0.7713
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4665 - accuracy: 0.7710 - val_loss: 0.5469 - val_accuracy: 0.7223 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.43858629953625583
Confusion Matrix :
 [[3103 1220]
 [1207 3116]]
Accuracy on test set:    0.7192921582234559
Sensitivity:    0.720795743696507 	 Specificity:    0.7177885727504049
Precision  : 0.7186346863468634
Area Under Curve:    0.7192921582234558
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6004 - accuracy: 0.6734 - val_loss: 0.5620 - val_accuracy: 0.7048 - lr: 0.0010
Epoch 2/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5567 - accuracy: 0.7140 - val_loss: 0.5543 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7255 - val_loss: 0.5469 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5306 - accuracy: 0.7313 - val_loss: 0.5409 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7373 - val_loss: 0.5423 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7418 - val_loss: 0.5419 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5119 - accuracy: 0.7449 - val_loss: 0.5384 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7476 - val_loss: 0.5443 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7513 - val_loss: 0.5490 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7555 - val_loss: 0.5475 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4868 - accuracy: 0.7600 - val_loss: 0.5451 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7622 - val_loss: 0.5490 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4755 - accuracy: 0.7662 - val_loss: 0.5500 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7711 - val_loss: 0.5589 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4634 - accuracy: 0.7727
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4640 - accuracy: 0.7723 - val_loss: 0.5603 - val_accuracy: 0.7183 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.421502632382832
Confusion Matrix :
 [[2659 1664]
 [ 868 3455]]
Accuracy on test set:    0.707147814018043
Sensitivity:    0.7992135091371733 	 Specificity:    0.6150821188989128
Precision  : 0.674936511037312
Area Under Curve:    0.7071478140180432
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6043 - accuracy: 0.6697 - val_loss: 0.5547 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5599 - accuracy: 0.7110 - val_loss: 0.5438 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7231 - val_loss: 0.5429 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7282 - val_loss: 0.5449 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7344 - val_loss: 0.5353 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7401 - val_loss: 0.5396 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7433 - val_loss: 0.5328 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7484 - val_loss: 0.5362 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7542 - val_loss: 0.5357 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7536 - val_loss: 0.5422 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4869 - accuracy: 0.7598 - val_loss: 0.5425 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4799 - accuracy: 0.7620 - val_loss: 0.5531 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4742 - accuracy: 0.7663 - val_loss: 0.5447 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4687 - accuracy: 0.7690 - val_loss: 0.5515 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4632 - accuracy: 0.7708 - val_loss: 0.5495 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4569 - accuracy: 0.7758 - val_loss: 0.5550 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4520 - accuracy: 0.7777 - val_loss: 0.5572 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 18/400
252/274 [==========================>...] - ETA: 0s - loss: 0.4468 - accuracy: 0.7806
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4477 - accuracy: 0.7799 - val_loss: 0.5710 - val_accuracy: 0.7176 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.45085892666873717
Confusion Matrix :
 [[2680 1643]
 [ 771 3552]]
Accuracy on test set:    0.720795743696507
Sensitivity:    0.8216516308119362 	 Specificity:    0.619939856581078
Precision  : 0.6837343599615014
Area Under Curve:    0.7207957436965071
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6052 - accuracy: 0.6695 - val_loss: 0.5608 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7122 - val_loss: 0.5516 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7213 - val_loss: 0.5440 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7281 - val_loss: 0.5461 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7373 - val_loss: 0.5392 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7407 - val_loss: 0.5378 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7459 - val_loss: 0.5422 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7506 - val_loss: 0.5448 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4946 - accuracy: 0.7532 - val_loss: 0.5430 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7540 - val_loss: 0.5442 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4864 - accuracy: 0.7593 - val_loss: 0.5433 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4818 - accuracy: 0.7607 - val_loss: 0.5486 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4739 - accuracy: 0.7643 - val_loss: 0.5498 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7673 - val_loss: 0.5514 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4601 - accuracy: 0.7720 - val_loss: 0.5602 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 16/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4545 - accuracy: 0.7759
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4547 - accuracy: 0.7761 - val_loss: 0.5596 - val_accuracy: 0.7196 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.43376262487614603
Confusion Matrix :
 [[2921 1402]
 [1052 3271]]
Accuracy on test set:    0.7161693268563497
Sensitivity:    0.7566504742077261 	 Specificity:    0.6756881795049734
Precision  : 0.6999786004707896
Area Under Curve:    0.7161693268563497
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6014 - accuracy: 0.6708 - val_loss: 0.5574 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5584 - accuracy: 0.7103 - val_loss: 0.5449 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7241 - val_loss: 0.5466 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7307 - val_loss: 0.5431 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7341 - val_loss: 0.5387 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7400 - val_loss: 0.5399 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7449 - val_loss: 0.5386 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7499 - val_loss: 0.5382 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7541 - val_loss: 0.5404 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7579 - val_loss: 0.5475 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7605 - val_loss: 0.5450 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4745 - accuracy: 0.7671
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4752 - accuracy: 0.7664 - val_loss: 0.5492 - val_accuracy: 0.7205 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.44797092306816405
Confusion Matrix :
 [[3017 1306]
 [1083 3240]]
Accuracy on test set:    0.7236872542216054
Sensitivity:    0.7494795281054824 	 Specificity:    0.6978949803377285
Precision  : 0.7127144742630884
Area Under Curve:    0.7236872542216054
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6056 - accuracy: 0.6689 - val_loss: 0.5635 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5605 - accuracy: 0.7091 - val_loss: 0.5480 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7232 - val_loss: 0.5401 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7297 - val_loss: 0.5402 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7316 - val_loss: 0.5344 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7382 - val_loss: 0.5352 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5146 - accuracy: 0.7404 - val_loss: 0.5352 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7454 - val_loss: 0.5370 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5006 - accuracy: 0.7492 - val_loss: 0.5498 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7510 - val_loss: 0.5335 - val_accuracy: 0.7326 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7556 - val_loss: 0.5340 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7582 - val_loss: 0.5372 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4774 - accuracy: 0.7629 - val_loss: 0.5453 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4741 - accuracy: 0.7651 - val_loss: 0.5430 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 15/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4711 - accuracy: 0.7659
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4711 - accuracy: 0.7657 - val_loss: 0.5412 - val_accuracy: 0.7290 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.43452994130601286
Confusion Matrix :
 [[3149 1174]
 [1271 3052]]
Accuracy on test set:    0.7172102706453851
Sensitivity:    0.7059912098080037 	 Specificity:    0.7284293314827666
Precision  : 0.7221959299574066
Area Under Curve:    0.7172102706453851
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6049 - accuracy: 0.6695 - val_loss: 0.5600 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5604 - accuracy: 0.7088 - val_loss: 0.5601 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7208 - val_loss: 0.5482 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7279 - val_loss: 0.5380 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7354 - val_loss: 0.5384 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5218 - accuracy: 0.7360 - val_loss: 0.5465 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7436 - val_loss: 0.5370 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7474 - val_loss: 0.5367 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7503 - val_loss: 0.5406 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7551 - val_loss: 0.5435 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4865 - accuracy: 0.7584 - val_loss: 0.5375 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4764 - accuracy: 0.7626
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7620 - val_loss: 0.5408 - val_accuracy: 0.7259 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.4710519288002659
Confusion Matrix :
 [[3139 1184]
 [1103 3220]]
Accuracy on test set:    0.7354846171640065
Sensitivity:    0.744853111265325 	 Specificity:    0.7261161230626879
Precision  : 0.7311534968210718
Area Under Curve:    0.7354846171640065
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6087 - accuracy: 0.6640 - val_loss: 0.5610 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5653 - accuracy: 0.7074 - val_loss: 0.5498 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5500 - accuracy: 0.7178 - val_loss: 0.5411 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7263 - val_loss: 0.5390 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5317 - accuracy: 0.7310 - val_loss: 0.5419 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7362 - val_loss: 0.5448 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7415 - val_loss: 0.5396 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5119 - accuracy: 0.7449 - val_loss: 0.5431 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5068 - accuracy: 0.7479
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7481 - val_loss: 0.5437 - val_accuracy: 0.7221 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.5101830803245236
Confusion Matrix :
 [[3217 1106]
 [1012 3311]]
Accuracy on test set:    0.7550312283136711
Sensitivity:    0.7659033078880407 	 Specificity:    0.7441591487393014
Precision  : 0.7496038034865293
Area Under Curve:    0.7550312283136709
(8646, 4352) (8646,)
Mean MCC = 0.4465 + 0.0254 and Mean AUC = 0.7217 + 0.0134
Mean Sensitivity = 0.7644 + 0.0365 and Mean Specificity = 0.6790 + 0.0488 and Mean Accuracy = 0.7217 + 0.0134
Mean Precision = 0.7059 + 0.0238





Seed   : 421681
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6094 - accuracy: 0.6639 - val_loss: 0.5585 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5564 - accuracy: 0.7129 - val_loss: 0.5521 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7251 - val_loss: 0.5415 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7322 - val_loss: 0.5395 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7389 - val_loss: 0.5379 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7406 - val_loss: 0.5329 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7456 - val_loss: 0.5440 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7490 - val_loss: 0.5439 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4950 - accuracy: 0.7540 - val_loss: 0.5341 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7543 - val_loss: 0.5358 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4863 - accuracy: 0.7585
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7587 - val_loss: 0.5451 - val_accuracy: 0.7183 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.417869167771781
Confusion Matrix :
 [[3176 1147]
 [1372 2951]]
Accuracy on test set:    0.7086513994910941
Sensitivity:    0.6826278047652093 	 Specificity:    0.7346749942169789
Precision  : 0.7201073694485115
Area Under Curve:    0.7086513994910941
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6072 - accuracy: 0.6656 - val_loss: 0.5770 - val_accuracy: 0.6916 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5588 - accuracy: 0.7120 - val_loss: 0.5544 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7244 - val_loss: 0.5522 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5314 - accuracy: 0.7311 - val_loss: 0.5566 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7358 - val_loss: 0.5384 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5146 - accuracy: 0.7428 - val_loss: 0.5415 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7427 - val_loss: 0.5448 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7516 - val_loss: 0.5353 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7543 - val_loss: 0.5365 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4873 - accuracy: 0.7588 - val_loss: 0.5410 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4784 - accuracy: 0.7641
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4792 - accuracy: 0.7637 - val_loss: 0.5371 - val_accuracy: 0.7246 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4348546270220543
Confusion Matrix :
 [[3167 1156]
 [1288 3035]]
Accuracy on test set:    0.7173259310663891
Sensitivity:    0.70205875549387 	 Specificity:    0.7325931066389082
Precision  : 0.7241708422810785
Area Under Curve:    0.7173259310663891
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5984 - accuracy: 0.6735 - val_loss: 0.5692 - val_accuracy: 0.7005 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5560 - accuracy: 0.7147 - val_loss: 0.5523 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7258 - val_loss: 0.5451 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5310 - accuracy: 0.7289 - val_loss: 0.5458 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7344 - val_loss: 0.5411 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7411 - val_loss: 0.5376 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7445 - val_loss: 0.5390 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5008 - accuracy: 0.7513 - val_loss: 0.5360 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4961 - accuracy: 0.7515 - val_loss: 0.5396 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7579 - val_loss: 0.5500 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7604 - val_loss: 0.5524 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4759 - accuracy: 0.7649 - val_loss: 0.5453 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4696 - accuracy: 0.7686 - val_loss: 0.5563 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 14/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4614 - accuracy: 0.7749
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4622 - accuracy: 0.7746 - val_loss: 0.5514 - val_accuracy: 0.7221 - lr: 0.0010
271/271 [==============================] - 0s 666us/step
Independent Testing Matthews Correlation:  0.4510067175934368
Confusion Matrix :
 [[3078 1245]
 [1129 3194]]
Accuracy on test set:    0.7254221605366643
Sensitivity:    0.7388387693731205 	 Specificity:    0.7120055517002082
Precision  : 0.7195314259968462
Area Under Curve:    0.7254221605366644
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6077 - accuracy: 0.6656 - val_loss: 0.5684 - val_accuracy: 0.6975 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5629 - accuracy: 0.7091 - val_loss: 0.5552 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7226 - val_loss: 0.5479 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7307 - val_loss: 0.5464 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7351 - val_loss: 0.5489 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5187 - accuracy: 0.7386 - val_loss: 0.5410 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5127 - accuracy: 0.7435 - val_loss: 0.5422 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5057 - accuracy: 0.7461 - val_loss: 0.5418 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5014 - accuracy: 0.7490 - val_loss: 0.5441 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7539 - val_loss: 0.5380 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4847 - accuracy: 0.7605 - val_loss: 0.5464 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4802 - accuracy: 0.7622 - val_loss: 0.5452 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4739 - accuracy: 0.7657 - val_loss: 0.5464 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7692 - val_loss: 0.5559 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4621 - accuracy: 0.7714 - val_loss: 0.5537 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 16/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4566 - accuracy: 0.7745
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4568 - accuracy: 0.7742 - val_loss: 0.5656 - val_accuracy: 0.7178 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.436418260979646
Confusion Matrix :
 [[3014 1309]
 [1129 3194]]
Accuracy on test set:    0.7180198935924127
Sensitivity:    0.7388387693731205 	 Specificity:    0.6972010178117048
Precision  : 0.7093049078392183
Area Under Curve:    0.7180198935924127
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6099 - accuracy: 0.6673 - val_loss: 0.5583 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5572 - accuracy: 0.7124 - val_loss: 0.5450 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7225 - val_loss: 0.5378 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7284 - val_loss: 0.5385 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7353 - val_loss: 0.5367 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5180 - accuracy: 0.7398 - val_loss: 0.5357 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5127 - accuracy: 0.7424 - val_loss: 0.5381 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5055 - accuracy: 0.7472 - val_loss: 0.5441 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7516 - val_loss: 0.5339 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4910 - accuracy: 0.7562
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7563 - val_loss: 0.5372 - val_accuracy: 0.7218 - lr: 0.0010
271/271 [==============================] - 0s 669us/step
Independent Testing Matthews Correlation:  0.44891404278634045
Confusion Matrix :
 [[2850 1473]
 [ 925 3398]]
Accuracy on test set:    0.72264631043257
Sensitivity:    0.786028221142725 	 Specificity:    0.659264399722415
Precision  : 0.6975980291521248
Area Under Curve:    0.72264631043257
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6083 - accuracy: 0.6659 - val_loss: 0.5706 - val_accuracy: 0.6992 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5599 - accuracy: 0.7105 - val_loss: 0.5490 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7221 - val_loss: 0.5370 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7282 - val_loss: 0.5368 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7350 - val_loss: 0.5331 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7385 - val_loss: 0.5375 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7436 - val_loss: 0.5349 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5086 - accuracy: 0.7456 - val_loss: 0.5357 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5014 - accuracy: 0.7514 - val_loss: 0.5371 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4947 - accuracy: 0.7557 - val_loss: 0.5353 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4871 - accuracy: 0.7603
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7606 - val_loss: 0.5461 - val_accuracy: 0.7192 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.43890498664975625
Confusion Matrix :
 [[3309 1014]
 [1420 2903]]
Accuracy on test set:    0.7184825352764284
Sensitivity:    0.6715244043488319 	 Specificity:    0.765440666204025
Precision  : 0.7411284146030125
Area Under Curve:    0.7184825352764285
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6077 - accuracy: 0.6637 - val_loss: 0.5618 - val_accuracy: 0.7055 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7104 - val_loss: 0.5471 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7223 - val_loss: 0.5414 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7293 - val_loss: 0.5390 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5278 - accuracy: 0.7336 - val_loss: 0.5420 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5214 - accuracy: 0.7359 - val_loss: 0.5354 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7411 - val_loss: 0.5364 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7446 - val_loss: 0.5367 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5045 - accuracy: 0.7471 - val_loss: 0.5374 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7545 - val_loss: 0.5395 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7557 - val_loss: 0.5417 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4827 - accuracy: 0.7601 - val_loss: 0.5434 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4772 - accuracy: 0.7644 - val_loss: 0.5540 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7693 - val_loss: 0.5501 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4661 - accuracy: 0.7699 - val_loss: 0.5491 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4582 - accuracy: 0.7744 - val_loss: 0.5468 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4540 - accuracy: 0.7768 - val_loss: 0.5589 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4493 - accuracy: 0.7794 - val_loss: 0.5588 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4448 - accuracy: 0.7839 - val_loss: 0.5540 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4395 - accuracy: 0.7842 - val_loss: 0.5588 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4320 - accuracy: 0.7881 - val_loss: 0.5801 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 22/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4264 - accuracy: 0.7907
Epoch 22: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4264 - accuracy: 0.7909 - val_loss: 0.5682 - val_accuracy: 0.7228 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4407005873303459
Confusion Matrix :
 [[3087 1236]
 [1182 3141]]
Accuracy on test set:    0.7203331020124913
Sensitivity:    0.7265787647467037 	 Specificity:    0.714087439278279
Precision  : 0.7176148046607266
Area Under Curve:    0.7203331020124915
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6116 - accuracy: 0.6625 - val_loss: 0.5745 - val_accuracy: 0.6951 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7119 - val_loss: 0.5472 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7211 - val_loss: 0.5375 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7297 - val_loss: 0.5392 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5262 - accuracy: 0.7352 - val_loss: 0.5324 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7419 - val_loss: 0.5338 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7419 - val_loss: 0.5387 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7472 - val_loss: 0.5398 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4979 - accuracy: 0.7533 - val_loss: 0.5317 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7523 - val_loss: 0.5344 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7582 - val_loss: 0.5476 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4837 - accuracy: 0.7604 - val_loss: 0.5385 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4747 - accuracy: 0.7651 - val_loss: 0.5354 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4697 - accuracy: 0.7694 - val_loss: 0.5486 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 15/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4633 - accuracy: 0.7728
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4636 - accuracy: 0.7728 - val_loss: 0.5461 - val_accuracy: 0.7244 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4508551774357438
Confusion Matrix :
 [[3151 1172]
 [1202 3121]]
Accuracy on test set:    0.7254221605366643
Sensitivity:    0.7219523479065464 	 Specificity:    0.7288919731667823
Precision  : 0.7269974376892616
Area Under Curve:    0.7254221605366644
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6112 - accuracy: 0.6617 - val_loss: 0.5628 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5655 - accuracy: 0.7081 - val_loss: 0.5556 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5506 - accuracy: 0.7171 - val_loss: 0.5447 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7233 - val_loss: 0.5399 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7299 - val_loss: 0.5359 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5261 - accuracy: 0.7336 - val_loss: 0.5392 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5197 - accuracy: 0.7384 - val_loss: 0.5386 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7439 - val_loss: 0.5369 - val_accuracy: 0.7343 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5063 - accuracy: 0.7458 - val_loss: 0.5360 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7488 - val_loss: 0.5357 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7513 - val_loss: 0.5412 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7564 - val_loss: 0.5432 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4836 - accuracy: 0.7573
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7572 - val_loss: 0.5356 - val_accuracy: 0.7277 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.4695623508821593
Confusion Matrix :
 [[3111 1212]
 [1082 3241]]
Accuracy on test set:    0.7346749942169789
Sensitivity:    0.7497108489474902 	 Specificity:    0.7196391394864677
Precision  : 0.7278239389175837
Area Under Curve:    0.734674994216979
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6134 - accuracy: 0.6594 - val_loss: 0.5642 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5667 - accuracy: 0.7064 - val_loss: 0.5545 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5530 - accuracy: 0.7179 - val_loss: 0.5430 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7241 - val_loss: 0.5423 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7298 - val_loss: 0.5463 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7337 - val_loss: 0.5399 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5225 - accuracy: 0.7384 - val_loss: 0.5401 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7438 - val_loss: 0.5379 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5105 - accuracy: 0.7448 - val_loss: 0.5416 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5017 - accuracy: 0.7521
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7519 - val_loss: 0.5375 - val_accuracy: 0.7210 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.509152920784909
Confusion Matrix :
 [[3245 1078]
 [1044 3279]]
Accuracy on test set:    0.7545685866296553
Sensitivity:    0.758501040943789 	 Specificity:    0.7506361323155216
Precision  : 0.7525820518705532
Area Under Curve:    0.7545685866296553
(8646, 4352) (8646,)
Mean MCC = 0.4498 + 0.0235 and Mean AUC = 0.7246 + 0.0119
Mean Sensitivity = 0.7277 + 0.0331 and Mean Specificity = 0.7214 + 0.0278 and Mean Accuracy = 0.7246 + 0.0119
Mean Precision = 0.7237 + 0.0146





Seed   : 70112
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6252 - accuracy: 0.6512 - val_loss: 0.5757 - val_accuracy: 0.7003 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5636 - accuracy: 0.7099 - val_loss: 0.5624 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7209 - val_loss: 0.5537 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7272 - val_loss: 0.5469 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5287 - accuracy: 0.7327 - val_loss: 0.5430 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5201 - accuracy: 0.7382 - val_loss: 0.5402 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7391 - val_loss: 0.5473 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7446 - val_loss: 0.5416 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7461 - val_loss: 0.5433 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7537 - val_loss: 0.5423 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4931 - accuracy: 0.7544
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7542 - val_loss: 0.5413 - val_accuracy: 0.7159 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.4306652904100114
Confusion Matrix :
 [[3154 1169]
 [1293 3030]]
Accuracy on test set:    0.7152440434883183
Sensitivity:    0.7009021512838307 	 Specificity:    0.7295859356928059
Precision  : 0.7216003810431055
Area Under Curve:    0.7152440434883183
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6055 - accuracy: 0.6657 - val_loss: 0.5672 - val_accuracy: 0.7019 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7104 - val_loss: 0.5542 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7231 - val_loss: 0.5519 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7300 - val_loss: 0.5464 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7357 - val_loss: 0.5491 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7387 - val_loss: 0.5467 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5112 - accuracy: 0.7443 - val_loss: 0.5451 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7454 - val_loss: 0.5438 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7509 - val_loss: 0.5488 - val_accuracy: 0.7141 - lr: 0.0010

Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7553 - val_loss: 0.5489 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7599 - val_loss: 0.5470 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4789 - accuracy: 0.7629 - val_loss: 0.5574 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 13/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4725 - accuracy: 0.7686
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4736 - accuracy: 0.7673 - val_loss: 0.5533 - val_accuracy: 0.7158 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4198616697035517
Confusion Matrix :
 [[2942 1381]
 [1130 3193]]
Accuracy on test set:    0.7095766828591256
Sensitivity:    0.7386074485311126 	 Specificity:    0.6805459171871385
Precision  : 0.6980760822037604
Area Under Curve:    0.7095766828591257
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6100 - accuracy: 0.6636 - val_loss: 0.5663 - val_accuracy: 0.7016 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7128 - val_loss: 0.5555 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7228 - val_loss: 0.5493 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7270 - val_loss: 0.5467 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7342 - val_loss: 0.5420 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5178 - accuracy: 0.7390 - val_loss: 0.5504 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5119 - accuracy: 0.7440 - val_loss: 0.5445 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5047 - accuracy: 0.7462 - val_loss: 0.5582 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7499 - val_loss: 0.5480 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7536 - val_loss: 0.5518 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4851 - accuracy: 0.7595 - val_loss: 0.5468 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7619 - val_loss: 0.5446 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4743 - accuracy: 0.7624 - val_loss: 0.5474 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7704 - val_loss: 0.5570 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4593 - accuracy: 0.7747 - val_loss: 0.5577 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4547 - accuracy: 0.7752 - val_loss: 0.5579 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 17/400
256/274 [===========================>..] - ETA: 0s - loss: 0.4508 - accuracy: 0.7784
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4513 - accuracy: 0.7782 - val_loss: 0.5677 - val_accuracy: 0.7149 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4163140548754702
Confusion Matrix :
 [[2759 1564]
 [ 976 3347]]
Accuracy on test set:    0.7062225306500116
Sensitivity:    0.7742308582003239 	 Specificity:    0.6382142030996992
Precision  : 0.6815312563632662
Area Under Curve:    0.7062225306500116
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6247 - accuracy: 0.6519 - val_loss: 0.5759 - val_accuracy: 0.6937 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5687 - accuracy: 0.7016 - val_loss: 0.5599 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7174 - val_loss: 0.5485 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7254 - val_loss: 0.5466 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5307 - accuracy: 0.7318 - val_loss: 0.5457 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7376 - val_loss: 0.5427 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5192 - accuracy: 0.7391 - val_loss: 0.5373 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5110 - accuracy: 0.7432 - val_loss: 0.5463 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7471 - val_loss: 0.5402 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5009 - accuracy: 0.7503 - val_loss: 0.5453 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7545 - val_loss: 0.5441 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7542 - val_loss: 0.5423 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4837 - accuracy: 0.7605 - val_loss: 0.5453 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7622 - val_loss: 0.5418 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4764 - accuracy: 0.7640 - val_loss: 0.5441 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4723 - accuracy: 0.7667 - val_loss: 0.5465 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 17/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4659 - accuracy: 0.7705
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4659 - accuracy: 0.7706 - val_loss: 0.5487 - val_accuracy: 0.7268 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.43518309933610716
Confusion Matrix :
 [[2954 1369]
 [1077 3246]]
Accuracy on test set:    0.7170946102243813
Sensitivity:    0.7508674531575295 	 Specificity:    0.683321767291233
Precision  : 0.7033586132177682
Area Under Curve:    0.7170946102243813
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6094 - accuracy: 0.6660 - val_loss: 0.5595 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5598 - accuracy: 0.7126 - val_loss: 0.5556 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7207 - val_loss: 0.5461 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7285 - val_loss: 0.5399 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5274 - accuracy: 0.7324 - val_loss: 0.5456 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5206 - accuracy: 0.7383 - val_loss: 0.5338 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7428 - val_loss: 0.5443 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7431 - val_loss: 0.5382 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7475 - val_loss: 0.5365 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7526 - val_loss: 0.5552 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7562 - val_loss: 0.5414 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7576 - val_loss: 0.5403 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.7609 - val_loss: 0.5419 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7626 - val_loss: 0.5445 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4698 - accuracy: 0.7683 - val_loss: 0.5391 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4674 - accuracy: 0.7691 - val_loss: 0.5485 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4610 - accuracy: 0.7699 - val_loss: 0.5484 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4571 - accuracy: 0.7746 - val_loss: 0.5559 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4510 - accuracy: 0.7769 - val_loss: 0.5536 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 20/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4491 - accuracy: 0.7757
Epoch 20: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4493 - accuracy: 0.7760 - val_loss: 0.5593 - val_accuracy: 0.7181 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.4288689443508021
Confusion Matrix :
 [[3090 1233]
 [1236 3087]]
Accuracy on test set:    0.7144344205412908
Sensitivity:    0.714087439278279 	 Specificity:    0.7147814018043026
Precision  : 0.7145833333333333
Area Under Curve:    0.7144344205412909
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6049 - accuracy: 0.6681 - val_loss: 0.5575 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7103 - val_loss: 0.5457 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7223 - val_loss: 0.5396 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7286 - val_loss: 0.5336 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5239 - accuracy: 0.7348 - val_loss: 0.5324 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7374 - val_loss: 0.5336 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5119 - accuracy: 0.7440 - val_loss: 0.5310 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7452 - val_loss: 0.5316 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7507 - val_loss: 0.5345 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4942 - accuracy: 0.7549 - val_loss: 0.5329 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4878 - accuracy: 0.7563 - val_loss: 0.5356 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4825 - accuracy: 0.7609 - val_loss: 0.5352 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7637 - val_loss: 0.5429 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4705 - accuracy: 0.7685 - val_loss: 0.5351 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4641 - accuracy: 0.7716
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4638 - accuracy: 0.7716 - val_loss: 0.5446 - val_accuracy: 0.7249 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4525798676410773
Confusion Matrix :
 [[3299 1024]
 [1348 2975]]
Accuracy on test set:    0.7256534813786722
Sensitivity:    0.6881795049733981 	 Specificity:    0.7631274577839463
Precision  : 0.743935983995999
Area Under Curve:    0.7256534813786722
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6081 - accuracy: 0.6653 - val_loss: 0.5598 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5616 - accuracy: 0.7094 - val_loss: 0.5515 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7197 - val_loss: 0.5508 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7282 - val_loss: 0.5410 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7323 - val_loss: 0.5369 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7375 - val_loss: 0.5377 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7407 - val_loss: 0.5338 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7441 - val_loss: 0.5382 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5025 - accuracy: 0.7508 - val_loss: 0.5370 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7526 - val_loss: 0.5368 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4918 - accuracy: 0.7559 - val_loss: 0.5382 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4841 - accuracy: 0.7593
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4838 - accuracy: 0.7594 - val_loss: 0.5496 - val_accuracy: 0.7222 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4540283800550139
Confusion Matrix :
 [[2811 1512]
 [ 870 3453]]
Accuracy on test set:    0.7244968771686329
Sensitivity:    0.7987508674531575 	 Specificity:    0.6502428868841083
Precision  : 0.6954682779456194
Area Under Curve:    0.7244968771686329
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6078 - accuracy: 0.6664 - val_loss: 0.5590 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7119 - val_loss: 0.5461 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7233 - val_loss: 0.5452 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7265 - val_loss: 0.5393 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5256 - accuracy: 0.7351 - val_loss: 0.5361 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7378 - val_loss: 0.5334 - val_accuracy: 0.7327 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5136 - accuracy: 0.7416 - val_loss: 0.5481 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7470 - val_loss: 0.5364 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7504 - val_loss: 0.5324 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4969 - accuracy: 0.7525 - val_loss: 0.5392 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 11/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4918 - accuracy: 0.7543
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7543 - val_loss: 0.5374 - val_accuracy: 0.7271 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4584543242858709
Confusion Matrix :
 [[3015 1308]
 [1037 3286]]
Accuracy on test set:    0.7287763127457784
Sensitivity:    0.760120286837844 	 Specificity:    0.6974323386537127
Precision  : 0.7152808010448412
Area Under Curve:    0.7287763127457784
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6104 - accuracy: 0.6618 - val_loss: 0.5631 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5628 - accuracy: 0.7098 - val_loss: 0.5475 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7208 - val_loss: 0.5422 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7246 - val_loss: 0.5388 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7298 - val_loss: 0.5397 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7349 - val_loss: 0.5382 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7394 - val_loss: 0.5393 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7427 - val_loss: 0.5386 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7483 - val_loss: 0.5374 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7527 - val_loss: 0.5389 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7537 - val_loss: 0.5439 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4881 - accuracy: 0.7573
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4883 - accuracy: 0.7573 - val_loss: 0.5442 - val_accuracy: 0.7233 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4697805206231006
Confusion Matrix :
 [[3363  960]
 [1340 2983]]
Accuracy on test set:    0.7339810316909554
Sensitivity:    0.6900300717094611 	 Specificity:    0.7779319916724496
Precision  : 0.7565305604869389
Area Under Curve:    0.7339810316909554
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6129 - accuracy: 0.6629 - val_loss: 0.5671 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5680 - accuracy: 0.7058 - val_loss: 0.5513 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5507 - accuracy: 0.7178 - val_loss: 0.5448 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7227 - val_loss: 0.5489 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7271 - val_loss: 0.5400 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7334 - val_loss: 0.5383 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5231 - accuracy: 0.7362 - val_loss: 0.5431 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5191 - accuracy: 0.7396 - val_loss: 0.5485 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5153 - accuracy: 0.7423 - val_loss: 0.5381 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7453 - val_loss: 0.5398 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 11/400
258/274 [===========================>..] - ETA: 0s - loss: 0.5031 - accuracy: 0.7467
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5042 - accuracy: 0.7460 - val_loss: 0.5438 - val_accuracy: 0.7276 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.5056882380863728
Confusion Matrix :
 [[3159 1164]
 [ 975 3348]]
Accuracy on test set:    0.7526023594725885
Sensitivity:    0.7744621790423317 	 Specificity:    0.7307425399028452
Precision  : 0.7420212765957447
Area Under Curve:    0.7526023594725886
(8646, 4352) (8646,)
Mean MCC = 0.4471 + 0.0257 and Mean AUC = 0.7228 + 0.0129
Mean Sensitivity = 0.7390 + 0.0370 and Mean Specificity = 0.7066 + 0.0432 and Mean Accuracy = 0.7228 + 0.0129
Mean Precision = 0.7172 + 0.0228





Seed   : 20701
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6048 - accuracy: 0.6707 - val_loss: 0.5685 - val_accuracy: 0.6971 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5571 - accuracy: 0.7138 - val_loss: 0.5588 - val_accuracy: 0.7052 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7262 - val_loss: 0.5623 - val_accuracy: 0.7059 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7293 - val_loss: 0.5463 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7373 - val_loss: 0.5426 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7409 - val_loss: 0.5396 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7458 - val_loss: 0.5549 - val_accuracy: 0.7073 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7488 - val_loss: 0.5454 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7507 - val_loss: 0.5420 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4924 - accuracy: 0.7563 - val_loss: 0.5522 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7586 - val_loss: 0.5499 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4801 - accuracy: 0.7639 - val_loss: 0.5429 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4757 - accuracy: 0.7662 - val_loss: 0.5506 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 14/400
257/274 [===========================>..] - ETA: 0s - loss: 0.4696 - accuracy: 0.7716
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7718 - val_loss: 0.5560 - val_accuracy: 0.7224 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.42516780998747267
Confusion Matrix :
 [[3079 1244]
 [1241 3082]]
Accuracy on test set:    0.7125838538052278
Sensitivity:    0.7129308350682396 	 Specificity:    0.712236872542216
Precision  : 0.7124364308830329
Area Under Curve:    0.7125838538052278
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6038 - accuracy: 0.6695 - val_loss: 0.5686 - val_accuracy: 0.6990 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5587 - accuracy: 0.7083 - val_loss: 0.5564 - val_accuracy: 0.7092 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7204 - val_loss: 0.5547 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7262 - val_loss: 0.5582 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7335 - val_loss: 0.5454 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5210 - accuracy: 0.7365 - val_loss: 0.5477 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7391 - val_loss: 0.5469 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5130 - accuracy: 0.7411 - val_loss: 0.5488 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7461 - val_loss: 0.5502 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5021 - accuracy: 0.7486 - val_loss: 0.5470 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7522 - val_loss: 0.5446 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4891 - accuracy: 0.7555 - val_loss: 0.5564 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7600 - val_loss: 0.5492 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7634 - val_loss: 0.5529 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4753 - accuracy: 0.7632 - val_loss: 0.5514 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4674 - accuracy: 0.7677
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4677 - accuracy: 0.7678 - val_loss: 0.5651 - val_accuracy: 0.7120 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.43535387576419576
Confusion Matrix :
 [[3258 1065]
 [1381 2942]]
Accuracy on test set:    0.7170946102243813
Sensitivity:    0.6805459171871385 	 Specificity:    0.7536433032616239
Precision  : 0.7342151235338158
Area Under Curve:    0.7170946102243813
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6035 - accuracy: 0.6687 - val_loss: 0.5659 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5559 - accuracy: 0.7153 - val_loss: 0.5516 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7246 - val_loss: 0.5499 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5319 - accuracy: 0.7323 - val_loss: 0.5554 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7344 - val_loss: 0.5468 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7412 - val_loss: 0.5408 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5116 - accuracy: 0.7432 - val_loss: 0.5528 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7454 - val_loss: 0.5463 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7506 - val_loss: 0.5455 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7542 - val_loss: 0.5443 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4899 - accuracy: 0.7576 - val_loss: 0.5511 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4824 - accuracy: 0.7610
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7605 - val_loss: 0.5507 - val_accuracy: 0.7168 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.43951817232756174
Confusion Matrix :
 [[3098 1225]
 [1198 3125]]
Accuracy on test set:    0.7197547999074717
Sensitivity:    0.7228776312745778 	 Specificity:    0.7166319685403655
Precision  : 0.7183908045977011
Area Under Curve:    0.7197547999074717
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6037 - accuracy: 0.6711 - val_loss: 0.5665 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7106 - val_loss: 0.5504 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7220 - val_loss: 0.5438 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7293 - val_loss: 0.5419 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7319 - val_loss: 0.5433 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7365 - val_loss: 0.5474 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7390 - val_loss: 0.5444 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5112 - accuracy: 0.7445 - val_loss: 0.5424 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7460 - val_loss: 0.5494 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5015 - accuracy: 0.7503 - val_loss: 0.5401 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4936 - accuracy: 0.7537 - val_loss: 0.5542 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7550 - val_loss: 0.5415 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4832 - accuracy: 0.7617 - val_loss: 0.5448 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4774 - accuracy: 0.7644 - val_loss: 0.5539 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 15/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4726 - accuracy: 0.7667
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4720 - accuracy: 0.7673 - val_loss: 0.5545 - val_accuracy: 0.7178 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.44808765287657487
Confusion Matrix :
 [[3110 1213]
 [1173 3150]]
Accuracy on test set:    0.7240342354846172
Sensitivity:    0.7286606523247745 	 Specificity:    0.7194078186444599
Precision  : 0.7219802887921155
Area Under Curve:    0.7240342354846172
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6077 - accuracy: 0.6672 - val_loss: 0.5690 - val_accuracy: 0.6948 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5593 - accuracy: 0.7120 - val_loss: 0.5499 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7224 - val_loss: 0.5568 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7274 - val_loss: 0.5382 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7350 - val_loss: 0.5408 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7399 - val_loss: 0.5372 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7416 - val_loss: 0.5375 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7452 - val_loss: 0.5378 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7492 - val_loss: 0.5593 - val_accuracy: 0.7021 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7521 - val_loss: 0.5384 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4917 - accuracy: 0.7542 - val_loss: 0.5399 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7572 - val_loss: 0.5417 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7600 - val_loss: 0.5473 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7639 - val_loss: 0.5440 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4711 - accuracy: 0.7674 - val_loss: 0.5542 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4658 - accuracy: 0.7708 - val_loss: 0.5524 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4611 - accuracy: 0.7718 - val_loss: 0.5538 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4542 - accuracy: 0.7744 - val_loss: 0.5617 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 19/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4504 - accuracy: 0.7783
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4513 - accuracy: 0.7780 - val_loss: 0.5585 - val_accuracy: 0.7262 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.444664429665323
Confusion Matrix :
 [[3043 1280]
 [1122 3201]]
Accuracy on test set:    0.7221836687485542
Sensitivity:    0.7404580152671756 	 Specificity:    0.703909322229933
Precision  : 0.7143494755634903
Area Under Curve:    0.7221836687485541
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6017 - accuracy: 0.6717 - val_loss: 0.5641 - val_accuracy: 0.7041 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5577 - accuracy: 0.7125 - val_loss: 0.5526 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7225 - val_loss: 0.5425 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7290 - val_loss: 0.5417 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5253 - accuracy: 0.7348 - val_loss: 0.5441 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5205 - accuracy: 0.7383 - val_loss: 0.5361 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7435 - val_loss: 0.5362 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5089 - accuracy: 0.7446 - val_loss: 0.5359 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7530 - val_loss: 0.5360 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4933 - accuracy: 0.7558 - val_loss: 0.5367 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7575 - val_loss: 0.5377 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4830 - accuracy: 0.7623 - val_loss: 0.5470 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4774 - accuracy: 0.7653 - val_loss: 0.5495 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4707 - accuracy: 0.7695 - val_loss: 0.5500 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 15/400
256/274 [===========================>..] - ETA: 0s - loss: 0.4653 - accuracy: 0.7736
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4655 - accuracy: 0.7735 - val_loss: 0.5469 - val_accuracy: 0.7214 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.4304154949527828
Confusion Matrix :
 [[2999 1324]
 [1140 3183]]
Accuracy on test set:    0.7150127226463104
Sensitivity:    0.7362942401110341 	 Specificity:    0.6937312051815868
Precision  : 0.7062347459507433
Area Under Curve:    0.7150127226463106
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5981 - accuracy: 0.6759 - val_loss: 0.5685 - val_accuracy: 0.6983 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7130 - val_loss: 0.5507 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7266 - val_loss: 0.5433 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7299 - val_loss: 0.5438 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7368 - val_loss: 0.5412 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7438 - val_loss: 0.5380 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5073 - accuracy: 0.7480 - val_loss: 0.5394 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7517 - val_loss: 0.5373 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7539 - val_loss: 0.5394 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7587 - val_loss: 0.5403 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4804 - accuracy: 0.7634 - val_loss: 0.5459 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4725 - accuracy: 0.7680
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4733 - accuracy: 0.7673 - val_loss: 0.5466 - val_accuracy: 0.7215 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4493933939919502
Confusion Matrix :
 [[3246 1077]
 [1306 3017]]
Accuracy on test set:    0.724381216747629
Sensitivity:    0.6978949803377285 	 Specificity:    0.7508674531575295
Precision  : 0.7369320957498778
Area Under Curve:    0.724381216747629
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6012 - accuracy: 0.6710 - val_loss: 0.5606 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7099 - val_loss: 0.5515 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7223 - val_loss: 0.5465 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7308 - val_loss: 0.5365 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7334 - val_loss: 0.5430 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5196 - accuracy: 0.7384 - val_loss: 0.5360 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5104 - accuracy: 0.7445 - val_loss: 0.5365 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5061 - accuracy: 0.7480 - val_loss: 0.5443 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7510 - val_loss: 0.5423 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4925 - accuracy: 0.7551 - val_loss: 0.5385 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7584 - val_loss: 0.5369 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4802 - accuracy: 0.7635 - val_loss: 0.5388 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4750 - accuracy: 0.7671 - val_loss: 0.5402 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7707 - val_loss: 0.5401 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4607 - accuracy: 0.7736 - val_loss: 0.5458 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4554 - accuracy: 0.7769
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4558 - accuracy: 0.7771 - val_loss: 0.5535 - val_accuracy: 0.7298 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.46386625357749633
Confusion Matrix :
 [[3201 1122]
 [1196 3127]]
Accuracy on test set:    0.7318991441128846
Sensitivity:    0.7233402729585936 	 Specificity:    0.7404580152671756
Precision  : 0.7359378677335844
Area Under Curve:    0.7318991441128846
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6078 - accuracy: 0.6677 - val_loss: 0.5643 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5593 - accuracy: 0.7108 - val_loss: 0.5525 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7225 - val_loss: 0.5442 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7286 - val_loss: 0.5414 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7358 - val_loss: 0.5372 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5192 - accuracy: 0.7367 - val_loss: 0.5429 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7443 - val_loss: 0.5460 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5042 - accuracy: 0.7478 - val_loss: 0.5383 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7526 - val_loss: 0.5364 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4912 - accuracy: 0.7555 - val_loss: 0.5415 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4843 - accuracy: 0.7600
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4856 - accuracy: 0.7595 - val_loss: 0.5423 - val_accuracy: 0.7192 - lr: 0.0010
271/271 [==============================] - 0s 639us/step
Independent Testing Matthews Correlation:  0.46529191903996275
Confusion Matrix :
 [[3361  962]
 [1358 2965]]
Accuracy on test set:    0.7316678232708768
Sensitivity:    0.6858662965533194 	 Specificity:    0.777469349988434
Precision  : 0.7550292844410491
Area Under Curve:    0.7316678232708768
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6079 - accuracy: 0.6652 - val_loss: 0.5713 - val_accuracy: 0.7026 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7094 - val_loss: 0.5523 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7205 - val_loss: 0.5496 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 4/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7264 - val_loss: 0.5457 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5306 - accuracy: 0.7323 - val_loss: 0.5430 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7372 - val_loss: 0.5452 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5181 - accuracy: 0.7398 - val_loss: 0.5436 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7457 - val_loss: 0.5423 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5052 - accuracy: 0.7488 - val_loss: 0.5425 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7520 - val_loss: 0.5467 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7565 - val_loss: 0.5425 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4859 - accuracy: 0.7595 - val_loss: 0.5444 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4806 - accuracy: 0.7642 - val_loss: 0.5455 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4781 - accuracy: 0.7626 - val_loss: 0.5527 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4698 - accuracy: 0.7685 - val_loss: 0.5520 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 16/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4648 - accuracy: 0.7701
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4658 - accuracy: 0.7702 - val_loss: 0.5538 - val_accuracy: 0.7246 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.48621919267603864
Confusion Matrix :
 [[3304 1019]
 [1204 3119]]
Accuracy on test set:    0.7428868841082582
Sensitivity:    0.7214897062225306 	 Specificity:    0.7642840619939857
Precision  : 0.7537457709038182
Area Under Curve:    0.7428868841082582
(8646, 4352) (8646,)
Mean MCC = 0.4488 + 0.0176 and Mean AUC = 0.7241 + 0.0087
Mean Sensitivity = 0.7150 + 0.0195 and Mean Specificity = 0.7333 + 0.0265 and Mean Accuracy = 0.7241 + 0.0087
Mean Precision = 0.7289 + 0.0161





Seed   : 835948
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6019 - accuracy: 0.6739 - val_loss: 0.5682 - val_accuracy: 0.6981 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5546 - accuracy: 0.7133 - val_loss: 0.5474 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7259 - val_loss: 0.5420 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7322 - val_loss: 0.5420 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5225 - accuracy: 0.7369 - val_loss: 0.5357 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5148 - accuracy: 0.7417 - val_loss: 0.5397 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5052 - accuracy: 0.7469 - val_loss: 0.5336 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7502 - val_loss: 0.5348 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4938 - accuracy: 0.7538 - val_loss: 0.5442 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7561 - val_loss: 0.5399 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7596 - val_loss: 0.5438 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4759 - accuracy: 0.7668
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4769 - accuracy: 0.7666 - val_loss: 0.5410 - val_accuracy: 0.7237 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.42125889963050867
Confusion Matrix :
 [[2925 1398]
 [1108 3215]]
Accuracy on test set:    0.7101549849641453
Sensitivity:    0.7436965070552857 	 Specificity:    0.6766134628730048
Precision  : 0.6969434207673965
Area Under Curve:    0.7101549849641452
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6031 - accuracy: 0.6697 - val_loss: 0.5573 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5560 - accuracy: 0.7143 - val_loss: 0.5506 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7226 - val_loss: 0.5472 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7306 - val_loss: 0.5474 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7349 - val_loss: 0.5437 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5177 - accuracy: 0.7389 - val_loss: 0.5405 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7457 - val_loss: 0.5383 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7470 - val_loss: 0.5462 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7506 - val_loss: 0.5408 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4908 - accuracy: 0.7564 - val_loss: 0.5401 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7593 - val_loss: 0.5413 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7627 - val_loss: 0.5443 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7659 - val_loss: 0.5479 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 14/400
264/274 [===========================>..] - ETA: 0s - loss: 0.4704 - accuracy: 0.7664
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4698 - accuracy: 0.7672 - val_loss: 0.5608 - val_accuracy: 0.7231 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.4386539811076977
Confusion Matrix :
 [[2962 1361]
 [1070 3253]]
Accuracy on test set:    0.7188295165394402
Sensitivity:    0.7524866990515845 	 Specificity:    0.6851723340272958
Precision  : 0.7050281751192025
Area Under Curve:    0.7188295165394402
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6161 - accuracy: 0.6612 - val_loss: 0.5698 - val_accuracy: 0.7021 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5588 - accuracy: 0.7118 - val_loss: 0.5568 - val_accuracy: 0.7125 - lr: 0.0010

Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7219 - val_loss: 0.5463 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7311 - val_loss: 0.5537 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5247 - accuracy: 0.7347 - val_loss: 0.5449 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7410 - val_loss: 0.5411 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5149 - accuracy: 0.7411 - val_loss: 0.5441 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7462 - val_loss: 0.5401 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5003 - accuracy: 0.7523 - val_loss: 0.5416 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7551 - val_loss: 0.5409 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7587 - val_loss: 0.5421 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4820 - accuracy: 0.7628 - val_loss: 0.5458 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4758 - accuracy: 0.7647 - val_loss: 0.5470 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4714 - accuracy: 0.7710 - val_loss: 0.5483 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4678 - accuracy: 0.7706 - val_loss: 0.5497 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4597 - accuracy: 0.7747
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4604 - accuracy: 0.7744 - val_loss: 0.5541 - val_accuracy: 0.7177 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.42758611847467837
Confusion Matrix :
 [[3288 1035]
 [1448 2875]]
Accuracy on test set:    0.7128151746472358
Sensitivity:    0.6650474207726116 	 Specificity:    0.7605829285218598
Precision  : 0.7352941176470589
Area Under Curve:    0.7128151746472356
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6122 - accuracy: 0.6634 - val_loss: 0.5626 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7143 - val_loss: 0.5514 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7237 - val_loss: 0.5463 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7306 - val_loss: 0.5449 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7369 - val_loss: 0.5387 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5150 - accuracy: 0.7411 - val_loss: 0.5374 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5106 - accuracy: 0.7465 - val_loss: 0.5400 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7483 - val_loss: 0.5371 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7517 - val_loss: 0.5386 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7549 - val_loss: 0.5407 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4850 - accuracy: 0.7582 - val_loss: 0.5408 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7629 - val_loss: 0.5434 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4754 - accuracy: 0.7649 - val_loss: 0.5496 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4699 - accuracy: 0.7661 - val_loss: 0.5536 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4630 - accuracy: 0.7717
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4629 - accuracy: 0.7721 - val_loss: 0.5562 - val_accuracy: 0.7233 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4332468186909751
Confusion Matrix :
 [[2999 1324]
 [1128 3195]]
Accuracy on test set:    0.7164006476983577
Sensitivity:    0.7390700902151284 	 Specificity:    0.6937312051815868
Precision  : 0.707014826289002
Area Under Curve:    0.7164006476983577
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6098 - accuracy: 0.6646 - val_loss: 0.5676 - val_accuracy: 0.7041 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5632 - accuracy: 0.7086 - val_loss: 0.5517 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7201 - val_loss: 0.5484 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7275 - val_loss: 0.5394 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5280 - accuracy: 0.7335 - val_loss: 0.5342 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5219 - accuracy: 0.7367 - val_loss: 0.5381 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7418 - val_loss: 0.5334 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7456 - val_loss: 0.5364 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5042 - accuracy: 0.7476 - val_loss: 0.5349 - val_accuracy: 0.7345 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4985 - accuracy: 0.7504 - val_loss: 0.5335 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7553 - val_loss: 0.5323 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4910 - accuracy: 0.7548 - val_loss: 0.5339 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7592 - val_loss: 0.5382 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 14/400
256/274 [===========================>..] - ETA: 0s - loss: 0.4764 - accuracy: 0.7632
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4752 - accuracy: 0.7640 - val_loss: 0.5435 - val_accuracy: 0.7277 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4439575743616161
Confusion Matrix :
 [[2944 1379]
 [1031 3292]]
Accuracy on test set:    0.7212583853805228
Sensitivity:    0.7615082118898913 	 Specificity:    0.6810085588711543
Precision  : 0.7047741383001499
Area Under Curve:    0.7212583853805228
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6081 - accuracy: 0.6675 - val_loss: 0.5584 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5578 - accuracy: 0.7140 - val_loss: 0.5471 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7225 - val_loss: 0.5438 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7293 - val_loss: 0.5488 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7371 - val_loss: 0.5371 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5197 - accuracy: 0.7395 - val_loss: 0.5361 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7419 - val_loss: 0.5358 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5054 - accuracy: 0.7499 - val_loss: 0.5425 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7510 - val_loss: 0.5378 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4951 - accuracy: 0.7530
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7532 - val_loss: 0.5377 - val_accuracy: 0.7217 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.45140049727437026
Confusion Matrix :
 [[3181 1142]
 [1230 3093]]
Accuracy on test set:    0.7256534813786722
Sensitivity:    0.7154753643303262 	 Specificity:    0.7358315984270183
Precision  : 0.7303423848878394
Area Under Curve:    0.7256534813786722
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6046 - accuracy: 0.6695 - val_loss: 0.5580 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7091 - val_loss: 0.5518 - val_accuracy: 0.7077 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7210 - val_loss: 0.5436 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7283 - val_loss: 0.5410 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5269 - accuracy: 0.7343 - val_loss: 0.5362 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5191 - accuracy: 0.7372 - val_loss: 0.5365 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7429 - val_loss: 0.5374 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7478 - val_loss: 0.5398 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5002 - accuracy: 0.7494 - val_loss: 0.5339 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4922 - accuracy: 0.7547 - val_loss: 0.5392 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4876 - accuracy: 0.7563
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7556 - val_loss: 0.5431 - val_accuracy: 0.7200 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.44409383309698136
Confusion Matrix :
 [[2936 1387]
 [1023 3300]]
Accuracy on test set:    0.7212583853805228
Sensitivity:    0.7633587786259542 	 Specificity:    0.6791579921350914
Precision  : 0.7040751013441434
Area Under Curve:    0.7212583853805229
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6044 - accuracy: 0.6685 - val_loss: 0.5643 - val_accuracy: 0.7029 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7107 - val_loss: 0.5513 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7226 - val_loss: 0.5510 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7292 - val_loss: 0.5470 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7338 - val_loss: 0.5466 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5189 - accuracy: 0.7393 - val_loss: 0.5452 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7426 - val_loss: 0.5432 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7467 - val_loss: 0.5462 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5002 - accuracy: 0.7515 - val_loss: 0.5442 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7540 - val_loss: 0.5418 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7586 - val_loss: 0.5409 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7607 - val_loss: 0.5522 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4775 - accuracy: 0.7649 - val_loss: 0.5484 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4707 - accuracy: 0.7698 - val_loss: 0.5511 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7713 - val_loss: 0.5613 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4611 - accuracy: 0.7746
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4623 - accuracy: 0.7735 - val_loss: 0.5576 - val_accuracy: 0.7137 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.45801764022369706
Confusion Matrix :
 [[3012 1311]
 [1036 3287]]
Accuracy on test set:    0.7285449919037705
Sensitivity:    0.760351607679852 	 Specificity:    0.6967383761276891
Precision  : 0.7148760330578512
Area Under Curve:    0.7285449919037705
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6262 - accuracy: 0.6488 - val_loss: 0.5762 - val_accuracy: 0.6951 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5683 - accuracy: 0.7049 - val_loss: 0.5572 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5506 - accuracy: 0.7198 - val_loss: 0.5477 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7257 - val_loss: 0.5467 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7304 - val_loss: 0.5441 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5249 - accuracy: 0.7357 - val_loss: 0.5436 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7397 - val_loss: 0.5457 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7441 - val_loss: 0.5425 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7469 - val_loss: 0.5431 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7536 - val_loss: 0.5408 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4940 - accuracy: 0.7551 - val_loss: 0.5471 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7593 - val_loss: 0.5414 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4847 - accuracy: 0.7629 - val_loss: 0.5454 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4759 - accuracy: 0.7677 - val_loss: 0.5513 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4716 - accuracy: 0.7705
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4715 - accuracy: 0.7704 - val_loss: 0.5613 - val_accuracy: 0.7192 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.49458981457380946
Confusion Matrix :
 [[2917 1406]
 [ 800 3523]]
Accuracy on test set:    0.744853111265325
Sensitivity:    0.814943326393708 	 Specificity:    0.674762896136942
Precision  : 0.7147494420775005
Area Under Curve:    0.7448531112653249
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6028 - accuracy: 0.6714 - val_loss: 0.5658 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7115 - val_loss: 0.5593 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7235 - val_loss: 0.5573 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7286 - val_loss: 0.5489 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5263 - accuracy: 0.7347 - val_loss: 0.5459 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5200 - accuracy: 0.7391 - val_loss: 0.5490 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7436 - val_loss: 0.5475 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7454 - val_loss: 0.5503 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5003 - accuracy: 0.7536 - val_loss: 0.5451 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4944 - accuracy: 0.7570
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7558 - val_loss: 0.5497 - val_accuracy: 0.7190 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.49727377068382306
Confusion Matrix :
 [[3076 1247]
 [ 932 3391]]
Accuracy on test set:    0.7479759426324312
Sensitivity:    0.7844089752486699 	 Specificity:    0.7115429100161924
Precision  : 0.7311341095299698
Area Under Curve:    0.7479759426324312
(8646, 4352) (8646,)
Mean MCC = 0.4510 + 0.0247 and Mean AUC = 0.7248 + 0.0120
Mean Sensitivity = 0.7500 + 0.0379 and Mean Specificity = 0.6995 + 0.0271 and Mean Accuracy = 0.7248 + 0.0120
Mean Precision = 0.7144 + 0.0127





Seed   : 12997
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6117 - accuracy: 0.6619 - val_loss: 0.5633 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5615 - accuracy: 0.7089 - val_loss: 0.5511 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7205 - val_loss: 0.5437 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7270 - val_loss: 0.5384 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5285 - accuracy: 0.7318 - val_loss: 0.5484 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5191 - accuracy: 0.7383 - val_loss: 0.5508 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7419 - val_loss: 0.5387 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7467 - val_loss: 0.5395 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7535 - val_loss: 0.5348 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7568 - val_loss: 0.5343 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4868 - accuracy: 0.7595 - val_loss: 0.5373 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4788 - accuracy: 0.7660 - val_loss: 0.5404 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4732 - accuracy: 0.7686 - val_loss: 0.5397 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 14/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4668 - accuracy: 0.7712
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4672 - accuracy: 0.7705 - val_loss: 0.5433 - val_accuracy: 0.7237 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4041633739949946
Confusion Matrix :
 [[2753 1570]
 [1020 3303]]
Accuracy on test set:    0.7004395095998149
Sensitivity:    0.7640527411519777 	 Specificity:    0.6368262780476521
Precision  : 0.6778165401190231
Area Under Curve:    0.7004395095998149
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6178 - accuracy: 0.6590 - val_loss: 0.5689 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5612 - accuracy: 0.7080 - val_loss: 0.5510 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7217 - val_loss: 0.5430 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7275 - val_loss: 0.5416 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7342 - val_loss: 0.5441 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7387 - val_loss: 0.5438 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7429 - val_loss: 0.5339 - val_accuracy: 0.7294 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7466 - val_loss: 0.5406 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7495 - val_loss: 0.5402 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4906 - accuracy: 0.7573 - val_loss: 0.5401 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4827 - accuracy: 0.7600 - val_loss: 0.5518 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 12/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4769 - accuracy: 0.7629
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4775 - accuracy: 0.7624 - val_loss: 0.5437 - val_accuracy: 0.7274 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4343737629798503
Confusion Matrix :
 [[3037 1286]
 [1160 3163]]
Accuracy on test set:    0.7170946102243813
Sensitivity:    0.7316678232708768 	 Specificity:    0.7025213971778858
Precision  : 0.7109462800629355
Area Under Curve:    0.7170946102243811
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5987 - accuracy: 0.6719 - val_loss: 0.5676 - val_accuracy: 0.7044 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5567 - accuracy: 0.7123 - val_loss: 0.5505 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7239 - val_loss: 0.5416 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7303 - val_loss: 0.5453 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7357 - val_loss: 0.5409 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7407 - val_loss: 0.5369 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5114 - accuracy: 0.7423 - val_loss: 0.5405 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7470 - val_loss: 0.5397 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7503 - val_loss: 0.5402 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7535 - val_loss: 0.5473 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4875 - accuracy: 0.7577 - val_loss: 0.5402 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4810 - accuracy: 0.7618 - val_loss: 0.5532 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4770 - accuracy: 0.7632
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4766 - accuracy: 0.7635 - val_loss: 0.5521 - val_accuracy: 0.7292 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.44894870843996926
Confusion Matrix :
 [[2910 1413]
 [ 979 3344]]
Accuracy on test set:    0.7233402729585936
Sensitivity:    0.7735368956743003 	 Specificity:    0.6731436502428869
Precision  : 0.7029640529745638
Area Under Curve:    0.7233402729585936
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.5967 - accuracy: 0.6743 - val_loss: 0.5586 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5550 - accuracy: 0.7143 - val_loss: 0.5462 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7242 - val_loss: 0.5419 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7312 - val_loss: 0.5427 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7357 - val_loss: 0.5367 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5159 - accuracy: 0.7405 - val_loss: 0.5380 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7468 - val_loss: 0.5431 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7478 - val_loss: 0.5408 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4988 - accuracy: 0.7510 - val_loss: 0.5380 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7566 - val_loss: 0.5486 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4866 - accuracy: 0.7597 - val_loss: 0.5374 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4791 - accuracy: 0.7638 - val_loss: 0.5437 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4742 - accuracy: 0.7652 - val_loss: 0.5441 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7687 - val_loss: 0.5460 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4630 - accuracy: 0.7719 - val_loss: 0.5498 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4576 - accuracy: 0.7763 - val_loss: 0.5536 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4515 - accuracy: 0.7787 - val_loss: 0.5549 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4464 - accuracy: 0.7826 - val_loss: 0.5582 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 19/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4400 - accuracy: 0.7855
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4404 - accuracy: 0.7853 - val_loss: 0.5596 - val_accuracy: 0.7183 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4442984202066329
Confusion Matrix :
 [[2795 1528]
 [ 895 3428]]
Accuracy on test set:    0.7197547999074717
Sensitivity:    0.7929678464029609 	 Specificity:    0.6465417534119824
Precision  : 0.6916868442292171
Area Under Curve:    0.7197547999074716
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6016 - accuracy: 0.6710 - val_loss: 0.5736 - val_accuracy: 0.6962 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5568 - accuracy: 0.7127 - val_loss: 0.5487 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7229 - val_loss: 0.5401 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7273 - val_loss: 0.5393 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5240 - accuracy: 0.7355 - val_loss: 0.5359 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5177 - accuracy: 0.7390 - val_loss: 0.5333 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5119 - accuracy: 0.7409 - val_loss: 0.5317 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5050 - accuracy: 0.7470 - val_loss: 0.5333 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7492 - val_loss: 0.5354 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7539 - val_loss: 0.5393 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7591 - val_loss: 0.5389 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4810 - accuracy: 0.7626
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4818 - accuracy: 0.7621 - val_loss: 0.5335 - val_accuracy: 0.7274 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4550120441776107
Confusion Matrix :
 [[3075 1248]
 [1109 3214]]
Accuracy on test set:    0.7273883876937312
Sensitivity:    0.7434651862132778 	 Specificity:    0.7113115891741846
Precision  : 0.7203047960555805
Area Under Curve:    0.7273883876937312
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6099 - accuracy: 0.6636 - val_loss: 0.5582 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5598 - accuracy: 0.7102 - val_loss: 0.5426 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7221 - val_loss: 0.5441 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7284 - val_loss: 0.5362 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7330 - val_loss: 0.5350 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7361 - val_loss: 0.5356 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7393 - val_loss: 0.5397 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5108 - accuracy: 0.7421
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5116 - accuracy: 0.7418 - val_loss: 0.5351 - val_accuracy: 0.7247 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.43261037844800787
Confusion Matrix :
 [[2918 1405]
 [1054 3269]]
Accuracy on test set:    0.7155910247513301
Sensitivity:    0.7561878325237104 	 Specificity:    0.6749942169789498
Precision  : 0.6994009413778348
Area Under Curve:    0.7155910247513301
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6043 - accuracy: 0.6695 - val_loss: 0.5609 - val_accuracy: 0.7055 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7112 - val_loss: 0.5462 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7215 - val_loss: 0.5420 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7282 - val_loss: 0.5383 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5252 - accuracy: 0.7357 - val_loss: 0.5367 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5191 - accuracy: 0.7377 - val_loss: 0.5400 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5120 - accuracy: 0.7427 - val_loss: 0.5355 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7486 - val_loss: 0.5389 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
255/274 [==========================>...] - ETA: 0s - loss: 0.4968 - accuracy: 0.7536
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.7533 - val_loss: 0.5394 - val_accuracy: 0.7235 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.45586338565203305
Confusion Matrix :
 [[3204 1119]
 [1234 3089]]
Accuracy on test set:    0.7278510293777469
Sensitivity:    0.7145500809622947 	 Specificity:    0.7411519777931992
Precision  : 0.7340779467680608
Area Under Curve:    0.7278510293777469
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6018 - accuracy: 0.6698 - val_loss: 0.5551 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5579 - accuracy: 0.7103 - val_loss: 0.5426 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7219 - val_loss: 0.5431 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7303 - val_loss: 0.5382 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7363 - val_loss: 0.5397 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7384 - val_loss: 0.5371 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5096 - accuracy: 0.7456 - val_loss: 0.5383 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7510 - val_loss: 0.5515 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4968 - accuracy: 0.7522
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7525 - val_loss: 0.5396 - val_accuracy: 0.7271 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4559545733886636
Confusion Matrix :
 [[2882 1441]
 [ 925 3398]]
Accuracy on test set:    0.7263474439046959
Sensitivity:    0.786028221142725 	 Specificity:    0.6666666666666666
Precision  : 0.7022112006612936
Area Under Curve:    0.7263474439046959
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6152 - accuracy: 0.6577 - val_loss: 0.5588 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5640 - accuracy: 0.7093 - val_loss: 0.5509 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5510 - accuracy: 0.7166 - val_loss: 0.5501 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7271 - val_loss: 0.5379 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7282 - val_loss: 0.5338 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7367 - val_loss: 0.5327 - val_accuracy: 0.7314 - lr: 0.0010

Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7407 - val_loss: 0.5338 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5110 - accuracy: 0.7435 - val_loss: 0.5321 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7472 - val_loss: 0.5388 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7495 - val_loss: 0.5352 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7551 - val_loss: 0.5357 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4856 - accuracy: 0.7574 - val_loss: 0.5443 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4793 - accuracy: 0.7630
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4794 - accuracy: 0.7626 - val_loss: 0.5411 - val_accuracy: 0.7276 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4531673167996616
Confusion Matrix :
 [[3211 1112]
 [1253 3070]]
Accuracy on test set:    0.7264631043256997
Sensitivity:    0.7101549849641453 	 Specificity:    0.7427712236872542
Precision  : 0.7340985174557628
Area Under Curve:    0.7264631043256998
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6171 - accuracy: 0.6580 - val_loss: 0.5623 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5638 - accuracy: 0.7080 - val_loss: 0.5568 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5489 - accuracy: 0.7190 - val_loss: 0.5421 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7262 - val_loss: 0.5392 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5294 - accuracy: 0.7327 - val_loss: 0.5374 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5251 - accuracy: 0.7357 - val_loss: 0.5347 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7408 - val_loss: 0.5375 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7470 - val_loss: 0.5374 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7490 - val_loss: 0.5383 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7522 - val_loss: 0.5382 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4929 - accuracy: 0.7559 - val_loss: 0.5393 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4856 - accuracy: 0.7603 - val_loss: 0.5432 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4786 - accuracy: 0.7650
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4795 - accuracy: 0.7646 - val_loss: 0.5408 - val_accuracy: 0.7204 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.47992722477473565
Confusion Matrix :
 [[3413  910]
 [1349 2974]]
Accuracy on test set:    0.7387231089521166
Sensitivity:    0.6879481841313903 	 Specificity:    0.7894980337728429
Precision  : 0.7657054582904222
Area Under Curve:    0.7387231089521166
(8646, 4352) (8646,)
Mean MCC = 0.4464 + 0.0189 and Mean AUC = 0.7223 + 0.0096
Mean Sensitivity = 0.7461 + 0.0329 and Mean Specificity = 0.6985 + 0.0458 and Mean Accuracy = 0.7223 + 0.0096
Mean Precision = 0.7139 + 0.0241





Seed   : 805755
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6002 - accuracy: 0.6734 - val_loss: 0.5624 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5546 - accuracy: 0.7149 - val_loss: 0.5462 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7259 - val_loss: 0.5441 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5310 - accuracy: 0.7298 - val_loss: 0.5434 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7360 - val_loss: 0.5339 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7397 - val_loss: 0.5355 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7445 - val_loss: 0.5371 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7510 - val_loss: 0.5345 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4950 - accuracy: 0.7542 - val_loss: 0.5317 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4898 - accuracy: 0.7565 - val_loss: 0.5331 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7617 - val_loss: 0.5358 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4750 - accuracy: 0.7675 - val_loss: 0.5365 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4682 - accuracy: 0.7700 - val_loss: 0.5444 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4628 - accuracy: 0.7741 - val_loss: 0.5477 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4551 - accuracy: 0.7797 - val_loss: 0.5377 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4507 - accuracy: 0.7812
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4517 - accuracy: 0.7808 - val_loss: 0.5434 - val_accuracy: 0.7267 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.4021777200569986
Confusion Matrix :
 [[2799 1524]
 [1070 3253]]
Accuracy on test set:    0.6999768679157992
Sensitivity:    0.7524866990515845 	 Specificity:    0.6474670367800138
Precision  : 0.6809713209127067
Area Under Curve:    0.6999768679157992
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6013 - accuracy: 0.6710 - val_loss: 0.5642 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5588 - accuracy: 0.7113 - val_loss: 0.5494 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7226 - val_loss: 0.5413 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7264 - val_loss: 0.5408 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7307 - val_loss: 0.5400 - val_accuracy: 0.7238 - lr: 0.0010

Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7359 - val_loss: 0.5370 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7421 - val_loss: 0.5404 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7450 - val_loss: 0.5368 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7498 - val_loss: 0.5421 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4987 - accuracy: 0.7508 - val_loss: 0.5423 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4924 - accuracy: 0.7546 - val_loss: 0.5394 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4877 - accuracy: 0.7587 - val_loss: 0.5398 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7615 - val_loss: 0.5445 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4792 - accuracy: 0.7629 - val_loss: 0.5392 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4721 - accuracy: 0.7664 - val_loss: 0.5413 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 16/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4674 - accuracy: 0.7692
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4680 - accuracy: 0.7690 - val_loss: 0.5475 - val_accuracy: 0.7209 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.42150226542576763
Confusion Matrix :
 [[2680 1643]
 [ 886 3437]]
Accuracy on test set:    0.7074947952810549
Sensitivity:    0.7950497339810317 	 Specificity:    0.619939856581078
Precision  : 0.6765748031496063
Area Under Curve:    0.7074947952810549
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6142 - accuracy: 0.6587 - val_loss: 0.5650 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5639 - accuracy: 0.7074 - val_loss: 0.5534 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7209 - val_loss: 0.5459 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7266 - val_loss: 0.5399 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5276 - accuracy: 0.7329 - val_loss: 0.5407 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5225 - accuracy: 0.7367 - val_loss: 0.5385 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7420 - val_loss: 0.5351 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7438 - val_loss: 0.5372 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7500 - val_loss: 0.5377 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7531 - val_loss: 0.5430 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7546 - val_loss: 0.5473 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 12/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4847 - accuracy: 0.7605
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4860 - accuracy: 0.7594 - val_loss: 0.5415 - val_accuracy: 0.7206 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.44449117855567427
Confusion Matrix :
 [[3232 1091]
 [1313 3010]]
Accuracy on test set:    0.7219523479065464
Sensitivity:    0.6962757344436734 	 Specificity:    0.7476289613694194
Precision  : 0.7339673250426725
Area Under Curve:    0.7219523479065464
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6052 - accuracy: 0.6658 - val_loss: 0.5564 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5617 - accuracy: 0.7097 - val_loss: 0.5464 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7231 - val_loss: 0.5424 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7304 - val_loss: 0.5356 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7346 - val_loss: 0.5382 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5197 - accuracy: 0.7385 - val_loss: 0.5349 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7423 - val_loss: 0.5331 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7461 - val_loss: 0.5319 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7477 - val_loss: 0.5343 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4967 - accuracy: 0.7537
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7540 - val_loss: 0.5377 - val_accuracy: 0.7228 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4307614977994175
Confusion Matrix :
 [[3015 1308]
 [1154 3169]]
Accuracy on test set:    0.7152440434883183
Sensitivity:    0.7330557483229239 	 Specificity:    0.6974323386537127
Precision  : 0.7078400714764351
Area Under Curve:    0.7152440434883183
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6100 - accuracy: 0.6634 - val_loss: 0.5598 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5597 - accuracy: 0.7109 - val_loss: 0.5464 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7202 - val_loss: 0.5388 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7266 - val_loss: 0.5350 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7309 - val_loss: 0.5361 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5223 - accuracy: 0.7360 - val_loss: 0.5360 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5163 - accuracy: 0.7414 - val_loss: 0.5328 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5116 - accuracy: 0.7413 - val_loss: 0.5292 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5048 - accuracy: 0.7482 - val_loss: 0.5299 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 10/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5002 - accuracy: 0.7507 - val_loss: 0.5437 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7542 - val_loss: 0.5333 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7570 - val_loss: 0.5335 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.7586 - val_loss: 0.5397 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4753 - accuracy: 0.7640
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7642 - val_loss: 0.5459 - val_accuracy: 0.7304 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4499424650653153
Confusion Matrix :
 [[2909 1414]
 [ 974 3349]]
Accuracy on test set:    0.7238029146426093
Sensitivity:    0.7746934998843396 	 Specificity:    0.672912329400879
Precision  : 0.703128280495486
Area Under Curve:    0.7238029146426093
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6144 - accuracy: 0.6586 - val_loss: 0.5629 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5619 - accuracy: 0.7094 - val_loss: 0.5482 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7227 - val_loss: 0.5385 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7278 - val_loss: 0.5339 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5262 - accuracy: 0.7347 - val_loss: 0.5417 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5219 - accuracy: 0.7368 - val_loss: 0.5327 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7438 - val_loss: 0.5309 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5052 - accuracy: 0.7467 - val_loss: 0.5323 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5017 - accuracy: 0.7496 - val_loss: 0.5351 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7530 - val_loss: 0.5351 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4884 - accuracy: 0.7570 - val_loss: 0.5437 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7600 - val_loss: 0.5404 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4778 - accuracy: 0.7633 - val_loss: 0.5398 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4702 - accuracy: 0.7673 - val_loss: 0.5510 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4657 - accuracy: 0.7687 - val_loss: 0.5475 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4571 - accuracy: 0.7754 - val_loss: 0.5525 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4553 - accuracy: 0.7741 - val_loss: 0.5647 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 18/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4485 - accuracy: 0.7790
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4484 - accuracy: 0.7790 - val_loss: 0.5641 - val_accuracy: 0.7287 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4504355272984851
Confusion Matrix :
 [[3009 1314]
 [1065 3258]]
Accuracy on test set:    0.7248438584316447
Sensitivity:    0.7536433032616239 	 Specificity:    0.6960444136016655
Precision  : 0.7125984251968503
Area Under Curve:    0.7248438584316447
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6034 - accuracy: 0.6708 - val_loss: 0.5597 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7131 - val_loss: 0.5468 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7237 - val_loss: 0.5514 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7309 - val_loss: 0.5448 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5252 - accuracy: 0.7344 - val_loss: 0.5347 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7410 - val_loss: 0.5420 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5122 - accuracy: 0.7417 - val_loss: 0.5356 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7489 - val_loss: 0.5376 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4973 - accuracy: 0.7532 - val_loss: 0.5323 - val_accuracy: 0.7330 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7564 - val_loss: 0.5453 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4845 - accuracy: 0.7605 - val_loss: 0.5427 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4797 - accuracy: 0.7621 - val_loss: 0.5469 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4741 - accuracy: 0.7664 - val_loss: 0.5405 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 14/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4618 - accuracy: 0.7742
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4631 - accuracy: 0.7737 - val_loss: 0.5488 - val_accuracy: 0.7295 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4414127382273835
Confusion Matrix :
 [[2911 1412]
 [1011 3312]]
Accuracy on test set:    0.7197547999074717
Sensitivity:    0.7661346287300486 	 Specificity:    0.6733749710848947
Precision  : 0.7011007620660458
Area Under Curve:    0.7197547999074717
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6102 - accuracy: 0.6623 - val_loss: 0.5650 - val_accuracy: 0.7034 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5617 - accuracy: 0.7097 - val_loss: 0.5483 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7213 - val_loss: 0.5474 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7283 - val_loss: 0.5387 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7322 - val_loss: 0.5460 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5257 - accuracy: 0.7349 - val_loss: 0.5399 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7401 - val_loss: 0.5401 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7439 - val_loss: 0.5414 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7445 - val_loss: 0.5354 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7487 - val_loss: 0.5377 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4953 - accuracy: 0.7531
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4951 - accuracy: 0.7532 - val_loss: 0.5399 - val_accuracy: 0.7265 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.44899459089754057
Confusion Matrix :
 [[3062 1261]
 [1122 3201]]
Accuracy on test set:    0.724381216747629
Sensitivity:    0.7404580152671756 	 Specificity:    0.7083044182280823
Precision  : 0.717391304347826
Area Under Curve:    0.724381216747629
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6136 - accuracy: 0.6619 - val_loss: 0.5641 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7134 - val_loss: 0.5487 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7216 - val_loss: 0.5458 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7291 - val_loss: 0.5411 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7335 - val_loss: 0.5536 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5187 - accuracy: 0.7380 - val_loss: 0.5407 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7429 - val_loss: 0.5363 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7487 - val_loss: 0.5377 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7506 - val_loss: 0.5351 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7539 - val_loss: 0.5412 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7585 - val_loss: 0.5397 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4842 - accuracy: 0.7610 - val_loss: 0.5396 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4775 - accuracy: 0.7636 - val_loss: 0.5413 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4701 - accuracy: 0.7681
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4704 - accuracy: 0.7683 - val_loss: 0.5408 - val_accuracy: 0.7195 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4526293704081584
Confusion Matrix :
 [[3198 1125]
 [1242 3081]]
Accuracy on test set:    0.7262317834836919
Sensitivity:    0.7126995142262318 	 Specificity:    0.739764052741152
Precision  : 0.7325249643366619
Area Under Curve:    0.7262317834836919
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6119 - accuracy: 0.6628 - val_loss: 0.5659 - val_accuracy: 0.7032 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5638 - accuracy: 0.7088 - val_loss: 0.5604 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7215 - val_loss: 0.5473 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5369 - accuracy: 0.7275 - val_loss: 0.5483 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7314 - val_loss: 0.5451 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5189 - accuracy: 0.7385 - val_loss: 0.5482 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5147 - accuracy: 0.7437 - val_loss: 0.5455 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7479 - val_loss: 0.5440 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7498 - val_loss: 0.5417 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4973 - accuracy: 0.7525 - val_loss: 0.5562 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7592 - val_loss: 0.5474 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7619 - val_loss: 0.5517 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4750 - accuracy: 0.7664 - val_loss: 0.5632 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 14/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4691 - accuracy: 0.7692
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4701 - accuracy: 0.7688 - val_loss: 0.5560 - val_accuracy: 0.7195 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4995996402652463
Confusion Matrix :
 [[3409  914]
 [1256 3067]]
Accuracy on test set:    0.7490168864214666
Sensitivity:    0.7094610224381217 	 Specificity:    0.7885727504048115
Precision  : 0.7704094448630997
Area Under Curve:    0.7490168864214666
(8646, 4352) (8646,)
Mean MCC = 0.4442 + 0.0239 and Mean AUC = 0.7213 + 0.0123
Mean Sensitivity = 0.7434 + 0.0296 and Mean Specificity = 0.6991 + 0.0473 and Mean Accuracy = 0.7213 + 0.0123
Mean Precision = 0.7137 + 0.0260





Seed   : 869305
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6024 - accuracy: 0.6701 - val_loss: 0.5592 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5567 - accuracy: 0.7129 - val_loss: 0.5472 - val_accuracy: 0.7092 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7211 - val_loss: 0.5461 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7303 - val_loss: 0.5420 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7333 - val_loss: 0.5369 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5194 - accuracy: 0.7392 - val_loss: 0.5309 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7436 - val_loss: 0.5293 - val_accuracy: 0.7251 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7462 - val_loss: 0.5291 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7506 - val_loss: 0.5299 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4963 - accuracy: 0.7522 - val_loss: 0.5291 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7554 - val_loss: 0.5328 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7581 - val_loss: 0.5320 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7635 - val_loss: 0.5325 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 14/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4738 - accuracy: 0.7647
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4744 - accuracy: 0.7646 - val_loss: 0.5396 - val_accuracy: 0.7245 - lr: 0.0010
271/271 [==============================] - 0s 671us/step
Independent Testing Matthews Correlation:  0.4073555161014019
Confusion Matrix :
 [[2807 1516]
 [1056 3267]]
Accuracy on test set:    0.7025213971778858
Sensitivity:    0.7557251908396947 	 Specificity:    0.6493176035160768
Precision  : 0.6830441145724441
Area Under Curve:    0.7025213971778858
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6040 - accuracy: 0.6695 - val_loss: 0.5670 - val_accuracy: 0.7055 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5570 - accuracy: 0.7129 - val_loss: 0.5501 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7236 - val_loss: 0.5429 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7308 - val_loss: 0.5387 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5251 - accuracy: 0.7340 - val_loss: 0.5443 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7400 - val_loss: 0.5386 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5120 - accuracy: 0.7421 - val_loss: 0.5428 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.7469 - val_loss: 0.5352 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 9/400
259/274 [===========================>..] - ETA: 0s - loss: 0.5016 - accuracy: 0.7476
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5020 - accuracy: 0.7475 - val_loss: 0.5420 - val_accuracy: 0.7231 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.42640434727206045
Confusion Matrix :
 [[2916 1407]
 [1078 3245]]
Accuracy on test set:    0.7125838538052278
Sensitivity:    0.7506361323155216 	 Specificity:    0.6745315752949341
Precision  : 0.6975494411006019
Area Under Curve:    0.712583853805228
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6177 - accuracy: 0.6538 - val_loss: 0.5639 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.7076 - val_loss: 0.5522 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7202 - val_loss: 0.5481 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7267 - val_loss: 0.5428 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7335 - val_loss: 0.5469 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5234 - accuracy: 0.7367 - val_loss: 0.5389 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7419 - val_loss: 0.5414 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7467 - val_loss: 0.5392 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5032 - accuracy: 0.7493 - val_loss: 0.5334 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7530 - val_loss: 0.5441 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7558 - val_loss: 0.5401 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7580 - val_loss: 0.5389 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4815 - accuracy: 0.7612 - val_loss: 0.5467 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4730 - accuracy: 0.7672 - val_loss: 0.5473 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4677 - accuracy: 0.7707 - val_loss: 0.5554 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 16/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4610 - accuracy: 0.7744
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4625 - accuracy: 0.7735 - val_loss: 0.5447 - val_accuracy: 0.7254 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.45342292809777274
Confusion Matrix :
 [[3168 1155]
 [1208 3115]]
Accuracy on test set:    0.7266944251677077
Sensitivity:    0.7205644228544992 	 Specificity:    0.732824427480916
Precision  : 0.7295081967213115
Area Under Curve:    0.7266944251677075
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6038 - accuracy: 0.6693 - val_loss: 0.5656 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7118 - val_loss: 0.5656 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7220 - val_loss: 0.5425 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7300 - val_loss: 0.5366 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5267 - accuracy: 0.7335 - val_loss: 0.5358 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7396 - val_loss: 0.5419 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7434 - val_loss: 0.5350 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7468 - val_loss: 0.5373 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7511 - val_loss: 0.5342 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7545 - val_loss: 0.5363 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 11/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7582 - val_loss: 0.5350 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7600 - val_loss: 0.5381 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4742 - accuracy: 0.7647 - val_loss: 0.5377 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4689 - accuracy: 0.7696
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4693 - accuracy: 0.7693 - val_loss: 0.5386 - val_accuracy: 0.7290 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.43669015471013
Confusion Matrix :
 [[2869 1454]
 [ 992 3331]]
Accuracy on test set:    0.7170946102243813
Sensitivity:    0.770529724728198 	 Specificity:    0.6636594957205644
Precision  : 0.6961337513061651
Area Under Curve:    0.7170946102243811
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6029 - accuracy: 0.6695 - val_loss: 0.5601 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7103 - val_loss: 0.5527 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7208 - val_loss: 0.5397 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7285 - val_loss: 0.5344 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5270 - accuracy: 0.7340 - val_loss: 0.5304 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5222 - accuracy: 0.7360 - val_loss: 0.5311 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5141 - accuracy: 0.7404 - val_loss: 0.5281 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7438 - val_loss: 0.5320 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7452 - val_loss: 0.5347 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4978 - accuracy: 0.7507 - val_loss: 0.5308 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7544 - val_loss: 0.5323 - val_accuracy: 0.7344 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7577 - val_loss: 0.5397 - val_accuracy: 0.7340 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7621 - val_loss: 0.5412 - val_accuracy: 0.7341 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7643 - val_loss: 0.5371 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4687 - accuracy: 0.7678 - val_loss: 0.5457 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4680 - accuracy: 0.7675
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7670 - val_loss: 0.5403 - val_accuracy: 0.7318 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.45121387629449466
Confusion Matrix :
 [[3190 1133]
 [1240 3083]]
Accuracy on test set:    0.7255378209576683
Sensitivity:    0.7131621559102476 	 Specificity:    0.7379134860050891
Precision  : 0.7312618595825426
Area Under Curve:    0.7255378209576683
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6135 - accuracy: 0.6584 - val_loss: 0.5690 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5616 - accuracy: 0.7077 - val_loss: 0.5466 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7239 - val_loss: 0.5395 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7281 - val_loss: 0.5456 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5270 - accuracy: 0.7350 - val_loss: 0.5337 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5187 - accuracy: 0.7382 - val_loss: 0.5359 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7418 - val_loss: 0.5362 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7458 - val_loss: 0.5332 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7490 - val_loss: 0.5323 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7534 - val_loss: 0.5319 - val_accuracy: 0.7328 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7574 - val_loss: 0.5386 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7610 - val_loss: 0.5422 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4766 - accuracy: 0.7638 - val_loss: 0.5398 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4734 - accuracy: 0.7656 - val_loss: 0.5531 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4668 - accuracy: 0.7693
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4669 - accuracy: 0.7691 - val_loss: 0.5472 - val_accuracy: 0.7240 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.43341588124860636
Confusion Matrix :
 [[3352  971]
 [1492 2831]]
Accuracy on test set:    0.7151283830673144
Sensitivity:    0.6548693037242656 	 Specificity:    0.7753874624103632
Precision  : 0.7446081009994739
Area Under Curve:    0.7151283830673143
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6027 - accuracy: 0.6712 - val_loss: 0.5573 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5593 - accuracy: 0.7131 - val_loss: 0.5463 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7223 - val_loss: 0.5437 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7290 - val_loss: 0.5573 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5261 - accuracy: 0.7343 - val_loss: 0.5361 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5168 - accuracy: 0.7409 - val_loss: 0.5343 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5111 - accuracy: 0.7445 - val_loss: 0.5369 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7488 - val_loss: 0.5395 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7525 - val_loss: 0.5399 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4929 - accuracy: 0.7563 - val_loss: 0.5341 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4856 - accuracy: 0.7588 - val_loss: 0.5422 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4795 - accuracy: 0.7656
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7651 - val_loss: 0.5461 - val_accuracy: 0.7219 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4455087454792602
Confusion Matrix :
 [[2889 1434]
 [ 974 3349]]
Accuracy on test set:    0.7214897062225306
Sensitivity:    0.7746934998843396 	 Specificity:    0.6682859125607217
Precision  : 0.7001881664227473
Area Under Curve:    0.7214897062225306
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6071 - accuracy: 0.6665 - val_loss: 0.5619 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5595 - accuracy: 0.7104 - val_loss: 0.5547 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7228 - val_loss: 0.5440 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7294 - val_loss: 0.5410 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7329 - val_loss: 0.5370 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7414 - val_loss: 0.5369 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5110 - accuracy: 0.7456 - val_loss: 0.5330 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7476 - val_loss: 0.5407 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7544 - val_loss: 0.5383 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7575 - val_loss: 0.5395 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7593 - val_loss: 0.5387 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7652 - val_loss: 0.5358 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4705 - accuracy: 0.7693 - val_loss: 0.5426 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4669 - accuracy: 0.7731 - val_loss: 0.5450 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4630 - accuracy: 0.7750
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4632 - accuracy: 0.7751 - val_loss: 0.5415 - val_accuracy: 0.7258 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4410276340650449
Confusion Matrix :
 [[3062 1261]
 [1156 3167]]
Accuracy on test set:    0.7204487624334952
Sensitivity:    0.7325931066389082 	 Specificity:    0.7083044182280823
Precision  : 0.7152213188798555
Area Under Curve:    0.7204487624334954
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6063 - accuracy: 0.6690 - val_loss: 0.5629 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5589 - accuracy: 0.7111 - val_loss: 0.5515 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7226 - val_loss: 0.5533 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7267 - val_loss: 0.5397 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7343 - val_loss: 0.5379 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7407 - val_loss: 0.5363 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7433 - val_loss: 0.5418 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5022 - accuracy: 0.7496 - val_loss: 0.5378 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4992 - accuracy: 0.7508 - val_loss: 0.5374 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4922 - accuracy: 0.7550 - val_loss: 0.5442 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4854 - accuracy: 0.7594 - val_loss: 0.5426 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4789 - accuracy: 0.7630 - val_loss: 0.5386 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4686 - accuracy: 0.7680 - val_loss: 0.5391 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4639 - accuracy: 0.7719
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4641 - accuracy: 0.7715 - val_loss: 0.5507 - val_accuracy: 0.7250 - lr: 0.0010
271/271 [==============================] - 0s 664us/step
Independent Testing Matthews Correlation:  0.4690563194439352
Confusion Matrix :
 [[3382  941]
 [1364 2959]]
Accuracy on test set:    0.7334027295859357
Sensitivity:    0.6844783715012722 	 Specificity:    0.7823270876705991
Precision  : 0.7587179487179487
Area Under Curve:    0.7334027295859358
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6103 - accuracy: 0.6647 - val_loss: 0.5629 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5624 - accuracy: 0.7087 - val_loss: 0.5498 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7202 - val_loss: 0.5426 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5369 - accuracy: 0.7275 - val_loss: 0.5576 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7338 - val_loss: 0.5387 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7399 - val_loss: 0.5395 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7421 - val_loss: 0.5396 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5053 - accuracy: 0.7485 - val_loss: 0.5376 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 9/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7495 - val_loss: 0.5349 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7514 - val_loss: 0.5385 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4869 - accuracy: 0.7597 - val_loss: 0.5386 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4819 - accuracy: 0.7620 - val_loss: 0.5440 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7669 - val_loss: 0.5433 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4689 - accuracy: 0.7699 - val_loss: 0.5442 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4656 - accuracy: 0.7706 - val_loss: 0.5427 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4599 - accuracy: 0.7743
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4597 - accuracy: 0.7745 - val_loss: 0.5664 - val_accuracy: 0.7235 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4810357892567838
Confusion Matrix :
 [[3369  954]
 [1296 3027]]
Accuracy on test set:    0.739764052741152
Sensitivity:    0.7002081887578071 	 Specificity:    0.7793199167244969
Precision  : 0.760361718161266
Area Under Curve:    0.739764052741152
(8646, 4352) (8646,)
Mean MCC = 0.4445 + 0.0199 and Mean AUC = 0.7215 + 0.0101
Mean Sensitivity = 0.7257 + 0.0368 and Mean Specificity = 0.7172 + 0.0489 and Mean Accuracy = 0.7215 + 0.0101
Mean Precision = 0.7217 + 0.0260





Seed   : 687606
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6101 - accuracy: 0.6646 - val_loss: 0.5575 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5583 - accuracy: 0.7113 - val_loss: 0.5424 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7229 - val_loss: 0.5354 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7293 - val_loss: 0.5361 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7353 - val_loss: 0.5333 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7393 - val_loss: 0.5327 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7457 - val_loss: 0.5290 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5051 - accuracy: 0.7471 - val_loss: 0.5278 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4985 - accuracy: 0.7518 - val_loss: 0.5297 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4903 - accuracy: 0.7585 - val_loss: 0.5311 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4831 - accuracy: 0.7614 - val_loss: 0.5326 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7646 - val_loss: 0.5310 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4736 - accuracy: 0.7667 - val_loss: 0.5378 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4680 - accuracy: 0.7696 - val_loss: 0.5315 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4609 - accuracy: 0.7742
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4604 - accuracy: 0.7741 - val_loss: 0.5391 - val_accuracy: 0.7228 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.42301479837424844
Confusion Matrix :
 [[3016 1307]
 [1188 3135]]
Accuracy on test set:    0.7114272495951885
Sensitivity:    0.7251908396946565 	 Specificity:    0.6976636594957205
Precision  : 0.7057631697433588
Area Under Curve:    0.7114272495951885
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6087 - accuracy: 0.6652 - val_loss: 0.5584 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5582 - accuracy: 0.7112 - val_loss: 0.5456 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7225 - val_loss: 0.5429 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7300 - val_loss: 0.5346 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7335 - val_loss: 0.5341 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5172 - accuracy: 0.7404 - val_loss: 0.5360 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7457 - val_loss: 0.5320 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7494 - val_loss: 0.5277 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5013 - accuracy: 0.7512 - val_loss: 0.5301 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7562 - val_loss: 0.5298 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4867 - accuracy: 0.7607 - val_loss: 0.5302 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4774 - accuracy: 0.7659 - val_loss: 0.5344 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 13/400
254/274 [==========================>...] - ETA: 0s - loss: 0.4709 - accuracy: 0.7688
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4715 - accuracy: 0.7683 - val_loss: 0.5345 - val_accuracy: 0.7272 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.43148256371665233
Confusion Matrix :
 [[2964 1359]
 [1102 3221]]
Accuracy on test set:    0.7153597039093222
Sensitivity:    0.7450844321073329 	 Specificity:    0.6856349757113116
Precision  : 0.7032751091703057
Area Under Curve:    0.7153597039093222
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6100 - accuracy: 0.6631 - val_loss: 0.5592 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5573 - accuracy: 0.7119 - val_loss: 0.5498 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7212 - val_loss: 0.5454 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7315 - val_loss: 0.5392 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5270 - accuracy: 0.7332 - val_loss: 0.5374 - val_accuracy: 0.7214 - lr: 0.0010

Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5178 - accuracy: 0.7390 - val_loss: 0.5340 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7423 - val_loss: 0.5285 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7467 - val_loss: 0.5322 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7524 - val_loss: 0.5295 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7529 - val_loss: 0.5276 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4895 - accuracy: 0.7571 - val_loss: 0.5352 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4851 - accuracy: 0.7593 - val_loss: 0.5359 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4778 - accuracy: 0.7646 - val_loss: 0.5340 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4725 - accuracy: 0.7674 - val_loss: 0.5391 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4639 - accuracy: 0.7737
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4644 - accuracy: 0.7735 - val_loss: 0.5438 - val_accuracy: 0.7203 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.4450152023512898
Confusion Matrix :
 [[3216 1107]
 [1294 3029]]
Accuracy on test set:    0.7222993291695582
Sensitivity:    0.7006708304418228 	 Specificity:    0.7439278278972935
Precision  : 0.7323500967117988
Area Under Curve:    0.7222993291695582
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6050 - accuracy: 0.6695 - val_loss: 0.5593 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5597 - accuracy: 0.7095 - val_loss: 0.5480 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7207 - val_loss: 0.5407 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7276 - val_loss: 0.5351 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7382 - val_loss: 0.5374 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5175 - accuracy: 0.7407 - val_loss: 0.5360 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5120 - accuracy: 0.7440 - val_loss: 0.5324 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7470 - val_loss: 0.5368 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4973 - accuracy: 0.7521 - val_loss: 0.5307 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4928 - accuracy: 0.7546 - val_loss: 0.5335 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4876 - accuracy: 0.7584 - val_loss: 0.5378 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4784 - accuracy: 0.7640
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4791 - accuracy: 0.7635 - val_loss: 0.5378 - val_accuracy: 0.7303 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.44030766524152765
Confusion Matrix :
 [[3066 1257]
 [1163 3160]]
Accuracy on test set:    0.7201017811704835
Sensitivity:    0.7309738607448532 	 Specificity:    0.7092297015961138
Precision  : 0.7154177043242019
Area Under Curve:    0.7201017811704834
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6054 - accuracy: 0.6661 - val_loss: 0.5618 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7114 - val_loss: 0.5447 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7259 - val_loss: 0.5405 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7278 - val_loss: 0.5394 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7356 - val_loss: 0.5401 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7383 - val_loss: 0.5397 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7438 - val_loss: 0.5329 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5030 - accuracy: 0.7493
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7490 - val_loss: 0.5336 - val_accuracy: 0.7218 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.4415931887099609
Confusion Matrix :
 [[3122 1201]
 [1213 3110]]
Accuracy on test set:    0.720795743696507
Sensitivity:    0.7194078186444599 	 Specificity:    0.7221836687485542
Precision  : 0.7214103456274646
Area Under Curve:    0.7207957436965071
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6087 - accuracy: 0.6637 - val_loss: 0.5619 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5593 - accuracy: 0.7138 - val_loss: 0.5462 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7233 - val_loss: 0.5446 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5310 - accuracy: 0.7322 - val_loss: 0.5345 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7359 - val_loss: 0.5321 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7398 - val_loss: 0.5299 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7465 - val_loss: 0.5286 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7503 - val_loss: 0.5355 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 9/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4947 - accuracy: 0.7544
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4955 - accuracy: 0.7543 - val_loss: 0.5363 - val_accuracy: 0.7200 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.42930106080900315
Confusion Matrix :
 [[2668 1655]
 [ 845 3478]]
Accuracy on test set:    0.7108489474901689
Sensitivity:    0.8045338885033542 	 Specificity:    0.6171640064769836
Precision  : 0.677576466004286
Area Under Curve:    0.7108489474901689
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6181 - accuracy: 0.6537 - val_loss: 0.5652 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5619 - accuracy: 0.7088 - val_loss: 0.5514 - val_accuracy: 0.7140 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7195 - val_loss: 0.5437 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7275 - val_loss: 0.5414 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7308 - val_loss: 0.5445 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5242 - accuracy: 0.7348 - val_loss: 0.5399 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7396 - val_loss: 0.5375 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5084 - accuracy: 0.7454 - val_loss: 0.5429 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5023 - accuracy: 0.7493 - val_loss: 0.5420 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7539 - val_loss: 0.5446 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4912 - accuracy: 0.7550
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7553 - val_loss: 0.5428 - val_accuracy: 0.7212 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.458226321776294
Confusion Matrix :
 [[2955 1368]
 [ 982 3341]]
Accuracy on test set:    0.7281980106407587
Sensitivity:    0.7728429331482767 	 Specificity:    0.6835530881332408
Precision  : 0.7094924612444256
Area Under Curve:    0.7281980106407586
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6198 - accuracy: 0.6515 - val_loss: 0.5684 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5674 - accuracy: 0.7052 - val_loss: 0.5503 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5540 - accuracy: 0.7148 - val_loss: 0.5410 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7258 - val_loss: 0.5503 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7292 - val_loss: 0.5400 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7348 - val_loss: 0.5362 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7374 - val_loss: 0.5471 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 8/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5121 - accuracy: 0.7423
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7421 - val_loss: 0.5411 - val_accuracy: 0.7240 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4596535109936776
Confusion Matrix :
 [[2815 1508]
 [ 851 3472]]
Accuracy on test set:    0.7271570668517233
Sensitivity:    0.803145963451307 	 Specificity:    0.6511681702521397
Precision  : 0.6971887550200804
Area Under Curve:    0.7271570668517233
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6082 - accuracy: 0.6646 - val_loss: 0.5608 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5592 - accuracy: 0.7132 - val_loss: 0.5494 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7228 - val_loss: 0.5408 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7285 - val_loss: 0.5419 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5271 - accuracy: 0.7342 - val_loss: 0.5382 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5214 - accuracy: 0.7376 - val_loss: 0.5386 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5122 - accuracy: 0.7436 - val_loss: 0.5475 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5073 - accuracy: 0.7468 - val_loss: 0.5374 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7514 - val_loss: 0.5385 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4970 - accuracy: 0.7522 - val_loss: 0.5393 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4905 - accuracy: 0.7561
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4902 - accuracy: 0.7560 - val_loss: 0.5367 - val_accuracy: 0.7303 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.4793251140984262
Confusion Matrix :
 [[3174 1149]
 [1102 3221]]
Accuracy on test set:    0.739648392320148
Sensitivity:    0.7450844321073329 	 Specificity:    0.7342123525329632
Precision  : 0.7370709382151029
Area Under Curve:    0.7396483923201481
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6043 - accuracy: 0.6663 - val_loss: 0.5709 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7088 - val_loss: 0.5463 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7209 - val_loss: 0.5424 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7293 - val_loss: 0.5414 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5270 - accuracy: 0.7353 - val_loss: 0.5437 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7402 - val_loss: 0.5506 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5150 - accuracy: 0.7431 - val_loss: 0.5421 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7469 - val_loss: 0.5394 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7520 - val_loss: 0.5405 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4952 - accuracy: 0.7539 - val_loss: 0.5477 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7574 - val_loss: 0.5475 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4822 - accuracy: 0.7623 - val_loss: 0.5481 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4763 - accuracy: 0.7656
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4766 - accuracy: 0.7655 - val_loss: 0.5455 - val_accuracy: 0.7245 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.49322443593807247
Confusion Matrix :
 [[3376  947]
 [1249 3074]]
Accuracy on test set:    0.7460097154753643
Sensitivity:    0.7110802683321767 	 Specificity:    0.7809391626185519
Precision  : 0.7644864461576723
Area Under Curve:    0.7460097154753643
(8646, 4352) (8646,)
Mean MCC = 0.4501 + 0.0214 and Mean AUC = 0.7242 + 0.0109
Mean Sensitivity = 0.7458 + 0.0347 and Mean Specificity = 0.7026 + 0.0446 and Mean Accuracy = 0.7242 + 0.0109
Mean Precision = 0.7164 + 0.0229





Seed   : 45266
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6078 - accuracy: 0.6660 - val_loss: 0.5697 - val_accuracy: 0.7003 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5589 - accuracy: 0.7117 - val_loss: 0.5509 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7248 - val_loss: 0.5482 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7298 - val_loss: 0.5368 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7365 - val_loss: 0.5407 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7394 - val_loss: 0.5364 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5118 - accuracy: 0.7438 - val_loss: 0.5332 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7471 - val_loss: 0.5338 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4987 - accuracy: 0.7539 - val_loss: 0.5355 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7567 - val_loss: 0.5317 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4893 - accuracy: 0.7577 - val_loss: 0.5374 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7628 - val_loss: 0.5362 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4786 - accuracy: 0.7656 - val_loss: 0.5359 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4727 - accuracy: 0.7667 - val_loss: 0.5370 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7702 - val_loss: 0.5390 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 16/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4594 - accuracy: 0.7763
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4599 - accuracy: 0.7762 - val_loss: 0.5456 - val_accuracy: 0.7200 - lr: 0.0010
271/271 [==============================] - 0s 673us/step
Independent Testing Matthews Correlation:  0.40624315542195966
Confusion Matrix :
 [[2802 1521]
 [1056 3267]]
Accuracy on test set:    0.7019430950728661
Sensitivity:    0.7557251908396947 	 Specificity:    0.6481609993060374
Precision  : 0.6823308270676691
Area Under Curve:    0.7019430950728661
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6025 - accuracy: 0.6707 - val_loss: 0.5617 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5570 - accuracy: 0.7138 - val_loss: 0.5586 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7258 - val_loss: 0.5499 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7302 - val_loss: 0.5411 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7362 - val_loss: 0.5411 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5171 - accuracy: 0.7392 - val_loss: 0.5372 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7455 - val_loss: 0.5374 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5055 - accuracy: 0.7481 - val_loss: 0.5385 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4994 - accuracy: 0.7503 - val_loss: 0.5331 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4938 - accuracy: 0.7552 - val_loss: 0.5393 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7566 - val_loss: 0.5386 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4832 - accuracy: 0.7617 - val_loss: 0.5415 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4794 - accuracy: 0.7636 - val_loss: 0.5411 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4688 - accuracy: 0.7689
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4698 - accuracy: 0.7681 - val_loss: 0.5415 - val_accuracy: 0.7240 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4218659223919366
Confusion Matrix :
 [[3012 1311]
 [1189 3134]]
Accuracy on test set:    0.7108489474901689
Sensitivity:    0.7249595188526486 	 Specificity:    0.6967383761276891
Precision  : 0.7050618672665917
Area Under Curve:    0.7108489474901688
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.5998 - accuracy: 0.6753 - val_loss: 0.5588 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5553 - accuracy: 0.7147 - val_loss: 0.5471 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7246 - val_loss: 0.5445 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7308 - val_loss: 0.5401 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7363 - val_loss: 0.5389 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7401 - val_loss: 0.5413 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7437 - val_loss: 0.5357 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7479 - val_loss: 0.5359 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4973 - accuracy: 0.7504 - val_loss: 0.5377 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7559 - val_loss: 0.5373 - val_accuracy: 0.7265 - lr: 0.0010

Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4850 - accuracy: 0.7586
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7585 - val_loss: 0.5431 - val_accuracy: 0.7256 - lr: 0.0010
271/271 [==============================] - 0s 658us/step
Independent Testing Matthews Correlation:  0.4418648170653896
Confusion Matrix :
 [[2785 1538]
 [ 896 3427]]
Accuracy on test set:    0.7184825352764284
Sensitivity:    0.7927365255609531 	 Specificity:    0.6442285449919037
Precision  : 0.6902316213494462
Area Under Curve:    0.7184825352764285
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6026 - accuracy: 0.6691 - val_loss: 0.5659 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5577 - accuracy: 0.7123 - val_loss: 0.5549 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7219 - val_loss: 0.5463 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7275 - val_loss: 0.5483 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7345 - val_loss: 0.5366 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7416 - val_loss: 0.5374 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5112 - accuracy: 0.7437 - val_loss: 0.5380 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5054 - accuracy: 0.7470 - val_loss: 0.5476 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5005 - accuracy: 0.7498 - val_loss: 0.5433 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4936 - accuracy: 0.7551 - val_loss: 0.5415 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7563 - val_loss: 0.5430 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7601 - val_loss: 0.5368 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4783 - accuracy: 0.7615 - val_loss: 0.5409 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4733 - accuracy: 0.7666 - val_loss: 0.5473 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4665 - accuracy: 0.7694 - val_loss: 0.5565 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4606 - accuracy: 0.7734 - val_loss: 0.5615 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 17/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4582 - accuracy: 0.7747
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4582 - accuracy: 0.7749 - val_loss: 0.5649 - val_accuracy: 0.7182 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.43166096006799964
Confusion Matrix :
 [[2707 1616]
 [ 869 3454]]
Accuracy on test set:    0.7125838538052278
Sensitivity:    0.7989821882951654 	 Specificity:    0.6261855193152903
Precision  : 0.6812623274161735
Area Under Curve:    0.7125838538052278
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6045 - accuracy: 0.6690 - val_loss: 0.5641 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5554 - accuracy: 0.7133 - val_loss: 0.5470 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7248 - val_loss: 0.5405 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5279 - accuracy: 0.7320 - val_loss: 0.5352 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5206 - accuracy: 0.7366 - val_loss: 0.5374 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5130 - accuracy: 0.7426 - val_loss: 0.5407 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7465 - val_loss: 0.5333 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7520 - val_loss: 0.5372 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7589 - val_loss: 0.5413 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7646 - val_loss: 0.5381 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7667 - val_loss: 0.5385 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4713 - accuracy: 0.7688
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4709 - accuracy: 0.7688 - val_loss: 0.5522 - val_accuracy: 0.7204 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.4271097664540663
Confusion Matrix :
 [[2730 1593]
 [ 907 3416]]
Accuracy on test set:    0.7108489474901689
Sensitivity:    0.7901919962988665 	 Specificity:    0.6315058986814712
Precision  : 0.6819724495907367
Area Under Curve:    0.7108489474901689
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6004 - accuracy: 0.6718 - val_loss: 0.5573 - val_accuracy: 0.7118 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7125 - val_loss: 0.5512 - val_accuracy: 0.7133 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7246 - val_loss: 0.5409 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7306 - val_loss: 0.5414 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7381 - val_loss: 0.5413 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5168 - accuracy: 0.7428 - val_loss: 0.5428 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7457 - val_loss: 0.5433 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7469 - val_loss: 0.5405 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7516 - val_loss: 0.5406 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7557 - val_loss: 0.5382 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4854 - accuracy: 0.7608 - val_loss: 0.5418 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7645 - val_loss: 0.5406 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 13/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4759 - accuracy: 0.7651 - val_loss: 0.5541 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4712 - accuracy: 0.7682 - val_loss: 0.5450 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4625 - accuracy: 0.7732
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4622 - accuracy: 0.7729 - val_loss: 0.5573 - val_accuracy: 0.7251 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.435115976711979
Confusion Matrix :
 [[2959 1364]
 [1082 3241]]
Accuracy on test set:    0.7170946102243813
Sensitivity:    0.7497108489474902 	 Specificity:    0.6844783715012722
Precision  : 0.703800217155266
Area Under Curve:    0.7170946102243813
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6040 - accuracy: 0.6716 - val_loss: 0.5684 - val_accuracy: 0.7039 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5571 - accuracy: 0.7122 - val_loss: 0.5478 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7240 - val_loss: 0.5482 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5314 - accuracy: 0.7303 - val_loss: 0.5436 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7366 - val_loss: 0.5395 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7414 - val_loss: 0.5370 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7441 - val_loss: 0.5367 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7493 - val_loss: 0.5353 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7537 - val_loss: 0.5423 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4904 - accuracy: 0.7576 - val_loss: 0.5447 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7620 - val_loss: 0.5376 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4776 - accuracy: 0.7655 - val_loss: 0.5472 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4726 - accuracy: 0.7684 - val_loss: 0.5433 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4655 - accuracy: 0.7702 - val_loss: 0.5495 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4598 - accuracy: 0.7735 - val_loss: 0.5515 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4511 - accuracy: 0.7796 - val_loss: 0.5515 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4478 - accuracy: 0.7813 - val_loss: 0.5593 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4404 - accuracy: 0.7854 - val_loss: 0.5636 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 19/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4340 - accuracy: 0.7868
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4343 - accuracy: 0.7868 - val_loss: 0.5706 - val_accuracy: 0.7210 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4482998038053539
Confusion Matrix :
 [[3130 1193]
 [1192 3131]]
Accuracy on test set:    0.7241498959056211
Sensitivity:    0.724265556326625 	 Specificity:    0.7240342354846172
Precision  : 0.7240980573543015
Area Under Curve:    0.7241498959056212
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6098 - accuracy: 0.6653 - val_loss: 0.5685 - val_accuracy: 0.6997 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5612 - accuracy: 0.7107 - val_loss: 0.5493 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7196 - val_loss: 0.5460 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7272 - val_loss: 0.5405 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7316 - val_loss: 0.5417 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7358 - val_loss: 0.5382 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5149 - accuracy: 0.7405 - val_loss: 0.5396 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5116 - accuracy: 0.7434 - val_loss: 0.5403 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7471 - val_loss: 0.5395 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4995 - accuracy: 0.7492 - val_loss: 0.5456 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4947 - accuracy: 0.7530 - val_loss: 0.5430 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4897 - accuracy: 0.7563 - val_loss: 0.5414 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4833 - accuracy: 0.7584 - val_loss: 0.5483 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4777 - accuracy: 0.7628 - val_loss: 0.5465 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4716 - accuracy: 0.7659 - val_loss: 0.5598 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4666 - accuracy: 0.7690 - val_loss: 0.5579 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4600 - accuracy: 0.7714 - val_loss: 0.5488 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4570 - accuracy: 0.7727 - val_loss: 0.5573 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4587 - accuracy: 0.7731 - val_loss: 0.5633 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4460 - accuracy: 0.7788 - val_loss: 0.5617 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4423 - accuracy: 0.7815 - val_loss: 0.5630 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 22/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4398 - accuracy: 0.7812
Epoch 22: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4402 - accuracy: 0.7809 - val_loss: 0.5794 - val_accuracy: 0.7245 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.46139155590977626
Confusion Matrix :
 [[2931 1392]
 [ 947 3376]]
Accuracy on test set:    0.729470275271802
Sensitivity:    0.7809391626185519 	 Specificity:    0.678001387925052
Precision  : 0.7080536912751678
Area Under Curve:    0.729470275271802
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6105 - accuracy: 0.6633 - val_loss: 0.5652 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5626 - accuracy: 0.7093 - val_loss: 0.5651 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7220 - val_loss: 0.5512 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7256 - val_loss: 0.5473 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7301 - val_loss: 0.5439 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7390 - val_loss: 0.5408 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5158 - accuracy: 0.7404 - val_loss: 0.5467 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7458 - val_loss: 0.5396 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7496 - val_loss: 0.5458 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7536 - val_loss: 0.5529 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4930 - accuracy: 0.7551 - val_loss: 0.5602 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4882 - accuracy: 0.7575 - val_loss: 0.5457 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4812 - accuracy: 0.7619
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4816 - accuracy: 0.7615 - val_loss: 0.5458 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.47401907018861156
Confusion Matrix :
 [[3215 1108]
 [1166 3157]]
Accuracy on test set:    0.7369882026370576
Sensitivity:    0.7302798982188295 	 Specificity:    0.7436965070552857
Precision  : 0.74021101992966
Area Under Curve:    0.7369882026370576
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6076 - accuracy: 0.6655 - val_loss: 0.5672 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5618 - accuracy: 0.7108 - val_loss: 0.5578 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7204 - val_loss: 0.5493 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7270 - val_loss: 0.5490 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5301 - accuracy: 0.7325 - val_loss: 0.5447 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7354 - val_loss: 0.5458 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5172 - accuracy: 0.7405 - val_loss: 0.5486 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7441 - val_loss: 0.5525 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7478 - val_loss: 0.5473 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7523 - val_loss: 0.5493 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7553 - val_loss: 0.5466 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4875 - accuracy: 0.7588 - val_loss: 0.5473 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4820 - accuracy: 0.7641 - val_loss: 0.5545 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4790 - accuracy: 0.7643
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4788 - accuracy: 0.7643 - val_loss: 0.5523 - val_accuracy: 0.7203 - lr: 0.0010
271/271 [==============================] - 0s 646us/step
Independent Testing Matthews Correlation:  0.49666145370742815
Confusion Matrix :
 [[3349  974]
 [1205 3118]]
Accuracy on test set:    0.7479759426324312
Sensitivity:    0.7212583853805228 	 Specificity:    0.7746934998843396
Precision  : 0.7619745845552297
Area Under Curve:    0.7479759426324312
(8646, 4352) (8646,)
Mean MCC = 0.4444 + 0.0254 and Mean AUC = 0.7210 + 0.0131
Mean Sensitivity = 0.7569 + 0.0298 and Mean Specificity = 0.6852 + 0.0475 and Mean Accuracy = 0.7210 + 0.0131
Mean Precision = 0.7079 + 0.0257





Seed   : 481630
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6099 - accuracy: 0.6634 - val_loss: 0.5720 - val_accuracy: 0.6993 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5612 - accuracy: 0.7106 - val_loss: 0.5576 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7220 - val_loss: 0.5454 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7280 - val_loss: 0.5420 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5270 - accuracy: 0.7358 - val_loss: 0.5399 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.7366 - val_loss: 0.5386 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7403 - val_loss: 0.5454 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5105 - accuracy: 0.7438 - val_loss: 0.5463 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5032 - accuracy: 0.7485 - val_loss: 0.5384 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7506 - val_loss: 0.5378 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4949 - accuracy: 0.7544 - val_loss: 0.5403 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4884 - accuracy: 0.7554 - val_loss: 0.5521 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4817 - accuracy: 0.7624 - val_loss: 0.5435 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4780 - accuracy: 0.7621 - val_loss: 0.5389 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4691 - accuracy: 0.7698 - val_loss: 0.5453 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4679 - accuracy: 0.7692 - val_loss: 0.5514 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4588 - accuracy: 0.7753 - val_loss: 0.5472 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 18/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4559 - accuracy: 0.7759 - val_loss: 0.5512 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4496 - accuracy: 0.7783 - val_loss: 0.5525 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4432 - accuracy: 0.7811 - val_loss: 0.5634 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4388 - accuracy: 0.7823 - val_loss: 0.5641 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 22/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4340 - accuracy: 0.7873
Epoch 22: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4334 - accuracy: 0.7872 - val_loss: 0.5705 - val_accuracy: 0.7173 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.42211719455120567
Confusion Matrix :
 [[3009 1314]
 [1185 3138]]
Accuracy on test set:    0.7109646079111728
Sensitivity:    0.7258848022206801 	 Specificity:    0.6960444136016655
Precision  : 0.7048517520215634
Area Under Curve:    0.7109646079111728
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6078 - accuracy: 0.6643 - val_loss: 0.5724 - val_accuracy: 0.7021 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5595 - accuracy: 0.7124 - val_loss: 0.5556 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7210 - val_loss: 0.5467 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7294 - val_loss: 0.5456 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7347 - val_loss: 0.5557 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5197 - accuracy: 0.7372 - val_loss: 0.5404 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7414 - val_loss: 0.5434 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7460 - val_loss: 0.5355 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7487 - val_loss: 0.5415 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7531 - val_loss: 0.5387 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4936 - accuracy: 0.7544 - val_loss: 0.5412 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4891 - accuracy: 0.7570 - val_loss: 0.5440 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 13/400
263/274 [===========================>..] - ETA: 0s - loss: 0.4812 - accuracy: 0.7611
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4817 - accuracy: 0.7609 - val_loss: 0.5428 - val_accuracy: 0.7256 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.44114806738713963
Confusion Matrix :
 [[3013 1310]
 [1108 3215]]
Accuracy on test set:    0.7203331020124913
Sensitivity:    0.7436965070552857 	 Specificity:    0.696969696969697
Precision  : 0.7104972375690608
Area Under Curve:    0.7203331020124913
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6057 - accuracy: 0.6674 - val_loss: 0.5687 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5582 - accuracy: 0.7125 - val_loss: 0.5566 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7223 - val_loss: 0.5550 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7312 - val_loss: 0.5463 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7336 - val_loss: 0.5447 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5179 - accuracy: 0.7398 - val_loss: 0.5406 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7418 - val_loss: 0.5444 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7485 - val_loss: 0.5483 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4991 - accuracy: 0.7514 - val_loss: 0.5460 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4929 - accuracy: 0.7536 - val_loss: 0.5428 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7578 - val_loss: 0.5450 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7632 - val_loss: 0.5454 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4762 - accuracy: 0.7647 - val_loss: 0.5467 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4693 - accuracy: 0.7706 - val_loss: 0.5510 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4655 - accuracy: 0.7720 - val_loss: 0.5521 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4602 - accuracy: 0.7735 - val_loss: 0.5591 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 17/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4524 - accuracy: 0.7792
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4527 - accuracy: 0.7792 - val_loss: 0.5592 - val_accuracy: 0.7191 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.4290739367818238
Confusion Matrix :
 [[2739 1584]
 [ 907 3416]]
Accuracy on test set:    0.7118898912792042
Sensitivity:    0.7901919962988665 	 Specificity:    0.6335877862595419
Precision  : 0.6832
Area Under Curve:    0.7118898912792043
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6022 - accuracy: 0.6726 - val_loss: 0.5711 - val_accuracy: 0.6965 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7145 - val_loss: 0.5520 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7225 - val_loss: 0.5460 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7289 - val_loss: 0.5452 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7344 - val_loss: 0.5390 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5194 - accuracy: 0.7395 - val_loss: 0.5373 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5120 - accuracy: 0.7416 - val_loss: 0.5406 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5083 - accuracy: 0.7467 - val_loss: 0.5464 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5038 - accuracy: 0.7497 - val_loss: 0.5385 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4975 - accuracy: 0.7534 - val_loss: 0.5388 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4916 - accuracy: 0.7584 - val_loss: 0.5380 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4858 - accuracy: 0.7604 - val_loss: 0.5450 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4817 - accuracy: 0.7632 - val_loss: 0.5473 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4760 - accuracy: 0.7653
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7649 - val_loss: 0.5491 - val_accuracy: 0.7212 - lr: 0.0010
271/271 [==============================] - 0s 655us/step
Independent Testing Matthews Correlation:  0.4286747625188377
Confusion Matrix :
 [[3164 1159]
 [1312 3011]]
Accuracy on test set:    0.7142030996992829
Sensitivity:    0.6965070552856812 	 Specificity:    0.7318991441128846
Precision  : 0.722062350119904
Area Under Curve:    0.714203099699283
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6017 - accuracy: 0.6726 - val_loss: 0.5609 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7146 - val_loss: 0.5502 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7237 - val_loss: 0.5410 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7308 - val_loss: 0.5395 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7351 - val_loss: 0.5352 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7399 - val_loss: 0.5369 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5079 - accuracy: 0.7471 - val_loss: 0.5349 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7497 - val_loss: 0.5329 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4959 - accuracy: 0.7517 - val_loss: 0.5410 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4909 - accuracy: 0.7557 - val_loss: 0.5375 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4851 - accuracy: 0.7595 - val_loss: 0.5390 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4797 - accuracy: 0.7638 - val_loss: 0.5362 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4730 - accuracy: 0.7656 - val_loss: 0.5403 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7709 - val_loss: 0.5460 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4601 - accuracy: 0.7732 - val_loss: 0.5544 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4580 - accuracy: 0.7769 - val_loss: 0.5484 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 17/400
259/274 [===========================>..] - ETA: 0s - loss: 0.4495 - accuracy: 0.7814
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4497 - accuracy: 0.7815 - val_loss: 0.5566 - val_accuracy: 0.7183 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.44209978207936285
Confusion Matrix :
 [[3193 1130]
 [1283 3040]]
Accuracy on test set:    0.720911404117511
Sensitivity:    0.7032153597039094 	 Specificity:    0.7386074485311126
Precision  : 0.7290167865707434
Area Under Curve:    0.7209114041175111
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6202 - accuracy: 0.6559 - val_loss: 0.5649 - val_accuracy: 0.7034 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5612 - accuracy: 0.7100 - val_loss: 0.5491 - val_accuracy: 0.7151 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7219 - val_loss: 0.5529 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7277 - val_loss: 0.5414 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5249 - accuracy: 0.7357 - val_loss: 0.5361 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7416 - val_loss: 0.5380 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7453 - val_loss: 0.5403 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5050 - accuracy: 0.7473 - val_loss: 0.5382 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4987 - accuracy: 0.7529 - val_loss: 0.5374 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 10/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4906 - accuracy: 0.7568
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4907 - accuracy: 0.7569 - val_loss: 0.5407 - val_accuracy: 0.7173 - lr: 0.0010
271/271 [==============================] - 0s 640us/step
Independent Testing Matthews Correlation:  0.43735628870426174
Confusion Matrix :
 [[2970 1353]
 [1083 3240]]
Accuracy on test set:    0.7182512144344205
Sensitivity:    0.7494795281054824 	 Specificity:    0.6870229007633588
Precision  : 0.705421293272371
Area Under Curve:    0.7182512144344206
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6049 - accuracy: 0.6662 - val_loss: 0.5657 - val_accuracy: 0.7003 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5562 - accuracy: 0.7147 - val_loss: 0.5503 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7238 - val_loss: 0.5471 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7300 - val_loss: 0.5394 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5248 - accuracy: 0.7353 - val_loss: 0.5400 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7426 - val_loss: 0.5405 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5106 - accuracy: 0.7455 - val_loss: 0.5417 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7518 - val_loss: 0.5401 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4965 - accuracy: 0.7526 - val_loss: 0.5414 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4927 - accuracy: 0.7569 - val_loss: 0.5421 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4849 - accuracy: 0.7614 - val_loss: 0.5461 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4784 - accuracy: 0.7659 - val_loss: 0.5548 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 13/400
265/274 [============================>.] - ETA: 0s - loss: 0.4707 - accuracy: 0.7711
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4712 - accuracy: 0.7707 - val_loss: 0.5481 - val_accuracy: 0.7223 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.44462493691948607
Confusion Matrix :
 [[3099 1224]
 [1177 3146]]
Accuracy on test set:    0.7222993291695582
Sensitivity:    0.727735368956743 	 Specificity:    0.7168632893823733
Precision  : 0.7199084668192219
Area Under Curve:    0.7222993291695582
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6105 - accuracy: 0.6608 - val_loss: 0.5711 - val_accuracy: 0.7008 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7095 - val_loss: 0.5486 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7220 - val_loss: 0.5497 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7260 - val_loss: 0.5427 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7326 - val_loss: 0.5356 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5217 - accuracy: 0.7373 - val_loss: 0.5362 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7423 - val_loss: 0.5339 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5092 - accuracy: 0.7465 - val_loss: 0.5384 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7512 - val_loss: 0.5381 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4959 - accuracy: 0.7532 - val_loss: 0.5311 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4900 - accuracy: 0.7553 - val_loss: 0.5393 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4826 - accuracy: 0.7616 - val_loss: 0.5398 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4777 - accuracy: 0.7627 - val_loss: 0.5385 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4702 - accuracy: 0.7683 - val_loss: 0.5440 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4655 - accuracy: 0.7700
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4657 - accuracy: 0.7702 - val_loss: 0.5425 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.45130817021889424
Confusion Matrix :
 [[3142 1181]
 [1191 3132]]
Accuracy on test set:    0.7256534813786722
Sensitivity:    0.7244968771686329 	 Specificity:    0.7268100855887115
Precision  : 0.7261766751680965
Area Under Curve:    0.7256534813786721
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6042 - accuracy: 0.6707 - val_loss: 0.5624 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7134 - val_loss: 0.5518 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7217 - val_loss: 0.5460 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7278 - val_loss: 0.5463 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5269 - accuracy: 0.7354 - val_loss: 0.5426 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5192 - accuracy: 0.7393 - val_loss: 0.5434 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5129 - accuracy: 0.7436 - val_loss: 0.5414 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7464 - val_loss: 0.5361 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5004 - accuracy: 0.7502 - val_loss: 0.5416 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7537 - val_loss: 0.5382 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7582 - val_loss: 0.5429 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4817 - accuracy: 0.7607 - val_loss: 0.5449 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4787 - accuracy: 0.7636 - val_loss: 0.5462 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4719 - accuracy: 0.7657 - val_loss: 0.5527 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 15/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4657 - accuracy: 0.7706
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4660 - accuracy: 0.7705 - val_loss: 0.5482 - val_accuracy: 0.7237 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.45692517149059475
Confusion Matrix :
 [[3331  992]
 [1363 2960]]
Accuracy on test set:    0.7276197085357391
Sensitivity:    0.6847096923432802 	 Specificity:    0.770529724728198
Precision  : 0.7489878542510121
Area Under Curve:    0.7276197085357392
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6185 - accuracy: 0.6597 - val_loss: 0.5717 - val_accuracy: 0.7001 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5686 - accuracy: 0.7042 - val_loss: 0.5706 - val_accuracy: 0.6943 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5525 - accuracy: 0.7173 - val_loss: 0.5503 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7249 - val_loss: 0.5544 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7302 - val_loss: 0.5423 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5249 - accuracy: 0.7335 - val_loss: 0.5378 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7385 - val_loss: 0.5431 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5120 - accuracy: 0.7426 - val_loss: 0.5444 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5062 - accuracy: 0.7475 - val_loss: 0.5413 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4988 - accuracy: 0.7511 - val_loss: 0.5459 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7553 - val_loss: 0.5460 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4878 - accuracy: 0.7573 - val_loss: 0.5479 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4827 - accuracy: 0.7606 - val_loss: 0.5560 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4752 - accuracy: 0.7652
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4759 - accuracy: 0.7649 - val_loss: 0.5547 - val_accuracy: 0.7177 - lr: 0.0010
271/271 [==============================] - 0s 662us/step
Independent Testing Matthews Correlation:  0.5123770358968994
Confusion Matrix :
 [[3264 1059]
 [1049 3274]]
Accuracy on test set:    0.7561878325237104
Sensitivity:    0.7573444367337497 	 Specificity:    0.7550312283136711
Precision  : 0.7555965843526425
Area Under Curve:    0.7561878325237105
(8646, 4352) (8646,)
Mean MCC = 0.4466 + 0.0241 and Mean AUC = 0.7228 + 0.0123
Mean Sensitivity = 0.7303 + 0.0298 and Mean Specificity = 0.7153 + 0.0371 and Mean Accuracy = 0.7228 + 0.0123
Mean Precision = 0.7206 + 0.0203





Seed   : 943007
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6055 - accuracy: 0.6665 - val_loss: 0.5676 - val_accuracy: 0.7026 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5551 - accuracy: 0.7156 - val_loss: 0.5503 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7245 - val_loss: 0.5417 - val_accuracy: 0.7177 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7316 - val_loss: 0.5372 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7364 - val_loss: 0.5378 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7440 - val_loss: 0.5421 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5105 - accuracy: 0.7441 - val_loss: 0.5324 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7503 - val_loss: 0.5346 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4967 - accuracy: 0.7535 - val_loss: 0.5408 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7543 - val_loss: 0.5347 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4869 - accuracy: 0.7588 - val_loss: 0.5417 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4824 - accuracy: 0.7612 - val_loss: 0.5388 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4736 - accuracy: 0.7681 - val_loss: 0.5400 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4684 - accuracy: 0.7697 - val_loss: 0.5443 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 15/400
260/274 [===========================>..] - ETA: 0s - loss: 0.4623 - accuracy: 0.7717
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4629 - accuracy: 0.7713 - val_loss: 0.5401 - val_accuracy: 0.7260 - lr: 0.0010
271/271 [==============================] - 0s 656us/step
Independent Testing Matthews Correlation:  0.4278604150177671
Confusion Matrix :
 [[2798 1525]
 [ 964 3359]]
Accuracy on test set:    0.7121212121212122
Sensitivity:    0.7770067083044182 	 Specificity:    0.647235715938006
Precision  : 0.6877559377559378
Area Under Curve:    0.7121212121212122
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6059 - accuracy: 0.6666 - val_loss: 0.5639 - val_accuracy: 0.7021 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5582 - accuracy: 0.7116 - val_loss: 0.5485 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7233 - val_loss: 0.5503 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5306 - accuracy: 0.7303 - val_loss: 0.5405 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5222 - accuracy: 0.7343 - val_loss: 0.5478 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7392 - val_loss: 0.5356 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7449 - val_loss: 0.5443 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7482 - val_loss: 0.5388 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7521 - val_loss: 0.5360 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4923 - accuracy: 0.7556 - val_loss: 0.5382 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7585 - val_loss: 0.5347 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4798 - accuracy: 0.7625 - val_loss: 0.5446 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4729 - accuracy: 0.7662 - val_loss: 0.5470 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4653 - accuracy: 0.7710 - val_loss: 0.5529 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4626 - accuracy: 0.7745
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4618 - accuracy: 0.7749 - val_loss: 0.5533 - val_accuracy: 0.7253 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.44965501756581316
Confusion Matrix :
 [[3038 1285]
 [1096 3227]]
Accuracy on test set:    0.7246125375896368
Sensitivity:    0.7464723571593801 	 Specificity:    0.7027527180198936
Precision  : 0.7152039007092199
Area Under Curve:    0.7246125375896368
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6204 - accuracy: 0.6552 - val_loss: 0.5721 - val_accuracy: 0.7041 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.7067 - val_loss: 0.5554 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5504 - accuracy: 0.7181 - val_loss: 0.5525 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7248 - val_loss: 0.5484 - val_accuracy: 0.7164 - lr: 0.0010

Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5307 - accuracy: 0.7299 - val_loss: 0.5444 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7369 - val_loss: 0.5436 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5190 - accuracy: 0.7389 - val_loss: 0.5384 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7425 - val_loss: 0.5402 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7487 - val_loss: 0.5357 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7509 - val_loss: 0.5443 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.7517 - val_loss: 0.5433 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4910 - accuracy: 0.7553 - val_loss: 0.5435 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4855 - accuracy: 0.7603 - val_loss: 0.5431 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4788 - accuracy: 0.7639 - val_loss: 0.5475 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7648 - val_loss: 0.5498 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4695 - accuracy: 0.7682 - val_loss: 0.5554 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4643 - accuracy: 0.7707 - val_loss: 0.5549 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4591 - accuracy: 0.7765 - val_loss: 0.5531 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 19/400
263/274 [===========================>..] - ETA: 0s - loss: 0.4541 - accuracy: 0.7780
Epoch 19: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4539 - accuracy: 0.7781 - val_loss: 0.5608 - val_accuracy: 0.7218 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.43525545743417743
Confusion Matrix :
 [[2836 1487]
 [ 968 3355]]
Accuracy on test set:    0.7160536664353458
Sensitivity:    0.7760814249363868 	 Specificity:    0.6560259079343049
Precision  : 0.6928954977282115
Area Under Curve:    0.716053666435346
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5998 - accuracy: 0.6738 - val_loss: 0.5659 - val_accuracy: 0.7030 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5555 - accuracy: 0.7162 - val_loss: 0.5510 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7245 - val_loss: 0.5565 - val_accuracy: 0.7114 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7296 - val_loss: 0.5457 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7373 - val_loss: 0.5422 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5194 - accuracy: 0.7368 - val_loss: 0.5399 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7451 - val_loss: 0.5422 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5040 - accuracy: 0.7504 - val_loss: 0.5419 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4960 - accuracy: 0.7530 - val_loss: 0.5487 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4939 - accuracy: 0.7546 - val_loss: 0.5421 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4887 - accuracy: 0.7574 - val_loss: 0.5387 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4785 - accuracy: 0.7643 - val_loss: 0.5462 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4776 - accuracy: 0.7653 - val_loss: 0.5473 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4710 - accuracy: 0.7666 - val_loss: 0.5481 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4653 - accuracy: 0.7708
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4656 - accuracy: 0.7708 - val_loss: 0.5596 - val_accuracy: 0.7244 - lr: 0.0010
271/271 [==============================] - 0s 653us/step
Independent Testing Matthews Correlation:  0.4353823602058772
Confusion Matrix :
 [[2777 1546]
 [ 915 3408]]
Accuracy on test set:    0.7153597039093222
Sensitivity:    0.7883414295628036 	 Specificity:    0.6423779782558409
Precision  : 0.6879289463060153
Area Under Curve:    0.7153597039093222
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6224 - accuracy: 0.6555 - val_loss: 0.5654 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.7090 - val_loss: 0.5488 - val_accuracy: 0.7169 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7196 - val_loss: 0.5410 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7272 - val_loss: 0.5412 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5295 - accuracy: 0.7320 - val_loss: 0.5393 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7362 - val_loss: 0.5414 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7402 - val_loss: 0.5356 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7440 - val_loss: 0.5354 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7516 - val_loss: 0.5326 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5014 - accuracy: 0.7492 - val_loss: 0.5350 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4949 - accuracy: 0.7534 - val_loss: 0.5348 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4863 - accuracy: 0.7583 - val_loss: 0.5401 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7623 - val_loss: 0.5373 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4748 - accuracy: 0.7671 - val_loss: 0.5435 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4683 - accuracy: 0.7699 - val_loss: 0.5506 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4616 - accuracy: 0.7736
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4615 - accuracy: 0.7738 - val_loss: 0.5442 - val_accuracy: 0.7271 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.45335953698484127
Confusion Matrix :
 [[3023 1300]
 [1066 3257]]
Accuracy on test set:    0.7263474439046959
Sensitivity:    0.753411982419616 	 Specificity:    0.6992829053897757
Precision  : 0.7147245995172262
Area Under Curve:    0.7263474439046959
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6080 - accuracy: 0.6665 - val_loss: 0.5646 - val_accuracy: 0.7029 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5593 - accuracy: 0.7125 - val_loss: 0.5468 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7241 - val_loss: 0.5495 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7321 - val_loss: 0.5391 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7371 - val_loss: 0.5387 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5189 - accuracy: 0.7379 - val_loss: 0.5385 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7433 - val_loss: 0.5418 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7485 - val_loss: 0.5374 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4974 - accuracy: 0.7525 - val_loss: 0.5482 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7563 - val_loss: 0.5422 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 11/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4860 - accuracy: 0.7588
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4864 - accuracy: 0.7586 - val_loss: 0.5406 - val_accuracy: 0.7219 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4313681403285691
Confusion Matrix :
 [[2954 1369]
 [1093 3230]]
Accuracy on test set:    0.7152440434883183
Sensitivity:    0.7471663196854037 	 Specificity:    0.683321767291233
Precision  : 0.7023265927375516
Area Under Curve:    0.7152440434883184
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6072 - accuracy: 0.6646 - val_loss: 0.5773 - val_accuracy: 0.6928 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7126 - val_loss: 0.5532 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7220 - val_loss: 0.5463 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7282 - val_loss: 0.5476 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5251 - accuracy: 0.7350 - val_loss: 0.5438 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5178 - accuracy: 0.7405 - val_loss: 0.5435 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5140 - accuracy: 0.7421 - val_loss: 0.5409 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7466 - val_loss: 0.5426 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7520 - val_loss: 0.5445 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7550 - val_loss: 0.5416 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7584 - val_loss: 0.5430 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4834 - accuracy: 0.7624 - val_loss: 0.5500 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4775 - accuracy: 0.7678
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4775 - accuracy: 0.7679 - val_loss: 0.5631 - val_accuracy: 0.7199 - lr: 0.0010
271/271 [==============================] - 0s 642us/step
Independent Testing Matthews Correlation:  0.45403597523324907
Confusion Matrix :
 [[2788 1535]
 [ 850 3473]]
Accuracy on test set:    0.7241498959056211
Sensitivity:    0.8033772842933148 	 Specificity:    0.6449225075179273
Precision  : 0.6934904153354633
Area Under Curve:    0.7241498959056211
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5994 - accuracy: 0.6733 - val_loss: 0.5673 - val_accuracy: 0.6998 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5559 - accuracy: 0.7143 - val_loss: 0.5534 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7249 - val_loss: 0.5444 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7303 - val_loss: 0.5430 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5231 - accuracy: 0.7360 - val_loss: 0.5404 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7385 - val_loss: 0.5386 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5111 - accuracy: 0.7431 - val_loss: 0.5398 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7476 - val_loss: 0.5407 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4982 - accuracy: 0.7530 - val_loss: 0.5429 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4922 - accuracy: 0.7567 - val_loss: 0.5474 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4869 - accuracy: 0.7597
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7594 - val_loss: 0.5434 - val_accuracy: 0.7204 - lr: 0.0010
271/271 [==============================] - 0s 637us/step
Independent Testing Matthews Correlation:  0.44888832403782375
Confusion Matrix :
 [[2816 1507]
 [ 895 3428]]
Accuracy on test set:    0.7221836687485542
Sensitivity:    0.7929678464029609 	 Specificity:    0.6513994910941476
Precision  : 0.6946301925025329
Area Under Curve:    0.7221836687485543
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6081 - accuracy: 0.6634 - val_loss: 0.5713 - val_accuracy: 0.6935 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5637 - accuracy: 0.7092 - val_loss: 0.5590 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5500 - accuracy: 0.7188 - val_loss: 0.5547 - val_accuracy: 0.7128 - lr: 0.0010

Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7262 - val_loss: 0.5497 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7292 - val_loss: 0.5515 - val_accuracy: 0.7129 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5286 - accuracy: 0.7334 - val_loss: 0.5469 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5212 - accuracy: 0.7357 - val_loss: 0.5461 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7374 - val_loss: 0.5450 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5127 - accuracy: 0.7438 - val_loss: 0.5465 - val_accuracy: 0.7158 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7480 - val_loss: 0.5455 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7502 - val_loss: 0.5511 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4980 - accuracy: 0.7514 - val_loss: 0.5446 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4947 - accuracy: 0.7531
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4948 - accuracy: 0.7532 - val_loss: 0.5441 - val_accuracy: 0.7200 - lr: 0.0010
271/271 [==============================] - 0s 649us/step
Independent Testing Matthews Correlation:  0.46582537052225426
Confusion Matrix :
 [[3342  981]
 [1335 2988]]
Accuracy on test set:    0.7321304649548924
Sensitivity:    0.6911866759195003 	 Specificity:    0.7730742539902845
Precision  : 0.7528344671201814
Area Under Curve:    0.7321304649548924
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6166 - accuracy: 0.6595 - val_loss: 0.5696 - val_accuracy: 0.7011 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5652 - accuracy: 0.7081 - val_loss: 0.5660 - val_accuracy: 0.7092 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5510 - accuracy: 0.7188 - val_loss: 0.5515 - val_accuracy: 0.7147 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7245 - val_loss: 0.5478 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7313 - val_loss: 0.5466 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5265 - accuracy: 0.7354 - val_loss: 0.5471 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5211 - accuracy: 0.7402 - val_loss: 0.5602 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5150 - accuracy: 0.7420 - val_loss: 0.5488 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5091 - accuracy: 0.7452 - val_loss: 0.5429 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7475 - val_loss: 0.5522 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4989 - accuracy: 0.7517 - val_loss: 0.5484 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4919 - accuracy: 0.7555 - val_loss: 0.5488 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4875 - accuracy: 0.7578 - val_loss: 0.5537 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4830 - accuracy: 0.7617 - val_loss: 0.5520 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7616 - val_loss: 0.5593 - val_accuracy: 0.7125 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4727 - accuracy: 0.7655 - val_loss: 0.5612 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4645 - accuracy: 0.7729
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4649 - accuracy: 0.7727 - val_loss: 0.5639 - val_accuracy: 0.7203 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.5024560917444711
Confusion Matrix :
 [[3270 1053]
 [1098 3225]]
Accuracy on test set:    0.7512144344205413
Sensitivity:    0.7460097154753643 	 Specificity:    0.7564191533657183
Precision  : 0.7538569424964937
Area Under Curve:    0.7512144344205414
(8646, 4352) (8646,)
Mean MCC = 0.4504 + 0.0207 and Mean AUC = 0.7239 + 0.0108
Mean Sensitivity = 0.7622 + 0.0310 and Mean Specificity = 0.6857 + 0.0449 and Mean Accuracy = 0.7239 + 0.0108
Mean Precision = 0.7096 + 0.0238





Seed   : 528012
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6117 - accuracy: 0.6652 - val_loss: 0.5657 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5584 - accuracy: 0.7129 - val_loss: 0.5524 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7225 - val_loss: 0.5409 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5317 - accuracy: 0.7322 - val_loss: 0.5385 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5240 - accuracy: 0.7363 - val_loss: 0.5348 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5186 - accuracy: 0.7392 - val_loss: 0.5332 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7440 - val_loss: 0.5308 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5035 - accuracy: 0.7486 - val_loss: 0.5286 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4956 - accuracy: 0.7531 - val_loss: 0.5245 - val_accuracy: 0.7317 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4894 - accuracy: 0.7575 - val_loss: 0.5368 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4845 - accuracy: 0.7602 - val_loss: 0.5347 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4775 - accuracy: 0.7648 - val_loss: 0.5430 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4722 - accuracy: 0.7666 - val_loss: 0.5355 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4645 - accuracy: 0.7722
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4649 - accuracy: 0.7720 - val_loss: 0.5364 - val_accuracy: 0.7272 - lr: 0.0010
271/271 [==============================] - 0s 654us/step
Independent Testing Matthews Correlation:  0.4362023167721567
Confusion Matrix :
 [[3045 1278]
 [1160 3163]]
Accuracy on test set:    0.7180198935924127
Sensitivity:    0.7316678232708768 	 Specificity:    0.7043719639139486
Precision  : 0.7122269759063274
Area Under Curve:    0.7180198935924127
(8646, 4352) (8646,)

Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6157 - accuracy: 0.6554 - val_loss: 0.5755 - val_accuracy: 0.7006 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5623 - accuracy: 0.7084 - val_loss: 0.5539 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7218 - val_loss: 0.5481 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7280 - val_loss: 0.5422 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7334 - val_loss: 0.5383 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5209 - accuracy: 0.7379 - val_loss: 0.5360 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7410 - val_loss: 0.5405 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7456 - val_loss: 0.5382 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5018 - accuracy: 0.7494 - val_loss: 0.5366 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4963 - accuracy: 0.7532 - val_loss: 0.5343 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7569 - val_loss: 0.5453 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4839 - accuracy: 0.7595 - val_loss: 0.5389 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4779 - accuracy: 0.7647 - val_loss: 0.5412 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4722 - accuracy: 0.7671 - val_loss: 0.5451 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4678 - accuracy: 0.7712
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4677 - accuracy: 0.7716 - val_loss: 0.5428 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 651us/step
Independent Testing Matthews Correlation:  0.45254222268054023
Confusion Matrix :
 [[2773 1550]
 [ 843 3480]]
Accuracy on test set:    0.7232246125375896
Sensitivity:    0.8049965301873698 	 Specificity:    0.6414526948878094
Precision  : 0.6918489065606361
Area Under Curve:    0.7232246125375896
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6019 - accuracy: 0.6695 - val_loss: 0.5693 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5577 - accuracy: 0.7114 - val_loss: 0.5568 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7244 - val_loss: 0.5465 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7314 - val_loss: 0.5457 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5229 - accuracy: 0.7374 - val_loss: 0.5402 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7404 - val_loss: 0.5451 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7468 - val_loss: 0.5470 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7475 - val_loss: 0.5435 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4937 - accuracy: 0.7559 - val_loss: 0.5399 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4881 - accuracy: 0.7610 - val_loss: 0.5407 - val_accuracy: 0.7287 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4823 - accuracy: 0.7614 - val_loss: 0.5427 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4736 - accuracy: 0.7682 - val_loss: 0.5471 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7726 - val_loss: 0.5504 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4666 - accuracy: 0.7717 - val_loss: 0.5417 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4564 - accuracy: 0.7779 - val_loss: 0.5511 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4493 - accuracy: 0.7823 - val_loss: 0.5548 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 17/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4423 - accuracy: 0.7871 - val_loss: 0.5621 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 18/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4389 - accuracy: 0.7890 - val_loss: 0.5665 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 19/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4341 - accuracy: 0.7907 - val_loss: 0.5684 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 20/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4310 - accuracy: 0.7920 - val_loss: 0.5729 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 21/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4225 - accuracy: 0.7976 - val_loss: 0.5690 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 22/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4163 - accuracy: 0.8010
Epoch 22: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4163 - accuracy: 0.8010 - val_loss: 0.5847 - val_accuracy: 0.7230 - lr: 0.0010
271/271 [==============================] - 1s 654us/step
Independent Testing Matthews Correlation:  0.43499726399593525
Confusion Matrix :
 [[3052 1271]
 [1172 3151]]
Accuracy on test set:    0.7174415914873931
Sensitivity:    0.7288919731667823 	 Specificity:    0.7059912098080037
Precision  : 0.7125734961555857
Area Under Curve:    0.717441591487393
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6125 - accuracy: 0.6609 - val_loss: 0.5717 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5590 - accuracy: 0.7116 - val_loss: 0.5513 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7231 - val_loss: 0.5490 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7295 - val_loss: 0.5440 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7332 - val_loss: 0.5415 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5168 - accuracy: 0.7401 - val_loss: 0.5431 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7413 - val_loss: 0.5476 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5030 - accuracy: 0.7470 - val_loss: 0.5402 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4983 - accuracy: 0.7521 - val_loss: 0.5379 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4944 - accuracy: 0.7511 - val_loss: 0.5506 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7578 - val_loss: 0.5413 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4819 - accuracy: 0.7600 - val_loss: 0.5442 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4750 - accuracy: 0.7636 - val_loss: 0.5476 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 14/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4667 - accuracy: 0.7685
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4672 - accuracy: 0.7685 - val_loss: 0.5462 - val_accuracy: 0.7292 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.4246112273535366
Confusion Matrix :
 [[3024 1299]
 [1189 3134]]
Accuracy on test set:    0.712236872542216
Sensitivity:    0.7249595188526486 	 Specificity:    0.6995142262317835
Precision  : 0.7069704489059327
Area Under Curve:    0.712236872542216
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6025 - accuracy: 0.6708 - val_loss: 0.5645 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7143 - val_loss: 0.5477 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7232 - val_loss: 0.5415 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7301 - val_loss: 0.5410 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5230 - accuracy: 0.7370 - val_loss: 0.5388 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7425 - val_loss: 0.5380 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7458 - val_loss: 0.5380 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5010 - accuracy: 0.7503 - val_loss: 0.5347 - val_accuracy: 0.7313 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4945 - accuracy: 0.7548 - val_loss: 0.5393 - val_accuracy: 0.7355 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7578 - val_loss: 0.5354 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4813 - accuracy: 0.7630 - val_loss: 0.5409 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4747 - accuracy: 0.7658 - val_loss: 0.5459 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4736 - accuracy: 0.7659 - val_loss: 0.5515 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 14/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4627 - accuracy: 0.7719
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4628 - accuracy: 0.7721 - val_loss: 0.5497 - val_accuracy: 0.7321 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4263460018636793
Confusion Matrix :
 [[2979 1344]
 [1138 3185]]
Accuracy on test set:    0.7129308350682396
Sensitivity:    0.7367568817950497 	 Specificity:    0.6891047883414295
Precision  : 0.7032457496136012
Area Under Curve:    0.7129308350682396
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6027 - accuracy: 0.6699 - val_loss: 0.5628 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5573 - accuracy: 0.7116 - val_loss: 0.5486 - val_accuracy: 0.7203 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7245 - val_loss: 0.5412 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7313 - val_loss: 0.5402 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7367 - val_loss: 0.5391 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5142 - accuracy: 0.7433 - val_loss: 0.5368 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7468 - val_loss: 0.5396 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7501 - val_loss: 0.5361 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.7550 - val_loss: 0.5434 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4872 - accuracy: 0.7596 - val_loss: 0.5347 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4828 - accuracy: 0.7616 - val_loss: 0.5403 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.7658 - val_loss: 0.5409 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4691 - accuracy: 0.7707 - val_loss: 0.5447 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4623 - accuracy: 0.7743 - val_loss: 0.5426 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4564 - accuracy: 0.7784 - val_loss: 0.5529 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4511 - accuracy: 0.7786
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4509 - accuracy: 0.7787 - val_loss: 0.5525 - val_accuracy: 0.7253 - lr: 0.0010
271/271 [==============================] - 0s 641us/step
Independent Testing Matthews Correlation:  0.43810720682543514
Confusion Matrix :
 [[3040 1283]
 [1147 3176]]
Accuracy on test set:    0.7189451769604441
Sensitivity:    0.7346749942169789 	 Specificity:    0.7032153597039094
Precision  : 0.7122673245122225
Area Under Curve:    0.7189451769604441
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6293 - accuracy: 0.6486 - val_loss: 0.5702 - val_accuracy: 0.7066 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5660 - accuracy: 0.7061 - val_loss: 0.5649 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5487 - accuracy: 0.7209 - val_loss: 0.5480 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7274 - val_loss: 0.5470 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7290 - val_loss: 0.5430 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7350 - val_loss: 0.5453 - val_accuracy: 0.7122 - lr: 0.0010
Epoch 7/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5193 - accuracy: 0.7402 - val_loss: 0.5392 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 8/400
261/274 [===========================>..] - ETA: 0s - loss: 0.5132 - accuracy: 0.7423
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7421 - val_loss: 0.5447 - val_accuracy: 0.7221 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.44801972656948746
Confusion Matrix :
 [[3294 1029]
 [1363 2960]]
Accuracy on test set:    0.7233402729585936
Sensitivity:    0.6847096923432802 	 Specificity:    0.761970853573907
Precision  : 0.7420406116821259
Area Under Curve:    0.7233402729585937
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.5990 - accuracy: 0.6729 - val_loss: 0.5750 - val_accuracy: 0.7048 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7113 - val_loss: 0.5471 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7237 - val_loss: 0.5418 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7317 - val_loss: 0.5411 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7360 - val_loss: 0.5344 - val_accuracy: 0.7258 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5174 - accuracy: 0.7399 - val_loss: 0.5358 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5131 - accuracy: 0.7419 - val_loss: 0.5355 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7473 - val_loss: 0.5413 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5001 - accuracy: 0.7509 - val_loss: 0.5369 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4934 - accuracy: 0.7569 - val_loss: 0.5326 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4863 - accuracy: 0.7603
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4869 - accuracy: 0.7594 - val_loss: 0.5366 - val_accuracy: 0.7287 - lr: 0.0010
271/271 [==============================] - 0s 647us/step
Independent Testing Matthews Correlation:  0.4593084847713956
Confusion Matrix :
 [[3067 1256]
 [1083 3240]]
Accuracy on test set:    0.729470275271802
Sensitivity:    0.7494795281054824 	 Specificity:    0.7094610224381217
Precision  : 0.7206405693950177
Area Under Curve:    0.7294702752718021
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6144 - accuracy: 0.6586 - val_loss: 0.5667 - val_accuracy: 0.7110 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5638 - accuracy: 0.7089 - val_loss: 0.5514 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7188 - val_loss: 0.5469 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7250 - val_loss: 0.5442 - val_accuracy: 0.7192 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5292 - accuracy: 0.7333 - val_loss: 0.5447 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7354 - val_loss: 0.5404 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5145 - accuracy: 0.7413 - val_loss: 0.5413 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.7428 - val_loss: 0.5409 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7486 - val_loss: 0.5445 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4931 - accuracy: 0.7552 - val_loss: 0.5475 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4862 - accuracy: 0.7594 - val_loss: 0.5541 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4813 - accuracy: 0.7641
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4815 - accuracy: 0.7641 - val_loss: 0.5464 - val_accuracy: 0.7230 - lr: 0.0010
271/271 [==============================] - 0s 663us/step
Independent Testing Matthews Correlation:  0.4585981793829488
Confusion Matrix :
 [[3103 1220]
 [1121 3202]]
Accuracy on test set:    0.7292389544297941
Sensitivity:    0.7406893361091834 	 Specificity:    0.7177885727504049
Precision  : 0.7241067390321122
Area Under Curve:    0.729238954429794
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6099 - accuracy: 0.6648 - val_loss: 0.5632 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5647 - accuracy: 0.7076 - val_loss: 0.5529 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5499 - accuracy: 0.7170 - val_loss: 0.5484 - val_accuracy: 0.7195 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7248 - val_loss: 0.5515 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7306 - val_loss: 0.5433 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7345 - val_loss: 0.5524 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5159 - accuracy: 0.7411 - val_loss: 0.5463 - val_accuracy: 0.7199 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7421 - val_loss: 0.5493 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7465 - val_loss: 0.5429 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
262/274 [===========================>..] - ETA: 0s - loss: 0.5013 - accuracy: 0.7511
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.5015 - accuracy: 0.7509 - val_loss: 0.5473 - val_accuracy: 0.7204 - lr: 0.0010
271/271 [==============================] - 0s 652us/step
Independent Testing Matthews Correlation:  0.501654378374644
Confusion Matrix :
 [[3102 1221]
 [ 938 3385]]
Accuracy on test set:    0.7502891510525098
Sensitivity:    0.7830210501966227 	 Specificity:    0.7175572519083969
Precision  : 0.7349109856708641
Area Under Curve:    0.7502891510525098
(8646, 4352) (8646,)
Mean MCC = 0.4480 + 0.0214 and Mean AUC = 0.7235 + 0.0105
Mean Sensitivity = 0.7420 + 0.0311 and Mean Specificity = 0.7050 + 0.0281 and Mean Accuracy = 0.7235 + 0.0105
Mean Precision = 0.7161 + 0.0141





Seed   : 716232
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6125 - accuracy: 0.6613 - val_loss: 0.5617 - val_accuracy: 0.7096 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7115 - val_loss: 0.5459 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7237 - val_loss: 0.5381 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7312 - val_loss: 0.5373 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5222 - accuracy: 0.7379 - val_loss: 0.5366 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7387 - val_loss: 0.5324 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5078 - accuracy: 0.7468 - val_loss: 0.5350 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5002 - accuracy: 0.7512 - val_loss: 0.5310 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4949 - accuracy: 0.7546 - val_loss: 0.5383 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4889 - accuracy: 0.7591 - val_loss: 0.5301 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4805 - accuracy: 0.7628 - val_loss: 0.5434 - val_accuracy: 0.7247 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4748 - accuracy: 0.7665 - val_loss: 0.5422 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4681 - accuracy: 0.7713 - val_loss: 0.5393 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 14/400
263/274 [===========================>..] - ETA: 0s - loss: 0.4604 - accuracy: 0.7744
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4608 - accuracy: 0.7744 - val_loss: 0.5431 - val_accuracy: 0.7232 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.4138374152084935
Confusion Matrix :
 [[3066 1257]
 [1277 3046]]
Accuracy on test set:    0.7069164931760351
Sensitivity:    0.7046032847559565 	 Specificity:    0.7092297015961138
Precision  : 0.7078782244945387
Area Under Curve:    0.7069164931760351
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6092 - accuracy: 0.6645 - val_loss: 0.5655 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7114 - val_loss: 0.5452 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7207 - val_loss: 0.5408 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7282 - val_loss: 0.5361 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7337 - val_loss: 0.5390 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5220 - accuracy: 0.7382 - val_loss: 0.5351 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5137 - accuracy: 0.7427 - val_loss: 0.5307 - val_accuracy: 0.7298 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7449 - val_loss: 0.5330 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7494 - val_loss: 0.5349 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5019 - accuracy: 0.7508 - val_loss: 0.5350 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4942 - accuracy: 0.7557 - val_loss: 0.5332 - val_accuracy: 0.7330 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4901 - accuracy: 0.7576 - val_loss: 0.5324 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4839 - accuracy: 0.7609 - val_loss: 0.5381 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4815 - accuracy: 0.7621 - val_loss: 0.5530 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7654 - val_loss: 0.5385 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4705 - accuracy: 0.7673
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7677 - val_loss: 0.5439 - val_accuracy: 0.7245 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4368363386834867
Confusion Matrix :
 [[2939 1384]
 [1056 3267]]
Accuracy on test set:    0.7177885727504049
Sensitivity:    0.7557251908396947 	 Specificity:    0.6798519546611149
Precision  : 0.7024295850354763
Area Under Curve:    0.717788572750405
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6079 - accuracy: 0.6687 - val_loss: 0.5621 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7107 - val_loss: 0.5478 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7250 - val_loss: 0.5412 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7309 - val_loss: 0.5392 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5258 - accuracy: 0.7348 - val_loss: 0.5331 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7414 - val_loss: 0.5376 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.7483 - val_loss: 0.5323 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5006 - accuracy: 0.7513 - val_loss: 0.5438 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7555 - val_loss: 0.5345 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 10/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4851 - accuracy: 0.7625
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4853 - accuracy: 0.7623 - val_loss: 0.5418 - val_accuracy: 0.7240 - lr: 0.0010
271/271 [==============================] - 0s 644us/step
Independent Testing Matthews Correlation:  0.44036461999722204
Confusion Matrix :
 [[2997 1326]
 [1096 3227]]
Accuracy on test set:    0.7198704603284756
Sensitivity:    0.7464723571593801 	 Specificity:    0.6932685634975712
Precision  : 0.7087634526685702
Area Under Curve:    0.7198704603284757
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.5969 - accuracy: 0.6750 - val_loss: 0.5647 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5548 - accuracy: 0.7142 - val_loss: 0.5466 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7247 - val_loss: 0.5430 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7315 - val_loss: 0.5394 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5226 - accuracy: 0.7370 - val_loss: 0.5387 - val_accuracy: 0.7221 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7410 - val_loss: 0.5403 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7431 - val_loss: 0.5358 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5039 - accuracy: 0.7477 - val_loss: 0.5394 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4997 - accuracy: 0.7508 - val_loss: 0.5401 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4959 - accuracy: 0.7524 - val_loss: 0.5358 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7570 - val_loss: 0.5353 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4837 - accuracy: 0.7603 - val_loss: 0.5457 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4773 - accuracy: 0.7620 - val_loss: 0.5481 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4737 - accuracy: 0.7645 - val_loss: 0.5420 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4650 - accuracy: 0.7706 - val_loss: 0.5627 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 16/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4625 - accuracy: 0.7716
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4623 - accuracy: 0.7719 - val_loss: 0.5476 - val_accuracy: 0.7267 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.43732540838559014
Confusion Matrix :
 [[3054 1269]
 [1164 3159]]
Accuracy on test set:    0.7185981956974323
Sensitivity:    0.7307425399028452 	 Specificity:    0.7064538514920194
Precision  : 0.7134146341463414
Area Under Curve:    0.7185981956974323
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6082 - accuracy: 0.6635 - val_loss: 0.5656 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5617 - accuracy: 0.7088 - val_loss: 0.5465 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7220 - val_loss: 0.5457 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7294 - val_loss: 0.5361 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5275 - accuracy: 0.7333 - val_loss: 0.5345 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5189 - accuracy: 0.7385 - val_loss: 0.5336 - val_accuracy: 0.7265 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5123 - accuracy: 0.7432 - val_loss: 0.5316 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7450 - val_loss: 0.5340 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5011 - accuracy: 0.7522 - val_loss: 0.5369 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 10/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4971 - accuracy: 0.7521
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4971 - accuracy: 0.7521 - val_loss: 0.5357 - val_accuracy: 0.7276 - lr: 0.0010
271/271 [==============================] - 0s 637us/step
Independent Testing Matthews Correlation:  0.4438077507596825
Confusion Matrix :
 [[2987 1336]
 [1072 3251]]
Accuracy on test set:    0.7214897062225306
Sensitivity:    0.7520240573675688 	 Specificity:    0.6909553550774925
Precision  : 0.7087420972313059
Area Under Curve:    0.7214897062225307
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6081 - accuracy: 0.6643 - val_loss: 0.5611 - val_accuracy: 0.7023 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5594 - accuracy: 0.7104 - val_loss: 0.5522 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7191 - val_loss: 0.5425 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7303 - val_loss: 0.5396 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7366 - val_loss: 0.5403 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5183 - accuracy: 0.7400 - val_loss: 0.5386 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5105 - accuracy: 0.7438 - val_loss: 0.5335 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7466 - val_loss: 0.5353 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7507 - val_loss: 0.5371 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4926 - accuracy: 0.7538 - val_loss: 0.5357 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4881 - accuracy: 0.7577 - val_loss: 0.5436 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4807 - accuracy: 0.7638
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4814 - accuracy: 0.7634 - val_loss: 0.5424 - val_accuracy: 0.7194 - lr: 0.0010
271/271 [==============================] - 0s 659us/step
Independent Testing Matthews Correlation:  0.440985273684265
Confusion Matrix :
 [[2921 1402]
 [1022 3301]]
Accuracy on test set:    0.7196391394864677
Sensitivity:    0.7635900994679621 	 Specificity:    0.6756881795049734
Precision  : 0.7018924091005742
Area Under Curve:    0.7196391394864677
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6105 - accuracy: 0.6645 - val_loss: 0.5665 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7117 - val_loss: 0.5512 - val_accuracy: 0.7155 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7250 - val_loss: 0.5484 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7303 - val_loss: 0.5430 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7358 - val_loss: 0.5393 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7407 - val_loss: 0.5432 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5096 - accuracy: 0.7471 - val_loss: 0.5381 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5034 - accuracy: 0.7480 - val_loss: 0.5375 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.7532 - val_loss: 0.5390 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7566 - val_loss: 0.5416 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4860 - accuracy: 0.7617 - val_loss: 0.5384 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4789 - accuracy: 0.7624 - val_loss: 0.5423 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 13/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4717 - accuracy: 0.7675
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4717 - accuracy: 0.7677 - val_loss: 0.5455 - val_accuracy: 0.7264 - lr: 0.0010
271/271 [==============================] - 0s 677us/step
Independent Testing Matthews Correlation:  0.44738198947806584
Confusion Matrix :
 [[3141 1182]
 [1207 3116]]
Accuracy on test set:    0.7236872542216054
Sensitivity:    0.720795743696507 	 Specificity:    0.7265787647467037
Precision  : 0.7249883666821778
Area Under Curve:    0.7236872542216053
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 4ms/step - loss: 0.6125 - accuracy: 0.6590 - val_loss: 0.5626 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5620 - accuracy: 0.7097 - val_loss: 0.5540 - val_accuracy: 0.7107 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5492 - accuracy: 0.7191 - val_loss: 0.5444 - val_accuracy: 0.7173 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7291 - val_loss: 0.5420 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7313 - val_loss: 0.5414 - val_accuracy: 0.7232 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5259 - accuracy: 0.7360 - val_loss: 0.5373 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5177 - accuracy: 0.7412 - val_loss: 0.5407 - val_accuracy: 0.7236 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7442 - val_loss: 0.5378 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5059 - accuracy: 0.7485 - val_loss: 0.5355 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4986 - accuracy: 0.7515 - val_loss: 0.5354 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4943 - accuracy: 0.7557 - val_loss: 0.5419 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4864 - accuracy: 0.7586 - val_loss: 0.5370 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4819 - accuracy: 0.7600 - val_loss: 0.5421 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4763 - accuracy: 0.7645 - val_loss: 0.5444 - val_accuracy: 0.7188 - lr: 0.0010
Epoch 15/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4744 - accuracy: 0.7656
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4747 - accuracy: 0.7655 - val_loss: 0.5430 - val_accuracy: 0.7250 - lr: 0.0010
271/271 [==============================] - 0s 660us/step
Independent Testing Matthews Correlation:  0.4598811267507927
Confusion Matrix :
 [[3034 1289]
 [1049 3274]]
Accuracy on test set:    0.7295859356928059
Sensitivity:    0.7573444367337497 	 Specificity:    0.7018274346518621
Precision  : 0.7175104098181021
Area Under Curve:    0.729585935692806
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6114 - accuracy: 0.6663 - val_loss: 0.5662 - val_accuracy: 0.7088 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5624 - accuracy: 0.7099 - val_loss: 0.5507 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7224 - val_loss: 0.5434 - val_accuracy: 0.7214 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7293 - val_loss: 0.5425 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7352 - val_loss: 0.5438 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5206 - accuracy: 0.7384 - val_loss: 0.5433 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5130 - accuracy: 0.7428 - val_loss: 0.5427 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5072 - accuracy: 0.7465 - val_loss: 0.5376 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5008 - accuracy: 0.7497 - val_loss: 0.5363 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4958 - accuracy: 0.7528 - val_loss: 0.5400 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4896 - accuracy: 0.7573 - val_loss: 0.5412 - val_accuracy: 0.7291 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4821 - accuracy: 0.7621 - val_loss: 0.5477 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4757 - accuracy: 0.7645 - val_loss: 0.5481 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7677 - val_loss: 0.5512 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4645 - accuracy: 0.7709 - val_loss: 0.5491 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 16/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4579 - accuracy: 0.7742
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4582 - accuracy: 0.7741 - val_loss: 0.5558 - val_accuracy: 0.7177 - lr: 0.0010
271/271 [==============================] - 0s 657us/step
Independent Testing Matthews Correlation:  0.4388647778831403
Confusion Matrix :
 [[3392  931]
 [1512 2811]]
Accuracy on test set:    0.7174415914873931
Sensitivity:    0.6502428868841083 	 Specificity:    0.7846402960906778
Precision  : 0.7512025654730091
Area Under Curve:    0.717441591487393
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6070 - accuracy: 0.6669 - val_loss: 0.5710 - val_accuracy: 0.7005 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5647 - accuracy: 0.7087 - val_loss: 0.5512 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5491 - accuracy: 0.7189 - val_loss: 0.5548 - val_accuracy: 0.7136 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7266 - val_loss: 0.5465 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7302 - val_loss: 0.5555 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5241 - accuracy: 0.7370 - val_loss: 0.5447 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400

274/274 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7390 - val_loss: 0.5441 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7433 - val_loss: 0.5527 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7474 - val_loss: 0.5485 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5008 - accuracy: 0.7498 - val_loss: 0.5434 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4959 - accuracy: 0.7533 - val_loss: 0.5505 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 12/400
253/274 [==========================>...] - ETA: 0s - loss: 0.4892 - accuracy: 0.7567
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4905 - accuracy: 0.7559 - val_loss: 0.5540 - val_accuracy: 0.7183 - lr: 0.0010
271/271 [==============================] - 0s 645us/step
Independent Testing Matthews Correlation:  0.520481574672778
Confusion Matrix :
 [[3155 1168]
 [ 909 3414]]
Accuracy on test set:    0.7597733055748322
Sensitivity:    0.7897293546148508 	 Specificity:    0.7298172565348138
Precision  : 0.7450894805761676
Area Under Curve:    0.7597733055748322
(8646, 4352) (8646,)
Mean MCC = 0.4480 + 0.0265 and Mean AUC = 0.7235 + 0.0132
Mean Sensitivity = 0.7371 + 0.0367 and Mean Specificity = 0.7098 + 0.0301 and Mean Accuracy = 0.7235 + 0.0132
Mean Precision = 0.7182 + 0.0164





Seed   : 503150
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6013 - accuracy: 0.6705 - val_loss: 0.5610 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7136 - val_loss: 0.5571 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7235 - val_loss: 0.5498 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7306 - val_loss: 0.5350 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5224 - accuracy: 0.7367 - val_loss: 0.5335 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5169 - accuracy: 0.7407 - val_loss: 0.5325 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7447 - val_loss: 0.5405 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5041 - accuracy: 0.7486 - val_loss: 0.5374 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4976 - accuracy: 0.7535 - val_loss: 0.5277 - val_accuracy: 0.7273 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4914 - accuracy: 0.7573 - val_loss: 0.5311 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4848 - accuracy: 0.7615 - val_loss: 0.5307 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4800 - accuracy: 0.7648 - val_loss: 0.5307 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4728 - accuracy: 0.7688 - val_loss: 0.5410 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4651 - accuracy: 0.7721 - val_loss: 0.5400 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4600 - accuracy: 0.7763 - val_loss: 0.5404 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 16/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4525 - accuracy: 0.7811 - val_loss: 0.5539 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 17/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4468 - accuracy: 0.7846
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4467 - accuracy: 0.7840 - val_loss: 0.5509 - val_accuracy: 0.7272 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.40512116117149394
Confusion Matrix :
 [[2952 1371]
 [1202 3121]]
Accuracy on test set:    0.7024057367568818
Sensitivity:    0.7219523479065464 	 Specificity:    0.6828591256072172
Precision  : 0.6947907390917186
Area Under Curve:    0.7024057367568817
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6088 - accuracy: 0.6665 - val_loss: 0.5628 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5589 - accuracy: 0.7121 - val_loss: 0.5547 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7226 - val_loss: 0.5464 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7327 - val_loss: 0.5379 - val_accuracy: 0.7217 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7363 - val_loss: 0.5392 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5176 - accuracy: 0.7402 - val_loss: 0.5345 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5096 - accuracy: 0.7472 - val_loss: 0.5368 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5033 - accuracy: 0.7495 - val_loss: 0.5351 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4961 - accuracy: 0.7549 - val_loss: 0.5384 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4898 - accuracy: 0.7566 - val_loss: 0.5343 - val_accuracy: 0.7210 - lr: 0.0010
Epoch 11/400
261/274 [===========================>..] - ETA: 0s - loss: 0.4841 - accuracy: 0.7597
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4843 - accuracy: 0.7596 - val_loss: 0.5373 - val_accuracy: 0.7228 - lr: 0.0010
271/271 [==============================] - 0s 661us/step
Independent Testing Matthews Correlation:  0.4265830363637516
Confusion Matrix :
 [[3108 1215]
 [1264 3059]]
Accuracy on test set:    0.7132778163312514
Sensitivity:    0.7076104557020587 	 Specificity:    0.7189451769604441
Precision  : 0.7157229761347683
Area Under Curve:    0.7132778163312514
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6170 - accuracy: 0.6605 - val_loss: 0.5674 - val_accuracy: 0.7037 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7102 - val_loss: 0.5506 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7216 - val_loss: 0.5407 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7302 - val_loss: 0.5387 - val_accuracy: 0.7206 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5261 - accuracy: 0.7338 - val_loss: 0.5404 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5207 - accuracy: 0.7361 - val_loss: 0.5344 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7422 - val_loss: 0.5385 - val_accuracy: 0.7258 - lr: 0.0010

Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5057 - accuracy: 0.7480 - val_loss: 0.5389 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4983 - accuracy: 0.7498 - val_loss: 0.5374 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4920 - accuracy: 0.7529 - val_loss: 0.5349 - val_accuracy: 0.7276 - lr: 0.0010
Epoch 11/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4872 - accuracy: 0.7572
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4873 - accuracy: 0.7575 - val_loss: 0.5389 - val_accuracy: 0.7263 - lr: 0.0010
271/271 [==============================] - 0s 648us/step
Independent Testing Matthews Correlation:  0.4289140389080842
Confusion Matrix :
 [[2869 1454]
 [1024 3299]]
Accuracy on test set:    0.7133934767522554
Sensitivity:    0.7631274577839463 	 Specificity:    0.6636594957205644
Precision  : 0.694087944456133
Area Under Curve:    0.7133934767522553
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 2s 3ms/step - loss: 0.6096 - accuracy: 0.6652 - val_loss: 0.5645 - val_accuracy: 0.7074 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5581 - accuracy: 0.7124 - val_loss: 0.5463 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7225 - val_loss: 0.5441 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7324 - val_loss: 0.5415 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7379 - val_loss: 0.5367 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7428 - val_loss: 0.5332 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5102 - accuracy: 0.7440 - val_loss: 0.5366 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5046 - accuracy: 0.7493 - val_loss: 0.5344 - val_accuracy: 0.7309 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4963 - accuracy: 0.7541 - val_loss: 0.5415 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4885 - accuracy: 0.7583 - val_loss: 0.5343 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4807 - accuracy: 0.7612 - val_loss: 0.5377 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4754 - accuracy: 0.7657 - val_loss: 0.5464 - val_accuracy: 0.7280 - lr: 0.0010
Epoch 13/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4696 - accuracy: 0.7697 - val_loss: 0.5429 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 14/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4614 - accuracy: 0.7740 - val_loss: 0.5444 - val_accuracy: 0.7262 - lr: 0.0010
Epoch 15/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4547 - accuracy: 0.7776 - val_loss: 0.5509 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 16/400
258/274 [===========================>..] - ETA: 0s - loss: 0.4493 - accuracy: 0.7813
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4497 - accuracy: 0.7811 - val_loss: 0.5580 - val_accuracy: 0.7238 - lr: 0.0010
271/271 [==============================] - 0s 643us/step
Independent Testing Matthews Correlation:  0.42772876195254267
Confusion Matrix :
 [[3067 1256]
 [1218 3105]]
Accuracy on test set:    0.7138561184362711
Sensitivity:    0.7182512144344205 	 Specificity:    0.7094610224381217
Precision  : 0.7119926622334327
Area Under Curve:    0.7138561184362711
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6033 - accuracy: 0.6718 - val_loss: 0.5584 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5565 - accuracy: 0.7150 - val_loss: 0.5400 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7240 - val_loss: 0.5547 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7296 - val_loss: 0.5366 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5250 - accuracy: 0.7349 - val_loss: 0.5326 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5198 - accuracy: 0.7374 - val_loss: 0.5307 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5136 - accuracy: 0.7436 - val_loss: 0.5308 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7464 - val_loss: 0.5334 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5032 - accuracy: 0.7501 - val_loss: 0.5270 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4962 - accuracy: 0.7551 - val_loss: 0.5346 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4913 - accuracy: 0.7565 - val_loss: 0.5358 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 12/400
262/274 [===========================>..] - ETA: 0s - loss: 0.4890 - accuracy: 0.7575
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
274/274 [==============================] - 1s 2ms/step - loss: 0.4892 - accuracy: 0.7575 - val_loss: 0.5329 - val_accuracy: 0.7250 - lr: 0.0010
271/271 [==============================] - 0s 650us/step
Independent Testing Matthews Correlation:  0.44087220738278304
Confusion Matrix :
 [[2994 1329]
 [1091 3232]]
Accuracy on test set:    0.7201017811704835
Sensitivity:    0.7476289613694194 	 Specificity:    0.6925746009715475
Precision  : 0.7086165314623986
Area Under Curve:    0.7201017811704834
(8646, 4352) (8646,)
Epoch 1/400
274/274 [==============================] - 1s 3ms/step - loss: 0.6029 - accuracy: 0.6697 - val_loss: 0.5548 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5596 - accuracy: 0.7116 - val_loss: 0.5501 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7247 - val_loss: 0.5389 - val_accuracy: 0.7254 - lr: 0.0010
Epoch 4/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7298 - val_loss: 0.5371 - val_accuracy: 0.7269 - lr: 0.0010
Epoch 5/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7345 - val_loss: 0.5356 - val_accuracy: 0.7228 - lr: 0.0010
Epoch 6/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5189 - accuracy: 0.7382 - val_loss: 0.5354 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5122 - accuracy: 0.7419 - val_loss: 0.5344 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 8/400
274/274 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7479 - val_loss: 0.5336 - val_accuracy: 0.7250 - lr: 0.0010
Epoch 9/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4998 - accuracy: 0.7508 - val_loss: 0.5333 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 10/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4921 - accuracy: 0.7555 - val_loss: 0.5341 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 11/400

274/274 [==============================] - 1s 2ms/step - loss: 0.4864 - accuracy: 0.7607 - val_loss: 0.5353 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 12/400
274/274 [==============================] - 1s 2ms/step - loss: 0.4811 - accuracy: 0.7614 - val_loss: 0.5364 - val_accuracy: 0.7295 - lr: 0.0010
Epoch 13/400
 88/274 [========>.....................] - ETA: 0s - loss: 0.4675 - accuracy: 0.7732