In [4]:
import os 
import pandas as pd
import numpy as np

os.chdir("/homes/t326h379/Test_V1_Bioinformatics_Advances_ESM")

df_positive = pd.read_csv('Final_ESM_2_DeepUbi_Feature_Extraction_May_2025.txt', header=None)

df_negative = pd.read_csv('Final_Negative_ESM_2_DeepUbi_Feature_Extraction_May_2025.txt', header=None)

In [5]:
Header_name = ["Label","PID","Position","K"] + [i for i in range(1,2561)]

df_positive.columns = Header_name
df_negative.columns = Header_name

In [7]:
df_positive.head()

,Label,PID,Position,K,1,2,3,4,5,6,...,2551,2552,2553,2554,2555,2556,2557,2558,2559,2560
0,1,P16144,1020,K,0.156837,-0.098284,0.280280,0.198836,0.026452,-0.223713,...,0.307817,-0.208374,-0.093758,-0.291563,0.075684,-0.051130,0.143260,0.087510,0.085177,-0.455214
1,1,P16144,1054,K,-0.032041,0.032619,0.205538,-0.061591,0.205379,0.306535,...,0.068880,-0.038812,0.193596,-0.092230,0.190095,0.227185,0.018039,-0.034437,-0.060396,-0.228281
2,1,P16144,1059,K,0.329651,-0.105151,0.114759,0.020698,-0.166177,0.316250,...,0.259767,0.101928,0.080431,-0.063326,-0.120040,-0.030918,-0.068319,-0.057438,0.077026,-0.050484
3,1,P16144,1159,K,0.189425,-0.066323,0.015130,0.325235,0.113270,-0.294183,...,-0.060124,-0.054666,0.142981,-0.023452,0.335680,0.069276,-0.113617,-0.101351,0.006186,0.331229
4,1,P16144,1712,K,0.151514,-0.063330,0.137010,0.244198,-0.029894,0.089161,...,0.223106,0.222133,-0.048381,-0.018709,0.280043,-0.218382,-0.080067,-0.029252,-0.152350,0.015903

In [17]:
df_negative.tail()

,Label,PID,Position,K,1,2,3,4,5,6,...,2551,2552,2553,2554,2555,2556,2557,2558,2559,2560
40467,0,Q5B9P3,183,K,0.167110,-0.241758,0.089904,0.075568,-0.175181,0.094736,...,0.066086,-0.052976,-0.138428,-0.160649,-0.210169,-0.035695,0.035162,0.051641,0.118768,0.069843
40468,0,Q5B0N6,229,K,0.097181,-0.016471,0.099616,0.224574,0.274327,0.128154,...,-0.012625,-0.157198,0.303113,-0.205683,0.077122,0.048195,0.053759,-0.018400,-0.253202,-0.089991
40469,0,Q5T6F2,167,K,-0.147015,-0.146286,-0.002704,0.089688,0.099355,-0.108106,...,-0.007627,-0.024571,-0.001118,0.008359,0.089822,-0.123033,-0.012884,0.207799,-0.073775,0.135884
40470,0,C8VRT7,467,K,0.030962,0.010376,0.017957,-0.006794,-0.102190,0.036504,...,0.154211,-0.046731,0.019134,0.038987,0.001614,-0.048989,0.036910,-0.189483,-0.218315,0.120791
40471,0,A0A0G2JV04,110,K,-0.281330,-0.202848,0.311292,0.250143,-0.052686,0.145958,...,0.134642,0.049804,-0.117127,-0.300569,-0.002371,-0.237892,-0.045500,0.039761,-0.035814,-0.422546

In [10]:
frames = [df_positive, df_negative]

Ubiquitination_training = pd.concat(frames,ignore_index = True)

df_Train_array = Ubiquitination_training.drop(["Label","PID","Position","K"],axis=1)

df_Train_array = np.array(df_Train_array)

In [12]:
X_train_full = df_Train_array

y_train_full = np.array(list(df_positive["Label"]) + list(df_negative["Label"]))

In [13]:
X_train_full.shape

(82867, 2560)

In [14]:
y_train_full.shape

(82867,)

In [16]:
X_train_full

array([[ 0.15683748, -0.09828431,  0.28027996, ...,  0.0875103 ,
         0.08517724, -0.45521414],
       [-0.03204086,  0.03261896,  0.2055383 , ..., -0.03443728,
        -0.06039588, -0.22828117],
       [ 0.32965058, -0.10515148,  0.11475936, ..., -0.0574378 ,
         0.07702551, -0.05048423],
       ...,
       [-0.14701487, -0.14628552, -0.00270376, ...,  0.20779915,
        -0.07377528,  0.13588424],
       [ 0.03096166,  0.01037606,  0.01795706, ..., -0.1894834 ,
        -0.21831535,  0.12079053],
       [-0.28133029, -0.2028477 ,  0.31129166, ...,  0.03976088,
        -0.03581426, -0.42254636]])

In [33]:
import os 
import pandas as pd
import numpy as np
from tensorflow.keras.layers import Dense, MaxPooling2D, Conv2D, Flatten, \
    BatchNormalization, Activation, GlobalAveragePooling2D, DepthwiseConv2D, \
    Dropout, ReLU, Concatenate, Input, add, Conv1D, MaxPooling1D
import pandas as pd
from Bio import SeqIO
import os
import random
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv1D, Dense, MaxPooling1D, Input, Flatten, LSTM, Dropout, Bidirectional, LeakyReLU, Reshape, Lambda
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import plot_model
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.callbacks import EarlyStopping

# performance matrices
from sklearn.metrics import confusion_matrix, matthews_corrcoef, accuracy_score

# plots
import matplotlib.pyplot as plt
import numpy as np

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.callbacks import ModelCheckpoint
from numpy import array
from numpy import argmax

from tensorflow.keras.regularizers import l1, l2


from tensorflow.keras.models import Model
from tensorflow.keras.layers import Concatenate

from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_curve, roc_auc_score, classification_report, auc
from imblearn.under_sampling import RandomUnderSampler
import imblearn
a = random.sample(range(1, 1000000), 200)

In [34]:
from imblearn.under_sampling import RandomUnderSampler

for i in range(len(a)):
    print("Seed   :", a[i])
    seed = a[i]

    rus = RandomUnderSampler(random_state = seed)
    X_train, y_train = rus.fit_resample(X_train_full,y_train_full)
    
    kfold = StratifiedKFold(n_splits=10)
    cvscores, auc_scores, sn, sp, acc, precision_Charles = list(), list(), list(), list(), list(), list()

    for train_index, test_index in kfold.split(X_train,y_train):
        xtrain, xval = X_train[train_index], X_train[test_index]

        ytrain, yval = y_train[train_index], y_train[test_index]  

        X_train_train, X_test_test, Y_train_train, Y_test_test = train_test_split(xtrain, ytrain, test_size = 0.1, random_state = 321)

        model = Sequential()

        model.add(Input(shape=(2560,)))

    #     model.add(Dense(2560, activation='relu'))
    #     model.add(Dropout(0.3))

    #     model.add(Dense(1024, activation='relu'))
    #     model.add(Dropout(0.3))

    #     model.add(Dense(256, activation='relu'))
    #     model.add(Dropout(0.3))

        model.add(Dense(32,activation='relu',name="Dense_1"))
        model.add(Dropout(0.3))

        model.add(Dense(1,activation='sigmoid',name="Dense_2"))


        model.compile(optimizer=tf.keras.optimizers.Adam(),loss="binary_crossentropy",metrics=["accuracy"])

        reduce_lr_acc = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_accuracy', factor=0.001, patience=5, verbose=1, min_delta=1e-4, mode='max')

        early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_accuracy',patience=5,mode='max')

        history = model.fit(X_train_train, Y_train_train,epochs=400,verbose=1,batch_size=256,
                                callbacks=[reduce_lr_acc, early_stopping],validation_data=(X_test_test, Y_test_test))

        Y_pred = model.predict(xval)
        y_pred = np.array([1 if x > 0.5 else 0 for x in Y_pred])

        Accurayc_laurie = accuracy_score(yval, y_pred)

        print("Independent Testing Matthews Correlation: ",matthews_corrcoef(yval, y_pred))
        print("Confusion Matrix : \n",confusion_matrix(yval, y_pred))
        print("Accuracy on test set:   ",Accurayc_laurie)

        cm = confusion_matrix(yval, y_pred)

        TP = cm[1][1]
        TN = cm[0][0]
        FP = cm[0][1]
        FN = cm[1][0]

        mcc = matthews_corrcoef(yval, y_pred)

        cvscores.append(mcc)


        Sensitivity = TP/(TP+FN)

        Specificity = TN/(TN+FP)

        sn.append(Sensitivity)
        sp.append(Specificity)

        acc.append(Accurayc_laurie)

        print("Sensitivity:   ",Sensitivity,"\t","Specificity:   ",Specificity)


        fpr, tpr, _ = roc_curve(yval, y_pred)

        roc_auc_test = auc(fpr,tpr)

        pre = TP / (TP + FP)

        print("Precision  :",pre)

        precision_Charles.append(pre)

        print("Area Under Curve:   ",roc_auc_test)

        auc_scores.append(roc_auc_test)

        print(xval.shape, yval.shape)


    print("Mean MCC = %.4f + %.4f and Mean AUC = %.4f + %.4f" % (np.mean(cvscores),np.std(cvscores),np.mean(auc_scores),np.std(auc_scores)))

    print("Mean Sensitivity = %.4f + %.4f and Mean Specificity = %.4f + %.4f and Mean Accuracy = %.4f + %.4f" % (np.mean(sn),np.std(sn),np.mean(sp),np.std(sp),np.mean(acc),np.std(acc)))

    print("Mean Precision = %.4f + %.4f" % (np.mean(precision_Charles),np.std(precision_Charles)))

    print("\n\n\n\n")

Seed   : 954302
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5871 - accuracy: 0.6849 - val_loss: 0.5613 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7245 - val_loss: 0.5572 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7341 - val_loss: 0.5509 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7420 - val_loss: 0.5512 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7482 - val_loss: 0.5483 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7566 - val_loss: 0.5506 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4863 - accuracy: 0.7640 - val_loss: 0.5528 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4733 - accuracy: 0.7728 - val_loss: 0.5574 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4630 - accuracy: 0.7797
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7792 - val_loss: 0.5595 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.40161269922389325
Confusion Matrix :
 [[2693 1355]
 [1071 2976]]
Accuracy on test set:    0.7003088326127239
Sensitivity:    0.7353595255744997 	 Specificity:    0.6652667984189723
Precision  : 0.687139228815516
Area Under Curve:    0.7003131619967361
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5891 - accuracy: 0.6822 - val_loss: 0.5564 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7227 - val_loss: 0.5545 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7343 - val_loss: 0.5460 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7427 - val_loss: 0.5474 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7501 - val_loss: 0.5496 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7572 - val_loss: 0.5485 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7648 - val_loss: 0.5509 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4726 - accuracy: 0.7739
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7737 - val_loss: 0.5633 - val_accuracy: 0.7131 - lr: 0.0010
253/253 [==============================] - 0s 813us/step
Independent Testing Matthews Correlation:  0.4165121776739509
Confusion Matrix :
 [[2617 1431]
 [ 943 3104]]
Accuracy on test set:    0.7067325509573811
Sensitivity:    0.7669878922658759 	 Specificity:    0.64649209486166
Precision  : 0.6844542447629548
Area Under Curve:    0.706739993563768
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5863 - accuracy: 0.6862 - val_loss: 0.5479 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7206 - val_loss: 0.5381 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7318 - val_loss: 0.5378 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7420 - val_loss: 0.5348 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7505 - val_loss: 0.5425 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4927 - accuracy: 0.7594 - val_loss: 0.5470 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7632 - val_loss: 0.5423 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4700 - accuracy: 0.7762
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4701 - accuracy: 0.7761 - val_loss: 0.5428 - val_accuracy: 0.7272 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42563557848334094
Confusion Matrix :
 [[2849 1198]
 [1127 2921]]
Accuracy on test set:    0.7127856701667696
Sensitivity:    0.7215909090909091 	 Specificity:    0.7039782554978997
Precision  : 0.7091527069677106
Area Under Curve:    0.7127845822944044
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5849 - accuracy: 0.6854 - val_loss: 0.5456 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7229 - val_loss: 0.5372 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7336 - val_loss: 0.5336 - val_accuracy: 0.7348 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5149 - accuracy: 0.7433 - val_loss: 0.5337 - val_accuracy: 0.7338 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7516 - val_loss: 0.5350 - val_accuracy: 0.7355 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.7615 - val_loss: 0.5367 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.7696 - val_loss: 0.5359 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4640 - accuracy: 0.7777 - val_loss: 0.5424 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4521 - accuracy: 0.7881 - val_loss: 0.5452 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4375 - accuracy: 0.7939
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4374 - accuracy: 0.7940 - val_loss: 0.5525 - val_accuracy: 0.7263 - lr: 0.0010
253/253 [==============================] - 0s 853us/step
Independent Testing Matthews Correlation:  0.40989369943450094
Confusion Matrix :
 [[2904 1143]
 [1246 2802]]
Accuracy on test set:    0.7048795552810376
Sensitivity:    0.692193675889328 	 Specificity:    0.7175685693106004
Precision  : 0.7102661596958175
Area Under Curve:    0.7048811225999643
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5857 - accuracy: 0.6867 - val_loss: 0.5504 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7216 - val_loss: 0.5444 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7319 - val_loss: 0.5414 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7394 - val_loss: 0.5406 - val_accuracy: 0.7226 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7462 - val_loss: 0.5410 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4994 - accuracy: 0.7534 - val_loss: 0.5443 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
252/257 [============================>.] - ETA: 0s - loss: 0.4906 - accuracy: 0.7606
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7604 - val_loss: 0.5428 - val_accuracy: 0.7200 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42808929957815023
Confusion Matrix :
 [[2842 1205]
 [1110 2937]]
Accuracy on test set:    0.7139856683963429
Sensitivity:    0.7257227575982209 	 Specificity:    0.702248579194465
Precision  : 0.7090777402221149
Area Under Curve:    0.7139856683963429
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5860 - accuracy: 0.6865 - val_loss: 0.5577 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7238 - val_loss: 0.5472 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7342 - val_loss: 0.5501 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7420 - val_loss: 0.5432 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5054 - accuracy: 0.7514 - val_loss: 0.5448 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7599 - val_loss: 0.5453 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7668 - val_loss: 0.5460 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4732 - accuracy: 0.7747 - val_loss: 0.5494 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4599 - accuracy: 0.7833
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4600 - accuracy: 0.7831 - val_loss: 0.5557 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 793us/step
Independent Testing Matthews Correlation:  0.42798556557767137
Confusion Matrix :
 [[2906 1141]
 [1174 2873]]
Accuracy on test set:    0.7139856683963429
Sensitivity:    0.7099085742525327 	 Specificity:    0.7180627625401532
Precision  : 0.7157448928749377
Area Under Curve:    0.713985668396343
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5862 - accuracy: 0.6849 - val_loss: 0.5481 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7200 - val_loss: 0.5431 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7325 - val_loss: 0.5447 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7405 - val_loss: 0.5413 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5108 - accuracy: 0.7476 - val_loss: 0.5414 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7562 - val_loss: 0.5394 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4868 - accuracy: 0.7638
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.7634 - val_loss: 0.5422 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4380083205051636
Confusion Matrix :
 [[2856 1191]
 [1084 2963]]
Accuracy on test set:    0.7189276006918706
Sensitivity:    0.7321472695824067 	 Specificity:    0.7057079318013343
Precision  : 0.7132883967260472
Area Under Curve:    0.7189276006918706
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5908 - accuracy: 0.6812 - val_loss: 0.5526 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5484 - accuracy: 0.7199 - val_loss: 0.5439 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5332 - accuracy: 0.7319 - val_loss: 0.5426 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5220 - accuracy: 0.7385 - val_loss: 0.5407 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7475 - val_loss: 0.5412 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4989 - accuracy: 0.7563 - val_loss: 0.5433 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7630 - val_loss: 0.5476 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7702 - val_loss: 0.5460 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4633 - accuracy: 0.7806 - val_loss: 0.5538 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4501 - accuracy: 0.7901 - val_loss: 0.5562 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4368 - accuracy: 0.7970 - val_loss: 0.5605 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 12/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4237 - accuracy: 0.8033
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4240 - accuracy: 0.8034 - val_loss: 0.5702 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4482704808274762
Confusion Matrix :
 [[2831 1216]
 [1019 3028]]
Accuracy on test set:    0.7238695329873981
Sensitivity:    0.7482085495428713 	 Specificity:    0.6995305164319249
Precision  : 0.7134778510838832
Area Under Curve:    0.7238695329873981
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5907 - accuracy: 0.6832 - val_loss: 0.5559 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7220 - val_loss: 0.5467 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5324 - accuracy: 0.7339 - val_loss: 0.5433 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5226 - accuracy: 0.7391 - val_loss: 0.5489 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5112 - accuracy: 0.7470 - val_loss: 0.5410 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.7561 - val_loss: 0.5427 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4872 - accuracy: 0.7633 - val_loss: 0.5421 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4734 - accuracy: 0.7745 - val_loss: 0.5536 - val_accuracy: 0.7139 - lr: 0.0010

Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4615 - accuracy: 0.7813 - val_loss: 0.5582 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4482 - accuracy: 0.7902 - val_loss: 0.5568 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 11/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4346 - accuracy: 0.7974
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4353 - accuracy: 0.7969 - val_loss: 0.5604 - val_accuracy: 0.7149 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43882394886014886
Confusion Matrix :
 [[3026 1021]
 [1253 2794]]
Accuracy on test set:    0.7190511489992587
Sensitivity:    0.6903879416851989 	 Specificity:    0.7477143563133185
Precision  : 0.7323722149410222
Area Under Curve:    0.7190511489992587
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5952 - accuracy: 0.6798 - val_loss: 0.5569 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5515 - accuracy: 0.7167 - val_loss: 0.5493 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5374 - accuracy: 0.7294 - val_loss: 0.5451 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5245 - accuracy: 0.7366 - val_loss: 0.5443 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7444 - val_loss: 0.5443 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7522 - val_loss: 0.5472 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4927 - accuracy: 0.7600 - val_loss: 0.5474 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4792 - accuracy: 0.7688
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.7690 - val_loss: 0.5527 - val_accuracy: 0.7154 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.4845877660015821
Confusion Matrix :
 [[2981 1066]
 [1020 3027]]
Accuracy on test set:    0.7422782307882382
Sensitivity:    0.7479614529280949 	 Specificity:    0.7365950086483816
Precision  : 0.7395553383826045
Area Under Curve:    0.7422782307882382
(8094, 2560) (8094,)
Mean MCC = 0.4319 + 0.0220 and Mean AUC = 0.7157 + 0.0112
Mean Sensitivity = 0.7270 + 0.0234 and Mean Specificity = 0.7043 + 0.0286 and Mean Accuracy = 0.7157 + 0.0112
Mean Precision = 0.7115 + 0.0161





Seed   : 121183
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5882 - accuracy: 0.6824 - val_loss: 0.5596 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7239 - val_loss: 0.5527 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7352 - val_loss: 0.5534 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7421 - val_loss: 0.5576 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5054 - accuracy: 0.7514 - val_loss: 0.5540 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7603 - val_loss: 0.5499 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4823 - accuracy: 0.7666
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.7665 - val_loss: 0.5630 - val_accuracy: 0.7098 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4149468288670486
Confusion Matrix :
 [[2587 1461]
 [ 922 3125]]
Accuracy on test set:    0.705620753551575
Sensitivity:    0.7721769211761799 	 Specificity:    0.6390810276679841
Precision  : 0.6814217182730048
Area Under Curve:    0.705628974422082
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5855 - accuracy: 0.6865 - val_loss: 0.5581 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7258 - val_loss: 0.5503 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5261 - accuracy: 0.7347 - val_loss: 0.5484 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7425 - val_loss: 0.5544 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5021 - accuracy: 0.7536 - val_loss: 0.5552 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4893 - accuracy: 0.7612 - val_loss: 0.5582 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4783 - accuracy: 0.7695 - val_loss: 0.5610 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4644 - accuracy: 0.7787
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4647 - accuracy: 0.7784 - val_loss: 0.5598 - val_accuracy: 0.7127 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4229437646707553
Confusion Matrix :
 [[2773 1275]
 [1063 2984]]
Accuracy on test set:    0.7111797405806053
Sensitivity:    0.7373362984927107 	 Specificity:    0.6850296442687747
Precision  : 0.7006339516318385
Area Under Curve:    0.7111829713807426
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5862 - accuracy: 0.6832 - val_loss: 0.5530 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7239 - val_loss: 0.5421 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7354 - val_loss: 0.5461 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7427 - val_loss: 0.5380 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7482 - val_loss: 0.5385 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7563 - val_loss: 0.5403 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4838 - accuracy: 0.7657
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7657 - val_loss: 0.5478 - val_accuracy: 0.7145 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4200376093366019
Confusion Matrix :
 [[2706 1341]
 [1012 3036]]
Accuracy on test set:    0.7093267449042618
Sensitivity:    0.75 	 Specificity:    0.6686434395848777
Precision  : 0.6936257710760795
Area Under Curve:    0.7093217197924389
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5908 - accuracy: 0.6829 - val_loss: 0.5523 - val_accuracy: 0.7176 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7208 - val_loss: 0.5490 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7318 - val_loss: 0.5412 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7404 - val_loss: 0.5370 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7472 - val_loss: 0.5403 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.7536 - val_loss: 0.5425 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7628 - val_loss: 0.5460 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4759 - accuracy: 0.7711 - val_loss: 0.5478 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 9/400
240/257 [===========================>..] - ETA: 0s - loss: 0.4647 - accuracy: 0.7796
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4651 - accuracy: 0.7795 - val_loss: 0.5524 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 0s 950us/step
Independent Testing Matthews Correlation:  0.4243163177071899
Confusion Matrix :
 [[2743 1304]
 [1030 3018]]
Accuracy on test set:    0.7116738727609636
Sensitivity:    0.7455533596837944 	 Specificity:    0.6777860143316037
Precision  : 0.6982878297084683
Area Under Curve:    0.7116696870076991
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6865 - val_loss: 0.5544 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7223 - val_loss: 0.5452 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7329 - val_loss: 0.5449 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7402 - val_loss: 0.5427 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.7478 - val_loss: 0.5440 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7558 - val_loss: 0.5503 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4857 - accuracy: 0.7649 - val_loss: 0.5565 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4736 - accuracy: 0.7736 - val_loss: 0.5527 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4620 - accuracy: 0.7807
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4619 - accuracy: 0.7806 - val_loss: 0.5612 - val_accuracy: 0.7131 - lr: 0.0010
253/253 [==============================] - 0s 860us/step
Independent Testing Matthews Correlation:  0.41515433807483454
Confusion Matrix :
 [[3019 1028]
 [1344 2703]]
Accuracy on test set:    0.7069434148752162
Sensitivity:    0.6679021497405485 	 Specificity:    0.7459846800098838
Precision  : 0.7244706512999196
Area Under Curve:    0.7069434148752163
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5876 - accuracy: 0.6852 - val_loss: 0.5567 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7232 - val_loss: 0.5504 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7352 - val_loss: 0.5485 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7423 - val_loss: 0.5490 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7496 - val_loss: 0.5519 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7574 - val_loss: 0.5566 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7660 - val_loss: 0.5521 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4733 - accuracy: 0.7734 - val_loss: 0.5632 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4595 - accuracy: 0.7819 - val_loss: 0.5711 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4496 - accuracy: 0.7896
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4496 - accuracy: 0.7896 - val_loss: 0.5614 - val_accuracy: 0.7093 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41139098484662656
Confusion Matrix :
 [[2922 1125]
 [1258 2789]]
Accuracy on test set:    0.7055843834939461
Sensitivity:    0.689152458611317 	 Specificity:    0.7220163083765753
Precision  : 0.7125702606029637
Area Under Curve:    0.705584383493946
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5839 - accuracy: 0.6882 - val_loss: 0.5574 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7220 - val_loss: 0.5483 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7352 - val_loss: 0.5532 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7414 - val_loss: 0.5455 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7517 - val_loss: 0.5483 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.7593 - val_loss: 0.5478 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7666 - val_loss: 0.5547 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.7752 - val_loss: 0.5564 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4550 - accuracy: 0.7846
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4550 - accuracy: 0.7846 - val_loss: 0.5574 - val_accuracy: 0.7126 - lr: 0.0010
253/253 [==============================] - 0s 784us/step
Independent Testing Matthews Correlation:  0.4207826681445947
Confusion Matrix :
 [[2736 1311]
 [1037 3010]]
Accuracy on test set:    0.7099085742525327
Sensitivity:    0.7437608104768965 	 Specificity:    0.676056338028169
Precision  : 0.6965980097199722
Area Under Curve:    0.7099085742525327
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5868 - accuracy: 0.6860 - val_loss: 0.5574 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7226 - val_loss: 0.5489 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7339 - val_loss: 0.5471 - val_accuracy: 0.7152 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7413 - val_loss: 0.5463 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7497 - val_loss: 0.5444 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7579 - val_loss: 0.5488 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7670 - val_loss: 0.5550 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4725 - accuracy: 0.7733 - val_loss: 0.5567 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4637 - accuracy: 0.7811 - val_loss: 0.5556 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4495 - accuracy: 0.7885 - val_loss: 0.5595 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4409 - accuracy: 0.7953 - val_loss: 0.5701 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4263 - accuracy: 0.8038 - val_loss: 0.5730 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 13/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4157 - accuracy: 0.8110
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4161 - accuracy: 0.8107 - val_loss: 0.5738 - val_accuracy: 0.7071 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42995095604265293
Confusion Matrix :
 [[2773 1274]
 [1036 3011]]
Accuracy on test set:    0.7146034099332839
Sensitivity:    0.7440079070916729 	 Specificity:    0.685198912774895
Precision  : 0.7026837806301051
Area Under Curve:    0.7146034099332839
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5906 - accuracy: 0.6833 - val_loss: 0.5589 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.7211 - val_loss: 0.5499 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5328 - accuracy: 0.7306 - val_loss: 0.5467 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7400 - val_loss: 0.5491 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.7459 - val_loss: 0.5510 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5018 - accuracy: 0.7551 - val_loss: 0.5475 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7613 - val_loss: 0.5524 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4779 - accuracy: 0.7705 - val_loss: 0.5556 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4659 - accuracy: 0.7779 - val_loss: 0.5592 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4533 - accuracy: 0.7868 - val_loss: 0.5720 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4429 - accuracy: 0.7937
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4427 - accuracy: 0.7939 - val_loss: 0.5739 - val_accuracy: 0.7105 - lr: 0.0010
253/253 [==============================] - 0s 876us/step
Independent Testing Matthews Correlation:  0.4591095608576128
Confusion Matrix :
 [[2944 1103]
 [1086 2961]]
Accuracy on test set:    0.7295527551272547
Sensitivity:    0.7316530763528539 	 Specificity:    0.7274524339016556
Precision  : 0.7285925196850394
Area Under Curve:    0.7295527551272547
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5908 - accuracy: 0.6824 - val_loss: 0.5566 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7196 - val_loss: 0.5502 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5324 - accuracy: 0.7308 - val_loss: 0.5475 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5222 - accuracy: 0.7382 - val_loss: 0.5460 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7483 - val_loss: 0.5511 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.7560 - val_loss: 0.5496 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7638 - val_loss: 0.5518 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4751 - accuracy: 0.7732
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4752 - accuracy: 0.7730 - val_loss: 0.5581 - val_accuracy: 0.7101 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4731319352545866
Confusion Matrix :
 [[3247  800]
 [1350 2697]]
Accuracy on test set:    0.7343711391153941
Sensitivity:    0.6664195700518903 	 Specificity:    0.802322708178898
Precision  : 0.7712324849871318
Area Under Curve:    0.7343711391153942
(8094, 2560) (8094,)
Mean MCC = 0.4292 + 0.0194 and Mean AUC = 0.7139 + 0.0095
Mean Sensitivity = 0.7248 + 0.0349 and Mean Specificity = 0.7030 + 0.0447 and Mean Accuracy = 0.7139 + 0.0095
Mean Precision = 0.7110 + 0.0242





Seed   : 462580
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5855 - accuracy: 0.6867 - val_loss: 0.5586 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7259 - val_loss: 0.5496 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7357 - val_loss: 0.5500 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5141 - accuracy: 0.7459 - val_loss: 0.5494 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7519 - val_loss: 0.5488 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.7591 - val_loss: 0.5499 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4783 - accuracy: 0.7693 - val_loss: 0.5562 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7782 - val_loss: 0.5562 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4501 - accuracy: 0.7874 - val_loss: 0.5674 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4356 - accuracy: 0.7964 - val_loss: 0.5785 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4233 - accuracy: 0.8056
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4235 - accuracy: 0.8052 - val_loss: 0.5822 - val_accuracy: 0.7069 - lr: 0.0010

253/253 [==============================] - 0s 965us/step
Independent Testing Matthews Correlation:  0.4008020050093676
Confusion Matrix :
 [[2741 1307]
 [1120 2927]]
Accuracy on test set:    0.7001852995676343
Sensitivity:    0.7232517914504571 	 Specificity:    0.6771245059288538
Precision  : 0.6913084553613604
Area Under Curve:    0.7001881486896555
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5883 - accuracy: 0.6865 - val_loss: 0.5576 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7233 - val_loss: 0.5507 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7340 - val_loss: 0.5493 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7410 - val_loss: 0.5484 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5101 - accuracy: 0.7473 - val_loss: 0.5472 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.7549 - val_loss: 0.5485 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7605 - val_loss: 0.5523 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7678 - val_loss: 0.5506 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.7745 - val_loss: 0.5507 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4637 - accuracy: 0.7797 - val_loss: 0.5576 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4513 - accuracy: 0.7879 - val_loss: 0.5706 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4421 - accuracy: 0.7924 - val_loss: 0.5710 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4317 - accuracy: 0.8010 - val_loss: 0.5654 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4208 - accuracy: 0.8060 - val_loss: 0.5688 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 15/400
252/257 [============================>.] - ETA: 0s - loss: 0.4115 - accuracy: 0.8115
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4115 - accuracy: 0.8116 - val_loss: 0.5747 - val_accuracy: 0.7150 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39716136420921044
Confusion Matrix :
 [[2821 1227]
 [1213 2834]]
Accuracy on test set:    0.6985793699814701
Sensitivity:    0.700271806276254 	 Specificity:    0.6968873517786561
Precision  : 0.6978576705245013
Area Under Curve:    0.6985795790274552
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5871 - accuracy: 0.6863 - val_loss: 0.5506 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7231 - val_loss: 0.5524 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7347 - val_loss: 0.5400 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5130 - accuracy: 0.7435 - val_loss: 0.5438 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7540 - val_loss: 0.5470 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4886 - accuracy: 0.7620 - val_loss: 0.5465 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4756 - accuracy: 0.7706 - val_loss: 0.5454 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4620 - accuracy: 0.7811
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4624 - accuracy: 0.7813 - val_loss: 0.5513 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 785us/step
Independent Testing Matthews Correlation:  0.41276621958832854
Confusion Matrix :
 [[2754 1293]
 [1086 2962]]
Accuracy on test set:    0.7061148857319333
Sensitivity:    0.7317193675889329 	 Specificity:    0.6805040770941438
Precision  : 0.6961222091656875
Area Under Curve:    0.7061117223415383
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5873 - accuracy: 0.6842 - val_loss: 0.5483 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7215 - val_loss: 0.5378 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7330 - val_loss: 0.5374 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7397 - val_loss: 0.5400 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7488 - val_loss: 0.5383 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7546 - val_loss: 0.5392 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4881 - accuracy: 0.7638
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4883 - accuracy: 0.7638 - val_loss: 0.5410 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.432788646041639
Confusion Matrix :
 [[2796 1251]
 [1047 3001]]
Accuracy on test set:    0.7161210623841878
Sensitivity:    0.7413537549407114 	 Specificity:    0.6908821349147517
Precision  : 0.705785512699906
Area Under Curve:    0.7161179449277314
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5864 - accuracy: 0.6845 - val_loss: 0.5486 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7214 - val_loss: 0.5388 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7332 - val_loss: 0.5380 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7415 - val_loss: 0.5397 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7501 - val_loss: 0.5382 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7580 - val_loss: 0.5405 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4817 - accuracy: 0.7677 - val_loss: 0.5444 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4685 - accuracy: 0.7747 - val_loss: 0.5524 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4559 - accuracy: 0.7842 - val_loss: 0.5531 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4458 - accuracy: 0.7893 - val_loss: 0.5585 - val_accuracy: 0.7272 - lr: 0.0010

Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4330 - accuracy: 0.7976 - val_loss: 0.5562 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4193 - accuracy: 0.8052 - val_loss: 0.5644 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4091 - accuracy: 0.8120 - val_loss: 0.5770 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3978 - accuracy: 0.8174 - val_loss: 0.5805 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 15/400
253/257 [============================>.] - ETA: 0s - loss: 0.3892 - accuracy: 0.8223
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3896 - accuracy: 0.8221 - val_loss: 0.5876 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4156250885052434
Confusion Matrix :
 [[2764 1283]
 [1084 2963]]
Accuracy on test set:    0.7075611564121571
Sensitivity:    0.7321472695824067 	 Specificity:    0.6829750432419076
Precision  : 0.6978332548280735
Area Under Curve:    0.7075611564121572
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5866 - accuracy: 0.6840 - val_loss: 0.5488 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7211 - val_loss: 0.5445 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7334 - val_loss: 0.5382 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7408 - val_loss: 0.5384 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7487 - val_loss: 0.5398 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7592 - val_loss: 0.5414 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7644 - val_loss: 0.5438 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7742 - val_loss: 0.5501 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4582 - accuracy: 0.7843
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4582 - accuracy: 0.7843 - val_loss: 0.5502 - val_accuracy: 0.7197 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42417737106258285
Confusion Matrix :
 [[2937 1110]
 [1221 2826]]
Accuracy on test set:    0.712008895478132
Sensitivity:    0.698295033358043 	 Specificity:    0.7257227575982209
Precision  : 0.7179878048780488
Area Under Curve:    0.712008895478132
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5857 - accuracy: 0.6877 - val_loss: 0.5525 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7220 - val_loss: 0.5369 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7338 - val_loss: 0.5351 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7434 - val_loss: 0.5332 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5043 - accuracy: 0.7514 - val_loss: 0.5385 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.7605 - val_loss: 0.5391 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4779 - accuracy: 0.7704 - val_loss: 0.5480 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4644 - accuracy: 0.7788 - val_loss: 0.5468 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4516 - accuracy: 0.7882
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4515 - accuracy: 0.7883 - val_loss: 0.5607 - val_accuracy: 0.7237 - lr: 0.0010
253/253 [==============================] - 0s 765us/step
Independent Testing Matthews Correlation:  0.43228228656676154
Confusion Matrix :
 [[2708 1339]
 [ 966 3081]]
Accuracy on test set:    0.7152211514702248
Sensitivity:    0.7613046701260193 	 Specificity:    0.6691376328144304
Precision  : 0.6970588235294117
Area Under Curve:    0.7152211514702249
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5904 - accuracy: 0.6835 - val_loss: 0.5450 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7217 - val_loss: 0.5418 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7309 - val_loss: 0.5368 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7391 - val_loss: 0.5354 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5108 - accuracy: 0.7459 - val_loss: 0.5343 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5020 - accuracy: 0.7539 - val_loss: 0.5353 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4907 - accuracy: 0.7616 - val_loss: 0.5411 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7698 - val_loss: 0.5458 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4673 - accuracy: 0.7779
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7773 - val_loss: 0.5437 - val_accuracy: 0.7253 - lr: 0.0010
253/253 [==============================] - 0s 977us/step
Independent Testing Matthews Correlation:  0.4514455151964418
Confusion Matrix :
 [[2937 1110]
 [1110 2937]]
Accuracy on test set:    0.7257227575982209
Sensitivity:    0.7257227575982209 	 Specificity:    0.7257227575982209
Precision  : 0.7257227575982209
Area Under Curve:    0.7257227575982208
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5909 - accuracy: 0.6830 - val_loss: 0.5470 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7213 - val_loss: 0.5391 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7323 - val_loss: 0.5372 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7425 - val_loss: 0.5374 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.7487 - val_loss: 0.5427 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7558 - val_loss: 0.5405 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4892 - accuracy: 0.7624
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7622 - val_loss: 0.5429 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4435559730588799
Confusion Matrix :
 [[2903 1144]
 [1108 2939]]
Accuracy on test set:    0.7217692117617989
Sensitivity:    0.7262169508277737 	 Specificity:    0.717321472695824
Precision  : 0.7198138623561107
Area Under Curve:    0.721769211761799
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5939 - accuracy: 0.6792 - val_loss: 0.5532 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5505 - accuracy: 0.7195 - val_loss: 0.5448 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5357 - accuracy: 0.7305 - val_loss: 0.5418 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5234 - accuracy: 0.7391 - val_loss: 0.5443 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5129 - accuracy: 0.7460 - val_loss: 0.5491 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.7542 - val_loss: 0.5466 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4894 - accuracy: 0.7630
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4897 - accuracy: 0.7625 - val_loss: 0.5446 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 950us/step
Independent Testing Matthews Correlation:  0.5012026620117112
Confusion Matrix :
 [[2999 1048]
 [ 971 3076]]
Accuracy on test set:    0.7505559673832468
Sensitivity:    0.7600691870521374 	 Specificity:    0.7410427477143563
Precision  : 0.7458777885548011
Area Under Curve:    0.7505559673832468
(8094, 2560) (8094,)
Mean MCC = 0.4312 + 0.0286 and Mean AUC = 0.7154 + 0.0143
Mean Sensitivity = 0.7300 + 0.0200 and Mean Specificity = 0.7007 + 0.0235 and Mean Accuracy = 0.7154 + 0.0143
Mean Precision = 0.7095 + 0.0165





Seed   : 560276
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5930 - accuracy: 0.6807 - val_loss: 0.5632 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7241 - val_loss: 0.5591 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7341 - val_loss: 0.5509 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7423 - val_loss: 0.5495 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7513 - val_loss: 0.5528 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7564 - val_loss: 0.5528 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.7629 - val_loss: 0.5666 - val_accuracy: 0.7032 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4770 - accuracy: 0.7708 - val_loss: 0.5564 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4660 - accuracy: 0.7787
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4660 - accuracy: 0.7786 - val_loss: 0.5717 - val_accuracy: 0.7030 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40689599223237133
Confusion Matrix :
 [[3108  940]
 [1475 2572]]
Accuracy on test set:    0.701667696108709
Sensitivity:    0.6355324932048431 	 Specificity:    0.7677865612648221
Precision  : 0.7323462414578588
Area Under Curve:    0.7016595272348327
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5857 - accuracy: 0.6860 - val_loss: 0.5580 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5419 - accuracy: 0.7248 - val_loss: 0.5485 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.7363 - val_loss: 0.5455 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5154 - accuracy: 0.7442 - val_loss: 0.5447 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7530 - val_loss: 0.5454 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7591 - val_loss: 0.5474 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7664 - val_loss: 0.5538 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4723 - accuracy: 0.7761 - val_loss: 0.5516 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4591 - accuracy: 0.7833 - val_loss: 0.5592 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4483 - accuracy: 0.7907 - val_loss: 0.5610 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4361 - accuracy: 0.7979 - val_loss: 0.5623 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 12/400
252/257 [============================>.] - ETA: 0s - loss: 0.4249 - accuracy: 0.8045
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4249 - accuracy: 0.8048 - val_loss: 0.5682 - val_accuracy: 0.7043 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.404986068292704
Confusion Matrix :
 [[2935 1113]
 [1297 2750]]
Accuracy on test set:    0.7022853613341569
Sensitivity:    0.6795156906350382 	 Specificity:    0.7250494071146245
Precision  : 0.7118819570282164
Area Under Curve:    0.7022825488748314
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5850 - accuracy: 0.6868 - val_loss: 0.5568 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7251 - val_loss: 0.5430 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7355 - val_loss: 0.5403 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7415 - val_loss: 0.5421 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7517 - val_loss: 0.5413 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.7596 - val_loss: 0.5442 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4825 - accuracy: 0.7666 - val_loss: 0.5508 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4689 - accuracy: 0.7759 - val_loss: 0.5498 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4563 - accuracy: 0.7838 - val_loss: 0.5530 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 10/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4411 - accuracy: 0.7942
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4420 - accuracy: 0.7932 - val_loss: 0.5617 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 760us/step
Independent Testing Matthews Correlation:  0.4049973366316633
Confusion Matrix :
 [[2595 1452]
 [ 968 3080]]
Accuracy on test set:    0.7010500308832612
Sensitivity:    0.7608695652173914 	 Specificity:    0.6412157153446998
Precision  : 0.6796116504854369
Area Under Curve:    0.7010426402810456
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5917 - accuracy: 0.6807 - val_loss: 0.5455 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7228 - val_loss: 0.5384 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7347 - val_loss: 0.5375 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7408 - val_loss: 0.5365 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7496 - val_loss: 0.5351 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7564 - val_loss: 0.5373 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7647 - val_loss: 0.5413 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4746 - accuracy: 0.7719
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7719 - val_loss: 0.5468 - val_accuracy: 0.7266 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4268035837959912
Confusion Matrix :
 [[2676 1371]
 [ 958 3090]]
Accuracy on test set:    0.7122915379864113
Sensitivity:    0.7633399209486166 	 Specificity:    0.6612305411415864
Precision  : 0.6926698049764627
Area Under Curve:    0.7122852310451016
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5849 - accuracy: 0.6859 - val_loss: 0.5474 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7238 - val_loss: 0.5407 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7349 - val_loss: 0.5389 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7422 - val_loss: 0.5414 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7496 - val_loss: 0.5381 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7589 - val_loss: 0.5417 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7636 - val_loss: 0.5459 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7745 - val_loss: 0.5494 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4589 - accuracy: 0.7809 - val_loss: 0.5543 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4472 - accuracy: 0.7891
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4472 - accuracy: 0.7893 - val_loss: 0.5721 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4451511205806811
Confusion Matrix :
 [[2670 1377]
 [ 882 3165]]
Accuracy on test set:    0.7209043736100815
Sensitivity:    0.782060785767235 	 Specificity:    0.6597479614529281
Precision  : 0.6968295904887715
Area Under Curve:    0.7209043736100814
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5912 - accuracy: 0.6817 - val_loss: 0.5526 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7227 - val_loss: 0.5500 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7336 - val_loss: 0.5450 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7423 - val_loss: 0.5434 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7497 - val_loss: 0.5435 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4928 - accuracy: 0.7590 - val_loss: 0.5486 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7654 - val_loss: 0.5477 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7745 - val_loss: 0.5552 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4595 - accuracy: 0.7809 - val_loss: 0.5555 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4484 - accuracy: 0.7903 - val_loss: 0.5614 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - ETA: 0s - loss: 0.4375 - accuracy: 0.7960
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4375 - accuracy: 0.7960 - val_loss: 0.5710 - val_accuracy: 0.7193 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4273457841796948
Confusion Matrix :
 [[2684 1363]
 [ 963 3084]]
Accuracy on test set:    0.7126266370150729
Sensitivity:    0.7620459599703484 	 Specificity:    0.6632073140597974
Precision  : 0.6935012367888465
Area Under Curve:    0.7126266370150729
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5880 - accuracy: 0.6831 - val_loss: 0.5490 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7237 - val_loss: 0.5431 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5259 - accuracy: 0.7364 - val_loss: 0.5436 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7446 - val_loss: 0.5438 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5003 - accuracy: 0.7550 - val_loss: 0.5490 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4866 - accuracy: 0.7646 - val_loss: 0.5480 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4733 - accuracy: 0.7727
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7722 - val_loss: 0.5503 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.428312317089194
Confusion Matrix :
 [[2783 1264]
 [1052 2995]]
Accuracy on test set:    0.7138621200889548
Sensitivity:    0.7400543612552508 	 Specificity:    0.6876698789226587
Precision  : 0.7032167175393285
Area Under Curve:    0.7138621200889548
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5879 - accuracy: 0.6827 - val_loss: 0.5525 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5432 - accuracy: 0.7244 - val_loss: 0.5446 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7335 - val_loss: 0.5448 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7416 - val_loss: 0.5437 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7483 - val_loss: 0.5412 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7576 - val_loss: 0.5405 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4846 - accuracy: 0.7653
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4848 - accuracy: 0.7656 - val_loss: 0.5462 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 908us/step
Independent Testing Matthews Correlation:  0.4460147240428527
Confusion Matrix :
 [[2789 1258]
 [ 988 3059]]
Accuracy on test set:    0.722510501606128
Sensitivity:    0.755868544600939 	 Specificity:    0.689152458611317
Precision  : 0.7085939309705814
Area Under Curve:    0.7225105016061281
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5943 - accuracy: 0.6780 - val_loss: 0.5533 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5492 - accuracy: 0.7211 - val_loss: 0.5459 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5343 - accuracy: 0.7308 - val_loss: 0.5441 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5221 - accuracy: 0.7412 - val_loss: 0.5450 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5118 - accuracy: 0.7469 - val_loss: 0.5483 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4995 - accuracy: 0.7559 - val_loss: 0.5474 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4879 - accuracy: 0.7623
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7623 - val_loss: 0.5525 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 0s 889us/step
Independent Testing Matthews Correlation:  0.45801079076789525
Confusion Matrix :
 [[2806 1241]
 [ 957 3090]]
Accuracy on test set:    0.7284408203607611
Sensitivity:    0.7635285396590067 	 Specificity:    0.6933531010625155
Precision  : 0.7134610944354652
Area Under Curve:    0.7284408203607611
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5929 - accuracy: 0.6793 - val_loss: 0.5557 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5510 - accuracy: 0.7191 - val_loss: 0.5484 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5371 - accuracy: 0.7281 - val_loss: 0.5468 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5230 - accuracy: 0.7388 - val_loss: 0.5467 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5133 - accuracy: 0.7453 - val_loss: 0.5473 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5021 - accuracy: 0.7541 - val_loss: 0.5466 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4887 - accuracy: 0.7630 - val_loss: 0.5505 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4752 - accuracy: 0.7709 - val_loss: 0.5553 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4626 - accuracy: 0.7814 - val_loss: 0.5543 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4477 - accuracy: 0.7904 - val_loss: 0.5609 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4350 - accuracy: 0.7973 - val_loss: 0.5642 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4200 - accuracy: 0.8056
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4202 - accuracy: 0.8055 - val_loss: 0.5692 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 842us/step
Independent Testing Matthews Correlation:  0.4760614920029534
Confusion Matrix :
 [[3109  938]
 [1186 2861]]
Accuracy on test set:    0.737583395107487
Sensitivity:    0.7069434148752162 	 Specificity:    0.7682233753397578
Precision  : 0.7530929191892604
Area Under Curve:    0.737583395107487
(8094, 2560) (8094,)
Mean MCC = 0.4325 + 0.0227 and Mean AUC = 0.7153 + 0.0115
Mean Sensitivity = 0.7350 + 0.0441 and Mean Specificity = 0.6957 + 0.0424 and Mean Accuracy = 0.7153 + 0.0115
Mean Precision = 0.7085 + 0.0202





Seed   : 775780
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5850 - accuracy: 0.6866 - val_loss: 0.5622 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5413 - accuracy: 0.7242 - val_loss: 0.5533 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5241 - accuracy: 0.7373 - val_loss: 0.5459 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5120 - accuracy: 0.7449 - val_loss: 0.5497 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.7540 - val_loss: 0.5506 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.7636 - val_loss: 0.5446 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4776 - accuracy: 0.7708 - val_loss: 0.5664 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4645 - accuracy: 0.7776 - val_loss: 0.5576 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4516 - accuracy: 0.7877 - val_loss: 0.5682 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4399 - accuracy: 0.7950 - val_loss: 0.5669 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4240 - accuracy: 0.8049
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4241 - accuracy: 0.8050 - val_loss: 0.5811 - val_accuracy: 0.7091 - lr: 0.0010
253/253 [==============================] - 0s 892us/step
Independent Testing Matthews Correlation:  0.39318569280447774
Confusion Matrix :
 [[2643 1405]
 [1057 2990]]
Accuracy on test set:    0.6958616429894997
Sensitivity:    0.7388188781813689 	 Specificity:    0.6529150197628458
Precision  : 0.6803185437997725
Area Under Curve:    0.6958669489721074
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5820 - accuracy: 0.6880 - val_loss: 0.5525 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5418 - accuracy: 0.7246 - val_loss: 0.5471 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5256 - accuracy: 0.7366 - val_loss: 0.5455 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5142 - accuracy: 0.7436 - val_loss: 0.5457 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5010 - accuracy: 0.7534 - val_loss: 0.5487 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 6/400
256/257 [============================>.] - ETA: 0s - loss: 0.4884 - accuracy: 0.7626
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.7626 - val_loss: 0.5494 - val_accuracy: 0.7112 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42289309666889124
Confusion Matrix :
 [[2908 1140]
 [1196 2851]]
Accuracy on test set:    0.7114268066707844
Sensitivity:    0.7044724487274524 	 Specificity:    0.7183794466403162
Precision  : 0.7143573039338512
Area Under Curve:    0.7114259476838843
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5851 - accuracy: 0.6879 - val_loss: 0.5449 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7230 - val_loss: 0.5381 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7333 - val_loss: 0.5345 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7413 - val_loss: 0.5371 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7491 - val_loss: 0.5435 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7574 - val_loss: 0.5378 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7660 - val_loss: 0.5433 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4723 - accuracy: 0.7752 - val_loss: 0.5440 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4592 - accuracy: 0.7811 - val_loss: 0.5451 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4467 - accuracy: 0.7900 - val_loss: 0.5502 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4344 - accuracy: 0.7984 - val_loss: 0.5542 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4217 - accuracy: 0.8054
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4222 - accuracy: 0.8053 - val_loss: 0.5662 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 830us/step
Independent Testing Matthews Correlation:  0.40638659359950835
Confusion Matrix :
 [[2736 1311]
 [1094 2954]]
Accuracy on test set:    0.7029030265596047
Sensitivity:    0.7297430830039525 	 Specificity:    0.676056338028169
Precision  : 0.6926143024618991
Area Under Curve:    0.7028997105160608
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5852 - accuracy: 0.6849 - val_loss: 0.5478 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7220 - val_loss: 0.5348 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7341 - val_loss: 0.5336 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7428 - val_loss: 0.5313 - val_accuracy: 0.7315 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7488 - val_loss: 0.5313 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7590 - val_loss: 0.5410 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7671 - val_loss: 0.5389 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4680 - accuracy: 0.7759 - val_loss: 0.5452 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4538 - accuracy: 0.7839
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4542 - accuracy: 0.7836 - val_loss: 0.5438 - val_accuracy: 0.7226 - lr: 0.0010
253/253 [==============================] - 0s 851us/step
Independent Testing Matthews Correlation:  0.41865522221578483
Confusion Matrix :
 [[2876 1171]
 [1182 2866]]
Accuracy on test set:    0.7093267449042618
Sensitivity:    0.7080039525691699 	 Specificity:    0.7106498640968619
Precision  : 0.7099331186524647
Area Under Curve:    0.709326908333016
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5870 - accuracy: 0.6836 - val_loss: 0.5528 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7242 - val_loss: 0.5411 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7345 - val_loss: 0.5409 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5142 - accuracy: 0.7437 - val_loss: 0.5466 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5034 - accuracy: 0.7533 - val_loss: 0.5394 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.7619 - val_loss: 0.5457 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4751 - accuracy: 0.7709
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7704 - val_loss: 0.5460 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43506048948275894
Confusion Matrix :
 [[2687 1360]
 [ 936 3111]]
Accuracy on test set:    0.7163330862367185
Sensitivity:    0.7687175685693106 	 Specificity:    0.6639486039041265
Precision  : 0.6958174904942965
Area Under Curve:    0.7163330862367184
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5866 - accuracy: 0.6840 - val_loss: 0.5527 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7243 - val_loss: 0.5445 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7333 - val_loss: 0.5428 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7428 - val_loss: 0.5451 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7504 - val_loss: 0.5471 - val_accuracy: 0.7219 - lr: 0.0010

Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.7587 - val_loss: 0.5460 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4817 - accuracy: 0.7682 - val_loss: 0.5515 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7743 - val_loss: 0.5493 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4599 - accuracy: 0.7816 - val_loss: 0.5604 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4464 - accuracy: 0.7915 - val_loss: 0.5609 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4343 - accuracy: 0.7960 - val_loss: 0.5641 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4206 - accuracy: 0.8059 - val_loss: 0.5691 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 13/400
249/257 [============================>.] - ETA: 0s - loss: 0.4099 - accuracy: 0.8133
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4102 - accuracy: 0.8131 - val_loss: 0.5749 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 949us/step
Independent Testing Matthews Correlation:  0.4255007245513704
Confusion Matrix :
 [[2815 1232]
 [1094 2953]]
Accuracy on test set:    0.7126266370150729
Sensitivity:    0.729676303434643 	 Specificity:    0.6955769705955028
Precision  : 0.7056152927120669
Area Under Curve:    0.7126266370150729
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6828 - val_loss: 0.5503 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7242 - val_loss: 0.5421 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7352 - val_loss: 0.5422 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7435 - val_loss: 0.5401 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7489 - val_loss: 0.5438 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7562 - val_loss: 0.5464 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7641 - val_loss: 0.5466 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4754 - accuracy: 0.7727 - val_loss: 0.5463 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4640 - accuracy: 0.7794
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4643 - accuracy: 0.7793 - val_loss: 0.5468 - val_accuracy: 0.7234 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4368071558793058
Confusion Matrix :
 [[2793 1254]
 [1028 3019]]
Accuracy on test set:    0.7180627625401532
Sensitivity:    0.7459846800098838 	 Specificity:    0.6901408450704225
Precision  : 0.706529370465715
Area Under Curve:    0.7180627625401531
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5881 - accuracy: 0.6849 - val_loss: 0.5492 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7229 - val_loss: 0.5427 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7342 - val_loss: 0.5390 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7413 - val_loss: 0.5393 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7512 - val_loss: 0.5409 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7588 - val_loss: 0.5409 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7680 - val_loss: 0.5389 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7759 - val_loss: 0.5453 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4562 - accuracy: 0.7853 - val_loss: 0.5476 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4457 - accuracy: 0.7921 - val_loss: 0.5568 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4322 - accuracy: 0.8014 - val_loss: 0.5528 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4204 - accuracy: 0.8079 - val_loss: 0.5641 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4085 - accuracy: 0.8150 - val_loss: 0.5739 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 14/400
255/257 [============================>.] - ETA: 0s - loss: 0.3955 - accuracy: 0.8205
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3955 - accuracy: 0.8204 - val_loss: 0.5740 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43944290133143693
Confusion Matrix :
 [[2993 1054]
 [1216 2831]]
Accuracy on test set:    0.7195453422288115
Sensitivity:    0.6995305164319249 	 Specificity:    0.739560168025698
Precision  : 0.7287001287001287
Area Under Curve:    0.7195453422288114
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5888 - accuracy: 0.6840 - val_loss: 0.5505 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5482 - accuracy: 0.7217 - val_loss: 0.5443 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7319 - val_loss: 0.5426 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5232 - accuracy: 0.7384 - val_loss: 0.5438 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7456 - val_loss: 0.5438 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5019 - accuracy: 0.7552 - val_loss: 0.5449 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7612 - val_loss: 0.5478 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7682 - val_loss: 0.5543 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4699 - accuracy: 0.7755 - val_loss: 0.5534 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4570 - accuracy: 0.7843
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4571 - accuracy: 0.7843 - val_loss: 0.5585 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4734663844827584
Confusion Matrix :
 [[2959 1088]
 [1043 3004]]
Accuracy on test set:    0.7367185569557697
Sensitivity:    0.7422782307882382 	 Specificity:    0.7311588831233012
Precision  : 0.7341153470185728
Area Under Curve:    0.7367185569557696
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5918 - accuracy: 0.6809 - val_loss: 0.5530 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7194 - val_loss: 0.5466 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5340 - accuracy: 0.7307 - val_loss: 0.5461 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5238 - accuracy: 0.7379 - val_loss: 0.5418 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5121 - accuracy: 0.7459 - val_loss: 0.5444 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7546 - val_loss: 0.5469 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7636 - val_loss: 0.5452 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4793 - accuracy: 0.7712 - val_loss: 0.5475 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7801 - val_loss: 0.5552 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4533 - accuracy: 0.7855 - val_loss: 0.5651 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4417 - accuracy: 0.7946 - val_loss: 0.5577 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4270 - accuracy: 0.8031 - val_loss: 0.5735 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 13/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4154 - accuracy: 0.8099
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4165 - accuracy: 0.8090 - val_loss: 0.5684 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4774076115758723
Confusion Matrix :
 [[3102  945]
 [1173 2874]]
Accuracy on test set:    0.7383246849518161
Sensitivity:    0.7101556708673091 	 Specificity:    0.7664936990363233
Precision  : 0.7525530243519246
Area Under Curve:    0.7383246849518161
(8094, 2560) (8094,)
Mean MCC = 0.4329 + 0.0252 and Mean AUC = 0.7161 + 0.0126
Mean Sensitivity = 0.7277 + 0.0210 and Mean Specificity = 0.7045 + 0.0338 and Mean Accuracy = 0.7161 + 0.0126
Mean Precision = 0.7121 + 0.0203





Seed   : 278824
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5844 - accuracy: 0.6879 - val_loss: 0.5601 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5420 - accuracy: 0.7239 - val_loss: 0.5543 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.7348 - val_loss: 0.5506 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7422 - val_loss: 0.5495 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7495 - val_loss: 0.5546 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4928 - accuracy: 0.7584 - val_loss: 0.5602 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4804 - accuracy: 0.7685
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7682 - val_loss: 0.5563 - val_accuracy: 0.7109 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42393338105141587
Confusion Matrix :
 [[2775 1273]
 [1061 2986]]
Accuracy on test set:    0.7116738727609636
Sensitivity:    0.7378304917222634 	 Specificity:    0.6855237154150198
Precision  : 0.7011035454332003
Area Under Curve:    0.7116771035686417
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5891 - accuracy: 0.6831 - val_loss: 0.5582 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7236 - val_loss: 0.5500 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7339 - val_loss: 0.5476 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7427 - val_loss: 0.5459 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5038 - accuracy: 0.7504 - val_loss: 0.5505 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7596 - val_loss: 0.5523 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4779 - accuracy: 0.7687 - val_loss: 0.5565 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4665 - accuracy: 0.7773
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4663 - accuracy: 0.7774 - val_loss: 0.5612 - val_accuracy: 0.7119 - lr: 0.0010
253/253 [==============================] - 0s 997us/step
Independent Testing Matthews Correlation:  0.418574497220946
Confusion Matrix :
 [[2814 1234]
 [1120 2927]]
Accuracy on test set:    0.7092032118591723
Sensitivity:    0.7232517914504571 	 Specificity:    0.6951581027667985
Precision  : 0.703436673876472
Area Under Curve:    0.7092049471086277
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5873 - accuracy: 0.6860 - val_loss: 0.5481 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7227 - val_loss: 0.5413 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7327 - val_loss: 0.5408 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7426 - val_loss: 0.5486 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7500 - val_loss: 0.5440 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7598 - val_loss: 0.5526 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4804 - accuracy: 0.7661
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7665 - val_loss: 0.5480 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 739us/step
Independent Testing Matthews Correlation:  0.42522504402855266
Confusion Matrix :
 [[2771 1276]
 [1053 2995]]
Accuracy on test set:    0.7122915379864113
Sensitivity:    0.7398715415019763 	 Specificity:    0.6847047195453422
Precision  : 0.7012409271833294
Area Under Curve:    0.7122881305236592
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5862 - accuracy: 0.6865 - val_loss: 0.5468 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7216 - val_loss: 0.5432 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7328 - val_loss: 0.5384 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7389 - val_loss: 0.5402 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7492 - val_loss: 0.5413 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7542 - val_loss: 0.5438 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7650 - val_loss: 0.5499 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7736 - val_loss: 0.5435 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4587 - accuracy: 0.7816 - val_loss: 0.5532 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4459 - accuracy: 0.7904 - val_loss: 0.5522 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4322 - accuracy: 0.7999 - val_loss: 0.5623 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4182 - accuracy: 0.8094 - val_loss: 0.5714 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 13/400
256/257 [============================>.] - ETA: 0s - loss: 0.4067 - accuracy: 0.8143
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4067 - accuracy: 0.8143 - val_loss: 0.5795 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 970us/step
Independent Testing Matthews Correlation:  0.40817653066941456
Confusion Matrix :
 [[2665 1382]
 [1020 3028]]
Accuracy on test set:    0.7032736256948734
Sensitivity:    0.7480237154150198 	 Specificity:    0.6585124783790463
Precision  : 0.6866213151927437
Area Under Curve:    0.703268096897033
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5864 - accuracy: 0.6858 - val_loss: 0.5508 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7206 - val_loss: 0.5438 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7332 - val_loss: 0.5456 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7418 - val_loss: 0.5421 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5054 - accuracy: 0.7493 - val_loss: 0.5452 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7585 - val_loss: 0.5505 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4835 - accuracy: 0.7657
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7656 - val_loss: 0.5479 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4324371492276345
Confusion Matrix :
 [[2917 1130]
 [1167 2880]]
Accuracy on test set:    0.7162095379293304
Sensitivity:    0.7116382505559674 	 Specificity:    0.7207808253026934
Precision  : 0.7182044887780549
Area Under Curve:    0.7162095379293303
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6848 - val_loss: 0.5512 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7237 - val_loss: 0.5423 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7336 - val_loss: 0.5420 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7416 - val_loss: 0.5516 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7493 - val_loss: 0.5450 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7580 - val_loss: 0.5480 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7662 - val_loss: 0.5509 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4689 - accuracy: 0.7760
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4683 - accuracy: 0.7765 - val_loss: 0.5573 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 887us/step
Independent Testing Matthews Correlation:  0.4227846595715697
Confusion Matrix :
 [[2809 1238]
 [1099 2948]]
Accuracy on test set:    0.7112676056338029
Sensitivity:    0.7284408203607611 	 Specificity:    0.6940943909068445
Precision  : 0.7042522694696608
Area Under Curve:    0.7112676056338028
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5839 - accuracy: 0.6873 - val_loss: 0.5474 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7241 - val_loss: 0.5504 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7322 - val_loss: 0.5410 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7410 - val_loss: 0.5420 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7499 - val_loss: 0.5430 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7597 - val_loss: 0.5439 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7651 - val_loss: 0.5479 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4728 - accuracy: 0.7744
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4733 - accuracy: 0.7740 - val_loss: 0.5477 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4295949844805073
Confusion Matrix :
 [[2806 1241]
 [1069 2978]]
Accuracy on test set:    0.7146034099332839
Sensitivity:    0.7358537188040524 	 Specificity:    0.6933531010625155
Precision  : 0.7058544678833847
Area Under Curve:    0.7146034099332839
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6826 - val_loss: 0.5636 - val_accuracy: 0.7031 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7215 - val_loss: 0.5427 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7338 - val_loss: 0.5407 - val_accuracy: 0.7186 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7407 - val_loss: 0.5383 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7500 - val_loss: 0.5389 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7574 - val_loss: 0.5477 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7652 - val_loss: 0.5523 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4734 - accuracy: 0.7722 - val_loss: 0.5479 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4618 - accuracy: 0.7832 - val_loss: 0.5569 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4501 - accuracy: 0.7882
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4501 - accuracy: 0.7882 - val_loss: 0.5521 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4253461625880526
Confusion Matrix :
 [[3055  992]
 [1340 2707]]
Accuracy on test set:    0.7118853471707438
Sensitivity:    0.6688905361996541 	 Specificity:    0.7548801581418334
Precision  : 0.7318194106515274
Area Under Curve:    0.7118853471707438
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5919 - accuracy: 0.6804 - val_loss: 0.5492 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5477 - accuracy: 0.7203 - val_loss: 0.5412 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7331 - val_loss: 0.5400 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7414 - val_loss: 0.5413 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7492 - val_loss: 0.5432 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7581 - val_loss: 0.5430 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4844 - accuracy: 0.7667
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7665 - val_loss: 0.5463 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44172061474661106
Confusion Matrix :
 [[3026 1021]
 [1241 2806]]
Accuracy on test set:    0.720533728687917
Sensitivity:    0.6933531010625155 	 Specificity:    0.7477143563133185
Precision  : 0.7332113927358244
Area Under Curve:    0.720533728687917
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5945 - accuracy: 0.6806 - val_loss: 0.5566 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5519 - accuracy: 0.7195 - val_loss: 0.5470 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5373 - accuracy: 0.7300 - val_loss: 0.5430 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5260 - accuracy: 0.7374 - val_loss: 0.5413 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7438 - val_loss: 0.5447 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7501 - val_loss: 0.5462 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7594 - val_loss: 0.5596 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7672 - val_loss: 0.5508 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 9/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4714 - accuracy: 0.7757
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4718 - accuracy: 0.7756 - val_loss: 0.5523 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47501960544783883
Confusion Matrix :
 [[3026 1021]
 [1104 2943]]
Accuracy on test set:    0.7374598468000988
Sensitivity:    0.7272053372868792 	 Specificity:    0.7477143563133185
Precision  : 0.7424318869828456
Area Under Curve:    0.7374598468000989
(8094, 2560) (8094,)
Mean MCC = 0.4303 + 0.0171 and Mean AUC = 0.7148 + 0.0087
Mean Sensitivity = 0.7214 + 0.0229 and Mean Specificity = 0.7082 + 0.0310 and Mean Accuracy = 0.7148 + 0.0087
Mean Precision = 0.7128 + 0.0169





Seed   : 23276
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5830 - accuracy: 0.6888 - val_loss: 0.5568 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7226 - val_loss: 0.5495 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7338 - val_loss: 0.5500 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7402 - val_loss: 0.5500 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7484 - val_loss: 0.5512 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7580 - val_loss: 0.5557 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7653 - val_loss: 0.5608 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7731 - val_loss: 0.5597 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4595 - accuracy: 0.7832 - val_loss: 0.5600 - val_accuracy: 0.7049 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4478 - accuracy: 0.7905
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4478 - accuracy: 0.7905 - val_loss: 0.5671 - val_accuracy: 0.7045 - lr: 0.0010
253/253 [==============================] - 0s 912us/step
Independent Testing Matthews Correlation:  0.4239173019254762
Confusion Matrix :
 [[2706 1342]
 [ 996 3051]]
Accuracy on test set:    0.7111797405806053
Sensitivity:    0.7538917716827279 	 Specificity:    0.6684782608695652
Precision  : 0.6945139995447303
Area Under Curve:    0.7111850162761465
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5897 - accuracy: 0.6823 - val_loss: 0.5556 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7239 - val_loss: 0.5515 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7348 - val_loss: 0.5556 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7440 - val_loss: 0.5452 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7482 - val_loss: 0.5474 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7581 - val_loss: 0.5477 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7629 - val_loss: 0.5476 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4777 - accuracy: 0.7700 - val_loss: 0.5570 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4648 - accuracy: 0.7775 - val_loss: 0.5596 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4531 - accuracy: 0.7867 - val_loss: 0.5548 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 11/400
256/257 [============================>.] - ETA: 0s - loss: 0.4425 - accuracy: 0.7925
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4425 - accuracy: 0.7925 - val_loss: 0.5655 - val_accuracy: 0.7145 - lr: 0.0010
253/253 [==============================] - 0s 761us/step
Independent Testing Matthews Correlation:  0.4173749304136406
Confusion Matrix :
 [[2714 1334]
 [1029 3018]]
Accuracy on test set:    0.7080914144533663
Sensitivity:    0.7457375833951075 	 Specificity:    0.6704545454545454
Precision  : 0.6934742647058824
Area Under Curve:    0.7080960644248264
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5845 - accuracy: 0.6860 - val_loss: 0.5472 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5419 - accuracy: 0.7228 - val_loss: 0.5412 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7344 - val_loss: 0.5387 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7411 - val_loss: 0.5415 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7485 - val_loss: 0.5433 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4970 - accuracy: 0.7580 - val_loss: 0.5385 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7646 - val_loss: 0.5435 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7727 - val_loss: 0.5459 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4624 - accuracy: 0.7816 - val_loss: 0.5596 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4497 - accuracy: 0.7892 - val_loss: 0.5530 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4368 - accuracy: 0.7983 - val_loss: 0.5596 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 12/400
249/257 [============================>.] - ETA: 0s - loss: 0.4218 - accuracy: 0.8079
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4223 - accuracy: 0.8077 - val_loss: 0.5620 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 826us/step
Independent Testing Matthews Correlation:  0.43028070208957564
Confusion Matrix :
 [[2683 1364]
 [ 951 3097]]
Accuracy on test set:    0.7140210006176653
Sensitivity:    0.7650691699604744 	 Specificity:    0.662960217445021
Precision  : 0.6942389598744676
Area Under Curve:    0.7140146937027476
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5878 - accuracy: 0.6831 - val_loss: 0.5448 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7223 - val_loss: 0.5383 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7318 - val_loss: 0.5374 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.7385 - val_loss: 0.5345 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5123 - accuracy: 0.7465 - val_loss: 0.5385 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5006 - accuracy: 0.7533 - val_loss: 0.5384 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4895 - accuracy: 0.7606
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.7605 - val_loss: 0.5435 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 792us/step
Independent Testing Matthews Correlation:  0.4270297335307513
Confusion Matrix :
 [[2624 1423]
 [ 910 3138]]
Accuracy on test set:    0.7117974058060531
Sensitivity:    0.775197628458498 	 Specificity:    0.6483815171732147
Precision  : 0.688007016005262
Area Under Curve:    0.7117895728158564
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5874 - accuracy: 0.6857 - val_loss: 0.5500 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7239 - val_loss: 0.5462 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7334 - val_loss: 0.5433 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7402 - val_loss: 0.5510 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7479 - val_loss: 0.5450 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7568 - val_loss: 0.5455 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7644 - val_loss: 0.5522 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4725 - accuracy: 0.7730 - val_loss: 0.5529 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4604 - accuracy: 0.7815 - val_loss: 0.5489 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4468 - accuracy: 0.7897 - val_loss: 0.5527 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4338 - accuracy: 0.7985 - val_loss: 0.5609 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4206 - accuracy: 0.8056 - val_loss: 0.5670 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 13/400
256/257 [============================>.] - ETA: 0s - loss: 0.4071 - accuracy: 0.8124
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4071 - accuracy: 0.8123 - val_loss: 0.5717 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 976us/step
Independent Testing Matthews Correlation:  0.41855265007028625
Confusion Matrix :
 [[2751 1296]
 [1060 2987]]
Accuracy on test set:    0.7089201877934272
Sensitivity:    0.7380775883370397 	 Specificity:    0.6797627872498146
Precision  : 0.6974083586271305
Area Under Curve:    0.7089201877934271
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5885 - accuracy: 0.6822 - val_loss: 0.5527 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7236 - val_loss: 0.5437 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7335 - val_loss: 0.5428 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7398 - val_loss: 0.5422 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7484 - val_loss: 0.5423 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7558 - val_loss: 0.5475 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.7632 - val_loss: 0.5522 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4733 - accuracy: 0.7728 - val_loss: 0.5500 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4600 - accuracy: 0.7824
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4600 - accuracy: 0.7824 - val_loss: 0.5492 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 914us/step
Independent Testing Matthews Correlation:  0.4337508364771548
Confusion Matrix :
 [[2981 1066]
 [1227 2820]]
Accuracy on test set:    0.7167037311588831
Sensitivity:    0.6968124536693847 	 Specificity:    0.7365950086483816
Precision  : 0.7256819351518271
Area Under Curve:    0.7167037311588831
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5907 - accuracy: 0.6803 - val_loss: 0.5510 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7198 - val_loss: 0.5490 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7313 - val_loss: 0.5420 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5219 - accuracy: 0.7390 - val_loss: 0.5438 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5123 - accuracy: 0.7454 - val_loss: 0.5418 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7518 - val_loss: 0.5424 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.7600 - val_loss: 0.5452 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4840 - accuracy: 0.7664
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7660 - val_loss: 0.5483 - val_accuracy: 0.7248 - lr: 0.0010
253/253 [==============================] - 0s 906us/step
Independent Testing Matthews Correlation:  0.42821676974806033
Confusion Matrix :
 [[2821 1226]
 [1089 2958]]
Accuracy on test set:    0.7139856683963429
Sensitivity:    0.7309117865085248 	 Specificity:    0.6970595502841611
Precision  : 0.7069789674952199
Area Under Curve:    0.7139856683963429
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6856 - val_loss: 0.5543 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7229 - val_loss: 0.5431 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7333 - val_loss: 0.5388 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7415 - val_loss: 0.5376 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7496 - val_loss: 0.5388 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7597 - val_loss: 0.5404 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7669 - val_loss: 0.5409 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4686 - accuracy: 0.7769 - val_loss: 0.5422 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4539 - accuracy: 0.7860 - val_loss: 0.5441 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4409 - accuracy: 0.7938 - val_loss: 0.5481 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4291 - accuracy: 0.8004 - val_loss: 0.5551 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4136 - accuracy: 0.8110 - val_loss: 0.5639 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4010 - accuracy: 0.8193 - val_loss: 0.5637 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 14/400
248/257 [===========================>..] - ETA: 0s - loss: 0.3872 - accuracy: 0.8266
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3875 - accuracy: 0.8263 - val_loss: 0.5768 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41060781827720044
Confusion Matrix :
 [[2988 1059]
 [1330 2717]]
Accuracy on test set:    0.704843093649617
Sensitivity:    0.6713615023474179 	 Specificity:    0.7383246849518161
Precision  : 0.7195444915254238
Area Under Curve:    0.7048430936496171
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5895 - accuracy: 0.6826 - val_loss: 0.5548 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7213 - val_loss: 0.5437 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7304 - val_loss: 0.5452 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5222 - accuracy: 0.7401 - val_loss: 0.5432 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5110 - accuracy: 0.7459 - val_loss: 0.5429 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.7530 - val_loss: 0.5414 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7618 - val_loss: 0.5445 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4785 - accuracy: 0.7710 - val_loss: 0.5428 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.7790 - val_loss: 0.5472 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4543 - accuracy: 0.7857 - val_loss: 0.5484 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7933 - val_loss: 0.5576 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 12/400
252/257 [============================>.] - ETA: 0s - loss: 0.4270 - accuracy: 0.8024
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4271 - accuracy: 0.8025 - val_loss: 0.5629 - val_accuracy: 0.7226 - lr: 0.0010
253/253 [==============================] - 0s 880us/step
Independent Testing Matthews Correlation:  0.4571951934587706
Confusion Matrix :
 [[2914 1133]
 [1064 2983]]
Accuracy on test set:    0.7285643686681492
Sensitivity:    0.7370892018779343 	 Specificity:    0.7200395354583642
Precision  : 0.7247327502429544
Area Under Curve:    0.7285643686681491
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5968 - accuracy: 0.6781 - val_loss: 0.5541 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5533 - accuracy: 0.7171 - val_loss: 0.5461 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5386 - accuracy: 0.7285 - val_loss: 0.5435 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7341 - val_loss: 0.5399 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7452 - val_loss: 0.5428 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7515 - val_loss: 0.5423 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7585 - val_loss: 0.5507 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4841 - accuracy: 0.7665 - val_loss: 0.5453 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4695 - accuracy: 0.7767 - val_loss: 0.5502 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4576 - accuracy: 0.7836
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4577 - accuracy: 0.7836 - val_loss: 0.5574 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4788774644467457
Confusion Matrix :
 [[3001 1046]
 [1063 2984]]
Accuracy on test set:    0.7394366197183099
Sensitivity:    0.7373362984927107 	 Specificity:    0.7415369409439091
Precision  : 0.7404466501240695
Area Under Curve:    0.7394366197183099
(8094, 2560) (8094,)
Mean MCC = 0.4326 + 0.0195 and Mean AUC = 0.7158 + 0.0100
Mean Sensitivity = 0.7351 + 0.0292 and Mean Specificity = 0.6964 + 0.0334 and Mean Accuracy = 0.7158 + 0.0100
Mean Precision = 0.7085 + 0.0169





Seed   : 89684
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5853 - accuracy: 0.6873 - val_loss: 0.5575 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5418 - accuracy: 0.7268 - val_loss: 0.5540 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5251 - accuracy: 0.7363 - val_loss: 0.5477 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5139 - accuracy: 0.7452 - val_loss: 0.5482 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5011 - accuracy: 0.7556 - val_loss: 0.5476 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4890 - accuracy: 0.7626 - val_loss: 0.5481 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4758 - accuracy: 0.7721 - val_loss: 0.5546 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4634 - accuracy: 0.7792 - val_loss: 0.5573 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4507 - accuracy: 0.7872 - val_loss: 0.5648 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4369 - accuracy: 0.7984 - val_loss: 0.5675 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4238 - accuracy: 0.8064 - val_loss: 0.5781 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4118 - accuracy: 0.8116 - val_loss: 0.5769 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 13/400
246/257 [===========================>..] - ETA: 0s - loss: 0.3993 - accuracy: 0.8189
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4004 - accuracy: 0.8181 - val_loss: 0.5805 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39329605504119636
Confusion Matrix :
 [[2777 1271]
 [1185 2862]]
Accuracy on test set:    0.696602841260037
Sensitivity:    0.7071905114899926 	 Specificity:    0.6860177865612648
Precision  : 0.692475199612872
Area Under Curve:    0.6966041490256287
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5858 - accuracy: 0.6862 - val_loss: 0.5563 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5417 - accuracy: 0.7253 - val_loss: 0.5497 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5258 - accuracy: 0.7350 - val_loss: 0.5470 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5133 - accuracy: 0.7453 - val_loss: 0.5472 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5011 - accuracy: 0.7528 - val_loss: 0.5471 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4899 - accuracy: 0.7622 - val_loss: 0.5547 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4789 - accuracy: 0.7705
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4791 - accuracy: 0.7705 - val_loss: 0.5577 - val_accuracy: 0.7141 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4220136969545217
Confusion Matrix :
 [[2932 1116]
 [1224 2823]]
Accuracy on test set:    0.7109326744904262
Sensitivity:    0.6975537435137139 	 Specificity:    0.724308300395257
Precision  : 0.7166793602437167
Area Under Curve:    0.7109310219544853
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5848 - accuracy: 0.6857 - val_loss: 0.5565 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7234 - val_loss: 0.5410 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7343 - val_loss: 0.5360 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7442 - val_loss: 0.5361 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7501 - val_loss: 0.5367 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7579 - val_loss: 0.5447 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400

257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7660 - val_loss: 0.5402 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4718 - accuracy: 0.7751
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.7748 - val_loss: 0.5415 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42290268593014363
Confusion Matrix :
 [[2735 1312]
 [1028 3020]]
Accuracy on test set:    0.7109326744904262
Sensitivity:    0.7460474308300395 	 Specificity:    0.6758092414133926
Precision  : 0.6971375807940905
Area Under Curve:    0.7109283361217161
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5896 - accuracy: 0.6805 - val_loss: 0.5454 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7247 - val_loss: 0.5395 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7331 - val_loss: 0.5335 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7415 - val_loss: 0.5368 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7487 - val_loss: 0.5366 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7551 - val_loss: 0.5347 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7623 - val_loss: 0.5423 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4756 - accuracy: 0.7718
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7716 - val_loss: 0.5451 - val_accuracy: 0.7193 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42160916709908514
Confusion Matrix :
 [[2592 1455]
 [ 902 3146]]
Accuracy on test set:    0.7088326127239036
Sensitivity:    0.7771739130434783 	 Specificity:    0.6404744255003706
Precision  : 0.6837643990436861
Area Under Curve:    0.7088241692719245
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5896 - accuracy: 0.6825 - val_loss: 0.5508 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7214 - val_loss: 0.5434 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7325 - val_loss: 0.5397 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7396 - val_loss: 0.5384 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7482 - val_loss: 0.5402 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7555 - val_loss: 0.5412 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4865 - accuracy: 0.7644
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4867 - accuracy: 0.7644 - val_loss: 0.5456 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 964us/step
Independent Testing Matthews Correlation:  0.43236848532297345
Confusion Matrix :
 [[2837 1210]
 [1088 2959]]
Accuracy on test set:    0.7160859896219421
Sensitivity:    0.7311588831233012 	 Specificity:    0.7010130961205832
Precision  : 0.7097625329815304
Area Under Curve:    0.7160859896219423
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5941 - accuracy: 0.6790 - val_loss: 0.5539 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5502 - accuracy: 0.7204 - val_loss: 0.5485 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5361 - accuracy: 0.7287 - val_loss: 0.5426 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5260 - accuracy: 0.7369 - val_loss: 0.5407 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7432 - val_loss: 0.5423 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7506 - val_loss: 0.5456 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7555 - val_loss: 0.5495 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.7628 - val_loss: 0.5501 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4748 - accuracy: 0.7717
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4752 - accuracy: 0.7714 - val_loss: 0.5562 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42819966744139054
Confusion Matrix :
 [[2771 1276]
 [1041 3006]]
Accuracy on test set:    0.7137385717815666
Sensitivity:    0.742772424017791 	 Specificity:    0.6847047195453422
Precision  : 0.7020084072863149
Area Under Curve:    0.7137385717815666
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5820 - accuracy: 0.6896 - val_loss: 0.5471 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5413 - accuracy: 0.7244 - val_loss: 0.5422 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5256 - accuracy: 0.7368 - val_loss: 0.5364 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7452 - val_loss: 0.5412 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7537 - val_loss: 0.5366 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7596 - val_loss: 0.5398 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7685 - val_loss: 0.5421 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4670 - accuracy: 0.7788
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4671 - accuracy: 0.7787 - val_loss: 0.5457 - val_accuracy: 0.7242 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4246485828169436
Confusion Matrix :
 [[2796 1251]
 [1079 2968]]
Accuracy on test set:    0.7121324437855201
Sensitivity:    0.7333827526562886 	 Specificity:    0.6908821349147517
Precision  : 0.7034842379710832
Area Under Curve:    0.7121324437855201
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5883 - accuracy: 0.6828 - val_loss: 0.5461 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7220 - val_loss: 0.5466 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7310 - val_loss: 0.5343 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7406 - val_loss: 0.5352 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.7475 - val_loss: 0.5417 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7577 - val_loss: 0.5380 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.7657 - val_loss: 0.5393 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4728 - accuracy: 0.7745
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4725 - accuracy: 0.7744 - val_loss: 0.5483 - val_accuracy: 0.7237 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4404544182241628
Confusion Matrix :
 [[2623 1424]
 [ 858 3189]]
Accuracy on test set:    0.7180627625401532
Sensitivity:    0.787991104521868 	 Specificity:    0.6481344205584384
Precision  : 0.6913071753739432
Area Under Curve:    0.718062762540153
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5905 - accuracy: 0.6817 - val_loss: 0.5498 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5486 - accuracy: 0.7196 - val_loss: 0.5466 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7300 - val_loss: 0.5448 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7382 - val_loss: 0.5440 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5133 - accuracy: 0.7438 - val_loss: 0.5536 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
251/257 [============================>.] - ETA: 0s - loss: 0.5031 - accuracy: 0.7533
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7533 - val_loss: 0.5453 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46662600099084206
Confusion Matrix :
 [[3088  959]
 [1203 2844]]
Accuracy on test set:    0.7328885594267358
Sensitivity:    0.7027427724240178 	 Specificity:    0.7630343464294539
Precision  : 0.747830660005259
Area Under Curve:    0.7328885594267358
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5913 - accuracy: 0.6832 - val_loss: 0.5550 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5494 - accuracy: 0.7182 - val_loss: 0.5486 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5345 - accuracy: 0.7322 - val_loss: 0.5507 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5227 - accuracy: 0.7389 - val_loss: 0.5488 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7460 - val_loss: 0.5459 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7556 - val_loss: 0.5461 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4872 - accuracy: 0.7641 - val_loss: 0.5469 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4759 - accuracy: 0.7713 - val_loss: 0.5507 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4639 - accuracy: 0.7779 - val_loss: 0.5567 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4525 - accuracy: 0.7865 - val_loss: 0.5646 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 11/400
256/257 [============================>.] - ETA: 0s - loss: 0.4381 - accuracy: 0.7955
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4381 - accuracy: 0.7955 - val_loss: 0.5630 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4581396692876559
Confusion Matrix :
 [[3166  881]
 [1323 2724]]
Accuracy on test set:    0.7276995305164319
Sensitivity:    0.6730911786508524 	 Specificity:    0.7823078823820113
Precision  : 0.7556171983356449
Area Under Curve:    0.7276995305164319
(8094, 2560) (8094,)
Mean MCC = 0.4310 + 0.0195 and Mean AUC = 0.7148 + 0.0095
Mean Sensitivity = 0.7299 + 0.0340 and Mean Specificity = 0.6997 + 0.0432 and Mean Accuracy = 0.7148 + 0.0095
Mean Precision = 0.7100 + 0.0227





Seed   : 857674
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5870 - accuracy: 0.6837 - val_loss: 0.5591 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7242 - val_loss: 0.5472 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7352 - val_loss: 0.5441 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5150 - accuracy: 0.7447 - val_loss: 0.5479 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5018 - accuracy: 0.7523 - val_loss: 0.5438 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4905 - accuracy: 0.7613 - val_loss: 0.5483 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7692 - val_loss: 0.5514 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4662 - accuracy: 0.7768 - val_loss: 0.5550 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 9/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4544 - accuracy: 0.7848
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4541 - accuracy: 0.7850 - val_loss: 0.5622 - val_accuracy: 0.7102 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4023787663375259
Confusion Matrix :
 [[2712 1336]
 [1086 2961]]
Accuracy on test set:    0.7008029647930821
Sensitivity:    0.7316530763528539 	 Specificity:    0.6699604743083004
Precision  : 0.6890854084244822
Area Under Curve:    0.7008067753305771
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5861 - accuracy: 0.6867 - val_loss: 0.5573 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5432 - accuracy: 0.7257 - val_loss: 0.5513 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7365 - val_loss: 0.5523 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7437 - val_loss: 0.5527 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 5/400

257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7510 - val_loss: 0.5560 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7564 - val_loss: 0.5566 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7642 - val_loss: 0.5537 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4718 - accuracy: 0.7747
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4716 - accuracy: 0.7748 - val_loss: 0.5563 - val_accuracy: 0.7054 - lr: 0.0010
253/253 [==============================] - 0s 900us/step
Independent Testing Matthews Correlation:  0.40558953151065225
Confusion Matrix :
 [[2770 1278]
 [1129 2918]]
Accuracy on test set:    0.7026559604694256
Sensitivity:    0.7210279219174698 	 Specificity:    0.6842885375494071
Precision  : 0.6954242135367016
Area Under Curve:    0.7026582297334385
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5843 - accuracy: 0.6876 - val_loss: 0.5491 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5419 - accuracy: 0.7253 - val_loss: 0.5381 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5268 - accuracy: 0.7349 - val_loss: 0.5411 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5150 - accuracy: 0.7451 - val_loss: 0.5338 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7522 - val_loss: 0.5366 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7580 - val_loss: 0.5411 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4811 - accuracy: 0.7689 - val_loss: 0.5375 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.7768 - val_loss: 0.5432 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4574 - accuracy: 0.7833 - val_loss: 0.5505 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4453 - accuracy: 0.7915 - val_loss: 0.5468 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4325 - accuracy: 0.7981 - val_loss: 0.5540 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - ETA: 0s - loss: 0.4228 - accuracy: 0.8046
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4228 - accuracy: 0.8046 - val_loss: 0.5698 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40211264566821375
Confusion Matrix :
 [[2619 1428]
 [1001 3047]]
Accuracy on test set:    0.6999382334774552
Sensitivity:    0.7527173913043478 	 Specificity:    0.6471460340993328
Precision  : 0.6808938547486033
Area Under Curve:    0.6999317127018404
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5863 - accuracy: 0.6865 - val_loss: 0.5445 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7220 - val_loss: 0.5358 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7348 - val_loss: 0.5331 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7419 - val_loss: 0.5330 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7481 - val_loss: 0.5348 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7568 - val_loss: 0.5352 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7647 - val_loss: 0.5394 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4724 - accuracy: 0.7735
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7734 - val_loss: 0.5429 - val_accuracy: 0.7252 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4406531956325495
Confusion Matrix :
 [[2795 1252]
 [1015 3033]]
Accuracy on test set:    0.7199505867819642
Sensitivity:    0.7492588932806324 	 Specificity:    0.6906350382999753
Precision  : 0.7078179696616103
Area Under Curve:    0.7199469657903038
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5840 - accuracy: 0.6881 - val_loss: 0.5527 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7228 - val_loss: 0.5391 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7351 - val_loss: 0.5389 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7431 - val_loss: 0.5413 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7483 - val_loss: 0.5392 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7547 - val_loss: 0.5390 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7655 - val_loss: 0.5433 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.7726 - val_loss: 0.5459 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4599 - accuracy: 0.7804
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4604 - accuracy: 0.7802 - val_loss: 0.5553 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 937us/step
Independent Testing Matthews Correlation:  0.41780075288357976
Confusion Matrix :
 [[2594 1453]
 [ 918 3129]]
Accuracy on test set:    0.7070669631826044
Sensitivity:    0.7731653076352853 	 Specificity:    0.6409686187299234
Precision  : 0.6828895678742907
Area Under Curve:    0.7070669631826044
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5876 - accuracy: 0.6858 - val_loss: 0.5594 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7217 - val_loss: 0.5502 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7337 - val_loss: 0.5474 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7412 - val_loss: 0.5491 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7485 - val_loss: 0.5597 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7575 - val_loss: 0.5495 - val_accuracy: 0.7207 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.7622 - val_loss: 0.5651 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.7728 - val_loss: 0.5564 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4620 - accuracy: 0.7819
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4623 - accuracy: 0.7818 - val_loss: 0.5608 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4311849091239686
Confusion Matrix :
 [[2891 1156]
 [1146 2901]]
Accuracy on test set:    0.7155917963923895
Sensitivity:    0.7168272794662713 	 Specificity:    0.7143563133185076
Precision  : 0.7150603894503328
Area Under Curve:    0.7155917963923895
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5923 - accuracy: 0.6813 - val_loss: 0.5549 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7220 - val_loss: 0.5473 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7312 - val_loss: 0.5440 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5211 - accuracy: 0.7400 - val_loss: 0.5437 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.7504 - val_loss: 0.5442 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.7561 - val_loss: 0.5514 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.7629 - val_loss: 0.5490 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7724 - val_loss: 0.5553 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4620 - accuracy: 0.7802
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4622 - accuracy: 0.7802 - val_loss: 0.5562 - val_accuracy: 0.7245 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4205488728731317
Confusion Matrix :
 [[2942 1105]
 [1241 2806]]
Accuracy on test set:    0.7101556708673091
Sensitivity:    0.6933531010625155 	 Specificity:    0.7269582406721028
Precision  : 0.7174635643058042
Area Under Curve:    0.710155670867309
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5854 - accuracy: 0.6859 - val_loss: 0.5535 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7232 - val_loss: 0.5442 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7326 - val_loss: 0.5431 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7424 - val_loss: 0.5424 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7475 - val_loss: 0.5451 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4980 - accuracy: 0.7555 - val_loss: 0.5489 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4867 - accuracy: 0.7652 - val_loss: 0.5462 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4740 - accuracy: 0.7723 - val_loss: 0.5502 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4632 - accuracy: 0.7793
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4631 - accuracy: 0.7794 - val_loss: 0.5545 - val_accuracy: 0.7152 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4448630200848229
Confusion Matrix :
 [[2964 1083]
 [1164 2883]]
Accuracy on test set:    0.7223869532987398
Sensitivity:    0.7123795404002965 	 Specificity:    0.7323943661971831
Precision  : 0.726928895612708
Area Under Curve:    0.7223869532987397
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5893 - accuracy: 0.6819 - val_loss: 0.5592 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7216 - val_loss: 0.5526 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5326 - accuracy: 0.7310 - val_loss: 0.5494 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7392 - val_loss: 0.5499 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5130 - accuracy: 0.7456 - val_loss: 0.5468 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5027 - accuracy: 0.7532 - val_loss: 0.5478 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4911 - accuracy: 0.7616 - val_loss: 0.5503 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7698 - val_loss: 0.5532 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4667 - accuracy: 0.7784 - val_loss: 0.5642 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4550 - accuracy: 0.7856 - val_loss: 0.5709 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4428 - accuracy: 0.7945
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4431 - accuracy: 0.7944 - val_loss: 0.5721 - val_accuracy: 0.7117 - lr: 0.0010
253/253 [==============================] - 0s 877us/step
Independent Testing Matthews Correlation:  0.4531650315241731
Confusion Matrix :
 [[3033 1014]
 [1201 2846]]
Accuracy on test set:    0.7263404991351619
Sensitivity:    0.7032369656535705 	 Specificity:    0.7494440326167532
Precision  : 0.7373056994818653
Area Under Curve:    0.7263404991351617
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5918 - accuracy: 0.6805 - val_loss: 0.5650 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5493 - accuracy: 0.7199 - val_loss: 0.5540 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5340 - accuracy: 0.7324 - val_loss: 0.5524 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5216 - accuracy: 0.7406 - val_loss: 0.5506 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7501 - val_loss: 0.5528 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.7574 - val_loss: 0.5594 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4857 - accuracy: 0.7629 - val_loss: 0.5595 - val_accuracy: 0.7160 - lr: 0.0010

Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4714 - accuracy: 0.7748 - val_loss: 0.5649 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4585 - accuracy: 0.7831 - val_loss: 0.5643 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4446 - accuracy: 0.7923 - val_loss: 0.5733 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4321 - accuracy: 0.7987 - val_loss: 0.5789 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4188 - accuracy: 0.8066 - val_loss: 0.5829 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4082 - accuracy: 0.8129 - val_loss: 0.5923 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 14/400
254/257 [============================>.] - ETA: 0s - loss: 0.3956 - accuracy: 0.8209
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3957 - accuracy: 0.8208 - val_loss: 0.6001 - val_accuracy: 0.7117 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.46202186084106583
Confusion Matrix :
 [[3249  798]
 [1400 2647]]
Accuracy on test set:    0.7284408203607611
Sensitivity:    0.6540647393130714 	 Specificity:    0.8028169014084507
Precision  : 0.7683599419448476
Area Under Curve:    0.7284408203607611
(8094, 2560) (8094,)
Mean MCC = 0.4280 + 0.0206 and Mean AUC = 0.7133 + 0.0101
Mean Sensitivity = 0.7208 + 0.0321 and Mean Specificity = 0.7059 + 0.0471 and Mean Accuracy = 0.7133 + 0.0101
Mean Precision = 0.7121 + 0.0259





Seed   : 672996
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5842 - accuracy: 0.6863 - val_loss: 0.5619 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5409 - accuracy: 0.7235 - val_loss: 0.5546 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5245 - accuracy: 0.7364 - val_loss: 0.5583 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.7450 - val_loss: 0.5547 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7522 - val_loss: 0.5573 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4899 - accuracy: 0.7616 - val_loss: 0.5584 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4773 - accuracy: 0.7685 - val_loss: 0.5700 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4653 - accuracy: 0.7780
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4653 - accuracy: 0.7780 - val_loss: 0.5662 - val_accuracy: 0.7078 - lr: 0.0010
253/253 [==============================] - 0s 948us/step
Independent Testing Matthews Correlation:  0.4086509261231474
Confusion Matrix :
 [[2718 1330]
 [1067 2980]]
Accuracy on test set:    0.7038912909203212
Sensitivity:    0.7363479120336052 	 Specificity:    0.6714426877470355
Precision  : 0.691415313225058
Area Under Curve:    0.7038952998903204
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5848 - accuracy: 0.6866 - val_loss: 0.5624 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7243 - val_loss: 0.5581 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7355 - val_loss: 0.5573 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7450 - val_loss: 0.5558 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5024 - accuracy: 0.7529 - val_loss: 0.5596 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7626 - val_loss: 0.5570 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4763 - accuracy: 0.7708 - val_loss: 0.5592 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4659 - accuracy: 0.7774 - val_loss: 0.5611 - val_accuracy: 0.7040 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4506 - accuracy: 0.7885
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4513 - accuracy: 0.7880 - val_loss: 0.5636 - val_accuracy: 0.7089 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41671094183412444
Confusion Matrix :
 [[2842 1206]
 [1155 2892]]
Accuracy on test set:    0.7083384805435454
Sensitivity:    0.7146034099332839 	 Specificity:    0.7020750988142292
Precision  : 0.705710102489019
Area Under Curve:    0.7083392543737566
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5880 - accuracy: 0.6839 - val_loss: 0.5513 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7212 - val_loss: 0.5429 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7331 - val_loss: 0.5440 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7415 - val_loss: 0.5406 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7469 - val_loss: 0.5433 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7553 - val_loss: 0.5498 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4885 - accuracy: 0.7639
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4887 - accuracy: 0.7637 - val_loss: 0.5473 - val_accuracy: 0.7172 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42873539821416884
Confusion Matrix :
 [[2649 1398]
 [ 926 3122]]
Accuracy on test set:    0.7129092032118591
Sensitivity:    0.7712450592885376 	 Specificity:    0.6545589325426242
Precision  : 0.6907079646017699
Area Under Curve:    0.7129019959155809
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5916 - accuracy: 0.6803 - val_loss: 0.5477 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7204 - val_loss: 0.5419 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7318 - val_loss: 0.5378 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5210 - accuracy: 0.7402 - val_loss: 0.5371 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7470 - val_loss: 0.5440 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.7534 - val_loss: 0.5470 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4897 - accuracy: 0.7635 - val_loss: 0.5415 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4752 - accuracy: 0.7717 - val_loss: 0.5465 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4615 - accuracy: 0.7811
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4615 - accuracy: 0.7811 - val_loss: 0.5481 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 985us/step
Independent Testing Matthews Correlation:  0.41357972314130237
Confusion Matrix :
 [[2812 1235]
 [1139 2909]]
Accuracy on test set:    0.7067325509573811
Sensitivity:    0.7186264822134387 	 Specificity:    0.6948356807511737
Precision  : 0.7019787644787645
Area Under Curve:    0.7067310814823062
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5875 - accuracy: 0.6860 - val_loss: 0.5543 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7223 - val_loss: 0.5444 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7330 - val_loss: 0.5497 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7406 - val_loss: 0.5449 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7492 - val_loss: 0.5436 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7582 - val_loss: 0.5482 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - ETA: 0s - loss: 0.4812 - accuracy: 0.7673
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7673 - val_loss: 0.5544 - val_accuracy: 0.7167 - lr: 0.0010
253/253 [==============================] - 0s 920us/step
Independent Testing Matthews Correlation:  0.4250520216021716
Confusion Matrix :
 [[2724 1323]
 [1009 3038]]
Accuracy on test set:    0.7118853471707438
Sensitivity:    0.7506795156906351 	 Specificity:    0.6730911786508524
Precision  : 0.6966292134831461
Area Under Curve:    0.7118853471707437
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5838 - accuracy: 0.6872 - val_loss: 0.5511 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7227 - val_loss: 0.5500 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5255 - accuracy: 0.7356 - val_loss: 0.5459 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5139 - accuracy: 0.7435 - val_loss: 0.5438 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7537 - val_loss: 0.5443 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4911 - accuracy: 0.7610 - val_loss: 0.5468 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.7698 - val_loss: 0.5538 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4645 - accuracy: 0.7785
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4646 - accuracy: 0.7784 - val_loss: 0.5493 - val_accuracy: 0.7172 - lr: 0.0010
253/253 [==============================] - 0s 859us/step
Independent Testing Matthews Correlation:  0.44205235003691956
Confusion Matrix :
 [[2781 1266]
 [ 996 3051]]
Accuracy on test set:    0.720533728687917
Sensitivity:    0.7538917716827279 	 Specificity:    0.687175685693106
Precision  : 0.7067407922168172
Area Under Curve:    0.7205337286879169
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5843 - accuracy: 0.6864 - val_loss: 0.5505 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7237 - val_loss: 0.5418 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7335 - val_loss: 0.5430 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7432 - val_loss: 0.5427 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7506 - val_loss: 0.5467 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7574 - val_loss: 0.5623 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7674 - val_loss: 0.5521 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4711 - accuracy: 0.7749
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7749 - val_loss: 0.5541 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4308936809685184
Confusion Matrix :
 [[2700 1347]
 [ 964 3083]]
Accuracy on test set:    0.7144798616258957
Sensitivity:    0.761798863355572 	 Specificity:    0.6671608598962194
Precision  : 0.6959367945823928
Area Under Curve:    0.7144798616258957
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5861 - accuracy: 0.6866 - val_loss: 0.5457 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7216 - val_loss: 0.5429 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7336 - val_loss: 0.5411 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7415 - val_loss: 0.5391 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7508 - val_loss: 0.5395 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4986 - accuracy: 0.7568 - val_loss: 0.5420 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7642 - val_loss: 0.5453 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4732 - accuracy: 0.7740 - val_loss: 0.5478 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4625 - accuracy: 0.7818
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4624 - accuracy: 0.7817 - val_loss: 0.5618 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43266617247343714
Confusion Matrix :
 [[2899 1148]
 [1148 2899]]
Accuracy on test set:    0.7163330862367185
Sensitivity:    0.7163330862367185 	 Specificity:    0.7163330862367185
Precision  : 0.7163330862367185
Area Under Curve:    0.7163330862367185
(8094, 2560) (8094,)
Epoch 1/400

257/257 [==============================] - 2s 5ms/step - loss: 0.5942 - accuracy: 0.6773 - val_loss: 0.5533 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5500 - accuracy: 0.7197 - val_loss: 0.5446 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5349 - accuracy: 0.7294 - val_loss: 0.5444 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5241 - accuracy: 0.7371 - val_loss: 0.5489 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5142 - accuracy: 0.7440 - val_loss: 0.5423 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7509 - val_loss: 0.5455 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4924 - accuracy: 0.7606 - val_loss: 0.5451 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4811 - accuracy: 0.7671 - val_loss: 0.5501 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4698 - accuracy: 0.7762 - val_loss: 0.5516 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4569 - accuracy: 0.7839 - val_loss: 0.5533 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4433 - accuracy: 0.7925 - val_loss: 0.5575 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4309 - accuracy: 0.7999 - val_loss: 0.5745 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - ETA: 0s - loss: 0.4186 - accuracy: 0.8071
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4186 - accuracy: 0.8071 - val_loss: 0.5696 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4500598925286306
Confusion Matrix :
 [[2976 1071]
 [1155 2892]]
Accuracy on test set:    0.7249814677538917
Sensitivity:    0.7146034099332839 	 Specificity:    0.7353595255744997
Precision  : 0.7297501892505678
Area Under Curve:    0.7249814677538917
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5935 - accuracy: 0.6794 - val_loss: 0.5517 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5504 - accuracy: 0.7194 - val_loss: 0.5427 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5349 - accuracy: 0.7296 - val_loss: 0.5386 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5238 - accuracy: 0.7369 - val_loss: 0.5415 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5143 - accuracy: 0.7446 - val_loss: 0.5381 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7524 - val_loss: 0.5408 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4924 - accuracy: 0.7605 - val_loss: 0.5431 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7684 - val_loss: 0.5485 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7757 - val_loss: 0.5462 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4566 - accuracy: 0.7847 - val_loss: 0.5595 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4430 - accuracy: 0.7939 - val_loss: 0.5550 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4310 - accuracy: 0.8006
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4313 - accuracy: 0.8007 - val_loss: 0.5635 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 964us/step
Independent Testing Matthews Correlation:  0.4813824309305397
Confusion Matrix :
 [[3023 1024]
 [1075 2972]]
Accuracy on test set:    0.7406721027921918
Sensitivity:    0.7343711391153941 	 Specificity:    0.7469730664689894
Precision  : 0.7437437437437437
Area Under Curve:    0.7406721027921918
(8094, 2560) (8094,)
Mean MCC = 0.4330 + 0.0201 and Mean AUC = 0.7161 + 0.0101
Mean Sensitivity = 0.7373 + 0.0201 and Mean Specificity = 0.6949 + 0.0289 and Mean Accuracy = 0.7161 + 0.0101
Mean Precision = 0.7079 + 0.0165





Seed   : 764669
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5870 - accuracy: 0.6855 - val_loss: 0.5559 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7227 - val_loss: 0.5485 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7346 - val_loss: 0.5484 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7412 - val_loss: 0.5462 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7503 - val_loss: 0.5465 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7579 - val_loss: 0.5480 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7657 - val_loss: 0.5520 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4743 - accuracy: 0.7726 - val_loss: 0.5542 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4606 - accuracy: 0.7832 - val_loss: 0.5548 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4489 - accuracy: 0.7905 - val_loss: 0.5667 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4380 - accuracy: 0.7962 - val_loss: 0.5668 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4265 - accuracy: 0.8056 - val_loss: 0.5808 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 13/400
249/257 [============================>.] - ETA: 0s - loss: 0.4150 - accuracy: 0.8105
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4150 - accuracy: 0.8108 - val_loss: 0.5847 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39987378634742005
Confusion Matrix :
 [[2582 1466]
 [ 975 3072]]
Accuracy on test set:    0.6984558369363805
Sensitivity:    0.7590808005930318 	 Specificity:    0.6378458498023716
Precision  : 0.6769501983252534
Area Under Curve:    0.6984633251977018
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5847 - accuracy: 0.6871 - val_loss: 0.5568 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7223 - val_loss: 0.5560 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5268 - accuracy: 0.7343 - val_loss: 0.5497 - val_accuracy: 0.7137 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5140 - accuracy: 0.7451 - val_loss: 0.5443 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7514 - val_loss: 0.5511 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7611 - val_loss: 0.5518 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7695 - val_loss: 0.5502 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7758 - val_loss: 0.5514 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4579 - accuracy: 0.7841 - val_loss: 0.5602 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4449 - accuracy: 0.7921 - val_loss: 0.5585 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4339 - accuracy: 0.7981 - val_loss: 0.5656 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4218 - accuracy: 0.8042 - val_loss: 0.5758 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4110 - accuracy: 0.8127 - val_loss: 0.5666 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3963 - accuracy: 0.8202 - val_loss: 0.5750 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 15/400
251/257 [============================>.] - ETA: 0s - loss: 0.3875 - accuracy: 0.8248
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3874 - accuracy: 0.8250 - val_loss: 0.5826 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4190094209748179
Confusion Matrix :
 [[2742 1306]
 [1049 2998]]
Accuracy on test set:    0.7090796788140827
Sensitivity:    0.7407956510995799 	 Specificity:    0.6773715415019763
Precision  : 0.6965613382899628
Area Under Curve:    0.7090835963007782
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5902 - accuracy: 0.6805 - val_loss: 0.5548 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7221 - val_loss: 0.5427 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7337 - val_loss: 0.5430 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7402 - val_loss: 0.5381 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7476 - val_loss: 0.5385 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4991 - accuracy: 0.7550 - val_loss: 0.5380 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7639 - val_loss: 0.5395 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.7714 - val_loss: 0.5426 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4648 - accuracy: 0.7799 - val_loss: 0.5514 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4507 - accuracy: 0.7906 - val_loss: 0.5573 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4376 - accuracy: 0.7983 - val_loss: 0.5540 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 12/400
250/257 [============================>.] - ETA: 0s - loss: 0.4236 - accuracy: 0.8075
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4240 - accuracy: 0.8072 - val_loss: 0.5650 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 793us/step
Independent Testing Matthews Correlation:  0.4074202423890516
Confusion Matrix :
 [[2734 1313]
 [1088 2960]]
Accuracy on test set:    0.7033971587399629
Sensitivity:    0.7312252964426877 	 Specificity:    0.6755621447986162
Precision  : 0.6927217411654575
Area Under Curve:    0.703393720620652
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5882 - accuracy: 0.6836 - val_loss: 0.5477 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7221 - val_loss: 0.5386 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7336 - val_loss: 0.5375 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7388 - val_loss: 0.5347 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7486 - val_loss: 0.5359 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7565 - val_loss: 0.5350 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7641 - val_loss: 0.5431 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7726 - val_loss: 0.5438 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4606 - accuracy: 0.7810
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4610 - accuracy: 0.7806 - val_loss: 0.5459 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4197976736285756
Confusion Matrix :
 [[2817 1230]
 [1119 2929]]
Accuracy on test set:    0.7098208770846202
Sensitivity:    0.7235671936758893 	 Specificity:    0.6960711638250556
Precision  : 0.7042558307285405
Area Under Curve:    0.7098191787504724
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5891 - accuracy: 0.6841 - val_loss: 0.5533 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7232 - val_loss: 0.5494 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7319 - val_loss: 0.5468 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7404 - val_loss: 0.5444 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7484 - val_loss: 0.5492 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7561 - val_loss: 0.5525 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4856 - accuracy: 0.7634 - val_loss: 0.5511 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4734 - accuracy: 0.7718
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7712 - val_loss: 0.5631 - val_accuracy: 0.7132 - lr: 0.0010
253/253 [==============================] - 0s 949us/step
Independent Testing Matthews Correlation:  0.43293251391191406
Confusion Matrix :
 [[2618 1429]
 [ 882 3165]]
Accuracy on test set:    0.7144798616258957
Sensitivity:    0.782060785767235 	 Specificity:    0.6468989374845565
Precision  : 0.6889420983892033
Area Under Curve:    0.7144798616258957
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5849 - accuracy: 0.6867 - val_loss: 0.5515 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7236 - val_loss: 0.5513 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5270 - accuracy: 0.7332 - val_loss: 0.5518 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5149 - accuracy: 0.7434 - val_loss: 0.5458 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.7519 - val_loss: 0.5472 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7602 - val_loss: 0.5526 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4788 - accuracy: 0.7691 - val_loss: 0.5510 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4659 - accuracy: 0.7768 - val_loss: 0.5593 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4520 - accuracy: 0.7866 - val_loss: 0.5676 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4379 - accuracy: 0.7962 - val_loss: 0.5650 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4247 - accuracy: 0.8034 - val_loss: 0.5762 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4121 - accuracy: 0.8128 - val_loss: 0.5825 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 13/400
246/257 [===========================>..] - ETA: 0s - loss: 0.3992 - accuracy: 0.8188
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3993 - accuracy: 0.8189 - val_loss: 0.5855 - val_accuracy: 0.7145 - lr: 0.0010
253/253 [==============================] - 0s 760us/step
Independent Testing Matthews Correlation:  0.42454310374695114
Confusion Matrix :
 [[2858 1189]
 [1140 2907]]
Accuracy on test set:    0.7122559920929084
Sensitivity:    0.7183098591549296 	 Specificity:    0.7062021250308871
Precision  : 0.709716796875
Area Under Curve:    0.7122559920929084
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5907 - accuracy: 0.6812 - val_loss: 0.5553 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7229 - val_loss: 0.5463 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5328 - accuracy: 0.7339 - val_loss: 0.5458 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5204 - accuracy: 0.7395 - val_loss: 0.5466 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7508 - val_loss: 0.5421 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7569 - val_loss: 0.5466 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4849 - accuracy: 0.7641
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7641 - val_loss: 0.5452 - val_accuracy: 0.7207 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4190117995024008
Confusion Matrix :
 [[2985 1062]
 [1292 2755]]
Accuracy on test set:    0.7091672844082036
Sensitivity:    0.6807511737089202 	 Specificity:    0.737583395107487
Precision  : 0.7217710243646843
Area Under Curve:    0.7091672844082036
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5941 - accuracy: 0.6792 - val_loss: 0.5501 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7213 - val_loss: 0.5419 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5332 - accuracy: 0.7322 - val_loss: 0.5405 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7401 - val_loss: 0.5381 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5110 - accuracy: 0.7469 - val_loss: 0.5429 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7527 - val_loss: 0.5416 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7611 - val_loss: 0.5401 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7687 - val_loss: 0.5450 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4688 - accuracy: 0.7756 - val_loss: 0.5470 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4577 - accuracy: 0.7831 - val_loss: 0.5658 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4455 - accuracy: 0.7899 - val_loss: 0.5533 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4365 - accuracy: 0.7966 - val_loss: 0.5600 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4248 - accuracy: 0.8046 - val_loss: 0.5646 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4126 - accuracy: 0.8106 - val_loss: 0.5876 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4001 - accuracy: 0.8175 - val_loss: 0.5815 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 16/400
254/257 [============================>.] - ETA: 0s - loss: 0.3906 - accuracy: 0.8240
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3908 - accuracy: 0.8239 - val_loss: 0.5798 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4221941788340685
Confusion Matrix :
 [[2932 1115]
 [1224 2823]]
Accuracy on test set:    0.7110205090190265
Sensitivity:    0.6975537435137139 	 Specificity:    0.724487274524339
Precision  : 0.7168613509395633
Area Under Curve:    0.7110205090190265
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5898 - accuracy: 0.6844 - val_loss: 0.5501 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7197 - val_loss: 0.5479 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7313 - val_loss: 0.5474 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5226 - accuracy: 0.7386 - val_loss: 0.5394 - val_accuracy: 0.7219 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7484 - val_loss: 0.5409 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7529 - val_loss: 0.5418 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4903 - accuracy: 0.7630 - val_loss: 0.5469 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4775 - accuracy: 0.7704 - val_loss: 0.5463 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4672 - accuracy: 0.7776 - val_loss: 0.5464 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4524 - accuracy: 0.7869 - val_loss: 0.5544 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7967 - val_loss: 0.5566 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4280 - accuracy: 0.8031 - val_loss: 0.5698 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4154 - accuracy: 0.8118 - val_loss: 0.5688 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 14/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4041 - accuracy: 0.8194
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4048 - accuracy: 0.8188 - val_loss: 0.5897 - val_accuracy: 0.7115 - lr: 0.0010
253/253 [==============================] - 0s 914us/step
Independent Testing Matthews Correlation:  0.43311376396410084
Confusion Matrix :
 [[3155  892]
 [1417 2630]]
Accuracy on test set:    0.7147269582406721
Sensitivity:    0.649864096861873 	 Specificity:    0.7795898196194712
Precision  : 0.7467348097671778
Area Under Curve:    0.7147269582406721
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5932 - accuracy: 0.6800 - val_loss: 0.5573 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5496 - accuracy: 0.7203 - val_loss: 0.5487 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5342 - accuracy: 0.7317 - val_loss: 0.5548 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5226 - accuracy: 0.7379 - val_loss: 0.5462 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5119 - accuracy: 0.7474 - val_loss: 0.5494 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5000 - accuracy: 0.7555 - val_loss: 0.5523 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.7627 - val_loss: 0.5506 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4792 - accuracy: 0.7690 - val_loss: 0.5538 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7776 - val_loss: 0.5606 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4533 - accuracy: 0.7869
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4532 - accuracy: 0.7869 - val_loss: 0.5637 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 0s 983us/step
Independent Testing Matthews Correlation:  0.4765152943246377
Confusion Matrix :
 [[3123  924]
 [1199 2848]]
Accuracy on test set:    0.7377069434148752
Sensitivity:    0.7037311588831233 	 Specificity:    0.7716827279466272
Precision  : 0.7550371155885471
Area Under Curve:    0.7377069434148753
(8094, 2560) (8094,)
Mean MCC = 0.4254 + 0.0196 and Mean AUC = 0.7120 + 0.0098
Mean Sensitivity = 0.7187 + 0.0363 and Mean Specificity = 0.7053 + 0.0459 and Mean Accuracy = 0.7120 + 0.0098
Mean Precision = 0.7110 + 0.0237





Seed   : 309385
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5845 - accuracy: 0.6867 - val_loss: 0.5545 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5410 - accuracy: 0.7246 - val_loss: 0.5474 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5260 - accuracy: 0.7357 - val_loss: 0.5444 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5142 - accuracy: 0.7432 - val_loss: 0.5443 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7532 - val_loss: 0.5480 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7592 - val_loss: 0.5483 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7659 - val_loss: 0.5515 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.7734 - val_loss: 0.5593 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4595 - accuracy: 0.7816
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4599 - accuracy: 0.7813 - val_loss: 0.5637 - val_accuracy: 0.7179 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3957484915127491
Confusion Matrix :
 [[2580 1468]
 [ 989 3058]]
Accuracy on test set:    0.6964793082149475
Sensitivity:    0.7556214479861626 	 Specificity:    0.6373517786561265
Precision  : 0.6756517896597437
Area Under Curve:    0.6964866133211445
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5898 - accuracy: 0.6806 - val_loss: 0.5577 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7233 - val_loss: 0.5539 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7344 - val_loss: 0.5475 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7429 - val_loss: 0.5479 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7493 - val_loss: 0.5456 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7584 - val_loss: 0.5504 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.7663 - val_loss: 0.5571 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7736 - val_loss: 0.5547 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4591 - accuracy: 0.7842 - val_loss: 0.5570 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4449 - accuracy: 0.7940 - val_loss: 0.5561 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4324 - accuracy: 0.7998 - val_loss: 0.5622 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4183 - accuracy: 0.8087 - val_loss: 0.5733 - val_accuracy: 0.7135 - lr: 0.0010

Epoch 13/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4048 - accuracy: 0.8161
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4050 - accuracy: 0.8158 - val_loss: 0.5791 - val_accuracy: 0.7156 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4018611087164367
Confusion Matrix :
 [[2825 1223]
 [1198 2849]]
Accuracy on test set:    0.7009264978381717
Sensitivity:    0.7039782554978997 	 Specificity:    0.6978754940711462
Precision  : 0.699656188605108
Area Under Curve:    0.700926874784523
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5869 - accuracy: 0.6843 - val_loss: 0.5499 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7241 - val_loss: 0.5410 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5270 - accuracy: 0.7340 - val_loss: 0.5405 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5138 - accuracy: 0.7454 - val_loss: 0.5394 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7529 - val_loss: 0.5381 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4903 - accuracy: 0.7613 - val_loss: 0.5433 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7683 - val_loss: 0.5422 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4675 - accuracy: 0.7749 - val_loss: 0.5481 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4562 - accuracy: 0.7826 - val_loss: 0.5531 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4441 - accuracy: 0.7913 - val_loss: 0.5583 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4305 - accuracy: 0.8002 - val_loss: 0.5606 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4212 - accuracy: 0.8059 - val_loss: 0.5781 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4088 - accuracy: 0.8123 - val_loss: 0.5834 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 14/400
253/257 [============================>.] - ETA: 0s - loss: 0.3975 - accuracy: 0.8199
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3978 - accuracy: 0.8196 - val_loss: 0.5795 - val_accuracy: 0.7094 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40435162691214943
Confusion Matrix :
 [[2766 1281]
 [1131 2917]]
Accuracy on test set:    0.7020382952439778
Sensitivity:    0.720602766798419 	 Specificity:    0.6834692364714603
Precision  : 0.6948546927108147
Area Under Curve:    0.7020360016349396
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5859 - accuracy: 0.6868 - val_loss: 0.5519 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7227 - val_loss: 0.5389 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7343 - val_loss: 0.5351 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7441 - val_loss: 0.5370 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7502 - val_loss: 0.5368 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7580 - val_loss: 0.5355 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4805 - accuracy: 0.7687 - val_loss: 0.5428 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4672 - accuracy: 0.7801
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7801 - val_loss: 0.5424 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 843us/step
Independent Testing Matthews Correlation:  0.4223884835163919
Confusion Matrix :
 [[2804 1243]
 [1096 2952]]
Accuracy on test set:    0.7110562075355158
Sensitivity:    0.7292490118577075 	 Specificity:    0.6928589078329627
Precision  : 0.7036948748510131
Area Under Curve:    0.7110539598453351
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5868 - accuracy: 0.6843 - val_loss: 0.5593 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7236 - val_loss: 0.5523 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7348 - val_loss: 0.5472 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7405 - val_loss: 0.5494 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7494 - val_loss: 0.5485 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4923 - accuracy: 0.7595 - val_loss: 0.5517 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4805 - accuracy: 0.7665 - val_loss: 0.5536 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4679 - accuracy: 0.7761
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4684 - accuracy: 0.7760 - val_loss: 0.5534 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 844us/step
Independent Testing Matthews Correlation:  0.4203115470374812
Confusion Matrix :
 [[2876 1171]
 [1175 2872]]
Accuracy on test set:    0.7101556708673091
Sensitivity:    0.7096614776377563 	 Specificity:    0.7106498640968619
Precision  : 0.7103635913925302
Area Under Curve:    0.7101556708673091
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5894 - accuracy: 0.6803 - val_loss: 0.5608 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7241 - val_loss: 0.5481 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7327 - val_loss: 0.5491 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7426 - val_loss: 0.5471 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7532 - val_loss: 0.5473 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7608 - val_loss: 0.5530 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7694 - val_loss: 0.5552 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4653 - accuracy: 0.7789 - val_loss: 0.5558 - val_accuracy: 0.7127 - lr: 0.0010

Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4510 - accuracy: 0.7869 - val_loss: 0.5634 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4367 - accuracy: 0.7969
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4366 - accuracy: 0.7972 - val_loss: 0.5765 - val_accuracy: 0.7134 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4139333694323471
Confusion Matrix :
 [[2716 1331]
 [1045 3002]]
Accuracy on test set:    0.7064492216456635
Sensitivity:    0.7417840375586855 	 Specificity:    0.6711144057326415
Precision  : 0.6928225248096007
Area Under Curve:    0.7064492216456635
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5930 - accuracy: 0.6793 - val_loss: 0.5619 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7208 - val_loss: 0.5487 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5336 - accuracy: 0.7305 - val_loss: 0.5468 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5219 - accuracy: 0.7385 - val_loss: 0.5500 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7447 - val_loss: 0.5490 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4994 - accuracy: 0.7547 - val_loss: 0.5481 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 7/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4880 - accuracy: 0.7625
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.7618 - val_loss: 0.5531 - val_accuracy: 0.7064 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4280456802125596
Confusion Matrix :
 [[3030 1017]
 [1302 2745]]
Accuracy on test set:    0.7134914751667902
Sensitivity:    0.6782802075611564 	 Specificity:    0.748702742772424
Precision  : 0.7296650717703349
Area Under Curve:    0.7134914751667901
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5894 - accuracy: 0.6837 - val_loss: 0.5582 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7220 - val_loss: 0.5493 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7320 - val_loss: 0.5440 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7438 - val_loss: 0.5428 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5028 - accuracy: 0.7513 - val_loss: 0.5476 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7625 - val_loss: 0.5494 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4754 - accuracy: 0.7717 - val_loss: 0.5512 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4624 - accuracy: 0.7797 - val_loss: 0.5576 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 9/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4465 - accuracy: 0.7911
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4470 - accuracy: 0.7909 - val_loss: 0.5633 - val_accuracy: 0.7119 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4418693059554873
Confusion Matrix :
 [[2951 1096]
 [1163 2884]]
Accuracy on test set:    0.7209043736100815
Sensitivity:    0.7126266370150729 	 Specificity:    0.7291821102050902
Precision  : 0.7246231155778895
Area Under Curve:    0.7209043736100815
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5921 - accuracy: 0.6823 - val_loss: 0.5573 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5482 - accuracy: 0.7213 - val_loss: 0.5489 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7314 - val_loss: 0.5465 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.7393 - val_loss: 0.5458 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5115 - accuracy: 0.7469 - val_loss: 0.5503 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7524 - val_loss: 0.5511 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7600 - val_loss: 0.5538 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7681 - val_loss: 0.5556 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4689 - accuracy: 0.7768
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4689 - accuracy: 0.7767 - val_loss: 0.5583 - val_accuracy: 0.7148 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4525498270839676
Confusion Matrix :
 [[3140  907]
 [1318 2729]]
Accuracy on test set:    0.72510501606128
Sensitivity:    0.6743266617247343 	 Specificity:    0.7758833703978255
Precision  : 0.7505500550055005
Area Under Curve:    0.72510501606128
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5921 - accuracy: 0.6796 - val_loss: 0.5601 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5493 - accuracy: 0.7198 - val_loss: 0.5519 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7329 - val_loss: 0.5525 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7421 - val_loss: 0.5515 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7503 - val_loss: 0.5541 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7588 - val_loss: 0.5533 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7673 - val_loss: 0.5603 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4686 - accuracy: 0.7767 - val_loss: 0.5635 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4545 - accuracy: 0.7870 - val_loss: 0.5670 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4404 - accuracy: 0.7941 - val_loss: 0.5745 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 11/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4271 - accuracy: 0.8036
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4278 - accuracy: 0.8035 - val_loss: 0.5823 - val_accuracy: 0.7101 - lr: 0.0010

253/253 [==============================] - 0s 957us/step
Independent Testing Matthews Correlation:  0.48340604195577896
Confusion Matrix :
 [[3076  971]
 [1121 2926]]
Accuracy on test set:    0.7415369409439091
Sensitivity:    0.7230046948356808 	 Specificity:    0.7600691870521374
Precision  : 0.7508339748524506
Area Under Curve:    0.7415369409439091
(8094, 2560) (8094,)
Mean MCC = 0.4264 + 0.0253 and Mean AUC = 0.7128 + 0.0127
Mean Sensitivity = 0.7149 + 0.0241 and Mean Specificity = 0.7107 + 0.0408 and Mean Accuracy = 0.7128 + 0.0127
Mean Precision = 0.7133 + 0.0238





Seed   : 408493
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5831 - accuracy: 0.6889 - val_loss: 0.5598 - val_accuracy: 0.7054 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5403 - accuracy: 0.7256 - val_loss: 0.5508 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5252 - accuracy: 0.7384 - val_loss: 0.5556 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.7452 - val_loss: 0.5486 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7515 - val_loss: 0.5626 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7597 - val_loss: 0.5511 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7664 - val_loss: 0.5539 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4699 - accuracy: 0.7762 - val_loss: 0.5606 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4585 - accuracy: 0.7838 - val_loss: 0.5599 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4455 - accuracy: 0.7917 - val_loss: 0.5712 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 11/400
254/257 [============================>.] - ETA: 0s - loss: 0.4342 - accuracy: 0.7997
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4340 - accuracy: 0.7998 - val_loss: 0.5745 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40407039019631386
Confusion Matrix :
 [[2772 1276]
 [1137 2910]]
Accuracy on test set:    0.7019147621988882
Sensitivity:    0.7190511489992587 	 Specificity:    0.6847826086956522
Precision  : 0.6951743908265647
Area Under Curve:    0.7019168788474553
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5882 - accuracy: 0.6851 - val_loss: 0.5597 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7245 - val_loss: 0.5567 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7340 - val_loss: 0.5489 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7432 - val_loss: 0.5478 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7519 - val_loss: 0.5510 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7599 - val_loss: 0.5531 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4806 - accuracy: 0.7688 - val_loss: 0.5580 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4663 - accuracy: 0.7775 - val_loss: 0.5575 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4548 - accuracy: 0.7845 - val_loss: 0.5714 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4405 - accuracy: 0.7920 - val_loss: 0.5676 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4258 - accuracy: 0.8026 - val_loss: 0.5892 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4146 - accuracy: 0.8085 - val_loss: 0.5847 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 13/400
256/257 [============================>.] - ETA: 0s - loss: 0.4021 - accuracy: 0.8158
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4021 - accuracy: 0.8158 - val_loss: 0.5984 - val_accuracy: 0.7094 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4142579721169072
Confusion Matrix :
 [[2758 1290]
 [1083 2964]]
Accuracy on test set:    0.7068560840024707
Sensitivity:    0.7323943661971831 	 Specificity:    0.6813241106719368
Precision  : 0.6967559943582511
Area Under Curve:    0.7068592384345599
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6845 - val_loss: 0.5493 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7238 - val_loss: 0.5422 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7331 - val_loss: 0.5379 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7410 - val_loss: 0.5376 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.7487 - val_loss: 0.5419 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4970 - accuracy: 0.7582 - val_loss: 0.5386 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.7660 - val_loss: 0.5399 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.7741 - val_loss: 0.5413 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4599 - accuracy: 0.7826 - val_loss: 0.5475 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4477 - accuracy: 0.7899 - val_loss: 0.5470 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4352 - accuracy: 0.7971 - val_loss: 0.5517 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4235 - accuracy: 0.8037 - val_loss: 0.5554 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4101 - accuracy: 0.8141 - val_loss: 0.5654 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 14/400
256/257 [============================>.] - ETA: 0s - loss: 0.3989 - accuracy: 0.8190
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3989 - accuracy: 0.8190 - val_loss: 0.5751 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 823us/step
Independent Testing Matthews Correlation:  0.4112466560556326
Confusion Matrix :
 [[2845 1202]
 [1181 2867]]
Accuracy on test set:    0.705620753551575
Sensitivity:    0.7082509881422925 	 Specificity:    0.7029898690387941
Precision  : 0.7045957237650529
Area Under Curve:    0.7056204285905433
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5855 - accuracy: 0.6867 - val_loss: 0.5489 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7223 - val_loss: 0.5376 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5265 - accuracy: 0.7358 - val_loss: 0.5339 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5149 - accuracy: 0.7446 - val_loss: 0.5327 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7526 - val_loss: 0.5350 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7598 - val_loss: 0.5380 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7687 - val_loss: 0.5417 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4679 - accuracy: 0.7774 - val_loss: 0.5396 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4541 - accuracy: 0.7848 - val_loss: 0.5463 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4441 - accuracy: 0.7922 - val_loss: 0.5487 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4322 - accuracy: 0.7990 - val_loss: 0.5503 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
256/257 [============================>.] - ETA: 0s - loss: 0.4194 - accuracy: 0.8059
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4193 - accuracy: 0.8059 - val_loss: 0.5678 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 810us/step
Independent Testing Matthews Correlation:  0.4203168066203371
Confusion Matrix :
 [[3022 1025]
 [1326 2722]]
Accuracy on test set:    0.7095738109944411
Sensitivity:    0.6724308300395256 	 Specificity:    0.746725969854213
Precision  : 0.726447824926608
Area Under Curve:    0.7095783999468693
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5876 - accuracy: 0.6846 - val_loss: 0.5502 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7235 - val_loss: 0.5396 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7309 - val_loss: 0.5404 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7411 - val_loss: 0.5407 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7487 - val_loss: 0.5421 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7558 - val_loss: 0.5461 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4844 - accuracy: 0.7646
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.7646 - val_loss: 0.5477 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 980us/step
Independent Testing Matthews Correlation:  0.4463476486068577
Confusion Matrix :
 [[2705 1342]
 [ 909 3138]]
Accuracy on test set:    0.721892760069187
Sensitivity:    0.7753891771682728 	 Specificity:    0.6683963429701013
Precision  : 0.7004464285714286
Area Under Curve:    0.721892760069187
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5909 - accuracy: 0.6813 - val_loss: 0.5583 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7206 - val_loss: 0.5474 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7312 - val_loss: 0.5416 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7414 - val_loss: 0.5411 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7492 - val_loss: 0.5441 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7556 - val_loss: 0.5446 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4876 - accuracy: 0.7618 - val_loss: 0.5521 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4751 - accuracy: 0.7718
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4752 - accuracy: 0.7718 - val_loss: 0.5518 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 917us/step
Independent Testing Matthews Correlation:  0.4294225965611928
Confusion Matrix :
 [[2661 1386]
 [ 934 3113]]
Accuracy on test set:    0.713367926859402
Sensitivity:    0.7692117617988633 	 Specificity:    0.6575240919199407
Precision  : 0.6919315403422983
Area Under Curve:    0.7133679268594021
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6853 - val_loss: 0.5514 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7226 - val_loss: 0.5445 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7326 - val_loss: 0.5417 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7427 - val_loss: 0.5363 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7496 - val_loss: 0.5368 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7589 - val_loss: 0.5363 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7666 - val_loss: 0.5404 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7777 - val_loss: 0.5404 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4546 - accuracy: 0.7859
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4549 - accuracy: 0.7861 - val_loss: 0.5533 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 911us/step
Independent Testing Matthews Correlation:  0.42670896676981973
Confusion Matrix :
 [[2717 1330]
 [ 996 3051]]
Accuracy on test set:    0.7126266370150729
Sensitivity:    0.7538917716827279 	 Specificity:    0.6713615023474179
Precision  : 0.6964163433006163
Area Under Curve:    0.7126266370150728
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5854 - accuracy: 0.6863 - val_loss: 0.5503 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7224 - val_loss: 0.5404 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7326 - val_loss: 0.5415 - val_accuracy: 0.7197 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7414 - val_loss: 0.5349 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7495 - val_loss: 0.5382 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7582 - val_loss: 0.5430 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7673 - val_loss: 0.5395 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4703 - accuracy: 0.7764 - val_loss: 0.5490 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4576 - accuracy: 0.7836 - val_loss: 0.5440 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4426 - accuracy: 0.7931 - val_loss: 0.5454 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4285 - accuracy: 0.8018 - val_loss: 0.5541 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4153 - accuracy: 0.8102 - val_loss: 0.5578 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 13/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4026 - accuracy: 0.8185
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4033 - accuracy: 0.8178 - val_loss: 0.5613 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4287277570469603
Confusion Matrix :
 [[2908 1139]
 [1173 2874]]
Accuracy on test set:    0.7143563133185076
Sensitivity:    0.7101556708673091 	 Specificity:    0.7185569557697059
Precision  : 0.716172439571393
Area Under Curve:    0.7143563133185077
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5955 - accuracy: 0.6785 - val_loss: 0.5537 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5515 - accuracy: 0.7188 - val_loss: 0.5512 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5359 - accuracy: 0.7294 - val_loss: 0.5438 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5245 - accuracy: 0.7390 - val_loss: 0.5560 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5120 - accuracy: 0.7478 - val_loss: 0.5470 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7556 - val_loss: 0.5439 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7649 - val_loss: 0.5447 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4741 - accuracy: 0.7735
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4743 - accuracy: 0.7734 - val_loss: 0.5497 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4545747984305522
Confusion Matrix :
 [[3085  962]
 [1250 2797]]
Accuracy on test set:    0.7267111440573264
Sensitivity:    0.6911292315295281 	 Specificity:    0.7622930565851248
Precision  : 0.7440808725724927
Area Under Curve:    0.7267111440573265
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5939 - accuracy: 0.6779 - val_loss: 0.5551 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5494 - accuracy: 0.7201 - val_loss: 0.5500 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5348 - accuracy: 0.7320 - val_loss: 0.5489 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5236 - accuracy: 0.7386 - val_loss: 0.5473 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5122 - accuracy: 0.7488 - val_loss: 0.5428 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5018 - accuracy: 0.7564 - val_loss: 0.5520 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7621 - val_loss: 0.5477 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7704 - val_loss: 0.5533 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.7777 - val_loss: 0.5528 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4556 - accuracy: 0.7858
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4553 - accuracy: 0.7859 - val_loss: 0.5630 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 866us/step
Independent Testing Matthews Correlation:  0.4665367261622279
Confusion Matrix :
 [[3139  908]
 [1258 2789]]
Accuracy on test set:    0.7323943661971831
Sensitivity:    0.689152458611317 	 Specificity:    0.7756362737830492
Precision  : 0.7543954557749527
Area Under Curve:    0.732394366197183
(8094, 2560) (8094,)
Mean MCC = 0.4302 + 0.0189 and Mean AUC = 0.7145 + 0.0092
Mean Sensitivity = 0.7221 + 0.0332 and Mean Specificity = 0.7070 + 0.0398 and Mean Accuracy = 0.7145 + 0.0092
Mean Precision = 0.7126 + 0.0210





Seed   : 681404
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6849 - val_loss: 0.5576 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7263 - val_loss: 0.5475 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5268 - accuracy: 0.7353 - val_loss: 0.5458 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7447 - val_loss: 0.5507 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7532 - val_loss: 0.5442 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7617 - val_loss: 0.5490 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7685 - val_loss: 0.5467 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7771 - val_loss: 0.5525 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4549 - accuracy: 0.7847 - val_loss: 0.5640 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4429 - accuracy: 0.7922
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4430 - accuracy: 0.7919 - val_loss: 0.5585 - val_accuracy: 0.7193 - lr: 0.0010
253/253 [==============================] - 0s 983us/step
Independent Testing Matthews Correlation:  0.40965445262047023
Confusion Matrix :
 [[2800 1248]
 [1142 2905]]
Accuracy on test set:    0.7047560222359481
Sensitivity:    0.7178156659253768 	 Specificity:    0.691699604743083
Precision  : 0.699494341439923
Area Under Curve:    0.70475763533423
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5842 - accuracy: 0.6867 - val_loss: 0.5523 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5413 - accuracy: 0.7260 - val_loss: 0.5451 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5251 - accuracy: 0.7365 - val_loss: 0.5430 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7440 - val_loss: 0.5418 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7523 - val_loss: 0.5497 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4928 - accuracy: 0.7596 - val_loss: 0.5436 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4793 - accuracy: 0.7700 - val_loss: 0.5469 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4671 - accuracy: 0.7770 - val_loss: 0.5457 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4559 - accuracy: 0.7858 - val_loss: 0.5523 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4435 - accuracy: 0.7943 - val_loss: 0.5587 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4313 - accuracy: 0.8014 - val_loss: 0.5589 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4183 - accuracy: 0.8064 - val_loss: 0.5656 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 13/400
252/257 [============================>.] - ETA: 0s - loss: 0.4067 - accuracy: 0.8146
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4066 - accuracy: 0.8146 - val_loss: 0.5766 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 838us/step
Independent Testing Matthews Correlation:  0.40709018053081
Confusion Matrix :
 [[2670 1378]
 [1028 3019]]
Accuracy on test set:    0.7027794935145152
Sensitivity:    0.7459846800098838 	 Specificity:    0.6595849802371542
Precision  : 0.6866045030702752
Area Under Curve:    0.7027848301235191
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5905 - accuracy: 0.6825 - val_loss: 0.5527 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7215 - val_loss: 0.5406 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7332 - val_loss: 0.5569 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.7394 - val_loss: 0.5394 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7478 - val_loss: 0.5355 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7557 - val_loss: 0.5442 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7630 - val_loss: 0.5401 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4749 - accuracy: 0.7720 - val_loss: 0.5486 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 9/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4635 - accuracy: 0.7800
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4636 - accuracy: 0.7799 - val_loss: 0.5467 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 828us/step
Independent Testing Matthews Correlation:  0.41072667708844723
Confusion Matrix :
 [[2756 1291]
 [1096 2952]]
Accuracy on test set:    0.7051266213712168
Sensitivity:    0.7292490118577075 	 Specificity:    0.6809982703236965
Precision  : 0.6957341503653076
Area Under Curve:    0.705123641090702
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5922 - accuracy: 0.6796 - val_loss: 0.5499 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7226 - val_loss: 0.5370 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5331 - accuracy: 0.7318 - val_loss: 0.5360 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7386 - val_loss: 0.5371 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5103 - accuracy: 0.7468 - val_loss: 0.5355 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7551 - val_loss: 0.5415 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7647 - val_loss: 0.5391 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4754 - accuracy: 0.7705 - val_loss: 0.5429 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4632 - accuracy: 0.7794 - val_loss: 0.5468 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4523 - accuracy: 0.7869 - val_loss: 0.5519 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4414 - accuracy: 0.7948 - val_loss: 0.5583 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4293 - accuracy: 0.8022
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4292 - accuracy: 0.8022 - val_loss: 0.5656 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 956us/step
Independent Testing Matthews Correlation:  0.41868269922097806
Confusion Matrix :
 [[2656 1391]
 [ 971 3077]]
Accuracy on test set:    0.7082149474984558
Sensitivity:    0.7601284584980237 	 Specificity:    0.6562886088460588
Precision  : 0.6886750223813787
Area Under Curve:    0.7082085336720413
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5853 - accuracy: 0.6864 - val_loss: 0.5497 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7215 - val_loss: 0.5428 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7337 - val_loss: 0.5402 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7409 - val_loss: 0.5455 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7496 - val_loss: 0.5432 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7572 - val_loss: 0.5407 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4846 - accuracy: 0.7653
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.7648 - val_loss: 0.5422 - val_accuracy: 0.7227 - lr: 0.0010
253/253 [==============================] - 0s 911us/step
Independent Testing Matthews Correlation:  0.44414638459775263
Confusion Matrix :
 [[2795 1252]
 [1001 3046]]
Accuracy on test set:    0.7216456634544107
Sensitivity:    0.752656288608846 	 Specificity:    0.6906350382999753
Precision  : 0.7087017217310377
Area Under Curve:    0.7216456634544107
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6842 - val_loss: 0.5534 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7223 - val_loss: 0.5429 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7333 - val_loss: 0.5410 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7432 - val_loss: 0.5402 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7492 - val_loss: 0.5427 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7581 - val_loss: 0.5430 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7666 - val_loss: 0.5433 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4698 - accuracy: 0.7749 - val_loss: 0.5486 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4585 - accuracy: 0.7821
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4588 - accuracy: 0.7818 - val_loss: 0.5507 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 964us/step
Independent Testing Matthews Correlation:  0.4367626851980286
Confusion Matrix :
 [[2821 1226]
 [1055 2992]]
Accuracy on test set:    0.7181863108475414
Sensitivity:    0.7393130714109216 	 Specificity:    0.6970595502841611
Precision  : 0.7093409198672357
Area Under Curve:    0.7181863108475415
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5842 - accuracy: 0.6865 - val_loss: 0.5522 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7231 - val_loss: 0.5388 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5270 - accuracy: 0.7352 - val_loss: 0.5374 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7431 - val_loss: 0.5369 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7517 - val_loss: 0.5381 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7605 - val_loss: 0.5356 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7676 - val_loss: 0.5407 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4676 - accuracy: 0.7762 - val_loss: 0.5466 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4551 - accuracy: 0.7838 - val_loss: 0.5479 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4423 - accuracy: 0.7925 - val_loss: 0.5507 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4307 - accuracy: 0.8004
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4308 - accuracy: 0.8005 - val_loss: 0.5548 - val_accuracy: 0.7270 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4196431031529229
Confusion Matrix :
 [[2997 1050]
 [1302 2745]]
Accuracy on test set:    0.7094143810229799
Sensitivity:    0.6782802075611564 	 Specificity:    0.7405485544848036
Precision  : 0.7233201581027668
Area Under Curve:    0.70941438102298
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5884 - accuracy: 0.6830 - val_loss: 0.5481 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7219 - val_loss: 0.5424 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7326 - val_loss: 0.5349 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7389 - val_loss: 0.5360 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5101 - accuracy: 0.7476 - val_loss: 0.5430 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7516 - val_loss: 0.5383 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7599 - val_loss: 0.5389 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4792 - accuracy: 0.7682 - val_loss: 0.5466 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4679 - accuracy: 0.7781 - val_loss: 0.5456 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4567 - accuracy: 0.7845 - val_loss: 0.5521 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4435 - accuracy: 0.7928 - val_loss: 0.5485 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4304 - accuracy: 0.7999
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4305 - accuracy: 0.7998 - val_loss: 0.5545 - val_accuracy: 0.7260 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43892304128836246
Confusion Matrix :
 [[2873 1174]
 [1097 2950]]
Accuracy on test set:    0.7194217939214232
Sensitivity:    0.7289350135903138 	 Specificity:    0.7099085742525327
Precision  : 0.7153249272550921
Area Under Curve:    0.7194217939214232
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5909 - accuracy: 0.6810 - val_loss: 0.5545 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7205 - val_loss: 0.5434 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5328 - accuracy: 0.7312 - val_loss: 0.5496 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7398 - val_loss: 0.5420 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7504 - val_loss: 0.5389 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7567 - val_loss: 0.5440 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7662 - val_loss: 0.5494 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7727 - val_loss: 0.5487 - val_accuracy: 0.7240 - lr: 0.0010

Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4551 - accuracy: 0.7858 - val_loss: 0.5538 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4430 - accuracy: 0.7921
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4434 - accuracy: 0.7916 - val_loss: 0.5579 - val_accuracy: 0.7244 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46505139910309273
Confusion Matrix :
 [[2896 1151]
 [1015 3032]]
Accuracy on test set:    0.7323943661971831
Sensitivity:    0.7491969360019768 	 Specificity:    0.7155917963923895
Precision  : 0.7248386325603634
Area Under Curve:    0.7323943661971831
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5910 - accuracy: 0.6812 - val_loss: 0.5533 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5499 - accuracy: 0.7213 - val_loss: 0.5468 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7322 - val_loss: 0.5470 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5216 - accuracy: 0.7401 - val_loss: 0.5405 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7499 - val_loss: 0.5469 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7587 - val_loss: 0.5460 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7664 - val_loss: 0.5484 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4718 - accuracy: 0.7747
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7747 - val_loss: 0.5510 - val_accuracy: 0.7139 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4617364555261151
Confusion Matrix :
 [[3219  828]
 [1367 2680]]
Accuracy on test set:    0.7288114652829256
Sensitivity:    0.6622189276006919 	 Specificity:    0.7954040029651593
Precision  : 0.7639680729760547
Area Under Curve:    0.7288114652829256
(8094, 2560) (8094,)
Mean MCC = 0.4312 + 0.0202 and Mean AUC = 0.7151 + 0.0100
Mean Sensitivity = 0.7264 + 0.0307 and Mean Specificity = 0.7038 + 0.0387 and Mean Accuracy = 0.7151 + 0.0100
Mean Precision = 0.7116 + 0.0215





Seed   : 718520
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5863 - accuracy: 0.6875 - val_loss: 0.5567 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7233 - val_loss: 0.5481 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7350 - val_loss: 0.5525 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7430 - val_loss: 0.5437 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7514 - val_loss: 0.5491 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7608 - val_loss: 0.5484 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7688 - val_loss: 0.5527 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4677 - accuracy: 0.7766 - val_loss: 0.5541 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4513 - accuracy: 0.7892
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4518 - accuracy: 0.7889 - val_loss: 0.5608 - val_accuracy: 0.7097 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3870506459674351
Confusion Matrix :
 [[2732 1316]
 [1166 2881]]
Accuracy on test set:    0.6933909820877084
Sensitivity:    0.7118853471707438 	 Specificity:    0.674901185770751
Precision  : 0.6864426971646415
Area Under Curve:    0.6933932664707474
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5886 - accuracy: 0.6854 - val_loss: 0.5587 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7229 - val_loss: 0.5555 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7329 - val_loss: 0.5460 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7403 - val_loss: 0.5468 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5106 - accuracy: 0.7473 - val_loss: 0.5463 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7550 - val_loss: 0.5464 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.7620 - val_loss: 0.5577 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4791 - accuracy: 0.7703 - val_loss: 0.5545 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4682 - accuracy: 0.7776 - val_loss: 0.5595 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4572 - accuracy: 0.7846 - val_loss: 0.5572 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 11/400
249/257 [============================>.] - ETA: 0s - loss: 0.4423 - accuracy: 0.7942
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7942 - val_loss: 0.5663 - val_accuracy: 0.7126 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4172491648616657
Confusion Matrix :
 [[2908 1140]
 [1219 2828]]
Accuracy on test set:    0.7085855466337245
Sensitivity:    0.6987892265875958 	 Specificity:    0.7183794466403162
Precision  : 0.7127016129032258
Area Under Curve:    0.708584336613956
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6840 - val_loss: 0.5447 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7226 - val_loss: 0.5387 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7348 - val_loss: 0.5373 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7420 - val_loss: 0.5336 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7495 - val_loss: 0.5391 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7567 - val_loss: 0.5373 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4848 - accuracy: 0.7659 - val_loss: 0.5340 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4730 - accuracy: 0.7750 - val_loss: 0.5378 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4588 - accuracy: 0.7846 - val_loss: 0.5484 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4458 - accuracy: 0.7917 - val_loss: 0.5410 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4321 - accuracy: 0.8013 - val_loss: 0.5522 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 12/400
255/257 [============================>.] - ETA: 0s - loss: 0.4171 - accuracy: 0.8120
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4171 - accuracy: 0.8119 - val_loss: 0.5526 - val_accuracy: 0.7244 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41230328050415754
Confusion Matrix :
 [[2710 1337]
 [1046 3002]]
Accuracy on test set:    0.705620753551575
Sensitivity:    0.741600790513834 	 Specificity:    0.6696318260439832
Precision  : 0.6918644849043558
Area Under Curve:    0.7056163082789086
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5911 - accuracy: 0.6799 - val_loss: 0.5470 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7223 - val_loss: 0.5399 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7324 - val_loss: 0.5364 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5212 - accuracy: 0.7394 - val_loss: 0.5331 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5101 - accuracy: 0.7480 - val_loss: 0.5340 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7541 - val_loss: 0.5344 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7640 - val_loss: 0.5375 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4770 - accuracy: 0.7707 - val_loss: 0.5409 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4673 - accuracy: 0.7764
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7769 - val_loss: 0.5492 - val_accuracy: 0.7219 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.417148034777374
Confusion Matrix :
 [[2770 1277]
 [1084 2964]]
Accuracy on test set:    0.7083384805435454
Sensitivity:    0.7322134387351779 	 Specificity:    0.6844576229305659
Precision  : 0.6988917708087715
Area Under Curve:    0.7083355308328718
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5927 - accuracy: 0.6793 - val_loss: 0.5556 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5485 - accuracy: 0.7193 - val_loss: 0.5454 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7303 - val_loss: 0.5409 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5228 - accuracy: 0.7385 - val_loss: 0.5523 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5119 - accuracy: 0.7463 - val_loss: 0.5414 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.7539 - val_loss: 0.5404 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7596 - val_loss: 0.5449 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7686 - val_loss: 0.5474 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4683 - accuracy: 0.7763 - val_loss: 0.5503 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4582 - accuracy: 0.7820 - val_loss: 0.5521 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 11/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4465 - accuracy: 0.7926
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4469 - accuracy: 0.7921 - val_loss: 0.5616 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4323178334185185
Confusion Matrix :
 [[2612 1435]
 [ 879 3168]]
Accuracy on test set:    0.7141092167037312
Sensitivity:    0.7828020756115641 	 Specificity:    0.6454163577958982
Precision  : 0.6882467955681077
Area Under Curve:    0.7141092167037313
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6848 - val_loss: 0.5545 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7224 - val_loss: 0.5485 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7328 - val_loss: 0.5494 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7411 - val_loss: 0.5429 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7492 - val_loss: 0.5463 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4954 - accuracy: 0.7567 - val_loss: 0.5445 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7665 - val_loss: 0.5484 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7755 - val_loss: 0.5490 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4555 - accuracy: 0.7843 - val_loss: 0.5530 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4441 - accuracy: 0.7923
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4444 - accuracy: 0.7921 - val_loss: 0.5635 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4254197857697755
Confusion Matrix :
 [[2733 1314]
 [1016 3031]]
Accuracy on test set:    0.7121324437855201
Sensitivity:    0.7489498393872004 	 Specificity:    0.6753150481838399
Precision  : 0.6975834292289989
Area Under Curve:    0.7121324437855202
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6861 - val_loss: 0.5473 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7222 - val_loss: 0.5491 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7343 - val_loss: 0.5417 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7422 - val_loss: 0.5363 - val_accuracy: 0.7233 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7493 - val_loss: 0.5491 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7559 - val_loss: 0.5404 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7655 - val_loss: 0.5420 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.7729 - val_loss: 0.5445 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4587 - accuracy: 0.7819 - val_loss: 0.5478 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4474 - accuracy: 0.7890 - val_loss: 0.5499 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4352 - accuracy: 0.7959 - val_loss: 0.5560 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 12/400
250/257 [============================>.] - ETA: 0s - loss: 0.4204 - accuracy: 0.8049
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4209 - accuracy: 0.8046 - val_loss: 0.5592 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 896us/step
Independent Testing Matthews Correlation:  0.420535094934701
Confusion Matrix :
 [[2808 1239]
 [1107 2940]]
Accuracy on test set:    0.7101556708673091
Sensitivity:    0.72646404744255 	 Specificity:    0.6938472942920682
Precision  : 0.7035175879396985
Area Under Curve:    0.710155670867309
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5887 - accuracy: 0.6828 - val_loss: 0.5497 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7232 - val_loss: 0.5428 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7340 - val_loss: 0.5406 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7431 - val_loss: 0.5397 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7506 - val_loss: 0.5389 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7599 - val_loss: 0.5482 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7686 - val_loss: 0.5497 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4702 - accuracy: 0.7765
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4702 - accuracy: 0.7766 - val_loss: 0.5501 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 959us/step
Independent Testing Matthews Correlation:  0.4326006534780358
Confusion Matrix :
 [[3085  962]
 [1342 2705]]
Accuracy on test set:    0.7153446997776131
Sensitivity:    0.6683963429701013 	 Specificity:    0.7622930565851248
Precision  : 0.7376602127079357
Area Under Curve:    0.7153446997776131
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5894 - accuracy: 0.6848 - val_loss: 0.5547 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7209 - val_loss: 0.5443 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5324 - accuracy: 0.7329 - val_loss: 0.5421 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5219 - accuracy: 0.7393 - val_loss: 0.5427 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5108 - accuracy: 0.7486 - val_loss: 0.5421 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4994 - accuracy: 0.7541 - val_loss: 0.5409 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.7639 - val_loss: 0.5442 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7732 - val_loss: 0.5518 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4624 - accuracy: 0.7816 - val_loss: 0.5553 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4499 - accuracy: 0.7907
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4504 - accuracy: 0.7903 - val_loss: 0.5628 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43690376740025383
Confusion Matrix :
 [[3119  928]
 [1361 2686]]
Accuracy on test set:    0.7171979243884359
Sensitivity:    0.6637015072893502 	 Specificity:    0.7706943414875216
Precision  : 0.7432208079690094
Area Under Curve:    0.7171979243884359
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5912 - accuracy: 0.6820 - val_loss: 0.5607 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5510 - accuracy: 0.7183 - val_loss: 0.5438 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5344 - accuracy: 0.7315 - val_loss: 0.5406 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5226 - accuracy: 0.7389 - val_loss: 0.5427 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5118 - accuracy: 0.7466 - val_loss: 0.5465 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5015 - accuracy: 0.7542 - val_loss: 0.5441 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.7648 - val_loss: 0.5459 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4763 - accuracy: 0.7725 - val_loss: 0.5468 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4652 - accuracy: 0.7786
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4652 - accuracy: 0.7786 - val_loss: 0.5507 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.490254066884526
Confusion Matrix :
 [[3000 1047]
 [1016 3031]]
Accuracy on test set:    0.7451198418581666
Sensitivity:    0.7489498393872004 	 Specificity:    0.7412898443291327
Precision  : 0.7432564982834723
Area Under Curve:    0.7451198418581666
(8094, 2560) (8094,)
Mean MCC = 0.4272 + 0.0249 and Mean AUC = 0.7130 + 0.0124
Mean Sensitivity = 0.7224 + 0.0355 and Mean Specificity = 0.7036 + 0.0403 and Mean Accuracy = 0.7130 + 0.0124
Mean Precision = 0.7103 + 0.0216





Seed   : 380784
Epoch 1/400
257/257 [==============================] - 2s 6ms/step - loss: 0.5832 - accuracy: 0.6881 - val_loss: 0.5560 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5419 - accuracy: 0.7237 - val_loss: 0.5512 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7354 - val_loss: 0.5495 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5142 - accuracy: 0.7448 - val_loss: 0.5498 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7511 - val_loss: 0.5523 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7587 - val_loss: 0.5625 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7685 - val_loss: 0.5549 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4688 - accuracy: 0.7766 - val_loss: 0.5612 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4557 - accuracy: 0.7841 - val_loss: 0.5609 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4412 - accuracy: 0.7951 - val_loss: 0.5700 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4297 - accuracy: 0.8021 - val_loss: 0.5694 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4175 - accuracy: 0.8085 - val_loss: 0.5774 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4030 - accuracy: 0.8177 - val_loss: 0.5849 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 14/400
254/257 [============================>.] - ETA: 0s - loss: 0.3924 - accuracy: 0.8239
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3925 - accuracy: 0.8238 - val_loss: 0.6001 - val_accuracy: 0.7086 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39142637127713537
Confusion Matrix :
 [[2657 1391]
 [1077 2970]]
Accuracy on test set:    0.6951204447189623
Sensitivity:    0.7338769458858414 	 Specificity:    0.6563735177865613
Precision  : 0.6810364595276313
Area Under Curve:    0.6951252318362013
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5852 - accuracy: 0.6870 - val_loss: 0.5558 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7246 - val_loss: 0.5527 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7341 - val_loss: 0.5489 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7436 - val_loss: 0.5446 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7499 - val_loss: 0.5479 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7596 - val_loss: 0.5500 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7662 - val_loss: 0.5508 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4734 - accuracy: 0.7736 - val_loss: 0.5655 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 9/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4626 - accuracy: 0.7809
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4630 - accuracy: 0.7806 - val_loss: 0.5554 - val_accuracy: 0.7120 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4217000015079056
Confusion Matrix :
 [[2838 1210]
 [1131 2916]]
Accuracy on test set:    0.7108091414453366
Sensitivity:    0.720533728687917 	 Specificity:    0.7010869565217391
Precision  : 0.7067377605428987
Area Under Curve:    0.7108103426048281
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5847 - accuracy: 0.6873 - val_loss: 0.5485 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7203 - val_loss: 0.5387 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7337 - val_loss: 0.5370 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7399 - val_loss: 0.5388 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7475 - val_loss: 0.5428 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.7551 - val_loss: 0.5469 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4880 - accuracy: 0.7619
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4883 - accuracy: 0.7619 - val_loss: 0.5379 - val_accuracy: 0.7202 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43349128427577627
Confusion Matrix :
 [[2884 1163]
 [1130 2918]]
Accuracy on test set:    0.7167387276096355
Sensitivity:    0.7208498023715415 	 Specificity:    0.7126266370150729
Precision  : 0.7150208282283754
Area Under Curve:    0.7167382196933072
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5856 - accuracy: 0.6862 - val_loss: 0.5495 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7224 - val_loss: 0.5403 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7344 - val_loss: 0.5382 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5146 - accuracy: 0.7431 - val_loss: 0.5360 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.7515 - val_loss: 0.5368 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7602 - val_loss: 0.5378 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7689 - val_loss: 0.5443 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4656 - accuracy: 0.7783 - val_loss: 0.5469 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4493 - accuracy: 0.7890 - val_loss: 0.5478 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4362 - accuracy: 0.7967 - val_loss: 0.5561 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4219 - accuracy: 0.8052 - val_loss: 0.5602 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4088 - accuracy: 0.8125 - val_loss: 0.5646 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3947 - accuracy: 0.8212 - val_loss: 0.5801 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 14/400
252/257 [============================>.] - ETA: 0s - loss: 0.3821 - accuracy: 0.8277
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3825 - accuracy: 0.8271 - val_loss: 0.5892 - val_accuracy: 0.7197 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39991858615929987
Confusion Matrix :
 [[2668 1379]
 [1055 2993]]
Accuracy on test set:    0.6993205682520074
Sensitivity:    0.7393774703557312 	 Specificity:    0.6592537682233753
Precision  : 0.684583714547118
Area Under Curve:    0.6993156192895533
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5917 - accuracy: 0.6783 - val_loss: 0.5509 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7210 - val_loss: 0.5459 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7323 - val_loss: 0.5423 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7395 - val_loss: 0.5422 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7470 - val_loss: 0.5446 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7563 - val_loss: 0.5412 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7637 - val_loss: 0.5472 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4788 - accuracy: 0.7704 - val_loss: 0.5486 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4673 - accuracy: 0.7772 - val_loss: 0.5528 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4557 - accuracy: 0.7852 - val_loss: 0.5599 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4443 - accuracy: 0.7926 - val_loss: 0.5622 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4334 - accuracy: 0.7996 - val_loss: 0.5710 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 13/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4210 - accuracy: 0.8070
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4220 - accuracy: 0.8064 - val_loss: 0.5728 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3988140458253679
Confusion Matrix :
 [[2829 1218]
 [1215 2832]]
Accuracy on test set:    0.6994069681245367
Sensitivity:    0.6997776130467013 	 Specificity:    0.6990363232023721
Precision  : 0.6992592592592592
Area Under Curve:    0.6994069681245367
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5875 - accuracy: 0.6852 - val_loss: 0.5547 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7210 - val_loss: 0.5579 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7338 - val_loss: 0.5435 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7426 - val_loss: 0.5437 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7495 - val_loss: 0.5436 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7593 - val_loss: 0.5427 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7658 - val_loss: 0.5439 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7740 - val_loss: 0.5540 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4576 - accuracy: 0.7821 - val_loss: 0.5535 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4436 - accuracy: 0.7919 - val_loss: 0.5569 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4305 - accuracy: 0.7993 - val_loss: 0.5715 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 12/400
255/257 [============================>.] - ETA: 0s - loss: 0.4195 - accuracy: 0.8069
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4196 - accuracy: 0.8070 - val_loss: 0.5695 - val_accuracy: 0.7213 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41984427049295664
Confusion Matrix :
 [[2850 1197]
 [1151 2896]]
Accuracy on test set:    0.7099085742525327
Sensitivity:    0.7155917963923895 	 Specificity:    0.704225352112676
Precision  : 0.7075494747129245
Area Under Curve:    0.7099085742525327
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5865 - accuracy: 0.6848 - val_loss: 0.5499 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7217 - val_loss: 0.5440 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7335 - val_loss: 0.5431 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7426 - val_loss: 0.5431 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7506 - val_loss: 0.5464 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
249/257 [============================>.] - ETA: 0s - loss: 0.4905 - accuracy: 0.7615
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7615 - val_loss: 0.5446 - val_accuracy: 0.7167 - lr: 0.0010
253/253 [==============================] - 0s 944us/step
Independent Testing Matthews Correlation:  0.42685007011368337
Confusion Matrix :
 [[2994 1053]
 [1269 2778]]
Accuracy on test set:    0.7131208302446257
Sensitivity:    0.6864343958487769 	 Specificity:    0.7398072646404744
Precision  : 0.7251370399373531
Area Under Curve:    0.7131208302446256
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5898 - accuracy: 0.6832 - val_loss: 0.5516 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.7230 - val_loss: 0.5414 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7322 - val_loss: 0.5395 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.7398 - val_loss: 0.5386 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7481 - val_loss: 0.5395 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4995 - accuracy: 0.7547 - val_loss: 0.5385 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4882 - accuracy: 0.7637
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4886 - accuracy: 0.7636 - val_loss: 0.5410 - val_accuracy: 0.7222 - lr: 0.0010
253/253 [==============================] - 0s 971us/step
Independent Testing Matthews Correlation:  0.43932443486123673
Confusion Matrix :
 [[2846 1201]
 [1069 2978]]
Accuracy on test set:    0.7195453422288115
Sensitivity:    0.7358537188040524 	 Specificity:    0.7032369656535705
Precision  : 0.7126106724096674
Area Under Curve:    0.7195453422288114
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5901 - accuracy: 0.6818 - val_loss: 0.5540 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7206 - val_loss: 0.5492 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5326 - accuracy: 0.7323 - val_loss: 0.5442 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7419 - val_loss: 0.5445 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7502 - val_loss: 0.5423 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7597 - val_loss: 0.5435 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4831 - accuracy: 0.7659 - val_loss: 0.5484 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4685 - accuracy: 0.7771 - val_loss: 0.5528 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4559 - accuracy: 0.7842 - val_loss: 0.5624 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4429 - accuracy: 0.7931 - val_loss: 0.5589 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4282 - accuracy: 0.8015 - val_loss: 0.5654 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4150 - accuracy: 0.8098 - val_loss: 0.5688 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 13/400
255/257 [============================>.] - ETA: 0s - loss: 0.4031 - accuracy: 0.8159
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4031 - accuracy: 0.8160 - val_loss: 0.5856 - val_accuracy: 0.7132 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4479664602540381
Confusion Matrix :
 [[2795 1252]
 [ 986 3061]]
Accuracy on test set:    0.7234988880652335
Sensitivity:    0.7563627378304917 	 Specificity:    0.6906350382999753
Precision  : 0.7097148156735451
Area Under Curve:    0.7234988880652334
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5904 - accuracy: 0.6818 - val_loss: 0.5574 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5486 - accuracy: 0.7201 - val_loss: 0.5600 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5328 - accuracy: 0.7307 - val_loss: 0.5488 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.7389 - val_loss: 0.5493 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7452 - val_loss: 0.5550 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.7548 - val_loss: 0.5533 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4897 - accuracy: 0.7629 - val_loss: 0.5524 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4787 - accuracy: 0.7693
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4785 - accuracy: 0.7694 - val_loss: 0.5575 - val_accuracy: 0.7120 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4816371037611269
Confusion Matrix :
 [[3143  904]
 [1199 2848]]
Accuracy on test set:    0.740177909562639
Sensitivity:    0.7037311588831233 	 Specificity:    0.7766246602421547
Precision  : 0.7590618336886994
Area Under Curve:    0.7401779095626391
(8094, 2560) (8094,)
Mean MCC = 0.4261 + 0.0255 and Mean AUC = 0.7128 + 0.0127
Mean Sensitivity = 0.7212 + 0.0199 and Mean Specificity = 0.7043 + 0.0333 and Mean Accuracy = 0.7128 + 0.0127
Mean Precision = 0.7101 + 0.0207





Seed   : 721340
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5862 - accuracy: 0.6854 - val_loss: 0.5619 - val_accuracy: 0.7049 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5422 - accuracy: 0.7245 - val_loss: 0.5551 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7334 - val_loss: 0.5522 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7421 - val_loss: 0.5525 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7506 - val_loss: 0.5502 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7565 - val_loss: 0.5597 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4856 - accuracy: 0.7653 - val_loss: 0.5574 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4734 - accuracy: 0.7728 - val_loss: 0.5605 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4589 - accuracy: 0.7832 - val_loss: 0.5658 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4465 - accuracy: 0.7906
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4465 - accuracy: 0.7906 - val_loss: 0.5731 - val_accuracy: 0.7087 - lr: 0.0010
253/253 [==============================] - 0s 844us/step
Independent Testing Matthews Correlation:  0.41504836775538867
Confusion Matrix :
 [[2671 1377]
 [ 998 3049]]
Accuracy on test set:    0.7066090179122916
Sensitivity:    0.7533975784531752 	 Specificity:    0.6598320158102767
Precision  : 0.6888838680524175
Area Under Curve:    0.7066147971317259
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5870 - accuracy: 0.6855 - val_loss: 0.5610 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7228 - val_loss: 0.5524 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7355 - val_loss: 0.5497 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7428 - val_loss: 0.5479 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7525 - val_loss: 0.5506 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4908 - accuracy: 0.7610 - val_loss: 0.5498 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4779 - accuracy: 0.7717 - val_loss: 0.5512 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.7791 - val_loss: 0.5502 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4506 - accuracy: 0.7881 - val_loss: 0.5646 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4391 - accuracy: 0.7953 - val_loss: 0.5650 - val_accuracy: 0.7176 - lr: 0.0010

Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4253 - accuracy: 0.8043 - val_loss: 0.5685 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4119 - accuracy: 0.8114 - val_loss: 0.5769 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4004 - accuracy: 0.8193 - val_loss: 0.5838 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3894 - accuracy: 0.8262 - val_loss: 0.5976 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 15/400
251/257 [============================>.] - ETA: 0s - loss: 0.3766 - accuracy: 0.8323
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3766 - accuracy: 0.8327 - val_loss: 0.5988 - val_accuracy: 0.7076 - lr: 0.0010
253/253 [==============================] - 0s 860us/step
Independent Testing Matthews Correlation:  0.3930027629741735
Confusion Matrix :
 [[2713 1335]
 [1124 2923]]
Accuracy on test set:    0.6962322421247684
Sensitivity:    0.7222634049913517 	 Specificity:    0.670207509881423
Precision  : 0.6864725223109441
Area Under Curve:    0.6962354574363872
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5889 - accuracy: 0.6856 - val_loss: 0.5579 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7230 - val_loss: 0.5364 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7342 - val_loss: 0.5342 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7400 - val_loss: 0.5352 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7511 - val_loss: 0.5345 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7587 - val_loss: 0.5369 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7669 - val_loss: 0.5367 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7720 - val_loss: 0.5413 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4605 - accuracy: 0.7810 - val_loss: 0.5399 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4471 - accuracy: 0.7898 - val_loss: 0.5479 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4345 - accuracy: 0.7987 - val_loss: 0.5493 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 12/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4228 - accuracy: 0.8058
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4233 - accuracy: 0.8056 - val_loss: 0.5587 - val_accuracy: 0.7193 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4066132204211111
Confusion Matrix :
 [[2698 1349]
 [1057 2991]]
Accuracy on test set:    0.7027794935145152
Sensitivity:    0.7388833992094862 	 Specificity:    0.6666666666666666
Precision  : 0.6891705069124424
Area Under Curve:    0.7027750329380765
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5881 - accuracy: 0.6830 - val_loss: 0.5468 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7235 - val_loss: 0.5391 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7346 - val_loss: 0.5376 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7427 - val_loss: 0.5418 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7496 - val_loss: 0.5378 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7581 - val_loss: 0.5425 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7653 - val_loss: 0.5413 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4721 - accuracy: 0.7751
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7751 - val_loss: 0.5439 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 762us/step
Independent Testing Matthews Correlation:  0.4339729914045495
Confusion Matrix :
 [[2896 1151]
 [1140 2908]]
Accuracy on test set:    0.7169857936998147
Sensitivity:    0.7183794466403162 	 Specificity:    0.7155917963923895
Precision  : 0.7164326188716432
Area Under Curve:    0.7169856215163528
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5844 - accuracy: 0.6875 - val_loss: 0.5549 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5418 - accuracy: 0.7235 - val_loss: 0.5468 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7349 - val_loss: 0.5446 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7429 - val_loss: 0.5447 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.7513 - val_loss: 0.5496 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4928 - accuracy: 0.7602 - val_loss: 0.5446 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7688 - val_loss: 0.5508 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4664 - accuracy: 0.7769
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4669 - accuracy: 0.7766 - val_loss: 0.5512 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 840us/step
Independent Testing Matthews Correlation:  0.4322484370531153
Confusion Matrix :
 [[2597 1450]
 [ 866 3181]]
Accuracy on test set:    0.7138621200889548
Sensitivity:    0.7860143316036571 	 Specificity:    0.6417099085742526
Precision  : 0.686892679766789
Area Under Curve:    0.7138621200889549
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6823 - val_loss: 0.5533 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7227 - val_loss: 0.5525 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7325 - val_loss: 0.5435 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7404 - val_loss: 0.5508 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7501 - val_loss: 0.5447 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7575 - val_loss: 0.5485 - val_accuracy: 0.7172 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.7646 - val_loss: 0.5484 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4731 - accuracy: 0.7746 - val_loss: 0.5513 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4609 - accuracy: 0.7835 - val_loss: 0.5604 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4475 - accuracy: 0.7905 - val_loss: 0.5611 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4352 - accuracy: 0.7994 - val_loss: 0.5622 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 12/400
254/257 [============================>.] - ETA: 0s - loss: 0.4212 - accuracy: 0.8080
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4213 - accuracy: 0.8079 - val_loss: 0.5737 - val_accuracy: 0.7126 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42327836188371043
Confusion Matrix :
 [[2886 1161]
 [1173 2874]]
Accuracy on test set:    0.7116382505559674
Sensitivity:    0.7101556708673091 	 Specificity:    0.7131208302446257
Precision  : 0.7122676579925651
Area Under Curve:    0.7116382505559675
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5887 - accuracy: 0.6826 - val_loss: 0.5531 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7235 - val_loss: 0.5435 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7339 - val_loss: 0.5436 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7416 - val_loss: 0.5384 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7486 - val_loss: 0.5410 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7572 - val_loss: 0.5367 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7648 - val_loss: 0.5388 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4728 - accuracy: 0.7743 - val_loss: 0.5454 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4602 - accuracy: 0.7834 - val_loss: 0.5507 - val_accuracy: 0.7311 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4470 - accuracy: 0.7918 - val_loss: 0.5510 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4327 - accuracy: 0.8013 - val_loss: 0.5579 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4201 - accuracy: 0.8085 - val_loss: 0.5565 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4070 - accuracy: 0.8147 - val_loss: 0.5694 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - ETA: 0s - loss: 0.3944 - accuracy: 0.8230
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3944 - accuracy: 0.8230 - val_loss: 0.5708 - val_accuracy: 0.7249 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41426295618266656
Confusion Matrix :
 [[2912 1135]
 [1236 2811]]
Accuracy on test set:    0.7070669631826044
Sensitivity:    0.6945885841363973 	 Specificity:    0.7195453422288115
Precision  : 0.7123669538773442
Area Under Curve:    0.7070669631826044
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6844 - val_loss: 0.5498 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7218 - val_loss: 0.5419 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7316 - val_loss: 0.5374 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7400 - val_loss: 0.5357 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5101 - accuracy: 0.7474 - val_loss: 0.5395 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4985 - accuracy: 0.7566 - val_loss: 0.5354 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7639 - val_loss: 0.5421 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4750 - accuracy: 0.7732 - val_loss: 0.5426 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4626 - accuracy: 0.7809 - val_loss: 0.5437 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4481 - accuracy: 0.7917 - val_loss: 0.5542 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4374 - accuracy: 0.7978 - val_loss: 0.5563 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4242 - accuracy: 0.8051 - val_loss: 0.5588 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4114 - accuracy: 0.8126 - val_loss: 0.5659 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3985 - accuracy: 0.8210 - val_loss: 0.5716 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3860 - accuracy: 0.8276 - val_loss: 0.5934 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 16/400
249/257 [============================>.] - ETA: 0s - loss: 0.3736 - accuracy: 0.8342
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3747 - accuracy: 0.8338 - val_loss: 0.5928 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44675789449367037
Confusion Matrix :
 [[2916 1131]
 [1108 2939]]
Accuracy on test set:    0.7233753397578453
Sensitivity:    0.7262169508277737 	 Specificity:    0.720533728687917
Precision  : 0.7221130221130221
Area Under Curve:    0.7233753397578454
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5936 - accuracy: 0.6802 - val_loss: 0.5506 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5488 - accuracy: 0.7195 - val_loss: 0.5410 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5344 - accuracy: 0.7302 - val_loss: 0.5368 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5223 - accuracy: 0.7391 - val_loss: 0.5392 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5105 - accuracy: 0.7481 - val_loss: 0.5364 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5006 - accuracy: 0.7551 - val_loss: 0.5356 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7615 - val_loss: 0.5553 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 8/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4782 - accuracy: 0.7704
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4785 - accuracy: 0.7700 - val_loss: 0.5440 - val_accuracy: 0.7226 - lr: 0.0010
253/253 [==============================] - 0s 847us/step
Independent Testing Matthews Correlation:  0.4537761702257309
Confusion Matrix :
 [[3080  967]
 [1248 2799]]
Accuracy on test set:    0.7263404991351619
Sensitivity:    0.6916234247590808 	 Specificity:    0.7610575735112429
Precision  : 0.7432288900690388
Area Under Curve:    0.7263404991351619
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5912 - accuracy: 0.6825 - val_loss: 0.5555 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5497 - accuracy: 0.7189 - val_loss: 0.5432 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5344 - accuracy: 0.7311 - val_loss: 0.5403 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5227 - accuracy: 0.7382 - val_loss: 0.5425 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5135 - accuracy: 0.7476 - val_loss: 0.5418 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.7551 - val_loss: 0.5424 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4863 - accuracy: 0.7660 - val_loss: 0.5458 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4729 - accuracy: 0.7745
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4736 - accuracy: 0.7737 - val_loss: 0.5489 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4658428833565045
Confusion Matrix :
 [[3000 1047]
 [1115 2932]]
Accuracy on test set:    0.7328885594267358
Sensitivity:    0.724487274524339 	 Specificity:    0.7412898443291327
Precision  : 0.7368685599396834
Area Under Curve:    0.7328885594267358
(8094, 2560) (8094,)
Mean MCC = 0.4285 + 0.0214 and Mean AUC = 0.7138 + 0.0107
Mean Sensitivity = 0.7266 + 0.0265 and Mean Specificity = 0.7010 + 0.0369 and Mean Accuracy = 0.7138 + 0.0107
Mean Precision = 0.7095 + 0.0200





Seed   : 460316
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5877 - accuracy: 0.6860 - val_loss: 0.5633 - val_accuracy: 0.7019 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7252 - val_loss: 0.5523 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7351 - val_loss: 0.5551 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7430 - val_loss: 0.5508 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7520 - val_loss: 0.5492 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7588 - val_loss: 0.5539 - val_accuracy: 0.7035 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7687 - val_loss: 0.5553 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7757 - val_loss: 0.5565 - val_accuracy: 0.7054 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4573 - accuracy: 0.7835 - val_loss: 0.5633 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4468 - accuracy: 0.7914
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4468 - accuracy: 0.7915 - val_loss: 0.5621 - val_accuracy: 0.7034 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.395848607326354
Confusion Matrix :
 [[2707 1341]
 [1107 2940]]
Accuracy on test set:    0.6975911056207535
Sensitivity:    0.72646404744255 	 Specificity:    0.6687252964426877
Precision  : 0.6867554309740714
Area Under Curve:    0.6975946719426188
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5856 - accuracy: 0.6860 - val_loss: 0.5629 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7232 - val_loss: 0.5556 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7349 - val_loss: 0.5509 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7411 - val_loss: 0.5551 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7487 - val_loss: 0.5549 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7555 - val_loss: 0.5590 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7635 - val_loss: 0.5569 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.7701 - val_loss: 0.5559 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4669 - accuracy: 0.7790
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7788 - val_loss: 0.5598 - val_accuracy: 0.7071 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42418450961249243
Confusion Matrix :
 [[2605 1443]
 [ 903 3144]]
Accuracy on test set:    0.7101914762198889
Sensitivity:    0.7768717568569311 	 Specificity:    0.6435276679841897
Precision  : 0.6854153041203401
Area Under Curve:    0.7101997124205605
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5867 - accuracy: 0.6840 - val_loss: 0.5508 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7235 - val_loss: 0.5397 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7344 - val_loss: 0.5365 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7417 - val_loss: 0.5341 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7485 - val_loss: 0.5382 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7588 - val_loss: 0.5351 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4836 - accuracy: 0.7662 - val_loss: 0.5406 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4709 - accuracy: 0.7749
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.7750 - val_loss: 0.5469 - val_accuracy: 0.7230 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4359144828425522
Confusion Matrix :
 [[2968 1079]
 [1205 2843]]
Accuracy on test set:    0.7178505250154417
Sensitivity:    0.7023221343873518 	 Specificity:    0.7333827526562886
Precision  : 0.7248852626211116
Area Under Curve:    0.7178524435218202
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5852 - accuracy: 0.6849 - val_loss: 0.5486 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7219 - val_loss: 0.5391 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7323 - val_loss: 0.5352 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7400 - val_loss: 0.5368 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7479 - val_loss: 0.5363 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5003 - accuracy: 0.7538 - val_loss: 0.5323 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4897 - accuracy: 0.7616 - val_loss: 0.5340 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4794 - accuracy: 0.7697 - val_loss: 0.5407 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4669 - accuracy: 0.7772 - val_loss: 0.5483 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4572 - accuracy: 0.7855 - val_loss: 0.5437 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4433 - accuracy: 0.7933
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4433 - accuracy: 0.7933 - val_loss: 0.5503 - val_accuracy: 0.7255 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41845906600444277
Confusion Matrix :
 [[2725 1322]
 [1036 3012]]
Accuracy on test set:    0.7087090796788141
Sensitivity:    0.7440711462450593 	 Specificity:    0.6733382752656288
Precision  : 0.6949700046146746
Area Under Curve:    0.708704710755344
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5864 - accuracy: 0.6844 - val_loss: 0.5604 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7237 - val_loss: 0.5479 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7317 - val_loss: 0.5479 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7397 - val_loss: 0.5498 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7480 - val_loss: 0.5527 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7550 - val_loss: 0.5536 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4848 - accuracy: 0.7652
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4848 - accuracy: 0.7652 - val_loss: 0.5633 - val_accuracy: 0.7089 - lr: 0.0010
253/253 [==============================] - 0s 959us/step
Independent Testing Matthews Correlation:  0.42402613363929426
Confusion Matrix :
 [[3095  952]
 [1389 2658]]
Accuracy on test set:    0.7107734124042501
Sensitivity:    0.6567828020756116 	 Specificity:    0.7647640227328886
Precision  : 0.7362880886426593
Area Under Curve:    0.7107734124042501
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5898 - accuracy: 0.6831 - val_loss: 0.5569 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7240 - val_loss: 0.5486 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7339 - val_loss: 0.5461 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7412 - val_loss: 0.5474 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7477 - val_loss: 0.5460 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7569 - val_loss: 0.5459 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4837 - accuracy: 0.7656
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7656 - val_loss: 0.5504 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 855us/step
Independent Testing Matthews Correlation:  0.43285220531521124
Confusion Matrix :
 [[2989 1058]
 [1239 2808]]
Accuracy on test set:    0.7162095379293304
Sensitivity:    0.6938472942920682 	 Specificity:    0.7385717815665925
Precision  : 0.7263321262286602
Area Under Curve:    0.7162095379293304
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5902 - accuracy: 0.6813 - val_loss: 0.5551 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7233 - val_loss: 0.5475 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7346 - val_loss: 0.5440 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5148 - accuracy: 0.7436 - val_loss: 0.5439 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7525 - val_loss: 0.5468 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4891 - accuracy: 0.7601 - val_loss: 0.5468 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4785 - accuracy: 0.7689 - val_loss: 0.5500 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4634 - accuracy: 0.7785 - val_loss: 0.5546 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4513 - accuracy: 0.7864
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4510 - accuracy: 0.7869 - val_loss: 0.5604 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4230839783856542
Confusion Matrix :
 [[2847 1200]
 [1135 2912]]
Accuracy on test set:    0.7115147022485792
Sensitivity:    0.7195453422288115 	 Specificity:    0.7034840622683469
Precision  : 0.708171206225681
Area Under Curve:    0.7115147022485793
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5904 - accuracy: 0.6795 - val_loss: 0.5534 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7208 - val_loss: 0.5447 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7330 - val_loss: 0.5428 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7412 - val_loss: 0.5436 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7484 - val_loss: 0.5396 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.7542 - val_loss: 0.5455 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4891 - accuracy: 0.7627 - val_loss: 0.5455 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4801 - accuracy: 0.7689 - val_loss: 0.5435 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4659 - accuracy: 0.7777 - val_loss: 0.5519 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4544 - accuracy: 0.7841 - val_loss: 0.5520 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4433 - accuracy: 0.7931 - val_loss: 0.5561 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4297 - accuracy: 0.8013 - val_loss: 0.5668 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 13/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4136 - accuracy: 0.8090
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4144 - accuracy: 0.8081 - val_loss: 0.5613 - val_accuracy: 0.7238 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44626500120638013
Confusion Matrix :
 [[2939 1108]
 [1133 2914]]
Accuracy on test set:    0.7231282431430689
Sensitivity:    0.7200395354583642 	 Specificity:    0.7262169508277737
Precision  : 0.7245151665837891
Area Under Curve:    0.7231282431430688
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5955 - accuracy: 0.6780 - val_loss: 0.5540 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5504 - accuracy: 0.7210 - val_loss: 0.5457 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5357 - accuracy: 0.7295 - val_loss: 0.5442 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5235 - accuracy: 0.7391 - val_loss: 0.5432 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7466 - val_loss: 0.5395 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.7559 - val_loss: 0.5448 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4891 - accuracy: 0.7620 - val_loss: 0.5450 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4766 - accuracy: 0.7732 - val_loss: 0.5460 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4628 - accuracy: 0.7827 - val_loss: 0.5476 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4492 - accuracy: 0.7893 - val_loss: 0.5504 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4381 - accuracy: 0.7970 - val_loss: 0.5593 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4239 - accuracy: 0.8052 - val_loss: 0.5693 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 13/400
250/257 [============================>.] - ETA: 0s - loss: 0.4113 - accuracy: 0.8122
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4115 - accuracy: 0.8122 - val_loss: 0.5758 - val_accuracy: 0.7157 - lr: 0.0010
253/253 [==============================] - 0s 972us/step
Independent Testing Matthews Correlation:  0.4525612302503757
Confusion Matrix :
 [[2795 1252]
 [ 968 3079]]
Accuracy on test set:    0.7257227575982209
Sensitivity:    0.7608104768964665 	 Specificity:    0.6906350382999753
Precision  : 0.7109212652966982
Area Under Curve:    0.7257227575982209
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5918 - accuracy: 0.6816 - val_loss: 0.5563 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7198 - val_loss: 0.5430 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5349 - accuracy: 0.7300 - val_loss: 0.5431 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5232 - accuracy: 0.7389 - val_loss: 0.5444 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5128 - accuracy: 0.7466 - val_loss: 0.5425 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5019 - accuracy: 0.7539 - val_loss: 0.5420 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7623 - val_loss: 0.5508 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4792 - accuracy: 0.7709 - val_loss: 0.5471 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4655 - accuracy: 0.7797 - val_loss: 0.5508 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4517 - accuracy: 0.7900 - val_loss: 0.5548 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4399 - accuracy: 0.7957 - val_loss: 0.5606 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4263 - accuracy: 0.8048 - val_loss: 0.5663 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4120 - accuracy: 0.8124 - val_loss: 0.5741 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - ETA: 0s - loss: 0.4010 - accuracy: 0.8189
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4010 - accuracy: 0.8189 - val_loss: 0.5862 - val_accuracy: 0.7152 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4799621529446214
Confusion Matrix :
 [[2917 1130]
 [ 976 3071]]
Accuracy on test set:    0.7398072646404744
Sensitivity:    0.7588337039782554 	 Specificity:    0.7207808253026934
Precision  : 0.7310164246607951
Area Under Curve:    0.7398072646404743
(8094, 2560) (8094,)
Mean MCC = 0.4333 + 0.0215 and Mean AUC = 0.7162 + 0.0109
Mean Sensitivity = 0.7260 + 0.0342 and Mean Specificity = 0.7063 + 0.0353 and Mean Accuracy = 0.7161 + 0.0109
Mean Precision = 0.7129 + 0.0177





Seed   : 141374
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5846 - accuracy: 0.6880 - val_loss: 0.5576 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7243 - val_loss: 0.5505 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7329 - val_loss: 0.5502 - val_accuracy: 0.7152 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7419 - val_loss: 0.5490 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7482 - val_loss: 0.5488 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7566 - val_loss: 0.5515 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 7/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4832 - accuracy: 0.7665
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7669 - val_loss: 0.5566 - val_accuracy: 0.7141 - lr: 0.0010
253/253 [==============================] - 0s 973us/step
Independent Testing Matthews Correlation:  0.4061717951650129
Confusion Matrix :
 [[2760 1288]
 [1117 2930]]
Accuracy on test set:    0.7029030265596047
Sensitivity:    0.7239930812947862 	 Specificity:    0.6818181818181818
Precision  : 0.6946420104314841
Area Under Curve:    0.702905631556484
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5866 - accuracy: 0.6866 - val_loss: 0.5573 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7242 - val_loss: 0.5501 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7358 - val_loss: 0.5437 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7429 - val_loss: 0.5450 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7500 - val_loss: 0.5458 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7563 - val_loss: 0.5492 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.7662 - val_loss: 0.5504 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4731 - accuracy: 0.7737
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4729 - accuracy: 0.7736 - val_loss: 0.5635 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4194867529059675
Confusion Matrix :
 [[2634 1414]
 [ 947 3100]]
Accuracy on test set:    0.7083384805435454
Sensitivity:    0.7659995058067705 	 Specificity:    0.650691699604743
Precision  : 0.6867523260965884
Area Under Curve:    0.7083456027057569
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5850 - accuracy: 0.6876 - val_loss: 0.5514 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7240 - val_loss: 0.5439 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7348 - val_loss: 0.5429 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7440 - val_loss: 0.5424 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7517 - val_loss: 0.5424 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7599 - val_loss: 0.5434 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4831 - accuracy: 0.7681 - val_loss: 0.5474 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4731 - accuracy: 0.7743 - val_loss: 0.5501 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4625 - accuracy: 0.7815
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4625 - accuracy: 0.7815 - val_loss: 0.5542 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 816us/step
Independent Testing Matthews Correlation:  0.42970753959930924
Confusion Matrix :
 [[2758 1289]
 [1023 3025]]
Accuracy on test set:    0.7143915997529339
Sensitivity:    0.7472826086956522 	 Specificity:    0.6814924635532493
Precision  : 0.701205377839592
Area Under Curve:    0.7143875361244508
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5896 - accuracy: 0.6815 - val_loss: 0.5522 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7221 - val_loss: 0.5403 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7333 - val_loss: 0.5375 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7393 - val_loss: 0.5361 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5103 - accuracy: 0.7460 - val_loss: 0.5465 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.7546 - val_loss: 0.5495 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7630 - val_loss: 0.5427 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4782 - accuracy: 0.7686
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7686 - val_loss: 0.5435 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42093879574675513
Confusion Matrix :
 [[2840 1207]
 [1137 2911]]
Accuracy on test set:    0.710438542310068
Sensitivity:    0.7191205533596838 	 Specificity:    0.7017543859649122
Precision  : 0.7068965517241379
Area Under Curve:    0.710437469662298
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5882 - accuracy: 0.6844 - val_loss: 0.5520 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7234 - val_loss: 0.5466 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7331 - val_loss: 0.5431 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7397 - val_loss: 0.5435 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5093 - accuracy: 0.7465 - val_loss: 0.5500 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7538 - val_loss: 0.5486 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7634 - val_loss: 0.5500 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4773 - accuracy: 0.7710 - val_loss: 0.5510 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7786 - val_loss: 0.5530 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4534 - accuracy: 0.7850 - val_loss: 0.5626 - val_accuracy: 0.7134 - lr: 0.0010

Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4405 - accuracy: 0.7936
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4403 - accuracy: 0.7937 - val_loss: 0.5652 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41973370301625024
Confusion Matrix :
 [[2929 1118]
 [1231 2816]]
Accuracy on test set:    0.7097850259451446
Sensitivity:    0.6958240672102792 	 Specificity:    0.7237459846800098
Precision  : 0.7158108795119471
Area Under Curve:    0.7097850259451445
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5854 - accuracy: 0.6850 - val_loss: 0.5603 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7233 - val_loss: 0.5536 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7333 - val_loss: 0.5450 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7416 - val_loss: 0.5418 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7482 - val_loss: 0.5428 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7558 - val_loss: 0.5427 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7641 - val_loss: 0.5513 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7717 - val_loss: 0.5527 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4634 - accuracy: 0.7794 - val_loss: 0.5497 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4523 - accuracy: 0.7864 - val_loss: 0.5636 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4409 - accuracy: 0.7948 - val_loss: 0.5561 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4284 - accuracy: 0.8036 - val_loss: 0.5696 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4161 - accuracy: 0.8096 - val_loss: 0.5832 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4057 - accuracy: 0.8157 - val_loss: 0.5730 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 15/400
255/257 [============================>.] - ETA: 0s - loss: 0.3949 - accuracy: 0.8215
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3946 - accuracy: 0.8216 - val_loss: 0.5909 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.426289399021533
Confusion Matrix :
 [[2783 1264]
 [1060 2987]]
Accuracy on test set:    0.7128737336298493
Sensitivity:    0.7380775883370397 	 Specificity:    0.6876698789226587
Precision  : 0.7026581980710421
Area Under Curve:    0.7128737336298492
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5863 - accuracy: 0.6851 - val_loss: 0.5480 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7227 - val_loss: 0.5450 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7336 - val_loss: 0.5389 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7436 - val_loss: 0.5405 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7489 - val_loss: 0.5417 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.7594 - val_loss: 0.5465 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.7663 - val_loss: 0.5564 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4703 - accuracy: 0.7753 - val_loss: 0.5506 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4577 - accuracy: 0.7812 - val_loss: 0.5520 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4464 - accuracy: 0.7911 - val_loss: 0.5501 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4333 - accuracy: 0.7984 - val_loss: 0.5647 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4200 - accuracy: 0.8052 - val_loss: 0.5662 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 13/400
251/257 [============================>.] - ETA: 0s - loss: 0.4083 - accuracy: 0.8121
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4091 - accuracy: 0.8118 - val_loss: 0.5685 - val_accuracy: 0.7207 - lr: 0.0010
253/253 [==============================] - 0s 975us/step
Independent Testing Matthews Correlation:  0.40228362313462335
Confusion Matrix :
 [[2646 1401]
 [1025 3022]]
Accuracy on test set:    0.700271806276254
Sensitivity:    0.746725969854213 	 Specificity:    0.653817642698295
Precision  : 0.683246665159394
Area Under Curve:    0.7002718062762541
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5885 - accuracy: 0.6836 - val_loss: 0.5469 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7232 - val_loss: 0.5392 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7339 - val_loss: 0.5362 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7430 - val_loss: 0.5397 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5022 - accuracy: 0.7520 - val_loss: 0.5344 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7599 - val_loss: 0.5409 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7686 - val_loss: 0.5468 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4644 - accuracy: 0.7774 - val_loss: 0.5477 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4512 - accuracy: 0.7886 - val_loss: 0.5450 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4377 - accuracy: 0.7962 - val_loss: 0.5653 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4255 - accuracy: 0.8039 - val_loss: 0.5625 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 12/400
250/257 [============================>.] - ETA: 0s - loss: 0.4107 - accuracy: 0.8110
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4109 - accuracy: 0.8110 - val_loss: 0.5661 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 857us/step
Independent Testing Matthews Correlation:  0.4206304156464098
Confusion Matrix :
 [[3176  871]
 [1494 2553]]
Accuracy on test set:    0.7078082530269335
Sensitivity:    0.6308376575240919 	 Specificity:    0.7847788485297752
Precision  : 0.7456191588785047
Area Under Curve:    0.7078082530269335
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6836 - val_loss: 0.5526 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7222 - val_loss: 0.5408 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5324 - accuracy: 0.7312 - val_loss: 0.5378 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7400 - val_loss: 0.5359 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7492 - val_loss: 0.5368 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7566 - val_loss: 0.5373 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7651 - val_loss: 0.5417 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4719 - accuracy: 0.7726
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7727 - val_loss: 0.5467 - val_accuracy: 0.7235 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4626322543290729
Confusion Matrix :
 [[2791 1256]
 [ 925 3122]]
Accuracy on test set:    0.7305411415863603
Sensitivity:    0.7714356313318508 	 Specificity:    0.6896466518408698
Precision  : 0.7131110095934217
Area Under Curve:    0.7305411415863601
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5909 - accuracy: 0.6805 - val_loss: 0.5522 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5489 - accuracy: 0.7190 - val_loss: 0.5415 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5358 - accuracy: 0.7291 - val_loss: 0.5414 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5235 - accuracy: 0.7385 - val_loss: 0.5388 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7451 - val_loss: 0.5393 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7531 - val_loss: 0.5397 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4921 - accuracy: 0.7616
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4928 - accuracy: 0.7612 - val_loss: 0.5437 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 838us/step
Independent Testing Matthews Correlation:  0.4920069118736149
Confusion Matrix :
 [[3044 1003]
 [1053 2994]]
Accuracy on test set:    0.7459846800098838
Sensitivity:    0.7398072646404744 	 Specificity:    0.7521620953792933
Precision  : 0.7490617963472604
Area Under Curve:    0.7459846800098838
(8094, 2560) (8094,)
Mean MCC = 0.4300 + 0.0258 and Mean AUC = 0.7143 + 0.0131
Mean Sensitivity = 0.7279 + 0.0386 and Mean Specificity = 0.7008 + 0.0400 and Mean Accuracy = 0.7143 + 0.0131
Mean Precision = 0.7099 + 0.0211





Seed   : 745752
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5842 - accuracy: 0.6873 - val_loss: 0.5562 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5422 - accuracy: 0.7252 - val_loss: 0.5516 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.7369 - val_loss: 0.5528 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5139 - accuracy: 0.7445 - val_loss: 0.5506 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7509 - val_loss: 0.5479 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7590 - val_loss: 0.5513 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7683 - val_loss: 0.5547 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7751 - val_loss: 0.5599 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4584 - accuracy: 0.7828 - val_loss: 0.5609 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4444 - accuracy: 0.7916 - val_loss: 0.5647 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4326 - accuracy: 0.7985 - val_loss: 0.5802 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4202 - accuracy: 0.8051 - val_loss: 0.5820 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4075 - accuracy: 0.8128 - val_loss: 0.5842 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 14/400
244/257 [===========================>..] - ETA: 0s - loss: 0.3987 - accuracy: 0.8184
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3987 - accuracy: 0.8187 - val_loss: 0.5995 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.39465554924838814
Confusion Matrix :
 [[2663 1385]
 [1070 2977]]
Accuracy on test set:    0.6967263743051266
Sensitivity:    0.735606622189276 	 Specificity:    0.6578557312252964
Precision  : 0.6824850985786337
Area Under Curve:    0.6967311767072861
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5871 - accuracy: 0.6827 - val_loss: 0.5665 - val_accuracy: 0.7036 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7238 - val_loss: 0.5528 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5267 - accuracy: 0.7353 - val_loss: 0.5522 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7433 - val_loss: 0.5488 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7522 - val_loss: 0.5517 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.7588 - val_loss: 0.5494 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7688 - val_loss: 0.5650 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4697 - accuracy: 0.7749 - val_loss: 0.5594 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4580 - accuracy: 0.7843 - val_loss: 0.5685 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 10/400

247/257 [===========================>..] - ETA: 0s - loss: 0.4448 - accuracy: 0.7914
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4454 - accuracy: 0.7910 - val_loss: 0.5643 - val_accuracy: 0.7094 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42671922399982937
Confusion Matrix :
 [[2799 1249]
 [1073 2974]]
Accuracy on test set:    0.7131562693020383
Sensitivity:    0.7348653323449469 	 Specificity:    0.6914525691699605
Precision  : 0.7042386928723656
Area Under Curve:    0.7131589507574537
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5909 - accuracy: 0.6818 - val_loss: 0.5573 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7214 - val_loss: 0.5437 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7321 - val_loss: 0.5480 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7405 - val_loss: 0.5406 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7512 - val_loss: 0.5423 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7572 - val_loss: 0.5478 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4817 - accuracy: 0.7683 - val_loss: 0.5505 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7766 - val_loss: 0.5482 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 9/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4574 - accuracy: 0.7850
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4586 - accuracy: 0.7842 - val_loss: 0.5535 - val_accuracy: 0.7130 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43202398482936094
Confusion Matrix :
 [[2969 1078]
 [1222 2826]]
Accuracy on test set:    0.7158739962940086
Sensitivity:    0.6981225296442688 	 Specificity:    0.733629849271065
Precision  : 0.7238729508196722
Area Under Curve:    0.7158761894576668
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5870 - accuracy: 0.6850 - val_loss: 0.5459 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7218 - val_loss: 0.5374 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7340 - val_loss: 0.5333 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7415 - val_loss: 0.5340 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7507 - val_loss: 0.5363 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7584 - val_loss: 0.5385 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7663 - val_loss: 0.5424 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4705 - accuracy: 0.7757
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7757 - val_loss: 0.5513 - val_accuracy: 0.7268 - lr: 0.0010
253/253 [==============================] - 0s 857us/step
Independent Testing Matthews Correlation:  0.4384708596875546
Confusion Matrix :
 [[2787 1260]
 [1016 3032]]
Accuracy on test set:    0.7188387893761581
Sensitivity:    0.7490118577075099 	 Specificity:    0.6886582653817642
Precision  : 0.706430568499534
Area Under Curve:    0.718835061544637
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5869 - accuracy: 0.6853 - val_loss: 0.5535 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7239 - val_loss: 0.5448 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7321 - val_loss: 0.5433 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7407 - val_loss: 0.5409 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.7473 - val_loss: 0.5401 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7561 - val_loss: 0.5452 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7635 - val_loss: 0.5463 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.7718 - val_loss: 0.5467 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4640 - accuracy: 0.7784 - val_loss: 0.5571 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4520 - accuracy: 0.7872 - val_loss: 0.5510 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4385 - accuracy: 0.7957
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4390 - accuracy: 0.7953 - val_loss: 0.5597 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40906598827654095
Confusion Matrix :
 [[2669 1378]
 [1020 3027]]
Accuracy on test set:    0.7037311588831233
Sensitivity:    0.7479614529280949 	 Specificity:    0.6595008648381517
Precision  : 0.6871736662883088
Area Under Curve:    0.7037311588831233
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5887 - accuracy: 0.6830 - val_loss: 0.5555 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7214 - val_loss: 0.5478 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7339 - val_loss: 0.5446 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7417 - val_loss: 0.5459 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7508 - val_loss: 0.5450 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7563 - val_loss: 0.5452 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4863 - accuracy: 0.7645 - val_loss: 0.5471 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7727 - val_loss: 0.5521 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4606 - accuracy: 0.7813 - val_loss: 0.5541 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4484 - accuracy: 0.7908 - val_loss: 0.5622 - val_accuracy: 0.7146 - lr: 0.0010

Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4349 - accuracy: 0.7996
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4348 - accuracy: 0.7996 - val_loss: 0.5672 - val_accuracy: 0.7170 - lr: 0.0010
253/253 [==============================] - 0s 845us/step
Independent Testing Matthews Correlation:  0.42666627977419797
Confusion Matrix :
 [[2772 1275]
 [1048 2999]]
Accuracy on test set:    0.7129972819372374
Sensitivity:    0.7410427477143563 	 Specificity:    0.6849518161601186
Precision  : 0.701684604585868
Area Under Curve:    0.7129972819372375
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5875 - accuracy: 0.6845 - val_loss: 0.5534 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7221 - val_loss: 0.5572 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7316 - val_loss: 0.5443 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7423 - val_loss: 0.5443 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7496 - val_loss: 0.5471 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7575 - val_loss: 0.5469 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7671 - val_loss: 0.5507 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7743 - val_loss: 0.5489 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4569 - accuracy: 0.7826 - val_loss: 0.5570 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4451 - accuracy: 0.7918 - val_loss: 0.5563 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4337 - accuracy: 0.7985 - val_loss: 0.5716 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4211 - accuracy: 0.8075 - val_loss: 0.5704 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4066 - accuracy: 0.8148 - val_loss: 0.5722 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3940 - accuracy: 0.8223 - val_loss: 0.5860 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3824 - accuracy: 0.8294 - val_loss: 0.5886 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3737 - accuracy: 0.8329 - val_loss: 0.5959 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 17/400
247/257 [===========================>..] - ETA: 0s - loss: 0.3631 - accuracy: 0.8371
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3640 - accuracy: 0.8368 - val_loss: 0.6092 - val_accuracy: 0.7111 - lr: 0.0010
253/253 [==============================] - 0s 814us/step
Independent Testing Matthews Correlation:  0.4074909806145501
Confusion Matrix :
 [[2872 1175]
 [1223 2824]]
Accuracy on test set:    0.7037311588831233
Sensitivity:    0.6978008401284902 	 Specificity:    0.7096614776377563
Precision  : 0.706176544136034
Area Under Curve:    0.7037311588831232
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6831 - val_loss: 0.5512 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7228 - val_loss: 0.5437 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7342 - val_loss: 0.5434 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7438 - val_loss: 0.5451 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5033 - accuracy: 0.7526 - val_loss: 0.5397 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7589 - val_loss: 0.5435 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7695 - val_loss: 0.5496 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4695 - accuracy: 0.7762 - val_loss: 0.5476 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4559 - accuracy: 0.7837 - val_loss: 0.5546 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4441 - accuracy: 0.7941
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4445 - accuracy: 0.7937 - val_loss: 0.5547 - val_accuracy: 0.7175 - lr: 0.0010
253/253 [==============================] - 0s 779us/step
Independent Testing Matthews Correlation:  0.4349496523946631
Confusion Matrix :
 [[2937 1110]
 [1177 2870]]
Accuracy on test set:    0.7174450210032123
Sensitivity:    0.7091672844082036 	 Specificity:    0.7257227575982209
Precision  : 0.7211055276381909
Area Under Curve:    0.7174450210032123
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5907 - accuracy: 0.6822 - val_loss: 0.5590 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5477 - accuracy: 0.7211 - val_loss: 0.5505 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7320 - val_loss: 0.5513 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5204 - accuracy: 0.7400 - val_loss: 0.5465 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7494 - val_loss: 0.5489 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.7539 - val_loss: 0.5528 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4865 - accuracy: 0.7644
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4867 - accuracy: 0.7643 - val_loss: 0.5509 - val_accuracy: 0.7116 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46149483378364015
Confusion Matrix :
 [[2812 1235]
 [ 949 3098]]
Accuracy on test set:    0.7301704966641956
Sensitivity:    0.7655053125772177 	 Specificity:    0.6948356807511737
Precision  : 0.7149780752365567
Area Under Curve:    0.7301704966641956
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5908 - accuracy: 0.6832 - val_loss: 0.5568 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5485 - accuracy: 0.7218 - val_loss: 0.5540 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5340 - accuracy: 0.7311 - val_loss: 0.5531 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5211 - accuracy: 0.7396 - val_loss: 0.5488 - val_accuracy: 0.7152 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5105 - accuracy: 0.7469 - val_loss: 0.5489 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5000 - accuracy: 0.7570 - val_loss: 0.5494 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.7644 - val_loss: 0.5522 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.7730 - val_loss: 0.5553 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4676 - accuracy: 0.7792 - val_loss: 0.5630 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4547 - accuracy: 0.7893 - val_loss: 0.5568 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4430 - accuracy: 0.7946 - val_loss: 0.5649 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 12/400
253/257 [============================>.] - ETA: 0s - loss: 0.4282 - accuracy: 0.8045
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4286 - accuracy: 0.8043 - val_loss: 0.5671 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4762436567770976
Confusion Matrix :
 [[3121  926]
 [1198 2849]]
Accuracy on test set:    0.737583395107487
Sensitivity:    0.7039782554978997 	 Specificity:    0.7711885347170744
Precision  : 0.7547019867549669
Area Under Curve:    0.737583395107487
(8094, 2560) (8094,)
Mean MCC = 0.4308 + 0.0233 and Mean AUC = 0.7150 + 0.0116
Mean Sensitivity = 0.7283 + 0.0229 and Mean Specificity = 0.7017 + 0.0329 and Mean Accuracy = 0.7150 + 0.0116
Mean Precision = 0.7103 + 0.0194





Seed   : 260384
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5846 - accuracy: 0.6857 - val_loss: 0.5612 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7241 - val_loss: 0.5480 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5257 - accuracy: 0.7366 - val_loss: 0.5495 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5123 - accuracy: 0.7445 - val_loss: 0.5447 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7539 - val_loss: 0.5549 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.7619 - val_loss: 0.5506 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 7/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4767 - accuracy: 0.7707
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4773 - accuracy: 0.7702 - val_loss: 0.5513 - val_accuracy: 0.7149 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.403959062987644
Confusion Matrix :
 [[2754 1294]
 [1120 2927]]
Accuracy on test set:    0.7017912291537987
Sensitivity:    0.7232517914504571 	 Specificity:    0.6803359683794467
Precision  : 0.6934375740345889
Area Under Curve:    0.7017938799149518
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5886 - accuracy: 0.6824 - val_loss: 0.5573 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7247 - val_loss: 0.5529 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7345 - val_loss: 0.5462 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7438 - val_loss: 0.5422 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5034 - accuracy: 0.7524 - val_loss: 0.5441 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.7616 - val_loss: 0.5503 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7682 - val_loss: 0.5490 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4669 - accuracy: 0.7779 - val_loss: 0.5523 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4523 - accuracy: 0.7867 - val_loss: 0.5591 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4399 - accuracy: 0.7960 - val_loss: 0.5571 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 11/400
250/257 [============================>.] - ETA: 0s - loss: 0.4252 - accuracy: 0.8047
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4255 - accuracy: 0.8044 - val_loss: 0.5626 - val_accuracy: 0.7108 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41666274378943624
Confusion Matrix :
 [[2935 1113]
 [1249 2798]]
Accuracy on test set:    0.7082149474984558
Sensitivity:    0.6913763281443044 	 Specificity:    0.7250494071146245
Precision  : 0.7154180516491946
Area Under Curve:    0.7082128676294644
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5865 - accuracy: 0.6858 - val_loss: 0.5482 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7237 - val_loss: 0.5414 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7341 - val_loss: 0.5402 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7410 - val_loss: 0.5394 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7518 - val_loss: 0.5409 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7606 - val_loss: 0.5465 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7688 - val_loss: 0.5423 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4675 - accuracy: 0.7758 - val_loss: 0.5462 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4543 - accuracy: 0.7844 - val_loss: 0.5541 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4428 - accuracy: 0.7928 - val_loss: 0.5594 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4306 - accuracy: 0.7998 - val_loss: 0.5637 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4172 - accuracy: 0.8068 - val_loss: 0.5690 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4038 - accuracy: 0.8158 - val_loss: 0.5707 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3951 - accuracy: 0.8206 - val_loss: 0.5795 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 15/400
245/257 [===========================>..] - ETA: 0s - loss: 0.3797 - accuracy: 0.8306
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.3799 - accuracy: 0.8306 - val_loss: 0.5999 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41727959644294765
Confusion Matrix :
 [[2821 1226]
 [1133 2915]]
Accuracy on test set:    0.7085855466337245
Sensitivity:    0.720108695652174 	 Specificity:    0.6970595502841611
Precision  : 0.7039362472832649
Area Under Curve:    0.7085841229681675
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5852 - accuracy: 0.6853 - val_loss: 0.5475 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5423 - accuracy: 0.7255 - val_loss: 0.5418 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7335 - val_loss: 0.5396 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7425 - val_loss: 0.5398 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7503 - val_loss: 0.5438 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7577 - val_loss: 0.5415 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.7665 - val_loss: 0.5443 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4743 - accuracy: 0.7704 - val_loss: 0.5495 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4627 - accuracy: 0.7808 - val_loss: 0.5557 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4496 - accuracy: 0.7889
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4498 - accuracy: 0.7888 - val_loss: 0.5692 - val_accuracy: 0.7257 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41227417107629133
Confusion Matrix :
 [[2559 1488]
 [ 908 3140]]
Accuracy on test set:    0.7040148239654107
Sensitivity:    0.775691699604743 	 Specificity:    0.6323202372127502
Precision  : 0.6784788245462403
Area Under Curve:    0.7040059684087465
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5850 - accuracy: 0.6852 - val_loss: 0.5547 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7228 - val_loss: 0.5394 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5255 - accuracy: 0.7351 - val_loss: 0.5362 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7421 - val_loss: 0.5363 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.7512 - val_loss: 0.5388 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7580 - val_loss: 0.5394 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7676 - val_loss: 0.5396 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4731 - accuracy: 0.7727 - val_loss: 0.5443 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4599 - accuracy: 0.7809 - val_loss: 0.5508 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4474 - accuracy: 0.7906
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4473 - accuracy: 0.7906 - val_loss: 0.5501 - val_accuracy: 0.7260 - lr: 0.0010
253/253 [==============================] - 0s 930us/step
Independent Testing Matthews Correlation:  0.4080015541294027
Confusion Matrix :
 [[2952 1095]
 [1303 2744]]
Accuracy on test set:    0.7037311588831233
Sensitivity:    0.6780331109463801 	 Specificity:    0.7294292068198666
Precision  : 0.7147694712164626
Area Under Curve:    0.7037311588831234
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6833 - val_loss: 0.5506 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7215 - val_loss: 0.5412 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7328 - val_loss: 0.5368 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7423 - val_loss: 0.5366 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7524 - val_loss: 0.5376 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.7606 - val_loss: 0.5408 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7693 - val_loss: 0.5436 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4651 - accuracy: 0.7782 - val_loss: 0.5459 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4515 - accuracy: 0.7876
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4516 - accuracy: 0.7875 - val_loss: 0.5531 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42289589759895213
Confusion Matrix :
 [[2715 1332]
 [1009 3038]]
Accuracy on test set:    0.7107734124042501
Sensitivity:    0.7506795156906351 	 Specificity:    0.6708673091178651
Precision  : 0.6951945080091533
Area Under Curve:    0.7107734124042501
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5936 - accuracy: 0.6791 - val_loss: 0.5482 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5485 - accuracy: 0.7213 - val_loss: 0.5372 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7325 - val_loss: 0.5372 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5220 - accuracy: 0.7393 - val_loss: 0.5366 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7473 - val_loss: 0.5365 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7548 - val_loss: 0.5386 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4881 - accuracy: 0.7629
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.7629 - val_loss: 0.5404 - val_accuracy: 0.7274 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42880945751970967
Confusion Matrix :
 [[2848 1199]
 [1113 2934]]
Accuracy on test set:    0.7143563133185076
Sensitivity:    0.7249814677538917 	 Specificity:    0.7037311588831233
Precision  : 0.7098959593515606
Area Under Curve:    0.7143563133185076
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5920 - accuracy: 0.6820 - val_loss: 0.5475 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7222 - val_loss: 0.5382 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7344 - val_loss: 0.5407 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7414 - val_loss: 0.5329 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7480 - val_loss: 0.5393 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7572 - val_loss: 0.5373 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7657 - val_loss: 0.5395 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7728 - val_loss: 0.5452 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4606 - accuracy: 0.7808
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4608 - accuracy: 0.7806 - val_loss: 0.5456 - val_accuracy: 0.7241 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4311548646031871
Confusion Matrix :
 [[2989 1058]
 [1246 2801]]
Accuracy on test set:    0.7153446997776131
Sensitivity:    0.6921176179886336 	 Specificity:    0.7385717815665925
Precision  : 0.7258357087328323
Area Under Curve:    0.7153446997776131
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5911 - accuracy: 0.6833 - val_loss: 0.5566 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5480 - accuracy: 0.7211 - val_loss: 0.5418 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7324 - val_loss: 0.5372 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7433 - val_loss: 0.5378 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7501 - val_loss: 0.5390 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7578 - val_loss: 0.5399 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.7659 - val_loss: 0.5451 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4723 - accuracy: 0.7734 - val_loss: 0.5504 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4604 - accuracy: 0.7804
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4604 - accuracy: 0.7804 - val_loss: 0.5454 - val_accuracy: 0.7244 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.45103945536929
Confusion Matrix :
 [[2976 1071]
 [1151 2896]]
Accuracy on test set:    0.7254756609834445
Sensitivity:    0.7155917963923895 	 Specificity:    0.7353595255744997
Precision  : 0.7300226871691454
Area Under Curve:    0.7254756609834445
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5932 - accuracy: 0.6789 - val_loss: 0.5615 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5510 - accuracy: 0.7198 - val_loss: 0.5499 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5354 - accuracy: 0.7294 - val_loss: 0.5452 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5231 - accuracy: 0.7369 - val_loss: 0.5531 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.7475 - val_loss: 0.5428 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 5ms/step - loss: 0.4999 - accuracy: 0.7540 - val_loss: 0.5537 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.7626 - val_loss: 0.5457 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7729 - val_loss: 0.5493 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4599 - accuracy: 0.7816 - val_loss: 0.5531 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4486 - accuracy: 0.7879 - val_loss: 0.5655 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4343 - accuracy: 0.7963 - val_loss: 0.5670 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4238 - accuracy: 0.8036 - val_loss: 0.5672 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - ETA: 0s - loss: 0.4084 - accuracy: 0.8136
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4084 - accuracy: 0.8136 - val_loss: 0.5759 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 773us/step
Independent Testing Matthews Correlation:  0.4821326151847494
Confusion Matrix :
 [[3144  903]
 [1198 2849]]
Accuracy on test set:    0.7404250061774154
Sensitivity:    0.7039782554978997 	 Specificity:    0.7768717568569311
Precision  : 0.7593283582089553
Area Under Curve:    0.7404250061774154
(8094, 2560) (8094,)
Mean MCC = 0.4274 + 0.0223 and Mean AUC = 0.7133 + 0.0112
Mean Sensitivity = 0.7176 + 0.0277 and Mean Specificity = 0.7090 + 0.0390 and Mean Accuracy = 0.7133 + 0.0112
Mean Precision = 0.7126 + 0.0214





Seed   : 230615
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5845 - accuracy: 0.6869 - val_loss: 0.5542 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7243 - val_loss: 0.5467 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7355 - val_loss: 0.5426 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7445 - val_loss: 0.5451 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7516 - val_loss: 0.5445 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7587 - val_loss: 0.5488 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7686 - val_loss: 0.5582 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7743 - val_loss: 0.5670 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4586 - accuracy: 0.7837 - val_loss: 0.5686 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4453 - accuracy: 0.7914
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4452 - accuracy: 0.7914 - val_loss: 0.5630 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4088578146628828
Confusion Matrix :
 [[2743 1305]
 [1090 2957]]
Accuracy on test set:    0.7041383570105003
Sensitivity:    0.7306646898937484 	 Specificity:    0.6776185770750988
Precision  : 0.6938057250117315
Area Under Curve:    0.7041416334844236
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5877 - accuracy: 0.6852 - val_loss: 0.5567 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7227 - val_loss: 0.5534 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7340 - val_loss: 0.5454 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5211 - accuracy: 0.7399 - val_loss: 0.5429 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7467 - val_loss: 0.5462 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7543 - val_loss: 0.5458 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.7592 - val_loss: 0.5488 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7692 - val_loss: 0.5560 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.7776 - val_loss: 0.5557 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4563 - accuracy: 0.7847 - val_loss: 0.5665 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4439 - accuracy: 0.7913
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4440 - accuracy: 0.7912 - val_loss: 0.5677 - val_accuracy: 0.7121 - lr: 0.0010
253/253 [==============================] - 0s 931us/step
Independent Testing Matthews Correlation:  0.3952753731541586
Confusion Matrix :
 [[3015 1033]
 [1422 2625]]
Accuracy on test set:    0.6967263743051266
Sensitivity:    0.6486286137879911 	 Specificity:    0.7448122529644269
Precision  : 0.7176052487698196
Area Under Curve:    0.6967204333762089
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5886 - accuracy: 0.6818 - val_loss: 0.5455 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7210 - val_loss: 0.5378 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7329 - val_loss: 0.5337 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5211 - accuracy: 0.7389 - val_loss: 0.5317 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5119 - accuracy: 0.7450 - val_loss: 0.5333 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7526 - val_loss: 0.5348 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7623 - val_loss: 0.5437 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7679 - val_loss: 0.5389 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7746 - val_loss: 0.5388 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.7836 - val_loss: 0.5543 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4480 - accuracy: 0.7903 - val_loss: 0.5484 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4385 - accuracy: 0.7977 - val_loss: 0.5547 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4269 - accuracy: 0.8040 - val_loss: 0.5592 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 14/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4141 - accuracy: 0.8119
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4148 - accuracy: 0.8112 - val_loss: 0.5580 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42186446606576383
Confusion Matrix :
 [[2995 1052]
 [1291 2757]]
Accuracy on test set:    0.7105620753551575
Sensitivity:    0.6810770750988142 	 Specificity:    0.7400543612552508
Precision  : 0.7238120241533211
Area Under Curve:    0.7105657181770325
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5865 - accuracy: 0.6851 - val_loss: 0.5501 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7236 - val_loss: 0.5382 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7329 - val_loss: 0.5331 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7409 - val_loss: 0.5340 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7482 - val_loss: 0.5365 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7563 - val_loss: 0.5404 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7669 - val_loss: 0.5369 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4736 - accuracy: 0.7725 - val_loss: 0.5503 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4607 - accuracy: 0.7808
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4607 - accuracy: 0.7808 - val_loss: 0.5487 - val_accuracy: 0.7277 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42458306258814876
Confusion Matrix :
 [[2882 1165]
 [1164 2884]]
Accuracy on test set:    0.7122915379864113
Sensitivity:    0.7124505928853755 	 Specificity:    0.7121324437855201
Precision  : 0.7122746357125216
Area Under Curve:    0.7122915183354477
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5853 - accuracy: 0.6850 - val_loss: 0.5505 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5411 - accuracy: 0.7265 - val_loss: 0.5439 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5241 - accuracy: 0.7378 - val_loss: 0.5453 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5110 - accuracy: 0.7480 - val_loss: 0.5417 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7555 - val_loss: 0.5413 - val_accuracy: 0.7249 - lr: 0.0010

Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.7625 - val_loss: 0.5430 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7715 - val_loss: 0.5486 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7790 - val_loss: 0.5480 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4517 - accuracy: 0.7869 - val_loss: 0.5564 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4387 - accuracy: 0.7952
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4389 - accuracy: 0.7951 - val_loss: 0.5600 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4056178504922836
Confusion Matrix :
 [[2931 1116]
 [1291 2756]]
Accuracy on test set:    0.7026192241166296
Sensitivity:    0.6809982703236965 	 Specificity:    0.7242401779095626
Precision  : 0.7117768595041323
Area Under Curve:    0.7026192241166296
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5873 - accuracy: 0.6834 - val_loss: 0.5516 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7211 - val_loss: 0.5511 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7310 - val_loss: 0.5425 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7406 - val_loss: 0.5424 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7480 - val_loss: 0.5459 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.7558 - val_loss: 0.5458 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.7625 - val_loss: 0.5542 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7724 - val_loss: 0.5486 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4642 - accuracy: 0.7789
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.7790 - val_loss: 0.5609 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 847us/step
Independent Testing Matthews Correlation:  0.435285970005383
Confusion Matrix :
 [[2637 1410]
 [ 890 3157]]
Accuracy on test set:    0.7158388930071659
Sensitivity:    0.780084012849024 	 Specificity:    0.6515937731653076
Precision  : 0.6912634114298226
Area Under Curve:    0.7158388930071657
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6839 - val_loss: 0.5513 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7220 - val_loss: 0.5487 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7330 - val_loss: 0.5469 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7419 - val_loss: 0.5427 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5093 - accuracy: 0.7502 - val_loss: 0.5430 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.7576 - val_loss: 0.5447 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - ETA: 0s - loss: 0.4847 - accuracy: 0.7658
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7658 - val_loss: 0.5540 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.424047925568866
Confusion Matrix :
 [[2758 1289]
 [1045 3002]]
Accuracy on test set:    0.7116382505559674
Sensitivity:    0.7417840375586855 	 Specificity:    0.6814924635532493
Precision  : 0.6996038219529247
Area Under Curve:    0.7116382505559674
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5904 - accuracy: 0.6816 - val_loss: 0.5531 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5477 - accuracy: 0.7212 - val_loss: 0.5443 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7323 - val_loss: 0.5422 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5207 - accuracy: 0.7409 - val_loss: 0.5474 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7476 - val_loss: 0.5435 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7556 - val_loss: 0.5408 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7632 - val_loss: 0.5444 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4758 - accuracy: 0.7730
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4756 - accuracy: 0.7731 - val_loss: 0.5464 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4437953969950122
Confusion Matrix :
 [[2935 1112]
 [1139 2908]]
Accuracy on test set:    0.721892760069187
Sensitivity:    0.7185569557697059 	 Specificity:    0.7252285643686681
Precision  : 0.7233830845771144
Area Under Curve:    0.7218927600691871
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5928 - accuracy: 0.6785 - val_loss: 0.5532 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5481 - accuracy: 0.7194 - val_loss: 0.5470 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7314 - val_loss: 0.5474 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5231 - accuracy: 0.7375 - val_loss: 0.5410 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5139 - accuracy: 0.7449 - val_loss: 0.5417 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7534 - val_loss: 0.5446 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4923 - accuracy: 0.7605 - val_loss: 0.5442 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7720 - val_loss: 0.5476 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4690 - accuracy: 0.7786 - val_loss: 0.5501 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.7867 - val_loss: 0.5540 - val_accuracy: 0.7146 - lr: 0.0010

Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4459 - accuracy: 0.7930 - val_loss: 0.5554 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4334 - accuracy: 0.8005 - val_loss: 0.5623 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4176 - accuracy: 0.8083 - val_loss: 0.5725 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 14/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4044 - accuracy: 0.8163
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4049 - accuracy: 0.8161 - val_loss: 0.5798 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4605884414686438
Confusion Matrix :
 [[2958 1089]
 [1094 2953]]
Accuracy on test set:    0.7302940449715839
Sensitivity:    0.729676303434643 	 Specificity:    0.7309117865085248
Precision  : 0.7305789213260762
Area Under Curve:    0.7302940449715839
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5926 - accuracy: 0.6787 - val_loss: 0.5594 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5497 - accuracy: 0.7184 - val_loss: 0.5461 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5342 - accuracy: 0.7298 - val_loss: 0.5483 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5243 - accuracy: 0.7382 - val_loss: 0.5485 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5113 - accuracy: 0.7454 - val_loss: 0.5467 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7541 - val_loss: 0.5481 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4890 - accuracy: 0.7634 - val_loss: 0.5488 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7704 - val_loss: 0.5512 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.7779 - val_loss: 0.5531 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4549 - accuracy: 0.7872 - val_loss: 0.5595 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4437 - accuracy: 0.7935 - val_loss: 0.5679 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 12/400
256/257 [============================>.] - ETA: 0s - loss: 0.4308 - accuracy: 0.8018
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4308 - accuracy: 0.8018 - val_loss: 0.5689 - val_accuracy: 0.7149 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4846331652368159
Confusion Matrix :
 [[3040 1007]
 [1079 2968]]
Accuracy on test set:    0.7422782307882382
Sensitivity:    0.7333827526562886 	 Specificity:    0.7511737089201878
Precision  : 0.7466666666666667
Area Under Curve:    0.7422782307882382
(8094, 2560) (8094,)
Mean MCC = 0.4305 + 0.0255 and Mean AUC = 0.7148 + 0.0129
Mean Sensitivity = 0.7157 + 0.0353 and Mean Specificity = 0.7139 + 0.0313 and Mean Accuracy = 0.7148 + 0.0129
Mean Precision = 0.7151 + 0.0163





Seed   : 541360
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5899 - accuracy: 0.6831 - val_loss: 0.5574 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7243 - val_loss: 0.5495 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5265 - accuracy: 0.7370 - val_loss: 0.5438 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7438 - val_loss: 0.5425 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7490 - val_loss: 0.5464 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7565 - val_loss: 0.5454 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7665 - val_loss: 0.5477 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4743 - accuracy: 0.7734 - val_loss: 0.5585 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4623 - accuracy: 0.7800 - val_loss: 0.5575 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4510 - accuracy: 0.7888
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4514 - accuracy: 0.7885 - val_loss: 0.5653 - val_accuracy: 0.7150 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40411076360102954
Confusion Matrix :
 [[2650 1398]
 [1021 3026]]
Accuracy on test set:    0.7011735639283508
Sensitivity:    0.7477143563133185 	 Specificity:    0.6546442687747036
Precision  : 0.683996383363472
Area Under Curve:    0.7011793125440111
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5887 - accuracy: 0.6822 - val_loss: 0.5551 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7240 - val_loss: 0.5486 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7336 - val_loss: 0.5419 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7421 - val_loss: 0.5430 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7520 - val_loss: 0.5421 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7579 - val_loss: 0.5452 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7647 - val_loss: 0.5466 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7738 - val_loss: 0.5446 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4606 - accuracy: 0.7815 - val_loss: 0.5602 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4496 - accuracy: 0.7876 - val_loss: 0.5495 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4387 - accuracy: 0.7952 - val_loss: 0.5607 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4260 - accuracy: 0.8023 - val_loss: 0.5601 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 13/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4110 - accuracy: 0.8127
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4117 - accuracy: 0.8121 - val_loss: 0.5669 - val_accuracy: 0.7148 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.429847579816131
Confusion Matrix :
 [[2750 1298]
 [1014 3033]]
Accuracy on test set:    0.7143915997529339
Sensitivity:    0.7494440326167532 	 Specificity:    0.6793478260869565
Precision  : 0.7003001616254907
Area Under Curve:    0.7143959293518549
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5904 - accuracy: 0.6820 - val_loss: 0.5484 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7221 - val_loss: 0.5346 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7323 - val_loss: 0.5327 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7401 - val_loss: 0.5323 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7476 - val_loss: 0.5331 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7557 - val_loss: 0.5373 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4857 - accuracy: 0.7650 - val_loss: 0.5396 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4732 - accuracy: 0.7740 - val_loss: 0.5442 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4607 - accuracy: 0.7816 - val_loss: 0.5453 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4487 - accuracy: 0.7903 - val_loss: 0.5490 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 11/400
254/257 [============================>.] - ETA: 0s - loss: 0.4348 - accuracy: 0.7988
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4349 - accuracy: 0.7988 - val_loss: 0.5556 - val_accuracy: 0.7209 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4145436016115783
Confusion Matrix :
 [[2621 1426]
 [ 955 3093]]
Accuracy on test set:    0.7058678196417542
Sensitivity:    0.7640810276679841 	 Specificity:    0.6476402273288856
Precision  : 0.6844434609426865
Area Under Curve:    0.7058606274984348
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5898 - accuracy: 0.6835 - val_loss: 0.5456 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7212 - val_loss: 0.5336 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7333 - val_loss: 0.5305 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7424 - val_loss: 0.5308 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7496 - val_loss: 0.5334 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7580 - val_loss: 0.5354 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7657 - val_loss: 0.5376 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4701 - accuracy: 0.7740
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4701 - accuracy: 0.7743 - val_loss: 0.5393 - val_accuracy: 0.7246 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4090451507475812
Confusion Matrix :
 [[2874 1173]
 [1219 2829]]
Accuracy on test set:    0.704508956145769
Sensitivity:    0.6988636363636364 	 Specificity:    0.7101556708673091
Precision  : 0.7068965517241379
Area Under Curve:    0.7045096536154727
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6835 - val_loss: 0.5478 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7230 - val_loss: 0.5402 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7345 - val_loss: 0.5361 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7431 - val_loss: 0.5378 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7491 - val_loss: 0.5417 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7588 - val_loss: 0.5391 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7670 - val_loss: 0.5412 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4695 - accuracy: 0.7745
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.7747 - val_loss: 0.5424 - val_accuracy: 0.7256 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41425293406039415
Confusion Matrix :
 [[2910 1137]
 [1234 2813]]
Accuracy on test set:    0.7070669631826044
Sensitivity:    0.69508277736595 	 Specificity:    0.7190511489992587
Precision  : 0.7121518987341772
Area Under Curve:    0.7070669631826043
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5875 - accuracy: 0.6862 - val_loss: 0.5471 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7253 - val_loss: 0.5419 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7328 - val_loss: 0.5402 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7418 - val_loss: 0.5389 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7482 - val_loss: 0.5384 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7587 - val_loss: 0.5444 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7654 - val_loss: 0.5462 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4679 - accuracy: 0.7752 - val_loss: 0.5496 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4555 - accuracy: 0.7837 - val_loss: 0.5549 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4406 - accuracy: 0.7946
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4406 - accuracy: 0.7946 - val_loss: 0.5604 - val_accuracy: 0.7179 - lr: 0.0010
253/253 [==============================] - 0s 894us/step
Independent Testing Matthews Correlation:  0.4341565728413623
Confusion Matrix :
 [[2763 1284]
 [1010 3037]]
Accuracy on test set:    0.7165801828514949
Sensitivity:    0.7504324190758587 	 Specificity:    0.6827279466271312
Precision  : 0.7028465632955334
Area Under Curve:    0.7165801828514949
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5859 - accuracy: 0.6872 - val_loss: 0.5462 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7225 - val_loss: 0.5419 - val_accuracy: 0.7244 - lr: 0.0010

Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7350 - val_loss: 0.5379 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7434 - val_loss: 0.5410 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7532 - val_loss: 0.5514 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7594 - val_loss: 0.5406 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7674 - val_loss: 0.5521 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4651 - accuracy: 0.7777 - val_loss: 0.5460 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4534 - accuracy: 0.7856 - val_loss: 0.5496 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4398 - accuracy: 0.7949 - val_loss: 0.5628 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 11/400
252/257 [============================>.] - ETA: 0s - loss: 0.4276 - accuracy: 0.8019
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4278 - accuracy: 0.8016 - val_loss: 0.5701 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 904us/step
Independent Testing Matthews Correlation:  0.4233380298342678
Confusion Matrix :
 [[2643 1404]
 [ 941 3106]]
Accuracy on test set:    0.7102792191746973
Sensitivity:    0.7674820854954287 	 Specificity:    0.6530763528539659
Precision  : 0.6886917960088692
Area Under Curve:    0.7102792191746974
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5857 - accuracy: 0.6856 - val_loss: 0.5484 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7237 - val_loss: 0.5407 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7331 - val_loss: 0.5423 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7423 - val_loss: 0.5397 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7479 - val_loss: 0.5395 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7581 - val_loss: 0.5437 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7687 - val_loss: 0.5467 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4676 - accuracy: 0.7751 - val_loss: 0.5500 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4555 - accuracy: 0.7834 - val_loss: 0.5526 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4413 - accuracy: 0.7922 - val_loss: 0.5577 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 11/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4300 - accuracy: 0.7992
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4303 - accuracy: 0.7989 - val_loss: 0.5655 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 954us/step
Independent Testing Matthews Correlation:  0.44674854303953665
Confusion Matrix :
 [[2994 1053]
 [1187 2860]]
Accuracy on test set:    0.7232517914504571
Sensitivity:    0.7066963182604399 	 Specificity:    0.7398072646404744
Precision  : 0.7308970099667774
Area Under Curve:    0.7232517914504571
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5874 - accuracy: 0.6869 - val_loss: 0.5593 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.7206 - val_loss: 0.5509 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5326 - accuracy: 0.7312 - val_loss: 0.5442 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5236 - accuracy: 0.7394 - val_loss: 0.5391 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5125 - accuracy: 0.7463 - val_loss: 0.5519 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7547 - val_loss: 0.5431 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4908 - accuracy: 0.7622 - val_loss: 0.5467 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4777 - accuracy: 0.7717 - val_loss: 0.5521 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4643 - accuracy: 0.7785 - val_loss: 0.5536 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4542 - accuracy: 0.7863 - val_loss: 0.5530 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4402 - accuracy: 0.7947 - val_loss: 0.5716 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4278 - accuracy: 0.8020 - val_loss: 0.5715 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4128 - accuracy: 0.8117 - val_loss: 0.5755 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4022 - accuracy: 0.8172 - val_loss: 0.5785 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3876 - accuracy: 0.8258 - val_loss: 0.6020 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3811 - accuracy: 0.8274 - val_loss: 0.5919 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 17/400
251/257 [============================>.] - ETA: 0s - loss: 0.3671 - accuracy: 0.8362
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3672 - accuracy: 0.8363 - val_loss: 0.6049 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42599517075467846
Confusion Matrix :
 [[2982 1065]
 [1260 2787]]
Accuracy on test set:    0.712750185322461
Sensitivity:    0.6886582653817642 	 Specificity:    0.7368421052631579
Precision  : 0.7235202492211839
Area Under Curve:    0.7127501853224611
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5944 - accuracy: 0.6789 - val_loss: 0.5556 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7194 - val_loss: 0.5533 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5352 - accuracy: 0.7298 - val_loss: 0.5457 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5250 - accuracy: 0.7375 - val_loss: 0.5460 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5141 - accuracy: 0.7451 - val_loss: 0.5474 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7515 - val_loss: 0.5560 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7616 - val_loss: 0.5539 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4811 - accuracy: 0.7670 - val_loss: 0.5700 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4693 - accuracy: 0.7769
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4693 - accuracy: 0.7769 - val_loss: 0.5599 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4871588559035605
Confusion Matrix :
 [[3056  991]
 [1085 2962]]
Accuracy on test set:    0.7435137138621201
Sensitivity:    0.7319001729676303 	 Specificity:    0.7551272547566098
Precision  : 0.7493043258284847
Area Under Curve:    0.7435137138621201
(8094, 2560) (8094,)
Mean MCC = 0.4289 + 0.0228 and Mean AUC = 0.7139 + 0.0116
Mean Sensitivity = 0.7300 + 0.0285 and Mean Specificity = 0.6978 + 0.0376 and Mean Accuracy = 0.7139 + 0.0116
Mean Precision = 0.7083 + 0.0202





Seed   : 548231
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5845 - accuracy: 0.6887 - val_loss: 0.5617 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5406 - accuracy: 0.7274 - val_loss: 0.5581 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7334 - val_loss: 0.5573 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7433 - val_loss: 0.5570 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7491 - val_loss: 0.5595 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 6/400
249/257 [============================>.] - ETA: 0s - loss: 0.4971 - accuracy: 0.7563
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7563 - val_loss: 0.5600 - val_accuracy: 0.7113 - lr: 0.0010
253/253 [==============================] - 0s 865us/step
Independent Testing Matthews Correlation:  0.4137830849945733
Confusion Matrix :
 [[2499 1549]
 [ 849 3198]]
Accuracy on test set:    0.7037677578752316
Sensitivity:    0.7902149740548554 	 Specificity:    0.6173418972332015
Precision  : 0.6736886454602907
Area Under Curve:    0.7037784356440285
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5889 - accuracy: 0.6840 - val_loss: 0.5581 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7239 - val_loss: 0.5521 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7337 - val_loss: 0.5577 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7405 - val_loss: 0.5497 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5108 - accuracy: 0.7468 - val_loss: 0.5515 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5011 - accuracy: 0.7532 - val_loss: 0.5520 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7603 - val_loss: 0.5649 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4795 - accuracy: 0.7716
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4802 - accuracy: 0.7710 - val_loss: 0.5585 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 827us/step
Independent Testing Matthews Correlation:  0.4017048886334362
Confusion Matrix :
 [[2641 1407]
 [1022 3025]]
Accuracy on test set:    0.6999382334774552
Sensitivity:    0.7474672596985421 	 Specificity:    0.6524209486166008
Precision  : 0.6825361010830325
Area Under Curve:    0.6999441041575715
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5826 - accuracy: 0.6874 - val_loss: 0.5536 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5401 - accuracy: 0.7261 - val_loss: 0.5479 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5260 - accuracy: 0.7353 - val_loss: 0.5468 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7446 - val_loss: 0.5453 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5020 - accuracy: 0.7535 - val_loss: 0.5471 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4903 - accuracy: 0.7617 - val_loss: 0.5501 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7675 - val_loss: 0.5575 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4664 - accuracy: 0.7781 - val_loss: 0.5550 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4536 - accuracy: 0.7863 - val_loss: 0.5657 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4389 - accuracy: 0.7947
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4391 - accuracy: 0.7946 - val_loss: 0.5779 - val_accuracy: 0.7139 - lr: 0.0010
253/253 [==============================] - 0s 786us/step
Independent Testing Matthews Correlation:  0.4242420842136075
Confusion Matrix :
 [[3011 1036]
 [1298 2750]]
Accuracy on test set:    0.7116738727609636
Sensitivity:    0.6793478260869565 	 Specificity:    0.7440079070916729
Precision  : 0.7263602746962493
Area Under Curve:    0.7116778665893146
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 6s 5ms/step - loss: 0.5872 - accuracy: 0.6848 - val_loss: 0.5550 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7213 - val_loss: 0.5480 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7331 - val_loss: 0.5476 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7387 - val_loss: 0.5469 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5108 - accuracy: 0.7469 - val_loss: 0.5461 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5010 - accuracy: 0.7531 - val_loss: 0.5498 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4897 - accuracy: 0.7631 - val_loss: 0.5493 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7711 - val_loss: 0.5580 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4659 - accuracy: 0.7801 - val_loss: 0.5605 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 10/400

257/257 [==============================] - 1s 4ms/step - loss: 0.4519 - accuracy: 0.7891 - val_loss: 0.5645 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4395 - accuracy: 0.7984 - val_loss: 0.5649 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 12/400
253/257 [============================>.] - ETA: 0s - loss: 0.4264 - accuracy: 0.8045
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4266 - accuracy: 0.8044 - val_loss: 0.5681 - val_accuracy: 0.7179 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41218289255347973
Confusion Matrix :
 [[2633 1414]
 [ 975 3073]]
Accuracy on test set:    0.7048795552810376
Sensitivity:    0.7591403162055336 	 Specificity:    0.6506053867062022
Precision  : 0.6848673946957878
Area Under Curve:    0.7048728514558679
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5888 - accuracy: 0.6818 - val_loss: 0.5476 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7210 - val_loss: 0.5387 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7323 - val_loss: 0.5352 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5207 - accuracy: 0.7392 - val_loss: 0.5411 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7473 - val_loss: 0.5349 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7557 - val_loss: 0.5389 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4885 - accuracy: 0.7625
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.7624 - val_loss: 0.5441 - val_accuracy: 0.7255 - lr: 0.0010
253/253 [==============================] - 0s 718us/step
Independent Testing Matthews Correlation:  0.42830089512180025
Confusion Matrix :
 [[2745 1302]
 [1016 3031]]
Accuracy on test set:    0.7136150234741784
Sensitivity:    0.7489498393872004 	 Specificity:    0.6782802075611564
Precision  : 0.6995153473344103
Area Under Curve:    0.7136150234741785
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5879 - accuracy: 0.6839 - val_loss: 0.5587 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7217 - val_loss: 0.5434 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7319 - val_loss: 0.5399 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5216 - accuracy: 0.7405 - val_loss: 0.5432 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5122 - accuracy: 0.7471 - val_loss: 0.5413 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5023 - accuracy: 0.7538 - val_loss: 0.5466 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.7613 - val_loss: 0.5448 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4817 - accuracy: 0.7668 - val_loss: 0.5443 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4702 - accuracy: 0.7763 - val_loss: 0.5519 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4594 - accuracy: 0.7837
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.7838 - val_loss: 0.5572 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 840us/step
Independent Testing Matthews Correlation:  0.41829094649130844
Confusion Matrix :
 [[3048  999]
 [1362 2685]]
Accuracy on test set:    0.7083024462564863
Sensitivity:    0.6634544106745738 	 Specificity:    0.7531504818383988
Precision  : 0.7288273615635179
Area Under Curve:    0.7083024462564863
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5906 - accuracy: 0.6803 - val_loss: 0.5547 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7210 - val_loss: 0.5384 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7317 - val_loss: 0.5366 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5209 - accuracy: 0.7392 - val_loss: 0.5378 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.7472 - val_loss: 0.5411 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.7550 - val_loss: 0.5417 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4863 - accuracy: 0.7621
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.7620 - val_loss: 0.5389 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 894us/step
Independent Testing Matthews Correlation:  0.43877060655498756
Confusion Matrix :
 [[2854 1193]
 [1079 2968]]
Accuracy on test set:    0.7192982456140351
Sensitivity:    0.7333827526562886 	 Specificity:    0.7052137385717816
Precision  : 0.7132900745013218
Area Under Curve:    0.7192982456140351
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5894 - accuracy: 0.6824 - val_loss: 0.5451 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7228 - val_loss: 0.5418 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5337 - accuracy: 0.7302 - val_loss: 0.5340 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7388 - val_loss: 0.5373 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7479 - val_loss: 0.5343 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7571 - val_loss: 0.5338 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4866 - accuracy: 0.7635 - val_loss: 0.5412 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4757 - accuracy: 0.7716
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4759 - accuracy: 0.7716 - val_loss: 0.5430 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 901us/step
Independent Testing Matthews Correlation:  0.43790173934641735
Confusion Matrix :
 [[2880 1167]
 [1108 2939]]
Accuracy on test set:    0.7189276006918706
Sensitivity:    0.7262169508277737 	 Specificity:    0.7116382505559674
Precision  : 0.715781782756941
Area Under Curve:    0.7189276006918707
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.6848 - val_loss: 0.5608 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5485 - accuracy: 0.7212 - val_loss: 0.5411 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7306 - val_loss: 0.5363 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5204 - accuracy: 0.7410 - val_loss: 0.5455 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7472 - val_loss: 0.5391 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7580 - val_loss: 0.5394 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7669 - val_loss: 0.5400 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4704 - accuracy: 0.7758
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7752 - val_loss: 0.5437 - val_accuracy: 0.7248 - lr: 0.0010
253/253 [==============================] - 0s 968us/step
Independent Testing Matthews Correlation:  0.45626607795685065
Confusion Matrix :
 [[2994 1053]
 [1148 2899]]
Accuracy on test set:    0.7280701754385965
Sensitivity:    0.7163330862367185 	 Specificity:    0.7398072646404744
Precision  : 0.7335526315789473
Area Under Curve:    0.7280701754385964
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5928 - accuracy: 0.6819 - val_loss: 0.5499 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5507 - accuracy: 0.7180 - val_loss: 0.5422 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5344 - accuracy: 0.7310 - val_loss: 0.5363 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5233 - accuracy: 0.7391 - val_loss: 0.5329 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7474 - val_loss: 0.5333 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5024 - accuracy: 0.7554 - val_loss: 0.5346 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7637 - val_loss: 0.5401 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4802 - accuracy: 0.7712
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4802 - accuracy: 0.7711 - val_loss: 0.5357 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 803us/step
Independent Testing Matthews Correlation:  0.477342958201285
Confusion Matrix :
 [[3076  971]
 [1146 2901]]
Accuracy on test set:    0.7384482332592044
Sensitivity:    0.7168272794662713 	 Specificity:    0.7600691870521374
Precision  : 0.7492252066115702
Area Under Curve:    0.7384482332592044
(8094, 2560) (8094,)
Mean MCC = 0.4309 + 0.0215 and Mean AUC = 0.7147 + 0.0113
Mean Sensitivity = 0.7281 + 0.0353 and Mean Specificity = 0.7013 + 0.0470 and Mean Accuracy = 0.7147 + 0.0113
Mean Precision = 0.7108 + 0.0236





Seed   : 33247
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5863 - accuracy: 0.6846 - val_loss: 0.5719 - val_accuracy: 0.6973 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7245 - val_loss: 0.5545 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7368 - val_loss: 0.5536 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7420 - val_loss: 0.5526 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7490 - val_loss: 0.5518 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7572 - val_loss: 0.5499 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7661 - val_loss: 0.5589 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4730 - accuracy: 0.7742 - val_loss: 0.5589 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4614 - accuracy: 0.7827 - val_loss: 0.5620 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4486 - accuracy: 0.7903 - val_loss: 0.5774 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4357 - accuracy: 0.7996
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4359 - accuracy: 0.7995 - val_loss: 0.5677 - val_accuracy: 0.7113 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40903343360062094
Confusion Matrix :
 [[2870 1178]
 [1214 2833]]
Accuracy on test set:    0.704508956145769
Sensitivity:    0.7000247096614777 	 Specificity:    0.70899209486166
Precision  : 0.706307653951633
Area Under Curve:    0.7045084022615689
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5856 - accuracy: 0.6877 - val_loss: 0.5599 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7250 - val_loss: 0.5574 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5263 - accuracy: 0.7357 - val_loss: 0.5573 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5154 - accuracy: 0.7440 - val_loss: 0.5568 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7508 - val_loss: 0.5630 - val_accuracy: 0.7013 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7590 - val_loss: 0.5600 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4841 - accuracy: 0.7668 - val_loss: 0.5625 - val_accuracy: 0.7049 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4731 - accuracy: 0.7732 - val_loss: 0.5635 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4636 - accuracy: 0.7797 - val_loss: 0.5705 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4519 - accuracy: 0.7897 - val_loss: 0.5699 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4404 - accuracy: 0.7962
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4406 - accuracy: 0.7961 - val_loss: 0.5836 - val_accuracy: 0.7038 - lr: 0.0010
253/253 [==============================] - 0s 774us/step
Independent Testing Matthews Correlation:  0.4083535867841427
Confusion Matrix :
 [[2609 1439]
 [ 967 3080]]
Accuracy on test set:    0.7027794935145152
Sensitivity:    0.7610575735112429 	 Specificity:    0.6445158102766798
Precision  : 0.681566718300509
Area Under Curve:    0.7027866918939615
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5868 - accuracy: 0.6849 - val_loss: 0.5526 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7234 - val_loss: 0.5428 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7349 - val_loss: 0.5391 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7413 - val_loss: 0.5459 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7507 - val_loss: 0.5397 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7588 - val_loss: 0.5506 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7680 - val_loss: 0.5481 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7755 - val_loss: 0.5455 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4554 - accuracy: 0.7846 - val_loss: 0.5529 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4418 - accuracy: 0.7925 - val_loss: 0.5571 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4274 - accuracy: 0.8018 - val_loss: 0.5612 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4164 - accuracy: 0.8087 - val_loss: 0.5676 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 13/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4032 - accuracy: 0.8161
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4034 - accuracy: 0.8162 - val_loss: 0.5925 - val_accuracy: 0.7226 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40220628690464927
Confusion Matrix :
 [[2640 1407]
 [1020 3028]]
Accuracy on test set:    0.7001852995676343
Sensitivity:    0.7480237154150198 	 Specificity:    0.6523350630096367
Precision  : 0.6827508455467869
Area Under Curve:    0.7001793892123283
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5867 - accuracy: 0.6850 - val_loss: 0.5521 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7218 - val_loss: 0.5430 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7340 - val_loss: 0.5433 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7441 - val_loss: 0.5404 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7500 - val_loss: 0.5374 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7593 - val_loss: 0.5428 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7672 - val_loss: 0.5477 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4698 - accuracy: 0.7748 - val_loss: 0.5495 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4564 - accuracy: 0.7845 - val_loss: 0.5547 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4424 - accuracy: 0.7930
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4426 - accuracy: 0.7932 - val_loss: 0.5567 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.422125854745488
Confusion Matrix :
 [[2861 1186]
 [1153 2895]]
Accuracy on test set:    0.7110562075355158
Sensitivity:    0.7151679841897233 	 Specificity:    0.7069434148752162
Precision  : 0.7093849546679736
Area Under Curve:    0.7110556995324697
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5871 - accuracy: 0.6826 - val_loss: 0.5499 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7212 - val_loss: 0.5419 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7323 - val_loss: 0.5410 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7389 - val_loss: 0.5394 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5109 - accuracy: 0.7459 - val_loss: 0.5417 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.7531 - val_loss: 0.5490 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4897 - accuracy: 0.7617 - val_loss: 0.5488 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4777 - accuracy: 0.7700
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7696 - val_loss: 0.5473 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43266622530781623
Confusion Matrix :
 [[2900 1147]
 [1149 2898]]
Accuracy on test set:    0.7163330862367185
Sensitivity:    0.7160859896219421 	 Specificity:    0.7165801828514949
Precision  : 0.7164400494437577
Area Under Curve:    0.7163330862367187
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5884 - accuracy: 0.6842 - val_loss: 0.5552 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7226 - val_loss: 0.5484 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7342 - val_loss: 0.5425 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7418 - val_loss: 0.5400 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7485 - val_loss: 0.5424 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7558 - val_loss: 0.5424 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4856 - accuracy: 0.7651 - val_loss: 0.5434 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4742 - accuracy: 0.7727
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7727 - val_loss: 0.5536 - val_accuracy: 0.7229 - lr: 0.0010
253/253 [==============================] - 0s 791us/step
Independent Testing Matthews Correlation:  0.4358052133753566
Confusion Matrix :
 [[2792 1255]
 [1031 3016]]
Accuracy on test set:    0.7175685693106004
Sensitivity:    0.7452433901655547 	 Specificity:    0.6898937484556461
Precision  : 0.7061578084757668
Area Under Curve:    0.7175685693106005
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5868 - accuracy: 0.6843 - val_loss: 0.5503 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7229 - val_loss: 0.5408 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.7348 - val_loss: 0.5373 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5135 - accuracy: 0.7450 - val_loss: 0.5468 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5018 - accuracy: 0.7518 - val_loss: 0.5393 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4891 - accuracy: 0.7610 - val_loss: 0.5401 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4762 - accuracy: 0.7700 - val_loss: 0.5440 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4664 - accuracy: 0.7782 - val_loss: 0.5486 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4544 - accuracy: 0.7861 - val_loss: 0.5585 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4420 - accuracy: 0.7928
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4417 - accuracy: 0.7932 - val_loss: 0.5591 - val_accuracy: 0.7241 - lr: 0.0010
253/253 [==============================] - 0s 819us/step
Independent Testing Matthews Correlation:  0.42825215652027904
Confusion Matrix :
 [[2678 1369]
 [ 954 3093]]
Accuracy on test set:    0.7129972819372374
Sensitivity:    0.7642698295033358 	 Specificity:    0.6617247343711391
Precision  : 0.6931869116987898
Area Under Curve:    0.7129972819372374
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5887 - accuracy: 0.6841 - val_loss: 0.5464 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7218 - val_loss: 0.5389 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7303 - val_loss: 0.5374 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7418 - val_loss: 0.5345 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7483 - val_loss: 0.5486 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7564 - val_loss: 0.5355 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4856 - accuracy: 0.7654 - val_loss: 0.5364 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4740 - accuracy: 0.7718 - val_loss: 0.5420 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4639 - accuracy: 0.7795 - val_loss: 0.5481 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4527 - accuracy: 0.7864 - val_loss: 0.5542 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4400 - accuracy: 0.7934 - val_loss: 0.5516 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4296 - accuracy: 0.8007 - val_loss: 0.5554 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 13/400
254/257 [============================>.] - ETA: 0s - loss: 0.4195 - accuracy: 0.8057
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4194 - accuracy: 0.8058 - val_loss: 0.5627 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 874us/step
Independent Testing Matthews Correlation:  0.436311030300928
Confusion Matrix :
 [[2965 1082]
 [1200 2847]]
Accuracy on test set:    0.7180627625401532
Sensitivity:    0.7034840622683469 	 Specificity:    0.7326414628119595
Precision  : 0.7246118605243065
Area Under Curve:    0.7180627625401532
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5897 - accuracy: 0.6833 - val_loss: 0.5515 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5482 - accuracy: 0.7211 - val_loss: 0.5409 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7315 - val_loss: 0.5402 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5224 - accuracy: 0.7392 - val_loss: 0.5385 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5101 - accuracy: 0.7452 - val_loss: 0.5427 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5003 - accuracy: 0.7545 - val_loss: 0.5417 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4887 - accuracy: 0.7622 - val_loss: 0.5401 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4785 - accuracy: 0.7694 - val_loss: 0.5442 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4643 - accuracy: 0.7781 - val_loss: 0.5496 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 10/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4538 - accuracy: 0.7874
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4538 - accuracy: 0.7870 - val_loss: 0.5556 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4600942478619178
Confusion Matrix :
 [[2952 1095]
 [1090 2957]]
Accuracy on test set:    0.7300469483568075
Sensitivity:    0.7306646898937484 	 Specificity:    0.7294292068198666
Precision  : 0.7297630799605134
Area Under Curve:    0.7300469483568075
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5952 - accuracy: 0.6787 - val_loss: 0.5553 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5504 - accuracy: 0.7184 - val_loss: 0.5457 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5347 - accuracy: 0.7301 - val_loss: 0.5512 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7391 - val_loss: 0.5423 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5110 - accuracy: 0.7474 - val_loss: 0.5413 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7556 - val_loss: 0.5416 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7635 - val_loss: 0.5450 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.7706 - val_loss: 0.5490 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4636 - accuracy: 0.7809 - val_loss: 0.5557 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4513 - accuracy: 0.7898 - val_loss: 0.5588 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4392 - accuracy: 0.7977
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4403 - accuracy: 0.7968 - val_loss: 0.5620 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 0s 812us/step
Independent Testing Matthews Correlation:  0.4685661529756739
Confusion Matrix :
 [[3120  927]
 [1229 2818]]
Accuracy on test set:    0.733629849271065
Sensitivity:    0.696318260439832 	 Specificity:    0.770941438102298
Precision  : 0.7524699599465955
Area Under Curve:    0.733629849271065
(8094, 2560) (8094,)
Mean MCC = 0.4303 + 0.0205 and Mean AUC = 0.7147 + 0.0104
Mean Sensitivity = 0.7280 + 0.0241 and Mean Specificity = 0.7014 + 0.0378 and Mean Accuracy = 0.7147 + 0.0104
Mean Precision = 0.7103 + 0.0208





Seed   : 229374
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5861 - accuracy: 0.6826 - val_loss: 0.5544 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7240 - val_loss: 0.5481 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.7357 - val_loss: 0.5461 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5148 - accuracy: 0.7410 - val_loss: 0.5446 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7521 - val_loss: 0.5528 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7585 - val_loss: 0.5453 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7665 - val_loss: 0.5496 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4695 - accuracy: 0.7760 - val_loss: 0.5550 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4579 - accuracy: 0.7822 - val_loss: 0.5615 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4426 - accuracy: 0.7924 - val_loss: 0.5573 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
251/257 [============================>.] - ETA: 0s - loss: 0.4274 - accuracy: 0.8034
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4273 - accuracy: 0.8035 - val_loss: 0.5692 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4089002296145398
Confusion Matrix :
 [[2619 1429]
 [ 974 3073]]
Accuracy on test set:    0.7031500926497838
Sensitivity:    0.7593278972078082 	 Specificity:    0.6469861660079052
Precision  : 0.6825855175477565
Area Under Curve:    0.7031570316078567
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5858 - accuracy: 0.6856 - val_loss: 0.5566 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7254 - val_loss: 0.5513 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5267 - accuracy: 0.7357 - val_loss: 0.5560 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7413 - val_loss: 0.5457 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7499 - val_loss: 0.5479 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7570 - val_loss: 0.5505 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4857 - accuracy: 0.7648 - val_loss: 0.5518 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.7726 - val_loss: 0.5546 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 9/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4641 - accuracy: 0.7802
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4651 - accuracy: 0.7795 - val_loss: 0.5555 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4087867527241076
Confusion Matrix :
 [[2834 1214]
 [1179 2868]]
Accuracy on test set:    0.7043854231006794
Sensitivity:    0.7086730911786508 	 Specificity:    0.700098814229249
Precision  : 0.7025967662910338
Area Under Curve:    0.7043859527039499
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5895 - accuracy: 0.6809 - val_loss: 0.5481 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7237 - val_loss: 0.5406 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7333 - val_loss: 0.5353 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7418 - val_loss: 0.5321 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7500 - val_loss: 0.5348 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7586 - val_loss: 0.5375 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7684 - val_loss: 0.5398 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4676 - accuracy: 0.7775 - val_loss: 0.5417 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4551 - accuracy: 0.7836
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4551 - accuracy: 0.7838 - val_loss: 0.5461 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.415992239516828
Confusion Matrix :
 [[2898 1149]
 [1215 2833]]
Accuracy on test set:    0.7079678814082767
Sensitivity:    0.6998517786561265 	 Specificity:    0.7160859896219421
Precision  : 0.7114515318935208
Area Under Curve:    0.7079688841390344
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5854 - accuracy: 0.6846 - val_loss: 0.5515 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7224 - val_loss: 0.5353 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7332 - val_loss: 0.5338 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7412 - val_loss: 0.5354 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7486 - val_loss: 0.5325 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7550 - val_loss: 0.5339 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 7/400

257/257 [==============================] - 1s 4ms/step - loss: 0.4872 - accuracy: 0.7636 - val_loss: 0.5383 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4751 - accuracy: 0.7732
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4750 - accuracy: 0.7734 - val_loss: 0.5461 - val_accuracy: 0.7244 - lr: 0.0010
253/253 [==============================] - 0s 799us/step
Independent Testing Matthews Correlation:  0.4377311550191344
Confusion Matrix :
 [[2710 1337]
 [ 947 3101]]
Accuracy on test set:    0.7178505250154417
Sensitivity:    0.7660573122529645 	 Specificity:    0.6696318260439832
Precision  : 0.6987381703470031
Area Under Curve:    0.7178445691484738
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5905 - accuracy: 0.6803 - val_loss: 0.5522 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7227 - val_loss: 0.5414 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7331 - val_loss: 0.5433 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7407 - val_loss: 0.5415 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7482 - val_loss: 0.5427 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7556 - val_loss: 0.5434 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7627 - val_loss: 0.5496 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4732 - accuracy: 0.7718
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4732 - accuracy: 0.7716 - val_loss: 0.5502 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 786us/step
Independent Testing Matthews Correlation:  0.42557740827621626
Confusion Matrix :
 [[2846 1201]
 [1124 2923]]
Accuracy on test set:    0.712750185322461
Sensitivity:    0.7222634049913517 	 Specificity:    0.7032369656535705
Precision  : 0.7087778855480117
Area Under Curve:    0.712750185322461
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5865 - accuracy: 0.6873 - val_loss: 0.5545 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7230 - val_loss: 0.5490 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7327 - val_loss: 0.5512 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7394 - val_loss: 0.5437 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7480 - val_loss: 0.5450 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7557 - val_loss: 0.5503 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4831 - accuracy: 0.7661 - val_loss: 0.5518 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4708 - accuracy: 0.7754 - val_loss: 0.5606 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4574 - accuracy: 0.7841 - val_loss: 0.5599 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4471 - accuracy: 0.7892
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4469 - accuracy: 0.7894 - val_loss: 0.5621 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 829us/step
Independent Testing Matthews Correlation:  0.4250290153158366
Confusion Matrix :
 [[2742 1305]
 [1026 3021]]
Accuracy on test set:    0.712008895478132
Sensitivity:    0.7464788732394366 	 Specificity:    0.6775389177168273
Precision  : 0.6983356449375867
Area Under Curve:    0.7120088954781318
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5850 - accuracy: 0.6850 - val_loss: 0.5522 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7218 - val_loss: 0.5470 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7335 - val_loss: 0.5437 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7415 - val_loss: 0.5490 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7493 - val_loss: 0.5467 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7572 - val_loss: 0.5432 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7666 - val_loss: 0.5475 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4736 - accuracy: 0.7739
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4734 - accuracy: 0.7741 - val_loss: 0.5550 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4235013231483578
Confusion Matrix :
 [[2784 1263]
 [1072 2975]]
Accuracy on test set:    0.7115147022485792
Sensitivity:    0.7351124289597233 	 Specificity:    0.6879169755374351
Precision  : 0.7019820670127419
Area Under Curve:    0.7115147022485792
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.6833 - val_loss: 0.5524 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7218 - val_loss: 0.5448 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7305 - val_loss: 0.5429 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5221 - accuracy: 0.7392 - val_loss: 0.5438 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5130 - accuracy: 0.7461 - val_loss: 0.5462 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5028 - accuracy: 0.7525 - val_loss: 0.5454 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4905 - accuracy: 0.7615 - val_loss: 0.5467 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7714 - val_loss: 0.5554 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4653 - accuracy: 0.7786 - val_loss: 0.5593 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4536 - accuracy: 0.7861 - val_loss: 0.5569 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4411 - accuracy: 0.7937 - val_loss: 0.5587 - val_accuracy: 0.7193 - lr: 0.0010

Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4295 - accuracy: 0.8015 - val_loss: 0.5656 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 13/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4153 - accuracy: 0.8091
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4157 - accuracy: 0.8088 - val_loss: 0.5741 - val_accuracy: 0.7167 - lr: 0.0010
253/253 [==============================] - 0s 846us/step
Independent Testing Matthews Correlation:  0.428353890579267
Confusion Matrix :
 [[2804 1243]
 [1072 2975]]
Accuracy on test set:    0.7139856683963429
Sensitivity:    0.7351124289597233 	 Specificity:    0.6928589078329627
Precision  : 0.7053105737316263
Area Under Curve:    0.713985668396343
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5897 - accuracy: 0.6839 - val_loss: 0.5607 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7194 - val_loss: 0.5507 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5327 - accuracy: 0.7316 - val_loss: 0.5523 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.7393 - val_loss: 0.5468 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5113 - accuracy: 0.7474 - val_loss: 0.5478 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7563 - val_loss: 0.5636 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.7654 - val_loss: 0.5516 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4701 - accuracy: 0.7751 - val_loss: 0.5551 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4555 - accuracy: 0.7861 - val_loss: 0.5620 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4413 - accuracy: 0.7959
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4421 - accuracy: 0.7956 - val_loss: 0.5673 - val_accuracy: 0.7116 - lr: 0.0010
253/253 [==============================] - 0s 944us/step
Independent Testing Matthews Correlation:  0.46522718568027577
Confusion Matrix :
 [[2790 1257]
 [ 914 3133]]
Accuracy on test set:    0.7317766246602422
Sensitivity:    0.7741536940943909 	 Specificity:    0.6893995552260934
Precision  : 0.7136674259681094
Area Under Curve:    0.7317766246602422
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5920 - accuracy: 0.6805 - val_loss: 0.5589 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5496 - accuracy: 0.7195 - val_loss: 0.5545 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5338 - accuracy: 0.7310 - val_loss: 0.5571 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5224 - accuracy: 0.7388 - val_loss: 0.5543 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7463 - val_loss: 0.5499 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7521 - val_loss: 0.5558 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7597 - val_loss: 0.5586 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7683 - val_loss: 0.5557 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7755 - val_loss: 0.5651 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4582 - accuracy: 0.7849 - val_loss: 0.5667 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4465 - accuracy: 0.7906 - val_loss: 0.5678 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 12/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4324 - accuracy: 0.8004
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4330 - accuracy: 0.8000 - val_loss: 0.5727 - val_accuracy: 0.7117 - lr: 0.0010
253/253 [==============================] - 0s 760us/step
Independent Testing Matthews Correlation:  0.4781874933761579
Confusion Matrix :
 [[3087  960]
 [1154 2893]]
Accuracy on test set:    0.7388188781813689
Sensitivity:    0.7148505065480603 	 Specificity:    0.7627872498146775
Precision  : 0.7508434985725408
Area Under Curve:    0.7388188781813688
(8094, 2560) (8094,)
Mean MCC = 0.4317 + 0.0218 and Mean AUC = 0.7154 + 0.0109
Mean Sensitivity = 0.7362 + 0.0239 and Mean Specificity = 0.6947 + 0.0291 and Mean Accuracy = 0.7154 + 0.0109
Mean Precision = 0.7074 + 0.0167





Seed   : 273838
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5853 - accuracy: 0.6874 - val_loss: 0.5601 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7247 - val_loss: 0.5557 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7349 - val_loss: 0.5544 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5154 - accuracy: 0.7427 - val_loss: 0.5514 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7515 - val_loss: 0.5542 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7591 - val_loss: 0.5534 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7665 - val_loss: 0.5589 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4723 - accuracy: 0.7739 - val_loss: 0.5707 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4615 - accuracy: 0.7817
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4613 - accuracy: 0.7817 - val_loss: 0.5685 - val_accuracy: 0.7132 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4002538388923135
Confusion Matrix :
 [[2623 1425]
 [1011 3036]]
Accuracy on test set:    0.6990735021618283
Sensitivity:    0.7501853224610823 	 Specificity:    0.6479743083003953
Precision  : 0.6805648957632818
Area Under Curve:    0.6990798153807388
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5925 - accuracy: 0.6811 - val_loss: 0.5646 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7217 - val_loss: 0.5549 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7343 - val_loss: 0.5557 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7417 - val_loss: 0.5523 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7509 - val_loss: 0.5559 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7609 - val_loss: 0.5543 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4781 - accuracy: 0.7694 - val_loss: 0.5581 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4646 - accuracy: 0.7795 - val_loss: 0.5752 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4498 - accuracy: 0.7894 - val_loss: 0.5691 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4362 - accuracy: 0.7968 - val_loss: 0.5802 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 11/400
256/257 [============================>.] - ETA: 0s - loss: 0.4222 - accuracy: 0.8038
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4222 - accuracy: 0.8037 - val_loss: 0.5780 - val_accuracy: 0.7086 - lr: 0.0010
253/253 [==============================] - 0s 727us/step
Independent Testing Matthews Correlation:  0.40534009400776133
Confusion Matrix :
 [[2821 1227]
 [1180 2867]]
Accuracy on test set:    0.7026559604694256
Sensitivity:    0.7084259945638745 	 Specificity:    0.6968873517786561
Precision  : 0.7002931118710308
Area Under Curve:    0.7026566731712653
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5876 - accuracy: 0.6844 - val_loss: 0.5567 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7227 - val_loss: 0.5489 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7335 - val_loss: 0.5433 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7417 - val_loss: 0.5437 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7489 - val_loss: 0.5506 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7577 - val_loss: 0.5479 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7651 - val_loss: 0.5460 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7743 - val_loss: 0.5500 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 9/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4578 - accuracy: 0.7831
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4576 - accuracy: 0.7835 - val_loss: 0.5531 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42483082268561917
Confusion Matrix :
 [[2879 1168]
 [1160 2888]]
Accuracy on test set:    0.7124150710315009
Sensitivity:    0.7134387351778656 	 Specificity:    0.711391153941191
Precision  : 0.7120315581854043
Area Under Curve:    0.7124149445595284
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5850 - accuracy: 0.6849 - val_loss: 0.5505 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7223 - val_loss: 0.5552 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7330 - val_loss: 0.5434 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7420 - val_loss: 0.5423 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7529 - val_loss: 0.5429 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7586 - val_loss: 0.5432 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4785 - accuracy: 0.7694 - val_loss: 0.5536 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4658 - accuracy: 0.7785 - val_loss: 0.5551 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 9/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4503 - accuracy: 0.7885
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4507 - accuracy: 0.7880 - val_loss: 0.5540 - val_accuracy: 0.7220 - lr: 0.0010
253/253 [==============================] - 0s 749us/step
Independent Testing Matthews Correlation:  0.42932039430702335
Confusion Matrix :
 [[2863 1184]
 [1126 2922]]
Accuracy on test set:    0.7146386658431131
Sensitivity:    0.7218379446640316 	 Specificity:    0.707437608104769
Precision  : 0.711641500243546
Area Under Curve:    0.7146377763844003
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5844 - accuracy: 0.6866 - val_loss: 0.5486 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7235 - val_loss: 0.5456 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7343 - val_loss: 0.5411 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7433 - val_loss: 0.5444 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7509 - val_loss: 0.5455 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7602 - val_loss: 0.5497 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4793 - accuracy: 0.7685 - val_loss: 0.5545 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4678 - accuracy: 0.7760
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4680 - accuracy: 0.7760 - val_loss: 0.5580 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 997us/step
Independent Testing Matthews Correlation:  0.4123466189714464
Confusion Matrix :
 [[2659 1388]
 [ 998 3049]]
Accuracy on test set:    0.7052137385717816
Sensitivity:    0.7533975784531752 	 Specificity:    0.657029898690388
Precision  : 0.6871760198332206
Area Under Curve:    0.7052137385717816
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5853 - accuracy: 0.6856 - val_loss: 0.5563 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7220 - val_loss: 0.5420 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7349 - val_loss: 0.5405 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7405 - val_loss: 0.5494 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7493 - val_loss: 0.5475 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7567 - val_loss: 0.5452 - val_accuracy: 0.7231 - lr: 0.0010

Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4847 - accuracy: 0.7662
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.7664 - val_loss: 0.5485 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 826us/step
Independent Testing Matthews Correlation:  0.4412221049365901
Confusion Matrix :
 [[2753 1294]
 [ 973 3074]]
Accuracy on test set:    0.719915987150976
Sensitivity:    0.7595749938225846 	 Specificity:    0.6802569804793674
Precision  : 0.7037545787545788
Area Under Curve:    0.719915987150976
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5895 - accuracy: 0.6811 - val_loss: 0.5502 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7217 - val_loss: 0.5423 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7315 - val_loss: 0.5520 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.7417 - val_loss: 0.5438 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7465 - val_loss: 0.5431 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7554 - val_loss: 0.5502 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.7635 - val_loss: 0.5538 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4743 - accuracy: 0.7721 - val_loss: 0.5515 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4629 - accuracy: 0.7804 - val_loss: 0.5592 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4487 - accuracy: 0.7902 - val_loss: 0.5624 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4364 - accuracy: 0.7963 - val_loss: 0.5662 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 12/400
255/257 [============================>.] - ETA: 0s - loss: 0.4243 - accuracy: 0.8055
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4244 - accuracy: 0.8054 - val_loss: 0.5716 - val_accuracy: 0.7095 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41939691483342645
Confusion Matrix :
 [[2910 1137]
 [1213 2834]]
Accuracy on test set:    0.7096614776377563
Sensitivity:    0.700271806276254 	 Specificity:    0.7190511489992587
Precision  : 0.7136741374968522
Area Under Curve:    0.7096614776377563
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5896 - accuracy: 0.6824 - val_loss: 0.5496 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7209 - val_loss: 0.5443 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7334 - val_loss: 0.5413 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7397 - val_loss: 0.5430 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7465 - val_loss: 0.5476 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
256/257 [============================>.] - ETA: 0s - loss: 0.5008 - accuracy: 0.7535
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.5008 - accuracy: 0.7536 - val_loss: 0.5418 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 899us/step
Independent Testing Matthews Correlation:  0.4384416129367669
Confusion Matrix :
 [[2952 1095]
 [1178 2869]]
Accuracy on test set:    0.7191746973066468
Sensitivity:    0.7089201877934272 	 Specificity:    0.7294292068198666
Precision  : 0.7237638748738647
Area Under Curve:    0.719174697306647
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5921 - accuracy: 0.6806 - val_loss: 0.5605 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5489 - accuracy: 0.7211 - val_loss: 0.5508 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7309 - val_loss: 0.5486 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7396 - val_loss: 0.5472 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5101 - accuracy: 0.7475 - val_loss: 0.5537 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7545 - val_loss: 0.5558 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7635 - val_loss: 0.5646 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4770 - accuracy: 0.7694 - val_loss: 0.5556 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4632 - accuracy: 0.7804 - val_loss: 0.5611 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4526 - accuracy: 0.7874 - val_loss: 0.5675 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4397 - accuracy: 0.7942 - val_loss: 0.5717 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4265 - accuracy: 0.8029 - val_loss: 0.5785 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 13/400
250/257 [============================>.] - ETA: 0s - loss: 0.4149 - accuracy: 0.8098
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4151 - accuracy: 0.8094 - val_loss: 0.5861 - val_accuracy: 0.7124 - lr: 0.0010
253/253 [==============================] - 0s 816us/step
Independent Testing Matthews Correlation:  0.4428823246311126
Confusion Matrix :
 [[3099  948]
 [1314 2733]]
Accuracy on test set:    0.720533728687917
Sensitivity:    0.6753150481838399 	 Specificity:    0.765752409191994
Precision  : 0.7424612876935616
Area Under Curve:    0.720533728687917
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5938 - accuracy: 0.6805 - val_loss: 0.5544 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5512 - accuracy: 0.7191 - val_loss: 0.5469 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5364 - accuracy: 0.7280 - val_loss: 0.5486 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5245 - accuracy: 0.7378 - val_loss: 0.5482 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5140 - accuracy: 0.7443 - val_loss: 0.5520 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 6/400
254/257 [============================>.] - ETA: 0s - loss: 0.5027 - accuracy: 0.7548
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7550 - val_loss: 0.5490 - val_accuracy: 0.7130 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4999277956298346
Confusion Matrix :
 [[3064  983]
 [1041 3006]]
Accuracy on test set:    0.7499382258463059
Sensitivity:    0.742772424017791 	 Specificity:    0.7571040276748209
Precision  : 0.7535723238906994
Area Under Curve:    0.7499382258463059
(8094, 2560) (8094,)
Mean MCC = 0.4314 + 0.0268 and Mean AUC = 0.7153 + 0.0135
Mean Sensitivity = 0.7234 + 0.0259 and Mean Specificity = 0.7072 + 0.0366 and Mean Accuracy = 0.7153 + 0.0135
Mean Precision = 0.7129 + 0.0214





Seed   : 381220
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5852 - accuracy: 0.6866 - val_loss: 0.5584 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5418 - accuracy: 0.7254 - val_loss: 0.5494 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5252 - accuracy: 0.7358 - val_loss: 0.5497 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5118 - accuracy: 0.7451 - val_loss: 0.5481 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.7529 - val_loss: 0.5549 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4887 - accuracy: 0.7605 - val_loss: 0.5513 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4770 - accuracy: 0.7695
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7692 - val_loss: 0.5518 - val_accuracy: 0.7082 - lr: 0.0010
253/253 [==============================] - 0s 748us/step
Independent Testing Matthews Correlation:  0.4125232327935323
Confusion Matrix :
 [[2829 1219]
 [1159 2888]]
Accuracy on test set:    0.7062384187770229
Sensitivity:    0.7136150234741784 	 Specificity:    0.6988636363636364
Precision  : 0.7031896761626492
Area Under Curve:    0.7062393299189074
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5822 - accuracy: 0.6896 - val_loss: 0.5581 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5395 - accuracy: 0.7274 - val_loss: 0.5557 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5250 - accuracy: 0.7359 - val_loss: 0.5530 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5124 - accuracy: 0.7457 - val_loss: 0.5505 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.7545 - val_loss: 0.5490 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4886 - accuracy: 0.7629 - val_loss: 0.5548 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7694 - val_loss: 0.5573 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4651 - accuracy: 0.7788 - val_loss: 0.5595 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4525 - accuracy: 0.7879 - val_loss: 0.5609 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4408 - accuracy: 0.7937
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4408 - accuracy: 0.7937 - val_loss: 0.5695 - val_accuracy: 0.7069 - lr: 0.0010
253/253 [==============================] - 0s 818us/step
Independent Testing Matthews Correlation:  0.41614608934414
Confusion Matrix :
 [[2681 1367]
 [1003 3044]]
Accuracy on test set:    0.7072266831377394
Sensitivity:    0.7521620953792933 	 Specificity:    0.662302371541502
Precision  : 0.6900929494445704
Area Under Curve:    0.7072322334603977
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5878 - accuracy: 0.6845 - val_loss: 0.5518 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7209 - val_loss: 0.5411 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7326 - val_loss: 0.5400 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7397 - val_loss: 0.5383 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7485 - val_loss: 0.5400 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7577 - val_loss: 0.5420 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7648 - val_loss: 0.5488 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4718 - accuracy: 0.7743 - val_loss: 0.5523 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4592 - accuracy: 0.7819 - val_loss: 0.5592 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4471 - accuracy: 0.7901 - val_loss: 0.5606 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4357 - accuracy: 0.7961 - val_loss: 0.5648 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4246 - accuracy: 0.8036 - val_loss: 0.5704 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4132 - accuracy: 0.8097 - val_loss: 0.5807 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4024 - accuracy: 0.8159 - val_loss: 0.5745 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3906 - accuracy: 0.8238 - val_loss: 0.6036 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 16/400
244/257 [===========================>..] - ETA: 0s - loss: 0.3792 - accuracy: 0.8290
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3795 - accuracy: 0.8288 - val_loss: 0.6001 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 984us/step
Independent Testing Matthews Correlation:  0.4139657338255926
Confusion Matrix :
 [[2872 1175]
 [1197 2851]]
Accuracy on test set:    0.7069796170475602
Sensitivity:    0.704298418972332 	 Specificity:    0.7096614776377563
Precision  : 0.708147044212618
Area Under Curve:    0.7069799483050442
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5885 - accuracy: 0.6832 - val_loss: 0.5447 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5432 - accuracy: 0.7243 - val_loss: 0.5347 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7347 - val_loss: 0.5405 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7447 - val_loss: 0.5326 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7543 - val_loss: 0.5352 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.7592 - val_loss: 0.5355 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7683 - val_loss: 0.5366 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4695 - accuracy: 0.7779 - val_loss: 0.5420 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4559 - accuracy: 0.7841 - val_loss: 0.5445 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4406 - accuracy: 0.7947
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4415 - accuracy: 0.7936 - val_loss: 0.5536 - val_accuracy: 0.7209 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4208428095784178
Confusion Matrix :
 [[2664 1383]
 [ 970 3078]]
Accuracy on test set:    0.7093267449042618
Sensitivity:    0.7603754940711462 	 Specificity:    0.6582653817642699
Precision  : 0.6899798251513114
Area Under Curve:    0.709320437917708
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5895 - accuracy: 0.6824 - val_loss: 0.5543 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7221 - val_loss: 0.5514 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7340 - val_loss: 0.5394 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7414 - val_loss: 0.5383 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7495 - val_loss: 0.5383 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7578 - val_loss: 0.5435 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7664 - val_loss: 0.5473 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4730 - accuracy: 0.7743 - val_loss: 0.5461 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4591 - accuracy: 0.7837
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4597 - accuracy: 0.7834 - val_loss: 0.5523 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 798us/step
Independent Testing Matthews Correlation:  0.4325818178085781
Confusion Matrix :
 [[2843 1204]
 [1093 2954]]
Accuracy on test set:    0.7162095379293304
Sensitivity:    0.7299234000494194 	 Specificity:    0.7024956758092414
Precision  : 0.7104377104377104
Area Under Curve:    0.7162095379293303
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5857 - accuracy: 0.6872 - val_loss: 0.5624 - val_accuracy: 0.7040 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7241 - val_loss: 0.5431 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7343 - val_loss: 0.5421 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7425 - val_loss: 0.5436 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7483 - val_loss: 0.5413 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7565 - val_loss: 0.5448 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4858 - accuracy: 0.7655 - val_loss: 0.5519 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4744 - accuracy: 0.7734 - val_loss: 0.5537 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4630 - accuracy: 0.7807 - val_loss: 0.5629 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4502 - accuracy: 0.7895
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4505 - accuracy: 0.7893 - val_loss: 0.5558 - val_accuracy: 0.7207 - lr: 0.0010
253/253 [==============================] - 0s 718us/step
Independent Testing Matthews Correlation:  0.41428421763811407
Confusion Matrix :
 [[2807 1240]
 [1131 2916]]
Accuracy on test set:    0.7070669631826044
Sensitivity:    0.720533728687917 	 Specificity:    0.6936001976772919
Precision  : 0.7016361886429259
Area Under Curve:    0.7070669631826045
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5884 - accuracy: 0.6852 - val_loss: 0.5642 - val_accuracy: 0.7027 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7229 - val_loss: 0.5401 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7308 - val_loss: 0.5418 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7419 - val_loss: 0.5392 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7492 - val_loss: 0.5398 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4995 - accuracy: 0.7549 - val_loss: 0.5417 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4867 - accuracy: 0.7637 - val_loss: 0.5413 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7723 - val_loss: 0.5458 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4641 - accuracy: 0.7793 - val_loss: 0.5510 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4517 - accuracy: 0.7883
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4519 - accuracy: 0.7877 - val_loss: 0.5527 - val_accuracy: 0.7152 - lr: 0.0010
253/253 [==============================] - 0s 864us/step
Independent Testing Matthews Correlation:  0.4133200741460136
Confusion Matrix :
 [[3024 1023]
 [1357 2690]]
Accuracy on test set:    0.7059550284161107
Sensitivity:    0.6646898937484557 	 Specificity:    0.7472201630837657
Precision  : 0.7244815513062214
Area Under Curve:    0.7059550284161109
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5925 - accuracy: 0.6810 - val_loss: 0.5522 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7214 - val_loss: 0.5414 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7319 - val_loss: 0.5378 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7402 - val_loss: 0.5407 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7486 - val_loss: 0.5398 - val_accuracy: 0.7251 - lr: 0.0010

Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7557 - val_loss: 0.5449 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.7623 - val_loss: 0.5507 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4765 - accuracy: 0.7713 - val_loss: 0.5417 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4654 - accuracy: 0.7782 - val_loss: 0.5485 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4530 - accuracy: 0.7873
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4529 - accuracy: 0.7873 - val_loss: 0.5660 - val_accuracy: 0.7213 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4399049644655253
Confusion Matrix :
 [[2727 1320]
 [ 954 3093]]
Accuracy on test set:    0.7190511489992587
Sensitivity:    0.7642698295033358 	 Specificity:    0.6738324684951816
Precision  : 0.7008837525492863
Area Under Curve:    0.7190511489992587
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5894 - accuracy: 0.6847 - val_loss: 0.5521 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7201 - val_loss: 0.5448 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7311 - val_loss: 0.5422 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7399 - val_loss: 0.5413 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5105 - accuracy: 0.7481 - val_loss: 0.5387 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5003 - accuracy: 0.7563 - val_loss: 0.5456 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4886 - accuracy: 0.7636 - val_loss: 0.5448 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7734 - val_loss: 0.5425 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4644 - accuracy: 0.7798 - val_loss: 0.5479 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4494 - accuracy: 0.7884
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4496 - accuracy: 0.7883 - val_loss: 0.5518 - val_accuracy: 0.7202 - lr: 0.0010
253/253 [==============================] - 0s 794us/step
Independent Testing Matthews Correlation:  0.47121606393668714
Confusion Matrix :
 [[2970 1077]
 [1063 2984]]
Accuracy on test set:    0.735606622189276
Sensitivity:    0.7373362984927107 	 Specificity:    0.7338769458858414
Precision  : 0.7347943856193055
Area Under Curve:    0.735606622189276
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5875 - accuracy: 0.6845 - val_loss: 0.5636 - val_accuracy: 0.7014 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5486 - accuracy: 0.7205 - val_loss: 0.5408 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7320 - val_loss: 0.5387 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7407 - val_loss: 0.5444 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.7491 - val_loss: 0.5433 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7570 - val_loss: 0.5385 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4862 - accuracy: 0.7657 - val_loss: 0.5453 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4733 - accuracy: 0.7725 - val_loss: 0.5436 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4626 - accuracy: 0.7819 - val_loss: 0.5441 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4494 - accuracy: 0.7897 - val_loss: 0.5580 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4368 - accuracy: 0.7990 - val_loss: 0.5593 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4249 - accuracy: 0.8044 - val_loss: 0.5601 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 13/400
250/257 [============================>.] - ETA: 0s - loss: 0.4105 - accuracy: 0.8129
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4111 - accuracy: 0.8125 - val_loss: 0.5760 - val_accuracy: 0.7121 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.48695969374581555
Confusion Matrix :
 [[2826 1221]
 [ 863 3184]]
Accuracy on test set:    0.7425253274030146
Sensitivity:    0.7867556214479862 	 Specificity:    0.698295033358043
Precision  : 0.7228149829738933
Area Under Curve:    0.7425253274030146
(8094, 2560) (8094,)
Mean MCC = 0.4322 + 0.0252 and Mean AUC = 0.7156 + 0.0125
Mean Sensitivity = 0.7334 + 0.0332 and Mean Specificity = 0.6978 + 0.0271 and Mean Accuracy = 0.7156 + 0.0125
Mean Precision = 0.7086 + 0.0140





Seed   : 843020
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5827 - accuracy: 0.6874 - val_loss: 0.5598 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7250 - val_loss: 0.5544 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5270 - accuracy: 0.7349 - val_loss: 0.5533 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7420 - val_loss: 0.5549 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7514 - val_loss: 0.5571 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7585 - val_loss: 0.5645 - val_accuracy: 0.7054 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7659 - val_loss: 0.5557 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7730 - val_loss: 0.5579 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4632 - accuracy: 0.7813 - val_loss: 0.5690 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4500 - accuracy: 0.7891
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4505 - accuracy: 0.7887 - val_loss: 0.5645 - val_accuracy: 0.7076 - lr: 0.0010
253/253 [==============================] - 0s 738us/step
Independent Testing Matthews Correlation:  0.39919149887403543
Confusion Matrix :
 [[2753 1295]
 [1138 2909]]
Accuracy on test set:    0.699444101297097
Sensitivity:    0.7188040523844823 	 Specificity:    0.6800889328063241
Precision  : 0.6919600380589914
Area Under Curve:    0.6994464925954031
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5859 - accuracy: 0.6854 - val_loss: 0.5627 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7251 - val_loss: 0.5570 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5261 - accuracy: 0.7362 - val_loss: 0.5524 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7450 - val_loss: 0.5592 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7501 - val_loss: 0.5558 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7590 - val_loss: 0.5580 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4825 - accuracy: 0.7678 - val_loss: 0.5638 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7750 - val_loss: 0.5643 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4592 - accuracy: 0.7838 - val_loss: 0.5657 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4448 - accuracy: 0.7935
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4448 - accuracy: 0.7935 - val_loss: 0.5687 - val_accuracy: 0.7040 - lr: 0.0010
253/253 [==============================] - 0s 966us/step
Independent Testing Matthews Correlation:  0.4128345532432249
Confusion Matrix :
 [[2813 1235]
 [1142 2905]]
Accuracy on test set:    0.7063619518221124
Sensitivity:    0.7178156659253768 	 Specificity:    0.6949110671936759
Precision  : 0.7016908212560387
Area Under Curve:    0.7063633665595264
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5863 - accuracy: 0.6846 - val_loss: 0.5538 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7232 - val_loss: 0.5429 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7349 - val_loss: 0.5414 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5148 - accuracy: 0.7426 - val_loss: 0.5402 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7514 - val_loss: 0.5437 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7594 - val_loss: 0.5427 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7680 - val_loss: 0.5435 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4702 - accuracy: 0.7744 - val_loss: 0.5474 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4560 - accuracy: 0.7862 - val_loss: 0.5567 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4450 - accuracy: 0.7926 - val_loss: 0.5530 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4344 - accuracy: 0.7990 - val_loss: 0.5575 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4235 - accuracy: 0.8065 - val_loss: 0.5625 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4099 - accuracy: 0.8142 - val_loss: 0.5768 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3983 - accuracy: 0.8194 - val_loss: 0.5840 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 15/400
245/257 [===========================>..] - ETA: 0s - loss: 0.3823 - accuracy: 0.8288
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3829 - accuracy: 0.8286 - val_loss: 0.5777 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41749040462040393
Confusion Matrix :
 [[2830 1217]
 [1141 2907]]
Accuracy on test set:    0.7087090796788141
Sensitivity:    0.7181324110671937 	 Specificity:    0.6992834198171485
Precision  : 0.704898157129001
Area Under Curve:    0.708707915442171
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5868 - accuracy: 0.6857 - val_loss: 0.5550 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7226 - val_loss: 0.5533 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7343 - val_loss: 0.5422 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7416 - val_loss: 0.5378 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7509 - val_loss: 0.5377 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7584 - val_loss: 0.5367 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7664 - val_loss: 0.5379 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.7743 - val_loss: 0.5442 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4572 - accuracy: 0.7835 - val_loss: 0.5507 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4414 - accuracy: 0.7943 - val_loss: 0.5584 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4270 - accuracy: 0.8025 - val_loss: 0.5640 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - ETA: 0s - loss: 0.4146 - accuracy: 0.8084
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4146 - accuracy: 0.8084 - val_loss: 0.5646 - val_accuracy: 0.7224 - lr: 0.0010
253/253 [==============================] - 0s 951us/step
Independent Testing Matthews Correlation:  0.4129984580211513
Confusion Matrix :
 [[2882 1165]
 [1211 2837]]
Accuracy on test set:    0.706485484867202
Sensitivity:    0.7008399209486166 	 Specificity:    0.7121324437855201
Precision  : 0.708895552223888
Area Under Curve:    0.7064861823670683
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5890 - accuracy: 0.6832 - val_loss: 0.5591 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7210 - val_loss: 0.5485 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7326 - val_loss: 0.5459 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7419 - val_loss: 0.5466 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7497 - val_loss: 0.5508 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7574 - val_loss: 0.5485 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4863 - accuracy: 0.7649 - val_loss: 0.5536 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.7718 - val_loss: 0.5571 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.7800 - val_loss: 0.5547 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4520 - accuracy: 0.7893 - val_loss: 0.5613 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 11/400
249/257 [============================>.] - ETA: 0s - loss: 0.4406 - accuracy: 0.7933
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4412 - accuracy: 0.7931 - val_loss: 0.5596 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4135872995133283
Confusion Matrix :
 [[2766 1281]
 [1094 2953]]
Accuracy on test set:    0.7065727699530516
Sensitivity:    0.729676303434643 	 Specificity:    0.6834692364714603
Precision  : 0.6974492205951819
Area Under Curve:    0.7065727699530516
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5897 - accuracy: 0.6810 - val_loss: 0.5665 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7211 - val_loss: 0.5526 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7314 - val_loss: 0.5490 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7412 - val_loss: 0.5499 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5122 - accuracy: 0.7461 - val_loss: 0.5509 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.7552 - val_loss: 0.5503 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.7646 - val_loss: 0.5551 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4802 - accuracy: 0.7687 - val_loss: 0.5579 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4672 - accuracy: 0.7791 - val_loss: 0.5632 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 10/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4551 - accuracy: 0.7860
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4556 - accuracy: 0.7859 - val_loss: 0.5672 - val_accuracy: 0.7148 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43070379461868036
Confusion Matrix :
 [[2755 1292]
 [1016 3031]]
Accuracy on test set:    0.7148505065480603
Sensitivity:    0.7489498393872004 	 Specificity:    0.6807511737089202
Precision  : 0.7011334721258385
Area Under Curve:    0.7148505065480603
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5878 - accuracy: 0.6862 - val_loss: 0.5553 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7236 - val_loss: 0.5530 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7311 - val_loss: 0.5514 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7407 - val_loss: 0.5522 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.7473 - val_loss: 0.5504 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 6/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4987 - accuracy: 0.7546
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4987 - accuracy: 0.7544 - val_loss: 0.5519 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 930us/step
Independent Testing Matthews Correlation:  0.4222984989569354
Confusion Matrix :
 [[2705 1342]
 [1002 3045]]
Accuracy on test set:    0.7104027674820855
Sensitivity:    0.7524091919940696 	 Specificity:    0.6683963429701013
Precision  : 0.6940961932983816
Area Under Curve:    0.7104027674820854
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5890 - accuracy: 0.6810 - val_loss: 0.5542 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7247 - val_loss: 0.5469 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7323 - val_loss: 0.5444 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7407 - val_loss: 0.5428 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7477 - val_loss: 0.5443 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7580 - val_loss: 0.5445 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4858 - accuracy: 0.7649 - val_loss: 0.5511 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7740 - val_loss: 0.5727 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4620 - accuracy: 0.7814 - val_loss: 0.5531 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4489 - accuracy: 0.7890 - val_loss: 0.5611 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 11/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4351 - accuracy: 0.8000
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4356 - accuracy: 0.7993 - val_loss: 0.5628 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 776us/step
Independent Testing Matthews Correlation:  0.4272724377213136
Confusion Matrix :
 [[2764 1283]
 [1038 3009]]
Accuracy on test set:    0.7132443785520138
Sensitivity:    0.7435137138621201 	 Specificity:    0.6829750432419076
Precision  : 0.701071761416589
Area Under Curve:    0.7132443785520138
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5893 - accuracy: 0.6840 - val_loss: 0.5588 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5480 - accuracy: 0.7208 - val_loss: 0.5520 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5334 - accuracy: 0.7305 - val_loss: 0.5504 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5210 - accuracy: 0.7384 - val_loss: 0.5512 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5101 - accuracy: 0.7466 - val_loss: 0.5524 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.7554 - val_loss: 0.5549 - val_accuracy: 0.7141 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4900 - accuracy: 0.7624 - val_loss: 0.5564 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.7708 - val_loss: 0.5576 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7801 - val_loss: 0.5621 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 10/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4531 - accuracy: 0.7879
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4537 - accuracy: 0.7874 - val_loss: 0.5675 - val_accuracy: 0.7124 - lr: 0.0010
253/253 [==============================] - 0s 921us/step
Independent Testing Matthews Correlation:  0.46401747591072895
Confusion Matrix :
 [[3073  974]
 [1198 2849]]
Accuracy on test set:    0.7316530763528539
Sensitivity:    0.7039782554978997 	 Specificity:    0.7593278972078082
Precision  : 0.7452262620978289
Area Under Curve:    0.7316530763528539
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5907 - accuracy: 0.6840 - val_loss: 0.5646 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5489 - accuracy: 0.7202 - val_loss: 0.5581 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5343 - accuracy: 0.7307 - val_loss: 0.5584 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5240 - accuracy: 0.7388 - val_loss: 0.5488 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5148 - accuracy: 0.7440 - val_loss: 0.5516 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7532 - val_loss: 0.5491 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.7624 - val_loss: 0.5558 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.7704 - val_loss: 0.5638 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4692 - accuracy: 0.7771
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4693 - accuracy: 0.7770 - val_loss: 0.5619 - val_accuracy: 0.7108 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4886214187932354
Confusion Matrix :
 [[3089  958]
 [1113 2934]]
Accuracy on test set:    0.744131455399061
Sensitivity:    0.7249814677538917 	 Specificity:    0.7632814430442303
Precision  : 0.7538540596094553
Area Under Curve:    0.744131455399061
(8094, 2560) (8094,)
Mean MCC = 0.4289 + 0.0257 and Mean AUC = 0.7142 + 0.0128
Mean Sensitivity = 0.7259 + 0.0169 and Mean Specificity = 0.7025 + 0.0316 and Mean Accuracy = 0.7142 + 0.0128
Mean Precision = 0.7100 + 0.0204





Seed   : 18705
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5858 - accuracy: 0.6864 - val_loss: 0.5583 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7240 - val_loss: 0.5524 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7351 - val_loss: 0.5526 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7426 - val_loss: 0.5536 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7499 - val_loss: 0.5497 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7577 - val_loss: 0.5554 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4866 - accuracy: 0.7650 - val_loss: 0.5516 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4759 - accuracy: 0.7721 - val_loss: 0.5575 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4641 - accuracy: 0.7814 - val_loss: 0.5567 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4535 - accuracy: 0.7869 - val_loss: 0.5673 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 11/400
252/257 [============================>.] - ETA: 0s - loss: 0.4402 - accuracy: 0.7963
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4400 - accuracy: 0.7966 - val_loss: 0.5703 - val_accuracy: 0.7087 - lr: 0.0010
253/253 [==============================] - 0s 759us/step
Independent Testing Matthews Correlation:  0.40334584176171745
Confusion Matrix :
 [[2569 1479]
 [ 950 3097]]
Accuracy on test set:    0.6999382334774552
Sensitivity:    0.7652582159624414 	 Specificity:    0.6346343873517787
Precision  : 0.676791958041958
Area Under Curve:    0.6999463016571101
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5889 - accuracy: 0.6839 - val_loss: 0.5611 - val_accuracy: 0.7036 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7243 - val_loss: 0.5513 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7331 - val_loss: 0.5491 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7422 - val_loss: 0.5477 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7487 - val_loss: 0.5493 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.7570 - val_loss: 0.5512 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.7640 - val_loss: 0.5496 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4766 - accuracy: 0.7722 - val_loss: 0.5506 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4668 - accuracy: 0.7772 - val_loss: 0.5567 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 10/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4545 - accuracy: 0.7856
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4550 - accuracy: 0.7852 - val_loss: 0.5629 - val_accuracy: 0.7065 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4246521763553525
Confusion Matrix :
 [[2708 1340]
 [ 995 3052]]
Accuracy on test set:    0.711550339715874
Sensitivity:    0.7541388682975043 	 Specificity:    0.6689723320158103
Precision  : 0.6948998178506375
Area Under Curve:    0.7115556001566573
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5854 - accuracy: 0.6877 - val_loss: 0.5553 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7245 - val_loss: 0.5444 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7351 - val_loss: 0.5419 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7429 - val_loss: 0.5440 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7522 - val_loss: 0.5433 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7578 - val_loss: 0.5486 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.7643 - val_loss: 0.5561 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7725 - val_loss: 0.5641 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4609 - accuracy: 0.7807 - val_loss: 0.5552 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4474 - accuracy: 0.7883 - val_loss: 0.5622 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4357 - accuracy: 0.7977 - val_loss: 0.5660 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4228 - accuracy: 0.8046 - val_loss: 0.5720 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4097 - accuracy: 0.8132 - val_loss: 0.5781 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3976 - accuracy: 0.8214 - val_loss: 0.5842 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3861 - accuracy: 0.8263 - val_loss: 0.5975 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3726 - accuracy: 0.8339 - val_loss: 0.6124 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 17/400
252/257 [============================>.] - ETA: 0s - loss: 0.3634 - accuracy: 0.8386
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3638 - accuracy: 0.8385 - val_loss: 0.6197 - val_accuracy: 0.7104 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4028060240829284
Confusion Matrix :
 [[2697 1350]
 [1071 2977]]
Accuracy on test set:    0.7009264978381717
Sensitivity:    0.7354249011857708 	 Specificity:    0.6664195700518903
Precision  : 0.688005546568061
Area Under Curve:    0.7009222356188304
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5861 - accuracy: 0.6859 - val_loss: 0.5528 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7244 - val_loss: 0.5447 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7335 - val_loss: 0.5420 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7434 - val_loss: 0.5422 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7518 - val_loss: 0.5405 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7588 - val_loss: 0.5442 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.7689 - val_loss: 0.5434 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4689 - accuracy: 0.7757 - val_loss: 0.5460 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4574 - accuracy: 0.7837 - val_loss: 0.5517 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4432 - accuracy: 0.7926 - val_loss: 0.5627 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4306 - accuracy: 0.8013 - val_loss: 0.5642 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4192 - accuracy: 0.8068 - val_loss: 0.5741 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - ETA: 0s - loss: 0.4070 - accuracy: 0.8156
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4070 - accuracy: 0.8156 - val_loss: 0.5781 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 780us/step
Independent Testing Matthews Correlation:  0.413956132526253
Confusion Matrix :
 [[2613 1434]
 [ 950 3098]]
Accuracy on test set:    0.7054972205064854
Sensitivity:    0.7653162055335968 	 Specificity:    0.6456634544106745
Precision  : 0.6835834068843778
Area Under Curve:    0.7054898299721357
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5902 - accuracy: 0.6795 - val_loss: 0.5581 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7233 - val_loss: 0.5469 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7322 - val_loss: 0.5431 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7415 - val_loss: 0.5419 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7480 - val_loss: 0.5446 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7580 - val_loss: 0.5415 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7664 - val_loss: 0.5469 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4730 - accuracy: 0.7742 - val_loss: 0.5482 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4596 - accuracy: 0.7828 - val_loss: 0.5575 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4472 - accuracy: 0.7889
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4475 - accuracy: 0.7888 - val_loss: 0.5613 - val_accuracy: 0.7132 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42316647993746187
Confusion Matrix :
 [[2828 1219]
 [1116 2931]]
Accuracy on test set:    0.7115147022485792
Sensitivity:    0.7242401779095626 	 Specificity:    0.6987892265875958
Precision  : 0.7062650602409638
Area Under Curve:    0.7115147022485792
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5842 - accuracy: 0.6866 - val_loss: 0.5525 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7220 - val_loss: 0.5467 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7326 - val_loss: 0.5512 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7420 - val_loss: 0.5565 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7490 - val_loss: 0.5557 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 6/400

257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7572 - val_loss: 0.5455 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - ETA: 0s - loss: 0.4840 - accuracy: 0.7660
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7660 - val_loss: 0.5498 - val_accuracy: 0.7112 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4330575060702893
Confusion Matrix :
 [[2632 1415]
 [ 894 3153]]
Accuracy on test set:    0.7147269582406721
Sensitivity:    0.7790956263899185 	 Specificity:    0.6503582900914258
Precision  : 0.6902364273204904
Area Under Curve:    0.7147269582406721
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5823 - accuracy: 0.6895 - val_loss: 0.5457 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7239 - val_loss: 0.5398 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7334 - val_loss: 0.5451 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7429 - val_loss: 0.5381 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7498 - val_loss: 0.5410 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
250/257 [============================>.] - ETA: 0s - loss: 0.4968 - accuracy: 0.7565
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7561 - val_loss: 0.5371 - val_accuracy: 0.7226 - lr: 0.0010
253/253 [==============================] - 0s 763us/step
Independent Testing Matthews Correlation:  0.43344251709215964
Confusion Matrix :
 [[2827 1220]
 [1074 2973]]
Accuracy on test set:    0.7165801828514949
Sensitivity:    0.7346182357301705 	 Specificity:    0.6985421299728194
Precision  : 0.7090388743143334
Area Under Curve:    0.7165801828514949
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5865 - accuracy: 0.6848 - val_loss: 0.5577 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7226 - val_loss: 0.5462 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7333 - val_loss: 0.5372 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5150 - accuracy: 0.7435 - val_loss: 0.5328 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7529 - val_loss: 0.5337 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7630 - val_loss: 0.5375 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4778 - accuracy: 0.7698 - val_loss: 0.5427 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4636 - accuracy: 0.7810 - val_loss: 0.5450 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4498 - accuracy: 0.7900 - val_loss: 0.5501 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4376 - accuracy: 0.7950
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4378 - accuracy: 0.7950 - val_loss: 0.5487 - val_accuracy: 0.7167 - lr: 0.0010
253/253 [==============================] - 0s 791us/step
Independent Testing Matthews Correlation:  0.43263215296552787
Confusion Matrix :
 [[2962 1085]
 [1212 2835]]
Accuracy on test set:    0.7162095379293304
Sensitivity:    0.7005189028910304 	 Specificity:    0.7319001729676303
Precision  : 0.7232142857142857
Area Under Curve:    0.7162095379293303
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5921 - accuracy: 0.6816 - val_loss: 0.5602 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5493 - accuracy: 0.7208 - val_loss: 0.5466 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5340 - accuracy: 0.7296 - val_loss: 0.5406 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5227 - accuracy: 0.7384 - val_loss: 0.5412 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.7469 - val_loss: 0.5400 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7550 - val_loss: 0.5611 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4897 - accuracy: 0.7630 - val_loss: 0.5499 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4777 - accuracy: 0.7718 - val_loss: 0.5482 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4631 - accuracy: 0.7827 - val_loss: 0.5577 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4510 - accuracy: 0.7881 - val_loss: 0.5624 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4369 - accuracy: 0.7968 - val_loss: 0.5666 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4258 - accuracy: 0.8022 - val_loss: 0.5723 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4121 - accuracy: 0.8115 - val_loss: 0.5769 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3992 - accuracy: 0.8186 - val_loss: 0.5924 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 15/400
247/257 [===========================>..] - ETA: 0s - loss: 0.3844 - accuracy: 0.8256
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3836 - accuracy: 0.8260 - val_loss: 0.6009 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 0s 746us/step
Independent Testing Matthews Correlation:  0.46350996043488635
Confusion Matrix :
 [[2901 1146]
 [1026 3021]]
Accuracy on test set:    0.7316530763528539
Sensitivity:    0.7464788732394366 	 Specificity:    0.7168272794662713
Precision  : 0.7249820014398848
Area Under Curve:    0.7316530763528539
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.6813 - val_loss: 0.5573 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5485 - accuracy: 0.7211 - val_loss: 0.5501 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5352 - accuracy: 0.7301 - val_loss: 0.5478 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5228 - accuracy: 0.7381 - val_loss: 0.5562 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7459 - val_loss: 0.5464 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5024 - accuracy: 0.7543 - val_loss: 0.5541 - val_accuracy: 0.7123 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7610 - val_loss: 0.5545 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7680 - val_loss: 0.5594 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4701 - accuracy: 0.7753 - val_loss: 0.5637 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4595 - accuracy: 0.7827
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4596 - accuracy: 0.7825 - val_loss: 0.5626 - val_accuracy: 0.7116 - lr: 0.0010
253/253 [==============================] - 0s 863us/step
Independent Testing Matthews Correlation:  0.48392558258786184
Confusion Matrix :
 [[3121  926]
 [1166 2881]]
Accuracy on test set:    0.7415369409439091
Sensitivity:    0.7118853471707438 	 Specificity:    0.7711885347170744
Precision  : 0.7567638560546361
Area Under Curve:    0.7415369409439091
(8094, 2560) (8094,)
Mean MCC = 0.4314 + 0.0241 and Mean AUC = 0.7150 + 0.0123
Mean Sensitivity = 0.7417 + 0.0238 and Mean Specificity = 0.6883 + 0.0410 and Mean Accuracy = 0.7150 + 0.0123
Mean Precision = 0.7054 + 0.0230





Seed   : 926203
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5877 - accuracy: 0.6836 - val_loss: 0.5622 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7242 - val_loss: 0.5539 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7342 - val_loss: 0.5537 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7412 - val_loss: 0.5530 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7457 - val_loss: 0.5525 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4989 - accuracy: 0.7547 - val_loss: 0.5532 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.7611 - val_loss: 0.5587 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4792 - accuracy: 0.7686
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4791 - accuracy: 0.7688 - val_loss: 0.5674 - val_accuracy: 0.7113 - lr: 0.0010
253/253 [==============================] - 0s 757us/step
Independent Testing Matthews Correlation:  0.40827442765749034
Confusion Matrix :
 [[2562 1486]
 [ 925 3122]]
Accuracy on test set:    0.7021618282890674
Sensitivity:    0.7714356313318508 	 Specificity:    0.6329051383399209
Precision  : 0.6775173611111112
Area Under Curve:    0.7021703848358858
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5812 - accuracy: 0.6904 - val_loss: 0.5605 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5393 - accuracy: 0.7263 - val_loss: 0.5493 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5239 - accuracy: 0.7356 - val_loss: 0.5489 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5118 - accuracy: 0.7458 - val_loss: 0.5482 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.7532 - val_loss: 0.5510 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4905 - accuracy: 0.7625 - val_loss: 0.5533 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4775 - accuracy: 0.7690 - val_loss: 0.5565 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4649 - accuracy: 0.7767 - val_loss: 0.5633 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4512 - accuracy: 0.7878 - val_loss: 0.5689 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4384 - accuracy: 0.7960 - val_loss: 0.5648 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4291 - accuracy: 0.7999 - val_loss: 0.5820 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4153 - accuracy: 0.8082
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4159 - accuracy: 0.8079 - val_loss: 0.5839 - val_accuracy: 0.7119 - lr: 0.0010
253/253 [==============================] - 0s 867us/step
Independent Testing Matthews Correlation:  0.41356895815763184
Confusion Matrix :
 [[2816 1232]
 [1142 2905]]
Accuracy on test set:    0.7067325509573811
Sensitivity:    0.7178156659253768 	 Specificity:    0.6956521739130435
Precision  : 0.7021996615905245
Area Under Curve:    0.7067339199192102
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5852 - accuracy: 0.6871 - val_loss: 0.5529 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7208 - val_loss: 0.5406 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7328 - val_loss: 0.5411 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5168 - accuracy: 0.7432 - val_loss: 0.5434 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7510 - val_loss: 0.5402 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4918 - accuracy: 0.7596 - val_loss: 0.5415 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4801 - accuracy: 0.7693 - val_loss: 0.5452 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.7773 - val_loss: 0.5501 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4529 - accuracy: 0.7856 - val_loss: 0.5553 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4407 - accuracy: 0.7946 - val_loss: 0.5592 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4275 - accuracy: 0.8008 - val_loss: 0.5564 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4148 - accuracy: 0.8108
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4148 - accuracy: 0.8109 - val_loss: 0.5709 - val_accuracy: 0.7244 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4207398971622058
Confusion Matrix :
 [[2744 1303]
 [1045 3003]]
Accuracy on test set:    0.7099444101297097
Sensitivity:    0.7418478260869565 	 Specificity:    0.6780331109463801
Precision  : 0.6973989781699954
Area Under Curve:    0.7099404685166683
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5883 - accuracy: 0.6828 - val_loss: 0.5453 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7239 - val_loss: 0.5400 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7333 - val_loss: 0.5356 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7431 - val_loss: 0.5341 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7521 - val_loss: 0.5368 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4927 - accuracy: 0.7586 - val_loss: 0.5363 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7694 - val_loss: 0.5401 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4675 - accuracy: 0.7777
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4675 - accuracy: 0.7779 - val_loss: 0.5431 - val_accuracy: 0.7251 - lr: 0.0010
253/253 [==============================] - 0s 806us/step
Independent Testing Matthews Correlation:  0.4199161803947612
Confusion Matrix :
 [[2799 1248]
 [1101 2947]]
Accuracy on test set:    0.7098208770846202
Sensitivity:    0.7280138339920948 	 Specificity:    0.6916234247590808
Precision  : 0.7025029797377831
Area Under Curve:    0.7098186293755877
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5915 - accuracy: 0.6818 - val_loss: 0.5535 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7215 - val_loss: 0.5436 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5331 - accuracy: 0.7299 - val_loss: 0.5424 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5227 - accuracy: 0.7381 - val_loss: 0.5425 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5139 - accuracy: 0.7425 - val_loss: 0.5443 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7498 - val_loss: 0.5444 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7594 - val_loss: 0.5499 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7677 - val_loss: 0.5503 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.7742 - val_loss: 0.5539 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4582 - accuracy: 0.7816 - val_loss: 0.5571 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - ETA: 0s - loss: 0.4458 - accuracy: 0.7900
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4458 - accuracy: 0.7900 - val_loss: 0.5696 - val_accuracy: 0.7134 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42807045008539096
Confusion Matrix :
 [[2782 1265]
 [1052 2995]]
Accuracy on test set:    0.7137385717815666
Sensitivity:    0.7400543612552508 	 Specificity:    0.6874227823078823
Precision  : 0.7030516431924883
Area Under Curve:    0.7137385717815667
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5839 - accuracy: 0.6884 - val_loss: 0.5551 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7230 - val_loss: 0.5515 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7341 - val_loss: 0.5504 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7399 - val_loss: 0.5496 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7500 - val_loss: 0.5528 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7583 - val_loss: 0.5536 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7659 - val_loss: 0.5572 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4699 - accuracy: 0.7765 - val_loss: 0.5599 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4542 - accuracy: 0.7850
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4547 - accuracy: 0.7847 - val_loss: 0.5756 - val_accuracy: 0.7116 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4210978113263401
Confusion Matrix :
 [[2555 1492]
 [ 871 3176]]
Accuracy on test set:    0.7080553496417099
Sensitivity:    0.7847788485297752 	 Specificity:    0.6313318507536447
Precision  : 0.6803770351328192
Area Under Curve:    0.7080553496417099
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5846 - accuracy: 0.6865 - val_loss: 0.5532 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5422 - accuracy: 0.7239 - val_loss: 0.5475 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5263 - accuracy: 0.7358 - val_loss: 0.5506 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5138 - accuracy: 0.7422 - val_loss: 0.5460 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5006 - accuracy: 0.7539 - val_loss: 0.5524 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7608 - val_loss: 0.5497 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4760 - accuracy: 0.7710 - val_loss: 0.5554 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4640 - accuracy: 0.7791 - val_loss: 0.5537 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4506 - accuracy: 0.7900 - val_loss: 0.5600 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4368 - accuracy: 0.7975 - val_loss: 0.5637 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4207 - accuracy: 0.8085 - val_loss: 0.5695 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 12/400
253/257 [============================>.] - ETA: 0s - loss: 0.4096 - accuracy: 0.8144
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4099 - accuracy: 0.8140 - val_loss: 0.5818 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.426851011742998
Confusion Matrix :
 [[2840 1207]
 [1113 2934]]
Accuracy on test set:    0.713367926859402
Sensitivity:    0.7249814677538917 	 Specificity:    0.7017543859649122
Precision  : 0.7085245109876841
Area Under Curve:    0.713367926859402
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5859 - accuracy: 0.6868 - val_loss: 0.5494 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7218 - val_loss: 0.5450 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7335 - val_loss: 0.5449 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7394 - val_loss: 0.5446 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7478 - val_loss: 0.5523 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4991 - accuracy: 0.7531 - val_loss: 0.5507 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.7621 - val_loss: 0.5471 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7701 - val_loss: 0.5533 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4660 - accuracy: 0.7778 - val_loss: 0.5543 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4561 - accuracy: 0.7850 - val_loss: 0.5612 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 11/400
251/257 [============================>.] - ETA: 0s - loss: 0.4431 - accuracy: 0.7938
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4436 - accuracy: 0.7935 - val_loss: 0.5567 - val_accuracy: 0.7227 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42723886404344646
Confusion Matrix :
 [[2875 1172]
 [1146 2901]]
Accuracy on test set:    0.7136150234741784
Sensitivity:    0.7168272794662713 	 Specificity:    0.7104027674820855
Precision  : 0.7122514117358213
Area Under Curve:    0.7136150234741783
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5872 - accuracy: 0.6868 - val_loss: 0.5568 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7209 - val_loss: 0.5484 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7312 - val_loss: 0.5509 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7403 - val_loss: 0.5493 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7463 - val_loss: 0.5480 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7553 - val_loss: 0.5509 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4891 - accuracy: 0.7622 - val_loss: 0.5526 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7689 - val_loss: 0.5574 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4690 - accuracy: 0.7769 - val_loss: 0.5576 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4573 - accuracy: 0.7842 - val_loss: 0.5670 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4449 - accuracy: 0.7930 - val_loss: 0.5694 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4311 - accuracy: 0.7994 - val_loss: 0.5750 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4182 - accuracy: 0.8076 - val_loss: 0.5761 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 14/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4067 - accuracy: 0.8154
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4069 - accuracy: 0.8153 - val_loss: 0.5917 - val_accuracy: 0.7146 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44573128067618806
Confusion Matrix :
 [[2988 1059]
 [1185 2862]]
Accuracy on test set:    0.7227575982209044
Sensitivity:    0.7071905114899926 	 Specificity:    0.7383246849518161
Precision  : 0.7299158377964805
Area Under Curve:    0.7227575982209044
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5976 - accuracy: 0.6761 - val_loss: 0.5581 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5531 - accuracy: 0.7189 - val_loss: 0.5521 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5361 - accuracy: 0.7291 - val_loss: 0.5495 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5253 - accuracy: 0.7368 - val_loss: 0.5553 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5138 - accuracy: 0.7463 - val_loss: 0.5505 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7534 - val_loss: 0.5572 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7613 - val_loss: 0.5601 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4792 - accuracy: 0.7704
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4792 - accuracy: 0.7704 - val_loss: 0.5620 - val_accuracy: 0.7172 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4900479899069532
Confusion Matrix :
 [[3145  902]
 [1166 2881]]
Accuracy on test set:    0.7445021003212255
Sensitivity:    0.7118853471707438 	 Specificity:    0.7771188534717074
Precision  : 0.7615648955855141
Area Under Curve:    0.7445021003212257
(8094, 2560) (8094,)
Mean MCC = 0.4302 + 0.0221 and Mean AUC = 0.7145 + 0.0113
Mean Sensitivity = 0.7345 + 0.0244 and Mean Specificity = 0.6945 + 0.0414 and Mean Accuracy = 0.7145 + 0.0113
Mean Precision = 0.7075 + 0.0229





Seed   : 240428
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5858 - accuracy: 0.6866 - val_loss: 0.5632 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7236 - val_loss: 0.5544 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7331 - val_loss: 0.5619 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7425 - val_loss: 0.5486 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5054 - accuracy: 0.7492 - val_loss: 0.5646 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7577 - val_loss: 0.5511 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7653 - val_loss: 0.5552 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4729 - accuracy: 0.7739 - val_loss: 0.5598 - val_accuracy: 0.7193 - lr: 0.0010

Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4607 - accuracy: 0.7793
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4609 - accuracy: 0.7790 - val_loss: 0.5596 - val_accuracy: 0.7156 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4050610798799395
Confusion Matrix :
 [[2914 1134]
 [1275 2772]]
Accuracy on test set:    0.7024088943792465
Sensitivity:    0.6849518161601186 	 Specificity:    0.7198616600790514
Precision  : 0.7096774193548387
Area Under Curve:    0.702406738119585
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5886 - accuracy: 0.6838 - val_loss: 0.5586 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7224 - val_loss: 0.5547 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7330 - val_loss: 0.5481 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7389 - val_loss: 0.5472 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7466 - val_loss: 0.5497 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7546 - val_loss: 0.5650 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7621 - val_loss: 0.5508 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7707 - val_loss: 0.5552 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4646 - accuracy: 0.7791 - val_loss: 0.5600 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4523 - accuracy: 0.7867 - val_loss: 0.5592 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4400 - accuracy: 0.7952 - val_loss: 0.5693 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4272 - accuracy: 0.8022 - val_loss: 0.5733 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 13/400
253/257 [============================>.] - ETA: 0s - loss: 0.4139 - accuracy: 0.8090
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4137 - accuracy: 0.8090 - val_loss: 0.5856 - val_accuracy: 0.7119 - lr: 0.0010
253/253 [==============================] - 0s 966us/step
Independent Testing Matthews Correlation:  0.4184436413370482
Confusion Matrix :
 [[2634 1414]
 [ 951 3096]]
Accuracy on test set:    0.7078443483631871
Sensitivity:    0.765011119347665 	 Specificity:    0.650691699604743
Precision  : 0.6864745011086475
Area Under Curve:    0.7078514094762041
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5844 - accuracy: 0.6874 - val_loss: 0.5549 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7232 - val_loss: 0.5427 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7334 - val_loss: 0.5411 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7410 - val_loss: 0.5377 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5113 - accuracy: 0.7469 - val_loss: 0.5463 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5008 - accuracy: 0.7543 - val_loss: 0.5392 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7608 - val_loss: 0.5463 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4806 - accuracy: 0.7690 - val_loss: 0.5454 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7747 - val_loss: 0.5484 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4595 - accuracy: 0.7834 - val_loss: 0.5491 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4482 - accuracy: 0.7921 - val_loss: 0.5547 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4374 - accuracy: 0.7978 - val_loss: 0.5565 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4245 - accuracy: 0.8045 - val_loss: 0.5653 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 14/400
252/257 [============================>.] - ETA: 0s - loss: 0.4157 - accuracy: 0.8084
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4156 - accuracy: 0.8083 - val_loss: 0.5712 - val_accuracy: 0.7219 - lr: 0.0010
253/253 [==============================] - 0s 799us/step
Independent Testing Matthews Correlation:  0.3903667538444441
Confusion Matrix :
 [[2864 1183]
 [1285 2763]]
Accuracy on test set:    0.6951204447189623
Sensitivity:    0.6825592885375494 	 Specificity:    0.7076847047195454
Precision  : 0.700202736948809
Area Under Curve:    0.6951219966285473
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5886 - accuracy: 0.6825 - val_loss: 0.5507 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7218 - val_loss: 0.5393 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7323 - val_loss: 0.5421 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7394 - val_loss: 0.5371 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7479 - val_loss: 0.5371 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7545 - val_loss: 0.5415 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4897 - accuracy: 0.7614 - val_loss: 0.5393 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4783 - accuracy: 0.7700 - val_loss: 0.5396 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4665 - accuracy: 0.7786
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4669 - accuracy: 0.7782 - val_loss: 0.5457 - val_accuracy: 0.7237 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4272006483816889
Confusion Matrix :
 [[2722 1325]
 [ 999 3049]]
Accuracy on test set:    0.7129092032118591
Sensitivity:    0.7532114624505929 	 Specificity:    0.6725969854212998
Precision  : 0.6970736168267032
Area Under Curve:    0.7129042239359463
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5890 - accuracy: 0.6838 - val_loss: 0.5571 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7215 - val_loss: 0.5516 - val_accuracy: 0.7086 - lr: 0.0010

Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7335 - val_loss: 0.5502 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7397 - val_loss: 0.5538 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7490 - val_loss: 0.5512 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4954 - accuracy: 0.7576 - val_loss: 0.5606 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7655 - val_loss: 0.5616 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4722 - accuracy: 0.7729
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7728 - val_loss: 0.5673 - val_accuracy: 0.7116 - lr: 0.0010
253/253 [==============================] - 0s 833us/step
Independent Testing Matthews Correlation:  0.4258919926638056
Confusion Matrix :
 [[2606 1441]
 [ 898 3149]]
Accuracy on test set:    0.7110205090190265
Sensitivity:    0.778107239930813 	 Specificity:    0.64393377810724
Precision  : 0.6860566448801743
Area Under Curve:    0.7110205090190265
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5857 - accuracy: 0.6842 - val_loss: 0.5599 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7236 - val_loss: 0.5529 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7339 - val_loss: 0.5474 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7421 - val_loss: 0.5479 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7504 - val_loss: 0.5473 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7585 - val_loss: 0.5525 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7676 - val_loss: 0.5522 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4690 - accuracy: 0.7766
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4690 - accuracy: 0.7766 - val_loss: 0.5579 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 967us/step
Independent Testing Matthews Correlation:  0.43097347706850564
Confusion Matrix :
 [[2754 1293]
 [1014 3033]]
Accuracy on test set:    0.7149740548554485
Sensitivity:    0.7494440326167532 	 Specificity:    0.6805040770941438
Precision  : 0.7011095700416089
Area Under Curve:    0.7149740548554485
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6845 - val_loss: 0.5535 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7236 - val_loss: 0.5460 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7322 - val_loss: 0.5470 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5168 - accuracy: 0.7431 - val_loss: 0.5429 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7505 - val_loss: 0.5449 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7563 - val_loss: 0.5452 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4858 - accuracy: 0.7646 - val_loss: 0.5481 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4750 - accuracy: 0.7705 - val_loss: 0.5534 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4613 - accuracy: 0.7809 - val_loss: 0.5584 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4489 - accuracy: 0.7867 - val_loss: 0.5609 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4359 - accuracy: 0.7984 - val_loss: 0.5640 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - ETA: 0s - loss: 0.4237 - accuracy: 0.8040
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4237 - accuracy: 0.8040 - val_loss: 0.5908 - val_accuracy: 0.7073 - lr: 0.0010
253/253 [==============================] - 1s 4ms/step
Independent Testing Matthews Correlation:  0.42048824273080826
Confusion Matrix :
 [[2483 1564]
 [ 811 3236]]
Accuracy on test set:    0.7065727699530516
Sensitivity:    0.7996046454163578 	 Specificity:    0.6135408944897455
Precision  : 0.6741666666666667
Area Under Curve:    0.7065727699530516
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5843 - accuracy: 0.6860 - val_loss: 0.5509 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7232 - val_loss: 0.5436 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7339 - val_loss: 0.5430 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5142 - accuracy: 0.7443 - val_loss: 0.5430 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5023 - accuracy: 0.7532 - val_loss: 0.5433 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4893 - accuracy: 0.7609 - val_loss: 0.5475 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4777 - accuracy: 0.7699 - val_loss: 0.5450 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4634 - accuracy: 0.7792 - val_loss: 0.5524 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4508 - accuracy: 0.7887
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4515 - accuracy: 0.7882 - val_loss: 0.5521 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 829us/step
Independent Testing Matthews Correlation:  0.4469601515500009
Confusion Matrix :
 [[3040 1007]
 [1234 2813]]
Accuracy on test set:    0.7231282431430689
Sensitivity:    0.69508277736595 	 Specificity:    0.7511737089201878
Precision  : 0.7363874345549738
Area Under Curve:    0.7231282431430689
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5896 - accuracy: 0.6839 - val_loss: 0.5518 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5486 - accuracy: 0.7193 - val_loss: 0.5475 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7303 - val_loss: 0.5438 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.7381 - val_loss: 0.5471 - val_accuracy: 0.7167 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5110 - accuracy: 0.7462 - val_loss: 0.5473 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 6/400
255/257 [============================>.] - ETA: 0s - loss: 0.4996 - accuracy: 0.7557
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7556 - val_loss: 0.5498 - val_accuracy: 0.7146 - lr: 0.0010
253/253 [==============================] - 0s 781us/step
Independent Testing Matthews Correlation:  0.4574651196143934
Confusion Matrix :
 [[3245  802]
 [1415 2632]]
Accuracy on test set:    0.7260934025203855
Sensitivity:    0.6503582900914258 	 Specificity:    0.8018285149493452
Precision  : 0.7664531158998252
Area Under Curve:    0.7260934025203855
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5930 - accuracy: 0.6827 - val_loss: 0.5554 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5517 - accuracy: 0.7167 - val_loss: 0.5477 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5369 - accuracy: 0.7313 - val_loss: 0.5462 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5249 - accuracy: 0.7370 - val_loss: 0.5472 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5139 - accuracy: 0.7453 - val_loss: 0.5493 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5022 - accuracy: 0.7541 - val_loss: 0.5547 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - ETA: 0s - loss: 0.4896 - accuracy: 0.7634
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4896 - accuracy: 0.7634 - val_loss: 0.5525 - val_accuracy: 0.7127 - lr: 0.0010
253/253 [==============================] - 0s 986us/step
Independent Testing Matthews Correlation:  0.48324931817184014
Confusion Matrix :
 [[3177  870]
 [1229 2818]]
Accuracy on test set:    0.7406721027921918
Sensitivity:    0.696318260439832 	 Specificity:    0.7850259451445515
Precision  : 0.7640997830802603
Area Under Curve:    0.7406721027921919
(8094, 2560) (8094,)
Mean MCC = 0.4306 + 0.0251 and Mean AUC = 0.7141 + 0.0124
Mean Sensitivity = 0.7255 + 0.0470 and Mean Specificity = 0.7027 + 0.0590 and Mean Accuracy = 0.7141 + 0.0124
Mean Precision = 0.7122 + 0.0308





Seed   : 737198
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5811 - accuracy: 0.6880 - val_loss: 0.5628 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5409 - accuracy: 0.7245 - val_loss: 0.5566 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5249 - accuracy: 0.7342 - val_loss: 0.5585 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.7458 - val_loss: 0.5560 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5015 - accuracy: 0.7519 - val_loss: 0.5607 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7599 - val_loss: 0.5607 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7688 - val_loss: 0.5667 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4668 - accuracy: 0.7789 - val_loss: 0.5695 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4546 - accuracy: 0.7858 - val_loss: 0.5682 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4399 - accuracy: 0.7960
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4403 - accuracy: 0.7958 - val_loss: 0.5822 - val_accuracy: 0.7045 - lr: 0.0010
253/253 [==============================] - 0s 746us/step
Independent Testing Matthews Correlation:  0.3905585678397446
Confusion Matrix :
 [[2896 1152]
 [1316 2731]]
Accuracy on test set:    0.6951204447189623
Sensitivity:    0.6748208549542871 	 Specificity:    0.7154150197628458
Precision  : 0.7033221735771311
Area Under Curve:    0.6951179373585665
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5873 - accuracy: 0.6858 - val_loss: 0.5656 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7245 - val_loss: 0.5544 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7350 - val_loss: 0.5518 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7447 - val_loss: 0.5558 - val_accuracy: 0.7035 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7511 - val_loss: 0.5548 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7571 - val_loss: 0.5572 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7653 - val_loss: 0.5597 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4723 - accuracy: 0.7742
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4725 - accuracy: 0.7739 - val_loss: 0.5606 - val_accuracy: 0.7062 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42324496105515863
Confusion Matrix :
 [[2828 1220]
 [1115 2932]]
Accuracy on test set:    0.711550339715874
Sensitivity:    0.724487274524339 	 Specificity:    0.6986166007905138
Precision  : 0.7061657032755299
Area Under Curve:    0.7115519376574265
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5857 - accuracy: 0.6862 - val_loss: 0.5718 - val_accuracy: 0.6992 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5422 - accuracy: 0.7238 - val_loss: 0.5449 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7341 - val_loss: 0.5420 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7431 - val_loss: 0.5416 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7511 - val_loss: 0.5444 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7581 - val_loss: 0.5449 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7656 - val_loss: 0.5489 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4702 - accuracy: 0.7733 - val_loss: 0.5536 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4579 - accuracy: 0.7842 - val_loss: 0.5559 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4470 - accuracy: 0.7894 - val_loss: 0.5570 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4347 - accuracy: 0.7973 - val_loss: 0.5589 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 12/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4220 - accuracy: 0.8053
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4227 - accuracy: 0.8049 - val_loss: 0.5772 - val_accuracy: 0.7137 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4219195066547772
Confusion Matrix :
 [[2629 1418]
 [ 934 3114]]
Accuracy on test set:    0.7094502779493514
Sensitivity:    0.7692687747035574 	 Specificity:    0.6496170002470966
Precision  : 0.6871138570167696
Area Under Curve:    0.709442887475327
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5857 - accuracy: 0.6848 - val_loss: 0.5539 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7223 - val_loss: 0.5449 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7339 - val_loss: 0.5442 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7423 - val_loss: 0.5425 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7484 - val_loss: 0.5421 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7588 - val_loss: 0.5476 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7649 - val_loss: 0.5431 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7761 - val_loss: 0.5494 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4600 - accuracy: 0.7811 - val_loss: 0.5609 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4462 - accuracy: 0.7887 - val_loss: 0.5576 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4367 - accuracy: 0.7964 - val_loss: 0.5650 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 12/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4219 - accuracy: 0.8040
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4225 - accuracy: 0.8038 - val_loss: 0.5734 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 845us/step
Independent Testing Matthews Correlation:  0.3998406838609209
Confusion Matrix :
 [[2928 1119]
 [1312 2736]]
Accuracy on test set:    0.6996911673872761
Sensitivity:    0.6758893280632411 	 Specificity:    0.7234988880652335
Precision  : 0.709727626459144
Area Under Curve:    0.6996941080642374
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5873 - accuracy: 0.6840 - val_loss: 0.5534 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7240 - val_loss: 0.5483 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7329 - val_loss: 0.5489 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7399 - val_loss: 0.5433 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7497 - val_loss: 0.5430 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7568 - val_loss: 0.5411 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7642 - val_loss: 0.5582 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7750 - val_loss: 0.5474 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4581 - accuracy: 0.7827 - val_loss: 0.5525 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4454 - accuracy: 0.7900 - val_loss: 0.5488 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4293 - accuracy: 0.8011 - val_loss: 0.5561 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4175 - accuracy: 0.8076 - val_loss: 0.5763 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4038 - accuracy: 0.8154 - val_loss: 0.5663 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 14/400
249/257 [============================>.] - ETA: 0s - loss: 0.3874 - accuracy: 0.8253
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3883 - accuracy: 0.8247 - val_loss: 0.5852 - val_accuracy: 0.7156 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4110136688262725
Confusion Matrix :
 [[2690 1357]
 [1032 3015]]
Accuracy on test set:    0.704843093649617
Sensitivity:    0.7449962935507783 	 Specificity:    0.6646898937484557
Precision  : 0.689615736505032
Area Under Curve:    0.704843093649617
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5884 - accuracy: 0.6829 - val_loss: 0.5497 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7191 - val_loss: 0.5455 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7320 - val_loss: 0.5398 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7403 - val_loss: 0.5410 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5093 - accuracy: 0.7482 - val_loss: 0.5405 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7548 - val_loss: 0.5418 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.7641 - val_loss: 0.5483 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4702 - accuracy: 0.7740
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7737 - val_loss: 0.5501 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 945us/step
Independent Testing Matthews Correlation:  0.4244081156011056
Confusion Matrix :
 [[2676 1371]
 [ 967 3080]]
Accuracy on test set:    0.7111440573264146
Sensitivity:    0.7610575735112429 	 Specificity:    0.6612305411415864
Precision  : 0.6919793304875309
Area Under Curve:    0.7111440573264147
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5873 - accuracy: 0.6835 - val_loss: 0.5515 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7218 - val_loss: 0.5403 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7312 - val_loss: 0.5414 - val_accuracy: 0.7261 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7390 - val_loss: 0.5392 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.7496 - val_loss: 0.5389 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7567 - val_loss: 0.5433 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4862 - accuracy: 0.7638
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7645 - val_loss: 0.5509 - val_accuracy: 0.7209 - lr: 0.0010
253/253 [==============================] - 0s 978us/step
Independent Testing Matthews Correlation:  0.4277495221714602
Confusion Matrix :
 [[2911 1136]
 [1180 2867]]
Accuracy on test set:    0.7138621200889548
Sensitivity:    0.7084259945638745 	 Specificity:    0.7192982456140351
Precision  : 0.7162128403697227
Area Under Curve:    0.7138621200889548
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5883 - accuracy: 0.6822 - val_loss: 0.5681 - val_accuracy: 0.7006 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.7197 - val_loss: 0.5436 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5342 - accuracy: 0.7303 - val_loss: 0.5414 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7396 - val_loss: 0.5414 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5133 - accuracy: 0.7466 - val_loss: 0.5448 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5027 - accuracy: 0.7517 - val_loss: 0.5444 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4918 - accuracy: 0.7611
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7613 - val_loss: 0.5457 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44086721387923733
Confusion Matrix :
 [[2886 1161]
 [1102 2945]]
Accuracy on test set:    0.7204101803805288
Sensitivity:    0.7276995305164319 	 Specificity:    0.7131208302446257
Precision  : 0.7172430589381393
Area Under Curve:    0.7204101803805288
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5947 - accuracy: 0.6772 - val_loss: 0.5562 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5504 - accuracy: 0.7210 - val_loss: 0.5501 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5369 - accuracy: 0.7291 - val_loss: 0.5476 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5257 - accuracy: 0.7367 - val_loss: 0.5482 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7439 - val_loss: 0.5541 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7493 - val_loss: 0.5500 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7570 - val_loss: 0.5533 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7668 - val_loss: 0.5573 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4728 - accuracy: 0.7736 - val_loss: 0.5608 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4604 - accuracy: 0.7826 - val_loss: 0.5617 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4474 - accuracy: 0.7916 - val_loss: 0.5751 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4325 - accuracy: 0.8003 - val_loss: 0.5733 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4228 - accuracy: 0.8049 - val_loss: 0.5754 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 14/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4085 - accuracy: 0.8147
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4085 - accuracy: 0.8148 - val_loss: 0.5881 - val_accuracy: 0.7100 - lr: 0.0010
253/253 [==============================] - 0s 763us/step
Independent Testing Matthews Correlation:  0.44980594253020983
Confusion Matrix :
 [[2974 1073]
 [1154 2893]]
Accuracy on test set:    0.7248579194465036
Sensitivity:    0.7148505065480603 	 Specificity:    0.7348653323449469
Precision  : 0.7294503277861826
Area Under Curve:    0.7248579194465035
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5929 - accuracy: 0.6792 - val_loss: 0.5609 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5512 - accuracy: 0.7180 - val_loss: 0.5497 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5337 - accuracy: 0.7316 - val_loss: 0.5507 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.7393 - val_loss: 0.5490 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7484 - val_loss: 0.5547 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.7556 - val_loss: 0.5522 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4892 - accuracy: 0.7637 - val_loss: 0.5541 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.7719 - val_loss: 0.5567 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4651 - accuracy: 0.7793 - val_loss: 0.5604 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4525 - accuracy: 0.7863 - val_loss: 0.5694 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4403 - accuracy: 0.7953 - val_loss: 0.5697 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4282 - accuracy: 0.8031 - val_loss: 0.5841 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - ETA: 0s - loss: 0.4143 - accuracy: 0.8104
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4143 - accuracy: 0.8104 - val_loss: 0.5933 - val_accuracy: 0.7145 - lr: 0.0010
253/253 [==============================] - 0s 923us/step
Independent Testing Matthews Correlation:  0.47890553655786267
Confusion Matrix :
 [[3016 1031]
 [1078 2969]]
Accuracy on test set:    0.7394366197183099
Sensitivity:    0.733629849271065 	 Specificity:    0.7452433901655547
Precision  : 0.74225
Area Under Curve:    0.7394366197183099
(8094, 2560) (8094,)
Mean MCC = 0.4268 + 0.0240 and Mean AUC = 0.7130 + 0.0122
Mean Sensitivity = 0.7235 + 0.0300 and Mean Specificity = 0.7026 + 0.0313 and Mean Accuracy = 0.7130 + 0.0122
Mean Precision = 0.7093 + 0.0168





Seed   : 761980

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5868 - accuracy: 0.6819 - val_loss: 0.5609 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7240 - val_loss: 0.5510 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5265 - accuracy: 0.7363 - val_loss: 0.5463 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7444 - val_loss: 0.5483 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5021 - accuracy: 0.7513 - val_loss: 0.5461 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.7606 - val_loss: 0.5509 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4769 - accuracy: 0.7712 - val_loss: 0.5521 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4644 - accuracy: 0.7786
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4648 - accuracy: 0.7785 - val_loss: 0.5530 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42031717291758086
Confusion Matrix :
 [[2783 1265]
 [1083 2964]]
Accuracy on test set:    0.7099444101297097
Sensitivity:    0.7323943661971831 	 Specificity:    0.6875
Precision  : 0.7008749113265548
Area Under Curve:    0.7099471830985915
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5895 - accuracy: 0.6838 - val_loss: 0.5565 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7249 - val_loss: 0.5486 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7351 - val_loss: 0.5447 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7422 - val_loss: 0.5471 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7495 - val_loss: 0.5447 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7589 - val_loss: 0.5469 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.7654 - val_loss: 0.5432 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7734 - val_loss: 0.5509 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4625 - accuracy: 0.7813 - val_loss: 0.5572 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4519 - accuracy: 0.7893 - val_loss: 0.5524 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4377 - accuracy: 0.7980 - val_loss: 0.5587 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 12/400
256/257 [============================>.] - ETA: 0s - loss: 0.4250 - accuracy: 0.8067
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4251 - accuracy: 0.8067 - val_loss: 0.5710 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 785us/step
Independent Testing Matthews Correlation:  0.41452092950473335
Confusion Matrix :
 [[2717 1331]
 [1043 3004]]
Accuracy on test set:    0.7067325509573811
Sensitivity:    0.7422782307882382 	 Specificity:    0.6711956521739131
Precision  : 0.692964244521338
Area Under Curve:    0.7067369414810756
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5900 - accuracy: 0.6835 - val_loss: 0.5527 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7218 - val_loss: 0.5385 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7327 - val_loss: 0.5345 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7404 - val_loss: 0.5332 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7495 - val_loss: 0.5347 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7599 - val_loss: 0.5417 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7656 - val_loss: 0.5420 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4714 - accuracy: 0.7737 - val_loss: 0.5494 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4575 - accuracy: 0.7835 - val_loss: 0.5464 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4436 - accuracy: 0.7937
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4441 - accuracy: 0.7933 - val_loss: 0.5541 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4125460126460835
Confusion Matrix :
 [[3030 1017]
 [1367 2681]]
Accuracy on test set:    0.7054972205064854
Sensitivity:    0.662302371541502 	 Specificity:    0.748702742772424
Precision  : 0.724986479177934
Area Under Curve:    0.705502557156963
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5843 - accuracy: 0.6861 - val_loss: 0.5459 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7229 - val_loss: 0.5320 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7350 - val_loss: 0.5297 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7442 - val_loss: 0.5288 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7497 - val_loss: 0.5297 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.7600 - val_loss: 0.5332 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4788 - accuracy: 0.7695 - val_loss: 0.5362 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4650 - accuracy: 0.7776
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4657 - accuracy: 0.7772 - val_loss: 0.5397 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4103229442886315
Confusion Matrix :
 [[3026 1021]
 [1372 2676]]
Accuracy on test set:    0.7043854231006794
Sensitivity:    0.6610671936758893 	 Specificity:    0.7477143563133185
Precision  : 0.7238301325398973
Area Under Curve:    0.7043907749946039
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5918 - accuracy: 0.6802 - val_loss: 0.5497 - val_accuracy: 0.7209 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5477 - accuracy: 0.7205 - val_loss: 0.5368 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7315 - val_loss: 0.5352 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5210 - accuracy: 0.7395 - val_loss: 0.5358 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5124 - accuracy: 0.7461 - val_loss: 0.5346 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.7539 - val_loss: 0.5385 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4893 - accuracy: 0.7619 - val_loss: 0.5409 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4804 - accuracy: 0.7677
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4803 - accuracy: 0.7677 - val_loss: 0.5463 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 921us/step
Independent Testing Matthews Correlation:  0.4248620263903279
Confusion Matrix :
 [[2754 1293]
 [1038 3009]]
Accuracy on test set:    0.712008895478132
Sensitivity:    0.7435137138621201 	 Specificity:    0.6805040770941438
Precision  : 0.699442119944212
Area Under Curve:    0.7120088954781318
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5884 - accuracy: 0.6841 - val_loss: 0.5468 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7234 - val_loss: 0.5395 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7320 - val_loss: 0.5365 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7408 - val_loss: 0.5385 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7486 - val_loss: 0.5381 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.7555 - val_loss: 0.5370 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.7636 - val_loss: 0.5419 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7693 - val_loss: 0.5434 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4682 - accuracy: 0.7772 - val_loss: 0.5470 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4578 - accuracy: 0.7841 - val_loss: 0.5505 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4459 - accuracy: 0.7918 - val_loss: 0.5558 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 12/400
255/257 [============================>.] - ETA: 0s - loss: 0.4352 - accuracy: 0.7965
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4352 - accuracy: 0.7966 - val_loss: 0.5600 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 794us/step
Independent Testing Matthews Correlation:  0.42402246402378324
Confusion Matrix :
 [[2872 1175]
 [1156 2891]]
Accuracy on test set:    0.712008895478132
Sensitivity:    0.7143563133185076 	 Specificity:    0.7096614776377563
Precision  : 0.7110181997048697
Area Under Curve:    0.7120088954781318
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5871 - accuracy: 0.6843 - val_loss: 0.5453 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7213 - val_loss: 0.5377 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7307 - val_loss: 0.5354 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5210 - accuracy: 0.7401 - val_loss: 0.5357 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7458 - val_loss: 0.5355 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7546 - val_loss: 0.5362 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.7635 - val_loss: 0.5439 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7721 - val_loss: 0.5437 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4625 - accuracy: 0.7807 - val_loss: 0.5495 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4493 - accuracy: 0.7885 - val_loss: 0.5535 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4359 - accuracy: 0.7971 - val_loss: 0.5472 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4210 - accuracy: 0.8076 - val_loss: 0.5599 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 13/400
252/257 [============================>.] - ETA: 0s - loss: 0.4091 - accuracy: 0.8135
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4095 - accuracy: 0.8133 - val_loss: 0.5595 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 859us/step
Independent Testing Matthews Correlation:  0.4178465496204177
Confusion Matrix :
 [[2858 1189]
 [1167 2880]]
Accuracy on test set:    0.7089201877934272
Sensitivity:    0.7116382505559674 	 Specificity:    0.7062021250308871
Precision  : 0.7077906119439665
Area Under Curve:    0.7089201877934272
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5882 - accuracy: 0.6825 - val_loss: 0.5454 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7234 - val_loss: 0.5366 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7343 - val_loss: 0.5380 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7422 - val_loss: 0.5376 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7504 - val_loss: 0.5428 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.7597 - val_loss: 0.5425 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4784 - accuracy: 0.7691 - val_loss: 0.5420 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7790 - val_loss: 0.5473 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4506 - accuracy: 0.7881 - val_loss: 0.5569 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4371 - accuracy: 0.7951 - val_loss: 0.5615 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4231 - accuracy: 0.8041
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4232 - accuracy: 0.8038 - val_loss: 0.5684 - val_accuracy: 0.7219 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43341268881511924
Confusion Matrix :
 [[2745 1302]
 [ 996 3051]]
Accuracy on test set:    0.7160859896219421
Sensitivity:    0.7538917716827279 	 Specificity:    0.6782802075611564
Precision  : 0.7008959338387319
Area Under Curve:    0.7160859896219421
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5918 - accuracy: 0.6803 - val_loss: 0.5517 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5498 - accuracy: 0.7211 - val_loss: 0.5442 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5346 - accuracy: 0.7295 - val_loss: 0.5412 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5241 - accuracy: 0.7380 - val_loss: 0.5401 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5131 - accuracy: 0.7451 - val_loss: 0.5419 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7509 - val_loss: 0.5436 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4923 - accuracy: 0.7599
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7601 - val_loss: 0.5500 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47262720865428537
Confusion Matrix :
 [[2807 1240]
 [ 901 3146]]
Accuracy on test set:    0.7354830738818878
Sensitivity:    0.7773659500864838 	 Specificity:    0.6936001976772919
Precision  : 0.717282261741906
Area Under Curve:    0.7354830738818878
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5975 - accuracy: 0.6772 - val_loss: 0.5652 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5529 - accuracy: 0.7172 - val_loss: 0.5496 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5385 - accuracy: 0.7282 - val_loss: 0.5484 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7348 - val_loss: 0.5473 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7418 - val_loss: 0.5455 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5103 - accuracy: 0.7491 - val_loss: 0.5473 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4983 - accuracy: 0.7566
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.7560 - val_loss: 0.5477 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 961us/step
Independent Testing Matthews Correlation:  0.4869034385006573
Confusion Matrix :
 [[3054  993]
 [1084 2963]]
Accuracy on test set:    0.7433901655547319
Sensitivity:    0.7321472695824067 	 Specificity:    0.7546330615270571
Precision  : 0.7489888776541962
Area Under Curve:    0.7433901655547319
(8094, 2560) (8094,)
Mean MCC = 0.4317 + 0.0250 and Mean AUC = 0.7154 + 0.0126
Mean Sensitivity = 0.7231 + 0.0355 and Mean Specificity = 0.7078 + 0.0301 and Mean Accuracy = 0.7154 + 0.0126
Mean Precision = 0.7128 + 0.0158





Seed   : 482121
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5866 - accuracy: 0.6861 - val_loss: 0.5569 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5420 - accuracy: 0.7248 - val_loss: 0.5546 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7344 - val_loss: 0.5493 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7435 - val_loss: 0.5542 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7504 - val_loss: 0.5504 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4970 - accuracy: 0.7553 - val_loss: 0.5503 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7656 - val_loss: 0.5538 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4727 - accuracy: 0.7726 - val_loss: 0.5622 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4622 - accuracy: 0.7789 - val_loss: 0.5640 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4502 - accuracy: 0.7886 - val_loss: 0.5663 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4381 - accuracy: 0.7963 - val_loss: 0.5686 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4270 - accuracy: 0.8026 - val_loss: 0.5806 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 13/400
254/257 [============================>.] - ETA: 0s - loss: 0.4141 - accuracy: 0.8107
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4141 - accuracy: 0.8107 - val_loss: 0.5878 - val_accuracy: 0.7091 - lr: 0.0010
253/253 [==============================] - 0s 831us/step
Independent Testing Matthews Correlation:  0.4058953286848479
Confusion Matrix :
 [[2680 1368]
 [1042 3005]]
Accuracy on test set:    0.7022853613341569
Sensitivity:    0.7425253274030146 	 Specificity:    0.6620553359683794
Precision  : 0.6871712782986508
Area Under Curve:    0.702290331685697
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5875 - accuracy: 0.6825 - val_loss: 0.5567 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7254 - val_loss: 0.5506 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5263 - accuracy: 0.7359 - val_loss: 0.5485 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5142 - accuracy: 0.7432 - val_loss: 0.5459 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7524 - val_loss: 0.5481 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.7599 - val_loss: 0.5490 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7666 - val_loss: 0.5681 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4685 - accuracy: 0.7768 - val_loss: 0.5533 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4526 - accuracy: 0.7855 - val_loss: 0.5562 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 10/400

257/257 [==============================] - 1s 4ms/step - loss: 0.4408 - accuracy: 0.7930 - val_loss: 0.5640 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4301 - accuracy: 0.8002 - val_loss: 0.5665 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4162 - accuracy: 0.8093 - val_loss: 0.5883 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 13/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4022 - accuracy: 0.8176
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4030 - accuracy: 0.8172 - val_loss: 0.5791 - val_accuracy: 0.7076 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40838694865498504
Confusion Matrix :
 [[2935 1113]
 [1283 2764]]
Accuracy on test set:    0.7040148239654107
Sensitivity:    0.6829750432419076 	 Specificity:    0.7250494071146245
Precision  : 0.7129223626515347
Area Under Curve:    0.7040122251782661
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5902 - accuracy: 0.6808 - val_loss: 0.5462 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7238 - val_loss: 0.5363 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7328 - val_loss: 0.5415 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5209 - accuracy: 0.7378 - val_loss: 0.5332 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7482 - val_loss: 0.5338 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4991 - accuracy: 0.7559 - val_loss: 0.5359 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7624 - val_loss: 0.5446 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4767 - accuracy: 0.7703 - val_loss: 0.5428 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4639 - accuracy: 0.7795
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4639 - accuracy: 0.7794 - val_loss: 0.5433 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 820us/step
Independent Testing Matthews Correlation:  0.42236427614526884
Confusion Matrix :
 [[2868 1179]
 [1159 2889]]
Accuracy on test set:    0.7111797405806053
Sensitivity:    0.7136857707509882 	 Specificity:    0.7086730911786508
Precision  : 0.7101769911504425
Area Under Curve:    0.7111794309648196
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5876 - accuracy: 0.6857 - val_loss: 0.5404 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7229 - val_loss: 0.5366 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7324 - val_loss: 0.5289 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7414 - val_loss: 0.5291 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7468 - val_loss: 0.5293 - val_accuracy: 0.7347 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7561 - val_loss: 0.5321 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7654 - val_loss: 0.5372 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.7720 - val_loss: 0.5318 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4652 - accuracy: 0.7797 - val_loss: 0.5388 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4525 - accuracy: 0.7870
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4525 - accuracy: 0.7870 - val_loss: 0.5416 - val_accuracy: 0.7290 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41634458993969337
Confusion Matrix :
 [[2697 1350]
 [1018 3030]]
Accuracy on test set:    0.7074737492279185
Sensitivity:    0.7485177865612648 	 Specificity:    0.6664195700518903
Precision  : 0.6917808219178082
Area Under Curve:    0.7074686783065774
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5871 - accuracy: 0.6847 - val_loss: 0.5488 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7238 - val_loss: 0.5412 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7326 - val_loss: 0.5429 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7400 - val_loss: 0.5398 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7491 - val_loss: 0.5437 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7546 - val_loss: 0.5457 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.7616 - val_loss: 0.5421 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4759 - accuracy: 0.7703 - val_loss: 0.5501 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4646 - accuracy: 0.7792 - val_loss: 0.5509 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4530 - accuracy: 0.7866 - val_loss: 0.5563 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4420 - accuracy: 0.7934 - val_loss: 0.5570 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - ETA: 0s - loss: 0.4302 - accuracy: 0.8010
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4302 - accuracy: 0.8010 - val_loss: 0.5690 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 847us/step
Independent Testing Matthews Correlation:  0.4074321330901421
Confusion Matrix :
 [[2966 1081]
 [1320 2727]]
Accuracy on test set:    0.7033605139609588
Sensitivity:    0.6738324684951816 	 Specificity:    0.7328885594267358
Precision  : 0.7161239495798319
Area Under Curve:    0.7033605139609588
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5887 - accuracy: 0.6826 - val_loss: 0.5480 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7215 - val_loss: 0.5446 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7337 - val_loss: 0.5502 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7398 - val_loss: 0.5447 - val_accuracy: 0.7200 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7477 - val_loss: 0.5463 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.7547 - val_loss: 0.5481 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7615 - val_loss: 0.5500 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.7696 - val_loss: 0.5557 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4686 - accuracy: 0.7770
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4686 - accuracy: 0.7770 - val_loss: 0.5525 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4312165048816966
Confusion Matrix :
 [[2921 1126]
 [1176 2871]]
Accuracy on test set:    0.7155917963923895
Sensitivity:    0.7094143810229799 	 Specificity:    0.7217692117617989
Precision  : 0.718288716537403
Area Under Curve:    0.7155917963923895
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5904 - accuracy: 0.6830 - val_loss: 0.5471 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7215 - val_loss: 0.5450 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7328 - val_loss: 0.5421 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7398 - val_loss: 0.5458 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7473 - val_loss: 0.5448 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7553 - val_loss: 0.5500 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7646 - val_loss: 0.5478 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4762 - accuracy: 0.7722
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4764 - accuracy: 0.7720 - val_loss: 0.5501 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 921us/step
Independent Testing Matthews Correlation:  0.424746750094644
Confusion Matrix :
 [[2763 1284]
 [1047 3000]]
Accuracy on test set:    0.712008895478132
Sensitivity:    0.7412898443291327 	 Specificity:    0.6827279466271312
Precision  : 0.7002801120448179
Area Under Curve:    0.712008895478132
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5914 - accuracy: 0.6815 - val_loss: 0.5481 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7219 - val_loss: 0.5384 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7319 - val_loss: 0.5368 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7421 - val_loss: 0.5385 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7490 - val_loss: 0.5399 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7567 - val_loss: 0.5421 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7652 - val_loss: 0.5414 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4727 - accuracy: 0.7735 - val_loss: 0.5475 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4605 - accuracy: 0.7802 - val_loss: 0.5519 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4463 - accuracy: 0.7911
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4462 - accuracy: 0.7912 - val_loss: 0.5533 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 965us/step
Independent Testing Matthews Correlation:  0.4312133632090329
Confusion Matrix :
 [[2968 1079]
 [1224 2823]]
Accuracy on test set:    0.7154682480850012
Sensitivity:    0.6975537435137139 	 Specificity:    0.7333827526562886
Precision  : 0.7234751409533573
Area Under Curve:    0.7154682480850012
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5891 - accuracy: 0.6825 - val_loss: 0.5524 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5486 - accuracy: 0.7194 - val_loss: 0.5440 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7320 - val_loss: 0.5403 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7398 - val_loss: 0.5392 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7491 - val_loss: 0.5391 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7565 - val_loss: 0.5415 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4858 - accuracy: 0.7637 - val_loss: 0.5456 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4732 - accuracy: 0.7724
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4730 - accuracy: 0.7728 - val_loss: 0.5572 - val_accuracy: 0.7219 - lr: 0.0010
253/253 [==============================] - 0s 818us/step
Independent Testing Matthews Correlation:  0.4653868593160404
Confusion Matrix :
 [[2737 1310]
 [ 865 3182]]
Accuracy on test set:    0.7312824314306894
Sensitivity:    0.7862614282184334 	 Specificity:    0.6763034346429454
Precision  : 0.7083704363312555
Area Under Curve:    0.7312824314306894
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5895 - accuracy: 0.6832 - val_loss: 0.5477 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7215 - val_loss: 0.5450 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7308 - val_loss: 0.5425 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5204 - accuracy: 0.7402 - val_loss: 0.5429 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5110 - accuracy: 0.7477 - val_loss: 0.5412 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4994 - accuracy: 0.7579 - val_loss: 0.5439 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7657 - val_loss: 0.5480 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4755 - accuracy: 0.7733
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7733 - val_loss: 0.5500 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 786us/step
Independent Testing Matthews Correlation:  0.4676345112086366
Confusion Matrix :
 [[3050  997]
 [1159 2888]]
Accuracy on test set:    0.733629849271065
Sensitivity:    0.7136150234741784 	 Specificity:    0.7536446750679515
Precision  : 0.7433719433719433
Area Under Curve:    0.7336298492710649
(8094, 2560) (8094,)
Mean MCC = 0.4281 + 0.0211 and Mean AUC = 0.7136 + 0.0104
Mean Sensitivity = 0.7210 + 0.0322 and Mean Specificity = 0.7063 + 0.0305 and Mean Accuracy = 0.7136 + 0.0104
Mean Precision = 0.7112 + 0.0153





Seed   : 160654
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5857 - accuracy: 0.6854 - val_loss: 0.5649 - val_accuracy: 0.7035 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5405 - accuracy: 0.7253 - val_loss: 0.5590 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5243 - accuracy: 0.7374 - val_loss: 0.5579 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5128 - accuracy: 0.7447 - val_loss: 0.5598 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7521 - val_loss: 0.5600 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4900 - accuracy: 0.7611 - val_loss: 0.5637 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4763 - accuracy: 0.7698 - val_loss: 0.5744 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4648 - accuracy: 0.7760 - val_loss: 0.5707 - val_accuracy: 0.7019 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4510 - accuracy: 0.7863 - val_loss: 0.5756 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4362 - accuracy: 0.7967
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4373 - accuracy: 0.7958 - val_loss: 0.5733 - val_accuracy: 0.7053 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39890418240671055
Confusion Matrix :
 [[2850 1198]
 [1235 2812]]
Accuracy on test set:    0.699444101297097
Sensitivity:    0.6948356807511737 	 Specificity:    0.7040513833992095
Precision  : 0.7012468827930175
Area Under Curve:    0.6994435320751916
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5897 - accuracy: 0.6812 - val_loss: 0.5638 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7229 - val_loss: 0.5585 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7342 - val_loss: 0.5578 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7411 - val_loss: 0.5555 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7484 - val_loss: 0.5551 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7555 - val_loss: 0.5591 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7645 - val_loss: 0.5643 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.7731 - val_loss: 0.5594 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4601 - accuracy: 0.7805 - val_loss: 0.5666 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4478 - accuracy: 0.7897 - val_loss: 0.5664 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4325 - accuracy: 0.7974 - val_loss: 0.5754 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4219 - accuracy: 0.8029 - val_loss: 0.5784 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 13/400
255/257 [============================>.] - ETA: 0s - loss: 0.4100 - accuracy: 0.8121
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4101 - accuracy: 0.8120 - val_loss: 0.5856 - val_accuracy: 0.7069 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41324211805245303
Confusion Matrix :
 [[2839 1209]
 [1166 2881]]
Accuracy on test set:    0.7066090179122916
Sensitivity:    0.7118853471707438 	 Specificity:    0.7013339920948617
Precision  : 0.70440097799511
Area Under Curve:    0.7066096696328026
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5857 - accuracy: 0.6865 - val_loss: 0.5543 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7227 - val_loss: 0.5488 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7329 - val_loss: 0.5441 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7410 - val_loss: 0.5409 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7499 - val_loss: 0.5416 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7597 - val_loss: 0.5421 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7707 - val_loss: 0.5504 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4653 - accuracy: 0.7782 - val_loss: 0.5464 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4500 - accuracy: 0.7886 - val_loss: 0.5495 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4357 - accuracy: 0.7981
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4359 - accuracy: 0.7980 - val_loss: 0.5620 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 735us/step
Independent Testing Matthews Correlation:  0.43122143197825447
Confusion Matrix :
 [[2759 1288]
 [1018 3030]]
Accuracy on test set:    0.7151327980234713
Sensitivity:    0.7485177865612648 	 Specificity:    0.6817395601680257
Precision  : 0.7017137563686892
Area Under Curve:    0.7151286733646451
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5891 - accuracy: 0.6843 - val_loss: 0.5599 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7222 - val_loss: 0.5447 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5338 - accuracy: 0.7299 - val_loss: 0.5463 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5239 - accuracy: 0.7366 - val_loss: 0.5442 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5138 - accuracy: 0.7443 - val_loss: 0.5427 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5028 - accuracy: 0.7507 - val_loss: 0.5482 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.7607 - val_loss: 0.5461 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4776 - accuracy: 0.7707
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.7712 - val_loss: 0.5502 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4153427704905664
Confusion Matrix :
 [[2681 1366]
 [1007 3041]]
Accuracy on test set:    0.7068560840024707
Sensitivity:    0.7512351778656127 	 Specificity:    0.6624660242154683
Precision  : 0.6900385749943272
Area Under Curve:    0.7068506010405406
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5854 - accuracy: 0.6847 - val_loss: 0.5643 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7226 - val_loss: 0.5475 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7333 - val_loss: 0.5432 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7411 - val_loss: 0.5446 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7495 - val_loss: 0.5444 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7570 - val_loss: 0.5460 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4827 - accuracy: 0.7657 - val_loss: 0.5475 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4698 - accuracy: 0.7743
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7739 - val_loss: 0.5467 - val_accuracy: 0.7252 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41514545704377415
Confusion Matrix :
 [[2790 1257]
 [1111 2936]]
Accuracy on test set:    0.707437608104769
Sensitivity:    0.7254756609834445 	 Specificity:    0.6893995552260934
Precision  : 0.7002146434533747
Area Under Curve:    0.707437608104769
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5862 - accuracy: 0.6875 - val_loss: 0.5534 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7231 - val_loss: 0.5488 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5327 - accuracy: 0.7305 - val_loss: 0.5550 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7385 - val_loss: 0.5483 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7462 - val_loss: 0.5459 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.7516 - val_loss: 0.5440 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7604 - val_loss: 0.5465 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4797 - accuracy: 0.7687 - val_loss: 0.5567 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4673 - accuracy: 0.7755 - val_loss: 0.5589 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4564 - accuracy: 0.7830 - val_loss: 0.5578 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 11/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4446 - accuracy: 0.7928
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4442 - accuracy: 0.7928 - val_loss: 0.5632 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 886us/step
Independent Testing Matthews Correlation:  0.4406503044568057
Confusion Matrix :
 [[2811 1236]
 [1030 3017]]
Accuracy on test set:    0.7200395354583642
Sensitivity:    0.7454904867803311 	 Specificity:    0.6945885841363973
Precision  : 0.7093816129790737
Area Under Curve:    0.7200395354583642
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5867 - accuracy: 0.6845 - val_loss: 0.5514 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7233 - val_loss: 0.5437 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7347 - val_loss: 0.5404 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5148 - accuracy: 0.7434 - val_loss: 0.5404 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7510 - val_loss: 0.5427 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7586 - val_loss: 0.5416 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4850 - accuracy: 0.7648
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.7646 - val_loss: 0.5450 - val_accuracy: 0.7219 - lr: 0.0010
253/253 [==============================] - 0s 784us/step
Independent Testing Matthews Correlation:  0.4188289666246506
Confusion Matrix :
 [[2869 1178]
 [1174 2873]]
Accuracy on test set:    0.7094143810229799
Sensitivity:    0.7099085742525327 	 Specificity:    0.7089201877934272
Precision  : 0.7092076030609726
Area Under Curve:    0.7094143810229799
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5875 - accuracy: 0.6855 - val_loss: 0.5474 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7216 - val_loss: 0.5401 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7323 - val_loss: 0.5356 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7399 - val_loss: 0.5452 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7465 - val_loss: 0.5345 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4994 - accuracy: 0.7536 - val_loss: 0.5408 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7627 - val_loss: 0.5355 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4777 - accuracy: 0.7721 - val_loss: 0.5372 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4655 - accuracy: 0.7800 - val_loss: 0.5434 - val_accuracy: 0.7229 - lr: 0.0010

Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4542 - accuracy: 0.7866
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4542 - accuracy: 0.7867 - val_loss: 0.5475 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4450473075856729
Confusion Matrix :
 [[2946 1101]
 [1145 2902]]
Accuracy on test set:    0.722510501606128
Sensitivity:    0.7170743760810477 	 Specificity:    0.7279466271312083
Precision  : 0.724956282787909
Area Under Curve:    0.7225105016061281
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5888 - accuracy: 0.6825 - val_loss: 0.5511 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7194 - val_loss: 0.5474 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5336 - accuracy: 0.7307 - val_loss: 0.5416 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5233 - accuracy: 0.7378 - val_loss: 0.5407 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5129 - accuracy: 0.7459 - val_loss: 0.5395 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5023 - accuracy: 0.7542 - val_loss: 0.5411 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7614 - val_loss: 0.5442 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4836 - accuracy: 0.7674 - val_loss: 0.5463 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4718 - accuracy: 0.7753 - val_loss: 0.5479 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4603 - accuracy: 0.7834
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4603 - accuracy: 0.7833 - val_loss: 0.5566 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 1s 3ms/step
Independent Testing Matthews Correlation:  0.4546601169199262
Confusion Matrix :
 [[2937 1110]
 [1097 2950]]
Accuracy on test set:    0.7273288855942673
Sensitivity:    0.7289350135903138 	 Specificity:    0.7257227575982209
Precision  : 0.7266009852216748
Area Under Curve:    0.7273288855942672
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5916 - accuracy: 0.6813 - val_loss: 0.5543 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5511 - accuracy: 0.7196 - val_loss: 0.5482 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5363 - accuracy: 0.7289 - val_loss: 0.5438 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5236 - accuracy: 0.7385 - val_loss: 0.5393 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5129 - accuracy: 0.7468 - val_loss: 0.5429 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5000 - accuracy: 0.7555 - val_loss: 0.5431 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7653 - val_loss: 0.5465 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4729 - accuracy: 0.7732 - val_loss: 0.5470 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4607 - accuracy: 0.7845 - val_loss: 0.5528 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4474 - accuracy: 0.7907 - val_loss: 0.5531 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4332 - accuracy: 0.7971 - val_loss: 0.5591 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4184 - accuracy: 0.8084 - val_loss: 0.5806 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 13/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4070 - accuracy: 0.8155
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4075 - accuracy: 0.8151 - val_loss: 0.5707 - val_accuracy: 0.7170 - lr: 0.0010
253/253 [==============================] - 0s 788us/step
Independent Testing Matthews Correlation:  0.47451591733910425
Confusion Matrix :
 [[3023 1024]
 [1103 2944]]
Accuracy on test set:    0.7372127501853225
Sensitivity:    0.7274524339016556 	 Specificity:    0.7469730664689894
Precision  : 0.7419354838709677
Area Under Curve:    0.7372127501853224
(8094, 2560) (8094,)
Mean MCC = 0.4308 + 0.0218 and Mean AUC = 0.7152 + 0.0109
Mean Sensitivity = 0.7261 + 0.0174 and Mean Specificity = 0.7043 + 0.0233 and Mean Accuracy = 0.7152 + 0.0109
Mean Precision = 0.7110 + 0.0148





Seed   : 797300
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5878 - accuracy: 0.6856 - val_loss: 0.5604 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7239 - val_loss: 0.5529 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7349 - val_loss: 0.5532 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7422 - val_loss: 0.5550 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7489 - val_loss: 0.5551 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7582 - val_loss: 0.5583 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7664 - val_loss: 0.5617 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4725 - accuracy: 0.7734 - val_loss: 0.5621 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4618 - accuracy: 0.7797
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4619 - accuracy: 0.7798 - val_loss: 0.5669 - val_accuracy: 0.7061 - lr: 0.0010
253/253 [==============================] - 0s 793us/step
Independent Testing Matthews Correlation:  0.41424355504283755
Confusion Matrix :
 [[2890 1158]
 [1213 2834]]
Accuracy on test set:    0.7071031500926498
Sensitivity:    0.700271806276254 	 Specificity:    0.7139328063241107
Precision  : 0.7099198396793587
Area Under Curve:    0.7071023063001823
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5871 - accuracy: 0.6860 - val_loss: 0.5580 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7222 - val_loss: 0.5535 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7343 - val_loss: 0.5499 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7420 - val_loss: 0.5505 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5038 - accuracy: 0.7503 - val_loss: 0.5589 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.7577 - val_loss: 0.5523 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4806 - accuracy: 0.7681 - val_loss: 0.5619 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4686 - accuracy: 0.7746 - val_loss: 0.5530 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4539 - accuracy: 0.7864 - val_loss: 0.5557 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4434 - accuracy: 0.7907 - val_loss: 0.5666 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4283 - accuracy: 0.8006 - val_loss: 0.5710 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4183 - accuracy: 0.8067 - val_loss: 0.5820 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4058 - accuracy: 0.8129 - val_loss: 0.5791 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3919 - accuracy: 0.8223 - val_loss: 0.5909 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3816 - accuracy: 0.8271 - val_loss: 0.6049 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3695 - accuracy: 0.8334 - val_loss: 0.6037 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 17/400
247/257 [===========================>..] - ETA: 0s - loss: 0.3590 - accuracy: 0.8397
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3590 - accuracy: 0.8396 - val_loss: 0.6233 - val_accuracy: 0.7093 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4295034498863227
Confusion Matrix :
 [[2710 1338]
 [ 978 3069]]
Accuracy on test set:    0.7138974675725757
Sensitivity:    0.7583395107487028 	 Specificity:    0.6694664031620553
Precision  : 0.6963921034717495
Area Under Curve:    0.7139029569553792
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5825 - accuracy: 0.6888 - val_loss: 0.5473 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5418 - accuracy: 0.7238 - val_loss: 0.5396 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7336 - val_loss: 0.5383 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7412 - val_loss: 0.5411 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7500 - val_loss: 0.5399 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7565 - val_loss: 0.5397 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4849 - accuracy: 0.7655
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7655 - val_loss: 0.5442 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 753us/step
Independent Testing Matthews Correlation:  0.43391098996943855
Confusion Matrix :
 [[2960 1087]
 [1205 2843]]
Accuracy on test set:    0.7168622606547251
Sensitivity:    0.7023221343873518 	 Specificity:    0.7314059797380776
Precision  : 0.723409669211196
Area Under Curve:    0.7168640570627147
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5878 - accuracy: 0.6820 - val_loss: 0.5466 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7232 - val_loss: 0.5396 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7335 - val_loss: 0.5379 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7401 - val_loss: 0.5350 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7480 - val_loss: 0.5351 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4980 - accuracy: 0.7561 - val_loss: 0.5479 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4886 - accuracy: 0.7613 - val_loss: 0.5451 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4758 - accuracy: 0.7700 - val_loss: 0.5454 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4656 - accuracy: 0.7775 - val_loss: 0.5452 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4509 - accuracy: 0.7868 - val_loss: 0.5506 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4408 - accuracy: 0.7929 - val_loss: 0.5564 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4271 - accuracy: 0.8040
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4276 - accuracy: 0.8036 - val_loss: 0.5637 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 815us/step
Independent Testing Matthews Correlation:  0.4190695083331321
Confusion Matrix :
 [[2780 1267]
 [1086 2962]]
Accuracy on test set:    0.7093267449042618
Sensitivity:    0.7317193675889329 	 Specificity:    0.6869285890783297
Precision  : 0.7004019862851738
Area Under Curve:    0.7093239783336313
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5897 - accuracy: 0.6817 - val_loss: 0.5462 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7229 - val_loss: 0.5365 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7322 - val_loss: 0.5358 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7418 - val_loss: 0.5319 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.7490 - val_loss: 0.5377 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7567 - val_loss: 0.5384 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7630 - val_loss: 0.5406 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7744 - val_loss: 0.5419 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4602 - accuracy: 0.7820
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4606 - accuracy: 0.7817 - val_loss: 0.5451 - val_accuracy: 0.7174 - lr: 0.0010

253/253 [==============================] - 0s 812us/step
Independent Testing Matthews Correlation:  0.41689518486852917
Confusion Matrix :
 [[2942 1105]
 [1256 2791]]
Accuracy on test set:    0.7083024462564863
Sensitivity:    0.6896466518408698 	 Specificity:    0.7269582406721028
Precision  : 0.7163757700205339
Area Under Curve:    0.7083024462564863
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5905 - accuracy: 0.6798 - val_loss: 0.5517 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7229 - val_loss: 0.5365 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7345 - val_loss: 0.5337 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7414 - val_loss: 0.5357 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7505 - val_loss: 0.5344 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7571 - val_loss: 0.5408 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4840 - accuracy: 0.7646
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7645 - val_loss: 0.5432 - val_accuracy: 0.7248 - lr: 0.0010
253/253 [==============================] - 0s 807us/step
Independent Testing Matthews Correlation:  0.4180866792283575
Confusion Matrix :
 [[2669 1378]
 [ 985 3062]]
Accuracy on test set:    0.7080553496417099
Sensitivity:    0.7566098344452681 	 Specificity:    0.6595008648381517
Precision  : 0.6896396396396396
Area Under Curve:    0.7080553496417099
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5876 - accuracy: 0.6841 - val_loss: 0.5457 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7243 - val_loss: 0.5376 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7329 - val_loss: 0.5364 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7409 - val_loss: 0.5395 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7471 - val_loss: 0.5355 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7552 - val_loss: 0.5471 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7628 - val_loss: 0.5415 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4788 - accuracy: 0.7692 - val_loss: 0.5454 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4660 - accuracy: 0.7779 - val_loss: 0.5432 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 10/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4520 - accuracy: 0.7881
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4525 - accuracy: 0.7876 - val_loss: 0.5568 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 763us/step
Independent Testing Matthews Correlation:  0.41970018056262437
Confusion Matrix :
 [[2666 1381]
 [ 976 3071]]
Accuracy on test set:    0.708796639486039
Sensitivity:    0.7588337039782554 	 Specificity:    0.6587595749938225
Precision  : 0.6898023360287511
Area Under Curve:    0.7087966394860391
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5930 - accuracy: 0.6796 - val_loss: 0.5513 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5498 - accuracy: 0.7209 - val_loss: 0.5381 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5349 - accuracy: 0.7300 - val_loss: 0.5321 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5224 - accuracy: 0.7387 - val_loss: 0.5353 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7467 - val_loss: 0.5328 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5000 - accuracy: 0.7548 - val_loss: 0.5356 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.7636 - val_loss: 0.5368 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7734 - val_loss: 0.5398 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4589 - accuracy: 0.7814 - val_loss: 0.5430 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4451 - accuracy: 0.7917
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4457 - accuracy: 0.7913 - val_loss: 0.5492 - val_accuracy: 0.7235 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4347457365160584
Confusion Matrix :
 [[2859 1188]
 [1100 2947]]
Accuracy on test set:    0.717321472695824
Sensitivity:    0.7281937237459847 	 Specificity:    0.7064492216456635
Precision  : 0.7126964933494558
Area Under Curve:    0.717321472695824
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5902 - accuracy: 0.6821 - val_loss: 0.5489 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7223 - val_loss: 0.5431 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7328 - val_loss: 0.5372 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7415 - val_loss: 0.5357 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7496 - val_loss: 0.5412 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7587 - val_loss: 0.5419 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7664 - val_loss: 0.5485 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7741 - val_loss: 0.5469 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4601 - accuracy: 0.7819
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4601 - accuracy: 0.7819 - val_loss: 0.5505 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46252464020662326
Confusion Matrix :
 [[2828 1219]
 [ 960 3087]]
Accuracy on test set:    0.7307882382011367
Sensitivity:    0.7627872498146775 	 Specificity:    0.6987892265875958
Precision  : 0.7169066418950302
Area Under Curve:    0.7307882382011366
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5942 - accuracy: 0.6792 - val_loss: 0.5468 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5507 - accuracy: 0.7194 - val_loss: 0.5418 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5346 - accuracy: 0.7303 - val_loss: 0.5428 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5241 - accuracy: 0.7397 - val_loss: 0.5393 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7445 - val_loss: 0.5437 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7515 - val_loss: 0.5427 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
252/257 [============================>.] - ETA: 0s - loss: 0.4927 - accuracy: 0.7593
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7591 - val_loss: 0.5418 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 878us/step
Independent Testing Matthews Correlation:  0.4711328419317548
Confusion Matrix :
 [[3130  917]
 [1229 2818]]
Accuracy on test set:    0.7348653323449469
Sensitivity:    0.696318260439832 	 Specificity:    0.7734124042500617
Precision  : 0.7544846050870148
Area Under Curve:    0.7348653323449469
(8094, 2560) (8094,)
Mean MCC = 0.4320 + 0.0188 and Mean AUC = 0.7155 + 0.0094
Mean Sensitivity = 0.7285 + 0.0280 and Mean Specificity = 0.7026 + 0.0342 and Mean Accuracy = 0.7155 + 0.0094
Mean Precision = 0.7110 + 0.0183





Seed   : 169485
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5869 - accuracy: 0.6861 - val_loss: 0.5655 - val_accuracy: 0.7054 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7245 - val_loss: 0.5503 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7344 - val_loss: 0.5483 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7423 - val_loss: 0.5480 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7502 - val_loss: 0.5494 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7584 - val_loss: 0.5542 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7662 - val_loss: 0.5542 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4706 - accuracy: 0.7748 - val_loss: 0.5570 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4577 - accuracy: 0.7827 - val_loss: 0.5648 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4445 - accuracy: 0.7905 - val_loss: 0.5651 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4329 - accuracy: 0.7977 - val_loss: 0.5739 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 12/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4215 - accuracy: 0.8035
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4216 - accuracy: 0.8036 - val_loss: 0.5829 - val_accuracy: 0.7101 - lr: 0.0010
253/253 [==============================] - 0s 912us/step
Independent Testing Matthews Correlation:  0.4097065843657988
Confusion Matrix :
 [[2791 1257]
 [1133 2914]]
Accuracy on test set:    0.7047560222359481
Sensitivity:    0.7200395354583642 	 Specificity:    0.6894762845849802
Precision  : 0.6986334212419084
Area Under Curve:    0.7047579100216722
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5865 - accuracy: 0.6847 - val_loss: 0.5570 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5410 - accuracy: 0.7275 - val_loss: 0.5494 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5260 - accuracy: 0.7356 - val_loss: 0.5467 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5150 - accuracy: 0.7442 - val_loss: 0.5515 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5034 - accuracy: 0.7513 - val_loss: 0.5476 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7581 - val_loss: 0.5552 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7688 - val_loss: 0.5515 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.7756 - val_loss: 0.5518 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4558 - accuracy: 0.7845 - val_loss: 0.5587 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4433 - accuracy: 0.7928 - val_loss: 0.5795 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4311 - accuracy: 0.8013 - val_loss: 0.5750 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4189 - accuracy: 0.8079 - val_loss: 0.5821 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4056 - accuracy: 0.8144 - val_loss: 0.5751 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 14/400
255/257 [============================>.] - ETA: 0s - loss: 0.3938 - accuracy: 0.8227
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3940 - accuracy: 0.8225 - val_loss: 0.5895 - val_accuracy: 0.7106 - lr: 0.0010
253/253 [==============================] - 0s 790us/step
Independent Testing Matthews Correlation:  0.40815007991017377
Confusion Matrix :
 [[2764 1284]
 [1113 2934]]
Accuracy on test set:    0.7038912909203212
Sensitivity:    0.7249814677538917 	 Specificity:    0.682806324110672
Precision  : 0.6955903271692745
Area Under Curve:    0.7038938959322818
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5909 - accuracy: 0.6819 - val_loss: 0.5506 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7219 - val_loss: 0.5414 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7335 - val_loss: 0.5510 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7423 - val_loss: 0.5376 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7494 - val_loss: 0.5477 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7576 - val_loss: 0.5421 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7662 - val_loss: 0.5422 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4738 - accuracy: 0.7721 - val_loss: 0.5463 - val_accuracy: 0.7215 - lr: 0.0010

Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4625 - accuracy: 0.7803
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4628 - accuracy: 0.7802 - val_loss: 0.5493 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41975091685101384
Confusion Matrix :
 [[2826 1221]
 [1128 2920]]
Accuracy on test set:    0.7098208770846202
Sensitivity:    0.7213438735177866 	 Specificity:    0.698295033358043
Precision  : 0.7051436851002173
Area Under Curve:    0.7098194534379147
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5898 - accuracy: 0.6835 - val_loss: 0.5570 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7218 - val_loss: 0.5370 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7326 - val_loss: 0.5389 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7407 - val_loss: 0.5339 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5101 - accuracy: 0.7474 - val_loss: 0.5360 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7568 - val_loss: 0.5343 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4889 - accuracy: 0.7620 - val_loss: 0.5460 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4766 - accuracy: 0.7695 - val_loss: 0.5403 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4662 - accuracy: 0.7773
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4662 - accuracy: 0.7773 - val_loss: 0.5459 - val_accuracy: 0.7260 - lr: 0.0010
253/253 [==============================] - 0s 778us/step
Independent Testing Matthews Correlation:  0.43076438628468217
Confusion Matrix :
 [[3030 1017]
 [1291 2757]]
Accuracy on test set:    0.7148857319332922
Sensitivity:    0.6810770750988142 	 Specificity:    0.748702742772424
Precision  : 0.7305246422893482
Area Under Curve:    0.7148899089356191
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5852 - accuracy: 0.6844 - val_loss: 0.5457 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7226 - val_loss: 0.5371 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7330 - val_loss: 0.5365 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7421 - val_loss: 0.5469 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7490 - val_loss: 0.5377 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7587 - val_loss: 0.5359 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4814 - accuracy: 0.7681
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7679 - val_loss: 0.5447 - val_accuracy: 0.7301 - lr: 0.0010
253/253 [==============================] - 0s 709us/step
Independent Testing Matthews Correlation:  0.4407388136988681
Confusion Matrix :
 [[2689 1358]
 [ 916 3131]]
Accuracy on test set:    0.7190511489992587
Sensitivity:    0.7736595008648381 	 Specificity:    0.6644427971336793
Precision  : 0.697482735575852
Area Under Curve:    0.7190511489992587
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5894 - accuracy: 0.6822 - val_loss: 0.5528 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7235 - val_loss: 0.5377 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7335 - val_loss: 0.5374 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7418 - val_loss: 0.5365 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7502 - val_loss: 0.5367 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7599 - val_loss: 0.5473 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 7/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4839 - accuracy: 0.7651
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7648 - val_loss: 0.5395 - val_accuracy: 0.7248 - lr: 0.0010
253/253 [==============================] - 0s 737us/step
Independent Testing Matthews Correlation:  0.42755453909283053
Confusion Matrix :
 [[2850 1197]
 [1120 2927]]
Accuracy on test set:    0.7137385717815666
Sensitivity:    0.7232517914504571 	 Specificity:    0.704225352112676
Precision  : 0.7097478176527643
Area Under Curve:    0.7137385717815665
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5883 - accuracy: 0.6837 - val_loss: 0.5599 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7228 - val_loss: 0.5413 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5324 - accuracy: 0.7312 - val_loss: 0.5416 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7383 - val_loss: 0.5477 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7479 - val_loss: 0.5424 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7534 - val_loss: 0.5467 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4907 - accuracy: 0.7618
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4902 - accuracy: 0.7624 - val_loss: 0.5499 - val_accuracy: 0.7220 - lr: 0.0010
253/253 [==============================] - 0s 763us/step
Independent Testing Matthews Correlation:  0.4228256430225188
Confusion Matrix :
 [[2980 1067]
 [1271 2776]]
Accuracy on test set:    0.7111440573264146
Sensitivity:    0.6859402026192242 	 Specificity:    0.7363479120336052
Precision  : 0.7223523289097059
Area Under Curve:    0.7111440573264146
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5891 - accuracy: 0.6827 - val_loss: 0.5473 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7224 - val_loss: 0.5395 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7328 - val_loss: 0.5377 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7412 - val_loss: 0.5394 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7471 - val_loss: 0.5382 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.7554 - val_loss: 0.5408 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7632 - val_loss: 0.5526 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4782 - accuracy: 0.7695
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4783 - accuracy: 0.7695 - val_loss: 0.5440 - val_accuracy: 0.7260 - lr: 0.0010
253/253 [==============================] - 0s 887us/step
Independent Testing Matthews Correlation:  0.43399703926756616
Confusion Matrix :
 [[3095  952]
 [1347 2700]]
Accuracy on test set:    0.715962441314554
Sensitivity:    0.6671608598962194 	 Specificity:    0.7647640227328886
Precision  : 0.7393209200438116
Area Under Curve:    0.715962441314554
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5906 - accuracy: 0.6827 - val_loss: 0.5533 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.7211 - val_loss: 0.5443 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7312 - val_loss: 0.5428 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7405 - val_loss: 0.5405 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5102 - accuracy: 0.7479 - val_loss: 0.5474 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4986 - accuracy: 0.7557 - val_loss: 0.5465 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.7634 - val_loss: 0.5538 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4758 - accuracy: 0.7711 - val_loss: 0.5479 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4632 - accuracy: 0.7792
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7790 - val_loss: 0.5580 - val_accuracy: 0.7229 - lr: 0.0010
253/253 [==============================] - 0s 937us/step
Independent Testing Matthews Correlation:  0.4666589081700585
Confusion Matrix :
 [[2861 1186]
 [ 975 3072]]
Accuracy on test set:    0.7330121077341241
Sensitivity:    0.7590808005930318 	 Specificity:    0.7069434148752162
Precision  : 0.7214654767496477
Area Under Curve:    0.7330121077341241
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5891 - accuracy: 0.6838 - val_loss: 0.5547 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5492 - accuracy: 0.7196 - val_loss: 0.5485 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7311 - val_loss: 0.5434 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7399 - val_loss: 0.5430 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7488 - val_loss: 0.5478 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7578 - val_loss: 0.5503 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7652 - val_loss: 0.5480 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4716 - accuracy: 0.7753 - val_loss: 0.5533 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4567 - accuracy: 0.7847 - val_loss: 0.5565 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4447 - accuracy: 0.7926 - val_loss: 0.5567 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4306 - accuracy: 0.8027 - val_loss: 0.5674 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4167 - accuracy: 0.8108 - val_loss: 0.5718 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 13/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4052 - accuracy: 0.8172
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4060 - accuracy: 0.8168 - val_loss: 0.5780 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 949us/step
Independent Testing Matthews Correlation:  0.4550095822230689
Confusion Matrix :
 [[3154  893]
 [1323 2724]]
Accuracy on test set:    0.7262169508277737
Sensitivity:    0.6730911786508524 	 Specificity:    0.7793427230046949
Precision  : 0.7531103124136024
Area Under Curve:    0.7262169508277736
(8094, 2560) (8094,)
Mean MCC = 0.4315 + 0.0177 and Mean AUC = 0.7152 + 0.0086
Mean Sensitivity = 0.7130 + 0.0341 and Mean Specificity = 0.7175 + 0.0358 and Mean Accuracy = 0.7152 + 0.0086
Mean Precision = 0.7173 + 0.0184





Seed   : 760895
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5865 - accuracy: 0.6869 - val_loss: 0.5676 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5422 - accuracy: 0.7257 - val_loss: 0.5527 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7362 - val_loss: 0.5507 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5150 - accuracy: 0.7450 - val_loss: 0.5517 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.7534 - val_loss: 0.5521 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4907 - accuracy: 0.7626 - val_loss: 0.5622 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4785 - accuracy: 0.7713 - val_loss: 0.5570 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7803 - val_loss: 0.5583 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4505 - accuracy: 0.7876 - val_loss: 0.5644 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4365 - accuracy: 0.7973 - val_loss: 0.5654 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - ETA: 0s - loss: 0.4244 - accuracy: 0.8036
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4244 - accuracy: 0.8036 - val_loss: 0.5697 - val_accuracy: 0.7089 - lr: 0.0010
253/253 [==============================] - 0s 869us/step
Independent Testing Matthews Correlation:  0.403929963425399
Confusion Matrix :
 [[2887 1161]
 [1252 2795]]
Accuracy on test set:    0.7019147621988882
Sensitivity:    0.6906350382999753 	 Specificity:    0.713191699604743
Precision  : 0.7065217391304348
Area Under Curve:    0.7019133689523592
(8095, 2560) (8095,)
Epoch 1/400

257/257 [==============================] - 2s 5ms/step - loss: 0.5860 - accuracy: 0.6866 - val_loss: 0.5607 - val_accuracy: 0.7034 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5420 - accuracy: 0.7249 - val_loss: 0.5543 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5250 - accuracy: 0.7370 - val_loss: 0.5491 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5146 - accuracy: 0.7439 - val_loss: 0.5483 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7529 - val_loss: 0.5494 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7601 - val_loss: 0.5498 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4805 - accuracy: 0.7671 - val_loss: 0.5490 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7731 - val_loss: 0.5557 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4571 - accuracy: 0.7819 - val_loss: 0.5567 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4447 - accuracy: 0.7919 - val_loss: 0.5650 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4315 - accuracy: 0.8000 - val_loss: 0.5738 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4208 - accuracy: 0.8052 - val_loss: 0.5722 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4064 - accuracy: 0.8145 - val_loss: 0.5813 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 14/400
252/257 [============================>.] - ETA: 0s - loss: 0.3970 - accuracy: 0.8194
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3971 - accuracy: 0.8194 - val_loss: 0.5977 - val_accuracy: 0.7083 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4165781806821825
Confusion Matrix :
 [[2754 1294]
 [1070 2977]]
Accuracy on test set:    0.7079678814082767
Sensitivity:    0.735606622189276 	 Specificity:    0.6803359683794467
Precision  : 0.6970264575040974
Area Under Curve:    0.7079712952843613
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5860 - accuracy: 0.6859 - val_loss: 0.5498 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7234 - val_loss: 0.5457 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7308 - val_loss: 0.5377 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7412 - val_loss: 0.5442 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7496 - val_loss: 0.5369 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7579 - val_loss: 0.5412 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.7662 - val_loss: 0.5471 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4692 - accuracy: 0.7767 - val_loss: 0.5477 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4567 - accuracy: 0.7840 - val_loss: 0.5458 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4430 - accuracy: 0.7937 - val_loss: 0.5545 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4282 - accuracy: 0.8029 - val_loss: 0.5743 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4144 - accuracy: 0.8103
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4145 - accuracy: 0.8101 - val_loss: 0.5673 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 729us/step
Independent Testing Matthews Correlation:  0.4157005969242788
Confusion Matrix :
 [[2705 1342]
 [1028 3020]]
Accuracy on test set:    0.7072266831377394
Sensitivity:    0.7460474308300395 	 Specificity:    0.6683963429701013
Precision  : 0.6923429619440623
Area Under Curve:    0.7072218869000704
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5928 - accuracy: 0.6808 - val_loss: 0.5604 - val_accuracy: 0.7039 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7210 - val_loss: 0.5429 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7314 - val_loss: 0.5406 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7421 - val_loss: 0.5370 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7474 - val_loss: 0.5384 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7570 - val_loss: 0.5457 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7654 - val_loss: 0.5394 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7739 - val_loss: 0.5420 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4577 - accuracy: 0.7848 - val_loss: 0.5467 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4437 - accuracy: 0.7916 - val_loss: 0.5513 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4289 - accuracy: 0.8003 - val_loss: 0.5529 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4180 - accuracy: 0.8068 - val_loss: 0.5693 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4033 - accuracy: 0.8159 - val_loss: 0.5792 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3931 - accuracy: 0.8209 - val_loss: 0.5890 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3802 - accuracy: 0.8272 - val_loss: 0.5876 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3705 - accuracy: 0.8322 - val_loss: 0.5950 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 17/400
245/257 [===========================>..] - ETA: 0s - loss: 0.3578 - accuracy: 0.8389
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3584 - accuracy: 0.8383 - val_loss: 0.5966 - val_accuracy: 0.7120 - lr: 0.0010
253/253 [==============================] - 0s 703us/step
Independent Testing Matthews Correlation:  0.39108262522317977
Confusion Matrix :
 [[2860 1187]
 [1278 2770]]
Accuracy on test set:    0.695491043854231
Sensitivity:    0.6842885375494071 	 Specificity:    0.7066963182604399
Precision  : 0.7000252716704575
Area Under Curve:    0.6954924279049235
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5845 - accuracy: 0.6864 - val_loss: 0.5493 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7218 - val_loss: 0.5437 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7335 - val_loss: 0.5428 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7419 - val_loss: 0.5422 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7500 - val_loss: 0.5409 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7581 - val_loss: 0.5416 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4829 - accuracy: 0.7669
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4831 - accuracy: 0.7667 - val_loss: 0.5495 - val_accuracy: 0.7126 - lr: 0.0010
253/253 [==============================] - 0s 857us/step
Independent Testing Matthews Correlation:  0.430281757629929
Confusion Matrix :
 [[3050  997]
 [1314 2733]]
Accuracy on test set:    0.7144798616258957
Sensitivity:    0.6753150481838399 	 Specificity:    0.7536446750679515
Precision  : 0.7327077747989276
Area Under Curve:    0.7144798616258956
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5868 - accuracy: 0.6841 - val_loss: 0.5510 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7243 - val_loss: 0.5465 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7323 - val_loss: 0.5418 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7400 - val_loss: 0.5430 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7476 - val_loss: 0.5445 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4970 - accuracy: 0.7566 - val_loss: 0.5465 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4872 - accuracy: 0.7651 - val_loss: 0.5514 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4756 - accuracy: 0.7725
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4758 - accuracy: 0.7726 - val_loss: 0.5508 - val_accuracy: 0.7170 - lr: 0.0010
253/253 [==============================] - 0s 822us/step
Independent Testing Matthews Correlation:  0.4201306742522807
Confusion Matrix :
 [[2768 1279]
 [1070 2977]]
Accuracy on test set:    0.7097850259451446
Sensitivity:    0.735606622189276 	 Specificity:    0.6839634297010131
Precision  : 0.699483082706767
Area Under Curve:    0.7097850259451446
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5896 - accuracy: 0.6825 - val_loss: 0.5539 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7244 - val_loss: 0.5477 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5256 - accuracy: 0.7345 - val_loss: 0.5412 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5140 - accuracy: 0.7451 - val_loss: 0.5431 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.7520 - val_loss: 0.5420 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4891 - accuracy: 0.7609 - val_loss: 0.5432 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7679 - val_loss: 0.5512 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4653 - accuracy: 0.7769
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4653 - accuracy: 0.7768 - val_loss: 0.5531 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 936us/step
Independent Testing Matthews Correlation:  0.42783986737771507
Confusion Matrix :
 [[2780 1267]
 [1051 2996]]
Accuracy on test set:    0.7136150234741784
Sensitivity:    0.7403014578700272 	 Specificity:    0.6869285890783297
Precision  : 0.7027914614121511
Area Under Curve:    0.7136150234741785
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5836 - accuracy: 0.6877 - val_loss: 0.5556 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5432 - accuracy: 0.7238 - val_loss: 0.5397 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7344 - val_loss: 0.5388 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5168 - accuracy: 0.7412 - val_loss: 0.5358 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7520 - val_loss: 0.5412 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7592 - val_loss: 0.5376 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4814 - accuracy: 0.7678
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7678 - val_loss: 0.5398 - val_accuracy: 0.7197 - lr: 0.0010
253/253 [==============================] - 0s 929us/step
Independent Testing Matthews Correlation:  0.4304793807439011
Confusion Matrix :
 [[2994 1053]
 [1254 2793]]
Accuracy on test set:    0.7149740548554485
Sensitivity:    0.6901408450704225 	 Specificity:    0.7398072646404744
Precision  : 0.7262090483619345
Area Under Curve:    0.7149740548554484
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5895 - accuracy: 0.6825 - val_loss: 0.5572 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7204 - val_loss: 0.5471 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7320 - val_loss: 0.5457 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5224 - accuracy: 0.7366 - val_loss: 0.5429 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.7465 - val_loss: 0.5426 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5015 - accuracy: 0.7533 - val_loss: 0.5462 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.7606 - val_loss: 0.5442 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.7706 - val_loss: 0.5567 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4683 - accuracy: 0.7773 - val_loss: 0.5566 - val_accuracy: 0.7202 - lr: 0.0010

Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4540 - accuracy: 0.7855 - val_loss: 0.5565 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4405 - accuracy: 0.7955 - val_loss: 0.5748 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 12/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4275 - accuracy: 0.8019
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4273 - accuracy: 0.8023 - val_loss: 0.5754 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 896us/step
Independent Testing Matthews Correlation:  0.4596028604531412
Confusion Matrix :
 [[2961 1086]
 [1101 2946]]
Accuracy on test set:    0.7297998517420311
Sensitivity:    0.7279466271312083 	 Specificity:    0.7316530763528539
Precision  : 0.7306547619047619
Area Under Curve:    0.7297998517420311
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5903 - accuracy: 0.6814 - val_loss: 0.5551 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7223 - val_loss: 0.5500 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5326 - accuracy: 0.7320 - val_loss: 0.5519 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7400 - val_loss: 0.5479 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5123 - accuracy: 0.7466 - val_loss: 0.5476 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5015 - accuracy: 0.7551 - val_loss: 0.5455 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7615 - val_loss: 0.5455 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4767 - accuracy: 0.7722 - val_loss: 0.5565 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4656 - accuracy: 0.7799 - val_loss: 0.5514 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 10/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4505 - accuracy: 0.7893
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4516 - accuracy: 0.7885 - val_loss: 0.5581 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 940us/step
Independent Testing Matthews Correlation:  0.4653032963187254
Confusion Matrix :
 [[3159  888]
 [1285 2762]]
Accuracy on test set:    0.7315295280454658
Sensitivity:    0.6824808500123548 	 Specificity:    0.7805782060785768
Precision  : 0.7567123287671232
Area Under Curve:    0.7315295280454657
(8094, 2560) (8094,)
Mean MCC = 0.4261 + 0.0216 and Mean AUC = 0.7127 + 0.0106
Mean Sensitivity = 0.7108 + 0.0269 and Mean Specificity = 0.7145 + 0.0345 and Mean Accuracy = 0.7127 + 0.0106
Mean Precision = 0.7144 + 0.0199





Seed   : 785583
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5838 - accuracy: 0.6876 - val_loss: 0.5570 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5400 - accuracy: 0.7247 - val_loss: 0.5485 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5237 - accuracy: 0.7374 - val_loss: 0.5455 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5118 - accuracy: 0.7457 - val_loss: 0.5546 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5010 - accuracy: 0.7530 - val_loss: 0.5473 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4891 - accuracy: 0.7621 - val_loss: 0.5490 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7697 - val_loss: 0.5558 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4657 - accuracy: 0.7771 - val_loss: 0.5549 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4535 - accuracy: 0.7864 - val_loss: 0.5614 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4396 - accuracy: 0.7937 - val_loss: 0.5654 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 11/400
254/257 [============================>.] - ETA: 0s - loss: 0.4287 - accuracy: 0.8001
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4289 - accuracy: 0.8001 - val_loss: 0.5680 - val_accuracy: 0.7134 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3984712211563772
Confusion Matrix :
 [[2649 1399]
 [1042 3005]]
Accuracy on test set:    0.6984558369363805
Sensitivity:    0.7425253274030146 	 Specificity:    0.654397233201581
Precision  : 0.6823342415985467
Area Under Curve:    0.6984612803022978
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5846 - accuracy: 0.6855 - val_loss: 0.5529 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7242 - val_loss: 0.5528 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7341 - val_loss: 0.5462 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7432 - val_loss: 0.5488 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7496 - val_loss: 0.5512 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7588 - val_loss: 0.5500 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.7663 - val_loss: 0.5498 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4716 - accuracy: 0.7751
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7752 - val_loss: 0.5551 - val_accuracy: 0.7139 - lr: 0.0010
253/253 [==============================] - 0s 774us/step
Independent Testing Matthews Correlation:  0.42322901450919587
Confusion Matrix :
 [[3009 1039]
 [1299 2748]]
Accuracy on test set:    0.7111797405806053
Sensitivity:    0.6790214974054856 	 Specificity:    0.7433300395256917
Precision  : 0.7256403485608661
Area Under Curve:    0.7111757684655886
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5926 - accuracy: 0.6794 - val_loss: 0.5543 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7196 - val_loss: 0.5420 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7318 - val_loss: 0.5405 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7406 - val_loss: 0.5368 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7480 - val_loss: 0.5432 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7553 - val_loss: 0.5403 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7656 - val_loss: 0.5418 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.7731 - val_loss: 0.5485 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4600 - accuracy: 0.7819 - val_loss: 0.5519 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4459 - accuracy: 0.7910 - val_loss: 0.5542 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4338 - accuracy: 0.7989 - val_loss: 0.5579 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4211 - accuracy: 0.8053 - val_loss: 0.5645 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4068 - accuracy: 0.8127 - val_loss: 0.5796 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 14/400
246/257 [===========================>..] - ETA: 0s - loss: 0.3965 - accuracy: 0.8189
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3969 - accuracy: 0.8187 - val_loss: 0.5787 - val_accuracy: 0.7124 - lr: 0.0010
253/253 [==============================] - 0s 796us/step
Independent Testing Matthews Correlation:  0.4228257522440307
Confusion Matrix :
 [[2813 1234]
 [1103 2945]]
Accuracy on test set:    0.7113032736256949
Sensitivity:    0.7275197628458498 	 Specificity:    0.69508277736595
Precision  : 0.7047140464225892
Area Under Curve:    0.7113012701058999
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.6814 - val_loss: 0.5507 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7221 - val_loss: 0.5402 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7332 - val_loss: 0.5363 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5207 - accuracy: 0.7399 - val_loss: 0.5354 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7471 - val_loss: 0.5388 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7551 - val_loss: 0.5397 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4867 - accuracy: 0.7649 - val_loss: 0.5425 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.7706 - val_loss: 0.5480 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4634 - accuracy: 0.7802
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4638 - accuracy: 0.7797 - val_loss: 0.5496 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 782us/step
Independent Testing Matthews Correlation:  0.4325608219744512
Confusion Matrix :
 [[2820 1227]
 [1071 2977]]
Accuracy on test set:    0.7161210623841878
Sensitivity:    0.7354249011857708 	 Specificity:    0.6968124536693847
Precision  : 0.7081351094196003
Area Under Curve:    0.7161186774275777
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5849 - accuracy: 0.6868 - val_loss: 0.5538 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7227 - val_loss: 0.5495 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7342 - val_loss: 0.5480 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7394 - val_loss: 0.5514 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7486 - val_loss: 0.5458 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7557 - val_loss: 0.5503 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 7/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4841 - accuracy: 0.7640
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7636 - val_loss: 0.5536 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42689724699764287
Confusion Matrix :
 [[2798 1249]
 [1072 2975]]
Accuracy on test set:    0.7132443785520138
Sensitivity:    0.7351124289597233 	 Specificity:    0.6913763281443044
Precision  : 0.7043087121212122
Area Under Curve:    0.7132443785520138
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5861 - accuracy: 0.6845 - val_loss: 0.5591 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 5ms/step - loss: 0.5452 - accuracy: 0.7217 - val_loss: 0.5478 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7333 - val_loss: 0.5462 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7400 - val_loss: 0.5477 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7485 - val_loss: 0.5503 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7588 - val_loss: 0.5470 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7667 - val_loss: 0.5550 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4683 - accuracy: 0.7775
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4683 - accuracy: 0.7770 - val_loss: 0.5621 - val_accuracy: 0.7126 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43887317589123137
Confusion Matrix :
 [[2727 1320]
 [ 958 3089]]
Accuracy on test set:    0.7185569557697059
Sensitivity:    0.7632814430442303 	 Specificity:    0.6738324684951816
Precision  : 0.70061238376049
Area Under Curve:    0.7185569557697059
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5948 - accuracy: 0.6781 - val_loss: 0.5570 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5496 - accuracy: 0.7203 - val_loss: 0.5468 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5344 - accuracy: 0.7308 - val_loss: 0.5478 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5228 - accuracy: 0.7389 - val_loss: 0.5477 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.7439 - val_loss: 0.5481 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5033 - accuracy: 0.7502 - val_loss: 0.5486 - val_accuracy: 0.7132 - lr: 0.0010

Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4915 - accuracy: 0.7617
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7617 - val_loss: 0.5542 - val_accuracy: 0.7113 - lr: 0.0010
253/253 [==============================] - 0s 848us/step
Independent Testing Matthews Correlation:  0.43143544416405916
Confusion Matrix :
 [[2906 1141]
 [1160 2887]]
Accuracy on test set:    0.7157153446997776
Sensitivity:    0.713367926859402 	 Specificity:    0.7180627625401532
Precision  : 0.7167328699106256
Area Under Curve:    0.7157153446997776
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5869 - accuracy: 0.6873 - val_loss: 0.5528 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7226 - val_loss: 0.5426 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7344 - val_loss: 0.5427 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7421 - val_loss: 0.5412 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7485 - val_loss: 0.5426 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7562 - val_loss: 0.5401 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4876 - accuracy: 0.7640 - val_loss: 0.5430 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4763 - accuracy: 0.7727 - val_loss: 0.5520 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4648 - accuracy: 0.7798 - val_loss: 0.5432 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4510 - accuracy: 0.7873 - val_loss: 0.5589 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4368 - accuracy: 0.7973 - val_loss: 0.5545 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4264 - accuracy: 0.8043
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4265 - accuracy: 0.8043 - val_loss: 0.5577 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43567304386191175
Confusion Matrix :
 [[2877 1170]
 [1114 2933]]
Accuracy on test set:    0.7178156659253768
Sensitivity:    0.7247343711391154 	 Specificity:    0.7108969607116382
Precision  : 0.7148427979527175
Area Under Curve:    0.7178156659253767
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5925 - accuracy: 0.6796 - val_loss: 0.5553 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5489 - accuracy: 0.7214 - val_loss: 0.5452 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7311 - val_loss: 0.5423 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7392 - val_loss: 0.5402 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7477 - val_loss: 0.5426 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5011 - accuracy: 0.7552 - val_loss: 0.5433 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4905 - accuracy: 0.7618 - val_loss: 0.5465 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7700 - val_loss: 0.5522 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4643 - accuracy: 0.7788 - val_loss: 0.5585 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4529 - accuracy: 0.7876 - val_loss: 0.5600 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4395 - accuracy: 0.7969 - val_loss: 0.5593 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4281 - accuracy: 0.8022 - val_loss: 0.5633 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 13/400
255/257 [============================>.] - ETA: 0s - loss: 0.4150 - accuracy: 0.8101
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4150 - accuracy: 0.8100 - val_loss: 0.5760 - val_accuracy: 0.7145 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.4273100312811483
Confusion Matrix :
 [[3029 1018]
 [1304 2743]]
Accuracy on test set:    0.7131208302446257
Sensitivity:    0.6777860143316037 	 Specificity:    0.7484556461576476
Precision  : 0.7293273065674023
Area Under Curve:    0.7131208302446257
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5903 - accuracy: 0.6835 - val_loss: 0.5584 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5494 - accuracy: 0.7201 - val_loss: 0.5494 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5344 - accuracy: 0.7292 - val_loss: 0.5537 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5228 - accuracy: 0.7385 - val_loss: 0.5571 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5120 - accuracy: 0.7464 - val_loss: 0.5505 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4995 - accuracy: 0.7553 - val_loss: 0.5518 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7642 - val_loss: 0.5515 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7730 - val_loss: 0.5542 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4614 - accuracy: 0.7831 - val_loss: 0.5589 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4456 - accuracy: 0.7906 - val_loss: 0.5597 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4325 - accuracy: 0.7997 - val_loss: 0.5680 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4192 - accuracy: 0.8062 - val_loss: 0.5762 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4050 - accuracy: 0.8167 - val_loss: 0.5789 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 14/400
247/257 [===========================>..] - ETA: 0s - loss: 0.3960 - accuracy: 0.8214
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3952 - accuracy: 0.8219 - val_loss: 0.6095 - val_accuracy: 0.7139 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.48814560783272615
Confusion Matrix :
 [[2931 1116]
 [ 957 3090]]
Accuracy on test set:    0.7438843587842846
Sensitivity:    0.7635285396590067 	 Specificity:    0.7242401779095626
Precision  : 0.7346647646219686
Area Under Curve:    0.7438843587842847
(8094, 2560) (8094,)
Mean MCC = 0.4325 + 0.0213 and Mean AUC = 0.7159 + 0.0108
Mean Sensitivity = 0.7262 + 0.0282 and Mean Specificity = 0.7056 + 0.0279 and Mean Accuracy = 0.7159 + 0.0108
Mean Precision = 0.7121 + 0.0147





Seed   : 129779

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5843 - accuracy: 0.6889 - val_loss: 0.5558 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5417 - accuracy: 0.7258 - val_loss: 0.5483 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7344 - val_loss: 0.5505 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7422 - val_loss: 0.5492 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7500 - val_loss: 0.5510 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7586 - val_loss: 0.5554 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7666 - val_loss: 0.5573 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.7751 - val_loss: 0.5590 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 9/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4571 - accuracy: 0.7844
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4571 - accuracy: 0.7841 - val_loss: 0.5670 - val_accuracy: 0.7157 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39426555577408046
Confusion Matrix :
 [[2691 1357]
 [1098 2949]]
Accuracy on test set:    0.6967263743051266
Sensitivity:    0.7286879169755375 	 Specificity:    0.6647727272727273
Precision  : 0.6848583372039015
Area Under Curve:    0.6967303221241323
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5837 - accuracy: 0.6878 - val_loss: 0.5555 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5413 - accuracy: 0.7252 - val_loss: 0.5462 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5265 - accuracy: 0.7345 - val_loss: 0.5454 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5116 - accuracy: 0.7448 - val_loss: 0.5486 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.7545 - val_loss: 0.5463 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4886 - accuracy: 0.7639 - val_loss: 0.5469 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7705 - val_loss: 0.5522 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4610 - accuracy: 0.7789 - val_loss: 0.5564 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4491 - accuracy: 0.7891 - val_loss: 0.5595 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4348 - accuracy: 0.7980 - val_loss: 0.5677 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4202 - accuracy: 0.8068 - val_loss: 0.5696 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4073 - accuracy: 0.8140 - val_loss: 0.5691 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3965 - accuracy: 0.8196 - val_loss: 0.5852 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 14/400
243/257 [===========================>..] - ETA: 0s - loss: 0.3835 - accuracy: 0.8261
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3833 - accuracy: 0.8265 - val_loss: 0.5994 - val_accuracy: 0.7135 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4115289606260545
Confusion Matrix :
 [[2829 1219]
 [1163 2884]]
Accuracy on test set:    0.7057442865966647
Sensitivity:    0.7126266370150729 	 Specificity:    0.6988636363636364
Precision  : 0.7029003168413356
Area Under Curve:    0.7057451366893546
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5870 - accuracy: 0.6852 - val_loss: 0.5606 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7240 - val_loss: 0.5458 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7338 - val_loss: 0.5386 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7428 - val_loss: 0.5415 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7490 - val_loss: 0.5410 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7572 - val_loss: 0.5383 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4854 - accuracy: 0.7643 - val_loss: 0.5411 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7737 - val_loss: 0.5452 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4626 - accuracy: 0.7812 - val_loss: 0.5478 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4527 - accuracy: 0.7860
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4524 - accuracy: 0.7862 - val_loss: 0.5537 - val_accuracy: 0.7167 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4257300293025188
Confusion Matrix :
 [[2972 1075]
 [1251 2797]]
Accuracy on test set:    0.71266213712168
Sensitivity:    0.6909584980237155 	 Specificity:    0.7343711391153941
Precision  : 0.7223657024793388
Area Under Curve:    0.7126648185695548
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5991 - accuracy: 0.6756 - val_loss: 0.5568 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5503 - accuracy: 0.7185 - val_loss: 0.5419 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7310 - val_loss: 0.5378 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5216 - accuracy: 0.7398 - val_loss: 0.5373 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5113 - accuracy: 0.7460 - val_loss: 0.5386 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7533 - val_loss: 0.5425 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4908 - accuracy: 0.7615 - val_loss: 0.5428 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4802 - accuracy: 0.7682 - val_loss: 0.5430 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4683 - accuracy: 0.7769 - val_loss: 0.5456 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4565 - accuracy: 0.7861 - val_loss: 0.5502 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4444 - accuracy: 0.7944 - val_loss: 0.5535 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4347 - accuracy: 0.7992 - val_loss: 0.5619 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4198 - accuracy: 0.8073 - val_loss: 0.5767 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 14/400
252/257 [============================>.] - ETA: 0s - loss: 0.4098 - accuracy: 0.8141
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4100 - accuracy: 0.8141 - val_loss: 0.5736 - val_accuracy: 0.7121 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.41664422232861625
Confusion Matrix :
 [[2710 1337]
 [1029 3019]]
Accuracy on test set:    0.7077208153180976
Sensitivity:    0.745800395256917 	 Specificity:    0.6696318260439832
Precision  : 0.6930670339761249
Area Under Curve:    0.70771611065045
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5855 - accuracy: 0.6838 - val_loss: 0.5470 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7237 - val_loss: 0.5386 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7338 - val_loss: 0.5373 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7417 - val_loss: 0.5397 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7506 - val_loss: 0.5370 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7586 - val_loss: 0.5427 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7670 - val_loss: 0.5403 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4684 - accuracy: 0.7756 - val_loss: 0.5456 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4556 - accuracy: 0.7843 - val_loss: 0.5549 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4432 - accuracy: 0.7911 - val_loss: 0.5576 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 11/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4302 - accuracy: 0.8012
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4309 - accuracy: 0.8009 - val_loss: 0.5608 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 783us/step
Independent Testing Matthews Correlation:  0.4290436770893235
Confusion Matrix :
 [[2666 1381]
 [ 940 3107]]
Accuracy on test set:    0.7132443785520138
Sensitivity:    0.7677291821102051 	 Specificity:    0.6587595749938225
Precision  : 0.6922905525846702
Area Under Curve:    0.713244378552014
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5911 - accuracy: 0.6801 - val_loss: 0.5476 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7207 - val_loss: 0.5421 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5324 - accuracy: 0.7322 - val_loss: 0.5411 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7410 - val_loss: 0.5380 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5094 - accuracy: 0.7483 - val_loss: 0.5362 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7582 - val_loss: 0.5390 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7668 - val_loss: 0.5424 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4725 - accuracy: 0.7736 - val_loss: 0.5455 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4586 - accuracy: 0.7851 - val_loss: 0.5485 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4466 - accuracy: 0.7919 - val_loss: 0.5511 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4340 - accuracy: 0.7979
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4341 - accuracy: 0.7980 - val_loss: 0.5587 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 821us/step
Independent Testing Matthews Correlation:  0.4243132486562254
Confusion Matrix :
 [[2957 1090]
 [1241 2806]]
Accuracy on test set:    0.712008895478132
Sensitivity:    0.6933531010625155 	 Specificity:    0.7306646898937484
Precision  : 0.7202258726899384
Area Under Curve:    0.712008895478132
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5887 - accuracy: 0.6833 - val_loss: 0.5490 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7234 - val_loss: 0.5415 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7340 - val_loss: 0.5384 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7410 - val_loss: 0.5400 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7504 - val_loss: 0.5409 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7575 - val_loss: 0.5393 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7681 - val_loss: 0.5422 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7758 - val_loss: 0.5437 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4582 - accuracy: 0.7829
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4584 - accuracy: 0.7826 - val_loss: 0.5489 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4173739930937902
Confusion Matrix :
 [[3050  997]
 [1368 2679]]
Accuracy on test set:    0.7078082530269335
Sensitivity:    0.6619718309859155 	 Specificity:    0.7536446750679515
Precision  : 0.7287812840043526
Area Under Curve:    0.7078082530269334
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5882 - accuracy: 0.6845 - val_loss: 0.5451 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7240 - val_loss: 0.5464 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7340 - val_loss: 0.5351 - val_accuracy: 0.7263 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7415 - val_loss: 0.5341 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7483 - val_loss: 0.5380 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7587 - val_loss: 0.5365 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7685 - val_loss: 0.5364 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4681 - accuracy: 0.7785
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4682 - accuracy: 0.7783 - val_loss: 0.5363 - val_accuracy: 0.7238 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43463816853996423
Confusion Matrix :
 [[2998 1049]
 [1241 2806]]
Accuracy on test set:    0.7170743760810477
Sensitivity:    0.6933531010625155 	 Specificity:    0.7407956510995799
Precision  : 0.7278858625162127
Area Under Curve:    0.7170743760810476
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5958 - accuracy: 0.6791 - val_loss: 0.5523 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5518 - accuracy: 0.7191 - val_loss: 0.5480 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5372 - accuracy: 0.7294 - val_loss: 0.5396 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7373 - val_loss: 0.5422 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7440 - val_loss: 0.5397 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7509 - val_loss: 0.5399 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4954 - accuracy: 0.7595 - val_loss: 0.5414 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4866 - accuracy: 0.7659 - val_loss: 0.5426 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4731 - accuracy: 0.7744 - val_loss: 0.5513 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4619 - accuracy: 0.7820 - val_loss: 0.5471 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4494 - accuracy: 0.7902 - val_loss: 0.5495 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 12/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4393 - accuracy: 0.7968
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4392 - accuracy: 0.7966 - val_loss: 0.5651 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.45399433228281955
Confusion Matrix :
 [[2819 1228]
 [ 985 3062]]
Accuracy on test set:    0.7265875957499383
Sensitivity:    0.7566098344452681 	 Specificity:    0.6965653570546083
Precision  : 0.7137529137529137
Area Under Curve:    0.7265875957499383
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5926 - accuracy: 0.6801 - val_loss: 0.5525 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7199 - val_loss: 0.5464 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5345 - accuracy: 0.7292 - val_loss: 0.5438 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5233 - accuracy: 0.7392 - val_loss: 0.5376 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5141 - accuracy: 0.7467 - val_loss: 0.5431 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.7540 - val_loss: 0.5398 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7623 - val_loss: 0.5496 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7712 - val_loss: 0.5460 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4673 - accuracy: 0.7783 - val_loss: 0.5497 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4548 - accuracy: 0.7847 - val_loss: 0.5520 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4398 - accuracy: 0.7950 - val_loss: 0.5562 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4271 - accuracy: 0.8026 - val_loss: 0.5591 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4147 - accuracy: 0.8109 - val_loss: 0.5737 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4041 - accuracy: 0.8172 - val_loss: 0.5763 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3910 - accuracy: 0.8249 - val_loss: 0.5808 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3799 - accuracy: 0.8305 - val_loss: 0.5928 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 17/400
246/257 [===========================>..] - ETA: 0s - loss: 0.3668 - accuracy: 0.8394
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3674 - accuracy: 0.8390 - val_loss: 0.6051 - val_accuracy: 0.7083 - lr: 0.0010
253/253 [==============================] - 0s 851us/step
Independent Testing Matthews Correlation:  0.4638697409393506
Confusion Matrix :
 [[2927 1120]
 [1050 2997]]
Accuracy on test set:    0.7319001729676303
Sensitivity:    0.7405485544848036 	 Specificity:    0.7232517914504571
Precision  : 0.7279572504250668
Area Under Curve:    0.7319001729676304
(8094, 2560) (8094,)
Mean MCC = 0.4271 + 0.0192 and Mean AUC = 0.7131 + 0.0097
Mean Sensitivity = 0.7192 + 0.0323 and Mean Specificity = 0.7071 + 0.0325 and Mean Accuracy = 0.7131 + 0.0097
Mean Precision = 0.7114 + 0.0159





Seed   : 220259
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5825 - accuracy: 0.6892 - val_loss: 0.5584 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5416 - accuracy: 0.7245 - val_loss: 0.5562 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5259 - accuracy: 0.7369 - val_loss: 0.5517 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.7448 - val_loss: 0.5512 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.7531 - val_loss: 0.5575 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7614 - val_loss: 0.5601 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4794 - accuracy: 0.7691 - val_loss: 0.5587 - val_accuracy: 0.7105 - lr: 0.0010

Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4660 - accuracy: 0.7774 - val_loss: 0.5616 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4557 - accuracy: 0.7846 - val_loss: 0.5645 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4416 - accuracy: 0.7926
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4418 - accuracy: 0.7925 - val_loss: 0.5791 - val_accuracy: 0.7050 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39553655376343144
Confusion Matrix :
 [[2501 1547]
 [ 919 3128]]
Accuracy on test set:    0.6953675108091415
Sensitivity:    0.7729182110205091 	 Specificity:    0.6178359683794467
Precision  : 0.6690909090909091
Area Under Curve:    0.6953770896999778
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5927 - accuracy: 0.6798 - val_loss: 0.5575 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7233 - val_loss: 0.5572 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7338 - val_loss: 0.5492 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7419 - val_loss: 0.5495 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7491 - val_loss: 0.5491 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7587 - val_loss: 0.5512 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7677 - val_loss: 0.5559 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 8/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4737 - accuracy: 0.7754
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4730 - accuracy: 0.7759 - val_loss: 0.5630 - val_accuracy: 0.7073 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4215322560035987
Confusion Matrix :
 [[2726 1322]
 [1024 3023]]
Accuracy on test set:    0.7101914762198889
Sensitivity:    0.7469730664689894 	 Specificity:    0.6734189723320159
Precision  : 0.6957422324510932
Area Under Curve:    0.7101960194005027
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5877 - accuracy: 0.6850 - val_loss: 0.5531 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7227 - val_loss: 0.5434 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7345 - val_loss: 0.5432 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5168 - accuracy: 0.7414 - val_loss: 0.5393 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7506 - val_loss: 0.5433 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7572 - val_loss: 0.5429 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7645 - val_loss: 0.5446 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7729 - val_loss: 0.5451 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4631 - accuracy: 0.7811 - val_loss: 0.5492 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4503 - accuracy: 0.7883 - val_loss: 0.5535 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4380 - accuracy: 0.7964 - val_loss: 0.5609 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4253 - accuracy: 0.8026 - val_loss: 0.5618 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 13/400
254/257 [============================>.] - ETA: 0s - loss: 0.4135 - accuracy: 0.8098
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4135 - accuracy: 0.8099 - val_loss: 0.5748 - val_accuracy: 0.7112 - lr: 0.0010
253/253 [==============================] - 0s 931us/step
Independent Testing Matthews Correlation:  0.419161103618623
Confusion Matrix :
 [[2942 1105]
 [1247 2801]]
Accuracy on test set:    0.7094502779493514
Sensitivity:    0.6919466403162056 	 Specificity:    0.7269582406721028
Precision  : 0.7171018945212494
Area Under Curve:    0.7094524404941541
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5859 - accuracy: 0.6840 - val_loss: 0.5476 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7245 - val_loss: 0.5389 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7360 - val_loss: 0.5453 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7427 - val_loss: 0.5369 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7513 - val_loss: 0.5389 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7587 - val_loss: 0.5406 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7666 - val_loss: 0.5448 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4703 - accuracy: 0.7745 - val_loss: 0.5493 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4582 - accuracy: 0.7843 - val_loss: 0.5501 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4467 - accuracy: 0.7922 - val_loss: 0.5596 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4336 - accuracy: 0.8005 - val_loss: 0.5606 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 12/400
250/257 [============================>.] - ETA: 0s - loss: 0.4184 - accuracy: 0.8079
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4191 - accuracy: 0.8073 - val_loss: 0.5741 - val_accuracy: 0.7054 - lr: 0.0010
253/253 [==============================] - 0s 927us/step
Independent Testing Matthews Correlation:  0.4171972131092824
Confusion Matrix :
 [[3138  909]
 [1466 2582]]
Accuracy on test set:    0.7066090179122916
Sensitivity:    0.6378458498023716 	 Specificity:    0.7753891771682728
Precision  : 0.7396161558292753
Area Under Curve:    0.7066175134853222
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5886 - accuracy: 0.6812 - val_loss: 0.5551 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7219 - val_loss: 0.5445 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7316 - val_loss: 0.5418 - val_accuracy: 0.7229 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7398 - val_loss: 0.5414 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7462 - val_loss: 0.5429 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.7537 - val_loss: 0.5420 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7617 - val_loss: 0.5445 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4775 - accuracy: 0.7714 - val_loss: 0.5483 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4655 - accuracy: 0.7780 - val_loss: 0.5521 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4530 - accuracy: 0.7856 - val_loss: 0.5584 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4417 - accuracy: 0.7931
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7930 - val_loss: 0.5599 - val_accuracy: 0.7213 - lr: 0.0010
253/253 [==============================] - 0s 820us/step
Independent Testing Matthews Correlation:  0.42466604170780425
Confusion Matrix :
 [[2937 1110]
 [1219 2828]]
Accuracy on test set:    0.7122559920929084
Sensitivity:    0.6987892265875958 	 Specificity:    0.7257227575982209
Precision  : 0.718131030980193
Area Under Curve:    0.7122559920929084
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5882 - accuracy: 0.6831 - val_loss: 0.5484 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7228 - val_loss: 0.5415 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7341 - val_loss: 0.5375 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7409 - val_loss: 0.5383 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7490 - val_loss: 0.5397 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7575 - val_loss: 0.5392 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7647 - val_loss: 0.5385 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4701 - accuracy: 0.7748 - val_loss: 0.5428 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4612 - accuracy: 0.7813
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4611 - accuracy: 0.7812 - val_loss: 0.5476 - val_accuracy: 0.7193 - lr: 0.0010
253/253 [==============================] - 0s 929us/step
Independent Testing Matthews Correlation:  0.4225577022712948
Confusion Matrix :
 [[3093  954]
 [1393 2654]]
Accuracy on test set:    0.7100321225599209
Sensitivity:    0.6557944156165061 	 Specificity:    0.7642698295033358
Precision  : 0.7355875831485588
Area Under Curve:    0.710032122559921
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5878 - accuracy: 0.6859 - val_loss: 0.5449 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7238 - val_loss: 0.5415 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7306 - val_loss: 0.5367 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7423 - val_loss: 0.5395 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7505 - val_loss: 0.5371 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7585 - val_loss: 0.5399 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4825 - accuracy: 0.7650 - val_loss: 0.5434 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4727 - accuracy: 0.7725
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4729 - accuracy: 0.7724 - val_loss: 0.5452 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41290454430261264
Confusion Matrix :
 [[2848 1199]
 [1177 2870]]
Accuracy on test set:    0.7064492216456635
Sensitivity:    0.7091672844082036 	 Specificity:    0.7037311588831233
Precision  : 0.7053330056524945
Area Under Curve:    0.7064492216456635
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5914 - accuracy: 0.6793 - val_loss: 0.5478 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5481 - accuracy: 0.7215 - val_loss: 0.5379 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5338 - accuracy: 0.7303 - val_loss: 0.5374 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5227 - accuracy: 0.7372 - val_loss: 0.5378 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5117 - accuracy: 0.7462 - val_loss: 0.5380 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5018 - accuracy: 0.7532 - val_loss: 0.5364 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7618 - val_loss: 0.5387 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4795 - accuracy: 0.7682
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7681 - val_loss: 0.5399 - val_accuracy: 0.7272 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43612573810767447
Confusion Matrix :
 [[2904 1143]
 [1139 2908]]
Accuracy on test set:    0.7180627625401532
Sensitivity:    0.7185569557697059 	 Specificity:    0.7175685693106004
Precision  : 0.7178474450752901
Area Under Curve:    0.7180627625401532
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5918 - accuracy: 0.6812 - val_loss: 0.5465 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5488 - accuracy: 0.7198 - val_loss: 0.5433 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5327 - accuracy: 0.7314 - val_loss: 0.5428 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7389 - val_loss: 0.5365 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7481 - val_loss: 0.5353 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7570 - val_loss: 0.5359 - val_accuracy: 0.7275 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7647 - val_loss: 0.5458 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4714 - accuracy: 0.7736 - val_loss: 0.5392 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4588 - accuracy: 0.7831 - val_loss: 0.5393 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4456 - accuracy: 0.7910 - val_loss: 0.5551 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4323 - accuracy: 0.7976 - val_loss: 0.5626 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4197 - accuracy: 0.8060 - val_loss: 0.5622 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 13/400
249/257 [============================>.] - ETA: 0s - loss: 0.4084 - accuracy: 0.8138
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4085 - accuracy: 0.8137 - val_loss: 0.5589 - val_accuracy: 0.7308 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4378956421757441
Confusion Matrix :
 [[2937 1110]
 [1165 2882]]
Accuracy on test set:    0.7189276006918706
Sensitivity:    0.7121324437855201 	 Specificity:    0.7257227575982209
Precision  : 0.7219438877755511
Area Under Curve:    0.7189276006918706
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5916 - accuracy: 0.6800 - val_loss: 0.5486 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7198 - val_loss: 0.5424 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5338 - accuracy: 0.7310 - val_loss: 0.5448 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5233 - accuracy: 0.7382 - val_loss: 0.5408 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7484 - val_loss: 0.5609 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4991 - accuracy: 0.7570 - val_loss: 0.5447 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.7649 - val_loss: 0.5525 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7732 - val_loss: 0.5485 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4607 - accuracy: 0.7849
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4608 - accuracy: 0.7848 - val_loss: 0.5648 - val_accuracy: 0.7167 - lr: 0.0010
253/253 [==============================] - 0s 834us/step
Independent Testing Matthews Correlation:  0.47776290730269055
Confusion Matrix :
 [[2886 1161]
 [ 955 3092]]
Accuracy on test set:    0.7385717815665925
Sensitivity:    0.7640227328885594 	 Specificity:    0.7131208302446257
Precision  : 0.7270162238419939
Area Under Curve:    0.7385717815665925
(8094, 2560) (8094,)
Mean MCC = 0.4265 + 0.0204 and Mean AUC = 0.7126 + 0.0107
Mean Sensitivity = 0.7108 + 0.0411 and Mean Specificity = 0.7144 + 0.0421 and Mean Accuracy = 0.7126 + 0.0107
Mean Precision = 0.7147 + 0.0195





Seed   : 31871
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5835 - accuracy: 0.6887 - val_loss: 0.5648 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5415 - accuracy: 0.7253 - val_loss: 0.5525 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7348 - val_loss: 0.5477 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7443 - val_loss: 0.5543 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7506 - val_loss: 0.5480 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7588 - val_loss: 0.5526 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7668 - val_loss: 0.5531 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4697 - accuracy: 0.7766
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4701 - accuracy: 0.7764 - val_loss: 0.5570 - val_accuracy: 0.7105 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40806064377988055
Confusion Matrix :
 [[2952 1096]
 [1302 2745]]
Accuracy on test set:    0.7037677578752316
Sensitivity:    0.6782802075611564 	 Specificity:    0.7292490118577075
Precision  : 0.7146576412392606
Area Under Curve:    0.7037646097094319
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6851 - val_loss: 0.5554 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7236 - val_loss: 0.5499 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7327 - val_loss: 0.5498 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7427 - val_loss: 0.5469 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7528 - val_loss: 0.5480 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7602 - val_loss: 0.5501 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4791 - accuracy: 0.7689 - val_loss: 0.5529 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.7775 - val_loss: 0.5518 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4538 - accuracy: 0.7850 - val_loss: 0.5599 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4411 - accuracy: 0.7934 - val_loss: 0.5641 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 11/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4262 - accuracy: 0.8019
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4267 - accuracy: 0.8013 - val_loss: 0.5688 - val_accuracy: 0.7102 - lr: 0.0010
253/253 [==============================] - 0s 952us/step
Independent Testing Matthews Correlation:  0.41758383841902713
Confusion Matrix :
 [[2717 1331]
 [1031 3016]]
Accuracy on test set:    0.7082149474984558
Sensitivity:    0.7452433901655547 	 Specificity:    0.6711956521739131
Precision  : 0.6938118242466068
Area Under Curve:    0.708219521169734
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5876 - accuracy: 0.6860 - val_loss: 0.5494 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7225 - val_loss: 0.5369 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7316 - val_loss: 0.5342 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7412 - val_loss: 0.5341 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5103 - accuracy: 0.7469 - val_loss: 0.5361 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7542 - val_loss: 0.5403 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7594 - val_loss: 0.5391 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4798 - accuracy: 0.7689
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7687 - val_loss: 0.5397 - val_accuracy: 0.7252 - lr: 0.0010
253/253 [==============================] - 0s 972us/step
Independent Testing Matthews Correlation:  0.4110292896715435
Confusion Matrix :
 [[2881 1166]
 [1218 2830]]
Accuracy on test set:    0.7054972205064854
Sensitivity:    0.6991106719367589 	 Specificity:    0.7118853471707438
Precision  : 0.7082082082082082
Area Under Curve:    0.7054980095537514
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5849 - accuracy: 0.6860 - val_loss: 0.5471 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7241 - val_loss: 0.5368 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7347 - val_loss: 0.5370 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7419 - val_loss: 0.5359 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7516 - val_loss: 0.5421 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7593 - val_loss: 0.5379 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4801 - accuracy: 0.7686 - val_loss: 0.5424 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4677 - accuracy: 0.7778 - val_loss: 0.5480 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4551 - accuracy: 0.7850 - val_loss: 0.5531 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4429 - accuracy: 0.7936 - val_loss: 0.5593 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4296 - accuracy: 0.8012
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4298 - accuracy: 0.8010 - val_loss: 0.5614 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.419002549462117
Confusion Matrix :
 [[2826 1221]
 [1131 2917]]
Accuracy on test set:    0.7094502779493514
Sensitivity:    0.720602766798419 	 Specificity:    0.698295033358043
Precision  : 0.7049299178347027
Area Under Curve:    0.7094489000782309
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5837 - accuracy: 0.6875 - val_loss: 0.5487 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5432 - accuracy: 0.7238 - val_loss: 0.5400 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7341 - val_loss: 0.5411 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7414 - val_loss: 0.5454 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7501 - val_loss: 0.5421 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7577 - val_loss: 0.5413 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4799 - accuracy: 0.7669
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4803 - accuracy: 0.7669 - val_loss: 0.5505 - val_accuracy: 0.7241 - lr: 0.0010
253/253 [==============================] - 0s 997us/step
Independent Testing Matthews Correlation:  0.4344336453281272
Confusion Matrix :
 [[2587 1460]
 [ 849 3198]]
Accuracy on test set:    0.7147269582406721
Sensitivity:    0.7902149740548554 	 Specificity:    0.6392389424264887
Precision  : 0.686560755689137
Area Under Curve:    0.7147269582406721
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5845 - accuracy: 0.6886 - val_loss: 0.5482 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7213 - val_loss: 0.5426 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7354 - val_loss: 0.5395 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5140 - accuracy: 0.7451 - val_loss: 0.5423 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5033 - accuracy: 0.7535 - val_loss: 0.5395 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7619 - val_loss: 0.5510 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4776 - accuracy: 0.7710
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7707 - val_loss: 0.5458 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4272853207447602
Confusion Matrix :
 [[2763 1284]
 [1037 3010]]
Accuracy on test set:    0.7132443785520138
Sensitivity:    0.7437608104768965 	 Specificity:    0.6827279466271312
Precision  : 0.7009781089892874
Area Under Curve:    0.7132443785520138
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5863 - accuracy: 0.6851 - val_loss: 0.5469 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7247 - val_loss: 0.5414 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7355 - val_loss: 0.5414 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7430 - val_loss: 0.5389 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7515 - val_loss: 0.5409 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7559 - val_loss: 0.5405 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4860 - accuracy: 0.7655
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4862 - accuracy: 0.7658 - val_loss: 0.5437 - val_accuracy: 0.7211 - lr: 0.0010

253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.43576960163284856
Confusion Matrix :
 [[2775 1272]
 [1015 3032]]
Accuracy on test set:    0.7174450210032123
Sensitivity:    0.7491969360019768 	 Specificity:    0.6856931060044478
Precision  : 0.7044609665427509
Area Under Curve:    0.7174450210032124
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5843 - accuracy: 0.6876 - val_loss: 0.5515 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7222 - val_loss: 0.5394 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7350 - val_loss: 0.5359 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7429 - val_loss: 0.5481 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7490 - val_loss: 0.5341 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.7563 - val_loss: 0.5349 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7655 - val_loss: 0.5360 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7752 - val_loss: 0.5423 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4591 - accuracy: 0.7838 - val_loss: 0.5439 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4470 - accuracy: 0.7913 - val_loss: 0.5502 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4331 - accuracy: 0.8007
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4336 - accuracy: 0.8000 - val_loss: 0.5467 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43261803264207194
Confusion Matrix :
 [[2783 1264]
 [1035 3012]]
Accuracy on test set:    0.715962441314554
Sensitivity:    0.7442550037064493 	 Specificity:    0.6876698789226587
Precision  : 0.7043966323666978
Area Under Curve:    0.715962441314554
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5901 - accuracy: 0.6836 - val_loss: 0.5540 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5497 - accuracy: 0.7179 - val_loss: 0.5429 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7314 - val_loss: 0.5413 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7403 - val_loss: 0.5542 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7483 - val_loss: 0.5457 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7580 - val_loss: 0.5413 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7692 - val_loss: 0.5426 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7763 - val_loss: 0.5557 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4533 - accuracy: 0.7839 - val_loss: 0.5640 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4406 - accuracy: 0.7931 - val_loss: 0.5638 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4255 - accuracy: 0.8036 - val_loss: 0.5674 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 12/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4134 - accuracy: 0.8100
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4134 - accuracy: 0.8097 - val_loss: 0.5758 - val_accuracy: 0.7146 - lr: 0.0010
253/253 [==============================] - 0s 884us/step
Independent Testing Matthews Correlation:  0.4443114362349867
Confusion Matrix :
 [[3099  948]
 [1308 2739]]
Accuracy on test set:    0.7212750185322461
Sensitivity:    0.6767976278724982 	 Specificity:    0.765752409191994
Precision  : 0.7428803905614321
Area Under Curve:    0.7212750185322461
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5918 - accuracy: 0.6821 - val_loss: 0.5516 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7192 - val_loss: 0.5444 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5345 - accuracy: 0.7299 - val_loss: 0.5434 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5221 - accuracy: 0.7404 - val_loss: 0.5443 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7466 - val_loss: 0.5412 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7558 - val_loss: 0.5459 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4876 - accuracy: 0.7633
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4876 - accuracy: 0.7632 - val_loss: 0.5470 - val_accuracy: 0.7209 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47357886275676325
Confusion Matrix :
 [[3179  868]
 [1272 2775]]
Accuracy on test set:    0.735606622189276
Sensitivity:    0.6856931060044478 	 Specificity:    0.7855201383741043
Precision  : 0.7617348339280813
Area Under Curve:    0.7356066221892761
(8094, 2560) (8094,)
Mean MCC = 0.4304 + 0.0181 and Mean AUC = 0.7145 + 0.0087
Mean Sensitivity = 0.7233 + 0.0356 and Mean Specificity = 0.7057 + 0.0418 and Mean Accuracy = 0.7145 + 0.0087
Mean Precision = 0.7123 + 0.0217





Seed   : 644386
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5891 - accuracy: 0.6839 - val_loss: 0.5601 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7251 - val_loss: 0.5519 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7357 - val_loss: 0.5474 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7434 - val_loss: 0.5514 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7505 - val_loss: 0.5486 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7576 - val_loss: 0.5504 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4854 - accuracy: 0.7659 - val_loss: 0.5575 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7736 - val_loss: 0.5654 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4622 - accuracy: 0.7805 - val_loss: 0.5763 - val_accuracy: 0.7038 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4508 - accuracy: 0.7869 - val_loss: 0.5671 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4354 - accuracy: 0.7981
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4362 - accuracy: 0.7974 - val_loss: 0.5702 - val_accuracy: 0.7094 - lr: 0.0010
253/253 [==============================] - 0s 764us/step
Independent Testing Matthews Correlation:  0.39820341032592693
Confusion Matrix :
 [[2665 1383]
 [1058 2989]]
Accuracy on test set:    0.6984558369363805
Sensitivity:    0.7385717815665925 	 Specificity:    0.6583498023715415
Precision  : 0.6836688014638609
Area Under Curve:    0.698460791969067
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5891 - accuracy: 0.6833 - val_loss: 0.5568 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7219 - val_loss: 0.5565 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7341 - val_loss: 0.5542 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7424 - val_loss: 0.5482 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7498 - val_loss: 0.5493 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7583 - val_loss: 0.5520 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7639 - val_loss: 0.5544 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.7719 - val_loss: 0.5594 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4621 - accuracy: 0.7808 - val_loss: 0.5642 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4493 - accuracy: 0.7879 - val_loss: 0.5654 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 11/400
252/257 [============================>.] - ETA: 0s - loss: 0.4381 - accuracy: 0.7946
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4385 - accuracy: 0.7944 - val_loss: 0.5680 - val_accuracy: 0.7071 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4160045660017694
Confusion Matrix :
 [[2787 1261]
 [1104 2943]]
Accuracy on test set:    0.7078443483631871
Sensitivity:    0.7272053372868792 	 Specificity:    0.6884881422924901
Precision  : 0.7000475737392959
Area Under Curve:    0.7078467397896847
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5863 - accuracy: 0.6847 - val_loss: 0.5488 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7232 - val_loss: 0.5434 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7335 - val_loss: 0.5398 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7398 - val_loss: 0.5383 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7498 - val_loss: 0.5388 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7553 - val_loss: 0.5408 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.7624 - val_loss: 0.5405 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4756 - accuracy: 0.7704 - val_loss: 0.5434 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4629 - accuracy: 0.7799 - val_loss: 0.5530 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4509 - accuracy: 0.7875 - val_loss: 0.5508 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4399 - accuracy: 0.7955 - val_loss: 0.5572 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4262 - accuracy: 0.8029
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4270 - accuracy: 0.8022 - val_loss: 0.5544 - val_accuracy: 0.7202 - lr: 0.0010
253/253 [==============================] - 0s 849us/step
Independent Testing Matthews Correlation:  0.42067886653270764
Confusion Matrix :
 [[2905 1142]
 [1203 2845]]
Accuracy on test set:    0.7103150092649784
Sensitivity:    0.7028162055335968 	 Specificity:    0.7178156659253768
Precision  : 0.7135690995736143
Area Under Curve:    0.7103159357294868
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5853 - accuracy: 0.6864 - val_loss: 0.5478 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7217 - val_loss: 0.5391 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.7356 - val_loss: 0.5372 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5140 - accuracy: 0.7431 - val_loss: 0.5372 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7527 - val_loss: 0.5397 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4897 - accuracy: 0.7614 - val_loss: 0.5381 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7699 - val_loss: 0.5402 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4668 - accuracy: 0.7768
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4668 - accuracy: 0.7768 - val_loss: 0.5414 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 755us/step
Independent Testing Matthews Correlation:  0.4229144915207479
Confusion Matrix :
 [[2913 1134]
 [1202 2846]]
Accuracy on test set:    0.7114268066707844
Sensitivity:    0.7030632411067194 	 Specificity:    0.7197924388435878
Precision  : 0.7150753768844221
Area Under Curve:    0.7114278399751536
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5858 - accuracy: 0.6856 - val_loss: 0.5562 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7237 - val_loss: 0.5467 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7351 - val_loss: 0.5439 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7421 - val_loss: 0.5446 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7506 - val_loss: 0.5461 - val_accuracy: 0.7218 - lr: 0.0010

Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4918 - accuracy: 0.7596 - val_loss: 0.5475 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - ETA: 0s - loss: 0.4799 - accuracy: 0.7682
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7682 - val_loss: 0.5464 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 953us/step
Independent Testing Matthews Correlation:  0.41731114310496664
Confusion Matrix :
 [[2932 1115]
 [1244 2803]]
Accuracy on test set:    0.7085495428712627
Sensitivity:    0.6926118112181863 	 Specificity:    0.724487274524339
Precision  : 0.7154160285860133
Area Under Curve:    0.7085495428712627
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5872 - accuracy: 0.6852 - val_loss: 0.5617 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7243 - val_loss: 0.5540 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7347 - val_loss: 0.5495 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7426 - val_loss: 0.5548 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7508 - val_loss: 0.5505 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7596 - val_loss: 0.5495 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7676 - val_loss: 0.5578 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.7764 - val_loss: 0.5624 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4587 - accuracy: 0.7817 - val_loss: 0.5587 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4442 - accuracy: 0.7928 - val_loss: 0.5713 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 11/400
249/257 [============================>.] - ETA: 0s - loss: 0.4336 - accuracy: 0.8006
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4332 - accuracy: 0.8007 - val_loss: 0.5782 - val_accuracy: 0.7111 - lr: 0.0010
253/253 [==============================] - 0s 918us/step
Independent Testing Matthews Correlation:  0.4175118616740135
Confusion Matrix :
 [[2811 1236]
 [1122 2925]]
Accuracy on test set:    0.7086730911786508
Sensitivity:    0.7227575982209044 	 Specificity:    0.6945885841363973
Precision  : 0.702956020187455
Area Under Curve:    0.7086730911786508
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5880 - accuracy: 0.6834 - val_loss: 0.5539 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7242 - val_loss: 0.5468 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7345 - val_loss: 0.5464 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7401 - val_loss: 0.5459 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7499 - val_loss: 0.5435 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.7569 - val_loss: 0.5479 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7644 - val_loss: 0.5531 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4739 - accuracy: 0.7735
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4743 - accuracy: 0.7734 - val_loss: 0.5585 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 713us/step
Independent Testing Matthews Correlation:  0.41455797260922667
Confusion Matrix :
 [[2953 1094]
 [1277 2770]]
Accuracy on test set:    0.7070669631826044
Sensitivity:    0.6844576229305659 	 Specificity:    0.729676303434643
Precision  : 0.7168737060041408
Area Under Curve:    0.7070669631826044
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5886 - accuracy: 0.6825 - val_loss: 0.5552 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7215 - val_loss: 0.5516 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7356 - val_loss: 0.5482 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7423 - val_loss: 0.5416 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7515 - val_loss: 0.5495 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7607 - val_loss: 0.5402 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7667 - val_loss: 0.5441 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7761 - val_loss: 0.5582 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.7835 - val_loss: 0.5519 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4417 - accuracy: 0.7939 - val_loss: 0.5613 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4291 - accuracy: 0.8001
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4293 - accuracy: 0.8000 - val_loss: 0.5709 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4462200660160431
Confusion Matrix :
 [[2734 1313]
 [ 936 3111]]
Accuracy on test set:    0.7221398566839634
Sensitivity:    0.7687175685693106 	 Specificity:    0.6755621447986162
Precision  : 0.7032097649186256
Area Under Curve:    0.7221398566839634
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5938 - accuracy: 0.6776 - val_loss: 0.5565 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5499 - accuracy: 0.7193 - val_loss: 0.5509 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5363 - accuracy: 0.7297 - val_loss: 0.5442 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5239 - accuracy: 0.7383 - val_loss: 0.5456 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.7442 - val_loss: 0.5466 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7552 - val_loss: 0.5471 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4886 - accuracy: 0.7618 - val_loss: 0.5505 - val_accuracy: 0.7202 - lr: 0.0010

Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7719 - val_loss: 0.5523 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4637 - accuracy: 0.7792 - val_loss: 0.5555 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4507 - accuracy: 0.7883 - val_loss: 0.5590 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4380 - accuracy: 0.7966 - val_loss: 0.5718 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 12/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4249 - accuracy: 0.8039
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4253 - accuracy: 0.8037 - val_loss: 0.5724 - val_accuracy: 0.7148 - lr: 0.0010
253/253 [==============================] - 0s 729us/step
Independent Testing Matthews Correlation:  0.48298323703142554
Confusion Matrix :
 [[3052  995]
 [1098 2949]]
Accuracy on test set:    0.7414133926365208
Sensitivity:    0.7286879169755375 	 Specificity:    0.7541388682975043
Precision  : 0.7477180527383367
Area Under Curve:    0.741413392636521
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5931 - accuracy: 0.6800 - val_loss: 0.5514 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5500 - accuracy: 0.7194 - val_loss: 0.5522 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5348 - accuracy: 0.7302 - val_loss: 0.5479 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5235 - accuracy: 0.7387 - val_loss: 0.5447 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5120 - accuracy: 0.7466 - val_loss: 0.5481 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7569 - val_loss: 0.5480 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4900 - accuracy: 0.7632 - val_loss: 0.5450 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4763 - accuracy: 0.7707 - val_loss: 0.5521 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4639 - accuracy: 0.7791
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4638 - accuracy: 0.7794 - val_loss: 0.5551 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 844us/step
Independent Testing Matthews Correlation:  0.4741852905459925
Confusion Matrix :
 [[3075  972]
 [1158 2889]]
Accuracy on test set:    0.7368421052631579
Sensitivity:    0.7138621200889548 	 Specificity:    0.759822090437361
Precision  : 0.7482517482517482
Area Under Curve:    0.7368421052631579
(8094, 2560) (8094,)
Mean MCC = 0.4311 + 0.0263 and Mean AUC = 0.7153 + 0.0131
Mean Sensitivity = 0.7183 + 0.0234 and Mean Specificity = 0.7123 + 0.0311 and Mean Accuracy = 0.7153 + 0.0131
Mean Precision = 0.7147 + 0.0192





Seed   : 280681
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5910 - accuracy: 0.6809 - val_loss: 0.5623 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7219 - val_loss: 0.5529 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7327 - val_loss: 0.5534 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7404 - val_loss: 0.5478 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7477 - val_loss: 0.5487 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7568 - val_loss: 0.5466 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 7/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4897 - accuracy: 0.7628
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4900 - accuracy: 0.7628 - val_loss: 0.5567 - val_accuracy: 0.7113 - lr: 0.0010
253/253 [==============================] - 0s 707us/step
Independent Testing Matthews Correlation:  0.415541341924557
Confusion Matrix :
 [[2717 1331]
 [1039 3008]]
Accuracy on test set:    0.7072266831377394
Sensitivity:    0.7432666172473437 	 Specificity:    0.6711956521739131
Precision  : 0.6932472920027656
Area Under Curve:    0.7072311347106285
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5867 - accuracy: 0.6846 - val_loss: 0.5566 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7250 - val_loss: 0.5485 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7369 - val_loss: 0.5495 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.7447 - val_loss: 0.5447 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7538 - val_loss: 0.5514 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.7610 - val_loss: 0.5544 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4764 - accuracy: 0.7698 - val_loss: 0.5582 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4641 - accuracy: 0.7789 - val_loss: 0.5561 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4509 - accuracy: 0.7883 - val_loss: 0.5594 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4377 - accuracy: 0.7979 - val_loss: 0.5705 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4279 - accuracy: 0.8022 - val_loss: 0.5744 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4153 - accuracy: 0.8092 - val_loss: 0.5726 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4030 - accuracy: 0.8180 - val_loss: 0.5830 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 14/400
256/257 [============================>.] - ETA: 0s - loss: 0.3903 - accuracy: 0.8232
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3903 - accuracy: 0.8232 - val_loss: 0.5990 - val_accuracy: 0.7067 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39732979057638257
Confusion Matrix :
 [[2769 1279]
 [1161 2886]]
Accuracy on test set:    0.6985793699814701
Sensitivity:    0.7131208302446257 	 Specificity:    0.6840415019762845
Precision  : 0.6929171668667466
Area Under Curve:    0.6985811661104553
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.6821 - val_loss: 0.5537 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7205 - val_loss: 0.5441 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7342 - val_loss: 0.5428 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7398 - val_loss: 0.5413 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7494 - val_loss: 0.5402 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7573 - val_loss: 0.5440 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7642 - val_loss: 0.5473 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4750 - accuracy: 0.7734 - val_loss: 0.5463 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4631 - accuracy: 0.7814 - val_loss: 0.5560 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4504 - accuracy: 0.7881 - val_loss: 0.5568 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 11/400
256/257 [============================>.] - ETA: 0s - loss: 0.4369 - accuracy: 0.7982
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4369 - accuracy: 0.7982 - val_loss: 0.5554 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 840us/step
Independent Testing Matthews Correlation:  0.4098835129542596
Confusion Matrix :
 [[2902 1145]
 [1244 2804]]
Accuracy on test set:    0.7048795552810376
Sensitivity:    0.6926877470355731 	 Specificity:    0.7170743760810477
Precision  : 0.7100531780197519
Area Under Curve:    0.7048810615583103
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5862 - accuracy: 0.6846 - val_loss: 0.5509 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7205 - val_loss: 0.5383 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7347 - val_loss: 0.5393 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7425 - val_loss: 0.5395 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7494 - val_loss: 0.5355 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7597 - val_loss: 0.5365 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4834 - accuracy: 0.7671
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7674 - val_loss: 0.5461 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4040670071848111
Confusion Matrix :
 [[2665 1382]
 [1036 3012]]
Accuracy on test set:    0.7012970969734404
Sensitivity:    0.7440711462450593 	 Specificity:    0.6585124783790463
Precision  : 0.6854802002730996
Area Under Curve:    0.7012918123120527
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5855 - accuracy: 0.6853 - val_loss: 0.5566 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7215 - val_loss: 0.5579 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7341 - val_loss: 0.5473 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7397 - val_loss: 0.5494 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7475 - val_loss: 0.5475 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7532 - val_loss: 0.5484 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7644 - val_loss: 0.5530 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4730 - accuracy: 0.7728
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4730 - accuracy: 0.7729 - val_loss: 0.5572 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4381216121235543
Confusion Matrix :
 [[2929 1118]
 [1156 2891]]
Accuracy on test set:    0.7190511489992587
Sensitivity:    0.7143563133185076 	 Specificity:    0.7237459846800098
Precision  : 0.7211274632077825
Area Under Curve:    0.7190511489992587
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5925 - accuracy: 0.6800 - val_loss: 0.5604 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7219 - val_loss: 0.5503 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7341 - val_loss: 0.5506 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7424 - val_loss: 0.5472 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7497 - val_loss: 0.5476 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7562 - val_loss: 0.5482 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7648 - val_loss: 0.5530 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4729 - accuracy: 0.7741 - val_loss: 0.5544 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.7824 - val_loss: 0.5585 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4471 - accuracy: 0.7897
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4471 - accuracy: 0.7896 - val_loss: 0.5623 - val_accuracy: 0.7179 - lr: 0.0010
253/253 [==============================] - 0s 785us/step
Independent Testing Matthews Correlation:  0.4317134248710153
Confusion Matrix :
 [[2871 1176]
 [1124 2923]]
Accuracy on test set:    0.7158388930071659
Sensitivity:    0.7222634049913517 	 Specificity:    0.7094143810229799
Precision  : 0.71310075628202
Area Under Curve:    0.715838893007166
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5880 - accuracy: 0.6833 - val_loss: 0.5547 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7200 - val_loss: 0.5488 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7343 - val_loss: 0.5456 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7427 - val_loss: 0.5428 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7526 - val_loss: 0.5427 - val_accuracy: 0.7175 - lr: 0.0010

Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7594 - val_loss: 0.5448 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4779 - accuracy: 0.7706 - val_loss: 0.5457 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4638 - accuracy: 0.7784 - val_loss: 0.5550 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4510 - accuracy: 0.7890 - val_loss: 0.5567 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4384 - accuracy: 0.7964 - val_loss: 0.5711 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 11/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4251 - accuracy: 0.8023
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4254 - accuracy: 0.8022 - val_loss: 0.5698 - val_accuracy: 0.7119 - lr: 0.0010
253/253 [==============================] - 0s 959us/step
Independent Testing Matthews Correlation:  0.42638329938551794
Confusion Matrix :
 [[2721 1326]
 [1001 3046]]
Accuracy on test set:    0.7125030887076848
Sensitivity:    0.752656288608846 	 Specificity:    0.6723498888065234
Precision  : 0.6967063129002745
Area Under Curve:    0.7125030887076848
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5939 - accuracy: 0.6793 - val_loss: 0.5579 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5497 - accuracy: 0.7198 - val_loss: 0.5511 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5348 - accuracy: 0.7316 - val_loss: 0.5452 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5219 - accuracy: 0.7392 - val_loss: 0.5598 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7481 - val_loss: 0.5449 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.7548 - val_loss: 0.5450 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7634 - val_loss: 0.5521 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7752 - val_loss: 0.5473 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4578 - accuracy: 0.7844 - val_loss: 0.5528 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4441 - accuracy: 0.7924 - val_loss: 0.5522 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4311 - accuracy: 0.8018
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4317 - accuracy: 0.8014 - val_loss: 0.5626 - val_accuracy: 0.7127 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4267827606295458
Confusion Matrix :
 [[2917 1130]
 [1190 2857]]
Accuracy on test set:    0.713367926859402
Sensitivity:    0.7059550284161107 	 Specificity:    0.7207808253026934
Precision  : 0.7165788813644344
Area Under Curve:    0.713367926859402
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5918 - accuracy: 0.6794 - val_loss: 0.5568 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5507 - accuracy: 0.7181 - val_loss: 0.5467 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5339 - accuracy: 0.7314 - val_loss: 0.5450 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5230 - accuracy: 0.7381 - val_loss: 0.5421 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5133 - accuracy: 0.7446 - val_loss: 0.5451 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7550 - val_loss: 0.5451 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7601 - val_loss: 0.5464 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4801 - accuracy: 0.7696 - val_loss: 0.5496 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4685 - accuracy: 0.7783
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4688 - accuracy: 0.7782 - val_loss: 0.5481 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 786us/step
Independent Testing Matthews Correlation:  0.46210183352074463
Confusion Matrix :
 [[2935 1112]
 [1065 2982]]
Accuracy on test set:    0.731035334815913
Sensitivity:    0.7368421052631579 	 Specificity:    0.7252285643686681
Precision  : 0.7283829995114802
Area Under Curve:    0.7310353348159131
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5984 - accuracy: 0.6762 - val_loss: 0.5664 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5535 - accuracy: 0.7175 - val_loss: 0.5497 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5392 - accuracy: 0.7297 - val_loss: 0.5494 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7362 - val_loss: 0.5527 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7421 - val_loss: 0.5569 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7479 - val_loss: 0.5504 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4996 - accuracy: 0.7570
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7568 - val_loss: 0.5520 - val_accuracy: 0.7098 - lr: 0.0010
253/253 [==============================] - 0s 832us/step
Independent Testing Matthews Correlation:  0.4850349778760001
Confusion Matrix :
 [[2942 1105]
 [ 980 3067]]
Accuracy on test set:    0.7424017790956264
Sensitivity:    0.75784531751915 	 Specificity:    0.7269582406721028
Precision  : 0.7351390220517737
Area Under Curve:    0.7424017790956263
(8094, 2560) (8094,)
Mean MCC = 0.4297 + 0.0255 and Mean AUC = 0.7146 + 0.0129
Mean Sensitivity = 0.7283 + 0.0206 and Mean Specificity = 0.7009 + 0.0251 and Mean Accuracy = 0.7146 + 0.0129
Mean Precision = 0.7093 + 0.0158





Seed   : 851044
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5847 - accuracy: 0.6888 - val_loss: 0.5556 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5422 - accuracy: 0.7255 - val_loss: 0.5472 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5265 - accuracy: 0.7358 - val_loss: 0.5469 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7447 - val_loss: 0.5470 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7541 - val_loss: 0.5475 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7597 - val_loss: 0.5519 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4797 - accuracy: 0.7679
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7677 - val_loss: 0.5507 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40413026284417525
Confusion Matrix :
 [[2714 1334]
 [1081 2966]]
Accuracy on test set:    0.701667696108709
Sensitivity:    0.7328885594267358 	 Specificity:    0.6704545454545454
Precision  : 0.6897674418604651
Area Under Curve:    0.7016715524406406
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5836 - accuracy: 0.6888 - val_loss: 0.5552 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7216 - val_loss: 0.5507 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7349 - val_loss: 0.5510 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7419 - val_loss: 0.5459 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7506 - val_loss: 0.5478 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7584 - val_loss: 0.5611 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7649 - val_loss: 0.5548 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4740 - accuracy: 0.7729 - val_loss: 0.5554 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4608 - accuracy: 0.7809 - val_loss: 0.5556 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4490 - accuracy: 0.7892 - val_loss: 0.5581 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4377 - accuracy: 0.7962 - val_loss: 0.5731 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 12/400
250/257 [============================>.] - ETA: 0s - loss: 0.4265 - accuracy: 0.8020
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4264 - accuracy: 0.8020 - val_loss: 0.5717 - val_accuracy: 0.7098 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41112683426261715
Confusion Matrix :
 [[2805 1243]
 [1141 2906]]
Accuracy on test set:    0.7054972205064854
Sensitivity:    0.7180627625401532 	 Specificity:    0.6929347826086957
Precision  : 0.700409737286093
Area Under Curve:    0.7054987725744245
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5882 - accuracy: 0.6819 - val_loss: 0.5418 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7224 - val_loss: 0.5359 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7346 - val_loss: 0.5352 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5168 - accuracy: 0.7420 - val_loss: 0.5389 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5054 - accuracy: 0.7502 - val_loss: 0.5368 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7597 - val_loss: 0.5360 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4825 - accuracy: 0.7680 - val_loss: 0.5361 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4694 - accuracy: 0.7761 - val_loss: 0.5424 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4562 - accuracy: 0.7826 - val_loss: 0.5462 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4430 - accuracy: 0.7925
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4439 - accuracy: 0.7920 - val_loss: 0.5513 - val_accuracy: 0.7255 - lr: 0.0010
253/253 [==============================] - 0s 836us/step
Independent Testing Matthews Correlation:  0.4317913133283868
Confusion Matrix :
 [[2868 1179]
 [1121 2927]]
Accuracy on test set:    0.7158739962940086
Sensitivity:    0.7230731225296443 	 Specificity:    0.7086730911786508
Precision  : 0.7128592303945446
Area Under Curve:    0.7158731068541476
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5853 - accuracy: 0.6843 - val_loss: 0.5514 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7235 - val_loss: 0.5410 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7363 - val_loss: 0.5351 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5149 - accuracy: 0.7423 - val_loss: 0.5344 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7519 - val_loss: 0.5346 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4908 - accuracy: 0.7607 - val_loss: 0.5384 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.7703 - val_loss: 0.5399 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4632 - accuracy: 0.7799
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4637 - accuracy: 0.7796 - val_loss: 0.5411 - val_accuracy: 0.7261 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41277295636691613
Confusion Matrix :
 [[2781 1266]
 [1112 2936]]
Accuracy on test set:    0.7062384187770229
Sensitivity:    0.7252964426877471 	 Specificity:    0.687175685693106
Precision  : 0.6987148976677773
Area Under Curve:    0.7062360641904264
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5889 - accuracy: 0.6814 - val_loss: 0.5487 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7210 - val_loss: 0.5462 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7310 - val_loss: 0.5442 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7379 - val_loss: 0.5404 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5108 - accuracy: 0.7465 - val_loss: 0.5413 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7512 - val_loss: 0.5444 - val_accuracy: 0.7215 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4923 - accuracy: 0.7599 - val_loss: 0.5457 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7646 - val_loss: 0.5493 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7752 - val_loss: 0.5594 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4595 - accuracy: 0.7817
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4595 - accuracy: 0.7817 - val_loss: 0.5607 - val_accuracy: 0.7213 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4205420840765254
Confusion Matrix :
 [[2735 1312]
 [1037 3010]]
Accuracy on test set:    0.7097850259451446
Sensitivity:    0.7437608104768965 	 Specificity:    0.6758092414133926
Precision  : 0.6964368347987043
Area Under Curve:    0.7097850259451446
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5887 - accuracy: 0.6815 - val_loss: 0.5496 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7217 - val_loss: 0.5450 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7350 - val_loss: 0.5496 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7425 - val_loss: 0.5440 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7492 - val_loss: 0.5431 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
251/257 [============================>.] - ETA: 0s - loss: 0.4952 - accuracy: 0.7589
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4954 - accuracy: 0.7586 - val_loss: 0.5494 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 965us/step
Independent Testing Matthews Correlation:  0.430003717700616
Confusion Matrix :
 [[2601 1446]
 [ 878 3169]]
Accuracy on test set:    0.7128737336298493
Sensitivity:    0.7830491722263405 	 Specificity:    0.6426982950333581
Precision  : 0.6866738894907909
Area Under Curve:    0.7128737336298492
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5924 - accuracy: 0.6805 - val_loss: 0.5492 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7214 - val_loss: 0.5441 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7327 - val_loss: 0.5419 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7409 - val_loss: 0.5421 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7497 - val_loss: 0.5420 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7580 - val_loss: 0.5435 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4810 - accuracy: 0.7693
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7693 - val_loss: 0.5459 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 903us/step
Independent Testing Matthews Correlation:  0.43002595261359833
Confusion Matrix :
 [[2855 1192]
 [1115 2932]]
Accuracy on test set:    0.7149740548554485
Sensitivity:    0.724487274524339 	 Specificity:    0.705460835186558
Precision  : 0.7109602327837051
Area Under Curve:    0.7149740548554485
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5890 - accuracy: 0.6839 - val_loss: 0.5493 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7225 - val_loss: 0.5440 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7333 - val_loss: 0.5411 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7414 - val_loss: 0.5398 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7506 - val_loss: 0.5473 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7576 - val_loss: 0.5402 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7653 - val_loss: 0.5411 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.7760 - val_loss: 0.5475 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4562 - accuracy: 0.7854 - val_loss: 0.5567 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4445 - accuracy: 0.7915 - val_loss: 0.5538 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 11/400
251/257 [============================>.] - ETA: 0s - loss: 0.4331 - accuracy: 0.8002
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4331 - accuracy: 0.8000 - val_loss: 0.5647 - val_accuracy: 0.7200 - lr: 0.0010
253/253 [==============================] - 0s 809us/step
Independent Testing Matthews Correlation:  0.4384365623928364
Confusion Matrix :
 [[2989 1058]
 [1216 2831]]
Accuracy on test set:    0.7190511489992587
Sensitivity:    0.6995305164319249 	 Specificity:    0.7385717815665925
Precision  : 0.7279506299820006
Area Under Curve:    0.7190511489992587
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5899 - accuracy: 0.6834 - val_loss: 0.5563 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7210 - val_loss: 0.5575 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5327 - accuracy: 0.7311 - val_loss: 0.5477 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7410 - val_loss: 0.5472 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5109 - accuracy: 0.7474 - val_loss: 0.5476 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7547 - val_loss: 0.5522 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4893 - accuracy: 0.7608 - val_loss: 0.5511 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4777 - accuracy: 0.7719 - val_loss: 0.5554 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4658 - accuracy: 0.7786 - val_loss: 0.5558 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4539 - accuracy: 0.7869
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4537 - accuracy: 0.7870 - val_loss: 0.5650 - val_accuracy: 0.7171 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.45645819173624247
Confusion Matrix :
 [[3022 1025]
 [1176 2871]]
Accuracy on test set:    0.7280701754385965
Sensitivity:    0.7094143810229799 	 Specificity:    0.746725969854213
Precision  : 0.7369096509240246
Area Under Curve:    0.7280701754385965
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5931 - accuracy: 0.6809 - val_loss: 0.5549 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7196 - val_loss: 0.5515 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5342 - accuracy: 0.7289 - val_loss: 0.5491 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5220 - accuracy: 0.7397 - val_loss: 0.5518 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7479 - val_loss: 0.5504 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4999 - accuracy: 0.7550 - val_loss: 0.5633 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4885 - accuracy: 0.7629
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.7629 - val_loss: 0.5567 - val_accuracy: 0.7156 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4828681950182186
Confusion Matrix :
 [[2974 1073]
 [1020 3027]]
Accuracy on test set:    0.7414133926365208
Sensitivity:    0.7479614529280949 	 Specificity:    0.7348653323449469
Precision  : 0.7382926829268293
Area Under Curve:    0.741413392636521
(8094, 2560) (8094,)
Mean MCC = 0.4318 + 0.0222 and Mean AUC = 0.7155 + 0.0112
Mean Sensitivity = 0.7308 + 0.0222 and Mean Specificity = 0.7003 + 0.0315 and Mean Accuracy = 0.7155 + 0.0112
Mean Precision = 0.7099 + 0.0179





Seed   : 448604
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5820 - accuracy: 0.6866 - val_loss: 0.5600 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5410 - accuracy: 0.7252 - val_loss: 0.5505 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5240 - accuracy: 0.7369 - val_loss: 0.5487 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5139 - accuracy: 0.7448 - val_loss: 0.5505 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5040 - accuracy: 0.7527 - val_loss: 0.5550 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4923 - accuracy: 0.7610 - val_loss: 0.5578 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7653 - val_loss: 0.5544 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4728 - accuracy: 0.7751 - val_loss: 0.5565 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4613 - accuracy: 0.7805 - val_loss: 0.5605 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4513 - accuracy: 0.7877 - val_loss: 0.5741 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4390 - accuracy: 0.7967 - val_loss: 0.5861 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4257 - accuracy: 0.8038 - val_loss: 0.5812 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 13/400
250/257 [============================>.] - ETA: 0s - loss: 0.4158 - accuracy: 0.8103
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4162 - accuracy: 0.8101 - val_loss: 0.5877 - val_accuracy: 0.7062 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3932631948353081
Confusion Matrix :
 [[2855 1193]
 [1263 2784]]
Accuracy on test set:    0.696602841260037
Sensitivity:    0.6879169755374351 	 Specificity:    0.7052865612648221
Precision  : 0.7000251445813427
Area Under Curve:    0.6966017684011286
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5869 - accuracy: 0.6842 - val_loss: 0.5524 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5412 - accuracy: 0.7245 - val_loss: 0.5509 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5256 - accuracy: 0.7357 - val_loss: 0.5495 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5146 - accuracy: 0.7442 - val_loss: 0.5442 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.7530 - val_loss: 0.5456 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4892 - accuracy: 0.7612 - val_loss: 0.5466 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7723 - val_loss: 0.5500 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4624 - accuracy: 0.7802 - val_loss: 0.5557 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4511 - accuracy: 0.7865 - val_loss: 0.5606 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4366 - accuracy: 0.7962 - val_loss: 0.5637 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4228 - accuracy: 0.8038 - val_loss: 0.5638 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 12/400
256/257 [============================>.] - ETA: 0s - loss: 0.4100 - accuracy: 0.8108
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4101 - accuracy: 0.8108 - val_loss: 0.5923 - val_accuracy: 0.7100 - lr: 0.0010
253/253 [==============================] - 0s 978us/step
Independent Testing Matthews Correlation:  0.4193461616910333
Confusion Matrix :
 [[2539 1509]
 [ 863 3184]]
Accuracy on test set:    0.7069796170475602
Sensitivity:    0.7867556214479862 	 Specificity:    0.6272233201581028
Precision  : 0.6784572767952269
Area Under Curve:    0.7069894708030445
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5858 - accuracy: 0.6861 - val_loss: 0.5464 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7225 - val_loss: 0.5387 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7324 - val_loss: 0.5383 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7414 - val_loss: 0.5349 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7489 - val_loss: 0.5353 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7581 - val_loss: 0.5394 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4836 - accuracy: 0.7661
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7655 - val_loss: 0.5397 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43272950610878047
Confusion Matrix :
 [[2667 1380]
 [ 927 3121]]
Accuracy on test set:    0.7150092649783817
Sensitivity:    0.770998023715415 	 Specificity:    0.6590066716085989
Precision  : 0.6934014663408131
Area Under Curve:    0.715002347662007
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5860 - accuracy: 0.6862 - val_loss: 0.5481 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7212 - val_loss: 0.5412 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7318 - val_loss: 0.5400 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7396 - val_loss: 0.5404 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7520 - val_loss: 0.5337 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7568 - val_loss: 0.5389 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7667 - val_loss: 0.5384 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4718 - accuracy: 0.7749 - val_loss: 0.5401 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4584 - accuracy: 0.7833 - val_loss: 0.5468 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4452 - accuracy: 0.7918 - val_loss: 0.5492 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4330 - accuracy: 0.7981 - val_loss: 0.5519 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4198 - accuracy: 0.8069
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4196 - accuracy: 0.8070 - val_loss: 0.5656 - val_accuracy: 0.7246 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42650894930188804
Confusion Matrix :
 [[2644 1403]
 [ 930 3118]]
Accuracy on test set:    0.7117974058060531
Sensitivity:    0.7702569169960475 	 Specificity:    0.6533234494687423
Precision  : 0.6896704268967042
Area Under Curve:    0.711790183232395
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5887 - accuracy: 0.6851 - val_loss: 0.5518 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7221 - val_loss: 0.5480 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7336 - val_loss: 0.5471 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7402 - val_loss: 0.5521 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7492 - val_loss: 0.5430 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7555 - val_loss: 0.5427 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7642 - val_loss: 0.5459 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4727 - accuracy: 0.7729 - val_loss: 0.5561 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4618 - accuracy: 0.7798 - val_loss: 0.5571 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4475 - accuracy: 0.7892
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4473 - accuracy: 0.7892 - val_loss: 0.5621 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 837us/step
Independent Testing Matthews Correlation:  0.40652741528198877
Confusion Matrix :
 [[2950 1097]
 [1307 2740]]
Accuracy on test set:    0.7029898690387941
Sensitivity:    0.6770447244872745 	 Specificity:    0.7289350135903138
Precision  : 0.7140995569455304
Area Under Curve:    0.7029898690387943
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5898 - accuracy: 0.6815 - val_loss: 0.5479 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7228 - val_loss: 0.5452 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7324 - val_loss: 0.5392 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7404 - val_loss: 0.5377 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7495 - val_loss: 0.5409 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7578 - val_loss: 0.5406 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4833 - accuracy: 0.7667
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7668 - val_loss: 0.5435 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42282963589868616
Confusion Matrix :
 [[2954 1093]
 [1244 2803]]
Accuracy on test set:    0.7112676056338029
Sensitivity:    0.6926118112181863 	 Specificity:    0.7299234000494194
Precision  : 0.7194558521560575
Area Under Curve:    0.7112676056338028
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5930 - accuracy: 0.6800 - val_loss: 0.5475 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5482 - accuracy: 0.7204 - val_loss: 0.5399 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7328 - val_loss: 0.5360 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5212 - accuracy: 0.7389 - val_loss: 0.5398 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5133 - accuracy: 0.7446 - val_loss: 0.5344 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7522 - val_loss: 0.5377 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7580 - val_loss: 0.5455 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4829 - accuracy: 0.7654
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.7651 - val_loss: 0.5386 - val_accuracy: 0.7229 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4413145674632243
Confusion Matrix :
 [[2917 1130]
 [1131 2916]]
Accuracy on test set:    0.7206572769953051
Sensitivity:    0.720533728687917 	 Specificity:    0.7207808253026934
Precision  : 0.7207118141374197
Area Under Curve:    0.7206572769953051
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5915 - accuracy: 0.6807 - val_loss: 0.5484 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5480 - accuracy: 0.7198 - val_loss: 0.5418 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7309 - val_loss: 0.5408 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7394 - val_loss: 0.5402 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.7469 - val_loss: 0.5370 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7567 - val_loss: 0.5331 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7653 - val_loss: 0.5360 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7759 - val_loss: 0.5397 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4554 - accuracy: 0.7833 - val_loss: 0.5453 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4436 - accuracy: 0.7910 - val_loss: 0.5506 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 11/400
250/257 [============================>.] - ETA: 0s - loss: 0.4293 - accuracy: 0.8017
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4291 - accuracy: 0.8017 - val_loss: 0.5596 - val_accuracy: 0.7167 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4415320143979616
Confusion Matrix :
 [[2853 1194]
 [1067 2980]]
Accuracy on test set:    0.7206572769953051
Sensitivity:    0.7363479120336052 	 Specificity:    0.7049666419570052
Precision  : 0.7139434595112601
Area Under Curve:    0.7206572769953052
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5960 - accuracy: 0.6752 - val_loss: 0.5560 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5502 - accuracy: 0.7190 - val_loss: 0.5459 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7323 - val_loss: 0.5403 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5207 - accuracy: 0.7407 - val_loss: 0.5373 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7514 - val_loss: 0.5390 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7605 - val_loss: 0.5535 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7690 - val_loss: 0.5399 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4672 - accuracy: 0.7786 - val_loss: 0.5427 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4531 - accuracy: 0.7862 - val_loss: 0.5429 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4395 - accuracy: 0.7965 - val_loss: 0.5495 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4277 - accuracy: 0.8038 - val_loss: 0.5517 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 3ms/step - loss: 0.4120 - accuracy: 0.8141 - val_loss: 0.5686 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - ETA: 0s - loss: 0.4008 - accuracy: 0.8183
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4008 - accuracy: 0.8183 - val_loss: 0.5834 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 713us/step
Independent Testing Matthews Correlation:  0.4485649662209903
Confusion Matrix :
 [[2759 1288]
 [ 950 3097]]
Accuracy on test set:    0.7234988880652335
Sensitivity:    0.7652582159624414 	 Specificity:    0.6817395601680257
Precision  : 0.7062713797035348
Area Under Curve:    0.7234988880652334
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5940 - accuracy: 0.6795 - val_loss: 0.5529 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5518 - accuracy: 0.7188 - val_loss: 0.5453 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5351 - accuracy: 0.7288 - val_loss: 0.5432 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5243 - accuracy: 0.7382 - val_loss: 0.5417 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5130 - accuracy: 0.7450 - val_loss: 0.5494 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7557 - val_loss: 0.5439 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.7636 - val_loss: 0.5449 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 8/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4759 - accuracy: 0.7713
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4769 - accuracy: 0.7712 - val_loss: 0.5508 - val_accuracy: 0.7142 - lr: 0.0010
253/253 [==============================] - 0s 752us/step
Independent Testing Matthews Correlation:  0.4665225247035376
Confusion Matrix :
 [[2976 1071]
 [1088 2959]]
Accuracy on test set:    0.7332592043489005
Sensitivity:    0.7311588831233012 	 Specificity:    0.7353595255744997
Precision  : 0.7342431761786601
Area Under Curve:    0.7332592043489005
(8094, 2560) (8094,)
Mean MCC = 0.4299 + 0.0201 and Mean AUC = 0.7143 + 0.0102
Mean Sensitivity = 0.7339 + 0.0370 and Mean Specificity = 0.6947 + 0.0356 and Mean Accuracy = 0.7143 + 0.0102
Mean Precision = 0.7070 + 0.0159





Seed   : 981033
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5850 - accuracy: 0.6866 - val_loss: 0.5596 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5416 - accuracy: 0.7265 - val_loss: 0.5528 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7353 - val_loss: 0.5515 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7430 - val_loss: 0.5502 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7504 - val_loss: 0.5494 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7568 - val_loss: 0.5576 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4883 - accuracy: 0.7633
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.7630 - val_loss: 0.5570 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4139156168704541
Confusion Matrix :
 [[2663 1385]
 [ 995 3052]]
Accuracy on test set:    0.7059913526868438
Sensitivity:    0.7541388682975043 	 Specificity:    0.6578557312252964
Precision  : 0.6878521523551949
Area Under Curve:    0.7059972997614004
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5871 - accuracy: 0.6845 - val_loss: 0.5572 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7247 - val_loss: 0.5536 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7342 - val_loss: 0.5512 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7406 - val_loss: 0.5493 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7477 - val_loss: 0.5521 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7571 - val_loss: 0.5515 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.7624 - val_loss: 0.5495 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4763 - accuracy: 0.7733 - val_loss: 0.5675 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4661 - accuracy: 0.7787
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.7785 - val_loss: 0.5571 - val_accuracy: 0.7091 - lr: 0.0010
253/253 [==============================] - 0s 791us/step
Independent Testing Matthews Correlation:  0.42201230863198147
Confusion Matrix :
 [[2728 1320]
 [1024 3023]]
Accuracy on test set:    0.710438542310068
Sensitivity:    0.7469730664689894 	 Specificity:    0.6739130434782609
Precision  : 0.6960626295187659
Area Under Curve:    0.7104430549736253
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5854 - accuracy: 0.6863 - val_loss: 0.5457 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7221 - val_loss: 0.5399 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7345 - val_loss: 0.5359 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7423 - val_loss: 0.5388 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.7499 - val_loss: 0.5388 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7586 - val_loss: 0.5401 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7671 - val_loss: 0.5407 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4675 - accuracy: 0.7769 - val_loss: 0.5441 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4550 - accuracy: 0.7857 - val_loss: 0.5472 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4411 - accuracy: 0.7934 - val_loss: 0.5520 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4269 - accuracy: 0.8016 - val_loss: 0.5608 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4165 - accuracy: 0.8082 - val_loss: 0.5767 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4007 - accuracy: 0.8186 - val_loss: 0.5783 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 14/400
246/257 [===========================>..] - ETA: 0s - loss: 0.3892 - accuracy: 0.8247
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3894 - accuracy: 0.8242 - val_loss: 0.5838 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40517696222392907
Confusion Matrix :
 [[3019 1028]
 [1386 2662]]
Accuracy on test set:    0.7017912291537987
Sensitivity:    0.657608695652174 	 Specificity:    0.7459846800098838
Precision  : 0.7214092140921409
Area Under Curve:    0.7017966878310289
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5898 - accuracy: 0.6833 - val_loss: 0.5481 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7217 - val_loss: 0.5410 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7330 - val_loss: 0.5406 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7401 - val_loss: 0.5382 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5106 - accuracy: 0.7478 - val_loss: 0.5458 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7559 - val_loss: 0.5438 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7648 - val_loss: 0.5413 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4750 - accuracy: 0.7728
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7725 - val_loss: 0.5432 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4253566512232973
Confusion Matrix :
 [[2782 1265]
 [1063 2985]]
Accuracy on test set:    0.7124150710315009
Sensitivity:    0.737401185770751 	 Specificity:    0.6874227823078823
Precision  : 0.7023529411764706
Area Under Curve:    0.7124119840393167
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5870 - accuracy: 0.6847 - val_loss: 0.5526 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7204 - val_loss: 0.5459 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7335 - val_loss: 0.5396 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5142 - accuracy: 0.7433 - val_loss: 0.5428 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7505 - val_loss: 0.5429 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.7588 - val_loss: 0.5500 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4785 - accuracy: 0.7686 - val_loss: 0.5532 - val_accuracy: 0.7212 - lr: 0.0010

Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4662 - accuracy: 0.7764 - val_loss: 0.5531 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4533 - accuracy: 0.7855 - val_loss: 0.5615 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4391 - accuracy: 0.7952
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4395 - accuracy: 0.7948 - val_loss: 0.5650 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4120409488925481
Confusion Matrix :
 [[2806 1241]
 [1139 2908]]
Accuracy on test set:    0.7059550284161107
Sensitivity:    0.7185569557697059 	 Specificity:    0.6933531010625155
Precision  : 0.7008917811520848
Area Under Curve:    0.7059550284161108
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5858 - accuracy: 0.6869 - val_loss: 0.5514 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7229 - val_loss: 0.5443 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7351 - val_loss: 0.5419 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7427 - val_loss: 0.5405 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7520 - val_loss: 0.5422 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7592 - val_loss: 0.5472 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4825 - accuracy: 0.7671 - val_loss: 0.5443 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7756 - val_loss: 0.5499 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4563 - accuracy: 0.7855 - val_loss: 0.5540 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4449 - accuracy: 0.7916 - val_loss: 0.5504 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4309 - accuracy: 0.8007 - val_loss: 0.5584 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4190 - accuracy: 0.8088 - val_loss: 0.5726 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4067 - accuracy: 0.8148 - val_loss: 0.5728 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 14/400
245/257 [===========================>..] - ETA: 0s - loss: 0.3919 - accuracy: 0.8239
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3921 - accuracy: 0.8237 - val_loss: 0.5830 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4099006518330795
Confusion Matrix :
 [[2756 1291]
 [1099 2948]]
Accuracy on test set:    0.7047195453422288
Sensitivity:    0.7284408203607611 	 Specificity:    0.6809982703236965
Precision  : 0.695447039396084
Area Under Curve:    0.7047195453422288
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5896 - accuracy: 0.6827 - val_loss: 0.5521 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7214 - val_loss: 0.5404 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7321 - val_loss: 0.5396 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 5ms/step - loss: 0.5202 - accuracy: 0.7396 - val_loss: 0.5406 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7498 - val_loss: 0.5397 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7556 - val_loss: 0.5479 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7652 - val_loss: 0.5466 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4706 - accuracy: 0.7739 - val_loss: 0.5515 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4562 - accuracy: 0.7834 - val_loss: 0.5648 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 10/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4427 - accuracy: 0.7938
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4434 - accuracy: 0.7931 - val_loss: 0.5562 - val_accuracy: 0.7245 - lr: 0.0010
253/253 [==============================] - 0s 835us/step
Independent Testing Matthews Correlation:  0.4309955646456207
Confusion Matrix :
 [[2862 1185]
 [1118 2929]]
Accuracy on test set:    0.7154682480850012
Sensitivity:    0.7237459846800098 	 Specificity:    0.7071905114899926
Precision  : 0.7119591638308216
Area Under Curve:    0.7154682480850012
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5920 - accuracy: 0.6828 - val_loss: 0.5468 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5480 - accuracy: 0.7198 - val_loss: 0.5427 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5342 - accuracy: 0.7299 - val_loss: 0.5369 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5238 - accuracy: 0.7375 - val_loss: 0.5378 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5137 - accuracy: 0.7442 - val_loss: 0.5401 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7532 - val_loss: 0.5369 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4905 - accuracy: 0.7599 - val_loss: 0.5394 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4794 - accuracy: 0.7680 - val_loss: 0.5428 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4660 - accuracy: 0.7779 - val_loss: 0.5444 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4532 - accuracy: 0.7865 - val_loss: 0.5515 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4405 - accuracy: 0.7948 - val_loss: 0.5523 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4285 - accuracy: 0.8023
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4282 - accuracy: 0.8024 - val_loss: 0.5613 - val_accuracy: 0.7249 - lr: 0.0010
253/253 [==============================] - 0s 837us/step
Independent Testing Matthews Correlation:  0.4381066314164936
Confusion Matrix :
 [[2901 1146]
 [1128 2919]]
Accuracy on test set:    0.7190511489992587
Sensitivity:    0.7212750185322461 	 Specificity:    0.7168272794662713
Precision  : 0.7180811808118082
Area Under Curve:    0.7190511489992587
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5895 - accuracy: 0.6842 - val_loss: 0.5507 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7212 - val_loss: 0.5421 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7316 - val_loss: 0.5386 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7411 - val_loss: 0.5412 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7485 - val_loss: 0.5401 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7586 - val_loss: 0.5442 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7670 - val_loss: 0.5446 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.7744 - val_loss: 0.5462 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4553 - accuracy: 0.7851
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4555 - accuracy: 0.7850 - val_loss: 0.5560 - val_accuracy: 0.7170 - lr: 0.0010
253/253 [==============================] - 0s 781us/step
Independent Testing Matthews Correlation:  0.44396221186430046
Confusion Matrix :
 [[3066  981]
 [1274 2773]]
Accuracy on test set:    0.7213985668396343
Sensitivity:    0.685198912774895 	 Specificity:    0.7575982209043736
Precision  : 0.7386787426744805
Area Under Curve:    0.7213985668396343
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5916 - accuracy: 0.6815 - val_loss: 0.5616 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7198 - val_loss: 0.5432 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7318 - val_loss: 0.5416 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5204 - accuracy: 0.7404 - val_loss: 0.5413 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7469 - val_loss: 0.5454 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7558 - val_loss: 0.5456 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4836 - accuracy: 0.7677 - val_loss: 0.5497 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7772 - val_loss: 0.5504 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4565 - accuracy: 0.7841
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4565 - accuracy: 0.7841 - val_loss: 0.5557 - val_accuracy: 0.7179 - lr: 0.0010
253/253 [==============================] - 0s 927us/step
Independent Testing Matthews Correlation:  0.48667004213087417
Confusion Matrix :
 [[3128  919]
 [1162 2885]]
Accuracy on test set:    0.7428959723251791
Sensitivity:    0.7128737336298493 	 Specificity:    0.7729182110205091
Precision  : 0.7584121976866456
Area Under Curve:    0.7428959723251792
(8094, 2560) (8094,)
Mean MCC = 0.4288 + 0.0227 and Mean AUC = 0.7140 + 0.0114
Mean Sensitivity = 0.7186 + 0.0272 and Mean Specificity = 0.7094 + 0.0364 and Mean Accuracy = 0.7140 + 0.0114
Mean Precision = 0.7131 + 0.0208





Seed   : 989535
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5856 - accuracy: 0.6849 - val_loss: 0.5678 - val_accuracy: 0.6990 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7239 - val_loss: 0.5520 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7343 - val_loss: 0.5453 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7430 - val_loss: 0.5464 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7507 - val_loss: 0.5523 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7593 - val_loss: 0.5491 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7679 - val_loss: 0.5524 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4703 - accuracy: 0.7750 - val_loss: 0.5569 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4560 - accuracy: 0.7848
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4560 - accuracy: 0.7849 - val_loss: 0.5665 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 824us/step
Independent Testing Matthews Correlation:  0.392339939197657
Confusion Matrix :
 [[2559 1489]
 [ 983 3064]]
Accuracy on test set:    0.6946263125386041
Sensitivity:    0.7571040276748209 	 Specificity:    0.6321640316205533
Precision  : 0.6729628816165166
Area Under Curve:    0.6946340296476871
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5853 - accuracy: 0.6871 - val_loss: 0.5565 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7229 - val_loss: 0.5491 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5256 - accuracy: 0.7362 - val_loss: 0.5468 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.7446 - val_loss: 0.5438 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5033 - accuracy: 0.7512 - val_loss: 0.5511 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7606 - val_loss: 0.5508 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7675 - val_loss: 0.5490 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4714 - accuracy: 0.7737 - val_loss: 0.5541 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4607 - accuracy: 0.7815
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4607 - accuracy: 0.7815 - val_loss: 0.5569 - val_accuracy: 0.7111 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41742630063900615
Confusion Matrix :
 [[2882 1166]
 [1192 2855]]
Accuracy on test set:    0.7087090796788141
Sensitivity:    0.705460835186558 	 Specificity:    0.7119565217391305
Precision  : 0.7100223824919174
Area Under Curve:    0.7087086784628442
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5859 - accuracy: 0.6858 - val_loss: 0.5494 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7228 - val_loss: 0.5456 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7331 - val_loss: 0.5432 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7428 - val_loss: 0.5407 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7505 - val_loss: 0.5406 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7598 - val_loss: 0.5395 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7683 - val_loss: 0.5468 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7773 - val_loss: 0.5485 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4545 - accuracy: 0.7853 - val_loss: 0.5501 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4426 - accuracy: 0.7922
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4426 - accuracy: 0.7922 - val_loss: 0.5618 - val_accuracy: 0.7241 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43557460133179665
Confusion Matrix :
 [[2690 1357]
 [ 937 3111]]
Accuracy on test set:    0.716615194564546
Sensitivity:    0.7685276679841897 	 Specificity:    0.6646898937484557
Precision  : 0.696284691136974
Area Under Curve:    0.7166087808663226
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5905 - accuracy: 0.6832 - val_loss: 0.5488 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7207 - val_loss: 0.5378 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7308 - val_loss: 0.5398 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7391 - val_loss: 0.5361 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5102 - accuracy: 0.7469 - val_loss: 0.5370 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7531 - val_loss: 0.5362 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4889 - accuracy: 0.7619 - val_loss: 0.5377 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4790 - accuracy: 0.7681
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7679 - val_loss: 0.5420 - val_accuracy: 0.7242 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42203871222851497
Confusion Matrix :
 [[2742 1305]
 [1038 3010]]
Accuracy on test set:    0.7105620753551575
Sensitivity:    0.7435770750988142 	 Specificity:    0.6775389177168273
Precision  : 0.697566628041715
Area Under Curve:    0.7105579964078208
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5867 - accuracy: 0.6835 - val_loss: 0.5513 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7217 - val_loss: 0.5420 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7332 - val_loss: 0.5437 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7402 - val_loss: 0.5415 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7482 - val_loss: 0.5439 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7567 - val_loss: 0.5453 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4840 - accuracy: 0.7651
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7652 - val_loss: 0.5460 - val_accuracy: 0.7193 - lr: 0.0010
253/253 [==============================] - 0s 934us/step
Independent Testing Matthews Correlation:  0.41817542789684875
Confusion Matrix :
 [[2911 1136]
 [1219 2828]]
Accuracy on test set:    0.7090437361008154
Sensitivity:    0.6987892265875958 	 Specificity:    0.7192982456140351
Precision  : 0.7134207870837538
Area Under Curve:    0.7090437361008155
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5867 - accuracy: 0.6840 - val_loss: 0.5527 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7219 - val_loss: 0.5455 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7325 - val_loss: 0.5451 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7432 - val_loss: 0.5463 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7505 - val_loss: 0.5462 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7568 - val_loss: 0.5463 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7659 - val_loss: 0.5489 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4716 - accuracy: 0.7749 - val_loss: 0.5567 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4598 - accuracy: 0.7833
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4597 - accuracy: 0.7831 - val_loss: 0.5564 - val_accuracy: 0.7241 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43427354959392134
Confusion Matrix :
 [[2793 1254]
 [1038 3009]]
Accuracy on test set:    0.7168272794662713
Sensitivity:    0.7435137138621201 	 Specificity:    0.6901408450704225
Precision  : 0.7058409570724842
Area Under Curve:    0.7168272794662712
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5886 - accuracy: 0.6824 - val_loss: 0.5554 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7227 - val_loss: 0.5418 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7321 - val_loss: 0.5414 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7402 - val_loss: 0.5423 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5106 - accuracy: 0.7466 - val_loss: 0.5396 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7545 - val_loss: 0.5414 - val_accuracy: 0.7237 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4911 - accuracy: 0.7619 - val_loss: 0.5433 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7683 - val_loss: 0.5473 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4698 - accuracy: 0.7764 - val_loss: 0.5522 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4581 - accuracy: 0.7848 - val_loss: 0.5546 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4471 - accuracy: 0.7904 - val_loss: 0.5599 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 12/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4367 - accuracy: 0.7967
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4366 - accuracy: 0.7967 - val_loss: 0.5716 - val_accuracy: 0.7152 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.428465857031453
Confusion Matrix :
 [[2888 1159]
 [1154 2893]]
Accuracy on test set:    0.7142327650111193
Sensitivity:    0.7148505065480603 	 Specificity:    0.7136150234741784
Precision  : 0.7139684106614018
Area Under Curve:    0.7142327650111192
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6853 - val_loss: 0.5528 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7213 - val_loss: 0.5453 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7322 - val_loss: 0.5405 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7409 - val_loss: 0.5402 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7488 - val_loss: 0.5414 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7581 - val_loss: 0.5408 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4805 - accuracy: 0.7668 - val_loss: 0.5459 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4684 - accuracy: 0.7768
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4692 - accuracy: 0.7761 - val_loss: 0.5484 - val_accuracy: 0.7209 - lr: 0.0010
253/253 [==============================] - 0s 739us/step
Independent Testing Matthews Correlation:  0.4469978307149284
Confusion Matrix :
 [[2927 1120]
 [1118 2929]]
Accuracy on test set:    0.7234988880652335
Sensitivity:    0.7237459846800098 	 Specificity:    0.7232517914504571
Precision  : 0.7233884909854285
Area Under Curve:    0.7234988880652334
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5901 - accuracy: 0.6827 - val_loss: 0.5547 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7214 - val_loss: 0.5539 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7314 - val_loss: 0.5449 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7398 - val_loss: 0.5446 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7498 - val_loss: 0.5506 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7570 - val_loss: 0.5486 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7654 - val_loss: 0.5514 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4716 - accuracy: 0.7750 - val_loss: 0.5539 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4568 - accuracy: 0.7832 - val_loss: 0.5618 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4435 - accuracy: 0.7925 - val_loss: 0.5671 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4313 - accuracy: 0.7988 - val_loss: 0.5727 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 12/400
256/257 [============================>.] - ETA: 0s - loss: 0.4181 - accuracy: 0.8077
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4181 - accuracy: 0.8077 - val_loss: 0.5759 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 778us/step
Independent Testing Matthews Correlation:  0.42996818062436853
Confusion Matrix :
 [[3116  931]
 [1387 2660]]
Accuracy on test set:    0.7136150234741784
Sensitivity:    0.6572769953051644 	 Specificity:    0.7699530516431925
Precision  : 0.7407407407407407
Area Under Curve:    0.7136150234741785
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5991 - accuracy: 0.6754 - val_loss: 0.5585 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5525 - accuracy: 0.7204 - val_loss: 0.5524 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5396 - accuracy: 0.7274 - val_loss: 0.5471 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7352 - val_loss: 0.5457 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7428 - val_loss: 0.5452 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5113 - accuracy: 0.7477 - val_loss: 0.5469 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5015 - accuracy: 0.7549 - val_loss: 0.5481 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7612 - val_loss: 0.5603 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.7678 - val_loss: 0.5556 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4686 - accuracy: 0.7782
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4686 - accuracy: 0.7782 - val_loss: 0.5588 - val_accuracy: 0.7104 - lr: 0.0010
253/253 [==============================] - 0s 786us/step
Independent Testing Matthews Correlation:  0.48387758742938725
Confusion Matrix :
 [[2970 1077]
 [1012 3035]]
Accuracy on test set:    0.7419075858660736
Sensitivity:    0.7499382258463059 	 Specificity:    0.7338769458858414
Precision  : 0.7380836575875487
Area Under Curve:    0.7419075858660736
(8094, 2560) (8094,)
Mean MCC = 0.4309 + 0.0224 and Mean AUC = 0.7150 + 0.0115
Mean Sensitivity = 0.7263 + 0.0316 and Mean Specificity = 0.7036 + 0.0369 and Mean Accuracy = 0.7150 + 0.0115
Mean Precision = 0.7112 + 0.0191





Seed   : 292870
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5888 - accuracy: 0.6832 - val_loss: 0.5515 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7239 - val_loss: 0.5439 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7345 - val_loss: 0.5380 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7437 - val_loss: 0.5373 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7514 - val_loss: 0.5365 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7580 - val_loss: 0.5368 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4819 - accuracy: 0.7689 - val_loss: 0.5400 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.7755 - val_loss: 0.5418 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4568 - accuracy: 0.7872 - val_loss: 0.5414 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4449 - accuracy: 0.7922 - val_loss: 0.5459 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4327 - accuracy: 0.7988 - val_loss: 0.5480 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 12/400
252/257 [============================>.] - ETA: 0s - loss: 0.4199 - accuracy: 0.8092
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4199 - accuracy: 0.8092 - val_loss: 0.5596 - val_accuracy: 0.7172 - lr: 0.0010
253/253 [==============================] - 0s 815us/step
Independent Testing Matthews Correlation:  0.4006689238512833
Confusion Matrix :
 [[2475 1573]
 [ 877 3170]]
Accuracy on test set:    0.6973440395305744
Sensitivity:    0.7832962688411169 	 Specificity:    0.6114130434782609
Precision  : 0.6683533628505165
Area Under Curve:    0.697354656159689
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5883 - accuracy: 0.6850 - val_loss: 0.5550 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7245 - val_loss: 0.5440 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7343 - val_loss: 0.5421 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7428 - val_loss: 0.5378 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7513 - val_loss: 0.5396 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7584 - val_loss: 0.5430 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7674 - val_loss: 0.5391 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4679 - accuracy: 0.7748 - val_loss: 0.5486 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.7829 - val_loss: 0.5495 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4456 - accuracy: 0.7888 - val_loss: 0.5500 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4333 - accuracy: 0.7971 - val_loss: 0.5627 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 12/400
256/257 [============================>.] - ETA: 0s - loss: 0.4207 - accuracy: 0.8040
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4207 - accuracy: 0.8040 - val_loss: 0.5654 - val_accuracy: 0.7145 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4042447426994354
Confusion Matrix :
 [[2784 1264]
 [1148 2899]]
Accuracy on test set:    0.7020382952439778
Sensitivity:    0.7163330862367185 	 Specificity:    0.6877470355731226
Precision  : 0.6963728080711026
Area Under Curve:    0.7020400609049204
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5862 - accuracy: 0.6852 - val_loss: 0.5464 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7218 - val_loss: 0.5350 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7334 - val_loss: 0.5321 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7424 - val_loss: 0.5307 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7489 - val_loss: 0.5311 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7569 - val_loss: 0.5318 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7665 - val_loss: 0.5422 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7741 - val_loss: 0.5340 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4618 - accuracy: 0.7834 - val_loss: 0.5398 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4500 - accuracy: 0.7891
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4504 - accuracy: 0.7890 - val_loss: 0.5459 - val_accuracy: 0.7224 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43091089432967034
Confusion Matrix :
 [[2678 1369]
 [ 944 3104]]
Accuracy on test set:    0.7142680667078444
Sensitivity:    0.766798418972332 	 Specificity:    0.6617247343711391
Precision  : 0.6939414263357926
Area Under Curve:    0.7142615766717355
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5911 - accuracy: 0.6807 - val_loss: 0.5568 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7209 - val_loss: 0.5349 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7322 - val_loss: 0.5324 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7388 - val_loss: 0.5288 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.7462 - val_loss: 0.5285 - val_accuracy: 0.7311 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7543 - val_loss: 0.5299 - val_accuracy: 0.7311 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7640 - val_loss: 0.5342 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.7721 - val_loss: 0.5373 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4638 - accuracy: 0.7789 - val_loss: 0.5389 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 10/400

246/257 [===========================>..] - ETA: 0s - loss: 0.4526 - accuracy: 0.7849
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4534 - accuracy: 0.7841 - val_loss: 0.5447 - val_accuracy: 0.7277 - lr: 0.0010
253/253 [==============================] - 0s 872us/step
Independent Testing Matthews Correlation:  0.4193946949787746
Confusion Matrix :
 [[2871 1176]
 [1174 2874]]
Accuracy on test set:    0.7096973440395306
Sensitivity:    0.7099802371541502 	 Specificity:    0.7094143810229799
Precision  : 0.7096296296296296
Area Under Curve:    0.7096973090885651
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5886 - accuracy: 0.6813 - val_loss: 0.5533 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7204 - val_loss: 0.5399 - val_accuracy: 0.7333 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7334 - val_loss: 0.5386 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7404 - val_loss: 0.5426 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7493 - val_loss: 0.5384 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7580 - val_loss: 0.5415 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4795 - accuracy: 0.7695
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7696 - val_loss: 0.5467 - val_accuracy: 0.7200 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42410461947772915
Confusion Matrix :
 [[2586 1461]
 [ 887 3160]]
Accuracy on test set:    0.7099085742525327
Sensitivity:    0.7808253026933532 	 Specificity:    0.6389918458117124
Precision  : 0.683834667820818
Area Under Curve:    0.7099085742525327
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5891 - accuracy: 0.6829 - val_loss: 0.5494 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7230 - val_loss: 0.5444 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7331 - val_loss: 0.5398 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7414 - val_loss: 0.5416 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7511 - val_loss: 0.5402 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4954 - accuracy: 0.7572 - val_loss: 0.5442 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7660 - val_loss: 0.5456 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4720 - accuracy: 0.7741
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.7739 - val_loss: 0.5469 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 751us/step
Independent Testing Matthews Correlation:  0.4397138182439168
Confusion Matrix :
 [[2962 1085]
 [1183 2864]]
Accuracy on test set:    0.7197924388435878
Sensitivity:    0.7076847047195454 	 Specificity:    0.7319001729676303
Precision  : 0.7252468979488478
Area Under Curve:    0.7197924388435879
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5865 - accuracy: 0.6850 - val_loss: 0.5525 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7231 - val_loss: 0.5493 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.7344 - val_loss: 0.5417 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7428 - val_loss: 0.5390 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7511 - val_loss: 0.5400 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7580 - val_loss: 0.5497 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4801 - accuracy: 0.7667 - val_loss: 0.5457 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4672 - accuracy: 0.7757 - val_loss: 0.5498 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4535 - accuracy: 0.7859 - val_loss: 0.5577 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4396 - accuracy: 0.7947
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4398 - accuracy: 0.7946 - val_loss: 0.5600 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 820us/step
Independent Testing Matthews Correlation:  0.42237538694582694
Confusion Matrix :
 [[2958 1089]
 [1250 2797]]
Accuracy on test set:    0.7110205090190265
Sensitivity:    0.6911292315295281 	 Specificity:    0.7309117865085248
Precision  : 0.7197632527020073
Area Under Curve:    0.7110205090190265
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5894 - accuracy: 0.6817 - val_loss: 0.5544 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7186 - val_loss: 0.5373 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5342 - accuracy: 0.7305 - val_loss: 0.5390 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5231 - accuracy: 0.7395 - val_loss: 0.5329 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5112 - accuracy: 0.7463 - val_loss: 0.5351 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7544 - val_loss: 0.5361 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4918 - accuracy: 0.7613 - val_loss: 0.5387 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4793 - accuracy: 0.7699 - val_loss: 0.5447 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4688 - accuracy: 0.7769
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4688 - accuracy: 0.7772 - val_loss: 0.5480 - val_accuracy: 0.7271 - lr: 0.0010
253/253 [==============================] - 0s 943us/step
Independent Testing Matthews Correlation:  0.43628503358728865
Confusion Matrix :
 [[2702 1345]
 [ 945 3102]]
Accuracy on test set:    0.7170743760810477
Sensitivity:    0.7664936990363233 	 Specificity:    0.6676550531257722
Precision  : 0.6975489093771081
Area Under Curve:    0.7170743760810476
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5875 - accuracy: 0.6829 - val_loss: 0.5458 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7208 - val_loss: 0.5399 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7318 - val_loss: 0.5354 - val_accuracy: 0.7311 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7411 - val_loss: 0.5353 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7481 - val_loss: 0.5372 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 6/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4972 - accuracy: 0.7569
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.7566 - val_loss: 0.5371 - val_accuracy: 0.7296 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4569527293220889
Confusion Matrix :
 [[3023 1024]
 [1175 2872]]
Accuracy on test set:    0.7283172720533728
Sensitivity:    0.7096614776377563 	 Specificity:    0.7469730664689894
Precision  : 0.7371663244353183
Area Under Curve:    0.7283172720533728
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5957 - accuracy: 0.6786 - val_loss: 0.5517 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5505 - accuracy: 0.7181 - val_loss: 0.5443 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5360 - accuracy: 0.7305 - val_loss: 0.5523 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5239 - accuracy: 0.7377 - val_loss: 0.5465 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5135 - accuracy: 0.7449 - val_loss: 0.5427 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
242/257 [===========================>..] - ETA: 0s - loss: 0.5036 - accuracy: 0.7526
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.5038 - accuracy: 0.7522 - val_loss: 0.5583 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 725us/step
Independent Testing Matthews Correlation:  0.485325231016438
Confusion Matrix :
 [[2843 1204]
 [ 885 3162]]
Accuracy on test set:    0.7419075858660736
Sensitivity:    0.7813194959229058 	 Specificity:    0.7024956758092414
Precision  : 0.7242327072835547
Area Under Curve:    0.7419075858660736
(8094, 2560) (8094,)
Mean MCC = 0.4320 + 0.0237 and Mean AUC = 0.7151 + 0.0122
Mean Sensitivity = 0.7414 + 0.0353 and Mean Specificity = 0.6889 + 0.0416 and Mean Accuracy = 0.7151 + 0.0122
Mean Precision = 0.7056 + 0.0202





Seed   : 777917
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5896 - accuracy: 0.6849 - val_loss: 0.5573 - val_accuracy: 0.7054 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7254 - val_loss: 0.5486 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7364 - val_loss: 0.5463 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7419 - val_loss: 0.5475 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7498 - val_loss: 0.5531 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7565 - val_loss: 0.5488 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7641 - val_loss: 0.5514 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4729 - accuracy: 0.7725 - val_loss: 0.5544 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4618 - accuracy: 0.7810 - val_loss: 0.5535 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4489 - accuracy: 0.7882 - val_loss: 0.5573 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4367 - accuracy: 0.7971 - val_loss: 0.5666 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4256 - accuracy: 0.8031 - val_loss: 0.5647 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4123 - accuracy: 0.8115 - val_loss: 0.6038 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4006 - accuracy: 0.8176 - val_loss: 0.5847 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 15/400
250/257 [============================>.] - ETA: 0s - loss: 0.3892 - accuracy: 0.8238
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3898 - accuracy: 0.8236 - val_loss: 0.5890 - val_accuracy: 0.7104 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3747100470991256
Confusion Matrix :
 [[2704 1344]
 [1188 2859]]
Accuracy on test set:    0.6872143298332304
Sensitivity:    0.7064492216456635 	 Specificity:    0.6679841897233202
Precision  : 0.6802284082798001
Area Under Curve:    0.6872167056844918
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5901 - accuracy: 0.6832 - val_loss: 0.5554 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7226 - val_loss: 0.5534 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7360 - val_loss: 0.5473 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7421 - val_loss: 0.5452 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7508 - val_loss: 0.5487 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7599 - val_loss: 0.5474 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7691 - val_loss: 0.5509 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4703 - accuracy: 0.7736 - val_loss: 0.5572 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4571 - accuracy: 0.7823 - val_loss: 0.5529 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4458 - accuracy: 0.7914 - val_loss: 0.5644 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4336 - accuracy: 0.7973 - val_loss: 0.5654 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4221 - accuracy: 0.8048 - val_loss: 0.5744 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4086 - accuracy: 0.8114 - val_loss: 0.5687 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 14/400
255/257 [============================>.] - ETA: 0s - loss: 0.3984 - accuracy: 0.8180
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.3986 - accuracy: 0.8179 - val_loss: 0.5800 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 844us/step
Independent Testing Matthews Correlation:  0.39944863730804564
Confusion Matrix :
 [[2796 1252]
 [1179 2868]]
Accuracy on test set:    0.6996911673872761
Sensitivity:    0.7086730911786508 	 Specificity:    0.6907114624505929
Precision  : 0.6961165048543689
Area Under Curve:    0.6996922768146219
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5891 - accuracy: 0.6816 - val_loss: 0.5502 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7226 - val_loss: 0.5392 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7313 - val_loss: 0.5401 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5206 - accuracy: 0.7401 - val_loss: 0.5358 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7475 - val_loss: 0.5367 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5011 - accuracy: 0.7552 - val_loss: 0.5392 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4900 - accuracy: 0.7623 - val_loss: 0.5415 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7687 - val_loss: 0.5461 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7763 - val_loss: 0.5447 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4581 - accuracy: 0.7834 - val_loss: 0.5514 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4466 - accuracy: 0.7904 - val_loss: 0.5546 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4344 - accuracy: 0.7987 - val_loss: 0.5669 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 13/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4200 - accuracy: 0.8082
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4208 - accuracy: 0.8077 - val_loss: 0.5680 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41254305218135356
Confusion Matrix :
 [[2936 1111]
 [1268 2780]]
Accuracy on test set:    0.7061148857319333
Sensitivity:    0.6867588932806324 	 Specificity:    0.7254756609834445
Precision  : 0.7144692881007453
Area Under Curve:    0.7061172771320384
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5928 - accuracy: 0.6793 - val_loss: 0.5461 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7212 - val_loss: 0.5394 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7315 - val_loss: 0.5359 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7404 - val_loss: 0.5325 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7502 - val_loss: 0.5339 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7579 - val_loss: 0.5344 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7679 - val_loss: 0.5416 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4706 - accuracy: 0.7743
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4706 - accuracy: 0.7743 - val_loss: 0.5516 - val_accuracy: 0.7209 - lr: 0.0010
253/253 [==============================] - 0s 865us/step
Independent Testing Matthews Correlation:  0.4334395077558853
Confusion Matrix :
 [[2992 1055]
 [1240 2808]]
Accuracy on test set:    0.7164916615194564
Sensitivity:    0.6936758893280632 	 Specificity:    0.7393130714109216
Precision  : 0.726896194667357
Area Under Curve:    0.7164944803694925
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5890 - accuracy: 0.6842 - val_loss: 0.5569 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7213 - val_loss: 0.5448 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7358 - val_loss: 0.5445 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7422 - val_loss: 0.5457 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7495 - val_loss: 0.5426 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.7565 - val_loss: 0.5466 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7622 - val_loss: 0.5485 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4779 - accuracy: 0.7694 - val_loss: 0.5497 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4673 - accuracy: 0.7768 - val_loss: 0.5567 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4545 - accuracy: 0.7872
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4550 - accuracy: 0.7868 - val_loss: 0.5612 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42292080016691996
Confusion Matrix :
 [[2699 1348]
 [ 994 3053]]
Accuracy on test set:    0.7106498640968619
Sensitivity:    0.7543859649122807 	 Specificity:    0.666913763281443
Precision  : 0.6937059759145648
Area Under Curve:    0.7106498640968619
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5876 - accuracy: 0.6845 - val_loss: 0.5509 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7242 - val_loss: 0.5440 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7318 - val_loss: 0.5440 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7404 - val_loss: 0.5426 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7486 - val_loss: 0.5448 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4985 - accuracy: 0.7557 - val_loss: 0.5520 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.7647 - val_loss: 0.5506 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4741 - accuracy: 0.7710
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7707 - val_loss: 0.5543 - val_accuracy: 0.7146 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4290365266945331
Confusion Matrix :
 [[2747 1300]
 [1015 3032]]
Accuracy on test set:    0.7139856683963429
Sensitivity:    0.7491969360019768 	 Specificity:    0.6787744007907092
Precision  : 0.6999076638965835
Area Under Curve:    0.713985668396343
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5900 - accuracy: 0.6819 - val_loss: 0.5499 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7228 - val_loss: 0.5423 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7331 - val_loss: 0.5445 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7409 - val_loss: 0.5425 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.7478 - val_loss: 0.5475 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7560 - val_loss: 0.5475 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7629 - val_loss: 0.5477 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4754 - accuracy: 0.7731 - val_loss: 0.5549 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4616 - accuracy: 0.7838 - val_loss: 0.5562 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4490 - accuracy: 0.7879 - val_loss: 0.5612 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4367 - accuracy: 0.7965
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4371 - accuracy: 0.7966 - val_loss: 0.5644 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41414061458594664
Confusion Matrix :
 [[2850 1197]
 [1174 2873]]
Accuracy on test set:    0.7070669631826044
Sensitivity:    0.7099085742525327 	 Specificity:    0.704225352112676
Precision  : 0.7058968058968059
Area Under Curve:    0.7070669631826043
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5895 - accuracy: 0.6828 - val_loss: 0.5518 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7224 - val_loss: 0.5434 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7331 - val_loss: 0.5457 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7447 - val_loss: 0.5487 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7495 - val_loss: 0.5466 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7586 - val_loss: 0.5457 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4801 - accuracy: 0.7697
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7696 - val_loss: 0.5501 - val_accuracy: 0.7222 - lr: 0.0010
253/253 [==============================] - 0s 764us/step
Independent Testing Matthews Correlation:  0.4403215403925527
Confusion Matrix :
 [[2796 1251]
 [1017 3030]]
Accuracy on test set:    0.7197924388435878
Sensitivity:    0.748702742772424 	 Specificity:    0.6908821349147517
Precision  : 0.7077785564120532
Area Under Curve:    0.7197924388435877
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5901 - accuracy: 0.6811 - val_loss: 0.5548 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7204 - val_loss: 0.5492 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7311 - val_loss: 0.5459 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7395 - val_loss: 0.5478 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7482 - val_loss: 0.5482 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.7566 - val_loss: 0.5515 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7652 - val_loss: 0.5530 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4756 - accuracy: 0.7725
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4760 - accuracy: 0.7723 - val_loss: 0.5531 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 839us/step
Independent Testing Matthews Correlation:  0.4578745561278977
Confusion Matrix :
 [[2941 1106]
 [1088 2959]]
Accuracy on test set:    0.7289350135903138
Sensitivity:    0.7311588831233012 	 Specificity:    0.7267111440573264
Precision  : 0.7279212792127921
Area Under Curve:    0.7289350135903139
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5934 - accuracy: 0.6810 - val_loss: 0.5668 - val_accuracy: 0.6976 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5509 - accuracy: 0.7199 - val_loss: 0.5530 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5350 - accuracy: 0.7321 - val_loss: 0.5506 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5234 - accuracy: 0.7397 - val_loss: 0.5496 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5133 - accuracy: 0.7465 - val_loss: 0.5541 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.7555 - val_loss: 0.5557 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7635 - val_loss: 0.5658 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4787 - accuracy: 0.7722
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4791 - accuracy: 0.7720 - val_loss: 0.5630 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 853us/step
Independent Testing Matthews Correlation:  0.47596062277679013
Confusion Matrix :
 [[3208  839]
 [1294 2753]]
Accuracy on test set:    0.7364714603409933
Sensitivity:    0.6802569804793674 	 Specificity:    0.7926859402026192
Precision  : 0.7664253897550112
Area Under Curve:    0.7364714603409933
(8094, 2560) (8094,)
Mean MCC = 0.4260 + 0.0273 and Mean AUC = 0.7126 + 0.0134
Mean Sensitivity = 0.7169 + 0.0258 and Mean Specificity = 0.7084 + 0.0368 and Mean Accuracy = 0.7126 + 0.0134
Mean Precision = 0.7119 + 0.0229





Seed   : 882763

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5899 - accuracy: 0.6820 - val_loss: 0.5603 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7232 - val_loss: 0.5506 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7327 - val_loss: 0.5474 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7408 - val_loss: 0.5463 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7491 - val_loss: 0.5605 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7560 - val_loss: 0.5488 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.7646 - val_loss: 0.5547 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7720 - val_loss: 0.5575 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4632 - accuracy: 0.7807 - val_loss: 0.5620 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4504 - accuracy: 0.7887 - val_loss: 0.5630 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4368 - accuracy: 0.7971 - val_loss: 0.5731 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - ETA: 0s - loss: 0.4262 - accuracy: 0.8039
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4262 - accuracy: 0.8039 - val_loss: 0.5798 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 784us/step
Independent Testing Matthews Correlation:  0.39113011931300967
Confusion Matrix :
 [[2678 1370]
 [1098 2949]]
Accuracy on test set:    0.6951204447189623
Sensitivity:    0.7286879169755375 	 Specificity:    0.6615612648221344
Precision  : 0.6827969437369762
Area Under Curve:    0.6951245908988359
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5838 - accuracy: 0.6873 - val_loss: 0.5536 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5395 - accuracy: 0.7257 - val_loss: 0.5511 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5236 - accuracy: 0.7353 - val_loss: 0.5480 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.7442 - val_loss: 0.5453 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7544 - val_loss: 0.5483 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7622 - val_loss: 0.5590 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4762 - accuracy: 0.7715 - val_loss: 0.5584 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4632 - accuracy: 0.7799 - val_loss: 0.5548 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 9/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4513 - accuracy: 0.7887
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4519 - accuracy: 0.7881 - val_loss: 0.5572 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4193373363766791
Confusion Matrix :
 [[2780 1268]
 [1084 2963]]
Accuracy on test set:    0.7094502779493514
Sensitivity:    0.7321472695824067 	 Specificity:    0.6867588932806324
Precision  : 0.7003072559678563
Area Under Curve:    0.7094530814315195
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5907 - accuracy: 0.6783 - val_loss: 0.5523 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7221 - val_loss: 0.5403 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7348 - val_loss: 0.5382 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7393 - val_loss: 0.5462 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7475 - val_loss: 0.5386 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7549 - val_loss: 0.5396 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7621 - val_loss: 0.5493 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4775 - accuracy: 0.7693
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7691 - val_loss: 0.5429 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 814us/step
Independent Testing Matthews Correlation:  0.42489201984367464
Confusion Matrix :
 [[2805 1242]
 [1087 2961]]
Accuracy on test set:    0.7122915379864113
Sensitivity:    0.7314723320158103 	 Specificity:    0.6931060044477391
Precision  : 0.7044967880085653
Area Under Curve:    0.7122891682317747
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5882 - accuracy: 0.6822 - val_loss: 0.5491 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7207 - val_loss: 0.5409 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7335 - val_loss: 0.5392 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7411 - val_loss: 0.5361 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7490 - val_loss: 0.5408 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7576 - val_loss: 0.5412 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.7631 - val_loss: 0.5418 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4750 - accuracy: 0.7720 - val_loss: 0.5482 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4623 - accuracy: 0.7794
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4630 - accuracy: 0.7795 - val_loss: 0.5468 - val_accuracy: 0.7259 - lr: 0.0010
253/253 [==============================] - 0s 824us/step
Independent Testing Matthews Correlation:  0.42451679550358196
Confusion Matrix :
 [[2972 1075]
 [1256 2792]]
Accuracy on test set:    0.7120444718962322
Sensitivity:    0.6897233201581028 	 Specificity:    0.7343711391153941
Precision  : 0.722006723558314
Area Under Curve:    0.7120472296367485
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5876 - accuracy: 0.6844 - val_loss: 0.5481 - val_accuracy: 0.7215 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7207 - val_loss: 0.5382 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7319 - val_loss: 0.5373 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7422 - val_loss: 0.5354 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7508 - val_loss: 0.5406 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7567 - val_loss: 0.5391 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7658 - val_loss: 0.5379 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.7732 - val_loss: 0.5418 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4579 - accuracy: 0.7819
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4581 - accuracy: 0.7820 - val_loss: 0.5494 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 880us/step
Independent Testing Matthews Correlation:  0.4361668190064798
Confusion Matrix :
 [[2734 1313]
 [ 975 3072]]
Accuracy on test set:    0.717321472695824
Sensitivity:    0.7590808005930318 	 Specificity:    0.6755621447986162
Precision  : 0.7005701254275941
Area Under Curve:    0.717321472695824
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5896 - accuracy: 0.6813 - val_loss: 0.5513 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7220 - val_loss: 0.5415 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7334 - val_loss: 0.5395 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7416 - val_loss: 0.5476 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7498 - val_loss: 0.5409 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7585 - val_loss: 0.5445 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4829 - accuracy: 0.7675
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4827 - accuracy: 0.7676 - val_loss: 0.5473 - val_accuracy: 0.7249 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43534153774914935
Confusion Matrix :
 [[2842 1205]
 [1081 2966]]
Accuracy on test set:    0.7175685693106004
Sensitivity:    0.7328885594267358 	 Specificity:    0.702248579194465
Precision  : 0.7111004555262527
Area Under Curve:    0.7175685693106004
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5964 - accuracy: 0.6766 - val_loss: 0.5551 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5488 - accuracy: 0.7198 - val_loss: 0.5467 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5331 - accuracy: 0.7301 - val_loss: 0.5398 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7407 - val_loss: 0.5382 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5109 - accuracy: 0.7479 - val_loss: 0.5395 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7543 - val_loss: 0.5375 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7635 - val_loss: 0.5403 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7725 - val_loss: 0.5423 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4631 - accuracy: 0.7801 - val_loss: 0.5492 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4512 - accuracy: 0.7883 - val_loss: 0.5523 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4379 - accuracy: 0.7937 - val_loss: 0.5593 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 12/400
249/257 [============================>.] - ETA: 0s - loss: 0.4242 - accuracy: 0.8037
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4240 - accuracy: 0.8040 - val_loss: 0.5691 - val_accuracy: 0.7200 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4078237550827547
Confusion Matrix :
 [[2958 1089]
 [1310 2737]]
Accuracy on test set:    0.7036076105757351
Sensitivity:    0.6763034346429454 	 Specificity:    0.7309117865085248
Precision  : 0.7153685311029796
Area Under Curve:    0.7036076105757352
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5896 - accuracy: 0.6813 - val_loss: 0.5519 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7232 - val_loss: 0.5433 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7317 - val_loss: 0.5407 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5213 - accuracy: 0.7397 - val_loss: 0.5403 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5101 - accuracy: 0.7483 - val_loss: 0.5409 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7553 - val_loss: 0.5469 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.7642 - val_loss: 0.5451 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7726 - val_loss: 0.5531 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4632 - accuracy: 0.7805
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4631 - accuracy: 0.7808 - val_loss: 0.5594 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 803us/step
Independent Testing Matthews Correlation:  0.4553421606257446
Confusion Matrix :
 [[2782 1265]
 [ 945 3102]]
Accuracy on test set:    0.7269582406721028
Sensitivity:    0.7664936990363233 	 Specificity:    0.6874227823078823
Precision  : 0.7103274559193955
Area Under Curve:    0.7269582406721029
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5941 - accuracy: 0.6786 - val_loss: 0.5573 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7210 - val_loss: 0.5439 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7300 - val_loss: 0.5396 - val_accuracy: 0.7222 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5211 - accuracy: 0.7397 - val_loss: 0.5414 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7479 - val_loss: 0.5402 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4995 - accuracy: 0.7539 - val_loss: 0.5422 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4890 - accuracy: 0.7614 - val_loss: 0.5454 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4774 - accuracy: 0.7694 - val_loss: 0.5497 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4656 - accuracy: 0.7770 - val_loss: 0.5505 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4518 - accuracy: 0.7863
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4522 - accuracy: 0.7860 - val_loss: 0.5604 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 748us/step
Independent Testing Matthews Correlation:  0.4458725514732986
Confusion Matrix :
 [[3049  998]
 [1248 2799]]
Accuracy on test set:    0.722510501606128
Sensitivity:    0.6916234247590808 	 Specificity:    0.7533975784531752
Precision  : 0.7371609165130366
Area Under Curve:    0.7225105016061281
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5907 - accuracy: 0.6824 - val_loss: 0.5565 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7216 - val_loss: 0.5497 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5344 - accuracy: 0.7308 - val_loss: 0.5480 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5222 - accuracy: 0.7370 - val_loss: 0.5470 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5126 - accuracy: 0.7448 - val_loss: 0.5478 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7529 - val_loss: 0.5490 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7606 - val_loss: 0.5475 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4801 - accuracy: 0.7699 - val_loss: 0.5540 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4663 - accuracy: 0.7792
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7787 - val_loss: 0.5584 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4829386156690991
Confusion Matrix :
 [[2922 1125]
 [ 969 3078]]
Accuracy on test set:    0.7412898443291327
Sensitivity:    0.7605633802816901 	 Specificity:    0.7220163083765753
Precision  : 0.7323340471092077
Area Under Curve:    0.7412898443291327
(8094, 2560) (8094,)
Mean MCC = 0.4323 + 0.0243 and Mean AUC = 0.7158 + 0.0121
Mean Sensitivity = 0.7269 + 0.0300 and Mean Specificity = 0.7047 + 0.0278 and Mean Accuracy = 0.7158 + 0.0121
Mean Precision = 0.7116 + 0.0153





Seed   : 398752
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5855 - accuracy: 0.6876 - val_loss: 0.5627 - val_accuracy: 0.7038 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5402 - accuracy: 0.7265 - val_loss: 0.5524 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5255 - accuracy: 0.7363 - val_loss: 0.5524 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5139 - accuracy: 0.7455 - val_loss: 0.5500 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5040 - accuracy: 0.7526 - val_loss: 0.5514 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7582 - val_loss: 0.5510 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7663 - val_loss: 0.5544 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7741 - val_loss: 0.5605 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.7830 - val_loss: 0.5591 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4488 - accuracy: 0.7919 - val_loss: 0.5731 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4349 - accuracy: 0.7970 - val_loss: 0.5773 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4244 - accuracy: 0.8048 - val_loss: 0.5801 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 13/400
249/257 [============================>.] - ETA: 0s - loss: 0.4127 - accuracy: 0.8108
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4128 - accuracy: 0.8109 - val_loss: 0.5932 - val_accuracy: 0.7082 - lr: 0.0010
253/253 [==============================] - 0s 912us/step
Independent Testing Matthews Correlation:  0.4097256568756721
Confusion Matrix :
 [[2576 1472]
 [ 932 3115]]
Accuracy on test set:    0.7030265596046943
Sensitivity:    0.7697059550284161 	 Specificity:    0.6363636363636364
Precision  : 0.6790930891650316
Area Under Curve:    0.7030347956960262
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5909 - accuracy: 0.6811 - val_loss: 0.5620 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7222 - val_loss: 0.5510 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7319 - val_loss: 0.5518 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5209 - accuracy: 0.7400 - val_loss: 0.5496 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5120 - accuracy: 0.7455 - val_loss: 0.5510 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5038 - accuracy: 0.7510 - val_loss: 0.5588 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7576 - val_loss: 0.5597 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4831 - accuracy: 0.7657 - val_loss: 0.5522 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4725 - accuracy: 0.7745
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.7747 - val_loss: 0.5586 - val_accuracy: 0.7131 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40855632209484705
Confusion Matrix :
 [[2776 1272]
 [1123 2924]]
Accuracy on test set:    0.7041383570105003
Sensitivity:    0.722510501606128 	 Specificity:    0.6857707509881423
Precision  : 0.6968541468064824
Area Under Curve:    0.7041406262971351
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5857 - accuracy: 0.6860 - val_loss: 0.5467 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7245 - val_loss: 0.5412 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.7357 - val_loss: 0.5368 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7424 - val_loss: 0.5347 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7504 - val_loss: 0.5347 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7586 - val_loss: 0.5377 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7671 - val_loss: 0.5380 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4682 - accuracy: 0.7750 - val_loss: 0.5424 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 9/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4563 - accuracy: 0.7839
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4569 - accuracy: 0.7834 - val_loss: 0.5467 - val_accuracy: 0.7270 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4061583061537574
Confusion Matrix :
 [[2649 1398]
 [1013 3035]]
Accuracy on test set:    0.7021618282890674
Sensitivity:    0.7497529644268774 	 Specificity:    0.6545589325426242
Precision  : 0.6846379427024588
Area Under Curve:    0.7021559484847508
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6849 - val_loss: 0.5469 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7229 - val_loss: 0.5390 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7326 - val_loss: 0.5484 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7403 - val_loss: 0.5384 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7495 - val_loss: 0.5395 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7581 - val_loss: 0.5390 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4836 - accuracy: 0.7651 - val_loss: 0.5421 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7738 - val_loss: 0.5441 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4580 - accuracy: 0.7847
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4580 - accuracy: 0.7847 - val_loss: 0.5475 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 995us/step
Independent Testing Matthews Correlation:  0.42557839839151473
Confusion Matrix :
 [[2685 1362]
 [ 971 3077]]
Accuracy on test set:    0.7117974058060531
Sensitivity:    0.7601284584980237 	 Specificity:    0.6634544106745738
Precision  : 0.6931741383194413
Area Under Curve:    0.7117914345862987
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5931 - accuracy: 0.6782 - val_loss: 0.5576 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7201 - val_loss: 0.5533 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7312 - val_loss: 0.5449 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5212 - accuracy: 0.7386 - val_loss: 0.5452 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5104 - accuracy: 0.7484 - val_loss: 0.5470 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7533 - val_loss: 0.5474 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7628 - val_loss: 0.5493 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7705 - val_loss: 0.5468 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.7785 - val_loss: 0.5500 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4554 - accuracy: 0.7874 - val_loss: 0.5570 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4452 - accuracy: 0.7937 - val_loss: 0.5590 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 12/400
250/257 [============================>.] - ETA: 0s - loss: 0.4302 - accuracy: 0.8037
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4308 - accuracy: 0.8035 - val_loss: 0.5662 - val_accuracy: 0.7137 - lr: 0.0010
253/253 [==============================] - 0s 994us/step
Independent Testing Matthews Correlation:  0.42764629730294773
Confusion Matrix :
 [[2659 1388]
 [ 939 3108]]
Accuracy on test set:    0.7125030887076848
Sensitivity:    0.7679762787249814 	 Specificity:    0.657029898690388
Precision  : 0.6912811387900356
Area Under Curve:    0.7125030887076846
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5884 - accuracy: 0.6850 - val_loss: 0.5559 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7210 - val_loss: 0.5477 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5337 - accuracy: 0.7302 - val_loss: 0.5489 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5237 - accuracy: 0.7376 - val_loss: 0.5466 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5139 - accuracy: 0.7443 - val_loss: 0.5492 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.7521 - val_loss: 0.5535 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4912 - accuracy: 0.7583
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7584 - val_loss: 0.5494 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 746us/step
Independent Testing Matthews Correlation:  0.4324238415160959
Confusion Matrix :
 [[2889 1158]
 [1139 2908]]
Accuracy on test set:    0.7162095379293304
Sensitivity:    0.7185569557697059 	 Specificity:    0.7138621200889548
Precision  : 0.7151992129857354
Area Under Curve:    0.7162095379293303
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5872 - accuracy: 0.6845 - val_loss: 0.5609 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7213 - val_loss: 0.5558 - val_accuracy: 0.7152 - lr: 0.0010

Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7333 - val_loss: 0.5537 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7391 - val_loss: 0.5516 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7477 - val_loss: 0.5492 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7539 - val_loss: 0.5502 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4871 - accuracy: 0.7632 - val_loss: 0.5552 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4758 - accuracy: 0.7706 - val_loss: 0.5554 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4641 - accuracy: 0.7783 - val_loss: 0.5656 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4512 - accuracy: 0.7863
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4515 - accuracy: 0.7863 - val_loss: 0.5630 - val_accuracy: 0.7175 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.43510272617130974
Confusion Matrix :
 [[2810 1237]
 [1051 2996]]
Accuracy on test set:    0.717321472695824
Sensitivity:    0.7403014578700272 	 Specificity:    0.694341487521621
Precision  : 0.7077722655327191
Area Under Curve:    0.7173214726958241
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5874 - accuracy: 0.6857 - val_loss: 0.5578 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7237 - val_loss: 0.5493 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7325 - val_loss: 0.5493 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7423 - val_loss: 0.5471 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7498 - val_loss: 0.5449 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7582 - val_loss: 0.5488 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7677 - val_loss: 0.5545 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4699 - accuracy: 0.7778 - val_loss: 0.5552 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4577 - accuracy: 0.7843 - val_loss: 0.5610 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4430 - accuracy: 0.7935 - val_loss: 0.5625 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4283 - accuracy: 0.8028
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4283 - accuracy: 0.8025 - val_loss: 0.5688 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 975us/step
Independent Testing Matthews Correlation:  0.44025377480249733
Confusion Matrix :
 [[2857 1190]
 [1076 2971]]
Accuracy on test set:    0.7200395354583642
Sensitivity:    0.7341240425006177 	 Specificity:    0.7059550284161107
Precision  : 0.7140110550348474
Area Under Curve:    0.7200395354583642
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5939 - accuracy: 0.6790 - val_loss: 0.5554 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5492 - accuracy: 0.7192 - val_loss: 0.5487 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5336 - accuracy: 0.7315 - val_loss: 0.5453 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5209 - accuracy: 0.7380 - val_loss: 0.5465 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7481 - val_loss: 0.5442 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4987 - accuracy: 0.7555 - val_loss: 0.5497 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.7629 - val_loss: 0.5497 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4732 - accuracy: 0.7727
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4740 - accuracy: 0.7721 - val_loss: 0.5520 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 950us/step
Independent Testing Matthews Correlation:  0.4370341668330643
Confusion Matrix :
 [[3067  980]
 [1304 2743]]
Accuracy on test set:    0.7178156659253768
Sensitivity:    0.6777860143316037 	 Specificity:    0.75784531751915
Precision  : 0.736771420897126
Area Under Curve:    0.7178156659253768
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5906 - accuracy: 0.6819 - val_loss: 0.5621 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7178 - val_loss: 0.5492 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7304 - val_loss: 0.5489 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7389 - val_loss: 0.5490 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7473 - val_loss: 0.5534 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7565 - val_loss: 0.5561 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4846 - accuracy: 0.7644
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7644 - val_loss: 0.5523 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 812us/step
Independent Testing Matthews Correlation:  0.4712810735293418
Confusion Matrix :
 [[3138  909]
 [1237 2810]]
Accuracy on test set:    0.7348653323449469
Sensitivity:    0.694341487521621 	 Specificity:    0.7753891771682728
Precision  : 0.7555794568432375
Area Under Curve:    0.7348653323449469
(8094, 2560) (8094,)
Mean MCC = 0.4294 + 0.0183 and Mean AUC = 0.7140 + 0.0093
Mean Sensitivity = 0.7335 + 0.0292 and Mean Specificity = 0.6945 + 0.0430 and Mean Accuracy = 0.7140 + 0.0093
Mean Precision = 0.7074 + 0.0228





Seed   : 522127
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5900 - accuracy: 0.6827 - val_loss: 0.5618 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7220 - val_loss: 0.5555 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7345 - val_loss: 0.5641 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7406 - val_loss: 0.5542 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5108 - accuracy: 0.7488 - val_loss: 0.5536 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7553 - val_loss: 0.5649 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4905 - accuracy: 0.7611 - val_loss: 0.5601 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.7698 - val_loss: 0.5594 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 9/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4646 - accuracy: 0.7790
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4652 - accuracy: 0.7784 - val_loss: 0.5666 - val_accuracy: 0.7061 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4019036291295918
Confusion Matrix :
 [[2870 1178]
 [1243 2804]]
Accuracy on test set:    0.7009264978381717
Sensitivity:    0.6928589078329627 	 Specificity:    0.70899209486166
Precision  : 0.7041687594173782
Area Under Curve:    0.7009255013473115
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5856 - accuracy: 0.6855 - val_loss: 0.5633 - val_accuracy: 0.7016 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7260 - val_loss: 0.5558 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7353 - val_loss: 0.5532 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7422 - val_loss: 0.5572 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7510 - val_loss: 0.5546 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7566 - val_loss: 0.5580 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.7654 - val_loss: 0.5605 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.7747 - val_loss: 0.5660 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4605 - accuracy: 0.7820 - val_loss: 0.5679 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4496 - accuracy: 0.7879 - val_loss: 0.5617 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4348 - accuracy: 0.7982 - val_loss: 0.5775 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 12/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4223 - accuracy: 0.8058
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4226 - accuracy: 0.8058 - val_loss: 0.5799 - val_accuracy: 0.6990 - lr: 0.0010
253/253 [==============================] - 0s 776us/step
Independent Testing Matthews Correlation:  0.3974807570671923
Confusion Matrix :
 [[2957 1091]
 [1351 2696]]
Accuracy on test set:    0.698332303891291
Sensitivity:    0.6661724734371139 	 Specificity:    0.7304841897233202
Precision  : 0.7119091629257988
Area Under Curve:    0.698328331580217
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5843 - accuracy: 0.6884 - val_loss: 0.5512 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5423 - accuracy: 0.7242 - val_loss: 0.5409 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.7352 - val_loss: 0.5398 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5150 - accuracy: 0.7428 - val_loss: 0.5434 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7497 - val_loss: 0.5415 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4923 - accuracy: 0.7595 - val_loss: 0.5435 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4794 - accuracy: 0.7666
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7665 - val_loss: 0.5475 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 899us/step
Independent Testing Matthews Correlation:  0.4202423144659558
Confusion Matrix :
 [[2764 1283]
 [1066 2982]]
Accuracy on test set:    0.7098208770846202
Sensitivity:    0.7366600790513834 	 Specificity:    0.6829750432419076
Precision  : 0.699179366940211
Area Under Curve:    0.7098175611466455
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5858 - accuracy: 0.6841 - val_loss: 0.5508 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7225 - val_loss: 0.5469 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7320 - val_loss: 0.5455 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7413 - val_loss: 0.5397 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7506 - val_loss: 0.5395 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7560 - val_loss: 0.5459 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.7651 - val_loss: 0.5477 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.7730 - val_loss: 0.5490 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4617 - accuracy: 0.7814 - val_loss: 0.5574 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4484 - accuracy: 0.7880
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4496 - accuracy: 0.7874 - val_loss: 0.5582 - val_accuracy: 0.7224 - lr: 0.0010
253/253 [==============================] - 0s 796us/step
Independent Testing Matthews Correlation:  0.4301386714360848
Confusion Matrix :
 [[2941 1106]
 [1201 2847]]
Accuracy on test set:    0.7150092649783817
Sensitivity:    0.7033102766798419 	 Specificity:    0.7267111440573264
Precision  : 0.7202124968378447
Area Under Curve:    0.7150107103685841
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5917 - accuracy: 0.6791 - val_loss: 0.5548 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7227 - val_loss: 0.5495 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7316 - val_loss: 0.5436 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7408 - val_loss: 0.5480 - val_accuracy: 0.7213 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7488 - val_loss: 0.5444 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7558 - val_loss: 0.5451 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.7636 - val_loss: 0.5470 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7729 - val_loss: 0.5488 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4627 - accuracy: 0.7804 - val_loss: 0.5523 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4516 - accuracy: 0.7861
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4515 - accuracy: 0.7861 - val_loss: 0.5579 - val_accuracy: 0.7124 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42159162941590744
Confusion Matrix :
 [[2847 1200]
 [1141 2906]]
Accuracy on test set:    0.7107734124042501
Sensitivity:    0.7180627625401532 	 Specificity:    0.7034840622683469
Precision  : 0.7077447637603507
Area Under Curve:    0.7107734124042501
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5884 - accuracy: 0.6828 - val_loss: 0.5493 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7208 - val_loss: 0.5428 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7327 - val_loss: 0.5399 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7407 - val_loss: 0.5393 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7495 - val_loss: 0.5399 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7575 - val_loss: 0.5400 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.7655 - val_loss: 0.5447 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4732 - accuracy: 0.7750 - val_loss: 0.5484 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4611 - accuracy: 0.7816
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4609 - accuracy: 0.7818 - val_loss: 0.5518 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43932443486123673
Confusion Matrix :
 [[2846 1201]
 [1069 2978]]
Accuracy on test set:    0.7195453422288115
Sensitivity:    0.7358537188040524 	 Specificity:    0.7032369656535705
Precision  : 0.7126106724096674
Area Under Curve:    0.7195453422288114
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5878 - accuracy: 0.6834 - val_loss: 0.5486 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7222 - val_loss: 0.5391 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7328 - val_loss: 0.5352 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7410 - val_loss: 0.5327 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7504 - val_loss: 0.5348 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7554 - val_loss: 0.5350 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7645 - val_loss: 0.5474 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7715 - val_loss: 0.5458 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4620 - accuracy: 0.7798 - val_loss: 0.5501 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4497 - accuracy: 0.7890
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4498 - accuracy: 0.7888 - val_loss: 0.5513 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4117063538671281
Confusion Matrix :
 [[2932 1115]
 [1267 2780]]
Accuracy on test set:    0.7057079318013343
Sensitivity:    0.6869285890783297 	 Specificity:    0.724487274524339
Precision  : 0.7137355584082157
Area Under Curve:    0.7057079318013344
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5880 - accuracy: 0.6845 - val_loss: 0.5490 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7221 - val_loss: 0.5410 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7311 - val_loss: 0.5371 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7414 - val_loss: 0.5379 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7487 - val_loss: 0.5421 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7552 - val_loss: 0.5419 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4883 - accuracy: 0.7640 - val_loss: 0.5398 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4778 - accuracy: 0.7698 - val_loss: 0.5494 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4655 - accuracy: 0.7774
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4655 - accuracy: 0.7776 - val_loss: 0.5605 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44320751693132904
Confusion Matrix :
 [[2674 1373]
 [ 893 3154]]
Accuracy on test set:    0.7200395354583642
Sensitivity:    0.7793427230046949 	 Specificity:    0.6607363479120336
Precision  : 0.69670863706649
Area Under Curve:    0.7200395354583643
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5924 - accuracy: 0.6798 - val_loss: 0.5523 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7194 - val_loss: 0.5452 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5332 - accuracy: 0.7310 - val_loss: 0.5414 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5219 - accuracy: 0.7386 - val_loss: 0.5419 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5103 - accuracy: 0.7476 - val_loss: 0.5433 - val_accuracy: 0.7220 - lr: 0.0010

Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7545 - val_loss: 0.5486 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.7630 - val_loss: 0.5522 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4745 - accuracy: 0.7729
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4749 - accuracy: 0.7725 - val_loss: 0.5532 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 869us/step
Independent Testing Matthews Correlation:  0.45758310024476684
Confusion Matrix :
 [[2836 1211]
 [ 987 3060]]
Accuracy on test set:    0.7284408203607611
Sensitivity:    0.7561156412157154 	 Specificity:    0.7007659995058068
Precision  : 0.7164598454694451
Area Under Curve:    0.7284408203607611
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5926 - accuracy: 0.6800 - val_loss: 0.5525 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5497 - accuracy: 0.7195 - val_loss: 0.5417 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5347 - accuracy: 0.7299 - val_loss: 0.5406 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5230 - accuracy: 0.7379 - val_loss: 0.5404 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5130 - accuracy: 0.7456 - val_loss: 0.5415 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5008 - accuracy: 0.7559 - val_loss: 0.5417 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7609 - val_loss: 0.5458 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4802 - accuracy: 0.7681 - val_loss: 0.5495 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4662 - accuracy: 0.7787 - val_loss: 0.5481 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4548 - accuracy: 0.7842 - val_loss: 0.5557 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4416 - accuracy: 0.7925 - val_loss: 0.5612 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 12/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4310 - accuracy: 0.7997
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4312 - accuracy: 0.7997 - val_loss: 0.5648 - val_accuracy: 0.7270 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47673769351702483
Confusion Matrix :
 [[3087  960]
 [1160 2887]]
Accuracy on test set:    0.7380775883370397
Sensitivity:    0.713367926859402 	 Specificity:    0.7627872498146775
Precision  : 0.7504548999220172
Area Under Curve:    0.7380775883370397
(8094, 2560) (8094,)
Mean MCC = 0.4300 + 0.0236 and Mean AUC = 0.7147 + 0.0117
Mean Sensitivity = 0.7189 + 0.0322 and Mean Specificity = 0.7105 + 0.0265 and Mean Accuracy = 0.7147 + 0.0117
Mean Precision = 0.7133 + 0.0142





Seed   : 794942
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5814 - accuracy: 0.6915 - val_loss: 0.5669 - val_accuracy: 0.6998 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5404 - accuracy: 0.7256 - val_loss: 0.5561 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5250 - accuracy: 0.7380 - val_loss: 0.5585 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5141 - accuracy: 0.7438 - val_loss: 0.5535 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7525 - val_loss: 0.5526 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7591 - val_loss: 0.5569 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7682 - val_loss: 0.5597 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4663 - accuracy: 0.7783 - val_loss: 0.5612 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4539 - accuracy: 0.7869
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4539 - accuracy: 0.7871 - val_loss: 0.5684 - val_accuracy: 0.7072 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4057009287125939
Confusion Matrix :
 [[2600 1448]
 [ 969 3078]]
Accuracy on test set:    0.70142063001853
Sensitivity:    0.7605633802816901 	 Specificity:    0.642292490118577
Precision  : 0.6800707026071586
Area Under Curve:    0.7014279352001336
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5909 - accuracy: 0.6815 - val_loss: 0.5657 - val_accuracy: 0.6999 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7219 - val_loss: 0.5527 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7350 - val_loss: 0.5521 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7429 - val_loss: 0.5495 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7527 - val_loss: 0.5493 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7603 - val_loss: 0.5534 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4831 - accuracy: 0.7660
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7656 - val_loss: 0.5666 - val_accuracy: 0.7090 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41512682783117716
Confusion Matrix :
 [[2590 1458]
 [ 924 3123]]
Accuracy on test set:    0.7057442865966647
Sensitivity:    0.7716827279466272 	 Specificity:    0.6398221343873518
Precision  : 0.6817288801571709
Area Under Curve:    0.7057524311669895
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5888 - accuracy: 0.6830 - val_loss: 0.5524 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7238 - val_loss: 0.5433 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7336 - val_loss: 0.5405 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7425 - val_loss: 0.5412 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7497 - val_loss: 0.5436 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7591 - val_loss: 0.5484 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7661 - val_loss: 0.5462 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4702 - accuracy: 0.7746
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.7742 - val_loss: 0.5528 - val_accuracy: 0.7097 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41322041752812294
Confusion Matrix :
 [[2979 1068]
 [1310 2738]]
Accuracy on test set:    0.7062384187770229
Sensitivity:    0.6763833992094862 	 Specificity:    0.7361008154188288
Precision  : 0.7193904361534419
Area Under Curve:    0.7062421073141576
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5890 - accuracy: 0.6825 - val_loss: 0.5494 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7233 - val_loss: 0.5397 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7338 - val_loss: 0.5397 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7393 - val_loss: 0.5384 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7492 - val_loss: 0.5395 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7557 - val_loss: 0.5420 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4834 - accuracy: 0.7673
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7671 - val_loss: 0.5498 - val_accuracy: 0.7197 - lr: 0.0010
253/253 [==============================] - 0s 834us/step
Independent Testing Matthews Correlation:  0.4166752148000316
Confusion Matrix :
 [[2599 1448]
 [ 927 3121]]
Accuracy on test set:    0.7066090179122916
Sensitivity:    0.770998023715415 	 Specificity:    0.6422041018038053
Precision  : 0.6830816371197198
Area Under Curve:    0.7066010627596102
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5849 - accuracy: 0.6872 - val_loss: 0.5528 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7228 - val_loss: 0.5414 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7329 - val_loss: 0.5425 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5150 - accuracy: 0.7428 - val_loss: 0.5411 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5040 - accuracy: 0.7506 - val_loss: 0.5420 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7607 - val_loss: 0.5460 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
252/257 [============================>.] - ETA: 0s - loss: 0.4769 - accuracy: 0.7699
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4773 - accuracy: 0.7698 - val_loss: 0.5433 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 708us/step
Independent Testing Matthews Correlation:  0.40673802721639224
Confusion Matrix :
 [[2865 1182]
 [1219 2828]]
Accuracy on test set:    0.7033605139609588
Sensitivity:    0.6987892265875958 	 Specificity:    0.7079318013343218
Precision  : 0.7052369077306733
Area Under Curve:    0.7033605139609588
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5879 - accuracy: 0.6851 - val_loss: 0.5582 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7233 - val_loss: 0.5558 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7323 - val_loss: 0.5469 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7420 - val_loss: 0.5522 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7491 - val_loss: 0.5465 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7557 - val_loss: 0.5533 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7635 - val_loss: 0.5515 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4753 - accuracy: 0.7710
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7707 - val_loss: 0.5506 - val_accuracy: 0.7141 - lr: 0.0010
253/253 [==============================] - 0s 841us/step
Independent Testing Matthews Correlation:  0.43853627735891315
Confusion Matrix :
 [[2820 1227]
 [1047 3000]]
Accuracy on test set:    0.7190511489992587
Sensitivity:    0.7412898443291327 	 Specificity:    0.6968124536693847
Precision  : 0.7097232079489
Area Under Curve:    0.7190511489992587
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5881 - accuracy: 0.6850 - val_loss: 0.5572 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7228 - val_loss: 0.5513 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7331 - val_loss: 0.5450 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7421 - val_loss: 0.5457 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7489 - val_loss: 0.5476 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7580 - val_loss: 0.5467 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4856 - accuracy: 0.7634 - val_loss: 0.5484 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4750 - accuracy: 0.7726
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4750 - accuracy: 0.7726 - val_loss: 0.5514 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42558601073445185
Confusion Matrix :
 [[2804 1243]
 [1083 2964]]
Accuracy on test set:    0.7126266370150729
Sensitivity:    0.7323943661971831 	 Specificity:    0.6928589078329627
Precision  : 0.704540052293796
Area Under Curve:    0.7126266370150729
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5891 - accuracy: 0.6825 - val_loss: 0.5562 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7216 - val_loss: 0.5520 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7326 - val_loss: 0.5471 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 4/400

257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7427 - val_loss: 0.5583 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7499 - val_loss: 0.5487 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4954 - accuracy: 0.7590 - val_loss: 0.5473 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7677 - val_loss: 0.5561 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7757 - val_loss: 0.5552 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4588 - accuracy: 0.7833 - val_loss: 0.5578 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4458 - accuracy: 0.7925 - val_loss: 0.5539 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 11/400
250/257 [============================>.] - ETA: 0s - loss: 0.4318 - accuracy: 0.8008
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4318 - accuracy: 0.8007 - val_loss: 0.5660 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 945us/step
Independent Testing Matthews Correlation:  0.43769238887502326
Confusion Matrix :
 [[2804 1243]
 [1035 3012]]
Accuracy on test set:    0.7185569557697059
Sensitivity:    0.7442550037064493 	 Specificity:    0.6928589078329627
Precision  : 0.7078730904817861
Area Under Curve:    0.718556955769706
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5878 - accuracy: 0.6864 - val_loss: 0.5653 - val_accuracy: 0.7020 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7220 - val_loss: 0.5476 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7336 - val_loss: 0.5453 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7400 - val_loss: 0.5435 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7461 - val_loss: 0.5481 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7572 - val_loss: 0.5499 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7652 - val_loss: 0.5485 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7749 - val_loss: 0.5528 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4606 - accuracy: 0.7817 - val_loss: 0.5582 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4483 - accuracy: 0.7894 - val_loss: 0.5556 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4355 - accuracy: 0.7966
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4364 - accuracy: 0.7960 - val_loss: 0.5630 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 744us/step
Independent Testing Matthews Correlation:  0.4532344015665733
Confusion Matrix :
 [[3076  971]
 [1246 2801]]
Accuracy on test set:    0.7260934025203855
Sensitivity:    0.6921176179886336 	 Specificity:    0.7600691870521374
Precision  : 0.7425768822905621
Area Under Curve:    0.7260934025203856
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5888 - accuracy: 0.6822 - val_loss: 0.5586 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7214 - val_loss: 0.5491 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7337 - val_loss: 0.5509 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5212 - accuracy: 0.7385 - val_loss: 0.5461 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7489 - val_loss: 0.5509 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7580 - val_loss: 0.5521 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7663 - val_loss: 0.5615 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7744 - val_loss: 0.5619 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4560 - accuracy: 0.7849 - val_loss: 0.5584 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4432 - accuracy: 0.7926 - val_loss: 0.5685 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4300 - accuracy: 0.8016 - val_loss: 0.5742 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - ETA: 0s - loss: 0.4155 - accuracy: 0.8102
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4155 - accuracy: 0.8102 - val_loss: 0.5819 - val_accuracy: 0.7105 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4639804010063848
Confusion Matrix :
 [[3173  874]
 [1306 2741]]
Accuracy on test set:    0.7306646898937484
Sensitivity:    0.6772918211020509 	 Specificity:    0.784037558685446
Precision  : 0.7582295988934993
Area Under Curve:    0.7306646898937484
(8094, 2560) (8094,)
Mean MCC = 0.4276 + 0.0190 and Mean AUC = 0.7130 + 0.0096
Mean Sensitivity = 0.7266 + 0.0355 and Mean Specificity = 0.6995 + 0.0474 and Mean Accuracy = 0.7130 + 0.0096
Mean Precision = 0.7092 + 0.0244





Seed   : 104149
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5859 - accuracy: 0.6871 - val_loss: 0.5605 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5422 - accuracy: 0.7262 - val_loss: 0.5550 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5269 - accuracy: 0.7367 - val_loss: 0.5575 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7439 - val_loss: 0.5521 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5034 - accuracy: 0.7519 - val_loss: 0.5502 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7605 - val_loss: 0.5555 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4784 - accuracy: 0.7698 - val_loss: 0.5591 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.7789 - val_loss: 0.5632 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4510 - accuracy: 0.7884 - val_loss: 0.5712 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4378 - accuracy: 0.7941
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4381 - accuracy: 0.7939 - val_loss: 0.5747 - val_accuracy: 0.7058 - lr: 0.0010
253/253 [==============================] - 0s 743us/step
Independent Testing Matthews Correlation:  0.3966835173713389
Confusion Matrix :
 [[2596 1452]
 [1000 3047]]
Accuracy on test set:    0.6970969734403953
Sensitivity:    0.7529033852236224 	 Specificity:    0.6413043478260869
Precision  : 0.6772616136919315
Area Under Curve:    0.6971038665248546
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5845 - accuracy: 0.6855 - val_loss: 0.5555 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7233 - val_loss: 0.5489 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.7358 - val_loss: 0.5545 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7418 - val_loss: 0.5504 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7502 - val_loss: 0.5507 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7569 - val_loss: 0.5540 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7645 - val_loss: 0.5553 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4743 - accuracy: 0.7734 - val_loss: 0.5605 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4638 - accuracy: 0.7802 - val_loss: 0.5617 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4539 - accuracy: 0.7876
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4535 - accuracy: 0.7878 - val_loss: 0.5710 - val_accuracy: 0.7091 - lr: 0.0010
253/253 [==============================] - 0s 709us/step
Independent Testing Matthews Correlation:  0.42353685304597255
Confusion Matrix :
 [[2713 1335]
 [1004 3043]]
Accuracy on test set:    0.7110562075355158
Sensitivity:    0.751914998764517 	 Specificity:    0.670207509881423
Precision  : 0.695066240292371
Area Under Curve:    0.71106125432297
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5873 - accuracy: 0.6835 - val_loss: 0.5489 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7257 - val_loss: 0.5408 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7330 - val_loss: 0.5373 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7419 - val_loss: 0.5418 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7494 - val_loss: 0.5378 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7571 - val_loss: 0.5390 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7665 - val_loss: 0.5448 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4708 - accuracy: 0.7730
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4714 - accuracy: 0.7729 - val_loss: 0.5441 - val_accuracy: 0.7132 - lr: 0.0010
253/253 [==============================] - 0s 958us/step
Independent Testing Matthews Correlation:  0.4075146315594372
Confusion Matrix :
 [[2985 1062]
 [1340 2708]]
Accuracy on test set:    0.7032736256948734
Sensitivity:    0.6689723320158103 	 Specificity:    0.737583395107487
Precision  : 0.7183023872679045
Area Under Curve:    0.7032778635616487
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5857 - accuracy: 0.6842 - val_loss: 0.5440 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7230 - val_loss: 0.5375 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7336 - val_loss: 0.5357 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7436 - val_loss: 0.5347 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7479 - val_loss: 0.5359 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7574 - val_loss: 0.5384 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7633 - val_loss: 0.5385 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.7712 - val_loss: 0.5434 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4655 - accuracy: 0.7793
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4658 - accuracy: 0.7791 - val_loss: 0.5442 - val_accuracy: 0.7249 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41841852772670407
Confusion Matrix :
 [[2711 1336]
 [1023 3025]]
Accuracy on test set:    0.7085855466337245
Sensitivity:    0.7472826086956522 	 Specificity:    0.6698789226587596
Precision  : 0.69364824581518
Area Under Curve:    0.7085807656772058
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5878 - accuracy: 0.6835 - val_loss: 0.5507 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7223 - val_loss: 0.5443 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7324 - val_loss: 0.5409 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7423 - val_loss: 0.5428 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7497 - val_loss: 0.5418 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7567 - val_loss: 0.5502 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - ETA: 0s - loss: 0.4815 - accuracy: 0.7686
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7686 - val_loss: 0.5450 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 759us/step
Independent Testing Matthews Correlation:  0.4250177010772111
Confusion Matrix :
 [[2684 1363]
 [ 972 3075]]
Accuracy on test set:    0.7115147022485792
Sensitivity:    0.759822090437361 	 Specificity:    0.6632073140597974
Precision  : 0.6928796755295178
Area Under Curve:    0.7115147022485792
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5884 - accuracy: 0.6835 - val_loss: 0.5510 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7261 - val_loss: 0.5435 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7350 - val_loss: 0.5427 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5143 - accuracy: 0.7441 - val_loss: 0.5430 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5023 - accuracy: 0.7544 - val_loss: 0.5414 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4902 - accuracy: 0.7623 - val_loss: 0.5429 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.7732 - val_loss: 0.5533 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4644 - accuracy: 0.7812
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4646 - accuracy: 0.7808 - val_loss: 0.5519 - val_accuracy: 0.7205 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4356339193395395
Confusion Matrix :
 [[2836 1211]
 [1074 2973]]
Accuracy on test set:    0.7176921176179887
Sensitivity:    0.7346182357301705 	 Specificity:    0.7007659995058068
Precision  : 0.7105640535372849
Area Under Curve:    0.7176921176179887
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5907 - accuracy: 0.6820 - val_loss: 0.5518 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7224 - val_loss: 0.5508 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7322 - val_loss: 0.5461 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7418 - val_loss: 0.5482 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7486 - val_loss: 0.5451 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7582 - val_loss: 0.5466 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7666 - val_loss: 0.5463 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4700 - accuracy: 0.7746 - val_loss: 0.5536 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4581 - accuracy: 0.7831 - val_loss: 0.5497 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4466 - accuracy: 0.7918 - val_loss: 0.5602 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4338 - accuracy: 0.7989 - val_loss: 0.5660 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4207 - accuracy: 0.8062 - val_loss: 0.5734 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4102 - accuracy: 0.8122 - val_loss: 0.5758 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 14/400
244/257 [===========================>..] - ETA: 0s - loss: 0.3975 - accuracy: 0.8187
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3978 - accuracy: 0.8185 - val_loss: 0.5934 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4209271350916807
Confusion Matrix :
 [[2744 1303]
 [1044 3003]]
Accuracy on test set:    0.7100321225599209
Sensitivity:    0.7420311341734618 	 Specificity:    0.6780331109463801
Precision  : 0.6973989781699954
Area Under Curve:    0.7100321225599209
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5853 - accuracy: 0.6862 - val_loss: 0.5491 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7228 - val_loss: 0.5449 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7342 - val_loss: 0.5394 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7410 - val_loss: 0.5437 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7515 - val_loss: 0.5491 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4928 - accuracy: 0.7589 - val_loss: 0.5428 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7681 - val_loss: 0.5454 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4684 - accuracy: 0.7753
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4679 - accuracy: 0.7756 - val_loss: 0.5567 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 877us/step
Independent Testing Matthews Correlation:  0.44504062235449593
Confusion Matrix :
 [[2905 1142]
 [1104 2943]]
Accuracy on test set:    0.722510501606128
Sensitivity:    0.7272053372868792 	 Specificity:    0.7178156659253768
Precision  : 0.7204406364749082
Area Under Curve:    0.722510501606128
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5937 - accuracy: 0.6765 - val_loss: 0.5534 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5484 - accuracy: 0.7190 - val_loss: 0.5586 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7319 - val_loss: 0.5448 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7407 - val_loss: 0.5420 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7493 - val_loss: 0.5427 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7577 - val_loss: 0.5537 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7664 - val_loss: 0.5494 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4695 - accuracy: 0.7752 - val_loss: 0.5718 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4565 - accuracy: 0.7833 - val_loss: 0.5622 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7927 - val_loss: 0.5648 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4274 - accuracy: 0.8016 - val_loss: 0.5690 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 12/400
256/257 [============================>.] - ETA: 0s - loss: 0.4158 - accuracy: 0.8087
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4158 - accuracy: 0.8086 - val_loss: 0.5760 - val_accuracy: 0.7139 - lr: 0.0010

253/253 [==============================] - 0s 777us/step
Independent Testing Matthews Correlation:  0.4455439786337851
Confusion Matrix :
 [[2948 1099]
 [1145 2902]]
Accuracy on test set:    0.7227575982209044
Sensitivity:    0.7170743760810477 	 Specificity:    0.7284408203607611
Precision  : 0.7253186703324169
Area Under Curve:    0.7227575982209045
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5941 - accuracy: 0.6798 - val_loss: 0.5549 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5511 - accuracy: 0.7182 - val_loss: 0.5491 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5360 - accuracy: 0.7294 - val_loss: 0.5500 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5249 - accuracy: 0.7382 - val_loss: 0.5470 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5143 - accuracy: 0.7455 - val_loss: 0.5471 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5033 - accuracy: 0.7524 - val_loss: 0.5516 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4918 - accuracy: 0.7614
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7611 - val_loss: 0.5525 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 807us/step
Independent Testing Matthews Correlation:  0.48558493409933895
Confusion Matrix :
 [[2980 1067]
 [1015 3032]]
Accuracy on test set:    0.742772424017791
Sensitivity:    0.7491969360019768 	 Specificity:    0.7363479120336052
Precision  : 0.7396926079531593
Area Under Curve:    0.7427724240177911
(8094, 2560) (8094,)
Mean MCC = 0.4304 + 0.0234 and Mean AUC = 0.7147 + 0.0120
Mean Sensitivity = 0.7351 + 0.0252 and Mean Specificity = 0.6944 + 0.0326 and Mean Accuracy = 0.7147 + 0.0120
Mean Precision = 0.7071 + 0.0180





Seed   : 865107
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5845 - accuracy: 0.6867 - val_loss: 0.5569 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5407 - accuracy: 0.7272 - val_loss: 0.5536 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5238 - accuracy: 0.7369 - val_loss: 0.5514 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5115 - accuracy: 0.7458 - val_loss: 0.5536 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7554 - val_loss: 0.5518 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7630 - val_loss: 0.5526 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4770 - accuracy: 0.7697 - val_loss: 0.5661 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4639 - accuracy: 0.7797
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4639 - accuracy: 0.7797 - val_loss: 0.5625 - val_accuracy: 0.7020 - lr: 0.0010
253/253 [==============================] - 0s 903us/step
Independent Testing Matthews Correlation:  0.40797242249504173
Confusion Matrix :
 [[2966 1082]
 [1317 2730]]
Accuracy on test set:    0.7036442248301421
Sensitivity:    0.6745737583395107 	 Specificity:    0.732707509881423
Precision  : 0.7161594963273872
Area Under Curve:    0.7036406341104668
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5904 - accuracy: 0.6824 - val_loss: 0.5602 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7235 - val_loss: 0.5506 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7356 - val_loss: 0.5514 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7446 - val_loss: 0.5499 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.7523 - val_loss: 0.5519 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.7614 - val_loss: 0.5538 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4788 - accuracy: 0.7693 - val_loss: 0.5602 - val_accuracy: 0.7032 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4673 - accuracy: 0.7775 - val_loss: 0.5637 - val_accuracy: 0.7034 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4535 - accuracy: 0.7859
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4535 - accuracy: 0.7859 - val_loss: 0.5686 - val_accuracy: 0.7039 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41643093349961247
Confusion Matrix :
 [[2797 1251]
 [1112 2935]]
Accuracy on test set:    0.7080914144533663
Sensitivity:    0.7252285643686681 	 Specificity:    0.6909584980237155
Precision  : 0.7011466794075489
Area Under Curve:    0.7080935311961917
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5891 - accuracy: 0.6825 - val_loss: 0.5518 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7212 - val_loss: 0.5417 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7323 - val_loss: 0.5392 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7404 - val_loss: 0.5381 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7483 - val_loss: 0.5404 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7558 - val_loss: 0.5458 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4855 - accuracy: 0.7634
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.7636 - val_loss: 0.5476 - val_accuracy: 0.7146 - lr: 0.0010
253/253 [==============================] - 0s 877us/step
Independent Testing Matthews Correlation:  0.42952945247099755
Confusion Matrix :
 [[2902 1145]
 [1164 2884]]
Accuracy on test set:    0.7147621988882026
Sensitivity:    0.7124505928853755 	 Specificity:    0.7170743760810477
Precision  : 0.7158103747828245
Area Under Curve:    0.7147624844832116
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5870 - accuracy: 0.6846 - val_loss: 0.5447 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7223 - val_loss: 0.5422 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7348 - val_loss: 0.5393 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7397 - val_loss: 0.5349 - val_accuracy: 0.7211 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7489 - val_loss: 0.5351 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7574 - val_loss: 0.5403 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7643 - val_loss: 0.5403 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4728 - accuracy: 0.7719 - val_loss: 0.5521 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4592 - accuracy: 0.7836 - val_loss: 0.5533 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4462 - accuracy: 0.7895
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4462 - accuracy: 0.7895 - val_loss: 0.5557 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4129937316541953
Confusion Matrix :
 [[2785 1262]
 [1115 2933]]
Accuracy on test set:    0.7063619518221124
Sensitivity:    0.7245553359683794 	 Specificity:    0.6881640721522115
Precision  : 0.699165673420739
Area Under Curve:    0.7063597040602955
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5919 - accuracy: 0.6817 - val_loss: 0.5516 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7202 - val_loss: 0.5427 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7308 - val_loss: 0.5409 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5221 - accuracy: 0.7382 - val_loss: 0.5396 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5124 - accuracy: 0.7449 - val_loss: 0.5467 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5028 - accuracy: 0.7531 - val_loss: 0.5447 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.7605 - val_loss: 0.5548 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4776 - accuracy: 0.7702 - val_loss: 0.5509 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4618 - accuracy: 0.7807
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4619 - accuracy: 0.7805 - val_loss: 0.5530 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42159162941590744
Confusion Matrix :
 [[2906 1141]
 [1200 2847]]
Accuracy on test set:    0.7107734124042501
Sensitivity:    0.7034840622683469 	 Specificity:    0.7180627625401532
Precision  : 0.7138916750250752
Area Under Curve:    0.7107734124042501
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5870 - accuracy: 0.6852 - val_loss: 0.5528 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7228 - val_loss: 0.5535 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7325 - val_loss: 0.5419 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7397 - val_loss: 0.5421 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7481 - val_loss: 0.5425 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.7564 - val_loss: 0.5453 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4861 - accuracy: 0.7648 - val_loss: 0.5521 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4756 - accuracy: 0.7693 - val_loss: 0.5492 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4669 - accuracy: 0.7780 - val_loss: 0.5546 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4555 - accuracy: 0.7854 - val_loss: 0.5582 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4427 - accuracy: 0.7938 - val_loss: 0.5623 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4315 - accuracy: 0.7992 - val_loss: 0.5625 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 13/400
250/257 [============================>.] - ETA: 0s - loss: 0.4198 - accuracy: 0.8080
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4202 - accuracy: 0.8077 - val_loss: 0.5670 - val_accuracy: 0.7154 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4161108136120939
Confusion Matrix :
 [[2867 1180]
 [1183 2864]]
Accuracy on test set:    0.7080553496417099
Sensitivity:    0.7076847047195454 	 Specificity:    0.7084259945638745
Precision  : 0.7082096933728981
Area Under Curve:    0.7080553496417099
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5894 - accuracy: 0.6829 - val_loss: 0.5504 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7211 - val_loss: 0.5453 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7312 - val_loss: 0.5441 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7405 - val_loss: 0.5437 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5093 - accuracy: 0.7466 - val_loss: 0.5438 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7554 - val_loss: 0.5426 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7640 - val_loss: 0.5483 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7727 - val_loss: 0.5541 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4618 - accuracy: 0.7806
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4620 - accuracy: 0.7804 - val_loss: 0.5530 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42353729996669254
Confusion Matrix :
 [[2951 1096]
 [1238 2809]]
Accuracy on test set:    0.7116382505559674
Sensitivity:    0.6940943909068445 	 Specificity:    0.7291821102050902
Precision  : 0.7193341869398208
Area Under Curve:    0.7116382505559673
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5889 - accuracy: 0.6831 - val_loss: 0.5543 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7229 - val_loss: 0.5418 - val_accuracy: 0.7212 - lr: 0.0010

Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7342 - val_loss: 0.5402 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7410 - val_loss: 0.5368 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7508 - val_loss: 0.5388 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7574 - val_loss: 0.5381 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7672 - val_loss: 0.5390 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.7755 - val_loss: 0.5385 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4582 - accuracy: 0.7826 - val_loss: 0.5453 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4466 - accuracy: 0.7892 - val_loss: 0.5507 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4326 - accuracy: 0.7986 - val_loss: 0.5576 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4215 - accuracy: 0.8075
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4218 - accuracy: 0.8070 - val_loss: 0.5632 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 841us/step
Independent Testing Matthews Correlation:  0.430483163879148
Confusion Matrix :
 [[2820 1227]
 [1079 2968]]
Accuracy on test set:    0.7150976031628367
Sensitivity:    0.7333827526562886 	 Specificity:    0.6968124536693847
Precision  : 0.7075089392133492
Area Under Curve:    0.7150976031628367
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5889 - accuracy: 0.6817 - val_loss: 0.5549 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7219 - val_loss: 0.5461 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7327 - val_loss: 0.5425 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7406 - val_loss: 0.5533 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7488 - val_loss: 0.5413 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4994 - accuracy: 0.7572 - val_loss: 0.5436 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.7635 - val_loss: 0.5478 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4760 - accuracy: 0.7725 - val_loss: 0.5472 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7792 - val_loss: 0.5499 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4510 - accuracy: 0.7886 - val_loss: 0.5584 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4393 - accuracy: 0.7957 - val_loss: 0.5605 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4279 - accuracy: 0.8015 - val_loss: 0.5683 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4168 - accuracy: 0.8108 - val_loss: 0.5746 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 14/400
250/257 [============================>.] - ETA: 0s - loss: 0.4052 - accuracy: 0.8164
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4053 - accuracy: 0.8161 - val_loss: 0.5881 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 923us/step
Independent Testing Matthews Correlation:  0.4386382618607602
Confusion Matrix :
 [[2810 1237]
 [1037 3010]]
Accuracy on test set:    0.7190511489992587
Sensitivity:    0.7437608104768965 	 Specificity:    0.694341487521621
Precision  : 0.7087355780550977
Area Under Curve:    0.7190511489992587
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5944 - accuracy: 0.6805 - val_loss: 0.5569 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5520 - accuracy: 0.7180 - val_loss: 0.5503 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5359 - accuracy: 0.7307 - val_loss: 0.5462 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5252 - accuracy: 0.7376 - val_loss: 0.5458 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5150 - accuracy: 0.7466 - val_loss: 0.5449 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7528 - val_loss: 0.5456 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4924 - accuracy: 0.7613 - val_loss: 0.5453 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4793 - accuracy: 0.7688 - val_loss: 0.5517 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4692 - accuracy: 0.7774 - val_loss: 0.5664 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4564 - accuracy: 0.7830 - val_loss: 0.5558 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4439 - accuracy: 0.7922 - val_loss: 0.5585 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4324 - accuracy: 0.7995 - val_loss: 0.5663 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 13/400
255/257 [============================>.] - ETA: 0s - loss: 0.4216 - accuracy: 0.8058
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4217 - accuracy: 0.8058 - val_loss: 0.5670 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 946us/step
Independent Testing Matthews Correlation:  0.46072065760607
Confusion Matrix :
 [[3245  802]
 [1401 2646]]
Accuracy on test set:    0.7278230788238201
Sensitivity:    0.653817642698295 	 Specificity:    0.8018285149493452
Precision  : 0.7674013921113689
Area Under Curve:    0.72782307882382
(8094, 2560) (8094,)
Mean MCC = 0.4258 + 0.0145 and Mean AUC = 0.7125 + 0.0067
Mean Sensitivity = 0.7073 + 0.0260 and Mean Specificity = 0.7178 + 0.0318 and Mean Accuracy = 0.7125 + 0.0067
Mean Precision = 0.7157 + 0.0183





Seed   : 84009
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5869 - accuracy: 0.6847 - val_loss: 0.5537 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7250 - val_loss: 0.5485 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7339 - val_loss: 0.5469 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7407 - val_loss: 0.5453 - val_accuracy: 0.7168 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.7470 - val_loss: 0.5462 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.7554 - val_loss: 0.5489 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4905 - accuracy: 0.7613 - val_loss: 0.5550 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7679 - val_loss: 0.5514 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4698 - accuracy: 0.7747 - val_loss: 0.5566 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 10/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4572 - accuracy: 0.7827
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4572 - accuracy: 0.7827 - val_loss: 0.5580 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4055671743231044
Confusion Matrix :
 [[3029 1019]
 [1394 2653]]
Accuracy on test set:    0.7019147621988882
Sensitivity:    0.6555473190017297 	 Specificity:    0.7482707509881423
Precision  : 0.7224945533769063
Area Under Curve:    0.7019090349949361
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5858 - accuracy: 0.6844 - val_loss: 0.5615 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5423 - accuracy: 0.7239 - val_loss: 0.5453 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5264 - accuracy: 0.7365 - val_loss: 0.5489 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7438 - val_loss: 0.5531 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7532 - val_loss: 0.5404 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7608 - val_loss: 0.5443 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4785 - accuracy: 0.7701 - val_loss: 0.5494 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4657 - accuracy: 0.7787 - val_loss: 0.5493 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4525 - accuracy: 0.7856 - val_loss: 0.5533 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4405 - accuracy: 0.7929
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4404 - accuracy: 0.7931 - val_loss: 0.5593 - val_accuracy: 0.7139 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4089051363698029
Confusion Matrix :
 [[2718 1330]
 [1066 2981]]
Accuracy on test set:    0.7040148239654107
Sensitivity:    0.7365950086483816 	 Specificity:    0.6714426877470355
Precision  : 0.6914868939921132
Area Under Curve:    0.7040188481977085
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5857 - accuracy: 0.6857 - val_loss: 0.5464 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7237 - val_loss: 0.5344 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7333 - val_loss: 0.5332 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7423 - val_loss: 0.5306 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7488 - val_loss: 0.5303 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7572 - val_loss: 0.5290 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7664 - val_loss: 0.5318 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7747 - val_loss: 0.5308 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4606 - accuracy: 0.7824 - val_loss: 0.5470 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4477 - accuracy: 0.7912 - val_loss: 0.5385 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4339 - accuracy: 0.8000 - val_loss: 0.5485 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4191 - accuracy: 0.8064 - val_loss: 0.5548 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 13/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4060 - accuracy: 0.8145
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4060 - accuracy: 0.8145 - val_loss: 0.5586 - val_accuracy: 0.7283 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4074232340977473
Confusion Matrix :
 [[2713 1334]
 [1068 2980]]
Accuracy on test set:    0.7032736256948734
Sensitivity:    0.7361660079051383 	 Specificity:    0.6703731158883123
Precision  : 0.6907742234585071
Area Under Curve:    0.7032695618967253
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5871 - accuracy: 0.6853 - val_loss: 0.5449 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7225 - val_loss: 0.5391 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7336 - val_loss: 0.5330 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7441 - val_loss: 0.5313 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7509 - val_loss: 0.5338 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7618 - val_loss: 0.5335 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7689 - val_loss: 0.5360 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4672 - accuracy: 0.7771 - val_loss: 0.5362 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4552 - accuracy: 0.7852 - val_loss: 0.5434 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4424 - accuracy: 0.7930 - val_loss: 0.5477 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 11/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4291 - accuracy: 0.8018
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4297 - accuracy: 0.8015 - val_loss: 0.5538 - val_accuracy: 0.7251 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42196817168700745
Confusion Matrix :
 [[2672 1375]
 [ 973 3075]]
Accuracy on test set:    0.7099444101297097
Sensitivity:    0.7596343873517787 	 Specificity:    0.6602421546824808
Precision  : 0.6910112359550562
Area Under Curve:    0.7099382710171298
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5855 - accuracy: 0.6845 - val_loss: 0.5491 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7239 - val_loss: 0.5492 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7328 - val_loss: 0.5431 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7421 - val_loss: 0.5401 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7489 - val_loss: 0.5394 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4985 - accuracy: 0.7564 - val_loss: 0.5449 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4856 - accuracy: 0.7640 - val_loss: 0.5468 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4728 - accuracy: 0.7725 - val_loss: 0.5503 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4603 - accuracy: 0.7807
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4609 - accuracy: 0.7804 - val_loss: 0.5531 - val_accuracy: 0.7120 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42105326142880584
Confusion Matrix :
 [[2879 1168]
 [1175 2872]]
Accuracy on test set:    0.7105263157894737
Sensitivity:    0.7096614776377563 	 Specificity:    0.711391153941191
Precision  : 0.7108910891089109
Area Under Curve:    0.7105263157894737
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5881 - accuracy: 0.6842 - val_loss: 0.5559 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7228 - val_loss: 0.5468 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7306 - val_loss: 0.5484 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7392 - val_loss: 0.5459 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5115 - accuracy: 0.7464 - val_loss: 0.5470 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5003 - accuracy: 0.7535 - val_loss: 0.5447 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4899 - accuracy: 0.7622
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4903 - accuracy: 0.7622 - val_loss: 0.5503 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43916580960363666
Confusion Matrix :
 [[2834 1213]
 [1058 2989]]
Accuracy on test set:    0.7194217939214232
Sensitivity:    0.7385717815665925 	 Specificity:    0.700271806276254
Precision  : 0.7113279390766302
Area Under Curve:    0.7194217939214234
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5876 - accuracy: 0.6842 - val_loss: 0.5527 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7231 - val_loss: 0.5444 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7343 - val_loss: 0.5387 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7443 - val_loss: 0.5383 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7515 - val_loss: 0.5387 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7587 - val_loss: 0.5427 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7651 - val_loss: 0.5430 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4727 - accuracy: 0.7734 - val_loss: 0.5472 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4579 - accuracy: 0.7835 - val_loss: 0.5478 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4494 - accuracy: 0.7898 - val_loss: 0.5484 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4384 - accuracy: 0.7951 - val_loss: 0.5602 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 12/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4267 - accuracy: 0.8040
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4275 - accuracy: 0.8033 - val_loss: 0.5610 - val_accuracy: 0.7222 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.41907955608961855
Confusion Matrix :
 [[2863 1184]
 [1167 2880]]
Accuracy on test set:    0.7095379293303682
Sensitivity:    0.7116382505559674 	 Specificity:    0.707437608104769
Precision  : 0.7086614173228346
Area Under Curve:    0.7095379293303682
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5883 - accuracy: 0.6832 - val_loss: 0.5490 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7222 - val_loss: 0.5396 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7320 - val_loss: 0.5370 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5206 - accuracy: 0.7389 - val_loss: 0.5397 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7474 - val_loss: 0.5368 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4986 - accuracy: 0.7562 - val_loss: 0.5387 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.7654 - val_loss: 0.5414 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4757 - accuracy: 0.7721 - val_loss: 0.5567 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4634 - accuracy: 0.7812 - val_loss: 0.5508 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4529 - accuracy: 0.7876 - val_loss: 0.5531 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 11/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4362 - accuracy: 0.7984
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4377 - accuracy: 0.7973 - val_loss: 0.5562 - val_accuracy: 0.7116 - lr: 0.0010
253/253 [==============================] - 0s 877us/step
Independent Testing Matthews Correlation:  0.43738323621779285
Confusion Matrix :
 [[2979 1068]
 [1210 2837]]
Accuracy on test set:    0.7185569557697059
Sensitivity:    0.7010130961205832 	 Specificity:    0.7361008154188288
Precision  : 0.7265044814340589
Area Under Curve:    0.718556955769706
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6836 - val_loss: 0.5508 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7198 - val_loss: 0.5441 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5338 - accuracy: 0.7305 - val_loss: 0.5437 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5232 - accuracy: 0.7376 - val_loss: 0.5426 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7473 - val_loss: 0.5418 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.7530 - val_loss: 0.5421 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4903 - accuracy: 0.7619 - val_loss: 0.5450 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4778 - accuracy: 0.7705 - val_loss: 0.5492 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4667 - accuracy: 0.7787 - val_loss: 0.5526 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4535 - accuracy: 0.7872 - val_loss: 0.5604 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 11/400
250/257 [============================>.] - ETA: 0s - loss: 0.4423 - accuracy: 0.7940
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4424 - accuracy: 0.7937 - val_loss: 0.5631 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.450220051962646
Confusion Matrix :
 [[2948 1099]
 [1126 2921]]
Accuracy on test set:    0.72510501606128
Sensitivity:    0.7217692117617989 	 Specificity:    0.7284408203607611
Precision  : 0.7266169154228855
Area Under Curve:    0.72510501606128
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5882 - accuracy: 0.6843 - val_loss: 0.5563 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7205 - val_loss: 0.5440 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5327 - accuracy: 0.7324 - val_loss: 0.5432 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7422 - val_loss: 0.5457 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7480 - val_loss: 0.5428 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7574 - val_loss: 0.5448 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4870 - accuracy: 0.7645
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7634 - val_loss: 0.5464 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4751887791229669
Confusion Matrix :
 [[3177  870]
 [1263 2784]]
Accuracy on test set:    0.7364714603409933
Sensitivity:    0.6879169755374351 	 Specificity:    0.7850259451445515
Precision  : 0.7619047619047619
Area Under Curve:    0.7364714603409933
(8094, 2560) (8094,)
Mean MCC = 0.4286 + 0.0209 and Mean AUC = 0.7139 + 0.0104
Mean Sensitivity = 0.7159 + 0.0283 and Mean Specificity = 0.7119 + 0.0370 and Mean Accuracy = 0.7139 + 0.0104
Mean Precision = 0.7142 + 0.0207





Seed   : 885580
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5888 - accuracy: 0.6831 - val_loss: 0.5614 - val_accuracy: 0.7054 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7234 - val_loss: 0.5505 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7334 - val_loss: 0.5499 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7430 - val_loss: 0.5561 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5054 - accuracy: 0.7518 - val_loss: 0.5526 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7592 - val_loss: 0.5535 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.7651 - val_loss: 0.5594 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7743 - val_loss: 0.5557 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4627 - accuracy: 0.7806 - val_loss: 0.5765 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4475 - accuracy: 0.7911
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4479 - accuracy: 0.7906 - val_loss: 0.5705 - val_accuracy: 0.7127 - lr: 0.0010
253/253 [==============================] - 0s 791us/step
Independent Testing Matthews Correlation:  0.4140177179170062
Confusion Matrix :
 [[2634 1414]
 [ 968 3079]]
Accuracy on test set:    0.7057442865966647
Sensitivity:    0.7608104768964665 	 Specificity:    0.650691699604743
Precision  : 0.6852882261295349
Area Under Curve:    0.7057510882506048
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5848 - accuracy: 0.6866 - val_loss: 0.5572 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7243 - val_loss: 0.5514 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5268 - accuracy: 0.7351 - val_loss: 0.5634 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7431 - val_loss: 0.5473 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7511 - val_loss: 0.5501 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7575 - val_loss: 0.5593 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7670 - val_loss: 0.5523 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4731 - accuracy: 0.7731 - val_loss: 0.5576 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4609 - accuracy: 0.7799
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4610 - accuracy: 0.7799 - val_loss: 0.5590 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4251111068961278
Confusion Matrix :
 [[2783 1265]
 [1064 2983]]
Accuracy on test set:    0.7122915379864113
Sensitivity:    0.7370892018779343 	 Specificity:    0.6875
Precision  : 0.7022128060263654
Area Under Curve:    0.7122946009389671
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5886 - accuracy: 0.6830 - val_loss: 0.5496 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7208 - val_loss: 0.5421 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7325 - val_loss: 0.5394 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7392 - val_loss: 0.5435 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7479 - val_loss: 0.5455 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4980 - accuracy: 0.7558 - val_loss: 0.5428 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7628 - val_loss: 0.5487 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4745 - accuracy: 0.7726
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7725 - val_loss: 0.5523 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4226183879615727
Confusion Matrix :
 [[2863 1184]
 [1153 2895]]
Accuracy on test set:    0.7113032736256949
Sensitivity:    0.7151679841897233 	 Specificity:    0.707437608104769
Precision  : 0.7097327776415788
Area Under Curve:    0.7113027961472461
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5846 - accuracy: 0.6862 - val_loss: 0.5477 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7213 - val_loss: 0.5379 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7333 - val_loss: 0.5371 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7403 - val_loss: 0.5352 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7482 - val_loss: 0.5355 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7552 - val_loss: 0.5353 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4848 - accuracy: 0.7632 - val_loss: 0.5426 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7741 - val_loss: 0.5491 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4588 - accuracy: 0.7831 - val_loss: 0.5441 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4451 - accuracy: 0.7917 - val_loss: 0.5526 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4329 - accuracy: 0.7983 - val_loss: 0.5566 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4198 - accuracy: 0.8056 - val_loss: 0.5639 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 13/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4078 - accuracy: 0.8142
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4082 - accuracy: 0.8140 - val_loss: 0.5710 - val_accuracy: 0.7220 - lr: 0.0010
253/253 [==============================] - 0s 791us/step
Independent Testing Matthews Correlation:  0.4163885919213573
Confusion Matrix :
 [[2710 1337]
 [1030 3018]]
Accuracy on test set:    0.707597282273008
Sensitivity:    0.7455533596837944 	 Specificity:    0.6696318260439832
Precision  : 0.6929965556831228
Area Under Curve:    0.7075925928638888
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5871 - accuracy: 0.6843 - val_loss: 0.5490 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7235 - val_loss: 0.5418 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7322 - val_loss: 0.5386 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7409 - val_loss: 0.5427 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7489 - val_loss: 0.5520 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7557 - val_loss: 0.5430 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4862 - accuracy: 0.7645 - val_loss: 0.5458 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4745 - accuracy: 0.7716
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7716 - val_loss: 0.5447 - val_accuracy: 0.7252 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4361642727921716
Confusion Matrix :
 [[2805 1242]
 [1042 3005]]
Accuracy on test set:    0.7178156659253768
Sensitivity:    0.7425253274030146 	 Specificity:    0.6931060044477391
Precision  : 0.7075582764304215
Area Under Curve:    0.7178156659253768
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 4ms/step - loss: 0.5886 - accuracy: 0.6827 - val_loss: 0.5519 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7233 - val_loss: 0.5419 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7326 - val_loss: 0.5418 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7431 - val_loss: 0.5418 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7511 - val_loss: 0.5465 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7570 - val_loss: 0.5474 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7670 - val_loss: 0.5539 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7731 - val_loss: 0.5530 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4608 - accuracy: 0.7808 - val_loss: 0.5533 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4483 - accuracy: 0.7891 - val_loss: 0.5559 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4366 - accuracy: 0.7971 - val_loss: 0.5633 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 12/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4237 - accuracy: 0.8046
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4237 - accuracy: 0.8047 - val_loss: 0.5678 - val_accuracy: 0.7167 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.419995716986559
Confusion Matrix :
 [[2932 1115]
 [1233 2814]]
Accuracy on test set:    0.7099085742525327
Sensitivity:    0.6953298739807264 	 Specificity:    0.724487274524339
Precision  : 0.7162127767879868
Area Under Curve:    0.7099085742525327
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5908 - accuracy: 0.6824 - val_loss: 0.5502 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7233 - val_loss: 0.5491 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7332 - val_loss: 0.5406 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7423 - val_loss: 0.5413 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7504 - val_loss: 0.5425 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7590 - val_loss: 0.5449 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.7679 - val_loss: 0.5431 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.7797 - val_loss: 0.5514 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4539 - accuracy: 0.7873 - val_loss: 0.5522 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4420 - accuracy: 0.7941 - val_loss: 0.5566 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 11/400
251/257 [============================>.] - ETA: 0s - loss: 0.4254 - accuracy: 0.8059
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4257 - accuracy: 0.8055 - val_loss: 0.5699 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 885us/step
Independent Testing Matthews Correlation:  0.4285111132999943
Confusion Matrix :
 [[2703 1344]
 [ 976 3071]]
Accuracy on test set:    0.713367926859402
Sensitivity:    0.7588337039782554 	 Specificity:    0.6679021497405485
Precision  : 0.6955832389580974
Area Under Curve:    0.713367926859402
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5851 - accuracy: 0.6863 - val_loss: 0.5469 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7237 - val_loss: 0.5437 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5283 - accuracy: 0.7338 - val_loss: 0.5419 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5184 - accuracy: 0.7412 - val_loss: 0.5401 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7495 - val_loss: 0.5424 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7585 - val_loss: 0.5460 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7655 - val_loss: 0.5465 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7734 - val_loss: 0.5444 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4607 - accuracy: 0.7829
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4607 - accuracy: 0.7829 - val_loss: 0.5518 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 961us/step
Independent Testing Matthews Correlation:  0.42648887428412946
Confusion Matrix :
 [[2888 1159]
 [1162 2885]]
Accuracy on test set:    0.7132443785520138
Sensitivity:    0.7128737336298493 	 Specificity:    0.7136150234741784
Precision  : 0.713402571711177
Area Under Curve:    0.713244378552014
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5888 - accuracy: 0.6850 - val_loss: 0.5632 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7214 - val_loss: 0.5485 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7334 - val_loss: 0.5477 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5228 - accuracy: 0.7384 - val_loss: 0.5475 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5128 - accuracy: 0.7471 - val_loss: 0.5490 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.7543 - val_loss: 0.5487 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4923 - accuracy: 0.7606 - val_loss: 0.5534 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7672 - val_loss: 0.5604 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7761 - val_loss: 0.5546 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4602 - accuracy: 0.7839 - val_loss: 0.5619 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 11/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4453 - accuracy: 0.7938
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4461 - accuracy: 0.7929 - val_loss: 0.5659 - val_accuracy: 0.7148 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46546763501016425
Confusion Matrix :
 [[2908 1139]
 [1025 3022]]
Accuracy on test set:    0.7326414628119595
Sensitivity:    0.746725969854213 	 Specificity:    0.7185569557697059
Precision  : 0.7262677241047825
Area Under Curve:    0.7326414628119595
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5907 - accuracy: 0.6836 - val_loss: 0.5588 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7220 - val_loss: 0.5484 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7305 - val_loss: 0.5496 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5219 - accuracy: 0.7384 - val_loss: 0.5521 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5116 - accuracy: 0.7472 - val_loss: 0.5486 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.7553 - val_loss: 0.5531 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7627 - val_loss: 0.5501 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.7703 - val_loss: 0.5565 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4675 - accuracy: 0.7783 - val_loss: 0.5595 - val_accuracy: 0.7156 - lr: 0.0010

Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4541 - accuracy: 0.7867 - val_loss: 0.5611 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4421 - accuracy: 0.7949 - val_loss: 0.5691 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 12/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4310 - accuracy: 0.8003
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4309 - accuracy: 0.8005 - val_loss: 0.5812 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 840us/step
Independent Testing Matthews Correlation:  0.48415966072279065
Confusion Matrix :
 [[3102  945]
 [1145 2902]]
Accuracy on test set:    0.7417840375586855
Sensitivity:    0.7170743760810477 	 Specificity:    0.7664936990363233
Precision  : 0.7543540421107356
Area Under Curve:    0.7417840375586855
(8094, 2560) (8094,)
Mean MCC = 0.4339 + 0.0217 and Mean AUC = 0.7166 + 0.0110
Mean Sensitivity = 0.7332 + 0.0207 and Mean Specificity = 0.6999 + 0.0319 and Mean Accuracy = 0.7166 + 0.0110
Mean Precision = 0.7104 + 0.0186





Seed   : 275815
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5821 - accuracy: 0.6863 - val_loss: 0.5600 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5395 - accuracy: 0.7275 - val_loss: 0.5530 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5246 - accuracy: 0.7379 - val_loss: 0.5503 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5125 - accuracy: 0.7461 - val_loss: 0.5562 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7530 - val_loss: 0.5532 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7641 - val_loss: 0.5588 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4764 - accuracy: 0.7709
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4767 - accuracy: 0.7707 - val_loss: 0.5713 - val_accuracy: 0.7053 - lr: 0.0010
253/253 [==============================] - 0s 905us/step
Independent Testing Matthews Correlation:  0.3967241273291494
Confusion Matrix :
 [[2450 1598]
 [ 870 3177]]
Accuracy on test set:    0.6951204447189623
Sensitivity:    0.7850259451445515 	 Specificity:    0.6052371541501976
Precision  : 0.6653403141361256
Area Under Curve:    0.6951315496473746
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5896 - accuracy: 0.6821 - val_loss: 0.5566 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7227 - val_loss: 0.5522 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7361 - val_loss: 0.5511 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7423 - val_loss: 0.5523 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7506 - val_loss: 0.5579 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7595 - val_loss: 0.5548 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4827 - accuracy: 0.7672 - val_loss: 0.5620 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 8/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4719 - accuracy: 0.7756
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4716 - accuracy: 0.7759 - val_loss: 0.5705 - val_accuracy: 0.7061 - lr: 0.0010
253/253 [==============================] - 0s 961us/step
Independent Testing Matthews Correlation:  0.43147553370806807
Confusion Matrix :
 [[3061  987]
 [1320 2727]]
Accuracy on test set:    0.7150092649783817
Sensitivity:    0.6738324684951816 	 Specificity:    0.7561758893280632
Precision  : 0.7342487883683361
Area Under Curve:    0.7150041789116225
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5911 - accuracy: 0.6815 - val_loss: 0.5466 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7205 - val_loss: 0.5384 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7324 - val_loss: 0.5377 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7412 - val_loss: 0.5375 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7489 - val_loss: 0.5381 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7553 - val_loss: 0.5373 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.7619 - val_loss: 0.5415 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7726 - val_loss: 0.5454 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4616 - accuracy: 0.7806 - val_loss: 0.5485 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4490 - accuracy: 0.7894 - val_loss: 0.5550 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4372 - accuracy: 0.7955 - val_loss: 0.5574 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4230 - accuracy: 0.8067
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4234 - accuracy: 0.8064 - val_loss: 0.5648 - val_accuracy: 0.7152 - lr: 0.0010
253/253 [==============================] - 0s 826us/step
Independent Testing Matthews Correlation:  0.41248720090571256
Confusion Matrix :
 [[2872 1175]
 [1203 2845]]
Accuracy on test set:    0.7062384187770229
Sensitivity:    0.7028162055335968 	 Specificity:    0.7096614776377563
Precision  : 0.7077114427860697
Area Under Curve:    0.7062388415856765
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5931 - accuracy: 0.6785 - val_loss: 0.5455 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7211 - val_loss: 0.5384 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7319 - val_loss: 0.5335 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7389 - val_loss: 0.5330 - val_accuracy: 0.7315 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7477 - val_loss: 0.5393 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.7553 - val_loss: 0.5367 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4856 - accuracy: 0.7649 - val_loss: 0.5410 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7716 - val_loss: 0.5422 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4629 - accuracy: 0.7798
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4632 - accuracy: 0.7795 - val_loss: 0.5454 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4160125795254512
Confusion Matrix :
 [[2990 1057]
 [1310 2738]]
Accuracy on test set:    0.707597282273008
Sensitivity:    0.6763833992094862 	 Specificity:    0.7388188781813689
Precision  : 0.7214756258234519
Area Under Curve:    0.7076011386954276
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5871 - accuracy: 0.6849 - val_loss: 0.5556 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7236 - val_loss: 0.5502 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7335 - val_loss: 0.5462 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7409 - val_loss: 0.5432 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.7483 - val_loss: 0.5447 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4991 - accuracy: 0.7554 - val_loss: 0.5477 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4907 - accuracy: 0.7600 - val_loss: 0.5509 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4811 - accuracy: 0.7675 - val_loss: 0.5510 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4692 - accuracy: 0.7767 - val_loss: 0.5553 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4580 - accuracy: 0.7829
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4579 - accuracy: 0.7830 - val_loss: 0.5585 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 762us/step
Independent Testing Matthews Correlation:  0.4097723755632241
Confusion Matrix :
 [[2811 1236]
 [1153 2894]]
Accuracy on test set:    0.704843093649617
Sensitivity:    0.7150976031628367 	 Specificity:    0.6945885841363973
Precision  : 0.700726392251816
Area Under Curve:    0.7048430936496171
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5861 - accuracy: 0.6846 - val_loss: 0.5508 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7229 - val_loss: 0.5475 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7317 - val_loss: 0.5429 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7407 - val_loss: 0.5416 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7489 - val_loss: 0.5434 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7581 - val_loss: 0.5447 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7676 - val_loss: 0.5465 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4690 - accuracy: 0.7763 - val_loss: 0.5548 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4568 - accuracy: 0.7845
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4568 - accuracy: 0.7845 - val_loss: 0.5595 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43348460584708
Confusion Matrix :
 [[2726 1321]
 [ 978 3069]]
Accuracy on test set:    0.715962441314554
Sensitivity:    0.7583395107487028 	 Specificity:    0.6735853718804052
Precision  : 0.6990888382687928
Area Under Curve:    0.715962441314554
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5857 - accuracy: 0.6841 - val_loss: 0.5479 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7226 - val_loss: 0.5459 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7344 - val_loss: 0.5425 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7408 - val_loss: 0.5424 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7506 - val_loss: 0.5446 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7569 - val_loss: 0.5455 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7672 - val_loss: 0.5466 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4701 - accuracy: 0.7756 - val_loss: 0.5492 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4572 - accuracy: 0.7831
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.7833 - val_loss: 0.5562 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4396161130510981
Confusion Matrix :
 [[2757 1290]
 [ 983 3064]]
Accuracy on test set:    0.7191746973066468
Sensitivity:    0.7571040276748209 	 Specificity:    0.6812453669384729
Precision  : 0.7037207165824529
Area Under Curve:    0.719174697306647
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5878 - accuracy: 0.6841 - val_loss: 0.5522 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7236 - val_loss: 0.5448 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7305 - val_loss: 0.5406 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7399 - val_loss: 0.5416 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7483 - val_loss: 0.5394 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7565 - val_loss: 0.5418 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 5ms/step - loss: 0.4848 - accuracy: 0.7650 - val_loss: 0.5437 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4731 - accuracy: 0.7728 - val_loss: 0.5491 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4606 - accuracy: 0.7810 - val_loss: 0.5544 - val_accuracy: 0.7215 - lr: 0.0010

Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4474 - accuracy: 0.7890 - val_loss: 0.5550 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4341 - accuracy: 0.7990 - val_loss: 0.5595 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 12/400
256/257 [============================>.] - ETA: 0s - loss: 0.4243 - accuracy: 0.8041
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4243 - accuracy: 0.8041 - val_loss: 0.5736 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 835us/step
Independent Testing Matthews Correlation:  0.41574505982252896
Confusion Matrix :
 [[2950 1097]
 [1269 2778]]
Accuracy on test set:    0.7076847047195454
Sensitivity:    0.6864343958487769 	 Specificity:    0.7289350135903138
Precision  : 0.7169032258064516
Area Under Curve:    0.7076847047195454
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5893 - accuracy: 0.6811 - val_loss: 0.5518 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7206 - val_loss: 0.5516 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7335 - val_loss: 0.5420 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7435 - val_loss: 0.5435 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7504 - val_loss: 0.5442 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7598 - val_loss: 0.5449 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7667 - val_loss: 0.5464 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4706 - accuracy: 0.7761 - val_loss: 0.5473 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4569 - accuracy: 0.7841 - val_loss: 0.5575 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4438 - accuracy: 0.7919 - val_loss: 0.5590 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4311 - accuracy: 0.8010 - val_loss: 0.5688 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 12/400
249/257 [============================>.] - ETA: 0s - loss: 0.4201 - accuracy: 0.8069
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4200 - accuracy: 0.8070 - val_loss: 0.5718 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 992us/step
Independent Testing Matthews Correlation:  0.433898755513431
Confusion Matrix :
 [[3018 1029]
 [1265 2782]]
Accuracy on test set:    0.7165801828514949
Sensitivity:    0.6874227823078823 	 Specificity:    0.7457375833951075
Precision  : 0.7299921280503805
Area Under Curve:    0.7165801828514948
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5920 - accuracy: 0.6807 - val_loss: 0.5571 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5498 - accuracy: 0.7181 - val_loss: 0.5513 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5348 - accuracy: 0.7297 - val_loss: 0.5542 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7396 - val_loss: 0.5503 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7466 - val_loss: 0.5461 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4987 - accuracy: 0.7574 - val_loss: 0.5514 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7654 - val_loss: 0.5525 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7743 - val_loss: 0.5526 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4605 - accuracy: 0.7838 - val_loss: 0.5556 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4483 - accuracy: 0.7901 - val_loss: 0.5629 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4339 - accuracy: 0.7995 - val_loss: 0.5726 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 12/400
249/257 [============================>.] - ETA: 0s - loss: 0.4238 - accuracy: 0.8056
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4236 - accuracy: 0.8057 - val_loss: 0.5846 - val_accuracy: 0.7098 - lr: 0.0010
253/253 [==============================] - 0s 883us/step
Independent Testing Matthews Correlation:  0.45635471429636043
Confusion Matrix :
 [[3226  821]
 [1398 2649]]
Accuracy on test set:    0.7258463059056091
Sensitivity:    0.6545589325426242 	 Specificity:    0.797133679268594
Precision  : 0.763400576368876
Area Under Curve:    0.7258463059056091
(8094, 2560) (8094,)
Mean MCC = 0.4246 + 0.0166 and Mean AUC = 0.7114 + 0.0083
Mean Sensitivity = 0.7097 + 0.0410 and Mean Specificity = 0.7131 + 0.0505 and Mean Accuracy = 0.7114 + 0.0083
Mean Precision = 0.7143 + 0.0247





Seed   : 612018
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6856 - val_loss: 0.5634 - val_accuracy: 0.7023 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7260 - val_loss: 0.5621 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5267 - accuracy: 0.7354 - val_loss: 0.5515 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7452 - val_loss: 0.5549 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5021 - accuracy: 0.7532 - val_loss: 0.5534 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4890 - accuracy: 0.7608 - val_loss: 0.5580 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.7707 - val_loss: 0.5592 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4638 - accuracy: 0.7793 - val_loss: 0.5722 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4516 - accuracy: 0.7866 - val_loss: 0.5729 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4367 - accuracy: 0.7959
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4367 - accuracy: 0.7960 - val_loss: 0.5800 - val_accuracy: 0.7084 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39865363677650034
Confusion Matrix :
 [[2568 1480]
 [ 967 3080]]
Accuracy on test set:    0.6977146386658432
Sensitivity:    0.7610575735112429 	 Specificity:    0.6343873517786561
Precision  : 0.6754385964912281
Area Under Curve:    0.6977224626449495
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5836 - accuracy: 0.6880 - val_loss: 0.5635 - val_accuracy: 0.7014 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5402 - accuracy: 0.7280 - val_loss: 0.5534 - val_accuracy: 0.7058 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5268 - accuracy: 0.7351 - val_loss: 0.5516 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7427 - val_loss: 0.5482 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7513 - val_loss: 0.5518 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7584 - val_loss: 0.5548 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4817 - accuracy: 0.7677 - val_loss: 0.5521 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4703 - accuracy: 0.7754 - val_loss: 0.5584 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4581 - accuracy: 0.7841 - val_loss: 0.5613 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4456 - accuracy: 0.7896 - val_loss: 0.5622 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4331 - accuracy: 0.7976
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4328 - accuracy: 0.7976 - val_loss: 0.5747 - val_accuracy: 0.7104 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4090270343550291
Confusion Matrix :
 [[2751 1297]
 [1097 2950]]
Accuracy on test set:    0.7042618900555899
Sensitivity:    0.7289350135903138 	 Specificity:    0.6795948616600791
Precision  : 0.6946079585589828
Area Under Curve:    0.7042649376251964
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5869 - accuracy: 0.6839 - val_loss: 0.5499 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5423 - accuracy: 0.7260 - val_loss: 0.5444 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5261 - accuracy: 0.7369 - val_loss: 0.5407 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5139 - accuracy: 0.7438 - val_loss: 0.5500 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5033 - accuracy: 0.7504 - val_loss: 0.5402 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 6/400
251/257 [============================>.] - ETA: 0s - loss: 0.4906 - accuracy: 0.7625
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7626 - val_loss: 0.5439 - val_accuracy: 0.7139 - lr: 0.0010
253/253 [==============================] - 0s 957us/step
Independent Testing Matthews Correlation:  0.424394286376121
Confusion Matrix :
 [[2756 1291]
 [1042 3006]]
Accuracy on test set:    0.7117974058060531
Sensitivity:    0.7425889328063241 	 Specificity:    0.6809982703236965
Precision  : 0.6995578310449151
Area Under Curve:    0.7117936015650104
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5895 - accuracy: 0.6837 - val_loss: 0.5496 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7208 - val_loss: 0.5427 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7326 - val_loss: 0.5391 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7413 - val_loss: 0.5413 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7499 - val_loss: 0.5389 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7555 - val_loss: 0.5409 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7664 - val_loss: 0.5437 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4734 - accuracy: 0.7725 - val_loss: 0.5487 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4597 - accuracy: 0.7840 - val_loss: 0.5513 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4475 - accuracy: 0.7924 - val_loss: 0.5555 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4348 - accuracy: 0.7992 - val_loss: 0.5612 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - ETA: 0s - loss: 0.4225 - accuracy: 0.8055
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4225 - accuracy: 0.8055 - val_loss: 0.5754 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42683608055100686
Confusion Matrix :
 [[2745 1302]
 [1022 3026]]
Accuracy on test set:    0.7129092032118591
Sensitivity:    0.7475296442687747 	 Specificity:    0.6782802075611564
Precision  : 0.6991682070240296
Area Under Curve:    0.7129049259149656
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6865 - val_loss: 0.5634 - val_accuracy: 0.7031 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7233 - val_loss: 0.5473 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7335 - val_loss: 0.5470 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7427 - val_loss: 0.5456 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7513 - val_loss: 0.5464 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4903 - accuracy: 0.7600 - val_loss: 0.5479 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4775 - accuracy: 0.7711 - val_loss: 0.5624 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4645 - accuracy: 0.7787 - val_loss: 0.5627 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4493 - accuracy: 0.7890 - val_loss: 0.5638 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4368 - accuracy: 0.7956
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4368 - accuracy: 0.7958 - val_loss: 0.5790 - val_accuracy: 0.7120 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41965080777842273
Confusion Matrix :
 [[2695 1352]
 [1003 3044]]
Accuracy on test set:    0.7090437361008154
Sensitivity:    0.7521620953792933 	 Specificity:    0.6659253768223375
Precision  : 0.6924476797088263
Area Under Curve:    0.7090437361008155
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5881 - accuracy: 0.6837 - val_loss: 0.5540 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5423 - accuracy: 0.7247 - val_loss: 0.5466 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7350 - val_loss: 0.5436 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5149 - accuracy: 0.7440 - val_loss: 0.5422 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7509 - val_loss: 0.5467 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4924 - accuracy: 0.7615 - val_loss: 0.5510 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7667 - val_loss: 0.5489 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4723 - accuracy: 0.7722 - val_loss: 0.5512 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4582 - accuracy: 0.7812 - val_loss: 0.5531 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4478 - accuracy: 0.7886 - val_loss: 0.5584 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4356 - accuracy: 0.7973 - val_loss: 0.5547 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4255 - accuracy: 0.8030 - val_loss: 0.5648 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 13/400
241/257 [===========================>..] - ETA: 0s - loss: 0.4129 - accuracy: 0.8098
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4137 - accuracy: 0.8093 - val_loss: 0.5746 - val_accuracy: 0.7202 - lr: 0.0010
253/253 [==============================] - 0s 766us/step
Independent Testing Matthews Correlation:  0.440905185385549
Confusion Matrix :
 [[2662 1385]
 [ 891 3156]]
Accuracy on test set:    0.7188040523844823
Sensitivity:    0.7798369162342476 	 Specificity:    0.657771188534717
Precision  : 0.6950011010790574
Area Under Curve:    0.7188040523844823
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6856 - val_loss: 0.5524 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7221 - val_loss: 0.5464 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.7350 - val_loss: 0.5482 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5130 - accuracy: 0.7453 - val_loss: 0.5460 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5022 - accuracy: 0.7526 - val_loss: 0.5445 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.7599 - val_loss: 0.5531 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4775 - accuracy: 0.7688 - val_loss: 0.5509 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4659 - accuracy: 0.7779 - val_loss: 0.5609 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4512 - accuracy: 0.7876 - val_loss: 0.5632 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 10/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4374 - accuracy: 0.7945
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4387 - accuracy: 0.7941 - val_loss: 0.5629 - val_accuracy: 0.7227 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42886227205636396
Confusion Matrix :
 [[2726 1321]
 [ 996 3051]]
Accuracy on test set:    0.7137385717815666
Sensitivity:    0.7538917716827279 	 Specificity:    0.6735853718804052
Precision  : 0.6978499542543458
Area Under Curve:    0.7137385717815665
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5949 - accuracy: 0.6773 - val_loss: 0.5537 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5489 - accuracy: 0.7221 - val_loss: 0.5462 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5326 - accuracy: 0.7308 - val_loss: 0.5392 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7413 - val_loss: 0.5426 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7487 - val_loss: 0.5394 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7581 - val_loss: 0.5470 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.7650 - val_loss: 0.5464 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4704 - accuracy: 0.7756
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4703 - accuracy: 0.7756 - val_loss: 0.5529 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 857us/step
Independent Testing Matthews Correlation:  0.4363838257134457
Confusion Matrix :
 [[2921 1126]
 [1155 2892]]
Accuracy on test set:    0.7181863108475414
Sensitivity:    0.7146034099332839 	 Specificity:    0.7217692117617989
Precision  : 0.719761075161772
Area Under Curve:    0.7181863108475414
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5898 - accuracy: 0.6827 - val_loss: 0.5547 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7227 - val_loss: 0.5436 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5327 - accuracy: 0.7327 - val_loss: 0.5426 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7400 - val_loss: 0.5411 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7486 - val_loss: 0.5429 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4991 - accuracy: 0.7550 - val_loss: 0.5514 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4892 - accuracy: 0.7615 - val_loss: 0.5479 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7688 - val_loss: 0.5495 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7744 - val_loss: 0.5537 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4576 - accuracy: 0.7825 - val_loss: 0.5537 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4464 - accuracy: 0.7889 - val_loss: 0.5609 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4345 - accuracy: 0.7971 - val_loss: 0.5678 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4240 - accuracy: 0.8039 - val_loss: 0.5658 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4150 - accuracy: 0.8063 - val_loss: 0.5737 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 15/400
253/257 [============================>.] - ETA: 0s - loss: 0.4022 - accuracy: 0.8157
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4022 - accuracy: 0.8159 - val_loss: 0.5880 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4353853118571714
Confusion Matrix :
 [[2909 1138]
 [1147 2900]]
Accuracy on test set:    0.7176921176179887
Sensitivity:    0.7165801828514949 	 Specificity:    0.7188040523844823
Precision  : 0.7181773155027241
Area Under Curve:    0.7176921176179886
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5945 - accuracy: 0.6802 - val_loss: 0.5542 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5519 - accuracy: 0.7184 - val_loss: 0.5498 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5376 - accuracy: 0.7300 - val_loss: 0.5425 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7341 - val_loss: 0.5413 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7419 - val_loss: 0.5458 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7490 - val_loss: 0.5433 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7559 - val_loss: 0.5470 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7627 - val_loss: 0.5517 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4780 - accuracy: 0.7724
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7717 - val_loss: 0.5489 - val_accuracy: 0.7226 - lr: 0.0010
253/253 [==============================] - 0s 867us/step
Independent Testing Matthews Correlation:  0.4809246144428161
Confusion Matrix :
 [[3070  977]
 [1125 2922]]
Accuracy on test set:    0.7403014578700272
Sensitivity:    0.7220163083765753 	 Specificity:    0.7585866073634792
Precision  : 0.7494229289561426
Area Under Curve:    0.7403014578700273
(8094, 2560) (8094,)
Mean MCC = 0.4301 + 0.0209 and Mean AUC = 0.7144 + 0.0107
Mean Sensitivity = 0.7419 + 0.0201 and Mean Specificity = 0.6870 + 0.0343 and Mean Accuracy = 0.7144 + 0.0107
Mean Precision = 0.7041 + 0.0193





Seed   : 978340
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5880 - accuracy: 0.6831 - val_loss: 0.5668 - val_accuracy: 0.7039 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7237 - val_loss: 0.5576 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7341 - val_loss: 0.5554 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7407 - val_loss: 0.5596 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7485 - val_loss: 0.5664 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.7546 - val_loss: 0.5595 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7615 - val_loss: 0.5587 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7682 - val_loss: 0.5646 - val_accuracy: 0.7058 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4688 - accuracy: 0.7765 - val_loss: 0.5640 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4563 - accuracy: 0.7839 - val_loss: 0.5812 - val_accuracy: 0.7058 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4460 - accuracy: 0.7911 - val_loss: 0.5759 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 12/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4310 - accuracy: 0.7992
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4314 - accuracy: 0.7984 - val_loss: 0.5784 - val_accuracy: 0.7109 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4159022759043075
Confusion Matrix :
 [[2801 1247]
 [1118 2929]]
Accuracy on test set:    0.7078443483631871
Sensitivity:    0.7237459846800098 	 Specificity:    0.6919466403162056
Precision  : 0.7013888888888888
Area Under Curve:    0.7078463124981077
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5856 - accuracy: 0.6865 - val_loss: 0.5674 - val_accuracy: 0.7006 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5417 - accuracy: 0.7240 - val_loss: 0.5544 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5257 - accuracy: 0.7353 - val_loss: 0.5569 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5135 - accuracy: 0.7436 - val_loss: 0.5576 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5028 - accuracy: 0.7519 - val_loss: 0.5533 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4907 - accuracy: 0.7605 - val_loss: 0.5545 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4778 - accuracy: 0.7695 - val_loss: 0.5574 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4669 - accuracy: 0.7757 - val_loss: 0.5623 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4531 - accuracy: 0.7879 - val_loss: 0.5662 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4407 - accuracy: 0.7946 - val_loss: 0.5711 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 11/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4280 - accuracy: 0.8023
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4287 - accuracy: 0.8014 - val_loss: 0.5742 - val_accuracy: 0.7115 - lr: 0.0010
253/253 [==============================] - 0s 940us/step
Independent Testing Matthews Correlation:  0.40672821084873395
Confusion Matrix :
 [[2787 1261]
 [1141 2906]]
Accuracy on test set:    0.7032736256948734
Sensitivity:    0.7180627625401532 	 Specificity:    0.6884881422924901
Precision  : 0.697384209263259
Area Under Curve:    0.7032754524163217
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5846 - accuracy: 0.6872 - val_loss: 0.5509 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400

257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7229 - val_loss: 0.5443 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7331 - val_loss: 0.5434 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7419 - val_loss: 0.5435 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7498 - val_loss: 0.5469 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7591 - val_loss: 0.5474 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7657 - val_loss: 0.5577 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4701 - accuracy: 0.7747
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4703 - accuracy: 0.7746 - val_loss: 0.5569 - val_accuracy: 0.7167 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4250603718708235
Confusion Matrix :
 [[2629 1418]
 [ 922 3126]]
Accuracy on test set:    0.7109326744904262
Sensitivity:    0.7722332015810277 	 Specificity:    0.6496170002470966
Precision  : 0.6879401408450704
Area Under Curve:    0.7109251009140622
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5830 - accuracy: 0.6893 - val_loss: 0.5499 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7240 - val_loss: 0.5472 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5258 - accuracy: 0.7358 - val_loss: 0.5412 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7418 - val_loss: 0.5426 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7506 - val_loss: 0.5431 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7581 - val_loss: 0.5421 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.7670 - val_loss: 0.5526 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 3ms/step - loss: 0.4719 - accuracy: 0.7737 - val_loss: 0.5533 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4603 - accuracy: 0.7825 - val_loss: 0.5552 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 10/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4458 - accuracy: 0.7926
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4464 - accuracy: 0.7923 - val_loss: 0.5588 - val_accuracy: 0.7167 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4190931348887152
Confusion Matrix :
 [[2932 1115]
 [1237 2811]]
Accuracy on test set:    0.7094502779493514
Sensitivity:    0.6944169960474308 	 Specificity:    0.724487274524339
Precision  : 0.7159959246051961
Area Under Curve:    0.7094521352858849
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5884 - accuracy: 0.6834 - val_loss: 0.5518 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7219 - val_loss: 0.5451 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7326 - val_loss: 0.5474 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7388 - val_loss: 0.5478 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5109 - accuracy: 0.7467 - val_loss: 0.5470 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4980 - accuracy: 0.7559 - val_loss: 0.5467 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4867 - accuracy: 0.7642 - val_loss: 0.5489 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4740 - accuracy: 0.7723
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7723 - val_loss: 0.5528 - val_accuracy: 0.7170 - lr: 0.0010
253/253 [==============================] - 0s 885us/step
Independent Testing Matthews Correlation:  0.42676276657040757
Confusion Matrix :
 [[2959 1088]
 [1233 2814]]
Accuracy on test set:    0.7132443785520138
Sensitivity:    0.6953298739807264 	 Specificity:    0.7311588831233012
Precision  : 0.7211686314710405
Area Under Curve:    0.7132443785520138
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5870 - accuracy: 0.6845 - val_loss: 0.5539 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7239 - val_loss: 0.5548 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5263 - accuracy: 0.7350 - val_loss: 0.5468 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7412 - val_loss: 0.5495 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5034 - accuracy: 0.7513 - val_loss: 0.5464 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 6/400
249/257 [============================>.] - ETA: 0s - loss: 0.4918 - accuracy: 0.7592
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7591 - val_loss: 0.5496 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 829us/step
Independent Testing Matthews Correlation:  0.4292101742697867
Confusion Matrix :
 [[2884 1163]
 [1147 2900]]
Accuracy on test set:    0.7146034099332839
Sensitivity:    0.7165801828514949 	 Specificity:    0.7126266370150729
Precision  : 0.7137583066699483
Area Under Curve:    0.7146034099332839
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5899 - accuracy: 0.6823 - val_loss: 0.5548 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7217 - val_loss: 0.5470 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7335 - val_loss: 0.5457 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7396 - val_loss: 0.5448 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7496 - val_loss: 0.5450 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7594 - val_loss: 0.5469 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4819 - accuracy: 0.7675 - val_loss: 0.5502 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4684 - accuracy: 0.7773
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7771 - val_loss: 0.5472 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4307665741495766
Confusion Matrix :
 [[2816 1231]
 [1074 2973]]
Accuracy on test set:    0.7152211514702248
Sensitivity:    0.7346182357301705 	 Specificity:    0.6958240672102792
Precision  : 0.7071836346336822
Area Under Curve:    0.7152211514702248
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5873 - accuracy: 0.6838 - val_loss: 0.5616 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7238 - val_loss: 0.5510 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7346 - val_loss: 0.5478 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7419 - val_loss: 0.5474 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5064 - accuracy: 0.7499 - val_loss: 0.5470 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7588 - val_loss: 0.5496 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4827 - accuracy: 0.7672 - val_loss: 0.5510 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4708 - accuracy: 0.7746 - val_loss: 0.5548 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4589 - accuracy: 0.7835 - val_loss: 0.5614 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4474 - accuracy: 0.7915 - val_loss: 0.5645 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4346 - accuracy: 0.7978 - val_loss: 0.5762 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4219 - accuracy: 0.8059
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4226 - accuracy: 0.8053 - val_loss: 0.5698 - val_accuracy: 0.7078 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43144503319781424
Confusion Matrix :
 [[2880 1167]
 [1134 2913]]
Accuracy on test set:    0.7157153446997776
Sensitivity:    0.7197924388435878 	 Specificity:    0.7116382505559674
Precision  : 0.7139705882352941
Area Under Curve:    0.7157153446997776
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5928 - accuracy: 0.6771 - val_loss: 0.5583 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7200 - val_loss: 0.5508 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7305 - val_loss: 0.5493 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7397 - val_loss: 0.5530 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5117 - accuracy: 0.7457 - val_loss: 0.5482 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5024 - accuracy: 0.7523 - val_loss: 0.5500 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4886 - accuracy: 0.7640 - val_loss: 0.5493 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4762 - accuracy: 0.7711 - val_loss: 0.5576 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4669 - accuracy: 0.7799 - val_loss: 0.5572 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4535 - accuracy: 0.7876
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4534 - accuracy: 0.7874 - val_loss: 0.5720 - val_accuracy: 0.7119 - lr: 0.0010
253/253 [==============================] - 0s 984us/step
Independent Testing Matthews Correlation:  0.4622513188209137
Confusion Matrix :
 [[2784 1263]
 [ 920 3127]]
Accuracy on test set:    0.7302940449715839
Sensitivity:    0.7726711144057327 	 Specificity:    0.6879169755374351
Precision  : 0.7123006833712984
Area Under Curve:    0.730294044971584
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5950 - accuracy: 0.6774 - val_loss: 0.5621 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5500 - accuracy: 0.7191 - val_loss: 0.5515 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5355 - accuracy: 0.7291 - val_loss: 0.5476 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5237 - accuracy: 0.7390 - val_loss: 0.5508 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5144 - accuracy: 0.7446 - val_loss: 0.5459 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5028 - accuracy: 0.7534 - val_loss: 0.5553 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 3ms/step - loss: 0.4921 - accuracy: 0.7613 - val_loss: 0.5591 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 3ms/step - loss: 0.4823 - accuracy: 0.7657 - val_loss: 0.5540 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4713 - accuracy: 0.7772
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7771 - val_loss: 0.5564 - val_accuracy: 0.7098 - lr: 0.0010
253/253 [==============================] - 0s 945us/step
Independent Testing Matthews Correlation:  0.4791069531006437
Confusion Matrix :
 [[2880 1167]
 [ 944 3103]]
Accuracy on test set:    0.7391895231035335
Sensitivity:    0.7667407956510995 	 Specificity:    0.7116382505559674
Precision  : 0.7266978922716628
Area Under Curve:    0.7391895231035336
(8094, 2560) (8094,)
Mean MCC = 0.4326 + 0.0207 and Mean AUC = 0.7160 + 0.0102
Mean Sensitivity = 0.7314 + 0.0281 and Mean Specificity = 0.7005 + 0.0221 and Mean Accuracy = 0.7160 + 0.0102
Mean Precision = 0.7098 + 0.0110





Seed   : 196222
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5858 - accuracy: 0.6869 - val_loss: 0.5587 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7239 - val_loss: 0.5496 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5269 - accuracy: 0.7349 - val_loss: 0.5490 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7421 - val_loss: 0.5511 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5048 - accuracy: 0.7514 - val_loss: 0.5486 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7583 - val_loss: 0.5510 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7669 - val_loss: 0.5606 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4708 - accuracy: 0.7735 - val_loss: 0.5600 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4599 - accuracy: 0.7820 - val_loss: 0.5668 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4471 - accuracy: 0.7898
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4474 - accuracy: 0.7890 - val_loss: 0.5673 - val_accuracy: 0.7084 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40404387035399364
Confusion Matrix :
 [[2593 1455]
 [ 969 3078]]
Accuracy on test set:    0.700555898702903
Sensitivity:    0.7605633802816901 	 Specificity:    0.6405632411067194
Precision  : 0.6790205162144275
Area Under Curve:    0.7005633106942047
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5900 - accuracy: 0.6825 - val_loss: 0.5629 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7231 - val_loss: 0.5559 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7350 - val_loss: 0.5540 - val_accuracy: 0.7058 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7415 - val_loss: 0.5485 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7499 - val_loss: 0.5514 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.7568 - val_loss: 0.5517 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4863 - accuracy: 0.7649 - val_loss: 0.5581 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4729 - accuracy: 0.7742 - val_loss: 0.5577 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4596 - accuracy: 0.7822 - val_loss: 0.5615 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4489 - accuracy: 0.7888
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4494 - accuracy: 0.7886 - val_loss: 0.5620 - val_accuracy: 0.7071 - lr: 0.0010
253/253 [==============================] - 0s 901us/step
Independent Testing Matthews Correlation:  0.4078885556265443
Confusion Matrix :
 [[2996 1052]
 [1349 2698]]
Accuracy on test set:    0.7033971587399629
Sensitivity:    0.6666666666666666 	 Specificity:    0.7401185770750988
Precision  : 0.7194666666666667
Area Under Curve:    0.7033926218708827
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5878 - accuracy: 0.6850 - val_loss: 0.5458 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7198 - val_loss: 0.5384 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7316 - val_loss: 0.5327 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7410 - val_loss: 0.5320 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7496 - val_loss: 0.5310 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7554 - val_loss: 0.5301 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4866 - accuracy: 0.7642 - val_loss: 0.5395 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4753 - accuracy: 0.7717 - val_loss: 0.5377 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4642 - accuracy: 0.7776
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4640 - accuracy: 0.7777 - val_loss: 0.5436 - val_accuracy: 0.7238 - lr: 0.0010
253/253 [==============================] - 0s 956us/step
Independent Testing Matthews Correlation:  0.4205113982319652
Confusion Matrix :
 [[2644 1403]
 [ 953 3095]]
Accuracy on test set:    0.7089561457689932
Sensitivity:    0.7645750988142292 	 Specificity:    0.6533234494687423
Precision  : 0.6880835927078701
Area Under Curve:    0.7089492741414858
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5862 - accuracy: 0.6852 - val_loss: 0.5382 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7220 - val_loss: 0.5323 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7319 - val_loss: 0.5295 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7406 - val_loss: 0.5410 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7507 - val_loss: 0.5280 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7563 - val_loss: 0.5294 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.7653 - val_loss: 0.5341 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7721 - val_loss: 0.5459 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4637 - accuracy: 0.7798 - val_loss: 0.5339 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4517 - accuracy: 0.7855
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4524 - accuracy: 0.7853 - val_loss: 0.5418 - val_accuracy: 0.7235 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40812356196208255
Confusion Matrix :
 [[2606 1441]
 [ 966 3082]]
Accuracy on test set:    0.7026559604694256
Sensitivity:    0.7613636363636364 	 Specificity:    0.64393377810724
Precision  : 0.6814061463630334
Area Under Curve:    0.7026487072354382
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6837 - val_loss: 0.5567 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7230 - val_loss: 0.5497 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7339 - val_loss: 0.5455 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7417 - val_loss: 0.5480 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7493 - val_loss: 0.5466 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7569 - val_loss: 0.5529 - val_accuracy: 0.7154 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7647 - val_loss: 0.5500 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4741 - accuracy: 0.7714
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7714 - val_loss: 0.5526 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4331539175375511
Confusion Matrix :
 [[2803 1244]
 [1052 2995]]
Accuracy on test set:    0.7163330862367185
Sensitivity:    0.7400543612552508 	 Specificity:    0.6926118112181863
Precision  : 0.7065345600377447
Area Under Curve:    0.7163330862367185
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5940 - accuracy: 0.6802 - val_loss: 0.5599 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7222 - val_loss: 0.5559 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5327 - accuracy: 0.7317 - val_loss: 0.5530 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7402 - val_loss: 0.5523 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5121 - accuracy: 0.7454 - val_loss: 0.5513 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7539 - val_loss: 0.5513 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7610 - val_loss: 0.5533 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7698 - val_loss: 0.5565 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4663 - accuracy: 0.7795 - val_loss: 0.5587 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 10/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4518 - accuracy: 0.7889
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4528 - accuracy: 0.7886 - val_loss: 0.5631 - val_accuracy: 0.7156 - lr: 0.0010
253/253 [==============================] - 0s 804us/step
Independent Testing Matthews Correlation:  0.4255315626613794
Confusion Matrix :
 [[2909 1138]
 [1187 2860]]
Accuracy on test set:    0.712750185322461
Sensitivity:    0.7066963182604399 	 Specificity:    0.7188040523844823
Precision  : 0.7153576788394197
Area Under Curve:    0.7127501853224611
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5865 - accuracy: 0.6844 - val_loss: 0.5569 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7228 - val_loss: 0.5466 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7345 - val_loss: 0.5433 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.7421 - val_loss: 0.5454 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5018 - accuracy: 0.7531 - val_loss: 0.5432 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4907 - accuracy: 0.7605 - val_loss: 0.5496 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4801 - accuracy: 0.7694 - val_loss: 0.5487 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4653 - accuracy: 0.7780 - val_loss: 0.5542 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4530 - accuracy: 0.7854 - val_loss: 0.5541 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4408 - accuracy: 0.7956 - val_loss: 0.5692 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4292 - accuracy: 0.8000 - val_loss: 0.5673 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 12/400
256/257 [============================>.] - ETA: 0s - loss: 0.4140 - accuracy: 0.8106
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4140 - accuracy: 0.8106 - val_loss: 0.5768 - val_accuracy: 0.7156 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42463969979110217
Confusion Matrix :
 [[2967 1080]
 [1250 2797]]
Accuracy on test set:    0.7121324437855201
Sensitivity:    0.6911292315295281 	 Specificity:    0.7331356560415122
Precision  : 0.7214340985297911
Area Under Curve:    0.7121324437855202
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5871 - accuracy: 0.6856 - val_loss: 0.5512 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7223 - val_loss: 0.5445 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7324 - val_loss: 0.5415 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7404 - val_loss: 0.5412 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.7480 - val_loss: 0.5427 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4995 - accuracy: 0.7543 - val_loss: 0.5405 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4890 - accuracy: 0.7622 - val_loss: 0.5417 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4785 - accuracy: 0.7690 - val_loss: 0.5439 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4668 - accuracy: 0.7757 - val_loss: 0.5499 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4557 - accuracy: 0.7838 - val_loss: 0.5519 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4424 - accuracy: 0.7933 - val_loss: 0.5585 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4331 - accuracy: 0.7989 - val_loss: 0.5655 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4190 - accuracy: 0.8077 - val_loss: 0.5707 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4053 - accuracy: 0.8158 - val_loss: 0.5727 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3937 - accuracy: 0.8198 - val_loss: 0.5828 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 16/400
254/257 [============================>.] - ETA: 0s - loss: 0.3817 - accuracy: 0.8280
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3819 - accuracy: 0.8279 - val_loss: 0.5874 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 787us/step
Independent Testing Matthews Correlation:  0.4314468246266481
Confusion Matrix :
 [[2879 1168]
 [1133 2914]]
Accuracy on test set:    0.7157153446997776
Sensitivity:    0.7200395354583642 	 Specificity:    0.711391153941191
Precision  : 0.7138657520823126
Area Under Curve:    0.7157153446997776
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5893 - accuracy: 0.6824 - val_loss: 0.5526 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7209 - val_loss: 0.5478 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5327 - accuracy: 0.7320 - val_loss: 0.5417 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5213 - accuracy: 0.7390 - val_loss: 0.5414 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7488 - val_loss: 0.5408 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7554 - val_loss: 0.5468 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7645 - val_loss: 0.5468 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4766 - accuracy: 0.7723 - val_loss: 0.5498 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4649 - accuracy: 0.7809 - val_loss: 0.5507 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4511 - accuracy: 0.7887 - val_loss: 0.5593 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4398 - accuracy: 0.7953 - val_loss: 0.5639 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4278 - accuracy: 0.8050 - val_loss: 0.5681 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 13/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4127 - accuracy: 0.8133
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4141 - accuracy: 0.8122 - val_loss: 0.5713 - val_accuracy: 0.7106 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.4550800178336144
Confusion Matrix :
 [[3147  900]
 [1315 2732]]
Accuracy on test set:    0.7263404991351619
Sensitivity:    0.6750679515690635 	 Specificity:    0.7776130467012602
Precision  : 0.7522026431718062
Area Under Curve:    0.7263404991351619
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5923 - accuracy: 0.6806 - val_loss: 0.5545 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7223 - val_loss: 0.5470 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5343 - accuracy: 0.7294 - val_loss: 0.5502 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5228 - accuracy: 0.7388 - val_loss: 0.5440 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5121 - accuracy: 0.7458 - val_loss: 0.5428 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7530 - val_loss: 0.5445 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7629 - val_loss: 0.5536 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7698 - val_loss: 0.5508 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4672 - accuracy: 0.7769 - val_loss: 0.5613 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4534 - accuracy: 0.7868
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4539 - accuracy: 0.7862 - val_loss: 0.5627 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 772us/step
Independent Testing Matthews Correlation:  0.47393896108344014
Confusion Matrix :
 [[2994 1053]
 [1076 2971]]
Accuracy on test set:    0.7369656535705461
Sensitivity:    0.7341240425006177 	 Specificity:    0.7398072646404744
Precision  : 0.7383200795228628
Area Under Curve:    0.736965653570546
(8094, 2560) (8094,)
Mean MCC = 0.4284 + 0.0208 and Mean AUC = 0.7136 + 0.0107
Mean Sensitivity = 0.7220 + 0.0343 and Mean Specificity = 0.7051 + 0.0441 and Mean Accuracy = 0.7136 + 0.0107
Mean Precision = 0.7116 + 0.0226





Seed   : 970938
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5941 - accuracy: 0.6777 - val_loss: 0.5637 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7230 - val_loss: 0.5501 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7341 - val_loss: 0.5477 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7436 - val_loss: 0.5482 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7511 - val_loss: 0.5575 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7594 - val_loss: 0.5497 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7671 - val_loss: 0.5522 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4686 - accuracy: 0.7760 - val_loss: 0.5592 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4565 - accuracy: 0.7821 - val_loss: 0.5614 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4451 - accuracy: 0.7906 - val_loss: 0.5712 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4347 - accuracy: 0.7983 - val_loss: 0.5833 - val_accuracy: 0.7032 - lr: 0.0010
Epoch 12/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4216 - accuracy: 0.8053
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4221 - accuracy: 0.8054 - val_loss: 0.5850 - val_accuracy: 0.7057 - lr: 0.0010
253/253 [==============================] - 0s 871us/step
Independent Testing Matthews Correlation:  0.3929915728362726
Confusion Matrix :
 [[2743 1305]
 [1153 2894]]
Accuracy on test set:    0.6963557751698579
Sensitivity:    0.7150976031628367 	 Specificity:    0.6776185770750988
Precision  : 0.6892117170754941
Area Under Curve:    0.6963580901189678
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5846 - accuracy: 0.6885 - val_loss: 0.5544 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5413 - accuracy: 0.7255 - val_loss: 0.5464 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5263 - accuracy: 0.7349 - val_loss: 0.5464 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5143 - accuracy: 0.7436 - val_loss: 0.5479 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7508 - val_loss: 0.5495 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4924 - accuracy: 0.7587 - val_loss: 0.5568 - val_accuracy: 0.7150 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4793 - accuracy: 0.7684 - val_loss: 0.5571 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4682 - accuracy: 0.7758
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4684 - accuracy: 0.7756 - val_loss: 0.5564 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4254173639301845
Confusion Matrix :
 [[2843 1205]
 [1121 2926]]
Accuracy on test set:    0.71266213712168
Sensitivity:    0.7230046948356808 	 Specificity:    0.7023221343873518
Precision  : 0.7083030743161463
Area Under Curve:    0.7126634146115163
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5895 - accuracy: 0.6847 - val_loss: 0.5462 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7230 - val_loss: 0.5420 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7308 - val_loss: 0.5412 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5213 - accuracy: 0.7400 - val_loss: 0.5374 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5112 - accuracy: 0.7462 - val_loss: 0.5363 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5027 - accuracy: 0.7535 - val_loss: 0.5388 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4918 - accuracy: 0.7597 - val_loss: 0.5439 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7668 - val_loss: 0.5439 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4690 - accuracy: 0.7768 - val_loss: 0.5450 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4576 - accuracy: 0.7833 - val_loss: 0.5517 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4466 - accuracy: 0.7918 - val_loss: 0.5595 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4345 - accuracy: 0.7990 - val_loss: 0.5666 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 13/400
251/257 [============================>.] - ETA: 0s - loss: 0.4230 - accuracy: 0.8059
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4232 - accuracy: 0.8058 - val_loss: 0.5670 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 788us/step
Independent Testing Matthews Correlation:  0.42151617539258973
Confusion Matrix :
 [[2743 1304]
 [1041 3007]]
Accuracy on test set:    0.7103150092649784
Sensitivity:    0.7428359683794467 	 Specificity:    0.6777860143316037
Precision  : 0.6975179772674553
Area Under Curve:    0.7103109913555252
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5863 - accuracy: 0.6832 - val_loss: 0.5447 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7242 - val_loss: 0.5345 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5269 - accuracy: 0.7353 - val_loss: 0.5323 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5139 - accuracy: 0.7423 - val_loss: 0.5359 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5027 - accuracy: 0.7512 - val_loss: 0.5375 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7618 - val_loss: 0.5361 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7690 - val_loss: 0.5393 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4654 - accuracy: 0.7760 - val_loss: 0.5403 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4510 - accuracy: 0.7859 - val_loss: 0.5475 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4378 - accuracy: 0.7954 - val_loss: 0.5576 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4250 - accuracy: 0.8021 - val_loss: 0.5530 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4147 - accuracy: 0.8101
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4147 - accuracy: 0.8097 - val_loss: 0.5673 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39948553701722533
Confusion Matrix :
 [[2634 1413]
 [1025 3023]]
Accuracy on test set:    0.6988264360716492
Sensitivity:    0.7467885375494071 	 Specificity:    0.6508524833209784
Precision  : 0.6814697926059513
Area Under Curve:    0.6988205104351929
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5855 - accuracy: 0.6846 - val_loss: 0.5483 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7226 - val_loss: 0.5410 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7328 - val_loss: 0.5394 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7407 - val_loss: 0.5451 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7495 - val_loss: 0.5407 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7572 - val_loss: 0.5441 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7655 - val_loss: 0.5482 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7750 - val_loss: 0.5476 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4580 - accuracy: 0.7840 - val_loss: 0.5516 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4457 - accuracy: 0.7927 - val_loss: 0.5791 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - ETA: 0s - loss: 0.4330 - accuracy: 0.7984
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4330 - accuracy: 0.7984 - val_loss: 0.5556 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 742us/step
Independent Testing Matthews Correlation:  0.4272333859023956
Confusion Matrix :
 [[2880 1167]
 [1151 2896]]
Accuracy on test set:    0.7136150234741784
Sensitivity:    0.7155917963923895 	 Specificity:    0.7116382505559674
Precision  : 0.7127738124538519
Area Under Curve:    0.7136150234741785
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5890 - accuracy: 0.6823 - val_loss: 0.5536 - val_accuracy: 0.7157 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7190 - val_loss: 0.5397 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7322 - val_loss: 0.5421 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7399 - val_loss: 0.5387 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7476 - val_loss: 0.5426 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7575 - val_loss: 0.5381 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7642 - val_loss: 0.5402 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4711 - accuracy: 0.7735 - val_loss: 0.5413 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4623 - accuracy: 0.7814 - val_loss: 0.5416 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4490 - accuracy: 0.7878 - val_loss: 0.5531 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4379 - accuracy: 0.7957 - val_loss: 0.5647 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4257 - accuracy: 0.8055 - val_loss: 0.5679 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4137 - accuracy: 0.8101 - val_loss: 0.5676 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 14/400
251/257 [============================>.] - ETA: 0s - loss: 0.4013 - accuracy: 0.8165
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4019 - accuracy: 0.8162 - val_loss: 0.5710 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 754us/step
Independent Testing Matthews Correlation:  0.39890423527752655
Confusion Matrix :
 [[2939 1108]
 [1327 2720]]
Accuracy on test set:    0.6991598715097603
Sensitivity:    0.672102792191747 	 Specificity:    0.7262169508277737
Precision  : 0.7105538140020898
Area Under Curve:    0.6991598715097603
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5881 - accuracy: 0.6841 - val_loss: 0.5462 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7227 - val_loss: 0.5433 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7341 - val_loss: 0.5436 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7393 - val_loss: 0.5403 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7495 - val_loss: 0.5374 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7552 - val_loss: 0.5448 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7623 - val_loss: 0.5409 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4764 - accuracy: 0.7715 - val_loss: 0.5456 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.7782 - val_loss: 0.5513 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4529 - accuracy: 0.7868 - val_loss: 0.5631 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4419 - accuracy: 0.7936 - val_loss: 0.5582 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4253 - accuracy: 0.8017
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4256 - accuracy: 0.8017 - val_loss: 0.5676 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 989us/step
Independent Testing Matthews Correlation:  0.4336681160648338
Confusion Matrix :
 [[2885 1162]
 [1130 2917]]
Accuracy on test set:    0.7168272794662713
Sensitivity:    0.7207808253026934 	 Specificity:    0.7128737336298493
Precision  : 0.7151262564354008
Area Under Curve:    0.7168272794662712
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5885 - accuracy: 0.6841 - val_loss: 0.5496 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7230 - val_loss: 0.5408 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7323 - val_loss: 0.5387 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7406 - val_loss: 0.5399 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7510 - val_loss: 0.5395 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7602 - val_loss: 0.5557 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.7680 - val_loss: 0.5411 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7775 - val_loss: 0.5443 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4560 - accuracy: 0.7854 - val_loss: 0.5575 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4397 - accuracy: 0.7944
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4397 - accuracy: 0.7945 - val_loss: 0.5645 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 891us/step
Independent Testing Matthews Correlation:  0.4416102689352417
Confusion Matrix :
 [[2675 1372]
 [ 900 3147]]
Accuracy on test set:    0.7192982456140351
Sensitivity:    0.7776130467012602 	 Specificity:    0.66098344452681
Precision  : 0.6963930073025005
Area Under Curve:    0.719298245614035
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5924 - accuracy: 0.6808 - val_loss: 0.5500 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5481 - accuracy: 0.7204 - val_loss: 0.5419 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7289 - val_loss: 0.5451 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5234 - accuracy: 0.7382 - val_loss: 0.5462 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5120 - accuracy: 0.7456 - val_loss: 0.5431 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7535 - val_loss: 0.5446 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 7/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4905 - accuracy: 0.7619
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7619 - val_loss: 0.5455 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 777us/step
Independent Testing Matthews Correlation:  0.46285316483349126
Confusion Matrix :
 [[2933 1114]
 [1060 2987]]
Accuracy on test set:    0.7314059797380776
Sensitivity:    0.7380775883370397 	 Specificity:    0.7247343711391154
Precision  : 0.728358936844672
Area Under Curve:    0.7314059797380776
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5929 - accuracy: 0.6828 - val_loss: 0.5515 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5527 - accuracy: 0.7169 - val_loss: 0.5416 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5356 - accuracy: 0.7303 - val_loss: 0.5468 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5253 - accuracy: 0.7384 - val_loss: 0.5430 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.7456 - val_loss: 0.5418 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5023 - accuracy: 0.7544 - val_loss: 0.5444 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4896 - accuracy: 0.7624 - val_loss: 0.5413 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.7704 - val_loss: 0.5474 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7782 - val_loss: 0.5510 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4545 - accuracy: 0.7858 - val_loss: 0.5547 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4389 - accuracy: 0.7973
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4394 - accuracy: 0.7968 - val_loss: 0.5538 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 734us/step
Independent Testing Matthews Correlation:  0.47637540542136403
Confusion Matrix :
 [[3114  933]
 [1190 2857]]
Accuracy on test set:    0.7377069434148752
Sensitivity:    0.7059550284161107 	 Specificity:    0.7694588584136397
Precision  : 0.7538258575197889
Area Under Curve:    0.7377069434148752
(8094, 2560) (8094,)
Mean MCC = 0.4280 + 0.0259 and Mean AUC = 0.7136 + 0.0129
Mean Sensitivity = 0.7258 + 0.0266 and Mean Specificity = 0.7014 + 0.0337 and Mean Accuracy = 0.7136 + 0.0129
Mean Precision = 0.7094 + 0.0197





Seed   : 796562
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5846 - accuracy: 0.6869 - val_loss: 0.5594 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5418 - accuracy: 0.7255 - val_loss: 0.5526 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7360 - val_loss: 0.5515 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5142 - accuracy: 0.7437 - val_loss: 0.5529 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7515 - val_loss: 0.5479 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4918 - accuracy: 0.7593 - val_loss: 0.5582 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.7701 - val_loss: 0.5525 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4702 - accuracy: 0.7738 - val_loss: 0.5572 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4574 - accuracy: 0.7841 - val_loss: 0.5570 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4450 - accuracy: 0.7934
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4453 - accuracy: 0.7930 - val_loss: 0.5620 - val_accuracy: 0.7111 - lr: 0.0010
253/253 [==============================] - 0s 890us/step
Independent Testing Matthews Correlation:  0.4136552302301485
Confusion Matrix :
 [[2800 1248]
 [1126 2921]]
Accuracy on test set:    0.7067325509573811
Sensitivity:    0.7217692117617989 	 Specificity:    0.691699604743083
Precision  : 0.7006476373230991
Area Under Curve:    0.7067344082524409
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5855 - accuracy: 0.6872 - val_loss: 0.5561 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7235 - val_loss: 0.5492 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7336 - val_loss: 0.5474 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5154 - accuracy: 0.7441 - val_loss: 0.5468 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7509 - val_loss: 0.5452 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7613 - val_loss: 0.5466 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.7694 - val_loss: 0.5546 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4664 - accuracy: 0.7785 - val_loss: 0.5564 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4543 - accuracy: 0.7869 - val_loss: 0.5541 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4397 - accuracy: 0.7939
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4402 - accuracy: 0.7936 - val_loss: 0.5594 - val_accuracy: 0.7148 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4126771286643132
Confusion Matrix :
 [[2741 1307]
 [1073 2974]]
Accuracy on test set:    0.7059913526868438
Sensitivity:    0.7348653323449469 	 Specificity:    0.6771245059288538
Precision  : 0.6946975005839757
Area Under Curve:    0.7059949191369003
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5887 - accuracy: 0.6829 - val_loss: 0.5481 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7216 - val_loss: 0.5456 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5326 - accuracy: 0.7315 - val_loss: 0.5373 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7412 - val_loss: 0.5371 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7482 - val_loss: 0.5426 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7563 - val_loss: 0.5380 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7671 - val_loss: 0.5419 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4688 - accuracy: 0.7775 - val_loss: 0.5470 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4556 - accuracy: 0.7850 - val_loss: 0.5527 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4404 - accuracy: 0.7947 - val_loss: 0.5644 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 11/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4293 - accuracy: 0.8015
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4293 - accuracy: 0.8015 - val_loss: 0.5650 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 0s 802us/step
Independent Testing Matthews Correlation:  0.41826812460617413
Confusion Matrix :
 [[2823 1224]
 [1131 2917]]
Accuracy on test set:    0.7090796788140827
Sensitivity:    0.720602766798419 	 Specificity:    0.6975537435137139
Precision  : 0.7044192224100458
Area Under Curve:    0.7090782551560664
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5852 - accuracy: 0.6844 - val_loss: 0.5479 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7228 - val_loss: 0.5422 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7327 - val_loss: 0.5446 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7404 - val_loss: 0.5392 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7477 - val_loss: 0.5395 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7566 - val_loss: 0.5406 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4817 - accuracy: 0.7671 - val_loss: 0.5440 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4690 - accuracy: 0.7746 - val_loss: 0.5441 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4572 - accuracy: 0.7827 - val_loss: 0.5529 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 10/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4429 - accuracy: 0.7916
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4434 - accuracy: 0.7906 - val_loss: 0.5535 - val_accuracy: 0.7172 - lr: 0.0010
253/253 [==============================] - 0s 724us/step
Independent Testing Matthews Correlation:  0.41703012624644514
Confusion Matrix :
 [[2821 1226]
 [1134 2914]]
Accuracy on test set:    0.7084620135886349
Sensitivity:    0.7198616600790514 	 Specificity:    0.6970595502841611
Precision  : 0.7038647342995169
Area Under Curve:    0.7084606051816063
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5871 - accuracy: 0.6830 - val_loss: 0.5534 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7234 - val_loss: 0.5479 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7306 - val_loss: 0.5453 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7407 - val_loss: 0.5450 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7474 - val_loss: 0.5452 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7566 - val_loss: 0.5439 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7651 - val_loss: 0.5503 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.7734 - val_loss: 0.5471 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4627 - accuracy: 0.7803
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4625 - accuracy: 0.7804 - val_loss: 0.5551 - val_accuracy: 0.7237 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43166385789796274
Confusion Matrix :
 [[2830 1217]
 [1084 2963]]
Accuracy on test set:    0.7157153446997776
Sensitivity:    0.7321472695824067 	 Specificity:    0.6992834198171485
Precision  : 0.7088516746411483
Area Under Curve:    0.7157153446997776
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6851 - val_loss: 0.5572 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7219 - val_loss: 0.5578 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7317 - val_loss: 0.5477 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.7396 - val_loss: 0.5496 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.7481 - val_loss: 0.5515 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7556 - val_loss: 0.5524 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4903 - accuracy: 0.7626 - val_loss: 0.5534 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4784 - accuracy: 0.7714
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4784 - accuracy: 0.7714 - val_loss: 0.5599 - val_accuracy: 0.7193 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4302835408786187
Confusion Matrix :
 [[2853 1194]
 [1112 2935]]
Accuracy on test set:    0.7150976031628367
Sensitivity:    0.7252285643686681 	 Specificity:    0.7049666419570052
Precision  : 0.7108258658270767
Area Under Curve:    0.7150976031628367
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5876 - accuracy: 0.6845 - val_loss: 0.5550 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7223 - val_loss: 0.5522 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7328 - val_loss: 0.5508 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7398 - val_loss: 0.5499 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5109 - accuracy: 0.7470 - val_loss: 0.5464 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
252/257 [============================>.] - ETA: 0s - loss: 0.4994 - accuracy: 0.7543
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7541 - val_loss: 0.5497 - val_accuracy: 0.7176 - lr: 0.0010

253/253 [==============================] - 0s 851us/step
Independent Testing Matthews Correlation:  0.41697436181963005
Confusion Matrix :
 [[2976 1071]
 [1291 2756]]
Accuracy on test set:    0.708178897949098
Sensitivity:    0.6809982703236965 	 Specificity:    0.7353595255744997
Precision  : 0.7201463287170107
Area Under Curve:    0.7081788979490979
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5889 - accuracy: 0.6818 - val_loss: 0.5584 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7195 - val_loss: 0.5496 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7325 - val_loss: 0.5520 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7417 - val_loss: 0.5495 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7505 - val_loss: 0.5499 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
256/257 [============================>.] - ETA: 0s - loss: 0.4947 - accuracy: 0.7590
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7591 - val_loss: 0.5535 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.435980773802658
Confusion Matrix :
 [[2986 1061]
 [1223 2824]]
Accuracy on test set:    0.7178156659253768
Sensitivity:    0.6978008401284902 	 Specificity:    0.7378304917222634
Precision  : 0.7268983268983269
Area Under Curve:    0.7178156659253768
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5890 - accuracy: 0.6834 - val_loss: 0.5566 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7222 - val_loss: 0.5493 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7320 - val_loss: 0.5484 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.7394 - val_loss: 0.5475 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7487 - val_loss: 0.5503 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7541 - val_loss: 0.5513 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4867 - accuracy: 0.7641 - val_loss: 0.5536 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4776 - accuracy: 0.7710 - val_loss: 0.5578 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4639 - accuracy: 0.7809 - val_loss: 0.5616 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4513 - accuracy: 0.7885 - val_loss: 0.5722 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4383 - accuracy: 0.7953 - val_loss: 0.5779 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 12/400
256/257 [============================>.] - ETA: 0s - loss: 0.4255 - accuracy: 0.8027
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4256 - accuracy: 0.8027 - val_loss: 0.5791 - val_accuracy: 0.7127 - lr: 0.0010
253/253 [==============================] - 0s 800us/step
Independent Testing Matthews Correlation:  0.45294715605290625
Confusion Matrix :
 [[3088  959]
 [1260 2787]]
Accuracy on test set:    0.7258463059056091
Sensitivity:    0.6886582653817642 	 Specificity:    0.7630343464294539
Precision  : 0.7439935931660437
Area Under Curve:    0.7258463059056091
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5902 - accuracy: 0.6827 - val_loss: 0.5617 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5484 - accuracy: 0.7197 - val_loss: 0.5536 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7304 - val_loss: 0.5576 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5227 - accuracy: 0.7400 - val_loss: 0.5497 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5105 - accuracy: 0.7481 - val_loss: 0.5506 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5006 - accuracy: 0.7550 - val_loss: 0.5527 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7629 - val_loss: 0.5522 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7699 - val_loss: 0.5576 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4668 - accuracy: 0.7788
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4669 - accuracy: 0.7784 - val_loss: 0.5594 - val_accuracy: 0.7172 - lr: 0.0010
253/253 [==============================] - 0s 783us/step
Independent Testing Matthews Correlation:  0.48264566562982664
Confusion Matrix :
 [[3146  901]
 [1198 2849]]
Accuracy on test set:    0.7406721027921918
Sensitivity:    0.7039782554978997 	 Specificity:    0.7773659500864838
Precision  : 0.7597333333333334
Area Under Curve:    0.7406721027921918
(8094, 2560) (8094,)
Mean MCC = 0.4312 + 0.0209 and Mean AUC = 0.7154 + 0.0103
Mean Sensitivity = 0.7126 + 0.0176 and Mean Specificity = 0.7181 + 0.0316 and Mean Accuracy = 0.7154 + 0.0103
Mean Precision = 0.7174 + 0.0196





Seed   : 341385
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5917 - accuracy: 0.6794 - val_loss: 0.5614 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7239 - val_loss: 0.5523 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7342 - val_loss: 0.5527 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7415 - val_loss: 0.5573 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5093 - accuracy: 0.7498 - val_loss: 0.5553 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4994 - accuracy: 0.7552 - val_loss: 0.5565 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7613 - val_loss: 0.5593 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.7680 - val_loss: 0.5645 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4711 - accuracy: 0.7761 - val_loss: 0.5645 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4595 - accuracy: 0.7831
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4599 - accuracy: 0.7831 - val_loss: 0.5737 - val_accuracy: 0.7109 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40452735070045875
Confusion Matrix :
 [[2617 1431]
 [ 989 3058]]
Accuracy on test set:    0.7010500308832612
Sensitivity:    0.7556214479861626 	 Specificity:    0.64649209486166
Precision  : 0.6812207618623302
Area Under Curve:    0.7010567714239113
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5898 - accuracy: 0.6842 - val_loss: 0.5583 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7214 - val_loss: 0.5533 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7347 - val_loss: 0.5479 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7437 - val_loss: 0.5621 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7501 - val_loss: 0.5510 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7583 - val_loss: 0.5507 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.7649 - val_loss: 0.5498 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.7721 - val_loss: 0.5573 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4614 - accuracy: 0.7802 - val_loss: 0.5578 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4504 - accuracy: 0.7869 - val_loss: 0.5773 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4399 - accuracy: 0.7941
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4400 - accuracy: 0.7941 - val_loss: 0.5797 - val_accuracy: 0.7117 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4108692526593527
Confusion Matrix :
 [[2689 1359]
 [1031 3016]]
Accuracy on test set:    0.7047560222359481
Sensitivity:    0.7452433901655547 	 Specificity:    0.6642786561264822
Precision  : 0.6893714285714285
Area Under Curve:    0.7047610231460185
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5938 - accuracy: 0.6806 - val_loss: 0.5519 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5480 - accuracy: 0.7217 - val_loss: 0.5436 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5326 - accuracy: 0.7320 - val_loss: 0.5406 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7420 - val_loss: 0.5460 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7490 - val_loss: 0.5418 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7590 - val_loss: 0.5411 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4817 - accuracy: 0.7688 - val_loss: 0.5492 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4676 - accuracy: 0.7777
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4677 - accuracy: 0.7776 - val_loss: 0.5485 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 871us/step
Independent Testing Matthews Correlation:  0.39797160868149556
Confusion Matrix :
 [[2935 1112]
 [1327 2721]]
Accuracy on test set:    0.6987029030265596
Sensitivity:    0.6721837944664032 	 Specificity:    0.7252285643686681
Precision  : 0.7098878163318549
Area Under Curve:    0.6987061794175358
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.6807 - val_loss: 0.5503 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7230 - val_loss: 0.5392 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7329 - val_loss: 0.5388 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7425 - val_loss: 0.5370 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7521 - val_loss: 0.5367 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4927 - accuracy: 0.7602 - val_loss: 0.5379 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4825 - accuracy: 0.7685 - val_loss: 0.5414 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4708 - accuracy: 0.7750 - val_loss: 0.5441 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4591 - accuracy: 0.7837 - val_loss: 0.5498 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4472 - accuracy: 0.7913
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4473 - accuracy: 0.7912 - val_loss: 0.5517 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4264840686741523
Confusion Matrix :
 [[2645 1402]
 [ 931 3117]]
Accuracy on test set:    0.7117974058060531
Sensitivity:    0.7700098814229249 	 Specificity:    0.6535705460835186
Precision  : 0.6897543704359371
Area Under Curve:    0.7117902137532217
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5864 - accuracy: 0.6847 - val_loss: 0.5539 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7215 - val_loss: 0.5471 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7339 - val_loss: 0.5438 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5168 - accuracy: 0.7433 - val_loss: 0.5434 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7493 - val_loss: 0.5426 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7578 - val_loss: 0.5431 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7663 - val_loss: 0.5447 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7755 - val_loss: 0.5457 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.7822 - val_loss: 0.5567 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 10/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4456 - accuracy: 0.7909
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4468 - accuracy: 0.7899 - val_loss: 0.5509 - val_accuracy: 0.7215 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4088405892091857
Confusion Matrix :
 [[2716 1331]
 [1065 2982]]
Accuracy on test set:    0.7039782554978997
Sensitivity:    0.7368421052631579 	 Specificity:    0.6711144057326415
Precision  : 0.691398098771157
Area Under Curve:    0.7039782554978997
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5923 - accuracy: 0.6784 - val_loss: 0.5537 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5481 - accuracy: 0.7206 - val_loss: 0.5449 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7320 - val_loss: 0.5421 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.7390 - val_loss: 0.5419 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5113 - accuracy: 0.7464 - val_loss: 0.5428 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7526 - val_loss: 0.5415 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4911 - accuracy: 0.7612
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7613 - val_loss: 0.5497 - val_accuracy: 0.7202 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4222210966431664
Confusion Matrix :
 [[2968 1079]
 [1261 2786]]
Accuracy on test set:    0.7108969607116382
Sensitivity:    0.6884111687669879 	 Specificity:    0.7333827526562886
Precision  : 0.7208279430789133
Area Under Curve:    0.7108969607116382
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5925 - accuracy: 0.6797 - val_loss: 0.5552 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7218 - val_loss: 0.5430 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7335 - val_loss: 0.5402 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7424 - val_loss: 0.5378 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7510 - val_loss: 0.5393 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7604 - val_loss: 0.5390 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.7677 - val_loss: 0.5422 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.7749 - val_loss: 0.5466 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4582 - accuracy: 0.7823 - val_loss: 0.5488 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4480 - accuracy: 0.7891 - val_loss: 0.5559 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4364 - accuracy: 0.7946 - val_loss: 0.5597 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4252 - accuracy: 0.8024
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4257 - accuracy: 0.8024 - val_loss: 0.5627 - val_accuracy: 0.7170 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4119682156792005
Confusion Matrix :
 [[2891 1156]
 [1224 2823]]
Accuracy on test set:    0.7059550284161107
Sensitivity:    0.6975537435137139 	 Specificity:    0.7143563133185076
Precision  : 0.7094747423975873
Area Under Curve:    0.7059550284161107
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5883 - accuracy: 0.6839 - val_loss: 0.5537 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7213 - val_loss: 0.5458 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5338 - accuracy: 0.7304 - val_loss: 0.5382 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5231 - accuracy: 0.7380 - val_loss: 0.5393 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5131 - accuracy: 0.7458 - val_loss: 0.5406 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7503 - val_loss: 0.5382 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7594 - val_loss: 0.5417 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4827 - accuracy: 0.7651 - val_loss: 0.5481 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4708 - accuracy: 0.7757 - val_loss: 0.5458 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4598 - accuracy: 0.7830
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4602 - accuracy: 0.7825 - val_loss: 0.5488 - val_accuracy: 0.7226 - lr: 0.0010
253/253 [==============================] - 0s 834us/step
Independent Testing Matthews Correlation:  0.4401027719879107
Confusion Matrix :
 [[2935 1112]
 [1154 2893]]
Accuracy on test set:    0.7200395354583642
Sensitivity:    0.7148505065480603 	 Specificity:    0.7252285643686681
Precision  : 0.7223470661672909
Area Under Curve:    0.7200395354583642
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5936 - accuracy: 0.6799 - val_loss: 0.5564 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5504 - accuracy: 0.7194 - val_loss: 0.5504 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5350 - accuracy: 0.7303 - val_loss: 0.5467 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5246 - accuracy: 0.7364 - val_loss: 0.5457 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7430 - val_loss: 0.5487 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7516 - val_loss: 0.5463 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7592 - val_loss: 0.5513 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.7665 - val_loss: 0.5602 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7743 - val_loss: 0.5553 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4589 - accuracy: 0.7816 - val_loss: 0.5582 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4478 - accuracy: 0.7894 - val_loss: 0.5648 - val_accuracy: 0.7152 - lr: 0.0010

Epoch 12/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4362 - accuracy: 0.7945
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4365 - accuracy: 0.7946 - val_loss: 0.5731 - val_accuracy: 0.7100 - lr: 0.0010
253/253 [==============================] - 0s 999us/step
Independent Testing Matthews Correlation:  0.451966421751358
Confusion Matrix :
 [[2960 1087]
 [1131 2916]]
Accuracy on test set:    0.7259698542129973
Sensitivity:    0.720533728687917 	 Specificity:    0.7314059797380776
Precision  : 0.7284536597551836
Area Under Curve:    0.7259698542129973
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5917 - accuracy: 0.6838 - val_loss: 0.5566 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5499 - accuracy: 0.7196 - val_loss: 0.5503 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5370 - accuracy: 0.7296 - val_loss: 0.5479 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5258 - accuracy: 0.7354 - val_loss: 0.5455 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5168 - accuracy: 0.7440 - val_loss: 0.5488 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7498 - val_loss: 0.5478 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7585 - val_loss: 0.5528 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.7657 - val_loss: 0.5498 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4726 - accuracy: 0.7750 - val_loss: 0.5525 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4590 - accuracy: 0.7841
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.7839 - val_loss: 0.5583 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4711349350479461
Confusion Matrix :
 [[3228  819]
 [1337 2710]]
Accuracy on test set:    0.733629849271065
Sensitivity:    0.6696318260439832 	 Specificity:    0.7976278724981468
Precision  : 0.7679229243411732
Area Under Curve:    0.733629849271065
(8094, 2560) (8094,)
Mean MCC = 0.4246 + 0.0221 and Mean AUC = 0.7117 + 0.0109
Mean Sensitivity = 0.7171 + 0.0331 and Mean Specificity = 0.7063 + 0.0446 and Mean Accuracy = 0.7117 + 0.0109
Mean Precision = 0.7111 + 0.0244





Seed   : 560368
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6840 - val_loss: 0.5624 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7251 - val_loss: 0.5509 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.7359 - val_loss: 0.5495 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7430 - val_loss: 0.5427 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7515 - val_loss: 0.5455 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7591 - val_loss: 0.5477 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7664 - val_loss: 0.5505 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.7749 - val_loss: 0.5555 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4604 - accuracy: 0.7819 - val_loss: 0.5544 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4468 - accuracy: 0.7915 - val_loss: 0.5660 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4366 - accuracy: 0.7989 - val_loss: 0.5717 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4231 - accuracy: 0.8061
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4232 - accuracy: 0.8062 - val_loss: 0.5842 - val_accuracy: 0.7089 - lr: 0.0010
253/253 [==============================] - 0s 909us/step
Independent Testing Matthews Correlation:  0.3811985477913132
Confusion Matrix :
 [[2581 1467]
 [1046 3001]]
Accuracy on test set:    0.689561457689932
Sensitivity:    0.7415369409439091 	 Specificity:    0.637598814229249
Precision  : 0.6716651745747538
Area Under Curve:    0.689567877586579
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5858 - accuracy: 0.6864 - val_loss: 0.5511 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7241 - val_loss: 0.5476 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5267 - accuracy: 0.7339 - val_loss: 0.5466 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.7435 - val_loss: 0.5552 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5038 - accuracy: 0.7517 - val_loss: 0.5489 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4911 - accuracy: 0.7589 - val_loss: 0.5511 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7682 - val_loss: 0.5542 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4664 - accuracy: 0.7775 - val_loss: 0.5692 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4535 - accuracy: 0.7866 - val_loss: 0.5625 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4423 - accuracy: 0.7916 - val_loss: 0.5747 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 11/400
256/257 [============================>.] - ETA: 0s - loss: 0.4283 - accuracy: 0.8010
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4283 - accuracy: 0.8010 - val_loss: 0.5786 - val_accuracy: 0.7076 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41967952013700743
Confusion Matrix :
 [[2901 1147]
 [1202 2845]]
Accuracy on test set:    0.7098208770846202
Sensitivity:    0.7029898690387941 	 Specificity:    0.7166501976284585
Precision  : 0.7126753507014028
Area Under Curve:    0.7098200333336263
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6863 - val_loss: 0.5492 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7228 - val_loss: 0.5348 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7336 - val_loss: 0.5320 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7426 - val_loss: 0.5322 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7515 - val_loss: 0.5351 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4928 - accuracy: 0.7596 - val_loss: 0.5360 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7673 - val_loss: 0.5384 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4684 - accuracy: 0.7752
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4682 - accuracy: 0.7752 - val_loss: 0.5429 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 759us/step
Independent Testing Matthews Correlation:  0.4216185075047361
Confusion Matrix :
 [[2874 1173]
 [1168 2880]]
Accuracy on test set:    0.7108091414453366
Sensitivity:    0.7114624505928854 	 Specificity:    0.7101556708673091
Precision  : 0.7105847520355293
Area Under Curve:    0.7108090607300972
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5919 - accuracy: 0.6815 - val_loss: 0.5430 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.7198 - val_loss: 0.5377 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7328 - val_loss: 0.5318 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5213 - accuracy: 0.7398 - val_loss: 0.5341 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7469 - val_loss: 0.5310 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7544 - val_loss: 0.5310 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4886 - accuracy: 0.7614 - val_loss: 0.5320 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4784 - accuracy: 0.7703 - val_loss: 0.5345 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4646 - accuracy: 0.7782 - val_loss: 0.5434 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4521 - accuracy: 0.7879 - val_loss: 0.5490 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4404 - accuracy: 0.7940 - val_loss: 0.5480 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4250 - accuracy: 0.8036 - val_loss: 0.5527 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 13/400
256/257 [============================>.] - ETA: 0s - loss: 0.4122 - accuracy: 0.8120
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4122 - accuracy: 0.8120 - val_loss: 0.5697 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41337672040414913
Confusion Matrix :
 [[2769 1278]
 [1098 2950]]
Accuracy on test set:    0.706485484867202
Sensitivity:    0.7287549407114624 	 Specificity:    0.6842105263157895
Precision  : 0.6977294228949859
Area Under Curve:    0.7064827335136259
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5873 - accuracy: 0.6858 - val_loss: 0.5516 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7239 - val_loss: 0.5418 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7323 - val_loss: 0.5475 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7396 - val_loss: 0.5445 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7475 - val_loss: 0.5421 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7553 - val_loss: 0.5471 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4877 - accuracy: 0.7620
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7620 - val_loss: 0.5464 - val_accuracy: 0.7209 - lr: 0.0010
253/253 [==============================] - 0s 903us/step
Independent Testing Matthews Correlation:  0.4166764512015356
Confusion Matrix :
 [[2829 1218]
 [1143 2904]]
Accuracy on test set:    0.7083024462564863
Sensitivity:    0.7175685693106004 	 Specificity:    0.6990363232023721
Precision  : 0.7045123726346434
Area Under Curve:    0.7083024462564863
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5849 - accuracy: 0.6856 - val_loss: 0.5536 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7229 - val_loss: 0.5454 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7334 - val_loss: 0.5446 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7415 - val_loss: 0.5445 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7496 - val_loss: 0.5522 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4954 - accuracy: 0.7579 - val_loss: 0.5549 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4841 - accuracy: 0.7661 - val_loss: 0.5504 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4697 - accuracy: 0.7764 - val_loss: 0.5586 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4579 - accuracy: 0.7832
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4579 - accuracy: 0.7831 - val_loss: 0.5586 - val_accuracy: 0.7197 - lr: 0.0010
253/253 [==============================] - 0s 805us/step
Independent Testing Matthews Correlation:  0.4449557343362383
Confusion Matrix :
 [[2811 1236]
 [1013 3034]]
Accuracy on test set:    0.7221398566839634
Sensitivity:    0.7496911292315295 	 Specificity:    0.6945885841363973
Precision  : 0.7105386416861826
Area Under Curve:    0.7221398566839634
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5847 - accuracy: 0.6862 - val_loss: 0.5575 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7230 - val_loss: 0.5462 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7337 - val_loss: 0.5428 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7409 - val_loss: 0.5415 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7481 - val_loss: 0.5445 - val_accuracy: 0.7202 - lr: 0.0010

Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7592 - val_loss: 0.5458 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7681 - val_loss: 0.5483 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4690 - accuracy: 0.7760 - val_loss: 0.5498 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4553 - accuracy: 0.7831 - val_loss: 0.5539 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4445 - accuracy: 0.7905 - val_loss: 0.5685 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4313 - accuracy: 0.7990 - val_loss: 0.5651 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 12/400
249/257 [============================>.] - ETA: 0s - loss: 0.4191 - accuracy: 0.8068
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4198 - accuracy: 0.8061 - val_loss: 0.5645 - val_accuracy: 0.7149 - lr: 0.0010
253/253 [==============================] - 0s 752us/step
Independent Testing Matthews Correlation:  0.41389537147066097
Confusion Matrix :
 [[2848 1199]
 [1173 2874]]
Accuracy on test set:    0.7069434148752162
Sensitivity:    0.7101556708673091 	 Specificity:    0.7037311588831233
Precision  : 0.7056223913577215
Area Under Curve:    0.7069434148752163
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5909 - accuracy: 0.6806 - val_loss: 0.5584 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7211 - val_loss: 0.5452 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5324 - accuracy: 0.7317 - val_loss: 0.5427 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7396 - val_loss: 0.5408 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5102 - accuracy: 0.7493 - val_loss: 0.5404 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4986 - accuracy: 0.7566 - val_loss: 0.5413 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4858 - accuracy: 0.7654 - val_loss: 0.5426 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7738 - val_loss: 0.5474 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4622 - accuracy: 0.7807
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4626 - accuracy: 0.7802 - val_loss: 0.5507 - val_accuracy: 0.7175 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43268730776976533
Confusion Matrix :
 [[2919 1128]
 [1168 2879]]
Accuracy on test set:    0.7163330862367185
Sensitivity:    0.711391153941191 	 Specificity:    0.7212750185322461
Precision  : 0.7184926378837035
Area Under Curve:    0.7163330862367185
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5891 - accuracy: 0.6827 - val_loss: 0.5541 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7216 - val_loss: 0.5469 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5334 - accuracy: 0.7303 - val_loss: 0.5490 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5227 - accuracy: 0.7383 - val_loss: 0.5441 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5128 - accuracy: 0.7440 - val_loss: 0.5440 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7521 - val_loss: 0.5522 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.7603 - val_loss: 0.5476 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7677 - val_loss: 0.5518 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4686 - accuracy: 0.7774 - val_loss: 0.5549 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4556 - accuracy: 0.7841 - val_loss: 0.5584 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4430 - accuracy: 0.7909 - val_loss: 0.5706 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4312 - accuracy: 0.8001 - val_loss: 0.5695 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4170 - accuracy: 0.8079 - val_loss: 0.5752 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 14/400
256/257 [============================>.] - ETA: 0s - loss: 0.4066 - accuracy: 0.8148
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4065 - accuracy: 0.8149 - val_loss: 0.5858 - val_accuracy: 0.7167 - lr: 0.0010
253/253 [==============================] - 0s 950us/step
Independent Testing Matthews Correlation:  0.4374074935909474
Confusion Matrix :
 [[2938 1109]
 [1168 2879]]
Accuracy on test set:    0.7186805040770942
Sensitivity:    0.711391153941191 	 Specificity:    0.7259698542129973
Precision  : 0.7219157472417251
Area Under Curve:    0.7186805040770943
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5905 - accuracy: 0.6837 - val_loss: 0.5788 - val_accuracy: 0.6902 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5502 - accuracy: 0.7193 - val_loss: 0.5497 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5355 - accuracy: 0.7293 - val_loss: 0.5463 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5236 - accuracy: 0.7372 - val_loss: 0.5518 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5120 - accuracy: 0.7453 - val_loss: 0.5491 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.7540 - val_loss: 0.5454 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.7633 - val_loss: 0.5460 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4785 - accuracy: 0.7718
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4785 - accuracy: 0.7718 - val_loss: 0.5587 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 845us/step
Independent Testing Matthews Correlation:  0.48875747705202655
Confusion Matrix :
 [[3010 1037]
 [1032 3015]]
Accuracy on test set:    0.7443785520138374
Sensitivity:    0.7449962935507783 	 Specificity:    0.7437608104768965
Precision  : 0.7440769990128332
Area Under Curve:    0.7443785520138374
(8094, 2560) (8094,)
Mean MCC = 0.4270 + 0.0263 and Mean AUC = 0.7133 + 0.0133
Mean Sensitivity = 0.7230 + 0.0160 and Mean Specificity = 0.7037 + 0.0273 and Mean Accuracy = 0.7133 + 0.0133
Mean Precision = 0.7098 + 0.0175





Seed   : 969291

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5866 - accuracy: 0.6835 - val_loss: 0.5519 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7238 - val_loss: 0.5449 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7333 - val_loss: 0.5418 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7405 - val_loss: 0.5425 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7501 - val_loss: 0.5437 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7572 - val_loss: 0.5493 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7647 - val_loss: 0.5543 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.7725 - val_loss: 0.5546 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4626 - accuracy: 0.7790 - val_loss: 0.5571 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 10/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4503 - accuracy: 0.7865
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4510 - accuracy: 0.7862 - val_loss: 0.5643 - val_accuracy: 0.7117 - lr: 0.0010
253/253 [==============================] - 0s 948us/step
Independent Testing Matthews Correlation:  0.4033443067085346
Confusion Matrix :
 [[2664 1384]
 [1037 3010]]
Accuracy on test set:    0.7009264978381717
Sensitivity:    0.7437608104768965 	 Specificity:    0.658102766798419
Precision  : 0.6850250341374602
Area Under Curve:    0.7009317886376577
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5882 - accuracy: 0.6833 - val_loss: 0.5592 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7254 - val_loss: 0.5460 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7335 - val_loss: 0.5482 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7446 - val_loss: 0.5510 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7541 - val_loss: 0.5493 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.7603 - val_loss: 0.5527 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4794 - accuracy: 0.7699
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7699 - val_loss: 0.5531 - val_accuracy: 0.7135 - lr: 0.0010
253/253 [==============================] - 0s 845us/step
Independent Testing Matthews Correlation:  0.4324905888686128
Confusion Matrix :
 [[2905 1143]
 [1154 2893]]
Accuracy on test set:    0.7162445954292773
Sensitivity:    0.7148505065480603 	 Specificity:    0.7176383399209486
Precision  : 0.716798810703667
Area Under Curve:    0.7162444232345043
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.6837 - val_loss: 0.5474 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7228 - val_loss: 0.5410 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7369 - val_loss: 0.5347 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5141 - accuracy: 0.7445 - val_loss: 0.5364 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7520 - val_loss: 0.5322 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7611 - val_loss: 0.5394 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7688 - val_loss: 0.5412 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4637 - accuracy: 0.7766 - val_loss: 0.5482 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4525 - accuracy: 0.7854 - val_loss: 0.5554 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4379 - accuracy: 0.7945
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4382 - accuracy: 0.7944 - val_loss: 0.5536 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 830us/step
Independent Testing Matthews Correlation:  0.3944930782244082
Confusion Matrix :
 [[2854 1193]
 [1258 2790]]
Accuracy on test set:    0.6972205064854848
Sensitivity:    0.6892292490118577 	 Specificity:    0.7052137385717816
Precision  : 0.7004770273663068
Area Under Curve:    0.6972214937918196
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5827 - accuracy: 0.6879 - val_loss: 0.5419 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7240 - val_loss: 0.5315 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5256 - accuracy: 0.7359 - val_loss: 0.5308 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.7425 - val_loss: 0.5315 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5020 - accuracy: 0.7531 - val_loss: 0.5368 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4924 - accuracy: 0.7601 - val_loss: 0.5339 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.7688 - val_loss: 0.5393 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7758 - val_loss: 0.5396 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4549 - accuracy: 0.7847 - val_loss: 0.5413 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4413 - accuracy: 0.7927 - val_loss: 0.5463 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 11/400
249/257 [============================>.] - ETA: 0s - loss: 0.4261 - accuracy: 0.8042
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4265 - accuracy: 0.8038 - val_loss: 0.5489 - val_accuracy: 0.7245 - lr: 0.0010
253/253 [==============================] - 0s 813us/step
Independent Testing Matthews Correlation:  0.43125393909446613
Confusion Matrix :
 [[2897 1150]
 [1152 2896]]
Accuracy on test set:    0.7156269302038295
Sensitivity:    0.7154150197628458 	 Specificity:    0.7158388930071659
Precision  : 0.7157686604053386
Area Under Curve:    0.7156269563850057
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5891 - accuracy: 0.6824 - val_loss: 0.5533 - val_accuracy: 0.7235 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7208 - val_loss: 0.5417 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7347 - val_loss: 0.5405 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7398 - val_loss: 0.5456 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7472 - val_loss: 0.5422 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7569 - val_loss: 0.5432 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4852 - accuracy: 0.7644
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4854 - accuracy: 0.7645 - val_loss: 0.5492 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4178323037365859
Confusion Matrix :
 [[2682 1365]
 [ 998 3049]]
Accuracy on test set:    0.7080553496417099
Sensitivity:    0.7533975784531752 	 Specificity:    0.6627131208302446
Precision  : 0.6907566832804712
Area Under Curve:    0.7080553496417099
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5852 - accuracy: 0.6857 - val_loss: 0.5548 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7218 - val_loss: 0.5460 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5267 - accuracy: 0.7336 - val_loss: 0.5435 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5168 - accuracy: 0.7433 - val_loss: 0.5445 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7518 - val_loss: 0.5422 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7610 - val_loss: 0.5532 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4829 - accuracy: 0.7662
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7660 - val_loss: 0.5428 - val_accuracy: 0.7241 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43723694522112094
Confusion Matrix :
 [[2860 1187]
 [1091 2956]]
Accuracy on test set:    0.7185569557697059
Sensitivity:    0.730417593278972 	 Specificity:    0.7066963182604399
Precision  : 0.7134926381848902
Area Under Curve:    0.7185569557697059
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5894 - accuracy: 0.6822 - val_loss: 0.5529 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7209 - val_loss: 0.5451 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7341 - val_loss: 0.5472 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5216 - accuracy: 0.7387 - val_loss: 0.5428 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.7464 - val_loss: 0.5418 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5020 - accuracy: 0.7529 - val_loss: 0.5496 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7592 - val_loss: 0.5462 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7663 - val_loss: 0.5499 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4723 - accuracy: 0.7743 - val_loss: 0.5562 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4609 - accuracy: 0.7830 - val_loss: 0.5562 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4498 - accuracy: 0.7892 - val_loss: 0.5627 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4381 - accuracy: 0.7961
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4385 - accuracy: 0.7958 - val_loss: 0.5778 - val_accuracy: 0.7170 - lr: 0.0010
253/253 [==============================] - 0s 893us/step
Independent Testing Matthews Correlation:  0.4297152316119998
Confusion Matrix :
 [[2639 1408]
 [ 913 3134]]
Accuracy on test set:    0.7132443785520138
Sensitivity:    0.7744007907091672 	 Specificity:    0.6520879663948604
Precision  : 0.6900044033465433
Area Under Curve:    0.7132443785520138
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5903 - accuracy: 0.6840 - val_loss: 0.5494 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5488 - accuracy: 0.7205 - val_loss: 0.5443 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5339 - accuracy: 0.7306 - val_loss: 0.5389 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5221 - accuracy: 0.7389 - val_loss: 0.5400 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.7479 - val_loss: 0.5393 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7555 - val_loss: 0.5449 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4866 - accuracy: 0.7645 - val_loss: 0.5472 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4749 - accuracy: 0.7716
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7718 - val_loss: 0.5540 - val_accuracy: 0.7193 - lr: 0.0010
253/253 [==============================] - 0s 712us/step
Independent Testing Matthews Correlation:  0.44246499317174803
Confusion Matrix :
 [[2831 1216]
 [1042 3005]]
Accuracy on test set:    0.7210279219174698
Sensitivity:    0.7425253274030146 	 Specificity:    0.6995305164319249
Precision  : 0.7119166074389955
Area Under Curve:    0.7210279219174698
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5951 - accuracy: 0.6784 - val_loss: 0.5586 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5506 - accuracy: 0.7204 - val_loss: 0.5501 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5343 - accuracy: 0.7303 - val_loss: 0.5435 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5239 - accuracy: 0.7373 - val_loss: 0.5437 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5124 - accuracy: 0.7458 - val_loss: 0.5422 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5015 - accuracy: 0.7530 - val_loss: 0.5487 - val_accuracy: 0.7159 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.7596 - val_loss: 0.5468 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4806 - accuracy: 0.7681 - val_loss: 0.5620 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4690 - accuracy: 0.7764 - val_loss: 0.5561 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4552 - accuracy: 0.7866 - val_loss: 0.5577 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4443 - accuracy: 0.7915 - val_loss: 0.5596 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 12/400
256/257 [============================>.] - ETA: 0s - loss: 0.4326 - accuracy: 0.7993
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4325 - accuracy: 0.7994 - val_loss: 0.5714 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.45614103321453964
Confusion Matrix :
 [[2950 1097]
 [1104 2943]]
Accuracy on test set:    0.7280701754385965
Sensitivity:    0.7272053372868792 	 Specificity:    0.7289350135903138
Precision  : 0.7284653465346534
Area Under Curve:    0.7280701754385965
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5918 - accuracy: 0.6821 - val_loss: 0.5570 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5507 - accuracy: 0.7196 - val_loss: 0.5527 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5336 - accuracy: 0.7315 - val_loss: 0.5499 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5209 - accuracy: 0.7410 - val_loss: 0.5535 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7489 - val_loss: 0.5493 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7577 - val_loss: 0.5522 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7650 - val_loss: 0.5509 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7739 - val_loss: 0.5578 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4616 - accuracy: 0.7833 - val_loss: 0.5566 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4512 - accuracy: 0.7892
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4515 - accuracy: 0.7891 - val_loss: 0.5750 - val_accuracy: 0.7130 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.49470592377007416
Confusion Matrix :
 [[3007 1040]
 [1005 3042]]
Accuracy on test set:    0.747343711391154
Sensitivity:    0.7516679021497406 	 Specificity:    0.7430195206325674
Precision  : 0.7452229299363057
Area Under Curve:    0.747343711391154
(8094, 2560) (8094,)
Mean MCC = 0.4340 + 0.0265 and Mean AUC = 0.7166 + 0.0134
Mean Sensitivity = 0.7343 + 0.0229 and Mean Specificity = 0.6990 + 0.0296 and Mean Accuracy = 0.7166 + 0.0134
Mean Precision = 0.7098 + 0.0178





Seed   : 351950
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5855 - accuracy: 0.6846 - val_loss: 0.5573 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5432 - accuracy: 0.7252 - val_loss: 0.5562 - val_accuracy: 0.7008 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7349 - val_loss: 0.5522 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7430 - val_loss: 0.5462 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7523 - val_loss: 0.5534 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4911 - accuracy: 0.7609 - val_loss: 0.5510 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7689 - val_loss: 0.5601 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4695 - accuracy: 0.7769 - val_loss: 0.5571 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4592 - accuracy: 0.7822 - val_loss: 0.5643 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4453 - accuracy: 0.7922
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4453 - accuracy: 0.7922 - val_loss: 0.5717 - val_accuracy: 0.7075 - lr: 0.0010
253/253 [==============================] - 0s 871us/step
Independent Testing Matthews Correlation:  0.4115211206613468
Confusion Matrix :
 [[2754 1294]
 [1090 2957]]
Accuracy on test set:    0.7054972205064854
Sensitivity:    0.7306646898937484 	 Specificity:    0.6803359683794467
Precision  : 0.6956010350505764
Area Under Curve:    0.7055003291365974
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5832 - accuracy: 0.6878 - val_loss: 0.5548 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7262 - val_loss: 0.5538 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7349 - val_loss: 0.5473 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7443 - val_loss: 0.5480 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7516 - val_loss: 0.5468 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 6/400
253/257 [============================>.] - ETA: 0s - loss: 0.4945 - accuracy: 0.7588
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7590 - val_loss: 0.5643 - val_accuracy: 0.7062 - lr: 0.0010
253/253 [==============================] - 0s 996us/step
Independent Testing Matthews Correlation:  0.4165336556233651
Confusion Matrix :
 [[2401 1647]
 [ 756 3291]]
Accuracy on test set:    0.7031500926497838
Sensitivity:    0.8131949592290586 	 Specificity:    0.5931324110671937
Precision  : 0.6664641555285541
Area Under Curve:    0.7031636851481261
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6824 - val_loss: 0.5503 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7244 - val_loss: 0.5546 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5330 - accuracy: 0.7314 - val_loss: 0.5429 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7417 - val_loss: 0.5429 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7475 - val_loss: 0.5394 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7552 - val_loss: 0.5383 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7617 - val_loss: 0.5422 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4784 - accuracy: 0.7708 - val_loss: 0.5519 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4667 - accuracy: 0.7775 - val_loss: 0.5475 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4548 - accuracy: 0.7852 - val_loss: 0.5533 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4443 - accuracy: 0.7933 - val_loss: 0.5545 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 12/400
254/257 [============================>.] - ETA: 0s - loss: 0.4334 - accuracy: 0.7987
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4333 - accuracy: 0.7987 - val_loss: 0.5613 - val_accuracy: 0.7205 - lr: 0.0010
253/253 [==============================] - 0s 816us/step
Independent Testing Matthews Correlation:  0.4177763705288326
Confusion Matrix :
 [[2650 1397]
 [ 969 3079]]
Accuracy on test set:    0.7077208153180976
Sensitivity:    0.7606225296442688 	 Specificity:    0.6548060291574005
Precision  : 0.6878909740840036
Area Under Curve:    0.7077142794008346
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5900 - accuracy: 0.6816 - val_loss: 0.5529 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7236 - val_loss: 0.5386 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7338 - val_loss: 0.5344 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7410 - val_loss: 0.5332 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7488 - val_loss: 0.5333 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7581 - val_loss: 0.5372 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7671 - val_loss: 0.5407 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7770 - val_loss: 0.5425 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4546 - accuracy: 0.7861 - val_loss: 0.5442 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4411 - accuracy: 0.7925
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4414 - accuracy: 0.7923 - val_loss: 0.5526 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4196827001485642
Confusion Matrix :
 [[2635 1412]
 [ 948 3100]]
Accuracy on test set:    0.7084620135886349
Sensitivity:    0.7658102766798419 	 Specificity:    0.6510995799357548
Precision  : 0.6870567375886525
Area Under Curve:    0.7084549283077983
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5929 - accuracy: 0.6812 - val_loss: 0.5561 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5482 - accuracy: 0.7185 - val_loss: 0.5458 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7308 - val_loss: 0.5435 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7389 - val_loss: 0.5425 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7463 - val_loss: 0.5548 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7547 - val_loss: 0.5441 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7613 - val_loss: 0.5439 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4709 - accuracy: 0.7744
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7740 - val_loss: 0.5507 - val_accuracy: 0.7120 - lr: 0.0010
253/253 [==============================] - 0s 840us/step
Independent Testing Matthews Correlation:  0.4174948716154715
Confusion Matrix :
 [[2922 1125]
 [1233 2814]]
Accuracy on test set:    0.7086730911786508
Sensitivity:    0.6953298739807264 	 Specificity:    0.7220163083765753
Precision  : 0.7143945163747144
Area Under Curve:    0.708673091178651
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5883 - accuracy: 0.6831 - val_loss: 0.5586 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7212 - val_loss: 0.5478 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7337 - val_loss: 0.5456 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7406 - val_loss: 0.5420 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7497 - val_loss: 0.5435 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7583 - val_loss: 0.5439 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4861 - accuracy: 0.7651 - val_loss: 0.5478 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4724 - accuracy: 0.7751
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7751 - val_loss: 0.5540 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.4235030066648491
Confusion Matrix :
 [[2761 1286]
 [1050 2997]]
Accuracy on test set:    0.711391153941191
Sensitivity:    0.7405485544848036 	 Specificity:    0.6822337533975784
Precision  : 0.6997431706747607
Area Under Curve:    0.711391153941191
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5846 - accuracy: 0.6885 - val_loss: 0.5502 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7251 - val_loss: 0.5441 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7337 - val_loss: 0.5408 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7423 - val_loss: 0.5469 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7496 - val_loss: 0.5416 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7582 - val_loss: 0.5492 - val_accuracy: 0.7218 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.7654 - val_loss: 0.5461 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7752 - val_loss: 0.5541 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4612 - accuracy: 0.7806 - val_loss: 0.5507 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4492 - accuracy: 0.7881 - val_loss: 0.5568 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4356 - accuracy: 0.7983 - val_loss: 0.5599 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4242 - accuracy: 0.8054
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4248 - accuracy: 0.8052 - val_loss: 0.5789 - val_accuracy: 0.7150 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40964464491317604
Confusion Matrix :
 [[2713 1334]
 [1059 2988]]
Accuracy on test set:    0.7043489004200643
Sensitivity:    0.7383246849518161 	 Specificity:    0.6703731158883123
Precision  : 0.6913465987968533
Area Under Curve:    0.7043489004200643
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5894 - accuracy: 0.6787 - val_loss: 0.5546 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7205 - val_loss: 0.5459 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7327 - val_loss: 0.5435 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7415 - val_loss: 0.5419 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7480 - val_loss: 0.5441 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7537 - val_loss: 0.5432 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7633 - val_loss: 0.5480 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7702 - val_loss: 0.5473 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 9/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4608 - accuracy: 0.7814
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4606 - accuracy: 0.7813 - val_loss: 0.5550 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 997us/step
Independent Testing Matthews Correlation:  0.44344634705771074
Confusion Matrix :
 [[2867 1180]
 [1073 2974]]
Accuracy on test set:    0.7216456634544107
Sensitivity:    0.7348653323449469 	 Specificity:    0.7084259945638745
Precision  : 0.7159364467982667
Area Under Curve:    0.7216456634544106
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5893 - accuracy: 0.6829 - val_loss: 0.5578 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7214 - val_loss: 0.5576 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7328 - val_loss: 0.5492 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7412 - val_loss: 0.5521 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7470 - val_loss: 0.5487 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4980 - accuracy: 0.7552 - val_loss: 0.5518 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4861 - accuracy: 0.7633 - val_loss: 0.5535 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4754 - accuracy: 0.7721 - val_loss: 0.5638 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4618 - accuracy: 0.7810
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4621 - accuracy: 0.7809 - val_loss: 0.5620 - val_accuracy: 0.7084 - lr: 0.0010
253/253 [==============================] - 0s 779us/step
Independent Testing Matthews Correlation:  0.46538035958183605
Confusion Matrix :
 [[3066  981]
 [1185 2862]]
Accuracy on test set:    0.7323943661971831
Sensitivity:    0.7071905114899926 	 Specificity:    0.7575982209043736
Precision  : 0.7447306791569087
Area Under Curve:    0.7323943661971831
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5897 - accuracy: 0.6838 - val_loss: 0.5612 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7196 - val_loss: 0.5577 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5324 - accuracy: 0.7327 - val_loss: 0.5586 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5220 - accuracy: 0.7398 - val_loss: 0.5510 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5110 - accuracy: 0.7473 - val_loss: 0.5541 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5000 - accuracy: 0.7564 - val_loss: 0.5530 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7637 - val_loss: 0.5560 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.7728 - val_loss: 0.5617 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4613 - accuracy: 0.7823
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4618 - accuracy: 0.7820 - val_loss: 0.5641 - val_accuracy: 0.7091 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47928476695995564
Confusion Matrix :
 [[3046 1001]
 [1107 2940]]
Accuracy on test set:    0.739560168025698
Sensitivity:    0.72646404744255 	 Specificity:    0.752656288608846
Precision  : 0.7460035523978685
Area Under Curve:    0.739560168025698
(8094, 2560) (8094,)
Mean MCC = 0.4304 + 0.0229 and Mean AUC = 0.7143 + 0.0120
Mean Sensitivity = 0.7413 + 0.0313 and Mean Specificity = 0.6873 + 0.0474 and Mean Accuracy = 0.7143 + 0.0120
Mean Precision = 0.7049 + 0.0242





Seed   : 630950
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5857 - accuracy: 0.6873 - val_loss: 0.5639 - val_accuracy: 0.7036 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7231 - val_loss: 0.5541 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7352 - val_loss: 0.5550 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7417 - val_loss: 0.5544 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7501 - val_loss: 0.5533 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7548 - val_loss: 0.5562 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.7617 - val_loss: 0.5521 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4762 - accuracy: 0.7707 - val_loss: 0.5589 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4645 - accuracy: 0.7774 - val_loss: 0.5695 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4534 - accuracy: 0.7852 - val_loss: 0.5802 - val_accuracy: 0.7040 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4417 - accuracy: 0.7933
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4418 - accuracy: 0.7932 - val_loss: 0.5714 - val_accuracy: 0.7148 - lr: 0.0010
253/253 [==============================] - 0s 838us/step
Independent Testing Matthews Correlation:  0.4135212550194068
Confusion Matrix :
 [[2828 1220]
 [1154 2893]]
Accuracy on test set:    0.7067325509573811
Sensitivity:    0.7148505065480603 	 Specificity:    0.6986166007905138
Precision  : 0.7033795283248238
Area Under Curve:    0.7067335536692871
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5871 - accuracy: 0.6841 - val_loss: 0.5596 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7228 - val_loss: 0.5538 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7340 - val_loss: 0.5592 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7406 - val_loss: 0.5473 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7493 - val_loss: 0.5478 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7561 - val_loss: 0.5479 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7663 - val_loss: 0.5554 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4734 - accuracy: 0.7734 - val_loss: 0.5521 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4624 - accuracy: 0.7806 - val_loss: 0.5580 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4517 - accuracy: 0.7882 - val_loss: 0.5694 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4397 - accuracy: 0.7934 - val_loss: 0.5884 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4295 - accuracy: 0.7999 - val_loss: 0.5800 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 13/400
256/257 [============================>.] - ETA: 0s - loss: 0.4169 - accuracy: 0.8069
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4170 - accuracy: 0.8069 - val_loss: 0.5923 - val_accuracy: 0.7108 - lr: 0.0010
253/253 [==============================] - 0s 835us/step
Independent Testing Matthews Correlation:  0.4149688882489454
Confusion Matrix :
 [[2662 1386]
 [ 990 3057]]
Accuracy on test set:    0.706485484867202
Sensitivity:    0.7553743513713862 	 Specificity:    0.657608695652174
Precision  : 0.6880486158001351
Area Under Curve:    0.7064915235117799
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5912 - accuracy: 0.6808 - val_loss: 0.5521 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7210 - val_loss: 0.5451 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7331 - val_loss: 0.5435 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7403 - val_loss: 0.5401 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7498 - val_loss: 0.5420 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7601 - val_loss: 0.5451 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7665 - val_loss: 0.5448 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4702 - accuracy: 0.7757 - val_loss: 0.5547 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4562 - accuracy: 0.7836 - val_loss: 0.5556 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4427 - accuracy: 0.7937 - val_loss: 0.5593 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4316 - accuracy: 0.8003 - val_loss: 0.5589 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4180 - accuracy: 0.8076 - val_loss: 0.5613 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4062 - accuracy: 0.8140 - val_loss: 0.5886 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3936 - accuracy: 0.8212 - val_loss: 0.5786 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 15/400
255/257 [============================>.] - ETA: 0s - loss: 0.3800 - accuracy: 0.8284
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3799 - accuracy: 0.8284 - val_loss: 0.5949 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4002563602318031
Confusion Matrix :
 [[2648 1399]
 [1035 3013]]
Accuracy on test set:    0.6993205682520074
Sensitivity:    0.7443181818181818 	 Specificity:    0.6543118359278478
Precision  : 0.6829102447869447
Area Under Curve:    0.6993150088730148
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5937 - accuracy: 0.6788 - val_loss: 0.5552 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7211 - val_loss: 0.5425 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7309 - val_loss: 0.5395 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7402 - val_loss: 0.5400 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7476 - val_loss: 0.5427 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7551 - val_loss: 0.5396 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4863 - accuracy: 0.7631 - val_loss: 0.5419 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400

257/257 [==============================] - 1s 4ms/step - loss: 0.4750 - accuracy: 0.7709 - val_loss: 0.5463 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4638 - accuracy: 0.7776 - val_loss: 0.5514 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4511 - accuracy: 0.7871 - val_loss: 0.5518 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
256/257 [============================>.] - ETA: 0s - loss: 0.4389 - accuracy: 0.7955
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4390 - accuracy: 0.7954 - val_loss: 0.5653 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4156692419732172
Confusion Matrix :
 [[2664 1383]
 [ 990 3058]]
Accuracy on test set:    0.7068560840024707
Sensitivity:    0.7554347826086957 	 Specificity:    0.6582653817642699
Precision  : 0.6885836523305562
Area Under Curve:    0.7068500821864828
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5869 - accuracy: 0.6853 - val_loss: 0.5616 - val_accuracy: 0.7017 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7212 - val_loss: 0.5428 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7335 - val_loss: 0.5412 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7407 - val_loss: 0.5410 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5093 - accuracy: 0.7472 - val_loss: 0.5397 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.7553 - val_loss: 0.5452 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.7645 - val_loss: 0.5413 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4762 - accuracy: 0.7704
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4765 - accuracy: 0.7703 - val_loss: 0.5486 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42675552538948575
Confusion Matrix :
 [[2746 1301]
 [1023 3024]]
Accuracy on test set:    0.7128737336298493
Sensitivity:    0.7472201630837657 	 Specificity:    0.6785273041759328
Precision  : 0.6991907514450867
Area Under Curve:    0.7128737336298492
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5881 - accuracy: 0.6826 - val_loss: 0.5512 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7211 - val_loss: 0.5444 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.7343 - val_loss: 0.5420 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5168 - accuracy: 0.7418 - val_loss: 0.5408 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7517 - val_loss: 0.5414 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7585 - val_loss: 0.5445 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4836 - accuracy: 0.7651 - val_loss: 0.5437 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4727 - accuracy: 0.7724
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4727 - accuracy: 0.7723 - val_loss: 0.5493 - val_accuracy: 0.7148 - lr: 0.0010
253/253 [==============================] - 0s 890us/step
Independent Testing Matthews Correlation:  0.4358042700599679
Confusion Matrix :
 [[2962 1085]
 [1199 2848]]
Accuracy on test set:    0.7178156659253768
Sensitivity:    0.7037311588831233 	 Specificity:    0.7319001729676303
Precision  : 0.7241291634884313
Area Under Curve:    0.7178156659253768
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5928 - accuracy: 0.6799 - val_loss: 0.5504 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7210 - val_loss: 0.5427 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7325 - val_loss: 0.5403 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7414 - val_loss: 0.5384 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7498 - val_loss: 0.5432 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7579 - val_loss: 0.5454 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7667 - val_loss: 0.5463 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4689 - accuracy: 0.7755
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4693 - accuracy: 0.7753 - val_loss: 0.5579 - val_accuracy: 0.7209 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.4298793696691707
Confusion Matrix :
 [[2653 1394]
 [ 925 3122]]
Accuracy on test set:    0.7134914751667902
Sensitivity:    0.7714356313318508 	 Specificity:    0.6555473190017297
Precision  : 0.6913197519929141
Area Under Curve:    0.7134914751667902
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5929 - accuracy: 0.6797 - val_loss: 0.5550 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7215 - val_loss: 0.5420 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7333 - val_loss: 0.5370 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7420 - val_loss: 0.5359 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7490 - val_loss: 0.5438 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7576 - val_loss: 0.5399 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7642 - val_loss: 0.5418 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4716 - accuracy: 0.7743 - val_loss: 0.5461 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4600 - accuracy: 0.7809 - val_loss: 0.5488 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4479 - accuracy: 0.7881 - val_loss: 0.5587 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4375 - accuracy: 0.7945 - val_loss: 0.5635 - val_accuracy: 0.7201 - lr: 0.0010

Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4234 - accuracy: 0.8021 - val_loss: 0.5642 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 13/400
251/257 [============================>.] - ETA: 0s - loss: 0.4119 - accuracy: 0.8092
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4122 - accuracy: 0.8089 - val_loss: 0.5774 - val_accuracy: 0.7219 - lr: 0.0010
253/253 [==============================] - 0s 902us/step
Independent Testing Matthews Correlation:  0.41948362640053904
Confusion Matrix :
 [[2928 1119]
 [1231 2816]]
Accuracy on test set:    0.7096614776377563
Sensitivity:    0.6958240672102792 	 Specificity:    0.7234988880652335
Precision  : 0.7156289707750954
Area Under Curve:    0.7096614776377563
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5899 - accuracy: 0.6829 - val_loss: 0.5571 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5480 - accuracy: 0.7191 - val_loss: 0.5436 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7314 - val_loss: 0.5497 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5211 - accuracy: 0.7387 - val_loss: 0.5442 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7470 - val_loss: 0.5454 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7555 - val_loss: 0.5466 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.7628 - val_loss: 0.5510 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4765 - accuracy: 0.7726 - val_loss: 0.5546 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4650 - accuracy: 0.7781
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7781 - val_loss: 0.5652 - val_accuracy: 0.7179 - lr: 0.0010
253/253 [==============================] - 0s 864us/step
Independent Testing Matthews Correlation:  0.46216706230698734
Confusion Matrix :
 [[3036 1011]
 [1167 2880]]
Accuracy on test set:    0.7309117865085248
Sensitivity:    0.7116382505559674 	 Specificity:    0.7501853224610823
Precision  : 0.7401696222050886
Area Under Curve:    0.7309117865085248
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5918 - accuracy: 0.6824 - val_loss: 0.5528 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5502 - accuracy: 0.7181 - val_loss: 0.5436 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5350 - accuracy: 0.7303 - val_loss: 0.5471 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5229 - accuracy: 0.7382 - val_loss: 0.5430 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5116 - accuracy: 0.7449 - val_loss: 0.5455 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5022 - accuracy: 0.7558 - val_loss: 0.5453 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.7624 - val_loss: 0.5492 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4769 - accuracy: 0.7704
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4766 - accuracy: 0.7707 - val_loss: 0.5584 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4655359309800464
Confusion Matrix :
 [[3321  726]
 [1469 2578]]
Accuracy on test set:    0.7288114652829256
Sensitivity:    0.6370150728935013 	 Specificity:    0.8206078576723499
Precision  : 0.7802663438256658
Area Under Curve:    0.7288114652829256
(8094, 2560) (8094,)
Mean MCC = 0.4284 + 0.0200 and Mean AUC = 0.7133 + 0.0095
Mean Sensitivity = 0.7237 + 0.0377 and Mean Specificity = 0.7029 + 0.0516 and Mean Accuracy = 0.7133 + 0.0095
Mean Precision = 0.7114 + 0.0287





Seed   : 6214
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5881 - accuracy: 0.6826 - val_loss: 0.5549 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7231 - val_loss: 0.5453 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7345 - val_loss: 0.5429 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7425 - val_loss: 0.5517 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7513 - val_loss: 0.5447 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.7588 - val_loss: 0.5482 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7682 - val_loss: 0.5551 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.7758 - val_loss: 0.5535 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4549 - accuracy: 0.7854 - val_loss: 0.5586 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4447 - accuracy: 0.7913 - val_loss: 0.5652 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4309 - accuracy: 0.7992
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4308 - accuracy: 0.7992 - val_loss: 0.5759 - val_accuracy: 0.7111 - lr: 0.0010
253/253 [==============================] - 0s 789us/step
Independent Testing Matthews Correlation:  0.3978593213362134
Confusion Matrix :
 [[2590 1458]
 [ 990 3057]]
Accuracy on test set:    0.6975911056207535
Sensitivity:    0.7553743513713862 	 Specificity:    0.6398221343873518
Precision  : 0.6770764119601329
Area Under Curve:    0.697598242879369
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5856 - accuracy: 0.6859 - val_loss: 0.5532 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7253 - val_loss: 0.5440 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5250 - accuracy: 0.7362 - val_loss: 0.5409 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.7444 - val_loss: 0.5446 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.7536 - val_loss: 0.5461 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7611 - val_loss: 0.5449 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7679 - val_loss: 0.5490 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4672 - accuracy: 0.7772
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4672 - accuracy: 0.7774 - val_loss: 0.5677 - val_accuracy: 0.7108 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39017369382924366
Confusion Matrix :
 [[2503 1545]
 [ 941 3106]]
Accuracy on test set:    0.6928968499073502
Sensitivity:    0.7674820854954287 	 Specificity:    0.6183300395256917
Precision  : 0.6678133734680713
Area Under Curve:    0.6929060625105601
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5994 - accuracy: 0.6730 - val_loss: 0.5508 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5504 - accuracy: 0.7185 - val_loss: 0.5414 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5358 - accuracy: 0.7293 - val_loss: 0.5361 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5244 - accuracy: 0.7378 - val_loss: 0.5371 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7435 - val_loss: 0.5361 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7511 - val_loss: 0.5358 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7583 - val_loss: 0.5431 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4824 - accuracy: 0.7686
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7688 - val_loss: 0.5481 - val_accuracy: 0.7220 - lr: 0.0010
253/253 [==============================] - 0s 954us/step
Independent Testing Matthews Correlation:  0.4222216139238313
Confusion Matrix :
 [[2685 1362]
 [ 984 3064]]
Accuracy on test set:    0.7101914762198889
Sensitivity:    0.7569169960474308 	 Specificity:    0.6634544106745738
Precision  : 0.6922729326705829
Area Under Curve:    0.7101857033610023
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5882 - accuracy: 0.6838 - val_loss: 0.5536 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7230 - val_loss: 0.5399 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.7355 - val_loss: 0.5375 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.7435 - val_loss: 0.5363 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5011 - accuracy: 0.7547 - val_loss: 0.5469 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.7609 - val_loss: 0.5390 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4762 - accuracy: 0.7719 - val_loss: 0.5474 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7805 - val_loss: 0.5472 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4515 - accuracy: 0.7888 - val_loss: 0.5619 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4382 - accuracy: 0.7957 - val_loss: 0.5618 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 11/400
249/257 [============================>.] - ETA: 0s - loss: 0.4237 - accuracy: 0.8048
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4243 - accuracy: 0.8045 - val_loss: 0.5596 - val_accuracy: 0.7145 - lr: 0.0010
253/253 [==============================] - 0s 754us/step
Independent Testing Matthews Correlation:  0.41933288361386223
Confusion Matrix :
 [[2755 1292]
 [1061 2987]]
Accuracy on test set:    0.7093267449042618
Sensitivity:    0.7378952569169961 	 Specificity:    0.6807511737089202
Precision  : 0.6980602944613228
Area Under Curve:    0.7093232153129582
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5993 - accuracy: 0.6731 - val_loss: 0.5561 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5494 - accuracy: 0.7209 - val_loss: 0.5487 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7304 - val_loss: 0.5465 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5213 - accuracy: 0.7400 - val_loss: 0.5455 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.7482 - val_loss: 0.5449 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7568 - val_loss: 0.5508 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4823 - accuracy: 0.7677
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7670 - val_loss: 0.5519 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4225500597400189
Confusion Matrix :
 [[2756 1291]
 [1049 2998]]
Accuracy on test set:    0.7108969607116382
Sensitivity:    0.7407956510995799 	 Specificity:    0.6809982703236965
Precision  : 0.6989974352996037
Area Under Curve:    0.7108969607116382
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5854 - accuracy: 0.6845 - val_loss: 0.5532 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5432 - accuracy: 0.7238 - val_loss: 0.5493 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7327 - val_loss: 0.5470 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7418 - val_loss: 0.5479 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7500 - val_loss: 0.5469 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 6/400
251/257 [============================>.] - ETA: 0s - loss: 0.4971 - accuracy: 0.7565
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7568 - val_loss: 0.5511 - val_accuracy: 0.7106 - lr: 0.0010
253/253 [==============================] - 0s 809us/step
Independent Testing Matthews Correlation:  0.42309092569597917
Confusion Matrix :
 [[3062  985]
 [1357 2690]]
Accuracy on test set:    0.7106498640968619
Sensitivity:    0.6646898937484557 	 Specificity:    0.7566098344452681
Precision  : 0.7319727891156462
Area Under Curve:    0.7106498640968619
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5880 - accuracy: 0.6837 - val_loss: 0.5521 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7215 - val_loss: 0.5452 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400

257/257 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7319 - val_loss: 0.5425 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5229 - accuracy: 0.7370 - val_loss: 0.5458 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5135 - accuracy: 0.7460 - val_loss: 0.5442 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7531 - val_loss: 0.5442 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7562 - val_loss: 0.5471 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4863 - accuracy: 0.7654
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.7652 - val_loss: 0.5491 - val_accuracy: 0.7157 - lr: 0.0010
253/253 [==============================] - 0s 872us/step
Independent Testing Matthews Correlation:  0.438274578030025
Confusion Matrix :
 [[2821 1226]
 [1049 2998]]
Accuracy on test set:    0.7189276006918706
Sensitivity:    0.7407956510995799 	 Specificity:    0.6970595502841611
Precision  : 0.7097537878787878
Area Under Curve:    0.7189276006918704
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5886 - accuracy: 0.6849 - val_loss: 0.5492 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7213 - val_loss: 0.5424 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7339 - val_loss: 0.5546 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7404 - val_loss: 0.5475 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7494 - val_loss: 0.5412 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
254/257 [============================>.] - ETA: 0s - loss: 0.4956 - accuracy: 0.7557
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7555 - val_loss: 0.5404 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 795us/step
Independent Testing Matthews Correlation:  0.4511261946938569
Confusion Matrix :
 [[2848 1199]
 [1024 3023]]
Accuracy on test set:    0.7253521126760564
Sensitivity:    0.7469730664689894 	 Specificity:    0.7037311588831233
Precision  : 0.7160113690194221
Area Under Curve:    0.7253521126760565
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5896 - accuracy: 0.6829 - val_loss: 0.5488 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7209 - val_loss: 0.5444 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7310 - val_loss: 0.5424 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5204 - accuracy: 0.7397 - val_loss: 0.5470 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7481 - val_loss: 0.5425 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7545 - val_loss: 0.5438 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4897 - accuracy: 0.7609 - val_loss: 0.5459 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4767 - accuracy: 0.7730 - val_loss: 0.5490 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4645 - accuracy: 0.7803 - val_loss: 0.5569 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4521 - accuracy: 0.7873
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4521 - accuracy: 0.7873 - val_loss: 0.5571 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 840us/step
Independent Testing Matthews Correlation:  0.46145387314659947
Confusion Matrix :
 [[2910 1137]
 [1043 3004]]
Accuracy on test set:    0.7306646898937484
Sensitivity:    0.7422782307882382 	 Specificity:    0.7190511489992587
Precision  : 0.7254286404250181
Area Under Curve:    0.7306646898937483
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5927 - accuracy: 0.6804 - val_loss: 0.5576 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5504 - accuracy: 0.7204 - val_loss: 0.5454 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5364 - accuracy: 0.7294 - val_loss: 0.5419 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5255 - accuracy: 0.7369 - val_loss: 0.5420 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7463 - val_loss: 0.5475 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7503 - val_loss: 0.5465 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7606 - val_loss: 0.5438 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4825 - accuracy: 0.7682 - val_loss: 0.5474 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4713 - accuracy: 0.7765
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4714 - accuracy: 0.7763 - val_loss: 0.5481 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 977us/step
Independent Testing Matthews Correlation:  0.4863137171907408
Confusion Matrix :
 [[3075  972]
 [1108 2939]]
Accuracy on test set:    0.7430195206325674
Sensitivity:    0.7262169508277737 	 Specificity:    0.759822090437361
Precision  : 0.7514702122219381
Area Under Curve:    0.7430195206325675
(8094, 2560) (8094,)
Mean MCC = 0.4312 + 0.0275 and Mean AUC = 0.7150 + 0.0143
Mean Sensitivity = 0.7379 + 0.0268 and Mean Specificity = 0.6920 + 0.0435 and Mean Accuracy = 0.7150 + 0.0143
Mean Precision = 0.7069 + 0.0241





Seed   : 680110
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5879 - accuracy: 0.6844 - val_loss: 0.5556 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7255 - val_loss: 0.5461 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7371 - val_loss: 0.5435 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7432 - val_loss: 0.5482 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7510 - val_loss: 0.5462 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7607 - val_loss: 0.5478 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4827 - accuracy: 0.7672 - val_loss: 0.5549 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7751 - val_loss: 0.5512 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4595 - accuracy: 0.7842 - val_loss: 0.5609 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4464 - accuracy: 0.7927 - val_loss: 0.5592 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4348 - accuracy: 0.8005 - val_loss: 0.5634 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4231 - accuracy: 0.8073
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4237 - accuracy: 0.8068 - val_loss: 0.5733 - val_accuracy: 0.7137 - lr: 0.0010
253/253 [==============================] - 0s 824us/step
Independent Testing Matthews Correlation:  0.4199539872661147
Confusion Matrix :
 [[2910 1138]
 [1210 2837]]
Accuracy on test set:    0.7099444101297097
Sensitivity:    0.7010130961205832 	 Specificity:    0.7188735177865613
Precision  : 0.7137106918238993
Area Under Curve:    0.7099433069535722
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5874 - accuracy: 0.6838 - val_loss: 0.5566 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5432 - accuracy: 0.7239 - val_loss: 0.5484 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7349 - val_loss: 0.5412 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7425 - val_loss: 0.5401 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7497 - val_loss: 0.5429 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7567 - val_loss: 0.5421 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4861 - accuracy: 0.7635 - val_loss: 0.5467 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4740 - accuracy: 0.7713 - val_loss: 0.5479 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4623 - accuracy: 0.7806 - val_loss: 0.5529 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4501 - accuracy: 0.7891 - val_loss: 0.5603 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 11/400
250/257 [============================>.] - ETA: 0s - loss: 0.4363 - accuracy: 0.7975
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4367 - accuracy: 0.7969 - val_loss: 0.5630 - val_accuracy: 0.7109 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40747886092931485
Confusion Matrix :
 [[2787 1261]
 [1138 2909]]
Accuracy on test set:    0.7036442248301421
Sensitivity:    0.7188040523844823 	 Specificity:    0.6884881422924901
Precision  : 0.6976019184652278
Area Under Curve:    0.7036460973384862
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5841 - accuracy: 0.6885 - val_loss: 0.5410 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5423 - accuracy: 0.7243 - val_loss: 0.5367 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5259 - accuracy: 0.7345 - val_loss: 0.5308 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5137 - accuracy: 0.7435 - val_loss: 0.5340 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7519 - val_loss: 0.5345 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4908 - accuracy: 0.7609 - val_loss: 0.5362 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.7697 - val_loss: 0.5456 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4649 - accuracy: 0.7789 - val_loss: 0.5398 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4517 - accuracy: 0.7857 - val_loss: 0.5476 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4391 - accuracy: 0.7936 - val_loss: 0.5498 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4251 - accuracy: 0.8051
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4252 - accuracy: 0.8048 - val_loss: 0.5485 - val_accuracy: 0.7263 - lr: 0.0010
253/253 [==============================] - 0s 702us/step
Independent Testing Matthews Correlation:  0.4117471506780555
Confusion Matrix :
 [[2841 1206]
 [1175 2873]]
Accuracy on test set:    0.7058678196417542
Sensitivity:    0.7097332015810277 	 Specificity:    0.7020014825796886
Precision  : 0.7043392988477568
Area Under Curve:    0.7058673420803582
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5898 - accuracy: 0.6828 - val_loss: 0.5409 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7228 - val_loss: 0.5327 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7320 - val_loss: 0.5279 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7416 - val_loss: 0.5307 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7478 - val_loss: 0.5296 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7569 - val_loss: 0.5316 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7641 - val_loss: 0.5317 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4729 - accuracy: 0.7734 - val_loss: 0.5515 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4589 - accuracy: 0.7842 - val_loss: 0.5412 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4457 - accuracy: 0.7907
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4455 - accuracy: 0.7907 - val_loss: 0.5490 - val_accuracy: 0.7270 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42165003881300533
Confusion Matrix :
 [[2901 1146]
 [1195 2853]]
Accuracy on test set:    0.7108091414453366
Sensitivity:    0.704792490118577 	 Specificity:    0.7168272794662713
Precision  : 0.7134283570892723
Area Under Curve:    0.7108098847924242
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5849 - accuracy: 0.6864 - val_loss: 0.5438 - val_accuracy: 0.7263 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7219 - val_loss: 0.5393 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7318 - val_loss: 0.5341 - val_accuracy: 0.7345 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7399 - val_loss: 0.5349 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7485 - val_loss: 0.5329 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7561 - val_loss: 0.5361 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7623 - val_loss: 0.5354 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4753 - accuracy: 0.7693
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7691 - val_loss: 0.5394 - val_accuracy: 0.7299 - lr: 0.0010
253/253 [==============================] - 0s 814us/step
Independent Testing Matthews Correlation:  0.4313348969800095
Confusion Matrix :
 [[3041 1006]
 [1300 2747]]
Accuracy on test set:    0.7150976031628367
Sensitivity:    0.6787744007907092 	 Specificity:    0.7514208055349642
Precision  : 0.7319477751132427
Area Under Curve:    0.7150976031628367
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5882 - accuracy: 0.6848 - val_loss: 0.5518 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7214 - val_loss: 0.5386 - val_accuracy: 0.7333 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7312 - val_loss: 0.5360 - val_accuracy: 0.7348 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7396 - val_loss: 0.5340 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7476 - val_loss: 0.5344 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4985 - accuracy: 0.7552 - val_loss: 0.5381 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4883 - accuracy: 0.7626 - val_loss: 0.5378 - val_accuracy: 0.7315 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4761 - accuracy: 0.7710
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7710 - val_loss: 0.5404 - val_accuracy: 0.7289 - lr: 0.0010
253/253 [==============================] - 0s 869us/step
Independent Testing Matthews Correlation:  0.43126947318149667
Confusion Matrix :
 [[2816 1231]
 [1072 2975]]
Accuracy on test set:    0.7154682480850012
Sensitivity:    0.7351124289597233 	 Specificity:    0.6958240672102792
Precision  : 0.707322872087494
Area Under Curve:    0.7154682480850013
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5851 - accuracy: 0.6872 - val_loss: 0.5470 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7222 - val_loss: 0.5376 - val_accuracy: 0.7330 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7313 - val_loss: 0.5347 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7403 - val_loss: 0.5339 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7484 - val_loss: 0.5373 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7588 - val_loss: 0.5373 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4819 - accuracy: 0.7678
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7671 - val_loss: 0.5348 - val_accuracy: 0.7293 - lr: 0.0010
253/253 [==============================] - 0s 710us/step
Independent Testing Matthews Correlation:  0.4319492655373556
Confusion Matrix :
 [[2876 1171]
 [1128 2919]]
Accuracy on test set:    0.715962441314554
Sensitivity:    0.7212750185322461 	 Specificity:    0.7106498640968619
Precision  : 0.7136919315403423
Area Under Curve:    0.715962441314554
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5872 - accuracy: 0.6859 - val_loss: 0.5421 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7218 - val_loss: 0.5348 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7331 - val_loss: 0.5305 - val_accuracy: 0.7340 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7407 - val_loss: 0.5325 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7477 - val_loss: 0.5301 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7575 - val_loss: 0.5359 - val_accuracy: 0.7327 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7654 - val_loss: 0.5370 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4711 - accuracy: 0.7754
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4714 - accuracy: 0.7755 - val_loss: 0.5355 - val_accuracy: 0.7304 - lr: 0.0010
253/253 [==============================] - 0s 813us/step
Independent Testing Matthews Correlation:  0.4440111451519669
Confusion Matrix :
 [[2857 1190]
 [1061 2986]]
Accuracy on test set:    0.721892760069187
Sensitivity:    0.7378304917222634 	 Specificity:    0.7059550284161107
Precision  : 0.7150383141762452
Area Under Curve:    0.7218927600691871
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5891 - accuracy: 0.6829 - val_loss: 0.5483 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5493 - accuracy: 0.7202 - val_loss: 0.5394 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5324 - accuracy: 0.7320 - val_loss: 0.5396 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5224 - accuracy: 0.7395 - val_loss: 0.5345 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.7469 - val_loss: 0.5385 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7541 - val_loss: 0.5397 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4882 - accuracy: 0.7640
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.7636 - val_loss: 0.5379 - val_accuracy: 0.7292 - lr: 0.0010
253/253 [==============================] - 0s 776us/step
Independent Testing Matthews Correlation:  0.45595389176038
Confusion Matrix :
 [[2979 1068]
 [1134 2913]]
Accuracy on test set:    0.7279466271312083
Sensitivity:    0.7197924388435878 	 Specificity:    0.7361008154188288
Precision  : 0.73172569706104
Area Under Curve:    0.7279466271312083
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5926 - accuracy: 0.6814 - val_loss: 0.5473 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5504 - accuracy: 0.7189 - val_loss: 0.5489 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5346 - accuracy: 0.7308 - val_loss: 0.5389 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5236 - accuracy: 0.7372 - val_loss: 0.5363 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5129 - accuracy: 0.7467 - val_loss: 0.5384 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7544 - val_loss: 0.5417 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7618 - val_loss: 0.5380 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7690 - val_loss: 0.5473 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7778 - val_loss: 0.5485 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4552 - accuracy: 0.7867
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4552 - accuracy: 0.7867 - val_loss: 0.5551 - val_accuracy: 0.7226 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.48160635795462164
Confusion Matrix :
 [[3014 1033]
 [1065 2982]]
Accuracy on test set:    0.7407956510995799
Sensitivity:    0.7368421052631579 	 Specificity:    0.744749196936002
Precision  : 0.7427148194271482
Area Under Curve:    0.74079565109958
(8094, 2560) (8094,)
Mean MCC = 0.4337 + 0.0210 and Mean AUC = 0.7167 + 0.0105
Mean Sensitivity = 0.7164 + 0.0176 and Mean Specificity = 0.7171 + 0.0199 and Mean Accuracy = 0.7167 + 0.0105
Mean Precision = 0.7172 + 0.0133





Seed   : 632883
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5878 - accuracy: 0.6834 - val_loss: 0.5576 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7253 - val_loss: 0.5484 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.7355 - val_loss: 0.5505 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7421 - val_loss: 0.5522 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7506 - val_loss: 0.5527 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7616 - val_loss: 0.5519 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4794 - accuracy: 0.7687 - val_loss: 0.5556 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4657 - accuracy: 0.7775 - val_loss: 0.5539 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4534 - accuracy: 0.7864 - val_loss: 0.5592 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4409 - accuracy: 0.7930 - val_loss: 0.5757 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 11/400
254/257 [============================>.] - ETA: 0s - loss: 0.4275 - accuracy: 0.8032
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4275 - accuracy: 0.8032 - val_loss: 0.5721 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 735us/step
Independent Testing Matthews Correlation:  0.3953607715936914
Confusion Matrix :
 [[2730 1318]
 [1131 2916]]
Accuracy on test set:    0.6974675725756639
Sensitivity:    0.720533728687917 	 Specificity:    0.674407114624506
Precision  : 0.6887104393008975
Area Under Curve:    0.6974704216562114
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5893 - accuracy: 0.6832 - val_loss: 0.5599 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7248 - val_loss: 0.5511 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7347 - val_loss: 0.5467 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7420 - val_loss: 0.5492 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7512 - val_loss: 0.5509 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4918 - accuracy: 0.7586 - val_loss: 0.5501 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7665 - val_loss: 0.5537 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4694 - accuracy: 0.7758 - val_loss: 0.5650 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4547 - accuracy: 0.7857
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4549 - accuracy: 0.7855 - val_loss: 0.5626 - val_accuracy: 0.7102 - lr: 0.0010
253/253 [==============================] - 0s 964us/step
Independent Testing Matthews Correlation:  0.4160273336963681
Confusion Matrix :
 [[2758 1290]
 [1076 2971]]
Accuracy on test set:    0.7077208153180976
Sensitivity:    0.7341240425006177 	 Specificity:    0.6813241106719368
Precision  : 0.6972541656888055
Area Under Curve:    0.7077240765862772
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5840 - accuracy: 0.6875 - val_loss: 0.5469 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7238 - val_loss: 0.5380 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7324 - val_loss: 0.5403 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7428 - val_loss: 0.5369 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7499 - val_loss: 0.5433 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7599 - val_loss: 0.5391 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
252/257 [============================>.] - ETA: 0s - loss: 0.4818 - accuracy: 0.7652
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7649 - val_loss: 0.5448 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 725us/step
Independent Testing Matthews Correlation:  0.4402044175794847
Confusion Matrix :
 [[2671 1376]
 [ 902 3146]]
Accuracy on test set:    0.718591723285979
Sensitivity:    0.7771739130434783 	 Specificity:    0.6599950580677044
Precision  : 0.6957098628925255
Area Under Curve:    0.7185844855555914
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5883 - accuracy: 0.6830 - val_loss: 0.5437 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7235 - val_loss: 0.5392 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7327 - val_loss: 0.5369 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7428 - val_loss: 0.5368 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7493 - val_loss: 0.5375 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7582 - val_loss: 0.5372 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4829 - accuracy: 0.7666
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.7668 - val_loss: 0.5411 - val_accuracy: 0.7245 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41075699081056566
Confusion Matrix :
 [[2868 1179]
 [1206 2842]]
Accuracy on test set:    0.705373687461396
Sensitivity:    0.7020750988142292 	 Specificity:    0.7086730911786508
Precision  : 0.7067893558816215
Area Under Curve:    0.70537409499644
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5878 - accuracy: 0.6816 - val_loss: 0.5503 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7237 - val_loss: 0.5395 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7317 - val_loss: 0.5359 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7415 - val_loss: 0.5383 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.7476 - val_loss: 0.5411 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7564 - val_loss: 0.5441 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4846 - accuracy: 0.7660
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7659 - val_loss: 0.5445 - val_accuracy: 0.7229 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42253483422438465
Confusion Matrix :
 [[2655 1392]
 [ 955 3092]]
Accuracy on test set:    0.7100321225599209
Sensitivity:    0.7640227328885594 	 Specificity:    0.6560415122312825
Precision  : 0.6895628902765388
Area Under Curve:    0.7100321225599209
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5884 - accuracy: 0.6830 - val_loss: 0.5507 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7232 - val_loss: 0.5479 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7310 - val_loss: 0.5426 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7407 - val_loss: 0.5391 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7508 - val_loss: 0.5403 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7600 - val_loss: 0.5493 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7692 - val_loss: 0.5438 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4669 - accuracy: 0.7777 - val_loss: 0.5506 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4539 - accuracy: 0.7846 - val_loss: 0.5530 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4408 - accuracy: 0.7927 - val_loss: 0.5609 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4285 - accuracy: 0.8010 - val_loss: 0.5631 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4151 - accuracy: 0.8099 - val_loss: 0.5687 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 13/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4012 - accuracy: 0.8172
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4019 - accuracy: 0.8171 - val_loss: 0.5796 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 922us/step
Independent Testing Matthews Correlation:  0.43260966492612657
Confusion Matrix :
 [[2807 1240]
 [1058 2989]]
Accuracy on test set:    0.7160859896219421
Sensitivity:    0.7385717815665925 	 Specificity:    0.6936001976772919
Precision  : 0.7067864743438165
Area Under Curve:    0.7160859896219423
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5864 - accuracy: 0.6865 - val_loss: 0.5534 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7219 - val_loss: 0.5425 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7351 - val_loss: 0.5387 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7425 - val_loss: 0.5387 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7488 - val_loss: 0.5408 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7584 - val_loss: 0.5384 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7658 - val_loss: 0.5436 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7735 - val_loss: 0.5470 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4576 - accuracy: 0.7835 - val_loss: 0.5508 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4453 - accuracy: 0.7921 - val_loss: 0.5542 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4320 - accuracy: 0.7995 - val_loss: 0.5563 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4198 - accuracy: 0.8076 - val_loss: 0.5641 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4087 - accuracy: 0.8129 - val_loss: 0.5751 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3953 - accuracy: 0.8212 - val_loss: 0.5780 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3830 - accuracy: 0.8276 - val_loss: 0.6023 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 16/400

257/257 [==============================] - ETA: 0s - loss: 0.3713 - accuracy: 0.8352
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3713 - accuracy: 0.8352 - val_loss: 0.6085 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 982us/step
Independent Testing Matthews Correlation:  0.4263744274281613
Confusion Matrix :
 [[3014 1033]
 [1292 2755]]
Accuracy on test set:    0.712750185322461
Sensitivity:    0.6807511737089202 	 Specificity:    0.744749196936002
Precision  : 0.7272967265047519
Area Under Curve:    0.7127501853224611
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5869 - accuracy: 0.6857 - val_loss: 0.5506 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7226 - val_loss: 0.5417 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7334 - val_loss: 0.5426 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7417 - val_loss: 0.5397 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7495 - val_loss: 0.5392 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7594 - val_loss: 0.5388 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4825 - accuracy: 0.7678 - val_loss: 0.5424 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.7742 - val_loss: 0.5468 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4568 - accuracy: 0.7835 - val_loss: 0.5576 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7936 - val_loss: 0.5561 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4288 - accuracy: 0.8015 - val_loss: 0.5656 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4144 - accuracy: 0.8116
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4148 - accuracy: 0.8113 - val_loss: 0.5733 - val_accuracy: 0.7152 - lr: 0.0010
253/253 [==============================] - 0s 786us/step
Independent Testing Matthews Correlation:  0.4225377438795084
Confusion Matrix :
 [[3015 1032]
 [1309 2738]]
Accuracy on test set:    0.7107734124042501
Sensitivity:    0.6765505312577218 	 Specificity:    0.7449962935507783
Precision  : 0.7262599469496022
Area Under Curve:    0.7107734124042501
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5886 - accuracy: 0.6834 - val_loss: 0.5495 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7204 - val_loss: 0.5484 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7328 - val_loss: 0.5414 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7410 - val_loss: 0.5391 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7489 - val_loss: 0.5419 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7549 - val_loss: 0.5439 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.7645 - val_loss: 0.5458 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4758 - accuracy: 0.7707 - val_loss: 0.5504 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4641 - accuracy: 0.7805 - val_loss: 0.5481 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4531 - accuracy: 0.7874 - val_loss: 0.5599 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4385 - accuracy: 0.7975 - val_loss: 0.5750 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4253 - accuracy: 0.8050 - val_loss: 0.5706 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4145 - accuracy: 0.8106 - val_loss: 0.5734 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4025 - accuracy: 0.8169 - val_loss: 0.5906 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 15/400
248/257 [===========================>..] - ETA: 0s - loss: 0.3938 - accuracy: 0.8217
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3944 - accuracy: 0.8216 - val_loss: 0.5915 - val_accuracy: 0.7150 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4505451655551867
Confusion Matrix :
 [[2975 1072]
 [1152 2895]]
Accuracy on test set:    0.7252285643686681
Sensitivity:    0.7153446997776131 	 Specificity:    0.7351124289597233
Precision  : 0.7297706075119738
Area Under Curve:    0.7252285643686682
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5918 - accuracy: 0.6819 - val_loss: 0.5564 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5502 - accuracy: 0.7190 - val_loss: 0.5482 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7319 - val_loss: 0.5439 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7393 - val_loss: 0.5447 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7484 - val_loss: 0.5435 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7561 - val_loss: 0.5432 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4887 - accuracy: 0.7628 - val_loss: 0.5528 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7711 - val_loss: 0.5509 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4671 - accuracy: 0.7771 - val_loss: 0.5610 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4537 - accuracy: 0.7872 - val_loss: 0.5590 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4421 - accuracy: 0.7947 - val_loss: 0.5603 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4272 - accuracy: 0.8048 - val_loss: 0.5633 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4154 - accuracy: 0.8101 - val_loss: 0.5652 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4043 - accuracy: 0.8167 - val_loss: 0.5867 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3914 - accuracy: 0.8231 - val_loss: 0.5877 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 16/400
249/257 [============================>.] - ETA: 0s - loss: 0.3800 - accuracy: 0.8298
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3804 - accuracy: 0.8294 - val_loss: 0.6029 - val_accuracy: 0.7111 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4776742142901545
Confusion Matrix :
 [[2965 1082]
 [1032 3015]]
Accuracy on test set:    0.7388188781813689
Sensitivity:    0.7449962935507783 	 Specificity:    0.7326414628119595
Precision  : 0.7359043202343178
Area Under Curve:    0.7388188781813689
(8094, 2560) (8094,)
Mean MCC = 0.4295 + 0.0217 and Mean AUC = 0.7143 + 0.0109
Mean Sensitivity = 0.7254 + 0.0314 and Mean Specificity = 0.7032 + 0.0330 and Mean Accuracy = 0.7143 + 0.0109
Mean Precision = 0.7104 + 0.0170





Seed   : 614011
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5874 - accuracy: 0.6863 - val_loss: 0.5543 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7249 - val_loss: 0.5490 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.7367 - val_loss: 0.5430 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5154 - accuracy: 0.7429 - val_loss: 0.5466 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5038 - accuracy: 0.7516 - val_loss: 0.5428 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.7586 - val_loss: 0.5502 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.7667 - val_loss: 0.5497 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4688 - accuracy: 0.7747 - val_loss: 0.5558 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4578 - accuracy: 0.7829 - val_loss: 0.5586 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4435 - accuracy: 0.7946
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4441 - accuracy: 0.7943 - val_loss: 0.5607 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 883us/step
Independent Testing Matthews Correlation:  0.41658571862821475
Confusion Matrix :
 [[2812 1236]
 [1126 2921]]
Accuracy on test set:    0.7082149474984558
Sensitivity:    0.7217692117617989 	 Specificity:    0.6946640316205533
Precision  : 0.7026701948520567
Area Under Curve:    0.708216621691176
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5904 - accuracy: 0.6815 - val_loss: 0.5554 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7233 - val_loss: 0.5533 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7351 - val_loss: 0.5502 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5138 - accuracy: 0.7431 - val_loss: 0.5447 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.7531 - val_loss: 0.5475 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4887 - accuracy: 0.7615 - val_loss: 0.5549 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4764 - accuracy: 0.7701 - val_loss: 0.5544 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4640 - accuracy: 0.7782 - val_loss: 0.5573 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4520 - accuracy: 0.7859 - val_loss: 0.5547 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4388 - accuracy: 0.7968 - val_loss: 0.5654 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4249 - accuracy: 0.8049 - val_loss: 0.5687 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4134 - accuracy: 0.8115 - val_loss: 0.5822 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 13/400
252/257 [============================>.] - ETA: 0s - loss: 0.3988 - accuracy: 0.8197
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3986 - accuracy: 0.8199 - val_loss: 0.5785 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 918us/step
Independent Testing Matthews Correlation:  0.4106189164280297
Confusion Matrix :
 [[2904 1144]
 [1242 2805]]
Accuracy on test set:    0.7052501544163063
Sensitivity:    0.6931060044477391 	 Specificity:    0.717391304347826
Precision  : 0.7103064066852368
Area Under Curve:    0.7052486543977826
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5896 - accuracy: 0.6837 - val_loss: 0.5481 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7205 - val_loss: 0.5420 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7309 - val_loss: 0.5385 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7420 - val_loss: 0.5367 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7501 - val_loss: 0.5357 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7576 - val_loss: 0.5423 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4831 - accuracy: 0.7660 - val_loss: 0.5452 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7747 - val_loss: 0.5461 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4578 - accuracy: 0.7816 - val_loss: 0.5459 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4436 - accuracy: 0.7896
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4438 - accuracy: 0.7895 - val_loss: 0.5507 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4115036938456523
Confusion Matrix :
 [[2873 1174]
 [1208 2840]]
Accuracy on test set:    0.7057442865966647
Sensitivity:    0.7015810276679841 	 Specificity:    0.7099085742525327
Precision  : 0.7075236671649228
Area Under Curve:    0.7057448009602585
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5854 - accuracy: 0.6863 - val_loss: 0.5430 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5420 - accuracy: 0.7240 - val_loss: 0.5336 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 3/400

257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7338 - val_loss: 0.5359 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7428 - val_loss: 0.5312 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7517 - val_loss: 0.5281 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.7604 - val_loss: 0.5364 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4783 - accuracy: 0.7705
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7704 - val_loss: 0.5353 - val_accuracy: 0.7253 - lr: 0.0010
253/253 [==============================] - 0s 734us/step
Independent Testing Matthews Correlation:  0.4225025189839023
Confusion Matrix :
 [[2825 1222]
 [1116 2932]]
Accuracy on test set:    0.7111797405806053
Sensitivity:    0.724308300395257 	 Specificity:    0.6980479367432666
Precision  : 0.705825710158883
Area Under Curve:    0.7111781185692618
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5870 - accuracy: 0.6847 - val_loss: 0.5549 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7223 - val_loss: 0.5452 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7311 - val_loss: 0.5458 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7405 - val_loss: 0.5430 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7470 - val_loss: 0.5481 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5024 - accuracy: 0.7520 - val_loss: 0.5448 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4924 - accuracy: 0.7591
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7593 - val_loss: 0.5527 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 946us/step
Independent Testing Matthews Correlation:  0.4332550487168595
Confusion Matrix :
 [[2711 1336]
 [ 965 3082]]
Accuracy on test set:    0.7157153446997776
Sensitivity:    0.7615517667407956 	 Specificity:    0.6698789226587596
Precision  : 0.6976007243096424
Area Under Curve:    0.7157153446997776
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5901 - accuracy: 0.6828 - val_loss: 0.5536 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7230 - val_loss: 0.5491 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7326 - val_loss: 0.5470 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5204 - accuracy: 0.7396 - val_loss: 0.5455 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7469 - val_loss: 0.5456 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4970 - accuracy: 0.7572 - val_loss: 0.5458 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.7639 - val_loss: 0.5521 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4728 - accuracy: 0.7735
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4729 - accuracy: 0.7733 - val_loss: 0.5508 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 723us/step
Independent Testing Matthews Correlation:  0.42188080218359525
Confusion Matrix :
 [[2796 1251]
 [1090 2957]]
Accuracy on test set:    0.7107734124042501
Sensitivity:    0.7306646898937484 	 Specificity:    0.6908821349147517
Precision  : 0.7027091254752852
Area Under Curve:    0.71077341240425
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5869 - accuracy: 0.6858 - val_loss: 0.5505 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7222 - val_loss: 0.5440 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7321 - val_loss: 0.5449 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7393 - val_loss: 0.5466 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7482 - val_loss: 0.5436 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7574 - val_loss: 0.5421 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4840 - accuracy: 0.7651
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7647 - val_loss: 0.5458 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 939us/step
Independent Testing Matthews Correlation:  0.4257338458950684
Confusion Matrix :
 [[3063  984]
 [1347 2700]]
Accuracy on test set:    0.712008895478132
Sensitivity:    0.6671608598962194 	 Specificity:    0.7568569310600445
Precision  : 0.7328990228013029
Area Under Curve:    0.7120088954781321
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5881 - accuracy: 0.6834 - val_loss: 0.5493 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7208 - val_loss: 0.5424 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7323 - val_loss: 0.5390 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5210 - accuracy: 0.7387 - val_loss: 0.5426 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5119 - accuracy: 0.7448 - val_loss: 0.5385 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7542 - val_loss: 0.5422 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.7623 - val_loss: 0.5422 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4768 - accuracy: 0.7717
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4765 - accuracy: 0.7717 - val_loss: 0.5465 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4359644948965484
Confusion Matrix :
 [[3074  973]
 [1316 2731]]
Accuracy on test set:    0.7171979243884359
Sensitivity:    0.6748208549542871 	 Specificity:    0.7595749938225846
Precision  : 0.7373110151187905
Area Under Curve:    0.7171979243884359
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5904 - accuracy: 0.6820 - val_loss: 0.5543 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7204 - val_loss: 0.5473 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7321 - val_loss: 0.5436 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7401 - val_loss: 0.5440 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7490 - val_loss: 0.5463 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7578 - val_loss: 0.5444 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.7661 - val_loss: 0.5531 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.7739 - val_loss: 0.5670 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4626 - accuracy: 0.7818
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4627 - accuracy: 0.7820 - val_loss: 0.5559 - val_accuracy: 0.7175 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.45136216074415053
Confusion Matrix :
 [[2991 1056]
 [1165 2882]]
Accuracy on test set:    0.7255992092908328
Sensitivity:    0.7121324437855201 	 Specificity:    0.7390659747961453
Precision  : 0.7318435754189944
Area Under Curve:    0.7255992092908327
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5979 - accuracy: 0.6736 - val_loss: 0.5553 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5504 - accuracy: 0.7185 - val_loss: 0.5466 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5346 - accuracy: 0.7296 - val_loss: 0.5442 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5230 - accuracy: 0.7400 - val_loss: 0.5448 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5115 - accuracy: 0.7459 - val_loss: 0.5491 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5015 - accuracy: 0.7525 - val_loss: 0.5479 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4884 - accuracy: 0.7630
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.7625 - val_loss: 0.5497 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 743us/step
Independent Testing Matthews Correlation:  0.4738434796676406
Confusion Matrix :
 [[3159  888]
 [1249 2798]]
Accuracy on test set:    0.7359772671114406
Sensitivity:    0.6913763281443044 	 Specificity:    0.7805782060785768
Precision  : 0.7590884427563754
Area Under Curve:    0.7359772671114406
(8094, 2560) (8094,)
Mean MCC = 0.4303 + 0.0186 and Mean AUC = 0.7148 + 0.0091
Mean Sensitivity = 0.7078 + 0.0268 and Mean Specificity = 0.7217 + 0.0339 and Mean Accuracy = 0.7148 + 0.0091
Mean Precision = 0.7188 + 0.0192





Seed   : 648699
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5852 - accuracy: 0.6860 - val_loss: 0.5608 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7250 - val_loss: 0.5479 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5252 - accuracy: 0.7363 - val_loss: 0.5479 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5126 - accuracy: 0.7453 - val_loss: 0.5561 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7536 - val_loss: 0.5447 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7601 - val_loss: 0.5515 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4802 - accuracy: 0.7678 - val_loss: 0.5533 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.7764 - val_loss: 0.5538 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4560 - accuracy: 0.7842 - val_loss: 0.5538 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4433 - accuracy: 0.7920 - val_loss: 0.5601 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - ETA: 0s - loss: 0.4291 - accuracy: 0.8009
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4291 - accuracy: 0.8009 - val_loss: 0.5701 - val_accuracy: 0.7130 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4065947937165704
Confusion Matrix :
 [[2701 1347]
 [1059 2988]]
Accuracy on test set:    0.7027794935145152
Sensitivity:    0.7383246849518161 	 Specificity:    0.6672430830039525
Precision  : 0.6892733564013841
Area Under Curve:    0.7027838839778844
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5903 - accuracy: 0.6808 - val_loss: 0.5556 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7237 - val_loss: 0.5478 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7343 - val_loss: 0.5453 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7434 - val_loss: 0.5529 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7488 - val_loss: 0.5452 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7601 - val_loss: 0.5491 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7684 - val_loss: 0.5413 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4677 - accuracy: 0.7783 - val_loss: 0.5450 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4528 - accuracy: 0.7872 - val_loss: 0.5549 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4384 - accuracy: 0.7961 - val_loss: 0.5670 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4271 - accuracy: 0.8048 - val_loss: 0.5670 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4143 - accuracy: 0.8108 - val_loss: 0.5669 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4013 - accuracy: 0.8185 - val_loss: 0.5753 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3887 - accuracy: 0.8257 - val_loss: 0.5912 - val_accuracy: 0.7100 - lr: 0.0010

Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3786 - accuracy: 0.8313 - val_loss: 0.5904 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3659 - accuracy: 0.8386 - val_loss: 0.5988 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 17/400
248/257 [===========================>..] - ETA: 0s - loss: 0.3538 - accuracy: 0.8454
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3538 - accuracy: 0.8455 - val_loss: 0.6164 - val_accuracy: 0.7132 - lr: 0.0010
253/253 [==============================] - 0s 767us/step
Independent Testing Matthews Correlation:  0.4106951566742334
Confusion Matrix :
 [[2761 1287]
 [1100 2947]]
Accuracy on test set:    0.7051266213712168
Sensitivity:    0.7281937237459847 	 Specificity:    0.6820652173913043
Precision  : 0.6960321209258384
Area Under Curve:    0.7051294705686445
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5909 - accuracy: 0.6799 - val_loss: 0.5517 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7194 - val_loss: 0.5403 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7334 - val_loss: 0.5350 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7418 - val_loss: 0.5326 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7497 - val_loss: 0.5339 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7604 - val_loss: 0.5353 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4819 - accuracy: 0.7653 - val_loss: 0.5488 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4699 - accuracy: 0.7761 - val_loss: 0.5441 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4559 - accuracy: 0.7854
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4559 - accuracy: 0.7855 - val_loss: 0.5464 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 731us/step
Independent Testing Matthews Correlation:  0.40700890624932906
Confusion Matrix :
 [[2942 1105]
 [1297 2751]]
Accuracy on test set:    0.7032736256948734
Sensitivity:    0.6795948616600791 	 Specificity:    0.7269582406721028
Precision  : 0.7134336099585062
Area Under Curve:    0.7032765511660909
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5883 - accuracy: 0.6850 - val_loss: 0.5459 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7225 - val_loss: 0.5350 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7329 - val_loss: 0.5324 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7408 - val_loss: 0.5323 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7488 - val_loss: 0.5328 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7580 - val_loss: 0.5360 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7682 - val_loss: 0.5392 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4672 - accuracy: 0.7760 - val_loss: 0.5457 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4545 - accuracy: 0.7849 - val_loss: 0.5481 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4403 - accuracy: 0.7928 - val_loss: 0.5551 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 11/400
252/257 [============================>.] - ETA: 0s - loss: 0.4281 - accuracy: 0.8011
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4283 - accuracy: 0.8010 - val_loss: 0.5674 - val_accuracy: 0.7220 - lr: 0.0010
253/253 [==============================] - 0s 735us/step
Independent Testing Matthews Correlation:  0.40755953960149116
Confusion Matrix :
 [[2597 1450]
 [ 960 3088]]
Accuracy on test set:    0.7022853613341569
Sensitivity:    0.7628458498023716 	 Specificity:    0.6417099085742526
Precision  : 0.6804759806081975
Area Under Curve:    0.7022778791883121
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5874 - accuracy: 0.6831 - val_loss: 0.5483 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7217 - val_loss: 0.5413 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7333 - val_loss: 0.5356 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7418 - val_loss: 0.5428 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7488 - val_loss: 0.5370 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7569 - val_loss: 0.5427 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.7638 - val_loss: 0.5404 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4737 - accuracy: 0.7721
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7717 - val_loss: 0.5487 - val_accuracy: 0.7285 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42277320415916514
Confusion Matrix :
 [[2680 1367]
 [ 977 3070]]
Accuracy on test set:    0.7104027674820855
Sensitivity:    0.7585866073634792 	 Specificity:    0.6622189276006919
Precision  : 0.6919089474870408
Area Under Curve:    0.7104027674820855
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5865 - accuracy: 0.6851 - val_loss: 0.5514 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7231 - val_loss: 0.5399 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7338 - val_loss: 0.5393 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7448 - val_loss: 0.5427 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7527 - val_loss: 0.5395 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7589 - val_loss: 0.5421 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7686 - val_loss: 0.5410 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4666 - accuracy: 0.7770 - val_loss: 0.5494 - val_accuracy: 0.7292 - lr: 0.0010

Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4534 - accuracy: 0.7848 - val_loss: 0.5491 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4419 - accuracy: 0.7943 - val_loss: 0.5569 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4285 - accuracy: 0.8024 - val_loss: 0.5586 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4147 - accuracy: 0.8101 - val_loss: 0.5703 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 13/400
251/257 [============================>.] - ETA: 0s - loss: 0.4015 - accuracy: 0.8186
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4015 - accuracy: 0.8188 - val_loss: 0.5861 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 774us/step
Independent Testing Matthews Correlation:  0.3906651686099772
Confusion Matrix :
 [[2620 1427]
 [1046 3001]]
Accuracy on test set:    0.6944650358290091
Sensitivity:    0.7415369409439091 	 Specificity:    0.6473931307141092
Precision  : 0.6777326106594399
Area Under Curve:    0.6944650358290091
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5884 - accuracy: 0.6846 - val_loss: 0.5490 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7199 - val_loss: 0.5445 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7308 - val_loss: 0.5394 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7389 - val_loss: 0.5394 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7465 - val_loss: 0.5417 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5010 - accuracy: 0.7530 - val_loss: 0.5413 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4905 - accuracy: 0.7609 - val_loss: 0.5391 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4807 - accuracy: 0.7690
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4811 - accuracy: 0.7685 - val_loss: 0.5437 - val_accuracy: 0.7234 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4238345707548611
Confusion Matrix :
 [[2958 1089]
 [1244 2803]]
Accuracy on test set:    0.7117617988633556
Sensitivity:    0.6926118112181863 	 Specificity:    0.7309117865085248
Precision  : 0.7201952723535457
Area Under Curve:    0.7117617988633556
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5904 - accuracy: 0.6808 - val_loss: 0.5486 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5480 - accuracy: 0.7200 - val_loss: 0.5401 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7304 - val_loss: 0.5416 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5221 - accuracy: 0.7390 - val_loss: 0.5376 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5115 - accuracy: 0.7462 - val_loss: 0.5362 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5018 - accuracy: 0.7535 - val_loss: 0.5388 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.7638 - val_loss: 0.5362 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4765 - accuracy: 0.7719 - val_loss: 0.5405 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7791 - val_loss: 0.5461 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4526 - accuracy: 0.7887 - val_loss: 0.5507 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4392 - accuracy: 0.7948 - val_loss: 0.5544 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4259 - accuracy: 0.8036 - val_loss: 0.5646 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4128 - accuracy: 0.8105 - val_loss: 0.5686 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4002 - accuracy: 0.8170 - val_loss: 0.5834 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 15/400
256/257 [============================>.] - ETA: 0s - loss: 0.3910 - accuracy: 0.8236
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3910 - accuracy: 0.8236 - val_loss: 0.5742 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 951us/step
Independent Testing Matthews Correlation:  0.4256289594295206
Confusion Matrix :
 [[2799 1248]
 [1078 2969]]
Accuracy on test set:    0.7126266370150729
Sensitivity:    0.733629849271065 	 Specificity:    0.6916234247590808
Precision  : 0.7040550154138013
Area Under Curve:    0.7126266370150729
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5884 - accuracy: 0.6812 - val_loss: 0.5550 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5477 - accuracy: 0.7204 - val_loss: 0.5474 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5328 - accuracy: 0.7299 - val_loss: 0.5396 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7387 - val_loss: 0.5421 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7477 - val_loss: 0.5426 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4989 - accuracy: 0.7551 - val_loss: 0.5508 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4861 - accuracy: 0.7646 - val_loss: 0.5434 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4744 - accuracy: 0.7736 - val_loss: 0.5500 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4607 - accuracy: 0.7821 - val_loss: 0.5616 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4489 - accuracy: 0.7884 - val_loss: 0.5545 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4349 - accuracy: 0.7990 - val_loss: 0.5544 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4191 - accuracy: 0.8088 - val_loss: 0.5624 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 13/400
256/257 [============================>.] - ETA: 0s - loss: 0.4073 - accuracy: 0.8145
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4073 - accuracy: 0.8144 - val_loss: 0.5763 - val_accuracy: 0.7156 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4596583466005171
Confusion Matrix :
 [[3088  959]
 [1232 2815]]
Accuracy on test set:    0.7293056585124784
Sensitivity:    0.6955769705955028 	 Specificity:    0.7630343464294539
Precision  : 0.7458929517753047
Area Under Curve:    0.7293056585124784
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5924 - accuracy: 0.6811 - val_loss: 0.5532 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5507 - accuracy: 0.7190 - val_loss: 0.5492 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5352 - accuracy: 0.7296 - val_loss: 0.5445 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5233 - accuracy: 0.7378 - val_loss: 0.5428 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5117 - accuracy: 0.7469 - val_loss: 0.5458 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7547 - val_loss: 0.5449 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4899 - accuracy: 0.7620 - val_loss: 0.5494 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4760 - accuracy: 0.7710 - val_loss: 0.5539 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4633 - accuracy: 0.7787
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7786 - val_loss: 0.5542 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47185392914492424
Confusion Matrix :
 [[3143  904]
 [1240 2807]]
Accuracy on test set:    0.7351124289597233
Sensitivity:    0.6936001976772919 	 Specificity:    0.7766246602421547
Precision  : 0.7563998922123417
Area Under Curve:    0.7351124289597233
(8094, 2560) (8094,)
Mean MCC = 0.4226 + 0.0239 and Mean AUC = 0.7107 + 0.0120
Mean Sensitivity = 0.7225 + 0.0283 and Mean Specificity = 0.6990 + 0.0454 and Mean Accuracy = 0.7107 + 0.0120
Mean Precision = 0.7075 + 0.0253





Seed   : 797314
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5849 - accuracy: 0.6869 - val_loss: 0.5621 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5409 - accuracy: 0.7238 - val_loss: 0.5538 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5254 - accuracy: 0.7366 - val_loss: 0.5569 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5137 - accuracy: 0.7440 - val_loss: 0.5544 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7517 - val_loss: 0.5515 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.7595 - val_loss: 0.5516 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7660 - val_loss: 0.5667 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7748 - val_loss: 0.5584 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4588 - accuracy: 0.7827 - val_loss: 0.5613 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4471 - accuracy: 0.7910
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4470 - accuracy: 0.7910 - val_loss: 0.5729 - val_accuracy: 0.7105 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.404210946424861
Confusion Matrix :
 [[2576 1472]
 [ 953 3094]]
Accuracy on test set:    0.7004323656578134
Sensitivity:    0.7645169261181122 	 Specificity:    0.6363636363636364
Precision  : 0.6776171703898379
Area Under Curve:    0.7004402812408742
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5885 - accuracy: 0.6841 - val_loss: 0.5610 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7258 - val_loss: 0.5532 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7337 - val_loss: 0.5576 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7429 - val_loss: 0.5655 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7493 - val_loss: 0.5568 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7549 - val_loss: 0.5559 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7652 - val_loss: 0.5584 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7715 - val_loss: 0.5639 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4615 - accuracy: 0.7819 - val_loss: 0.5636 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4509 - accuracy: 0.7880 - val_loss: 0.5765 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - ETA: 0s - loss: 0.4386 - accuracy: 0.7953
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4386 - accuracy: 0.7953 - val_loss: 0.5820 - val_accuracy: 0.7105 - lr: 0.0010
253/253 [==============================] - 0s 952us/step
Independent Testing Matthews Correlation:  0.4210993693135281
Confusion Matrix :
 [[2721 1327]
 [1021 3026]]
Accuracy on test set:    0.7099444101297097
Sensitivity:    0.7477143563133185 	 Specificity:    0.6721837944664032
Precision  : 0.695152768205835
Area Under Curve:    0.7099490753898609
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5873 - accuracy: 0.6855 - val_loss: 0.5553 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7231 - val_loss: 0.5466 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7326 - val_loss: 0.5452 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7418 - val_loss: 0.5457 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7467 - val_loss: 0.5467 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5000 - accuracy: 0.7552 - val_loss: 0.5495 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.7619 - val_loss: 0.5483 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7677 - val_loss: 0.5456 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400

255/257 [============================>.] - ETA: 0s - loss: 0.4723 - accuracy: 0.7756
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7756 - val_loss: 0.5550 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 959us/step
Independent Testing Matthews Correlation:  0.4252926580836621
Confusion Matrix :
 [[2746 1301]
 [1029 3019]]
Accuracy on test set:    0.7121680049413218
Sensitivity:    0.745800395256917 	 Specificity:    0.6785273041759328
Precision  : 0.6988425925925926
Area Under Curve:    0.7121638497164249
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5980 - accuracy: 0.6733 - val_loss: 0.5592 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7216 - val_loss: 0.5499 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7320 - val_loss: 0.5451 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7404 - val_loss: 0.5469 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7488 - val_loss: 0.5509 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7594 - val_loss: 0.5491 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7683 - val_loss: 0.5530 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4664 - accuracy: 0.7763 - val_loss: 0.5562 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4541 - accuracy: 0.7863 - val_loss: 0.5634 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4395 - accuracy: 0.7944
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4394 - accuracy: 0.7946 - val_loss: 0.5682 - val_accuracy: 0.7109 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40037776995219604
Confusion Matrix :
 [[2821 1226]
 [1201 2847]]
Accuracy on test set:    0.7001852995676343
Sensitivity:    0.7033102766798419 	 Specificity:    0.6970595502841611
Precision  : 0.6989933709796219
Area Under Curve:    0.7001849134820015
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5929 - accuracy: 0.6791 - val_loss: 0.5541 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7208 - val_loss: 0.5398 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7316 - val_loss: 0.5411 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7402 - val_loss: 0.5375 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7481 - val_loss: 0.5381 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7562 - val_loss: 0.5417 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7640 - val_loss: 0.5439 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7738 - val_loss: 0.5523 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4587 - accuracy: 0.7813 - val_loss: 0.5523 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4461 - accuracy: 0.7897 - val_loss: 0.5604 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4323 - accuracy: 0.7970 - val_loss: 0.5543 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4192 - accuracy: 0.8068 - val_loss: 0.5655 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 13/400
255/257 [============================>.] - ETA: 0s - loss: 0.4083 - accuracy: 0.8130
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4081 - accuracy: 0.8131 - val_loss: 0.5770 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 746us/step
Independent Testing Matthews Correlation:  0.42535846958902446
Confusion Matrix :
 [[2839 1208]
 [1118 2929]]
Accuracy on test set:    0.7126266370150729
Sensitivity:    0.7237459846800098 	 Specificity:    0.701507289350136
Precision  : 0.7080009668842157
Area Under Curve:    0.7126266370150729
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5928 - accuracy: 0.6809 - val_loss: 0.5491 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7222 - val_loss: 0.5392 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7325 - val_loss: 0.5436 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7410 - val_loss: 0.5366 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7486 - val_loss: 0.5423 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7569 - val_loss: 0.5388 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7655 - val_loss: 0.5408 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4738 - accuracy: 0.7738 - val_loss: 0.5408 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4623 - accuracy: 0.7806 - val_loss: 0.5458 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4494 - accuracy: 0.7907 - val_loss: 0.5487 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4392 - accuracy: 0.7952 - val_loss: 0.5582 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 12/400
255/257 [============================>.] - ETA: 0s - loss: 0.4260 - accuracy: 0.8031
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4260 - accuracy: 0.8031 - val_loss: 0.5656 - val_accuracy: 0.7268 - lr: 0.0010
253/253 [==============================] - 0s 824us/step
Independent Testing Matthews Correlation:  0.4111824371369776
Confusion Matrix :
 [[2839 1208]
 [1175 2872]]
Accuracy on test set:    0.7055843834939461
Sensitivity:    0.7096614776377563 	 Specificity:    0.701507289350136
Precision  : 0.703921568627451
Area Under Curve:    0.7055843834939463
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.6824 - val_loss: 0.5414 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7209 - val_loss: 0.5324 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7321 - val_loss: 0.5292 - val_accuracy: 0.7299 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7408 - val_loss: 0.5292 - val_accuracy: 0.7336 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7480 - val_loss: 0.5292 - val_accuracy: 0.7338 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7561 - val_loss: 0.5447 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4886 - accuracy: 0.7628 - val_loss: 0.5296 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7734 - val_loss: 0.5367 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4640 - accuracy: 0.7787 - val_loss: 0.5363 - val_accuracy: 0.7311 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4496 - accuracy: 0.7884
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4499 - accuracy: 0.7881 - val_loss: 0.5412 - val_accuracy: 0.7303 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4316300897228645
Confusion Matrix :
 [[2835 1212]
 [1089 2958]]
Accuracy on test set:    0.7157153446997776
Sensitivity:    0.7309117865085248 	 Specificity:    0.7005189028910304
Precision  : 0.7093525179856115
Area Under Curve:    0.7157153446997775
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5929 - accuracy: 0.6796 - val_loss: 0.5383 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7215 - val_loss: 0.5319 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7309 - val_loss: 0.5311 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7409 - val_loss: 0.5251 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7486 - val_loss: 0.5281 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7550 - val_loss: 0.5234 - val_accuracy: 0.7337 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4854 - accuracy: 0.7632 - val_loss: 0.5283 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7718 - val_loss: 0.5287 - val_accuracy: 0.7327 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4612 - accuracy: 0.7804 - val_loss: 0.5343 - val_accuracy: 0.7311 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4490 - accuracy: 0.7878 - val_loss: 0.5411 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4340 - accuracy: 0.7977
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4344 - accuracy: 0.7974 - val_loss: 0.5521 - val_accuracy: 0.7312 - lr: 0.0010
253/253 [==============================] - 0s 767us/step
Independent Testing Matthews Correlation:  0.4476634667722383
Confusion Matrix :
 [[2727 1320]
 [ 924 3123]]
Accuracy on test set:    0.7227575982209044
Sensitivity:    0.7716827279466272 	 Specificity:    0.6738324684951816
Precision  : 0.7029034436191762
Area Under Curve:    0.7227575982209045
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5921 - accuracy: 0.6797 - val_loss: 0.5473 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7186 - val_loss: 0.5432 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5355 - accuracy: 0.7305 - val_loss: 0.5326 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5254 - accuracy: 0.7374 - val_loss: 0.5301 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7440 - val_loss: 0.5304 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7506 - val_loss: 0.5300 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7568 - val_loss: 0.5334 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4854 - accuracy: 0.7659 - val_loss: 0.5387 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4732 - accuracy: 0.7739 - val_loss: 0.5369 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4633 - accuracy: 0.7805 - val_loss: 0.5416 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4496 - accuracy: 0.7890 - val_loss: 0.5422 - val_accuracy: 0.7329 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4387 - accuracy: 0.7959 - val_loss: 0.5472 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4259 - accuracy: 0.8011 - val_loss: 0.5493 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4136 - accuracy: 0.8099 - val_loss: 0.5586 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4028 - accuracy: 0.8161 - val_loss: 0.5730 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 16/400
248/257 [===========================>..] - ETA: 0s - loss: 0.3926 - accuracy: 0.8214
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3923 - accuracy: 0.8218 - val_loss: 0.5783 - val_accuracy: 0.7244 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44952381376255013
Confusion Matrix :
 [[3032 1015]
 [1215 2832]]
Accuracy on test set:    0.724487274524339
Sensitivity:    0.6997776130467013 	 Specificity:    0.7491969360019768
Precision  : 0.7361580452300494
Area Under Curve:    0.724487274524339
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5963 - accuracy: 0.6782 - val_loss: 0.5495 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5533 - accuracy: 0.7170 - val_loss: 0.5393 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5387 - accuracy: 0.7288 - val_loss: 0.5466 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7331 - val_loss: 0.5321 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7422 - val_loss: 0.5341 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7485 - val_loss: 0.5312 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7561 - val_loss: 0.5324 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7638 - val_loss: 0.5334 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4776 - accuracy: 0.7720 - val_loss: 0.5389 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4656 - accuracy: 0.7781 - val_loss: 0.5368 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 11/400
256/257 [============================>.] - ETA: 0s - loss: 0.4551 - accuracy: 0.7861
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4551 - accuracy: 0.7861 - val_loss: 0.5436 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.45332539839249925
Confusion Matrix :
 [[3180  867]
 [1359 2688]]
Accuracy on test set:    0.7249814677538917
Sensitivity:    0.6641957005189029 	 Specificity:    0.7857672349888807
Precision  : 0.7561181434599156
Area Under Curve:    0.7249814677538917
(8094, 2560) (8094,)
Mean MCC = 0.4270 + 0.0178 and Mean AUC = 0.7129 + 0.0087
Mean Sensitivity = 0.7261 + 0.0312 and Mean Specificity = 0.6996 + 0.0397 and Mean Accuracy = 0.7129 + 0.0087
Mean Precision = 0.7087 + 0.0210





Seed   : 728736
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6848 - val_loss: 0.5602 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7239 - val_loss: 0.5622 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7349 - val_loss: 0.5466 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7432 - val_loss: 0.5465 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7529 - val_loss: 0.5481 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7592 - val_loss: 0.5599 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7665 - val_loss: 0.5653 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7762 - val_loss: 0.5554 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4559 - accuracy: 0.7841 - val_loss: 0.5624 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4428 - accuracy: 0.7935 - val_loss: 0.5598 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4324 - accuracy: 0.7987 - val_loss: 0.5772 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4211 - accuracy: 0.8061 - val_loss: 0.5828 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4092 - accuracy: 0.8130 - val_loss: 0.5873 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 14/400
249/257 [============================>.] - ETA: 0s - loss: 0.3968 - accuracy: 0.8201
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3973 - accuracy: 0.8198 - val_loss: 0.5879 - val_accuracy: 0.7115 - lr: 0.0010
253/253 [==============================] - 0s 768us/step
Independent Testing Matthews Correlation:  0.39621581152254004
Confusion Matrix :
 [[2857 1191]
 [1253 2794]]
Accuracy on test set:    0.6980852378011118
Sensitivity:    0.6903879416851989 	 Specificity:    0.7057806324110671
Precision  : 0.701129234629862
Area Under Curve:    0.698084287048133
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5895 - accuracy: 0.6834 - val_loss: 0.5551 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7235 - val_loss: 0.5479 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7320 - val_loss: 0.5519 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7418 - val_loss: 0.5442 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7497 - val_loss: 0.5472 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4970 - accuracy: 0.7559 - val_loss: 0.5472 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7632 - val_loss: 0.5508 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4743 - accuracy: 0.7727 - val_loss: 0.5544 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4588 - accuracy: 0.7824 - val_loss: 0.5587 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4468 - accuracy: 0.7900 - val_loss: 0.5636 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 11/400
256/257 [============================>.] - ETA: 0s - loss: 0.4319 - accuracy: 0.8005
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4320 - accuracy: 0.8004 - val_loss: 0.5707 - val_accuracy: 0.7111 - lr: 0.0010
253/253 [==============================] - 0s 918us/step
Independent Testing Matthews Correlation:  0.4009580498318829
Confusion Matrix :
 [[2752 1296]
 [1130 2917]]
Accuracy on test set:    0.7003088326127239
Sensitivity:    0.7207808253026934 	 Specificity:    0.6798418972332015
Precision  : 0.6923807263232851
Area Under Curve:    0.7003113612679476
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5864 - accuracy: 0.6865 - val_loss: 0.5512 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7217 - val_loss: 0.5460 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7330 - val_loss: 0.5410 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7411 - val_loss: 0.5405 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7505 - val_loss: 0.5429 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7587 - val_loss: 0.5434 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4825 - accuracy: 0.7691 - val_loss: 0.5452 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4709 - accuracy: 0.7768
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.7767 - val_loss: 0.5567 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4148101352752186
Confusion Matrix :
 [[3072  975]
 [1403 2645]]
Accuracy on test set:    0.7062384187770229
Sensitivity:    0.6534090909090909 	 Specificity:    0.7590808005930318
Precision  : 0.7306629834254144
Area Under Curve:    0.7062449457510613
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5840 - accuracy: 0.6870 - val_loss: 0.5482 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400

257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7223 - val_loss: 0.5428 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7337 - val_loss: 0.5421 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.7438 - val_loss: 0.5422 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7505 - val_loss: 0.5413 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7568 - val_loss: 0.5451 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4831 - accuracy: 0.7652
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7653 - val_loss: 0.5515 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40799787270828
Confusion Matrix :
 [[3042 1005]
 [1399 2649]]
Accuracy on test set:    0.7030265596046943
Sensitivity:    0.654397233201581 	 Specificity:    0.7516679021497406
Precision  : 0.7249589490968801
Area Under Curve:    0.7030325676756608
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5882 - accuracy: 0.6826 - val_loss: 0.5505 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7224 - val_loss: 0.5423 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7306 - val_loss: 0.5403 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7387 - val_loss: 0.5421 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7482 - val_loss: 0.5401 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7571 - val_loss: 0.5421 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7648 - val_loss: 0.5434 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4708 - accuracy: 0.7746
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7745 - val_loss: 0.5493 - val_accuracy: 0.7197 - lr: 0.0010
253/253 [==============================] - 0s 759us/step
Independent Testing Matthews Correlation:  0.43588227414038155
Confusion Matrix :
 [[2897 1150]
 [1133 2914]]
Accuracy on test set:    0.717939214232765
Sensitivity:    0.7200395354583642 	 Specificity:    0.7158388930071659
Precision  : 0.7170275590551181
Area Under Curve:    0.717939214232765
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5855 - accuracy: 0.6876 - val_loss: 0.5511 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7221 - val_loss: 0.5444 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7353 - val_loss: 0.5424 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7419 - val_loss: 0.5461 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5034 - accuracy: 0.7516 - val_loss: 0.5441 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4911 - accuracy: 0.7599 - val_loss: 0.5466 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7689 - val_loss: 0.5590 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4697 - accuracy: 0.7762 - val_loss: 0.5570 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4563 - accuracy: 0.7836 - val_loss: 0.5601 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4451 - accuracy: 0.7911 - val_loss: 0.5622 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4314 - accuracy: 0.8011 - val_loss: 0.5828 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 12/400
255/257 [============================>.] - ETA: 0s - loss: 0.4165 - accuracy: 0.8087
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4165 - accuracy: 0.8085 - val_loss: 0.5812 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43490001099423786
Confusion Matrix :
 [[2733 1314]
 [ 979 3068]]
Accuracy on test set:    0.7167037311588831
Sensitivity:    0.7580924141339264 	 Specificity:    0.6753150481838399
Precision  : 0.7001369237790963
Area Under Curve:    0.7167037311588831
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5838 - accuracy: 0.6876 - val_loss: 0.5460 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5419 - accuracy: 0.7243 - val_loss: 0.5461 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.7351 - val_loss: 0.5387 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5120 - accuracy: 0.7446 - val_loss: 0.5429 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7516 - val_loss: 0.5432 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.7612 - val_loss: 0.5471 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4781 - accuracy: 0.7683 - val_loss: 0.5473 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4637 - accuracy: 0.7807
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4647 - accuracy: 0.7799 - val_loss: 0.5537 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 763us/step
Independent Testing Matthews Correlation:  0.42592378381188883
Confusion Matrix :
 [[2644 1403]
 [ 932 3115]]
Accuracy on test set:    0.7115147022485792
Sensitivity:    0.7697059550284161 	 Specificity:    0.6533234494687423
Precision  : 0.6894643647631695
Area Under Curve:    0.7115147022485792
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5919 - accuracy: 0.6782 - val_loss: 0.5468 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5477 - accuracy: 0.7204 - val_loss: 0.5428 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7319 - val_loss: 0.5441 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7394 - val_loss: 0.5416 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7466 - val_loss: 0.5402 - val_accuracy: 0.7237 - lr: 0.0010

Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.7537 - val_loss: 0.5434 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7638 - val_loss: 0.5447 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4738 - accuracy: 0.7710 - val_loss: 0.5465 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4605 - accuracy: 0.7811
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 5ms/step - loss: 0.4604 - accuracy: 0.7810 - val_loss: 0.5540 - val_accuracy: 0.7278 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4340059923392373
Confusion Matrix :
 [[2756 1291]
 [1004 3043]]
Accuracy on test set:    0.7164566345441068
Sensitivity:    0.751914998764517 	 Specificity:    0.6809982703236965
Precision  : 0.7021227503461006
Area Under Curve:    0.7164566345441068
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5915 - accuracy: 0.6807 - val_loss: 0.5515 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5499 - accuracy: 0.7192 - val_loss: 0.5474 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5352 - accuracy: 0.7292 - val_loss: 0.5431 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5224 - accuracy: 0.7375 - val_loss: 0.5445 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5108 - accuracy: 0.7468 - val_loss: 0.5474 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7559 - val_loss: 0.5490 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7629 - val_loss: 0.5522 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4768 - accuracy: 0.7707
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4770 - accuracy: 0.7707 - val_loss: 0.5567 - val_accuracy: 0.7172 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4661520361837156
Confusion Matrix :
 [[3165  882]
 [1288 2759]]
Accuracy on test set:    0.7319001729676303
Sensitivity:    0.6817395601680257 	 Specificity:    0.782060785767235
Precision  : 0.7577588574567427
Area Under Curve:    0.7319001729676304
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5973 - accuracy: 0.6752 - val_loss: 0.5588 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5498 - accuracy: 0.7187 - val_loss: 0.5491 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5364 - accuracy: 0.7294 - val_loss: 0.5491 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5236 - accuracy: 0.7360 - val_loss: 0.5491 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7448 - val_loss: 0.5506 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5038 - accuracy: 0.7509 - val_loss: 0.5515 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7595 - val_loss: 0.5553 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7690 - val_loss: 0.5568 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4680 - accuracy: 0.7774 - val_loss: 0.5656 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4550 - accuracy: 0.7856 - val_loss: 0.5729 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4442 - accuracy: 0.7923 - val_loss: 0.5782 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4304 - accuracy: 0.7999
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4307 - accuracy: 0.7999 - val_loss: 0.5735 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4645926567113358
Confusion Matrix :
 [[3159  888]
 [1288 2759]]
Accuracy on test set:    0.7311588831233012
Sensitivity:    0.6817395601680257 	 Specificity:    0.7805782060785768
Precision  : 0.7565122018097066
Area Under Curve:    0.7311588831233012
(8094, 2560) (8094,)
Mean MCC = 0.4281 + 0.0229 and Mean AUC = 0.7133 + 0.0113
Mean Sensitivity = 0.7082 + 0.0401 and Mean Specificity = 0.7184 + 0.0445 and Mean Accuracy = 0.7133 + 0.0113
Mean Precision = 0.7172 + 0.0237





Seed   : 140767
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5862 - accuracy: 0.6871 - val_loss: 0.5609 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7233 - val_loss: 0.5565 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7343 - val_loss: 0.5505 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7425 - val_loss: 0.5488 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7505 - val_loss: 0.5497 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7565 - val_loss: 0.5510 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7649 - val_loss: 0.5544 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7753 - val_loss: 0.5601 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4585 - accuracy: 0.7834 - val_loss: 0.5690 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4444 - accuracy: 0.7931 - val_loss: 0.5621 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 11/400
251/257 [============================>.] - ETA: 0s - loss: 0.4303 - accuracy: 0.8028
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4307 - accuracy: 0.8025 - val_loss: 0.5700 - val_accuracy: 0.7111 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3960059750240145
Confusion Matrix :
 [[2629 1419]
 [1033 3014]]
Accuracy on test set:    0.6970969734403953
Sensitivity:    0.744749196936002 	 Specificity:    0.6494565217391305
Precision  : 0.6799007444168734
Area Under Curve:    0.6971028593375661
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5898 - accuracy: 0.6841 - val_loss: 0.5567 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7232 - val_loss: 0.5496 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7338 - val_loss: 0.5497 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7424 - val_loss: 0.5492 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7499 - val_loss: 0.5463 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7575 - val_loss: 0.5539 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4839 - accuracy: 0.7646
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7642 - val_loss: 0.5571 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41986399365060084
Confusion Matrix :
 [[2663 1385]
 [ 972 3075]]
Accuracy on test set:    0.7088326127239036
Sensitivity:    0.759822090437361 	 Specificity:    0.6578557312252964
Precision  : 0.6894618834080718
Area Under Curve:    0.7088389108313287
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5885 - accuracy: 0.6852 - val_loss: 0.5520 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7202 - val_loss: 0.5395 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7324 - val_loss: 0.5382 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7403 - val_loss: 0.5412 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7474 - val_loss: 0.5412 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7563 - val_loss: 0.5388 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4854 - accuracy: 0.7649 - val_loss: 0.5438 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4748 - accuracy: 0.7719 - val_loss: 0.5421 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4612 - accuracy: 0.7820 - val_loss: 0.5408 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4498 - accuracy: 0.7880 - val_loss: 0.5541 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4372 - accuracy: 0.7967 - val_loss: 0.5582 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4258 - accuracy: 0.8032 - val_loss: 0.5611 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 13/400
255/257 [============================>.] - ETA: 0s - loss: 0.4158 - accuracy: 0.8092
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4160 - accuracy: 0.8090 - val_loss: 0.5636 - val_accuracy: 0.7219 - lr: 0.0010
253/253 [==============================] - 0s 955us/step
Independent Testing Matthews Correlation:  0.4122339397991344
Confusion Matrix :
 [[2734 1313]
 [1069 2979]]
Accuracy on test set:    0.7057442865966647
Sensitivity:    0.7359189723320159 	 Specificity:    0.6755621447986162
Precision  : 0.6940820130475303
Area Under Curve:    0.705740558565316
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5831 - accuracy: 0.6873 - val_loss: 0.5399 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5416 - accuracy: 0.7251 - val_loss: 0.5309 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.7352 - val_loss: 0.5313 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7423 - val_loss: 0.5302 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5043 - accuracy: 0.7501 - val_loss: 0.5291 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4927 - accuracy: 0.7585 - val_loss: 0.5320 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7695 - val_loss: 0.5348 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4698 - accuracy: 0.7760 - val_loss: 0.5372 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4563 - accuracy: 0.7860 - val_loss: 0.5371 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4427 - accuracy: 0.7943 - val_loss: 0.5466 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4303 - accuracy: 0.8003 - val_loss: 0.5563 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4152 - accuracy: 0.8108 - val_loss: 0.5550 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4028 - accuracy: 0.8169 - val_loss: 0.5614 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3923 - accuracy: 0.8236 - val_loss: 0.5713 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 15/400
255/257 [============================>.] - ETA: 0s - loss: 0.3802 - accuracy: 0.8325
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3803 - accuracy: 0.8324 - val_loss: 0.5823 - val_accuracy: 0.7205 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4234160017851935
Confusion Matrix :
 [[2916 1131]
 [1203 2845]]
Accuracy on test set:    0.7116738727609636
Sensitivity:    0.7028162055335968 	 Specificity:    0.720533728687917
Precision  : 0.7155432595573441
Area Under Curve:    0.7116749671107568
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5921 - accuracy: 0.6802 - val_loss: 0.5635 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5485 - accuracy: 0.7202 - val_loss: 0.5488 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7316 - val_loss: 0.5465 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7383 - val_loss: 0.5446 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7483 - val_loss: 0.5446 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.7562 - val_loss: 0.5465 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 7/400
252/257 [============================>.] - ETA: 0s - loss: 0.4863 - accuracy: 0.7650
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.7650 - val_loss: 0.5485 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 956us/step
Independent Testing Matthews Correlation:  0.4378203538976867
Confusion Matrix :
 [[2972 1075]
 [1201 2846]]
Accuracy on test set:    0.7188040523844823
Sensitivity:    0.7032369656535705 	 Specificity:    0.7343711391153941
Precision  : 0.7258352461106861
Area Under Curve:    0.7188040523844823
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5846 - accuracy: 0.6870 - val_loss: 0.5520 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7228 - val_loss: 0.5466 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7344 - val_loss: 0.5460 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7426 - val_loss: 0.5456 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7509 - val_loss: 0.5468 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7586 - val_loss: 0.5477 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4821 - accuracy: 0.7668
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4827 - accuracy: 0.7663 - val_loss: 0.5494 - val_accuracy: 0.7205 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4337480018603771
Confusion Matrix :
 [[2859 1188]
 [1104 2943]]
Accuracy on test set:    0.7168272794662713
Sensitivity:    0.7272053372868792 	 Specificity:    0.7064492216456635
Precision  : 0.7124183006535948
Area Under Curve:    0.7168272794662713
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5866 - accuracy: 0.6846 - val_loss: 0.5491 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7213 - val_loss: 0.5447 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7329 - val_loss: 0.5414 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7417 - val_loss: 0.5383 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7478 - val_loss: 0.5390 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
251/257 [============================>.] - ETA: 0s - loss: 0.4967 - accuracy: 0.7578
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7576 - val_loss: 0.5419 - val_accuracy: 0.7202 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4124359704471209
Confusion Matrix :
 [[3014 1033]
 [1350 2697]]
Accuracy on test set:    0.7055843834939461
Sensitivity:    0.6664195700518903 	 Specificity:    0.744749196936002
Precision  : 0.7230563002680965
Area Under Curve:    0.7055843834939463
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5883 - accuracy: 0.6841 - val_loss: 0.5550 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7215 - val_loss: 0.5429 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7337 - val_loss: 0.5414 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7437 - val_loss: 0.5385 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7522 - val_loss: 0.5421 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4907 - accuracy: 0.7604 - val_loss: 0.5407 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4785 - accuracy: 0.7697 - val_loss: 0.5425 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4657 - accuracy: 0.7779 - val_loss: 0.5460 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4519 - accuracy: 0.7873
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4525 - accuracy: 0.7867 - val_loss: 0.5498 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.4403284393213633
Confusion Matrix :
 [[2908 1139]
 [1126 2921]]
Accuracy on test set:    0.7201630837657524
Sensitivity:    0.7217692117617989 	 Specificity:    0.7185569557697059
Precision  : 0.7194581280788177
Area Under Curve:    0.7201630837657524
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5914 - accuracy: 0.6823 - val_loss: 0.5552 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5482 - accuracy: 0.7192 - val_loss: 0.5433 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7325 - val_loss: 0.5444 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7424 - val_loss: 0.5407 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5093 - accuracy: 0.7495 - val_loss: 0.5404 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7546 - val_loss: 0.5525 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4875 - accuracy: 0.7633
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7635 - val_loss: 0.5522 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46099021225292375
Confusion Matrix :
 [[2871 1176]
 [1007 3040]]
Accuracy on test set:    0.7302940449715839
Sensitivity:    0.7511737089201878 	 Specificity:    0.7094143810229799
Precision  : 0.7210626185958254
Area Under Curve:    0.7302940449715839
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5894 - accuracy: 0.6828 - val_loss: 0.5531 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7220 - val_loss: 0.5451 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7322 - val_loss: 0.5426 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7408 - val_loss: 0.5420 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.7496 - val_loss: 0.5415 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7577 - val_loss: 0.5473 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4867 - accuracy: 0.7650 - val_loss: 0.5499 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7724 - val_loss: 0.5509 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4639 - accuracy: 0.7802 - val_loss: 0.5535 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4501 - accuracy: 0.7902 - val_loss: 0.5602 - val_accuracy: 0.7164 - lr: 0.0010

Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4380 - accuracy: 0.7960 - val_loss: 0.5736 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4232 - accuracy: 0.8053
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4234 - accuracy: 0.8051 - val_loss: 0.5716 - val_accuracy: 0.7113 - lr: 0.0010
253/253 [==============================] - 0s 973us/step
Independent Testing Matthews Correlation:  0.4860164698712208
Confusion Matrix :
 [[2945 1102]
 [ 979 3068]]
Accuracy on test set:    0.7428959723251791
Sensitivity:    0.7580924141339264 	 Specificity:    0.7276995305164319
Precision  : 0.7357314148681056
Area Under Curve:    0.7428959723251791
(8094, 2560) (8094,)
Mean MCC = 0.4323 + 0.0248 and Mean AUC = 0.7158 + 0.0126
Mean Sensitivity = 0.7271 + 0.0281 and Mean Specificity = 0.7045 + 0.0309 and Mean Accuracy = 0.7158 + 0.0126
Mean Precision = 0.7117 + 0.0170





Seed   : 796637
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5860 - accuracy: 0.6860 - val_loss: 0.5563 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7236 - val_loss: 0.5483 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7346 - val_loss: 0.5442 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7426 - val_loss: 0.5469 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7496 - val_loss: 0.5481 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.7564 - val_loss: 0.5507 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4861 - accuracy: 0.7639
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4857 - accuracy: 0.7642 - val_loss: 0.5544 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4000311531926922
Confusion Matrix :
 [[2679 1369]
 [1064 2983]]
Accuracy on test set:    0.699444101297097
Sensitivity:    0.7370892018779343 	 Specificity:    0.661808300395257
Precision  : 0.6854319852941176
Area Under Curve:    0.6994487511365954
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5878 - accuracy: 0.6851 - val_loss: 0.5559 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7227 - val_loss: 0.5497 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7335 - val_loss: 0.5492 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7434 - val_loss: 0.5458 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7505 - val_loss: 0.5461 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7570 - val_loss: 0.5521 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7645 - val_loss: 0.5511 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4723 - accuracy: 0.7722 - val_loss: 0.5616 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4599 - accuracy: 0.7831 - val_loss: 0.5564 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4488 - accuracy: 0.7891 - val_loss: 0.5651 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4368 - accuracy: 0.7956
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4372 - accuracy: 0.7953 - val_loss: 0.5721 - val_accuracy: 0.7137 - lr: 0.0010
253/253 [==============================] - 0s 995us/step
Independent Testing Matthews Correlation:  0.40768399858289023
Confusion Matrix :
 [[2639 1409]
 [ 997 3050]]
Accuracy on test set:    0.7027794935145152
Sensitivity:    0.7536446750679515 	 Specificity:    0.6519268774703557
Precision  : 0.684009867683337
Area Under Curve:    0.7027857762691536
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6847 - val_loss: 0.5545 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7221 - val_loss: 0.5385 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7352 - val_loss: 0.5350 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7411 - val_loss: 0.5401 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7506 - val_loss: 0.5360 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7579 - val_loss: 0.5369 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7667 - val_loss: 0.5421 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4711 - accuracy: 0.7733
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7730 - val_loss: 0.5406 - val_accuracy: 0.7251 - lr: 0.0010
253/253 [==============================] - 0s 849us/step
Independent Testing Matthews Correlation:  0.42562183672339077
Confusion Matrix :
 [[2808 1239]
 [1087 2961]]
Accuracy on test set:    0.71266213712168
Sensitivity:    0.7314723320158103 	 Specificity:    0.6938472942920682
Precision  : 0.705
Area Under Curve:    0.7126598131539392
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5877 - accuracy: 0.6848 - val_loss: 0.5422 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7230 - val_loss: 0.5348 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7353 - val_loss: 0.5315 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7415 - val_loss: 0.5301 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7496 - val_loss: 0.5350 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7583 - val_loss: 0.5325 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4810 - accuracy: 0.7678
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4811 - accuracy: 0.7677 - val_loss: 0.5370 - val_accuracy: 0.7266 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42299021657245545
Confusion Matrix :
 [[2599 1448]
 [ 903 3145]]
Accuracy on test set:    0.7095738109944411
Sensitivity:    0.7769268774703557 	 Specificity:    0.6422041018038053
Precision  : 0.6847376442412366
Area Under Curve:    0.7095654896370805
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6853 - val_loss: 0.5564 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7217 - val_loss: 0.5420 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7341 - val_loss: 0.5407 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7423 - val_loss: 0.5384 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7511 - val_loss: 0.5395 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7558 - val_loss: 0.5430 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4846 - accuracy: 0.7656
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.7655 - val_loss: 0.5430 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 866us/step
Independent Testing Matthews Correlation:  0.41415123548886595
Confusion Matrix :
 [[2880 1167]
 [1204 2843]]
Accuracy on test set:    0.7070669631826044
Sensitivity:    0.7024956758092414 	 Specificity:    0.7116382505559674
Precision  : 0.7089775561097257
Area Under Curve:    0.7070669631826044
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5873 - accuracy: 0.6836 - val_loss: 0.5493 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7232 - val_loss: 0.5429 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7345 - val_loss: 0.5456 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7433 - val_loss: 0.5435 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7509 - val_loss: 0.5514 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7575 - val_loss: 0.5436 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4838 - accuracy: 0.7683
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4836 - accuracy: 0.7686 - val_loss: 0.5464 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4371285516628662
Confusion Matrix :
 [[2769 1278]
 [1004 3043]]
Accuracy on test set:    0.7180627625401532
Sensitivity:    0.751914998764517 	 Specificity:    0.6842105263157895
Precision  : 0.7042351307567692
Area Under Curve:    0.7180627625401532
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5904 - accuracy: 0.6802 - val_loss: 0.5473 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7227 - val_loss: 0.5416 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7337 - val_loss: 0.5422 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7414 - val_loss: 0.5386 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7495 - val_loss: 0.5401 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7575 - val_loss: 0.5377 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.7658 - val_loss: 0.5411 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4726 - accuracy: 0.7741 - val_loss: 0.5458 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4563 - accuracy: 0.7827 - val_loss: 0.5432 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4446 - accuracy: 0.7904
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4446 - accuracy: 0.7904 - val_loss: 0.5498 - val_accuracy: 0.7237 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40428739875819264
Confusion Matrix :
 [[2814 1233]
 [1178 2869]]
Accuracy on test set:    0.7021250308870769
Sensitivity:    0.7089201877934272 	 Specificity:    0.6953298739807264
Precision  : 0.6994149195514383
Area Under Curve:    0.702125030887077
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5925 - accuracy: 0.6809 - val_loss: 0.5560 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7202 - val_loss: 0.5431 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7311 - val_loss: 0.5401 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7409 - val_loss: 0.5382 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5113 - accuracy: 0.7468 - val_loss: 0.5397 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7531 - val_loss: 0.5392 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4899 - accuracy: 0.7621 - val_loss: 0.5418 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7682 - val_loss: 0.5513 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4706 - accuracy: 0.7752
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4706 - accuracy: 0.7752 - val_loss: 0.5457 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 763us/step
Independent Testing Matthews Correlation:  0.44185658562780944
Confusion Matrix :
 [[2777 1270]
 [ 993 3054]]
Accuracy on test set:    0.7204101803805288
Sensitivity:    0.7546330615270571 	 Specificity:    0.6861872992340005
Precision  : 0.706290471785384
Area Under Curve:    0.7204101803805288
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5897 - accuracy: 0.6828 - val_loss: 0.5521 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7208 - val_loss: 0.5483 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7313 - val_loss: 0.5413 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.7405 - val_loss: 0.5412 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5113 - accuracy: 0.7462 - val_loss: 0.5404 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7546 - val_loss: 0.5402 - val_accuracy: 0.7235 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7636 - val_loss: 0.5417 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4776 - accuracy: 0.7724 - val_loss: 0.5480 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4633 - accuracy: 0.7801 - val_loss: 0.5554 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4513 - accuracy: 0.7879 - val_loss: 0.5604 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4367 - accuracy: 0.7969
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4368 - accuracy: 0.7968 - val_loss: 0.5659 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47228491705755915
Confusion Matrix :
 [[2941 1106]
 [1030 3017]]
Accuracy on test set:    0.7361008154188288
Sensitivity:    0.7454904867803311 	 Specificity:    0.7267111440573264
Precision  : 0.7317487266553481
Area Under Curve:    0.7361008154188288
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5972 - accuracy: 0.6763 - val_loss: 0.5622 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5525 - accuracy: 0.7189 - val_loss: 0.5484 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5360 - accuracy: 0.7299 - val_loss: 0.5559 - val_accuracy: 0.7058 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5228 - accuracy: 0.7399 - val_loss: 0.5436 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5110 - accuracy: 0.7480 - val_loss: 0.5447 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7551 - val_loss: 0.5482 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.7649 - val_loss: 0.5464 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4773 - accuracy: 0.7719 - val_loss: 0.5523 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4648 - accuracy: 0.7799 - val_loss: 0.5563 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4517 - accuracy: 0.7885
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4513 - accuracy: 0.7887 - val_loss: 0.5680 - val_accuracy: 0.7149 - lr: 0.0010
253/253 [==============================] - 0s 841us/step
Independent Testing Matthews Correlation:  0.5025283590141199
Confusion Matrix :
 [[2956 1091]
 [ 924 3123]]
Accuracy on test set:    0.7510501606127996
Sensitivity:    0.7716827279466272 	 Specificity:    0.730417593278972
Precision  : 0.7411010915994305
Area Under Curve:    0.7510501606127996
(8094, 2560) (8094,)
Mean MCC = 0.4329 + 0.0309 and Mean AUC = 0.7159 + 0.0156
Mean Sensitivity = 0.7434 + 0.0230 and Mean Specificity = 0.6884 + 0.0284 and Mean Accuracy = 0.7159 + 0.0156
Mean Precision = 0.7051 + 0.0182





Seed   : 267793
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5820 - accuracy: 0.6894 - val_loss: 0.5605 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5407 - accuracy: 0.7265 - val_loss: 0.5539 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5246 - accuracy: 0.7363 - val_loss: 0.5522 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7441 - val_loss: 0.5534 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5010 - accuracy: 0.7533 - val_loss: 0.5568 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4893 - accuracy: 0.7613 - val_loss: 0.5646 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4781 - accuracy: 0.7689 - val_loss: 0.5563 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7789 - val_loss: 0.5703 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4518 - accuracy: 0.7874 - val_loss: 0.5713 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4414 - accuracy: 0.7937 - val_loss: 0.5804 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4264 - accuracy: 0.8038
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4265 - accuracy: 0.8037 - val_loss: 0.5849 - val_accuracy: 0.7079 - lr: 0.0010
253/253 [==============================] - 0s 754us/step
Independent Testing Matthews Correlation:  0.3988542446415176
Confusion Matrix :
 [[2592 1456]
 [ 988 3059]]
Accuracy on test set:    0.6980852378011118
Sensitivity:    0.755868544600939 	 Specificity:    0.6403162055335968
Precision  : 0.6775193798449612
Area Under Curve:    0.6980923750672681
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5880 - accuracy: 0.6844 - val_loss: 0.5623 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7237 - val_loss: 0.5522 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.7354 - val_loss: 0.5515 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7416 - val_loss: 0.5497 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7502 - val_loss: 0.5497 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7578 - val_loss: 0.5642 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.7660 - val_loss: 0.5520 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4713 - accuracy: 0.7742
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7743 - val_loss: 0.5612 - val_accuracy: 0.7102 - lr: 0.0010
253/253 [==============================] - 0s 899us/step
Independent Testing Matthews Correlation:  0.4147056301449551
Confusion Matrix :
 [[2874 1174]
 [1195 2852]]
Accuracy on test set:    0.7073502161828289
Sensitivity:    0.7047195453422288 	 Specificity:    0.7099802371541502
Precision  : 0.7083954297069052
Area Under Curve:    0.7073498912481895
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5857 - accuracy: 0.6843 - val_loss: 0.5539 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7217 - val_loss: 0.5424 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7334 - val_loss: 0.5426 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7414 - val_loss: 0.5383 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7494 - val_loss: 0.5439 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7588 - val_loss: 0.5396 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7667 - val_loss: 0.5474 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4693 - accuracy: 0.7774 - val_loss: 0.5451 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4556 - accuracy: 0.7845
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4558 - accuracy: 0.7845 - val_loss: 0.5487 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 909us/step
Independent Testing Matthews Correlation:  0.43041798121978553
Confusion Matrix :
 [[2806 1241]
 [1066 2982]]
Accuracy on test set:    0.7150092649783817
Sensitivity:    0.7366600790513834 	 Specificity:    0.6933531010625155
Precision  : 0.7061330807482832
Area Under Curve:    0.7150065900569494
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5895 - accuracy: 0.6829 - val_loss: 0.5488 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7209 - val_loss: 0.5407 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7314 - val_loss: 0.5391 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5216 - accuracy: 0.7393 - val_loss: 0.5393 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7497 - val_loss: 0.5370 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7556 - val_loss: 0.5402 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4856 - accuracy: 0.7640 - val_loss: 0.5431 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7730 - val_loss: 0.5428 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4607 - accuracy: 0.7828
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4606 - accuracy: 0.7828 - val_loss: 0.5576 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 883us/step
Independent Testing Matthews Correlation:  0.4246467771850373
Confusion Matrix :
 [[2524 1523]
 [ 831 3217]]
Accuracy on test set:    0.7092032118591723
Sensitivity:    0.7947134387351779 	 Specificity:    0.6236718556955769
Precision  : 0.6786919831223629
Area Under Curve:    0.7091926472153773
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5854 - accuracy: 0.6859 - val_loss: 0.5527 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7211 - val_loss: 0.5485 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7335 - val_loss: 0.5507 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7413 - val_loss: 0.5434 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7504 - val_loss: 0.5451 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7582 - val_loss: 0.5603 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7662 - val_loss: 0.5490 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4708 - accuracy: 0.7752 - val_loss: 0.5535 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4548 - accuracy: 0.7849 - val_loss: 0.5623 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4419 - accuracy: 0.7947
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4419 - accuracy: 0.7946 - val_loss: 0.5727 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4275788303651623
Confusion Matrix :
 [[2760 1287]
 [1033 3014]]
Accuracy on test set:    0.713367926859402
Sensitivity:    0.744749196936002 	 Specificity:    0.6819866567828021
Precision  : 0.7007672634271099
Area Under Curve:    0.7133679268594021
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5971 - accuracy: 0.6739 - val_loss: 0.5579 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5498 - accuracy: 0.7219 - val_loss: 0.5509 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5336 - accuracy: 0.7318 - val_loss: 0.5489 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5227 - accuracy: 0.7390 - val_loss: 0.5475 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7474 - val_loss: 0.5529 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.7567 - val_loss: 0.5508 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4867 - accuracy: 0.7644
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4867 - accuracy: 0.7645 - val_loss: 0.5691 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 736us/step
Independent Testing Matthews Correlation:  0.4315782690005549
Confusion Matrix :
 [[2638 1409]
 [ 905 3142]]
Accuracy on test set:    0.7141092167037312
Sensitivity:    0.7763775636273783 	 Specificity:    0.651840869780084
Precision  : 0.6903977147879586
Area Under Curve:    0.7141092167037311
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5902 - accuracy: 0.6817 - val_loss: 0.5552 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7229 - val_loss: 0.5457 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7323 - val_loss: 0.5496 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5207 - accuracy: 0.7405 - val_loss: 0.5424 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5109 - accuracy: 0.7474 - val_loss: 0.5492 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7545 - val_loss: 0.5451 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7622 - val_loss: 0.5462 - val_accuracy: 0.7174 - lr: 0.0010

Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7682 - val_loss: 0.5494 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4696 - accuracy: 0.7749
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.7749 - val_loss: 0.5552 - val_accuracy: 0.7175 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4128721738912613
Confusion Matrix :
 [[2646 1401]
 [ 984 3063]]
Accuracy on test set:    0.7053372868791697
Sensitivity:    0.7568569310600445 	 Specificity:    0.653817642698295
Precision  : 0.6861559139784946
Area Under Curve:    0.7053372868791697
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5889 - accuracy: 0.6846 - val_loss: 0.5528 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7209 - val_loss: 0.5480 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7328 - val_loss: 0.5415 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7405 - val_loss: 0.5419 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5102 - accuracy: 0.7474 - val_loss: 0.5454 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.7551 - val_loss: 0.5425 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.7624 - val_loss: 0.5447 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4751 - accuracy: 0.7710
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.7709 - val_loss: 0.5467 - val_accuracy: 0.7146 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44922086480511236
Confusion Matrix :
 [[2865 1182]
 [1048 2999]]
Accuracy on test set:    0.724487274524339
Sensitivity:    0.7410427477143563 	 Specificity:    0.7079318013343218
Precision  : 0.7172925137526908
Area Under Curve:    0.724487274524339
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5894 - accuracy: 0.6823 - val_loss: 0.5550 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5477 - accuracy: 0.7216 - val_loss: 0.5503 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7328 - val_loss: 0.5460 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7414 - val_loss: 0.5457 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7500 - val_loss: 0.5445 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7586 - val_loss: 0.5556 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7662 - val_loss: 0.5497 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4722 - accuracy: 0.7746
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.7743 - val_loss: 0.5567 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4596589952087131
Confusion Matrix :
 [[2986 1061]
 [1126 2921]]
Accuracy on test set:    0.7297998517420311
Sensitivity:    0.7217692117617989 	 Specificity:    0.7378304917222634
Precision  : 0.733550979407333
Area Under Curve:    0.729799851742031
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5932 - accuracy: 0.6811 - val_loss: 0.5568 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5508 - accuracy: 0.7186 - val_loss: 0.5445 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5374 - accuracy: 0.7290 - val_loss: 0.5438 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5248 - accuracy: 0.7383 - val_loss: 0.5415 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5141 - accuracy: 0.7450 - val_loss: 0.5434 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5022 - accuracy: 0.7535 - val_loss: 0.5498 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.7634 - val_loss: 0.5505 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.7700 - val_loss: 0.5567 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 9/400
241/257 [===========================>..] - ETA: 0s - loss: 0.4631 - accuracy: 0.7804
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7802 - val_loss: 0.5540 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 714us/step
Independent Testing Matthews Correlation:  0.475000509295251
Confusion Matrix :
 [[3102  945]
 [1183 2864]]
Accuracy on test set:    0.7370892018779343
Sensitivity:    0.7076847047195454 	 Specificity:    0.7664936990363233
Precision  : 0.7519033867156734
Area Under Curve:    0.7370892018779343
(8094, 2560) (8094,)
Mean MCC = 0.4325 + 0.0218 and Mean AUC = 0.7154 + 0.0113
Mean Sensitivity = 0.7440 + 0.0271 and Mean Specificity = 0.6867 + 0.0430 and Mean Accuracy = 0.7154 + 0.0113
Mean Precision = 0.7051 + 0.0228





Seed   : 248194
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5874 - accuracy: 0.6840 - val_loss: 0.5599 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5416 - accuracy: 0.7256 - val_loss: 0.5538 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5265 - accuracy: 0.7368 - val_loss: 0.5485 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.7455 - val_loss: 0.5496 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7537 - val_loss: 0.5588 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7591 - val_loss: 0.5493 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7663 - val_loss: 0.5603 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4732 - accuracy: 0.7747 - val_loss: 0.5580 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 9/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4616 - accuracy: 0.7842
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4618 - accuracy: 0.7839 - val_loss: 0.5619 - val_accuracy: 0.7109 - lr: 0.0010
253/253 [==============================] - 0s 696us/step

Independent Testing Matthews Correlation:  0.4041516281929811
Confusion Matrix :
 [[2734 1314]
 [1100 2947]]
Accuracy on test set:    0.7017912291537987
Sensitivity:    0.7281937237459847 	 Specificity:    0.6753952569169961
Precision  : 0.6916216850504576
Area Under Curve:    0.7017944903314903
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5886 - accuracy: 0.6812 - val_loss: 0.5590 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7241 - val_loss: 0.5496 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7363 - val_loss: 0.5452 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7432 - val_loss: 0.5466 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7512 - val_loss: 0.5475 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7599 - val_loss: 0.5521 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7674 - val_loss: 0.5542 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4672 - accuracy: 0.7773 - val_loss: 0.5562 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4542 - accuracy: 0.7860 - val_loss: 0.5602 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4401 - accuracy: 0.7965 - val_loss: 0.5653 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4289 - accuracy: 0.8006 - val_loss: 0.5748 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4143 - accuracy: 0.8110 - val_loss: 0.5845 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4043 - accuracy: 0.8169 - val_loss: 0.5968 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 14/400
255/257 [============================>.] - ETA: 0s - loss: 0.3893 - accuracy: 0.8235
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3892 - accuracy: 0.8236 - val_loss: 0.5967 - val_accuracy: 0.7134 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40567713893540003
Confusion Matrix :
 [[2694 1354]
 [1056 2991]]
Accuracy on test set:    0.7022853613341569
Sensitivity:    0.7390659747961453 	 Specificity:    0.6655138339920948
Precision  : 0.6883774453394707
Area Under Curve:    0.7022899043941201
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5888 - accuracy: 0.6828 - val_loss: 0.5497 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7228 - val_loss: 0.5460 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7338 - val_loss: 0.5423 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7412 - val_loss: 0.5418 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7493 - val_loss: 0.5398 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7578 - val_loss: 0.5425 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4857 - accuracy: 0.7648 - val_loss: 0.5460 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4760 - accuracy: 0.7720 - val_loss: 0.5437 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4633 - accuracy: 0.7815 - val_loss: 0.5510 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4516 - accuracy: 0.7889 - val_loss: 0.5565 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4395 - accuracy: 0.7946 - val_loss: 0.5541 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4289 - accuracy: 0.8014 - val_loss: 0.5611 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 13/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4160 - accuracy: 0.8092
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4169 - accuracy: 0.8086 - val_loss: 0.5665 - val_accuracy: 0.7141 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40997603890261797
Confusion Matrix :
 [[2732 1315]
 [1076 2972]]
Accuracy on test set:    0.7046324891908585
Sensitivity:    0.7341897233201581 	 Specificity:    0.6750679515690635
Precision  : 0.6932586890599487
Area Under Curve:    0.7046288374446109
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5864 - accuracy: 0.6852 - val_loss: 0.5477 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7245 - val_loss: 0.5396 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7331 - val_loss: 0.5385 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7415 - val_loss: 0.5368 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5076 - accuracy: 0.7481 - val_loss: 0.5436 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4985 - accuracy: 0.7541 - val_loss: 0.5437 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.7635 - val_loss: 0.5420 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7693 - val_loss: 0.5425 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4667 - accuracy: 0.7777 - val_loss: 0.5456 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4551 - accuracy: 0.7857 - val_loss: 0.5561 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4438 - accuracy: 0.7924
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4437 - accuracy: 0.7924 - val_loss: 0.5720 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4086698616162244
Confusion Matrix :
 [[2461 1586]
 [ 836 3212]]
Accuracy on test set:    0.7008029647930821
Sensitivity:    0.7934782608695652 	 Specificity:    0.6081047689646651
Precision  : 0.669445602334306
Area Under Curve:    0.7007915149171152
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6820 - val_loss: 0.5514 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7214 - val_loss: 0.5440 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400

257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7337 - val_loss: 0.5450 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7429 - val_loss: 0.5464 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7500 - val_loss: 0.5411 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7586 - val_loss: 0.5462 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4836 - accuracy: 0.7680
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4836 - accuracy: 0.7680 - val_loss: 0.5455 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 791us/step
Independent Testing Matthews Correlation:  0.4307538404141119
Confusion Matrix :
 [[2860 1187]
 [1117 2930]]
Accuracy on test set:    0.7153446997776131
Sensitivity:    0.7239930812947862 	 Specificity:    0.7066963182604399
Precision  : 0.7116832645129949
Area Under Curve:    0.715344699777613
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5885 - accuracy: 0.6829 - val_loss: 0.5518 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7207 - val_loss: 0.5455 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7332 - val_loss: 0.5423 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7423 - val_loss: 0.5435 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7504 - val_loss: 0.5441 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7569 - val_loss: 0.5441 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7662 - val_loss: 0.5503 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7750 - val_loss: 0.5499 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4592 - accuracy: 0.7841
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4594 - accuracy: 0.7840 - val_loss: 0.5538 - val_accuracy: 0.7202 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41817123887973356
Confusion Matrix :
 [[2910 1137]
 [1218 2829]]
Accuracy on test set:    0.7090437361008154
Sensitivity:    0.6990363232023721 	 Specificity:    0.7190511489992587
Precision  : 0.7133131618759455
Area Under Curve:    0.7090437361008153
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5865 - accuracy: 0.6852 - val_loss: 0.5505 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7230 - val_loss: 0.5453 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7326 - val_loss: 0.5424 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5148 - accuracy: 0.7425 - val_loss: 0.5421 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7518 - val_loss: 0.5454 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4918 - accuracy: 0.7610 - val_loss: 0.5464 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4792 - accuracy: 0.7688
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7684 - val_loss: 0.5455 - val_accuracy: 0.7205 - lr: 0.0010
253/253 [==============================] - 0s 973us/step
Independent Testing Matthews Correlation:  0.43885067512210096
Confusion Matrix :
 [[2923 1124]
 [1147 2900]]
Accuracy on test set:    0.7194217939214232
Sensitivity:    0.7165801828514949 	 Specificity:    0.7222634049913517
Precision  : 0.7206759443339961
Area Under Curve:    0.7194217939214234
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5917 - accuracy: 0.6818 - val_loss: 0.5525 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5477 - accuracy: 0.7200 - val_loss: 0.5445 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7321 - val_loss: 0.5410 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5210 - accuracy: 0.7392 - val_loss: 0.5395 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7488 - val_loss: 0.5399 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4986 - accuracy: 0.7550 - val_loss: 0.5401 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4887 - accuracy: 0.7639 - val_loss: 0.5453 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4751 - accuracy: 0.7716
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.7716 - val_loss: 0.5468 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44461808732948593
Confusion Matrix :
 [[2882 1165]
 [1083 2964]]
Accuracy on test set:    0.7222634049913517
Sensitivity:    0.7323943661971831 	 Specificity:    0.7121324437855201
Precision  : 0.7178493581981109
Area Under Curve:    0.7222634049913516
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5872 - accuracy: 0.6860 - val_loss: 0.5523 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7233 - val_loss: 0.5452 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7327 - val_loss: 0.5451 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7414 - val_loss: 0.5398 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7488 - val_loss: 0.5407 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7571 - val_loss: 0.5512 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4836 - accuracy: 0.7649 - val_loss: 0.5455 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4718 - accuracy: 0.7747 - val_loss: 0.5532 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 9/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4579 - accuracy: 0.7844
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4582 - accuracy: 0.7840 - val_loss: 0.5513 - val_accuracy: 0.7154 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.45467477509337484
Confusion Matrix :
 [[2961 1086]
 [1121 2926]]
Accuracy on test set:    0.7273288855942673
Sensitivity:    0.7230046948356808 	 Specificity:    0.7316530763528539
Precision  : 0.7293120638085743
Area Under Curve:    0.7273288855942672
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5912 - accuracy: 0.6815 - val_loss: 0.5565 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5489 - accuracy: 0.7200 - val_loss: 0.5519 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5337 - accuracy: 0.7305 - val_loss: 0.5500 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5224 - accuracy: 0.7383 - val_loss: 0.5515 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5128 - accuracy: 0.7452 - val_loss: 0.5497 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.7558 - val_loss: 0.5458 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7606 - val_loss: 0.5476 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4785 - accuracy: 0.7714 - val_loss: 0.5582 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4648 - accuracy: 0.7800 - val_loss: 0.5578 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4510 - accuracy: 0.7881 - val_loss: 0.5634 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 11/400
251/257 [============================>.] - ETA: 0s - loss: 0.4389 - accuracy: 0.7961
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4391 - accuracy: 0.7960 - val_loss: 0.5675 - val_accuracy: 0.7150 - lr: 0.0010
253/253 [==============================] - 0s 881us/step
Independent Testing Matthews Correlation:  0.46785447100970334
Confusion Matrix :
 [[3071  976]
 [1180 2867]]
Accuracy on test set:    0.733629849271065
Sensitivity:    0.7084259945638745 	 Specificity:    0.7588337039782554
Precision  : 0.746031746031746
Area Under Curve:    0.733629849271065
(8094, 2560) (8094,)
Mean MCC = 0.4283 + 0.0214 and Mean AUC = 0.7137 + 0.0111
Mean Sensitivity = 0.7298 + 0.0241 and Mean Specificity = 0.6975 + 0.0404 and Mean Accuracy = 0.7137 + 0.0111
Mean Precision = 0.7082 + 0.0213





Seed   : 153761
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5868 - accuracy: 0.6867 - val_loss: 0.5548 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5413 - accuracy: 0.7263 - val_loss: 0.5456 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5240 - accuracy: 0.7373 - val_loss: 0.5424 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5122 - accuracy: 0.7460 - val_loss: 0.5463 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.7529 - val_loss: 0.5475 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4897 - accuracy: 0.7633 - val_loss: 0.5464 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7717 - val_loss: 0.5462 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4654 - accuracy: 0.7786 - val_loss: 0.5529 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4508 - accuracy: 0.7876 - val_loss: 0.5546 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4400 - accuracy: 0.7955 - val_loss: 0.5608 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4272 - accuracy: 0.8045 - val_loss: 0.5684 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4153 - accuracy: 0.8085 - val_loss: 0.5736 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4040 - accuracy: 0.8163 - val_loss: 0.5763 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 14/400
256/257 [============================>.] - ETA: 0s - loss: 0.3913 - accuracy: 0.8234
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3914 - accuracy: 0.8233 - val_loss: 0.5863 - val_accuracy: 0.7132 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3936383916588332
Confusion Matrix :
 [[2701 1347]
 [1110 2937]]
Accuracy on test set:    0.6964793082149475
Sensitivity:    0.7257227575982209 	 Specificity:    0.6672430830039525
Precision  : 0.6855742296918768
Area Under Curve:    0.6964829203010867
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5849 - accuracy: 0.6881 - val_loss: 0.5564 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7256 - val_loss: 0.5531 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7353 - val_loss: 0.5427 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7436 - val_loss: 0.5478 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7515 - val_loss: 0.5453 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7585 - val_loss: 0.5508 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7665 - val_loss: 0.5479 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4711 - accuracy: 0.7750 - val_loss: 0.5522 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4605 - accuracy: 0.7816 - val_loss: 0.5651 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4469 - accuracy: 0.7897 - val_loss: 0.5592 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4372 - accuracy: 0.7967 - val_loss: 0.5693 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4233 - accuracy: 0.8048 - val_loss: 0.5777 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4126 - accuracy: 0.8101 - val_loss: 0.5812 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3997 - accuracy: 0.8185 - val_loss: 0.5858 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3879 - accuracy: 0.8229 - val_loss: 0.5939 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - ETA: 0s - loss: 0.3751 - accuracy: 0.8290
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3751 - accuracy: 0.8290 - val_loss: 0.6017 - val_accuracy: 0.7120 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40532074820576625
Confusion Matrix :
 [[2701 1347]
 [1064 2983]]
Accuracy on test set:    0.7021618282890674
Sensitivity:    0.7370892018779343 	 Specificity:    0.6672430830039525
Precision  : 0.6889145496535797
Area Under Curve:    0.7021661424409434
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5867 - accuracy: 0.6858 - val_loss: 0.5453 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5477 - accuracy: 0.7201 - val_loss: 0.5449 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7332 - val_loss: 0.5338 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7416 - val_loss: 0.5313 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7479 - val_loss: 0.5367 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7558 - val_loss: 0.5344 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4856 - accuracy: 0.7658 - val_loss: 0.5464 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7736 - val_loss: 0.5400 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4601 - accuracy: 0.7811 - val_loss: 0.5436 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4464 - accuracy: 0.7913 - val_loss: 0.5527 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
256/257 [============================>.] - ETA: 0s - loss: 0.4326 - accuracy: 0.7986
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4326 - accuracy: 0.7986 - val_loss: 0.5705 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42213143673684134
Confusion Matrix :
 [[2458 1589]
 [ 784 3264]]
Accuracy on test set:    0.7068560840024707
Sensitivity:    0.8063241106719368 	 Specificity:    0.6073634791203361
Precision  : 0.6725736657737482
Area Under Curve:    0.7068437948961364
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5919 - accuracy: 0.6791 - val_loss: 0.5401 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7217 - val_loss: 0.5332 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7335 - val_loss: 0.5301 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7432 - val_loss: 0.5364 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7500 - val_loss: 0.5308 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7577 - val_loss: 0.5306 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7647 - val_loss: 0.5358 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4685 - accuracy: 0.7756 - val_loss: 0.5408 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.7850 - val_loss: 0.5414 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4441 - accuracy: 0.7917
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4441 - accuracy: 0.7918 - val_loss: 0.5484 - val_accuracy: 0.7235 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4073066436482027
Confusion Matrix :
 [[2828 1219]
 [1180 2868]]
Accuracy on test set:    0.7036442248301421
Sensitivity:    0.708498023715415 	 Specificity:    0.6987892265875958
Precision  : 0.7017372155615366
Area Under Curve:    0.7036436251515052
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5862 - accuracy: 0.6845 - val_loss: 0.5471 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7225 - val_loss: 0.5404 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5265 - accuracy: 0.7354 - val_loss: 0.5408 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7447 - val_loss: 0.5403 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5027 - accuracy: 0.7522 - val_loss: 0.5508 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.7606 - val_loss: 0.5386 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4774 - accuracy: 0.7690 - val_loss: 0.5432 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.7782 - val_loss: 0.5479 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4527 - accuracy: 0.7865
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4527 - accuracy: 0.7866 - val_loss: 0.5508 - val_accuracy: 0.7256 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4218211711191742
Confusion Matrix :
 [[2900 1147]
 [1193 2854]]
Accuracy on test set:    0.7108969607116382
Sensitivity:    0.7052137385717816 	 Specificity:    0.7165801828514949
Precision  : 0.7133216695826043
Area Under Curve:    0.7108969607116383
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5890 - accuracy: 0.6834 - val_loss: 0.5456 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5480 - accuracy: 0.7196 - val_loss: 0.5417 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7315 - val_loss: 0.5359 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5210 - accuracy: 0.7376 - val_loss: 0.5380 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7442 - val_loss: 0.5419 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5021 - accuracy: 0.7535 - val_loss: 0.5415 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4923 - accuracy: 0.7603
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4928 - accuracy: 0.7599 - val_loss: 0.5500 - val_accuracy: 0.7227 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44261933730002406
Confusion Matrix :
 [[2657 1390]
 [ 880 3167]]
Accuracy on test set:    0.7195453422288115
Sensitivity:    0.7825549789967877 	 Specificity:    0.6565357054608352
Precision  : 0.694974764099188
Area Under Curve:    0.7195453422288115
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5870 - accuracy: 0.6847 - val_loss: 0.5430 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7236 - val_loss: 0.5373 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7338 - val_loss: 0.5337 - val_accuracy: 0.7329 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7436 - val_loss: 0.5366 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7515 - val_loss: 0.5366 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4924 - accuracy: 0.7590 - val_loss: 0.5403 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4794 - accuracy: 0.7687 - val_loss: 0.5380 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4636 - accuracy: 0.7791
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4636 - accuracy: 0.7793 - val_loss: 0.5428 - val_accuracy: 0.7278 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4324090767991973
Confusion Matrix :
 [[2831 1216]
 [1082 2965]]
Accuracy on test set:    0.7160859896219421
Sensitivity:    0.7326414628119595 	 Specificity:    0.6995305164319249
Precision  : 0.7091604879215498
Area Under Curve:    0.7160859896219421
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5865 - accuracy: 0.6859 - val_loss: 0.5465 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7212 - val_loss: 0.5408 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7332 - val_loss: 0.5369 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7400 - val_loss: 0.5385 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7502 - val_loss: 0.5357 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7595 - val_loss: 0.5432 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.7665 - val_loss: 0.5355 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4727 - accuracy: 0.7754 - val_loss: 0.5435 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.7833 - val_loss: 0.5495 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4473 - accuracy: 0.7913 - val_loss: 0.5470 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4352 - accuracy: 0.7995 - val_loss: 0.5552 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4237 - accuracy: 0.8048 - val_loss: 0.5619 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4105 - accuracy: 0.8132 - val_loss: 0.5713 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3998 - accuracy: 0.8186 - val_loss: 0.5706 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 15/400
252/257 [============================>.] - ETA: 0s - loss: 0.3867 - accuracy: 0.8270
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3868 - accuracy: 0.8269 - val_loss: 0.5898 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 721us/step
Independent Testing Matthews Correlation:  0.4150252493986354
Confusion Matrix :
 [[2774 1273]
 [1096 2951]]
Accuracy on test set:    0.7073140597973808
Sensitivity:    0.7291821102050902 	 Specificity:    0.6854460093896714
Precision  : 0.6986268939393939
Area Under Curve:    0.7073140597973807
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5915 - accuracy: 0.6818 - val_loss: 0.5499 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7188 - val_loss: 0.5428 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7325 - val_loss: 0.5409 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7401 - val_loss: 0.5396 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7479 - val_loss: 0.5409 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7557 - val_loss: 0.5428 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7666 - val_loss: 0.5489 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4697 - accuracy: 0.7760 - val_loss: 0.5475 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4560 - accuracy: 0.7838 - val_loss: 0.5531 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4450 - accuracy: 0.7912 - val_loss: 0.5623 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 11/400
251/257 [============================>.] - ETA: 0s - loss: 0.4286 - accuracy: 0.7991
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4286 - accuracy: 0.7992 - val_loss: 0.5628 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42584219309835936
Confusion Matrix :
 [[3056  991]
 [1339 2708]]
Accuracy on test set:    0.7121324437855201
Sensitivity:    0.6691376328144304 	 Specificity:    0.7551272547566098
Precision  : 0.7320897539875642
Area Under Curve:    0.7121324437855201
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5965 - accuracy: 0.6784 - val_loss: 0.5562 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5517 - accuracy: 0.7177 - val_loss: 0.5475 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5371 - accuracy: 0.7278 - val_loss: 0.5471 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5253 - accuracy: 0.7362 - val_loss: 0.5479 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7427 - val_loss: 0.5474 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7525 - val_loss: 0.5474 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7604 - val_loss: 0.5551 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7705 - val_loss: 0.5596 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7797 - val_loss: 0.5590 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4542 - accuracy: 0.7862 - val_loss: 0.5649 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7927 - val_loss: 0.5669 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4302 - accuracy: 0.8000 - val_loss: 0.5788 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - ETA: 0s - loss: 0.4168 - accuracy: 0.8092
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4168 - accuracy: 0.8092 - val_loss: 0.5797 - val_accuracy: 0.7150 - lr: 0.0010
253/253 [==============================] - 0s 960us/step
Independent Testing Matthews Correlation:  0.4655849512688028
Confusion Matrix :
 [[3139  908]
 [1262 2785]]
Accuracy on test set:    0.7319001729676303
Sensitivity:    0.6881640721522115 	 Specificity:    0.7756362737830492
Precision  : 0.7541294340644462
Area Under Curve:    0.7319001729676303
(8094, 2560) (8094,)
Mean MCC = 0.4232 + 0.0194 and Mean AUC = 0.7107 + 0.0095
Mean Sensitivity = 0.7285 + 0.0389 and Mean Specificity = 0.6929 + 0.0462 and Mean Accuracy = 0.7107 + 0.0095
Mean Precision = 0.7051 + 0.0225





Seed   : 335595
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5848 - accuracy: 0.6874 - val_loss: 0.5494 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7251 - val_loss: 0.5452 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7347 - val_loss: 0.5407 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7437 - val_loss: 0.5421 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7501 - val_loss: 0.5431 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7585 - val_loss: 0.5471 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7651 - val_loss: 0.5488 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7733 - val_loss: 0.5552 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4627 - accuracy: 0.7817
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4627 - accuracy: 0.7818 - val_loss: 0.5568 - val_accuracy: 0.7224 - lr: 0.0010
253/253 [==============================] - 0s 822us/step
Independent Testing Matthews Correlation:  0.40182207327855546
Confusion Matrix :
 [[2771 1277]
 [1145 2902]]
Accuracy on test set:    0.7008029647930821
Sensitivity:    0.7170743760810477 	 Specificity:    0.6845355731225297
Precision  : 0.6944245034697296
Area Under Curve:    0.7008049746017887
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5875 - accuracy: 0.6844 - val_loss: 0.5543 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7235 - val_loss: 0.5505 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7333 - val_loss: 0.5468 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7412 - val_loss: 0.5458 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7493 - val_loss: 0.5443 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7577 - val_loss: 0.5495 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7678 - val_loss: 0.5621 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7759 - val_loss: 0.5534 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4548 - accuracy: 0.7847
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4550 - accuracy: 0.7845 - val_loss: 0.5596 - val_accuracy: 0.7134 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4096104451072343
Confusion Matrix :
 [[2809 1239]
 [1151 2896]]
Accuracy on test set:    0.7047560222359481
Sensitivity:    0.7155917963923895 	 Specificity:    0.6939229249011858
Precision  : 0.7003627569528416
Area Under Curve:    0.7047573606467876
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5843 - accuracy: 0.6867 - val_loss: 0.5446 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7239 - val_loss: 0.5381 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7338 - val_loss: 0.5376 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7429 - val_loss: 0.5357 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7495 - val_loss: 0.5437 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7605 - val_loss: 0.5397 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4825 - accuracy: 0.7688
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4825 - accuracy: 0.7686 - val_loss: 0.5427 - val_accuracy: 0.7238 - lr: 0.0010
253/253 [==============================] - 0s 847us/step
Independent Testing Matthews Correlation:  0.4140030656608917
Confusion Matrix :
 [[2936 1111]
 [1262 2786]]
Accuracy on test set:    0.7068560840024707
Sensitivity:    0.6882411067193676 	 Specificity:    0.7254756609834445
Precision  : 0.7149089042853477
Area Under Curve:    0.7068583838514061
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5958 - accuracy: 0.6756 - val_loss: 0.5454 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5495 - accuracy: 0.7194 - val_loss: 0.5357 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5328 - accuracy: 0.7321 - val_loss: 0.5349 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5220 - accuracy: 0.7393 - val_loss: 0.5368 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7467 - val_loss: 0.5344 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.7543 - val_loss: 0.5361 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7642 - val_loss: 0.5439 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 8/400

255/257 [============================>.] - ETA: 0s - loss: 0.4759 - accuracy: 0.7709
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4760 - accuracy: 0.7708 - val_loss: 0.5496 - val_accuracy: 0.7222 - lr: 0.0010
253/253 [==============================] - 0s 750us/step
Independent Testing Matthews Correlation:  0.42261897554360206
Confusion Matrix :
 [[2643 1404]
 [ 944 3104]]
Accuracy on test set:    0.7099444101297097
Sensitivity:    0.766798418972332 	 Specificity:    0.6530763528539659
Precision  : 0.6885536823425022
Area Under Curve:    0.709937385913149
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6830 - val_loss: 0.5534 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7213 - val_loss: 0.5578 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7310 - val_loss: 0.5424 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7410 - val_loss: 0.5429 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7488 - val_loss: 0.5426 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7562 - val_loss: 0.5521 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4801 - accuracy: 0.7664 - val_loss: 0.5458 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4675 - accuracy: 0.7763 - val_loss: 0.5558 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4554 - accuracy: 0.7832 - val_loss: 0.5542 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 10/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4419 - accuracy: 0.7941
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7933 - val_loss: 0.5568 - val_accuracy: 0.7149 - lr: 0.0010
253/253 [==============================] - 0s 776us/step
Independent Testing Matthews Correlation:  0.4148898582604302
Confusion Matrix :
 [[2880 1167]
 [1201 2846]]
Accuracy on test set:    0.707437608104769
Sensitivity:    0.7032369656535705 	 Specificity:    0.7116382505559674
Precision  : 0.7091951158734114
Area Under Curve:    0.707437608104769
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5870 - accuracy: 0.6832 - val_loss: 0.5559 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7237 - val_loss: 0.5513 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7340 - val_loss: 0.5475 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7418 - val_loss: 0.5499 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7517 - val_loss: 0.5496 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7592 - val_loss: 0.5556 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4818 - accuracy: 0.7653
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7654 - val_loss: 0.5517 - val_accuracy: 0.7200 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4330250527107028
Confusion Matrix :
 [[2697 1350]
 [ 953 3094]]
Accuracy on test set:    0.7154682480850012
Sensitivity:    0.7645169261181122 	 Specificity:    0.6664195700518903
Precision  : 0.6962196219621962
Area Under Curve:    0.7154682480850012
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5851 - accuracy: 0.6858 - val_loss: 0.5606 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7243 - val_loss: 0.5499 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5261 - accuracy: 0.7353 - val_loss: 0.5528 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5130 - accuracy: 0.7442 - val_loss: 0.5669 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5023 - accuracy: 0.7524 - val_loss: 0.5515 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7605 - val_loss: 0.5542 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4788 - accuracy: 0.7677
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7680 - val_loss: 0.5562 - val_accuracy: 0.7149 - lr: 0.0010
253/253 [==============================] - 0s 784us/step
Independent Testing Matthews Correlation:  0.4334037198539747
Confusion Matrix :
 [[2781 1266]
 [1030 3017]]
Accuracy on test set:    0.7163330862367185
Sensitivity:    0.7454904867803311 	 Specificity:    0.687175685693106
Precision  : 0.7044127947700211
Area Under Curve:    0.7163330862367185
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5850 - accuracy: 0.6864 - val_loss: 0.5535 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7239 - val_loss: 0.5485 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7339 - val_loss: 0.5467 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7406 - val_loss: 0.5457 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7488 - val_loss: 0.5451 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4970 - accuracy: 0.7551 - val_loss: 0.5447 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4861 - accuracy: 0.7646 - val_loss: 0.5417 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4730 - accuracy: 0.7742 - val_loss: 0.5497 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4618 - accuracy: 0.7831 - val_loss: 0.5495 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4483 - accuracy: 0.7906 - val_loss: 0.5596 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - ETA: 0s - loss: 0.4348 - accuracy: 0.7990
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4348 - accuracy: 0.7990 - val_loss: 0.5663 - val_accuracy: 0.7242 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4393448763328241
Confusion Matrix :
 [[2901 1146]
 [1123 2924]]
Accuracy on test set:    0.7196688905361996
Sensitivity:    0.722510501606128 	 Specificity:    0.7168272794662713
Precision  : 0.7184275184275184
Area Under Curve:    0.7196688905361996
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5985 - accuracy: 0.6739 - val_loss: 0.5570 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5524 - accuracy: 0.7180 - val_loss: 0.5509 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5348 - accuracy: 0.7285 - val_loss: 0.5461 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5222 - accuracy: 0.7379 - val_loss: 0.5497 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7491 - val_loss: 0.5478 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7567 - val_loss: 0.5459 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4848 - accuracy: 0.7649 - val_loss: 0.5504 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4687 - accuracy: 0.7752
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7752 - val_loss: 0.5540 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 828us/step
Independent Testing Matthews Correlation:  0.47988000063149333
Confusion Matrix :
 [[2900 1147]
 [ 960 3087]]
Accuracy on test set:    0.7396837163330863
Sensitivity:    0.7627872498146775 	 Specificity:    0.7165801828514949
Precision  : 0.7290977798771847
Area Under Curve:    0.7396837163330862
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5926 - accuracy: 0.6800 - val_loss: 0.5544 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5502 - accuracy: 0.7197 - val_loss: 0.5535 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5366 - accuracy: 0.7302 - val_loss: 0.5460 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5242 - accuracy: 0.7368 - val_loss: 0.5446 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5140 - accuracy: 0.7444 - val_loss: 0.5466 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7540 - val_loss: 0.5476 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7630 - val_loss: 0.5497 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4757 - accuracy: 0.7711 - val_loss: 0.5529 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4616 - accuracy: 0.7810 - val_loss: 0.5576 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4472 - accuracy: 0.7923
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4474 - accuracy: 0.7924 - val_loss: 0.5621 - val_accuracy: 0.7148 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4741219236012675
Confusion Matrix :
 [[3218  829]
 [1313 2734]]
Accuracy on test set:    0.7353595255744997
Sensitivity:    0.6755621447986162 	 Specificity:    0.795156906350383
Precision  : 0.7673309009261858
Area Under Curve:    0.7353595255744995
(8094, 2560) (8094,)
Mean MCC = 0.4323 + 0.0250 and Mean AUC = 0.7156 + 0.0122
Mean Sensitivity = 0.7262 + 0.0309 and Mean Specificity = 0.7051 + 0.0373 and Mean Accuracy = 0.7156 + 0.0122
Mean Precision = 0.7123 + 0.0217





Seed   : 441253
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5895 - accuracy: 0.6832 - val_loss: 0.5617 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7235 - val_loss: 0.5536 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7351 - val_loss: 0.5506 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7415 - val_loss: 0.5522 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7488 - val_loss: 0.5517 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4985 - accuracy: 0.7555 - val_loss: 0.5640 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4899 - accuracy: 0.7631 - val_loss: 0.5634 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4784 - accuracy: 0.7691 - val_loss: 0.5561 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7728 - val_loss: 0.5625 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4587 - accuracy: 0.7823 - val_loss: 0.5634 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4493 - accuracy: 0.7877 - val_loss: 0.5771 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4377 - accuracy: 0.7952 - val_loss: 0.5779 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4271 - accuracy: 0.7996 - val_loss: 0.5780 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4149 - accuracy: 0.8083 - val_loss: 0.5808 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 15/400
255/257 [============================>.] - ETA: 0s - loss: 0.4048 - accuracy: 0.8148
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4045 - accuracy: 0.8149 - val_loss: 0.5957 - val_accuracy: 0.7082 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40757117189215775
Confusion Matrix :
 [[2704 1344]
 [1058 2989]]
Accuracy on test set:    0.7032736256948734
Sensitivity:    0.7385717815665925 	 Specificity:    0.6679841897233202
Precision  : 0.6898222940226171
Area Under Curve:    0.7032779856449562
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5885 - accuracy: 0.6842 - val_loss: 0.5609 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7242 - val_loss: 0.5556 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7335 - val_loss: 0.5598 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7422 - val_loss: 0.5523 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7499 - val_loss: 0.5543 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7570 - val_loss: 0.5537 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7670 - val_loss: 0.5558 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4740 - accuracy: 0.7734 - val_loss: 0.5629 - val_accuracy: 0.7058 - lr: 0.0010

Epoch 9/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4630 - accuracy: 0.7808
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4629 - accuracy: 0.7806 - val_loss: 0.5646 - val_accuracy: 0.7083 - lr: 0.0010
253/253 [==============================] - 0s 979us/step
Independent Testing Matthews Correlation:  0.41676311191916643
Confusion Matrix :
 [[2909 1139]
 [1222 2825]]
Accuracy on test set:    0.7083384805435454
Sensitivity:    0.6980479367432666 	 Specificity:    0.7186264822134387
Precision  : 0.7126639757820383
Area Under Curve:    0.7083372094783527
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5902 - accuracy: 0.6832 - val_loss: 0.5545 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7234 - val_loss: 0.5432 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7340 - val_loss: 0.5410 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5154 - accuracy: 0.7429 - val_loss: 0.5421 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7502 - val_loss: 0.5434 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7595 - val_loss: 0.5413 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7675 - val_loss: 0.5446 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.7730 - val_loss: 0.5465 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4613 - accuracy: 0.7807 - val_loss: 0.5521 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4492 - accuracy: 0.7881 - val_loss: 0.5548 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4352 - accuracy: 0.7974
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4352 - accuracy: 0.7974 - val_loss: 0.5663 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41393738144799025
Confusion Matrix :
 [[2763 1284]
 [1090 2958]]
Accuracy on test set:    0.7067325509573811
Sensitivity:    0.7307312252964426 	 Specificity:    0.6827279466271312
Precision  : 0.6973125884016973
Area Under Curve:    0.706729585961787
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5897 - accuracy: 0.6815 - val_loss: 0.5570 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7213 - val_loss: 0.5483 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7328 - val_loss: 0.5412 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7399 - val_loss: 0.5397 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7496 - val_loss: 0.5402 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7584 - val_loss: 0.5419 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7651 - val_loss: 0.5389 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4690 - accuracy: 0.7755 - val_loss: 0.5457 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4585 - accuracy: 0.7809 - val_loss: 0.5554 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4439 - accuracy: 0.7905
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4443 - accuracy: 0.7903 - val_loss: 0.5552 - val_accuracy: 0.7205 - lr: 0.0010
253/253 [==============================] - 0s 988us/step
Independent Testing Matthews Correlation:  0.4293903201146656
Confusion Matrix :
 [[2665 1382]
 [ 938 3110]]
Accuracy on test set:    0.7134033353922175
Sensitivity:    0.7682806324110671 	 Specificity:    0.6585124783790463
Precision  : 0.6923419412288513
Area Under Curve:    0.7133965553950565
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5859 - accuracy: 0.6868 - val_loss: 0.5526 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7244 - val_loss: 0.5447 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7338 - val_loss: 0.5403 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7408 - val_loss: 0.5440 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7497 - val_loss: 0.5448 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7580 - val_loss: 0.5435 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7674 - val_loss: 0.5499 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4718 - accuracy: 0.7755
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4716 - accuracy: 0.7757 - val_loss: 0.5542 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 763us/step
Independent Testing Matthews Correlation:  0.42839301665459634
Confusion Matrix :
 [[2739 1308]
 [1010 3037]]
Accuracy on test set:    0.7136150234741784
Sensitivity:    0.7504324190758587 	 Specificity:    0.6767976278724982
Precision  : 0.698964326812428
Area Under Curve:    0.7136150234741784
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5870 - accuracy: 0.6848 - val_loss: 0.5451 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7228 - val_loss: 0.5396 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7318 - val_loss: 0.5376 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7395 - val_loss: 0.5360 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.7475 - val_loss: 0.5391 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7552 - val_loss: 0.5402 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4899 - accuracy: 0.7611 - val_loss: 0.5432 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7699 - val_loss: 0.5448 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4652 - accuracy: 0.7788
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4652 - accuracy: 0.7788 - val_loss: 0.5514 - val_accuracy: 0.7241 - lr: 0.0010
253/253 [==============================] - 0s 953us/step
Independent Testing Matthews Correlation:  0.3996747803056946
Confusion Matrix :
 [[3010 1037]
 [1399 2648]]
Accuracy on test set:    0.6990363232023721
Sensitivity:    0.6543118359278478 	 Specificity:    0.7437608104768965
Precision  : 0.7185888738127544
Area Under Curve:    0.6990363232023721
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5907 - accuracy: 0.6814 - val_loss: 0.5498 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7212 - val_loss: 0.5430 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7321 - val_loss: 0.5367 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5204 - accuracy: 0.7393 - val_loss: 0.5351 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5102 - accuracy: 0.7463 - val_loss: 0.5362 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4999 - accuracy: 0.7535 - val_loss: 0.5394 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.7609 - val_loss: 0.5393 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4797 - accuracy: 0.7699 - val_loss: 0.5409 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4682 - accuracy: 0.7771 - val_loss: 0.5460 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4565 - accuracy: 0.7841 - val_loss: 0.5523 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4443 - accuracy: 0.7929 - val_loss: 0.5602 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4312 - accuracy: 0.8006 - val_loss: 0.5700 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 13/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4198 - accuracy: 0.8083
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4202 - accuracy: 0.8080 - val_loss: 0.5682 - val_accuracy: 0.7229 - lr: 0.0010
253/253 [==============================] - 0s 744us/step
Independent Testing Matthews Correlation:  0.42243304112148744
Confusion Matrix :
 [[2825 1222]
 [1116 2931]]
Accuracy on test set:    0.7111440573264146
Sensitivity:    0.7242401779095626 	 Specificity:    0.6980479367432666
Precision  : 0.7057548759932579
Area Under Curve:    0.7111440573264146
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5893 - accuracy: 0.6829 - val_loss: 0.5427 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7215 - val_loss: 0.5361 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7315 - val_loss: 0.5339 - val_accuracy: 0.7311 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7400 - val_loss: 0.5347 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.7481 - val_loss: 0.5358 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7565 - val_loss: 0.5380 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.7631 - val_loss: 0.5406 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4750 - accuracy: 0.7712
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4752 - accuracy: 0.7710 - val_loss: 0.5446 - val_accuracy: 0.7275 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44906089210957073
Confusion Matrix :
 [[2760 1287]
 [ 949 3098]]
Accuracy on test set:    0.7237459846800098
Sensitivity:    0.7655053125772177 	 Specificity:    0.6819866567828021
Precision  : 0.7064994298745724
Area Under Curve:    0.7237459846800098
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5901 - accuracy: 0.6814 - val_loss: 0.5475 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7223 - val_loss: 0.5406 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7334 - val_loss: 0.5420 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7406 - val_loss: 0.5368 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7496 - val_loss: 0.5389 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7583 - val_loss: 0.5467 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.7670 - val_loss: 0.5534 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4670 - accuracy: 0.7782
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4673 - accuracy: 0.7781 - val_loss: 0.5534 - val_accuracy: 0.7237 - lr: 0.0010
253/253 [==============================] - 0s 794us/step
Independent Testing Matthews Correlation:  0.46304362109846486
Confusion Matrix :
 [[2896 1151]
 [1023 3024]]
Accuracy on test set:    0.7314059797380776
Sensitivity:    0.7472201630837657 	 Specificity:    0.7155917963923895
Precision  : 0.724311377245509
Area Under Curve:    0.7314059797380775
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5911 - accuracy: 0.6840 - val_loss: 0.5551 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.7201 - val_loss: 0.5428 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5332 - accuracy: 0.7320 - val_loss: 0.5452 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7396 - val_loss: 0.5424 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5103 - accuracy: 0.7483 - val_loss: 0.5452 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7553 - val_loss: 0.5487 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4889 - accuracy: 0.7619 - val_loss: 0.5508 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.7717 - val_loss: 0.5595 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4641 - accuracy: 0.7783 - val_loss: 0.5555 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4498 - accuracy: 0.7897
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4496 - accuracy: 0.7897 - val_loss: 0.5679 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4825967201802383
Confusion Matrix :
 [[3017 1030]
 [1064 2983]]
Accuracy on test set:    0.7412898443291327
Sensitivity:    0.7370892018779343 	 Specificity:    0.7454904867803311
Precision  : 0.7433341639671069
Area Under Curve:    0.7412898443291327
(8094, 2560) (8094,)
Mean MCC = 0.4313 + 0.0247 and Mean AUC = 0.7152 + 0.0125
Mean Sensitivity = 0.7314 + 0.0321 and Mean Specificity = 0.6990 + 0.0291 and Mean Accuracy = 0.7152 + 0.0125
Mean Precision = 0.7090 + 0.0155





Seed   : 381237
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5825 - accuracy: 0.6903 - val_loss: 0.5580 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5400 - accuracy: 0.7249 - val_loss: 0.5590 - val_accuracy: 0.7058 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5249 - accuracy: 0.7349 - val_loss: 0.5537 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5119 - accuracy: 0.7461 - val_loss: 0.5492 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7540 - val_loss: 0.5480 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4887 - accuracy: 0.7631 - val_loss: 0.5499 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.7704 - val_loss: 0.5564 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4648 - accuracy: 0.7780 - val_loss: 0.5636 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4512 - accuracy: 0.7867 - val_loss: 0.5667 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4383 - accuracy: 0.7952
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4385 - accuracy: 0.7951 - val_loss: 0.5644 - val_accuracy: 0.7109 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4060186457967461
Confusion Matrix :
 [[2620 1428]
 [ 986 3061]]
Accuracy on test set:    0.7017912291537987
Sensitivity:    0.7563627378304917 	 Specificity:    0.6472332015810277
Precision  : 0.6818890621519269
Area Under Curve:    0.7017979697057596
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5859 - accuracy: 0.6869 - val_loss: 0.5596 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7252 - val_loss: 0.5479 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5263 - accuracy: 0.7368 - val_loss: 0.5573 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5150 - accuracy: 0.7425 - val_loss: 0.5461 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7502 - val_loss: 0.5532 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7583 - val_loss: 0.5525 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.7683 - val_loss: 0.5527 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4693 - accuracy: 0.7766 - val_loss: 0.5527 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4559 - accuracy: 0.7840 - val_loss: 0.5568 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4434 - accuracy: 0.7931 - val_loss: 0.5659 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4312 - accuracy: 0.7984 - val_loss: 0.5614 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4169 - accuracy: 0.8094 - val_loss: 0.5740 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4055 - accuracy: 0.8139 - val_loss: 0.5836 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 14/400
249/257 [============================>.] - ETA: 0s - loss: 0.3928 - accuracy: 0.8211
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3932 - accuracy: 0.8208 - val_loss: 0.5861 - val_accuracy: 0.7130 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4074288998705783
Confusion Matrix :
 [[2902 1146]
 [1253 2794]]
Accuracy on test set:    0.7036442248301421
Sensitivity:    0.6903879416851989 	 Specificity:    0.716897233201581
Precision  : 0.7091370558375635
Area Under Curve:    0.70364258744339
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5883 - accuracy: 0.6846 - val_loss: 0.5492 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7212 - val_loss: 0.5398 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7330 - val_loss: 0.5414 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7424 - val_loss: 0.5403 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7500 - val_loss: 0.5380 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7582 - val_loss: 0.5408 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7656 - val_loss: 0.5427 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.7739 - val_loss: 0.5461 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4606 - accuracy: 0.7815 - val_loss: 0.5463 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4494 - accuracy: 0.7883 - val_loss: 0.5530 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4376 - accuracy: 0.7980 - val_loss: 0.5534 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4259 - accuracy: 0.8043 - val_loss: 0.5680 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 13/400
251/257 [============================>.] - ETA: 0s - loss: 0.4149 - accuracy: 0.8108
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4147 - accuracy: 0.8110 - val_loss: 0.5658 - val_accuracy: 0.7179 - lr: 0.0010
253/253 [==============================] - 0s 958us/step
Independent Testing Matthews Correlation:  0.4179300270459819
Confusion Matrix :
 [[2850 1197]
 [1159 2889]]
Accuracy on test set:    0.7089561457689932
Sensitivity:    0.7136857707509882 	 Specificity:    0.704225352112676
Precision  : 0.7070484581497798
Area Under Curve:    0.708955561431832
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5885 - accuracy: 0.6831 - val_loss: 0.5465 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7230 - val_loss: 0.5385 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7324 - val_loss: 0.5353 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7407 - val_loss: 0.5408 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7474 - val_loss: 0.5349 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7565 - val_loss: 0.5380 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.7633 - val_loss: 0.5358 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4770 - accuracy: 0.7714 - val_loss: 0.5446 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7791 - val_loss: 0.5431 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4525 - accuracy: 0.7872
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4529 - accuracy: 0.7869 - val_loss: 0.5484 - val_accuracy: 0.7256 - lr: 0.0010
253/253 [==============================] - 0s 774us/step
Independent Testing Matthews Correlation:  0.4207951855798853
Confusion Matrix :
 [[2643 1404]
 [ 951 3097]]
Accuracy on test set:    0.7090796788140827
Sensitivity:    0.7650691699604744 	 Specificity:    0.6530763528539659
Precision  : 0.688069317929349
Area Under Curve:    0.7090727614072202
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5840 - accuracy: 0.6870 - val_loss: 0.5496 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7235 - val_loss: 0.5462 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7350 - val_loss: 0.5455 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7427 - val_loss: 0.5460 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7516 - val_loss: 0.5450 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7581 - val_loss: 0.5472 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4802 - accuracy: 0.7693 - val_loss: 0.5469 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7747 - val_loss: 0.5597 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4562 - accuracy: 0.7841 - val_loss: 0.5604 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 10/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4412 - accuracy: 0.7934
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7928 - val_loss: 0.5625 - val_accuracy: 0.7150 - lr: 0.0010
253/253 [==============================] - 0s 906us/step
Independent Testing Matthews Correlation:  0.43464299846741794
Confusion Matrix :
 [[2902 1145]
 [1143 2904]]
Accuracy on test set:    0.717321472695824
Sensitivity:    0.7175685693106004 	 Specificity:    0.7170743760810477
Precision  : 0.7172141269449247
Area Under Curve:    0.717321472695824
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5894 - accuracy: 0.6822 - val_loss: 0.5540 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7238 - val_loss: 0.5507 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7352 - val_loss: 0.5435 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7434 - val_loss: 0.5444 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5034 - accuracy: 0.7516 - val_loss: 0.5507 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4893 - accuracy: 0.7614 - val_loss: 0.5530 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4749 - accuracy: 0.7715 - val_loss: 0.5518 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4613 - accuracy: 0.7807 - val_loss: 0.5576 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4479 - accuracy: 0.7880 - val_loss: 0.5650 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4341 - accuracy: 0.7980 - val_loss: 0.5746 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4202 - accuracy: 0.8067 - val_loss: 0.5834 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4084 - accuracy: 0.8121
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4087 - accuracy: 0.8118 - val_loss: 0.5849 - val_accuracy: 0.7146 - lr: 0.0010
253/253 [==============================] - 0s 744us/step
Independent Testing Matthews Correlation:  0.41733176478302036
Confusion Matrix :
 [[2770 1277]
 [1083 2964]]
Accuracy on test set:    0.7084259945638745
Sensitivity:    0.7323943661971831 	 Specificity:    0.6844576229305659
Precision  : 0.6988917708087715
Area Under Curve:    0.7084259945638745
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6849 - val_loss: 0.5505 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7228 - val_loss: 0.5452 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7328 - val_loss: 0.5417 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7390 - val_loss: 0.5472 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7491 - val_loss: 0.5435 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7556 - val_loss: 0.5455 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7627 - val_loss: 0.5468 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4763 - accuracy: 0.7715 - val_loss: 0.5500 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4638 - accuracy: 0.7797 - val_loss: 0.5559 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4555 - accuracy: 0.7859 - val_loss: 0.5561 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 11/400

257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7938 - val_loss: 0.5622 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4312 - accuracy: 0.8010 - val_loss: 0.5704 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4229 - accuracy: 0.8045 - val_loss: 0.5642 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 14/400
256/257 [============================>.] - ETA: 0s - loss: 0.4095 - accuracy: 0.8127
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4095 - accuracy: 0.8127 - val_loss: 0.5860 - val_accuracy: 0.7209 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.425266568517139
Confusion Matrix :
 [[2900 1147]
 [1179 2868]]
Accuracy on test set:    0.7126266370150729
Sensitivity:    0.7086730911786508 	 Specificity:    0.7165801828514949
Precision  : 0.714321295143213
Area Under Curve:    0.7126266370150729
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5851 - accuracy: 0.6857 - val_loss: 0.5476 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7224 - val_loss: 0.5460 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7336 - val_loss: 0.5485 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7423 - val_loss: 0.5500 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7503 - val_loss: 0.5456 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4922 - accuracy: 0.7607
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7594 - val_loss: 0.5465 - val_accuracy: 0.7193 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4399383709559223
Confusion Matrix :
 [[2869 1178]
 [1089 2958]]
Accuracy on test set:    0.719915987150976
Sensitivity:    0.7309117865085248 	 Specificity:    0.7089201877934272
Precision  : 0.715183752417795
Area Under Curve:    0.7199159871509762
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5915 - accuracy: 0.6809 - val_loss: 0.5535 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5485 - accuracy: 0.7203 - val_loss: 0.5441 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5337 - accuracy: 0.7292 - val_loss: 0.5420 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5222 - accuracy: 0.7389 - val_loss: 0.5481 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5122 - accuracy: 0.7467 - val_loss: 0.5437 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5019 - accuracy: 0.7517 - val_loss: 0.5472 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4905 - accuracy: 0.7597 - val_loss: 0.5513 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7671 - val_loss: 0.5550 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4666 - accuracy: 0.7774 - val_loss: 0.5606 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4539 - accuracy: 0.7848 - val_loss: 0.5667 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4421 - accuracy: 0.7928 - val_loss: 0.5678 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4292 - accuracy: 0.7999 - val_loss: 0.5716 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 13/400
254/257 [============================>.] - ETA: 0s - loss: 0.4147 - accuracy: 0.8081
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4149 - accuracy: 0.8081 - val_loss: 0.5777 - val_accuracy: 0.7097 - lr: 0.0010
253/253 [==============================] - 0s 829us/step
Independent Testing Matthews Correlation:  0.448498100892405
Confusion Matrix :
 [[2913 1134]
 [1098 2949]]
Accuracy on test set:    0.7242401779095626
Sensitivity:    0.7286879169755375 	 Specificity:    0.7197924388435878
Precision  : 0.7222630418809699
Area Under Curve:    0.7242401779095627
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5907 - accuracy: 0.6795 - val_loss: 0.5500 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7207 - val_loss: 0.5508 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5331 - accuracy: 0.7296 - val_loss: 0.5483 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7414 - val_loss: 0.5441 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7498 - val_loss: 0.5508 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7581 - val_loss: 0.5516 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.7667 - val_loss: 0.5532 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4700 - accuracy: 0.7769 - val_loss: 0.5622 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4568 - accuracy: 0.7850 - val_loss: 0.5617 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4440 - accuracy: 0.7926 - val_loss: 0.5685 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4299 - accuracy: 0.8004 - val_loss: 0.5698 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4156 - accuracy: 0.8115 - val_loss: 0.5787 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4058 - accuracy: 0.8169 - val_loss: 0.5873 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3906 - accuracy: 0.8244 - val_loss: 0.5992 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3807 - accuracy: 0.8300 - val_loss: 0.6028 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3675 - accuracy: 0.8367 - val_loss: 0.6205 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 17/400
257/257 [==============================] - ETA: 0s - loss: 0.3540 - accuracy: 0.8435
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3540 - accuracy: 0.8435 - val_loss: 0.6185 - val_accuracy: 0.7091 - lr: 0.0010
253/253 [==============================] - 0s 852us/step
Independent Testing Matthews Correlation:  0.4463838584315087
Confusion Matrix :
 [[3082  965]
 [1281 2766]]
Accuracy on test set:    0.722510501606128
Sensitivity:    0.6834692364714603 	 Specificity:    0.7615517667407956
Precision  : 0.741356204770839
Area Under Curve:    0.722510501606128
(8094, 2560) (8094,)
Mean MCC = 0.4264 + 0.0145 and Mean AUC = 0.7129 + 0.0074
Mean Sensitivity = 0.7227 + 0.0245 and Mean Specificity = 0.7030 + 0.0320 and Mean Accuracy = 0.7129 + 0.0074
Mean Precision = 0.7095 + 0.0162





Seed   : 941090

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5853 - accuracy: 0.6855 - val_loss: 0.5650 - val_accuracy: 0.6991 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5410 - accuracy: 0.7259 - val_loss: 0.5526 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5267 - accuracy: 0.7352 - val_loss: 0.5535 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7466 - val_loss: 0.5499 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5019 - accuracy: 0.7533 - val_loss: 0.5528 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 3ms/step - loss: 0.4890 - accuracy: 0.7619 - val_loss: 0.5572 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.7710 - val_loss: 0.5645 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4653 - accuracy: 0.7780
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4649 - accuracy: 0.7782 - val_loss: 0.5619 - val_accuracy: 0.7135 - lr: 0.0010
253/253 [==============================] - 0s 954us/step
Independent Testing Matthews Correlation:  0.4237041402764869
Confusion Matrix :
 [[2690 1358]
 [ 982 3065]]
Accuracy on test set:    0.7109326744904262
Sensitivity:    0.7573511242895973 	 Specificity:    0.6645256916996047
Precision  : 0.6929685733664933
Area Under Curve:    0.710938407994601
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5878 - accuracy: 0.6843 - val_loss: 0.5602 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5446 - accuracy: 0.7235 - val_loss: 0.5514 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7347 - val_loss: 0.5521 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7418 - val_loss: 0.5513 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7480 - val_loss: 0.5517 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7574 - val_loss: 0.5552 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7669 - val_loss: 0.5560 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 3ms/step - loss: 0.4730 - accuracy: 0.7743 - val_loss: 0.5504 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4612 - accuracy: 0.7817
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4611 - accuracy: 0.7816 - val_loss: 0.5725 - val_accuracy: 0.7102 - lr: 0.0010
253/253 [==============================] - 0s 855us/step
Independent Testing Matthews Correlation:  0.42975891990224174
Confusion Matrix :
 [[2604 1444]
 [ 881 3166]]
Accuracy on test set:    0.7127856701667696
Sensitivity:    0.7823078823820113 	 Specificity:    0.6432806324110671
Precision  : 0.6867678958785249
Area Under Curve:    0.7127942573965392
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5863 - accuracy: 0.6847 - val_loss: 0.5507 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7215 - val_loss: 0.5421 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7339 - val_loss: 0.5423 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7433 - val_loss: 0.5406 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7511 - val_loss: 0.5425 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7593 - val_loss: 0.5431 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7656 - val_loss: 0.5464 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.7743 - val_loss: 0.5552 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4578 - accuracy: 0.7821 - val_loss: 0.5525 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4450 - accuracy: 0.7908
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4450 - accuracy: 0.7909 - val_loss: 0.5683 - val_accuracy: 0.7135 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4232176222735592
Confusion Matrix :
 [[2731 1316]
 [1023 3025]]
Accuracy on test set:    0.7110562075355158
Sensitivity:    0.7472826086956522 	 Specificity:    0.6748208549542871
Precision  : 0.6968440451508869
Area Under Curve:    0.7110517318249697
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5912 - accuracy: 0.6818 - val_loss: 0.5516 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7208 - val_loss: 0.5405 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7298 - val_loss: 0.5397 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7373 - val_loss: 0.5406 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5135 - accuracy: 0.7435 - val_loss: 0.5547 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5034 - accuracy: 0.7505 - val_loss: 0.5473 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7583 - val_loss: 0.5426 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7654 - val_loss: 0.5458 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7731 - val_loss: 0.5460 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4608 - accuracy: 0.7815 - val_loss: 0.5477 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4481 - accuracy: 0.7883 - val_loss: 0.5550 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4361 - accuracy: 0.7965 - val_loss: 0.5691 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 13/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4248 - accuracy: 0.8036
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4247 - accuracy: 0.8032 - val_loss: 0.5659 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 793us/step
Independent Testing Matthews Correlation:  0.42610292468432337
Confusion Matrix :
 [[2912 1135]
 [1188 2860]]
Accuracy on test set:    0.7130327362569487
Sensitivity:    0.7065217391304348 	 Specificity:    0.7195453422288115
Precision  : 0.7158948685857321
Area Under Curve:    0.7130335406796231
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5840 - accuracy: 0.6872 - val_loss: 0.5509 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7231 - val_loss: 0.5464 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7329 - val_loss: 0.5439 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7410 - val_loss: 0.5622 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7484 - val_loss: 0.5478 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.7552 - val_loss: 0.5518 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7620 - val_loss: 0.5480 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4776 - accuracy: 0.7702
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4776 - accuracy: 0.7702 - val_loss: 0.5506 - val_accuracy: 0.7179 - lr: 0.0010
253/253 [==============================] - 0s 974us/step
Independent Testing Matthews Correlation:  0.4094488906501285
Confusion Matrix :
 [[2866 1181]
 [1209 2838]]
Accuracy on test set:    0.7047195453422288
Sensitivity:    0.7012601927353596 	 Specificity:    0.708178897949098
Precision  : 0.7061458074147798
Area Under Curve:    0.7047195453422289
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5871 - accuracy: 0.6847 - val_loss: 0.5582 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7218 - val_loss: 0.5480 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7327 - val_loss: 0.5471 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7413 - val_loss: 0.5473 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7519 - val_loss: 0.5475 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4918 - accuracy: 0.7603 - val_loss: 0.5486 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4791 - accuracy: 0.7700
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7696 - val_loss: 0.5502 - val_accuracy: 0.7116 - lr: 0.0010
253/253 [==============================] - 0s 920us/step
Independent Testing Matthews Correlation:  0.4348832349133437
Confusion Matrix :
 [[2749 1298]
 [ 994 3053]]
Accuracy on test set:    0.7168272794662713
Sensitivity:    0.7543859649122807 	 Specificity:    0.679268594020262
Precision  : 0.7016777752240864
Area Under Curve:    0.7168272794662712
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5867 - accuracy: 0.6844 - val_loss: 0.5506 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7220 - val_loss: 0.5437 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7317 - val_loss: 0.5410 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7405 - val_loss: 0.5416 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7475 - val_loss: 0.5411 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7566 - val_loss: 0.5425 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4876 - accuracy: 0.7641 - val_loss: 0.5480 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7736 - val_loss: 0.5491 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4632 - accuracy: 0.7809 - val_loss: 0.5510 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4512 - accuracy: 0.7890 - val_loss: 0.5578 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4405 - accuracy: 0.7953
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4404 - accuracy: 0.7953 - val_loss: 0.5630 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40937749392468314
Confusion Matrix :
 [[2758 1289]
 [1103 2944]]
Accuracy on test set:    0.7044724487274524
Sensitivity:    0.7274524339016556 	 Specificity:    0.6814924635532493
Precision  : 0.695487833687692
Area Under Curve:    0.7044724487274524
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5875 - accuracy: 0.6852 - val_loss: 0.5518 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7228 - val_loss: 0.5479 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7328 - val_loss: 0.5412 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7400 - val_loss: 0.5407 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7497 - val_loss: 0.5480 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7571 - val_loss: 0.5454 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7650 - val_loss: 0.5456 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4716 - accuracy: 0.7744 - val_loss: 0.5469 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4602 - accuracy: 0.7824 - val_loss: 0.5552 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4470 - accuracy: 0.7899 - val_loss: 0.5542 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4342 - accuracy: 0.7971 - val_loss: 0.5622 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4227 - accuracy: 0.8054
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4233 - accuracy: 0.8051 - val_loss: 0.5668 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 883us/step
Independent Testing Matthews Correlation:  0.4215886428558039
Confusion Matrix :
 [[2848 1199]
 [1142 2905]]
Accuracy on test set:    0.7107734124042501
Sensitivity:    0.7178156659253768 	 Specificity:    0.7037311588831233
Precision  : 0.7078460038986355
Area Under Curve:    0.7107734124042502
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5914 - accuracy: 0.6801 - val_loss: 0.5521 - val_accuracy: 0.7198 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7217 - val_loss: 0.5454 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7316 - val_loss: 0.5436 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7400 - val_loss: 0.5434 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7470 - val_loss: 0.5460 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4987 - accuracy: 0.7570 - val_loss: 0.5446 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4866 - accuracy: 0.7649 - val_loss: 0.5487 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4767 - accuracy: 0.7720 - val_loss: 0.5521 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4630 - accuracy: 0.7815 - val_loss: 0.5536 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4495 - accuracy: 0.7905 - val_loss: 0.5621 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 11/400
256/257 [============================>.] - ETA: 0s - loss: 0.4376 - accuracy: 0.7967
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4376 - accuracy: 0.7967 - val_loss: 0.5602 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4426323080670168
Confusion Matrix :
 [[3086  961]
 [1301 2746]]
Accuracy on test set:    0.720533728687917
Sensitivity:    0.6785273041759328 	 Specificity:    0.7625401531999012
Precision  : 0.7407607229565687
Area Under Curve:    0.720533728687917
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5898 - accuracy: 0.6807 - val_loss: 0.5553 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.7207 - val_loss: 0.5511 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7316 - val_loss: 0.5447 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5223 - accuracy: 0.7377 - val_loss: 0.5436 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7463 - val_loss: 0.5426 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5008 - accuracy: 0.7546 - val_loss: 0.5464 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7593 - val_loss: 0.5462 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7691 - val_loss: 0.5477 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4698 - accuracy: 0.7758 - val_loss: 0.5493 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.7854 - val_loss: 0.5538 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4416 - accuracy: 0.7955 - val_loss: 0.5615 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 12/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4293 - accuracy: 0.8019
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4301 - accuracy: 0.8013 - val_loss: 0.5622 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 962us/step
Independent Testing Matthews Correlation:  0.48174612145711027
Confusion Matrix :
 [[3102  945]
 [1155 2892]]
Accuracy on test set:    0.7405485544848036
Sensitivity:    0.7146034099332839 	 Specificity:    0.7664936990363233
Precision  : 0.7537138389366693
Area Under Curve:    0.7405485544848035
(8094, 2560) (8094,)
Mean MCC = 0.4302 + 0.0197 and Mean AUC = 0.7146 + 0.0098
Mean Sensitivity = 0.7288 + 0.0296 and Mean Specificity = 0.7004 + 0.0383 and Mean Accuracy = 0.7146 + 0.0098
Mean Precision = 0.7098 + 0.0205





Seed   : 220344
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5868 - accuracy: 0.6838 - val_loss: 0.5666 - val_accuracy: 0.7049 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7244 - val_loss: 0.5530 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7351 - val_loss: 0.5523 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.7444 - val_loss: 0.5535 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7509 - val_loss: 0.5563 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7599 - val_loss: 0.5563 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7682 - val_loss: 0.5595 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7774 - val_loss: 0.5721 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4553 - accuracy: 0.7856 - val_loss: 0.5718 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4412 - accuracy: 0.7946 - val_loss: 0.5831 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 11/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4273 - accuracy: 0.8031
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4286 - accuracy: 0.8025 - val_loss: 0.5800 - val_accuracy: 0.7045 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4089051180174466
Confusion Matrix :
 [[2800 1248]
 [1145 2902]]
Accuracy on test set:    0.7043854231006794
Sensitivity:    0.7170743760810477 	 Specificity:    0.691699604743083
Precision  : 0.6992771084337349
Area Under Curve:    0.7043869904120654
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5927 - accuracy: 0.6771 - val_loss: 0.5619 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7231 - val_loss: 0.5599 - val_accuracy: 0.7039 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7336 - val_loss: 0.5526 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7408 - val_loss: 0.5576 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7495 - val_loss: 0.5526 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7550 - val_loss: 0.5538 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4876 - accuracy: 0.7637 - val_loss: 0.5585 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4740 - accuracy: 0.7741 - val_loss: 0.5575 - val_accuracy: 0.7141 - lr: 0.0010

Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4615 - accuracy: 0.7800 - val_loss: 0.5692 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4480 - accuracy: 0.7898 - val_loss: 0.5684 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4359 - accuracy: 0.7957 - val_loss: 0.5748 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4238 - accuracy: 0.8038 - val_loss: 0.5889 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 13/400
250/257 [============================>.] - ETA: 0s - loss: 0.4109 - accuracy: 0.8127
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4108 - accuracy: 0.8127 - val_loss: 0.5905 - val_accuracy: 0.7068 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4108189475913826
Confusion Matrix :
 [[2594 1454]
 [ 944 3103]]
Accuracy on test set:    0.7037677578752316
Sensitivity:    0.7667407956510995 	 Specificity:    0.6408102766798419
Precision  : 0.6809304366908053
Area Under Curve:    0.7037755361654707
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5856 - accuracy: 0.6851 - val_loss: 0.5566 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5422 - accuracy: 0.7238 - val_loss: 0.5436 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5263 - accuracy: 0.7366 - val_loss: 0.5411 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5139 - accuracy: 0.7449 - val_loss: 0.5434 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5010 - accuracy: 0.7533 - val_loss: 0.5404 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7610 - val_loss: 0.5470 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.7697 - val_loss: 0.5483 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4633 - accuracy: 0.7798 - val_loss: 0.5535 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4519 - accuracy: 0.7873 - val_loss: 0.5577 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4392 - accuracy: 0.7957 - val_loss: 0.5663 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4249 - accuracy: 0.8032 - val_loss: 0.5651 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4114 - accuracy: 0.8126 - val_loss: 0.5745 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 13/400
253/257 [============================>.] - ETA: 0s - loss: 0.3991 - accuracy: 0.8169
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3991 - accuracy: 0.8169 - val_loss: 0.5878 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 933us/step
Independent Testing Matthews Correlation:  0.40023326208223886
Confusion Matrix :
 [[2587 1460]
 [ 979 3069]]
Accuracy on test set:    0.6987029030265596
Sensitivity:    0.7581521739130435 	 Specificity:    0.6392389424264887
Precision  : 0.677633031574299
Area Under Curve:    0.6986955581697661
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5925 - accuracy: 0.6800 - val_loss: 0.5535 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5484 - accuracy: 0.7203 - val_loss: 0.5410 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7316 - val_loss: 0.5382 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5204 - accuracy: 0.7393 - val_loss: 0.5391 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7477 - val_loss: 0.5417 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4991 - accuracy: 0.7563 - val_loss: 0.5392 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7650 - val_loss: 0.5421 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4736 - accuracy: 0.7755 - val_loss: 0.5463 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4618 - accuracy: 0.7822 - val_loss: 0.5532 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4503 - accuracy: 0.7886 - val_loss: 0.5509 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 11/400
254/257 [============================>.] - ETA: 0s - loss: 0.4385 - accuracy: 0.7966
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4387 - accuracy: 0.7963 - val_loss: 0.5576 - val_accuracy: 0.7235 - lr: 0.0010
253/253 [==============================] - 0s 985us/step
Independent Testing Matthews Correlation:  0.41047455095242597
Confusion Matrix :
 [[2640 1407]
 [ 988 3060]]
Accuracy on test set:    0.7041383570105003
Sensitivity:    0.7559288537549407 	 Specificity:    0.6523350630096367
Precision  : 0.6850235057085292
Area Under Curve:    0.7041319583822887
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5885 - accuracy: 0.6843 - val_loss: 0.5543 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7218 - val_loss: 0.5413 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7345 - val_loss: 0.5409 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7400 - val_loss: 0.5374 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7502 - val_loss: 0.5453 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7569 - val_loss: 0.5402 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
252/257 [============================>.] - ETA: 0s - loss: 0.4840 - accuracy: 0.7670
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7668 - val_loss: 0.5392 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 996us/step
Independent Testing Matthews Correlation:  0.44502540506548505
Confusion Matrix :
 [[2915 1132]
 [1114 2933]]
Accuracy on test set:    0.722510501606128
Sensitivity:    0.7247343711391154 	 Specificity:    0.7202866320731406
Precision  : 0.7215252152521525
Area Under Curve:    0.7225105016061281
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5859 - accuracy: 0.6867 - val_loss: 0.5489 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7233 - val_loss: 0.5416 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7321 - val_loss: 0.5397 - val_accuracy: 0.7216 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5210 - accuracy: 0.7391 - val_loss: 0.5391 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5116 - accuracy: 0.7459 - val_loss: 0.5406 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7546 - val_loss: 0.5434 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7615 - val_loss: 0.5499 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4792 - accuracy: 0.7695 - val_loss: 0.5464 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4653 - accuracy: 0.7793 - val_loss: 0.5483 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4523 - accuracy: 0.7872
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4531 - accuracy: 0.7865 - val_loss: 0.5511 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4196241794969865
Confusion Matrix :
 [[2840 1207]
 [1142 2905]]
Accuracy on test set:    0.7097850259451446
Sensitivity:    0.7178156659253768 	 Specificity:    0.7017543859649122
Precision  : 0.7064688715953308
Area Under Curve:    0.7097850259451446
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5881 - accuracy: 0.6844 - val_loss: 0.5566 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7226 - val_loss: 0.5417 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7313 - val_loss: 0.5406 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7388 - val_loss: 0.5405 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7496 - val_loss: 0.5414 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4987 - accuracy: 0.7547 - val_loss: 0.5442 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4896 - accuracy: 0.7600 - val_loss: 0.5439 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4781 - accuracy: 0.7698
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7694 - val_loss: 0.5475 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4290508356524693
Confusion Matrix :
 [[2730 1317]
 [ 999 3048]]
Accuracy on test set:    0.7138621200889548
Sensitivity:    0.7531504818383988 	 Specificity:    0.6745737583395107
Precision  : 0.6982817869415807
Area Under Curve:    0.7138621200889549
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5871 - accuracy: 0.6843 - val_loss: 0.5483 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7223 - val_loss: 0.5414 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7331 - val_loss: 0.5435 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7385 - val_loss: 0.5411 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.7468 - val_loss: 0.5420 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
254/257 [============================>.] - ETA: 0s - loss: 0.5004 - accuracy: 0.7546
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.7544 - val_loss: 0.5415 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 790us/step
Independent Testing Matthews Correlation:  0.43553649025400576
Confusion Matrix :
 [[2851 1196]
 [1089 2958]]
Accuracy on test set:    0.7176921176179887
Sensitivity:    0.7309117865085248 	 Specificity:    0.7044724487274524
Precision  : 0.7120847376023111
Area Under Curve:    0.7176921176179887
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6831 - val_loss: 0.5503 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7202 - val_loss: 0.5476 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7339 - val_loss: 0.5422 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7426 - val_loss: 0.5428 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7534 - val_loss: 0.5404 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7619 - val_loss: 0.5435 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7685 - val_loss: 0.5492 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4677 - accuracy: 0.7767 - val_loss: 0.5546 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4533 - accuracy: 0.7869 - val_loss: 0.5534 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4401 - accuracy: 0.7952
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4402 - accuracy: 0.7951 - val_loss: 0.5701 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 1s 4ms/step
Independent Testing Matthews Correlation:  0.45701475841317196
Confusion Matrix :
 [[2775 1272]
 [ 932 3115]]
Accuracy on test set:    0.7276995305164319
Sensitivity:    0.7697059550284161 	 Specificity:    0.6856931060044478
Precision  : 0.71005242762708
Area Under Curve:    0.727699530516432
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5943 - accuracy: 0.6793 - val_loss: 0.5557 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5525 - accuracy: 0.7177 - val_loss: 0.5443 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5351 - accuracy: 0.7316 - val_loss: 0.5395 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5219 - accuracy: 0.7397 - val_loss: 0.5420 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7472 - val_loss: 0.5396 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4986 - accuracy: 0.7556 - val_loss: 0.5441 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7640 - val_loss: 0.5526 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4752 - accuracy: 0.7721 - val_loss: 0.5515 - val_accuracy: 0.7223 - lr: 0.0010

Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4613 - accuracy: 0.7807 - val_loss: 0.5624 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4500 - accuracy: 0.7890
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4500 - accuracy: 0.7887 - val_loss: 0.5610 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46722826831302444
Confusion Matrix :
 [[3079  968]
 [1191 2856]]
Accuracy on test set:    0.7332592043489005
Sensitivity:    0.7057079318013343 	 Specificity:    0.7608104768964665
Precision  : 0.7468619246861925
Area Under Curve:    0.7332592043489004
(8094, 2560) (8094,)
Mean MCC = 0.4284 + 0.0213 and Mean AUC = 0.7136 + 0.0109
Mean Sensitivity = 0.7400 + 0.0221 and Mean Specificity = 0.6872 + 0.0359 and Mean Accuracy = 0.7136 + 0.0109
Mean Precision = 0.7038 + 0.0197





Seed   : 106908
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5819 - accuracy: 0.6876 - val_loss: 0.5614 - val_accuracy: 0.7054 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7262 - val_loss: 0.5569 - val_accuracy: 0.7023 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5242 - accuracy: 0.7361 - val_loss: 0.5507 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5129 - accuracy: 0.7448 - val_loss: 0.5557 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5022 - accuracy: 0.7525 - val_loss: 0.5613 - val_accuracy: 0.7003 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7608 - val_loss: 0.5610 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4779 - accuracy: 0.7694 - val_loss: 0.5599 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4664 - accuracy: 0.7779 - val_loss: 0.5656 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4548 - accuracy: 0.7864 - val_loss: 0.5745 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4431 - accuracy: 0.7954 - val_loss: 0.5735 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4298 - accuracy: 0.8023 - val_loss: 0.5753 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4170 - accuracy: 0.8107 - val_loss: 0.5843 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 13/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4049 - accuracy: 0.8154
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4054 - accuracy: 0.8150 - val_loss: 0.5931 - val_accuracy: 0.7019 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3934343372851003
Confusion Matrix :
 [[2942 1106]
 [1352 2695]]
Accuracy on test set:    0.6963557751698579
Sensitivity:    0.6659253768223375 	 Specificity:    0.7267786561264822
Precision  : 0.7090239410681399
Area Under Curve:    0.6963520164744098
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5844 - accuracy: 0.6878 - val_loss: 0.5605 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5400 - accuracy: 0.7259 - val_loss: 0.5543 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5250 - accuracy: 0.7363 - val_loss: 0.5544 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7452 - val_loss: 0.5492 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7529 - val_loss: 0.5525 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7624 - val_loss: 0.5536 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.7680 - val_loss: 0.5612 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4698 - accuracy: 0.7752 - val_loss: 0.5565 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 9/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4558 - accuracy: 0.7855
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4568 - accuracy: 0.7851 - val_loss: 0.5643 - val_accuracy: 0.7111 - lr: 0.0010
253/253 [==============================] - 0s 787us/step
Independent Testing Matthews Correlation:  0.40432364164762497
Confusion Matrix :
 [[2843 1205]
 [1206 2841]]
Accuracy on test set:    0.7021618282890674
Sensitivity:    0.7020014825796886 	 Specificity:    0.7023221343873518
Precision  : 0.7021749876421157
Area Under Curve:    0.7021618084835203
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5865 - accuracy: 0.6862 - val_loss: 0.5530 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7235 - val_loss: 0.5491 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7338 - val_loss: 0.5429 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7396 - val_loss: 0.5402 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7484 - val_loss: 0.5401 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7590 - val_loss: 0.5481 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4836 - accuracy: 0.7649 - val_loss: 0.5462 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7743 - val_loss: 0.5469 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4583 - accuracy: 0.7840 - val_loss: 0.5539 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4464 - accuracy: 0.7926 - val_loss: 0.5546 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4324 - accuracy: 0.8001 - val_loss: 0.5604 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4207 - accuracy: 0.8077 - val_loss: 0.5693 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4077 - accuracy: 0.8148 - val_loss: 0.5670 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3954 - accuracy: 0.8226 - val_loss: 0.5831 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 15/400
256/257 [============================>.] - ETA: 0s - loss: 0.3841 - accuracy: 0.8294
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3841 - accuracy: 0.8294 - val_loss: 0.5844 - val_accuracy: 0.7146 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41990136837658015
Confusion Matrix :
 [[2857 1190]
 [1158 2890]]
Accuracy on test set:    0.7099444101297097
Sensitivity:    0.7139328063241107 	 Specificity:    0.7059550284161107
Precision  : 0.7083333333333334
Area Under Curve:    0.7099439173701108
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5845 - accuracy: 0.6869 - val_loss: 0.5556 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7242 - val_loss: 0.5462 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5260 - accuracy: 0.7355 - val_loss: 0.5411 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7443 - val_loss: 0.5455 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5024 - accuracy: 0.7539 - val_loss: 0.5375 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4899 - accuracy: 0.7608 - val_loss: 0.5429 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7721 - val_loss: 0.5428 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4630 - accuracy: 0.7812 - val_loss: 0.5441 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4506 - accuracy: 0.7880 - val_loss: 0.5577 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4362 - accuracy: 0.7982 - val_loss: 0.5534 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4256 - accuracy: 0.8042 - val_loss: 0.5588 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4132 - accuracy: 0.8108 - val_loss: 0.5717 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 13/400
256/257 [============================>.] - ETA: 0s - loss: 0.3987 - accuracy: 0.8193
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3987 - accuracy: 0.8193 - val_loss: 0.5844 - val_accuracy: 0.7152 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.3992562339429849
Confusion Matrix :
 [[2917 1130]
 [1303 2745]]
Accuracy on test set:    0.699444101297097
Sensitivity:    0.6781126482213439 	 Specificity:    0.7207808253026934
Precision  : 0.7083870967741935
Area Under Curve:    0.6994467367620185
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5905 - accuracy: 0.6819 - val_loss: 0.5476 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7209 - val_loss: 0.5398 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7317 - val_loss: 0.5418 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5223 - accuracy: 0.7378 - val_loss: 0.5370 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.7440 - val_loss: 0.5360 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7517 - val_loss: 0.5372 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7566 - val_loss: 0.5434 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4857 - accuracy: 0.7656 - val_loss: 0.5431 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7726 - val_loss: 0.5475 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4630 - accuracy: 0.7803 - val_loss: 0.5432 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 11/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4522 - accuracy: 0.7879
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4530 - accuracy: 0.7875 - val_loss: 0.5475 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 827us/step
Independent Testing Matthews Correlation:  0.4166904552123679
Confusion Matrix :
 [[3025 1022]
 [1344 2703]]
Accuracy on test set:    0.7076847047195454
Sensitivity:    0.6679021497405485 	 Specificity:    0.7474672596985421
Precision  : 0.7256375838926175
Area Under Curve:    0.7076847047195454
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5935 - accuracy: 0.6780 - val_loss: 0.5507 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7197 - val_loss: 0.5415 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7314 - val_loss: 0.5377 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5245 - accuracy: 0.7354 - val_loss: 0.5380 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7457 - val_loss: 0.5386 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5033 - accuracy: 0.7522 - val_loss: 0.5402 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4922 - accuracy: 0.7608
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.7608 - val_loss: 0.5399 - val_accuracy: 0.7257 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43217219034012616
Confusion Matrix :
 [[2900 1147]
 [1151 2896]]
Accuracy on test set:    0.7160859896219421
Sensitivity:    0.7155917963923895 	 Specificity:    0.7165801828514949
Precision  : 0.716299777393025
Area Under Curve:    0.7160859896219421
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5966 - accuracy: 0.6755 - val_loss: 0.5516 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5488 - accuracy: 0.7199 - val_loss: 0.5402 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7303 - val_loss: 0.5407 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5225 - accuracy: 0.7386 - val_loss: 0.5392 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5118 - accuracy: 0.7450 - val_loss: 0.5460 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5022 - accuracy: 0.7529 - val_loss: 0.5408 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4905 - accuracy: 0.7596
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4907 - accuracy: 0.7595 - val_loss: 0.5408 - val_accuracy: 0.7255 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42875367617720755
Confusion Matrix :
 [[2919 1128]
 [1184 2863]]
Accuracy on test set:    0.7143563133185076
Sensitivity:    0.707437608104769 	 Specificity:    0.7212750185322461
Precision  : 0.7173640691556001
Area Under Curve:    0.7143563133185075
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5866 - accuracy: 0.6870 - val_loss: 0.5476 - val_accuracy: 0.7231 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7215 - val_loss: 0.5407 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5327 - accuracy: 0.7309 - val_loss: 0.5378 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7398 - val_loss: 0.5384 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5115 - accuracy: 0.7475 - val_loss: 0.5367 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7531 - val_loss: 0.5366 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7607 - val_loss: 0.5388 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7683 - val_loss: 0.5501 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4727 - accuracy: 0.7735 - val_loss: 0.5461 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4616 - accuracy: 0.7835 - val_loss: 0.5448 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4492 - accuracy: 0.7887
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4491 - accuracy: 0.7889 - val_loss: 0.5523 - val_accuracy: 0.7261 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4482813454592268
Confusion Matrix :
 [[2830 1217]
 [1018 3029]]
Accuracy on test set:    0.7238695329873981
Sensitivity:    0.7484556461576476 	 Specificity:    0.6992834198171485
Precision  : 0.7133772962788507
Area Under Curve:    0.7238695329873981
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5921 - accuracy: 0.6811 - val_loss: 0.5532 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5489 - accuracy: 0.7208 - val_loss: 0.5463 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5330 - accuracy: 0.7308 - val_loss: 0.5432 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5207 - accuracy: 0.7391 - val_loss: 0.5426 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7492 - val_loss: 0.5508 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7583 - val_loss: 0.5512 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4866 - accuracy: 0.7642 - val_loss: 0.5561 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4714 - accuracy: 0.7755
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7756 - val_loss: 0.5550 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4598470247129644
Confusion Matrix :
 [[2952 1095]
 [1091 2956]]
Accuracy on test set:    0.7299234000494194
Sensitivity:    0.730417593278972 	 Specificity:    0.7294292068198666
Precision  : 0.729696371266354
Area Under Curve:    0.7299234000494192
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5977 - accuracy: 0.6756 - val_loss: 0.5579 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5522 - accuracy: 0.7179 - val_loss: 0.5512 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5381 - accuracy: 0.7287 - val_loss: 0.5533 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5265 - accuracy: 0.7363 - val_loss: 0.5484 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7454 - val_loss: 0.5491 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5054 - accuracy: 0.7508 - val_loss: 0.5531 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.7600 - val_loss: 0.5547 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.7681 - val_loss: 0.5560 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4700 - accuracy: 0.7760 - val_loss: 0.5625 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4557 - accuracy: 0.7853
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4559 - accuracy: 0.7850 - val_loss: 0.5695 - val_accuracy: 0.7065 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4887959180598601
Confusion Matrix :
 [[3038 1009]
 [1060 2987]]
Accuracy on test set:    0.7443785520138374
Sensitivity:    0.7380775883370397 	 Specificity:    0.7506795156906351
Precision  : 0.7474974974974975
Area Under Curve:    0.7443785520138374
(8094, 2560) (8094,)
Mean MCC = 0.4291 + 0.0281 and Mean AUC = 0.7144 + 0.0141
Mean Sensitivity = 0.7068 + 0.0273 and Mean Specificity = 0.7221 + 0.0166 and Mean Accuracy = 0.7144 + 0.0141
Mean Precision = 0.7178 + 0.0127





Seed   : 391667
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5836 - accuracy: 0.6872 - val_loss: 0.5559 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7259 - val_loss: 0.5479 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7351 - val_loss: 0.5496 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5149 - accuracy: 0.7436 - val_loss: 0.5514 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7508 - val_loss: 0.5540 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7595 - val_loss: 0.5501 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7656 - val_loss: 0.5523 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4726 - accuracy: 0.7735 - val_loss: 0.5562 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.7820 - val_loss: 0.5578 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4457 - accuracy: 0.7906 - val_loss: 0.5640 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4315 - accuracy: 0.8003 - val_loss: 0.5743 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4195 - accuracy: 0.8061 - val_loss: 0.5778 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4093 - accuracy: 0.8136 - val_loss: 0.5861 - val_accuracy: 0.7095 - lr: 0.0010

Epoch 14/400
257/257 [==============================] - ETA: 0s - loss: 0.3965 - accuracy: 0.8210
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3965 - accuracy: 0.8210 - val_loss: 0.5966 - val_accuracy: 0.7073 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40210098406697925
Confusion Matrix :
 [[2834 1214]
 [1206 2841]]
Accuracy on test set:    0.7010500308832612
Sensitivity:    0.7020014825796886 	 Specificity:    0.700098814229249
Precision  : 0.700616522811344
Area Under Curve:    0.7010501484044689
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5867 - accuracy: 0.6840 - val_loss: 0.5565 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7236 - val_loss: 0.5508 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7340 - val_loss: 0.5488 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7426 - val_loss: 0.5474 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7488 - val_loss: 0.5475 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7554 - val_loss: 0.5477 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4851 - accuracy: 0.7668
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7669 - val_loss: 0.5528 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40203641403721463
Confusion Matrix :
 [[2931 1117]
 [1305 2742]]
Accuracy on test set:    0.7008029647930821
Sensitivity:    0.6775389177168273 	 Specificity:    0.7240612648221344
Precision  : 0.7105467737755895
Area Under Curve:    0.7008000912694808
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5848 - accuracy: 0.6878 - val_loss: 0.5448 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7249 - val_loss: 0.5397 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7332 - val_loss: 0.5364 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7416 - val_loss: 0.5368 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7505 - val_loss: 0.5374 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7574 - val_loss: 0.5386 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7663 - val_loss: 0.5387 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4682 - accuracy: 0.7760 - val_loss: 0.5652 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4557 - accuracy: 0.7861
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4561 - accuracy: 0.7861 - val_loss: 0.5478 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 764us/step
Independent Testing Matthews Correlation:  0.41150996564458353
Confusion Matrix :
 [[2835 1212]
 [1170 2878]]
Accuracy on test set:    0.7057442865966647
Sensitivity:    0.7109683794466403 	 Specificity:    0.7005189028910304
Precision  : 0.7036674816625916
Area Under Curve:    0.7057436411688353
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5842 - accuracy: 0.6875 - val_loss: 0.5421 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5403 - accuracy: 0.7248 - val_loss: 0.5366 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5258 - accuracy: 0.7356 - val_loss: 0.5325 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5115 - accuracy: 0.7468 - val_loss: 0.5309 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7532 - val_loss: 0.5300 - val_accuracy: 0.7311 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.7611 - val_loss: 0.5329 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7704 - val_loss: 0.5409 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7787 - val_loss: 0.5375 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4531 - accuracy: 0.7873 - val_loss: 0.5415 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4385 - accuracy: 0.7958 - val_loss: 0.5483 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4260 - accuracy: 0.8033 - val_loss: 0.5597 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4145 - accuracy: 0.8121 - val_loss: 0.5570 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 13/400
256/257 [============================>.] - ETA: 0s - loss: 0.4017 - accuracy: 0.8161
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4018 - accuracy: 0.8161 - val_loss: 0.5744 - val_accuracy: 0.7246 - lr: 0.0010
253/253 [==============================] - 0s 954us/step
Independent Testing Matthews Correlation:  0.4028493911903192
Confusion Matrix :
 [[2851 1196]
 [1221 2827]]
Accuracy on test set:    0.70142063001853
Sensitivity:    0.6983695652173914 	 Specificity:    0.7044724487274524
Precision  : 0.7027094208302263
Area Under Curve:    0.7014210069724219
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5906 - accuracy: 0.6829 - val_loss: 0.5495 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5488 - accuracy: 0.7212 - val_loss: 0.5404 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5343 - accuracy: 0.7304 - val_loss: 0.5441 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5223 - accuracy: 0.7390 - val_loss: 0.5385 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5138 - accuracy: 0.7453 - val_loss: 0.5432 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7513 - val_loss: 0.5413 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7602 - val_loss: 0.5457 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4799 - accuracy: 0.7687
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4801 - accuracy: 0.7686 - val_loss: 0.5520 - val_accuracy: 0.7193 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41396771931154014
Confusion Matrix :
 [[2821 1226]
 [1146 2901]]
Accuracy on test set:    0.7069434148752162
Sensitivity:    0.7168272794662713 	 Specificity:    0.6970595502841611
Precision  : 0.7029319118003392
Area Under Curve:    0.7069434148752163
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5908 - accuracy: 0.6829 - val_loss: 0.5535 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7219 - val_loss: 0.5472 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7314 - val_loss: 0.5407 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5207 - accuracy: 0.7401 - val_loss: 0.5413 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5094 - accuracy: 0.7482 - val_loss: 0.5416 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7548 - val_loss: 0.5431 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7637 - val_loss: 0.5468 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4764 - accuracy: 0.7716 - val_loss: 0.5511 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4629 - accuracy: 0.7800 - val_loss: 0.5566 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4522 - accuracy: 0.7863 - val_loss: 0.5556 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4366 - accuracy: 0.7964
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4369 - accuracy: 0.7960 - val_loss: 0.5583 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.424145069971893
Confusion Matrix :
 [[2966 1081]
 [1251 2796]]
Accuracy on test set:    0.7118853471707438
Sensitivity:    0.6908821349147517 	 Specificity:    0.7328885594267358
Precision  : 0.7211761671395409
Area Under Curve:    0.7118853471707437
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5969 - accuracy: 0.6762 - val_loss: 0.5518 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5513 - accuracy: 0.7193 - val_loss: 0.5436 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5344 - accuracy: 0.7296 - val_loss: 0.5463 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7399 - val_loss: 0.5389 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5103 - accuracy: 0.7458 - val_loss: 0.5383 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7546 - val_loss: 0.5391 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4863 - accuracy: 0.7633 - val_loss: 0.5418 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4740 - accuracy: 0.7726 - val_loss: 0.5453 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4608 - accuracy: 0.7822 - val_loss: 0.5512 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4469 - accuracy: 0.7899
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4466 - accuracy: 0.7902 - val_loss: 0.5596 - val_accuracy: 0.7227 - lr: 0.0010
253/253 [==============================] - 0s 775us/step
Independent Testing Matthews Correlation:  0.4315573281157599
Confusion Matrix :
 [[2787 1260]
 [1043 3004]]
Accuracy on test set:    0.7154682480850012
Sensitivity:    0.7422782307882382 	 Specificity:    0.6886582653817642
Precision  : 0.7045028142589118
Area Under Curve:    0.7154682480850013
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5872 - accuracy: 0.6836 - val_loss: 0.5472 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7236 - val_loss: 0.5415 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7330 - val_loss: 0.5437 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7423 - val_loss: 0.5427 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5054 - accuracy: 0.7504 - val_loss: 0.5439 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 6/400
255/257 [============================>.] - ETA: 0s - loss: 0.4929 - accuracy: 0.7589
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4927 - accuracy: 0.7590 - val_loss: 0.5463 - val_accuracy: 0.7205 - lr: 0.0010
253/253 [==============================] - 0s 992us/step
Independent Testing Matthews Correlation:  0.44430377209350136
Confusion Matrix :
 [[2753 1294]
 [ 961 3086]]
Accuracy on test set:    0.7213985668396343
Sensitivity:    0.7625401531999012 	 Specificity:    0.6802569804793674
Precision  : 0.7045662100456621
Area Under Curve:    0.7213985668396343
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5909 - accuracy: 0.6818 - val_loss: 0.5620 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5477 - accuracy: 0.7218 - val_loss: 0.5517 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7310 - val_loss: 0.5464 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7402 - val_loss: 0.5487 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7471 - val_loss: 0.5471 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7557 - val_loss: 0.5531 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.7657 - val_loss: 0.5531 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4750 - accuracy: 0.7718
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7716 - val_loss: 0.5564 - val_accuracy: 0.7131 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4430252280915974
Confusion Matrix :
 [[3034 1013]
 [1244 2803]]
Accuracy on test set:    0.7211514702248579
Sensitivity:    0.6926118112181863 	 Specificity:    0.7496911292315295
Precision  : 0.734538784067086
Area Under Curve:    0.7211514702248579
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5906 - accuracy: 0.6827 - val_loss: 0.5630 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7188 - val_loss: 0.5536 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5344 - accuracy: 0.7288 - val_loss: 0.5503 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5232 - accuracy: 0.7380 - val_loss: 0.5481 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5113 - accuracy: 0.7464 - val_loss: 0.5522 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7532 - val_loss: 0.5543 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7636 - val_loss: 0.5596 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4793 - accuracy: 0.7714 - val_loss: 0.5616 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4664 - accuracy: 0.7772 - val_loss: 0.5688 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4546 - accuracy: 0.7869 - val_loss: 0.5769 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4414 - accuracy: 0.7947
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4415 - accuracy: 0.7946 - val_loss: 0.5762 - val_accuracy: 0.7080 - lr: 0.0010
253/253 [==============================] - 0s 954us/step
Independent Testing Matthews Correlation:  0.4794292745725287
Confusion Matrix :
 [[2961 1086]
 [1021 3026]]
Accuracy on test set:    0.7396837163330863
Sensitivity:    0.7477143563133185 	 Specificity:    0.7316530763528539
Precision  : 0.7358949416342413
Area Under Curve:    0.7396837163330863
(8094, 2560) (8094,)
Mean MCC = 0.4255 + 0.0236 and Mean AUC = 0.7126 + 0.0117
Mean Sensitivity = 0.7142 + 0.0265 and Mean Specificity = 0.7109 + 0.0212 and Mean Accuracy = 0.7126 + 0.0117
Mean Precision = 0.7121 + 0.0128





Seed   : 312190
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5856 - accuracy: 0.6864 - val_loss: 0.5571 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7252 - val_loss: 0.5530 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5263 - accuracy: 0.7352 - val_loss: 0.5490 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5137 - accuracy: 0.7430 - val_loss: 0.5484 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7528 - val_loss: 0.5489 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7617 - val_loss: 0.5602 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7683 - val_loss: 0.5555 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4663 - accuracy: 0.7785 - val_loss: 0.5607 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4544 - accuracy: 0.7852 - val_loss: 0.5580 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4420 - accuracy: 0.7936
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4420 - accuracy: 0.7936 - val_loss: 0.5799 - val_accuracy: 0.7023 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4007061287117505
Confusion Matrix :
 [[2385 1663]
 [ 800 3247]]
Accuracy on test set:    0.6957381099444101
Sensitivity:    0.802322708178898 	 Specificity:    0.5891798418972332
Precision  : 0.6613034623217923
Area Under Curve:    0.6957512750380654
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5843 - accuracy: 0.6872 - val_loss: 0.5566 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7244 - val_loss: 0.5491 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7358 - val_loss: 0.5484 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7430 - val_loss: 0.5498 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5067 - accuracy: 0.7496 - val_loss: 0.5539 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7595 - val_loss: 0.5511 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7682 - val_loss: 0.5491 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4693 - accuracy: 0.7756 - val_loss: 0.5523 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4582 - accuracy: 0.7824 - val_loss: 0.5609 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4414 - accuracy: 0.7951 - val_loss: 0.5599 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 11/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4277 - accuracy: 0.8022
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4284 - accuracy: 0.8019 - val_loss: 0.5690 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42243575231212005
Confusion Matrix :
 [[2752 1296]
 [1045 3002]]
Accuracy on test set:    0.7108091414453366
Sensitivity:    0.7417840375586855 	 Specificity:    0.6798418972332015
Precision  : 0.698464402047464
Area Under Curve:    0.7108129673959436
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5861 - accuracy: 0.6850 - val_loss: 0.5486 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7234 - val_loss: 0.5401 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7340 - val_loss: 0.5447 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7435 - val_loss: 0.5364 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7500 - val_loss: 0.5389 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7576 - val_loss: 0.5387 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 7/400
252/257 [============================>.] - ETA: 0s - loss: 0.4843 - accuracy: 0.7675
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7678 - val_loss: 0.5454 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 752us/step
Independent Testing Matthews Correlation:  0.4268270113832272
Confusion Matrix :
 [[2985 1062]
 [1260 2788]]
Accuracy on test set:    0.7131562693020383
Sensitivity:    0.6887351778656127 	 Specificity:    0.737583395107487
Precision  : 0.7241558441558441
Area Under Curve:    0.7131592864865499
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5940 - accuracy: 0.6787 - val_loss: 0.5559 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7242 - val_loss: 0.5391 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7330 - val_loss: 0.5399 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5204 - accuracy: 0.7423 - val_loss: 0.5348 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7486 - val_loss: 0.5359 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4989 - accuracy: 0.7541 - val_loss: 0.5391 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7656 - val_loss: 0.5607 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4744 - accuracy: 0.7730 - val_loss: 0.5467 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4634 - accuracy: 0.7821 - val_loss: 0.5498 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4501 - accuracy: 0.7902
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4503 - accuracy: 0.7899 - val_loss: 0.5486 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4206463559797328
Confusion Matrix :
 [[2892 1155]
 [1190 2858]]
Accuracy on test set:    0.7103150092649784
Sensitivity:    0.7060276679841897 	 Specificity:    0.7146034099332839
Precision  : 0.7121853974582607
Area Under Curve:    0.7103155389587368
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5856 - accuracy: 0.6860 - val_loss: 0.5437 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7233 - val_loss: 0.5361 - val_accuracy: 0.7311 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7331 - val_loss: 0.5376 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7383 - val_loss: 0.5350 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.7466 - val_loss: 0.5356 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7555 - val_loss: 0.5400 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4832 - accuracy: 0.7677
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4831 - accuracy: 0.7675 - val_loss: 0.5427 - val_accuracy: 0.7252 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42733827378060096
Confusion Matrix :
 [[2805 1242]
 [1077 2970]]
Accuracy on test set:    0.7134914751667902
Sensitivity:    0.7338769458858414 	 Specificity:    0.6931060044477391
Precision  : 0.7051282051282052
Area Under Curve:    0.7134914751667902
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5887 - accuracy: 0.6827 - val_loss: 0.5485 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7206 - val_loss: 0.5404 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7322 - val_loss: 0.5405 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7410 - val_loss: 0.5407 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7475 - val_loss: 0.5420 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7572 - val_loss: 0.5422 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4824 - accuracy: 0.7664
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7658 - val_loss: 0.5438 - val_accuracy: 0.7249 - lr: 0.0010
253/253 [==============================] - 0s 772us/step
Independent Testing Matthews Correlation:  0.4331739073855576
Confusion Matrix :
 [[2884 1163]
 [1131 2916]]
Accuracy on test set:    0.7165801828514949
Sensitivity:    0.720533728687917 	 Specificity:    0.7126266370150729
Precision  : 0.714881098308409
Area Under Curve:    0.7165801828514949
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5886 - accuracy: 0.6840 - val_loss: 0.5474 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7216 - val_loss: 0.5419 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7309 - val_loss: 0.5409 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7395 - val_loss: 0.5363 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5118 - accuracy: 0.7445 - val_loss: 0.5374 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 6/400
246/257 [===========================>..] - ETA: 0s - loss: 0.5028 - accuracy: 0.7521
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7520 - val_loss: 0.5384 - val_accuracy: 0.7270 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43700292752443587
Confusion Matrix :
 [[2958 1089]
 [1190 2857]]
Accuracy on test set:    0.7184334074623178
Sensitivity:    0.7059550284161107 	 Specificity:    0.7309117865085248
Precision  : 0.7240243284338571
Area Under Curve:    0.7184334074623178
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5875 - accuracy: 0.6845 - val_loss: 0.5500 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7212 - val_loss: 0.5430 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7304 - val_loss: 0.5437 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7406 - val_loss: 0.5391 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7477 - val_loss: 0.5369 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7576 - val_loss: 0.5384 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7657 - val_loss: 0.5427 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7745 - val_loss: 0.5419 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4629 - accuracy: 0.7818 - val_loss: 0.5478 - val_accuracy: 0.7224 - lr: 0.0010

Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4478 - accuracy: 0.7908
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4477 - accuracy: 0.7909 - val_loss: 0.5521 - val_accuracy: 0.7222 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43224820509349604
Confusion Matrix :
 [[2860 1187]
 [1111 2936]]
Accuracy on test set:    0.7160859896219421
Sensitivity:    0.7254756609834445 	 Specificity:    0.7066963182604399
Precision  : 0.7121028377395101
Area Under Curve:    0.7160859896219421
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5932 - accuracy: 0.6795 - val_loss: 0.5495 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5492 - accuracy: 0.7193 - val_loss: 0.5450 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5336 - accuracy: 0.7310 - val_loss: 0.5434 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7398 - val_loss: 0.5404 - val_accuracy: 0.7315 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5114 - accuracy: 0.7453 - val_loss: 0.5415 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5006 - accuracy: 0.7541 - val_loss: 0.5485 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4902 - accuracy: 0.7615 - val_loss: 0.5477 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4779 - accuracy: 0.7691 - val_loss: 0.5522 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4669 - accuracy: 0.7759
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4669 - accuracy: 0.7759 - val_loss: 0.5564 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 736us/step
Independent Testing Matthews Correlation:  0.45632498072123695
Confusion Matrix :
 [[2858 1189]
 [1013 3034]]
Accuracy on test set:    0.7279466271312083
Sensitivity:    0.7496911292315295 	 Specificity:    0.7062021250308871
Precision  : 0.7184466019417476
Area Under Curve:    0.7279466271312083
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5927 - accuracy: 0.6801 - val_loss: 0.5546 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7202 - val_loss: 0.5489 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5343 - accuracy: 0.7295 - val_loss: 0.5453 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5213 - accuracy: 0.7412 - val_loss: 0.5475 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7494 - val_loss: 0.5457 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7562 - val_loss: 0.5464 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7644 - val_loss: 0.5493 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4743 - accuracy: 0.7740
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4740 - accuracy: 0.7743 - val_loss: 0.5553 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.48929648504964635
Confusion Matrix :
 [[3041 1006]
 [1061 2986]]
Accuracy on test set:    0.7446256486286138
Sensitivity:    0.7378304917222634 	 Specificity:    0.7514208055349642
Precision  : 0.7479959919839679
Area Under Curve:    0.7446256486286138
(8094, 2560) (8094,)
Mean MCC = 0.4346 + 0.0225 and Mean AUC = 0.7167 + 0.0120
Mean Sensitivity = 0.7312 + 0.0296 and Mean Specificity = 0.7022 + 0.0426 and Mean Accuracy = 0.7167 + 0.0120
Mean Precision = 0.7119 + 0.0211





Seed   : 894193
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5866 - accuracy: 0.6869 - val_loss: 0.5534 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5416 - accuracy: 0.7246 - val_loss: 0.5488 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5268 - accuracy: 0.7354 - val_loss: 0.5476 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5133 - accuracy: 0.7449 - val_loss: 0.5540 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5003 - accuracy: 0.7532 - val_loss: 0.5493 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.7616 - val_loss: 0.5616 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4759 - accuracy: 0.7701 - val_loss: 0.5796 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4640 - accuracy: 0.7783 - val_loss: 0.5703 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4506 - accuracy: 0.7879 - val_loss: 0.5686 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4374 - accuracy: 0.7956
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4373 - accuracy: 0.7959 - val_loss: 0.5802 - val_accuracy: 0.7109 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40698037473856213
Confusion Matrix :
 [[2612 1436]
 [ 975 3072]]
Accuracy on test set:    0.7021618282890674
Sensitivity:    0.7590808005930318 	 Specificity:    0.6452569169960475
Precision  : 0.6814551907719609
Area Under Curve:    0.7021688587945396
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5827 - accuracy: 0.6889 - val_loss: 0.5546 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7243 - val_loss: 0.5525 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5263 - accuracy: 0.7360 - val_loss: 0.5501 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5124 - accuracy: 0.7446 - val_loss: 0.5508 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.7534 - val_loss: 0.5522 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7620 - val_loss: 0.5520 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7718 - val_loss: 0.5607 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4613 - accuracy: 0.7815 - val_loss: 0.5608 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4474 - accuracy: 0.7909 - val_loss: 0.5676 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4324 - accuracy: 0.7991
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4325 - accuracy: 0.7993 - val_loss: 0.5706 - val_accuracy: 0.7076 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4167136232961922
Confusion Matrix :
 [[2841 1207]
 [1154 2893]]
Accuracy on test set:    0.7083384805435454
Sensitivity:    0.7148505065480603 	 Specificity:    0.7018280632411067
Precision  : 0.7056097560975609
Area Under Curve:    0.7083392848945834
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5893 - accuracy: 0.6828 - val_loss: 0.5554 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7214 - val_loss: 0.5429 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7322 - val_loss: 0.5376 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5168 - accuracy: 0.7408 - val_loss: 0.5395 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7505 - val_loss: 0.5413 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7579 - val_loss: 0.5433 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4797 - accuracy: 0.7681 - val_loss: 0.5522 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4680 - accuracy: 0.7768
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4683 - accuracy: 0.7767 - val_loss: 0.5531 - val_accuracy: 0.7179 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4380969090378992
Confusion Matrix :
 [[2633 1414]
 [ 876 3172]]
Accuracy on test set:    0.7171093267449042
Sensitivity:    0.7835968379446641 	 Specificity:    0.6506053867062022
Precision  : 0.6916703009158308
Area Under Curve:    0.7171011123254329
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6849 - val_loss: 0.5471 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7223 - val_loss: 0.5396 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7327 - val_loss: 0.5369 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7389 - val_loss: 0.5407 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7470 - val_loss: 0.5355 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.7550 - val_loss: 0.5386 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.7648 - val_loss: 0.5415 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.7728 - val_loss: 0.5460 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4659 - accuracy: 0.7808 - val_loss: 0.5475 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4542 - accuracy: 0.7870 - val_loss: 0.5517 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4407 - accuracy: 0.7959 - val_loss: 0.5621 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4303 - accuracy: 0.8033 - val_loss: 0.5598 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 13/400
251/257 [============================>.] - ETA: 0s - loss: 0.4178 - accuracy: 0.8101
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4180 - accuracy: 0.8101 - val_loss: 0.5625 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 701us/step
Independent Testing Matthews Correlation:  0.4079811653504229
Confusion Matrix :
 [[2785 1262]
 [1135 2913]]
Accuracy on test set:    0.7038912909203212
Sensitivity:    0.7196146245059288 	 Specificity:    0.6881640721522115
Precision  : 0.6977245508982036
Area Under Curve:    0.7038893483290701
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5908 - accuracy: 0.6807 - val_loss: 0.5608 - val_accuracy: 0.7049 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7214 - val_loss: 0.5461 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7336 - val_loss: 0.5425 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7403 - val_loss: 0.5437 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7491 - val_loss: 0.5399 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7605 - val_loss: 0.5526 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7675 - val_loss: 0.5482 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4673 - accuracy: 0.7766 - val_loss: 0.5483 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4548 - accuracy: 0.7834 - val_loss: 0.5597 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4407 - accuracy: 0.7935 - val_loss: 0.5694 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4292 - accuracy: 0.8016 - val_loss: 0.5732 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4159 - accuracy: 0.8090 - val_loss: 0.5735 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 13/400
251/257 [============================>.] - ETA: 0s - loss: 0.4003 - accuracy: 0.8193
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4009 - accuracy: 0.8190 - val_loss: 0.5829 - val_accuracy: 0.7120 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42113479156349304
Confusion Matrix :
 [[2795 1252]
 [1092 2955]]
Accuracy on test set:    0.7104027674820855
Sensitivity:    0.7301704966641956 	 Specificity:    0.6906350382999753
Precision  : 0.7024007606370335
Area Under Curve:    0.7104027674820854
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5847 - accuracy: 0.6871 - val_loss: 0.5547 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7256 - val_loss: 0.5450 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7354 - val_loss: 0.5437 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7438 - val_loss: 0.5435 - val_accuracy: 0.7219 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7522 - val_loss: 0.5455 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4911 - accuracy: 0.7614 - val_loss: 0.5438 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4806 - accuracy: 0.7684 - val_loss: 0.5583 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4679 - accuracy: 0.7748 - val_loss: 0.5591 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4568 - accuracy: 0.7837
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4572 - accuracy: 0.7832 - val_loss: 0.5573 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43842330968233756
Confusion Matrix :
 [[2677 1370]
 [ 914 3133]]
Accuracy on test set:    0.7178156659253768
Sensitivity:    0.7741536940943909 	 Specificity:    0.6614776377563627
Precision  : 0.6957583833000222
Area Under Curve:    0.7178156659253767
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5891 - accuracy: 0.6828 - val_loss: 0.5536 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7230 - val_loss: 0.5423 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7345 - val_loss: 0.5449 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7449 - val_loss: 0.5413 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7515 - val_loss: 0.5447 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7593 - val_loss: 0.5439 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4793 - accuracy: 0.7690
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7680 - val_loss: 0.5432 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 960us/step
Independent Testing Matthews Correlation:  0.410590409852301
Confusion Matrix :
 [[2797 1250]
 [1136 2911]]
Accuracy on test set:    0.7052137385717816
Sensitivity:    0.7192982456140351 	 Specificity:    0.6911292315295281
Precision  : 0.6995914443643355
Area Under Curve:    0.7052137385717816
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5932 - accuracy: 0.6793 - val_loss: 0.5531 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7207 - val_loss: 0.5415 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5343 - accuracy: 0.7309 - val_loss: 0.5413 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7404 - val_loss: 0.5386 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.7488 - val_loss: 0.5389 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7538 - val_loss: 0.5389 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7618 - val_loss: 0.5442 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4776 - accuracy: 0.7707 - val_loss: 0.5426 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.7781 - val_loss: 0.5540 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4547 - accuracy: 0.7843 - val_loss: 0.5485 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4427 - accuracy: 0.7921 - val_loss: 0.5547 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4326 - accuracy: 0.7980 - val_loss: 0.5606 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4181 - accuracy: 0.8078 - val_loss: 0.5655 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4084 - accuracy: 0.8126 - val_loss: 0.5686 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3961 - accuracy: 0.8210 - val_loss: 0.5777 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 16/400
244/257 [===========================>..] - ETA: 0s - loss: 0.3877 - accuracy: 0.8251
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3874 - accuracy: 0.8254 - val_loss: 0.5986 - val_accuracy: 0.7209 - lr: 0.0010
253/253 [==============================] - 0s 749us/step
Independent Testing Matthews Correlation:  0.41366721805785006
Confusion Matrix :
 [[2700 1347]
 [1031 3016]]
Accuracy on test set:    0.7062021250308871
Sensitivity:    0.7452433901655547 	 Specificity:    0.6671608598962194
Precision  : 0.6912674765069906
Area Under Curve:    0.7062021250308871
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5882 - accuracy: 0.6831 - val_loss: 0.5467 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7205 - val_loss: 0.5400 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7304 - val_loss: 0.5413 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7384 - val_loss: 0.5400 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7468 - val_loss: 0.5403 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7544 - val_loss: 0.5393 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4889 - accuracy: 0.7637
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4889 - accuracy: 0.7639 - val_loss: 0.5451 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46870035930020476
Confusion Matrix :
 [[2860 1187]
 [ 966 3081]]
Accuracy on test set:    0.7340004941932295
Sensitivity:    0.7613046701260193 	 Specificity:    0.7066963182604399
Precision  : 0.721883786316776
Area Under Curve:    0.7340004941932295
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5933 - accuracy: 0.6818 - val_loss: 0.5525 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5506 - accuracy: 0.7195 - val_loss: 0.5483 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5362 - accuracy: 0.7308 - val_loss: 0.5440 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5221 - accuracy: 0.7373 - val_loss: 0.5487 - val_accuracy: 0.7135 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5122 - accuracy: 0.7452 - val_loss: 0.5444 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.7555 - val_loss: 0.5504 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7605 - val_loss: 0.5461 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4802 - accuracy: 0.7694
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4805 - accuracy: 0.7692 - val_loss: 0.5551 - val_accuracy: 0.7157 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.48719457229400337
Confusion Matrix :
 [[2956 1091]
 [ 985 3062]]
Accuracy on test set:    0.7435137138621201
Sensitivity:    0.7566098344452681 	 Specificity:    0.730417593278972
Precision  : 0.7372983385504455
Area Under Curve:    0.74351371386212
(8094, 2560) (8094,)
Mean MCC = 0.4309 + 0.0261 and Mean AUC = 0.7149 + 0.0131
Mean Sensitivity = 0.7464 + 0.0231 and Mean Specificity = 0.6833 + 0.0255 and Mean Accuracy = 0.7149 + 0.0131
Mean Precision = 0.7025 + 0.0154





Seed   : 275100
Epoch 1/400
257/257 [==============================] - 3s 8ms/step - loss: 0.5886 - accuracy: 0.6846 - val_loss: 0.5582 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7259 - val_loss: 0.5557 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7329 - val_loss: 0.5542 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7415 - val_loss: 0.5525 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7503 - val_loss: 0.5541 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7572 - val_loss: 0.5499 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4841 - accuracy: 0.7655 - val_loss: 0.5532 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7726 - val_loss: 0.5560 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4622 - accuracy: 0.7812 - val_loss: 0.5633 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4506 - accuracy: 0.7869 - val_loss: 0.5654 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4370 - accuracy: 0.7947 - val_loss: 0.5712 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4273 - accuracy: 0.8024 - val_loss: 0.5802 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 13/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4153 - accuracy: 0.8073
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4159 - accuracy: 0.8073 - val_loss: 0.5872 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3781975439083539
Confusion Matrix :
 [[2753 1295]
 [1222 2825]]
Accuracy on test set:    0.6890673255095738
Sensitivity:    0.6980479367432666 	 Specificity:    0.6800889328063241
Precision  : 0.6856796116504854
Area Under Curve:    0.6890684347747954
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5846 - accuracy: 0.6883 - val_loss: 0.5529 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5423 - accuracy: 0.7238 - val_loss: 0.5444 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5259 - accuracy: 0.7367 - val_loss: 0.5456 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7439 - val_loss: 0.5434 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5021 - accuracy: 0.7519 - val_loss: 0.5463 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4923 - accuracy: 0.7598 - val_loss: 0.5534 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4808 - accuracy: 0.7665
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7666 - val_loss: 0.5559 - val_accuracy: 0.7139 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41716199653435604
Confusion Matrix :
 [[2800 1248]
 [1112 2935]]
Accuracy on test set:    0.7084620135886349
Sensitivity:    0.7252285643686681 	 Specificity:    0.691699604743083
Precision  : 0.7016495338273966
Area Under Curve:    0.7084640845558756
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5865 - accuracy: 0.6846 - val_loss: 0.5452 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7213 - val_loss: 0.5396 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7345 - val_loss: 0.5353 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7423 - val_loss: 0.5387 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7511 - val_loss: 0.5412 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7588 - val_loss: 0.5387 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7672 - val_loss: 0.5410 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4672 - accuracy: 0.7761
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.7761 - val_loss: 0.5473 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 830us/step
Independent Testing Matthews Correlation:  0.42178423097653167
Confusion Matrix :
 [[2742 1305]
 [1039 3009]]
Accuracy on test set:    0.710438542310068
Sensitivity:    0.7433300395256917 	 Specificity:    0.6775389177168273
Precision  : 0.6974965229485396
Area Under Curve:    0.7104344786212595
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5862 - accuracy: 0.6845 - val_loss: 0.5465 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7216 - val_loss: 0.5414 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7320 - val_loss: 0.5434 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7396 - val_loss: 0.5356 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7498 - val_loss: 0.5352 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7552 - val_loss: 0.5377 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.7624 - val_loss: 0.5444 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7701 - val_loss: 0.5430 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4659 - accuracy: 0.7774 - val_loss: 0.5476 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4561 - accuracy: 0.7834
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4561 - accuracy: 0.7834 - val_loss: 0.5510 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 846us/step
Independent Testing Matthews Correlation:  0.42972529281969196
Confusion Matrix :
 [[2673 1374]
 [ 944 3104]]
Accuracy on test set:    0.7136504014823966
Sensitivity:    0.766798418972332 	 Specificity:    0.6604892512972572
Precision  : 0.6931665922286735
Area Under Curve:    0.7136438351347947
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5898 - accuracy: 0.6842 - val_loss: 0.5471 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7215 - val_loss: 0.5490 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7312 - val_loss: 0.5400 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7394 - val_loss: 0.5342 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.7482 - val_loss: 0.5352 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7547 - val_loss: 0.5404 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.7621 - val_loss: 0.5362 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4736 - accuracy: 0.7725 - val_loss: 0.5469 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4630 - accuracy: 0.7799 - val_loss: 0.5431 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4488 - accuracy: 0.7886
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4489 - accuracy: 0.7884 - val_loss: 0.5458 - val_accuracy: 0.7242 - lr: 0.0010
253/253 [==============================] - 0s 883us/step
Independent Testing Matthews Correlation:  0.4356676234949562
Confusion Matrix :
 [[2748 1299]
 [ 990 3057]]
Accuracy on test set:    0.7171979243884359
Sensitivity:    0.7553743513713862 	 Specificity:    0.6790214974054856
Precision  : 0.7017906336088154
Area Under Curve:    0.7171979243884359
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5863 - accuracy: 0.6850 - val_loss: 0.5465 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7231 - val_loss: 0.5402 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7339 - val_loss: 0.5377 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7427 - val_loss: 0.5362 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7511 - val_loss: 0.5377 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7594 - val_loss: 0.5348 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.7682 - val_loss: 0.5395 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7768 - val_loss: 0.5433 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4574 - accuracy: 0.7850 - val_loss: 0.5432 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4436 - accuracy: 0.7929 - val_loss: 0.5497 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 11/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4310 - accuracy: 0.8016
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4320 - accuracy: 0.8012 - val_loss: 0.5594 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 746us/step
Independent Testing Matthews Correlation:  0.4107739883408926
Confusion Matrix :
 [[3015 1032]
 [1358 2689]]
Accuracy on test set:    0.7047195453422288
Sensitivity:    0.6644427971336793 	 Specificity:    0.7449962935507783
Precision  : 0.722655200214996
Area Under Curve:    0.7047195453422288
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.6832 - val_loss: 0.5483 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7225 - val_loss: 0.5400 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7329 - val_loss: 0.5381 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.7418 - val_loss: 0.5379 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5106 - accuracy: 0.7473 - val_loss: 0.5390 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4999 - accuracy: 0.7540 - val_loss: 0.5396 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7602 - val_loss: 0.5415 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7699 - val_loss: 0.5461 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4679 - accuracy: 0.7770
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4676 - accuracy: 0.7772 - val_loss: 0.5631 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 727us/step
Independent Testing Matthews Correlation:  0.42789747817379287
Confusion Matrix :
 [[2738 1309]
 [1011 3036]]
Accuracy on test set:    0.713367926859402
Sensitivity:    0.7501853224610823 	 Specificity:    0.6765505312577218
Precision  : 0.6987341772151898
Area Under Curve:    0.7133679268594021
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5906 - accuracy: 0.6814 - val_loss: 0.5503 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7233 - val_loss: 0.5434 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7324 - val_loss: 0.5400 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7405 - val_loss: 0.5403 - val_accuracy: 0.7201 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5093 - accuracy: 0.7488 - val_loss: 0.5384 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7568 - val_loss: 0.5407 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4872 - accuracy: 0.7643 - val_loss: 0.5487 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4738 - accuracy: 0.7729 - val_loss: 0.5547 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4618 - accuracy: 0.7821 - val_loss: 0.5527 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4486 - accuracy: 0.7887 - val_loss: 0.5557 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4352 - accuracy: 0.7980
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4351 - accuracy: 0.7980 - val_loss: 0.5767 - val_accuracy: 0.7152 - lr: 0.0010
253/253 [==============================] - 0s 930us/step
Independent Testing Matthews Correlation:  0.43130954243466796
Confusion Matrix :
 [[2705 1342]
 [ 967 3080]]
Accuracy on test set:    0.7147269582406721
Sensitivity:    0.7610575735112429 	 Specificity:    0.6683963429701013
Precision  : 0.6965174129353234
Area Under Curve:    0.7147269582406722
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5890 - accuracy: 0.6836 - val_loss: 0.5547 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7217 - val_loss: 0.5462 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7321 - val_loss: 0.5442 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.7404 - val_loss: 0.5467 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7496 - val_loss: 0.5488 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7583 - val_loss: 0.5547 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7655 - val_loss: 0.5525 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4730 - accuracy: 0.7736 - val_loss: 0.5629 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4606 - accuracy: 0.7823
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4606 - accuracy: 0.7824 - val_loss: 0.5576 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 914us/step
Independent Testing Matthews Correlation:  0.4611248692437576
Confusion Matrix :
 [[2984 1063]
 [1118 2929]]
Accuracy on test set:    0.7305411415863603
Sensitivity:    0.7237459846800098 	 Specificity:    0.7373362984927107
Precision  : 0.7337174348697395
Area Under Curve:    0.7305411415863602
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5942 - accuracy: 0.6774 - val_loss: 0.5576 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5502 - accuracy: 0.7201 - val_loss: 0.5495 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5332 - accuracy: 0.7310 - val_loss: 0.5469 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5231 - accuracy: 0.7384 - val_loss: 0.5468 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5133 - accuracy: 0.7451 - val_loss: 0.5471 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7539 - val_loss: 0.5490 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.7623 - val_loss: 0.5471 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4763 - accuracy: 0.7721 - val_loss: 0.5546 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4647 - accuracy: 0.7806 - val_loss: 0.5634 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4492 - accuracy: 0.7895 - val_loss: 0.5685 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4354 - accuracy: 0.7984
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4360 - accuracy: 0.7981 - val_loss: 0.5790 - val_accuracy: 0.7098 - lr: 0.0010
253/253 [==============================] - 0s 947us/step
Independent Testing Matthews Correlation:  0.4831078636151882
Confusion Matrix :
 [[2977 1070]
 [1022 3025]]
Accuracy on test set:    0.7415369409439091
Sensitivity:    0.7474672596985421 	 Specificity:    0.735606622189276
Precision  : 0.7387057387057387
Area Under Curve:    0.7415369409439092
(8094, 2560) (8094,)
Mean MCC = 0.4297 + 0.0267 and Mean AUC = 0.7144 + 0.0134
Mean Sensitivity = 0.7336 + 0.0302 and Mean Specificity = 0.6952 + 0.0300 and Mean Accuracy = 0.7144 + 0.0134
Mean Precision = 0.7070 + 0.0171





Seed   : 146936
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5856 - accuracy: 0.6850 - val_loss: 0.5606 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5413 - accuracy: 0.7246 - val_loss: 0.5504 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.7354 - val_loss: 0.5508 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5150 - accuracy: 0.7442 - val_loss: 0.5500 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7511 - val_loss: 0.5514 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4918 - accuracy: 0.7606 - val_loss: 0.5579 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4794 - accuracy: 0.7696
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7693 - val_loss: 0.5575 - val_accuracy: 0.7149 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42591351921460624
Confusion Matrix :
 [[2724 1324]
 [1005 3042]]
Accuracy on test set:    0.7122915379864113
Sensitivity:    0.7516679021497406 	 Specificity:    0.6729249011857708
Precision  : 0.6967475950526798
Area Under Curve:    0.7122964016677557
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5829 - accuracy: 0.6891 - val_loss: 0.5536 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5406 - accuracy: 0.7247 - val_loss: 0.5454 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.7330 - val_loss: 0.5436 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7459 - val_loss: 0.5466 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7507 - val_loss: 0.5472 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.7609 - val_loss: 0.5456 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.7697 - val_loss: 0.5543 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4675 - accuracy: 0.7787 - val_loss: 0.5542 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4545 - accuracy: 0.7860 - val_loss: 0.5621 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7936 - val_loss: 0.5691 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4290 - accuracy: 0.8026 - val_loss: 0.5662 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 12/400
254/257 [============================>.] - ETA: 0s - loss: 0.4166 - accuracy: 0.8098
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4167 - accuracy: 0.8097 - val_loss: 0.5807 - val_accuracy: 0.7117 - lr: 0.0010
253/253 [==============================] - 0s 917us/step
Independent Testing Matthews Correlation:  0.40674332070675356
Confusion Matrix :
 [[2611 1437]
 [ 975 3072]]
Accuracy on test set:    0.7020382952439778
Sensitivity:    0.7590808005930318 	 Specificity:    0.6450098814229249
Precision  : 0.6813040585495675
Area Under Curve:    0.7020453410079784
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.6839 - val_loss: 0.5463 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7245 - val_loss: 0.5360 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7346 - val_loss: 0.5370 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5168 - accuracy: 0.7427 - val_loss: 0.5367 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7520 - val_loss: 0.5337 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.7616 - val_loss: 0.5373 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4803 - accuracy: 0.7692
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7685 - val_loss: 0.5325 - val_accuracy: 0.7234 - lr: 0.0010
253/253 [==============================] - 0s 782us/step
Independent Testing Matthews Correlation:  0.4211255027597646
Confusion Matrix :
 [[2870 1177]
 [1166 2882]]
Accuracy on test set:    0.7105620753551575
Sensitivity:    0.7119565217391305 	 Specificity:    0.7091672844082036
Precision  : 0.7100271002710027
Area Under Curve:    0.710561903073667
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5899 - accuracy: 0.6842 - val_loss: 0.5515 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5482 - accuracy: 0.7210 - val_loss: 0.5444 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7327 - val_loss: 0.5372 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7399 - val_loss: 0.5367 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5103 - accuracy: 0.7471 - val_loss: 0.5347 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5000 - accuracy: 0.7547 - val_loss: 0.5368 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4892 - accuracy: 0.7630 - val_loss: 0.5410 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4784 - accuracy: 0.7698 - val_loss: 0.5428 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4677 - accuracy: 0.7767
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4677 - accuracy: 0.7766 - val_loss: 0.5487 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 767us/step
Independent Testing Matthews Correlation:  0.4292857272468759
Confusion Matrix :
 [[2879 1168]
 [1142 2906]]
Accuracy on test set:    0.7146386658431131
Sensitivity:    0.7178853754940712 	 Specificity:    0.711391153941191
Precision  : 0.7133038782523319
Area Under Curve:    0.7146382647176311
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5862 - accuracy: 0.6851 - val_loss: 0.5450 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7229 - val_loss: 0.5393 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7332 - val_loss: 0.5397 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7420 - val_loss: 0.5378 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7491 - val_loss: 0.5347 - val_accuracy: 0.7334 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7565 - val_loss: 0.5401 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7645 - val_loss: 0.5398 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4757 - accuracy: 0.7727 - val_loss: 0.5392 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.7792 - val_loss: 0.5447 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4517 - accuracy: 0.7870
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4515 - accuracy: 0.7873 - val_loss: 0.5507 - val_accuracy: 0.7251 - lr: 0.0010
253/253 [==============================] - 0s 710us/step
Independent Testing Matthews Correlation:  0.42273784782914114
Confusion Matrix :
 [[2695 1352]
 [ 991 3056]]
Accuracy on test set:    0.7105263157894737
Sensitivity:    0.7551272547566098 	 Specificity:    0.6659253768223375
Precision  : 0.6932849364791288
Area Under Curve:    0.7105263157894737
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5888 - accuracy: 0.6825 - val_loss: 0.5517 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7214 - val_loss: 0.5456 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7340 - val_loss: 0.5427 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7418 - val_loss: 0.5454 - val_accuracy: 0.7229 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7503 - val_loss: 0.5398 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7593 - val_loss: 0.5413 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7674 - val_loss: 0.5462 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4685 - accuracy: 0.7765 - val_loss: 0.5459 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4548 - accuracy: 0.7866 - val_loss: 0.5484 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4413 - accuracy: 0.7933
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4416 - accuracy: 0.7934 - val_loss: 0.5539 - val_accuracy: 0.7251 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4307028639891768
Confusion Matrix :
 [[2911 1136]
 [1168 2879]]
Accuracy on test set:    0.7153446997776131
Sensitivity:    0.711391153941191 	 Specificity:    0.7192982456140351
Precision  : 0.7170610211706102
Area Under Curve:    0.7153446997776131
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6839 - val_loss: 0.5478 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7241 - val_loss: 0.5381 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7326 - val_loss: 0.5384 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7405 - val_loss: 0.5387 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7474 - val_loss: 0.5392 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5000 - accuracy: 0.7534 - val_loss: 0.5422 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4913 - accuracy: 0.7604
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7605 - val_loss: 0.5419 - val_accuracy: 0.7241 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43055600189912413
Confusion Matrix :
 [[2848 1199]
 [1106 2941]]
Accuracy on test set:    0.7152211514702248
Sensitivity:    0.7267111440573264 	 Specificity:    0.7037311588831233
Precision  : 0.7103864734299516
Area Under Curve:    0.7152211514702249
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5877 - accuracy: 0.6834 - val_loss: 0.5518 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7218 - val_loss: 0.5419 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7332 - val_loss: 0.5408 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7416 - val_loss: 0.5401 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7488 - val_loss: 0.5380 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7580 - val_loss: 0.5403 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4828 - accuracy: 0.7652
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.7651 - val_loss: 0.5409 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 720us/step
Independent Testing Matthews Correlation:  0.4544240316379532
Confusion Matrix :
 [[2874 1173]
 [1036 3011]]
Accuracy on test set:    0.7270817889794909
Sensitivity:    0.7440079070916729 	 Specificity:    0.7101556708673091
Precision  : 0.7196462715105163
Area Under Curve:    0.7270817889794909
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5900 - accuracy: 0.6840 - val_loss: 0.5546 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7202 - val_loss: 0.5441 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5340 - accuracy: 0.7299 - val_loss: 0.5437 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7405 - val_loss: 0.5396 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5119 - accuracy: 0.7483 - val_loss: 0.5419 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.7541 - val_loss: 0.5515 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7632 - val_loss: 0.5427 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.7729 - val_loss: 0.5502 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4652 - accuracy: 0.7797
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7797 - val_loss: 0.5502 - val_accuracy: 0.7193 - lr: 0.0010
253/253 [==============================] - 0s 729us/step
Independent Testing Matthews Correlation:  0.45248700459603086
Confusion Matrix :
 [[2970 1077]
 [1139 2908]]
Accuracy on test set:    0.7262169508277737
Sensitivity:    0.7185569557697059 	 Specificity:    0.7338769458858414
Precision  : 0.7297365119196989
Area Under Curve:    0.7262169508277737
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5925 - accuracy: 0.6810 - val_loss: 0.5569 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5499 - accuracy: 0.7217 - val_loss: 0.5460 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5341 - accuracy: 0.7314 - val_loss: 0.5438 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5219 - accuracy: 0.7393 - val_loss: 0.5439 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5123 - accuracy: 0.7469 - val_loss: 0.5567 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7557 - val_loss: 0.5510 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4863 - accuracy: 0.7660 - val_loss: 0.5551 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4722 - accuracy: 0.7739
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4727 - accuracy: 0.7736 - val_loss: 0.5527 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4685937418985965
Confusion Matrix :
 [[3013 1034]
 [1117 2930]]
Accuracy on test set:    0.734247590808006
Sensitivity:    0.7239930812947862 	 Specificity:    0.7445021003212255
Precision  : 0.7391523713420787
Area Under Curve:    0.7342475908080058
(8094, 2560) (8094,)
Mean MCC = 0.4343 + 0.0176 and Mean AUC = 0.7168 + 0.0091
Mean Sensitivity = 0.7320 + 0.0176 and Mean Specificity = 0.7016 + 0.0295 and Mean Accuracy = 0.7168 + 0.0091
Mean Precision = 0.7111 + 0.0163





Seed   : 197817

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5885 - accuracy: 0.6830 - val_loss: 0.5516 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7225 - val_loss: 0.5424 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7344 - val_loss: 0.5426 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7420 - val_loss: 0.5511 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7473 - val_loss: 0.5402 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4980 - accuracy: 0.7547 - val_loss: 0.5782 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4874 - accuracy: 0.7643
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7636 - val_loss: 0.5479 - val_accuracy: 0.7156 - lr: 0.0010
253/253 [==============================] - 0s 699us/step
Independent Testing Matthews Correlation:  0.40165172592797427
Confusion Matrix :
 [[2658 1390]
 [1038 3009]]
Accuracy on test set:    0.7000617665225448
Sensitivity:    0.7435137138621201 	 Specificity:    0.6566205533596838
Precision  : 0.6840190952489202
Area Under Curve:    0.700067133610902
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5848 - accuracy: 0.6861 - val_loss: 0.5484 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7247 - val_loss: 0.5440 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7332 - val_loss: 0.5394 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7434 - val_loss: 0.5390 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5019 - accuracy: 0.7514 - val_loss: 0.5405 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.7614 - val_loss: 0.5410 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4775 - accuracy: 0.7703 - val_loss: 0.5463 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4655 - accuracy: 0.7783 - val_loss: 0.5471 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4540 - accuracy: 0.7856 - val_loss: 0.5514 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4401 - accuracy: 0.7931
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4404 - accuracy: 0.7931 - val_loss: 0.5570 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 692us/step
Independent Testing Matthews Correlation:  0.41477123563088986
Confusion Matrix :
 [[2672 1376]
 [1000 3047]]
Accuracy on test set:    0.706485484867202
Sensitivity:    0.7529033852236224 	 Specificity:    0.6600790513833992
Precision  : 0.6888989373728239
Area Under Curve:    0.7064912183035108
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5882 - accuracy: 0.6836 - val_loss: 0.5503 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7215 - val_loss: 0.5330 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7323 - val_loss: 0.5305 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7387 - val_loss: 0.5307 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.7474 - val_loss: 0.5312 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4995 - accuracy: 0.7546 - val_loss: 0.5301 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.7634 - val_loss: 0.5370 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7699 - val_loss: 0.5354 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4664 - accuracy: 0.7786
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4663 - accuracy: 0.7789 - val_loss: 0.5407 - val_accuracy: 0.7234 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4211317335763199
Confusion Matrix :
 [[2863 1184]
 [1159 2889]]
Accuracy on test set:    0.7105620753551575
Sensitivity:    0.7136857707509882 	 Specificity:    0.707437608104769
Precision  : 0.7093051804566658
Area Under Curve:    0.7105616894278787
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5966 - accuracy: 0.6749 - val_loss: 0.5536 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5492 - accuracy: 0.7193 - val_loss: 0.5374 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7334 - val_loss: 0.5293 - val_accuracy: 0.7330 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7417 - val_loss: 0.5314 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7497 - val_loss: 0.5402 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7572 - val_loss: 0.5307 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7674 - val_loss: 0.5361 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4683 - accuracy: 0.7765
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7764 - val_loss: 0.5408 - val_accuracy: 0.7285 - lr: 0.0010
253/253 [==============================] - 0s 716us/step
Independent Testing Matthews Correlation:  0.4245011235901923
Confusion Matrix :
 [[2792 1255]
 [1076 2972]]
Accuracy on test set:    0.7120444718962322
Sensitivity:    0.7341897233201581 	 Specificity:    0.6898937484556461
Precision  : 0.7030991246747101
Area Under Curve:    0.7120417358879022
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5878 - accuracy: 0.6849 - val_loss: 0.5542 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7217 - val_loss: 0.5483 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7328 - val_loss: 0.5590 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7415 - val_loss: 0.5478 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7494 - val_loss: 0.5539 - val_accuracy: 0.7187 - lr: 0.0010

Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7575 - val_loss: 0.5501 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4836 - accuracy: 0.7655 - val_loss: 0.5505 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7753 - val_loss: 0.5590 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4578 - accuracy: 0.7834 - val_loss: 0.5604 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4450 - accuracy: 0.7925 - val_loss: 0.5658 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4314 - accuracy: 0.7983 - val_loss: 0.5697 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4189 - accuracy: 0.8068 - val_loss: 0.5942 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 13/400
249/257 [============================>.] - ETA: 0s - loss: 0.4079 - accuracy: 0.8123
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4088 - accuracy: 0.8119 - val_loss: 0.5849 - val_accuracy: 0.7105 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4047602626345941
Confusion Matrix :
 [[2999 1048]
 [1366 2681]]
Accuracy on test set:    0.7017543859649122
Sensitivity:    0.6624660242154683 	 Specificity:    0.7410427477143563
Precision  : 0.7189595065701261
Area Under Curve:    0.7017543859649122
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5848 - accuracy: 0.6862 - val_loss: 0.5583 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7231 - val_loss: 0.5504 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7323 - val_loss: 0.5478 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7419 - val_loss: 0.5491 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7484 - val_loss: 0.5490 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4970 - accuracy: 0.7554 - val_loss: 0.5492 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7643 - val_loss: 0.5505 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.7727 - val_loss: 0.5564 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4585 - accuracy: 0.7813 - val_loss: 0.5595 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4463 - accuracy: 0.7895
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4468 - accuracy: 0.7889 - val_loss: 0.5548 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 787us/step
Independent Testing Matthews Correlation:  0.43699641105097675
Confusion Matrix :
 [[2823 1224]
 [1056 2991]]
Accuracy on test set:    0.7183098591549296
Sensitivity:    0.7390659747961453 	 Specificity:    0.6975537435137139
Precision  : 0.7096085409252669
Area Under Curve:    0.7183098591549295
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5861 - accuracy: 0.6855 - val_loss: 0.5499 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7246 - val_loss: 0.5486 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7325 - val_loss: 0.5415 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7423 - val_loss: 0.5395 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7497 - val_loss: 0.5446 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7569 - val_loss: 0.5428 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4861 - accuracy: 0.7650 - val_loss: 0.5496 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4738 - accuracy: 0.7740 - val_loss: 0.5532 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4605 - accuracy: 0.7816 - val_loss: 0.5545 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4488 - accuracy: 0.7902 - val_loss: 0.5580 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4358 - accuracy: 0.7973 - val_loss: 0.5630 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4214 - accuracy: 0.8062 - val_loss: 0.5743 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 13/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4071 - accuracy: 0.8148
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4074 - accuracy: 0.8144 - val_loss: 0.5735 - val_accuracy: 0.7172 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.404765027344277
Confusion Matrix :
 [[2822 1225]
 [1184 2863]]
Accuracy on test set:    0.7023721275018532
Sensitivity:    0.707437608104769 	 Specificity:    0.6973066468989375
Precision  : 0.7003424657534246
Area Under Curve:    0.7023721275018532
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5863 - accuracy: 0.6875 - val_loss: 0.5547 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7221 - val_loss: 0.5445 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7319 - val_loss: 0.5430 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7397 - val_loss: 0.5469 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7493 - val_loss: 0.5463 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7559 - val_loss: 0.5470 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7648 - val_loss: 0.5447 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4711 - accuracy: 0.7735 - val_loss: 0.5512 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4600 - accuracy: 0.7824 - val_loss: 0.5486 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4465 - accuracy: 0.7909 - val_loss: 0.5540 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4337 - accuracy: 0.7992 - val_loss: 0.5633 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4213 - accuracy: 0.8070 - val_loss: 0.5633 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4077 - accuracy: 0.8132 - val_loss: 0.5693 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 14/400
253/257 [============================>.] - ETA: 0s - loss: 0.3969 - accuracy: 0.8201
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3971 - accuracy: 0.8199 - val_loss: 0.5762 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4289205612718726
Confusion Matrix :
 [[2954 1093]
 [1219 2828]]
Accuracy on test set:    0.7143563133185076
Sensitivity:    0.6987892265875958 	 Specificity:    0.7299234000494194
Precision  : 0.7212445804641673
Area Under Curve:    0.7143563133185076
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5908 - accuracy: 0.6815 - val_loss: 0.5565 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5492 - accuracy: 0.7194 - val_loss: 0.5565 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5326 - accuracy: 0.7315 - val_loss: 0.5472 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5228 - accuracy: 0.7389 - val_loss: 0.5479 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7448 - val_loss: 0.5472 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7526 - val_loss: 0.5522 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4900 - accuracy: 0.7626 - val_loss: 0.5487 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7675 - val_loss: 0.5535 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7779 - val_loss: 0.5642 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4559 - accuracy: 0.7850
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4571 - accuracy: 0.7843 - val_loss: 0.5610 - val_accuracy: 0.7089 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.439893364162856
Confusion Matrix :
 [[3162  885]
 [1396 2651]]
Accuracy on test set:    0.7181863108475414
Sensitivity:    0.6550531257721769 	 Specificity:    0.7813194959229058
Precision  : 0.7497171945701357
Area Under Curve:    0.7181863108475414
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5904 - accuracy: 0.6823 - val_loss: 0.5555 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5507 - accuracy: 0.7184 - val_loss: 0.5520 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5363 - accuracy: 0.7303 - val_loss: 0.5502 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5239 - accuracy: 0.7380 - val_loss: 0.5472 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7465 - val_loss: 0.5518 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5033 - accuracy: 0.7529 - val_loss: 0.5523 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7611 - val_loss: 0.5521 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7712 - val_loss: 0.5519 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4656 - accuracy: 0.7795 - val_loss: 0.5622 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4529 - accuracy: 0.7883 - val_loss: 0.5608 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4385 - accuracy: 0.7970 - val_loss: 0.5693 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - ETA: 0s - loss: 0.4248 - accuracy: 0.8049
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4248 - accuracy: 0.8049 - val_loss: 0.5706 - val_accuracy: 0.7154 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.475132396421279
Confusion Matrix :
 [[3073  974]
 [1152 2895]]
Accuracy on test set:    0.7373362984927107
Sensitivity:    0.7153446997776131 	 Specificity:    0.7593278972078082
Precision  : 0.748255363142931
Area Under Curve:    0.7373362984927107
(8094, 2560) (8094,)
Mean MCC = 0.4253 + 0.0209 and Mean AUC = 0.7121 + 0.0105
Mean Sensitivity = 0.7122 + 0.0313 and Mean Specificity = 0.7121 + 0.0386 and Mean Accuracy = 0.7121 + 0.0105
Mean Precision = 0.7133 + 0.0210





Seed   : 169270
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5857 - accuracy: 0.6859 - val_loss: 0.5695 - val_accuracy: 0.7021 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7246 - val_loss: 0.5574 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5267 - accuracy: 0.7350 - val_loss: 0.5552 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7448 - val_loss: 0.5557 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7492 - val_loss: 0.5563 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7581 - val_loss: 0.5656 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7658 - val_loss: 0.5611 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4699 - accuracy: 0.7737
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4700 - accuracy: 0.7740 - val_loss: 0.5706 - val_accuracy: 0.7073 - lr: 0.0010
253/253 [==============================] - 0s 745us/step
Independent Testing Matthews Correlation:  0.4072531173923702
Confusion Matrix :
 [[2580 1468]
 [ 945 3102]]
Accuracy on test set:    0.7019147621988882
Sensitivity:    0.7664936990363233 	 Specificity:    0.6373517786561265
Precision  : 0.6787746170678337
Area Under Curve:    0.7019227388462248
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5885 - accuracy: 0.6858 - val_loss: 0.5608 - val_accuracy: 0.7058 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7249 - val_loss: 0.5533 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7349 - val_loss: 0.5560 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7430 - val_loss: 0.5529 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 5/400

257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7503 - val_loss: 0.5526 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7599 - val_loss: 0.5593 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4805 - accuracy: 0.7674 - val_loss: 0.5614 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4686 - accuracy: 0.7764 - val_loss: 0.5611 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4567 - accuracy: 0.7831 - val_loss: 0.5652 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4436 - accuracy: 0.7923
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4441 - accuracy: 0.7921 - val_loss: 0.5791 - val_accuracy: 0.7021 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4107239076689063
Confusion Matrix :
 [[2758 1290]
 [1097 2950]]
Accuracy on test set:    0.7051266213712168
Sensitivity:    0.7289350135903138 	 Specificity:    0.6813241106719368
Precision  : 0.6957547169811321
Area Under Curve:    0.7051295621311253
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5903 - accuracy: 0.6816 - val_loss: 0.5540 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7221 - val_loss: 0.5431 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7299 - val_loss: 0.5428 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5211 - accuracy: 0.7407 - val_loss: 0.5429 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.7477 - val_loss: 0.5434 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7545 - val_loss: 0.5436 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7625 - val_loss: 0.5488 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4766 - accuracy: 0.7694
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4762 - accuracy: 0.7703 - val_loss: 0.5587 - val_accuracy: 0.7132 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41487751841460513
Confusion Matrix :
 [[2618 1429]
 [ 951 3097]]
Accuracy on test set:    0.7059913526868438
Sensitivity:    0.7650691699604744 	 Specificity:    0.6468989374845565
Precision  : 0.6842686699072028
Area Under Curve:    0.7059840537225153
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5915 - accuracy: 0.6822 - val_loss: 0.5512 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5484 - accuracy: 0.7204 - val_loss: 0.5411 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5340 - accuracy: 0.7311 - val_loss: 0.5411 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5232 - accuracy: 0.7383 - val_loss: 0.5409 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5131 - accuracy: 0.7460 - val_loss: 0.5398 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7511 - val_loss: 0.5413 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.7603 - val_loss: 0.5446 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7669 - val_loss: 0.5464 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4696 - accuracy: 0.7763
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4706 - accuracy: 0.7759 - val_loss: 0.5503 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 943us/step
Independent Testing Matthews Correlation:  0.4327957113168803
Confusion Matrix :
 [[3000 1047]
 [1251 2797]]
Accuracy on test set:    0.7161210623841878
Sensitivity:    0.6909584980237155 	 Specificity:    0.7412898443291327
Precision  : 0.727627471383975
Area Under Curve:    0.716124171176424
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5896 - accuracy: 0.6822 - val_loss: 0.5502 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7215 - val_loss: 0.5437 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7328 - val_loss: 0.5415 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7415 - val_loss: 0.5427 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7497 - val_loss: 0.5428 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7575 - val_loss: 0.5428 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7657 - val_loss: 0.5502 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4731 - accuracy: 0.7724 - val_loss: 0.5516 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4621 - accuracy: 0.7797 - val_loss: 0.5622 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4478 - accuracy: 0.7892
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4480 - accuracy: 0.7891 - val_loss: 0.5633 - val_accuracy: 0.7148 - lr: 0.0010
253/253 [==============================] - 0s 880us/step
Independent Testing Matthews Correlation:  0.4178106893230908
Confusion Matrix :
 [[2730 1317]
 [1043 3004]]
Accuracy on test set:    0.7084259945638745
Sensitivity:    0.7422782307882382 	 Specificity:    0.6745737583395107
Precision  : 0.6952094422587364
Area Under Curve:    0.7084259945638745
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5891 - accuracy: 0.6840 - val_loss: 0.5501 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7234 - val_loss: 0.5448 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7329 - val_loss: 0.5417 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7414 - val_loss: 0.5406 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7478 - val_loss: 0.5413 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5006 - accuracy: 0.7537 - val_loss: 0.5411 - val_accuracy: 0.7224 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7618 - val_loss: 0.5439 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4801 - accuracy: 0.7702 - val_loss: 0.5466 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 9/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4700 - accuracy: 0.7772
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.7767 - val_loss: 0.5461 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 967us/step
Independent Testing Matthews Correlation:  0.4341640358044148
Confusion Matrix :
 [[2999 1048]
 [1244 2803]]
Accuracy on test set:    0.7168272794662713
Sensitivity:    0.6926118112181863 	 Specificity:    0.7410427477143563
Precision  : 0.7278628927551285
Area Under Curve:    0.7168272794662713
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5870 - accuracy: 0.6862 - val_loss: 0.5522 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7227 - val_loss: 0.5450 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7326 - val_loss: 0.5403 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7419 - val_loss: 0.5475 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7496 - val_loss: 0.5406 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7578 - val_loss: 0.5453 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7661 - val_loss: 0.5474 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4699 - accuracy: 0.7749 - val_loss: 0.5504 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4562 - accuracy: 0.7847 - val_loss: 0.5510 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4428 - accuracy: 0.7927
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4429 - accuracy: 0.7927 - val_loss: 0.5595 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 781us/step
Independent Testing Matthews Correlation:  0.4306101947316301
Confusion Matrix :
 [[2838 1209]
 [1096 2951]]
Accuracy on test set:    0.7152211514702248
Sensitivity:    0.7291821102050902 	 Specificity:    0.7012601927353596
Precision  : 0.709375
Area Under Curve:    0.7152211514702248
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5874 - accuracy: 0.6845 - val_loss: 0.5512 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7222 - val_loss: 0.5455 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7323 - val_loss: 0.5401 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7413 - val_loss: 0.5382 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7484 - val_loss: 0.5404 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4986 - accuracy: 0.7569 - val_loss: 0.5414 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4863 - accuracy: 0.7650 - val_loss: 0.5460 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7732 - val_loss: 0.5430 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4612 - accuracy: 0.7828
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4611 - accuracy: 0.7826 - val_loss: 0.5544 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 834us/step
Independent Testing Matthews Correlation:  0.43135441143124564
Confusion Matrix :
 [[2716 1331]
 [ 977 3070]]
Accuracy on test set:    0.7148505065480603
Sensitivity:    0.7585866073634792 	 Specificity:    0.6711144057326415
Precision  : 0.6975687343785504
Area Under Curve:    0.7148505065480604
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5886 - accuracy: 0.6844 - val_loss: 0.5496 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7191 - val_loss: 0.5430 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7321 - val_loss: 0.5484 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5221 - accuracy: 0.7376 - val_loss: 0.5396 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7481 - val_loss: 0.5436 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7563 - val_loss: 0.5424 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.7641 - val_loss: 0.5464 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4733 - accuracy: 0.7733 - val_loss: 0.5452 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4613 - accuracy: 0.7816 - val_loss: 0.5560 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4482 - accuracy: 0.7906
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4490 - accuracy: 0.7902 - val_loss: 0.5527 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 942us/step
Independent Testing Matthews Correlation:  0.45022159142123336
Confusion Matrix :
 [[2949 1098]
 [1127 2920]]
Accuracy on test set:    0.72510501606128
Sensitivity:    0.7215221151470225 	 Specificity:    0.7286879169755375
Precision  : 0.7267297162767546
Area Under Curve:    0.7251050160612799
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5936 - accuracy: 0.6795 - val_loss: 0.5543 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5525 - accuracy: 0.7176 - val_loss: 0.5450 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5365 - accuracy: 0.7303 - val_loss: 0.5431 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5256 - accuracy: 0.7374 - val_loss: 0.5418 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5138 - accuracy: 0.7454 - val_loss: 0.5413 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5024 - accuracy: 0.7525 - val_loss: 0.5442 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4891 - accuracy: 0.7639
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.7633 - val_loss: 0.5463 - val_accuracy: 0.7167 - lr: 0.0010
253/253 [==============================] - 0s 863us/step
Independent Testing Matthews Correlation:  0.46271336187876216
Confusion Matrix :
 [[3235  812]
 [1381 2666]]
Accuracy on test set:    0.729058561897702
Sensitivity:    0.6587595749938225 	 Specificity:    0.7993575488015814
Precision  : 0.7665324899367453
Area Under Curve:    0.729058561897702
(8094, 2560) (8094,)
Mean MCC = 0.4293 + 0.0166 and Mean AUC = 0.7139 + 0.0083
Mean Sensitivity = 0.7254 + 0.0338 and Mean Specificity = 0.7023 + 0.0475 and Mean Accuracy = 0.7139 + 0.0083
Mean Precision = 0.7110 + 0.0251





Seed   : 779016
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5843 - accuracy: 0.6857 - val_loss: 0.5516 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7248 - val_loss: 0.5464 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7349 - val_loss: 0.5512 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7434 - val_loss: 0.5545 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5054 - accuracy: 0.7501 - val_loss: 0.5503 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7578 - val_loss: 0.5548 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4841 - accuracy: 0.7654 - val_loss: 0.5536 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4698 - accuracy: 0.7753 - val_loss: 0.5640 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4590 - accuracy: 0.7831 - val_loss: 0.5603 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4455 - accuracy: 0.7914 - val_loss: 0.5652 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4344 - accuracy: 0.7978 - val_loss: 0.5736 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4210 - accuracy: 0.8056 - val_loss: 0.5824 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4080 - accuracy: 0.8140 - val_loss: 0.5888 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 14/400
250/257 [============================>.] - ETA: 0s - loss: 0.3975 - accuracy: 0.8200
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3973 - accuracy: 0.8200 - val_loss: 0.5787 - val_accuracy: 0.7102 - lr: 0.0010
253/253 [==============================] - 0s 820us/step
Independent Testing Matthews Correlation:  0.3917734446261657
Confusion Matrix :
 [[2785 1263]
 [1199 2848]]
Accuracy on test set:    0.6958616429894997
Sensitivity:    0.7037311588831233 	 Specificity:    0.6879940711462451
Precision  : 0.6927754804183897
Area Under Curve:    0.6958626150146843
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6827 - val_loss: 0.5641 - val_accuracy: 0.7034 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7223 - val_loss: 0.5598 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7343 - val_loss: 0.5541 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7405 - val_loss: 0.5505 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7513 - val_loss: 0.5556 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7578 - val_loss: 0.5537 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4848 - accuracy: 0.7647 - val_loss: 0.5684 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4733 - accuracy: 0.7727 - val_loss: 0.5585 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4610 - accuracy: 0.7820 - val_loss: 0.5644 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4485 - accuracy: 0.7903 - val_loss: 0.5779 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4357 - accuracy: 0.7969
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4358 - accuracy: 0.7970 - val_loss: 0.5852 - val_accuracy: 0.7078 - lr: 0.0010
253/253 [==============================] - 0s 984us/step
Independent Testing Matthews Correlation:  0.4219073156559101
Confusion Matrix :
 [[2735 1313]
 [1031 3016]]
Accuracy on test set:    0.710438542310068
Sensitivity:    0.7452433901655547 	 Specificity:    0.6756422924901185
Precision  : 0.6966966966966966
Area Under Curve:    0.7104428413278367
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5869 - accuracy: 0.6842 - val_loss: 0.5535 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7214 - val_loss: 0.5421 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7341 - val_loss: 0.5393 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7413 - val_loss: 0.5400 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7484 - val_loss: 0.5436 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7544 - val_loss: 0.5443 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.7640 - val_loss: 0.5478 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4738 - accuracy: 0.7729
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7723 - val_loss: 0.5460 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4311653164288396
Confusion Matrix :
 [[2763 1284]
 [1022 3026]]
Accuracy on test set:    0.7151327980234713
Sensitivity:    0.7475296442687747 	 Specificity:    0.6827279466271312
Precision  : 0.7020881670533643
Area Under Curve:    0.7151287954479529
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5884 - accuracy: 0.6830 - val_loss: 0.5440 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7218 - val_loss: 0.5363 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7320 - val_loss: 0.5348 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7398 - val_loss: 0.5326 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7484 - val_loss: 0.5361 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.7552 - val_loss: 0.5427 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.7627 - val_loss: 0.5395 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4779 - accuracy: 0.7694 - val_loss: 0.5445 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4662 - accuracy: 0.7800 - val_loss: 0.5445 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4555 - accuracy: 0.7863
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4554 - accuracy: 0.7866 - val_loss: 0.5513 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41969702007023973
Confusion Matrix :
 [[2905 1142]
 [1207 2841]]
Accuracy on test set:    0.7098208770846202
Sensitivity:    0.7018280632411067 	 Specificity:    0.7178156659253768
Precision  : 0.713281446146121
Area Under Curve:    0.7098218645832418
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5909 - accuracy: 0.6813 - val_loss: 0.5556 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7201 - val_loss: 0.5476 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7318 - val_loss: 0.5445 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7396 - val_loss: 0.5483 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7474 - val_loss: 0.5446 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7549 - val_loss: 0.5470 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7641 - val_loss: 0.5537 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4733 - accuracy: 0.7721
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4728 - accuracy: 0.7723 - val_loss: 0.5531 - val_accuracy: 0.7175 - lr: 0.0010
253/253 [==============================] - 0s 831us/step
Independent Testing Matthews Correlation:  0.43759644128356345
Confusion Matrix :
 [[2813 1234]
 [1044 3003]]
Accuracy on test set:    0.7185569557697059
Sensitivity:    0.7420311341734618 	 Specificity:    0.69508277736595
Precision  : 0.7087561954212886
Area Under Curve:    0.7185569557697059
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5901 - accuracy: 0.6850 - val_loss: 0.5497 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7223 - val_loss: 0.5549 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7336 - val_loss: 0.5424 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7412 - val_loss: 0.5444 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7510 - val_loss: 0.5519 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7597 - val_loss: 0.5494 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4803 - accuracy: 0.7673 - val_loss: 0.5493 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4690 - accuracy: 0.7757
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7756 - val_loss: 0.5620 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4528487431749091
Confusion Matrix :
 [[2793 1254]
 [ 965 3082]]
Accuracy on test set:    0.7258463059056091
Sensitivity:    0.7615517667407956 	 Specificity:    0.6901408450704225
Precision  : 0.7107933579335793
Area Under Curve:    0.7258463059056091
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5885 - accuracy: 0.6823 - val_loss: 0.5502 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7223 - val_loss: 0.5492 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7346 - val_loss: 0.5400 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7421 - val_loss: 0.5395 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7499 - val_loss: 0.5429 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7584 - val_loss: 0.5470 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7669 - val_loss: 0.5483 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4688 - accuracy: 0.7772
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4695 - accuracy: 0.7770 - val_loss: 0.5496 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 723us/step
Independent Testing Matthews Correlation:  0.42204566931970966
Confusion Matrix :
 [[2887 1160]
 [1179 2868]]
Accuracy on test set:    0.7110205090190265
Sensitivity:    0.7086730911786508 	 Specificity:    0.713367926859402
Precision  : 0.7120158887785502
Area Under Curve:    0.7110205090190265
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5882 - accuracy: 0.6854 - val_loss: 0.5510 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7233 - val_loss: 0.5428 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7311 - val_loss: 0.5410 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5213 - accuracy: 0.7388 - val_loss: 0.5395 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7480 - val_loss: 0.5459 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7574 - val_loss: 0.5426 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4851 - accuracy: 0.7662
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7659 - val_loss: 0.5446 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4416775569706014
Confusion Matrix :
 [[2772 1275]
 [ 989 3058]]
Accuracy on test set:    0.7202866320731406
Sensitivity:    0.7556214479861626 	 Specificity:    0.6849518161601186
Precision  : 0.7057465958919917
Area Under Curve:    0.7202866320731406
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5962 - accuracy: 0.6767 - val_loss: 0.5564 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5498 - accuracy: 0.7206 - val_loss: 0.5478 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7321 - val_loss: 0.5451 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5223 - accuracy: 0.7391 - val_loss: 0.5441 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5133 - accuracy: 0.7454 - val_loss: 0.5478 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7550 - val_loss: 0.5481 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4941 - accuracy: 0.7597
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7594 - val_loss: 0.5497 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4388967709116407
Confusion Matrix :
 [[2943 1104]
 [1167 2880]]
Accuracy on test set:    0.7194217939214232
Sensitivity:    0.7116382505559674 	 Specificity:    0.7272053372868792
Precision  : 0.7228915662650602
Area Under Curve:    0.7194217939214234
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5935 - accuracy: 0.6787 - val_loss: 0.5584 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5497 - accuracy: 0.7200 - val_loss: 0.5501 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5352 - accuracy: 0.7284 - val_loss: 0.5494 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5242 - accuracy: 0.7392 - val_loss: 0.5495 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5140 - accuracy: 0.7442 - val_loss: 0.5505 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5034 - accuracy: 0.7540 - val_loss: 0.5547 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4924 - accuracy: 0.7621 - val_loss: 0.5532 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7696 - val_loss: 0.5566 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4682 - accuracy: 0.7776 - val_loss: 0.5566 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4566 - accuracy: 0.7858 - val_loss: 0.5715 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4428 - accuracy: 0.7936 - val_loss: 0.5704 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4334 - accuracy: 0.7991 - val_loss: 0.5732 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4197 - accuracy: 0.8069 - val_loss: 0.5862 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 14/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4066 - accuracy: 0.8139
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4069 - accuracy: 0.8138 - val_loss: 0.5920 - val_accuracy: 0.7115 - lr: 0.0010
253/253 [==============================] - 0s 868us/step
Independent Testing Matthews Correlation:  0.4754513645664493
Confusion Matrix :
 [[3055  992]
 [1132 2915]]
Accuracy on test set:    0.737583395107487
Sensitivity:    0.7202866320731406 	 Specificity:    0.7548801581418334
Precision  : 0.7460967494241105
Area Under Curve:    0.737583395107487
(8094, 2560) (8094,)
Mean MCC = 0.4333 + 0.0211 and Mean AUC = 0.7164 + 0.0105
Mean Sensitivity = 0.7298 + 0.0217 and Mean Specificity = 0.7030 + 0.0235 and Mean Accuracy = 0.7164 + 0.0105
Mean Precision = 0.7111 + 0.0142





Seed   : 445600
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5858 - accuracy: 0.6846 - val_loss: 0.5541 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7241 - val_loss: 0.5495 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7351 - val_loss: 0.5487 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7418 - val_loss: 0.5485 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7493 - val_loss: 0.5601 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7557 - val_loss: 0.5530 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4839 - accuracy: 0.7649
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7647 - val_loss: 0.5547 - val_accuracy: 0.7098 - lr: 0.0010
253/253 [==============================] - 0s 787us/step
Independent Testing Matthews Correlation:  0.4034518068418775
Confusion Matrix :
 [[2644 1404]
 [1018 3029]]
Accuracy on test set:    0.7008029647930821
Sensitivity:    0.7484556461576476 	 Specificity:    0.6531620553359684
Precision  : 0.6832844574780058
Area Under Curve:    0.7008088507468081
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5873 - accuracy: 0.6853 - val_loss: 0.5596 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7253 - val_loss: 0.5491 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7351 - val_loss: 0.5470 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7414 - val_loss: 0.5482 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7497 - val_loss: 0.5493 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7551 - val_loss: 0.5507 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4858 - accuracy: 0.7652 - val_loss: 0.5571 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4723 - accuracy: 0.7753
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4733 - accuracy: 0.7744 - val_loss: 0.5569 - val_accuracy: 0.7056 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4219875753445275
Confusion Matrix :
 [[2768 1280]
 [1062 2985]]
Accuracy on test set:    0.7106856084002471
Sensitivity:    0.737583395107487 	 Specificity:    0.6837944664031621
Precision  : 0.6998827667057445
Area Under Curve:    0.7106889307553246
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5899 - accuracy: 0.6813 - val_loss: 0.5476 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7218 - val_loss: 0.5426 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7303 - val_loss: 0.5398 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7396 - val_loss: 0.5431 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7463 - val_loss: 0.5368 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7555 - val_loss: 0.5382 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7629 - val_loss: 0.5394 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7706 - val_loss: 0.5430 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4641 - accuracy: 0.7789 - val_loss: 0.5476 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4527 - accuracy: 0.7868 - val_loss: 0.5532 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4415 - accuracy: 0.7942 - val_loss: 0.5585 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4309 - accuracy: 0.8021
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4307 - accuracy: 0.8024 - val_loss: 0.5612 - val_accuracy: 0.7226 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4351594961033022
Confusion Matrix :
 [[2811 1236]
 [1052 2996]]
Accuracy on test set:    0.7173563928350833
Sensitivity:    0.7401185770750988 	 Specificity:    0.6945885841363973
Precision  : 0.7079395085066162
Area Under Curve:    0.717353580605748
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5939 - accuracy: 0.6791 - val_loss: 0.5496 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7223 - val_loss: 0.5405 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7317 - val_loss: 0.5393 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7410 - val_loss: 0.5394 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7489 - val_loss: 0.5369 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7540 - val_loss: 0.5368 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4858 - accuracy: 0.7622 - val_loss: 0.5383 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.7740 - val_loss: 0.5419 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4602 - accuracy: 0.7814 - val_loss: 0.5449 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4474 - accuracy: 0.7894 - val_loss: 0.5501 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4331 - accuracy: 0.7977 - val_loss: 0.5557 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4204 - accuracy: 0.8062 - val_loss: 0.5610 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 13/400
250/257 [============================>.] - ETA: 0s - loss: 0.4087 - accuracy: 0.8139
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4089 - accuracy: 0.8140 - val_loss: 0.5769 - val_accuracy: 0.7234 - lr: 0.0010
253/253 [==============================] - 0s 838us/step
Independent Testing Matthews Correlation:  0.41271564091038215
Confusion Matrix :
 [[2590 1457]
 [ 934 3114]]
Accuracy on test set:    0.7046324891908585
Sensitivity:    0.7692687747035574 	 Specificity:    0.6399802322708179
Precision  : 0.6812513673156858
Area Under Curve:    0.7046245034871876
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5866 - accuracy: 0.6844 - val_loss: 0.5513 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7231 - val_loss: 0.5402 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5268 - accuracy: 0.7354 - val_loss: 0.5384 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5149 - accuracy: 0.7430 - val_loss: 0.5427 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7515 - val_loss: 0.5402 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7599 - val_loss: 0.5438 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7681 - val_loss: 0.5499 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4668 - accuracy: 0.7784 - val_loss: 0.5573 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4535 - accuracy: 0.7844
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4535 - accuracy: 0.7844 - val_loss: 0.5505 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 763us/step
Independent Testing Matthews Correlation:  0.4183836694599018
Confusion Matrix :
 [[2901 1146]
 [1208 2839]]
Accuracy on test set:    0.7091672844082036
Sensitivity:    0.701507289350136 	 Specificity:    0.7168272794662713
Precision  : 0.7124215809284818
Area Under Curve:    0.7091672844082036
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5901 - accuracy: 0.6813 - val_loss: 0.5510 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7211 - val_loss: 0.5381 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7326 - val_loss: 0.5346 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7387 - val_loss: 0.5391 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7468 - val_loss: 0.5391 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7569 - val_loss: 0.5358 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.7649 - val_loss: 0.5379 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4734 - accuracy: 0.7733
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4738 - accuracy: 0.7732 - val_loss: 0.5382 - val_accuracy: 0.7271 - lr: 0.0010

253/253 [==============================] - 0s 772us/step
Independent Testing Matthews Correlation:  0.43072774495716776
Confusion Matrix :
 [[2922 1125]
 [1179 2868]]
Accuracy on test set:    0.7153446997776131
Sensitivity:    0.7086730911786508 	 Specificity:    0.7220163083765753
Precision  : 0.7182569496619083
Area Under Curve:    0.7153446997776132
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5896 - accuracy: 0.6837 - val_loss: 0.5455 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7202 - val_loss: 0.5370 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5334 - accuracy: 0.7318 - val_loss: 0.5393 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7384 - val_loss: 0.5379 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5109 - accuracy: 0.7473 - val_loss: 0.5438 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5000 - accuracy: 0.7538 - val_loss: 0.5380 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4887 - accuracy: 0.7617
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4899 - accuracy: 0.7610 - val_loss: 0.5415 - val_accuracy: 0.7261 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43023728510320774
Confusion Matrix :
 [[2994 1053]
 [1255 2792]]
Accuracy on test set:    0.7148505065480603
Sensitivity:    0.6898937484556461 	 Specificity:    0.7398072646404744
Precision  : 0.7261378413524057
Area Under Curve:    0.7148505065480601
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5884 - accuracy: 0.6822 - val_loss: 0.5458 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7218 - val_loss: 0.5386 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7317 - val_loss: 0.5366 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7404 - val_loss: 0.5355 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5105 - accuracy: 0.7470 - val_loss: 0.5376 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4995 - accuracy: 0.7555 - val_loss: 0.5410 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.7621 - val_loss: 0.5395 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4774 - accuracy: 0.7722 - val_loss: 0.5408 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4649 - accuracy: 0.7796 - val_loss: 0.5490 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4531 - accuracy: 0.7868 - val_loss: 0.5494 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4426 - accuracy: 0.7929 - val_loss: 0.5559 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4301 - accuracy: 0.8016 - val_loss: 0.5631 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 13/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4193 - accuracy: 0.8079
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4194 - accuracy: 0.8080 - val_loss: 0.5777 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 953us/step
Independent Testing Matthews Correlation:  0.4339102780607754
Confusion Matrix :
 [[2692 1355]
 [ 945 3102]]
Accuracy on test set:    0.7158388930071659
Sensitivity:    0.7664936990363233 	 Specificity:    0.6651840869780083
Precision  : 0.6959838456360781
Area Under Curve:    0.7158388930071657
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5923 - accuracy: 0.6816 - val_loss: 0.5503 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5480 - accuracy: 0.7202 - val_loss: 0.5433 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5328 - accuracy: 0.7308 - val_loss: 0.5392 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7401 - val_loss: 0.5380 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7482 - val_loss: 0.5428 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7552 - val_loss: 0.5407 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7644 - val_loss: 0.5470 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4762 - accuracy: 0.7709 - val_loss: 0.5565 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4644 - accuracy: 0.7806 - val_loss: 0.5533 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4493 - accuracy: 0.7894
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4493 - accuracy: 0.7894 - val_loss: 0.5591 - val_accuracy: 0.7229 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.45911729794766826
Confusion Matrix :
 [[2938 1109]
 [1080 2967]]
Accuracy on test set:    0.7295527551272547
Sensitivity:    0.7331356560415122 	 Specificity:    0.7259698542129973
Precision  : 0.7279195289499509
Area Under Curve:    0.7295527551272547
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5983 - accuracy: 0.6734 - val_loss: 0.5586 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5521 - accuracy: 0.7168 - val_loss: 0.5555 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5349 - accuracy: 0.7303 - val_loss: 0.5463 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5234 - accuracy: 0.7380 - val_loss: 0.5465 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7478 - val_loss: 0.5460 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7538 - val_loss: 0.5512 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4896 - accuracy: 0.7618 - val_loss: 0.5511 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4750 - accuracy: 0.7721 - val_loss: 0.5559 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4619 - accuracy: 0.7808 - val_loss: 0.5572 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4504 - accuracy: 0.7869
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4505 - accuracy: 0.7868 - val_loss: 0.5638 - val_accuracy: 0.7135 - lr: 0.0010
253/253 [==============================] - 0s 787us/step
Independent Testing Matthews Correlation:  0.4718497424252397
Confusion Matrix :
 [[3116  931]
 [1211 2836]]
Accuracy on test set:    0.7353595255744997
Sensitivity:    0.7007659995058068 	 Specificity:    0.7699530516431925
Precision  : 0.7528537297584285
Area Under Curve:    0.7353595255744996
(8094, 2560) (8094,)
Mean MCC = 0.4318 + 0.0195 and Mean AUC = 0.7154 + 0.0100
Mean Sensitivity = 0.7296 + 0.0267 and Mean Specificity = 0.7011 + 0.0390 and Mean Accuracy = 0.7154 + 0.0100
Mean Precision = 0.7106 + 0.0208





Seed   : 21749
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5876 - accuracy: 0.6852 - val_loss: 0.5561 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7241 - val_loss: 0.5479 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7340 - val_loss: 0.5516 - val_accuracy: 0.7054 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7396 - val_loss: 0.5455 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7494 - val_loss: 0.5546 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7554 - val_loss: 0.5489 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.7630 - val_loss: 0.5501 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4740 - accuracy: 0.7722 - val_loss: 0.5495 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4624 - accuracy: 0.7810 - val_loss: 0.5536 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4487 - accuracy: 0.7892 - val_loss: 0.5635 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 11/400
250/257 [============================>.] - ETA: 0s - loss: 0.4347 - accuracy: 0.7973
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4348 - accuracy: 0.7972 - val_loss: 0.5692 - val_accuracy: 0.7105 - lr: 0.0010
253/253 [==============================] - 0s 773us/step
Independent Testing Matthews Correlation:  0.42001373295617983
Confusion Matrix :
 [[2959 1089]
 [1260 2787]]
Accuracy on test set:    0.7098208770846202
Sensitivity:    0.6886582653817642 	 Specificity:    0.7309782608695652
Precision  : 0.7190402476780186
Area Under Curve:    0.7098182631256647
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5893 - accuracy: 0.6845 - val_loss: 0.5566 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7233 - val_loss: 0.5491 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7356 - val_loss: 0.5453 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7409 - val_loss: 0.5463 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7510 - val_loss: 0.5464 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4970 - accuracy: 0.7563 - val_loss: 0.5507 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4862 - accuracy: 0.7641
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4861 - accuracy: 0.7642 - val_loss: 0.5545 - val_accuracy: 0.7116 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41859274538552976
Confusion Matrix :
 [[2755 1293]
 [1063 2984]]
Accuracy on test set:    0.7089561457689932
Sensitivity:    0.7373362984927107 	 Specificity:    0.6805830039525692
Precision  : 0.6976852934299743
Area Under Curve:    0.7089596512226398
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5875 - accuracy: 0.6841 - val_loss: 0.5512 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7229 - val_loss: 0.5418 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7333 - val_loss: 0.5385 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7420 - val_loss: 0.5382 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7506 - val_loss: 0.5392 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7575 - val_loss: 0.5388 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7652 - val_loss: 0.5413 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4726 - accuracy: 0.7731 - val_loss: 0.5421 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4606 - accuracy: 0.7803 - val_loss: 0.5471 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4483 - accuracy: 0.7894 - val_loss: 0.5497 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 11/400
249/257 [============================>.] - ETA: 0s - loss: 0.4361 - accuracy: 0.7979
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4363 - accuracy: 0.7978 - val_loss: 0.5628 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4200375589364255
Confusion Matrix :
 [[2642 1405]
 [ 953 3095]]
Accuracy on test set:    0.7087090796788141
Sensitivity:    0.7645750988142292 	 Specificity:    0.6528292562391895
Precision  : 0.6877777777777778
Area Under Curve:    0.7087021775267094
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5881 - accuracy: 0.6824 - val_loss: 0.5497 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7226 - val_loss: 0.5405 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7338 - val_loss: 0.5417 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7423 - val_loss: 0.5357 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7522 - val_loss: 0.5370 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7587 - val_loss: 0.5416 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - ETA: 0s - loss: 0.4806 - accuracy: 0.7693
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4806 - accuracy: 0.7693 - val_loss: 0.5431 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 858us/step

Independent Testing Matthews Correlation:  0.42916744780009725
Confusion Matrix :
 [[2840 1207]
 [1104 2944]]
Accuracy on test set:    0.7145151327980235
Sensitivity:    0.7272727272727273 	 Specificity:    0.7017543859649122
Precision  : 0.709226692363286
Area Under Curve:    0.7145135566188198
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5834 - accuracy: 0.6874 - val_loss: 0.5512 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7219 - val_loss: 0.5439 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7332 - val_loss: 0.5432 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7424 - val_loss: 0.5438 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7497 - val_loss: 0.5440 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7581 - val_loss: 0.5444 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7676 - val_loss: 0.5501 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4683 - accuracy: 0.7754 - val_loss: 0.5509 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4539 - accuracy: 0.7858 - val_loss: 0.5593 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4406 - accuracy: 0.7944 - val_loss: 0.5613 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 11/400
251/257 [============================>.] - ETA: 0s - loss: 0.4278 - accuracy: 0.8032
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4279 - accuracy: 0.8032 - val_loss: 0.5712 - val_accuracy: 0.7137 - lr: 0.0010
253/253 [==============================] - 0s 791us/step
Independent Testing Matthews Correlation:  0.41508135531304985
Confusion Matrix :
 [[2692 1355]
 [1018 3029]]
Accuracy on test set:    0.706819866567828
Sensitivity:    0.7484556461576476 	 Specificity:    0.6651840869780083
Precision  : 0.6909215328467153
Area Under Curve:    0.706819866567828
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5807 - accuracy: 0.6905 - val_loss: 0.5516 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7233 - val_loss: 0.5439 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7338 - val_loss: 0.5401 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7414 - val_loss: 0.5437 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7496 - val_loss: 0.5417 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7582 - val_loss: 0.5448 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7660 - val_loss: 0.5463 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4717 - accuracy: 0.7731
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7731 - val_loss: 0.5475 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42624212893867314
Confusion Matrix :
 [[2883 1164]
 [1158 2889]]
Accuracy on test set:    0.7131208302446257
Sensitivity:    0.7138621200889548 	 Specificity:    0.7123795404002965
Precision  : 0.7128053293856402
Area Under Curve:    0.7131208302446256
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5941 - accuracy: 0.6777 - val_loss: 0.5500 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5481 - accuracy: 0.7204 - val_loss: 0.5407 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7326 - val_loss: 0.5368 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7401 - val_loss: 0.5397 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5128 - accuracy: 0.7475 - val_loss: 0.5412 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.7537 - val_loss: 0.5387 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7619 - val_loss: 0.5388 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7692 - val_loss: 0.5430 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4654 - accuracy: 0.7783 - val_loss: 0.5476 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4548 - accuracy: 0.7861 - val_loss: 0.5535 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4429 - accuracy: 0.7925 - val_loss: 0.5601 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4293 - accuracy: 0.8000 - val_loss: 0.5627 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4203 - accuracy: 0.8061 - val_loss: 0.5717 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - ETA: 0s - loss: 0.4071 - accuracy: 0.8164
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4071 - accuracy: 0.8164 - val_loss: 0.5837 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 841us/step
Independent Testing Matthews Correlation:  0.4186031479372437
Confusion Matrix :
 [[2850 1197]
 [1156 2891]]
Accuracy on test set:    0.7092908327155918
Sensitivity:    0.7143563133185076 	 Specificity:    0.704225352112676
Precision  : 0.7071917808219178
Area Under Curve:    0.7092908327155918
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5883 - accuracy: 0.6836 - val_loss: 0.5478 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7188 - val_loss: 0.5386 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7327 - val_loss: 0.5365 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7396 - val_loss: 0.5380 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5108 - accuracy: 0.7475 - val_loss: 0.5336 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7562 - val_loss: 0.5400 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7652 - val_loss: 0.5364 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7746 - val_loss: 0.5411 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4571 - accuracy: 0.7843 - val_loss: 0.5502 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4441 - accuracy: 0.7926 - val_loss: 0.5549 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4293 - accuracy: 0.8023 - val_loss: 0.5706 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 12/400
254/257 [============================>.] - ETA: 0s - loss: 0.4169 - accuracy: 0.8076
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4166 - accuracy: 0.8077 - val_loss: 0.5722 - val_accuracy: 0.7172 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4402434570075379
Confusion Matrix :
 [[2723 1324]
 [ 949 3098]]
Accuracy on test set:    0.7191746973066468
Sensitivity:    0.7655053125772177 	 Specificity:    0.6728440820360762
Precision  : 0.7005879692446857
Area Under Curve:    0.7191746973066468
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5931 - accuracy: 0.6799 - val_loss: 0.5562 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5491 - accuracy: 0.7195 - val_loss: 0.5434 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7291 - val_loss: 0.5426 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5226 - accuracy: 0.7376 - val_loss: 0.5405 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5130 - accuracy: 0.7448 - val_loss: 0.5438 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5019 - accuracy: 0.7532 - val_loss: 0.5454 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.7585 - val_loss: 0.5459 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7680 - val_loss: 0.5523 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4668 - accuracy: 0.7782
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4671 - accuracy: 0.7780 - val_loss: 0.5503 - val_accuracy: 0.7227 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.45913249929346417
Confusion Matrix :
 [[3085  962]
 [1231 2816]]
Accuracy on test set:    0.729058561897702
Sensitivity:    0.6958240672102792 	 Specificity:    0.7622930565851248
Precision  : 0.745367919534145
Area Under Curve:    0.7290585618977019
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5922 - accuracy: 0.6804 - val_loss: 0.5576 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5505 - accuracy: 0.7190 - val_loss: 0.5487 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5351 - accuracy: 0.7318 - val_loss: 0.5449 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5221 - accuracy: 0.7394 - val_loss: 0.5464 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5126 - accuracy: 0.7472 - val_loss: 0.5489 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7532 - val_loss: 0.5464 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4885 - accuracy: 0.7620
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4887 - accuracy: 0.7620 - val_loss: 0.5491 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 751us/step
Independent Testing Matthews Correlation:  0.4801106115880029
Confusion Matrix :
 [[3151  896]
 [1214 2833]]
Accuracy on test set:    0.7393130714109216
Sensitivity:    0.7000247096614777 	 Specificity:    0.7786014331603657
Precision  : 0.7597211048538483
Area Under Curve:    0.7393130714109216
(8094, 2560) (8094,)
Mean MCC = 0.4327 + 0.0202 and Mean AUC = 0.7159 + 0.0100
Mean Sensitivity = 0.7256 + 0.0264 and Mean Specificity = 0.7062 + 0.0392 and Mean Accuracy = 0.7159 + 0.0100
Mean Precision = 0.7130 + 0.0220





Seed   : 635354
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5877 - accuracy: 0.6860 - val_loss: 0.5591 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7234 - val_loss: 0.5514 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7352 - val_loss: 0.5487 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7432 - val_loss: 0.5495 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7497 - val_loss: 0.5590 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7564 - val_loss: 0.5569 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.7629 - val_loss: 0.5548 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7683 - val_loss: 0.5566 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4663 - accuracy: 0.7780 - val_loss: 0.5564 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4549 - accuracy: 0.7867 - val_loss: 0.5656 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 11/400
252/257 [============================>.] - ETA: 0s - loss: 0.4431 - accuracy: 0.7927
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4435 - accuracy: 0.7925 - val_loss: 0.5743 - val_accuracy: 0.7082 - lr: 0.0010
253/253 [==============================] - 0s 950us/step
Independent Testing Matthews Correlation:  0.395988684628556
Confusion Matrix :
 [[2570 1478]
 [ 979 3068]]
Accuracy on test set:    0.6964793082149475
Sensitivity:    0.7580924141339264 	 Specificity:    0.6348814229249012
Precision  : 0.6748790145182578
Area Under Curve:    0.6964869185294137
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5842 - accuracy: 0.6879 - val_loss: 0.5727 - val_accuracy: 0.6977 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7226 - val_loss: 0.5529 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7342 - val_loss: 0.5495 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7398 - val_loss: 0.5508 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7491 - val_loss: 0.5509 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 6/400

257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7558 - val_loss: 0.5517 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4857 - accuracy: 0.7646 - val_loss: 0.5589 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4736 - accuracy: 0.7724 - val_loss: 0.5565 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4603 - accuracy: 0.7807 - val_loss: 0.5636 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4467 - accuracy: 0.7895
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4468 - accuracy: 0.7895 - val_loss: 0.5642 - val_accuracy: 0.7069 - lr: 0.0010
253/253 [==============================] - 0s 827us/step
Independent Testing Matthews Correlation:  0.42763923402803483
Confusion Matrix :
 [[2848 1200]
 [1117 2930]]
Accuracy on test set:    0.713773934527486
Sensitivity:    0.7239930812947862 	 Specificity:    0.7035573122529645
Precision  : 0.7094430992736077
Area Under Curve:    0.7137751967738752
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5844 - accuracy: 0.6879 - val_loss: 0.5499 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7226 - val_loss: 0.5412 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7335 - val_loss: 0.5381 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7420 - val_loss: 0.5375 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7513 - val_loss: 0.5370 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.7604 - val_loss: 0.5374 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7695 - val_loss: 0.5403 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7775 - val_loss: 0.5428 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4550 - accuracy: 0.7859 - val_loss: 0.5524 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4402 - accuracy: 0.7962 - val_loss: 0.5520 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
252/257 [============================>.] - ETA: 0s - loss: 0.4279 - accuracy: 0.8034
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4278 - accuracy: 0.8032 - val_loss: 0.5565 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 908us/step
Independent Testing Matthews Correlation:  0.40933122237350494
Confusion Matrix :
 [[2956 1091]
 [1302 2746]]
Accuracy on test set:    0.7043854231006794
Sensitivity:    0.6783596837944664 	 Specificity:    0.730417593278972
Precision  : 0.7156632786030753
Area Under Curve:    0.7043886385367192
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5864 - accuracy: 0.6857 - val_loss: 0.5481 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7222 - val_loss: 0.5399 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7317 - val_loss: 0.5390 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7411 - val_loss: 0.5370 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7475 - val_loss: 0.5353 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7586 - val_loss: 0.5437 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7655 - val_loss: 0.5483 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4748 - accuracy: 0.7718 - val_loss: 0.5423 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4622 - accuracy: 0.7804 - val_loss: 0.5456 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4520 - accuracy: 0.7867 - val_loss: 0.5553 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4388 - accuracy: 0.7964 - val_loss: 0.5581 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4286 - accuracy: 0.8012 - val_loss: 0.5748 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 13/400
254/257 [============================>.] - ETA: 0s - loss: 0.4153 - accuracy: 0.8093
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4152 - accuracy: 0.8093 - val_loss: 0.5720 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41955737073727345
Confusion Matrix :
 [[2609 1438]
 [ 925 3123]]
Accuracy on test set:    0.7080914144533663
Sensitivity:    0.77149209486166 	 Specificity:    0.644675067951569
Precision  : 0.6847182635386977
Area Under Curve:    0.7080835814066145
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5840 - accuracy: 0.6870 - val_loss: 0.5514 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7230 - val_loss: 0.5534 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7338 - val_loss: 0.5436 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7405 - val_loss: 0.5429 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7493 - val_loss: 0.5459 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7570 - val_loss: 0.5504 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7644 - val_loss: 0.5569 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.7750 - val_loss: 0.5529 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4603 - accuracy: 0.7813
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4604 - accuracy: 0.7814 - val_loss: 0.5590 - val_accuracy: 0.7124 - lr: 0.0010
253/253 [==============================] - 0s 947us/step
Independent Testing Matthews Correlation:  0.42276416052065957
Confusion Matrix :
 [[2974 1073]
 [1265 2782]]
Accuracy on test set:    0.7111440573264146
Sensitivity:    0.6874227823078823 	 Specificity:    0.7348653323449469
Precision  : 0.7216601815823606
Area Under Curve:    0.7111440573264145
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5877 - accuracy: 0.6842 - val_loss: 0.5552 - val_accuracy: 0.7237 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7230 - val_loss: 0.5444 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7342 - val_loss: 0.5416 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5158 - accuracy: 0.7432 - val_loss: 0.5519 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7513 - val_loss: 0.5448 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.7620 - val_loss: 0.5465 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.7672 - val_loss: 0.5477 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4700 - accuracy: 0.7738
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4706 - accuracy: 0.7737 - val_loss: 0.5489 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4255014228252265
Confusion Matrix :
 [[2880 1167]
 [1158 2889]]
Accuracy on test set:    0.712750185322461
Sensitivity:    0.7138621200889548 	 Specificity:    0.7116382505559674
Precision  : 0.7122781065088757
Area Under Curve:    0.7127501853224611
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5846 - accuracy: 0.6869 - val_loss: 0.5530 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7237 - val_loss: 0.5448 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7336 - val_loss: 0.5464 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7429 - val_loss: 0.5438 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7514 - val_loss: 0.5460 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7588 - val_loss: 0.5476 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7666 - val_loss: 0.5486 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4732 - accuracy: 0.7749 - val_loss: 0.5544 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4585 - accuracy: 0.7844
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4586 - accuracy: 0.7843 - val_loss: 0.5576 - val_accuracy: 0.7209 - lr: 0.0010
253/253 [==============================] - 0s 775us/step
Independent Testing Matthews Correlation:  0.42842879609527224
Confusion Matrix :
 [[2773 1274]
 [1042 3005]]
Accuracy on test set:    0.7138621200889548
Sensitivity:    0.7425253274030146 	 Specificity:    0.685198912774895
Precision  : 0.702266884786165
Area Under Curve:    0.7138621200889548
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5909 - accuracy: 0.6798 - val_loss: 0.5551 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7225 - val_loss: 0.5498 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7319 - val_loss: 0.5464 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7413 - val_loss: 0.5461 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7506 - val_loss: 0.5467 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
250/257 [============================>.] - ETA: 0s - loss: 0.4946 - accuracy: 0.7585
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7586 - val_loss: 0.5529 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4346664091091896
Confusion Matrix :
 [[3104  943]
 [1354 2693]]
Accuracy on test set:    0.7162095379293304
Sensitivity:    0.6654311835927847 	 Specificity:    0.7669878922658759
Precision  : 0.7406490649064906
Area Under Curve:    0.7162095379293304
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5912 - accuracy: 0.6798 - val_loss: 0.5557 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5493 - accuracy: 0.7202 - val_loss: 0.5500 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5341 - accuracy: 0.7311 - val_loss: 0.5479 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5247 - accuracy: 0.7359 - val_loss: 0.5579 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5137 - accuracy: 0.7435 - val_loss: 0.5465 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7505 - val_loss: 0.5524 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7581 - val_loss: 0.5501 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7648 - val_loss: 0.5536 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4765 - accuracy: 0.7729 - val_loss: 0.5633 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4653 - accuracy: 0.7791 - val_loss: 0.5630 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4506 - accuracy: 0.7873 - val_loss: 0.5796 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4390 - accuracy: 0.7953 - val_loss: 0.5775 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 13/400
251/257 [============================>.] - ETA: 0s - loss: 0.4293 - accuracy: 0.8008
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4295 - accuracy: 0.8009 - val_loss: 0.5768 - val_accuracy: 0.7124 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4628246760048953
Confusion Matrix :
 [[2945 1102]
 [1072 2975]]
Accuracy on test set:    0.7314059797380776
Sensitivity:    0.7351124289597233 	 Specificity:    0.7276995305164319
Precision  : 0.7297032131469218
Area Under Curve:    0.7314059797380776
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5901 - accuracy: 0.6821 - val_loss: 0.5607 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7201 - val_loss: 0.5532 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7299 - val_loss: 0.5506 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.7386 - val_loss: 0.5524 - val_accuracy: 0.7101 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5115 - accuracy: 0.7472 - val_loss: 0.5550 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7544 - val_loss: 0.5513 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7616 - val_loss: 0.5577 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.7719 - val_loss: 0.5606 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4622 - accuracy: 0.7831 - val_loss: 0.5650 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4485 - accuracy: 0.7911 - val_loss: 0.5648 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4371 - accuracy: 0.7976 - val_loss: 0.5761 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 12/400
255/257 [============================>.] - ETA: 0s - loss: 0.4238 - accuracy: 0.8061
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4240 - accuracy: 0.8059 - val_loss: 0.5823 - val_accuracy: 0.7069 - lr: 0.0010
253/253 [==============================] - 0s 740us/step
Independent Testing Matthews Correlation:  0.4642355104763491
Confusion Matrix :
 [[3164  883]
 [1295 2752]]
Accuracy on test set:    0.7309117865085248
Sensitivity:    0.680009883864591 	 Specificity:    0.7818136891524586
Precision  : 0.7570839064649243
Area Under Curve:    0.7309117865085248
(8094, 2560) (8094,)
Mean MCC = 0.4291 + 0.0201 and Mean AUC = 0.7139 + 0.0102
Mean Sensitivity = 0.7156 + 0.0347 and Mean Specificity = 0.7122 + 0.0450 and Mean Accuracy = 0.7139 + 0.0102
Mean Precision = 0.7148 + 0.0233





Seed   : 847331
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5866 - accuracy: 0.6860 - val_loss: 0.5620 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7228 - val_loss: 0.5531 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7357 - val_loss: 0.5513 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7435 - val_loss: 0.5515 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7506 - val_loss: 0.5620 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7597 - val_loss: 0.5567 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7668 - val_loss: 0.5587 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4685 - accuracy: 0.7761 - val_loss: 0.5708 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4552 - accuracy: 0.7852 - val_loss: 0.5740 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4421 - accuracy: 0.7931 - val_loss: 0.5755 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4271 - accuracy: 0.8026 - val_loss: 0.5851 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 12/400
256/257 [============================>.] - ETA: 0s - loss: 0.4133 - accuracy: 0.8089
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4133 - accuracy: 0.8089 - val_loss: 0.5889 - val_accuracy: 0.7090 - lr: 0.0010
253/253 [==============================] - 0s 792us/step
Independent Testing Matthews Correlation:  0.40811661780136554
Confusion Matrix :
 [[2720 1328]
 [1071 2976]]
Accuracy on test set:    0.7036442248301421
Sensitivity:    0.7353595255744997 	 Specificity:    0.6719367588932806
Precision  : 0.6914498141263941
Area Under Curve:    0.7036481422338903
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5864 - accuracy: 0.6865 - val_loss: 0.5575 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5417 - accuracy: 0.7246 - val_loss: 0.5589 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5259 - accuracy: 0.7353 - val_loss: 0.5482 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5126 - accuracy: 0.7448 - val_loss: 0.5471 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5008 - accuracy: 0.7534 - val_loss: 0.5499 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4893 - accuracy: 0.7611 - val_loss: 0.5535 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4763 - accuracy: 0.7714 - val_loss: 0.5542 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4627 - accuracy: 0.7804 - val_loss: 0.5562 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4501 - accuracy: 0.7903
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4503 - accuracy: 0.7902 - val_loss: 0.5590 - val_accuracy: 0.7091 - lr: 0.0010
253/253 [==============================] - 0s 845us/step
Independent Testing Matthews Correlation:  0.4242206527677645
Confusion Matrix :
 [[2718 1330]
 [1006 3041]]
Accuracy on test set:    0.7114268066707844
Sensitivity:    0.7514208055349642 	 Specificity:    0.6714426877470355
Precision  : 0.6957218027911233
Area Under Curve:    0.7114317466409998
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5865 - accuracy: 0.6856 - val_loss: 0.5555 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7225 - val_loss: 0.5472 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7325 - val_loss: 0.5423 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7411 - val_loss: 0.5409 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7492 - val_loss: 0.5423 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7568 - val_loss: 0.5471 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - ETA: 0s - loss: 0.4839 - accuracy: 0.7652
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7652 - val_loss: 0.5444 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41990408746145225
Confusion Matrix :
 [[2772 1275]
 [1075 2973]]
Accuracy on test set:    0.7096973440395306
Sensitivity:    0.7344367588932806 	 Specificity:    0.6849518161601186
Precision  : 0.6998587570621468
Area Under Curve:    0.7096942875266997
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5867 - accuracy: 0.6834 - val_loss: 0.5508 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5432 - accuracy: 0.7236 - val_loss: 0.5402 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7336 - val_loss: 0.5409 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7426 - val_loss: 0.5405 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7503 - val_loss: 0.5416 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7560 - val_loss: 0.5408 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4840 - accuracy: 0.7650
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7650 - val_loss: 0.5439 - val_accuracy: 0.7224 - lr: 0.0010
253/253 [==============================] - 0s 994us/step
Independent Testing Matthews Correlation:  0.4117357972679407
Confusion Matrix :
 [[2858 1189]
 [1192 2856]]
Accuracy on test set:    0.7058678196417542
Sensitivity:    0.7055335968379447 	 Specificity:    0.7062021250308871
Precision  : 0.7060568603213844
Area Under Curve:    0.7058678609344159
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5869 - accuracy: 0.6842 - val_loss: 0.5642 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7231 - val_loss: 0.5497 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7314 - val_loss: 0.5446 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7395 - val_loss: 0.5428 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7481 - val_loss: 0.5441 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7581 - val_loss: 0.5453 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4857 - accuracy: 0.7638 - val_loss: 0.5469 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.7761 - val_loss: 0.5545 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.7814 - val_loss: 0.5643 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4474 - accuracy: 0.7898 - val_loss: 0.5603 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 11/400
256/257 [============================>.] - ETA: 0s - loss: 0.4343 - accuracy: 0.7976
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4342 - accuracy: 0.7977 - val_loss: 0.5817 - val_accuracy: 0.7135 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43241621320112134
Confusion Matrix :
 [[2830 1217]
 [1081 2966]]
Accuracy on test set:    0.7160859896219421
Sensitivity:    0.7328885594267358 	 Specificity:    0.6992834198171485
Precision  : 0.7090604829070045
Area Under Curve:    0.716085989621942
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5920 - accuracy: 0.6800 - val_loss: 0.5563 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.7205 - val_loss: 0.5489 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5324 - accuracy: 0.7321 - val_loss: 0.5447 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7390 - val_loss: 0.5466 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5106 - accuracy: 0.7463 - val_loss: 0.5469 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.7528 - val_loss: 0.5498 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4907 - accuracy: 0.7614 - val_loss: 0.5502 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4783 - accuracy: 0.7684
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7684 - val_loss: 0.5537 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 769us/step
Independent Testing Matthews Correlation:  0.42941881064430815
Confusion Matrix :
 [[2775 1272]
 [1040 3007]]
Accuracy on test set:    0.7143563133185076
Sensitivity:    0.7430195206325674 	 Specificity:    0.6856931060044478
Precision  : 0.7027342837111474
Area Under Curve:    0.7143563133185076
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.6016 - accuracy: 0.6721 - val_loss: 0.5555 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5499 - accuracy: 0.7194 - val_loss: 0.5464 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5330 - accuracy: 0.7326 - val_loss: 0.5453 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7393 - val_loss: 0.5474 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7473 - val_loss: 0.5425 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7543 - val_loss: 0.5477 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4883 - accuracy: 0.7607 - val_loss: 0.5503 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.7708 - val_loss: 0.5540 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4617 - accuracy: 0.7820 - val_loss: 0.5568 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4502 - accuracy: 0.7903
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4503 - accuracy: 0.7901 - val_loss: 0.5637 - val_accuracy: 0.7145 - lr: 0.0010
253/253 [==============================] - 0s 807us/step
Independent Testing Matthews Correlation:  0.4193414414967127
Confusion Matrix :
 [[2891 1156]
 [1194 2853]]
Accuracy on test set:    0.7096614776377563
Sensitivity:    0.7049666419570052 	 Specificity:    0.7143563133185076
Precision  : 0.7116487902220004
Area Under Curve:    0.7096614776377563
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5864 - accuracy: 0.6856 - val_loss: 0.5595 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7213 - val_loss: 0.5415 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7343 - val_loss: 0.5429 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7424 - val_loss: 0.5429 - val_accuracy: 0.7227 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7479 - val_loss: 0.5418 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7569 - val_loss: 0.5399 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4843 - accuracy: 0.7646
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4848 - accuracy: 0.7647 - val_loss: 0.5429 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 953us/step
Independent Testing Matthews Correlation:  0.43280583703362097
Confusion Matrix :
 [[2751 1296]
 [1004 3043]]
Accuracy on test set:    0.7158388930071659
Sensitivity:    0.751914998764517 	 Specificity:    0.6797627872498146
Precision  : 0.7013136667434893
Area Under Curve:    0.7158388930071659
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5917 - accuracy: 0.6796 - val_loss: 0.5520 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5500 - accuracy: 0.7199 - val_loss: 0.5491 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5344 - accuracy: 0.7310 - val_loss: 0.5398 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5216 - accuracy: 0.7400 - val_loss: 0.5388 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5117 - accuracy: 0.7488 - val_loss: 0.5400 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7558 - val_loss: 0.5408 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7662 - val_loss: 0.5505 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4702 - accuracy: 0.7744
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4702 - accuracy: 0.7747 - val_loss: 0.5539 - val_accuracy: 0.7213 - lr: 0.0010
253/253 [==============================] - 0s 837us/step
Independent Testing Matthews Correlation:  0.45545601672615926
Confusion Matrix :
 [[2977 1070]
 [1134 2913]]
Accuracy on test set:    0.7276995305164319
Sensitivity:    0.7197924388435878 	 Specificity:    0.735606622189276
Precision  : 0.7313582726587999
Area Under Curve:    0.7276995305164319
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5922 - accuracy: 0.6816 - val_loss: 0.5515 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5510 - accuracy: 0.7195 - val_loss: 0.5437 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5363 - accuracy: 0.7285 - val_loss: 0.5412 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.7356 - val_loss: 0.5445 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7413 - val_loss: 0.5455 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7505 - val_loss: 0.5485 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4946 - accuracy: 0.7570
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7566 - val_loss: 0.5491 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.5036119436477787
Confusion Matrix :
 [[2975 1072]
 [ 938 3109]]
Accuracy on test set:    0.7516679021497406
Sensitivity:    0.7682233753397578 	 Specificity:    0.7351124289597233
Precision  : 0.7436020090887348
Area Under Curve:    0.7516679021497406
(8094, 2560) (8094,)
Mean MCC = 0.4337 + 0.0265 and Mean AUC = 0.7166 + 0.0133
Mean Sensitivity = 0.7348 + 0.0193 and Mean Specificity = 0.6984 + 0.0227 and Mean Accuracy = 0.7166 + 0.0133
Mean Precision = 0.7093 + 0.0154





Seed   : 895562
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5836 - accuracy: 0.6898 - val_loss: 0.5591 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5423 - accuracy: 0.7232 - val_loss: 0.5511 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7341 - val_loss: 0.5533 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7416 - val_loss: 0.5495 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7484 - val_loss: 0.5518 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.7565 - val_loss: 0.5547 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4855 - accuracy: 0.7637
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4858 - accuracy: 0.7634 - val_loss: 0.5551 - val_accuracy: 0.7091 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42442859923993703
Confusion Matrix :
 [[2737 1311]
 [1023 3024]]
Accuracy on test set:    0.7116738727609636
Sensitivity:    0.7472201630837657 	 Specificity:    0.6761363636363636
Precision  : 0.6975778546712803
Area Under Curve:    0.7116782633600647
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5922 - accuracy: 0.6804 - val_loss: 0.5581 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7235 - val_loss: 0.5485 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7325 - val_loss: 0.5491 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7417 - val_loss: 0.5437 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7491 - val_loss: 0.5482 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4987 - accuracy: 0.7571 - val_loss: 0.5498 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.7645 - val_loss: 0.5471 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4781 - accuracy: 0.7706 - val_loss: 0.5545 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4664 - accuracy: 0.7788 - val_loss: 0.5589 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4539 - accuracy: 0.7860 - val_loss: 0.5600 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4427 - accuracy: 0.7933 - val_loss: 0.5621 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 12/400
253/257 [============================>.] - ETA: 0s - loss: 0.4300 - accuracy: 0.8014
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4300 - accuracy: 0.8015 - val_loss: 0.5643 - val_accuracy: 0.7111 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40852748599244837
Confusion Matrix :
 [[2860 1188]
 [1206 2841]]
Accuracy on test set:    0.7042618900555899
Sensitivity:    0.7020014825796886 	 Specificity:    0.7065217391304348
Precision  : 0.7051377513030529
Area Under Curve:    0.7042616108550618
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 8ms/step - loss: 0.5867 - accuracy: 0.6858 - val_loss: 0.5488 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7240 - val_loss: 0.5389 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7353 - val_loss: 0.5408 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.7447 - val_loss: 0.5364 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5019 - accuracy: 0.7514 - val_loss: 0.5402 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7630 - val_loss: 0.5414 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7731 - val_loss: 0.5390 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4614 - accuracy: 0.7825
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4619 - accuracy: 0.7821 - val_loss: 0.5423 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41000965931305905
Confusion Matrix :
 [[2861 1186]
 [1202 2846]]
Accuracy on test set:    0.7050030883261272
Sensitivity:    0.7030632411067194 	 Specificity:    0.7069434148752162
Precision  : 0.7058531746031746
Area Under Curve:    0.7050033279909679
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5899 - accuracy: 0.6833 - val_loss: 0.5478 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7211 - val_loss: 0.5377 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5324 - accuracy: 0.7317 - val_loss: 0.5379 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5209 - accuracy: 0.7411 - val_loss: 0.5399 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5124 - accuracy: 0.7453 - val_loss: 0.5371 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5021 - accuracy: 0.7527 - val_loss: 0.5369 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.7613 - val_loss: 0.5417 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4801 - accuracy: 0.7699 - val_loss: 0.5420 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7775 - val_loss: 0.5534 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4564 - accuracy: 0.7846 - val_loss: 0.5486 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4447 - accuracy: 0.7927 - val_loss: 0.5551 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4339 - accuracy: 0.7990 - val_loss: 0.5572 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 13/400
252/257 [============================>.] - ETA: 0s - loss: 0.4228 - accuracy: 0.8055
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4226 - accuracy: 0.8057 - val_loss: 0.5605 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 980us/step
Independent Testing Matthews Correlation:  0.4046000382704662
Confusion Matrix :
 [[2866 1181]
 [1229 2819]]
Accuracy on test set:    0.7022853613341569
Sensitivity:    0.696393280632411 	 Specificity:    0.708178897949098
Precision  : 0.70475
Area Under Curve:    0.7022860892907546
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5934 - accuracy: 0.6782 - val_loss: 0.5684 - val_accuracy: 0.7009 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7233 - val_loss: 0.5492 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7347 - val_loss: 0.5474 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7403 - val_loss: 0.5453 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7496 - val_loss: 0.5488 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7577 - val_loss: 0.5474 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7658 - val_loss: 0.5516 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4717 - accuracy: 0.7736
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7736 - val_loss: 0.5571 - val_accuracy: 0.7157 - lr: 0.0010
253/253 [==============================] - 0s 970us/step
Independent Testing Matthews Correlation:  0.418642517686031
Confusion Matrix :
 [[2905 1142]
 [1211 2836]]
Accuracy on test set:    0.7092908327155918
Sensitivity:    0.7007659995058068 	 Specificity:    0.7178156659253768
Precision  : 0.7129210658622424
Area Under Curve:    0.7092908327155918
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5883 - accuracy: 0.6847 - val_loss: 0.5555 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7240 - val_loss: 0.5461 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7348 - val_loss: 0.5466 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7425 - val_loss: 0.5576 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7509 - val_loss: 0.5456 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7571 - val_loss: 0.5463 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7668 - val_loss: 0.5509 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4740 - accuracy: 0.7727 - val_loss: 0.5530 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4592 - accuracy: 0.7839 - val_loss: 0.5603 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4482 - accuracy: 0.7901 - val_loss: 0.5601 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4366 - accuracy: 0.7969 - val_loss: 0.5663 - val_accuracy: 0.7159 - lr: 0.0010

Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4232 - accuracy: 0.8056 - val_loss: 0.5743 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4121 - accuracy: 0.8122 - val_loss: 0.5839 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3982 - accuracy: 0.8196 - val_loss: 0.5868 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 15/400
247/257 [===========================>..] - ETA: 0s - loss: 0.3885 - accuracy: 0.8267
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3880 - accuracy: 0.8269 - val_loss: 0.6129 - val_accuracy: 0.7121 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4096902024614555
Confusion Matrix :
 [[2729 1318]
 [1074 2973]]
Accuracy on test set:    0.7044724487274524
Sensitivity:    0.7346182357301705 	 Specificity:    0.6743266617247343
Precision  : 0.6928454905616407
Area Under Curve:    0.7044724487274524
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6842 - val_loss: 0.5550 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7243 - val_loss: 0.5484 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7315 - val_loss: 0.5454 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7400 - val_loss: 0.5454 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7471 - val_loss: 0.5426 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7562 - val_loss: 0.5488 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7640 - val_loss: 0.5487 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4754 - accuracy: 0.7718 - val_loss: 0.5498 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4620 - accuracy: 0.7830 - val_loss: 0.5548 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4491 - accuracy: 0.7907
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4493 - accuracy: 0.7903 - val_loss: 0.5656 - val_accuracy: 0.7152 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42950709920727936
Confusion Matrix :
 [[2692 1355]
 [ 962 3085]]
Accuracy on test set:    0.7137385717815666
Sensitivity:    0.7622930565851248 	 Specificity:    0.6651840869780083
Precision  : 0.6948198198198198
Area Under Curve:    0.7137385717815665
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5942 - accuracy: 0.6792 - val_loss: 0.5592 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5493 - accuracy: 0.7213 - val_loss: 0.5522 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5358 - accuracy: 0.7298 - val_loss: 0.5480 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5245 - accuracy: 0.7378 - val_loss: 0.5461 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7436 - val_loss: 0.5527 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7506 - val_loss: 0.5476 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7601 - val_loss: 0.5456 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7676 - val_loss: 0.5479 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.7754 - val_loss: 0.5540 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4580 - accuracy: 0.7832 - val_loss: 0.5581 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4448 - accuracy: 0.7910 - val_loss: 0.5610 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4321 - accuracy: 0.7986 - val_loss: 0.5664 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 13/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4201 - accuracy: 0.8054
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4209 - accuracy: 0.8048 - val_loss: 0.5753 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 860us/step
Independent Testing Matthews Correlation:  0.448966090894699
Confusion Matrix :
 [[2780 1267]
 [ 968 3079]]
Accuracy on test set:    0.7238695329873981
Sensitivity:    0.7608104768964665 	 Specificity:    0.6869285890783297
Precision  : 0.708467556373677
Area Under Curve:    0.7238695329873981
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5940 - accuracy: 0.6776 - val_loss: 0.5580 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5488 - accuracy: 0.7206 - val_loss: 0.5562 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5334 - accuracy: 0.7318 - val_loss: 0.5460 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5216 - accuracy: 0.7399 - val_loss: 0.5432 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5121 - accuracy: 0.7465 - val_loss: 0.5443 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7529 - val_loss: 0.5456 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4900 - accuracy: 0.7615 - val_loss: 0.5474 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4784 - accuracy: 0.7688 - val_loss: 0.5490 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4673 - accuracy: 0.7777 - val_loss: 0.5503 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4561 - accuracy: 0.7838
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4558 - accuracy: 0.7840 - val_loss: 0.5625 - val_accuracy: 0.7102 - lr: 0.0010
253/253 [==============================] - 0s 829us/step
Independent Testing Matthews Correlation:  0.45838201856826327
Confusion Matrix :
 [[2815 1232]
 [ 964 3083]]
Accuracy on test set:    0.7286879169755375
Sensitivity:    0.761798863355572 	 Specificity:    0.6955769705955028
Precision  : 0.7144843568945539
Area Under Curve:    0.7286879169755375
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5930 - accuracy: 0.6823 - val_loss: 0.5612 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5515 - accuracy: 0.7183 - val_loss: 0.5517 - val_accuracy: 0.7172 - lr: 0.0010

Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5367 - accuracy: 0.7288 - val_loss: 0.5515 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5242 - accuracy: 0.7363 - val_loss: 0.5493 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7461 - val_loss: 0.5499 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.7545 - val_loss: 0.5506 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4914 - accuracy: 0.7602
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7602 - val_loss: 0.5544 - val_accuracy: 0.7130 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4929166842048148
Confusion Matrix :
 [[2962 1085]
 [ 968 3079]]
Accuracy on test set:    0.7463553249320485
Sensitivity:    0.7608104768964665 	 Specificity:    0.7319001729676303
Precision  : 0.739433237271854
Area Under Curve:    0.7463553249320485
(8094, 2560) (8094,)
Mean MCC = 0.4306 + 0.0268 and Mean AUC = 0.7150 + 0.0133
Mean Sensitivity = 0.7330 + 0.0277 and Mean Specificity = 0.6970 + 0.0201 and Mean Accuracy = 0.7150 + 0.0133
Mean Precision = 0.7076 + 0.0126





Seed   : 627844
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5830 - accuracy: 0.6882 - val_loss: 0.5541 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7254 - val_loss: 0.5486 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5259 - accuracy: 0.7363 - val_loss: 0.5453 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7445 - val_loss: 0.5460 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7507 - val_loss: 0.5481 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7590 - val_loss: 0.5525 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7650 - val_loss: 0.5506 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4718 - accuracy: 0.7748 - val_loss: 0.5590 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4598 - accuracy: 0.7836
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.7836 - val_loss: 0.5600 - val_accuracy: 0.7124 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40521282591883295
Confusion Matrix :
 [[2588 1460]
 [ 960 3087]]
Accuracy on test set:    0.7010500308832612
Sensitivity:    0.7627872498146775 	 Specificity:    0.6393280632411067
Precision  : 0.6789091708819002
Area Under Curve:    0.7010576565278921
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5891 - accuracy: 0.6828 - val_loss: 0.5604 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7237 - val_loss: 0.5496 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7337 - val_loss: 0.5478 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7425 - val_loss: 0.5442 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7500 - val_loss: 0.5486 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7593 - val_loss: 0.5495 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7686 - val_loss: 0.5488 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4675 - accuracy: 0.7763 - val_loss: 0.5526 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4547 - accuracy: 0.7852 - val_loss: 0.5669 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4425 - accuracy: 0.7942
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4424 - accuracy: 0.7944 - val_loss: 0.5751 - val_accuracy: 0.7146 - lr: 0.0010
253/253 [==============================] - 0s 918us/step
Independent Testing Matthews Correlation:  0.42293200992522073
Confusion Matrix :
 [[2632 1416]
 [ 932 3115]]
Accuracy on test set:    0.7099444101297097
Sensitivity:    0.7697059550284161 	 Specificity:    0.650197628458498
Precision  : 0.6874862061355109
Area Under Curve:    0.709951791743457
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5838 - accuracy: 0.6877 - val_loss: 0.5470 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7247 - val_loss: 0.5370 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7336 - val_loss: 0.5333 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7430 - val_loss: 0.5375 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5054 - accuracy: 0.7486 - val_loss: 0.5336 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7585 - val_loss: 0.5342 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7670 - val_loss: 0.5392 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4691 - accuracy: 0.7760
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4692 - accuracy: 0.7758 - val_loss: 0.5377 - val_accuracy: 0.7281 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4088215002859065
Confusion Matrix :
 [[2882 1165]
 [1228 2820]]
Accuracy on test set:    0.7043854231006794
Sensitivity:    0.6966403162055336 	 Specificity:    0.7121324437855201
Precision  : 0.7076537013801757
Area Under Curve:    0.7043863799955268
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5869 - accuracy: 0.6839 - val_loss: 0.5431 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7213 - val_loss: 0.5345 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7336 - val_loss: 0.5346 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7408 - val_loss: 0.5280 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7476 - val_loss: 0.5304 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7565 - val_loss: 0.5395 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4848 - accuracy: 0.7652 - val_loss: 0.5355 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7746 - val_loss: 0.5457 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4587 - accuracy: 0.7822
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4588 - accuracy: 0.7822 - val_loss: 0.5437 - val_accuracy: 0.7240 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4169981002189866
Confusion Matrix :
 [[2650 1397]
 [ 972 3076]]
Accuracy on test set:    0.7073502161828289
Sensitivity:    0.7598814229249012 	 Specificity:    0.6548060291574005
Precision  : 0.6876816454281243
Area Under Curve:    0.7073437260411509
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5882 - accuracy: 0.6846 - val_loss: 0.5504 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7224 - val_loss: 0.5424 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7327 - val_loss: 0.5441 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7403 - val_loss: 0.5424 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7477 - val_loss: 0.5446 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7564 - val_loss: 0.5445 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7649 - val_loss: 0.5493 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.7724 - val_loss: 0.5533 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4610 - accuracy: 0.7809 - val_loss: 0.5576 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4460 - accuracy: 0.7913
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4460 - accuracy: 0.7914 - val_loss: 0.5612 - val_accuracy: 0.7150 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43020516000368175
Confusion Matrix :
 [[2672 1375]
 [ 941 3106]]
Accuracy on test set:    0.7138621200889548
Sensitivity:    0.7674820854954287 	 Specificity:    0.6602421546824808
Precision  : 0.6931488507029681
Area Under Curve:    0.7138621200889548
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5889 - accuracy: 0.6843 - val_loss: 0.5527 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7217 - val_loss: 0.5381 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7337 - val_loss: 0.5392 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7425 - val_loss: 0.5403 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7514 - val_loss: 0.5397 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4911 - accuracy: 0.7607 - val_loss: 0.5456 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4794 - accuracy: 0.7680
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.7684 - val_loss: 0.5543 - val_accuracy: 0.7220 - lr: 0.0010
253/253 [==============================] - 0s 908us/step
Independent Testing Matthews Correlation:  0.4284530924670768
Confusion Matrix :
 [[2752 1295]
 [1022 3025]]
Accuracy on test set:    0.7137385717815666
Sensitivity:    0.7474672596985421 	 Specificity:    0.680009883864591
Precision  : 0.7002314814814815
Area Under Curve:    0.7137385717815665
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5843 - accuracy: 0.6867 - val_loss: 0.5481 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7202 - val_loss: 0.5452 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5267 - accuracy: 0.7344 - val_loss: 0.5386 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5135 - accuracy: 0.7434 - val_loss: 0.5373 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5018 - accuracy: 0.7524 - val_loss: 0.5381 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7605 - val_loss: 0.5385 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4775 - accuracy: 0.7680 - val_loss: 0.5473 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7762 - val_loss: 0.5436 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4540 - accuracy: 0.7854 - val_loss: 0.5504 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4401 - accuracy: 0.7952
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4408 - accuracy: 0.7949 - val_loss: 0.5514 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 811us/step
Independent Testing Matthews Correlation:  0.42939258280952025
Confusion Matrix :
 [[2725 1322]
 [ 993 3054]]
Accuracy on test set:    0.7139856683963429
Sensitivity:    0.7546330615270571 	 Specificity:    0.6733382752656288
Precision  : 0.6978976234003657
Area Under Curve:    0.713985668396343
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5870 - accuracy: 0.6843 - val_loss: 0.5456 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7231 - val_loss: 0.5363 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7351 - val_loss: 0.5338 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7430 - val_loss: 0.5383 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.7505 - val_loss: 0.5338 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7561 - val_loss: 0.5335 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7687 - val_loss: 0.5350 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4693 - accuracy: 0.7753 - val_loss: 0.5435 - val_accuracy: 0.7263 - lr: 0.0010

Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4551 - accuracy: 0.7867 - val_loss: 0.5465 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4426 - accuracy: 0.7943 - val_loss: 0.5435 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4285 - accuracy: 0.8025 - val_loss: 0.5563 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4151 - accuracy: 0.8074 - val_loss: 0.5654 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4011 - accuracy: 0.8184 - val_loss: 0.5629 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3881 - accuracy: 0.8240 - val_loss: 0.5682 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - ETA: 0s - loss: 0.3769 - accuracy: 0.8311
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3769 - accuracy: 0.8311 - val_loss: 0.5828 - val_accuracy: 0.7220 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4247740716793803
Confusion Matrix :
 [[2866 1181]
 [1147 2900]]
Accuracy on test set:    0.7123795404002965
Sensitivity:    0.7165801828514949 	 Specificity:    0.708178897949098
Precision  : 0.7106101445724087
Area Under Curve:    0.7123795404002966
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5901 - accuracy: 0.6825 - val_loss: 0.5471 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5480 - accuracy: 0.7194 - val_loss: 0.5397 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5328 - accuracy: 0.7316 - val_loss: 0.5510 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7399 - val_loss: 0.5335 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7479 - val_loss: 0.5338 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7570 - val_loss: 0.5347 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4848 - accuracy: 0.7652 - val_loss: 0.5370 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4684 - accuracy: 0.7768 - val_loss: 0.5370 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4561 - accuracy: 0.7846 - val_loss: 0.5450 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4421 - accuracy: 0.7942
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7941 - val_loss: 0.5477 - val_accuracy: 0.7286 - lr: 0.0010
253/253 [==============================] - 0s 730us/step
Independent Testing Matthews Correlation:  0.45595027176330105
Confusion Matrix :
 [[2914 1133]
 [1069 2978]]
Accuracy on test set:    0.7279466271312083
Sensitivity:    0.7358537188040524 	 Specificity:    0.7200395354583642
Precision  : 0.7243979567015325
Area Under Curve:    0.7279466271312083
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5946 - accuracy: 0.6782 - val_loss: 0.5493 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5519 - accuracy: 0.7170 - val_loss: 0.5408 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5358 - accuracy: 0.7294 - val_loss: 0.5413 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5240 - accuracy: 0.7380 - val_loss: 0.5358 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7452 - val_loss: 0.5389 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5019 - accuracy: 0.7541 - val_loss: 0.5477 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7602 - val_loss: 0.5366 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7716 - val_loss: 0.5529 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4652 - accuracy: 0.7799 - val_loss: 0.5462 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4514 - accuracy: 0.7869 - val_loss: 0.5511 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4363 - accuracy: 0.7978 - val_loss: 0.5544 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 12/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4230 - accuracy: 0.8047
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4236 - accuracy: 0.8043 - val_loss: 0.5627 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4749352494478467
Confusion Matrix :
 [[3114  933]
 [1196 2851]]
Accuracy on test set:    0.7369656535705461
Sensitivity:    0.7044724487274524 	 Specificity:    0.7694588584136397
Precision  : 0.7534355179704016
Area Under Curve:    0.7369656535705461
(8094, 2560) (8094,)
Mean MCC = 0.4298 + 0.0200 and Mean AUC = 0.7142 + 0.0102
Mean Sensitivity = 0.7416 + 0.0255 and Mean Specificity = 0.6868 + 0.0382 and Mean Accuracy = 0.7142 + 0.0102
Mean Precision = 0.7041 + 0.0206





Seed   : 976711
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5876 - accuracy: 0.6830 - val_loss: 0.5670 - val_accuracy: 0.7023 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7227 - val_loss: 0.5608 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7344 - val_loss: 0.5531 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7435 - val_loss: 0.5584 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7503 - val_loss: 0.5616 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7566 - val_loss: 0.5561 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7646 - val_loss: 0.5607 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 8/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4741 - accuracy: 0.7739
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7735 - val_loss: 0.5663 - val_accuracy: 0.7062 - lr: 0.0010
253/253 [==============================] - 0s 882us/step
Independent Testing Matthews Correlation:  0.41882817068533845
Confusion Matrix :
 [[2689 1359]
 [1000 3047]]
Accuracy on test set:    0.7085855466337245
Sensitivity:    0.7529033852236224 	 Specificity:    0.6642786561264822
Precision  : 0.6915569677712211
Area Under Curve:    0.7085910206750523
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5868 - accuracy: 0.6855 - val_loss: 0.5548 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7228 - val_loss: 0.5470 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7342 - val_loss: 0.5476 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7431 - val_loss: 0.5457 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7500 - val_loss: 0.5498 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7592 - val_loss: 0.5480 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4825 - accuracy: 0.7658
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4831 - accuracy: 0.7652 - val_loss: 0.5524 - val_accuracy: 0.7134 - lr: 0.0010
253/253 [==============================] - 0s 762us/step
Independent Testing Matthews Correlation:  0.4256259999804934
Confusion Matrix :
 [[2711 1337]
 [ 994 3053]]
Accuracy on test set:    0.7120444718962322
Sensitivity:    0.7543859649122807 	 Specificity:    0.6697134387351779
Precision  : 0.6954441913439635
Area Under Curve:    0.7120497018237294
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5869 - accuracy: 0.6857 - val_loss: 0.5455 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7220 - val_loss: 0.5389 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7340 - val_loss: 0.5341 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7416 - val_loss: 0.5337 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7509 - val_loss: 0.5320 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7558 - val_loss: 0.5350 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7647 - val_loss: 0.5455 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7739 - val_loss: 0.5370 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4567 - accuracy: 0.7836 - val_loss: 0.5457 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4467 - accuracy: 0.7890 - val_loss: 0.5537 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4315 - accuracy: 0.7982 - val_loss: 0.5628 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4187 - accuracy: 0.8062 - val_loss: 0.5651 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 13/400
254/257 [============================>.] - ETA: 0s - loss: 0.4068 - accuracy: 0.8132
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4072 - accuracy: 0.8130 - val_loss: 0.5648 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 733us/step
Independent Testing Matthews Correlation:  0.41875580700585485
Confusion Matrix :
 [[2787 1260]
 [1094 2954]]
Accuracy on test set:    0.7092032118591723
Sensitivity:    0.7297430830039525 	 Specificity:    0.6886582653817642
Precision  : 0.7009966777408638
Area Under Curve:    0.7092006741928585
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5889 - accuracy: 0.6826 - val_loss: 0.5472 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7216 - val_loss: 0.5475 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7313 - val_loss: 0.5341 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7407 - val_loss: 0.5335 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7495 - val_loss: 0.5329 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7586 - val_loss: 0.5355 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4825 - accuracy: 0.7651 - val_loss: 0.5426 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4709 - accuracy: 0.7751
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7748 - val_loss: 0.5405 - val_accuracy: 0.7257 - lr: 0.0010
253/253 [==============================] - 0s 792us/step
Independent Testing Matthews Correlation:  0.42137214283155017
Confusion Matrix :
 [[2703 1344]
 [1004 3044]]
Accuracy on test set:    0.7099444101297097
Sensitivity:    0.7519762845849802 	 Specificity:    0.6679021497405485
Precision  : 0.6937101185050136
Area Under Curve:    0.7099392171627645
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5891 - accuracy: 0.6793 - val_loss: 0.5567 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7218 - val_loss: 0.5502 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7335 - val_loss: 0.5498 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7405 - val_loss: 0.5491 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7475 - val_loss: 0.5492 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5006 - accuracy: 0.7538 - val_loss: 0.5523 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7615 - val_loss: 0.5535 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7691 - val_loss: 0.5616 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4684 - accuracy: 0.7781 - val_loss: 0.5576 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4553 - accuracy: 0.7863 - val_loss: 0.5603 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4440 - accuracy: 0.7945 - val_loss: 0.5645 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - ETA: 0s - loss: 0.4329 - accuracy: 0.8010
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4329 - accuracy: 0.8010 - val_loss: 0.5771 - val_accuracy: 0.7148 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4343958620382689
Confusion Matrix :
 [[2902 1145]
 [1144 2903]]
Accuracy on test set:    0.7171979243884359
Sensitivity:    0.717321472695824 	 Specificity:    0.7170743760810477
Precision  : 0.7171442687747036
Area Under Curve:    0.7171979243884358
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5849 - accuracy: 0.6867 - val_loss: 0.5588 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7234 - val_loss: 0.5518 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7355 - val_loss: 0.5494 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7415 - val_loss: 0.5579 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.7511 - val_loss: 0.5529 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7584 - val_loss: 0.5556 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4822 - accuracy: 0.7663
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7662 - val_loss: 0.5598 - val_accuracy: 0.7142 - lr: 0.0010
253/253 [==============================] - 0s 727us/step
Independent Testing Matthews Correlation:  0.433608761880478
Confusion Matrix :
 [[2808 1239]
 [1055 2992]]
Accuracy on test set:    0.7165801828514949
Sensitivity:    0.7393130714109216 	 Specificity:    0.6938472942920682
Precision  : 0.7071614275584968
Area Under Curve:    0.7165801828514948
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5927 - accuracy: 0.6799 - val_loss: 0.5525 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7231 - val_loss: 0.5447 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.7351 - val_loss: 0.5474 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.7443 - val_loss: 0.5482 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.7538 - val_loss: 0.5483 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4911 - accuracy: 0.7620 - val_loss: 0.5427 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4784 - accuracy: 0.7694 - val_loss: 0.5476 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4658 - accuracy: 0.7772 - val_loss: 0.5559 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4524 - accuracy: 0.7866 - val_loss: 0.5580 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4403 - accuracy: 0.7933 - val_loss: 0.5589 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4275 - accuracy: 0.8036
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4279 - accuracy: 0.8033 - val_loss: 0.5710 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 749us/step
Independent Testing Matthews Correlation:  0.42176480067183475
Confusion Matrix :
 [[2781 1266]
 [1076 2971]]
Accuracy on test set:    0.7106498640968619
Sensitivity:    0.7341240425006177 	 Specificity:    0.687175685693106
Precision  : 0.7012036818503659
Area Under Curve:    0.7106498640968618
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5878 - accuracy: 0.6843 - val_loss: 0.5616 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7231 - val_loss: 0.5566 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7329 - val_loss: 0.5464 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7420 - val_loss: 0.5433 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7525 - val_loss: 0.5429 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4924 - accuracy: 0.7603 - val_loss: 0.5450 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.7700 - val_loss: 0.5501 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4659 - accuracy: 0.7783
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4658 - accuracy: 0.7788 - val_loss: 0.5570 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 751us/step
Independent Testing Matthews Correlation:  0.4245406149671868
Confusion Matrix :
 [[2859 1188]
 [1141 2906]]
Accuracy on test set:    0.7122559920929084
Sensitivity:    0.7180627625401532 	 Specificity:    0.7064492216456635
Precision  : 0.709819247679531
Area Under Curve:    0.7122559920929084
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5915 - accuracy: 0.6806 - val_loss: 0.5642 - val_accuracy: 0.7020 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7230 - val_loss: 0.5479 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7349 - val_loss: 0.5599 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7445 - val_loss: 0.5491 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7528 - val_loss: 0.5507 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4923 - accuracy: 0.7595 - val_loss: 0.5531 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7682 - val_loss: 0.5643 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7772 - val_loss: 0.5603 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4567 - accuracy: 0.7841
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4569 - accuracy: 0.7841 - val_loss: 0.5632 - val_accuracy: 0.7137 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4603351282660393
Confusion Matrix :
 [[3020 1027]
 [1158 2889]]
Accuracy on test set:    0.7300469483568075
Sensitivity:    0.7138621200889548 	 Specificity:    0.7462317766246602
Precision  : 0.7377425944841676
Area Under Curve:    0.7300469483568075
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5950 - accuracy: 0.6774 - val_loss: 0.5588 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5504 - accuracy: 0.7214 - val_loss: 0.5525 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5349 - accuracy: 0.7298 - val_loss: 0.5525 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5227 - accuracy: 0.7393 - val_loss: 0.5557 - val_accuracy: 0.7038 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5125 - accuracy: 0.7463 - val_loss: 0.5532 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7542 - val_loss: 0.5568 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4887 - accuracy: 0.7638
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7639 - val_loss: 0.5618 - val_accuracy: 0.7062 - lr: 0.0010
253/253 [==============================] - 0s 827us/step
Independent Testing Matthews Correlation:  0.47692601160137416
Confusion Matrix :
 [[3102  945]
 [1175 2872]]
Accuracy on test set:    0.7380775883370397
Sensitivity:    0.7096614776377563 	 Specificity:    0.7664936990363233
Precision  : 0.7524233691380665
Area Under Curve:    0.7380775883370396
(8094, 2560) (8094,)
Mean MCC = 0.4336 + 0.0186 and Mean AUC = 0.7165 + 0.0094
Mean Sensitivity = 0.7321 + 0.0162 and Mean Specificity = 0.7008 + 0.0323 and Mean Accuracy = 0.7165 + 0.0094
Mean Precision = 0.7107 + 0.0190





Seed   : 652013
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5882 - accuracy: 0.6824 - val_loss: 0.5574 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7247 - val_loss: 0.5540 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7339 - val_loss: 0.5506 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7434 - val_loss: 0.5488 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7502 - val_loss: 0.5576 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7593 - val_loss: 0.5523 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4811 - accuracy: 0.7676 - val_loss: 0.5566 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7767 - val_loss: 0.5595 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.7840 - val_loss: 0.5649 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4420 - accuracy: 0.7938
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7935 - val_loss: 0.5680 - val_accuracy: 0.7087 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3981124788712661
Confusion Matrix :
 [[2896 1152]
 [1285 2762]]
Accuracy on test set:    0.6989499691167387
Sensitivity:    0.6824808500123548 	 Specificity:    0.7154150197628458
Precision  : 0.7056719468574348
Area Under Curve:    0.6989479348876003
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5869 - accuracy: 0.6856 - val_loss: 0.5549 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7240 - val_loss: 0.5507 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5256 - accuracy: 0.7370 - val_loss: 0.5471 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5141 - accuracy: 0.7443 - val_loss: 0.5448 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5028 - accuracy: 0.7537 - val_loss: 0.5527 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.7603 - val_loss: 0.5520 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4775 - accuracy: 0.7706 - val_loss: 0.5545 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4662 - accuracy: 0.7774 - val_loss: 0.5537 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4538 - accuracy: 0.7841
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4538 - accuracy: 0.7839 - val_loss: 0.5637 - val_accuracy: 0.7117 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4217687075590416
Confusion Matrix :
 [[2765 1283]
 [1060 2987]]
Accuracy on test set:    0.7105620753551575
Sensitivity:    0.7380775883370397 	 Specificity:    0.6830533596837944
Precision  : 0.6995316159250585
Area Under Curve:    0.710565474010417
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5865 - accuracy: 0.6853 - val_loss: 0.5455 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7228 - val_loss: 0.5370 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7330 - val_loss: 0.5455 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7429 - val_loss: 0.5359 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7503 - val_loss: 0.5359 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7595 - val_loss: 0.5397 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4809 - accuracy: 0.7672
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7670 - val_loss: 0.5414 - val_accuracy: 0.7237 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4187390821963037
Confusion Matrix :
 [[2789 1258]
 [1096 2952]]
Accuracy on test set:    0.7092032118591723
Sensitivity:    0.7292490118577075 	 Specificity:    0.689152458611317
Precision  : 0.701187648456057
Area Under Curve:    0.7092007352345122
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5872 - accuracy: 0.6851 - val_loss: 0.5432 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7230 - val_loss: 0.5352 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7346 - val_loss: 0.5333 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7422 - val_loss: 0.5330 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7501 - val_loss: 0.5370 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7573 - val_loss: 0.5390 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7643 - val_loss: 0.5428 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7728 - val_loss: 0.5469 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 9/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4595 - accuracy: 0.7809
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4600 - accuracy: 0.7810 - val_loss: 0.5493 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42433765522989647
Confusion Matrix :
 [[2876 1171]
 [1159 2889]]
Accuracy on test set:    0.7121680049413218
Sensitivity:    0.7136857707509882 	 Specificity:    0.7106498640968619
Precision  : 0.711576354679803
Area Under Curve:    0.7121678174239251
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5902 - accuracy: 0.6828 - val_loss: 0.5504 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7214 - val_loss: 0.5430 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7338 - val_loss: 0.5411 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7396 - val_loss: 0.5404 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7476 - val_loss: 0.5465 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7566 - val_loss: 0.5435 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.7644 - val_loss: 0.5478 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7750 - val_loss: 0.5468 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4611 - accuracy: 0.7809 - val_loss: 0.5529 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4457 - accuracy: 0.7923
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4460 - accuracy: 0.7920 - val_loss: 0.5543 - val_accuracy: 0.7193 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4216398350956839
Confusion Matrix :
 [[2919 1128]
 [1213 2834]]
Accuracy on test set:    0.7107734124042501
Sensitivity:    0.700271806276254 	 Specificity:    0.7212750185322461
Precision  : 0.7152953054013125
Area Under Curve:    0.71077341240425
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5895 - accuracy: 0.6823 - val_loss: 0.5515 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7220 - val_loss: 0.5488 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7323 - val_loss: 0.5389 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7418 - val_loss: 0.5386 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7498 - val_loss: 0.5472 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7585 - val_loss: 0.5438 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7681 - val_loss: 0.5518 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4694 - accuracy: 0.7747
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4695 - accuracy: 0.7747 - val_loss: 0.5502 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 812us/step
Independent Testing Matthews Correlation:  0.43242280699740887
Confusion Matrix :
 [[2714 1333]
 [ 971 3076]]
Accuracy on test set:    0.7153446997776131
Sensitivity:    0.7600691870521374 	 Specificity:    0.6706202125030887
Precision  : 0.6976638693581311
Area Under Curve:    0.7153446997776131
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5837 - accuracy: 0.6887 - val_loss: 0.5514 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7244 - val_loss: 0.5456 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5264 - accuracy: 0.7355 - val_loss: 0.5432 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5143 - accuracy: 0.7436 - val_loss: 0.5421 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7511 - val_loss: 0.5412 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7618 - val_loss: 0.5412 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7704 - val_loss: 0.5501 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4652 - accuracy: 0.7771 - val_loss: 0.5617 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4536 - accuracy: 0.7848 - val_loss: 0.5496 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4383 - accuracy: 0.7953 - val_loss: 0.5566 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4270 - accuracy: 0.8040
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4276 - accuracy: 0.8034 - val_loss: 0.5628 - val_accuracy: 0.7197 - lr: 0.0010
253/253 [==============================] - 0s 751us/step
Independent Testing Matthews Correlation:  0.4382095335283196
Confusion Matrix :
 [[2765 1282]
 [ 996 3051]]
Accuracy on test set:    0.7185569557697059
Sensitivity:    0.7538917716827279 	 Specificity:    0.683222139856684
Precision  : 0.7041310870066928
Area Under Curve:    0.7185569557697059
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5899 - accuracy: 0.6820 - val_loss: 0.5504 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7217 - val_loss: 0.5568 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7334 - val_loss: 0.5416 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7438 - val_loss: 0.5442 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7501 - val_loss: 0.5405 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7555 - val_loss: 0.5389 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7643 - val_loss: 0.5441 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4752 - accuracy: 0.7721 - val_loss: 0.5507 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4643 - accuracy: 0.7802 - val_loss: 0.5466 - val_accuracy: 0.7208 - lr: 0.0010

Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4522 - accuracy: 0.7872 - val_loss: 0.5531 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4401 - accuracy: 0.7934 - val_loss: 0.5567 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4280 - accuracy: 0.8030 - val_loss: 0.5653 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4136 - accuracy: 0.8105 - val_loss: 0.5738 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 14/400
253/257 [============================>.] - ETA: 0s - loss: 0.4021 - accuracy: 0.8177
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4022 - accuracy: 0.8177 - val_loss: 0.5739 - val_accuracy: 0.7121 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4159216732845253
Confusion Matrix :
 [[2942 1105]
 [1260 2787]]
Accuracy on test set:    0.7078082530269335
Sensitivity:    0.6886582653817642 	 Specificity:    0.7269582406721028
Precision  : 0.7160842754367934
Area Under Curve:    0.7078082530269336
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5958 - accuracy: 0.6793 - val_loss: 0.5589 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5485 - accuracy: 0.7197 - val_loss: 0.5500 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5339 - accuracy: 0.7308 - val_loss: 0.5545 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5221 - accuracy: 0.7384 - val_loss: 0.5493 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.7463 - val_loss: 0.5495 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5003 - accuracy: 0.7536 - val_loss: 0.5515 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 7/400
252/257 [============================>.] - ETA: 0s - loss: 0.4880 - accuracy: 0.7635
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.7633 - val_loss: 0.5564 - val_accuracy: 0.7106 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4651865159125603
Confusion Matrix :
 [[3016 1031]
 [1134 2913]]
Accuracy on test set:    0.7325179145045713
Sensitivity:    0.7197924388435878 	 Specificity:    0.7452433901655547
Precision  : 0.7385902636916836
Area Under Curve:    0.7325179145045713
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5912 - accuracy: 0.6815 - val_loss: 0.5728 - val_accuracy: 0.7017 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5503 - accuracy: 0.7175 - val_loss: 0.5509 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5346 - accuracy: 0.7310 - val_loss: 0.5540 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5247 - accuracy: 0.7366 - val_loss: 0.5477 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5131 - accuracy: 0.7457 - val_loss: 0.5498 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7545 - val_loss: 0.5501 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.7643 - val_loss: 0.5524 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.7726 - val_loss: 0.5563 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7811 - val_loss: 0.5709 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4493 - accuracy: 0.7903 - val_loss: 0.5662 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4385 - accuracy: 0.7970 - val_loss: 0.5731 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4217 - accuracy: 0.8059
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4218 - accuracy: 0.8059 - val_loss: 0.5809 - val_accuracy: 0.7104 - lr: 0.0010
253/253 [==============================] - 0s 848us/step
Independent Testing Matthews Correlation:  0.4713937982002522
Confusion Matrix :
 [[3033 1014]
 [1126 2921]]
Accuracy on test set:    0.735606622189276
Sensitivity:    0.7217692117617989 	 Specificity:    0.7494440326167532
Precision  : 0.7423125794155019
Area Under Curve:    0.735606622189276
(8094, 2560) (8094,)
Mean MCC = 0.4308 + 0.0213 and Mean AUC = 0.7151 + 0.0106
Mean Sensitivity = 0.7208 + 0.0245 and Mean Specificity = 0.7095 + 0.0258 and Mean Accuracy = 0.7151 + 0.0106
Mean Precision = 0.7132 + 0.0149





Seed   : 71237
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5862 - accuracy: 0.6854 - val_loss: 0.5571 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7268 - val_loss: 0.5498 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5250 - accuracy: 0.7367 - val_loss: 0.5549 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5142 - accuracy: 0.7436 - val_loss: 0.5479 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7522 - val_loss: 0.5651 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4918 - accuracy: 0.7583 - val_loss: 0.5499 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.7690 - val_loss: 0.5541 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4667 - accuracy: 0.7780 - val_loss: 0.5582 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4541 - accuracy: 0.7853 - val_loss: 0.5639 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4405 - accuracy: 0.7929 - val_loss: 0.5736 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4286 - accuracy: 0.8028 - val_loss: 0.5732 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 12/400
253/257 [============================>.] - ETA: 0s - loss: 0.4157 - accuracy: 0.8088
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4160 - accuracy: 0.8089 - val_loss: 0.5872 - val_accuracy: 0.7094 - lr: 0.0010
253/253 [==============================] - 0s 869us/step
Independent Testing Matthews Correlation:  0.4009616254308535
Confusion Matrix :
 [[2591 1457]
 [ 979 3068]]
Accuracy on test set:    0.6990735021618283
Sensitivity:    0.7580924141339264 	 Specificity:    0.6400691699604744
Precision  : 0.6780110497237569
Area Under Curve:    0.6990807920472004
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5867 - accuracy: 0.6869 - val_loss: 0.5705 - val_accuracy: 0.7001 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7235 - val_loss: 0.5550 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7346 - val_loss: 0.5497 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7434 - val_loss: 0.5487 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7497 - val_loss: 0.5509 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7561 - val_loss: 0.5652 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7681 - val_loss: 0.5561 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4724 - accuracy: 0.7734
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7734 - val_loss: 0.5646 - val_accuracy: 0.7072 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4277036911787411
Confusion Matrix :
 [[2684 1364]
 [ 961 3086]]
Accuracy on test set:    0.7127856701667696
Sensitivity:    0.7625401531999012 	 Specificity:    0.6630434782608695
Precision  : 0.6934831460674157
Area Under Curve:    0.7127918157303854
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5921 - accuracy: 0.6821 - val_loss: 0.5504 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7236 - val_loss: 0.5428 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7338 - val_loss: 0.5430 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5154 - accuracy: 0.7445 - val_loss: 0.5387 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7503 - val_loss: 0.5376 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.7611 - val_loss: 0.5398 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4793 - accuracy: 0.7685 - val_loss: 0.5465 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4657 - accuracy: 0.7790 - val_loss: 0.5573 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4521 - accuracy: 0.7873 - val_loss: 0.5563 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4372 - accuracy: 0.7969
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4373 - accuracy: 0.7964 - val_loss: 0.5659 - val_accuracy: 0.7207 - lr: 0.0010
253/253 [==============================] - 0s 742us/step
Independent Testing Matthews Correlation:  0.42216581605190023
Confusion Matrix :
 [[2953 1094]
 [1246 2802]]
Accuracy on test set:    0.7109326744904262
Sensitivity:    0.692193675889328 	 Specificity:    0.729676303434643
Precision  : 0.7191991786447639
Area Under Curve:    0.7109349896619855
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5888 - accuracy: 0.6823 - val_loss: 0.5463 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7225 - val_loss: 0.5393 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7332 - val_loss: 0.5379 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7426 - val_loss: 0.5388 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7501 - val_loss: 0.5389 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7591 - val_loss: 0.5397 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7650 - val_loss: 0.5490 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4733 - accuracy: 0.7728
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4732 - accuracy: 0.7729 - val_loss: 0.5500 - val_accuracy: 0.7261 - lr: 0.0010
253/253 [==============================] - 0s 819us/step
Independent Testing Matthews Correlation:  0.4283659069329319
Confusion Matrix :
 [[2928 1119]
 [1195 2853]]
Accuracy on test set:    0.7141445336627548
Sensitivity:    0.704792490118577 	 Specificity:    0.7234988880652335
Precision  : 0.7182779456193353
Area Under Curve:    0.7141456890919053
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5844 - accuracy: 0.6890 - val_loss: 0.5546 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7220 - val_loss: 0.5470 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7338 - val_loss: 0.5478 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7414 - val_loss: 0.5475 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7477 - val_loss: 0.5478 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7551 - val_loss: 0.5506 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4851 - accuracy: 0.7646
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4862 - accuracy: 0.7638 - val_loss: 0.5514 - val_accuracy: 0.7156 - lr: 0.0010
253/253 [==============================] - 0s 844us/step
Independent Testing Matthews Correlation:  0.4268388318510698
Confusion Matrix :
 [[2779 1268]
 [1054 2993]]
Accuracy on test set:    0.7131208302446257
Sensitivity:    0.739560168025698 	 Specificity:    0.6866814924635533
Precision  : 0.7024172729406243
Area Under Curve:    0.7131208302446256
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5840 - accuracy: 0.6887 - val_loss: 0.5528 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7226 - val_loss: 0.5461 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7315 - val_loss: 0.5461 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7409 - val_loss: 0.5478 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.7517 - val_loss: 0.5478 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7576 - val_loss: 0.5526 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 7/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4832 - accuracy: 0.7640
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4827 - accuracy: 0.7647 - val_loss: 0.5529 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 898us/step
Independent Testing Matthews Correlation:  0.4329428005262952
Confusion Matrix :
 [[2799 1248]
 [1049 2998]]
Accuracy on test set:    0.7162095379293304
Sensitivity:    0.7407956510995799 	 Specificity:    0.6916234247590808
Precision  : 0.7060763071125765
Area Under Curve:    0.7162095379293303
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5890 - accuracy: 0.6821 - val_loss: 0.5527 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7243 - val_loss: 0.5483 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7330 - val_loss: 0.5411 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7432 - val_loss: 0.5400 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5023 - accuracy: 0.7534 - val_loss: 0.5441 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7614 - val_loss: 0.5494 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4770 - accuracy: 0.7719 - val_loss: 0.5570 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4643 - accuracy: 0.7795 - val_loss: 0.5508 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4516 - accuracy: 0.7893
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4518 - accuracy: 0.7892 - val_loss: 0.5624 - val_accuracy: 0.7213 - lr: 0.0010
253/253 [==============================] - 0s 981us/step
Independent Testing Matthews Correlation:  0.4305696416861234
Confusion Matrix :
 [[2567 1480]
 [ 846 3201]]
Accuracy on test set:    0.7126266370150729
Sensitivity:    0.7909562638991846 	 Specificity:    0.6342970101309612
Precision  : 0.6838282418286691
Area Under Curve:    0.712626637015073
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5911 - accuracy: 0.6811 - val_loss: 0.5523 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7205 - val_loss: 0.5444 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7323 - val_loss: 0.5438 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5206 - accuracy: 0.7380 - val_loss: 0.5400 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7458 - val_loss: 0.5427 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.7541 - val_loss: 0.5440 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.7617 - val_loss: 0.5454 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4754 - accuracy: 0.7723 - val_loss: 0.5464 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4646 - accuracy: 0.7792 - val_loss: 0.5602 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4533 - accuracy: 0.7860 - val_loss: 0.5597 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4407 - accuracy: 0.7936
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4408 - accuracy: 0.7934 - val_loss: 0.5630 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42509995097571884
Confusion Matrix :
 [[2926 1121]
 [1206 2841]]
Accuracy on test set:    0.7125030887076848
Sensitivity:    0.7020014825796886 	 Specificity:    0.7230046948356808
Precision  : 0.7170620898536093
Area Under Curve:    0.7125030887076846
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5875 - accuracy: 0.6867 - val_loss: 0.5534 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7229 - val_loss: 0.5507 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7316 - val_loss: 0.5436 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7384 - val_loss: 0.5415 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7475 - val_loss: 0.5384 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7562 - val_loss: 0.5419 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4866 - accuracy: 0.7662 - val_loss: 0.5424 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.7719 - val_loss: 0.5427 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4638 - accuracy: 0.7795 - val_loss: 0.5485 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4508 - accuracy: 0.7892
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4510 - accuracy: 0.7889 - val_loss: 0.5549 - val_accuracy: 0.7220 - lr: 0.0010
253/253 [==============================] - 0s 728us/step
Independent Testing Matthews Correlation:  0.4651586656568034
Confusion Matrix :
 [[2918 1129]
 [1036 3011]]
Accuracy on test set:    0.7325179145045713
Sensitivity:    0.7440079070916729 	 Specificity:    0.7210279219174698
Precision  : 0.7272946859903382
Area Under Curve:    0.7325179145045714
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5960 - accuracy: 0.6774 - val_loss: 0.5563 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5511 - accuracy: 0.7198 - val_loss: 0.5469 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5357 - accuracy: 0.7305 - val_loss: 0.5465 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5240 - accuracy: 0.7388 - val_loss: 0.5418 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7459 - val_loss: 0.5438 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7525 - val_loss: 0.5428 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7603 - val_loss: 0.5411 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7686 - val_loss: 0.5415 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4689 - accuracy: 0.7766 - val_loss: 0.5487 - val_accuracy: 0.7191 - lr: 0.0010

Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4597 - accuracy: 0.7820 - val_loss: 0.5541 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4466 - accuracy: 0.7910 - val_loss: 0.5622 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4335 - accuracy: 0.8001 - val_loss: 0.5660 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 13/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4205 - accuracy: 0.8070
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4205 - accuracy: 0.8066 - val_loss: 0.5703 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 863us/step
Independent Testing Matthews Correlation:  0.46642534875883235
Confusion Matrix :
 [[3019 1028]
 [1132 2915]]
Accuracy on test set:    0.7331356560415122
Sensitivity:    0.7202866320731406 	 Specificity:    0.7459846800098838
Precision  : 0.7392848085214304
Area Under Curve:    0.7331356560415123
(8094, 2560) (8094,)
Mean MCC = 0.4326 + 0.0186 and Mean AUC = 0.7157 + 0.0096
Mean Sensitivity = 0.7355 + 0.0293 and Mean Specificity = 0.6959 + 0.0372 and Mean Accuracy = 0.7157 + 0.0096
Mean Precision = 0.7085 + 0.0184





Seed   : 822214
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5839 - accuracy: 0.6884 - val_loss: 0.5596 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5423 - accuracy: 0.7239 - val_loss: 0.5540 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5268 - accuracy: 0.7352 - val_loss: 0.5501 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7407 - val_loss: 0.5505 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7484 - val_loss: 0.5513 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7575 - val_loss: 0.5520 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4863 - accuracy: 0.7654 - val_loss: 0.5547 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4732 - accuracy: 0.7742
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4736 - accuracy: 0.7739 - val_loss: 0.5664 - val_accuracy: 0.7093 - lr: 0.0010
253/253 [==============================] - 0s 776us/step
Independent Testing Matthews Correlation:  0.4013145033944426
Confusion Matrix :
 [[2429 1619]
 [ 835 3212]]
Accuracy on test set:    0.6968499073502162
Sensitivity:    0.7936743266617248 	 Specificity:    0.6000494071146245
Precision  : 0.6648726971641482
Area Under Curve:    0.6968618668881746
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5889 - accuracy: 0.6835 - val_loss: 0.5595 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7247 - val_loss: 0.5548 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7360 - val_loss: 0.5536 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.7446 - val_loss: 0.5520 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7522 - val_loss: 0.5518 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.7586 - val_loss: 0.5527 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7679 - val_loss: 0.5656 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4672 - accuracy: 0.7757
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4675 - accuracy: 0.7757 - val_loss: 0.5625 - val_accuracy: 0.7135 - lr: 0.0010
253/253 [==============================] - 1s 4ms/step
Independent Testing Matthews Correlation:  0.41470160942878337
Confusion Matrix :
 [[2859 1189]
 [1180 2867]]
Accuracy on test set:    0.7073502161828289
Sensitivity:    0.7084259945638745 	 Specificity:    0.7062747035573123
Precision  : 0.7068540433925049
Area Under Curve:    0.7073503490605934
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5862 - accuracy: 0.6851 - val_loss: 0.5564 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7239 - val_loss: 0.5466 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7330 - val_loss: 0.5409 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7423 - val_loss: 0.5409 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7500 - val_loss: 0.5461 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7556 - val_loss: 0.5446 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4856 - accuracy: 0.7649 - val_loss: 0.5477 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4744 - accuracy: 0.7732 - val_loss: 0.5519 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4608 - accuracy: 0.7823
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4609 - accuracy: 0.7822 - val_loss: 0.5520 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 928us/step
Independent Testing Matthews Correlation:  0.4275328198071058
Confusion Matrix :
 [[2821 1226]
 [1092 2956]]
Accuracy on test set:    0.7136504014823966
Sensitivity:    0.7302371541501976 	 Specificity:    0.6970595502841611
Precision  : 0.7068388330942132
Area Under Curve:    0.7136483522171794
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5835 - accuracy: 0.6875 - val_loss: 0.5492 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7233 - val_loss: 0.5483 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7334 - val_loss: 0.5409 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7421 - val_loss: 0.5379 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5034 - accuracy: 0.7520 - val_loss: 0.5383 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4900 - accuracy: 0.7616 - val_loss: 0.5403 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4794 - accuracy: 0.7694 - val_loss: 0.5425 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.7769 - val_loss: 0.5542 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4516 - accuracy: 0.7871 - val_loss: 0.5525 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4398 - accuracy: 0.7960
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4400 - accuracy: 0.7960 - val_loss: 0.5582 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 774us/step
Independent Testing Matthews Correlation:  0.4369359480803266
Confusion Matrix :
 [[2810 1237]
 [1044 3004]]
Accuracy on test set:    0.7182211241507103
Sensitivity:    0.7420948616600791 	 Specificity:    0.694341487521621
Precision  : 0.7083235086064608
Area Under Curve:    0.71821817459085
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5868 - accuracy: 0.6844 - val_loss: 0.5496 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7233 - val_loss: 0.5420 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7340 - val_loss: 0.5430 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7414 - val_loss: 0.5392 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7506 - val_loss: 0.5396 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7564 - val_loss: 0.5378 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.7646 - val_loss: 0.5433 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4704 - accuracy: 0.7742
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.7741 - val_loss: 0.5523 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 840us/step
Independent Testing Matthews Correlation:  0.43271371196233144
Confusion Matrix :
 [[2676 1371]
 [ 935 3112]]
Accuracy on test set:    0.7150976031628367
Sensitivity:    0.768964665184087 	 Specificity:    0.6612305411415864
Precision  : 0.6941780057996877
Area Under Curve:    0.7150976031628367
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5909 - accuracy: 0.6828 - val_loss: 0.5503 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7225 - val_loss: 0.5399 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7317 - val_loss: 0.5421 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7394 - val_loss: 0.5363 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7474 - val_loss: 0.5369 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4991 - accuracy: 0.7557 - val_loss: 0.5373 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7644 - val_loss: 0.5393 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7733 - val_loss: 0.5455 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4621 - accuracy: 0.7822 - val_loss: 0.5483 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4497 - accuracy: 0.7907 - val_loss: 0.5531 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4370 - accuracy: 0.7976 - val_loss: 0.5557 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4250 - accuracy: 0.8057 - val_loss: 0.5655 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 13/400
252/257 [============================>.] - ETA: 0s - loss: 0.4123 - accuracy: 0.8137
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4120 - accuracy: 0.8137 - val_loss: 0.5649 - val_accuracy: 0.7205 - lr: 0.0010
253/253 [==============================] - 0s 917us/step
Independent Testing Matthews Correlation:  0.4178166571792826
Confusion Matrix :
 [[2772 1275]
 [1083 2964]]
Accuracy on test set:    0.7086730911786508
Sensitivity:    0.7323943661971831 	 Specificity:    0.6849518161601186
Precision  : 0.6992215145081387
Area Under Curve:    0.7086730911786508
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5860 - accuracy: 0.6859 - val_loss: 0.5499 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7211 - val_loss: 0.5442 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7341 - val_loss: 0.5438 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7425 - val_loss: 0.5399 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7493 - val_loss: 0.5412 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7598 - val_loss: 0.5431 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7663 - val_loss: 0.5465 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4701 - accuracy: 0.7758
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4699 - accuracy: 0.7759 - val_loss: 0.5507 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 764us/step
Independent Testing Matthews Correlation:  0.4243968107586733
Confusion Matrix :
 [[2796 1251]
 [1080 2967]]
Accuracy on test set:    0.712008895478132
Sensitivity:    0.7331356560415122 	 Specificity:    0.6908821349147517
Precision  : 0.7034139402560455
Area Under Curve:    0.7120088954781318
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5878 - accuracy: 0.6851 - val_loss: 0.5525 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7206 - val_loss: 0.5414 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7339 - val_loss: 0.5400 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7411 - val_loss: 0.5392 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5112 - accuracy: 0.7464 - val_loss: 0.5381 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5019 - accuracy: 0.7545 - val_loss: 0.5399 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7619 - val_loss: 0.5433 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7682 - val_loss: 0.5423 - val_accuracy: 0.7241 - lr: 0.0010

Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4689 - accuracy: 0.7770 - val_loss: 0.5476 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4578 - accuracy: 0.7836
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4579 - accuracy: 0.7835 - val_loss: 0.5480 - val_accuracy: 0.7197 - lr: 0.0010
253/253 [==============================] - 0s 849us/step
Independent Testing Matthews Correlation:  0.4290933722751248
Confusion Matrix :
 [[2841 1206]
 [1105 2942]]
Accuracy on test set:    0.7144798616258957
Sensitivity:    0.7269582406721028 	 Specificity:    0.7020014825796886
Precision  : 0.7092574734811957
Area Under Curve:    0.7144798616258957
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5906 - accuracy: 0.6809 - val_loss: 0.5506 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5484 - accuracy: 0.7194 - val_loss: 0.5489 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7311 - val_loss: 0.5427 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5220 - accuracy: 0.7377 - val_loss: 0.5409 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7492 - val_loss: 0.5398 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7570 - val_loss: 0.5436 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7633 - val_loss: 0.5435 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7725 - val_loss: 0.5503 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4633 - accuracy: 0.7797 - val_loss: 0.5514 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4504 - accuracy: 0.7898 - val_loss: 0.5550 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4390 - accuracy: 0.7969 - val_loss: 0.5721 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4254 - accuracy: 0.8038 - val_loss: 0.5674 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 13/400
250/257 [============================>.] - ETA: 0s - loss: 0.4147 - accuracy: 0.8114
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4149 - accuracy: 0.8114 - val_loss: 0.5737 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 743us/step
Independent Testing Matthews Correlation:  0.4550494222622562
Confusion Matrix :
 [[2995 1052]
 [1154 2893]]
Accuracy on test set:    0.7274524339016556
Sensitivity:    0.7148505065480603 	 Specificity:    0.7400543612552508
Precision  : 0.7333333333333333
Area Under Curve:    0.7274524339016555
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5919 - accuracy: 0.6803 - val_loss: 0.5563 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5507 - accuracy: 0.7188 - val_loss: 0.5503 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7310 - val_loss: 0.5459 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5219 - accuracy: 0.7398 - val_loss: 0.5462 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7475 - val_loss: 0.5481 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4985 - accuracy: 0.7580 - val_loss: 0.5515 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.7640 - val_loss: 0.5620 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4758 - accuracy: 0.7712 - val_loss: 0.5518 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4634 - accuracy: 0.7792 - val_loss: 0.5637 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4489 - accuracy: 0.7891
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4497 - accuracy: 0.7886 - val_loss: 0.5635 - val_accuracy: 0.7117 - lr: 0.0010
253/253 [==============================] - 0s 740us/step
Independent Testing Matthews Correlation:  0.4843238549891226
Confusion Matrix :
 [[3115  932]
 [1158 2889]]
Accuracy on test set:    0.7417840375586855
Sensitivity:    0.7138621200889548 	 Specificity:    0.7697059550284161
Precision  : 0.7560847945563989
Area Under Curve:    0.7417840375586854
(8094, 2560) (8094,)
Mean MCC = 0.4324 + 0.0220 and Mean AUC = 0.7156 + 0.0115
Mean Sensitivity = 0.7365 + 0.0251 and Mean Specificity = 0.6947 + 0.0425 and Mean Accuracy = 0.7156 + 0.0115
Mean Precision = 0.7082 + 0.0226





Seed   : 272612
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5828 - accuracy: 0.6896 - val_loss: 0.5600 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7253 - val_loss: 0.5570 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5245 - accuracy: 0.7381 - val_loss: 0.5542 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5138 - accuracy: 0.7445 - val_loss: 0.5599 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7536 - val_loss: 0.5551 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 6/400
255/257 [============================>.] - ETA: 0s - loss: 0.4896 - accuracy: 0.7614
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.7613 - val_loss: 0.5594 - val_accuracy: 0.7101 - lr: 0.0010
253/253 [==============================] - 0s 703us/step
Independent Testing Matthews Correlation:  0.403909907285022
Confusion Matrix :
 [[2647 1401]
 [1019 3028]]
Accuracy on test set:    0.7010500308832612
Sensitivity:    0.7482085495428713 	 Specificity:    0.6539031620553359
Precision  : 0.6836757733122601
Area Under Curve:    0.7010558557991036
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6831 - val_loss: 0.5588 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7237 - val_loss: 0.5504 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5265 - accuracy: 0.7356 - val_loss: 0.5469 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5138 - accuracy: 0.7439 - val_loss: 0.5584 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7510 - val_loss: 0.5469 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7582 - val_loss: 0.5483 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7683 - val_loss: 0.5637 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4694 - accuracy: 0.7765 - val_loss: 0.5607 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4578 - accuracy: 0.7829 - val_loss: 0.5572 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4441 - accuracy: 0.7917
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4440 - accuracy: 0.7917 - val_loss: 0.5617 - val_accuracy: 0.7091 - lr: 0.0010
253/253 [==============================] - 0s 826us/step
Independent Testing Matthews Correlation:  0.4099797518131909
Confusion Matrix :
 [[2950 1098]
 [1292 2755]]
Accuracy on test set:    0.7047560222359481
Sensitivity:    0.6807511737089202 	 Specificity:    0.7287549407114624
Precision  : 0.7150272514923436
Area Under Curve:    0.7047530572101913
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5856 - accuracy: 0.6855 - val_loss: 0.5498 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7239 - val_loss: 0.5443 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7338 - val_loss: 0.5394 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7420 - val_loss: 0.5414 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.7520 - val_loss: 0.5417 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4954 - accuracy: 0.7570 - val_loss: 0.5421 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7660 - val_loss: 0.5471 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4714 - accuracy: 0.7764
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4718 - accuracy: 0.7760 - val_loss: 0.5473 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 748us/step
Independent Testing Matthews Correlation:  0.4215541914070308
Confusion Matrix :
 [[2760 1287]
 [1057 2991]]
Accuracy on test set:    0.710438542310068
Sensitivity:    0.7388833992094862 	 Specificity:    0.6819866567828021
Precision  : 0.6991584852734923
Area Under Curve:    0.7104350279961442
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5905 - accuracy: 0.6828 - val_loss: 0.5513 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7227 - val_loss: 0.5408 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7324 - val_loss: 0.5390 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7417 - val_loss: 0.5362 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7485 - val_loss: 0.5392 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7559 - val_loss: 0.5396 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.7645 - val_loss: 0.5427 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4729 - accuracy: 0.7758 - val_loss: 0.5482 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4612 - accuracy: 0.7823 - val_loss: 0.5534 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4505 - accuracy: 0.7907 - val_loss: 0.5519 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 11/400
249/257 [============================>.] - ETA: 0s - loss: 0.4377 - accuracy: 0.7979
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4376 - accuracy: 0.7979 - val_loss: 0.5606 - val_accuracy: 0.7130 - lr: 0.0010
253/253 [==============================] - 0s 904us/step
Independent Testing Matthews Correlation:  0.4132660556108331
Confusion Matrix :
 [[2890 1157]
 [1218 2830]]
Accuracy on test set:    0.7066090179122916
Sensitivity:    0.6991106719367589 	 Specificity:    0.7141092167037312
Precision  : 0.709806872335089
Area Under Curve:    0.7066099443202449
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5926 - accuracy: 0.6801 - val_loss: 0.5534 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5482 - accuracy: 0.7203 - val_loss: 0.5437 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7311 - val_loss: 0.5405 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5207 - accuracy: 0.7394 - val_loss: 0.5419 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7500 - val_loss: 0.5374 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7570 - val_loss: 0.5468 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4816 - accuracy: 0.7677
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7677 - val_loss: 0.5424 - val_accuracy: 0.7222 - lr: 0.0010
253/253 [==============================] - 0s 782us/step
Independent Testing Matthews Correlation:  0.4258291472583356
Confusion Matrix :
 [[2805 1242]
 [1083 2964]]
Accuracy on test set:    0.712750185322461
Sensitivity:    0.7323943661971831 	 Specificity:    0.6931060044477391
Precision  : 0.7047075606276747
Area Under Curve:    0.7127501853224611
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5911 - accuracy: 0.6823 - val_loss: 0.5524 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7219 - val_loss: 0.5452 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5265 - accuracy: 0.7345 - val_loss: 0.5420 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5146 - accuracy: 0.7442 - val_loss: 0.5411 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5019 - accuracy: 0.7528 - val_loss: 0.5452 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.7626 - val_loss: 0.5399 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7686 - val_loss: 0.5435 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4657 - accuracy: 0.7782 - val_loss: 0.5504 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4534 - accuracy: 0.7866 - val_loss: 0.5546 - val_accuracy: 0.7212 - lr: 0.0010

Epoch 10/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4410 - accuracy: 0.7941
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4410 - accuracy: 0.7943 - val_loss: 0.5604 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 849us/step
Independent Testing Matthews Correlation:  0.4346476067402068
Confusion Matrix :
 [[2783 1264]
 [1027 3020]]
Accuracy on test set:    0.7169508277736595
Sensitivity:    0.7462317766246602 	 Specificity:    0.6876698789226587
Precision  : 0.7049486461251168
Area Under Curve:    0.7169508277736595
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5870 - accuracy: 0.6860 - val_loss: 0.5476 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7237 - val_loss: 0.5408 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7333 - val_loss: 0.5445 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7412 - val_loss: 0.5402 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7486 - val_loss: 0.5414 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7569 - val_loss: 0.5408 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7653 - val_loss: 0.5423 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4736 - accuracy: 0.7731 - val_loss: 0.5468 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4622 - accuracy: 0.7810 - val_loss: 0.5486 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 10/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4485 - accuracy: 0.7902
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4486 - accuracy: 0.7903 - val_loss: 0.5537 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4300546776747463
Confusion Matrix :
 [[2765 1282]
 [1028 3019]]
Accuracy on test set:    0.7146034099332839
Sensitivity:    0.7459846800098838 	 Specificity:    0.683222139856684
Precision  : 0.701929783771216
Area Under Curve:    0.7146034099332841
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5932 - accuracy: 0.6815 - val_loss: 0.5555 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5486 - accuracy: 0.7192 - val_loss: 0.5478 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7313 - val_loss: 0.5420 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7397 - val_loss: 0.5412 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7474 - val_loss: 0.5420 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7555 - val_loss: 0.5412 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.7628 - val_loss: 0.5453 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4750 - accuracy: 0.7716
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.7715 - val_loss: 0.5455 - val_accuracy: 0.7241 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44049791447288456
Confusion Matrix :
 [[2971 1076]
 [1189 2858]]
Accuracy on test set:    0.7201630837657524
Sensitivity:    0.7062021250308871 	 Specificity:    0.7341240425006177
Precision  : 0.726487036095577
Area Under Curve:    0.7201630837657524
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5922 - accuracy: 0.6834 - val_loss: 0.5546 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7192 - val_loss: 0.5479 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5340 - accuracy: 0.7313 - val_loss: 0.5456 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5230 - accuracy: 0.7382 - val_loss: 0.5431 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.7459 - val_loss: 0.5442 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7537 - val_loss: 0.5459 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7626 - val_loss: 0.5481 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7711 - val_loss: 0.5496 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4679 - accuracy: 0.7779 - val_loss: 0.5532 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4545 - accuracy: 0.7881 - val_loss: 0.5568 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4381 - accuracy: 0.7956
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4383 - accuracy: 0.7957 - val_loss: 0.5691 - val_accuracy: 0.7119 - lr: 0.0010
253/253 [==============================] - 0s 816us/step
Independent Testing Matthews Correlation:  0.4434369148526899
Confusion Matrix :
 [[3187  860]
 [1409 2638]]
Accuracy on test set:    0.7196688905361996
Sensitivity:    0.651840869780084 	 Specificity:    0.7874969112923152
Precision  : 0.7541452258433391
Area Under Curve:    0.7196688905361996
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5901 - accuracy: 0.6838 - val_loss: 0.5578 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7202 - val_loss: 0.5514 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7320 - val_loss: 0.5481 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7402 - val_loss: 0.5514 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7489 - val_loss: 0.5482 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7579 - val_loss: 0.5533 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7657 - val_loss: 0.5556 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4716 - accuracy: 0.7743 - val_loss: 0.5561 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4592 - accuracy: 0.7815 - val_loss: 0.5608 - val_accuracy: 0.7138 - lr: 0.0010

Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4455 - accuracy: 0.7927 - val_loss: 0.5650 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4323 - accuracy: 0.7991 - val_loss: 0.5687 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4192 - accuracy: 0.8074
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4193 - accuracy: 0.8072 - val_loss: 0.5739 - val_accuracy: 0.7145 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.4736279831883161
Confusion Matrix :
 [[3068  979]
 [1153 2894]]
Accuracy on test set:    0.7365950086483816
Sensitivity:    0.7150976031628367 	 Specificity:    0.7580924141339264
Precision  : 0.7472243738703848
Area Under Curve:    0.7365950086483816
(8094, 2560) (8094,)
Mean MCC = 0.4297 + 0.0191 and Mean AUC = 0.7144 + 0.0095
Mean Sensitivity = 0.7165 + 0.0306 and Mean Specificity = 0.7122 + 0.0383 and Mean Accuracy = 0.7144 + 0.0095
Mean Precision = 0.7147 + 0.0208





Seed   : 870461
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5860 - accuracy: 0.6852 - val_loss: 0.5572 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5422 - accuracy: 0.7252 - val_loss: 0.5487 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7346 - val_loss: 0.5444 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5142 - accuracy: 0.7458 - val_loss: 0.5467 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7521 - val_loss: 0.5481 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4900 - accuracy: 0.7605 - val_loss: 0.5482 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4753 - accuracy: 0.7721 - val_loss: 0.5591 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4623 - accuracy: 0.7810
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4626 - accuracy: 0.7809 - val_loss: 0.5529 - val_accuracy: 0.7126 - lr: 0.0010
253/253 [==============================] - 0s 879us/step
Independent Testing Matthews Correlation:  0.39766587979472345
Confusion Matrix :
 [[2813 1235]
 [1203 2844]]
Accuracy on test set:    0.6988264360716492
Sensitivity:    0.7027427724240178 	 Specificity:    0.6949110671936759
Precision  : 0.6972297131649914
Area Under Curve:    0.6988269198088468
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5952 - accuracy: 0.6760 - val_loss: 0.5627 - val_accuracy: 0.7021 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7212 - val_loss: 0.5499 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7336 - val_loss: 0.5447 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5168 - accuracy: 0.7426 - val_loss: 0.5533 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7510 - val_loss: 0.5507 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7578 - val_loss: 0.5465 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7672 - val_loss: 0.5537 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4712 - accuracy: 0.7742
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7743 - val_loss: 0.5562 - val_accuracy: 0.7109 - lr: 0.0010
253/253 [==============================] - 0s 819us/step
Independent Testing Matthews Correlation:  0.4222209890335343
Confusion Matrix :
 [[2715 1333]
 [1011 3036]]
Accuracy on test set:    0.710438542310068
Sensitivity:    0.7501853224610823 	 Specificity:    0.670701581027668
Precision  : 0.694895857175555
Area Under Curve:    0.7104434517443752
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5882 - accuracy: 0.6827 - val_loss: 0.5463 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7219 - val_loss: 0.5395 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7317 - val_loss: 0.5360 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7404 - val_loss: 0.5312 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7499 - val_loss: 0.5321 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7598 - val_loss: 0.5366 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4806 - accuracy: 0.7672 - val_loss: 0.5403 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4656 - accuracy: 0.7783 - val_loss: 0.5449 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4539 - accuracy: 0.7866 - val_loss: 0.5565 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4384 - accuracy: 0.7961
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4386 - accuracy: 0.7959 - val_loss: 0.5523 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 870us/step
Independent Testing Matthews Correlation:  0.41917950641686214
Confusion Matrix :
 [[2594 1453]
 [ 913 3135]]
Accuracy on test set:    0.7077208153180976
Sensitivity:    0.7744565217391305 	 Specificity:    0.6409686187299234
Precision  : 0.6833042720139494
Area Under Curve:    0.7077125702345268
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5845 - accuracy: 0.6884 - val_loss: 0.5401 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7223 - val_loss: 0.5308 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7333 - val_loss: 0.5284 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7404 - val_loss: 0.5274 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7505 - val_loss: 0.5267 - val_accuracy: 0.7349 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4989 - accuracy: 0.7551 - val_loss: 0.5248 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7634 - val_loss: 0.5284 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.7727 - val_loss: 0.5311 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4632 - accuracy: 0.7813 - val_loss: 0.5326 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4510 - accuracy: 0.7877
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4517 - accuracy: 0.7874 - val_loss: 0.5416 - val_accuracy: 0.7279 - lr: 0.0010
253/253 [==============================] - 0s 889us/step
Independent Testing Matthews Correlation:  0.4128441550676981
Confusion Matrix :
 [[2677 1370]
 [1013 3035]]
Accuracy on test set:    0.705620753551575
Sensitivity:    0.7497529644268774 	 Specificity:    0.6614776377563627
Precision  : 0.6889897843359818
Area Under Curve:    0.7056153010916201
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5865 - accuracy: 0.6827 - val_loss: 0.5524 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5423 - accuracy: 0.7226 - val_loss: 0.5403 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7357 - val_loss: 0.5426 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5150 - accuracy: 0.7422 - val_loss: 0.5430 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7512 - val_loss: 0.5487 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.7590 - val_loss: 0.5439 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4786 - accuracy: 0.7668
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4788 - accuracy: 0.7668 - val_loss: 0.5487 - val_accuracy: 0.7259 - lr: 0.0010
253/253 [==============================] - 0s 901us/step
Independent Testing Matthews Correlation:  0.4243179493862265
Confusion Matrix :
 [[2850 1197]
 [1133 2914]]
Accuracy on test set:    0.7121324437855201
Sensitivity:    0.7200395354583642 	 Specificity:    0.704225352112676
Precision  : 0.7088299683775238
Area Under Curve:    0.7121324437855201
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5859 - accuracy: 0.6835 - val_loss: 0.5561 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7232 - val_loss: 0.5420 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7337 - val_loss: 0.5407 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7427 - val_loss: 0.5465 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7524 - val_loss: 0.5502 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7574 - val_loss: 0.5484 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.7697 - val_loss: 0.5457 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4642 - accuracy: 0.7780
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4643 - accuracy: 0.7779 - val_loss: 0.5535 - val_accuracy: 0.7234 - lr: 0.0010
253/253 [==============================] - 0s 715us/step
Independent Testing Matthews Correlation:  0.43106097592634546
Confusion Matrix :
 [[2811 1236]
 [1068 2979]]
Accuracy on test set:    0.7153446997776131
Sensitivity:    0.7361008154188288 	 Specificity:    0.6945885841363973
Precision  : 0.7067615658362989
Area Under Curve:    0.7153446997776131
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5871 - accuracy: 0.6838 - val_loss: 0.5511 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7232 - val_loss: 0.5409 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7348 - val_loss: 0.5446 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7423 - val_loss: 0.5475 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7486 - val_loss: 0.5435 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7571 - val_loss: 0.5460 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4848 - accuracy: 0.7655
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7651 - val_loss: 0.5463 - val_accuracy: 0.7237 - lr: 0.0010
253/253 [==============================] - 0s 886us/step
Independent Testing Matthews Correlation:  0.4170796551133392
Confusion Matrix :
 [[2985 1062]
 [1300 2747]]
Accuracy on test set:    0.708178897949098
Sensitivity:    0.6787744007907092 	 Specificity:    0.737583395107487
Precision  : 0.7211866631661854
Area Under Curve:    0.708178897949098
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5904 - accuracy: 0.6813 - val_loss: 0.5551 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7217 - val_loss: 0.5436 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7322 - val_loss: 0.5452 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7423 - val_loss: 0.5440 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7506 - val_loss: 0.5496 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7590 - val_loss: 0.5445 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4798 - accuracy: 0.7673
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4801 - accuracy: 0.7669 - val_loss: 0.5496 - val_accuracy: 0.7237 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4358785181141389
Confusion Matrix :
 [[2709 1338]
 [ 953 3094]]
Accuracy on test set:    0.7169508277736595
Sensitivity:    0.7645169261181122 	 Specificity:    0.6693847294292068
Precision  : 0.6981046931407943
Area Under Curve:    0.7169508277736595
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5924 - accuracy: 0.6810 - val_loss: 0.5560 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7211 - val_loss: 0.5480 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5334 - accuracy: 0.7300 - val_loss: 0.5489 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5216 - accuracy: 0.7387 - val_loss: 0.5462 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400

257/257 [==============================] - 1s 4ms/step - loss: 0.5106 - accuracy: 0.7468 - val_loss: 0.5534 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7556 - val_loss: 0.5471 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7638 - val_loss: 0.5507 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.7721 - val_loss: 0.5582 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7783 - val_loss: 0.5566 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4539 - accuracy: 0.7857 - val_loss: 0.5602 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4404 - accuracy: 0.7958 - val_loss: 0.5623 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 12/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4289 - accuracy: 0.8018
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4292 - accuracy: 0.8012 - val_loss: 0.5697 - val_accuracy: 0.7193 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.459157304187188
Confusion Matrix :
 [[3025 1022]
 [1168 2879]]
Accuracy on test set:    0.7294292068198666
Sensitivity:    0.711391153941191 	 Specificity:    0.7474672596985421
Precision  : 0.7380158933606767
Area Under Curve:    0.7294292068198666
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5900 - accuracy: 0.6823 - val_loss: 0.5563 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5499 - accuracy: 0.7206 - val_loss: 0.5584 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5351 - accuracy: 0.7288 - val_loss: 0.5467 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5238 - accuracy: 0.7357 - val_loss: 0.5497 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7475 - val_loss: 0.5506 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5019 - accuracy: 0.7533 - val_loss: 0.5510 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4867 - accuracy: 0.7635 - val_loss: 0.5533 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.7707 - val_loss: 0.5573 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4606 - accuracy: 0.7818 - val_loss: 0.5595 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4470 - accuracy: 0.7914 - val_loss: 0.5673 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4345 - accuracy: 0.7973 - val_loss: 0.5694 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4210 - accuracy: 0.8071 - val_loss: 0.5756 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4089 - accuracy: 0.8131 - val_loss: 0.5817 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 14/400
255/257 [============================>.] - ETA: 0s - loss: 0.3969 - accuracy: 0.8195
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3971 - accuracy: 0.8194 - val_loss: 0.5861 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 788us/step
Independent Testing Matthews Correlation:  0.47341922487958443
Confusion Matrix :
 [[3109  938]
 [1197 2850]]
Accuracy on test set:    0.7362243637262169
Sensitivity:    0.704225352112676 	 Specificity:    0.7682233753397578
Precision  : 0.752375923970433
Area Under Curve:    0.7362243637262169
(8094, 2560) (8094,)
Mean MCC = 0.4293 + 0.0212 and Mean AUC = 0.7141 + 0.0106
Mean Sensitivity = 0.7292 + 0.0291 and Mean Specificity = 0.6990 + 0.0389 and Mean Accuracy = 0.7141 + 0.0106
Mean Precision = 0.7090 + 0.0210





Seed   : 229823
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5930 - accuracy: 0.6782 - val_loss: 0.5548 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7225 - val_loss: 0.5489 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7330 - val_loss: 0.5473 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7399 - val_loss: 0.5478 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7471 - val_loss: 0.5473 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.7549 - val_loss: 0.5491 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4889 - accuracy: 0.7629
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7624 - val_loss: 0.5477 - val_accuracy: 0.7127 - lr: 0.0010
253/253 [==============================] - 0s 830us/step
Independent Testing Matthews Correlation:  0.40787377281405235
Confusion Matrix :
 [[2995 1053]
 [1348 2699]]
Accuracy on test set:    0.7033971587399629
Sensitivity:    0.666913763281443 	 Specificity:    0.7398715415019763
Precision  : 0.7193496801705757
Area Under Curve:    0.7033926523917097
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6849 - val_loss: 0.5557 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7228 - val_loss: 0.5489 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7350 - val_loss: 0.5477 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5168 - accuracy: 0.7434 - val_loss: 0.5452 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7508 - val_loss: 0.5493 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4928 - accuracy: 0.7586 - val_loss: 0.5495 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7675 - val_loss: 0.5523 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4700 - accuracy: 0.7740 - val_loss: 0.5610 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4577 - accuracy: 0.7841 - val_loss: 0.5624 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4455 - accuracy: 0.7921 - val_loss: 0.5732 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 11/400
256/257 [============================>.] - ETA: 0s - loss: 0.4332 - accuracy: 0.7988
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4331 - accuracy: 0.7988 - val_loss: 0.5915 - val_accuracy: 0.7116 - lr: 0.0010

253/253 [==============================] - 0s 896us/step
Independent Testing Matthews Correlation:  0.4218581526528339
Confusion Matrix :
 [[2568 1480]
 [ 879 3168]]
Accuracy on test set:    0.7085855466337245
Sensitivity:    0.7828020756115641 	 Specificity:    0.6343873517786561
Precision  : 0.6815834767641996
Area Under Curve:    0.7085947136951102
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5850 - accuracy: 0.6864 - val_loss: 0.5490 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7225 - val_loss: 0.5372 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7317 - val_loss: 0.5349 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7410 - val_loss: 0.5334 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7480 - val_loss: 0.5361 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7570 - val_loss: 0.5354 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.7633 - val_loss: 0.5370 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7721 - val_loss: 0.5399 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4631 - accuracy: 0.7794
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4634 - accuracy: 0.7792 - val_loss: 0.5395 - val_accuracy: 0.7267 - lr: 0.0010
253/253 [==============================] - 0s 730us/step
Independent Testing Matthews Correlation:  0.4323176898006399
Confusion Matrix :
 [[2819 1228]
 [1071 2977]]
Accuracy on test set:    0.7159975293390982
Sensitivity:    0.7354249011857708 	 Specificity:    0.6965653570546083
Precision  : 0.7079667063020214
Area Under Curve:    0.7159951291201896
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 4ms/step - loss: 0.5865 - accuracy: 0.6865 - val_loss: 0.5426 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7220 - val_loss: 0.5362 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5273 - accuracy: 0.7338 - val_loss: 0.5394 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5141 - accuracy: 0.7448 - val_loss: 0.5325 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5037 - accuracy: 0.7518 - val_loss: 0.5301 - val_accuracy: 0.7337 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7601 - val_loss: 0.5321 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4792 - accuracy: 0.7709 - val_loss: 0.5356 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.7788 - val_loss: 0.5359 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4540 - accuracy: 0.7856 - val_loss: 0.5426 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 10/400
241/257 [===========================>..] - ETA: 0s - loss: 0.4366 - accuracy: 0.7964
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 3ms/step - loss: 0.4382 - accuracy: 0.7953 - val_loss: 0.5415 - val_accuracy: 0.7286 - lr: 0.0010
253/253 [==============================] - 0s 876us/step
Independent Testing Matthews Correlation:  0.40582612220647846
Confusion Matrix :
 [[2824 1223]
 [1182 2866]]
Accuracy on test set:    0.7029030265596047
Sensitivity:    0.7080039525691699 	 Specificity:    0.6978008401284902
Precision  : 0.7009048667155784
Area Under Curve:    0.7029023963488301
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5896 - accuracy: 0.6824 - val_loss: 0.5534 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7220 - val_loss: 0.5471 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7331 - val_loss: 0.5412 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5225 - accuracy: 0.7382 - val_loss: 0.5419 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.7448 - val_loss: 0.5434 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7522 - val_loss: 0.5461 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7599 - val_loss: 0.5425 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4823 - accuracy: 0.7663
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7663 - val_loss: 0.5444 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 884us/step
Independent Testing Matthews Correlation:  0.4231596439458861
Confusion Matrix :
 [[2700 1347]
 [ 994 3053]]
Accuracy on test set:    0.7107734124042501
Sensitivity:    0.7543859649122807 	 Specificity:    0.6671608598962194
Precision  : 0.6938636363636363
Area Under Curve:    0.7107734124042501
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5934 - accuracy: 0.6778 - val_loss: 0.5603 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7228 - val_loss: 0.5489 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7315 - val_loss: 0.5470 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5204 - accuracy: 0.7400 - val_loss: 0.5410 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5093 - accuracy: 0.7488 - val_loss: 0.5436 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4970 - accuracy: 0.7572 - val_loss: 0.5435 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7653 - val_loss: 0.5451 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.7738 - val_loss: 0.5465 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4606 - accuracy: 0.7796 - val_loss: 0.5574 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4473 - accuracy: 0.7878 - val_loss: 0.5645 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4350 - accuracy: 0.7979 - val_loss: 0.5681 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 12/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4242 - accuracy: 0.8050
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4237 - accuracy: 0.8052 - val_loss: 0.5715 - val_accuracy: 0.7142 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41907955608961855
Confusion Matrix :
 [[2863 1184]
 [1167 2880]]
Accuracy on test set:    0.7095379293303682
Sensitivity:    0.7116382505559674 	 Specificity:    0.707437608104769
Precision  : 0.7086614173228346
Area Under Curve:    0.7095379293303682
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5922 - accuracy: 0.6813 - val_loss: 0.5523 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7197 - val_loss: 0.5518 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7323 - val_loss: 0.5424 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.7404 - val_loss: 0.5389 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.7482 - val_loss: 0.5398 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7558 - val_loss: 0.5404 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7623 - val_loss: 0.5402 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4785 - accuracy: 0.7705 - val_loss: 0.5497 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4670 - accuracy: 0.7781
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4671 - accuracy: 0.7782 - val_loss: 0.5523 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4248836726033125
Confusion Matrix :
 [[2834 1213]
 [1115 2932]]
Accuracy on test set:    0.7123795404002965
Sensitivity:    0.724487274524339 	 Specificity:    0.700271806276254
Precision  : 0.7073582629674307
Area Under Curve:    0.7123795404002966
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5883 - accuracy: 0.6846 - val_loss: 0.5529 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7218 - val_loss: 0.5415 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7317 - val_loss: 0.5409 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7409 - val_loss: 0.5422 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7495 - val_loss: 0.5420 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7583 - val_loss: 0.5429 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4826 - accuracy: 0.7665
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.7663 - val_loss: 0.5450 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 823us/step
Independent Testing Matthews Correlation:  0.4514499805966914
Confusion Matrix :
 [[2928 1119]
 [1101 2946]]
Accuracy on test set:    0.7257227575982209
Sensitivity:    0.7279466271312083 	 Specificity:    0.7234988880652335
Precision  : 0.7247232472324723
Area Under Curve:    0.725722757598221
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5922 - accuracy: 0.6813 - val_loss: 0.5571 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5497 - accuracy: 0.7191 - val_loss: 0.5585 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5347 - accuracy: 0.7291 - val_loss: 0.5526 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7395 - val_loss: 0.5455 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5118 - accuracy: 0.7464 - val_loss: 0.5516 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4994 - accuracy: 0.7543 - val_loss: 0.5563 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.7658 - val_loss: 0.5537 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4759 - accuracy: 0.7729 - val_loss: 0.5567 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 9/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4614 - accuracy: 0.7837
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4615 - accuracy: 0.7835 - val_loss: 0.5613 - val_accuracy: 0.7197 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4668118917887067
Confusion Matrix :
 [[2849 1198]
 [ 963 3084]]
Accuracy on test set:    0.7330121077341241
Sensitivity:    0.7620459599703484 	 Specificity:    0.7039782554978997
Precision  : 0.7202241943017281
Area Under Curve:    0.7330121077341241
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5990 - accuracy: 0.6767 - val_loss: 0.5669 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5515 - accuracy: 0.7183 - val_loss: 0.5538 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5346 - accuracy: 0.7318 - val_loss: 0.5512 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5220 - accuracy: 0.7403 - val_loss: 0.5497 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7515 - val_loss: 0.5514 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7583 - val_loss: 0.5508 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4818 - accuracy: 0.7685
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7689 - val_loss: 0.5721 - val_accuracy: 0.7130 - lr: 0.0010
253/253 [==============================] - 0s 775us/step
Independent Testing Matthews Correlation:  0.5029623722939158
Confusion Matrix :
 [[2890 1157]
 [ 860 3187]]
Accuracy on test set:    0.7508030639980232
Sensitivity:    0.7874969112923152 	 Specificity:    0.7141092167037312
Precision  : 0.7336556169429097
Area Under Curve:    0.7508030639980233
(8094, 2560) (8094,)
Mean MCC = 0.4356 + 0.0286 and Mean AUC = 0.7173 + 0.0143
Mean Sensitivity = 0.7361 + 0.0349 and Mean Specificity = 0.6985 + 0.0279 and Mean Accuracy = 0.7173 + 0.0143
Mean Precision = 0.7098 + 0.0146





Seed   : 985683
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5875 - accuracy: 0.6860 - val_loss: 0.5532 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7239 - val_loss: 0.5439 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7350 - val_loss: 0.5415 - val_accuracy: 0.7215 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.7446 - val_loss: 0.5436 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5024 - accuracy: 0.7533 - val_loss: 0.5444 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4890 - accuracy: 0.7621 - val_loss: 0.5449 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.7721 - val_loss: 0.5507 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4602 - accuracy: 0.7819 - val_loss: 0.5685 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4498 - accuracy: 0.7903 - val_loss: 0.5590 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4362 - accuracy: 0.7983
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4359 - accuracy: 0.7986 - val_loss: 0.5733 - val_accuracy: 0.7105 - lr: 0.0010
253/253 [==============================] - 0s 800us/step
Independent Testing Matthews Correlation:  0.4110946600918648
Confusion Matrix :
 [[2470 1578]
 [ 834 3213]]
Accuracy on test set:    0.7020382952439778
Sensitivity:    0.7939214232765011 	 Specificity:    0.6101778656126482
Precision  : 0.6706324358171571
Area Under Curve:    0.7020496444445745
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5872 - accuracy: 0.6848 - val_loss: 0.5518 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7221 - val_loss: 0.5431 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7353 - val_loss: 0.5413 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7423 - val_loss: 0.5396 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7509 - val_loss: 0.5391 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7605 - val_loss: 0.5418 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7680 - val_loss: 0.5473 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4680 - accuracy: 0.7764 - val_loss: 0.5458 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4563 - accuracy: 0.7853 - val_loss: 0.5573 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4440 - accuracy: 0.7931 - val_loss: 0.5513 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 11/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4285 - accuracy: 0.8036
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4290 - accuracy: 0.8033 - val_loss: 0.5618 - val_accuracy: 0.7141 - lr: 0.0010
253/253 [==============================] - 0s 831us/step
Independent Testing Matthews Correlation:  0.4262226320618502
Confusion Matrix :
 [[2774 1274]
 [1051 2996]]
Accuracy on test set:    0.7127856701667696
Sensitivity:    0.7403014578700272 	 Specificity:    0.6852766798418972
Precision  : 0.7016393442622951
Area Under Curve:    0.7127890688559622
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5927 - accuracy: 0.6794 - val_loss: 0.5454 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7224 - val_loss: 0.5354 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7322 - val_loss: 0.5319 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7417 - val_loss: 0.5339 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7485 - val_loss: 0.5320 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7544 - val_loss: 0.5311 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7630 - val_loss: 0.5372 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4776 - accuracy: 0.7702
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4779 - accuracy: 0.7698 - val_loss: 0.5381 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4161781781763688
Confusion Matrix :
 [[2984 1063]
 [1303 2745]]
Accuracy on test set:    0.7077208153180976
Sensitivity:    0.6781126482213439 	 Specificity:    0.7373362984927107
Precision  : 0.7208508403361344
Area Under Curve:    0.7077244733570273
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5876 - accuracy: 0.6847 - val_loss: 0.5478 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7237 - val_loss: 0.5376 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7348 - val_loss: 0.5388 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7418 - val_loss: 0.5319 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7503 - val_loss: 0.5325 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.7587 - val_loss: 0.5392 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7668 - val_loss: 0.5438 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4684 - accuracy: 0.7765 - val_loss: 0.5427 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4569 - accuracy: 0.7822 - val_loss: 0.5438 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4456 - accuracy: 0.7913 - val_loss: 0.5521 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4317 - accuracy: 0.7984 - val_loss: 0.5588 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4194 - accuracy: 0.8056 - val_loss: 0.5582 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 13/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4076 - accuracy: 0.8147
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4075 - accuracy: 0.8143 - val_loss: 0.5667 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 842us/step
Independent Testing Matthews Correlation:  0.42981162135214085
Confusion Matrix :
 [[2865 1182]
 [1126 2922]]
Accuracy on test set:    0.7148857319332922
Sensitivity:    0.7218379446640316 	 Specificity:    0.7079318013343218
Precision  : 0.7119883040935673
Area Under Curve:    0.7148848729991767
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5882 - accuracy: 0.6815 - val_loss: 0.5476 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7212 - val_loss: 0.5420 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7304 - val_loss: 0.5415 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5212 - accuracy: 0.7379 - val_loss: 0.5401 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5120 - accuracy: 0.7448 - val_loss: 0.5412 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5021 - accuracy: 0.7527 - val_loss: 0.5422 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7608 - val_loss: 0.5447 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4791 - accuracy: 0.7690 - val_loss: 0.5446 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4700 - accuracy: 0.7743
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4700 - accuracy: 0.7743 - val_loss: 0.5470 - val_accuracy: 0.7242 - lr: 0.0010
253/253 [==============================] - 0s 805us/step
Independent Testing Matthews Correlation:  0.4225267629277967
Confusion Matrix :
 [[2810 1237]
 [1101 2946]]
Accuracy on test set:    0.7111440573264146
Sensitivity:    0.7279466271312083 	 Specificity:    0.694341487521621
Precision  : 0.7042792254362897
Area Under Curve:    0.7111440573264146
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5909 - accuracy: 0.6786 - val_loss: 0.5544 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7207 - val_loss: 0.5449 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7329 - val_loss: 0.5521 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7416 - val_loss: 0.5425 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7503 - val_loss: 0.5499 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7564 - val_loss: 0.5447 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7654 - val_loss: 0.5477 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7736 - val_loss: 0.5545 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4599 - accuracy: 0.7823 - val_loss: 0.5580 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4484 - accuracy: 0.7889 - val_loss: 0.5583 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4361 - accuracy: 0.7973 - val_loss: 0.5662 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4221 - accuracy: 0.8052
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4224 - accuracy: 0.8049 - val_loss: 0.5769 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4363282967297499
Confusion Matrix :
 [[2700 1347]
 [ 943 3104]]
Accuracy on test set:    0.7170743760810477
Sensitivity:    0.7669878922658759 	 Specificity:    0.6671608598962194
Precision  : 0.6973713772186025
Area Under Curve:    0.7170743760810476
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5870 - accuracy: 0.6850 - val_loss: 0.5515 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7226 - val_loss: 0.5396 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7335 - val_loss: 0.5381 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7430 - val_loss: 0.5374 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7515 - val_loss: 0.5361 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4954 - accuracy: 0.7576 - val_loss: 0.5388 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.7659 - val_loss: 0.5389 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4702 - accuracy: 0.7746 - val_loss: 0.5435 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4576 - accuracy: 0.7835
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4581 - accuracy: 0.7830 - val_loss: 0.5454 - val_accuracy: 0.7235 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42537801079133264
Confusion Matrix :
 [[2933 1114]
 [1212 2835]]
Accuracy on test set:    0.7126266370150729
Sensitivity:    0.7005189028910304 	 Specificity:    0.7247343711391154
Precision  : 0.7179032666497848
Area Under Curve:    0.7126266370150729
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5854 - accuracy: 0.6868 - val_loss: 0.5463 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7225 - val_loss: 0.5406 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7350 - val_loss: 0.5380 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7438 - val_loss: 0.5383 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7529 - val_loss: 0.5366 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7606 - val_loss: 0.5435 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7692 - val_loss: 0.5396 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4662 - accuracy: 0.7792 - val_loss: 0.5506 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4545 - accuracy: 0.7876 - val_loss: 0.5534 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4429 - accuracy: 0.7939 - val_loss: 0.5546 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4272 - accuracy: 0.8032 - val_loss: 0.5568 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4163 - accuracy: 0.8101
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4166 - accuracy: 0.8098 - val_loss: 0.5647 - val_accuracy: 0.7186 - lr: 0.0010

253/253 [==============================] - 0s 792us/step
Independent Testing Matthews Correlation:  0.43207592790238486
Confusion Matrix :
 [[2844 1203]
 [1096 2951]]
Accuracy on test set:    0.715962441314554
Sensitivity:    0.7291821102050902 	 Specificity:    0.7027427724240178
Precision  : 0.7103996148290804
Area Under Curve:    0.715962441314554
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5943 - accuracy: 0.6783 - val_loss: 0.5493 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5481 - accuracy: 0.7196 - val_loss: 0.5416 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5342 - accuracy: 0.7305 - val_loss: 0.5394 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5220 - accuracy: 0.7393 - val_loss: 0.5440 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7486 - val_loss: 0.5400 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7558 - val_loss: 0.5425 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
252/257 [============================>.] - ETA: 0s - loss: 0.4871 - accuracy: 0.7655
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.7652 - val_loss: 0.5448 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 851us/step
Independent Testing Matthews Correlation:  0.4568837155320299
Confusion Matrix :
 [[3143  904]
 [1303 2744]]
Accuracy on test set:    0.7273288855942673
Sensitivity:    0.6780331109463801 	 Specificity:    0.7766246602421547
Precision  : 0.7521929824561403
Area Under Curve:    0.7273288855942674
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5889 - accuracy: 0.6844 - val_loss: 0.5515 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7203 - val_loss: 0.5463 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5334 - accuracy: 0.7330 - val_loss: 0.5469 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5228 - accuracy: 0.7389 - val_loss: 0.5448 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5123 - accuracy: 0.7482 - val_loss: 0.5450 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5020 - accuracy: 0.7547 - val_loss: 0.5539 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4918 - accuracy: 0.7611 - val_loss: 0.5463 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7715 - val_loss: 0.5522 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4659 - accuracy: 0.7779 - val_loss: 0.5585 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4530 - accuracy: 0.7873 - val_loss: 0.5700 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4417 - accuracy: 0.7946 - val_loss: 0.5720 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 12/400
255/257 [============================>.] - ETA: 0s - loss: 0.4286 - accuracy: 0.8013
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4284 - accuracy: 0.8014 - val_loss: 0.5734 - val_accuracy: 0.7154 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46037339805449606
Confusion Matrix :
 [[3025 1022]
 [1163 2884]]
Accuracy on test set:    0.7300469483568075
Sensitivity:    0.7126266370150729 	 Specificity:    0.7474672596985421
Precision  : 0.7383512544802867
Area Under Curve:    0.7300469483568075
(8094, 2560) (8094,)
Mean MCC = 0.4317 + 0.0152 and Mean AUC = 0.7152 + 0.0079
Mean Sensitivity = 0.7249 + 0.0346 and Mean Specificity = 0.7054 + 0.0439 and Mean Accuracy = 0.7152 + 0.0079
Mean Precision = 0.7126 + 0.0212





Seed   : 571197
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6854 - val_loss: 0.5593 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5422 - accuracy: 0.7253 - val_loss: 0.5506 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7361 - val_loss: 0.5543 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7428 - val_loss: 0.5499 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7495 - val_loss: 0.5544 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7583 - val_loss: 0.5544 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7637 - val_loss: 0.5542 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4753 - accuracy: 0.7711 - val_loss: 0.5555 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4618 - accuracy: 0.7801
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4623 - accuracy: 0.7797 - val_loss: 0.5599 - val_accuracy: 0.7079 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4130152684807771
Confusion Matrix :
 [[2890 1158]
 [1218 2829]]
Accuracy on test set:    0.706485484867202
Sensitivity:    0.6990363232023721 	 Specificity:    0.7139328063241107
Precision  : 0.709556057185854
Area Under Curve:    0.7064845647632413
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5868 - accuracy: 0.6845 - val_loss: 0.5617 - val_accuracy: 0.7054 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5420 - accuracy: 0.7250 - val_loss: 0.5548 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.7353 - val_loss: 0.5526 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7431 - val_loss: 0.5541 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7498 - val_loss: 0.5533 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7568 - val_loss: 0.5595 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4863 - accuracy: 0.7646 - val_loss: 0.5614 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7729 - val_loss: 0.5692 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4610 - accuracy: 0.7818 - val_loss: 0.5702 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 10/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4496 - accuracy: 0.7884
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4492 - accuracy: 0.7886 - val_loss: 0.5775 - val_accuracy: 0.7028 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41154446742146983
Confusion Matrix :
 [[2824 1224]
 [1158 2889]]
Accuracy on test set:    0.7057442865966647
Sensitivity:    0.7138621200889548 	 Specificity:    0.6976284584980237
Precision  : 0.7024070021881839
Area Under Curve:    0.7057452892934892
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5873 - accuracy: 0.6868 - val_loss: 0.5547 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7230 - val_loss: 0.5423 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7330 - val_loss: 0.5387 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7411 - val_loss: 0.5426 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.7507 - val_loss: 0.5429 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7565 - val_loss: 0.5457 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7641 - val_loss: 0.5516 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4765 - accuracy: 0.7702
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4766 - accuracy: 0.7700 - val_loss: 0.5460 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 848us/step
Independent Testing Matthews Correlation:  0.4265149049109399
Confusion Matrix :
 [[2948 1099]
 [1223 2825]]
Accuracy on test set:    0.7131562693020383
Sensitivity:    0.6978754940711462 	 Specificity:    0.7284408203607611
Precision  : 0.7199286442405708
Area Under Curve:    0.7131581572159537
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5895 - accuracy: 0.6819 - val_loss: 0.5494 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5484 - accuracy: 0.7203 - val_loss: 0.5406 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5338 - accuracy: 0.7301 - val_loss: 0.5373 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5228 - accuracy: 0.7390 - val_loss: 0.5342 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5140 - accuracy: 0.7449 - val_loss: 0.5344 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.7517 - val_loss: 0.5352 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7595 - val_loss: 0.5388 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4808 - accuracy: 0.7680
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7680 - val_loss: 0.5403 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 892us/step
Independent Testing Matthews Correlation:  0.40754546211999126
Confusion Matrix :
 [[2919 1128]
 [1271 2777]]
Accuracy on test set:    0.7036442248301421
Sensitivity:    0.6860177865612648 	 Specificity:    0.7212750185322461
Precision  : 0.7111395646606914
Area Under Curve:    0.7036464025467554
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5891 - accuracy: 0.6815 - val_loss: 0.5469 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7218 - val_loss: 0.5373 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7336 - val_loss: 0.5344 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7404 - val_loss: 0.5324 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7493 - val_loss: 0.5327 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7580 - val_loss: 0.5365 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4859 - accuracy: 0.7658
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7656 - val_loss: 0.5369 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42133066990116175
Confusion Matrix :
 [[2802 1245]
 [1098 2949]]
Accuracy on test set:    0.7105263157894737
Sensitivity:    0.7286879169755375 	 Specificity:    0.69236471460341
Precision  : 0.7031473533619457
Area Under Curve:    0.7105263157894738
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5888 - accuracy: 0.6842 - val_loss: 0.5461 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7235 - val_loss: 0.5407 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5326 - accuracy: 0.7322 - val_loss: 0.5411 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7385 - val_loss: 0.5395 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5106 - accuracy: 0.7469 - val_loss: 0.5416 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7547 - val_loss: 0.5408 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4915 - accuracy: 0.7617
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7616 - val_loss: 0.5440 - val_accuracy: 0.7207 - lr: 0.0010
253/253 [==============================] - 0s 957us/step
Independent Testing Matthews Correlation:  0.4240940239727662
Confusion Matrix :
 [[2802 1245]
 [1087 2960]]
Accuracy on test set:    0.7118853471707438
Sensitivity:    0.7314059797380776 	 Specificity:    0.69236471460341
Precision  : 0.703923900118906
Area Under Curve:    0.7118853471707438
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5868 - accuracy: 0.6840 - val_loss: 0.5523 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7241 - val_loss: 0.5462 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5267 - accuracy: 0.7351 - val_loss: 0.5458 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5137 - accuracy: 0.7444 - val_loss: 0.5446 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5015 - accuracy: 0.7529 - val_loss: 0.5466 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4903 - accuracy: 0.7609 - val_loss: 0.5494 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4779 - accuracy: 0.7701 - val_loss: 0.5496 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4659 - accuracy: 0.7776 - val_loss: 0.5551 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4524 - accuracy: 0.7852
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4523 - accuracy: 0.7853 - val_loss: 0.5662 - val_accuracy: 0.7115 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4273648442166123
Confusion Matrix :
 [[2757 1290]
 [1031 3016]]
Accuracy on test set:    0.7132443785520138
Sensitivity:    0.7452433901655547 	 Specificity:    0.6812453669384729
Precision  : 0.7004180213655364
Area Under Curve:    0.7132443785520138
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5925 - accuracy: 0.6800 - val_loss: 0.5559 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7219 - val_loss: 0.5461 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5339 - accuracy: 0.7339 - val_loss: 0.5409 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5220 - accuracy: 0.7402 - val_loss: 0.5414 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7489 - val_loss: 0.5396 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7575 - val_loss: 0.5414 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4841 - accuracy: 0.7664 - val_loss: 0.5478 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7760 - val_loss: 0.5484 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4602 - accuracy: 0.7848 - val_loss: 0.5537 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4463 - accuracy: 0.7908 - val_loss: 0.5601 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 11/400
254/257 [============================>.] - ETA: 0s - loss: 0.4307 - accuracy: 0.8021
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4310 - accuracy: 0.8019 - val_loss: 0.5669 - val_accuracy: 0.7130 - lr: 0.0010
253/253 [==============================] - 0s 823us/step
Independent Testing Matthews Correlation:  0.44363175940054866
Confusion Matrix :
 [[2762 1285]
 [ 972 3075]]
Accuracy on test set:    0.7211514702248579
Sensitivity:    0.759822090437361 	 Specificity:    0.6824808500123548
Precision  : 0.7052752293577982
Area Under Curve:    0.7211514702248579
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5926 - accuracy: 0.6802 - val_loss: 0.5553 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7213 - val_loss: 0.5479 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7339 - val_loss: 0.5459 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7412 - val_loss: 0.5450 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7495 - val_loss: 0.5453 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7579 - val_loss: 0.5527 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7655 - val_loss: 0.5481 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4683 - accuracy: 0.7773 - val_loss: 0.5543 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.7846 - val_loss: 0.5604 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4447 - accuracy: 0.7919
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4442 - accuracy: 0.7918 - val_loss: 0.5610 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.4509709792359616
Confusion Matrix :
 [[3052  995]
 [1230 2817]]
Accuracy on test set:    0.72510501606128
Sensitivity:    0.6960711638250556 	 Specificity:    0.7541388682975043
Precision  : 0.7389821615949633
Area Under Curve:    0.72510501606128
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5937 - accuracy: 0.6806 - val_loss: 0.5575 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5497 - accuracy: 0.7201 - val_loss: 0.5503 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5341 - accuracy: 0.7298 - val_loss: 0.5522 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7412 - val_loss: 0.5508 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7492 - val_loss: 0.5468 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7558 - val_loss: 0.5550 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4872 - accuracy: 0.7652 - val_loss: 0.5493 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4738 - accuracy: 0.7737 - val_loss: 0.5548 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4614 - accuracy: 0.7806 - val_loss: 0.5608 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4484 - accuracy: 0.7888 - val_loss: 0.5603 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4354 - accuracy: 0.7979 - val_loss: 0.5739 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4272 - accuracy: 0.8033 - val_loss: 0.5744 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4129 - accuracy: 0.8105 - val_loss: 0.5925 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4009 - accuracy: 0.8158 - val_loss: 0.5863 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 15/400
251/257 [============================>.] - ETA: 0s - loss: 0.3895 - accuracy: 0.8224
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3893 - accuracy: 0.8225 - val_loss: 0.6073 - val_accuracy: 0.7080 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47459731153123186
Confusion Matrix :
 [[2898 1149]
 [ 979 3068]]
Accuracy on test set:    0.7370892018779343
Sensitivity:    0.7580924141339264 	 Specificity:    0.7160859896219421
Precision  : 0.7275314204410719
Area Under Curve:    0.7370892018779344
(8094, 2560) (8094,)
Mean MCC = 0.4301 + 0.0197 and Mean AUC = 0.7148 + 0.0098
Mean Sensitivity = 0.7216 + 0.0256 and Mean Specificity = 0.7080 + 0.0219 and Mean Accuracy = 0.7148 + 0.0098
Mean Precision = 0.7122 + 0.0121





Seed   : 620505

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5862 - accuracy: 0.6883 - val_loss: 0.5607 - val_accuracy: 0.7054 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7257 - val_loss: 0.5512 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7342 - val_loss: 0.5492 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7427 - val_loss: 0.5474 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7517 - val_loss: 0.5629 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7574 - val_loss: 0.5493 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7679 - val_loss: 0.5544 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4688 - accuracy: 0.7763 - val_loss: 0.5557 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4544 - accuracy: 0.7870 - val_loss: 0.5593 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4427 - accuracy: 0.7946 - val_loss: 0.5609 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4313 - accuracy: 0.8001 - val_loss: 0.5764 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4152 - accuracy: 0.8100 - val_loss: 0.5684 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 13/400
255/257 [============================>.] - ETA: 0s - loss: 0.4028 - accuracy: 0.8161
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4030 - accuracy: 0.8162 - val_loss: 0.5822 - val_accuracy: 0.7124 - lr: 0.0010
253/253 [==============================] - 0s 786us/step
Independent Testing Matthews Correlation:  0.4049558514030532
Confusion Matrix :
 [[2660 1388]
 [1027 3020]]
Accuracy on test set:    0.701667696108709
Sensitivity:    0.7462317766246602 	 Specificity:    0.6571146245059288
Precision  : 0.6851179673321234
Area Under Curve:    0.7016732005652945
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5918 - accuracy: 0.6804 - val_loss: 0.5595 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7231 - val_loss: 0.5525 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7320 - val_loss: 0.5488 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7420 - val_loss: 0.5483 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7482 - val_loss: 0.5505 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7558 - val_loss: 0.5579 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7647 - val_loss: 0.5597 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4727 - accuracy: 0.7741
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4727 - accuracy: 0.7741 - val_loss: 0.5583 - val_accuracy: 0.7047 - lr: 0.0010
253/253 [==============================] - 0s 982us/step
Independent Testing Matthews Correlation:  0.4218654755887128
Confusion Matrix :
 [[2880 1168]
 [1172 2875]]
Accuracy on test set:    0.7109326744904262
Sensitivity:    0.7104027674820855 	 Specificity:    0.7114624505928854
Precision  : 0.7111056146425921
Area Under Curve:    0.7109326090374856
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5887 - accuracy: 0.6835 - val_loss: 0.5521 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7230 - val_loss: 0.5468 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7337 - val_loss: 0.5488 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7419 - val_loss: 0.5428 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7494 - val_loss: 0.5440 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7551 - val_loss: 0.5458 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4852 - accuracy: 0.7661
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.7661 - val_loss: 0.5466 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4216508478230063
Confusion Matrix :
 [[2851 1196]
 [1145 2903]]
Accuracy on test set:    0.7108091414453366
Sensitivity:    0.7171442687747036 	 Specificity:    0.7044724487274524
Precision  : 0.7082215174432789
Area Under Curve:    0.7108083587510781
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5868 - accuracy: 0.6839 - val_loss: 0.5506 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7245 - val_loss: 0.5408 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7350 - val_loss: 0.5381 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7428 - val_loss: 0.5390 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7507 - val_loss: 0.5416 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7589 - val_loss: 0.5408 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4819 - accuracy: 0.7669 - val_loss: 0.5411 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4698 - accuracy: 0.7757 - val_loss: 0.5455 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4577 - accuracy: 0.7837 - val_loss: 0.5516 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4474 - accuracy: 0.7916 - val_loss: 0.5562 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 11/400
252/257 [============================>.] - ETA: 0s - loss: 0.4323 - accuracy: 0.7984
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4320 - accuracy: 0.7986 - val_loss: 0.5667 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4160867349259275
Confusion Matrix :
 [[2751 1296]
 [1070 2978]]
Accuracy on test set:    0.7077208153180976
Sensitivity:    0.7356719367588933 	 Specificity:    0.6797627872498146
Precision  : 0.6967711745437529
Area Under Curve:    0.707717362004354
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5881 - accuracy: 0.6848 - val_loss: 0.5556 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7213 - val_loss: 0.5532 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7321 - val_loss: 0.5461 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7416 - val_loss: 0.5462 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7495 - val_loss: 0.5458 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7590 - val_loss: 0.5569 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7664 - val_loss: 0.5523 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4693 - accuracy: 0.7747
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4697 - accuracy: 0.7747 - val_loss: 0.5519 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 731us/step
Independent Testing Matthews Correlation:  0.4346816427880999
Confusion Matrix :
 [[2930 1117]
 [1171 2876]]
Accuracy on test set:    0.717321472695824
Sensitivity:    0.7106498640968619 	 Specificity:    0.7239930812947862
Precision  : 0.7202604557976459
Area Under Curve:    0.717321472695824
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5921 - accuracy: 0.6817 - val_loss: 0.5565 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7210 - val_loss: 0.5475 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5339 - accuracy: 0.7323 - val_loss: 0.5480 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.7392 - val_loss: 0.5534 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7448 - val_loss: 0.5474 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5033 - accuracy: 0.7514 - val_loss: 0.5480 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4926 - accuracy: 0.7607
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7609 - val_loss: 0.5518 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 728us/step
Independent Testing Matthews Correlation:  0.4418716569483989
Confusion Matrix :
 [[2776 1271]
 [ 992 3055]]
Accuracy on test set:    0.7204101803805288
Sensitivity:    0.7548801581418334 	 Specificity:    0.6859402026192242
Precision  : 0.7061950993989828
Area Under Curve:    0.7204101803805286
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5868 - accuracy: 0.6852 - val_loss: 0.5555 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7221 - val_loss: 0.5444 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7336 - val_loss: 0.5434 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7397 - val_loss: 0.5475 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5102 - accuracy: 0.7485 - val_loss: 0.5544 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7549 - val_loss: 0.5476 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4892 - accuracy: 0.7624
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4896 - accuracy: 0.7626 - val_loss: 0.5513 - val_accuracy: 0.7093 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44252571256123385
Confusion Matrix :
 [[2713 1334]
 [ 931 3116]]
Accuracy on test set:    0.7201630837657524
Sensitivity:    0.7699530516431925 	 Specificity:    0.6703731158883123
Precision  : 0.7002247191011236
Area Under Curve:    0.7201630837657524
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5950 - accuracy: 0.6778 - val_loss: 0.5613 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5500 - accuracy: 0.7207 - val_loss: 0.5458 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7330 - val_loss: 0.5444 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7425 - val_loss: 0.5445 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7519 - val_loss: 0.5438 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7606 - val_loss: 0.5449 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4775 - accuracy: 0.7717
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7711 - val_loss: 0.5449 - val_accuracy: 0.7175 - lr: 0.0010
253/253 [==============================] - 0s 914us/step
Independent Testing Matthews Correlation:  0.42894782632739126
Confusion Matrix :
 [[2824 1223]
 [1089 2958]]
Accuracy on test set:    0.7143563133185076
Sensitivity:    0.7309117865085248 	 Specificity:    0.6978008401284902
Precision  : 0.7074862473092561
Area Under Curve:    0.7143563133185076
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5944 - accuracy: 0.6792 - val_loss: 0.5601 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5484 - accuracy: 0.7219 - val_loss: 0.5525 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7314 - val_loss: 0.5486 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5235 - accuracy: 0.7391 - val_loss: 0.5477 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5123 - accuracy: 0.7455 - val_loss: 0.5516 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7527 - val_loss: 0.5556 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7608 - val_loss: 0.5498 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4806 - accuracy: 0.7689 - val_loss: 0.5569 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4664 - accuracy: 0.7777
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.7777 - val_loss: 0.5602 - val_accuracy: 0.7171 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44234087465845
Confusion Matrix :
 [[2892 1155]
 [1102 2945]]
Accuracy on test set:    0.7211514702248579
Sensitivity:    0.7276995305164319 	 Specificity:    0.7146034099332839
Precision  : 0.7182926829268292
Area Under Curve:    0.7211514702248578
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5960 - accuracy: 0.6767 - val_loss: 0.5617 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5527 - accuracy: 0.7190 - val_loss: 0.5520 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5372 - accuracy: 0.7305 - val_loss: 0.5524 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5232 - accuracy: 0.7404 - val_loss: 0.5497 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5112 - accuracy: 0.7485 - val_loss: 0.5480 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4987 - accuracy: 0.7570 - val_loss: 0.5499 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7664 - val_loss: 0.5550 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4730 - accuracy: 0.7749 - val_loss: 0.5608 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4608 - accuracy: 0.7834 - val_loss: 0.5623 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4512 - accuracy: 0.7896 - val_loss: 0.5678 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4378 - accuracy: 0.7992 - val_loss: 0.5664 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4238 - accuracy: 0.8067 - val_loss: 0.5831 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 13/400
255/257 [============================>.] - ETA: 0s - loss: 0.4144 - accuracy: 0.8111
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4144 - accuracy: 0.8111 - val_loss: 0.5871 - val_accuracy: 0.7113 - lr: 0.0010
253/253 [==============================] - 0s 756us/step
Independent Testing Matthews Correlation:  0.4589770250082854
Confusion Matrix :
 [[2906 1141]
 [1049 2998]]
Accuracy on test set:    0.7294292068198666
Sensitivity:    0.7407956510995799 	 Specificity:    0.7180627625401532
Precision  : 0.7243295482000484
Area Under Curve:    0.7294292068198666
(8094, 2560) (8094,)
Mean MCC = 0.4314 + 0.0150 and Mean AUC = 0.7154 + 0.0076
Mean Sensitivity = 0.7344 + 0.0183 and Mean Specificity = 0.6964 + 0.0211 and Mean Accuracy = 0.7154 + 0.0076
Mean Precision = 0.7078 + 0.0112





Seed   : 436619
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5868 - accuracy: 0.6851 - val_loss: 0.5681 - val_accuracy: 0.7006 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7252 - val_loss: 0.5594 - val_accuracy: 0.7019 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7361 - val_loss: 0.5587 - val_accuracy: 0.7031 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7422 - val_loss: 0.5533 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7496 - val_loss: 0.5573 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7587 - val_loss: 0.5575 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7667 - val_loss: 0.5642 - val_accuracy: 0.7031 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4718 - accuracy: 0.7747 - val_loss: 0.5693 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4603 - accuracy: 0.7802 - val_loss: 0.5725 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4465 - accuracy: 0.7907
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4469 - accuracy: 0.7904 - val_loss: 0.5762 - val_accuracy: 0.7028 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42043320178821203
Confusion Matrix :
 [[2638 1410]
 [ 947 3100]]
Accuracy on test set:    0.7088326127239036
Sensitivity:    0.7659995058067705 	 Specificity:    0.6516798418972332
Precision  : 0.6873614190687362
Area Under Curve:    0.7088396738520018
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5901 - accuracy: 0.6826 - val_loss: 0.5644 - val_accuracy: 0.7058 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5420 - accuracy: 0.7272 - val_loss: 0.5539 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7353 - val_loss: 0.5502 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7429 - val_loss: 0.5533 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5038 - accuracy: 0.7531 - val_loss: 0.5539 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.7583 - val_loss: 0.5572 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7679 - val_loss: 0.5525 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4700 - accuracy: 0.7752
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4697 - accuracy: 0.7754 - val_loss: 0.5591 - val_accuracy: 0.7137 - lr: 0.0010
253/253 [==============================] - 0s 936us/step
Independent Testing Matthews Correlation:  0.41255105780404683
Confusion Matrix :
 [[2779 1269]
 [1110 2937]]
Accuracy on test set:    0.7061148857319333
Sensitivity:    0.7257227575982209 	 Specificity:    0.6865118577075099
Precision  : 0.6982881597717546
Area Under Curve:    0.7061173076528653
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5857 - accuracy: 0.6856 - val_loss: 0.5546 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7226 - val_loss: 0.5480 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7348 - val_loss: 0.5445 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7419 - val_loss: 0.5458 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7508 - val_loss: 0.5484 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7583 - val_loss: 0.5477 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7639 - val_loss: 0.5513 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7735 - val_loss: 0.5541 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4612 - accuracy: 0.7822 - val_loss: 0.5590 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4505 - accuracy: 0.7888 - val_loss: 0.5592 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4363 - accuracy: 0.7981 - val_loss: 0.5649 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - ETA: 0s - loss: 0.4230 - accuracy: 0.8044
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4230 - accuracy: 0.8044 - val_loss: 0.5739 - val_accuracy: 0.7120 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4139719149897607
Confusion Matrix :
 [[2718 1329]
 [1047 3001]]
Accuracy on test set:    0.706485484867202
Sensitivity:    0.7413537549407114 	 Specificity:    0.6716085989621943
Precision  : 0.6930715935334874
Area Under Curve:    0.7064811769514528
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5889 - accuracy: 0.6830 - val_loss: 0.5532 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7234 - val_loss: 0.5431 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7321 - val_loss: 0.5377 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7394 - val_loss: 0.5386 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7495 - val_loss: 0.5385 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7566 - val_loss: 0.5417 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7668 - val_loss: 0.5431 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7756 - val_loss: 0.5488 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4541 - accuracy: 0.7846 - val_loss: 0.5553 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4426 - accuracy: 0.7940
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4427 - accuracy: 0.7938 - val_loss: 0.5595 - val_accuracy: 0.7202 - lr: 0.0010
253/253 [==============================] - 0s 927us/step
Independent Testing Matthews Correlation:  0.41910143815700174
Confusion Matrix :
 [[2808 1239]
 [1113 2935]]
Accuracy on test set:    0.7094502779493514
Sensitivity:    0.7250494071146245 	 Specificity:    0.6938472942920682
Precision  : 0.7031624341159559
Area Under Curve:    0.7094483507033463
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5895 - accuracy: 0.6816 - val_loss: 0.5455 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7217 - val_loss: 0.5373 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7327 - val_loss: 0.5355 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7414 - val_loss: 0.5363 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7483 - val_loss: 0.5394 - val_accuracy: 0.7321 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7573 - val_loss: 0.5373 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4871 - accuracy: 0.7635 - val_loss: 0.5432 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4762 - accuracy: 0.7704 - val_loss: 0.5421 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4656 - accuracy: 0.7778 - val_loss: 0.5502 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4553 - accuracy: 0.7845
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4558 - accuracy: 0.7841 - val_loss: 0.5497 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41390855547881916
Confusion Matrix :
 [[2961 1086]
 [1288 2759]]
Accuracy on test set:    0.7066963182604399
Sensitivity:    0.6817395601680257 	 Specificity:    0.7316530763528539
Precision  : 0.717555266579974
Area Under Curve:    0.7066963182604398
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5860 - accuracy: 0.6836 - val_loss: 0.5478 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7239 - val_loss: 0.5391 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7350 - val_loss: 0.5428 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7443 - val_loss: 0.5377 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7515 - val_loss: 0.5374 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7602 - val_loss: 0.5390 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7663 - val_loss: 0.5420 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.7739 - val_loss: 0.5424 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4602 - accuracy: 0.7808 - val_loss: 0.5468 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4476 - accuracy: 0.7898 - val_loss: 0.5523 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 11/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4345 - accuracy: 0.7987
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4347 - accuracy: 0.7986 - val_loss: 0.5592 - val_accuracy: 0.7244 - lr: 0.0010
253/253 [==============================] - 0s 784us/step
Independent Testing Matthews Correlation:  0.4149084864533435
Confusion Matrix :
 [[2760 1287]
 [1083 2964]]
Accuracy on test set:    0.7071905114899926
Sensitivity:    0.7323943661971831 	 Specificity:    0.6819866567828021
Precision  : 0.6972477064220184
Area Under Curve:    0.7071905114899926
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5887 - accuracy: 0.6843 - val_loss: 0.5464 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7199 - val_loss: 0.5401 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7334 - val_loss: 0.5370 - val_accuracy: 0.7230 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7413 - val_loss: 0.5384 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.7472 - val_loss: 0.5370 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7556 - val_loss: 0.5409 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7633 - val_loss: 0.5387 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.7712 - val_loss: 0.5414 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4662 - accuracy: 0.7791 - val_loss: 0.5445 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4511 - accuracy: 0.7884 - val_loss: 0.5463 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4407 - accuracy: 0.7931 - val_loss: 0.5518 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 12/400
252/257 [============================>.] - ETA: 0s - loss: 0.4283 - accuracy: 0.8029
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4287 - accuracy: 0.8028 - val_loss: 0.5578 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4050649202677193
Confusion Matrix :
 [[2923 1124]
 [1285 2762]]
Accuracy on test set:    0.7023721275018532
Sensitivity:    0.6824808500123548 	 Specificity:    0.7222634049913517
Precision  : 0.7107565620174987
Area Under Curve:    0.7023721275018533
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5995 - accuracy: 0.6752 - val_loss: 0.5581 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5525 - accuracy: 0.7172 - val_loss: 0.5420 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5377 - accuracy: 0.7292 - val_loss: 0.5396 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5268 - accuracy: 0.7364 - val_loss: 0.5379 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7444 - val_loss: 0.5380 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7509 - val_loss: 0.5366 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4937 - accuracy: 0.7608
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7610 - val_loss: 0.5498 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 0s 940us/step
Independent Testing Matthews Correlation:  0.4385089932139238
Confusion Matrix :
 [[2626 1421]
 [ 868 3179]]
Accuracy on test set:    0.7171979243884359
Sensitivity:    0.7855201383741043 	 Specificity:    0.6488757104027675
Precision  : 0.6910869565217391
Area Under Curve:    0.7171979243884359
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6835 - val_loss: 0.5489 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5477 - accuracy: 0.7213 - val_loss: 0.5398 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7313 - val_loss: 0.5384 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5216 - accuracy: 0.7395 - val_loss: 0.5377 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7487 - val_loss: 0.5388 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5003 - accuracy: 0.7560 - val_loss: 0.5405 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7622 - val_loss: 0.5457 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4808 - accuracy: 0.7706
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.7706 - val_loss: 0.5429 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46707211247366176
Confusion Matrix :
 [[3066  981]
 [1178 2869]]
Accuracy on test set:    0.7332592043489005
Sensitivity:    0.7089201877934272 	 Specificity:    0.7575982209043736
Precision  : 0.7451948051948052
Area Under Curve:    0.7332592043489005
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5978 - accuracy: 0.6735 - val_loss: 0.5504 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5514 - accuracy: 0.7187 - val_loss: 0.5409 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5365 - accuracy: 0.7306 - val_loss: 0.5389 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5230 - accuracy: 0.7385 - val_loss: 0.5400 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5124 - accuracy: 0.7467 - val_loss: 0.5374 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5011 - accuracy: 0.7545 - val_loss: 0.5456 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4886 - accuracy: 0.7623
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.7628 - val_loss: 0.5423 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47102649259367385
Confusion Matrix :
 [[3181  866]
 [1285 2762]]
Accuracy on test set:    0.734247590808006
Sensitivity:    0.6824808500123548 	 Specificity:    0.7860143316036571
Precision  : 0.7613009922822491
Area Under Curve:    0.7342475908080058
(8094, 2560) (8094,)
Mean MCC = 0.4277 + 0.0223 and Mean AUC = 0.7132 + 0.0109
Mean Sensitivity = 0.7232 + 0.0337 and Mean Specificity = 0.7032 + 0.0429 and Mean Accuracy = 0.7132 + 0.0109
Mean Precision = 0.7105 + 0.0233





Seed   : 750328
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5848 - accuracy: 0.6853 - val_loss: 0.5622 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5408 - accuracy: 0.7261 - val_loss: 0.5576 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5257 - accuracy: 0.7369 - val_loss: 0.5564 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5130 - accuracy: 0.7438 - val_loss: 0.5556 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.7532 - val_loss: 0.5567 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4890 - accuracy: 0.7608 - val_loss: 0.5587 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4783 - accuracy: 0.7695 - val_loss: 0.5716 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7789 - val_loss: 0.5706 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4498 - accuracy: 0.7882 - val_loss: 0.5707 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4374 - accuracy: 0.7954
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4376 - accuracy: 0.7953 - val_loss: 0.5748 - val_accuracy: 0.7089 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4015310834090892
Confusion Matrix :
 [[2589 1459]
 [ 975 3072]]
Accuracy on test set:    0.6993205682520074
Sensitivity:    0.7590808005930318 	 Specificity:    0.6395750988142292
Precision  : 0.6779960273670271
Area Under Curve:    0.6993279497036305
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5835 - accuracy: 0.6882 - val_loss: 0.5751 - val_accuracy: 0.6957 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5419 - accuracy: 0.7250 - val_loss: 0.5563 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5235 - accuracy: 0.7368 - val_loss: 0.5573 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5128 - accuracy: 0.7448 - val_loss: 0.5588 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7518 - val_loss: 0.5561 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7617 - val_loss: 0.5659 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.7700 - val_loss: 0.5624 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4632 - accuracy: 0.7792 - val_loss: 0.5606 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4505 - accuracy: 0.7875 - val_loss: 0.5757 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4377 - accuracy: 0.7950 - val_loss: 0.5863 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4244 - accuracy: 0.8042 - val_loss: 0.5802 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4112 - accuracy: 0.8114 - val_loss: 0.5911 - val_accuracy: 0.7035 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3992 - accuracy: 0.8173 - val_loss: 0.5992 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3870 - accuracy: 0.8248 - val_loss: 0.6020 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3752 - accuracy: 0.8316 - val_loss: 0.6184 - val_accuracy: 0.7013 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3666 - accuracy: 0.8339 - val_loss: 0.6198 - val_accuracy: 0.7032 - lr: 0.0010
Epoch 17/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3564 - accuracy: 0.8407 - val_loss: 0.6303 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 18/400
251/257 [============================>.] - ETA: 0s - loss: 0.3447 - accuracy: 0.8449
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3447 - accuracy: 0.8451 - val_loss: 0.6498 - val_accuracy: 0.7019 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4081192061341733
Confusion Matrix :
 [[2656 1392]
 [1011 3036]]
Accuracy on test set:    0.7031500926497838
Sensitivity:    0.7501853224610823 	 Specificity:    0.6561264822134387
Precision  : 0.6856368563685636
Area Under Curve:    0.7031559023372606
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5843 - accuracy: 0.6882 - val_loss: 0.5530 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7249 - val_loss: 0.5492 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7344 - val_loss: 0.5423 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7419 - val_loss: 0.5418 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7516 - val_loss: 0.5452 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4927 - accuracy: 0.7566 - val_loss: 0.5488 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4794 - accuracy: 0.7670 - val_loss: 0.5488 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4694 - accuracy: 0.7756 - val_loss: 0.5530 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4559 - accuracy: 0.7827
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4559 - accuracy: 0.7827 - val_loss: 0.5525 - val_accuracy: 0.7157 - lr: 0.0010
253/253 [==============================] - 0s 791us/step
Independent Testing Matthews Correlation:  0.42338812816210897
Confusion Matrix :
 [[2777 1270]
 [1066 2982]]
Accuracy on test set:    0.7114268066707844
Sensitivity:    0.7366600790513834 	 Specificity:    0.6861872992340005
Precision  : 0.7013170272812794
Area Under Curve:    0.7114236891426919
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6862 - val_loss: 0.5544 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7242 - val_loss: 0.5428 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7354 - val_loss: 0.5425 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7413 - val_loss: 0.5401 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7502 - val_loss: 0.5403 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7573 - val_loss: 0.5439 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7655 - val_loss: 0.5451 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7735 - val_loss: 0.5496 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4608 - accuracy: 0.7830 - val_loss: 0.5500 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4485 - accuracy: 0.7897 - val_loss: 0.5575 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4376 - accuracy: 0.7975 - val_loss: 0.5638 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 12/400

257/257 [==============================] - 1s 4ms/step - loss: 0.4223 - accuracy: 0.8054 - val_loss: 0.5802 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4115 - accuracy: 0.8132 - val_loss: 0.5726 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 14/400
253/257 [============================>.] - ETA: 0s - loss: 0.3976 - accuracy: 0.8219
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3977 - accuracy: 0.8218 - val_loss: 0.5850 - val_accuracy: 0.7145 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41223309365681116
Confusion Matrix :
 [[2849 1198]
 [1181 2867]]
Accuracy on test set:    0.7061148857319333
Sensitivity:    0.7082509881422925 	 Specificity:    0.7039782554978997
Precision  : 0.7052890528905289
Area Under Curve:    0.7061146218200961
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5890 - accuracy: 0.6821 - val_loss: 0.5565 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7228 - val_loss: 0.5486 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.7353 - val_loss: 0.5466 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7448 - val_loss: 0.5506 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7523 - val_loss: 0.5466 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7596 - val_loss: 0.5505 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4777 - accuracy: 0.7685 - val_loss: 0.5535 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4679 - accuracy: 0.7766
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4673 - accuracy: 0.7769 - val_loss: 0.5596 - val_accuracy: 0.7197 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4176811307007532
Confusion Matrix :
 [[2827 1220]
 [1137 2910]]
Accuracy on test set:    0.708796639486039
Sensitivity:    0.7190511489992587 	 Specificity:    0.6985421299728194
Precision  : 0.7046004842615012
Area Under Curve:    0.708796639486039
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5870 - accuracy: 0.6847 - val_loss: 0.5568 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7259 - val_loss: 0.5483 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7335 - val_loss: 0.5472 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7428 - val_loss: 0.5464 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7491 - val_loss: 0.5479 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7572 - val_loss: 0.5504 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7643 - val_loss: 0.5535 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4752 - accuracy: 0.7729 - val_loss: 0.5537 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4630 - accuracy: 0.7794 - val_loss: 0.5550 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4502 - accuracy: 0.7868
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4514 - accuracy: 0.7862 - val_loss: 0.5599 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4223705892774341
Confusion Matrix :
 [[2732 1315]
 [1027 3020]]
Accuracy on test set:    0.7106498640968619
Sensitivity:    0.7462317766246602 	 Specificity:    0.6750679515690635
Precision  : 0.6966551326412919
Area Under Curve:    0.7106498640968619
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5865 - accuracy: 0.6848 - val_loss: 0.5512 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7241 - val_loss: 0.5474 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7322 - val_loss: 0.5465 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7405 - val_loss: 0.5474 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7477 - val_loss: 0.5469 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 6/400
254/257 [============================>.] - ETA: 0s - loss: 0.4975 - accuracy: 0.7558
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7559 - val_loss: 0.5487 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43192647813934915
Confusion Matrix :
 [[2892 1155]
 [1144 2903]]
Accuracy on test set:    0.715962441314554
Sensitivity:    0.717321472695824 	 Specificity:    0.7146034099332839
Precision  : 0.7153770330211927
Area Under Curve:    0.7159624413145539
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5887 - accuracy: 0.6841 - val_loss: 0.5618 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7220 - val_loss: 0.5456 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7324 - val_loss: 0.5429 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7404 - val_loss: 0.5413 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.7464 - val_loss: 0.5406 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7538 - val_loss: 0.5442 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7612 - val_loss: 0.5441 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7689 - val_loss: 0.5487 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.7790 - val_loss: 0.5525 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4551 - accuracy: 0.7860 - val_loss: 0.5552 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4419 - accuracy: 0.7957
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4418 - accuracy: 0.7957 - val_loss: 0.5663 - val_accuracy: 0.7154 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4201634614444646
Confusion Matrix :
 [[3017 1030]
 [1321 2726]]
Accuracy on test set:    0.7095379293303682
Sensitivity:    0.6735853718804052 	 Specificity:    0.7454904867803311
Precision  : 0.7257720979765708
Area Under Curve:    0.7095379293303683
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5907 - accuracy: 0.6821 - val_loss: 0.5530 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7205 - val_loss: 0.5540 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5355 - accuracy: 0.7290 - val_loss: 0.5449 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5245 - accuracy: 0.7369 - val_loss: 0.5427 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5143 - accuracy: 0.7441 - val_loss: 0.5442 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7524 - val_loss: 0.5459 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7616 - val_loss: 0.5482 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7684 - val_loss: 0.5485 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4672 - accuracy: 0.7783 - val_loss: 0.5565 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4540 - accuracy: 0.7872 - val_loss: 0.5587 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4406 - accuracy: 0.7944 - val_loss: 0.5710 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4274 - accuracy: 0.8045 - val_loss: 0.5778 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4156 - accuracy: 0.8106 - val_loss: 0.5837 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4049 - accuracy: 0.8166 - val_loss: 0.5880 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3941 - accuracy: 0.8219 - val_loss: 0.5954 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3832 - accuracy: 0.8277 - val_loss: 0.6008 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 17/400
257/257 [==============================] - ETA: 0s - loss: 0.3722 - accuracy: 0.8319
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3722 - accuracy: 0.8319 - val_loss: 0.6195 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47172381039552597
Confusion Matrix :
 [[2844 1203]
 [ 939 3108]]
Accuracy on test set:    0.7353595255744997
Sensitivity:    0.7679762787249814 	 Specificity:    0.7027427724240178
Precision  : 0.720946416144746
Area Under Curve:    0.7353595255744996
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5912 - accuracy: 0.6826 - val_loss: 0.5552 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5496 - accuracy: 0.7189 - val_loss: 0.5455 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5340 - accuracy: 0.7326 - val_loss: 0.5420 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5235 - accuracy: 0.7374 - val_loss: 0.5424 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5113 - accuracy: 0.7477 - val_loss: 0.5451 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4995 - accuracy: 0.7547 - val_loss: 0.5457 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.7638 - val_loss: 0.5546 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4758 - accuracy: 0.7723 - val_loss: 0.5483 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4632 - accuracy: 0.7829 - val_loss: 0.5655 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 10/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4482 - accuracy: 0.7900
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4477 - accuracy: 0.7904 - val_loss: 0.5637 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 931us/step
Independent Testing Matthews Correlation:  0.4877656510556707
Confusion Matrix :
 [[2946 1101]
 [ 973 3074]]
Accuracy on test set:    0.7437608104768965
Sensitivity:    0.7595749938225846 	 Specificity:    0.7279466271312083
Precision  : 0.7362874251497006
Area Under Curve:    0.7437608104768965
(8094, 2560) (8094,)
Mean MCC = 0.4297 + 0.0265 and Mean AUC = 0.7144 + 0.0134
Mean Sensitivity = 0.7338 + 0.0277 and Mean Specificity = 0.6950 + 0.0304 and Mean Accuracy = 0.7144 + 0.0134
Mean Precision = 0.7070 + 0.0171





Seed   : 588223
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5855 - accuracy: 0.6876 - val_loss: 0.5712 - val_accuracy: 0.7031 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7243 - val_loss: 0.5537 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7356 - val_loss: 0.5511 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7425 - val_loss: 0.5520 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7494 - val_loss: 0.5531 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7575 - val_loss: 0.5508 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7661 - val_loss: 0.5582 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4714 - accuracy: 0.7756 - val_loss: 0.5574 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4578 - accuracy: 0.7844 - val_loss: 0.5649 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4431 - accuracy: 0.7919 - val_loss: 0.5637 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4335 - accuracy: 0.7987 - val_loss: 0.5706 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4180 - accuracy: 0.8074 - val_loss: 0.5797 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4059 - accuracy: 0.8144 - val_loss: 0.5927 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 14/400
245/257 [===========================>..] - ETA: 0s - loss: 0.3955 - accuracy: 0.8212
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3958 - accuracy: 0.8210 - val_loss: 0.6037 - val_accuracy: 0.7035 - lr: 0.0010

253/253 [==============================] - 0s 798us/step
Independent Testing Matthews Correlation:  0.39231941958344435
Confusion Matrix :
 [[2582 1466]
 [1004 3043]]
Accuracy on test set:    0.6948733786287832
Sensitivity:    0.751914998764517 	 Specificity:    0.6378458498023716
Precision  : 0.6748724772676868
Area Under Curve:    0.6948804242834443
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5887 - accuracy: 0.6826 - val_loss: 0.5617 - val_accuracy: 0.7040 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7226 - val_loss: 0.5521 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7346 - val_loss: 0.5488 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7424 - val_loss: 0.5473 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7500 - val_loss: 0.5483 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7584 - val_loss: 0.5529 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7667 - val_loss: 0.5520 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4703 - accuracy: 0.7750 - val_loss: 0.5577 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4582 - accuracy: 0.7847 - val_loss: 0.5744 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4450 - accuracy: 0.7927 - val_loss: 0.5681 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 11/400
249/257 [============================>.] - ETA: 0s - loss: 0.4300 - accuracy: 0.8009
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4305 - accuracy: 0.8004 - val_loss: 0.5737 - val_accuracy: 0.7060 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4214016895763179
Confusion Matrix :
 [[2853 1195]
 [1147 2900]]
Accuracy on test set:    0.7106856084002471
Sensitivity:    0.7165801828514949 	 Specificity:    0.704792490118577
Precision  : 0.7081807081807082
Area Under Curve:    0.710686336485036
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5885 - accuracy: 0.6843 - val_loss: 0.5514 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7222 - val_loss: 0.5411 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7333 - val_loss: 0.5379 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7426 - val_loss: 0.5382 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7493 - val_loss: 0.5400 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7571 - val_loss: 0.5383 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.7642 - val_loss: 0.5431 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7755 - val_loss: 0.5419 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4627 - accuracy: 0.7827 - val_loss: 0.5476 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4499 - accuracy: 0.7900 - val_loss: 0.5557 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 11/400
250/257 [============================>.] - ETA: 0s - loss: 0.4386 - accuracy: 0.7972
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4386 - accuracy: 0.7971 - val_loss: 0.5557 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41569617167476364
Confusion Matrix :
 [[2852 1195]
 [1170 2878]]
Accuracy on test set:    0.7078443483631871
Sensitivity:    0.7109683794466403 	 Specificity:    0.7047195453422288
Precision  : 0.7066044684507734
Area Under Curve:    0.7078439623944345
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5916 - accuracy: 0.6812 - val_loss: 0.5474 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7215 - val_loss: 0.5385 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7319 - val_loss: 0.5340 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7402 - val_loss: 0.5335 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5102 - accuracy: 0.7474 - val_loss: 0.5355 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4999 - accuracy: 0.7527 - val_loss: 0.5337 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4892 - accuracy: 0.7618 - val_loss: 0.5400 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4763 - accuracy: 0.7711
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4765 - accuracy: 0.7711 - val_loss: 0.5448 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 816us/step
Independent Testing Matthews Correlation:  0.4111148775282862
Confusion Matrix :
 [[2591 1456]
 [ 941 3107]]
Accuracy on test set:    0.7038912909203212
Sensitivity:    0.7675395256916996 	 Specificity:    0.6402273288855943
Precision  : 0.6809116809116809
Area Under Curve:    0.703883427288647
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5895 - accuracy: 0.6812 - val_loss: 0.5668 - val_accuracy: 0.7017 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7221 - val_loss: 0.5533 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7327 - val_loss: 0.5503 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7405 - val_loss: 0.5487 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5094 - accuracy: 0.7488 - val_loss: 0.5524 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7551 - val_loss: 0.5524 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.7650 - val_loss: 0.5531 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4766 - accuracy: 0.7718 - val_loss: 0.5662 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4621 - accuracy: 0.7803
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4621 - accuracy: 0.7801 - val_loss: 0.5639 - val_accuracy: 0.7111 - lr: 0.0010

253/253 [==============================] - 0s 853us/step
Independent Testing Matthews Correlation:  0.4171931990135117
Confusion Matrix :
 [[3053  994]
 [1372 2675]]
Accuracy on test set:    0.7076847047195454
Sensitivity:    0.66098344452681 	 Specificity:    0.7543859649122807
Precision  : 0.729081493594985
Area Under Curve:    0.7076847047195454
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5869 - accuracy: 0.6836 - val_loss: 0.5558 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7233 - val_loss: 0.5533 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7359 - val_loss: 0.5498 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7431 - val_loss: 0.5478 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7505 - val_loss: 0.5483 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7589 - val_loss: 0.5507 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7669 - val_loss: 0.5566 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7745 - val_loss: 0.5557 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4593 - accuracy: 0.7834
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4591 - accuracy: 0.7833 - val_loss: 0.5675 - val_accuracy: 0.7134 - lr: 0.0010
253/253 [==============================] - 0s 760us/step
Independent Testing Matthews Correlation:  0.430457313400796
Confusion Matrix :
 [[3073  974]
 [1338 2709]]
Accuracy on test set:    0.7143563133185076
Sensitivity:    0.6693847294292068 	 Specificity:    0.7593278972078082
Precision  : 0.7355416779799077
Area Under Curve:    0.7143563133185076
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5927 - accuracy: 0.6783 - val_loss: 0.5549 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7215 - val_loss: 0.5490 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7308 - val_loss: 0.5492 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7418 - val_loss: 0.5456 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7472 - val_loss: 0.5475 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7550 - val_loss: 0.5510 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7631 - val_loss: 0.5499 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7734 - val_loss: 0.5562 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4620 - accuracy: 0.7802
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4622 - accuracy: 0.7798 - val_loss: 0.5530 - val_accuracy: 0.7132 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41844270508294407
Confusion Matrix :
 [[2916 1131]
 [1223 2824]]
Accuracy on test set:    0.7091672844082036
Sensitivity:    0.6978008401284902 	 Specificity:    0.720533728687917
Precision  : 0.7140328697850822
Area Under Curve:    0.7091672844082035
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5862 - accuracy: 0.6852 - val_loss: 0.5574 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7233 - val_loss: 0.5507 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7337 - val_loss: 0.5463 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7406 - val_loss: 0.5442 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7495 - val_loss: 0.5482 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4980 - accuracy: 0.7573 - val_loss: 0.5470 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.7654 - val_loss: 0.5589 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4764 - accuracy: 0.7719 - val_loss: 0.5587 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4640 - accuracy: 0.7812
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4640 - accuracy: 0.7812 - val_loss: 0.5557 - val_accuracy: 0.7150 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4445390240965332
Confusion Matrix :
 [[2908 1139]
 [1109 2938]]
Accuracy on test set:    0.7222634049913517
Sensitivity:    0.7259698542129973 	 Specificity:    0.7185569557697059
Precision  : 0.7206279126808928
Area Under Curve:    0.7222634049913517
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5889 - accuracy: 0.6828 - val_loss: 0.5542 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7226 - val_loss: 0.5528 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7331 - val_loss: 0.5472 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7428 - val_loss: 0.5432 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7488 - val_loss: 0.5449 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7597 - val_loss: 0.5513 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4801 - accuracy: 0.7692 - val_loss: 0.5509 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4683 - accuracy: 0.7771 - val_loss: 0.5566 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4553 - accuracy: 0.7849
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4553 - accuracy: 0.7847 - val_loss: 0.5606 - val_accuracy: 0.7090 - lr: 0.0010
253/253 [==============================] - 0s 892us/step
Independent Testing Matthews Correlation:  0.45921656923376614
Confusion Matrix :
 [[2997 1050]
 [1139 2908]]
Accuracy on test set:    0.7295527551272547
Sensitivity:    0.7185569557697059 	 Specificity:    0.7405485544848036
Precision  : 0.7347145022738757
Area Under Curve:    0.7295527551272549
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5955 - accuracy: 0.6780 - val_loss: 0.5552 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5516 - accuracy: 0.7174 - val_loss: 0.5499 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5369 - accuracy: 0.7297 - val_loss: 0.5527 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5243 - accuracy: 0.7375 - val_loss: 0.5514 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7439 - val_loss: 0.5491 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 6/400
244/257 [===========================>..] - ETA: 0s - loss: 0.5054 - accuracy: 0.7532
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7531 - val_loss: 0.5501 - val_accuracy: 0.7142 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4781449137118625
Confusion Matrix :
 [[3182  865]
 [1256 2791]]
Accuracy on test set:    0.7379540400296516
Sensitivity:    0.6896466518408698 	 Specificity:    0.7862614282184334
Precision  : 0.763402625820569
Area Under Curve:    0.7379540400296516
(8094, 2560) (8094,)
Mean MCC = 0.4289 + 0.0239 and Mean AUC = 0.7138 + 0.0121
Mean Sensitivity = 0.7109 + 0.0317 and Mean Specificity = 0.7167 + 0.0458 and Mean Accuracy = 0.7138 + 0.0121
Mean Precision = 0.7168 + 0.0250





Seed   : 698305
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5912 - accuracy: 0.6802 - val_loss: 0.5648 - val_accuracy: 0.7020 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7250 - val_loss: 0.5497 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7349 - val_loss: 0.5503 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7419 - val_loss: 0.5463 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7495 - val_loss: 0.5514 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7571 - val_loss: 0.5498 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7653 - val_loss: 0.5517 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4728 - accuracy: 0.7732 - val_loss: 0.5615 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 9/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4613 - accuracy: 0.7821
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4620 - accuracy: 0.7820 - val_loss: 0.5568 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 998us/step
Independent Testing Matthews Correlation:  0.4087790860336144
Confusion Matrix :
 [[2839 1209]
 [1184 2863]]
Accuracy on test set:    0.7043854231006794
Sensitivity:    0.707437608104769 	 Specificity:    0.7013339920948617
Precision  : 0.7030943025540275
Area Under Curve:    0.7043858000998151
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5871 - accuracy: 0.6832 - val_loss: 0.5568 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7226 - val_loss: 0.5538 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7354 - val_loss: 0.5497 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5148 - accuracy: 0.7444 - val_loss: 0.5454 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5028 - accuracy: 0.7532 - val_loss: 0.5559 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4887 - accuracy: 0.7617 - val_loss: 0.5500 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4762 - accuracy: 0.7703 - val_loss: 0.5484 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4609 - accuracy: 0.7817 - val_loss: 0.5547 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4499 - accuracy: 0.7871 - val_loss: 0.5591 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4365 - accuracy: 0.7966 - val_loss: 0.5571 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4235 - accuracy: 0.8062 - val_loss: 0.5743 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 12/400
254/257 [============================>.] - ETA: 0s - loss: 0.4099 - accuracy: 0.8125
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4098 - accuracy: 0.8126 - val_loss: 0.5818 - val_accuracy: 0.7087 - lr: 0.0010
253/253 [==============================] - 0s 693us/step
Independent Testing Matthews Correlation:  0.4384487828721917
Confusion Matrix :
 [[2560 1488]
 [ 810 3237]]
Accuracy on test set:    0.7161210623841878
Sensitivity:    0.7998517420311342 	 Specificity:    0.6324110671936759
Precision  : 0.6850793650793651
Area Under Curve:    0.7161314046124051
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5868 - accuracy: 0.6845 - val_loss: 0.5478 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7227 - val_loss: 0.5439 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7325 - val_loss: 0.5391 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7423 - val_loss: 0.5446 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7511 - val_loss: 0.5422 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4928 - accuracy: 0.7601 - val_loss: 0.5427 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7673 - val_loss: 0.5429 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4679 - accuracy: 0.7762 - val_loss: 0.5511 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4548 - accuracy: 0.7836 - val_loss: 0.5593 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4428 - accuracy: 0.7916
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4428 - accuracy: 0.7916 - val_loss: 0.5577 - val_accuracy: 0.7202 - lr: 0.0010
253/253 [==============================] - 0s 987us/step
Independent Testing Matthews Correlation:  0.4259420392901404
Confusion Matrix :
 [[2668 1379]
 [ 954 3094]]
Accuracy on test set:    0.7117974058060531
Sensitivity:    0.7643280632411067 	 Specificity:    0.6592537682233753
Precision  : 0.6917057902973396
Area Under Curve:    0.7117909157322411
(8095, 2560) (8095,)
Epoch 1/400

257/257 [==============================] - 2s 4ms/step - loss: 0.5836 - accuracy: 0.6868 - val_loss: 0.5492 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5395 - accuracy: 0.7258 - val_loss: 0.5461 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5250 - accuracy: 0.7362 - val_loss: 0.5382 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.7439 - val_loss: 0.5433 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4995 - accuracy: 0.7538 - val_loss: 0.5400 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4867 - accuracy: 0.7645 - val_loss: 0.5430 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7742 - val_loss: 0.5516 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4619 - accuracy: 0.7818 - val_loss: 0.5471 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4488 - accuracy: 0.7912 - val_loss: 0.5531 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4339 - accuracy: 0.7997 - val_loss: 0.5527 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4237 - accuracy: 0.8064 - val_loss: 0.5640 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4088 - accuracy: 0.8151 - val_loss: 0.5714 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3946 - accuracy: 0.8238 - val_loss: 0.5752 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 14/400
246/257 [===========================>..] - ETA: 0s - loss: 0.3832 - accuracy: 0.8282
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3830 - accuracy: 0.8282 - val_loss: 0.5856 - val_accuracy: 0.7222 - lr: 0.0010
253/253 [==============================] - 0s 917us/step
Independent Testing Matthews Correlation:  0.4159386371906584
Confusion Matrix :
 [[2794 1253]
 [1112 2936]]
Accuracy on test set:    0.7078443483631871
Sensitivity:    0.7252964426877471 	 Specificity:    0.6903879416851989
Precision  : 0.7008832656958701
Area Under Curve:    0.707842192186473
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5850 - accuracy: 0.6873 - val_loss: 0.5517 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7250 - val_loss: 0.5422 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.7352 - val_loss: 0.5408 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7412 - val_loss: 0.5443 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7504 - val_loss: 0.5431 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4954 - accuracy: 0.7562 - val_loss: 0.5492 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4822 - accuracy: 0.7661
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7662 - val_loss: 0.5447 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 888us/step
Independent Testing Matthews Correlation:  0.4102155597391212
Confusion Matrix :
 [[2827 1220]
 [1167 2880]]
Accuracy on test set:    0.7050901902643933
Sensitivity:    0.7116382505559674 	 Specificity:    0.6985421299728194
Precision  : 0.7024390243902439
Area Under Curve:    0.7050901902643933
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5866 - accuracy: 0.6851 - val_loss: 0.5546 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7227 - val_loss: 0.5471 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7341 - val_loss: 0.5410 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7418 - val_loss: 0.5385 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7503 - val_loss: 0.5463 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7583 - val_loss: 0.5443 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7657 - val_loss: 0.5436 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4750 - accuracy: 0.7722
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4750 - accuracy: 0.7722 - val_loss: 0.5458 - val_accuracy: 0.7240 - lr: 0.0010
253/253 [==============================] - 0s 811us/step
Independent Testing Matthews Correlation:  0.41747065667216116
Confusion Matrix :
 [[2674 1373]
 [ 992 3055]]
Accuracy on test set:    0.7078082530269335
Sensitivity:    0.7548801581418334 	 Specificity:    0.6607363479120336
Precision  : 0.6899277326106594
Area Under Curve:    0.7078082530269335
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5864 - accuracy: 0.6851 - val_loss: 0.5504 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7238 - val_loss: 0.5519 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7334 - val_loss: 0.5431 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7412 - val_loss: 0.5389 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7509 - val_loss: 0.5386 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4954 - accuracy: 0.7572 - val_loss: 0.5455 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7670 - val_loss: 0.5437 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7740 - val_loss: 0.5415 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4568 - accuracy: 0.7841 - val_loss: 0.5551 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4444 - accuracy: 0.7930
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4445 - accuracy: 0.7930 - val_loss: 0.5606 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 819us/step
Independent Testing Matthews Correlation:  0.4288015152188833
Confusion Matrix :
 [[2597 1450]
 [ 879 3168]]
Accuracy on test set:    0.7122559920929084
Sensitivity:    0.7828020756115641 	 Specificity:    0.6417099085742526
Precision  : 0.686011260285838
Area Under Curve:    0.7122559920929084
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5870 - accuracy: 0.6841 - val_loss: 0.5489 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7224 - val_loss: 0.5422 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7329 - val_loss: 0.5379 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7415 - val_loss: 0.5348 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7487 - val_loss: 0.5378 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7573 - val_loss: 0.5368 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7667 - val_loss: 0.5387 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7732 - val_loss: 0.5383 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4594 - accuracy: 0.7823 - val_loss: 0.5462 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4489 - accuracy: 0.7907 - val_loss: 0.5488 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4353 - accuracy: 0.7991 - val_loss: 0.5551 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4209 - accuracy: 0.8065
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4212 - accuracy: 0.8064 - val_loss: 0.5624 - val_accuracy: 0.7274 - lr: 0.0010
253/253 [==============================] - 0s 926us/step
Independent Testing Matthews Correlation:  0.42906820773458937
Confusion Matrix :
 [[2937 1110]
 [1201 2846]]
Accuracy on test set:    0.7144798616258957
Sensitivity:    0.7032369656535705 	 Specificity:    0.7257227575982209
Precision  : 0.7194135490394338
Area Under Curve:    0.7144798616258957
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5935 - accuracy: 0.6807 - val_loss: 0.5489 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7204 - val_loss: 0.5384 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7332 - val_loss: 0.5406 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7400 - val_loss: 0.5386 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7498 - val_loss: 0.5386 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7563 - val_loss: 0.5376 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
252/257 [============================>.] - ETA: 0s - loss: 0.4832 - accuracy: 0.7675
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7676 - val_loss: 0.5397 - val_accuracy: 0.7240 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4586197030624078
Confusion Matrix :
 [[3124  923]
 [1275 2772]]
Accuracy on test set:    0.7284408203607611
Sensitivity:    0.6849518161601186 	 Specificity:    0.7719298245614035
Precision  : 0.7502029769959404
Area Under Curve:    0.7284408203607609
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5947 - accuracy: 0.6791 - val_loss: 0.5513 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5511 - accuracy: 0.7186 - val_loss: 0.5437 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5358 - accuracy: 0.7297 - val_loss: 0.5413 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5249 - accuracy: 0.7378 - val_loss: 0.5403 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5146 - accuracy: 0.7452 - val_loss: 0.5406 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7516 - val_loss: 0.5445 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7591 - val_loss: 0.5437 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7666 - val_loss: 0.5443 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4708 - accuracy: 0.7782 - val_loss: 0.5454 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4589 - accuracy: 0.7835 - val_loss: 0.5564 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - ETA: 0s - loss: 0.4469 - accuracy: 0.7906
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4469 - accuracy: 0.7906 - val_loss: 0.5570 - val_accuracy: 0.7220 - lr: 0.0010
253/253 [==============================] - 0s 915us/step
Independent Testing Matthews Correlation:  0.4765958869994178
Confusion Matrix :
 [[3074  973]
 [1147 2900]]
Accuracy on test set:    0.7380775883370397
Sensitivity:    0.7165801828514949 	 Specificity:    0.7595749938225846
Precision  : 0.7487735605473793
Area Under Curve:    0.7380775883370397
(8094, 2560) (8094,)
Mean MCC = 0.4310 + 0.0207 and Mean AUC = 0.7146 + 0.0102
Mean Sensitivity = 0.7351 + 0.0361 and Mean Specificity = 0.6942 + 0.0451 and Mean Accuracy = 0.7146 + 0.0102
Mean Precision = 0.7078 + 0.0230





Seed   : 739274
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6851 - val_loss: 0.5640 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7241 - val_loss: 0.5565 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5265 - accuracy: 0.7359 - val_loss: 0.5515 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7430 - val_loss: 0.5578 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7533 - val_loss: 0.5522 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.7616 - val_loss: 0.5582 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.7704 - val_loss: 0.5604 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4651 - accuracy: 0.7781
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4649 - accuracy: 0.7783 - val_loss: 0.5571 - val_accuracy: 0.7127 - lr: 0.0010
253/253 [==============================] - 0s 740us/step
Independent Testing Matthews Correlation:  0.400488444871217
Confusion Matrix :
 [[2748 1300]
 [1128 2919]]
Accuracy on test set:    0.7000617665225448
Sensitivity:    0.7212750185322461 	 Specificity:    0.6788537549407114
Precision  : 0.6918701114008059
Area Under Curve:    0.7000643867364787
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5867 - accuracy: 0.6869 - val_loss: 0.5584 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7260 - val_loss: 0.5536 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7348 - val_loss: 0.5501 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7416 - val_loss: 0.5490 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7498 - val_loss: 0.5581 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7587 - val_loss: 0.5499 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4827 - accuracy: 0.7660 - val_loss: 0.5533 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.7734 - val_loss: 0.5653 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4577 - accuracy: 0.7844 - val_loss: 0.5619 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4456 - accuracy: 0.7920 - val_loss: 0.5804 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 11/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4319 - accuracy: 0.7991
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4320 - accuracy: 0.7988 - val_loss: 0.5789 - val_accuracy: 0.7082 - lr: 0.0010
253/253 [==============================] - 0s 779us/step
Independent Testing Matthews Correlation:  0.4198908692949981
Confusion Matrix :
 [[2868 1180]
 [1168 2879]]
Accuracy on test set:    0.7099444101297097
Sensitivity:    0.711391153941191 	 Specificity:    0.708498023715415
Precision  : 0.7092880019709288
Area Under Curve:    0.709944588828303
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5845 - accuracy: 0.6854 - val_loss: 0.5505 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5432 - accuracy: 0.7242 - val_loss: 0.5413 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7356 - val_loss: 0.5407 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7437 - val_loss: 0.5370 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5038 - accuracy: 0.7509 - val_loss: 0.5392 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7588 - val_loss: 0.5433 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7672 - val_loss: 0.5487 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4733 - accuracy: 0.7751 - val_loss: 0.5431 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4565 - accuracy: 0.7849 - val_loss: 0.5482 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4439 - accuracy: 0.7952
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4439 - accuracy: 0.7952 - val_loss: 0.5481 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 696us/step
Independent Testing Matthews Correlation:  0.42244473097972335
Confusion Matrix :
 [[2837 1210]
 [1128 2920]]
Accuracy on test set:    0.7111797405806053
Sensitivity:    0.7213438735177866 	 Specificity:    0.7010130961205832
Precision  : 0.7070217917675545
Area Under Curve:    0.7111784848191849
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5877 - accuracy: 0.6830 - val_loss: 0.5476 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7212 - val_loss: 0.5449 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7328 - val_loss: 0.5376 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7411 - val_loss: 0.5386 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7475 - val_loss: 0.5427 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7570 - val_loss: 0.5416 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4858 - accuracy: 0.7651 - val_loss: 0.5452 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4725 - accuracy: 0.7740 - val_loss: 0.5458 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4589 - accuracy: 0.7821
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4589 - accuracy: 0.7821 - val_loss: 0.5485 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44119760573300404
Confusion Matrix :
 [[2882 1165]
 [1097 2951]]
Accuracy on test set:    0.720568252007412
Sensitivity:    0.729001976284585 	 Specificity:    0.7121324437855201
Precision  : 0.716958211856171
Area Under Curve:    0.7205672100350525
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5866 - accuracy: 0.6846 - val_loss: 0.5640 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7220 - val_loss: 0.5481 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7308 - val_loss: 0.5429 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7408 - val_loss: 0.5435 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7474 - val_loss: 0.5468 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7560 - val_loss: 0.5463 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.7636 - val_loss: 0.5527 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4742 - accuracy: 0.7731
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7728 - val_loss: 0.5550 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4328398415197268
Confusion Matrix :
 [[2766 1281]
 [1018 3029]]
Accuracy on test set:    0.715962441314554
Sensitivity:    0.7484556461576476 	 Specificity:    0.6834692364714603
Precision  : 0.702784222737819
Area Under Curve:    0.715962441314554
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5919 - accuracy: 0.6805 - val_loss: 0.5535 - val_accuracy: 0.7248 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7230 - val_loss: 0.5442 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7316 - val_loss: 0.5440 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7418 - val_loss: 0.5430 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7477 - val_loss: 0.5465 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7574 - val_loss: 0.5494 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4847 - accuracy: 0.7649
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7641 - val_loss: 0.5462 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 0s 834us/step
Independent Testing Matthews Correlation:  0.4221239513792616
Confusion Matrix :
 [[2797 1250]
 [1090 2957]]
Accuracy on test set:    0.7108969607116382
Sensitivity:    0.7306646898937484 	 Specificity:    0.6911292315295281
Precision  : 0.7028761587829807
Area Under Curve:    0.7108969607116383
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6816 - val_loss: 0.5544 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7233 - val_loss: 0.5435 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7325 - val_loss: 0.5436 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7421 - val_loss: 0.5423 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5023 - accuracy: 0.7518 - val_loss: 0.5429 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7604 - val_loss: 0.5445 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4786 - accuracy: 0.7696
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4788 - accuracy: 0.7693 - val_loss: 0.5453 - val_accuracy: 0.7224 - lr: 0.0010
253/253 [==============================] - 0s 826us/step
Independent Testing Matthews Correlation:  0.4297690333232141
Confusion Matrix :
 [[2929 1118]
 [1190 2857]]
Accuracy on test set:    0.7148505065480603
Sensitivity:    0.7059550284161107 	 Specificity:    0.7237459846800098
Precision  : 0.7187421383647798
Area Under Curve:    0.7148505065480603
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5923 - accuracy: 0.6805 - val_loss: 0.5550 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5481 - accuracy: 0.7201 - val_loss: 0.5430 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5331 - accuracy: 0.7319 - val_loss: 0.5499 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7404 - val_loss: 0.5451 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7491 - val_loss: 0.5465 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4987 - accuracy: 0.7556 - val_loss: 0.5457 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7627 - val_loss: 0.5476 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4759 - accuracy: 0.7724 - val_loss: 0.5546 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4613 - accuracy: 0.7827
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4613 - accuracy: 0.7825 - val_loss: 0.5562 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.4255552633061312
Confusion Matrix :
 [[2852 1195]
 [1130 2917]]
Accuracy on test set:    0.712750185322461
Sensitivity:    0.7207808253026934 	 Specificity:    0.7047195453422288
Precision  : 0.709387159533074
Area Under Curve:    0.712750185322461
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5874 - accuracy: 0.6845 - val_loss: 0.5548 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7232 - val_loss: 0.5461 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7325 - val_loss: 0.5464 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7425 - val_loss: 0.5510 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7496 - val_loss: 0.5560 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7571 - val_loss: 0.5538 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7662 - val_loss: 0.5567 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4696 - accuracy: 0.7757
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4695 - accuracy: 0.7759 - val_loss: 0.5613 - val_accuracy: 0.7108 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4593611605338635
Confusion Matrix :
 [[2885 1162]
 [1027 3020]]
Accuracy on test set:    0.7295527551272547
Sensitivity:    0.7462317766246602 	 Specificity:    0.7128737336298493
Precision  : 0.7221425155428025
Area Under Curve:    0.7295527551272548
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5935 - accuracy: 0.6811 - val_loss: 0.5573 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7191 - val_loss: 0.5522 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5368 - accuracy: 0.7297 - val_loss: 0.5488 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5258 - accuracy: 0.7357 - val_loss: 0.5478 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5141 - accuracy: 0.7439 - val_loss: 0.5607 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7527 - val_loss: 0.5487 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.7605 - val_loss: 0.5530 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7681 - val_loss: 0.5562 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4678 - accuracy: 0.7765 - val_loss: 0.5601 - val_accuracy: 0.7163 - lr: 0.0010

Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4557 - accuracy: 0.7857 - val_loss: 0.5647 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4416 - accuracy: 0.7937
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7934 - val_loss: 0.5717 - val_accuracy: 0.7117 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46813951189682
Confusion Matrix :
 [[3093  954]
 [1202 2845]]
Accuracy on test set:    0.733629849271065
Sensitivity:    0.7029898690387941 	 Specificity:    0.7642698295033358
Precision  : 0.7488812845485654
Area Under Curve:    0.7336298492710649
(8094, 2560) (8094,)
Mean MCC = 0.4322 + 0.0187 and Mean AUC = 0.7159 + 0.0093
Mean Sensitivity = 0.7238 + 0.0145 and Mean Specificity = 0.7081 + 0.0229 and Mean Accuracy = 0.7159 + 0.0093
Mean Precision = 0.7130 + 0.0146





Seed   : 290449
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5846 - accuracy: 0.6855 - val_loss: 0.5586 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7237 - val_loss: 0.5505 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7333 - val_loss: 0.5487 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7417 - val_loss: 0.5568 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7501 - val_loss: 0.5570 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7586 - val_loss: 0.5564 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4820 - accuracy: 0.7659
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7666 - val_loss: 0.5575 - val_accuracy: 0.7121 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41643045051057787
Confusion Matrix :
 [[2864 1184]
 [1178 2869]]
Accuracy on test set:    0.7082149474984558
Sensitivity:    0.7089201877934272 	 Specificity:    0.7075098814229249
Precision  : 0.7078707130520602
Area Under Curve:    0.7082150346081761
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5879 - accuracy: 0.6851 - val_loss: 0.5566 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7221 - val_loss: 0.5478 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5268 - accuracy: 0.7368 - val_loss: 0.5475 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.7453 - val_loss: 0.5585 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.7547 - val_loss: 0.5477 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4887 - accuracy: 0.7632 - val_loss: 0.5514 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7685 - val_loss: 0.5557 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7777 - val_loss: 0.5581 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4519 - accuracy: 0.7867 - val_loss: 0.5567 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4404 - accuracy: 0.7934 - val_loss: 0.5664 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4257 - accuracy: 0.8035 - val_loss: 0.5722 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 12/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4168 - accuracy: 0.8094
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4166 - accuracy: 0.8096 - val_loss: 0.5773 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40013099765292726
Confusion Matrix :
 [[2822 1226]
 [1202 2845]]
Accuracy on test set:    0.7000617665225448
Sensitivity:    0.7029898690387941 	 Specificity:    0.6971343873517787
Precision  : 0.6988454925079833
Area Under Curve:    0.7000621281952865
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5862 - accuracy: 0.6850 - val_loss: 0.5467 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7226 - val_loss: 0.5398 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7348 - val_loss: 0.5462 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7429 - val_loss: 0.5397 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7509 - val_loss: 0.5430 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7600 - val_loss: 0.5515 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4794 - accuracy: 0.7692
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4802 - accuracy: 0.7686 - val_loss: 0.5418 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 708us/step
Independent Testing Matthews Correlation:  0.4133485480876355
Confusion Matrix :
 [[2910 1137]
 [1238 2810]]
Accuracy on test set:    0.7066090179122916
Sensitivity:    0.6941699604743083 	 Specificity:    0.7190511489992587
Precision  : 0.711933113757284
Area Under Curve:    0.7066105547367836
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5842 - accuracy: 0.6875 - val_loss: 0.5453 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7236 - val_loss: 0.5404 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7337 - val_loss: 0.5356 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7429 - val_loss: 0.5370 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7514 - val_loss: 0.5368 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4923 - accuracy: 0.7589 - val_loss: 0.5408 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7684 - val_loss: 0.5527 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4670 - accuracy: 0.7753
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7753 - val_loss: 0.5438 - val_accuracy: 0.7248 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42375799535926373
Confusion Matrix :
 [[2824 1223]
 [1110 2938]]
Accuracy on test set:    0.7117974058060531
Sensitivity:    0.7257905138339921 	 Specificity:    0.6978008401284902
Precision  : 0.7060802691660658
Area Under Curve:    0.7117956769812412
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5939 - accuracy: 0.6788 - val_loss: 0.5527 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7209 - val_loss: 0.5439 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5327 - accuracy: 0.7308 - val_loss: 0.5422 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7389 - val_loss: 0.5423 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7460 - val_loss: 0.5426 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7542 - val_loss: 0.5445 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7640 - val_loss: 0.5457 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4717 - accuracy: 0.7739
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7732 - val_loss: 0.5496 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 891us/step
Independent Testing Matthews Correlation:  0.4281627537070093
Confusion Matrix :
 [[2950 1097]
 [1218 2829]]
Accuracy on test set:    0.7139856683963429
Sensitivity:    0.6990363232023721 	 Specificity:    0.7289350135903138
Precision  : 0.7205807437595517
Area Under Curve:    0.7139856683963429
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5872 - accuracy: 0.6846 - val_loss: 0.5640 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7216 - val_loss: 0.5473 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7348 - val_loss: 0.5455 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7423 - val_loss: 0.5433 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7502 - val_loss: 0.5467 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7595 - val_loss: 0.5454 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7676 - val_loss: 0.5472 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4702 - accuracy: 0.7756 - val_loss: 0.5492 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4546 - accuracy: 0.7862 - val_loss: 0.5546 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4417 - accuracy: 0.7943
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7940 - val_loss: 0.5594 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 763us/step
Independent Testing Matthews Correlation:  0.42204566931970966
Confusion Matrix :
 [[2868 1179]
 [1160 2887]]
Accuracy on test set:    0.7110205090190265
Sensitivity:    0.713367926859402 	 Specificity:    0.7086730911786508
Precision  : 0.7100344318740777
Area Under Curve:    0.7110205090190265
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5923 - accuracy: 0.6817 - val_loss: 0.5524 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7219 - val_loss: 0.5407 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7316 - val_loss: 0.5381 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7398 - val_loss: 0.5371 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7492 - val_loss: 0.5391 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7579 - val_loss: 0.5479 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 7/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4801 - accuracy: 0.7683
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4802 - accuracy: 0.7682 - val_loss: 0.5527 - val_accuracy: 0.7248 - lr: 0.0010
253/253 [==============================] - 0s 776us/step
Independent Testing Matthews Correlation:  0.42322044497091627
Confusion Matrix :
 [[2711 1336]
 [1004 3043]]
Accuracy on test set:    0.7108969607116382
Sensitivity:    0.751914998764517 	 Specificity:    0.6698789226587596
Precision  : 0.6949075131308518
Area Under Curve:    0.7108969607116383
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5891 - accuracy: 0.6848 - val_loss: 0.5489 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7228 - val_loss: 0.5416 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7331 - val_loss: 0.5386 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7417 - val_loss: 0.5388 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7511 - val_loss: 0.5428 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7596 - val_loss: 0.5484 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4826 - accuracy: 0.7658
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4827 - accuracy: 0.7657 - val_loss: 0.5425 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4408420568289953
Confusion Matrix :
 [[3033 1014]
 [1252 2795]]
Accuracy on test set:    0.7200395354583642
Sensitivity:    0.6906350382999753 	 Specificity:    0.7494440326167532
Precision  : 0.7337883959044369
Area Under Curve:    0.7200395354583642
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5923 - accuracy: 0.6791 - val_loss: 0.5564 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5498 - accuracy: 0.7193 - val_loss: 0.5459 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5364 - accuracy: 0.7292 - val_loss: 0.5439 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5240 - accuracy: 0.7370 - val_loss: 0.5414 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400

257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7420 - val_loss: 0.5488 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7527 - val_loss: 0.5440 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4928 - accuracy: 0.7595 - val_loss: 0.5430 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7680 - val_loss: 0.5510 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 3ms/step - loss: 0.4688 - accuracy: 0.7779 - val_loss: 0.5525 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4535 - accuracy: 0.7860 - val_loss: 0.5573 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 11/400
252/257 [============================>.] - ETA: 0s - loss: 0.4405 - accuracy: 0.7955
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4403 - accuracy: 0.7956 - val_loss: 0.5752 - val_accuracy: 0.7113 - lr: 0.0010
253/253 [==============================] - 0s 849us/step
Independent Testing Matthews Correlation:  0.44702124305602076
Confusion Matrix :
 [[3302  745]
 [1527 2520]]
Accuracy on test set:    0.7192982456140351
Sensitivity:    0.6226834692364714 	 Specificity:    0.8159130219915988
Precision  : 0.7718223583460949
Area Under Curve:    0.719298245614035
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5911 - accuracy: 0.6807 - val_loss: 0.5592 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5511 - accuracy: 0.7182 - val_loss: 0.5535 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5364 - accuracy: 0.7284 - val_loss: 0.5461 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5245 - accuracy: 0.7381 - val_loss: 0.5426 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5133 - accuracy: 0.7455 - val_loss: 0.5432 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7530 - val_loss: 0.5417 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4911 - accuracy: 0.7623 - val_loss: 0.5525 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7708 - val_loss: 0.5453 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4652 - accuracy: 0.7795 - val_loss: 0.5521 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4527 - accuracy: 0.7880 - val_loss: 0.5566 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4382 - accuracy: 0.7959 - val_loss: 0.5563 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4241 - accuracy: 0.8044 - val_loss: 0.5550 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 13/400
252/257 [============================>.] - ETA: 0s - loss: 0.4113 - accuracy: 0.8136
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4117 - accuracy: 0.8134 - val_loss: 0.5699 - val_accuracy: 0.7209 - lr: 0.0010
253/253 [==============================] - 0s 764us/step
Independent Testing Matthews Correlation:  0.4753734853686216
Confusion Matrix :
 [[3140  907]
 [1222 2825]]
Accuracy on test set:    0.7369656535705461
Sensitivity:    0.6980479367432666 	 Specificity:    0.7758833703978255
Precision  : 0.7569667738478028
Area Under Curve:    0.736965653570546
(8094, 2560) (8094,)
Mean MCC = 0.4290 + 0.0199 and Mean AUC = 0.7139 + 0.0095
Mean Sensitivity = 0.7008 + 0.0312 and Mean Specificity = 0.7270 + 0.0407 and Mean Accuracy = 0.7139 + 0.0095
Mean Precision = 0.7213 + 0.0241





Seed   : 208418
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5848 - accuracy: 0.6860 - val_loss: 0.5580 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5413 - accuracy: 0.7246 - val_loss: 0.5536 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5244 - accuracy: 0.7375 - val_loss: 0.5507 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.7452 - val_loss: 0.5515 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5021 - accuracy: 0.7522 - val_loss: 0.5491 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.7613 - val_loss: 0.5566 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4774 - accuracy: 0.7707 - val_loss: 0.5574 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4651 - accuracy: 0.7784 - val_loss: 0.5584 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4545 - accuracy: 0.7836 - val_loss: 0.5589 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4388 - accuracy: 0.7943 - val_loss: 0.5680 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 11/400
254/257 [============================>.] - ETA: 0s - loss: 0.4260 - accuracy: 0.8025
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4261 - accuracy: 0.8023 - val_loss: 0.5755 - val_accuracy: 0.7134 - lr: 0.0010
253/253 [==============================] - 0s 868us/step
Independent Testing Matthews Correlation:  0.4067973735644901
Confusion Matrix :
 [[2840 1208]
 [1193 2854]]
Accuracy on test set:    0.7033971587399629
Sensitivity:    0.7052137385717816 	 Specificity:    0.7015810276679841
Precision  : 0.7026095519448547
Area Under Curve:    0.7033973831198829
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6846 - val_loss: 0.5559 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7232 - val_loss: 0.5529 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7329 - val_loss: 0.5502 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7405 - val_loss: 0.5494 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7494 - val_loss: 0.5498 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7564 - val_loss: 0.5499 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4866 - accuracy: 0.7632 - val_loss: 0.5500 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.7710 - val_loss: 0.5566 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4636 - accuracy: 0.7800 - val_loss: 0.5617 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4513 - accuracy: 0.7878 - val_loss: 0.5607 - val_accuracy: 0.7131 - lr: 0.0010

Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4388 - accuracy: 0.7947 - val_loss: 0.5720 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4253 - accuracy: 0.8026 - val_loss: 0.5702 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - ETA: 0s - loss: 0.4151 - accuracy: 0.8113
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4151 - accuracy: 0.8113 - val_loss: 0.5820 - val_accuracy: 0.7097 - lr: 0.0010
253/253 [==============================] - 0s 724us/step
Independent Testing Matthews Correlation:  0.39609040276136626
Confusion Matrix :
 [[2708 1340]
 [1107 2940]]
Accuracy on test set:    0.6977146386658432
Sensitivity:    0.72646404744255 	 Specificity:    0.6689723320158103
Precision  : 0.6869158878504673
Area Under Curve:    0.6977181897291801
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5899 - accuracy: 0.6819 - val_loss: 0.5500 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7232 - val_loss: 0.5402 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7324 - val_loss: 0.5393 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7413 - val_loss: 0.5376 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7479 - val_loss: 0.5370 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7574 - val_loss: 0.5424 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7649 - val_loss: 0.5417 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4716 - accuracy: 0.7743
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7739 - val_loss: 0.5529 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40560698821807406
Confusion Matrix :
 [[2665 1382]
 [1030 3018]]
Accuracy on test set:    0.7020382952439778
Sensitivity:    0.7455533596837944 	 Specificity:    0.6585124783790463
Precision  : 0.6859090909090909
Area Under Curve:    0.7020329190314203
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5939 - accuracy: 0.6771 - val_loss: 0.5540 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5508 - accuracy: 0.7179 - val_loss: 0.5382 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7299 - val_loss: 0.5381 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5232 - accuracy: 0.7389 - val_loss: 0.5407 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5130 - accuracy: 0.7458 - val_loss: 0.5412 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5019 - accuracy: 0.7529 - val_loss: 0.5415 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - ETA: 0s - loss: 0.4900 - accuracy: 0.7604
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4900 - accuracy: 0.7604 - val_loss: 0.5421 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 901us/step
Independent Testing Matthews Correlation:  0.4251797500582035
Confusion Matrix :
 [[2692 1355]
 [ 979 3069]]
Accuracy on test set:    0.7116738727609636
Sensitivity:    0.7581521739130435 	 Specificity:    0.6651840869780083
Precision  : 0.6937160940325497
Area Under Curve:    0.7116681304455259
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5877 - accuracy: 0.6844 - val_loss: 0.5505 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7239 - val_loss: 0.5403 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7329 - val_loss: 0.5393 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7400 - val_loss: 0.5363 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7492 - val_loss: 0.5412 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7581 - val_loss: 0.5443 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7649 - val_loss: 0.5444 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4685 - accuracy: 0.7777 - val_loss: 0.5445 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4575 - accuracy: 0.7829
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4579 - accuracy: 0.7826 - val_loss: 0.5556 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 832us/step
Independent Testing Matthews Correlation:  0.41604239418177985
Confusion Matrix :
 [[2729 1318]
 [1049 2998]]
Accuracy on test set:    0.7075611564121571
Sensitivity:    0.7407956510995799 	 Specificity:    0.6743266617247343
Precision  : 0.6946246524559777
Area Under Curve:    0.7075611564121571
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5864 - accuracy: 0.6853 - val_loss: 0.5492 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7235 - val_loss: 0.5421 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7344 - val_loss: 0.5396 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.7441 - val_loss: 0.5414 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5021 - accuracy: 0.7520 - val_loss: 0.5457 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7599 - val_loss: 0.5441 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4779 - accuracy: 0.7705
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7700 - val_loss: 0.5460 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 876us/step
Independent Testing Matthews Correlation:  0.4317162194149008
Confusion Matrix :
 [[2924 1123]
 [1177 2870]]
Accuracy on test set:    0.7158388930071659
Sensitivity:    0.7091672844082036 	 Specificity:    0.722510501606128
Precision  : 0.7187578261958427
Area Under Curve:    0.7158388930071657
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5875 - accuracy: 0.6841 - val_loss: 0.5466 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7217 - val_loss: 0.5411 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7325 - val_loss: 0.5400 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5207 - accuracy: 0.7407 - val_loss: 0.5382 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7470 - val_loss: 0.5386 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4991 - accuracy: 0.7535 - val_loss: 0.5437 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7637 - val_loss: 0.5395 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4767 - accuracy: 0.7687
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.7687 - val_loss: 0.5496 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4351930755448466
Confusion Matrix :
 [[2828 1219]
 [1068 2979]]
Accuracy on test set:    0.7174450210032123
Sensitivity:    0.7361008154188288 	 Specificity:    0.6987892265875958
Precision  : 0.709623630300143
Area Under Curve:    0.7174450210032122
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5953 - accuracy: 0.6789 - val_loss: 0.5518 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5498 - accuracy: 0.7168 - val_loss: 0.5429 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7327 - val_loss: 0.5471 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7396 - val_loss: 0.5397 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5110 - accuracy: 0.7473 - val_loss: 0.5411 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5020 - accuracy: 0.7535 - val_loss: 0.5463 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4908 - accuracy: 0.7619
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4908 - accuracy: 0.7619 - val_loss: 0.5431 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 886us/step
Independent Testing Matthews Correlation:  0.4381365135357835
Confusion Matrix :
 [[2837 1210]
 [1065 2982]]
Accuracy on test set:    0.7189276006918706
Sensitivity:    0.7368421052631579 	 Specificity:    0.7010130961205832
Precision  : 0.711354961832061
Area Under Curve:    0.7189276006918706
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5917 - accuracy: 0.6813 - val_loss: 0.5528 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7224 - val_loss: 0.5451 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5339 - accuracy: 0.7325 - val_loss: 0.5456 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5234 - accuracy: 0.7391 - val_loss: 0.5437 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.7449 - val_loss: 0.5438 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7547 - val_loss: 0.5462 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.7619 - val_loss: 0.5500 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7707 - val_loss: 0.5483 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4654 - accuracy: 0.7797
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4655 - accuracy: 0.7799 - val_loss: 0.5529 - val_accuracy: 0.7172 - lr: 0.0010
253/253 [==============================] - 0s 746us/step
Independent Testing Matthews Correlation:  0.47402162992520935
Confusion Matrix :
 [[2943 1104]
 [1025 3022]]
Accuracy on test set:    0.7369656535705461
Sensitivity:    0.746725969854213 	 Specificity:    0.7272053372868792
Precision  : 0.7324285021812894
Area Under Curve:    0.7369656535705461
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5942 - accuracy: 0.6800 - val_loss: 0.5603 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5513 - accuracy: 0.7184 - val_loss: 0.5504 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5354 - accuracy: 0.7314 - val_loss: 0.5541 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5244 - accuracy: 0.7376 - val_loss: 0.5531 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5135 - accuracy: 0.7452 - val_loss: 0.5517 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5034 - accuracy: 0.7533 - val_loss: 0.5565 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4931 - accuracy: 0.7622
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7621 - val_loss: 0.5621 - val_accuracy: 0.7132 - lr: 0.0010
253/253 [==============================] - 0s 763us/step
Independent Testing Matthews Correlation:  0.4962507419264068
Confusion Matrix :
 [[2991 1056]
 [ 983 3064]]
Accuracy on test set:    0.748085001235483
Sensitivity:    0.7571040276748209 	 Specificity:    0.7390659747961453
Precision  : 0.7436893203883496
Area Under Curve:    0.7480850012354829
(8094, 2560) (8094,)
Mean MCC = 0.4325 + 0.0298 and Mean AUC = 0.7160 + 0.0150
Mean Sensitivity = 0.7362 + 0.0171 and Mean Specificity = 0.6957 + 0.0267 and Mean Accuracy = 0.7160 + 0.0150
Mean Precision = 0.7080 + 0.0183





Seed   : 510212
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5889 - accuracy: 0.6823 - val_loss: 0.5570 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7252 - val_loss: 0.5490 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5268 - accuracy: 0.7360 - val_loss: 0.5522 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5141 - accuracy: 0.7448 - val_loss: 0.5537 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5022 - accuracy: 0.7530 - val_loss: 0.5462 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4905 - accuracy: 0.7605 - val_loss: 0.5570 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4781 - accuracy: 0.7721
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7719 - val_loss: 0.5490 - val_accuracy: 0.7134 - lr: 0.0010

253/253 [==============================] - 0s 786us/step
Independent Testing Matthews Correlation:  0.40151205296162307
Confusion Matrix :
 [[2721 1327]
 [1098 2949]]
Accuracy on test set:    0.7004323656578134
Sensitivity:    0.7286879169755375 	 Specificity:    0.6721837944664032
Precision  : 0.6896632366697848
Area Under Curve:    0.7004358557209702
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5901 - accuracy: 0.6829 - val_loss: 0.5542 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7230 - val_loss: 0.5451 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7349 - val_loss: 0.5443 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7430 - val_loss: 0.5404 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7500 - val_loss: 0.5492 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7557 - val_loss: 0.5435 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 3ms/step - loss: 0.4834 - accuracy: 0.7662 - val_loss: 0.5456 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7743 - val_loss: 0.5519 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 9/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4575 - accuracy: 0.7839
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4579 - accuracy: 0.7839 - val_loss: 0.5495 - val_accuracy: 0.7175 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41569987529439034
Confusion Matrix :
 [[2851 1197]
 [1168 2879]]
Accuracy on test set:    0.7078443483631871
Sensitivity:    0.711391153941191 	 Specificity:    0.704298418972332
Precision  : 0.7063297350343474
Area Under Curve:    0.7078447864567615
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5888 - accuracy: 0.6839 - val_loss: 0.5505 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7233 - val_loss: 0.5409 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7324 - val_loss: 0.5442 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7413 - val_loss: 0.5373 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7476 - val_loss: 0.5379 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.7564 - val_loss: 0.5353 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7622 - val_loss: 0.5378 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7718 - val_loss: 0.5481 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4620 - accuracy: 0.7790 - val_loss: 0.5486 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4521 - accuracy: 0.7873 - val_loss: 0.5604 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4397 - accuracy: 0.7943 - val_loss: 0.5602 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4287 - accuracy: 0.8005 - val_loss: 0.5726 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 13/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4174 - accuracy: 0.8072
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4182 - accuracy: 0.8068 - val_loss: 0.5736 - val_accuracy: 0.7152 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.401972579205418
Confusion Matrix :
 [[2967 1080]
 [1344 2704]]
Accuracy on test set:    0.700555898702903
Sensitivity:    0.6679841897233202 	 Specificity:    0.7331356560415122
Precision  : 0.7145877378435518
Area Under Curve:    0.7005599228824162
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5865 - accuracy: 0.6840 - val_loss: 0.5513 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7240 - val_loss: 0.5389 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7336 - val_loss: 0.5361 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7411 - val_loss: 0.5341 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7464 - val_loss: 0.5363 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4985 - accuracy: 0.7561 - val_loss: 0.5360 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7640 - val_loss: 0.5379 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4764 - accuracy: 0.7713 - val_loss: 0.5417 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4663 - accuracy: 0.7799 - val_loss: 0.5444 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4521 - accuracy: 0.7878
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4521 - accuracy: 0.7878 - val_loss: 0.5484 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 833us/step
Independent Testing Matthews Correlation:  0.417159634432058
Confusion Matrix :
 [[2746 1301]
 [1061 2987]]
Accuracy on test set:    0.7082149474984558
Sensitivity:    0.7378952569169961 	 Specificity:    0.6785273041759328
Precision  : 0.6965951492537313
Area Under Curve:    0.7082112805464644
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5910 - accuracy: 0.6825 - val_loss: 0.5552 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7228 - val_loss: 0.5486 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7335 - val_loss: 0.5438 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7406 - val_loss: 0.5438 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7495 - val_loss: 0.5494 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7564 - val_loss: 0.5530 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.7664 - val_loss: 0.5531 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4695 - accuracy: 0.7756
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4697 - accuracy: 0.7751 - val_loss: 0.5572 - val_accuracy: 0.7146 - lr: 0.0010
253/253 [==============================] - 0s 751us/step
Independent Testing Matthews Correlation:  0.42878824233116963
Confusion Matrix :
 [[2853 1194]
 [1118 2929]]
Accuracy on test set:    0.7143563133185076
Sensitivity:    0.7237459846800098 	 Specificity:    0.7049666419570052
Precision  : 0.7104050448702401
Area Under Curve:    0.7143563133185075
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5853 - accuracy: 0.6843 - val_loss: 0.5514 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5422 - accuracy: 0.7231 - val_loss: 0.5452 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5263 - accuracy: 0.7364 - val_loss: 0.5475 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7433 - val_loss: 0.5452 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7517 - val_loss: 0.5459 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4928 - accuracy: 0.7593 - val_loss: 0.5482 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.7670 - val_loss: 0.5489 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4714 - accuracy: 0.7761 - val_loss: 0.5624 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4585 - accuracy: 0.7847 - val_loss: 0.5552 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4443 - accuracy: 0.7939
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4452 - accuracy: 0.7933 - val_loss: 0.5598 - val_accuracy: 0.7170 - lr: 0.0010
253/253 [==============================] - 0s 737us/step
Independent Testing Matthews Correlation:  0.4275135828706548
Confusion Matrix :
 [[2765 1282]
 [1038 3009]]
Accuracy on test set:    0.713367926859402
Sensitivity:    0.7435137138621201 	 Specificity:    0.683222139856684
Precision  : 0.7012351433232347
Area Under Curve:    0.7133679268594021
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6840 - val_loss: 0.5546 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7241 - val_loss: 0.5586 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7324 - val_loss: 0.5462 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7411 - val_loss: 0.5454 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7483 - val_loss: 0.5499 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7571 - val_loss: 0.5474 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7657 - val_loss: 0.5529 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4732 - accuracy: 0.7735
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4728 - accuracy: 0.7736 - val_loss: 0.5629 - val_accuracy: 0.7139 - lr: 0.0010
253/253 [==============================] - 0s 742us/step
Independent Testing Matthews Correlation:  0.4353219699078971
Confusion Matrix :
 [[2609 1438]
 [ 865 3182]]
Accuracy on test set:    0.7154682480850012
Sensitivity:    0.7862614282184334 	 Specificity:    0.644675067951569
Precision  : 0.6887445887445888
Area Under Curve:    0.7154682480850012
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5899 - accuracy: 0.6825 - val_loss: 0.5560 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7219 - val_loss: 0.5511 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7348 - val_loss: 0.5438 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7430 - val_loss: 0.5433 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7498 - val_loss: 0.5464 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7577 - val_loss: 0.5555 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7650 - val_loss: 0.5528 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4743 - accuracy: 0.7748
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7747 - val_loss: 0.5508 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 993us/step
Independent Testing Matthews Correlation:  0.4383842055804812
Confusion Matrix :
 [[2885 1162]
 [1111 2936]]
Accuracy on test set:    0.7191746973066468
Sensitivity:    0.7254756609834445 	 Specificity:    0.7128737336298493
Precision  : 0.716447047340166
Area Under Curve:    0.7191746973066468
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5865 - accuracy: 0.6864 - val_loss: 0.5532 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5480 - accuracy: 0.7213 - val_loss: 0.5551 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5326 - accuracy: 0.7308 - val_loss: 0.5464 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7407 - val_loss: 0.5463 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7481 - val_loss: 0.5519 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7579 - val_loss: 0.5496 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7661 - val_loss: 0.5542 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4744 - accuracy: 0.7713
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4748 - accuracy: 0.7710 - val_loss: 0.5582 - val_accuracy: 0.7157 - lr: 0.0010
253/253 [==============================] - 0s 798us/step
Independent Testing Matthews Correlation:  0.4627215102022495
Confusion Matrix :
 [[2832 1215]
 [ 963 3084]]
Accuracy on test set:    0.7309117865085248
Sensitivity:    0.7620459599703484 	 Specificity:    0.6997776130467013
Precision  : 0.7173761339846476
Area Under Curve:    0.7309117865085248
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5944 - accuracy: 0.6782 - val_loss: 0.5546 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5510 - accuracy: 0.7190 - val_loss: 0.5482 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5360 - accuracy: 0.7296 - val_loss: 0.5466 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5247 - accuracy: 0.7379 - val_loss: 0.5492 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5137 - accuracy: 0.7450 - val_loss: 0.5492 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5015 - accuracy: 0.7551 - val_loss: 0.5535 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7630 - val_loss: 0.5541 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4773 - accuracy: 0.7700 - val_loss: 0.5595 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4646 - accuracy: 0.7782 - val_loss: 0.5677 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4511 - accuracy: 0.7872
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4511 - accuracy: 0.7872 - val_loss: 0.5719 - val_accuracy: 0.7112 - lr: 0.0010
253/253 [==============================] - 0s 873us/step
Independent Testing Matthews Correlation:  0.4723125332582441
Confusion Matrix :
 [[3099  948]
 [1191 2856]]
Accuracy on test set:    0.7357301704966642
Sensitivity:    0.7057079318013343 	 Specificity:    0.765752409191994
Precision  : 0.750788643533123
Area Under Curve:    0.7357301704966641
(8094, 2560) (8094,)
Mean MCC = 0.4301 + 0.0222 and Mean AUC = 0.7146 + 0.0110
Mean Sensitivity = 0.7293 + 0.0305 and Mean Specificity = 0.6999 + 0.0319 and Mean Accuracy = 0.7146 + 0.0110
Mean Precision = 0.7092 + 0.0171





Seed   : 456525
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5880 - accuracy: 0.6851 - val_loss: 0.5622 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7249 - val_loss: 0.5577 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7351 - val_loss: 0.5535 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7428 - val_loss: 0.5541 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7505 - val_loss: 0.5536 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7572 - val_loss: 0.5591 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7629 - val_loss: 0.5648 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4736 - accuracy: 0.7720 - val_loss: 0.5572 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.7817 - val_loss: 0.5696 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 10/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4486 - accuracy: 0.7906
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4483 - accuracy: 0.7905 - val_loss: 0.5752 - val_accuracy: 0.7089 - lr: 0.0010
253/253 [==============================] - 0s 827us/step
Independent Testing Matthews Correlation:  0.4043420771762668
Confusion Matrix :
 [[2740 1308]
 [1105 2942]]
Accuracy on test set:    0.7019147621988882
Sensitivity:    0.7269582406721028 	 Specificity:    0.6768774703557312
Precision  : 0.6922352941176471
Area Under Curve:    0.701917855513917
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5935 - accuracy: 0.6790 - val_loss: 0.5682 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7238 - val_loss: 0.5595 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7327 - val_loss: 0.5564 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7442 - val_loss: 0.5626 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7509 - val_loss: 0.5624 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7586 - val_loss: 0.5566 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 7/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4820 - accuracy: 0.7687
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4825 - accuracy: 0.7686 - val_loss: 0.5596 - val_accuracy: 0.7050 - lr: 0.0010
253/253 [==============================] - 0s 946us/step
Independent Testing Matthews Correlation:  0.4144145199222064
Confusion Matrix :
 [[2927 1121]
 [1250 2797]]
Accuracy on test set:    0.7071031500926498
Sensitivity:    0.6911292315295281 	 Specificity:    0.7230731225296443
Precision  : 0.7138846350178663
Area Under Curve:    0.7071011770295862
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5897 - accuracy: 0.6820 - val_loss: 0.5567 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7224 - val_loss: 0.5490 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7335 - val_loss: 0.5450 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7399 - val_loss: 0.5472 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5105 - accuracy: 0.7475 - val_loss: 0.5431 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7552 - val_loss: 0.5477 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4906 - accuracy: 0.7625
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7625 - val_loss: 0.5529 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 821us/step
Independent Testing Matthews Correlation:  0.4259501769362605
Confusion Matrix :
 [[2736 1311]
 [1017 3031]]
Accuracy on test set:    0.7124150710315009
Sensitivity:    0.7487648221343873 	 Specificity:    0.676056338028169
Precision  : 0.6980654076462459
Area Under Curve:    0.7124105800812781
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5879 - accuracy: 0.6853 - val_loss: 0.5542 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7220 - val_loss: 0.5473 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7328 - val_loss: 0.5558 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7428 - val_loss: 0.5434 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400

257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7502 - val_loss: 0.5421 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7568 - val_loss: 0.5458 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.7649 - val_loss: 0.5459 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4733 - accuracy: 0.7734 - val_loss: 0.5505 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4588 - accuracy: 0.7820 - val_loss: 0.5550 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4472 - accuracy: 0.7912
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4477 - accuracy: 0.7908 - val_loss: 0.5567 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 944us/step
Independent Testing Matthews Correlation:  0.4259349267892313
Confusion Matrix :
 [[2932 1115]
 [1209 2839]]
Accuracy on test set:    0.7129092032118591
Sensitivity:    0.7013339920948617 	 Specificity:    0.724487274524339
Precision  : 0.71800708143652
Area Under Curve:    0.7129106333096004
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5910 - accuracy: 0.6824 - val_loss: 0.5478 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7213 - val_loss: 0.5393 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7306 - val_loss: 0.5379 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7406 - val_loss: 0.5373 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7468 - val_loss: 0.5369 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7562 - val_loss: 0.5364 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4859 - accuracy: 0.7644
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7654 - val_loss: 0.5421 - val_accuracy: 0.7271 - lr: 0.0010
253/253 [==============================] - 0s 817us/step
Independent Testing Matthews Correlation:  0.42229017458961465
Confusion Matrix :
 [[2947 1100]
 [1239 2808]]
Accuracy on test set:    0.7110205090190265
Sensitivity:    0.6938472942920682 	 Specificity:    0.7281937237459847
Precision  : 0.7185261003070624
Area Under Curve:    0.7110205090190264
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5886 - accuracy: 0.6861 - val_loss: 0.5453 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7194 - val_loss: 0.5382 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7328 - val_loss: 0.5399 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7417 - val_loss: 0.5365 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7511 - val_loss: 0.5361 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7581 - val_loss: 0.5439 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7652 - val_loss: 0.5438 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7740 - val_loss: 0.5439 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4600 - accuracy: 0.7825 - val_loss: 0.5589 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4474 - accuracy: 0.7906
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4478 - accuracy: 0.7902 - val_loss: 0.5628 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 696us/step
Independent Testing Matthews Correlation:  0.42158220918092937
Confusion Matrix :
 [[3031 1016]
 [1330 2717]]
Accuracy on test set:    0.7101556708673091
Sensitivity:    0.6713615023474179 	 Specificity:    0.7489498393872004
Precision  : 0.7278328422180552
Area Under Curve:    0.7101556708673092
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5876 - accuracy: 0.6841 - val_loss: 0.5446 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7222 - val_loss: 0.5385 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7331 - val_loss: 0.5372 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7422 - val_loss: 0.5355 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7496 - val_loss: 0.5364 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7576 - val_loss: 0.5432 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.7625 - val_loss: 0.5421 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4769 - accuracy: 0.7704 - val_loss: 0.5434 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4651 - accuracy: 0.7800
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7801 - val_loss: 0.5505 - val_accuracy: 0.7237 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43029777922281703
Confusion Matrix :
 [[2748 1299]
 [1011 3036]]
Accuracy on test set:    0.7146034099332839
Sensitivity:    0.7501853224610823 	 Specificity:    0.6790214974054856
Precision  : 0.7003460207612456
Area Under Curve:    0.714603409933284
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5907 - accuracy: 0.6801 - val_loss: 0.5542 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7217 - val_loss: 0.5370 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7313 - val_loss: 0.5316 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7404 - val_loss: 0.5317 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5116 - accuracy: 0.7454 - val_loss: 0.5340 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5003 - accuracy: 0.7545 - val_loss: 0.5400 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7606 - val_loss: 0.5367 - val_accuracy: 0.7260 - lr: 0.0010

Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7700 - val_loss: 0.5396 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4676 - accuracy: 0.7780 - val_loss: 0.5464 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4531 - accuracy: 0.7864 - val_loss: 0.5604 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4403 - accuracy: 0.7975 - val_loss: 0.5509 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4276 - accuracy: 0.8028 - val_loss: 0.5532 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4174 - accuracy: 0.8077 - val_loss: 0.5723 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4027 - accuracy: 0.8171 - val_loss: 0.5636 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3905 - accuracy: 0.8243 - val_loss: 0.5791 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3808 - accuracy: 0.8293 - val_loss: 0.5885 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 17/400
246/257 [===========================>..] - ETA: 0s - loss: 0.3690 - accuracy: 0.8365
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3697 - accuracy: 0.8361 - val_loss: 0.5883 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 817us/step
Independent Testing Matthews Correlation:  0.4164131748597508
Confusion Matrix :
 [[2899 1148]
 [1214 2833]]
Accuracy on test set:    0.708178897949098
Sensitivity:    0.7000247096614777 	 Specificity:    0.7163330862367185
Precision  : 0.7116302436573725
Area Under Curve:    0.708178897949098
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5964 - accuracy: 0.6772 - val_loss: 0.5486 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5516 - accuracy: 0.7189 - val_loss: 0.5400 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5352 - accuracy: 0.7301 - val_loss: 0.5377 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5240 - accuracy: 0.7378 - val_loss: 0.5424 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5119 - accuracy: 0.7465 - val_loss: 0.5350 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7539 - val_loss: 0.5386 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4880 - accuracy: 0.7626
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.7624 - val_loss: 0.5395 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 798us/step
Independent Testing Matthews Correlation:  0.4573979908793454
Confusion Matrix :
 [[3110  937]
 [1265 2782]]
Accuracy on test set:    0.7279466271312083
Sensitivity:    0.6874227823078823 	 Specificity:    0.7684704719545342
Precision  : 0.7480505512234472
Area Under Curve:    0.7279466271312083
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5966 - accuracy: 0.6778 - val_loss: 0.5523 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5515 - accuracy: 0.7193 - val_loss: 0.5403 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5355 - accuracy: 0.7302 - val_loss: 0.5372 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5240 - accuracy: 0.7382 - val_loss: 0.5361 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7479 - val_loss: 0.5374 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.7570 - val_loss: 0.5391 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.7646 - val_loss: 0.5377 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4710 - accuracy: 0.7748
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.7749 - val_loss: 0.5445 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4788736049175063
Confusion Matrix :
 [[2990 1057]
 [1052 2995]]
Accuracy on test set:    0.7394366197183099
Sensitivity:    0.7400543612552508 	 Specificity:    0.7388188781813689
Precision  : 0.7391411648568608
Area Under Curve:    0.7394366197183099
(8094, 2560) (8094,)
Mean MCC = 0.4297 + 0.0209 and Mean AUC = 0.7146 + 0.0105
Mean Sensitivity = 0.7111 + 0.0266 and Mean Specificity = 0.7180 + 0.0301 and Mean Accuracy = 0.7146 + 0.0105
Mean Precision = 0.7168 + 0.0169





Seed   : 864464
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5907 - accuracy: 0.6801 - val_loss: 0.5559 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7238 - val_loss: 0.5482 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7344 - val_loss: 0.5463 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7406 - val_loss: 0.5433 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7480 - val_loss: 0.5452 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7554 - val_loss: 0.5535 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4872 - accuracy: 0.7640 - val_loss: 0.5529 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4733 - accuracy: 0.7751 - val_loss: 0.5550 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4633 - accuracy: 0.7810
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4633 - accuracy: 0.7810 - val_loss: 0.5612 - val_accuracy: 0.7175 - lr: 0.0010
253/253 [==============================] - 0s 939us/step
Independent Testing Matthews Correlation:  0.4103569693039199
Confusion Matrix :
 [[2689 1359]
 [1033 3014]]
Accuracy on test set:    0.704508956145769
Sensitivity:    0.744749196936002 	 Specificity:    0.6642786561264822
Precision  : 0.6892293619940544
Area Under Curve:    0.704513926531242
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5889 - accuracy: 0.6841 - val_loss: 0.5558 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7230 - val_loss: 0.5558 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7332 - val_loss: 0.5473 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7399 - val_loss: 0.5452 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7478 - val_loss: 0.5476 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7568 - val_loss: 0.5505 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7650 - val_loss: 0.5486 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7740 - val_loss: 0.5577 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4633 - accuracy: 0.7793 - val_loss: 0.5565 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4514 - accuracy: 0.7872
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4515 - accuracy: 0.7871 - val_loss: 0.5814 - val_accuracy: 0.7156 - lr: 0.0010
253/253 [==============================] - 0s 827us/step
Independent Testing Matthews Correlation:  0.421345506251728
Confusion Matrix :
 [[2513 1535]
 [ 833 3214]]
Accuracy on test set:    0.7074737492279185
Sensitivity:    0.7941685198912775 	 Specificity:    0.620800395256917
Precision  : 0.6767740576963571
Area Under Curve:    0.7074844575740973
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5972 - accuracy: 0.6727 - val_loss: 0.5480 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7213 - val_loss: 0.5389 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7348 - val_loss: 0.5346 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7429 - val_loss: 0.5340 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7516 - val_loss: 0.5364 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7597 - val_loss: 0.5394 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4822 - accuracy: 0.7670
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7670 - val_loss: 0.5448 - val_accuracy: 0.7220 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4235262635322247
Confusion Matrix :
 [[2608 1439]
 [ 909 3139]]
Accuracy on test set:    0.7099444101297097
Sensitivity:    0.7754446640316206 	 Specificity:    0.6444279713367926
Precision  : 0.6856705985146352
Area Under Curve:    0.7099363176842066
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 4ms/step - loss: 0.5878 - accuracy: 0.6858 - val_loss: 0.5477 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7224 - val_loss: 0.5377 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7338 - val_loss: 0.5358 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7409 - val_loss: 0.5409 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7500 - val_loss: 0.5423 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.7547 - val_loss: 0.5413 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.7627 - val_loss: 0.5413 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4754 - accuracy: 0.7721 - val_loss: 0.5442 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4660 - accuracy: 0.7789 - val_loss: 0.5505 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4529 - accuracy: 0.7879
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4530 - accuracy: 0.7878 - val_loss: 0.5538 - val_accuracy: 0.7131 - lr: 0.0010
253/253 [==============================] - 0s 958us/step
Independent Testing Matthews Correlation:  0.42054022352645504
Confusion Matrix :
 [[2929 1118]
 [1228 2820]]
Accuracy on test set:    0.7101914762198889
Sensitivity:    0.6966403162055336 	 Specificity:    0.7237459846800098
Precision  : 0.7160995429151854
Area Under Curve:    0.7101931504427716
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5845 - accuracy: 0.6880 - val_loss: 0.5506 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7236 - val_loss: 0.5434 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5265 - accuracy: 0.7346 - val_loss: 0.5396 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7440 - val_loss: 0.5405 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5041 - accuracy: 0.7508 - val_loss: 0.5403 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7582 - val_loss: 0.5418 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4819 - accuracy: 0.7663 - val_loss: 0.5441 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4706 - accuracy: 0.7748 - val_loss: 0.5502 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4599 - accuracy: 0.7804
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4604 - accuracy: 0.7803 - val_loss: 0.5498 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 794us/step
Independent Testing Matthews Correlation:  0.41415730494313957
Confusion Matrix :
 [[2840 1207]
 [1164 2883]]
Accuracy on test set:    0.7070669631826044
Sensitivity:    0.7123795404002965 	 Specificity:    0.7017543859649122
Precision  : 0.7048899755501222
Area Under Curve:    0.7070669631826043
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5896 - accuracy: 0.6821 - val_loss: 0.5532 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7241 - val_loss: 0.5456 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7340 - val_loss: 0.5425 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7423 - val_loss: 0.5414 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7487 - val_loss: 0.5460 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7557 - val_loss: 0.5444 - val_accuracy: 0.7267 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7637 - val_loss: 0.5462 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4718 - accuracy: 0.7739 - val_loss: 0.5482 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4616 - accuracy: 0.7808 - val_loss: 0.5567 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4490 - accuracy: 0.7887 - val_loss: 0.5668 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4356 - accuracy: 0.7982
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4357 - accuracy: 0.7981 - val_loss: 0.5699 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 697us/step
Independent Testing Matthews Correlation:  0.40384919644779776
Confusion Matrix :
 [[2884 1163]
 [1250 2797]]
Accuracy on test set:    0.7018779342723005
Sensitivity:    0.6911292315295281 	 Specificity:    0.7126266370150729
Precision  : 0.7063131313131313
Area Under Curve:    0.7018779342723005
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5882 - accuracy: 0.6819 - val_loss: 0.5569 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7223 - val_loss: 0.5475 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7353 - val_loss: 0.5473 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7422 - val_loss: 0.5420 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7507 - val_loss: 0.5485 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7575 - val_loss: 0.5457 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7678 - val_loss: 0.5498 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4683 - accuracy: 0.7762 - val_loss: 0.5509 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 9/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4553 - accuracy: 0.7853
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4555 - accuracy: 0.7850 - val_loss: 0.5540 - val_accuracy: 0.7193 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4296589151623283
Confusion Matrix :
 [[2830 1217]
 [1092 2955]]
Accuracy on test set:    0.7147269582406721
Sensitivity:    0.7301704966641956 	 Specificity:    0.6992834198171485
Precision  : 0.7082933844678811
Area Under Curve:    0.7147269582406721
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5888 - accuracy: 0.6840 - val_loss: 0.5569 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7222 - val_loss: 0.5452 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5338 - accuracy: 0.7315 - val_loss: 0.5454 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5237 - accuracy: 0.7366 - val_loss: 0.5437 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7436 - val_loss: 0.5403 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7519 - val_loss: 0.5416 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7569 - val_loss: 0.5453 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4866 - accuracy: 0.7648 - val_loss: 0.5485 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4785 - accuracy: 0.7699 - val_loss: 0.5493 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.7791 - val_loss: 0.5504 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.7839 - val_loss: 0.5508 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4460 - accuracy: 0.7930 - val_loss: 0.5611 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 13/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4336 - accuracy: 0.8013
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4335 - accuracy: 0.8010 - val_loss: 0.5661 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.45503290907410043
Confusion Matrix :
 [[2992 1055]
 [1151 2896]]
Accuracy on test set:    0.7274524339016556
Sensitivity:    0.7155917963923895 	 Specificity:    0.7393130714109216
Precision  : 0.732978992660086
Area Under Curve:    0.7274524339016556
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5913 - accuracy: 0.6821 - val_loss: 0.5646 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7204 - val_loss: 0.5471 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5342 - accuracy: 0.7308 - val_loss: 0.5658 - val_accuracy: 0.7017 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5234 - accuracy: 0.7385 - val_loss: 0.5486 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5122 - accuracy: 0.7453 - val_loss: 0.5478 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7538 - val_loss: 0.5486 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.7627 - val_loss: 0.5502 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.7722 - val_loss: 0.5526 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4625 - accuracy: 0.7806 - val_loss: 0.5603 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4464 - accuracy: 0.7900 - val_loss: 0.5675 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4336 - accuracy: 0.7982 - val_loss: 0.5778 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 12/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4199 - accuracy: 0.8065
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4206 - accuracy: 0.8059 - val_loss: 0.5874 - val_accuracy: 0.7131 - lr: 0.0010
253/253 [==============================] - 0s 921us/step
Independent Testing Matthews Correlation:  0.45738259216285815
Confusion Matrix :
 [[2960 1087]
 [1109 2938]]
Accuracy on test set:    0.7286879169755375
Sensitivity:    0.7259698542129973 	 Specificity:    0.7314059797380776
Precision  : 0.7299378881987577
Area Under Curve:    0.7286879169755375
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5897 - accuracy: 0.6838 - val_loss: 0.5562 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5488 - accuracy: 0.7218 - val_loss: 0.5559 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5347 - accuracy: 0.7309 - val_loss: 0.5505 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5230 - accuracy: 0.7379 - val_loss: 0.5475 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5121 - accuracy: 0.7465 - val_loss: 0.5533 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.7530 - val_loss: 0.5488 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4905 - accuracy: 0.7628 - val_loss: 0.5537 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4792 - accuracy: 0.7709 - val_loss: 0.5546 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4659 - accuracy: 0.7789 - val_loss: 0.5581 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4536 - accuracy: 0.7868 - val_loss: 0.5676 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 11/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4409 - accuracy: 0.7938
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4401 - accuracy: 0.7940 - val_loss: 0.5689 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 857us/step
Independent Testing Matthews Correlation:  0.4738262479174224
Confusion Matrix :
 [[3104  943]
 [1190 2857]]
Accuracy on test set:    0.7364714603409933
Sensitivity:    0.7059550284161107 	 Specificity:    0.7669878922658759
Precision  : 0.7518421052631579
Area Under Curve:    0.7364714603409933
(8094, 2560) (8094,)
Mean MCC = 0.4310 + 0.0219 and Mean AUC = 0.7148 + 0.0112
Mean Sensitivity = 0.7292 + 0.0318 and Mean Specificity = 0.7005 + 0.0429 and Mean Accuracy = 0.7148 + 0.0112
Mean Precision = 0.7102 + 0.0221





Seed   : 801520
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5863 - accuracy: 0.6854 - val_loss: 0.5595 - val_accuracy: 0.7035 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5409 - accuracy: 0.7252 - val_loss: 0.5466 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5246 - accuracy: 0.7378 - val_loss: 0.5439 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5112 - accuracy: 0.7456 - val_loss: 0.5421 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.7541 - val_loss: 0.5482 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.7621 - val_loss: 0.5525 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4760 - accuracy: 0.7707 - val_loss: 0.5480 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4614 - accuracy: 0.7802
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4615 - accuracy: 0.7802 - val_loss: 0.5498 - val_accuracy: 0.7117 - lr: 0.0010
253/253 [==============================] - 0s 927us/step
Independent Testing Matthews Correlation:  0.40691421550750784
Confusion Matrix :
 [[2958 1090]
 [1313 2734]]
Accuracy on test set:    0.7031500926497838
Sensitivity:    0.6755621447986162 	 Specificity:    0.7307312252964426
Precision  : 0.7149581589958159
Area Under Curve:    0.7031466850475294
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5856 - accuracy: 0.6855 - val_loss: 0.5512 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7227 - val_loss: 0.5484 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7318 - val_loss: 0.5446 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7400 - val_loss: 0.5431 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7485 - val_loss: 0.5400 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7561 - val_loss: 0.5477 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7654 - val_loss: 0.5479 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7754 - val_loss: 0.5581 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4591 - accuracy: 0.7826 - val_loss: 0.5571 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4443 - accuracy: 0.7919 - val_loss: 0.5648 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4327 - accuracy: 0.8002 - val_loss: 0.5685 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4167 - accuracy: 0.8105 - val_loss: 0.5762 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4044 - accuracy: 0.8180 - val_loss: 0.5731 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 14/400
256/257 [============================>.] - ETA: 0s - loss: 0.3911 - accuracy: 0.8263
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3912 - accuracy: 0.8262 - val_loss: 0.5808 - val_accuracy: 0.7098 - lr: 0.0010
253/253 [==============================] - 0s 871us/step
Independent Testing Matthews Correlation:  0.4013439857107828
Confusion Matrix :
 [[2737 1311]
 [1114 2933]]
Accuracy on test set:    0.7004323656578134
Sensitivity:    0.7247343711391154 	 Specificity:    0.6761363636363636
Precision  : 0.6910933081998115
Area Under Curve:    0.7004353673877396
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5887 - accuracy: 0.6840 - val_loss: 0.5471 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7204 - val_loss: 0.5394 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7328 - val_loss: 0.5385 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5213 - accuracy: 0.7397 - val_loss: 0.5351 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5102 - accuracy: 0.7473 - val_loss: 0.5344 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5000 - accuracy: 0.7555 - val_loss: 0.5338 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4896 - accuracy: 0.7611
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4896 - accuracy: 0.7611 - val_loss: 0.5349 - val_accuracy: 0.7240 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43758733939167943
Confusion Matrix :
 [[2854 1193]
 [1084 2964]]
Accuracy on test set:    0.7187152563310686
Sensitivity:    0.7322134387351779 	 Specificity:    0.7052137385717816
Precision  : 0.713014192927592
Area Under Curve:    0.7187135886534797
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5869 - accuracy: 0.6860 - val_loss: 0.5438 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7209 - val_loss: 0.5340 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5327 - accuracy: 0.7301 - val_loss: 0.5348 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5212 - accuracy: 0.7392 - val_loss: 0.5324 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5120 - accuracy: 0.7453 - val_loss: 0.5299 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5015 - accuracy: 0.7528 - val_loss: 0.5357 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7596 - val_loss: 0.5327 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7671 - val_loss: 0.5356 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7741 - val_loss: 0.5367 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4580 - accuracy: 0.7831 - val_loss: 0.5378 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4486 - accuracy: 0.7890 - val_loss: 0.5461 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 12/400
253/257 [============================>.] - ETA: 0s - loss: 0.4382 - accuracy: 0.7958
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4384 - accuracy: 0.7955 - val_loss: 0.5544 - val_accuracy: 0.7249 - lr: 0.0010
253/253 [==============================] - 0s 734us/step
Independent Testing Matthews Correlation:  0.42244655049295926
Confusion Matrix :
 [[2609 1438]
 [ 914 3134]]
Accuracy on test set:    0.7094502779493514
Sensitivity:    0.7742094861660079 	 Specificity:    0.644675067951569
Precision  : 0.6854768153980753
Area Under Curve:    0.7094422770587885
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5833 - accuracy: 0.6884 - val_loss: 0.5501 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7226 - val_loss: 0.5446 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5268 - accuracy: 0.7341 - val_loss: 0.5402 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7437 - val_loss: 0.5415 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7507 - val_loss: 0.5404 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7585 - val_loss: 0.5471 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4816 - accuracy: 0.7648
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7648 - val_loss: 0.5438 - val_accuracy: 0.7142 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4227422333860701
Confusion Matrix :
 [[2994 1053]
 [1286 2761]]
Accuracy on test set:    0.7110205090190265
Sensitivity:    0.6822337533975784 	 Specificity:    0.7398072646404744
Precision  : 0.7239119035133718
Area Under Curve:    0.7110205090190264
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5923 - accuracy: 0.6801 - val_loss: 0.5504 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7206 - val_loss: 0.5450 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7326 - val_loss: 0.5456 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5209 - accuracy: 0.7381 - val_loss: 0.5435 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5113 - accuracy: 0.7467 - val_loss: 0.5415 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5000 - accuracy: 0.7540 - val_loss: 0.5438 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4908 - accuracy: 0.7605 - val_loss: 0.5482 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4793 - accuracy: 0.7676 - val_loss: 0.5498 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4683 - accuracy: 0.7772
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4683 - accuracy: 0.7772 - val_loss: 0.5573 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44032611634310154
Confusion Matrix :
 [[2777 1270]
 [ 999 3048]]
Accuracy on test set:    0.7196688905361996
Sensitivity:    0.7531504818383988 	 Specificity:    0.6861872992340005
Precision  : 0.7058823529411765
Area Under Curve:    0.7196688905361996
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.6836 - val_loss: 0.5495 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7234 - val_loss: 0.5459 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7341 - val_loss: 0.5438 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7439 - val_loss: 0.5464 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5054 - accuracy: 0.7500 - val_loss: 0.5411 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7587 - val_loss: 0.5394 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.7655 - val_loss: 0.5423 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.7737 - val_loss: 0.5489 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4601 - accuracy: 0.7813 - val_loss: 0.5510 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4494 - accuracy: 0.7877 - val_loss: 0.5593 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4374 - accuracy: 0.7971
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4376 - accuracy: 0.7971 - val_loss: 0.5615 - val_accuracy: 0.7121 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4137686089795846
Confusion Matrix :
 [[2810 1237]
 [1136 2911]]
Accuracy on test set:    0.706819866567828
Sensitivity:    0.7192982456140351 	 Specificity:    0.694341487521621
Precision  : 0.7017839922854388
Area Under Curve:    0.706819866567828
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5948 - accuracy: 0.6788 - val_loss: 0.5490 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7215 - val_loss: 0.5369 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7323 - val_loss: 0.5348 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7409 - val_loss: 0.5335 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7496 - val_loss: 0.5367 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7545 - val_loss: 0.5366 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7641 - val_loss: 0.5385 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7734 - val_loss: 0.5409 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4582 - accuracy: 0.7824 - val_loss: 0.5486 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4440 - accuracy: 0.7918 - val_loss: 0.5563 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4304 - accuracy: 0.7997 - val_loss: 0.5570 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 12/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4169 - accuracy: 0.8087
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4172 - accuracy: 0.8079 - val_loss: 0.5722 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42719344751467014
Confusion Matrix :
 [[2751 1296]
 [1026 3021]]
Accuracy on test set:    0.7131208302446257
Sensitivity:    0.7464788732394366 	 Specificity:    0.6797627872498146
Precision  : 0.6997915218902016
Area Under Curve:    0.7131208302446256
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5914 - accuracy: 0.6804 - val_loss: 0.5493 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7222 - val_loss: 0.5408 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7317 - val_loss: 0.5416 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7394 - val_loss: 0.5414 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7508 - val_loss: 0.5411 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.7581 - val_loss: 0.5450 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4792 - accuracy: 0.7695 - val_loss: 0.5468 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4647 - accuracy: 0.7784
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7782 - val_loss: 0.5526 - val_accuracy: 0.7193 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4598678597953889
Confusion Matrix :
 [[3086  961]
 [1229 2818]]
Accuracy on test set:    0.7294292068198666
Sensitivity:    0.696318260439832 	 Specificity:    0.7625401531999012
Precision  : 0.745699920613919
Area Under Curve:    0.7294292068198667
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5916 - accuracy: 0.6788 - val_loss: 0.5484 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5477 - accuracy: 0.7200 - val_loss: 0.5489 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5330 - accuracy: 0.7316 - val_loss: 0.5390 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7403 - val_loss: 0.5435 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7500 - val_loss: 0.5449 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4989 - accuracy: 0.7572 - val_loss: 0.5439 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7648 - val_loss: 0.5436 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.7717 - val_loss: 0.5529 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4640 - accuracy: 0.7786 - val_loss: 0.5500 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4512 - accuracy: 0.7869 - val_loss: 0.5569 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4385 - accuracy: 0.7966 - val_loss: 0.5616 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 12/400
249/257 [============================>.] - ETA: 0s - loss: 0.4264 - accuracy: 0.8032
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4266 - accuracy: 0.8031 - val_loss: 0.5711 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4719683809220991
Confusion Matrix :
 [[2994 1053]
 [1084 2963]]
Accuracy on test set:    0.7359772671114406
Sensitivity:    0.7321472695824067 	 Specificity:    0.7398072646404744
Precision  : 0.7377988047808764
Area Under Curve:    0.7359772671114406
(8094, 2560) (8094,)
Mean MCC = 0.4304 + 0.0213 and Mean AUC = 0.7148 + 0.0107
Mean Sensitivity = 0.7236 + 0.0298 and Mean Specificity = 0.7059 + 0.0346 and Mean Accuracy = 0.7148 + 0.0107
Mean Precision = 0.7119 + 0.0184





Seed   : 136051
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5873 - accuracy: 0.6837 - val_loss: 0.5542 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7241 - val_loss: 0.5566 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7348 - val_loss: 0.5575 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7438 - val_loss: 0.5565 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5043 - accuracy: 0.7506 - val_loss: 0.5574 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7582 - val_loss: 0.5506 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7667 - val_loss: 0.5603 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4688 - accuracy: 0.7759 - val_loss: 0.5591 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4553 - accuracy: 0.7839 - val_loss: 0.5669 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4419 - accuracy: 0.7929 - val_loss: 0.5708 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4279 - accuracy: 0.8004 - val_loss: 0.5719 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4153 - accuracy: 0.8075 - val_loss: 0.5853 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 13/400
251/257 [============================>.] - ETA: 0s - loss: 0.4028 - accuracy: 0.8158
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4030 - accuracy: 0.8158 - val_loss: 0.5923 - val_accuracy: 0.7050 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4093404374282175
Confusion Matrix :
 [[2814 1234]
 [1157 2890]]
Accuracy on test set:    0.7046324891908585
Sensitivity:    0.7141092167037312 	 Specificity:    0.6951581027667985
Precision  : 0.7007759456838021
Area Under Curve:    0.7046336597352647
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5860 - accuracy: 0.6859 - val_loss: 0.5543 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7237 - val_loss: 0.5488 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5255 - accuracy: 0.7380 - val_loss: 0.5577 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5130 - accuracy: 0.7452 - val_loss: 0.5480 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7542 - val_loss: 0.5526 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.7608 - val_loss: 0.5520 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4749 - accuracy: 0.7710 - val_loss: 0.5567 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4633 - accuracy: 0.7796 - val_loss: 0.5624 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4492 - accuracy: 0.7884
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4494 - accuracy: 0.7884 - val_loss: 0.5636 - val_accuracy: 0.7100 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.416969910467803
Confusion Matrix :
 [[2792 1256]
 [1105 2942]]
Accuracy on test set:    0.7083384805435454
Sensitivity:    0.7269582406721028 	 Specificity:    0.6897233201581028
Precision  : 0.7008099094807051
Area Under Curve:    0.7083407804151028
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5886 - accuracy: 0.6838 - val_loss: 0.5489 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7227 - val_loss: 0.5450 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7331 - val_loss: 0.5349 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5168 - accuracy: 0.7428 - val_loss: 0.5374 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7500 - val_loss: 0.5362 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7584 - val_loss: 0.5420 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4817 - accuracy: 0.7669 - val_loss: 0.5415 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4703 - accuracy: 0.7750 - val_loss: 0.5432 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4596 - accuracy: 0.7821 - val_loss: 0.5439 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4452 - accuracy: 0.7925
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4452 - accuracy: 0.7925 - val_loss: 0.5525 - val_accuracy: 0.7246 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.408576006864846
Confusion Matrix :
 [[2882 1165]
 [1229 2819]]
Accuracy on test set:    0.7042618900555899
Sensitivity:    0.696393280632411 	 Specificity:    0.7121324437855201
Precision  : 0.7075803212851406
Area Under Curve:    0.7042628622089655
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5882 - accuracy: 0.6858 - val_loss: 0.5443 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7220 - val_loss: 0.5354 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7332 - val_loss: 0.5334 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7415 - val_loss: 0.5379 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7505 - val_loss: 0.5348 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7578 - val_loss: 0.5346 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7685 - val_loss: 0.5381 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4666 - accuracy: 0.7786 - val_loss: 0.5425 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4531 - accuracy: 0.7871 - val_loss: 0.5464 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4400 - accuracy: 0.7966 - val_loss: 0.5487 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4248 - accuracy: 0.8059 - val_loss: 0.5665 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 12/400
255/257 [============================>.] - ETA: 0s - loss: 0.4126 - accuracy: 0.8129
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4126 - accuracy: 0.8129 - val_loss: 0.5617 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42285981298916236
Confusion Matrix :
 [[2706 1341]
 [1001 3047]]
Accuracy on test set:    0.7106856084002471
Sensitivity:    0.7527173913043478 	 Specificity:    0.6686434395848777
Precision  : 0.6943938012762079
Area Under Curve:    0.7106804154446128
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5847 - accuracy: 0.6859 - val_loss: 0.5584 - val_accuracy: 0.7062 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7239 - val_loss: 0.5459 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.7349 - val_loss: 0.5463 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7430 - val_loss: 0.5442 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7499 - val_loss: 0.5448 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7578 - val_loss: 0.5478 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4848 - accuracy: 0.7670 - val_loss: 0.5556 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7738 - val_loss: 0.5523 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4578 - accuracy: 0.7837
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4579 - accuracy: 0.7835 - val_loss: 0.5592 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 996us/step
Independent Testing Matthews Correlation:  0.4229310338700134
Confusion Matrix :
 [[2685 1362]
 [ 981 3066]]
Accuracy on test set:    0.7105263157894737
Sensitivity:    0.7575982209043736 	 Specificity:    0.6634544106745738
Precision  : 0.6924119241192412
Area Under Curve:    0.7105263157894737
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5852 - accuracy: 0.6851 - val_loss: 0.5533 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5423 - accuracy: 0.7249 - val_loss: 0.5435 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7338 - val_loss: 0.5423 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7416 - val_loss: 0.5452 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.7507 - val_loss: 0.5424 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.7611 - val_loss: 0.5467 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4827 - accuracy: 0.7683 - val_loss: 0.5535 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4689 - accuracy: 0.7754
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7753 - val_loss: 0.5547 - val_accuracy: 0.7148 - lr: 0.0010
253/253 [==============================] - 0s 775us/step
Independent Testing Matthews Correlation:  0.43068016586686264
Confusion Matrix :
 [[2990 1057]
 [1249 2798]]
Accuracy on test set:    0.7150976031628367
Sensitivity:    0.6913763281443044 	 Specificity:    0.7388188781813689
Precision  : 0.725810635538262
Area Under Curve:    0.7150976031628367
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5876 - accuracy: 0.6826 - val_loss: 0.5534 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7234 - val_loss: 0.5408 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7337 - val_loss: 0.5389 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7420 - val_loss: 0.5378 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7491 - val_loss: 0.5389 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7575 - val_loss: 0.5412 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7661 - val_loss: 0.5418 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7753 - val_loss: 0.5516 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.7819 - val_loss: 0.5582 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4473 - accuracy: 0.7918
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4473 - accuracy: 0.7918 - val_loss: 0.5565 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 921us/step
Independent Testing Matthews Correlation:  0.4069752809914359
Confusion Matrix :
 [[2859 1188]
 [1212 2835]]
Accuracy on test set:    0.7034840622683469
Sensitivity:    0.7005189028910304 	 Specificity:    0.7064492216456635
Precision  : 0.7046979865771812
Area Under Curve:    0.7034840622683469
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5913 - accuracy: 0.6803 - val_loss: 0.5524 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7206 - val_loss: 0.5394 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5331 - accuracy: 0.7324 - val_loss: 0.5389 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5222 - accuracy: 0.7395 - val_loss: 0.5364 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5106 - accuracy: 0.7465 - val_loss: 0.5355 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.7538 - val_loss: 0.5387 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4902 - accuracy: 0.7611 - val_loss: 0.5405 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4777 - accuracy: 0.7707 - val_loss: 0.5370 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4652 - accuracy: 0.7793 - val_loss: 0.5411 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 10/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4524 - accuracy: 0.7874
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4528 - accuracy: 0.7871 - val_loss: 0.5429 - val_accuracy: 0.7264 - lr: 0.0010
253/253 [==============================] - 0s 716us/step
Independent Testing Matthews Correlation:  0.44208852396216525
Confusion Matrix :
 [[2734 1313]
 [ 952 3095]]
Accuracy on test set:    0.7201630837657524
Sensitivity:    0.7647640227328886 	 Specificity:    0.6755621447986162
Precision  : 0.7021324863883848
Area Under Curve:    0.7201630837657523
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5916 - accuracy: 0.6811 - val_loss: 0.5507 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5494 - accuracy: 0.7195 - val_loss: 0.5418 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5349 - accuracy: 0.7298 - val_loss: 0.5428 - val_accuracy: 0.7172 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5238 - accuracy: 0.7374 - val_loss: 0.5371 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.7454 - val_loss: 0.5393 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7536 - val_loss: 0.5413 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4938 - accuracy: 0.7610
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7610 - val_loss: 0.5423 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4573803580101126
Confusion Matrix :
 [[2940 1107]
 [1089 2958]]
Accuracy on test set:    0.7286879169755375
Sensitivity:    0.7309117865085248 	 Specificity:    0.72646404744255
Precision  : 0.7276752767527676
Area Under Curve:    0.7286879169755375
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5902 - accuracy: 0.6826 - val_loss: 0.5551 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5494 - accuracy: 0.7197 - val_loss: 0.5458 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7310 - val_loss: 0.5398 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5220 - accuracy: 0.7407 - val_loss: 0.5360 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7480 - val_loss: 0.5386 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7597 - val_loss: 0.5424 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7664 - val_loss: 0.5444 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4702 - accuracy: 0.7752 - val_loss: 0.5457 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4550 - accuracy: 0.7853 - val_loss: 0.5571 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4430 - accuracy: 0.7927 - val_loss: 0.5531 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4280 - accuracy: 0.8019
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4289 - accuracy: 0.8010 - val_loss: 0.5604 - val_accuracy: 0.7141 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47267424959169835
Confusion Matrix :
 [[3042 1005]
 [1130 2917]]
Accuracy on test set:    0.7362243637262169
Sensitivity:    0.7207808253026934 	 Specificity:    0.7516679021497406
Precision  : 0.7437531871494135
Area Under Curve:    0.7362243637262169
(8094, 2560) (8094,)
Mean MCC = 0.4290 + 0.0210 and Mean AUC = 0.7142 + 0.0105
Mean Sensitivity = 0.7256 + 0.0248 and Mean Specificity = 0.7028 + 0.0283 and Mean Accuracy = 0.7142 + 0.0105
Mean Precision = 0.7100 + 0.0159





Seed   : 680006
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5855 - accuracy: 0.6867 - val_loss: 0.5549 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5423 - accuracy: 0.7259 - val_loss: 0.5468 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7344 - val_loss: 0.5457 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7403 - val_loss: 0.5405 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7504 - val_loss: 0.5421 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7573 - val_loss: 0.5454 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4862 - accuracy: 0.7653 - val_loss: 0.5431 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.7714 - val_loss: 0.5510 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4626 - accuracy: 0.7804 - val_loss: 0.5496 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4512 - accuracy: 0.7878 - val_loss: 0.5539 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4362 - accuracy: 0.7969 - val_loss: 0.5660 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4232 - accuracy: 0.8042 - val_loss: 0.5685 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4129 - accuracy: 0.8104 - val_loss: 0.5710 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 14/400
245/257 [===========================>..] - ETA: 0s - loss: 0.3993 - accuracy: 0.8182
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3996 - accuracy: 0.8181 - val_loss: 0.5859 - val_accuracy: 0.7113 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.38833560464205774
Confusion Matrix :
 [[2659 1389]
 [1091 2956]]
Accuracy on test set:    0.6936380481778875
Sensitivity:    0.730417593278972 	 Specificity:    0.6568675889328063
Precision  : 0.6803222094361335
Area Under Curve:    0.6936425911058892
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5855 - accuracy: 0.6867 - val_loss: 0.5558 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7250 - val_loss: 0.5483 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7361 - val_loss: 0.5544 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7437 - val_loss: 0.5403 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7532 - val_loss: 0.5489 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7606 - val_loss: 0.5455 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4808 - accuracy: 0.7682
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.7680 - val_loss: 0.5519 - val_accuracy: 0.7115 - lr: 0.0010
253/253 [==============================] - 0s 885us/step
Independent Testing Matthews Correlation:  0.4135567798239958
Confusion Matrix :
 [[2571 1477]
 [ 913 3134]]
Accuracy on test set:    0.7047560222359481
Sensitivity:    0.7744007907091672 	 Specificity:    0.6351284584980237
Precision  : 0.6796790284103231
Area Under Curve:    0.7047646246035955
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5880 - accuracy: 0.6845 - val_loss: 0.5470 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7229 - val_loss: 0.5373 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7326 - val_loss: 0.5334 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7424 - val_loss: 0.5367 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7462 - val_loss: 0.5338 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7565 - val_loss: 0.5354 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7651 - val_loss: 0.5361 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4748 - accuracy: 0.7732 - val_loss: 0.5374 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4614 - accuracy: 0.7814 - val_loss: 0.5445 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4507 - accuracy: 0.7887
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4507 - accuracy: 0.7888 - val_loss: 0.5488 - val_accuracy: 0.7219 - lr: 0.0010
253/253 [==============================] - 0s 951us/step
Independent Testing Matthews Correlation:  0.4330650537342593
Confusion Matrix :
 [[2755 1292]
 [1007 3041]]
Accuracy on test set:    0.7159975293390982
Sensitivity:    0.7512351778656127 	 Specificity:    0.6807511737089202
Precision  : 0.7018232171705516
Area Under Curve:    0.7159931757872665
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5882 - accuracy: 0.6827 - val_loss: 0.5480 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7213 - val_loss: 0.5342 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7335 - val_loss: 0.5298 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7417 - val_loss: 0.5307 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5043 - accuracy: 0.7499 - val_loss: 0.5323 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.7595 - val_loss: 0.5333 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.7689 - val_loss: 0.5366 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4687 - accuracy: 0.7760
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4692 - accuracy: 0.7755 - val_loss: 0.5409 - val_accuracy: 0.7240 - lr: 0.0010
253/253 [==============================] - 0s 880us/step
Independent Testing Matthews Correlation:  0.4234210502298381
Confusion Matrix :
 [[2842 1205]
 [1129 2919]]
Accuracy on test set:    0.7116738727609636
Sensitivity:    0.7210968379446641 	 Specificity:    0.702248579194465
Precision  : 0.707807953443259
Area Under Curve:    0.7116727085695645
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5914 - accuracy: 0.6798 - val_loss: 0.5615 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7223 - val_loss: 0.5441 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7322 - val_loss: 0.5445 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7384 - val_loss: 0.5463 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5101 - accuracy: 0.7477 - val_loss: 0.5465 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5003 - accuracy: 0.7528 - val_loss: 0.5454 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4903 - accuracy: 0.7605
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7602 - val_loss: 0.5451 - val_accuracy: 0.7156 - lr: 0.0010
253/253 [==============================] - 0s 796us/step
Independent Testing Matthews Correlation:  0.43024569907246846
Confusion Matrix :
 [[2863 1184]
 [1122 2925]]
Accuracy on test set:    0.7150976031628367
Sensitivity:    0.7227575982209044 	 Specificity:    0.707437608104769
Precision  : 0.7118520321246046
Area Under Curve:    0.7150976031628367
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5848 - accuracy: 0.6867 - val_loss: 0.5525 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7249 - val_loss: 0.5445 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7323 - val_loss: 0.5418 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7439 - val_loss: 0.5436 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5034 - accuracy: 0.7528 - val_loss: 0.5414 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7616 - val_loss: 0.5452 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4788 - accuracy: 0.7701 - val_loss: 0.5473 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4663 - accuracy: 0.7784 - val_loss: 0.5517 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4523 - accuracy: 0.7874 - val_loss: 0.5591 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4397 - accuracy: 0.7953 - val_loss: 0.5649 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4266 - accuracy: 0.8037
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4274 - accuracy: 0.8029 - val_loss: 0.5773 - val_accuracy: 0.7137 - lr: 0.0010
253/253 [==============================] - 0s 960us/step
Independent Testing Matthews Correlation:  0.4097344687971514
Confusion Matrix :
 [[3150  897]
 [1511 2536]]
Accuracy on test set:    0.7024956758092414
Sensitivity:    0.6266370150728935 	 Specificity:    0.7783543365455893
Precision  : 0.7387124963588698
Area Under Curve:    0.7024956758092414
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5854 - accuracy: 0.6846 - val_loss: 0.5464 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5432 - accuracy: 0.7222 - val_loss: 0.5416 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7325 - val_loss: 0.5400 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7392 - val_loss: 0.5521 - val_accuracy: 0.7187 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7501 - val_loss: 0.5430 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4954 - accuracy: 0.7583
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7581 - val_loss: 0.5422 - val_accuracy: 0.7213 - lr: 0.0010
253/253 [==============================] - 0s 716us/step
Independent Testing Matthews Correlation:  0.43994626202892534
Confusion Matrix :
 [[2995 1052]
 [1216 2831]]
Accuracy on test set:    0.7197924388435878
Sensitivity:    0.6995305164319249 	 Specificity:    0.7400543612552508
Precision  : 0.7290754571207829
Area Under Curve:    0.7197924388435879
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5835 - accuracy: 0.6872 - val_loss: 0.5484 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7228 - val_loss: 0.5425 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7352 - val_loss: 0.5396 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7413 - val_loss: 0.5380 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7508 - val_loss: 0.5388 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7577 - val_loss: 0.5409 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4841 - accuracy: 0.7643 - val_loss: 0.5406 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4723 - accuracy: 0.7747 - val_loss: 0.5552 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4587 - accuracy: 0.7833 - val_loss: 0.5523 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4477 - accuracy: 0.7911 - val_loss: 0.5507 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4330 - accuracy: 0.7985 - val_loss: 0.5580 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 12/400
253/257 [============================>.] - ETA: 0s - loss: 0.4198 - accuracy: 0.8069
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4198 - accuracy: 0.8069 - val_loss: 0.5724 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 763us/step
Independent Testing Matthews Correlation:  0.4466345528761988
Confusion Matrix :
 [[2878 1169]
 [1071 2976]]
Accuracy on test set:    0.7232517914504571
Sensitivity:    0.7353595255744997 	 Specificity:    0.7111440573264146
Precision  : 0.7179734620024125
Area Under Curve:    0.7232517914504571
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5912 - accuracy: 0.6821 - val_loss: 0.5530 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7208 - val_loss: 0.5438 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7327 - val_loss: 0.5409 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7424 - val_loss: 0.5402 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7488 - val_loss: 0.5396 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7564 - val_loss: 0.5387 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7671 - val_loss: 0.5468 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7740 - val_loss: 0.5470 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4578 - accuracy: 0.7828 - val_loss: 0.5526 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4474 - accuracy: 0.7897 - val_loss: 0.5576 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4338 - accuracy: 0.7991
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4336 - accuracy: 0.7991 - val_loss: 0.5652 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 850us/step
Independent Testing Matthews Correlation:  0.45318651436328805
Confusion Matrix :
 [[3147  900]
 [1323 2724]]
Accuracy on test set:    0.7253521126760564
Sensitivity:    0.6730911786508524 	 Specificity:    0.7776130467012602
Precision  : 0.7516556291390728
Area Under Curve:    0.7253521126760563
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5957 - accuracy: 0.6767 - val_loss: 0.5540 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5507 - accuracy: 0.7203 - val_loss: 0.5435 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5351 - accuracy: 0.7303 - val_loss: 0.5412 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5249 - accuracy: 0.7386 - val_loss: 0.5419 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5141 - accuracy: 0.7459 - val_loss: 0.5397 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7562 - val_loss: 0.5468 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7618 - val_loss: 0.5424 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4791 - accuracy: 0.7702 - val_loss: 0.5483 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.7787 - val_loss: 0.5538 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4533 - accuracy: 0.7884 - val_loss: 0.5577 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4406 - accuracy: 0.7936 - val_loss: 0.5561 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4249 - accuracy: 0.8062
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4252 - accuracy: 0.8059 - val_loss: 0.5635 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 803us/step
Independent Testing Matthews Correlation:  0.4764756054332584
Confusion Matrix :
 [[3023 1024]
 [1095 2952]]
Accuracy on test set:    0.738201136644428
Sensitivity:    0.7294292068198666 	 Specificity:    0.7469730664689894
Precision  : 0.7424547283702213
Area Under Curve:    0.7382011366444279
(8094, 2560) (8094,)
Mean MCC = 0.4315 + 0.0235 and Mean AUC = 0.7150 + 0.0121
Mean Sensitivity = 0.7164 + 0.0395 and Mean Specificity = 0.7137 + 0.0455 and Mean Accuracy = 0.7150 + 0.0121
Mean Precision = 0.7161 + 0.0235





Seed   : 100584
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5870 - accuracy: 0.6839 - val_loss: 0.5594 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7223 - val_loss: 0.5498 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7345 - val_loss: 0.5484 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5149 - accuracy: 0.7440 - val_loss: 0.5504 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7517 - val_loss: 0.5490 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.7599 - val_loss: 0.5556 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4811 - accuracy: 0.7686 - val_loss: 0.5568 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4692 - accuracy: 0.7788 - val_loss: 0.5646 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4545 - accuracy: 0.7865 - val_loss: 0.5692 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4420 - accuracy: 0.7963
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7963 - val_loss: 0.5717 - val_accuracy: 0.7108 - lr: 0.0010
253/253 [==============================] - 0s 760us/step
Independent Testing Matthews Correlation:  0.41207964764890603
Confusion Matrix :
 [[2749 1299]
 [1083 2964]]
Accuracy on test set:    0.7057442865966647
Sensitivity:    0.7323943661971831 	 Specificity:    0.679100790513834
Precision  : 0.6952850105559465
Area Under Curve:    0.7057475783555085
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5839 - accuracy: 0.6888 - val_loss: 0.5575 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7245 - val_loss: 0.5496 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7339 - val_loss: 0.5482 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7425 - val_loss: 0.5442 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7487 - val_loss: 0.5495 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7580 - val_loss: 0.5517 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7649 - val_loss: 0.5514 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7744 - val_loss: 0.5501 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 9/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4607 - accuracy: 0.7826
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4602 - accuracy: 0.7829 - val_loss: 0.5621 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 726us/step
Independent Testing Matthews Correlation:  0.42237125710144663
Confusion Matrix :
 [[2808 1240]
 [1099 2948]]
Accuracy on test set:    0.7110562075355158
Sensitivity:    0.7284408203607611 	 Specificity:    0.6936758893280632
Precision  : 0.7039159503342884
Area Under Curve:    0.7110583548444122
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5853 - accuracy: 0.6851 - val_loss: 0.5539 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7243 - val_loss: 0.5462 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7332 - val_loss: 0.5397 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7408 - val_loss: 0.5402 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7476 - val_loss: 0.5410 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4991 - accuracy: 0.7531 - val_loss: 0.5488 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7635 - val_loss: 0.5438 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4777 - accuracy: 0.7709 - val_loss: 0.5462 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4668 - accuracy: 0.7783 - val_loss: 0.5469 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4556 - accuracy: 0.7872
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4557 - accuracy: 0.7870 - val_loss: 0.5560 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42342904700084366
Confusion Matrix :
 [[2840 1207]
 [1127 2921]]
Accuracy on test set:    0.7116738727609636
Sensitivity:    0.7215909090909091 	 Specificity:    0.7017543859649122
Precision  : 0.7076065891472868
Area Under Curve:    0.7116726475279106
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5856 - accuracy: 0.6866 - val_loss: 0.5471 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5432 - accuracy: 0.7234 - val_loss: 0.5394 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7337 - val_loss: 0.5353 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7419 - val_loss: 0.5502 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7523 - val_loss: 0.5368 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4928 - accuracy: 0.7603 - val_loss: 0.5392 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7672 - val_loss: 0.5429 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4673 - accuracy: 0.7781
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.7779 - val_loss: 0.5438 - val_accuracy: 0.7226 - lr: 0.0010
253/253 [==============================] - 0s 798us/step
Independent Testing Matthews Correlation:  0.4112149867482819
Confusion Matrix :
 [[2682 1365]
 [1024 3024]]
Accuracy on test set:    0.7048795552810376
Sensitivity:    0.7470355731225297 	 Specificity:    0.6627131208302446
Precision  : 0.6889952153110048
Area Under Curve:    0.7048743469763872
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5862 - accuracy: 0.6862 - val_loss: 0.5506 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7226 - val_loss: 0.5386 - val_accuracy: 0.7278 - lr: 0.0010

Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7333 - val_loss: 0.5399 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7421 - val_loss: 0.5404 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7487 - val_loss: 0.5382 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7595 - val_loss: 0.5432 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4833 - accuracy: 0.7672
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.7672 - val_loss: 0.5413 - val_accuracy: 0.7209 - lr: 0.0010
253/253 [==============================] - 0s 836us/step
Independent Testing Matthews Correlation:  0.42359251576785917
Confusion Matrix :
 [[2917 1130]
 [1203 2844]]
Accuracy on test set:    0.7117617988633556
Sensitivity:    0.7027427724240178 	 Specificity:    0.7207808253026934
Precision  : 0.7156517362858581
Area Under Curve:    0.7117617988633556
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5863 - accuracy: 0.6832 - val_loss: 0.5537 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7212 - val_loss: 0.5410 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.7316 - val_loss: 0.5370 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7420 - val_loss: 0.5382 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7503 - val_loss: 0.5376 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.7612 - val_loss: 0.5437 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4822 - accuracy: 0.7674
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7674 - val_loss: 0.5469 - val_accuracy: 0.7207 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4306624625829988
Confusion Matrix :
 [[2777 1270]
 [1037 3010]]
Accuracy on test set:    0.7149740548554485
Sensitivity:    0.7437608104768965 	 Specificity:    0.6861872992340005
Precision  : 0.7032710280373832
Area Under Curve:    0.7149740548554486
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5846 - accuracy: 0.6879 - val_loss: 0.5461 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7220 - val_loss: 0.5369 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5252 - accuracy: 0.7352 - val_loss: 0.5303 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7443 - val_loss: 0.5333 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5018 - accuracy: 0.7541 - val_loss: 0.5338 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4908 - accuracy: 0.7605 - val_loss: 0.5349 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4799 - accuracy: 0.7677
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7685 - val_loss: 0.5459 - val_accuracy: 0.7271 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41885583676842514
Confusion Matrix :
 [[2657 1390]
 [ 971 3076]]
Accuracy on test set:    0.7083024462564863
Sensitivity:    0.7600691870521374 	 Specificity:    0.6565357054608352
Precision  : 0.6887595163457232
Area Under Curve:    0.7083024462564863
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5930 - accuracy: 0.6792 - val_loss: 0.5474 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7211 - val_loss: 0.5369 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7317 - val_loss: 0.5369 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7407 - val_loss: 0.5338 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7487 - val_loss: 0.5317 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7581 - val_loss: 0.5352 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4832 - accuracy: 0.7665
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7665 - val_loss: 0.5344 - val_accuracy: 0.7296 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4423040341795328
Confusion Matrix :
 [[2923 1124]
 [1133 2914]]
Accuracy on test set:    0.7211514702248579
Sensitivity:    0.7200395354583642 	 Specificity:    0.7222634049913517
Precision  : 0.721644378405151
Area Under Curve:    0.721151470224858
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5961 - accuracy: 0.6768 - val_loss: 0.5493 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7187 - val_loss: 0.5415 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5350 - accuracy: 0.7308 - val_loss: 0.5423 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5242 - accuracy: 0.7378 - val_loss: 0.5412 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5118 - accuracy: 0.7463 - val_loss: 0.5363 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7540 - val_loss: 0.5390 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4890 - accuracy: 0.7621 - val_loss: 0.5421 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4777 - accuracy: 0.7697 - val_loss: 0.5405 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4643 - accuracy: 0.7803 - val_loss: 0.5516 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4511 - accuracy: 0.7879
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4510 - accuracy: 0.7877 - val_loss: 0.5539 - val_accuracy: 0.7241 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4566737074686121
Confusion Matrix :
 [[2974 1073]
 [1126 2921]]
Accuracy on test set:    0.7283172720533728
Sensitivity:    0.7217692117617989 	 Specificity:    0.7348653323449469
Precision  : 0.7313470205307961
Area Under Curve:    0.7283172720533728
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5932 - accuracy: 0.6797 - val_loss: 0.5553 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5511 - accuracy: 0.7189 - val_loss: 0.5439 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5361 - accuracy: 0.7283 - val_loss: 0.5405 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5254 - accuracy: 0.7335 - val_loss: 0.5398 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7441 - val_loss: 0.5378 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7516 - val_loss: 0.5471 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7580 - val_loss: 0.5467 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7675 - val_loss: 0.5455 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4711 - accuracy: 0.7761 - val_loss: 0.5467 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.7812 - val_loss: 0.5495 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4460 - accuracy: 0.7908 - val_loss: 0.5604 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4354 - accuracy: 0.7981 - val_loss: 0.5608 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4214 - accuracy: 0.8074 - val_loss: 0.5654 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 14/400
255/257 [============================>.] - ETA: 0s - loss: 0.4095 - accuracy: 0.8135
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4096 - accuracy: 0.8135 - val_loss: 0.5761 - val_accuracy: 0.7278 - lr: 0.0010
253/253 [==============================] - 0s 786us/step
Independent Testing Matthews Correlation:  0.4723132245817448
Confusion Matrix :
 [[3154  893]
 [1250 2797]]
Accuracy on test set:    0.7352359772671114
Sensitivity:    0.6911292315295281 	 Specificity:    0.7793427230046949
Precision  : 0.7579945799457994
Area Under Curve:    0.7352359772671115
(8094, 2560) (8094,)
Mean MCC = 0.4313 + 0.0189 and Mean AUC = 0.7153 + 0.0095
Mean Sensitivity = 0.7269 + 0.0195 and Mean Specificity = 0.7037 + 0.0350 and Mean Accuracy = 0.7153 + 0.0095
Mean Precision = 0.7114 + 0.0203





Seed   : 40795
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5859 - accuracy: 0.6867 - val_loss: 0.5604 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7255 - val_loss: 0.5490 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.7352 - val_loss: 0.5504 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.7442 - val_loss: 0.5494 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5027 - accuracy: 0.7517 - val_loss: 0.5473 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4902 - accuracy: 0.7604 - val_loss: 0.5466 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4783 - accuracy: 0.7693 - val_loss: 0.5557 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4654 - accuracy: 0.7785 - val_loss: 0.5532 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4543 - accuracy: 0.7873 - val_loss: 0.5593 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4412 - accuracy: 0.7921 - val_loss: 0.5606 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4292 - accuracy: 0.8009 - val_loss: 0.5727 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4162 - accuracy: 0.8099 - val_loss: 0.5777 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 13/400
249/257 [============================>.] - ETA: 0s - loss: 0.4040 - accuracy: 0.8151
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4039 - accuracy: 0.8151 - val_loss: 0.5809 - val_accuracy: 0.7115 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.38897072857871096
Confusion Matrix :
 [[2593 1455]
 [1027 3020]]
Accuracy on test set:    0.6933909820877084
Sensitivity:    0.7462317766246602 	 Specificity:    0.6405632411067194
Precision  : 0.6748603351955307
Area Under Curve:    0.6933975088656897
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5839 - accuracy: 0.6867 - val_loss: 0.5569 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7254 - val_loss: 0.5492 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5254 - accuracy: 0.7359 - val_loss: 0.5453 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5137 - accuracy: 0.7446 - val_loss: 0.5456 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7525 - val_loss: 0.5484 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7596 - val_loss: 0.5485 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7670 - val_loss: 0.5502 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4709 - accuracy: 0.7752
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7749 - val_loss: 0.5509 - val_accuracy: 0.7113 - lr: 0.0010
253/253 [==============================] - 0s 894us/step
Independent Testing Matthews Correlation:  0.4161226563415765
Confusion Matrix :
 [[2927 1121]
 [1243 2804]]
Accuracy on test set:    0.7079678814082767
Sensitivity:    0.6928589078329627 	 Specificity:    0.7230731225296443
Precision  : 0.7143949044585988
Area Under Curve:    0.7079660151813035
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5893 - accuracy: 0.6826 - val_loss: 0.5568 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7222 - val_loss: 0.5441 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7334 - val_loss: 0.5403 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7414 - val_loss: 0.5380 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7495 - val_loss: 0.5425 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7575 - val_loss: 0.5423 - val_accuracy: 0.7170 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7679 - val_loss: 0.5437 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7734 - val_loss: 0.5441 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4590 - accuracy: 0.7824 - val_loss: 0.5488 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4451 - accuracy: 0.7924 - val_loss: 0.5516 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4321 - accuracy: 0.8007 - val_loss: 0.5560 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4196 - accuracy: 0.8086
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4201 - accuracy: 0.8085 - val_loss: 0.5637 - val_accuracy: 0.7200 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.4291495382197935
Confusion Matrix :
 [[2728 1319]
 [ 997 3051]]
Accuracy on test set:    0.7138974675725757
Sensitivity:    0.7537055335968379 	 Specificity:    0.674079565109958
Precision  : 0.6981693363844393
Area Under Curve:    0.713892549353398
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5852 - accuracy: 0.6842 - val_loss: 0.5477 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7226 - val_loss: 0.5449 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7324 - val_loss: 0.5381 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7422 - val_loss: 0.5404 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7488 - val_loss: 0.5375 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7559 - val_loss: 0.5395 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.7635 - val_loss: 0.5615 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4740 - accuracy: 0.7716 - val_loss: 0.5466 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4611 - accuracy: 0.7808 - val_loss: 0.5450 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4520 - accuracy: 0.7862
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4520 - accuracy: 0.7862 - val_loss: 0.5515 - val_accuracy: 0.7219 - lr: 0.0010
253/253 [==============================] - 0s 698us/step
Independent Testing Matthews Correlation:  0.4093737245607941
Confusion Matrix :
 [[2935 1112]
 [1280 2768]]
Accuracy on test set:    0.704508956145769
Sensitivity:    0.6837944664031621 	 Specificity:    0.7252285643686681
Precision  : 0.7134020618556701
Area Under Curve:    0.7045115153859152
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5854 - accuracy: 0.6875 - val_loss: 0.5577 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7236 - val_loss: 0.5509 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7329 - val_loss: 0.5459 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7419 - val_loss: 0.5516 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7482 - val_loss: 0.5485 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7570 - val_loss: 0.5529 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.7634 - val_loss: 0.5525 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4763 - accuracy: 0.7724
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4764 - accuracy: 0.7723 - val_loss: 0.5528 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 779us/step
Independent Testing Matthews Correlation:  0.43322517627420437
Confusion Matrix :
 [[2865 1182]
 [1112 2935]]
Accuracy on test set:    0.7165801828514949
Sensitivity:    0.7252285643686681 	 Specificity:    0.7079318013343218
Precision  : 0.7128977410735973
Area Under Curve:    0.7165801828514949
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5860 - accuracy: 0.6878 - val_loss: 0.5533 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7238 - val_loss: 0.5493 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7321 - val_loss: 0.5458 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7407 - val_loss: 0.5489 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7489 - val_loss: 0.5483 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7581 - val_loss: 0.5537 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7671 - val_loss: 0.5521 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4693 - accuracy: 0.7752 - val_loss: 0.5553 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4576 - accuracy: 0.7843 - val_loss: 0.5623 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4447 - accuracy: 0.7911 - val_loss: 0.5633 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4340 - accuracy: 0.7982 - val_loss: 0.5682 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4210 - accuracy: 0.8063 - val_loss: 0.5712 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4116 - accuracy: 0.8104 - val_loss: 0.5735 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 14/400
256/257 [============================>.] - ETA: 0s - loss: 0.3969 - accuracy: 0.8203
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3968 - accuracy: 0.8203 - val_loss: 0.5890 - val_accuracy: 0.7137 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4173920571530416
Confusion Matrix :
 [[2838 1209]
 [1149 2898]]
Accuracy on test set:    0.7086730911786508
Sensitivity:    0.7160859896219421 	 Specificity:    0.7012601927353596
Precision  : 0.7056245434623813
Area Under Curve:    0.7086730911786508
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5847 - accuracy: 0.6877 - val_loss: 0.5504 - val_accuracy: 0.7200 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7235 - val_loss: 0.5450 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7351 - val_loss: 0.5405 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7429 - val_loss: 0.5471 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7523 - val_loss: 0.5448 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7601 - val_loss: 0.5431 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4794 - accuracy: 0.7683
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7681 - val_loss: 0.5465 - val_accuracy: 0.7227 - lr: 0.0010
253/253 [==============================] - 0s 719us/step
Independent Testing Matthews Correlation:  0.4380083205051636
Confusion Matrix :
 [[2963 1084]
 [1191 2856]]
Accuracy on test set:    0.7189276006918706
Sensitivity:    0.7057079318013343 	 Specificity:    0.7321472695824067
Precision  : 0.7248730964467005
Area Under Curve:    0.7189276006918704
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5923 - accuracy: 0.6793 - val_loss: 0.5538 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5506 - accuracy: 0.7190 - val_loss: 0.5469 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5338 - accuracy: 0.7315 - val_loss: 0.5419 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5228 - accuracy: 0.7375 - val_loss: 0.5404 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5124 - accuracy: 0.7470 - val_loss: 0.5457 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5022 - accuracy: 0.7532 - val_loss: 0.5421 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7625 - val_loss: 0.5438 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7710 - val_loss: 0.5446 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7808 - val_loss: 0.5503 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4525 - accuracy: 0.7884 - val_loss: 0.5487 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4391 - accuracy: 0.7979 - val_loss: 0.5604 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 12/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4247 - accuracy: 0.8064
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4249 - accuracy: 0.8062 - val_loss: 0.5611 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4365032467391616
Confusion Matrix :
 [[2857 1190]
 [1091 2956]]
Accuracy on test set:    0.7181863108475414
Sensitivity:    0.730417593278972 	 Specificity:    0.7059550284161107
Precision  : 0.7129763627592861
Area Under Curve:    0.7181863108475414
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5893 - accuracy: 0.6837 - val_loss: 0.5543 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7225 - val_loss: 0.5456 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7317 - val_loss: 0.5497 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7409 - val_loss: 0.5462 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7492 - val_loss: 0.5459 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7573 - val_loss: 0.5527 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
252/257 [============================>.] - ETA: 0s - loss: 0.4832 - accuracy: 0.7679
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7678 - val_loss: 0.5486 - val_accuracy: 0.7150 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4598535948217607
Confusion Matrix :
 [[2965 1082]
 [1104 2943]]
Accuracy on test set:    0.7299234000494194
Sensitivity:    0.7272053372868792 	 Specificity:    0.7326414628119595
Precision  : 0.7311801242236025
Area Under Curve:    0.7299234000494194
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5908 - accuracy: 0.6819 - val_loss: 0.5656 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5507 - accuracy: 0.7193 - val_loss: 0.5533 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7316 - val_loss: 0.5496 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7398 - val_loss: 0.5499 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7472 - val_loss: 0.5464 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7552 - val_loss: 0.5471 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7641 - val_loss: 0.5510 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7716 - val_loss: 0.5577 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4621 - accuracy: 0.7808 - val_loss: 0.5633 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4487 - accuracy: 0.7883 - val_loss: 0.5586 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 11/400
256/257 [============================>.] - ETA: 0s - loss: 0.4344 - accuracy: 0.7984
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4344 - accuracy: 0.7984 - val_loss: 0.5675 - val_accuracy: 0.7149 - lr: 0.0010
253/253 [==============================] - 0s 881us/step
Independent Testing Matthews Correlation:  0.4701595830783204
Confusion Matrix :
 [[3129  918]
 [1232 2815]]
Accuracy on test set:    0.7343711391153941
Sensitivity:    0.6955769705955028 	 Specificity:    0.7731653076352853
Precision  : 0.7540851861773372
Area Under Curve:    0.7343711391153941
(8094, 2560) (8094,)
Mean MCC = 0.4299 + 0.0225 and Mean AUC = 0.7146 + 0.0114
Mean Sensitivity = 0.7177 + 0.0220 and Mean Specificity = 0.7116 + 0.0340 and Mean Accuracy = 0.7146 + 0.0114
Mean Precision = 0.7142 + 0.0197





Seed   : 616488
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5853 - accuracy: 0.6870 - val_loss: 0.5697 - val_accuracy: 0.7019 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7248 - val_loss: 0.5593 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5269 - accuracy: 0.7376 - val_loss: 0.5554 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7444 - val_loss: 0.5538 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7523 - val_loss: 0.5603 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7617 - val_loss: 0.5598 - val_accuracy: 0.7058 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7706 - val_loss: 0.5614 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4680 - accuracy: 0.7766 - val_loss: 0.5627 - val_accuracy: 0.7030 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4576 - accuracy: 0.7837
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4574 - accuracy: 0.7840 - val_loss: 0.5688 - val_accuracy: 0.7060 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.418729125814105
Confusion Matrix :
 [[2644 1404]
 [ 959 3088]]
Accuracy on test set:    0.7080914144533663
Sensitivity:    0.7630343464294539 	 Specificity:    0.6531620553359684
Precision  : 0.6874443455031166
Area Under Curve:    0.7080982008827111
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5893 - accuracy: 0.6813 - val_loss: 0.5649 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7248 - val_loss: 0.5625 - val_accuracy: 0.7001 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5265 - accuracy: 0.7359 - val_loss: 0.5616 - val_accuracy: 0.7038 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7438 - val_loss: 0.5539 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7515 - val_loss: 0.5582 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7597 - val_loss: 0.5577 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4819 - accuracy: 0.7683 - val_loss: 0.5592 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7779 - val_loss: 0.5654 - val_accuracy: 0.7054 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4569 - accuracy: 0.7839 - val_loss: 0.5694 - val_accuracy: 0.7042 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4441 - accuracy: 0.7920
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4441 - accuracy: 0.7921 - val_loss: 0.5687 - val_accuracy: 0.7050 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41284563583500145
Confusion Matrix :
 [[2909 1139]
 [1238 2809]]
Accuracy on test set:    0.7063619518221124
Sensitivity:    0.6940943909068445 	 Specificity:    0.7186264822134387
Precision  : 0.711499493414387
Area Under Curve:    0.7063604365601417
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5880 - accuracy: 0.6860 - val_loss: 0.5505 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7238 - val_loss: 0.5431 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7338 - val_loss: 0.5416 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7408 - val_loss: 0.5407 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7476 - val_loss: 0.5405 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7558 - val_loss: 0.5396 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7630 - val_loss: 0.5456 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4760 - accuracy: 0.7716 - val_loss: 0.5421 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4631 - accuracy: 0.7806 - val_loss: 0.5500 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4515 - accuracy: 0.7878 - val_loss: 0.5492 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4413 - accuracy: 0.7948 - val_loss: 0.5585 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4283 - accuracy: 0.8028 - val_loss: 0.5733 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 13/400
256/257 [============================>.] - ETA: 0s - loss: 0.4182 - accuracy: 0.8090
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4182 - accuracy: 0.8090 - val_loss: 0.5838 - val_accuracy: 0.7213 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.420410706444507
Confusion Matrix :
 [[2660 1387]
 [ 968 3080]]
Accuracy on test set:    0.7090796788140827
Sensitivity:    0.7608695652173914 	 Specificity:    0.6572769953051644
Precision  : 0.6895007835236177
Area Under Curve:    0.7090732802612778
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5865 - accuracy: 0.6839 - val_loss: 0.5474 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5416 - accuracy: 0.7258 - val_loss: 0.5427 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7333 - val_loss: 0.5377 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7445 - val_loss: 0.5371 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7508 - val_loss: 0.5354 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4927 - accuracy: 0.7603 - val_loss: 0.5406 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7695 - val_loss: 0.5403 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7759 - val_loss: 0.5482 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4548 - accuracy: 0.7834 - val_loss: 0.5494 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4417 - accuracy: 0.7937 - val_loss: 0.5570 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4282 - accuracy: 0.8012
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4286 - accuracy: 0.8010 - val_loss: 0.5648 - val_accuracy: 0.7197 - lr: 0.0010

253/253 [==============================] - 0s 825us/step
Independent Testing Matthews Correlation:  0.4043229066458983
Confusion Matrix :
 [[2770 1277]
 [1135 2913]]
Accuracy on test set:    0.7020382952439778
Sensitivity:    0.7196146245059288 	 Specificity:    0.6844576229305659
Precision  : 0.6952267303102625
Area Under Curve:    0.7020361237182474
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5916 - accuracy: 0.6794 - val_loss: 0.5634 - val_accuracy: 0.7008 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7203 - val_loss: 0.5441 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7330 - val_loss: 0.5445 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7439 - val_loss: 0.5454 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7514 - val_loss: 0.5447 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7590 - val_loss: 0.5488 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4819 - accuracy: 0.7686
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7682 - val_loss: 0.5484 - val_accuracy: 0.7141 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43244800875426515
Confusion Matrix :
 [[2798 1249]
 [1050 2997]]
Accuracy on test set:    0.715962441314554
Sensitivity:    0.7405485544848036 	 Specificity:    0.6913763281443044
Precision  : 0.7058407913330194
Area Under Curve:    0.7159624413145539
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5873 - accuracy: 0.6844 - val_loss: 0.5581 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7225 - val_loss: 0.5484 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7334 - val_loss: 0.5437 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7416 - val_loss: 0.5419 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7490 - val_loss: 0.5479 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7586 - val_loss: 0.5494 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4825 - accuracy: 0.7670 - val_loss: 0.5463 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4706 - accuracy: 0.7740
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7740 - val_loss: 0.5520 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43911213358473616
Confusion Matrix :
 [[2932 1115]
 [1155 2892]]
Accuracy on test set:    0.7195453422288115
Sensitivity:    0.7146034099332839 	 Specificity:    0.724487274524339
Precision  : 0.721736960319441
Area Under Curve:    0.7195453422288115
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5907 - accuracy: 0.6806 - val_loss: 0.5520 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7226 - val_loss: 0.5496 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7299 - val_loss: 0.5548 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7403 - val_loss: 0.5429 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7498 - val_loss: 0.5450 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7576 - val_loss: 0.5478 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7651 - val_loss: 0.5477 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4726 - accuracy: 0.7732 - val_loss: 0.5624 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4588 - accuracy: 0.7819 - val_loss: 0.5601 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4441 - accuracy: 0.7916
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4447 - accuracy: 0.7912 - val_loss: 0.5689 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43404674597771464
Confusion Matrix :
 [[2815 1232]
 [1060 2987]]
Accuracy on test set:    0.7168272794662713
Sensitivity:    0.7380775883370397 	 Specificity:    0.6955769705955028
Precision  : 0.707987674804456
Area Under Curve:    0.7168272794662712
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5903 - accuracy: 0.6825 - val_loss: 0.5528 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7238 - val_loss: 0.5468 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7321 - val_loss: 0.5390 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5210 - accuracy: 0.7398 - val_loss: 0.5393 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7488 - val_loss: 0.5392 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4994 - accuracy: 0.7546 - val_loss: 0.5410 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7636 - val_loss: 0.5403 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7729 - val_loss: 0.5426 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4611 - accuracy: 0.7794 - val_loss: 0.5505 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4500 - accuracy: 0.7878 - val_loss: 0.5581 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4400 - accuracy: 0.7927
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4401 - accuracy: 0.7927 - val_loss: 0.5590 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 903us/step
Independent Testing Matthews Correlation:  0.434326704304478
Confusion Matrix :
 [[2991 1056]
 [1235 2812]]
Accuracy on test set:    0.7169508277736595
Sensitivity:    0.6948356807511737 	 Specificity:    0.7390659747961453
Precision  : 0.7269906928645294
Area Under Curve:    0.7169508277736595
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5877 - accuracy: 0.6851 - val_loss: 0.5528 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7205 - val_loss: 0.5478 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7328 - val_loss: 0.5437 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7408 - val_loss: 0.5425 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7486 - val_loss: 0.5536 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7587 - val_loss: 0.5463 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7666 - val_loss: 0.5601 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4684 - accuracy: 0.7769
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4686 - accuracy: 0.7770 - val_loss: 0.5530 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44795190184016087
Confusion Matrix :
 [[3060  987]
 [1251 2796]]
Accuracy on test set:    0.7234988880652335
Sensitivity:    0.6908821349147517 	 Specificity:    0.7561156412157154
Precision  : 0.739095955590801
Area Under Curve:    0.7234988880652334
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5908 - accuracy: 0.6832 - val_loss: 0.5544 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5491 - accuracy: 0.7208 - val_loss: 0.5440 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5351 - accuracy: 0.7312 - val_loss: 0.5428 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5231 - accuracy: 0.7396 - val_loss: 0.5433 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7461 - val_loss: 0.5481 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5043 - accuracy: 0.7535 - val_loss: 0.5477 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4924 - accuracy: 0.7604 - val_loss: 0.5499 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4817 - accuracy: 0.7692 - val_loss: 0.5463 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4693 - accuracy: 0.7765
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4692 - accuracy: 0.7765 - val_loss: 0.5552 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4928581392966524
Confusion Matrix :
 [[3070  977]
 [1076 2971]]
Accuracy on test set:    0.7463553249320485
Sensitivity:    0.7341240425006177 	 Specificity:    0.7585866073634792
Precision  : 0.752532928064843
Area Under Curve:    0.7463553249320485
(8094, 2560) (8094,)
Mean MCC = 0.4337 + 0.0233 and Mean AUC = 0.7165 + 0.0118
Mean Sensitivity = 0.7251 + 0.0253 and Mean Specificity = 0.7079 + 0.0358 and Mean Accuracy = 0.7165 + 0.0118
Mean Precision = 0.7138 + 0.0203





Seed   : 938278
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5851 - accuracy: 0.6860 - val_loss: 0.5598 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5415 - accuracy: 0.7253 - val_loss: 0.5539 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5249 - accuracy: 0.7380 - val_loss: 0.5501 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5128 - accuracy: 0.7446 - val_loss: 0.5521 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7568 - val_loss: 0.5552 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 6/400
255/257 [============================>.] - ETA: 0s - loss: 0.4872 - accuracy: 0.7645
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4872 - accuracy: 0.7644 - val_loss: 0.5553 - val_accuracy: 0.7087 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4162676276399407
Confusion Matrix :
 [[2826 1222]
 [1141 2906]]
Accuracy on test set:    0.7080914144533663
Sensitivity:    0.7180627625401532 	 Specificity:    0.6981225296442688
Precision  : 0.7039728682170543
Area Under Curve:    0.708092646092211
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5846 - accuracy: 0.6848 - val_loss: 0.5558 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5417 - accuracy: 0.7239 - val_loss: 0.5576 - val_accuracy: 0.7017 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5258 - accuracy: 0.7359 - val_loss: 0.5504 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5138 - accuracy: 0.7433 - val_loss: 0.5549 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7532 - val_loss: 0.5479 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4905 - accuracy: 0.7599 - val_loss: 0.5501 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4778 - accuracy: 0.7697 - val_loss: 0.5530 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4664 - accuracy: 0.7782 - val_loss: 0.5581 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4547 - accuracy: 0.7861 - val_loss: 0.5637 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7939 - val_loss: 0.5799 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4314 - accuracy: 0.7988 - val_loss: 0.5869 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4187 - accuracy: 0.8088 - val_loss: 0.5750 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 13/400
252/257 [============================>.] - ETA: 0s - loss: 0.4083 - accuracy: 0.8137
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4081 - accuracy: 0.8139 - val_loss: 0.5835 - val_accuracy: 0.7073 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4033384260794398
Confusion Matrix :
 [[2833 1215]
 [1200 2847]]
Accuracy on test set:    0.701667696108709
Sensitivity:    0.7034840622683469 	 Specificity:    0.6998517786561265
Precision  : 0.7008862629246676
Area Under Curve:    0.7016679204622367
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5895 - accuracy: 0.6816 - val_loss: 0.5534 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400

257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7224 - val_loss: 0.5459 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7319 - val_loss: 0.5426 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7398 - val_loss: 0.5432 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7460 - val_loss: 0.5455 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7554 - val_loss: 0.5440 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4903 - accuracy: 0.7613 - val_loss: 0.5506 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7691 - val_loss: 0.5514 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4700 - accuracy: 0.7752
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4700 - accuracy: 0.7752 - val_loss: 0.5579 - val_accuracy: 0.7148 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.419921953265664
Confusion Matrix :
 [[2994 1053]
 [1298 2750]]
Accuracy on test set:    0.7095738109944411
Sensitivity:    0.6793478260869565 	 Specificity:    0.7398072646404744
Precision  : 0.7231133315803313
Area Under Curve:    0.7095775453637154
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5845 - accuracy: 0.6866 - val_loss: 0.5468 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5413 - accuracy: 0.7258 - val_loss: 0.5478 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7331 - val_loss: 0.5396 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5150 - accuracy: 0.7428 - val_loss: 0.5389 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7514 - val_loss: 0.5549 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 6/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4941 - accuracy: 0.7597
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7597 - val_loss: 0.5448 - val_accuracy: 0.7134 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4038399351600329
Confusion Matrix :
 [[2738 1309]
 [1106 2942]]
Accuracy on test set:    0.701667696108709
Sensitivity:    0.7267786561264822 	 Specificity:    0.6765505312577218
Precision  : 0.6920724535403434
Area Under Curve:    0.701664593692102
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5878 - accuracy: 0.6828 - val_loss: 0.5485 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7228 - val_loss: 0.5413 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7327 - val_loss: 0.5387 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7433 - val_loss: 0.5358 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7495 - val_loss: 0.5405 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7571 - val_loss: 0.5400 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4830 - accuracy: 0.7654 - val_loss: 0.5395 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4716 - accuracy: 0.7748 - val_loss: 0.5473 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4602 - accuracy: 0.7836
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4602 - accuracy: 0.7836 - val_loss: 0.5460 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42623187859147843
Confusion Matrix :
 [[2766 1281]
 [1044 3003]]
Accuracy on test set:    0.712750185322461
Sensitivity:    0.7420311341734618 	 Specificity:    0.6834692364714603
Precision  : 0.7009803921568627
Area Under Curve:    0.7127501853224609
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5842 - accuracy: 0.6863 - val_loss: 0.5478 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7228 - val_loss: 0.5433 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7340 - val_loss: 0.5514 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7418 - val_loss: 0.5425 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7492 - val_loss: 0.5435 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7571 - val_loss: 0.5455 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4856 - accuracy: 0.7650
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7650 - val_loss: 0.5466 - val_accuracy: 0.7244 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.427784602136899
Confusion Matrix :
 [[2991 1056]
 [1262 2785]]
Accuracy on test set:    0.7136150234741784
Sensitivity:    0.6881640721522115 	 Specificity:    0.7390659747961453
Precision  : 0.7250715959385576
Area Under Curve:    0.7136150234741784
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5863 - accuracy: 0.6856 - val_loss: 0.5497 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7230 - val_loss: 0.5420 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7327 - val_loss: 0.5383 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7403 - val_loss: 0.5407 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7486 - val_loss: 0.5425 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7563 - val_loss: 0.5440 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4857 - accuracy: 0.7644
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4863 - accuracy: 0.7642 - val_loss: 0.5412 - val_accuracy: 0.7207 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44125218706104147
Confusion Matrix :
 [[2826 1221]
 [1042 3005]]
Accuracy on test set:    0.7204101803805288
Sensitivity:    0.7425253274030146 	 Specificity:    0.698295033358043
Precision  : 0.7110743019403691
Area Under Curve:    0.7204101803805288
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5907 - accuracy: 0.6790 - val_loss: 0.5497 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7213 - val_loss: 0.5418 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7319 - val_loss: 0.5395 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7399 - val_loss: 0.5417 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7492 - val_loss: 0.5383 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7591 - val_loss: 0.5412 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4826 - accuracy: 0.7666
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.7664 - val_loss: 0.5423 - val_accuracy: 0.7202 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43777817711937067
Confusion Matrix :
 [[3038 1009]
 [1270 2777]]
Accuracy on test set:    0.7184334074623178
Sensitivity:    0.6861872992340005 	 Specificity:    0.7506795156906351
Precision  : 0.7334918119387216
Area Under Curve:    0.7184334074623178
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5906 - accuracy: 0.6801 - val_loss: 0.5486 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5491 - accuracy: 0.7181 - val_loss: 0.5419 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7315 - val_loss: 0.5405 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5220 - accuracy: 0.7406 - val_loss: 0.5400 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5103 - accuracy: 0.7481 - val_loss: 0.5386 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7545 - val_loss: 0.5405 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7645 - val_loss: 0.5420 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7743 - val_loss: 0.5439 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4589 - accuracy: 0.7821 - val_loss: 0.5520 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4453 - accuracy: 0.7903 - val_loss: 0.5561 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4326 - accuracy: 0.8003 - val_loss: 0.5625 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4195 - accuracy: 0.8083 - val_loss: 0.5662 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4044 - accuracy: 0.8155 - val_loss: 0.5768 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 14/400
253/257 [============================>.] - ETA: 0s - loss: 0.3938 - accuracy: 0.8207
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3941 - accuracy: 0.8205 - val_loss: 0.5769 - val_accuracy: 0.7179 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4370012852364863
Confusion Matrix :
 [[3015 1032]
 [1249 2798]]
Accuracy on test set:    0.7181863108475414
Sensitivity:    0.6913763281443044 	 Specificity:    0.7449962935507783
Precision  : 0.7305483028720626
Area Under Curve:    0.7181863108475414
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5927 - accuracy: 0.6791 - val_loss: 0.5626 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7203 - val_loss: 0.5479 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5336 - accuracy: 0.7310 - val_loss: 0.5455 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5232 - accuracy: 0.7381 - val_loss: 0.5486 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5122 - accuracy: 0.7463 - val_loss: 0.5454 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7540 - val_loss: 0.5491 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4896 - accuracy: 0.7628 - val_loss: 0.5516 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4786 - accuracy: 0.7684
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7684 - val_loss: 0.5502 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 966us/step
Independent Testing Matthews Correlation:  0.4753337938582211
Confusion Matrix :
 [[3124  923]
 [1205 2842]]
Accuracy on test set:    0.7370892018779343
Sensitivity:    0.702248579194465 	 Specificity:    0.7719298245614035
Precision  : 0.7548472775564409
Area Under Curve:    0.7370892018779343
(8094, 2560) (8094,)
Mean MCC = 0.4289 + 0.0200 and Mean AUC = 0.7141 + 0.0099
Mean Sensitivity = 0.7080 + 0.0220 and Mean Specificity = 0.7203 + 0.0310 and Mean Accuracy = 0.7141 + 0.0099
Mean Precision = 0.7176 + 0.0182





Seed   : 473026
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5932 - accuracy: 0.6802 - val_loss: 0.5603 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7252 - val_loss: 0.5475 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7330 - val_loss: 0.5460 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7398 - val_loss: 0.5446 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7489 - val_loss: 0.5496 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.7560 - val_loss: 0.5509 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4891 - accuracy: 0.7635 - val_loss: 0.5527 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7704 - val_loss: 0.5461 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4675 - accuracy: 0.7798 - val_loss: 0.5523 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4560 - accuracy: 0.7857
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4561 - accuracy: 0.7856 - val_loss: 0.5536 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.41324437393070335
Confusion Matrix :
 [[2838 1210]
 [1165 2882]]
Accuracy on test set:    0.7066090179122916
Sensitivity:    0.7121324437855201 	 Specificity:    0.7010869565217391
Precision  : 0.7043010752688172
Area Under Curve:    0.7066097001536296
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5871 - accuracy: 0.6844 - val_loss: 0.5532 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7225 - val_loss: 0.5507 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7339 - val_loss: 0.5445 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7417 - val_loss: 0.5456 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7484 - val_loss: 0.5595 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7580 - val_loss: 0.5478 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7664 - val_loss: 0.5459 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7746 - val_loss: 0.5576 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.7840 - val_loss: 0.5635 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4448 - accuracy: 0.7916 - val_loss: 0.5666 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4335 - accuracy: 0.8000 - val_loss: 0.5692 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4195 - accuracy: 0.8067
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4201 - accuracy: 0.8067 - val_loss: 0.5883 - val_accuracy: 0.7073 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41187900333270405
Confusion Matrix :
 [[2457 1591]
 [ 820 3227]]
Accuracy on test set:    0.7021618282890674
Sensitivity:    0.7973807758833704 	 Specificity:    0.6069664031620553
Precision  : 0.6697799916977999
Area Under Curve:    0.702173589522713
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5899 - accuracy: 0.6832 - val_loss: 0.5512 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7212 - val_loss: 0.5446 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7324 - val_loss: 0.5371 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7404 - val_loss: 0.5361 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7499 - val_loss: 0.5392 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7570 - val_loss: 0.5346 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7656 - val_loss: 0.5379 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4732 - accuracy: 0.7730 - val_loss: 0.5406 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4602 - accuracy: 0.7828 - val_loss: 0.5530 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4487 - accuracy: 0.7907 - val_loss: 0.5447 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4343 - accuracy: 0.7988
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4341 - accuracy: 0.7990 - val_loss: 0.5588 - val_accuracy: 0.7222 - lr: 0.0010
253/253 [==============================] - 0s 913us/step
Independent Testing Matthews Correlation:  0.42693593211309466
Confusion Matrix :
 [[2756 1291]
 [1032 3016]]
Accuracy on test set:    0.7130327362569487
Sensitivity:    0.7450592885375494 	 Specificity:    0.6809982703236965
Precision  : 0.7002553981889946
Area Under Curve:    0.7130287794306229
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5868 - accuracy: 0.6841 - val_loss: 0.5456 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7225 - val_loss: 0.5403 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7327 - val_loss: 0.5345 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7403 - val_loss: 0.5362 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7498 - val_loss: 0.5325 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7566 - val_loss: 0.5348 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7662 - val_loss: 0.5366 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7742 - val_loss: 0.5395 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4556 - accuracy: 0.7851 - val_loss: 0.5455 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4425 - accuracy: 0.7922
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4429 - accuracy: 0.7918 - val_loss: 0.5474 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42443350525351076
Confusion Matrix :
 [[2753 1294]
 [1039 3009]]
Accuracy on test set:    0.7117974058060531
Sensitivity:    0.7433300395256917 	 Specificity:    0.6802569804793674
Precision  : 0.6992795723913549
Area Under Curve:    0.7117935100025296
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5858 - accuracy: 0.6859 - val_loss: 0.5472 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7231 - val_loss: 0.5383 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7317 - val_loss: 0.5376 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7396 - val_loss: 0.5428 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5131 - accuracy: 0.7432 - val_loss: 0.5358 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7530 - val_loss: 0.5409 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7613 - val_loss: 0.5399 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4792 - accuracy: 0.7684 - val_loss: 0.5420 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4689 - accuracy: 0.7762 - val_loss: 0.5436 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4584 - accuracy: 0.7844
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4587 - accuracy: 0.7842 - val_loss: 0.5517 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 768us/step
Independent Testing Matthews Correlation:  0.41651040305229853
Confusion Matrix :
 [[2732 1315]
 [1050 2997]]
Accuracy on test set:    0.7078082530269335
Sensitivity:    0.7405485544848036 	 Specificity:    0.6750679515690635
Precision  : 0.6950371057513914
Area Under Curve:    0.7078082530269336
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5891 - accuracy: 0.6815 - val_loss: 0.5484 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7206 - val_loss: 0.5448 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5331 - accuracy: 0.7315 - val_loss: 0.5378 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7412 - val_loss: 0.5368 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5105 - accuracy: 0.7480 - val_loss: 0.5368 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7556 - val_loss: 0.5397 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4876 - accuracy: 0.7631 - val_loss: 0.5462 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4751 - accuracy: 0.7743
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4750 - accuracy: 0.7746 - val_loss: 0.5404 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4259983223458151
Confusion Matrix :
 [[2877 1170]
 [1153 2894]]
Accuracy on test set:    0.7129972819372374
Sensitivity:    0.7150976031628367 	 Specificity:    0.7108969607116382
Precision  : 0.7121062992125984
Area Under Curve:    0.7129972819372374
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5884 - accuracy: 0.6841 - val_loss: 0.5490 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7221 - val_loss: 0.5436 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7317 - val_loss: 0.5383 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7411 - val_loss: 0.5375 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7480 - val_loss: 0.5404 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4994 - accuracy: 0.7561 - val_loss: 0.5431 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7635 - val_loss: 0.5472 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4745 - accuracy: 0.7729
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7728 - val_loss: 0.5493 - val_accuracy: 0.7242 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4218936738106377
Confusion Matrix :
 [[2833 1214]
 [1126 2921]]
Accuracy on test set:    0.7108969607116382
Sensitivity:    0.7217692117617989 	 Specificity:    0.7000247096614777
Precision  : 0.7064087061668682
Area Under Curve:    0.7108969607116381
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5871 - accuracy: 0.6853 - val_loss: 0.5471 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7208 - val_loss: 0.5378 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7349 - val_loss: 0.5378 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7408 - val_loss: 0.5360 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7498 - val_loss: 0.5352 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7575 - val_loss: 0.5396 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7629 - val_loss: 0.5366 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4773 - accuracy: 0.7720 - val_loss: 0.5410 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4640 - accuracy: 0.7798 - val_loss: 0.5394 - val_accuracy: 0.7315 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4541 - accuracy: 0.7862 - val_loss: 0.5443 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4420 - accuracy: 0.7942 - val_loss: 0.5500 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4277 - accuracy: 0.8027
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4280 - accuracy: 0.8026 - val_loss: 0.5567 - val_accuracy: 0.7281 - lr: 0.0010
253/253 [==============================] - 0s 934us/step
Independent Testing Matthews Correlation:  0.45468281822033296
Confusion Matrix :
 [[2873 1174]
 [1034 3013]]
Accuracy on test set:    0.7272053372868792
Sensitivity:    0.7445021003212255 	 Specificity:    0.7099085742525327
Precision  : 0.719608311440172
Area Under Curve:    0.7272053372868791
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5928 - accuracy: 0.6811 - val_loss: 0.5482 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7221 - val_loss: 0.5410 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7301 - val_loss: 0.5392 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7419 - val_loss: 0.5460 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7495 - val_loss: 0.5388 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7580 - val_loss: 0.5395 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4830 - accuracy: 0.7659 - val_loss: 0.5444 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4698 - accuracy: 0.7761 - val_loss: 0.5454 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4581 - accuracy: 0.7827 - val_loss: 0.5552 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4457 - accuracy: 0.7905 - val_loss: 0.5524 - val_accuracy: 0.7216 - lr: 0.0010

Epoch 11/400
254/257 [============================>.] - ETA: 0s - loss: 0.4332 - accuracy: 0.7979
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4333 - accuracy: 0.7980 - val_loss: 0.5602 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 759us/step
Independent Testing Matthews Correlation:  0.4535264818101974
Confusion Matrix :
 [[3063  984]
 [1231 2816]]
Accuracy on test set:    0.7263404991351619
Sensitivity:    0.6958240672102792 	 Specificity:    0.7568569310600445
Precision  : 0.7410526315789474
Area Under Curve:    0.7263404991351619
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5913 - accuracy: 0.6841 - val_loss: 0.5507 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5496 - accuracy: 0.7195 - val_loss: 0.5453 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5365 - accuracy: 0.7297 - val_loss: 0.5471 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5252 - accuracy: 0.7370 - val_loss: 0.5468 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7460 - val_loss: 0.5429 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7518 - val_loss: 0.5431 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
252/257 [============================>.] - ETA: 0s - loss: 0.4954 - accuracy: 0.7572
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7574 - val_loss: 0.5514 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.48293331639915965
Confusion Matrix :
 [[2958 1089]
 [1004 3043]]
Accuracy on test set:    0.7414133926365208
Sensitivity:    0.751914998764517 	 Specificity:    0.7309117865085248
Precision  : 0.7364472410454985
Area Under Curve:    0.741413392636521
(8094, 2560) (8094,)
Mean MCC = 0.4332 + 0.0219 and Mean AUC = 0.7160 + 0.0113
Mean Sensitivity = 0.7368 + 0.0266 and Mean Specificity = 0.6953 + 0.0377 and Mean Accuracy = 0.7160 + 0.0113
Mean Precision = 0.7084 + 0.0196





Seed   : 997427
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5845 - accuracy: 0.6881 - val_loss: 0.5614 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5416 - accuracy: 0.7260 - val_loss: 0.5530 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7358 - val_loss: 0.5516 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5154 - accuracy: 0.7436 - val_loss: 0.5486 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7525 - val_loss: 0.5460 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7593 - val_loss: 0.5534 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7700 - val_loss: 0.5536 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4697 - accuracy: 0.7764 - val_loss: 0.5597 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4590 - accuracy: 0.7840 - val_loss: 0.5695 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4425 - accuracy: 0.7955
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4433 - accuracy: 0.7951 - val_loss: 0.5671 - val_accuracy: 0.7082 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39612890905296105
Confusion Matrix :
 [[3034 1014]
 [1439 2608]]
Accuracy on test set:    0.6969734403953057
Sensitivity:    0.6444279713367926 	 Specificity:    0.7495059288537549
Precision  : 0.7200441744892324
Area Under Curve:    0.6969669500952738
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5845 - accuracy: 0.6881 - val_loss: 0.5620 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5415 - accuracy: 0.7264 - val_loss: 0.5548 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7345 - val_loss: 0.5499 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5137 - accuracy: 0.7450 - val_loss: 0.5539 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5024 - accuracy: 0.7534 - val_loss: 0.5488 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4903 - accuracy: 0.7620 - val_loss: 0.5478 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7714 - val_loss: 0.5519 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4667 - accuracy: 0.7802 - val_loss: 0.5496 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4537 - accuracy: 0.7881 - val_loss: 0.5582 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4432 - accuracy: 0.7944 - val_loss: 0.5588 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4299 - accuracy: 0.8021
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4304 - accuracy: 0.8018 - val_loss: 0.5609 - val_accuracy: 0.7112 - lr: 0.0010
253/253 [==============================] - 0s 857us/step
Independent Testing Matthews Correlation:  0.42663657433317614
Confusion Matrix :
 [[2662 1386]
 [ 945 3102]]
Accuracy on test set:    0.7120444718962322
Sensitivity:    0.7664936990363233 	 Specificity:    0.657608695652174
Precision  : 0.6911764705882353
Area Under Curve:    0.7120511973442485
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5945 - accuracy: 0.6774 - val_loss: 0.5549 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7217 - val_loss: 0.5455 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7313 - val_loss: 0.5427 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5213 - accuracy: 0.7380 - val_loss: 0.5414 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5126 - accuracy: 0.7453 - val_loss: 0.5411 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5020 - accuracy: 0.7535 - val_loss: 0.5411 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7585 - val_loss: 0.5428 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7671 - val_loss: 0.5480 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.7736 - val_loss: 0.5540 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4596 - accuracy: 0.7824
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4596 - accuracy: 0.7824 - val_loss: 0.5565 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 795us/step
Independent Testing Matthews Correlation:  0.42694646474831927
Confusion Matrix :
 [[2694 1353]
 [ 974 3074]]
Accuracy on test set:    0.7125386040765905
Sensitivity:    0.7593873517786561 	 Specificity:    0.6656782802075611
Precision  : 0.6943754235373842
Area Under Curve:    0.7125328159931087
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5884 - accuracy: 0.6845 - val_loss: 0.5520 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7232 - val_loss: 0.5437 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7334 - val_loss: 0.5399 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7398 - val_loss: 0.5400 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7488 - val_loss: 0.5439 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7539 - val_loss: 0.5416 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.7629 - val_loss: 0.5468 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4792 - accuracy: 0.7694
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4794 - accuracy: 0.7692 - val_loss: 0.5548 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4319972241159702
Confusion Matrix :
 [[2777 1270]
 [1032 3016]]
Accuracy on test set:    0.7156269302038295
Sensitivity:    0.7450592885375494 	 Specificity:    0.6861872992340005
Precision  : 0.703686420905273
Area Under Curve:    0.7156232938857751
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5922 - accuracy: 0.6804 - val_loss: 0.5577 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5482 - accuracy: 0.7212 - val_loss: 0.5499 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7314 - val_loss: 0.5524 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.7403 - val_loss: 0.5462 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7484 - val_loss: 0.5467 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.7560 - val_loss: 0.5473 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4867 - accuracy: 0.7643
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7639 - val_loss: 0.5542 - val_accuracy: 0.7170 - lr: 0.0010
253/253 [==============================] - 0s 789us/step
Independent Testing Matthews Correlation:  0.42112886393883425
Confusion Matrix :
 [[2837 1210]
 [1133 2914]]
Accuracy on test set:    0.7105263157894737
Sensitivity:    0.7200395354583642 	 Specificity:    0.7010130961205832
Precision  : 0.7065955383123181
Area Under Curve:    0.7105263157894737
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5831 - accuracy: 0.6867 - val_loss: 0.5540 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5406 - accuracy: 0.7263 - val_loss: 0.5490 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5255 - accuracy: 0.7364 - val_loss: 0.5450 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7452 - val_loss: 0.5455 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5019 - accuracy: 0.7538 - val_loss: 0.5452 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4918 - accuracy: 0.7608 - val_loss: 0.5445 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7699 - val_loss: 0.5514 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4668 - accuracy: 0.7777
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4675 - accuracy: 0.7772 - val_loss: 0.5595 - val_accuracy: 0.7170 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42144221889106803
Confusion Matrix :
 [[2646 1401]
 [ 951 3096]]
Accuracy on test set:    0.7094143810229799
Sensitivity:    0.765011119347665 	 Specificity:    0.653817642698295
Precision  : 0.6884589726484323
Area Under Curve:    0.7094143810229799
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5894 - accuracy: 0.6835 - val_loss: 0.5513 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7238 - val_loss: 0.5468 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7318 - val_loss: 0.5412 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7420 - val_loss: 0.5409 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7490 - val_loss: 0.5379 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7579 - val_loss: 0.5435 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7651 - val_loss: 0.5436 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7750 - val_loss: 0.5531 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4571 - accuracy: 0.7850 - val_loss: 0.5511 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4442 - accuracy: 0.7932
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4442 - accuracy: 0.7932 - val_loss: 0.5612 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4229113550516233
Confusion Matrix :
 [[2730 1317]
 [1023 3024]]
Accuracy on test set:    0.7108969607116382
Sensitivity:    0.7472201630837657 	 Specificity:    0.6745737583395107
Precision  : 0.6966136834830684
Area Under Curve:    0.7108969607116382
(8094, 2560) (8094,)
Epoch 1/400

257/257 [==============================] - 2s 5ms/step - loss: 0.5939 - accuracy: 0.6812 - val_loss: 0.5545 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5506 - accuracy: 0.7197 - val_loss: 0.5422 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5345 - accuracy: 0.7316 - val_loss: 0.5400 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5232 - accuracy: 0.7380 - val_loss: 0.5381 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5115 - accuracy: 0.7477 - val_loss: 0.5386 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4989 - accuracy: 0.7553 - val_loss: 0.5365 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4858 - accuracy: 0.7647 - val_loss: 0.5402 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7738 - val_loss: 0.5388 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4589 - accuracy: 0.7821 - val_loss: 0.5455 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4461 - accuracy: 0.7891 - val_loss: 0.5465 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4326 - accuracy: 0.7997
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4327 - accuracy: 0.7996 - val_loss: 0.5487 - val_accuracy: 0.7253 - lr: 0.0010
253/253 [==============================] - 0s 723us/step
Independent Testing Matthews Correlation:  0.43979136607367214
Confusion Matrix :
 [[2975 1072]
 [1196 2851]]
Accuracy on test set:    0.7197924388435878
Sensitivity:    0.7044724487274524 	 Specificity:    0.7351124289597233
Precision  : 0.7267397399949018
Area Under Curve:    0.7197924388435879
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5919 - accuracy: 0.6801 - val_loss: 0.5565 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.7214 - val_loss: 0.5459 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7329 - val_loss: 0.5405 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7407 - val_loss: 0.5520 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7483 - val_loss: 0.5430 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7571 - val_loss: 0.5422 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7648 - val_loss: 0.5436 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4718 - accuracy: 0.7742
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7737 - val_loss: 0.5458 - val_accuracy: 0.7251 - lr: 0.0010
253/253 [==============================] - 0s 943us/step
Independent Testing Matthews Correlation:  0.4524598682798721
Confusion Matrix :
 [[3035 1012]
 [1206 2841]]
Accuracy on test set:    0.7259698542129973
Sensitivity:    0.7020014825796886 	 Specificity:    0.7499382258463059
Precision  : 0.7373475214118869
Area Under Curve:    0.7259698542129973
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5934 - accuracy: 0.6812 - val_loss: 0.5534 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5506 - accuracy: 0.7205 - val_loss: 0.5446 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5364 - accuracy: 0.7297 - val_loss: 0.5417 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5246 - accuracy: 0.7381 - val_loss: 0.5417 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5154 - accuracy: 0.7450 - val_loss: 0.5411 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7530 - val_loss: 0.5458 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7607 - val_loss: 0.5470 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7675 - val_loss: 0.5471 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4688 - accuracy: 0.7776 - val_loss: 0.5494 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4552 - accuracy: 0.7880 - val_loss: 0.5523 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4420 - accuracy: 0.7933
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4424 - accuracy: 0.7930 - val_loss: 0.5572 - val_accuracy: 0.7154 - lr: 0.0010
253/253 [==============================] - 0s 753us/step
Independent Testing Matthews Correlation:  0.47738089203338846
Confusion Matrix :
 [[3117  930]
 [1189 2858]]
Accuracy on test set:    0.738201136644428
Sensitivity:    0.7062021250308871 	 Specificity:    0.7702001482579689
Precision  : 0.7544878563885956
Area Under Curve:    0.7382011366444281
(8094, 2560) (8094,)
Mean MCC = 0.4317 + 0.0205 and Mean AUC = 0.7152 + 0.0104
Mean Sensitivity = 0.7260 + 0.0363 and Mean Specificity = 0.7044 + 0.0411 and Mean Accuracy = 0.7152 + 0.0104
Mean Precision = 0.7120 + 0.0209





Seed   : 703218
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5877 - accuracy: 0.6857 - val_loss: 0.5579 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7219 - val_loss: 0.5489 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7335 - val_loss: 0.5459 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7416 - val_loss: 0.5482 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7477 - val_loss: 0.5498 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7536 - val_loss: 0.5498 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4902 - accuracy: 0.7604 - val_loss: 0.5613 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 8/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4806 - accuracy: 0.7680
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4803 - accuracy: 0.7682 - val_loss: 0.5582 - val_accuracy: 0.7124 - lr: 0.0010
253/253 [==============================] - 0s 891us/step
Independent Testing Matthews Correlation:  0.4160765757051531
Confusion Matrix :
 [[2919 1129]
 [1235 2812]]
Accuracy on test set:    0.7079678814082767
Sensitivity:    0.6948356807511737 	 Specificity:    0.7210968379446641
Precision  : 0.7135244861710226
Area Under Curve:    0.7079662593479189
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5945 - accuracy: 0.6785 - val_loss: 0.5601 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7220 - val_loss: 0.5483 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5327 - accuracy: 0.7315 - val_loss: 0.5489 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7389 - val_loss: 0.5494 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7482 - val_loss: 0.5467 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5006 - accuracy: 0.7559 - val_loss: 0.5497 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 7/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4888 - accuracy: 0.7639
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4892 - accuracy: 0.7637 - val_loss: 0.5569 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41629798487294073
Confusion Matrix :
 [[2605 1443]
 [ 933 3114]]
Accuracy on test set:    0.706485484867202
Sensitivity:    0.7694588584136397 	 Specificity:    0.6435276679841897
Precision  : 0.6833443054641212
Area Under Curve:    0.7064932631989147
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5885 - accuracy: 0.6835 - val_loss: 0.5443 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7227 - val_loss: 0.5416 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7321 - val_loss: 0.5347 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7412 - val_loss: 0.5373 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7496 - val_loss: 0.5352 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7597 - val_loss: 0.5411 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7685 - val_loss: 0.5454 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4661 - accuracy: 0.7777
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4656 - accuracy: 0.7777 - val_loss: 0.5423 - val_accuracy: 0.7202 - lr: 0.0010
253/253 [==============================] - 0s 933us/step
Independent Testing Matthews Correlation:  0.43227001563589035
Confusion Matrix :
 [[2825 1222]
 [1077 2971]]
Accuracy on test set:    0.7159975293390982
Sensitivity:    0.7339426877470355 	 Specificity:    0.6980479367432666
Precision  : 0.7085618888623897
Area Under Curve:    0.7159953122451511
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5878 - accuracy: 0.6858 - val_loss: 0.5438 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7207 - val_loss: 0.5386 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7333 - val_loss: 0.5329 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5211 - accuracy: 0.7414 - val_loss: 0.5341 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7474 - val_loss: 0.5299 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7573 - val_loss: 0.5381 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7653 - val_loss: 0.5351 - val_accuracy: 0.7353 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4708 - accuracy: 0.7730 - val_loss: 0.5365 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4581 - accuracy: 0.7826 - val_loss: 0.5443 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4458 - accuracy: 0.7892 - val_loss: 0.5444 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4342 - accuracy: 0.7964 - val_loss: 0.5533 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - ETA: 0s - loss: 0.4229 - accuracy: 0.8044
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4229 - accuracy: 0.8044 - val_loss: 0.5559 - val_accuracy: 0.7279 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4148717040559283
Confusion Matrix :
 [[2804 1243]
 [1126 2922]]
Accuracy on test set:    0.7073502161828289
Sensitivity:    0.7218379446640316 	 Specificity:    0.6928589078329627
Precision  : 0.7015606242496999
Area Under Curve:    0.7073484262484973
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5886 - accuracy: 0.6834 - val_loss: 0.5598 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7243 - val_loss: 0.5519 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7343 - val_loss: 0.5488 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7423 - val_loss: 0.5480 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7505 - val_loss: 0.5451 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7583 - val_loss: 0.5501 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7664 - val_loss: 0.5516 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7746 - val_loss: 0.5533 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4597 - accuracy: 0.7839 - val_loss: 0.5539 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4493 - accuracy: 0.7893 - val_loss: 0.5531 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4371 - accuracy: 0.7964 - val_loss: 0.5656 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4235 - accuracy: 0.8033 - val_loss: 0.5659 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4124 - accuracy: 0.8120 - val_loss: 0.5733 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4022 - accuracy: 0.8169 - val_loss: 0.5902 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 15/400
255/257 [============================>.] - ETA: 0s - loss: 0.3900 - accuracy: 0.8241
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3902 - accuracy: 0.8239 - val_loss: 0.5836 - val_accuracy: 0.7117 - lr: 0.0010

253/253 [==============================] - 0s 708us/step
Independent Testing Matthews Correlation:  0.4099753894957467
Confusion Matrix :
 [[2824 1223]
 [1165 2882]]
Accuracy on test set:    0.7049666419570052
Sensitivity:    0.7121324437855201 	 Specificity:    0.6978008401284902
Precision  : 0.7020706455542022
Area Under Curve:    0.7049666419570052
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5894 - accuracy: 0.6831 - val_loss: 0.5581 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7228 - val_loss: 0.5520 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7344 - val_loss: 0.5538 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7435 - val_loss: 0.5463 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7495 - val_loss: 0.5506 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7594 - val_loss: 0.5515 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7680 - val_loss: 0.5517 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4726 - accuracy: 0.7735 - val_loss: 0.5569 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4610 - accuracy: 0.7818 - val_loss: 0.5562 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4499 - accuracy: 0.7890
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4499 - accuracy: 0.7890 - val_loss: 0.5600 - val_accuracy: 0.7142 - lr: 0.0010
253/253 [==============================] - 0s 890us/step
Independent Testing Matthews Correlation:  0.4332367658827322
Confusion Matrix :
 [[2862 1185]
 [1109 2938]]
Accuracy on test set:    0.7165801828514949
Sensitivity:    0.7259698542129973 	 Specificity:    0.7071905114899926
Precision  : 0.7125879214164443
Area Under Curve:    0.7165801828514949
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5901 - accuracy: 0.6827 - val_loss: 0.5587 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7209 - val_loss: 0.5505 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7326 - val_loss: 0.5499 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5213 - accuracy: 0.7382 - val_loss: 0.5461 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5109 - accuracy: 0.7461 - val_loss: 0.5507 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.7538 - val_loss: 0.5497 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4909 - accuracy: 0.7615
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7615 - val_loss: 0.5543 - val_accuracy: 0.7170 - lr: 0.0010
253/253 [==============================] - 0s 730us/step
Independent Testing Matthews Correlation:  0.43728743830747774
Confusion Matrix :
 [[2851 1196]
 [1082 2965]]
Accuracy on test set:    0.7185569557697059
Sensitivity:    0.7326414628119595 	 Specificity:    0.7044724487274524
Precision  : 0.7125690939677962
Area Under Curve:    0.718556955769706
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5884 - accuracy: 0.6829 - val_loss: 0.5560 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7217 - val_loss: 0.5506 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7319 - val_loss: 0.5453 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7400 - val_loss: 0.5462 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7489 - val_loss: 0.5456 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7580 - val_loss: 0.5455 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7653 - val_loss: 0.5553 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4723 - accuracy: 0.7737 - val_loss: 0.5503 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4588 - accuracy: 0.7817 - val_loss: 0.5549 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4482 - accuracy: 0.7893 - val_loss: 0.5558 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4347 - accuracy: 0.7981 - val_loss: 0.5679 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4241 - accuracy: 0.8045 - val_loss: 0.5654 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4118 - accuracy: 0.8122 - val_loss: 0.5779 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3982 - accuracy: 0.8197 - val_loss: 0.5762 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3885 - accuracy: 0.8248 - val_loss: 0.5854 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 16/400
254/257 [============================>.] - ETA: 0s - loss: 0.3764 - accuracy: 0.8317
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3765 - accuracy: 0.8315 - val_loss: 0.6067 - val_accuracy: 0.7150 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4284797752376918
Confusion Matrix :
 [[2907 1140]
 [1173 2874]]
Accuracy on test set:    0.7142327650111193
Sensitivity:    0.7101556708673091 	 Specificity:    0.7183098591549296
Precision  : 0.7159940209267563
Area Under Curve:    0.7142327650111193
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5906 - accuracy: 0.6826 - val_loss: 0.5552 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7226 - val_loss: 0.5562 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7327 - val_loss: 0.5469 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7418 - val_loss: 0.5474 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7486 - val_loss: 0.5481 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7581 - val_loss: 0.5526 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7655 - val_loss: 0.5544 - val_accuracy: 0.7204 - lr: 0.0010

Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4714 - accuracy: 0.7752 - val_loss: 0.5664 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.7835 - val_loss: 0.5575 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4457 - accuracy: 0.7922 - val_loss: 0.5631 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4327 - accuracy: 0.7991 - val_loss: 0.5705 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4191 - accuracy: 0.8076 - val_loss: 0.5720 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4061 - accuracy: 0.8130 - val_loss: 0.5781 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 14/400
245/257 [===========================>..] - ETA: 0s - loss: 0.3934 - accuracy: 0.8190
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3936 - accuracy: 0.8192 - val_loss: 0.5868 - val_accuracy: 0.7120 - lr: 0.0010
253/253 [==============================] - 0s 818us/step
Independent Testing Matthews Correlation:  0.4450597918811374
Confusion Matrix :
 [[3022 1025]
 [1223 2824]]
Accuracy on test set:    0.7222634049913517
Sensitivity:    0.6978008401284902 	 Specificity:    0.746725969854213
Precision  : 0.7336970641725123
Area Under Curve:    0.7222634049913517
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5945 - accuracy: 0.6793 - val_loss: 0.5617 - val_accuracy: 0.7036 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5488 - accuracy: 0.7201 - val_loss: 0.5560 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7313 - val_loss: 0.5532 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.7393 - val_loss: 0.5508 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7488 - val_loss: 0.5487 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7581 - val_loss: 0.5550 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.7684 - val_loss: 0.5568 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4697 - accuracy: 0.7774 - val_loss: 0.5558 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4585 - accuracy: 0.7842 - val_loss: 0.5618 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4443 - accuracy: 0.7930 - val_loss: 0.5676 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4298 - accuracy: 0.8018 - val_loss: 0.5672 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 12/400
254/257 [============================>.] - ETA: 0s - loss: 0.4179 - accuracy: 0.8114
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4181 - accuracy: 0.8112 - val_loss: 0.5882 - val_accuracy: 0.7172 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4596539581872231
Confusion Matrix :
 [[3071  976]
 [1214 2833]]
Accuracy on test set:    0.7294292068198666
Sensitivity:    0.7000247096614777 	 Specificity:    0.7588337039782554
Precision  : 0.7437647676555527
Area Under Curve:    0.7294292068198666
(8094, 2560) (8094,)
Mean MCC = 0.4293 + 0.0148 and Mean AUC = 0.7144 + 0.0074
Mean Sensitivity = 0.7199 + 0.0213 and Mean Specificity = 0.7089 + 0.0299 and Mean Accuracy = 0.7144 + 0.0074
Mean Precision = 0.7128 + 0.0159





Seed   : 982550
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5798 - accuracy: 0.6914 - val_loss: 0.5636 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5389 - accuracy: 0.7277 - val_loss: 0.5562 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5234 - accuracy: 0.7374 - val_loss: 0.5537 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5110 - accuracy: 0.7454 - val_loss: 0.5531 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7552 - val_loss: 0.5565 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4891 - accuracy: 0.7629 - val_loss: 0.5563 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4778 - accuracy: 0.7712 - val_loss: 0.5560 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.7787 - val_loss: 0.5686 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4532 - accuracy: 0.7870 - val_loss: 0.5616 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4397 - accuracy: 0.7954 - val_loss: 0.5805 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4256 - accuracy: 0.8044 - val_loss: 0.5771 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4130 - accuracy: 0.8118 - val_loss: 0.5937 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 13/400
251/257 [============================>.] - ETA: 0s - loss: 0.3999 - accuracy: 0.8195
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4002 - accuracy: 0.8194 - val_loss: 0.5998 - val_accuracy: 0.7039 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3756082273209922
Confusion Matrix :
 [[2849 1199]
 [1329 2718]]
Accuracy on test set:    0.6877084620135886
Sensitivity:    0.6716085989621943 	 Specificity:    0.7038043478260869
Precision  : 0.6938983916262446
Area Under Curve:    0.6877064733941406
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5857 - accuracy: 0.6876 - val_loss: 0.5609 - val_accuracy: 0.7034 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5422 - accuracy: 0.7256 - val_loss: 0.5486 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5257 - accuracy: 0.7360 - val_loss: 0.5518 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5140 - accuracy: 0.7437 - val_loss: 0.5512 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7507 - val_loss: 0.5507 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4908 - accuracy: 0.7634 - val_loss: 0.5499 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4792 - accuracy: 0.7665 - val_loss: 0.5584 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4664 - accuracy: 0.7763 - val_loss: 0.5622 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4532 - accuracy: 0.7855 - val_loss: 0.5613 - val_accuracy: 0.7098 - lr: 0.0010

Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4410 - accuracy: 0.7936
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4410 - accuracy: 0.7935 - val_loss: 0.5703 - val_accuracy: 0.7098 - lr: 0.0010
253/253 [==============================] - 0s 793us/step
Independent Testing Matthews Correlation:  0.41990091034743127
Confusion Matrix :
 [[2774 1274]
 [1076 2971]]
Accuracy on test set:    0.7096973440395306
Sensitivity:    0.7341240425006177 	 Specificity:    0.6852766798418972
Precision  : 0.6998822143698469
Area Under Curve:    0.7097003611712575
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5860 - accuracy: 0.6856 - val_loss: 0.5500 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7225 - val_loss: 0.5423 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7337 - val_loss: 0.5390 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7418 - val_loss: 0.5449 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7498 - val_loss: 0.5427 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7572 - val_loss: 0.5412 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4867 - accuracy: 0.7643
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7642 - val_loss: 0.5452 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4359672890759268
Confusion Matrix :
 [[2806 1241]
 [1044 3004]]
Accuracy on test set:    0.7177269919703521
Sensitivity:    0.7420948616600791 	 Specificity:    0.6933531010625155
Precision  : 0.7076560659599529
Area Under Curve:    0.7177239813612972
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5874 - accuracy: 0.6830 - val_loss: 0.5478 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7229 - val_loss: 0.5506 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7333 - val_loss: 0.5446 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7413 - val_loss: 0.5379 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7495 - val_loss: 0.5357 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7574 - val_loss: 0.5412 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7647 - val_loss: 0.5381 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4727 - accuracy: 0.7731 - val_loss: 0.5459 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.7811 - val_loss: 0.5510 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4474 - accuracy: 0.7886 - val_loss: 0.5503 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4373 - accuracy: 0.7965 - val_loss: 0.5615 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 12/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4227 - accuracy: 0.8047
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4224 - accuracy: 0.8046 - val_loss: 0.5742 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41602968472896673
Confusion Matrix :
 [[2659 1388]
 [ 984 3064]]
Accuracy on test set:    0.7069796170475602
Sensitivity:    0.7569169960474308 	 Specificity:    0.657029898690388
Precision  : 0.688230008984726
Area Under Curve:    0.7069734473689093
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5850 - accuracy: 0.6848 - val_loss: 0.5548 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5420 - accuracy: 0.7248 - val_loss: 0.5477 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5253 - accuracy: 0.7355 - val_loss: 0.5482 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7431 - val_loss: 0.5444 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5027 - accuracy: 0.7513 - val_loss: 0.5500 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7585 - val_loss: 0.5505 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4827 - accuracy: 0.7665 - val_loss: 0.5553 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4714 - accuracy: 0.7733 - val_loss: 0.5554 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4606 - accuracy: 0.7818
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4604 - accuracy: 0.7819 - val_loss: 0.5610 - val_accuracy: 0.7149 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41333696121471725
Confusion Matrix :
 [[2975 1072]
 [1305 2742]]
Accuracy on test set:    0.7063256733382752
Sensitivity:    0.6775389177168273 	 Specificity:    0.7351124289597233
Precision  : 0.718930256948086
Area Under Curve:    0.7063256733382752
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5857 - accuracy: 0.6868 - val_loss: 0.5559 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7252 - val_loss: 0.5515 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7355 - val_loss: 0.5499 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7410 - val_loss: 0.5492 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7492 - val_loss: 0.5607 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.7562 - val_loss: 0.5499 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4857 - accuracy: 0.7640 - val_loss: 0.5578 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4754 - accuracy: 0.7714
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4752 - accuracy: 0.7715 - val_loss: 0.5620 - val_accuracy: 0.7152 - lr: 0.0010
253/253 [==============================] - 0s 853us/step
Independent Testing Matthews Correlation:  0.42797312852900765
Confusion Matrix :
 [[2958 1089]
 [1227 2820]]
Accuracy on test set:    0.7138621200889548
Sensitivity:    0.6968124536693847 	 Specificity:    0.7309117865085248
Precision  : 0.7214121258633922
Area Under Curve:    0.7138621200889548
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5868 - accuracy: 0.6845 - val_loss: 0.5532 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7250 - val_loss: 0.5451 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7351 - val_loss: 0.5424 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5137 - accuracy: 0.7436 - val_loss: 0.5446 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5028 - accuracy: 0.7526 - val_loss: 0.5434 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4907 - accuracy: 0.7602 - val_loss: 0.5443 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4779 - accuracy: 0.7689 - val_loss: 0.5484 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.7758 - val_loss: 0.5544 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4507 - accuracy: 0.7872 - val_loss: 0.5534 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4401 - accuracy: 0.7950 - val_loss: 0.5734 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4271 - accuracy: 0.8004
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4270 - accuracy: 0.8005 - val_loss: 0.5641 - val_accuracy: 0.7175 - lr: 0.0010
253/253 [==============================] - 0s 865us/step
Independent Testing Matthews Correlation:  0.4169411198081464
Confusion Matrix :
 [[2973 1074]
 [1288 2759]]
Accuracy on test set:    0.708178897949098
Sensitivity:    0.6817395601680257 	 Specificity:    0.7346182357301705
Precision  : 0.7198017218888599
Area Under Curve:    0.708178897949098
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5966 - accuracy: 0.6768 - val_loss: 0.5572 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5493 - accuracy: 0.7215 - val_loss: 0.5484 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5337 - accuracy: 0.7325 - val_loss: 0.5461 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5226 - accuracy: 0.7391 - val_loss: 0.5406 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5110 - accuracy: 0.7465 - val_loss: 0.5417 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7538 - val_loss: 0.5454 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4911 - accuracy: 0.7622 - val_loss: 0.5465 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4797 - accuracy: 0.7689 - val_loss: 0.5487 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4675 - accuracy: 0.7774
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.7775 - val_loss: 0.5542 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 724us/step
Independent Testing Matthews Correlation:  0.44440662664279573
Confusion Matrix :
 [[2839 1208]
 [1042 3005]]
Accuracy on test set:    0.7220163083765753
Sensitivity:    0.7425253274030146 	 Specificity:    0.701507289350136
Precision  : 0.7132684547828151
Area Under Curve:    0.7220163083765753
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5910 - accuracy: 0.6809 - val_loss: 0.5570 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5480 - accuracy: 0.7220 - val_loss: 0.5551 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7327 - val_loss: 0.5446 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5209 - accuracy: 0.7420 - val_loss: 0.5459 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7484 - val_loss: 0.5452 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4989 - accuracy: 0.7574 - val_loss: 0.5521 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7630 - val_loss: 0.5530 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4765 - accuracy: 0.7732 - val_loss: 0.5492 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4631 - accuracy: 0.7827 - val_loss: 0.5561 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 10/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4480 - accuracy: 0.7923
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4486 - accuracy: 0.7917 - val_loss: 0.5622 - val_accuracy: 0.7120 - lr: 0.0010
253/253 [==============================] - 0s 838us/step
Independent Testing Matthews Correlation:  0.46340789894162254
Confusion Matrix :
 [[3039 1008]
 [1165 2882]]
Accuracy on test set:    0.7315295280454658
Sensitivity:    0.7121324437855201 	 Specificity:    0.7509266123054115
Precision  : 0.7408740359897172
Area Under Curve:    0.7315295280454658
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5915 - accuracy: 0.6806 - val_loss: 0.5579 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7210 - val_loss: 0.5476 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5345 - accuracy: 0.7310 - val_loss: 0.5506 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5233 - accuracy: 0.7385 - val_loss: 0.5447 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5124 - accuracy: 0.7460 - val_loss: 0.5473 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5022 - accuracy: 0.7535 - val_loss: 0.5484 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4908 - accuracy: 0.7623 - val_loss: 0.5561 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7703 - val_loss: 0.5577 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4656 - accuracy: 0.7789
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4663 - accuracy: 0.7783 - val_loss: 0.5587 - val_accuracy: 0.7130 - lr: 0.0010
253/253 [==============================] - 0s 971us/step
Independent Testing Matthews Correlation:  0.47623479709435335
Confusion Matrix :
 [[3024 1023]
 [1097 2950]]
Accuracy on test set:    0.7380775883370397
Sensitivity:    0.7289350135903138 	 Specificity:    0.7472201630837657
Precision  : 0.7425119557009816
Area Under Curve:    0.7380775883370398
(8094, 2560) (8094,)
Mean MCC = 0.4290 + 0.0268 and Mean AUC = 0.7142 + 0.0135
Mean Sensitivity = 0.7144 + 0.0292 and Mean Specificity = 0.7140 + 0.0289 and Mean Accuracy = 0.7142 + 0.0135
Mean Precision = 0.7146 + 0.0172





Seed   : 761408

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5849 - accuracy: 0.6882 - val_loss: 0.5652 - val_accuracy: 0.7035 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5416 - accuracy: 0.7254 - val_loss: 0.5524 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7353 - val_loss: 0.5498 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7424 - val_loss: 0.5521 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7488 - val_loss: 0.5542 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.7550 - val_loss: 0.5528 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.7624 - val_loss: 0.5554 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7693 - val_loss: 0.5590 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4688 - accuracy: 0.7747 - val_loss: 0.5633 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4585 - accuracy: 0.7834 - val_loss: 0.5693 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4455 - accuracy: 0.7919 - val_loss: 0.5721 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4339 - accuracy: 0.7977 - val_loss: 0.5772 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 13/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4227 - accuracy: 0.8045
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4236 - accuracy: 0.8038 - val_loss: 0.5819 - val_accuracy: 0.7156 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3900019242310342
Confusion Matrix :
 [[2687 1361]
 [1111 2936]]
Accuracy on test set:    0.6946263125386041
Sensitivity:    0.7254756609834445 	 Specificity:    0.6637845849802372
Precision  : 0.683267395857575
Area Under Curve:    0.6946301229818409
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5857 - accuracy: 0.6855 - val_loss: 0.5606 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5413 - accuracy: 0.7252 - val_loss: 0.5523 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5258 - accuracy: 0.7364 - val_loss: 0.5482 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5139 - accuracy: 0.7438 - val_loss: 0.5504 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7518 - val_loss: 0.5480 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.7604 - val_loss: 0.5551 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7670 - val_loss: 0.5515 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.7750 - val_loss: 0.5540 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4591 - accuracy: 0.7832 - val_loss: 0.5559 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4451 - accuracy: 0.7901 - val_loss: 0.5683 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4338 - accuracy: 0.7987 - val_loss: 0.5627 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 12/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4201 - accuracy: 0.8071
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4206 - accuracy: 0.8070 - val_loss: 0.5751 - val_accuracy: 0.7126 - lr: 0.0010
253/253 [==============================] - 0s 844us/step
Independent Testing Matthews Correlation:  0.40979624760199657
Confusion Matrix :
 [[2778 1270]
 [1120 2927]]
Accuracy on test set:    0.7047560222359481
Sensitivity:    0.7232517914504571 	 Specificity:    0.6862648221343873
Precision  : 0.6974029068382178
Area Under Curve:    0.7047583067924222
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5829 - accuracy: 0.6888 - val_loss: 0.5483 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7236 - val_loss: 0.5424 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7350 - val_loss: 0.5397 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7406 - val_loss: 0.5415 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7492 - val_loss: 0.5422 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4980 - accuracy: 0.7561 - val_loss: 0.5501 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4871 - accuracy: 0.7636
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7634 - val_loss: 0.5473 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4318403693334765
Confusion Matrix :
 [[2721 1326]
 [ 980 3068]]
Accuracy on test set:    0.7151327980234713
Sensitivity:    0.7579051383399209 	 Specificity:    0.6723498888065234
Precision  : 0.6982248520710059
Area Under Curve:    0.7151275135732221
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5886 - accuracy: 0.6822 - val_loss: 0.5505 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7236 - val_loss: 0.5399 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7337 - val_loss: 0.5349 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7395 - val_loss: 0.5376 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7483 - val_loss: 0.5362 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7549 - val_loss: 0.5381 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4870 - accuracy: 0.7636
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.7636 - val_loss: 0.5463 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44156102084291465
Confusion Matrix :
 [[2650 1397]
 [ 878 3170]]
Accuracy on test set:    0.7189623224212477
Sensitivity:    0.783102766798419 	 Specificity:    0.6548060291574005
Precision  : 0.6941099189840158
Area Under Curve:    0.7189543979779096
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5851 - accuracy: 0.6853 - val_loss: 0.5467 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7209 - val_loss: 0.5395 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5261 - accuracy: 0.7360 - val_loss: 0.5365 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5143 - accuracy: 0.7431 - val_loss: 0.5369 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7524 - val_loss: 0.5398 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
254/257 [============================>.] - ETA: 0s - loss: 0.4921 - accuracy: 0.7581
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.7581 - val_loss: 0.5399 - val_accuracy: 0.7222 - lr: 0.0010
253/253 [==============================] - 0s 911us/step
Independent Testing Matthews Correlation:  0.4369197584300567
Confusion Matrix :
 [[2939 1108]
 [1171 2876]]
Accuracy on test set:    0.7184334074623178
Sensitivity:    0.7106498640968619 	 Specificity:    0.7262169508277737
Precision  : 0.7218875502008032
Area Under Curve:    0.7184334074623178
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5851 - accuracy: 0.6859 - val_loss: 0.5511 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7248 - val_loss: 0.5376 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7337 - val_loss: 0.5342 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7424 - val_loss: 0.5392 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.7463 - val_loss: 0.5350 - val_accuracy: 0.7311 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7562 - val_loss: 0.5421 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4873 - accuracy: 0.7633
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7633 - val_loss: 0.5446 - val_accuracy: 0.7283 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4230490486640741
Confusion Matrix :
 [[2860 1187]
 [1148 2899]]
Accuracy on test set:    0.7115147022485792
Sensitivity:    0.7163330862367185 	 Specificity:    0.7066963182604399
Precision  : 0.7094958394517866
Area Under Curve:    0.7115147022485792
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5855 - accuracy: 0.6851 - val_loss: 0.5411 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7235 - val_loss: 0.5467 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7332 - val_loss: 0.5343 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7424 - val_loss: 0.5321 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7522 - val_loss: 0.5343 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7595 - val_loss: 0.5406 - val_accuracy: 0.7304 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4801 - accuracy: 0.7686 - val_loss: 0.5413 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4672 - accuracy: 0.7755 - val_loss: 0.5403 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4569 - accuracy: 0.7851 - val_loss: 0.5500 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4434 - accuracy: 0.7924
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4434 - accuracy: 0.7925 - val_loss: 0.5442 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42344453466405274
Confusion Matrix :
 [[2937 1110]
 [1224 2823]]
Accuracy on test set:    0.7116382505559674
Sensitivity:    0.6975537435137139 	 Specificity:    0.7257227575982209
Precision  : 0.7177726926010679
Area Under Curve:    0.7116382505559673
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5880 - accuracy: 0.6832 - val_loss: 0.5411 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7210 - val_loss: 0.5363 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7329 - val_loss: 0.5307 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7415 - val_loss: 0.5324 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7509 - val_loss: 0.5363 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7598 - val_loss: 0.5327 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7664 - val_loss: 0.5361 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4684 - accuracy: 0.7756 - val_loss: 0.5405 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4543 - accuracy: 0.7861 - val_loss: 0.5481 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4416 - accuracy: 0.7938 - val_loss: 0.5482 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4283 - accuracy: 0.8030
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4284 - accuracy: 0.8029 - val_loss: 0.5539 - val_accuracy: 0.7227 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4262416604892513
Confusion Matrix :
 [[2886 1161]
 [1161 2886]]
Accuracy on test set:    0.7131208302446257
Sensitivity:    0.7131208302446257 	 Specificity:    0.7131208302446257
Precision  : 0.7131208302446257
Area Under Curve:    0.7131208302446257
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5909 - accuracy: 0.6808 - val_loss: 0.5498 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5492 - accuracy: 0.7188 - val_loss: 0.5452 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7315 - val_loss: 0.5392 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7405 - val_loss: 0.5374 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7489 - val_loss: 0.5401 - val_accuracy: 0.7240 - lr: 0.0010

Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7584 - val_loss: 0.5424 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4830 - accuracy: 0.7650 - val_loss: 0.5403 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4708 - accuracy: 0.7741 - val_loss: 0.5513 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4589 - accuracy: 0.7829 - val_loss: 0.5572 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4449 - accuracy: 0.7894 - val_loss: 0.5560 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4310 - accuracy: 0.8001
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4309 - accuracy: 0.8002 - val_loss: 0.5616 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 975us/step
Independent Testing Matthews Correlation:  0.4563901783382597
Confusion Matrix :
 [[2940 1107]
 [1093 2954]]
Accuracy on test set:    0.7281937237459847
Sensitivity:    0.7299234000494194 	 Specificity:    0.72646404744255
Precision  : 0.7274070426003447
Area Under Curve:    0.7281937237459847
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5925 - accuracy: 0.6797 - val_loss: 0.5548 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5493 - accuracy: 0.7204 - val_loss: 0.5425 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5343 - accuracy: 0.7296 - val_loss: 0.5423 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5232 - accuracy: 0.7376 - val_loss: 0.5405 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5131 - accuracy: 0.7459 - val_loss: 0.5442 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7522 - val_loss: 0.5423 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7595 - val_loss: 0.5454 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7690 - val_loss: 0.5512 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4732 - accuracy: 0.7738
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4733 - accuracy: 0.7737 - val_loss: 0.5509 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4579169810501658
Confusion Matrix :
 [[3270  777]
 [1442 2605]]
Accuracy on test set:    0.7258463059056091
Sensitivity:    0.6436866814924636 	 Specificity:    0.8080059303187547
Precision  : 0.770254287403903
Area Under Curve:    0.7258463059056092
(8094, 2560) (8094,)
Mean MCC = 0.4297 + 0.0194 and Mean AUC = 0.7142 + 0.0093
Mean Sensitivity = 0.7201 + 0.0347 and Mean Specificity = 0.7083 + 0.0419 and Mean Accuracy = 0.7142 + 0.0093
Mean Precision = 0.7133 + 0.0230





Seed   : 542398
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5896 - accuracy: 0.6821 - val_loss: 0.5642 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7262 - val_loss: 0.5548 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5259 - accuracy: 0.7363 - val_loss: 0.5543 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5146 - accuracy: 0.7449 - val_loss: 0.5540 - val_accuracy: 0.7027 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5028 - accuracy: 0.7525 - val_loss: 0.5596 - val_accuracy: 0.7036 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7603 - val_loss: 0.5596 - val_accuracy: 0.7025 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4794 - accuracy: 0.7688
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4797 - accuracy: 0.7686 - val_loss: 0.5591 - val_accuracy: 0.7040 - lr: 0.0010
253/253 [==============================] - 0s 924us/step
Independent Testing Matthews Correlation:  0.40378043998306645
Confusion Matrix :
 [[2778 1270]
 [1144 2903]]
Accuracy on test set:    0.7017912291537987
Sensitivity:    0.717321472695824 	 Specificity:    0.6862648221343873
Precision  : 0.6956625928588546
Area Under Curve:    0.7017931474151056
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6845 - val_loss: 0.5638 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7235 - val_loss: 0.5577 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7334 - val_loss: 0.5572 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7412 - val_loss: 0.5555 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7489 - val_loss: 0.5565 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 6/400
250/257 [============================>.] - ETA: 0s - loss: 0.4964 - accuracy: 0.7575
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7577 - val_loss: 0.5587 - val_accuracy: 0.7073 - lr: 0.0010
253/253 [==============================] - 0s 982us/step
Independent Testing Matthews Correlation:  0.43016146587424337
Confusion Matrix :
 [[2947 1101]
 [1206 2841]]
Accuracy on test set:    0.7150092649783817
Sensitivity:    0.7020014825796886 	 Specificity:    0.7280138339920948
Precision  : 0.7207001522070016
Area Under Curve:    0.7150076582858917
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5893 - accuracy: 0.6819 - val_loss: 0.5528 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7223 - val_loss: 0.5446 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7327 - val_loss: 0.5440 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7412 - val_loss: 0.5423 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7483 - val_loss: 0.5448 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7573 - val_loss: 0.5433 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4866 - accuracy: 0.7649 - val_loss: 0.5595 - val_accuracy: 0.7016 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4756 - accuracy: 0.7709
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4757 - accuracy: 0.7707 - val_loss: 0.5502 - val_accuracy: 0.7113 - lr: 0.0010
253/253 [==============================] - 0s 750us/step
Independent Testing Matthews Correlation:  0.4290310204929776
Confusion Matrix :
 [[2895 1152]
 [1159 2889]]
Accuracy on test set:    0.7145151327980235
Sensitivity:    0.7136857707509882 	 Specificity:    0.7153446997776131
Precision  : 0.7149220489977728
Area Under Curve:    0.7145152352643007
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5862 - accuracy: 0.6838 - val_loss: 0.5506 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7237 - val_loss: 0.5385 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7339 - val_loss: 0.5351 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7428 - val_loss: 0.5369 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7510 - val_loss: 0.5421 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7582 - val_loss: 0.5420 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4854 - accuracy: 0.7648 - val_loss: 0.5439 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4735 - accuracy: 0.7736
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7734 - val_loss: 0.5487 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40584693287743195
Confusion Matrix :
 [[3111  936]
 [1484 2564]]
Accuracy on test set:    0.7010500308832612
Sensitivity:    0.633399209486166 	 Specificity:    0.7687175685693106
Precision  : 0.7325714285714285
Area Under Curve:    0.7010583890277383
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5897 - accuracy: 0.6845 - val_loss: 0.5490 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7236 - val_loss: 0.5425 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7347 - val_loss: 0.5394 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5163 - accuracy: 0.7421 - val_loss: 0.5437 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5043 - accuracy: 0.7515 - val_loss: 0.5402 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7610 - val_loss: 0.5466 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7681 - val_loss: 0.5466 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4678 - accuracy: 0.7754 - val_loss: 0.5542 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4539 - accuracy: 0.7836 - val_loss: 0.5536 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4420 - accuracy: 0.7937
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4420 - accuracy: 0.7937 - val_loss: 0.5644 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 900us/step
Independent Testing Matthews Correlation:  0.4293989501489365
Confusion Matrix :
 [[2800 1247]
 [1064 2983]]
Accuracy on test set:    0.7144798616258957
Sensitivity:    0.7370892018779343 	 Specificity:    0.6918705213738572
Precision  : 0.7052009456264775
Area Under Curve:    0.7144798616258957
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5860 - accuracy: 0.6861 - val_loss: 0.5496 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7236 - val_loss: 0.5384 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7334 - val_loss: 0.5377 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7436 - val_loss: 0.5406 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7501 - val_loss: 0.5371 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7583 - val_loss: 0.5438 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7671 - val_loss: 0.5467 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4717 - accuracy: 0.7737
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7737 - val_loss: 0.5568 - val_accuracy: 0.7229 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42507274774035225
Confusion Matrix :
 [[2589 1458]
 [ 886 3161]]
Accuracy on test set:    0.7104027674820855
Sensitivity:    0.7810723993081294 	 Specificity:    0.6397331356560415
Precision  : 0.6843472613119723
Area Under Curve:    0.7104027674820854
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5847 - accuracy: 0.6872 - val_loss: 0.5579 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7227 - val_loss: 0.5423 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7327 - val_loss: 0.5413 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7417 - val_loss: 0.5431 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7489 - val_loss: 0.5427 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7563 - val_loss: 0.5435 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4899 - accuracy: 0.7635 - val_loss: 0.5534 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4766 - accuracy: 0.7708 - val_loss: 0.5508 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4673 - accuracy: 0.7775 - val_loss: 0.5517 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4522 - accuracy: 0.7897 - val_loss: 0.5717 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 11/400
250/257 [============================>.] - ETA: 0s - loss: 0.4400 - accuracy: 0.7965
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4404 - accuracy: 0.7961 - val_loss: 0.5575 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 797us/step
Independent Testing Matthews Correlation:  0.43168708669243816
Confusion Matrix :
 [[2634 1413]
 [ 901 3146]]
Accuracy on test set:    0.7141092167037312
Sensitivity:    0.7773659500864838 	 Specificity:    0.6508524833209784
Precision  : 0.6900636104408862
Area Under Curve:    0.7141092167037312
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5918 - accuracy: 0.6791 - val_loss: 0.5481 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5480 - accuracy: 0.7203 - val_loss: 0.5406 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5330 - accuracy: 0.7319 - val_loss: 0.5362 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7398 - val_loss: 0.5375 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7465 - val_loss: 0.5401 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.7549 - val_loss: 0.5383 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4883 - accuracy: 0.7645 - val_loss: 0.5453 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4760 - accuracy: 0.7732 - val_loss: 0.5516 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4619 - accuracy: 0.7809 - val_loss: 0.5464 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4492 - accuracy: 0.7897 - val_loss: 0.5530 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4348 - accuracy: 0.7982 - val_loss: 0.5667 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 12/400
249/257 [============================>.] - ETA: 0s - loss: 0.4222 - accuracy: 0.8053
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4219 - accuracy: 0.8053 - val_loss: 0.5679 - val_accuracy: 0.7179 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42541044681617884
Confusion Matrix :
 [[2829 1218]
 [1108 2939]]
Accuracy on test set:    0.7126266370150729
Sensitivity:    0.7262169508277737 	 Specificity:    0.6990363232023721
Precision  : 0.7070002405580947
Area Under Curve:    0.712626637015073
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6801 - val_loss: 0.5582 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7208 - val_loss: 0.5401 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7323 - val_loss: 0.5369 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7421 - val_loss: 0.5387 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7485 - val_loss: 0.5409 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7583 - val_loss: 0.5401 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4830 - accuracy: 0.7659 - val_loss: 0.5402 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4716 - accuracy: 0.7749 - val_loss: 0.5452 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4599 - accuracy: 0.7811 - val_loss: 0.5453 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4466 - accuracy: 0.7934 - val_loss: 0.5551 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - ETA: 0s - loss: 0.4348 - accuracy: 0.7980
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4348 - accuracy: 0.7980 - val_loss: 0.5556 - val_accuracy: 0.7240 - lr: 0.0010
253/253 [==============================] - 0s 938us/step
Independent Testing Matthews Correlation:  0.46603310757211125
Confusion Matrix :
 [[2979 1068]
 [1093 2954]]
Accuracy on test set:    0.7330121077341241
Sensitivity:    0.7299234000494194 	 Specificity:    0.7361008154188288
Precision  : 0.7344604674291397
Area Under Curve:    0.7330121077341241
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5955 - accuracy: 0.6771 - val_loss: 0.5521 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5521 - accuracy: 0.7181 - val_loss: 0.5447 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5374 - accuracy: 0.7275 - val_loss: 0.5497 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5263 - accuracy: 0.7349 - val_loss: 0.5400 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7426 - val_loss: 0.5414 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7490 - val_loss: 0.5462 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4960 - accuracy: 0.7578
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7576 - val_loss: 0.5424 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47129677865952335
Confusion Matrix :
 [[3162  885]
 [1263 2784]]
Accuracy on test set:    0.7346182357301705
Sensitivity:    0.6879169755374351 	 Specificity:    0.7813194959229058
Precision  : 0.758789860997547
Area Under Curve:    0.7346182357301706
(8094, 2560) (8094,)
Mean MCC = 0.4318 + 0.0207 and Mean AUC = 0.7152 + 0.0105
Mean Sensitivity = 0.7206 + 0.0404 and Mean Specificity = 0.7097 + 0.0436 and Mean Accuracy = 0.7152 + 0.0105
Mean Precision = 0.7144 + 0.0217





Seed   : 754558
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5845 - accuracy: 0.6862 - val_loss: 0.5596 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7246 - val_loss: 0.5563 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5260 - accuracy: 0.7362 - val_loss: 0.5526 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7436 - val_loss: 0.5490 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7501 - val_loss: 0.5547 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7581 - val_loss: 0.5554 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.7662 - val_loss: 0.5584 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4709 - accuracy: 0.7744
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.7746 - val_loss: 0.5650 - val_accuracy: 0.7101 - lr: 0.0010
253/253 [==============================] - 0s 734us/step
Independent Testing Matthews Correlation:  0.3950921003369084
Confusion Matrix :
 [[2686 1362]
 [1090 2957]]
Accuracy on test set:    0.6970969734403953
Sensitivity:    0.7306646898937484 	 Specificity:    0.6635375494071146
Precision  : 0.6846492243574902
Area Under Curve:    0.6971011196504314
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5834 - accuracy: 0.6870 - val_loss: 0.5557 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5400 - accuracy: 0.7262 - val_loss: 0.5489 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5241 - accuracy: 0.7387 - val_loss: 0.5490 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7451 - val_loss: 0.5530 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.7547 - val_loss: 0.5615 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7616 - val_loss: 0.5532 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4778 - accuracy: 0.7694 - val_loss: 0.5574 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4656 - accuracy: 0.7786
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4656 - accuracy: 0.7785 - val_loss: 0.5722 - val_accuracy: 0.7105 - lr: 0.0010
253/253 [==============================] - 0s 784us/step
Independent Testing Matthews Correlation:  0.4267584555840883
Confusion Matrix :
 [[2499 1549]
 [ 801 3246]]
Accuracy on test set:    0.7096973440395306
Sensitivity:    0.8020756115641215 	 Specificity:    0.6173418972332015
Precision  : 0.6769551616266944
Area Under Curve:    0.7097087543986615
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5878 - accuracy: 0.6840 - val_loss: 0.5481 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7226 - val_loss: 0.5388 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7318 - val_loss: 0.5390 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7408 - val_loss: 0.5350 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7492 - val_loss: 0.5400 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7568 - val_loss: 0.5440 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4819 - accuracy: 0.7678 - val_loss: 0.5497 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4695 - accuracy: 0.7754 - val_loss: 0.5449 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4571 - accuracy: 0.7855
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.7857 - val_loss: 0.5526 - val_accuracy: 0.7179 - lr: 0.0010
253/253 [==============================] - 0s 775us/step
Independent Testing Matthews Correlation:  0.4308838991696861
Confusion Matrix :
 [[3038 1009]
 [1299 2749]]
Accuracy on test set:    0.7148857319332922
Sensitivity:    0.679100790513834 	 Specificity:    0.7506795156906351
Precision  : 0.731506120276743
Area Under Curve:    0.7148901531022345
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5851 - accuracy: 0.6852 - val_loss: 0.5419 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7212 - val_loss: 0.5372 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7333 - val_loss: 0.5328 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7437 - val_loss: 0.5357 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7503 - val_loss: 0.5351 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7600 - val_loss: 0.5397 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.7689 - val_loss: 0.5424 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.7782 - val_loss: 0.5466 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4517 - accuracy: 0.7879 - val_loss: 0.5516 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4382 - accuracy: 0.7957
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4385 - accuracy: 0.7952 - val_loss: 0.5576 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 830us/step
Independent Testing Matthews Correlation:  0.42287911774569703
Confusion Matrix :
 [[2720 1327]
 [1014 3034]]
Accuracy on test set:    0.7108091414453366
Sensitivity:    0.7495059288537549 	 Specificity:    0.672102792191747
Precision  : 0.6957119926622334
Area Under Curve:    0.7108043605227509
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5895 - accuracy: 0.6810 - val_loss: 0.5596 - val_accuracy: 0.7049 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7230 - val_loss: 0.5473 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7331 - val_loss: 0.5482 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7430 - val_loss: 0.5461 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5040 - accuracy: 0.7512 - val_loss: 0.5493 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4918 - accuracy: 0.7592 - val_loss: 0.5493 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4807 - accuracy: 0.7666
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4811 - accuracy: 0.7665 - val_loss: 0.5526 - val_accuracy: 0.7124 - lr: 0.0010
253/253 [==============================] - 0s 968us/step
Independent Testing Matthews Correlation:  0.4125203287586494
Confusion Matrix :
 [[2906 1141]
 [1237 2810]]
Accuracy on test set:    0.7062021250308871
Sensitivity:    0.694341487521621 	 Specificity:    0.7180627625401532
Precision  : 0.7112123513034675
Area Under Curve:    0.7062021250308871
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6851 - val_loss: 0.5510 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7213 - val_loss: 0.5481 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7322 - val_loss: 0.5453 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7407 - val_loss: 0.5441 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7486 - val_loss: 0.5448 - val_accuracy: 0.7183 - lr: 0.0010

Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7564 - val_loss: 0.5480 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.7656 - val_loss: 0.5515 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4732 - accuracy: 0.7746 - val_loss: 0.5605 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4594 - accuracy: 0.7815
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4594 - accuracy: 0.7816 - val_loss: 0.5629 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 742us/step
Independent Testing Matthews Correlation:  0.4195823616783897
Confusion Matrix :
 [[2857 1190]
 [1159 2888]]
Accuracy on test set:    0.7097850259451446
Sensitivity:    0.7136150234741784 	 Specificity:    0.7059550284161107
Precision  : 0.7081902893575281
Area Under Curve:    0.7097850259451446
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5904 - accuracy: 0.6819 - val_loss: 0.5482 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7222 - val_loss: 0.5405 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7349 - val_loss: 0.5460 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7425 - val_loss: 0.5403 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5027 - accuracy: 0.7499 - val_loss: 0.5413 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4896 - accuracy: 0.7605 - val_loss: 0.5450 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4778 - accuracy: 0.7675 - val_loss: 0.5461 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4656 - accuracy: 0.7773 - val_loss: 0.5510 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4534 - accuracy: 0.7848 - val_loss: 0.5516 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4399 - accuracy: 0.7950 - val_loss: 0.5681 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 11/400
251/257 [============================>.] - ETA: 0s - loss: 0.4278 - accuracy: 0.8005
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4280 - accuracy: 0.8005 - val_loss: 0.5754 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 929us/step
Independent Testing Matthews Correlation:  0.41458123734486685
Confusion Matrix :
 [[2639 1408]
 [ 971 3076]]
Accuracy on test set:    0.7060785767234989
Sensitivity:    0.7600691870521374 	 Specificity:    0.6520879663948604
Precision  : 0.6859946476360392
Area Under Curve:    0.7060785767234989
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5941 - accuracy: 0.6793 - val_loss: 0.5466 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7204 - val_loss: 0.5376 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7314 - val_loss: 0.5371 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7399 - val_loss: 0.5384 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7477 - val_loss: 0.5373 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.7546 - val_loss: 0.5418 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7621 - val_loss: 0.5493 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4797 - accuracy: 0.7675 - val_loss: 0.5520 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4684 - accuracy: 0.7738 - val_loss: 0.5556 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4587 - accuracy: 0.7820 - val_loss: 0.5553 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - ETA: 0s - loss: 0.4474 - accuracy: 0.7902
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4474 - accuracy: 0.7902 - val_loss: 0.5640 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 813us/step
Independent Testing Matthews Correlation:  0.4298197359326108
Confusion Matrix :
 [[3051  996]
 [1317 2730]]
Accuracy on test set:    0.7142327650111193
Sensitivity:    0.6745737583395107 	 Specificity:    0.7538917716827279
Precision  : 0.7326892109500805
Area Under Curve:    0.7142327650111193
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5889 - accuracy: 0.6844 - val_loss: 0.5486 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.7209 - val_loss: 0.5393 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5328 - accuracy: 0.7309 - val_loss: 0.5427 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7390 - val_loss: 0.5405 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5109 - accuracy: 0.7491 - val_loss: 0.5396 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5021 - accuracy: 0.7525 - val_loss: 0.5398 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4889 - accuracy: 0.7639 - val_loss: 0.5402 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7685 - val_loss: 0.5444 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4675 - accuracy: 0.7771 - val_loss: 0.5445 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4559 - accuracy: 0.7847
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4555 - accuracy: 0.7851 - val_loss: 0.5541 - val_accuracy: 0.7253 - lr: 0.0010
253/253 [==============================] - 0s 891us/step
Independent Testing Matthews Correlation:  0.4544675066518757
Confusion Matrix :
 [[2975 1072]
 [1136 2911]]
Accuracy on test set:    0.7272053372868792
Sensitivity:    0.7192982456140351 	 Specificity:    0.7351124289597233
Precision  : 0.7308561385890032
Area Under Curve:    0.7272053372868792
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5947 - accuracy: 0.6781 - val_loss: 0.5561 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5511 - accuracy: 0.7215 - val_loss: 0.5456 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5356 - accuracy: 0.7297 - val_loss: 0.5471 - val_accuracy: 0.7194 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5232 - accuracy: 0.7382 - val_loss: 0.5454 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5122 - accuracy: 0.7466 - val_loss: 0.5491 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7529 - val_loss: 0.5440 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7622 - val_loss: 0.5518 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7700 - val_loss: 0.5515 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4679 - accuracy: 0.7770
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4673 - accuracy: 0.7774 - val_loss: 0.5618 - val_accuracy: 0.7224 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4844372926075105
Confusion Matrix :
 [[2957 1090]
 [ 997 3050]]
Accuracy on test set:    0.74215468248085
Sensitivity:    0.7536446750679515 	 Specificity:    0.7306646898937484
Precision  : 0.7367149758454107
Area Under Curve:    0.7421546824808499
(8094, 2560) (8094,)
Mean MCC = 0.4291 + 0.0234 and Mean AUC = 0.7138 + 0.0119
Mean Sensitivity = 0.7277 + 0.0378 and Mean Specificity = 0.6999 + 0.0439 and Mean Accuracy = 0.7138 + 0.0119
Mean Precision = 0.7094 + 0.0215





Seed   : 899782
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5882 - accuracy: 0.6840 - val_loss: 0.5591 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7234 - val_loss: 0.5466 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7343 - val_loss: 0.5457 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7442 - val_loss: 0.5449 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7512 - val_loss: 0.5551 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7577 - val_loss: 0.5522 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4832 - accuracy: 0.7668
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4831 - accuracy: 0.7668 - val_loss: 0.5528 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41455715946606325
Confusion Matrix :
 [[2991 1057]
 [1316 2731]]
Accuracy on test set:    0.7068560840024707
Sensitivity:    0.6748208549542871 	 Specificity:    0.7388833992094862
Precision  : 0.720960929250264
Area Under Curve:    0.7068521270818866
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5873 - accuracy: 0.6856 - val_loss: 0.5540 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7249 - val_loss: 0.5479 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7364 - val_loss: 0.5458 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7411 - val_loss: 0.5483 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7501 - val_loss: 0.5469 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7583 - val_loss: 0.5505 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7654 - val_loss: 0.5570 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4725 - accuracy: 0.7755 - val_loss: 0.5645 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4628 - accuracy: 0.7798
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4627 - accuracy: 0.7799 - val_loss: 0.5642 - val_accuracy: 0.7078 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42878877428966805
Confusion Matrix :
 [[2882 1166]
 [1146 2901]]
Accuracy on test set:    0.7143915997529339
Sensitivity:    0.7168272794662713 	 Specificity:    0.7119565217391305
Precision  : 0.7133021883452176
Area Under Curve:    0.7143919006027009
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5888 - accuracy: 0.6828 - val_loss: 0.5465 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7215 - val_loss: 0.5378 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7345 - val_loss: 0.5379 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7415 - val_loss: 0.5400 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5043 - accuracy: 0.7516 - val_loss: 0.5407 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7596 - val_loss: 0.5419 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4822 - accuracy: 0.7672
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7671 - val_loss: 0.5444 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 789us/step
Independent Testing Matthews Correlation:  0.42316821758826056
Confusion Matrix :
 [[2843 1204]
 [1131 2917]]
Accuracy on test set:    0.711550339715874
Sensitivity:    0.720602766798419 	 Specificity:    0.7024956758092414
Precision  : 0.7078379034214997
Area Under Curve:    0.7115492213038302
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5869 - accuracy: 0.6855 - val_loss: 0.5431 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7227 - val_loss: 0.5392 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7326 - val_loss: 0.5411 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7423 - val_loss: 0.5353 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7516 - val_loss: 0.5372 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7602 - val_loss: 0.5360 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4799 - accuracy: 0.7674
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7674 - val_loss: 0.5388 - val_accuracy: 0.7238 - lr: 0.0010
253/253 [==============================] - 0s 721us/step
Independent Testing Matthews Correlation:  0.41611744917593574
Confusion Matrix :
 [[2711 1336]
 [1032 3016]]
Accuracy on test set:    0.7074737492279185
Sensitivity:    0.7450592885375494 	 Specificity:    0.6698789226587596
Precision  : 0.6930147058823529
Area Under Curve:    0.7074691055981545
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5888 - accuracy: 0.6832 - val_loss: 0.5539 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7202 - val_loss: 0.5451 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5269 - accuracy: 0.7354 - val_loss: 0.5480 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7432 - val_loss: 0.5409 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5028 - accuracy: 0.7517 - val_loss: 0.5422 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.7607 - val_loss: 0.5446 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4770 - accuracy: 0.7691 - val_loss: 0.5502 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4643 - accuracy: 0.7788 - val_loss: 0.5490 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4519 - accuracy: 0.7877 - val_loss: 0.5555 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4389 - accuracy: 0.7953 - val_loss: 0.5649 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4266 - accuracy: 0.8040 - val_loss: 0.5767 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 12/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4138 - accuracy: 0.8105
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4140 - accuracy: 0.8105 - val_loss: 0.5719 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4097765806498499
Confusion Matrix :
 [[2810 1237]
 [1152 2895]]
Accuracy on test set:    0.704843093649617
Sensitivity:    0.7153446997776131 	 Specificity:    0.694341487521621
Precision  : 0.7006292352371732
Area Under Curve:    0.7048430936496171
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5900 - accuracy: 0.6834 - val_loss: 0.5483 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7223 - val_loss: 0.5400 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7347 - val_loss: 0.5423 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7415 - val_loss: 0.5442 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7502 - val_loss: 0.5404 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7576 - val_loss: 0.5404 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4873 - accuracy: 0.7645
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7646 - val_loss: 0.5408 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.408565670124654
Confusion Matrix :
 [[2898 1149]
 [1245 2802]]
Accuracy on test set:    0.704225352112676
Sensitivity:    0.69236471460341 	 Specificity:    0.7160859896219421
Precision  : 0.7091875474563402
Area Under Curve:    0.7042253521126762
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5903 - accuracy: 0.6814 - val_loss: 0.5501 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7228 - val_loss: 0.5398 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7316 - val_loss: 0.5422 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5210 - accuracy: 0.7382 - val_loss: 0.5439 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5105 - accuracy: 0.7474 - val_loss: 0.5403 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5003 - accuracy: 0.7559 - val_loss: 0.5406 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4896 - accuracy: 0.7607
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4902 - accuracy: 0.7601 - val_loss: 0.5386 - val_accuracy: 0.7241 - lr: 0.0010
253/253 [==============================] - 0s 778us/step
Independent Testing Matthews Correlation:  0.4346749383724082
Confusion Matrix :
 [[2830 1217]
 [1072 2975]]
Accuracy on test set:    0.7171979243884359
Sensitivity:    0.7351124289597233 	 Specificity:    0.6992834198171485
Precision  : 0.7096851145038168
Area Under Curve:    0.7171979243884359
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6847 - val_loss: 0.5506 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.7206 - val_loss: 0.5401 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7317 - val_loss: 0.5361 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5212 - accuracy: 0.7392 - val_loss: 0.5382 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7489 - val_loss: 0.5389 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4995 - accuracy: 0.7533 - val_loss: 0.5387 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7634 - val_loss: 0.5401 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4736 - accuracy: 0.7735
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7733 - val_loss: 0.5394 - val_accuracy: 0.7255 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4587318975632051
Confusion Matrix :
 [[3032 1015]
 [1177 2870]]
Accuracy on test set:    0.7291821102050902
Sensitivity:    0.7091672844082036 	 Specificity:    0.7491969360019768
Precision  : 0.7387387387387387
Area Under Curve:    0.7291821102050902
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5876 - accuracy: 0.6849 - val_loss: 0.5574 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7216 - val_loss: 0.5433 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 3/400

257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7304 - val_loss: 0.5418 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7417 - val_loss: 0.5429 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7491 - val_loss: 0.5425 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7588 - val_loss: 0.5423 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7670 - val_loss: 0.5455 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4713 - accuracy: 0.7759
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7756 - val_loss: 0.5491 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4633781525466463
Confusion Matrix :
 [[2860 1187]
 [ 987 3060]]
Accuracy on test set:    0.7314059797380776
Sensitivity:    0.7561156412157154 	 Specificity:    0.7066963182604399
Precision  : 0.7205085943018601
Area Under Curve:    0.7314059797380776
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5938 - accuracy: 0.6778 - val_loss: 0.5555 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5497 - accuracy: 0.7202 - val_loss: 0.5446 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7323 - val_loss: 0.5427 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7409 - val_loss: 0.5432 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5093 - accuracy: 0.7499 - val_loss: 0.5478 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7575 - val_loss: 0.5444 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7649 - val_loss: 0.5485 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7744 - val_loss: 0.5514 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4609 - accuracy: 0.7829 - val_loss: 0.5557 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4482 - accuracy: 0.7903 - val_loss: 0.5581 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4345 - accuracy: 0.7990 - val_loss: 0.5624 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4212 - accuracy: 0.8079 - val_loss: 0.5741 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4115 - accuracy: 0.8123 - val_loss: 0.5731 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - ETA: 0s - loss: 0.4000 - accuracy: 0.8192
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4000 - accuracy: 0.8192 - val_loss: 0.5820 - val_accuracy: 0.7137 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.45569781134848864
Confusion Matrix :
 [[3241  806]
 [1418 2629]]
Accuracy on test set:    0.7252285643686681
Sensitivity:    0.6496170002470966 	 Specificity:    0.8008401284902397
Precision  : 0.7653566229985443
Area Under Curve:    0.7252285643686682
(8094, 2560) (8094,)
Mean MCC = 0.4313 + 0.0199 and Mean AUC = 0.7152 + 0.0097
Mean Sensitivity = 0.7115 + 0.0306 and Mean Specificity = 0.7190 + 0.0345 and Mean Accuracy = 0.7152 + 0.0097
Mean Precision = 0.7179 + 0.0197





Seed   : 870955
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5863 - accuracy: 0.6876 - val_loss: 0.5522 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7229 - val_loss: 0.5486 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7356 - val_loss: 0.5541 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7407 - val_loss: 0.5604 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7477 - val_loss: 0.5481 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 6/400
255/257 [============================>.] - ETA: 0s - loss: 0.4980 - accuracy: 0.7574
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7572 - val_loss: 0.5500 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39914468731489994
Confusion Matrix :
 [[2933 1115]
 [1319 2728]]
Accuracy on test set:    0.6993205682520074
Sensitivity:    0.674079565109958 	 Specificity:    0.7245553359683794
Precision  : 0.7098620869112673
Area Under Curve:    0.6993174505391687
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5852 - accuracy: 0.6861 - val_loss: 0.5529 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7229 - val_loss: 0.5468 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7329 - val_loss: 0.5418 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7431 - val_loss: 0.5428 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7522 - val_loss: 0.5465 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7583 - val_loss: 0.5449 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4817 - accuracy: 0.7668 - val_loss: 0.5506 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4723 - accuracy: 0.7732
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7735 - val_loss: 0.5498 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4165267783546575
Confusion Matrix :
 [[2911 1137]
 [1225 2822]]
Accuracy on test set:    0.7082149474984558
Sensitivity:    0.6973066468989375 	 Specificity:    0.7191205533596838
Precision  : 0.7128062642081334
Area Under Curve:    0.7082136001293107
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5887 - accuracy: 0.6835 - val_loss: 0.5423 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7238 - val_loss: 0.5354 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7328 - val_loss: 0.5330 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7426 - val_loss: 0.5340 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7509 - val_loss: 0.5339 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7574 - val_loss: 0.5390 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4821 - accuracy: 0.7679
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7677 - val_loss: 0.5409 - val_accuracy: 0.7197 - lr: 0.0010
253/253 [==============================] - 0s 763us/step
Independent Testing Matthews Correlation:  0.42204367414612115
Confusion Matrix :
 [[2967 1080]
 [1261 2787]]
Accuracy on test set:    0.7108091414453366
Sensitivity:    0.6884881422924901 	 Specificity:    0.7331356560415122
Precision  : 0.7207137315748642
Area Under Curve:    0.7108118991670012
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5900 - accuracy: 0.6812 - val_loss: 0.5492 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7214 - val_loss: 0.5379 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7330 - val_loss: 0.5355 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7422 - val_loss: 0.5339 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7509 - val_loss: 0.5329 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7571 - val_loss: 0.5362 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7675 - val_loss: 0.5410 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7740 - val_loss: 0.5457 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4578 - accuracy: 0.7833 - val_loss: 0.5515 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4440 - accuracy: 0.7931
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4440 - accuracy: 0.7931 - val_loss: 0.5541 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 898us/step
Independent Testing Matthews Correlation:  0.4165439092385798
Confusion Matrix :
 [[2913 1134]
 [1228 2820]]
Accuracy on test set:    0.7082149474984558
Sensitivity:    0.6966403162055336 	 Specificity:    0.7197924388435878
Precision  : 0.7132018209408194
Area Under Curve:    0.7082163775245608
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 8ms/step - loss: 0.5847 - accuracy: 0.6849 - val_loss: 0.5504 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7227 - val_loss: 0.5460 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7322 - val_loss: 0.5438 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7403 - val_loss: 0.5433 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7492 - val_loss: 0.5474 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7550 - val_loss: 0.5474 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4855 - accuracy: 0.7648
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7650 - val_loss: 0.5495 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 704us/step
Independent Testing Matthews Correlation:  0.44256992864068795
Confusion Matrix :
 [[2711 1336]
 [ 929 3118]]
Accuracy on test set:    0.7201630837657524
Sensitivity:    0.7704472448727453 	 Specificity:    0.6698789226587596
Precision  : 0.7000449034575662
Area Under Curve:    0.7201630837657524
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5885 - accuracy: 0.6843 - val_loss: 0.5514 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7206 - val_loss: 0.5482 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7317 - val_loss: 0.5437 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7402 - val_loss: 0.5431 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7479 - val_loss: 0.5443 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7551 - val_loss: 0.5431 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.7617 - val_loss: 0.5474 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4764 - accuracy: 0.7697
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4764 - accuracy: 0.7698 - val_loss: 0.5536 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 803us/step
Independent Testing Matthews Correlation:  0.429553184471403
Confusion Matrix :
 [[2849 1198]
 [1111 2936]]
Accuracy on test set:    0.7147269582406721
Sensitivity:    0.7254756609834445 	 Specificity:    0.7039782554978997
Precision  : 0.710208030962748
Area Under Curve:    0.7147269582406721
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5904 - accuracy: 0.6826 - val_loss: 0.5520 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7218 - val_loss: 0.5453 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7337 - val_loss: 0.5498 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7421 - val_loss: 0.5464 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7521 - val_loss: 0.5455 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7608 - val_loss: 0.5492 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4794 - accuracy: 0.7676
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7673 - val_loss: 0.5502 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 825us/step
Independent Testing Matthews Correlation:  0.4268229235906027
Confusion Matrix :
 [[2697 1350]
 [ 977 3070]]
Accuracy on test set:    0.7125030887076848
Sensitivity:    0.7585866073634792 	 Specificity:    0.6664195700518903
Precision  : 0.6945701357466063
Area Under Curve:    0.7125030887076846
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5853 - accuracy: 0.6847 - val_loss: 0.5521 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7239 - val_loss: 0.5454 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7359 - val_loss: 0.5414 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7431 - val_loss: 0.5405 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7507 - val_loss: 0.5416 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7594 - val_loss: 0.5484 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4801 - accuracy: 0.7682
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7680 - val_loss: 0.5472 - val_accuracy: 0.7150 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43217329860047055
Confusion Matrix :
 [[2903 1144]
 [1154 2893]]
Accuracy on test set:    0.7160859896219421
Sensitivity:    0.7148505065480603 	 Specificity:    0.717321472695824
Precision  : 0.7166212534059946
Area Under Curve:    0.7160859896219421
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5942 - accuracy: 0.6799 - val_loss: 0.5589 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5489 - accuracy: 0.7199 - val_loss: 0.5477 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7317 - val_loss: 0.5462 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5207 - accuracy: 0.7382 - val_loss: 0.5459 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7477 - val_loss: 0.5481 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7568 - val_loss: 0.5453 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7630 - val_loss: 0.5509 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7751 - val_loss: 0.5520 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4578 - accuracy: 0.7810 - val_loss: 0.5580 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4460 - accuracy: 0.7924 - val_loss: 0.5646 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4325 - accuracy: 0.7986 - val_loss: 0.5676 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4201 - accuracy: 0.8066
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4200 - accuracy: 0.8066 - val_loss: 0.5734 - val_accuracy: 0.7121 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44258469514506327
Confusion Matrix :
 [[3096  951]
 [1312 2735]]
Accuracy on test set:    0.7204101803805288
Sensitivity:    0.6758092414133926 	 Specificity:    0.765011119347665
Precision  : 0.7419967444384157
Area Under Curve:    0.7204101803805287
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5906 - accuracy: 0.6821 - val_loss: 0.5626 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7201 - val_loss: 0.5488 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7308 - val_loss: 0.5452 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5209 - accuracy: 0.7386 - val_loss: 0.5438 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7490 - val_loss: 0.5479 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7566 - val_loss: 0.5455 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4854 - accuracy: 0.7648 - val_loss: 0.5474 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7723 - val_loss: 0.5532 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4609 - accuracy: 0.7815
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4609 - accuracy: 0.7815 - val_loss: 0.5574 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4706032220862993
Confusion Matrix :
 [[3113  934]
 [1213 2834]]
Accuracy on test set:    0.7347417840375586
Sensitivity:    0.700271806276254 	 Specificity:    0.7692117617988633
Precision  : 0.7521231422505308
Area Under Curve:    0.7347417840375587
(8094, 2560) (8094,)
Mean MCC = 0.4299 + 0.0183 and Mean AUC = 0.7145 + 0.0090
Mean Sensitivity = 0.7102 + 0.0310 and Mean Specificity = 0.7188 + 0.0321 and Mean Accuracy = 0.7145 + 0.0090
Mean Precision = 0.7172 + 0.0167





Seed   : 674743
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5849 - accuracy: 0.6872 - val_loss: 0.5547 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5410 - accuracy: 0.7267 - val_loss: 0.5476 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.7370 - val_loss: 0.5493 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5154 - accuracy: 0.7430 - val_loss: 0.5474 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7500 - val_loss: 0.5493 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7575 - val_loss: 0.5503 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7658 - val_loss: 0.5570 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4723 - accuracy: 0.7750 - val_loss: 0.5538 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4593 - accuracy: 0.7825
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4595 - accuracy: 0.7823 - val_loss: 0.5587 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.403948195629735
Confusion Matrix :
 [[2645 1403]
 [1017 3030]]
Accuracy on test set:    0.7010500308832612
Sensitivity:    0.748702742772424 	 Specificity:    0.6534090909090909
Precision  : 0.683510038348748
Area Under Curve:    0.7010559168407573
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5880 - accuracy: 0.6835 - val_loss: 0.5594 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7245 - val_loss: 0.5541 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7363 - val_loss: 0.5495 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7442 - val_loss: 0.5475 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5023 - accuracy: 0.7525 - val_loss: 0.5480 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.7640 - val_loss: 0.5522 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7717 - val_loss: 0.5549 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4645 - accuracy: 0.7783 - val_loss: 0.5601 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4507 - accuracy: 0.7889 - val_loss: 0.5688 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4382 - accuracy: 0.7978
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4378 - accuracy: 0.7980 - val_loss: 0.5747 - val_accuracy: 0.7100 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41721338841866595
Confusion Matrix :
 [[2666 1382]
 [ 985 3062]]
Accuracy on test set:    0.707597282273008
Sensitivity:    0.7566098344452681 	 Specificity:    0.6585968379446641
Precision  : 0.689018901890189
Area Under Curve:    0.7076033361949661
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5881 - accuracy: 0.6852 - val_loss: 0.5495 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7237 - val_loss: 0.5414 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7351 - val_loss: 0.5355 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7449 - val_loss: 0.5390 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7517 - val_loss: 0.5417 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7589 - val_loss: 0.5405 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7664 - val_loss: 0.5434 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4706 - accuracy: 0.7755 - val_loss: 0.5459 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4578 - accuracy: 0.7831
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4580 - accuracy: 0.7831 - val_loss: 0.5528 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42711976001001517
Confusion Matrix :
 [[2712 1335]
 [ 990 3058]]
Accuracy on test set:    0.7127856701667696
Sensitivity:    0.7554347826086957 	 Specificity:    0.670126019273536
Precision  : 0.6961074436603688
Area Under Curve:    0.7127804009411158
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5873 - accuracy: 0.6856 - val_loss: 0.5478 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7243 - val_loss: 0.5431 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7340 - val_loss: 0.5369 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7410 - val_loss: 0.5373 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7516 - val_loss: 0.5408 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7588 - val_loss: 0.5427 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4797 - accuracy: 0.7696 - val_loss: 0.5431 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4656 - accuracy: 0.7779
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4666 - accuracy: 0.7771 - val_loss: 0.5475 - val_accuracy: 0.7222 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40612678576973954
Confusion Matrix :
 [[2715 1332]
 [1075 2973]]
Accuracy on test set:    0.7026559604694256
Sensitivity:    0.7344367588932806 	 Specificity:    0.6708673091178651
Precision  : 0.6905923344947735
Area Under Curve:    0.7026520340055729
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5896 - accuracy: 0.6840 - val_loss: 0.5632 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7231 - val_loss: 0.5592 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7327 - val_loss: 0.5453 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7397 - val_loss: 0.5484 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7484 - val_loss: 0.5441 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7551 - val_loss: 0.5524 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4890 - accuracy: 0.7616 - val_loss: 0.5453 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4769 - accuracy: 0.7697 - val_loss: 0.5504 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4652 - accuracy: 0.7782 - val_loss: 0.5499 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4535 - accuracy: 0.7845
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4532 - accuracy: 0.7849 - val_loss: 0.5575 - val_accuracy: 0.7248 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42847129857466854
Confusion Matrix :
 [[2901 1146]
 [1167 2880]]
Accuracy on test set:    0.7142327650111193
Sensitivity:    0.7116382505559674 	 Specificity:    0.7168272794662713
Precision  : 0.7153502235469449
Area Under Curve:    0.7142327650111193
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5857 - accuracy: 0.6866 - val_loss: 0.5538 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7215 - val_loss: 0.5449 - val_accuracy: 0.7248 - lr: 0.0010

Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7314 - val_loss: 0.5458 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7412 - val_loss: 0.5392 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.7471 - val_loss: 0.5390 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5011 - accuracy: 0.7540 - val_loss: 0.5396 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.7616 - val_loss: 0.5401 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7705 - val_loss: 0.5469 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4646 - accuracy: 0.7794
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4658 - accuracy: 0.7790 - val_loss: 0.5506 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 921us/step
Independent Testing Matthews Correlation:  0.4399049907041268
Confusion Matrix :
 [[2554 1493]
 [ 800 3247]]
Accuracy on test set:    0.7167037311588831
Sensitivity:    0.802322708178898 	 Specificity:    0.6310847541388683
Precision  : 0.6850210970464135
Area Under Curve:    0.7167037311588831
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5854 - accuracy: 0.6853 - val_loss: 0.5503 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7220 - val_loss: 0.5528 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7314 - val_loss: 0.5410 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7406 - val_loss: 0.5403 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7493 - val_loss: 0.5418 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7574 - val_loss: 0.5426 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7660 - val_loss: 0.5430 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4729 - accuracy: 0.7736 - val_loss: 0.5480 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4599 - accuracy: 0.7820 - val_loss: 0.5471 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4470 - accuracy: 0.7910
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4477 - accuracy: 0.7904 - val_loss: 0.5587 - val_accuracy: 0.7235 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4153399653528174
Confusion Matrix :
 [[2929 1118]
 [1249 2798]]
Accuracy on test set:    0.7075611564121571
Sensitivity:    0.6913763281443044 	 Specificity:    0.7237459846800098
Precision  : 0.7145045965270684
Area Under Curve:    0.7075611564121571
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5882 - accuracy: 0.6836 - val_loss: 0.5502 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7229 - val_loss: 0.5419 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7347 - val_loss: 0.5370 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7450 - val_loss: 0.5357 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7525 - val_loss: 0.5367 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7601 - val_loss: 0.5407 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.7695 - val_loss: 0.5416 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4672 - accuracy: 0.7773
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4675 - accuracy: 0.7770 - val_loss: 0.5436 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 741us/step
Independent Testing Matthews Correlation:  0.4395551702139951
Confusion Matrix :
 [[3005 1042]
 [1228 2819]]
Accuracy on test set:    0.7195453422288115
Sensitivity:    0.6965653570546083 	 Specificity:    0.7425253274030146
Precision  : 0.7301217301217301
Area Under Curve:    0.7195453422288114
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5891 - accuracy: 0.6830 - val_loss: 0.5534 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7207 - val_loss: 0.5477 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7316 - val_loss: 0.5424 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7416 - val_loss: 0.5393 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7498 - val_loss: 0.5384 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7598 - val_loss: 0.5403 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7680 - val_loss: 0.5416 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4683 - accuracy: 0.7774 - val_loss: 0.5460 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4554 - accuracy: 0.7843 - val_loss: 0.5506 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4430 - accuracy: 0.7933 - val_loss: 0.5538 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4292 - accuracy: 0.8026
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4294 - accuracy: 0.8025 - val_loss: 0.5625 - val_accuracy: 0.7142 - lr: 0.0010
253/253 [==============================] - 0s 764us/step
Independent Testing Matthews Correlation:  0.45222187156794225
Confusion Matrix :
 [[3136  911]
 [1315 2732]]
Accuracy on test set:    0.7249814677538917
Sensitivity:    0.6750679515690635 	 Specificity:    0.77489498393872
Precision  : 0.7499313752401866
Area Under Curve:    0.7249814677538917
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5953 - accuracy: 0.6788 - val_loss: 0.5546 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5494 - accuracy: 0.7208 - val_loss: 0.5519 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5347 - accuracy: 0.7308 - val_loss: 0.5531 - val_accuracy: 0.7132 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7389 - val_loss: 0.5482 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5115 - accuracy: 0.7470 - val_loss: 0.5481 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7555 - val_loss: 0.5525 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.7638 - val_loss: 0.5510 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7733 - val_loss: 0.5558 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4622 - accuracy: 0.7802 - val_loss: 0.5630 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4497 - accuracy: 0.7905
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4497 - accuracy: 0.7905 - val_loss: 0.5663 - val_accuracy: 0.7119 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.48358136195492796
Confusion Matrix :
 [[3017 1030]
 [1060 2987]]
Accuracy on test set:    0.7417840375586855
Sensitivity:    0.7380775883370397 	 Specificity:    0.7454904867803311
Precision  : 0.7435897435897436
Area Under Curve:    0.7417840375586854
(8094, 2560) (8094,)
Mean MCC = 0.4313 + 0.0227 and Mean AUC = 0.7149 + 0.0114
Mean Sensitivity = 0.7310 + 0.0360 and Mean Specificity = 0.6988 + 0.0455 and Mean Accuracy = 0.7149 + 0.0114
Mean Precision = 0.7098 + 0.0235





Seed   : 593791
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5810 - accuracy: 0.6896 - val_loss: 0.5612 - val_accuracy: 0.7039 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5396 - accuracy: 0.7266 - val_loss: 0.5515 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5243 - accuracy: 0.7369 - val_loss: 0.5542 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5131 - accuracy: 0.7438 - val_loss: 0.5531 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7511 - val_loss: 0.5616 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4927 - accuracy: 0.7597 - val_loss: 0.5541 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7689 - val_loss: 0.5545 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4689 - accuracy: 0.7761 - val_loss: 0.5620 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4557 - accuracy: 0.7843 - val_loss: 0.5642 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4455 - accuracy: 0.7925 - val_loss: 0.5658 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4321 - accuracy: 0.7995 - val_loss: 0.5723 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4192 - accuracy: 0.8083 - val_loss: 0.5731 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4089 - accuracy: 0.8143 - val_loss: 0.5838 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 14/400
252/257 [============================>.] - ETA: 0s - loss: 0.3947 - accuracy: 0.8220
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3948 - accuracy: 0.8219 - val_loss: 0.5889 - val_accuracy: 0.7108 - lr: 0.0010
253/253 [==============================] - 0s 772us/step
Independent Testing Matthews Correlation:  0.39449960752389557
Confusion Matrix :
 [[2788 1260]
 [1191 2856]]
Accuracy on test set:    0.6972205064854848
Sensitivity:    0.7057079318013343 	 Specificity:    0.6887351778656127
Precision  : 0.6938775510204082
Area Under Curve:    0.6972215548334734
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5886 - accuracy: 0.6833 - val_loss: 0.5693 - val_accuracy: 0.6957 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7243 - val_loss: 0.5575 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7328 - val_loss: 0.5589 - val_accuracy: 0.7036 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7403 - val_loss: 0.5545 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7493 - val_loss: 0.5569 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7558 - val_loss: 0.5571 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4857 - accuracy: 0.7635 - val_loss: 0.5597 - val_accuracy: 0.7034 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4754 - accuracy: 0.7722 - val_loss: 0.5587 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4654 - accuracy: 0.7782 - val_loss: 0.5658 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4528 - accuracy: 0.7859 - val_loss: 0.5655 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4402 - accuracy: 0.7936 - val_loss: 0.5746 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4283 - accuracy: 0.8014 - val_loss: 0.5814 - val_accuracy: 0.7021 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4145 - accuracy: 0.8090 - val_loss: 0.5945 - val_accuracy: 0.6997 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4071 - accuracy: 0.8130 - val_loss: 0.5911 - val_accuracy: 0.7032 - lr: 0.0010
Epoch 15/400
246/257 [===========================>..] - ETA: 0s - loss: 0.3936 - accuracy: 0.8214
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3942 - accuracy: 0.8208 - val_loss: 0.5971 - val_accuracy: 0.7021 - lr: 0.0010
253/253 [==============================] - 0s 841us/step
Independent Testing Matthews Correlation:  0.42353603231169995
Confusion Matrix :
 [[2821 1227]
 [1107 2940]]
Accuracy on test set:    0.7116738727609636
Sensitivity:    0.72646404744255 	 Specificity:    0.6968873517786561
Precision  : 0.7055435565154787
Area Under Curve:    0.711675699610603
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5848 - accuracy: 0.6858 - val_loss: 0.5586 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7255 - val_loss: 0.5462 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7356 - val_loss: 0.5449 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7417 - val_loss: 0.5475 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7506 - val_loss: 0.5430 - val_accuracy: 0.7168 - lr: 0.0010

Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7595 - val_loss: 0.5508 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 7/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4825 - accuracy: 0.7671
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7666 - val_loss: 0.5518 - val_accuracy: 0.7116 - lr: 0.0010
253/253 [==============================] - 0s 863us/step
Independent Testing Matthews Correlation:  0.4270668766477384
Confusion Matrix :
 [[2604 1443]
 [ 892 3156]]
Accuracy on test set:    0.711550339715874
Sensitivity:    0.7796442687747036 	 Specificity:    0.6434395848776872
Precision  : 0.6862361382909328
Area Under Curve:    0.7115419268261953
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5857 - accuracy: 0.6857 - val_loss: 0.5503 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5413 - accuracy: 0.7231 - val_loss: 0.5425 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5245 - accuracy: 0.7372 - val_loss: 0.5444 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5110 - accuracy: 0.7450 - val_loss: 0.5404 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5003 - accuracy: 0.7550 - val_loss: 0.5470 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.7624 - val_loss: 0.5445 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4765 - accuracy: 0.7715 - val_loss: 0.5477 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4653 - accuracy: 0.7799 - val_loss: 0.5494 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4530 - accuracy: 0.7865
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4528 - accuracy: 0.7867 - val_loss: 0.5575 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4025795766140259
Confusion Matrix :
 [[2480 1567]
 [ 875 3173]]
Accuracy on test set:    0.698332303891291
Sensitivity:    0.7838438735177866 	 Specificity:    0.6127996046454164
Precision  : 0.669409282700422
Area Under Curve:    0.6983217390816016
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6820 - val_loss: 0.5514 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7247 - val_loss: 0.5414 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7315 - val_loss: 0.5397 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7411 - val_loss: 0.5416 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7477 - val_loss: 0.5369 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7547 - val_loss: 0.5480 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.7631 - val_loss: 0.5426 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4750 - accuracy: 0.7728 - val_loss: 0.5486 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4629 - accuracy: 0.7805 - val_loss: 0.5506 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4499 - accuracy: 0.7870
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4499 - accuracy: 0.7870 - val_loss: 0.5623 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 997us/step
Independent Testing Matthews Correlation:  0.4221338257710919
Confusion Matrix :
 [[2590 1457]
 [ 898 3149]]
Accuracy on test set:    0.7090437361008154
Sensitivity:    0.778107239930813 	 Specificity:    0.6399802322708179
Precision  : 0.6836734693877551
Area Under Curve:    0.7090437361008154
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5867 - accuracy: 0.6833 - val_loss: 0.5523 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7251 - val_loss: 0.5462 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7350 - val_loss: 0.5460 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7437 - val_loss: 0.5412 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7499 - val_loss: 0.5451 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7578 - val_loss: 0.5421 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4827 - accuracy: 0.7673 - val_loss: 0.5482 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4706 - accuracy: 0.7753 - val_loss: 0.5525 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4584 - accuracy: 0.7817
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4585 - accuracy: 0.7815 - val_loss: 0.5519 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 889us/step
Independent Testing Matthews Correlation:  0.43736401236669886
Confusion Matrix :
 [[2901 1146]
 [1131 2916]]
Accuracy on test set:    0.7186805040770942
Sensitivity:    0.720533728687917 	 Specificity:    0.7168272794662713
Precision  : 0.7178729689807977
Area Under Curve:    0.7186805040770942
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5873 - accuracy: 0.6836 - val_loss: 0.5527 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7222 - val_loss: 0.5453 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7335 - val_loss: 0.5461 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7425 - val_loss: 0.5420 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7510 - val_loss: 0.5461 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4980 - accuracy: 0.7552 - val_loss: 0.5493 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4858 - accuracy: 0.7640 - val_loss: 0.5510 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4733 - accuracy: 0.7735
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7732 - val_loss: 0.5529 - val_accuracy: 0.7128 - lr: 0.0010

253/253 [==============================] - 0s 916us/step
Independent Testing Matthews Correlation:  0.43438627718069994
Confusion Matrix :
 [[3066  981]
 [1314 2733]]
Accuracy on test set:    0.7164566345441068
Sensitivity:    0.6753150481838399 	 Specificity:    0.7575982209043736
Precision  : 0.7358642972536349
Area Under Curve:    0.7164566345441068
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5875 - accuracy: 0.6838 - val_loss: 0.5505 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7236 - val_loss: 0.5454 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7350 - val_loss: 0.5468 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7420 - val_loss: 0.5403 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7482 - val_loss: 0.5437 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7575 - val_loss: 0.5455 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.7639 - val_loss: 0.5426 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4758 - accuracy: 0.7712 - val_loss: 0.5474 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4654 - accuracy: 0.7770 - val_loss: 0.5598 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4529 - accuracy: 0.7852 - val_loss: 0.5536 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4420 - accuracy: 0.7930 - val_loss: 0.5667 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4319 - accuracy: 0.7990 - val_loss: 0.5672 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4206 - accuracy: 0.8049 - val_loss: 0.5784 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4116 - accuracy: 0.8107 - val_loss: 0.5802 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3987 - accuracy: 0.8194 - val_loss: 0.5896 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3919 - accuracy: 0.8210 - val_loss: 0.6052 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 17/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3799 - accuracy: 0.8278 - val_loss: 0.5985 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 18/400
247/257 [===========================>..] - ETA: 0s - loss: 0.3697 - accuracy: 0.8329
Epoch 18: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3701 - accuracy: 0.8329 - val_loss: 0.6139 - val_accuracy: 0.7080 - lr: 0.0010
253/253 [==============================] - 0s 939us/step
Independent Testing Matthews Correlation:  0.4136476257029238
Confusion Matrix :
 [[2848 1199]
 [1174 2873]]
Accuracy on test set:    0.706819866567828
Sensitivity:    0.7099085742525327 	 Specificity:    0.7037311588831233
Precision  : 0.7055500982318271
Area Under Curve:    0.7068198665678279
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5901 - accuracy: 0.6818 - val_loss: 0.5558 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7220 - val_loss: 0.5458 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7340 - val_loss: 0.5488 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7401 - val_loss: 0.5451 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7483 - val_loss: 0.5480 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7573 - val_loss: 0.5475 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7675 - val_loss: 0.5465 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4728 - accuracy: 0.7741 - val_loss: 0.5510 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.7825 - val_loss: 0.5580 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4466 - accuracy: 0.7895
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4466 - accuracy: 0.7895 - val_loss: 0.5627 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 783us/step
Independent Testing Matthews Correlation:  0.4648224713949103
Confusion Matrix :
 [[2772 1275]
 [ 899 3148]]
Accuracy on test set:    0.7314059797380776
Sensitivity:    0.7778601433160366 	 Specificity:    0.6849518161601186
Precision  : 0.7117341171150803
Area Under Curve:    0.7314059797380776
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5941 - accuracy: 0.6812 - val_loss: 0.5496 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5504 - accuracy: 0.7202 - val_loss: 0.5417 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5359 - accuracy: 0.7289 - val_loss: 0.5523 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5238 - accuracy: 0.7387 - val_loss: 0.5393 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5130 - accuracy: 0.7463 - val_loss: 0.5389 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5015 - accuracy: 0.7541 - val_loss: 0.5402 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4896 - accuracy: 0.7633 - val_loss: 0.5443 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7703 - val_loss: 0.5452 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4631 - accuracy: 0.7809 - val_loss: 0.5515 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4519 - accuracy: 0.7889 - val_loss: 0.5539 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4385 - accuracy: 0.7961 - val_loss: 0.5616 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 12/400
249/257 [============================>.] - ETA: 0s - loss: 0.4270 - accuracy: 0.8035
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4269 - accuracy: 0.8035 - val_loss: 0.5686 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4978825891763168
Confusion Matrix :
 [[2969 1078]
 [ 955 3092]]
Accuracy on test set:    0.7488262910798122
Sensitivity:    0.7640227328885594 	 Specificity:    0.733629849271065
Precision  : 0.7414868105515587
Area Under Curve:    0.7488262910798122
(8094, 2560) (8094,)
Mean MCC = 0.4318 + 0.0287 and Mean AUC = 0.7150 + 0.0147
Mean Sensitivity = 0.7421 + 0.0371 and Mean Specificity = 0.6879 + 0.0425 and Mean Accuracy = 0.7150 + 0.0147
Mean Precision = 0.7051 + 0.0217





Seed   : 301727

Epoch 1/400
257/257 [==============================] - 3s 9ms/step - loss: 0.5868 - accuracy: 0.6846 - val_loss: 0.5531 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7242 - val_loss: 0.5492 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7341 - val_loss: 0.5461 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7399 - val_loss: 0.5463 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7480 - val_loss: 0.5486 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7559 - val_loss: 0.5513 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7623 - val_loss: 0.5540 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4748 - accuracy: 0.7721 - val_loss: 0.5565 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4641 - accuracy: 0.7797 - val_loss: 0.5637 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4535 - accuracy: 0.7853 - val_loss: 0.5679 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4402 - accuracy: 0.7919
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4401 - accuracy: 0.7918 - val_loss: 0.5710 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 824us/step
Independent Testing Matthews Correlation:  0.396764355014794
Confusion Matrix :
 [[2782 1266]
 [1176 2871]]
Accuracy on test set:    0.698332303891291
Sensitivity:    0.7094143810229799 	 Specificity:    0.6872529644268774
Precision  : 0.6939811457577955
Area Under Curve:    0.6983336727249287
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5851 - accuracy: 0.6861 - val_loss: 0.5632 - val_accuracy: 0.7016 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5432 - accuracy: 0.7233 - val_loss: 0.5475 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7332 - val_loss: 0.5472 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7416 - val_loss: 0.5481 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7507 - val_loss: 0.5507 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7591 - val_loss: 0.5561 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4806 - accuracy: 0.7662 - val_loss: 0.5503 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4678 - accuracy: 0.7755 - val_loss: 0.5530 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4548 - accuracy: 0.7859 - val_loss: 0.5637 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4414 - accuracy: 0.7932 - val_loss: 0.5768 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4283 - accuracy: 0.8021 - val_loss: 0.5791 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4162 - accuracy: 0.8075 - val_loss: 0.5807 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4073 - accuracy: 0.8133 - val_loss: 0.5871 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 14/400
251/257 [============================>.] - ETA: 0s - loss: 0.3935 - accuracy: 0.8214
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3935 - accuracy: 0.8214 - val_loss: 0.5985 - val_accuracy: 0.7086 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4104814391186162
Confusion Matrix :
 [[2757 1291]
 [1097 2950]]
Accuracy on test set:    0.7050030883261272
Sensitivity:    0.7289350135903138 	 Specificity:    0.6810770750988142
Precision  : 0.6955906625795802
Area Under Curve:    0.7050060443445639
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5942 - accuracy: 0.6785 - val_loss: 0.5543 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5502 - accuracy: 0.7192 - val_loss: 0.5385 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5347 - accuracy: 0.7295 - val_loss: 0.5384 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5240 - accuracy: 0.7376 - val_loss: 0.5356 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5138 - accuracy: 0.7442 - val_loss: 0.5333 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7526 - val_loss: 0.5397 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7611 - val_loss: 0.5379 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7663 - val_loss: 0.5400 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4719 - accuracy: 0.7738
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7742 - val_loss: 0.5492 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41778380119449926
Confusion Matrix :
 [[2783 1264]
 [1094 2954]]
Accuracy on test set:    0.7087090796788141
Sensitivity:    0.7297430830039525 	 Specificity:    0.6876698789226587
Precision  : 0.7003319108582267
Area Under Curve:    0.7087064809633057
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5869 - accuracy: 0.6863 - val_loss: 0.5452 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7203 - val_loss: 0.5342 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7336 - val_loss: 0.5330 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5206 - accuracy: 0.7385 - val_loss: 0.5352 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5103 - accuracy: 0.7469 - val_loss: 0.5346 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.7527 - val_loss: 0.5425 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4902 - accuracy: 0.7614 - val_loss: 0.5358 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4805 - accuracy: 0.7656 - val_loss: 0.5381 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.7741 - val_loss: 0.5458 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4605 - accuracy: 0.7807
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4614 - accuracy: 0.7801 - val_loss: 0.5434 - val_accuracy: 0.7249 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40962554166068305
Confusion Matrix :
 [[2804 1243]
 [1147 2901]]
Accuracy on test set:    0.7047560222359481
Sensitivity:    0.7166501976284585 	 Specificity:    0.6928589078329627
Precision  : 0.7000482625482626
Area Under Curve:    0.7047545527307106
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6853 - val_loss: 0.5555 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7224 - val_loss: 0.5460 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7328 - val_loss: 0.5510 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7419 - val_loss: 0.5443 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7502 - val_loss: 0.5451 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7579 - val_loss: 0.5441 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7663 - val_loss: 0.5496 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4678 - accuracy: 0.7772 - val_loss: 0.5548 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4550 - accuracy: 0.7844
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4554 - accuracy: 0.7839 - val_loss: 0.5630 - val_accuracy: 0.7146 - lr: 0.0010
253/253 [==============================] - 0s 939us/step
Independent Testing Matthews Correlation:  0.4332215249463938
Confusion Matrix :
 [[2866 1181]
 [1113 2934]]
Accuracy on test set:    0.7165801828514949
Sensitivity:    0.7249814677538917 	 Specificity:    0.708178897949098
Precision  : 0.7130012150668287
Area Under Curve:    0.716580182851495
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5832 - accuracy: 0.6874 - val_loss: 0.5524 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7229 - val_loss: 0.5441 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7346 - val_loss: 0.5430 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7431 - val_loss: 0.5450 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7523 - val_loss: 0.5404 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7592 - val_loss: 0.5431 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4803 - accuracy: 0.7682 - val_loss: 0.5488 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4677 - accuracy: 0.7763
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4677 - accuracy: 0.7764 - val_loss: 0.5514 - val_accuracy: 0.7240 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42987963209700675
Confusion Matrix :
 [[2742 1305]
 [1007 3040]]
Accuracy on test set:    0.7143563133185076
Sensitivity:    0.7511737089201878 	 Specificity:    0.6775389177168273
Precision  : 0.6996547756041427
Area Under Curve:    0.7143563133185076
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5855 - accuracy: 0.6860 - val_loss: 0.5526 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7235 - val_loss: 0.5439 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7340 - val_loss: 0.5426 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7421 - val_loss: 0.5399 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7517 - val_loss: 0.5453 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7588 - val_loss: 0.5472 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7680 - val_loss: 0.5463 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4718 - accuracy: 0.7745 - val_loss: 0.5490 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4584 - accuracy: 0.7827 - val_loss: 0.5526 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4482 - accuracy: 0.7902 - val_loss: 0.5579 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4325 - accuracy: 0.7978 - val_loss: 0.5596 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4207 - accuracy: 0.8066
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4215 - accuracy: 0.8063 - val_loss: 0.5698 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41343463335966624
Confusion Matrix :
 [[2983 1064]
 [1313 2734]]
Accuracy on test set:    0.7063256733382752
Sensitivity:    0.6755621447986162 	 Specificity:    0.7370892018779343
Precision  : 0.7198525539757767
Area Under Curve:    0.7063256733382752
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5949 - accuracy: 0.6780 - val_loss: 0.5543 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5497 - accuracy: 0.7208 - val_loss: 0.5426 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5339 - accuracy: 0.7314 - val_loss: 0.5407 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5212 - accuracy: 0.7387 - val_loss: 0.5423 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7473 - val_loss: 0.5385 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7562 - val_loss: 0.5414 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7639 - val_loss: 0.5451 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4730 - accuracy: 0.7749
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4730 - accuracy: 0.7749 - val_loss: 0.5460 - val_accuracy: 0.7220 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44532349732127696
Confusion Matrix :
 [[2823 1224]
 [1023 3024]]
Accuracy on test set:    0.7223869532987398
Sensitivity:    0.7472201630837657 	 Specificity:    0.6975537435137139
Precision  : 0.711864406779661
Area Under Curve:    0.7223869532987397
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5898 - accuracy: 0.6841 - val_loss: 0.5532 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5481 - accuracy: 0.7212 - val_loss: 0.5461 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5332 - accuracy: 0.7317 - val_loss: 0.5430 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7396 - val_loss: 0.5445 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7499 - val_loss: 0.5461 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7581 - val_loss: 0.5452 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7657 - val_loss: 0.5508 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.7738 - val_loss: 0.5541 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4557 - accuracy: 0.7838 - val_loss: 0.5599 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4416 - accuracy: 0.7919
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4415 - accuracy: 0.7921 - val_loss: 0.5783 - val_accuracy: 0.7104 - lr: 0.0010
253/253 [==============================] - 0s 855us/step
Independent Testing Matthews Correlation:  0.4634862922881463
Confusion Matrix :
 [[2692 1355]
 [ 832 3215]]
Accuracy on test set:    0.7297998517420311
Sensitivity:    0.7944156165060539 	 Specificity:    0.6651840869780083
Precision  : 0.7035010940919038
Area Under Curve:    0.7297998517420311
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5938 - accuracy: 0.6787 - val_loss: 0.5549 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5518 - accuracy: 0.7179 - val_loss: 0.5505 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5369 - accuracy: 0.7290 - val_loss: 0.5480 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5251 - accuracy: 0.7366 - val_loss: 0.5459 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7454 - val_loss: 0.5440 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7521 - val_loss: 0.5590 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7589 - val_loss: 0.5483 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7668 - val_loss: 0.5479 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4725 - accuracy: 0.7742 - val_loss: 0.5506 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4582 - accuracy: 0.7818 - val_loss: 0.5555 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4453 - accuracy: 0.7907 - val_loss: 0.5652 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - ETA: 0s - loss: 0.4308 - accuracy: 0.7995
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4308 - accuracy: 0.7995 - val_loss: 0.5753 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4949311829925639
Confusion Matrix :
 [[2961 1086]
 [ 959 3088]]
Accuracy on test set:    0.747343711391154
Sensitivity:    0.7630343464294539 	 Specificity:    0.7316530763528539
Precision  : 0.7398179204599904
Area Under Curve:    0.7473437113911539
(8094, 2560) (8094,)
Mean MCC = 0.4315 + 0.0281 and Mean AUC = 0.7154 + 0.0139
Mean Sensitivity = 0.7341 + 0.0307 and Mean Specificity = 0.6966 + 0.0219 and Mean Accuracy = 0.7154 + 0.0139
Mean Precision = 0.7078 + 0.0132





Seed   : 394383
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5865 - accuracy: 0.6852 - val_loss: 0.5551 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7231 - val_loss: 0.5497 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7336 - val_loss: 0.5408 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7424 - val_loss: 0.5460 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7513 - val_loss: 0.5401 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7593 - val_loss: 0.5440 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7666 - val_loss: 0.5448 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.7735 - val_loss: 0.5535 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4596 - accuracy: 0.7830 - val_loss: 0.5583 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4488 - accuracy: 0.7886 - val_loss: 0.5618 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 11/400
256/257 [============================>.] - ETA: 0s - loss: 0.4372 - accuracy: 0.7964
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4372 - accuracy: 0.7964 - val_loss: 0.5594 - val_accuracy: 0.7115 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41027909848860716
Confusion Matrix :
 [[2752 1296]
 [1093 2954]]
Accuracy on test set:    0.7048795552810376
Sensitivity:    0.7299234000494194 	 Specificity:    0.6798418972332015
Precision  : 0.6950588235294117
Area Under Curve:    0.7048826486413104
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6829 - val_loss: 0.5547 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7254 - val_loss: 0.5470 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7344 - val_loss: 0.5456 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7430 - val_loss: 0.5428 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7513 - val_loss: 0.5446 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7597 - val_loss: 0.5443 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7659 - val_loss: 0.5509 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4698 - accuracy: 0.7744 - val_loss: 0.5516 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4544 - accuracy: 0.7859
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4547 - accuracy: 0.7854 - val_loss: 0.5578 - val_accuracy: 0.7068 - lr: 0.0010
253/253 [==============================] - 0s 822us/step
Independent Testing Matthews Correlation:  0.41721058356062884
Confusion Matrix :
 [[2841 1207]
 [1152 2895]]
Accuracy on test set:    0.7085855466337245
Sensitivity:    0.7153446997776131 	 Specificity:    0.7018280632411067
Precision  : 0.7057532910775232
Area Under Curve:    0.7085863815093599
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5893 - accuracy: 0.6821 - val_loss: 0.5452 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7219 - val_loss: 0.5333 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7332 - val_loss: 0.5281 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7432 - val_loss: 0.5277 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7482 - val_loss: 0.5300 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7581 - val_loss: 0.5335 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7654 - val_loss: 0.5309 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4755 - accuracy: 0.7743
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7743 - val_loss: 0.5391 - val_accuracy: 0.7237 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.426587888687428
Confusion Matrix :
 [[2674 1373]
 [ 957 3091]]
Accuracy on test set:    0.7121680049413218
Sensitivity:    0.7635869565217391 	 Specificity:    0.6607363479120336
Precision  : 0.6924283154121864
Area Under Curve:    0.7121616522168863
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6847 - val_loss: 0.5484 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7200 - val_loss: 0.5325 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7347 - val_loss: 0.5300 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7407 - val_loss: 0.5323 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7487 - val_loss: 0.5329 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7592 - val_loss: 0.5406 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4811 - accuracy: 0.7679 - val_loss: 0.5356 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7757 - val_loss: 0.5434 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4548 - accuracy: 0.7856 - val_loss: 0.5453 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4418 - accuracy: 0.7935
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4418 - accuracy: 0.7935 - val_loss: 0.5600 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41808809574599953
Confusion Matrix :
 [[2543 1504]
 [ 872 3176]]
Accuracy on test set:    0.706485484867202
Sensitivity:    0.7845849802371542 	 Specificity:    0.6283666913763282
Precision  : 0.6786324786324787
Area Under Curve:    0.7064758358067411
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5846 - accuracy: 0.6856 - val_loss: 0.5506 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7217 - val_loss: 0.5399 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7315 - val_loss: 0.5442 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7418 - val_loss: 0.5403 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.7499 - val_loss: 0.5483 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7587 - val_loss: 0.5433 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4831 - accuracy: 0.7664 - val_loss: 0.5499 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7723 - val_loss: 0.5504 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4608 - accuracy: 0.7825 - val_loss: 0.5570 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4472 - accuracy: 0.7895 - val_loss: 0.5675 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 11/400
249/257 [============================>.] - ETA: 0s - loss: 0.4351 - accuracy: 0.7987
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4351 - accuracy: 0.7989 - val_loss: 0.5600 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4172918622292069
Confusion Matrix :
 [[2806 1241]
 [1118 2929]]
Accuracy on test set:    0.7085495428712627
Sensitivity:    0.7237459846800098 	 Specificity:    0.6933531010625155
Precision  : 0.7023980815347722
Area Under Curve:    0.7085495428712626
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5860 - accuracy: 0.6854 - val_loss: 0.5538 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7231 - val_loss: 0.5451 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7336 - val_loss: 0.5479 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7417 - val_loss: 0.5451 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5038 - accuracy: 0.7508 - val_loss: 0.5578 - val_accuracy: 0.7174 - lr: 0.0010

Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7587 - val_loss: 0.5505 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4807 - accuracy: 0.7677
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4811 - accuracy: 0.7671 - val_loss: 0.5497 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4439710957030328
Confusion Matrix :
 [[2863 1184]
 [1067 2980]]
Accuracy on test set:    0.721892760069187
Sensitivity:    0.7363479120336052 	 Specificity:    0.707437608104769
Precision  : 0.7156580211335255
Area Under Curve:    0.7218927600691871
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5908 - accuracy: 0.6808 - val_loss: 0.5581 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7211 - val_loss: 0.5426 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7334 - val_loss: 0.5382 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7401 - val_loss: 0.5396 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7487 - val_loss: 0.5428 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7584 - val_loss: 0.5459 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7676 - val_loss: 0.5435 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7761 - val_loss: 0.5525 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4552 - accuracy: 0.7837 - val_loss: 0.5599 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4427 - accuracy: 0.7910 - val_loss: 0.5600 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4284 - accuracy: 0.8020 - val_loss: 0.5707 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4165 - accuracy: 0.8088
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4168 - accuracy: 0.8087 - val_loss: 0.5786 - val_accuracy: 0.7154 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41907597380410405
Confusion Matrix :
 [[2873 1174]
 [1177 2870]]
Accuracy on test set:    0.7095379293303682
Sensitivity:    0.7091672844082036 	 Specificity:    0.7099085742525327
Precision  : 0.7096933728981206
Area Under Curve:    0.7095379293303682
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5925 - accuracy: 0.6801 - val_loss: 0.5482 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7218 - val_loss: 0.5472 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7328 - val_loss: 0.5341 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7393 - val_loss: 0.5380 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.7475 - val_loss: 0.5366 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5000 - accuracy: 0.7557 - val_loss: 0.5377 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7636 - val_loss: 0.5393 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4753 - accuracy: 0.7709 - val_loss: 0.5445 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4615 - accuracy: 0.7796
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4615 - accuracy: 0.7796 - val_loss: 0.5474 - val_accuracy: 0.7235 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43258124188696123
Confusion Matrix :
 [[2986 1061]
 [1237 2810]]
Accuracy on test set:    0.7160859896219421
Sensitivity:    0.694341487521621 	 Specificity:    0.7378304917222634
Precision  : 0.7259106174115215
Area Under Curve:    0.7160859896219421
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5888 - accuracy: 0.6800 - val_loss: 0.5555 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7208 - val_loss: 0.5505 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7337 - val_loss: 0.5415 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7424 - val_loss: 0.5449 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7511 - val_loss: 0.5446 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7592 - val_loss: 0.5532 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7687 - val_loss: 0.5504 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4667 - accuracy: 0.7779 - val_loss: 0.5535 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 9/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4508 - accuracy: 0.7884
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4509 - accuracy: 0.7883 - val_loss: 0.5626 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4607491588158154
Confusion Matrix :
 [[2902 1145]
 [1038 3009]]
Accuracy on test set:    0.7302940449715839
Sensitivity:    0.7435137138621201 	 Specificity:    0.7170743760810477
Precision  : 0.7243620606644199
Area Under Curve:    0.7302940449715839
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6828 - val_loss: 0.5542 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7219 - val_loss: 0.5481 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7342 - val_loss: 0.5453 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7420 - val_loss: 0.5454 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7497 - val_loss: 0.5468 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7596 - val_loss: 0.5494 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7707 - val_loss: 0.5545 - val_accuracy: 0.7154 - lr: 0.0010

Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4687 - accuracy: 0.7776
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4692 - accuracy: 0.7775 - val_loss: 0.5578 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4829053534483062
Confusion Matrix :
 [[3037 1010]
 [1083 2964]]
Accuracy on test set:    0.7414133926365208
Sensitivity:    0.7323943661971831 	 Specificity:    0.7504324190758587
Precision  : 0.7458480120785104
Area Under Curve:    0.741413392636521
(8094, 2560) (8094,)
Mean MCC = 0.4329 + 0.0220 and Mean AUC = 0.7160 + 0.0113
Mean Sensitivity = 0.7333 + 0.0249 and Mean Specificity = 0.6987 + 0.0340 and Mean Accuracy = 0.7160 + 0.0113
Mean Precision = 0.7096 + 0.0183





Seed   : 516667
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6835 - val_loss: 0.5533 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7255 - val_loss: 0.5489 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7354 - val_loss: 0.5467 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7432 - val_loss: 0.5445 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7523 - val_loss: 0.5454 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4927 - accuracy: 0.7614 - val_loss: 0.5557 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4808 - accuracy: 0.7670
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4806 - accuracy: 0.7669 - val_loss: 0.5542 - val_accuracy: 0.7137 - lr: 0.0010
253/253 [==============================] - 0s 943us/step
Independent Testing Matthews Correlation:  0.4014299625051442
Confusion Matrix :
 [[2656 1392]
 [1037 3010]]
Accuracy on test set:    0.6999382334774552
Sensitivity:    0.7437608104768965 	 Specificity:    0.6561264822134387
Precision  : 0.6837800999545661
Area Under Curve:    0.6999436463451676
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6824 - val_loss: 0.5538 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7230 - val_loss: 0.5443 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7355 - val_loss: 0.5433 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7409 - val_loss: 0.5441 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7495 - val_loss: 0.5429 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7556 - val_loss: 0.5473 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7650 - val_loss: 0.5485 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4729 - accuracy: 0.7736 - val_loss: 0.5540 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4585 - accuracy: 0.7820 - val_loss: 0.5560 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4450 - accuracy: 0.7902
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4452 - accuracy: 0.7903 - val_loss: 0.5603 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 909us/step
Independent Testing Matthews Correlation:  0.42091358388028743
Confusion Matrix :
 [[2903 1145]
 [1199 2848]]
Accuracy on test set:    0.710438542310068
Sensitivity:    0.7037311588831233 	 Specificity:    0.7171442687747036
Precision  : 0.7132481843225645
Area Under Curve:    0.7104377138289135
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5853 - accuracy: 0.6848 - val_loss: 0.5414 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7233 - val_loss: 0.5351 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7355 - val_loss: 0.5325 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7422 - val_loss: 0.5324 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7507 - val_loss: 0.5323 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7590 - val_loss: 0.5386 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.7671 - val_loss: 0.5321 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4682 - accuracy: 0.7755 - val_loss: 0.5395 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4544 - accuracy: 0.7829 - val_loss: 0.5389 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4413 - accuracy: 0.7912 - val_loss: 0.5425 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4282 - accuracy: 0.8009 - val_loss: 0.5509 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4174 - accuracy: 0.8056
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4180 - accuracy: 0.8050 - val_loss: 0.5537 - val_accuracy: 0.7167 - lr: 0.0010
253/253 [==============================] - 0s 892us/step
Independent Testing Matthews Correlation:  0.41322136726250797
Confusion Matrix :
 [[2851 1196]
 [1179 2869]]
Accuracy on test set:    0.7066090179122916
Sensitivity:    0.7087450592885376 	 Specificity:    0.7044724487274524
Precision  : 0.7057810578105781
Area Under Curve:    0.706608754007995
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5905 - accuracy: 0.6799 - val_loss: 0.5446 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7219 - val_loss: 0.5347 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7340 - val_loss: 0.5345 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7420 - val_loss: 0.5326 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7509 - val_loss: 0.5350 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.7591 - val_loss: 0.5349 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4795 - accuracy: 0.7677
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7679 - val_loss: 0.5404 - val_accuracy: 0.7201 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41173695336549876
Confusion Matrix :
 [[2851 1196]
 [1185 2863]]
Accuracy on test set:    0.7058678196417542
Sensitivity:    0.7072628458498024 	 Specificity:    0.7044724487274524
Precision  : 0.7053461443705347
Area Under Curve:    0.7058676472886275
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5871 - accuracy: 0.6832 - val_loss: 0.5503 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7208 - val_loss: 0.5370 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7330 - val_loss: 0.5369 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7413 - val_loss: 0.5362 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7500 - val_loss: 0.5391 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4928 - accuracy: 0.7591 - val_loss: 0.5399 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4813 - accuracy: 0.7684
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7687 - val_loss: 0.5477 - val_accuracy: 0.7257 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.434743204425631
Confusion Matrix :
 [[2742 1305]
 [ 988 3059]]
Accuracy on test set:    0.7167037311588831
Sensitivity:    0.755868544600939 	 Specificity:    0.6775389177168273
Precision  : 0.7009624197983502
Area Under Curve:    0.7167037311588832
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5897 - accuracy: 0.6824 - val_loss: 0.5479 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7225 - val_loss: 0.5406 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7324 - val_loss: 0.5390 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7420 - val_loss: 0.5369 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7486 - val_loss: 0.5387 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4954 - accuracy: 0.7560 - val_loss: 0.5404 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7657 - val_loss: 0.5436 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4677 - accuracy: 0.7738 - val_loss: 0.5546 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4538 - accuracy: 0.7858
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4541 - accuracy: 0.7853 - val_loss: 0.5550 - val_accuracy: 0.7142 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.430802498201427
Confusion Matrix :
 [[3066  981]
 [1329 2718]]
Accuracy on test set:    0.7146034099332839
Sensitivity:    0.6716085989621943 	 Specificity:    0.7575982209043736
Precision  : 0.7347931873479319
Area Under Curve:    0.714603409933284
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5903 - accuracy: 0.6833 - val_loss: 0.5470 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7206 - val_loss: 0.5420 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7302 - val_loss: 0.5363 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7380 - val_loss: 0.5378 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7466 - val_loss: 0.5384 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5008 - accuracy: 0.7528 - val_loss: 0.5377 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7640 - val_loss: 0.5396 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4752 - accuracy: 0.7720 - val_loss: 0.5431 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4627 - accuracy: 0.7815
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4626 - accuracy: 0.7815 - val_loss: 0.5469 - val_accuracy: 0.7249 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4341488051775175
Confusion Matrix :
 [[2901 1146]
 [1144 2903]]
Accuracy on test set:    0.7170743760810477
Sensitivity:    0.717321472695824 	 Specificity:    0.7168272794662713
Precision  : 0.7169671523833046
Area Under Curve:    0.7170743760810476
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5874 - accuracy: 0.6833 - val_loss: 0.5452 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7216 - val_loss: 0.5422 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7317 - val_loss: 0.5314 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5210 - accuracy: 0.7390 - val_loss: 0.5343 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7486 - val_loss: 0.5318 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7557 - val_loss: 0.5466 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 3ms/step - loss: 0.4847 - accuracy: 0.7660 - val_loss: 0.5356 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4724 - accuracy: 0.7753
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4725 - accuracy: 0.7749 - val_loss: 0.5373 - val_accuracy: 0.7270 - lr: 0.0010
253/253 [==============================] - 0s 984us/step
Independent Testing Matthews Correlation:  0.441375044986857
Confusion Matrix :
 [[2950 1097]
 [1164 2883]]
Accuracy on test set:    0.7206572769953051
Sensitivity:    0.7123795404002965 	 Specificity:    0.7289350135903138
Precision  : 0.7243718592964824
Area Under Curve:    0.7206572769953052
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5910 - accuracy: 0.6828 - val_loss: 0.5459 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5502 - accuracy: 0.7184 - val_loss: 0.5379 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5353 - accuracy: 0.7296 - val_loss: 0.5340 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5237 - accuracy: 0.7381 - val_loss: 0.5326 - val_accuracy: 0.7311 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7443 - val_loss: 0.5348 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5033 - accuracy: 0.7515 - val_loss: 0.5351 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.7603 - val_loss: 0.5439 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.7678 - val_loss: 0.5377 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4711 - accuracy: 0.7747
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7752 - val_loss: 0.5434 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 834us/step
Independent Testing Matthews Correlation:  0.46952558822927565
Confusion Matrix :
 [[3044 1003]
 [1145 2902]]
Accuracy on test set:    0.7346182357301705
Sensitivity:    0.7170743760810477 	 Specificity:    0.7521620953792933
Precision  : 0.7431498079385404
Area Under Curve:    0.7346182357301706
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5901 - accuracy: 0.6828 - val_loss: 0.5480 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5496 - accuracy: 0.7186 - val_loss: 0.5432 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5330 - accuracy: 0.7299 - val_loss: 0.5383 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7393 - val_loss: 0.5407 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5103 - accuracy: 0.7491 - val_loss: 0.5389 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4991 - accuracy: 0.7549 - val_loss: 0.5411 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.7640 - val_loss: 0.5469 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4730 - accuracy: 0.7740 - val_loss: 0.5515 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4616 - accuracy: 0.7830 - val_loss: 0.5641 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4480 - accuracy: 0.7907 - val_loss: 0.5491 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4373 - accuracy: 0.7984
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4372 - accuracy: 0.7982 - val_loss: 0.5698 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 853us/step
Independent Testing Matthews Correlation:  0.48154239335125404
Confusion Matrix :
 [[3084  963]
 [1137 2910]]
Accuracy on test set:    0.7405485544848036
Sensitivity:    0.7190511489992587 	 Specificity:    0.7620459599703484
Precision  : 0.7513555383423702
Area Under Curve:    0.7405485544848035
(8094, 2560) (8094,)
Mean MCC = 0.4339 + 0.0240 and Mean AUC = 0.7167 + 0.0120
Mean Sensitivity = 0.7157 + 0.0215 and Mean Specificity = 0.7177 + 0.0326 and Mean Accuracy = 0.7167 + 0.0120
Mean Precision = 0.7180 + 0.0197





Seed   : 126807
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5817 - accuracy: 0.6901 - val_loss: 0.5602 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5413 - accuracy: 0.7251 - val_loss: 0.5539 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5263 - accuracy: 0.7372 - val_loss: 0.5513 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5141 - accuracy: 0.7448 - val_loss: 0.5536 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7523 - val_loss: 0.5536 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7611 - val_loss: 0.5580 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7692 - val_loss: 0.5580 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7769 - val_loss: 0.5593 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4577 - accuracy: 0.7844 - val_loss: 0.5614 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4420 - accuracy: 0.7961 - val_loss: 0.5702 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 11/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4286 - accuracy: 0.8012
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4294 - accuracy: 0.8006 - val_loss: 0.5716 - val_accuracy: 0.7115 - lr: 0.0010
253/253 [==============================] - 0s 896us/step
Independent Testing Matthews Correlation:  0.39741839924486144
Confusion Matrix :
 [[2845 1203]
 [1236 2811]]
Accuracy on test set:    0.6987029030265596
Sensitivity:    0.6945885841363973 	 Specificity:    0.7028162055335968
Precision  : 0.7002989536621823
Area Under Curve:    0.6987023948349972
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5879 - accuracy: 0.6839 - val_loss: 0.5630 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5435 - accuracy: 0.7243 - val_loss: 0.5582 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5286 - accuracy: 0.7347 - val_loss: 0.5524 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7405 - val_loss: 0.5511 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5073 - accuracy: 0.7478 - val_loss: 0.5563 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 3ms/step - loss: 0.4978 - accuracy: 0.7565 - val_loss: 0.5558 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 3ms/step - loss: 0.4869 - accuracy: 0.7612 - val_loss: 0.5612 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4754 - accuracy: 0.7708 - val_loss: 0.5593 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4649 - accuracy: 0.7805 - val_loss: 0.5595 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4522 - accuracy: 0.7860
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 3ms/step - loss: 0.4522 - accuracy: 0.7860 - val_loss: 0.5771 - val_accuracy: 0.7072 - lr: 0.0010
253/253 [==============================] - 0s 917us/step
Independent Testing Matthews Correlation:  0.42346362211107597
Confusion Matrix :
 [[2653 1395]
 [ 949 3098]]
Accuracy on test set:    0.710438542310068
Sensitivity:    0.7655053125772177 	 Specificity:    0.6553853754940712
Precision  : 0.6895170264856444
Area Under Curve:    0.7104453440356444
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6855 - val_loss: 0.5480 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7227 - val_loss: 0.5430 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7332 - val_loss: 0.5384 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7422 - val_loss: 0.5373 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7505 - val_loss: 0.5414 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7575 - val_loss: 0.5412 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7658 - val_loss: 0.5437 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7751 - val_loss: 0.5512 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4591 - accuracy: 0.7815 - val_loss: 0.5510 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4481 - accuracy: 0.7900 - val_loss: 0.5562 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4349 - accuracy: 0.7994
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4350 - accuracy: 0.7989 - val_loss: 0.5560 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4237246369120178
Confusion Matrix :
 [[2965 1082]
 [1252 2796]]
Accuracy on test set:    0.7116738727609636
Sensitivity:    0.6907114624505929 	 Specificity:    0.7326414628119595
Precision  : 0.7209902011346054
Area Under Curve:    0.7116764626312762
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5863 - accuracy: 0.6846 - val_loss: 0.5479 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7238 - val_loss: 0.5387 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7332 - val_loss: 0.5393 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7391 - val_loss: 0.5368 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7486 - val_loss: 0.5384 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7584 - val_loss: 0.5420 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7642 - val_loss: 0.5383 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4753 - accuracy: 0.7708 - val_loss: 0.5418 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4616 - accuracy: 0.7831 - val_loss: 0.5519 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4484 - accuracy: 0.7898
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4490 - accuracy: 0.7893 - val_loss: 0.5519 - val_accuracy: 0.7237 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4140788166608641
Confusion Matrix :
 [[2775 1272]
 [1101 2947]]
Accuracy on test set:    0.7068560840024707
Sensitivity:    0.7280138339920948 	 Specificity:    0.6856931060044478
Precision  : 0.6985067551552501
Area Under Curve:    0.7068534699982713
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5862 - accuracy: 0.6857 - val_loss: 0.5539 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7221 - val_loss: 0.5478 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7320 - val_loss: 0.5414 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7390 - val_loss: 0.5475 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7458 - val_loss: 0.5483 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4999 - accuracy: 0.7545 - val_loss: 0.5458 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7600 - val_loss: 0.5449 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7667 - val_loss: 0.5504 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4683 - accuracy: 0.7757 - val_loss: 0.5571 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4571 - accuracy: 0.7839 - val_loss: 0.5653 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4483 - accuracy: 0.7890 - val_loss: 0.5675 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4351 - accuracy: 0.7973 - val_loss: 0.5831 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4235 - accuracy: 0.8041 - val_loss: 0.5784 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4148 - accuracy: 0.8076 - val_loss: 0.5869 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4037 - accuracy: 0.8151 - val_loss: 0.5840 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - ETA: 0s - loss: 0.3938 - accuracy: 0.8200
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3938 - accuracy: 0.8200 - val_loss: 0.5968 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4193538890057157
Confusion Matrix :
 [[2729 1318]
 [1036 3011]]
Accuracy on test set:    0.7091672844082036
Sensitivity:    0.7440079070916729 	 Specificity:    0.6743266617247343
Precision  : 0.6955416955416955
Area Under Curve:    0.7091672844082035
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5946 - accuracy: 0.6789 - val_loss: 0.5569 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7232 - val_loss: 0.5477 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7332 - val_loss: 0.5415 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7442 - val_loss: 0.5419 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7488 - val_loss: 0.5429 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7589 - val_loss: 0.5584 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4819 - accuracy: 0.7688 - val_loss: 0.5490 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4699 - accuracy: 0.7741 - val_loss: 0.5588 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4563 - accuracy: 0.7834
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4565 - accuracy: 0.7832 - val_loss: 0.5553 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42646579343506
Confusion Matrix :
 [[2665 1382]
 [ 949 3098]]
Accuracy on test set:    0.712008895478132
Sensitivity:    0.7655053125772177 	 Specificity:    0.6585124783790463
Precision  : 0.6915178571428572
Area Under Curve:    0.7120088954781318
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5905 - accuracy: 0.6828 - val_loss: 0.5534 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7223 - val_loss: 0.5452 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7321 - val_loss: 0.5429 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7400 - val_loss: 0.5436 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7477 - val_loss: 0.5444 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5008 - accuracy: 0.7541 - val_loss: 0.5422 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4886 - accuracy: 0.7617
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7614 - val_loss: 0.5479 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 918us/step
Independent Testing Matthews Correlation:  0.42853912596883914
Confusion Matrix :
 [[2928 1119]
 [1194 2853]]
Accuracy on test set:    0.7142327650111193
Sensitivity:    0.7049666419570052 	 Specificity:    0.7234988880652335
Precision  : 0.7182779456193353
Area Under Curve:    0.7142327650111194
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5871 - accuracy: 0.6842 - val_loss: 0.5570 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7208 - val_loss: 0.5450 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7349 - val_loss: 0.5418 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7412 - val_loss: 0.5423 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7517 - val_loss: 0.5426 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7573 - val_loss: 0.5490 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7642 - val_loss: 0.5433 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4738 - accuracy: 0.7749 - val_loss: 0.5491 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4631 - accuracy: 0.7809 - val_loss: 0.5525 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4504 - accuracy: 0.7902 - val_loss: 0.5592 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4370 - accuracy: 0.7976 - val_loss: 0.5612 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4263 - accuracy: 0.8036
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4265 - accuracy: 0.8034 - val_loss: 0.5689 - val_accuracy: 0.7200 - lr: 0.0010
253/253 [==============================] - 0s 860us/step
Independent Testing Matthews Correlation:  0.45570690411470777
Confusion Matrix :
 [[2824 1223]
 [ 983 3064]]
Accuracy on test set:    0.7274524339016556
Sensitivity:    0.7571040276748209 	 Specificity:    0.6978008401284902
Precision  : 0.714718917658036
Area Under Curve:    0.7274524339016556
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5931 - accuracy: 0.6799 - val_loss: 0.5556 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5513 - accuracy: 0.7195 - val_loss: 0.5494 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5362 - accuracy: 0.7286 - val_loss: 0.5466 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5250 - accuracy: 0.7388 - val_loss: 0.5457 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5154 - accuracy: 0.7435 - val_loss: 0.5475 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7508 - val_loss: 0.5503 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7602 - val_loss: 0.5534 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7669 - val_loss: 0.5576 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 9/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4722 - accuracy: 0.7774
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4732 - accuracy: 0.7766 - val_loss: 0.5585 - val_accuracy: 0.7137 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46069870777314664
Confusion Matrix :
 [[2831 1216]
 [ 970 3077]]
Accuracy on test set:    0.7299234000494194
Sensitivity:    0.7603162836669137 	 Specificity:    0.6995305164319249
Precision  : 0.7167481947356161
Area Under Curve:    0.7299234000494194
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5926 - accuracy: 0.6813 - val_loss: 0.5554 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5505 - accuracy: 0.7206 - val_loss: 0.5468 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5370 - accuracy: 0.7289 - val_loss: 0.5489 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7363 - val_loss: 0.5445 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7423 - val_loss: 0.5462 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7495 - val_loss: 0.5509 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - ETA: 0s - loss: 0.4974 - accuracy: 0.7575
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7575 - val_loss: 0.5563 - val_accuracy: 0.7145 - lr: 0.0010
253/253 [==============================] - 0s 826us/step
Independent Testing Matthews Correlation:  0.48444070462525535
Confusion Matrix :
 [[2864 1183]
 [ 908 3139]]
Accuracy on test set:    0.7416604892512972
Sensitivity:    0.7756362737830492 	 Specificity:    0.7076847047195454
Precision  : 0.7262841277186488
Area Under Curve:    0.7416604892512972
(8094, 2560) (8094,)
Mean MCC = 0.4334 + 0.0244 and Mean AUC = 0.7162 + 0.0122
Mean Sensitivity = 0.7386 + 0.0302 and Mean Specificity = 0.6938 + 0.0242 and Mean Accuracy = 0.7162 + 0.0122
Mean Precision = 0.7072 + 0.0128





Seed   : 76584
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5847 - accuracy: 0.6883 - val_loss: 0.5573 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7246 - val_loss: 0.5523 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5256 - accuracy: 0.7370 - val_loss: 0.5497 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5149 - accuracy: 0.7448 - val_loss: 0.5486 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7522 - val_loss: 0.5503 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7594 - val_loss: 0.5493 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7682 - val_loss: 0.5555 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4682 - accuracy: 0.7769 - val_loss: 0.5547 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 9/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4561 - accuracy: 0.7858
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4563 - accuracy: 0.7859 - val_loss: 0.5635 - val_accuracy: 0.7150 - lr: 0.0010
253/253 [==============================] - 0s 881us/step
Independent Testing Matthews Correlation:  0.385764313261029
Confusion Matrix :
 [[2643 1405]
 [1086 2961]]
Accuracy on test set:    0.6922791846819024
Sensitivity:    0.7316530763528539 	 Specificity:    0.6529150197628458
Precision  : 0.6781951442968392
Area Under Curve:    0.6922840480578499
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5838 - accuracy: 0.6893 - val_loss: 0.5626 - val_accuracy: 0.7012 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5403 - accuracy: 0.7270 - val_loss: 0.5490 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5261 - accuracy: 0.7362 - val_loss: 0.5489 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5129 - accuracy: 0.7469 - val_loss: 0.5485 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5024 - accuracy: 0.7533 - val_loss: 0.5494 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7615 - val_loss: 0.5485 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7691 - val_loss: 0.5506 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.7764 - val_loss: 0.5591 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4596 - accuracy: 0.7818
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4596 - accuracy: 0.7818 - val_loss: 0.5605 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42338546805782573
Confusion Matrix :
 [[2707 1341]
 [ 999 3048]]
Accuracy on test set:    0.7109326744904262
Sensitivity:    0.7531504818383988 	 Specificity:    0.6687252964426877
Precision  : 0.6944634313055366
Area Under Curve:    0.7109378891405432
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6817 - val_loss: 0.5546 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7214 - val_loss: 0.5530 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7330 - val_loss: 0.5442 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7421 - val_loss: 0.5454 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7506 - val_loss: 0.5495 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7555 - val_loss: 0.5514 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4861 - accuracy: 0.7644 - val_loss: 0.5506 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4744 - accuracy: 0.7732 - val_loss: 0.5530 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4636 - accuracy: 0.7810 - val_loss: 0.5522 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4496 - accuracy: 0.7889 - val_loss: 0.5553 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4361 - accuracy: 0.7964 - val_loss: 0.5639 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4238 - accuracy: 0.8051
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4236 - accuracy: 0.8051 - val_loss: 0.5679 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 960us/step
Independent Testing Matthews Correlation:  0.4153464779355708
Confusion Matrix :
 [[3011 1036]
 [1335 2713]]
Accuracy on test set:    0.7071031500926498
Sensitivity:    0.670207509881423 	 Specificity:    0.7440079070916729
Precision  : 0.7236596425713524
Area Under Curve:    0.7071077084865479
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5843 - accuracy: 0.6853 - val_loss: 0.5538 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7252 - val_loss: 0.5433 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7349 - val_loss: 0.5412 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7416 - val_loss: 0.5410 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7488 - val_loss: 0.5393 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7570 - val_loss: 0.5437 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7628 - val_loss: 0.5478 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7692 - val_loss: 0.5496 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4654 - accuracy: 0.7788 - val_loss: 0.5504 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4534 - accuracy: 0.7870 - val_loss: 0.5545 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4430 - accuracy: 0.7935 - val_loss: 0.5640 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4300 - accuracy: 0.8038 - val_loss: 0.5675 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4182 - accuracy: 0.8098 - val_loss: 0.5736 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4058 - accuracy: 0.8159 - val_loss: 0.5821 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 15/400
253/257 [============================>.] - ETA: 0s - loss: 0.3936 - accuracy: 0.8224
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3936 - accuracy: 0.8225 - val_loss: 0.5973 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41326387080558635
Confusion Matrix :
 [[2829 1218]
 [1157 2891]]
Accuracy on test set:    0.7066090179122916
Sensitivity:    0.7141798418972332 	 Specificity:    0.6990363232023721
Precision  : 0.7035775127768313
Area Under Curve:    0.7066080825498027
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5868 - accuracy: 0.6849 - val_loss: 0.5490 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7224 - val_loss: 0.5437 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7332 - val_loss: 0.5424 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7404 - val_loss: 0.5402 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7488 - val_loss: 0.5382 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7576 - val_loss: 0.5395 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7661 - val_loss: 0.5402 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4701 - accuracy: 0.7737 - val_loss: 0.5487 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4567 - accuracy: 0.7835
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4573 - accuracy: 0.7833 - val_loss: 0.5468 - val_accuracy: 0.7244 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42153086103066406
Confusion Matrix :
 [[2943 1104]
 [1238 2809]]
Accuracy on test set:    0.7106498640968619
Sensitivity:    0.6940943909068445 	 Specificity:    0.7272053372868792
Precision  : 0.7178635318170202
Area Under Curve:    0.7106498640968618
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5855 - accuracy: 0.6843 - val_loss: 0.5526 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7225 - val_loss: 0.5437 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7335 - val_loss: 0.5416 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7395 - val_loss: 0.5473 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5101 - accuracy: 0.7477 - val_loss: 0.5401 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.7547 - val_loss: 0.5443 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.7623 - val_loss: 0.5431 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7721 - val_loss: 0.5460 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4654 - accuracy: 0.7793 - val_loss: 0.5590 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4527 - accuracy: 0.7894 - val_loss: 0.5575 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4401 - accuracy: 0.7955 - val_loss: 0.5581 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4284 - accuracy: 0.8036 - val_loss: 0.5672 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 13/400
254/257 [============================>.] - ETA: 0s - loss: 0.4147 - accuracy: 0.8109
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4144 - accuracy: 0.8110 - val_loss: 0.5809 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 831us/step
Independent Testing Matthews Correlation:  0.4287302174095169
Confusion Matrix :
 [[2705 1342]
 [ 977 3070]]
Accuracy on test set:    0.7134914751667902
Sensitivity:    0.7585866073634792 	 Specificity:    0.6683963429701013
Precision  : 0.6958295557570263
Area Under Curve:    0.7134914751667902
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5917 - accuracy: 0.6786 - val_loss: 0.5599 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7221 - val_loss: 0.5463 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7344 - val_loss: 0.5466 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7422 - val_loss: 0.5414 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7486 - val_loss: 0.5440 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7568 - val_loss: 0.5420 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7659 - val_loss: 0.5458 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4688 - accuracy: 0.7757 - val_loss: 0.5486 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4569 - accuracy: 0.7818 - val_loss: 0.5583 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4445 - accuracy: 0.7913 - val_loss: 0.5570 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4338 - accuracy: 0.7989 - val_loss: 0.5594 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 12/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4205 - accuracy: 0.8047
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4209 - accuracy: 0.8042 - val_loss: 0.5659 - val_accuracy: 0.7187 - lr: 0.0010

253/253 [==============================] - 0s 753us/step
Independent Testing Matthews Correlation:  0.4254385505726305
Confusion Matrix :
 [[2702 1345]
 [ 987 3060]]
Accuracy on test set:    0.7118853471707438
Sensitivity:    0.7561156412157154 	 Specificity:    0.6676550531257722
Precision  : 0.6946651532349603
Area Under Curve:    0.7118853471707438
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5861 - accuracy: 0.6849 - val_loss: 0.5512 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7235 - val_loss: 0.5457 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7334 - val_loss: 0.5434 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7423 - val_loss: 0.5453 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7485 - val_loss: 0.5410 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7574 - val_loss: 0.5466 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7657 - val_loss: 0.5446 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4723 - accuracy: 0.7750 - val_loss: 0.5504 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4604 - accuracy: 0.7835 - val_loss: 0.5586 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4477 - accuracy: 0.7891 - val_loss: 0.5664 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4333 - accuracy: 0.7989 - val_loss: 0.5591 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4218 - accuracy: 0.8063 - val_loss: 0.5744 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 13/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4087 - accuracy: 0.8137
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4087 - accuracy: 0.8140 - val_loss: 0.5788 - val_accuracy: 0.7120 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41876864438774536
Confusion Matrix :
 [[3020 1027]
 [1330 2717]]
Accuracy on test set:    0.708796639486039
Sensitivity:    0.6713615023474179 	 Specificity:    0.7462317766246602
Precision  : 0.7256944444444444
Area Under Curve:    0.708796639486039
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5899 - accuracy: 0.6826 - val_loss: 0.5520 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7193 - val_loss: 0.5463 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7308 - val_loss: 0.5428 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7403 - val_loss: 0.5407 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7496 - val_loss: 0.5424 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7580 - val_loss: 0.5460 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4837 - accuracy: 0.7653
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7654 - val_loss: 0.5486 - val_accuracy: 0.7219 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4672611250162892
Confusion Matrix :
 [[2974 1073]
 [1083 2964]]
Accuracy on test set:    0.733629849271065
Sensitivity:    0.7323943661971831 	 Specificity:    0.7348653323449469
Precision  : 0.7342085707208323
Area Under Curve:    0.7336298492710649
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5931 - accuracy: 0.6801 - val_loss: 0.5578 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5509 - accuracy: 0.7190 - val_loss: 0.5546 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5347 - accuracy: 0.7307 - val_loss: 0.5531 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5225 - accuracy: 0.7391 - val_loss: 0.5489 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5102 - accuracy: 0.7495 - val_loss: 0.5495 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7562 - val_loss: 0.5532 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7626 - val_loss: 0.5539 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.7735 - val_loss: 0.5526 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4638 - accuracy: 0.7811
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4637 - accuracy: 0.7811 - val_loss: 0.5586 - val_accuracy: 0.7152 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.48776990632684325
Confusion Matrix :
 [[3152  895]
 [1183 2864]]
Accuracy on test set:    0.7432666172473437
Sensitivity:    0.7076847047195454 	 Specificity:    0.7788485297751421
Precision  : 0.7619047619047619
Area Under Curve:    0.7432666172473438
(8094, 2560) (8094,)
Mean MCC = 0.4287 + 0.0272 and Mean AUC = 0.7139 + 0.0137
Mean Sensitivity = 0.7189 + 0.0314 and Mean Specificity = 0.7088 + 0.0409 and Mean Accuracy = 0.7139 + 0.0137
Mean Precision = 0.7130 + 0.0233





Seed   : 99258
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5960 - accuracy: 0.6770 - val_loss: 0.5624 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5489 - accuracy: 0.7236 - val_loss: 0.5500 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5350 - accuracy: 0.7315 - val_loss: 0.5481 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5232 - accuracy: 0.7408 - val_loss: 0.5457 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5122 - accuracy: 0.7484 - val_loss: 0.5481 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5021 - accuracy: 0.7546 - val_loss: 0.5454 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4893 - accuracy: 0.7636 - val_loss: 0.5510 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4784 - accuracy: 0.7711 - val_loss: 0.5634 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4677 - accuracy: 0.7789 - val_loss: 0.5571 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4541 - accuracy: 0.7865 - val_loss: 0.5580 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4414 - accuracy: 0.7951
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4421 - accuracy: 0.7950 - val_loss: 0.5679 - val_accuracy: 0.7102 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4008202681756456
Confusion Matrix :
 [[2647 1401]
 [1031 3016]]
Accuracy on test set:    0.6995676343421865
Sensitivity:    0.7452433901655547 	 Specificity:    0.6539031620553359
Precision  : 0.6828163912157573
Area Under Curve:    0.6995732761104453
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5901 - accuracy: 0.6808 - val_loss: 0.5563 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7234 - val_loss: 0.5467 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7343 - val_loss: 0.5490 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7427 - val_loss: 0.5466 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7507 - val_loss: 0.5477 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7587 - val_loss: 0.5463 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7674 - val_loss: 0.5500 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7776 - val_loss: 0.5518 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4538 - accuracy: 0.7844 - val_loss: 0.5584 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4420 - accuracy: 0.7936 - val_loss: 0.5647 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4287 - accuracy: 0.8021 - val_loss: 0.5673 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 12/400
254/257 [============================>.] - ETA: 0s - loss: 0.4158 - accuracy: 0.8091
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4159 - accuracy: 0.8090 - val_loss: 0.5777 - val_accuracy: 0.7094 - lr: 0.0010
253/253 [==============================] - 0s 848us/step
Independent Testing Matthews Correlation:  0.4088342055009838
Confusion Matrix :
 [[2600 1448]
 [ 957 3090]]
Accuracy on test set:    0.7029030265596047
Sensitivity:    0.7635285396590067 	 Specificity:    0.642292490118577
Precision  : 0.6809167033935655
Area Under Curve:    0.702910514888792
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5871 - accuracy: 0.6847 - val_loss: 0.5621 - val_accuracy: 0.7019 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7232 - val_loss: 0.5405 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7326 - val_loss: 0.5382 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7406 - val_loss: 0.5465 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7495 - val_loss: 0.5400 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4928 - accuracy: 0.7589 - val_loss: 0.5434 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4811 - accuracy: 0.7680 - val_loss: 0.5429 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7761 - val_loss: 0.5480 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4550 - accuracy: 0.7848 - val_loss: 0.5529 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4417 - accuracy: 0.7928 - val_loss: 0.5613 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4289 - accuracy: 0.8009 - val_loss: 0.5767 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4180 - accuracy: 0.8079 - val_loss: 0.5682 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4044 - accuracy: 0.8153 - val_loss: 0.5773 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3946 - accuracy: 0.8203 - val_loss: 0.5802 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 15/400
245/257 [===========================>..] - ETA: 0s - loss: 0.3812 - accuracy: 0.8287
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3812 - accuracy: 0.8284 - val_loss: 0.5903 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4127262565500533
Confusion Matrix :
 [[2865 1182]
 [1195 2853]]
Accuracy on test set:    0.7063619518221124
Sensitivity:    0.704792490118577 	 Specificity:    0.7079318013343218
Precision  : 0.7070631970260223
Area Under Curve:    0.7063621457264493
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5887 - accuracy: 0.6828 - val_loss: 0.5491 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7240 - val_loss: 0.5398 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7341 - val_loss: 0.5472 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7427 - val_loss: 0.5375 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7510 - val_loss: 0.5384 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7593 - val_loss: 0.5486 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4832 - accuracy: 0.7670
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7667 - val_loss: 0.5435 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41994687825219584
Confusion Matrix :
 [[2839 1208]
 [1140 2908]]
Accuracy on test set:    0.7099444101297097
Sensitivity:    0.7183794466403162 	 Specificity:    0.701507289350136
Precision  : 0.706511175898931
Area Under Curve:    0.7099433679952262
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5864 - accuracy: 0.6852 - val_loss: 0.5564 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7227 - val_loss: 0.5508 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7347 - val_loss: 0.5589 - val_accuracy: 0.7068 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7402 - val_loss: 0.5470 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7486 - val_loss: 0.5503 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7559 - val_loss: 0.5568 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7657 - val_loss: 0.5546 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7736 - val_loss: 0.5562 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4590 - accuracy: 0.7822
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4592 - accuracy: 0.7821 - val_loss: 0.5629 - val_accuracy: 0.7093 - lr: 0.0010
253/253 [==============================] - 0s 812us/step
Independent Testing Matthews Correlation:  0.4126305026745914
Confusion Matrix :
 [[2791 1256]
 [1122 2925]]
Accuracy on test set:    0.7062021250308871
Sensitivity:    0.7227575982209044 	 Specificity:    0.6896466518408698
Precision  : 0.699593398708443
Area Under Curve:    0.706202125030887
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5889 - accuracy: 0.6823 - val_loss: 0.5572 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7225 - val_loss: 0.5555 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7317 - val_loss: 0.5493 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7405 - val_loss: 0.5493 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7472 - val_loss: 0.5493 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.7563 - val_loss: 0.5472 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.7631 - val_loss: 0.5549 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.7717 - val_loss: 0.5549 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7787 - val_loss: 0.5570 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4541 - accuracy: 0.7870
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4541 - accuracy: 0.7869 - val_loss: 0.5610 - val_accuracy: 0.7131 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41689518486852917
Confusion Matrix :
 [[2942 1105]
 [1256 2791]]
Accuracy on test set:    0.7083024462564863
Sensitivity:    0.6896466518408698 	 Specificity:    0.7269582406721028
Precision  : 0.7163757700205339
Area Under Curve:    0.7083024462564863
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5859 - accuracy: 0.6850 - val_loss: 0.5538 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5432 - accuracy: 0.7225 - val_loss: 0.5479 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7357 - val_loss: 0.5474 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7428 - val_loss: 0.5492 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5043 - accuracy: 0.7499 - val_loss: 0.5550 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7601 - val_loss: 0.5573 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4819 - accuracy: 0.7667 - val_loss: 0.5593 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4682 - accuracy: 0.7751 - val_loss: 0.5648 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4565 - accuracy: 0.7836
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4565 - accuracy: 0.7832 - val_loss: 0.5666 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 936us/step
Independent Testing Matthews Correlation:  0.4279342273672595
Confusion Matrix :
 [[2982 1065]
 [1252 2795]]
Accuracy on test set:    0.7137385717815666
Sensitivity:    0.6906350382999753 	 Specificity:    0.7368421052631579
Precision  : 0.7240932642487047
Area Under Curve:    0.7137385717815666
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5883 - accuracy: 0.6819 - val_loss: 0.5524 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7233 - val_loss: 0.5465 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7339 - val_loss: 0.5455 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7417 - val_loss: 0.5425 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7484 - val_loss: 0.5441 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7557 - val_loss: 0.5453 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7633 - val_loss: 0.5485 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4762 - accuracy: 0.7716 - val_loss: 0.5525 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4658 - accuracy: 0.7786 - val_loss: 0.5499 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4533 - accuracy: 0.7874 - val_loss: 0.5621 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4402 - accuracy: 0.7943 - val_loss: 0.5703 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4255 - accuracy: 0.8029 - val_loss: 0.5657 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4154 - accuracy: 0.8094 - val_loss: 0.5733 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 14/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4022 - accuracy: 0.8162
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4032 - accuracy: 0.8157 - val_loss: 0.5818 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 857us/step
Independent Testing Matthews Correlation:  0.42578713376631483
Confusion Matrix :
 [[3006 1041]
 [1286 2761]]
Accuracy on test set:    0.7125030887076848
Sensitivity:    0.6822337533975784 	 Specificity:    0.742772424017791
Precision  : 0.7261967385586533
Area Under Curve:    0.7125030887076848
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5947 - accuracy: 0.6780 - val_loss: 0.5551 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7201 - val_loss: 0.5484 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5337 - accuracy: 0.7302 - val_loss: 0.5504 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7398 - val_loss: 0.5434 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7472 - val_loss: 0.5470 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7578 - val_loss: 0.5462 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7653 - val_loss: 0.5524 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.7746 - val_loss: 0.5831 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4574 - accuracy: 0.7842
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4577 - accuracy: 0.7840 - val_loss: 0.5564 - val_accuracy: 0.7219 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44308086632796134
Confusion Matrix :
 [[3097  950]
 [1311 2736]]
Accuracy on test set:    0.7206572769953051
Sensitivity:    0.676056338028169 	 Specificity:    0.7652582159624414
Precision  : 0.7422680412371134
Area Under Curve:    0.720657276995305
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5935 - accuracy: 0.6804 - val_loss: 0.5573 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5514 - accuracy: 0.7187 - val_loss: 0.5495 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5372 - accuracy: 0.7297 - val_loss: 0.5497 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5257 - accuracy: 0.7361 - val_loss: 0.5488 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7437 - val_loss: 0.5473 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7532 - val_loss: 0.5582 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7626 - val_loss: 0.5547 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4801 - accuracy: 0.7699 - val_loss: 0.5645 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4694 - accuracy: 0.7767
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4694 - accuracy: 0.7767 - val_loss: 0.5606 - val_accuracy: 0.7127 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.48706850921128475
Confusion Matrix :
 [[3189  858]
 [1226 2821]]
Accuracy on test set:    0.7425253274030146
Sensitivity:    0.6970595502841611 	 Specificity:    0.787991104521868
Precision  : 0.7667844522968198
Area Under Curve:    0.7425253274030146
(8094, 2560) (8094,)
Mean MCC = 0.4256 + 0.0233 and Mean AUC = 0.7123 + 0.0115
Mean Sensitivity = 0.7090 + 0.0269 and Mean Specificity = 0.7155 + 0.0437 and Mean Accuracy = 0.7123 + 0.0115
Mean Precision = 0.7153 + 0.0249





Seed   : 813274
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5814 - accuracy: 0.6877 - val_loss: 0.5579 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5385 - accuracy: 0.7270 - val_loss: 0.5521 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5224 - accuracy: 0.7387 - val_loss: 0.5497 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5093 - accuracy: 0.7479 - val_loss: 0.5487 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7542 - val_loss: 0.5554 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.7615 - val_loss: 0.5702 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7701 - val_loss: 0.5553 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4656 - accuracy: 0.7784 - val_loss: 0.5557 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 9/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4533 - accuracy: 0.7869
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4538 - accuracy: 0.7863 - val_loss: 0.5698 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39526088059157083
Confusion Matrix :
 [[2657 1391]
 [1062 2985]]
Accuracy on test set:    0.6969734403953057
Sensitivity:    0.737583395107487 	 Specificity:    0.6563735177865613
Precision  : 0.6821297989031079
Area Under Curve:    0.6969784564470242
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5888 - accuracy: 0.6822 - val_loss: 0.5591 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7229 - val_loss: 0.5512 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7349 - val_loss: 0.5489 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7404 - val_loss: 0.5486 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7495 - val_loss: 0.5520 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.7558 - val_loss: 0.5493 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7624 - val_loss: 0.5551 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.7718 - val_loss: 0.5619 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.7771 - val_loss: 0.5632 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4561 - accuracy: 0.7847 - val_loss: 0.5557 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 11/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4444 - accuracy: 0.7930
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4447 - accuracy: 0.7927 - val_loss: 0.5650 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.420011438186208
Confusion Matrix :
 [[2681 1367]
 [ 988 3059]]
Accuracy on test set:    0.7090796788140827
Sensitivity:    0.755868544600939 	 Specificity:    0.662302371541502
Precision  : 0.6911432444645278
Area Under Curve:    0.7090854580712205
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5887 - accuracy: 0.6840 - val_loss: 0.5504 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7225 - val_loss: 0.5439 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7334 - val_loss: 0.5390 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7417 - val_loss: 0.5402 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7510 - val_loss: 0.5390 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7587 - val_loss: 0.5390 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.7673 - val_loss: 0.5410 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.7747 - val_loss: 0.5476 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4571 - accuracy: 0.7832 - val_loss: 0.5456 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4445 - accuracy: 0.7882 - val_loss: 0.5550 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4317 - accuracy: 0.7977 - val_loss: 0.5721 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4193 - accuracy: 0.8055 - val_loss: 0.5660 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4075 - accuracy: 0.8121 - val_loss: 0.5654 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 14/400
256/257 [============================>.] - ETA: 0s - loss: 0.3947 - accuracy: 0.8202
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3947 - accuracy: 0.8202 - val_loss: 0.5716 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4018809404291334
Confusion Matrix :
 [[2860 1187]
 [1234 2814]]
Accuracy on test set:    0.7009264978381717
Sensitivity:    0.6951581027667985 	 Specificity:    0.7066963182604399
Precision  : 0.7033241689577605
Area Under Curve:    0.7009272105136191
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5862 - accuracy: 0.6850 - val_loss: 0.5491 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7239 - val_loss: 0.5424 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7346 - val_loss: 0.5416 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7412 - val_loss: 0.5375 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7489 - val_loss: 0.5436 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7558 - val_loss: 0.5392 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7645 - val_loss: 0.5418 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4759 - accuracy: 0.7729 - val_loss: 0.5396 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4647 - accuracy: 0.7807
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4648 - accuracy: 0.7804 - val_loss: 0.5501 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 901us/step
Independent Testing Matthews Correlation:  0.41889661005171647
Confusion Matrix :
 [[2730 1317]
 [1039 3009]]
Accuracy on test set:    0.7089561457689932
Sensitivity:    0.7433300395256917 	 Specificity:    0.6745737583395107
Precision  : 0.6955617198335645
Area Under Curve:    0.7089518989326014
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5842 - accuracy: 0.6875 - val_loss: 0.5581 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7236 - val_loss: 0.5493 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5263 - accuracy: 0.7349 - val_loss: 0.5439 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5148 - accuracy: 0.7419 - val_loss: 0.5465 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7519 - val_loss: 0.5431 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4899 - accuracy: 0.7595 - val_loss: 0.5450 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4777 - accuracy: 0.7682 - val_loss: 0.5495 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.7790 - val_loss: 0.5555 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4523 - accuracy: 0.7857 - val_loss: 0.5627 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4372 - accuracy: 0.7958
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4374 - accuracy: 0.7956 - val_loss: 0.5604 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41957016716943907
Confusion Matrix :
 [[2874 1173]
 [1176 2871]]
Accuracy on test set:    0.7097850259451446
Sensitivity:    0.7094143810229799 	 Specificity:    0.7101556708673091
Precision  : 0.7099406528189911
Area Under Curve:    0.7097850259451446
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5889 - accuracy: 0.6847 - val_loss: 0.5563 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7224 - val_loss: 0.5500 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7325 - val_loss: 0.5461 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7417 - val_loss: 0.5453 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.7477 - val_loss: 0.5464 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7555 - val_loss: 0.5522 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7663 - val_loss: 0.5528 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 8/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4714 - accuracy: 0.7735
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4723 - accuracy: 0.7725 - val_loss: 0.5531 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42797145438013456
Confusion Matrix :
 [[2888 1159]
 [1156 2891]]
Accuracy on test set:    0.7139856683963429
Sensitivity:    0.7143563133185076 	 Specificity:    0.7136150234741784
Precision  : 0.7138271604938271
Area Under Curve:    0.7139856683963429
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5872 - accuracy: 0.6864 - val_loss: 0.5551 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7236 - val_loss: 0.5461 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7332 - val_loss: 0.5564 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7410 - val_loss: 0.5477 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7491 - val_loss: 0.5554 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7570 - val_loss: 0.5455 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7676 - val_loss: 0.5526 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4711 - accuracy: 0.7728 - val_loss: 0.5535 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4575 - accuracy: 0.7832 - val_loss: 0.5553 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4456 - accuracy: 0.7899 - val_loss: 0.5647 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4317 - accuracy: 0.7986 - val_loss: 0.5646 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 12/400
253/257 [============================>.] - ETA: 0s - loss: 0.4210 - accuracy: 0.8060
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4210 - accuracy: 0.8057 - val_loss: 0.5661 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43095082353779385
Confusion Matrix :
 [[2879 1168]
 [1135 2912]]
Accuracy on test set:    0.7154682480850012
Sensitivity:    0.7195453422288115 	 Specificity:    0.711391153941191
Precision  : 0.7137254901960784
Area Under Curve:    0.7154682480850012
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5898 - accuracy: 0.6819 - val_loss: 0.5541 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7224 - val_loss: 0.5458 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7338 - val_loss: 0.5431 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7437 - val_loss: 0.5415 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7491 - val_loss: 0.5410 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7586 - val_loss: 0.5422 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7678 - val_loss: 0.5473 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4708 - accuracy: 0.7746 - val_loss: 0.5487 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.7838 - val_loss: 0.5542 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4448 - accuracy: 0.7927 - val_loss: 0.5548 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 11/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4314 - accuracy: 0.7996
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4316 - accuracy: 0.7995 - val_loss: 0.5677 - val_accuracy: 0.7141 - lr: 0.0010
253/253 [==============================] - 0s 846us/step
Independent Testing Matthews Correlation:  0.43886672938755356
Confusion Matrix :
 [[2840 1207]
 [1065 2982]]
Accuracy on test set:    0.7192982456140351
Sensitivity:    0.7368421052631579 	 Specificity:    0.7017543859649122
Precision  : 0.711864406779661
Area Under Curve:    0.719298245614035
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5918 - accuracy: 0.6831 - val_loss: 0.5597 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5493 - accuracy: 0.7206 - val_loss: 0.5527 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5344 - accuracy: 0.7302 - val_loss: 0.5534 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5235 - accuracy: 0.7374 - val_loss: 0.5494 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7450 - val_loss: 0.5485 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7503 - val_loss: 0.5509 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7592 - val_loss: 0.5617 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7681 - val_loss: 0.5645 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7773 - val_loss: 0.5638 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4571 - accuracy: 0.7842
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4573 - accuracy: 0.7838 - val_loss: 0.5638 - val_accuracy: 0.7148 - lr: 0.0010
253/253 [==============================] - 0s 820us/step
Independent Testing Matthews Correlation:  0.4528768247970677
Confusion Matrix :
 [[2999 1048]
 [1167 2880]]
Accuracy on test set:    0.7263404991351619
Sensitivity:    0.7116382505559674 	 Specificity:    0.7410427477143563
Precision  : 0.7331975560081466
Area Under Curve:    0.7263404991351617
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5910 - accuracy: 0.6818 - val_loss: 0.5568 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7194 - val_loss: 0.5533 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7323 - val_loss: 0.5490 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5237 - accuracy: 0.7380 - val_loss: 0.5495 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5126 - accuracy: 0.7457 - val_loss: 0.5582 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5015 - accuracy: 0.7534 - val_loss: 0.5531 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7638 - val_loss: 0.5566 - val_accuracy: 0.7164 - lr: 0.0010

Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4784 - accuracy: 0.7725 - val_loss: 0.5555 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.7795 - val_loss: 0.5588 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4533 - accuracy: 0.7893 - val_loss: 0.5613 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4426 - accuracy: 0.7958
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4425 - accuracy: 0.7956 - val_loss: 0.5700 - val_accuracy: 0.7170 - lr: 0.0010
253/253 [==============================] - 0s 762us/step
Independent Testing Matthews Correlation:  0.4701781030659453
Confusion Matrix :
 [[3101  946]
 [1202 2845]]
Accuracy on test set:    0.7346182357301705
Sensitivity:    0.7029898690387941 	 Specificity:    0.7662466024215469
Precision  : 0.7504616196254287
Area Under Curve:    0.7346182357301705
(8094, 2560) (8094,)
Mean MCC = 0.4276 + 0.0212 and Mean AUC = 0.7135 + 0.0106
Mean Sensitivity = 0.7227 + 0.0186 and Mean Specificity = 0.7044 + 0.0321 and Mean Accuracy = 0.7135 + 0.0106
Mean Precision = 0.7105 + 0.0189





Seed   : 338629
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5828 - accuracy: 0.6879 - val_loss: 0.5574 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5403 - accuracy: 0.7261 - val_loss: 0.5548 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5247 - accuracy: 0.7376 - val_loss: 0.5474 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5138 - accuracy: 0.7451 - val_loss: 0.5481 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7511 - val_loss: 0.5522 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7598 - val_loss: 0.5508 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7673 - val_loss: 0.5575 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7747 - val_loss: 0.5623 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4573 - accuracy: 0.7834 - val_loss: 0.5638 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4450 - accuracy: 0.7919 - val_loss: 0.5639 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4335 - accuracy: 0.7991 - val_loss: 0.5695 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4215 - accuracy: 0.8064 - val_loss: 0.5742 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4086 - accuracy: 0.8140 - val_loss: 0.5893 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3979 - accuracy: 0.8202 - val_loss: 0.5860 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 15/400
253/257 [============================>.] - ETA: 0s - loss: 0.3867 - accuracy: 0.8261
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3867 - accuracy: 0.8261 - val_loss: 0.6046 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 837us/step
Independent Testing Matthews Correlation:  0.3940768486526552
Confusion Matrix :
 [[2636 1412]
 [1047 3000]]
Accuracy on test set:    0.6962322421247684
Sensitivity:    0.7412898443291327 	 Specificity:    0.6511857707509882
Precision  : 0.6799637352674524
Area Under Curve:    0.6962378075400605
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5895 - accuracy: 0.6838 - val_loss: 0.5609 - val_accuracy: 0.7039 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7263 - val_loss: 0.5527 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7335 - val_loss: 0.5498 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7420 - val_loss: 0.5500 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7489 - val_loss: 0.5515 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7565 - val_loss: 0.5513 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7632 - val_loss: 0.5543 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4765 - accuracy: 0.7711 - val_loss: 0.5617 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4646 - accuracy: 0.7780 - val_loss: 0.5599 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4541 - accuracy: 0.7872 - val_loss: 0.5662 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4414 - accuracy: 0.7929 - val_loss: 0.5737 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4302 - accuracy: 0.7979 - val_loss: 0.5737 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 13/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4190 - accuracy: 0.8070
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4195 - accuracy: 0.8065 - val_loss: 0.5779 - val_accuracy: 0.7124 - lr: 0.0010
253/253 [==============================] - 0s 774us/step
Independent Testing Matthews Correlation:  0.40453320455558
Confusion Matrix :
 [[2908 1140]
 [1271 2776]]
Accuracy on test set:    0.7021618282890674
Sensitivity:    0.6859402026192242 	 Specificity:    0.7183794466403162
Precision  : 0.7088866189989785
Area Under Curve:    0.7021598246297701
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 4ms/step - loss: 0.5857 - accuracy: 0.6852 - val_loss: 0.5552 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7232 - val_loss: 0.5431 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7349 - val_loss: 0.5402 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7416 - val_loss: 0.5404 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7507 - val_loss: 0.5409 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7577 - val_loss: 0.5435 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7668 - val_loss: 0.5442 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7754 - val_loss: 0.5435 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4583 - accuracy: 0.7823 - val_loss: 0.5464 - val_accuracy: 0.7219 - lr: 0.0010

Epoch 10/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4440 - accuracy: 0.7913
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4451 - accuracy: 0.7906 - val_loss: 0.5493 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 797us/step
Independent Testing Matthews Correlation:  0.4052022030569857
Confusion Matrix :
 [[2754 1293]
 [1116 2932]]
Accuracy on test set:    0.7024088943792465
Sensitivity:    0.724308300395257 	 Specificity:    0.6805040770941438
Precision  : 0.6939644970414202
Area Under Curve:    0.7024061887447003
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5901 - accuracy: 0.6820 - val_loss: 0.5549 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7220 - val_loss: 0.5427 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7320 - val_loss: 0.5424 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7390 - val_loss: 0.5427 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7451 - val_loss: 0.5428 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7539 - val_loss: 0.5405 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7598 - val_loss: 0.5540 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7654 - val_loss: 0.5425 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7735 - val_loss: 0.5501 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4630 - accuracy: 0.7813 - val_loss: 0.5561 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4531 - accuracy: 0.7895 - val_loss: 0.5581 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4414 - accuracy: 0.7945 - val_loss: 0.5576 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 13/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4262 - accuracy: 0.8039
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4267 - accuracy: 0.8034 - val_loss: 0.5667 - val_accuracy: 0.7132 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43764770622875415
Confusion Matrix :
 [[2727 1320]
 [ 963 3085]]
Accuracy on test set:    0.7179740580605312
Sensitivity:    0.7621047430830039 	 Specificity:    0.6738324684951816
Precision  : 0.7003405221339387
Area Under Curve:    0.7179686057890927
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5904 - accuracy: 0.6838 - val_loss: 0.5569 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7222 - val_loss: 0.5472 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7305 - val_loss: 0.5470 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7399 - val_loss: 0.5443 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7472 - val_loss: 0.5506 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.7551 - val_loss: 0.5505 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4846 - accuracy: 0.7658
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7656 - val_loss: 0.5488 - val_accuracy: 0.7229 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42887945648188985
Confusion Matrix :
 [[2725 1322]
 [ 995 3052]]
Accuracy on test set:    0.7137385717815666
Sensitivity:    0.7541388682975043 	 Specificity:    0.6733382752656288
Precision  : 0.6977594878829446
Area Under Curve:    0.7137385717815665
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5870 - accuracy: 0.6834 - val_loss: 0.5538 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7240 - val_loss: 0.5431 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7350 - val_loss: 0.5419 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5154 - accuracy: 0.7443 - val_loss: 0.5423 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7521 - val_loss: 0.5458 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4924 - accuracy: 0.7607 - val_loss: 0.5453 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.7699 - val_loss: 0.5493 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4648 - accuracy: 0.7795 - val_loss: 0.5488 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 9/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4512 - accuracy: 0.7876
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4516 - accuracy: 0.7873 - val_loss: 0.5517 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 782us/step
Independent Testing Matthews Correlation:  0.40893644343520774
Confusion Matrix :
 [[2989 1058]
 [1338 2709]]
Accuracy on test set:    0.7039782554978997
Sensitivity:    0.6693847294292068 	 Specificity:    0.7385717815665925
Precision  : 0.7191398991239714
Area Under Curve:    0.7039782554978997
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5900 - accuracy: 0.6830 - val_loss: 0.5533 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7236 - val_loss: 0.5449 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7348 - val_loss: 0.5410 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7422 - val_loss: 0.5396 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7485 - val_loss: 0.5402 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7563 - val_loss: 0.5443 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4872 - accuracy: 0.7651 - val_loss: 0.5447 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7715 - val_loss: 0.5514 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.7787 - val_loss: 0.5523 - val_accuracy: 0.7200 - lr: 0.0010

Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4516 - accuracy: 0.7877 - val_loss: 0.5580 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 11/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4414 - accuracy: 0.7949
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4412 - accuracy: 0.7948 - val_loss: 0.5614 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43343425802857943
Confusion Matrix :
 [[2878 1169]
 [1124 2923]]
Accuracy on test set:    0.7167037311588831
Sensitivity:    0.7222634049913517 	 Specificity:    0.7111440573264146
Precision  : 0.7143206256109482
Area Under Curve:    0.7167037311588832
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5924 - accuracy: 0.6786 - val_loss: 0.5498 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7222 - val_loss: 0.5467 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7336 - val_loss: 0.5369 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7403 - val_loss: 0.5352 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7496 - val_loss: 0.5419 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7567 - val_loss: 0.5386 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7666 - val_loss: 0.5382 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4738 - accuracy: 0.7738 - val_loss: 0.5404 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4618 - accuracy: 0.7818 - val_loss: 0.5466 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4478 - accuracy: 0.7901 - val_loss: 0.5507 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4354 - accuracy: 0.7978 - val_loss: 0.5561 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 12/400
252/257 [============================>.] - ETA: 0s - loss: 0.4218 - accuracy: 0.8069
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4223 - accuracy: 0.8065 - val_loss: 0.5778 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 947us/step
Independent Testing Matthews Correlation:  0.43749072381264065
Confusion Matrix :
 [[2616 1431]
 [ 863 3184]]
Accuracy on test set:    0.7165801828514949
Sensitivity:    0.7867556214479862 	 Specificity:    0.6464047442550037
Precision  : 0.6899241603466956
Area Under Curve:    0.716580182851495
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 4ms/step - loss: 0.5910 - accuracy: 0.6818 - val_loss: 0.5572 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5484 - accuracy: 0.7202 - val_loss: 0.5533 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5334 - accuracy: 0.7308 - val_loss: 0.5459 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7397 - val_loss: 0.5453 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7472 - val_loss: 0.5446 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4986 - accuracy: 0.7550 - val_loss: 0.5480 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7655 - val_loss: 0.5522 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4725 - accuracy: 0.7732 - val_loss: 0.5548 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4587 - accuracy: 0.7829 - val_loss: 0.5577 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4441 - accuracy: 0.7922
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4444 - accuracy: 0.7922 - val_loss: 0.5663 - val_accuracy: 0.7109 - lr: 0.0010
253/253 [==============================] - 0s 962us/step
Independent Testing Matthews Correlation:  0.4495692574215046
Confusion Matrix :
 [[3134  913]
 [1324 2723]]
Accuracy on test set:    0.7236224363726217
Sensitivity:    0.6728440820360762 	 Specificity:    0.7744007907091672
Precision  : 0.7488998899889989
Area Under Curve:    0.7236224363726216
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5939 - accuracy: 0.6805 - val_loss: 0.5585 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5500 - accuracy: 0.7211 - val_loss: 0.5520 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5346 - accuracy: 0.7303 - val_loss: 0.5484 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5241 - accuracy: 0.7384 - val_loss: 0.5496 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5120 - accuracy: 0.7465 - val_loss: 0.5496 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.7549 - val_loss: 0.5509 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4886 - accuracy: 0.7635 - val_loss: 0.5590 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4780 - accuracy: 0.7711
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4781 - accuracy: 0.7708 - val_loss: 0.5655 - val_accuracy: 0.7127 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4880216367506828
Confusion Matrix :
 [[2837 1210]
 [ 869 3178]]
Accuracy on test set:    0.7431430689399555
Sensitivity:    0.7852730417593279 	 Specificity:    0.7010130961205832
Precision  : 0.7242479489516864
Area Under Curve:    0.7431430689399554
(8094, 2560) (8094,)
Mean MCC = 0.4288 + 0.0262 and Mean AUC = 0.7137 + 0.0129
Mean Sensitivity = 0.7304 + 0.0412 and Mean Specificity = 0.6969 + 0.0380 and Mean Accuracy = 0.7137 + 0.0129
Mean Precision = 0.7077 + 0.0189





Seed   : 386444
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5850 - accuracy: 0.6858 - val_loss: 0.5546 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5423 - accuracy: 0.7266 - val_loss: 0.5455 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7358 - val_loss: 0.5459 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7434 - val_loss: 0.5455 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7513 - val_loss: 0.5508 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7584 - val_loss: 0.5469 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7671 - val_loss: 0.5527 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7748 - val_loss: 0.5611 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.7832 - val_loss: 0.5523 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4464 - accuracy: 0.7917 - val_loss: 0.5576 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4346 - accuracy: 0.7984 - val_loss: 0.5636 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 12/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4220 - accuracy: 0.8068
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4229 - accuracy: 0.8062 - val_loss: 0.5725 - val_accuracy: 0.7116 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3932848740405037
Confusion Matrix :
 [[2861 1187]
 [1269 2778]]
Accuracy on test set:    0.696602841260037
Sensitivity:    0.6864343958487769 	 Specificity:    0.7067687747035574
Precision  : 0.7006305170239596
Area Under Curve:    0.6966015852761671
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5850 - accuracy: 0.6873 - val_loss: 0.5577 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7233 - val_loss: 0.5480 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7360 - val_loss: 0.5478 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5140 - accuracy: 0.7449 - val_loss: 0.5436 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7507 - val_loss: 0.5420 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7608 - val_loss: 0.5504 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4805 - accuracy: 0.7676 - val_loss: 0.5478 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7759 - val_loss: 0.5469 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4565 - accuracy: 0.7853
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4565 - accuracy: 0.7852 - val_loss: 0.5501 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4107492507921764
Confusion Matrix :
 [[2862 1186]
 [1199 2848]]
Accuracy on test set:    0.705373687461396
Sensitivity:    0.7037311588831233 	 Specificity:    0.7070158102766798
Precision  : 0.7059990084283589
Area Under Curve:    0.7053734845799017
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5840 - accuracy: 0.6875 - val_loss: 0.5447 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7225 - val_loss: 0.5395 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7338 - val_loss: 0.5354 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5154 - accuracy: 0.7426 - val_loss: 0.5402 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7522 - val_loss: 0.5386 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7608 - val_loss: 0.5402 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4788 - accuracy: 0.7686 - val_loss: 0.5414 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7783 - val_loss: 0.5494 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4531 - accuracy: 0.7877 - val_loss: 0.5515 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4390 - accuracy: 0.7949 - val_loss: 0.5544 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4258 - accuracy: 0.8028 - val_loss: 0.5615 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 12/400
255/257 [============================>.] - ETA: 0s - loss: 0.4115 - accuracy: 0.8114
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4118 - accuracy: 0.8113 - val_loss: 0.5700 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 792us/step
Independent Testing Matthews Correlation:  0.4262519737753862
Confusion Matrix :
 [[2690 1357]
 [ 973 3075]]
Accuracy on test set:    0.7121680049413218
Sensitivity:    0.7596343873517787 	 Specificity:    0.6646898937484557
Precision  : 0.6938176895306859
Area Under Curve:    0.7121621405501172
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5840 - accuracy: 0.6860 - val_loss: 0.5456 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7232 - val_loss: 0.5390 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7340 - val_loss: 0.5354 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5149 - accuracy: 0.7430 - val_loss: 0.5330 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.7515 - val_loss: 0.5357 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4918 - accuracy: 0.7615 - val_loss: 0.5425 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4793 - accuracy: 0.7692 - val_loss: 0.5409 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4663 - accuracy: 0.7777 - val_loss: 0.5475 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4529 - accuracy: 0.7879 - val_loss: 0.5482 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4387 - accuracy: 0.7967
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4384 - accuracy: 0.7969 - val_loss: 0.5559 - val_accuracy: 0.7229 - lr: 0.0010
253/253 [==============================] - 0s 791us/step
Independent Testing Matthews Correlation:  0.430639772020228
Confusion Matrix :
 [[2845 1202]
 [1103 2945]]
Accuracy on test set:    0.7152563310685608
Sensitivity:    0.7275197628458498 	 Specificity:    0.7029898690387941
Precision  : 0.7101519170484688
Area Under Curve:    0.715254815942322
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 8ms/step - loss: 0.5874 - accuracy: 0.6838 - val_loss: 0.5547 - val_accuracy: 0.7164 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7226 - val_loss: 0.5465 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7316 - val_loss: 0.5465 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7369 - val_loss: 0.5478 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7465 - val_loss: 0.5495 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.7546 - val_loss: 0.5477 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4893 - accuracy: 0.7617
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7614 - val_loss: 0.5503 - val_accuracy: 0.7207 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42784240914678334
Confusion Matrix :
 [[2685 1362]
 [ 962 3085]]
Accuracy on test set:    0.7128737336298493
Sensitivity:    0.7622930565851248 	 Specificity:    0.6634544106745738
Precision  : 0.6937261074881943
Area Under Curve:    0.7128737336298492
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5918 - accuracy: 0.6796 - val_loss: 0.5542 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7218 - val_loss: 0.5466 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7325 - val_loss: 0.5421 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7402 - val_loss: 0.5411 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7479 - val_loss: 0.5485 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.7556 - val_loss: 0.5491 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4876 - accuracy: 0.7626 - val_loss: 0.5465 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4754 - accuracy: 0.7694 - val_loss: 0.5504 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4651 - accuracy: 0.7776 - val_loss: 0.5571 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4520 - accuracy: 0.7867 - val_loss: 0.5554 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4414 - accuracy: 0.7944 - val_loss: 0.5625 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4261 - accuracy: 0.8027 - val_loss: 0.5681 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4156 - accuracy: 0.8083 - val_loss: 0.5813 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4052 - accuracy: 0.8145 - val_loss: 0.5814 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 15/400
245/257 [===========================>..] - ETA: 0s - loss: 0.3925 - accuracy: 0.8213
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3929 - accuracy: 0.8211 - val_loss: 0.5883 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 754us/step
Independent Testing Matthews Correlation:  0.42377090133408596
Confusion Matrix :
 [[2883 1164]
 [1168 2879]]
Accuracy on test set:    0.7118853471707438
Sensitivity:    0.711391153941191 	 Specificity:    0.7123795404002965
Precision  : 0.7120949789760079
Area Under Curve:    0.7118853471707438
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5843 - accuracy: 0.6868 - val_loss: 0.5489 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5422 - accuracy: 0.7238 - val_loss: 0.5450 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7344 - val_loss: 0.5459 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7420 - val_loss: 0.5397 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7500 - val_loss: 0.5410 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7579 - val_loss: 0.5425 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7678 - val_loss: 0.5439 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4706 - accuracy: 0.7747 - val_loss: 0.5483 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4567 - accuracy: 0.7829 - val_loss: 0.5514 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4438 - accuracy: 0.7928 - val_loss: 0.5530 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4322 - accuracy: 0.7992 - val_loss: 0.5659 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 12/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4199 - accuracy: 0.8054
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4202 - accuracy: 0.8052 - val_loss: 0.5656 - val_accuracy: 0.7224 - lr: 0.0010
253/253 [==============================] - 0s 743us/step
Independent Testing Matthews Correlation:  0.41999966437378694
Confusion Matrix :
 [[2964 1083]
 [1266 2781]]
Accuracy on test set:    0.7097850259451446
Sensitivity:    0.687175685693106 	 Specificity:    0.7323943661971831
Precision  : 0.71972049689441
Area Under Curve:    0.7097850259451446
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5924 - accuracy: 0.6800 - val_loss: 0.5518 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7237 - val_loss: 0.5443 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7341 - val_loss: 0.5460 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7410 - val_loss: 0.5368 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7487 - val_loss: 0.5348 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7558 - val_loss: 0.5408 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7676 - val_loss: 0.5401 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4703 - accuracy: 0.7729 - val_loss: 0.5501 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4578 - accuracy: 0.7829 - val_loss: 0.5493 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4442 - accuracy: 0.7921
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4442 - accuracy: 0.7922 - val_loss: 0.5628 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41936845255275645
Confusion Matrix :
 [[2728 1319]
 [1035 3012]]
Accuracy on test set:    0.7091672844082036
Sensitivity:    0.7442550037064493 	 Specificity:    0.674079565109958
Precision  : 0.6954513969060263
Area Under Curve:    0.7091672844082036
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5926 - accuracy: 0.6827 - val_loss: 0.5479 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5488 - accuracy: 0.7208 - val_loss: 0.5397 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5330 - accuracy: 0.7304 - val_loss: 0.5387 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5239 - accuracy: 0.7380 - val_loss: 0.5393 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5122 - accuracy: 0.7458 - val_loss: 0.5402 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5021 - accuracy: 0.7528 - val_loss: 0.5408 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7624 - val_loss: 0.5444 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4801 - accuracy: 0.7668
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4806 - accuracy: 0.7665 - val_loss: 0.5402 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.45229332576020476
Confusion Matrix :
 [[3018 1029]
 [1189 2858]]
Accuracy on test set:    0.7259698542129973
Sensitivity:    0.7062021250308871 	 Specificity:    0.7457375833951075
Precision  : 0.735271417545665
Area Under Curve:    0.7259698542129973
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5915 - accuracy: 0.6790 - val_loss: 0.5558 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5492 - accuracy: 0.7202 - val_loss: 0.5454 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5347 - accuracy: 0.7301 - val_loss: 0.5436 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5237 - accuracy: 0.7376 - val_loss: 0.5440 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.7441 - val_loss: 0.5454 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5023 - accuracy: 0.7534 - val_loss: 0.5475 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7607 - val_loss: 0.5485 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4815 - accuracy: 0.7690
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7690 - val_loss: 0.5485 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47633681598149386
Confusion Matrix :
 [[3153  894]
 [1232 2815]]
Accuracy on test set:    0.7373362984927107
Sensitivity:    0.6955769705955028 	 Specificity:    0.7790956263899185
Precision  : 0.7589646805068752
Area Under Curve:    0.7373362984927107
(8094, 2560) (8094,)
Mean MCC = 0.4281 + 0.0214 and Mean AUC = 0.7136 + 0.0106
Mean Sensitivity = 0.7184 + 0.0270 and Mean Specificity = 0.7089 + 0.0348 and Mean Accuracy = 0.7136 + 0.0106
Mean Precision = 0.7126 + 0.0198





Seed   : 295836
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5830 - accuracy: 0.6882 - val_loss: 0.5537 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5405 - accuracy: 0.7255 - val_loss: 0.5505 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5249 - accuracy: 0.7370 - val_loss: 0.5478 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7450 - val_loss: 0.5513 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.7532 - val_loss: 0.5468 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4902 - accuracy: 0.7606 - val_loss: 0.5505 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4766 - accuracy: 0.7726 - val_loss: 0.5518 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4629 - accuracy: 0.7791 - val_loss: 0.5541 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4515 - accuracy: 0.7868
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4519 - accuracy: 0.7869 - val_loss: 0.5748 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39550124977504714
Confusion Matrix :
 [[2425 1623]
 [ 853 3194]]
Accuracy on test set:    0.6941321803582459
Sensitivity:    0.7892265875957499 	 Specificity:    0.5990612648221344
Precision  : 0.6630682997716421
Area Under Curve:    0.6941439262089422
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5852 - accuracy: 0.6837 - val_loss: 0.5564 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5418 - accuracy: 0.7233 - val_loss: 0.5547 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5255 - accuracy: 0.7365 - val_loss: 0.5444 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5126 - accuracy: 0.7455 - val_loss: 0.5504 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5027 - accuracy: 0.7513 - val_loss: 0.5448 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7612 - val_loss: 0.5516 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7672 - val_loss: 0.5603 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4684 - accuracy: 0.7764 - val_loss: 0.5579 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4562 - accuracy: 0.7847 - val_loss: 0.5601 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4440 - accuracy: 0.7923
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4438 - accuracy: 0.7924 - val_loss: 0.5729 - val_accuracy: 0.7095 - lr: 0.0010
253/253 [==============================] - 0s 723us/step

Independent Testing Matthews Correlation:  0.4296123457468537
Confusion Matrix :
 [[2647 1401]
 [ 920 3127]]
Accuracy on test set:    0.7132798023471278
Sensitivity:    0.7726711144057327 	 Specificity:    0.6539031620553359
Precision  : 0.6905918727915195
Area Under Curve:    0.7132871382305344
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5855 - accuracy: 0.6851 - val_loss: 0.5458 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7241 - val_loss: 0.5396 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7346 - val_loss: 0.5394 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7416 - val_loss: 0.5337 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7510 - val_loss: 0.5340 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7578 - val_loss: 0.5360 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.7667 - val_loss: 0.5384 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7755 - val_loss: 0.5434 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4595 - accuracy: 0.7822 - val_loss: 0.5421 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4452 - accuracy: 0.7912
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4450 - accuracy: 0.7914 - val_loss: 0.5516 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 762us/step
Independent Testing Matthews Correlation:  0.4239336211850077
Confusion Matrix :
 [[2677 1370]
 [ 970 3078]]
Accuracy on test set:    0.7109326744904262
Sensitivity:    0.7603754940711462 	 Specificity:    0.6614776377563627
Precision  : 0.6919964028776978
Area Under Curve:    0.7109265659137545
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5885 - accuracy: 0.6831 - val_loss: 0.5515 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7233 - val_loss: 0.5430 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7328 - val_loss: 0.5385 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.7401 - val_loss: 0.5405 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5103 - accuracy: 0.7465 - val_loss: 0.5405 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7542 - val_loss: 0.5385 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7615 - val_loss: 0.5434 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4789 - accuracy: 0.7701
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4791 - accuracy: 0.7702 - val_loss: 0.5466 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 756us/step
Independent Testing Matthews Correlation:  0.4367291358416675
Confusion Matrix :
 [[2685 1362]
 [ 928 3120]]
Accuracy on test set:    0.7171093267449042
Sensitivity:    0.7707509881422925 	 Specificity:    0.6634544106745738
Precision  : 0.6961178045515395
Area Under Curve:    0.7171026994084331
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5957 - accuracy: 0.6769 - val_loss: 0.5489 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7202 - val_loss: 0.5402 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7309 - val_loss: 0.5393 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7394 - val_loss: 0.5383 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5113 - accuracy: 0.7472 - val_loss: 0.5450 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4995 - accuracy: 0.7538 - val_loss: 0.5402 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4899 - accuracy: 0.7614
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7615 - val_loss: 0.5420 - val_accuracy: 0.7245 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42675271872982884
Confusion Matrix :
 [[2787 1260]
 [1062 2985]]
Accuracy on test set:    0.7131208302446257
Sensitivity:    0.737583395107487 	 Specificity:    0.6886582653817642
Precision  : 0.7031802120141343
Area Under Curve:    0.7131208302446257
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5878 - accuracy: 0.6820 - val_loss: 0.5494 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7224 - val_loss: 0.5439 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.7352 - val_loss: 0.5428 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7428 - val_loss: 0.5436 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7488 - val_loss: 0.5447 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
252/257 [============================>.] - ETA: 0s - loss: 0.4945 - accuracy: 0.7590
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7587 - val_loss: 0.5477 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 730us/step
Independent Testing Matthews Correlation:  0.42812048385146506
Confusion Matrix :
 [[2710 1337]
 [ 984 3063]]
Accuracy on test set:    0.7132443785520138
Sensitivity:    0.7568569310600445 	 Specificity:    0.6696318260439832
Precision  : 0.6961363636363637
Area Under Curve:    0.713244378552014
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5886 - accuracy: 0.6823 - val_loss: 0.5470 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7220 - val_loss: 0.5401 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7324 - val_loss: 0.5373 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7416 - val_loss: 0.5371 - val_accuracy: 0.7311 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7483 - val_loss: 0.5464 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7582 - val_loss: 0.5411 - val_accuracy: 0.7227 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7644 - val_loss: 0.5441 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4682 - accuracy: 0.7766 - val_loss: 0.5601 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4559 - accuracy: 0.7856
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4560 - accuracy: 0.7854 - val_loss: 0.5550 - val_accuracy: 0.7205 - lr: 0.0010
253/253 [==============================] - 0s 834us/step
Independent Testing Matthews Correlation:  0.4305372759300594
Confusion Matrix :
 [[2937 1110]
 [1195 2852]]
Accuracy on test set:    0.7152211514702248
Sensitivity:    0.7047195453422288 	 Specificity:    0.7257227575982209
Precision  : 0.7198384654215043
Area Under Curve:    0.7152211514702249
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5946 - accuracy: 0.6777 - val_loss: 0.5528 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5514 - accuracy: 0.7200 - val_loss: 0.5403 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5363 - accuracy: 0.7289 - val_loss: 0.5426 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5249 - accuracy: 0.7384 - val_loss: 0.5429 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.7461 - val_loss: 0.5430 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7537 - val_loss: 0.5391 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4940 - accuracy: 0.7593
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7591 - val_loss: 0.5391 - val_accuracy: 0.7222 - lr: 0.0010
253/253 [==============================] - 0s 703us/step
Independent Testing Matthews Correlation:  0.4453029854248198
Confusion Matrix :
 [[2996 1051]
 [1195 2852]]
Accuracy on test set:    0.722510501606128
Sensitivity:    0.7047195453422288 	 Specificity:    0.7403014578700272
Precision  : 0.7307199590058929
Area Under Curve:    0.722510501606128
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5882 - accuracy: 0.6827 - val_loss: 0.5497 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7204 - val_loss: 0.5424 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7317 - val_loss: 0.5415 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7385 - val_loss: 0.5440 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7465 - val_loss: 0.5418 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7535 - val_loss: 0.5468 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4878 - accuracy: 0.7634
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.7631 - val_loss: 0.5464 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 836us/step
Independent Testing Matthews Correlation:  0.47183684883248694
Confusion Matrix :
 [[2873 1174]
 [ 966 3081]]
Accuracy on test set:    0.735606622189276
Sensitivity:    0.7613046701260193 	 Specificity:    0.7099085742525327
Precision  : 0.7240893066980023
Area Under Curve:    0.735606622189276
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5946 - accuracy: 0.6798 - val_loss: 0.5504 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7193 - val_loss: 0.5429 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5355 - accuracy: 0.7306 - val_loss: 0.5421 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5238 - accuracy: 0.7382 - val_loss: 0.5424 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5122 - accuracy: 0.7456 - val_loss: 0.5498 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7535 - val_loss: 0.5494 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4905 - accuracy: 0.7626 - val_loss: 0.5465 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7703 - val_loss: 0.5564 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4655 - accuracy: 0.7791 - val_loss: 0.5596 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4528 - accuracy: 0.7865
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4540 - accuracy: 0.7859 - val_loss: 0.5617 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 888us/step
Independent Testing Matthews Correlation:  0.468010510223488
Confusion Matrix :
 [[3037 1010]
 [1144 2903]]
Accuracy on test set:    0.7338769458858414
Sensitivity:    0.717321472695824 	 Specificity:    0.7504324190758587
Precision  : 0.7418860209557884
Area Under Curve:    0.7338769458858414
(8094, 2560) (8094,)
Mean MCC = 0.4356 + 0.0210 and Mean AUC = 0.7169 + 0.0113
Mean Sensitivity = 0.7476 + 0.0283 and Mean Specificity = 0.6863 + 0.0438 and Mean Accuracy = 0.7169 + 0.0113
Mean Precision = 0.7058 + 0.0221





Seed   : 196769
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5811 - accuracy: 0.6880 - val_loss: 0.5535 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5407 - accuracy: 0.7248 - val_loss: 0.5488 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5250 - accuracy: 0.7382 - val_loss: 0.5498 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5128 - accuracy: 0.7431 - val_loss: 0.5457 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.7540 - val_loss: 0.5546 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.7604 - val_loss: 0.5611 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4791 - accuracy: 0.7699
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7695 - val_loss: 0.5598 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39895418754593526
Confusion Matrix :
 [[2494 1554]
 [ 900 3147]]
Accuracy on test set:    0.6968499073502162
Sensitivity:    0.7776130467012602 	 Specificity:    0.616106719367589
Precision  : 0.6694320357370772
Area Under Curve:    0.6968598830344246
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5837 - accuracy: 0.6863 - val_loss: 0.5519 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5404 - accuracy: 0.7249 - val_loss: 0.5447 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5245 - accuracy: 0.7364 - val_loss: 0.5461 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5125 - accuracy: 0.7453 - val_loss: 0.5463 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7550 - val_loss: 0.5474 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4863 - accuracy: 0.7640 - val_loss: 0.5554 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4740 - accuracy: 0.7720 - val_loss: 0.5536 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4623 - accuracy: 0.7810 - val_loss: 0.5562 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4477 - accuracy: 0.7896 - val_loss: 0.5627 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4351 - accuracy: 0.7976
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4351 - accuracy: 0.7977 - val_loss: 0.5644 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 792us/step
Independent Testing Matthews Correlation:  0.39753006265173535
Confusion Matrix :
 [[3044 1004]
 [1444 2603]]
Accuracy on test set:    0.6975911056207535
Sensitivity:    0.6431924882629108 	 Specificity:    0.7519762845849802
Precision  : 0.7216523426670364
Area Under Curve:    0.6975843864239455
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5883 - accuracy: 0.6828 - val_loss: 0.5502 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7227 - val_loss: 0.5374 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7336 - val_loss: 0.5360 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7408 - val_loss: 0.5332 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7486 - val_loss: 0.5337 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7577 - val_loss: 0.5399 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4887 - accuracy: 0.7638 - val_loss: 0.5358 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4757 - accuracy: 0.7718 - val_loss: 0.5377 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4637 - accuracy: 0.7796 - val_loss: 0.5455 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4513 - accuracy: 0.7876
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4520 - accuracy: 0.7873 - val_loss: 0.5474 - val_accuracy: 0.7285 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.437021669826447
Confusion Matrix :
 [[2802 1245]
 [1036 3012]]
Accuracy on test set:    0.7182211241507103
Sensitivity:    0.7440711462450593 	 Specificity:    0.69236471460341
Precision  : 0.7075405214940098
Area Under Curve:    0.7182179304242347
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5896 - accuracy: 0.6808 - val_loss: 0.5428 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7217 - val_loss: 0.5381 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7334 - val_loss: 0.5366 - val_accuracy: 0.7315 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7424 - val_loss: 0.5319 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7494 - val_loss: 0.5426 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7585 - val_loss: 0.5332 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7656 - val_loss: 0.5370 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4673 - accuracy: 0.7761 - val_loss: 0.5483 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4555 - accuracy: 0.7841
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4559 - accuracy: 0.7837 - val_loss: 0.5411 - val_accuracy: 0.7297 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4239192299057122
Confusion Matrix :
 [[2801 1246]
 [1087 2961]]
Accuracy on test set:    0.7117974058060531
Sensitivity:    0.7314723320158103 	 Specificity:    0.6921176179886336
Precision  : 0.7038269550748752
Area Under Curve:    0.7117949750022219
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5865 - accuracy: 0.6845 - val_loss: 0.5547 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7252 - val_loss: 0.5467 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7341 - val_loss: 0.5447 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7394 - val_loss: 0.5432 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7490 - val_loss: 0.5523 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7535 - val_loss: 0.5444 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7634 - val_loss: 0.5485 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.7721 - val_loss: 0.5527 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4636 - accuracy: 0.7797 - val_loss: 0.5510 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4524 - accuracy: 0.7880 - val_loss: 0.5613 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4385 - accuracy: 0.7962 - val_loss: 0.5555 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4264 - accuracy: 0.8033 - val_loss: 0.5719 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4137 - accuracy: 0.8106 - val_loss: 0.5791 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 14/400
249/257 [============================>.] - ETA: 0s - loss: 0.4010 - accuracy: 0.8181
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4013 - accuracy: 0.8181 - val_loss: 0.5775 - val_accuracy: 0.7115 - lr: 0.0010
253/253 [==============================] - 0s 981us/step
Independent Testing Matthews Correlation:  0.4136633749000151
Confusion Matrix :
 [[2736 1311]
 [1065 2982]]
Accuracy on test set:    0.7064492216456635
Sensitivity:    0.7368421052631579 	 Specificity:    0.676056338028169
Precision  : 0.6946191474493362
Area Under Curve:    0.7064492216456635
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5915 - accuracy: 0.6818 - val_loss: 0.5556 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7209 - val_loss: 0.5554 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5332 - accuracy: 0.7322 - val_loss: 0.5483 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5216 - accuracy: 0.7398 - val_loss: 0.5524 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7478 - val_loss: 0.5494 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
248/257 [===========================>..] - ETA: 0s - loss: 0.5005 - accuracy: 0.7538
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7540 - val_loss: 0.5515 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 880us/step
Independent Testing Matthews Correlation:  0.4383010815485412
Confusion Matrix :
 [[2682 1365]
 [ 919 3128]]
Accuracy on test set:    0.7178156659253768
Sensitivity:    0.7729182110205091 	 Specificity:    0.6627131208302446
Precision  : 0.6961940796795014
Area Under Curve:    0.7178156659253768
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5877 - accuracy: 0.6842 - val_loss: 0.5499 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7235 - val_loss: 0.5507 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7342 - val_loss: 0.5441 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7398 - val_loss: 0.5457 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7501 - val_loss: 0.5451 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7569 - val_loss: 0.5470 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.7653 - val_loss: 0.5481 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.7723 - val_loss: 0.5531 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4629 - accuracy: 0.7794 - val_loss: 0.5629 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4513 - accuracy: 0.7888
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4513 - accuracy: 0.7889 - val_loss: 0.5624 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.41859232273415675
Confusion Matrix :
 [[2799 1248]
 [1106 2941]]
Accuracy on test set:    0.7091672844082036
Sensitivity:    0.7267111440573264 	 Specificity:    0.6916234247590808
Precision  : 0.7020768679875865
Area Under Curve:    0.7091672844082035
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5905 - accuracy: 0.6810 - val_loss: 0.5535 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7211 - val_loss: 0.5475 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7327 - val_loss: 0.5440 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7405 - val_loss: 0.5439 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7486 - val_loss: 0.5467 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7572 - val_loss: 0.5488 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7643 - val_loss: 0.5467 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4733 - accuracy: 0.7741 - val_loss: 0.5482 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4619 - accuracy: 0.7810 - val_loss: 0.5555 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4510 - accuracy: 0.7862
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4509 - accuracy: 0.7863 - val_loss: 0.5628 - val_accuracy: 0.7135 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42942473595527353
Confusion Matrix :
 [[3081  966]
 [1351 2696]]
Accuracy on test set:    0.7137385717815666
Sensitivity:    0.6661724734371139 	 Specificity:    0.7613046701260193
Precision  : 0.736209721463681
Area Under Curve:    0.7137385717815666
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5923 - accuracy: 0.6805 - val_loss: 0.5598 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5482 - accuracy: 0.7198 - val_loss: 0.5482 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5340 - accuracy: 0.7296 - val_loss: 0.5487 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5241 - accuracy: 0.7377 - val_loss: 0.5459 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7447 - val_loss: 0.5467 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7528 - val_loss: 0.5527 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7596 - val_loss: 0.5507 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7645 - val_loss: 0.5569 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.7725 - val_loss: 0.5579 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4656 - accuracy: 0.7794
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4656 - accuracy: 0.7797 - val_loss: 0.5595 - val_accuracy: 0.7121 - lr: 0.0010
253/253 [==============================] - 0s 699us/step
Independent Testing Matthews Correlation:  0.46105970223365067
Confusion Matrix :
 [[2864 1183]
 [1000 3047]]
Accuracy on test set:    0.7302940449715839
Sensitivity:    0.7529033852236224 	 Specificity:    0.7076847047195454
Precision  : 0.7203309692671395
Area Under Curve:    0.7302940449715839
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5944 - accuracy: 0.6788 - val_loss: 0.5577 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5510 - accuracy: 0.7206 - val_loss: 0.5503 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5360 - accuracy: 0.7299 - val_loss: 0.5521 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5247 - accuracy: 0.7375 - val_loss: 0.5484 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5150 - accuracy: 0.7441 - val_loss: 0.5499 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7519 - val_loss: 0.5506 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.7591 - val_loss: 0.5564 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7672 - val_loss: 0.5626 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7775 - val_loss: 0.5617 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4535 - accuracy: 0.7867 - val_loss: 0.5722 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 11/400
252/257 [============================>.] - ETA: 0s - loss: 0.4438 - accuracy: 0.7927
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4437 - accuracy: 0.7928 - val_loss: 0.5688 - val_accuracy: 0.7112 - lr: 0.0010
253/253 [==============================] - 0s 809us/step
Independent Testing Matthews Correlation:  0.47850519953650383
Confusion Matrix :
 [[3177  870]
 [1249 2798]]
Accuracy on test set:    0.738201136644428
Sensitivity:    0.6913763281443044 	 Specificity:    0.7850259451445515
Precision  : 0.762813522355507
Area Under Curve:    0.7382011366444279
(8094, 2560) (8094,)
Mean MCC = 0.4297 + 0.0243 and Mean AUC = 0.7140 + 0.0124
Mean Sensitivity = 0.7243 + 0.0420 and Mean Specificity = 0.7037 + 0.0478 and Mean Accuracy = 0.7140 + 0.0124
Mean Precision = 0.7115 + 0.0242





Seed   : 524085
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5835 - accuracy: 0.6874 - val_loss: 0.5622 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5403 - accuracy: 0.7247 - val_loss: 0.5548 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5240 - accuracy: 0.7385 - val_loss: 0.5460 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5115 - accuracy: 0.7464 - val_loss: 0.5482 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7549 - val_loss: 0.5477 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7636 - val_loss: 0.5576 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4763 - accuracy: 0.7708 - val_loss: 0.5631 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4624 - accuracy: 0.7800 - val_loss: 0.5626 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4487 - accuracy: 0.7899
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4493 - accuracy: 0.7894 - val_loss: 0.5661 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4027013878899154
Confusion Matrix :
 [[2754 1294]
 [1125 2922]]
Accuracy on test set:    0.7011735639283508
Sensitivity:    0.7220163083765753 	 Specificity:    0.6803359683794467
Precision  : 0.6930740037950665
Area Under Curve:    0.7011761383780111
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5822 - accuracy: 0.6905 - val_loss: 0.5565 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5412 - accuracy: 0.7258 - val_loss: 0.5482 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5259 - accuracy: 0.7370 - val_loss: 0.5480 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5148 - accuracy: 0.7460 - val_loss: 0.5474 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7513 - val_loss: 0.5489 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.7607 - val_loss: 0.5564 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4805 - accuracy: 0.7687 - val_loss: 0.5520 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4686 - accuracy: 0.7772 - val_loss: 0.5535 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4562 - accuracy: 0.7863 - val_loss: 0.5643 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4413 - accuracy: 0.7936
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4419 - accuracy: 0.7933 - val_loss: 0.5614 - val_accuracy: 0.7084 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4111438634652798
Confusion Matrix :
 [[2767 1281]
 [1104 2943]]
Accuracy on test set:    0.705373687461396
Sensitivity:    0.7272053372868792 	 Specificity:    0.6835474308300395
Precision  : 0.6967329545454546
Area Under Curve:    0.7053763840584594
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5879 - accuracy: 0.6850 - val_loss: 0.5504 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7223 - val_loss: 0.5407 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7322 - val_loss: 0.5458 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7405 - val_loss: 0.5444 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7494 - val_loss: 0.5412 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4980 - accuracy: 0.7553 - val_loss: 0.5397 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7655 - val_loss: 0.5418 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4760 - accuracy: 0.7712 - val_loss: 0.5539 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.7801 - val_loss: 0.5488 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4511 - accuracy: 0.7893 - val_loss: 0.5556 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - ETA: 0s - loss: 0.4394 - accuracy: 0.7950
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4394 - accuracy: 0.7950 - val_loss: 0.5623 - val_accuracy: 0.7138 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41809820772074036
Confusion Matrix :
 [[2929 1118]
 [1238 2810]]
Accuracy on test set:    0.7089561457689932
Sensitivity:    0.6941699604743083 	 Specificity:    0.7237459846800098
Precision  : 0.7153767820773931
Area Under Curve:    0.7089579725771591
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5855 - accuracy: 0.6853 - val_loss: 0.5478 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7229 - val_loss: 0.5364 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7326 - val_loss: 0.5339 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7434 - val_loss: 0.5403 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7504 - val_loss: 0.5348 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7569 - val_loss: 0.5372 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.7675 - val_loss: 0.5396 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.7736 - val_loss: 0.5452 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4583 - accuracy: 0.7838 - val_loss: 0.5477 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4468 - accuracy: 0.7907 - val_loss: 0.5512 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4326 - accuracy: 0.8002
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4324 - accuracy: 0.8003 - val_loss: 0.5644 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4150864255794408
Confusion Matrix :
 [[2537 1510]
 [ 878 3170]]
Accuracy on test set:    0.7050030883261272
Sensitivity:    0.783102766798419 	 Specificity:    0.6268841116876699
Precision  : 0.6773504273504274
Area Under Curve:    0.7049934392430445
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5876 - accuracy: 0.6828 - val_loss: 0.5579 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7239 - val_loss: 0.5427 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7315 - val_loss: 0.5418 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7396 - val_loss: 0.5457 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5122 - accuracy: 0.7446 - val_loss: 0.5411 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5024 - accuracy: 0.7526 - val_loss: 0.5444 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7598 - val_loss: 0.5426 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7667 - val_loss: 0.5434 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4743 - accuracy: 0.7717 - val_loss: 0.5462 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.7791 - val_loss: 0.5529 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4529 - accuracy: 0.7862 - val_loss: 0.5581 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4406 - accuracy: 0.7939 - val_loss: 0.5586 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4295 - accuracy: 0.8019 - val_loss: 0.5656 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4193 - accuracy: 0.8102 - val_loss: 0.5701 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 15/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4054 - accuracy: 0.8161
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4056 - accuracy: 0.8159 - val_loss: 0.5741 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 865us/step
Independent Testing Matthews Correlation:  0.4181092937403758
Confusion Matrix :
 [[2695 1352]
 [1009 3038]]
Accuracy on test set:    0.7083024462564863
Sensitivity:    0.7506795156906351 	 Specificity:    0.6659253768223375
Precision  : 0.6920273348519362
Area Under Curve:    0.7083024462564862
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5863 - accuracy: 0.6853 - val_loss: 0.5600 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7242 - val_loss: 0.5466 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7350 - val_loss: 0.5449 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5142 - accuracy: 0.7446 - val_loss: 0.5456 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7525 - val_loss: 0.5446 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7609 - val_loss: 0.5461 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.7700 - val_loss: 0.5466 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.7772 - val_loss: 0.5484 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4538 - accuracy: 0.7850 - val_loss: 0.5562 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4409 - accuracy: 0.7941
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4409 - accuracy: 0.7941 - val_loss: 0.5628 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4339411316177535
Confusion Matrix :
 [[2744 1303]
 [ 993 3054]]
Accuracy on test set:    0.7163330862367185
Sensitivity:    0.7546330615270571 	 Specificity:    0.6780331109463801
Precision  : 0.7009410144594905
Area Under Curve:    0.7163330862367185
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5870 - accuracy: 0.6858 - val_loss: 0.5538 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7222 - val_loss: 0.5417 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7337 - val_loss: 0.5401 - val_accuracy: 0.7194 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7409 - val_loss: 0.5388 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.7479 - val_loss: 0.5402 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4994 - accuracy: 0.7561 - val_loss: 0.5405 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.7621 - val_loss: 0.5444 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7700 - val_loss: 0.5496 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4647 - accuracy: 0.7779
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4647 - accuracy: 0.7779 - val_loss: 0.5525 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 782us/step
Independent Testing Matthews Correlation:  0.41413870593180385
Confusion Matrix :
 [[3043 1004]
 [1374 2673]]
Accuracy on test set:    0.7062021250308871
Sensitivity:    0.6604892512972572 	 Specificity:    0.751914998764517
Precision  : 0.7269513190100626
Area Under Curve:    0.7062021250308872
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5860 - accuracy: 0.6858 - val_loss: 0.5464 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7232 - val_loss: 0.5430 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7340 - val_loss: 0.5402 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7426 - val_loss: 0.5378 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7495 - val_loss: 0.5402 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4970 - accuracy: 0.7584 - val_loss: 0.5494 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7663 - val_loss: 0.5401 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.7746 - val_loss: 0.5452 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4577 - accuracy: 0.7848 - val_loss: 0.5507 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4452 - accuracy: 0.7935 - val_loss: 0.5469 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4324 - accuracy: 0.8002 - val_loss: 0.5587 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4203 - accuracy: 0.8076 - val_loss: 0.5578 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4060 - accuracy: 0.8156 - val_loss: 0.5675 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3922 - accuracy: 0.8222 - val_loss: 0.5800 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3808 - accuracy: 0.8288 - val_loss: 0.5824 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 16/400
256/257 [============================>.] - ETA: 0s - loss: 0.3694 - accuracy: 0.8345
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3694 - accuracy: 0.8345 - val_loss: 0.5890 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43174996913535824
Confusion Matrix :
 [[2934 1113]
 [1187 2860]]
Accuracy on test set:    0.7158388930071659
Sensitivity:    0.7066963182604399 	 Specificity:    0.7249814677538917
Precision  : 0.7198590485779008
Area Under Curve:    0.7158388930071657
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5903 - accuracy: 0.6797 - val_loss: 0.5520 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7211 - val_loss: 0.5422 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7315 - val_loss: 0.5397 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7416 - val_loss: 0.5449 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7489 - val_loss: 0.5429 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7586 - val_loss: 0.5435 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7654 - val_loss: 0.5467 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7742 - val_loss: 0.5480 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4576 - accuracy: 0.7829 - val_loss: 0.5580 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4443 - accuracy: 0.7917 - val_loss: 0.5583 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
249/257 [============================>.] - ETA: 0s - loss: 0.4305 - accuracy: 0.8008
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4310 - accuracy: 0.8007 - val_loss: 0.5597 - val_accuracy: 0.7213 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46116057054786425
Confusion Matrix :
 [[3032 1015]
 [1167 2880]]
Accuracy on test set:    0.730417593278972
Sensitivity:    0.7116382505559674 	 Specificity:    0.7491969360019768
Precision  : 0.7394094993581515
Area Under Curve:    0.730417593278972
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5932 - accuracy: 0.6796 - val_loss: 0.5533 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5523 - accuracy: 0.7163 - val_loss: 0.5447 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5362 - accuracy: 0.7296 - val_loss: 0.5451 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5239 - accuracy: 0.7383 - val_loss: 0.5438 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7459 - val_loss: 0.5421 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7518 - val_loss: 0.5470 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.7611 - val_loss: 0.5531 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4797 - accuracy: 0.7682
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4797 - accuracy: 0.7682 - val_loss: 0.5527 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4899207075789388
Confusion Matrix :
 [[3098  949]
 [1117 2930]]
Accuracy on test set:    0.744749196936002
Sensitivity:    0.7239930812947862 	 Specificity:    0.7655053125772177
Precision  : 0.7553493168342357
Area Under Curve:    0.744749196936002
(8094, 2560) (8094,)
Mean MCC = 0.4296 + 0.0254 and Mean AUC = 0.7142 + 0.0129
Mean Sensitivity = 0.7235 + 0.0325 and Mean Specificity = 0.7050 + 0.0424 and Mean Accuracy = 0.7142 + 0.0129
Mean Precision = 0.7117 + 0.0229





Seed   : 769961
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5858 - accuracy: 0.6848 - val_loss: 0.5639 - val_accuracy: 0.7027 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7243 - val_loss: 0.5531 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5242 - accuracy: 0.7370 - val_loss: 0.5510 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5122 - accuracy: 0.7454 - val_loss: 0.5561 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7545 - val_loss: 0.5561 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4892 - accuracy: 0.7622 - val_loss: 0.5517 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4764 - accuracy: 0.7701 - val_loss: 0.5519 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4641 - accuracy: 0.7792
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4634 - accuracy: 0.7794 - val_loss: 0.5678 - val_accuracy: 0.7109 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3994240487738633
Confusion Matrix :
 [[2639 1409]
 [1029 3018]]
Accuracy on test set:    0.6988264360716492
Sensitivity:    0.7457375833951075 	 Specificity:    0.6519268774703557
Precision  : 0.6817257736616219
Area Under Curve:    0.6988322304327317
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5876 - accuracy: 0.6844 - val_loss: 0.5585 - val_accuracy: 0.7038 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5412 - accuracy: 0.7261 - val_loss: 0.5511 - val_accuracy: 0.7035 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5261 - accuracy: 0.7375 - val_loss: 0.5463 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7448 - val_loss: 0.5469 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7517 - val_loss: 0.5479 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7586 - val_loss: 0.5502 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7676 - val_loss: 0.5512 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4701 - accuracy: 0.7755
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4701 - accuracy: 0.7757 - val_loss: 0.5539 - val_accuracy: 0.7135 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.41258868643768376
Confusion Matrix :
 [[2968 1080]
 [1300 2747]]
Accuracy on test set:    0.7059913526868438
Sensitivity:    0.6787744007907092 	 Specificity:    0.733201581027668
Precision  : 0.7177946171936243
Area Under Curve:    0.7059879909091886
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5843 - accuracy: 0.6888 - val_loss: 0.5487 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7227 - val_loss: 0.5462 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7337 - val_loss: 0.5375 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7421 - val_loss: 0.5372 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7494 - val_loss: 0.5368 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7575 - val_loss: 0.5383 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7659 - val_loss: 0.5404 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4685 - accuracy: 0.7758 - val_loss: 0.5460 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4558 - accuracy: 0.7843 - val_loss: 0.5484 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4437 - accuracy: 0.7920
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4437 - accuracy: 0.7920 - val_loss: 0.5514 - val_accuracy: 0.7219 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4162492261052289
Confusion Matrix :
 [[2829 1218]
 [1145 2903]]
Accuracy on test set:    0.7080914144533663
Sensitivity:    0.7171442687747036 	 Specificity:    0.6990363232023721
Precision  : 0.7044406697403542
Area Under Curve:    0.708090295988538
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5873 - accuracy: 0.6845 - val_loss: 0.5491 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7229 - val_loss: 0.5393 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5331 - accuracy: 0.7304 - val_loss: 0.5343 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7395 - val_loss: 0.5348 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5112 - accuracy: 0.7472 - val_loss: 0.5398 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5023 - accuracy: 0.7522 - val_loss: 0.5341 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7610 - val_loss: 0.5367 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7705 - val_loss: 0.5355 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4702 - accuracy: 0.7771 - val_loss: 0.5374 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4557 - accuracy: 0.7853 - val_loss: 0.5484 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4434 - accuracy: 0.7933 - val_loss: 0.5493 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4306 - accuracy: 0.8004 - val_loss: 0.5507 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 13/400

256/257 [============================>.] - ETA: 0s - loss: 0.4199 - accuracy: 0.8071
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4199 - accuracy: 0.8071 - val_loss: 0.5560 - val_accuracy: 0.7207 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4142652589699669
Confusion Matrix :
 [[2827 1220]
 [1151 2897]]
Accuracy on test set:    0.7071031500926498
Sensitivity:    0.7156620553359684 	 Specificity:    0.6985421299728194
Precision  : 0.7036677192130192
Area Under Curve:    0.7071020926543938
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5871 - accuracy: 0.6845 - val_loss: 0.5517 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7216 - val_loss: 0.5445 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7315 - val_loss: 0.5405 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.7367 - val_loss: 0.5472 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5125 - accuracy: 0.7445 - val_loss: 0.5401 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7528 - val_loss: 0.5465 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7576 - val_loss: 0.5453 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4836 - accuracy: 0.7648
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7644 - val_loss: 0.5471 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 822us/step
Independent Testing Matthews Correlation:  0.4247609480899581
Confusion Matrix :
 [[2877 1170]
 [1158 2889]]
Accuracy on test set:    0.7123795404002965
Sensitivity:    0.7138621200889548 	 Specificity:    0.7108969607116382
Precision  : 0.7117516629711752
Area Under Curve:    0.7123795404002965
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5860 - accuracy: 0.6856 - val_loss: 0.5513 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7222 - val_loss: 0.5466 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7343 - val_loss: 0.5408 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7416 - val_loss: 0.5451 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7496 - val_loss: 0.5432 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7584 - val_loss: 0.5422 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4819 - accuracy: 0.7658 - val_loss: 0.5470 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4701 - accuracy: 0.7760
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4706 - accuracy: 0.7756 - val_loss: 0.5494 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4326033273595489
Confusion Matrix :
 [[2659 1388]
 [ 920 3127]]
Accuracy on test set:    0.7148505065480603
Sensitivity:    0.7726711144057327 	 Specificity:    0.657029898690388
Precision  : 0.6925802879291252
Area Under Curve:    0.7148505065480604
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5900 - accuracy: 0.6816 - val_loss: 0.5589 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7215 - val_loss: 0.5450 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7328 - val_loss: 0.5419 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7404 - val_loss: 0.5400 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7466 - val_loss: 0.5420 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7582 - val_loss: 0.5437 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7672 - val_loss: 0.5450 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.7765 - val_loss: 0.5476 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4524 - accuracy: 0.7856
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4526 - accuracy: 0.7848 - val_loss: 0.5529 - val_accuracy: 0.7175 - lr: 0.0010
253/253 [==============================] - 0s 792us/step
Independent Testing Matthews Correlation:  0.4304820590689313
Confusion Matrix :
 [[2867 1180]
 [1125 2922]]
Accuracy on test set:    0.7152211514702248
Sensitivity:    0.7220163083765753 	 Specificity:    0.7084259945638745
Precision  : 0.712335446123842
Area Under Curve:    0.7152211514702249
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5866 - accuracy: 0.6840 - val_loss: 0.5510 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7227 - val_loss: 0.5420 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7333 - val_loss: 0.5376 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7384 - val_loss: 0.5373 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7476 - val_loss: 0.5396 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7553 - val_loss: 0.5369 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4882 - accuracy: 0.7641
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.7641 - val_loss: 0.5375 - val_accuracy: 0.7257 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43553649025400576
Confusion Matrix :
 [[2851 1196]
 [1089 2958]]
Accuracy on test set:    0.7176921176179887
Sensitivity:    0.7309117865085248 	 Specificity:    0.7044724487274524
Precision  : 0.7120847376023111
Area Under Curve:    0.7176921176179887
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5878 - accuracy: 0.6851 - val_loss: 0.5495 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7213 - val_loss: 0.5435 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5326 - accuracy: 0.7301 - val_loss: 0.5399 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7382 - val_loss: 0.5463 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5119 - accuracy: 0.7454 - val_loss: 0.5382 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5019 - accuracy: 0.7541 - val_loss: 0.5393 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.7619 - val_loss: 0.5421 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4819 - accuracy: 0.7691
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4817 - accuracy: 0.7690 - val_loss: 0.5439 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 758us/step
Independent Testing Matthews Correlation:  0.46359972108358527
Confusion Matrix :
 [[2889 1158]
 [1014 3033]]
Accuracy on test set:    0.7316530763528539
Sensitivity:    0.7494440326167532 	 Specificity:    0.7138621200889548
Precision  : 0.7236936292054402
Area Under Curve:    0.731653076352854
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5932 - accuracy: 0.6807 - val_loss: 0.5525 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5536 - accuracy: 0.7180 - val_loss: 0.5431 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5402 - accuracy: 0.7260 - val_loss: 0.5407 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7346 - val_loss: 0.5421 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7411 - val_loss: 0.5423 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7493 - val_loss: 0.5420 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7558 - val_loss: 0.5443 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7645 - val_loss: 0.5471 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4765 - accuracy: 0.7733
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4765 - accuracy: 0.7732 - val_loss: 0.5477 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 899us/step
Independent Testing Matthews Correlation:  0.4687700907821017
Confusion Matrix :
 [[3203  844]
 [1319 2728]]
Accuracy on test set:    0.7327650111193477
Sensitivity:    0.674079565109958 	 Specificity:    0.7914504571287373
Precision  : 0.7637178051511758
Area Under Curve:    0.7327650111193476
(8094, 2560) (8094,)
Mean MCC = 0.4298 + 0.0209 and Mean AUC = 0.7145 + 0.0103
Mean Sensitivity = 0.7220 + 0.0287 and Mean Specificity = 0.7069 + 0.0368 and Mean Accuracy = 0.7145 + 0.0103
Mean Precision = 0.7124 + 0.0206





Seed   : 794587
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5846 - accuracy: 0.6846 - val_loss: 0.5631 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5398 - accuracy: 0.7271 - val_loss: 0.5539 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5246 - accuracy: 0.7377 - val_loss: 0.5524 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7473 - val_loss: 0.5583 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4991 - accuracy: 0.7560 - val_loss: 0.5522 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4861 - accuracy: 0.7637 - val_loss: 0.5530 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7720 - val_loss: 0.5619 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4597 - accuracy: 0.7825 - val_loss: 0.5688 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4462 - accuracy: 0.7916 - val_loss: 0.5682 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4333 - accuracy: 0.7987 - val_loss: 0.5701 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 11/400
251/257 [============================>.] - ETA: 0s - loss: 0.4206 - accuracy: 0.8075
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4208 - accuracy: 0.8073 - val_loss: 0.5768 - val_accuracy: 0.7149 - lr: 0.0010
253/253 [==============================] - 0s 942us/step
Independent Testing Matthews Correlation:  0.4129667830640818
Confusion Matrix :
 [[2738 1310]
 [1069 2978]]
Accuracy on test set:    0.7061148857319333
Sensitivity:    0.7358537188040524 	 Specificity:    0.6763833992094862
Precision  : 0.6944962686567164
Area Under Curve:    0.7061185590067692
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5852 - accuracy: 0.6853 - val_loss: 0.5599 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7250 - val_loss: 0.5553 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7361 - val_loss: 0.5631 - val_accuracy: 0.7009 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7423 - val_loss: 0.5518 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5043 - accuracy: 0.7509 - val_loss: 0.5567 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7596 - val_loss: 0.5524 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4812 - accuracy: 0.7684
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.7684 - val_loss: 0.5582 - val_accuracy: 0.7056 - lr: 0.0010
253/253 [==============================] - 0s 766us/step
Independent Testing Matthews Correlation:  0.4343357130140896
Confusion Matrix :
 [[2795 1253]
 [1039 3008]]
Accuracy on test set:    0.7168622606547251
Sensitivity:    0.7432666172473437 	 Specificity:    0.6904644268774703
Precision  : 0.7059375733395916
Area Under Curve:    0.7168655220624071
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6837 - val_loss: 0.5537 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7231 - val_loss: 0.5484 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7327 - val_loss: 0.5445 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7425 - val_loss: 0.5458 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400

257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7502 - val_loss: 0.5505 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7585 - val_loss: 0.5558 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7690 - val_loss: 0.5512 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7779 - val_loss: 0.5560 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4521 - accuracy: 0.7878
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4517 - accuracy: 0.7881 - val_loss: 0.5665 - val_accuracy: 0.7149 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42068274458201005
Confusion Matrix :
 [[2770 1277]
 [1070 2978]]
Accuracy on test set:    0.7100679431747993
Sensitivity:    0.7356719367588933 	 Specificity:    0.6844576229305659
Precision  : 0.699882491186839
Area Under Curve:    0.7100647798447297
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5920 - accuracy: 0.6792 - val_loss: 0.5541 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7219 - val_loss: 0.5453 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7325 - val_loss: 0.5390 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7436 - val_loss: 0.5413 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7515 - val_loss: 0.5419 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7604 - val_loss: 0.5451 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.7676 - val_loss: 0.5453 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.7764 - val_loss: 0.5533 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4524 - accuracy: 0.7849 - val_loss: 0.5556 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4392 - accuracy: 0.7931
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4393 - accuracy: 0.7927 - val_loss: 0.5648 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4235196666412755
Confusion Matrix :
 [[2822 1225]
 [1109 2939]]
Accuracy on test set:    0.7116738727609636
Sensitivity:    0.7260375494071146 	 Specificity:    0.6973066468989375
Precision  : 0.7058117195004803
Area Under Curve:    0.7116720981530261
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5869 - accuracy: 0.6857 - val_loss: 0.5527 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7255 - val_loss: 0.5424 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7346 - val_loss: 0.5534 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7426 - val_loss: 0.5404 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7517 - val_loss: 0.5425 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7578 - val_loss: 0.5444 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7672 - val_loss: 0.5423 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4700 - accuracy: 0.7763 - val_loss: 0.5495 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4557 - accuracy: 0.7855 - val_loss: 0.5554 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4435 - accuracy: 0.7938 - val_loss: 0.5598 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4315 - accuracy: 0.8008 - val_loss: 0.5615 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 12/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4164 - accuracy: 0.8103
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4170 - accuracy: 0.8103 - val_loss: 0.5646 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 687us/step
Independent Testing Matthews Correlation:  0.416040489516409
Confusion Matrix :
 [[2806 1241]
 [1123 2924]]
Accuracy on test set:    0.7079318013343218
Sensitivity:    0.722510501606128 	 Specificity:    0.6933531010625155
Precision  : 0.7020408163265306
Area Under Curve:    0.7079318013343217
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5891 - accuracy: 0.6819 - val_loss: 0.5563 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7220 - val_loss: 0.5521 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7321 - val_loss: 0.5507 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7414 - val_loss: 0.5449 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7485 - val_loss: 0.5487 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7562 - val_loss: 0.5462 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7662 - val_loss: 0.5566 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4738 - accuracy: 0.7732 - val_loss: 0.5536 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.7834 - val_loss: 0.5555 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4480 - accuracy: 0.7896 - val_loss: 0.5606 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 11/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4343 - accuracy: 0.7988
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4345 - accuracy: 0.7983 - val_loss: 0.5752 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 763us/step
Independent Testing Matthews Correlation:  0.42771728539477044
Confusion Matrix :
 [[2750 1297]
 [1023 3024]]
Accuracy on test set:    0.713367926859402
Sensitivity:    0.7472201630837657 	 Specificity:    0.6795156906350382
Precision  : 0.6998380004628558
Area Under Curve:    0.7133679268594021
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5871 - accuracy: 0.6855 - val_loss: 0.5533 - val_accuracy: 0.7149 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7218 - val_loss: 0.5495 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7330 - val_loss: 0.5476 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5209 - accuracy: 0.7389 - val_loss: 0.5474 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5109 - accuracy: 0.7475 - val_loss: 0.5496 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7527 - val_loss: 0.5481 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7614 - val_loss: 0.5529 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.7685 - val_loss: 0.5554 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4714 - accuracy: 0.7760 - val_loss: 0.5556 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4576 - accuracy: 0.7842
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4576 - accuracy: 0.7842 - val_loss: 0.5626 - val_accuracy: 0.7146 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.437474076752907
Confusion Matrix :
 [[2763 1284]
 [ 997 3050]]
Accuracy on test set:    0.7181863108475414
Sensitivity:    0.7536446750679515 	 Specificity:    0.6827279466271312
Precision  : 0.7037378864790033
Area Under Curve:    0.7181863108475414
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5836 - accuracy: 0.6868 - val_loss: 0.5519 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7237 - val_loss: 0.5439 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7335 - val_loss: 0.5466 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7420 - val_loss: 0.5453 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7502 - val_loss: 0.5486 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7576 - val_loss: 0.5464 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4861 - accuracy: 0.7628
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4862 - accuracy: 0.7626 - val_loss: 0.5466 - val_accuracy: 0.7145 - lr: 0.0010
253/253 [==============================] - 0s 762us/step
Independent Testing Matthews Correlation:  0.4418657437812791
Confusion Matrix :
 [[2950 1097]
 [1162 2885]]
Accuracy on test set:    0.7209043736100815
Sensitivity:    0.7128737336298493 	 Specificity:    0.7289350135903138
Precision  : 0.7245102963335007
Area Under Curve:    0.7209043736100816
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5931 - accuracy: 0.6797 - val_loss: 0.5570 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5492 - accuracy: 0.7195 - val_loss: 0.5479 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5360 - accuracy: 0.7303 - val_loss: 0.5487 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5255 - accuracy: 0.7377 - val_loss: 0.5455 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7451 - val_loss: 0.5591 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7525 - val_loss: 0.5466 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7586 - val_loss: 0.5538 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.7685 - val_loss: 0.5568 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4712 - accuracy: 0.7764
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4708 - accuracy: 0.7767 - val_loss: 0.5597 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 912us/step
Independent Testing Matthews Correlation:  0.4688663545956018
Confusion Matrix :
 [[2891 1156]
 [ 995 3052]]
Accuracy on test set:    0.734247590808006
Sensitivity:    0.7541388682975043 	 Specificity:    0.7143563133185076
Precision  : 0.7252851711026616
Area Under Curve:    0.734247590808006
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5951 - accuracy: 0.6785 - val_loss: 0.5586 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5502 - accuracy: 0.7192 - val_loss: 0.5523 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5352 - accuracy: 0.7298 - val_loss: 0.5532 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5246 - accuracy: 0.7390 - val_loss: 0.5514 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.7458 - val_loss: 0.5530 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7535 - val_loss: 0.5550 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4909 - accuracy: 0.7624
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4907 - accuracy: 0.7626 - val_loss: 0.5563 - val_accuracy: 0.7097 - lr: 0.0010
253/253 [==============================] - 0s 841us/step
Independent Testing Matthews Correlation:  0.4836758578742755
Confusion Matrix :
 [[3079  968]
 [1123 2924]]
Accuracy on test set:    0.7416604892512972
Sensitivity:    0.722510501606128 	 Specificity:    0.7608104768964665
Precision  : 0.7512846865364851
Area Under Curve:    0.7416604892512972
(8094, 2560) (8094,)
Mean MCC = 0.4367 + 0.0219 and Mean AUC = 0.7181 + 0.0110
Mean Sensitivity = 0.7354 + 0.0135 and Mean Specificity = 0.7008 + 0.0253 and Mean Accuracy = 0.7181 + 0.0110
Mean Precision = 0.7113 + 0.0165





Seed   : 741562
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5840 - accuracy: 0.6866 - val_loss: 0.5587 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5405 - accuracy: 0.7249 - val_loss: 0.5523 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5247 - accuracy: 0.7354 - val_loss: 0.5507 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5137 - accuracy: 0.7446 - val_loss: 0.5534 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7505 - val_loss: 0.5484 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7593 - val_loss: 0.5530 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7671 - val_loss: 0.5589 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4694 - accuracy: 0.7764 - val_loss: 0.5572 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4558 - accuracy: 0.7860 - val_loss: 0.5627 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4419 - accuracy: 0.7927 - val_loss: 0.5597 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4293 - accuracy: 0.8026 - val_loss: 0.5800 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4161 - accuracy: 0.8082 - val_loss: 0.5757 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4030 - accuracy: 0.8185 - val_loss: 0.5787 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 14/400
247/257 [===========================>..] - ETA: 0s - loss: 0.3917 - accuracy: 0.8249
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3925 - accuracy: 0.8241 - val_loss: 0.5877 - val_accuracy: 0.7045 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.400606771747714
Confusion Matrix :
 [[2735 1313]
 [1115 2932]]
Accuracy on test set:    0.7000617665225448
Sensitivity:    0.724487274524339 	 Specificity:    0.6756422924901185
Precision  : 0.6906949352179034
Area Under Curve:    0.7000647835072289
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 8ms/step - loss: 0.5857 - accuracy: 0.6856 - val_loss: 0.5590 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5401 - accuracy: 0.7266 - val_loss: 0.5509 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7351 - val_loss: 0.5489 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7419 - val_loss: 0.5462 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7487 - val_loss: 0.5500 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7561 - val_loss: 0.5540 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4866 - accuracy: 0.7648 - val_loss: 0.5606 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4750 - accuracy: 0.7721
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4758 - accuracy: 0.7717 - val_loss: 0.5574 - val_accuracy: 0.7078 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41649342470104345
Confusion Matrix :
 [[2832 1216]
 [1146 2901]]
Accuracy on test set:    0.7082149474984558
Sensitivity:    0.7168272794662713 	 Specificity:    0.6996047430830039
Precision  : 0.7046393004615011
Area Under Curve:    0.7082160112746375
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5889 - accuracy: 0.6830 - val_loss: 0.5491 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7232 - val_loss: 0.5392 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7329 - val_loss: 0.5376 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7424 - val_loss: 0.5330 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5050 - accuracy: 0.7516 - val_loss: 0.5353 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7595 - val_loss: 0.5372 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7667 - val_loss: 0.5395 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7751 - val_loss: 0.5436 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4556 - accuracy: 0.7845 - val_loss: 0.5472 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4416 - accuracy: 0.7940 - val_loss: 0.5546 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 11/400
252/257 [============================>.] - ETA: 0s - loss: 0.4296 - accuracy: 0.8023
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4297 - accuracy: 0.8021 - val_loss: 0.5633 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 775us/step
Independent Testing Matthews Correlation:  0.4158663454564268
Confusion Matrix :
 [[2805 1242]
 [1123 2925]]
Accuracy on test set:    0.7078443483631871
Sensitivity:    0.7225790513833992 	 Specificity:    0.6931060044477391
Precision  : 0.7019438444924406
Area Under Curve:    0.7078425279155691
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5851 - accuracy: 0.6853 - val_loss: 0.5470 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7218 - val_loss: 0.5375 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7344 - val_loss: 0.5367 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7426 - val_loss: 0.5461 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7512 - val_loss: 0.5386 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7598 - val_loss: 0.5350 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4777 - accuracy: 0.7688
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4779 - accuracy: 0.7684 - val_loss: 0.5432 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 723us/step
Independent Testing Matthews Correlation:  0.4256957632254048
Confusion Matrix :
 [[2692 1355]
 [ 977 3071]]
Accuracy on test set:    0.7119209388511427
Sensitivity:    0.7586462450592886 	 Specificity:    0.6651840869780083
Precision  : 0.6938544961590601
Area Under Curve:    0.7119151660186485
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5910 - accuracy: 0.6806 - val_loss: 0.5546 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7212 - val_loss: 0.5527 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7335 - val_loss: 0.5483 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7415 - val_loss: 0.5453 - val_accuracy: 0.7176 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7515 - val_loss: 0.5449 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7555 - val_loss: 0.5442 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7646 - val_loss: 0.5452 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7736 - val_loss: 0.5506 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4610 - accuracy: 0.7792 - val_loss: 0.5580 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4483 - accuracy: 0.7898
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4483 - accuracy: 0.7898 - val_loss: 0.5570 - val_accuracy: 0.7157 - lr: 0.0010
253/253 [==============================] - 0s 822us/step
Independent Testing Matthews Correlation:  0.41465152607075667
Confusion Matrix :
 [[2884 1163]
 [1206 2841]]
Accuracy on test set:    0.7073140597973808
Sensitivity:    0.7020014825796886 	 Specificity:    0.7126266370150729
Precision  : 0.7095404595404595
Area Under Curve:    0.7073140597973808
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5845 - accuracy: 0.6867 - val_loss: 0.5532 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5415 - accuracy: 0.7247 - val_loss: 0.5502 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5253 - accuracy: 0.7362 - val_loss: 0.5477 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5131 - accuracy: 0.7460 - val_loss: 0.5458 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7534 - val_loss: 0.5472 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7586 - val_loss: 0.5475 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4799 - accuracy: 0.7689
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4797 - accuracy: 0.7691 - val_loss: 0.5505 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 763us/step
Independent Testing Matthews Correlation:  0.4369266962691843
Confusion Matrix :
 [[2874 1173]
 [1106 2941]]
Accuracy on test set:    0.7184334074623178
Sensitivity:    0.7267111440573264 	 Specificity:    0.7101556708673091
Precision  : 0.7148760330578512
Area Under Curve:    0.7184334074623178
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5908 - accuracy: 0.6805 - val_loss: 0.5592 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7211 - val_loss: 0.5458 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7327 - val_loss: 0.5442 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7398 - val_loss: 0.5456 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7484 - val_loss: 0.5452 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7557 - val_loss: 0.5488 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7655 - val_loss: 0.5509 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4694 - accuracy: 0.7742
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4695 - accuracy: 0.7742 - val_loss: 0.5634 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 956us/step
Independent Testing Matthews Correlation:  0.4400842090944269
Confusion Matrix :
 [[2845 1202]
 [1065 2982]]
Accuracy on test set:    0.719915987150976
Sensitivity:    0.7368421052631579 	 Specificity:    0.7029898690387941
Precision  : 0.7127151051625239
Area Under Curve:    0.7199159871509759
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5902 - accuracy: 0.6816 - val_loss: 0.5538 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7219 - val_loss: 0.5425 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7324 - val_loss: 0.5411 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7400 - val_loss: 0.5397 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7504 - val_loss: 0.5409 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7568 - val_loss: 0.5419 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4863 - accuracy: 0.7645 - val_loss: 0.5467 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4752 - accuracy: 0.7719
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4757 - accuracy: 0.7715 - val_loss: 0.5476 - val_accuracy: 0.7142 - lr: 0.0010
253/253 [==============================] - 0s 758us/step
Independent Testing Matthews Correlation:  0.43729476834300524
Confusion Matrix :
 [[2997 1050]
 [1229 2818]]
Accuracy on test set:    0.7184334074623178
Sensitivity:    0.696318260439832 	 Specificity:    0.7405485544848036
Precision  : 0.7285418821096173
Area Under Curve:    0.7184334074623179
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 4ms/step - loss: 0.5906 - accuracy: 0.6817 - val_loss: 0.5461 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7191 - val_loss: 0.5421 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5338 - accuracy: 0.7313 - val_loss: 0.5399 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5222 - accuracy: 0.7376 - val_loss: 0.5410 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7476 - val_loss: 0.5437 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7553 - val_loss: 0.5437 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.7622 - val_loss: 0.5527 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4794 - accuracy: 0.7699 - val_loss: 0.5543 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.7766 - val_loss: 0.5531 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 10/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4564 - accuracy: 0.7858
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4567 - accuracy: 0.7853 - val_loss: 0.5611 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 826us/step
Independent Testing Matthews Correlation:  0.45787053039035436
Confusion Matrix :
 [[2947 1100]
 [1094 2953]]
Accuracy on test set:    0.7289350135903138
Sensitivity:    0.729676303434643 	 Specificity:    0.7281937237459847
Precision  : 0.7285961016530965
Area Under Curve:    0.7289350135903139
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5906 - accuracy: 0.6816 - val_loss: 0.5536 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7185 - val_loss: 0.5457 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7312 - val_loss: 0.5463 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5231 - accuracy: 0.7386 - val_loss: 0.5478 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5121 - accuracy: 0.7457 - val_loss: 0.5508 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5003 - accuracy: 0.7547 - val_loss: 0.5504 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4887 - accuracy: 0.7631
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4886 - accuracy: 0.7628 - val_loss: 0.5531 - val_accuracy: 0.7200 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.49141294503054467
Confusion Matrix :
 [[3073  974]
 [1085 2962]]
Accuracy on test set:    0.7456140350877193
Sensitivity:    0.7319001729676303 	 Specificity:    0.7593278972078082
Precision  : 0.7525406504065041
Area Under Curve:    0.7456140350877193
(8094, 2560) (8094,)
Mean MCC = 0.4337 + 0.0247 and Mean AUC = 0.7167 + 0.0124
Mean Sensitivity = 0.7246 + 0.0166 and Mean Specificity = 0.7087 + 0.0271 and Mean Accuracy = 0.7167 + 0.0124
Mean Precision = 0.7138 + 0.0176





Seed   : 595976
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5864 - accuracy: 0.6860 - val_loss: 0.5646 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7236 - val_loss: 0.5556 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7355 - val_loss: 0.5570 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7417 - val_loss: 0.5545 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5054 - accuracy: 0.7516 - val_loss: 0.5568 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7587 - val_loss: 0.5536 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7654 - val_loss: 0.5617 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7744 - val_loss: 0.5696 - val_accuracy: 0.7017 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4620 - accuracy: 0.7802 - val_loss: 0.5699 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4478 - accuracy: 0.7888 - val_loss: 0.5756 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4373 - accuracy: 0.7972 - val_loss: 0.5771 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 12/400
250/257 [============================>.] - ETA: 0s - loss: 0.4252 - accuracy: 0.8049
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4257 - accuracy: 0.8046 - val_loss: 0.5788 - val_accuracy: 0.7051 - lr: 0.0010
253/253 [==============================] - 0s 701us/step
Independent Testing Matthews Correlation:  0.3888572336133831
Confusion Matrix :
 [[2857 1191]
 [1283 2764]]
Accuracy on test set:    0.694379246448425
Sensitivity:    0.6829750432419076 	 Specificity:    0.7057806324110671
Precision  : 0.6988621997471555
Area Under Curve:    0.6943778378264873
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5850 - accuracy: 0.6860 - val_loss: 0.5555 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5417 - accuracy: 0.7260 - val_loss: 0.5533 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7350 - val_loss: 0.5461 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7444 - val_loss: 0.5564 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7506 - val_loss: 0.5537 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7578 - val_loss: 0.5478 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7665 - val_loss: 0.5536 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7746 - val_loss: 0.5533 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.7839 - val_loss: 0.5607 - val_accuracy: 0.7036 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4483 - accuracy: 0.7886 - val_loss: 0.5891 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 11/400
249/257 [============================>.] - ETA: 0s - loss: 0.4388 - accuracy: 0.7950
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4384 - accuracy: 0.7953 - val_loss: 0.5775 - val_accuracy: 0.7075 - lr: 0.0010
253/253 [==============================] - 0s 976us/step
Independent Testing Matthews Correlation:  0.40666865879176245
Confusion Matrix :
 [[2651 1397]
 [1012 3035]]
Accuracy on test set:    0.7024088943792465
Sensitivity:    0.7499382258463059 	 Specificity:    0.654891304347826
Precision  : 0.6847924187725631
Area Under Curve:    0.702414765097066
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5820 - accuracy: 0.6882 - val_loss: 0.5513 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7241 - val_loss: 0.5468 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.7354 - val_loss: 0.5456 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7430 - val_loss: 0.5455 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7501 - val_loss: 0.5462 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7583 - val_loss: 0.5470 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7657 - val_loss: 0.5527 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4706 - accuracy: 0.7738
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4711 - accuracy: 0.7736 - val_loss: 0.5634 - val_accuracy: 0.7094 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41240696169073165
Confusion Matrix :
 [[3022 1025]
 [1359 2689]]
Accuracy on test set:    0.7054972205064854
Sensitivity:    0.6642786561264822 	 Specificity:    0.746725969854213
Precision  : 0.7240172320947765
Area Under Curve:    0.7055023129903476
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5868 - accuracy: 0.6848 - val_loss: 0.5528 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7227 - val_loss: 0.5456 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5267 - accuracy: 0.7353 - val_loss: 0.5455 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7420 - val_loss: 0.5434 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7521 - val_loss: 0.5492 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7607 - val_loss: 0.5514 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7704 - val_loss: 0.5515 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7743 - val_loss: 0.5571 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4547 - accuracy: 0.7876 - val_loss: 0.5605 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4438 - accuracy: 0.7928
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4438 - accuracy: 0.7928 - val_loss: 0.5708 - val_accuracy: 0.7100 - lr: 0.0010
253/253 [==============================] - 0s 699us/step
Independent Testing Matthews Correlation:  0.41976290293046464
Confusion Matrix :
 [[2741 1306]
 [1046 3002]]
Accuracy on test set:    0.7094502779493514
Sensitivity:    0.741600790513834 	 Specificity:    0.6772918211020509
Precision  : 0.6968430826369545
Area Under Curve:    0.7094463058079424
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5880 - accuracy: 0.6845 - val_loss: 0.5476 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7220 - val_loss: 0.5428 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7345 - val_loss: 0.5424 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7431 - val_loss: 0.5374 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.7516 - val_loss: 0.5383 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7604 - val_loss: 0.5427 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4797 - accuracy: 0.7690 - val_loss: 0.5439 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4671 - accuracy: 0.7778 - val_loss: 0.5508 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4548 - accuracy: 0.7852
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4551 - accuracy: 0.7850 - val_loss: 0.5541 - val_accuracy: 0.7172 - lr: 0.0010
253/253 [==============================] - 0s 770us/step
Independent Testing Matthews Correlation:  0.42243386927464754
Confusion Matrix :
 [[2712 1335]
 [1008 3039]]
Accuracy on test set:    0.7105263157894737
Sensitivity:    0.7509266123054115 	 Specificity:    0.670126019273536
Precision  : 0.6947873799725651
Area Under Curve:    0.7105263157894737
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5867 - accuracy: 0.6847 - val_loss: 0.5538 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7216 - val_loss: 0.5448 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7347 - val_loss: 0.5432 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7425 - val_loss: 0.5450 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7513 - val_loss: 0.5427 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7574 - val_loss: 0.5428 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7651 - val_loss: 0.5470 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.7743 - val_loss: 0.5589 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4586 - accuracy: 0.7829 - val_loss: 0.5509 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4458 - accuracy: 0.7914 - val_loss: 0.5668 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 11/400
254/257 [============================>.] - ETA: 0s - loss: 0.4347 - accuracy: 0.7986
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4347 - accuracy: 0.7985 - val_loss: 0.5654 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4363489124875592
Confusion Matrix :
 [[2789 1258]
 [1026 3021]]
Accuracy on test set:    0.7178156659253768
Sensitivity:    0.7464788732394366 	 Specificity:    0.689152458611317
Precision  : 0.7060060761860247
Area Under Curve:    0.7178156659253767
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5889 - accuracy: 0.6843 - val_loss: 0.5501 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7223 - val_loss: 0.5457 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7333 - val_loss: 0.5548 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7415 - val_loss: 0.5451 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7502 - val_loss: 0.5445 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7608 - val_loss: 0.5437 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7674 - val_loss: 0.5483 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4678 - accuracy: 0.7765 - val_loss: 0.5453 - val_accuracy: 0.7191 - lr: 0.0010

Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4554 - accuracy: 0.7866 - val_loss: 0.5539 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4405 - accuracy: 0.7956 - val_loss: 0.5560 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 11/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4260 - accuracy: 0.8042
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4257 - accuracy: 0.8044 - val_loss: 0.5656 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 763us/step
Independent Testing Matthews Correlation:  0.4294086183568057
Confusion Matrix :
 [[2799 1248]
 [1063 2984]]
Accuracy on test set:    0.7144798616258957
Sensitivity:    0.7373362984927107 	 Specificity:    0.6916234247590808
Precision  : 0.7051039697542533
Area Under Curve:    0.7144798616258957
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5922 - accuracy: 0.6817 - val_loss: 0.5587 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7219 - val_loss: 0.5445 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7338 - val_loss: 0.5407 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7409 - val_loss: 0.5451 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7490 - val_loss: 0.5416 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7568 - val_loss: 0.5427 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4819 - accuracy: 0.7663 - val_loss: 0.5414 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4700 - accuracy: 0.7769 - val_loss: 0.5500 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.7820 - val_loss: 0.5506 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4434 - accuracy: 0.7922
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4437 - accuracy: 0.7919 - val_loss: 0.5559 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 767us/step
Independent Testing Matthews Correlation:  0.4314131338395375
Confusion Matrix :
 [[2830 1217]
 [1085 2962]]
Accuracy on test set:    0.7155917963923895
Sensitivity:    0.7319001729676303 	 Specificity:    0.6992834198171485
Precision  : 0.7087820052644174
Area Under Curve:    0.7155917963923893
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5909 - accuracy: 0.6804 - val_loss: 0.5530 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5486 - accuracy: 0.7207 - val_loss: 0.5490 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5351 - accuracy: 0.7292 - val_loss: 0.5463 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5229 - accuracy: 0.7395 - val_loss: 0.5445 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5129 - accuracy: 0.7464 - val_loss: 0.5463 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5033 - accuracy: 0.7537 - val_loss: 0.5455 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4908 - accuracy: 0.7613 - val_loss: 0.5498 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4793 - accuracy: 0.7710 - val_loss: 0.5502 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4663 - accuracy: 0.7793
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4664 - accuracy: 0.7792 - val_loss: 0.5547 - val_accuracy: 0.7142 - lr: 0.0010
253/253 [==============================] - 0s 973us/step
Independent Testing Matthews Correlation:  0.4695404643761922
Confusion Matrix :
 [[3005 1042]
 [1105 2942]]
Accuracy on test set:    0.7347417840375586
Sensitivity:    0.7269582406721028 	 Specificity:    0.7425253274030146
Precision  : 0.7384538152610441
Area Under Curve:    0.7347417840375587
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.6020 - accuracy: 0.6721 - val_loss: 0.5606 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5558 - accuracy: 0.7164 - val_loss: 0.5568 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5387 - accuracy: 0.7287 - val_loss: 0.5468 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7348 - val_loss: 0.5462 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7436 - val_loss: 0.5463 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7510 - val_loss: 0.5473 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.7581 - val_loss: 0.5546 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7658 - val_loss: 0.5580 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4730 - accuracy: 0.7763 - val_loss: 0.5576 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4632 - accuracy: 0.7833 - val_loss: 0.5607 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4505 - accuracy: 0.7902 - val_loss: 0.5582 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 12/400
252/257 [============================>.] - ETA: 0s - loss: 0.4357 - accuracy: 0.8012
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4358 - accuracy: 0.8012 - val_loss: 0.5660 - val_accuracy: 0.7038 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47491768423474573
Confusion Matrix :
 [[3049  998]
 [1128 2919]]
Accuracy on test set:    0.7373362984927107
Sensitivity:    0.7212750185322461 	 Specificity:    0.7533975784531752
Precision  : 0.7452131733469491
Area Under Curve:    0.7373362984927107
(8094, 2560) (8094,)
Mean MCC = 0.4292 + 0.0252 and Mean AUC = 0.7142 + 0.0127
Mean Sensitivity = 0.7254 + 0.0277 and Mean Specificity = 0.7031 + 0.0323 and Mean Accuracy = 0.7142 + 0.0127
Mean Precision = 0.7103 + 0.0186





Seed   : 177571
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5891 - accuracy: 0.6832 - val_loss: 0.5596 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7252 - val_loss: 0.5567 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7346 - val_loss: 0.5515 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7434 - val_loss: 0.5499 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7496 - val_loss: 0.5514 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7560 - val_loss: 0.5527 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4867 - accuracy: 0.7641 - val_loss: 0.5543 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4775 - accuracy: 0.7707 - val_loss: 0.5581 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4649 - accuracy: 0.7795 - val_loss: 0.5601 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4538 - accuracy: 0.7871 - val_loss: 0.5703 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4412 - accuracy: 0.7923 - val_loss: 0.5780 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4305 - accuracy: 0.7992 - val_loss: 0.5911 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 13/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4172 - accuracy: 0.8081
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4178 - accuracy: 0.8074 - val_loss: 0.5864 - val_accuracy: 0.7112 - lr: 0.0010
253/253 [==============================] - 0s 734us/step
Independent Testing Matthews Correlation:  0.4014958948888876
Confusion Matrix :
 [[2784 1264]
 [1159 2888]]
Accuracy on test set:    0.7006794317479926
Sensitivity:    0.7136150234741784 	 Specificity:    0.6877470355731226
Precision  : 0.6955684007707129
Area Under Curve:    0.7006810295236505
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5877 - accuracy: 0.6850 - val_loss: 0.5644 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7242 - val_loss: 0.5599 - val_accuracy: 0.7021 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5267 - accuracy: 0.7371 - val_loss: 0.5537 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7422 - val_loss: 0.5517 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7488 - val_loss: 0.5524 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7580 - val_loss: 0.5557 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7637 - val_loss: 0.5629 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4746 - accuracy: 0.7724
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7726 - val_loss: 0.5554 - val_accuracy: 0.7087 - lr: 0.0010
253/253 [==============================] - 0s 725us/step
Independent Testing Matthews Correlation:  0.42863965159885975
Confusion Matrix :
 [[2784 1264]
 [1051 2996]]
Accuracy on test set:    0.7140210006176653
Sensitivity:    0.7403014578700272 	 Specificity:    0.6877470355731226
Precision  : 0.7032863849765258
Area Under Curve:    0.7140242467215749
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5886 - accuracy: 0.6844 - val_loss: 0.5562 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7214 - val_loss: 0.5419 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7337 - val_loss: 0.5382 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7398 - val_loss: 0.5494 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7496 - val_loss: 0.5390 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7569 - val_loss: 0.5407 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7660 - val_loss: 0.5545 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4703 - accuracy: 0.7756 - val_loss: 0.5485 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4560 - accuracy: 0.7851 - val_loss: 0.5484 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4447 - accuracy: 0.7928
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4449 - accuracy: 0.7927 - val_loss: 0.5618 - val_accuracy: 0.7170 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.4426679492275397
Confusion Matrix :
 [[2667 1380]
 [ 889 3159]]
Accuracy on test set:    0.719703520691785
Sensitivity:    0.7803853754940712 	 Specificity:    0.6590066716085989
Precision  : 0.6959682749504296
Area Under Curve:    0.7196960235513351
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5852 - accuracy: 0.6849 - val_loss: 0.5481 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7252 - val_loss: 0.5374 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7332 - val_loss: 0.5335 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5142 - accuracy: 0.7441 - val_loss: 0.5339 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7537 - val_loss: 0.5347 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4896 - accuracy: 0.7605 - val_loss: 0.5409 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4766 - accuracy: 0.7716 - val_loss: 0.5383 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4649 - accuracy: 0.7797 - val_loss: 0.5459 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4503 - accuracy: 0.7884 - val_loss: 0.5519 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4391 - accuracy: 0.7976 - val_loss: 0.5499 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4250 - accuracy: 0.8056 - val_loss: 0.5560 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 12/400
249/257 [============================>.] - ETA: 0s - loss: 0.4110 - accuracy: 0.8143
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4114 - accuracy: 0.8143 - val_loss: 0.5626 - val_accuracy: 0.7235 - lr: 0.0010
253/253 [==============================] - 0s 897us/step
Independent Testing Matthews Correlation:  0.405127610346716
Confusion Matrix :
 [[2763 1284]
 [1125 2923]]
Accuracy on test set:    0.7024088943792465
Sensitivity:    0.7220849802371542 	 Specificity:    0.6827279466271312
Precision  : 0.6947943903018778
Area Under Curve:    0.7024064634321427
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5859 - accuracy: 0.6870 - val_loss: 0.5564 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7222 - val_loss: 0.5464 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7326 - val_loss: 0.5450 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7407 - val_loss: 0.5454 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7495 - val_loss: 0.5436 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7549 - val_loss: 0.5551 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4890 - accuracy: 0.7618
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.7612 - val_loss: 0.5509 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43091511152438405
Confusion Matrix :
 [[2712 1335]
 [ 975 3072]]
Accuracy on test set:    0.7146034099332839
Sensitivity:    0.7590808005930318 	 Specificity:    0.670126019273536
Precision  : 0.697072838665759
Area Under Curve:    0.7146034099332839
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5852 - accuracy: 0.6872 - val_loss: 0.5504 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7247 - val_loss: 0.5452 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.7347 - val_loss: 0.5438 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7429 - val_loss: 0.5429 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7512 - val_loss: 0.5481 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7573 - val_loss: 0.5522 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4845 - accuracy: 0.7652
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.7648 - val_loss: 0.5550 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 820us/step
Independent Testing Matthews Correlation:  0.422985971042468
Confusion Matrix :
 [[2588 1459]
 [ 893 3154]]
Accuracy on test set:    0.7094143810229799
Sensitivity:    0.7793427230046949 	 Specificity:    0.6394860390412651
Precision  : 0.6837199219596791
Area Under Curve:    0.70941438102298
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5871 - accuracy: 0.6846 - val_loss: 0.5492 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7241 - val_loss: 0.5434 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7347 - val_loss: 0.5427 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7410 - val_loss: 0.5439 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7494 - val_loss: 0.5417 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7565 - val_loss: 0.5448 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7662 - val_loss: 0.5475 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4736 - accuracy: 0.7733
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7733 - val_loss: 0.5619 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.423184766889337
Confusion Matrix :
 [[2504 1543]
 [ 819 3228]]
Accuracy on test set:    0.708178897949098
Sensitivity:    0.7976278724981468 	 Specificity:    0.6187299234000494
Precision  : 0.6765877174596521
Area Under Curve:    0.7081788979490982
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5952 - accuracy: 0.6767 - val_loss: 0.5516 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7247 - val_loss: 0.5421 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7316 - val_loss: 0.5397 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7415 - val_loss: 0.5413 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7511 - val_loss: 0.5405 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7570 - val_loss: 0.5410 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7648 - val_loss: 0.5448 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7741 - val_loss: 0.5464 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4614 - accuracy: 0.7794 - val_loss: 0.5523 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4481 - accuracy: 0.7906 - val_loss: 0.5554 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4363 - accuracy: 0.7969
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4361 - accuracy: 0.7971 - val_loss: 0.5658 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4289626697562651
Confusion Matrix :
 [[2899 1148]
 [1163 2884]]
Accuracy on test set:    0.7144798616258957
Sensitivity:    0.7126266370150729 	 Specificity:    0.7163330862367185
Precision  : 0.7152777777777778
Area Under Curve:    0.7144798616258957
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5903 - accuracy: 0.6817 - val_loss: 0.5544 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7227 - val_loss: 0.5456 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7308 - val_loss: 0.5498 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5212 - accuracy: 0.7397 - val_loss: 0.5395 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5105 - accuracy: 0.7481 - val_loss: 0.5509 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7560 - val_loss: 0.5439 - val_accuracy: 0.7170 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4889 - accuracy: 0.7635 - val_loss: 0.5480 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7729 - val_loss: 0.5516 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4645 - accuracy: 0.7804
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4644 - accuracy: 0.7801 - val_loss: 0.5585 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4513176001537317
Confusion Matrix :
 [[2890 1157]
 [1064 2983]]
Accuracy on test set:    0.7255992092908328
Sensitivity:    0.7370892018779343 	 Specificity:    0.7141092167037312
Precision  : 0.7205314009661836
Area Under Curve:    0.7255992092908328
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5943 - accuracy: 0.6764 - val_loss: 0.5555 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5503 - accuracy: 0.7192 - val_loss: 0.5514 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5353 - accuracy: 0.7296 - val_loss: 0.5458 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5224 - accuracy: 0.7387 - val_loss: 0.5473 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5124 - accuracy: 0.7472 - val_loss: 0.5493 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5038 - accuracy: 0.7515 - val_loss: 0.5506 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4923 - accuracy: 0.7602 - val_loss: 0.5494 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7687 - val_loss: 0.5551 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7765 - val_loss: 0.5583 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4545 - accuracy: 0.7873 - val_loss: 0.5581 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4426 - accuracy: 0.7931 - val_loss: 0.5658 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4288 - accuracy: 0.8018 - val_loss: 0.5896 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 13/400
255/257 [============================>.] - ETA: 0s - loss: 0.4165 - accuracy: 0.8085
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4166 - accuracy: 0.8085 - val_loss: 0.5782 - val_accuracy: 0.7172 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.46720353866929143
Confusion Matrix :
 [[3124  923]
 [1239 2808]]
Accuracy on test set:    0.7328885594267358
Sensitivity:    0.6938472942920682 	 Specificity:    0.7719298245614035
Precision  : 0.7526132404181185
Area Under Curve:    0.7328885594267357
(8094, 2560) (8094,)
Mean MCC = 0.4303 + 0.0188 and Mean AUC = 0.7142 + 0.0094
Mean Sensitivity = 0.7436 + 0.0326 and Mean Specificity = 0.6848 + 0.0409 and Mean Accuracy = 0.7142 + 0.0094
Mean Precision = 0.7035 + 0.0205





Seed   : 288724
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5827 - accuracy: 0.6882 - val_loss: 0.5590 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5409 - accuracy: 0.7262 - val_loss: 0.5535 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5265 - accuracy: 0.7345 - val_loss: 0.5515 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5149 - accuracy: 0.7433 - val_loss: 0.5550 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5040 - accuracy: 0.7504 - val_loss: 0.5486 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7588 - val_loss: 0.5540 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4811 - accuracy: 0.7671 - val_loss: 0.5548 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4700 - accuracy: 0.7745 - val_loss: 0.5583 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4574 - accuracy: 0.7829
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4577 - accuracy: 0.7825 - val_loss: 0.5568 - val_accuracy: 0.7093 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3997060096949239
Confusion Matrix :
 [[2873 1175]
 [1255 2792]]
Accuracy on test set:    0.6998147004323657
Sensitivity:    0.6898937484556461 	 Specificity:    0.7097332015810277
Precision  : 0.7038064028232922
Area Under Curve:    0.6998134750183368
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5894 - accuracy: 0.6809 - val_loss: 0.5591 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7240 - val_loss: 0.5520 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7330 - val_loss: 0.5535 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7413 - val_loss: 0.5485 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7493 - val_loss: 0.5523 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4980 - accuracy: 0.7552 - val_loss: 0.5551 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4861 - accuracy: 0.7633 - val_loss: 0.5517 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4758 - accuracy: 0.7701 - val_loss: 0.5578 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4658 - accuracy: 0.7786
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4664 - accuracy: 0.7782 - val_loss: 0.5579 - val_accuracy: 0.7113 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42983262149801604
Confusion Matrix :
 [[2751 1297]
 [1015 3032]]
Accuracy on test set:    0.7143915997529339
Sensitivity:    0.7491969360019768 	 Specificity:    0.6795948616600791
Precision  : 0.7003927003927004
Area Under Curve:    0.7143958988310279
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6845 - val_loss: 0.5559 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7235 - val_loss: 0.5465 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7343 - val_loss: 0.5429 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5149 - accuracy: 0.7435 - val_loss: 0.5466 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7504 - val_loss: 0.5455 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4923 - accuracy: 0.7595 - val_loss: 0.5508 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.7695 - val_loss: 0.5511 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4666 - accuracy: 0.7770
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7769 - val_loss: 0.5497 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42739577932432526
Confusion Matrix :
 [[2845 1202]
 [1116 2932]]
Accuracy on test set:    0.7136504014823966
Sensitivity:    0.724308300395257 	 Specificity:    0.7029898690387941
Precision  : 0.7092404450895017
Area Under Curve:    0.7136490847170255
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5920 - accuracy: 0.6793 - val_loss: 0.5557 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7208 - val_loss: 0.5500 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7319 - val_loss: 0.5460 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5209 - accuracy: 0.7387 - val_loss: 0.5450 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5113 - accuracy: 0.7460 - val_loss: 0.5532 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5006 - accuracy: 0.7545 - val_loss: 0.5508 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4899 - accuracy: 0.7632 - val_loss: 0.5482 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.7703 - val_loss: 0.5504 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4662 - accuracy: 0.7774
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.7775 - val_loss: 0.5573 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43033688052057895
Confusion Matrix :
 [[2971 1076]
 [1231 2817]]
Accuracy on test set:    0.7150092649783817
Sensitivity:    0.695899209486166 	 Specificity:    0.7341240425006177
Precision  : 0.7236064731569484
Area Under Curve:    0.7150116259933919
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5891 - accuracy: 0.6839 - val_loss: 0.5575 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7245 - val_loss: 0.5464 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7329 - val_loss: 0.5451 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7434 - val_loss: 0.5464 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5034 - accuracy: 0.7498 - val_loss: 0.5480 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.7594 - val_loss: 0.5528 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - ETA: 0s - loss: 0.4794 - accuracy: 0.7687
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4794 - accuracy: 0.7687 - val_loss: 0.5545 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 846us/step
Independent Testing Matthews Correlation:  0.41743167466016934
Confusion Matrix :
 [[3053  994]
 [1371 2676]]
Accuracy on test set:    0.7078082530269335
Sensitivity:    0.6612305411415864 	 Specificity:    0.7543859649122807
Precision  : 0.7291553133514986
Area Under Curve:    0.7078082530269336
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5876 - accuracy: 0.6855 - val_loss: 0.5560 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7242 - val_loss: 0.5514 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7336 - val_loss: 0.5508 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7416 - val_loss: 0.5508 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7481 - val_loss: 0.5544 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7565 - val_loss: 0.5563 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.7637 - val_loss: 0.5554 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7712 - val_loss: 0.5567 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4621 - accuracy: 0.7794 - val_loss: 0.5660 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4508 - accuracy: 0.7875
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4510 - accuracy: 0.7873 - val_loss: 0.5661 - val_accuracy: 0.7108 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4395542674129763
Confusion Matrix :
 [[2849 1198]
 [1071 2976]]
Accuracy on test set:    0.7196688905361996
Sensitivity:    0.7353595255744997 	 Specificity:    0.7039782554978997
Precision  : 0.7129851461427887
Area Under Curve:    0.7196688905361998
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5860 - accuracy: 0.6857 - val_loss: 0.5521 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7231 - val_loss: 0.5484 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7350 - val_loss: 0.5433 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7425 - val_loss: 0.5440 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5054 - accuracy: 0.7500 - val_loss: 0.5408 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7579 - val_loss: 0.5449 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7670 - val_loss: 0.5453 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4701 - accuracy: 0.7757 - val_loss: 0.5502 - val_accuracy: 0.7263 - lr: 0.0010

Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4579 - accuracy: 0.7825 - val_loss: 0.5611 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4440 - accuracy: 0.7916 - val_loss: 0.5563 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4289 - accuracy: 0.8003
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4292 - accuracy: 0.8002 - val_loss: 0.5624 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 831us/step
Independent Testing Matthews Correlation:  0.4124520129639555
Confusion Matrix :
 [[2781 1266]
 [1113 2934]]
Accuracy on test set:    0.7060785767234989
Sensitivity:    0.7249814677538917 	 Specificity:    0.687175685693106
Precision  : 0.6985714285714286
Area Under Curve:    0.7060785767234988
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5868 - accuracy: 0.6860 - val_loss: 0.5510 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7234 - val_loss: 0.5474 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7342 - val_loss: 0.5418 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7418 - val_loss: 0.5412 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7504 - val_loss: 0.5407 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7611 - val_loss: 0.5468 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7692 - val_loss: 0.5526 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4682 - accuracy: 0.7781
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4682 - accuracy: 0.7781 - val_loss: 0.5544 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.456829396860777
Confusion Matrix :
 [[2785 1262]
 [ 942 3105]]
Accuracy on test set:    0.7276995305164319
Sensitivity:    0.7672349888806523 	 Specificity:    0.6881640721522115
Precision  : 0.7110144263796657
Area Under Curve:    0.727699530516432
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5916 - accuracy: 0.6811 - val_loss: 0.5564 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7215 - val_loss: 0.5498 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7345 - val_loss: 0.5474 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7432 - val_loss: 0.5457 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5043 - accuracy: 0.7514 - val_loss: 0.5485 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7621 - val_loss: 0.5563 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4793 - accuracy: 0.7692 - val_loss: 0.5543 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4654 - accuracy: 0.7790 - val_loss: 0.5572 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4522 - accuracy: 0.7872 - val_loss: 0.5601 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4396 - accuracy: 0.7954 - val_loss: 0.5726 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4239 - accuracy: 0.8041 - val_loss: 0.5748 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 12/400
249/257 [============================>.] - ETA: 0s - loss: 0.4111 - accuracy: 0.8121
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4120 - accuracy: 0.8115 - val_loss: 0.5810 - val_accuracy: 0.7098 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4291867078716317
Confusion Matrix :
 [[3081  966]
 [1352 2695]]
Accuracy on test set:    0.7136150234741784
Sensitivity:    0.6659253768223375 	 Specificity:    0.7613046701260193
Precision  : 0.7361376673040153
Area Under Curve:    0.7136150234741784
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5911 - accuracy: 0.6834 - val_loss: 0.5628 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7210 - val_loss: 0.5484 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7319 - val_loss: 0.5515 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5212 - accuracy: 0.7406 - val_loss: 0.5475 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5102 - accuracy: 0.7471 - val_loss: 0.5494 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4989 - accuracy: 0.7562 - val_loss: 0.5543 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4876 - accuracy: 0.7646
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7645 - val_loss: 0.5546 - val_accuracy: 0.7105 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.48486231110846795
Confusion Matrix :
 [[2973 1074]
 [1011 3036]]
Accuracy on test set:    0.7424017790956264
Sensitivity:    0.7501853224610823 	 Specificity:    0.7346182357301705
Precision  : 0.7386861313868613
Area Under Curve:    0.7424017790956264
(8094, 2560) (8094,)
Mean MCC = 0.4328 + 0.0227 and Mean AUC = 0.7160 + 0.0114
Mean Sensitivity = 0.7164 + 0.0347 and Mean Specificity = 0.7156 + 0.0274 and Mean Accuracy = 0.7160 + 0.0114
Mean Precision = 0.7164 + 0.0139





Seed   : 990807
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5859 - accuracy: 0.6865 - val_loss: 0.5590 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7242 - val_loss: 0.5555 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7345 - val_loss: 0.5504 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7433 - val_loss: 0.5546 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7504 - val_loss: 0.5533 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7581 - val_loss: 0.5736 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4836 - accuracy: 0.7673 - val_loss: 0.5568 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4717 - accuracy: 0.7741
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7741 - val_loss: 0.5586 - val_accuracy: 0.7083 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39874568966120993
Confusion Matrix :
 [[2648 1400]
 [1040 3007]]
Accuracy on test set:    0.6985793699814701
Sensitivity:    0.7430195206325674 	 Specificity:    0.6541501976284585
Precision  : 0.6823235761288858
Area Under Curve:    0.698584859130513
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5897 - accuracy: 0.6821 - val_loss: 0.5622 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7239 - val_loss: 0.5502 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7353 - val_loss: 0.5508 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7421 - val_loss: 0.5556 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7500 - val_loss: 0.5493 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7595 - val_loss: 0.5559 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7663 - val_loss: 0.5520 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 8/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4709 - accuracy: 0.7758
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7753 - val_loss: 0.5536 - val_accuracy: 0.7060 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4202143802856144
Confusion Matrix :
 [[2747 1301]
 [1049 2998]]
Accuracy on test set:    0.7096973440395306
Sensitivity:    0.7407956510995799 	 Specificity:    0.678606719367589
Precision  : 0.6973714817399396
Area Under Curve:    0.7097011852335844
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5870 - accuracy: 0.6854 - val_loss: 0.5494 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7248 - val_loss: 0.5426 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7350 - val_loss: 0.5378 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5154 - accuracy: 0.7451 - val_loss: 0.5358 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7513 - val_loss: 0.5360 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7602 - val_loss: 0.5371 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7691 - val_loss: 0.5400 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4679 - accuracy: 0.7779 - val_loss: 0.5509 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4556 - accuracy: 0.7857
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4557 - accuracy: 0.7852 - val_loss: 0.5513 - val_accuracy: 0.7234 - lr: 0.0010
253/253 [==============================] - 0s 784us/step
Independent Testing Matthews Correlation:  0.4162726077645916
Confusion Matrix :
 [[3024 1023]
 [1345 2703]]
Accuracy on test set:    0.7074737492279185
Sensitivity:    0.6677371541501976 	 Specificity:    0.7472201630837657
Precision  : 0.7254428341384863
Area Under Curve:    0.7074786586169818
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5924 - accuracy: 0.6790 - val_loss: 0.5545 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7227 - val_loss: 0.5439 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7317 - val_loss: 0.5383 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5206 - accuracy: 0.7397 - val_loss: 0.5380 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5119 - accuracy: 0.7467 - val_loss: 0.5364 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5015 - accuracy: 0.7547 - val_loss: 0.5432 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7614 - val_loss: 0.5437 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7685 - val_loss: 0.5433 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4707 - accuracy: 0.7757
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4700 - accuracy: 0.7761 - val_loss: 0.5533 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.420424176234696
Confusion Matrix :
 [[2902 1145]
 [1201 2847]]
Accuracy on test set:    0.7101914762198889
Sensitivity:    0.7033102766798419 	 Specificity:    0.7170743760810477
Precision  : 0.7131763527054108
Area Under Curve:    0.7101923263804447
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5848 - accuracy: 0.6867 - val_loss: 0.5589 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7232 - val_loss: 0.5545 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7305 - val_loss: 0.5427 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5210 - accuracy: 0.7396 - val_loss: 0.5447 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.7444 - val_loss: 0.5439 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7515 - val_loss: 0.5427 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7587 - val_loss: 0.5451 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4822 - accuracy: 0.7685
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7685 - val_loss: 0.5470 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 741us/step
Independent Testing Matthews Correlation:  0.43197973051881206
Confusion Matrix :
 [[2674 1373]
 [ 936 3111]]
Accuracy on test set:    0.7147269582406721
Sensitivity:    0.7687175685693106 	 Specificity:    0.6607363479120336
Precision  : 0.693800178412132
Area Under Curve:    0.7147269582406721
(8094, 2560) (8094,)
Epoch 1/400

257/257 [==============================] - 2s 4ms/step - loss: 0.5975 - accuracy: 0.6771 - val_loss: 0.5595 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5516 - accuracy: 0.7180 - val_loss: 0.5492 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5342 - accuracy: 0.7308 - val_loss: 0.5455 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5237 - accuracy: 0.7389 - val_loss: 0.5448 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5094 - accuracy: 0.7473 - val_loss: 0.5456 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7578 - val_loss: 0.5516 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4824 - accuracy: 0.7682
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.7683 - val_loss: 0.5539 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 815us/step
Independent Testing Matthews Correlation:  0.43070208915851643
Confusion Matrix :
 [[2662 1385]
 [ 930 3117]]
Accuracy on test set:    0.7139856683963429
Sensitivity:    0.7702001482579689 	 Specificity:    0.657771188534717
Precision  : 0.6923589515770768
Area Under Curve:    0.713985668396343
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5880 - accuracy: 0.6837 - val_loss: 0.5537 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7221 - val_loss: 0.5470 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7342 - val_loss: 0.5414 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7433 - val_loss: 0.5441 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7502 - val_loss: 0.5420 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.7601 - val_loss: 0.5437 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4797 - accuracy: 0.7692 - val_loss: 0.5483 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4666 - accuracy: 0.7777
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.7778 - val_loss: 0.5496 - val_accuracy: 0.7209 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4297018526551174
Confusion Matrix :
 [[2897 1150]
 [1158 2889]]
Accuracy on test set:    0.7148505065480603
Sensitivity:    0.7138621200889548 	 Specificity:    0.7158388930071659
Precision  : 0.7152760584303045
Area Under Curve:    0.7148505065480603
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5924 - accuracy: 0.6817 - val_loss: 0.5508 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7242 - val_loss: 0.5484 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7340 - val_loss: 0.5406 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7403 - val_loss: 0.5387 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7501 - val_loss: 0.5387 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7584 - val_loss: 0.5420 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7663 - val_loss: 0.5421 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4732 - accuracy: 0.7759 - val_loss: 0.5465 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4604 - accuracy: 0.7842 - val_loss: 0.5477 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4479 - accuracy: 0.7918 - val_loss: 0.5563 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4346 - accuracy: 0.7994 - val_loss: 0.5669 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4219 - accuracy: 0.8069 - val_loss: 0.5657 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4122 - accuracy: 0.8138 - val_loss: 0.5761 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3964 - accuracy: 0.8212 - val_loss: 0.5903 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 15/400
248/257 [===========================>..] - ETA: 0s - loss: 0.3870 - accuracy: 0.8285
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3875 - accuracy: 0.8279 - val_loss: 0.5898 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 753us/step
Independent Testing Matthews Correlation:  0.41942668384228615
Confusion Matrix :
 [[2827 1220]
 [1130 2917]]
Accuracy on test set:    0.7096614776377563
Sensitivity:    0.7207808253026934 	 Specificity:    0.6985421299728194
Precision  : 0.7051003142373701
Area Under Curve:    0.7096614776377563
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5955 - accuracy: 0.6771 - val_loss: 0.5544 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5496 - accuracy: 0.7197 - val_loss: 0.5476 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5345 - accuracy: 0.7306 - val_loss: 0.5445 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5235 - accuracy: 0.7402 - val_loss: 0.5452 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5105 - accuracy: 0.7471 - val_loss: 0.5429 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7569 - val_loss: 0.5460 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7654 - val_loss: 0.5465 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4716 - accuracy: 0.7750 - val_loss: 0.5502 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4575 - accuracy: 0.7843 - val_loss: 0.5558 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4432 - accuracy: 0.7933 - val_loss: 0.5610 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4287 - accuracy: 0.8008 - val_loss: 0.5686 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4165 - accuracy: 0.8079 - val_loss: 0.5826 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 13/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4043 - accuracy: 0.8150
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4046 - accuracy: 0.8146 - val_loss: 0.5854 - val_accuracy: 0.7120 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4528262731482429
Confusion Matrix :
 [[3046 1001]
 [1216 2831]]
Accuracy on test set:    0.7260934025203855
Sensitivity:    0.6995305164319249 	 Specificity:    0.752656288608846
Precision  : 0.7387787056367432
Area Under Curve:    0.7260934025203855
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5940 - accuracy: 0.6798 - val_loss: 0.5534 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5510 - accuracy: 0.7212 - val_loss: 0.5474 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5377 - accuracy: 0.7292 - val_loss: 0.5401 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5249 - accuracy: 0.7392 - val_loss: 0.5429 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5149 - accuracy: 0.7464 - val_loss: 0.5402 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7547 - val_loss: 0.5431 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4899 - accuracy: 0.7642 - val_loss: 0.5443 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4774 - accuracy: 0.7713
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4779 - accuracy: 0.7710 - val_loss: 0.5449 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47690397040052684
Confusion Matrix :
 [[3132  915]
 [1207 2840]]
Accuracy on test set:    0.7378304917222634
Sensitivity:    0.7017543859649122 	 Specificity:    0.7739065974796145
Precision  : 0.7563249001331558
Area Under Curve:    0.7378304917222634
(8094, 2560) (8094,)
Mean MCC = 0.4297 + 0.0205 and Mean AUC = 0.7143 + 0.0102
Mean Sensitivity = 0.7230 + 0.0309 and Mean Specificity = 0.7057 + 0.0407 and Mean Accuracy = 0.7143 + 0.0102
Mean Precision = 0.7120 + 0.0218





Seed   : 15324
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5868 - accuracy: 0.6848 - val_loss: 0.5631 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7251 - val_loss: 0.5618 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7344 - val_loss: 0.5540 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7418 - val_loss: 0.5551 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7489 - val_loss: 0.5532 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7574 - val_loss: 0.5589 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.7634 - val_loss: 0.5601 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4762 - accuracy: 0.7724 - val_loss: 0.5593 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4631 - accuracy: 0.7819 - val_loss: 0.5669 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4516 - accuracy: 0.7887 - val_loss: 0.5675 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4390 - accuracy: 0.7980 - val_loss: 0.5730 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 12/400
253/257 [============================>.] - ETA: 0s - loss: 0.4277 - accuracy: 0.8037
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4281 - accuracy: 0.8034 - val_loss: 0.5902 - val_accuracy: 0.7053 - lr: 0.0010
253/253 [==============================] - 0s 877us/step
Independent Testing Matthews Correlation:  0.37996576261331777
Confusion Matrix :
 [[2510 1538]
 [ 986 3061]]
Accuracy on test set:    0.6882025941939469
Sensitivity:    0.7563627378304917 	 Specificity:    0.6200592885375494
Precision  : 0.6655794737986519
Area Under Curve:    0.6882110131840204
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5887 - accuracy: 0.6825 - val_loss: 0.5658 - val_accuracy: 0.7019 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7218 - val_loss: 0.5564 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7327 - val_loss: 0.5530 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7416 - val_loss: 0.5543 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7493 - val_loss: 0.5601 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7565 - val_loss: 0.5578 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7659 - val_loss: 0.5612 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.7728 - val_loss: 0.5700 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.7810 - val_loss: 0.5700 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4483 - accuracy: 0.7879
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4483 - accuracy: 0.7880 - val_loss: 0.5756 - val_accuracy: 0.7072 - lr: 0.0010
253/253 [==============================] - 0s 754us/step
Independent Testing Matthews Correlation:  0.4056825308316676
Confusion Matrix :
 [[2956 1092]
 [1316 2731]]
Accuracy on test set:    0.702532427424336
Sensitivity:    0.6748208549542871 	 Specificity:    0.7302371541501976
Precision  : 0.7143604499084488
Area Under Curve:    0.7025290045522424
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.6830 - val_loss: 0.5538 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7222 - val_loss: 0.5472 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7321 - val_loss: 0.5390 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7410 - val_loss: 0.5401 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7491 - val_loss: 0.5380 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7586 - val_loss: 0.5406 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 7/400

257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7646 - val_loss: 0.5427 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7730 - val_loss: 0.5447 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4572 - accuracy: 0.7847 - val_loss: 0.5497 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4451 - accuracy: 0.7911 - val_loss: 0.5562 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4331 - accuracy: 0.7986 - val_loss: 0.5671 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 12/400
249/257 [============================>.] - ETA: 0s - loss: 0.4176 - accuracy: 0.8071
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4177 - accuracy: 0.8071 - val_loss: 0.5609 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 713us/step
Independent Testing Matthews Correlation:  0.4112580172468108
Confusion Matrix :
 [[2837 1210]
 [1173 2875]]
Accuracy on test set:    0.705620753551575
Sensitivity:    0.7102272727272727 	 Specificity:    0.7010130961205832
Precision  : 0.7037943696450428
Area Under Curve:    0.7056201844239279
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5839 - accuracy: 0.6874 - val_loss: 0.5520 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7238 - val_loss: 0.5434 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7330 - val_loss: 0.5407 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7405 - val_loss: 0.5408 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7478 - val_loss: 0.5433 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7555 - val_loss: 0.5418 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7643 - val_loss: 0.5464 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4726 - accuracy: 0.7733
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4731 - accuracy: 0.7728 - val_loss: 0.5503 - val_accuracy: 0.7220 - lr: 0.0010
253/253 [==============================] - 0s 784us/step
Independent Testing Matthews Correlation:  0.4234893887673737
Confusion Matrix :
 [[2932 1115]
 [1219 2829]]
Accuracy on test set:    0.7116738727609636
Sensitivity:    0.6988636363636364 	 Specificity:    0.724487274524339
Precision  : 0.717292089249493
Area Under Curve:    0.7116754554439876
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5912 - accuracy: 0.6808 - val_loss: 0.5557 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7203 - val_loss: 0.5475 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5336 - accuracy: 0.7304 - val_loss: 0.5460 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7383 - val_loss: 0.5497 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5115 - accuracy: 0.7447 - val_loss: 0.5453 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.7545 - val_loss: 0.5548 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7603 - val_loss: 0.5489 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4801 - accuracy: 0.7697 - val_loss: 0.5560 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4680 - accuracy: 0.7784 - val_loss: 0.5637 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4586 - accuracy: 0.7845
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4586 - accuracy: 0.7846 - val_loss: 0.5629 - val_accuracy: 0.7112 - lr: 0.0010
253/253 [==============================] - 0s 984us/step
Independent Testing Matthews Correlation:  0.4440847336204628
Confusion Matrix :
 [[2891 1156]
 [1094 2953]]
Accuracy on test set:    0.7220163083765753
Sensitivity:    0.729676303434643 	 Specificity:    0.7143563133185076
Precision  : 0.7186663421757119
Area Under Curve:    0.7220163083765753
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5871 - accuracy: 0.6856 - val_loss: 0.5569 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7232 - val_loss: 0.5463 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7325 - val_loss: 0.5421 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7411 - val_loss: 0.5404 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7491 - val_loss: 0.5431 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7573 - val_loss: 0.5479 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4844 - accuracy: 0.7660
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.7656 - val_loss: 0.5461 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 899us/step
Independent Testing Matthews Correlation:  0.43503602631042737
Confusion Matrix :
 [[2817 1230]
 [1058 2989]]
Accuracy on test set:    0.717321472695824
Sensitivity:    0.7385717815665925 	 Specificity:    0.6960711638250556
Precision  : 0.7084617207869164
Area Under Curve:    0.7173214726958241
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5886 - accuracy: 0.6827 - val_loss: 0.5563 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7215 - val_loss: 0.5486 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7322 - val_loss: 0.5467 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7397 - val_loss: 0.5415 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.7458 - val_loss: 0.5412 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4985 - accuracy: 0.7543 - val_loss: 0.5405 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.7636 - val_loss: 0.5460 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.7717 - val_loss: 0.5487 - val_accuracy: 0.7174 - lr: 0.0010

Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7805 - val_loss: 0.5508 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 10/400
256/257 [============================>.] - ETA: 0s - loss: 0.4500 - accuracy: 0.7892
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4500 - accuracy: 0.7892 - val_loss: 0.5559 - val_accuracy: 0.7157 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4297547547947862
Confusion Matrix :
 [[2861 1186]
 [1122 2925]]
Accuracy on test set:    0.7148505065480603
Sensitivity:    0.7227575982209044 	 Specificity:    0.7069434148752162
Precision  : 0.7115057163707127
Area Under Curve:    0.7148505065480604
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5859 - accuracy: 0.6864 - val_loss: 0.5509 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7229 - val_loss: 0.5440 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7341 - val_loss: 0.5457 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7410 - val_loss: 0.5415 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7499 - val_loss: 0.5442 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7564 - val_loss: 0.5437 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4866 - accuracy: 0.7656 - val_loss: 0.5455 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4743 - accuracy: 0.7726 - val_loss: 0.5494 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4614 - accuracy: 0.7813
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4616 - accuracy: 0.7813 - val_loss: 0.5549 - val_accuracy: 0.7137 - lr: 0.0010
253/253 [==============================] - 0s 734us/step
Independent Testing Matthews Correlation:  0.4449794739410974
Confusion Matrix :
 [[2862 1185]
 [1062 2985]]
Accuracy on test set:    0.7223869532987398
Sensitivity:    0.737583395107487 	 Specificity:    0.7071905114899926
Precision  : 0.7158273381294964
Area Under Curve:    0.7223869532987398
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5885 - accuracy: 0.6834 - val_loss: 0.5529 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7228 - val_loss: 0.5458 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7340 - val_loss: 0.5476 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7409 - val_loss: 0.5442 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7492 - val_loss: 0.5455 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.7562 - val_loss: 0.5472 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4892 - accuracy: 0.7641 - val_loss: 0.5494 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.7713 - val_loss: 0.5485 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.7795 - val_loss: 0.5509 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4545 - accuracy: 0.7875
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4545 - accuracy: 0.7876 - val_loss: 0.5670 - val_accuracy: 0.7083 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4228701577458337
Confusion Matrix :
 [[3194  853]
 [1505 2542]]
Accuracy on test set:    0.7086730911786508
Sensitivity:    0.6281195947615518 	 Specificity:    0.7892265875957499
Precision  : 0.7487481590574374
Area Under Curve:    0.7086730911786508
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5916 - accuracy: 0.6814 - val_loss: 0.5595 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5493 - accuracy: 0.7195 - val_loss: 0.5530 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5332 - accuracy: 0.7296 - val_loss: 0.5509 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7380 - val_loss: 0.5498 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5108 - accuracy: 0.7476 - val_loss: 0.5552 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4991 - accuracy: 0.7558 - val_loss: 0.5596 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 7/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4868 - accuracy: 0.7658
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.7652 - val_loss: 0.5542 - val_accuracy: 0.7102 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4838652363639663
Confusion Matrix :
 [[3133  914]
 [1179 2868]]
Accuracy on test set:    0.7414133926365208
Sensitivity:    0.7086730911786508 	 Specificity:    0.7741536940943909
Precision  : 0.7583289264939186
Area Under Curve:    0.741413392636521
(8094, 2560) (8094,)
Mean MCC = 0.4281 + 0.0262 and Mean AUC = 0.7135 + 0.0134
Mean Sensitivity = 0.7106 + 0.0351 and Mean Specificity = 0.7164 + 0.0436 and Mean Accuracy = 0.7135 + 0.0134
Mean Precision = 0.7163 + 0.0238





Seed   : 503146
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5869 - accuracy: 0.6839 - val_loss: 0.5560 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7240 - val_loss: 0.5521 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7327 - val_loss: 0.5470 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7409 - val_loss: 0.5487 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7498 - val_loss: 0.5498 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7579 - val_loss: 0.5511 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4854 - accuracy: 0.7647 - val_loss: 0.5606 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.7735 - val_loss: 0.5541 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4623 - accuracy: 0.7802 - val_loss: 0.5576 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4512 - accuracy: 0.7873 - val_loss: 0.5673 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4383 - accuracy: 0.7960 - val_loss: 0.5664 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 12/400
254/257 [============================>.] - ETA: 0s - loss: 0.4258 - accuracy: 0.8037
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4258 - accuracy: 0.8037 - val_loss: 0.5735 - val_accuracy: 0.7109 - lr: 0.0010
253/253 [==============================] - 0s 783us/step
Independent Testing Matthews Correlation:  0.40415698907914044
Confusion Matrix :
 [[2802 1246]
 [1166 2881]]
Accuracy on test set:    0.7020382952439778
Sensitivity:    0.7118853471707438 	 Specificity:    0.692193675889328
Precision  : 0.698085776593167
Area Under Curve:    0.702039511530036
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5865 - accuracy: 0.6868 - val_loss: 0.5596 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7236 - val_loss: 0.5537 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7344 - val_loss: 0.5474 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7434 - val_loss: 0.5460 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7507 - val_loss: 0.5519 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7583 - val_loss: 0.5507 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7660 - val_loss: 0.5564 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7743 - val_loss: 0.5561 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4610 - accuracy: 0.7809 - val_loss: 0.5658 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4473 - accuracy: 0.7903 - val_loss: 0.5708 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4346 - accuracy: 0.7997
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4352 - accuracy: 0.7991 - val_loss: 0.5638 - val_accuracy: 0.7078 - lr: 0.0010
253/253 [==============================] - 0s 850us/step
Independent Testing Matthews Correlation:  0.4112496050088871
Confusion Matrix :
 [[3026 1022]
 [1367 2680]]
Accuracy on test set:    0.7048795552810376
Sensitivity:    0.6622189276006919 	 Specificity:    0.7475296442687747
Precision  : 0.7239330091842248
Area Under Curve:    0.7048742859347333
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5856 - accuracy: 0.6848 - val_loss: 0.5522 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7231 - val_loss: 0.5437 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7350 - val_loss: 0.5411 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7431 - val_loss: 0.5414 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7493 - val_loss: 0.5429 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7595 - val_loss: 0.5427 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4817 - accuracy: 0.7676 - val_loss: 0.5437 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7762 - val_loss: 0.5488 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4563 - accuracy: 0.7838 - val_loss: 0.5523 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4431 - accuracy: 0.7914 - val_loss: 0.5612 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4311 - accuracy: 0.7989 - val_loss: 0.5629 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 12/400
256/257 [============================>.] - ETA: 0s - loss: 0.4184 - accuracy: 0.8062
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4184 - accuracy: 0.8063 - val_loss: 0.5698 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4118190574592197
Confusion Matrix :
 [[2748 1299]
 [1084 2964]]
Accuracy on test set:    0.705620753551575
Sensitivity:    0.7322134387351779 	 Specificity:    0.6790214974054856
Precision  : 0.6952850105559465
Area Under Curve:    0.7056174680703317
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5872 - accuracy: 0.6844 - val_loss: 0.5485 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7234 - val_loss: 0.5401 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7324 - val_loss: 0.5380 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7425 - val_loss: 0.5424 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7509 - val_loss: 0.5385 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7579 - val_loss: 0.5429 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7674 - val_loss: 0.5409 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4714 - accuracy: 0.7729 - val_loss: 0.5494 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.7821 - val_loss: 0.5491 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4475 - accuracy: 0.7901 - val_loss: 0.5542 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4347 - accuracy: 0.7992 - val_loss: 0.5576 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 12/400
252/257 [============================>.] - ETA: 0s - loss: 0.4245 - accuracy: 0.8039
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4246 - accuracy: 0.8039 - val_loss: 0.5658 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 764us/step
Independent Testing Matthews Correlation:  0.4204513961925184
Confusion Matrix :
 [[2768 1279]
 [1069 2979]]
Accuracy on test set:    0.7099444101297097
Sensitivity:    0.7359189723320159 	 Specificity:    0.6839634297010131
Precision  : 0.6996242367308596
Area Under Curve:    0.7099412010165145
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5911 - accuracy: 0.6808 - val_loss: 0.5449 - val_accuracy: 0.7267 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5486 - accuracy: 0.7188 - val_loss: 0.5356 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7326 - val_loss: 0.5345 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5224 - accuracy: 0.7382 - val_loss: 0.5395 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7458 - val_loss: 0.5325 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.7526 - val_loss: 0.5348 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7603 - val_loss: 0.5477 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7671 - val_loss: 0.5402 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4709 - accuracy: 0.7759
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4708 - accuracy: 0.7759 - val_loss: 0.5425 - val_accuracy: 0.7246 - lr: 0.0010
253/253 [==============================] - 0s 826us/step
Independent Testing Matthews Correlation:  0.42922664753405976
Confusion Matrix :
 [[2792 1255]
 [1057 2990]]
Accuracy on test set:    0.7143563133185076
Sensitivity:    0.7388188781813689 	 Specificity:    0.6898937484556461
Precision  : 0.7043580683156655
Area Under Curve:    0.7143563133185077
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5889 - accuracy: 0.6842 - val_loss: 0.5436 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7226 - val_loss: 0.5339 - val_accuracy: 0.7344 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7337 - val_loss: 0.5318 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7438 - val_loss: 0.5313 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7499 - val_loss: 0.5350 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7595 - val_loss: 0.5361 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
251/257 [============================>.] - ETA: 0s - loss: 0.4799 - accuracy: 0.7680
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7679 - val_loss: 0.5401 - val_accuracy: 0.7267 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43306135398370377
Confusion Matrix :
 [[3044 1003]
 [1296 2751]]
Accuracy on test set:    0.715962441314554
Sensitivity:    0.6797627872498146 	 Specificity:    0.7521620953792933
Precision  : 0.7328183271177411
Area Under Curve:    0.715962441314554
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5905 - accuracy: 0.6808 - val_loss: 0.5469 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7204 - val_loss: 0.5476 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7336 - val_loss: 0.5322 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7402 - val_loss: 0.5323 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7490 - val_loss: 0.5317 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7572 - val_loss: 0.5348 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7662 - val_loss: 0.5366 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4691 - accuracy: 0.7741
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4693 - accuracy: 0.7741 - val_loss: 0.5391 - val_accuracy: 0.7235 - lr: 0.0010
253/253 [==============================] - 0s 788us/step
Independent Testing Matthews Correlation:  0.4235242312728716
Confusion Matrix :
 [[2884 1163]
 [1170 2877]]
Accuracy on test set:    0.7117617988633556
Sensitivity:    0.7108969607116382 	 Specificity:    0.7126266370150729
Precision  : 0.7121287128712871
Area Under Curve:    0.7117617988633556
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5908 - accuracy: 0.6810 - val_loss: 0.5458 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5477 - accuracy: 0.7202 - val_loss: 0.5353 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7312 - val_loss: 0.5326 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7418 - val_loss: 0.5314 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7487 - val_loss: 0.5319 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7565 - val_loss: 0.5363 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7673 - val_loss: 0.5325 - val_accuracy: 0.7311 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7738 - val_loss: 0.5355 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4580 - accuracy: 0.7836 - val_loss: 0.5346 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4421 - accuracy: 0.7922 - val_loss: 0.5443 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4305 - accuracy: 0.7986 - val_loss: 0.5445 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 12/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4197 - accuracy: 0.8065
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4197 - accuracy: 0.8065 - val_loss: 0.5522 - val_accuracy: 0.7270 - lr: 0.0010
253/253 [==============================] - 0s 992us/step
Independent Testing Matthews Correlation:  0.4309792456861208
Confusion Matrix :
 [[2867 1180]
 [1123 2924]]
Accuracy on test set:    0.7154682480850012
Sensitivity:    0.722510501606128 	 Specificity:    0.7084259945638745
Precision  : 0.7124756335282652
Area Under Curve:    0.7154682480850012
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5899 - accuracy: 0.6834 - val_loss: 0.5495 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7214 - val_loss: 0.5380 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7308 - val_loss: 0.5384 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7416 - val_loss: 0.5347 - val_accuracy: 0.7248 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7489 - val_loss: 0.5429 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7578 - val_loss: 0.5375 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4825 - accuracy: 0.7678
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7676 - val_loss: 0.5384 - val_accuracy: 0.7241 - lr: 0.0010
253/253 [==============================] - 1s 3ms/step
Independent Testing Matthews Correlation:  0.4518553526074385
Confusion Matrix :
 [[3119  928]
 [1298 2749]]
Accuracy on test set:    0.7249814677538917
Sensitivity:    0.679268594020262 	 Specificity:    0.7706943414875216
Precision  : 0.7476203426706555
Area Under Curve:    0.7249814677538917
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5944 - accuracy: 0.6772 - val_loss: 0.5484 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5493 - accuracy: 0.7198 - val_loss: 0.5399 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5339 - accuracy: 0.7305 - val_loss: 0.5391 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5219 - accuracy: 0.7396 - val_loss: 0.5368 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7482 - val_loss: 0.5348 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7568 - val_loss: 0.5360 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4854 - accuracy: 0.7651 - val_loss: 0.5353 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.7759 - val_loss: 0.5404 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4620 - accuracy: 0.7809 - val_loss: 0.5421 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4479 - accuracy: 0.7908 - val_loss: 0.5518 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4372 - accuracy: 0.7973 - val_loss: 0.5689 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4261 - accuracy: 0.8033
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4260 - accuracy: 0.8034 - val_loss: 0.5616 - val_accuracy: 0.7256 - lr: 0.0010
253/253 [==============================] - 0s 808us/step
Independent Testing Matthews Correlation:  0.45642496783251446
Confusion Matrix :
 [[3190  857]
 [1357 2690]]
Accuracy on test set:    0.72646404744255
Sensitivity:    0.6646898937484557 	 Specificity:    0.7882382011366444
Precision  : 0.7583873696081196
Area Under Curve:    0.7264640474425501
(8094, 2560) (8094,)
Mean MCC = 0.4273 + 0.0161 and Mean AUC = 0.7131 + 0.0077
Mean Sensitivity = 0.7038 + 0.0282 and Mean Specificity = 0.7225 + 0.0372 and Mean Accuracy = 0.7131 + 0.0077
Mean Precision = 0.7185 + 0.0206





Seed   : 278913
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5874 - accuracy: 0.6854 - val_loss: 0.5705 - val_accuracy: 0.7032 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7233 - val_loss: 0.5485 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7347 - val_loss: 0.5526 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7428 - val_loss: 0.5471 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7499 - val_loss: 0.5491 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7575 - val_loss: 0.5538 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7663 - val_loss: 0.5533 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7738 - val_loss: 0.5632 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 9/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4571 - accuracy: 0.7838
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4576 - accuracy: 0.7837 - val_loss: 0.5684 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41615961031173454
Confusion Matrix :
 [[2667 1381]
 [ 990 3057]]
Accuracy on test set:    0.7071031500926498
Sensitivity:    0.7553743513713862 	 Specificity:    0.6588438735177866
Precision  : 0.6888237945020279
Area Under Curve:    0.7071091124445864
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5877 - accuracy: 0.6856 - val_loss: 0.5570 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7224 - val_loss: 0.5479 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7326 - val_loss: 0.5458 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7426 - val_loss: 0.5467 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7498 - val_loss: 0.5557 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7579 - val_loss: 0.5500 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.7675 - val_loss: 0.5522 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4695 - accuracy: 0.7754 - val_loss: 0.5562 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4551 - accuracy: 0.7845
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4551 - accuracy: 0.7845 - val_loss: 0.5635 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 823us/step
Independent Testing Matthews Correlation:  0.43099113256756116
Confusion Matrix :
 [[2700 1348]
 [ 963 3084]]
Accuracy on test set:    0.7145151327980235
Sensitivity:    0.7620459599703484 	 Specificity:    0.6669960474308301
Precision  : 0.6958483754512635
Area Under Curve:    0.7145210037005894
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5843 - accuracy: 0.6873 - val_loss: 0.5451 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7234 - val_loss: 0.5450 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7333 - val_loss: 0.5356 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7428 - val_loss: 0.5372 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7520 - val_loss: 0.5363 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7581 - val_loss: 0.5369 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7672 - val_loss: 0.5433 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4695 - accuracy: 0.7749 - val_loss: 0.5397 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4584 - accuracy: 0.7822 - val_loss: 0.5501 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4468 - accuracy: 0.7895 - val_loss: 0.5505 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4345 - accuracy: 0.7969 - val_loss: 0.5531 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4210 - accuracy: 0.8050 - val_loss: 0.5553 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 13/400
249/257 [============================>.] - ETA: 0s - loss: 0.4104 - accuracy: 0.8113
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4102 - accuracy: 0.8112 - val_loss: 0.5650 - val_accuracy: 0.7238 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4219410706725066
Confusion Matrix :
 [[2915 1132]
 [1208 2840]]
Accuracy on test set:    0.7109326744904262
Sensitivity:    0.7015810276679841 	 Specificity:    0.7202866320731406
Precision  : 0.7150050352467271
Area Under Curve:    0.7109338298705624
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5878 - accuracy: 0.6852 - val_loss: 0.5461 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7200 - val_loss: 0.5368 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7309 - val_loss: 0.5365 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7405 - val_loss: 0.5366 - val_accuracy: 0.7311 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7498 - val_loss: 0.5387 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7572 - val_loss: 0.5390 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.7645 - val_loss: 0.5451 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7732 - val_loss: 0.5470 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4612 - accuracy: 0.7815
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4618 - accuracy: 0.7810 - val_loss: 0.5475 - val_accuracy: 0.7281 - lr: 0.0010
253/253 [==============================] - 0s 891us/step
Independent Testing Matthews Correlation:  0.4243886135782735
Confusion Matrix :
 [[2680 1367]
 [ 971 3077]]
Accuracy on test set:    0.7111797405806053
Sensitivity:    0.7601284584980237 	 Specificity:    0.6622189276006919
Precision  : 0.6923942394239424
Area Under Curve:    0.7111736930493577
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5860 - accuracy: 0.6864 - val_loss: 0.5446 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7239 - val_loss: 0.5389 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7353 - val_loss: 0.5380 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5142 - accuracy: 0.7425 - val_loss: 0.5364 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7540 - val_loss: 0.5362 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7593 - val_loss: 0.5416 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7723 - val_loss: 0.5415 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4647 - accuracy: 0.7795 - val_loss: 0.5446 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4520 - accuracy: 0.7866
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4521 - accuracy: 0.7863 - val_loss: 0.5535 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41651778524803995
Confusion Matrix :
 [[3029 1018]
 [1349 2698]]
Accuracy on test set:    0.7075611564121571
Sensitivity:    0.6666666666666666 	 Specificity:    0.7484556461576476
Precision  : 0.7260495156081809
Area Under Curve:    0.7075611564121571
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5884 - accuracy: 0.6836 - val_loss: 0.5496 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7236 - val_loss: 0.5410 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7318 - val_loss: 0.5394 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7405 - val_loss: 0.5398 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7489 - val_loss: 0.5421 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7539 - val_loss: 0.5427 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4902 - accuracy: 0.7603 - val_loss: 0.5430 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4793 - accuracy: 0.7708
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7702 - val_loss: 0.5418 - val_accuracy: 0.7229 - lr: 0.0010
253/253 [==============================] - 0s 992us/step
Independent Testing Matthews Correlation:  0.41932300648050497
Confusion Matrix :
 [[2871 1176]
 [1174 2873]]
Accuracy on test set:    0.7096614776377563
Sensitivity:    0.7099085742525327 	 Specificity:    0.7094143810229799
Precision  : 0.7095579155346999
Area Under Curve:    0.7096614776377563
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5901 - accuracy: 0.6818 - val_loss: 0.5509 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7211 - val_loss: 0.5487 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7323 - val_loss: 0.5398 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7405 - val_loss: 0.5402 - val_accuracy: 0.7246 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7497 - val_loss: 0.5437 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7568 - val_loss: 0.5454 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4848 - accuracy: 0.7659 - val_loss: 0.5527 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7730 - val_loss: 0.5501 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4577 - accuracy: 0.7832
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4577 - accuracy: 0.7832 - val_loss: 0.5584 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 856us/step
Independent Testing Matthews Correlation:  0.4281100135815911
Confusion Matrix :
 [[2838 1209]
 [1106 2941]]
Accuracy on test set:    0.7139856683963429
Sensitivity:    0.7267111440573264 	 Specificity:    0.7012601927353596
Precision  : 0.7086746987951807
Area Under Curve:    0.7139856683963429
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5867 - accuracy: 0.6848 - val_loss: 0.5519 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7238 - val_loss: 0.5426 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7338 - val_loss: 0.5379 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7404 - val_loss: 0.5367 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7504 - val_loss: 0.5383 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7577 - val_loss: 0.5440 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7676 - val_loss: 0.5427 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7749 - val_loss: 0.5445 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4578 - accuracy: 0.7833 - val_loss: 0.5486 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4460 - accuracy: 0.7904
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4463 - accuracy: 0.7904 - val_loss: 0.5514 - val_accuracy: 0.7245 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41908047726359926
Confusion Matrix :
 [[2881 1166]
 [1185 2862]]
Accuracy on test set:    0.7095379293303682
Sensitivity:    0.7071905114899926 	 Specificity:    0.7118853471707438
Precision  : 0.7105263157894737
Area Under Curve:    0.7095379293303682
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5903 - accuracy: 0.6818 - val_loss: 0.5522 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7223 - val_loss: 0.5527 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7308 - val_loss: 0.5545 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7418 - val_loss: 0.5419 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7506 - val_loss: 0.5425 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7601 - val_loss: 0.5557 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7679 - val_loss: 0.5487 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7770 - val_loss: 0.5510 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4564 - accuracy: 0.7846 - val_loss: 0.5533 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4452 - accuracy: 0.7915
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4458 - accuracy: 0.7911 - val_loss: 0.5586 - val_accuracy: 0.7226 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.45325846568394257
Confusion Matrix :
 [[3061  986]
 [1230 2817]]
Accuracy on test set:    0.7262169508277737
Sensitivity:    0.6960711638250556 	 Specificity:    0.7563627378304917
Precision  : 0.7407310018406521
Area Under Curve:    0.7262169508277737
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5916 - accuracy: 0.6807 - val_loss: 0.5572 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7209 - val_loss: 0.5512 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7311 - val_loss: 0.5515 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5236 - accuracy: 0.7366 - val_loss: 0.5472 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5128 - accuracy: 0.7451 - val_loss: 0.5511 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7540 - val_loss: 0.5493 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7619 - val_loss: 0.5567 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7669 - val_loss: 0.5517 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4718 - accuracy: 0.7762
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4718 - accuracy: 0.7762 - val_loss: 0.5561 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 775us/step
Independent Testing Matthews Correlation:  0.4844543395293073
Confusion Matrix :
 [[3053  994]
 [1093 2954]]
Accuracy on test set:    0.74215468248085
Sensitivity:    0.7299234000494194 	 Specificity:    0.7543859649122807
Precision  : 0.74822695035461
Area Under Curve:    0.74215468248085
(8094, 2560) (8094,)
Mean MCC = 0.4314 + 0.0205 and Mean AUC = 0.7153 + 0.0103
Mean Sensitivity = 0.7216 + 0.0296 and Mean Specificity = 0.7090 + 0.0354 and Mean Accuracy = 0.7153 + 0.0103
Mean Precision = 0.7136 + 0.0188





Seed   : 388166
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5890 - accuracy: 0.6818 - val_loss: 0.5561 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7250 - val_loss: 0.5480 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7350 - val_loss: 0.5477 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7435 - val_loss: 0.5444 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7509 - val_loss: 0.5491 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7587 - val_loss: 0.5467 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.7655 - val_loss: 0.5462 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4727 - accuracy: 0.7742 - val_loss: 0.5484 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4605 - accuracy: 0.7829 - val_loss: 0.5586 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4472 - accuracy: 0.7910 - val_loss: 0.5595 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4347 - accuracy: 0.8008 - val_loss: 0.5679 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4224 - accuracy: 0.8063 - val_loss: 0.5662 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4099 - accuracy: 0.8153 - val_loss: 0.5660 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3959 - accuracy: 0.8227 - val_loss: 0.5859 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 15/400
249/257 [============================>.] - ETA: 0s - loss: 0.3870 - accuracy: 0.8291
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3872 - accuracy: 0.8290 - val_loss: 0.5884 - val_accuracy: 0.7087 - lr: 0.0010
253/253 [==============================] - 0s 882us/step
Independent Testing Matthews Correlation:  0.38407086122193573
Confusion Matrix :
 [[2790 1258]
 [1235 2812]]
Accuracy on test set:    0.6920321185917233
Sensitivity:    0.6948356807511737 	 Specificity:    0.6892292490118577
Precision  : 0.6909090909090909
Area Under Curve:    0.6920324648815157
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5851 - accuracy: 0.6873 - val_loss: 0.5542 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7234 - val_loss: 0.5478 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5253 - accuracy: 0.7348 - val_loss: 0.5451 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5140 - accuracy: 0.7432 - val_loss: 0.5436 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7499 - val_loss: 0.5673 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7569 - val_loss: 0.5551 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 7/400
252/257 [============================>.] - ETA: 0s - loss: 0.4808 - accuracy: 0.7670
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4811 - accuracy: 0.7668 - val_loss: 0.5560 - val_accuracy: 0.7065 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4006981376252725
Confusion Matrix :
 [[2669 1379]
 [1052 2995]]
Accuracy on test set:    0.6996911673872761
Sensitivity:    0.7400543612552508 	 Specificity:    0.6593379446640316
Precision  : 0.6847279378143576
Area Under Curve:    0.6996961529596413
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5895 - accuracy: 0.6825 - val_loss: 0.5529 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7218 - val_loss: 0.5422 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7322 - val_loss: 0.5371 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7407 - val_loss: 0.5398 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7465 - val_loss: 0.5362 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7554 - val_loss: 0.5421 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4896 - accuracy: 0.7632 - val_loss: 0.5515 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4756 - accuracy: 0.7719 - val_loss: 0.5444 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4638 - accuracy: 0.7788 - val_loss: 0.5477 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4504 - accuracy: 0.7879 - val_loss: 0.5521 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 11/400
249/257 [============================>.] - ETA: 0s - loss: 0.4387 - accuracy: 0.7946
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4388 - accuracy: 0.7945 - val_loss: 0.5632 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 740us/step
Independent Testing Matthews Correlation:  0.4239703438197236
Confusion Matrix :
 [[2795 1252]
 [1081 2967]]
Accuracy on test set:    0.7117974058060531
Sensitivity:    0.7329545454545454 	 Specificity:    0.6906350382999753
Precision  : 0.7032472149798531
Area Under Curve:    0.7117947918772604
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5953 - accuracy: 0.6789 - val_loss: 0.5503 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.7227 - val_loss: 0.5467 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5328 - accuracy: 0.7321 - val_loss: 0.5373 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7421 - val_loss: 0.5387 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7469 - val_loss: 0.5387 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5008 - accuracy: 0.7554 - val_loss: 0.5448 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7625 - val_loss: 0.5422 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4785 - accuracy: 0.7698
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4783 - accuracy: 0.7700 - val_loss: 0.5551 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 728us/step
Independent Testing Matthews Correlation:  0.4304323449020879
Confusion Matrix :
 [[2644 1403]
 [ 915 3133]]
Accuracy on test set:    0.7136504014823966
Sensitivity:    0.7739624505928854 	 Specificity:    0.6533234494687423
Precision  : 0.6906966490299824
Area Under Curve:    0.7136429500308138
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5890 - accuracy: 0.6817 - val_loss: 0.5568 - val_accuracy: 0.7123 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7238 - val_loss: 0.5493 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7325 - val_loss: 0.5455 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7416 - val_loss: 0.5484 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7482 - val_loss: 0.5507 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7554 - val_loss: 0.5524 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4871 - accuracy: 0.7630 - val_loss: 0.5543 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4768 - accuracy: 0.7703
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.7702 - val_loss: 0.5502 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 848us/step
Independent Testing Matthews Correlation:  0.41669253630856207
Confusion Matrix :
 [[2908 1139]
 [1222 2825]]
Accuracy on test set:    0.7083024462564863
Sensitivity:    0.6980479367432666 	 Specificity:    0.7185569557697059
Precision  : 0.7126639757820383
Area Under Curve:    0.7083024462564863
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5883 - accuracy: 0.6842 - val_loss: 0.5578 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7231 - val_loss: 0.5507 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7344 - val_loss: 0.5485 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7430 - val_loss: 0.5474 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5040 - accuracy: 0.7522 - val_loss: 0.5518 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7615 - val_loss: 0.5549 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7696 - val_loss: 0.5530 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4660 - accuracy: 0.7785 - val_loss: 0.5579 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4504 - accuracy: 0.7872 - val_loss: 0.5618 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4384 - accuracy: 0.7956 - val_loss: 0.5695 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4231 - accuracy: 0.8049 - val_loss: 0.5826 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 12/400
254/257 [============================>.] - ETA: 0s - loss: 0.4125 - accuracy: 0.8104
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4124 - accuracy: 0.8105 - val_loss: 0.5822 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 747us/step
Independent Testing Matthews Correlation:  0.4220606163073824
Confusion Matrix :
 [[2858 1189]
 [1150 2897]]
Accuracy on test set:    0.7110205090190265
Sensitivity:    0.7158388930071659 	 Specificity:    0.7062021250308871
Precision  : 0.7090063631913852
Area Under Curve:    0.7110205090190265
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5891 - accuracy: 0.6826 - val_loss: 0.5547 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7211 - val_loss: 0.5431 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7339 - val_loss: 0.5443 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7393 - val_loss: 0.5430 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7498 - val_loss: 0.5436 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7553 - val_loss: 0.5425 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7670 - val_loss: 0.5462 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7743 - val_loss: 0.5518 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4579 - accuracy: 0.7824
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4580 - accuracy: 0.7823 - val_loss: 0.5564 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 987us/step
Independent Testing Matthews Correlation:  0.422809621432283
Confusion Matrix :
 [[2856 1191]
 [1145 2902]]
Accuracy on test set:    0.711391153941191
Sensitivity:    0.7170743760810477 	 Specificity:    0.7057079318013343
Precision  : 0.7090153921329099
Area Under Curve:    0.7113911539411911
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5908 - accuracy: 0.6817 - val_loss: 0.5530 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5488 - accuracy: 0.7193 - val_loss: 0.5435 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5330 - accuracy: 0.7308 - val_loss: 0.5406 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5229 - accuracy: 0.7366 - val_loss: 0.5406 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.7434 - val_loss: 0.5428 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.7516 - val_loss: 0.5405 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.7595 - val_loss: 0.5407 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7678 - val_loss: 0.5467 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7761 - val_loss: 0.5438 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4585 - accuracy: 0.7834 - val_loss: 0.5521 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4472 - accuracy: 0.7914 - val_loss: 0.5545 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4366 - accuracy: 0.7976 - val_loss: 0.5605 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4251 - accuracy: 0.8043 - val_loss: 0.5635 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 14/400
249/257 [============================>.] - ETA: 0s - loss: 0.4118 - accuracy: 0.8138
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4124 - accuracy: 0.8133 - val_loss: 0.5688 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4388980687833799
Confusion Matrix :
 [[2836 1211]
 [1061 2986]]
Accuracy on test set:    0.7192982456140351
Sensitivity:    0.7378304917222634 	 Specificity:    0.7007659995058068
Precision  : 0.7114605670717179
Area Under Curve:    0.7192982456140351
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5905 - accuracy: 0.6831 - val_loss: 0.5509 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5486 - accuracy: 0.7212 - val_loss: 0.5510 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5339 - accuracy: 0.7301 - val_loss: 0.5436 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5229 - accuracy: 0.7372 - val_loss: 0.5406 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5131 - accuracy: 0.7453 - val_loss: 0.5417 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7538 - val_loss: 0.5471 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.7619 - val_loss: 0.5498 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7689 - val_loss: 0.5476 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4672 - accuracy: 0.7783 - val_loss: 0.5670 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4562 - accuracy: 0.7840 - val_loss: 0.5638 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4429 - accuracy: 0.7922
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4427 - accuracy: 0.7923 - val_loss: 0.5740 - val_accuracy: 0.7241 - lr: 0.0010
253/253 [==============================] - 0s 737us/step
Independent Testing Matthews Correlation:  0.4675065770254324
Confusion Matrix :
 [[2820 1227]
 [ 933 3114]]
Accuracy on test set:    0.7331356560415122
Sensitivity:    0.7694588584136397 	 Specificity:    0.6968124536693847
Precision  : 0.7173462335867312
Area Under Curve:    0.7331356560415122
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5933 - accuracy: 0.6780 - val_loss: 0.5567 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5496 - accuracy: 0.7191 - val_loss: 0.5505 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5350 - accuracy: 0.7306 - val_loss: 0.5447 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5236 - accuracy: 0.7375 - val_loss: 0.5459 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5138 - accuracy: 0.7445 - val_loss: 0.5459 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7522 - val_loss: 0.5441 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7600 - val_loss: 0.5458 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7666 - val_loss: 0.5495 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4716 - accuracy: 0.7768 - val_loss: 0.5575 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 10/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4592 - accuracy: 0.7825
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.7822 - val_loss: 0.5577 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.48321262919350966
Confusion Matrix :
 [[3151  896]
 [1201 2846]]
Accuracy on test set:    0.7409191994069682
Sensitivity:    0.7032369656535705 	 Specificity:    0.7786014331603657
Precision  : 0.760555852485302
Area Under Curve:    0.740919199406968
(8094, 2560) (8094,)
Mean MCC = 0.4290 + 0.0276 and Mean AUC = 0.7141 + 0.0136
Mean Sensitivity = 0.7283 + 0.0264 and Mean Specificity = 0.6999 + 0.0326 and Mean Accuracy = 0.7141 + 0.0136
Mean Precision = 0.7090 + 0.0201





Seed   : 675938
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5849 - accuracy: 0.6861 - val_loss: 0.5656 - val_accuracy: 0.7014 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5406 - accuracy: 0.7263 - val_loss: 0.5538 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5249 - accuracy: 0.7365 - val_loss: 0.5606 - val_accuracy: 0.7028 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5118 - accuracy: 0.7455 - val_loss: 0.5566 - val_accuracy: 0.7030 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7531 - val_loss: 0.5572 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.7609 - val_loss: 0.5675 - val_accuracy: 0.7039 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7692 - val_loss: 0.5687 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7788 - val_loss: 0.5690 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4545 - accuracy: 0.7849 - val_loss: 0.5686 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4439 - accuracy: 0.7910
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4440 - accuracy: 0.7908 - val_loss: 0.5779 - val_accuracy: 0.7034 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41085469271399966
Confusion Matrix :
 [[2675 1373]
 [1018 3029]]
Accuracy on test set:    0.7046324891908585
Sensitivity:    0.7484556461576476 	 Specificity:    0.6608201581027668
Precision  : 0.6880963198546115
Area Under Curve:    0.7046379021302073
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5897 - accuracy: 0.6831 - val_loss: 0.5614 - val_accuracy: 0.7014 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7230 - val_loss: 0.5539 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7358 - val_loss: 0.5524 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7430 - val_loss: 0.5543 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7494 - val_loss: 0.5554 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7578 - val_loss: 0.5538 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.7631 - val_loss: 0.5595 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4767 - accuracy: 0.7708 - val_loss: 0.5606 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4641 - accuracy: 0.7800 - val_loss: 0.5639 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4536 - accuracy: 0.7843 - val_loss: 0.5730 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 11/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4411 - accuracy: 0.7961
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4420 - accuracy: 0.7950 - val_loss: 0.5708 - val_accuracy: 0.7115 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39797336667680194
Confusion Matrix :
 [[2791 1257]
 [1180 2867]]
Accuracy on test set:    0.6989499691167387
Sensitivity:    0.7084259945638745 	 Specificity:    0.6894762845849802
Precision  : 0.6951988360814743
Area Under Curve:    0.6989511395744273
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5860 - accuracy: 0.6848 - val_loss: 0.5525 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7239 - val_loss: 0.5507 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7358 - val_loss: 0.5390 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5146 - accuracy: 0.7431 - val_loss: 0.5381 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7521 - val_loss: 0.5384 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7599 - val_loss: 0.5450 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7674 - val_loss: 0.5533 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4675 - accuracy: 0.7747
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.7748 - val_loss: 0.5475 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 767us/step
Independent Testing Matthews Correlation:  0.42759749005979053
Confusion Matrix :
 [[2919 1128]
 [1189 2859]]
Accuracy on test set:    0.713773934527486
Sensitivity:    0.7062747035573123 	 Specificity:    0.7212750185322461
Precision  : 0.7170805116629044
Area Under Curve:    0.7137748610447792
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5861 - accuracy: 0.6839 - val_loss: 0.5463 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7236 - val_loss: 0.5506 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7349 - val_loss: 0.5373 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7429 - val_loss: 0.5368 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7513 - val_loss: 0.5402 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7598 - val_loss: 0.5436 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7699 - val_loss: 0.5448 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4689 - accuracy: 0.7755 - val_loss: 0.5522 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4568 - accuracy: 0.7836
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4573 - accuracy: 0.7831 - val_loss: 0.5555 - val_accuracy: 0.7244 - lr: 0.0010
253/253 [==============================] - 0s 736us/step
Independent Testing Matthews Correlation:  0.42197466558792057
Confusion Matrix :
 [[2793 1254]
 [1087 2961]]
Accuracy on test set:    0.7108091414453366
Sensitivity:    0.7314723320158103 	 Specificity:    0.6901408450704225
Precision  : 0.702491103202847
Area Under Curve:    0.7108065885431164
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5886 - accuracy: 0.6820 - val_loss: 0.5572 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7227 - val_loss: 0.5565 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7328 - val_loss: 0.5512 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7397 - val_loss: 0.5528 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7485 - val_loss: 0.5561 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7560 - val_loss: 0.5579 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7650 - val_loss: 0.5565 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4752 - accuracy: 0.7723 - val_loss: 0.5630 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4643 - accuracy: 0.7785
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4643 - accuracy: 0.7785 - val_loss: 0.5671 - val_accuracy: 0.7112 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43481916133064746
Confusion Matrix :
 [[2753 1294]
 [ 998 3049]]
Accuracy on test set:    0.7168272794662713
Sensitivity:    0.7533975784531752 	 Specificity:    0.6802569804793674
Precision  : 0.7020492746949113
Area Under Curve:    0.7168272794662713
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5859 - accuracy: 0.6879 - val_loss: 0.5546 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7241 - val_loss: 0.5499 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7340 - val_loss: 0.5485 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7405 - val_loss: 0.5462 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7486 - val_loss: 0.5488 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7560 - val_loss: 0.5585 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 3ms/step - loss: 0.4862 - accuracy: 0.7635 - val_loss: 0.5512 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7728 - val_loss: 0.5576 - val_accuracy: 0.7187 - lr: 0.0010

Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4603 - accuracy: 0.7816
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4602 - accuracy: 0.7812 - val_loss: 0.5699 - val_accuracy: 0.7139 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4080970224727247
Confusion Matrix :
 [[3039 1008]
 [1395 2652]]
Accuracy on test set:    0.7031134173461824
Sensitivity:    0.6553002223869533 	 Specificity:    0.7509266123054115
Precision  : 0.7245901639344262
Area Under Curve:    0.7031134173461825
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5866 - accuracy: 0.6859 - val_loss: 0.5533 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7238 - val_loss: 0.5480 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7310 - val_loss: 0.5444 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7399 - val_loss: 0.5492 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.7475 - val_loss: 0.5485 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4989 - accuracy: 0.7557 - val_loss: 0.5525 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7632 - val_loss: 0.5498 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4765 - accuracy: 0.7719 - val_loss: 0.5552 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.7798 - val_loss: 0.5652 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4530 - accuracy: 0.7871 - val_loss: 0.5641 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4402 - accuracy: 0.7961
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4401 - accuracy: 0.7963 - val_loss: 0.5681 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.417574705149082
Confusion Matrix :
 [[2748 1299]
 [1061 2986]]
Accuracy on test set:    0.7084259945638745
Sensitivity:    0.7378304917222634 	 Specificity:    0.6790214974054856
Precision  : 0.6968494749124854
Area Under Curve:    0.7084259945638746
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5860 - accuracy: 0.6852 - val_loss: 0.5515 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7247 - val_loss: 0.5428 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7356 - val_loss: 0.5519 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7433 - val_loss: 0.5575 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5040 - accuracy: 0.7524 - val_loss: 0.5443 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7601 - val_loss: 0.5451 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4792 - accuracy: 0.7696 - val_loss: 0.5476 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7796 - val_loss: 0.5494 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4546 - accuracy: 0.7870 - val_loss: 0.5520 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4407 - accuracy: 0.7950 - val_loss: 0.5552 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4286 - accuracy: 0.8018 - val_loss: 0.5576 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4139 - accuracy: 0.8118 - val_loss: 0.5752 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4019 - accuracy: 0.8187 - val_loss: 0.5773 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 14/400
246/257 [===========================>..] - ETA: 0s - loss: 0.3875 - accuracy: 0.8253
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3877 - accuracy: 0.8248 - val_loss: 0.5906 - val_accuracy: 0.7127 - lr: 0.0010
253/253 [==============================] - 0s 794us/step
Independent Testing Matthews Correlation:  0.43100973226381967
Confusion Matrix :
 [[2817 1230]
 [1074 2973]]
Accuracy on test set:    0.7153446997776131
Sensitivity:    0.7346182357301705 	 Specificity:    0.6960711638250556
Precision  : 0.7073518915060671
Area Under Curve:    0.7153446997776131
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5914 - accuracy: 0.6814 - val_loss: 0.5587 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7207 - val_loss: 0.5485 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7329 - val_loss: 0.5531 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7416 - val_loss: 0.5512 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7500 - val_loss: 0.5542 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7581 - val_loss: 0.5509 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7674 - val_loss: 0.5526 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7751 - val_loss: 0.5577 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4577 - accuracy: 0.7840 - val_loss: 0.5617 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4436 - accuracy: 0.7927 - val_loss: 0.5822 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4335 - accuracy: 0.7974 - val_loss: 0.5817 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 12/400
253/257 [============================>.] - ETA: 0s - loss: 0.4198 - accuracy: 0.8055
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4199 - accuracy: 0.8055 - val_loss: 0.5785 - val_accuracy: 0.7115 - lr: 0.0010
253/253 [==============================] - 0s 960us/step
Independent Testing Matthews Correlation:  0.45957540253856555
Confusion Matrix :
 [[2890 1157]
 [1031 3016]]
Accuracy on test set:    0.729676303434643
Sensitivity:    0.7452433901655547 	 Specificity:    0.7141092167037312
Precision  : 0.7227414330218068
Area Under Curve:    0.729676303434643
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5941 - accuracy: 0.6786 - val_loss: 0.5543 - val_accuracy: 0.7168 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5498 - accuracy: 0.7211 - val_loss: 0.5527 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7300 - val_loss: 0.5509 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7399 - val_loss: 0.5488 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7477 - val_loss: 0.5525 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7557 - val_loss: 0.5569 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7651 - val_loss: 0.5612 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4743 - accuracy: 0.7733 - val_loss: 0.5587 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4609 - accuracy: 0.7822 - val_loss: 0.5615 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4498 - accuracy: 0.7890 - val_loss: 0.5674 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4377 - accuracy: 0.7949 - val_loss: 0.5741 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4234 - accuracy: 0.8034 - val_loss: 0.5759 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - ETA: 0s - loss: 0.4104 - accuracy: 0.8112
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4104 - accuracy: 0.8112 - val_loss: 0.5886 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 805us/step
Independent Testing Matthews Correlation:  0.4719548944233421
Confusion Matrix :
 [[2981 1066]
 [1071 2976]]
Accuracy on test set:    0.7359772671114406
Sensitivity:    0.7353595255744997 	 Specificity:    0.7365950086483816
Precision  : 0.7362691736763978
Area Under Curve:    0.7359772671114406
(8094, 2560) (8094,)
Mean MCC = 0.4281 + 0.0217 and Mean AUC = 0.7138 + 0.0110
Mean Sensitivity = 0.7256 + 0.0277 and Mean Specificity = 0.7019 + 0.0267 and Mean Accuracy = 0.7138 + 0.0110
Mean Precision = 0.7093 + 0.0145





Seed   : 984258
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5855 - accuracy: 0.6870 - val_loss: 0.5685 - val_accuracy: 0.6991 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5418 - accuracy: 0.7250 - val_loss: 0.5593 - val_accuracy: 0.7031 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.7356 - val_loss: 0.5571 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5154 - accuracy: 0.7442 - val_loss: 0.5612 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7511 - val_loss: 0.5588 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7592 - val_loss: 0.5737 - val_accuracy: 0.7027 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7661 - val_loss: 0.5637 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7710 - val_loss: 0.5665 - val_accuracy: 0.7031 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4626 - accuracy: 0.7800 - val_loss: 0.5704 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4507 - accuracy: 0.7887 - val_loss: 0.5725 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4386 - accuracy: 0.7965 - val_loss: 0.5786 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4262 - accuracy: 0.8052 - val_loss: 0.5754 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4173 - accuracy: 0.8087 - val_loss: 0.5888 - val_accuracy: 0.7040 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4041 - accuracy: 0.8178 - val_loss: 0.5919 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3936 - accuracy: 0.8230 - val_loss: 0.6144 - val_accuracy: 0.7039 - lr: 0.0010
Epoch 16/400
250/257 [============================>.] - ETA: 0s - loss: 0.3838 - accuracy: 0.8280
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3842 - accuracy: 0.8278 - val_loss: 0.6118 - val_accuracy: 0.7073 - lr: 0.0010
253/253 [==============================] - 0s 870us/step
Independent Testing Matthews Correlation:  0.3827113219403867
Confusion Matrix :
 [[2547 1501]
 [1009 3038]]
Accuracy on test set:    0.6899320568252008
Sensitivity:    0.7506795156906351 	 Specificity:    0.629199604743083
Precision  : 0.6693104207975324
Area Under Curve:    0.689939560216859
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5821 - accuracy: 0.6890 - val_loss: 0.5707 - val_accuracy: 0.6916 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7247 - val_loss: 0.5610 - val_accuracy: 0.7021 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5267 - accuracy: 0.7351 - val_loss: 0.5582 - val_accuracy: 0.7043 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7437 - val_loss: 0.5537 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7517 - val_loss: 0.5616 - val_accuracy: 0.7049 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7573 - val_loss: 0.5564 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4841 - accuracy: 0.7649 - val_loss: 0.5629 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7725 - val_loss: 0.5632 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4629 - accuracy: 0.7820 - val_loss: 0.5664 - val_accuracy: 0.7054 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4512 - accuracy: 0.7882 - val_loss: 0.5682 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4380 - accuracy: 0.7951 - val_loss: 0.5790 - val_accuracy: 0.7058 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4248 - accuracy: 0.8060 - val_loss: 0.5805 - val_accuracy: 0.7034 - lr: 0.0010
Epoch 13/400
256/257 [============================>.] - ETA: 0s - loss: 0.4110 - accuracy: 0.8125
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4110 - accuracy: 0.8125 - val_loss: 0.5951 - val_accuracy: 0.7056 - lr: 0.0010
253/253 [==============================] - 0s 905us/step
Independent Testing Matthews Correlation:  0.41121166078648824
Confusion Matrix :
 [[2952 1096]
 [1289 2758]]
Accuracy on test set:    0.705373687461396
Sensitivity:    0.6814924635532493 	 Specificity:    0.7292490118577075
Precision  : 0.7156201349247535
Area Under Curve:    0.7053707377054784
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5952 - accuracy: 0.6759 - val_loss: 0.5584 - val_accuracy: 0.7054 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7192 - val_loss: 0.5493 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5332 - accuracy: 0.7309 - val_loss: 0.5454 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5211 - accuracy: 0.7392 - val_loss: 0.5445 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.7475 - val_loss: 0.5454 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7544 - val_loss: 0.5426 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7618 - val_loss: 0.5437 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4765 - accuracy: 0.7702 - val_loss: 0.5483 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4648 - accuracy: 0.7799 - val_loss: 0.5487 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4521 - accuracy: 0.7873 - val_loss: 0.5557 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4404 - accuracy: 0.7946 - val_loss: 0.5625 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4279 - accuracy: 0.8006 - val_loss: 0.5654 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4166 - accuracy: 0.8091 - val_loss: 0.5799 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4076 - accuracy: 0.8141 - val_loss: 0.5790 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3936 - accuracy: 0.8208 - val_loss: 0.5894 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3854 - accuracy: 0.8275 - val_loss: 0.5972 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 17/400
244/257 [===========================>..] - ETA: 0s - loss: 0.3724 - accuracy: 0.8342
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3738 - accuracy: 0.8334 - val_loss: 0.5973 - val_accuracy: 0.7071 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.39180521611665436
Confusion Matrix :
 [[2683 1364]
 [1101 2947]]
Accuracy on test set:    0.695491043854231
Sensitivity:    0.7280138339920948 	 Specificity:    0.662960217445021
Precision  : 0.6836000927858965
Area Under Curve:    0.6954870257185578
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5888 - accuracy: 0.6826 - val_loss: 0.5499 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7238 - val_loss: 0.5452 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7357 - val_loss: 0.5443 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7447 - val_loss: 0.5404 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5020 - accuracy: 0.7538 - val_loss: 0.5392 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7605 - val_loss: 0.5428 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4784 - accuracy: 0.7690 - val_loss: 0.5489 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4651 - accuracy: 0.7771 - val_loss: 0.5475 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4538 - accuracy: 0.7838
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4538 - accuracy: 0.7839 - val_loss: 0.5575 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 750us/step
Independent Testing Matthews Correlation:  0.4180990500036135
Confusion Matrix :
 [[2685 1362]
 [1000 3048]]
Accuracy on test set:    0.7082149474984558
Sensitivity:    0.7529644268774703 	 Specificity:    0.6634544106745738
Precision  : 0.691156462585034
Area Under Curve:    0.708209418776022
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5908 - accuracy: 0.6801 - val_loss: 0.5538 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7196 - val_loss: 0.5550 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7321 - val_loss: 0.5466 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7394 - val_loss: 0.5461 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5094 - accuracy: 0.7481 - val_loss: 0.5472 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7563 - val_loss: 0.5446 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7640 - val_loss: 0.5486 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4762 - accuracy: 0.7695 - val_loss: 0.5538 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4639 - accuracy: 0.7782
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4641 - accuracy: 0.7781 - val_loss: 0.5581 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41842905566620664
Confusion Matrix :
 [[2913 1134]
 [1220 2827]]
Accuracy on test set:    0.7091672844082036
Sensitivity:    0.6985421299728194 	 Specificity:    0.7197924388435878
Precision  : 0.7137086594294371
Area Under Curve:    0.7091672844082038
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5837 - accuracy: 0.6877 - val_loss: 0.5526 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7251 - val_loss: 0.5476 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5269 - accuracy: 0.7335 - val_loss: 0.5459 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7419 - val_loss: 0.5451 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7505 - val_loss: 0.5439 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7587 - val_loss: 0.5470 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7671 - val_loss: 0.5511 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7767 - val_loss: 0.5543 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4560 - accuracy: 0.7856 - val_loss: 0.5537 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4438 - accuracy: 0.7916 - val_loss: 0.5656 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4325 - accuracy: 0.7995 - val_loss: 0.5718 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4173 - accuracy: 0.8088 - val_loss: 0.5803 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - ETA: 0s - loss: 0.4049 - accuracy: 0.8157
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4049 - accuracy: 0.8157 - val_loss: 0.5764 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41786736986673906
Confusion Matrix :
 [[2892 1155]
 [1201 2846]]
Accuracy on test set:    0.7089201877934272
Sensitivity:    0.7032369656535705 	 Specificity:    0.7146034099332839
Precision  : 0.7113221694576356
Area Under Curve:    0.7089201877934271
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5883 - accuracy: 0.6854 - val_loss: 0.5560 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7211 - val_loss: 0.5461 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7341 - val_loss: 0.5504 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7412 - val_loss: 0.5477 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7498 - val_loss: 0.5476 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7587 - val_loss: 0.5515 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7665 - val_loss: 0.5519 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4680 - accuracy: 0.7760 - val_loss: 0.5563 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4555 - accuracy: 0.7844 - val_loss: 0.5587 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4412 - accuracy: 0.7938 - val_loss: 0.5738 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4284 - accuracy: 0.8013 - val_loss: 0.5774 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 12/400
250/257 [============================>.] - ETA: 0s - loss: 0.4131 - accuracy: 0.8098
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4135 - accuracy: 0.8094 - val_loss: 0.5832 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4038970630391858
Confusion Matrix :
 [[2894 1153]
 [1260 2787]]
Accuracy on test set:    0.7018779342723005
Sensitivity:    0.6886582653817642 	 Specificity:    0.7150976031628367
Precision  : 0.7073604060913705
Area Under Curve:    0.7018779342723005
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5860 - accuracy: 0.6859 - val_loss: 0.5476 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7231 - val_loss: 0.5404 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7314 - val_loss: 0.5411 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7428 - val_loss: 0.5352 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7499 - val_loss: 0.5366 - val_accuracy: 0.7337 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7583 - val_loss: 0.5398 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.7668 - val_loss: 0.5476 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4684 - accuracy: 0.7759 - val_loss: 0.5451 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4565 - accuracy: 0.7837 - val_loss: 0.5520 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4418 - accuracy: 0.7936
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4417 - accuracy: 0.7937 - val_loss: 0.5613 - val_accuracy: 0.7277 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44396480165323
Confusion Matrix :
 [[2864 1183]
 [1068 2979]]
Accuracy on test set:    0.721892760069187
Sensitivity:    0.7361008154188288 	 Specificity:    0.7076847047195454
Precision  : 0.7157616530514176
Area Under Curve:    0.7218927600691871
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5932 - accuracy: 0.6763 - val_loss: 0.5520 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7208 - val_loss: 0.5439 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7323 - val_loss: 0.5414 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.7416 - val_loss: 0.5394 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7482 - val_loss: 0.5417 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7574 - val_loss: 0.5451 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.7670 - val_loss: 0.5451 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7745 - val_loss: 0.5481 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4578 - accuracy: 0.7853 - val_loss: 0.5573 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4448 - accuracy: 0.7940 - val_loss: 0.5542 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4350 - accuracy: 0.8013 - val_loss: 0.5659 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4208 - accuracy: 0.8092 - val_loss: 0.5720 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 13/400
253/257 [============================>.] - ETA: 0s - loss: 0.4086 - accuracy: 0.8172
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4092 - accuracy: 0.8169 - val_loss: 0.5731 - val_accuracy: 0.7176 - lr: 0.0010

253/253 [==============================] - 0s 846us/step
Independent Testing Matthews Correlation:  0.45583771760484365
Confusion Matrix :
 [[2798 1249]
 [ 958 3089]]
Accuracy on test set:    0.7273288855942673
Sensitivity:    0.7632814430442303 	 Specificity:    0.6913763281443044
Precision  : 0.7120792992162287
Area Under Curve:    0.7273288855942673
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5978 - accuracy: 0.6754 - val_loss: 0.5520 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5523 - accuracy: 0.7179 - val_loss: 0.5402 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5357 - accuracy: 0.7298 - val_loss: 0.5383 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5237 - accuracy: 0.7379 - val_loss: 0.5385 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5118 - accuracy: 0.7454 - val_loss: 0.5389 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4991 - accuracy: 0.7549 - val_loss: 0.5466 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.7639 - val_loss: 0.5390 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7726 - val_loss: 0.5452 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 9/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4613 - accuracy: 0.7835
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4613 - accuracy: 0.7833 - val_loss: 0.5639 - val_accuracy: 0.7209 - lr: 0.0010
253/253 [==============================] - 0s 740us/step
Independent Testing Matthews Correlation:  0.4845580643600231
Confusion Matrix :
 [[2857 1190]
 [ 901 3146]]
Accuracy on test set:    0.7416604892512972
Sensitivity:    0.7773659500864838 	 Specificity:    0.7059550284161107
Precision  : 0.7255535055350554
Area Under Curve:    0.7416604892512972
(8094, 2560) (8094,)
Mean MCC = 0.4228 + 0.0291 and Mean AUC = 0.7110 + 0.0146
Mean Sensitivity = 0.7280 + 0.0317 and Mean Specificity = 0.6939 + 0.0303 and Mean Accuracy = 0.7110 + 0.0146
Mean Precision = 0.7045 + 0.0166





Seed   : 801918
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5839 - accuracy: 0.6869 - val_loss: 0.5620 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5419 - accuracy: 0.7246 - val_loss: 0.5493 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5258 - accuracy: 0.7360 - val_loss: 0.5526 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5120 - accuracy: 0.7458 - val_loss: 0.5475 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.7531 - val_loss: 0.5502 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.7614 - val_loss: 0.5481 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4773 - accuracy: 0.7715 - val_loss: 0.5626 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4625 - accuracy: 0.7801 - val_loss: 0.5604 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4528 - accuracy: 0.7879 - val_loss: 0.5641 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4371 - accuracy: 0.7953 - val_loss: 0.5651 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4260 - accuracy: 0.8036 - val_loss: 0.5766 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4131 - accuracy: 0.8114 - val_loss: 0.5785 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 13/400
246/257 [===========================>..] - ETA: 0s - loss: 0.3988 - accuracy: 0.8202
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3998 - accuracy: 0.8195 - val_loss: 0.5795 - val_accuracy: 0.7121 - lr: 0.0010
253/253 [==============================] - 0s 999us/step
Independent Testing Matthews Correlation:  0.40993586950373495
Confusion Matrix :
 [[2717 1331]
 [1061 2986]]
Accuracy on test set:    0.704508956145769
Sensitivity:    0.7378304917222634 	 Specificity:    0.6711956521739131
Precision  : 0.6916840398424832
Area Under Curve:    0.7045130719480883
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5893 - accuracy: 0.6821 - val_loss: 0.5536 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7230 - val_loss: 0.5477 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7347 - val_loss: 0.5487 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7427 - val_loss: 0.5421 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7510 - val_loss: 0.5440 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7587 - val_loss: 0.5477 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.7663 - val_loss: 0.5461 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4753 - accuracy: 0.7733 - val_loss: 0.5482 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4635 - accuracy: 0.7820
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7821 - val_loss: 0.5533 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 920us/step
Independent Testing Matthews Correlation:  0.4220531058916411
Confusion Matrix :
 [[2786 1262]
 [1079 2968]]
Accuracy on test set:    0.7108091414453366
Sensitivity:    0.7333827526562886 	 Specificity:    0.6882411067193676
Precision  : 0.7016548463356974
Area Under Curve:    0.7108119296878281
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5873 - accuracy: 0.6849 - val_loss: 0.5489 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7249 - val_loss: 0.5410 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7335 - val_loss: 0.5406 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7427 - val_loss: 0.5389 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.7512 - val_loss: 0.5370 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7596 - val_loss: 0.5450 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7674 - val_loss: 0.5429 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7751 - val_loss: 0.5452 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4559 - accuracy: 0.7862 - val_loss: 0.5496 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4445 - accuracy: 0.7942
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4449 - accuracy: 0.7938 - val_loss: 0.5536 - val_accuracy: 0.7213 - lr: 0.0010
253/253 [==============================] - 0s 906us/step
Independent Testing Matthews Correlation:  0.41895821211071405
Confusion Matrix :
 [[2602 1445]
 [ 921 3127]]
Accuracy on test set:    0.7077208153180976
Sensitivity:    0.7724802371541502 	 Specificity:    0.6429453916481345
Precision  : 0.6839457567804025
Area Under Curve:    0.7077128144011423
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5929 - accuracy: 0.6800 - val_loss: 0.5514 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5494 - accuracy: 0.7204 - val_loss: 0.5450 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7315 - val_loss: 0.5414 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5224 - accuracy: 0.7392 - val_loss: 0.5393 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5119 - accuracy: 0.7469 - val_loss: 0.5396 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 3ms/step - loss: 0.4982 - accuracy: 0.7558 - val_loss: 0.5429 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4862 - accuracy: 0.7640 - val_loss: 0.5440 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.7712 - val_loss: 0.5484 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4615 - accuracy: 0.7807 - val_loss: 0.5552 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4508 - accuracy: 0.7866 - val_loss: 0.5577 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4394 - accuracy: 0.7952 - val_loss: 0.5623 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4263 - accuracy: 0.8022
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4265 - accuracy: 0.8023 - val_loss: 0.5739 - val_accuracy: 0.7121 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3999968995430651
Confusion Matrix :
 [[3077  970]
 [1471 2577]]
Accuracy on test set:    0.6984558369363805
Sensitivity:    0.6366106719367589 	 Specificity:    0.7603162836669137
Precision  : 0.7265294615167748
Area Under Curve:    0.6984634778018363
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5858 - accuracy: 0.6849 - val_loss: 0.5465 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7241 - val_loss: 0.5407 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7317 - val_loss: 0.5375 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7405 - val_loss: 0.5370 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7480 - val_loss: 0.5382 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7577 - val_loss: 0.5387 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7674 - val_loss: 0.5528 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4703 - accuracy: 0.7761 - val_loss: 0.5437 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4552 - accuracy: 0.7865 - val_loss: 0.5457 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4420 - accuracy: 0.7957 - val_loss: 0.5522 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 11/400
252/257 [============================>.] - ETA: 0s - loss: 0.4291 - accuracy: 0.8019
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4291 - accuracy: 0.8018 - val_loss: 0.5594 - val_accuracy: 0.7219 - lr: 0.0010
253/253 [==============================] - 0s 720us/step
Independent Testing Matthews Correlation:  0.4312288650906715
Confusion Matrix :
 [[2821 1226]
 [1077 2970]]
Accuracy on test set:    0.7154682480850012
Sensitivity:    0.7338769458858414 	 Specificity:    0.6970595502841611
Precision  : 0.707816968541468
Area Under Curve:    0.7154682480850013
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5867 - accuracy: 0.6861 - val_loss: 0.5518 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7232 - val_loss: 0.5452 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7340 - val_loss: 0.5412 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7442 - val_loss: 0.5463 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7525 - val_loss: 0.5417 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7613 - val_loss: 0.5495 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7701 - val_loss: 0.5453 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.7777 - val_loss: 0.5460 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4518 - accuracy: 0.7874 - val_loss: 0.5505 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4390 - accuracy: 0.7946 - val_loss: 0.5528 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4246 - accuracy: 0.8042 - val_loss: 0.5557 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4122 - accuracy: 0.8118 - val_loss: 0.5667 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3991 - accuracy: 0.8197 - val_loss: 0.5775 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3872 - accuracy: 0.8236 - val_loss: 0.5896 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 15/400
254/257 [============================>.] - ETA: 0s - loss: 0.3760 - accuracy: 0.8315
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3761 - accuracy: 0.8313 - val_loss: 0.6009 - val_accuracy: 0.7179 - lr: 0.0010

253/253 [==============================] - 0s 876us/step
Independent Testing Matthews Correlation:  0.4124616018457054
Confusion Matrix :
 [[2712 1335]
 [1047 3000]]
Accuracy on test set:    0.7057079318013343
Sensitivity:    0.7412898443291327 	 Specificity:    0.670126019273536
Precision  : 0.6920415224913494
Area Under Curve:    0.7057079318013343
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5852 - accuracy: 0.6873 - val_loss: 0.5513 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5420 - accuracy: 0.7245 - val_loss: 0.5439 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7338 - val_loss: 0.5387 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7401 - val_loss: 0.5426 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7500 - val_loss: 0.5485 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7593 - val_loss: 0.5401 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7674 - val_loss: 0.5420 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4674 - accuracy: 0.7757
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.7757 - val_loss: 0.5461 - val_accuracy: 0.7200 - lr: 0.0010
253/253 [==============================] - 0s 767us/step
Independent Testing Matthews Correlation:  0.4321823233235213
Confusion Matrix :
 [[2884 1163]
 [1135 2912]]
Accuracy on test set:    0.7160859896219421
Sensitivity:    0.7195453422288115 	 Specificity:    0.7126266370150729
Precision  : 0.7146012269938651
Area Under Curve:    0.7160859896219423
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5913 - accuracy: 0.6827 - val_loss: 0.5676 - val_accuracy: 0.7028 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7206 - val_loss: 0.5443 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7311 - val_loss: 0.5419 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5216 - accuracy: 0.7398 - val_loss: 0.5539 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5112 - accuracy: 0.7461 - val_loss: 0.5441 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7542 - val_loss: 0.5480 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 7/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4898 - accuracy: 0.7632
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7626 - val_loss: 0.5447 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 889us/step
Independent Testing Matthews Correlation:  0.4403062965237284
Confusion Matrix :
 [[2979 1068]
 [1198 2849]]
Accuracy on test set:    0.7200395354583642
Sensitivity:    0.7039782554978997 	 Specificity:    0.7361008154188288
Precision  : 0.7273423538422262
Area Under Curve:    0.7200395354583642
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5897 - accuracy: 0.6821 - val_loss: 0.5561 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7222 - val_loss: 0.5481 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7339 - val_loss: 0.5446 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7421 - val_loss: 0.5423 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7516 - val_loss: 0.5441 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7573 - val_loss: 0.5461 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7660 - val_loss: 0.5490 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4731 - accuracy: 0.7730 - val_loss: 0.5538 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4605 - accuracy: 0.7832 - val_loss: 0.5572 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4475 - accuracy: 0.7913
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4480 - accuracy: 0.7909 - val_loss: 0.5557 - val_accuracy: 0.7172 - lr: 0.0010
253/253 [==============================] - 0s 911us/step
Independent Testing Matthews Correlation:  0.44972956495469496
Confusion Matrix :
 [[3108  939]
 [1295 2752]]
Accuracy on test set:    0.7239930812947862
Sensitivity:    0.680009883864591 	 Specificity:    0.7679762787249814
Precision  : 0.7455973990788404
Area Under Curve:    0.7239930812947862
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5927 - accuracy: 0.6824 - val_loss: 0.5725 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5514 - accuracy: 0.7181 - val_loss: 0.5532 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5375 - accuracy: 0.7287 - val_loss: 0.5502 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5261 - accuracy: 0.7374 - val_loss: 0.5517 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7430 - val_loss: 0.5494 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7515 - val_loss: 0.5522 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7594 - val_loss: 0.5474 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.7664 - val_loss: 0.5536 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7754 - val_loss: 0.5535 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4596 - accuracy: 0.7841 - val_loss: 0.5563 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4477 - accuracy: 0.7898 - val_loss: 0.5660 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 12/400
252/257 [============================>.] - ETA: 0s - loss: 0.4329 - accuracy: 0.8007
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4329 - accuracy: 0.8006 - val_loss: 0.5658 - val_accuracy: 0.7127 - lr: 0.0010
253/253 [==============================] - 0s 903us/step
Independent Testing Matthews Correlation:  0.4810274111674731
Confusion Matrix :
 [[3120  927]
 [1177 2870]]
Accuracy on test set:    0.7400543612552508
Sensitivity:    0.7091672844082036 	 Specificity:    0.770941438102298
Precision  : 0.7558598893863576
Area Under Curve:    0.7400543612552507
(8094, 2560) (8094,)
Mean MCC = 0.4298 + 0.0221 and Mean AUC = 0.7143 + 0.0113
Mean Sensitivity = 0.7168 + 0.0357 and Mean Specificity = 0.7118 + 0.0430 and Mean Accuracy = 0.7143 + 0.0113
Mean Precision = 0.7147 + 0.0227





Seed   : 70225

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5898 - accuracy: 0.6813 - val_loss: 0.5467 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7228 - val_loss: 0.5406 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7320 - val_loss: 0.5366 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5213 - accuracy: 0.7406 - val_loss: 0.5467 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.7452 - val_loss: 0.5389 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7546 - val_loss: 0.5399 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4902 - accuracy: 0.7618 - val_loss: 0.5488 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7688 - val_loss: 0.5450 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.7794 - val_loss: 0.5507 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4529 - accuracy: 0.7876
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4530 - accuracy: 0.7872 - val_loss: 0.5566 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 783us/step
Independent Testing Matthews Correlation:  0.39778669298799396
Confusion Matrix :
 [[2436 1612]
 [ 854 3193]]
Accuracy on test set:    0.6953675108091415
Sensitivity:    0.7889794909809735 	 Specificity:    0.6017786561264822
Precision  : 0.6645161290322581
Area Under Curve:    0.6953790735537279
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5872 - accuracy: 0.6828 - val_loss: 0.5495 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7226 - val_loss: 0.5437 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7349 - val_loss: 0.5594 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7424 - val_loss: 0.5409 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5040 - accuracy: 0.7523 - val_loss: 0.5406 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4954 - accuracy: 0.7574 - val_loss: 0.5422 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7684 - val_loss: 0.5467 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4690 - accuracy: 0.7763 - val_loss: 0.5475 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4581 - accuracy: 0.7819
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4582 - accuracy: 0.7819 - val_loss: 0.5536 - val_accuracy: 0.7167 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4191171862313178
Confusion Matrix :
 [[2717 1331]
 [1025 3022]]
Accuracy on test set:    0.7089561457689932
Sensitivity:    0.746725969854213 	 Specificity:    0.6711956521739131
Precision  : 0.6942338617045716
Area Under Curve:    0.708960811014063
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5927 - accuracy: 0.6780 - val_loss: 0.5486 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7209 - val_loss: 0.5367 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7302 - val_loss: 0.5293 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7392 - val_loss: 0.5290 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5106 - accuracy: 0.7460 - val_loss: 0.5304 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7535 - val_loss: 0.5313 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.7649 - val_loss: 0.5326 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4743 - accuracy: 0.7721
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7720 - val_loss: 0.5374 - val_accuracy: 0.7253 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4317590934607882
Confusion Matrix :
 [[2675 1372]
 [ 938 3110]]
Accuracy on test set:    0.7146386658431131
Sensitivity:    0.7682806324110671 	 Specificity:    0.66098344452681
Precision  : 0.6938866577420795
Area Under Curve:    0.7146320384689384
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5880 - accuracy: 0.6819 - val_loss: 0.5404 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7242 - val_loss: 0.5328 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7336 - val_loss: 0.5303 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7422 - val_loss: 0.5296 - val_accuracy: 0.7308 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7516 - val_loss: 0.5368 - val_accuracy: 0.7305 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7571 - val_loss: 0.5312 - val_accuracy: 0.7310 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4825 - accuracy: 0.7666 - val_loss: 0.5328 - val_accuracy: 0.7338 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4699 - accuracy: 0.7746 - val_loss: 0.5422 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4590 - accuracy: 0.7822 - val_loss: 0.5484 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4445 - accuracy: 0.7921 - val_loss: 0.5470 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4325 - accuracy: 0.7988 - val_loss: 0.5571 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 12/400
252/257 [============================>.] - ETA: 0s - loss: 0.4200 - accuracy: 0.8057
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4195 - accuracy: 0.8059 - val_loss: 0.5728 - val_accuracy: 0.7272 - lr: 0.0010
253/253 [==============================] - 0s 855us/step
Independent Testing Matthews Correlation:  0.4097126578051262
Confusion Matrix :
 [[2713 1334]
 [1059 2989]]
Accuracy on test set:    0.7043854231006794
Sensitivity:    0.7383893280632411 	 Specificity:    0.6703731158883123
Precision  : 0.6914179967615082
Area Under Curve:    0.7043812219757768
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5883 - accuracy: 0.6825 - val_loss: 0.5542 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7228 - val_loss: 0.5534 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7307 - val_loss: 0.5466 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7387 - val_loss: 0.5472 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7485 - val_loss: 0.5489 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 6/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4966 - accuracy: 0.7560
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7561 - val_loss: 0.5508 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 778us/step
Independent Testing Matthews Correlation:  0.4269971462576306
Confusion Matrix :
 [[2904 1143]
 [1176 2871]]
Accuracy on test set:    0.7134914751667902
Sensitivity:    0.7094143810229799 	 Specificity:    0.7175685693106004
Precision  : 0.7152466367713004
Area Under Curve:    0.7134914751667902
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5881 - accuracy: 0.6839 - val_loss: 0.5568 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5477 - accuracy: 0.7213 - val_loss: 0.5533 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7333 - val_loss: 0.5513 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7405 - val_loss: 0.5492 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5094 - accuracy: 0.7477 - val_loss: 0.5493 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7542 - val_loss: 0.5509 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.7630 - val_loss: 0.5535 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.7712 - val_loss: 0.5618 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4682 - accuracy: 0.7778 - val_loss: 0.5700 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4559 - accuracy: 0.7841 - val_loss: 0.5640 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4423 - accuracy: 0.7942 - val_loss: 0.5694 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4293 - accuracy: 0.8008 - val_loss: 0.5742 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - ETA: 0s - loss: 0.4157 - accuracy: 0.8090
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4157 - accuracy: 0.8090 - val_loss: 0.5854 - val_accuracy: 0.7094 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4319259506959907
Confusion Matrix :
 [[2902 1145]
 [1154 2893]]
Accuracy on test set:    0.715962441314554
Sensitivity:    0.7148505065480603 	 Specificity:    0.7170743760810477
Precision  : 0.7164437840515107
Area Under Curve:    0.7159624413145539
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5830 - accuracy: 0.6880 - val_loss: 0.5539 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5406 - accuracy: 0.7268 - val_loss: 0.5520 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5255 - accuracy: 0.7374 - val_loss: 0.5456 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7447 - val_loss: 0.5449 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5024 - accuracy: 0.7518 - val_loss: 0.5477 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7614 - val_loss: 0.5449 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4773 - accuracy: 0.7706 - val_loss: 0.5492 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4651 - accuracy: 0.7793 - val_loss: 0.5534 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4521 - accuracy: 0.7881 - val_loss: 0.5562 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 10/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4392 - accuracy: 0.7963
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4392 - accuracy: 0.7961 - val_loss: 0.5656 - val_accuracy: 0.7172 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4139264597099842
Confusion Matrix :
 [[2889 1158]
 [1214 2833]]
Accuracy on test set:    0.7069434148752162
Sensitivity:    0.7000247096614777 	 Specificity:    0.7138621200889548
Precision  : 0.7098471561012277
Area Under Curve:    0.7069434148752162
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5866 - accuracy: 0.6858 - val_loss: 0.5550 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7237 - val_loss: 0.5498 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7318 - val_loss: 0.5471 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5212 - accuracy: 0.7390 - val_loss: 0.5450 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7461 - val_loss: 0.5506 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7562 - val_loss: 0.5421 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.7632 - val_loss: 0.5481 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7719 - val_loss: 0.5514 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4629 - accuracy: 0.7797 - val_loss: 0.5538 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4497 - accuracy: 0.7894
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4499 - accuracy: 0.7895 - val_loss: 0.5662 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 929us/step
Independent Testing Matthews Correlation:  0.4339023046179478
Confusion Matrix :
 [[2905 1142]
 [1149 2898]]
Accuracy on test set:    0.7169508277736595
Sensitivity:    0.7160859896219421 	 Specificity:    0.7178156659253768
Precision  : 0.7173267326732673
Area Under Curve:    0.7169508277736596
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5902 - accuracy: 0.6828 - val_loss: 0.5551 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7200 - val_loss: 0.5518 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7314 - val_loss: 0.5443 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7401 - val_loss: 0.5423 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7479 - val_loss: 0.5438 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7547 - val_loss: 0.5436 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7665 - val_loss: 0.5492 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4692 - accuracy: 0.7743 - val_loss: 0.5535 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4549 - accuracy: 0.7849
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4549 - accuracy: 0.7849 - val_loss: 0.5575 - val_accuracy: 0.7141 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4728519831349477
Confusion Matrix :
 [[2928 1119]
 [1015 3032]]
Accuracy on test set:    0.7363479120336052
Sensitivity:    0.7491969360019768 	 Specificity:    0.7234988880652335
Precision  : 0.7304264032763189
Area Under Curve:    0.7363479120336052
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5911 - accuracy: 0.6810 - val_loss: 0.5602 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7179 - val_loss: 0.5504 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5330 - accuracy: 0.7325 - val_loss: 0.5532 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5211 - accuracy: 0.7391 - val_loss: 0.5475 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5101 - accuracy: 0.7475 - val_loss: 0.5481 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4989 - accuracy: 0.7559 - val_loss: 0.5506 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4889 - accuracy: 0.7620 - val_loss: 0.5557 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7718 - val_loss: 0.5558 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4628 - accuracy: 0.7801 - val_loss: 0.5584 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4502 - accuracy: 0.7890 - val_loss: 0.5631 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4371 - accuracy: 0.7956 - val_loss: 0.5688 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 12/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4212 - accuracy: 0.8064
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4223 - accuracy: 0.8052 - val_loss: 0.5756 - val_accuracy: 0.7093 - lr: 0.0010
253/253 [==============================] - 0s 867us/step
Independent Testing Matthews Correlation:  0.45514248493776416
Confusion Matrix :
 [[3264  783]
 [1447 2600]]
Accuracy on test set:    0.724487274524339
Sensitivity:    0.6424511984185817 	 Specificity:    0.8065233506300964
Precision  : 0.7685486254803429
Area Under Curve:    0.724487274524339
(8094, 2560) (8094,)
Mean MCC = 0.4293 + 0.0208 and Mean AUC = 0.7138 + 0.0107
Mean Sensitivity = 0.7274 + 0.0387 and Mean Specificity = 0.7001 + 0.0509 and Mean Accuracy = 0.7138 + 0.0107
Mean Precision = 0.7102 + 0.0262





Seed   : 580428
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5825 - accuracy: 0.6882 - val_loss: 0.5560 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5403 - accuracy: 0.7262 - val_loss: 0.5476 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5249 - accuracy: 0.7355 - val_loss: 0.5555 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.7444 - val_loss: 0.5450 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5022 - accuracy: 0.7511 - val_loss: 0.5478 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7610 - val_loss: 0.5519 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7685 - val_loss: 0.5532 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4677 - accuracy: 0.7760 - val_loss: 0.5559 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4549 - accuracy: 0.7854 - val_loss: 0.5549 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4403 - accuracy: 0.7953
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4406 - accuracy: 0.7950 - val_loss: 0.5602 - val_accuracy: 0.7086 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3906477965436892
Confusion Matrix :
 [[2757 1291]
 [1176 2871]]
Accuracy on test set:    0.6952439777640519
Sensitivity:    0.7094143810229799 	 Specificity:    0.6810770750988142
Precision  : 0.689812590100913
Area Under Curve:    0.6952457280608971
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5850 - accuracy: 0.6857 - val_loss: 0.5561 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7236 - val_loss: 0.5464 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.7362 - val_loss: 0.5442 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5137 - accuracy: 0.7448 - val_loss: 0.5469 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7508 - val_loss: 0.5541 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4927 - accuracy: 0.7614 - val_loss: 0.5510 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.7679 - val_loss: 0.5504 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4700 - accuracy: 0.7746 - val_loss: 0.5615 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4567 - accuracy: 0.7850
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4564 - accuracy: 0.7852 - val_loss: 0.5612 - val_accuracy: 0.7131 - lr: 0.0010

253/253 [==============================] - 0s 849us/step
Independent Testing Matthews Correlation:  0.42457813624356383
Confusion Matrix :
 [[2815 1233]
 [1097 2950]]
Accuracy on test set:    0.7121680049413218
Sensitivity:    0.7289350135903138 	 Specificity:    0.6954051383399209
Precision  : 0.7052354769304328
Area Under Curve:    0.7121700759651173
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5918 - accuracy: 0.6815 - val_loss: 0.5498 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7218 - val_loss: 0.5413 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7319 - val_loss: 0.5367 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7396 - val_loss: 0.5348 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7455 - val_loss: 0.5362 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5038 - accuracy: 0.7518 - val_loss: 0.5372 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7594 - val_loss: 0.5356 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7671 - val_loss: 0.5389 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7732 - val_loss: 0.5453 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4627 - accuracy: 0.7805 - val_loss: 0.5489 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4523 - accuracy: 0.7873 - val_loss: 0.5457 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4412 - accuracy: 0.7951 - val_loss: 0.5486 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4302 - accuracy: 0.8013 - val_loss: 0.5613 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4184 - accuracy: 0.8072 - val_loss: 0.5626 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4087 - accuracy: 0.8151 - val_loss: 0.5707 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 16/400
252/257 [============================>.] - ETA: 0s - loss: 0.3986 - accuracy: 0.8187
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3988 - accuracy: 0.8188 - val_loss: 0.5861 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40372899218883485
Confusion Matrix :
 [[2704 1343]
 [1074 2974]]
Accuracy on test set:    0.70142063001853
Sensitivity:    0.7346837944664032 	 Specificity:    0.6681492463553249
Precision  : 0.688904331711837
Area Under Curve:    0.701416520410864
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5870 - accuracy: 0.6830 - val_loss: 0.5486 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7208 - val_loss: 0.5362 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7341 - val_loss: 0.5367 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7418 - val_loss: 0.5315 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7484 - val_loss: 0.5324 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7559 - val_loss: 0.5314 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4862 - accuracy: 0.7636 - val_loss: 0.5373 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7740 - val_loss: 0.5383 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4614 - accuracy: 0.7833 - val_loss: 0.5401 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4486 - accuracy: 0.7883
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4493 - accuracy: 0.7878 - val_loss: 0.5463 - val_accuracy: 0.7235 - lr: 0.0010
253/253 [==============================] - 0s 959us/step
Independent Testing Matthews Correlation:  0.4255348653784268
Confusion Matrix :
 [[2820 1227]
 [1099 2949]]
Accuracy on test set:    0.71266213712168
Sensitivity:    0.72850790513834 	 Specificity:    0.6968124536693847
Precision  : 0.7061781609195402
Area Under Curve:    0.7126601794038623
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 8ms/step - loss: 0.5882 - accuracy: 0.6827 - val_loss: 0.5525 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7236 - val_loss: 0.5492 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7327 - val_loss: 0.5426 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7414 - val_loss: 0.5393 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7501 - val_loss: 0.5414 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7574 - val_loss: 0.5403 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7664 - val_loss: 0.5411 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4714 - accuracy: 0.7748 - val_loss: 0.5564 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4577 - accuracy: 0.7835
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4584 - accuracy: 0.7831 - val_loss: 0.5507 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43234155927178336
Confusion Matrix :
 [[2748 1299]
 [1003 3044]]
Accuracy on test set:    0.7155917963923895
Sensitivity:    0.7521620953792933 	 Specificity:    0.6790214974054856
Precision  : 0.7008979967764218
Area Under Curve:    0.7155917963923895
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5850 - accuracy: 0.6869 - val_loss: 0.5478 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7230 - val_loss: 0.5433 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7329 - val_loss: 0.5400 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7419 - val_loss: 0.5385 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7479 - val_loss: 0.5418 - val_accuracy: 0.7263 - lr: 0.0010

Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7548 - val_loss: 0.5412 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7642 - val_loss: 0.5425 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4754 - accuracy: 0.7720 - val_loss: 0.5528 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4622 - accuracy: 0.7792
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4626 - accuracy: 0.7788 - val_loss: 0.5510 - val_accuracy: 0.7249 - lr: 0.0010
253/253 [==============================] - 0s 877us/step
Independent Testing Matthews Correlation:  0.4208304080057751
Confusion Matrix :
 [[2897 1150]
 [1194 2853]]
Accuracy on test set:    0.7104027674820855
Sensitivity:    0.7049666419570052 	 Specificity:    0.7158388930071659
Precision  : 0.7127154634024482
Area Under Curve:    0.7104027674820854
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5880 - accuracy: 0.6838 - val_loss: 0.5458 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7216 - val_loss: 0.5399 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7314 - val_loss: 0.5365 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.7395 - val_loss: 0.5380 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7477 - val_loss: 0.5413 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4994 - accuracy: 0.7547 - val_loss: 0.5391 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4887 - accuracy: 0.7632 - val_loss: 0.5426 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4762 - accuracy: 0.7709
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4769 - accuracy: 0.7702 - val_loss: 0.5415 - val_accuracy: 0.7267 - lr: 0.0010
253/253 [==============================] - 0s 773us/step
Independent Testing Matthews Correlation:  0.42427006851187454
Confusion Matrix :
 [[2872 1175]
 [1155 2892]]
Accuracy on test set:    0.7121324437855201
Sensitivity:    0.7146034099332839 	 Specificity:    0.7096614776377563
Precision  : 0.7110892549791
Area Under Curve:    0.7121324437855201
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5880 - accuracy: 0.6828 - val_loss: 0.5427 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7222 - val_loss: 0.5358 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7343 - val_loss: 0.5330 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7433 - val_loss: 0.5362 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7519 - val_loss: 0.5358 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7601 - val_loss: 0.5351 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4781 - accuracy: 0.7700 - val_loss: 0.5444 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4669 - accuracy: 0.7777
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4669 - accuracy: 0.7779 - val_loss: 0.5455 - val_accuracy: 0.7234 - lr: 0.0010
253/253 [==============================] - 0s 748us/step
Independent Testing Matthews Correlation:  0.4310412999311161
Confusion Matrix :
 [[3066  981]
 [1328 2719]]
Accuracy on test set:    0.7147269582406721
Sensitivity:    0.6718556955769706 	 Specificity:    0.7575982209043736
Precision  : 0.7348648648648649
Area Under Curve:    0.7147269582406721
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.6027 - accuracy: 0.6713 - val_loss: 0.5529 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5532 - accuracy: 0.7186 - val_loss: 0.5407 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5377 - accuracy: 0.7298 - val_loss: 0.5374 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5249 - accuracy: 0.7378 - val_loss: 0.5349 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5124 - accuracy: 0.7484 - val_loss: 0.5390 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7542 - val_loss: 0.5383 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 7/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4885 - accuracy: 0.7624
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7629 - val_loss: 0.5416 - val_accuracy: 0.7285 - lr: 0.0010
253/253 [==============================] - 0s 892us/step
Independent Testing Matthews Correlation:  0.45819581288709793
Confusion Matrix :
 [[2913 1134]
 [1059 2988]]
Accuracy on test set:    0.729058561897702
Sensitivity:    0.7383246849518161 	 Specificity:    0.7197924388435878
Precision  : 0.7248908296943232
Area Under Curve:    0.7290585618977021
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5912 - accuracy: 0.6832 - val_loss: 0.5515 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7182 - val_loss: 0.5468 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5349 - accuracy: 0.7293 - val_loss: 0.5425 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5227 - accuracy: 0.7390 - val_loss: 0.5422 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7450 - val_loss: 0.5440 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.7549 - val_loss: 0.5428 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4897 - accuracy: 0.7635 - val_loss: 0.5529 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.7713 - val_loss: 0.5475 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4663 - accuracy: 0.7797
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4663 - accuracy: 0.7797 - val_loss: 0.5583 - val_accuracy: 0.7229 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.48966010381094166
Confusion Matrix :
 [[2962 1085]
 [ 981 3066]]
Accuracy on test set:    0.744749196936002
Sensitivity:    0.7575982209043736 	 Specificity:    0.7319001729676303
Precision  : 0.7386172006745363
Area Under Curve:    0.744749196936002
(8094, 2560) (8094,)
Mean MCC = 0.4301 + 0.0260 and Mean AUC = 0.7148 + 0.0130
Mean Sensitivity = 0.7241 + 0.0238 and Mean Specificity = 0.7055 + 0.0257 and Mean Accuracy = 0.7148 + 0.0130
Mean Precision = 0.7113 + 0.0162





Seed   : 891000

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5880 - accuracy: 0.6827 - val_loss: 0.5633 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7250 - val_loss: 0.5513 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5270 - accuracy: 0.7344 - val_loss: 0.5499 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5148 - accuracy: 0.7445 - val_loss: 0.5496 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7514 - val_loss: 0.5506 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7597 - val_loss: 0.5522 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.7656 - val_loss: 0.5519 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7751 - val_loss: 0.5704 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4583 - accuracy: 0.7846 - val_loss: 0.5593 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4464 - accuracy: 0.7929 - val_loss: 0.5702 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4299 - accuracy: 0.8018 - val_loss: 0.5804 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4179 - accuracy: 0.8081
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4181 - accuracy: 0.8078 - val_loss: 0.5819 - val_accuracy: 0.7053 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3890737497396456
Confusion Matrix :
 [[2774 1274]
 [1199 2848]]
Accuracy on test set:    0.6945027794935145
Sensitivity:    0.7037311588831233 	 Specificity:    0.6852766798418972
Precision  : 0.6909267345948569
Area Under Curve:    0.6945039193625103
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5888 - accuracy: 0.6823 - val_loss: 0.5554 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7239 - val_loss: 0.5472 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7352 - val_loss: 0.5456 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7433 - val_loss: 0.5461 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7505 - val_loss: 0.5488 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7592 - val_loss: 0.5519 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7676 - val_loss: 0.5497 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4716 - accuracy: 0.7739 - val_loss: 0.5531 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4584 - accuracy: 0.7838 - val_loss: 0.5619 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4465 - accuracy: 0.7928 - val_loss: 0.5627 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4322 - accuracy: 0.8006 - val_loss: 0.5696 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 12/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4209 - accuracy: 0.8078
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4216 - accuracy: 0.8070 - val_loss: 0.5744 - val_accuracy: 0.7101 - lr: 0.0010
253/253 [==============================] - 0s 780us/step
Independent Testing Matthews Correlation:  0.41016684037624973
Confusion Matrix :
 [[2911 1137]
 [1251 2796]]
Accuracy on test set:    0.7050030883261272
Sensitivity:    0.6908821349147517 	 Specificity:    0.7191205533596838
Precision  : 0.7109077040427155
Area Under Curve:    0.7050013441372177
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5844 - accuracy: 0.6866 - val_loss: 0.5496 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7227 - val_loss: 0.5372 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7329 - val_loss: 0.5420 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7409 - val_loss: 0.5409 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7470 - val_loss: 0.5367 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7547 - val_loss: 0.5413 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4892 - accuracy: 0.7618
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4890 - accuracy: 0.7620 - val_loss: 0.5435 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 845us/step
Independent Testing Matthews Correlation:  0.4282499955864471
Confusion Matrix :
 [[2753 1294]
 [1024 3024]]
Accuracy on test set:    0.7136504014823966
Sensitivity:    0.7470355731225297 	 Specificity:    0.6802569804793674
Precision  : 0.7003242241778601
Area Under Curve:    0.7136462768009486
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5856 - accuracy: 0.6862 - val_loss: 0.5474 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7223 - val_loss: 0.5377 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7349 - val_loss: 0.5395 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7424 - val_loss: 0.5361 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7509 - val_loss: 0.5364 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7581 - val_loss: 0.5359 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.7690 - val_loss: 0.5448 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4692 - accuracy: 0.7761 - val_loss: 0.5479 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4543 - accuracy: 0.7860 - val_loss: 0.5532 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4400 - accuracy: 0.7948
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4402 - accuracy: 0.7947 - val_loss: 0.5537 - val_accuracy: 0.7222 - lr: 0.0010
253/253 [==============================] - 0s 786us/step
Independent Testing Matthews Correlation:  0.4069565237424869
Confusion Matrix :
 [[2789 1258]
 [1143 2905]]
Accuracy on test set:    0.7033971587399629
Sensitivity:    0.7176383399209486 	 Specificity:    0.689152458611317
Precision  : 0.6978140763872207
Area Under Curve:    0.7033953992661329
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5864 - accuracy: 0.6854 - val_loss: 0.5534 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7212 - val_loss: 0.5449 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5327 - accuracy: 0.7324 - val_loss: 0.5451 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.7385 - val_loss: 0.5438 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7461 - val_loss: 0.5455 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7545 - val_loss: 0.5442 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4902 - accuracy: 0.7617 - val_loss: 0.5460 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4774 - accuracy: 0.7716 - val_loss: 0.5525 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4651 - accuracy: 0.7786 - val_loss: 0.5584 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4511 - accuracy: 0.7876 - val_loss: 0.5614 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4387 - accuracy: 0.7966 - val_loss: 0.5758 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 12/400
254/257 [============================>.] - ETA: 0s - loss: 0.4271 - accuracy: 0.8020
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 3ms/step - loss: 0.4271 - accuracy: 0.8021 - val_loss: 0.5667 - val_accuracy: 0.7126 - lr: 0.0010
253/253 [==============================] - 0s 959us/step
Independent Testing Matthews Correlation:  0.4185832116522068
Confusion Matrix :
 [[2865 1182]
 [1171 2876]]
Accuracy on test set:    0.7092908327155918
Sensitivity:    0.7106498640968619 	 Specificity:    0.7079318013343218
Precision  : 0.708723509117792
Area Under Curve:    0.7092908327155918
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5875 - accuracy: 0.6850 - val_loss: 0.5576 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7214 - val_loss: 0.5474 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7324 - val_loss: 0.5470 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7404 - val_loss: 0.5456 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7481 - val_loss: 0.5451 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4994 - accuracy: 0.7556 - val_loss: 0.5542 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7631 - val_loss: 0.5501 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4732 - accuracy: 0.7727 - val_loss: 0.5584 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4618 - accuracy: 0.7802 - val_loss: 0.5569 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4479 - accuracy: 0.7893 - val_loss: 0.5582 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4368 - accuracy: 0.7977 - val_loss: 0.5679 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4238 - accuracy: 0.8060 - val_loss: 0.5739 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4123 - accuracy: 0.8126 - val_loss: 0.5803 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 14/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4012 - accuracy: 0.8179
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4012 - accuracy: 0.8181 - val_loss: 0.5908 - val_accuracy: 0.7126 - lr: 0.0010
253/253 [==============================] - 0s 785us/step
Independent Testing Matthews Correlation:  0.40553986722933305
Confusion Matrix :
 [[2665 1382]
 [1030 3017]]
Accuracy on test set:    0.7020014825796886
Sensitivity:    0.7454904867803311 	 Specificity:    0.6585124783790463
Precision  : 0.6858376903841782
Area Under Curve:    0.7020014825796886
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5862 - accuracy: 0.6848 - val_loss: 0.5524 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7228 - val_loss: 0.5459 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7345 - val_loss: 0.5468 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7433 - val_loss: 0.5447 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5027 - accuracy: 0.7520 - val_loss: 0.5452 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.7610 - val_loss: 0.5467 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7700 - val_loss: 0.5498 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4636 - accuracy: 0.7802 - val_loss: 0.5508 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4498 - accuracy: 0.7900 - val_loss: 0.5642 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4363 - accuracy: 0.7991
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4362 - accuracy: 0.7992 - val_loss: 0.5686 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 690us/step
Independent Testing Matthews Correlation:  0.43061320279435256
Confusion Matrix :
 [[2655 1392]
 [ 924 3123]]
Accuracy on test set:    0.7138621200889548
Sensitivity:    0.7716827279466272 	 Specificity:    0.6560415122312825
Precision  : 0.6916943521594684
Area Under Curve:    0.7138621200889548
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5859 - accuracy: 0.6872 - val_loss: 0.5538 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7248 - val_loss: 0.5458 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7351 - val_loss: 0.5427 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7416 - val_loss: 0.5411 - val_accuracy: 0.7160 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7509 - val_loss: 0.5461 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7574 - val_loss: 0.5460 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4861 - accuracy: 0.7650 - val_loss: 0.5464 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7731 - val_loss: 0.5550 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4616 - accuracy: 0.7824 - val_loss: 0.5497 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4493 - accuracy: 0.7901 - val_loss: 0.5570 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4401 - accuracy: 0.7953 - val_loss: 0.5693 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4271 - accuracy: 0.8025 - val_loss: 0.5660 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4146 - accuracy: 0.8112 - val_loss: 0.5775 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 14/400
254/257 [============================>.] - ETA: 0s - loss: 0.4010 - accuracy: 0.8187
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4011 - accuracy: 0.8187 - val_loss: 0.5760 - val_accuracy: 0.7154 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44030335234119333
Confusion Matrix :
 [[2733 1314]
 [ 958 3089]]
Accuracy on test set:    0.7192982456140351
Sensitivity:    0.7632814430442303 	 Specificity:    0.6753150481838399
Precision  : 0.7015671133318192
Area Under Curve:    0.7192982456140351
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6826 - val_loss: 0.5562 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7214 - val_loss: 0.5547 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7323 - val_loss: 0.5471 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7411 - val_loss: 0.5459 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7483 - val_loss: 0.5545 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.7543 - val_loss: 0.5529 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.7632 - val_loss: 0.5467 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4765 - accuracy: 0.7731
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4766 - accuracy: 0.7732 - val_loss: 0.5516 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4650490503801099
Confusion Matrix :
 [[2869 1178]
 [ 989 3058]]
Accuracy on test set:    0.7322708178897949
Sensitivity:    0.7556214479861626 	 Specificity:    0.7089201877934272
Precision  : 0.7219074598677998
Area Under Curve:    0.7322708178897949
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5941 - accuracy: 0.6805 - val_loss: 0.5591 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5509 - accuracy: 0.7182 - val_loss: 0.5490 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5334 - accuracy: 0.7304 - val_loss: 0.5574 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5240 - accuracy: 0.7386 - val_loss: 0.5483 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5138 - accuracy: 0.7453 - val_loss: 0.5491 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5038 - accuracy: 0.7532 - val_loss: 0.5495 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4909 - accuracy: 0.7632
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.7633 - val_loss: 0.5523 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 708us/step
Independent Testing Matthews Correlation:  0.4830286865276871
Confusion Matrix :
 [[3059  988]
 [1105 2942]]
Accuracy on test set:    0.7414133926365208
Sensitivity:    0.7269582406721028 	 Specificity:    0.755868544600939
Precision  : 0.7486005089058524
Area Under Curve:    0.741413392636521
(8094, 2560) (8094,)
Mean MCC = 0.4278 + 0.0273 and Mean AUC = 0.7135 + 0.0136
Mean Sensitivity = 0.7333 + 0.0258 and Mean Specificity = 0.6936 + 0.0287 and Mean Accuracy = 0.7135 + 0.0136
Mean Precision = 0.7058 + 0.0175





Seed   : 485300
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5842 - accuracy: 0.6878 - val_loss: 0.5621 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7253 - val_loss: 0.5517 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5257 - accuracy: 0.7367 - val_loss: 0.5469 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7442 - val_loss: 0.5527 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5054 - accuracy: 0.7495 - val_loss: 0.5486 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7591 - val_loss: 0.5524 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7661 - val_loss: 0.5583 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7736 - val_loss: 0.5641 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4595 - accuracy: 0.7820 - val_loss: 0.5736 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 10/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4469 - accuracy: 0.7913
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4466 - accuracy: 0.7913 - val_loss: 0.5715 - val_accuracy: 0.7127 - lr: 0.0010
253/253 [==============================] - 0s 740us/step
Independent Testing Matthews Correlation:  0.40013826431536403
Confusion Matrix :
 [[2817 1231]
 [1197 2850]]
Accuracy on test set:    0.7000617665225448
Sensitivity:    0.704225352112676 	 Specificity:    0.695899209486166
Precision  : 0.6983582455280568
Area Under Curve:    0.700062280799421
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.6840 - val_loss: 0.5635 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7231 - val_loss: 0.5469 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7349 - val_loss: 0.5456 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.7435 - val_loss: 0.5436 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5027 - accuracy: 0.7520 - val_loss: 0.5464 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.7589 - val_loss: 0.5493 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4831 - accuracy: 0.7647 - val_loss: 0.5567 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7763 - val_loss: 0.5534 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4588 - accuracy: 0.7827
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.7823 - val_loss: 0.5662 - val_accuracy: 0.7104 - lr: 0.0010
253/253 [==============================] - 0s 806us/step
Independent Testing Matthews Correlation:  0.4167757754141296
Confusion Matrix :
 [[2650 1398]
 [ 972 3075]]
Accuracy on test set:    0.7072266831377394
Sensitivity:    0.759822090437361 	 Specificity:    0.6546442687747036
Precision  : 0.687458081824279
Area Under Curve:    0.7072331796060323
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5879 - accuracy: 0.6831 - val_loss: 0.5459 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7227 - val_loss: 0.5334 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7340 - val_loss: 0.5363 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7399 - val_loss: 0.5379 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7491 - val_loss: 0.5358 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7568 - val_loss: 0.5410 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4840 - accuracy: 0.7659
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.7657 - val_loss: 0.5378 - val_accuracy: 0.7272 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4176494792443948
Confusion Matrix :
 [[2935 1112]
 [1246 2802]]
Accuracy on test set:    0.7087090796788141
Sensitivity:    0.692193675889328 	 Specificity:    0.7252285643686681
Precision  : 0.715891670924885
Area Under Curve:    0.7087111201289982
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5914 - accuracy: 0.6809 - val_loss: 0.5397 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7203 - val_loss: 0.5331 - val_accuracy: 0.7314 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7306 - val_loss: 0.5370 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5206 - accuracy: 0.7390 - val_loss: 0.5275 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7484 - val_loss: 0.5300 - val_accuracy: 0.7345 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.7566 - val_loss: 0.5304 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7654 - val_loss: 0.5349 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4726 - accuracy: 0.7732 - val_loss: 0.5417 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4596 - accuracy: 0.7823 - val_loss: 0.5492 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4473 - accuracy: 0.7896
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4469 - accuracy: 0.7898 - val_loss: 0.5508 - val_accuracy: 0.7255 - lr: 0.0010
253/253 [==============================] - 0s 753us/step
Independent Testing Matthews Correlation:  0.42181062935111263
Confusion Matrix :
 [[2693 1354]
 [ 993 3055]]
Accuracy on test set:    0.7100679431747993
Sensitivity:    0.754693675889328 	 Specificity:    0.6654311835927847
Precision  : 0.6929008845543208
Area Under Curve:    0.7100624297410565
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6798 - val_loss: 0.5562 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7220 - val_loss: 0.5446 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7334 - val_loss: 0.5437 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7422 - val_loss: 0.5404 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7487 - val_loss: 0.5425 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7583 - val_loss: 0.5462 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - ETA: 0s - loss: 0.4857 - accuracy: 0.7664
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4857 - accuracy: 0.7664 - val_loss: 0.5463 - val_accuracy: 0.7253 - lr: 0.0010
253/253 [==============================] - 0s 939us/step
Independent Testing Matthews Correlation:  0.4364225670084523
Confusion Matrix :
 [[2765 1282]
 [1003 3044]]
Accuracy on test set:    0.7176921176179887
Sensitivity:    0.7521620953792933 	 Specificity:    0.683222139856684
Precision  : 0.7036523347202959
Area Under Curve:    0.7176921176179887
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5836 - accuracy: 0.6899 - val_loss: 0.5491 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7223 - val_loss: 0.5442 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7312 - val_loss: 0.5430 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7398 - val_loss: 0.5522 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7484 - val_loss: 0.5555 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4959 - accuracy: 0.7563
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7561 - val_loss: 0.5461 - val_accuracy: 0.7226 - lr: 0.0010
253/253 [==============================] - 0s 902us/step
Independent Testing Matthews Correlation:  0.44638945917612044
Confusion Matrix :
 [[2726 1321]
 [ 928 3119]]
Accuracy on test set:    0.7221398566839634
Sensitivity:    0.7706943414875216 	 Specificity:    0.6735853718804052
Precision  : 0.7024774774774775
Area Under Curve:    0.7221398566839634
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5868 - accuracy: 0.6845 - val_loss: 0.5502 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7224 - val_loss: 0.5418 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7322 - val_loss: 0.5383 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7402 - val_loss: 0.5388 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7485 - val_loss: 0.5414 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7543 - val_loss: 0.5435 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.7619 - val_loss: 0.5445 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4749 - accuracy: 0.7718
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4753 - accuracy: 0.7715 - val_loss: 0.5458 - val_accuracy: 0.7200 - lr: 0.0010
253/253 [==============================] - 0s 771us/step
Independent Testing Matthews Correlation:  0.42484209522181343
Confusion Matrix :
 [[2843 1204]
 [1124 2923]]
Accuracy on test set:    0.7123795404002965
Sensitivity:    0.7222634049913517 	 Specificity:    0.7024956758092414
Precision  : 0.7082626605282287
Area Under Curve:    0.7123795404002965
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5888 - accuracy: 0.6827 - val_loss: 0.5531 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7234 - val_loss: 0.5414 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7330 - val_loss: 0.5387 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7407 - val_loss: 0.5408 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5094 - accuracy: 0.7471 - val_loss: 0.5418 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7559 - val_loss: 0.5421 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7637 - val_loss: 0.5430 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4736 - accuracy: 0.7735
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7735 - val_loss: 0.5484 - val_accuracy: 0.7244 - lr: 0.0010
253/253 [==============================] - 0s 749us/step
Independent Testing Matthews Correlation:  0.43793424952970106
Confusion Matrix :
 [[3012 1035]
 [1242 2805]]
Accuracy on test set:    0.7186805040770942
Sensitivity:    0.6931060044477391 	 Specificity:    0.7442550037064493
Precision  : 0.73046875
Area Under Curve:    0.7186805040770943
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5888 - accuracy: 0.6850 - val_loss: 0.5532 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5484 - accuracy: 0.7203 - val_loss: 0.5489 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7310 - val_loss: 0.5548 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5226 - accuracy: 0.7382 - val_loss: 0.5450 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5119 - accuracy: 0.7449 - val_loss: 0.5462 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5019 - accuracy: 0.7522 - val_loss: 0.5470 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.7615 - val_loss: 0.5475 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7676 - val_loss: 0.5572 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4672 - accuracy: 0.7774 - val_loss: 0.5520 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4549 - accuracy: 0.7857 - val_loss: 0.5589 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4426 - accuracy: 0.7942 - val_loss: 0.5651 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4296 - accuracy: 0.8009 - val_loss: 0.5697 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4198 - accuracy: 0.8070 - val_loss: 0.5779 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 14/400
253/257 [============================>.] - ETA: 0s - loss: 0.4063 - accuracy: 0.8141
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4060 - accuracy: 0.8145 - val_loss: 0.5823 - val_accuracy: 0.7131 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44472893373129174
Confusion Matrix :
 [[2984 1063]
 [1185 2862]]
Accuracy on test set:    0.7222634049913517
Sensitivity:    0.7071905114899926 	 Specificity:    0.7373362984927107
Precision  : 0.729171974522293
Area Under Curve:    0.7222634049913516
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5918 - accuracy: 0.6806 - val_loss: 0.5594 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5497 - accuracy: 0.7200 - val_loss: 0.5546 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5357 - accuracy: 0.7303 - val_loss: 0.5507 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5242 - accuracy: 0.7383 - val_loss: 0.5503 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7460 - val_loss: 0.5549 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.7525 - val_loss: 0.5529 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.7612 - val_loss: 0.5550 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.7687 - val_loss: 0.5581 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4695 - accuracy: 0.7769 - val_loss: 0.5634 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4563 - accuracy: 0.7846 - val_loss: 0.5645 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 11/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4427 - accuracy: 0.7955
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4437 - accuracy: 0.7949 - val_loss: 0.5700 - val_accuracy: 0.7146 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47919202327192373
Confusion Matrix :
 [[3028 1019]
 [1089 2958]]
Accuracy on test set:    0.739560168025698
Sensitivity:    0.7309117865085248 	 Specificity:    0.7482085495428713
Precision  : 0.7437767161176766
Area Under Curve:    0.739560168025698
(8094, 2560) (8094,)
Mean MCC = 0.4326 + 0.0206 and Mean AUC = 0.7159 + 0.0104
Mean Sensitivity = 0.7287 + 0.0277 and Mean Specificity = 0.7030 + 0.0324 and Mean Accuracy = 0.7159 + 0.0104
Mean Precision = 0.7112 + 0.0173





Seed   : 722654
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5861 - accuracy: 0.6864 - val_loss: 0.5623 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7242 - val_loss: 0.5574 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7352 - val_loss: 0.5533 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7409 - val_loss: 0.5639 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7491 - val_loss: 0.5532 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4999 - accuracy: 0.7541 - val_loss: 0.5517 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.7628 - val_loss: 0.5651 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7696 - val_loss: 0.5661 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4676 - accuracy: 0.7770 - val_loss: 0.5675 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4564 - accuracy: 0.7833 - val_loss: 0.5700 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4461 - accuracy: 0.7914 - val_loss: 0.5731 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4357 - accuracy: 0.7965 - val_loss: 0.5910 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 13/400
254/257 [============================>.] - ETA: 0s - loss: 0.4221 - accuracy: 0.8040
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4223 - accuracy: 0.8039 - val_loss: 0.5824 - val_accuracy: 0.7039 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41497408019136994
Confusion Matrix :
 [[2762 1286]
 [1084 2963]]
Accuracy on test set:    0.7072266831377394
Sensitivity:    0.7321472695824067 	 Specificity:    0.6823122529644269
Precision  : 0.697340550717816
Area Under Curve:    0.7072297612734169
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5864 - accuracy: 0.6864 - val_loss: 0.5596 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5419 - accuracy: 0.7250 - val_loss: 0.5542 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5239 - accuracy: 0.7376 - val_loss: 0.5534 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5102 - accuracy: 0.7476 - val_loss: 0.5576 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7557 - val_loss: 0.5558 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.7627 - val_loss: 0.5573 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7742 - val_loss: 0.5572 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4597 - accuracy: 0.7834 - val_loss: 0.5625 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4476 - accuracy: 0.7899 - val_loss: 0.5759 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4334 - accuracy: 0.7993 - val_loss: 0.5769 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4194 - accuracy: 0.8058 - val_loss: 0.5846 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4072 - accuracy: 0.8133 - val_loss: 0.5958 - val_accuracy: 0.7039 - lr: 0.0010
Epoch 13/400
244/257 [===========================>..] - ETA: 0s - loss: 0.3940 - accuracy: 0.8214
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3948 - accuracy: 0.8206 - val_loss: 0.5987 - val_accuracy: 0.7009 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4205621262181222
Confusion Matrix :
 [[2707 1341]
 [1010 3037]]
Accuracy on test set:    0.7095738109944411
Sensitivity:    0.7504324190758587 	 Specificity:    0.6687252964426877
Precision  : 0.6936957514846962
Area Under Curve:    0.7095788577592732
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.6814 - val_loss: 0.5547 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5432 - accuracy: 0.7226 - val_loss: 0.5481 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7338 - val_loss: 0.5441 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5148 - accuracy: 0.7435 - val_loss: 0.5426 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7502 - val_loss: 0.5478 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7607 - val_loss: 0.5467 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4806 - accuracy: 0.7688 - val_loss: 0.5513 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4692 - accuracy: 0.7782 - val_loss: 0.5535 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4576 - accuracy: 0.7830 - val_loss: 0.5586 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4452 - accuracy: 0.7916 - val_loss: 0.5624 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 11/400
249/257 [============================>.] - ETA: 0s - loss: 0.4322 - accuracy: 0.8002
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4329 - accuracy: 0.7999 - val_loss: 0.5617 - val_accuracy: 0.7112 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4145563277817155
Confusion Matrix :
 [[2778 1269]
 [1102 2946]]
Accuracy on test set:    0.7071031500926498
Sensitivity:    0.7277667984189723 	 Specificity:    0.6864343958487769
Precision  : 0.698932384341637
Area Under Curve:    0.7071005971338745
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5901 - accuracy: 0.6826 - val_loss: 0.5537 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 2/400

257/257 [==============================] - 1s 4ms/step - loss: 0.5486 - accuracy: 0.7205 - val_loss: 0.5460 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5328 - accuracy: 0.7306 - val_loss: 0.5398 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5220 - accuracy: 0.7379 - val_loss: 0.5401 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5125 - accuracy: 0.7451 - val_loss: 0.5423 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5038 - accuracy: 0.7514 - val_loss: 0.5429 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7594 - val_loss: 0.5481 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7682 - val_loss: 0.5555 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
256/257 [============================>.] - ETA: 0s - loss: 0.4728 - accuracy: 0.7735
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4728 - accuracy: 0.7735 - val_loss: 0.5502 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42192369011087566
Confusion Matrix :
 [[2843 1204]
 [1136 2912]]
Accuracy on test set:    0.7109326744904262
Sensitivity:    0.7193675889328063 	 Specificity:    0.7024956758092414
Precision  : 0.7074829931972789
Area Under Curve:    0.7109316323710239
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.6822 - val_loss: 0.5554 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7215 - val_loss: 0.5468 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7328 - val_loss: 0.5414 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7395 - val_loss: 0.5429 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7471 - val_loss: 0.5410 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7550 - val_loss: 0.5502 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.7664 - val_loss: 0.5505 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7743 - val_loss: 0.5536 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 9/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4588 - accuracy: 0.7829
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4586 - accuracy: 0.7830 - val_loss: 0.5677 - val_accuracy: 0.7205 - lr: 0.0010
253/253 [==============================] - 0s 761us/step
Independent Testing Matthews Correlation:  0.41803841702758937
Confusion Matrix :
 [[2647 1400]
 [ 965 3082]]
Accuracy on test set:    0.7078082530269335
Sensitivity:    0.7615517667407956 	 Specificity:    0.6540647393130714
Precision  : 0.6876394466755913
Area Under Curve:    0.7078082530269334
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5888 - accuracy: 0.6804 - val_loss: 0.5507 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7240 - val_loss: 0.5451 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7352 - val_loss: 0.5415 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7434 - val_loss: 0.5420 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7528 - val_loss: 0.5494 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7599 - val_loss: 0.5494 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4791 - accuracy: 0.7684 - val_loss: 0.5466 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4659 - accuracy: 0.7768
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4659 - accuracy: 0.7767 - val_loss: 0.5537 - val_accuracy: 0.7207 - lr: 0.0010
253/253 [==============================] - 0s 866us/step
Independent Testing Matthews Correlation:  0.42205380679693183
Confusion Matrix :
 [[2806 1241]
 [1099 2948]]
Accuracy on test set:    0.7108969607116382
Sensitivity:    0.7284408203607611 	 Specificity:    0.6933531010625155
Precision  : 0.7037479111959895
Area Under Curve:    0.7108969607116383
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5861 - accuracy: 0.6871 - val_loss: 0.5525 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7246 - val_loss: 0.5461 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7341 - val_loss: 0.5473 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7420 - val_loss: 0.5438 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7506 - val_loss: 0.5424 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7579 - val_loss: 0.5436 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7658 - val_loss: 0.5480 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7755 - val_loss: 0.5499 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4586 - accuracy: 0.7835 - val_loss: 0.5552 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4473 - accuracy: 0.7911 - val_loss: 0.5539 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4335 - accuracy: 0.7982 - val_loss: 0.5684 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4193 - accuracy: 0.8080 - val_loss: 0.5725 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 13/400
253/257 [============================>.] - ETA: 0s - loss: 0.4088 - accuracy: 0.8127
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4093 - accuracy: 0.8126 - val_loss: 0.5719 - val_accuracy: 0.7127 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40480655689817285
Confusion Matrix :
 [[2878 1169]
 [1240 2807]]
Accuracy on test set:    0.7023721275018532
Sensitivity:    0.6936001976772919 	 Specificity:    0.7111440573264146
Precision  : 0.7059859154929577
Area Under Curve:    0.7023721275018532
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5904 - accuracy: 0.6815 - val_loss: 0.5530 - val_accuracy: 0.7212 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5481 - accuracy: 0.7186 - val_loss: 0.5447 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5345 - accuracy: 0.7300 - val_loss: 0.5447 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.7377 - val_loss: 0.5430 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.7456 - val_loss: 0.5427 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.7555 - val_loss: 0.5424 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7633 - val_loss: 0.5436 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7724 - val_loss: 0.5447 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4593 - accuracy: 0.7835
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4596 - accuracy: 0.7833 - val_loss: 0.5473 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 917us/step
Independent Testing Matthews Correlation:  0.4380990185500571
Confusion Matrix :
 [[2842 1205]
 [1070 2977]]
Accuracy on test set:    0.7189276006918706
Sensitivity:    0.735606622189276 	 Specificity:    0.702248579194465
Precision  : 0.7118603538976567
Area Under Curve:    0.7189276006918704
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5884 - accuracy: 0.6837 - val_loss: 0.5569 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7209 - val_loss: 0.5506 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7331 - val_loss: 0.5452 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7404 - val_loss: 0.5470 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7485 - val_loss: 0.5455 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7583 - val_loss: 0.5488 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7668 - val_loss: 0.5513 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4729 - accuracy: 0.7741 - val_loss: 0.5566 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4582 - accuracy: 0.7828 - val_loss: 0.5585 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4466 - accuracy: 0.7909 - val_loss: 0.5640 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4353 - accuracy: 0.7988
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4350 - accuracy: 0.7988 - val_loss: 0.5645 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 803us/step
Independent Testing Matthews Correlation:  0.45370264172258573
Confusion Matrix :
 [[2917 1130]
 [1081 2966]]
Accuracy on test set:    0.7268346923647147
Sensitivity:    0.7328885594267358 	 Specificity:    0.7207808253026934
Precision  : 0.72412109375
Area Under Curve:    0.7268346923647145
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5868 - accuracy: 0.6840 - val_loss: 0.5612 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5466 - accuracy: 0.7218 - val_loss: 0.5576 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7318 - val_loss: 0.5566 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.7407 - val_loss: 0.5548 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7486 - val_loss: 0.5540 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7567 - val_loss: 0.5558 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7647 - val_loss: 0.5645 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4726 - accuracy: 0.7747 - val_loss: 0.5601 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4601 - accuracy: 0.7832
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4603 - accuracy: 0.7826 - val_loss: 0.5623 - val_accuracy: 0.7115 - lr: 0.0010
253/253 [==============================] - 0s 808us/step
Independent Testing Matthews Correlation:  0.47692112388656993
Confusion Matrix :
 [[3133  914]
 [1208 2839]]
Accuracy on test set:    0.7378304917222634
Sensitivity:    0.701507289350136 	 Specificity:    0.7741536940943909
Precision  : 0.7564614974686917
Area Under Curve:    0.7378304917222634
(8094, 2560) (8094,)
Mean MCC = 0.4286 + 0.0207 and Mean AUC = 0.7140 + 0.0103
Mean Sensitivity = 0.7283 + 0.0192 and Mean Specificity = 0.6996 + 0.0311 and Mean Accuracy = 0.7140 + 0.0103
Mean Precision = 0.7087 + 0.0186





Seed   : 410050
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5849 - accuracy: 0.6862 - val_loss: 0.5543 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5417 - accuracy: 0.7255 - val_loss: 0.5500 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5253 - accuracy: 0.7357 - val_loss: 0.5484 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5129 - accuracy: 0.7449 - val_loss: 0.5559 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5015 - accuracy: 0.7530 - val_loss: 0.5540 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7608 - val_loss: 0.5566 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7685 - val_loss: 0.5598 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4662 - accuracy: 0.7780
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4664 - accuracy: 0.7778 - val_loss: 0.5662 - val_accuracy: 0.7095 - lr: 0.0010
253/253 [==============================] - 0s 978us/step
Independent Testing Matthews Correlation:  0.41730975015080324
Confusion Matrix :
 [[2736 1312]
 [1050 2997]]
Accuracy on test set:    0.7082149474984558
Sensitivity:    0.7405485544848036 	 Specificity:    0.6758893280632411
Precision  : 0.6955210025527965
Area Under Curve:    0.7082189412740224
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5840 - accuracy: 0.6863 - val_loss: 0.5566 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7230 - val_loss: 0.5594 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7340 - val_loss: 0.5538 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7409 - val_loss: 0.5533 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7492 - val_loss: 0.5555 - val_accuracy: 0.7058 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7582 - val_loss: 0.5543 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.7655 - val_loss: 0.5573 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4723 - accuracy: 0.7750 - val_loss: 0.5621 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4595 - accuracy: 0.7828 - val_loss: 0.5724 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4467 - accuracy: 0.7913 - val_loss: 0.5732 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4344 - accuracy: 0.7975 - val_loss: 0.5739 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4226 - accuracy: 0.8056 - val_loss: 0.5836 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4087 - accuracy: 0.8123 - val_loss: 0.5907 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3975 - accuracy: 0.8218 - val_loss: 0.5952 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3864 - accuracy: 0.8254 - val_loss: 0.6136 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 16/400
255/257 [============================>.] - ETA: 0s - loss: 0.3750 - accuracy: 0.8323
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3751 - accuracy: 0.8321 - val_loss: 0.6159 - val_accuracy: 0.7035 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4119164971624542
Confusion Matrix :
 [[2647 1401]
 [ 988 3059]]
Accuracy on test set:    0.7048795552810376
Sensitivity:    0.755868544600939 	 Specificity:    0.6539031620553359
Precision  : 0.6858744394618834
Area Under Curve:    0.7048858533281375
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5906 - accuracy: 0.6814 - val_loss: 0.5501 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7205 - val_loss: 0.5427 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7343 - val_loss: 0.5565 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7412 - val_loss: 0.5426 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7491 - val_loss: 0.5484 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7559 - val_loss: 0.5449 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7619 - val_loss: 0.5489 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7716 - val_loss: 0.5545 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7796 - val_loss: 0.5531 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4509 - accuracy: 0.7865 - val_loss: 0.5567 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4371 - accuracy: 0.7953 - val_loss: 0.5654 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4250 - accuracy: 0.8026 - val_loss: 0.5666 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4125 - accuracy: 0.8099 - val_loss: 0.5862 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 14/400
255/257 [============================>.] - ETA: 0s - loss: 0.3986 - accuracy: 0.8179
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3985 - accuracy: 0.8179 - val_loss: 0.5941 - val_accuracy: 0.7205 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4194158699611958
Confusion Matrix :
 [[2892 1155]
 [1195 2853]]
Accuracy on test set:    0.7096973440395306
Sensitivity:    0.704792490118577 	 Specificity:    0.7146034099332839
Precision  : 0.7118263473053892
Area Under Curve:    0.7096979500259304
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5895 - accuracy: 0.6840 - val_loss: 0.5441 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7212 - val_loss: 0.5356 - val_accuracy: 0.7315 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5324 - accuracy: 0.7327 - val_loss: 0.5387 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.7394 - val_loss: 0.5392 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7486 - val_loss: 0.5355 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7582 - val_loss: 0.5427 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4793 - accuracy: 0.7677
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4794 - accuracy: 0.7676 - val_loss: 0.5451 - val_accuracy: 0.7245 - lr: 0.0010
253/253 [==============================] - 0s 785us/step
Independent Testing Matthews Correlation:  0.42171264829544697
Confusion Matrix :
 [[3048  999]
 [1348 2700]]
Accuracy on test set:    0.7100679431747993
Sensitivity:    0.6669960474308301 	 Specificity:    0.7531504818383988
Precision  : 0.7299270072992701
Area Under Curve:    0.7100732646346144
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5899 - accuracy: 0.6822 - val_loss: 0.5533 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7236 - val_loss: 0.5480 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7330 - val_loss: 0.5525 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7412 - val_loss: 0.5496 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7497 - val_loss: 0.5546 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7581 - val_loss: 0.5514 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400

257/257 [==============================] - 1s 4ms/step - loss: 0.4841 - accuracy: 0.7669 - val_loss: 0.5516 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7744 - val_loss: 0.5560 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4589 - accuracy: 0.7824 - val_loss: 0.5579 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4450 - accuracy: 0.7916 - val_loss: 0.5616 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4306 - accuracy: 0.7999
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4314 - accuracy: 0.7994 - val_loss: 0.5722 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4106003785986374
Confusion Matrix :
 [[2762 1285]
 [1102 2945]]
Accuracy on test set:    0.7050901902643933
Sensitivity:    0.7276995305164319 	 Specificity:    0.6824808500123548
Precision  : 0.6962174940898345
Area Under Curve:    0.7050901902643933
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5917 - accuracy: 0.6812 - val_loss: 0.5533 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7215 - val_loss: 0.5501 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7329 - val_loss: 0.5509 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7401 - val_loss: 0.5484 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7481 - val_loss: 0.5532 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 6/400
252/257 [============================>.] - ETA: 0s - loss: 0.4976 - accuracy: 0.7554
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7557 - val_loss: 0.5516 - val_accuracy: 0.7175 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42352770936461975
Confusion Matrix :
 [[2759 1288]
 [1048 2999]]
Accuracy on test set:    0.711391153941191
Sensitivity:    0.7410427477143563 	 Specificity:    0.6817395601680257
Precision  : 0.6995567996267786
Area Under Curve:    0.711391153941191
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5865 - accuracy: 0.6854 - val_loss: 0.5539 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7222 - val_loss: 0.5483 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7338 - val_loss: 0.5478 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7425 - val_loss: 0.5478 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7515 - val_loss: 0.5512 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7592 - val_loss: 0.5576 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7668 - val_loss: 0.5550 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4689 - accuracy: 0.7769
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7769 - val_loss: 0.5818 - val_accuracy: 0.7109 - lr: 0.0010
253/253 [==============================] - 0s 851us/step
Independent Testing Matthews Correlation:  0.4233059559565944
Confusion Matrix :
 [[2515 1532]
 [ 828 3219]]
Accuracy on test set:    0.7084259945638745
Sensitivity:    0.7954040029651593 	 Specificity:    0.6214479861625896
Precision  : 0.6775415701957482
Area Under Curve:    0.7084259945638745
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5849 - accuracy: 0.6866 - val_loss: 0.5495 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7226 - val_loss: 0.5469 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7335 - val_loss: 0.5425 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7417 - val_loss: 0.5625 - val_accuracy: 0.7017 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7474 - val_loss: 0.5450 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7560 - val_loss: 0.5429 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7664 - val_loss: 0.5532 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4725 - accuracy: 0.7731
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4725 - accuracy: 0.7731 - val_loss: 0.5508 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 881us/step
Independent Testing Matthews Correlation:  0.44357613164965887
Confusion Matrix :
 [[2993 1054]
 [1199 2848]]
Accuracy on test set:    0.7216456634544107
Sensitivity:    0.7037311588831233 	 Specificity:    0.739560168025698
Precision  : 0.7298821117375704
Area Under Curve:    0.7216456634544106
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5917 - accuracy: 0.6805 - val_loss: 0.5633 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7192 - val_loss: 0.5522 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5337 - accuracy: 0.7299 - val_loss: 0.5471 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7394 - val_loss: 0.5487 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7494 - val_loss: 0.5534 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7561 - val_loss: 0.5518 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4848 - accuracy: 0.7647 - val_loss: 0.5534 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4737 - accuracy: 0.7721
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7715 - val_loss: 0.5553 - val_accuracy: 0.7115 - lr: 0.0010
253/253 [==============================] - 0s 958us/step
Independent Testing Matthews Correlation:  0.4705818843188776
Confusion Matrix :
 [[3077  970]
 [1175 2872]]
Accuracy on test set:    0.734988880652335
Sensitivity:    0.7096614776377563 	 Specificity:    0.7603162836669137
Precision  : 0.7475273295158772
Area Under Curve:    0.734988880652335
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5939 - accuracy: 0.6798 - val_loss: 0.5570 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5497 - accuracy: 0.7202 - val_loss: 0.5467 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5354 - accuracy: 0.7301 - val_loss: 0.5448 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5244 - accuracy: 0.7372 - val_loss: 0.5451 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.7456 - val_loss: 0.5456 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5010 - accuracy: 0.7548 - val_loss: 0.5506 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4900 - accuracy: 0.7620 - val_loss: 0.5518 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4774 - accuracy: 0.7713 - val_loss: 0.5546 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7797 - val_loss: 0.5532 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4523 - accuracy: 0.7870
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4520 - accuracy: 0.7872 - val_loss: 0.5622 - val_accuracy: 0.7111 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46502860341259394
Confusion Matrix :
 [[3135  912]
 [1260 2787]]
Accuracy on test set:    0.7316530763528539
Sensitivity:    0.6886582653817642 	 Specificity:    0.7746478873239436
Precision  : 0.7534468775344688
Area Under Curve:    0.7316530763528539
(8094, 2560) (8094,)
Mean MCC = 0.4307 + 0.0205 and Mean AUC = 0.7146 + 0.0104
Mean Sensitivity = 0.7234 + 0.0349 and Mean Specificity = 0.7058 + 0.0480 and Mean Accuracy = 0.7146 + 0.0104
Mean Precision = 0.7127 + 0.0248





Seed   : 605699
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5842 - accuracy: 0.6876 - val_loss: 0.5610 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5404 - accuracy: 0.7257 - val_loss: 0.5545 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5253 - accuracy: 0.7360 - val_loss: 0.5511 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5128 - accuracy: 0.7458 - val_loss: 0.5542 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.7519 - val_loss: 0.5507 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7619 - val_loss: 0.5567 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.7691 - val_loss: 0.5599 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4663 - accuracy: 0.7778 - val_loss: 0.5602 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4541 - accuracy: 0.7854 - val_loss: 0.5636 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4409 - accuracy: 0.7926 - val_loss: 0.5728 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4281 - accuracy: 0.8016 - val_loss: 0.5731 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 12/400
249/257 [============================>.] - ETA: 0s - loss: 0.4140 - accuracy: 0.8087
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4141 - accuracy: 0.8088 - val_loss: 0.5909 - val_accuracy: 0.7090 - lr: 0.0010
253/253 [==============================] - 0s 861us/step
Independent Testing Matthews Correlation:  0.39721131377031316
Confusion Matrix :
 [[2699 1349]
 [1094 2953]]
Accuracy on test set:    0.6982087708462014
Sensitivity:    0.729676303434643 	 Specificity:    0.6667490118577075
Precision  : 0.6864249186424919
Area Under Curve:    0.6982126576461752
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5888 - accuracy: 0.6830 - val_loss: 0.5673 - val_accuracy: 0.7028 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7242 - val_loss: 0.5536 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.7352 - val_loss: 0.5578 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7430 - val_loss: 0.5518 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7515 - val_loss: 0.5528 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7588 - val_loss: 0.5530 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7675 - val_loss: 0.5532 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7735 - val_loss: 0.5609 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4603 - accuracy: 0.7829 - val_loss: 0.5667 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4490 - accuracy: 0.7905 - val_loss: 0.5669 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4357 - accuracy: 0.7970
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4360 - accuracy: 0.7969 - val_loss: 0.5699 - val_accuracy: 0.7091 - lr: 0.0010
253/253 [==============================] - 0s 739us/step
Independent Testing Matthews Correlation:  0.41523191233268664
Confusion Matrix :
 [[2892 1156]
 [1211 2836]]
Accuracy on test set:    0.707597282273008
Sensitivity:    0.7007659995058068 	 Specificity:    0.7144268774703557
Precision  : 0.7104208416833667
Area Under Curve:    0.7075964384880812
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5854 - accuracy: 0.6856 - val_loss: 0.5518 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7221 - val_loss: 0.5429 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7342 - val_loss: 0.5422 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7426 - val_loss: 0.5437 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7485 - val_loss: 0.5447 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7568 - val_loss: 0.5430 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4846 - accuracy: 0.7656
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.7656 - val_loss: 0.5512 - val_accuracy: 0.7143 - lr: 0.0010

253/253 [==============================] - 0s 735us/step
Independent Testing Matthews Correlation:  0.44049204031865774
Confusion Matrix :
 [[2670 1377]
 [ 900 3148]]
Accuracy on test set:    0.7187152563310686
Sensitivity:    0.7776679841897233 	 Specificity:    0.6597479614529281
Precision  : 0.6956906077348066
Area Under Curve:    0.7187079728213256
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5869 - accuracy: 0.6836 - val_loss: 0.5503 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7221 - val_loss: 0.5432 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5267 - accuracy: 0.7336 - val_loss: 0.5415 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7441 - val_loss: 0.5488 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7512 - val_loss: 0.5424 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.7602 - val_loss: 0.5498 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4792 - accuracy: 0.7682 - val_loss: 0.5485 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4657 - accuracy: 0.7782 - val_loss: 0.5548 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4522 - accuracy: 0.7867 - val_loss: 0.5526 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4410 - accuracy: 0.7936
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4409 - accuracy: 0.7937 - val_loss: 0.5592 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 751us/step
Independent Testing Matthews Correlation:  0.4251183570871283
Confusion Matrix :
 [[2855 1192]
 [1135 2913]]
Accuracy on test set:    0.7125386040765905
Sensitivity:    0.7196146245059288 	 Specificity:    0.705460835186558
Precision  : 0.7096224116930573
Area Under Curve:    0.7125377298462432
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5889 - accuracy: 0.6819 - val_loss: 0.5573 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7215 - val_loss: 0.5476 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5270 - accuracy: 0.7328 - val_loss: 0.5435 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7428 - val_loss: 0.5436 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.7518 - val_loss: 0.5444 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7580 - val_loss: 0.5455 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7664 - val_loss: 0.5463 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4726 - accuracy: 0.7735 - val_loss: 0.5532 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4607 - accuracy: 0.7810 - val_loss: 0.5582 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4461 - accuracy: 0.7911
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4467 - accuracy: 0.7908 - val_loss: 0.5609 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44101945829804673
Confusion Matrix :
 [[2824 1223]
 [1041 3006]]
Accuracy on test set:    0.7202866320731406
Sensitivity:    0.742772424017791 	 Specificity:    0.6978008401284902
Precision  : 0.7108063371955545
Area Under Curve:    0.7202866320731407
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5868 - accuracy: 0.6850 - val_loss: 0.5540 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7211 - val_loss: 0.5509 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7326 - val_loss: 0.5460 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7422 - val_loss: 0.5459 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7491 - val_loss: 0.5507 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7590 - val_loss: 0.5491 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7664 - val_loss: 0.5500 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 8/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4706 - accuracy: 0.7751
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7749 - val_loss: 0.5515 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 776us/step
Independent Testing Matthews Correlation:  0.42402463880040836
Confusion Matrix :
 [[2893 1154]
 [1177 2870]]
Accuracy on test set:    0.712008895478132
Sensitivity:    0.7091672844082036 	 Specificity:    0.7148505065480603
Precision  : 0.713220675944334
Area Under Curve:    0.712008895478132
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5853 - accuracy: 0.6862 - val_loss: 0.5497 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7207 - val_loss: 0.5448 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7355 - val_loss: 0.5419 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7436 - val_loss: 0.5436 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7505 - val_loss: 0.5446 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7584 - val_loss: 0.5479 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7667 - val_loss: 0.5482 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7762 - val_loss: 0.5545 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4583 - accuracy: 0.7835 - val_loss: 0.5518 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4461 - accuracy: 0.7933 - val_loss: 0.5579 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4355 - accuracy: 0.7966 - val_loss: 0.5562 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4222 - accuracy: 0.8058 - val_loss: 0.5739 - val_accuracy: 0.7196 - lr: 0.0010

Epoch 13/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4103 - accuracy: 0.8132
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4100 - accuracy: 0.8133 - val_loss: 0.5778 - val_accuracy: 0.7175 - lr: 0.0010
253/253 [==============================] - 0s 697us/step
Independent Testing Matthews Correlation:  0.4196715471253686
Confusion Matrix :
 [[2828 1219]
 [1130 2917]]
Accuracy on test set:    0.7097850259451446
Sensitivity:    0.7207808253026934 	 Specificity:    0.6987892265875958
Precision  : 0.7052707930367504
Area Under Curve:    0.7097850259451445
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5865 - accuracy: 0.6862 - val_loss: 0.5447 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7214 - val_loss: 0.5440 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7318 - val_loss: 0.5412 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7407 - val_loss: 0.5372 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7475 - val_loss: 0.5410 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4999 - accuracy: 0.7539 - val_loss: 0.5426 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4886 - accuracy: 0.7627 - val_loss: 0.5423 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.7692 - val_loss: 0.5443 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4679 - accuracy: 0.7776 - val_loss: 0.5431 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4542 - accuracy: 0.7872 - val_loss: 0.5525 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4425 - accuracy: 0.7935 - val_loss: 0.5562 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4269 - accuracy: 0.8048 - val_loss: 0.5630 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4159 - accuracy: 0.8098 - val_loss: 0.5715 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 14/400
250/257 [============================>.] - ETA: 0s - loss: 0.4043 - accuracy: 0.8164
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4044 - accuracy: 0.8166 - val_loss: 0.5757 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 851us/step
Independent Testing Matthews Correlation:  0.4232932489414269
Confusion Matrix :
 [[2862 1185]
 [1149 2898]]
Accuracy on test set:    0.7116382505559674
Sensitivity:    0.7160859896219421 	 Specificity:    0.7071905114899926
Precision  : 0.7097722263041881
Area Under Curve:    0.7116382505559674
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.6014 - accuracy: 0.6706 - val_loss: 0.5543 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5514 - accuracy: 0.7198 - val_loss: 0.5481 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5349 - accuracy: 0.7298 - val_loss: 0.5447 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5220 - accuracy: 0.7394 - val_loss: 0.5413 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5112 - accuracy: 0.7462 - val_loss: 0.5433 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7564 - val_loss: 0.5492 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7671 - val_loss: 0.5446 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4699 - accuracy: 0.7764 - val_loss: 0.5501 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4573 - accuracy: 0.7860 - val_loss: 0.5540 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4420 - accuracy: 0.7937
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4424 - accuracy: 0.7937 - val_loss: 0.5606 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 795us/step
Independent Testing Matthews Correlation:  0.45011735979065454
Confusion Matrix :
 [[2987 1060]
 [1166 2881]]
Accuracy on test set:    0.7249814677538917
Sensitivity:    0.7118853471707438 	 Specificity:    0.7380775883370397
Precision  : 0.7310327328089318
Area Under Curve:    0.7249814677538919
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5932 - accuracy: 0.6826 - val_loss: 0.5560 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5514 - accuracy: 0.7184 - val_loss: 0.5482 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5352 - accuracy: 0.7298 - val_loss: 0.5461 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5242 - accuracy: 0.7398 - val_loss: 0.5492 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5116 - accuracy: 0.7451 - val_loss: 0.5468 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7554 - val_loss: 0.5504 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4871 - accuracy: 0.7646 - val_loss: 0.5520 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7714 - val_loss: 0.5515 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4630 - accuracy: 0.7799 - val_loss: 0.5587 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4506 - accuracy: 0.7884 - val_loss: 0.5621 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4363 - accuracy: 0.7957 - val_loss: 0.5656 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 12/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4225 - accuracy: 0.8052
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4231 - accuracy: 0.8049 - val_loss: 0.5691 - val_accuracy: 0.7132 - lr: 0.0010
253/253 [==============================] - 0s 918us/step
Independent Testing Matthews Correlation:  0.4804779994749465
Confusion Matrix :
 [[3131  916]
 [1191 2856]]
Accuracy on test set:    0.7396837163330863
Sensitivity:    0.7057079318013343 	 Specificity:    0.7736595008648381
Precision  : 0.7571580063626723
Area Under Curve:    0.7396837163330863
(8094, 2560) (8094,)
Mean MCC = 0.4317 + 0.0216 and Mean AUC = 0.7155 + 0.0107
Mean Sensitivity = 0.7234 + 0.0214 and Mean Specificity = 0.7077 + 0.0309 and Mean Accuracy = 0.7155 + 0.0107
Mean Precision = 0.7129 + 0.0184





Seed   : 882183
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5881 - accuracy: 0.6849 - val_loss: 0.5501 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5420 - accuracy: 0.7244 - val_loss: 0.5431 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5256 - accuracy: 0.7371 - val_loss: 0.5444 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7439 - val_loss: 0.5473 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.7543 - val_loss: 0.5507 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.7624 - val_loss: 0.5516 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4757 - accuracy: 0.7705 - val_loss: 0.5467 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4639 - accuracy: 0.7783
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4638 - accuracy: 0.7786 - val_loss: 0.5604 - val_accuracy: 0.7139 - lr: 0.0010
253/253 [==============================] - 0s 856us/step
Independent Testing Matthews Correlation:  0.39554105516033083
Confusion Matrix :
 [[2589 1459]
 [ 998 3049]]
Accuracy on test set:    0.6964793082149475
Sensitivity:    0.7533975784531752 	 Specificity:    0.6395750988142292
Precision  : 0.6763531499556344
Area Under Curve:    0.6964863386337021
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5854 - accuracy: 0.6848 - val_loss: 0.5559 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7241 - val_loss: 0.5490 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.7362 - val_loss: 0.5428 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7415 - val_loss: 0.5467 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7483 - val_loss: 0.5439 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7579 - val_loss: 0.5451 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4858 - accuracy: 0.7641 - val_loss: 0.5522 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4756 - accuracy: 0.7717 - val_loss: 0.5481 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7792 - val_loss: 0.5544 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4528 - accuracy: 0.7869
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4530 - accuracy: 0.7868 - val_loss: 0.5592 - val_accuracy: 0.7170 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4245207063065827
Confusion Matrix :
 [[2731 1317]
 [1017 3030]]
Accuracy on test set:    0.7116738727609636
Sensitivity:    0.748702742772424 	 Specificity:    0.6746541501976284
Precision  : 0.6970324361628709
Area Under Curve:    0.7116784464850262
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5886 - accuracy: 0.6834 - val_loss: 0.5411 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7218 - val_loss: 0.5360 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7326 - val_loss: 0.5330 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7408 - val_loss: 0.5358 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7478 - val_loss: 0.5317 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7557 - val_loss: 0.5337 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4844 - accuracy: 0.7639
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7642 - val_loss: 0.5486 - val_accuracy: 0.7268 - lr: 0.0010
253/253 [==============================] - 0s 911us/step
Independent Testing Matthews Correlation:  0.4117967816860647
Confusion Matrix :
 [[2595 1452]
 [ 942 3106]]
Accuracy on test set:    0.7042618900555899
Sensitivity:    0.767292490118577 	 Specificity:    0.6412157153446998
Precision  : 0.6814392277314612
Area Under Curve:    0.7042541027316385
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5889 - accuracy: 0.6815 - val_loss: 0.5511 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7201 - val_loss: 0.5306 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7306 - val_loss: 0.5304 - val_accuracy: 0.7311 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7399 - val_loss: 0.5283 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5102 - accuracy: 0.7467 - val_loss: 0.5287 - val_accuracy: 0.7329 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5000 - accuracy: 0.7545 - val_loss: 0.5296 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7611 - val_loss: 0.5277 - val_accuracy: 0.7332 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4758 - accuracy: 0.7703 - val_loss: 0.5341 - val_accuracy: 0.7323 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4638 - accuracy: 0.7789 - val_loss: 0.5356 - val_accuracy: 0.7340 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4507 - accuracy: 0.7868 - val_loss: 0.5411 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4383 - accuracy: 0.7949 - val_loss: 0.5444 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4260 - accuracy: 0.8032 - val_loss: 0.5489 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4131 - accuracy: 0.8106 - val_loss: 0.5598 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 14/400
251/257 [============================>.] - ETA: 0s - loss: 0.4019 - accuracy: 0.8171
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4020 - accuracy: 0.8171 - val_loss: 0.5653 - val_accuracy: 0.7311 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.418424181585918
Confusion Matrix :
 [[2851 1196]
 [1158 2890]]
Accuracy on test set:    0.7092032118591723
Sensitivity:    0.7139328063241107 	 Specificity:    0.7044724487274524
Precision  : 0.7072931962799804
Area Under Curve:    0.7092026275257817
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5843 - accuracy: 0.6877 - val_loss: 0.5491 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7233 - val_loss: 0.5422 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7331 - val_loss: 0.5399 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7418 - val_loss: 0.5418 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7506 - val_loss: 0.5416 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7573 - val_loss: 0.5424 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.7665 - val_loss: 0.5434 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4696 - accuracy: 0.7769
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4699 - accuracy: 0.7767 - val_loss: 0.5596 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 858us/step
Independent Testing Matthews Correlation:  0.4276446255670722
Confusion Matrix :
 [[2551 1496]
 [ 843 3204]]
Accuracy on test set:    0.7110205090190265
Sensitivity:    0.7916975537435137 	 Specificity:    0.6303434642945391
Precision  : 0.6817021276595745
Area Under Curve:    0.7110205090190265
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5859 - accuracy: 0.6853 - val_loss: 0.5592 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5418 - accuracy: 0.7224 - val_loss: 0.5438 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7349 - val_loss: 0.5428 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7420 - val_loss: 0.5452 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7496 - val_loss: 0.5427 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7588 - val_loss: 0.5446 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7660 - val_loss: 0.5423 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7731 - val_loss: 0.5448 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4607 - accuracy: 0.7833 - val_loss: 0.5509 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4487 - accuracy: 0.7890 - val_loss: 0.5553 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 11/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4355 - accuracy: 0.7979
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4364 - accuracy: 0.7972 - val_loss: 0.5558 - val_accuracy: 0.7260 - lr: 0.0010
253/253 [==============================] - 0s 892us/step
Independent Testing Matthews Correlation:  0.4293221089880552
Confusion Matrix :
 [[2745 1302]
 [1012 3035]]
Accuracy on test set:    0.7141092167037312
Sensitivity:    0.7499382258463059 	 Specificity:    0.6782802075611564
Precision  : 0.6997924832833756
Area Under Curve:    0.7141092167037313
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5891 - accuracy: 0.6820 - val_loss: 0.5515 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7219 - val_loss: 0.5483 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7327 - val_loss: 0.5411 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7407 - val_loss: 0.5408 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7503 - val_loss: 0.5416 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7553 - val_loss: 0.5422 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7653 - val_loss: 0.5451 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7742 - val_loss: 0.5490 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4590 - accuracy: 0.7811 - val_loss: 0.5518 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4440 - accuracy: 0.7913
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4444 - accuracy: 0.7910 - val_loss: 0.5647 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41508740045409226
Confusion Matrix :
 [[2744 1303]
 [1067 2980]]
Accuracy on test set:    0.7071905114899926
Sensitivity:    0.7363479120336052 	 Specificity:    0.6780331109463801
Precision  : 0.6957739901937894
Area Under Curve:    0.7071905114899926
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5885 - accuracy: 0.6860 - val_loss: 0.5510 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7223 - val_loss: 0.5443 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7328 - val_loss: 0.5406 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7421 - val_loss: 0.5454 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7509 - val_loss: 0.5418 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7590 - val_loss: 0.5423 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7668 - val_loss: 0.5443 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.7761 - val_loss: 0.5462 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4578 - accuracy: 0.7832 - val_loss: 0.5478 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4442 - accuracy: 0.7910 - val_loss: 0.5538 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
252/257 [============================>.] - ETA: 0s - loss: 0.4347 - accuracy: 0.7969
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4347 - accuracy: 0.7970 - val_loss: 0.5593 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 951us/step
Independent Testing Matthews Correlation:  0.4453958456225237
Confusion Matrix :
 [[2841 1206]
 [1040 3007]]
Accuracy on test set:    0.722510501606128

Sensitivity:    0.7430195206325674 	 Specificity:    0.7020014825796886
Precision  : 0.713743175884168
Area Under Curve:    0.7225105016061281
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5877 - accuracy: 0.6833 - val_loss: 0.5484 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7206 - val_loss: 0.5416 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7315 - val_loss: 0.5421 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5211 - accuracy: 0.7383 - val_loss: 0.5417 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5110 - accuracy: 0.7464 - val_loss: 0.5407 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5020 - accuracy: 0.7521 - val_loss: 0.5456 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7597 - val_loss: 0.5390 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7687 - val_loss: 0.5503 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4711 - accuracy: 0.7746 - val_loss: 0.5499 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4596 - accuracy: 0.7819 - val_loss: 0.5496 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4480 - accuracy: 0.7904 - val_loss: 0.5635 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 12/400
249/257 [============================>.] - ETA: 0s - loss: 0.4347 - accuracy: 0.7975
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4351 - accuracy: 0.7973 - val_loss: 0.5626 - val_accuracy: 0.7227 - lr: 0.0010
253/253 [==============================] - 0s 839us/step
Independent Testing Matthews Correlation:  0.4682030525396379
Confusion Matrix :
 [[2796 1251]
 [ 908 3139]]
Accuracy on test set:    0.7332592043489005
Sensitivity:    0.7756362737830492 	 Specificity:    0.6908821349147517
Precision  : 0.7150341685649203
Area Under Curve:    0.7332592043489004
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5904 - accuracy: 0.6828 - val_loss: 0.5581 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5488 - accuracy: 0.7200 - val_loss: 0.5441 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5336 - accuracy: 0.7313 - val_loss: 0.5450 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7403 - val_loss: 0.5465 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7471 - val_loss: 0.5448 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7548 - val_loss: 0.5442 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7655 - val_loss: 0.5450 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4726 - accuracy: 0.7740 - val_loss: 0.5519 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4590 - accuracy: 0.7838 - val_loss: 0.5528 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4447 - accuracy: 0.7918 - val_loss: 0.5561 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4308 - accuracy: 0.8007 - val_loss: 0.5612 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 12/400
250/257 [============================>.] - ETA: 0s - loss: 0.4180 - accuracy: 0.8088
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4185 - accuracy: 0.8086 - val_loss: 0.5651 - val_accuracy: 0.7171 - lr: 0.0010
253/253 [==============================] - 0s 773us/step
Independent Testing Matthews Correlation:  0.46378575500621577
Confusion Matrix :
 [[3053  994]
 [1178 2869]]
Accuracy on test set:    0.7316530763528539
Sensitivity:    0.7089201877934272 	 Specificity:    0.7543859649122807
Precision  : 0.7426870308050738
Area Under Curve:    0.7316530763528539
(8094, 2560) (8094,)
Mean MCC = 0.4300 + 0.0218 and Mean AUC = 0.7141 + 0.0111
Mean Sensitivity = 0.7489 + 0.0243 and Mean Specificity = 0.6794 + 0.0352 and Mean Accuracy = 0.7141 + 0.0111
Mean Precision = 0.7011 + 0.0188





Seed   : 296611
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5902 - accuracy: 0.6822 - val_loss: 0.5598 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7241 - val_loss: 0.5545 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5269 - accuracy: 0.7337 - val_loss: 0.5558 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7427 - val_loss: 0.5522 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7539 - val_loss: 0.5506 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4899 - accuracy: 0.7619 - val_loss: 0.5526 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.7696 - val_loss: 0.5559 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4646 - accuracy: 0.7789 - val_loss: 0.5603 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4504 - accuracy: 0.7877 - val_loss: 0.5731 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4371 - accuracy: 0.7959 - val_loss: 0.5756 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 11/400
254/257 [============================>.] - ETA: 0s - loss: 0.4229 - accuracy: 0.8060
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4228 - accuracy: 0.8061 - val_loss: 0.5761 - val_accuracy: 0.7126 - lr: 0.0010
253/253 [==============================] - 0s 912us/step
Independent Testing Matthews Correlation:  0.4158892953931754
Confusion Matrix :
 [[2803 1245]
 [1120 2927]]
Accuracy on test set:    0.7078443483631871
Sensitivity:    0.7232517914504571 	 Specificity:    0.6924407114624506
Precision  : 0.701581975071908
Area Under Curve:    0.7078462514564539
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5867 - accuracy: 0.6860 - val_loss: 0.5565 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7230 - val_loss: 0.5539 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7333 - val_loss: 0.5492 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7425 - val_loss: 0.5480 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7493 - val_loss: 0.5545 - val_accuracy: 0.7104 - lr: 0.0010

Epoch 6/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4970 - accuracy: 0.7576
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.7573 - val_loss: 0.5509 - val_accuracy: 0.7095 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42385151873154864
Confusion Matrix :
 [[2896 1152]
 [1180 2867]]
Accuracy on test set:    0.7119209388511427
Sensitivity:    0.7084259945638745 	 Specificity:    0.7154150197628458
Precision  : 0.713361532719582
Area Under Curve:    0.7119205071633601
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5897 - accuracy: 0.6809 - val_loss: 0.5464 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7229 - val_loss: 0.5395 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7307 - val_loss: 0.5366 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7390 - val_loss: 0.5373 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7471 - val_loss: 0.5379 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.7545 - val_loss: 0.5378 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4879 - accuracy: 0.7625
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7629 - val_loss: 0.5481 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 919us/step
Independent Testing Matthews Correlation:  0.41492597743996384
Confusion Matrix :
 [[2518 1529]
 [ 862 3186]]
Accuracy on test set:    0.7046324891908585
Sensitivity:    0.7870553359683794 	 Specificity:    0.6221892760069188
Precision  : 0.6757158006362672
Area Under Curve:    0.7046223059876491
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5884 - accuracy: 0.6833 - val_loss: 0.5515 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7201 - val_loss: 0.5393 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7320 - val_loss: 0.5363 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7394 - val_loss: 0.5357 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5118 - accuracy: 0.7451 - val_loss: 0.5363 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5028 - accuracy: 0.7526 - val_loss: 0.5369 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7600 - val_loss: 0.5398 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7698 - val_loss: 0.5449 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4664 - accuracy: 0.7787
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4663 - accuracy: 0.7791 - val_loss: 0.5528 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 824us/step
Independent Testing Matthews Correlation:  0.41223464536827314
Confusion Matrix :
 [[2867 1180]
 [1199 2849]]
Accuracy on test set:    0.7061148857319333
Sensitivity:    0.7038043478260869 	 Specificity:    0.7084259945638745
Precision  : 0.7071233556713825
Area Under Curve:    0.7061151711949807
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5875 - accuracy: 0.6852 - val_loss: 0.5455 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7213 - val_loss: 0.5405 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7339 - val_loss: 0.5355 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7397 - val_loss: 0.5343 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7487 - val_loss: 0.5340 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7569 - val_loss: 0.5354 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.7639 - val_loss: 0.5435 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4747 - accuracy: 0.7708
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4752 - accuracy: 0.7705 - val_loss: 0.5370 - val_accuracy: 0.7271 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42520521891696333
Confusion Matrix :
 [[2767 1280]
 [1049 2998]]
Accuracy on test set:    0.7122559920929084
Sensitivity:    0.7407956510995799 	 Specificity:    0.6837163330862367
Precision  : 0.7007947639083684
Area Under Curve:    0.7122559920929084
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5868 - accuracy: 0.6857 - val_loss: 0.5504 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7229 - val_loss: 0.5504 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7309 - val_loss: 0.5482 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7406 - val_loss: 0.5399 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7484 - val_loss: 0.5439 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7574 - val_loss: 0.5414 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.7642 - val_loss: 0.5543 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7711 - val_loss: 0.5477 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4631 - accuracy: 0.7808 - val_loss: 0.5469 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4507 - accuracy: 0.7894 - val_loss: 0.5519 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4368 - accuracy: 0.7993 - val_loss: 0.5604 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4235 - accuracy: 0.8065 - val_loss: 0.5650 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4120 - accuracy: 0.8117 - val_loss: 0.5570 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 14/400
243/257 [===========================>..] - ETA: 0s - loss: 0.3983 - accuracy: 0.8206
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.3992 - accuracy: 0.8200 - val_loss: 0.5729 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 996us/step
Independent Testing Matthews Correlation:  0.41728160811448967
Confusion Matrix :
 [[2646 1401]
 [ 967 3080]]
Accuracy on test set:    0.707437608104769
Sensitivity:    0.7610575735112429 	 Specificity:    0.653817642698295
Precision  : 0.6873465744253515
Area Under Curve:    0.707437608104769
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5897 - accuracy: 0.6822 - val_loss: 0.5502 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7221 - val_loss: 0.5411 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7322 - val_loss: 0.5386 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7396 - val_loss: 0.5379 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7488 - val_loss: 0.5373 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7561 - val_loss: 0.5381 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7644 - val_loss: 0.5423 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.7721 - val_loss: 0.5469 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.7824 - val_loss: 0.5489 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4468 - accuracy: 0.7915
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4468 - accuracy: 0.7915 - val_loss: 0.5628 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 683us/step
Independent Testing Matthews Correlation:  0.41792954577323627
Confusion Matrix :
 [[2740 1307]
 [1052 2995]]
Accuracy on test set:    0.7085495428712627
Sensitivity:    0.7400543612552508 	 Specificity:    0.6770447244872745
Precision  : 0.696187819618782
Area Under Curve:    0.7085495428712628
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5840 - accuracy: 0.6879 - val_loss: 0.5473 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7232 - val_loss: 0.5429 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7341 - val_loss: 0.5381 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7432 - val_loss: 0.5395 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7501 - val_loss: 0.5470 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4911 - accuracy: 0.7606 - val_loss: 0.5369 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4791 - accuracy: 0.7701 - val_loss: 0.5431 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4658 - accuracy: 0.7775 - val_loss: 0.5506 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4550 - accuracy: 0.7847
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4552 - accuracy: 0.7847 - val_loss: 0.5491 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 793us/step
Independent Testing Matthews Correlation:  0.4393379017828402
Confusion Matrix :
 [[2914 1133]
 [1136 2911]]
Accuracy on test set:    0.7196688905361996
Sensitivity:    0.7192982456140351 	 Specificity:    0.7200395354583642
Precision  : 0.7198318496538081
Area Under Curve:    0.7196688905361996
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5930 - accuracy: 0.6814 - val_loss: 0.5642 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5508 - accuracy: 0.7186 - val_loss: 0.5481 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5347 - accuracy: 0.7289 - val_loss: 0.5456 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5222 - accuracy: 0.7377 - val_loss: 0.5448 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5125 - accuracy: 0.7454 - val_loss: 0.5444 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5020 - accuracy: 0.7532 - val_loss: 0.5468 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7605 - val_loss: 0.5487 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.7679 - val_loss: 0.5545 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4690 - accuracy: 0.7760 - val_loss: 0.5551 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4590 - accuracy: 0.7819 - val_loss: 0.5567 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4473 - accuracy: 0.7894 - val_loss: 0.5651 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4341 - accuracy: 0.7981 - val_loss: 0.5745 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4228 - accuracy: 0.8051 - val_loss: 0.5811 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4095 - accuracy: 0.8120 - val_loss: 0.5855 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3982 - accuracy: 0.8176 - val_loss: 0.5947 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3875 - accuracy: 0.8239 - val_loss: 0.5962 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 17/400
253/257 [============================>.] - ETA: 0s - loss: 0.3784 - accuracy: 0.8284
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3787 - accuracy: 0.8284 - val_loss: 0.6124 - val_accuracy: 0.7084 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44313969648755336
Confusion Matrix :
 [[2962 1085]
 [1169 2878]]
Accuracy on test set:    0.7215221151470225
Sensitivity:    0.7111440573264146 	 Specificity:    0.7319001729676303
Precision  : 0.7262175119858693
Area Under Curve:    0.7215221151470225
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5922 - accuracy: 0.6830 - val_loss: 0.5569 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5498 - accuracy: 0.7185 - val_loss: 0.5496 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5341 - accuracy: 0.7308 - val_loss: 0.5463 - val_accuracy: 0.7146 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5228 - accuracy: 0.7400 - val_loss: 0.5474 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5121 - accuracy: 0.7482 - val_loss: 0.5475 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5020 - accuracy: 0.7542 - val_loss: 0.5499 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4903 - accuracy: 0.7635 - val_loss: 0.5577 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4794 - accuracy: 0.7714 - val_loss: 0.5510 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 3ms/step - loss: 0.4666 - accuracy: 0.7787 - val_loss: 0.5671 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4523 - accuracy: 0.7871
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4528 - accuracy: 0.7870 - val_loss: 0.5579 - val_accuracy: 0.7175 - lr: 0.0010
253/253 [==============================] - 0s 893us/step
Independent Testing Matthews Correlation:  0.46269052040086656
Confusion Matrix :
 [[3178  869]
 [1317 2730]]
Accuracy on test set:    0.7299234000494194
Sensitivity:    0.6745737583395107 	 Specificity:    0.7852730417593279
Precision  : 0.7585440400111142
Area Under Curve:    0.7299234000494194
(8094, 2560) (8094,)
Mean MCC = 0.4272 + 0.0154 and Mean AUC = 0.7130 + 0.0077
Mean Sensitivity = 0.7269 + 0.0301 and Mean Specificity = 0.6990 + 0.0425 and Mean Accuracy = 0.7130 + 0.0077
Mean Precision = 0.7087 + 0.0218





Seed   : 888801
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5860 - accuracy: 0.6852 - val_loss: 0.5563 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5419 - accuracy: 0.7277 - val_loss: 0.5485 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7354 - val_loss: 0.5460 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7428 - val_loss: 0.5476 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7491 - val_loss: 0.5478 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7582 - val_loss: 0.5498 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4827 - accuracy: 0.7658 - val_loss: 0.5525 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4698 - accuracy: 0.7749 - val_loss: 0.5573 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4576 - accuracy: 0.7849 - val_loss: 0.5652 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4452 - accuracy: 0.7927 - val_loss: 0.5626 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4321 - accuracy: 0.7994 - val_loss: 0.5756 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4207 - accuracy: 0.8072 - val_loss: 0.5799 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 13/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4065 - accuracy: 0.8147
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4075 - accuracy: 0.8144 - val_loss: 0.5913 - val_accuracy: 0.7089 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3870452622045586
Confusion Matrix :
 [[2703 1345]
 [1138 2909]]
Accuracy on test set:    0.6932674490426189
Sensitivity:    0.7188040523844823 	 Specificity:    0.6677371541501976
Precision  : 0.6838269863657734
Area Under Curve:    0.6932706032673399
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5871 - accuracy: 0.6841 - val_loss: 0.5624 - val_accuracy: 0.7019 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7219 - val_loss: 0.5516 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7339 - val_loss: 0.5625 - val_accuracy: 0.7034 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7423 - val_loss: 0.5512 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7496 - val_loss: 0.5543 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7562 - val_loss: 0.5517 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.7633 - val_loss: 0.5542 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7726 - val_loss: 0.5612 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4639 - accuracy: 0.7799 - val_loss: 0.5611 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4496 - accuracy: 0.7889 - val_loss: 0.5620 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4375 - accuracy: 0.7975 - val_loss: 0.5680 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 12/400
253/257 [============================>.] - ETA: 0s - loss: 0.4255 - accuracy: 0.8033
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4251 - accuracy: 0.8037 - val_loss: 0.5844 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41929041702589015
Confusion Matrix :
 [[2740 1308]
 [1046 3001]]
Accuracy on test set:    0.7092032118591723
Sensitivity:    0.7415369409439091 	 Specificity:    0.6768774703557312
Precision  : 0.6964492921791599
Area Under Curve:    0.7092072056498202
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5906 - accuracy: 0.6808 - val_loss: 0.5506 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7214 - val_loss: 0.5439 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7324 - val_loss: 0.5407 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7401 - val_loss: 0.5417 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7474 - val_loss: 0.5418 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7568 - val_loss: 0.5411 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7638 - val_loss: 0.5453 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4738 - accuracy: 0.7723 - val_loss: 0.5509 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4605 - accuracy: 0.7819 - val_loss: 0.5501 - val_accuracy: 0.7241 - lr: 0.0010

Epoch 10/400
249/257 [============================>.] - ETA: 0s - loss: 0.4481 - accuracy: 0.7894
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4484 - accuracy: 0.7892 - val_loss: 0.5515 - val_accuracy: 0.7220 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4197858403467833
Confusion Matrix :
 [[2959 1088]
 [1262 2786]]
Accuracy on test set:    0.7096973440395306
Sensitivity:    0.6882411067193676 	 Specificity:    0.7311588831233012
Precision  : 0.719153329891585
Area Under Curve:    0.7096999949213344
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5886 - accuracy: 0.6823 - val_loss: 0.5482 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7213 - val_loss: 0.5413 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7319 - val_loss: 0.5371 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7408 - val_loss: 0.5406 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7507 - val_loss: 0.5405 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.7584 - val_loss: 0.5434 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4805 - accuracy: 0.7680 - val_loss: 0.5479 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4680 - accuracy: 0.7792
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4677 - accuracy: 0.7792 - val_loss: 0.5544 - val_accuracy: 0.7245 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43088433787662844
Confusion Matrix :
 [[2846 1201]
 [1103 2945]]
Accuracy on test set:    0.7153798641136504
Sensitivity:    0.7275197628458498 	 Specificity:    0.7032369656535705
Precision  : 0.7103232030873131
Area Under Curve:    0.7153783642497102
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5890 - accuracy: 0.6844 - val_loss: 0.5493 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7228 - val_loss: 0.5420 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7331 - val_loss: 0.5391 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7404 - val_loss: 0.5389 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7491 - val_loss: 0.5419 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7556 - val_loss: 0.5415 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4854 - accuracy: 0.7657 - val_loss: 0.5427 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4730 - accuracy: 0.7739
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4734 - accuracy: 0.7738 - val_loss: 0.5517 - val_accuracy: 0.7259 - lr: 0.0010
253/253 [==============================] - 0s 994us/step
Independent Testing Matthews Correlation:  0.40964617259425046
Confusion Matrix :
 [[2616 1431]
 [ 969 3078]]
Accuracy on test set:    0.7034840622683469
Sensitivity:    0.7605633802816901 	 Specificity:    0.6464047442550037
Precision  : 0.6826347305389222
Area Under Curve:    0.7034840622683469
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5915 - accuracy: 0.6808 - val_loss: 0.5560 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7218 - val_loss: 0.5488 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7316 - val_loss: 0.5444 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5212 - accuracy: 0.7401 - val_loss: 0.5423 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5102 - accuracy: 0.7480 - val_loss: 0.5421 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7546 - val_loss: 0.5445 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.7642 - val_loss: 0.5518 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4749 - accuracy: 0.7742 - val_loss: 0.5472 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4623 - accuracy: 0.7804
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4632 - accuracy: 0.7801 - val_loss: 0.5498 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4270486754090615
Confusion Matrix :
 [[2852 1195]
 [1124 2923]]
Accuracy on test set:    0.7134914751667902
Sensitivity:    0.7222634049913517 	 Specificity:    0.7047195453422288
Precision  : 0.7098105876639145
Area Under Curve:    0.7134914751667902
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5907 - accuracy: 0.6813 - val_loss: 0.5565 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7211 - val_loss: 0.5504 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7324 - val_loss: 0.5492 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5206 - accuracy: 0.7402 - val_loss: 0.5450 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5093 - accuracy: 0.7468 - val_loss: 0.5450 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5006 - accuracy: 0.7546 - val_loss: 0.5481 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.7613 - val_loss: 0.5491 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4775 - accuracy: 0.7694 - val_loss: 0.5530 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7754 - val_loss: 0.5580 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4554 - accuracy: 0.7846
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4553 - accuracy: 0.7846 - val_loss: 0.5618 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4203639090890922
Confusion Matrix :
 [[2906 1141]
 [1205 2842]]
Accuracy on test set:    0.7101556708673091
Sensitivity:    0.702248579194465 	 Specificity:    0.7180627625401532
Precision  : 0.7135325131810193
Area Under Curve:    0.7101556708673091
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5882 - accuracy: 0.6831 - val_loss: 0.5499 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7218 - val_loss: 0.5429 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7328 - val_loss: 0.5416 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7414 - val_loss: 0.5399 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7485 - val_loss: 0.5392 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7588 - val_loss: 0.5394 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7675 - val_loss: 0.5419 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.7752 - val_loss: 0.5457 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4585 - accuracy: 0.7826 - val_loss: 0.5504 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4450 - accuracy: 0.7935 - val_loss: 0.5535 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4315 - accuracy: 0.8017
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4313 - accuracy: 0.8018 - val_loss: 0.5694 - val_accuracy: 0.7200 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.437668501241679
Confusion Matrix :
 [[2767 1280]
 [1000 3047]]
Accuracy on test set:    0.7183098591549296
Sensitivity:    0.7529033852236224 	 Specificity:    0.6837163330862367
Precision  : 0.7041830367460135
Area Under Curve:    0.7183098591549295
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5888 - accuracy: 0.6835 - val_loss: 0.5555 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7209 - val_loss: 0.5491 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7319 - val_loss: 0.5504 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7403 - val_loss: 0.5478 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7473 - val_loss: 0.5526 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.7568 - val_loss: 0.5496 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4886 - accuracy: 0.7622 - val_loss: 0.5500 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4743 - accuracy: 0.7730 - val_loss: 0.5544 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 9/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4629 - accuracy: 0.7791
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4630 - accuracy: 0.7787 - val_loss: 0.5600 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 789us/step
Independent Testing Matthews Correlation:  0.4588584136397331
Confusion Matrix :
 [[2952 1095]
 [1095 2952]]
Accuracy on test set:    0.7294292068198666
Sensitivity:    0.7294292068198666 	 Specificity:    0.7294292068198666
Precision  : 0.7294292068198666
Area Under Curve:    0.7294292068198667
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5939 - accuracy: 0.6791 - val_loss: 0.5604 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5513 - accuracy: 0.7200 - val_loss: 0.5520 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5345 - accuracy: 0.7320 - val_loss: 0.5508 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5226 - accuracy: 0.7397 - val_loss: 0.5483 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5115 - accuracy: 0.7458 - val_loss: 0.5503 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.7555 - val_loss: 0.5521 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7642 - val_loss: 0.5584 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7734 - val_loss: 0.5579 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4620 - accuracy: 0.7803
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4621 - accuracy: 0.7804 - val_loss: 0.5585 - val_accuracy: 0.7139 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4658457230821626
Confusion Matrix :
 [[3162  885]
 [1286 2761]]
Accuracy on test set:    0.7317766246602422
Sensitivity:    0.6822337533975784 	 Specificity:    0.7813194959229058
Precision  : 0.7572682391662096
Area Under Curve:    0.7317766246602421
(8094, 2560) (8094,)
Mean MCC = 0.4276 + 0.0217 and Mean AUC = 0.7134 + 0.0108
Mean Sensitivity = 0.7226 + 0.0246 and Mean Specificity = 0.7043 + 0.0365 and Mean Accuracy = 0.7134 + 0.0108
Mean Precision = 0.7107 + 0.0209





Seed   : 687993
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5866 - accuracy: 0.6842 - val_loss: 0.5556 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7219 - val_loss: 0.5472 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7344 - val_loss: 0.5471 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7429 - val_loss: 0.5451 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7503 - val_loss: 0.5453 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7563 - val_loss: 0.5481 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7628 - val_loss: 0.5589 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4749 - accuracy: 0.7720 - val_loss: 0.5514 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4629 - accuracy: 0.7790 - val_loss: 0.5619 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4498 - accuracy: 0.7875 - val_loss: 0.5669 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4381 - accuracy: 0.7946 - val_loss: 0.5786 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4263 - accuracy: 0.8019 - val_loss: 0.5739 - val_accuracy: 0.7097 - lr: 0.0010

Epoch 13/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4141 - accuracy: 0.8090
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4143 - accuracy: 0.8088 - val_loss: 0.5826 - val_accuracy: 0.7097 - lr: 0.0010
253/253 [==============================] - 0s 816us/step
Independent Testing Matthews Correlation:  0.39491860435624626
Confusion Matrix :
 [[2680 1368]
 [1085 2962]]
Accuracy on test set:    0.6969734403953057
Sensitivity:    0.7319001729676303 	 Specificity:    0.6620553359683794
Precision  : 0.6840646651270208
Area Under Curve:    0.6969777544680049
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5984 - accuracy: 0.6747 - val_loss: 0.5636 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7213 - val_loss: 0.5496 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7338 - val_loss: 0.5487 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5215 - accuracy: 0.7417 - val_loss: 0.5470 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.7464 - val_loss: 0.5481 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7529 - val_loss: 0.5527 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 7/400
252/257 [============================>.] - ETA: 0s - loss: 0.4905 - accuracy: 0.7618
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7614 - val_loss: 0.5633 - val_accuracy: 0.7087 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4377370244778737
Confusion Matrix :
 [[2523 1525]
 [ 781 3266]]
Accuracy on test set:    0.7151327980234713
Sensitivity:    0.8070175438596491 	 Specificity:    0.6232707509881423
Precision  : 0.6816948445001043
Area Under Curve:    0.7151441474238956
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5866 - accuracy: 0.6839 - val_loss: 0.5481 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7229 - val_loss: 0.5403 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7329 - val_loss: 0.5368 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7421 - val_loss: 0.5381 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7509 - val_loss: 0.5377 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7563 - val_loss: 0.5416 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.7646 - val_loss: 0.5463 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7729 - val_loss: 0.5435 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4627 - accuracy: 0.7796 - val_loss: 0.5513 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4503 - accuracy: 0.7893 - val_loss: 0.5503 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4379 - accuracy: 0.7975 - val_loss: 0.5570 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4257 - accuracy: 0.8047 - val_loss: 0.5683 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 13/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4128 - accuracy: 0.8129
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4132 - accuracy: 0.8124 - val_loss: 0.5660 - val_accuracy: 0.7213 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41923013560698275
Confusion Matrix :
 [[2831 1216]
 [1135 2913]]
Accuracy on test set:    0.7095738109944411
Sensitivity:    0.7196146245059288 	 Specificity:    0.6995305164319249
Precision  : 0.705497699200775
Area Under Curve:    0.7095725704689267
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5857 - accuracy: 0.6843 - val_loss: 0.5444 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7214 - val_loss: 0.5362 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5269 - accuracy: 0.7347 - val_loss: 0.5380 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7426 - val_loss: 0.5340 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7508 - val_loss: 0.5393 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7609 - val_loss: 0.5370 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4820 - accuracy: 0.7671
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4819 - accuracy: 0.7671 - val_loss: 0.5462 - val_accuracy: 0.7229 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4220280294598455
Confusion Matrix :
 [[2787 1260]
 [1081 2967]]
Accuracy on test set:    0.7108091414453366
Sensitivity:    0.7329545454545454 	 Specificity:    0.6886582653817642
Precision  : 0.7019162526614621
Area Under Curve:    0.710806405418155
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5860 - accuracy: 0.6866 - val_loss: 0.5567 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7232 - val_loss: 0.5444 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7332 - val_loss: 0.5417 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7413 - val_loss: 0.5414 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7493 - val_loss: 0.5395 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7568 - val_loss: 0.5453 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7663 - val_loss: 0.5471 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7727 - val_loss: 0.5469 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4591 - accuracy: 0.7810 - val_loss: 0.5479 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4460 - accuracy: 0.7893 - val_loss: 0.5506 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4337 - accuracy: 0.7984 - val_loss: 0.5579 - val_accuracy: 0.7215 - lr: 0.0010

Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4242 - accuracy: 0.8039
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4243 - accuracy: 0.8041 - val_loss: 0.5611 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40812194765473064
Confusion Matrix :
 [[2733 1314]
 [1084 2963]]
Accuracy on test set:    0.7037311588831233
Sensitivity:    0.7321472695824067 	 Specificity:    0.6753150481838399
Precision  : 0.6927753097965864
Area Under Curve:    0.7037311588831234
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5878 - accuracy: 0.6838 - val_loss: 0.5505 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7217 - val_loss: 0.5410 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7327 - val_loss: 0.5458 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7411 - val_loss: 0.5378 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7482 - val_loss: 0.5408 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7559 - val_loss: 0.5378 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4866 - accuracy: 0.7646 - val_loss: 0.5409 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7707 - val_loss: 0.5425 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4637 - accuracy: 0.7788
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4638 - accuracy: 0.7787 - val_loss: 0.5468 - val_accuracy: 0.7208 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4172189455214471
Confusion Matrix :
 [[2819 1228]
 [1131 2916]]
Accuracy on test set:    0.7085495428712627
Sensitivity:    0.720533728687917 	 Specificity:    0.6965653570546083
Precision  : 0.7036679536679536
Area Under Curve:    0.7085495428712627
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5876 - accuracy: 0.6828 - val_loss: 0.5451 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7219 - val_loss: 0.5375 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7341 - val_loss: 0.5421 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7415 - val_loss: 0.5349 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7520 - val_loss: 0.5394 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4923 - accuracy: 0.7593 - val_loss: 0.5419 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7697 - val_loss: 0.5405 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4658 - accuracy: 0.7796 - val_loss: 0.5444 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
241/257 [===========================>..] - ETA: 0s - loss: 0.4520 - accuracy: 0.7875
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4519 - accuracy: 0.7876 - val_loss: 0.5513 - val_accuracy: 0.7233 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41042827904551465
Confusion Matrix :
 [[2850 1197]
 [1189 2858]]
Accuracy on test set:    0.7052137385717816
Sensitivity:    0.7062021250308871 	 Specificity:    0.704225352112676
Precision  : 0.7048088779284833
Area Under Curve:    0.7052137385717816
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5900 - accuracy: 0.6811 - val_loss: 0.5503 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5477 - accuracy: 0.7221 - val_loss: 0.5412 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5328 - accuracy: 0.7314 - val_loss: 0.5362 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5224 - accuracy: 0.7391 - val_loss: 0.5348 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5126 - accuracy: 0.7450 - val_loss: 0.5361 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.7532 - val_loss: 0.5333 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7585 - val_loss: 0.5352 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.7669 - val_loss: 0.5380 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4738 - accuracy: 0.7727 - val_loss: 0.5407 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4621 - accuracy: 0.7812
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4621 - accuracy: 0.7812 - val_loss: 0.5436 - val_accuracy: 0.7227 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44527202834521973
Confusion Matrix :
 [[2933 1114]
 [1131 2916]]
Accuracy on test set:    0.7226340499135162
Sensitivity:    0.720533728687917 	 Specificity:    0.7247343711391154
Precision  : 0.7235732009925558
Area Under Curve:    0.7226340499135162
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5916 - accuracy: 0.6814 - val_loss: 0.5488 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7207 - val_loss: 0.5438 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5339 - accuracy: 0.7311 - val_loss: 0.5395 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5222 - accuracy: 0.7386 - val_loss: 0.5379 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5125 - accuracy: 0.7474 - val_loss: 0.5422 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5006 - accuracy: 0.7552 - val_loss: 0.5408 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7631 - val_loss: 0.5429 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7717 - val_loss: 0.5443 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4632 - accuracy: 0.7810 - val_loss: 0.5530 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4514 - accuracy: 0.7885 - val_loss: 0.5562 - val_accuracy: 0.7196 - lr: 0.0010

Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4386 - accuracy: 0.7952 - val_loss: 0.5579 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4228 - accuracy: 0.8036
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4233 - accuracy: 0.8032 - val_loss: 0.5627 - val_accuracy: 0.7145 - lr: 0.0010
253/253 [==============================] - 0s 960us/step
Independent Testing Matthews Correlation:  0.4451251383335707
Confusion Matrix :
 [[3146  901]
 [1356 2691]]
Accuracy on test set:    0.7211514702248579
Sensitivity:    0.6649369903632321 	 Specificity:    0.7773659500864838
Precision  : 0.7491648106904232
Area Under Curve:    0.7211514702248579
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5911 - accuracy: 0.6828 - val_loss: 0.5493 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5496 - accuracy: 0.7213 - val_loss: 0.5447 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5352 - accuracy: 0.7307 - val_loss: 0.5432 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.7368 - val_loss: 0.5403 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7456 - val_loss: 0.5461 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7528 - val_loss: 0.5434 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4955 - accuracy: 0.7594
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7589 - val_loss: 0.5477 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4899955190280286
Confusion Matrix :
 [[3008 1039]
 [1025 3022]]
Accuracy on test set:    0.7449962935507783
Sensitivity:    0.746725969854213 	 Specificity:    0.7432666172473437
Precision  : 0.744151686776656
Area Under Curve:    0.7449962935507782
(8094, 2560) (8094,)
Mean MCC = 0.4290 + 0.0256 and Mean AUC = 0.7139 + 0.0127
Mean Sensitivity = 0.7283 + 0.0336 and Mean Specificity = 0.6995 + 0.0407 and Mean Accuracy = 0.7139 + 0.0127
Mean Precision = 0.7091 + 0.0219





Seed   : 617350
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5880 - accuracy: 0.6860 - val_loss: 0.5612 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7224 - val_loss: 0.5506 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7339 - val_loss: 0.5472 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7407 - val_loss: 0.5469 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7500 - val_loss: 0.5466 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7585 - val_loss: 0.5506 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7658 - val_loss: 0.5552 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.7735 - val_loss: 0.5626 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4601 - accuracy: 0.7842 - val_loss: 0.5545 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4462 - accuracy: 0.7920 - val_loss: 0.5577 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4334 - accuracy: 0.8006 - val_loss: 0.5763 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4199 - accuracy: 0.8087
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4200 - accuracy: 0.8086 - val_loss: 0.5707 - val_accuracy: 0.7126 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40268244498119965
Confusion Matrix :
 [[2797 1251]
 [1167 2880]]
Accuracy on test set:    0.7012970969734404
Sensitivity:    0.7116382505559674 	 Specificity:    0.6909584980237155
Precision  : 0.6971677559912854
Area Under Curve:    0.7012983742898413
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5861 - accuracy: 0.6848 - val_loss: 0.5678 - val_accuracy: 0.7019 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7235 - val_loss: 0.5500 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7350 - val_loss: 0.5471 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7430 - val_loss: 0.5428 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5038 - accuracy: 0.7500 - val_loss: 0.5489 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.7624 - val_loss: 0.5492 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4811 - accuracy: 0.7681 - val_loss: 0.5543 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4702 - accuracy: 0.7757 - val_loss: 0.5537 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4550 - accuracy: 0.7852 - val_loss: 0.5523 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4416 - accuracy: 0.7935 - val_loss: 0.5610 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4308 - accuracy: 0.8013 - val_loss: 0.5611 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4156 - accuracy: 0.8118 - val_loss: 0.5771 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 13/400
251/257 [============================>.] - ETA: 0s - loss: 0.4031 - accuracy: 0.8177
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4031 - accuracy: 0.8179 - val_loss: 0.5859 - val_accuracy: 0.7098 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4131791961930988
Confusion Matrix :
 [[2516 1532]
 [ 866 3181]]
Accuracy on test set:    0.7037677578752316
Sensitivity:    0.7860143316036571 	 Specificity:    0.6215415019762845
Precision  : 0.6749416507532358
Area Under Curve:    0.7037779167899709
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5875 - accuracy: 0.6840 - val_loss: 0.5485 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7230 - val_loss: 0.5402 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7349 - val_loss: 0.5389 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7414 - val_loss: 0.5381 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7514 - val_loss: 0.5426 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7601 - val_loss: 0.5434 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.7680 - val_loss: 0.5425 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.7779 - val_loss: 0.5520 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4554 - accuracy: 0.7838
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4554 - accuracy: 0.7839 - val_loss: 0.5524 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4056543224142694
Confusion Matrix :
 [[2760 1287]
 [1120 2928]]
Accuracy on test set:    0.7026559604694256
Sensitivity:    0.7233201581027668 	 Specificity:    0.6819866567828021
Precision  : 0.6946619217081851
Area Under Curve:    0.7026534074427845
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5842 - accuracy: 0.6879 - val_loss: 0.5467 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7232 - val_loss: 0.5388 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5264 - accuracy: 0.7347 - val_loss: 0.5356 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7435 - val_loss: 0.5348 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.7507 - val_loss: 0.5351 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.7598 - val_loss: 0.5404 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4794 - accuracy: 0.7692 - val_loss: 0.5424 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7773 - val_loss: 0.5436 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4537 - accuracy: 0.7870 - val_loss: 0.5515 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4404 - accuracy: 0.7932
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4402 - accuracy: 0.7932 - val_loss: 0.5508 - val_accuracy: 0.7226 - lr: 0.0010
253/253 [==============================] - 0s 719us/step
Independent Testing Matthews Correlation:  0.4126051765364279
Confusion Matrix :
 [[2676 1371]
 [1013 3035]]
Accuracy on test set:    0.7054972205064854
Sensitivity:    0.7497529644268774 	 Specificity:    0.6612305411415864
Precision  : 0.688833408987744
Area Under Curve:    0.7054917527842319
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5874 - accuracy: 0.6834 - val_loss: 0.5489 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7224 - val_loss: 0.5424 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7327 - val_loss: 0.5398 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.7391 - val_loss: 0.5352 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.7467 - val_loss: 0.5428 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4987 - accuracy: 0.7556 - val_loss: 0.5369 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.7637 - val_loss: 0.5408 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4763 - accuracy: 0.7708 - val_loss: 0.5434 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4640 - accuracy: 0.7788 - val_loss: 0.5456 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4519 - accuracy: 0.7874 - val_loss: 0.5454 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4377 - accuracy: 0.7950 - val_loss: 0.5559 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4248 - accuracy: 0.8023
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4253 - accuracy: 0.8018 - val_loss: 0.5589 - val_accuracy: 0.7251 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4141418432248745
Confusion Matrix :
 [[2932 1115]
 [1257 2790]]
Accuracy on test set:    0.7069434148752162
Sensitivity:    0.6893995552260934 	 Specificity:    0.724487274524339
Precision  : 0.7144686299615877
Area Under Curve:    0.7069434148752163
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5908 - accuracy: 0.6806 - val_loss: 0.5503 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7220 - val_loss: 0.5403 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7326 - val_loss: 0.5400 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5204 - accuracy: 0.7383 - val_loss: 0.5381 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.7471 - val_loss: 0.5396 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7533 - val_loss: 0.5383 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4905 - accuracy: 0.7612
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7611 - val_loss: 0.5457 - val_accuracy: 0.7270 - lr: 0.0010
253/253 [==============================] - 0s 723us/step
Independent Testing Matthews Correlation:  0.43559941834428456
Confusion Matrix :
 [[2710 1337]
 [ 955 3092]]
Accuracy on test set:    0.7168272794662713
Sensitivity:    0.7640227328885594 	 Specificity:    0.6696318260439832
Precision  : 0.6981259878076315
Area Under Curve:    0.7168272794662712
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5891 - accuracy: 0.6822 - val_loss: 0.5416 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7216 - val_loss: 0.5377 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7343 - val_loss: 0.5369 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7430 - val_loss: 0.5368 - val_accuracy: 0.7237 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7504 - val_loss: 0.5352 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7559 - val_loss: 0.5352 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7642 - val_loss: 0.5439 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4763 - accuracy: 0.7736
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4764 - accuracy: 0.7734 - val_loss: 0.5413 - val_accuracy: 0.7245 - lr: 0.0010
253/253 [==============================] - 0s 991us/step
Independent Testing Matthews Correlation:  0.4252428396761277
Confusion Matrix :
 [[2816 1231]
 [1096 2951]]
Accuracy on test set:    0.7125030887076848
Sensitivity:    0.7291821102050902 	 Specificity:    0.6958240672102792
Precision  : 0.7056432329029173
Area Under Curve:    0.7125030887076848
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5890 - accuracy: 0.6845 - val_loss: 0.5447 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.7204 - val_loss: 0.5370 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5326 - accuracy: 0.7313 - val_loss: 0.5337 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5223 - accuracy: 0.7379 - val_loss: 0.5321 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5126 - accuracy: 0.7443 - val_loss: 0.5341 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7520 - val_loss: 0.5324 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4900 - accuracy: 0.7620
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4902 - accuracy: 0.7618 - val_loss: 0.5361 - val_accuracy: 0.7251 - lr: 0.0010
253/253 [==============================] - 0s 951us/step
Independent Testing Matthews Correlation:  0.44321101456963247
Confusion Matrix :
 [[3064  983]
 [1275 2772]]
Accuracy on test set:    0.7210279219174698
Sensitivity:    0.6849518161601186 	 Specificity:    0.7571040276748209
Precision  : 0.7382157123834887
Area Under Curve:    0.7210279219174697
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5879 - accuracy: 0.6864 - val_loss: 0.5450 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7204 - val_loss: 0.5395 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7306 - val_loss: 0.5382 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5238 - accuracy: 0.7382 - val_loss: 0.5366 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7456 - val_loss: 0.5376 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.7545 - val_loss: 0.5393 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.7635 - val_loss: 0.5398 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4765 - accuracy: 0.7725 - val_loss: 0.5417 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4654 - accuracy: 0.7802
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4653 - accuracy: 0.7803 - val_loss: 0.5546 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 993us/step
Independent Testing Matthews Correlation:  0.4552525113352051
Confusion Matrix :
 [[2820 1227]
 [ 981 3066]]
Accuracy on test set:    0.7272053372868792
Sensitivity:    0.7575982209043736 	 Specificity:    0.6968124536693847
Precision  : 0.7141858839972047
Area Under Curve:    0.7272053372868792
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5946 - accuracy: 0.6787 - val_loss: 0.5496 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5528 - accuracy: 0.7185 - val_loss: 0.5455 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5378 - accuracy: 0.7281 - val_loss: 0.5435 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5250 - accuracy: 0.7383 - val_loss: 0.5420 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7446 - val_loss: 0.5403 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
244/257 [===========================>..] - ETA: 0s - loss: 0.5024 - accuracy: 0.7554
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7541 - val_loss: 0.5424 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4860405250698259
Confusion Matrix :
 [[3002 1045]
 [1035 3012]]
Accuracy on test set:    0.7430195206325674
Sensitivity:    0.7442550037064493 	 Specificity:    0.7417840375586855
Precision  : 0.7424205077643579
Area Under Curve:    0.7430195206325675
(8094, 2560) (8094,)
Mean MCC = 0.4294 + 0.0249 and Mean AUC = 0.7141 + 0.0126
Mean Sensitivity = 0.7340 + 0.0309 and Mean Specificity = 0.6941 + 0.0378 and Mean Accuracy = 0.7141 + 0.0126
Mean Precision = 0.7069 + 0.0201





Seed   : 248266
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5838 - accuracy: 0.6886 - val_loss: 0.5475 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5400 - accuracy: 0.7247 - val_loss: 0.5438 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5242 - accuracy: 0.7380 - val_loss: 0.5370 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7473 - val_loss: 0.5397 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.7564 - val_loss: 0.5410 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4841 - accuracy: 0.7654 - val_loss: 0.5399 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4706 - accuracy: 0.7758
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4706 - accuracy: 0.7758 - val_loss: 0.5404 - val_accuracy: 0.7164 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40979519069441134
Confusion Matrix :
 [[2827 1221]
 [1168 2879]]
Accuracy on test set:    0.7048795552810376
Sensitivity:    0.711391153941191 	 Specificity:    0.6983695652173914
Precision  : 0.7021951219512195
Area Under Curve:    0.7048803595792913
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5864 - accuracy: 0.6828 - val_loss: 0.5506 - val_accuracy: 0.7164 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7237 - val_loss: 0.5399 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7356 - val_loss: 0.5462 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7434 - val_loss: 0.5374 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5043 - accuracy: 0.7502 - val_loss: 0.5475 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7595 - val_loss: 0.5413 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7665 - val_loss: 0.5479 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4676 - accuracy: 0.7788 - val_loss: 0.5604 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4567 - accuracy: 0.7840
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.7840 - val_loss: 0.5460 - val_accuracy: 0.7150 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4216903917919879
Confusion Matrix :
 [[2772 1276]
 [1067 2980]]
Accuracy on test set:    0.7105620753551575
Sensitivity:    0.7363479120336052 	 Specificity:    0.6847826086956522
Precision  : 0.700187969924812
Area Under Curve:    0.7105652603646286
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5948 - accuracy: 0.6784 - val_loss: 0.5489 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7211 - val_loss: 0.5428 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7285 - val_loss: 0.5334 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5209 - accuracy: 0.7372 - val_loss: 0.5298 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.7473 - val_loss: 0.5329 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.7585 - val_loss: 0.5308 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.7660 - val_loss: 0.5337 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4711 - accuracy: 0.7736
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7735 - val_loss: 0.5361 - val_accuracy: 0.7277 - lr: 0.0010
253/253 [==============================] - 0s 792us/step
Independent Testing Matthews Correlation:  0.42623823719611886
Confusion Matrix :
 [[2771 1276]
 [1049 2999]]
Accuracy on test set:    0.7127856701667696
Sensitivity:    0.7408596837944664 	 Specificity:    0.6847047195453422
Precision  : 0.7015204678362573
Area Under Curve:    0.7127822016699042
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5852 - accuracy: 0.6872 - val_loss: 0.5406 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7245 - val_loss: 0.5328 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7336 - val_loss: 0.5376 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7433 - val_loss: 0.5299 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7473 - val_loss: 0.5304 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7566 - val_loss: 0.5307 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7655 - val_loss: 0.5372 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4744 - accuracy: 0.7709 - val_loss: 0.5426 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4631 - accuracy: 0.7808 - val_loss: 0.5415 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4513 - accuracy: 0.7883 - val_loss: 0.5589 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4392 - accuracy: 0.7949
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4385 - accuracy: 0.7956 - val_loss: 0.5528 - val_accuracy: 0.7253 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3992493360146201
Confusion Matrix :
 [[2879 1168]
 [1264 2784]]
Accuracy on test set:    0.6995676343421865
Sensitivity:    0.6877470355731226 	 Specificity:    0.711391153941191
Precision  : 0.7044534412955465
Area Under Curve:    0.6995690947571568
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5858 - accuracy: 0.6859 - val_loss: 0.5512 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7225 - val_loss: 0.5449 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7313 - val_loss: 0.5430 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7390 - val_loss: 0.5423 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7457 - val_loss: 0.5419 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.7543 - val_loss: 0.5424 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4897 - accuracy: 0.7624 - val_loss: 0.5466 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7695 - val_loss: 0.5480 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4667 - accuracy: 0.7777 - val_loss: 0.5523 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4530 - accuracy: 0.7876
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4530 - accuracy: 0.7876 - val_loss: 0.5556 - val_accuracy: 0.7197 - lr: 0.0010
253/253 [==============================] - 0s 956us/step
Independent Testing Matthews Correlation:  0.4267421591924668
Confusion Matrix :
 [[2898 1149]
 [1171 2876]]
Accuracy on test set:    0.713367926859402
Sensitivity:    0.7106498640968619 	 Specificity:    0.7160859896219421
Precision  : 0.7145341614906833
Area Under Curve:    0.7133679268594021
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5886 - accuracy: 0.6834 - val_loss: 0.5534 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7222 - val_loss: 0.5429 - val_accuracy: 0.7215 - lr: 0.0010

Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7315 - val_loss: 0.5427 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7405 - val_loss: 0.5434 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7494 - val_loss: 0.5451 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.7557 - val_loss: 0.5456 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.7645 - val_loss: 0.5474 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4738 - accuracy: 0.7724
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7725 - val_loss: 0.5582 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 987us/step
Independent Testing Matthews Correlation:  0.4209308811336722
Confusion Matrix :
 [[2521 1526]
 [ 842 3205]]
Accuracy on test set:    0.707437608104769
Sensitivity:    0.7919446503582901 	 Specificity:    0.6229305658512478
Precision  : 0.6774466286197421
Area Under Curve:    0.707437608104769
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5900 - accuracy: 0.6828 - val_loss: 0.5516 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7227 - val_loss: 0.5433 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7336 - val_loss: 0.5442 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7421 - val_loss: 0.5414 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7495 - val_loss: 0.5453 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4927 - accuracy: 0.7589 - val_loss: 0.5433 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4819 - accuracy: 0.7679 - val_loss: 0.5463 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4673 - accuracy: 0.7752
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4673 - accuracy: 0.7752 - val_loss: 0.5546 - val_accuracy: 0.7182 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44077441865388917
Confusion Matrix :
 [[2677 1370]
 [ 905 3142]]
Accuracy on test set:    0.7189276006918706
Sensitivity:    0.7763775636273783 	 Specificity:    0.6614776377563627
Precision  : 0.6963652482269503
Area Under Curve:    0.7189276006918704
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5862 - accuracy: 0.6864 - val_loss: 0.5493 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7217 - val_loss: 0.5401 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7338 - val_loss: 0.5419 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7406 - val_loss: 0.5401 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7501 - val_loss: 0.5432 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7582 - val_loss: 0.5433 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7665 - val_loss: 0.5464 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4732 - accuracy: 0.7741 - val_loss: 0.5642 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4575 - accuracy: 0.7836 - val_loss: 0.5547 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4450 - accuracy: 0.7904 - val_loss: 0.5629 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4338 - accuracy: 0.7995 - val_loss: 0.5746 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4187 - accuracy: 0.8083 - val_loss: 0.5728 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4032 - accuracy: 0.8171 - val_loss: 0.5806 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3914 - accuracy: 0.8227 - val_loss: 0.5911 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3811 - accuracy: 0.8295 - val_loss: 0.5850 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 16/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3693 - accuracy: 0.8341 - val_loss: 0.6057 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 17/400
249/257 [============================>.] - ETA: 0s - loss: 0.3607 - accuracy: 0.8383
Epoch 17: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3605 - accuracy: 0.8384 - val_loss: 0.6252 - val_accuracy: 0.7179 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4331043586538866
Confusion Matrix :
 [[2808 1239]
 [1057 2990]]
Accuracy on test set:    0.7163330862367185
Sensitivity:    0.7388188781813689 	 Specificity:    0.6938472942920682
Precision  : 0.707022936864507
Area Under Curve:    0.7163330862367185
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5899 - accuracy: 0.6822 - val_loss: 0.5514 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7213 - val_loss: 0.5490 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5331 - accuracy: 0.7309 - val_loss: 0.5438 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5225 - accuracy: 0.7387 - val_loss: 0.5467 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5119 - accuracy: 0.7473 - val_loss: 0.5505 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.7546 - val_loss: 0.5483 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4902 - accuracy: 0.7609 - val_loss: 0.5510 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 8/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4768 - accuracy: 0.7710
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4770 - accuracy: 0.7711 - val_loss: 0.5520 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4479061501587679
Confusion Matrix :
 [[3016 1031]
 [1205 2842]]
Accuracy on test set:    0.7237459846800098
Sensitivity:    0.702248579194465 	 Specificity:    0.7452433901655547
Precision  : 0.7337980893364318
Area Under Curve:    0.72374598468001
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5906 - accuracy: 0.6825 - val_loss: 0.5550 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5500 - accuracy: 0.7187 - val_loss: 0.5544 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5361 - accuracy: 0.7293 - val_loss: 0.5456 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5243 - accuracy: 0.7378 - val_loss: 0.5471 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7428 - val_loss: 0.5447 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7517 - val_loss: 0.5497 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7584 - val_loss: 0.5487 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7678 - val_loss: 0.5581 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4722 - accuracy: 0.7758
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4723 - accuracy: 0.7757 - val_loss: 0.5545 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47717493911930114
Confusion Matrix :
 [[3181  866]
 [1259 2788]]
Accuracy on test set:    0.7374598468000988
Sensitivity:    0.6889053619965406 	 Specificity:    0.7860143316036571
Precision  : 0.7629994526546251
Area Under Curve:    0.7374598468000988
(8094, 2560) (8094,)
Mean MCC = 0.4304 + 0.0205 and Mean AUC = 0.7145 + 0.0101
Mean Sensitivity = 0.7285 + 0.0334 and Mean Specificity = 0.7005 + 0.0421 and Mean Accuracy = 0.7145 + 0.0101
Mean Precision = 0.7101 + 0.0222





Seed   : 991056
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5856 - accuracy: 0.6869 - val_loss: 0.5608 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5423 - accuracy: 0.7262 - val_loss: 0.5516 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5264 - accuracy: 0.7371 - val_loss: 0.5515 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7437 - val_loss: 0.5488 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7508 - val_loss: 0.5533 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7595 - val_loss: 0.5526 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4830 - accuracy: 0.7662 - val_loss: 0.5592 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7751 - val_loss: 0.5554 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4597 - accuracy: 0.7817 - val_loss: 0.5587 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4481 - accuracy: 0.7890 - val_loss: 0.5673 - val_accuracy: 0.7049 - lr: 0.0010
Epoch 11/400
250/257 [============================>.] - ETA: 0s - loss: 0.4361 - accuracy: 0.7968
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4362 - accuracy: 0.7970 - val_loss: 0.5803 - val_accuracy: 0.7050 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40284782601434144
Confusion Matrix :
 [[2738 1310]
 [1109 2938]]
Accuracy on test set:    0.7011735639283508
Sensitivity:    0.7259698542129973 	 Specificity:    0.6763833992094862
Precision  : 0.6916195856873822
Area Under Curve:    0.7011766267112417
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5817 - accuracy: 0.6911 - val_loss: 0.5570 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7251 - val_loss: 0.5518 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5257 - accuracy: 0.7374 - val_loss: 0.5482 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5146 - accuracy: 0.7433 - val_loss: 0.5470 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.7529 - val_loss: 0.5486 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.7607 - val_loss: 0.5670 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7672 - val_loss: 0.5600 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4689 - accuracy: 0.7757 - val_loss: 0.5509 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4558 - accuracy: 0.7854 - val_loss: 0.5673 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4432 - accuracy: 0.7936
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4431 - accuracy: 0.7937 - val_loss: 0.5587 - val_accuracy: 0.7117 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40347973464435727
Confusion Matrix :
 [[2895 1153]
 [1262 2785]]
Accuracy on test set:    0.701667696108709
Sensitivity:    0.6881640721522115 	 Specificity:    0.7151679841897233
Precision  : 0.707211782630777
Area Under Curve:    0.7016660281709675
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5881 - accuracy: 0.6836 - val_loss: 0.5544 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7236 - val_loss: 0.5441 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7328 - val_loss: 0.5426 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7416 - val_loss: 0.5422 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7503 - val_loss: 0.5419 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7591 - val_loss: 0.5425 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4830 - accuracy: 0.7664 - val_loss: 0.5430 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4679 - accuracy: 0.7774 - val_loss: 0.5445 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4550 - accuracy: 0.7859 - val_loss: 0.5503 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4419 - accuracy: 0.7942 - val_loss: 0.5577 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 11/400
254/257 [============================>.] - ETA: 0s - loss: 0.4260 - accuracy: 0.8044
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4260 - accuracy: 0.8045 - val_loss: 0.5612 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41351858289891
Confusion Matrix :
 [[2782 1265]
 [1110 2938]]
Accuracy on test set:    0.7066090179122916
Sensitivity:    0.7257905138339921 	 Specificity:    0.6874227823078823
Precision  : 0.6990245063050202
Area Under Curve:    0.7066066480709373
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5866 - accuracy: 0.6837 - val_loss: 0.5500 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7226 - val_loss: 0.5428 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7329 - val_loss: 0.5401 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7407 - val_loss: 0.5410 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7478 - val_loss: 0.5421 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - ETA: 0s - loss: 0.4963 - accuracy: 0.7567
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7567 - val_loss: 0.5454 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 907us/step
Independent Testing Matthews Correlation:  0.4233534390423802
Confusion Matrix :
 [[2758 1289]
 [1048 3000]]
Accuracy on test set:    0.7113032736256949
Sensitivity:    0.741106719367589 	 Specificity:    0.6814924635532493
Precision  : 0.6994637444625786
Area Under Curve:    0.7112995914604191
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5859 - accuracy: 0.6872 - val_loss: 0.5528 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7215 - val_loss: 0.5455 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7339 - val_loss: 0.5448 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7409 - val_loss: 0.5419 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7510 - val_loss: 0.5439 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7575 - val_loss: 0.5518 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7672 - val_loss: 0.5511 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7764 - val_loss: 0.5586 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4559 - accuracy: 0.7838 - val_loss: 0.5670 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4406 - accuracy: 0.7946
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4409 - accuracy: 0.7944 - val_loss: 0.5661 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.416609109866697
Confusion Matrix :
 [[2744 1303]
 [1061 2986]]
Accuracy on test set:    0.7079318013343218
Sensitivity:    0.7378304917222634 	 Specificity:    0.6780331109463801
Precision  : 0.6961995803217533
Area Under Curve:    0.7079318013343217
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5900 - accuracy: 0.6829 - val_loss: 0.5539 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7239 - val_loss: 0.5506 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7333 - val_loss: 0.5450 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5149 - accuracy: 0.7431 - val_loss: 0.5485 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7495 - val_loss: 0.5447 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.7606 - val_loss: 0.5470 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4784 - accuracy: 0.7694 - val_loss: 0.5504 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4636 - accuracy: 0.7793
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4641 - accuracy: 0.7789 - val_loss: 0.5523 - val_accuracy: 0.7219 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42709529449755607
Confusion Matrix :
 [[2804 1243]
 [1077 2970]]
Accuracy on test set:    0.713367926859402
Sensitivity:    0.7338769458858414 	 Specificity:    0.6928589078329627
Precision  : 0.7049608355091384
Area Under Curve:    0.713367926859402
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5861 - accuracy: 0.6857 - val_loss: 0.5541 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7230 - val_loss: 0.5466 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7341 - val_loss: 0.5439 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7418 - val_loss: 0.5445 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7483 - val_loss: 0.5444 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7575 - val_loss: 0.5467 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.7645 - val_loss: 0.5474 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.7728 - val_loss: 0.5489 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4640 - accuracy: 0.7779 - val_loss: 0.5520 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 10/400
252/257 [============================>.] - ETA: 0s - loss: 0.4486 - accuracy: 0.7894
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4485 - accuracy: 0.7897 - val_loss: 0.5563 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41742774801026344
Confusion Matrix :
 [[2908 1139]
 [1219 2828]]
Accuracy on test set:    0.7086730911786508
Sensitivity:    0.6987892265875958 	 Specificity:    0.7185569557697059
Precision  : 0.7128812704814721
Area Under Curve:    0.708673091178651
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5858 - accuracy: 0.6863 - val_loss: 0.5594 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7226 - val_loss: 0.5474 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7333 - val_loss: 0.5428 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7435 - val_loss: 0.5478 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7485 - val_loss: 0.5461 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7583 - val_loss: 0.5494 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7639 - val_loss: 0.5504 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4711 - accuracy: 0.7733 - val_loss: 0.5514 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 9/400
249/257 [============================>.] - ETA: 0s - loss: 0.4601 - accuracy: 0.7812
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4601 - accuracy: 0.7810 - val_loss: 0.5575 - val_accuracy: 0.7142 - lr: 0.0010
253/253 [==============================] - 0s 969us/step
Independent Testing Matthews Correlation:  0.4340477698829533
Confusion Matrix :
 [[2954 1093]
 [1198 2849]]
Accuracy on test set:    0.7169508277736595
Sensitivity:    0.7039782554978997 	 Specificity:    0.7299234000494194
Precision  : 0.7227295788939625
Area Under Curve:    0.7169508277736595
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5907 - accuracy: 0.6810 - val_loss: 0.5525 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5481 - accuracy: 0.7213 - val_loss: 0.5533 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7307 - val_loss: 0.5442 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5213 - accuracy: 0.7392 - val_loss: 0.5432 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5108 - accuracy: 0.7480 - val_loss: 0.5428 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.7549 - val_loss: 0.5444 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4883 - accuracy: 0.7629 - val_loss: 0.5465 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4753 - accuracy: 0.7722 - val_loss: 0.5497 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4647 - accuracy: 0.7786
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4647 - accuracy: 0.7786 - val_loss: 0.5536 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.45617378900865646
Confusion Matrix :
 [[2971 1076]
 [1125 2922]]
Accuracy on test set:    0.7280701754385965
Sensitivity:    0.7220163083765753 	 Specificity:    0.7341240425006177
Precision  : 0.7308654327163582
Area Under Curve:    0.7280701754385965
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5958 - accuracy: 0.6770 - val_loss: 0.5553 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5508 - accuracy: 0.7185 - val_loss: 0.5494 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5358 - accuracy: 0.7298 - val_loss: 0.5505 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5259 - accuracy: 0.7366 - val_loss: 0.5460 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5150 - accuracy: 0.7444 - val_loss: 0.5462 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5040 - accuracy: 0.7527 - val_loss: 0.5491 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4919 - accuracy: 0.7595
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.7594 - val_loss: 0.5517 - val_accuracy: 0.7123 - lr: 0.0010
253/253 [==============================] - 0s 790us/step
Independent Testing Matthews Correlation:  0.4971298828984301
Confusion Matrix :
 [[3089  958]
 [1078 2969]]
Accuracy on test set:    0.7484556461576476
Sensitivity:    0.733629849271065 	 Specificity:    0.7632814430442303
Precision  : 0.7560478736949325
Area Under Curve:    0.7484556461576477
(8094, 2560) (8094,)
Mean MCC = 0.4292 + 0.0270 and Mean AUC = 0.7144 + 0.0136
Mean Sensitivity = 0.7211 + 0.0171 and Mean Specificity = 0.7077 + 0.0276 and Mean Accuracy = 0.7144 + 0.0136
Mean Precision = 0.7121 + 0.0186





Seed   : 71980
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5873 - accuracy: 0.6855 - val_loss: 0.5609 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7241 - val_loss: 0.5537 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7327 - val_loss: 0.5509 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7432 - val_loss: 0.5516 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7476 - val_loss: 0.5526 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.7577 - val_loss: 0.5549 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.7653 - val_loss: 0.5553 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4711 - accuracy: 0.7734
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7735 - val_loss: 0.5625 - val_accuracy: 0.7119 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4248764908870843
Confusion Matrix :
 [[2696 1352]
 [ 983 3064]]
Accuracy on test set:    0.711550339715874
Sensitivity:    0.7571040276748209 	 Specificity:    0.66600790513834
Precision  : 0.6938405797101449
Area Under Curve:    0.7115559664065804
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5941 - accuracy: 0.6777 - val_loss: 0.5634 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5481 - accuracy: 0.7208 - val_loss: 0.5522 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7322 - val_loss: 0.5521 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7411 - val_loss: 0.5487 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7486 - val_loss: 0.5478 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 6/400

257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7600 - val_loss: 0.5510 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7678 - val_loss: 0.5593 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7757 - val_loss: 0.5548 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4575 - accuracy: 0.7853 - val_loss: 0.5621 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4437 - accuracy: 0.7944
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4439 - accuracy: 0.7943 - val_loss: 0.5623 - val_accuracy: 0.7106 - lr: 0.0010
253/253 [==============================] - 0s 974us/step
Independent Testing Matthews Correlation:  0.4075980324379024
Confusion Matrix :
 [[2770 1278]
 [1121 2926]]
Accuracy on test set:    0.7036442248301421
Sensitivity:    0.7230046948356808 	 Specificity:    0.6842885375494071
Precision  : 0.6960038058991437
Area Under Curve:    0.7036466161925439
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5843 - accuracy: 0.6863 - val_loss: 0.5436 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7228 - val_loss: 0.5381 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7340 - val_loss: 0.5372 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7414 - val_loss: 0.5369 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7497 - val_loss: 0.5365 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7594 - val_loss: 0.5360 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7657 - val_loss: 0.5393 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7767 - val_loss: 0.5409 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4579 - accuracy: 0.7836 - val_loss: 0.5522 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4443 - accuracy: 0.7930 - val_loss: 0.5525 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 11/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4305 - accuracy: 0.8019
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4304 - accuracy: 0.8021 - val_loss: 0.5566 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41793566566194945
Confusion Matrix :
 [[2680 1367]
 [ 996 3052]]
Accuracy on test set:    0.7080914144533663
Sensitivity:    0.7539525691699605 	 Specificity:    0.6622189276006919
Precision  : 0.6906539941163159
Area Under Curve:    0.7080857483853261
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5923 - accuracy: 0.6810 - val_loss: 0.5481 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7216 - val_loss: 0.5368 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7336 - val_loss: 0.5330 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7426 - val_loss: 0.5330 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.7498 - val_loss: 0.5352 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7585 - val_loss: 0.5367 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.7647 - val_loss: 0.5390 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7726 - val_loss: 0.5436 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4614 - accuracy: 0.7815
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4619 - accuracy: 0.7813 - val_loss: 0.5425 - val_accuracy: 0.7253 - lr: 0.0010
253/253 [==============================] - 0s 732us/step
Independent Testing Matthews Correlation:  0.420152778331683
Confusion Matrix :
 [[2855 1192]
 [1155 2893]]
Accuracy on test set:    0.7100679431747993
Sensitivity:    0.7146739130434783 	 Specificity:    0.705460835186558
Precision  : 0.7082007343941249
Area Under Curve:    0.7100673741150181
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5876 - accuracy: 0.6839 - val_loss: 0.5453 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7233 - val_loss: 0.5386 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7341 - val_loss: 0.5336 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7420 - val_loss: 0.5337 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.7479 - val_loss: 0.5361 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7577 - val_loss: 0.5371 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7672 - val_loss: 0.5391 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4700 - accuracy: 0.7749
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4702 - accuracy: 0.7746 - val_loss: 0.5418 - val_accuracy: 0.7259 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4204153148000759
Confusion Matrix :
 [[2829 1218]
 [1128 2919]]
Accuracy on test set:    0.7101556708673091
Sensitivity:    0.7212750185322461 	 Specificity:    0.6990363232023721
Precision  : 0.7055837563451777
Area Under Curve:    0.7101556708673091
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5952 - accuracy: 0.6770 - val_loss: 0.5492 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5494 - accuracy: 0.7201 - val_loss: 0.5403 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7319 - val_loss: 0.5372 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7387 - val_loss: 0.5406 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5133 - accuracy: 0.7453 - val_loss: 0.5366 - val_accuracy: 0.7325 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7522 - val_loss: 0.5429 - val_accuracy: 0.7241 - lr: 0.0010

Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7615 - val_loss: 0.5460 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7691 - val_loss: 0.5411 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4708 - accuracy: 0.7774 - val_loss: 0.5476 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4588 - accuracy: 0.7834
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4589 - accuracy: 0.7832 - val_loss: 0.5521 - val_accuracy: 0.7234 - lr: 0.0010
253/253 [==============================] - 0s 952us/step
Independent Testing Matthews Correlation:  0.4390833494401196
Confusion Matrix :
 [[2682 1365]
 [ 916 3131]]
Accuracy on test set:    0.7181863108475414
Sensitivity:    0.7736595008648381 	 Specificity:    0.6627131208302446
Precision  : 0.6963967971530249
Area Under Curve:    0.7181863108475414
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6832 - val_loss: 0.5457 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7227 - val_loss: 0.5419 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7340 - val_loss: 0.5370 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7427 - val_loss: 0.5362 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7485 - val_loss: 0.5380 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 6/400
253/257 [============================>.] - ETA: 0s - loss: 0.4965 - accuracy: 0.7558
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7557 - val_loss: 0.5403 - val_accuracy: 0.7246 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42082408654620024
Confusion Matrix :
 [[2856 1191]
 [1153 2894]]
Accuracy on test set:    0.7104027674820855
Sensitivity:    0.7150976031628367 	 Specificity:    0.7057079318013343
Precision  : 0.7084455324357405
Area Under Curve:    0.7104027674820856
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5984 - accuracy: 0.6742 - val_loss: 0.5540 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5520 - accuracy: 0.7186 - val_loss: 0.5434 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5356 - accuracy: 0.7292 - val_loss: 0.5432 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5242 - accuracy: 0.7357 - val_loss: 0.5426 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5130 - accuracy: 0.7445 - val_loss: 0.5433 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5027 - accuracy: 0.7526 - val_loss: 0.5406 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7618 - val_loss: 0.5485 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4792 - accuracy: 0.7677 - val_loss: 0.5480 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4651 - accuracy: 0.7770 - val_loss: 0.5520 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4532 - accuracy: 0.7845 - val_loss: 0.5559 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 11/400
256/257 [============================>.] - ETA: 0s - loss: 0.4418 - accuracy: 0.7939
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4418 - accuracy: 0.7939 - val_loss: 0.5671 - val_accuracy: 0.7175 - lr: 0.0010
253/253 [==============================] - 0s 789us/step
Independent Testing Matthews Correlation:  0.43779655832187264
Confusion Matrix :
 [[2704 1343]
 [ 941 3106]]
Accuracy on test set:    0.7178156659253768
Sensitivity:    0.7674820854954287 	 Specificity:    0.6681492463553249
Precision  : 0.6981344122274669
Area Under Curve:    0.7178156659253768
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5886 - accuracy: 0.6831 - val_loss: 0.5513 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7195 - val_loss: 0.5442 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7331 - val_loss: 0.5421 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5207 - accuracy: 0.7400 - val_loss: 0.5431 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5121 - accuracy: 0.7464 - val_loss: 0.5428 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5010 - accuracy: 0.7542 - val_loss: 0.5450 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7612 - val_loss: 0.5439 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
255/257 [============================>.] - ETA: 0s - loss: 0.4782 - accuracy: 0.7701
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7700 - val_loss: 0.5490 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 750us/step
Independent Testing Matthews Correlation:  0.46077693175266365
Confusion Matrix :
 [[3043 1004]
 [1180 2867]]
Accuracy on test set:    0.7301704966641956
Sensitivity:    0.7084259945638745 	 Specificity:    0.751914998764517
Precision  : 0.7406354947042108
Area Under Curve:    0.7301704966641956
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5908 - accuracy: 0.6835 - val_loss: 0.5515 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5499 - accuracy: 0.7190 - val_loss: 0.5427 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5345 - accuracy: 0.7299 - val_loss: 0.5420 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5231 - accuracy: 0.7403 - val_loss: 0.5409 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5133 - accuracy: 0.7478 - val_loss: 0.5414 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.7551 - val_loss: 0.5510 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7625 - val_loss: 0.5417 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4806 - accuracy: 0.7692
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4806 - accuracy: 0.7691 - val_loss: 0.5440 - val_accuracy: 0.7211 - lr: 0.0010
253/253 [==============================] - 0s 928us/step
Independent Testing Matthews Correlation:  0.4744623861690152
Confusion Matrix :
 [[3053  994]
 [1134 2913]]
Accuracy on test set:    0.7370892018779343
Sensitivity:    0.7197924388435878 	 Specificity:    0.7543859649122807
Precision  : 0.7455848477092398
Area Under Curve:    0.7370892018779343
(8094, 2560) (8094,)
Mean MCC = 0.4324 + 0.0199 and Mean AUC = 0.7157 + 0.0099
Mean Sensitivity = 0.7354 + 0.0234 and Mean Specificity = 0.6960 + 0.0328 and Mean Accuracy = 0.7157 + 0.0099
Mean Precision = 0.7083 + 0.0183





Seed   : 793180

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5861 - accuracy: 0.6869 - val_loss: 0.5559 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7251 - val_loss: 0.5500 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7335 - val_loss: 0.5451 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7425 - val_loss: 0.5529 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7510 - val_loss: 0.5475 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7590 - val_loss: 0.5495 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.7687 - val_loss: 0.5543 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4699 - accuracy: 0.7753 - val_loss: 0.5598 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4542 - accuracy: 0.7847 - val_loss: 0.5657 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4433 - accuracy: 0.7934 - val_loss: 0.5641 - val_accuracy: 0.7056 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4282 - accuracy: 0.8048 - val_loss: 0.5736 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 12/400
255/257 [============================>.] - ETA: 0s - loss: 0.4167 - accuracy: 0.8116
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4166 - accuracy: 0.8116 - val_loss: 0.5816 - val_accuracy: 0.7100 - lr: 0.0010
253/253 [==============================] - 0s 881us/step
Independent Testing Matthews Correlation:  0.4047806846957463
Confusion Matrix :
 [[2670 1378]
 [1037 3010]]
Accuracy on test set:    0.701667696108709
Sensitivity:    0.7437608104768965 	 Specificity:    0.6595849802371542
Precision  : 0.6859617137648131
Area Under Curve:    0.7016728953570253
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5849 - accuracy: 0.6873 - val_loss: 0.5529 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7248 - val_loss: 0.5473 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7335 - val_loss: 0.5505 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7412 - val_loss: 0.5431 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7500 - val_loss: 0.5524 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4999 - accuracy: 0.7556 - val_loss: 0.5456 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.7631 - val_loss: 0.5461 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7713 - val_loss: 0.5522 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4659 - accuracy: 0.7782
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.7781 - val_loss: 0.5529 - val_accuracy: 0.7135 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42017413400917436
Confusion Matrix :
 [[2772 1276]
 [1073 2974]]
Accuracy on test set:    0.7098208770846202
Sensitivity:    0.7348653323449469 	 Specificity:    0.6847826086956522
Precision  : 0.699764705882353
Area Under Curve:    0.7098239705202994
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5834 - accuracy: 0.6874 - val_loss: 0.5462 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7234 - val_loss: 0.5397 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7349 - val_loss: 0.5356 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7410 - val_loss: 0.5344 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7488 - val_loss: 0.5352 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7569 - val_loss: 0.5372 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4889 - accuracy: 0.7626 - val_loss: 0.5426 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7698 - val_loss: 0.5425 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4667 - accuracy: 0.7778 - val_loss: 0.5457 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4562 - accuracy: 0.7857 - val_loss: 0.5484 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4424 - accuracy: 0.7938 - val_loss: 0.5522 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 12/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4291 - accuracy: 0.7992
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4296 - accuracy: 0.7988 - val_loss: 0.5587 - val_accuracy: 0.7148 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41238062864227554
Confusion Matrix :
 [[2743 1304]
 [1077 2971]]
Accuracy on test set:    0.7058678196417542
Sensitivity:    0.7339426877470355 	 Specificity:    0.6777860143316037
Precision  : 0.6949707602339181
Area Under Curve:    0.7058643510393197
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5893 - accuracy: 0.6836 - val_loss: 0.5450 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7209 - val_loss: 0.5358 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7330 - val_loss: 0.5330 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7408 - val_loss: 0.5354 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7509 - val_loss: 0.5330 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7589 - val_loss: 0.5365 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7687 - val_loss: 0.5353 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4675 - accuracy: 0.7780
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.7780 - val_loss: 0.5423 - val_accuracy: 0.7234 - lr: 0.0010
253/253 [==============================] - 0s 849us/step
Independent Testing Matthews Correlation:  0.42639201333787646
Confusion Matrix :
 [[2600 1447]
 [ 891 3157]]
Accuracy on test set:    0.7111797405806053
Sensitivity:    0.779891304347826 	 Specificity:    0.6424511984185817
Precision  : 0.6857080799304952
Area Under Curve:    0.7111712513832039
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5864 - accuracy: 0.6857 - val_loss: 0.5480 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7213 - val_loss: 0.5431 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7325 - val_loss: 0.5424 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7409 - val_loss: 0.5405 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7484 - val_loss: 0.5390 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4980 - accuracy: 0.7561 - val_loss: 0.5442 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4862 - accuracy: 0.7636
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7633 - val_loss: 0.5418 - val_accuracy: 0.7237 - lr: 0.0010
253/253 [==============================] - 0s 762us/step
Independent Testing Matthews Correlation:  0.4224531530232153
Confusion Matrix :
 [[2764 1283]
 [1057 2990]]
Accuracy on test set:    0.7108969607116382
Sensitivity:    0.7388188781813689 	 Specificity:    0.6829750432419076
Precision  : 0.6997425696232156
Area Under Curve:    0.7108969607116382
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5906 - accuracy: 0.6803 - val_loss: 0.5540 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7229 - val_loss: 0.5464 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7321 - val_loss: 0.5381 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7403 - val_loss: 0.5406 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7496 - val_loss: 0.5452 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.7554 - val_loss: 0.5390 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4857 - accuracy: 0.7650 - val_loss: 0.5428 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7732 - val_loss: 0.5488 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - ETA: 0s - loss: 0.4610 - accuracy: 0.7828
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4610 - accuracy: 0.7828 - val_loss: 0.5540 - val_accuracy: 0.7249 - lr: 0.0010
253/253 [==============================] - 0s 842us/step
Independent Testing Matthews Correlation:  0.412575374230265
Confusion Matrix :
 [[2722 1325]
 [1056 2991]]
Accuracy on test set:    0.7058314801087225
Sensitivity:    0.7390659747961453 	 Specificity:    0.6725969854212998
Precision  : 0.693002780352178
Area Under Curve:    0.7058314801087225
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5867 - accuracy: 0.6867 - val_loss: 0.5523 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7217 - val_loss: 0.5396 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7314 - val_loss: 0.5377 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7426 - val_loss: 0.5376 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7490 - val_loss: 0.5384 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7614 - val_loss: 0.5396 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7675 - val_loss: 0.5450 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4700 - accuracy: 0.7759 - val_loss: 0.5459 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4561 - accuracy: 0.7847
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4561 - accuracy: 0.7847 - val_loss: 0.5587 - val_accuracy: 0.7205 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4312137731206517
Confusion Matrix :
 [[3087  960]
 [1350 2697]]
Accuracy on test set:    0.7146034099332839
Sensitivity:    0.6664195700518903 	 Specificity:    0.7627872498146775
Precision  : 0.7374897456931911
Area Under Curve:    0.714603409933284
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5910 - accuracy: 0.6812 - val_loss: 0.5564 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7210 - val_loss: 0.5442 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7326 - val_loss: 0.5382 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5210 - accuracy: 0.7396 - val_loss: 0.5361 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.7477 - val_loss: 0.5387 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7530 - val_loss: 0.5367 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.7627 - val_loss: 0.5399 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4791 - accuracy: 0.7697 - val_loss: 0.5451 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4659 - accuracy: 0.7769 - val_loss: 0.5460 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4544 - accuracy: 0.7864 - val_loss: 0.5502 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4425 - accuracy: 0.7936
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4424 - accuracy: 0.7938 - val_loss: 0.5550 - val_accuracy: 0.7227 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4420104267266343
Confusion Matrix :
 [[2803 1244]
 [1017 3030]]
Accuracy on test set:    0.7206572769953051
Sensitivity:    0.748702742772424 	 Specificity:    0.6926118112181863
Precision  : 0.7089377632194666
Area Under Curve:    0.720657276995305
(8094, 2560) (8094,)
Epoch 1/400

257/257 [==============================] - 2s 4ms/step - loss: 0.5869 - accuracy: 0.6843 - val_loss: 0.5449 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7205 - val_loss: 0.5384 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7334 - val_loss: 0.5360 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7415 - val_loss: 0.5372 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7520 - val_loss: 0.5364 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7578 - val_loss: 0.5385 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7700 - val_loss: 0.5443 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.7787 - val_loss: 0.5407 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4522 - accuracy: 0.7863 - val_loss: 0.5459 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4394 - accuracy: 0.7938 - val_loss: 0.5499 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4261 - accuracy: 0.8005 - val_loss: 0.5542 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4143 - accuracy: 0.8092 - val_loss: 0.5663 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - ETA: 0s - loss: 0.3989 - accuracy: 0.8180
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3989 - accuracy: 0.8180 - val_loss: 0.5744 - val_accuracy: 0.7213 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4578014240200798
Confusion Matrix :
 [[2893 1154]
 [1041 3006]]
Accuracy on test set:    0.7288114652829256
Sensitivity:    0.742772424017791 	 Specificity:    0.7148505065480603
Precision  : 0.7225961538461538
Area Under Curve:    0.7288114652829257
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5930 - accuracy: 0.6800 - val_loss: 0.5476 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5515 - accuracy: 0.7170 - val_loss: 0.5431 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5354 - accuracy: 0.7311 - val_loss: 0.5410 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5242 - accuracy: 0.7360 - val_loss: 0.5522 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5126 - accuracy: 0.7446 - val_loss: 0.5414 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.7543 - val_loss: 0.5419 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4883 - accuracy: 0.7629
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4883 - accuracy: 0.7628 - val_loss: 0.5444 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4713909469951112
Confusion Matrix :
 [[3084  963]
 [1179 2868]]
Accuracy on test set:    0.7353595255744997
Sensitivity:    0.7086730911786508 	 Specificity:    0.7620459599703484
Precision  : 0.7486296006264683
Area Under Curve:    0.7353595255744997
(8094, 2560) (8094,)
Mean MCC = 0.4301 + 0.0201 and Mean AUC = 0.7145 + 0.0102
Mean Sensitivity = 0.7337 + 0.0278 and Mean Specificity = 0.6952 + 0.0381 and Mean Accuracy = 0.7145 + 0.0102
Mean Precision = 0.7077 + 0.0206





Seed   : 999113
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5827 - accuracy: 0.6895 - val_loss: 0.5641 - val_accuracy: 0.7032 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5418 - accuracy: 0.7250 - val_loss: 0.5554 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5260 - accuracy: 0.7363 - val_loss: 0.5554 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7426 - val_loss: 0.5566 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5049 - accuracy: 0.7502 - val_loss: 0.5555 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7590 - val_loss: 0.5587 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4830 - accuracy: 0.7666 - val_loss: 0.5584 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7725 - val_loss: 0.5642 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 9/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4575 - accuracy: 0.7824
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4572 - accuracy: 0.7826 - val_loss: 0.5685 - val_accuracy: 0.7047 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4065072619125416
Confusion Matrix :
 [[2942 1106]
 [1298 2749]]
Accuracy on test set:    0.7030265596046943
Sensitivity:    0.679268594020262 	 Specificity:    0.7267786561264822
Precision  : 0.7130998702983139
Area Under Curve:    0.703023625073372
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5894 - accuracy: 0.6839 - val_loss: 0.5626 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5419 - accuracy: 0.7256 - val_loss: 0.5532 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5258 - accuracy: 0.7361 - val_loss: 0.5521 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.7436 - val_loss: 0.5526 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5028 - accuracy: 0.7530 - val_loss: 0.5512 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7613 - val_loss: 0.5546 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4805 - accuracy: 0.7684 - val_loss: 0.5560 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4689 - accuracy: 0.7741 - val_loss: 0.5599 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4581 - accuracy: 0.7838 - val_loss: 0.5601 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4444 - accuracy: 0.7913 - val_loss: 0.5702 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4331 - accuracy: 0.7990 - val_loss: 0.5690 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4205 - accuracy: 0.8069 - val_loss: 0.5831 - val_accuracy: 0.7139 - lr: 0.0010

Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4087 - accuracy: 0.8132 - val_loss: 0.5790 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 14/400
243/257 [===========================>..] - ETA: 0s - loss: 0.3964 - accuracy: 0.8214
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3963 - accuracy: 0.8215 - val_loss: 0.5955 - val_accuracy: 0.7064 - lr: 0.0010
253/253 [==============================] - 0s 776us/step
Independent Testing Matthews Correlation:  0.4139673012117108
Confusion Matrix :
 [[2875 1173]
 [1199 2848]]
Accuracy on test set:    0.7069796170475602
Sensitivity:    0.7037311588831233 	 Specificity:    0.7102272727272727
Precision  : 0.7082815220094504
Area Under Curve:    0.7069792158051981
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5859 - accuracy: 0.6849 - val_loss: 0.5505 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7244 - val_loss: 0.5444 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7331 - val_loss: 0.5410 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7433 - val_loss: 0.5406 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7495 - val_loss: 0.5463 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7588 - val_loss: 0.5442 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7666 - val_loss: 0.5528 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4697 - accuracy: 0.7760 - val_loss: 0.5486 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4562 - accuracy: 0.7838
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4569 - accuracy: 0.7831 - val_loss: 0.5540 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4335204974444565
Confusion Matrix :
 [[2777 1270]
 [1026 3022]]
Accuracy on test set:    0.7163681284743669
Sensitivity:    0.7465415019762845 	 Specificity:    0.6861872992340005
Precision  : 0.7041006523765144
Area Under Curve:    0.7163644006051426
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5876 - accuracy: 0.6840 - val_loss: 0.5494 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7219 - val_loss: 0.5384 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7335 - val_loss: 0.5347 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7418 - val_loss: 0.5380 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7504 - val_loss: 0.5392 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 6/400
253/257 [============================>.] - ETA: 0s - loss: 0.4945 - accuracy: 0.7578
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.7576 - val_loss: 0.5406 - val_accuracy: 0.7226 - lr: 0.0010
253/253 [==============================] - 0s 776us/step
Independent Testing Matthews Correlation:  0.4165555695828607
Confusion Matrix :
 [[2685 1362]
 [1006 3042]]
Accuracy on test set:    0.7074737492279185
Sensitivity:    0.7514822134387352 	 Specificity:    0.6634544106745738
Precision  : 0.6907356948228883
Area Under Curve:    0.7074683120566546
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5871 - accuracy: 0.6821 - val_loss: 0.5474 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7219 - val_loss: 0.5417 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7334 - val_loss: 0.5382 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7416 - val_loss: 0.5368 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7484 - val_loss: 0.5403 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7565 - val_loss: 0.5412 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 7/400
250/257 [============================>.] - ETA: 0s - loss: 0.4830 - accuracy: 0.7654
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7652 - val_loss: 0.5432 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41653944623818234
Confusion Matrix :
 [[3089  958]
 [1414 2633]]
Accuracy on test set:    0.7069434148752162
Sensitivity:    0.6506053867062022 	 Specificity:    0.7632814430442303
Precision  : 0.7332219437482596
Area Under Curve:    0.7069434148752163
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5910 - accuracy: 0.6819 - val_loss: 0.5516 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7232 - val_loss: 0.5441 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7318 - val_loss: 0.5414 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7420 - val_loss: 0.5452 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7482 - val_loss: 0.5391 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7557 - val_loss: 0.5436 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7670 - val_loss: 0.5408 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7739 - val_loss: 0.5465 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4592 - accuracy: 0.7825
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4592 - accuracy: 0.7825 - val_loss: 0.5518 - val_accuracy: 0.7226 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4324234556887547
Confusion Matrix :
 [[2829 1218]
 [1080 2967]]
Accuracy on test set:    0.7160859896219421
Sensitivity:    0.7331356560415122 	 Specificity:    0.6990363232023721
Precision  : 0.7089605734767025
Area Under Curve:    0.7160859896219421
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5979 - accuracy: 0.6769 - val_loss: 0.5530 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5513 - accuracy: 0.7197 - val_loss: 0.5408 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5366 - accuracy: 0.7294 - val_loss: 0.5404 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5254 - accuracy: 0.7371 - val_loss: 0.5391 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.7462 - val_loss: 0.5384 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7534 - val_loss: 0.5450 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4891 - accuracy: 0.7628
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.7622 - val_loss: 0.5461 - val_accuracy: 0.7213 - lr: 0.0010
253/253 [==============================] - 0s 703us/step
Independent Testing Matthews Correlation:  0.43498586998515637
Confusion Matrix :
 [[2679 1368]
 [ 929 3118]]
Accuracy on test set:    0.7162095379293304
Sensitivity:    0.7704472448727453 	 Specificity:    0.6619718309859155
Precision  : 0.6950512706197057
Area Under Curve:    0.7162095379293304
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5906 - accuracy: 0.6837 - val_loss: 0.5535 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5485 - accuracy: 0.7193 - val_loss: 0.5387 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5357 - accuracy: 0.7296 - val_loss: 0.5402 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5245 - accuracy: 0.7379 - val_loss: 0.5454 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5140 - accuracy: 0.7436 - val_loss: 0.5399 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5033 - accuracy: 0.7532 - val_loss: 0.5421 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7621 - val_loss: 0.5454 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7697 - val_loss: 0.5452 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7786 - val_loss: 0.5506 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4485 - accuracy: 0.7901 - val_loss: 0.5477 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 11/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4379 - accuracy: 0.7967
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4376 - accuracy: 0.7966 - val_loss: 0.5564 - val_accuracy: 0.7237 - lr: 0.0010
253/253 [==============================] - 0s 919us/step
Independent Testing Matthews Correlation:  0.4371165270603039
Confusion Matrix :
 [[2901 1146]
 [1132 2915]]
Accuracy on test set:    0.7185569557697059
Sensitivity:    0.7202866320731406 	 Specificity:    0.7168272794662713
Precision  : 0.7178034966756957
Area Under Curve:    0.718556955769706
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5912 - accuracy: 0.6825 - val_loss: 0.5504 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5484 - accuracy: 0.7197 - val_loss: 0.5431 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5345 - accuracy: 0.7298 - val_loss: 0.5415 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5231 - accuracy: 0.7377 - val_loss: 0.5444 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7458 - val_loss: 0.5479 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4989 - accuracy: 0.7554 - val_loss: 0.5403 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.7638 - val_loss: 0.5458 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4756 - accuracy: 0.7716 - val_loss: 0.5458 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4620 - accuracy: 0.7827 - val_loss: 0.5472 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4492 - accuracy: 0.7890 - val_loss: 0.5570 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4363 - accuracy: 0.7967
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4363 - accuracy: 0.7967 - val_loss: 0.5646 - val_accuracy: 0.7238 - lr: 0.0010
253/253 [==============================] - 0s 694us/step
Independent Testing Matthews Correlation:  0.4647494093355528
Confusion Matrix :
 [[3024 1023]
 [1144 2903]]
Accuracy on test set:    0.7322708178897949
Sensitivity:    0.717321472695824 	 Specificity:    0.7472201630837657
Precision  : 0.739429444727458
Area Under Curve:    0.732270817889795
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5968 - accuracy: 0.6774 - val_loss: 0.5562 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5530 - accuracy: 0.7161 - val_loss: 0.5472 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5378 - accuracy: 0.7292 - val_loss: 0.5420 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5249 - accuracy: 0.7373 - val_loss: 0.5438 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7459 - val_loss: 0.5417 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.7530 - val_loss: 0.5468 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4918 - accuracy: 0.7604 - val_loss: 0.5474 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4773 - accuracy: 0.7706
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4776 - accuracy: 0.7702 - val_loss: 0.5491 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 914us/step
Independent Testing Matthews Correlation:  0.46175699919104857
Confusion Matrix :
 [[3212  835]
 [1359 2688]]
Accuracy on test set:    0.7289350135903138
Sensitivity:    0.6641957005189029 	 Specificity:    0.7936743266617248
Precision  : 0.7629860913993756
Area Under Curve:    0.7289350135903138
(8094, 2560) (8094,)
Mean MCC = 0.4318 + 0.0186 and Mean AUC = 0.7153 + 0.0092
Mean Sensitivity = 0.7137 + 0.0373 and Mean Specificity = 0.7169 + 0.0403 and Mean Accuracy = 0.7153 + 0.0092
Mean Precision = 0.7174 + 0.0209





Seed   : 56926
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5855 - accuracy: 0.6851 - val_loss: 0.5583 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5428 - accuracy: 0.7250 - val_loss: 0.5512 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 3/400

257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7347 - val_loss: 0.5495 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7430 - val_loss: 0.5497 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7510 - val_loss: 0.5599 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7577 - val_loss: 0.5557 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7675 - val_loss: 0.5555 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 8/400
252/257 [============================>.] - ETA: 0s - loss: 0.4728 - accuracy: 0.7738
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4728 - accuracy: 0.7737 - val_loss: 0.5576 - val_accuracy: 0.7105 - lr: 0.0010
253/253 [==============================] - 0s 873us/step
Independent Testing Matthews Correlation:  0.4026628700111675
Confusion Matrix :
 [[2919 1129]
 [1290 2757]]
Accuracy on test set:    0.7011735639283508
Sensitivity:    0.6812453669384729 	 Specificity:    0.7210968379446641
Precision  : 0.7094698919197118
Area Under Curve:    0.7011711024415686
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5897 - accuracy: 0.6832 - val_loss: 0.5608 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7236 - val_loss: 0.5512 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7360 - val_loss: 0.5520 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7423 - val_loss: 0.5537 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7506 - val_loss: 0.5511 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7557 - val_loss: 0.5541 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 7/400
253/257 [============================>.] - ETA: 0s - loss: 0.4884 - accuracy: 0.7635
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7638 - val_loss: 0.5619 - val_accuracy: 0.7094 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41965931763116754
Confusion Matrix :
 [[2627 1421]
 [ 940 3107]]
Accuracy on test set:    0.7083384805435454
Sensitivity:    0.7677291821102051 	 Specificity:    0.6489624505928854
Precision  : 0.6861749116607774
Area Under Curve:    0.7083458163515453
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5908 - accuracy: 0.6798 - val_loss: 0.5582 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7226 - val_loss: 0.5435 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7347 - val_loss: 0.5461 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7443 - val_loss: 0.5424 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7501 - val_loss: 0.5412 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7585 - val_loss: 0.5429 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4806 - accuracy: 0.7694 - val_loss: 0.5448 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4680 - accuracy: 0.7766 - val_loss: 0.5542 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4533 - accuracy: 0.7860 - val_loss: 0.5591 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4409 - accuracy: 0.7938 - val_loss: 0.5612 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 11/400
251/257 [============================>.] - ETA: 0s - loss: 0.4272 - accuracy: 0.8028
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4273 - accuracy: 0.8026 - val_loss: 0.5706 - val_accuracy: 0.7106 - lr: 0.0010
253/253 [==============================] - 0s 783us/step
Independent Testing Matthews Correlation:  0.4085259621973614
Confusion Matrix :
 [[2843 1204]
 [1190 2858]]
Accuracy on test set:    0.7042618900555899
Sensitivity:    0.7060276679841897 	 Specificity:    0.7024956758092414
Precision  : 0.7035942885278188
Area Under Curve:    0.7042616718967156
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5915 - accuracy: 0.6815 - val_loss: 0.5528 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7228 - val_loss: 0.5432 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7311 - val_loss: 0.5425 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.7406 - val_loss: 0.5440 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7489 - val_loss: 0.5454 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7555 - val_loss: 0.5430 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7645 - val_loss: 0.5503 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4749 - accuracy: 0.7720 - val_loss: 0.5489 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4641 - accuracy: 0.7798 - val_loss: 0.5519 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4511 - accuracy: 0.7890 - val_loss: 0.5588 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4394 - accuracy: 0.7955 - val_loss: 0.5671 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4268 - accuracy: 0.8038
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4268 - accuracy: 0.8039 - val_loss: 0.5673 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 839us/step
Independent Testing Matthews Correlation:  0.4162077426101898
Confusion Matrix :
 [[2843 1204]
 [1159 2889]]
Accuracy on test set:    0.7080914144533663
Sensitivity:    0.7136857707509882 	 Specificity:    0.7024956758092414
Precision  : 0.7058392377229417
Area Under Curve:    0.7080907232801148
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5898 - accuracy: 0.6805 - val_loss: 0.5471 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7212 - val_loss: 0.5360 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7327 - val_loss: 0.5378 - val_accuracy: 0.7285 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7416 - val_loss: 0.5389 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7495 - val_loss: 0.5381 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7554 - val_loss: 0.5387 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4856 - accuracy: 0.7650 - val_loss: 0.5403 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4734 - accuracy: 0.7725
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4734 - accuracy: 0.7725 - val_loss: 0.5435 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41643123246571806
Confusion Matrix :
 [[2904 1143]
 [1219 2828]]
Accuracy on test set:    0.708178897949098
Sensitivity:    0.6987892265875958 	 Specificity:    0.7175685693106004
Precision  : 0.7121631830773105
Area Under Curve:    0.7081788979490982
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5875 - accuracy: 0.6848 - val_loss: 0.5550 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7215 - val_loss: 0.5439 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7333 - val_loss: 0.5472 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7422 - val_loss: 0.5391 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7502 - val_loss: 0.5433 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7591 - val_loss: 0.5415 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4786 - accuracy: 0.7697 - val_loss: 0.5431 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4658 - accuracy: 0.7782 - val_loss: 0.5478 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4525 - accuracy: 0.7863 - val_loss: 0.5479 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4384 - accuracy: 0.7951 - val_loss: 0.5559 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4259 - accuracy: 0.8028 - val_loss: 0.5608 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4138 - accuracy: 0.8109 - val_loss: 0.5697 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3999 - accuracy: 0.8195 - val_loss: 0.5717 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 14/400
255/257 [============================>.] - ETA: 0s - loss: 0.3871 - accuracy: 0.8262
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3871 - accuracy: 0.8262 - val_loss: 0.5905 - val_accuracy: 0.7246 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4113915373359434
Confusion Matrix :
 [[2569 1478]
 [ 920 3127]]
Accuracy on test set:    0.7037311588831233
Sensitivity:    0.7726711144057327 	 Specificity:    0.634791203360514
Precision  : 0.6790445168295332
Area Under Curve:    0.7037311588831234
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5881 - accuracy: 0.6845 - val_loss: 0.5480 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7234 - val_loss: 0.5395 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7325 - val_loss: 0.5401 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7407 - val_loss: 0.5398 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7503 - val_loss: 0.5414 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7565 - val_loss: 0.5408 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7662 - val_loss: 0.5466 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4682 - accuracy: 0.7767 - val_loss: 0.5472 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4546 - accuracy: 0.7833 - val_loss: 0.5544 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4431 - accuracy: 0.7932 - val_loss: 0.5584 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 11/400
251/257 [============================>.] - ETA: 0s - loss: 0.4312 - accuracy: 0.8001
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4311 - accuracy: 0.8004 - val_loss: 0.5666 - val_accuracy: 0.7209 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4155064382552069
Confusion Matrix :
 [[2731 1316]
 [1053 2994]]
Accuracy on test set:    0.7073140597973808
Sensitivity:    0.7398072646404744 	 Specificity:    0.6748208549542871
Precision  : 0.6946635730858469
Area Under Curve:    0.7073140597973807
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5910 - accuracy: 0.6818 - val_loss: 0.5489 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5499 - accuracy: 0.7199 - val_loss: 0.5418 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5345 - accuracy: 0.7313 - val_loss: 0.5382 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5226 - accuracy: 0.7378 - val_loss: 0.5383 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7483 - val_loss: 0.5392 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4985 - accuracy: 0.7562 - val_loss: 0.5406 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7641 - val_loss: 0.5403 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7725 - val_loss: 0.5472 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4613 - accuracy: 0.7812
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4613 - accuracy: 0.7812 - val_loss: 0.5535 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 857us/step
Independent Testing Matthews Correlation:  0.43845152983952473
Confusion Matrix :
 [[2804 1243]
 [1032 3015]]
Accuracy on test set:    0.7189276006918706
Sensitivity:    0.7449962935507783 	 Specificity:    0.6928589078329627
Precision  : 0.7080789102865195
Area Under Curve:    0.7189276006918704
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5903 - accuracy: 0.6807 - val_loss: 0.5507 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5481 - accuracy: 0.7217 - val_loss: 0.5438 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7305 - val_loss: 0.5423 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7402 - val_loss: 0.5417 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7510 - val_loss: 0.5497 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7591 - val_loss: 0.5432 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7677 - val_loss: 0.5446 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7767 - val_loss: 0.5479 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4547 - accuracy: 0.7848 - val_loss: 0.5608 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4456 - accuracy: 0.7908 - val_loss: 0.5653 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4297 - accuracy: 0.8001
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4299 - accuracy: 0.8002 - val_loss: 0.5651 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4594929039747992
Confusion Matrix :
 [[3003 1044]
 [1144 2903]]
Accuracy on test set:    0.729676303434643
Sensitivity:    0.717321472695824 	 Specificity:    0.7420311341734618
Precision  : 0.7354953128958703
Area Under Curve:    0.7296763034346427
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5921 - accuracy: 0.6819 - val_loss: 0.5500 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5484 - accuracy: 0.7198 - val_loss: 0.5469 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7306 - val_loss: 0.5439 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.7399 - val_loss: 0.5412 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7502 - val_loss: 0.5433 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7545 - val_loss: 0.5431 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7647 - val_loss: 0.5449 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4748 - accuracy: 0.7727 - val_loss: 0.5522 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4636 - accuracy: 0.7795 - val_loss: 0.5490 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4515 - accuracy: 0.7880 - val_loss: 0.5560 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4388 - accuracy: 0.7973 - val_loss: 0.5566 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4276 - accuracy: 0.8028 - val_loss: 0.5666 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4149 - accuracy: 0.8099 - val_loss: 0.5793 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4033 - accuracy: 0.8156 - val_loss: 0.5805 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 15/400
255/257 [============================>.] - ETA: 0s - loss: 0.3944 - accuracy: 0.8217
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3943 - accuracy: 0.8218 - val_loss: 0.5806 - val_accuracy: 0.7139 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46395796040047477
Confusion Matrix :
 [[3046 1001]
 [1170 2877]]
Accuracy on test set:    0.7317766246602422
Sensitivity:    0.7108969607116382 	 Specificity:    0.752656288608846
Precision  : 0.7418772563176895
Area Under Curve:    0.7317766246602421
(8094, 2560) (8094,)
Mean MCC = 0.4252 + 0.0203 and Mean AUC = 0.7121 + 0.0103
Mean Sensitivity = 0.7253 + 0.0284 and Mean Specificity = 0.6990 + 0.0358 and Mean Accuracy = 0.7121 + 0.0103
Mean Precision = 0.7076 + 0.0185





Seed   : 73701
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5834 - accuracy: 0.6876 - val_loss: 0.5542 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7223 - val_loss: 0.5478 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5263 - accuracy: 0.7367 - val_loss: 0.5471 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7433 - val_loss: 0.5479 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7513 - val_loss: 0.5515 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7575 - val_loss: 0.5505 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4841 - accuracy: 0.7665 - val_loss: 0.5521 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4727 - accuracy: 0.7741 - val_loss: 0.5518 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4602 - accuracy: 0.7816 - val_loss: 0.5620 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4457 - accuracy: 0.7911 - val_loss: 0.5590 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4334 - accuracy: 0.8004 - val_loss: 0.5650 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4210 - accuracy: 0.8089 - val_loss: 0.5850 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 13/400
250/257 [============================>.] - ETA: 0s - loss: 0.4096 - accuracy: 0.8128
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4098 - accuracy: 0.8127 - val_loss: 0.5757 - val_accuracy: 0.7113 - lr: 0.0010
253/253 [==============================] - 0s 745us/step
Independent Testing Matthews Correlation:  0.389751878696462
Confusion Matrix :
 [[2803 1245]
 [1225 2822]]
Accuracy on test set:    0.6948733786287832
Sensitivity:    0.6973066468989375 	 Specificity:    0.6924407114624506
Precision  : 0.6938775510204082
Area Under Curve:    0.6948736791806941
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5858 - accuracy: 0.6855 - val_loss: 0.5582 - val_accuracy: 0.7049 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7259 - val_loss: 0.5479 - val_accuracy: 0.7076 - lr: 0.0010

Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5274 - accuracy: 0.7354 - val_loss: 0.5457 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7427 - val_loss: 0.5493 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5052 - accuracy: 0.7505 - val_loss: 0.5471 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7576 - val_loss: 0.5479 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4836 - accuracy: 0.7671 - val_loss: 0.5542 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4736 - accuracy: 0.7739 - val_loss: 0.5526 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.7852 - val_loss: 0.5546 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4472 - accuracy: 0.7910
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4478 - accuracy: 0.7907 - val_loss: 0.5597 - val_accuracy: 0.7079 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42892697191034945
Confusion Matrix :
 [[2781 1267]
 [1047 3000]]
Accuracy on test set:    0.7141445336627548
Sensitivity:    0.7412898443291327 	 Specificity:    0.6870059288537549
Precision  : 0.7030700726505742
Area Under Curve:    0.7141478865914438
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5844 - accuracy: 0.6879 - val_loss: 0.5498 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7245 - val_loss: 0.5394 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.7354 - val_loss: 0.5385 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7434 - val_loss: 0.5390 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7508 - val_loss: 0.5389 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7587 - val_loss: 0.5451 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 7/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4832 - accuracy: 0.7669
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7672 - val_loss: 0.5449 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 988us/step
Independent Testing Matthews Correlation:  0.4136142961630419
Confusion Matrix :
 [[2914 1133]
 [1241 2807]]
Accuracy on test set:    0.7067325509573811
Sensitivity:    0.6934288537549407 	 Specificity:    0.7200395354583642
Precision  : 0.7124365482233502
Area Under Curve:    0.7067341946066524
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5861 - accuracy: 0.6861 - val_loss: 0.5479 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7210 - val_loss: 0.5417 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7327 - val_loss: 0.5378 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7420 - val_loss: 0.5382 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7487 - val_loss: 0.5356 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7557 - val_loss: 0.5442 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.7643 - val_loss: 0.5400 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4767 - accuracy: 0.7712 - val_loss: 0.5422 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4648 - accuracy: 0.7808 - val_loss: 0.5442 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4551 - accuracy: 0.7858 - val_loss: 0.5494 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4414 - accuracy: 0.7960 - val_loss: 0.5543 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4276 - accuracy: 0.8041 - val_loss: 0.5589 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 13/400
256/257 [============================>.] - ETA: 0s - loss: 0.4154 - accuracy: 0.8124
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4155 - accuracy: 0.8123 - val_loss: 0.5693 - val_accuracy: 0.7160 - lr: 0.0010
253/253 [==============================] - 0s 842us/step
Independent Testing Matthews Correlation:  0.4293882533780298
Confusion Matrix :
 [[2701 1346]
 [ 971 3077]]
Accuracy on test set:    0.713773934527486
Sensitivity:    0.7601284584980237 	 Specificity:    0.6674079565109958
Precision  : 0.6956816640289396
Area Under Curve:    0.7137682075045098
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5864 - accuracy: 0.6834 - val_loss: 0.5466 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7231 - val_loss: 0.5423 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7335 - val_loss: 0.5405 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7398 - val_loss: 0.5388 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7472 - val_loss: 0.5399 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7553 - val_loss: 0.5429 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7638 - val_loss: 0.5479 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4770 - accuracy: 0.7697 - val_loss: 0.5529 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4644 - accuracy: 0.7787 - val_loss: 0.5597 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4520 - accuracy: 0.7875
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4523 - accuracy: 0.7872 - val_loss: 0.5596 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 859us/step
Independent Testing Matthews Correlation:  0.4236555530412235
Confusion Matrix :
 [[2830 1217]
 [1116 2931]]
Accuracy on test set:    0.7117617988633556
Sensitivity:    0.7242401779095626 	 Specificity:    0.6992834198171485
Precision  : 0.7066055930568949
Area Under Curve:    0.7117617988633556
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5841 - accuracy: 0.6878 - val_loss: 0.5468 - val_accuracy: 0.7281 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7241 - val_loss: 0.5423 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7334 - val_loss: 0.5388 - val_accuracy: 0.7292 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7431 - val_loss: 0.5425 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7506 - val_loss: 0.5438 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7560 - val_loss: 0.5405 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7646 - val_loss: 0.5431 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4725 - accuracy: 0.7736
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4734 - accuracy: 0.7731 - val_loss: 0.5455 - val_accuracy: 0.7242 - lr: 0.0010
253/253 [==============================] - 0s 798us/step
Independent Testing Matthews Correlation:  0.4353020500250034
Confusion Matrix :
 [[2666 1381]
 [ 916 3131]]
Accuracy on test set:    0.7162095379293304
Sensitivity:    0.7736595008648381 	 Specificity:    0.6587595749938225
Precision  : 0.693927304964539
Area Under Curve:    0.7162095379293305
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5859 - accuracy: 0.6857 - val_loss: 0.5486 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7224 - val_loss: 0.5374 - val_accuracy: 0.7352 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7324 - val_loss: 0.5384 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7423 - val_loss: 0.5356 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7491 - val_loss: 0.5363 - val_accuracy: 0.7329 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7567 - val_loss: 0.5337 - val_accuracy: 0.7333 - lr: 0.0010
Epoch 7/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4840 - accuracy: 0.7665
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.7662 - val_loss: 0.5359 - val_accuracy: 0.7321 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4222287157501291
Confusion Matrix :
 [[2709 1338]
 [1006 3041]]
Accuracy on test set:    0.7104027674820855
Sensitivity:    0.7514208055349642 	 Specificity:    0.6693847294292068
Precision  : 0.6944507878511076
Area Under Curve:    0.7104027674820854
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5894 - accuracy: 0.6828 - val_loss: 0.5504 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7212 - val_loss: 0.5408 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7319 - val_loss: 0.5403 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7401 - val_loss: 0.5348 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7492 - val_loss: 0.5352 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7567 - val_loss: 0.5359 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7643 - val_loss: 0.5412 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.7727 - val_loss: 0.5416 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4606 - accuracy: 0.7819
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4611 - accuracy: 0.7813 - val_loss: 0.5405 - val_accuracy: 0.7246 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44657574065521805
Confusion Matrix :
 [[2850 1197]
 [1044 3003]]
Accuracy on test set:    0.7231282431430689
Sensitivity:    0.7420311341734618 	 Specificity:    0.704225352112676
Precision  : 0.715
Area Under Curve:    0.7231282431430689
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5889 - accuracy: 0.6846 - val_loss: 0.5513 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7202 - val_loss: 0.5474 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5340 - accuracy: 0.7297 - val_loss: 0.5436 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5225 - accuracy: 0.7385 - val_loss: 0.5441 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5128 - accuracy: 0.7454 - val_loss: 0.5400 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5033 - accuracy: 0.7522 - val_loss: 0.5411 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.7625 - val_loss: 0.5427 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.7687 - val_loss: 0.5468 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7757 - val_loss: 0.5473 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4573 - accuracy: 0.7841 - val_loss: 0.5517 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4449 - accuracy: 0.7917 - val_loss: 0.5617 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 12/400
249/257 [============================>.] - ETA: 0s - loss: 0.4339 - accuracy: 0.8001
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4338 - accuracy: 0.8003 - val_loss: 0.5641 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 907us/step
Independent Testing Matthews Correlation:  0.4532140581696074
Confusion Matrix :
 [[2914 1133]
 [1080 2967]]
Accuracy on test set:    0.7265875957499383
Sensitivity:    0.7331356560415122 	 Specificity:    0.7200395354583642
Precision  : 0.7236585365853658
Area Under Curve:    0.7265875957499381
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5928 - accuracy: 0.6811 - val_loss: 0.5560 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5493 - accuracy: 0.7200 - val_loss: 0.5505 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5349 - accuracy: 0.7310 - val_loss: 0.5547 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5240 - accuracy: 0.7389 - val_loss: 0.5469 - val_accuracy: 0.7186 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5126 - accuracy: 0.7466 - val_loss: 0.5476 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
254/257 [============================>.] - ETA: 0s - loss: 0.5000 - accuracy: 0.7558
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.7557 - val_loss: 0.5579 - val_accuracy: 0.7149 - lr: 0.0010
253/253 [==============================] - 0s 841us/step
Independent Testing Matthews Correlation:  0.4864209320394898
Confusion Matrix :
 [[2827 1220]
 [ 866 3181]]
Accuracy on test set:    0.7422782307882382
Sensitivity:    0.7860143316036571 	 Specificity:    0.6985421299728194
Precision  : 0.7227902749375142
Area Under Curve:    0.7422782307882383
(8094, 2560) (8094,)
Mean MCC = 0.4329 + 0.0244 and Mean AUC = 0.7160 + 0.0120
Mean Sensitivity = 0.7403 + 0.0284 and Mean Specificity = 0.6917 + 0.0202 and Mean Accuracy = 0.7160 + 0.0120
Mean Precision = 0.7061 + 0.0112





Seed   : 628753
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5821 - accuracy: 0.6894 - val_loss: 0.5526 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5413 - accuracy: 0.7259 - val_loss: 0.5466 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5258 - accuracy: 0.7364 - val_loss: 0.5456 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5146 - accuracy: 0.7427 - val_loss: 0.5475 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7510 - val_loss: 0.5483 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7561 - val_loss: 0.5470 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4862 - accuracy: 0.7644 - val_loss: 0.5523 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4740 - accuracy: 0.7726 - val_loss: 0.5526 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4647 - accuracy: 0.7799 - val_loss: 0.5563 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4523 - accuracy: 0.7861 - val_loss: 0.5607 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - ETA: 0s - loss: 0.4407 - accuracy: 0.7940
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4407 - accuracy: 0.7940 - val_loss: 0.5695 - val_accuracy: 0.7120 - lr: 0.0010
253/253 [==============================] - 0s 838us/step
Independent Testing Matthews Correlation:  0.4032095530556622
Confusion Matrix :
 [[2672 1376]
 [1045 3002]]
Accuracy on test set:    0.7009264978381717
Sensitivity:    0.7417840375586855 	 Specificity:    0.6600790513833992
Precision  : 0.685701233439927
Area Under Curve:    0.7009315444710422
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5853 - accuracy: 0.6862 - val_loss: 0.5547 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7248 - val_loss: 0.5456 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5268 - accuracy: 0.7350 - val_loss: 0.5456 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5148 - accuracy: 0.7435 - val_loss: 0.5462 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7507 - val_loss: 0.5426 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7587 - val_loss: 0.5427 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7685 - val_loss: 0.5510 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4689 - accuracy: 0.7748 - val_loss: 0.5513 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4564 - accuracy: 0.7850 - val_loss: 0.5583 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4470 - accuracy: 0.7908 - val_loss: 0.5561 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4332 - accuracy: 0.7990 - val_loss: 0.5637 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4188 - accuracy: 0.8074 - val_loss: 0.5693 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 13/400
256/257 [============================>.] - ETA: 0s - loss: 0.4079 - accuracy: 0.8141
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4080 - accuracy: 0.8141 - val_loss: 0.5856 - val_accuracy: 0.7149 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4103504797988474
Confusion Matrix :
 [[2582 1466]
 [ 935 3112]]
Accuracy on test set:    0.7033971587399629
Sensitivity:    0.768964665184087 	 Specificity:    0.6378458498023716
Precision  : 0.6797728265618174
Area Under Curve:    0.7034052574932294
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5842 - accuracy: 0.6868 - val_loss: 0.5469 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7219 - val_loss: 0.5377 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7334 - val_loss: 0.5401 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7410 - val_loss: 0.5366 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7497 - val_loss: 0.5386 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7556 - val_loss: 0.5362 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.7637 - val_loss: 0.5406 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4738 - accuracy: 0.7734 - val_loss: 0.5444 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4628 - accuracy: 0.7794
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4630 - accuracy: 0.7793 - val_loss: 0.5472 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 816us/step
Independent Testing Matthews Correlation:  0.4384918494306585
Confusion Matrix :
 [[2987 1060]
 [1214 2834]]
Accuracy on test set:    0.7190858554663373
Sensitivity:    0.700098814229249 	 Specificity:    0.7380775883370397
Precision  : 0.7277863379558295
Area Under Curve:    0.7190882012831445
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5903 - accuracy: 0.6832 - val_loss: 0.5485 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5481 - accuracy: 0.7207 - val_loss: 0.5377 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7301 - val_loss: 0.5359 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5223 - accuracy: 0.7375 - val_loss: 0.5365 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.7461 - val_loss: 0.5354 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5010 - accuracy: 0.7546 - val_loss: 0.5348 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.7602 - val_loss: 0.5454 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7659 - val_loss: 0.5418 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7750 - val_loss: 0.5398 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4597 - accuracy: 0.7810
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4601 - accuracy: 0.7807 - val_loss: 0.5448 - val_accuracy: 0.7266 - lr: 0.0010
253/253 [==============================] - 0s 734us/step
Independent Testing Matthews Correlation:  0.4192092686671331
Confusion Matrix :
 [[2793 1254]
 [1098 2950]]
Accuracy on test set:    0.7094502779493514
Sensitivity:    0.7287549407114624 	 Specificity:    0.6901408450704225
Precision  : 0.7017126546146527
Area Under Curve:    0.7094478928909425
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5945 - accuracy: 0.6778 - val_loss: 0.5518 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7200 - val_loss: 0.5429 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7312 - val_loss: 0.5409 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5224 - accuracy: 0.7354 - val_loss: 0.5445 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.7440 - val_loss: 0.5436 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5010 - accuracy: 0.7541 - val_loss: 0.5385 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.7616 - val_loss: 0.5445 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.7700 - val_loss: 0.5451 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7798 - val_loss: 0.5500 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4487 - accuracy: 0.7882 - val_loss: 0.5550 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4356 - accuracy: 0.7960 - val_loss: 0.5621 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4218 - accuracy: 0.8035 - val_loss: 0.5693 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4097 - accuracy: 0.8140 - val_loss: 0.5732 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - ETA: 0s - loss: 0.3972 - accuracy: 0.8184
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3972 - accuracy: 0.8184 - val_loss: 0.5812 - val_accuracy: 0.7183 - lr: 0.0010
253/253 [==============================] - 0s 737us/step
Independent Testing Matthews Correlation:  0.40829367384412063
Confusion Matrix :
 [[2807 1240]
 [1155 2892]]
Accuracy on test set:    0.7041018038052879
Sensitivity:    0.7146034099332839 	 Specificity:    0.6936001976772919
Precision  : 0.6999031945788964
Area Under Curve:    0.704101803805288
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5937 - accuracy: 0.6787 - val_loss: 0.5495 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7212 - val_loss: 0.5420 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5341 - accuracy: 0.7303 - val_loss: 0.5452 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5214 - accuracy: 0.7402 - val_loss: 0.5380 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7476 - val_loss: 0.5385 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.7574 - val_loss: 0.5441 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7648 - val_loss: 0.5474 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4695 - accuracy: 0.7775 - val_loss: 0.5472 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.7828 - val_loss: 0.5527 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4426 - accuracy: 0.7927 - val_loss: 0.5537 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4307 - accuracy: 0.7992
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4308 - accuracy: 0.7992 - val_loss: 0.5629 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 730us/step
Independent Testing Matthews Correlation:  0.4307432648690698
Confusion Matrix :
 [[2927 1120]
 [1184 2863]]
Accuracy on test set:    0.7153446997776131
Sensitivity:    0.707437608104769 	 Specificity:    0.7232517914504571
Precision  : 0.718804920913884
Area Under Curve:    0.715344699777613
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5916 - accuracy: 0.6800 - val_loss: 0.5438 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7231 - val_loss: 0.5402 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7320 - val_loss: 0.5330 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7408 - val_loss: 0.5352 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7486 - val_loss: 0.5392 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.7573 - val_loss: 0.5393 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7651 - val_loss: 0.5435 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4714 - accuracy: 0.7735
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7734 - val_loss: 0.5416 - val_accuracy: 0.7251 - lr: 0.0010

253/253 [==============================] - 0s 844us/step
Independent Testing Matthews Correlation:  0.42978574792972546
Confusion Matrix :
 [[2972 1075]
 [1234 2813]]
Accuracy on test set:    0.7147269582406721
Sensitivity:    0.69508277736595 	 Specificity:    0.7343711391153941
Precision  : 0.7235082304526749
Area Under Curve:    0.7147269582406721
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5883 - accuracy: 0.6849 - val_loss: 0.5421 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7234 - val_loss: 0.5344 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7328 - val_loss: 0.5342 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7400 - val_loss: 0.5313 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7488 - val_loss: 0.5291 - val_accuracy: 0.7336 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7589 - val_loss: 0.5358 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7647 - val_loss: 0.5407 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.7751 - val_loss: 0.5394 - val_accuracy: 0.7316 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4595 - accuracy: 0.7832 - val_loss: 0.5432 - val_accuracy: 0.7336 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4471 - accuracy: 0.7899
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4479 - accuracy: 0.7893 - val_loss: 0.5414 - val_accuracy: 0.7311 - lr: 0.0010
253/253 [==============================] - 0s 840us/step
Independent Testing Matthews Correlation:  0.426851011742998
Confusion Matrix :
 [[2840 1207]
 [1113 2934]]
Accuracy on test set:    0.713367926859402
Sensitivity:    0.7249814677538917 	 Specificity:    0.7017543859649122
Precision  : 0.7085245109876841
Area Under Curve:    0.713367926859402
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5913 - accuracy: 0.6821 - val_loss: 0.5527 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5484 - accuracy: 0.7227 - val_loss: 0.5415 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7319 - val_loss: 0.5395 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5207 - accuracy: 0.7393 - val_loss: 0.5361 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7468 - val_loss: 0.5387 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.7529 - val_loss: 0.5369 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.7624 - val_loss: 0.5447 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4787 - accuracy: 0.7700 - val_loss: 0.5469 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7751 - val_loss: 0.5453 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4556 - accuracy: 0.7856 - val_loss: 0.5527 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4450 - accuracy: 0.7928 - val_loss: 0.5587 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4320 - accuracy: 0.8019
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4326 - accuracy: 0.8013 - val_loss: 0.5655 - val_accuracy: 0.7187 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4446144089098385
Confusion Matrix :
 [[3001 1046]
 [1203 2844]]
Accuracy on test set:    0.7221398566839634
Sensitivity:    0.7027427724240178 	 Specificity:    0.7415369409439091
Precision  : 0.7311053984575836
Area Under Curve:    0.7221398566839635
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5902 - accuracy: 0.6816 - val_loss: 0.5608 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7196 - val_loss: 0.5456 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5328 - accuracy: 0.7314 - val_loss: 0.5426 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5221 - accuracy: 0.7383 - val_loss: 0.5444 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7469 - val_loss: 0.5472 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4986 - accuracy: 0.7550 - val_loss: 0.5499 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4886 - accuracy: 0.7631 - val_loss: 0.5437 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4759 - accuracy: 0.7723 - val_loss: 0.5510 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 9/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4640 - accuracy: 0.7801
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4640 - accuracy: 0.7801 - val_loss: 0.5599 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 966us/step
Independent Testing Matthews Correlation:  0.5011478926007278
Confusion Matrix :
 [[2969 1078]
 [ 942 3105]]
Accuracy on test set:    0.7504324190758587
Sensitivity:    0.7672349888806523 	 Specificity:    0.733629849271065
Precision  : 0.7422902223284724
Area Under Curve:    0.7504324190758587
(8094, 2560) (8094,)
Mean MCC = 0.4313 + 0.0265 and Mean AUC = 0.7153 + 0.0134
Mean Sensitivity = 0.7252 + 0.0254 and Mean Specificity = 0.7054 + 0.0337 and Mean Accuracy = 0.7153 + 0.0134
Mean Precision = 0.7119 + 0.0192





Seed   : 253858
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5828 - accuracy: 0.6904 - val_loss: 0.5535 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5412 - accuracy: 0.7249 - val_loss: 0.5507 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5255 - accuracy: 0.7372 - val_loss: 0.5611 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5108 - accuracy: 0.7464 - val_loss: 0.5458 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.7553 - val_loss: 0.5459 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.7632 - val_loss: 0.5435 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.7737 - val_loss: 0.5552 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4623 - accuracy: 0.7801 - val_loss: 0.5471 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4490 - accuracy: 0.7905 - val_loss: 0.5617 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4362 - accuracy: 0.7958 - val_loss: 0.5643 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4227 - accuracy: 0.8039 - val_loss: 0.5703 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4110 - accuracy: 0.8118 - val_loss: 0.5847 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 13/400
246/257 [===========================>..] - ETA: 0s - loss: 0.3972 - accuracy: 0.8203
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3979 - accuracy: 0.8196 - val_loss: 0.5946 - val_accuracy: 0.7127 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.38404187690142944
Confusion Matrix :
 [[2594 1454]
 [1047 3000]]
Accuracy on test set:    0.6910438542310068
Sensitivity:    0.7412898443291327 	 Specificity:    0.6408102766798419
Precision  : 0.673551863493489
Area Under Curve:    0.6910500605044874
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5848 - accuracy: 0.6864 - val_loss: 0.5542 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5410 - accuracy: 0.7254 - val_loss: 0.5454 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5253 - accuracy: 0.7355 - val_loss: 0.5416 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5148 - accuracy: 0.7425 - val_loss: 0.5426 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7492 - val_loss: 0.5451 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.7579 - val_loss: 0.5451 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7668 - val_loss: 0.5486 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4700 - accuracy: 0.7744 - val_loss: 0.5469 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4585 - accuracy: 0.7830 - val_loss: 0.5535 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4450 - accuracy: 0.7917 - val_loss: 0.5655 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4346 - accuracy: 0.7970 - val_loss: 0.5582 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4228 - accuracy: 0.8051 - val_loss: 0.5668 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 13/400
252/257 [============================>.] - ETA: 0s - loss: 0.4115 - accuracy: 0.8101
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4114 - accuracy: 0.8103 - val_loss: 0.5704 - val_accuracy: 0.7149 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42397200141146985
Confusion Matrix :
 [[2703 1345]
 [ 993 3054]]
Accuracy on test set:    0.7111797405806053
Sensitivity:    0.7546330615270571 	 Specificity:    0.6677371541501976
Precision  : 0.6942486928847466
Area Under Curve:    0.7111851078386273
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 8ms/step - loss: 0.5873 - accuracy: 0.6850 - val_loss: 0.5454 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7229 - val_loss: 0.5360 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7324 - val_loss: 0.5322 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7416 - val_loss: 0.5326 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7484 - val_loss: 0.5346 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7566 - val_loss: 0.5352 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4858 - accuracy: 0.7635 - val_loss: 0.5354 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4737 - accuracy: 0.7721
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4730 - accuracy: 0.7724 - val_loss: 0.5418 - val_accuracy: 0.7219 - lr: 0.0010
253/253 [==============================] - 0s 938us/step
Independent Testing Matthews Correlation:  0.41840751435284124
Confusion Matrix :
 [[2865 1182]
 [1172 2876]]
Accuracy on test set:    0.7092032118591723
Sensitivity:    0.7104743083003953 	 Specificity:    0.7079318013343218
Precision  : 0.708723509117792
Area Under Curve:    0.7092030548173585
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5849 - accuracy: 0.6870 - val_loss: 0.5462 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7211 - val_loss: 0.5380 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7354 - val_loss: 0.5404 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7437 - val_loss: 0.5374 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5028 - accuracy: 0.7528 - val_loss: 0.5358 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.7601 - val_loss: 0.5389 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4778 - accuracy: 0.7701
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4777 - accuracy: 0.7702 - val_loss: 0.5433 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4157694545989063
Confusion Matrix :
 [[2944 1103]
 [1263 2785]]
Accuracy on test set:    0.7077208153180976
Sensitivity:    0.6879940711462451 	 Specificity:    0.7274524339016556
Precision  : 0.7163065843621399
Area Under Curve:    0.7077232525239502
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5875 - accuracy: 0.6846 - val_loss: 0.5487 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7248 - val_loss: 0.5420 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7354 - val_loss: 0.5373 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7423 - val_loss: 0.5363 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7508 - val_loss: 0.5434 - val_accuracy: 0.7219 - lr: 0.0010

Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.7606 - val_loss: 0.5372 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.7658 - val_loss: 0.5400 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4668 - accuracy: 0.7773
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4669 - accuracy: 0.7775 - val_loss: 0.5472 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4239255198408308
Confusion Matrix :
 [[2748 1299]
 [1036 3011]]
Accuracy on test set:    0.7115147022485792
Sensitivity:    0.7440079070916729 	 Specificity:    0.6790214974054856
Precision  : 0.6986078886310905
Area Under Curve:    0.7115147022485792
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5837 - accuracy: 0.6880 - val_loss: 0.5491 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7227 - val_loss: 0.5416 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5269 - accuracy: 0.7348 - val_loss: 0.5456 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5124 - accuracy: 0.7435 - val_loss: 0.5393 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7543 - val_loss: 0.5396 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.7603 - val_loss: 0.5429 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - ETA: 0s - loss: 0.4746 - accuracy: 0.7718
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7718 - val_loss: 0.5460 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 818us/step
Independent Testing Matthews Correlation:  0.4155090161537062
Confusion Matrix :
 [[3011 1036]
 [1334 2713]]
Accuracy on test set:    0.7071905114899926
Sensitivity:    0.6703731158883123 	 Specificity:    0.7440079070916729
Precision  : 0.7236596425713524
Area Under Curve:    0.7071905114899927
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5901 - accuracy: 0.6807 - val_loss: 0.5490 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.7211 - val_loss: 0.5436 - val_accuracy: 0.7318 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7316 - val_loss: 0.5455 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5207 - accuracy: 0.7391 - val_loss: 0.5415 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7475 - val_loss: 0.5465 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7554 - val_loss: 0.5427 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
252/257 [============================>.] - ETA: 0s - loss: 0.4846 - accuracy: 0.7645
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7645 - val_loss: 0.5538 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 845us/step
Independent Testing Matthews Correlation:  0.4462364291215763
Confusion Matrix :
 [[2810 1237]
 [1007 3040]]
Accuracy on test set:    0.7227575982209044
Sensitivity:    0.7511737089201878 	 Specificity:    0.694341487521621
Precision  : 0.7107785831190087
Area Under Curve:    0.7227575982209045
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5913 - accuracy: 0.6807 - val_loss: 0.5495 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7202 - val_loss: 0.5399 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7320 - val_loss: 0.5395 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.7428 - val_loss: 0.5362 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7489 - val_loss: 0.5398 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7568 - val_loss: 0.5470 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4837 - accuracy: 0.7628
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7630 - val_loss: 0.5397 - val_accuracy: 0.7222 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44217011186850974
Confusion Matrix :
 [[2872 1175]
 [1083 2964]]
Accuracy on test set:    0.7210279219174698
Sensitivity:    0.7323943661971831 	 Specificity:    0.7096614776377563
Precision  : 0.7161150036240638
Area Under Curve:    0.7210279219174697
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5938 - accuracy: 0.6773 - val_loss: 0.5571 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5494 - accuracy: 0.7178 - val_loss: 0.5485 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5350 - accuracy: 0.7295 - val_loss: 0.5429 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5243 - accuracy: 0.7371 - val_loss: 0.5511 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.7455 - val_loss: 0.5421 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7513 - val_loss: 0.5422 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.7599 - val_loss: 0.5425 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4794 - accuracy: 0.7714 - val_loss: 0.5467 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.7769 - val_loss: 0.5514 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4557 - accuracy: 0.7829 - val_loss: 0.5551 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4442 - accuracy: 0.7917 - val_loss: 0.5571 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4298 - accuracy: 0.7992 - val_loss: 0.5663 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4175 - accuracy: 0.8070 - val_loss: 0.5712 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4040 - accuracy: 0.8177 - val_loss: 0.5894 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3928 - accuracy: 0.8212 - val_loss: 0.5911 - val_accuracy: 0.7170 - lr: 0.0010

Epoch 16/400
255/257 [============================>.] - ETA: 0s - loss: 0.3789 - accuracy: 0.8296
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3788 - accuracy: 0.8297 - val_loss: 0.6056 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4433937934071905
Confusion Matrix :
 [[2964 1083]
 [1170 2877]]
Accuracy on test set:    0.7216456634544107
Sensitivity:    0.7108969607116382 	 Specificity:    0.7323943661971831
Precision  : 0.7265151515151516
Area Under Curve:    0.7216456634544106
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5944 - accuracy: 0.6780 - val_loss: 0.5554 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5499 - accuracy: 0.7190 - val_loss: 0.5513 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5345 - accuracy: 0.7304 - val_loss: 0.5515 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5228 - accuracy: 0.7393 - val_loss: 0.5494 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5119 - accuracy: 0.7460 - val_loss: 0.5582 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7572 - val_loss: 0.5516 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4854 - accuracy: 0.7665 - val_loss: 0.5531 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4731 - accuracy: 0.7741 - val_loss: 0.5611 - val_accuracy: 0.7141 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4596 - accuracy: 0.7827 - val_loss: 0.5568 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4451 - accuracy: 0.7936 - val_loss: 0.5607 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4312 - accuracy: 0.8032 - val_loss: 0.5712 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 12/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4145 - accuracy: 0.8133
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4151 - accuracy: 0.8129 - val_loss: 0.5773 - val_accuracy: 0.7159 - lr: 0.0010
253/253 [==============================] - 0s 978us/step
Independent Testing Matthews Correlation:  0.4681091665068109
Confusion Matrix :
 [[3014 1033]
 [1120 2927]]
Accuracy on test set:    0.7340004941932295
Sensitivity:    0.7232517914504571 	 Specificity:    0.744749196936002
Precision  : 0.7391414141414141
Area Under Curve:    0.7340004941932295
(8094, 2560) (8094,)
Mean MCC = 0.4282 + 0.0218 and Mean AUC = 0.7137 + 0.0111
Mean Sensitivity = 0.7226 + 0.0264 and Mean Specificity = 0.7048 + 0.0327 and Mean Accuracy = 0.7137 + 0.0111
Mean Precision = 0.7108 + 0.0176





Seed   : 218846
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5845 - accuracy: 0.6855 - val_loss: 0.5540 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5416 - accuracy: 0.7256 - val_loss: 0.5483 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5260 - accuracy: 0.7357 - val_loss: 0.5478 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5157 - accuracy: 0.7432 - val_loss: 0.5508 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5043 - accuracy: 0.7516 - val_loss: 0.5473 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.7579 - val_loss: 0.5552 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.7670 - val_loss: 0.5546 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7764 - val_loss: 0.5555 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4569 - accuracy: 0.7848 - val_loss: 0.5647 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4435 - accuracy: 0.7933 - val_loss: 0.5667 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4310 - accuracy: 0.8008 - val_loss: 0.5739 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4184 - accuracy: 0.8086 - val_loss: 0.5781 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 13/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4039 - accuracy: 0.8182
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4036 - accuracy: 0.8182 - val_loss: 0.5875 - val_accuracy: 0.7130 - lr: 0.0010
253/253 [==============================] - 0s 818us/step
Independent Testing Matthews Correlation:  0.3916966548953306
Confusion Matrix :
 [[2749 1299]
 [1164 2883]]
Accuracy on test set:    0.6957381099444101
Sensitivity:    0.7123795404002965 	 Specificity:    0.679100790513834
Precision  : 0.6893830703012912
Area Under Curve:    0.6957401654570653
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5891 - accuracy: 0.6830 - val_loss: 0.5612 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7254 - val_loss: 0.5503 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7353 - val_loss: 0.5519 - val_accuracy: 0.7050 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7414 - val_loss: 0.5543 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5094 - accuracy: 0.7493 - val_loss: 0.5485 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7563 - val_loss: 0.5532 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4865 - accuracy: 0.7653
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7653 - val_loss: 0.5542 - val_accuracy: 0.7098 - lr: 0.0010
253/253 [==============================] - 0s 837us/step
Independent Testing Matthews Correlation:  0.4128023567738016
Confusion Matrix :
 [[2779 1269]
 [1109 2938]]
Accuracy on test set:    0.7062384187770229
Sensitivity:    0.7259698542129973 	 Specificity:    0.6865118577075099
Precision  : 0.698359876396482
Area Under Curve:    0.7062408559602537
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5915 - accuracy: 0.6788 - val_loss: 0.5478 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5484 - accuracy: 0.7197 - val_loss: 0.5452 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5316 - accuracy: 0.7315 - val_loss: 0.5461 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5206 - accuracy: 0.7414 - val_loss: 0.5411 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5094 - accuracy: 0.7471 - val_loss: 0.5454 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.7564 - val_loss: 0.5416 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 7/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4852 - accuracy: 0.7642
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.7645 - val_loss: 0.5459 - val_accuracy: 0.7126 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43437476000902786
Confusion Matrix :
 [[2814 1233]
 [1058 2990]]
Accuracy on test set:    0.7169857936998147
Sensitivity:    0.7386363636363636 	 Specificity:    0.6953298739807264
Precision  : 0.7080274686242009
Area Under Curve:    0.7169831188085452
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5937 - accuracy: 0.6795 - val_loss: 0.5478 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7218 - val_loss: 0.5394 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7319 - val_loss: 0.5373 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7394 - val_loss: 0.5397 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7475 - val_loss: 0.5419 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7554 - val_loss: 0.5460 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4882 - accuracy: 0.7630
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.7629 - val_loss: 0.5455 - val_accuracy: 0.7124 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4238420055468154
Confusion Matrix :
 [[2879 1168]
 [1164 2884]]
Accuracy on test set:    0.7119209388511427
Sensitivity:    0.7124505928853755 	 Specificity:    0.711391153941191
Precision  : 0.7117472852912142
Area Under Curve:    0.7119208734132831
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5873 - accuracy: 0.6859 - val_loss: 0.5589 - val_accuracy: 0.7054 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7230 - val_loss: 0.5466 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7353 - val_loss: 0.5431 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7407 - val_loss: 0.5430 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7500 - val_loss: 0.5445 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7562 - val_loss: 0.5495 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7637 - val_loss: 0.5459 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4728 - accuracy: 0.7727
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4728 - accuracy: 0.7727 - val_loss: 0.5521 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42460521192238443
Confusion Matrix :
 [[2963 1084]
 [1246 2801]]
Accuracy on test set:    0.7121324437855201
Sensitivity:    0.6921176179886336 	 Specificity:    0.7321472695824067
Precision  : 0.720978120978121
Area Under Curve:    0.7121324437855201
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5930 - accuracy: 0.6795 - val_loss: 0.5589 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7211 - val_loss: 0.5484 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5328 - accuracy: 0.7303 - val_loss: 0.5464 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5218 - accuracy: 0.7391 - val_loss: 0.5483 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7485 - val_loss: 0.5468 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4989 - accuracy: 0.7558 - val_loss: 0.5457 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4893 - accuracy: 0.7630 - val_loss: 0.5466 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.7715 - val_loss: 0.5491 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4622 - accuracy: 0.7802 - val_loss: 0.5553 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4479 - accuracy: 0.7881 - val_loss: 0.5555 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4358 - accuracy: 0.7962
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4360 - accuracy: 0.7962 - val_loss: 0.5685 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4263129346070366
Confusion Matrix :
 [[2849 1198]
 [1124 2923]]
Accuracy on test set:    0.7131208302446257
Sensitivity:    0.7222634049913517 	 Specificity:    0.7039782554978997
Precision  : 0.709293860713419
Area Under Curve:    0.7131208302446257
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5869 - accuracy: 0.6856 - val_loss: 0.5534 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7221 - val_loss: 0.5471 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7328 - val_loss: 0.5444 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7423 - val_loss: 0.5461 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7492 - val_loss: 0.5433 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7571 - val_loss: 0.5460 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.7672 - val_loss: 0.5473 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4713 - accuracy: 0.7767
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7768 - val_loss: 0.5538 - val_accuracy: 0.7145 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4294684837800206
Confusion Matrix :
 [[3011 1036]
 [1276 2771]]
Accuracy on test set:    0.7143563133185076
Sensitivity:    0.6847047195453422 	 Specificity:    0.7440079070916729
Precision  : 0.7278697136853165
Area Under Curve:    0.7143563133185076
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5891 - accuracy: 0.6832 - val_loss: 0.5601 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7224 - val_loss: 0.5493 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7323 - val_loss: 0.5460 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7432 - val_loss: 0.5432 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7492 - val_loss: 0.5432 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.7584 - val_loss: 0.5449 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7657 - val_loss: 0.5489 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.7735 - val_loss: 0.5485 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4587 - accuracy: 0.7834 - val_loss: 0.5519 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4448 - accuracy: 0.7916 - val_loss: 0.5579 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4318 - accuracy: 0.7990 - val_loss: 0.5667 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4196 - accuracy: 0.8092 - val_loss: 0.5660 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4081 - accuracy: 0.8132 - val_loss: 0.5753 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 14/400
250/257 [============================>.] - ETA: 0s - loss: 0.3957 - accuracy: 0.8221
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3962 - accuracy: 0.8220 - val_loss: 0.5897 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4354869433496982
Confusion Matrix :
 [[2729 1318]
 [ 973 3074]]
Accuracy on test set:    0.7169508277736595
Sensitivity:    0.7595749938225846 	 Specificity:    0.6743266617247343
Precision  : 0.6999089253187614
Area Under Curve:    0.7169508277736594
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5906 - accuracy: 0.6825 - val_loss: 0.5605 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7209 - val_loss: 0.5519 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5336 - accuracy: 0.7303 - val_loss: 0.5509 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5224 - accuracy: 0.7383 - val_loss: 0.5484 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5121 - accuracy: 0.7452 - val_loss: 0.5527 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7550 - val_loss: 0.5519 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4893 - accuracy: 0.7617 - val_loss: 0.5547 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4785 - accuracy: 0.7680
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7684 - val_loss: 0.5622 - val_accuracy: 0.7089 - lr: 0.0010
253/253 [==============================] - 0s 791us/step
Independent Testing Matthews Correlation:  0.4639465062600584
Confusion Matrix :
 [[3181  866]
 [1315 2732]]
Accuracy on test set:    0.7305411415863603
Sensitivity:    0.6750679515690635 	 Specificity:    0.7860143316036571
Precision  : 0.7593107281823235
Area Under Curve:    0.7305411415863602
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5927 - accuracy: 0.6823 - val_loss: 0.5621 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5495 - accuracy: 0.7199 - val_loss: 0.5538 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5341 - accuracy: 0.7308 - val_loss: 0.5540 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5234 - accuracy: 0.7393 - val_loss: 0.5487 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5107 - accuracy: 0.7480 - val_loss: 0.5513 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4995 - accuracy: 0.7545 - val_loss: 0.5536 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.7630 - val_loss: 0.5585 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4744 - accuracy: 0.7721 - val_loss: 0.5597 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 9/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4622 - accuracy: 0.7794
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4625 - accuracy: 0.7794 - val_loss: 0.5624 - val_accuracy: 0.7051 - lr: 0.0010
253/253 [==============================] - 0s 945us/step
Independent Testing Matthews Correlation:  0.47854561183193894
Confusion Matrix :
 [[3130  917]
 [1198 2849]]
Accuracy on test set:    0.7386953298739807
Sensitivity:    0.7039782554978997 	 Specificity:    0.7734124042500617
Precision  : 0.7565055762081785
Area Under Curve:    0.7386953298739807
(8094, 2560) (8094,)
Mean MCC = 0.4321 + 0.0231 and Mean AUC = 0.7157 + 0.0113
Mean Sensitivity = 0.7127 + 0.0242 and Mean Specificity = 0.7186 + 0.0371 and Mean Accuracy = 0.7157 + 0.0113
Mean Precision = 0.7181 + 0.0225





Seed   : 735329
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5851 - accuracy: 0.6870 - val_loss: 0.5591 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7241 - val_loss: 0.5497 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5258 - accuracy: 0.7368 - val_loss: 0.5528 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.7441 - val_loss: 0.5473 - val_accuracy: 0.7135 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5021 - accuracy: 0.7532 - val_loss: 0.5483 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7619 - val_loss: 0.5498 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4795 - accuracy: 0.7687
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7687 - val_loss: 0.5612 - val_accuracy: 0.7105 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.407002660801485
Confusion Matrix :
 [[2380 1668]
 [ 773 3274]]
Accuracy on test set:    0.6984558369363805
Sensitivity:    0.8089943167778602 	 Specificity:    0.5879446640316206
Precision  : 0.6624848239579118
Area Under Curve:    0.6984694904047404
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 3s 4ms/step - loss: 0.5857 - accuracy: 0.6856 - val_loss: 0.5537 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7225 - val_loss: 0.5500 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7325 - val_loss: 0.5442 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7418 - val_loss: 0.5407 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7498 - val_loss: 0.5470 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.7572 - val_loss: 0.5451 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4872 - accuracy: 0.7622 - val_loss: 0.5514 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.7717 - val_loss: 0.5620 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4636 - accuracy: 0.7800 - val_loss: 0.5559 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4519 - accuracy: 0.7865 - val_loss: 0.5573 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 11/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4391 - accuracy: 0.7970
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4393 - accuracy: 0.7967 - val_loss: 0.5673 - val_accuracy: 0.7152 - lr: 0.0010
253/253 [==============================] - 0s 783us/step
Independent Testing Matthews Correlation:  0.41934526230480546
Confusion Matrix :
 [[2736 1312]
 [1042 3005]]
Accuracy on test set:    0.7092032118591723
Sensitivity:    0.7425253274030146 	 Specificity:    0.6758893280632411
Precision  : 0.6960852443826732
Area Under Curve:    0.7092073277331279
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5857 - accuracy: 0.6875 - val_loss: 0.5462 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7226 - val_loss: 0.5382 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7322 - val_loss: 0.5358 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7394 - val_loss: 0.5327 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7463 - val_loss: 0.5312 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7563 - val_loss: 0.5317 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7659 - val_loss: 0.5373 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.7739 - val_loss: 0.5389 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4617 - accuracy: 0.7822
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4620 - accuracy: 0.7818 - val_loss: 0.5438 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 748us/step
Independent Testing Matthews Correlation:  0.43274596461232134
Confusion Matrix :
 [[2701 1346]
 [ 958 3090]]
Accuracy on test set:    0.7153798641136504
Sensitivity:    0.7633399209486166 	 Specificity:    0.6674079565109958
Precision  : 0.6965734896302975
Area Under Curve:    0.7153739387298063
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5870 - accuracy: 0.6846 - val_loss: 0.5522 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7225 - val_loss: 0.5374 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7330 - val_loss: 0.5343 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7397 - val_loss: 0.5351 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7491 - val_loss: 0.5345 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.7557 - val_loss: 0.5372 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4883 - accuracy: 0.7617 - val_loss: 0.5379 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4764 - accuracy: 0.7728 - val_loss: 0.5393 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4638 - accuracy: 0.7792 - val_loss: 0.5457 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4519 - accuracy: 0.7882
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4518 - accuracy: 0.7881 - val_loss: 0.5462 - val_accuracy: 0.7200 - lr: 0.0010
253/253 [==============================] - 0s 829us/step
Independent Testing Matthews Correlation:  0.4265237144940925
Confusion Matrix :
 [[2749 1298]
 [1027 3021]]
Accuracy on test set:    0.7127856701667696
Sensitivity:    0.7462944664031621 	 Specificity:    0.679268594020262
Precision  : 0.6994674693216022
Area Under Curve:    0.712781530211712
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5855 - accuracy: 0.6861 - val_loss: 0.5483 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7235 - val_loss: 0.5453 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7325 - val_loss: 0.5420 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7438 - val_loss: 0.5421 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5040 - accuracy: 0.7521 - val_loss: 0.5419 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4918 - accuracy: 0.7603 - val_loss: 0.5428 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4802 - accuracy: 0.7689 - val_loss: 0.5541 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4671 - accuracy: 0.7769 - val_loss: 0.5521 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4533 - accuracy: 0.7872 - val_loss: 0.5562 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 10/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4404 - accuracy: 0.7955
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4406 - accuracy: 0.7958 - val_loss: 0.5642 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4152729627876084
Confusion Matrix :
 [[2809 1238]
 [1129 2918]]
Accuracy on test set:    0.7075611564121571
Sensitivity:    0.7210279219174698 	 Specificity:    0.6940943909068445
Precision  : 0.7021174205967277
Area Under Curve:    0.7075611564121571
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5871 - accuracy: 0.6855 - val_loss: 0.5500 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7223 - val_loss: 0.5406 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7334 - val_loss: 0.5410 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7409 - val_loss: 0.5408 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.7489 - val_loss: 0.5446 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4999 - accuracy: 0.7560 - val_loss: 0.5448 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4883 - accuracy: 0.7645
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.7641 - val_loss: 0.5485 - val_accuracy: 0.7153 - lr: 0.0010
253/253 [==============================] - 0s 970us/step
Independent Testing Matthews Correlation:  0.43703419935696275
Confusion Matrix :
 [[2597 1450]
 [ 848 3199]]
Accuracy on test set:    0.7160859896219421
Sensitivity:    0.7904620706696318 	 Specificity:    0.6417099085742526
Precision  : 0.6881049688104969
Area Under Curve:    0.7160859896219423
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5888 - accuracy: 0.6840 - val_loss: 0.5481 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7221 - val_loss: 0.5412 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7333 - val_loss: 0.5406 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5189 - accuracy: 0.7411 - val_loss: 0.5441 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7501 - val_loss: 0.5402 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7599 - val_loss: 0.5471 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7660 - val_loss: 0.5448 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.7748 - val_loss: 0.5462 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4575 - accuracy: 0.7848 - val_loss: 0.5547 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4458 - accuracy: 0.7919 - val_loss: 0.5570 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4303 - accuracy: 0.8006 - val_loss: 0.5677 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 12/400
255/257 [============================>.] - ETA: 0s - loss: 0.4180 - accuracy: 0.8084
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4181 - accuracy: 0.8082 - val_loss: 0.5659 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 915us/step
Independent Testing Matthews Correlation:  0.4177684434209482
Confusion Matrix :
 [[2753 1294]
 [1065 2982]]
Accuracy on test set:    0.7085495428712627
Sensitivity:    0.7368421052631579 	 Specificity:    0.6802569804793674
Precision  : 0.6973807296538821
Area Under Curve:    0.7085495428712627
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5848 - accuracy: 0.6880 - val_loss: 0.5498 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7233 - val_loss: 0.5407 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5290 - accuracy: 0.7353 - val_loss: 0.5371 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7423 - val_loss: 0.5395 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7491 - val_loss: 0.5414 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7577 - val_loss: 0.5403 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4834 - accuracy: 0.7660 - val_loss: 0.5455 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4703 - accuracy: 0.7749 - val_loss: 0.5518 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4603 - accuracy: 0.7825 - val_loss: 0.5548 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4479 - accuracy: 0.7889 - val_loss: 0.5540 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4342 - accuracy: 0.7981 - val_loss: 0.5591 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 12/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4206 - accuracy: 0.8050
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4212 - accuracy: 0.8042 - val_loss: 0.5649 - val_accuracy: 0.7157 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4306748100277569
Confusion Matrix :
 [[3011 1036]
 [1271 2776]]
Accuracy on test set:    0.7149740548554485
Sensitivity:    0.6859402026192242 	 Specificity:    0.7440079070916729
Precision  : 0.7282266526757608
Area Under Curve:    0.7149740548554485
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5922 - accuracy: 0.6813 - val_loss: 0.5516 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5500 - accuracy: 0.7199 - val_loss: 0.5434 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5344 - accuracy: 0.7299 - val_loss: 0.5422 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5225 - accuracy: 0.7385 - val_loss: 0.5395 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5125 - accuracy: 0.7466 - val_loss: 0.5430 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7517 - val_loss: 0.5414 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.7594 - val_loss: 0.5471 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4815 - accuracy: 0.7684
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.7685 - val_loss: 0.5467 - val_accuracy: 0.7202 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4528430722992567
Confusion Matrix :
 [[3025 1022]
 [1194 2853]]
Accuracy on test set:    0.7262169508277737
Sensitivity:    0.7049666419570052 	 Specificity:    0.7474672596985421
Precision  : 0.7362580645161291
Area Under Curve:    0.7262169508277736
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5926 - accuracy: 0.6825 - val_loss: 0.5498 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5499 - accuracy: 0.7187 - val_loss: 0.5435 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5350 - accuracy: 0.7303 - val_loss: 0.5410 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5233 - accuracy: 0.7381 - val_loss: 0.5421 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5128 - accuracy: 0.7474 - val_loss: 0.5405 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.7539 - val_loss: 0.5436 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7634 - val_loss: 0.5461 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4792 - accuracy: 0.7694 - val_loss: 0.5470 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4647 - accuracy: 0.7805 - val_loss: 0.5522 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 10/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4537 - accuracy: 0.7872
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4535 - accuracy: 0.7875 - val_loss: 0.5567 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 924us/step
Independent Testing Matthews Correlation:  0.479187984524277
Confusion Matrix :
 [[3027 1020]
 [1088 2959]]
Accuracy on test set:    0.739560168025698
Sensitivity:    0.7311588831233012 	 Specificity:    0.7479614529280949
Precision  : 0.7436541844684594
Area Under Curve:    0.7395601680256981
(8094, 2560) (8094,)
Mean MCC = 0.4318 + 0.0200 and Mean AUC = 0.7149 + 0.0107
Mean Sensitivity = 0.7432 + 0.0352 and Mean Specificity = 0.6866 + 0.0481 and Mean Accuracy = 0.7149 + 0.0107
Mean Precision = 0.7050 + 0.0231





Seed   : 611076
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5820 - accuracy: 0.6895 - val_loss: 0.5605 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5407 - accuracy: 0.7252 - val_loss: 0.5575 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5258 - accuracy: 0.7362 - val_loss: 0.5521 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5139 - accuracy: 0.7429 - val_loss: 0.5579 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5029 - accuracy: 0.7521 - val_loss: 0.5536 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7597 - val_loss: 0.5612 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.7668 - val_loss: 0.5565 - val_accuracy: 0.7020 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 3ms/step - loss: 0.4724 - accuracy: 0.7753 - val_loss: 0.5640 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4563 - accuracy: 0.7859
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4565 - accuracy: 0.7858 - val_loss: 0.5731 - val_accuracy: 0.7054 - lr: 0.0010
253/253 [==============================] - 0s 881us/step
Independent Testing Matthews Correlation:  0.4231283716501689
Confusion Matrix :
 [[2904 1144]
 [1191 2856]]
Accuracy on test set:    0.711550339715874
Sensitivity:    0.7057079318013343 	 Specificity:    0.717391304347826
Precision  : 0.714
Area Under Curve:    0.7115496180745802
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5869 - accuracy: 0.6836 - val_loss: 0.5748 - val_accuracy: 0.6998 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7225 - val_loss: 0.5485 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7349 - val_loss: 0.5513 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5157 - accuracy: 0.7425 - val_loss: 0.5524 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7499 - val_loss: 0.5504 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7609 - val_loss: 0.5515 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7670 - val_loss: 0.5570 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.7774 - val_loss: 0.5582 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4544 - accuracy: 0.7882 - val_loss: 0.5750 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 10/400
251/257 [============================>.] - ETA: 0s - loss: 0.4424 - accuracy: 0.7942
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7942 - val_loss: 0.5663 - val_accuracy: 0.7145 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41785412787224135
Confusion Matrix :
 [[2809 1239]
 [1118 2929]]
Accuracy on test set:    0.7088326127239036
Sensitivity:    0.7237459846800098 	 Specificity:    0.6939229249011858
Precision  : 0.7027351247600768
Area Under Curve:    0.7088344547905978
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5842 - accuracy: 0.6859 - val_loss: 0.5481 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7249 - val_loss: 0.5404 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.7353 - val_loss: 0.5403 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5143 - accuracy: 0.7424 - val_loss: 0.5381 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5043 - accuracy: 0.7516 - val_loss: 0.5380 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
255/257 [============================>.] - ETA: 0s - loss: 0.4937 - accuracy: 0.7580
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.7579 - val_loss: 0.5438 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 939us/step
Independent Testing Matthews Correlation:  0.43163928387839795
Confusion Matrix :
 [[2669 1378]
 [ 933 3115]]
Accuracy on test set:    0.7145151327980235
Sensitivity:    0.7695158102766798 	 Specificity:    0.6595008648381517
Precision  : 0.6933006899621633
Area Under Curve:    0.7145083375574158
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5900 - accuracy: 0.6829 - val_loss: 0.5504 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7220 - val_loss: 0.5370 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7323 - val_loss: 0.5353 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5204 - accuracy: 0.7412 - val_loss: 0.5342 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7471 - val_loss: 0.5345 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.7584 - val_loss: 0.5338 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.7640 - val_loss: 0.5401 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.7743 - val_loss: 0.5407 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4590 - accuracy: 0.7821
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4591 - accuracy: 0.7820 - val_loss: 0.5464 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4195862858347697
Confusion Matrix :
 [[2755 1292]
 [1060 2988]]
Accuracy on test set:    0.7094502779493514
Sensitivity:    0.7381422924901185 	 Specificity:    0.6807511737089202
Precision  : 0.6981308411214954
Area Under Curve:    0.7094467330995194
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5862 - accuracy: 0.6861 - val_loss: 0.5475 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7231 - val_loss: 0.5392 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7334 - val_loss: 0.5381 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7417 - val_loss: 0.5384 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7498 - val_loss: 0.5371 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.7575 - val_loss: 0.5398 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4841 - accuracy: 0.7666 - val_loss: 0.5529 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7748 - val_loss: 0.5463 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4607 - accuracy: 0.7816 - val_loss: 0.5493 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 10/400
245/257 [===========================>..] - ETA: 0s - loss: 0.4463 - accuracy: 0.7914
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4476 - accuracy: 0.7908 - val_loss: 0.5592 - val_accuracy: 0.7238 - lr: 0.0010
253/253 [==============================] - 0s 832us/step
Independent Testing Matthews Correlation:  0.40172391453591
Confusion Matrix :
 [[2679 1368]
 [1058 2989]]
Accuracy on test set:    0.700271806276254
Sensitivity:    0.7385717815665925 	 Specificity:    0.6619718309859155
Precision  : 0.686022492540739
Area Under Curve:    0.7002718062762541
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 4ms/step - loss: 0.5876 - accuracy: 0.6834 - val_loss: 0.5524 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7228 - val_loss: 0.5459 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7305 - val_loss: 0.5442 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7413 - val_loss: 0.5404 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5070 - accuracy: 0.7483 - val_loss: 0.5431 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7570 - val_loss: 0.5444 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.7647 - val_loss: 0.5520 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4696 - accuracy: 0.7747
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4699 - accuracy: 0.7746 - val_loss: 0.5500 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 783us/step
Independent Testing Matthews Correlation:  0.4322522709011123
Confusion Matrix :
 [[2937 1110]
 [1188 2859]]
Accuracy on test set:    0.7160859896219421
Sensitivity:    0.7064492216456635 	 Specificity:    0.7257227575982209
Precision  : 0.7203325774754347
Area Under Curve:    0.7160859896219423
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5889 - accuracy: 0.6867 - val_loss: 0.5483 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7213 - val_loss: 0.5403 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7325 - val_loss: 0.5371 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7434 - val_loss: 0.5369 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7490 - val_loss: 0.5363 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7572 - val_loss: 0.5386 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4857 - accuracy: 0.7642 - val_loss: 0.5437 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7722 - val_loss: 0.5484 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 9/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4614 - accuracy: 0.7806
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4616 - accuracy: 0.7807 - val_loss: 0.5527 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 758us/step
Independent Testing Matthews Correlation:  0.42985404838655056
Confusion Matrix :
 [[2781 1266]
 [1044 3003]]
Accuracy on test set:    0.7146034099332839
Sensitivity:    0.7420311341734618 	 Specificity:    0.687175685693106
Precision  : 0.7034434293745608
Area Under Curve:    0.7146034099332839
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5898 - accuracy: 0.6817 - val_loss: 0.5503 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7227 - val_loss: 0.5438 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5331 - accuracy: 0.7315 - val_loss: 0.5397 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5209 - accuracy: 0.7391 - val_loss: 0.5415 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5102 - accuracy: 0.7475 - val_loss: 0.5441 - val_accuracy: 0.7163 - lr: 0.0010

Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4985 - accuracy: 0.7547 - val_loss: 0.5436 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7627 - val_loss: 0.5501 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4784 - accuracy: 0.7707
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7704 - val_loss: 0.5460 - val_accuracy: 0.7218 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4514499805966914
Confusion Matrix :
 [[2946 1101]
 [1119 2928]]
Accuracy on test set:    0.7257227575982209
Sensitivity:    0.7234988880652335 	 Specificity:    0.7279466271312083
Precision  : 0.7267311988086373
Area Under Curve:    0.7257227575982209
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5909 - accuracy: 0.6826 - val_loss: 0.5528 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5484 - accuracy: 0.7197 - val_loss: 0.5463 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7319 - val_loss: 0.5444 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7407 - val_loss: 0.5478 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7500 - val_loss: 0.5445 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.7577 - val_loss: 0.5458 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4854 - accuracy: 0.7659 - val_loss: 0.5524 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4715 - accuracy: 0.7742
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7742 - val_loss: 0.5530 - val_accuracy: 0.7185 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46262722551285806
Confusion Matrix :
 [[3033 1014]
 [1162 2885]]
Accuracy on test set:    0.7311588831233012
Sensitivity:    0.7128737336298493 	 Specificity:    0.7494440326167532
Precision  : 0.7399333162349321
Area Under Curve:    0.7311588831233012
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5907 - accuracy: 0.6836 - val_loss: 0.5839 - val_accuracy: 0.6884 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5508 - accuracy: 0.7191 - val_loss: 0.5495 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5346 - accuracy: 0.7323 - val_loss: 0.5531 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5223 - accuracy: 0.7378 - val_loss: 0.5512 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5124 - accuracy: 0.7476 - val_loss: 0.5494 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7550 - val_loss: 0.5522 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - ETA: 0s - loss: 0.4889 - accuracy: 0.7629
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4889 - accuracy: 0.7629 - val_loss: 0.5530 - val_accuracy: 0.7126 - lr: 0.0010
253/253 [==============================] - 0s 727us/step
Independent Testing Matthews Correlation:  0.47617911154645737
Confusion Matrix :
 [[3157  890]
 [1237 2810]]
Accuracy on test set:    0.7372127501853225
Sensitivity:    0.694341487521621 	 Specificity:    0.780084012849024
Precision  : 0.7594594594594595
Area Under Curve:    0.7372127501853225
(8094, 2560) (8094,)
Mean MCC = 0.4346 + 0.0213 and Mean AUC = 0.7169 + 0.0106
Mean Sensitivity = 0.7255 + 0.0211 and Mean Specificity = 0.7084 + 0.0368 and Mean Accuracy = 0.7169 + 0.0106
Mean Precision = 0.7144 + 0.0215





Seed   : 180547
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.6851 - val_loss: 0.5630 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7238 - val_loss: 0.5543 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7366 - val_loss: 0.5535 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7431 - val_loss: 0.5478 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7496 - val_loss: 0.5588 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7602 - val_loss: 0.5555 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4817 - accuracy: 0.7679 - val_loss: 0.5572 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4698 - accuracy: 0.7748 - val_loss: 0.5588 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4568 - accuracy: 0.7834 - val_loss: 0.5628 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4459 - accuracy: 0.7914 - val_loss: 0.5730 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4316 - accuracy: 0.7998 - val_loss: 0.5634 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4205 - accuracy: 0.8070 - val_loss: 0.5778 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4081 - accuracy: 0.8136 - val_loss: 0.5893 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 14/400
252/257 [============================>.] - ETA: 0s - loss: 0.3960 - accuracy: 0.8215
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3959 - accuracy: 0.8215 - val_loss: 0.5989 - val_accuracy: 0.7057 - lr: 0.0010
253/253 [==============================] - 0s 744us/step
Independent Testing Matthews Correlation:  0.39430365994391187
Confusion Matrix :
 [[2688 1360]
 [1095 2952]]
Accuracy on test set:    0.6967263743051266
Sensitivity:    0.7294292068198666 	 Specificity:    0.6640316205533597
Precision  : 0.6846011131725418
Area Under Curve:    0.6967304136866131
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5858 - accuracy: 0.6843 - val_loss: 0.5571 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5418 - accuracy: 0.7247 - val_loss: 0.5486 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.7361 - val_loss: 0.5506 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.7454 - val_loss: 0.5522 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5003 - accuracy: 0.7533 - val_loss: 0.5477 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4893 - accuracy: 0.7626 - val_loss: 0.5535 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.7711 - val_loss: 0.5526 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4626 - accuracy: 0.7798 - val_loss: 0.5548 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4505 - accuracy: 0.7892 - val_loss: 0.5723 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4341 - accuracy: 0.7984 - val_loss: 0.5686 - val_accuracy: 0.7035 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4229 - accuracy: 0.8039 - val_loss: 0.5836 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 12/400
252/257 [============================>.] - ETA: 0s - loss: 0.4097 - accuracy: 0.8121
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4102 - accuracy: 0.8118 - val_loss: 0.5886 - val_accuracy: 0.7071 - lr: 0.0010
253/253 [==============================] - 0s 799us/step
Independent Testing Matthews Correlation:  0.4067593805399202
Confusion Matrix :
 [[2690 1358]
 [1048 2999]]
Accuracy on test set:    0.7027794935145152
Sensitivity:    0.7410427477143563 	 Specificity:    0.6645256916996047
Precision  : 0.6883176497590084
Area Under Curve:    0.7027842197069806
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 8ms/step - loss: 0.5894 - accuracy: 0.6819 - val_loss: 0.5534 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7245 - val_loss: 0.5457 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7329 - val_loss: 0.5474 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7412 - val_loss: 0.5418 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7478 - val_loss: 0.5414 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7568 - val_loss: 0.5432 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.7640 - val_loss: 0.5462 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7712 - val_loss: 0.5506 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4603 - accuracy: 0.7807 - val_loss: 0.5516 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4479 - accuracy: 0.7897 - val_loss: 0.5655 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 11/400
256/257 [============================>.] - ETA: 0s - loss: 0.4357 - accuracy: 0.7977
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4357 - accuracy: 0.7977 - val_loss: 0.5632 - val_accuracy: 0.7157 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4167816556979324
Confusion Matrix :
 [[2673 1374]
 [ 994 3054]]
Accuracy on test set:    0.7074737492279185
Sensitivity:    0.7544466403162056 	 Specificity:    0.6604892512972572
Precision  : 0.6897018970189702
Area Under Curve:    0.7074679458067314
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5886 - accuracy: 0.6840 - val_loss: 0.5507 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7236 - val_loss: 0.5491 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7327 - val_loss: 0.5394 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7401 - val_loss: 0.5367 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7488 - val_loss: 0.5397 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4976 - accuracy: 0.7561 - val_loss: 0.5385 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.7631 - val_loss: 0.5375 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4756 - accuracy: 0.7714 - val_loss: 0.5591 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
250/257 [============================>.] - ETA: 0s - loss: 0.4647 - accuracy: 0.7809
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7805 - val_loss: 0.5472 - val_accuracy: 0.7146 - lr: 0.0010
253/253 [==============================] - 0s 688us/step
Independent Testing Matthews Correlation:  0.4310495999436495
Confusion Matrix :
 [[3075  972]
 [1338 2710]]
Accuracy on test set:    0.7146386658431131
Sensitivity:    0.6694664031620553 	 Specificity:    0.759822090437361
Precision  : 0.7360130363932645
Area Under Curve:    0.7146442467997082
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5899 - accuracy: 0.6821 - val_loss: 0.5498 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7202 - val_loss: 0.5445 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7324 - val_loss: 0.5411 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7416 - val_loss: 0.5445 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.7477 - val_loss: 0.5410 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.7574 - val_loss: 0.5426 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.7640 - val_loss: 0.5421 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.7732 - val_loss: 0.5439 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4628 - accuracy: 0.7821 - val_loss: 0.5492 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
250/257 [============================>.] - ETA: 0s - loss: 0.4492 - accuracy: 0.7895
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4492 - accuracy: 0.7897 - val_loss: 0.5490 - val_accuracy: 0.7235 - lr: 0.0010
253/253 [==============================] - 0s 765us/step
Independent Testing Matthews Correlation:  0.42661131514811473
Confusion Matrix :
 [[2935 1112]
 [1209 2838]]
Accuracy on test set:    0.7132443785520138
Sensitivity:    0.7012601927353596 	 Specificity:    0.7252285643686681
Precision  : 0.7184810126582278
Area Under Curve:    0.713244378552014
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5965 - accuracy: 0.6766 - val_loss: 0.5658 - val_accuracy: 0.7073 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5514 - accuracy: 0.7183 - val_loss: 0.5474 - val_accuracy: 0.7229 - lr: 0.0010

Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5362 - accuracy: 0.7299 - val_loss: 0.5450 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5270 - accuracy: 0.7365 - val_loss: 0.5405 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7436 - val_loss: 0.5424 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7537 - val_loss: 0.5531 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7610 - val_loss: 0.5459 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4790 - accuracy: 0.7683
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7680 - val_loss: 0.5583 - val_accuracy: 0.7204 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43142231176302814
Confusion Matrix :
 [[2654 1393]
 [ 920 3127]]
Accuracy on test set:    0.7142327650111193
Sensitivity:    0.7726711144057327 	 Specificity:    0.6557944156165061
Precision  : 0.6918141592920354
Area Under Curve:    0.7142327650111194
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5848 - accuracy: 0.6875 - val_loss: 0.5495 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7239 - val_loss: 0.5446 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7348 - val_loss: 0.5382 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5141 - accuracy: 0.7434 - val_loss: 0.5401 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5021 - accuracy: 0.7515 - val_loss: 0.5425 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7608 - val_loss: 0.5413 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4780 - accuracy: 0.7668 - val_loss: 0.5468 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4646 - accuracy: 0.7791 - val_loss: 0.5512 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4523 - accuracy: 0.7875
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4527 - accuracy: 0.7871 - val_loss: 0.5549 - val_accuracy: 0.7205 - lr: 0.0010
253/253 [==============================] - 0s 733us/step
Independent Testing Matthews Correlation:  0.42225932523411114
Confusion Matrix :
 [[2759 1288]
 [1053 2994]]
Accuracy on test set:    0.7107734124042501
Sensitivity:    0.7398072646404744 	 Specificity:    0.6817395601680257
Precision  : 0.6992059785147128
Area Under Curve:    0.71077341240425
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5866 - accuracy: 0.6833 - val_loss: 0.5537 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7207 - val_loss: 0.5433 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7334 - val_loss: 0.5412 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7420 - val_loss: 0.5406 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.7498 - val_loss: 0.5406 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.7562 - val_loss: 0.5404 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4831 - accuracy: 0.7643 - val_loss: 0.5439 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7742 - val_loss: 0.5500 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.7822 - val_loss: 0.5553 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4473 - accuracy: 0.7908 - val_loss: 0.5573 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 11/400
251/257 [============================>.] - ETA: 0s - loss: 0.4341 - accuracy: 0.7985
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4339 - accuracy: 0.7983 - val_loss: 0.5673 - val_accuracy: 0.7193 - lr: 0.0010
253/253 [==============================] - 0s 850us/step
Independent Testing Matthews Correlation:  0.44608996646081717
Confusion Matrix :
 [[2784 1263]
 [ 983 3064]]
Accuracy on test set:    0.722510501606128
Sensitivity:    0.7571040276748209 	 Specificity:    0.6879169755374351
Precision  : 0.7081118557892304
Area Under Curve:    0.722510501606128
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5870 - accuracy: 0.6842 - val_loss: 0.5565 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7206 - val_loss: 0.5470 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7325 - val_loss: 0.5448 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7385 - val_loss: 0.5494 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.7481 - val_loss: 0.5528 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.7560 - val_loss: 0.5496 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7661 - val_loss: 0.5486 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.7734 - val_loss: 0.5596 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.7819 - val_loss: 0.5548 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4453 - accuracy: 0.7908 - val_loss: 0.5629 - val_accuracy: 0.7171 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4337 - accuracy: 0.7997 - val_loss: 0.5716 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4209 - accuracy: 0.8079 - val_loss: 0.5716 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4071 - accuracy: 0.8154 - val_loss: 0.5715 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 14/400
246/257 [===========================>..] - ETA: 0s - loss: 0.3984 - accuracy: 0.8204
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3989 - accuracy: 0.8199 - val_loss: 0.5842 - val_accuracy: 0.7141 - lr: 0.0010
253/253 [==============================] - 0s 872us/step
Independent Testing Matthews Correlation:  0.44430479372778336
Confusion Matrix :
 [[2944 1103]
 [1146 2901]]
Accuracy on test set:    0.7221398566839634
Sensitivity:    0.7168272794662713 	 Specificity:    0.7274524339016556
Precision  : 0.7245254745254746
Area Under Curve:    0.7221398566839634
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5893 - accuracy: 0.6837 - val_loss: 0.5571 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5492 - accuracy: 0.7195 - val_loss: 0.5504 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5343 - accuracy: 0.7311 - val_loss: 0.5472 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5230 - accuracy: 0.7384 - val_loss: 0.5502 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5119 - accuracy: 0.7459 - val_loss: 0.5480 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.7540 - val_loss: 0.5533 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.7627 - val_loss: 0.5629 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4784 - accuracy: 0.7715
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4785 - accuracy: 0.7713 - val_loss: 0.5536 - val_accuracy: 0.7152 - lr: 0.0010
253/253 [==============================] - 0s 788us/step
Independent Testing Matthews Correlation:  0.4807851982021334
Confusion Matrix :
 [[3081  966]
 [1137 2910]]
Accuracy on test set:    0.740177909562639
Sensitivity:    0.7190511489992587 	 Specificity:    0.7613046701260193
Precision  : 0.7507739938080495
Area Under Curve:    0.7401779095626391
(8094, 2560) (8094,)
Mean MCC = 0.4300 + 0.0226 and Mean AUC = 0.7145 + 0.0114
Mean Sensitivity = 0.7301 + 0.0286 and Mean Specificity = 0.6988 + 0.0391 and Mean Accuracy = 0.7145 + 0.0114
Mean Precision = 0.7092 + 0.0214





Seed   : 545856
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5861 - accuracy: 0.6858 - val_loss: 0.5605 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7227 - val_loss: 0.5584 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7347 - val_loss: 0.5473 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7416 - val_loss: 0.5450 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5054 - accuracy: 0.7504 - val_loss: 0.5517 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4961 - accuracy: 0.7581 - val_loss: 0.5491 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.7653 - val_loss: 0.5548 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.7715 - val_loss: 0.5589 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4620 - accuracy: 0.7797 - val_loss: 0.5654 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4498 - accuracy: 0.7883 - val_loss: 0.5625 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4402 - accuracy: 0.7957 - val_loss: 0.5739 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 12/400
255/257 [============================>.] - ETA: 0s - loss: 0.4264 - accuracy: 0.8037
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4261 - accuracy: 0.8039 - val_loss: 0.5722 - val_accuracy: 0.7135 - lr: 0.0010
253/253 [==============================] - 0s 784us/step
Independent Testing Matthews Correlation:  0.38303043995679487
Confusion Matrix :
 [[2656 1392]
 [1109 2938]]
Accuracy on test set:    0.6910438542310068
Sensitivity:    0.7259698542129973 	 Specificity:    0.6561264822134387
Precision  : 0.6785219399538106
Area Under Curve:    0.691048168213218
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5863 - accuracy: 0.6877 - val_loss: 0.5530 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5442 - accuracy: 0.7220 - val_loss: 0.5445 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7343 - val_loss: 0.5459 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5211 - accuracy: 0.7396 - val_loss: 0.5425 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5101 - accuracy: 0.7453 - val_loss: 0.5439 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7541 - val_loss: 0.5492 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.7610 - val_loss: 0.5483 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4783 - accuracy: 0.7714 - val_loss: 0.5513 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7792 - val_loss: 0.5544 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 10/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4501 - accuracy: 0.7893
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4510 - accuracy: 0.7888 - val_loss: 0.5632 - val_accuracy: 0.7170 - lr: 0.0010
253/253 [==============================] - 0s 2ms/step
Independent Testing Matthews Correlation:  0.4151279038731598
Confusion Matrix :
 [[2631 1417]
 [ 961 3086]]
Accuracy on test set:    0.7062384187770229
Sensitivity:    0.7625401531999012 	 Specificity:    0.6499505928853755
Precision  : 0.685320897179658
Area Under Curve:    0.7062453730426383
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5884 - accuracy: 0.6824 - val_loss: 0.5428 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7225 - val_loss: 0.5358 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7307 - val_loss: 0.5359 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7392 - val_loss: 0.5331 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7468 - val_loss: 0.5378 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7559 - val_loss: 0.5346 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4872 - accuracy: 0.7627 - val_loss: 0.5368 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.7702 - val_loss: 0.5423 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4643 - accuracy: 0.7787
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.7787 - val_loss: 0.5402 - val_accuracy: 0.7257 - lr: 0.0010
253/253 [==============================] - 0s 686us/step
Independent Testing Matthews Correlation:  0.4242328710304151
Confusion Matrix :
 [[2749 1298]
 [1036 3012]]
Accuracy on test set:    0.7116738727609636
Sensitivity:    0.7440711462450593 	 Specificity:    0.679268594020262
Precision  : 0.6988399071925754
Area Under Curve:    0.7116698701326606
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5887 - accuracy: 0.6826 - val_loss: 0.5514 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7216 - val_loss: 0.5370 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7343 - val_loss: 0.5317 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7401 - val_loss: 0.5295 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.7469 - val_loss: 0.5322 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7556 - val_loss: 0.5327 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4878 - accuracy: 0.7636 - val_loss: 0.5332 - val_accuracy: 0.7312 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.7725 - val_loss: 0.5391 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4627 - accuracy: 0.7806 - val_loss: 0.5405 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4490 - accuracy: 0.7877 - val_loss: 0.5477 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4363 - accuracy: 0.7963 - val_loss: 0.5499 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4235 - accuracy: 0.8056
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4242 - accuracy: 0.8049 - val_loss: 0.5603 - val_accuracy: 0.7235 - lr: 0.0010
253/253 [==============================] - 0s 872us/step
Independent Testing Matthews Correlation:  0.4242512924026354
Confusion Matrix :
 [[2601 1446]
 [ 900 3148]]
Accuracy on test set:    0.7101914762198889
Sensitivity:    0.7776679841897233 	 Specificity:    0.6426982950333581
Precision  : 0.6852416195037004
Area Under Curve:    0.7101831396115406
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5868 - accuracy: 0.6834 - val_loss: 0.5431 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5430 - accuracy: 0.7228 - val_loss: 0.5469 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.7335 - val_loss: 0.5375 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7443 - val_loss: 0.5329 - val_accuracy: 0.7311 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7520 - val_loss: 0.5335 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7604 - val_loss: 0.5375 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4800 - accuracy: 0.7686 - val_loss: 0.5409 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4657 - accuracy: 0.7779 - val_loss: 0.5438 - val_accuracy: 0.7285 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4538 - accuracy: 0.7851
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4535 - accuracy: 0.7852 - val_loss: 0.5519 - val_accuracy: 0.7251 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40527864846630623
Confusion Matrix :
 [[2872 1175]
 [1232 2815]]
Accuracy on test set:    0.7026192241166296
Sensitivity:    0.6955769705955028 	 Specificity:    0.7096614776377563
Precision  : 0.7055137844611529
Area Under Curve:    0.7026192241166296
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 8ms/step - loss: 0.5903 - accuracy: 0.6811 - val_loss: 0.5478 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7223 - val_loss: 0.5390 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7315 - val_loss: 0.5357 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7379 - val_loss: 0.5372 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5106 - accuracy: 0.7483 - val_loss: 0.5345 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.7551 - val_loss: 0.5412 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4903 - accuracy: 0.7613 - val_loss: 0.5485 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.7686 - val_loss: 0.5429 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7770 - val_loss: 0.5470 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4583 - accuracy: 0.7839 - val_loss: 0.5476 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 11/400
249/257 [============================>.] - ETA: 0s - loss: 0.4458 - accuracy: 0.7909
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4462 - accuracy: 0.7905 - val_loss: 0.5507 - val_accuracy: 0.7266 - lr: 0.0010
253/253 [==============================] - 0s 953us/step
Independent Testing Matthews Correlation:  0.4247841875290237
Confusion Matrix :
 [[2905 1142]
 [1186 2861]]
Accuracy on test set:    0.7123795404002965
Sensitivity:    0.7069434148752162 	 Specificity:    0.7178156659253768
Precision  : 0.7147139645266051
Area Under Curve:    0.7123795404002966
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5908 - accuracy: 0.6812 - val_loss: 0.5529 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7216 - val_loss: 0.5459 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5305 - accuracy: 0.7321 - val_loss: 0.5407 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.7402 - val_loss: 0.5411 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5104 - accuracy: 0.7478 - val_loss: 0.5412 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.7553 - val_loss: 0.5435 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7637 - val_loss: 0.5430 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.7704 - val_loss: 0.5452 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4647 - accuracy: 0.7779 - val_loss: 0.5477 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4527 - accuracy: 0.7889 - val_loss: 0.5555 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4393 - accuracy: 0.7979 - val_loss: 0.5558 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4271 - accuracy: 0.8045 - val_loss: 0.5628 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 13/400
249/257 [============================>.] - ETA: 0s - loss: 0.4153 - accuracy: 0.8089
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4156 - accuracy: 0.8087 - val_loss: 0.5712 - val_accuracy: 0.7198 - lr: 0.0010
253/253 [==============================] - 0s 732us/step
Independent Testing Matthews Correlation:  0.42800804184828795
Confusion Matrix :
 [[2916 1131]
 [1184 2863]]
Accuracy on test set:    0.7139856683963429
Sensitivity:    0.707437608104769 	 Specificity:    0.720533728687917
Precision  : 0.7168252378567852
Area Under Curve:    0.7139856683963429
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5869 - accuracy: 0.6836 - val_loss: 0.5440 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7218 - val_loss: 0.5456 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5283 - accuracy: 0.7334 - val_loss: 0.5401 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5148 - accuracy: 0.7422 - val_loss: 0.5384 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.7518 - val_loss: 0.5390 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7598 - val_loss: 0.5418 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4798 - accuracy: 0.7691 - val_loss: 0.5508 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4664 - accuracy: 0.7759 - val_loss: 0.5506 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4508 - accuracy: 0.7892
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4511 - accuracy: 0.7890 - val_loss: 0.5536 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 766us/step
Independent Testing Matthews Correlation:  0.437110081713601
Confusion Matrix :
 [[2975 1072]
 [1207 2840]]
Accuracy on test set:    0.7184334074623178
Sensitivity:    0.7017543859649122 	 Specificity:    0.7351124289597233
Precision  : 0.7259713701431493
Area Under Curve:    0.7184334074623178
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5872 - accuracy: 0.6856 - val_loss: 0.5549 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7223 - val_loss: 0.5471 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7318 - val_loss: 0.5446 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7408 - val_loss: 0.5426 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5085 - accuracy: 0.7481 - val_loss: 0.5466 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4985 - accuracy: 0.7552 - val_loss: 0.5439 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7646 - val_loss: 0.5489 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7703 - val_loss: 0.5571 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4626 - accuracy: 0.7812
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4627 - accuracy: 0.7809 - val_loss: 0.5504 - val_accuracy: 0.7213 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4650757129090519
Confusion Matrix :
 [[2938 1109]
 [1056 2991]]
Accuracy on test set:    0.7325179145045713
Sensitivity:    0.7390659747961453 	 Specificity:    0.7259698542129973
Precision  : 0.7295121951219512
Area Under Curve:    0.7325179145045713
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5899 - accuracy: 0.6832 - val_loss: 0.5559 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5481 - accuracy: 0.7210 - val_loss: 0.5483 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5333 - accuracy: 0.7318 - val_loss: 0.5472 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.7403 - val_loss: 0.5465 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.7479 - val_loss: 0.5481 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.7564 - val_loss: 0.5486 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4887 - accuracy: 0.7638 - val_loss: 0.5516 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4738 - accuracy: 0.7732 - val_loss: 0.5542 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4604 - accuracy: 0.7842 - val_loss: 0.5554 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4471 - accuracy: 0.7910 - val_loss: 0.5621 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 11/400
250/257 [============================>.] - ETA: 0s - loss: 0.4357 - accuracy: 0.7989
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4359 - accuracy: 0.7987 - val_loss: 0.5750 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 781us/step
Independent Testing Matthews Correlation:  0.4952122309516951
Confusion Matrix :
 [[3048  999]
 [1044 3003]]
Accuracy on test set:    0.7475908080059304
Sensitivity:    0.7420311341734618 	 Specificity:    0.7531504818383988
Precision  : 0.7503748125937032
Area Under Curve:    0.7475908080059304
(8094, 2560) (8094,)
Mean MCC = 0.4302 + 0.0294 and Mean AUC = 0.7147 + 0.0149
Mean Sensitivity = 0.7303 + 0.0261 and Mean Specificity = 0.6990 + 0.0370 and Mean Accuracy = 0.7147 + 0.0149
Mean Precision = 0.7091 + 0.0216





Seed   : 308830
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5850 - accuracy: 0.6872 - val_loss: 0.5589 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5420 - accuracy: 0.7251 - val_loss: 0.5537 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7365 - val_loss: 0.5605 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.7419 - val_loss: 0.5547 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7500 - val_loss: 0.5547 - val_accuracy: 0.7040 - lr: 0.0010
Epoch 6/400

254/257 [============================>.] - ETA: 0s - loss: 0.4933 - accuracy: 0.7578
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.7578 - val_loss: 0.5575 - val_accuracy: 0.7061 - lr: 0.0010
253/253 [==============================] - 0s 896us/step
Independent Testing Matthews Correlation:  0.4086910202957038
Confusion Matrix :
 [[2715 1333]
 [1064 2983]]
Accuracy on test set:    0.7038912909203212
Sensitivity:    0.7370892018779343 	 Specificity:    0.670701581027668
Precision  : 0.6911492122335496
Area Under Curve:    0.7038953914528011
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5849 - accuracy: 0.6865 - val_loss: 0.5580 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7256 - val_loss: 0.5554 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.7349 - val_loss: 0.5522 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7438 - val_loss: 0.5508 - val_accuracy: 0.7089 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.7509 - val_loss: 0.5526 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - ETA: 0s - loss: 0.4947 - accuracy: 0.7597
Epoch 6: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7597 - val_loss: 0.5513 - val_accuracy: 0.7087 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4140874152173326
Confusion Matrix :
 [[2812 1236]
 [1136 2911]]
Accuracy on test set:    0.7069796170475602
Sensitivity:    0.7192982456140351 	 Specificity:    0.6946640316205533
Precision  : 0.7019532191945985
Area Under Curve:    0.7069811386172942
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5857 - accuracy: 0.6851 - val_loss: 0.5562 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7227 - val_loss: 0.5432 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7345 - val_loss: 0.5427 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7414 - val_loss: 0.5400 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7504 - val_loss: 0.5410 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7583 - val_loss: 0.5422 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 7/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4839 - accuracy: 0.7666
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.7666 - val_loss: 0.5475 - val_accuracy: 0.7168 - lr: 0.0010
253/253 [==============================] - 0s 861us/step
Independent Testing Matthews Correlation:  0.4281414766012498
Confusion Matrix :
 [[2743 1304]
 [1015 3033]]
Accuracy on test set:    0.713526868437307
Sensitivity:    0.7492588932806324 	 Specificity:    0.6777860143316037
Precision  : 0.6993313350242103
Area Under Curve:    0.713522453806118
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5918 - accuracy: 0.6803 - val_loss: 0.5499 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7239 - val_loss: 0.5394 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5326 - accuracy: 0.7310 - val_loss: 0.5384 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5206 - accuracy: 0.7403 - val_loss: 0.5380 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.7457 - val_loss: 0.5394 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7565 - val_loss: 0.5420 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7635 - val_loss: 0.5469 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4733 - accuracy: 0.7734 - val_loss: 0.5456 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4603 - accuracy: 0.7824 - val_loss: 0.5451 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4476 - accuracy: 0.7894 - val_loss: 0.5518 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4334 - accuracy: 0.7996 - val_loss: 0.5573 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 12/400
251/257 [============================>.] - ETA: 0s - loss: 0.4228 - accuracy: 0.8046
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4232 - accuracy: 0.8042 - val_loss: 0.5637 - val_accuracy: 0.7167 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40126201214753376
Confusion Matrix :
 [[2890 1157]
 [1267 2781]]
Accuracy on test set:    0.700555898702903
Sensitivity:    0.6870059288537549 	 Specificity:    0.7141092167037312
Precision  : 0.7061960385982733
Area Under Curve:    0.700557572778743
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5890 - accuracy: 0.6812 - val_loss: 0.5490 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7213 - val_loss: 0.5397 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7344 - val_loss: 0.5350 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7412 - val_loss: 0.5316 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7499 - val_loss: 0.5436 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7553 - val_loss: 0.5351 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4867 - accuracy: 0.7651 - val_loss: 0.5328 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4765 - accuracy: 0.7714 - val_loss: 0.5323 - val_accuracy: 0.7267 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4633 - accuracy: 0.7796 - val_loss: 0.5395 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4509 - accuracy: 0.7877 - val_loss: 0.5482 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 11/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4359 - accuracy: 0.7964
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4361 - accuracy: 0.7962 - val_loss: 0.5461 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41638547424504485
Confusion Matrix :
 [[2792 1255]
 [1108 2939]]
Accuracy on test set:    0.7080553496417099
Sensitivity:    0.7262169508277737 	 Specificity:    0.6898937484556461
Precision  : 0.7007629947544111
Area Under Curve:    0.70805534964171
(8094, 2560) (8094,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5867 - accuracy: 0.6867 - val_loss: 0.5490 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5451 - accuracy: 0.7224 - val_loss: 0.5423 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5309 - accuracy: 0.7333 - val_loss: 0.5420 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.7413 - val_loss: 0.5424 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7475 - val_loss: 0.5364 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.7572 - val_loss: 0.5402 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
256/257 [============================>.] - ETA: 0s - loss: 0.4853 - accuracy: 0.7642
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.7642 - val_loss: 0.5402 - val_accuracy: 0.7231 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43422532667196834
Confusion Matrix :
 [[2940 1107]
 [1183 2864]]
Accuracy on test set:    0.7170743760810477
Sensitivity:    0.7076847047195454 	 Specificity:    0.72646404744255
Precision  : 0.7212289095945605
Area Under Curve:    0.7170743760810478
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5884 - accuracy: 0.6808 - val_loss: 0.5470 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7227 - val_loss: 0.5429 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7334 - val_loss: 0.5376 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7430 - val_loss: 0.5403 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.7513 - val_loss: 0.5396 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7605 - val_loss: 0.5424 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4804 - accuracy: 0.7685 - val_loss: 0.5405 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 8/400
254/257 [============================>.] - ETA: 0s - loss: 0.4668 - accuracy: 0.7786
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4669 - accuracy: 0.7786 - val_loss: 0.5435 - val_accuracy: 0.7226 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42375249280475835
Confusion Matrix :
 [[2814 1233]
 [1100 2947]]
Accuracy on test set:    0.7117617988633556
Sensitivity:    0.7281937237459847 	 Specificity:    0.6953298739807264
Precision  : 0.7050239234449761
Area Under Curve:    0.7117617988633556
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5877 - accuracy: 0.6843 - val_loss: 0.5521 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7217 - val_loss: 0.5455 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7324 - val_loss: 0.5373 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7423 - val_loss: 0.5377 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5040 - accuracy: 0.7508 - val_loss: 0.5393 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4924 - accuracy: 0.7582 - val_loss: 0.5392 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7682 - val_loss: 0.5464 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 8/400
256/257 [============================>.] - ETA: 0s - loss: 0.4689 - accuracy: 0.7774
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4689 - accuracy: 0.7774 - val_loss: 0.5484 - val_accuracy: 0.7190 - lr: 0.0010
253/253 [==============================] - 0s 827us/step
Independent Testing Matthews Correlation:  0.45056278064232563
Confusion Matrix :
 [[3136  911]
 [1322 2725]]
Accuracy on test set:    0.7241166296021745
Sensitivity:    0.6733382752656288 	 Specificity:    0.77489498393872
Precision  : 0.7494499449944995
Area Under Curve:    0.7241166296021744
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5899 - accuracy: 0.6834 - val_loss: 0.5515 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7220 - val_loss: 0.5438 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7332 - val_loss: 0.5411 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7387 - val_loss: 0.5411 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7471 - val_loss: 0.5472 - val_accuracy: 0.7139 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7552 - val_loss: 0.5429 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.7631 - val_loss: 0.5452 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4774 - accuracy: 0.7717 - val_loss: 0.5482 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 9/400
255/257 [============================>.] - ETA: 0s - loss: 0.4649 - accuracy: 0.7790
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4649 - accuracy: 0.7790 - val_loss: 0.5500 - val_accuracy: 0.7150 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4500715065219247
Confusion Matrix :
 [[3101  946]
 [1286 2761]]
Accuracy on test set:    0.7242401779095626
Sensitivity:    0.6822337533975784 	 Specificity:    0.7662466024215469
Precision  : 0.744807121661721
Area Under Curve:    0.7242401779095626
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5922 - accuracy: 0.6808 - val_loss: 0.5547 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7193 - val_loss: 0.5488 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5348 - accuracy: 0.7308 - val_loss: 0.5520 - val_accuracy: 0.7098 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5231 - accuracy: 0.7382 - val_loss: 0.5467 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5129 - accuracy: 0.7467 - val_loss: 0.5482 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.7540 - val_loss: 0.5516 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4897 - accuracy: 0.7633 - val_loss: 0.5540 - val_accuracy: 0.7193 - lr: 0.0010

Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4765 - accuracy: 0.7719 - val_loss: 0.5583 - val_accuracy: 0.7178 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4632 - accuracy: 0.7812 - val_loss: 0.5627 - val_accuracy: 0.7128 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4508 - accuracy: 0.7897 - val_loss: 0.5725 - val_accuracy: 0.7130 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4369 - accuracy: 0.7964
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4371 - accuracy: 0.7963 - val_loss: 0.5715 - val_accuracy: 0.7130 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4724590489814867
Confusion Matrix :
 [[3109  938]
 [1201 2846]]
Accuracy on test set:    0.7357301704966642
Sensitivity:    0.7032369656535705 	 Specificity:    0.7682233753397578
Precision  : 0.7521141649048626
Area Under Curve:    0.7357301704966641
(8094, 2560) (8094,)
Mean MCC = 0.4300 + 0.0210 and Mean AUC = 0.7146 + 0.0103
Mean Sensitivity = 0.7114 + 0.0237 and Mean Specificity = 0.7178 + 0.0373 and Mean Accuracy = 0.7146 + 0.0103
Mean Precision = 0.7172 + 0.0219





Seed   : 826032
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5890 - accuracy: 0.6835 - val_loss: 0.5569 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7247 - val_loss: 0.5491 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7353 - val_loss: 0.5472 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7442 - val_loss: 0.5488 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7534 - val_loss: 0.5573 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.7611 - val_loss: 0.5521 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7682 - val_loss: 0.5540 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7771 - val_loss: 0.5714 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4565 - accuracy: 0.7834 - val_loss: 0.5666 - val_accuracy: 0.7023 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4444 - accuracy: 0.7913 - val_loss: 0.5686 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 11/400
253/257 [============================>.] - ETA: 0s - loss: 0.4319 - accuracy: 0.8007
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4319 - accuracy: 0.8005 - val_loss: 0.5775 - val_accuracy: 0.7040 - lr: 0.0010
253/253 [==============================] - 0s 767us/step
Independent Testing Matthews Correlation:  0.3935053295628745
Confusion Matrix :
 [[2625 1423]
 [1039 3008]]
Accuracy on test set:    0.6958616429894997
Sensitivity:    0.7432666172473437 	 Specificity:    0.6484683794466403
Precision  : 0.6788535319341007
Area Under Curve:    0.695867498346992
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5844 - accuracy: 0.6875 - val_loss: 0.5617 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5415 - accuracy: 0.7255 - val_loss: 0.5528 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.7367 - val_loss: 0.5572 - val_accuracy: 0.7027 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5152 - accuracy: 0.7453 - val_loss: 0.5508 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7534 - val_loss: 0.5575 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.7613 - val_loss: 0.5635 - val_accuracy: 0.7002 - lr: 0.0010
Epoch 7/400
242/257 [===========================>..] - ETA: 0s - loss: 0.4773 - accuracy: 0.7700
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4781 - accuracy: 0.7698 - val_loss: 0.5562 - val_accuracy: 0.7053 - lr: 0.0010
253/253 [==============================] - 0s 997us/step
Independent Testing Matthews Correlation:  0.42705018281329976
Confusion Matrix :
 [[2820 1228]
 [1092 2955]]
Accuracy on test set:    0.7134033353922175
Sensitivity:    0.7301704966641956 	 Specificity:    0.6966403162055336
Precision  : 0.7064307912981114
Area Under Curve:    0.7134054064348647
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5871 - accuracy: 0.6832 - val_loss: 0.5557 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7233 - val_loss: 0.5412 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7340 - val_loss: 0.5408 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7420 - val_loss: 0.5406 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7532 - val_loss: 0.5407 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7624 - val_loss: 0.5433 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4774 - accuracy: 0.7700 - val_loss: 0.5490 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4655 - accuracy: 0.7783 - val_loss: 0.5483 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4516 - accuracy: 0.7872 - val_loss: 0.5565 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4389 - accuracy: 0.7947 - val_loss: 0.5602 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4252 - accuracy: 0.8032 - val_loss: 0.5648 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4118 - accuracy: 0.8126 - val_loss: 0.5680 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3997 - accuracy: 0.8178 - val_loss: 0.5807 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 14/400
254/257 [============================>.] - ETA: 0s - loss: 0.3883 - accuracy: 0.8232
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3886 - accuracy: 0.8229 - val_loss: 0.5823 - val_accuracy: 0.7128 - lr: 0.0010
253/253 [==============================] - 0s 950us/step
Independent Testing Matthews Correlation:  0.41581091798862074
Confusion Matrix :
 [[2753 1294]
 [1073 2975]]
Accuracy on test set:    0.707597282273008
Sensitivity:    0.7349308300395256 	 Specificity:    0.6802569804793674
Precision  : 0.6968845162801592
Area Under Curve:    0.7075939052594465
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5894 - accuracy: 0.6817 - val_loss: 0.5478 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7209 - val_loss: 0.5359 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7312 - val_loss: 0.5355 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7410 - val_loss: 0.5420 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7493 - val_loss: 0.5353 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7602 - val_loss: 0.5363 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4831 - accuracy: 0.7673 - val_loss: 0.5373 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4714 - accuracy: 0.7742 - val_loss: 0.5443 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4597 - accuracy: 0.7836 - val_loss: 0.5460 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4465 - accuracy: 0.7911 - val_loss: 0.5559 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4358 - accuracy: 0.7984 - val_loss: 0.5572 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 12/400
252/257 [============================>.] - ETA: 0s - loss: 0.4236 - accuracy: 0.8037
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4236 - accuracy: 0.8037 - val_loss: 0.5606 - val_accuracy: 0.7163 - lr: 0.0010
253/253 [==============================] - 0s 865us/step
Independent Testing Matthews Correlation:  0.41223309365681116
Confusion Matrix :
 [[2849 1198]
 [1181 2867]]
Accuracy on test set:    0.7061148857319333
Sensitivity:    0.7082509881422925 	 Specificity:    0.7039782554978997
Precision  : 0.7052890528905289
Area Under Curve:    0.7061146218200961
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5887 - accuracy: 0.6819 - val_loss: 0.5508 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7202 - val_loss: 0.5436 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7319 - val_loss: 0.5381 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7403 - val_loss: 0.5359 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7505 - val_loss: 0.5446 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7576 - val_loss: 0.5416 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.7665 - val_loss: 0.5444 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4708 - accuracy: 0.7755 - val_loss: 0.5471 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4596 - accuracy: 0.7820
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.7817 - val_loss: 0.5470 - val_accuracy: 0.7277 - lr: 0.0010
253/253 [==============================] - 0s 847us/step
Independent Testing Matthews Correlation:  0.42562774115789137
Confusion Matrix :
 [[2835 1212]
 [1113 2934]]
Accuracy on test set:    0.712750185322461
Sensitivity:    0.7249814677538917 	 Specificity:    0.7005189028910304
Precision  : 0.7076700434153401
Area Under Curve:    0.712750185322461
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 7ms/step - loss: 0.5850 - accuracy: 0.6875 - val_loss: 0.5503 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7246 - val_loss: 0.5448 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7318 - val_loss: 0.5396 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7429 - val_loss: 0.5403 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7484 - val_loss: 0.5440 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7566 - val_loss: 0.5401 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7691 - val_loss: 0.5516 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4673 - accuracy: 0.7755 - val_loss: 0.5544 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4563 - accuracy: 0.7827 - val_loss: 0.5535 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4422 - accuracy: 0.7935 - val_loss: 0.5610 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4292 - accuracy: 0.8006 - val_loss: 0.5696 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 12/400
255/257 [============================>.] - ETA: 0s - loss: 0.4161 - accuracy: 0.8081
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4158 - accuracy: 0.8083 - val_loss: 0.5755 - val_accuracy: 0.7174 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42553792362780796
Confusion Matrix :
 [[2810 1237]
 [1089 2958]]
Accuracy on test set:    0.7126266370150729
Sensitivity:    0.7309117865085248 	 Specificity:    0.694341487521621
Precision  : 0.7051251489868892
Area Under Curve:    0.7126266370150729
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5860 - accuracy: 0.6851 - val_loss: 0.5516 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5448 - accuracy: 0.7228 - val_loss: 0.5489 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7335 - val_loss: 0.5371 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7417 - val_loss: 0.5346 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7496 - val_loss: 0.5426 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4941 - accuracy: 0.7583 - val_loss: 0.5371 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.7660 - val_loss: 0.5399 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4707 - accuracy: 0.7748 - val_loss: 0.5447 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 9/400
251/257 [============================>.] - ETA: 0s - loss: 0.4564 - accuracy: 0.7846
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4562 - accuracy: 0.7846 - val_loss: 0.5494 - val_accuracy: 0.7226 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42532827956884317
Confusion Matrix :
 [[2846 1201]
 [1125 2922]]
Accuracy on test set:    0.7126266370150729
Sensitivity:    0.7220163083765753 	 Specificity:    0.7032369656535705
Precision  : 0.7087072520009702
Area Under Curve:    0.712626637015073
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5882 - accuracy: 0.6846 - val_loss: 0.5463 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7235 - val_loss: 0.5442 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7333 - val_loss: 0.5356 - val_accuracy: 0.7296 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7438 - val_loss: 0.5350 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5056 - accuracy: 0.7513 - val_loss: 0.5394 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7589 - val_loss: 0.5410 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7679 - val_loss: 0.5417 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4692 - accuracy: 0.7775
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4691 - accuracy: 0.7774 - val_loss: 0.5451 - val_accuracy: 0.7266 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43396844561244907
Confusion Matrix :
 [[2937 1110]
 [1181 2866]]
Accuracy on test set:    0.7169508277736595
Sensitivity:    0.708178897949098 	 Specificity:    0.7257227575982209
Precision  : 0.7208249496981891
Area Under Curve:    0.7169508277736594
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5969 - accuracy: 0.6758 - val_loss: 0.5528 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5527 - accuracy: 0.7188 - val_loss: 0.5432 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5374 - accuracy: 0.7301 - val_loss: 0.5425 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5252 - accuracy: 0.7368 - val_loss: 0.5384 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7436 - val_loss: 0.5397 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5024 - accuracy: 0.7527 - val_loss: 0.5389 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7600 - val_loss: 0.5391 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7695 - val_loss: 0.5441 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4672 - accuracy: 0.7789 - val_loss: 0.5520 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4553 - accuracy: 0.7871 - val_loss: 0.5485 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4427 - accuracy: 0.7951 - val_loss: 0.5573 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4336 - accuracy: 0.7994
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4336 - accuracy: 0.7994 - val_loss: 0.5647 - val_accuracy: 0.7176 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.462049100736298
Confusion Matrix :
 [[3049  998]
 [1181 2866]]
Accuracy on test set:    0.7307882382011367
Sensitivity:    0.708178897949098 	 Specificity:    0.7533975784531752
Precision  : 0.7417184265010351
Area Under Curve:    0.7307882382011366
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5963 - accuracy: 0.6755 - val_loss: 0.5542 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5527 - accuracy: 0.7187 - val_loss: 0.5479 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5398 - accuracy: 0.7279 - val_loss: 0.5417 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7357 - val_loss: 0.5430 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7442 - val_loss: 0.5421 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7512 - val_loss: 0.5441 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4939 - accuracy: 0.7589 - val_loss: 0.5531 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4799 - accuracy: 0.7695
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7694 - val_loss: 0.5479 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4670757815467786
Confusion Matrix :
 [[3164  883]
 [1283 2764]]
Accuracy on test set:    0.7323943661971831
Sensitivity:    0.6829750432419076 	 Specificity:    0.7818136891524586
Precision  : 0.7578831916643817
Area Under Curve:    0.7323943661971831
(8094, 2560) (8094,)
Mean MCC = 0.4288 + 0.0208 and Mean AUC = 0.7141 + 0.0103
Mean Sensitivity = 0.7194 + 0.0167 and Mean Specificity = 0.7088 + 0.0354 and Mean Accuracy = 0.7141 + 0.0103
Mean Precision = 0.7129 + 0.0213





Seed   : 97935
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5874 - accuracy: 0.6851 - val_loss: 0.5622 - val_accuracy: 0.7031 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.7262 - val_loss: 0.5551 - val_accuracy: 0.7072 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5256 - accuracy: 0.7357 - val_loss: 0.5554 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5135 - accuracy: 0.7448 - val_loss: 0.5540 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7533 - val_loss: 0.5577 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.7606 - val_loss: 0.5607 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.7679 - val_loss: 0.5634 - val_accuracy: 0.7083 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4673 - accuracy: 0.7752 - val_loss: 0.5753 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.7845 - val_loss: 0.5681 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 10/400
255/257 [============================>.] - ETA: 0s - loss: 0.4436 - accuracy: 0.7949
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4438 - accuracy: 0.7946 - val_loss: 0.5755 - val_accuracy: 0.7010 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41285426350790627
Confusion Matrix :
 [[2809 1239]
 [1138 2909]]
Accuracy on test set:    0.7063619518221124
Sensitivity:    0.7188040523844823 	 Specificity:    0.6939229249011858
Precision  : 0.7013018322082931
Area Under Curve:    0.706363488642834
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5843 - accuracy: 0.6882 - val_loss: 0.5634 - val_accuracy: 0.7028 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5413 - accuracy: 0.7250 - val_loss: 0.5540 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5254 - accuracy: 0.7355 - val_loss: 0.5525 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5120 - accuracy: 0.7459 - val_loss: 0.5519 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.7532 - val_loss: 0.5534 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4886 - accuracy: 0.7625 - val_loss: 0.5609 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 7/400
254/257 [============================>.] - ETA: 0s - loss: 0.4767 - accuracy: 0.7692
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4769 - accuracy: 0.7691 - val_loss: 0.5556 - val_accuracy: 0.7087 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42537597075405176
Confusion Matrix :
 [[2809 1239]
 [1088 2959]]
Accuracy on test set:    0.7125386040765905
Sensitivity:    0.7311588831233012 	 Specificity:    0.6939229249011858
Precision  : 0.7048594568842306
Area Under Curve:    0.7125409040122436
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5923 - accuracy: 0.6799 - val_loss: 0.5584 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7200 - val_loss: 0.5439 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7324 - val_loss: 0.5408 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 3ms/step - loss: 0.5202 - accuracy: 0.7387 - val_loss: 0.5400 - val_accuracy: 0.7190 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7497 - val_loss: 0.5437 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.7558 - val_loss: 0.5426 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7646 - val_loss: 0.5504 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4733 - accuracy: 0.7727 - val_loss: 0.5511 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4601 - accuracy: 0.7826 - val_loss: 0.5531 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4486 - accuracy: 0.7883 - val_loss: 0.5560 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4362 - accuracy: 0.7963 - val_loss: 0.5604 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4233 - accuracy: 0.8050 - val_loss: 0.5687 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4102 - accuracy: 0.8114 - val_loss: 0.5746 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 14/400
256/257 [============================>.] - ETA: 0s - loss: 0.3998 - accuracy: 0.8177
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3999 - accuracy: 0.8176 - val_loss: 0.5795 - val_accuracy: 0.7189 - lr: 0.0010
253/253 [==============================] - 0s 723us/step
Independent Testing Matthews Correlation:  0.3957877804413629
Confusion Matrix :
 [[2737 1310]
 [1137 2911]]
Accuracy on test set:    0.6977146386658432
Sensitivity:    0.7191205533596838 	 Specificity:    0.6763034346429454
Precision  : 0.689647003079839
Area Under Curve:    0.6977119940013146
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5867 - accuracy: 0.6850 - val_loss: 0.5463 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7227 - val_loss: 0.5376 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7332 - val_loss: 0.5360 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7411 - val_loss: 0.5369 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.7515 - val_loss: 0.5349 - val_accuracy: 0.7294 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.7559 - val_loss: 0.5397 - val_accuracy: 0.7301 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.7656 - val_loss: 0.5448 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4715 - accuracy: 0.7738 - val_loss: 0.5470 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4576 - accuracy: 0.7828 - val_loss: 0.5506 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4441 - accuracy: 0.7926 - val_loss: 0.5569 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 11/400
254/257 [============================>.] - ETA: 0s - loss: 0.4299 - accuracy: 0.8029
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4299 - accuracy: 0.8029 - val_loss: 0.5610 - val_accuracy: 0.7263 - lr: 0.0010
253/253 [==============================] - 0s 731us/step
Independent Testing Matthews Correlation:  0.4123468015715027
Confusion Matrix :
 [[2746 1301]
 [1080 2968]]
Accuracy on test set:    0.7058678196417542
Sensitivity:    0.733201581027668 	 Specificity:    0.6785273041759328
Precision  : 0.6952447880065589
Area Under Curve:    0.7058644426018004
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5905 - accuracy: 0.6803 - val_loss: 0.5496 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7217 - val_loss: 0.5417 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7332 - val_loss: 0.5438 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.7424 - val_loss: 0.5394 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5048 - accuracy: 0.7494 - val_loss: 0.5435 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4927 - accuracy: 0.7592 - val_loss: 0.5428 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 7/400
252/257 [============================>.] - ETA: 0s - loss: 0.4820 - accuracy: 0.7664
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.7660 - val_loss: 0.5455 - val_accuracy: 0.7231 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42289614414218146
Confusion Matrix :
 [[2731 1316]
 [1024 3023]]
Accuracy on test set:    0.7108969607116382
Sensitivity:    0.7469730664689894 	 Specificity:    0.6748208549542871
Precision  : 0.69670430974879
Area Under Curve:    0.7108969607116382
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5870 - accuracy: 0.6860 - val_loss: 0.5544 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7233 - val_loss: 0.5525 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7343 - val_loss: 0.5431 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7426 - val_loss: 0.5451 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7508 - val_loss: 0.5475 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7590 - val_loss: 0.5471 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4817 - accuracy: 0.7693 - val_loss: 0.5488 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7764 - val_loss: 0.5527 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 9/400
252/257 [============================>.] - ETA: 0s - loss: 0.4562 - accuracy: 0.7833
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4568 - accuracy: 0.7828 - val_loss: 0.5540 - val_accuracy: 0.7121 - lr: 0.0010
253/253 [==============================] - 0s 885us/step
Independent Testing Matthews Correlation:  0.4364948337887981
Confusion Matrix :
 [[2798 1249]
 [1034 3013]]
Accuracy on test set:    0.717939214232765
Sensitivity:    0.7445021003212255 	 Specificity:    0.6913763281443044
Precision  : 0.7069450961989676
Area Under Curve:    0.7179392142327649
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5884 - accuracy: 0.6825 - val_loss: 0.5512 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7223 - val_loss: 0.5443 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7320 - val_loss: 0.5417 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7402 - val_loss: 0.5543 - val_accuracy: 0.7146 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7487 - val_loss: 0.5421 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.7585 - val_loss: 0.5433 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4825 - accuracy: 0.7663
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7658 - val_loss: 0.5534 - val_accuracy: 0.7186 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4316542002573648
Confusion Matrix :
 [[2645 1402]
 [ 911 3136]]
Accuracy on test set:    0.7142327650111193
Sensitivity:    0.77489498393872 	 Specificity:    0.6535705460835186
Precision  : 0.6910533274570295
Area Under Curve:    0.7142327650111193
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5897 - accuracy: 0.6826 - val_loss: 0.5558 - val_accuracy: 0.7160 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7234 - val_loss: 0.5447 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7327 - val_loss: 0.5410 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7428 - val_loss: 0.5445 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7504 - val_loss: 0.5436 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7585 - val_loss: 0.5440 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.7677 - val_loss: 0.5473 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4703 - accuracy: 0.7750 - val_loss: 0.5447 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4567 - accuracy: 0.7847 - val_loss: 0.5500 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4453 - accuracy: 0.7928 - val_loss: 0.5592 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4304 - accuracy: 0.8030
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4305 - accuracy: 0.8027 - val_loss: 0.5655 - val_accuracy: 0.7220 - lr: 0.0010
253/253 [==============================] - 0s 702us/step
Independent Testing Matthews Correlation:  0.4453617736821049
Confusion Matrix :
 [[2966 1081]
 [1164 2883]]
Accuracy on test set:    0.7226340499135162
Sensitivity:    0.7123795404002965 	 Specificity:    0.7328885594267358
Precision  : 0.7272956609485368
Area Under Curve:    0.7226340499135161
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 4ms/step - loss: 0.5896 - accuracy: 0.6837 - val_loss: 0.5533 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5486 - accuracy: 0.7207 - val_loss: 0.5495 - val_accuracy: 0.7156 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5332 - accuracy: 0.7315 - val_loss: 0.5449 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5228 - accuracy: 0.7367 - val_loss: 0.5477 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5112 - accuracy: 0.7487 - val_loss: 0.5504 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7543 - val_loss: 0.5491 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.7635 - val_loss: 0.5530 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.7729 - val_loss: 0.5548 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4625 - accuracy: 0.7799 - val_loss: 0.5587 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4484 - accuracy: 0.7884 - val_loss: 0.5682 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4374 - accuracy: 0.7950 - val_loss: 0.5640 - val_accuracy: 0.7131 - lr: 0.0010
Epoch 12/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4231 - accuracy: 0.8032
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4235 - accuracy: 0.8029 - val_loss: 0.5772 - val_accuracy: 0.7142 - lr: 0.0010

253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4388600003075183
Confusion Matrix :
 [[2929 1118]
 [1153 2894]]
Accuracy on test set:    0.7194217939214232
Sensitivity:    0.7150976031628367 	 Specificity:    0.7237459846800098
Precision  : 0.7213359920239282
Area Under Curve:    0.7194217939214232
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5960 - accuracy: 0.6769 - val_loss: 0.5661 - val_accuracy: 0.7057 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5508 - accuracy: 0.7195 - val_loss: 0.5521 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5352 - accuracy: 0.7302 - val_loss: 0.5527 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5246 - accuracy: 0.7375 - val_loss: 0.5498 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.7474 - val_loss: 0.5471 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5040 - accuracy: 0.7524 - val_loss: 0.5526 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4923 - accuracy: 0.7615 - val_loss: 0.5623 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4802 - accuracy: 0.7705 - val_loss: 0.5581 - val_accuracy: 0.7154 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4681 - accuracy: 0.7789 - val_loss: 0.5640 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 10/400
254/257 [============================>.] - ETA: 0s - loss: 0.4547 - accuracy: 0.7886
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4549 - accuracy: 0.7886 - val_loss: 0.5665 - val_accuracy: 0.7100 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4682449773575657
Confusion Matrix :
 [[3201  846]
 [1319 2728]]
Accuracy on test set:    0.7325179145045713
Sensitivity:    0.674079565109958 	 Specificity:    0.7909562638991846
Precision  : 0.7632904308897593
Area Under Curve:    0.7325179145045714
(8094, 2560) (8094,)
Mean MCC = 0.4290 + 0.0191 and Mean AUC = 0.7140 + 0.0093
Mean Sensitivity = 0.7270 + 0.0252 and Mean Specificity = 0.7010 + 0.0372 and Mean Accuracy = 0.7140 + 0.0093
Mean Precision = 0.7098 + 0.0213





Seed   : 106312
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5894 - accuracy: 0.6842 - val_loss: 0.5593 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7244 - val_loss: 0.5546 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7341 - val_loss: 0.5497 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5168 - accuracy: 0.7435 - val_loss: 0.5532 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5055 - accuracy: 0.7519 - val_loss: 0.5511 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.7597 - val_loss: 0.5578 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7687 - val_loss: 0.5537 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.7766 - val_loss: 0.5568 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4579 - accuracy: 0.7847 - val_loss: 0.5632 - val_accuracy: 0.7097 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4447 - accuracy: 0.7912 - val_loss: 0.5727 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4317 - accuracy: 0.7995 - val_loss: 0.5791 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4202 - accuracy: 0.8070 - val_loss: 0.5908 - val_accuracy: 0.7091 - lr: 0.0010
Epoch 13/400
249/257 [============================>.] - ETA: 0s - loss: 0.4062 - accuracy: 0.8132
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4066 - accuracy: 0.8131 - val_loss: 0.5981 - val_accuracy: 0.7111 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4021652321444211
Confusion Matrix :
 [[2658 1390]
 [1036 3011]]
Accuracy on test set:    0.7003088326127239
Sensitivity:    0.7440079070916729 	 Specificity:    0.6566205533596838
Precision  : 0.6841626902976596
Area Under Curve:    0.7003142302256784
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5859 - accuracy: 0.6856 - val_loss: 0.5583 - val_accuracy: 0.7061 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7253 - val_loss: 0.5562 - val_accuracy: 0.7123 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5267 - accuracy: 0.7358 - val_loss: 0.5508 - val_accuracy: 0.7111 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7438 - val_loss: 0.5471 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5020 - accuracy: 0.7522 - val_loss: 0.5487 - val_accuracy: 0.7137 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4892 - accuracy: 0.7627 - val_loss: 0.5536 - val_accuracy: 0.7062 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7710 - val_loss: 0.5546 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4624 - accuracy: 0.7822 - val_loss: 0.5549 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 9/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4501 - accuracy: 0.7877
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4496 - accuracy: 0.7877 - val_loss: 0.5661 - val_accuracy: 0.7142 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.43262677927276244
Confusion Matrix :
 [[2696 1352]
 [ 953 3094]]
Accuracy on test set:    0.7152563310685608
Sensitivity:    0.7645169261181122 	 Specificity:    0.66600790513834
Precision  : 0.695906432748538
Area Under Curve:    0.715262415628226
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5886 - accuracy: 0.6829 - val_loss: 0.5551 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7232 - val_loss: 0.5422 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7323 - val_loss: 0.5385 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7424 - val_loss: 0.5458 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7516 - val_loss: 0.5383 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4944 - accuracy: 0.7584 - val_loss: 0.5382 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.7672 - val_loss: 0.5423 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.7744 - val_loss: 0.5470 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4604 - accuracy: 0.7818 - val_loss: 0.5529 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4469 - accuracy: 0.7895 - val_loss: 0.5523 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - ETA: 0s - loss: 0.4347 - accuracy: 0.7974
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4347 - accuracy: 0.7974 - val_loss: 0.5598 - val_accuracy: 0.7143 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42186680418327377
Confusion Matrix :
 [[2882 1165]
 [1175 2873]]
Accuracy on test set:    0.7109326744904262
Sensitivity:    0.7097332015810277 	 Specificity:    0.7121324437855201
Precision  : 0.7114908370480436
Area Under Curve:    0.710932822683274
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5881 - accuracy: 0.6824 - val_loss: 0.5507 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5458 - accuracy: 0.7214 - val_loss: 0.5414 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.7328 - val_loss: 0.5384 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7410 - val_loss: 0.5382 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7524 - val_loss: 0.5373 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7577 - val_loss: 0.5411 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4819 - accuracy: 0.7666 - val_loss: 0.5442 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4685 - accuracy: 0.7757 - val_loss: 0.5492 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4568 - accuracy: 0.7826 - val_loss: 0.5541 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4434 - accuracy: 0.7913 - val_loss: 0.5565 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4286 - accuracy: 0.8005 - val_loss: 0.5618 - val_accuracy: 0.7179 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4171 - accuracy: 0.8087 - val_loss: 0.5692 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 13/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4026 - accuracy: 0.8169
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4033 - accuracy: 0.8166 - val_loss: 0.5752 - val_accuracy: 0.7201 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4198575428644674
Confusion Matrix :
 [[2717 1330]
 [1023 3025]]
Accuracy on test set:    0.7093267449042618
Sensitivity:    0.7472826086956522 	 Specificity:    0.6713615023474179
Precision  : 0.6946039035591275
Area Under Curve:    0.709322055521535
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5874 - accuracy: 0.6861 - val_loss: 0.5474 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5445 - accuracy: 0.7215 - val_loss: 0.5445 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7333 - val_loss: 0.5410 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.7409 - val_loss: 0.5421 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.7484 - val_loss: 0.5462 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.7567 - val_loss: 0.5442 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4827 - accuracy: 0.7651 - val_loss: 0.5510 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 8/400
249/257 [============================>.] - ETA: 0s - loss: 0.4673 - accuracy: 0.7752
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4677 - accuracy: 0.7749 - val_loss: 0.5474 - val_accuracy: 0.7178 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4196358206901461
Confusion Matrix :
 [[2767 1280]
 [1071 2976]]
Accuracy on test set:    0.7095379293303682
Sensitivity:    0.7353595255744997 	 Specificity:    0.6837163330862367
Precision  : 0.6992481203007519
Area Under Curve:    0.7095379293303682
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5999 - accuracy: 0.6712 - val_loss: 0.5629 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5500 - accuracy: 0.7201 - val_loss: 0.5462 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5344 - accuracy: 0.7318 - val_loss: 0.5443 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5223 - accuracy: 0.7390 - val_loss: 0.5440 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.7477 - val_loss: 0.5451 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5022 - accuracy: 0.7528 - val_loss: 0.5430 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.7626 - val_loss: 0.5469 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4773 - accuracy: 0.7706 - val_loss: 0.5575 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4653 - accuracy: 0.7797 - val_loss: 0.5526 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4537 - accuracy: 0.7883 - val_loss: 0.5612 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4398 - accuracy: 0.7965 - val_loss: 0.5760 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 12/400
255/257 [============================>.] - ETA: 0s - loss: 0.4257 - accuracy: 0.8030
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4259 - accuracy: 0.8030 - val_loss: 0.5741 - val_accuracy: 0.7197 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.40970074121436045
Confusion Matrix :
 [[2709 1338]
 [1055 2992]]
Accuracy on test set:    0.7043489004200643
Sensitivity:    0.7393130714109216 	 Specificity:    0.6693847294292068
Precision  : 0.6909930715935335
Area Under Curve:    0.7043489004200643
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5858 - accuracy: 0.6868 - val_loss: 0.5496 - val_accuracy: 0.7205 - lr: 0.0010

Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5416 - accuracy: 0.7260 - val_loss: 0.5422 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7342 - val_loss: 0.5407 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5164 - accuracy: 0.7419 - val_loss: 0.5429 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7511 - val_loss: 0.5446 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7579 - val_loss: 0.5482 - val_accuracy: 0.7193 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4819 - accuracy: 0.7660 - val_loss: 0.5495 - val_accuracy: 0.7167 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4710 - accuracy: 0.7755
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7755 - val_loss: 0.5526 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41336215599399445
Confusion Matrix :
 [[2925 1122]
 [1253 2794]]
Accuracy on test set:    0.7065727699530516
Sensitivity:    0.6903879416851989 	 Specificity:    0.7227575982209044
Precision  : 0.7134831460674157
Area Under Curve:    0.7065727699530516
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5870 - accuracy: 0.6842 - val_loss: 0.5486 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7219 - val_loss: 0.5415 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7331 - val_loss: 0.5389 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7403 - val_loss: 0.5386 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.7479 - val_loss: 0.5378 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4980 - accuracy: 0.7545 - val_loss: 0.5383 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.7617 - val_loss: 0.5401 - val_accuracy: 0.7288 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4746 - accuracy: 0.7711 - val_loss: 0.5507 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4627 - accuracy: 0.7795 - val_loss: 0.5466 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4503 - accuracy: 0.7883 - val_loss: 0.5522 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4378 - accuracy: 0.7960 - val_loss: 0.5587 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - ETA: 0s - loss: 0.4265 - accuracy: 0.8038
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4265 - accuracy: 0.8038 - val_loss: 0.5628 - val_accuracy: 0.7213 - lr: 0.0010
253/253 [==============================] - 0s 882us/step
Independent Testing Matthews Correlation:  0.43691197620589
Confusion Matrix :
 [[2833 1214]
 [1066 2981]]
Accuracy on test set:    0.7183098591549296
Sensitivity:    0.7365950086483816 	 Specificity:    0.7000247096614777
Precision  : 0.7106078665077473
Area Under Curve:    0.7183098591549295
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5904 - accuracy: 0.6820 - val_loss: 0.5513 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5472 - accuracy: 0.7206 - val_loss: 0.5481 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7310 - val_loss: 0.5412 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7401 - val_loss: 0.5420 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.7479 - val_loss: 0.5472 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7555 - val_loss: 0.5432 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7636 - val_loss: 0.5446 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4731 - accuracy: 0.7741 - val_loss: 0.5504 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4596 - accuracy: 0.7824 - val_loss: 0.5522 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4458 - accuracy: 0.7905 - val_loss: 0.5591 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4321 - accuracy: 0.7997
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4322 - accuracy: 0.7996 - val_loss: 0.5653 - val_accuracy: 0.7175 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.45101766471369026
Confusion Matrix :
 [[3155  892]
 [1341 2706]]
Accuracy on test set:    0.7241166296021745
Sensitivity:    0.6686434395848777 	 Specificity:    0.7795898196194712
Precision  : 0.7520844913841023
Area Under Curve:    0.7241166296021745
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5937 - accuracy: 0.6804 - val_loss: 0.5549 - val_accuracy: 0.7200 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5517 - accuracy: 0.7183 - val_loss: 0.5501 - val_accuracy: 0.7208 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5377 - accuracy: 0.7283 - val_loss: 0.5465 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5265 - accuracy: 0.7358 - val_loss: 0.5509 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5162 - accuracy: 0.7427 - val_loss: 0.5478 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.7508 - val_loss: 0.5525 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.7592 - val_loss: 0.5493 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.7684 - val_loss: 0.5547 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4710 - accuracy: 0.7765 - val_loss: 0.5576 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4586 - accuracy: 0.7846
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4588 - accuracy: 0.7843 - val_loss: 0.5585 - val_accuracy: 0.7205 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.48691122415328664
Confusion Matrix :
 [[3110  937]
 [1142 2905]]
Accuracy on test set:    0.7431430689399555
Sensitivity:    0.7178156659253768 	 Specificity:    0.7684704719545342
Precision  : 0.7561166059344092
Area Under Curve:    0.7431430689399555
(8094, 2560) (8094,)
Mean MCC = 0.4294 + 0.0234 and Mean AUC = 0.7142 + 0.0117
Mean Sensitivity = 0.7254 + 0.0274 and Mean Specificity = 0.7030 + 0.0408 and Mean Accuracy = 0.7142 + 0.0117
Mean Precision = 0.7109 + 0.0234





Seed   : 471138

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5816 - accuracy: 0.6898 - val_loss: 0.5613 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5407 - accuracy: 0.7257 - val_loss: 0.5557 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5258 - accuracy: 0.7369 - val_loss: 0.5603 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5148 - accuracy: 0.7444 - val_loss: 0.5561 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7532 - val_loss: 0.5581 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.7592 - val_loss: 0.5581 - val_accuracy: 0.7086 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4817 - accuracy: 0.7679 - val_loss: 0.5706 - val_accuracy: 0.7039 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4682 - accuracy: 0.7753 - val_loss: 0.5635 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4558 - accuracy: 0.7834
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4559 - accuracy: 0.7836 - val_loss: 0.5677 - val_accuracy: 0.7089 - lr: 0.0010
253/253 [==============================] - 0s 912us/step
Independent Testing Matthews Correlation:  0.41302408564044196
Confusion Matrix :
 [[2937 1111]
 [1266 2781]]
Accuracy on test set:    0.7063619518221124
Sensitivity:    0.687175685693106 	 Specificity:    0.7255434782608695
Precision  : 0.7145426515930113
Area Under Curve:    0.7063595819769879
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5861 - accuracy: 0.6866 - val_loss: 0.5593 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5429 - accuracy: 0.7259 - val_loss: 0.5547 - val_accuracy: 0.7124 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7349 - val_loss: 0.5512 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5149 - accuracy: 0.7444 - val_loss: 0.5556 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5040 - accuracy: 0.7523 - val_loss: 0.5479 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4927 - accuracy: 0.7586 - val_loss: 0.5552 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 7/400
243/257 [===========================>..] - ETA: 0s - loss: 0.4798 - accuracy: 0.7678
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4796 - accuracy: 0.7680 - val_loss: 0.5584 - val_accuracy: 0.7121 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4189217047642262
Confusion Matrix :
 [[2771 1277]
 [1077 2970]]
Accuracy on test set:    0.7092032118591723
Sensitivity:    0.7338769458858414 	 Specificity:    0.6845355731225297
Precision  : 0.6993171650576878
Area Under Curve:    0.7092062595041856
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5860 - accuracy: 0.6865 - val_loss: 0.5590 - val_accuracy: 0.7104 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7228 - val_loss: 0.5477 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7340 - val_loss: 0.5459 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.7402 - val_loss: 0.5461 - val_accuracy: 0.7168 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.7485 - val_loss: 0.5503 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7584 - val_loss: 0.5498 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.7667 - val_loss: 0.5497 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.7757 - val_loss: 0.5508 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4574 - accuracy: 0.7829 - val_loss: 0.5553 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4432 - accuracy: 0.7928 - val_loss: 0.5623 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4297 - accuracy: 0.8005 - val_loss: 0.5670 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4178 - accuracy: 0.8077 - val_loss: 0.5708 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4053 - accuracy: 0.8143 - val_loss: 0.5839 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3947 - accuracy: 0.8213 - val_loss: 0.5886 - val_accuracy: 0.7120 - lr: 0.0010
Epoch 15/400
257/257 [==============================] - 1s 4ms/step - loss: 0.3807 - accuracy: 0.8293 - val_loss: 0.5979 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 16/400
244/257 [===========================>..] - ETA: 0s - loss: 0.3699 - accuracy: 0.8340
Epoch 16: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3714 - accuracy: 0.8334 - val_loss: 0.5984 - val_accuracy: 0.7127 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4063369882960761
Confusion Matrix :
 [[2769 1278]
 [1126 2922]]
Accuracy on test set:    0.7030265596046943
Sensitivity:    0.7218379446640316 	 Specificity:    0.6842105263157895
Precision  : 0.6957142857142857
Area Under Curve:    0.7030242354899106
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5881 - accuracy: 0.6837 - val_loss: 0.5513 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.7221 - val_loss: 0.5453 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5291 - accuracy: 0.7331 - val_loss: 0.5406 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7403 - val_loss: 0.5426 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7497 - val_loss: 0.5445 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4957 - accuracy: 0.7566 - val_loss: 0.5443 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7639 - val_loss: 0.5496 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4739 - accuracy: 0.7713
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7713 - val_loss: 0.5593 - val_accuracy: 0.7172 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4403912782503608
Confusion Matrix :
 [[2543 1504]
 [ 789 3259]]
Accuracy on test set:    0.7167387276096355
Sensitivity:    0.8050889328063241 	 Specificity:    0.6283666913763282
Precision  : 0.684232626495906
Area Under Curve:    0.7167278120913261
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5899 - accuracy: 0.6804 - val_loss: 0.5491 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7198 - val_loss: 0.5393 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7326 - val_loss: 0.5339 - val_accuracy: 0.7279 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5198 - accuracy: 0.7396 - val_loss: 0.5344 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5094 - accuracy: 0.7477 - val_loss: 0.5332 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4983 - accuracy: 0.7568 - val_loss: 0.5474 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7638 - val_loss: 0.5396 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4733 - accuracy: 0.7751
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4737 - accuracy: 0.7752 - val_loss: 0.5376 - val_accuracy: 0.7235 - lr: 0.0010
253/253 [==============================] - 0s 945us/step
Independent Testing Matthews Correlation:  0.42056646293092964
Confusion Matrix :
 [[2887 1160]
 [1185 2862]]
Accuracy on test set:    0.7102792191746973
Sensitivity:    0.7071905114899926 	 Specificity:    0.713367926859402
Precision  : 0.7115862754848334
Area Under Curve:    0.7102792191746973
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5898 - accuracy: 0.6811 - val_loss: 0.5418 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7215 - val_loss: 0.5396 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7355 - val_loss: 0.5358 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5154 - accuracy: 0.7447 - val_loss: 0.5339 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.7514 - val_loss: 0.5381 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7599 - val_loss: 0.5353 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.7684 - val_loss: 0.5366 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4676 - accuracy: 0.7769 - val_loss: 0.5364 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 9/400
254/257 [============================>.] - ETA: 0s - loss: 0.4557 - accuracy: 0.7859
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4560 - accuracy: 0.7859 - val_loss: 0.5456 - val_accuracy: 0.7252 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4167056704672388
Confusion Matrix :
 [[2822 1225]
 [1136 2911]]
Accuracy on test set:    0.7083024462564863
Sensitivity:    0.7192982456140351 	 Specificity:    0.6973066468989375
Precision  : 0.7038201160541586
Area Under Curve:    0.7083024462564862
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5908 - accuracy: 0.6791 - val_loss: 0.5475 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7218 - val_loss: 0.5369 - val_accuracy: 0.7289 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7328 - val_loss: 0.5339 - val_accuracy: 0.7322 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5204 - accuracy: 0.7378 - val_loss: 0.5371 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7477 - val_loss: 0.5347 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4989 - accuracy: 0.7524 - val_loss: 0.5343 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.7620 - val_loss: 0.5359 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 8/400
253/257 [============================>.] - ETA: 0s - loss: 0.4737 - accuracy: 0.7719
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.7719 - val_loss: 0.5399 - val_accuracy: 0.7282 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.44151545424429767
Confusion Matrix :
 [[2802 1245]
 [1018 3029]]
Accuracy on test set:    0.7204101803805288
Sensitivity:    0.7484556461576476 	 Specificity:    0.69236471460341
Precision  : 0.7087037903603182
Area Under Curve:    0.7204101803805288
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5866 - accuracy: 0.6851 - val_loss: 0.5442 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7216 - val_loss: 0.5418 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7344 - val_loss: 0.5381 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.7425 - val_loss: 0.5335 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7504 - val_loss: 0.5341 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.7583 - val_loss: 0.5392 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7671 - val_loss: 0.5395 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4693 - accuracy: 0.7765 - val_loss: 0.5421 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4566 - accuracy: 0.7830 - val_loss: 0.5511 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - ETA: 0s - loss: 0.4453 - accuracy: 0.7932
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4453 - accuracy: 0.7932 - val_loss: 0.5526 - val_accuracy: 0.7202 - lr: 0.0010
253/253 [==============================] - 0s 772us/step
Independent Testing Matthews Correlation:  0.4348068320258003
Confusion Matrix :
 [[2771 1276]
 [1015 3032]]
Accuracy on test set:    0.7169508277736595
Sensitivity:    0.7491969360019768 	 Specificity:    0.6847047195453422
Precision  : 0.7038068709377902
Area Under Curve:    0.7169508277736595
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5893 - accuracy: 0.6830 - val_loss: 0.5477 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7221 - val_loss: 0.5422 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5324 - accuracy: 0.7307 - val_loss: 0.5401 - val_accuracy: 0.7256 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.7396 - val_loss: 0.5387 - val_accuracy: 0.7218 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5105 - accuracy: 0.7474 - val_loss: 0.5419 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7551 - val_loss: 0.5412 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4891 - accuracy: 0.7619 - val_loss: 0.5450 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4764 - accuracy: 0.7725
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4764 - accuracy: 0.7725 - val_loss: 0.5482 - val_accuracy: 0.7256 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.459606987024598
Confusion Matrix :
 [[2858 1189]
 [1000 3047]]
Accuracy on test set:    0.7295527551272547
Sensitivity:    0.7529033852236224 	 Specificity:    0.7062021250308871
Precision  : 0.7193106704438149
Area Under Curve:    0.7295527551272548
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5932 - accuracy: 0.6799 - val_loss: 0.5591 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7195 - val_loss: 0.5528 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5350 - accuracy: 0.7309 - val_loss: 0.5485 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5235 - accuracy: 0.7389 - val_loss: 0.5485 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.7455 - val_loss: 0.5536 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5023 - accuracy: 0.7541 - val_loss: 0.5507 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.7614 - val_loss: 0.5549 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 8/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4764 - accuracy: 0.7719
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.7716 - val_loss: 0.5573 - val_accuracy: 0.7131 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4786925762032655
Confusion Matrix :
 [[3108  939]
 [1174 2873]]
Accuracy on test set:    0.7389424264887571
Sensitivity:    0.7099085742525327 	 Specificity:    0.7679762787249814
Precision  : 0.7536726128016789
Area Under Curve:    0.7389424264887572
(8094, 2560) (8094,)
Mean MCC = 0.4331 + 0.0216 and Mean AUC = 0.7160 + 0.0106
Mean Sensitivity = 0.7335 + 0.0312 and Mean Specificity = 0.6985 + 0.0337 and Mean Accuracy = 0.7160 + 0.0106
Mean Precision = 0.7095 + 0.0175





Seed   : 314052
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5841 - accuracy: 0.6879 - val_loss: 0.5594 - val_accuracy: 0.7095 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5420 - accuracy: 0.7261 - val_loss: 0.5521 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5250 - accuracy: 0.7362 - val_loss: 0.5509 - val_accuracy: 0.7101 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7435 - val_loss: 0.5488 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5040 - accuracy: 0.7527 - val_loss: 0.5581 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7593 - val_loss: 0.5522 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.7680 - val_loss: 0.5543 - val_accuracy: 0.7127 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4714 - accuracy: 0.7734 - val_loss: 0.5565 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4591 - accuracy: 0.7823 - val_loss: 0.5625 - val_accuracy: 0.7145 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4507 - accuracy: 0.7883 - val_loss: 0.5718 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4388 - accuracy: 0.7942 - val_loss: 0.5815 - val_accuracy: 0.7017 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4259 - accuracy: 0.8013 - val_loss: 0.5767 - val_accuracy: 0.7078 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4132 - accuracy: 0.8102 - val_loss: 0.5843 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - ETA: 0s - loss: 0.4047 - accuracy: 0.8152
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4047 - accuracy: 0.8152 - val_loss: 0.5981 - val_accuracy: 0.7068 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4011886624105524
Confusion Matrix :
 [[2687 1361]
 [1067 2980]]
Accuracy on test set:    0.7000617665225448
Sensitivity:    0.7363479120336052 	 Specificity:    0.6637845849802372
Precision  : 0.6864777700990555
Area Under Curve:    0.7000662485069211
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5863 - accuracy: 0.6844 - val_loss: 0.5611 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7242 - val_loss: 0.5541 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5277 - accuracy: 0.7335 - val_loss: 0.5544 - val_accuracy: 0.7094 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5156 - accuracy: 0.7425 - val_loss: 0.5554 - val_accuracy: 0.7082 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.7494 - val_loss: 0.5527 - val_accuracy: 0.7109 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.7581 - val_loss: 0.5538 - val_accuracy: 0.7108 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7657 - val_loss: 0.5551 - val_accuracy: 0.7161 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4723 - accuracy: 0.7728 - val_loss: 0.5620 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4595 - accuracy: 0.7811 - val_loss: 0.5692 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4467 - accuracy: 0.7887 - val_loss: 0.5652 - val_accuracy: 0.7134 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4344 - accuracy: 0.7972 - val_loss: 0.5782 - val_accuracy: 0.7119 - lr: 0.0010
Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4208 - accuracy: 0.8050
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4208 - accuracy: 0.8053 - val_loss: 0.5807 - val_accuracy: 0.7105 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4116637472017174
Confusion Matrix :
 [[2741 1307]
 [1077 2970]]
Accuracy on test set:    0.7054972205064854
Sensitivity:    0.7338769458858414 	 Specificity:    0.6771245059288538
Precision  : 0.6944119710077157
Area Under Curve:    0.7055007259073476
(8095, 2560) (8095,)

Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5866 - accuracy: 0.6850 - val_loss: 0.5521 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5420 - accuracy: 0.7238 - val_loss: 0.5439 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5257 - accuracy: 0.7360 - val_loss: 0.5387 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5141 - accuracy: 0.7442 - val_loss: 0.5402 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.7502 - val_loss: 0.5429 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4911 - accuracy: 0.7599 - val_loss: 0.5381 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4783 - accuracy: 0.7690 - val_loss: 0.5413 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4649 - accuracy: 0.7782 - val_loss: 0.5438 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4522 - accuracy: 0.7870 - val_loss: 0.5476 - val_accuracy: 0.7185 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4373 - accuracy: 0.7965 - val_loss: 0.5587 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4259 - accuracy: 0.8042 - val_loss: 0.5567 - val_accuracy: 0.7181 - lr: 0.0010
Epoch 12/400
250/257 [============================>.] - ETA: 0s - loss: 0.4118 - accuracy: 0.8128
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4130 - accuracy: 0.8122 - val_loss: 0.5556 - val_accuracy: 0.7229 - lr: 0.0010
253/253 [==============================] - 0s 832us/step
Independent Testing Matthews Correlation:  0.40737295486183217
Confusion Matrix :
 [[2765 1282]
 [1118 2930]]
Accuracy on test set:    0.7035206917850525
Sensitivity:    0.7238142292490118 	 Specificity:    0.683222139856684
Precision  : 0.6956315289648622
Area Under Curve:    0.7035181845528479
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5890 - accuracy: 0.6841 - val_loss: 0.5539 - val_accuracy: 0.7170 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7213 - val_loss: 0.5397 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7322 - val_loss: 0.5398 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7393 - val_loss: 0.5355 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5094 - accuracy: 0.7464 - val_loss: 0.5424 - val_accuracy: 0.7216 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.7561 - val_loss: 0.5375 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.7643 - val_loss: 0.5397 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4732 - accuracy: 0.7727 - val_loss: 0.5430 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4618 - accuracy: 0.7809 - val_loss: 0.5436 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4478 - accuracy: 0.7890 - val_loss: 0.5540 - val_accuracy: 0.7148 - lr: 0.0010
Epoch 11/400
255/257 [============================>.] - ETA: 0s - loss: 0.4363 - accuracy: 0.7960
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4363 - accuracy: 0.7961 - val_loss: 0.5569 - val_accuracy: 0.7215 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42168441057498135
Confusion Matrix :
 [[2912 1135]
 [1206 2842]]
Accuracy on test set:    0.7108091414453366
Sensitivity:    0.7020750988142292 	 Specificity:    0.7195453422288115
Precision  : 0.7146090017601207
Area Under Curve:    0.7108102205215203
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5905 - accuracy: 0.6810 - val_loss: 0.5504 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7230 - val_loss: 0.5449 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7313 - val_loss: 0.5397 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5179 - accuracy: 0.7409 - val_loss: 0.5401 - val_accuracy: 0.7271 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7488 - val_loss: 0.5397 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4958 - accuracy: 0.7570 - val_loss: 0.5451 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7623 - val_loss: 0.5455 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.7730 - val_loss: 0.5507 - val_accuracy: 0.7207 - lr: 0.0010
Epoch 9/400
241/257 [===========================>..] - ETA: 0s - loss: 0.4613 - accuracy: 0.7800
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4617 - accuracy: 0.7802 - val_loss: 0.5522 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.427482898808637
Confusion Matrix :
 [[2899 1148]
 [1169 2878]]
Accuracy on test set:    0.7137385717815666
Sensitivity:    0.7111440573264146 	 Specificity:    0.7163330862367185
Precision  : 0.7148534525583706
Area Under Curve:    0.7137385717815665
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5878 - accuracy: 0.6844 - val_loss: 0.5478 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7231 - val_loss: 0.5400 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5298 - accuracy: 0.7347 - val_loss: 0.5392 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7404 - val_loss: 0.5401 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7482 - val_loss: 0.5395 - val_accuracy: 0.7281 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.7564 - val_loss: 0.5398 - val_accuracy: 0.7235 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4862 - accuracy: 0.7666 - val_loss: 0.5493 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4750 - accuracy: 0.7713 - val_loss: 0.5443 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.7785 - val_loss: 0.5523 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4528 - accuracy: 0.7864 - val_loss: 0.5497 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4397 - accuracy: 0.7937 - val_loss: 0.5518 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4279 - accuracy: 0.8006 - val_loss: 0.5622 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4179 - accuracy: 0.8068 - val_loss: 0.5644 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 14/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4050 - accuracy: 0.8143 - val_loss: 0.5801 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 15/400
255/257 [============================>.] - ETA: 0s - loss: 0.3943 - accuracy: 0.8193
Epoch 15: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.3942 - accuracy: 0.8195 - val_loss: 0.5856 - val_accuracy: 0.7212 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4277919474884897
Confusion Matrix :
 [[2853 1194]
 [1122 2925]]
Accuracy on test set:    0.7138621200889548
Sensitivity:    0.7227575982209044 	 Specificity:    0.7049666419570052
Precision  : 0.7101238164603059
Area Under Curve:    0.7138621200889548
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5910 - accuracy: 0.6811 - val_loss: 0.5490 - val_accuracy: 0.7249 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7222 - val_loss: 0.5409 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7337 - val_loss: 0.5390 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7394 - val_loss: 0.5351 - val_accuracy: 0.7275 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.7473 - val_loss: 0.5419 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4985 - accuracy: 0.7559 - val_loss: 0.5385 - val_accuracy: 0.7303 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4871 - accuracy: 0.7624 - val_loss: 0.5427 - val_accuracy: 0.7261 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7704 - val_loss: 0.5404 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4634 - accuracy: 0.7797 - val_loss: 0.5478 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4506 - accuracy: 0.7874 - val_loss: 0.5496 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 11/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4371 - accuracy: 0.7961
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4374 - accuracy: 0.7959 - val_loss: 0.5551 - val_accuracy: 0.7230 - lr: 0.0010
253/253 [==============================] - 0s 773us/step
Independent Testing Matthews Correlation:  0.4152900149094802
Confusion Matrix :
 [[2806 1241]
 [1126 2921]]
Accuracy on test set:    0.7075611564121571
Sensitivity:    0.7217692117617989 	 Specificity:    0.6933531010625155
Precision  : 0.7018260451705911
Area Under Curve:    0.7075611564121572
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5835 - accuracy: 0.6876 - val_loss: 0.5464 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7236 - val_loss: 0.5429 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5285 - accuracy: 0.7342 - val_loss: 0.5403 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.7416 - val_loss: 0.5381 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7485 - val_loss: 0.5396 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.7563 - val_loss: 0.5386 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.7648 - val_loss: 0.5414 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4743 - accuracy: 0.7727 - val_loss: 0.5427 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4622 - accuracy: 0.7796 - val_loss: 0.5493 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4502 - accuracy: 0.7889 - val_loss: 0.5506 - val_accuracy: 0.7172 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4388 - accuracy: 0.7963
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4388 - accuracy: 0.7965 - val_loss: 0.5591 - val_accuracy: 0.7220 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42578905142553686
Confusion Matrix :
 [[2810 1237]
 [1088 2959]]
Accuracy on test set:    0.712750185322461
Sensitivity:    0.7311588831233012 	 Specificity:    0.694341487521621
Precision  : 0.7051954242135366
Area Under Curve:    0.7127501853224611
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5892 - accuracy: 0.6826 - val_loss: 0.5482 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5465 - accuracy: 0.7209 - val_loss: 0.5526 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7328 - val_loss: 0.5397 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5204 - accuracy: 0.7391 - val_loss: 0.5422 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.7498 - val_loss: 0.5406 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7580 - val_loss: 0.5428 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.7669 - val_loss: 0.5431 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 8/400
251/257 [============================>.] - ETA: 0s - loss: 0.4701 - accuracy: 0.7764
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.7763 - val_loss: 0.5578 - val_accuracy: 0.7191 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.46288961380240223
Confusion Matrix :
 [[2791 1256]
 [ 924 3123]]
Accuracy on test set:    0.7306646898937484
Sensitivity:    0.7716827279466272 	 Specificity:    0.6896466518408698
Precision  : 0.7131765243206212
Area Under Curve:    0.7306646898937484
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5937 - accuracy: 0.6793 - val_loss: 0.5528 - val_accuracy: 0.7153 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5525 - accuracy: 0.7162 - val_loss: 0.5438 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5390 - accuracy: 0.7285 - val_loss: 0.5418 - val_accuracy: 0.7242 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.7358 - val_loss: 0.5501 - val_accuracy: 0.7146 - lr: 0.0010

Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7431 - val_loss: 0.5428 - val_accuracy: 0.7209 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7509 - val_loss: 0.5445 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 7/400
249/257 [============================>.] - ETA: 0s - loss: 0.4957 - accuracy: 0.7572
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4954 - accuracy: 0.7575 - val_loss: 0.5465 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4773286677586547
Confusion Matrix :
 [[3155  892]
 [1230 2817]]
Accuracy on test set:    0.7378304917222634
Sensitivity:    0.6960711638250556 	 Specificity:    0.7795898196194712
Precision  : 0.7595039094095444
Area Under Curve:    0.7378304917222634
(8094, 2560) (8094,)
Mean MCC = 0.4278 + 0.0230 and Mean AUC = 0.7136 + 0.0113
Mean Sensitivity = 0.7251 + 0.0200 and Mean Specificity = 0.7022 + 0.0304 and Mean Accuracy = 0.7136 + 0.0113
Mean Precision = 0.7096 + 0.0190





Seed   : 37438
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5820 - accuracy: 0.6878 - val_loss: 0.5602 - val_accuracy: 0.7047 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5401 - accuracy: 0.7270 - val_loss: 0.5520 - val_accuracy: 0.7087 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5244 - accuracy: 0.7369 - val_loss: 0.5512 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5125 - accuracy: 0.7464 - val_loss: 0.5496 - val_accuracy: 0.7075 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5012 - accuracy: 0.7540 - val_loss: 0.5541 - val_accuracy: 0.7058 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4897 - accuracy: 0.7631 - val_loss: 0.5607 - val_accuracy: 0.7064 - lr: 0.0010
Epoch 7/400
255/257 [============================>.] - ETA: 0s - loss: 0.4788 - accuracy: 0.7691
Epoch 7: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4788 - accuracy: 0.7692 - val_loss: 0.5581 - val_accuracy: 0.7079 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41617842897365265
Confusion Matrix :
 [[2964 1084]
 [1281 2766]]
Accuracy on test set:    0.7078443483631871
Sensitivity:    0.6834692364714603 	 Specificity:    0.7322134387351779
Precision  : 0.7184415584415584
Area Under Curve:    0.707841337603319
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5901 - accuracy: 0.6817 - val_loss: 0.5604 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7224 - val_loss: 0.5530 - val_accuracy: 0.7076 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5313 - accuracy: 0.7331 - val_loss: 0.5538 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7410 - val_loss: 0.5501 - val_accuracy: 0.7069 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7475 - val_loss: 0.5630 - val_accuracy: 0.7051 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.7579 - val_loss: 0.5588 - val_accuracy: 0.7080 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.7657 - val_loss: 0.5619 - val_accuracy: 0.7049 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4726 - accuracy: 0.7716 - val_loss: 0.5637 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4594 - accuracy: 0.7807 - val_loss: 0.5818 - val_accuracy: 0.7045 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4483 - accuracy: 0.7867 - val_loss: 0.5762 - val_accuracy: 0.7040 - lr: 0.0010
Epoch 11/400
247/257 [===========================>..] - ETA: 0s - loss: 0.4350 - accuracy: 0.7968
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4351 - accuracy: 0.7968 - val_loss: 0.5869 - val_accuracy: 0.7073 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41791082244429345
Confusion Matrix :
 [[2683 1365]
 [ 998 3049]]
Accuracy on test set:    0.7080914144533663
Sensitivity:    0.7533975784531752 	 Specificity:    0.6627964426877471
Precision  : 0.6907566832804712
Area Under Curve:    0.7080970105704611
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5863 - accuracy: 0.6836 - val_loss: 0.5533 - val_accuracy: 0.7117 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7227 - val_loss: 0.5509 - val_accuracy: 0.7138 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7334 - val_loss: 0.5429 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.7419 - val_loss: 0.5424 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.7516 - val_loss: 0.5466 - val_accuracy: 0.7142 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4924 - accuracy: 0.7599 - val_loss: 0.5512 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.7664 - val_loss: 0.5482 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 8/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4680 - accuracy: 0.7764
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4675 - accuracy: 0.7770 - val_loss: 0.5583 - val_accuracy: 0.7145 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42951508654329223
Confusion Matrix :
 [[2639 1408]
 [ 914 3134]]
Accuracy on test set:    0.7131562693020383
Sensitivity:    0.7742094861660079 	 Specificity:    0.6520879663948604
Precision  : 0.6900044033465433
Area Under Curve:    0.7131487262804342
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5871 - accuracy: 0.6834 - val_loss: 0.5573 - val_accuracy: 0.7039 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7230 - val_loss: 0.5455 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7338 - val_loss: 0.5430 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.7421 - val_loss: 0.5414 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5031 - accuracy: 0.7493 - val_loss: 0.5397 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.7597 - val_loss: 0.5416 - val_accuracy: 0.7175 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4783 - accuracy: 0.7673 - val_loss: 0.5497 - val_accuracy: 0.7132 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4654 - accuracy: 0.7769 - val_loss: 0.5542 - val_accuracy: 0.7165 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4517 - accuracy: 0.7866
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4519 - accuracy: 0.7865 - val_loss: 0.5538 - val_accuracy: 0.7137 - lr: 0.0010
253/253 [==============================] - 0s 944us/step
Independent Testing Matthews Correlation:  0.435158816548492
Confusion Matrix :
 [[2788 1259]
 [1030 3018]]
Accuracy on test set:    0.7172328597899938
Sensitivity:    0.7455533596837944 	 Specificity:    0.6889053619965406
Precision  : 0.7056347907411737
Area Under Curve:    0.7172293608401675
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5861 - accuracy: 0.6859 - val_loss: 0.5494 - val_accuracy: 0.7197 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7204 - val_loss: 0.5444 - val_accuracy: 0.7222 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7316 - val_loss: 0.5435 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.7398 - val_loss: 0.5443 - val_accuracy: 0.7198 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7496 - val_loss: 0.5431 - val_accuracy: 0.7224 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7544 - val_loss: 0.5415 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.7631 - val_loss: 0.5433 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 8/400
250/257 [============================>.] - ETA: 0s - loss: 0.4755 - accuracy: 0.7699
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4759 - accuracy: 0.7700 - val_loss: 0.5466 - val_accuracy: 0.7196 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4281511972212079
Confusion Matrix :
 [[3002 1045]
 [1272 2775]]
Accuracy on test set:    0.7137385717815666
Sensitivity:    0.6856931060044478 	 Specificity:    0.7417840375586855
Precision  : 0.7264397905759162
Area Under Curve:    0.7137385717815667
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5867 - accuracy: 0.6861 - val_loss: 0.5519 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7229 - val_loss: 0.5435 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7334 - val_loss: 0.5402 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7423 - val_loss: 0.5416 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5064 - accuracy: 0.7506 - val_loss: 0.5454 - val_accuracy: 0.7282 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.7571 - val_loss: 0.5433 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.7664 - val_loss: 0.5432 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.7756 - val_loss: 0.5466 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4571 - accuracy: 0.7855 - val_loss: 0.5474 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4451 - accuracy: 0.7917 - val_loss: 0.5481 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4317 - accuracy: 0.8001 - val_loss: 0.5540 - val_accuracy: 0.7245 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4175 - accuracy: 0.8075 - val_loss: 0.5635 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 13/400
250/257 [============================>.] - ETA: 0s - loss: 0.4067 - accuracy: 0.8137
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4071 - accuracy: 0.8135 - val_loss: 0.5637 - val_accuracy: 0.7245 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4158782796023252
Confusion Matrix :
 [[2848 1199]
 [1165 2882]]
Accuracy on test set:    0.7079318013343218
Sensitivity:    0.7121324437855201 	 Specificity:    0.7037311588831233
Precision  : 0.706199460916442
Area Under Curve:    0.7079318013343218
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5866 - accuracy: 0.6863 - val_loss: 0.5500 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5459 - accuracy: 0.7203 - val_loss: 0.5476 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7326 - val_loss: 0.5427 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.7412 - val_loss: 0.5400 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7497 - val_loss: 0.5423 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4955 - accuracy: 0.7586 - val_loss: 0.5472 - val_accuracy: 0.7174 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.7652 - val_loss: 0.5473 - val_accuracy: 0.7186 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - ETA: 0s - loss: 0.4700 - accuracy: 0.7740
Epoch 8: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4700 - accuracy: 0.7740 - val_loss: 0.5511 - val_accuracy: 0.7216 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4319075901533937
Confusion Matrix :
 [[2831 1216]
 [1084 2963]]
Accuracy on test set:    0.7158388930071659
Sensitivity:    0.7321472695824067 	 Specificity:    0.6995305164319249
Precision  : 0.7090212969609955
Area Under Curve:    0.7158388930071657
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5998 - accuracy: 0.6740 - val_loss: 0.5546 - val_accuracy: 0.7213 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7183 - val_loss: 0.5481 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5342 - accuracy: 0.7318 - val_loss: 0.5419 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5231 - accuracy: 0.7375 - val_loss: 0.5419 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5115 - accuracy: 0.7484 - val_loss: 0.5434 - val_accuracy: 0.7240 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5002 - accuracy: 0.7552 - val_loss: 0.5445 - val_accuracy: 0.7246 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4891 - accuracy: 0.7621 - val_loss: 0.5486 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4752 - accuracy: 0.7702 - val_loss: 0.5509 - val_accuracy: 0.7204 - lr: 0.0010
Epoch 9/400
253/257 [============================>.] - ETA: 0s - loss: 0.4631 - accuracy: 0.7795
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.

257/257 [==============================] - 1s 4ms/step - loss: 0.4630 - accuracy: 0.7796 - val_loss: 0.5561 - val_accuracy: 0.7194 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4215378179004642
Confusion Matrix :
 [[2944 1103]
 [1239 2808]]
Accuracy on test set:    0.7106498640968619
Sensitivity:    0.6938472942920682 	 Specificity:    0.7274524339016556
Precision  : 0.7179749424699565
Area Under Curve:    0.7106498640968618
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5919 - accuracy: 0.6821 - val_loss: 0.5556 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5491 - accuracy: 0.7200 - val_loss: 0.5480 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5332 - accuracy: 0.7301 - val_loss: 0.5476 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7403 - val_loss: 0.5459 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7478 - val_loss: 0.5460 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.7577 - val_loss: 0.5461 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4862 - accuracy: 0.7643 - val_loss: 0.5514 - val_accuracy: 0.7159 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4730 - accuracy: 0.7739 - val_loss: 0.5555 - val_accuracy: 0.7112 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4605 - accuracy: 0.7817 - val_loss: 0.5643 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 10/400
253/257 [============================>.] - ETA: 0s - loss: 0.4457 - accuracy: 0.7904
Epoch 10: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4458 - accuracy: 0.7903 - val_loss: 0.5657 - val_accuracy: 0.7165 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4576193184739163
Confusion Matrix :
 [[2883 1164]
 [1032 3015]]
Accuracy on test set:    0.7286879169755375
Sensitivity:    0.7449962935507783 	 Specificity:    0.7123795404002965
Precision  : 0.7214644651830582
Area Under Curve:    0.7286879169755374
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 3s 5ms/step - loss: 0.5946 - accuracy: 0.6800 - val_loss: 0.5551 - val_accuracy: 0.7191 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5523 - accuracy: 0.7179 - val_loss: 0.5480 - val_accuracy: 0.7229 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5369 - accuracy: 0.7281 - val_loss: 0.5476 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5249 - accuracy: 0.7369 - val_loss: 0.5464 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.7446 - val_loss: 0.5455 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.7518 - val_loss: 0.5486 - val_accuracy: 0.7205 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.7613 - val_loss: 0.5531 - val_accuracy: 0.7202 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4817 - accuracy: 0.7670 - val_loss: 0.5500 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 9/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4692 - accuracy: 0.7761
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4687 - accuracy: 0.7763 - val_loss: 0.5552 - val_accuracy: 0.7207 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.47475237896390743
Confusion Matrix :
 [[3157  890]
 [1243 2804]]
Accuracy on test set:    0.7364714603409933
Sensitivity:    0.6928589078329627 	 Specificity:    0.780084012849024
Precision  : 0.7590687601515972
Area Under Curve:    0.7364714603409934
(8094, 2560) (8094,)
Mean MCC = 0.4329 + 0.0182 and Mean AUC = 0.7160 + 0.0090
Mean Sensitivity = 0.7218 + 0.0307 and Mean Specificity = 0.7101 + 0.0359 and Mean Accuracy = 0.7160 + 0.0090
Mean Precision = 0.7145 + 0.0188





Seed   : 784532
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5861 - accuracy: 0.6861 - val_loss: 0.5641 - val_accuracy: 0.7024 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7247 - val_loss: 0.5562 - val_accuracy: 0.7100 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5258 - accuracy: 0.7365 - val_loss: 0.5567 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7452 - val_loss: 0.5571 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5023 - accuracy: 0.7523 - val_loss: 0.5518 - val_accuracy: 0.7093 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.7596 - val_loss: 0.5598 - val_accuracy: 0.7079 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.7704 - val_loss: 0.5603 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4670 - accuracy: 0.7771 - val_loss: 0.5676 - val_accuracy: 0.7113 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4540 - accuracy: 0.7853 - val_loss: 0.5668 - val_accuracy: 0.7060 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4415 - accuracy: 0.7959 - val_loss: 0.5727 - val_accuracy: 0.7065 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4281 - accuracy: 0.8028 - val_loss: 0.5858 - val_accuracy: 0.7028 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4163 - accuracy: 0.8098 - val_loss: 0.5853 - val_accuracy: 0.7053 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - ETA: 0s - loss: 0.4029 - accuracy: 0.8168
Epoch 13: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4029 - accuracy: 0.8168 - val_loss: 0.5945 - val_accuracy: 0.7060 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.3973578520313062
Confusion Matrix :
 [[2732 1316]
 [1125 2922]]
Accuracy on test set:    0.6984558369363805
Sensitivity:    0.7220163083765753 	 Specificity:    0.674901185770751
Precision  : 0.6894761680037753
Area Under Curve:    0.6984587470736632
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5896 - accuracy: 0.6828 - val_loss: 0.5609 - val_accuracy: 0.7071 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7234 - val_loss: 0.5576 - val_accuracy: 0.7102 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5301 - accuracy: 0.7318 - val_loss: 0.5519 - val_accuracy: 0.7084 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.7398 - val_loss: 0.5522 - val_accuracy: 0.7106 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.7472 - val_loss: 0.5540 - val_accuracy: 0.7090 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.7533 - val_loss: 0.5549 - val_accuracy: 0.7067 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7626 - val_loss: 0.5673 - val_accuracy: 0.7038 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4778 - accuracy: 0.7699 - val_loss: 0.5691 - val_accuracy: 0.7046 - lr: 0.0010
Epoch 9/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4681 - accuracy: 0.7766
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4685 - accuracy: 0.7765 - val_loss: 0.5689 - val_accuracy: 0.7014 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4179220243372039
Confusion Matrix :
 [[2770 1278]
 [1080 2967]]
Accuracy on test set:    0.7087090796788141
Sensitivity:    0.7331356560415122 	 Specificity:    0.6842885375494071
Precision  : 0.6989399293286219
Area Under Curve:    0.7087120967954595
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5849 - accuracy: 0.6872 - val_loss: 0.5515 - val_accuracy: 0.7150 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7234 - val_loss: 0.5493 - val_accuracy: 0.7105 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5302 - accuracy: 0.7324 - val_loss: 0.5470 - val_accuracy: 0.7121 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7417 - val_loss: 0.5471 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7484 - val_loss: 0.5465 - val_accuracy: 0.7149 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.7564 - val_loss: 0.5572 - val_accuracy: 0.7116 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4857 - accuracy: 0.7644 - val_loss: 0.5526 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4729 - accuracy: 0.7734 - val_loss: 0.5552 - val_accuracy: 0.7115 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.7827 - val_loss: 0.5575 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4460 - accuracy: 0.7910 - val_loss: 0.5648 - val_accuracy: 0.7126 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4328 - accuracy: 0.7991 - val_loss: 0.5674 - val_accuracy: 0.7157 - lr: 0.0010
Epoch 12/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4192 - accuracy: 0.8082
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4193 - accuracy: 0.8081 - val_loss: 0.5818 - val_accuracy: 0.7161 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42954571388574025
Confusion Matrix :
 [[2872 1175]
 [1134 2914]]
Accuracy on test set:    0.7147621988882026
Sensitivity:    0.7198616600790514 	 Specificity:    0.7096614776377563
Precision  : 0.7126436781609196
Area Under Curve:    0.7147615688584038
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5840 - accuracy: 0.6873 - val_loss: 0.5490 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5402 - accuracy: 0.7258 - val_loss: 0.5417 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5245 - accuracy: 0.7360 - val_loss: 0.5437 - val_accuracy: 0.7212 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5122 - accuracy: 0.7436 - val_loss: 0.5449 - val_accuracy: 0.7183 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.7538 - val_loss: 0.5427 - val_accuracy: 0.7187 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.7625 - val_loss: 0.5419 - val_accuracy: 0.7220 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4760 - accuracy: 0.7681 - val_loss: 0.5450 - val_accuracy: 0.7196 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4608 - accuracy: 0.7790 - val_loss: 0.5593 - val_accuracy: 0.7189 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4492 - accuracy: 0.7886 - val_loss: 0.5613 - val_accuracy: 0.7182 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4333 - accuracy: 0.7983 - val_loss: 0.5647 - val_accuracy: 0.7164 - lr: 0.0010
Epoch 11/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4202 - accuracy: 0.8071
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4204 - accuracy: 0.8070 - val_loss: 0.5716 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.41115543237555324
Confusion Matrix :
 [[2764 1283]
 [1102 2946]]
Accuracy on test set:    0.705373687461396
Sensitivity:    0.7277667984189723 	 Specificity:    0.6829750432419076
Precision  : 0.6966185859541263
Area Under Curve:    0.70537092083044
(8095, 2560) (8095,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5873 - accuracy: 0.6847 - val_loss: 0.5441 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7224 - val_loss: 0.5370 - val_accuracy: 0.7266 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7330 - val_loss: 0.5418 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5181 - accuracy: 0.7396 - val_loss: 0.5362 - val_accuracy: 0.7319 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.7493 - val_loss: 0.5377 - val_accuracy: 0.7263 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4970 - accuracy: 0.7559 - val_loss: 0.5359 - val_accuracy: 0.7297 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.7651 - val_loss: 0.5414 - val_accuracy: 0.7290 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4743 - accuracy: 0.7726 - val_loss: 0.5462 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 9/400
246/257 [===========================>..] - ETA: 0s - loss: 0.4638 - accuracy: 0.7787
Epoch 9: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4637 - accuracy: 0.7787 - val_loss: 0.5485 - val_accuracy: 0.7242 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4270414768965783
Confusion Matrix :
 [[2854 1193]
 [1126 2921]]
Accuracy on test set:    0.7134914751667902
Sensitivity:    0.7217692117617989 	 Specificity:    0.7052137385717816
Precision  : 0.7100145843461352
Area Under Curve:    0.7134914751667902
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5879 - accuracy: 0.6840 - val_loss: 0.5475 - val_accuracy: 0.7230 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7219 - val_loss: 0.5423 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.7332 - val_loss: 0.5358 - val_accuracy: 0.7285 - lr: 0.0010

Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5130 - accuracy: 0.7446 - val_loss: 0.5371 - val_accuracy: 0.7270 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.7540 - val_loss: 0.5361 - val_accuracy: 0.7277 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.7630 - val_loss: 0.5411 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4731 - accuracy: 0.7720 - val_loss: 0.5410 - val_accuracy: 0.7307 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4587 - accuracy: 0.7812 - val_loss: 0.5462 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4479 - accuracy: 0.7903 - val_loss: 0.5525 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4321 - accuracy: 0.8000 - val_loss: 0.5549 - val_accuracy: 0.7219 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4185 - accuracy: 0.8072 - val_loss: 0.5575 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 12/400
255/257 [============================>.] - ETA: 0s - loss: 0.4057 - accuracy: 0.8152
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4058 - accuracy: 0.8152 - val_loss: 0.5648 - val_accuracy: 0.7197 - lr: 0.0010
253/253 [==============================] - 0s 944us/step
Independent Testing Matthews Correlation:  0.41590610969683633
Confusion Matrix :
 [[2940 1107]
 [1258 2789]]
Accuracy on test set:    0.7078082530269335
Sensitivity:    0.689152458611317 	 Specificity:    0.72646404744255
Precision  : 0.7158624229979466
Area Under Curve:    0.7078082530269335
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5857 - accuracy: 0.6860 - val_loss: 0.5515 - val_accuracy: 0.7163 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5440 - accuracy: 0.7225 - val_loss: 0.5401 - val_accuracy: 0.7251 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7324 - val_loss: 0.5394 - val_accuracy: 0.7237 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5165 - accuracy: 0.7410 - val_loss: 0.5379 - val_accuracy: 0.7233 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7481 - val_loss: 0.5403 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.7572 - val_loss: 0.5388 - val_accuracy: 0.7300 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.7660 - val_loss: 0.5468 - val_accuracy: 0.7252 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4690 - accuracy: 0.7746 - val_loss: 0.5522 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4554 - accuracy: 0.7842 - val_loss: 0.5498 - val_accuracy: 0.7201 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4426 - accuracy: 0.7923 - val_loss: 0.5591 - val_accuracy: 0.7259 - lr: 0.0010
Epoch 11/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4299 - accuracy: 0.8022
Epoch 11: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4302 - accuracy: 0.8017 - val_loss: 0.5611 - val_accuracy: 0.7267 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.42288229401874694
Confusion Matrix :
 [[2835 1212]
 [1124 2923]]
Accuracy on test set:    0.711391153941191
Sensitivity:    0.7222634049913517 	 Specificity:    0.7005189028910304
Precision  : 0.7068923821039903
Area Under Curve:    0.711391153941191
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5942 - accuracy: 0.6808 - val_loss: 0.5477 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5508 - accuracy: 0.7188 - val_loss: 0.5448 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5361 - accuracy: 0.7300 - val_loss: 0.5371 - val_accuracy: 0.7238 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.7370 - val_loss: 0.5358 - val_accuracy: 0.7244 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7451 - val_loss: 0.5372 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5073 - accuracy: 0.7504 - val_loss: 0.5428 - val_accuracy: 0.7215 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.7587 - val_loss: 0.5357 - val_accuracy: 0.7255 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.7637 - val_loss: 0.5425 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4758 - accuracy: 0.7719 - val_loss: 0.5431 - val_accuracy: 0.7264 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4633 - accuracy: 0.7795 - val_loss: 0.5468 - val_accuracy: 0.7241 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4499 - accuracy: 0.7892 - val_loss: 0.5501 - val_accuracy: 0.7260 - lr: 0.0010
Epoch 12/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4389 - accuracy: 0.7948 - val_loss: 0.5615 - val_accuracy: 0.7227 - lr: 0.0010
Epoch 13/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4273 - accuracy: 0.8035 - val_loss: 0.5631 - val_accuracy: 0.7211 - lr: 0.0010
Epoch 14/400
256/257 [============================>.] - ETA: 0s - loss: 0.4177 - accuracy: 0.8080
Epoch 14: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4178 - accuracy: 0.8080 - val_loss: 0.5722 - val_accuracy: 0.7181 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.4255519366609489
Confusion Matrix :
 [[2916 1131]
 [1194 2853]]
Accuracy on test set:    0.712750185322461
Sensitivity:    0.7049666419570052 	 Specificity:    0.720533728687917
Precision  : 0.7161144578313253
Area Under Curve:    0.712750185322461
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 4ms/step - loss: 0.5883 - accuracy: 0.6842 - val_loss: 0.5534 - val_accuracy: 0.7152 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7216 - val_loss: 0.5410 - val_accuracy: 0.7226 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7317 - val_loss: 0.5382 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7403 - val_loss: 0.5370 - val_accuracy: 0.7278 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7491 - val_loss: 0.5391 - val_accuracy: 0.7286 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7554 - val_loss: 0.5417 - val_accuracy: 0.7283 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.7619 - val_loss: 0.5387 - val_accuracy: 0.7299 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4760 - accuracy: 0.7699 - val_loss: 0.5447 - val_accuracy: 0.7293 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4636 - accuracy: 0.7800 - val_loss: 0.5475 - val_accuracy: 0.7268 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4519 - accuracy: 0.7874 - val_loss: 0.5521 - val_accuracy: 0.7253 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4387 - accuracy: 0.7946 - val_loss: 0.5565 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 12/400
248/257 [===========================>..] - ETA: 0s - loss: 0.4292 - accuracy: 0.7991
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4288 - accuracy: 0.7995 - val_loss: 0.5623 - val_accuracy: 0.7223 - lr: 0.0010
253/253 [==============================] - 0s 993us/step
Independent Testing Matthews Correlation:  0.4593041159786855
Confusion Matrix :
 [[3012 1035]
 [1154 2893]]
Accuracy on test set:    0.7295527551272547
Sensitivity:    0.7148505065480603 	 Specificity:    0.7442550037064493
Precision  : 0.7365071283095723
Area Under Curve:    0.7295527551272548
(8094, 2560) (8094,)
Epoch 1/400
257/257 [==============================] - 2s 5ms/step - loss: 0.5913 - accuracy: 0.6829 - val_loss: 0.5533 - val_accuracy: 0.7143 - lr: 0.0010
Epoch 2/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5523 - accuracy: 0.7172 - val_loss: 0.5452 - val_accuracy: 0.7194 - lr: 0.0010
Epoch 3/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5381 - accuracy: 0.7277 - val_loss: 0.5444 - val_accuracy: 0.7176 - lr: 0.0010
Epoch 4/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.7344 - val_loss: 0.5442 - val_accuracy: 0.7231 - lr: 0.0010
Epoch 5/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5183 - accuracy: 0.7400 - val_loss: 0.5460 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/400
257/257 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.7483 - val_loss: 0.5422 - val_accuracy: 0.7257 - lr: 0.0010
Epoch 7/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4985 - accuracy: 0.7561 - val_loss: 0.5444 - val_accuracy: 0.7274 - lr: 0.0010
Epoch 8/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4876 - accuracy: 0.7632 - val_loss: 0.5485 - val_accuracy: 0.7234 - lr: 0.0010
Epoch 9/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7721 - val_loss: 0.5472 - val_accuracy: 0.7272 - lr: 0.0010
Epoch 10/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4635 - accuracy: 0.7810 - val_loss: 0.5559 - val_accuracy: 0.7223 - lr: 0.0010
Epoch 11/400
257/257 [==============================] - 1s 4ms/step - loss: 0.4524 - accuracy: 0.7893 - val_loss: 0.5553 - val_accuracy: 0.7248 - lr: 0.0010
Epoch 12/400
244/257 [===========================>..] - ETA: 0s - loss: 0.4401 - accuracy: 0.7966
Epoch 12: ReduceLROnPlateau reducing learning rate to 1.0000000474974512e-06.
257/257 [==============================] - 1s 4ms/step - loss: 0.4403 - accuracy: 0.7965 - val_loss: 0.5641 - val_accuracy: 0.7244 - lr: 0.0010
253/253 [==============================] - 0s 1ms/step
Independent Testing Matthews Correlation:  0.5037336448779226
Confusion Matrix :
 [[2993 1054]
 [ 955 3092]]
Accuracy on test set:    0.7517914504571287
Sensitivity:    0.7640227328885594 	 Specificity:    0.739560168025698
Precision  : 0.7457790641582248
Area Under Curve:    0.7517914504571287
(8094, 2560) (8094,)
Mean MCC = 0.4310 + 0.0285 and Mean AUC = 0.7154 + 0.0143
Mean Sensitivity = 0.7220 + 0.0183 and Mean Specificity = 0.7088 + 0.0227 and Mean Accuracy = 0.7154 + 0.0143
Mean Precision = 0.7129 + 0.0165

In [35]:
2+2

4

In [42]:
import os 
import pandas as pd
import numpy as np

os.chdir("/homes/t326h379/deepubi/download_12038_proteins/")

df_negative = pd.read_csv('Second_Final_DeepUbi_Negative_xtrimopglm_features.txt')

In [43]:
df_negative

,Q5AYD5,591,K,0.1416015625,0.004180908203125,0.73046875,-0.4296875,0.3828125,0.0021209716796875,0.0299072265625,...,0.0027923583984375,0.51171875.1,-0.392578125.1,-0.00653076171875.4,-0.56640625,-0.008056640625.4,-0.01495361328125,0.01483154296875.1,0.00927734375.4,0
0,P53336,90,K,0.060303,0.001869,0.316406,0.033936,-0.070801,-0.012573,0.007782,...,-0.000992,0.140625,-0.154297,0.002335,-0.101562,-0.005829,0.001198,-0.003052,0.003540,0
1,Q5BEV5,938,K,0.039307,-0.003296,0.519531,0.242188,-0.058838,-0.042236,0.030396,...,0.002151,0.170898,-0.433594,0.005096,0.069336,0.000097,0.006805,0.006561,-0.006073,0
2,F4JGB7,12,K,-0.000732,-0.002029,0.171875,0.157227,0.074219,0.012451,0.011841,...,0.001030,0.075684,0.033691,0.005798,-0.097168,-0.000443,0.007507,0.004883,0.007446,0
3,Q96IG2,25,K,-0.005005,-0.014709,1.468750,-0.174805,-0.115234,-0.060791,-0.009277,...,0.005707,1.101562,-1.296875,-0.009460,-0.074707,0.025757,-0.046387,0.018311,0.027954,0
4,P46677,558,K,-0.007935,0.007477,0.523438,-0.314453,0.120605,-0.018555,0.006897,...,-0.008057,0.941406,0.550781,-0.005524,-0.406250,-0.017578,-0.023560,0.002014,-0.006042,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43224,Q5B9P3,183,K,0.009277,0.000117,0.451172,-0.073242,0.005798,-0.005676,0.002258,...,0.004059,0.392578,0.318359,0.004944,-0.404297,-0.012207,0.001236,0.011658,-0.011841,0
43225,Q5B0N6,229,K,0.019287,-0.000622,-0.024780,-0.122559,0.174805,0.006744,0.005951,...,0.004089,0.040527,-0.453125,0.000893,-0.316406,0.007996,-0.008240,-0.001671,-0.006470,0
43226,Q5T6F2,167,K,0.010010,-0.001007,-0.261719,-0.020142,0.060303,-0.017944,0.003784,...,0.010254,-0.175781,-0.574219,-0.003769,-0.180664,-0.003708,-0.047119,0.009583,0.019531,0
43227,C8VRT7,467,K,-0.002686,0.001984,0.233398,0.074707,-0.212891,-0.007324,0.004089,...,0.001472,-0.453125,0.294922,0.000021,-0.106445,0.009705,0.014709,0.002533,-0.006104,0
43228,A0A0G2JV04,110,K,-0.031006,-0.008850,0.875000,-0.333984,0.308594,-0.001465,-0.030029,...,0.011353,0.925781,-1.359375,0.005951,1.093750,0.003708,-0.025269,0.009033,0.009827,0

In [41]:
df_negative

,Q5AYD5,591,K,0.1416015625,0.004180908203125,0.73046875,-0.4296875,0.3828125,0.0021209716796875,0.0299072265625,...,0.0027923583984375,0.51171875.1,-0.392578125.1,-0.00653076171875.4,-0.56640625,-0.008056640625.4,-0.01495361328125,0.01483154296875.1,0.00927734375.4,0
0,P53336,90,K,0.060303,0.001869,0.316406,0.033936,-0.070801,-0.012573,0.007782,...,-0.000992,0.140625,-0.154297,0.002335,-0.101562,-0.005829,0.001198,-0.003052,0.003540,0
1,Q5BEV5,938,K,0.039307,-0.003296,0.519531,0.242188,-0.058838,-0.042236,0.030396,...,0.002151,0.170898,-0.433594,0.005096,0.069336,0.000097,0.006805,0.006561,-0.006073,0
2,F4JGB7,12,K,-0.000732,-0.002029,0.171875,0.157227,0.074219,0.012451,0.011841,...,0.001030,0.075684,0.033691,0.005798,-0.097168,-0.000443,0.007507,0.004883,0.007446,0
3,Q96IG2,25,K,-0.005005,-0.014709,1.468750,-0.174805,-0.115234,-0.060791,-0.009277,...,0.005707,1.101562,-1.296875,-0.009460,-0.074707,0.025757,-0.046387,0.018311,0.027954,0
4,P46677,558,K,-0.007935,0.007477,0.523438,-0.314453,0.120605,-0.018555,0.006897,...,-0.008057,0.941406,0.550781,-0.005524,-0.406250,-0.017578,-0.023560,0.002014,-0.006042,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43224,Q5B9P3,183,K,0.009277,0.000117,0.451172,-0.073242,0.005798,-0.005676,0.002258,...,0.004059,0.392578,0.318359,0.004944,-0.404297,-0.012207,0.001236,0.011658,-0.011841,0
43225,Q5B0N6,229,K,0.019287,-0.000622,-0.024780,-0.122559,0.174805,0.006744,0.005951,...,0.004089,0.040527,-0.453125,0.000893,-0.316406,0.007996,-0.008240,-0.001671,-0.006470,0
43226,Q5T6F2,167,K,0.010010,-0.001007,-0.261719,-0.020142,0.060303,-0.017944,0.003784,...,0.010254,-0.175781,-0.574219,-0.003769,-0.180664,-0.003708,-0.047119,0.009583,0.019531,0
43227,C8VRT7,467,K,-0.002686,0.001984,0.233398,0.074707,-0.212891,-0.007324,0.004089,...,0.001472,-0.453125,0.294922,0.000021,-0.106445,0.009705,0.014709,0.002533,-0.006104,0
43228,A0A0G2JV04,110,K,-0.031006,-0.008850,0.875000,-0.333984,0.308594,-0.001465,-0.030029,...,0.011353,0.925781,-1.359375,0.005951,1.093750,0.003708,-0.025269,0.009033,0.009827,0

In [44]:
df_negative

,Q5AYD5,591,K,0.1416015625,0.004180908203125,0.73046875,-0.4296875,0.3828125,0.0021209716796875,0.0299072265625,...,0.0027923583984375,0.51171875.1,-0.392578125.1,-0.00653076171875.4,-0.56640625,-0.008056640625.4,-0.01495361328125,0.01483154296875.1,0.00927734375.4,0
0,P53336,90,K,0.060303,0.001869,0.316406,0.033936,-0.070801,-0.012573,0.007782,...,-0.000992,0.140625,-0.154297,0.002335,-0.101562,-0.005829,0.001198,-0.003052,0.003540,0
1,Q5BEV5,938,K,0.039307,-0.003296,0.519531,0.242188,-0.058838,-0.042236,0.030396,...,0.002151,0.170898,-0.433594,0.005096,0.069336,0.000097,0.006805,0.006561,-0.006073,0
2,F4JGB7,12,K,-0.000732,-0.002029,0.171875,0.157227,0.074219,0.012451,0.011841,...,0.001030,0.075684,0.033691,0.005798,-0.097168,-0.000443,0.007507,0.004883,0.007446,0
3,Q96IG2,25,K,-0.005005,-0.014709,1.468750,-0.174805,-0.115234,-0.060791,-0.009277,...,0.005707,1.101562,-1.296875,-0.009460,-0.074707,0.025757,-0.046387,0.018311,0.027954,0
4,P46677,558,K,-0.007935,0.007477,0.523438,-0.314453,0.120605,-0.018555,0.006897,...,-0.008057,0.941406,0.550781,-0.005524,-0.406250,-0.017578,-0.023560,0.002014,-0.006042,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43224,Q5B9P3,183,K,0.009277,0.000117,0.451172,-0.073242,0.005798,-0.005676,0.002258,...,0.004059,0.392578,0.318359,0.004944,-0.404297,-0.012207,0.001236,0.011658,-0.011841,0
43225,Q5B0N6,229,K,0.019287,-0.000622,-0.024780,-0.122559,0.174805,0.006744,0.005951,...,0.004089,0.040527,-0.453125,0.000893,-0.316406,0.007996,-0.008240,-0.001671,-0.006470,0
43226,Q5T6F2,167,K,0.010010,-0.001007,-0.261719,-0.020142,0.060303,-0.017944,0.003784,...,0.010254,-0.175781,-0.574219,-0.003769,-0.180664,-0.003708,-0.047119,0.009583,0.019531,0
43227,C8VRT7,467,K,-0.002686,0.001984,0.233398,0.074707,-0.212891,-0.007324,0.004089,...,0.001472,-0.453125,0.294922,0.000021,-0.106445,0.009705,0.014709,0.002533,-0.006104,0
43228,A0A0G2JV04,110,K,-0.031006,-0.008850,0.875000,-0.333984,0.308594,-0.001465,-0.030029,...,0.011353,0.925781,-1.359375,0.005951,1.093750,0.003708,-0.025269,0.009033,0.009827,0